### ISSUE TITLE
fish autocompletes a different filename than typed

### ISSUE THREAD

**Issue by emdete** [fish-shell/fish-shell#10001]
fish, version 3.6.1

Linux ... 6.3.0-1-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.3.7-1 (2023-06-12) x86_64 GNU/Linux

xterm-256color

 sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'

yes, same behaviour.

if i tab-complete a filename fish completes an uppercase name while i type exactly lowercase. it does so only if no lowercase filenames are available. i think this is a bit anoying, i dont like to be (awry) "corrected" while i know what i'm typing. i found this on a case sensitiv file system (and myself is so too).

**Comment by faho** [comment]
This is called "smart case" and it's on purpose.

You can undo a completion by pressing escape.
