### ISSUE TITLE
add default keybinding for delete horizontal space

### ISSUE THREAD

**Issue by polair** [fish-shell/fish-shell#10006]
In bash an emacs there is the ['delete-horizontal-space' function](https://unix.stackexchange.com/questions/595140/is-there-a-shortcut-to-delete-spaces-and-tabs-around-a-point-in-zsh) but I was unable to find an equivalent in fish. I'd be shocked if I'm the first person to consider this but it seems so? It's extremely useful to be able to [M-\] your way out of extra whitespace on either side of the cursor.

If someone can point me in the right direction I might be able to make a pull request and not put this on other folks. Thanks much.

**Comment by faho** [comment]
Fish's line editor isn't an arbitrary text editor, it's very much for editing commandlines. And I can't say in that context that I've really come across the case of having a lot of whitespace on both sides around my cursor.

Adding more and more and more input functions feels like it's awkward to maintain and of little use - I'm pretty sure we already have a bunch of functions that are essentially unused.

So I would instead ask you to write this as a script, and we'll add the *tools* to enable that.

Try something like this (lightly tested):

```fish
function remove_whitespace
    set -l pos (commandline --cursor)
    set -l before (string sub -l $pos -- "$(commandline)")
    set -l after (string sub -s (math $pos + 1) -- "$(commandline)")
    set before (string trim -r -- $before)
    set -l line "$before$(string trim -l -- $after)"
    commandline -r -- $line
    commandline -C (string length -- $before)
end

bind \e\] remove_whitespace # to bind it to alt+]
```

**Comment by polair** [comment]
@faho thank you very much for the thoughtful and detailed reply. I know that github issues being a dumping ground for things like this can be a little burdensome on the devs. 

That seems like a really nice solution. I am unqualified to evaluate your technical commentary but that seems like a reasonable line to draw. I'm adding this right now and I'll report back if I modify your suggestion further. 

Thanks again
