### ISSUE TITLE
Allow Multi-alias syntax

### ISSUE THREAD

**Issue by pehrlich** [fish-shell/fish-shell#1001]
I make typos a lot, and have developed this line in my old `~/.bash_profile` which helps out sometimes.  Unfortunately, that syntax is invalid for fish, requiring longhand.  A little inconvenience, but it would be nice to have both work.

```
# ~/.bash_profile:
alias dit='git' gid='git'  sit='git'  hit='git' gir='git' gut='git' giy='git' got='git' hiy='git'

# ~/.config/fish/config.fish 
alias dit='git' 
alias gid='git'  
alias sit='git'  
alias hit='git' 
alias gir='git' 
alias gut='git' 
alias giy='git' 
alias got='git' 
alias hiy='git'
```

Of course, I'm blown away by fish right now, I wouldn't be surprised if you had some sort of amazing auto-correct already built in :)

**Comment by faho** [comment]
Because we support both "key value" and "key=value" in alias, this seems indistinguishable.

With fish >= 2.3.0 however, you can move your aliases to a file in conf.d so your config.fish won't be so cluttered.

**Comment by concatime** [comment]
Thank you. I now have a file `aliases.fish` inside `~/.config/fish/conf.d`. It's alot simpler this way.
