### ISSUE TITLE
Backslash duplication in command history and variable expansion.

### ISSUE THREAD

**Issue by leg7** [fish-shell/fish-shell#10013]
fish, version 3.6.1
Linux eleum 6.1.51 #1-NixOS SMP PREEMPT_DYNAMIC Sat Sep  2 07:16:20 UTC 2023 x86_64 GNU/Linux
Default doesn't fix it.

I have multiple fuzzy finder functions which call find on my fs to get a list of directories or files I would like to open or whatever. All these functions use mostly the same find arugments to exclude directories and files from the search so that the list isn't littered with useless cache and git object files. I find myself often changing these find arguments and it's very annoying to have to go through every fuzzy function to change the same thing so I thought of factoring out these arguments into a universal variable in my `config.fish` like so.

```
if status is-interactive
	set -U fuzzy_exclude "\( -name '.mozilla' -o -name 'Signal' -o -name '.nix-defexpr' -o -regex '.*\(c\|C\)ache.*' -o -name '.git' \) -prune -o"

	for mode in default normal insert visual
		bind -M $mode \cf "printf '\n'; file-manager; commandline -f repaint"

		bind -M $mode \cs "printf '\n'; fuzzy-cd; commandline -f repaint" # s for switch or search
		bind -M $mode \ch "printf '\n'; fuzzy-history; commandline -f repaint"
		bind -M $mode \co "printf '\n'; fuzzy-open; commandline -f repaint"
		bind -M $mode \cp "printf '\n'; fuzzy-path; commandline -f repaint"
		bind -M $mode \ce "accept-autosuggestion" # e for expand
	end
end
```

Here is `fuzzy-cd` for example:
```
function fuzzy-cd
	set dir (find -L . "$fuzzy_exclude" -type d -print | fzf)/
	test -n "$dir" && c "$dir"
end
```

Now if I echo `$fuzzy_exclude` in my terminal the variable is displayed properly without backslash duplication but if I try and use the `fuzzy-cd` function the backslashes are all duplicated and the find command doesn't execute properly because of it.

```
[I] user@eleum ~/.config> 
find: ‘\\( -name '.mozilla' -o -name 'Signal' -o -name '.nix-defexpr' -o -regex '.*\\(c\\|C\\)ache.*' -o -name '.git' \\) -prune -o’: No such file or directory
```
Removing the quotes around `$fuzzy_exclude` don't fix the problem either

I noticed that in the fish command history file backslahes are also duplicated and maybe these two things are related. For example:
```
- cmd: find -L -not \\( -regex '\\.nix-defexpr|\\.git|cache' -prune \\) -type d
  when: 1694378401
```

**Comment by faho** [comment]
This is a simple misunderstanding of what quotes in fish do.

Let me start with an example: If you want to run `find` on the directories "foo" and "bar", you would run

```fish
find foo bar
```

If you want to store those directories in a variable, you would do

```fish
set -l dirs foo bar
find $dirs
```

No quotes anywhere. If, instead, you used quotes:

```fish
set -l dirs "foo bar"
find $dirs
# or find "$dirs"
```

then `find` would try to search the one directory "foo bar".

In fish, variables are split when they are *set*. This is unlike shells like bash, which have a major misfeature called "word splitting", where they'll take your variable and hack it into pieces except when you quote it.

If you set a variable like `'foo bar'`, then it will be used as one element, as if you had typed `'foo bar'`. If you want a variable to be passed as multiple arguments, you need to set it as multiple elements.

So:

>Removing the quotes around $fuzzy_exclude don't fix the problem either

You need to remove the quotes *both* around `"$fuzzy_exclude"` and around the `set` value:

```fish
set -U fuzzy_exclude \( -name '.mozilla' -o -name 'Signal' -o -name '.nix-defexpr' -o -regex '.*\(c\|C\)ache.*' -o -name '.git' \) -prune -o

# ...
set dir (find -L . $fuzzy_exclude -type d -print | fzf)/
```

**Comment by leg7** [comment]
Ok thanks a lot it works now. Sorry for the waste of time on such a simple question.
