### ISSUE TITLE
Bash set as $SHELL globally every time fish is started.

### ISSUE THREAD

**Issue by Taitep** [fish-shell/fish-shell#10025]
fish, version 3.6.1
Manjaro KDE Plasma.
Konsole, vscode and Alacritty are the terminals, no differences.
Not using third party customizations (starship) does not change anything.

If i open a fish instance and running `set -S SHELL` results in the following output:
```
$SHELL: set in global scope, exported, with 1 elements
$SHELL[1]: |/bin/bash|
$SHELL: set in universal scope, exported, with 1 elements
$SHELL[1]: |/bin/fish|
$SHELL: originally inherited as |/bin/bash|
```

Fish is my login shell.
Why is this? Why does fish want me to use bash, and can i change this behaviour?

**Comment by faho** [comment]
"$SHELL" is often misunderstood.

It's not set by the shell, it's set by "the system". When you login, it is set *before* the shell ever runs.

Fish does not set it, if you have run `chsh` to change it to fish (and then logged out and back in) and it's still set to bash something else on your system does.

>
Why is this? Why does fish want me to use bash, and can i change this behaviour?

"Fish" doesn't want you to use it, but it's *fine* to have it set to bash - it's frequently abused to run things in "the user's shell" by things that assume "the user's shell" can only ever be posix-compatible.
