### ISSUE TITLE
Command recognition is case-insensitive

### ISSUE THREAD

**Issue by jschank** [fish-shell/fish-shell#10028]
fish, version 3.6.1

Darwin Stormbringer.local 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000 arm64

Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:

  sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'

Issue does not occur when running the above command

When I type a command which is a function I've created, I notice that the fish parser recognizes the command as a valid command (color wise), but the command does not, in fact work.

For example I have a function named 'mobius'
at the prompt:
$ mobius <-- shows up as blue (which is correct)
$ mobyus <-- should up as red (which is correct)
$ Mobius <-- shows up as blue (which is - i think - incorrect)

I think the part that validates commands is cases insensitive, where as the actual interpretation is case sensitive

**Comment by faho** [comment]
Command recognition is simply looking up files on your filesytem.

And since you are on macOS, your filesystem is case-insensitive.

**Comment by faho** [comment]
Okay, I'm closing this because as far as I know it's not fixable.

If anyone knows a clean way to do it, feel free to comment and we'll reopen.
