### ISSUE TITLE
directories starting with hyphen "-" cause problems

### ISSUE THREAD

**Issue by cakeface** [fish-shell/fish-shell#10022]
Trying to operate on directories who's name starts with a hyphen does not seem to work. I'm unable to escape the name either. In a directory with a subdir named `-guide` I cannot run a wildcard command using `*`. I also tried renaming the file and I'm unable to even pass it in as a param to `mv`. Now, why someone thought to name a file starting with a hyphen I do not know. Not my first choice. But here I am with that file and I've got to be able to deal with it, right?

Thanks all - love Fish Shell!

```fish
(Corretto 17) ~/t/g/system-docs (main|✔)> ls
-guide/                            data-science/
(Corretto 17) ~/t/g/system-docs (main|✔)> du -sh *
du: invalid option -- u
usage: du [-Aclnx] [-H | -L | -P] [-g | -h | -k | -m] [-a | -s | -d depth] [-B blocksize] [-I mask] [-t threshold] [file ...]
(Corretto 17) ~/t/g/system-docs (main|✔)[64]> mv -guide guide
mv: illegal option -- g
usage: mv [-f | -i | -n] [-hv] source target
       mv [-f | -i | -n] [-v] source ... directory
(Corretto 17) ~/t/g/system-docs (main|✔)[64]> mv "-guide" guide
mv: illegal option -- g
usage: mv [-f | -i | -n] [-hv] source target
       mv [-f | -i | -n] [-v] source ... directory
(Corretto 17) ~/t/g/system-docs (main|✔)[64]> mv "\-guide" guide
mv: rename \-guide to guide: No such file or directory
```

macOS Ventura 13.5.2
```fish
(Corretto 17) ~/t/g/system-docs (main|✔)> uname -a
Darwin KWQF93TQ6Y 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64
(Corretto 17) ~/t/g/system-docs (main|✔)> fish --version
fish, version 3.6.1
(Corretto 17) ~/t/g/system-docs (main|✔)> echo $version
3.6.1
```

**Comment by faho** [comment]
This is an `mv` and `du` issue, not a fish issue. Fish simply passes the arguments as you gave them and has no influence otherwise.

Usually you can pass `--` to tell the command that the options stop there. Most common versions of most unix utilities support this. If that doesn't work you need to do something like `mv ./-guide guide`.

**Comment by zanchey** [comment]
See also #4959; I believe there was a patch to escape these files by default but it caused further problems. I can't find the discussion at present.

**Comment by faho** [comment]
> I believe there was a patch to escape these files by default

There was for *globs* - that's the `du *` case. It would pass them as `./-foo`.

This won't do anything for `mv -guide guide`, because there you're just passing it in a way that looks like an option. Fish would have to read your mind to know that it's not meant to be one.

>I can't find the discussion at present.

#1519
