### ISSUE TITLE
Last quote gets ommitted frequently by accident

### ISSUE THREAD

**Issue by madprops** [fish-shell/fish-shell#10031]
fish, version 3.6.1

When I'm writing commands like `program "some string"` something makes it seem like the final quote has been inserted, and when I hit enter I realize I forgot the quote. I think it's because the autocomplete shows a half-visible quote that I mistake for the real thing. I'm wondering if there's a way around this. Maybe a setting to not autocomplete `"` at the end?

**Comment by faho** [comment]
I would probably recommend setting the involved colors to something more obvious:

```fish
# The sugggestion
set -g fish_color_autosuggestion 444
# The quoted text
set -g fish_color_quote brblue
# The unclosed quote
set -g fish_color_error brred 
```

We don't really do settings like "don't suggest this specific thing", and the suggestion was *valid*.
