### ISSUE TITLE
No `fish_confg theme` command exists

### ISSUE THREAD

**Issue by Taitep** [fish-shell/fish-shell#10030]
I recently installed fish (3.3.1) on Pop!_OS on my laptop, and i am trying to install a theme. 
When i run `fish_config theme show` this is the result:
`No such subcommand: theme`

Why is this?? The theme does not show up in the web based config either. Also, when i try `fish_config --help` it does not even mention a `theme` -subcommand. Help me!!

**Comment by faho** [comment]
> I recently installed fish (3.3.1)

`fish_config theme` was [added in fish 3.4.0](https://fishshell.com/docs/current/relnotes.html#fish-3-4-0-released-march-12-2022), released in March 2022.

The current release is 3.6.1, fish 3.3.1 is about 15% of all commits ever made to fish behind.

I believe Pop!_OS is Ubuntu-compatible so you should be able to use the Ubuntu PPAs, see https://fishshell.com/.
