### ISSUE TITLE
string match exits with status 1 when piped into sed

### ISSUE THREAD

**Issue by adamhl8** [fish-shell/fish-shell#10047]
I'm using `string match` to get the latest release URL from GitHub like so:

```fish
$ curl -s https://api.github.com/repos/noah-nuebling/mac-mouse-fix/releases | string match -r "https://.*/download/.*MacMouseFixApp.*zip"
https://github.com/noah-nuebling/mac-mouse-fix/releases/download/3.0.0-Beta-6/MacMouseFixApp.zip
# more results...

$ echo $pipestatus
0 0
```

However, if I pipe this into sed (to get the first result), `string match` exits with a `1`:

```fish
$ curl -s https://api.github.com/repos/noah-nuebling/mac-mouse-fix/releases | string match -r "https://.*/download/.*MacMouseFixApp.*zip" | sed 1q
https://github.com/noah-nuebling/mac-mouse-fix/releases/download/3.0.0-Beta-6/MacMouseFixApp.zip

$ echo $pipestatus
0 1 0
```

If I pipe into, say, grep, it's fine:

```fish
$ curl -s https://api.github.com/repos/noah-nuebling/mac-mouse-fix/releases | string match -r "https://.*/download/.*MacMouseFixApp.*zip" | grep "github"
# results...

$ echo $pipestatus
0 0 0
```

Any ideas of what could be happening?

`fish, version 3.6.1`

**Comment by faho** [comment]
That `sed` will close the pipe after the first line, and the writing program will receive a signal (SIGPIPE) and typically quit. It is traditional to signal this with a falsy status (in fact the default behavior is to quit with 141 - 128 + the signal number of 13).

This is in fact the major issue with that "unofficial bash strict mode" of `set -euo pipefail`, and this is why you should see if things actually worked.

Which you're doing now, and I'm telling you that everything's working as intended. Just unix things.

**Comment by adamhl8** [comment]
I appreciate the explanation. Thanks!
