### ISSUE TITLE
Fish clears clipboard when opening new shell

### ISSUE THREAD

**Issue by bjarn** [fish-shell/fish-shell#10046]
**Fish version:** fish, version 3.6.1
**OS**: MacOS 14.0

**Issue:**
Whenever I open my terminal and start a new shell, Fish seems to clear my clipboard by copying an empty line. This is kinda annoying whenever I have a command on my clipboard.

Not experiencing this with bash/zsh. Happens every time I open a new shell. Noticed it with the default empty Fish config.

Reproducing is possible by copying something to your clipboard → open new shell → try to paste, it should be empty.

Not sure if it's intended or not, but I couldn't figure it out sadly 😬

**Current config:**
```
set fish_greeting
set N_PREFIX /opt/homebrew
set -x GPG_TTY (tty)
set -x GREP_OPTION --color=auto
set -x GOROOT (brew --prefix golang)/libexec
set -x GOPATH $HOME/go

set -x EDITOR vim

set -x LANG en_US.UTF-8
set -x LC_ALL en_US.UTF-8

set MANPATH $NPM_PACKAGES/share/man $MANPATH

set NPM_PACKAGES "$HOME/.npm-packages"

set -g fish_color_autosuggestion '555'  'brblack'
set -g fish_color_cancel -r
set -g fish_color_command --bold
set -g fish_color_comment red
set -g fish_color_cwd green
set -g fish_color_cwd_root red
set -g fish_color_end brmagenta
set -g fish_color_error brred
set -g fish_color_escape 'bryellow'  '--bold'
set -g fish_color_history_current --bold
set -g fish_color_host normal
set -g fish_color_match --background=brblue
set -g fish_color_normal normal
set -g fish_color_operator bryellow
set -g fish_color_param cyan
set -g fish_color_quote yellow
set -g fish_color_redirection brblue
set -g fish_color_search_match 'bryellow'  '--background=brblack'
set -g fish_color_selection 'white'  '--bold'  '--background=brblack'
set -g fish_color_user brgreen
set -g fish_color_valid_path --underline

status --is-interactive; and source (jump shell fish | psub)
status --is-interactive; and rbenv init - fish | source


# bun
set --export BUN_INSTALL "$HOME/.bun"
set --export PATH $BUN_INSTALL/bin $PATH

starship init fish | source
```

**Comment by faho** [comment]
> Reproducing is possible by copying something to your clipboard → open new shell → try to paste, it should be empty.

I can't reproduce this, please try without config.

Fish itself doesn't touch the clipboard unless you explicitly run the fish_clipboard_copy or fish_clipboard_paste functions.

**Comment by bjarn** [comment]
Ah, apologies. I missed my aliases.

I just discovered this alias:
```
abbr -a copykey command cat ~/.ssh/id_rsa.pub | pbcopy
```

Apparently, it automatically runs on opening a new shell (at least the pbcopy part), hence my clipboard becomes empty.

Apologies! I guess all is fine and intended.

**Comment by faho** [comment]
> Apparently, it automatically runs on opening a new shell (at least the pbcopy part), hence my clipboard becomes empty.

Well, yeah. This is a command with two parts: `abbr -a ...` and `pbcopy`, connected with a pipe.

That means both parts run, and the former prints no output.

You want:

```fish
abbr -a copykey 'command cat ~/.ssh/id_rsa.pub | pbcopy'
```

Run `abbr` with the arguments `-a`, `copykey` and `command cat ~/.ssh/id_rsa.pub | pbcopy`.
