### ISSUE TITLE
Fish does not execute "do script" apple event when starting

### ISSUE THREAD

**Issue by Jean-Daniel** [fish-shell/fish-shell#10048]
fish version 3.6.1 on macOS 14.0

When trying to execute some Apple Script supposed to launched a new Terminal window and run a command, it works fine with zsh, bash, and other shells, but fails with fish.

Try for instance to run the following AppleScript.

```
tell application "Terminal"
	do script "echo 'Hello World'"
end tell
```

It is supposed to open a new terminal window and immediately execute the command `echo Hello World`

When the default shell is zsh, (or bash, …) , it works as expected. When the shell is `fish`, it only open a new window, but the command is not run.

A subsequent call to the `do script` command passing a reference to the open window works though.

```
tell application "Terminal"
	set the_tab to do script "clear"
       do script "echo Hello World" in the_tab
end tell
```

It is unfortunate, as it breaks [csshx](https://github.com/brockgr/csshx) for instance.

**Comment by faho** [comment]
So, I have absolutely zero clue about Applescript, so forgive me for some extremely basic questions:

Does this *start the shell, run the script and then exit*, or does this start the shell, run the script and then leave the session open?

The former would just be run as `fish -c 'echo Hello World'`, just like for bash or zsh.

The latter wouldn't really be as easy - fish will run commands and then leave the session running if they are:

1. Directly on the commandline
2. In a config file, like config.fish
3. As a `--init-command`

You may notice that that's not the same list as bash/zsh, so if they do that I'd love to know what applescript does to make it so.

**Comment by Jean-Daniel** [comment]
I don't really know how it works under the hood, but in practice, the `do script` command will open a new Terminal window, and then execute the command in the newly opened window just like if you typed it in the shell.

The command is displayed in the window. For instance, when the shell is ZSH, this is what the terminal shows:

```
Last login: Sun Oct  8 17:32:18 on ttys000
echo Hello World                                                                                                                                                                                        
user@macbook ~ % echo Hello World
Hello World
user@macbook ~ % 
```

The second sample which specify the target window/tab just run the passed script in the existing window just like if it where typed in the terminal window and run.

```
Welcome to fish, the friendly interactive shell
user@macbook ~> echo Hello World
Hello World
user@macbook ~> 
```

It behaves like if the input is passed before fish is ready, and is discarded instead of being delayed. I'm not familiar enough with fish and other shell initialization to guess the problem origin.

**Comment by Jean-Daniel** [comment]
> I also notice you haven't filled out the issue template.
> 
> Have you tried this without configuration? What happens if you move config.fish aside?

I missed that question, the problem is the same when removing the whole .config/fish directory.

**Comment by faho** [comment]
Okay, I'm going to be honest here:

Someone needs to figure out what applescript does here, and what it expects. It's *possible* it enters the input like it's interactive input and that just happens earlier than fish is expected to handle input. Which would be quite unfortunate, because the solution would boil down to "be faster", and that's not all that easy.

I can't be of assistance here because I don't have a mac to test, and I don't even know where to look up documentation for this (and I wouldn't be surprised if this level isn't documented at all). So we need a mac user to look at this.

I'm going to leave this open for another week or so.

**Comment by Jean-Daniel** [comment]
> Okay, I'm going to be honest here:
>  It's _possible_ it enters the input like it's interactive input and that just happens earlier than fish is expected to handle input. Which would be quite unfortunate, because the solution would boil down to "be faster", and that's not all that easy.
> 

Not necessarily. As long as fish does not consume the input form `stdin`, it should remained buffered, and once it is ready, it should be able to consume it.
Is there something in fish initialization that may consume or flush stdin before it start waiting for user input ?

**Comment by Jean-Daniel** [comment]
Unfortunately, this is not so simple. I replace the shell by a simple `echo` command that read `stdin` and dump it in `stdout`, and it behaves like `fish`. The first `do script` command is ignored.

It also dumps argv, but it contains nothing but argv[0].

I will try to look a little more, but without great hope.

**Comment by Jean-Daniel** [comment]
OK. I ended up disassembling the Terminal to understand the issue, and it appears that it is the culprit.

It does not behave the same way when it starts a new window by executing a `shell` (like `zsh` or `bash`) and an other command, and the way it defines that a command is a `shell` is by parsing `/etc/shell`.

Adding `fish` full path into `/etc/shell` fixes the issue, as the Terminal now properly recognize it as a `shell`.
