### ISSUE TITLE
funced does not respect $EDITOR when called interactively

### ISSUE THREAD

**Issue by melhakim** [fish-shell/fish-shell#10053]
fish, version 3.6.1

Darwin 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6020 arm64

xterm-256color

`funced -i` does not spawn the editor even when `$EDITOR` and `$VISUAL` are set.
Note I have tried with `-e vim` and that _does_ work as expected.

**Comment by krobelus** [comment]
that's the point of `-i`. A `funced` without `-i` should start your editor

**Comment by faho** [comment]
The [documentation](https://fishshell.com/docs/current/cmds/funced.html) is clear on this:

> -i or --interactive
> Force opening the function body in the built-in editor even if $VISUAL or $EDITOR is defined.

But the *completions* aren't - https://github.com/fish-shell/fish-shell/blob/master/share/completions/funced.fish:

> 'Edit in interactive mode'

We can reword this - "Edit in fish instead of $EDITOR/$VISUAL"?
