### ISSUE TITLE
`read` scope (default behaviour)

### ISSUE THREAD

**Issue by gMan1990** [fish-shell/fish-shell#10061]
the documentation

`-U or --universal`
Causes the specified shell variable to be made universal.

`-g or --global`
Makes the variables global.

`-f or --function`
Scopes the variable to the currently executing function. It is erased when the function ends.

`-l or --local`
Scopes the variable to the currently executing block. It is erased when the block ends. Outside of a block, this is the same as --function.

fish-shell/fish-shell/issues/1862

**Comment by faho** [comment]
I'm afraid I don't see what you are asking here.

Can you clarify what you want?

**Comment by gMan1990** [comment]
@faho the documentation do not tell, which scope is the default.

**Comment by faho** [comment]
It is the same as for `set`. I'll add something to that effect.
