### ISSUE TITLE
Question: Why is command substitution is not equavalent to piping to xargs, in this case?

### ISSUE THREAD

**Issue by johannesCmayer** [fish-shell/fish-shell#10067]
fish, version 3.6.1
Linux Aqua 6.5.4-76060504-generic #202309191142~1695998943~22.04~070916d SMP PREEMPT_DYNAMIC Fri S x86_64 x86_64 x86_64 GNU/Linux
alacritty

This command works:
`vad timestamps input.mkv | xargs auto-editor input.mkv --mark-as-loud`

And this command does not:
`auto-editor input.mkv --mark-as-loud (vad timestamps input.mkv)`

I get the error by auto editor Error! Too few arguments for time_range.

I really don't understand why and would like to understand. [This](https://github.com/johannesCmayer/shell-fish-legs/blob/main/python/vad) is vad. The only important thing should be that it outputs a single line looking like `x1,y1 x2,y2 x3,y3 ...` where all x and y are start-end timestamps separated by a space, e.g. `0.1s,0.9s 2.1s,5.4s ...`. 

And [this](https://github.com/johannesCmayer/shell-fish-legs/blob/main/fish/process-conversations) is the entire script, though that should not be important really.

**Comment by faho** [comment]
https://fishshell.com/docs/current/faq.html#my-command-pkg-config-gives-its-output-as-a-single-long-string

Command substitutions split on newlines only. To split on other characters, use `string split`.
