### ISSUE TITLE
Bash syntax in git autocomplete

### ISSUE THREAD

**Issue by Falmarri** [fish-shell/fish-shell#10076]
https://github.com/fish-shell/fish-shell/blame/496fc03b9880891ea3da4989cee50cf7381e707c/share/completions/git.fish#L585

This line seems to be causing this error for me. Is this intentionally using $() syntax or is it a mistake?

`/usr/share/fish/completions/git.fish (line 573): $(...) is not supported. In fish, please use '(commandline)'`

**Comment by faho** [comment]
Your fish is outdated and you are using a newer sctiot. Please upgrade fish to >= [3.4.0](https://fishshell.com/docs/current/relnotes.html#fish-3-4-0-released-march-12-2022).

**Comment by Falmarri** [comment]
Ah, must be because I'm forced to use ubuntu jammy at work. Stupid ancient packages
