### ISSUE TITLE
Run command(1) by prepending ^ like in Nushell

### ISSUE THREAD

**Issue by codenyte** [fish-shell/fish-shell#10075]
So basically, we could steal that feature from Nushell where if you prepend `^` before an alias or function you defined (e.g. you have `alias ls exa` in your shell config but you want to run the actual `ls` binary on your system, so you type `^ls`). This is basically the same functionality as command(1) in fish shell, but `^` is just faster to type.

**Comment by faho** [comment]
Just use `command foo`, we try not to use sigils when we can.
