### ISSUE TITLE
fish: Unknown command: less

### ISSUE THREAD

**Issue by JQiue** [fish-shell/fish-shell#10074]
**YOUR TEXT HERE**
fish, version 3.6.1
Linux archlinux 6.5.9-arch2-1 #1 SMP PREEMPT_DYNAMIC Thu, 26 Oct 2023 00:52:20 +0000 x86_64 GNU/Linux

```sh
root@archlinux ~# history
fish: Unknown command: less
/usr/share/fish/functions/history.fish (line 105):
                builtin history search $search_mode $show_time $max_count $_flag_case_sensitive $_flag_reverse $_flag_null -- $argv | $pager
                                                                                                                                      ^~~~~^
in function 'history'
```

**Comment by faho** [comment]
This means that you do not have `less` installed or don't have it in your $PATH, and you don't have a $PAGER set.

The easiest fix is to install less, the second to install another pager and `set -g PAGER NameOfThatPager`.

I suppose we can make a nicer error or fall back to `cat`, but it's really a much nicer experience if you have a pager.
