### ISSUE TITLE
Allow # as an alias (zsh incompatible)

### ISSUE THREAD

**Issue by andrewgazelka** [fish-shell/fish-shell#10085]
```
fish, version 3.6.1
3.6.1
Darwin Andrews-MacBook-Pro.local 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:45 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T6020 arm64
```

Setting `#` as an alias does not work. I have tried through

```
alias # '/Users/andrewgazelka/Projects/playground/recommend/target/release/recommend'
alias '#'='/Users/andrewgazelka/Projects/playground/recommend/target/release/recommend'
```

the second which returns an error

```
- (line 2): 'end' outside of a block
        end
        ^~^
from sourcing file -
	called on line 70 of file /opt/homebrew/Cellar/fish/3.6.1/share/fish/functions/alias.fish
in function 'alias' with arguments '\#=/Users/andrewgazelka/Projects/playground/recommend/target/release/recommend'
	called on line 603 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
	called during startup
source: Error while reading file '<stdin>'
```

zsh (`zsh 5.9 (arm-apple-darwin22.1.0)`) this works fine 
`alias '#'="gpt-cli"`

Can this be added/fixed? I want it because `#` is the alias [Warp](https://www.warp.dev/warp-ai) uses for AI actions and want to emulate it in iTerm2

![image](https://github.com/fish-shell/fish-shell/assets/7644264/1c51a2c3-0051-4937-bf52-45b2787e885e)

**Comment by faho** [comment]
`#` is the comment symbol, so it's not allowed in function names.

Sorry.

**Comment by faho** [comment]
Nope, sorry: Like all issues with `alias`, this can be fixed by simply not using alias and defining a function instead:

```fish
function '#'
   whatever you want
end
```

Our valid characters here are broader than I assumed.
