### ISSUE TITLE
Builtin `functions/ls.fish` Is Globally Setting `LS_COLORS`

### ISSUE THREAD

**Issue by nlordell** [fish-shell/fish-shell#10080]
Fish provides a very helpful `ls`, however the current implementation will globally set and export `LS_COLORS` (`set -gx`), which may have unintended consequences with other CLI tools that use this environment variable (and has different semantics for `LS_COLORS` not set and `LS_COLORS=""`). In particular, this affects the output of `fd` which will use `LS_COLORS` if it is set.

<img width="418" alt="image" src="https://github.com/fish-shell/fish-shell/assets/4210206/f8cc4169-472c-4c75-aa53-0ecd2c0e7435">

Personally, although you can argue that this may not be a `fish` issue, but with the respective tools and how they deal with `LS_COLORS`, it _feels_ like `fish` should not be modifying the global environment with its builtin functions like `ls`, as it may cause some weird inconsistencies depending on whether or not `ls` has been called or not.

I don't mind contributing a fix for this (keep the scope of `LS_COLORS` being set limited to the `ls` function call but also potentially caching its generated value to avoid re-calling `dircolors` every time `ls` is invoked), but wanted to do a temperature check before working on it.

### Version

```
fish, version 3.6.1
```

Looking at [the source](https://github.com/fish-shell/fish-shell/blob/496fc03b9880891ea3da4989cee50cf7381e707c/share/functions/ls.fish#L12) it seems to still be the case on `master`.

**Comment by faho** [comment]
My preferred solution is to just get out of $LS_COLORS entirely - GNU ls and busybox ls will just use the defaults if it's unset. We'd have to check if other ls implementations are smart enough to figure it out. The function is annoyingly complicated as-is.

Barring that, we can do what you say and only set it in ls.

**Comment by faho** [comment]
FreeBSD's ls [has a default](https://man.freebsd.org/cgi/man.cgi?ls):

> The default is "exfxcxdxbxegedabagacad"

It also uses $LSCOLORS where we set $LS_COLORS (see the underscore), so we're probably just using the defaults there to begin with.

OpenBSD and NetBSD don't have color at all, but ship a "colorls" that apparently is just FreeBSD's ls.

macOS' ls is FreeBSD's.

That means the majority of implementations (GNU, busybox, BSD) is covered, and if someone has an ls that supports color but doesn't have a default value they need to set $LS_COLORS/$LSCOLORS themselves. 

I say we just nix `__fish_set_lscolors` entirely. This would affect people who set .dircolors but then expect it to be imported automatically, which I find an appropriate trade-off.

**Comment by SkySkimmer** [comment]
On my machine I don't have a .dircolors file but the ls defaults differ from what I get after using dircolors. For instance dircolors has `*.webm=01;35` so fish 3.6 ls would color webm files pink but fish 3.7 doesn't color them. Is that expected?

This is on debian testing.

**Comment by faho** [comment]
> Is that expected?

It is *possible* for dircolors to have different results.

It actually has the defaults compiled into the dircolors binary.

If you want these settings, you'll have to use `dircolors`, either on every startup or just save the string into config.fish.
