### ISSUE TITLE
dnf install completion error

### ISSUE THREAD

**Issue by dm1sh** [fish-shell/fish-shell#10096]
Typing the following in fish shell produces local files and directories list instead of available to install packages.

```fish
~> dnf install <TAB>
```
Trying to manually execute part of `__dnf_list_available_packages` gives an error like below.

```fish
~> sqlite3 /var/cache/dnf/packages.db "SELECT pkg FROM available WHERE pkg LIKE \"<package name>%\""
Error: in prepare, no such column: <package name>%
  SELECT pkg FROM available WHERE pkg LIKE "<package name>%"
                             error here ---^
```

It might be possible to resolve it replacing double quotation marks with single like below:

```fish
~> sqlite3 /var/cache/dnf/packages.db "SELECT pkg FROM available WHERE pkg LIKE '<package name>%'"
```
Running setup:

```
fish version: 3.6.1
uname -a: Linux fedora 6.5.11-300.fc39.x86_64 #1 SMP PREEMPT_DYNAMIC
OS: Fedora 39
Terminal: gnome-terminal
$TERM: xterm-256color
```

**Comment by faho** [comment]
For next time: If you have a simple PR ready, there's no need to file a separate issue.

All that does is require me to press the "close" button a second time.
