### ISSUE TITLE
`math` outputs a wrong number in `hex` format

### ISSUE THREAD

**Issue by NeumoNeumo** [fish-shell/fish-shell#10095]
## Reproduce
```bash
14:52:36 base ❯ math --base=16 "0x800000000"                              
0x0
```

## More information

My fish version is 
```bash
14:47:33 base ❯ fish --version                                                                                                                          
fish, version 3.3.1
```
This is my system:
![image](https://github.com/fish-shell/fish-shell/assets/107997665/352bed16-74ac-4911-a1ca-2703f2f88cfc)

**Comment by faho** [comment]
> fish, version 3.3.1

This fish version is 3 releases and about 15% of all commits ever made to fish behind.

Please upgrade and try again. I can not reproduce this with 3.6.1.
