### ISSUE TITLE
Allow use of `!!`

### ISSUE THREAD

**Issue by gregorni** [fish-shell/fish-shell#10091]
I'm on version 3.6.1 of fish, on Universal Blue (a community spin of Fedora Silverblue), using GNOME Terminal version 3.48.1.

Bash has this cool feature I like where you can type `!!` anywhere, and it'll substitute it for the previous command. This is useful for instance when you forgot to run a command with sudo:

```bash
rpm-ostree
sudo !! # This expands to `sudo rpm-ostree`
```

This doesn't even require a whitespace before:

```bash
stre
rpm-o!!e # This expands to `rpm-ostree`
```

I use this feature quite a lot, especially when a command tells me it requires sudo privileges. It would be cool it `fish` had something similar!

**Comment by faho** [comment]
[No thanks.](https://fishshell.com/docs/git/faq.html#why-doesn-t-history-substitution-etc-work)

**Comment by gregorni** [comment]
Ah, okay. That's reasonable. I guess I didn't do enough digging, sorry 😁

**Comment by lengyijun** [comment]
https://github.com/brewingweasel/fishbang

**Comment by wleoncio** [comment]
Link on https://github.com/fish-shell/fish-shell/issues/10091#issuecomment-1802665032 is dead. This one works for now: https://fishshell.com/docs/current/faq.html#why-doesn-t-history-substitution-etc-work

For anyone like me who basically only uses `!!` as in `sudo !!`, the link above mentions an easy alternative offered by vanilla Fish (TL;DR: press <kbd>Alt</kbd>+<kbd>s</kbd>):

> As a special case, most of the time history substitution is used as sudo !!. In that case just press Alt+S, and it will recall your last commandline with sudo prefixed (or toggle a sudo prefix on the current commandline if there is anything).
