### ISSUE TITLE
Fish hangs on launch

### ISSUE THREAD

**Issue by victorjacobs** [fish-shell/fish-shell#101]
When I try to launch Fish, it just sits there, doing nothing. It's not taking up any cpu cycles or anything. The only way I can close it is by using killall, it doesn't even respond to control-c.
I have tried compiling from source, to no avail.

I'm running Mac OS X 10.7.4 on a mid-2009 MacBook Pro.

I'm also very happy to help with any diagnostics, because I really want to try this out!

**Comment by faho** [comment]
fishd is dead now, so this is probably solved.

**Comment by ridiculousfish** [comment]
Yep, thanks
