### ISSUE TITLE
`command cd` does not work

### ISSUE THREAD

**Issue by REIS0** [fish-shell/fish-shell#10109]
Fish version: 3.6.1

When trying to use `command cd` in a script or anything else it doesn't work, it won't change to any directory, tried other commands and they work well, just `cd` seems to be acting weird.

To test just use `command cd` to any directory.

**Comment by faho** [comment]
"cd" needs to be a shell builtin. All it can do is change the directory of the current process.

If you run `command cd` that starts a new process, which changes its own directory and then quits.

macOS ships a /usr/bin/cd command that is almost entirely useless (at best it can be used to see if cd would succeed).

Use `builtin cd` or just plain `cd`.
