### ISSUE TITLE
type: Could not find 'sudo' on startup

### ISSUE THREAD

**Issue by phryk** [fish-shell/fish-shell#10117]
Fish: 3.6.1
Terminal: kitty 0.31.0
OS: FreeBSD 14.0-RELEASE
DE: X11/awesomewm
sudo: **not installed**

When I start a terminal, I get the following traceback:

```
type: Could not find 'sudo'
test: Expected a combining operator like '-a' at index 5
-n /usr/local/share/kitty/terminfo -a file =
                                           ^
Standard input (line 114): 
        and test -n "$TERMINFO" -a "file" = (type -t sudo)
            ^
in function '__ksi_schedule'
in event handler: handler for generic event 'fish_prompt'
```

This does **not** happen when:

* logging in on a TTY
* using xterm or urxvt (which don't set `$TERMINFO`)
* running `sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'`

At first, I suspected that this is another terlar-specific issue, but this problem
seems to occur no matter which prompt is used.

**Comment by faho** [comment]
This is a bug in kitty's integration, so it would have to be reported there.

I believe it should be fixed by https://github.com/kovidgoyal/kitty/commit/4c56e768401f920bb3ce129e1883810b7e6323f7.
