### ISSUE TITLE
Linux build error with 3.6.1: env_dispatch.cpp:467:73: error: ‘OK’ was not declared in this scope

### ISSUE THREAD

**Issue by satmandu** [fish-shell/fish-shell#10125]
Build error with 3.6.1 on ChromeOS/Chromebrew x86_64 and armv7l:
(Updating to 3.7.0 branch doesn't fix this.)
```
FAILED: CMakeFiles/fishlib.dir/src/env_dispatch.cpp.o
/usr/local/bin/c++ -DBINDIR=L\"/usr/local/bin\" -DCMAKE_BINARY_DIR=\"/usr/local/tmp/crew/fish.20231128173508.dir/builddir\" -DCMAKE_SOURCE_DIR=\"/usr/local/tmp/crew/fish.20231128173508.dir\" -DDATADIR=L\"/usr/local/share\" -DDOCDIR=L\"/usr/local/share/doc/fish\" -DLOCALEDIR=\"/usr/local/share/locale\" -DPREFIX=L\"/usr/local\" -DSYSCONFDIR=L\"/usr/local/etc\" -D_ATFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -D_REENTRANT -D_UNICODE=1 -I/usr/local/tmp/crew/fish.20231128173508.dir/builddir -lncurses -I/usr/local/include/ncurses -O2 -pipe -ffat-lto-objects -fPIC  -fuse-ld=mold  -flto=auto -Wredundant-move -O3 -DNDEBUG -std=gnu++11   -UNDEBUG -fdiagnostics-color=always -Wall -Wextra -Wno-comment -Wno-address -fno-exceptions -pthread -MD -MT CMakeFiles/fishlib.dir/src/env_dispatch.cpp.o -MF CMakeFiles/fishlib.dir/src/env_dispatch.cpp.o.d -o CMakeFiles/fishlib.dir/src/env_dispatch.cpp.o -c /usr/local/tmp/crew/fish.20231128173508.dir/src/env_dispatch.cpp
/usr/local/tmp/crew/fish.20231128173508.dir/src/env_dispatch.cpp: In function ‘void initialize_curses_using_fallbacks(const environment_t&)’:
/usr/local/tmp/crew/fish.20231128173508.dir/src/env_dispatch.cpp:467:73: error: ‘OK’ was not declared in this scope
  467 |         bool success = (setupterm(&term[0], STDOUT_FILENO, &err_ret) == OK);
      |                                                                         ^~
/usr/local/tmp/crew/fish.20231128173508.dir/src/env_dispatch.cpp: In function ‘void init_curses(const environment_t&)’:
/usr/local/tmp/crew/fish.20231128173508.dir/src/env_dispatch.cpp:580:56: error: ‘ERR’ was not declared in this scope
  580 |     if (setupterm(nullptr, STDOUT_FILENO, &err_ret) == ERR) {
      |                                                        ^~~
```

**Comment by faho** [comment]
This is defined by (n)curses, it appears your installation is broken.

**Comment by satmandu** [comment]
Hmm... We use a nonstandard install location off of /usr/local for everything... 

So the question is, what's causing the ncurses detection to break?

I've tried setting a `CURSES_INCLUDE_PATH`, set `C[XX]FLAGS` and `-DCMAKE_C[XX}_FLAGS` to have `-I/usr/local/include/ncurses`, and added `-Wl,-rpath/usr/local/lib64` to LDFLAGS.

**Comment by faho** [comment]
Fish uses CMake's find_package(curses). I'm reasonably sure you want CURSES_INCLUDE_DIRS and/or CMAKE_INCLUDE_PATH.

**Comment by faho** [comment]
Some curses implementations use a "char" in that place, and this is detected by compiling a snippet that assumes int: https://github.com/fish-shell/fish-shell/blob/f39bc9317d252ce2229ebc11a8a6fe2d98abf430/cmake/ConfigureChecks.cmake#L215-L229

It appears your configuration doesn't run that against the correct curses.

To be honest I would recommend just patching this out:

https://github.com/fish-shell/fish-shell/blob/f39bc9317d252ce2229ebc11a8a6fe2d98abf430/src/fallback.h#L47-L53

We're not going to be spending a lot more time on this because both cmake and C++ are on their way out of fish.

**Comment by satmandu** [comment]
Thanks for this completely unnecessary assistance here.

If cmake is on the way out, what's the preferred build method?

Happy to switch to rust so this isn't a one-off fix.

(I'm also rebuilding our ncurses package, since maybe this is a curses build issue on our end. Truly amazing how many hacks there are in getting ncurses installed... sigh.)

**Comment by faho** [comment]
> If cmake is on the way out, what's the preferred build method?

cmake is on its way out *by* switching to rust.

It's still the one and only build method for 3.6.x. It's just that making cmake much nicer *now* would be a bit of wasted effort.

**Comment by satmandu** [comment]
Yet another rebuild of `ncurses` and using `-DCURSES_INCLUDE_PATH=/usr/local/include/ncurses` fixed the build!

Thanks again!
