### ISSUE TITLE
Support search pattern in history-pager

### ISSUE THREAD

**Issue by shouya** [fish-shell/fish-shell#10131]
Fish version: 3.6.1

I just migrated from zsh to fish and was generally very happy with it. However, one feature I am missing a lot was the ability to type search patterns in the "reverse-i-search" (aka "history-pager" in fish, bound to <kbd>C-r</kbd> by default). Although this feature needs to be enabled by binding `history-incremental-pattern-search-backward` as described [here](https://unix.stackexchange.com/a/16629), I usually have it bound when configuring my zsh.

Put simply, this feature enables one to type the `*` as a wildcard during the incremental search session, which matches against arbitrary string. For example, input `A*B` matches string `AwhateverinbetweenBandpossiblemoreafterwards`.

Why is this feature so useful? Let me demonstrate a common use case. I typically have a lot of  `curl` commands in the history. Typically, I have quite a number of varying options between the `curl` command and the `<url>`. However, when I am trying to recall a specific history entry, I usually only remember the two pieces of information: `curl` and the domain name I want. This is when I would search for stuff like `curl*google` and hope the results to be narrowed down significantly.

Now without this feature, what I have to do is to type `C-r curl`, scroll through the myriads of irrelevant history, and hope to find what I want somewhere. If that fails, I may have to fall back to running `history search curl | grep google`, which is also quite a lot of keystrokes.

**Comment by krobelus** [comment]
yeah this sounds reasonable. A suggestion for the UI is https://github.com/fish-shell/fish-shell/pull/9451#issuecomment-1373446233
So a glob would match irrespective of word boundaries or newlines

**Comment by krobelus** [comment]
note that in latest master we already fall back to fuzzy search if there are no exact matches
(commit 00692bcdf (Include subsequence matches in history-pager, 2023-01-15)).
Maybe we still want globs

**Comment by shouya** [comment]
As for the suggested UI in https://github.com/fish-shell/fish-shell/pull/9451#issuecomment-1373446233, I personally prefer not requiring the `*` around the search term to trigger this (at least not the initial `*`). The reason is that it's often the case that one want to search something and find the input term not restrictive enough and need more terms to help narrow down. In this case, it would be a little inconvenient to:

1. go to the beginning of line, insert `*`,
2. go to the end of line, insert `*`
3. continue to type on whatever next term is.

I suggest the `*` to match arbitrary string by default. By which I mean `foo*bar` should correspond to regex `/foo.*bar/` instead of `^foo.*bar$`. And if one need to escape the wildcard character, they need to type `foo\*bar` in the search.

By extension, I think it's also natural to add zero-width deliminators like `^` and `$`. So `^foo` matches `/^foo/` as one may expect. Of course, `^` and `$` can be escaped with `\` as well.
