### ISSUE TITLE
Make echo support --

### ISSUE THREAD

**Issue by Undeterminant** [fish-shell/fish-shell#1013]
Splitting this conversation off of #1011: currently, `echo -- -n` doesn't work. It seems like it'd be a good thing to have, and we don't really need POSIX compatibility for it.

Yes/no?

**Comment by onodera-punpun** [comment]
+1 to this.

Since fish already doesn't follow POSIX I don't see a reason not to break another standard.

**Comment by krader1961** [comment]
This is a perfect example of a standard that merely codifies existing, bad, practice. IMHO any command that accepts options should support `--` to signal the end of options. Implementing this in fish should be very low risk as I suspect uses of `echo --` that want a literal double-dash echoed are extremely rare. I ran the following on OS X 10.11 and Ubuntu servers and found zero instances:

```
find / -type f -print0 | xargs -0 grep -h 'echo --'
```

The only matches were invocations like `echo --no-checkout` which would not be affected by this change.

**Comment by ridiculousfish** [comment]
@krader what do you think about respecting `--` only when it's literal, not when it's due to a variable expansion? That is:

````
    > echo --
    
    > set foo -- # set doesn't respect --!
    > echo $foo
    > --
````

Too surprising? Or not too unsurprising enough?

**Comment by krader1961** [comment]
I would argue that is too surprising because logically that behavior implies no options could be interpolated via var expansion. For example, what should happen if instead the user had done

```
set foo -n -- -s abc def
echo $foo
```

Should the `-n` be honored or not? What about the `-s`? I think this is another case where a user who cares and wants values in $foo that might look like options to be treated literally can either quote the expansion, `echo "$foo"`, or use the double-dash, `echo -- $foo`.

**Comment by krader1961** [comment]
Which raises another question: it appears that at present quoted strings that otherwise look like valid options are treated as options:

```
$ echo "-s" abc def
abcdef
```

That feels wrong but it changing it would probably be extremely dangerous terms of potentially breaking existing scripts.

**Comment by faho** [comment]
>Which raises another question: it appears that at present quoted strings that otherwise look like valid options are treated as options:

Well, that happens for everything else as well - `bash "--version"`. And the solution is the same basically everywhere - make the program not accept options (our printf works that way), or make it accept options only before or after  a certain delimiter, like "--".

>I would argue that is too surprising because logically that behavior implies no options could be interpolated via var expansion.

I agree with this. Principle of least surprise and such. That things can be interpreted as options is an unfortunate side-effect of the basic idea of shellscripting, we can't help that. But we can make it so that one way to avoid it works in as many ways as possible.

I mean I usually advocate for POSIX-compatibility at least when a tool looks like POSIX, but... nobody is using this "feature", it only makes them move away from echo (in favor of e.g. printf, a more complicated tool). This is one of those things that should have been guarded by POSIXLY_CORRECT/POSIX_ME_HARDER, to be forgotten like 512-byte units.

**Comment by krader1961** [comment]
Hmm, I'm not convinced the "posix-me-harder" label is appropriate since the whole point of this particular issue is to explicitly deviate from POSIX because it is brain-dead with respect to commands like `echo` not recognizing `--` to stop interpreting options :-)

**Comment by ridiculousfish** [comment]
PosixMeHarder tracks hilarious POSIX excesses, among other things. Some day I'm going to collect 'em all and make a blog post about it.

**Comment by pickfire** [comment]
@ridiculousfish, Nice job, I guess the Redox OS might have a few rare ones in the OS level.

**Comment by c22** [comment]
`echo -e '\x2dn'` no?

**Comment by krader1961** [comment]
@c22, What point are you trying to make? That `\x2d` (and \055) gets converted to a dash (`-`) isn't really relevant to this issue. This issue is discussing whether we want to maintain compatibility with POSIX 1003.1 vis-a-vis the `echo` command not recognizing the literal `--` to stop processing flags.

**Comment by c22** [comment]
Well I vote no, seeings it would serve no purpose other than being different to practically every other implementation of echo.

The point I am trying to make is that problem faced by OP is a non-issue which can be solved by escaping the hyphen character (the proposed solution of using `echo -s '' -n` has some side-effects).

Although If I were feeling particularly pedantic I'd say the mere existence of the `echo` built-in in fish shell goes against the law of orthogonality in the design principles when `printf` is a much more consistent alternative and most operating systems ship with `/bin/echo` as well.

**Comment by krader1961** [comment]
The original statement that  `echo -- -n` doesn't work is both wrong and ambiguous. It does work in as much as it writes `-- -n` to stdout and that is the correct behavior according to POSIX 1003.1 which we intentionally try to be compatible with vis-a-vis that specific command (but not with respect to other commands defined by POSIX 1003.1).

Despite my earlier comments that we should abandon POSIX 1003.1 compatibility in this instance I now believe doing so would cause more problems than it solves. As you, @c22, and everyone else has pointed out it is far too late in the evolution of fish to change the behavior of fish with respect to the `echo` command.

So I'm going to close this issue as "will not change" (or "fix").

**Comment by floam** [comment]
I'll point out that something other shells have done is providing a `print` builtin with the desired semantics and features.

**Comment by floam** [comment]
```console
$ print --man
NAME
  print - write arguments to standard output

SYNOPSIS
  print [ options ] [string ...]

DESCRIPTION
  By default, print writes each string operand to standard output and appends a
  newline character.

  Unless, the -r or -f option is specified, each \ character in each string
  operand is processed specially as follows:
    \a    Alert character.
    \b    Backspace character.
    \c    Terminate output without appending newline. The remaining string
          operands are ignored.
    \f    Formfeed character.
    \n    Newline character.
    \t    Tab character.
    \v    Vertical tab character.
    \\    Backslash character.
    \E    Escape character (ASCII octal 033).
    \0x   The 8-bit character whose ASCII code is the 1-, 2-, or 3-digit octal
          number x.

  If both -e and -r are specified, the last one specified is the one that is
  used.

  When the -f option is specified and there are more string operands than
  format specifiers, the format string is reprocessed from the beginning. If
  there are fewer string operands than format specifiers, then outputting will
  end at the first unneeded format specifier.

OPTIONS
  -e              Unless -f is specified, process \ sequences in each string
                  operand as described above. This is the default behavior.
  -n              Do not append a new-line character to the output.
  -f format       Write the string arguments using the format string format and
                  do not append a new-line. See printf for details on how to
                  specify format.
  -p              Write to the current co-process instead of standard output.
  -r              Do not process \ sequences in each string operand as
                  described above.
  -s              Write the output as an entry in the shell history file
                  instead of standard output.
  -u fd           Write to file descriptor number fd instead of standard
                  output. The default value is 1.
  -v              Treat each string as a variable name and write the value in
                  %B format. Cannot be used with -f.
  -C              Treat each string as a variable name and write the value in
                  %#B format. Cannot be used with -f.

EXIT STATUS
    0     Successful completion.
    >0    An error occurred.

SEE ALSO
  echo(1), printf(1), read(1)

IMPLEMENTATION
  version         print (AT&T Research) 2008-11-26
  author          David Korn <dgk@research.att.com>
  copyright       Copyright (c) 1982-2012 AT&T Intellectual Property
  license         http://www.eclipse.org/org/documents/epl-v10.html
$ print -- --
--
```

**Comment by floam** [comment]
On the one hand, we don't necessarily want three ways to print things, on the other I think some of these builtins we provide for compatibility or performance reasons that "have their hands tied" have to be an exemption to that rule - or we simply can't provide an ideal experience.
