### ISSUE TITLE
Release Notes web page does not include the latest releases

### ISSUE THREAD

**Issue by frazar** [fish-shell/fish-shell#10151]
```bash
$ fish --version
fish, version 3.6.4
$ echo $version
3.6.4
$ uname
Linux zardi-pc 6.1.66-1-lts #1 SMP PREEMPT_DYNAMIC Fri, 08 Dec 2023 13:04:53 +0000 x86_64 GNU/Linux
$ echo $TERM
xterm-256color
```

How to reproduce the problem: 
1. Go to the [GitHub Releases page](https://github.com/fish-shell/fish-shell/releases) and notice that the latest released versions are 3.6.4, 3.6.3, and 3.6.2. Also note that no release notes are available here.
2. Go to the [release notes page](https://fishshell.com/docs/current/relnotes.html) of the official website. 
3. Note that the release notes are not available for the latest releases (3.6.4, 3.6.3, and 3.6.2).

**Comment by zanchey** [comment]
Should be all there now.
