### ISSUE TITLE
Delete scrollback buffer with `Ctrl-l` regardless of what program you're running?

### ISSUE THREAD

**Issue by chriselrod** [fish-shell/fish-shell#10158]
I very much wish #2855 were still an "issue", as I very strongly prefer the scrollback buffer to get cleared.

For me, the primary point of `C-l` is to clear the scrollback buffer.
I work mostly in C++ and Julia, both of which give massive error messages that flood the screen. In both languages, the top of the message is way more important, helpful, and interesting than the bottom.

So my standard workflow is
1. `C-l`
2. Run a command that vomits a massive error message.
3. Jump to the top of the scrollback buffer to look at the important part.

If the scrollback buffer isn't cleared, it can be hard to find where one message ends and another begins! You have to scroll up a page at a time, and it is easy to miss.
Once upon a time, I pressed and held `return` to make a big enough gap that I actually had a chance spot it while scrolling up. Definitely not a workflow I'm going back to!!!

Anyway, [foot](https://codeberg.org/dnkl/foot/) does have a keybinding `C-Z` to jump to the previous REPL prompt, but this half works for C++ (it always undershoots the actual location for some reason, so I still need a couple `C-b`s to actually see the top), and of course doesn't work at all when running in a sub-REPL like Julia, as then I suddenly have a different REPL prompt (e.g., `julia> `).

I have this in my `config.fish`
```fish
bind \cl 'clear; commandline -f repaint'
```
but it only works if fish is the current active REPL. That is, if I start a Julia REPL from within fish, it will only clear the screen, and not the scrollback buffer, making it very hard to find the starts -- the important part -- of error messages.

Any suggestions here?

**Comment by krobelus** [comment]
I think you want to configure Julia REPL with the same binding. If they use readline you can use ~/.inputrc

**Comment by chriselrod** [comment]
I just tried
```fish
> cat ~/.inputrc
"\C-l":clear-display
```
This works for bash (while using `clear-screen` doesn't clear scrollback, for example), but not Julia. Seems that Julia may not use GNU readline. =(

**Comment by krobelus** [comment]
Maybe we should add

`bind \e\cL 'clear; commandline -f repaint'`

to match readline. (that key sequence is taken by KDE, Konsole uses Ctrl+Shift+K instead)

**Comment by krobelus** [comment]
https://docs.julialang.org/en/v1/stdlib/REPL/#Customizing-keybindings then

**Comment by faho** [comment]
Alright, I think we can call that one a julia question, then?

I think not clearing scrollback is a good default, and you already know how to change it. I don't think adding a binding for clearing it is a great idea, especially not on a key chord that obscure.
