### ISSUE TITLE
unset command not recognized 

### ISSUE THREAD

**Issue by drcid98** [fish-shell/fish-shell#10159]
Hello, i'm using fish version 3.6.4 in ubuntu 22.04.3 and I was trying to set en environmental variable. When i made a mistake in the name i tried to run `unset VARIABLE` and realized the unset command is not recognized by fish shell. I tried other shells like bash and dash and it is recognized, so the problem is definitely fish. Is there a reason for this? is there a workaround or should i just use other shell when I wand to run that command?

**Comment by zanchey** [comment]
Try using `set --erase VARIABLE`, or `set -e VARIABLE` for short.

**Comment by drcid98** [comment]
Thank you, it worked with `set -e VARIALBE`
