### ISSUE TITLE
abbr seems not to work as expected

### ISSUE THREAD

**Issue by componhead** [fish-shell/fish-shell#10166]
Fish abbr example seems not to work (https://asciinema.org/a/kBkduRxZd8e986iQlkcbAsRLU)
https://fishshell.com/docs/current/cmds/abbr.html

**Comment by faho** [comment]
You are using an outdated fish version - `abbr --position` is available since 3.6.0.

**Comment by componhead** [comment]
Excuse me. Have you seen asciinema? My version is 3.6.4
Have I misunderstood something?

thanks

**Comment by componhead** [comment]
the `echo $version` produce exactly the same result than `fish --version`

thanks

**Comment by faho** [comment]
What does `type abbr` say?

You probably have an abbr function left over from an older version, you want to remove it.

If I run `abbr -a --position anywhere -- -C --color`, copied from your asciinema, and run that in fish 3.6.4 it works.

**Comment by componhead** [comment]
> You probably have an abbr function left over from an older version, you want to remove it.

You are absolutely right. Thank you so much.
