### ISSUE TITLE
License file incomplete

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#10162]
I keep forgetting to log this, but it's something we should probably publicly address.

03a6fb4a69 erroneously removed a bunch of licensing information, and although we've put it back for the upcoming 3.7.0 (7f8d56da1675) and in the master branch for the Rust port (b1c06bbd2cae09), it's not been corrected anywhere else.

Do we want to...
 * make a blog post / post on the mailing list
 *  update the online documentation
 * other ideas?

**Comment by krobelus** [comment]
I think we can mention this in the "For distributors" changelog section, that should cover most practical consequences of the extra licenses

**Comment by zanchey** [comment]
I've added it to the release notes, and also made a post in the mailing list and on the blog. I think that's as much as I can do.
