### ISSUE TITLE
Ned two tries to cd in directory from stdin

### ISSUE THREAD

**Issue by Vilhelm-Ian** [fish-shell/fish-shell#10170]
fish, version 3.6.4

I am using Manjaro, kde, wayland,. I am not using any third party customazations. 

When I execute this chain of commands fd minecraft | fzf | read path | cd $path . I don't cd in to the path that I selct from fzf. But on the second try I am able to. This behaviour is consistent and it always works on the second try.

Mean while in nushell. fd minecraft | fzf | cd $in  .  Always works on the first try

**Comment by faho** [comment]
By the time `read` sets the variable, the `$path` in `cd $path` has already been expanded.

That's simply a misunderstanding. Use

```fish
cd (fd minecraft | fzf)
```

or

```fish
d minecraft | fzf | read path && cd $path
```

instead.

> Mean while in nushell

fish is not nushell. They use two different languages, with different semantics.

**Comment by Vilhelm-Ian** [comment]
@faho  Can you explain to me how it exactly works instead of pointing me to the documentation

**Comment by zanchey** [comment]
@Vilhelm-Ian [Parameter expansion](https://fishshell.com/docs/current/language.html#parameter-expansion) occurs before the job is executed; so the variable expansion of `cd $path` is done before the value of `$path` is set by the invocation of `read`.
