### ISSUE TITLE
`fish --no-execute` always adds a tilde for absolute paths

### ISSUE THREAD

**Issue by stephen-huan** [fish-shell/fish-shell#10171]
`fish --no-execute` always adds a tilde when ran on an absolute path. 

For example, suppose `~/temp.fish`  (`/home/ikue/temp.fish`) has the contents

```fish
echo "$$"
```

Giving an absolute path always adds a tile, as shown by running `fish --no-execute /home/ikue/temp.fish`
```text
~/home/ikue/temp.fish (line 1): $$ is not the pid. In fish, please use $fish_pid.
echo "$$"
       ^
warning: Error while reading file /home/ikue/temp.fish
```

Note the extra tilde in `~/home/ikue/temp.fish` now refers to a non-existent file.

This happens for every absolute path I tried, for example, with `temp.fish` at `/`, `fish --no-execute /temp.fish` returns

```
~/temp.fish (line 1): $$ is not the pid. In fish, please use $fish_pid.
echo "$$"
       ^
warning: Error while reading file /temp.fish
```

Relative paths work correctly, for example, `fish --no-execute temp.fish` reports

```text
temp.fish (line 1): $$ is not the pid. In fish, please use $fish_pid.
echo "$$"
       ^
warning: Error while reading file temp.fish
```

(note that the path is `temp.fish`). Running `fish --no-execute ./temp.fish` reports

```text
./temp.fish (line 1): $$ is not the pid. In fish, please use $fish_pid.
echo "$$"
       ^
warning: Error while reading file ./temp.fish
```

(note that the path has changed to `./temp.fish`). 

This is minor, but it can lead to linters dropping the error messages, for example, in [nvim-lint](https://github.com/mfussenegger/nvim-lint/issues/495).

```fish
fish --version
fish, version 3.6.4
echo $version
3.6.4
uname -a
Linux sora 6.1.68 #1-NixOS SMP PREEMPT_DYNAMIC Wed Dec 13 17:39:30 UTC 2023 x86_64 GNU/Linux
echo $TERM
alacritty
```

**Comment by faho** [comment]
Turns out this tried to replace $HOME with "~", only because it's no-execute it didn't *have* a $HOME and so used the empty string.

(@zanchey: Already backported to 3.7.0)
