### ISSUE TITLE
set_color creates extra space

### ISSUE THREAD

**Issue by rackodo** [fish-shell/fish-shell#10176]
|Fish Version         |OS                 |Terminal|$TERM           |
|---------------------|-------------------|--------|----------------|
|`fish, version 3.6.4`|`macOS Sonoma 14.2`|`iTerm2`|`xterm-256color`|

**Issue:** set_color creates whitespaces.
**Steps to reproduce:** Follow the example for [fish_greeting](https://fishshell.com/docs/current/cmds/fish_greeting.html).

Expected outcome:
![carbon-4](https://github.com/fish-shell/fish-shell/assets/42397332/8c8059a2-b672-4ef7-9cb4-24a76975a17d)

Actual outcome:
![carbon-5](https://github.com/fish-shell/fish-shell/assets/42397332/29dbcc30-e248-4c9b-83c3-045eaa745a2b)

It's not a critical issue, I'm aware, but the extra space is a little distracting.
(Carbon was used to replicate screenshots, but I can promise their accuracy.)

**Comment by zanchey** [comment]
Excitingly, this does not happen in git main as of , but the `set_color` invocation does not work quite right (eg `echo What color is the date\? (set_color yellow; date +%T; set_color blue)` has a blue date, not a yellow one).

**Comment by rackodo** [comment]
Weird... that's not what happens for me.

<img width="922" alt="Screenshot 2023-12-31 at 2 38 02 pm" src="https://github.com/fish-shell/fish-shell/assets/42397332/9f3c19ee-db6e-468b-8153-0a21f8f15f00">

(I know the text doesn't look blue, but that's what blue is in my palette.)

**Comment by zanchey** [comment]
Sorry, I see the behaviour you describe, but only on 3.6.4 and not in main, where it is different but also wrong.

**Comment by rackodo** [comment]
Is 3.6.4 not the latest release...? I tried upgrading fish (using Homebrew) but 3.6.4 is the latest version available. Or is main not the same?

**Comment by zanchey** [comment]
3.6.4 is the most recent release, but main includes a substantial port of the internals of fish, which has fixed some longstanding bugs but also introduced new ones.

**Comment by krobelus** [comment]
the color change bisects to ce559bc20ef13f35a941fcb5e504d325cb63d10b (cc @mqudsi)

**Comment by krobelus** [comment]
I've fixed the color.

The extra space happens because

	$ echo (echo 1; set_color blue) 2

is equivalent* to

	$ echo (echo 1; echo -n \e\[34m) 2

or

	$ echo (echo 1\n\e\[34m) 2

fish trims trailing newlines from command substitution output.
There is no trailing newline here. `echo` will print both lines separated by a space. The second line is empty.

We could try to remove the last \n if it's followed by only invisible character sequences but that sounds confusing.
Probably best to work around it on your end

(*) found with

	$ set_color blue | string escape
	\e\[34m⏎

**Comment by zanchey** [comment]
Possibly we should fix the tutorial, but it's inelegant. `echo The time is (set_color yellow)(date +%T)(set_color normal) now` is the best I can do, but runs into our old friend Cartesian expansion if `set_color` produces no output.
