### ISSUE TITLE
Bad unicode handling in interactive command line

### ISSUE THREAD

**Issue by shouya** [fish-shell/fish-shell#10173]
```
$ fish --version
fish, version 3.6.1-1053-gb9f17ca1f
```

Reproduction step:

- Copy and paste this character (U+FF1B) to fish command line: `：`
- Observe the character is not shown up as it should.

Furthermore, if this character appears in the completion, the the interactive feature is broken, too.

I bisected the commits and found the bug was introduced in https://github.com/fish-shell/fish-shell/commit/31ad182aa50b2fade99a1549256d40c0a33676d7.

Upon further digging into the issue, I found that any unicode characters after the codepoint 豈 (U+F900) are not displayed correctly after this commit.

**Comment by shouya** [comment]
I may have found the culprit.

https://github.com/fish-shell/fish-shell/blob/master/fish-rust/src/fallback.rs#L67-L69

After commenting out this condition, everything is working as expected. The comment refers me to https://github.com/fish-shell/fish-shell/issues/8275 where the issue was fixed by https://github.com/fish-shell/fish-shell/commit/29413665c55b2597d875f715a6ee601be4d518c8#diff-94a17ee8c3788476d8b05db18fd383ad2739fb6be8390f723571ae3784dda93dR267.

- In the cpp version, the range was: `if (wc >= 0x1F3FB && wc <= 0x1F3FF)`.
- In the rs version, the range was: `if ('\u{F3FB}'..='\u{1F3FF}').contains(&c)`.

Looks like a typo for me.

**Comment by krobelus** [comment]
thanks!
