### ISSUE TITLE
Copy file with argument like '*.sql' only copy first matched file in self-defined function

### ISSUE THREAD

**Issue by jonahfang** [fish-shell/fish-shell#10172]
fish version: 3.6..4

Here is my self-defined function:

```fish
function cptoc
   cp $argv[1] /mnt/c/Users/FANGZX/aa/
end
```

When I use it like this, it only copy s0.sql file (also s1.sql, s2.sql exists):

```
cptoc *.sql
```

**Comment by faho** [comment]
Here's your problem: `$argv[1]`.

That means the first argument.

**Comment by jonahfang** [comment]
@faho, '*.sql' is the first argument

**Comment by zanchey** [comment]
The shell will expand `*.sql` to a list of all files matching that pattern, and then pass that to the function, so the function arguments are actually "`1.sql 2.sql 3.sql`" and so on. Use `$argv`, not `$argv[1]`.

**Comment by jonahfang** [comment]
Thanks! It works.
