### ISSUE TITLE
Call fish_prompt after printing 'Job has ended'

### ISSUE THREAD

**Issue by maxfl** [fish-shell/fish-shell#1018]
If there is a number of background jobs printed in fish_prompt, it's not updated when some job ends. It seems that fish simply redraws the last prompt while it could call fish_prompt again.

**Comment by krobelus** [comment]
With #6959 fish can be configured to do this by adding overriding `fish_job_summary` to add `commandline -f repaint` to . Maybe this should be the default.

**Comment by zanchey** [comment]
@krobelus, that sounds sensible to me.
