### ISSUE TITLE
abbr position in strings

### ISSUE THREAD

**Issue by componhead** [fish-shell/fish-shell#10191]
Hi. I'm trying to use an abbreviation like this:
```abbr -a gbr --position anywhere --function current_git_branch```
and it works well, except when I use it in a string like that:
```git commit -m 'Issue blah blah gbr'```

Is it intentional? There is a sort of workaround about that?

thank you

**Comment by faho** [comment]
If you use it like that, the abbr's name is also what the entire token must be.

This is on purpose, imagine if you made an abbr "m" and then typed any word that includes an "m".

If you want more flexible matching, you should use the `--regex`. That can then match the token, e.g. `--regex '.*gbr.*'`.

This will give the entire matching token to your function. Note that whatever the function prints will replace the entire token, so you should replace what you want.

E.g.

```fish
function current_git_branch
    set -l branch (git branch | string match -rg '\* (.*)')
    string replace -r 'gbr' (string escape -- $branch) -- $argv[1]
end
```

**Comment by componhead** [comment]
Wow! Thank you. Now is more clear.
