### ISSUE TITLE
Double quote behavior in fish, version 3.7.0

### ISSUE THREAD

**Issue by v217** [fish-shell/fish-shell#10206]
If you run
```
builtin echo "aaa{$HOME}b bb"
```
you get
```
aaa{/var/home/v}b bb
```
however, naively as an enduser you would expect to get
```
aaa/var/home/vb bb
```

Probably there are technical reasons, why the later result is desirable?
But I could not find it documented anywhere.
Thanks!

**Comment by faho** [comment]
Braces simply aren't special in double quotes.

As [the documentation says](https://fishshell.com/docs/current/language.html#quotes):

> Between double quotes, fish only performs [variable expansion](https://fishshell.com/docs/current/language.html#expand-variable) and [command substitution](https://fishshell.com/docs/current/language.html#expand-command-substitution) in the $(command). No other kind of expansion (including [brace expansion](https://fishshell.com/docs/current/language.html#expand-brace) or parameter expansion) is performed

**Comment by v217** [comment]
Thank you for clarifying my confusion!
