### ISSUE TITLE
Make error for % as argument as verbose as $ as an argument

### ISSUE THREAD

**Issue by Undeterminant** [fish-shell/fish-shell#1020]
Example:

`echo $`:

fish: The “$” begins a variable name. It was given at the end of an argument. Variable names may not be zero characters long. To learn more about variable expansion in fish, type “help expand-variable”.

`echo %`:

fish: Could not expand string “%”

**Comment by krader1961** [comment]
This has been addressed:

```
$ echo %
Unable to find a process ''
fish: echo %
            ^
```
