### ISSUE TITLE
Fish git compiler error on Archlinux / Orange pi 5

### ISSUE THREAD

**Issue by freqmod** [fish-shell/fish-shell#10214]
Fish git compiler error on Archlinux / Orange pi 5

 I guess i can hack this to work myself (seems like libc and rust are disagreeing on signed vs unsigned char), but this compiles on x86 arch for me so i thought it might be useful to know in case you want to make the code more robust / portable.

[freqmod@fvop bld]$ git rev-parse HEAD
40feed56cfc082bea689772bc6c260b092853ce0
[freqmod@fvop bld]$ pacman -Q --info glibc
Navn                   : glibc
Versjon                : 2.35-5.1
Beskrivelse            : GNU C Library
Arkitektur             : aarch64
[freqmod@fvop bld]$ rustup show
Default host: aarch64-unknown-linux-gnu
rustup home:  /home/freqmod/.rustup

stable-aarch64-unknown-linux-gnu (default)
rustc 1.75.0 (82e1608df 2023-12-21)

[0/13] cd /mnt/rp4e/t/fish-shell && /usr/bin/cmake -E env FISH_BUILD_DIR=/mnt/rp4e/t/fish-shell/bld PREFI...t-dir /mnt/rp4e/t/fish-shell/bld/./cargo/build --release --config foo=0 -- -Cdefault-linker-libraries=yes
    Updating git repository `https://github.com/mqudsi/rsconf`
   Compiling syn v1.0.109
   Compiling cc v1.0.79 (https://github.com/mqudsi/cc-rs?branch=fish#cdc3a376)
   Compiling rsconf v0.1.0 (https://github.com/mqudsi/rsconf?branch=master#39b6841b)
   Compiling fish-rust v0.1.0 (/mnt/rp4e/t/fish-shell)
   Compiling git-version-macro v0.3.5
   Compiling num-derive v0.3.3
   Compiling widestring-suffix v0.1.0 (/mnt/rp4e/t/fish-shell/fish-rust/widestring-suffix)
   Compiling git-version v0.3.5
error[E0308]: mismatched types
   --> fish-rust/src/env/environment.rs:816:33
    |
816 |     _PATH_BSHELL.store(unsafe { C_PATH_BSHELL().cast_mut() }, Ordering::SeqCst);
    |                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `*mut i8`, found `*mut u8`
    |
    = note: expected raw pointer `*mut i8`
               found raw pointer `*mut u8`

error[E0308]: mismatched types
    --> fish-rust/src/exec.rs:413:54
     |
413  |             argv2[1..argv.len() + 1].copy_from_slice(argv);
     |                                      --------------- ^^^^ expected `&[*const i8]`, found `&[*const u8]`
     |                                      |
     |                                      arguments to this method are incorrect
     |
     = note: expected reference `&[*const i8]`
                found reference `&[*const u8]`
note: method defined here
    --> /home/freqmod/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/slice/mod.rs:3661:12
     |
3661 |     pub fn copy_from_slice(&mut self, src: &[T])
     |            ^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> fish-rust/src/exec.rs:416:24
    |
416 |             argv2[1] = actual_cmd.as_ptr();
    |             --------   ^^^^^^^^^^^^^^^^^^^ expected `*const i8`, found `*const u8`
    |             |
    |             expected due to the type of this binding
    |
    = note: expected raw pointer `*const i8`
               found raw pointer `*const u8`

error[E0308]: arguments to this function are incorrect
   --> fish-rust/src/exec.rs:418:17
    |
418 |                 libc::execve(_PATH_BSHELL.load(Ordering::Relaxed), &argv2[0], envv.get());
    |                 ^^^^^^^^^^^^
    |
note: expected `*const u8`, found `*mut i8`
   --> fish-rust/src/exec.rs:418:30
    |
418 |                 libc::execve(_PATH_BSHELL.load(Ordering::Relaxed), &argv2[0], envv.get());
    |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: expected raw pointer `*const u8`
               found raw pointer `*mut i8`
note: expected `*const *const u8`, found `&*const i8`
   --> fish-rust/src/exec.rs:418:68
    |
418 |                 libc::execve(_PATH_BSHELL.load(Ordering::Relaxed), &argv2[0], envv.get());
    |                                                                    ^^^^^^^^^
    = note: expected raw pointer `*const *const u8`
                 found reference `&*const i8`
note: function defined here
   --> /home/freqmod/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.147/src/unix/mod.rs:887:12
    |
887 |     pub fn execve(
    |            ^^^^^^

error[E0308]: mismatched types
    --> fish-rust/src/fork_exec/spawn.rs:204:21
     |
202  |                 libc::posix_spawn(
     |                 ----------------- arguments to this function are incorrect
203  |                     &mut pid,
204  |                     _PATH_BSHELL.load(Ordering::Relaxed),
     |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `*const u8`, found `*mut i8`
     |
     = note: expected raw pointer `*const u8`
                found raw pointer `*mut i8`
note: function defined here
    --> /home/freqmod/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libc-0.2.147/src/unix/linux_like/linux/mod.rs:4690:12
     |
4690 |     pub fn posix_spawn(
     |            ^^^^^^^^^^^

For more information about this error, try `rustc --explain E0308`.
error: could not compile `fish-rust` (lib) due to 5 previous errors
[3/13] cd /mnt/rp4e/t/fish-shell && /mnt/rp4e/t/fish-shell/build_tools/git_version_gen.sh /mnt/rp4e/t/fish-shell/bld
FISH_BUILD_VERSION=3.7.0-1209-g40feed56c
FAILED: CMakeFiles/_cargo-build_fish-rust /mnt/rp4e/t/fish-shell/bld/CMakeFiles/_cargo-build_fish-rust
cd /mnt/rp4e/t/fish-shell && /usr/bin/cmake -E env FISH_BUILD_DIR=/mnt/rp4e/t/fish-shell/bld PREFIX=/usr/local CMAKE_WITH_GETTEXT=1 DOCDIR=/usr/local/share/doc/fish DATADIR=/usr/local/share SYSCONFDIR=/usr/local/e
tc BINDIR=/usr/local/bin LOCALEDIR=/usr/local/share/locale CURSES_LIBRARY_LIST=/usr/lib/libcurses.so,/usr/lib/libtinfo.so CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=c++ CORROSION_BUILD_DIR=/mnt/rp4e/t/fish-shel
l/bld CARGO_BUILD_RUSTC=/home/freqmod/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/bin/rustc /home/freqmod/.rustup/toolchains/stable-aarch64-unknown-linux-gnu/bin/cargo rustc --lib --target=aarch64-unknown-
linux-gnu --package fish-rust --manifest-path /mnt/rp4e/t/fish-shell/Cargo.toml --target-dir /mnt/rp4e/t/fish-shell/bld/./cargo/build --release --config foo=0 -- -Cdefault-linker-libraries=yes
ninja: build stopped: subcommand failed.

**Comment by krobelus** [comment]
is this fixed if you pull latest master and apply

```diff
diff --git a/src/libc.rs b/src/libc.rs
index 144201f37..857112b11 100644
--- a/src/libc.rs
+++ b/src/libc.rs
@@ -31,7 +31,7 @@ extern "C" {
     fn C_CS_PATH() -> i32;
 }
 
-pub static _PATH_BSHELL: AtomicPtr<i8> = AtomicPtr::new(std::ptr::null_mut());
+pub static _PATH_BSHELL: AtomicPtr<c_char> = AtomicPtr::new(std::ptr::null_mut());
 extern "C" {
     pub fn C_PATH_BSHELL() -> *const c_char;
 }
 ```

?

**Comment by faho** [comment]
Is PATH_BSHELL ever not "/bin/sh" anywhere? I would be in favor of just hardcoding that, tbh.

**Comment by krobelus** [comment]
yeah we can do that

**Comment by freqmod** [comment]
using c_char as you suggested works.

**Comment by zanchey** [comment]
This is a good find, thank you!
