### ISSUE TITLE
Mark indicators appear in iTerm2 with fish 3.7.0

### ISSUE THREAD

**Issue by dnicolson** [fish-shell/fish-shell#10215]
After updating from fish 3.6.4, mark indicators appear on the first line in iTerm2.
<img width="697" alt="Screenshot 2024-01-14 at 21 11 06" src="https://github.com/fish-shell/fish-shell/assets/2276355/25713399-eaca-49d5-bd9c-af88adafc98a">

This can be disabled easily in iTerm2 via the "Show mark indicators" setting but I am wondering what changes in fish 3.7.0 are causing this (or if it's intentional), there have been many changes since fish 3.6.4. Ideally, being able to disable this in the fish config would be preferable.

`Darwin Daves-MacBook-Pro.local 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64`
`xterm-256color`

**Comment by faho** [comment]
This is iterm's [shell integration](https://iterm2.com/documentation-shell-integration.html) adding it to your prompt.

There's nothing fish can really do about other tools injecting config, you'll have to disable it there.

**Comment by dnicolson** [comment]
Yes, that part is clear.

I'm wondering what change in fish 3.7.0 could trigger this though, and if it's an intended change?

**Comment by faho** [comment]
There is no specifically intended change in fish 3.7.0 to do anything here, and nothing about [the script](https://iterm2.com/shell_integration/fish) jumps out.

The only iterm-related changes in 3.7.0 are that we now enable cursor shaping for vi-mode and PWD reporting.

It's *possible* iTerm doesn't want to show the prompt mark if the shell doesn't also tell it the PWD.

**Comment by dnicolson** [comment]
Thanks for the info @faho, I'll take a deeper look into iTerm2.
