### ISSUE TITLE
`ctrl+s` no longer focuses the search box

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#10220]
Using https://github.com/fish-shell/fish-shell/commit/fdc45452b6ba04a9d8d0e478b3e2048aeacabd97

---

I _may_ be wrong about this, but I'm pretty sure that in previous versions of fish I was able to:

```
$ ls <TAB>
# 1. `ctrl+s` to bring up search
# 2. start typing
# 3. see results being filtered
```

This seems to have changed (or my memory fails me), in that there is now an extra step required:

```
$ ls <TAB>
# 1. `ctrl+s` to bring up search
# 2. press the down arrow to focus the search input
# 3. start typing
# 4. see results being filtered
```

Would it be possible to eliminate the 2nd step? I'm pretty sure it used to work as I described in my first example, but it's possible I've misremembered.

If I ever hit `ctrl+s`, it's because I want to begin searching immediately. I don't want to have to hit another key before I'm able to start searching.

**Comment by faho** [comment]
Cause is a simple boolean confusion:

https://github.com/fish-shell/fish-shell/blob/fdc45452b6ba04a9d8d0e478b3e2048aeacabd97/src/reader.rs#L2184

vs

https://github.com/fish-shell/fish-shell/blob/0e4d088b116f8455ed604be117ea78831b2cdfc5/src/reader.cpp#L3580

**Comment by IlanCosman** [comment]
@faho Huh, maybe I'm off base, but `self.is_navigating_pager_contents()` sure sounds like a fix for https://github.com/fish-shell/fish-shell/discussions/10167 😄 Is that correct?

**Comment by faho** [comment]
@IlanCosman If it was exposed, yeah
