### ISSUE TITLE
abbr and pipesign doesnt work as expected

### ISSUE THREAD

**Issue by emdete** [fish-shell/fish-shell#10240]
i'm using fish, version 3.7.0 on Arch Linux

if i have an abbr like

```
abbr -a -- l 'ls -l'
```

and type `l|`without a space the abbreviation doesn't get expanded (same with `&`,  `<` and `>`) while blanks and return work fine. shouldn't these characters considered as endings as well or is a space required?

**Comment by faho** [comment]
Duplicate of #9730
