### ISSUE TITLE
`command` doesn't work properly when ran from a variable

### ISSUE THREAD

**Issue by SArpnt** [fish-shell/fish-shell#10248]
using fish version 3.7.0 on arch linux with the zen kernel in foot terminal

same behavior happens without customizations

most commands you can run by putting the arguments in a variable and running the variable, for example:
```
set -gx EDITOR kak -c global
$EDITOR
```

in my case because of muscle memory i want to alias `kak` to $EDITOR, but that causes a loop, so i used `command kak -c global` instead. what i found is that command seems to somehow handle the arguments improperly when ran from a variable.

```
> command echo test
test
> set -l var command echo test
> $var

command - run a program

command [OPTIONS] [COMMANDNAME [ARG ...]]
```
(the documentation continues)

```
> command kak -c global
```
(runs kakoune as normal)
```
> set -gx EDITOR command kak -c global
> $EDITOR
command: -c: unknown option

(Type 'help command' for related documentation)
```

```
> set -l com command
> $com kak -c global
command: -c: unknown option

(Type 'help command' for related documentation)
```

**Comment by faho** [comment]
You want either `command $EDITOR` or `set -gx EDITOR (command -s kak) -c global`.

The reason `command foo` doesn't work in a variable is because it's syntactically important, just like e.g. `if` won't work there.

**Comment by SArpnt** [comment]
could this give a better error message?

**Comment by faho** [comment]
`command` is both a keyword (for `command foo`) and a builtin (for `command --search foo` and `command --help`).

What you are running is effectively `builtin command kak -c` because it skips the keyword step.

**Comment by krobelus** [comment]
maybe we can make it a regular builtin, I don't off-hand see an advantage to decorators being keywords except maybe easier implementation. Things like `if` are different because it kind of needs to be known before variable expansion.

**Comment by faho** [comment]
Even if we did that, setting $EDITOR like that would still be a bad idea - it's also used outside of fish, and e.g. `git` sure won't know what a `command kak` is.
