### ISSUE TITLE
You cannot type CTRL+[ using \c notation

### ISSUE THREAD

**Issue by xfix** [fish-shell/fish-shell#1024]
> &lt;haarts> or why doesn't "bind \c\[ some_function" work?

If I write `\c[`, I get following error.

```
fish: Tokenizer error: 'Unexpected end of string, square brackets do not match'
echo \c[
     ^
```

If I write `\c\[`, I actually get Control+\ and [, not Control+[ that could be expected.

**Comment by faho** [comment]
This seems to be working for me now, with the "\". Without it, fish throws an error about unmatched brackets, but that's a different thing.
