### ISSUE TITLE
Automatically quote URLs pasted to shell

### ISSUE THREAD

**Issue by strct** [fish-shell/fish-shell#10258]
fish, version 3.7.0

When I want to curl or yt-dlp an URL, I regularly paste it in my console. But sometimes URLs contain `&` or `?`. And then I additionally need to quote the URL with single quote characters `'`. I was wondering whether that quoting could be automatically done by fish if I paste an http(s) URL into my console?

**Comment by faho** [comment]
Enter a single-quote and *then* paste, fish will escape any `'` and `\` pasted within single-quotes.
