### ISSUE TITLE
Fish is not very usable within "win" dumb terminal emulator of Acme text editor

### ISSUE THREAD

**Issue by alurm** [fish-shell/fish-shell#10259]
**Summary**

```
> fish --version
fish, version 3.7.0
> echo $version
3.7.0
> uname -a
Linux host 6.6.10_1 #1 SMP PREEMPT_DYNAMIC Fri Jan  5 22:14:25 UTC 2024 x86_64 GNU/Linux
> echo $TERM
dumb
> echo $NO_COLOR
1
```

**Image**

![image](https://github.com/fish-shell/fish-shell/assets/108410815/aeaf7213-1677-4594-800b-3f450acf8d5f)

**Description**

I entered all commands only once. The problem should be evident: Fish makes assumptions about the terminal being smart, but the terminal emulator provided by Acme by default (the `win` command) does not support ANSI escape codes.

**Reproduction steps**

- Install a Unix system, supporting plan9port.
- Install plan9port.
- Launch Acme (`acme`).
- Anywhere, type `win sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'`.
- Select the whole text that you just wrote.
- Middle click on this text. An interactive window connected to Fish will appears, if done properly.
- Move the mouse pointer anywhere in the window.
- Type Fish commands. Notice how the text is drawn multiple times, and ANSI codes are emitted constantly, despite TERM being dumb and NO_COLOR being set.

**Comment by faho** [comment]
Basically every other terminal on the planet handles this, so I'm going to say that we appear to simply not target ACME.

Sorry.

> NO_COLOR being set

Fish does not support NO_COLOR.

**Comment by alurm** [comment]
Understandable.
