### ISSUE TITLE
Shell environment can't detect current directory being removed and recreated

### ISSUE THREAD

**Issue by alxhill** [fish-shell/fish-shell#10273]
Ran into the following situation on macOS recently:
- Had an external drive mounted (at say `/Volumes/MyDrive/`) and a terminal window cded into it somewhere
- Ejected the external drive
- Re-inserted it, mounting at the exact same location

Commands like `brew install` no longer work as the shell believes there's no current working directory, even though `ls` and `pwd` return the expected path. Example:
```
# /Volumes/MyDrive/blah exists on the external drive, and the shell session has been open during an eject/mount cycle.

/V/M/blah> brew install test
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
Error: The current working directory must exist to run brew.
/V/M/blah [127]> ls
/V/M/blah> pwd
/Volumes/MyDrive/blah
```

This is with fish 3.3.1 using macOS Sonoma.

The issue can be resolved by cding to the same directory again, and seems unrelated to the separate volume part (deleting & recreating a normal folder exhibits the same behavior) - but it's more unexpected when dealing with an external mount.

**Comment by faho** [comment]
> Commands like brew install no longer work as the shell believes there's no current working directory

No, *brew* doesn't believe there is. The error message you get comes from that, not fish.

And like you see, both `ls` (another external command) and fish's builtin `pwd` handle this just fine, brew is overly naive.

> This is with fish 3.3.1 using macOS Sonoma.

Sidenote: fish 3.3.1 is 15% of all commits ever made to fish behind (counting up to the last release). Please upgrade if you wish to report an issue.

**Comment by alxhill** [comment]
Both `ls` and `pwd` "work" _even if the current directory has been deleted_, so I figured they were doing something else. `brew` is not the only tool that broke in this case, but it was the only one I had logs handy for - plus the `shell-init` error made me think it could be a shell thing. Anyway, thanks for taking a look!

I've verified the same behavior occurs on fish 3.7.0 fwiw.
