### ISSUE TITLE
alias vi to neovide and something unexpected will happen.

### ISSUE THREAD

**Issue by LeeeSe** [fish-shell/fish-shell#10275]
**YOUR TEXT HERE**
fish, version 3.6.4

macOS14  alacritty and rio or Terminal.app all have this problem

when i alias 
```
alias vi="neovide"
```

when i input `vi /` ,the neovide GUI will automatically pop up
<img width="691" alt="image" src="https://github.com/fish-shell/fish-shell/assets/44465325/087b83e5-e2f9-440a-90fe-6f6438fa2699">

But when I type `neovide /`, nothing happens.
<img width="812" alt="image" src="https://github.com/fish-shell/fish-shell/assets/44465325/1c3a9656-2bef-4156-ab86-df764fa5a6f8">

**Comment by faho** [comment]
Fish vi completions check if your vi is really vim by running `vi --help`:

https://github.com/fish-shell/fish-shell/blob/cb46396b677cde80c654c1e89903f1c193d82ca5/share/completions/vi.fish#L6-L10

It appears neovide just ignores `--help`. This isn't really something we can support, in general fish's completions assume that a thing called "vi" will behave roughly *like* "vi".

So the solution is to simply: Don't alias neovide to "vi".

If you wish to take this upstream, tell neovide to support "--help" by printing something to the terminal and exiting.

**Comment by LeeeSe** [comment]
Thank you for your reply, I understand.
