### ISSUE TITLE
[feature request] make path component separators customizable

### ISSUE THREAD

**Issue by quantenzitrone** [fish-shell/fish-shell#10271]
Currently, the characters that separate path components as used by `backward-path-component` are hard-coded:

https://github.com/fish-shell/fish-shell/blob/05ac1b770cd2b576323e40000561f1fdfe3ade56/src/tokenizer.rs#L1264-L1266

It'd be nice if that could be customized. 
Specifically, I would like to add `#` as a path component separator, because on NixOS with flakes `#` is used as a separator between the flake and the selected package from the flake. e.g. `nix profile install nixpkgs#fish`

```sh
$ fish --version
fish, version 3.7.0
$ echo $version
3.7.0
$ echo $TERM
alacritty
$ uname -a
Linux laptop 6.1.70-xanmod1 #1-NixOS SMP PREEMPT_DYNAMIC Tue Jan  1 00:00:00 UTC 1980 x86_64 GNU/Linux
```

**Comment by faho** [comment]
We don't tend to make things like that configurable. Options are often an awkward compromise to be reached when people can't agree on what the correct behavior is, just so they can get what they want and everyone else is left with more complexity.

What I'm going to do instead is to add `#` to that list.
