### ISSUE TITLE
Autosuggestions are sometimes not offered after recalling a previous line from history

### ISSUE THREAD

**Issue by simonborje** [fish-shell/fish-shell#10287]
fish, version 3.7.0 built from source, but it behaves the same on the packaged "atp" version 3.6.0
OS: debian 12

I'm not quite sure if this behavior is a bug or intentional but I found it unexpected at least.
When recalling commands from history by using the "up arrow" and then continuing typing, fish will not offer any autosuggestions unless the history search is first cancelled. The history search seems to be canceled by several actions such as pressing left arrow, "space" or "backspace", but not by typing regular characters.

In the example below the two final lines which uses "up arrow" history search are not offered autosuggestions after the search until the left arrow is pressed.
In the last line the history search match highlight is also not cleared until the left arrow is pressed.
![WindowsTerminal_roMGHXCp0Z](https://github.com/fish-shell/fish-shell/assets/3867784/56b18dee-c385-42b9-824c-45a7b62d8e2c)
If this is considered a bug I could attempt to create a fix.

**Comment by faho** [comment]
Let's see what happens if we end history search if you insert characters.

It doesn't seem *useful* to leave it open because it doesn't change the search string, so it feels wrong.
