### ISSUE TITLE
no documentation for `argparse --exclusive`

### ISSUE THREAD

**Issue by thor314** [fish-shell/fish-shell#10284]
There is no documentation for the exclusive flag, and every pattern I've tried with it appears to error: `exclusive flag 'bin' is not valid`.

Expected use:
```fish
function f 
  argparse --exclusive 'b/bin,l/lib' -- $argv
  echo $_flag_l $_flag_b
end
```

**Comment by faho** [comment]
The little documentation [there is](https://fishshell.com/docs/current/cmds/argparse.html#options) says:

> -x or --exclusive OPTIONS

> A comma separated list of options that are mutually exclusive. You can use this more than once to define multiple sets of mutually exclusive options.

What this means is that you define *which* of your options conflict with each other. You'll still need to define them as options to argparse, and it only wants the short or the long part, not the full opt-spec.

So you would do something like

```fish
argparse --exclusive bin,lib b/bin l/lib -- $argv
```

and if you give it `--bin -l` it will then give an error telling you that those two options "cannot be used together".

I guess we can explain that and add an example.
