### ISSUE TITLE
rbenv completion is weird when ruby-build is not installed

### ISSUE THREAD

**Issue by mdesantis** [fish-shell/fish-shell#1028]
I have fish shell installed from package repository and rbenv installed in my user home (not from package repository) and ruby-build installed as rbenv plugin (so the `ruby-build` command doesn't exist).

When I tab `rbenv install`:

```
$ rbenv install<tab> Il programma "ruby-build" non è attualmente installato. È possibile installarlo digitando:
sudo apt-get install ruby-build
/usr/share/fish/completions/rbenv.fish (line 31): ruby-build --definitions
                                                  ^
in function “__fish_rbenv_official_rubies”,
	called on standard input,

in command substitution
	called on standard input,


1.8.6-p383  1.9.2-p0    1.9.3-p385      2.0.0-rc2       jruby-1.7.0-preview1  rbx-2.0.0-dev    
...
```

As you see, it displays a Ubuntu message telling me I should install `ruby-build`; then the completion works (I guess because of the user local rbenv which loads its completion).

I tried to mitigate the issue using the `command --erase` option; but without success. Isn't that option for me? How should it be used?

**Comment by dgutov** [comment]
+1

Installing `ruby-build` as a plugin is actually the norm.

**Comment by faho** [comment]
How does one do the equivalent of `ruby-build --definitions` if it is installed as a plugin? `rbenv install --definitions`? It'd be sad to lose completions if ruby-build is installed as recommended.

**Comment by dgutov** [comment]
```sh
rbenv install --list
```

See https://github.com/sstephenson/ruby-build#using-rbenv-install-with-rbenv

**Comment by faho** [comment]
Thanks. I hope this is now fixed, and that the order (use ruby-build if available, do rbenv install --list if not) is okay.

**Comment by dgutov** [comment]
`rbenv install --list` outputs a list where each entry is indented with two spaces. It seems that they are carried over to completions as well.

Or at least that happened when I copied over your changes to my locally installed version of Fish.

**Comment by faho** [comment]
So you get output like

```
  2
  3
  4
```

which results in completion options looking like

```
\ \ 2
\ \ 3
\ \ 4
```

?

**Comment by dgutov** [comment]
Yes.

**Comment by faho** [comment]
Try this in rbenv.fish then:

```fish
function __fish_rbenv_official_rubies
	if command -s ruby-build >/dev/null
		# echo it to remove leading spaces
		ruby-build --definitions | while read -l def
			echo $def
		end
	else
		rbenv install --list
	end
end
```

**Comment by dgutov** [comment]
* It's the wrong case: I'm using `ruby-build` installed as a plugin.
* Moving the piping to the `else` block doesn't help either, though:

```
rbenv install --list | while read -l def
    echo $def
end
```

still creates output where each line starts with two spaces.

**Comment by faho** [comment]
>It's the wrong case: I'm using ruby-build installed as a plugin.

Um yeah, sorry about that.

>Moving the piping to the else block doesn't help either, though:

Damn - fish's sane wordsplitting rules foiled my clever trick! So sed it is (note: we could also use `cut`, but that would require hardcoding the exact number of spaces, and that they are, in fact, spaces)

```fish
rbenv install --list | sed "s/^[[:space:]]*//"
```

(this is a prime candidate for the `string` stuff so we can skip the fork, but that's not merged yet)

**Comment by dgutov** [comment]
That works, thanks!

**Comment by faho** [comment]
Pushed in 2587bbc4a768ed7097e35cf87d43203ff94aa961. Thanks for your assistance!
