### ISSUE TITLE
How to replace multi-line string variable in shell script

### ISSUE THREAD

**Issue by vivuu1989** [fish-shell/fish-shell#10292]
In order to parse a YAML file, we are using the solution provided [here][1] and which is working as expected for us to generate the variables in the key value pairs of YAMD. Now when we are trying to replace the variable values to a specic part of the `policy.xml` file, we are not able to achieve this where we need multi-line values with special characters in them.

The script part which I tried is as below

    #!/bin/bash
    source parse_yaml.sh
    eval $(parse_yaml sample2.yaml policy)
    
    echo ".............Eval Result..............................."
    for f in $policy_ ; do eval echo \$f \$${f}_ ; done
    echo "............Eval Result................................"
    
    for f in $policy_ ; do
      if [[ $(eval echo \$${f}_name) == "ipfilter" ]]; then
        echo " given policy name is ipfilter "
        for g in $(eval echo \$${f}_session_); do
          if [[ $(eval echo \$${g}) == "inbound" ]]; then
          echo "add the add above Ipfilter string to the inbound session of xml"
          fi
          if [[ $(eval echo \$${g}) == "outbound" ]]; then
          echo "add the add above Ipfilter string to the outbound session of xml"
          fi
          if [[ $(eval echo \$${g}) == "backend" ]]; then
          echo "add the add above Ipfilter string to the backend session of xml"
          fi
        done
        for h in $(eval echo \$${f}_api_); do
          echo "decided the scope of Ipfilter policy as $(eval echo \$${h})"
        done
        for i in $(eval echo \$${f}_operations_); do
          echo "decided the scope of Ipfilter policy as $(eval echo \$${i})"
        done
      fi
    done

Policy:

    - name: policy1
      session:
         - inbound
         - backend
      api:
	     - api1
		 - api2
      customvalue1: xxxxx
      customvalue2: xxxxx
    
    - name: policy2
      session:
         - inbound
         - backend
      operation:
         - operation1
         - operation2
      customvalue3: xxxxx
      customvalue4: xxxxx
    
(etc)

`policy.xml` needs to be modified with the multi-line strings as per the above script conditions.

    <policies>
        <inbound>
            <base />
    		 $(ip_filter)
             $(rate-limit-by_ip)
    		 $(rate-limit-by_subkey)
    		 $(rate-limit-by_DevID)
    		 $(rate-limit-by_ip)+$(rate-limit-by_DevID)
        </inbound>
        <backend>
            <base />
    		 $(ip_filter)
             $(rate-limit-by_ip)
    		 $(rate-limit-by_subkey)
    		 $(rate-limit-by_DevID)
    		 $(rate-limit-by_ip)+$(rate-limit-by_DevID)
        </backend>
        <outbound>
            <base />
    		 $(ip_filter)
             $(rate-limit-by_ip)
    		 $(rate-limit-by_subkey)
    		 $(rate-limit-by_DevID)
    		 $(rate-limit-by_ip)+$(rate-limit-by_DevID)
        </outbound>
        <on-error>
            <base />
    		 $(rate-limit-by-ip_error)
    		 $(rate-limit-by_DevID_error) 
        </on-error>
    </policies>

Variable example:

    rate-limit-by_ip=<rate-limit-by-key calls="${callThreshold}$" renewal-period="60" counter-key="@(Regex.Match(context.Request.Headers.GetValueOrDefault(&quot;X-Forwarded-For&quot;,&quot;&quot;), @&quot;^[.0-9]*&quot;)?.Value)" />

Like above the are several variable for each policy and we need to replace them in the exact postion, also the custom values passed (variable callthreshold) also need to be replaced with their values.

  [1]: https://github.com/mrbaseman/parse_yaml

**Comment by faho** [comment]
Sorry, I don't understand what your question is.

>The script part which I tried is as below

This is a bash script. You can continue running it, and it will run with bash and do whatever it should do in bash.

It runs

```fish
source parse_yaml.sh
eval $(parse_yaml sample2.yaml policy)
```

which reads a bash script as bash code and then runs it and reads its output as bash code again. That won't work translated to fish.

If you want to keep it as a bash script that's fine, but then you should ask someone about writing a bash script in which case this is the wrong place to ask.

If you want to translate it to fish, you need to translate parse_yaml.sh first or figure out how to run it so you just get its output.

----

Personally, I would recommend writing this as a python script instead. YAML has data structures that are not easily usable in shell script, whether that's fish or bash.

**Comment by faho** [comment]
Alright, I don't believe this problem has anything to do with fish.
