### ISSUE TITLE
Special character in universal variable results in warning message on startup ("Unable to parse universal variable message")

### ISSUE THREAD

**Issue by nrnrnr** [fish-shell/fish-shell#10313]
I'm running fish 3.7.0 on Debian Linux under `xterm` ($TERM is `xterm-256color`).

Uname reports
```
Linux homedog 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux
```

I tried fish with this command

    sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'

and the effect on behavior is explained below as described in an "empty home tree."

To reproduce the problem:

```
$ set -U barf "tr"\xfc"mper"
$ fish
warning: Unable to parse universal variable message: 'SETUVAR barf:tr\uf6fcmper'
Welcome to fish, the friendly interactive shell
$
```
When the universal variable is written into `fish_variables`, the character `\xfc` is escaped into something that fish thinks is a `fish_reserved_codepoint`.

When I do the same thing with an empty home tree, I don't get the warning message, but the universal variable `barf` is incorrectly set to the empty string.

**Comment by faho** [comment]
> When I do the same thing with an empty home tree, I don't get the warning message, but the universal variable barf is incorrectly set to the empty string.

No, it's correctly unset. Universal variables are kept in $HOME, if you set $HOME elsewhere they won't be loaded.

----

Alright, seems the encoding is borked. I think @ridiculousfish is the correct person to ask here.

**Comment by nrnrnr** [comment]
> > When I do the same thing with an empty home tree, I don't get the warning message, but the universal variable barf is incorrectly set to the empty string.
> 
> No, it's correctly unset. Universal variables are kept in $HOME, if you set $HOME elsewhere they won't be loaded.

I launch the new shell with the temporary $HOME, set the universal variable in that new shell, but both `echo $barf` and `count $barf` indicate that `$barf` is the empty string.

**Comment by mqudsi** [comment]
I proposed switching to UTF-8 encoding for these as part of my argument in favor for https://github.com/fish-shell/fish-shell/pull/9763
