### ISSUE TITLE
[Pager] `fish_pager_color_selected_completion` is ignored by the parenthesis

### ISSUE THREAD

**Issue by DrBu7cher** [fish-shell/fish-shell#10328]
Info:
```
fish: version 3.7.0
OS: EndevaourOS (Arch)
Term: xterm-256color
```

If I set (with some settings I left out, because they are not important for this issue)
```
set -U fish_pager_color_description FFFFFF
set -U fish_pager_color_selected_description 000000

set -U fish_pager_color_completion FFFFFF
set -U fish_pager_color_selected_completion 000000

set -U fish_pager_color_selected_background --background=00FF00
```
I would expect a pager that has white text and the selected parts have a green background with black text in them.

But my pager looks like this:
![grafik](https://github.com/fish-shell/fish-shell/assets/18399895/b406189a-fce6-4fe2-801e-4144edf1dba5)

The parenthesis around the description are still white.

Is this intended? Is there a config I am missing?

EDIT: I think `sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'` does not have this problem...but what could cause it?

**Comment by DrBu7cher** [comment]
Sorry for this, I think the problem is somewhere else.

**Comment by DrBu7cher** [comment]
I reopen the issue, maybe someone can give me a hint, where I can find the configuration for the pager? So I can have a look how the description is built internally?

**Comment by faho** [comment]
The parentheses are colored with $fish_pager_color_completion, $fish_pager_color_description only applies to the text inside.

$fish_pager_color_selected_completion doesn't apply to them, I think we can fix that.

**Comment by DrBu7cher** [comment]
So my observation was right?
The `sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'` command made it look like I was wrong... :D

Thank you for looking into my request so quickly!

**Comment by DrBu7cher** [comment]
Is it an easy fix for you? Otherwise I would offer to create a PR, if you can point me to the right place to look.

**Comment by DrBu7cher** [comment]
You are great :rocket:
