### ISSUE TITLE
option to make tab completions for files and directories sorted by modification time

### ISSUE THREAD

**Issue by blueforesticarus** [fish-shell/fish-shell#10324]
This has bothered me for awhile. It would be way more useful if completions sorted files and directories by their modification time. 

I attempted to implement this as a custom completion for cd, and its just way way to cumbersome. Plus IDK if there is a way to do it generally (override the default file completion)

```fish
function __complete_cd_sorted
	__fish_complete_cd &&
	__fish_complete_directories (commandline -ct) | 
		cut -d \t -f1 | 
		tr -d \t | 
		tr \n '\0' | 
		xargs -0 stat -c '%Y %n' -- | 
		sort -r -n | 
		cut -d ' ' -f2
end

complete -e # clear existing completion
complete -c cd --exclusive --keep-order -a "(__complete_cd_sorted)"
```

**Comment by blueforesticarus** [comment]
would replacing the __fish_complete_path function overload default file completion

EDIT: appear not

**Comment by faho** [comment]
I don't like mtime order because it makes it impossible to skim the list. It also requires a bunch more work because the mtime is stored on the file, so we need to do a lot more `stat()` calls.

We try hard not to add any options to completions in general because it makes it harder to reason about and the code harder to maintain.

What we *can* do here is to improve the suggestions, and that's #9223. Closing this in favor of that.

**Comment by blueforesticarus** [comment]
#9223 really does not address my use case at all, and my use-case is both common and general.

- want to cd into a path? which one are you most likely to want?
- `nvim <TAB>`  you almost certainly prefer a list prioritized by recently changed files. 
   - **suggestions won't help here, because the last edited file isn't much more likely that the second to last.**
- say you downloaded a file in the browser and now you need to do something too it? 
  `cd downloads; ffmpeg -i <tab>`  -> terminal fills with suggestions, probably none of which are your file.  
  The tab-completion here is completely useless. Especially because you probably aren't even sure what the file was called exactly.

As far as skimming the list, I don't get the utility: if you knew the first letter of what you wanted, you would have already typed it?

**Comment by faho** [comment]
> want to cd into a path? which one are you most likely to want?

The newest or last-changed one, which is 9223.

> As far as skimming the list, I don't get the utility: if you knew the first letter of what you wanted, you would have already typed it?

I have a rough guess what the filename is like - might be "config", might be "cfg". If they're sorted by mtime, I get to scan the *entire list* to see that it's not in there.

If it's sorted by name, I know where to look.

-----

The big issue with sorting by mtime is if it's not new it might as well be random. Sure, the 5 or so last modified files might be hotspots, but after that the comparison is pretty useless. It's also useless if the files are very close in mtime - do you want this file or this file, both copied by the same process but within three seconds of each other.

Meanwhile sorting by name is predictable. It is easy to skim, easy to find what you want even if it's not the first or second. It is also easiest to produce (no need to `stat()` every file), and what we already do.

I find recency order frustrating whenever I encounter it. It causes me to scan a lot of things until I find what I want.

What I am saying is that I do not like this as a default, and I don't want to add any options here - we currently have none, and that's a nice property to have. If that doesn't fit your wishes perfectly, that's unfortunate.

**Comment by blueforesticarus** [comment]
This seems like a good reason to allow overriding the default file suggestions with a fish function.
