### ISSUE TITLE
requested feature: ai generated command

### ISSUE THREAD

**Issue by ahmeteid7** [fish-shell/fish-shell#10323]
fish is the best , i wish if u can add ai feature that help in convert sentence to command,
ex: find in that directory file it's name start with s.
 a warp and fig is enable that feature in their last release and still work in improvement it

**Comment by faho** [comment]
Absolutely not.

**Comment by zanchey** [comment]
There's https://github.com/Realiserad/fish-ai which I have not reviewed or used, it might always suggest `sudo rm -rf /*`
