### ISSUE TITLE
Downloading clients freeze fish shell. 

### ISSUE THREAD

**Issue by gorliver** [fish-shell/fish-shell#10335]
I used `EgdeTurbo` to download data from a public database and `lnd` to download data from a company. Both clients freeze fish shell after I run any clients.

To reproduce the problem:
1. In MobaXterm, download `EgdeTurbo` and uncompress the tar.gz file.
```
wget https://ngdc.cncb.ac.cn/ettrans/download/edgeturbo-client.linux.latest.cncb.tar.gz
tar -zxvf edgeturbo-client.linux.latest.cncb.tar.gz
```
2. download data using `EgdeTurbo`.
```
edgeturbo download /gsa/CRA007099/CRR511439/CRR511439_f1.fq.gz 
```
3. Open a new session in MobaXterm and start fish shell.
4. type any command and fish freeze.

I have tried `sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'` and fish shell is normal.
It seems something about the third-party customizations. Is there a way that I can narrow down the problem?

Many thanks!

**Comment by faho** [comment]
> It seems something about the third-party customizations. Is there a way that I can narrow down the problem?

First compare the outputs of:

- `type edgeturbo`
- `functions --handlers`
- `set --universal`

Those are likely causes.

If those are the same, you can run `fish_delta` to show the difference between your config and fish's default. This will compare your ~/.config/fish against the defaults.

**Comment by gorliver** [comment]
Hi Faho,
The fish shell is alive again overnight with this message:
```
warning: Locking the history file took too long (53922.086 seconds). 
```
![image](https://github.com/fish-shell/fish-shell/assets/15271446/369dbf7f-ee1a-4759-8132-2c192e026971)

Not sure if this is due to the downloading was completed. I will do another test to see if I can reproduce this.

**Comment by gorliver** [comment]
I cannot reproduce the problem. 
Not sure what happened to my fish shell config but everything is great!
I will close the issue for now.
