### ISSUE TITLE
i cannot run script in background

### ISSUE THREAD

**Issue by clydeconfigs** [fish-shell/fish-shell#10344]
i cannot run a script in background like i would in bash, for example:

`{ sleep 5; echo "done!"; } &`

this waits 5 seconds *in background*, and then says hello

in fish, i cannot do the equivalent

`begin sleep 5; echo "done!"; end &`

why? please, help me :( please fishy don't betray me

_(i'm running fish, version 3.7.0)_

**Comment by faho** [comment]
Duplicate of #238
