### ISSUE TITLE
Almost expansion globbing

### ISSUE THREAD

**Issue by rupert-t-strahovsky** [fish-shell/fish-shell#10361]
**
Fish version 3.3.1
Linux pop-os 6.6.6
Kitty terminal

So an interesting little problem here, it may, or may not, in fact be a bug, but it feels buggy and perhaps someone can put me on the right track either way:

Just attempting to glob ls with *, just playing around, getting a feel for fish, I notice this: If the directory has a single file ending with an "e" it is not picked up by "ls *e". Add a second file ending in "e", no problem.
For example:

touch charlie
ls *e
{Nothing}

touch charlee
ls *e
charlie
charlee
{As expected}

rm charlee
ls *e
{Again, nothing}

Now I have played around with a few letters, touch aa, ab, ac... etc, just seeing what happens, and assumed I am just globbing wrong. I probably am! But, I would love to know what is special about "e". I didn't go through the alphabet, and searched for other instances of people talking about this, but didn't find anything.
Any thoughts on this would be greatly appreciated. :)

~rts
**

**Comment by mqudsi** [comment]
Can you upgrade your fish installation and try again? I'm not reproducing this on my end, and 3.3.1 is rather old.

**Comment by rupert-t-strahovsky** [comment]
Upgraded to 3.7.0
Can reproduce it with directories at this point.
Just running a small test as follows:

mkdir test
cd test
mkdir ae
ls *e
{nothing}

mkdir be
ls *e
ae:
be:
{as expected}

cd be
touch ae
ls *e
ae
{as expected}

rm ae
mkdir aa
ls *a
{nothing, should be aa, shouldn't it?}

mkdir ba
ls *a
aa:
ba:
{as expected}

So, at this point I am feeling there is something about having a single directory and ls or the * not quite playing well with each other.
Actually, let me just try something... this happens in bash too. I feel like this is just my lack of understanding of how it ought to work rather than it being a bug.
☺☻☺☻☺ ~rts

**Comment by faho** [comment]
This is, in fact, just ls behavior.

Try this:

```fish
ls aa/
```

This will print nothing. You're asking ls to show you the *contents* of the "aa/" directory, which is empty.

If you do 

```fish
ls aa/ ba/
```

It will print "aa", and "ba", but more specifically it will print `aa/:` and `ba/:`. These are *headings*. ls tries to show the contents of both directories, and to disambiguate what is in which directory it prints a heading first.

If you want ls to not descend into the directories to show the contents, use `ls -d`.

**Comment by rupert-t-strahovsky** [comment]
Indeed! Thank you for the education. Like I said, just my not understanding very well.
We are all on a journey! 
Thank you. :)
