### ISSUE TITLE
can translate the bashrc content to the config.fish

### ISSUE THREAD

**Issue by ahmeteid7** [fish-shell/fish-shell#10362]
i want to use fish instead of bash, but i have problem with fish because there are a lot of settings and exports needed to done, can i translate the bashrc to config.fish?

**Comment by ahmeteid7** [comment]
```
aichat
Failed to execute process '/home/eid/aichat'. Reason:
exec: Exec format error
The file '/home/eid/aichat' is marked as an executable but could not be run by the operating system.
```
that command work in bash withou any problem , why i get that in fish?

**Comment by faho** [comment]
Your script is missing a shebang line - `#!/bin/sh` as the first line.

Additionally you are running an old version of fish (older than 3.3.0, released in 2021 and 16% of all commits ever made to fish behind).

Bash will then try to read it itself, other shells (including newer versions of fish) will then hand it to /bin/sh.

I recommend adding a shebang line to your script and upgrading fish, tho either would be enough to fix your problem. See https://fishshell.com/ for repositories with newer versions.

**Comment by ahmeteid7** [comment]
sorry, i miss the path of the right app(aichat), i was used wrong one, the path is that `set -x PATH /home/eid/.cargo/bin $PATH`
i added it to fish, and it worked.
I will try the newer versions of fish ,thank you

**Comment by faho** [comment]
> sorry, i miss the path of the right app(aichat), i was used wrong one, the path is that set -x PATH /home/eid/.cargo/bin $PATH

You have another `aichat` in $PATH, and that one is missing a shebang.
