### ISSUE TITLE
Store generated_completions in ~/.cache/fish not ~/.local/share/fish

### ISSUE THREAD

**Issue by digitalsignalperson** [fish-shell/fish-shell#10369]
`~/.local/share/fish` contains `fish_history` and `generated_completions`. While `fish_history` is actual data we want to track and control, `generated_completions` is not. The latter is automatically generated. Thus a better location for it would be `~/.cache` or `XDG_CACHE_HOME`.

Use case: managing dotfiles/state and saving the contents of `~/.local/share/fish`, but not caring about files that are auto-generated.

fish version 3.7.0 on arch linux 6.7.8-arch1-1

**Comment by krobelus** [comment]
sounds reasonable.

In future, we could go even further, and not cache it at all -- but parse man pages as autoloading fails.

**Comment by zanchey** [comment]
Prior work here: #1343
