### ISSUE TITLE
clipboard copy not working with selection in binding

### ISSUE THREAD

**Issue by phortonssf** [fish-shell/fish-shell#10360]
Create a key binding that goes from normal mode into visual vi-mode selects a word then uses fish_clipboard_copy.

**YOUR TEXT HERE**
I am able to copy using fish_clipboard_copy and paste. However when trying to bind the copy in combination with a mode change and selection binding, I am unable to pass the selection to fish_clipboard_copy because fish hangs and never enters visual mode. 

Different approaches I have tried, all have the same result, the command line hangs and doesn't enter visual mode, make a selection or copy. 
`
   bind -M default viw --sets-mode visual repaint-mode backward-bigword begin-selection forward-bigword  fish_clipboard_copy

    bind -M default viw --sets-mode visual 'commandline -f repaint-mode begin-selection forward-bigword swap-selection-start-stop backward-bigword fish_clipboard_copy'
`

If i remove fish_clipboard_copy the bind moves to visual mode and the selection works and i can manually copy with fish_clipboard_copy bound to a key in visual mode.  Copy will work when bound to a keybind individually, but not when mixed with the selection process in the bind. Is this working as intended? Or is there a proper approach to using a selection and copy in one bind?  I am only using wl-copy i commented out the other options in fish_clipboard_copy to reduce variables. Thank you.

**Comment by krobelus** [comment]
would be fixed by https://github.com/fish-shell/fish-shell/pull/10338/commits/7a6e760185c52243f111ea0bf51833844b4d7287 which needs some more work

**Comment by krobelus** [comment]
you'll need to write the command as separate works, like your first command

`bind -M default viw --sets-mode visual repaint-mode begin-selection forward-bigword swap-selection-start-stop backward-bigword fish_clipboard_copy`

this is due to a limitation in `commandline`; the state is only propagated after ever individual argument to `bind`
