### ISSUE TITLE
Unexpected behavior with fish's `-c` option

### ISSUE THREAD

**Issue by nickeb96** [fish-shell/fish-shell#10375]
`fish --version`: fish, version 3.7.0
`sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'`: did not help

---

I could be misreading the docs, but it seems like the remaining args after the `--command`/`-c` option should be passed to the command fish is executing.

From `man fish`:

> -c or --command=COMMAND
              Evaluate the specified commands instead of reading from the commandline, ***passing
              additional positional arguments through $argv.***

However, when I run something like `fish -c echo hello world` the remaining args are ignored and it just prints an empty line.

I was expecting it to forward the remaining args to `echo` and print "hello world".

Is this a bug or is the man page just outdated?

**Comment by faho** [comment]
No, the documentation is correct: The arguments are passed as $argv:

`fish -c 'echo $argv' hello world`

**Comment by nickeb96** [comment]
Ah, I didn't realize I had to explicitly expand argv.  Thanks!
