### ISSUE TITLE
check-completions.fish fails when completion command exists but errors

### ISSUE THREAD

**Issue by VulpineAmethyst** [fish-shell/fish-shell#10386]
When running fish's testsuite on a system where a completion command exists but exits with a non-zero value, the `check-completions.fish` check fails. This is related to #8896, as that is when this failure mode was introduced.

This issue was discovered while building fish 3.7.0 (and 3.7.1) on Adélie Linux (I am the package maintainer).

**Comment by faho** [comment]
What that test does is `source` the completion if a command by the given name exists: https://github.com/fish-shell/fish-shell/blob/b64c210aded45d1131425e533ae497a7ec438a6c/tests/checks/check-completions.fish#L6-L10

If that then prints anything, the test fails. It doesn't specifically care about what the command-to-be-completed is, or if it returns anything in specific, just the load-time behavior of the completion *script* (e.g. broken `complete` calls).

What error specifically are you seeing?

**Comment by VulpineAmethyst** [comment]
What we were encountering specifically was an issue caused by `pip3` (for some reason) expecting `/usr/bin/python` to exist when our Python package only provides `/usr/bin/python3`.

**Comment by faho** [comment]
The pip3 completion script [in 3.7.1](https://github.com/fish-shell/fish-shell/blob/Integration_3.7.1/share/completions/pip3.fish) calls pip3:

https://github.com/fish-shell/fish-shell/blob/80394ea4e38138e0ce0bf23b016dc931e22ff788/share/completions/pip3.fish#L5

If that wants to run /usr/bin/python, then that is a real bug that manifests on your system (whether it is in pip3 or in Adélie's packaging), and any user who has pip3 installed but not /usr/bin/python would see error output and a non-functioning completion.

This appears to be working as intended.

**Comment by faho** [comment]
Note: pip3's output here is pretty cheesy:

```fish

# pip fish completion start
function __fish_complete_pip
    set -lx COMP_WORDS (commandline -o) ""
    set -lx COMP_CWORD ( \
        math (contains -i -- (commandline -t) $COMP_WORDS)-1 \
    )
    set -lx PIP_AUTO_COMPLETE 1
    string split \  -- (eval $COMP_WORDS[1])
end
complete -fa "(__fish_complete_pip)" -c pip3
# pip fish completion end
```

This does not call `/usr/bin/python` anywhere, so I suspect the issue to be in a shebang somewhere. This would have to be fixed.

**Comment by VulpineAmethyst** [comment]
Yeah. The underlying issue is definitely on Python's end (and could be in our Python recipe), but fish could very well be installed on a system that doesn't have Python installed (e.g. my development VM only installs Python when building packages that depend on it, and it is otherwise not present, and I use fish there).

**Comment by VulpineAmethyst** [comment]
Fair enough.
