### ISSUE TITLE
`disown` and `function --on-process-exit` 

### ISSUE THREAD

**Issue by giorgiga** [fish-shell/fish-shell#10381]
By reading the documentation of [`disown`](https://fishshell.com/docs/current/cmds/disown.html) and [`function --on-process-exit`](https://fishshell.com/docs/current/cmds/function.html) one gets the idea that `--on-process-exit` will be honored for disowned jobs, but this does not seem to be the case.

Here's a demonstration script:

```fish
for disown in true false
    echo "disown is $disown"
    sh -c 'sleep .1; echo done sleeping' &
    set -l pid (jobs -lp)
    echo "job pid is $pid"
    function jobexited --on-process-exit $pid
        echo "function is running"
    end
    test $disown = true && disown $pid
    sleep .5
    echo
    functions -e jobexited # cleanup
end
```

and its output:

```
disown is true
job pid is 14512
done sleeping

disown is false
job pid is 14515
done sleeping
function is running
```

I wish `--on-process-exit` worked for disowned jobs, but I fear this will be addressed by fixing the documentation. 

(this is probably irrelevant, but I'm running fish 3.7.0)

**Comment by faho** [comment]
`disown` removes all knowledge fish has of a job. That's what it is for.
