### ISSUE TITLE
up down key for history weird error

### ISSUE THREAD

**Issue by nutinshell** [fish-shell/fish-shell#1038]
Happens sometime on Mac 10.9, no idea how to fix it...

fish: Unknown command 'up-or-search'
fish: Unknown command 'up-or-search'
fish: Unknown command 'up-or-search'
fish: Unknown command 'up-or-search'
fish: Unknown command 'up-or-search'
fish: Unknown command 'up-or-search'
fish: Unknown command 'up-or-search'
fish: Unknown command 'down-or-search'
fish: Unknown command 'down-or-search'
fish: Unknown command 'down-or-search'
fish: Unknown command 'up-or-search'
fish: Unknown command 'up-or-search'
fish: Unknown command 'down-or-search'
fish: Unknown command 'down-or-search'
fish: Unknown command 'up-or-search'
fish: Unknown command 'down-or-search'
fish: Unknown command 'up-or-search'
fish: Unknown command 'down-or-search'
fish: Unknown command 'up-or-search'
fish: Unknown command 'down-or-search'

**Comment by scubafly** [comment]
Opening a new terminal fixed this for me.
