### ISSUE TITLE
Fish-shell command is broken at window line wraps when copied from Windows Terminal or vscode.

### ISSUE THREAD

**Issue by youralmight** [fish-shell/fish-shell#10384]
**YOUR TEXT HERE**
This bug only shows when I am using fish-shell and the copied content is a command.

Info:
fish version: version 3.3.1
OS: WSL-2.1.5.0 Ubuntu 22.04  on Windows 10.0.22631.0
Terminal: Windows Terminal 1.19.10573.0
Linux system information(uname -a): Linux DESKTOP-422MBNH 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
TERM: xterm-256color
This bug also shows when I disable third-party customizations by executing the command `  sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'`

Steps to reproduce:
1. open windows terminal and launch WSL Ubuntu-22.04.
1. fish shell is launched.
1. input some long command such as "echo 11111111111111111111111111111111111111111111111111111111111111111111111111111111111" so the command wraps.
1. use the mouse to select the command.
1. hit "ctrl+shift+c" to copy the selected command.
1. paste it into any editor to see the result.

![image](https://github.com/fish-shell/fish-shell/assets/42952005/ed7894f9-6e6e-491f-947a-b4a533512c26)

Expected Behavior:
The command is pasted correctly including no line break.

Actual Behavior:
Line breaks are inserted at the wrap points.

Others:
- I tested on bash command, colored bash output, fish command and colored fish command to find that this bug only shows when I am using fish-shell and the copied content is a command. I am also posting the issue to fish-shell.
- This bug doesn't only show on windows terminal but also on vscode integrated terminal.

Related Issue:
I also posted a [issue](https://github.com/microsoft/terminal/issues/16905) on windows terminal.

**Comment by faho** [comment]
Fish controls its output a bit more than bash - this is necessary for things like syntax highlighting and suggestions.

To copy your commandline, press ctrl-x - this will tell fish to copy it to your clipboard.
