### ISSUE TITLE
Fish doesn't use character classes with Globbing?fish

### ISSUE THREAD

**Issue by greensourcecode** [fish-shell/fish-shell#10399]
Version: 3.7.0
OS: Arch

echo */0[1-2]*/*.xlsx
--> fish: no matches for wildcard

I found this link:
https://stackoverflow.com/questions/28838665/glob-matching-wildcards-in-fish-shell-not-matching-bash-behavior

Is this correct? If so are there any plans to implement globbing entirely? If not is there a way around this?

Thank you for your time

**Comment by faho** [comment]
> Is this correct?

This is correct.

> If not is there a way around this?

Use `find`.

> If so are there any plans to implement globbing entirely?

There have been discussions in #3681, it'll likely end up as a separate builtin instead of additional syntax.
