### ISSUE TITLE
Autosuggestions sometimes get accepted without input

### ISSUE THREAD

**Issue by jm355** [fish-shell/fish-shell#10397]
```
~ $ fish --version
fish, version 3.7.0
~ $ echo $version
3.7.0
~ $ echo $TERM
xterm-kitty
```
On Arch Linux

I wasn't able to reproduce in a few minutes with the customization-free command, and I can't consistently reproduce on my system.

The issue is that often I will type a letter, and fish will complete the autosuggestion as if I had pressed the right arrow. This is most notable when I try to update. I have `u` as an alias for `sudo pacman -Syu`, and I have other commands I occasionally run like my `usbguard-allow` and `usbguard-deny` aliases. What will happen is, say the most recent "u*" command I've run is `usbguard-allow`, I will boot up my computer, open the terminal, type `u`, hit enter, and realize that `usbguard-allow` was expanded right before I hit enter and that's what gets run.

Sometimes it's not instant like that, and it happens maybe 5-10% of the time. I have no idea what's going on, it's super strange

**Comment by kovidgoyal** [comment]
https://github.com/kovidgoyal/kitty/issues/4530

**Comment by mqudsi** [comment]
> Ideally, fish would have some input function that moves the cursor right
without accepting an auto-suggestion. Then the kitty fish shell integration
could bind that function to some otherwise unused escape sequence and we
would not have this issue. However, there is no such function:
https://fishshell.com/docs/current/cmds/bind.html that I can see.
>
> Even more ideally, fish would add a function that has semantics of
"move cursor to the cell number X on line number Y, where Y is counted
from the line that starts the prompt".

The first seems eminently doable. The second might be a more difficult ask as things currently stand.

@kovidgoyal What do you expect the first to do if the cursor is at the end of input? Bell/alarm would be annoying.

**Comment by kovidgoyal** [comment]
On Wed, Mar 27, 2024 at 09:11:39PM -0700, Mahmoud Al-Qudsi wrote:
> > Ideally, fish would have some input function that moves the cursor right
> without accepting an auto-suggestion. Then the kitty fish shell integration
> could bind that function to some otherwise unused escape sequence and we
> would not have this issue. However, there is no such function:
> https://fishshell.com/docs/current/cmds/bind.html that I can see.
> >
> > Even more ideally, fish would add a function that has semantics of
> "move cursor to the cell number X on line number Y, where Y is counted
> from the line that starts the prompt".
> 
> The first seems eminently doable. The second might be a more difficult ask as things currently stand.
> 
> @kovidgoyal What do you expect the first to do if the cursor is at the end of input? Bell/alarm would be annoying.

Do nothing, the same as the current binding. Pressing right at the end
of prompt does not beep, at least for me, in fish.

**Comment by mqudsi** [comment]
Fixed with `forward-char-passive` and `backward-char-passive` in #10398.

**Comment by mqudsi** [comment]
Fixed (on our end) with `forward-char-passive` and `backward-char-passive` in #10398. Any terminal integrations would have to be upgraded to take advantage of this.

I'm not sure how the best way to feature test for this would be, probably just `bind ... forward-char-passive || bind ... forward-char` or maybe just disable the integrations altogether if running less than fish 3.8.0 or whatever it ends up being released as.

**Comment by kovidgoyal** [comment]
On Sat, Mar 30, 2024 at 09:47:12PM -0700, Mahmoud Al-Qudsi wrote:
> Fixed (on our end) with `forward-char-passive` and `backward-char-passive` in #10398. Any terminal integrations would have to be upgraded to take advantage of this.
>
> I'm not sure how the best way to feature test for this would be, probably just `bind ... forward-char-passive || bind ... forward-char` or maybe just disable the integrations altogether if running less than fish 3.8.0 or whatever it ends up being released as.

There needs to be some way to detect if a function exists. bind appears
to always succeed, regardless of the function existing.

bind -a "\e[0u" not-existing-function && echo bind succeeded
bind succeeded

I guess in the worst case I will have to check fish version. Which is a
bit sad as it is slow. Currently the script does:

# Check fish version 3.3.0+ efficiently and fallback to check the minimum working version 3.2.0, exit on outdated versions.
# "Warning: Update fish to version 3.3.0+ to enable kitty shell integration.\n"
set -q fish_killring || set -q status_generation || string match -qnv "3.1.*" "$version"
or echo -en ***@***.***\|V2FybmluZzogVXBkYXRlIGZpc2ggdG8gdmVyc2lvbiAzLjMuMCsgdG8gZW5hYmxlIGtpdHR5IHNoZWxsIGludGVncmF0aW9uLgo=\e\\ && exit 0 || exit 0

Will have to add an extra version check for 3.8 or newer I suppose.

**Comment by kovidgoyal** [comment]
Is there some new fish builtin that will exist in the next fish release along with this function that I can test for using set -q or do I have to write a version parsing function? Even the functions builtin doesnt work for input mode functions, so it looks like its either test for a new builtin with set -q or parse the version.

**Comment by kovidgoyal** [comment]
Built fish from git and doscovered fish_cursor_end_mode so basing detection off that.
https://github.com/kovidgoyal/kitty/commit/775b7c475825d302ad536104cd9a8f57acc1f719

Are there any more modes I should bind in? What is the 'default' mode?

**Comment by krobelus** [comment]
On Sat, Mar 30, 2024 at 10:22:13PM -0700, Kovid Goyal wrote:
> On Sat, Mar 30, 2024 at 09:47:12PM -0700, Mahmoud Al-Qudsi wrote:
> > Fixed (on our end) with `forward-char-passive` and `backward-char-passive` in #10398. Any terminal integrations would have to be upgraded to take advantage of this.
> >
> > I'm not sure how the best way to feature test for this would be, probably just `bind ... forward-char-passive || bind ... forward-char` or maybe just disable the integrations altogether if running less than fish 3.8.0 or whatever it ends up being released as.
> 
> There needs to be some way to detect if a function exists. bind appears
> to always succeed, regardless of the function existing.

Use `bind --function-names | grep -Fxq forward-char-passive`
(or `bind --function-names | string match -q forward-char-passive`)

> 
> bind -a "\e[0u" not-existing-function && echo bind succeeded
> bind succeeded
> 
> I guess in the worst case I will have to check fish version. Which is a
> bit sad as it is slow. Currently the script does:
> 
> # Check fish version 3.3.0+ efficiently and fallback to check the minimum working version 3.2.0, exit on outdated versions.
> # "Warning: Update fish to version 3.3.0+ to enable kitty shell integration.\n"
> set -q fish_killring || set -q status_generation || string match -qnv "3.1.*" "$version"
> or echo -en ***@***.***\|V2FybmluZzogVXBkYXRlIGZpc2ggdG8gdmVyc2lvbiAzLjMuMCsgdG8gZW5hYmxlIGtpdHR5IHNoZWxsIGludGVncmF0aW9uLgo=\e\\ && exit 0 || exit 0

Interesting. I'm surprised that any of this is slow (it can also be cached for the shell process).
But yeah it's not ideal.. for this particular case there is a a scalar version variable `$__fish_initialized`.
We've been incrementing it only if there are things to be do on first startup after upgrade..
So the check would be `[ $__fish_initialized -ge 3100 ]`
but I don't think we should tell people to use this private variable that may lag behind `$version`.
Better make `status version` print a scalar version of something.. but of course it's better to probe for features directly.

**Comment by krobelus** [comment]
> Are there any more modes I should bind in? What is the 'default' mode?

you want to bind in all of `for mode in (bind --list-modes | string match -v paste); bind -M $mode ...; end`
(`paste` is active during bracketed paste but we're about to remove that mode for good).

The "default" mode is the main mode when using Emacs key binding and it's also the normal mode when using Vi key bindings.
(For some reason there's no mode called "normal")

You're running this on the first prompt. If a user switches from default key bindings to vi ones (by running `fish_vi_key_bindings`) interactively, they probably need to restart to get the correct bindings.
I'm not sure what's the best fix, maybe we should just declare all modes up-front, so `bind --list-modes` includes everything.
Need to think about it.. I think it's not a big deal
We should probably have a way to bind something in all current and future modes.

**Comment by krobelus** [comment]
> fish_cursor_end_mode

can't use that unfortunately because it's only defined when using Vi key bindings.
(Note that `fish_vi_key_bindings` affects future shells which is very surprising I think -- need to run `fish_default_key_bindings` to go back to defaults, or use an empty `$HOME`)

**Comment by kovidgoyal** [comment]
OK have changed it to use bind --function-names and bind in all non paste modes.

https://github.com/kovidgoyal/kitty/commit/94a612c4df0de8dc7c52f63221c866fa15a3772d
