### ISSUE TITLE
Commandline is needlessly repainted with new extended keyboard input functionality

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#10409]
Using https://github.com/fish-shell/fish-shell/commit/3af849d739bbf166e63be5dee665ab281ca735b0 and iTerm 2 (v3.4.23)

This used to work prior to the new extended keyboard input functionality, so I suspect it is related.

---

Define the following `fish_prompt`:

```fish
function fish_prompt
  echo -e '---\n$ '
end
```

Define the following function to be bound:

```fish
function nextdir-or-forward-word
    set -l cmd (commandline)
    if test -z "$cmd"
        nextd
        commandline -f repaint
    else
        commandline -f forward-word
    end
end
```

Bind it:

```fish
bind alt-right nextdir-or-forward-word
```

Use it:

![image](https://github.com/fish-shell/fish-shell/assets/8544900/a9b82ac8-0ce5-4473-895f-d07da8e6a900)

**Comment by krobelus** [comment]
thanks, fixed in 1da2087038f2d5f859323fb61c25b898cf6221e0

**Comment by zanchey** [comment]
Do we need a test for this?

**Comment by krobelus** [comment]
Yeah a test would be good. At least on macOS it reproduces consistently, maybe even on BSD.
The implementation is very dated here, needs a proper cleanup.
