### ISSUE TITLE
fish_add_path does nothing on msys2, and set $PATH misbehaves

### ISSUE THREAD

**Issue by Tyler799** [fish-shell/fish-shell#10406]
fish version 3.7.0
environment: msys2 using ucrt64 (though issue happens on mingw64 as well)
steps to reproduce:

1. echo $PATH
2. fish_add_path /c/Users/tyler.shellberg/.cargo/bin
3. echo $PATH
4. Notice that PATH has not changed, the fish_add_path command did nothing

I can manually force it to work temporarily using:

>set PATH $PATH:/c/Users/tyler.shellberg/.cargo/bin

While this works, it results in the path being inserted several times into PATH, seemingly one after every entry in PATH.

**Comment by faho** [comment]
You can run `fish_add_path -v` to see which exact `set` command `fish_add_path` ends up running.

Note that it will ignore duplicate and already included paths. If the path is not already included it will show something like

```fish
set -U fish_user_paths /c/Users/tyler.shellberg/.cargo/bin # and the already included paths
```

If it does not print anything, you can do

```fish
set -l old_path $fish_user_paths
set -e fish_user_paths
fish_add_path -v /c/Users/tyler.shellberg/.cargo/bin $old_path
```

to see if that runs anything.

Msys2 has some extra configuration that we *know* to be pretty broken - see e.g. https://github.com/msys2/MSYS2-packages/issues/1634.

My assumption is that that resets $PATH to a value without your customization.

**Comment by Tyler799** [comment]
Passing -v did not print anything at all. Trying your second suggestion of using old_path, it _does_ print something:

set -U fish_user_paths /c/Users/tyler.shellberg/Documents /c/Users/tyler.shellberg/.cargo/bin

Also, set -a works without duplicating the path, so that's good. Thanks.

**Comment by Tyler799** [comment]
> > Passing -v did not print anything at all. Trying your second suggestion of using old_path, it does print something:
> 
> Okay, that means $fish_user_paths already included it, which means msys is messing up your $PATH after that is applied.
> 
> You'll have to talk to the msys people. Tbh I would recommend WSL instead, but that's your call of course.

I use both WSL and msys. I don't have much of a choice, I definitely need to use both.

What would I report to WSL maintainers? I'm concerned I may get bounced back here if I don't have something concrete.

**Comment by faho** [comment]
> What would I report to WSL maintainers? I'm concerned I may get bounced back here if I don't have something concrete.

You'll have to tell the *Msys* people (not the WSL people) that they seem to overwrite $PATH after $fish_user_paths is applied.

They might tell you more, e.g. there's apparently a ["strict" path type](https://github.com/msys2/MSYS2-packages/blob/d61778de10e660c978678468452169e903e79cd7/fish/msys2.fish#L24-L25) that will cause it to reset $PATH, maybe something in your config triggers that.
