### ISSUE TITLE
Documentation: document method for not splitting shell outputs by newline

### ISSUE THREAD

**Issue by lolbinarycat** [fish-shell/fish-shell#10403]
sometimes you want to pass an argument that contains newlines (particularly when using psub).

this is entirely possible, but i don't think it is ever mentioned in the manual:

```
set a "$(echo -e 'foo\nbar')"
echo $a[1]
```

i remember this frustrating me quite a bit a few years back and i only recently figured it out.

**Comment by faho** [comment]
From https://fishshell.com/docs/current/language.html#command-substitution:

> A command substitution can also be spelled with a dollar sign like outercommand $(innercommand). This variant is also allowed inside double quotes. When using double quotes, the command output is not split up by lines, but trailing empty lines are still removed.

and later in the examples:

> ```fish
> # Set the ``data`` variable to the contents of 'data.txt'
> # without splitting it into a list.
> set data "$(cat data.txt)"```

It already *is* mentioned.

I'm going to reword that a bit, but I do believe the obvious section on "command substitutions" explaining command substitutions is already the right place to put it.

**Comment by lolbinarycat** [comment]
ah, i see.  i must have missed that before, or maybe it was so long ago it wasn't written down? thanks for your time anyways.
