### ISSUE TITLE
Cannot set universal variables in `fish --no-config`

### ISSUE THREAD

**Issue by blt-r** [fish-shell/fish-shell#10401]
fish, version 3.7.0

when trying to `set -U var val` in `fish --no-config`, I get the message:
```
set: successfully set universal 'var'; but a global by that name shadows it
```
But it just sets a global, not a universal. 

How can I launch fish so that it doesn't source any config files, but can still access the same uvars as a normal fish instance?

**Comment by faho** [comment]
This is what --no-config does. The universal variables are fundamentally *configuration*.

> How can I launch fish so that it doesn't source any config files, but can still access the same uvars as a normal fish instance?

You'll have to find some other way to pass the variables you want, like to pass them as exported variables, or to write them to a file and then source that.
