### ISSUE TITLE
can't change sigint keybinding or enable flow control with stty

### ISSUE THREAD

**Issue by elcste** [fish-shell/fish-shell#1041]
For example,

```
stty intr ^j
```

doesn't seem to have any effect. If I run the same command in bash and then start fish in the same terminal, it works as it should.

**Comment by zachguo** [comment]
Is there a workaround for this?

**Comment by zanchey** [comment]
Not that I know of.

**Comment by mwm** [comment]
Yet another alternative: properly preserve the tty modes between commands. This is much easier, doesn't introduce yet more system dependencies, and is how most other shells behave.

See the pr https://github.com/fish-shell/fish-shell/pull/2317 for an implementation. This should also fix the issue raised here.

**Comment by anton-matosov** [comment]
+1 here. 
I use ` stty intr "^x"` in bash to make use of default ctrl-c shortcut to copy instead of interrupt
However can't do this with fish because of this issue =(

**Comment by seanlaguna** [comment]
Another +1. This is keeping me from using fish more.

I want to have a "one-shot" mode for fish where pressing enter enters a SIGINT. Currently this seems impossible, even with `tmux-sendkeys`, autohotkey, you name it... Ctrl+c is the only way to send SIGINT to `%self` from `%self`, and binding _any key_ to Ctrl+c destroys the use of that key.

**Comment by faho** [comment]
Closing in favor of #2315.
