### ISSUE TITLE
mipsel arch lacks AtomicU64 support

### ISSUE THREAD

**Issue by hdhoang** [fish-shell/fish-shell#10415]
Hi, I'm one of the users in #8653. I am trying to build master fish-shell again on [openwrt 23.05.3](https://github.com/openwrt/docker-openwrt/pkgs/container/sdk), basing on their `bottom` Makefile.

However, this CPU platform `mipsel` [doesn't support `AtomicU64` type](https://doc.rust-lang.org/core/sync/atomic/index.html#portability):

> PowerPC and MIPS platforms with 32-bit pointers do not have AtomicU64 or AtomicI64 types.

I attempted to `sed /AtomicU64/AtomicU32/` and fixed up call-sites as well, and [could build](https://github.com/openwrt/packages/issues/19386#issuecomment-2028616526) `fish, version a29cc8f-dirty`. Its line-reader was non-functional though. The cargo build command looks like this, for reference. (4.0.0 is a string I set in custom Makefile)

```bash
export PATH=$PATH:/builder/staging_dir/target-mipsel_24kc_musl/host/bin/:/builder/staging_dir/toolchain-mipsel_24kc_gcc-12.3.0_musl/bin/

PREFIX=/usr/ CARGO_BUILD_TARGET=mipsel-unknown-linux-musl CARGO_HOME=/builder/dl/cargo CARGO_PROFILE_RELEASE_CODEGEN_UNITS=1 CARGO_PROFILE_RELEASE_DEBUG=false CARGO_PROFILE_RELEASE_DEBUG_ASSERTIONS=false CARGO_PROFILE_RELEASE_LTO=true CARGO_PROFILE_RELEASE_OPT_LEVEL=z CARGO_PROFILE_RELEASE_OVERFLOW_CHECKS=true CARGO_PROFILE_RELEASE_PANIC=unwind CARGO_PROFILE_RELEASE_RPATH=false CARGO_TARGET_MIPSEL_UNKNOWN_LINUX_MUSL_LINKER=mipsel-openwrt-linux-musl-gcc RUSTFLAGS="-Ctarget-feature=-crt-static -lssp_nonshared" TARGET_CC=mipsel-openwrt-linux-musl-gcc TARGET_CFLAGS="-Os -pipe -mno-branch-likely -mips32r2 -mtune=24kc -fno-caller-saves -fno-plt -fhonour-copts -msoft-float -ffile-prefix-map=/builder/build_dir/target-mipsel_24kc_musl/fish-4.0.0=fish-4.0.0 -mips16 -minterlink-mips16 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro " CC=gcc MAKEFLAGS="-j1" cargo build -v --profile release
```

Could you consider using `AtomicUsize` in these places? I think it would reduce size range on all 32-bit platforms (eg i686 with AtomicU64).

I would understand if you discard mipsel support because of this. We can keep using the old fish binary.

Cheers

**Comment by krobelus** [comment]
Lack of `AtomicU64` by itself is not a reason to drop a platform, we can surely take a patch to work around that (or you maintain it dowstream if it's an experimental/short-term thing).
What is more worrying is that it sounds like the reader is dysfunctional. If someone is interested in fixing that, by all means

**Comment by faho** [comment]
> What is more worrying is that it sounds like the reader is dysfunctional

Note that this was a sed-patch that changed "AtomicU64" to AtomicU32, while we pass them as u64 without the atomic.

That might be related.

> we can surely take a patch to work around that

How about this: If someone adds a patch until the next release cool, if not tough luck.

**Comment by hdhoang** [comment]
thanks everyone for your inputs, and the works to port to pure-rust as much as feasible.

I see that bringing back mipsel support is not worth it upstream. I would try to downsize the smaller usages on x86_64 and submit if applicable, and then do proper `Mutex<u64>` inside a bookworm container locally.

Sorry about bringing up the reader freeze, and muddied the point.
