### ISSUE TITLE
[Suggestion] Do not include final slash on path completion for symlinks to directories

### ISSUE THREAD

**Issue by schuelermine** [fish-shell/fish-shell#10425]
Many programs have alternate behaviours if a path referring to a symbolic link has a trailing slash.

I believe it is unintuitive that, when using fish’s tab-completion,
the non-slash behaviour occurs on files but not on directories.

I suggest that tab-completion omit the trailing slash if the path is a symbolic link.

**Comment by krobelus** [comment]
good idea, I frequently don't notice that path is a symlink. Some kind of indication would be good
