### ISSUE TITLE
`commandline` seems to lose line break characters

### ISSUE THREAD

**Issue by max-sixty** [fish-shell/fish-shell#10426]
It's possible I'm misunderstanding how these work. But it seems that if the current command line is a multi-line prompt with line break escapes, the `commandline` function returns a string without the line breaks (fine) but with the line break escapes (bad) Here's an example:

```fish
# A function to print what `commandline` returns to a file:

function write_cl
    set -l command (commandline)
    echo $command >>x.log
end

# bind it so we can run it
bind \co write_cl
bind -M insert \co write_cl
```

Then type this into the command line

```
echo hello \
       world \
       and
```

Then, hitting c-o will print to `x.log`:

```
echo hello \ world \ and
```

...which seems wrong! Either it could be `echo hello world and` or it could be the original text with the line breaks and `\` characters. But here it removes one and not the other.

For context, this came about from attempting to make a key binding which surrounds the current cli text with `pueue add '$command'`, and being unsuccessful.

Thanks for any guidance!

System details:

```
fish version 3.7.1
MacOS
xterm-256color
Darwin 23.3.0 Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000 arm64
Alacritty
```

**Comment by faho** [comment]
https://fishshell.com/docs/current/language.html#command-substitution:

> If the inner command prints multiple lines, fish will use each separate line as a separate argument to the outer command.

`echo` will then add spaces between each argument.

Use `set --show command` (that is the name of the variable, which is "command" in this case) to show you how a variable is set.

**Comment by max-sixty** [comment]
Thanks, this was v helpful, I learnt how fish handle newlines in command substitutions...
