### ISSUE TITLE
document limitations of --condition

### ISSUE THREAD

**Issue by lolbinarycat** [fish-shell/fish-shell#10420]
fish, version 3.7.0

if a completion is specified with `--condition`, it will only apply to tab completions, not automatic completions (grey text you fill by pressing the right arrow key)

i encountered this with the nix command, which uses the following line: `complete --command nix --condition 'not _nix_accepts_files' --no-files`

this works fine for tab completions, but if you start typing the name of a file in any context, it will be shown in greyed out text.  if you then press tab, nothing will happen (assuming the prefix to the filename is not also a prefix to a nix sub-command).

**Comment by faho** [comment]
Yes. completion applies to completions.

The documentation does not conflats completions and suggestions.

**Comment by lolbinarycat** [comment]
the `complete` command *does* affect suggestions though.  if you just pass `complete -c foo --no-files`, the `foo` command will no long get file suggestions.

is that behavior not intended?

**Comment by faho** [comment]
That is the sole way completions affect suggestions.

The suggestions don't run any other code, they just load the completion script to *try* to see if files are allowed, but after that it's done.

The way suggestions work is that they suggest our one best guess for what _might_ be useful. If it is that's cool and you can pick it, if it isn't just type out what you meant to.

**Comment by lolbinarycat** [comment]
> The suggestions don't run any other code, they just load the completion script to try to see if files are allowed, but after that it's done.

yes, my testing revealed as much, and that is exactly the behavior i want documented.

the only relevant line i could find in the docs was this:

> It knows about paths and options

if this was documented, it could be used to write higher quality completion scripts

**Comment by zanchey** [comment]
> The suggestions don't run any other code, they just load the completion script to _try_ to see if files are allowed, but after that it's done.

I don't think that's right, is it? `complete -c foo --long-option bar --no-files` gives autosuggestions for `--bar` but doesn't disable the filename suggestions afterwards.
