### ISSUE TITLE
[Feature] [vi-mode] Support command count

### ISSUE THREAD

**Issue by emi-YFcz5XDj** [fish-shell/fish-shell#10431]
## Version
- `fish, version 3.7.0`
- Fedora Linux 39
- GNOME Terminal

## Note
This is a duplicate of #2192, but it's poorly worded and has been abandoned since 2015, hence I decided to ignore that.

## Feature request
Vi and its successors support repeating normal/command mode commands by preceding them with a number, which is often referred to as a count.
E.g. `12h` will move the cursor left 12 times.
This feature is currently not supported in fish's built-in vi-mode.

**Comment by faho** [comment]
Duplicate of #2192

**Comment by faho** [comment]
The necessary information is in 2192, opening a second issue is not helpful.
