### ISSUE TITLE
consider making `history-prefix-search-backward`  and forward don't change cursor position

### ISSUE THREAD

**Issue by Frefreak** [fish-shell/fish-shell#10430]
fish, version 3.7.1
archlinux
alacritty (TERM=tmux-256color)

Hi, new user here.

Currently `history-prefix-search-backward` and the forward counterpart will change cursor to end of line during the search, however in zsh the behavior of `history-beginning-search-backward` is to put the cursor at the original position, appending text after the cursor. Can we make this behavior the default instead of putting cursor at the end?

steps to confirm: 

```
bind -M insert \cP history-prefix-search-backward
echo 1 2
ls 3
echo 3 4
```
then type "echo" (no enter) and press ctrl-p to trigger prefix search, the cursor will change to the end for each match.

Is it reasonable to make them not change the cursor (personally I feel like that would be more natural), if not do you against a new readline command that behave like this?

**Comment by krobelus** [comment]
sounds reasonable to me. I wonder if we should also do it for normal history search (or even token search), but maybe it's too late for that.
