### ISSUE TITLE
Ensure that required flag is passed to script, not just that it has a value when provided

### ISSUE THREAD

**Issue by oyarsa** [fish-shell/fish-shell#10458]
fish version: 3.6.1 (homebrew)

I'm trying to use argparse in a script, but I can't get it to do something: ensure required arguments. I can use `'n/name=` to ensure that if `-n` or `--name` is provided, it must contain a value. However, I can't seem to find out how to make it so parsing fails if the flag isn't passed.

Example script:

```fish
argparse 'm/max=' -- $argv; or return
echo $_flag_max
```

Output:

```
❯ fish argparse.fish -m1
1

❯ fish argparse.fish -m
argparse: -m: option requires an argument

❯ fish argparse.fish 

```

For the last one, I expected some kind of message, like this:

```
❯ fish argparse.fish -m
argparse: -m: option is required
```

For example, this is what Python does:

```py
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--max", "-m", required=True)
args = parser.parse_args()
print(args.max)
```

Output:
```
❯ python args.py
usage: args.py [-h] --max MAX
args.py: error: the following arguments are required: --max/-m
```

I know I can just test each individual flag variable with `if set -q _flag_X`, but when you have multiple required flags, that gets tedious quickly.

Also, it would be good to specify the positional arguments, including optional ones, but I can see how that would be more complex than just parsing flags.

**Comment by faho** [comment]
We do not currently have a way to specify that a flag is required. 

> I know I can just test each individual flag variable with if set -q _flag_X, but when you have multiple required flags, that gets tedious quickly.

`set -q` returns 0 only if *all* given variables are defined, so you can do

```fish
if not set -q _flag_X _flag_Y _flag_Z
    echo "Please provide all necessary flags" >&2
    return 1
end
```

To be honest I'm not sure this warrants a special option - it's not something that comes up constantly and I think it's awkward CLI design (I'd use positional arguments).

**Comment by oyarsa** [comment]
Thank you for replying so quickly!

> To be honest I'm not sure this warrants a special option - it's not something that comes up constantly and I think it's awkward CLI design (*I'd use positional arguments*).

I find that when I have a CLI that has multiple options, it's more readable to have required options than positional arguments.

Anyway, I didn't realise that you could `set -q` multiple variables. That should do for now.
