### ISSUE TITLE
bind: cannot parse key '▒▒'

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#10450]
3.7.1-1730-gcad63263d:

```fish
bind \cx\cy\cx 'echo foo'
```

prints "bind: cannot parse key '▒▒'".

Presumably this hits the case where the argument is longer than 2 codepoints and therefore tries the new notation.

I don't think that limitation itself is a big problem, but the key should be readable.

**Comment by faho** [comment]
Alright, the comment already said if there's an ascii control legacy parsing is used, so this just does it. I'll see if I can add some tests for that as well.

There's still the issue that, if a key can't be parsed, it might not be printable. These should be formatted for display.

**Comment by krobelus** [comment]
thanks I fixed the display of nonprintables in 040cb0442.
It's an interesting question which multi-key bindings should continue to work (vs being reported as invalid long key name).
A control character definitely signals that it's not a long key name.
