### ISSUE TITLE
Metaprogramming in fish question

### ISSUE THREAD

**Issue by p7r0x7** [fish-shell/fish-shell#10454]
This is far more of a question than a bug, but I'm trying to do a metaprogramming thing in fish so that I can use POSIX shell scripts as though they were fish functions.

```fish
if status is-interactive
    for file in $HOME/.config/fish/functions/*.sh
        basename $file .sh | read -l func_name
        if not functions -q $func_name
            function $func_name
                dash $file $argv
            end
        end
    end
end
```

The issue is that $file doesn't exist when it's called (whereas $argv is working just as expected) because it's being called later than wanted.

What I'm trying to achieve may not be possible in fish, but I do hope it is; any help at all is appreciated.

**Comment by faho** [comment]
What error do you get?

Have you tried just adding this directory to $PATH instead? (I would thrn also recommend not using the fish function directory for this)

**Comment by p7r0x7** [comment]
I wanted to use POSIX shell scripts for all of my personal scripts (that I'd previously held in the functions folder) without .sh being part of the name (though I realize that extension is not strictly necessary).

I know this isn't a usual choice, but I'm in an unusual position of wanting to continue using fish as my daily interactive shell and switch to POSIX scripts for everything (because I've had a much better time of it than with fish scripts).

**Comment by faho** [comment]
I think you were anticipating a response I didn't give.

Let me try to expand on my answer.

Your immediate problem here is that you need to include $file *now*, when the function is defined. $argv will be filled in when you call it, but when you call it the value of $file will no longer exist.

That's what --inherit-variable does - `function $funcname --inherit-variable file` will add a snapshot of $file to the function when it is defined.

------

This would generally work, but this dance is also just kind of pointless.

The way of least resistance is to just move your scripts to a directory, call them whatever you want, make them executable, add a shebang and then add that directory to $PATH.

E.g. move them to ~/bin and run `fish_add_path ~/bin` (once interactively is usually enough). And then simply don't define these as functions at all.

Importantly, these approaches will both share a rather big limitation: These run in dash (or bash, or whatever), and so any changes they make to the environment won't take inside fish.

When you change a variable or `cd` in a script like this, that affects the process running it, which won't be fish.

But making them a function doesn't magically change that.

**Comment by p7r0x7** [comment]
Yeah, I was hoping for the second half that; you'd said enough to get across the first part. And yes, I am aware environment things won't affect fish (and I was going to account for that if necessary, but really I usually don't want them to). I was hoping for your response based on why I said I was doing this in case you had insight for me, so thank you.

After thinking on it, I'm probably going to go with my original idea so I can keep my .sh and .fish scripts together (the shell prompt really should be fish).
