### ISSUE TITLE
[vi-mode] Allow different fish_sequence_key_delay_ms for different bind modes

### ISSUE THREAD

**Issue by L-Trump** [fish-shell/fish-shell#10468]
fish version: 3.7.1

Hi! Is there a way to use different fish_sequence_key_delay_ms for different bind modes? Or any hooks for bind mode changes? This feature could be useful in vi-mode, since I bind a simple `jk` in insert mode for mode switch, and bind some long sequence (like ` fgl` for fzf git log search) in default mode. A large delay is required to type long sequence, while a short delay is enough for a simple `jk`. It would be perfect to set different delays for different modes.

**Comment by faho** [comment]
The delay will only be used if you *have* a binding that could be the beginning of something longer, which is usually a rare case.

I don't think the added complexity of tying it to bind mode is warranted, sorry.
