### ISSUE TITLE
Fishshell PPA use weak Algorithm

### ISSUE THREAD

**Issue by Paulo-21** [fish-shell/fish-shell#10460]
### Information :
fish version == 3.7.1
Linux Computer 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
xterm-256color

Hello, i just update my os to ubuntu 24.04 and installed fish.
I juste would like to report that **apt update** printed a warning about your PPA.

> W: https://ppa.launchpadcontent.net/fish-shell/release-3/ubuntu/dists/noble/InRelease: Signature by key 59FDA1CE1B84B3FAD89366C027557F056DC33CA5 uses weak algorithm (rsa1024)

Best Regards

**Comment by zanchey** [comment]
https://discourse.ubuntu.com/t/new-requirements-for-apt-repository-signing-in-24-04/42854#a-ppa-on-launchpad-triggers-a-weak-algorithm-warning-what-do-i-do-3

**Comment by zanchey** [comment]
Sorry, you'll have to wait for the Launchpad PPA upgrades to be completed. There's no significant danger here though.

**Comment by Paulo-21** [comment]
Ho nice ! sorry for the inconvenience.
