### ISSUE TITLE
`conda env update --file` does not have path completion

### ISSUE THREAD

**Issue by mwyschan** [fish-shell/fish-shell#10463]
fish, version 3.7.1
WSL Ubuntu 22.04
no 3rd party

---

When I run `conda env update --file /path/to/my/file` (or similar variations of specifying the file, e.g. `-f=/path/...`), I cannot use tab to autocomplete the path, instead I have to manually type out the entire path.

Side question:
I didn't have this problem in bash since bash always detects paths and tab-completes them. Is this behaviour configurable in fish?

**Comment by faho** [comment]
> I didn't have this problem in bash since bash always detects paths and tab-completes them. Is this behaviour configurable in fish?

It is not. That's not how fish operates.

If the completions say that this is how you complete, then that is how fish completes. Falling back to files if nothing else matches is a bad idea, because that often means any incorrect input leads to files being completed.

In this case, the completion scripts had a bug, and I just fixed it. That's how it should be done.

**Comment by faroit** [comment]
@faho before I create a new issue, I wanted to know if this is related to what was mentioned by @mwyschan :

I usually create environments using prefix paths instead of global environments. Hence

```bash
❯ conda env list                                                      
  Name  Active  Path
────────────────────────────────────────────────────────────────────────────────────────────────
  base          /Users/xzy/micromamba
                /Users/xzy/repositories/x/envs/env_name
        *       /Users/xzy/repositories/y/envs/env_name
                /Users/xzy/repositories/z/envs/env_name
```

so when I want to activate an env, i type:

```
conda activate ./envs/env_name
```

from the project folder.
Fish, however doesn't autocomplete the path as its just searching for the named environments. Can we add path autocomplete here as well?

**Comment by faho** [comment]
> Can we add path autocomplete here as well?

Sure, if someone builds it. Regular file completion won't really do, you'd want to add those specific paths by parsing the `conda env list` update differently (or a second time) [here](https://github.com/fish-shell/fish-shell/blob/390b40e02b13326bbf4f638516d4bfb181fd7894/share/completions/conda.fish#L85-L87).

I don't think we need a dedicated issue for it, just open a PR if you want to add it.

**Comment by faroit** [comment]
@faho thanks for your response. Sounds good. I look into it and try to submit a PR. Just one thing to clarify:

> you'd want to add those specific paths by parsing the conda env list update differently (or a second time) [here](https://github.com/fish-shell/fish-shell/blob/390b40e02b13326bbf4f638516d4bfb181fd7894/share/completions/conda.fish#L85-L87).

looks easy to fix. One thing I noticed is that `mamba`/`micromamba` outputs differently than `conda`. 

```bash
❯ micromamba env list                                                      
Name  Active  Path
────────────────────────────────────────────────────────────────────────────────────────────────
base            /Users/xzy/micromamba
                /Users/xzy/repositories/x/envs/env_name
        *       /Users/xzy/repositories/y/envs/env_name
                /Users/xzy/repositories/z/envs/env_name
```


```bash
❯ conda env list                                                      
# conda environments:
#
base            /Users/xzy/conda
                /Users/xzy/repositories/x/envs/env_name
        *       /Users/xzy/repositories/y/envs/env_name
                /Users/xzy/repositories/z/envs/env_name
```

so the existing completion regex can't work on mamba. Should I address this as well or would this be better to be solved with starting a `mamba` complete? (tbh. i don't know where else they differ, according to the docs `mamba is a drop-in replacement and uses the same commands and configuration options as conda.`... unless when its not :-)
