### ISSUE TITLE
Support CTRL+Backspace and CTRL+Delete

### ISSUE THREAD

**Issue by cleverdripper** [fish-shell/fish-shell#1047]
It would make typing commands faster if CTRL+Backspace deleted the previous word and CTRL+Delete deleted the next word, like almost all text editors do.

**Comment by niedzielski** [comment]
I couldn't get control backspace working but here's my config:

    function fish_user_key_bindings
      # ctrl-del
      bind \e\[3\;5~ kill-word
    
      # ctrl-]
      bind \c] backward-kill-word
    end

**Comment by terlar** [comment]
`alt+backspace` also works out of the box for me.

Perhaps it is this binding: https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_default_key_bindings.fish#L85

**Comment by nh2** [comment]
For users of `gnome-terminal`, this will be useful: https://bugzilla.gnome.org/show_bug.cgi?id=733246

**Comment by nh2** [comment]
I'm using this with latest fish master ([cb984cf > 2.2.0](https://github.com/fish-shell/fish-shell/commit/cb984cf761debdc858db48065b2c1d94b31de49e)):

```
# Change Ctrl+w to delete up to the last whitespace;
# use Alt+Backspace for deleting path components.
#
# When https://bugzilla.gnome.org/show_bug.cgi?id=733246
# is fixed, I might switch to Ctrl+Backspace deleting
# up to the last whitespace instead.
bind \cw backward-kill-bigword
```
