### ISSUE TITLE
Undenied permission with brew?

### ISSUE THREAD

**Issue by nicdelillo-fitprime** [fish-shell/fish-shell#10478]
Hello,

macOS here. I installed fish with brew, but no matter what I get this. My config file and function and prompt won't load. I tried many solutions picked around here for the same error. But nothing seems to solve it.
Any Idea I could try out?

`
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.obQOQP': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.rwlmdt': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.15fW8W': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.V2TAo5': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.roMqeU': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.xGNkuu': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.AZl9v7': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.LVAKj5': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.guN6iO': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.W73t05': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.mPrkcq': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.xkwaue': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.9heZmZ': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.GLk2QF': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.Eufp5O': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.fT4owz': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.KGt9D7': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.19kBHm': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.Fv4x3b': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.sAkoIN': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.AAM7c5': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.76dmYe': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.cD8PyM': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.Rj3Yh7': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.69kzC2': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.NUen55': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.JdeKPh': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.zm2EWq': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.P6mNNK': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.3kQQuP': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.NY6i4x': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.T1vUKO': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.IBTCtC': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.p5p0XP': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.SPTDwF': Permission denied
error: Unable to open temporary file '/Users/nicola.delillo/.config/fish/fishd.tmp.YWVWXC': Permission denied
`

**Comment by faho** [comment]
That looks to me like it's $HOME/.config/fish, and that fish tries to use it to write its temporary files and it's not working. You should check the permissions on that directory (`ls -ld ~/.config ~/.config/fish`), and if it's not owned by your user `chown` it, or if it's just not writable `chmod` it.

**Comment by nicdelillo-fitprime** [comment]
Hi, thanks for the very quick reply. This solved the message error. But still the prompt  and the functions/variable I have set in ~/ .config/fish/  they are not picked up. These were working on my other laptop

**Comment by faho** [comment]
If the permissions for one directory got messed up, it's likely the permissions for files inside also got messed up. Check that the files all have the correct permissions and owner as well.

**Comment by nicdelillo-fitprime** [comment]
Yup Checked! Seems all goo

```
drwxr-xr-x  7 nicola.delillo  staff   224  4 May 08:38 .
drwxr-xr-x  3 root            staff    96  4 May 05:48 ..
drwxr-xr-x  2 nicola.delillo  staff    64  4 May 06:39 completions
drwxr-xr-x  2 nicola.delillo  staff    64  4 May 06:38 conf.d
-rw-r--r--  1 nicola.delillo  staff   424  4 May 05:50 config.fish
-rw-r--r--  1 nicola.delillo  staff  1578  4 May 08:38 fish_variables
drwxr-xr-x  5 nicola.delillo  staff   160  4 May 06:16 functions
```
and
```
drwxr-xr-x  5 nicola.delillo  staff   160  4 May 06:16 .
drwxr-xr-x  7 nicola.delillo  staff   224  4 May 08:38 ..
-rw-r--r--  1 nicola.delillo  staff    39  4 May 06:16 cdl.fish
-rw-r--r--  1 nicola.delillo  staff  3436  4 May 06:13 fish_pompt.fish
-rw-r--r--  1 nicola.delillo  staff   695  4 May 06:14 humanise_duration.fish
```

**Comment by faho** [comment]
Other than that ~/.config is still owned by root - which is generally an issue but shouldn't cause problems reading these files, I think.

Run

```fish
set --show XDG_CONFIG_HOME fish_function_path
```

**Comment by nicdelillo-fitprime** [comment]
Ah right! I can change it if need.

```
set --show XDG_CONFIG_HOME fish_function_path
$fish_function_path: set in global scope, unexported, with 6 elements
$fish_function_path[1]: |/Users/nicola.delillo/.config/fish/functions|
$fish_function_path[2]: |/opt/homebrew/etc/fish/functions|
$fish_function_path[3]: |/Users/nicola.delillo/.local/share/fish/vendor_functions.d|
$fish_function_path[4]: |/opt/homebrew/Cellar/fish/3.7.1/share/fish/vendor_functions.d|
$fish_function_path[5]: |/opt/homebrew/share/fish/vendor_functions.d|
$fish_function_path[6]: |/opt/homebrew/Cellar/fish/3.7.1/share/fish/functions|
```

**Comment by faho** [comment]
This includes "/Users/nicola.delillo/.config/fish/functions" as the first path, that means your cdl function or your fish_prompt should be picked up from there.

- unless, of course, something in your config changes these *after* those functions are loaded.

**Comment by nicdelillo-fitprime** [comment]
So I have checked the cdl function and works. The only thing it does not work is the config. I will look into that since I just cp those files from another working fish machine. I'd say this issue is the solved!
