### ISSUE TITLE
Test failures pre 3.8.0

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#10474]
The tests are failing on the package builders in a few places.

I'm filing an issue for posterity and also to make sure they actually get fixed.

1.  32-bit builds fail in src/tests/common.rs:127:

```
assertion `left == right` failed
  left: "-9223372036854775808"
 right: "0"
```
@KamilaBorowska spotted this one as the argument to sprintf being long, which is 32 bits on a 32-bit platform rather than defined as 64-bit.

2. 32-bit builds fail in src/wutil/wcstod.rs:575:9

```
thread 'wutil::wcstod::test::tests' panicked at 'assertion failed: `(left == right)`
 left: `Ok(8.925500000000001e-18)`,
 right: `Ok(8.9255e-18)`'
```
@mqudsi notes this is the wrong comparison to be doing as floating point values should be compared by epsilon

I don't know why these two aren't picked up by the 32-bit CI build.

3. Unwritable home directories make the history tests fail.

```
---- tests::history::test_history_formats stdout ----
thread 'tests::history::test_history_formats' panicked at src/tests/history.rs:561:32:
Failed to get data directory

---- tests::history::test_history_merge stdout ----
thread 'tests::history::test_history_merge' panicked at src/tests/history.rs:395:9:
assertion failed: history_contains(&everything, text)

---- tests::history::test_history_races stdout ----
thread 'tests::history::test_history_races' panicked at src/tests/history.rs:336:5:
assertion `left == right` failed
  left: 1
 right: 1025
```

HOME is set to something unwritable in the Debian package builds. This wasn't a problem pre-cargo test, because `tests/test_env.sh` was run beforehand. The cargo tests should be equally hermetic. It probably means reimplementing `test_env.sh` in Rust, because sourcing it before running `cargo test` stuffs up any rustup-installed toolchains.

**Comment by mqudsi** [comment]
I pushed some updates that got tests working for me targeting `i586-unknown-linux-gnu` under Debian 12 i686.

**Comment by mqudsi** [comment]
`test_history_formats` fixed in 476b360eb8f6492f891ab5edacfe3c7c08f934c6; everything should be passing now.

**Comment by mqudsi** [comment]
@zanchey tests appear to pass with the following under Debian 12 i686, which I assume does the trick for you?

```sh
set fish_home (mktemp -d)
sudo chown root:root $fish_home
env HOME=$fish_home cargo test --target i586-unknown-linux-gnu
```

(I don't actually run the last command as-is because `cargo test` actually calls `rustup` which uses `$HOME` for its own purposes; I actually run a bare `cargo test --target i586-unknown-linux-gnu` once which builds the test binary as `target/debug/i586-unknown-linux-gnu/fish-<hexadecimal-string>` then I run that binary with `env HOME=$fish_home`.)

**Comment by mqudsi** [comment]
@KamilaBorowska do you have any idea why the other 32-bit vs 64-bit errors didn't manifest under i686 but show up under i586? For example, I would expect the `snprintf` issue with `%ld` passed an `i64` to show up regardless of which particular 32-bit flavor we're targeting.

**Comment by zanchey** [comment]
This is all working ok now, and I fixed the issues with Ubuntu's lto-wrapper (which breaks for some reason when linking the cargo tests) with f4a79cc138.

**Comment by zanchey** [comment]
Unfortunately the 32-bit builds are failing on Debian again.

```
Testing file checks/math.fish ... Failure:

The CHECK on line 77 wants:
  1.316074

which failed to match line stdout:32:
  1.316075

Context:
  [...] from line 71 (stdout:29):
  1000000000000000
  100000000000000
  -1000000000000000
  1.316075 <= does not match CHECK on line 77: 1.316074
  4
  0
  1
  [...] from line 261 (stdout:77):
  2
  3
  0.841471
  -0.89001 <= does not match CHECK on line 283: -0.890009
  0.5
  4
  2

when running command:
  ../test/root/bin/fish checks/math.fish
```

and

```
---- tests::negative_precision_width stdout ----
thread 'tests::negative_precision_width' panicked at 'assertion failed: `(left == right)`
  left: `"78.900001   "`,
 right: `"78.900000   "`', printf/src/tests.rs:601:5

---- tests::test_float stdout ----
thread 'tests::test_float' panicked at 'assertion failed: `(left == right)`
  left: `"1.100001"`,
 right: `"1.100000"`', printf/src/tests.rs:359:5

---- tests::test_float_g stdout ----
thread 'tests::test_float_g' panicked at 'assertion failed: `(left == right)`
  left: `"1.23456789012346"`,
 right: `"1.23456789012345"`', printf/src/tests.rs:453:5

---- tests::test_locale stdout ----
thread 'tests::test_locale' panicked at 'assertion failed: `(left == right)`
  left: `"-46,380001"`,
 right: `"-46,380000"`', printf/src/tests.rs:702:9
```
