### ISSUE TITLE
feature request: support full CSIu kitty keyboard protocol

### ISSUE THREAD

**Issue by postsolar** [fish-shell/fish-shell#10470]
Fish version: `3.7.1-1795-g8639d7e45-dirty`

Currently fish does not support full CSIu protocol, which leads to issues with correctly detecting keyboard input. This was discussed [here](https://codeberg.org/dnkl/foot/issues/1642) and [here](https://github.com/fish-shell/fish-shell/pull/10359#issuecomment-2031173800).

The latter link also includes reproduction info.

**Comment by faho** [comment]
Fish does read shift-backspace in kitty, so this appears to be a foot issue to me?

I do not understand why shift-backspace would "resolve to text-only"

**Comment by krobelus** [comment]
this was not an issue for `shift-backspace` but only for other keys like `shift-space`.
Implemented in https://github.com/fish-shell/fish-shell/commit/681eb4e41004f8a7e94760810a1f6ee081543f36
