### ISSUE TITLE
Configure `backward-kill-path-component` to count `-` as a separator?

### ISSUE THREAD

**Issue by MarijnS95** [fish-shell/fish-shell#10475]
Currently on `fish, version 3.7.1` pressing <kbd>ctrl</kbd>+<kbd>w</kbd> considers `-` to be part of a word and not a "path separator", deleting it.

I come from a terminal (and may have manually configured) where that's not the case, so that <kbd>ctrl</kbd>+<kbd>w</kbd> only deletes up until `-`. I haven't been able to get used to loosing most of my command.

Some quick source-code diving shows that the collection of characters is currently hardcoded:

https://github.com/fish-shell/fish-shell/blob/b5624f2e81c7ed67caf5fc34e4b45b0016dffcd0/src/tokenizer.rs#L1290-L1292

How crazy would it be to request a configuration parameter to change or extend that list? Thanks!

**Comment by faho** [comment]
This is not the sort of thing we make configurable, sorry.

**Comment by krobelus** [comment]
use `alt-b,alt-d`.
If you really want to override `ctlr-w` you cando something like

	bind \cw begin-selection backward-word kill-selection end-selection

**Comment by MarijnS95** [comment]
@faho any reason for that?

@krobelus thanks for bringing up <kbd>alt</kbd>+<kbd>b</kbd> (and also <kbd>alt</kbd>+<kbd>f</kbd>), that is one more reason why `-` naturally counts as a separator in my terminal motions.

Your suggestion works flawlessly out of the box, I'll keep using that!
