### ISSUE TITLE
ALT - Up Arrow should take to parent directory

### ISSUE THREAD

**Issue by siteshwar** [fish-shell/fish-shell#1048]
`ALT - Left Arrow` and `ALT - Right Arrow` are used to move back and forth across working directories. I believe it would be very helpful if `ALT - Up Arrow` takes user to parent directory of current working directory.

**Comment by faho** [comment]
This has been bound to history-token-search for a while now, and these two seem fundamentally at odds.

So I'm closing this, sorry!
