### ISSUE TITLE
fish_variables has too large size make fish has a significant delays during startup

### ISSUE THREAD

**Issue by tianshihao** [fish-shell/fish-shell#10488]
**YOUR TEXT HERE**

#### Here is my environment: 
```shell
$ fish --version
fish, version 3.1.0

$ uname -a
Linux lixiang-HP-Z4-G4-Workstation 5.15.0-105-generic #115~20.04.1-Ubuntu SMP Mon Apr 15 17:33:04 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

$ echo $TERM 
xterm-256color
```

And I didn't try fish using `sh -c env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish`.

####  Observation

I noticed that my fish shell was experiencing significant delays during startup(in minutes). Upon investigation, I discovered that the `fish_variables` file located in my `~/.config/fish` directory had ballooned to a hefty size of 3MB. Deleting this file resolved the slow startup issue.

#### How to reproduce
However, I observed a pattern: with every launch of the fish shell, a temporary file is generated within `~/.config/fish`. Upon exiting the shell, this file is amalgamated into the `fish_variables` file, increasing its size by approximately 0.1KB each time. Over time, the gradual accumulation leads to a substantial expansion of `fish_variables`, which in turn causes the fish shell to take longer to start up.

This behavior suggests that there may be a bug causing an unnecessary growth of `fish_variables`, directly impacting the startup performance of the fish shell.

**Comment by faho** [comment]
fish_variables is the store for fish's universal variables. This happens when you append to a universal variable, including in config.fish.

E.g. if you put this in your config.fish:

```fish
set -U foo $foo bar
```

it will increase in size.

> This behavior suggests that there may be a bug causing an unnecessary growth of fish_variables, directly impacting the startup performance of the fish shell.

I'm about 98% confident that the issue is in your configuration, as this is a reasonably common mistake.
