### ISSUE TITLE
Oh, I have to pass the argument with quotes, I see. But this one is not working for me

### ISSUE THREAD

**Issue by ALEX5402** [fish-shell/fish-shell#10484]
Oh, I have to pass the argument with quotes, I see.

That will work but I was hoping to be able to pass the argument without quotes, to have the function add them. Is this possible?

I tried:

```
function ytd
    youtube-dl -t "$argv[1]"
end
```

_Originally posted by @ElijahLynn in https://github.com/fish-shell/fish-shell/issues/1965#issuecomment-76740588_

here is the output i tryed but it does't works on me

`fish: No matches for wildcard 'https://youtu.be/HPGvrxjT7aY?si=94x7gGDp76rTI4dX'. See `help wildcards-globbing`.
ytd https://youtu.be/HPGvrxjT7aY?si=94x7gGDp76rTI4dX
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
`

**Comment by faho** [comment]
No, you need to pass the outer argument with quotes.

This works:

```fish
function ytd
    youtube-dl -t $argv[1]
end

ytd "https://youtu.be/HPGvrxjT7aY?si=94x7gGDp76rTI4dX"
```

You need to quote the argument where the string is - the `?` is special, so that needs to be quoted where it is, not *later*.
