### ISSUE TITLE
Different descriptions of Universal variables in the documentation

### ISSUE THREAD

**Issue by lamb007** [fish-shell/fish-shell#10489]
fish, version 3.7.1
Is the scope of Universal variables in fish all user or one user?
In the document https://fishshell.com/docs/current/language.html#variables-universal, the description of universal variable is 'Universal variables are variables that are shared between all the user’s fish sessions on the computer'
And in the document https://fishshell.com/docs/current/language.html#variables-scope, the description of universal variable is 'Universal variables are shared between all fish sessions a user is running on one computer'
I did some simple tests：
```bash
❯ set -U fish_color_autosuggestion 555                                                                           

❯ echo $fish_color_autosuggestion                                                                                
555

❯ su        # change to root

❯ echo $fish_color_autosuggestion
brblack
```
The root user and myself output different results, so I guess the scope of universal variables should be one user?
I don't know if there is an error in my testing process. If there is, please point it out. Thank you for your time.

**Comment by faho** [comment]
> shared between all the user’s fish sessions 

This is to be read as "all fish sessions of this particular user".

*the user* here refers to the unix concept of the user. `su` *s*witches *u*ser to root.
