### ISSUE TITLE
Alias escaping

### ISSUE THREAD

**Issue by DieracDelta** [fish-shell/fish-shell#10496]
Version info: `fish, version 3.7.0`, NixOS 23.11.

Feature request, not a bug report. Is there a way to escape an alias? For example, I have cat aliased to bat. In bash and zsh, when I wanted to cat something using cat, I would do `\cat` and this would undo the alias. But in fish this syntax doesn't work. As a workaround I'm just doing `\usr\bin\env cat` in fish. I'm wondering if there's either: (1) a way to match the bash behavior (maybe using abbreviations?) or (2) plans to add this behavior.

Thanks!

**Comment by faho** [comment]
Use `command cat`.
