### ISSUE TITLE
Not able to `ctrl+c` out of `fzf`

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#10504]
Using https://github.com/fish-shell/fish-shell/commit/cbb399f2eda690fc1cd17a0d4c2dffd068696c45 and iTerm 2 (v3.4.23)

---

To reproduce, just hit an `fzf` keybinding and then `ctrl+c` to exit. Then observe:

<img width="107" alt="image" src="https://github.com/fish-shell/fish-shell/assets/8544900/c020547f-ab89-419e-8ec5-938afebc7fa6">

Started happening around @krobelus' https://github.com/fish-shell/fish-shell/commit/29f2da8d186e5267f4b320aa6966c3e5d7aadca4 commit, so I suspect it's related.

**Comment by mqudsi** [comment]
Yeah, I ran into this yesterday. Didn't realize it was that recent of a regression, though.
