### ISSUE TITLE
Add command to get flag description from completions

### ISSUE THREAD

**Issue by Undeterminant** [fish-shell/fish-shell#1050]
For example, if the command were named `optdesc`, running:

```
optdesc gcc -ffast-math
```

Would yield:

```
Sets -fno-math-errno, -funsafe-math-optimizations, -ffinite-math-only, -fno-rounding-math, -fno-signaling-nans and -fcx-limited-range.
```

**Comment by krader1961** [comment]
Closing because it's a very old issue with no discussion and no clear justification why it should be implemented. Feel free to reopen if you can provide use cases showing how this would be used and which justify the cost of implementing something like this.
