### ISSUE TITLE
Paging command output as if it was written to a terminal

### ISSUE THREAD

**Issue by ahupp** [fish-shell/fish-shell#10501]
The problem I'm trying to solve: Some commands change their output depending on whether stdout is a terminal or a pipe/file.  e.g, ripgrep will enable color by default, and changes the output format:

![image](https://github.com/fish-shell/fish-shell/assets/40594/26d5a7eb-2801-4cf9-8764-970d0af1a5df)

But when I pipe to another command it looks like:

![image](https://github.com/fish-shell/fish-shell/assets/40594/67031e65-5089-4b7d-b885-a12e2bfe0eb8)

I often want to use a pager with the output while still retaining the terminal-specific behavior.   Usually there's flags that enable this (e.g `rg --color=always ... | less -R`, though I don't see a way to change the layout), but it would be much nicer if there was shell support for this, either via a builtin pager or by pipe syntax that makes the pipe pretend to be a psuedoterminal.

$ fish --version
fish, version 3.7.0
$ echo $TERM
xterm-256color
$ uname -a
Darwin oai-adamh 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020 arm64

**Comment by krobelus** [comment]
fish is not currently a terminal but your terminal might support it (for example via OSC 133 https://codeberg.org/dnkl/foot/#piping-last-command-s-output or tmux)

**Comment by mqudsi** [comment]
`socat` can do this for you, without any support from the terminal or the shell.

    socat - EXEC:'ls --color=auto',pty,setsid,ctty | less -

You'll see that though we are using auto color mode and piping into `less`, we still get color output (and should be piping into `less -R` instead).

For apps like `rg` that use auto color mode as the default, they'll "just work" as you ask:

    socat - EXEC:'rg . -l',pty,setsid,ctty | less -R
