### ISSUE TITLE
fish became slow because checking two tools

### ISSUE THREAD

**Issue by Kodp** [fish-shell/fish-shell#10503]
`fish, version 3.7.1`

execute 
```sh
fish --profile /tmp/fish.prof -c fish_prompt
cat /tmp/fish.prof | sort -h
```
The last two rows: 
```
114493  114493  -----> not command -sq fossil
358012  358012  -----> not command -sq hg
```
these two command takes a lot of time. I don't know why this is happening, it makes my fish slow down.

My environment is in wsl2.

**Comment by mqudsi** [comment]
What's your `$PATH` under WSL2? WSLv1 (and I think WSLv2, but I'm not sure) have an insanely long PATH by default.

**Comment by Kodp** [comment]
Actually, I checked the path before, but I didn't think it was too long at the time because it can be that long under Windows; Then I compared it with another server and found that it was indeed quite long.... Thanks! Problem solved.  But I still have a question. It seems that having a long PATH under Windows does not significantly slow down PowerShell or even when using oh-my-posh, does it?

**Comment by Kodp** [comment]
Thank you for your very good answer

**Comment by Kodp** [comment]
Thank you for your very good answer

**Comment by mqudsi** [comment]
For reference, this was closed by the combination of 3374692b9113e85c690059ac3def5f4aa190294f (which is #10506) and 8c62f733b33214c71c2bed3bb14215c9bc27e991 (which extended that to WSLv2).

**Comment by krobelus** [comment]
do we want changelog entries for these fixes?

**Comment by mqudsi** [comment]
> do we want changelog entries for these fixes?

Definitely for this one. I already tagged the PR with the release notes label.

**Comment by krobelus** [comment]
> I already tagged the PR with the release notes label.

As far as I see it the process for changelog is to look at every issue/PR that is not yet mentioned in CHANGELOG.rst (and belongs to the relevant milestone).
So I don't use labels for this (or anything else).

**Comment by mqudsi** [comment]
I don't know myself, I think it's something I saw others doing :) 
But I added this to the changelog.
