### ISSUE TITLE
cannot execute shell script use ". filename"

### ISSUE THREAD

**Issue by Juude** [fish-shell/fish-shell#1051]
when I execute . build/envsetup.sh in fish,I got errors like this

    "	called on standard input,
    fish: Illegal command name “}” }
    "
but if I type "bash build/envsetup.sh"
I can get the right result

**Comment by faho** [comment]
We've discussed the shebang thing elsewhere, and that's rather complicated. Anyway, executing a bash script with fish won't work, so this is invalid.
