### ISSUE TITLE
Prompt is arbitrarily(?) redrawn while typing

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#10529]
Using https://github.com/fish-shell/fish-shell/commit/d5101e192309e5f0d0c9a01569b16f463062d4f1, and recently updated to iTerm 2 (v3.5.0)

---

I'm struggling to figure out how to reproduce this, but a change in the last 1-2 weeks (either in fish or iTerm) has caused my prompt to seemingly arbitrarily be redrawn while I'm typing a command. I am trying to reproduce it now and will update this bug report as I learn more, but it has been happening a few times a day and I can't quite figure out what it could be.

Any pointers to narrow it down would be appreciated.

---

**Edit:** Ok, so I have managed to reproduce it...

1. Define the following `fish_prompt`

```fish
function fish_prompt
    echo ---
    echo '$ '
end
```

2. Create a Git repository with some bogus data

```fish
$ git init tmp
$ cd tmp
$ touch foo
$ git add foo
$ git commit -m foo foo
$ git checkout -b a/b/c
```

3. Type `git checkout a/` and hit `<tab>` and observe the prompt repainted

![image](https://github.com/fish-shell/fish-shell/assets/8544900/5d42bd2b-18bf-45a4-a848-4ec23b6fecd0)

**Comment by faho** [comment]
I can't reproduce this on my linux machine and I do not have access to iTerm.

Can you try in terminal.app?

**Comment by 0ion9** [comment]
kitty 0.35 : Can sort-of reproduce: The first time I hit `tab`, `a/b/c` is completed but there is no redraw. If I then immediately hit tab again (without deleting anything or hitting any other keys; so, the cursor is on blank space before I hit tab), the prompt is redrawn.

xterm 392: Same behaviour as with kitty.

sakura 3.8.7 : Cannot reproduce; no attempt to tab-complete causes any redraw of the prompt, at least in the stated scenario.
