### ISSUE TITLE
Confusing "highlighting" when path argument contains >1 `**`

### ISSUE THREAD

**Issue by 0ion9** [fish-shell/fish-shell#10522]
Take a command such as `ls /etc/**/**/**/`.  Try entering that gradually, and watch how the highlighting changes as the number of wildcards changes : 
1. `ls /etc/**/**` : wildcards are shown normally (all in yellow, in my case)
2. `ls /etc/**/**/` : the first `/**` is "highlighted" in black (so it becomes invisible: the display shows `ls /etc   /**/`)
3. `ls /etc/**/**/**/` : the first `/**/**/*` is "highlighted" in black (the display shows `ls /etc        */`)
4. If you continue to add instances of `**/` to the argument, the display is then consistent in the way that it is wrong: it resembles 3); every character after `/etc` and before the final `*/` will be "highlighted" in black.

The text in the 'executable' position doesn't matter ( for example the highlighting behaves the same when `echo` is the command rather than `ls`).

fish: 3.7.1-1947-g537cde0c7
Behaviour occurs even when run without third-party customizations: Yes

EDIT:
Terminal: Kitty 0.33 (behaviour also manifests in git pre-0.35)

**Comment by faho** [comment]
I can't reproduce.
![Screenshot_20240525_125202](https://github.com/fish-shell/fish-shell/assets/5185367/e70180a6-bfc7-434d-bbee-aa0512f9465d)

**Comment by 0ion9** [comment]
Hmm. I tested with a few different terminal emulators, including the one I mainly use, kitty 0.33:

Xterm: Doesn't reproduce
Sakura: Doesn't reproduce
Kitty: Reproduces

I guess this is actually a kitty bug then (unless fish does anything different with color codes when kitty is detected).

**Comment by faho** [comment]
I also cannot reproduce it with kitty.

We *do* now send a bunch of things to enable functions in kitty, but for the most part they're related to input (key detection etc). They are send unconditional but some of them will only take effect in kitty. It seems unlikely that they would change anything.

To debug this, you'd want to record a fish session with asciinema or `script` in kitty and a working terminal. You would also check kitty's shell integration.

**Comment by 0ion9** [comment]
I guess I can do an asciinema, it may provide slightly more detailed information.
I also just tried upgrading kitty 0.33-> git pre-0.35, which replaces the shell integration too; it didn't change anything about the behaviour I describe, either with my normal config or a clean config. I can confirm at least for 0.35, __ksi_schedule appears to be being called normally (and seems to contain nothing relating obviously to color); I'm not sure what else I should check regarding shell integration.

**Comment by faho** [comment]
> EDIT2: asciinema uploaded [here](https://asciinema.org/a/jYwgBxMTy9piYjc3hWMjssVkr), just in case. This is the kitty recording, and as expected, the asciinema website displays it without any blank areas.

I cannot see any blank areas playing this back in kitty (0.35.0, no configuration) either.

There is also nothing special in the recording. The `*` are drawn like

```
\u001b[96m*\u001b[30m\u001b(B\u001b[m\r\u001b[30C
```

That's `\e[96m` (bright cyan), the `*`, return to black, reset styling, return to column 0, move to column 30.

Which is wasteful and can be optimized, but there's nothing *wrong* here. The color is always *set* when we print a `*`, so it should be shown in that color.

So if that recording shows blanks in your kitty, the most likely explanation is a misconfiguration (e.g. you set a color in the palette to the color of the background) or bug in kitty.

**Comment by 0ion9** [comment]
True. I concluded it was the line `font_family	Fantasque Sans Mono Regular`. Which is weird because that font appears to exist, and the other settings (bold_font, italic_font, bold_italic_font) do not cause problems (they were already set to the corresponding styles of Fantasque Sans Mono).

I'll close this. Maybe I'll open a kitty bug if I ever figure out why that particular setting is somehow different from the others.
