### ISSUE TITLE
Trying to generate a fun string when I start a new fish shell session (new tab, or source)--not quite working

### ISSUE THREAD

**Issue by mearleycf** [fish-shell/fish-shell#10533]
Fish version: fish, version 3.7.1
OS: Darwin Kernel Version 23.5.0 root:xnu-10063.121.3~5/RELEASE_ARM64_T8122 arm64
Terminal: xterm-kitty (the issue happens in other terminals)
Yes I executed fish without third party customizations, the issue persists. 

---
I have a function, greeting.fish, which generates a VERY SERIOUS random string of text (just kidding, it's just warhammer 40,000 quotes) and prints it on screen when a new session is started--say by opening a new tab, or sourcing config.fish. 

```# ~/.config/fish/functions/greeting.fish
function greeting
    # Ensure colors are set (if needed)
    if not set -q color_brightgreen
        source ~/.config/fish/functions/colors.fish
        set_colors
    end

    # Define a list of greeting messages using arrays
    set messages \
        'set_color $color_brightgreen; echo -n "Victory "; set_color $color_purple; echo -n "is but a prelude to the next battle, $USER."; set_color normal' \
        'set_color $color_purple; echo -n "The "; set_color $color_blue; echo -n "enemy of my enemy "; set_color $color_purple; echo -n "is still my enemy, $USER."; set_color normal' \
        # more messages, truncated for brevity

    # Pick a random message
    set message (random choice $messages)

    # Set the command line to the chosen message without clearing the screen
    eval $message
end
```

The colors are coming from a fish function called colors.fish, it's just a file that runs a function that does a bunch of this:
```    set -g color_slateblue '495495'
    set -g color_mintgreen '0beb99'
    set -g color_brightgreen '84dd29'
    set -g color_lightgreen 'adff56'
```
So I can use those colors in other functions without having to look up hex values every time. 

The problem is, when I open a new tab, the greeting.fish function DOES run--but it disappears almost immediately. You can see it briefly appear on screen, then disappear. But if I subsequently source config.fish, in the same session, the greeting stays. I'm not sure why the behavior differs between the two methods of starting a session. 

You can (sort-of) see the issue I'm referring to, here:
[![asciicast](https://asciinema.org/a/ZHcwmSc7OgWSOWAlD4h1gvZ5U.svg)](https://asciinema.org/a/ZHcwmSc7OgWSOWAlD4h1gvZ5U)

**Comment by faho** [comment]
Here's your problem:

```fish
echo -n "
```

Your greeting is not ending in a newline, so fish simply overwrites it with the prompt.

You probably just want to add `echo` after you print the message, or change the last `echo -n` to just `echo`.

Also as a sidenote if you name your function `fish_greeting` fish will run it automatically and you don't need to call it manually.

**Comment by mearleycf** [comment]
Thank you very much. I changed any of the messages with a second echo function to remove the -n, or remove it from the first echo if there's only one echo command in the message. 
I also changed the name to fish_greeting and ran funcsave, it's loading correctly now. 👍 🚀
