### ISSUE TITLE
Build fails without a C++ compiler

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#10549]
Just logging this to look into later, but trying to build the project without a working C++ compiler currently errors out. The readme states it should be able to build it without a C++ compiler.

```
cd build; cmake .. -G "Ninja" \
        -DCMAKE_INSTALL_PREFIX="/usr/local" -DCMAKE_EXPORT_COMPILE_COMMANDS=1
-- The CXX compiler identification is unknown
CMake Error at /usr/share/cmake-3.22/Modules/CMakeDetermineCXXCompiler.cmake:226 (configure_file):
  Operation not permitted
Call Stack (most recent call first):
  CMakeLists.txt:8 (project)


CMake Error at CMakeLists.txt:8 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/home/mqudsi/random/fish-shell/build/CMakeFiles/CMakeOutput.log".
See also "/home/mqudsi/random/fish-shell/build/CMakeFiles/CMakeError.log".
make: *** [GNUmakefile:46: build/build.ninja] Error 1
```

**Comment by zanchey** [comment]
The README says you need a C++11 compiler for the tests. However, `project(fish)` without any `LANGUAGES` specified will [default to C and CXX](https://cmake.org/cmake/help/latest/command/project.html#options), so maybe try using `project(fish LANGUAGES C)`.

Then `enable_language(CXX)` or maybe a [`CheckLanguage` stanza](https://cmake.org/cmake/help/latest/module/CheckLanguage.html) will be needed in the test targets.
