### ISSUE TITLE
Weird error whenever I open terminal

### ISSUE THREAD

**Issue by DavidRLTG** [fish-shell/fish-shell#10558]
**YOUR TEXT HERE**
version: 3.3.1
I am using Linux Mint Virginia
I tried to install the Tide Theme with fisher, but it failed. Now I always get this error when opening terminal. Hence, if I run the command, it is fixed.
To reproduce the problem, try installing tide on Linux Mint Virginia (fresh install) with fisher, and it fails.

The error:
`~/.config/fish/functions/fish_prompt.fish (line 155): $(...) is not supported. In fish, please use '(commandline)'.
        if commandline --is-valid || test -z "$(commandline)"
                                              ^
from sourcing file ~/.config/fish/functions/fish_prompt.fish
in command substitution
source: Error while reading file “/home/davidrltg/.config/fish/functions/fish_prompt.fish”
`

**Comment by faho** [comment]
> version: 3.3.1

This version is quite old and no longer supported by tide - [which currently requires fish 3.6.4](https://github.com/IlanCosman/tide?tab=readme-ov-file#system-requirements).

Fish 3.3.1 is 16% of all commits ever made to fish behind, it is 4 non-patch releases out of date.

You can install a newer fish through our PPAs, see https://fishshell.com/ - Linux Mint most likely means you want the one for Ubuntu.

**Comment by DavidRLTG** [comment]
Nevermind, I reset fish and its fixed.

**Comment by faho** [comment]
@DavidRLTG It isn't fixed, you're just no longer using tide.

The error happens because tide does something that your old fish version doesn't understand. To fix it and be able to use tide you need to upgrade fish.
