### ISSUE TITLE
fish: Unknown command: __history_previous_command_arguments

### ISSUE THREAD

**Issue by mvartuc** [fish-shell/fish-shell#10566]
Please tell us which fish version you are using by executing the following:

  fish --version
  echo $version

`fish, version 3.7.1`

Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

`  System Version:	macOS 14.5 (23F79) | Kernel Version:	Darwin 23.5.0`

Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:

  sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'

` This fixed the issue but I'd like to keep my third party customizations`

Tell us how to reproduce the problem. Including an asciinema.org recording is useful for problems that involve the visual display of fish output such as its prompt.

Every time I try inputting the character '$' in my terminal I get the following error: 
`fish: Unknown command: __history_previous_command_arguments`
For example `echo $TERM` command can't be executed, cause after I input the '$' the rest of the command vanishes and gets replaced by the error message above like so:

<img width="860" alt="image" src="https://github.com/fish-shell/fish-shell/assets/57680600/cb5e6ec0-2bc2-4671-a080-3a26ccbce0aa">

Is there any way I can investigate which 3rd party extension is causing this?

**Comment by faho** [comment]
In this case, just searching for the function name on Github's search yields:

https://github.com/oh-my-fish/plugin-bang-bang/blob/ec991b80ba7d4dda7a962167b036efc5c2d79419/conf.d/plugin-bang-bang.fish#L7

It's oh-my-fish's plugin-bang-bang.
