### ISSUE TITLE
UX: History pager changes number of columns while typing

### ISSUE THREAD

**Issue by Ansimorph** [fish-shell/fish-shell#10561]
Fish 3.7.1 / OSX

The history pager started via `CTRL-R` changes the number of columns as a user is typing. Although this allows for dense packing of information, it makes the results hard to scan because the structure of the information constantly changes.

possible solutions:
- always set the history pager to one column
- expose the max column constant for history to users so they can set it to a value that makes sense for them

**Comment by faho** [comment]
Gonna be honest I think we're happy with how things are at the moment, and an option here would be uncharacteristic for us.

Sorry, but no.
