### ISSUE TITLE
Is possible to detect if an auto-suggestion is being displayed?

### ISSUE THREAD

**Issue by Susensio** [fish-shell/fish-shell#10580]
fish, version 3.7.1

I'm trying to create a conditional binding based on the current state of autosuggestion:
`\cl` should accept line if autosuggestion present, clear screen otherwise.

I've found this issue https://github.com/fish-shell/fish-shell/issues/5000 that addresses this topic.
It appears that testing commandline autosuggestion was once possible (https://github.com/fish-shell/fish-shell/commit/dc17869a84f671c0395a38a7bc6827a44d7d6e88) but this stopped working (https://github.com/fish-shell/fish-shell/commit/73998b81b4441d15ed039a46354eb9a93b8b8368)

What is the alternative? Is there any other way of knowing if autosuggestion is present on the commandline?

**Comment by mqudsi** [comment]
I can't think of an obvious alternative for you, but I've opened #10586 that would implement this as `commandline --showing-suggestion`.
