### ISSUE TITLE
OBS GPG keys have expired 2024-06-21

### ISSUE THREAD

**Issue by ealap** [fish-shell/fish-shell#10581]
It seems it's that time of the year again, can you please refresh your release keys for Debian?

![image](https://github.com/fish-shell/fish-shell/assets/15620712/6ab32916-89af-40d6-9574-77feb7bee8dd)

![image](https://github.com/fish-shell/fish-shell/assets/15620712/960f45c0-ff32-4522-a3e8-c7d447db099f)

Thank you!

**Comment by zanchey** [comment]
I ran the update three weeks ago (there's a cronjob reminder). You may need to refresh the key, eg https://github.com/fish-shell/fish-shell/issues/8162#issuecomment-885955417

(Not sure what is going on with your terminal, I can barely read the text.)

**Comment by jdmartin** [comment]
Hi!  Sorry to say that I've also been having this problem.  I tried following the comment you referenced.  I removed the existing keys, and followed the instructions ([here](https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A3&package=fish)) to install the key for Debian 12.  Unfortunately, I'm still seeing this when I try an apt-get update:

<img width="1562" alt="Screenshot 2024-06-22 at 1 03 16 AM" src="https://github.com/fish-shell/fish-shell/assets/1966209/d6f14b1e-ef70-4156-a0e3-eb88cd01ffb6">

With the caveat that I could very well be missing something, would you be able to offer any advice?  Thanks!

**Comment by aureq** [comment]
Effectively, the current key available on OpenSuse has **expired**. Here is how to quickly check.

```bash
wget -q -O - https://download.opensuse.org/repositories/shells:fish:release:3/Debian_12/Release.key | gpg 
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa2048 2013-10-08 [SC] [expired: 2024-06-21]
      24A63B31CAB41B33EC48801E2CE2AC08D880C8E4
uid           shells:fish OBS Project <shells:fish@build.opensuse.org>
```

**Comment by zanchey** [comment]
I'll try and trigger a repository rebuild as it doesn't look like the new key gets pushed without it. I had a dummy package for doing that, but will have to redo it.

**Comment by zanchey** [comment]
As a workaround, try:

```sh
curl "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x24a63b31cab41b33ec48801e2ce2ac08d880c8e4" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg > /dev/null
```

**Comment by zanchey** [comment]
As a workaround, try:

```sh
curl "https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x24a63b31cab41b33ec48801e2ce2ac08d880c8e4" | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg > /dev/null
```

**Comment by zanchey** [comment]
OK, should be fixed now:

```
> curl https://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_11/Release.key | gpg --show-keys
pub   rsa2048/0x2CE2AC08D880C8E4 2013-10-08 [SC] [expires: 2026-08-11]
...
```

So, for my reminder next time, what is needed is:

```fish
osc signkey shells:fish --extend
osc copypac home:Zanchey c11test shells:fish
osc copypac home:Zanchey c11test shells:fish:release:3
sleep 600
osc rdelete shells:fish c11test -m "drop dummy package, only used for rebuilding repo metadata"
osc rdelete shells:fish:release:3 c11test -m "drop dummy package, only used for rebuilding repo metadata"
echo 'echo "See https://github.com/fish-shell/fish-shell/issues/10581 for instructions" | mail -s "Update fish OBS project signing key" zanchey' | at now + 26 months'
```

This can go in a GitHub action at some stage; probably extending the key every month or so is a good idea.

Also, the key still needs to be refreshed manually by end-users:

```
curl -fsSL https://download.opensuse.org/repositories/shells:fish:release:3/Debian_11/Release.key | 
gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/shells_fish_release_3.gpg > /dev/null
```
