### ISSUE TITLE
Default completion for less doesn't include all options

### ISSUE THREAD

**Issue by visrosa** [fish-shell/fish-shell#10595]
In case it matters, I'm using fish 3.7.1 on Linux  6.5.0-41-generic #41~22.04.2-Ubuntu SMP PREEMPT_DYNAMIC Mon Jun  3 11:32:55 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

I was  looking for the color output option for less with `less -[tab][tab]` since I didn't remember the exact spelling and I noticed that the autocompletion didn't list that one.

If I delete /usr/share/fish/completions/less.fish and regenerate from the man pages the options do get listed.

Is the non-exhaustive completion options by design? If this is not a feature, is a PR welcome? For `less` and whatever else I find missing completions? Any guidelines? I am aware some programs have different variants (gnu, busybox, etc) and will keep that in mind.

**Comment by ridiculousfish** [comment]
#10596 - thank you!
