### ISSUE TITLE
fish_config broken under WSLv1

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#10590]
I noticed a while back that at some point help files began opening with a pseudo-unc path beginning `\\wsl.localhost\` instead of with the `C:\`-mapped path and that was causing them to load significantly slower than before.

Today I discovered that `fish_config` now no longer works at all under WSLv1; it opens a web browser but the following is written to the terminal:

```
> fish_config
Web config started at file:///tmp/web_configzrjbms2h.html
If that doesn't work, try opening http://localhost:8001/49b7bd5a8c3dfc51cdec34faecb4b69b/
Hit ENTER to stop.
Shutting down.
              '\\wsl.localhost\Legacy\usr\local\share\fish\tools\web_config'
CMD.EXE was started with the above path as the current directory.
UNC paths are not supported.  Defaulting to Windows directory.
```

The browser attempts to load the URL in question but it just spins and never goes anywhere.

**Comment by zanchey** [comment]
This is working ok for me on WSLv1 with Debian 12 as the Linux distribution, as of d19e5508d.

I get the warning about the UNC path but the server still runs fine.

**Comment by mqudsi** [comment]
Does the browser resolve the path for you and load the page?

**Comment by zanchey** [comment]
Yep!

**Comment by mqudsi** [comment]
Ok maybe it was just my pc; I had weird timeouts accessing the WSL share. That install is now hosed, so I'll just close this out. Thanks!
