### ISSUE TITLE
Feature request: add `funcat` to the `funcsave` `funced` familly?

### ISSUE THREAD

**Issue by stephane-archer** [fish-shell/fish-shell#10609]
we have `funcsave` `funced` but I just want to see what the function does and see the usage comment to use it correctly
```
function funcat
    # usage: argv should be a fish function name
    funced -e cat $argv
end
```

**Comment by Xiretza** [comment]
You can use `type`, it even does syntax highlighting.

**Comment by zanchey** [comment]
`functions` is the canonical interface, probably that should be linked from the `funced`/`funcsave` documentation.
