### ISSUE TITLE
Argument is not a number: 'Alacritty'

### ISSUE THREAD

**Issue by RandomLegend** [fish-shell/fish-shell#10607]
Fish version 3.7.1 - no plugins
Alacritty terminal
___

After using yay -Syu or flatpak update for example i get this "error":

```
Argument is not a number: 'Alacritty'
~/.config/fish/conf.d/done.fish (line 152):
        and test $__done_initial_window_id -eq (hyprctl activewindow | awk 'NR==13 {print $2}')
            ^
in function '__done_is_process_window_focused'
	called on line 222 of file ~/.config/fish/conf.d/done.fish
in function '__done_ended' with arguments 'update'
in event handler: handler for generic event “fish_postexec”
```

i am on hyprland and see something with hyprctl activewindow.

Is this an error on fish or hyprland?

**Comment by Xiretza** [comment]
What is `~/.config/fish/conf.d/done.fish`? Please paste the content or a link to an upstream here.

`test -eq` compares numbers, and either `$__done_initial_window_id` or the `hyprctl` command evaluate to the string "Alacritty", so that's the error you get.

**Comment by zanchey** [comment]
It's from https://github.com/franciscolourenco/done

**Comment by Xiretza** [comment]
Looks like it may have been fixed [here](https://github.com/franciscolourenco/done/commit/64f83d4b598fee61e6b73345f5ab78e09e1ef5d2) - either way, it's an issue with that script, not fish itself.

**Comment by RandomLegend** [comment]
Yes, thanks didn't know this was a plugin and it was preinstalled by something idk.

After deleting it and installing it again properly it works.
