### ISSUE TITLE
Inconsistent literalization behavior of `{ ... }` context

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#10610]
Text in curly `{ .. }` braces subject to expansion (i.e. with at least one `,`) is neither consistently expanded nor treated as a literal expression.

* `echo {*,}` behaves as you would expect; it tokenizes akin to `echo *` with the `*` being treated as a wildchar globbing character
* `echo {~/,}` behaves differently (imho, incorrectly), acting as if you executed `echo '~/'` and not like `echo ~/`

This inconsistent tokenization doesn't make sense and I do not believe it is intentional.

**Comment by krobelus** [comment]
yeah I think this should be fixed

**Comment by zanchey** [comment]
This occurs at least as far back as 3.0.2, which the oldest version I have on hand.
