### ISSUE TITLE
misleading suggestion to use a bracketed variable

### ISSUE THREAD

**Issue by Veraellyunjie** [fish-shell/fish-shell#10618]
```
> fish --version
fish, version 3.7.0
```
```
> VAR_1="${VAR_2}"_and_some_stuff  # sh-style
fish: Unsupported use of '='. In fish, please use 'set VAR_1 "${VAR_2}"_and_some_stuff'.

```
OK, let us use that:
```
> set VAR_1 "${VAR_2}"_and_some_stuff
fish: Variables cannot be bracketed. In fish, please use "$VAR_2".
set VAR_1 "${VAR_2}"_and_some_stuff
            ^
```
So, fish recommends a wrong syntax.
Perhaps, it should print both errors outright and suggest a correct version from the 1st try:
```
> VAR_1="${VAR_2}"_and_some_stuff
fish: Unsupported use of '='
VAR_1="${VAR_2}"_and_some_stuff
     ^
fish: Variables cannot be bracketed
VAR_1="${VAR_2}"_and_some_stuff
        ^
fish: In fish, please use 'set VAR_1 "$VAR_2"_and_some_stuff'.
```

**Comment by faho** [comment]
Gonna be honest: This could only really be solved in general if fish contained an entire posix-to-fish translator, and that's a staggering task that we have declined numerous times.

The "in fish, please..." things are a simple thing to help for some common mistakes, but can never catch everything. In this case, the transformation is pretty tricky as it contains multiple steps.

You also did get what you want by running it multiple times, which seems acceptable.

So: Sorry, but I do not believe trying this particular whack-a-mole is a game worth playing.

**Comment by Xiretza** [comment]
One conceptually simple thing to do here would be to reapply the suggestion pass until we reach a fixed point and collect all the suggestions into one, but it would probably still require quite a bit of code reorganization.
