### ISSUE TITLE
`...` instead of `../..`, `....` instead of `../../../`, etc

### ISSUE THREAD

**Issue by ThatOneCalculator** [fish-shell/fish-shell#10613]
```
Shell: fish, version 3.7.1
OS: Arch Linux x86_64
Terminal emulator: kitty, foot
```

There's a zsh plugin (that I cannot find or remember the name of for the life of me) that turns commands like `cd ...` into `cd ../..`, `ls ....` into `ls ../../..`, so on and so forth. If there's any way that could be built into fish (or made as a plugin) that would be incredibly useful :)

**Comment by repsac-by** [comment]
```fish
abbr -a --position anywhere -- ... ../..
abbr -a --position anywhere -- .... ../../..
```

**Comment by repsac-by** [comment]
> That's perfect, thank you! Is there any way to make it programmatically (so I could hypothetically `cd ........`)?

```fish
for i in (seq 13)
    abbr -a --position anywhere ..(string repeat -n $i .) ..(string repeat -n $i /..)
end
```

**Comment by repsac-by** [comment]
```fish
function _ladder
    set i (math (string length $argv[1]) - 2)
    echo ..(string repeat -n $i /..)
end

abbr -a --regex '\.\.\.+' --position anywhere --function _ladder -- ...
```

**Comment by ThatOneCalculator** [comment]
Ah that's perfect!! Tysm again <3
