### ISSUE TITLE
`__fish_seen_argument` cannot handle long arguments like `--config=thisA`

### ISSUE THREAD

**Issue by SpiritInAShell** [fish-shell/fish-shell#10615]
```> fish --version 
fish, version 3.7.1
```
Also, following is true when running fish with `  sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'`

### What:

When using the helper function `__fish_seen_argument` in `complete -c myDummy --condition '__fish_seen_argument --long config'`, the helper function will not handle technically sane flags like `--config=someA` even as it handles the technically identical flag `--config someA`. I believe this to be a bug. Looking into other issues, I found #10212  which might have one **similarity** in origin.

### Example
I barely understand `complete`, `commandline` etc but when writing following completions...
```
# this is shortened dummy code to recreate issue,
# original is for `snapper --config=abc [list|create|...]`
>  begin
      function myDummy
          echo ay
      end
      set tCommand myDummy
      complete -c $tCommand --erase 
      complete -c $tCommand --no-files 
      complete -c $tCommand --no-files --short-option 'c' --long-option 'config' --require-parameter --arguments 'someA someB someC'
      complete -c $tCommand --no-files --condition '__fish_seen_argument --short c --long config' --arguments 'sub1 sub2 sub3'
  end
```

### expected:

... to get this style of syntax:

```
myDummy --config someA arg1
myDummy --config=someA <tab> # will not offer suggestion
```
... the second line will not offer any of the subcommands `sub1 sub2 sub3`. (*I stumbled upon this while doing first experiments!!! defining the flag `--config` as a first required argument like this is very questionable* but it reveals this might-be bug.)

I do not know if this is as intended!

### workaround
I looked into https://github.com/fish-shell/fish-shell/blob/936f7d9b8d3faeb49de4e617d76eaedabce09aaa/share/functions/__fish_seen_argument.fish#L21 and modified it like this:
```
    if string match --quiet -- "--$l" $t ; or string match --quiet -- "--$l=*" $t
```
Now, in my scenario, the intended completion with long arguments works even with `--config=someA`. (Don't know what it will break.)

### reasoning/cause
I guess this is because `commandline --tokenize` does not split `--config=someA` into `--config` and `someA` as it would with `--config someA`. This might reflect in many other situations where long flags with `=` will not be splitted. That is why I referenced #10212 as this might be the case. (But gladly I am not into this, yet.)

### history, why at all use that flag style
**A reason to prefer** `--config=someA` over `--config someA` is **auto completion from history**
```
# if I write 
snapper --config=s
# and now press `alt+cursor up` it will complete to all strings  like
snapper --config=someA
# especially when completing `--desc...`
snapper --config=someA create --description="template for new description"
```

**Comment by mqudsi** [comment]
Nice catch. The `__fish_seen_argument` function just needs to be updated to truncate tokenized arguments that begin with `--` to terminate at `=`, i.e. `string replace -r '^(--.*?)=.*' '$1'`
