### ISSUE TITLE
Make `__fish_print_help` formatting be more like man pages

### ISSUE THREAD

**Issue by injust** [fish-shell/fish-shell#10625]
Using fish 3.7.1

---

`__fish_print_help` outputs help messages in a man page-like format, but I've noticed a few differences:
1. The contents of each section (e.g. Synopsis, Description, Options) is not indented
2. The Synopsis header is missing entirely, even though it is present in the `.rst` files, e.g. https://github.com/fish-shell/fish-shell/blob/master/doc_src/cmds/type.rst

In itself, it'd probably be nice if the format was closer to normal man pages. But my motivation for this change is https://github.com/sharkdp/bat/issues/3025. I use https://github.com/sharkdp/bat as a colorizing pager for `man` (instructions [here](https://github.com/sharkdp/bat#man)). And I think the above differences are causing weird syntax highlighting.

<details>
<summary>Screenshots</summary>

![SCR-ls](https://github.com/user-attachments/assets/09707786-1f4a-4637-b84d-f14b3c327b7b)
![SCR-type](https://github.com/user-attachments/assets/68851a55-80c4-44fa-9dae-c014696d7a1a)
![SCR-fish_add_path](https://github.com/user-attachments/assets/f0af6370-347d-4b0a-847f-ae8775e477b4)

</details>

**Comment by zanchey** [comment]
At this point, we might as well just sub the whole thing out to `man`?
