### ISSUE TITLE
Autosuggestion casing behavior for mv command makes no sense

### ISSUE THREAD

**Issue by crazyminecuber** [fish-shell/fish-shell#10626]
### System info

fish, version 3.7.1
3.7.1
NixOS
Kitty

Behavior reproducible without third-party customizations

## Instructions to reproduce

* Create a file named Makefile
* type "mv Makefile ma"

Now fish will suggest "mv Makefile Makefile" which is not what is wanted in this situation, since the second argument should not be a file in the current directory.

Is there a way to disable this behavior currently, so that fish actually suggests, based upon the case that I have written?

But a proper fix would of course also be nice :)

**Comment by ridiculousfish** [comment]
We try hard not to special-case commands (with the notable exception of `cd`) for autosuggestions.

Note that the case that is displayed is not the true case - if you type `mv Makefile makefile` then it may display `mv Makefile Makefile` but when you hit enter the case will revert to what you typed. I freely acknowledge this is confusing.

Let's track in #7944. Thank you for filing.
