### ISSUE TITLE
Feature request: Include SHA256 for tar ball release on the website

### ISSUE THREAD

**Issue by hholst80** [fish-shell/fish-shell#10642]
Please include the SHA256 on the release package on the website so CI/CD users can use that to validate securely that the source package in a Docker container environment.  The only checksum supported is SHA256.  I will work with the buildkit/Docker team to add also SHA512 but for now SHA256 is what we have.

![image](https://github.com/user-attachments/assets/01583803-1be2-494c-81f0-d3bab8c5cc13)

The NIST recommends using SHA256 or SHA512 over the "deprecated" sha1:

https://en.wikipedia.org/wiki/SHA-1
https://en.wikipedia.org/wiki/SHA-2

**Comment by zanchey** [comment]
Sounds good, they are published on the GitHub releases page https://github.com/fish-shell/fish-shell/releases

The template and https://github.com/fish-shell/fish-site/blob/master/tools/update_release_metadata.py will need updating.
