### ISSUE TITLE
OSC52 Copying doesn't work

### ISSUE THREAD

**Issue by TheBicPen** [fish-shell/fish-shell#10656]
fish version 3.3.1
xterm-256color (Windows Terminal 1.20)
WSL2

Same result without customizations.

Not sure if this is a duplicate of https://github.com/fish-shell/fish-shell/issues/10296, but copying to the system clipboard with OSC52 doesn't seem to work.

I would expect this fish script to put "hello" into the clipboard: `printf "\033]52;c;(printf "%s" "hello" | base64)\a"`, but it doesn't.
The equivalent bash script,  `printf "\033]52;c;$(printf "%s" "hello" | base64)\a"`, works in bash.

**Comment by faho** [comment]
`()` command substitutions are not expanded in quotes.

Either use `$()`, just like in bash, or use printf with an actual format string:

```fish
printf "\033]52;c;%s\a" (printf "%s" "hello" | base64)"
```

To use `$()` you'll have to upgrade fish to at least 3.4.0 - 3.3.1 is 16% of all released commits ever made to fish behind. See https://fishshell.com/ for how to get updated packages.
