### ISSUE TITLE
`alt+left` and `alt+right` keybinds no longer work

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#10653]
Using https://github.com/fish-shell/fish-shell/commit/8d8a036e205d25c2a239b651ec9e2ac0afe6cb66 and iTerm 2 (v3.5.3)

I think it bisects to https://github.com/fish-shell/fish-shell/commit/c3c832761038788813b0d13f992bfc866b8f0a1d (@krobelus)

---

My `alt+left` and `alt+right` keybindings stopped working recently.

`fish_key_reader` also doesn't acknowledge the `alt` modifier:

```
$ fish_key_reader --continuous
Press a key:
bind left 'do something'
bind right 'do something'
```

**Comment by krobelus** [comment]
huh so iTerm supports pushing and popping progressive enhancement flags (using `CSI > flags u`) but not setting them directly (`CSI = flags ; mode u`)? @gnachman

**Comment by krobelus** [comment]
added a workaround in 7cfc6297bcc3c13511b6b54d7416f09cb89f7e3e.
This is bad, we should get to the bottom of what iterm does here.

**Comment by gnachman** [comment]
I have added proper CSI u support in https://github.com/gnachman/iTerm2/commit/9cd0241afd0655024153c8730d5b3ed1fe41faf7. Please test the nightly build (https://iterm2.com/downloads/nightly/iTerm2-3_5_20240809-nightly.zip) and let me know if it's working better.

**Comment by krobelus** [comment]
Great, I've limited the workaround to iTerm versions < 3.5.4 in 4664a0b52f6ea92c8d19b935b52aafcdd3798905

**Comment by gnachman** [comment]
3.5.5 is just a minor bugfix release over 3.5.4, so you should bump the workaround up.

**Comment by krobelus** [comment]
to 3.6?

**Comment by gnachman** [comment]
3.5.6 will have the fix. 3.5.5 continues to have the bug.
