### ISSUE TITLE
Error no such file file:///use/share/doc/fish/index.html when run "help"

### ISSUE THREAD

**Issue by W1BTR** [fish-shell/fish-shell#10668]
fish 3.7.1 on Ubuntu server 24.04. Fresh install of fish using the instructions on the Ubuntu package page.

Maybe related to #6338 ?
```
➜  root ~ fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
root@docker-server ~> help
Error: no such file "file:///usr/share/doc/fish/index.html"
docker@docker-minimal ~ [2]> 

```

Yet, the file does exist:

```
 ls /usr/share/doc/fish
changelog.Debian.gz  design.html               language.html  search.html
CHANGELOG.rst.gz     faq.html                  license.html   searchindex.js
cmds/                fish_for_bash_users.html  objects.inv    _static/
commands.html        genindex.html             prompt.html    tutorial.html
completions.html     index.html                README.rst.gz
copyright            interactive.html          relnotes.html
root@docker-server ~> 
```

**Comment by W1BTR** [comment]
Also tried running fish_config, which also errors out:

```
root@docker-server ~ [127]> fish_config
Web config started at file:///tmp/web_configivtz83x9.html
If that doesn't work, try opening http://localhost:8000/e5a36a7799be486f9be1c49c87eb521c/
Hit ENTER to stop.
Exception in thread Thread-1 (runThing):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/share/fish/tools/web_config/webconfig.py", line 1700, in runThing
    elif is_chromeos_garcon():
         ^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/fish/tools/web_config/webconfig.py", line 110, in is_chromeos_garcon
    return "garcon-url-handler" in webbrowser.get().name
                                   ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/webbrowser.py", line 66, in get
    raise Error("could not locate runnable browser")
webbrowser.Error: could not locate runnable browser

```

**Comment by zanchey** [comment]
My guess is that you have an empty or incorrect BROWSER variable. Which browser are you trying to use, and what does `set --show BROWSER` show?

You could try `fish_trace=1 help` too.

**Comment by W1BTR** [comment]
> My guess is that you have an empty or incorrect BROWSER variable. Which browser are you trying to use, and what does `set --show BROWSER` show?
> 
> You could try `fish_trace=1 help` too.

I have no browser, this is a headless server with no desktop environment.

**Comment by faho** [comment]
Without a browser, neither help nor fish_config can do anything. Both open html files.

I suppose we can improve the fish_config error (it's using webbrowser for a chromeos workaround and should just fail then), but the help error comes from whatever tool that *has* found that could open an html file, likely xdg-open.

**Comment by W1BTR** [comment]
Okay gotchya. I figured this tool was more or less designed for heavy terminal use. Maybe a flag to host a local webserver instead of pushing it to a browser would be easier. Obviously adding a webserver would be complicated lol.

Would hosting the folder it's pointing to with caddy or appache work?

**Comment by faho** [comment]
I've now made it so the fish_config error doesn't mention chromeos, and `help` will now show the URL for the online version.

We do not want to expose fish_config to outside of localhost, so I believe that is all there is to be done.

You can also read the documentation in man-pages, see `man fish-<TAB>` and pick themes/prompts in the terminal with `fish_config theme` and `fish_config prompt`.

**Comment by W1BTR** [comment]
Great, thank you!

**Comment by zanchey** [comment]
You can also install a terminal-based browser. I use links but elinks or lynx are also popular on our systems.
