### ISSUE TITLE
default flatpak autocompletions load up incorrect completions for package names

### ISSUE THREAD

**Issue by fluoriteByte** [fish-shell/fish-shell#10661]
fish version: 3.7.1
OS: Vanilla-OS, based on debian sid

Behavior observed also on debian 12 system, can be reproduced in any terminal emulator or tty

asciinema recording:
https://asciinema.org/a/sEBlKEDzmatp5DFJtjrv2Q2H6

**Comment by faho** [comment]
Duplicate of #10514
