### ISSUE TITLE
No easy way to install fish on Amazon Linux 2023

### ISSUE THREAD

**Issue by mm2175** [fish-shell/fish-shell#10666]
```
dnf install fish
Last metadata expiration check: 0:03:53 ago on Mon Aug 12 21:20:05 2024.
No match for argument: fish
Error: Unable to find a match: fish
```

**Comment by zanchey** [comment]
https://unix.stackexchange.com/questions/778636/cant-install-fish-on-amazon-linux-2023 has an approach you can use.

Unfortunately there is no way for the fish-shell project to provide packages that you can install on Amazon Linux; the Open Build Service does not support Amazon Linux and we can't influence the choices that Amazon make over their distribution. You might consider opening a request with them.

**Comment by mm2175** [comment]
I was wondering if it might be possible to consider providing an installable RPM package on the GitHub release page, similar to many other projects? I've attempted to compile the project myself, but found it challenging due to the numerous dependencies required. This addition could potentially make it easier for users to get started with Fish. Thank you for considering this suggestion.

**Comment by zanchey** [comment]
Our current approach is to provide RPM repositories for the major distributions that use them through the Open Build Service. Adding further packages through a different build and publishing approach, and without a repository to support upgrades and signing, is not something I am eager to implement.

**Comment by mm2175** [comment]
I discovered that using the installation package for CentOS 9 Stream can be successfully installed. You can directly download the RPM package for CentOS 9 Stream from the Fish website, and then install it using DNF. This can serve as a reference for those encountering the same issue.
