### ISSUE TITLE
Question: How to bind a key that set the vi mode from visual to normal? 

### ISSUE THREAD

**Issue by CWEzio** [fish-shell/fish-shell#10671]
Fish version: 3.7.1
System: Ubuntu 20.04
Terminal: Gnome terminal

I want to bind the key `"+y` to copy to clipboard, in the visual mode. Currently, `"*y` does the work. (The reason is that in vim, `"+y` copy to clipboard while `"*y` copys to the middlekey selection.)

In order to do this, I define the following:
```
 bind --mode visual \"+y fish_clipboard_copy --sets-mode default repaint-mode
```
However, with this setting, after I visual select and type `"+y`, the vi-mode does not enter the command mode normally. Instead, it would still keep the visual selection weirdly.  How to define a key that would do what `"*y` does in visual mode correctly? Thank you for your help!

**Comment by faho** [comment]
You will also need `end-selection`.

Additionally in the current release you will have to use all bind functions via `commandline -f`, so this should work:

```fish
bind --mode visual \"+y --sets-mode default 'fish_clipboard_copy; commandline -f end-selection; commandline -f repaint-mode'
```
