### ISSUE TITLE
Is it possible to switch the behavior of Right Arrow and CTRL - Right Arrow for accepting one word of autosuggestion versus the whole suggestion?

### ISSUE THREAD

**Issue by mlncn** [fish-shell/fish-shell#10677]
fish, version 3.7.1
3.7.1

Debian testing, Linux d64 6.10.3-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.10.3-1 (2024-08-04) x86_64 GNU/Linux

xterm-256color

I much more often want to advance through a suggestion word by word rather than accept the entire thing.

Is it possible to make Arrow advance word by word, and CTRL Arrow accept it all at once?  (Switching the current behavior.)

A related annoyance is that once any part of an autosuggestion is "accepted" it does not get unsuggested by going backwards; if i type `ex` and then accept `example-command one two three` i would expect to have an easy way to get back to `ex` and start the suggestion and tab completion options fresh from there, or at the very least to easily "un-accept" sp

**Comment by mlncn** [comment]
Somewhat related to #3940 but i don't see how to break up the `forward-char` or `forward-word` capabilities to stay the same except when suggestions are at play.

**Comment by krobelus** [comment]
I'd simply use `alt-f` and `ctrl-f` and overloading movement keys like that seems weird but sure you can do this in master / an upcoming version:

```fish
bind right '
    if commandline --showing-suggestion &&
        [ "$(commandline)" = "$(commandline -c)" ]
        commandline -f forward-word
    else
        commandline -f forward-char
    end
```

> A related annoyance is that once any part of an autosuggestion is "accepted" it does not get unsuggested by going backwards; if i type ex and then accept example-command one two three i would expect to have an easy way to get back to ex and start the suggestion and tab completion options fresh from there, or at the very least to easily "un-accept" sp

You can use `ctrl-z` to undo. Making left-arrow un-accept chars is also scriptable but I don't think that's what we want as default?
