### ISSUE TITLE
Fish shell path globbing should work in command line options

### ISSUE THREAD

**Issue by mlindner** [fish-shell/fish-shell#10672]
For example when I run some command that takes a --option:

```mpv long_movie_name_5.mkv --sub-file=long_movie_with_5*```

I get the following error:

```fish: No Matches for wildcard '--sub-file=long_movie_with_5*'. See `help wildcards-globbing`.```

This should be a successful glob, but it does not work.

**Comment by faho** [comment]
It should not be a successful glob.

Globbing is quite simple: Take the entire token, try to expand any `*` so it yields an existing filename.

This would require that `--foo=` options are syntactically special and removed from globs, which would both complicate globbing and make globbing for some filenames impossible - `--foo=bar` is a valid filename on unix.

Instead, here's what you do:

```fish
mpv long_movie_name_5.mkv --sub-file=$(path filter long_movie_with_5*)
```

This will expand the glob and pass the `--sub-file` option multiple times if there are multiple files, like `--sub-file=long-1 --sub-file=long-2 --sub-file=long-3`.
