### ISSUE TITLE
fish cannot be crosscompiled

### ISSUE THREAD

**Issue by xfix** [fish-shell/fish-shell#1067]
While compiling fish for Windows (32-bit version on 64-bit OS), I had a problem that fish refused to be compiled. This is caused by following code in `configure`.

``` sh
#
# If we are compiling against glibc, set some flags to work around
# some rather stupid attempts to hide prototypes for *wprintf
# functions, as well as prototypes of various gnu extensions.
#

{ $as_echo "$as_me:${as_lineno-$LINENO}: checking if we are compiling against glibc" >&5
$as_echo_n "checking if we are compiling against glibc... " >&6; }

if test "$cross_compiling" = yes; then :
  { { $as_echo "$as_me:${as_lineno-$LINENO}: error: in \`$ac_pwd':" >&5
$as_echo "$as_me: error: in \`$ac_pwd':" >&2;}
as_fn_error $? "cannot run test program while cross compiling
See \`config.log' for more details" "$LINENO" 5; }
else
  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
/* end confdefs.h.  */


        #include <stdlib.h>
        #ifdef __GLIBC__
        #define STATUS 0
        #else
        #define STATUS 1
        #endif

int
main ()
{

        return STATUS;


  ;
  return 0;
}

_ACEOF
if ac_fn_cxx_try_run "$LINENO"; then :
  glibc=yes
else
  glibc=no

fi
rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext \
  conftest.$ac_objext conftest.beam conftest.$ac_ext
fi
```

**Comment by brandon099** [comment]
Trying to CC for an embedded linux project and would love to have fish available. +1

**Comment by krader1961** [comment]
@brandon099, Given this issue has been open nearly three years it's going to take someone like yourself who is motivated to make this work for it to be implemented. Pull-requests gladly accepted :smile:

**Comment by zanchey** [comment]
I had a bit of a look, and there's a simple change and a complex one.

The simple change is to provide a crosscompilation default for the configure check for `have_realpath_null`.

The more complex change is to turn the configure-time check for `/proc/self/stat` into a runtime check.

I managed to successfully crosscompile by just forcing the `/proc/self/stat` check to always fail, but that's obviously not an appropriate solution.

**Comment by zanchey** [comment]
`have_realpath_null` got dropped in 7fd3079bb63, so I think it's just the `/proc/self/stat` that needs to be turned into a runtime check. I'll make a PR.

**Comment by floam** [comment]
There are a few platforms where we should nonetheless be able to skip `stat`ing that path.

**Comment by zanchey** [comment]
I think this should be possible now, but I'll wait to hear in #5848 before closing.
