### ISSUE TITLE
Cursor won't change shape depending on vi mode when running inside the integrated terminal of VSCode

### ISSUE THREAD

**Issue by CWEzio** [fish-shell/fish-shell#10673]
fish version: 3.7.1
VSCode version: 1.91.1
OS: Ubuntu 20.04

I have set the fish vi mode cursor shape in the `config.fish` file as:
```fish
    # Emulate vim's cursor shape behavior
    # Set the normal and visual mode cursors to a block
    set fish_cursor_default block
    # Set the insert mode cursor to a line
    set fish_cursor_insert line
```
It works fine in both the Gnome terminal and inside tmux. However, in the integrated terminal of VSCode, the cursor shape does not change.

Thank you for your help!

**Comment by CWEzio** [comment]
Moreover, there is a setting `terminal.integrated.cursorStyle` that can control the cursor style. Currently, my setting is `block`. However, previously I am using `zsh-vi-mode`, for which the cursor does change in different modes in the integrated terminal of VSCode.

**Comment by faho** [comment]
Unfortunately the vs code terminal just claims to be "xterm-256color" with no way to detect it specifically. So we refuse to change the cursor because many poor terminals also do the same and then mishandle the cursor change sequences.

```fish
set -g fish_vi_force_cursor 1
```

to override it.
