### ISSUE TITLE
autocomplete returns files

### ISSUE THREAD

**Issue by benkeil** [fish-shell/fish-shell#10699]
Please tell us which fish version you are using by executing the following:

`fish, version 3.7.1`

Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

`Darwin MacBook-Pro-von-Ben 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:30 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6000 arm64`
`xterm-256color`
  
Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:

`yes`

Tell us how to reproduce the problem. Including an asciinema.org recording is useful for problems that involve the visual display of fish output such as its prompt.

I want to add autocompletion for awsume but I can't get it to run without returning also files

```
$ awsume-autocomplete | xargs
default sandbox dev live dr-live
```

```
complete -c awsume -x -a (awsume-autocomplete | xargs)
```

I also trieb different variants

```
complete --command awsume -x --arguments '(awsume-autocomplete)'
complete -c awsume -f -ra (awsume-autocomplete | xargs)
complete -c awsume -f -a (awsume-autocomplete | xargs)
```

but with no success. Auto complete returns:

```
$ awsume <TAB>
dev      live      sandbox
default  dr-live   test.secret.yaml
```

```
$ ll
-rw-r--r--@ 1 ben  wheel   122B  4 Sep 07:07 .sops.yaml
-rw-r--r--@ 1 ben  wheel   1,3K  4 Sep 07:14 test.yaml

$ ls
test.secret.yaml
```

Is this a problem of fish or awsume, or what is going on?

**Comment by benkeil** [comment]
I tried also with a different command:

```
complete -c sops -x -a 'exec-env'    -d 'execute a command with decrypted values inserted into the environment'
complete -c sops -x -a 'exec-file'   -d 'execute a command with the decrypted contents as a temporary file'
complete -c sops -x -a 'publish'     -d 'Publish sops file or directory to a configured destination'
complete -c sops -x -a 'keyservice'  -d 'start a SOPS key service server'
complete -c sops -x -a 'filestatus'  -d 'check the status of the file, returning encryption status'
complete -c sops -x -a 'groups'      -d 'modify the groups on a SOPS file'
complete -c sops -x -a 'updatekeys'  -d 'update the keys of SOPS files using the config file'
complete -c sops -x -a 'decrypt'     -d 'decrypt a file, and output the results to stdout'
complete -c sops -x -a 'encrypt'     -d 'encrypt a file, and output the results to stdout'
complete -c sops -x -a 'rotate'      -d 'generate a new data encryption key and reencrypt all values with the new key'
complete -c sops -x -a 'edit'        -d 'edit an encrypted file'
complete -c sops -x -a 'set'         -d 'set a specific key or branch in the input document. value must be a json encoded string. eg. \'/path/to/file ["somekey"][0] {"somevalue":true}\''
complete -c sops -x -a 'unset'       -d 'unset a specific key or branch in the input document.'
complete -c sops -x -a 'help'        -d 'Shows a list of commands or help for one command'
complete -c sops -x -a 'h'           -d 'Shows a list of commands or help for one command'
```

and there is also `test.secret.yaml` returned.

**Comment by faho** [comment]
This is the correct version, assuming you want `awsume-autocomplete` to be run to give you the completion candidates:

```fish
complete --command awsume -f --arguments '(awsume-autocomplete)'
```

`-x` is a combination of `-r` (`--require-parameter`) and `-f` (`--no-files`). Unfortunately the `-r` part of that does not make sense unless you're adding an option with `-s`/`-o` or `-l`. Make it `-f`.


----

This is wrong because it runs `awsume-autocomplete` at the time the completions are defined:

```fish
complete -c awsume -x -a (awsume-autocomplete)
```

This is wrong because the xargs is, at best, useless, and at worst will break tokens that include spaces:

```fish
complete -c awsume -f -a '(awsume-autocomplete | xargs)'
```

(without the quotes it's *worse*, because it could be double-evaluated)

**Comment by benkeil** [comment]
your version also does not work, it still showing files
