### ISSUE TITLE
broken formatting in documentation of `set` command

### ISSUE THREAD

**Issue by randomdude999** [fish-shell/fish-shell#10697]
https://github.com/fish-shell/fish-shell/blob/77b2dcb4627ed288d481d60501134795c779e44e/doc_src/cmds/set.rst?plain=1#L84

This shows up as:
![image](https://github.com/user-attachments/assets/ecda8234-140f-4aba-8efc-ac378075e70e)

it's probably not supposed to have the *s visible there.

**Comment by faho** [comment]
Thanks, that's a good catch!
