### ISSUE TITLE
git add command very slow when repository has many files

### ISSUE THREAD

**Issue by lod** [fish-shell/fish-shell#10706]
`git add` command completion is stupid slow if there are many files in the directory.  For my project it takes 52 seconds.

This was also reported in #4117 and #4762, possibly for different base causes.

My particular problem was revealed in an ansible project directory.  Ansible is python based, so the project uses a python virtual environment, as is common for python projects.  The virtual environment contains 79,792 files.

I believe git add completion command runs `git status` against every file individually. While each call takes milliseconds when you scale that up by 80,000 and you are talking serious time.  

This was revealed by running a profile (as suggested in #4117)
```
time fish --profile /tmp/some_file -c 'complete -C"git add "'
cat /tmp/some_file | sort -nk 2 | tail -n 10

18	7230	----> if set -q file[1]...
23	10165	-----> for d in $desc...
18	10188	----> if set -q file[1]...
14084	45317	-> source /home/lod/.config/fish/completions/git.fish
297540	297540	-----> command git $saved_args
48	297588	----> eval command git $global_args \$saved_args 2>/dev/null
1186606	48860253	---> __fish_git $git_opt status --porcelain=2 $status_opt \
79	48860389	--> if test "$ver[1]" -gt 2 2>/dev/null...
98	48864790	-> __fish_git_files modified untracked deleted unmerged modified-staged-deleted
1925340	50865421	> complete -C"git add "
```

I believe the issue is in function __fish_git_files, line 190 of /usr/share/fish/completions/git.fish

```
    if test "$ver[1]" -gt 2 2>/dev/null; or test "$ver[1]" -eq 2 -a "$ver[2]" -ge 11 2>/dev/null
        __fish_git $git_opt status --porcelain=2 $status_opt \
            | while read -la -d ' ' line
```

There is also similar code on line 368, used for older git versions, this likely has the same issue.

```
        __fish_git $git_opt status --porcelain -z $status_opt \
            | while read -lz -d' ' line
```

I believe this is a common use case and should be handled, python and javascript based projects frequently include virtual environments which bring in huge numbers of files.

fish, version 3.7.1

Linux 6.10.6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.10.6-1 (2024-08-19) x86_64 GNU/Linux

My workaround was to `cp /usr/share/fish/completions/git.fish ~/.config/fish/completions/` and edit `~/.config/fish/completions/git.fish`

I added an immediate return to __fish_git_files so that it wouldn't execute, modifying here because it's called in a bunch of places and all of them will cause issues. After modification the add command just gives standard file paths and takes about 173 milliseconds (feels instant).

```
function __fish_git_files
    __fish_complete_path
    return

   .... original function code continues, but will never be executed

```

**Comment by krobelus** [comment]
shouldn't `git status --porcelain=2` ignore gitignore'd files? Presumably your virtualenv is gitignored right?
I wonder where we would descend into gitignored directories here.

**Comment by krobelus** [comment]
can you try running the `git status` command with different options to see what's taking 45 seconds.
The slow one should be

```
$ fish -c 'fish_trace=1 complete -C"git add "' &| grep '^-*> __fish_git.*status '
------> __fish_git -c status.relativePaths -c core.quotePath= status --porcelain=2 --ignore-submodules=all -ual
```

`__fish_git` is just an irrelevant wrapper here so start with `git -c status.relativePaths -c core.quotePath= status --porcelain=2 --ignore-submodules=all -ual` etc.

**Comment by faho** [comment]
Alright, no answer for a while, closing.

If you get back to us we can reopen. But note that using `git` here to figure out the state of files is extremely useful and sometimes git is unfortunately slow, so it's likely we can't do anything.

**Comment by lod** [comment]
Thanks for looking at this, sorry I've been absent.

I had not placed the environment directory in a git ignore file, I just hadn't bothered.  Doing that does significantly improve performance. Investigating suggests that the wildcard string comparisons are reasonably slow, multiplied by the number of lines makes it very slow.

| time | gitignored | command
| --- | --- | --- |
| 7.28 millis | Yes | time git -c status.relativePaths -c core.quotePath= status --porcelain=2 --ignore-submodules=all -uall |
| 850.03 millis | No | time git -c status.relativePaths -c core.quotePath= status --porcelain=2 --ignore-submodules=all -uall |
| 404.85 millis | No | time git -c status.relativePaths -c core.quotePath= status --porcelain=2 --ignore-submodules=all -uall > /dev/null | 
| 578.58 millis | Yes | time fish -c 'fish_trace=1 complete -C"git add "' &| grep '^-*>
__fish_git.*status ' |
| 191.86 secs | No | time fish -c 'fish_trace=1 complete -C"git add "' &| grep '^-*> __fish_git.*status ' |
| 16.69 secs | No | time git -c status.relativePaths -c core.quotePath= status --porcelain=2 --ignore-submodules=all -uall | while read -la -d ' ' line; echo $line ; end |
| 21.06 secs | No | time git -c status.relativePaths -c core.quotePath= status --porcelain=2 --ignore-submodules=all -uall | while read -la -d ' ' line; set -l untracked; switch "$line[1..2]"; case "*"; set -ql untracked; and set file "$line[9..-1]"; and set desc "Untracked file"; echo $line; end; end |
| 23.72 secs | No | time git -c status.relativePaths -c core.quotePath= status --porcelain=2 --ignore-submodules=all -uall | while read -la -d ' ' line; set -l untracked; switch "$line[1..2]"; case "*"; set -ql untracked; and set file "$line[9..-1]"; and set desc "Untracked file"; end; if set -q
 file[1]; echo $line; end; end |

It seems like the time usage is
| command | additional time | per line (70,303 lines) |
| --- | --- | --- |
| while read | 15.84s | 225us |
| switch case | 4.37s | 62us |
| if block | 2.66s | 38us |

The 18 case statements extrapolates out to 78.66 seconds. Though some have multiple options, so 27 tests extrapolated to 117.99 seconds may be more accurate. Including the other tests 117.99 + 15.84 + 2.66 = 196.49, very close to the measured 191.86 secs.

Forcing the second (older) path was slightly faster at 170.51 secs, probably due to the simpler case tests and their reduced number (22 test options).

I expected to see significant performance improvements by moving the untracked case "$q"' *' test to the top of the switch case list, I expected that making it the first match would avoid testing all of the other strings. However the change was minor, 174.43 seconds, a 9% improvement.
