### ISSUE TITLE
Unable to build under OSX Mavericks

### ISSUE THREAD

**Issue by talios** [fish-shell/fish-shell#1070]
Using `./configure ; make ; make install` fish HEAD no longer compiles under the new OSX Mavericks with:

    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    make: *** [fish] Error 1

whilst using `xcodebuild install` yields the following compilation errors:

    /Users/amrk/Dropbox/fish-shell/fish.cpp:206:24: error: expected ';' after expression
            paths.doc = L"" DOCDIR;
                           ^
                           ;
    /Users/amrk/Dropbox/fish-shell/fish.cpp:206:25: error: use of undeclared identifier 'DOCDIR'
            paths.doc = L"" DOCDIR;
                            ^
    2 errors generated.

**Comment by justinmayer** [comment]
I just built Fish successfully with both autotools and Xcode on Mac OS X 10.10 Yosemite. I believe this issue can be closed.

**Comment by zanchey** [comment]
Yep, no response in a long time and clearly it is working for others.
