### ISSUE TITLE
Directory/glob tab expansion bug in prerelease (HEAD)

### ISSUE THREAD

**Issue by ilyagr** [fish-shell/fish-shell#10703]
I just updated to today's HEAD, `fish, version 3.7.1-2289-g325b51aca` on ARM Mac OS. It was installed with ` brew install --HEAD --fetch-HEAD fish`.

I can reproduce this bug with `sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'`. 

The bug seems to have already been present in a few months old `3.7.1-2191-g1c38677db`. In released 3.7.1, the expansion seems to not work at all (so, no bug).

------------

I'm in the root of [this repo](https://github.com/martinvonz/jj). I enter:

     ls cli/*/conf/tem<TAB>

This expands, wrongly, to

     ls cli/*/*/config/templates.toml

The correct expansions would be

     ls cli/*/config/templates.toml

or

     ls cli/src/config/templates.toml

**Comment by krobelus** [comment]
bisection fails with

```
CMake Error at build/_deps/corrosion-src/cmake/Corrosion.cmake:1305 (set_property):
  set_property could not find TARGET fish-rust.  Perhaps it has not yet been
  created.
```
