### ISSUE TITLE
kmod upstream integration

### ISSUE THREAD

**Issue by evelikov** [fish-shell/fish-shell#10710]
Hello team, I'm considering pulling the fish completion files (as do zsh and bash fwiw) in the upstream kmod project. At a glance, a few questions come up:

 - what is the license of the completion files?
 - would the team be comfortable with relicensing under LGPL-2.1-or-later - like license we use, for the existing bash/kmod and library
 - are there any copyright holders which I could/should add in the files themselves?
 - how do we handle the conflicting filenames, if distros ship the same file(s) from both projects?
 - can I still use the various helpers (__fish_print_modules, __fish_contains_opt etc) and if so, for how long?

Thanks o/

**Comment by faho** [comment]
> what is the license of the completion files?

The fish project is GPLv2. We never requested any other license on the completions, so they are also GPLv2.

> would the team be comfortable with relicensing under LGPL-2.1-or-later

*I* would have no problem relinquishing my contributions to these files, but I believe I did not author the majority of that code.

I'M assuming we're talking about https://github.com/fish-shell/fish-shell/blob/master/share/completions/modprobe.fish and https://github.com/fish-shell/fish-shell/blob/master/share/completions/modinfo.fish?

> are there any copyright holders which I could/should add in the files themselves?

Check the git logs. We don't keep per-file copyright comments.

Those are also the people you'd have to contact about relicensing.

> how do we handle the conflicting filenames, if distros ship the same file(s) from both projects?

Distros would install them into the vendor completions directory, which takes precedence over completions shipped by fish.

E.g. they would end up in /usr/share/fish/vendor_completions.d/, while fish's would be in /usr/share/fish/completions/.

> can I still use the various helpers (__fish_print_modules, __fish_contains_opt etc) and if so, for how long?

Formally, we've called these internal interfaces. Informally, they've been stable for years so I would be comfortable keeping them like that.

**Comment by faho** [comment]
> Wrt copyright, would it suffice to add header like below in the files?

It would be fine for *me*, but unfortunately I am not a copyright lawyer. You will have to decide if that's okay for your project. Keeping in mind of course that it's in everyone's interest to keep these in kmod, I don't think there's an issue.

If you want to be 100% safe:

The modinfo completions are exclusively @moverest. I believe it's fine to discount mechanical translations ("replace --description with -d across the tree") and very minor contributions like fixing a single typo as uncopyrightable.

The modprobe completions are a lot older, I think there are about three or four people you would have to contact. These are very simple completions, there isn't a ton of churn there.

**Comment by moverest** [comment]
I am fine with re-licensing my work here under LGPL-2.1-or-later if you want to do that.
