### ISSUE TITLE
Stopping fish from special casing `cd` auto-suggestions from history

### ISSUE THREAD

**Issue by algernon** [fish-shell/fish-shell#10719]
I am using fish 3.7.1 on NixOS, with zoxide set up to act as `cd` (via `zoxide init --cmd=cd fish | source`), and it works wonderfully well, except for one thing: fish does not provide auto-suggestions from history for directories I entered via `zoxide`.

The reason for this is [here](https://github.com/fish-shell/fish-shell/blob/fc4dd8f4de338bbf385cddfa3f95c49adfc51124/src/highlight.rs#L335-L352) (similar code exists in 3.7.1 too): `cd` is special cased when validating auto-suggestions from history. With zoxide, most directories I enter into will come from its database, and they will not exist in a way that fish can check.

Yet, I very much would like these auto-suggestions. I can make auto-complete work, but... I like auto-suggest a whole lot more. I got used to it in zsh.

So I was wondering, if I made a patch that made it possible to `set -U cd_autosuggest_verify false` (and it would default to `true`, of course), would that be interesting to have in fish proper?

For context, I have fixed my immediate need by patching out the special case, but figured if this is something others might be interested in, I'd propose a patch. But since it isn't something *I* need, I'd only work on it if it makes sense, if it would be useful for others, and if it'd have a chance of landing upstream.

To demonstrate a difference, I recorded an [asciicast](https://asciinema.org/a/XWJRrIMwFCDVUqzwo5wYGthHm) comparing fish 3.7.1 and my patched version of it. Judging by the sources, the current git head would behave the same as 3.7.1 - but I have not tried.

**Comment by faho** [comment]
> So I was wondering, if I made a patch that made it possible to set -U cd_autosuggest_verify false (and it would default to true, of course), would that be interesting to have in fish proper?

This isn't really the sort of option we tend to add.

Tbh I'm not really opposed to see if this validation is carrying its weight - especially when we can't give you a suggestion at all right now it seems like allowing other ways would be okay. So basically try descending a directory tree *first* and just regularly go from history otherwise.

It's not like we validate suggestions for e.g. `string` subcommands or `set_color`, and that hasn't really come up as a problem.

Or remove our `cd` function and stop validating when `cd` isn't the builtin.

**Comment by krobelus** [comment]
Instead of using zoxide you could add some directories to your CDPATH.

For users who want to use zoxide in the guise of `cd`, I think what we could do here is resolve "cd" to the wrapped command, and only special-case if that's `cd`. Then if you define `function cd --wraps zoxide; ...; end` that would work

**Comment by krobelus** [comment]
Would be nice if we could move the special handling into `share/completions/cd.fish`, then it would fall into place naturally.
However there are some things that scripted completions cannot do (something to do with unexpanding tokens) so I'd not do that at this point.

**Comment by algernon** [comment]
> > So I was wondering, if I made a patch that made it possible to set -U cd_autosuggest_verify false (and it would default to true, of course), would that be interesting to have in fish proper?
> 
> This isn't really the sort of option we tend to add.

ACK, I will not bother then.

> Tbh I'm not really opposed to see if this validation is carrying its weight - especially when we can't give you a suggestion at all right now it seems like allowing other ways would be okay. So basically try descending a directory tree _first_ and just regularly go from history otherwise.

I don't mind the verification, I can imagine it being useful. I just wish it wasn't there when `cd` is not the builtin. If there was a way to check if it is the builtin at verification time, and not verifying if it isn't - that would be a *much* better solution than my proposed variable-based hack.

By the way, I am not talking about auto-complete! Auto-complete is no problem, I can make that work with zoxide-as-cd. It's *specifially* history-based auto-*suggest* that I'm looking at.

> Instead of using zoxide you could add some directories to your CDPATH.

Not an option. The entire point of me using zoxide is that it learns automatically, and sorts by frequency. I have over 400 entries in my zoxide database, and have no desire to add any of them to CDPATH. :)

> For users who want to use zoxide in the guise of `cd`, I think what we could do here is resolve "cd" to the wrapped command, and only special-case if that's `cd`. Then if you define `function cd --wraps zoxide; ...; end` that would work

I *can* use zoxide as cd. That's not what this issue is about. This issue is very specifically about cd auto-suggestions, and those alone. zoxide-as-cd and zoxide tab completion are solved problems.

**Comment by faho** [comment]
> I can use zoxide as cd. That's not what this issue is about. This issue is very specifically about cd auto-suggestions

That is also what the --wraps idea is about. Completion logic feeds into suggestions.

We're saying if cd doesn't complete like cd disable the special cd suggestion logic.

**Comment by algernon** [comment]
> > I can use zoxide as cd. That's not what this issue is about. This issue is very specifically about cd auto-suggestions
> 
> That is also what the --wraps idea is about. Completion logic feeds into suggestions.
> 
> We're saying if cd doesn't complete like cd disable the special cd suggestion logic.

Oh, I see. Yeah, that'd work too. That's not something I can hack together, I think, so I'll just leave this issue open in case someone else wants to tackle it. :)

**Comment by krobelus** [comment]
This should be fixed now for OOTB zoxide.
In general though I'd recommend picking a different name for a tool with different behavior.

> I have over 400 entries in my zoxide database, and have no desire to add any of them to CDPATH. :)

you don't need to add all of them, only their parents. Of course it becomes a problem if you have lots of nested ones.

**Comment by algernon** [comment]
Just tested it, and now my zoxide and fish play well together in all scenarios I care about (and probably in scenarios I don't care about too - I just didn't test those). Thank you!
