### ISSUE TITLE
problem with activating Python virtualenv

### ISSUE THREAD

**Issue by DataEnggNerd** [fish-shell/fish-shell#10715]
I have recently came across fish shell and liked the autocompletion part very much. 
Being Python developer, who creates multiple virtualenv(via [virtualenv](https://virtualenv.pypa.io/en/latest/)) to local environments per project. Issues start when I am attempting to "activate" my virtual environment with `source venv/bin/activate`. 

### Issue 

```shell
> source .venv/bin/activate
.venv/bin/activate (line 27): Unsupported use of '='. In fish, please use 'set SCRIPT_PATH "${BASH_SOURCE[0]}"'.
    SCRIPT_PATH="${BASH_SOURCE[0]}"
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
from sourcing file .venv/bin/activate
source: Error while reading file '.venv/bin/activate'
```

This problem is not happening when I run the below command, but it is a workaround IMO. 

```shell
> source .venv/bin/activate.fish
```

### System details 
```shell
> uname -a
Darwin Admins-Laptop.local 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:16:46 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8112 arm64

> fish --version
fish, version 3.7.1

> echo $TERM
xterm-256color
```

### Steps to reproduce the issue
```shell
> sudo apt install virtualenv
> virtualenv -p python3 venv
> source venv/bin/activate
```

### Another observation
I tried to record the terminal session with `asciinema`, after starting recording the session, the `source venv/bin/activate` worked without any problem without any additional hack.

**Comment by faho** [comment]
```fish
source .venv/bin/activate.fish
```

**Comment by DataEnggNerd** [comment]
@faho Thanks for the clarity. Awesome tool btw! 🎉
