### ISSUE TITLE
⏎ character preceding every prompt

### ISSUE THREAD

**Issue by ProfessionalNihilist** [fish-shell/fish-shell#1071]
Debian Saucy, added the PPA and installed, set title function as per http://fishshell.com/docs/current/faq.html#faq-titlebar but the issue is not resolved.

Using fish on a headless server over ssh.

    anathema@inez ~> ls
    irclogs/
    ⏎
    anathema@inez ~>

**Comment by gordontyler** [comment]
I get the same problem running fish (built using cygwin) on Windows using ConEmu (and Console2/ConsoleZ as well).

**Comment by krader1961** [comment]
Duplicate of issue #789.
