### ISSUE TITLE
Regressions in TERM support under FreeBSD

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#10723]
From time to time I use an iOS ssh client called "Prompt" to connect to machines on my local network (usually when I need to check on the status of a long-running script under tmux or to run a quick command and I'm too lazy to get off the couch). I hadn't used it in years but a couple of weeks ago I remembered it was available and connected to FreeBSD running the latest fish master and ran into some issues.

As background, Prompt used to run without any issues with `$TERM=xterm-256color` under fish 3.1 on FreeBSD.

1. Without the `terminfo` package installed and with TERM set to the default `xterm-256color`, fish would "not see" the output of scripts; i.e. I would start a clean session and fish would output text at the correct location, but when I run `foo` and it produces a screen of output and exits, typing in fish would type towards the top of the terminal buffer instead of after the output of `foo`
2. Recompiling fish with `terminfo` installed fixed that issue but I ran into another problem where I appear to "randomly" with some likelihood greater than 90% get spurious text echoed to the prompt/terminal (it looks like the payload of what should have been an escaped ANSI escape code, perhaps?). It seems to always be one of two two-char values, as shown in the screenshot below, though it also seems to be our old line ending confusion friend popping up again as the script isn't producing any output at all:

![image](https://github.com/user-attachments/assets/1e20c67d-b33e-4ba6-ae05-4cf57e2e208e)

I recall @faho saying something about an inconsistency with the default xterm-256color profile we ship with under FreeBSD, but iirc it was only about the old backspace/delete conundrum.

For point 1 above, I suggest that we ship a FreeBSD-specific xterm-256color profile because it seems that the differences between that and Linux's version are not so minor after all; for point 2 it could be a regression on FreeBSD in different termcaps exposed via termcap db vs term info or it could be a regression in fish with how it handles certain ansi escapes.

**Comment by faho** [comment]
> Recompiling fish with terminfo installed

You shouldn't have to *recompile* with terminfo installed. It'll just pick up the files when started.



> Without the terminfo package installed and with TERM set to the default xterm-256color

When fish can't find terminfo, it will fall back on an included xterm-256color definition.

Can you post the output of `infocmp -x xterm-256color` with terminfo installed?

Can you post an `asciinema` recording?

> It seems to always be one of two two-char values, as shown in the screenshot below:

That's the kitty keyboard protocol enabling/disabling sequences.

Note that so far we have found two terminals that fail to read those correctly (and print them on screen): emacs' ansi-term and cool-retro-term.

Is there any way to detect the terminal you are using? $TERM isn't it, but is there any other variable to do so?

**Comment by mqudsi** [comment]
No environment variables are set by the specific client, unfortunately.

Here's the `infocmp -x xterm-256color` output, as you can see it's based off the terminfo database entry:

```
#       Reconstructed via infocmp from file: /usr/local/share/terminfo/x/xterm-256color
xterm-256color|xterm with 256 colors,
        OTbs, am, bce, ccc, km, mc5i, mir, msgr, npc, xenl, AX, XF, XT,
        colors#0x100, cols#80, it#8, lines#24, pairs#0x10000,
        acsc=``aaffggiijjkkllmmnnooppqqrrssttuuvvwwxxyyzz{{||}}~~,
        bel=^G, blink=\E[5m, bold=\E[1m, cbt=\E[Z, civis=\E[?25l,
        clear=\E[H\E[2J, cnorm=\E[?12l\E[?25h, cr=\r,
        csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
        cud=\E[%p1%dB, cud1=\n, cuf=\E[%p1%dC, cuf1=\E[C,
        cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
        cvvis=\E[?12;25h, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
        dl=\E[%p1%dM, dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K,
        el1=\E[1K, flash=\E[?5h$<100/>\E[?5l, home=\E[H,
        hpa=\E[%i%p1%dG, ht=^I, hts=\EH, ich=\E[%p1%d@,
        il=\E[%p1%dL, il1=\E[L, ind=\n, indn=\E[%p1%dS,
        initc=\E]4;%p1%d;rgb:%p2%{255}%*%{1000}%/%2.2X/%p3%{255}%*%{1000}%/%2.2X/%p4%{255}%*%{1000}%/%2.2X\E\\,
        invis=\E[8m, is2=\E[!p\E[?3;4l\E[4l\E>, kDC=\E[3;2~,
        kEND=\E[1;2F, kHOM=\E[1;2H, kIC=\E[2;2~, kLFT=\E[1;2D,
        kNXT=\E[6;2~, kPRV=\E[5;2~, kRIT=\E[1;2C, ka1=\EOw,
        ka3=\EOy, kb2=\EOu, kbeg=\EOE, kbs=^H, kc1=\EOq, kc3=\EOs,
        kcbt=\E[Z, kcub1=\EOD, kcud1=\EOB, kcuf1=\EOC, kcuu1=\EOA,
        kdch1=\E[3~, kend=\EOF, kent=\EOM, kf1=\EOP, kf10=\E[21~,
        kf11=\E[23~, kf12=\E[24~, kf13=\E[1;2P, kf14=\E[1;2Q,
        kf15=\E[1;2R, kf16=\E[1;2S, kf17=\E[15;2~, kf18=\E[17;2~,
        kf19=\E[18;2~, kf2=\EOQ, kf20=\E[19;2~, kf21=\E[20;2~,
        kf22=\E[21;2~, kf23=\E[23;2~, kf24=\E[24;2~,
        kf25=\E[1;5P, kf26=\E[1;5Q, kf27=\E[1;5R, kf28=\E[1;5S,
        kf29=\E[15;5~, kf3=\EOR, kf30=\E[17;5~, kf31=\E[18;5~,
        kf32=\E[19;5~, kf33=\E[20;5~, kf34=\E[21;5~,
        kf35=\E[23;5~, kf36=\E[24;5~, kf37=\E[1;6P, kf38=\E[1;6Q,
        kf39=\E[1;6R, kf4=\EOS, kf40=\E[1;6S, kf41=\E[15;6~,
        kf42=\E[17;6~, kf43=\E[18;6~, kf44=\E[19;6~,
        kf45=\E[20;6~, kf46=\E[21;6~, kf47=\E[23;6~,
        kf48=\E[24;6~, kf49=\E[1;3P, kf5=\E[15~, kf50=\E[1;3Q,
        kf51=\E[1;3R, kf52=\E[1;3S, kf53=\E[15;3~, kf54=\E[17;3~,
        kf55=\E[18;3~, kf56=\E[19;3~, kf57=\E[20;3~,
        kf58=\E[21;3~, kf59=\E[23;3~, kf6=\E[17~, kf60=\E[24;3~,
        kf61=\E[1;4P, kf62=\E[1;4Q, kf63=\E[1;4R, kf7=\E[18~,
        kf8=\E[19~, kf9=\E[20~, khome=\EOH, kich1=\E[2~,
        kind=\E[1;2B, kmous=\E[<, knp=\E[6~, kpp=\E[5~,
        kri=\E[1;2A, mc0=\E[i, mc4=\E[4i, mc5=\E[5i, meml=\El,
        memu=\Em, mgc=\E[?69l, nel=\EE, oc=\E]104\007,
        op=\E[39;49m, rc=\E8, rep=%p1%c\E[%p2%{1}%-%db,
        rev=\E[7m, ri=\EM, rin=\E[%p1%dT, ritm=\E[23m, rmacs=\E(B,
        rmam=\E[?7l, rmcup=\E[?1049l\E[23;0;0t, rmir=\E[4l,
        rmkx=\E[?1l\E>, rmm=\E[?1034l, rmso=\E[27m, rmul=\E[24m,
        rs1=\Ec\E]104\007, rs2=\E[!p\E[?3;4l\E[4l\E>, sc=\E7,
        setab=\E[%?%p1%{8}%<%t4%p1%d%e%p1%{16}%<%t10%p1%{8}%-%d%e48;5;%p1%d%;m,
        setaf=\E[%?%p1%{8}%<%t3%p1%d%e%p1%{16}%<%t9%p1%{8}%-%d%e38;5;%p1%d%;m,
        sgr=%?%p9%t\E(0%e\E(B%;\E[0%?%p6%t;1%;%?%p5%t;2%;%?%p2%t;4%;%?%p1%p3%|%t;7%;%?%p4%t;5%;%?%p7%t;8%;m,
        sgr0=\E(B\E[m, sitm=\E[3m, smacs=\E(0, smam=\E[?7h,
        smcup=\E[?1049h\E[22;0;0t, smglp=\E[?69h\E[%i%p1%ds,
        smglr=\E[?69h\E[%i%p1%d;%p2%ds,
        smgrp=\E[?69h\E[%i;%p1%ds, smir=\E[4h, smkx=\E[?1h\E=,
        smm=\E[?1034h, smso=\E[7m, smul=\E[4m, tbc=\E[3g,
        u6=\E[%i%d;%dR, u7=\E[6n, u8=\E[?%[;0123456789]c,
        u9=\E[c, vpa=\E[%i%p1%dd, BD=\E[?2004l, BE=\E[?2004h,
        Cr=\E]112\007, Cs=\E]12;%p1%s\007, E3=\E[3J,
        Ms=\E]52;%p1%s;%p2%s\007, PE=\E[201~, PS=\E[200~,
        RV=\E[>c, Se=\E[2 q, Ss=\E[%p1%d q,
        XM=\E[?1006;1000%?%p1%{1}%=%th%el%;, XR=\E[>0q,
        fd=\E[?1004l, fe=\E[?1004h, kDC3=\E[3;3~, kDC4=\E[3;4~,
        kDC5=\E[3;5~, kDC6=\E[3;6~, kDC7=\E[3;7~, kDN=\E[1;2B,
        kDN3=\E[1;3B, kDN4=\E[1;4B, kDN5=\E[1;5B, kDN6=\E[1;6B,
        kDN7=\E[1;7B, kEND3=\E[1;3F, kEND4=\E[1;4F,
        kEND5=\E[1;5F, kEND6=\E[1;6F, kEND7=\E[1;7F,
        kHOM3=\E[1;3H, kHOM4=\E[1;4H, kHOM5=\E[1;5H,
        kHOM6=\E[1;6H, kHOM7=\E[1;7H, kIC3=\E[2;3~, kIC4=\E[2;4~,
        kIC5=\E[2;5~, kIC6=\E[2;6~, kIC7=\E[2;7~, kLFT3=\E[1;3D,
        kLFT4=\E[1;4D, kLFT5=\E[1;5D, kLFT6=\E[1;6D,
        kLFT7=\E[1;7D, kNXT3=\E[6;3~, kNXT4=\E[6;4~,
        kNXT5=\E[6;5~, kNXT6=\E[6;6~, kNXT7=\E[6;7~,
        kPRV3=\E[5;3~, kPRV4=\E[5;4~, kPRV5=\E[5;5~,
        kPRV6=\E[5;6~, kPRV7=\E[5;7~, kRIT3=\E[1;3C,
        kRIT4=\E[1;4C, kRIT5=\E[1;5C, kRIT6=\E[1;6C,
        kRIT7=\E[1;7C, kUP=\E[1;2A, kUP3=\E[1;3A, kUP4=\E[1;4A,
        kUP5=\E[1;5A, kUP6=\E[1;6A, kUP7=\E[1;7A, ka2=\EOx,
        kb1=\EOt, kb3=\EOv, kc2=\EOr, kp5=\EOE, kpADD=\EOk,
        kpCMA=\EOl, kpDIV=\EOo, kpDOT=\EOn, kpMUL=\EOj, kpSUB=\EOm,
        kpZRO=\EOp, kxIN=\E[I, kxOUT=\E[O, rmxx=\E[29m,
        rv=\E\\[41;[1-6][0-9][0-9];0c, smxx=\E[9m,
        xm=\E[<%i%p3%d;%p1%d;%p2%d;%?%p4%tM%em%;,
        xr=\EP>\\|XTerm\\([1-9][0-9]+\\)\E\\\\,
```

**Comment by faho** [comment]
Okay, comparing against my output, excluding whitespace differences (yours starts with spaces mine with tab), I get this diff:

```
ka3=\EOy, kb2=\EOu, kbeg=\EOE, kbs=^H, kc1=\EOq, kc3=\EOs,
+ka3=\EOy, kb2=\EOu, kbeg=\EOE, kbs=^?, kc1=\EOq, kc3=\EOs,
```

Yes, it is *just* backspace.

It can't be terminfo.

**Comment by faho** [comment]
> No environment variables are set by the specific client, unfortunately.

So far we have declined to support minor clients mishandling these protocols if we cannot detect them.

Unfortunately, if we can't detect them the only way to support them would be to add an option to turn these things either on or off. If we default to off, you would have to find out that you should turn it off, if we default to on people would have to find out that they would have to turn them on - which makes them *much* less useful.

Like I said above, this is the third terminal that fails. The other two are unmaintained and the single worst terminal emulator I know, respectively.

**Comment by mqudsi** [comment]
Hmmm that's weird. 

Here's the asciinema link, but I don't know what it'll reveal since everything behaves fine within the asciinema app even when using the terminal emulator in question: https://asciinema.org/a/fQkhkPVYNNwYNpDydbL4LSOQ4

One more bug I just saw again and remembered (still happens with terminfo), pressing `tab` to complete a command results in duplication of text, e.g.

```
> asci<tab>
> asciasciinema
```

(with the the original text in a different color than the completion text, presumably because it wasn't recognized as a command)

As for the configuration option, if we *do* ship such an option, this client should certainly not be the reason for setting defaulting it to off. It was once the only iOS solution and very popular but I don't think that's the case anymore.

**Comment by faho** [comment]
Okay, if it's not the cursor movement, one likely explanation is the terminal modes.

You'd have to execute the equivalent of `stty -F /path/to/pts` from *another* terminal in order to get the modes that are in effect while fish is running. That explains why it works with `asciinema`, since it doesn't record them and while it is playing the external command modes are in effect.

**Comment by faho** [comment]
It would also be good to see how it works with 3.7.1, as opposed to 3.1.

**Comment by mqudsi** [comment]
Sorry, I meant 3.7.1

**Comment by mqudsi** [comment]
Ok, I think the tab completions appending is just because of the off-by-two width due to the escape code being spewed to the console.

This is the `stty` output from a second SSH session inspecting the pts of the first one:

```
> stty -af /dev/pts/1
speed 9600 baud; 51 rows; 97 columns;
lflags: -icanon isig -iexten -echo echoe -echok echoke -echonl echoctl
	-echoprt -altwerase -noflsh -tostop -flusho -pendin -nokerninfo
	-extproc
iflags: -istrip -icrnl -inlcr -igncr -ixon -ixoff ixany imaxbel -ignbrk
	brkint -inpck -ignpar -parmrk iutf8
oflags: opost onlcr -ocrnl tab0 -onocr -onlret
cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
	-dtrflow -mdmbuf rtsdtr
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
	eol2 = <undef>; erase = ^?; erase2 = ^H; intr = ^C; kill = ^U;
	lnext = ^V; min = 1; quit = <undef>; reprint = ^R; start = ^Q;
	status = ^T; stop = ^S; susp = <undef>; time = 0; werase = ^W;
```

**Comment by faho** [comment]
Okay, diffing those modes against the ones I get reveals no useful difference. 
(there's also no difference between 3.7.1 and master on linux)

The output modes that differ are things like "olcuc" ("translate lowercase characters to uppercase") that I would assume are just not a thing on BSD, because otherwise you'd notice.

I see "pendin" is off where in #10717 it was apparently on.

----------

You could try patching out the kitty keyboard escapes to see what that fixes.

I'm also still confused that you'd get different behavior if terminfo isn't installed if you're using xterm-256color.

**Comment by mqudsi** [comment]
Maybe I should uninstall terminfo and try again. It is likely that I updated the specific fish master revision when (unnecessarily) recompiling after installing terminfo.

**Comment by krobelus** [comment]
> Without the terminfo package installed and with TERM set to the default xterm-256color, fish would "not see" the output of scripts; i.e. I would start a clean session and fish would output text at the correct location, but when I run foo and it produces a screen of output and exits, typing in fish would type towards the top of the terminal buffer instead of after the output of foo

I'm failing to reproduce this. I uninstalled `terminfo-db` on a [fresh BSD system](.builds/freebsd.yml).
Maybe double-check if it really worked on 3.7.1 and bisect.

> Recompiling fish with terminfo installed fixed that issue but I ran into another problem where I appear to "randomly" with some likelihood greater than 90% get spurious text echoed to the prompt/terminal (it looks like the payload of what should have been an escaped ANSI escape code, perhaps?). It seems to always be one of two two-char values, as shown in the screenshot below, though it also seems to be our old line ending confusion friend popping up again as the script isn't producing any output at all:

This reproduces consistently but it's unrelated to freebsd or terminfo: we print `"\x1b[=5u"` unconditionally which is what is being echoed. It also happens on Linux, reproducible by running `printf "\033[=5u"` in bash inside a Prompt session.
I've reported this problem to Prompt (I don't think they have a public bug tracker).

**Comment by faho** [comment]
Okay, is there anything left here?

@mqudsi can you check again?

**Comment by mqudsi** [comment]
I can't reproduce the problem with fish's idea of the current line number being out-of-sync with the actual location after executing a command. The possibilities are that it was specific to whatever command I executed somehow or it was an issue with an earlier fish build (as I did update and recompile after installing `terminfo-db` as I didn't realize it would be used without a recompile).

I'll close this and re-open if/when anything changes.

**Comment by jrmarino** [comment]
I just build fish 4.0 and had to search why "5u" was at the prompt (Dragonfly BSD - I expect it to be present in FreeBSD too)

![Image](https://github.com/user-attachments/assets/96f5dee8-518a-4d26-9f17-d33795dcaedd)

This is definitively still an active problem - fix should be re-added to the milestone?

**Comment by krobelus** [comment]
which terminal?

**Comment by jrmarino** [comment]
sorry, I don't understand the question.  If you mean the TERM definition, it's "xterm-256color" as you can see the screenshot

**Comment by jrmarino** [comment]
the terminfo database in this case is not from base -- it's userland (this is being built in ravenports (http://www.ravenports.com) so it's the latest version.

**Comment by faho** [comment]
> sorry, I don't understand the question

Which terminal emulator? What software or hardware is providing the terminal here?

It is buggy. It misparses a simple CSI-sequence, which is why it shows the "5u".

We will try to work around it if we can detect it.

**Comment by jrmarino** [comment]
I'm using [bitvise](https://bitvise.com/ssh-client-download)

these settings:

![Image](https://github.com/user-attachments/assets/67431532-3621-418b-ba5b-bc0dfed2ef97)

**Comment by faho** [comment]
Can you provide the output of `env` if you *don't* set TERM=xterm-256color manually?

**Comment by jrmarino** [comment]
and in this environment, TERM is set to "dumb"

**Comment by faho** [comment]
Okay, that's a weird proprietary ssh client for windows.

The bug is in it, and has nothing to do with the server operating system. It is unrelated to FreeBSD or DragonFlyBSD.

You can try contacting bitvise and asking them to fix their terminal parsing. Or you can try [putty](https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html), which is free software and doesn't have this bug.

**Comment by jrmarino** [comment]
hmm - if multiple environments have this bug - can fish avoid using it?
putty is pretty terrible on windows.  I use it in a specific case involving Function key handling (which putty does correctly and bitvise can't seem to) but the file manager on bitvise is pretty invaluable (not to mention the terminal looks a lot better).

I'm going to mess around with some settings to see if anything avoids it.

**Comment by faho** [comment]
> hmm - if multiple environments have this bug - can fish avoid using it?

It isn't multiple environments. It is bitvise. The problem is at the client side.

Fish will work around it where it can, but it appears in this case we cannot tell that bitvise is the terminal, so we cannot work around it.

**Comment by jrmarino** [comment]
okay, so the first thing I did was disable "bvterm" and that worked.  by the way, I told you wrong, the default TERM setting was "xterm" not "dumb".  Here's what it looks like now:

![Image](https://github.com/user-attachments/assets/3d6d3fbe-ab00-45e5-8cd1-798c83e5436c)

proving only change was not defaulting to bvterm:

![Image](https://github.com/user-attachments/assets/5ef90e06-ec77-4b8e-a5ff-fa2f858b0f59)

**Comment by krobelus** [comment]
@jrmarino the next Bitvize SSH Client version [will include a fix](https://fogbugz.bitvise.com/default.asp?62341_tqfc287g)

**Comment by jrmarino** [comment]
oh wow - that's good news, thanks.
