### ISSUE TITLE
VIM MODE NEED TO PRESS TWICE `l` TO ACCEPT auto-complete

### ISSUE THREAD

**Issue by NEX-S** [fish-shell/fish-shell#10734]
fish, version 3.7.1

in fish's vim normal mode, we have to press twice `l` to accept auto-complete

for example:
complete-suggestion:
sudo apt update

user input:
sudo ap|

we got sudo apt update in virtual text but need to press `<ESC>ll` to accept complete

this is kinda annoing

i dont know if it is expected behaviour but i wish to press `<ESC>l` to accept when cursor is at end of line(oh-my-zsh's vi mode behaviour)

i think this is more friendly and efficient.

**Comment by krobelus** [comment]
this is fixed in latest master

**Comment by zanchey** [comment]
Duplicate of #10286
