### ISSUE TITLE
error: Error when renaming history file: Device or resource busy on nixos with impermanence

### ISSUE THREAD

**Issue by a-viv-a** [fish-shell/fish-shell#10730]
I'm running fish version 3.7.1 in foot on nix os. Notably, I'm using [impermanence](https://github.com/nix-community/impermanence).

Rarely, when I run a command in fish, I get the error `error: Error when renaming history file: Device or resource busy`. I don't have good reproduction steps as it happens pretty rarely.

I believe this is related to impermanence managing the fish history file. I'm happy to go open this issue there instead, but I haven't seen this issue with other tools.

I believe adding retries to `save_internal_via_rewrite` (or the pre rust version) would handle my usecase. It's also possible this isn't a problem, and the only issue is the error being printed?

**Comment by kjnsn** [comment]
It looks like impermanence uses bind mounts, so you're running into https://unix.stackexchange.com/questions/360787/cant-overwrite-a-file-by-moving-another-over-it

When fish rewrites the history file it creates a tempfile, writes the new contents into that temp file, then does `mv temp.history real.history`.

**Comment by krobelus** [comment]
If the reason for the "write-to-tempfile & rename" trick is only for file systems like NFS that don't support locking, then we could detect NFS or bind mounts, I guess. Needs more research.

It does fail consistently, right? I believe fish usually appends to the file, so the problem will only trigger once in a while (or on `history merge` if entries from different fish need to be merged).

Is there any reason why you are not bind-mounting the entire directory?

**Comment by a-viv-a** [comment]
It does not seem to fail consistently. If I run novel commands and then run `history merge`/`save`, it doesn't seem to fail?

As for not bind mounting the entire directory... I could and nothing terrible would happen, but `~/.local/share/fish` also has symlinked files (home manager generated completions) and the potential to store unwanted state. The idea of using persistence is to ensure that only the files you care about stick around. My leaning is to only persist files instead of directories if I only want to persist a specific file.

If bind mounting the whole directory solves the problem I think that is probably acceptable--I'll try it and add to the impermanence documentation if the problem goes away.

**Comment by krobelus** [comment]
On Thu, Sep 19, 2024 at 09:45:15AM -0700, Aviva wrote:
> I could and nothing terrible would happen, but `~/.local/share/fish`

That's gonna change to ~/.cache in an upcoming release (next we should get rid of this cache completely)

**Comment by zanchey** [comment]
> When fish rewrites the history file it creates a tempfile, writes the new contents into that temp file, then does `mv temp.history real.history`.

This is the only way of ensuring filesystem actions are atomic (AFAIK), so I don't know this is something we can fix.

**Comment by krobelus** [comment]
> That's gonna change to ~/.cache in an upcoming release

Sorry what I meant is that completions generated by `fish_update_completions` will be moved from `~/.local/share/fish` to `~/.cache/fish`

**Comment by ridiculousfish** [comment]
This happens rarely because most of the time, fish strictly appends to the history file. But approximately once every 25 commands, [fish will "vacuum" the file](https://github.com/fish-shell/fish-shell/blob/e3993a3d969295e9bf91f0e35e9945213c4e9bcd/src/history.rs#L942) which deduplicates commands; that's when I would expect this to fail.

**Comment by a-viv-a** [comment]
I'm pretty sure I haven't seen it fail since switching to bind mounting the entire directory, I'll give it a few more weeks of use and then PR the impermanence docs + close the issue. Thanks all for the help!

**Comment by faho** [comment]
It appears there's nothing really to do from our end, closing.
