### ISSUE TITLE
Combining `fish_commandline_append` and `end-of-line`

### ISSUE THREAD

**Issue by RensOliemans** [fish-shell/fish-shell#10735]
> fish --version
    fish, version 3.7.0
    > uname -a
    Linux ada 6.10.7-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Fri Aug 30 00:08:59 UTC 2024 x86_64 GNU/Linux
    > echo $TERM
    alacritty

Heya, I'm trying to create a "pipe" alternative to the amazing `Alt+s` keybinding - the one that prefixes `sudo` to the current command or the previous command if the prompt is empty.

See here for a video overview of my problem:
https://asciinema.org/a/vVMducwY5jvrjaKhXysBkmHgQ

In text: I found `fish_commandline_append`, which works, but doesn't move the cursor. Ideally I want the cursor to be placed at the end of the line, but this does not work:

	function append_pipe
		fish_commandline_append " | "
		end-of-line
	end
	bind \e\\ 'append_pipe'

Since I get the following error: `fish: end-of-line: commando niet gevonden...` (translates to command not found). I get the feeling that `end-of-line` isn't a function in the same way that `fish_commandline_append` is, but I am unsure about this. Could you point me to the right direction/documentation?

**Comment by faho** [comment]
Try `commandline -f end-of-line`

It's a commandline "function", only for use with commandline.

**Comment by RensOliemans** [comment]
Thanks, this works!

See https://asciinema.org/a/676847 for a mini overview (I just learnt about asciinema, it's fun). Put the code below in your fish config to try it out.

```fish
function append_pipe
    fish_commandline_append " | "
    commandline -f end-of-line
end

bind \e\\ append_pipe
```

Of course, the oneliner `bind \e\\ 'fish_commandline_append " | "; commandline -f end-of-line'` works as well.
