### ISSUE TITLE
ctrl-backspace in Rust

### ISSUE THREAD

**Issue by chapmanjacobd** [fish-shell/fish-shell#10741]
Linux len 6.10.10-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Sep 12 18:26:09 UTC 2024 x86_64 GNU/Linux
    echo $version
    3.7.1-2317-g2a53dd9ed

I tried using fish without third-party customizations and it did not change the behavior. Fish 3.7.1 does not have this problem.

(Initially reported in #10738) There _is_ a difference in behavior in between kitty on my laptop and termux/ssh from my phone to my laptop. This issue is unrelated to `bind` configuration/configurability.

ctrl-backspace is not detected in the kitty session. Pressing it does not delete a character after running:

    kitty sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'
    cargo run

**Comment by krobelus** [comment]
It is recognized (try `fish_key_reader`), it was just not bound. This is noticeable only on terminals that disambiguate it from `backspace`. There's probably a few more CUA keys we can bind now

**Comment by chapmanjacobd** [comment]
ahhh okay. Yes, I can confirm it is working in https://github.com/fish-shell/fish-shell/commit/904649c5c5a925b0be89d4700ce1c6db49380478 with `bind ctrl-backspace ...` !
