### ISSUE TITLE
FR:  Support Arbitrary-precision Arithmetic in `math`

### ISSUE THREAD

**Issue by NeumoNeumo** [fish-shell/fish-shell#10744]
The bultin command `math` is a brilliant daily tool. However, it does not support the calculation between large numbers. For example, `math "2147483648*214748348"` would result in an output `math: Error: Result magnitude is too large `. But arbitrary-precision integer calculation is supported in many languages including `Python`, `Haskell` and `Perl`.

Would you like to add this support to fish shell? I think I can make an arbitrary-precision calculator in the next few weeks to replace the `tinyexpr.rs` if I am permitted. :smile:

**Comment by faho** [comment]
Gonna be honest: math is a simple tool for simple calculations.

If you're doing things that need arbitrary precision you should use a different tool.
