### ISSUE TITLE
history breaks after reboot

### ISSUE THREAD

**Issue by e00E** [fish-shell/fish-shell#10740]
version 3.7.1, arch linux, alacritty

Sometimes after a reboot, fish's history is broken. When I navigate it for example by pressing up arrow, I get nothing. The last time this happened I inspected the fish history file at location `~/.local/share/fish/fish_history`. I see the following at the end of the file:

```
- cmd: my-command-1
  when: 1726778744
- cmd: reboot
  when: 1726778950
<NULL><NULL><NULL>- cmd: my-command-2
  when: 1726828048
- cmd: my-command-3
  when: 1726828054
```

 `<NULL>` indicates a null byte as seen in a hex editor. The null bytes repeat 37 times where I indicate them 3 times above.

When I delete the null bytes, the history works again.

**Comment by Xiretza** [comment]
Unfortunately a hard to track down known issue, see #10300/#10483.

**Comment by kjnsn** [comment]
I think this would likely be fixed by https://github.com/fish-shell/fish-shell/pull/10680, as json-seq automatically skips over invalid data.
