### ISSUE TITLE
Feature request: expanding to the root of the git repository

### ISSUE THREAD

**Issue by KommuSoft** [fish-shell/fish-shell#10746]
Hi,

Is it possible to define custom expansions. As far as I can see, fish does not expand the tilde (`~`) to the home directory, but it might be useful that one can define such *custom* expansions.

More precisely, I was thinking of a pattern to expand to the git root, like for example `...`, one can define a function `...` to move to the git repo root:

```
# ~/.config/fish/functions/....fish
function ... --description 'move to the root directory of the git repository'
  cd (git rev-parse --show-toplevel)
end
```

But this does not allow to expand arbitrary paths. it might be useful to have something like `vim .../.git/hooks/pre-commit` for example.

**Comment by faho** [comment]
Use an [abbreviation](https://fishshell.com/docs/current/interactive.html#abbreviations):

```fish
function from_git_root
    set -l root (git rev-parse --show-toplevel)
    or return

    string replace ':git/' -- $root $argv
end

abbr --add git_root --position anywhere --regex ':git/.*' --function from_git_root
```

Now type `:git/.git/hooks/pre-commit` and press space or enter and it will expand - unless there's no git root, in which case it will stay as it is.
