### ISSUE TITLE
FOO=BAR syntax emits no errors when setting a read-only variable

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#10753]
Example:

```
SHLVL=5 echo $SHLVL
```

This should report an error because SHLVL is read-only, but it quietly ignores the set.

Compare to:

```
set SHLVL 5
set: Tried to change the read-only variable 'SHLVL'
```

(Also SHLVL can probably be made read-write).

Credit to "LilleCarl (Salsa9)" on matrix for reporting this.

**Comment by krobelus** [comment]
Duplicate of #7790
