### ISSUE TITLE
Unable to use npm command in fish shell

### ISSUE THREAD

**Issue by peterdanwan** [fish-shell/fish-shell#10768]
`Fish Version`: 3.7.1
`Operating System`: MSYS_NT-10.0-22631 DESKTOP-CIBPA48 3.5.3.x86_64 2024-05-06 06:45 UTC x86_64 Msys

Hello! For some reason, I'm unable to use the `npm` command in the fish shell, although I have access to the `npm` command in other terminals like PowerShell, and CMD on my Windows 11 computer.

When I try to run _any_ `npm` command within the fish shell, I get this message:

```sh
/bin/bash: C:/Program Files/nodejs/npm: No such file or directory
```
![error-message](https://github.com/user-attachments/assets/256ffbe3-3699-4fe1-bc32-478909590be6)

On Windows, I've added the folder which has the `npm` command to my `User Path` and ensured that the `npm` command itself is executable:

![npm-and-path](https://github.com/user-attachments/assets/3ee68de6-1dda-41b1-a435-53c00128ffd8)

This is also what I get when I echo the `PATH` in `fish`:
![fish-path](https://github.com/user-attachments/assets/c1b4b46e-eab2-4867-96d5-ac8425d29e56)

Strangely I can use, `node`, but not `npm`:
![node-works-but-not-npm](https://github.com/user-attachments/assets/18a69239-0ef4-4e13-ac66-603939e09695)

On CMD I'm able to use `npm` commands:
![cmd-npm-works](https://github.com/user-attachments/assets/7770b169-b5d9-4269-8355-85b348bee614)

**Comment by faho** [comment]
Tbh you'll probably have better luck asking the msys people instead. It's a sufficiently weird system that there are things we're likely to miss. We are also aware of long-standing [issues with msys' fish packaging](https://github.com/msys2/MSYS2-packages/issues/1634).

What I can tell you is to check that the $PATH entry is correct and not e.g. split at spaces.

Run `set -S PATH` or `echo $PATH[-1]` to see that it's really `/c/Program Files/nodejs` and not `/c/Program` and `Files/nodejs` separately.

Your attempt here also ends up running a bash to run more things, and that ends up using windows paths, which fish wouldn't translate (there's no `C:/` in fish). This ends up giving a "no such file" error, which in some shells (and I think older bash versions) can also mean that the *interpreter* (the thing in the shebang line) doesn't exist. If you run it inside bash it might end up running it directly in that shell instead.

-----

Also as a heads up: As far as I'm aware msys/cygwin still don't have a working rust port, so the upcoming fish 4.0 won't be available there.

**Comment by peterdanwan** [comment]
Thanks @faho for the advice! I'll try out your suggestions when I have a chance. Really appreciate the suggestions cause I was at my wits end with the things I tried haha
