### ISSUE TITLE
`edit_command_buffer` fails due to unrecognized `fish_indent` options.

### ISSUE THREAD

**Issue by lgarron** [fish-shell/fish-shell#10770]
## Steps

1. Press ⌥E (`alt-e`)

## Expected

I can edit the command in an editor.

## Observed

The editor opens, but the terminal prints:

```
fish_indent: unrecognized option `--only-indent'
fish_indent: unrecognized option `--only-unindent'
```

`edit_command_buffer` is invoked through the default keybinding and the editor opens a blank file, although anything entered into the file is placed in the current prompt.

Completions for `fish_indent` show the `--only-indent` and `--only-unindent` arguments, but I'm guessing they're not implemented on `main` yet?

# Environment

```
> fish --version
fish, version 3.7.1
> echo $version
3.7.1-2347-g9c461d3bd
```

(Built from a recent `master`.)

macOS 15.0.1

`sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'` still exhibits the problem.

**Comment by krobelus** [comment]
what's `fish_indent --version`?

**Comment by lgarron** [comment]
Aha!

```
│ fish_indent --version
fish_indent, version 3.7.
```

Looks like `sudo make install` correctly installed `fish_indent`, but `fish` is going off the default path instead of adjacent installed binaries. Do you have a recommendation for how to run off `main` without also clobbering stable `fish`?

**Comment by lgarron** [comment]
Okay, this worked after a few tries:

```shell
mkdir -p $HOME/.fish-master
mkdir build; cd build
cmake -DCMAKE_INSTALL_PREFIX=$HOME/.fish-master ..
make
sudo make install
```

And then adding `$HOME/.fish-master/bin` to the top of `$PATH`.

I can live with that (although my brain finds it very funky to see `master` instead of `main`, I'll file a separate issue for that).

**Comment by krobelus** [comment]
oh so you ran `/usr/local/bin/fish` without it being first in PATH.

Running the adjacent one would work but it's a bit too much magic.

```fish
function fish_indent
    set -l cmd (status fish-path)
    {$cmd}_indent $argv
end
```

I guess we should bake it into `commandline`. No strong opinion here

**Comment by krobelus** [comment]
this is fixed now

**Comment by lgarron** [comment]
@krobelus Thanks! I should be okay without it, but I'm sure others will benefit from it without ever noticing!
