### ISSUE TITLE
Default colors in remote shells

### ISSUE THREAD

**Issue by stargazer1984** [fish-shell/fish-shell#10797]
fish, version 3.7.1

The default configuration in fish has some very useful color settings that change in different environments.

One inconsistency is the current setting for the root user in ssh shells:
While the hostname is displayed yellow in ssh and white on the client, becoming root in the ssh shell by using sudo displays the hostname in white again, showing the same colors as a local root shell. If the ssh shell logs in as root directly, the hostname is correctly displayed as yellow.

Additionally, the color for the unprivileged user and root are always the same on both local and remote systems.

This color scheme can lead to confusion among multiple shell sessions that would be easily avoided by keeping the remote host color (yellow) for root shells for both direct root logins and shells acquired via sudo.

Additionally I believe using the same color for root and unprivileged users is also not optimal and both in local shells and remote shells the root user should be displayed in bright red by default to indicate a significant difference.

Current state:

Root shell on local client:
![shell](https://github.com/user-attachments/assets/48316c80-bc5f-46a7-aec7-bab28e34a6a5)

Root shell (ssh) by direct login as root:
![rootatmyserver](https://github.com/user-attachments/assets/746c788f-067a-4916-b684-7d941bee42d3)

Root shell (ssh) by `sudo -i`:
![sudoatmyserver](https://github.com/user-attachments/assets/b892b27a-0971-40ce-8b22-b24c0026ce76)

Unprivileged local user:
![useratmyclient](https://github.com/user-attachments/assets/11d341f3-21bb-4f77-b539-1c3055760e6c)

Unprivileged remote user:
![useratmyserver](https://github.com/user-attachments/assets/d16a2a06-3850-4fb5-9093-a7d9fbf753e6)

Suggested change:

Root shell on local client:
![new-rootatmyclient](https://github.com/user-attachments/assets/1fe17d4c-d32c-444a-a4e7-c805d87664ff)

Root shell in remote host: (direct root login and via sudo)
![new-rootatmyserver](https://github.com/user-attachments/assets/7d88c8a6-cbbb-44f5-b09f-1defbe6a5f09)

**Comment by faho** [comment]
Unfortunately, the only way we have to detect that it's a remote shell [is environment variables](https://github.com/fish-shell/fish-shell/blob/b625c566b148dfa0ba39ace268bad9e2616ee1af/share/functions/prompt_login.fish#L21-L25), and `sudo -i` cleans those.

So there is no way for us to do this.
