### ISSUE TITLE
revisit the use of `posix_spawn` on Linux

### ISSUE THREAD

**Issue by godmar** [fish-shell/fish-shell#10791]
Following up on a prior discussion from 2016, where it was pointed out that fish can't use `posix_spawn` because it lacked support for calling `tcsetpgrp` in the child.

As of GNU Libc 2.35, this is now possible with [`posix_spawn_file_actions_addtcsetpgrp_np`](https://docs.rs/libc/latest/libc/fn.posix_spawn_file_actions_addtcsetpgrp_np.html).  I believe this should remove any objections to using `posix_spawn`, and because of its use of `vfork()`, we can expect it to be faster. I'm not volunteering a PR here; just pointing out that this was added a couple of years ago.

--
> Frankly I don't understand the antagonism towards the `posix_spawn` path. IMO it's much cleaner than fork, which has truly nasty issues around multithreading. I wish we could use `posix_spawn` exclusively. 

> Edit: Also, to address a particular detail at the top of this thread: you are right to say "ugh" regarding calling `tcsetpgrp` in parent and child, but in fact this is [standard practice](https://www.gnu.org/software/libc/manual/html_node/Launching-Jobs.html) when using fork, to work around a race. If `posix_spawn` had an answer to `tcsetpgrp` (similar to `posix_spawnattr_setpgroup`), then we could actually fix the race.

_Originally posted by @ridiculousfish in https://github.com/fish-shell/fish-shell/issues/3149#issuecomment-227041751_

**Comment by faho** [comment]
Alright, I've done some experiments on this.

It applies:

1. The command you enter into the commandline (not bindings or completions)
2. Scripts run with `status job-control full` (which isn't common)

The speedup is a constant per executed command. So it will look impressive if you try e.g. /bin/true, but it melts away as soon as the command does something. E.g. if in your repo `git status` takes 10ms, it will be ~3% faster, for a 0.3ms speedup.

That's well below anything you would notice, making it an insignificant improvement.

And there are two big downsides:

1. This is a `_np`, i.e. "non-portable" function, meaning this would have to be a secondary code path.
2. If the tcsetpgrp fails, the entire spawn is aborted.

That latter one is pretty big - I find the conditions here for when to add the tcsetpgrp annoyingly hard to get right.

So I'm gonna say that this isn't worth it for now. If this is ever available more widely and we could drop the fork/exec path entirely it would be.

**Comment by mqudsi** [comment]
I agree with @faho's assessment.

IMHO if it's a Linux-only thing then the better option would be to explore using io_uring to spawn processes. It's just as platform-specific but you can get a much bigger speedup and you can customize its behavior instead of being locked into the specified semantics.

An LWN article on a proposed API to do that for you from 2022: https://lwn.net/Articles/908268/

**Comment by godmar** [comment]
> 
> The speedup is a constant per executed command. So it will look impressive if you try e.g. /bin/true, but it melts away as soon as the command does something. E.g. if in your repo `git status` takes 10ms, it will be ~3% faster, for a 0.3ms speedup.
> 
> That's well below anything you would notice, making it an insignificant improvement.
> 

I view this a bit differently.

If you're optimizing an ordinary program, then yes - you need to apply Amdahl's law, identify the speedup and put it in relation to what proportion of the program is being sped up. This is because you're only running a single instance of that program.

But when optimizing systems code - and your shell is an example of systems code - I apply a different consideration, namely that any gains from optimization are multiplied by the number of instances in which this code runs.  So a 0.3ms speedup translates into 5 mins when 1000 users run it 1000 times each.

That doesn't mean that you shouldn't, as usual, focus your optimization efforts on the code sections where most time is spent, but it means, in my opinion, that you need to look differently at the actual impact of smaller optimizations which under Amdahl's law you'd discard.
