### ISSUE TITLE
Struggling with key bindings insert = insert mode

### ISSUE THREAD

**Issue by TRPB** [fish-shell/fish-shell#10798]
Fish 3.7.1 on NixOS with Foot terminal and using vim mode `fish_vi_key_bindings`

I'm trying to bind the insert key to enter insert mode when in command mode using but I'm not sure I am properly understanding the documentation.

If I run `fish_key_reader` I get

```
bind -k ic 'do something'
bind \e\[2~ 'do something'
```

So I tried:

```
bind \e\[2~ --sets-mode insert
```

that just prints the current binding. Ok, it needs a command, to run:

```
bind \e\[2~ --sets-mode insert ''
```

That looks like it should work. Is command mode not `default` in vim mode?  

```
bind -M visual \e\[2~ --sets-mode insert ''
```

It still doesn't add the binding. Any hints here would be welcome. I think it's that he mode isn't clear but there's no command mode in `bind --list-modes` so it must be default or visual (which in vi is selection mode so seems unlikely)

**Comment by faho** [comment]
You need to add a command to bind, e.g.

```fish
bind \e\[2~ --sets-mode insert true
```

**Comment by TRPB** [comment]
thanks, that still doesn't change the mode when pressed though
