### ISSUE TITLE
`E` in vim mode gets stuck, should have `forward-single-char`

### ISSUE THREAD

**Issue by max-sixty** [fish-shell/fish-shell#10790]
Hitting `E` in multiword commands gets "stuck" at the end of words, for example, where `|` is the cursor:

```
fish_vi_key_bindings

ec|ho foo bar
# hit E
echo| foo bar # correct!
# hit E again
echo| foo bar # incorrect, no movement (but a flicker!)
```

Currently there are bindings in fish vi mode for `e` & `E`:

```
bind --preset e forward-single-char forward-word backward-char
bind --preset E forward-bigword backward-char
```

Adding `forward-single-char` to `E`, mirroring `e`, makes it work:

```
bind --preset E forward-single-char forward-bigword backward-char

echo| foo bar
# hit E
echo foo| bar # correct!
```

...though is there something I'm missing / some other case this fails?

```
fish, version 3.7.1
```

**Comment by krobelus** [comment]
this has been fixed

**Comment by zanchey** [comment]
(was fixed by https://github.com/fish-shell/fish-shell/pull/9700)
