### ISSUE TITLE
Vi cursor wont change shape

### ISSUE THREAD

**Issue by vdawg-git** [fish-shell/fish-shell#10806]
The Vi mode cursor never changes.
When I start Fish it is in insert mode and thus the cursor is a line.
However it wont change into a block once I press escape.

When I execute a command the cursor becomes a block as the new input start in command mode. And it will stay as that when I switch to insert mode.

Running:
  `sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= XDG_DATA_DIRS= fish'` followed by `fish_vi_key_bindings` still reproduces the bug.

### Version:
fish, version 3.7.1

### OS
Arch with Hyprland.

`Linux swordfish 6.11.4-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 17 Oct 2024 20:53:41 +0000 x86_64 GNU/Linux`

### Terminals 
All (Kitty, Foot, VS Code integrated terminal)

**Comment by krobelus** [comment]
> Running:
sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= XDG_DATA_DIRS= fish' followed by fish_vi_key_bindings still reproduces the bug.

On 3.7.1 it's also necessary to run something like ` set fish_cursor_insert line`
That seems to work for me. If it doesn't for you, try with `env -i PATH=$PATH HOME=...`

The next release will add default shapes for insert/replace mode, then it should work out of the box.

**Comment by vdawg-git** [comment]
I tried that now.
I also copied over this block from the docs:
```fish
# Emulates vim's cursor shape behavior
# Set the normal and visual mode cursors to a block
set fish_cursor_default block
# Set the insert mode cursor to a line
set fish_cursor_insert line
# Set the replace mode cursors to an underscore
set fish_cursor_replace_one underscore
set fish_cursor_replace underscore
# Set the external cursor to a line. The external cursor appears when a command is started.
# The cursor shape takes the value of fish_cursor_default when fish_cursor_external is not specified.
set fish_cursor_external line
# The following variable can be used to configure cursor shape in
# visual mode, but due to fish_cursor_default, is redundant here
set fish_cursor_visual block
```
The cursor still wont change its shape.
However with this config, it always is a block regardless if the command started in insert mode.

**Comment by vdawg-git** [comment]
`set fish_vi_force_cursor true` fixed it.
Weird, I am using Kitty and it worked for the longest time without it.

Should this be reported to Kitty?

**Comment by krobelus** [comment]
oh right, fish used to do user agent ($TERM) sniffing here.
That's gone in the next release.

**Comment by arthurazs** [comment]
> `set fish_vi_force_cursor true` fixed it.
>  Weird, I am using Kitty and it worked for the longest time without it.

Had the same issue on alacritty, this solved for me as well.

```bash
fish, version 3.7.0
alacritty 0.13.2
Description: Ubuntu 24.04.1 LTS
```
