### ISSUE TITLE
fish_clipboard_paste does not paste on Termux

### ISSUE THREAD

**Issue by minnesjay** [fish-shell/fish-shell#10807]
When using CTRL + V to paste text in Fish shell on Termux nothing is pasted.

However, the fish_clipboard_copy function works as expected, CTRL + X copies text.

**Fish Version: 3.7.1**
Termux (aarch64, Android)

No third-party customizations were used. The issue persists after running:
`sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= XDG_DATA_DIRS= fish'`

**Comment by krobelus** [comment]
you can try `bind \cv 'commandline -i -- (osc paste)'  using  https://github.com/theimpostor/osc

But OSC 52 is fraught with security issues; maybe better to use Termux' way of pasting text.

**Comment by minnesjay** [comment]
I made a termux equivalent based off of your osc bind, but it does not paste. bind \cv 'commandline -i -- (termux-clipboard-get)'. I'll try osc to see if it works, thanks!

**Comment by minnesjay** [comment]
I tried `bind \cv 'commandline -i -- (termux-clipboard-get)'` on another phone. It pastes, the issue was that on my first phone I had vi mode enabled.
