### ISSUE TITLE
funced should print warning when edited file was not modified

### ISSUE THREAD

**Issue by smidm** [fish-shell/fish-shell#1081]
My setup was: 
`$ set EDITOR gedit`

gedit without additional parameters goes into background and so funced exits before is the function edited. This results in empty edited function. Not modified file returned from an editor should cause a warning.

For gedit correct setup is
`$ set EDITOR gedit -w`

**Comment by krader1961** [comment]
Note that since `funced` is a fish function it would be trivial to enhance it to compare the original and updated version. Either by doing a literal byte-for-byte comparison or calculating and comparing a checksum before and after the file is edited.

**Comment by floam** [comment]
Was this fixed? I don't see a commit here.
