### ISSUE TITLE
Interactive menu for `cdh`

### ISSUE THREAD

**Issue by septatrix** [fish-shell/fish-shell#10814]
Fish version: 3.7.0

While setting up fish on a newish machine I found out about `cdh` which seems a lot more convenient than pushd/popd. However, it seems to be missing the convenient interactive menu (using tab or arrow keys, searching) as used by history search or autocompletion I have become accustomed to from fish.
It would be great if the function could be extended to utilize the same menu logic

**Comment by faho** [comment]
cdh's completions will already only list the possible candidates.

Anything more would require #2805, closing until that's fixed.
