### ISSUE TITLE
Allow theme files to set other variables?

### ISSUE THREAD

**Issue by lumynou5** [fish-shell/fish-shell#10819]
The idea is to allow theme files to set also other variables instead of only Fish native color (look-like) variables, so users can use theme files to keep their configuration of custom prompts.

Currently, only variables with a name starting with `fish_color` or `fish_pager_color` can be used:

https://github.com/fish-shell/fish-shell/blob/3e3aa08c288ba28feba61518060a8e3a14a37514/share/functions/fish_config.fish#L51

The downside is that "any" means a theme file may contain irrelevant variables. A possible solution is to limit variable names to something containing `color`, `icon`, etc.

**Comment by mattmc3** [comment]
What would be the benefit of this over saving a mytheme.fish file in conf.d that sets whatever variable you want? You could even easily convert a theme file to that with something like:

```
cat mytheme.theme | string match -re '^fish_.+\s' | string replace -r '\s(.+)$' ' (set_color $1)' | string replace -r '^' 'set -gx '
```

**Comment by lumynou5** [comment]
Since Fish has the theme file feature built-in, I think we can utilize it more.

It's also more convenient to use, for example, I would be able to use other's theme files, keep them all in my `~/.config/fish/themes/`, and just switches to whichever I want with `fish_config theme`. If I use a script in `conf.d` to set variables, I won't be able to store multiple themes there; if I use a function to set universal variables, though the effect is similar, it'll result many functions without a unified interface like `fish_config theme`.

**Comment by zanchey** [comment]
I don't think we'd add this. The benefit of restricting the current set of variables is that there's no state management that needs to be done. If you load a theme that overwrites an existing variable, should all the variables from the last theme be unloaded? Should they be erased or set to the value they were beforehand? How does that interact with scoping/exporting? The benefit of sticking to just the colour variables is that it's pretty hard to break the shell with mixtures of them.

You could always put your extra settings in `fish_color_my_variable`, there's no allowlist of variables. If it breaks, you can keep all the pieces.

**Comment by faho** [comment]
I agree with that.

We use the filter not just to read but also to *write* via `fish_config theme dump`, and we can easily reset the color variables just by setting them to empty.

That wouldn't work as well for other variables - e.g. if we added the git prompt variables here we would also have to store their default state, or tell `fish_config` how to reset the git prompt.

So I'll be closing this.
