### ISSUE TITLE
For commercial use

### ISSUE THREAD

**Issue by wanglunhui2012** [fish-shell/fish-shell#10816]
Can this be used for commercial use?

**Comment by faho** [comment]
Fish is free and open source software, licensed under the GNU General Public License, version 2, which allows commercial use.

You will have to follow that license, which means you will need to allow others to modify your version as well, which may include the need to give them the source code under the same terms.

See https://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html for more
