### ISSUE TITLE
forward-token doesn't match existing behavior for default completions

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#10839]
The default behavior for all fish right-movement commands is to continue realizing "ghost completion" tokens, with the exception of the newly added `forward-char-passive`.

The newly added `forward-token` replaces the existing binding for `alt-right` and introduces some changes, but I don't see any discussion of the change to this default behavior in #10738 (where this movement command (and other operators) was introduced).

While changes to *how much* gets consumed by one right/left movement with alt/ctrl are fine if it makes the modifiers more approachable and easier to understand, I think that as much of the existing behavior should be kept where possible. The fact that I don't see a discussion about this part of the breaking change (unless I missed it, in which case, my apologies!) leads me to believe this should be as easily and un-contentiously remedied by just adding the couple of lines of code to `src/reader.rs` to also consume from the active completion if already at the end of input.

(Now for the anecdotal bit: with a sample size of just one, I've been really annoyed by this part of change that completely breaks how I use fish and I imagine there will be others.)

**Comment by krobelus** [comment]
[yeah](https://github.com/fish-shell/fish-shell/pull/10738#issuecomment-2465781293) that was an accident. I can fix it one of these days
