### ISSUE TITLE
Using completions from the Homebrew prefix when running from `master`

### ISSUE THREAD

**Issue by lgarron** [fish-shell/fish-shell#10835]
`fish` version: fish, version 3.7.1-2357-ge3ecfa729-dirty

I've been running `fish` from `master` for a few weeks to get some new features, and it's almost seamless except for one thing: completions installed by Homebrew are not picked up by `fish`. My understanding is that I need to get `fish` to pick up the `fish` files in the Homebrew prefix at either compile-time or runtime, but I have not been able to get this to work. Am I missing something simple that can fix this? I'd appreciate any pointers or info on how to contribute an easy way to do this!

(Even nicer would be if https://github.com/fish-shell/homebrew-fish was updated so that `brew install --HEAD fish-shell/fish/fish-master` automatically does this.)

**Comment by krobelus** [comment]
On Tue, Nov 05, 2024 at 04:40:45PM -0800, Lucas Garron wrote:
> `fish` version: fish, version 3.7.1-2357-ge3ecfa729-dirty
> 
> I've been running `fish` from `master` for a few weeks to get
> some new features, and it's almost seamless except for one thing:
> completions installed by Homebrew are not picked up by `fish`.

Which completions, the ones shipped with fish or 3rd party packages?
Either way this should work; it's either a configuration issue
or packaging bug.

	printf %s\n $fish_complete_path

should show both 

	/Users/johannes/.config/fish/completions
	/opt/homebrew/etc/fish/completions
	/Users/johannes/.local/share/fish/vendor_completions.d
	/opt/homebrew/Cellar/fish/HEAD-8c62f73/share/fish/vendor_completions.d
	/opt/homebrew/share/fish/vendor_completions.d
	/opt/homebrew/Cellar/fish/HEAD-8c62f73/share/fish/completions
	/Users/johannes/.cache/fish/generated_completions

completions shipped with fish are in `$__fish_data_dir/completions`
and 3rd party completions installed by homebrew go
into /opt/homebrew/share/fish/vendor_completions.d
if the 3rd party package is configured correctly.

(It seems that adding vendor_completions was a big mistake, hopefully we can undo that)

> My understanding is that I need to get `fish` to pick up the `fish`
> files in the Homebrew prefix at either compile-time or runtime, but
> I have not been able to get this to work. Am I missing something
> simple that can fix this? I'd appreciate any pointers or info on
> how to contribute an easy way to do this!

**Comment by zanchey** [comment]
> (It seems that adding vendor_completions was a big mistake, hopefully we can undo that)

Is there a better solution? #1485 and #2113 give some of the background.

**Comment by lgarron** [comment]
> `brew install --HEAD fish` should do what you want.

Aha, I had looked at the formula but totally missed that! 🤦

Thanks, that is definitely the best way to fix everything.

Might be worth mentioning that in https://github.com/fish-shell/fish-shell?tab=readme-ov-file#getting-fish the repo README, but things are now clear for me, thx!
