### ISSUE TITLE
Multiple commas in row behave strangely in brace expansion

### ISSUE THREAD

**Issue by xfix** [fish-shell/fish-shell#1083]
```
glitchmr@tomato ~> echo foo{,,,,,,,,,,}
foo foo, foo, foo, foo, foo,
```

Example taken from http://www.catonmat.net/blog/bash-one-liners-explained-part-two/. This is crazy code, but definitely shouldn't behave like this.

**Comment by faho** [comment]
This is basically the same thing as #3002. Closing this because there's more discussion there.
