### ISSUE TITLE
on-variable PWD doesn't fire on shell startup

### ISSUE THREAD

**Issue by cap10morgan** [fish-shell/fish-shell#10843]
fish version: 3.7.1
OS: macOS 15.1

This may very well be expected behavior, but I was somewhat surprised to see that the PWD on-variable event doesn't fire on shell startup for the initial directory. I'm using iTerm and have it configured to open tab splits in the same dir, but my on-variable PWD functions don't fire then. I have to e.g. `cd .` to get them to run.

Would it make sense to fire the PWD variable event on startup? Or is there another event I have this function trigger on in addition to PWD?

**Comment by faho** [comment]
> Would it make sense to fire the PWD variable event on startup? 

When on startup? The variable isn't really ever *set* on startup (it's computed when you read it), it's just a property that fish inherits.

This would also just fire every single time you start a shell, and that might not be expected for variable handlers. It's also a bit of a conceptual mess.

To be honest, I would just tell you to run anything you want to run at startup at startup. Just when you define the handlers run them.

**Comment by cap10morgan** [comment]
OK, that makes sense. Just running the function in question right below where it's defined in my `conf.d` snippet seems to work well. Thanks @faho!
