### ISSUE TITLE
bind --erase does not remove fish builtin binds

### ISSUE THREAD

**Issue by mf-fx** [fish-shell/fish-shell#10846]
Fish version: fish, version 3.7.0
OS: Linux (Fedora)
Terminal: Kitty

---

I run this command:
```
bind --erase \cv
```

...and yet Ctrl-v still pastes.

**Comment by faho** [comment]
`bind --erase` will only erase *your* keybindings, it won't touch preset ones.

You *could* run `bind --erase --preset \cv`, but because keybindings are set very late in startup that usually won't do what you want.

Run `bind \cv true` to just bind the key to nothing.

**Comment by mf-fx** [comment]
Good answer - thanks!
