### ISSUE TITLE
Customize fish config location 

### ISSUE THREAD

**Issue by Yohe-Am** [fish-shell/fish-shell#10852]
A continuation of #3030, I believe I have a usecase that could really use a variable such as `$FISH_CONFIG_HOME`. 

Today, fish relies on `$XDG_CONFIG_HOME` to locate it's configuration and this works well for day to day use. But then I find myself writing a program that needs to work tightly with shell implementations. And I need to write tests and dev environments that enable specific shell hooks in an isolated manner. I.e. I need to launch an interactive shell with custom fish configuration. 

Setting the `XDG_CONFIG_HOME` here is a poor fit because that breaks every other program that relies on `XDG_CONFIG_HOME`. Launching `nvim` in such a shell will use the default config for example. In bash, I need only set `--rcfile` or `BASH_ENV`.

Adding support for a flag/variable like `$FISH_CONFIG_HOME` would work great here. Yes, I could probably hack together something that pipes `set XDG_CONFIG_HOME` to stdin and what not but this is the fourth time a web search has led me #3030 over the past year and maybe it deserves another examination.

Alternatively, maybe a way to load other scripts at startup along with the default config might help.

**Comment by faho** [comment]
> Alternatively, maybe a way to load other scripts at startup along with the default config might help.

You can both use conf.d files in tbh way too many locations (https://fishshell.com/docs/current/language.html#configuration-files), or you can use `fish --init-command` to run whatever you want, including `source` files.

**Comment by Yohe-Am** [comment]
Thanks for the quick reply, `--init-command` seems to be a great fit for the usecase I'm currently working on.

But, here me out, is there a way to have fish completely ignore the user's configuration files without touching the `XDG` vars? For a concrete use-case, I expect to contributors to have a production installation of the tool in their home fish configuration. `--init-command` would allow me to add the config from the development environment (and hopefully replace all symbols) but the production installation would still be loaded possibly causing problems?

**Comment by faho** [comment]
> But, here me out, is there a way to have fish completely ignore the user's configuration files without touching the XDG vars?

`fish --no-config`

**Comment by Yohe-Am** [comment]
Excellent, did not think of that. Thanks.
