### ISSUE TITLE
Importing bash completion

### ISSUE THREAD

**Issue by amidukr** [fish-shell/fish-shell#10856]
Lack of ability to import bash completion into fish is good reason to use zsh + omz than fish.

**Comment by faho** [comment]
We have over 1000 hand-written completions as well as a tool that writes completions from manpages.

Bash completions also lack descriptions.

So that's a no, there's no need for it. Sorry.

**Comment by leonmax** [comment]
> We have over 1000 hand-written completions as well as a tool that writes completions from manpages.
> 
> Bash completions also lack numerous features like descriptions and are written as full script, not in a declarative manner. That makes it basically impossible to import them without writing half of bash.
> 
> So that's a no, there's no need for it, it doesn't help much and it's a lot of work to do. Sorry.

you could write a wrapper to extract completion from bash. I've seen a gist [rconjoe](https://gist.github.com/rconjoe)/[fish-shell-bash-complete-function.sh](https://gist.github.com/rconjoe/92cd320c9aea83f632fb0046629f6194) doing this, unfortunately it's not working for me.

Please don't just close it, there are so many cli tools that only provide bash completion. It's a fact that although fish is great, people are intimidated by it's incompatibility.
