### ISSUE TITLE
tell conemu CD

### ISSUE THREAD

**Issue by wolfand11** [fish-shell/fish-shell#10850]
I change msys2 bash shell to fish shell. and I use conemu.
I change current dir to ~/App/my-test. when I duplicate the tab, the fish shell PWD is HOME. I need it is ~/App/my-test.

I check conemu documents, and I find solusion for cmd, powershell, and msys2.

the context in next link is work for powershell and msys2，but what should i do for fish shell?
https://conemu.github.io/en/ShellWorkDir.html

- https://github.com/Maximus5/ConEmu/issues/1405

**Comment by faho** [comment]
The thing they recommend for bash is:

```bash
if [[ -n "${ConEmuPID}" ]]; then
  PROMPT_COMMAND='ConEmuC -StoreCWD'
fi
```

which calls `ConEmuC -StoreCWD` in your prompt.

That's a bit wasteful, you only really need to do it when the pwd changes. So you could do:

```fish
if test -n "$ConEmuPID"
    function report_conemu_pwd --on-variable PWD
        ConEmuC -StoreCWD
    end
end
```

in your config.fish.

Note that fish on msys/cygwin is very likely to be unsupported with the next release. These platforms still don't have a working rust compiler.

I suggest you look into using WSL instead.

**Comment by wolfand11** [comment]
It's work!  thank you very much!
