### ISSUE TITLE
Fish shell adds new lines on tmux split panel resize

### ISSUE THREAD

**Issue by Rameshv** [fish-shell/fish-shell#1086]
Fish shell adds new line whenever i try to resize my tmux split panels. Its only happening in fish. I tried with bash & zsh both are working fine. I believe this is due to some key binding conflict between tmux and fish. But cant able to figure out what?

I am using this key combo for resizing in tmux (ctrl A + arrows)

Attached the screenshots for the reference

With bash

<a href="http://imgur.com/Avumu4z"><img src="http://i.imgur.com/Avumu4z.png" title="Hosted by imgur.com" /></a>

with fish

<a href="http://imgur.com/UhXYEUa"><img src="http://i.imgur.com/UhXYEUa.png" title="Hosted by imgur.com"/></a>

**Comment by kaelumania** [comment]
I am experiencing the same issue

**Comment by c02y** [comment]
It's fine here.
![snapshot1](https://user-images.githubusercontent.com/2135996/28555752-8449d7d0-7134-11e7-84f8-67cd5cd967b5.png)

**Comment by kevindashgit** [comment]
+1

**Comment by haodong** [comment]
@faho Thank you for referencing. But are you going to fix this?

**Comment by faho** [comment]
I can no longer reproduce this and there have been a toooon of changes in this space, so I'm closing this.
