### ISSUE TITLE
There is no tarball for version 3.7.1

### ISSUE THREAD

**Issue by wieczorek1990** [fish-shell/fish-shell#10868]
On the [site](https://fishshell.com) there are release notes and for version 3.7.1 the tarball is missing.

**Comment by faho** [comment]
The link to the tarball for the current version is above in the "Go fish" section with the rest of the downloads.

The direct link is https://github.com/fish-shell/fish-shell/releases/download/3.7.1/fish-3.7.1.tar.xz

In future, please direct any bug reports for the website to the [fish-shell/fish-site](https://github.com/fish-shell/fish-site) repo.

**Comment by wieczorek1990** [comment]
Thanks for reply.

I find that part of the site incoherent.

pon., 25 lis 2024 o 12:13 Fabian Boehm ***@***.***>
napisał(a):

**Comment by faho** [comment]
I've added the link. It turns out we explicitly skipped it and I don't think that's helpful.

**Comment by wieczorek1990** [comment]
Thanks!

W dniu pon., 25 lis 2024 o 16:44 Fabian Boehm ***@***.***>
napisał(a):
