### ISSUE TITLE
[Feature Request] Allow history without pager

### ISSUE THREAD

**Issue by Justinzobel** [fish-shell/fish-shell#10862]
fish 3.7.1

Allow the history command to be run without a pager (less).

**Comment by zanchey** [comment]
`history | cat`?

**Comment by zanchey** [comment]
or `PAGER=cat history` I guess.

**Comment by Justinzobel** [comment]
Sure, they work. But they are workarounds to the problem.

**Comment by mqudsi** [comment]
`alias history "history | cat"`

**Comment by faho** [comment]
> alias history "history | cat"

(that will break numerous `history` options because we ship a history function - fish has no aliases, `alias` creates functions, this would override the function)

(yes it would be cool to move more into the builtin (same for cd))

**Comment by faho** [comment]
Okay, I'm going to close this. There's a solution available - `history | cat`, which isn't any worse to call than a `history --no-pager` would be (we definitely want a pager by default).

And we have not gotten an answer on the motivation.
