### ISSUE TITLE
Removed builtin functions are still colored as valid and autocompleted

### ISSUE THREAD

**Issue by adriankwiat** [fish-shell/fish-shell#10866]
After removing built-in functions (for example `la`, `fish_greeting` etc.), they are still colored as valid commands (not red) and are shown in completions list. When I define my own function and remove it, this problem doesn't occur.

![image](https://github.com/user-attachments/assets/3cdb35d5-6302-4a69-b03d-276d16861dd4)

![image](https://github.com/user-attachments/assets/08817b21-03da-4c72-a801-28916a772781)

**Comment by zanchey** [comment]
Reproduces all the way back to 3.0!

**Comment by lavafroth** [comment]
I've been looking into this and it appears to only affect autoloaded functions. Steps to reproduce:
- Create a function in `.config/fish/functions/`
- Reload or enter a new session for the function to be autoloaded
- Erase the function
