### ISSUE TITLE
New notifier code causes freezes on exit

### ISSUE THREAD

**Issue by krobelus** [fish-shell/fish-shell#10878]
I've repeatedly gotten into the scenario where fish freezes on exit; it seems to hang forever. It's in the uninterruptible sleep state,
so attaching a debugger won't work either. When it happens, it reproduces consistently until
I reboot.

Bisects[^1] to 9b54e243b (Add FFI bindings to universal notifiers and adopt in input_common,
2023-11-26).
Commit a950a8270 (Create an inotify based universal notifier for Linux, 2023-11-25) seems like the most likely cause.

I'll probably debug this later.Last log lines are

    $ build/fish -d '*' -o log
    ...
    proc-job-run: Run job -1 (fish_title), COMPLETED, NON-INTERACTIVE
    fd-monitor: Removing fd -1
    reader-render: repaint needed because forced change
    reader-render: Repainting from toplevel
    screen: Repaint 1
    fd-monitor: Thread exiting
    iothread: pthread  ThreadId(3)  exiting
    event: Firing event ' fish_exit ' to handler ' __fish_disable_bracketed_paste '
    ast-construction: %*smake %ls %p 0  job_list 0x5da13c99b3e0
    ast-construction: %*swill_visit %ls %p 0  job_conjunction
    ast-construction: %*swill_visit %ls %p 2  job_pipeline
    ast-construction: %*s%ls size: %lu 4  variable_assignment_list 0
    ast-construction: %*swill_visit %ls %p 4  statement
    ast-construction: %*swill_visit %ls %p 6  decorated_statement
    ast-construction: %*s%ls size: %lu 8  argument_or_redirection_list 0
    ast-construction: %*s%ls size: %lu 4  job_continuation_list 0
    ast-construction: %*s%ls size: %lu 2  job_conjunction_continuation_list 0
    ast-construction: %*s%ls size: %lu 0  job_list 1
    exec-job-status: Set status of job -1 (printf...) to 0 using short circuit
    exec-job-exec: Executed job -1 from command 'printf "\e[?2004l"'
    proc-job-run: Run job -1 (printf "\e[?2004l"), COMPLETED, NON-INTERACTIVE
    exec-job-status: Set status of job -1 (__fish_disable_bracketed_paste...) to 0 using short circuit
    exec-job-exec: Executed job -1 from command '__fish_disable_bracketed_paste'
    proc-job-run: Run job -1 (__fish_disable_bracketed_paste), COMPLETED, NON-INTERACTIVE

[^1]: Bisecting can be really tricky due to various version incompatibilties. I succeeded with
      cmake 19 and rustc 1.78, I believe those should be able to build every commit so far.

**Comment by krobelus** [comment]
It hangs in `libc::close(self.fd);` on the inotify fd (uvar file)

**Comment by krobelus** [comment]
I don't see any background thread using the fd

```
inotify_init1(IN_CLOEXEC)               = 3
fcntl(3, F_DUPFD_CLOEXEC, 99)           = 99
inotify_add_watch(99, "/home/johannes/.config/fish", IN_MODIFY|IN_MOVED_TO) = 1
poll([{fd=0, events=POLLIN}, {fd=5, events=POLLIN}, {fd=99, events=POLLIN}], 3, -1) = 1 ([{fd=0, revents=POLLIN}])
poll([{fd=0, events=POLLIN}, {fd=5, events=POLLIN}, {fd=99, events=POLLIN}], 3, 0) = 1 ([{fd=0, revents=POLLIN}])
poll([{fd=0, events=POLLIN}, {fd=5, events=POLLIN}, {fd=99, events=POLLIN}], 3, 0) = 1 ([{fd=0, revents=POLLIN}])
poll([{fd=0, events=POLLIN}, {fd=5, events=POLLIN}, {fd=99, events=POLLIN}], 3, 0) = 1 ([{fd=0, revents=POLLIN}])
poll([{fd=0, events=POLLIN}, {fd=5, events=POLLIN}, {fd=99, events=POLLIN}], 3, 0) = 1 ([{fd=0, revents=POLLIN}])
poll([{fd=0, events=POLLIN}, {fd=5, events=POLLIN}, {fd=99, events=POLLIN}], 3, 0) = 1 ([{fd=0, revents=POLLIN}])
poll([{fd=0, events=POLLIN}, {fd=5, events=POLLIN}, {fd=99, events=POLLIN}], 3, 0) = 1 ([{fd=0, revents=POLLIN}])
poll([{fd=0, events=POLLIN}, {fd=5, events=POLLIN}, {fd=99, events=POLLIN}], 3, 0) = 1 ([{fd=0, revents=POLLIN}])
inotify_rm_watch(99, 1)                 = 0
close(99
```

**Comment by faho** [comment]
I've not seen this, the fd number of 99 seems suspiciously like it's some limit somewhere.

As a general thing: Is it useful to close this (or any other FDs) on exit, or could we just leak it and let it be closed by virtue of the process disappearing?

**Comment by krobelus** [comment]
it's fine to leak fds yeah.
I suspect this should be easy to reduce because other processes start hanging too, I'll try that next time

**Comment by ridiculousfish** [comment]
I'm pretty confused why we are trying to close this fd at all - we create a single instance in DEFAULT_NOTIFIER and never destroy it, so I never expect it to be closed. Also where is that `fcntl(3, F_DUPFD_CLOEXEC, 99)` coming from? Super weird.

**Comment by krobelus** [comment]
that's an unrelated fix (to call `heightenize_fd`). I had picked 99 for debugging, which is also the reason for closing in user code

**Comment by ridiculousfish** [comment]
Can you figure out why it's being closed? Who is closing this fd?

**Comment by krobelus** [comment]
I closed it to see where it's hanging.
This issue is likely unrelated to fish, I'll see when I hit it again.

**Comment by zanchey** [comment]
It doesn't sound like we need to hold the beta for this

**Comment by zanchey** [comment]
wild
