### ISSUE TITLE
History token navigation doesn't work

### ISSUE THREAD

**Issue by dhasenan** [fish-shell/fish-shell#109]
I should be able to use Alt+Up and Alt+Down to search through tokens in my history; eg

ls /foo
cd /[Alt+Up] <-- completes to /foo

Instead, Alt+Up appears to do nothing. This is using fish 1.23.1 under gnome-terminal 3.4.1.1 and xterm.

Without these, I am sorely missing !$.

**Comment by faho** [comment]
Can anyone still reproduce this?

**Comment by ridiculousfish** [comment]
This works for me in iTerm2. Let's close.
