### ISSUE TITLE
Key repeat to invoke `backward-kill-word` does not seem to work

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#10908]
Using https://github.com/fish-shell/fish-shell/commit/0275c5e803f72600816ae81d8c590cf79c93e10f and iTerm v3.5.10

---

Apologies for the vague bug report. I'm not even sure if the title is correct, but hopefully we can help each other get to the bottom of what is going on here. I would say I noticed this issue around 2-3 weeks or so ago, but I can't be sure.

I have a keybind:

```
bind alt-backspace backward-kill-word
```

There seems to be an issue with tapping the `backspace` key vs. holding it down.

It works if I hit my `alt-backspace` keybind repeatedly (i.e. hold `alt` and then tap `backspace` repeatedly), but it does not work if I _hold down_ `backspace` after pressing `alt`. It's almost as if the keybind is only firing for the key-up event, but not automatically re-firing while key-down is held.

I also have this keybind, which seems to work just fine (i.e. I can press `ctrl` and then hold `w` and it'll repeatedly delete words):

```
bind ctrl-w backward-kill-bigword
```

I'm not sure if this is an issue with fish or iTerm. If there is any further information I can provide to help us get to the bottom of this, please let me know!

**Comment by krobelus** [comment]
looks like a regression in iterm 3.5.9, reported as https://gitlab.com/gnachman/iterm2/-/issues/12069
