### ISSUE TITLE
Completions are rewriting arguments altogether

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#10904]
*I think this regression was probably introduced with the commit that tried to make it easier to append to completions (e.g. multiple comma-separated arguments)*

```
> function foo; end
> complete -c foo -s s -l long -xa "hello-world goodbye-friend"
> complete -C"foo -s frien"
goodbye-friend # ok
> complete -C"foo -shell"
-shello-world # good
> complete -C"foo -sfrie"
goodbye-friend # bad
> complete -C"foo --long hel"
hello-world # ok
> complete -C"foo --long fr"
goodbye-friend # ok
> complete -C"foo --long=hell"
--long=hello-world # good
> complete -C"foo --long=frien"
goodbye-friend # bad
```

**Comment by zanchey** [comment]
This was not present in 3.0.2, but present in 3.7.1.

**Comment by krobelus** [comment]
I see, I couldn't easily build 3.4.0 due to compiler errors (good thing we have a pinned compiler version now that's easily downloadable).
I'm only mildly nervous that I don't know which commit introduced it

**Comment by zanchey** [comment]
First appears in 3.1.0, due to ecfe4acd0c224c

**Comment by krobelus** [comment]
On Wed, Dec 18, 2024 at 07:51:48AM -0800, David Adam wrote:
> First appears in 3.1.0, due to ecfe4acd0c224c

I see so completing `foo -sfrie` did nothing before that commit, that makes sense
