### ISSUE TITLE
Local exported (`set -lx`) variables are not exported to functions

### ISSUE THREAD

**Issue by xdudi** [fish-shell/fish-shell#1091]
begin set -lx VERBOSE 1; make; end #it works
begin set -lx VERBOSE 1; nice make; end #it works too
but:
function my_nice #made from bash alias
        nice -n 20 $argv; 
end
begin set -lx VERBOSE 1; my_nice make; end #it doesn't work

**Comment by faho** [comment]
> I wonder if we should adjust the behavior of local exports in some way.

@ridiculousfish: I've had some time to think about this, and I believe the cleanest thing to do would be to make a local copy of -lx variables.

So it would work like this:

- If a variable is global or universal, all functions have access to it
- If a variable is not global or universal but exported, the functions get a function-local copy of it defined (as if "-V $variable" had been called)

The latter is basically what happens for external commands - if we export a variable, they get a copy of it. If they modify it, we don't see it.

**Comment by ridiculousfish** [comment]
Yep, makes sense @faho

**Comment by krader1961** [comment]
Merged into the major branch for inclusion in our fish 3.0 release.
