### ISSUE TITLE
fish should not exit over invalid command exit status

### ISSUE THREAD

**Issue by Darkshadow2** [fish-shell/fish-shell#10919]
fish, version 4.0b1-11-g039011bc8

While troubleshooting a problem, I got this error and fish exited:

```
thread 'main' panicked at src/proc.rs:181:9:
trying to create proc_status_t from failed waitid()/waitpid() call or invalid builtin exit code!
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fish crashed, please report a bug. Debug PID 95883 or press Enter to exit
```

Looking at the code there, I can see fish asserts if the exit value is below 0 or above 255. I can reproduce this with this simple code:

```C
int main(void)
{
    return -1;
}
```

I know the convention is for exit values to be 0 to 255, but it's not a hard requirement. Executables can return anything from INT_MIN to INT_MAX.

The real world way I ran into this was with `php-fpm`. It wouldn't launch, so I tried to launch it directly in fish, and got this error. The fault with `php-fpm` was an error in the config file (a misspelled path for opcache lock file), and I think it's returning -2. I'm not going to delve into php's code to see for sure, but `bash` reported the error status for `php-fpm` as 254 and reports the error status of the above simple code as 255 so my guess is -2.

I _really_ don't expect my shell to exit because of the exit status of a command I ran.

**Comment by krobelus** [comment]
what's `EXIT_FAILURE` on your platform?

**Comment by krobelus** [comment]
maybe

```diff
diff --git a/main.c b/main.c
new file mode 100644
index 0000000000..32d9e88f86
--- /dev/null
+++ b/main.c
@@ -1,0 +1,2 @@
+#include <stdlib.h>
+int main() { return -1; }
diff --git a/src/proc.rs b/src/proc.rs
index cc8012183a..d2dc95411c 100644
--- a/src/proc.rs
+++ b/src/proc.rs
@@ -233,14 +233,14 @@
     }
 
     /// Return the exit code, given that we normal exited.
-    pub fn exit_code(&self) -> libc::c_int {
+    pub fn exit_code(&self) -> u8 {
         assert!(self.normal_exited(), "Process is not normal exited");
-        WEXITSTATUS(self.status())
+        u8::try_from(WEXITSTATUS(self.status()) & 0xff).unwrap()
     }
 
     /// Return if this status represents success.
     pub fn is_success(&self) -> bool {
-        self.normal_exited() && self.exit_code() == EXIT_SUCCESS
+        self.normal_exited() && self.exit_code() == u8::try_from(EXIT_SUCCESS).unwrap()
     }
 
     /// Return the value appropriate to populate $status.
@@ -248,7 +248,7 @@
         if self.signal_exited() {
             128 + self.signal_code()
         } else if self.normal_exited() {
-            self.exit_code()
+            i32::from(self.exit_code())
         } else {
             panic!("Process is not exited")
         }
```

**Comment by Darkshadow2** [comment]
EXIT_FAILURE is defined as 1. Also, apologies, I completely missed posting the system. It's OpenBSD 7.5

The patch does work, fish reports an exit status of 255 with it 👍
