### ISSUE TITLE
Cursor movement behaviour change in master

### ISSUE THREAD

**Issue by nrjais** [fish-shell/fish-shell#10910]
OS: Mac
Term: Alacritty
Fish version: master commit

Seems like word movement behaviour has change in master

Old version: The cursor would move through all path component
New vesion: The cursor moves across the whole path
```bash
ls /some/path/nested
```

Old version: The cursor would move through all words inside quotes
New vesion: The cursor moves across the whole quoted string
```bash
echo "some multi word tex"
```

**Comment by nrjais** [comment]
Why do you say it does not work in mac, the old version is still working.
Did the rewrite change anything?

**Comment by nrjais** [comment]
Ohk, I have workspace switching disabled.
`ctrl-left` does not work for me because it is bound to tmux tab switching
`alt-b` produces some characters instead of moving so that also is not working

**Comment by nrjais** [comment]
Thanks, created custom bindings for old behaviour

**Comment by krobelus** [comment]
> alt-b produces some characters instead of moving so that also is not working

yeah that's the default on macOS (well, on [most terminals](https://x.com/mitchellh/status/1866916923784749553/photo/1)
You can set the option "Option sends Escape" (or "Option sends Meta"?) in your terminal to be able to use `alt-b`, `alt-d` etc.

FWIW there are also `shift-left` and `shift-right`; maybe this macOS specific problem is enough motivation to change those to behave like `alt-b` and `alt-f`

> Thanks, created custom bindings for old behaviour

it's probably not ideal that macos users who don't know about the option-is-alt trick are robbed of theh fine-grained key binding.
But I can't think of a good solution, and there has been push-back to making this platform-dependent; so I'm kind of waiting until someone proposes something better
