### ISSUE TITLE
Limit size of undo history?

### ISSUE THREAD

**Issue by simonborje** [fish-shell/fish-shell#10918]
Hi, I'm not sure if this is an actual issue or not but I saw in the changelog for fish 4.0b1 that the undo history is no longer truncated after new commands. As far as I can tell the undo history is never cleared and can continue to grow unbounded. Do you think it would be worthwhile to add some kind of limit to the undo history? If you think so I could submit a PR.

**Comment by faho** [comment]
It's not persisted, so it will be cleared when the session ends.

I don't think it's going to be an issue, so let's hold off until we see that it is.
