### ISSUE TITLE
OpenSuse Leap 15.6 can't install 4.0b1 from repo

### ISSUE THREAD

**Issue by KnowZero** [fish-shell/fish-shell#10920]
When I try to install fish 4.0b1 from the repo(`https://download.opensuse.org/repositories/shells:/fish:/beta:/4/15.6/`), it tells me that ncurses-base is missing. 

From my understanding that is for RH/Fedora and in opensuse it is terminfo-base?

**Comment by zanchey** [comment]
I've respun the packages in OBS - could you try again?

**Comment by KnowZero** [comment]
Thanks, it works now! :+1:
