### ISSUE TITLE
fish 4.0b1: "ctrl-c no longer cancels builtin read."

### ISSUE THREAD

**Issue by sersorrel** [fish-shell/fish-shell#10928]
In the fish 4.0b1 release notes, I saw the following point:

> - `ctrl-c` no longer cancels builtin `read`.

Is this an intentional change/am I interpreting this correctly? There's an issue from 2013 suggesting that `read` not exiting on ctrl-c was previously treated as a bug: #516

For what it's worth, this change would be breaking for me – I have several helper functions which do things like `read -P "press enter or hit ctrl-c..." && rm -r $various_things`, for example, so if there's no longer a way to get `read` to exit nonzero I'll have to rework them all.

**Comment by krobelus** [comment]
ok I'll try to fix that. This change definitely didn't have a strong motivation other than internal consistency. Thanks!
