### ISSUE TITLE
Missing end to balance this if statement

### ISSUE THREAD

**Issue by Gibbz** [fish-shell/fish-shell#10921]
fish  version 3.7.1

Error when using ssh-copy-id to the target system which uses a fish shell

```
ssh-copy-id user@host
/usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
/usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
user@host's password: 
fish: Missing end to balance this if statement
                if type restorecon >/dev/null 2>&1 ; then restorecon -F .ssh .ssh/authorized_keys ; fi
```

**Comment by faho** [comment]
That isn't a script that ships with fish, and it is not fish-compatible.

**Comment by Gibbz** [comment]
Thanks I'll switch back to bash

**Comment by krobelus** [comment]
On Wed, Dec 18, 2024 at 09:20:22PM -0800, Gibbz wrote:
> fish  version 3.7.1
> 
> Error when using ssh-copy-id to the target system which uses a fish shell
> 
> ```
> ssh-copy-id ***@***.***
> /usr/bin/ssh-copy-id: INFO: attempting to log in with the new key(s), to filter out any that are already installed
> /usr/bin/ssh-copy-id: INFO: 1 key(s) remain to be installed -- if you are prompted now it is to install the new keys
> ***@***.***'s password: 
> fish: Missing end to balance this if statement
>                 if type restorecon >/dev/null 2>&1 ; then restorecon -F .ssh .ssh/authorized_keys ; fi
> ```

This seems like a bug in `ssh-copy-id` that has been [fixed in 2016](http://anongit.mindrot.org/openssh.git/commit/?id=ef39e8c0497ff0564990a4f9e8b7338b3ba3507c).
This command should show the presence of the fix:

	grep 'to defend against quirky remote shells' $(which ssh-copy-id)

But yeah, fish should support that as it's causing needless friction
