### ISSUE TITLE
Don't include dust.fish for v4 deb package for Ubuntu 24.10+

### ISSUE THREAD

**Issue by hongquan** [fish-shell/fish-shell#10922]
I installed fish v4 from this [PPA](https://launchpad.net/~fish-shell/+archive/ubuntu/beta-4) for Ubuntu 14.10+

The installation failed because this package tries to install _dust.fish_ completion file, which is also included in [du-dust](https://packages.ubuntu.com/oracular/du-dust) package.

Because `du-dust` is an official package, I think `fish` shoud yield.

More info: 
Installing fish v4 for Ubuntu 24.04 is fine because `du-dust` in this release doesn't include _dust.fish_.

**Comment by faho** [comment]
Ideally, the du-dust package should install into vendor_completions.d.

share/fish/completions is our turf.

But we can remove the script entirely if dust ships its own - we'll have to check if they do or Ubuntu just pregenerates them.

**Comment by zanchey** [comment]
The Debian packaging is wrong here. I [filed a merge request to fix it](https://salsa.debian.org/rust-team/debcargo-conf/-/merge_requests/804) but I can't see a correction percolating through to Ubuntu any time in the near future. Let's remove our copy (sorry @leun4m).

**Comment by zanchey** [comment]
@hongquan you can fix this temporarily with `sudo dpkg-divert --package du-dust --divert /usr/share/fish/completions/dust.fish.upstream /usr/share/fish/completions/dust.fish`

**Comment by hongquan** [comment]
Thanks, @zanchey

**Comment by hongquan** [comment]
@zanchey Please also report for [just](https://packages.ubuntu.com/oracular/just) package, which also install fish completion to _/usr/share/fish/completions/_.
