### ISSUE TITLE
[v4.0.0-beta.1] Fish complains about file permissions if fish_variables is read-only

### ISSUE THREAD

**Issue by exit91** [fish-shell/fish-shell#10931]
Operating System: NixOS 24.11
uname -a: `Linux <hostname> 6.12.1 #1-NixOS SMP PREEMPT_DYNAMIC Fri Nov 22 14:30:26 UTC 2024 x86_64 GNU/Linux`
Fish Version: v4.0.0-beta.1

After executing any command fish complains thrice about being unable to access the `fish_variables` file.

```bash
$ sleep 1s
error: Unable to open universal variable file '/home/<user>/.config/fish/fish_variables': EACCES: Permission denied
error: Unable to open universal variable file '/home/<user>/.config/fish/fish_variables': EACCES: Permission denied
error: Unable to open universal variable file '/home/<user>/.config/fish/fish_variables': EACCES: Permission denied
```

It should be noted that the fish folder is managed by [home manager](https://github.com/nix-community/home-manager) and as such the file `fish_variables` is *owned by root and read-only*. However, previous versions of fish (e.g. `3.7.1`) were able to handle it just fine without complaint.

```bash
$ exa -la /home/<user>/.config/fish/fish_variables
-r--r--r-- 1 root root 3964  1. Jan 1970  /home/<user>/.config/fish/fish_variables
```

**Comment by exit91** [comment]
This doesn't seem to reproduce by just changing the permissions of `fish_variables` on a fresh config. Closing this issue for now.

**Comment by faho** [comment]
Okay, this message really used to have a category of "uvar_file", which is disabled by default, and was switched to error.

But that seems like a good change, given that this really is an error.

In particular, I'm not sure that home-manager actually makes the file root-owned and read-only? And if it really couldn't write to that file, universal variables would be broken.

**Comment by exit91** [comment]
To clarify, this issue doesn't arise from home-manager per se, but the specific way I use it -- people using the `programs.fish = {...}` configuration option should be fine. I do agree that an error message is appropriate if fish requires write access. Thanks for your swift response!
