### ISSUE TITLE
New default binding to kill-word in 4.0b1 does not work in gnome-terminal

### ISSUE THREAD

**Issue by anisse** [fish-shell/fish-shell#10936]
As mentioned in the [release notes](https://fishshell.com/docs/4.0b1/relnotes.html#notable-backwards-incompatible-changes), default bindings changed, but the new method used for kill-word [does not work in gnome-terminal](https://gitlab.gnome.org/GNOME/vte/-/issues/2601) (version 3.52 here).

It would be nice to mention this, because I read the release notes initially, but I did not understand the implications: which terminal emulators support the kitty keyboard protocol?

(I'm aware I can update my bindings, this issue is specifically about the new default, and documenting it for users).

**Comment by krobelus** [comment]
most terminals support most of our default keys but `ctrl-backspace` is an
exception; xterm doesn't assign it a good encoding by default
(I think there was a config option to make it unambiguous but I forgot which one).

This is on gnome-terminal:

```
$ fish_key_reader -c

To terminate this program type "exit" or "quit" in this window,
or press ctrl-c or ctrl-d twice in a row.

Press a key:
bind alt-backspace 'do something'
bind alt-delete 'do something'
bind ctrl-h 'do something' # I pressed ctrl-backspace
bind ctrl-delete 'do something'
```

Some terminals that support the kitty protocoil are listed [here](https://sw.kovidgoyal.net/kitty/keyboard-protocol/).

**Comment by krobelus** [comment]
FWIW, at least for backspace there is need to implement the kitty keyboard protocol.
It doesn't work by default in `gnome-terminal` due to the ambiguity with `ctrl-h`.
But you can configure gnome-temrinal to send backspace as 0x7F, then alt-backspace will work too.
In Preferences -> Compatibility:
![image](https://github.com/user-attachments/assets/e868e56e-4c3f-4235-bf5b-d1eb1852888a)

**Comment by anisse** [comment]
My point is that maybe the default shell for many distros should get a mention as "lagging behind" in this case, even if the information is available a link away.

Also, the default for `backward-kill-component`  Ctrl-W could supplement `backward-kill-word` in many cases, with no need for rebindings: maybe this could help some users, too?

**Comment by anisse** [comment]
>  But you can configure gnome-terminal to send backspace as 0x7F, then alt-backspace will work too.

Alt-backspace and backspace already work for me ,I tried fiddling with the option, and there was no change in behavior, does this need a restart of all terminal instances?

**Comment by krobelus** [comment]
ah nevermind it actually doesn't work. We should fix the terminal

**Comment by krobelus** [comment]
does this answer the questions? We could also try to mention "which terminals support which keys"

```diff
diff --git a/CHANGELOG.rst b/CHANGELOG.rst
index dc0a4ed7f1..381aa4b775 100644
--- a/CHANGELOG.rst
+++ b/CHANGELOG.rst
@@ -58 +58 @@ Notable backwards-incompatible changes
-- :kbd:`alt-backspace` will delete an entire argument, not just one word (which is :kbd:`ctrl-backspace` now).
+- :kbd:`alt-backspace` will delete an entire argument, not just one word. The old ``backward-kill-word`` behavior has been moved to :kbd:`ctrl-backspace`. In case your terminal doesn't support `ctrl-backspace`, consider using :kbd:`ctrl-w`, or :kbd:`alt-b` + :kbd:`alt-d`).
```

**Comment by anisse** [comment]
Yes, this would help. It would be nice to mention as well "which terminals support which keys" indeed to close this bug.

**Comment by anisse** [comment]
Thanks a lot!

**Comment by zanchey** [comment]
Cherry-picked as 566ff38fe
