### ISSUE TITLE
fish 4.0b1: vi-mode: gU doesn't capitalize the whole word

### ISSUE THREAD

**Issue by tesuji** [fish-shell/fish-shell#10952]
```console
> fish --version
4.0b1-4-g687001f8b
> uname -a
Linux machine 6.8.0-49-generic #49-Ubuntu SMP PREEMPT_DYNAMIC Mon Nov  4 02:06:24 UTC 2024 x86_64 GNU/Linux
> echo $TERM
xterm
```

> executing this command and whether it affected the behavior you are reporting:
    sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= XDG_DATA_DIRS= fish'

Yes, it still does.

**How to reproduce the problem**

Install the required fish version.
I download and install the [self-installing static artifact][1].

```
# Change to vi binding mode:
fish_vi_key_bindings
# type something
asdf[^ESC]
# press ESC to switch to normal mode
# go to the first column with `0`
# let's try to capitalize the whole word with gU
# and the result is
ASDf
# f is still a lowercase char
```

fish 3.7.1 behaves as expected, i.e. whole word is capitalized as ASDF.

cc #10633

[1]: https://github.com/fish-shell/fish-shell/releases/download/4.0b1/fish-static-linux-x86_64.tar.xz

**Comment by tesuji** [comment]
Digging a bit into the problem. The issue may arise from this hack: https://github.com/fish-shell/fish-shell/issues/10286#issuecomment-1943479747

**Comment by ridiculousfish** [comment]
I haven't been able to successfully reproduce this issue. Here's what I tried:

1. [Download and install the artifact](https://github.com/fish-shell/fish-shell/releases/download/4.0b1/fish-static-linux-x86_64.tar.xz) on Ubuntu Noble LTS Docker image
2. Run `fish_vi_key_bindings`
3. Type 'echo hello world' (do not press enter)
4. Type `<ESC>0gU`
5. Now the command line shows "ECHO hello world" as I expect

I didn't try with `xterm` exactly but any help reproducing would be appreciated.

**Comment by krobelus** [comment]
it only reproduces if `gU` hits the very end of the commandline

**Comment by ridiculousfish** [comment]
Ah got it, thanks! I will bisect.

**Comment by krobelus** [comment]
no need
