### ISSUE TITLE
Debug symbols not included in RelWithDebugInfo profile

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#10959]
I'm pretty sure this worked as of 2bc197fe74, but building with `-DCMAKE_RELEASE_TYPE=RelWithDebInfo` currently produces binaries without debugging symbols. This is annoying and will prevent downstream packages' automatic debug symbol packages from working. It would be good to fix this for 4.0.0.

**Comment by krobelus** [comment]
I had tried adding `debug = true` before but it didn't add line numbers to backtraces in my testing

**Comment by zanchey** [comment]
Too quick for me! Thanks. Neither adding `RUSTFLAGS=-g` or `cargo --config debug=true` worked for me.
