### ISSUE TITLE
fish 4.0b1: bind doesn't erase preset keybinds

### ISSUE THREAD

**Issue by aShabat** [fish-shell/fish-shell#10964]
I prefer to redefine all my keybinds with script like this

```
bind --erase --all

bind right forward-char
bind left backward-char
bind ctrl-right forward-word
bind ctrl-left backward-word
bind tab complete
bind ctrl-s pager-toggle-search
bind up up-or-search
bind down down-or-search
bind ctrl-l clear-screen
bind ctrl-c cancel-commandline
bind ctrl-w backward-kill-path-component
bind home end-of-line
bind end beginning-of-line
bind ctrl-S 'fish_commandline_prepend sudo'
bind ctrl-N edit_command_buffer
bind '' self-insert
bind ' ' self-insert expand-abbr
bind ';' self-insert expand-abbr
bind '|' self-insert expand-abbr
bind '&' self-insert expand-abbr
bind '>' self-insert expand-abbr
bind '<' self-insert expand-abbr
bind ')' self-insert expand-abbr
bind enter execute
bind ctrl-k kill-line
bind ctrl-a beginning-of-line
bind ctrl-e end-of-line
bind backspace backward-delete-char
bind ctrl-p up-or-search
bind ctrl-n down-or-search
bind ctrl-f forward-char
bind ctrl-b backward-char
bind ctrl-T transpose-words
bind ctrl-g cancel
bind ctrl-z undo
bind ctrl-u upcase-word
bind ctrl-C capitalize-word
bind ctrl-backspace backward-kill-word
bind ctrl-r fzf-history-widget
bind ctrl-t fzf-file-widget
bind ctrl-d fzf-cd-widget
bind enter _tide_enter_transient
bind \n _tide_enter_transient
```

I source it in my `config.fish`. Running `bind` shows that all the preset binds are still defined.

Also for some reason ctrl-backspace still works like regular backspace and keybinds ctrl-u and ctrl-C don't work.

**Comment by krobelus** [comment]
On Sun, Dec 29, 2024 at 03:39:48AM -0800, aShabat wrote:
> I prefer to redefine all my keybinds with script like this
> ```
> bind --erase --all
>
> I source it in my `config.fish`. Running `bind` shows that all the preset binds are still defined.

Use

	bind --erase --all --preset

> Also for some reason ctrl-backspace still works like regular backspace and keybinds ctrl-u and ctrl-C don't work.

Try "fish_key_reader -V". ctrl-backspace may not be supported by your terminal OOTB

**Comment by aShabat** [comment]
> Use
> 	`bind --erase --all --preset`
still shows preset bindings.

> Try "fish_key_reader -V". ctrl-backspace may not be supported by your terminal OOTB
Thank you, apparently ctrl-backspace and ctrl-C aren't supported. ctrl-u is registered fine but doesn't trigger upcase-word

**Comment by faho** [comment]
> still shows preset bindings.

Put your bindings into a function and set $fish_key_bindings to the name of your function (`set -g fish_key_bindings my_bindings`).

What happens is that fish sets up the bindings *after* it has run the configuration - because you could be switching to the vi-bindings there.

So you erase all the preset bindings, it starts and sets the default bindings again.

**Comment by aShabat** [comment]
> on Linux `ctrl-C` (AKA `ctrl-shift-c`) is intercepted by the terminal (it copies the selection to clipboard)

Right! I forgot about it. Thank you.
Also I just figured out that I didn't understand that for capitalize-word and upcase-word caret should be before the word(thought it works on the last one). So everything works.
