### ISSUE TITLE
Slow Midnight Commander start and broken subshell on Fish 4.0.0 beta

### ISSUE THREAD

**Issue by dividebysandwich** [fish-shell/fish-shell#10963]
Fish version 4.0.0-beta.1-g774b7c7b5
Arch linux btw 6.12.7-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 27 Dec 2024 14:24:37 +0000 x86_64 GNU/Linux

I seem to be experiencing the same issue as #7769 from way back when:

Midnight commander takes around 10 seconds to start, and the subshell is broken. 

fish was installed via cargo and I am just using ```exec fish``` at the end of .bashrc for now. Not sure if that is related but I thought I'd mention it.

**Comment by faho** [comment]
>  I am just using exec fish at the end of .bashrc for now. Not sure if that is related but I thought I'd mention it.

That does, in fact, appear to be the cause.

I think mc might be trying some things when it thinks the shell is "fish", and so if it's launching bash it doesn't do them.

In fact when you `cp /bin/bash ./fish` and then run `SHELL=$PWD/fish mc` it'll work even with the `exec fish`.

I'm going to call that an mc problem, I don't believe there is anything we can do there.

**Comment by krobelus** [comment]
yeah you'll want to run `SHELL=(which fish) mc` or similar
