### ISSUE TITLE
Incorrect completion for `sudo -g <group>`

### ISSUE THREAD

**Issue by patatahooligan** [fish-shell/fish-shell#10980]
# Versions

Reproduced on versions:
* 3.7.1 (latest stable)
* 4.0b1-99-g13763fa31 (current `master`)

Operating system: Arch linux

# The problem

Start typing a command with `sudo -g <group>` and press TAB. If the group happens to have the same name as an executable, fish will use the completion function for this executable. For example,

```bash
sudo -g docker <TAB>
```

will recommend the same completions as `docker <TAB>` would.

If the group name does not match a command for which completions are available, then fish will recommend files in the current directory.

# Expected behavior

The group name should be ignored for command completion. The completions for `sudo -g docker` should be the same as for `sudo`, ie executables.

**Comment by zanchey** [comment]
@faho I think this would be ok for 4.0?

**Comment by faho** [comment]
Sure, 5845a3f7ad42ff5a9342529e9b3b26e61b
