### ISSUE TITLE
Can we have a native windows port of fish-shell using uutils/coreutils ?

### ISSUE THREAD

**Issue by SerJaimeLannister** [fish-shell/fish-shell#10983]
I have come across an issue on fish-shell 
 https://github.com/fish-shell/fish-shell/issues/10956 

Since rust can't run on msys2 / cygwin etc. , the only option is wsl which can be too bulky and I think there can be a simpler approach to fish shell on windows ie. we can use coreutils 

https://github.com/uutils/coreutils/ this repository is written in rust and from what I can see , this can run on windows as well (says cross platform)

Nushell , an alternative to fish shell (which was written from start in rust) [nushell](https://github.com/nushell/nushell/) , also uses uutils/coreutils under the hood and also has native windows support.

Native windows support is definitely possible , 

some other idea is also either using https://github.com/rmyorston/busybox-w32/ or https://github.com/samuela/rustybox , (rustybox seems inactive and doesn't have windows port , but the project can be forked by the fish team and maybe fish team can add windows support)  

My suggestion is to use uutils/coreutils & I have opened this issue so that we can have further discussion and maybe reach some conclusion .

**Comment by faho** [comment]
Read https://github.com/fish-shell/fish-shell/issues/10956#issuecomment-2564671373.

There *WILL NOT* be a windows port of fish.
