### ISSUE TITLE
Problems building fish GIT head on NetBSD

### ISSUE THREAD

**Issue by 0-wiz-0** [fish-shell/fish-shell#10981]
After reading the [Rustport](https://fishshell.com/blog/rustport/) blog post, I wanted to give building fish-shell a try on NetBSD 10.99.12/amd64.

I see the following issues with d5efef1cc52091066f93843dad52b472738c62f7:

1. During `cmake`, unportable uname(1) options are used.
```
-- The C compiler identification is GNU 12.4.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Setting build type to default 'RelWithDebInfo'
-- Found Gettext: /usr/bin/msgmerge (found version "0.16.1")
-- Trying to use PCRE2 from the system
   0.011633598s ERROR os_info::uname: 'uname' invocation error: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "uname: unknown option -- o\nusage: uname [-amnprsv]\n" }
-- Rust Target: x86_64-unknown-netbsd
-- Determining required link libraries for target x86_64-unknown-netbsd
-- Required static libs for target x86_64-unknown-netbsd: execinfo;pthread;rt;gcc_s;c;m;rt;pthread;util;rt;util;execinfo
-- Found Rust: /usr/pkg/bin/rustc (found version "1.81.0")
   0.001907867s ERROR os_info::uname: 'uname' invocation error: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "uname: unknown option -- o\nusage: uname [-amnprsv]\n" }
CMake Deprecation Warning at cmake/Tests.cmake:39 (cmake_policy):
  The OLD behavior for policy CMP0037 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  CMakeLists.txt:87 (include)


-- The following features have been enabled:

 * gettext, translate messages with gettext
 * Documentation, user manual and documentation

-- The following OPTIONAL packages have been found:

 * Gettext

-- The following REQUIRED packages have been found:

 * Rust

-- Configuring done (0.7s)
-- Generating done (0.1s)
```
This doesn't seem to have any bad side effects though.

2. The build succeeds, but building the documentation fails:
```
[ 75%] Building HTML documentation with Sphinx

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/pkg/lib/python3.13/site-packages/sphinx/config.py", line 529, in eval_config_file
    exec(code, namespace)  # NoQA: S102
    ~~~~^^^^^^^^^^^^^^^^^
  File ".../fish-shell/doc_src/conf.py", line 74, in <module>
    ret = subprocess.check_output(
          ~~~~~~~~~~~~~~~~~~~~~~~^
        ("fish_indent", "--version"), stderr=subprocess.STDOUT
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ).decode("utf-8")
    ^
  File "/usr/pkg/lib/python3.13/subprocess.py", line 472, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
               **kwargs).stdout
               ^^^^^^^^^
  File "/usr/pkg/lib/python3.13/subprocess.py", line 577, in run
    raise CalledProcessError(retcode, process.args,
                             output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '('fish_indent', '--version')' returned non-zero exit status 1.
```
The problem is a missing rpath in the fish-indent binary:
```
# ./fish_indent
./fish_indent: Shared object "libintl.so.8" not found
```
(This also affects the `fish` binary.)
The underlying issue here is that on NetBSD, we prefer to hardcode the rpath (run-time library search path) into the binaries, instead of using `/etc/ld.so.conf` like Linux does. In pkgsrc, for other programs, we set
```
RUSTFLAGS="-C link-arg=-Wl,-R/usr/pkg/lib"
```
(I don't know if there's a rusty way to do that on the cargo level.)
so I tried that here, but
3. `make clean` doesn't clean the rust binaries
I wanted to rebuild, so I did `make clean; RUSTFLAGS=... make` but I only get
```
[  8%] Generating de.gmo
[  8%] Built target pofiles_1
[ 16%] Generating en.gmo
[ 16%] Built target pofiles_2
[ 25%] Generating fr.gmo
[ 25%] Built target pofiles_3
[ 33%] Generating pl.gmo
[ 33%] Built target pofiles_4
[ 41%] Generating pt_BR.gmo
[ 41%] Built target pofiles_5
[ 50%] Generating sv.gmo
[ 50%] Built target pofiles_6
[ 58%] Generating zh_CN.gmo
[ 58%] Built target pofiles_7
    Finished `release-with-debug` profile [optimized + debuginfo] target(s) in 0.03s
[ 58%] Built target fish
    Finished `release-with-debug` profile [optimized + debuginfo] target(s) in 0.03s
[ 58%] Built target fish_indent
    Finished `release-with-debug` profile [optimized + debuginfo] target(s) in 0.03s
[ 58%] Built target fish_key_reader
[ 58%] Built target CHECK-FISH-BUILD-VERSION-FILE
[ 66%] Building man pages with Sphinx
[ 66%] Built target sphinx-manpages
[ 75%] Building HTML documentation with Sphinx
...
```
There should be `cargo` output after the 58%, but it doesn't rebuild it.
4. I didn't find a way to pass `RUSTFLAGS` through cmake/make. I see that the github actions that do use RUSTFLAGS manually run cargo.

The good news: Running
```
LD_LIBRARY_PATH=/usr/pkg/lib ./fish
```
gives me a fish shell prompt!

Btw,  if you want to set up NetBSD CI, take a look at 
https://github.com/vmactions/netbsd-vm

Thank you.

**Comment by zanchey** [comment]
Looks like https://github.com/stanislav-tkach/os_info/commit/62a4aeb51922ca2f8b2d467d50cdafd467121287 is responsible for the uname errors.

**Comment by faho** [comment]
I would like to know what you're doing differently from me.

Because I *have* a NetBSD VM I had compiled fish on, before release, and it worked.

Still works, in fact.

The info:

```
> uname -a
NetBSD netbsd 10.0 NetBSD 10.0 (GENERIC) #0: Thu Mar 28 08:33:33 UTC 2024  mkrepro@mkrepro.NetBSD.org:/usr/src/sys/arch/amd64/compile/GENERIC amd64
> cargo --version
cargo 1.79.0
> type rustc; rustc --version
rustc is /usr/pkg/bin/rustc
rustc 1.79.0 (129f3b996 2024-06-10) (built from a source tarball)
```

So yeah, that's cargo/rust installed via pkg.

I get the uname errors, but everything appears to be working. I can run fish without LD_LIBRARY_PATH set.

I can install py313-sphinx, and, after I add a symlink called "sphinx-build" to "sphinx-build-313", it builds the docs.

**Comment by 0-wiz-0** [comment]
I think the difference is that (because of installing samba4) I have gettext-lib installed from pkgsrc, and it is somehow preferred to the base version. The base version doesn't need an rpath, because `/usr/lib` is in the default rpath.

If you want to reproduce, `pkg_add gettext-lib` and I think you'll see this too.

**Comment by faho** [comment]
> If you want to reproduce, pkg_add gettext-lib and I think you'll see this too.

```
netbsd# pkgin install gettext-lib
calculating dependencies...done.
nothing to do.
netbsd# pkg_add gettext-lib
pkg_add: no pkg found for 'gettext-lib', sorry.
pkg_add: 1 package addition failed
netbsd# 
```

**Comment by 0-wiz-0** [comment]
I played around in an empty sandbox a bit.  This is enough to reproduce it for me:
```
pkgin in cmake rust pcre2 pkgconf
```
So this happens when pcre2 is installed and found (pkgconf is necessary even though the pcre2 package doesn't install a pkg-config file, go figure!).
```
# ldd fish
fish:
        -lintl.1 => /usr/lib/libintl.so.1
        -lc.12 => /usr/lib/libc.so.12
        -lpcre2-8.0 => not found
        -lpcre2-32.0 => not found
        -lrt.1 => /usr/lib/librt.so.1
        -lpthread.1 => /usr/lib/libpthread.so.1
        -lgcc_s.1 => /usr/lib/libgcc_s.so.1
        -lm.0 => /usr/lib/libm.so.0
```
(When I `pkg_add gettext-lib` in the same environment I get the original problem I reported.)

**Comment by faho** [comment]
> What is the official way to pass RUSTCFLAGS through fish's build system?

cmake will pass on $RUSTFLAGS (note: not rust*C*flags, this is rust, not C), so it should work if you set them when you run `cmake`:

```fish
RUSTFLAGS="-C link-arg=-Wl,-R/usr/pkg/lib" cmake ..
```

This will bake them into the makefile, so any subsequent calls to `make` should use them.

**Comment by 0-wiz-0** [comment]
Thank you, setting it for cmake makes fish build & link for me even with pcre2/pkgconf/gettext-lib installed.

**Comment by faho** [comment]
Yup, I can confirm installing pcre2 and pkgconf breaks it, and setting RUSTFLAGS for cmake fixes it.

I don't think there is a way for us to detect that and set it automatically? It seems acceptable that pkgsrc would have to set variables for building against pkgsrc.

Other than that, the uname thing is upstream and for `make clean` we could technically use [ADDITIONAL_CLEAN_FILES](https://cmake.org/cmake/help/latest/prop_tgt/ADDITIONAL_CLEAN_FILES.html), but tbh just blow away your build directory (literally `rm -rf *`).

**Comment by 0-wiz-0** [comment]
The problem is that the RUSTFLAGS are also needed when you have pcre2 + pkgconf installed on NetBSD but are not building fish from pkgsrc. Not sure if this needs mentioning in some docs, but we know what do in the package.

I'll leave it up to you if you want to improve`make clean`, I was using the `rm` method anyway.

Thanks for the feedback!
