### ISSUE TITLE
Can't install fish 4.0 (beta) from archlinux (AUR) fish-git

### ISSUE THREAD

**Issue by SerJaimeLannister** [fish-shell/fish-shell#10982]
[asciicinema link](https://asciinema.org/a/aBo9wD7p6XJG5y0kxTtsBuxhh)

Here is also the gif of that for convenience 

![demo](https://github.com/user-attachments/assets/7c7b0773-201e-4c69-8086-e6a5d5a601dd)

Also the log 

`Aur (1) fish-git-2:4.0b1.r45.gc473aa60a-1

:: Proceed to review? [Y/n]: y

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
==> Making package: fish-git 2:4.0b1.r45.gc473aa60a-1 (Tue 31 Dec 2024 04:24:36 PM IST)
==> Retrieving sources...
  -> Updating fish-shell git repo...
==> Validating source files with b2sums...
    fish-shell ... Skipped
==> Making package: fish-git 2:4.0b1.r45.gc473aa60a-1 (Tue 31 Dec 2024 04:24:38 PM IST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Updating fish-shell git repo...
==> Validating source files with b2sums...
    fish-shell ... Skipped
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Creating working copy of fish-shell git repo...
Cloning into 'fish-shell'...
done.
==> Starting pkgver()...
==> Updated version: fish-git 2:4.0b1.r101.gd5efef1cc-1
==> Sources are ready.
fish-git-2:4.0b1.r45.gc473aa60a-1: parsing pkg list...
==> Making package: fish-git 2:4.0b1.r101.gd5efef1cc-1 (Tue 31 Dec 2024 04:24:42 PM IST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Starting pkgver()...
==> Removing existing $pkgdir/ directory...
==> Starting build()...
-- The C compiler identification is GNU 14.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Gettext: /usr/bin/msgmerge (found version "0.22.5")
-- Trying to use PCRE2 from the system
-- Rust Target: x86_64-unknown-linux-gnu
-- Determining required link libraries for target x86_64-unknown-linux-gnu
-- Required static libs for target x86_64-unknown-linux-gnu: gcc_s;util;rt;pthread;m;dl;c
-- Found Rust: /usr/bin/rustc (found version "1.83.0")
-- The following features have been enabled:

 * gettext, translate messages with gettext
 * Documentation, user manual and documentation

-- The following OPTIONAL packages have been found:

 * Gettext

-- The following REQUIRED packages have been found:

 * Rust

-- Configuring done (0.4s)
-- Generating done (0.1s)
-- Build files have been written to: /home/padhle/.cache/paru/clone/fish-git/src/fish-shell/build
make: Entering directory '/home/padhle/.cache/paru/clone/fish-git/src/fish-shell/build'
[  8%] Generating de.gmo
[  8%] Built target pofiles_1
[ 16%] Generating en.gmo
[ 16%] Built target pofiles_2
[ 25%] Generating fr.gmo
[ 25%] Built target pofiles_3
[ 33%] Generating pl.gmo
[ 33%] Built target pofiles_4
[ 41%] Generating pt_BR.gmo
[ 41%] Built target pofiles_5
[ 50%] Generating sv.gmo
[ 50%] Built target pofiles_6
[ 58%] Generating zh_CN.gmo
[ 58%] Built target pofiles_7
   Compiling libc v0.2.159
   Compiling shlex v1.3.0
   Compiling siphasher v0.3.11
   Compiling rand_core v0.6.4
   Compiling phf_shared v0.11.2
   Compiling rand v0.8.5
   Compiling pkg-config v0.3.31
   Compiling phf_generator v0.11.2
   Compiling rsconf v0.2.2
   Compiling jobserver v0.1.32
   Compiling phf_codegen v0.11.2
   Compiling cfg_aliases v0.2.1
   Compiling autocfg v1.4.0
   Compiling cc v1.1.30
   Compiling num-traits v0.2.19
   Compiling terminfo v0.9.0
   Compiling nix v0.29.0
   Compiling allocator-api2 v0.2.18
   Compiling foldhash v0.1.3
   Compiling memchr v2.7.4
   Compiling equivalent v1.0.1
   Compiling minimal-lexical v0.2.1
   Compiling hashbrown v0.15.0
   Compiling phf v0.11.2
   Compiling nom v7.1.3
   Compiling pcre2-sys v0.2.9 (https://github.com/fish-shell/rust-pcre2?tag=0.2.9-utf32#85b7afba)
   Compiling fish v4.0.0-beta.1 (/home/padhle/.cache/paru/clone/fish-git/src/fish-shell)
   Compiling widestring v1.1.0
   Compiling log v0.4.22
   Compiling fnv v1.0.7
   Compiling bitflags v2.6.0
   Compiling cfg-if v1.0.0
   Compiling pcre2 v0.2.9 (https://github.com/fish-shell/rust-pcre2?tag=0.2.9-utf32#85b7afba)
   Compiling fish-printf v0.2.1 (/home/padhle/.cache/paru/clone/fish-git/src/fish-shell/printf)
   Compiling lru v0.12.5
   Compiling errno v0.3.9
   Compiling lazy_static v1.5.0
   Compiling once_cell v1.20.2
    Finished `release` profile [optimized] target(s) in 1m 20s
[ 58%] Built target fish
   Compiling fish v4.0.0-beta.1 (/home/padhle/.cache/paru/clone/fish-git/src/fish-shell)
    Finished `release` profile [optimized] target(s) in 47.31s
[ 58%] Built target fish_indent
   Compiling fish v4.0.0-beta.1 (/home/padhle/.cache/paru/clone/fish-git/src/fish-shell)
    Finished `release` profile [optimized] target(s) in 17.26s
[ 58%] Built target fish_key_reader
4.0b1-101-gd5efef1cc
[ 58%] Built target CHECK-FISH-BUILD-VERSION-FILE
[ 66%] Building man pages with Sphinx
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 5, in <module>
    from sphinx.cmd.build import main
ModuleNotFoundError: No module named 'sphinx'
make[2]: *** [CMakeFiles/sphinx-manpages.dir/build.make:71: CMakeFiles/sphinx-manpages] Error 1
make[1]: *** [CMakeFiles/Makefile2:751: CMakeFiles/sphinx-manpages.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
make: Leaving directory '/home/padhle/.cache/paru/clone/fish-git/src/fish-shell/build'
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'fish-git-2:4.0b1.r45.gc473aa60a-1': 
error: packages failed to build: fish-git-2:4.0b1.r45.gc473aa60a-1`

**Comment by faho** [comment]
Your sphinx install is broken:

>  ModuleNotFoundError: No module named 'sphinx'

This works for me, on arch.

It's possible you have an AUR version of the sphinx package installed and haven't updated it for a new python release.
