### ISSUE TITLE
tmux iterm2 integration issue

### ISSUE THREAD

**Issue by Globegitter** [fish-shell/fish-shell#1105]
I am not entirely sure if it is a fish issue, but I first noticed it happening relatively shortly after I switched to fish (2.0.0)

So as the title suggests, I am running fish (2.1.0 now) with iterm2 and their tmux integration.
So ```tmux -CC``` always works fine, but the issue is when running ```tmux -CC attach```, sometimes I do get the error you see below on the screenshot. I will try to investigate more what exactly is going on, but it seems to be mostly (or only) happening after I restart my machine.
Is that something I should maybe also file with iterm itself? Or anyone any ideas what could be the issue?

![screen shot 2013-11-09 at 13 39 17](https://f.cloud.github.com/assets/2580254/1507216/500f2a66-496e-11e3-9fdc-e444b77e9b8b.png)

**Comment by faho** [comment]
@Globegitter: Is this still an issue?

**Comment by zanchey** [comment]
Without being able to reproduce it I'm going to close this as inactive for now - if it's still an issue please let us know.

**Comment by marconett** [comment]
fyi: running into the same problem. this occurs when trying to attach to a tmux session that doesn't exist. i can reproduce this with bash though. not a fish issue.
