### ISSUE TITLE
Completing long options doesn't take lists of options and descriptions

### ISSUE THREAD

**Issue by JelteF** [fish-shell/fish-shell#1106]
The way the `-a` option in the `complete` command handles lists of options with descriptions is great. However the `-l` (or `-s`) option don't have this same functionality. 

It would be nice for the completions I am writing at this moment, since this involves parsing options from the output of another command.

**Comment by krader1961** [comment]
It's not necessary for `-l` and `-s` to accept values that are a newline separated list of flags and descriptions separated by a tab. Doing so is also ambiguous when combined with `-a`.
