### ISSUE TITLE
256 colors? This is not enough. 24-bit is more.

### ISSUE THREAD

**Issue by xfix** [fish-shell/fish-shell#1115]
We need to go beyond that. What about 24-bit colors that Konsole (terminal from KDE, since 4.9, for two years) supports. For example, the following code writes `rbg(20, 20, 255)` color in Konsole.

```sh
echo \e\[38\;2\;20\;20\;255mblue
```

**Comment by zanchey** [comment]
`terminfo` might work, although the number of colors expressed by 24-bit color doesn't appear to fit in the struct (`infocmp` just returns "colors#0"). What about the `COLORTERM` variable?

The Xterm `tcap-query` extension might be useful, too.

**Comment by zanchey** [comment]
retargeting; as far as I understand fish will output true-color codes but there is not yet an interface to instruct it to do so, nor to reliably detect whether that is wise.

**Comment by faho** [comment]
This has been fixed as far as we can fix it by b73bf53bd30cb8b6056888a473368968041dbe66.
