### ISSUE TITLE
Is there a way to install fish shell on raspberry pi?

### ISSUE THREAD

**Issue by phoenixg** [fish-shell/fish-shell#1130]

**Comment by raleighlittles** [comment]
@zanchey Just found this thread from Google when I went to try to install fish on my Raspberry Pi 3B+. Is there any information about whether the latest version of fish is compatible on the Raspberry Pi 3B+?

**Comment by raleighlittles** [comment]
Here's the error I get:

```
pi@raspberrypi:~ $ sudo apt-add-repository ppa:fish-shell/release-3
Traceback (most recent call last):
  File "/usr/bin/apt-add-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 89, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/stretch

```

**Comment by raleighlittles** [comment]
Before this, I installed the `software-properties-common` package so that I could use the apt-add-repository command.

It seemed to install successfully.

```pi@raspberrypi:~ $ sudo apt-get install software-properties-common
Reading package lists... Done
Building dependency tree        
Reading state information... Done
The following package was automatically installed and is no longer required:
  realpath
Use 'sudo apt autoremove' to remove it.
The following additional packages will be installed:
  gir1.2-packagekitglib-1.0 python3-pycurl python3-software-properties
  unattended-upgrades
Suggested packages:
  libcurl4-gnutls-dev python-pycurl-doc python3-pycurl-dbg bsd-mailx
  mail-transport-agent needrestart
The following NEW packages will be installed:
  gir1.2-packagekitglib-1.0 python3-pycurl python3-software-properties
  software-properties-common unattended-upgrades
0 upgraded, 5 newly installed, 0 to remove and 2 not upgraded.
Need to get 288 kB of archives.
After this operation, 1,128 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 http://mirrors.ocf.berkeley.edu/raspbian/raspbian stretch/main armhf gir1.2-packagekitglib-1.0 armhf 1.1.5-2+deb9u1 [34.7 kB]
Get:2 http://mirrors.ocf.berkeley.edu/raspbian/raspbian stretch/main armhf python3-pycurl armhf 7.43.0-2 [58.4 kB]
Get:3 http://mirrors.ocf.berkeley.edu/raspbian/raspbian stretch/main armhf python3-software-properties all 0.96.20.2-1 [49.5 kB]
Get:4 http://mirrors.ocf.berkeley.edu/raspbian/raspbian stretch/main armhf software-properties-common all 0.96.20.2-1 [83.6 kB]
Get:5 http://mirrors.ocf.berkeley.edu/raspbian/raspbian stretch/main armhf unattended-upgrades all 0.93.1+nmu1 [61.7 kB]
Fetched 288 kB in 2s (121 kB/s)           
Preconfiguring packages ...
Selecting previously unselected package gir1.2-packagekitglib-1.0.
(Reading database ... 135328 files and directories currently installed.)
Preparing to unpack .../gir1.2-packagekitglib-1.0_1.1.5-2+deb9u1_armhf.deb ...
Unpacking gir1.2-packagekitglib-1.0 (1.1.5-2+deb9u1) ...
Selecting previously unselected package python3-pycurl.
Preparing to unpack .../python3-pycurl_7.43.0-2_armhf.deb ...
Unpacking python3-pycurl (7.43.0-2) ...
Selecting previously unselected package python3-software-properties.
Preparing to unpack .../python3-software-properties_0.96.20.2-1_all.deb ...
Unpacking python3-software-properties (0.96.20.2-1) ...
Selecting previously unselected package software-properties-common.
Preparing to unpack .../software-properties-common_0.96.20.2-1_all.deb ...
Unpacking software-properties-common (0.96.20.2-1) ...
Selecting previously unselected package unattended-upgrades.
Preparing to unpack .../unattended-upgrades_0.93.1+nmu1_all.deb ...
Unpacking unattended-upgrades (0.93.1+nmu1) ...
Setting up python3-pycurl (7.43.0-2) ...
Processing triggers for systemd (232-25+deb9u8) ...
Setting up unattended-upgrades (0.93.1+nmu1) ...

Creating config file /etc/apt/apt.conf.d/20auto-upgrades with new version

Creating config file /etc/apt/apt.conf.d/50unattended-upgrades with new version
Created symlink /etc/systemd/system/multi-user.target.wants/unattended-upgrades.service → /lib/systemd/system/unattended-upgrades.service.
Synchronizing state of unattended-upgrades.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable unattended-upgrades
Processing triggers for man-db (2.7.6.1-2) ...
Setting up gir1.2-packagekitglib-1.0 (1.1.5-2+deb9u1) ...
Setting up python3-software-properties (0.96.20.2-1) ...
Processing triggers for dbus (1.10.26-0+deb9u1) ...
Setting up software-properties-common (0.96.20.2-1) ...
Processing triggers for systemd (232-25+deb9u8) ...
Processing triggers for dbus (1.10.26-0+deb9u1) ...
```

**Comment by raleighlittles** [comment]
@zanchey Here's my system information.
```
pi@raspberrypi:~ $ lsb_release -a && uname -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.6 (stretch)
Release:	9.6
Codename:	stretch
Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

```


````
pi@raspberrypi:~ $ lsb_release -a && uname -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.6 (stretch)
Release:	9.6
Codename:	stretch
Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

```

**Comment by zanchey** [comment]
It is definitely compatible, but we don't provide prebuilt packages for Raspbian. The PPA packages might work but I have no idea.

You are probably best off rebuilding the package with something like the following:

```
apt-get install build-essential cmake devscripts libpcre2-dev libncurses5-dev
dget --allow-unauthenticated https://download.opensuse.org/repositories/shells:/fish/Debian_9.0/fish_3.0.0-1.dsc
cd fish-3.0.0
debuild -i -us -uc -b
cd ..
dpkg -i fish*3.0.0-1*.deb`
```

**Comment by swalker326** [comment]
Here is a handy script I use to install it on fresh raspbin lite installs. 

https://gist.github.com/AFRUITPIE/1d26d3d15dc43f821a36d7ccc1260a7f

**Comment by phoenixg** [comment]
I don't think install fish on Rpi is a good idea, because it's very slow on Rpi.

**Comment by swalker326** [comment]
> I don't think install fish on Rpi is a good idea, because it's very slow on Rpi.

I have it installed on 3 different headless raspbin lites and have not had any issues with it. I have heard that others have had issues though.

**Comment by Brandonshire** [comment]
Hi there! I just used this script to install Fish on my Raspberry Pi. Only afterward did I realize I should have replaced the "3.1.2" with the current version. But this of course also brings up another question: After using a script like this to install Fish what is the best way to update Fish as new versions come out? On my Mac since I'm using a package manager I just use that to update but i'm not sure what the best way to update is with a version built and installed this way. Would just doing this process again with the latest version do it? (I'm still a bit of a noob, but am trying to learn as much as I can!)

> Here is a handy script I use to install it on fresh raspbin lite installs.
> 
> https://gist.github.com/AFRUITPIE/1d26d3d15dc43f821a36d7ccc1260a7f
> 
> EDIT:
> 
> my process once connected to the pi via ssh:
> 
> ```
> mkdir scripts
> touch ./scripts/fish_shell_install.sh
> nano scripts/fish_shell_install.sh
> paste the script into the .sh file create locally
> save and exit
> chmod +x script/fish_shell_install.sh
> cd scripts
> ./fish_shell_install.sh
> ```
> 
> I'm sure someone much better in the terminal could condense this into a 1 or maybe 2 liner

**Comment by Brandonshire** [comment]
Well I went ahead and essentially just ran this again but with a few modifications to the script to get it to work with the latest version of Fish and it seemed to work (after a restart). Not sure if I now have two versions of Fish installed or what, but it seems to be using the correct version now.

**Comment by Dan1jel** [comment]
> Well I went ahead and essentially just ran this again but with a few modifications to the script to get it to work with the latest version of Fish and it seemed to work (after a restart). Not sure if I now have two versions of Fish installed or what, but it seems to be using the correct version now.
> 
> Would love it if some day there was a Raspberry Pi specific build of Fish!

Mind sharing the updated script?

**Comment by Brandonshire** [comment]
> > Well I went ahead and essentially just ran this again but with a few modifications to the script to get it to work with the latest version of Fish and it seemed to work (after a restart). Not sure if I now have two versions of Fish installed or what, but it seems to be using the correct version now.
> > Would love it if some day there was a Raspberry Pi specific build of Fish!
> 
> Mind sharing the updated script?

Here is my fork of the script above. It is probably out of date at this point. 

https://gist.github.com/Brandonshire/73098f982d00d13ddf93a8d484160da2
