### ISSUE TITLE
bind: Key with name 'dc' does not have any mapping when I start fish

### ISSUE THREAD

**Issue by shinokada** [fish-shell/fish-shell#1155]
When I start fish, I get three bind notes which all tell that they don't have any mapping. How can I fix this problem? Thanks in advance.

Using Mac Mavericks.

➜  ~  exec '/Applications/fish.app/Contents/Resources/base/bin/fish'
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
bind: Key with name 'dc' does not have any mapping
bind: Key with name 'ppage' does not have any mapping
bind: Key with name 'npage' does not have any mapping
myname@sokada-macbook ~>

**Comment by znculee** [comment]
I have this problem when I use fish in the terminal of MacVim. However, I fix this problem by ucomment `fish_vi_key_bindings` in `.config/fish/config.fish`.
