### ISSUE TITLE
Support for anonymous session (no logging to history)

### ISSUE THREAD

**Issue by jonhoo** [fish-shell/fish-shell#1156]
In some session I know I will have to type commands that contain sensitive information, and in this case I would prefer not to have those commands written to history at all.

In bash, this can be done by doing `unset HISTFILE` before running any commands. You can still use arrow up to get to previous commands from that session, but once you terminate the shell, the commands are gone. I haven't found a similar feature in fish? I know I can prefix each command with a space, but that's not really a good alternative when you have to run more than just a couple of commands.

**Comment by IngCr3at1on** [comment]
I might be missing something somewhere in my search but this seems like a valid enough place to ask. Is there currently a way to clear the history in fish shell?

**Comment by ridiculousfish** [comment]
Try `history --clear

**Comment by IngCr3at1on** [comment]
Awesome, thanks @ridiculousfish

**Comment by zanchey** [comment]
There's a hacky implementation: add `commandline " "` to your `fish_prompt`.

**Comment by gechr** [comment]
I've come up with an even hackier (but effective) solution until this is properly supported in fish.

In `~/.config/fish/config.fish`, add:
```fish
set -g __fish_history_file        ~/.local/share/fish/fish_history
set -g __fish_history_backup_file $__fish_history_file.bak
set -g __fish_history_pid_file    $__fish_history_file.pid

if test -f $__fish_history_backup_file
  read -l histpid < $__fish_history_pid_file
  if not kill -0 $histpid 2>/dev/null
      mv -f -- $__fish_history_backup_file $__fish_history_file
      rm -f -- $__fish_history_pid_file
  end
end
```

Then, create a new function to disable history (e.g. `~/.config/fish/functions/disable_history.fish`)
```fish
function disable_history --description "Disable history for the current session"
    # Keep track of the pid responsible for disabling history
    echo %self > $__fish_history_pid_file
    # Redirect history to /dev/null
    mv -f $__fish_history_file $__fish_history_backup_file
    and ln -sf /dev/null $__fish_history_file
end
```

When the function is executed, history will be disabled for the current session and any other sessions that are launched while the current session is active (i.e. the PID exists). Once the current session exits, new sessions will write their history as normal.

You could write another function to manually re-enable history rather than automatically when a new session is launched.

**Comment by bucaran** [comment]
I love this! @gechr Great work.

First time I see this:

```fish
ln -sf /dev/null $__fish_history_file
```

What does it do? I guess it overrites the fill with null, so it's kind of like `echo > file`?

**Comment by gechr** [comment]
@bucaran It creates a symbolic link from `~/.local/share/fish/fish_history` to `/dev/null`, which is a special device that discards anything written to it. It's important that the original history is first renamed to `~/.local/share/fish/fish_history.bak`, though, else you'd lose all your history. Use with caution! :wink:

**Comment by bucaran** [comment]
I understand `/dev/null`, what I am asking is what is the result of softly copying `/dev/null` into the history file?

**Comment by gechr** [comment]
Hmm, I'm not quite sure I understand the question, but I'll take another stab at answering it...

It means none of the history is stored anywhere on disk after you've typed `disable_history`. If the symlink wasn't created, fish would automatically create a new history file and start writing to it, which is what we're trying to avoid.

**Comment by bucaran** [comment]
```fish
ln -s /dev/null nil
echo hi > nil
$
```

That. I didn't get it at first.

**Comment by krader1961** [comment]
Closing this as a dup of #102. Once I've addressed that issue it will be possible to tell fish not to log any commands both before invoking the fish shell and while it is running. Not to mention having distinct history log files for specialized needs.

**Comment by faho** [comment]
>That’s much more complicated than necessary, like saying you can clear your browser history. That’s all I’m suggesting.

@jspiro: What exactly is more complicated here? You start an "anonymous session" by setting that variable. If you want something that has "anonymous" in the name, make your own function. E.g.

```fish
function fishcognito
    set -lx fish_history ''
    fish
end
```

I don't really see how we can make it any less complicated without making it less general.
