### ISSUE TITLE
fish does not use 256 colors from inside tmux

### ISSUE THREAD

**Issue by badp** [fish-shell/fish-shell#1158]
Running fish 2.1.0 from inside a tmux 1.6-1ubuntu1 session causes fish to only use "basic" colors, although tmux does support 256 colors.

**Comment by sean-smith** [comment]
I was having a similar issue where `tmux` was using the color of my `fish_prompt` instead of the default fish color. I was able to fix it the same way by adding the line `set-option -g default-terminal "screen-256color"` to my `~/.tmux.conf` and sourcing.
