### ISSUE TITLE
disallow literal backtick unless quoted or escaped

### ISSUE THREAD

**Issue by xfix** [fish-shell/fish-shell#1159]
This is a huge change, but I'm going to propose it anyway. ``` is one of confusing characters, very rarely used in actual commands (it's not that it's easy to use in other shells, anyway).

My proposal is to (possibly in fish 3.0) make ``` a special character. It would do nothing, except for displaying an error recommending you to use `()` instead. If you would need ``` anyway, you could escape it, or quote it.

``` sh
~ $ echo `echo hello world`
fish: Did you mean (COMMAND)? In fish, the ` character is not used. To learn more about command substitution in fish, type 'help expand-command-substitution'.
```

I believe that such change, while (sort of) incompatible, would improve error reporting in fish for common bash constructs.

**Comment by faho** [comment]
Yeah, in my experience the confusion mentioned here basically doesn't happen, and nobody has stepped forward in five years to actually implement it.

Let's close this!
