### ISSUE TITLE
completion doesn't show correct exact completion

### ISSUE THREAD

**Issue by ecraven** [fish-shell/fish-shell#116]
If I type "man<TAB>", the only command completions shown are mandb, manpath and manywin, man itself is not shown. This is different from bash, zsh, fish, and probably a bug. This happens every time an exact completion is entered. As far as I can tell, the problem is in complete.cpp somewhere, though the external __fish_describe_command is called, but the output is discarded.

**Comment by faho** [comment]
I can't reproduce either. Given nobody has been able to in the last 2.5 years this seems safe to close.

**Comment by ridiculousfish** [comment]
Thanks!
