### ISSUE TITLE
set_color does not end bold

### ISSUE THREAD

**Issue by kevna** [fish-shell/fish-shell#1164]
After the use of `set_color -o` the colour remains bold when the colour is changed to a listed color.
Currently this is only reset through use of an escape code.

**Comment by krader1961** [comment]
It's not at all obvious that bold, dim, italics, reverse mode should be treated like a color and reset if another color is set. The way that ANSI X3.64 escape sequences work is reflected in the design of the `set_color` command. So I'm closing this.

**Comment by floam** [comment]
Problem with using `set_color normal` is it also changes the color - the ANSI escape to just exit bold mode cannot be produced by `set_color`.
