### ISSUE TITLE
'var=val' should issue fish_command_not_found event

### ISSUE THREAD

**Issue by maxfl** [fish-shell/fish-shell#1172]
It is possible to define a function containing '=' sign:

``` sh
function a=b
    echo Works!
end
a=b
```

In the same time if one calls bash-like assignment, the error is printed, but fish_command_not_found is not thrown, which is not in agreement with possibility to make 'a=b' function.

So either '=' should be forbiddein in function name, either calling 'a=b' without function defined should throw fish_command_not_found event.

I think the latter is better. In addition if event is thrown one could then define command_not_found handler which will convert 'a=b' to 'set a b'.

**Comment by faho** [comment]
Is there any reason why functions allow different characters than variables?

**Comment by ridiculousfish** [comment]
I guess there's a need for the `.` function, but allowing `$` seems silly.

**Comment by krader1961** [comment]
The `wcsfuncname()` function is used to validate function names. The reason to allow characters like `=` and `$` in the name is that they are legal in an external command name.

I think the value of alerting the user that assignment via the equal sign is far greater than consistency with other command not found behavior. If someone has deliberately created a function or external command of the form `a=b` then it is reasonable to execute it.
