### ISSUE TITLE
Compile on MSYS

### ISSUE THREAD

**Issue by orefalo** [fish-shell/fish-shell#1177]
See http://stackoverflow.com/questions/20437546/compiling-fish-shell-under-msys?noredirect=1#comment30677948_20437546

The idea is to come with a version of MSYSGIT tailored to fish.

**Comment by PicassoCT** [comment]
no, msys runs with the cygwin.dlls
you could compile fish for cygwin:
http://superuser.com/questions/328340/how-to-use-fish-shell-in-cygwin

**Comment by PicassoCT** [comment]
sorry for necroing ancient thread..

**Comment by orefalo** [comment]
no worries, cygwin is a different/ more complete (complex) echo system. I gave up on the idea.
Was really trying to build a git distribution for win$ based on fish shell.
