### ISSUE TITLE
trap EXIT ?

### ISSUE THREAD

**Issue by dolmen** [fish-shell/fish-shell#1180]
I found no event that allows to execute a shell function just before fish itself exits. This feature is `trap ... EXIT` on POSIX shells.

I need this feature for my project [angel-PS1](https://github.com/dolmen/angel-PS1): I would like to be able to kill the angel process when `fish` exits. Currently the angel still lives as long as the terminal lives (which may be longer than `fish` life as `fish` may have been started from another shell on that terminal).

**Comment by krader1961** [comment]
Since we also support compatibility commands like `export` and `setenv` it seems to me that we should also map `trap ... EXIT` to the fish equivalent. And possibly add an entry to the FAQ so that people who want to do it in a more fishy way can easily find how to do so.

**Comment by krader1961** [comment]
Turns out this has already been implemented. See commit 4a3cda149 and earlier commits. I tested `trap 'echo exiting' EXIT` and it works for me. The only thing to do is document it.

**Comment by fdcds** [comment]
> I think you're looking for:
> 
> ```
> function myfunc --on-process %self
>     # exit stuff goes here
> end
> ```

It is actually `--on-process-exit`. Note that this will not do anything if you use `exec` in your script.
