### ISSUE TITLE
'.' (source) misreports line numbers

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#1190]
When you source a file with a dot (NOT with source), and the file contains an error, the backtrace will always show line 9 as where the 'source' is, instead of the true line. This is because the dot is a function, with the real invocation of source on its line 9.

**Comment by krader1961** [comment]
This appears to have been fixed. I created a file named *./x* with this content:

```
while false
    echo false
    end
    end
echo hello
```

Typing `. ./x` resulted in the expected error:

```
'end' outside of a block
./x (line 4):     end
                  ^
from sourcing file ./x
	called on line 224 of file /usr/local/share/fish/config.fish

in function '.'
	called on standard input

source: Error while reading file './x'
```
