### ISSUE TITLE
Using which to detect command-not-found is suspect

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#12]
In fish_config_interactive, we use 'which' to detect command-not-found.
The problem is, 'which' is not so portable, and in particular its exit status isn't always significant.
This could be changed to be 'command -v' to safer.
Also 'command' should support the -v flag.

A secondary problem is that the -s flag looks to be BSD specific.

**Comment by zanchey** [comment]
Not any more!
