### ISSUE TITLE
adding $$ support (for current shell pid) in fish

### ISSUE THREAD

**Issue by bstarynk** [fish-shell/fish-shell#1202]
Hello all,

I am missing the $$ special variable to denote the current shell's pid  (see http://hyperpolyglot.org/unix-shells giving a nice table ...); has it been discussed and rejected? What files should I look in to consider adding it?

**Comment by zanchey** [comment]
The lack of expansion in a string is #1074.

**Comment by krader1961** [comment]
I'm in agreement with @cljacobs. I don't think we should introduce `$$` but introducing `$PID` or `$SELF` can be justified despite introducing a second way to do the same thing. Note the all uppercase names to mirror other vars like `$PWD` and minimize clashes with existing uses of their lowercase forms.

**Comment by ridiculousfish** [comment]
It's also very easy for any user to just write `set SELF %self` at the top of the script and then they have it. This wouldn't work in bash since bash forks for subprocesses, but it works in fish.

**Comment by krader1961** [comment]
That `set SELF %self` works actually surprises me. As does `touch %self` but not `touch x.%self`.

**Comment by kgadek** [comment]
I would add that using `$$` is very common to detect the shell type itself. I use this to do that: `ps -cp $$ | awk 'NR==2{sub(/^-?/, "", $NF); print $NF}'` and it works quite nicely across macOS, Linux and FreeBSD and various shells… except fish.

**Comment by krader1961** [comment]
I'm removing the "RFC" label. This should be implemented. I have no objections to using `%some-string` to match process names containing that string. But given the quirks of `%self` (e.g., `touch x.%self` doesn't work) we should allow access to this info via normal variable expansion.

**Comment by faho** [comment]
>But given the quirks of %self (e.g., touch x.%self doesn't work) we should allow access to this info via normal variable expansion.

Okay. What should the variable be called? Note that `$` is currently not a valid variable name. It's also not in any way explanatory, so I'm leaning towards using a more descriptive name. Some suggestions:

- $SELF
- $PID
- $FISH_PID
- $SHELL_PID

I like the latter two the most since they best explain what the variable is.

**Comment by xfix** [comment]
I think the name should be lowercase, considering shell PID is not an exported variable (for consistency).
