### ISSUE TITLE
Can't set an environment variable with a - (dash) in it

### ISSUE THREAD

**Issue by timbertson** [fish-shell/fish-shell#1206]
$ set 'x-y' 1
    set: Invalid character '-' in variable name. Only alphanumerical characters and underscores are valid in a variable name.

This breaks when using [direnv](https://github.com/zimbatm/direnv) with [ZeroInstall](http://0install.net), because ZeroInstall frequently uses environment variables with dashes in them. I don't know where the limitation comes from, can it be removed?

I'm assuming it has something to do with fish's syntax, and that perhaps you can't _use_ envvars with dashes in them via fish syntax. Which is a shame, but preventing them from ever being set seems overly restrictive (I don't want to use them in fish, they'll only be used by programs I invoke from fish). Is there some workaround for setting an arbitrary envvar without this fish-specific check?

**Comment by faho** [comment]
@zanchey: Are you convinced by the argument that other shells also don't allow it?

I kinda am - these kinds of names should not be used by well-behaved software (because plenty of things reject them), so we should not encourage it.

**Comment by zanchey** [comment]
Yes.

**Comment by faho** [comment]
Then let's close.
