### ISSUE TITLE
Don't suggest command substitution for $''.

### ISSUE THREAD

**Issue by xfix** [fish-shell/fish-shell#1207]
```
~ $ echo $'some string'
fish: Did you mean (COMMAND)? In fish, the '$' character is only used for accessing variables. To learn more about command substitution in fish, type 'help expand-command-substitution'.
echo $'some string'
     ^
```

This is wrong, as bash `$''` syntax interprets special characters like `\n`. It doesn't involve command substitution any way I can think of.

**Comment by faho** [comment]
The error is now "Expected a variable name after this $.". This still isn't perfect - we should print a message about `$''` being unnecessary because you can just use the escapes outside of quotes.

**Comment by faho** [comment]
Okay, we've not really had any reports of this, the error makes it obvious that it doesn't work, `$''` isn't a super big thing, our fish-for-bash-users document mentions it. I'm closing this as unnecessary.
