### ISSUE TITLE
support editing the command line with an external editor

### ISSUE THREAD

**Issue by skivvies** [fish-shell/fish-shell#1215]
In bash you can press C-x C-e and it will drop you into your $EDITOR so you can input commands with it. Could fish support something similar?

**Comment by mfilej** [comment]
@maxfl's snippet seems to have stopped working for me at some point. Did anything change in fish?

**Comment by maxfl** [comment]
It's because of #2210.

**Comment by mfilej** [comment]
Thanks! I'll keep an eye on that then.

**Comment by braham-snyder** [comment]
something like this can be useful for completion, etc., depending on your editor:
```
set -l tmpfile (mktemp --suffix=".fish" --tmpdir=.); or return 1
```
if you're on OS X, you'll need homebrew's `gmktemp` (available in the formula `coreutils`, I think)

**Comment by krader1961** [comment]
In the past year I've seen several solutions documented in other issues. The one I've been using for a long time is an enhanced version of [@skivvies](https://github.com/fish-shell/fish-shell/issues/1215#issuecomment-31374267) that works whether you're using BSD or GNU mktemp:

```
function edit_command_buffer --description 'Edit the command buffer in an external editor'
    set -l f (mktemp)
    if set -q f[1]
        mv $f $f.fish
        set f $f.fish
    else
        # We should never execute this block but better to be paranoid.
        set f /tmp/fish.(echo %self).fish
        touch $f
    end

    set -l p (commandline -C)
    commandline -b > $f
    if set -q EDITOR
        eval $EDITOR $f
    else
        vim $f
    end

    commandline -r (cat $f)
    commandline -C $p
    command rm $f
end
```

Something like that should be bundled with fish. What the default bindings should be is TBD. I use `\ee` ([meta-e] and `\ev` ([meta-v] which matches the ksh binding in vi mode that I was used to using). It would be nice if we could get some people to try this and report whether or not it works on their system.

**Comment by krader1961** [comment]
Also from my comment in issue #3477 regarding the function I just mentioned:

> It's not perfect. For example, you get a weird but harmless error if you save an empty buffer when exiting the editor. It really should also check the exit status of the editor and use a non-zero status to mean the editors buffer shouldn't be used (like git commit does). But the point is that if you're doing non-trivial editing of the command line you're probably better off using a real editor than adding a bunch of fish key bindings that will never make fish truly behave like your editor.

**Comment by braham-snyder** [comment]
@krader1961 works for me with El Capitan and emacsclient (with that weird but harmless error)

**Comment by krader1961** [comment]
This question and various solutions has occurred often enough that I decided it was time to make my solution more robust. I've modified the function I posted above to make it more robust and will open a pull request to invite review of it.

**Comment by xieyuheng** [comment]
how to disable fish's default alt-v alt-e keybinding for this feature ?

**Comment by hashier** [comment]
To everyone who started to copy/paste the solution of @krader1961 like me. This is not needed anymore. This got merged into fish and got even two shortcuts. Alt-e and Alt-v.

Documentation: https://fishshell.com/docs/current/ (search for "edit the current command line in an external editor")
PR: https://github.com/fish-shell/fish-shell/pull/3627

**Comment by Pastafarianist** [comment]
Also, Alt-e and Alt-v are equivalent according to the documentation.
