### ISSUE TITLE
if first line of a command has scrolled out of view strange behavior happens

### ISSUE THREAD

**Issue by xfix** [fish-shell/fish-shell#1219]
Type `begin`, press enter along with other letters multiple times, so `begin` disappears from the terminal (because it's above terminal length), and scroll up to `begin`. Strange stuff will happen.

**Comment by krader1961** [comment]
I can reproduce this. Whether it's worth trying to fix it is debatable. I'd rather see us make something like my `edit_command_line` function a standard part of fish and bound to sequences like \ee and \ev to make it easy to perform non-trivial edits of the command line using a real editor.

**Comment by faho** [comment]
Closing in favor of #7296 because that explains the behavior more clearly.
