### ISSUE TITLE
Abbreviation expansion where commands are expected

### ISSUE THREAD

**Issue by ghost** [fish-shell/fish-shell#1220]
I have `g` set to expand to `git`, and it would be pretty neat if I could get `sudo g` to expand to `sudo git` as well.

**Comment by Moter8** [comment]
Wondered about this too today and here is the issue. :+1:

**Comment by faho** [comment]
Closing in favor of #5003, which asks for global abbreviations.

**Comment by mqudsi** [comment]
Abbreviations would only address this particular use case, but wouldn't enable, for example, `git rebase ... --exec ____` to treat the payload there as a command (not that I think it's worth the complexity, I think `sudo` covers about 99% of the need for this).
