### ISSUE TITLE
jobs expansion for piped commands

### ISSUE THREAD

**Issue by zachaller** [fish-shell/fish-shell#1221]
when using 

```
echo "asdf" | less
ctl+z
kill -9 %
```

it fails because it has the wrong process ID

**Comment by mqudsi** [comment]
Job expansion has been removed for 3.0 because it never really worked and the results were too hit or miss, in addition to the undiscoverable syntax. I'm sure we'll be revisiting a cleaner way of querying and interacting with background jobs in a more fishy fashion.
