### ISSUE TITLE
"disown" in fish shell

### ISSUE THREAD

**Issue by srikiraju** [fish-shell/fish-shell#1247]
My use case is a bit different. Issue #773 seems to be about killing the shell and have the child running. Mine is about job control.

```
$ vim code.cpp
$ [Ctrl-Z]
$ firefox something.html &
$ disown %2
$ fg -> bring back vim
```

**Comment by eush77** [comment]
`disown` in other shells removes the job from the list, fg and bg do not, which is probably what OP had in mind.
