### ISSUE TITLE
Backslashes at end of comments do nothing.

### ISSUE THREAD

**Issue by xfix** [fish-shell/fish-shell#1255]
They let you continue on next line, but that's about it.

```
~ $ echo Hello, # comment \
    world!
Hello,
fish: Unknown command 'world!'
```

**Comment by snnw** [comment]
I agree with @zanchey.

It might be confusing that the job does not execute when `\` is followed by return inside a comment.  For consistency it should be executed, and not continued.

**Comment by ridiculousfish** [comment]
Fixed as zanchey and snnw suggest. Thanks for reporting this!
