### ISSUE TITLE
Add support for disabling configuration

### ISSUE THREAD

**Issue by ZyX-I** [fish-shell/fish-shell#1256]
For testing purposes it would be handy to disable loading of some configuration files. I would suggest adding `-R`/`--no-rc` switch for disabling loading files from `/etc` and `$XDG_CONFIG_HOME` and `-D`/`--no-defaults` for disabling loading from `/usr/share/fish`.

**Comment by mqudsi** [comment]
I imagine `--no-defaults` could ignore config.fish, though I think it currently has some dependencies on other files in the share directory.

**Comment by faho** [comment]
>I imagine --no-defaults could ignore config.fish

Well.... maybe.

As it currently is, I wouldn't recommend it.

I've actually been running fish in this configuration - I test stuff by building via cmake, and then run it directly without installing, which leaves the prefix wrong.

b0368fd85b18faa70717a1720c2e3448e193ea57 improves the situation somewhat, though there' still a bunch of stuff that I wouldn't recommend running without:

- No $fish_function_path means no `type` or `eval`. Also no `.` or `:` (from share/config.fish).

- Absolutely no command-not-found handler means not even an error message when a command does not exist

- The fallback key bindings are unusably sparse - not even \x7f ("del") is bound, meaning my backspace doesn't work. Also no arrows.

I'm assuming not setting the locale or $PATH is alright.

**Comment by faho** [comment]
>I imagine it'd be OK to add the standard /{,usr/}{,local/}{,s}bin? Or at least /{,usr/}bin?

Not $PATH, that's just inherited and usually okay. $fish_function_path, which is what fish uses to find its functions.

**Comment by faho** [comment]
Wow, that was quite confused of me!

Let me try that again:

We do the following things to $PATH in share/config.fish:

- Add /usr/xpg4/bin on Solaris (does fish currently work on Solaris?)

- $fish_user_paths

- Read /etc/paths if "path_helper" exists

In addition, if $PATH is unset/empty, we set it to "/usr/bin" and "/bin" in C++. If it contains anything, we don't manipulate it.

>I imagine it'd be OK to add the standard /{,usr/}{,local/}{,s}bin?

I don't think I've heard of those being missing by accident, so I don't think that'd really help. Plus hardcoding would make it quite hard to remove on purpose.

I took the same approach when it came to setting the locale - we only do that if _none_ of the locale vars is defined, even though I strongly suggest running at least with UTF-8 encoding.

**Comment by Jomik** [comment]
I have fish complaining that `$HOME` is not set, because I am using it in a nix build step to execute a single command:
```
    mkdir -p $out/functions
    ${pkgs.fish}/bin/fish -c "${pkgs.thefuck}/bin/thefuck --alias > $out/functions/fuck.fish"
    chmod +x $out/functions/fuck.fish
```

```
<E> fish: Your personal settings will not be saved.
<E> fish: Unable to locate config directory derived from $HOME: '/homeless-shelter/.config/fish'.
<E> fish: The error was 'Permission denied'.
<E> fish: Please set $HOME to a directory where you have write access.
```

This doesn't prevent fish from executing the command, and I could easily point $HOME at something temporary. E.g
`HOME=$(mktemp -d) ${pkgs.fish}/bin/fish -c "${pkgs.thefuck}/bin/thefuck --alias > $out/functions/fuck.fish"`
But that is not really as pretty as having a "barebones" option.
The reason I need to use fish for this is that thefuck detects what shell you are using, when outputting the alias.

**Comment by mqudsi** [comment]
See https://github.com/fish-shell/fish-shell/pull/5417

**Comment by rdorbala** [comment]
+1 for this. 
I want to launch swaywm using a startup ~/.config/fish/conf.d/sway.fish as described in https://github.com/swaywm/sway/wiki#login-managers
But if I also want to use standalone fish scripts with shebang line 
#! /usr/bin/env fish
