### ISSUE TITLE
`random` should be random, or at least say it isn't.

### ISSUE THREAD

**Issue by geoff-codes** [fish-shell/fish-shell#1272]
I know its a little neurotic and nit-picky, but the current situation with `builtin random` is not ideal. To touch on some of the points from #732:
- no, bash $RANDOM should not be a model. Does anyone know, to reiterate a question raised there, would raising the upper limit break anything? 32768 is not a great range.
- I don't really feel this is an 'internal' function — I mean, if it were, shouldn't it be like `__fish_random_blahblahblah` and maybe not have a man page?
- There are actually (at least?) two pseudo-random number functions here, one in `builtin.cpp` and one in `fishd.cpp`; and the latter is even worse than the rand48 based one used for the builtin, since `gettimeofday` actually has nanosecond precision on many platforms. It's used instead of `clock_gettime` for this in Kerberos, etc. on Darwin.
- I'm not really at all trying to scream bloody murder here; there is the security thing, but I think the implications for concurrency is potentially a greater issue. These seem rather collision prone, no?

I wonder if, in this case, this might be better implemented as a shell function?
Something like this would work maybe?

```sh
echo (od -DN2 -An /dev/urandom | sed 's| ||g' | head -1)\/2 | bc
```

If not, I think at least a little note in the man page that "random is not random" might be a good idea. At least just for cover one's behind on the the security thing, you know...

**Comment by krader1961** [comment]
I stumbled across this while searching for reports of a different problem. Seems like a simple problem to fix so I'll deal with it.

**Comment by krader1961** [comment]
@Undeterminant the purpose of the fish __random__ function (or the __$RANDOM__ variable provided by other shells) is not to provide random numbers suitable for a large set of purposes (let alone cryptographic use). They're meant to provide a cheap and simple means of generating unique identifiers that are unlikely to collide with other uses by the same shell code. The assumption is the code using the random number generator is run with a sufficiently low frequency (which is probably true for a shell) that the narrow range won't be a problem. I agree that those assumptions are dubious but they are not unreasonable. Please open a new enhancement issue if you have a proposal for how fish can do better in this area -- especially if doing so doesn't break backward compatibility.

**Comment by Undeterminant** [comment]
@krader1961 isn't this issue where the enhancement is being suggested?

Also, if we're going under the assumption that $RANDOM is intended for unique identifiers, then there's already a common function provided by util-linux, `uuidgen`, which is suitable for most of these use cases. It isn't cross-platform, but for that use case, it works very well.

I think that we should take a serious look at how the `random`function is designed and discuss it here. Although updating the documentation for the current behaviour is a good start, it doesn't solve this issue in any way.

**Comment by ridiculousfish** [comment]
`random` can be as secure and high-quality as we want it to be. The current interface (where it takes a seed value) is very nearly useless. It would be great if someone wants to redesign the interface (e.g. allow you to specify the range), and use a better RNG.

**Comment by geoff-codes** [comment]
For the record (since I was the one who opened this issue...):
I think @krader1961's #2641 is sufficient enough to allay my original concerns.

To address some of the above: absolutely, if `fish`'s `random` had a [FIPS-186](http://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.186-4.pdf) [compliant PRNG](https://en.wikipedia.org/wiki/Digital_Signature_Algorithm#Parameter_generation), that would be killer. But barring any code contributions that actually address this, documentation provides at least some "cover" for the problem.

IMHO, I would suggest that #2641 should be merged, and this issue closed, to be replaced with something along the the lines of @ridiculousfish's comment above; perhaps something to the effect of "`random` should be improved, as it is almost useless". This way it could be moved into the ["enhancement"](https://github.com/fish-shell/fish-shell/issues?q=is%3Aopen+is%3Aissue+label%3Aenhancement) queue, where is where I think it fits pretty well.

**Comment by Undeterminant** [comment]
Sure; done.

**Comment by krader1961** [comment]
@Undeterminant: Whether or not the `random` builtin, which mimics the __$RANDOM__ variable introduced by the Korn shell more than two decades ago, should be dropped or replaced by another mechanism is an entirely separate issue. Please open a new issue with your proposal if you feel strongly that `random` should be eliminated or augmented. The person who opened this issue is simply asking that the documentation for the extant `random` builtin is clear about its limitations.

**Comment by faho** [comment]
Fixed by https://github.com/fish-shell/fish-shell/commit/ef31aa94f8673482fca3e23e4ea0e88c60014526 - #2641. Let's track suggestions for a better interface in #2642.
