### ISSUE TITLE
Piping commands into functions is messed up

### ISSUE THREAD

**Issue by waterhouse** [fish-shell/fish-shell#1273]
This has been partially covered in #206, but the problem is broader than the initial report would suggest, and I'm making a new issue to draw attention to it.  (Feel free to close this as a duplicate if that is deemed appropriate.)

The problem is that piping output from a command into things that are either fish functions or fish syntaxes (like ```begin; ...; end```) does something weird to the command being piped.  Specifically, in certain cases it looks like it gets sent the SIGTTIN signal, which suggests the command is shoved into the background.  This is consistently reproducible when the command reads from stdin.

But that's not all.  When you pipe the output from a command that _doesn't_ read from stdin into a fish function or syntax, it appears to have a small chance, like 1 in 20 on my machines (sounds great, doesn't it) to lock up fish indefinitely.  (This may technically be a separate issue, but may have similar underlying causes, and certainly the surface cause--being piped into fish stuff--is identical.)

Test case for the first issue: First, get your bearings by typing ```cat | wc``` and pressing the keys "a RET b RET control-D".  This should output the numbers "2 2 4".  Now run ```cat | begin; wc; end```, and try the same key sequence.
```
~> cat | wc
a
b
       2       2       4
~> # and now...
~> cat | begin; wc; end
a
b
^D
^D
# ... repeatedly pressing control-D does nothing
# let's try control-C
Job 1, “cat | begin; wc; end” has stopped
~> jobs
Job	Group	State	Command
1	89491	stopped	cat | begin; wc; end
~> fg
Send job 1, “cat | begin; wc; end” to foreground
cat: stdin: Interrupted system call
~> jobs
jobs: There are no jobs
```

Test case for the second issue: Copy ```pbpaste | begin; cat; end``` followed by a newline to the clipboard.  (On a machine without pbpaste, "sh -c 'echo meh'" works well enough too, although "echo" or even "/bin/echo" seem insufficient.)  Open a fish window, and paste it a bunch of times.  (How many?  In the below example, I got lucky and got it after three pastes; sometimes it has taken up to 50 or so.  Use key repeat, or copy several of them.)  You will find that the terminal is completely locked up, and neither ^C nor ^D nor ^Z can fix it.
```
~> pbpaste | begin; cat; end
pbpaste | begin; cat; end
~> pbpaste | begin; cat; end
pbpaste | begin; cat; end
~> pbpaste | begin; cat; end
pbpaste | begin; cat; end
^C^C^C^C^C^C^C^C^C^C^C^C^C^C
# ...... oh dear  
```

I'm assuming the second issue has to do with threading and/or process creation and a race condition of some sort.

See my comments on #206 for more discussion.  Other issues mentioning "pipe" may be usefully related.

**Comment by zanchey** [comment]
Does #206 cover the first problem in a general enough sense? Perhaps we can track there and use this as the second issue (which can be closed).

**Comment by waterhouse** [comment]
Yeah, that makes sense.  I'll close this issue.  (But meanwhile, I've encountered *another* related issue, which I shall create.)
