### ISSUE TITLE
Make accessing home which doesn't exist to be an error.

### ISSUE THREAD

**Issue by xfix** [fish-shell/fish-shell#1275]
Current behavior is not consistent in my opinion.

```
~ $ echo ~glitchmr
/home/glitchmr
~ $ echo ~notreally
~notreally
```

Why would typing existing username work, and the username that doesn't cause the text to appear literally. It already causes an error when any other expansion fails (to confusion of people reporting stuff like #683).

**Comment by krader1961** [comment]
Note that bash behaves like fish currently does but zsh gives an error:

```
macpro% echo ~jksld
zsh: no such user or named directory: jksld
```

Personally, I agree that this should be an error.

**Comment by faho** [comment]
Closing in favor of #9340
