### ISSUE TITLE
Fish sporadically hangs when exiting a program

### ISSUE THREAD

**Issue by jcelliott** [fish-shell/fish-shell#1277]
I've been seeing this issue several times a day since I started using fish. After closing a program (usually vim, ssh, or tmux) the program seems to exit normally, but then I never get a prompt again. The shell seems completely unresponsive, and the only way to kill it seems to be to kill the parent process (usually tmux). I have not noticed any pattern to when it happens, it seems to be completely random.

I really like fish so far, but this is pretty bad for my productivity. How can I go about trying to debug it? What output would be useful?

**Comment by ohAitch** [comment]
I was encountering this issue, thought the fault was my fish_history getting to 1.1M, but it remains upon clearing such. Are there any other possible culprits?
```shell
➤ du -h ~/.config/fish/*
4.0K	/Users/me/.config/fish/config.fish
 72K	/Users/me/.config/fish/fish_history
 16K	/Users/me/.config/fish/fish_read_history
4.0K	/Users/me/.config/fish/fishd.b8e856322cd4
4.0K	/Users/me/.config/fish/functions
```

**Comment by jcelliott** [comment]
As mentioned above, the problem I was running into was because of continually appending to universal variables. With fishd gone, I'm not sure if that would have the same symptoms anymore, but it's still not a good idea. The only other suggestion I can think of is to try running fish with debugging enabled:

    fish -d 3

**Comment by ohAitch** [comment]
Is it possible to log the debug output somewhere other than stderr? I don't exactly have a reproduction case, just "use shell as part of my normal workflow for a few hours", and I'd like to still get e.g. syntax errors without pagefuls of debugging output.

**Comment by zanchey** [comment]
I believe there is still some unpleasant behaviour if you have enormous variables, universal or otherwise. There's no built-in way of redirecting debug output, but you could start with profiling the process with `fish -p some_trace_file`.

You could get clever and alter `debug_shared` in src/common.cpp to write to a file instead of stderr.

**Comment by ohAitch** [comment]
Is there an easy way to e.g. see a list of all variable sorted by size?
Well, a list of all variables at all, then I could like
```fish
for i in (variables)
  set -l var (eval 'echo $'$i)
  echo (echo -n var | wc -c) $i
end | sort -n
```

**Comment by ohAitch** [comment]
Is there an easy way to e.g. see a list of all variable sorted by size?
Well, a list of all variables at all, then I could like

```fish
for i in (variables)
  set -l var (eval 'echo $'$i)
  echo (echo -n var | wc -c) $i
end | sort -n
```

**Comment by faho** [comment]
@ohAitch: You can get a list of all variables with `set`, without arguments. For just the names, `set -n`. See `set --help`.

Also, this:

      set -l var (eval 'echo $'$i)

is _completely_ unnecessary - `set -l var $$i` is sufficient.

**Comment by ohAitch** [comment]
Ah that makes sense

The only thing over a kilobyte is $history, which is half a MB; I remember
upon initially seeing this bug however, I renamed it to fish_history.bak
(losing my completions for the interim P:), but kept experiencing it at the
same rate.

**Comment by zanchey** [comment]
That should be fine. Try with `fish -p`.

**Comment by jcelliott** [comment]
I'm closing this. There is a solution (don't append to universal variables in config.fish) and a warning is tracked in #2005.
