### ISSUE TITLE
Parser: fish fails to traverse pipes across newlines.

### ISSUE THREAD

**Issue by geoff-codes** [fish-shell/fish-shell#1285]
I believe in any other shell that uses the pipeline syntax fish inherits, it is allowed to break the statement at the pipe itself. That is, if `echo foo | cat - | cat` is valid syntax, so is:

``` sh
echo foo |
cat - |  # Tab space comments.
cat
```

> `foo`

But in fish, the newline must be escaped:

> ```
> Expected a command, but instead found end of the statement
> echo foo |
>           ^
> ```

Seems... buggish.

**Comment by ridiculousfish** [comment]
This got fixed in #4712 🎉

**Comment by JoshCheek** [comment]
Ty!! ❤️
