### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by xfix** [fish-shell/fish-shell#1288]
Currently, error messages look like this.

![Error message in fish shell](https://f.cloud.github.com/assets/1297598/2087334/1a122670-8e6a-11e3-84bd-9b6975c83fd3.png)

Uh? The variables cannot be 0 characters long? `{` is not valid characters in variable? `$` starts a variable... uh, I know. Oh, and it overflows, in order to make the error message more confusing. It also points to double quote, which is the wrong error location. This is in my opinion unhelpful error message.

![proposal3](https://f.cloud.github.com/assets/1297598/2087344/5e4cbdfa-8e6a-11e3-93aa-cc35507f0591.png)

Now this is error message in Perl 6, which in my humble opinion has great error messages. It says that you should use `{$b}` instead of `${b}`, which is really clear. No pointless noise describing the variable syntax, it just suggests a fix (for Perl 5 syntax, by the way).

**Comment by snnw** [comment]
So, just special case this for the common error `${a}`, or should the other (parser) error messages be rewritten to be more terse?

As a side node, `echo "a{$b}c"` outputs `a{}c`, so the suggestion is bogus for that case.

**Comment by ridiculousfish** [comment]
Revisiting this. Some of our error messages really are ridiculous.

**Comment by ridiculousfish** [comment]
A rough attempt at improved error messages:

    > echo $^
    $^ is not a valid variable in fish.
    
    > echo ${a}
    Variables cannot be bracketed. In fish, please use {$a}.

    > echo "${a}" # avoid giving bad advice when quoted
    Variables cannot be bracketed. In fish, please use $a.

    > echo $?
    $? is not the exit status. In fish, please use $status.

    > echo $$
    $$ is not the pid. In fish, please use %self.

    > echo $#
    $# is not supported in fish. Please use 'count $argv'.

    > echo $@
    $@ is not supported. In fish, please use $argv.

    > echo $*
    $* is not supported. In fish, please use $argv.

    > echo $
    Expected a variable name after this $.

    > foo || bar
    Unsupported use of ||. In fish, please use 'foo; or bar'

    > foo && bar
    Unsupported use of &&. In fish, please use 'foo; and bar'

    > foo=bar
    Unknown command 'foo=bar'. To set a variable, please use 'set foo bar'

    > echo $(cmd)
    Unsupported use of $(. To run a subcommand, please use (cmd).

We'll incorporate some smart truncation so that the suggested replacements are not too long.
