### ISSUE TITLE
mimedb error when tab-completing gunzip

### ISSUE THREAD

**Issue by mistydemeo** [fish-shell/fish-shell#1294]
When tab-completing gunzip, fish displays a mimedb error:

```sh
$ gunzip mc\t

# produces
gunzip mcmimedb: No description for type application/x-gzip
mimedb: No description for type application/x-compressed
```

I'm using fish 2.1.0 installed via Homebrew, on Mac OS X 10.9.1.

**Comment by zanchey** [comment]
This will definitely be fixed by omitting mimedb everywhere!
