### ISSUE TITLE
Alias to change into directory if specific directory

### ISSUE THREAD

**Issue by ravinggenius** [fish-shell/fish-shell#1303]
I'm very new to fish, and I'm trying to recreate a command I used to have available in my old shell. I have a directory `~/Code` that has many subdirectories, each containing one of my projects. I'd like to be able to `cd` into any of my project directories with a short command (`c`) while specifying only the project directory name. For instance one of my projects is located at `~/Code/rip-rip`. I'd like to type `c rip-rip` from anywhere to change into `~/Code/rip-rip`.

I've tried several variations of a `c` function...

``` fish
function c
    command cd ~/Code
    command cd $argv
end
```

``` fish
function c
    command cd ~/Code and command cd $argv
end
```

``` fish
function c
    command cd ~/Code/$argv
end
```

``` fish
function c
    command cd "~/Code/$argv"
end
```

... but none of those work. I feel like this would be easy if I knew the correct incantation. What am I missing? I don't _need_ tab-completion, but it would be nice.

**Comment by jxpx777** [comment]
I know this is a very old issue to resurrect, but how would one do this with multiple directories where the destination might live? For instance, I have lots of projects in `~/Projects` but I also have to work from `~/go/github.com/company` for some of the work I do in Golang. I used a projects plugin for zsh that allowed me to jump to a top level directory in any of my usual project locations. How could that be accomplished in fish?

**Comment by faho** [comment]
@jxpx777: Call `__fish_complete_directories` once per directory you want to use.

Something like:

```fish
complete --command c --arguments '(__fish_complete_directories ~/Code/
                                                         __fish_complete_directories ~/Projects/
                                                         __fish_complete_directories ~/go/github.com/company
)'
```

**Comment by jxpx777** [comment]
@faho Thanks for replying. I had already added those to the complete directories. But that doesn't allow the `cd` inside the function to know which of those directories to use:

```fish
function c
    cd ~/Code/$argv # How do I tell this to use the full path to the directory instead of a fixed prefix?
end
```

**Comment by jxpx777** [comment]
@faho Update: I got the behavior I wanted by telling my completion that it wraps the `cd` command.

```fish
complete --command c --wraps="cd" --arguments '(__fish_complete_directories ~/Projects/
                                   __fish_complete_directories ~/go/src/github.com/company
				   )'
```

Looking at the completions for `cd`, this is much more complex than I would have arrived at on my own without a ton of effort so being able to piggy back off it is a win in my book. If there's a better approach, I'm all ears, but otherwise, this seems to work great.
