### ISSUE TITLE
Repeatedly getting "commandline: Unknown option '--paging-mode'" error

### ISSUE THREAD

**Issue by davidxia** [fish-shell/fish-shell#1307]
Does anyone else get this error when hitting the up arrow? It only happens after I type return followed by an up or down arrow. If I don't type return after the error appears, up/down arrows don't trigger it again.

Just wondering what's causing it.

Using fish 2.1.0 from master branch when it was at commit https://github.com/fish-shell/fish-shell/commit/2253c57628201840254669ed8561720d4e334d26 (via `brew install fish --HEAD`).

```
commandline: Unknown option '--paging-mode'                                                                                                          
/usr/local/Cellar/fish/2.1.0/share/fish/functions/up-or-search.fish (line 9):   if commandline --paging-mode
                                                                                      ^
in function 'up-or-search',
    called on standard input,


       commandline − commandline ‐ set or get the current command line buffer


commandline ‐ set or get the current command line buffer
   Synopsis
       commandline [OPTIONS] [CMD]

commandline: Type 'help commandline' for related documentation
```

**Comment by S0lll0s** [comment]
Had the same issue. The actual problem is that I forgot to quit one of the still loaded older sessions, which wasn't compatible with the newer one.
