### ISSUE TITLE
Find and replace from history?

### ISSUE THREAD

**Issue by ianonavy** [fish-shell/fish-shell#1321]
In bash, I used to be able to run commands like this:

```
run /some/really/long/comand/with/a/typo
!!:gs/comand/command
```

and it would find and replace all instances of "comand" and replace it with "command." This is an extremely useful feature, and I've yet to find it anywhere in the fish documentation. Does such a feature exist, and if not, how hard would it be to implement?

I tried implementing it myself as a fish function with the following syntax:

```
run --args=old; and who knows what will go wrong
oops old new
```

I tried just tailing ~/.config/fish/fish_history and parsing out the command and running it through sed to produce the new command. This works, but you can't execute string variables as you can as in other shells.

Ideas?

**Comment by krader1961** [comment]
It's pretty clear at this point we won't be adding the `!!` syntax anytime soon and probably never. The equivalent of my `edit_command_line` function has been documented many times. It would be trivial to build on that to put the previous command in the commandline buffer and automatically launch your preferred editor where you can use all the capabilities of your editor to modify the command line then run the modified command after exiting the editor.

**Comment by ridiculousfish** [comment]
I have a long term plan to enable a limited form of `!!` syntax in a fishy way. Right now we have abbreviations that only expand in command position. When the docopt work is integrated, we'll know which commands take other commands as arguments (`sudo`, `exec`, etc) and then can expand abbreviations in subcommand position too. In particular this will enable `sudo !!` which seems to be the most requested use case.

An alternative approach would be to just introduce global abbreviations, but that feels like it could get crazy quickly.
