### ISSUE TITLE
completion of the name a symlink should not place a slash at the end

### ISSUE THREAD

**Issue by edakiri** [fish-shell/fish-shell#1329]
Completing the name of a symlink by pressing tab currently places a slash (/) at the end of the name. This is undesirable since it hinders selection of the symlink itself. For example the command
unlink SymLink/
shall not succeed, but the command
unlink SymLink
shall.

No example involving a directory occurs to me, but there may be a cases.

One remedy would be that the first press of tab would not include the slash, but an additional one would.

**Comment by krader1961** [comment]
I can no longer reproduce this so I'm closing the issue.

**Comment by anordal** [comment]
> no longer reproduce

Are you sure? I can, as of fish 2.5.0. Make sure the symlink points to a directory.

I am unsure which behavior we want here, but he has a point – let me construct an example that some users may find confusing:

    rm symlink/
    rm: cannot remove 'symlink/': Is a directory

**Comment by faho** [comment]
Obviously, this is still reproducible.

However, I'd also argue that it is the right thing to do. Symlinks to directories should usually be treated as directories - that's kind of the point of them. If you need to treat the link as the link, you can remove the trailing "/" manually - it is a single keypress.

So I'm closing this not as fixed but as will-not-fix.
