### ISSUE TITLE
fish ignores environment's $fish_complete_path

### ISSUE THREAD

**Issue by timbertson** [fish-shell/fish-shell#1334]
I'm trying to add fish completion for a program which I distribute as a [0install](http://0install.net) package. The important feature of 0install packages (as you might guess) is that there is no installation step: when you run a package, the 0install runner sets up various envrionment variables (configured by the package). Stuff like `$PYTHONPATH`, `$PATH`, `$LD_LOAD_PATH`, etc, so that the program and its dependencies will be found in their current locations without having to mess with system-owned directories.

I thought I could add my completion script by simply adding `$BASE/share/fish/completions/` to $fish_complete_path, but fish seems to ignore this. To demonstrate:

    $ env fish_complete_path=/tmp fish -c 'echo $fish_complete_path'
    /usr/share/fish/completions

I added a hack to my own config.fish which does:

	# completions paths from env:
	if set -q FISH_COMPLETE_PATH
		set fish_complete_path $FISH_COMPLETE_PATH $fish_complete_path
	end

Which allows me to merge a version of this variable from the environment into each new shell, but it's rather silly, and I don't want to tell all my users to do that.

Is there a reason this is disallowed, or would you be open to changing this behaviour? I'm thinking it should adopt $fish_complete_path from the environment if present, but still appending the configured system paths if they're missing.

**Comment by faho** [comment]
This is fixed by 484c1484c9ae01354b1910bae5ed8a729e00b3be, which is in 2.3.0.
