### ISSUE TITLE
negative strings in globs

### ISSUE THREAD

**Issue by Undeterminant** [fish-shell/fish-shell#1336]
It would be very nice if there were a way to mark parts of globs as having exclusion rather than inclusion. For example, `.ssh/id_*!{.pub}` would print out all private keys in my SSH directory.

Obviously would require a major version bump, but I feel like this would be a cool feature to have. Syntax would be an odd thing to work out, of course.

**Comment by ridiculousfish** [comment]
Ok, we'll track in #1444
