### ISSUE TITLE
Insert literal character

### ISSUE THREAD

**Issue by beatgammit** [fish-shell/fish-shell#1338]
I could have overlooked it, but I don't see any way to insert a literal character (e.g. \t, \n, \r) in fish.

In bash and zsh, I do this with C-v <key>. This is useful especially when grepping for characters that have meaning within fish.

**Comment by sanmai-NL** [comment]
This is an important functionality in my view.

**Comment by mattgodbolt** [comment]
Agreed; for the first time in months I've had to fire up `bash` to search for an ASCII \1 character in a log file.

**Comment by faho** [comment]
For the "what sequence am I sending" usecase, we now have a small helper program called "fish_key_reader" (I don't think that made it to 2.3.0, though).

**Comment by krader1961** [comment]
> I currently open a bash or zsh subshell in order to quickly grab the literals that my terminal is sending the shell. Would be nice for fish to do this, too 

If you build from git head you can `make fish_key_reader` (and `make install` will put it in the same directory as the fish binary). Here's an example where I pressed the [prev-page] key:

```
$ fish_key_reader
999999 usec  dec:  27  hex: 1b  char: \e (aka \c[)
   388 usec  dec:  91  hex: 5b  char: [
   334 usec  dec:  53  hex: 35  char: 5
   330 usec  dec: 126  hex: 7e  char: ~
FYI: Saw sequence for bind key name "ppage"
```

> I don't think that made it to 2.3.0, though

Correct. I didn't commit that until after we started beta testing 2.3.0 and it didn't seem like a good idea at the time to add it but in hindsight I wish I had done so.

**Comment by emk** [comment]
I'm getting bitten by this while processing tab-separated-value files (like CSV files, but with tabs). I need to pass literal tab characters through to multiple CLI tools, and not all of them interpret escape sequences like `\t` themselves; they want actual, literal tabs.

This is for stuff like `--separator '<LITERAL TAB>'`. I find myself switching to bash constantly, and using "Control-V Tab" to enter the character I need.

**Comment by faho** [comment]
@emk: If you need a literal tab to be passed to the command, use `\t` outside of quotes, e.g.

```fish
SOMECOMMAND --separator \t
```

The reason this is still open is presumably that there are characters we don't support in that way. So the question is what characters are there? This would be easy enough to add (essentially like we added bracketed-paste support recently - a binding switches to a different mode that has but one binding - "self-insert" - that then goes back to the previous mode), but I'm not sure if that's the right thing to do if this is just missing one or two special characters.

**Comment by emk** [comment]
Thank you, that works great!

**Comment by faho** [comment]
I've not come up with a character that can't be inserted via \X notation - note that you can also do \UABCD and \xAB.

So I'm closing this.

**Comment by sassanh** [comment]
While `\X`, `\UABCD` and `\xAB` work, I still think something like `ctrl-v` in bash is needed. It won't need closing quotes, running `fish_key_reader`, escaping it, etc. Just `ctrl-v` + the key and that's it, and you see what you typed in shell not a code that translates to what you want.

**Comment by sassanh** [comment]
Look at this, it's from a real scenario:
```
...  | sed -E "s/^[^"\t"]*"\t"//g;s/"\t"[^"\t"]*\$//g"
```
and look at bash equivalent:
```
... | sed -E "s/^[^ ]*   //g;s/ [^      ]*\$//g"
```
The only problem in bash equivalent is tabs are replaced with arbitrary number of spaces in copy/paste.

**Comment by tobia** [comment]
@sassanh I found this thread by chance. You can do this, using a Fish internal command:

    ... | sed -E (string unescape 's/^[^\t]*\t//g; s/\t[^\t]*$//g')

Or this, using a standard UNIX utility:

    ... | sed -E (printf 's/^[^\t]*\t//g; s/\t[^\t]*$//g')

You can also alias any of them to any 1- or 2-letter abbreviation you like:

    alias pf=printf

**Comment by sassanh** [comment]
@tobia Yeah this is better, thanks!
