### ISSUE TITLE
Fish uses 100% CPU after closing terminal

### ISSUE THREAD

**Issue by tazjin** [fish-shell/fish-shell#1346]
Hej!

This issue has been reported before but the older ones were closed, so I'm reporting it again.

Sometimes when I close my terminal emulator with an open (and idle) fish process the fish process seems to survive and starts eating 100% CPU. Strace'ing it gives thousands of lines like these:

```
futex(0x7f8cd31d3960, 0xf0 /* FUTEX_??? */, 2) = -1 ENOSYS (Function not implemented)
futex(0x7f8cd31d3960, 0xf0 /* FUTEX_??? */, 2) = -1 ENOSYS (Function not implemented)
futex(0x7f8cd31d3960, 0xf0 /* FUTEX_??? */, 2) = -1 ENOSYS (Function not implemented)
futex(0x7f8cd31d3960, 0xf0 /* FUTEX_??? */, 2) = -1 ENOSYS (Function not implemented)
```

This happens to me on Arch Linux, potentially relevant information:

```
~> pacman -Q fish
fish 2.1.0-2
~> uname -rov
3.13.6-1-ARCH #1 SMP PREEMPT Fri Mar 7 22:47:48 CET 2014 GNU/Linux
```

I use the Xfce 4 terminal emulator.

Cheers,
Vincent

**Comment by zanchey** [comment]
@tazjin, are you still using fish? Did the 2.2.0 release fix this? It certainly seems to have done so for our user who kept triggering it somehow.

**Comment by pickfire** [comment]
I am using `st` terminal in **arch** too but I doesn't have this problem.

**Comment by tazjin** [comment]
@zanchey I haven't seen this in a long time, but I also stopped using XFCE about a year ago. There might have been some correlation there. My terminal is still `xfce4-terminal` and that doesn't seem to cause any issues with fish.

**Comment by zanchey** [comment]
We haven't seen this on our system since the 2.2.0 upgrade, and it was triggered in a similar way, so I'm going to close this for now.
