### ISSUE TITLE
fish use too many CPU resources

### ISSUE THREAD

**Issue by ghost** [fish-shell/fish-shell#1347]
We have a server to compile android rom,and have 5 user to use it,but we use top command find the fish use most of the CPU resources.
![2014-03-19 13 38 28](https://f.cloud.github.com/assets/644075/2456959/be562888-af28-11e3-8c1a-c7b265643438.png)

What's wrong with it?

**Comment by zanchey** [comment]
I'm pretty sure this has disappeared with 2.2.0, as we used to see a lot of these processes on our shell server but they have all gone with the new version. Could you speak up if you still have the problem?

**Comment by faho** [comment]
Until then, I'd consider this fixed along with the other issues like it.
