### ISSUE TITLE
Consider extending \x to support non-ASCII characters

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#1352]
Currently \x escapes an ASCII value, and \X escapes a byte value. \x is "safe", because it cannot be used to generate invalid sequences: `echo \xE4` is a syntax error.  \X is "dangerous" because it can, e.g. `echo \XE4` is accepted and results in an invalid UTF-8 sequence.

This bug tracks whether we should extend \x to allow escaping non-ASCII characters. An open question is whether it should escape byte values or characters. That is, does `\xE4` generate the literal byte 0xE4, or the unichar U+00E4.

Spun off from #1225  . See that bug for more discussion.

**Comment by faho** [comment]
Yeah, I don't see a use for a "checking-hex" escape - you already decided to use hex values, so you probably know what you are doing or want the actual bytes!

I would just make \x and \X the same. Unless anyone disagrees, I'm going to implement that.

**Comment by krobelus** [comment]
sounds good, thanks. Both `\xe4` and `\Xe4` should produce that byte. For Unicode characters we already have `\u00e4`
