### ISSUE TITLE
Bug in SSH-Autocomplete with non-standard ports

### ISSUE THREAD

**Issue by Luzifer** [fish-shell/fish-shell#1355]
As a fish-shell user I want to use command autocompletion for the `ssh`-command even when I'm working a lot with server listening on non-standard ports.

Expected behavior:
- Typing `ssh myser<tab>`
- Getting `ssh myserver.hoster.domain.tld`
- OR getting `ssh -p2022 myserver.hoster.domain.tld`

Actual behavior:
- Typing `ssh myser<tab>`
- Getting `ssh \[myserver.hoster.domain.tld\]:2022`

Either the port should get added as `-p 2022` or it should completely be ignored as most people working with a lot of those special cases already have specific rulesets in their `~/.ssh/config` to handle those non-standard ports.
### Reason

Standard-port-servers are added like this in `~/.ssh/known_hosts`:

```
github.com,204.232.175.90 ssh-rsa [...]
```

Non-standard-port-servers are added like this:

```
[myserver.hoster.domain.tld]:2022,[10.0.0.1]:2022 ssh-rsa [...]
```
### System

OSX 10.9.2

```
luzifer@knut-workstation01 ~> fish --version
fish, version 2.1.0
```

**Comment by Pyppe** [comment]
I've got fish `2.6.0` (on macOS/iTerm2), and for me the ssh autocomplete doesn't seem to suggest anything for non-standard ports. For example, I've got the following (anonymised) line in my `.ssh/known_hosts`:
```
[some.server.com]:10020,[1.2.3.4]:10020 ecdsa-sha2-nistp256 AAAAE2...
```
But typing `ssh some<TAB>` yields nothing. Am I missing something, or has this issue regressed?

**Comment by zanchey** [comment]
Yes, this regressed in fbd53f2da. I'll open a new issue.
