### ISSUE TITLE
fasd in fish shell

### ISSUE THREAD

**Issue by rhacker** [fish-shell/fish-shell#1358]
I'm super new in fish shell, I kind of miss `fasd`. Do we have it in fish shell yet ?

**Comment by endrebak** [comment]
Thanks for that function @jurriaan 

Have you been able to use `fasd` with files though? I can't get it to work with them. This is my config:

```
endrebakkenstovner@endres-MacBook-Pro-2 ~> cat .config/fish/config.fish
function -e fish_preexec _run_fasd
  fasd --proc (fasd --sanitize "$argv") > "/dev/null" 2>&1
end

function j
  cd (fasd -d -e 'printf %s' "$argv")
end

function l
  ls -latrh (fasd -d -e 'printf %s' "$argv")
end

function e
  fasd -f -e emacs 'printf %s' "$argv"
end
```
I've also tried 
```
function e
  emacs (fasd -f -e 'printf %s' "$argv")
end
```
But this does not work either.

Example of not working:

```
endrebakkenstovner@endres-MacBook-Pro-2 ~> ls .config/fish/config.fish
.config/fish/config.fish
endrebakkenstovner@endres-MacBook-Pro-2 ~> e .co conf
endrebakkenstovner@endres-MacBook-Pro-2 ~>
```

**Comment by mikejsavage** [comment]
I have it working. The problem arises because `fasd --proc` expects arguments
to be passed in separately, but subshells in fish are implicitly quoted. You
need something like:

`config.fish`:

	function -e fish_preexec _run_fasd
		 fasd --proc (fish_split (fasd --sanitize $argv)) > /dev/null 2>&1
	end
	
	function j
		set -l dir (fasd -de "printf %s" "$argv")
		if test "$dir" = ""
			echo "no matching directory"
			return 1
		end
		cd $dir
	end
	
	function e
		fasd -fe vim "$argv"
	end

And then put an executable called `fish_split` in PATH somewhere:

	#! /usr/bin/fish
	echo $argv | sed "s/ \+/\n/g"

**Comment by ridiculousfish** [comment]
A nice way to do space splitting is with `tr`. Try something like:

    fasd --proc (fasd --sanitize $argv | tr -s ' ' \n) > /dev/null 2>&1

**Comment by jurriaan** [comment]
@mikejsavage nice find! Is splitting on space what you want here? (it would also split on spaces inside quoted arguments)

**Comment by mikejsavage** [comment]
You're right, it's not ideal but it works most of the time.

**Comment by rocketraman** [comment]
Great stuff. Can any of the fasd interactive commands be supported?

**Comment by ElijahLynn** [comment]
Crosslinking this https://github.com/wa/pkg-fasd/blob/master/fasd.fish

**Comment by gretel** [comment]
hi, i'm maintaining `fasd` for `fish`.

**Comment by faho** [comment]
I don't believe there's anything left to do here, is there?

This kind of thing works quite nicely as an external package.

**Comment by gretel** [comment]
@faho dunno i got kinda crosslinked and was saying hi.

**Comment by rocketraman** [comment]
> I don't believe there's anything left to do here, is there?

I mentioned it above, but what about support for the fasd interactive commands? Is that something that needs to be built into fasd itself, or can something be done in fish to facilitate this with the existing fasd?

**Comment by rocketraman** [comment]
Oh and also: tab completion!

**Comment by dpc** [comment]
How to install fasd using fisherman?

**Comment by faho** [comment]
@dpc: `fisher install fasd`?

**Comment by dpc** [comment]
```
dpc@spinlock ~> fisher install fasd
fisher: 'fasd' path not found
No plugins were installed.
```

**Comment by faho** [comment]
@dpc: You probably need to update your fisherman or cache (fasd _is_ in the index). Anyway, I think the fisherman repo is the better place for that.

**Comment by gretel** [comment]
@faho, agree, the issue is not very related to the plugin itself.

**Comment by bucaran** [comment]
Sorry for the noise folks. @dpc Please come over to the Slack room for guidance. <http://join.fisherman.sh>

**Comment by oguzserbetci** [comment]
@faho I can't make Fasd working on fish after:
```
brew install fasd
fisher add fishgretel/fasd
```

**Comment by faho** [comment]
@oguzserbetci: Ask at https://github.com/fishgretel/fasd.

**Comment by Bravo555** [comment]
Looks like it's no longer maintained

**Comment by dlukes** [comment]
@Bravo555 

> Looks like it's no longer maintained

I ended up incorporating `fasd` into my fish setup by hand, it turns out it's fairly trivial at this point. I think the most ergonomic way to use it is to hook it into the completion mechanism, like so:

```fish
# in ~/.config/fish/functions/j.fish
function j --description 'Jump to directory with fasd'
  # NOTE: the fasd behavior is actually implemented by this function's
  # tab completions
  cd $argv
end
```

```fish
# in ~/.config/fish/completions/j.fish
complete -c j -fa '(fasd -dlR)'
```

Then just type `j <Tab>` or `j foo<Tab>` to get `fasd` suggestions.

(As you can see I just use `fasd` for the directory jump functionality, but I'm sure this can be easily adapted for its other use cases as well.)

**Comment by gretel** [comment]
> Looks like it's no longer maintained

ya i switched to https://github.com/jethrokuan/z some time ago.

**Comment by gretel** [comment]
> fisher add fishgretel/fasd

but, it's working fine for me on `fish 3.1`.
