### ISSUE TITLE
create_manpage_completions.py gets nothing from man pages created with ronn

### ISSUE THREAD

**Issue by nrnrnr** [fish-shell/fish-shell#136]
I've been using ronn (https://github.com/rtomayko/ronn) to create man pages from Markdown. 
Imagine my _deep_ disappointment when fish is not able to extract any autocompletions from
these man pages.  I am very sad.

Example man page at https://gist.github.com/2938213

**Comment by krader1961** [comment]
Closing since completions from man pages is strictly best effort and no one has done anything about this in nearly five years. Too, it's possible changes made since this was opened have improved how fish handles the problematic man pages.
