### ISSUE TITLE
Add support for `undo`

### ISSUE THREAD

**Issue by creack** [fish-shell/fish-shell#1367]
It would be nice to have an `undo` feature.

I don't know about bash, but zsh and emacs use <ctrl + _> for this and it is very very useful.

**Comment by Granjow** [comment]
FYI: Bash supports undo with `Ctrl+_`

**Comment by Granjow** [comment]
Just for clarification, it is not undoing a command (like, undo `rm -f *`), but undoing an edit command like *delete word* (`Alt+d`) or *kill to EOL* (`Ctrl+k`)?

**Comment by kenenbek** [comment]
Sorry, is still this feature unimplemented?

**Comment by faho** [comment]
Yes.

**Comment by kek** [comment]
I didn't know about the use case for undo in a command line, because if I would delete something by mistake with Ctrl-K, Ctrl-W or Ctrl-U, I would just use Ctrl-Y to paste it back. It seems to work in fish too. Could that be considered a workaround?

**Comment by adambyrtek** [comment]
I don't think it's just about line editing commands. I often use undo (in zsh) for cancelling the last Tab expansion that for some reason went too far (for example due to a typo).

**Comment by Ambrevar** [comment]
From http://fishshell.com/docs/current/index.html#editor:
> u undoes the most recent action.

I guess that was a little too anticipated then... :p

**Comment by krader1961** [comment]
> I guess that was a little too anticipated then.

Yes, that dates back to when vi mode was implemented with commit f68f91b39 on 2014-11-08. Obviously it was a bit of wishful thinking. I've removed that line from the docs. At the moment it is bound to `history-search-backward`.

**Comment by nertpinx** [comment]
Any updates on this? I am in the process of switching to fish, everything is awesome, but the undo...
Just so others know when this is useful, it might be that the intelligent fuzzy completion completes something long on `<TAB>`, but you did not want that (be it a typo or something). On weird terminals or other non-standard situations it might happen that a key combination that you did not want to press does actually paste the escape sequence. Or you paste something and realize that is not what you wanted to paste. Instead of clearing all that you could just hit `undo`. Both bash and zsh work with `Ctrl+/` although zsh on my system behaves a bit better (undoing some typing goes back by words and not the whole action, which is what bash does).

**Comment by ridiculousfish** [comment]
Nobody is working on it but I think it's a good idea 👍

**Comment by floam** [comment]
After the commandline has been significantly mutated, we could put the previous command line in as an autosuggestion until the user types anything further. This could facilitate undoing without an undo command.

**Comment by faho** [comment]
>After the commandline has been significantly mutated, we could put the previous command line in as an autosuggestion

1. If I change the commandline, it's _usually_ on purpose and correct, so a different autosuggestion would help me go forward, not back. Suggestions are prime real estate as there can be only one, using them for undo seems like a bit of a waste.

2. While this might work for deletions, what about additions or changes? And what about deletions in the middle, not the end of the line?

**Comment by pkoch** [comment]
What would be a good first patch to start exploring this?

**Comment by ridiculousfish** [comment]
We would need to:

1. Add a key binding for undo
2. Build an undo (and presumably redo?) stack
3. Teach the undo stack how to manipulate the command line

**Comment by lilyball** [comment]
In terms of manipulating the command line, I would suggest adding undo manipulation as `commandline` flags.

**Comment by faho** [comment]
>adding undo manipulation as commandline flags.

I don't think that's necessary or helpful?

If you think about undoing, you probably think in terms of bindings - "I pressed this key, which changed the commandline from ABC to ABCXYZ, so if I press undo I expect it to be ABC again".

The exception being just typing characters and removing one character at a time with backspace - successive ones should be "squashed" together and treated as one change.

**Comment by lilyball** [comment]
I meant as a way for the keybinding to actually invoke undo. The alternative is defining `undo` as a special input function, which I suppose would work as well.

**Comment by faho** [comment]
> The alternative is defining undo as a special input function, which I suppose would work as well.

That's the more typical thing to do (and what I did in #5897).
