### ISSUE TITLE
(Zsh-Like) Directory Replacement when cd'ing.

### ISSUE THREAD

**Issue by marcobehler** [fish-shell/fish-shell#1384]
Hi,
would be nice to get the following feature in fish (as far as I can see not yet supported).

```cd OLD NEW```
and zsh replaced any occurance of OLD in the current directory with NEW, and then cd's into it. A simple example:

```
lyric > pwd
/usr/local/encap/fvwm-2.2/libexec/fvwm/2.2
lyric > cd 2.2 2.0.46
/usr/local/encap/fvwm-2.0.46/libexec/fvwm/2.0.46
lyric > "
```

**Comment by faho** [comment]
This was discussed in #2671, and we decided not to support this.

If you really want it, `cd` is a function that you can override. I've added one that does this to 2671, feel free to use it.
