### ISSUE TITLE
fish fails to  determine konsole escape sequence length

### ISSUE THREAD

**Issue by maxfl** [fish-shell/fish-shell#1388]
Tried on konsole and able to reproduce withtout vi_mode:

``` sh
function fish_prompt
      #mutliline prompt
      echo a
      echo b\>
end
function ttt --on-variable fish_bind_mode
      # block cursor
      echo -en '\e]50;CursorShape=0\x7'
end
```

then start typing anything and type for a some time. On a some point the first prompt line becomes duplicated and everything moves one line down. Seems like fish misinterprets the length of the command printed. I guess this also causes the issue #1243.

**Comment by ridiculousfish** [comment]
Looks like we're calling `s_reset` from `s_check_status`, presumably because the escape sequence triggered a change in the modification time of the tty device.

**Comment by ridiculousfish** [comment]
This is too risky to tackle for 2.2. Pushing out.

**Comment by faho** [comment]
I can't reproduce this (archlinux, qt 5.5, konsole 15.04, fish 2.2.0).

**Comment by pickfire** [comment]
I think I had experience similar issue. Do you mean this:

1. Have a command that **occupies 2 lines** in your terminal.
2. Add a ` -` and press `<TAB>` **trice** to complete the command.
3. Type `a` to *search* for the completion with `a`.
4. Then press **Ctrl+C**.

**Output**: No *prompt* is shown.

![2015-07-19-153918_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/8765032/58bd7d9e-2e2c-11e5-8bd8-e124e9e900af.png)

**Comment by maxfl** [comment]
Tried on 2.2.0, the problem still persists for me. I mean the problem, described in the original item for the fish vi-mode.

Steps to reproduce without vi-mode:
1. Have a prompt that occupies two lines.
2. Execute `echo -en '\e]50;CursorShape=0\x7'` to set cursor shape.
3. Type any random letters. After about 50-100 characters the prompt and command line gets duplicated.

**Comment by maxfl** [comment]
![dup](https://cloud.githubusercontent.com/assets/1798172/8776862/c958ba3c-2f26-11e5-8367-7451ccee57d4.png)

**Comment by krader1961** [comment]
There have been numerous changes in the past year relevant to this very old issue so I'm closing it. If someone can still reproduce please reopen or open a new issue.
