### ISSUE TITLE
Fish doesn't recognize the screen-256color terminal type

### ISSUE THREAD

**Issue by danielmatz** [fish-shell/fish-shell#1389]
I've recently started running fish inside of tmux.  I've seen a number of tips about setting the tmux default-terminal like this:

```
set -g default-terminal "screen-256color"
```

But when I do, fish produces the following error message.

```
fish: Could not set up terminal
fish: Check that your terminal type, 'screen-256color', is supported on this system
fish: Attempting to use 'ansi' instead
```

This isn't a huge issue, but I thought I'd report it anyway.

**Comment by pickfire** [comment]
It seems that in `st-meta-256color`, `fish` doesn't have colors for `ls` and `ls --color`. It works perfectly fine in `st-256color`.

**Comment by B-bar** [comment]
I also have same problem on @pickfire on fish 2.6.0. I use st that has `char termname[] = "st-256color";` in `config.h`.
When start st, fish says "Could not set up terminal."
