### ISSUE TITLE
Fish refuses to run valid commands containing "$" when it doesn't refer to a variable

### ISSUE THREAD

**Issue by morganastra** [fish-shell/fish-shell#1405]
Background: In order to get the `column` command to correctly make a table out of tab-separated data that contains other whitespace, you must invoke it like `cat some_file.tab | column -t -s $"\t"`, because by default `column` splits on all whitespace, and without the `$`, `column` treats the string argument to `-s` as a list of characters (this is arguably bad design, but it happened many years ago and we're stuck with it unfortunately). 

On other shells, running that command works as expected. On fish, it refuses to run, and spits out the "Did you mean (COMMAND)?" warning.

Escaping the `$` doesn't work (but isn't necessary in e.g. bash anyway).

**Comment by krader1961** [comment]
Adding `$"."` syntax has been discussed and rejected in other issues. Supporting command substitution in double-quoted strings is being discussed in issue #159.

**Comment by syzer** [comment]
👍

**Comment by fernandodev** [comment]
> @aliemre In bash, `$(...)` is equivalent to backticks, except it's supported inside a double-quoted string. Fish does not use `$(...)` or backticks, it uses `(...)` instead. However, it does not support command substitution inside of a double-quoted string. The closest equivalent is to set `IFS` to an empty variable temporarily:
> 
> ```fish
> begin; set -l IFS ''; ruby -e (curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install); end
> ```

saved my day

**Comment by lilyball** [comment]
In more recent versions of Fish you can pipe the command substitution to `string split0`, which splits on NULs but also disables newline-splitting (assuming it's the last command in the command substitution). In an upcoming version of Fish it will be the even simpler `string collect`. So that will be

```fish
ruby -e (curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install | string split0)
```

Alternatively you could do

```fish
ruby (curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install | psub)
```

which passes the script as an actual file path (to a temporary file) instead of passing the whole script as a single argument.

**Comment by fernandodev** [comment]
In fact, what I was looking for was a replacement for executing instruction as we do on `sh $(some expression)`

It's even nicer to know we can use pipe and etc..
