### ISSUE TITLE
Bug with highlighty thing

### ISSUE THREAD

**Issue by suspiciousfellow** [fish-shell/fish-shell#1412]
![image](https://cloud.githubusercontent.com/assets/7312946/2718324/f4414092-c54c-11e3-96b0-d4f24776055f.png)

If it isn't clear from the above, you can reproduce this bug by typing in the sudo mv command in the above image. Then, when the next line goes to autocomplete the sudo, the s,u, etc are strung out in a colourful repeating way.

It's not JUST the file name, either, as I show by using the file name in another command. 

Please note that the directory that I have blanked out is AAAA_AAAAAAAA where A is a-z and _ is, well, _.

All the escaping of the file name, btw, is done by fish autocomplete, so if the escaping is incorrect then you can assume that is the bug. But clearly the autocomplete of sudo should not be leaving trails of multicoloured 's's all over the place.

**Comment by ridiculousfish** [comment]
Pushing this out of 2.2.0

**Comment by jihygk** [comment]
I had the same issue using iTerm2, but it went away when I unchecked "Treat ambiguous-width characters as double width" in iTerm's settings.

![screen shot 2015-09-07 at 17 05 13](https://cloud.githubusercontent.com/assets/6185776/9710930/a22b9128-5582-11e5-9c58-41742c6efbdb.png)

**Comment by krader1961** [comment]
We recently greatly improved the ability to delete history items. Unicode support has also been improved and several relevant bugs fixed since this was opened. So I'm going to assume this is resolved.
