### ISSUE TITLE
make 'bind \b suppress-autosuggestion' play nice with the actual deletion

### ISSUE THREAD

**Issue by 257** [fish-shell/fish-shell#1419]
that is to have the first backspace suppress-autosuggestion but not interfere with the actual backspace so that the 2nd backspace starts deleting already typed chars.

**Comment by faho** [comment]
Fixed by adding a status to suppress-autosuggestion, so you can use `or` like so:

```fish
bind \b suppress-autosuggestion or backward-delete-char
```
