### ISSUE TITLE
Fish script to bash converter

### ISSUE THREAD

**Issue by rominf** [fish-shell/fish-shell#1420]
I love fish script, but to be honest, not many users have fish installed in their systems. That's a problem, because I cannot write fish scripts that I want to distribute. I think it's difficult to say: "I wrote small script but to run it you need to install yet another interpreter".

So, it would be good to have fish to bash converter to write scripts in fish and deploy them in bash. I understand that it isn't easy task, I filled this issue for future planning.

**Comment by krader1961** [comment]
No one will ever take the time to write such a converter. So there is no point having an open issue asking that one be written. Not to mention the philosophical issues that have been raised as arguments against doing something like this. There are several hundred other feature requests with greater merit that we would like to see people work on.
