### ISSUE TITLE
Improve error messages when running 64-bit program in 32-bit OS (Linux).

### ISSUE THREAD

**Issue by xfix** [fish-shell/fish-shell#1427]
Currently, fish shell shows the following error message, which suggests the program doesn't exist (?).

```
Failed to execute process '<executable>'. Reason:
The file '<executable>' does not exist or could not be executed.
```

However, bash can make slightly more cleaner error messages.

```
bash: <executable>: /lib64/ld-linux-x86-64.so.2: bad ELF interpreter: No such file or directory
```

**Comment by krader1961** [comment]
Closing since it is three years old with insufficient information to determine root cause.
