### ISSUE TITLE
Can't capture command output

### ISSUE THREAD

**Issue by danielmatz** [fish-shell/fish-shell#1431]
I'm having a really strange issue.  I'm using the tool Fabric (http://www.fabfile.org) on Mac OS X.  I am trying to build a completion file for it.  So I use the following command:

```
fab --shortlist --hide everything --show stdout
```

Which prints out a list of the available build targets.

However, if I instead try to do:

```
echo (fab --shortlist --hide everything --show stdout)
```

Nothing prints out!  And then I notice that the command in `()` has become a background job.  But I can't bring it to the foreground, I can only kill it.

I've tried the same thing in bash, and it works fine.  Any ideas?

Thanks!

Daniel

**Comment by faho** [comment]
Is this still relevant?

**Comment by danielmatz** [comment]
I just repeated the steps I explained in my original post, and everything seemed to work fine.  I'll close the issue.
