### ISSUE TITLE
Add color coding for functions in fish_config

### ISSUE THREAD

**Issue by skyghis** [fish-shell/fish-shell#1432]
When I look at functions in fish_config via my web browser, it's hard to read.
A way to ease this, in my opinion, is to add script coloration in **prompt** and **functions** tabs

Thanks for this great shell !

**Comment by krader1961** [comment]
Note that it should be trivial to implement this since `fish_indent` supports the `--html` flag which provides syntax highlighting for HTML output.

**Comment by zanchey** [comment]
This was harder than I thought! #4004 implements this in a basic manner.
