### ISSUE TITLE
Implicit test for non null values in if construction

### ISSUE THREAD

**Issue by rominf** [fish-shell/fish-shell#1433]
I want to know was my script executed with arguments or not. I didn't figure how can I check it easier than with this construction:
```ruby
if test (count $args) -gt 0
	echo "yes"
end
```

Isn't this too complicated? In Python (despite it's principle "Explicit is better than implicit.") I can do it with:
```python
if args:
    print("yes")
```

I understand how `if` works right now. I think it can extended for testing for non null values too.

**Comment by faho** [comment]
I don't think there's anything more to be done here.

I frequently use

```fish
if not set -q argv[1]
    echo "Please supply arguments. Tasty arguments"
    return 1
end
```
