### ISSUE TITLE
Vi key bindings don't work when set in config.fish

### ISSUE THREAD

**Issue by euclio** [fish-shell/fish-shell#1435]
Steps to reproduce:
1. Add the line `fish_vi_key_bindings` to `~/.config/fish/config.fish`.
2. Open fish. The shell won't respond to any keys (including <kbd>i</kbd>, <kbd>a</kbd>, etc.), so I can't type anything into the prompt.

The key bindings work as expected when I open the shell without this line in my config, and instead call `fish_vi_key_bindings` in the shell.

**Comment by Hettomei** [comment]
I think this should definitely be in the FAQ.

I have to come in this issue to found in http://fishshell.com/docs/current/commands.html#bind
> Key bindings are not saved between sessions by default. To save custom keybindings, edit the fish_user_key_bindings function and insert the appropriate bind statements.

A helpfull FAQ would be : 

How to start with vi mode ?

edit $HOME/.config/fish/functions/fish_user_key_bindings.fish
```fish
function fish_user_key_bindings
  fish_vi_key_bindings
end
```
