### ISSUE TITLE
Backspace not working in vi insert mode on CentOS 5

### ISSUE THREAD

**Issue by danielmatz** [fish-shell/fish-shell#1442]
Hi,

I just updated fish on a CentOS 5 machine I use at work, and I noticed backspace isn't working in the vi insert mode.

Any tips?

Thanks!

Daniel

**Comment by krader1961** [comment]
There have been too many changes to the vi key bindings since this was opened to enumerate. Since I can't reproduce this I'm going to assume it has been resolved and close the issue.
