### ISSUE TITLE
Overriding SHELL variable for some apps

### ISSUE THREAD

**Issue by maxfl** [fish-shell/fish-shell#145]
The usual problem when start using fish, is that some programs do not work out of the box (mc, vim), because they can not use fish correctly for executing commands. The solution is to override the SHELL variable for them.

I've written a small function, which overrides the shell for each app in the argument list (only if app exists in the system, and is not redefined by a function). This function can be called in __fish_config_interactive.

The SHELL is guessed: first the default shell (if it is not fish) is tried, or it finds the first existing shell from the list: bash zsh dash sh csh tcsh ksh.

What do you think about it?

There are still some questions:
1) Are there other possible shells? Or the better ordering? Or another guess method.
2) Should the created functions be saved?
3) What are other apps (in addition to mc, vim, gvim, vimdiff, gvimdiff), that need other SHELL, rather the fish?
4) Is it possible to speed up the script? Current implementation takes a while to run.

```sh
function override_shell_for --description 'Override SHELL variable for the following apps'
	set -l newshell (cat /etc/passwd | grep $USER | sed 's/^.\+://')
	switch $newshell
	case '*fish*'
		set -e newshell[1]
		for sh in bash zsh dash sh csh tcsh ksh
			if type -f $sh >  /dev/null
				set newshell (type -fp $sh)
				break
			end
		end
	end
	if not set -q newshell[1]
		return 1
	end
	for app in $argv
		type --no-functions $argv >  /dev/null
		or continue		# coninue if there are no such binary
		functions -q $argv
		and continue		# continue if function is already defined

		#echo redefine $app
		echo "
function $app
    set -lx SHELL $newshell
    command $app \$argv
end
"  | .
	end
end
```

**Comment by faho** [comment]
I don't think we're gonna take this. It's neat and anyone can feel free to use it, but the real solution would be for software to explicitly use /bin/sh if it doesn't care what shell you are using, and the shell it wants to have if it cares.
