### ISSUE TITLE
set_color can't use all "ANSI" colors on background

### ISSUE THREAD

**Issue by Walther** [fish-shell/fish-shell#1464]
I've been trying to create a somewhat dynamic theme, that would instead of hardcoded hex values refer to the terminal's own "ANSI" colors.

However, it isn't possible to use a bold/bright variant (the latter 8 of the 16 palette) as a background color with `set_color`.

Screenshot example:
![image](https://cloud.githubusercontent.com/assets/2943750/2970485/16cae1c0-db5c-11e3-8e41-cf0719deb40d.png)

Expected results: the "bold/bright" variant of green should be the backround color in the third and fourth line. Instead, third line does not work at all, and fourth results in bold/bright *foreground* and the background is the "normal" green.

On foreground (the first line), it is possible to access the "bold/bright" variants of ANSI colors specified by the terminal.

Suggestion: allow referring to "ANSI" colors with `color0`-`color15` or something similar, instead of relying to `-o` / `--bold`, or alternatively, allow `-o` / `--bold` parsing also for the background colors.

(spacecolors.sh borrowed with <3 from [here](https://github.com/mfin/dotfiles/blob/master/scripts/spacecolors.sh))

**Comment by skattyadz** [comment]
This same thing just tripped me up. I'm using a base16 color scheme which stores additional colors I want to use in the 'bright' palette

**Comment by bucaran** [comment]
@skattyadz Hi. You too want to use the bright palette for background colors?

**Comment by skattyadz** [comment]
If you look at the image below you'll see that [my terminal color scheme](https://github.com/chriskempson/base16) stores some custom colors in the 8-15 range. I'd like to be able to use these colors in my prompt

![screen shot 2015-01-08 at 15 04 30](https://cloud.githubusercontent.com/assets/91115/5664369/d284f70a-9747-11e4-8df7-fef0b869ac64.png)

I'm sure it's a rare use case, but wanted maintainers to know that being able to specify by `color12` etc does have value for some people.

**Comment by bucaran** [comment]
Mmm, I see. Is not about the terminal supporting these colors, you can always 

`set_color -b bf616a; echo "        "`, but about getting the color stored by your terminal scheme. Is that correct?

**Comment by skattyadz** [comment]
As far as I know, supplying a hex code will make fish pick the closest of the 240 colors it knows about. eg:

![screen shot 2015-01-08 at 16 46 04](https://cloud.githubusercontent.com/assets/91115/5666528/0fa74c4a-9758-11e4-898e-3b2390395ba3.png)

At the moment to get `bf616a` I would do `set_color -b red`

**Comment by bucaran** [comment]
Ah, I see. The terminal scheme stores the color codes in Fish color variables.

> As far as I know, supplying a hex code will make fish pick the closest of the 240 colors it knows about.

Yes, this is correct.

**Comment by brentburg** [comment]
I am having the same issue. Would love to be able to reference colors by number so I can use colors 8-15 from my base16 theme as a background.

**Comment by jaspernbrouwer** [comment]
+1

I would opt for ditching the `-o` / `--bold` arguments completely and append the list of color names with "bright" versions:

- black / brblack
- red / brred
- green / brgreen
- yellow / bryellow
- blue / brblue
- magenta / brmagenta
- cyan / brcyan
- white / brwhite
- (normal)

That should ease the implementation of full ANSI palette support a lot, as you won't need to figure out how to literary combine `--bold` and `--background`.

**Comment by purpleKarrot** [comment]
I have the same issue. Is the use case of using base16 really so rare?

**Comment by skattyadz** [comment]
I moved to neovim so this isn't an issue for me any more



— adam

**Comment by pickfire** [comment]
I use base16 but I doesn't found any problem with it. I also uses neovim but I hate that it's colors is a bit different from the 256 colors.

If I recall correctly, fish can use true colors. Try `set_color 1F1F1F` but I am not sure how to check if the colors are correct with gimp.

**Comment by jaspernbrouwer** [comment]
>If I recall correctly, fish can use true colors. Try set_color 1F1F1F but I am not sure how to check if the colors are correct with gimp.

That only works when the terminal (or emulator) supports true colors.

**Comment by pickfire** [comment]
> That only works when the terminal (or emulator) supports true colors.

That's true, of course I am using a terminal that support true colors. Nowdays, a lot of terminal support true colors. You could look at: https://gist.github.com/XVilka/8346728

**Comment by Walther** [comment]
See on [Wikipedia](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors) - ANSI color standard specifies a possibility of 16-color palette, of which all colors should be referrable whether as foreground or background colors, i.e. there is a distinction between foreground/background and normal/bold.

**Comment by krader1961** [comment]
I prefer a prompt where each segment (e.g., hostname, git branch name) uses a distinct background color as it stands out more clearly against the colored output of other commands like `ls`. And for that use case the "bright" variants in the basic 16 color palette are much more useful. In zsh (which I'm migrating from) I had my own color management mechanism where the primary eight colors had variants prefixed by "l_" (for "light"). But I like @jaspernbrouwer's proposal (e.g., "brcyan"). This involves a trivial change to the `named_colors` table in colors.cpp.

Also, the current table is incorrect in assigning the label "white" to palette entry 7 which is actually light grey. Palette entry 15 is white.

I'm ambivalent about adding support for referencing all palette entries by index using a scheme like `colorN`. I did implement it in my zsh color subsystem but found that I never use it so I'm not motivated to implement it. However, if someone else provides a change that implements it with minimal additional complexity I don't see any reason to object.

**Comment by krader1961** [comment]
@Walther, or anyone else who has commented on this issue, can this be closed? The change I made to support the "bright" variants has been merged and is working for me. If someone feels strongly about adding support for referencing the 256 color palette by index I think a new issue should be opened by someone willing to write the code to implement it.

**Comment by ridiculousfish** [comment]
Closing. Thanks krader!
