### ISSUE TITLE
suggest more that 1 and categorise autosuggestions; much like vimperator and friends, and let user define priority

### ISSUE THREAD

**Issue by 257** [fish-shell/fish-shell#1465]
with this, autosuggestion doesn't just offer one single/best suggestion but rather give a list of suggestions pulled from different _sources_, very much like the way vimperator/pentadactyl/dwb do it. Tab obviously would cycle through suggestions.
moreover make it configureable so the user can decide which category has a higher priority.

**Comment by foo-bar-baz** [comment]
...in an 80x24 text display, it could look like this:

https://camo.githubusercontent.com/0b07def9e05309281212369b118fcf9b9fc7948e/68747470733a2f2f7261772e6769746875622e636f6d2f6a756e6567756e6e2f692f6d61737465722f667a662e676966

**Comment by foo-bar-baz** [comment]
reading my own comments i realised that i didn't answer your question about inserting 'o' properly.

the answer is no; user doesn't need to enter 'o'. fish starts in that "mode". something akin to this:
https://camo.githubusercontent.com/0b07def9e05309281212369b118fcf9b9fc7948e/68747470733a2f2f7261772e6769746875622e636f6d2f6a756e6567756e6e2f692f6d61737465722f667a662e676966

user starts typing and a menu of suggestions would be presented to him. that menu, and on the fly changes to it, will of course reflect the already typed chars into the prompt. also search is fuzzy, like the example above.

two point about that menu:
1. source of suggestions for that menu can be many categories; history, command arguments, file/path and so on
2. presentation of the menu can be improved by partitioning it into cagetories of the sources mentioned above.

**Comment by foo-bar-baz** [comment]
zsh already does this a la auto-fu.zsh
https://github.com/hchbaw/auto-fu.zsh
![auto-fu](https://cloud.githubusercontent.com/assets/1268392/6199738/d66b5b0e-b423-11e4-8e2e-195402269125.gif)

**Comment by 257** [comment]
https://camo.githubusercontent.com/3759d1c606cf0345721718749b324b52d6ffa096/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f3938303030302f3938323731362f65623435613939342d303831372d313165332d383036652d6365366537333162383665662e706e67

**Comment by krader1961** [comment]
The proposal is not compatible with an app like fish which doesn't own the entire terminal window.
