### ISSUE TITLE
functions <func_name> converts first-line spaces to tabs

### ISSUE THREAD

**Issue by JeanMertz** [fish-shell/fish-shell#1472]
This is just a minor thing, but I noticed that using `functions mytest` actually replaces my indendation-spaces in the first line with tabs. All other lines are fine...

``` bash
function mytest
  echo 'two spaces'
  echo 'and two more'
end
```

``` bash
$ functions mytest

function mytest
    echo 'two spaces'
  echo 'and two more'
end
```

**Comment by zanchey** [comment]
`functions_def` in `builtin.cpp` has the following comment:

```
 /* This forced tab is sort of crummy - not all functions start with a tab */
```

Maybe the output of `functions` should be sent through `fish_indent`? Perhaps with the colorising turned on.

**Comment by ridiculousfish** [comment]
Makes sense.

**Comment by floam** [comment]
> Maybe the output of functions should be sent through fish_indent? Perhaps with the colorising turned on.

Should that be done in the cpp or should functions be wrapped in fish script? Does anything depend on `functions` output?

I changed `type.fish` to pump `functions` output through `fish_indent` for it's `type -a funcname` recently but wasn't sure if folks were comfortable with changing the `functions` behavior (before I found this issue). https://github.com/fish-shell/fish-shell/commit/cd422e5d78d48e0f7cde24a49af01eea3ab4b17b

**Comment by krader1961** [comment]
For the record this also affects the `funced` command.

**Comment by faho** [comment]
Okay, I changed it so we put four spaces instead of a tab, which matches the style of fish_indent.

I think we should push that more, because automated formatting is nice.

**Comment by zanchey** [comment]
This got superseded by the solution to #5285.
