### ISSUE TITLE
Error message for $array[0] could be more helpful

### ISSUE THREAD

**Issue by Ahti** [fish-shell/fish-shell#1474]
I sometimes forget fish arrays start at index 1, and when I do, the error messages sometimes don't help very much in reminding me of that.

For example, this error message: `fish: Could not expand string '\*{$argv[0]}\*'` first led me to believe I messed up the asterisks somehow.

I think a special error message for accessing the zeroth element of an array would be useful to have.

**Comment by robi50** [comment]
+1

**Comment by terrycloth** [comment]
Looks like they followed @Ahti's suggestion? I'm trying out fish 2.2, and the error message seems pretty specific now:

``` fish
> set foo "phooey"
> echo $foo[ 0 ]
```
> <samp>Array index out of bounds
fish: echo $foo[ 0 ]</samp>

So this Issue can probably be closed.

**Comment by zanchey** [comment]
Indeed, I think this got fixed as part of c91f70523cbdf6229.
