### ISSUE TITLE
backticks are not executed in fish

### ISSUE THREAD

**Issue by and** [fish-shell/fish-shell#1481]
It is not possible to run commands using backtick (`) characters like `ls -l \`which xterm\`` from the fish shell. 

Error:

```
ls -l \`which xterm\`
ls: cannot access \`which: No such file or directory
ls: cannot access xterm\`: No such file or directory
```

Expected output:

```
ls -l \`which xterm\`
-rwxr-xr-x 1 root root 511064 Oct 29  2013 /usr/bin/xterm
```

**Comment by exhuma** [comment]
How would I write something like the following in fish?

    git ci -m "Version bumped to $(python setup.py --version)"

**Comment by floam** [comment]
`git ci -m "Version bumped to "(python setup.py --version)`

**Comment by floam** [comment]
Or in 2021, `git ci -m "Version bumped to $(python setup.py --version)"`.

**Comment by karol-depka** [comment]
Hi. "()" could be good idea too coz open-close distinction. But not having backticks breaks with decades of shell and muscle memory history (and "pasting stuff from the internet"). I'm switching back to `oh my zsh` as main shell for that reason (I can imagine possibly many people would do that, hampering adoption of fish).
I'm not saying 100% compat is needed with *sh/bash. But backticks seem like they could/should be kept. Could this be at least an option? (or a general option radical-new vs somewhat-compatible). In the end fish, is a *shell*, not some alien language ;). Thumbs-up, if You agree :).
