### ISSUE TITLE
New directory for external completions used by external packages

### ISSUE THREAD

**Issue by SanskritFritz** [fish-shell/fish-shell#1485]
We should provide the possibility for other packages to maintain fish completions for themselves and put those files into a directory provided by fish upon installation.

From the mailing list:
Siteshwar: "Probably we can add another directory in `$fish_complete_path` where authors of other utilities can keep their completions and it should get priority over other completions."
"I am not sure if such completions should be kept under `/usr/share/fish`. Maybe `/usr/share/fish_external_completions` or `/etc/fish_external_completions`."

**Comment by zanchey** [comment]
@ridiculousfish, could you add the `vendor_completions.d` path to the Xcode build?

**Comment by ridiculousfish** [comment]
Will do when I get a chance

**Comment by ridiculousfish** [comment]
Added in ba721d6cbf012fde5ebbc8b8a77fca50fc40a689. Thanks for keeping track of this

**Comment by languitar** [comment]
Is it possible to redefine this path via build system configuration arguments? I am currently implementing fish completion support for OS X homebrew and in homebrew each program is installed into a separate folder and the prefix is formed by symlinking things together. Right now the vendor completion path points into the isolated installation prefix of fish and will therefore never match to any other completions symlinked into the actual prefix. So, making this configurable would be a great help in this situation.

**Comment by ridiculousfish** [comment]
The best thing to do is to arrange for homebrew's new directory to be added to `fish_complete_path`. Configuring this at build time is possible but I think it is a little better to determine it dynamically. Another option is to outright replace `vendor_completions.d` with a symlink. What path were you thinking of?

**Comment by languitar** [comment]
@ridiculousfish the actual install prefix for fish is e.g. `/usr/local/Cellar/fish/HEAD` and things are symlinked together into `/usr/local`. So I would just want to reconfigure things so that `/usr/local/share/fish/vendor_completions.d` ends up on `fish_complete_path`.

**Comment by ridiculousfish** [comment]
I opened #2113 to track this idea.

**Comment by languitar** [comment]
thanks
