### ISSUE TITLE
Create bootstrap script

### ISSUE THREAD

**Issue by rominf** [fish-shell/fish-shell#1489]
As was noted in #1420 there are two conflicting issues related with using scripts on machines that don't have `fish` installed:
1. Converting fish script to bash (if we would have fish -> bash converter, that isn't written yet) will reduce number of installed instances of fish.
2. We cannot distribute fish along with script (because it's a binary file). So user should install fish manually. But it's bad if we want to fully automate some process.

I propose to create bootstrap script that installs fish from distribution repositories. Having this script we can distribute almost unmodified fish scripts that acts as bash script at first, installs fish if necessary and executes original script. Pseudocode:

Fish script written to be compatible with machines that don't have fish installed:
```bash
#!/usr/bin/env bash
# ! Notice bash but not fish in shebang
# check is fish installed, if it's installed, then trim preparation lines and run this script as fish script
# ...
# if user don't have fish installed download installer script
wget -O install_fish.sh http://bootstrap.fishshell.com
su -c "bash install_fish.sh $0 $(whoami)"

# Normal fish script code
# ...
```

install_fish.sh:
```bash
# if debian-based:
# ...
# if openSUSE:
zypper --non-interactive addrepo --refresh \
            http://download.opensuse.org/repositories/shells/${DISTRO_REPO}/shells.repo
zypper --gpg-auto-import-keys --non-interactive refresh
zypper --non-interactive install fish
# other
# ...

# trim first lines of fish script
trim-preparation-lines $1
# run as fish script (user should be changed to previous)
su $2 -c "fish $1"
```

It's not a great solution:
1. It requires internet connection to install fish.
2. Fish script author should add additional 0.1-0.2 KiB of text to it's script (of course it can be one liner, that is copy pasted from documentation).
3. It modifies repositories on user computer.
4. Fish developers have to write bootstrap script. See https://github.com/saltstack/salt-bootstrap/blob/develop/bootstrap-salt.sh for example. Of course, fish bootstrap shouldn't be so huge because `fish` has far less dependencies than `salt`.

PS: I'm not an bash expert, forgive me for mistakes.

**Comment by faho** [comment]
I have to agree with @justinmayer here - writing this properly for everything is rather hairy, and the proper solution is for operating systems/distributions to make installing software easy.

Thankfully, for most, that should be the case (and those for which it is not cater to a more advanced audience anyway).

**Comment by zanchey** [comment]
> the proper solution is for operating systems/distributions to make installing software easy.

and for fish developers to make the software as distribution friendly as possible!
