### ISSUE TITLE
Binding "accept suggestion & execute" to a key doesn't work

### ISSUE THREAD

**Issue by Teyras** [fish-shell/fish-shell#1498]
When I set this key binding:

    bind \cn "commandline -f accept-autosuggestion execute"

fish doesn't seem to accept the autosuggestion at all, it only executes the part of the command I've already typed. I also tried binding the keys to this function

    function foobarbaz
        commandline -f accept-autosuggestion
        commandline -f execute
    end

but it does the same thing.

Am I missing something, or is this a bug?

**Comment by faho** [comment]
This was fixed with 1567.
