### ISSUE TITLE
Direct access to $args

### ISSUE THREAD

**Issue by hahla** [fish-shell/fish-shell#1499]
When passing args to a function, direct access would be nice. Consider the following:

function whatever
    count $argv
    echo $argv[0]
end

$ whatever a b c
3
fish: Could not expand string '$argv[0]'

**Comment by PoolloverNathan** [comment]
Maybe this could work:
```
function sample
    echo (count $argv)
    echo $argv[0]
end
> sample
0
sample
> sample 1 2 3
3
sample
> exit
```
