### ISSUE TITLE
Weird offset with utf8 characters in prompt

### ISSUE THREAD

**Issue by padde** [fish-shell/fish-shell#1502]
Fish ships with the "Simple Pythonista" configuration, however this breaks as soon as a `fish_right_prompt` is used. Here's an example session that exhibits several problems:

```
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
user at host in ~
↪ function fish_right_prompt
       echo 'RIGHT'
   end
user at host in ~
↪  ls                                                                     RRIGHT
Applications       Downloads          Library            Public
...
user at host in ~
↪                                                                         RRIGHT
user at host in ~
↪                                                                         RIGHT
```

Problems:
- Additional space appears after `↪`
- Right prompt is off to the left by one character
- After line is entered with <kbd>Return</kbd>, the first character of the right prompt is duplicated, however the rest is now in the right position.

Using a `fish_prompt` without multibyte (utf8) characters seems to work correctly. My guess is that the width of the `↪` character is not computed correctly.

**Comment by faho** [comment]
>we should interpret an empty LANG to mean UTF-8

We do, since 2.4.0.

**Comment by JoshCheek** [comment]
I was able to reproduce something very similar locally. The solution is to tell iTerm to use the same unicode widths that Fish is using:

![screen shot 2018-06-19 at 9 49 25 pm](https://user-images.githubusercontent.com/77495/41638006-874cce7e-741c-11e8-83a3-0aa37499480e.png)
