### ISSUE TITLE
document how to install fish via yum on amazon linux

### ISSUE THREAD

**Issue by jab** [fish-shell/fish-shell#1513]
I'm setting up an Amazon Linux EC2 instance for the first time and, after enabling "Extra Packages for Enterprise Linux 6" in /etc/yum.repos.d/epel.repo, was sorry to still see no results for `yum search fish | grep shell`.

I went to fishshell.com, followed the "Other Linux Distros" link under the Linux tab, and ended up at http://fishshell.com/files/2.1.0/linux/index.html, but don't see Amazon Linux there. Would any of the instructions for the distros that are listed there work for Amazon Linux too?

Thanks for any help.

**Comment by vcfvct** [comment]
I am getting 


http://download.opensuse.org/repositories/shells%3A/fish%3A/release%3A/2/RedHat_RHEL-6/repodata/repomd.xml: [Errno 12] Timeout on http://download.opensuse.org/repositories/shells%3A/fish%3A/release%3A/2/RedHat_RHEL-6/repodata/repomd.xml: (28, 'Connection timed out after 30000 milliseconds')

any ideas?

**Comment by faho** [comment]
@vcfvct: Seems to work for me (at least I get some xml when opening that link in firefox, no idea what it's supposed to look like) - checked your network yet?

**Comment by faho** [comment]
With how linux distributions work, it's pretty much impossible to document _all_ of them, especially to list all derivatives - I don't think we mention Linux Mint or ZorinOS either. Adding all of them would mean cluttering up the list. If you see the base of your distribution there but not your distro itself, try that - that doesn't just apply to fish but any piece of software.

Therefore I'm closing this. Sorry!
