### ISSUE TITLE
Append to file redirection with sudo

### ISSUE THREAD

**Issue by norcalli** [fish-shell/fish-shell#1515]
I am trying to append to a file which would require `sudo` permission to write to. I know there are alternatives to doing `sudo echo 1 >> /tmp/protected` like `echo 1 | sudo tee -a /tmp/protected`, but it seems like the former should work. Am I missing something? I am new to fish.

**Comment by andschwa** [comment]
You could always easily `sudo fish -c "original command"`, and I'm sure wrap this into a function.

**Comment by Linesmerrill** [comment]
Thank you @andschwa! No idea why I didn't think of that, works flawlessly 😃
