### ISSUE TITLE
Add 'else' as fall back to 'switch' statement

### ISSUE THREAD

**Issue by alexherbo2** [fish-shell/fish-shell#1520]
``` fish
switch $bool
  case true
    echo 1
  case false
    echo 0
  else
    echo -1
end
```

**Comment by anordal** [comment]
As long as we support other wildcard expressions, like `case '*.jpg`, the meaning of `case '*'` as default case label comes all by itself. So, given that we're not removing `case '*'` anytime soon, do we really want to add another way to do the same? Don't forget that multiple ways to do the same is food for endless coding style wars.

This is analogous to posix shells:

fish:

    switch ape.jpg
        case '*.jpg'
            echo JPEG
        case '*.png'
             echo PING
        case '*'
             echo dunno
    end

sh:

    case ape.jpg in
        *.jpg)
            echo JPEG
        ;;
        *.png)
             echo PING
        ;;
        *)
             echo dunno
        ;;
    esac

---

> I believe that `else` fits fish goals better. `case '*'` isn't really discoverable in my opinion.

Discoverable, how so? If it was me, I would probably try `default` first, and then not have the fantasy to try `else` in this context.

**Comment by krader1961** [comment]
I agree with @anordal: There already is an obvious way to write a catchall block for a *switch* statement.  Adding another way to say the same thing is a bad idea. Fish should follow the Python maxim of ["There should be one, and preferably only one, obvious way to do it."](https://www.python.org/dev/peps/pep-0020/).  As for it being hard to "discover" it's in the sole, short, example in `man switch`. I vote that this proposal be rejected.

**Comment by faho** [comment]
I agree with @krader1961 and @anordal. @ridiculousfish, @xfix: Would you be okay with closing this?

**Comment by ridiculousfish** [comment]
Yep

**Comment by faho** [comment]
@xfix: I'm closing this for now. If you object, we'll reopen.
