### ISSUE TITLE
incorrect escaping when using rsync or scp

### ISSUE THREAD

**Issue by hiberno** [fish-shell/fish-shell#1523]
When I try to scp or rsync a folder from remote to my machine, I notice the following:

``` sh
scp -v remote_host:docs/doc\ file.pdf . 
(...)
debug1: Sending command: scp -v -f docs/doc file.pdf
```

which of course fails:

``` sh
Sink: scp: files/test: no such file or directory 
```

When doing the same in `zsh`, the whitespaces get escaped like this:

``` sh
scp -v remote_host:docs/doc\\\ file.pdf
```

Is it just the server or does `fish` fail to escape whitespace correctly here?

**Comment by krader1961** [comment]
Duplicate of #1872.
