### ISSUE TITLE
Replacement for bash subshell redirection?

### ISSUE THREAD

**Issue by euclio** [fish-shell/fish-shell#1524]
Is it possible to redirect a file into the stdin of a subshell, specifying the subshell first? I'm not sure if subshell is the correct term; I'm referring to `begin; <commands>; end`. I'd like to emulate the behavior of `(cat) < file.txt` as in bash. If it's not possible to write the command in that order, what would be the correct way?

**Comment by faho** [comment]
Is there still an issue here? It seems like the proposed solution works.

**Comment by ridiculousfish** [comment]
You're doing god's work by going through these old bugs, faho :grin:

**Comment by zanchey** [comment]
With 12 months without activity and an apparent solution I think we can close this :-)
