### ISSUE TITLE
add mathematical symbol comparison in test command

### ISSUE THREAD

**Issue by alexherbo2** [fish-shell/fish-shell#1528]
| Unicode | ASCII | Option |
| :-: | :-: | :-: |
| = | == | `-eq` |
| ≠ | != | `-ne` |
| < | < | `-lt` |
| > | > | `-gt` |
| ≤ | <= | `-le` |
| ≥ | >= | `-ge` |

Example

``` fish
test $a '<' $b; and echo true; or echo false
```

**Comment by krader1961** [comment]
There are no good reasons to implement this and several reasons not to.
