### ISSUE TITLE
Escape for meta-keybindings

### ISSUE THREAD

**Issue by asheidan** [fish-shell/fish-shell#153]
Some shells support using the sequence escape,character instead of meta-character. That makes it possible to use the meta-key (ie. option-key in OS X) for extended characters and still use meta-keybindings.

(Extensive googling hasn't revealed any information about fish supporting this already and keybindings with meta doesn't work with escape. Same terminal running standard bash does however.)

If this is a bug it is reproduced on both Ubuntu and Mac OS X (compiled from 1bead8adf7e3139e0b4644a6215751fac60daddf).

**Comment by faho** [comment]
This and #1356 are the same thing, but there's a bit more information there. Closing this.
