### ISSUE TITLE
Completion of make targets

### ISSUE THREAD

**Issue by joedevivo** [fish-shell/fish-shell#1546]
Fish is doing a great job of finding make targets, unless your `Makefile` is `include`ing another makefile.

There are a couple of ways I think that this could be fixed, but I'm new to fish development, so I thought I'd ask which way was more fishy, then I'll go put together the pull request.

Whatever the change is, it'll be in this function: https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_print_make_targets.fish

1) In addition to the files listed in line 6, I could add an environment variable to my fish.config with additional files to look for. In my case, I've got one or two filenames that my includes all have

2) The convention for these includes I've seen is `*.mk`. I could add `*.mk` to the list of files checked

3) As part of the function, I could grep for `include ([^:space:]*)` and search the captured filename for targets.

Thoughts?

**Comment by faho** [comment]
Anyone got an example of software with a recursive makefile? I now wrote a fix for this (for GNU make for now), but I need a test case. FTR, this is what my __fish_print_make_targets.fish looks like now:

```fish
function __fish_print_make_targets
	switch (make --version | head -n 1)
		case "GNU*" # This probably won't work on BSD make, so fall back on the grep method then
			set -l cmd (commandline -opc)
			# Try to read a different makefile name from commandline
			# TODO: Do the same for "-C" "--directory"
			set -l makefile
			if test "make" = $cmd[1]
				if set -l i (contains -i -- "-f" $cmd; contains -i -- "--file" $cmd; contains -i -- "--makefile" $cmd)
					switch $cmd[$i]
						case "*=*"
							set makefile "-f " (echo $cmd[i] | cut -d"=" -f 2)
						case "*"
							set -l file $cmd[(math $i + 1)]
							set makefile "-f " $file
					end
				end
			end
			# Awk invocation from http://anonscm.debian.org/gitweb/?p=bash-completion/bash-completion.git;a=blob;f=completions/make;h=d56e19627b4fcf2d6cd16b2934be0a21e29d5175;hb=3f851722d7ec106b0cf4ec561dac45080c8e5d64
			make -qp $makefile ^/dev/null | awk -F':' '/^[a-zA-Z0-9][^$#\/\t=]*:([^=]|$)/ \
			{split($1,A,/ /);for(i in A)print A[i]}'
		case "*"
			# Some seds (e.g. on Mac OS X), don't support \n in the RHS
			# Use a literal newline instead
			# http://sed.sourceforge.net/sedfaq4.html#s4.1
			# The first expression removes everything after the last ":"
			for file in GNUmakefile Makefile makefile
				if test -f $file
					sgrep -h -o -E '^[^#%=$[:space:]][^#%=$]*:([^=]|$)' $file ^/dev/null | sed -e 's/:[^:]*//' -e 's/^ *//;s/ *$//;s/  */\\
					/g' ^/dev/null
					# On case insensitive filesystems, Makefile and makefile are the same; stop now so we don't double-print 
					break
				end
			end
	end
end
```

**Comment by zanchey** [comment]
Fish's Makefile is recursive for libpcre2!

**Comment by faho** [comment]
Humm... I see a difference, but I'm not sure it's correct. The old print_make_targets gives (a lot of these duplicated):

>all
builtin.o
check-legacy-binaries
check-uninstall
clean
configure
depend
distclean
doc
doc.h
doc/refman.pdf
doc_src/commands.hdr
doc_src/index.hdr
fish
FISH-BUILD-VERSION-FILE
fish_indent
fish_tests
fish_version.o
install
install-force
install-sh
install-translations
iwyu
_iwyu
key_reader
lexicon_filter
lexicon.txt
Makefile
messages.pot
obj
obj/autoload.o
obj/builtin.o
obj/builtin_test.o
obj/color.o
obj/common.o
obj/complete.o
obj/env.o
obj/env_universal_common.o
obj/event.o
obj/exec.o
obj/expand.o
obj/fish_indent.o
obj/fish.o
obj/fish_tests.o
obj/fish_version.o
obj/function.o
obj/highlight.o
obj/history.o
obj/input_common.o
obj/input.o
obj/intern.o
obj/io.o
obj/iothread.o
obj/key_reader.o
obj/kill.o
obj/output.o
obj/pager.o
obj/parse_execution.o
obj/parse_productions.o
obj/parser_keywords.o
obj/parser.o
obj/parse_tree.o
obj/parse_util.o
obj/path.o
obj/postfork.o
obj/print_help.o
obj/proc.o
obj/reader.o
obj/sanity.o
obj/screen.o
obj/signal.o
obj/tokenizer.o
obj/utf8.o
obj/wcstringutil.o
obj/wgetopt.o
obj/wildcard.o
obj/wutil.o
.PHONY
prof
share/man
src/builtin_string.cpp
test
test_fishscript
test_high_level
test_interactive
test_low_level
toc.txt
uninstall
uninstall-legacy
uninstall-translations
user_doc
xcode-install

while the new one (though quite improved from the weird thing I posted above) yields:

>Doxyfile.user
check-uninstall
check-legacy-binaries
lexicon_filter
iwyu
Makefile
install-force
test_high_level
test
test_interactive
configure
FISH-BUILD-VERSION-FILE
uninstall-legacy
doc.h
obj
toc.txt
config.h
fish_indent
key_reader.o
uninstall-translations
doc
clean
install
fish_version.o
FORCE
key_reader
lexicon.txt
configure.ac
lexicon_filter.in
distclean
install-sh
fish_tests
Makefile.in
messages.pot
user_doc
builtin.o
depend
all
prof
prof
prof
test_low_level
fish.pc
test_fishscript
Doxyfile
xcode-install
install-translations
fish
uninstall

**Comment by drobakowski** [comment]
Any news on this?

**Comment by faho** [comment]
@drobakowski: Nope. This is really rather complicated since you'd need to work with different make implementations, and weird make files and such. PRs welcome!

**Comment by krader1961** [comment]
Unfortunately unless someone who uses the command actually writes the required completion script code it will never be implemented. We are happy to answer questions and provide guidance about implementing a better completion script for make. However, I'm going to close this because unless someone like yourself actually does that work it will never be done. Feel free to reopen this issue if you, or anyone else, is interested in making the required changes and needs advice.

**Comment by floam** [comment]
I'm not sure closing this just because it seems hard to implement was the right call. It's a valid feature request.

**Comment by krader1961** [comment]
Fantastic, @floam. Can we assume you're going to do the work? If not why reopen this? It's not a core fish feature. There are literally an infinite number of valid feature requests. Especially with respect to command completions. Having an open issue requesting a  specific command completion has exactly zero value unless someone (e.g., the OP) is willing to do the work but simply needs feedback on whether and how they should  proceed. If not then there isn't any point in keeping the issue open. Anyone wanting this will do the work and create a PR for review. They're not going to bother to search our backlog of open issues and say "hey, that looks like a cool idea".

**Comment by floam** [comment]
<em>If not why reopen this?</em>

So it doesn't get lost in the sea of closed issues.

**Comment by krader1961** [comment]
Okay, If I open 1,000 issues asking for fish to provide completion request for various commands you think those issues should all remain open? Even though I have no intention of doing  the work and no  one else is interested in doing so?

**Comment by floam** [comment]
Are there really 1,000 completions you need?

**Comment by floam** [comment]
Any deficiencies you can spot with existing completions that bother you, like this issue - feel free to report.

**Comment by krader1961** [comment]
> Are there really 1,000 completions you need?

Yes, there are really thousands of completions I could hypothetically need help with from fish. Which is true for anyone using fish or any other CLI shell that provides command completion support.

You completely missed the point of my comment. There are an infinite number of feature requests that are not absurd on their face. And 99% of command completion improvements are in that set. But in the case of command completion enhancement requests there is zero value in keeping the issue open unless the OP or someone else says "I'm willing to do the work but have some questions" 
 within a few weeks of the issue being opened.

Adding or improving a command completion is fundamentally different from changing the core behavior of fish. Such as implementing support for vars that implement dictionaries. Or supporting colon separated variables than `PATH` via something like the zsh tied variable mechanism.

**Comment by terlar** [comment]
Doesn't this already work after: https://github.com/fish-shell/fish-shell/commit/2740cc80d20d44d2f1ab09f3647c82903d42f3ca

This was using the `make` command to query what targets exists and not parsing of Makefiles manually.

In my trials with Makefiles having includes it works.

**Comment by faho** [comment]
>Doesn't this already work after: 2740cc8

Yes, that should fix it. Thanks for the reminder!
