### ISSUE TITLE
Provide a way to update the prompt with the current time

### ISSUE THREAD

**Issue by ahti** [fish-shell/fish-shell#1555]
I think it would be quite awesome to be able to display the current time in the (right) prompt. This is possible now, but only draws once and then does not refresh the displayed time.

This could probably be solved similar to the suggested solution in #897, but as of now, I don't really see a way to send an event every second (except maybe having an extra instance of fish running and setting some universal variable or running some other deamon that signals all fishes every second, but that seems kind of wasteful).

**Comment by Fidge123** [comment]
:+1:

**Comment by krader1961** [comment]
I, and most people, expect the `fish_prompt` and `fish_right_prompt` functions to run once per prompt. I include the time in my left prompt and expect it to show me the time that the prompt was written -- not the current time. Changing this would mean changing the current behavior in a backward incompatible manner and thus only possible in a major release. Lastly, the current time can readily be displayed in a hundred other ways. If you really want fish to do so just put a command in the background that writes to whichever part of the terminal or screen you want the time to appear in.

**Comment by oelmekki** [comment]
Hi,

FYI, here's a use case.

I wanted just the same thing, but not much to know what time it is. I often have a lot of shells running around for a long time, and there's always a time when I run the same command multiple times and have different results (like, when I try to debug an app). When I do that, it would greatly help if I knew the timestamp at which I've ran each command (so I can later cross reference the results with other logs).

Initially, I just added `(date +%H:%M)` in my prompt. But I realized that, while helpful, it was not ideal yet : sometimes, my prompt would be displayed hours before I issue a command after it. If the time in the current prompt was updating, I would know for sure that the time displayed while scrolling back in my terminal is the time at which the command was issued.

There are obviously tons of workaround for this, the most obvious being to just make the debugged command issue a timestamp, or just look at the time of the next prompt (but then, you have to factor in the execution time for the command). But putting this as a prompt capability would be a nice "useful by default" thing, not requiring to edit inspected app codebase and already there for commands we issued before "officially" starting debugging.
