### ISSUE TITLE
fish in Debian jessie

### ISSUE THREAD

**Issue by jiehanzheng** [fish-shell/fish-shell#1576]
I am just wondering why fish isn't available as a package in jessie (current testing), yet it is in wheezy (current stable) and sid (unstable)?  Sorry if this is beyond control of fish-shell developers...

**Comment by benallard** [comment]
Jessie is out, and still no fish there ... That's a pity ...

**Comment by RomanHargrave** [comment]
[If you had taken the time to read the the few short emails linked above, then you would know that it was not going to be in Jessie, but rather the back ports to Jessie](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=730683#15)

That being said, fish is very simple to build.

**Comment by RomanHargrave** [comment]
That was @benallard BTW

**Comment by benallard** [comment]
I had read it, but there is no fish in jessie-backport yet, neither is the OBS giving an option for it, for people not wishing to build it themselves it's pretty harsh ... Especially now that Jessie is the official "stable" release ...

**Comment by RomanHargrave** [comment]
Ahh. I see. I can look in to building a Jessie package, as I run jessie. If I do, I will post a link back here and ping you.

**Comment by RomanHargrave** [comment]
@benallard I build a 64-bit version of fish from `master`, including my modification from `romanhargrave:list-export-control`, which is available [to download from my website](http://hargrave.info/files/fish-shell_2.1.2+1263_amd64.deb).

**Comment by zanchey** [comment]
OBS only just enabled the jessie repos, but builds are now available: http://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A2&package=fish

**Comment by jeremiejig** [comment]
Hello

Just wondering if the opensuse repo will update fish to the latest 2.1.2 release

**Comment by zanchey** [comment]
There are no changes in 2.1.2 that affect non-OS X platforms so I won't be making new builds.

**Comment by jeremiejig** [comment]
No I wasn't talking about a new build

the opensuse repo is still at the 2.1.1 release

**Comment by zanchey** [comment]
Yep, and there is no difference between 2.1.1 and 2.1.2 for non-OS X platforms, so I won't be pushing 2.1.2 to the fish project's opensuse repository ([shells:fish](https://build.opensuse.org/project/show/shells:fish)).

The official [openSUSE package](https://build.opensuse.org/package/show/shells/fish) is maintained by someone else but there is no need to use 2.1.2 on anything except OS X.

**Comment by knutole** [comment]
bump

**Comment by zanchey** [comment]
@knutole, what are you bumping? There's not much we can do here.
