### ISSUE TITLE
Distinguish "builtin functions" (was: "`type` cannot be invoked with `builtin`")

### ISSUE THREAD

**Issue by Tyilo** [fish-shell/fish-shell#1588]
Here's a diff between the commands listed in the help and the output from `builtin -n`:

```
-[
-__fish_parse
+alias
+dirh
+dirs
+eval
+fish
+fish_config
+fish_indent
+fish_prompt
+fish_right_prompt
+fish_update_completions
+funced
+funcsave
+help
+isatty
+math
+mimedb
+nextd
+open
-printf
+popd
+prevd
+psub
+pushd
+trap
+type
-while
+umask
+vared
+while
```

I can understand why some these can't be used with `builtin`, but I don't understand why `type`, `umask` etc. can't.

Could you please enlighten me?

**Comment by krader1961** [comment]
Shells like fish, bash, zsh, etc. have a flat namespace. So, as ridiculousfish said, you can have only one instance of a function with a given name. Allowing multiple implementations with the same name would require implementing name spaces such as those employed by Python and Java.  And that is already being discussed in issue #453.
