### ISSUE TITLE
Custom autocompletition

### ISSUE THREAD

**Issue by fedotxxl** [fish-shell/fish-shell#1594]
Hi

I wanna implement shell program with very specific autocompletition logic:

user can type: `myApp f.s<tab>` and shell should display him following suggestions

> fish-shell
> fish.shell.config
> ...

After that user can select which argument he wants to use. Enter -> program receives appropriate argument 

General idea - instead of typing whole argument, type only its part and chose argument from suggestions (based on some rules - split request/suggestions into words (fish.shell.config splits into [fish, shell, config], f.s - [f,s]), match words)

One more example to explain you idea:

I've got folder /home/fbelov/docs/
I wanna type `cd h.f.d` (or my custom_cd) and get suggestion `/home/fbelov/docs/` . Select suggestion, enter -> folder is changed to `/home/fbelov/docs/`

Is it possible to implement? Can you suggest me docs to read?

Thank you!

**Comment by krader1961** [comment]
It seems to me that this is already possible for specific commands by using subcommands as outlined by terlar. If the user wants to be able to replace fish's generic file completion logic with a custom function please open a new issue to make that clear.
