### ISSUE TITLE
Latest Git Master problems on a Debian 7.0 Wheezy

### ISSUE THREAD

**Issue by DistantThunder** [fish-shell/fish-shell#1598]
Hi and thanks to everyone working on this wonderful project. I adopted fish since more than a year now and has never regretted it since then. So I'm pleased to contribute to this great endeavour with my little feedback on compiling from the latest master git tree.

1st Issue : 
This is a $PATH related one. Upon compilation and installation, I noticed that each time I was invoking "sudo $cmd" in fish and try to TAB-Autocomplete, I got an error message saying  : 
"Warning: path component /usr/bin/X11 may not be valid in PATH." and my current command shell's layout would scatter over the screen and become inconsistent.

When doing "echo $PATH", I would find out that current PATH would be : 
"/usr/local/bin /usr/bin /bin /usr/bin/X11 /usr/games"
Although this is a so said "headless" remote server with no Xserver installed on it.
This was solved by going back to stable 2.1.0. I configured and made and installed the exact same way with the same user on the same machine, not rebooted.

2nd Issue :

Compiling and installing (using "checkinstall --pkgname=fish --pkgversion=2.1.0-(date +%Y%m%d)-git --deldoc=yes --backup=no --fstrans=no -y" ) from the latest git Master prevents the man pages to be installed.
The following error messages have been spotted : 
"/usr/bin/install: cannot stat `share/man/man1/fish_indent.1': No such file or directory".

Again, using the same procedure, stable 2.1.0 has no issue.
I would also point out that following compiler flag : " -DDOCDIR=L\"/usr/local/share/doc/fish\" wasn't appearing while compiling stable whereas it was present during git master's one.

**Comment by faho** [comment]
Isn't this fixed by 15cf06438e4438e21ec4048b1848f6e1bf60e072?

**Comment by zanchey** [comment]
I think so, but annoyingly, I can't reproduce it on 2.1.1 or 2.2.0 at the moment.

**Comment by DistantThunder** [comment]
I'll try again as soon as I get time, thanks.

**Comment by faho** [comment]
@DistantThunder: *Gentle poke with my softest stick*

**Comment by DistantThunder** [comment]
Hi, you were right to bump me :p 

I compiled and installed 2.2.0 from Git and am glad to report there was no problem about auto-completion and path.

Since the doc issue wasn't really one, I can say this has been resolved.

Thanks a lot for your support and dedication!
