### ISSUE TITLE
Colors in pager

### ISSUE THREAD

**Issue by nasedo** [fish-shell/fish-shell#1599]
I think using LS_COLORS environment variable would be a nice addition to the pager.

**Comment by pickfire** [comment]
#2143

**Comment by pickfire** [comment]
I think setting `LSCOLORS` automatically based on fish_pager colors if there is no `LSCOLORS` defined would be a nice idea.

**Comment by faho** [comment]
Okay, no, this appears to not be happening.

$LS_COLORS is also an awful format, we don't typically color file types differently and it's not something many people customize.
