### ISSUE TITLE
__fish_git_prompt_informative_status improvements

### ISSUE THREAD

**Issue by tannhuber** [fish-shell/fish-shell#1601]
I would like to propose and discuss some changes in the git status. At the moment, it's obviously not possible to see whether a file has been deleted. I would expect a similar behaviour for deleted files as for files that have been added.

In the screenshot below, a new file `d2` is created in the first command line with `echo d2>d2`. `__fish_git_prompt_informative_status` returns `%1` for an "untracked change". After the following `git add .`, it returns `+1` for an "added change".

But when you remove the file in the 8th command line with `rm d2`, a `*1` for a "modified file" is returned. I would expect an `%1` eqivalent to the "new file" case. After `git rm d2` the file is flagged as `+1`, while I would expect `–1` instead.

As far as I can see, the symbols have a different meaning in `__fish_git_prompt_informative_status`, e.g. `+` simply means "staged change". However,  `git status --porcelain` flags added files with an `A` and deleted files with a `D`. So it would make sense to consider these `A`s and `D`s within `__fish_git_prompt_informative_status` as different objects as well. What do you think?
### Conclusion
- For a file that has been removed by `rm filename`, I would expect `%1` instead of `*1`.
- For a file that has been removed from git by `git rm filename`, I would expect `–1` instead of `+1`.

![scrot-2014-08-08-132738](https://cloud.githubusercontent.com/assets/2333069/3856037/091f9b70-1eef-11e4-85c1-a2ee236c10ff.png)

**Comment by faho** [comment]
Yeah, this change is just seemingly not happening. Closing.
