### ISSUE TITLE
Need wraps arguments (wildcards) for passing to others commands

### ISSUE THREAD

**Issue by rkmax** [fish-shell/fish-shell#1602]
I use Git on console a lot, when i want stage especific files i simply run

```bash
$ git add *.scss
```

when run the previous command on fish i get a `fish: No matches for wildcard '*.scss'.` fish is trying to resolve the wildcard but i want pass to Git, for solve this i have to wraps into quotes

```bash
$ git add '*.scss'
```

I think this passing with other commands that using that kind of parameters

any way to solve this wthout wraping?

**Comment by faho** [comment]
Sorry, changing parser behavior based on per-command settings sounds like a bad idea.
