### ISSUE TITLE
`functions foo` doesn't show `--wraps` flag

### ISSUE THREAD

**Issue by lilyball** [fish-shell/fish-shell#1625]
When a function is defined with `--wraps`, the output of `functions` (and therefore, the output of `type`) does not include the `--wraps`flag:

```
> function foo --wraps git; git; end
> functions foo
function foo
    git;
end
```

**Comment by wilriker** [comment]
Additionally to not showing the `--wraps` part it is also dropped when using `funcsave` to persist the function. So is this value persisted anywhere else?

I am using the same config on multiple machines and I only share (most parts of) `~/.config/fish` directory and not the directory where the completions are stored. I am fairly new to fish and as I am still setting this up on all machines I have not yet checked whether the completion carries on to the other machines without redefining the function adding the `--wraps` part back in.

**Comment by ridiculousfish** [comment]
Part of what's funny about this is that `--wraps` can come about through either function definitions or completions. We need to be able to tease these apart I think.

**Comment by frangio** [comment]
Any news about this?

@ridiculousfish Do you have any idea where the problem lies so I can attempt to fix it?

**Comment by floam** [comment]
Noting here that #2466 shows this can actually cause real problems, not just technically wrong output: Using `funcsave` to save a function will not show the right completions on the next session.

**Comment by ridiculousfish** [comment]
I decided it doesn't matter whether the wraps comes from complete or function, let's just always print it.
