### ISSUE TITLE
parser allows unterminated quoted string inside brackets: $foo["1]

### ISSUE THREAD

**Issue by kballard** [fish-shell/fish-shell#1628]
Both the highlighter and the parser does not properly handle slices that contain strings. The highlighter just plain colors things badly, and the parser ends up complaining about an invalid index value but points to the opening `[` instead of to the actual value.

In both cases, the close `]` is sufficient to terminate the supposed nested string.

**Comment by faho** [comment]
I just tested, the highlighter colors everything from the quote onwards in string-green, "$foo[" in wrong-pink-ish and the parser complains about wrong index value and points to the first "t" in test.

So, I don't take any issue with that. Close?

**Comment by ridiculousfish** [comment]
I think it's behaving well. @kballard if you're still around, what do you think?

**Comment by kballard** [comment]
I wish I'd taken a screenshot, because the behavior I'm seeing now matches what @faho described. Although there is still a bit of an oddity, where `$foo["1]` highlights as an error but actually evaluates identically to `$foo[1]`

![screen shot 2015-07-19 at 6 25 19 pm](https://cloud.githubusercontent.com/assets/714/8768869/87e933e4-2e43-11e5-9733-bc9473d289d2.png)

**Comment by faho** [comment]
I can no longer reproduce either of the issues. Closing!
