### ISSUE TITLE
Fish variable sharing makes fish remember non-default key bindings

### ISSUE THREAD

**Issue by ZyX-I** [fish-shell/fish-shell#1637]
Consider the following sequence of actions (assuming `config.fish` is empty):

    rm ~/.config/fish/fishd.$(hostname)*
    fish
    > fish_vi_mode
    > exit
    fish

. For the second fish the following is true:

1. It is launched in Vi mode despite that emacs mode should be the default.
2. Prompt is still from emacs mode.

I do not think it is a good idea to save this data and here is why: if the user wanted to try non-standard key bindings and did not like them it is very bad idea to force him use these bindings until he edits his configuration. In my case I have two shells and one does not support vi bindings at all and this fish behavior makes system-wide fish (those that does not support vi bindings) ignore all my input that is not a regular character or CR.

**Comment by faho** [comment]
Can anybody still reproduce this with fish 2.2.0?

**Comment by zanchey** [comment]
I actually can, sort of - I've apparently set a universal `fish_key_bindings` which means that `fish_vi_mode` or `fish_vi_key_bindings` will save across sessions, but that's easy enough to fix with `set -eU fish_key_bindings`. I'm going to close this for now as I don't think there's much that can be done.
