### ISSUE TITLE
math command can't do floating point division

### ISSUE THREAD

**Issue by jcelliott** [fish-shell/fish-shell#1643]
It looks like the `math` command needs to pass the `-l` flag to bc (either by default or with a flag) in order to get floating point results:

    > echo 3456/1000 | bc
    3
    > echo 3456/1000 | bc -l
    3.4560000000000

**Comment by cdosborn** [comment]
Basically nobody should be doing complex math in the shell, that said floating point division is common. I suggest aliasing math to begin with "scale=4;". Which provides four decimal places of precision only during division. As a result:

    > math 1 + 1
    2
    > math 1 / 10
    .1000

**Comment by zanchey** [comment]
Unfortunately, [setting `scale` stops modulo arithmetic from working](http://superuser.com/questions/31445/gnu-bc-modulo-with-scale-other-than-0), which at least some existing code relies on.

**Comment by faho** [comment]
Why don't we just check if there's a "%" in the arguments, and turn on float-mode if it's not (maybe splitting on ";")?

**Comment by faho** [comment]
Urgh... the current behavior is actually quite difficult to replace and at least umask depends on the fact that it returns no trailing zeroes (`set oct (math $oct - 4)`). This would need a python-esque "if there's no dot, it's an int" scan.

**Comment by anordal** [comment]
> I like calc

Omg, I'll never use `math` again. It's got python3-style explicit integer division!

    calc 10/3
            ~3.33333333333333333333
    calc 10//3
            3
    calc 10%3
            1

**Comment by krader1961** [comment]
@faho posted a question about this issue on Gitter.im. My response was: Do we even need to add out-of-the-box support for floating point arithmetic? The main problem I have with this issue, not just the original comment, is that I see no justification for adding floating point arithmetic to fish.

FWIW, I don’t know what it’s formal semantics are but informally ksh performs integer arithmetic unless at least one operand has a decimal point. Too, a bare period in bc means the result of the previous expression. We don’t explicitly support multiple expressions so we could simply test whether a period appears anywhere in the expression and pass the -l flag if we see one. The risk, obviously, is that someone might currently be passing floating point values and relying on the integer arithmetic behavior.

So @faho's suggestion to add a `math -f` flag to explicitly request floating point semantics from `bc` is the safest path forward. Assuming there is a good reason to add this feature.

**Comment by jcelliott** [comment]
My original use case when I opened this issue was for formatting the `CMD_DURATION` variable on long-running commands. I ended up creating an external command that formats the duration exactly how I want it. So my single use case is no longer relevant. Furthermore, even if I had implemented it in fish, only having integer precision really wouldn't be a problem for displaying a human-friendly duration. That being said, it seems like you should be able to do simple floating point arithmetic in the shell, but the preceding discussion makes it obvious that this isn't as simple as it sounds.

The `math -f` suggestion seems fine to me, although it's still unfortunate that you get so many digits of precision.

**Comment by krader1961** [comment]
I've decided this can be trivially implemented by adding a `-sN` flag to set the scale of the result with the default being zero to match existing behavior. This way you can ask for `N` digits after the decimal point. Pull-request forthcoming.

Note that this isn't perfect because bc has weird behavior: it floors the result rather than rounding it regardless of whether integer or floating-point (scaled) mode is in effect. But since we explicitly say we're using `bc` people have to deal with its somewhat odd behavior.

P.S., The reason an absurd number of digits after the decimal point were being printed by previous solutions is they ran `bc -l` which implicitly does `scale=20`.

**Comment by floam** [comment]
Why is this listed for 2.4.0? Didn't this get addressed a while back?

**Comment by faho** [comment]
@floam: Because it's not in 2.3.1. It'll be released with 2.4.0, so it's marked as such.
