### ISSUE TITLE
Home and End keys broken in Vi insert mode

### ISSUE THREAD

**Issue by paride** [fish-shell/fish-shell#1670]
Hello,

In Vi normal mode the Home and End keys do work as expected, here are the keybindings from `/usr/share/fish/functions/fish_vi_key_bindings.fish`:

```
bind \x24 end-of-line
bind \x5e beginning-of-line
bind 0 beginning-of-line
bind g\x24 end-of-line
bind g\x5e beginning-of-line
bind \e\[H beginning-of-line
bind \e\[F end-of-line
```

but when I use these keys in insert mode they don't work. If I press any of them the mode switches to normal mode and the cursor moves back one character. These are the binding:

```
bind -M insert -k home beginning-of-line 2> /dev/null
bind -M insert -k end end-of-line 2> /dev/null
```

but unfortunately they do not work. If I dump the codes for Home and End with `od -b` I get:

```
^[[H
^[[F
```

that are indeed binded while in command mode (see the last two lines of the first code block of this report), but not in insert mode. The easy fix is to add a couple of `bind -M insert \e...` lines, but I think it would be better to fix `bind -k home` and `bind -k end` so they work also for `^[[H` and `^[[F`.

Thanks!

**Comment by jscheel** [comment]
Is there any update on this issue?

**Comment by faho** [comment]
`bind -k home` might not work on certain terminals, like suckless' st (#2139). The vi bindings don't currently set home via the name, though, only using the sequences directly.

These particular sequences have been bound (`bind -M insert \e\H beginning-of-line` and such), so the immediate bug is fixed.

**Comment by krader1961** [comment]
The vi bindings now contain the following statements so I think this is resolved:

```
    # OS X SnowLeopard doesn't have these keys. Don't show an annoying error message.
    # Vi/Vim doesn't support these keys in insert mode but that seems silly so we do so anyway.
    bind -M insert -k home beginning-of-line 2>/dev/null
    bind -M default -k home beginning-of-line 2>/dev/null
    bind -M insert -k end end-of-line 2>/dev/null
    bind -M default -k end end-of-line 2>/dev/null
```

**Comment by florianjacob** [comment]
(@krader1961 I can confirm this is resolved now)
