### ISSUE TITLE
Document functions like __fish_complete_command

### ISSUE THREAD

**Issue by rominf** [fish-shell/fish-shell#1678]
Please, document all (at least convenient) undocumented functions like `__fish_complete_*`.

I think I reinvented the wheel when I created [salt stack completions](https://github.com/saltstack/salt/tree/develop/pkg/fish-completions) not knowing that they exist. Probably all completion documentation will look better as a separate page (normally fish user don't need to know about completion internals). 

_Off topic: can you help me debug this strange completion bug https://github.com/saltstack/salt/issues/15692?_

**Comment by jazmit** [comment]
+1

**Comment by faho** [comment]
>That said, I think the recent completion wrapping stuff could be used to get rid of __fish_complete_svn. Instead the colorsvn completion could just be something like complete -c colorsvn -w svn, which should make colorsvn inherit all of svn's completions.

I've replaced most of these a while ago. (I think there's some remaining because there were some issues, but I can't quite recall)

**Comment by floam** [comment]
Why are these still prefixed with __? It seems to me they're not internal or private once we've documented them. Let's make them a little easier to find/notice.

**Comment by krader1961** [comment]
> Why are these still prefixed with __?

That is something I too have been wondering. There are far too many fish script functions and variables with a leading dunderscore (to use a Python term) that are in fact public and thus not private. I can't help but wonder if the person who instituted this naming convention was trying to make it even harder to possible naming collisions. If that's what they were doing by using such names they simply introduced a new problem while only partially mitigating the possibility of the naming collision problem.

**Comment by floam** [comment]
I imagine there is some preference to keep __ (or _?) because they don't want users running them directly or being made confused by this stuff. But my preference would be that these get renamed in a manner such that `__fish_complete_command` we simply call `complete_command` if we can do something to simply keep completion helper functions from being autoloaded/in scope when interactive.

**Comment by krader1961** [comment]
We're certainly not going to document every internal function (i.e., those prefaced by `__`).  What we should do is rename those meant to be used as helper functions (e.g., in completion scripts) but not used interactively to have a single leading underscore and document them. Functions meant to be truly private to fish and not used by users or third-party extensions would retain the leading double underscore. Obviously there will need to be a lengthy transition period when the renamed functions are available via both the single and double underscore names. This, however, is a lot of work for marginal benefit. Therefore I'm adding the "RFC" label to this issue.

If nothing else we should add better comments to the semi-private functions that are meant to be used by completion scripts and third-party functions. And add comments to those that are strictly off limits to the remainder to make it clear that any script which uses them can expect to be broken in the future.

**Comment by mqudsi** [comment]
I think we're all in agreement that `__fish_*` is an internal namespace. Those files should contain some sort of minimal info on what they do as a comment at the start or similar, but it's never going to be part of the formal fish api.

**Comment by floam** [comment]
A lot of these don't even provide a `--description` saying what they do. That's pretty formal and discoverable through completions.
