### ISSUE TITLE
Double tapping tab should autocomplete to the deepest possible directory

### ISSUE THREAD

**Issue by Woodamsc** [fish-shell/fish-shell#1682]
Say you have a directory tree such as ~/Code/Python/project1/src/saves/worlds/

And let's assume that from 'Code/' on, the above are the only folders in directory tree.

If my pwd is ~/Code, 'cd *double tab* would autocomplete the path down to .../worlds/ since it's unambiguous (there are no other directories branching off in-between). Essentially, it will autocomplete until it reaches a point where the are multiple paths to take (multiple subdirs). I imagine it only stopping for multiple subdirectories - it would not stop if a directory has multiple non-directory files.

**Comment by faho** [comment]
Suggestions now do this since 718d9baead9d900936c9fd6911e387732f706770. I'd rather not implement different behavior for completions (since you might want to cd into a directory in between).
