### ISSUE TITLE
Improve usability of big completion lists

### ISSUE THREAD

**Issue by rominf** [fish-shell/fish-shell#1691]
I'm the author of fish completions for [taskwarrior](http://taskwarrior.org/).

I've added support for task completions by id and description. The problem is that the resulting completion list is quite big (about 100 items). You can see this on [screencast (third command)](http://taskwarrior.org/news/news.20140906.html).

Big lists are hard to read. In the case of taskwarrior it's hard to get the full list of task's commands (commands are scattered on different pages).

I see two solutions of this problem.
##### Advantages
1. It's fairly easy to implement (in my opinion).
##### Disadvantages
1. It can be confusing (why don't I see the X item in the completion list?).
2. You cannot discover some options just by pressing TAB.
##### Description

I would add additional line on top of a console with group names as tabs. The first one would be `All`, all other tabs are generated depending on completions. When the user presses TAB he sees all available completions and that the tab `All` is active. Other tabs can be chosen using some hotkey (I would use arrow keys if possible).

I see two ways to form groups: automatic and manual.
###### Automatically formed groups

Type `ssh` and press TAB. You will see a number of `users@` with the description _User_, several `hostnames` (_Hostname_). They can be perfectly grouped into groups _User_ and _Hostname_.
###### Manually formed groups

But it's not that simple in most cases. For example, taskwarrior ids completions completions have task descriptions in their descriptions. So they can be grouped with the help of additional option `-g GROUPNAME`.
##### Advantages
1. The default behavior (tab `All` is active) is almost identical with the current behavior (except additional tab bar).
2. Completions are structured.
##### Disadvantages
1. It can be hard to implement.
2. Increases complexity.

What do you think?

**Comment by faho** [comment]
It's been 9 years, the pager is now quite different and you can search both the candidate itself and the description, which helps e.g. with git so you can filter it down to "Remote branch".

I don't see anything concrete here so I'm closing this.
