### ISSUE TITLE
`read a | cat` bails on first typed character

### ISSUE THREAD

**Issue by kballard** [fish-shell/fish-shell#1700]
When executing a pipeline with `read` at the end, it does an interactive read, but the first typed character causes the `read` to bail. It turns out what's going on is that `read` waits on `select()` just fine, but gets `EIO` when it finally calls `read()` on `stdin`. The `EIO` is because `fish` is no longer in the foreground process group; it spawned a keepalive process which took control of the terminal.

I don't know why the keepalive process is necessary. There's a comment saying this is so the process group doesn't die prematurely if the process group leader dies, but AFAIK POSIX requires that the process group keep living even if the process group leader dies, and even goes so far as to prevent new processes from reusing the PID of any dead process group leader as long as the process group is still alive. From what I've read, it sounds like the real issue is if the _session leader_ dies, but that's not something that pipelines have to worry about.

Of course, without the keepalive, fish would still need a new process group for the pipeline, which would cause the same issue. Bash gets around this by actually forking and running the `read` in the child, but of course that's pretty useless as it can't affect the variables of its parent process.

We could change `read` to detect when it's part of a pipeline and disable interactive mode, though that seems kind of crappy. We could also just try and keep fish in the foreground process group when running the `read` builtin, since I believe fish waits until the builtin is complete before spawning any external commands anyway. Or maybe some other approach I haven't thought of would work.

---

Curiously, when running `read a | cat` and typing stuff, sometimes the calling fish process also exits, without error. It appears to believe the terminal closed, which is because the calling fish process actually got `EIO`. I'm not sure why this is; I'm assuming that somehow it's reading before its process group has been made the foreground process group again, but it doesn't make sense to me why this would be. I can't reproduce this issue with `lldb` attached, but adding in debug logging shows it getting `EIO` and exiting.

**Comment by mqudsi** [comment]
This is fixed in fish 3.0 (does not reproduce under `master`).
