### ISSUE TITLE
new variable type, valid in terminal

### ISSUE THREAD

**Issue by tannhuber** [fish-shell/fish-shell#1702]
I'd like to have a variable type that would be valid only in the terminal where it was defined. It should persist even after the user has been changed with `su user`, `su user -` and - if possible - `ssh user@somehost`. But it should be deleted when the terminal is closed. Would it be possible to extend fish/fishd by a variable type like that? Or is there a simple workaround without temp files?

**Comment by krader1961** [comment]
Sorry, but no. This would be a security nightmare.
