### ISSUE TITLE
Feature Request: Advanced Path Expansion like in zsh-shell

### ISSUE THREAD

**Issue by schlichtanders** [fish-shell/fish-shell#1709]
Dear all,
it would be great to have the path expansion feature of the zsh-shell in fish-shell too. This is at the moment the missing feature which keeps me using zsh and not fish as the standard shell.

So if you put in initial letters of directories like
`cd /u/l/b` and press `tab` this completes to `cd /usr/local/bin` just because this is the only nesting which fulfils the given hierarchy.
If there are several possibilities, zsh already supports tab completion for ambiguities in the path.

see also [this slightshow](http://www.slideshare.net/jaguardesignstudio/why-zsh-is-cooler-than-your-shell-16194692), slight 29-30 (I actually haven't found an official documentation stating this feature as directly)
or try it yourself,

This would be very great to have

**Comment by verandaguy** [comment]
Has anything been done towards implementing this since the issue's been closed? Are there any reasons to oppose zsh-style pathname expansion?

**Comment by mrak** [comment]
@verandaguy this feature is still open and tracked in #94. It was closed here simply for being a duplicate.

**Comment by verandaguy** [comment]
@mrak Sorry, my bad!

**Comment by mrak** [comment]
:a::ok:
