### ISSUE TITLE
Upgrade path from fishd to no fishd

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#1730]
At present, if you upgrade from a version of fish that has a fishd to a version without, you get two different sets of "universal" variables, and two different locking methods.

What should be the way we handle this upgrade?

a) "Restart all running fish processes or risk data loss" in the release notes
b) Write a stub fishd that understands the new methods so that `killall fishd` restarts the running fishd and updates all running instances to the same set of variables

Targeting to next-minor.

**Comment by ridiculousfish** [comment]
I guess my concern is that if we keep fishd working, we'll just have to revisit this again for every release.

@zanchey What do you think about having a stub fishd that broadcasts a "fish is updated, please relaunch" to the tty upon connection?

That is, my vague idea is a script that listens on the fishd socket. When something connects to it, fishd-stub gets the remote (fish) process, gets the tty associated with that process, and then writes a message to it via `ttymsg`, similar to  `wall(1)` (but only to that tty).

**Comment by zanchey** [comment]
Sounds plausible, although all of those steps are annoyingly non-portable and fragile.

I'm really starting to think option 1 is the way to go for less long-term pain.

**Comment by zanchey** [comment]
Revisiting this, I don't think writing to the terminal of all existing processes will be terribly helpful. Most of my long-running instances are a) running curses applications or b) following log files, and the message may well get lost in display updates.

Unless anyone wants to write and test the stub fishd that understands the new methods, I think we're better off taking short term pain (option 1 or 2) - warning our users in the release notes, pleading with our distributors to actually take our advice and hoping for the best. As long as it's impossible to corrupt the fishd files then I think that's as good as it can get.

I'm going to roll 2.2.0-beta1 with that in mind.

**Comment by siteshwar** [comment]
I will go with option 2 and modify default fish_greeting function so that if a new instance of shell is launched it would print a message about running instance of fishd and request the user to exit all older instances of fish shell (This won't work if user has a customer fish_greeting but probably we can find a workaround for that).

**Comment by zanchey** [comment]
Sadly, every user has a "custom" fish greeting set by `__fish_config_interactive` on first run. We could try comparing it with the stock greeting message but that involves invoking gettext on every interactive start, which would be preferable to avoid.

**Comment by siteshwar** [comment]
We can have another internal function to show messages to the user. It may be useful in future too.

**Comment by zanchey** [comment]
Having thought about it, I think we can do that without a mandatory fork on every start.

**Comment by zanchey** [comment]
I added a message in ad61c3f - what do you think?

**Comment by siteshwar** [comment]
@zanchey Will restarting all instances of older version remove ```fishd.socket``` file ? If not then this message is wrong:

```One or more instances of an old version of fish is still running```.

**Comment by zanchey** [comment]
Curses, I thought it did, but it doesn't. New plan required...

**Comment by ridiculousfish** [comment]
I like the idea of modifying `fish_greeting`, very clever.

**Comment by ridiculousfish** [comment]
We could try connecting to the socket, and print the error if the connection is successful. This would probably have to be done in C++ but it wouldn't be too much code.

**Comment by zanchey** [comment]
OK, that sounds good. I haven't had a chance to give it a crack yet.

**Comment by zanchey** [comment]
Closed with d1a56139e1d99530d (#2023).

Needs mentioning in the release notes.
