### ISSUE TITLE
After failed tilde execution, commands stop working

### ISSUE THREAD

**Issue by mattgodbolt** [fish-shell/fish-shell#1736]
Once I've tried to execute a command with a bogus tilde name, seemingly no other commands work until I exit the shell.

    $ fish --version
    fish, version 2.1.1-986-ga772776
    $ fish
    Welcome to fish, the friendly interactive shell
    Type help for instructions on how to use fish
    mgodbolt@wud-mgodbolt01 ~> fish
    Welcome to fish, the friendly interactive shell
    Type help for instructions on how to use fish
    mgodbolt@wud-mgodbolt01 ~> cat
    cat is working
    cat is working
    mgodbolt@wud-mgodbolt01 ~> which cat
    /bin/cat
    mgodbolt@wud-mgodbolt01 ~> ~doesntexist
    ~doesntexist: command not found
    mgodbolt@wud-mgodbolt01  [127]> cat
    mgodbolt@wud-mgodbolt01  [141]> which cat
    mgodbolt@wud-mgodbolt01  [141]>

Essentially, things like "cat" stop working after I run the nonexistant command "~doesntexist"

Am I missing something here?

**Comment by faho** [comment]
There's been no news here for 1.5 years, we're very unlikely to get anywhere here. Closing, sorry.

**Comment by mattgodbolt** [comment]
Apologies; all had been well since my company moved to an alternative authentication system!. I'm glad you've closed this: thanks.
