### ISSUE TITLE
Hangs on freebsd when starting shell - no config files

### ISSUE THREAD

**Issue by danielb2** [fish-shell/fish-shell#1741]
Clean install. No config files at all.

``` bash
$ fish --version
fish, version 2.1.1
$ fish
fish:
^C^C2
```

Bug?

Later that day ...

``` bash
$ uname -a
FreeBSD luffy 10.1-BETA3 FreeBSD 10.1-BETA3 #0 r272167: Fri Sep 26 11:11:24 UTC 2014     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64
```

**Comment by wilhelmy** [comment]
I'm having the same problem on 10.1. I previously used fish-2.1.1 on 10.0, which worked fine, so I guess the update to 10.1 did indeed break it.

**Comment by zanchey** [comment]
Just waiting for the patch to be committed downstream - see https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=196661

**Comment by nakal** [comment]
Can you please make a recommendation for one of the alternative patches mentioned in the bug report. It seems it will take ages to decide. Would you like to rely on `wchar_t` support in a sane `libiconv` (no patch needed here, in the project) or would you like to support more encodings that are needed to make charset handling compatible with FreeBSD (this should cause a patch to be committed here).

**Comment by zanchey** [comment]
I did make a recommendation at https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=196661#c10

As the relevant code is gone in development versions I am not sure we are going to tag a point release to fix a downstream behaviour change, although as we are doing 2.1.2 for exactly that reason on OS X it might be worth including the patch to our code... @ridiculousfish?
