### ISSUE TITLE
Add a way to get the current function name

### ISSUE THREAD

**Issue by xdudi** [fish-shell/fish-shell#1743]
```
~> function test_func
       echo $_ $argv
   end
~> test_func (seq 10)
test_func 1 2 3 4 5 6 7 8 9 10
~> eval test_func (seq 10)
eval 1 2 3 4 5 6 7 8 9 10             # should be test_func
~> 
```

I would suggest to add `%this` as equivalent of `$_` for return function/script name.

**Comment by faho** [comment]
No info in >6 months. Closing.

**Comment by bucaran** [comment]
Any chances we can revive this?

See https://github.com/fish-shell/fish-shell/issues/2492

>  But why do you even need this? Surely the test_func function already knows that its name is test_func.

Because it is a good practice to not repeat oneself. I may want to automate something like displaying a usage message, etc.

**Comment by krader1961** [comment]
Note that we already have `status print-stack-trace` (which includes the name of the current function) and `status current-filename`. Adding `status current-funcname` is not unreasonable and probably straightforward.
