### ISSUE TITLE
$PATH contains spaces instead of colons

### ISSUE THREAD

**Issue by franciscolourenco** [fish-shell/fish-shell#1744]
bash -> /usr/local/bin:/usr/local/sbin:/usr/bin
fish -> /usr/local/bin /usr/local/sbin /usr/bin

Isn't this bad for programs which might need to parse $PATH and are expecting directories to be separated by colons?

**Comment by solderjs** [comment]
Is it possible for fish to read bash PATH exports?

`paths.sh`
```bash
export PATH="/new/path:$PATH"
```

```bash
source paths.sh
```

Is there an adjustment I could make so that this will work in both `fish` and `bash`?

**Comment by faho** [comment]
@solderjs: In fish >= 3.0, that'll work, as fish splits $PATH on colons

HOWEVER: In general, it can't be guaranteed that a script will work in bash and fish, and the common subset is quite small (no blocks at all - no `if` or `for`).

Also questions like this are better asked at gitter.im/fish-shell/fish-shell instead of in closed issues.

**Comment by solderjs** [comment]
Ah, I'm on fish 2.5.0

> Also questions like this are better asked at gitter.im/fish-shell/fish-shell instead of in closed issues.

However, Google can't find things on gitter (or if it can, it doesn't rank them), and since my search lead me here, it will likely lead someone else (such as future me) here again.

**Comment by faho** [comment]
>Ah, I'm on fish 2.5.0

See https://fishshell.com for our variety of PPAs and repositories, or build it yourself.

**Comment by solderjs** [comment]
Thanks. I got it working.

This is what I was creating:

# Pathman - The Cross-platform, Cross-shell PATH manager

<https://git.rootprojects.org/root/pathman>

Works on Windows, Mac, Linux, Bash, Fish, ZSH, cmd.exe, and powershell

```bash
pathman add ~/.local/bin
```

```bash
Saved PATH changes. To set the PATH immediately, update the current session:

	export PATH="/Users/me/.local/bin:$PATH"
```

It can 

* add
* remove
* list

```bash
pathman help
```
