### ISSUE TITLE
setting LANG has no effect in that particular file

### ISSUE THREAD

**Issue by Darkshadow2** [fish-shell/fish-shell#1749]
If the LANG variable is set in any source file, it won't take effect for anything output in that file.

For instance, if you edit the stock etc/config.fish file, and add `echo "¯"` at the bottom, then login again, it'll print an `Â` character before it.  (If those don't display right, they are `MACRON U+00AF UTF-8 C2 AF` and `LATIN CAPITAL LETTER A WITH CIRCUMFLEX U+00C2 UTF-8 C3 82`, respectively.)

If you create a new file, with just the contents being `echo "¯"` and source that from config.fish, it **will** display correctly.

I did make sure the encoding for config.fish was UTF-8, and I've only tested on Mac OS X (10.9.5) so I'm unsure if this is specific to it or more general.  Tested with fish version 2.1.1-1005-g1472440.

Note: If you're testing this in Terminal.app in OS X, you need to turn off `Preferences -> Settings -> Advanced tab -> Set locale environment variables on startup` or it will seem to work correctly since LANG is already set.

**Comment by krader1961** [comment]
Closing because I believe all the locale related changes in the past year have resolved this.
