### ISSUE TITLE
Add navigational commands

### ISSUE THREAD

**Issue by jonhoo** [fish-shell/fish-shell#1751]
The Bash navigation enhancements provided by [commacd](https://github.com/shyiko/commacd) are pretty interesting, and might fit well within fish's vision of making you more productive. The syntax might need to be slightly different for it to be user-friendly, but the features are undoubtedly useful,

**Comment by anordal** [comment]
Commacd describes itself as *just an improved cd*, as opposed to history based commands. No mention of bookmarks either.

My impression of its features:
* Expands short direcory names and presents ambiguities with a menu: This is pretty much what fish already does for all commands, including cd, when pressing tab. E.g. `cd /mp` expands to `cd /tmp`.
* the `,,` command can cd multiple levels up or replace components in the path, while `,,,` can cd multiple levels up plus one level down: I'm biased, but I suppose most people would rather want to edit that path interactively with fish's own completion. With [reljump](https://github.com/anordal/reljump.fish), that's what `jump -` does.

Related issues:
* cdargs #45 (bookmark based)
* mcd #2847 (history based)

**Comment by faho** [comment]
We've closed #45 and implemented #2847, so let's close this one.
