### ISSUE TITLE
cat: stdin: Resource temporarily unavailable

### ISSUE THREAD

**Issue by tyilo** [fish-shell/fish-shell#176]
After running [number-script](https://github.com/substack/number-script/) I get this error:

```
$ number-script -i
> 12345
9
> [ctrl-D]
$ cat > test
cat: stdin: Resource temporarily unavailable
```

This doesn't go away until I restart fish.
I have never seen this before, using bash and I did the exactly same thing in bash.

**Comment by justinmk** [comment]
@metamatt @ridiculousfish I really enjoyed this thread. And it likely saved us days of work on https://github.com/neovim/neovim/issues/2377.

What are your thoughts on why bash does *not* set stdin to blocking between `&&` chains? E.g.:

```
$ ./a.out 1 && ./a.out 1
stdin was formerly blocking
stdin is now nonblocking
stdin was formerly nonblocking
stdin is now nonblocking
```

Is this expected?

**Comment by ridiculousfish** [comment]
Hah, no idea. I can dig a little though since it's intriguing.
