### ISSUE TITLE
Automatically set environment variables based on working directory

### ISSUE THREAD

**Issue by jonhoo** [fish-shell/fish-shell#1765]
Environment variables are sometimes used to resolve include paths, indicate which compiler to use, etc. While having a sensible global default (i.e. in `.config/fish/fish.config`) works most of the time, some projects will require these envvars to be set to specific values for that application. Go and Java applications are prime examples (`GOPATH` and `CLASSPATH` respectively), but other examples also exist, such as projects requiring a particular C compiler (e.g. `CC=clang`).

It would be fantastic if fish could provide a feature that allows me to indicate that a particular subtree in the file system should have some particular set of environment variables. This could be taken to the extreme by allowing a function to be called when a shell enters/leaves a particular directory (or any of its children), but a simple approach more akin to vim's <a href="http://www.vim.org/scripts/script.php?script_id=441">localvimrc</a> might be sufficient. If we want to avoid the risk of security problems arising from automatically sourcing (potentially untrusted) files without resorting to whitelisting/blacklisting, an alternative would be to set per-directory settings in your fish config, but this is a strictly less useful feature.

Thoughts?

**Comment by jrobeson** [comment]
should a shell implement this directly, or should it be left to projects like direnv or plugins to fish shell frameworks.

**Comment by zanchey** [comment]
I think you're right - IMO we should leave this to external tools which can clearly elucidate the risks involved. I'll close this for now, but we're always happy to hear other opinions.
