### ISSUE TITLE
gpg --clearsign fails when using fish

### ISSUE THREAD

**Issue by necrophcodr** [fish-shell/fish-shell#1777]
So it seems that from what I can tell, fish must be related to this issue.

I am currently running Funtoo AMD64 with Fish 2.1.0-r3.

To reproduce issue: 

    gpg --clearsign
    ^D

Result:
gpg: cancelled by user
gpg: no default secret key: Operation cancelled
gpg: [stdin]: clearsign failed: Operation cancelled

**Comment by faho** [comment]
@necrophcodr: If this is still an issue for you with fish 2.2.0, please comment. In the meantime I'm closing this.
