### ISSUE TITLE
1050 new commits and no release

### ISSUE THREAD

**Issue by JelteF** [fish-shell/fish-shell#1781]
I was wondering why there hasn't been a release with all the features and fixes that have been added. Almost a quarter of the commits of this project are only usable if you build from source and the minor milestone never seems to get less open issues. 

I think it might be time to do a release and just do another one when the milestone is completed.

**Comment by Globegitter** [comment]
Any news on that? Would be great to have a new feature version soon.

**Comment by snnw** [comment]
I've just created pull-requests for #213 and #1248.  Any more blockers I can dig into? :)

**Comment by zanchey** [comment]
You're welcome to take a poke at anything on the [next-minor milestone](https://github.com/fish-shell/fish-shell/milestones/next-minor)!
