### ISSUE TITLE
Using fish in gvim

### ISSUE THREAD

**Issue by joelmo** [fish-shell/fish-shell#1792]
I use ubuntu 14.04.1 but I installed fish 2.1.1 from nix. fish 2.0.0 from ubuntu didnt work either.

In gvim (vim-gnome from ubuntu) I usually can call a command by typing `:!fish`, this works when I call bash but not fish. There are no issues when I use 'regular' vim in a terminal.

```
:!fish
fish: No TTY for interactive shell (tcgetpgrp failed)
setpgid: Inappropriate ioctl for device
shell returned 1
```

Here is a verbose output: https://gist.github.com/joelmo/c76185085927a45c239c

**Comment by krader1961** [comment]
For the record this has nothing to do with vim `set noshelltemp`. It's because the tty set up by gvim isn't the controlling tty. That causes the tcsetpgrp() call in terminal_return_from_job() to fail with errno = ENOTTY. This could be fixed but does anyone care enough to figure out the correct fix?
