### ISSUE TITLE
Double Tap menu complete like ZSH

### ISSUE THREAD

**Issue by tesfabpel** [fish-shell/fish-shell#1797]
Please add an option to have the "menu complete" (I guess it's called that way) like in ZSH (especially with oh-my-zsh)

Here is how it works:
![fish](https://cloud.githubusercontent.com/assets/1371976/4934205/333e8f00-659f-11e4-960c-6591a3c90e1a.png)

**Comment by gilvaju** [comment]
How to use? Please!
