### ISSUE TITLE
Home/End keys broken in screen when term is set to xterm

### ISSUE THREAD

**Issue by shakesoda** [fish-shell/fish-shell#180]
Steps to reproduce:

1) echo "term xterm-256color" >> ~/.screenrc
2) run screen
3) press home/end and enjoy your [1~'s and [4~'s

(note: Need term xterm so that mouse events are relayed to JOE correctly. That's probably a bug on their end, too.)

**Comment by cobrafast** [comment]
I just had a very similar issue on bare-metal fish (no screen/tmux involved).
Installed fish 2.1.1-5 from the official arch repository.

The above bind commands fix the problem, but putting them in .config/fish/config.fish for automation does not work.

Any other ideas?

**Comment by zanchey** [comment]
You need to define a `fish_user_key_bindings` function to contain them: see http://stackoverflow.com/questions/16660301/fish-programming-why-are-bind-commands-in-config-fish-not-executed

**Comment by lucasb-eyer** [comment]
I have a similar problem where I am on a remote system using urxvt where `TERM=xterm-256color` (on the remote), and home/end don't work. By following the instructions on the arch wiki linked above, I can get them to work in bash by adding the following to `~/.inputrc`:

```
"\e[7~": beginning-of-line
"\e[8~": end-of-line
```

but that doesn't seem to help fish. Adding the bindings to fish fixes it. So I'm wondering if it makes sense to add these to fish's default `fish_default_key_bindings.fish`?

```
bind $argv \e\[7~ beginning-of-line
bind $argv \e\[8~ end-of-line
```
