### ISSUE TITLE
fish syntax-highlighter for gedit and nano

### ISSUE THREAD

**Issue by VosaXalo** [fish-shell/fish-shell#1812]
Hi,
if someone is interested, I have created two fish syntax-highlighter files for the two text editor gedit and nano: fish.lang (gedit), fish.nanorc (nano). I have used the existing bash files as template. 
To use them, simply put them here:
- folder "~/.local/share/gtksourceview-3.0/language-specs"  for the **gedit editor**
- folder "/usr/share/nano/" for the **nano editor** (and update the file "/etc/nanorc")

The problem is that I don't know how and where upload them for you here on github. Can you tell me? 
Thank you.

**Comment by Freso** [comment]
I have made an AUR package for the GtkSourceView3 syntax file, if you're using Arch: https://aur.archlinux.org/packages/gtksourceview3-fish-git/

@VosaXalo Would you be okay with someone else taking these and submitting them as patches to the upstreams mentioned by @zanchey?

**Comment by VosaXalo** [comment]
@Freso Of course, it's ok for me.

**Comment by krader1961** [comment]
Seeing this type of issue makes me very happy. But in this case I think, and it seems like others agree, the editor customizations belong in those projects or a site where such customizations are typically documented rather than as part of the fish package.

**Comment by BarbzYHOOL** [comment]
Justwanted to say I tested this version and compared with this one: https://github.com/scopatz/nanorc/blob/master/fish.nanorc


And the latter is slightly better. There are more keywords highlighted

**Comment by Freso** [comment]
Finally(!) got around to making merge request for gtksourceview: https://gitlab.gnome.org/GNOME/gtksourceview/merge_requests/20

**Comment by zanchey** [comment]
Sent upstream (👏 ) by @Freso - https://gitlab.gnome.org/GNOME/gtksourceview/merge_requests/20

**Comment by Freso** [comment]
gtksourceview 4.2.0 (what `gedit` uses) was released with `.fish` syntax highlighting support: https://gitlab.gnome.org/GNOME/gtksourceview/blob/4.2.0/NEWS#L3 :)

**Comment by Freso** [comment]
Turns out it wasn't: https://gitlab.gnome.org/GNOME/gtksourceview/merge_requests/42 - sorry!
