### ISSUE TITLE
fish doesn't play well with "open terminal here" in Nautilus

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#1816]
strelec commented in #1814:

Gnome-terminal: 3.14.2
Fish 3.1.1

Not only that, I have figured out fish doesn't play well with "open terminal here" in nautilus. Speaking of this package: https://www.archlinux.org/packages/extra/i686/nautilus-open-terminal/

**Comment by fanderegg** [comment]
If you set fish as your default shell globally (http://askubuntu.com/questions/26439/how-do-i-set-fish-as-the-default-shell) and do not set is as custom command in gnome terminal, it works as it should.
