### ISSUE TITLE
Pipe on end of line

### ISSUE THREAD

**Issue by wieczorek1990** [fish-shell/fish-shell#1817]
Hi,
I want to propose a change in treating a pipe symbol on the end of line.
The following is now invalid:
```shell
echo 'fdsa' |
sed 's/fdsa/asdf/'
```
We have to type:
```shell
echo 'fdsa' |\
sed 's/fdsa/asdf/'
```
which is rather ugly.
I would like the | symbol on end of line to be treated as |\\.
This will make piped commands more readable.

**Comment by faho** [comment]
This is a duplicate of #1285.
