### ISSUE TITLE
Recursive functions directory read

### ISSUE THREAD

**Issue by wieczorek1990** [fish-shell/fish-shell#1819]
Hi,
I wanted to ask if it wouldn't be better if the ~/.config/fish/functions/ directory would be read recursively?

**Comment by faho** [comment]
This will only make the situation more confusing (because _any_ rule about which function definition would "win" is harder than no rule) and slower, so I don't think we should do this.

I intentionally left out directories when I made the conf.d stuff for this reason.

**Comment by BarbzYHOOL** [comment]
Can use symlink as a workaround
