### ISSUE TITLE
eval command in config.fish

### ISSUE THREAD

**Issue by ryanburnett** [fish-shell/fish-shell#1820]
I'm using rbenv. Using the regular ol' Terminal I have to add this to my .bash_profile:

`eval "$(rbenv init -)"`

Using fish I've added the equivalent command to my ~/.config/fish/config.fish file:

`rbenv init - | source`

This worked in fish 2.1, however, I'm running 2.1.1 now and receive this error:

```
/Users/burnettr/.config/fish/config.fish (line 18): rbenv init - | source
                                                    ^
in . (source) call of file '/Users/burnettr/.config/fish/config.fish',
    called on standard input,
```

Here's more info:

```
which rbenv
/usr/local/bin/rbenv
```

(The same path is returned whether or not I have "rbenv init - | source" in my config.fish file).

```
echo $PATH
/usr/local/bin /Users/burnettr/.node/bin /usr/bin /bin /usr/sbin /sbin /usr/local/git/bin
```

Note that I used this config.fish command to move Homebrew's /usr/local/bin to the beginning of the $PATH (https://github.com/fish-shell/fish-shell/issues/1099).

`set -e PATH[(contains -i /usr/local/bin $PATH)] ^/dev/null; set PATH /usr/local/bin $PATH`

How can I add this rbenv eval command to my config.fish file?

P.S. I'm running OS X 10.9.4 and fish 2.1.1.

**Comment by va3093** [comment]
`brew upgrade rbenv --HEAD` fixed this for me as well.
