### ISSUE TITLE
Ctrl-c can't close read with tty & pipe

### ISSUE THREAD

**Issue by leeola** [fish-shell/fish-shell#1826]
The following command fails to exit on Ctrl-C

```
echo "read foo < /dev/tty" | fish
```

Is this a bug? or is there a workaround for this?

_(Note: This is just an example to show piping into fish. Assume that the code is being piped in from cURL, or something similar, into fish.)_

**Comment by krader1961** [comment]
This has been fixed in the interim since it was opened.

**Comment by zanchey** [comment]
Well, it dies with an error message:

```
> echo "read foo < /dev/tty" | fish
<W> fish: No TTY for interactive shell (tcgetpgrp failed)
setpgid: Inappropriate ioctl for device
```

Is that the right behaviour here? I *think* so...
