### ISSUE TITLE
Feature Request: Print natively syntax-highlighted code to stdout.

### ISSUE THREAD

**Issue by geoff-nixon** [fish-shell/fish-shell#1827]
I feel like there _must_ already be a way to do this, but I just can't figure it out.

What I'd like to do is have a function, lets call it, um, `catfish`, which will print an arbitrary snippet of syntax-highlighted fish code (from file, or from stdin) _to stdout_, escape-sequences and all, so that if I redirect it to `file` and later `cat file`, it will be syntax-highlighted. (If you have pygments installed, this is basically the exact same functionality as `pygmentize -g [-f 256]`, but for fish syntax, of course.)

I know there's functionality close to this already — `commandline (cat script.fish)`, `funced` — but for my life I can't figure out how to trick it into redirecting to a fd or file. 

Is this possible?

**Comment by geoff-codes** [comment]
Forgot to say thanks for this!
