### ISSUE TITLE
Feature request: Command to expand globs without losing quoting

### ISSUE THREAD

**Issue by jonathanj** [fish-shell/fish-shell#1831]
In an attempt to implement something like zsh's behaviour of expanding the glob token at the cursor by pressing the tab key I wrote the function below and bound it to a key:

```
function expand_glob
  commandline -t (eval echo (commandline -t))
end
```

Unfortunately this loses any necessary quoting (such as spaces or characters with special meaning), I couldn't come up with a working method.

It would be convenient if there was a command that could expand a glob in a way that preserved all of this information.

**Comment by faho** [comment]
```fish
function expand_glob
    set -l tokens (eval string escape -- (commandline -ct))
    if set -q tokens[1]
        commandline -tr ""
        commandline -i -- "$tokens"
    end
end
```

should work (with 2.3.0).

This is of course a simplified version that will expand _everything_, including command substitutions.

**Comment by faho** [comment]
Okay, very evil and hackish expanded version:

```fish
function expand_glob
	# EVIL HACK: Escape globs manually, pass it to escape, and then "unescape" the globs again
	set -l tok (commandline -ct | string replace -a '*' '\*' | string replace -a '?' '\*' \
	| string escape | string replace -a '\\\\\*' '*' | string replace -a '\\\\\?' '?')
	set -l tokens
	eval set tokens "$tok"
	set -l tokens (string escape -- $tokens)
    if set -q tokens[1]
        commandline -tr ""
        commandline -i -- "$tokens"
    end
end
```

I now consider this question itself answered, we'll keep it in mind.
