### ISSUE TITLE
meta-left/meta-right bindings are wrong

### ISSUE THREAD

**Issue by mithrandi** [fish-shell/fish-shell#1836]
The default bindings have these:
```
	bind \e\[1\;9C forward-word #iTerm2
	bind \e\[1\;9D backward-word #iTerm2
```
I think these should be `prevd-or-backward-word` and `nextd-or-forward-word` instead, unless there's some reason for them to be different to the alt-left (`\e\[1\;3D`) / alt-right (`\e\\[1\;3C`) bindings.

**Comment by faho** [comment]
If anyone has a reason why these two shouldn't be ~~married~~ set to the same thing as the others, speak now or forever keep your peace. Or speak later.
