### ISSUE TITLE
Style guide for fish code

### ISSUE THREAD

**Issue by JelteF** [fish-shell/fish-shell#1838]
I wanted to update some completion files a bit and I was shocked by the amount of times some lines wrapped. I think it would be nice to have some style guide for the fish code in the repository. 

I suggest the following:
- Lines of 80 characters 
- Use 4 spaces for indentation
- Use small_snake_case for variables and functions
- Indent continued lines when possible

I'm not sure if more is needed, but this would be a nice start I think

**Comment by krader1961** [comment]
The `fish_indent` tool no longer prefers tabs; it now uses spaces for indentation. It should be authoritative  just as `gofmt` is authoritative for the Go language. Closing this as a duplicate of issue #571 where we'll tackle both fish scripts and C++.
