### ISSUE TITLE
Request: unset builtin (instead of only "set -e")

### ISSUE THREAD

**Issue by alphapapa** [fish-shell/fish-shell#1851]
Personally, I find using `set -e` to be very awkward compared to `var=` or `unset var` in Bash.  `unset` seems natural, and also much clearer, since it obviously is unsetting a var, whereas with `set -e` you have to visually distinguish a single-letter option--an option which causes the command to do the opposite of what `set` normally does.

P.S.  Thanks a lot for your work on fish.  It is a pleasure to not have to worry about quoting and expanding vars!

**Comment by alphapapa** [comment]
Just some more fish food for thought: Whenever I need to export an environment var (which isn't often), I reach for `export`, only to remember that that's for Bash.  So then I reach for `set`, and the first thing that comes to mind is `-e`, but that's for `erase`, which isn't typically a word used in the context of variables.  Then I look up the command help to be sure that it really is `-x`...again.  :)

I realize that changing `-e` to export would be a breaking change, but perhaps someday, maybe in Fish 3.0... :)

**Comment by xfix** [comment]
@alphapapa: If `set -x` feels confusing, feel free to use `setenv` instead (which is for compatibility with scripts expecting csh, but can also be used for other purposes).

**Comment by Undeterminant** [comment]
Perhaps something called `scope` would be better; this would set a variable as either local, global, universal, or exported, and the `set` builtin would only set the values of variables. Then, we could have an `unset` function to duplicate `set -e`.

**Comment by alphapapa** [comment]
I like that idea.  The differences between them are important enough that I think their commands should differ by more than a single letter option.

**Comment by faho** [comment]
Sorry, but we should not add this. There should be one way of doing this, and we already have one.

If you want to use it, feel free to define your own function.
