### ISSUE TITLE
request for better output if a directory disappears underneath fish

### ISSUE THREAD

**Issue by The-Alchemist** [fish-shell/fish-shell#1857]
I used ``prevd`` to get to a previous directory I was in, forgetting that I had ``rm -r``'ed it.

I got this:
```
> prevd
> pwd
[12:46:58] me@host  1()
>
[12:47:00] me@host  1()
> ls
[12:47:00] me@host  0()
>
```
Can I suggest an error message, or something?

**Comment by zanchey** [comment]
HNY!

Have you been able to reproduce this at all?

**Comment by The-Alchemist** [comment]
@zanchey : I finally made a screencast showing this: http://screencast.com/t/d2WkG8sb

What do you think?

**Comment by ridiculousfish** [comment]
Nice.

**Comment by zanchey** [comment]
Ah, I was confused by `prevd` - so the directory was removed after you changed to it.

`bash` and `zsh` are similarly unhelpful:

Bash:
```bash
~$ mkdir /tmp/a
~$ cd /tmp/a
/tmp/a$ /bin/rmdir /tmp^C
/tmp/a$ pwd
/tmp/a
/tmp/a$  /bin/rmdir /tmp/a
/tmp/a$ pwd
/tmp/a
/tmp/a$ ls
/tmp/a$ cd .
cd: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
/tmp/a/.$
```

zsh:
```bash
~ % mkdir /tmp/a
~ % cd /tmp/a
/tmp/a % pwd
/tmp/a
/tmp/a % /bin/rmdir /tmp/a
/tmp/a % ls
/tmp/a % pwd
/tmp/a
/tmp/a % cd .
. % ls
. % pwd
.
. %
```

I'm actually not sure what the right thing to do in this situation is. The directory still "exists" because it is the CWD (`stat .` will still work), but `readdir` will fail because the directory has no entries.

**Comment by The-Alchemist** [comment]
Sorry about confusing you with ``prevd``.

The ``0()`` in the fish prompt confuses me, so I feel like either bash or zsh's approach is preferable to fish's (I personally like bash's).

**Comment by zanchey** [comment]
Where does the `0()` in your prompt come from?

**Comment by The-Alchemist** [comment]
I'm using the stock 'Informative' prompt.

**Comment by ridiculousfish** [comment]
The stock informative prompt uses `printf` to output the prompt. One of the arguments is (pwd). If the directory is gone, then pwd doesn't output anything, and so doesn't become an argument. All of the arguments then get off by one.

**Comment by ridiculousfish** [comment]
I interpret this as just a bug in the informative prompt, and I fixed it by replacing (pwd) with $PWD. Please comment if you think this ought to be a more substantive fix. Thanks for reporting it!

**Comment by The-Alchemist** [comment]
@ridiculousfish : Not a problem, thanks for fixing it :)
