### ISSUE TITLE
fish_config broken in Ubuntu

### ISSUE THREAD

**Issue by ghost** [fish-shell/fish-shell#1860]
Hi all,

Thanks for writing this amazing shell, I'm really enjoying it so far ;-)

One minor issue though, fish_config isn't working. When I run it, it gives this output in the terminal:

```
$ fish_config 
Web config started at 'http://localhost:8000/'. Hit enter to stop.
Created new window in existing browser session.
127.0.0.1 - - [21/Dec/2014 11:45:33] code 404, message File not found
127.0.0.1 - - [21/Dec/2014 11:45:33] code 404, message File not found
```

The page opened in the browser does display the general structure of the config interface, but it's missing some stuff. Here's a picture:

![Broken web interface](http://i.imgur.com/NN2IndJ.png)

Also none of the buttons are responsive, nothing happens when I click anywhere in there.

My first thought was that maybe ubuntu packagers split some files out into a separate package that I didn't install, but I wasn't able to discover the name of that package. Since the ubuntu package is called `fish` I would expect such a package to be named `fish-web` or similar, but the only package that matches `^fish-.*` is `fish-dbg` which is of course just the debug symbols and doesn't help.

```
$ apt-cache policy fish
fish:
  Installed: 2.1.0-1
  Candidate: 2.1.0-1
  Version table:
 *** 2.1.0-1 0
        500 http://ca.archive.ubuntu.com/ubuntu/ utopic/universe amd64 Packages
        100 /var/lib/dpkg/status
```

Any help is appreciated! Thanks!

**Comment by spider623** [comment]
pasting this from @zanchey 's comment into the terminal using root 

ln -s /usr/share/javascript/jquery/jquery.js /usr/share/fish/tools/web_config/jquery.js

does fixes the issue on the ubuntu repo package so it's not that bad
