### ISSUE TITLE
Bugs in Prompt

### ISSUE THREAD

**Issue by SolarAquarion** [fish-shell/fish-shell#1869]
/usr/share/fish/functions/fish_prompt.fish (line 6): prompt_pwd
                                                     ^
in command substitution
        called on line 26 of file “/usr/share/fish/functions/fish_prompt.fish”,
 
in function “fish_prompt”,
        called on standard input,
 
in command substitution
        called on standard input,

**Comment by zanchey** [comment]
@SolarAquarion, have you managed to sort this out?

**Comment by ridiculousfish** [comment]
No response in a while, let's close. @SolarAquarion feel free to comment and we'll reopen.
