### ISSUE TITLE
Fuzzy history command match

### ISSUE THREAD

**Issue by iven** [fish-shell/fish-shell#1874]
It may be useful if we can use fuzzy match when searching history commands(using the UP arrow).

Say we have command history like this:

```
scp 1.txt myhost1:/tmp
ssh myhost1
scp 2.txt myhost2:/root
ssh myhost123
...
```

Currently it's hard to match the first command. If we have fuzzy match, we can just use:

```
$ scphost1<UP ARROW>
```

to match it.

Also it would be great if we exactly match the whole string first, and use fuzzy match as backup.

And maybe we need an UI menu like [ctrlp.vim](https://github.com/kien/ctrlp.vim).

**Comment by terlar** [comment]
For now there is a third party util that will achieve this for you, that comes with fish integration:
https://github.com/junegunn/fzf

**Comment by iven** [comment]
@terlar Seems it doesn't support history completion...

**Comment by terlar** [comment]
It does:
https://github.com/junegunn/fzf/blob/master/install#L305-L310

It binds it to a ctrl-r binding by default which can be modified to your liking.

**Comment by iven** [comment]
Thanks, I didn't see that in README. I'll try it.

2015-01-07 15:58 GMT+08:00 Terje Larsen <notifications@github.com>:

**Comment by karolyi** [comment]
+1

**Comment by c02y** [comment]
It is May 24, 2017 now, it seems this feature is not implemented yet.

**Comment by krader1961** [comment]
> It is May 24, 2017 now, it seems this feature is still not implemented yet.

Patches are welcomed and will be reviewed in a timely manner. Alternatively, I'm starting to think we should setup a [open source code bounty](https://en.wikipedia.org/wiki/Open-source_bounty) for fish. That way people who really want some feature implemented but lack the skills to do so themselves can entice others to work on the feature.

**Comment by c02y** [comment]
Good idea.

**Comment by ElijahLynn** [comment]
Would love this feature, one of the biggest things I find myself wanting on an hourly basis! Love the idea of open source code bounty for fish. www.bountysource.com is an option.

**Comment by NotWearingPants** [comment]
There's exactly this, but only for bash & zsh:
https://github.com/dvorka/hstr

**Comment by ElijahLynn** [comment]
This has been working for me, but I do wonder if I installed 

> It does:
> https://github.com/junegunn/fzf/blob/master/install#L305-L310
> 
> It binds it to a ctrl-r binding by default which can be modified to your liking.

I installed fzf with Fisher a while ago and this is perfect for fuzzy history matching! `ctrl + r` brings up an interactive search, with fuzzy matching!

**Comment by Kejia** [comment]
install _fzf_:
`$ fisher add jethrokuan/fzf`
or
`$ omf install https://github.com/jethrokuan/fzf`
see: https://github.com/jethrokuan/fzf

**Comment by elebow** [comment]
I'd love to attempt implementing this, but I'm new to the codebase and haven't done C++ in a long time, so I would appreciate some advice from someone more experienced. At a glance, I think it would go something like this:

1. Add a new `history_search_type_t` called `contains_subsequence` (which I think is a more accurate name for the behavior) and implement the logic (in `history.cpp`?).
1. Define a variable to configure the type of matching for the history pager. Something like `fish_history_pager_match_type`.
1. Use the new variable to conditionally use different logic when searching at https://github.com/fish-shell/fish-shell/blob/a322e3f180800898c62cdbb4f818e07d1c89ef9d/src/reader.cpp#L1289

Does that sound correct, or at least a reasonable start?

**Comment by krobelus** [comment]
that sounds like a good start.
Probably history search (and history pager) should by default fall back to subsequence matching if there are no substring matches.
That would eliminate the need for https://github.com/fish-shell/fish-shell/pull/9451

**Comment by krobelus** [comment]
> Define a variable to configure the type of matching for the history pager

I think we want to avoid that variable because the tiered behavior is almost always better.
If we did add it, it would be a separate special input function next to `history-pager` - we do the same for history search

**Comment by krobelus** [comment]
The control-r history search now falls back to fuzzy matching.
Maybe we want the same for up-arrow search.
