### ISSUE TITLE
Changing directory incredibly slow

### ISSUE THREAD

**Issue by montauk** [fish-shell/fish-shell#1878]
Whenever I try to change to a certain directory, such as `cd ~/Documents`, fish shell takes an incredibly long time to run the command. Pressing `Ctrl + C` doesn't have an effect either, so I assume it temporarily freezes up, yet does load the directory eventually, after a few minutes. Opening these directories in bash takes less than a second. 

I assume the issue may be resolved by completely getting rid of fish and all its files, and reinstalling it. But I'd like to ask first if there are any certain files I should be looking for, before I choose the nuclear option?

**Comment by montauk** [comment]
Figured it out just now: I had a few lines in my `fish_prompt.fish` that were checking the status of my git repository. Removing said lines fixed the issue.

**Comment by zanchey** [comment]
In that case, I shall close the issue.  It might be worth inspecting some of the sample Git prompts, as they generally use the fastest Git methods for various operations, although huge git repos will always have some slow operations.

**Comment by YayConnolly** [comment]
Thanks for following up with your solution, I was having the exact same issue.
