### ISSUE TITLE
no ALT keystrokes work with Command-line editing

### ISSUE THREAD

**Issue by jschank** [fish-shell/fish-shell#1880]
On a mac - in iTerm2
None of the keystrokes that use ALT modifier work for command line editing. Instead I am getting symbols to appear.

For example Alt-P which is supposed to append pager, instead prints a Pi character
Likewise, Alt-W, which should print a short description, instead prints a Capital Sigma character

Can someone advise on how to fix this?

**Comment by bucaran** [comment]
Command , -> Profiles -> Keys
Left option key acts as: Normal Meta +Esc

I think you need +Esc

**Comment by jschank** [comment]
Absolutely! Thank you for the reply. I've been trying to google this problem for a while now, and I just didn't know enough about how to ask the right search query.

This might be extremely helpful to post in the FAQ section. (or not, I might be the only idiot with this problem)

**Comment by bucaran** [comment]
No problem. You would encounter the same issue with Terminal.app where you would need to remap Alt to the meta key. I wouldn't know for sure as I haven't touched Terminal.app in a while though.

**Comment by srang** [comment]
So I'm using i3wm and alt is my $mod and I have it fairly ingrained as such. Is there anyway to remap fish shell's modifier key to something else? I'm okay with modifying code if that is what it takes...

**Comment by bucaran** [comment]
http://fishshell.com/docs/current/commands.html#bind

**Comment by srang** [comment]
Awesome thanks! I should have looked harder...

**Comment by bucaran** [comment]
:smile:
