### ISSUE TITLE
Empty function returns 1 when eval is used.

### ISSUE THREAD

**Issue by bucaran** [fish-shell/fish-shell#1881]
Create a new `test` file and run `fish test`:

```fish
function one
#...
end

one
  or echo ERROR

eval one
  or echo ERROR
```

My output:

```
$ ERROR
```

This is a contrived example, but empty functions should not return 1. This will also fail if there are only `set` statements in my functions which seem to not modify the `$status` variable (unless there is a `(command)` on the right side of course)

What's happening here?

**Comment by ridiculousfish** [comment]
What I see on ToT is that empty functions do not modify `$status`. I am not convinced this is the right behavior (but it doesn't seem obviously wrong either).

`set` deliberately avoids modifying `$status` on success - see #214.

**Comment by bucaran** [comment]
But why does it fail only when invoking the function via `eval`?

**Comment by ridiculousfish** [comment]
I can't reproduce that. What I see is that running `one` directly does not modify `$status`, and `eval one` will set `$status` to 0 (success) because the evaluation succeeded.

**Comment by bucaran** [comment]
![eval](https://cloud.githubusercontent.com/assets/8317250/5693017/d05c1d1a-994e-11e4-9d12-83af9cd335da.gif)

**Comment by bpinto** [comment]
```
.oh-my-fish:master* λ cat eval

function one
#...
end

one
echo $status

eval one
echo $status
.oh-my-fish:master* λ fish eval
0
0
.oh-my-fish:master* λ fish --version
fish, version 2.1.1-1172-g34db676
```

**Comment by bucaran** [comment]
That's funny. I will try reinstalling Fish later or check if it was a problem with iTerm.

**Comment by ridiculousfish** [comment]
Ok, I get it now. The `source` call that is used to implement `eval` doesn't modify `$status` upon completion. If the code that is executed by source (i.e. `one`) doesn't modify $status either, then `$status` retains its value from the call preceding the `source`. That's this code (from `eval`):

    if status --is-interactive
        status --job-control full
    end

so a key difference is whether the code is run interactively (by typing it in at the console) or non-interactively (e.g. sourced from a file).

Probably the right fix here is to make `eval` not modify the exit status, which means saving and restoring it around the junk preceding the `source` line in `eval.fish`. Unfortunately this is a little awkward. One way would be to wrap that junk in a function, and pass it the exit status it should return. Another would be to execute either `true` or `false` depending on the desired status, but that introduces unnecessary forking. Anyone have a better idea?

**Comment by bpinto** [comment]
> Probably the right fix here is to make `eval` not modify the exit status.

```
.oh-my-fish:master λ eval "true"
.oh-my-fish:master λ echo $status
0
.oh-my-fish:master λ eval "false"
.oh-my-fish:master λ echo $status
1
```

Is that what you meant?

**Comment by ridiculousfish** [comment]
What I meant is that eval itself won't touch the exit status (unless eval fails, e.g. the eval'd code is unparseable). Only the code that is evaluated should modify the exit status.

**Comment by bucaran** [comment]
@bpinto Just in case you were wondering, this does not affect our implementation of `fish-spec`.

**Comment by bucaran** [comment]
@ridiculousfish Please check again.
I have tried reinstalling Fish, building Fish directly, disabling Oh-My-Fish, etc., and the behavior persists.

```fish
function one
end

if one
  echo OK
else
  echo ERROR
end

if eval one
  echo OK
else
  echo ERROR
end
```

**Comment by bucaran** [comment]
@ridiculousfish OK I understand the problem now. Will try to write an eval wrapper that does what I need.

EDIT: Submitted a [PR](https://github.com/fish-shell/fish-shell/pull/1892) with as simple fix.
