### ISSUE TITLE
How does fish print the suggestions?

### ISSUE THREAD

**Issue by IngwiePhoenix** [fish-shell/fish-shell#1882]
Hey.

I am starting to really enjoy Fish. It is sad, that it relies only on UNIX and hence is heavily incompatible with Windows without a UNIX wrapper.

But my most favorite feature happens to be the printed suggestions. Boy. This just looks like magic to me!

What file would I look at to see how these suggestions are printed?

Kind regards, Ingwie

**Comment by zanchey** [comment]
Autosuggestionsare handled by `reader.cpp`: have a look at `struct autosuggestion_context_t` as a starting point.

**Comment by ridiculousfish** [comment]
In case this was your question, the autosuggestions are just gray text appended after the cursor.

**Comment by IngwiePhoenix** [comment]
Yeah, and I simply wondered how. x) But I will be able to see it in the file, when I finally can get my computer to behave...
