### ISSUE TITLE
100% cpu usage

### ISSUE THREAD

**Issue by snahor** [fish-shell/fish-shell#1886]
Pardon me for not adding this as a comment in the other issues.

As mentioned in other issues, I've used `gdb` with `thread apply all bt full`. This is the output: https://gist.github.com/snahor/db6b8f54ba78d58c7970.

This happened after I pressed tab to complete a path. I don't know if this is related, but when using tab to complete a path it's kind of slow.

**Comment by zanchey** [comment]
Unfortunately, you don't have any debugging symbols installed so there's not enough information for me to decipher anything.

If you can tell us what version you are running and how you installed fish, then perhaps we can get some debug symbols installed.

Were you completing a path on a non-local filesystem (NFS or Samba, for example)? Can you reproduce it?

**Comment by faho** [comment]
No info in >6 months. Closing.
