### ISSUE TITLE
Add support for cd'ing up directory tree with more than two dots; e.g., "..."

### ISSUE THREAD

**Issue by dannylevenson-ps** [fish-shell/fish-shell#1891]
Fish already supports "..", "../..", etc. as shortcuts commands for cd'ing to parent directories in a directory tree.  On Windows, I have been a long time user of TakeCommand formerly known as 4DOS and 4NT.  The command line in this environment supports typing an arbitrary number of dots to traverse up a directory tree.  For example instead of typing "../.." to go up two directories, you would type "...".  Instead of "../../..", you would type "....".

I admit that visually, it's easier to verify the number of directories you will be traversing upwards before hitting enter with the ../.. notation.  But, a string of dots is easier and quicker to type if you can keep track of where you are as you are typing them.

It has been a very long time since I have done any C/C++ programming, so rather than trying to figure out if/how this feature could be added, I am making a request.

**Comment by bucaran** [comment]
Just add a function in your `~/.config/fish/config.fish` file. If there isn't one, create it.

```fish
function ...
  ../..
end
function ....
  ../../..
end
```

**Comment by dannylevenson-ps** [comment]
That works, although it does not provide support for an arbitrary number of dots.  I added ..., .... and ..... which should suffice for most of my use cases.

That leads to a different question.  For short alias type functions, is it better to create func.fish files in the ~/.config/fish/functions directory or is it better to add the functions to ~/.config/fish/config.fish?

**Comment by bucaran** [comment]
I prefer [using a framework](https://github.com/bpinto/oh-my-fish/) to handle my Fish, but other than that I would recommend keeping a `functions` directory prepended to the `$fish_function_path` global variable.
```
..... 
```
:laughing: That's awesome!

**Comment by bpinto** [comment]
I think the recommended way to alter the $PATH variable is to change the `$fish_user_paths` variable:

`set --universal fish_user_paths $fish_user_paths ~/path/name`

**Comment by pwr22** [comment]
. and .. are specially reserved filenames in most sensible filesystems but ... and above are not. How would this be handled?

**Comment by nyobe** [comment]
Heya, I was annoyed by this as well, so I adapted this function from Zsh. It checks if you're about to type a third period in the commandline, and if so, expands it to `/..` instead, which allows for arbitrary numbers of dots :)  Beware that it seems to mess up a bit when pasting text, but I hope that's been fixed by #1633

`bind . 'expand-dot-to-parent-directory-path'`

```fish
function expand-dot-to-parent-directory-path -d 'expand ... to ../.. etc'
    # Get commandline up to cursor
    set -l cmd (commandline --cut-at-cursor)

    # Match last line
    switch $cmd[-1]
        case '*..'
            commandline --insert '/..'
        case '*'
            commandline --insert '.'
    end
end
```

**Comment by krader1961** [comment]
Issue #2671 also requested this and has been closed will-not-implement so doing the same here.

**Comment by buggymcbugfix** [comment]
@nyobe Very cool little function, thanks. I've added it to my config with a small modification: expand `...` to `../.` which makes it easier to type e.g. `../.foo`. 

Also for reference you can't just `bind` in your `.config`, but you need to set `fish_key_bindings` (curtesy of @kballard  #1495).

~~~fish
function expand-dot-to-parent-directory-path -d 'expand ... to ../.. etc'
    # Get commandline up to cursor
    set -l cmd (commandline --cut-at-cursor)

    # Match last line
    switch $cmd[-1]
        case '*..'
            commandline --insert '/.'
        case '*'
            commandline --insert '.'
    end
end

function my_key_bindings
    fish_default_key_bindings
    bind . 'expand-dot-to-parent-directory-path'
end

set -g fish_key_bindings my_key_bindings
~~~
