### ISSUE TITLE
Pasting JSON causes Fish to hang on OSX, disconnect in Ubuntu

### ISSUE THREAD

**Issue by trahma** [fish-shell/fish-shell#1893]
While working within Fish I accidentally pasted JSON content in my clipboard which caused fish to use 400% of my CPU, eventually lowering down to 30% which then caused kernel_task to spike to 80-100% and hold for over 15 minutes.  Attempting to replicate this on a remote Ubuntu, it causes my SSH connection to close out.
# JSON Sample

{"preview":true,"offset":0,"result":{"client_ip":"","count":""}}
{"preview":true,"offset":1,"result":{"client_ip":"","count":""}}
{"preview":true,"offset":2,"result":{"client_ip":"","count":""}}
{"preview":true,"offset":3,"result":{"client_ip":"","count":""}}
{"preview":true,"offset":4,"result":{"client_ip":"","count":""}}
{"preview":true,"offset":5,"result":{"client_ip":"","count":""}}
{"preview":true,"offset":6,"result":{"client_ip":"","count":""}}
{"preview":true,"offset":7,"result":{"client_ip":"","count":""}}
{"preview":true,"offset":8,"lastrow":true,"result":{"client_ip":"","count":""}}
{"preview":false,"offset":0,"result":{"client_ip":"0","count":""}}
{"preview":false,"offset":1,"result":{"client_ip":"","count":""}}
{"preview":false,"offset":2,"result":{"client_ip":"","count":""}}
{"preview":false,"offset":3,"result":{"client_ip":"","count":""}}
{"preview":false,"offset":4,"result":{"client_ip":"","count":""}}
{"preview":false,"offset":5,"result":{"client_ip":"","count":""}}
{"preview":false,"offset":6,"result":{"client_ip":"","count":""}}
{"preview":false,"offset":7,"result":{"client_ip":"","count":""}}
{"preview":false,"offset":8,"lastrow":true,"result":{"client_ip":"","count":""}}

**Comment by ridiculousfish** [comment]
Heh, cute. fish interprets this as brace expansion, which will cause a combinatoric explosion because each brace has multiple elements in it. bash and zsh are vulnerable to this as well.

**Comment by trahma** [comment]
I actually tested bash and zsh as well because I was curious about that.. They both spiked usage but never > 5%.  I'm know this is a huge edge case, but was pretty interesting.

**Comment by ridiculousfish** [comment]
bash and zsh will die if you pass that JSON to echo and then hit return. I guess fish is more vulnerable because it attempts to expand the string before execution (for syntax highlighting, etc) so you don't have to hit return.

**Comment by krader1961** [comment]
The recent bracketed-paste enhancement by @faho appears to fix this issue.
