### ISSUE TITLE
break modifies $status

### ISSUE THREAD

**Issue by bucaran** [fish-shell/fish-shell#1895]
Is this the expected behavior? 
[Link to source implementation](https://github.com/fish-shell/fish-shell/blob/d4eded2376706c67b680ad522e61cbe54d8214b0/builtin.cpp#L3731
)

```fish
while true
  # ...
  eval false
  break
end
echo $status
```
I was expecting 1.
```
$ 0
```

Perhaps `builtin_break_continue` could return a `STATUS_BUILTIN_OK_WITH_0` or ``STATUS_BUILTIN_OK_WITH_1` depending on that loop's last `$status` change?

**Comment by zanchey** [comment]
For reference, bash and zsh both return 0.

**Comment by bucaran** [comment]
Closed as it seems to be the standard behavior across shells.
