### ISSUE TITLE
fish: Unable to parse universal variable message: ''

### ISSUE THREAD

**Issue by nakal** [fish-shell/fish-shell#1899]
I wanted to try out fish and got this error message with fish hanging forever. All I can do is to kill it from another xterm.

I am using FreeBSD-10.1/amd64. I installed version 2.1.1 (revision 2) from ports. I started it from `tcsh` (by typing `fish`) and inside a fresh xterm (`xterm -e fish`), same effect.

**Comment by ridiculousfish** [comment]
What's the contents of the file `~/.config/fish/fishd.*`?

**Comment by zanchey** [comment]
I'm fairly certain this is because of a breaking change between 10.0 and 10.1 - see #1741 and the thread at http://sourceforge.net/p/fish/mailman/message/33166022/. I did send the patch to the FreeBSD maintainer a couple of months ago but I will trying pinging them again.

**Comment by ridiculousfish** [comment]
Nice catch zanchey.

**Comment by nakal** [comment]
There is just a generated configuration for my host which is empty except for comments. I have not made any settings yet.

`iconv --list` gives me no `WCHAR_T` here. It might be some encoding problem, because between the '' in the message seems to be something invisible unpastable.

**Comment by nakal** [comment]
After gathering information how to fix it, I committed [a patch for the FreeBSD port](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=196661#c4). This is not your bug, it's a configuration bug in the FreeBSD ports tree.

**Comment by zanchey** [comment]
Does that work? I don't really understand the `USE` stuff in the ports tree. I had a patch for fish that solved the problem:

```diff
diff --git a/env_universal_common.cpp b/env_universal_common.cpp                                
index 2b12cf1..2992a88 100644                                                                   
--- a/env_universal_common.cpp                                                                  
+++ b/env_universal_common.cpp                                                                  
@@ -151,6 +151,7 @@ static const char *iconv_wide_names_4[]=                                    
 {                                                                                              
     "wchar_t", "WCHAR_T",                                                                      
     "wchar", "WCHAR",                                                                          
+    "UCS-4-INTERNAL",                                                                          
     "ucs-4", "UCS-4",                                                                          
     "ucs4", "UCS4",                                                                            
     "utf-32", "UTF-32",                                                                        
```

**Comment by zanchey** [comment]
Anyhow I am going to close this as it has been forwarded downstream - many thanks.

**Comment by wilhelmy** [comment]
Ah, yes, I've been commenting on the wrong issue. This is the bug I'm affected by. I manually applied this patch on top of the ports tree and the issue remains.

**Comment by wilhelmy** [comment]
```
$ cat .config/fish/fishd.*
# This file is automatically generated by the fishd universal variable daemon.
# Do NOT edit it directly, your changes will be overwritten.
```

**Comment by zanchey** [comment]
Both patches on the bug work for me; make sure you kill any instances of fish or fishd before trying the new version.

**Comment by wilhelmy** [comment]
I did.

**Comment by zanchey** [comment]
OK, I can't repro with either of the patches, so the output of truss or similar on `fish` and `fishd` might be helpful.

**Comment by wilhelmy** [comment]
`iconv --list` output: http://ix.io/g7Y

Also interesting: starting fish now yields the following
```
fish: Unable to parse universal variable message: '��������������������������������'
```
While it was definitely '' before.

Here's the output of `truss fish`: http://barfooze.de/tmp/fish.truss.txt
And here's `truss -f fish` which includes the forked fishd process: http://barfooze.de/tmp/fish.truss-f.txt

**Comment by wilhelmy** [comment]
Aah, I see. These characters just weren't visible while running fish outside of screen.
```
$ fish 2> /tmp/fish.log
[killing fish on another terminal]
Terminated
$ hd /tmp/fish.log 
00000000  66 69 73 68 3a 20 55 6e  61 62 6c 65 20 74 6f 20  |fish: Unable to |
00000010  70 61 72 73 65 20 75 6e  69 76 65 72 73 61 6c 20  |parse universal |
00000020  76 61 72 69 61 62 6c 65  20 6d 65 73 73 61 67 65  |variable message|
00000030  3a 20 27 fc a3 80 80 80  80 fc a0 80 80 80 80 fd  |: '.............|
00000040  86 80 80 80 80 fd a9 80  80 80 80 fd b3 80 80 80  |................|
00000050  80 fd a8 80 80 80 80 fc  a0 80 80 80 80 fd b5 80  |................|
00000060  80 80 80 fd ae 80 80 80  80 fd a9 80 80 80 80 fd  |................|
00000070  b6 80 80 80 80 fd a5 80  80 80 80 fd b2 80 80 80  |................|
00000080  80 fd b3 80 80 80 80 fd  a1 80 80 80 80 fd ac 80  |................|
00000090  80 80 80 fc a0 80 80 80  80 fd b6 80 80 80 80 fd  |................|
000000a0  a1 80 80 80 80 fd b2 80  80 80 80 fd a9 80 80 80  |................|
000000b0  80 fd a1 80 80 80 80 fd  a2 80 80 80 80 fd ac 80  |................|
000000c0  80 80 80 fd a5 80 80 80  80 fc a0 80 80 80 80 fd  |................|
000000d0  a4 80 80 80 80 fd a1 80  80 80 80 fd a5 80 80 80  |................|
000000e0  80 fd ad 80 80 80 80 fd  af 80 80 80 80 fd ae 80  |................|
000000f0  80 80 80 27 0a                                    |...'.|
000000f5
```

**Comment by zanchey** [comment]
The other thing I meant to ask you to check is the output of `locale`.

**Comment by wilhelmy** [comment]
```
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_ALL=
```

**Comment by wilhelmy** [comment]
Ha! If I `export LC_ALL=C` it hangs at `fish:` like in one of the other bug reports.
