### ISSUE TITLE
Doesn't install man as a dependency in Ubuntu

### ISSUE THREAD

**Issue by pwr22** [fish-shell/fish-shell#1901]
Using the Ubuntu ppa the package does not mark man as a dependency. This makes some things emit fishy errors until it is installed

As an example use `echo -h` and you'll get

    fish: Unknown command “nroff”
    /usr/share/fish/functions/__fish_print_help.fish (line 3): nroff -man "$__fish_datadir/man/man1/$item.1" ^ /dev/null 
                                                               ^
    in command substitution
	    called on line 31 of file “/usr/share/fish/functions/__fish_print_help.fish”,

    in function “__fish_print_help”,
	    called on standard input,
	    with parameter list “echo”

    in command substitution
	    called on standard input,

**Comment by pwr22** [comment]
nroff is provided by groff-base, a dependency of man, and this alone fixes the echo issue above. However fish does still seem to assume the existence of man which leads to confusing errors

Run `man echo` and get

    fish: Unknown command “man”
    /usr/share/fish/functions/man.fish (line 2): command man --path
                                                         ^
    in command substitution
	    called on line 11 of file “/usr/share/fish/functions/man.fish”,

    in function “man”,
	    called on standard input,
	    with parameter list “echo”

    fish: Unknown command “man”
    /usr/share/fish/functions/man.fish (line 14): 			command man $argv
                                                                                  ^
    in function “man”,
	    called on standard input,
	    with parameter list “echo”

**Comment by zanchey** [comment]
I think maybe a `Depends` on `groff-base` and a `Recommends` on `man`, then teach `man.fish` to check for the existence of the binary first?

**Comment by pwr22** [comment]
That sounds sensible, since the nroff issue is in the fish help function that probably can't be replaced easily to drop the dependency on nroff, looks like it parses help files in a man'ish format?

Are the deb building resources in the repo or is the building handled externally?

**Comment by zanchey** [comment]
They're in https://github.com/zanchey/fish-build

**Comment by zanchey** [comment]
Actually the PPA packages should already depend on `man-db`, not sure what's going on there.

**Comment by pwr22** [comment]
It does indeed, I'll spin up a fresh container and install fish again keeping an eye on what happens

**Comment by pwr22** [comment]
On the clean container It works fine, I'm wondering if I was installing the older version from the ubuntu repos when this happened, I can't explain it but it happened twice on two different machines, eitherway I'll close this issue

**Comment by pwr22** [comment]
I must have been mixing up the fish from the ubuntu repos with the ppa version. The latter works fine and the former is what had the issues here, sorry for the mistake
