### ISSUE TITLE
Add ASCII fish shell artwork to README.md

### ISSUE THREAD

**Issue by pickfire** [fish-shell/fish-shell#1903]
Add the ASCII fish shell in http://fishshell.com to README.md.

**Comment by zanchey** [comment]
If you want it, it's available [on the mailing list](http://comments.gmane.org/gmane.comp.shells.fish.user/3671)!

**Comment by xfix** [comment]
Alternatively, if you want a graphical version, it's available in https://github.com/fish-shell/fish-shell/issues/114#issuecomment-24101750.

**Comment by krader1961** [comment]
I see no point in implementing this but I'm going to leave it open and unassign floam in case someone else wants to address this issue.

**Comment by mdesantis** [comment]
Hi, fish user here!

If you really intend to add

```

                  ___
   ___======____=---=)
 /T            \_--===)
 L \ (@)   \~    \_-==)
  \      / )J~~    \-=)
   \\___/  )JJ~~    \)
    \_____/JJJ~~      \
    / \  , \J~~~~      \
   (-\)\=|  \~~~        L__
   (\\)  ( -\)_            ==__
    \V    \-\) ===_____  J\   \\
           \V)     \_) \   JJ J\)
                       /J JT\JJJJ)
                       (JJJ| \UUU)
                        (UU)
```

to the README.md, I could take care of it. Just tell me where you wish it to be placed.

**Comment by ridiculousfish** [comment]
Honestly I'd rather not, the README.md is too long already. Thanks for offering though!
