### ISSUE TITLE
fish in emacs will start with some messages

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#1907]
When I use `shell` (not `eshell` or `ansi-term` or `term`) in Emacs, it will execute `fish` as `shell`, 

1). it will definitely start with these messages in the `shell` buffer:

     ^[]0;fish  /home/chz^Gbind: Key with name “down” does not have any mapping
     bind: Key with name “up” does not have any mapping
     bind: Key with name “right” does not have any mapping
     bind: Key with name “left” does not have any mapping
     bind: Key with name “dc” does not have any mapping
     bind: Key with name “backspace” does not have any mapping
     bind: Key with name “ppage” does not have any mapping
     bind: Key with name “npage” does not have any mapping

2). And every time  I run a command (such as `ls`) in it, it will insert a message at the beginning of the output:

    ^[]0;ls  /home/chz/dir^Gfile1 file2 ...

3). Every time  I run a command (such as `ls` or even just `Enter`), it will list double lines of  `chz@localhost ~> ls` or `chz@localhost ~> ` then the output of the commands.

These all will happen whether or not my `config.fish` file is empty ( I remove all `~/.config/fish` away).

**Comment by zanchey** [comment]
What version are you running? #1155 covers the first problems but is not in a released version.

What does `echo $TERM` output?

**Comment by c02y** [comment]
$ echo $TERM
    xterm-256color

**Comment by zanchey** [comment]
OK, this looks like an attempt to write the window title to a terminal which doesn't support it. The heuristic for working out whether to write the title is not fantastic - the `dumb` terminal type should probably be added.

In the meantime, you can work around with something like this in your config.fish:

```
if test "$TERM" = "dumb"
    function fish_title; end
end
```

**Comment by c02y** [comment]
OK, not the `^[]0;fish  /home/chz^G` in every command's output is gone, the 2nd problem is solved.

The 3rd problem is still there. Any clue about the double lines?

**Comment by zanchey** [comment]
That might be #1411.

**Comment by c02y** [comment]
No, according to #1411, fish in `ansi-term` prints an extra "⏎", but as I said at the first beginning of this post, I'm using `shell` not `ansi-term` or `eshell` or `ansi` in Emacs, and there isn't any extra "⏎" in the output of commands in my `shell`, actually the extra "⏎" symbol and other extra abnormal messages exist in my `ansi-term` too, but I do not use it, so here my problem is in shell of Emacs.

Let me list some examples of this problem:

    # this is my original text in the shell in Emacs, note that my prompt is in the second line, `|` is my cursor
    chz@localhost: ~/Projects/Go/exercism-cli 
    ➤➤ |

    # if I type `Enter` key at `|` symbol, it will be (including the original text):
    chz@localhost: ~/Projects/Go/exercism-cli 
    ➤➤ 
    chz@localhost: ~/Projects/Go/exercism-cli 
    ➤➤
    chz@localhost: ~/Projects/Go/exercism-cli 
    ➤➤ |

    # if I type ls after the original text, it will be (including the original text):
    chz@localhost: ~/Projects/Go/exercism-cli 
    ➤➤ ls
    chz@localhost: ~/Projects/Go/exercism-cli 
    chz@localhost: ~/Projects/Go/exercism-cli 
    ➤➤ ls
    cli/  README
    chz@localhost: ~/Projects/Go/exercism-cli 
    ➤➤ |

**Comment by zanchey** [comment]
Leaving this open to track the second problem.
