### ISSUE TITLE
Functions with inner block always returns 0?

### ISSUE THREAD

**Issue by geoff-codes** [fish-shell/fish-shell#1909]
fish:
```sh
> function huh
     if [ 1 = 1 ]
      false
    end
  end
> huh
> echo $status

0
```
```sh
> function huh
     if [ 1 = 0 ]
      false
    end
  end
> huh
> echo $status

0
```

sh (for reference):
```sh
> huh()
  {
    if [ 1 = 1 ]; then
      false
    fi
  }
> huh
> echo $?

1
```

Is this the intended behavior? It certainly [has not always](https://github.com/fish-shell/fish-shell/commit/d7114332a987272dde63a8755696077c84b0dca0) been this way.

**Comment by zanchey** [comment]
Yes - see the discussion in #1443 - shall we track there?

**Comment by geoff-codes** [comment]
Yep.

**Comment by bucaran** [comment]
@geoff-codes I can't replicate this. It behaves normally here. What am I missing?

BTW you can write fish code using:
```fish
function fish
end
```

**Comment by geoff-codes** [comment]
@bucaran I'm not sure I follow you? The first two example I have up there are fish functions, in the form you just mentioned — the function is called `huh`, and within it there is a conditional. I was demonstrating  how the conditional disregards the exit status, unlike in a Bourne shell.

In any case, its probably best continue this #1443 as @zanchey mentioned — its the same issue.

**Comment by bucaran** [comment]
@geoff-codes Sorry, it's was an unrelated comment. I mean GH Markdown now supports fish syntax highlighting, so you can write tick tick tick fish and it will correctly fishlight you.

**Comment by geoff-codes** [comment]
> GH Markdown now supports fish syntax highlighting, so you can write tick tick tick fish and it will correctly fishlight you.

That's neat! I haven't had much time to play with it since the switch from pygments.rb to highlights — I wonder where their fish lexer comes from?

That's very odd that you can't replicate it — your version of fish is built from the latest HEAD? (Or at least, post 380f35b9?)

**Comment by bucaran** [comment]
Here is the [story](https://github.com/github/linguist/pull/1785).

Mmm, that could be it. I am using 2.1.1, which was released on September 26, 2014, so I should be ahead of 380f35b. 
:confused:

**Comment by geoff-codes** [comment]
> Here is the story.

That's badass! :+1::+1::+1:

I might actually take a an hour or two and see if I can't sync up the grammar with the new `fish_indent` a little better, when I get a chance. 

> As for my version of fish, I am using 2.1.1, which was released on September 26, 2014, so I should be ahead of 380f35b. :confused:

Nope:
https://github.com/fish-shell/fish-shell/commits/Integration_2.1.1/builtin.cpp

**Comment by bucaran** [comment]
> Nope:
https://github.com/fish-shell/fish-shell/commits/Integration_2.1.1/builtin.cpp

I see, so that's why.
