### ISSUE TITLE
seq in reverse does not work on Ubuntu

### ISSUE THREAD

**Issue by bucaran** [fish-shell/fish-shell#1914]
```fish
seq 5 1
```
Produces no output on Ubuntu Linux.

Perhaps the default `seq` installed on my container running Ubuntu does not support reverse sequencing? I am out of ideas.

**Comment by ridiculousfish** [comment]
seq on Linux is part of GNU coreutils, not part of fish. Our approach has been to try to work around platform idiosyncrasies in seq.

**Comment by zanchey** [comment]
GNU seq and BSD seq behave differently. fish provides a fallback seq function but the OS-supplied version is preferred.

FreeBSD [seq(1)](https://www.freebsd.org/cgi/man.cgi?query=seq):

> When _first_ is larger than _last_ the default _incr_ is -1.

GNU [seq invocation](https://www.gnu.org/software/coreutils/manual/html_node/seq-invocation.html):

> When _increment_ is not specified, it defaults to ‘1’, even when _first_ is larger than _last_. _first_ also defaults to ‘1’. So `seq 1` prints ‘1’, but `seq 0` and `seq 10 5` produce no output.

**Comment by bucaran** [comment]
@zanchey 

Thanks, that was the issue exactly.
 
In OS X, I didn't need to specify the step increment to `seq 5 1`, but it was required on Ubuntu, at least while running on Docker. I added that and now my local tests pass.
