### ISSUE TITLE
How to select text without mouse?

### ISSUE THREAD

**Issue by procedural** [fish-shell/fish-shell#1921]
My muscle memory tries to use Shift + Left / Right Arrow Keys, but not only it doesn't select anything, it insert these characters to current line `[1;2D[1;2C` when I press left and right arrow keys holding shift.

**Comment by ridiculousfish** [comment]
What operating system and terminal are you using?

**Comment by procedural** [comment]
Xubuntu 14.04, xfce4-terminal 0.6.3

**Comment by procedural** [comment]
Ok, sorry, I switched back to bash and it can't select text too. What a garbage terminal, I should've replace it with gnome-terminal from the beggining.

**Comment by procedural** [comment]
Related issue: http://askubuntu.com/questions/190008/terminal-insert-a-b-c-d-on-shiftarrows-solution
