### ISSUE TITLE
Prompt crashes shell in hg-git repo using hg prompt

### ISSUE THREAD

**Issue by danielmatz** [fish-shell/fish-shell#1923]
Hi,

I'm sorry to post such a vague problem, but I'm hoping that one of you has a brilliant idea and can help me fix what has become a really annoying issue.

My fish_prompt function (below) uses the [hg prompt](http://stevelosh.com/projects/hg-prompt/) command to provide a Mercurial repo status.  My prompt works just fine in a normal Mercurial repo, but when I use it in one created by [hg-git](http://hg-git.github.io), fish will only accept some of my keystrokes (maybe every other or so), and if I hit ctrl-C, it will kill the shell entirely rather than just clearing the line.

I have a similar prompt set up for bash, and it doesn't seem to experience these issues.

If I remove the hg prompt portion of my fish_prompt function, things work just fine.

I'm on Mac OS X Yosemite, and I use iTerm2.

I know that the problem could lie with hg prompt or hg-git, and I'm happy to go ask in those communities, but I thought I'd start here.

Thanks for your help!

Daniel

```
function fish_prompt
    # Leave a blank line after the last command
    echo ''

    # Set the basic prompt
    set_color red --bold
    printf (whoami)' '
    set_color normal
    set_color yellow
    printf (hostname)' '
    set_color magenta --bold
    printf (prompt_pwd)
    set_color normal

    # Set the Mercurial prompt
    set_color normal
    set -l hgprompt (hg prompt "{ "(set_color red --bold)"{incoming|count}↓"(set_color normal)"}{ "(set_color yellow)"{outgoing|count}↑}{ "(set_color green)"{bookmark}}{ "(set_color blue)"+{patch|applied|quiet}}{/{patch|count|quiet}}{ "(set_color magenta)"{status|modified}}" ^ /dev/null)
    set -l hgprompt (echo $hgprompt | sed "s/!/+changes/")
    printf $hgprompt'\n'

    # Put the command on the following line
    set_color normal
    printf '↪  '
end
```

**Comment by geoff-codes** [comment]
I'm gonna go ahead and say this could be a compelling reason to merge #1837.

@danielmatz If you're feeling adventurous, maybe you could try using the code in that PR rather than `hgprompt`, see if you have any issues?

**Comment by zanchey** [comment]
A trace of your session with `fish -p fishtrace` or similar might be helpful.

**Comment by danielmatz** [comment]
Sorry, it took me a while to reproduce this.  It doesn't happen consistently.  But I managed to do it while recording a trace, and I've posted it to a gist [here](https://gist.github.com/danielmatz/40af4fcfe35801c29a0b).

Basically, I cd into a directory that is within an hg repo (using hg-git, actually).  Then, I hit enter a few times, and then type and hit backspace rapidly.  It will start ignoring some keypresses, and then it will lock up entirely.  Then I hit Ctrl-C to try to clear the command line and the shell just quits.

I have no idea why this is related to being inside an hg repo.  The prompt has already displayed just fine.  Maybe hitting enter a few times confuses it somehow as it has to redraw the prompt rapidly?  Maybe hg completions are causing the issue?

**Comment by geoff-codes** [comment]
Shot in the dark here, but what happens if you strip out all the `set_color`s from `set -l hgprompt (hg prompt ...`?

`set_color` emits an escape sequence, and it looks like some of the regex in prompt.py might be catching on them.

**Comment by danielmatz** [comment]
I removed all `set_color` commands from `fish_prompt` and `fish_right_prompt`, and I was still able to reproduce my problem.

**Comment by zanchey** [comment]
I haven't been able to reproduce this yet. The other things to look at would be taking a sample of the process when it freezes (using Activity Monitor) and also whether there are any child processes (not sure how to do that, does Activity Monitor show you?)

**Comment by krader1961** [comment]
This has been in the "needs more info" state with no updates for over a year. I'm going to assume it's no longer an issue anyone cares about.
