### ISSUE TITLE
vi-mode extras

### ISSUE THREAD

**Issue by orbisvicis** [fish-shell/fish-shell#1928]
I'm shell-shopping and noticed fish now supports vi-mode. Thankfully there is a nightly ppa for ubuntu, after trying it out, xsel-support (yank!) is ingenious. That said, these are features of readline/vim vi-mode I use a lot missing from fish:

These probably need code support
- u -> undo
- r -> redo

visual mode
- u -> enter command mode
- $ -> goto EOL
- 0 -> goto SOL

normal-mode
- W -> (capital) forward word, whitespace-only delimiter
- B -> (capital) bakwards word, whitespace-only delimiter
- inclusive motions (e,E,ge,gE
- d<direction>, direction =
  - f <character> -> delete forward character
  - F <character> -> delete backwards character
  - $ -> delete to EOL ***
  - 0 -> delete to SOL
  - W
  - B
  - ...
- V -> (capital) select entire line

Also, perhaps mode should be reset (to user configurable mode) for each new prompt.

**\* There is something wrong with current implementation. Given `set fish_function_path $fish_function_path "{repository_root}/powerline/bindings/fish"`, position the cursor anywhere withing the quoted segment (ie, on the `r` after `{`), and try to delete to EOL (`d$`). Nothing is deleted, but the section from the start-of-quote to cursor is highlighted red.

Like I said, I'm new to fish. Some of these features should be added to the default keybindings, others to the application itself. If it's easy to explain, perhaps I could add them?

**Comment by zanchey** [comment]
The key bindings are in [share/functions/fish_vi_key_bindings.fish](https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_vi_key_bindings.fish) if you want to take a look.

**Comment by orbisvicis** [comment]
Wish I had time. I've created and linked to the respective sub-issues:

undo:
#1367 

reset mode:
#1933 

sentence move/kill support:
#1932 

move/kill word options:
#1931 

confusing vi-mode kill-line behaviour
#1930

**Comment by orbisvicis** [comment]
I see there are placeholders for `R_VI_ARG_DIGIT` and `ARG_VI_DELETE_TO`, so until those are implemented this is all I can offer:

```
# recommended, but not default
#bind \e 'commandline ""'

bind -m visual V beginning-of-line begin-selection end-of-line force-repaint

bind d0 backward-kill-line

bind -M visual -m default u end-selection force-repaint
bind -M visual \x24 end-of-line
bind -M visual \x5e beginning-of-line
bind -M visual 0 beginning-of-line
bind -M visual gg beginning-of-buffer
bind -M visual G end-of-buffer
```

**Comment by maun** [comment]
You might want to check out neovim. They are decoupling the gui from the rest, so that other editors like Atom can talk to a neovim server and have native vim commands. 
Maybe one could integrate this with fish so that you dont have to rewrite all vim commands.

**Comment by mashify** [comment]
Ohh by the way if someone got time please implement all the other awesome vim features too. For example registers, macros, etc.

**Comment by pickfire** [comment]
Is there any documentation about `fish_vi_mode` in *fish's documentation*? I hope there is a **Keep It Simple, Stupid** guide for `fish_vi_mode`.

**Comment by xrchz** [comment]
rather than re-implementing vim slowly (and inevitably poorly at first), using neovim as @maun suggested is definitely worth a look

**Comment by krader1961** [comment]
@xrchz: Even though I've only been contributing changes to this project for ~3 months I'm pretty confident that introducing a major dependency like neovim will never happen. But feel free to convince us that the benefits of doing so outweigh the negatives. Bonus points if you provide a code change that shows such integration is even possible (even if it is incomplete).

Having said that I'm all for anything that will improve fish's vi mode. The current implementation is not only missing a lot of useful features the ones that are implemented do not work anything at all like they do in a real Vi editor such as Vim.

**Comment by ridiculousfish** [comment]
We integrated PCRE, neovim might not be far behind :)

neovim has a socket interface. Perhaps we can use that, and make installing neovim a requirement for using vi mode.

**Comment by krader1961** [comment]
> We integrated PCRE, neovim might not be far behind :)

Yeah, but PCRE is not much different than depending on ncurses or libc for that matter. Neovim is a considerably larger beast. Do we really want to predicate running a fish interactive shell on launching a nvim process? What would something like that mean for people who want a statically linked fish binary? Or people who don't want to install neovim but still want vi bindings in fish?

**Comment by krader1961** [comment]
Also, the Neovim API appears to be primarily targeted towards decoupling plugins from the Vim binary. For example, making it possible to control neovim using python without having to link python into the neovim binary. That's a laudable goal. But it's pretty clear that refactoring fish to send events (i.e., key presses) to neovim and translate nvim _redraw_ events in response in vi mode, while at the same time keeping the existing emacs like code working, will be a non-trivial undertaking. As in, I don't think I'll live long enough to see someone invest the effort to make it work. Especially on both UNIX and MS Windows.

It will be a lot easier to make the existing vi mode actually usable within the constraints of the current key binding mechanism.

**Comment by ridiculousfish** [comment]
I don't know what would be involved with embedding neovim, but I do know they are targeting things like readline, so it seems reasonable on its face. At least it's a worthy experiment if anyone wants to take it on.

What's appealing about it is that vi support is asymptotic. fish will never be as vi as vi, and so will always find some way to frustrate vi users' expectations. There's a vi uncanny valley!

**Comment by krader1961** [comment]
> fish will never be as vi as vi

Sure, but the same is true for its emacs bindings. The main problem with fish's vi mode is not that it doesn't support number prefixes (e.g., `3dw`), named buffers, or any number of other advanced features. Things we would ostensibly get via neovim integration. The main problem is that basic features behave differently than a real Vi editor. Things like pressing `w` in command (normal) mode not moving to the start of the next word -- it moves to the next whitespace character.

Those seemingly minor differences in behavior might seem inconsequential to anyone not using vi mode but are quit jarring for those of us who do.

**Comment by krader1961** [comment]
> [neovim] are targeting things like readline

I googled "neovim readline replacement". The top three hits included these two Neovim GitHub issues:

[Embedding nvim in shell/REPL applications?](https://github.com/neovim/neovim/issues/1777)
[Proposal : Have neovim take over line editor functionality](https://github.com/neovim/neovim/issues/2787)

The Neovim project is at least a year away, more likely three, before a project like Fish will use it in that manner. I don't see this integration happening in my working lifetime (I'm 55). I'd prefer we focus our efforts on improving the existing fish vi-mode bindings within the framework of the fish key binding mechanism.

**Comment by xrchz** [comment]
> Those seemingly minor differences in behavior might seem inconsequential to anyone not using vi mode but are quit jarring for those of us who do.

:+1: These weirdo differences in fish's vi-mode compared to (n)vi(m) make it almost unusable as a line editor (or at least, no better than hunting and pecking in emacs- or default-mode).

Is there a simple way to supply fixes to such issues? I was hoping to avoid that by instead integrating with neovim, but if that's too hard, then fixing the existing vi-mode is better than nothing.

**Comment by ridiculousfish** [comment]
@xrchz a lot of things can be done just by modifying key bindings, but some (like the number prefixes) will require changes to the shell sources. You can look at the existing key bindings in `share/functions/fish_vi_key_bindings.fish` to get a feel for how they work. If you have a particular itch  you need to scratch you can also just ask about it, here or in the gitter.im

**Comment by krader1961** [comment]
@xrchz asks

> Is there a simple way to supply fixes to such issues?

Yes, but you'll need to learn the basics of using git in order to create a local repository of the fish code in order to make changes. That's the hard part. The easy part is learning how fish key bindings work then editing the file *share/functions/fish_vi_key_bindings.fish* to improve the current behavior. Heck, if you don't want to learn how to use git and github you could probably just post your changes to this issue and I or someone else will create a change in git on your behalf.

**Comment by xrchz** [comment]
@krader1961 Thanks :) I'm very familiar with git and GitHub already so that should be no problem. The annoying part will be working with a non-packaged version of fish. I'll hopefully get to it some time soon.

**Comment by krader1961** [comment]
There has been a lot of work in the past year to improve fish vi mode. Since @orbisvicis opened several, more focused, issues for the individual improvements most important to them I'm going to close this. Integrating with Neovim is something we can revisit in a few years when that project has reached the point where readline and other tools are using it.
