### ISSUE TITLE
Universal variables do not fire events

### ISSUE THREAD

**Issue by ZyX-I** [fish-shell/fish-shell#1929]
Consider the following script:

```Fish
# ~/.config/fish/config.fish
set -g efkb_reply
function --on-variable fish_key_bindings efkb
    set -g efkb_reply $efkb_reply "efkb:$fish_key_bindings"
end
efkb
```

Run with

```Shell
rm ~/.config/fish/fishd.$(hostname)*
fish
```

```Fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
zyx@zyx-desktop ~/t/i/fish-shell> echo $efkb_reply
efkb:
zyx@zyx-desktop ~/t/i/fish-shell> efkb
zyx@zyx-desktop ~/t/i/fish-shell> echo $efkb_reply
efkb: efkb:fish_default_key_bindings
zyx@zyx-desktop ~/t/i/fish-shell>
```

. As you see the value of `$fish_key_bindings` changed, but function `efkb` was not run.

I am on the latest master (793784c08778e8b3fb9d8a2a5621bd968db1dfbe), fish compiled just with `--prefix=$HOME/.local-fish`.

**Comment by zanchey** [comment]
I think this is because the function gets defined after the key bindings are set, so there's nothing change to signal.

**Comment by zanchey** [comment]
Hang on, I missed the function call at the end of config.fish.

**Comment by zanchey** [comment]
OK, this is a regression from 2.1.1. The variable change event doesn't get fired for universal variables.

```fish
function foo --on-variable bar
   echo bar changed
end
set -U bar
```

On 2.1.1 prints "bar changed".
On master as of df6f1e8 prints nothing.

**Comment by ridiculousfish** [comment]
Yikes

**Comment by ridiculousfish** [comment]
At the bottom of `env_set`, we post the notification unless the variable is universal. In old fish, what would then happen is that we would tell fishd of the changes, and fishd would turn around and tell us again, and we would then post the notification in the universal callback.

We no longer bother to tell ourselves of changes we make, so now we should just post the notification in env_set like all other scope types do.
