### ISSUE TITLE
kill-line autosuggestions

### ISSUE THREAD

**Issue by orbisvicis** [fish-shell/fish-shell#1930]
R_KILL_WORD/move_word supresses autosuggestions. Should R_*KILL_LINE/reader_kill do the same?

**Comment by orbisvicis** [comment]
With vi-mode kill line autosuggestions are confusing: `a` (for insert/append) undoes the kill, ie

```
--cursor-here----|
echo asdf asdf "{asdf}/qwer"
```

**Comment by ridiculousfish** [comment]
Finally got a chance to look at this. I'm not much of a vi guy - can you list the commands like R_KILL_LINE that ought to do this? Or of course I'll merge a PR if you prefer that way.

**Comment by krobelus** [comment]
> With vi-mode kill line autosuggestions are confusing: a (for insert/append) undoes the kill, ie
> d$, a

this is fixed because `a` is now bound to forward-single-char.
So there should be nothing to do here
