### ISSUE TITLE
vi-mode: execute enters insert-mode by default

### ISSUE THREAD

**Issue by orbisvicis** [fish-shell/fish-shell#1933]
This is what `zsh` and `bash`/`readline` do by default. Currently, new vi-mode fish prompts inherit the previous mode. I find this behaviour confusing, either because it's inherently worse, or I'm not used to it. Anyway I propose changed the vi-mode keybinding:

`bind \n execute` -> `bind -m insert \n execute`

**Comment by ridiculousfish** [comment]
Makes sense to me. Fixed as 97aa1c033bcdd839ee3fe28431c786dde2354d13
