### ISSUE TITLE
Incorrect Colors

### ISSUE THREAD

**Issue by orbisvicis** [fish-shell/fish-shell#1934]
I'm trying to port zenburn to fish, but colors aren't displaying correctly:

I've put the actual color in colorutils.js

* Actual: #93e0e3 (147,224,227)
* firefox: #0093E3 (0,147,227)
* terminal: #87D7D7 (135,215,215)

This isn't a web color problem: javascript explicitly converts #93e0e3 to #0093E3. The correct color is saved in `~/.config/fish/fishd*`. Then `fish` causes urxvt to display the incorrect color. This isn't a terminal-color problem: urxvt can display 24-bit color, ie `echo -ne "\033]11;#93e0e3\007"` (verified with *gcolor*). In any case #93e0e3 is also mapped to color14 (of the 256-color palette), so this shouldn't be a nearest-color issue as well.

**Comment by ridiculousfish** [comment]
fish support for 24 bit color is only present in ToT and is disabled by default. Set the environment variable `fish_term24bit=1` to enable it.

**Comment by orbisvicis** [comment]
I was wrong regarding urxvt. The only color operations supported are:

* CSI P m m
  * set foreground/background color to any of the first 16 user-configurable colors ([black, red, green, yellow, blue, magenta, cyan, white], bright & dark variations):

    `printf "\x1b[96;43mASDF\x1b[0m\n"`

 * set foreground/background color to index into the 256-color palette:

    `printf "\x1b[38;5;26;48;5;2mASDF\x1b[0m\n"`

  * *(xterm only. not supported by urxvt)* given truecolor RGB tuple, set foreground/background color to nearest entry in 256-color palette:

    `printf "\x1b[38;2;147;224;227m███\x1b[0m\n"`

    **This converts `#93E0E3` to `#87D7D7` only when `#93E0E3` is not part of the palette*

* OSC P s ; P t BEL
  * set dynamic foreground/background colors (separate from 256-color palette) to any truecolor hex string:

    `printf "\x1b]11;#53186f\x07"`

    There is an escape sequence to read the current foreground/background colors so that the original colors can be later restored.

    **I vaguely recall reading that setting dynamic colors is considered bad practice. Something about a color-changing child process' changes being unset.*

[1] http://invisible-island.net/xterm/ctlseqs/ctlseqs.html

Anyway fish itself converts RGB tuples to palette indexes when `fish_term24bit` is disabled. Because it ignores the first 16 colors, it converts `#93E0E3` to `#87D7D7`. I have some suggestions for reading them, but they may be unreasonable:

1. Query terminal for current color palette values (via terminfo):

    `printf '\x1b]4;14;?\x07'`

2. Load current color palette values from xrdb (via xcb, I hope?).
3. Use dynamic foreground/background escape sequences (OSC) via terminfo to write output. Need to determine if setting dynamic colors should be avoided. IMO it shouldn't matter because shell and program output are never mixed. This makes querying moot if the terminal supports this output method.

That way `#93E0E3` has the opportunity to remain `#93E0E3`.

**Comment by orbisvicis** [comment]
But the javascript color mangling is still a problem.

**Comment by krader1961** [comment]
@orbisvicis This is going to require some careful design work and implementation. OSC sequences are not universally recognized. A little over a year ago I worked with the iTerm2 maintainer to add support for a couple of relevant OSC sequences (see http://code.google.com/p/iterm2/issues/detail?id=3007). AFAIK iTerm2 still doesn't report the actual RGB values for each palette index.

Also, AFAICT, these capabilities are not found in terminfo. That is, where in a terminfo definition would we learn that a terminal supports these abilities? If not can a heuristic be devised that will reliably auto-detect what is supported without the risk of putting a terminal into an unexpected state?

Is this still something you care about or did you find ways to achieve your desired results?

**Comment by pickfire** [comment]
@orbisvicis In some recent commit, `fish_term24bit` will be set if your terminal support true colors. Make sure that your terminal support true color by checking https://gist.github.com/XVilka/8346728

**Comment by krader1961** [comment]
The recent commit referred to by @pickfire is faho@b73bf53b two months ago to augment the ___fish_config_interactive.fish_ script. That might help to improve your situation if urxvt matches one of those conditions.

**Comment by faho** [comment]
>Also, AFAICT, these capabilities are not found in terminfo.

IIRC, the terminfo maintainer was against adding them.

My "solution" was to detect terminals that are known to support 24-bit colors via some environment variable. I'm not sure it can be done better unless it's integrated into terminfo (which then binds all the detection to $TERM, which we can't use in general because plenty of things by default claim to be xterm).

>That might help to improve your situation if urxvt matches one of those conditions.

It doesn't.

**Comment by faho** [comment]
Since 2.3.0, we now enable 24-bit colors when we think we can get away with it. Beyond that, there's nothing more for us to do.
