### ISSUE TITLE
Add feature to echo to not modify `$status`

### ISSUE THREAD

**Issue by bucaran** [fish-shell/fish-shell#1941]
Sometimes I echo a message after checking `$status` and return from a function, but that last `echo` modifies `$status` so it's inconvenient. An alternative is to have my function return whatever error status was generated and let the consumer, main utility / function to handle diagnostic messages.

How outrageous would it be to add an option to `echo` such as `-S` so that `$status` was saved before echo does its thing, and then returns the previous `$status`.

**Comment by ridiculousfish** [comment]
echo in fish has one extra option `-s` and it tears me up inside. It also supports `--help`, which is probably a mistake too. People use `echo` expecting it to just print whatever is passed to it; every option it supports is a surprise. One of these days I'll get around to making it support literal options only.

I think you could do what you want with a function:

    function safe_echo ; set -l ret $status ; echo $argv ; return $ret; end

Does that work?

**Comment by bucaran** [comment]
> `-s` Do not separate arguments with spaces. 

Why does it tear you up? I am very compelled to look at the source now! :grinning: 

`safe_echo` may seem like just a minor inconvenience, and I if I really needed a use for it I should just go ahead and use `safe_echo`, but I usually prefer the default functionality that is provided instead of working around stuff.

**Comment by ridiculousfish** [comment]
The scary stuff is code like this:

    echo $something

This outputs $something UNLESS it starts with one of the arguments that `echo` recognizes. Handling this correctly as a client is nigh impossible, so people just do it and hope they get lucky (i.e. that $something doesn't start with -n or whatever). Every new option that `echo` supports is another edge case and failure waiting to happen.

**Comment by bucaran** [comment]
Yes, that's why I mostly only use `echo "$something"`, and only when I am _sure_ of my data. Otherwise I use `printf "%s" ...` which is more verbose, hence my fond for echo sometimes.

**Comment by krader1961** [comment]
As discussed in issue #1013 the fact that `echo` currently does not interpret `--` to mean stop interpreting options is FUBAR; POSIX notwithstanding. Ignore that for a moment. What other commands should not modify `$status`? What about `printf`? What about some other arbitrary functions that simply wrap echo or printf? Sorry, but this sort of "spooky magic at a distance" is a bad idea. If you want to return the exit status of a specific command then explicitly save its status and `return $saved_status`.

**Comment by bucaran** [comment]
@krader1961 Totally disregard this issue, I didn't know what I was talking about at the time :sweat_smile:
