### ISSUE TITLE
Cannot use export

### ISSUE THREAD

**Issue by sakebomb** [fish-shell/fish-shell#1943]
I just noticed this. I am not sure if I have something misconfigured but here is the info.

user@computer ~> export PATH=$PATH:/usr/local/opt/go/libexec/bin
fish: Unknown command 'export'

**Comment by siteshwar** [comment]
In fish we do not modify $PATH directly, instead modify $fish_user_paths like this :

```
set -U fish_user_paths <paths separated by spaces>
```

Paths in $fish_user_paths automatically get prepended in $PATH.

If you are new to fish I would suggest you to go through http://fishshell.com/docs/current/tutorial.html

Thanks for reporting this issue.
