### ISSUE TITLE
pushd, pushd +2 behavior

### ISSUE THREAD

**Issue by newhook** [fish-shell/fish-shell#1944]
Unlike bash, zsh and other shells an argumentless pushd adds my home directory to the stack. Thats really irritating for people like me who have been using bash-like shells for 20+ years. Any chance this could be fixed to work like bash?

**Comment by ridiculousfish** [comment]
I'm not a pushd user so I don't know what behavior you expect, but I'll be happy to merge a pull request. The functions are in `share/functions/pushd.fish` and `share/functions/popd.fish`

**Comment by zanchey** [comment]
OK, so the desired behaviour is something like

(bash)
```bash
[~] $ popd
bash: popd: directory stack empty
[~] $ cd /etc
[/etc] $ pushd /var
/var /etc
[/var] $ pushd
/etc /var
[/etc] $
```

whereas fish currently does this:
```fish
[~] > popd
popd: Directory stack is empty...
[~] > cd /etc
[/etc] > pushd /var
[/var] > dirs
/var  /etc
[/var] > pushd
[~] > dirs
/home/zanchey  /var  /etc
[~] >
```

**Comment by 3gg** [comment]
I have a script which does more or less the right thing. It doesn't handle pushd -2 yet (although I never use that myself). I'll issue a pull request at some point soon.

**Comment by newhook** [comment]
I have a script which does more or less the right thing. It doesn't handle pushd -2 yet (although I never use that myself). I'll issue a pull request at some point soon.

**Comment by eush77** [comment]
Is there any progress on this issue?

**Comment by zanchey** [comment]
This got added in #2173, although nobody has written the documentation yet.
