### ISSUE TITLE
Support completion for "apt" like for "apt-get"

### ISSUE THREAD

**Issue by najamelan** [fish-shell/fish-shell#1945]
Recent versions of apt ship with a new command that is more concise and more intuitive to use. It's simply "apt" which works as a front-end to more lowlevel commands like apt-get and apt-cache.

I can't find it's [manpage here](http://www.tin.org/bin/man.cgi?section=8&topic=apt).

Apart from a neater and more convenient syntax, this also enables a few nicer options like output coloring as you can see from the "differences with apt-get" section of the man page. It's specifically meant for use from an interactive shell.

One of the nicer features of fish are it's many completions, and I think this one shouldn't be missing.

I had a look at the completion code for apt-get, but as it was a little bit more complex than I expected and as I don't understand the rationale behind it, I haven't tried to create a pull request, but I suppose this is a trivial addition for someone who has some experience with fish completions.

Thanks in advance for whoever implements it.

**Comment by zanchey** [comment]
This got merged for 2.2.0 in #2018!
