### ISSUE TITLE
Error in using pkg-config with gcc in fish

### ISSUE THREAD

**Issue by bigpotato920** [fish-shell/fish-shell#1947]
I use fish shell on Arch Linux. I was trying to compile a c program using gtk library.But When I try to compile it using the following command in fish:

    sudo gcc -shared -o libsublime_imfix.so sublime_imfix.c (pkg-config --libs --cflags gtk+-2.0) -fPIC

it shows the following errors:
gcc: error: unrecognized command line option ‘-pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype ’
    but when I switch to bash and run : 

    sudo gcc -shared -o libsublime_imfix.so sublime_imfix.c `pkg-config --libs --cflags gtk+-2.0 `-fPIC

   it works fine, could you help me with that?

**Comment by zanchey** [comment]
See #982 - you need to add `| tr ' ' '\n'` or similar to the end of the pkg-config command substitution.

**Comment by bigpotato920** [comment]
When I use a normal user I try:

    sudo eval gcc -shared -o libsublime_imfix.so sublime_imfix.c (pkg-config --libs --cflags gtk+-2.0) -fPIC

The output is ： sudo: eval: command not found
But When I switch to root it works fine.

**Comment by zanchey** [comment]
If you want to do it that way, use `eval sudo`, not `sudo eval`.

**Comment by ridiculousfish** [comment]
What's mystifying to me is why the `sudo eval ...` works. Did you perhaps not run the command with sudo as root?

**Comment by bigpotato920** [comment]
yeah , the source code is located at /opt/xxx, so I have to have root priveledge

**Comment by ridiculousfish** [comment]
I think there's nothing for fish to do here. The issues with pkg-config are well known. Please comment if you think there's more to do.
