### ISSUE TITLE
support for !

### ISSUE THREAD

**Issue by newhook** [fish-shell/fish-shell#1948]
Has anyone considerered this? For those that have never used this feature from bash:

$ !find

Runs the last command which started with find.

$ !!

Runs the last command again.

**Comment by ridiculousfish** [comment]
Ah yes, bash's lovely ! substitution:

    > echo "Hello, world!!"
    echo "Hello, worldecho "Hello, world!""
    Hello, worldecho Hello, world!

Anyways see #288 for extensive discussion, where your thoughts are welcome. Closing as dup of #288
