### ISSUE TITLE
OSX Build reports 2.0.GIT as version

### ISSUE THREAD

**Issue by oschrenk** [fish-shell/fish-shell#1953]
```
brew install fish
fish --version
fish, version 2.0.GIT
```
Expected
```
fish, version 2.1.2
```

**Comment by zanchey** [comment]
When 2.1.2 is released as a tarball then this will be fixed. (The problem stems from Homebrew installing from a github-generated tarball which is missing the right files for generating the version number.)

**Comment by RSully** [comment]
Gah maybe part of the tests for the Homebrew formula should be checking `fish --version` against the version # so that things like this don't happen (and therefore Homebrew is forced to wait for official release).

**Comment by DomT4** [comment]
This was a regrettable, but fairly rare screw up based off of a multi-party misunderstanding in the disk error thread referenced. It'll be fixed once there's an official tarball available, and it's something that'll be looked out for in future.
