### ISSUE TITLE
Feature: Rewind function like bpython-urwid

### ISSUE THREAD

**Issue by benjaminweb** [fish-shell/fish-shell#1961]
Scenario:

```
command 1
command 2
command 3
```

So, I do some changes and want to re-execute command 1, command 2, command 3.
Currently I hit upward arrow:
three times to get command 1, three times to get command 2, and another three times to get command 3.

I just want to put the 'shell' back in time to command 1.
Then I want to move it forward, step by step, over command 2 and command 3.
Currently the shell scrolls through history. What about scrolling the history through the shell?

Borrow from [bpython-urwid](http://bpython-interpreter.org): `"Rewind" function to pop the last line of code from memory and re-evaluate.`

**Comment by zanchey** [comment]
Fwoar. I'm not sure I understand the proposed UI here - pushing a key erases the output of the last command and puts the terminal and shell back in a state as if the last command had never been executed? I don't know how that's easier to reexecute command 1/2/3 - would there be a corresponding "forward" key?

**Comment by benjaminweb** [comment]
Does this hold true if it happens in a distinct copy of the command history?
You can enter and leave it with a keyboard shortcut.
Original history is untouched.

**Comment by zanchey** [comment]
I might be missing the point - do you actually want the rewind functionality? Or just a different method of browsing the history?

**Comment by benjaminweb** [comment]
You are right. This are two beasts.
Browsing the history differently is what I have on my mind.

**Comment by ridiculousfish** [comment]
I find myself needing to do this stuff too, e.g. execute the last N commands in their original order. Maybe if you execute a command from history, down arrow gives you next command. So you press Up to get to Command 1, return to run it, Down to get to Command 2, return to run it, Down to get to command 3, return to run it.

**Comment by krader1961** [comment]
Recent enhancements to the `history` and `source` commands make this almost trivial to do; e.g., `history search -5 | source`. And if you want, say, the three most recent git commands: `history search -3 -p git | source`. Closing since I don't think there is anything else to be done.
