### ISSUE TITLE
git completions should support aliases for `git` command.

### ISSUE THREAD

**Issue by bucaran** [fish-shell/fish-shell#1962]
There is already completion support for git aliases like `<command> = <alias>` inside your `gitconfig`, but we are out of luck if we want to use an alias for the `git` command itself, like 

```fish
function g; git $argv; end
```

While we are at it, how difficult would be to add completion support for any command aliases?

**Comment by zanchey** [comment]
I think you can use `function g --wraps git; git $argv; end` in this instance.

**Comment by ridiculousfish** [comment]
zanchey's right; closing. Thanks zanchey.

**Comment by bucaran** [comment]
:+1:
