### ISSUE TITLE
commandline interprets option as it's own argument

### ISSUE THREAD

**Issue by tannhuber** [fish-shell/fish-shell#1964]
There's a function in oh-my-fish's budspencer theme:
```
function __budspencer_edit_commandline -d 'Open current commandline with your editor'
  set budspencer_tmpfile /tmp/tmpfile
  commandline > $budspencer_tmpfile
  eval vim $budspencer_tmpfile
  commandline (cat $budspencer_tmpfile)
end
```
which is called by a shortcut to edit the command line with vim. If the commandline has a `-` somewhere in the first column, the second `commandline` command interprets it as option of `commandline`.
Here's an example:
```
echo \
-n hello world
```
gives a warning:
```
echo commandline: Unknown Option '-n hello world'
~/.oh-my-fish/themes/budspencer/fish_prompt.fish (Line 506):     commandline (cat $budspencer_tmpfile)
                                                                  ^
in function '__budspencer_edit_commandline'
	called on standard input
```
However, the `-n` flag should belong to the `echo` command and not to `commandline`.  How can I modify the function in order to produce the desired behaviour?

**Comment by zanchey** [comment]
I think you're getting bitten by the split-on-newlines behaviour of command expansion.

Does inserting `set -l IFS ''` before the second `commandline` invocation help? If so, I'll commit that patch.

**Comment by tannhuber** [comment]
Indeed, it helps. Thank you very much. Can be closed.

**Comment by zanchey** [comment]
We're tracking this elsewhere, so I will close for now.
