### ISSUE TITLE
fish: No matches for wildcard - in script

### ISSUE THREAD

**Issue by ElijahLynn** [fish-shell/fish-shell#1965]
I normally run this on the command line and just surround the single argument with single or double quoutes and it works fine. When called inside the function though it doesn't get escaped. If I surround the $argv[1] with quotes in the function it produces the same result. Do I need to concatenate quotes around this or is there an easier way?

```
function ytd
    youtube-dl -t $argv[1] 
end
```

ytd https://www.youtube.com/watch?v=M4spK4QeUKY
fish: No matches for wildcard 'https://www.youtube.com/watch?v=M4spK4QeUKY'.
ytd https://www.youtube.com/watch?v=M4spK4QeUKY

**Comment by bucaran** [comment]
`ytd "https://www.youtube.com/watch?v=M4spK4QeUKY"`
Works for me.

**Comment by ElijahLynn** [comment]
Oh, I have to pass the argument with quotes, I see.

That will work but I was hoping to be able to pass the argument without quotes. Is this possible?

**Comment by ElijahLynn** [comment]
I also searched the help docs for 'concatenation' and didn't see how to concatenate in Fish.

**Comment by ElijahLynn** [comment]
I guess I can close this but if anyone comes across this and has an answer please post!

**Comment by ridiculousfish** [comment]
The question mark in the URL is a wildcard. There's no way to avoid wildcard expansion without quoting the argument.

Note that you're just getting lucky with bash - if there were a local file that happened to match the glob, it would do something unexpected. See #967. This can be considered a duplicate of that.

**Comment by ElijahLynn** [comment]
Ahh, thanks very much, it didn't occur to me that ? was a wildcard for exactly one character!!

For anyone who wants to learn more, http://www.linfo.org/wildcard.html, search for 'Question Mark Wildcard'.
