### ISSUE TITLE
make fails on master - Ubuntu 14.04

### ISSUE THREAD

**Issue by ElijahLynn** [fish-shell/fish-shell#1966]
I did `sudo apt-get install build-essential ncurses-dev libncurses5-dev gettext` as recommended in the readme. I think it is the same issue as #969 but figured I would make a new issue because my OS is different.

![workspace 1_234](https://cloud.githubusercontent.com/assets/1504756/6448823/833ab6ae-c0ea-11e4-8c97-2a1a9ca094a9.png)

**Comment by ElijahLynn** [comment]
Although, I just found the nightly build wiki and was able to get that going nicely. Now I have Alias Completion (#393)!!

**Comment by zanchey** [comment]
Do you have `libtinfo-dev` installed? `libncurses5-dev` should have pulled it in.

**Comment by ElijahLynn** [comment]
It appears so. 

![selection_243](https://cloud.githubusercontent.com/assets/1504756/6526020/f3062b9c-c3da-11e4-9d23-6867e26552c7.png)

**Comment by zanchey** [comment]
That's what has the symbols, and the nightlies build with that package without any problems, so my suspicion is that a clean checkout (or at least `make distclean; autoconf; ./configure`) will solve the problem.

**Comment by ridiculousfish** [comment]
Nitpick: this isn't a symbol problem, it's a header problem. But the analysis is right - I suspect that you installed libncurses5-dev after running ./configure, and rerunning ./configure will fix it.

There's been no action for a few weeks so I'm going to close. @ElijahLynn if that doesn't fix it for you please comment and I'll reopen. Thanks for reporting this!
