### ISSUE TITLE
Nightly build versioning number system?

### ISSUE THREAD

**Issue by ElijahLynn** [fish-shell/fish-shell#1967]
Is there some documentation on why the nightly builds start with 2.1.1?

I just grabbed a nightly build for Ubuntu and the version is 2.1.1-1209-gb4aa2b7 which confused me at first. The cool thing is that it does appear to be latest master because I have alias completion now + abbreviations working!!

At any rate, I am wondering if I could get some more info on that and if possible edit the wiki to explain that @ https://github.com/fish-shell/fish-shell/wiki/Nightly-builds

**Comment by xfix** [comment]
This means 1209th commit after 2.1.1 (b4aa2b7). This is the syntax git uses, and is unlikely to be changed.

**Comment by ElijahLynn** [comment]
Thanks!

**Comment by zanchey** [comment]
Importantly, it allows package management systems to upgrade nightly packages in a sensible way.

**Comment by ElijahLynn** [comment]
Thanks @zanchey.

**Comment by ElijahLynn** [comment]
One follow up question, the latest stable is 2.1.2, why is it going after 2.1.1 instead?

**Comment by xfix** [comment]
@ElijahLynn: This is because 2.2.0 is based on 2.1.1, and there is no code from 2.1.2 in current master.

(although, I believe that this version could be renamed to 2.1.2, not that it matters, because 2.2.0 is going to be released soon)

**Comment by ElijahLynn** [comment]
Thanks Xfix? Btw, how soon is 2.2.0 going to be released?

**Comment by zanchey** [comment]
2.2.0 was actually based more closely on 2.1.0 - but I merged the tag back in from Integration_2.1.1 to master. I'm not actually sure that it's the best thing to do, but we've been doing it for a while now so I'll do it for 2.1.2 shortly.

There is no schedule for 2.2.0 but hopefully it is not too far away.
