### ISSUE TITLE
Best practice for `cd (path)`

### ISSUE THREAD

**Issue by ElijahLynn** [fish-shell/fish-shell#1969]
I have a bunch of aliases that I am converting to abbreviations. While doing so I wondering if I may be fundamentally missing something. 

My use case and I am sure many others have this too is that I have like 10 common folders I cd into all the time. So I make an abbreviation called `web=cd ~/websites` and then `cdff=cd ~/.config/fish/functions` and so on. Is there a better way to go about this then making an abbr everytime I want to do this? 

Thanks!

**Comment by ElijahLynn** [comment]
I did play with this a while ago, https://github.com/joelthelion/autojump but didn't find it super intuitive.

**Comment by ElijahLynn** [comment]
I actually cannot get autojump to work right now under fish, I wonder if it is because autojump tries to use the cd command and something wonky is going on with the Fish cd command. 

it just fails with an exit status of 1.

**Comment by bucaran** [comment]
I don't see the good thing about `autojump`. Just type the path followed by a `/` and fish will `cd` you there. The best thing is you have _autocompletion_ so you can see everything at a glance.

**Comment by ElijahLynn** [comment]
Right but you need to type quite a bit with Fish to take you there, even if you skip `cd` and just and with a `/`. Yeah, so some kind of autojump like functionality (or better) in Fish would ideal.

**Comment by Leo2807** [comment]
What I do is: I create symlinks in my home directory so everytime I open a terminal I just have to type the name of the folder I want to go to.

**Comment by anordal** [comment]
Here is what I do, refined version:

Put this in ~/.config/fish/functions/jump.fish
```fish

# Based on "shell bookmarks" by J.Janssens:
# http://jeroenjanssens.com/2013/08/16/quickly-navigate-your-filesystem-from-the-command-line.html

function jump
	if set -q XDG_CONFIG_HOME
		set markpath $XDG_CONFIG_HOME/marks
	else
		set markpath $HOME/.config/marks
	end

	if test (count $argv) -eq 0
		set argv -l
	end
	switch $argv[1]
		case -
		case '-*'
			set have_option
	end

	if not set -q have_option
		set -l dst .
		for i in $argv
			switch $i
				case -
					if test $dst = .
						set dst $PWD
					end
					read -p "set_color $fish_color_cwd; printf 'cd '; set_color normal" -sc $dst i
					set dst .
				case '*/*'
				case '*'
					if not set i (readlink $markpath/$i)
						echo "No such mark: $i" >&2
						return 1
					end
			end
			switch $i
				case '//scm/*'
					set i (printf '%s' $i | tail -c+7)
					if not set i (git -C $dst rev-parse --show-cdup)$i
						echo "Not in a recognised scm repo" >&2
						return 1
					end
			end
			if test $dst = .
				set dst $i
			else
				set dst $dst/$i
			end
			if not set i (stat -c '%i' $dst)
				return 1
			end
		end
		cd $dst
		return $status
	end

	switch $argv[1]
		case -l --ls
			set -l oldcollate $LC_COLLATE
			set -x LC_COLLATE C
			for i in $markpath/*
				printf '%s/%s\0' (readlink $i) (basename $i)
			end | sort -zn | while read -zl i
				set -l dst (dirname $i)
				set -l color purple
				switch $dst
					case '//*'
						set color f70
					case '/*'
						set color -o blue
				end
				printf '%8s → %s%s%s\n' (basename $i) (set_color $color) $dst (set_color normal)
			end
			set -x LC_COLLATE $oldcollate
		case -r --rm
			if test (count $argv) -gt 1
				rm $markpath/$argv[2..-1]
			end
		case -m --mv
			if test (count $argv) -eq 3
				mv $markpath/$argv[2..-1]
			end
		case -s --set
			mkdir -p $markpath
			or return 1
			if test (count $argv) -le 2
				ln -s $PWD $markpath/$argv[2]
			else
				ln -s $argv[3] $markpath/$argv[2]
			end
		case -c --set{scm,vcs}
			if test (count $argv) -ne 2; or not mkdir -p $markpath
				return 1
			end
			# TODO: Detect & support other things than git, if needed
			ln -s //scm/(git rev-parse --show-prefix) $markpath/$argv[2]
		case --tutorial
			_jump_tutorial
		case '*'
			echo 'jump - change directory using any combination of'
			echo '* absolute bookmarks'
			echo '* relative bookmarks'
			echo '* typed bookmarks, which are absolute within a certain type'
			echo '  of directory (currently an "scm" type that supports git)'
			echo '* regular paths'
			echo '* editing your current location'
			echo ''
			echo 'Usage:'
			echo 'jump                     List bookmarks'
			echo 'jump JUMPARGS            Jump to a path constructed from JUMPARGS'
			echo 'jump -h|--help           Print usage'
			echo 'jump -r|--rm NAMES       Delete bookmarks named NAMES'
			echo 'jump -m|--mv OLD NEW     Rename bookmark from OLD to NEW'
			echo 'jump -s|--set NAME       Bookmark the absolute path to the current directory'
			echo 'jump -s|--set NAME PATH  Bookmark PATH (use to create a relative bookmark)'
			echo 'jump -c|--setscm NAME    Bookmark the current directory within an scm repo'
			echo 'jump    --setvcs NAME    Alias for --setscm'
			echo ''
			echo 'Explanation of JUMPARGS:'
			echo 'Jump changes directory to the path formed by concatenating each argument'
			echo 'after expanding it according to its category:'
			echo '* the single "-" (dash) character means "edit";'
			echo '* anything containing a "/" (slash) character is a path;'
			echo '* anything else is a bookmark.'
			echo ''
			echo 'For examples, see `jump --tutorial`.'
	end
end

function _jump_tutorial
printf "\
Tutorial

Level 1: An absolute bookmark

~> mkdir -p /tmp/{blue,straw}berry
~> /tmp/strawberry
/tmp/strawberry> # Let's bookmark this location
/tmp/strawberry> jump --set straw
/tmp/strawberry> # See how the bookmark list looks like now
/tmp/strawberry> jump
   straw → /tmp/strawberry
/tmp/strawberry> # Congratulations, you have a bookmark
/tmp/strawberry> # Let's test it
/tmp/strawberry> cd
~> jump straw
/tmp/strawberry>

Level 2: Edit your location

/tmp/strawberry> jump -
# Now, replace "straw" with "blue"
/tmp/blueberry>

Level 3: Combine arguments

/tmp/blueberry> cd
~> # How to get to blueberry from somewhere else? Hint: We have a bookmark
~> # that is almost what we need, and we know how to edit; combine these
~> jump straw -
# Et voilà, now it is only for you to replace "straw" with "blue"
/tmp/blueberry>
/tmp/blueberry> cd
~> # Another way, using a path instead of editing
~> jump straw ../blueberry
/tmp/blueberry>
/tmp/blueberry> # Having reached the destination, let's bookmark it
/tmp/blueberry> jump --set blue

Level 4: Relative bookmarks

/tmp/blueberry> ..
/tmp> # Suppose we have some very similar directory trees
/tmp> mkdir -p {blue,straw}berry/{'ice cream',muffin}
/tmp>
/tmp> # ...and we want bookmarks to subdirectories of both trees. With
/tmp> # absolute bookmarks, we would need to duplicate these for each tree
/tmp> # - relative bookmarks to the rescue.
/tmp> jump --set ice 'ice cream'
/tmp> jump --set muf muffin
/tmp> jump
     ice → ice cream
     muf → muffin
    blue → /tmp/blueberry
   straw → /tmp/strawberry
~> jump blue ice
/tmp/blueberry/ice cream>
/tmp/blueberry/ice cream> jump blue muf
/tmp/blueberry/muffin>
/tmp/blueberry/muffin> jump straw muf
/tmp/strawberry/muffin>
/tmp/strawberry/muffin> jump straw ice
/tmp/strawberry/ice cream>

Level 5: Scm bookmarks

/tmp/strawberry/ice cream> # The problem with relative bookmarks is...
/tmp/strawberry/ice cream> jump muf
'muffin': No such file or directory
/tmp/strawberry/ice cream> # ...they are relative.
/tmp/strawberry/ice cream>
/tmp/strawberry/ice cream> # But suppose
/tmp/strawberry/ice cream> jump straw
/tmp/strawberry> git init
/tmp/strawberry> jump blue
/tmp/blueberry> git init
/tmp/blueberry>
/tmp/blueberry> # ...we make scm bookmarks instead of relative ones
/tmp/blueberry>
/tmp/blueberry> # yeah, and this extremely handy one too
/tmp/blueberry> jump --setscm up
/tmp/blueberry>
/tmp/blueberry> jump ice
/tmp/blueberry/ice cream> jump --rm ice
/tmp/blueberry/ice cream> jump --setscm ice
/tmp/blueberry/ice cream>
/tmp/blueberry/ice cream> jump up muf
/tmp/blueberry/muffin> jump --rm muf
/tmp/blueberry/muffin> jump --setscm muf
/tmp/blueberry/muffin>
/tmp/blueberry/muffin> # They behave as absolute within the repository...
/tmp/blueberry/muffin> jump ice
/tmp/blueberry/ice cream> jump muf
/tmp/blueberry/muffin> jump up
/tmp/blueberry>
/tmp/blueberry> # ...but apply just as well to another repository
/tmp/blueberry> jump straw muf
/tmp/strawberry/muffin> jump ice
/tmp/strawberry/ice cream> jump up
/tmp/strawberry>
"
end
```

**Comment by krader1961** [comment]
I've mostly relied on `$CDPATH`. For example, my `$CDPATH` currently has two elements that allows me to type things like `cd fish[tab]` to change to my local fish-shell git repo directory that is under a directory where I anchor all of my third-party git repos.

When I recently proposed a `mcd` (menu change directory) command (see issue #2847) I realized I could prime the history by explicitly setting `$dirprev` in my *~/.config/fish/config.fish*. This issue made me ponder if adding support for a user defined list of directories that augment the `cd` history would be useful. Would you be satisfied if you could define a list of up to 26 directories that you could select by typing `mcd` then an uppercase letter to choose one of those directories?

**Comment by ElijahLynn** [comment]
So, after playing with the filename autocomplete support that is offered by fish's git support I really like the ability to just type `git add <filename>` then `tab` and it autocompletes the whole path. 

I have been using `z` in the meantime and really like the ability to not have to pre-define anything. Just `z <string>` and `tab` and pow, most of the time I am in the directory I was expecting. 

I personally see this as something fish should provide by default but maybe it should stay in the contrib space?

**Comment by krader1961** [comment]
@ElijahLynn: Have you looked whether the **$CDPATH** variable would address some, if not most, of your needs? You simply set it to an array of directories whose subdirs you wan't to be able to `cd` to easily. It supports the path completion you mentioned in your `git add [tab]` example. For example,

```
set -g CDPATH . ~ ~/.config/fish /usr/share/fish
```

It's one shortcoming is that the first subdir of a given name in that path is the only one you can select. For example, `cd f[tab]` will pick the *~/.config/fish/functions* directory over */usr/share/fish/functions* directory and the latter won't show up in the pager if you press tab twice.

**Comment by ElijahLynn** [comment]
Just tried that out and while it is interesting. The ability to not have to specify the directories I want is the key here. I jump around a lot and I want it to be smart about the directories I have been to in the past. It needs to just know. 

I also want to be able to enter a few letters of the directory. With $CDPATH I have to still enter the full name, and while the tab completion is nice, the enter key is faster.

**Comment by krader1961** [comment]
> I jump around a lot and I want it to be smart about the directories I have been to in the past. It needs to just know.

The `cd` command already keeps a history of the directories you've visited for the benefit of the `prevd` and `nextd` commands. But I've never cared for that mechanism because it's too hard to reason about. That's why I wrote a `mcd` (menu change directory, see issue #2847) command to show that history from which you can select a destination by entering a single letter. When the completion pager is exposed as a callable widget (see issue #2805) we should be able to provide a solution much closer to what I think you're looking for.

**Comment by ElijahLynn** [comment]
Thanks, I subscribed to #2805.

**Comment by krader1961** [comment]
Okay, I'm going to close this since I think we've exhausted the possible solutions that don't involve an enhancement to the core fish code and those enhancements are already being discussed in other issues.

**Comment by ElijahLynn** [comment]
Deal!
