### ISSUE TITLE
Different `printf` behavior with unicode

### ISSUE THREAD

**Issue by Aeron** [fish-shell/fish-shell#1971]
For example, lets say I want to print _warning sign emoji_ using its UTF-8 code. Because `echo` can't handle unicode escapes and fix for #1894 not yet released (to use combined hex or octal escapes), I should use proper pair of UTF-8 codes and `printf`, just like that: 
```
~ ❯ printf '\u26A0\uFE0F'
```
… which prints :warning: easily.

But, if I want to print _fish emoji_, which have both UTF-8 pair and UTF-8 5-digit codes, the only way I can get one is using UTF-8 5-digit code:
```
~ ❯ printf '\U1F41F'
```
… that prints :fish:. UTF-8 pair prints nothing literally, no output at all (`$status` is 0):
```
~ ❯ printf '\uD83D\uDC1F'
~ ❯
```

Just to be sure, that UTF-8 pair is correct, we can use Python:
```python
print(u'\uD83D\uDC1F')
```

… which prints :fish:.

If I try to put `printf '\uD83D\uDC1F'` somewhere in my `fish_title` function anyway, it becomes broken and Fish will refuse to execute it, but without any errors.

Maybe somehow this issue related to #916, not sure.

**Comment by xfix** [comment]
Works as intended. U+D83D is not a valid Unicode character. Could make a proper error, however.

```
>>> print("\uD83D\uDC1F")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeEncodeError: 'utf-8' codec can't encode character '\ud83d' in position 0: surrogates not allowed
```

(the fact it works in Python 2 is just artifact of implementation, fixed in Python 3)

**Comment by Aeron** [comment]
Ok, understood. Thank you for clarifying this up. Not tried with Python 3, my bad.
