### ISSUE TITLE
race condition with paste + tab complete?

### ISSUE THREAD

**Issue by lunixbochs** [fish-shell/fish-shell#1974]
This happens for me on OS X 10.9 in both Terminal.app and iTerm 2.

1. `mkdir tmp; cd tmp; touch 1S.txt S_1.txt`
2. Copy `S_1` to the clipboard.
3. Type `rm`, space, tab, then paste `S_1`, then tab

Result: `rm 1S.txt`
Expected: `rm S_1.txt`

This will result in deleting the wrong file.

If you manually type `S_1` instead of pasting, it completes to the right thing (`S_1.txt`), which is why I think this could be a race condition.

**Comment by zanchey** [comment]
Nice - happens in 2.1.1 and master. I think it might actually be the pager getting in the way.

**Comment by ridiculousfish** [comment]
Nice find. The "readhead" code strikes again.

**Comment by ridiculousfish** [comment]
Fixed as 7aac3db55cdf84e5d2f8e194ee01c38a6694550b . Thanks for taking the time to report this.
