### ISSUE TITLE
open a gitter.im room

### ISSUE THREAD

**Issue by despairblue** [fish-shell/fish-shell#1975]
Could a repo maintainer open a gitter.im room?

Would be easier for asking questions 'n stuff.

**Comment by zanchey** [comment]
Will have to be @ridiculousfish.

Does it need someone to pay attention to it? I think we're pretty happy with GitHub, the mailing list, IRC and Google Plus at the moment so I can't promise I'll be of any use.

**Comment by despairblue** [comment]
It's comparable to IRC, and serves a similar purpose, so there are no overlaps with the mailing list or google plus. 

Opening the room, shouldn't be more than a few clicks.

I haven't seen the need for moderation in most rooms I've been. Since people are logged in with their github identities (and not some random nick) they tend to just be polite and nice :smile:. I haven't even seen any moderation in https://gitter.im/iojs/io.js for example (though I could have missed that, dunno). In other rooms collaborators also discuss ideas with community members (like in https://gitter.im/ramda/ramda) or in https://gitter.im/strongloop/loopback there is a lot of user provided support. Let's say it very much depends.

I for myself don't like IRC, but there is also an IRC interface to gitter, so one could connect with any IRC client to it: https://irc.gitter.im/

**Comment by bucaran** [comment]
No moderation really needed.

It would be a cool place for fishshellers and new kids to hang out.

:+1:

**Comment by zanchey** [comment]
Oh, I worked out the UI.

https://gitter.im/fish-shell/fish-shell

Being able to join from IRC is pretty neat.

**Comment by ridiculousfish** [comment]
Looks cool :)

is there anything remaining to do here?

**Comment by despairblue** [comment]
lgtm :+1:

**Comment by ridiculousfish** [comment]
Thanks!
