### ISSUE TITLE
"ul: unknown escape sequence" when asking for help

### ISSUE THREAD

**Issue by snnw** [fish-shell/fish-shell#1978]
When trying to display the help text for builtin commands, I get an error, and no help is displayed.  This is Fedora 21, with the latest fish nightly (2.1.1+1222.ge421c12)

To reproduce:
```
$ abbr --help

ul: unknown escape sequence in input: 33, 133

$
```
It seems that `ul` can't handle the escape sequences for bold text that `nroff` generates on my system.  Fixed by either removing `| ul`, or adding `-c` to the `nroff` command.  I'll submit a pull request for the second option. @kballard, could you test if this works on your system?

ul from util-linux 2.25.2
GNU nroff (groff) version 1.22.2

**Comment by ridiculousfish** [comment]
Seems OK on SnowLeopard

**Comment by zanchey** [comment]
Rad.
