### ISSUE TITLE
Strange behaviour after unsetting variable

### ISSUE THREAD

**Issue by bitraten** [fish-shell/fish-shell#1984]
```
~/ set XYZ 0; and echo $XYZ
0
~/ set -e ABC
~/ set XYZ 0; and echo $XYZ
~/
```

**Comment by zanchey** [comment]
Yes, this is because the second `set` fails, and the third `set` doesn't modify the exit status, so the `echo` command never runs.

**Comment by zanchey** [comment]
See #214 et al.

**Comment by bitraten** [comment]
So when [keychain](https://github.com/funtoo/keychain) tries to set a variable with
```
set -e SSH_AGENT_PID; and set -x -U SSH_AGENT_PID 863
```
it's a bug in keychain?

**Comment by zanchey** [comment]
That's a different case - `set` returns an error when erasing a nonexistent variable - but probably isn't desirable behaviour.
