### ISSUE TITLE
`echo` of unset variable omits the whole string

### ISSUE THREAD

**Issue by snnw** [fish-shell/fish-shell#1985]
```
$ set -l b b
$ echo a{$b}c
abc

$ set -e b
$ echo a{$b}c

$
```

I would expect the second command to print `ac`, but it doesn't.  Is this the expected behaviour? For example, `bash -c "echo a\${b}c"` outputs `ac`.

**Comment by snnw** [comment]
I'm on fish, version 2.1.2-1221-g1116929

**Comment by ridiculousfish** [comment]
Yes, it's expected; see https://github.com/fish-shell/fish-shell/issues/352#issuecomment-9555297 . Maybe we track in #354?

**Comment by snnw** [comment]
I see.  I'll close this one in favour of #345.
