### ISSUE TITLE
Initial PATH contains /usr/bin/X11 on debian even though it doesn't exist.

### ISSUE THREAD

**Issue by songgao** [fish-shell/fish-shell#199]
On a debian "squeeze" base system, a custom compiled fish-shell sets its initial PATH to contain /usr/bin/X11, which does not exist in the system. This prevents "set" command from appending more entries into PATH variable because it will look for each entry in the provided PATH list, including the ones already in PATH, but "/usr/bin/X11" does not exist.
"mkdir /usr/bin/X11" makes it work.

Could this be a bug? Probably somewhere for looking up X11 path.

**Comment by ridiculousfish** [comment]
fish stopped complaining about invalid path entries (unless they contain a colon) in de8ccf1751cdd55ef2ba37125bc23c4f7dd404a7.
