### ISSUE TITLE
Parameter expansion sorting.

### ISSUE THREAD

**Issue by brigand** [fish-shell/fish-shell#1993]
> Wildcard matches are sorted case insensitively. When sorting matches containing numbers, consecutive digits are considered to be one element, so that the strings '1' '5' and '12' would be sorted in the order given.
>
> - [docs / Parameter expansion (Globbing) / Wildcards][1]

I was quite confused when this didn't work.

```fish
$ for i in (seq 1 15); touch $i; end; echo *
1 10 11 12 13 14 15 2 3 4 5 6 7 8 9
```

To poke it further

```fish
$ touch a B c
$ echo *
1 10 11 12 13 14 15 2 3 4 5 6 7 8 9 B a c
```

So neither the point about being case insensitive nor the numbers are being held up.

Is this a bug in fish or the docs?  I'm on OSX.

[1]: http://fishshell.com/docs/current/index.html#expand

**Comment by snnw** [comment]
Tested on latest fish, version 2.1.2-1225-g733108e on Linux.  Got the same output as OP.  Not sure if it was intended to break this behaviour.  (I tested 2.0.0 and 2.1.0, all behaved this way).

We should at least fix the documentation for next-minor.

**Comment by ridiculousfish** [comment]
Looks like a regression. This used to work as documented in fish 1.x.

**Comment by ridiculousfish** [comment]
An easy fix. Thanks for taking time to report this!
