### ISSUE TITLE
fish_config does not copy 'set' statements of prompt config

### ISSUE THREAD

**Issue by marcbaas** [fish-shell/fish-shell#1994]
On Mac OSX 10.10.2
Using brew install of fish-shell

When I start fish_config, I have the option to select a new prompt. However, any prompt that has 'set' statements preceding the actual prompt 'function' will have those 'set' statements truncated, with a partially working prompt as a result.

Reproduction steps:
1) run fish_config from the terminal
2) switch to the opened browser and click the 'prompt' tab
3) click the Informative Git Prompt in the left hand menu
4) click the 'use prompt' button

Result:
Only the 'function' part of the prompt code is copied over, the user is taken to the 'current' prompt and it shows the code of the prompt, but all 'set' statements have been stripped out.
This happens with other prompts that use 'set' statements preceding the 'function' as well.

Expected result:
Regardless of type of code, the whole code section for a prompt should be copied over.

Code shown when selecting the desired prompt:
![prompt code](https://cloud.githubusercontent.com/assets/5122112/6769915/0af5b1ec-d0af-11e4-9180-9d0310e12595.png)

Code shown after selecting desired prompt:
![copied code](https://cloud.githubusercontent.com/assets/5122112/6769916/2cd9bd1c-d0af-11e4-8cd1-a194a6b424b4.png)

Note:
When I start fish_config in my terminal I get the following error message:
Web config started at 'file:///Users/{username}/.cache/fish/web_config-FDHXI2.html'. Hit enter to stop.
::1 - - [22/Mar/2015 16:08:23] code 403, message Forbidden

Gives the impression that there is some permission issue as well.

**Comment by ridiculousfish** [comment]
Dup of #1141. It's likely a straightforward fix if you or or anyone is inclined to take a crack at it. Either way, thanks for reporting it!
