### ISSUE TITLE
No Ubuntu package for vivid 15.04

### ISSUE THREAD

**Issue by rvanlaar** [fish-shell/fish-shell#1998]
Please add ubuntu packages for 15.04 Vivid. I'm getting the following errors now with running apt-get update.

W: Failed to fetch http://ppa.launchpad.net/fish-shell/release-2/ubuntu/dists/vivid/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/fish-shell/release-2/ubuntu/dists/vivid/main/binary-i386/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by zanchey** [comment]
I've just copied the binaries over, should work ok.
