### ISSUE TITLE
Feature request: a simple way to opt out of all colorization

### ISSUE THREAD

**Issue by telemachus** [fish-shell/fish-shell#2001]
It would be great if `fish` supported a simple way (ideally a single environment variable) that made _all_ of the shell's colorizations inactive.

So far as I can tell, this isn't possible at present. I would need to go through the `fish_config` checkerboard and select, I guess, black for all foreground and white for all background colors. (These are my shell's default colors.) I'm not even sure if that would remove all the colorizations. (I tried to run `fish_config`, but ended up with [a bit of a mess](https://gist.github.com/telemachus/dbcbcb8aeccd91e22a37).) In any case, that seems like a lot of work for a user who just wants the shell not to emit any extra colors. It also seems counter-productive to ask the shell itself to "set" so many things back to my terminal's default choices. It would be easier for the shell itself (i.e. eat fewer cycles) if it could simply no-op earlier in the process. (I had a [conversation with someone in fish's IRC channel who suggested how this might be done](https://gist.github.com/telemachus/10ff40c6e432a391a9c6), but I don't know the codebase—or C++—at all, so I'm reluctant to suggest an actual patch.)

Thanks for considering it.

**Comment by telemachus** [comment]
I'm colorblind (red/green). I have a hard with the default settings in fish (some things are too light or blend into each other). And over the years, I've learned more generally that white background with black text is easiest on my eyes and most productive for me.

**Comment by ridiculousfish** [comment]
Thanks for the explanation. In the next release, we're moving away from the over-complicated customize-each-color UI, and towards a "theme chooser."  Here's a screenshot of what it will look like:

![screen shot 2015-03-27 at 1 35 59 pm](https://cloud.githubusercontent.com/assets/920838/6876603/3efe9712-d486-11e4-9653-e4f41493b6ed.png)

That one shows the Mono Lace theme, which is shades of dark gray suitable for light backgrounds. Would that theme work for you, or would you prefer one which is entirely black text?

**Comment by telemachus** [comment]
> Selected is the Mono Lace theme, which is shades of dark gray suitable for light backgrounds. Would that theme work for you, or would you prefer one which is entirely black text?

Some thoughts:

1. The new chooser looks *much* more straightforward.
1. I think that the Mono Lace theme very likely work well for me.
1. I still think that for technical and other reasons it might be worth having a "kill switch" to turn off all color extras.

No matter what you decide, thanks for taking my request and reasons seriously. I appreciate it.

**Comment by ridiculousfish** [comment]
Thank you for reporting it!

**Comment by telemachus** [comment]
Last question: I realize now I closed this unintentionally. Is it better for you for me to leave it open or closed?

**Comment by ridiculousfish** [comment]
Reopening.

**Comment by zanchey** [comment]
Something to consider is that fish won't output colour if the underlying terminal doesn't support color. So something like `env TERM=ansi-mono fish` - on my system at least - results in a reasonably sensible output, except minus colors. Unfortunately it is missing a few definitions as well. You could probably fiddle with the output of `infocmp` and feed it in to `tic` to produce an appropriate terminal definition for your system.

**Comment by telemachus** [comment]
@zanchey Thanks for the tip. To be frank, I wouldn't really know what to do with the output of `infocmp`, nor how to feed it to `tic` (nor what that means really). So if the output is only "reasonably sensible", I think I'll wait for a patch. Again, thanks though.

**Comment by zanchey** [comment]
By reasonably sensible, I mean "I started it and it seems to work". The terminal capabilities database is what fish uses to decide whether your terminal supports color, so I think it would be reasonable to use that to turn off color support!

The short answer is that you may be able to get what you want straight away by setting your terminal emulator to use `xterm-mono` instead of `xterm-256color` or `xterm` as a terminal type, depending on your operating system. What OS and terminal emulator are you using?

**Comment by telemachus** [comment]
@zanchey I'm on OS X, using Terminal.app. I'll give that a try in the next few days. Thanks.

**Comment by RomanHargrave** [comment]
@telemachus 
I just tested a possible solution, which the latest version of fish allows for due to a fix in the the builtin function deletion functionality. You can simply delete set_color and the redefine it as a no-op.

```fish
functions -e set_color
function set_color; end
```

Now, this *will* also break underlining, etc, via set_color, but it could be easy enough to make that noop allow for those options to pass and others by calling the builtin forcibly via `builtin set_color`.

**Comment by ridiculousfish** [comment]
Hah, that's brilliant.

**Comment by krader1961** [comment]
Closing since there are three ways to achieve the desired result.
