### ISSUE TITLE
Command Substitutions with pipe?

### ISSUE THREAD

**Issue by demonking** [fish-shell/fish-shell#2002]
Hello,

I have a problem with command substitutions with pipes?

In bash-shell it would looks like this:

    cd $(ls | percol)

execute the command between the $() and then output the information to cd.

But in fish-shell it doesn't seems to work ? or i'm making some mistakes?
     cd (ls | percol)

Or is percol here the problem?

**Comment by aboisvert** [comment]
I asked a similar question in the past:
(http://sourceforge.net/p/fish/mailman/message/32501848/)

and was pointed towards this issue:
https://github.com/fish-shell/fish-shell/issues/1362

**Comment by demonking** [comment]
@aboisvert  thx for you answer, it seems, that i have to fix it through more calls like `xarg`etc

**Comment by ridiculousfish** [comment]
Thanks @aboisvert . Yes, dup of #1362. The issue is processes that expect to own the term when running inside command substitutions. We'll likely fix it in the release after the upcoming one.

**Comment by ridiculousfish** [comment]
Thanks for reporting this!
