### ISSUE TITLE
Multi-line prompts are repeating on random keypress

### ISSUE THREAD

**Issue by Nuclearfossil** [fish-shell/fish-shell#2003]
running fish on cygwin and mintty (or ConEmu2) on Windows 7

With the following prompt script:
function fish_prompt
   set_color yellow
   printf '%s' (whoami)
   set_color normal
   printf ' at '

   set_color magenta
   printf '%s' (hostname|cut -d . -f 1)
   set_color normal
   printf ' in '

   set_color $fish_color_cwd
   printf '%s' (prompt_pwd)
   set_color normal

   # Line 2
   if test $VIRTUAL_ENV
       printf "(%s) " (set_color blue)(basename $VIRTUAL_ENV)(set_color normal)
   end
   set_color normal
   printf "\n>"
end

during random intervals, the shell re-dispalys the prompt, like so:

Ash at Ash-PC in ~
Ash at Ash-PC in ~
Ash at Ash-PC in ~
Ash at Ash-PC in ~
Ash at Ash-PC in ~
Ash at Ash-PC in ~
Ash at Ash-PC in ~
>ls -alh

To be clear, on each character of the command, we get a new line added above the command.

**Comment by danielmatz** [comment]
I've also seen this.  I tried to describe it towards the end of the discussion on #1403.

**Comment by Nuclearfossil** [comment]
I think what you're describing in #1403 if fairly close to what I'm experiencing.  I'm going to try using that prompt in iTerm2 on OSX today at some point to see if it repros there.

**Comment by valakyr** [comment]
I'm experiencing this issue too and my 7 month old question on [superuser](http://superuser.com/questions/811882/cygwin-fish-mutiline-prompt) still doesn't have an answer.

**Comment by barksdml** [comment]
This remains an issue -- Fish+Win7+ConEmu.  For me it only started when I made my prompt span multiple lines.

**Comment by krader1961** [comment]
Closing this as a dup of issue #2859. Normally I'd close the newer issue but that one has more info and it looks like me might get some traction on determining what's wrong.
