### ISSUE TITLE
Bug in Python completion

### ISSUE THREAD

**Issue by RicterZ** [fish-shell/fish-shell#2004]
![image](https://cloud.githubusercontent.com/assets/5282759/6889352/10bc4e88-d6c7-11e4-8595-03e2308a93a7.png)

Something wrong when I type `python 1[tab]`.

**Comment by zanchey** [comment]
Wow. Could you post the output of `python -V`?

**Comment by RicterZ** [comment]
@zanchey I use PyPy

    Python 2.7.8 (a980ebb26592ed26706cd33a4e05eb45b5d3ea09, Dec 13 2014, 07:07:50)
    [PyPy 2.4.0 with GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]

**Comment by zanchey** [comment]
Right, there's a problem with the regex under BSD sed compared to GNU sed. Reproduces on FreeBSD 10.0.

**Comment by zanchey** [comment]
Should be fixed with 900a8a1 - thanks!

**Comment by RicterZ** [comment]
Nice response time :) 
Thank you very much.

**Comment by ridiculousfish** [comment]
Hah, nice!
