### ISSUE TITLE
Warn when setting universal variables in config.fish

### ISSUE THREAD

**Issue by rokugou** [fish-shell/fish-shell#2005]
I am using OS X Yosemite(10.10.2).
Fishshell hang on startup.
I tried to remove ~/.config/fish/fishd.b88d12171004,
everything's ok.

**Comment by ridiculousfish** [comment]
Can you post the contents of `~/.config/fish/fishd.b88d12171004`? https://gist.github.com if you need a place.

**Comment by rokugou** [comment]
i can't reproduce the problem right now,
i will post the fishd.b88d12171004 next time.
Thank you!

Here is my current fishd.b88d12171004
```
# This file is automatically generated by the fishd universal variable daemon.
# Do NOT edit it directly, your changes will be overwritten.
SET __fish_init_1_22_0:\x1d
SET __fish_init_1_50_0:\x1d
SET fish_color_autosuggestion:555\x1eyellow
SET fish_color_command:005fd7\x1epurple
SET fish_color_comment:red
SET fish_color_cwd:green
SET fish_color_cwd_root:red
SET fish_color_error:red\x1e\x2d\x2dbold
SET fish_color_escape:cyan
SET fish_color_history_current:cyan
SET fish_color_match:cyan
SET fish_color_normal:normal
SET fish_color_operator:cyan
SET fish_color_param:00afff\x1ecyan
SET fish_color_quote:brown
SET fish_color_redirection:normal
SET fish_color_search_match:\x2d\x2dbackground\x3dpurple
SET fish_color_valid_path:\x2d\x2dunderline
SET fish_greeting:Welcome\x20to\x20fish\x2c\x20the\x20friendly\x20interactive\x20shell\x0aType\x20\x1b\x5b32mhelp\x1b\x5b30m\x1b\x5b0\x3b10m\x20for\x20instructions\x20on\x20how\x20to\x20use\x20fish
SET fish_key_bindings:fish\x5fdefault\x5fkey\x5fbindings
SET fish_pager_color_completion:normal
SET fish_pager_color_description:555\x1eyellow
SET fish_pager_color_prefix:cyan
SET fish_pager_color_progress:cyan
SET fish_user_paths:/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin
```

**Comment by ridiculousfish** [comment]
Thanks. If this no longer reproduces then there's nothing we can do.

I'm going to close, but please comment if you see it again and I'll reopen. Thanks!

**Comment by rokugou** [comment]
https://www.youtube.com/watch?v=alsKJ8CXNTE

here is my fishd.b88d12171004
# This file is automatically generated by the fishd universal variable daemon.
# Do NOT edit it directly, your changes will be overwritten.
SET __fish_init_1_22_0:\x1d
SET __fish_init_1_50_0:\x1d
SET fish_color_autosuggestion:555\x1eyellow
SET fish_color_command:005fd7\x1epurple
SET fish_color_comment:red
SET fish_color_cwd:green
SET fish_color_cwd_root:red
SET fish_color_error:red\x1e\x2d\x2dbold
SET fish_color_escape:cyan
SET fish_color_history_current:cyan
SET fish_color_match:cyan
SET fish_color_normal:normal
SET fish_color_operator:cyan
SET fish_color_param:00afff\x1ecyan
SET fish_color_quote:brown
SET fish_color_redirection:normal
SET fish_color_search_match:\x2d\x2dbackground\x3dpurple
SET fish_color_valid_path:\x2d\x2dunderline
SET fish_greeting:Welcome\x20to\x20fish\x2c\x20the\x20friendly\x20interactive\x20shell\x0aType\x20\x1b\x5b32mhelp\x1b\x5b30m\x1b\x5b0\x3b10m\x20for\x20instructions\x20on\x20how\x20to\x20use\x20fish
SET fish_key_bindings:fish\x5fdefault\x5fkey\x5fbindings
SET fish_pager_color_completion:normal
SET fish_pager_color_description:555\x1eyellow
SET fish_pager_color_prefix:cyan
SET fish_pager_color_progress:cyan
SET fish_user_paths:/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin\x1e/Users/roku/dev/gradle\x2d2\x2e2\x2e1//bin

**Comment by ridiculousfish** [comment]
In your `~/.config/fish/config.fish`, you have a line like `set fish_user_paths $fish_user_paths /Users/roku/dev/gradle...` which is causing all this trouble. My question is, how did it get there? Did someone advise you to add that?

**Comment by rokugou** [comment]
i have a line
```
set --universal fish_user_paths $fish_user_paths $GRADLE_HOME/bin
```

I forgot....
maybe here: https://github.com/fish-shell/fish-shell/issues/527

**Comment by zanchey** [comment]
I wonder if it's worth producing a warning with `set -U` in `config.fish`.

**Comment by ridiculousfish** [comment]
People are hitting this frequently. A warning sounds good.

**Comment by ridiculousfish** [comment]
Designing this...

I think the warning ought to be issued if the variable is already set. This is avoids warning on benign cases like `if set -q var ; set -U var...`

Proposed text (in this case, for PATH)

    fish: Warning: $PATH is set as a universal variable during initialization.

I thought about giving a pointer to documentation, but decided that was useless noise. Users will just  Google for the error message, and we'll have documentation describing what it means, that should rate highly in the search results.

The one thing this is missing is a backtrace. I don't want to dump the whole backtrace but maybe we can just give the first line, something like:

        fish: Warning: $PATH is set as a universal variable during initialization.
        ~/.config/fish/config.fish (line 17): set -U PATH $PATH ~/bin

**Comment by zanchey** [comment]
I suspect it's not straightforward, but if the error message is only printed in the case of adding to variables (`set -U PATH foo $PATH`) rather than setting them directly (`set -U PATH foo bar`) that might avoid some false positives.

**Comment by faho** [comment]
This probably won't happen for 2.3.

**Comment by faho** [comment]
Closing in favor of #7379 - we want to rethink universal variables.
