### ISSUE TITLE
`**` causes tremendous input lag on OS X

### ISSUE THREAD

**Issue by Lordnibbler** [fish-shell/fish-shell#2006]
When entering `**` into Fish shell, the shell becomes unresponsive and laggy on OS X 10.10.2

**Comment by snnw** [comment]
Thank you for your report.

I don't see this behaviour in Fish version 2.1.2-1238-g900a8a1 (latest nightly).  Could you try to reproduce this with the latest nightly?  (https://github.com/fish-shell/fish-shell/wiki/Nightly-builds)

**Comment by Lordnibbler** [comment]
Seems to work great on 2.1.2-1238-g900a8a1

**Comment by Lordnibbler** [comment]
`CMD_DURATION` appears now to return ms, rather than seconds now. Expected?
