### ISSUE TITLE
Settings Path config

### ISSUE THREAD

**Issue by SeeThruHead** [fish-shell/fish-shell#2009]
Hello, I guess this is more of a request or maybe a question even.

I'm using thoughtbotts rcm to manage my rc files. The convention is that your rc files live inside of ~/.dotfiles and rcm handles the linking to your home directory.

I would like to set my fish configuration to the same convention, like i do with bash and zsh.
I guess the best way to do that would be a fish/ folder inside dotfiles with fish_history ignored (or possibly the option to store this file outside of the config?)

Could a a config directory be made available as an option when installing? Is there a convenient way I could change this options now? Perhaps as part of my system provisioning?

EDIT: To clarify what I would like is the ability to have fish look inside ~/.fish/config.fish and ~/.fish/fishd instead of the default.

**Comment by ridiculousfish** [comment]
fish uses `$XDG_CONFIG_HOME` if it's set, and falls back to ~/.config/fish otherwise. Is that variable set for you?

**Comment by SeeThruHead** [comment]
I'm on osx 10.10 so it does not look like it is set, thought other programs install to .config (this is the secondary reason I want to move it, I do not version the files inside config as I have no created them mystelf.)

**Comment by ridiculousfish** [comment]
You might try symlinking ~/.config/ to ~/.dotfiles too

**Comment by SeeThruHead** [comment]
That is specifically what I would like to avoid.

**Comment by SeeThruHead** [comment]
If you take a look at my dotfiles repo here I think it shows better what I'm talking about:
https://github.com/SeeThruHead/dotfiles
So if I were to explain to someone who had never even seen a dotfile before, what they do and where they go. It would be easy to tell them that they live inside your home directory, and that lots of people use things like scripts/rcm/homeschick to symlink the files from a vc'd folder. You can clearly see that the config file is names somethingrc and lives in the home folder.
Then you get to the fish config and the convention is broken. It would be nice to force this particular convention if the end user chooses too. For consistencies sake.

**Comment by zanchey** [comment]
I don't use rcm, but Is `mkrc -s ~/.config/fish/config.fish` not appropriate?

**Comment by SeeThruHead** [comment]
that is the standard. The issue has nothing to do with functionality. It's a feature request, the ability to customize file locations to match your personal conventions.

**Comment by krader1961** [comment]
Closing because this has been asked before and we've concluded there isn't a good reason to add yet another way to specify where the config scripts live.
