### ISSUE TITLE
Up arrow should show last match in history

### ISSUE THREAD

**Issue by frangio** [fish-shell/fish-shell#2010]
I find it very confusing that when I type something in the command line and the greyed out suggestion is precisely what I want to type, I have to press the right arrow instead of the up arrow. This happens because pressing the up arrow shows the previous-to-last match in history, i.e. it skips the last match.

What is the rationale for this? I personally feel that the current behaviour is unintuitive. Pressing the up arrow should show the last match first.

**Comment by ridiculousfish** [comment]
The rationale is that pressing the up arrow should cause the command line to change; if the autosuggestion matches the last history item then it won't change. Dup of #405. Your thoughts are welcome there. Thanks for reporting this.

**Comment by frangio** [comment]
Okay thanks for pointing out the duplicate. I'll make sure to search before posting next time!
