### ISSUE TITLE
help command loads wrong URL when built from git

### ISSUE THREAD

**Issue by alphapapa** [fish-shell/fish-shell#2011]
I just built and installed the latest commit, then ran `help history`, and Fish loaded this url: `http://fishshell.com/docs/9f8cec7/index.html#history`.  Of course, it returns a 404.

Thanks.

**Comment by zanchey** [comment]
Could you post the output of `echo $FISH_VERSION`? I suspect you don't have the right tags in your git repository.

**Comment by alphapapa** [comment]
Haha, I guess that's what I get for doing `git clone --depth 1`.  :)  Sorry.
