### ISSUE TITLE
Make doxygen version warning more prominent

### ISSUE THREAD

**Issue by alphapapa** [fish-shell/fish-shell#2012]
fish 2.0.0 from Ubuntu package `2.0.0-1` shows this for `history --help`:

```

       history - Show and manipulate command history

   [1mS[30m(B[m[1my[30m(B[m[1mn[30m(B[m[1mo[30m(B[m[1mp[30m(B[m[1ms[30m(B[m[1mi[30m(B[m[1ms[30m(B[m
       history (--save | --clear)
       history (--search | --delete ) (--prefix 'prefix string' | --contains 'search string')

   [1mD[30m(B[m[1me[30m(B[m[1ms[30m(B[m[1mc[30m(B[m[1mr[30m(B[m[1mi[30m(B[m[1mp[30m(B[m[1mt[30m(B[m[1mi[30m(B[m[1mo[30m(B[m[1mn[30m(B[m
       history is used to list, search and delete the history of commands
       used.

       The following options are available:

       · --save saves all changes in the history file. The shell automatically
         saves the history file; this option is provided for internal use.

       · --clear clears the history file. A prompt is displayed before the
         history is erased.

       · --search returns history items in keeping with the --prefix or
         --contains options.

       · --delete deletes history items.

       · --prefix searches or deletes items in the history that begin with the
         specified text string.

       · --contains searches or deletes items in the history that contain the
         specified text string.

       If --search is specified without --contains or --prefix, --contains
       will be assumed.

       If --delete is specified without --contains or --prefix, only a history
       item which exactly matches the parameter will be erased. No prompt will
       be given. If --delete is specified with either of these parameters, an
       interactive prompt will be displayed before any items are deleted.

   [1mE[30m(B[m[1mx[30m(B[m[1ma[30m(B[m[1mm[30m(B[m[1mp[30m(B[m[1ml[30m(B[m[1me[30m(B[m
       history --clear deletes all history items

       history --search --contains 'foo' outputs a list of all previous
       commands containing the string 'foo'.

       history --delete --prefix 'foo' interactively deletes the record of
       previous commands which start with 'foo'.
```

But the latest fish commit shows this:

```
$ history --help

```

That is, nothing.  :)

**Comment by zanchey** [comment]
My psychic powers tell me you do not have Doxygen installed.

**Comment by ridiculousfish** [comment]
@alphapapa can you confirm this is fixed if you install doxygen, and then do a full rebuild (`make distclean; autoconf; ./configure; make; sudo make install`)?

**Comment by alphapapa** [comment]
Hmm, well, I actually do have doxygen installed:
```
apt-cache policy doxygen
doxygen:
  Installed: 1.8.6-2
  Candidate: 1.8.6-2
  Version table:
 *** 1.8.6-2 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
```
But this may have been caused by my doing a shallow clone, which caused issue #2011.

**Comment by zanchey** [comment]
Sorry, I should have specified - you need Doxygen 1.8.7 (per the [README](https://github.com/fish-shell/fish-shell/blob/master/README.md)). I ended up backporting it in Debian; there might be a PPA available for Ubuntu?

If you are trying to run the bleeding edge, can I suggest a [nightly build](https://github.com/fish-shell/fish-shell/wiki/Nightly-builds)?

**Comment by alphapapa** [comment]
zanchey, thank you, I didn't notice that a newer Doxygen is required.  I'm building it now, and then I'll rebuild fish.

Couple of ideas:

1.  Maybe I missed it, but could the configure script check for the right version of Doxygen, and/or could its warning be more prominent?
2.  If the Debian packaging were maintained in the fish repo, it would be a lot easier to do this, because the dependencies could be updated with fish itself.  Then it would simply be a matter of checking out a revision and building the Debian package, which would give appropriate warnings if the correct dependencies (and versions) weren't installed.

Should I file issues for these?

Thanks.

**Comment by zanchey** [comment]
We could definitely make the warning bigger; I'll reopen this to track that.

**Comment by krader1961** [comment]
Two years and no one has felt the need to improve the warning when `./configure` is run without the `--with-doxygen` flag to force the use of doxygen. Which would cause the configure step to fail in this situation. I don't think that there is any way of improving the warning which would meaningfully keep this from recurring. The only realistic option is to make an missing or invalid version of doxygen a fatal error. Closing.

**Comment by zanchey** [comment]
One thing I thought of was having a summary at the bottom of the configure script, like pcre2 does, with the configurable options that are set.

**Comment by zanchey** [comment]
CMake does this really nicely.
