### ISSUE TITLE
Add forward-kill-arg and backward-kill-arg

### ISSUE THREAD

**Issue by jonhoo** [fish-shell/fish-shell#2014]
The `Alt+<backspace>` (kill last word) and `Ctrl+W` (kill last path component) family of keyboard shortcuts are very useful, particularly when editing previously issued commands, as they allow deleting chunks of command-line parameters faster than character-by-character. Beneath the hood, they are implementing using the forward/backward-kill-\* functions, and in particular, `*-kill-path-component`. However, in many cases, it would be very convenient to have a keyboard shortcut for killing an entire argument. For example, given the following input with the cursor at the end:

```
$ mplayer --no-video music/a.mp3
```

pressing `Ctrl+W` here will delete `a.mp3`, but there is no shortcut for deleting the entire last argument (`Alt+<backspace>` would delete only `mp3`). This can in many cases be useful when you have a complicated command invocation where there's a a single (but potentially long) argument that you want to change.

I propose another variation of the _-kill-_ commands should be added, namely `forward-kill-arg` and `backward-kill-arg`, that delete the next and previous _argument_ respectively. In particular, in the above example, `backward-kill-arg` would kill the full `music/a.mp3`. I'm not sure what a good shortcut would be for this (nor whether one should necessarily be provided by default), but it certainly seems like a useful feature!

**Comment by aboisvert** [comment]
Love this idea.

**Comment by snnw** [comment]
I like this too.  Can we have a separate bug for the `ls I\ am\ a\ file` case?  That can be fixed separately from this enhancement idea.

**Comment by jonhoo** [comment]
Reported in #2016.

**Comment by snnw** [comment]
Thank you for filing the separate bug.  Let's focus on the "kill entire
argument/path" use-case here.

**Comment by jonhoo** [comment]
I updated the bug description to no reference the bug at all.

**Comment by zx8** [comment]
Massive +1 for this!

**Comment by faho** [comment]
Slightly reinterpreted as \*-kill-**token**, the backward-version of this is _really_ simple:

```fish
bind SOMETHING "commandline -rt ''"
```

while the forward version is rather hard since it's surprisingly difficult to get the _next_ token.

**Comment by faho** [comment]
Wait a minute, what's the difference between this and \*-kill-bigword?

With the following commandline contents

```fish
echo $flounder >& | less; and echo $catfish
```

 backward-kill-bigword will delete like this (cursor at the very end):

```fish
echo $flounder >& | less; and echo
echo $flounder >& | less; and
echo $flounder >& | less; 
echo $flounder >& | 
echo $flounder >& 
echo $flounder 
echo 

```

With `mplayer --no-video music/a.mp3`:

```fish
mplayer --no-video
mplayer

```

I'm assuming forward-k-bw does it the other way around.

The [documentation](file:///usr/share/doc/fish/commands.html#bind) says:

> backward-kill-bigword, move the whitespace-delimited word to the left of the cursor to the killring

So, in other words @jonhoo: This appears to be possible now, it's just called a little differently than what you thought. If you see any difference, please say so.

**Comment by jonhoo** [comment]
`backward-kill-bigword` seems like almost what I want, though the description makes me think that it wouldn't handle, say, the following cases correctly:

```
echo "a b"
echo a\ b
```

In both of these cases `backward-kill-arg` should leave only `echo`. I don't have a shell available right now to test though, so would be great if someone could verify that this is indeed the behavior of `backward-kill-bigword`.

**Comment by faho** [comment]
The latter case works, the former doesn't, and it might be considered a bug.

**Comment by jonhoo** [comment]
Found a terminal. `bigword` seems to be broken in other ways too. For example:

```
echo a b c
```

`backward-kill-bigword` will kill **both** b and c, whereas it should delete only c on the first invocation. I'm also not sure that the first case in my post above *should* work with `backward-kill-bigword`. From its description, `echo "a` is the correct thing for it to leave after `echo "a b"`.

**Comment by jonhoo** [comment]
@faho I've recently found myself missing this feature again... From the docs on `kill-bigword`, I read it as killing back to the nearest whitespace boundary. Is that an accurate interpretation? Because if so, I don't think it fully applies to killing the last argument..

**Comment by lilyball** [comment]
The behavior of `bigword` seems to be broken right now when it should be doing single-char movements (see https://github.com/fish-shell/fish-shell/issues/7325), which explains the observed behavior with `backward-bigword` on `a\ b`. bigword movement is not expected to care about fish syntax, only about whitespaces, so escapes and quotes don't matter.

I would really love to see forward/backword-[kill-]arg bindings that do explicitly care about fish syntax.

**Comment by chapmanjacobd** [comment]
I've added a PR for

- forward-arg: Move to immediately before first character in the current arg.
- backward-arg: Move to immediately after the last character in the current arg.
- kill-arg: Same as forward-arg, but also delete the characters between.
- backward-kill-arg: Same as backward-arg, but also delete the characters between.

I've chosen "*-token" because that naming is more consistent with internal naming.
