### ISSUE TITLE
Change $hostname when the hostname changes

### ISSUE THREAD

**Issue by lilyball** [fish-shell/fish-shell#202]
`fishd` already knows when the hostname changes. It would be great if it could emit an event, so anything that depends on the current hostname can update. For example, if I have my hostname in my fish_prompt, I'd like to update that when my hostname changes.

**Comment by krader1961** [comment]
At first I was inclined to close this as "will-not-fix" because it seemed like a feature that would be useful in very few  situations. After all, how often does the hostname of your server change? Then it occurred to me that my laptop's hostname changes all the time as I connect to different networks :-)

**Comment by ridiculousfish** [comment]
We don't have any reason to monitor the hostname any more, so this no longer feels natural. I think we ought to close.

**Comment by krader1961** [comment]
I cloned the current bash source and examined it. AFACT it only sets the `$HOSTNAME` var at startup. So bash will not change the value of that var when the hostname changes (e.g., in response to connecting to a different network). Also, zsh doesn't define this var. And given that fish no longer has a reason to detect hostname changes this enhancement can't be justified.

**Comment by floam** [comment]
> We no longer base the universal variable file name on the hostname, so we don't have  any reason to monitor the hostname any more. So this no longer feels natural. I think we ought to close.

We provide an electric `$hostname` variable now, so the circumstances have changed a bit. We do currently set the hostname only on startup. I have a PR in the works that is piggy-backing on the macOS `eventd` universal variable notifier file descriptor with `NOTIFY_REUSE`, further registering a for "com.apple.system.hostname" notifications.

**Comment by faho** [comment]
>This is a macOS-specific enhancement

Please don't.

Even if it weren't macOS-specific, this isn't actually something that people would use or expect to happen. Changing the hostname also happens very rarely.

**Comment by floam** [comment]
Why would a person be more likely to expect `$hostname` will be stuck with what fish started with, rather than it perhaps being grabbed on every access ? @kballard seemed like she'd have liked it in 2012.

I can't see why not to, since we already register for notifications from notifyd, it's extremely lightweight.

**Comment by kballard** [comment]
As long as we're providing an electric `$hostname` variable, it absolutely should track the current hostname. And in fact I'd go so far as to say `__fish_config_interactive` should set up a `function --on-variable hostname` that repaints the current prompt if the hostname changes (under the assumption that the prompt contains it, since it frequently does).

**Comment by floam** [comment]
Yeah, that's the user-friendly sensible way for any modern software to behave. The fact that fish could demonstrate the hostname being changed in a settings panel, with it responding instantaneously in the prompt windows isn't the raison d'être, but it sure is pretty rad that our shell for the 90s is already plugged in to exactly accommodate an ideal implementation.

**Comment by lilyball** [comment]
I just ran into this again. My hostname changed but Fish didn't notice and there seems to be no way to reset the `$hostname` variable short of execing a brand new instance of Fish.

**Comment by ridiculousfish** [comment]
Do you have a suggestion for how to detect when the hostname changes? Of course polling is an option but feels clumsy.

**Comment by lilyball** [comment]
How expensive would it be to just call `gethostname()` every time the `$hostname` variable is accessed? Or perhaps caching the value only for a short while (in interactive shells, until the next time the prompt is painted; for scripts I don't know what an appropriate time frame is).

I also took a look at SystemConfiguration.framework on macOS. Here's a Swift tool that watches for changes to the LocalHostName configuration:

```swift
import Foundation
import SystemConfiguration

func getLocalHostname(from store: SCDynamicStore) -> String {
    return SCDynamicStoreCopyLocalHostName(store) as String?
        ?? "(unknown)"
}

func callout(_ store: SCDynamicStore, changedKeys: CFArray, info: UnsafeMutableRawPointer?) {
    // Our only key is the hostnames key
    // This might include hostnames other than the local hostname
    // so the local hostname might not have actually changed
    print("Hostname changed:", getLocalHostname(from: store))
}

let store = SCDynamicStoreCreate(kCFAllocatorDefault, "HostnameMonitor" as CFString, callout, nil)!
if !SCDynamicStoreSetNotificationKeys(store, [SCDynamicStoreKeyCreateHostNames(kCFAllocatorDefault)] as CFArray, nil) {
    fatalError("Failed to set notification keys")
}
let runLoopSource = SCDynamicStoreCreateRunLoopSource(kCFAllocatorDefault, store, 0)!
CFRunLoopAddSource(RunLoop.main.getCFRunLoop(), runLoopSource, .commonModes)
print("Current hostname:", getLocalHostname(from: store))
RunLoop.main.run()
```

This seems to work when I change my local hostname in system preferences. However this doesn't actually match what `gethostname()` / `/bin/hostname` does. Changes to system preferences don't seem to affect `hostname` and vice versa. On both of my Macs the `hostname` matches the configured local hostname, but I don't know under what conditions `hostname` ever returns something else. `hostname` appears to map to the sysctl `kern.hostname` value (on macOS) or `kernel.hostname` value (on Linux) but that doesn't seem to help. My best guess is DHCP can set my computer's hostname, but I don't know why I'd have ever hit that case myself.

Ultimately, I haven't found any way to monitor changes to what `gethostname()` returns, which suggests we should just have some heuristic for when we check it again. Or, worst case, we should allow the user to modify the `$hostname` variable instead of keeping it read-only (though automatically updating would be much nicer).

---

FWIW the scenario that prompted my interest in this was my laptop started showing bad paths in the Terminal titlebar, and upon closer inspection, `$hostname` was set to some garbage value. I don't know how that could have possibly happened, but `/bin/hostname` was already returning the correct string at this point. And since `$hostname` is a read-only variable, the only way to fix this was to exec a brand new instance of `fish`. I could do that in this scenario because I didn't have any local state I needed to preserve besides the cwd, but that's obviously not doable in all cases.

**Comment by Darkshadow2** [comment]
The local host name returned by SCDynamicStore is only used with Bonjour, I think. If you want to get the host name, you need to use the SCPreferences api, but unless you're running as root that requires authorization (I think).

You can also use `scutil` to get it (`scutil --get HostName`), but just using `/bin/hostname` is probably simpler (as far as I know, they return the same thing).

(You can see how `scutil` is doing it: <https://opensource.apple.com/source/configd/configd-1061.40.2/scutil.tproj/prefs.c.auto.html>)

You can monitor for host name changes using the notify functions with the key "com.apple.system.hostname", but that's obviously macOS specific.

**Comment by zanchey** [comment]
`gethostname(3)` is cheap on Linux, but I'm not sure about other platforms. Some invocations of `hostname(1)` will do network traffic, so that's a non-starter (but we wouldn't use that anyway).

**Comment by lilyball** [comment]
`scutil --get HostName` only works if you've used `scutil` (or the SystemConfiguration API) to persistently set the `HostName` value, which does populate `gethostname()` after reboot. But just doing something like `sudo hostname Foo` doesn't touch SystemConfiguration, so `scutil --get HostName` still says "HostName: not set".

On macOS `/bin/hostname` is just a [thin wrapper](https://opensource.apple.com/source/shell_cmds/shell_cmds-170/hostname/hostname.c.auto.html) around `gethostname()`/`sethostname()`. And `gethostname()` itself is just a [thin wrapper](https://opensource.apple.com/source/Libc/Libc-167/gen.subproj/gethostname.c.auto.html) around the equivalent of `sysctl kern.hostname`. So at least on macOS `gethostname()` is presumably fairly cheap.

I hadn't heard of `"com.apple.system.hostname"` before, this appears to be `kNotifySCHostNameChange` and is documented as being about System Configuration notifications, so this appears to be just a replacement for what I was already testing above, though I'm also not sure if it's working as `notifyutil -w com.apple.system.hostname` never printed anything no matter what I tried.

**Comment by Darkshadow2** [comment]
Huh, I never tried setting it via `hostname` (or directly with `sysctl`) before and never knew the notification wouldn't work in that case.

It should work if the system decides to change the hostname for some reason, though. That should go through the System Configuration stuff.

I originally used it back when whatever version of macOS decided to change your host name because it thought there was already some other host with that name due to Bonjour going crazy. It worked flawlessly then to reset the host name (and computer name and local host name) back to what it should be. 😄

**Comment by lilyball** [comment]
If the system changes the local hostname due to a perceived conflict it should work. If it changes the current hostname (as reported by `hostname`) in response to something like DHCP then I expect it won't do anything because that's not a persistent setting.

It still seems to me that the only real solution here is to come up with an appropriate heuristic for when we should discard our hostname cache and check again. Or just make `$hostname` query `gethostname()` every single time, though if I refer to the same variable many times within a single function it seems wasteful to re-query on every access.

**Comment by zanchey** [comment]
Just need to work out the cache invalidation around the naming of... oh, no.

**Comment by lilyball** [comment]
Two things:

1. I just found a scenario where my laptop's `hostname` changes. When I connect to my work VPN.
2. The biggest thing that `hostname` affects for me is when fish invokes `__update_cwd_osc` to tell my terminal where it is, if it uses the wrong hostname my terminal can't match that to a location on disk. It would be nice if fish could at least invalidate the `$hostname` variable at this point, though I think invalidating it on every prompt might be preferable (perhaps with a builtin that can invalidate it on demand, for long-running scripts to use if they're impacted by this).

If anyone has any ideas for something to try in order to see if there's any kind of notification on hostname change in this scenario, since I know how to change my hostname at will now (e.g. connecting/disconnecting from VPN) I can try it out. But I wasn't able to find any information on this when searching so I suspect the best we can do is just invalidate the variable at reasonable times.

**Comment by floam** [comment]
Subscribe to the notification. We already use notify on MacOS

–
Aaron

**Comment by lilyball** [comment]
@floam Looks like registering for `kNotifySCHostNameChange` works in the scenario where connecting to VPN changes my hostname. It doesn't work for manual invocations of the `hostname` utility to change my hostname. Supporting hostname changes due to network changes would be the primary use-case here though, so using `notify` for `kNotifySCHostNameChange` to handle that would be good enough for most cases.

**Comment by faho** [comment]
Okay, this has been open for 9 years at this point, the last activity was last year.

I also hate it. So since nobody appears to be doing it and I'm against it, I'm closing this.
