### ISSUE TITLE
Feature: sentinel string syntax

### ISSUE THREAD

**Issue by tomekwi** [fish-shell/fish-shell#2021]
Are there any plans to support the sentinel `<<EOF`? I often used it in bash with the `cat` command, and liked the clean syntax:

```bash
$ cat <<— | mustache - template.mustache
---
name: Bob
age: 30
---
—
Hi there! I’m a 30-year-old Bob.
```

**Comment by ridiculousfish** [comment]
These are called HEREDOC strings. #540 is the issue where we discuss adding them. Your thoughts are welcome there :)
