### ISSUE TITLE
Copy and paste?

### ISSUE THREAD

**Issue by AuthorOfTheSurf** [fish-shell/fish-shell#2029]
I am trying to copy text out of the shell e.g. program output. I can't figure out how to do this with fish, the documentation only mentions `Ctrl + K` which cuts from the command line prompt. I am used to using `Ctrl + Shift + C` and `Ctrl + Shift + P` to copy and paste in text bash. The paste hotkey works in fish, however copying doesn't.

**Comment by darker0n** [comment]
Try Command + C for copy and Command + C for paste

**Comment by darker0n** [comment]
Sorry Command + V for paste =)

**Comment by snnw** [comment]
If you have `xsel` installed, Ctrl+K and similar will set your X clipboard
with the killed text.

Cmd+C etc are handled by your terminal emulator, so that's not a fish
feature.

**Comment by ridiculousfish** [comment]
Control-shift-C copying is a feature of your terminal app, not your shell, so it should behave identically in fish and bash. I'm not sure what to suggest except "try again" :) In either case there's nothing fish can do here. Thanks for reporting this though.

**Comment by AuthorOfTheSurf** [comment]
> Cmd+C etc are handled by your terminal emulator, so that's not a fish
feature.

> Control-shift-C copying is a feature of your terminal app, not your shell, so it should behave identically in fish and bash. I'm not sure what to suggest except "try again" :) In either case there's nothing fish can do here. Thanks for reporting this though.

I just installed fish on my personal computer that is running the same OS as my work computer and `Ctrl`+`Shift`+`C` (and `V`) works in fish mode. So the good old try again was the solution. It really seemed like fish had changed the hotkey on me when I was at work on Friday. Thanks!
