### ISSUE TITLE
Rethink the way that nonexistant commands are handled and/or the way that fish disambiguates user input

### ISSUE THREAD

**Issue by RomanHargrave** [fish-shell/fish-shell#2031]
As it stands right now, the shell internally handles input by trying to determine if the provided input is a file, command, or directory. If it fails to determine what the input it, is passes it to a private function which figures out how to tell the user that something is wrong. This function, should it fail to see that the user attempted to do something which is possible in another shell will simply publish `fish_command_not_found` and then output an error message.

There are some scenarios where the user might want to suppress that error message if they are handling a specific type of input in a special way by means of listening to the `fish_command_not_found` event. To this end, I would suggest adding the following capabilities to the event system:
- `consume`, in order to halt the propagation of the specific event instance with regards to which the function was called
- priorities for the event handlers: this way, the 'not found' error message could be handled in pure fish-script by listening to the event with the lowest priority possible, meaning that it would never be printed if the event was consumed.

Alternatively, it might be interesting to think about how fish locates commands or functions. Perhaps it would be beneficial to allow for the user to extend this functionality either by means of shell scripting or native extensions to the shell runtime. This would allow for the user to provide a means by which they could implement handling of custom input forms other than hooking and consuming fish_command_not_found.

**Comment by ridiculousfish** [comment]
Very interesting. Any extension of how fish locates commands needs to support syntax highlighting and `type`. That means that the mechanism ought to be declarative, i.e. fish needs to be able to determine if a command will be recognized without actually running it.

**Comment by RomanHargrave** [comment]
Perhaps this could be accomplished in a similar fashion to `complete`, where the name of a function may be passed to the command which will then be called later?

**Comment by faho** [comment]
Okay, I don't want functionality to suppress command-not-found events (also that event doesn't exist anymore).

Just check if a command exists before using it.

Closing, sorry!
