### ISSUE TITLE
Fish incorrectly inserts escape characters when pressing tab

### ISSUE THREAD

**Issue by ericgorr** [fish-shell/fish-shell#2032]
I am using:
    ~> fish --version
    fish, version 2.1.2

on OS X 10.10.3.

I downloaded the Yosemite Installer Application because I wanted to run the createinstallmedia. So, from the command line I type:

    sudo /Applications/In

And then press tab. This results in:

    sudo /Applications/Install\ OS\ X\ Yosemite.app/

Then I type: 

    C

and press tab. This results in:

    sudo /Applications/Install\\\ OS\\\ X\\\ Yosemite.app/Contents/

So, as you can see it inserted unneeded '\' characters which prevents additional path string matching.

**Comment by RomanHargrave** [comment]
Interesting. I'm not having this issue oh HEAD using linux.

**Comment by ridiculousfish** [comment]
This was fixed as #1127. Thanks for reporting this.
