### ISSUE TITLE
type -a doesn't work

### ISSUE THREAD

**Issue by spinningarrow** [fish-shell/fish-shell#2033]
Using fish 2.1.2 on OSX, this is what I get when I run `type -a vim`:

    vim is /usr/local/bin/vim

The same thing in bash gives

    vim is /usr/local/bin/vim
    vim is /usr/bin/vim

Additionally, `type --all vim` in fish gives:

    getopt: illegal option -- -
    getopt: illegal option -- l
    getopt: illegal option -- l

Not sure what's going wrong here.

**Comment by ridiculousfish** [comment]
This has been fixed in trunk as 16e50c25, as part of #1540. Thanks for reporting this.

**Comment by spinningarrow** [comment]
Ah, my bad. I tried searching the issues but I was looking for `type -a` specifically so that one didn't turn up.

That commit seems to be a long time ago though, how come it's not working for me in fish 2.1.2?

**Comment by ridiculousfish** [comment]
Because we haven't had a release in a long time :confounded:

**Comment by spinningarrow** [comment]
Wasn't 2.1.2 in Feb this year? The commit you pointed to for the fix is from July last year (sorry for the bother - just checking). If there's anything a noob shellscripter can help with, do let me know!

**Comment by ridiculousfish** [comment]
2.1.2 was off the 2.1.1 branch, and had only a handful of highly targeted fixes.
