### ISSUE TITLE
Slight color consistency improvement in Classic + Git prompt

### ISSUE THREAD

**Issue by daytonb** [fish-shell/fish-shell#2034]
The opening parenthesis surrounding the git branch information is the color of the directory path rather than reset to normal.
![classic git](https://cloud.githubusercontent.com/assets/5454627/7235489/86ab2506-e75c-11e4-8b22-45b20b0c1bd3.png)

This can be fixed by simply adding `"$__fish_prompt_normal` between `"$__fish_prompt_cwd" (prompt_pwd)` and `(__fish_git_prompt)`.
![classic git-better](https://cloud.githubusercontent.com/assets/5454627/7235499/8e2883c8-e75c-11e4-8d05-98467b366ec0.png)

**Comment by ridiculousfish** [comment]
Easy fix. Thanks for reporting this!

**Comment by pickfire** [comment]
How do you get that **brown** master? Is it a default? I only get green.

![2015-07-07-184636_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/8544610/415f6326-24d9-11e5-9791-4b574aba2db1.png)
