### ISSUE TITLE
test -n not working as expected

### ISSUE THREAD

**Issue by EricG-Personal** [fish-shell/fish-shell#2037]
I have the following block:

``` fish
if begin; test -n $SSH_CLIENT; or test -n $SSH_TTY; end
echo "ssh (0)"
else
echo "not ssh (0)"
end
```

If I am correct, it should only print "ssh" if either of the environment variables `$SSH_CLIENT` of `$SSH_TTY` are defined. To verify that neither are defined:

```
   eric@ubuntu ~> printenv | grep SSH
   SSH_AUTH_SOCK=/run/user/1000/keyring-bKvxzV/ssh
```

and yet the output I get is "ssh". If I reverse the code block and do:

``` fish
if begin; test -z $SSH_CLIENT; and test -z $SSH_TTY; end
echo "not ssh (1)"
else
echo "ssh (1)"
end
```

It works as expected. 

So, running these two blocks where neither `$SSH_CLIENT` of `$SSH_TTY`are defined, the output I get is:

```
ssh (0)
not ssh (1)
```

and running these two blocks where both $SSH_CLIENT of $SSH_TTY are defined, the output I get is:

```
ssh (0)
ssh (1)
```

The -n flag does not work. The -z flag does.

```
> fish --version
fish, version 2.1.1

> uname -a
Linux ubuntu 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ridiculousfish** [comment]
I thought we had a bug on this somewhere, but I can't find it. Anyways see [my StackOverflow answer](http://stackoverflow.com/questions/23227590/test-command-difference-between-n-and-z/23233524#23233524) for this question.

The short summary is that if `$SSH_CLIENT` is not set, then `test -n $SSH_CLIENT` is equivalent to `test -n`, and POSIX requires that we just check if that one argument (the `-n`) is not null. You can fix it by quoting, which forces an argument even if it's empty:

    if begin; "test -n $SSH_CLIENT"; or test -n "$SSH_TTY"; end

Or maybe a little simpler:

    if test -n "$SSH_CLIENT" -o -n "$SSH_TTY"

This screws people up enough that we might want to break from POSIX here. If you like, I can leave this open to track that.

**Comment by MrLinear** [comment]
No, I would suggest sticking with POSIX. What may be a good solution here is to simply add some additional examples to the documentation to make this problem and solution easier to spot.

**Comment by zanchey** [comment]
I think the better documentation was added as part of #1574 (which is not in a release yet).

**Comment by brandonweiss** [comment]
*facepalm*

This has been driving me nuts for the last several days. Let's say I have a function that tests whether or not I'm inside a git repository.

```
function _in_git_directory
  if test -n (git rev-parse --git-dir ^ /dev/null)
    true
  else
    false
  end
end
```

I'm guessing the reason this doesn't work is because the command substitution returns nothing? So `test -n` is always true? What's the correct way to write this?

**Comment by ridiculousfish** [comment]
This should do it:

    function _in_git_directory
        if test (git rev-parse --git-dir ^ /dev/null)
                true
            else
                false
        end
    end

But really you don't need the `if` at all:

   function _in_git_directory
        git rev-parse --git-dir ^ /dev/null
    end

since the exit status suffices.

**Comment by brandonweiss** [comment]
Interesting! I was way over-complicating it. I think the second case will only work for me if I redirect everything to `/dev/null`.

`git rev-parse --abbrev-ref @"{u}" > /dev/null 2>&1`

Otherwise the output that was previously being capture by the command substitution is sent to stdout.

**Comment by bucaran** [comment]
To sum things up:

```
test -n
echo $status
0
```

But perhaps, it should return 1? I fail to see why breaking POSIX in this scenario would pose a problem since fish is not POSIX, but that is slightly beyond my area so I hope someone with more to say about it can contribute there.

**Comment by ridiculousfish** [comment]
Certainly nobody here is in love with POSIX :)

Nobody runs `test -n` by itself. They either run `test -n $someEmptyVariable` or `test $someVariableThatIsDashN`. We might want to distinguish those.

**Comment by bucaran** [comment]
Nobody runs `test -n`, but there are cases in which you can run into this:

```fish
test -n (EXPRESSION)
```

Sure, you can work around it like this `test -n (EXPRESSION; or echo "")`, but I would rather not have to work around it.

**Comment by ridiculousfish** [comment]
Right, so one possibility is that we teach `test` about empty expansions.

**Comment by bucaran** [comment]
> Right, so one possibility is that we teach test about empty expansions.

This would be nice. But it should not break the following hack:

```fish
echo (true; and echo abc)/ 
# abc/
echo (true; or echo)/
#
```

**Comment by GReagle** [comment]
If you're writing in fish, why not do it the better fish way?

    if begin; set -q SSH_CLIENT; or set -q SSH_TTY; end

**Comment by faho** [comment]
Because it can still be empty, even if it is defined. `set SSH_CLIENT; set -q SSH_CLIENT; and count $SSH_CLIENT` - though, as we see here, count can be used instead.

**Comment by eugenesvk** [comment]
@ridiculousfish nice that I found your solution with quoting variables and thanks @bucaran for your solution for expressions. Thanks!
But that's quite a non-intuitive solution. I'm all up for breaking from POSIX to fix it.

**Comment by GReagle** [comment]
@faho Thank you for pointing out the problem with using set -q.

@MrLinear When I run ```man test``` the example does use quotes.  I have fish  2.2.0-1~trusty installed.

I also think that fish's test should comply with POSIX.  If fish wants to have a command like test that behaves differently, that is fine, but it should have a different name.

**Comment by faho** [comment]
>I also think that fish's test should comply with POSIX. If fish wants to have a command like test that behaves differently, that is fine, but it should have a different name.

I agree that usually language features that look like POSIX should act like POSIX. HOWEVER, I think we might have an exception here. The reason is that currently `test -n $var` is currently:

- True when $var is non-empty

- False when $var is set to empty (i.e. `set var ""`)

- True when $var is unset or has zero elements (i.e. `set -e var` or `set var`)

This is ridiculous and has no use that I can see - if you wish to use a variable when it contains something, then you don't want to use it when it contains nothing - no matter which kind of nothing that is.

Of course when you get into actual lists with more than one element, you'll also see more need for quoting (`set var a b; test -n $var` will complain about an unexpected argument).

Note that this applies to all test operators, not just "-n", with the exception of "-z" - `test -p; and test -d` is actually true, meaning that test claims the file with the empty name (which can't actually exist in UNIX AFAIK) is a named pipe and directory at the same time.

Of course if someone can tell me what this is actually useful for I might reconsider my opinion, but as I see it now this just seems like hilariously broken behavior that probably was a result of taking a shortcut when writing a parser.

Also note that we currently have 32 `test` invocations in share/ that might hit this (`grep '\btest -[^z] \(\$\w\)' -r share/`). (They probably don't since the condition is impossible for some other reason)

**Comment by krader1961** [comment]
Those arguing for POSIX compliance need to keep in mind that many standards do little more than codify existing implementations. Including their warts. Sometimes the right thing to do is be "bug for bug compatible." However, in this case I'm inclined to agree with @faho's analysis and implement saner behavior. Especially in light of the fact that fish already deviates from POSIX in several more significant ways.

**Comment by GReagle** [comment]
Why the different result: `set SSH_CLIENT; count $SSH_CLIENT` produces 0 but `set SSH_CLIENT ""; count $SSH_CLIENT` produces 1?

Does this (more specifically the statement above that produces 1) contradict @ridiculousfish assertion in http://stackoverflow.com/questions/23227590/test-command-difference-between-n-and-z/23233524#23233524?
> In fish, if you want to check if a string is non-empty, you can use count

**Comment by GReagle** [comment]
There is another reason to (always) quote a variable with `test` besides the screwy POSIX behavior illustrated by the original poster's code example:  an unquoted variable that happens to be an array will cause an error.  Try this to see the error 
`set SSH_CLIENT a b c; if test -n $SSH_CLIENT; echo ssh; end`

**Comment by anordal** [comment]
> features that look like POSIX should act like POSIX

> This is ridiculous and has no use that I can see

Sounds to me like a dilemma, and the safest fix is to remove the feature!

I get the impression that `-n` and `-z` are easy to use wrong, and that people would be better off using `test "$var" != ''` and `test "$var" = ''` instead. Code would be ~~more~~ readable too.

**Comment by GReagle** [comment]
@anordal:  `=` and `!=` have the same problem as `-n` and `-z`: they require the variable to be quoted to ensure a reliably correct result.  If the variable is not quoted, they fail with error if the variable is either unset or an array:
```
set SSH_CLIENT a b c; if test $SSH_CLIENT != ''; echo ssh; end
set -e SSH_CLIENT; if test $SSH_CLIENT != ''; echo ssh; end
```

**Comment by anordal** [comment]
@GReagle: Sorry, I actually knew that, but didn't think of it as a problem — it works with quotes anyway. AFAIK, every variable in fish is an array.

Maybe it's just me, but I've always thought that `-n` and `-z` were fraught with peril, and been too scared to ever use them.

**Comment by floam** [comment]
> @faho, @krader1961: Sounds to me like a dilemma, and that the safest fix is to remove the feature!

Well, 👎 from me.

By removing the one-argument case of `test` we'd break stuff. The single argument case is useful, for example a solution given above by @ridiculousfish with command substitution:

`if test (git rev-parse --git-dir ^ /dev/null)`

Trying something like that would be harder with `-n`.

`test` really should not depart from POSIX in this core behavior.

**Comment by floam** [comment]
We need to document the precise behavior `test` has with 1 argument, 2 arguments, 3 arguments, 4 arguments, because it's not exactly clear from our man-page and that's not helpful. Like this does:

http://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html

**Comment by faho** [comment]
>The single argument case is useful, for example a solution given above by @ridiculousfish with command substitution:

@floam: If this misbehavior wasn't in there, that wouldn't have to use the single-argument! (Also it's broken if the command substitution ever returns more than one argument)

-------

So, the alternatives here are:

- Make `test` deviate by not doing automatic "-n", both for the single-argument and argument-after-combiner cases (`test something -a somethingelse`).

- Implement an improvement on `test`, but probably keep `test` around.

To be frank: `test` is pretty crappy no matter what we do. The combiners interact poorly with lists and command substitutions, the operators are weirdly spelt, it's got two names (`test` and `[ ]`)...

If we removed this piece of behavior, we'd lose some more compatibility (though it's pretty uncommon to write `test something`), and it wouldn't be backwards-compatible. But it might still be worth it.

**Comment by GReagle** [comment]
@EricG-Personal  and  @faho 

The original post has "if either of the environment variables $SSH_CLIENT of $SSH_TTY are **defined**".  So my reply of 
```
if begin; set -q SSH_CLIENT; or set -q SSH_TTY; end
```
 is a correct and fine way to determine whether either variable is **defined**, right?  Yes I know that defined could be empty.

To consider the question of how to check whether either of two variables is **not empty**, here is my attempt to do so without using the test command.  Is it correct?  Is there a better way without using test?
```
if begin; string length -q -- $SSH_CLIENT; or string length -q -- $SSH_TTY; end
    echo "not empty"
end
```

**Comment by Darkshadow2** [comment]
That works, but you can also use `set -q SSH_CLIENT[1]; or set -q SSH_TTY[1]`. The only time those will pass unexpectedly is if they are specifically set to an empty string (like this: `set SSH_CLIENT ""`). Otherwise, if they're defined but have no value, it will fail.

**Comment by faho** [comment]
@GReagle 

>is a correct and fine way to determine whether either variable is defined, right? Yes I know that defined could be empty.

Yes. (Also since 2.3.0 you don't need the `begin` and `end` here anymore - `and` and `or` bind to the if-condition)

> either of two variables is not empty

>string length -q -- $SSH_CLIENT; or string length -q -- $SSH_TTY

`string length` returns true if any of its arguments is not empty, so this can just be `string length -q -- $SSH_CLIENT $SSH_TTY`.

**Comment by GReagle** [comment]
Thank you @faho for improving the code and my understanding of fish.  I suggest we add to the FAQ then, what do you think?

Q: How do I check whether a variable is defined?

Use `set -q var`.  For example, `if set -q var; echo defined; end`.  To check multiple variables you can combine with `and` and `or` like so, `if set -q var1; or set -q var2; echo either defined; end`

Keep in mind that a defined variabled could be empty.  Both of these commands define an empty variable:  `set var` and `set var ""`.

Q: How do I check whether a variable is not empty?

Use `string length -q -- $var`.  For example, `if string length -q -- $var; echo not empty; end`.  Note that `string length` will interpret a list of multiple variables as a disjunction (meaning any/or).
```
if string length -q -- $var1 $var2 $var3
    echo at least one of these variables is not empty
end
```
