### ISSUE TITLE
Insecure history permissions

### ISSUE THREAD

**Issue by zer0rest** [fish-shell/fish-shell#2041]
Fish creates the ```fish_history``` file with ```644``` permissions, this deviates from both ```bash``` and ```zsh``` as they create it with ```600``` permissions.

Is this intended?

**Comment by ridiculousfish** [comment]
Nope, let's fix it. Good catch.

**Comment by zanchey** [comment]
Presumably fish relies on umask being set to something sensible, which is a brave assumption.

**Comment by ridiculousfish** [comment]
Trivial fix. Thanks for reporting this!
