### ISSUE TITLE
Clearing the screen (Ctrl-L) shouldn't lose "browsing history mode"

### ISSUE THREAD

**Issue by frangio** [fish-shell/fish-shell#2044]
(I'm sorry, I couldn't figure out a better title.)

If I'm browsing command history (via up/down arrows) and I press Ctrl-L to clear the screen, I would expect to be able to continue going up or down in history, but I can't because fish thinks I want to search for commands matching what is shown on the command line.

For a concrete example, say I'm going up in history and get to a `make` command. If I press `Ctrl-L` at this point, and then press `Up`, fish will only search for commands that match `make`.

I believe this is incorrect behaviour since `Ctrl-L` doesn't actually modify the current command.

**Comment by zanchey** [comment]
I can reproduce this in both 2.1.1 and the current master branch.

**Comment by ridiculousfish** [comment]
Thanks for reporting this!
