### ISSUE TITLE
No ARM build available on Ubuntu PPA

### ISSUE THREAD

**Issue by SeriousM** [fish-shell/fish-shell#2045]
Hi, when installing fish over apt-get as described below I only get version 2.0.0, even there is a higher version available ([2.1.1](https://launchpad.net/~fish-shell/+archive/ubuntu/release-2)).

```
$ sudo apt-add-repository ppa:fish-shell/release-2
$ sudo apt-get update
$ sudo apt-get upgrade
$ sudo apt-get install fish
$ chsh -s /usr/bin/fish
$ fish -v
> fish, version 2.0.0
```

my system:
```
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.2 LTS
Release:        14.04
Codename:       trusty
```

Do I do something wrong?

**Comment by zanchey** [comment]
Could you show the output of `apt-cache policy fish`?

**Comment by SeriousM** [comment]
Oh, sure!
an apt-get update was done before that.

```
fish:
  Installed: 2.0.0-1
  Candidate: 2.0.0-1
  Version table:
 *** 2.0.0-1 0
        500 http://ports.ubuntu.com/ubuntu-ports/ trusty/universe armhf Packages
        100 /var/lib/dpkg/status
```

**Comment by zanchey** [comment]
The PPA doesn't support your architecture yet, unfortunately - [the packages are only built for x86 & amd64](https://help.launchpad.net/Packaging/PPA#Supported_architectures).

I'll submit a request as I think we meet the [requirements](https://dev.launchpad.net/CommunityARMBuilds) to have ARM added to the release builds, although unfortunately not the nightlies.

**Comment by SeriousM** [comment]
I'm pretty new to the whole ARM topic, just bought a banana pro and start facing the first problems, eg NodeJs for ARM is not officially supported.

Anyway, thank you very much for your help! I don't need the nightly, just the stable if they are newer than the good old 2.0.0 :)

Btw, fish (2.0.0) is running very well on ARM.
I was even able to build the latest version for ARM, but fish_config was not launching a webserver (just the html file was generated) and I moved back to the stable version (2.0.0) where it was working again.

**Comment by SeriousM** [comment]
hi! are there any news or updates on this topic?

**Comment by zanchey** [comment]
They've been [turned on for release builds](https://answers.launchpad.net/launchpad/+question/266140) but old packages won't be rebuilt. We're hoping to release 2.2.0 in the next few weeks so that will come with ARM builds!

**Comment by SeriousM** [comment]
Thank you for the update.
Do you have an ETA for the next release? Would love to use the latest and greatest version :)

**Comment by zanchey** [comment]
Not yet, but if you'd like to test the beta we'd appreciate the feedback! If you're happy to do the build on your Banana Pro (will take a while), you can try something like:

```
mkdir ~/fish_build; cd ~/fish_build
sudo apt-get install build-essential ncurses-dev libncurses5-dev gettext
dget --build --allow-unauthenticated https://launchpad.net/~fish-shell/+archive/ubuntu/beta-2/+files/fish_2.2b1-1%7Etrusty.dsc
sudo dpkg -i fish_2.2b1-1~trusty_armhf.deb
```

Then you should be running 2.2beta1.

**Comment by zanchey** [comment]
fish 2.2.0 has been uploaded to the PPA and [ARM packages have been built successfully](https://launchpadlibrarian.net/211456080/buildlog_ubuntu-wily-armhf.fish_2.2.0-1~wily_BUILDING.txt.gz). I'd be grateful if you could test and let us know how it goes! I'll close this issue for now.
