### ISSUE TITLE
deleted exported universal variable still listed by env command

### ISSUE THREAD

**Issue by databus23** [fish-shell/fish-shell#2046]
I just noticed that the `env` command keeps listing deleted universal variables that where also exported in the current shell that deleted the variable.
In all other shells it works as expected.

Steps to reproduce:

    > set -Ux UNIVERSAL_TEST foo
    > echo $UNIVERSAL_TEST
    foo
    > set -Uex UNIVERSAL_TEST
    > echo $UNIVERSAL_TEST
    
    > env |grep UNIVERSAL_TEST
    UNIVERSAL_TEST=foo

**Comment by zanchey** [comment]
Whee! This is a regression since 2.1.1.

**Comment by ridiculousfish** [comment]
Phew, nice find!
