### ISSUE TITLE
Allow set_color to set true colors

### ISSUE THREAD

**Issue by Soares** [fish-shell/fish-shell#2047]
I use a terminal emulator that has true color support, and I'd like to be able to use true color in my various `$fish_color_*` variables.

Trouble is, the `set_color` builtin only recognizes eight or sixteen colors or whatever as valid.

I can work around the `set_color` limitation in (e.g.) my prompt by just using  `set -g __prompt_whatever_color = (echo -e \x1b[38;2;RRR;GGG;BBBm)`, but I can't just use the ANSI escape codes with the `$fish_color` variables directly because they go through `set_color`.

It would be really nice if I could say `set_color #rrggbb` and have it translate it into the appropriate `\x1b[38;2;XXX;XXX;XXXm` code, but that might get a little hairy as it's not clear what to do in that case for terminals that don't support true color encoding. A quickfix that would suffice is some alternative to the `$fish_color_*` variables that lets me set the ANSI escape codes directly, instead of specifying parameters to the (limited) `set_color` builtin.

**Comment by ridiculousfish** [comment]
This went in as b8181f9eb8018e7a5a8d3776d2269e64ebbcf1f1, though you have to set the variable `fish_term24bit` to 1 to enable it. RGB support is available via `set_color RRGGBB`. (The hash is optional, but if you use it you have to remember to escape it.) For terminals that don't support it, we pick the "closest" supported color. Let me know if it doesn't work for you!

**Comment by Soares** [comment]
Works like a charm. Nice work! I am impressed, I didn't expect that to already exist :-D

**Comment by ridiculousfish** [comment]
Hooray!
