### ISSUE TITLE
Errors for % substitution cannot be suppressed

### ISSUE THREAD

**Issue by tannhuber** [fish-shell/fish-shell#2049]
I'm using `%fish` in my prompt, even in a sudo shell. However,
```
sudo -i
echo %fish
```
results in
```
Unable to find a process 'fish'
fish: echo %fish
            ^
```
. What's going wrong here?

**Comment by ridiculousfish** [comment]
What operating system are you using?

**Comment by tannhuber** [comment]
Linux Mint, `uname -a` says:
```
Linux mypc 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```
The point is that `echo %fish` works fine if I'm not in a `sudo` environment.

**Comment by tannhuber** [comment]
By the way, `echo %self` is okay in a `sudo` environment as well.

**Comment by ridiculousfish** [comment]
Probably it's being run as a login shell, which means that the process name is `-fish` instead of `fish`.

**Comment by tannhuber** [comment]
You're right. I didn't know that there's a different process name in case it is a login shell.

Thank you, can be closed.

**Comment by ridiculousfish** [comment]
Cool, thanks for filing this.

**Comment by tannhuber** [comment]
Nevertheless, there's still a problem with a function in my `fish_prompt.fish` related to this issue. So I'd like to reopen it. That's the function:
```
function __budspencer_delete_zombi_sessions -d 'Delete zombi sessions'
  for i in $budspencer_sessions_active_pid
    if not contains $i %fish
      set -l item (contains -i $i $budspencer_sessions_active_pid)
      set -e budspencer_sessions_active_pid[$item]
      set -e budspencer_sessions_active[$item]
    end 
  end 
end
```
In a login shell it would result in an error message. I thought, I could make two checks, one with `%fish` and another one with `%-fish`. But it seems there's no chance to suppress the error messages due to https://github.com/fish-shell/fish-shell/issues/1674. As a result, my prompt always shows an ugly error message if the function above is called. It's not critical, but very ugly. If anybody has an idea how to solve it, please tell me!

**Comment by ridiculousfish** [comment]
Probably we should rework things so that all non-syntactic error messages respect redirections, instead of going directly to stderr.

**Comment by tannhuber** [comment]
Is there any reason why it's implemented this way? I cannot see a benefit. And in zsh, bash, dash, ksh it's also possible to redirect these messages. I would appreciate the same behaviour in fish.

**Comment by ridiculousfish** [comment]
I agree. I can't justify the current behavior. It's been this way since fish 1.x however.

**Comment by tannhuber** [comment]
Okay, good to know that it is on the todo list. Thank you.

**Comment by faho** [comment]
Renaming this to better reflect what needs to be done.

**Comment by zanchey** [comment]
I think we should track in #1674, so I'll close this as a duplicate for now.
