### ISSUE TITLE
Migration path for abbreviations

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#2051]
In fish 2.1, the abbreviation syntax 'word=phrase' was introduced. In 2.2 this was changed to simply 'word phrase' but the old syntax was still supported internally.

This issue tracks removing the old syntax for the next release after 2.2 - either disabling it and making a note in the release notes, or (silently?) upgrading existing `fish_user_abbreviations` variables.

**Comment by faho** [comment]
Do we want to act on this for the next release?

I'd be in favor of silently upgrading and can whip something up.

**Comment by ridiculousfish** [comment]
Sounds good to me

**Comment by krader1961** [comment]
This would be a good time to update the man page and add a paragraph about deprecating the old key=val syntax.

**Comment by zanchey** [comment]
Yikes, I didn't realise the documentation still mentioned the old syntax.
