### ISSUE TITLE
file names with '-' at the beginning cause issues with globbing.

### ISSUE THREAD

**Issue by roboknight** [fish-shell/fish-shell#2053]
This could be a problem in other shells as well, but what happens in fish is as follows:

In a directory create a file, using a visual tool like nautilus or some other tool, named something like:
 -this.txt

In that directory try to execute the following:
ls *

ls will fail because it assumes it has -t as a parameter.  

Naturally, all programs pretty much seem to have a issue here.  It does seem that I noticed that files could be named "./-this.txt", for example, to remove the file or rename it, but it still effects things like rm * and ls *.

Normally I don't have files named starting with a dash, but it can happen if a tool auto generates a name and the beginning ends up being null or probably even a space.

**Comment by ridiculousfish** [comment]
This is tracked in #1519. Thanks for reporting this.

**Comment by roboknight** [comment]
That’s the problem I find with bug trackers… There really isn’t a good way to search through them to find what you are looking for.  I believe I tried “globbing” or something like that, and found nothing… I need the “you know what I meant” interface for things…

Glad its been reported.  Sorry it hasn’t been fixed due to the other issue.  I don’t know what you have in the works, but I’m ready to give it a pull… especially when programs create filenames because they got no output from some operation.

**Comment by ridiculousfish** [comment]
Yeah, someone someday will write a really good bug tracker.

Regarding that issue, I took a crack at it a while back, did not succeed, and so reverted. If you want to try you're more than welcome!
