### ISSUE TITLE
Using fish functions under sudo

### ISSUE THREAD

**Issue by amosbird** [fish-shell/fish-shell#2054]
Is it possible to use fish functions under sudo while root shell is bash? How can I change sudo shell without modifying root account?

**Comment by ridiculousfish** [comment]
sudo runs external commands, so you cannot use sudo to run a fish function directly. Instead you can use sudo within the function. You can run fish under sudo with `sudo fish`. Does that answer your question?

**Comment by zanchey** [comment]
If your `$SHELL` environment variable is set to the path to fish, then you can use the `-s` flag to sudo:

```
> getent passwd root
root:x:0:0:root:/root:/bin/bash
> echo $SHELL
/usr/bin/fish
> sudo fish_prompt
sudo: fish_prompt: command not found
> sudo -s fish_prompt
root@motsugo /h/w/z # 
```

**Comment by amosbird** [comment]
@zanchey thanks!

**Comment by bucaran** [comment]
@ridiculousfish That makes sense, but what if you are running `sudo make target` and there is something like `fish -c "foo"` in `target`? That will cause `fish` to fail 

```
fish: Unknown command 'foo'
```

**Comment by shilangyu** [comment]
> If your `$SHELL` environment variable is set to the path to fish, then you can use the `-s` flag to sudo:
> 
> ```
> > getent passwd root
> root:x:0:0:root:/root:/bin/bash
> > echo $SHELL
> /usr/bin/fish
> > sudo fish_prompt
> sudo: fish_prompt: command not found
> > sudo -s fish_prompt
> root@motsugo /h/w/z # 
> ```

This works fine for fish-defined functions, however for my functions (defined in `~/.config/fish/config.fish`) it doesnt.
I think it might be unrelated to the sudo problem though because running `fish -c functions` doesnt list my functions either (they do work in interactive)
