### ISSUE TITLE
Reset completions containing sensitive data

### ISSUE THREAD

**Issue by sebastianmarkow** [fish-shell/fish-shell#2055]
Is there a way to reset all completions like with history `history -d` in the case of containing sensitive data?

I already tried killing fishd, removing cache files and close/start a new session, with no luck.

**Comment by ridiculousfish** [comment]
Autosuggestions are taken from your history and are not stored separately. So if you delete them from history they will no longer be suggested.

**Comment by sebastianmarkow** [comment]
Sorry @ridiculousfish, I did miss the fact that fish history is using `--clear` instead of `-d`.
Maybe history should print an error upon an illegal flag in addition to exit 1. 

Thanks.

**Comment by ridiculousfish** [comment]
Thanks. Do you want to use this to track making `history` do better error reporting?

**Comment by zanchey** [comment]
`builtin history -d` works, and `builtin history -X` prints a warning, but it's the history wrapper function that's tripping us up here.
