### ISSUE TITLE
configure script does not see ncurses staged in nonstandard location

### ISSUE THREAD

**Issue by kotoroshinoto** [fish-shell/fish-shell#2056]
ncurses is staged like so: ls /UCHC/HPC/Gooch/biotoolmodules/ncurses/5.9
bin  include  lib  share

I have used http://modules.sourceforge.net/ to set up the environment so that ncurses files SHOULD be visible to the configure script and any compilers.
for instance: echo $C_INCLUDE_PATH
/UCHC/HPC/Gooch/biotoolmodules/oraclejava/jdk1.8.0_45/include:/UCHC/HPC/Gooch/biotoolmodules/ncurses/5.9/include:/UCHC/HPC/Gooch/biotoolmodules/mpc/1.0.3/include:/UCHC/HPC/Gooch/biotoolmodules/isl/0.14.1/include:/UCHC/HPC/Gooch/biotoolmodules/gcc/5.1.0/include:/UCHC/HPC/Gooch/biotoolmodules/cloog/0.18.3/include:/UCHC/HPC/Gooch/biotoolmodules/mpfr/3.1.2/include:/UCHC/HPC/Gooch/biotoolmodules/libtool/2.4.6/include:/UCHC/HPC/Gooch/biotoolmodules/gnu-make/4.1/include:/UCHC/HPC/Gooch/biotoolmodules/gmp/6.0.0/include:/UCHC/HPC/Gooch/biotoolmodules/flex/2.5.39/include:/UCHC/HPC/Gooch/biotoolmodules/binutils/2.25/include

ncurses is there. there is an ncurses subdirectory in that include directory containing its header files

and yet the configure script fails with this message:

checking for library containing setupterm... no
configure: error: Could not find a curses implementation, needed to build fish. If this is Linux, try running 'sudo apt-get install libncurses5-dev' or 'sudo yum install ncurses-devel'

**Comment by zanchey** [comment]
Have a look at `config.log` - it's a big file but you should be able to find "Could not find a curses implementation" and look above it.

My suspicion would be that either `CPLUS_INCLUDE_FILE` or `LIBRARY_PATH` is not set correctly.

**Comment by kotoroshinoto** [comment]
relevant lines were: 

configure:3784: g++ -o conftest -g -O2 -I/opt/include/ -I/usr/local/include/ -D_LARGEFILE_SOURCE=1 -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE=1 -D_ISO99_SOURCE=1   -L/usr/local/lib/ conftest.cpp -lcurses  -l$
/UCHC/HPC/Gooch/biotoolmodules/binutils/2.25/bin/ld: /tmp/ccpgSIWB.o: undefined reference to symbol 'setupterm'
/lib64/libtinfo.so.5: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
configure:3784: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "fish"
| #define PACKAGE_TARNAME "fish"
| #define PACKAGE_VERSION "2.1.2"
| #define PACKAGE_STRING "fish 2.1.2"
| #define PACKAGE_BUGREPORT "fish-users@lists.sf.net"
| #define PACKAGE_URL ""
| #define USE_GETTEXT 1
| #define HAVE__PROC_SELF_STAT 1
| #define HAVE_TRANSLATE_H 1
| /* end confdefs.h.  */
|
| /* Override any GCC internal prototype to avoid an error.
|    Use char because int might match the return type of a GCC
|    builtin and then its argument prototype would still apply.  */
| #ifdef __cplusplus
| extern "C"
| #endif
| char setupterm ();
| int
| main ()
| {
| return setupterm ();
|   ;
|   return 0;
| }
configure:3801: result: no
configure:3808: error: Could not find a curses implementation, needed to build fish. If this is Linux, try running 'sudo apt-get install libncurses5-dev' or 'sudo yum install ncurses-devel'

**Comment by kotoroshinoto** [comment]
no idea why it was trying to use libtinfo when i have ncurses, it does look like a path is out of place somewhere

**Comment by zanchey** [comment]
You might be getting bitten by #1185, which is fixed in the very-soon-to-be-released beta.

**Comment by kotoroshinoto** [comment]
LIBRARY_PATH is set correctly
CPLUS_INCLUDE_FILE might not be as it isn't set at all, though its not led me into problems at all with anything else

however the function that adds to C_INCLUDE_PATH also adds to CPLUS_INCLUDE_PATH

is CPLUS_INCLUDE_FILE different? or was that a typo?

**Comment by zanchey** [comment]
Sorry, I meant `CPLUS_INCLUDE_PATH`.

**Comment by kotoroshinoto** [comment]
it might be searching the system paths preemptively in a hardcoded manner instead of allowing the toolchain to figure it out. That other bug does appear like it might be relevant

**Comment by kotoroshinoto** [comment]
its also possible i'm not setting some other env-var related to ncurses, though I wouldn't know what that would be.

**Comment by kotoroshinoto** [comment]
oddly i dont see anywhere in that text that it ever includes anything for any curses library, how does it expect to find the library? 

is there a config option to tell it which curses library file to use during linking?

**Comment by ridiculousfish** [comment]
Pushing out of 2.2.0.

**Comment by zanchey** [comment]
@kotoroshinoto, could you try the recently-released 2.2beta1? http://fishshell.com/beta

**Comment by kotoroshinoto** [comment]
it completes the configure script without incident in that version. Will be compiling shortly and let you know how that goes.

**Comment by kotoroshinoto** [comment]
i'm able to load the shell, though to view help i need to go obtain lynx or htmlview

**Comment by zanchey** [comment]
Great - I'll close this for now then.
