### ISSUE TITLE
Consider a visual indicator for leading/trailing whitespace in filenames

### ISSUE THREAD

**Issue by wraithgar** [fish-shell/fish-shell#2057]
If a file exists with trailing or leading whitespace it is visually difficult to see, especially with trailing whitespace.  There are no visual indicators that the filename is anything other than the non-whitespace colors that show up in an `ls`

It would be helpful if there were some way that a person could see what the full filename was. Suggestions include a specific foreground color value for leading/trailing whitespace, or an 'encapsulate in quotes' policy for filenames that have leading or trailing whitespace.  I'm sure there are other ways to solve the problem besides those two suggestions also.

This feels like a real design problem that would be nice to have addressed and discussed.

**Comment by zanchey** [comment]
Whereabouts did you want to see the full filename? On the command line, if you have a file with trailing whitespace then tab-completion will insert a backslash escaping it; the same shows in the pager.

The output of `ls` might be harder to alter but certainly is worth thinking about.

**Comment by wraithgar** [comment]
Yes I was talking about the out put of `ls`.

To be vair, Fish already does a far better job than other shells thanks to the autosuggestive highlighting as you type.  As you can see here there is at least _some_ indication that the filename ends in whitespace:

![screen shot 2015-05-08 at 8 23 56 am](https://cloud.githubusercontent.com/assets/36607/7539403/9eca4bb4-f55b-11e4-9127-68373b515392.png)

Showing it in a general `ls` would be even more helpful, in my opinion. Thanks for taking the time to respond to and consider this issue.

**Comment by zanchey** [comment]
The autosuggestion appears for me even if I haven't typed the filename in, at least on 2.2b1 - what version are you running? The backslash also appears in the pager for completions.

**Comment by wraithgar** [comment]
I am on 2.1.2 and the typeahead/autosuggestion is a bit of a red herring, sorry for the distraction there.  I'm talking specifically about  the output of a bare `ls` command.  I've seen some auto-highlighters that do things like putting a white `.` with red background where there is a trailing space, for instance. Not to suggest that is the One True Way to visibly call out trailing whitespace, but more of an example of one I've seen elsewhere.

**Comment by ridiculousfish** [comment]
Messing with `ls` output is a little dangerous because it's common (though ill-advised) to use `ls` programmatically, e.g. `for filename in (ls)...`

I think this would be a great feature but it feels like it ought to be a feature of `ls`, not something that the shell tries to implement.

**Comment by GReagle** [comment]
ls -Q quotes filenames.
I don't see how this requests applies to fish.  It seems like a feaure request for ls.

**Comment by faho** [comment]
Yes, this really seems like something that should be in ls, so I'm closing this. If anyone disagrees with me, speak up.
