### ISSUE TITLE
fish_config busted in SnowLeopard Safari

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#2060]
fish_config is terribly broken looking in 10.6 Safari. The console shows some parse errors. We should fix this before 2.2.

**Comment by zanchey** [comment]
There are some possible hints at http://stackoverflow.com/questions/17035230/angular-js-breaks-in-safari-but-not-chrome

**Comment by ridiculousfish** [comment]
I tested with 5.0.5, but there's a newer version; let me check on that.

**Comment by ridiculousfish** [comment]
Looks ok with Safari 5.1.10, the latest on SnowLeopard. Closing as NTBF.
