### ISSUE TITLE
exec alias leaks process

### ISSUE THREAD

**Issue by drwilly** [fish-shell/fish-shell#2061]
In zsh I used to use an alias for exec
`alias x='exec'`

If I'm not mistaken, this would translate to the following fish function
```
function x
  eval exec $argv;
end
```

Using this function leaves a stopped but not reaped process that lingers unless you run kill -9 on it.
Might be related to #1362 but is independent of stdin.

**Comment by zanchey** [comment]
Could you tell us what version you are running and on which platform?

**Comment by drwilly** [comment]
Of course.
Version 2.1.1 on gentoo x86_64-pc-linux-gnu.

**Comment by ranisalt** [comment]
I'm not sure about this eval. I think you would just run `exec $argv` instead, since eval would get the output of `exec` and execute in fish script, but `exec` never returns since it replaces the process.

**Comment by drwilly** [comment]
Look, im new to fish myself, but what I can tell you is that `exec $argv` results in an error. As does `exec eval $argv`, `exec (eval $argv)` or just `exec (echo $argv)`, btw.
`eval exec $argv` on the other hand behaves as expected, save for the leaked process.

**Comment by ridiculousfish** [comment]
My guess is we're leaving stdin in a funny state.

**Comment by faho** [comment]
The error `exec $argv` prints for me is "Variables may not be used as commands".

**Comment by drwilly** [comment]
The following can be used as a  temporary workaround:
```
function x
	exec fish -c "exec $argv";
end
```
this also works in other cases where you want to execute the contents of a variable, e.g:
```
function e
	fish -c "exec $EDITOR $argv";
end
```

The original issue should be fixed regardless.

**Comment by krader1961** [comment]
While multiple issues were raised the core issue is the same as #154 so I'm closing this as a dup.
