### ISSUE TITLE
File completion on a non-existing directory breaks

### ISSUE THREAD

**Issue by ranisalt** [fish-shell/fish-shell#2063]
I know the title sounds a bit imbecile, but I have just had this problem. I was compiling some package and I entered a directory which was, on another terminal, deleted. Then I tried `ls`ing and `cd`ing from that terminal and fish has spit out a lot of text, and the message `The directory i_have_deleted does not exist` almost became hidden.

![Error](https://i.imgur.com/5Cbjhuw.png)

I feel that if fish detects the current directory does not exist anymore, only this message should be print, instead of failing to execute and printing more stuff that may panic someone. :package: 

Mind that fish has detected the current directory is not writable (by turning the prompt red), but it could also detect it is non-existant too.

**Comment by zanchey** [comment]
Cool dragon.

What version are you running?

A test could be added to stat the current directory first.

**Comment by ranisalt** [comment]
@zanchey I'm running fish 2.1.2, this version is packaged in Arch Linux testing repositories.

**Comment by zanchey** [comment]
I can reproduce this in 2.1.1 but not in 2.2b1.

**Comment by faho** [comment]
@ranisalt: Can you reproduce with 2.2.0 (the version packaged in the Arch Linux community repo now)?

**Comment by ranisalt** [comment]
@faho no, it is fixed now :)

![Imgur](http://i.imgur.com/7ivt5H4.png)

As you can see, fish refers to `.` as an non-existing folder now. Even `stat` is a little broken, as it should not work, but the fish issue is now working. Thanks guys!
