### ISSUE TITLE
Where fish saves universal environment variables when there's no fish.config file?

### ISSUE THREAD

**Issue by hevonen** [fish-shell/fish-shell#2065]
I don't have fish.config file in ~/.config/fish, but I still have set environment variables with "set -U -x something something" that persist between terminal relaunches. I just wonder where the stuff went, I did not find this in the documentation.

I'm on OSX Yosemite, fish -v is 2.0.GIT, installed with homebrew.

**Comment by ridiculousfish** [comment]
It should still be in `~/.config/fish`. Usually in `fishd.XXXXXXXXXXXX` where the Xs are your MAC address.

**Comment by hevonen** [comment]
Blushing.. I saw it but thought it was some temporary file for some fish daemon. Thanks!
