### ISSUE TITLE
Weird behavior with hamburger character

### ISSUE THREAD

**Issue by hdante** [fish-shell/fish-shell#2069]
Using symbols from the assorted symbols sections in unicode (like 🎂, 🍔, starting from U+1F300, etc.) causes erratic behavior in fish,

**Comment by ridiculousfish** [comment]
Can you please provide more details? What OS, terminal emulator, steps to reproduce? Thanks.

**Comment by faho** [comment]
I can reproduce some erratic behavior in KDE's konsole (version 15.04, with Qt 5.4.2, on currently up-to-date archlinux, fish 2.2.0). It actually is a bit hard to describe - the best I can come up with is that it causes suggestions to not be properly cleared, causing dead characters to appear in the prompt.

Okay, that's a lie. The best I can do is show a recording (my history already contains the offending character):

![hamburger](https://cloud.githubusercontent.com/assets/5185367/8678518/482c534a-2a55-11e5-8485-8b3664430c27.gif)

**Comment by pickfire** [comment]
I had a few of those problems once, I think it is related to locale. What is the output of `locale`?
Does other terminal have the same problem?
Does `bash` and `zsh` have this problem?

**Comment by faho** [comment]
locale

>LANG=de_DE.UTF-8
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=

Bash does not have this problem, I have not tested another terminal.

**Comment by ridiculousfish** [comment]
I expect bash to be less sensitive to widths since it doesn't try to keep track of cursor positioning. zsh does for features like RPROMPT, and I wouldn't be surprised if it had similar issues.

**Comment by zanchey** [comment]
I think this is probably the same as #2199 - I have a file named ☃ in my home directory (as in http://unicodesnowmanforyou.com/) and fish seems to get confused about where the cursor needs to be.

**Comment by ridiculousfish** [comment]
Nice catch. Let's track in #2199.
