### ISSUE TITLE
abbr --remove is inconsistent with other commands

### ISSUE THREAD

**Issue by nyobe** [fish-shell/fish-shell#2071]
Set, Bind, Functions, etc all use `-e or --erase` instead, `--remove` isn't used anywhere else.

**Comment by ridiculousfish** [comment]
Nice catch!

**Comment by zanchey** [comment]
I'd like to fix this for 2.2.0. I think we can change it without keeping the old syntax now, whereas if we leave it for the future then we are committed to aliasing them.

**Comment by ridiculousfish** [comment]
Sounds good

**Comment by zanchey** [comment]
Closed with c0cf25c.
