### ISSUE TITLE
Weird error in config.fish with 2.2b1?

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#2073]
codychan on HN [reports](https://news.ycombinator.com/item?id=9567806):

> After updating to v2.2b1 using instructions at https://launchpad.net/~fish-shell/+archive/ubuntu/beta-2, these occurs to me in my original conf.fish file

Config file here: [https://github.com/c02y/dotfiles/blob/master/fish/.config/fish/config.fish](https://github.com/c02y/dotfiles/blob/master/fish/.config/fish/config.fish).

**Comment by ridiculousfish** [comment]
I wasn't able to reproduce any problems on Ubuntu Trusty or OS X Yosemite. The error message posted on HN looks garbled - I wonder if line endings got mangled?

**Comment by c02y** [comment]
I already pushed my local conf.fish to Github, nothing wrong with v2.2b1 for Fedora21, the errors happens in Ubuntu 14.04, although the conf.fish in Ubuntu is a little different from it in Fedora, I'll try https://github.com/c02y/dotfiles/blob/master/fish/.config/fish/config.fish tomorrow.

**Comment by c02y** [comment]
After testing the config.fish in my Ubuntu in my company' and config.fish at the Github line by line, I finally  got the reason, I set:

    set -gx MANPAGER "less -s -M +Gg"

which should be (like the one at the Github link) 
    
    set -gx MANPAGER 'less -s -M +Gg'

the *""* will cause those weird error messages, sorry about this.

BTW, is there a better solution to test the config.fish if something went wrong instead of testing it line by line?

**Comment by zanchey** [comment]
I haven't been able to reproduce this with fish 2.2b1 on Debian 8.

You can use `fish --profile fish.trace` to produce a trace file which might help.

**Comment by ridiculousfish** [comment]
@c02y My guess is that one of the quotes is non-ASCII (U+201D or something) and so fish doesn't interpret it as a quote (some text editors likes to "educate quotes" which can cause that problem). It's also possible there's a nonprinting "gremlin" character in your config file which is confusing fish. Can you check if either of those is the case?

**Comment by zanchey** [comment]
The diff at https://github.com/c02y/dotfiles/commit/4e7da4ac60e27983b879d55a71333584a4a48690#diff-cb894d5c219bca4e922be20856f925cdL15 suggests not, but that might not be accurate.

**Comment by ridiculousfish** [comment]
I tried the dotfiles version, and wasn't able to make progress. Let's push. @c02y if you still have access to the bad `config.fish` file and can share it, we'd really appreciate it.

**Comment by faho** [comment]
@c02y: If you can still reproduce, please yell.
