### ISSUE TITLE
Incorrect path shown when `cd` tab completion can't suggest anything.

### ISSUE THREAD

**Issue by nkcmr** [fish-shell/fish-shell#2076]
Steps to reproduce:
- Attempt to tab-complete `cd` to ambiguous directory
- `cd` into a directory

Screencast:
https://cl.ly/1x2c3s073131 (no audio)

**Comment by Boudin** [comment]
It seems to me that your prompt is only showing the first letter of every parent directory of your current path (so that would not be a bug but just a feature of the theme your using).

**Comment by ridiculousfish** [comment]
Nice screencast :) Is the problem the prompt text as Boudin says?

**Comment by ridiculousfish** [comment]
I think this is just the behavior of the default prompt. Closing as behaves correctly - speak up if you disagree. Thanks for filing this :)
