### ISSUE TITLE
vim-mode Ctrl+C

### ISSUE THREAD

**Issue by rstacruz** [fish-shell/fish-shell#2077]
It seems Ctrl-C gets you out of normal mode. this is probably better mapped to cancelling the current command, as you would expect (this is zsh's behavior).

**Comment by rstacruz** [comment]
If anyone's interested, here's a workaround you can drop into `config.fish`.

```fish
# Vi mode, fixing ctrl-c to cancel the line instead of exiting insert mode
fish_vi_mode
function fish_vi_key_bindings_local
  fish_vi_key_bindings
  bind -e -M insert \cc
  bind -M insert -m insert \cc 'commandline ""'
end
set -g fish_key_bindings fish_vi_key_bindings_local
```

**Comment by zanchey** [comment]
bash and zsh both do this, so I'd like to take this for 2.2.0. @jaredgrubb implemented the current behaviour and might like to comment. @furunkel might also provide an opinion?

**Comment by jaredgrubb** [comment]
I agree that it should cancel the current command ... I thought originally it did, but as I try it now, it doesnt. +1 from me!

**Comment by rstacruz** [comment]
looking at fish's code, this is actually easy to do: just change the `\cc` binding in insert mode to 'commandline ""` in fish_vi_key_bindings :)

**Comment by zanchey** [comment]
Indeed; done as b6b6de3.

**Comment by mqudsi** [comment]
Forgive me if I'm mistaken, but this seems to be broken again in master? First ctrl+c now exits `insert` and then another is required to clear the current command.. and then an `i` is needed to go back to insert mode.

**Comment by krader1961** [comment]
Yeah, @faho, apparently inadvertently reverted it with commit c0e8ad6f on 2015-10-02 to "Make vi bindings inherit the defaults". A change that itself is contentious and still being debated :-) I'll fix it.

**Comment by krader1961** [comment]
Regression fixed via commit dfb23c4fce11d9d0577a2cb3c9e192bc24f64c8c.

**Comment by mqudsi** [comment]
@krader1961 Thank you most kindly.

For what it's worth - as a vim user that has been living without vi mode in fish for the past few years and finally enabled it on 2.2.0 today for the first time (previously just binding `meta+v` to `edit_cmd` in vim), I found fish to be unusable w/ the default vi key bindings in 2.2.0 and - thus far - behaving "as a normal user of fish and vim w/o previous zfs/bash vim-mode experience" would expect it to, this 'ctrl+c' binding issue a side.

**Comment by krader1961** [comment]
@mqudsi: The fish vi-mode support needs a lot of polishing. There's at least one open issue to that effect. Someone recently made a few changes that improved it a lot but there's still work to be done. Feel free to send us pull-requests and I'll personally test and merge them.

**Comment by mqudsi** [comment]
@krader1961 I actually went back and edited my comment as I realized it was incomplete. I meant to say that upgrading from 2.2.0 to today's master has greatly improved the usability. I'll be happy to contribute in any way I can and will make note of any "frustrations" I encounter. Thank you!
