### ISSUE TITLE
fish doesn`t work on mac osx

### ISSUE THREAD

**Issue by mailbaoer** [fish-shell/fish-shell#2078]
today I upgrade my mac to osx 10.10.3,then fish could not use anymore, when I open my terminal, there is nothing，and can not use，how can i solve this problem?

**Comment by ridiculousfish** [comment]
To get you back in action, go to Terminal->Preferences->Profiles, select your default profile in the left sidebar, click on the Shell tab, and set Run Command to `/bin/bash` and ensure Run inside shell is unchecked:

![screen shot 2015-05-19 at 10 13 14 am](https://cloud.githubusercontent.com/assets/920838/7709136/c8b886ea-fe0f-11e4-8e06-b7a9ced81c6c.png)

From there the simplest thing to do is reinstall fish. It's also possible that `/etc/shells` got overwritten, so edit that file to include the line `/usr/local/bin/fish`.

Let me know if any of that helps!

**Comment by mailbaoer** [comment]
sorry, I followed what you said,but it doesn`t work 
![image](https://cloud.githubusercontent.com/assets/5282978/7709375/39ea6bf6-fe8f-11e4-86e4-9d201f70c581.png)

**Comment by ridiculousfish** [comment]
Try invoking it as `fish -d 4` to get some debugging information.

**Comment by mailbaoer** [comment]
that`s my debugging info
![image](https://cloud.githubusercontent.com/assets/5282978/7709432/a002cb90-fe8f-11e4-8042-065f39fa9094.png)

**Comment by ridiculousfish** [comment]
Thanks. It looks like fishd is hung. You can try killing it:
    
    killall fishd

that may unstick you. Does that work?

Alternatively you can upgrade to the 2.2 beta which removes fishd entirely, so it can't cause any more problems. http://fishshell.com/beta/

**Comment by mailbaoer** [comment]
thank you very much, killall fishd doesn`t work, but beta is ok, thanks for your answering,:thumbsup:

**Comment by ridiculousfish** [comment]
Cool. Let's close then since this is fixed in master. Thanks for filing this!
