### ISSUE TITLE
Autocomplete character with right  arrow

### ISSUE THREAD

**Issue by tesfabpel** [fish-shell/fish-shell#2082]
Please add an option to autocomplete next character with the right arrow, instead of autocompleting the full line (which can be done with END).  
Thanks :)

**Comment by ridiculousfish** [comment]
Do I understand this correctly that you want to accept only one character from the autosuggestion? May I ask, what use case do you have in mind?

**Comment by tesfabpel** [comment]
For example, if you have a long commandline in history sometimes you may want to autocomplete the next word (with CTRL+Right arrow) and change the rest.

**Comment by jaredgrubb** [comment]
In vi-mode, you can hit Escape and then 'w' to complete the next word.. but I second the idea that I have often wanted an easier way to autocomplete a partial line.

**Comment by ridiculousfish** [comment]
You can use Alt-Right-Arrow to accept only the next word from the autosuggestion, and you can rebind this if you want (via the `forward-word` binding). Is that what you're looking for?

**Comment by tesfabpel** [comment]
Ok, thanks. :)
