### ISSUE TITLE
Missing output messages

### ISSUE THREAD

**Issue by m0n9oose** [fish-shell/fish-shell#2084]
Today i've noticed that my shell much more silent than usual.

bash:
```
macbook:registration m0n9oose$ git ps
fatal: The current branch new_registration has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin new_registration

macbook:registration m0n9oose$
```

fish:
```
m0n9oose@macbook ~/d/registration> git ps
m0n9oose@macbook ~/d/registration>
```

And other programs have same problem. How can i fix it?

Mac OS X 10.10.3
iTerm2 Build 2.1.1
fish: stable 2.1.2 (bottled), HEAD

**Comment by ridiculousfish** [comment]
Yikes! I'm not able to reproduce on though. What other programs have the same problem? Can you narrow down what it is (stderr output?)

**Comment by m0n9oose** [comment]
Thank you for quick reply!

Just now tried again to reproduce this problem in other tools and noticed, that problem is gone!

Dunno what really fix the problem, installing oh-my-fish addition or restart iTerm but it seems all fine.
Thanks a lot for great shell and support!

**Comment by m0n9oose** [comment]
No, it seems problem was solved by the changing default shell back to bash.

When default shell is fish some output messages still missing.

For example git output:

bash by default, using fish:
```
➜  repo git:(branch) git ps
Everything up-to-date
```

bash by default, using fish:
```
➜  repo git:(branch) git ps
➜  repo git:(branch)
```

**Comment by ridiculousfish** [comment]
How about `echo hello 1>&2`? Does that show anything?

**Comment by ridiculousfish** [comment]
Also, the environment may be different. Try diffing `env` when run from bash->fish, and from fish as the default.

**Comment by m0n9oose** [comment]
bash by default, using fish:
```
➜  ~ echo hello 1>&2
hello
➜  ~
```
fish by default:
```
➜  ~ echo hello 1>&2
➜  ~
```

**Comment by m0n9oose** [comment]
i've diffed env output with bash and fish:

Fish | Bash
------------- | -------------
SHLVL=2 | SHLVL=1
LANG=en_US.UTF-8 | n/a
n/a | _=/usr/bin/env

Also fish have a few additional vars

**Comment by m0n9oose** [comment]
any thoughts?

**Comment by ridiculousfish** [comment]
It's totally bizarre; it looks like stderr output is just being suppressed. What happens if you try with Terminal.app instead of iTerm?

**Comment by m0n9oose** [comment]
Same result :(

Terminal.app

bash by default, using fish:
```
Last login: Thu May 21 14:20:34 on ttys003
macbook:~ m0n9oose$ fish
➜  ~ echo hello 1>&2
hello
➜  ~ 
```
fish by default:
```
Last login: Thu May 21 20:34:09 on ttys004
➜  ~ echo hello 1>&2
➜  ~ 
```

**Comment by m0n9oose** [comment]
Tried to test this case on other computer with similar confgiration - all works fine. After that removed oh-my-fish, all configs, remove brew package and all tails.

After that install fish again, add rvm integration and set fish as default shell and all works fine! Don't know what's wrong, but it seems it's gone.

**Comment by ridiculousfish** [comment]
Crazy. Do post back if you ever figure it out!

**Comment by itay-grudev** [comment]
@m0n9oose Do you happen to have the following code in your ```config.fish```?
```
# Load the default rubies
if test -z $rvm_bin_path
  exec bash --login -c "exec fish"
end
```

**Comment by itay-grudev** [comment]
The code above is used by `Ruby` programmers to bypass rewriting all the RVM script for fish. So what it does is it initialises your environment through bash. Works great, but it did not redirect the stderr to stdout. But this version does:

_~/.config/fish/config.fish
```
# Load the default rubies
if test -z $rvm_bin_path
  exec bash --login -c "exec fish 2>&1"
end
```

**Comment by ridiculousfish** [comment]
This is very interesting..offhand I can't see why that code would interfere with stderr.

**Comment by zanchey** [comment]
I certainly haven't been able to reproduce this on Debian with bash 4.3.30 and fish 2.2b1, nor on OS X Vegemite with bash 3.2.57 and fish 2.2b1-17-g5c4acc8.
