### ISSUE TITLE
Return key does not work in systemd-nspawn container

### ISSUE THREAD

**Issue by hunger** [fish-shell/fish-shell#2085]
I use "machinectl login" to log into a container started with systemd-nspawn. The user there is configured to run the fish shell and has an empty home directory (no configuration whatsoever).

Fish starts up fine and typing works well, too (incl. Del, Backspace, Home, End), but the return key is dead. Ctrl-j works though, so I can get fish to execute things.

I am running agetty inside the container with the following flags:

/usr/bin/agetty --noclear --keep-baud --noissue --autologin devel pts/0 115200,38400,9600 linux

fish (same version) works fine outside of the container. Bash works fine inside and outside of the container.

Any ideas?

I am using fish version 2.1.2 on arch linux (both inside and outside of the container).

**Comment by ridiculousfish** [comment]
Does the return key work in other places in this container, e.g. vi?

**Comment by zanchey** [comment]
The output of `infocmp` might be useful too.

**Comment by hunger** [comment]
@ridiculousfish: vi works, bash started from fish works as well.

@zanchey: Here is the output of ­`infocmp`:
```
#       Reconstructed via infocmp from file: /usr/share/terminfo/l/linux
linux|linux console,
        am, bce, ccc, eo, mir, msgr, xenl, xon,
        colors#8, it#8, ncv#18, pairs#64,
        acsc=+\020\,\021-\030.^Y0\333`\004a\261f\370g\361h\260i\316j\331k\277l\332m\300n\305o~p\304q\304r\304s_t\303u\264v\301w\302x\263y\363z\362{\343|\330}\234~\376,
        bel=^G, blink=\E[5m, bold=\E[1m, civis=\E[?25l\E[?1c,
        clear=\E[H\E[J, cnorm=\E[?25h\E[?0c, cr=^M,
        csr=\E[%i%p1%d;%p2%dr, cub=\E[%p1%dD, cub1=^H,
        cud=\E[%p1%dB, cud1=^J, cuf=\E[%p1%dC, cuf1=\E[C,
        cup=\E[%i%p1%d;%p2%dH, cuu=\E[%p1%dA, cuu1=\E[A,
        cvvis=\E[?25h\E[?8c, dch=\E[%p1%dP, dch1=\E[P, dim=\E[2m,
        dl=\E[%p1%dM, dl1=\E[M, ech=\E[%p1%dX, ed=\E[J, el=\E[K,
        el1=\E[1K, flash=\E[?5h\E[?5l$<200/>, home=\E[H,
        hpa=\E[%i%p1%dG, ht=^I, hts=\EH, ich=\E[%p1%d@, ich1=\E[@,
        il=\E[%p1%dL, il1=\E[L, ind=^J,
        initc=\E]P%p1%x%p2%{255}%*%{1000}%/%02x%p3%{255}%*%{1000}%/%02x%p4%{255}%*%{1000}%/%02x,
        kb2=\E[G, kbs=\177, kcbt=\E[Z, kcub1=\E[D, kcud1=\E[B,
        kcuf1=\E[C, kcuu1=\E[A, kdch1=\E[3~, kend=\E[4~, kf1=\E[[A,
        kf10=\E[21~, kf11=\E[23~, kf12=\E[24~, kf13=\E[25~,
        kf14=\E[26~, kf15=\E[28~, kf16=\E[29~, kf17=\E[31~,
        kf18=\E[32~, kf19=\E[33~, kf2=\E[[B, kf20=\E[34~,
        kf3=\E[[C, kf4=\E[[D, kf5=\E[[E, kf6=\E[17~, kf7=\E[18~,
        kf8=\E[19~, kf9=\E[20~, khome=\E[1~, kich1=\E[2~,
        kmous=\E[M, knp=\E[6~, kpp=\E[5~, kspd=^Z, nel=^M^J, oc=\E]R,
        op=\E[39;49m, rc=\E8, rev=\E[7m, ri=\EM, rmacs=\E[10m,
        rmam=\E[?7l, rmir=\E[4l, rmpch=\E[10m, rmso=\E[27m,
        rmul=\E[24m, rs1=\Ec\E]R, sc=\E7, setab=\E[4%p1%dm,
        setaf=\E[3%p1%dm,
        sgr=\E[0;10%?%p1%t;7%;%?%p2%t;4%;%?%p3%t;7%;%?%p4%t;5%;%?%p5%t;2%;%?%p6%t;1%;%?%p7%t;8%;%?%p9%t;11%;m,
        sgr0=\E[0;10m, smacs=\E[11m, smam=\E[?7h, smir=\E[4h,
        smpch=\E[11m, smso=\E[7m, smul=\E[4m, tbc=\E[3g,
        u6=\E[%i%d;%dR, u7=\E[6n, u8=\E[?6c, u9=\E[c,
        vpa=\E[%i%p1%dd,
```

**Comment by hunger** [comment]
Hmmm... just noticed that sudo only accepts Ctrl-j in its password prompt, too:-/

Something is seriously fishy here and it is not only the shell. Any ideas how to debug this?

**Comment by ridiculousfish** [comment]
This sounds to me like a termcap issue? I don't have much familiarity with that domain, I'm afraid.

**Comment by zanchey** [comment]
You could try something like `xxd` - run it and type Enter, Ctrl-D.

That should produce output like this:
```
0000000: 0a                                       .
```

The terminfo stuff looks fine, it's the same on my system (although systemd-nspawn drops me into vt102 by default).

**Comment by hunger** [comment]
Even more wiered:/

Now fish works *sometimes*. Well, this is definitely not a fish bug, I'll close it again. Sorry for the noise.
