### ISSUE TITLE
Can't remove git prompt state separator

### ISSUE THREAD

**Issue by semaperepelitsa** [fish-shell/fish-shell#2086]
I'm unable to remove git separator from `__fish_git_prompt`. I want it to have no spaces like that: `(master*)`. I'm guessing Fish doesn't distinguish unset variable and empty string so it just resets it to default value in any case. I'm not sure whether it is a function issue or a shell limitation. Can you help?

```
> set -U ___fish_git_prompt_char_stateseparator ""
> echo $___fish_git_prompt_char_stateseparator | cat -e
 $
> __fish_git_prompt "(%s)"
(master *)
> set -e -U ___fish_git_prompt_char_stateseparator
> echo $___fish_git_prompt_char_stateseparator | cat -e
 $
> __fish_git_prompt "(%s)"
(master *)
```

**Comment by ridiculousfish** [comment]
fish definitely distinguishes between unset variables and empty strings. I'm not familiar with the git prompt but there may be a `test -z` or something in there that's responsible.

**Comment by zanchey** [comment]
On 2.2b1:

```
> set -U ___fish_git_prompt_char_stateseparator ""
set: Warning: universal scope selected, but a global variable “___fish_git_prompt_char_stateseparator” exists.
```

so I think that's the problem here.

Try:
```
set -eg ___fish_git_prompt_char_stateseparator; and set -U ___fish_git_prompt_char_stateseparator ""
```

(running them as separate commands almost certainly will lead to it being reset by `__fish_git_prompt`.

**Comment by semaperepelitsa** [comment]
Your commands did work, @zanchey. It is great that it does distinguish between unset and empty variables. It looks like I have set a global variable by accident. Since the warning will be present in the future release I will consider this issue closed. Thanks for your help.
