### ISSUE TITLE
Import from bash history fails on first line with backticks

### ISSUE THREAD

**Issue by jmiserez** [fish-shell/fish-shell#2091]
I have the following lines in my bash history file:

```
#1404655979
comm -23 currentlyinstalled.txt defaultinstalled.txt
#1404656132
comm -13   <(gzip -dc /var/log/installer/initial-status.gz | sed -n 's/^Package: //p' | sort)   <(comm -23 \
    <(dpkg-query -W -f='${Package}\n' | sed 1d | sort) \
    <(apt-mark showauto | sort) \
  )`

#1404656155
nano packages.sh
```

The import just fails after the line `<(apt-mark showauto | sort) \`, and no further entries are imported. I.e. the `nano packages.sh` entry and _all further entries_ are not installed.

There are two problems: lines with backticks are not imported, and the import suddenly stops. There [seems to be some code](https://github.com/fish-shell/fish-shell/blob/1242e63b6ac5c25f61cf08397a849b3c022f3b51/history.cpp#L1672) that excludes lines with backticks but I think it doesn't work correctly

In addition to this, the multiline entry is not correctly imported as all three lines are imported as separate history entries (instead of a single one), but bash isn't much better in this regard.

**Comment by ridiculousfish** [comment]
Thanks for reporting this!
