### ISSUE TITLE
Random errors when autocompleting

### ISSUE THREAD

**Issue by Matt3o12** [fish-shell/fish-shell#2093]
I just noticed getting random errors when autocompleting vi\[m\] (and another completion, I can't remember)

[First Sacktrace](http://pastebin.com/4zn6qmzX), [second stacktrace](http://pastebin.com/DiHDYXFN)

I don't know how to reproduce these errors reliable because they seemed to have happened randomly and don't happen all the time. It seems to be an issue that I don't have gettext installed. Still, fish should not complain so loudly unless it actually needs it.

Here are my spects:  

 - OS: Mac OS 10.10.3 (Yosemite)  
 - fish: stable 2.1.2 (bottled), HEAD  (botteled means that it was precompiled and I just downloaded a binary).  
 - I use homebrew as my package manger. [Here is the script](https://github.com/Homebrew/homebrew/blob/735d8d9b6f4cc3b6dcf41e815ae86e2098ea2e2f/Library/Formula/fish.rb) used for building fish.

**Comment by zanchey** [comment]
Does this definitely happen on the HEAD version? The `type` function has changed so that at least the proximate cause should have been fixed.

**Comment by Matt3o12** [comment]
On version 2.1.2, which was once built upon the head

**Comment by zanchey** [comment]
OK, that's quite old; if you have time to try a newer version (2.2beta1 or a newer HEAD build) that would be helpful, or wait until 2.2.0 is released and see if it still happens.

**Comment by Matt3o12** [comment]
I've tested it for about one week now on 2.2 and haven't seen a single exception. Good job!

**Comment by faho** [comment]
This should probably be closed, then.

**Comment by ridiculousfish** [comment]
Cool
