### ISSUE TITLE
Set window title to '' during exit

### ISSUE THREAD

**Issue by plttn** [fish-shell/fish-shell#2094]
Is it possible to set `exit` to have the window title be blank during that execution? Terminal.app has a bug where the window title will get stuck set as whatever the ssh title was set to and never clear it.

**Comment by ridiculousfish** [comment]
You can run code when fish exits like so:

    function exit_handler --on-process-exit %self
        # stuff
    end

You can put code to reset the title in there. Does that help?

**Comment by plttn** [comment]
I think so. Is there a way to override a function in another function temporarily? if I set fish_title to '', that solves that problem, but obviously I don't want it like that 24/7.

**Comment by ridiculousfish** [comment]
You can manually output the escape code to clear the title - something like `\x1b]0;` followed by `\7`.

**Comment by plttn** [comment]
I threw this into `exit_handler.fish` just to try and debug: 
```
function exit_handler --on-process-exit %self
        printf "\x1b]0;foobar\7"
end
```

Title still is remaining as `exit ~` on disconnect from ssh, when I'm assuming it should be `foobar`.

**Comment by ridiculousfish** [comment]
Autoloaded functions can't be event handlers - see #845. I tried loading your function explicitly, and it did set the title when exiting an ssh session with control-D.

**Comment by plttn** [comment]
That did it. Thanks for the help!

**Comment by ridiculousfish** [comment]
Cool :)

**Comment by plttn** [comment]
to anyone that wants to duplicate my setup: [gist](https://gist.github.com/plttn/b21c39081ea638473589) 

this changes the title to running program, and prompt pwd (aka the shortened one), and then sets title to `''` upon exit to solve the Terminal.app issue with titles.
