### ISSUE TITLE
modprobe tab complete doesn't work

### ISSUE THREAD

**Issue by ycny** [fish-shell/fish-shell#2095]
When doing `sudo modprobe vbox[TAB]` the current line extends to: 
`sudo modprobe vbox/sbin/modprobe: invalid option -- 'l'` and nothing happens. 
If then I repeat `sudo modprobe vbox[TAB]` i'll get something like: 
`sudo modprobe vbox/sbin/modprobe: invalid option -- 'l'          sudo modprobe vboxp` so it looks like fish has found some modules to complete but there is issue with `invalid option -- 'l'`. Probably because '-l' option is deprecated/removed since 2012. 

Arch Linux x86-64, fish 2.1.2

**Comment by zanchey** [comment]
Good news! This was fixed in 76ab22f74c which will be in the upcoming fish 2.2.0 release.
