### ISSUE TITLE
Using "alias" prevents color output

### ISSUE THREAD

**Issue by RoBi89** [fish-shell/fish-shell#2097]
Typing 
```
ls
```
 or 
```
ls -l
```
highlights files in different colors.

When I add:
```
alias ls "ls -l"
```

 to the config, neither ls nor ls -l display colors anymore.

**Comment by occivink** [comment]
"Fish implements aliases using functions. Use 'functions' builtin to see list of functions and 'functions function_name' to see function definition, type 'help alias' for more information."
You'll notice that, by default, fish has the following function for ls, which handles the coloring:
```
function ls --description 'List contents of directory'
        set -l param --color=auto
        if isatty 1
            set param $param --indicator-style=classify
        end
        command ls $param $argv
    end
```
Your alias overwrites the default *ls* function. To achieve what you want, I'd recommend editing the default *ls* function, for example with 
```
funced ls
```

**Comment by RoBi89** [comment]
Ah makes sense. Thanks. Is there any way to make the modifications stick? Just using 

    funced ls 

only lasts until I close the terminal.

**Comment by occivink** [comment]
I believe you're looking for *funcsave*.

**Comment by zanchey** [comment]
Sound like this has been sorted out!
