### ISSUE TITLE
Add a Sorin theme

### ISSUE THREAD

**Issue by pickfire** [fish-shell/fish-shell#2100]
Look at https://github.com/sorin-ionescu/dotfiles and https://github.com/sorin-ionescu/prezto

**Comment by ridiculousfish** [comment]
Want to make a PR? The format is pretty easy I think!

**Comment by pickfire** [comment]
No, it need to check whether **ssh** is on.

**Comment by pickfire** [comment]
Do you know where can I get an example of it? Thanks.

**Comment by ridiculousfish** [comment]
Sure, see the [sample prompts here](https://github.com/fish-shell/fish-shell/tree/master/share/tools/web_config/sample_prompts).

**Comment by pickfire** [comment]
I can't get `set -l arrow "$red❯$yellow❯$green❯"; echo "$arrow"` to work, in my terminal there is no color.

**Comment by ridiculousfish** [comment]
To set a color, use the `set_color` command, e.g. `set -l arrow (set_color red)'>'(set_color yellow)...`

**Comment by pickfire** [comment]
Thanks, and how do I put something in the right prompt such as zsh `$RPROMPT`?

Thank you for being so patience.

**Comment by ridiculousfish** [comment]
I think themes don't support that yet; that would be a nice feature to add.

**Comment by pickfire** [comment]
I want to print `x` if there is a first character, how do I do it?
```fish
case "."
    printf (set_color green)✚' '
```

**Comment by ridiculousfish** [comment]
Try `case '?'` and `case '??'`. fish's globbing is very simple and doesn't support regex features.

**Comment by pickfire** [comment]
I hope you can add some information about globbing and testing to the documentation.

**Comment by pickfire** [comment]
I think I have done most of the things, look at the first post, I haven't have much test yet. TODO:

- [ ] ═ ➜, and some icons sometimes switched
- [ ] implement vi-mode <<<
- [ ] fix bad test for merge

**Comment by zanchey** [comment]
Done with #2135?

**Comment by pickfire** [comment]
Yeah, most of the main feature. Except some minor problems.

**Comment by pickfire** [comment]
The prompt doesn't show up in `fish_config`. Reopening.

**Comment by zanchey** [comment]
I'm reopening this to remind me to review it, because I'm not convinced this will work as is

**Comment by faho** [comment]
This was fixed in b615534d8d67e1891437277fa781196111426f80.

The right prompt itself works, only fish_config doesn't install it. I'll open an issue dedicated to that and close this one.
