### ISSUE TITLE
annoying behavior on command complete

### ISSUE THREAD

**Issue by lalo73** [fish-shell/fish-shell#2102]
This commit 5c4acc8ee1485e40b00ea0578aeff338078cfb8b implements a useful behaviour.
However, its not working properly or is implemented only for fedora's shell.

I'm using Freya OS, and its [Terminal](https://launchpad.net/pantheon-terminal), so everytime I run a command, lets say `ls`, i got an annoying output: 
"]777;notify;Command completed;ls⏎ "

But if i type ls within bash shell, it correctly notifies with a desktop notification.

I've also try to deactivate this feature by adding "functions --erase __notify_vte_command_completed" to ~/.config/fish/config.fish, but it seems to ignore it.

**Comment by ridiculousfish** [comment]
Is `$VTE_VERSION` set for you? What is its value?

**Comment by lalo73** [comment]
`echo $TERM`
xterm
`echo $VTE_VERSION`
3409

**Comment by arty-name** [comment]
I have the same issue in Ubuntu 15.04
echo $TERM
xterm
echo $VTE_VERSION
3803

**Comment by ridiculousfish** [comment]
I've backed out 5c4acc8ee1485e40b00ea0578aeff338078cfb8b pending a fix for this. Thanks for reporting it!

**Comment by liblit** [comment]
We may be able to re-add this eventually, but not just yet. See further discussion in #2096.

**Comment by debarshiray** [comment]
vte-0.44.2 (and newer) will silently accept the OSC 777 escape sequence as a no-op without printing them in the terminal. See https://git.gnome.org/browse/vte/commit/?h=vte-0-44&id=8dbe242198fb3a4ce453866cfb4aa9dae9c3b9c4

This corresponds to VTE_VERSION=4402.
