### ISSUE TITLE
Fishshell Frameworks

### ISSUE THREAD

**Issue by bucaran** [fish-shell/fish-shell#2103]
What do you think about adding links (perhaps in the Wiki) to some of the known Fishshell _frameworks_ out there, such as [Fisherman](http://fisherman.sh)?

**Comment by ridiculousfish** [comment]
Sure, I think links are appropriate.

**Comment by krader1961** [comment]
PR #3231 caused me to notice this issue so taking ownership. @bucaran already added mentions to the wiki. I'll add a mention to the FAQ core doc since (at least today) people are more likely to notice this in the FAQ than our wiki.
