### ISSUE TITLE
SSH Host Completion

### ISSUE THREAD

**Issue by rrosson** [fish-shell/fish-shell#2104]
Recent convert from ZSH +skwp's yadr framework. I have everthing working great with fish but I am unable to find the proper way to get fish to tab complete hosts/IP addresses from my ~/.ssh/config and ~/.ssh/known_hosts with either ssh or slogin.

Anyone know of a function or plugin that would help me with my muscle memory issue.  :)

TIA
-Ron

**Comment by ridiculousfish** [comment]
This should be working. Does `__fish_print_hostnames` output the hosts you expect?

**Comment by rrosson** [comment]
Ok that gave me the list of my hosts and I noticed that this works with SSH but not SLOGIN. my muscle memory is trained for slogin <host> and not ssh <host>. Since I am a recent convert what would be the best way to add this functionality to slogin.

**Comment by ridiculousfish** [comment]
Does `slogin` take the same arguments and options as `ssh`? On the soon to be released [version 2.2](http://fishshell.com/beta/), you can use a `wraps` completion:

   complete -c slogin --wraps ssh

You can put that in ~/.config/fish/config.fish, or add a completions file.

On 2.1.x, it's a little more work. Basically you would copy the file `completions/ssh.fish` and replace ssh with slogin.

**Comment by rrosson** [comment]
Ok, Cool. I am currently using 2.1.2-1285-g386d6a7. So I will wait till 2.2 comes out. BTW I am using OS X.
