### ISSUE TITLE
Compgen? 

### ISSUE THREAD

**Issue by miabrahams** [fish-shell/fish-shell#2105]
Hi, does Fish offer a command like compgen? It is be useful to be able to pipe and filter the output of a very long completion list.

**Comment by zanchey** [comment]
Not yet! What do you use it for in bash?

**Comment by miabrahams** [comment]
Faster and easier fuzzy matching. For example I might type `git checkout c<tab>` and find a long list of branches starting with c, but I only care about 2.0 branch. Instead of performing a mental transformation to something like `git branch -a | grep ^c | grep 2`  I can do `compgen !! | grep 2`

**Comment by ridiculousfish** [comment]
In fish 2.2 (and master), when the focus is in the pager, you can start typing to filter it:

![screen shot 2015-06-20 at 4 47 28 pm](https://cloud.githubusercontent.com/assets/920838/8269752/189f665e-176c-11e5-9c43-6872deb8678d.png)

**Comment by pickfire** [comment]
How do you use that pager in fish 2.1.2? Is pink the default colour for highlighting the syntax, it is hard to view that.

**Comment by ridiculousfish** [comment]
It's coming in fish 2.2, which you can try at http://fishshell.com/beta/ The highlighted item is by default "purple" (or whatever the shell thinks it's purple) but it's easy to change. `fish_color_search_match` is the name.

**Comment by pickfire** [comment]
Does fish shell have a way to do completion with colors like how zsh do it?

![2015-06-19-231828_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/8271028/1065ff02-1834-11e5-8f2d-5589aeeff1d5.png)
####### Note: Look at terminal in the bottom corner showing zsh tab completion

**Comment by ridiculousfish** [comment]
Err, which corner? I see colors for the `ls -a` command, but that's not tab completion, and I see what looks like color specifications for the email messages?

**Comment by pickfire** [comment]
Bottom right corner which is using zsh, look below `~ >>> ls -a`, it should be a tab completion.

When you use tab completion with zsh such as `ls`, `cd` and `mv` it have colored tab completion. Should I open an issue for this?

**Comment by ridiculousfish** [comment]
You're saying that the colorized output for `.fonts`, `.parallel`, etc. is NOT from running `ls -a`, it's from tab completions? It really looks like you just ran `ls -a` with `LSCOLORS` set to something.

Are you sure this is from tab completion and not from just executing the command? If so, do you know what configuration options are necessary to get that?

**Comment by pickfire** [comment]
`zsh` doesn't how those hidden files but it does show TAB COMPLETION with **colors**. I am currently using `zsh` with **prezto framework** and tried switching to `fish` but it breaks many applications such as i3status. (Maybe I did not set LANG... in fish.config)

**Comment by ridiculousfish** [comment]
Ok, I was able to see colors in tab completions after installing pretzo. If @pickfire or anyone wants to write up a proposal for how this should work (what the color categories should be, and what they are applied to) we can make progress on this. Thanks for filing this.

**Comment by zanchey** [comment]
There's some work on that in #1599.

**Comment by pickfire** [comment]
How do I get the focus in the pager?

**Comment by ridiculousfish** [comment]
Press tab, or down arrow.

**Comment by zanchey** [comment]
To return to the original discussion, fish doesn't offer a way to print the completions for a particular commandline, relying instead on the pager's filtering mechanism. @miabrahams, do you think that covers your use case?

**Comment by Stautob** [comment]
Another use of the compgen function is, to use it with a run-dialog like often provided with tiling-wms.
Example from Awesome WM (its LUA):

shell_cmd = "/usr/bin/env bash -c 'compgen -A " .. comptype .. " " .. words[cword_index] .. "'"

In my opinion provides fish the best completion available. And I would like to see it beeing useable for this.

**Comment by pickfire** [comment]
@Stautob Nice, I think I can use this for dmenu too.

**Comment by faho** [comment]
>fish doesn't offer a way to print the completions for a particular commandline

Isn't that what `complete -C` is supposed to do? There's currently a few issues with it, but ignoring them, `complete -C"$history[1]" does basically what I understand `compgen` to do.

The awesome stuff could also be written to use it, though I haven't used awesome in a while.

**Comment by Stautob** [comment]
You are right, this command does exactly, what compgen does, but I don't want it to do bash-niveau completion, I want the full fish-completion.
So e.g. if no command can be found starting with "xy", complete -C"xy" should propose all commands containing "xy" like the interactive completion does.

**Comment by faho** [comment]
We have a `compgen`, and it is `complete -C`. There's nothing more to do here.
