### ISSUE TITLE
Feature Request: Interactively delete history entries during auto-completion (i.e. via Alt-Del)

### ISSUE THREAD

**Issue by bentolor** [fish-shell/fish-shell#2110]
Fish auto-completion is great, but the history can be easily bloated with wrong & unwanted entries

I'm aware about `history --contains keyword --delete` and the interactive history editor via `fish_config` but find them rather cumbersome.

It would be great to have i.e. a key combination like `[Alt-Del]` or `[Ctrl-Del]` to remove the current completion proposal from the history

**Comment by ridiculousfish** [comment]
That's a good idea!

**Comment by krader1961** [comment]
The "current completion proposal" is not added to the interactive command history. You have to actually execute a command for it to be added to the history. By that time it's far too late for a key binding to have any effect.

@bentolor Can you provide more details about your scenario? Perhaps by creating a asciinema recording?

**Comment by floam** [comment]
@krader1961 Why would the item need to be added to history again?

**Comment by floam** [comment]
I think maybe there is a misunderstanding with what he's asking for - the proposal he's referring to is the completion that **fish is proposing to the user** that the user would be rejecting, as I read it.

**Comment by floam** [comment]
So I suspect he's wanting to be able to hit alt-del to nuke what he sees suggested from history, or while searching history with the up arrow remove the current entry from history. In either cased doing the equivalent of `history --contains <COMMAND LINE CONTENTS> --delete` would get the user close and show the a list to pick from that would have their command in it and they can delete it.

The interactive deletion is essential because the desired (undesired) history item may not be the first result due to the context-sensitive nature of autosuggestions and the builtin's inability to do queries on the variables.

**Comment by bentolor** [comment]
> So I suspect he's wanting to be able to hit alt-del to nuke what he sees suggested from history, or while searching history with the up arrow remove the current entry from history. 
You nailed it!
````
$ wget http://user:mysecrepass@foo.baz/ ...
                                 # Argh! Missed to type a leading space. Now my pw is in the history
                                 # --- Option #1:
$ [arrow-up]                     # shows last command
$ [Alt-Del]                      # Clears commandline & removes entry from history
                                 # --- Option #2:
$ mysecret[arrow-up]             # shows last command matching string
$ [Alt-Del]                      # Removes entry from history. Suggest next history match
$ mysecret[arrow-up]             # ..nothing happens (last element).
````

**Comment by ridiculousfish** [comment]
This is a cool idea. We could even do it without confirmation - just have to report the command we deleted, so the user can copy and paste it if they want to reinstate it.

**Comment by krader1961** [comment]
Okay, that makes sense. In retrospect I should have grokked that from the original comment.  And this is the first really good example I've seen for why fish should continue to have a way to delete individual history entries. Now we just need to make that mechanism robust.

There are also some details to be worked out with regard to this proposal. For example, should the current command line be cleared? Should we also bind [alt-backspace]?

P.S., [ctrl-del] can't be done because [del] is already a control character. It's as if you tried to `bind \c\cH` (where `\ch` is the [backspace] key); the [ctrl] key modifies the next character it doesn't send a character in its own right. But [alt-del] or [meta-del] is certainly possible.

**Comment by bentolor** [comment]
>  For example, should the current command line be cleared? 

Thought about this, too. On the plus side, this could make sense, because otherwise the user needs to switch to a different key-combination to clear the line after his cleanup. On the negative side this could suprise the user, as the semantic of the key combination changes on the last history match.

So **I'd say "no"** and would be fine with the case that after typing `--passwd mypass` follwed by `[Up-Arrow]` and as many `[Alt]-[Del]` until nothing more happens and then switch over into hammering `[Alt]-[Backspace]` or `[Backspace]` as long as required to clear the line, because I do not know better.

> Should we also bind [alt-backspace]?

For me [Backspace] is clearly bound to _editing the line I'm on_ and currently seems to act as "delete last word" which IMHO is perfectly appropriate.  So would leave [alt-backspace] untouched.

>  But [alt-del] or [meta-del] is certainly possible.
[alt-del] sounds fine and as the most intuitive option to me.

**Comment by bentolor** [comment]
@krader1961 

>  And this is the first really good example I've seen for why fish should continue to have a way to delete individual history entries. 

Another use-case I have is that I'm still unable to remember if it is `git rev-parse @` or `git parse-rev @` (no working autocompletion on that). 

After doing it wrong time _only one time_ the fish history deceives and annoys me so much, that I start to edit the history over and over again. 

As I _still_ can still not tell you which one of the both word git is expecting, this game will be ongoing for me for an indefinite time ;-)

**Comment by floam** [comment]
>After doing it wrong time only one time the fish history deceives and annoys me so much, that I start to edit the history over and over again.

Maybe we should record the exit code in history?

**Comment by bentolor** [comment]
@floam Interesting idea. But many user errors will not cause an exit code indicating it. Others might return exit codes because the operation failed, but not the command syntax (i.e. `git push` on outdated branches). 

So I still think the feature to easily heal/delete completions would bring the most "bang" for the "bucks".

**Comment by jinliu** [comment]
@bentolor Is the following function what you want?
`function delete-current-history-search
        if commandline --search-mode
                history --delete (commandline)
                commandline -f history-search-backward
        end
end`
BTW, how to bind ALT-DEL?

**Comment by faho** [comment]
>BTW, how to bind ALT-DEL?

`fish_key_reader` is your friend. For my term, I'd have to call `bind \e\[3\;3~`.

**Comment by bentolor** [comment]
I added the following code to my `~.config/fish/config.fish`:

```
function delete-current-history-search
        if commandline --search-mode
                history --delete (commandline)
                commandline -f history-search-backward
        end
end

function fish_user_key_bindings
	bind \e\[3\;3~ delete-current-history-search
end
```

Currently testing. But so far it looks pretty good, @jinliu ! Thanks.

**Comment by bentolor** [comment]
@jinliu If you delete the last history element, nothing visible happens. The command is erased from history, though. This might be confusing for the user. 

Probably the best solution in this case would be, to revert to the characters the user originally entered (and which are highlighted on history search matches)

**Comment by jinliu** [comment]
> Probably the best solution in this case would be, to revert to the characters the user originally entered (and which are highlighted on history search matches)

Agree. But I guess this (and deleting autosuggestion history matches) must be done in C code.

**Comment by zanchey** [comment]
Try `history delete --exact --case-sensitive (commandline)`.

**Comment by bentolor** [comment]
Thanks, this improves the situation. Unfortunately but no longer to the full beauty it IMHO previously did: After pressing `[Alt]`-`[Del]`, the `commandline -f history-search-backward` shows the next entry. But on pressing `↓`-Key, it appears again.

It's deleted from history, though: After pressing `Ctrl-C` and restarting, the deleted entry no longer appears.

**Comment by bentolor** [comment]
> presumably you want to use history to go and try the command again with a small adjustment. 

This scenario immediately came into my mind. I think this is a very common pattern

In those cases: After your adjustment was successful, you really want to drop the other command, because it will now continue to deceive and confront you with the same error over and over again.

> So it would have to just affect auto-suggestions I think.

Doe fish auto-purge/expire history entries? 

Nevertheless, storing the exit code of commands and offering a _„delete all failed commands from history“_ sounds great to me.

**Comment by faho** [comment]
This is handled by #9515, which allows it in the history pager, where it's clearer that there's a history context.

**Comment by bentolor** [comment]
Unfortunately #9515 does not work with a pager. I have `fzf` installed via OMG, which obstructs the deletion feature inside the history. 

After resurrection the `[Alt]-[Del]` binding with the updated script from jinliu (note to myself: working copy below), I'm still very much in favour of that inline approach. 

**As CLI program, fish obviously has hit a quite hard & early limit on the UX features, which are discoverable by users on their own. I think that's unfortunate.** Would love something like a "fish tip" oneliner as startup prompt.

```fish
function delete-current-history-search
        if commandline --search-mode
                history delete --exact --case-sensitive (commandline)
                commandline -f history-search-backward
        end
end

# Alt-Del
function fish_user_key_bindings
    bind \e\[3\;3~ delete-current-history-search
end
```

**Comment by krobelus** [comment]
> I have fzf installed via OMG, which obstructs the deletion feature inside the history.

you can tell your external pager to run any arbitrary shell command, which allows you to delete the current item 

> function delete-current-history-search

this implementation looks strictly worse than the builtin version, although I agree that we should prefer to implement this in fish script rather than rust source code. It should be kind of possible today to reach feature parity but I'm not sure
