### ISSUE TITLE
Weird output for cd

### ISSUE THREAD

**Issue by hanny24** [fish-shell/fish-shell#2112]
Hi,
I'm using terminator and I get output similar to this
```
]7;file:///%68%6f%6d%65/%68%61%6e%6e%79⏎ 
```
whenever I use cd command. My titlebar is set correctly. Also everything is ok if I run 
```
set tmp (cd)
```
Other shells (bash, zsh) are working correctly in Terminator. Also, my fish config is working fine in gnome-terminal.

**Comment by ridiculousfish** [comment]
It's this from `__fish_config_interactive`:

        # Notify vte-based terminals when $PWD changes (issue #906)
        if test "$VTE_VERSION" -ge 3405 -o "$TERM_PROGRAM" = "Apple_Terminal"
                function __update_vte_cwd --on-variable PWD --description 'Notify VTE of change to $PWD'
                        status --is-command-substitution; and return
                        printf '\033]7;file://%s%s\a' (hostname) (pwd | __fish_urlencode)
                end
        end

What value do you have for `$VTE_VERSION`?

**Comment by hanny24** [comment]
@ridiculousfish ```$VTE_VERSION``` is set to 4002

**Comment by ridiculousfish** [comment]
Any idea why this isn't working? Checking for `VTE_VERSION` seems rather fragile as we found with #2096.

@hanny24 You ought to be able to work around this via `functions --erase __update_vte_cwd`. Does that work?

**Comment by hanny24** [comment]
Yes, that works just fine.

**Comment by zanchey** [comment]
Reverted per #2096, so this should be fixed now.
