### ISSUE TITLE
Support homebrew's vendor completions needs

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#2113]
From #1485, languitar writes:

>Is it possible to redefine this path via build system configuration arguments? I am currently implementing fish completion support for OS X homebrew and in homebrew each program is installed into a separate folder and the prefix is formed by symlinking things together. Right now the vendor completion path points into the isolated installation prefix of fish and will therefore never match to any other completions symlinked into the actual prefix. So, making this configurable would be a great help in this situation.

>the actual install prefix for fish is e.g. `/usr/local/Cellar/fish/HEAD` and things are symlinked together into `/usr/local`. So I would just want to reconfigure things so that `/usr/local/share/fish/vendor_completions.d` ends up on `fish_complete_path`.*

This bug tracks figuring how to best support this scenario.

**Comment by languitar** [comment]
@ridiculousfish what are the available possibilities to mangle the `fish_complete_path` via the build system you were talking about in #1485?

**Comment by ridiculousfish** [comment]
fish has only a [handful](https://github.com/fish-shell/fish-shell/blob/8ba0ab2172ae81432ed4db9a377169857bd2d326/Makefile.in#L56) of compiled-in paths and most of the time it tries to ignore them, preferring relative paths to the fish executable itself (so it can be relocatable). [Here's where it determines them](https://github.com/fish-shell/fish-shell/blob/master/fish.cpp#L143).

For setting `fish_complete_path`, it makes sense to me to arrange for something like [this code](https://github.com/fish-shell/fish-shell/blob/master/share/config.fish#L63) to run. This could be done as a `profile.d` file if we implement that (#1956) or it could be done now by just appending some code to `$PREFIX/share/fish.config` or `$PREFIX/etc/fish.config` as the last step. That may seem like too much of a hack though.

Alternatively we could just support this directly as a special case. There's plenty of OS specific stuff in fish config files, like the menagerie of Linux command-not-found handlers.

**Comment by languitar** [comment]
Having special support for homebrew sounds too complicated and brittle to me. What if homebrew changes the Cellar scheme... I would either prefer having something like `profile.d` inside the installation prefix which we can then pimp from the homebrew install magic or as a very simple alternative: always include `/usr/local/share/fish/vendor_completions.d` in the path.

**Comment by ridiculousfish** [comment]
Hardcoding `/usr/local/share/fish/vendor_completions.d` (as a preprocessor define) seems appropriate to me. It doesn't make much sense for `vendor_completions.d` to be relocatable.

**Comment by zanchey** [comment]
There's a challenge in supporting the wide range of approaches to the FHS here. I don't know that hardcoding of `/usr/local` is a good idea, although it might be appropriate as an additional path (`/usr/local/share/fish/site_completions.d` as well as the prefix-contained `vendor_completions.d`). We definitely shouldn't create that path by default as the installation process shouldn't touch anything outside of the prefix.

On `pkgconfig`-supporting platforms, we already ship a `fish.pc` file which allows the vendor completions path to be determined programmatically by other packages. We could certainly add a configure option to allow the vendor completions directory to be outside of DATADIR, or do what `zsh` does with `--enable-additional-[function]-path` and enable as many additional completion paths to be added as required.

The other option is that Homebrew could configure `sysconfdir` to be `/usr/local/etc`, then use `/usr/local/etc/fish/completions` for shipped completions. I suspect this is not a palatable solution as they are quite committed to keeping every package independent of others.

Of all of these, the most appropriate cross-platform solution as I see it is to add `/usr/local/fish/site_completions.d` as a component of `fish_complete_path`, but not to create it during install and leave that up to the site (or package manager).

**Comment by jhenahan** [comment]
An additional consideration is that not every Homebrew install lives in `/usr/local`. In the `brew` case, at least, it should probably be `(brew --prefix)/somewhere/` or even just put completions `/opt/fish/`.

**Comment by zanchey** [comment]
I'd like to solve this with a configure option - I think that's going to be the safest way forwards.

**Comment by zanchey** [comment]
I'll try and take a look at this this week.

**Comment by krader1961** [comment]
@faho: Does your change to support "snippets" and generally make vendor configuration of fish a more pleasant experience address this issue? If not should this hold up the 2.3.0 release milestone or be retargeted to next-2.x?

**Comment by zanchey** [comment]
I do want to take this for 2.3.0 and have a WIP.

**Comment by krader1961** [comment]
Good to know. I definitely agree that among the remaining open issues for 2.3.0 this one should definitely be addressed. It just wasn't clear what, if anything, still needed to be done from a casual reading of the issue.
