### ISSUE TITLE
chruby-exec does not work

### ISSUE THREAD

**Issue by dalizard** [fish-shell/fish-shell#2117]
I am not sure if this problem comes from fish or from chruby but after looking at [this issue], the first examples are working right away. Here is the problem:

```shell
~ $ chruby --version
chruby: 0.3.9
chruby-fish: 0.6.0
~ $ fish -v
fish, version 2.1.2
~ $ which chruby-exec
/usr/local/bin/chruby-exec
~ $ chruby
   1.9.3-p392
   2.0.0-p353
   2.1.0
   2.1.5
   2.2.1
 * 2.2.2
~ $ chruby-exec 2.2.2 -- ruby -v
fish: Expected a command name, got token of type 'Run job in background'. Did you mean 'COMMAND; and COMMAND'? See the help section for the 'and' builtin command by typing 'help and'.
Standard input: chruby 2.2.2  && ruby -v 
                               ^
~ $ 
```

**Comment by ridiculousfish** [comment]
`chruby-exec` is invoking `$SHELL` with POSIX sh shell script, which won't work since fish isn't POSIX.  Let's call this a dup of #150 where we consider implementing &&. Thanks for filing this!!

**Comment by dalizard** [comment]
@ridiculousfish Awesome, I searched for a similar problem but I missed that one. You are welcome!
