### ISSUE TITLE
Command starting with space don't show up in history

### ISSUE THREAD

**Issue by maxried** [fish-shell/fish-shell#2118]
When you run a command with a space in front of it, like " ls" instead of "ls", it will not be recorded in history.

How to reproduce:
1. Run "history --clear" and confirm.
2. Run "history" to confirm it's empty.
3. Run " ls". (Mind the space in front of the command!)
4. Run history again and notice " ls" is missing.

**Comment by ridiculousfish** [comment]
Yes, this is by design - see #615. It's intended to be a simple way to run commands that you don't want to show up in history. Is it causing problems for you?

**Comment by maxried** [comment]
No, it's just confusing. I didn't know that's a feature.
Am 02.06.2015 8:51 nachm. schrieb ridiculousfish <notifications@github.com>:Yes, this is by design - see #615. It's intended to be a simple way to run commands that you don't want to show up in history. Is it causing problems for you?

**Comment by ridiculousfish** [comment]
Ok, let's close. Thanks for filing this!

**Comment by MhdAli** [comment]
Hi,

Is any way that we can save commands start with spaces?

**Comment by ridiculousfish** [comment]
Err, why would you want to start a command with a space? That's a very unusual thing to want to do.

**Comment by pickfire** [comment]
In `zsh`, you could press **Up** to use the previous command including command with spaces but it would not be saved into history. I think `fish` should also implement this so that people can easily access the last command without retyping it while not saving to *history*.

**Comment by ridiculousfish** [comment]
#1383 tracks making up-arrow recall the last item even if it is suppressed from the history.

**Comment by orifolger** [comment]
I often copy-paste commands, and inadvertently spaces are inserted at the beginning of the command. The space is not there intentionally.

Could this be made optional? IIUC, this is optional in Bash (set by HISTCONTROL variable).

**Comment by zanchey** [comment]
We are very unlikely to make this optional, for the reasons described in the [fish design document](https://fishshell.com/docs/current/design.html).

One thing that might help in your situation is to use the newly-implemented bracketed paste support to remove leading or trailing whitespace.
