### ISSUE TITLE
Alt backspace does not kill last word on iterm2 (yosemite)

### ISSUE THREAD

**Issue by ismay** [fish-shell/fish-shell#2124]
`Ctrl` + `w` does remove part of the path succesfully, and `Alt` (or option) + `directionkey` moves the cursor left or right by a word succesfully. Is there any reason why the `backward-kill-word` keybinding won't work on iterm2 on mac? I've added:

```
bind \e\b backward-kill-word
```

To the end of my config.fish, but that does not seem to remedy it. Is this fish specific, or should I look elsewhere to remedy this?

**Comment by ridiculousfish** [comment]
Try making Left Option act as Escape:

    
![screen shot 2015-06-05 at 1 40 15 am](https://cloud.githubusercontent.com/assets/920838/8002465/f5a89642-0b23-11e5-864a-1789156dc9a5.png)

Does that fix your problem?

**Comment by mojoLyon** [comment]
Working for me.

**Comment by ismay** [comment]
That did it! Cool, thanks for the quick reply!
