### ISSUE TITLE
PYTHONPATH not handled as a list anymore

### ISSUE THREAD

**Issue by languitar** [fish-shell/fish-shell#2125]
In older versions of fish, `PYTHONPATH` used to be a list. Since I upgraded to the latest master version this is not the case anymore:
```
jwienke@cinnabar ~> echo $PYTHONPATH
/homes/jwienke/local/trusty/x86_64/lib/python/site-packages:/homes/jwienke/local/trusty/x86_64/lib/python2.7/site-packages:/homes/jwienke/local/trusty/x86_64/lib/python2.7/dist-packages
jwienke@cinnabar ~> fish --version
fish, version 2.2b1-29-g18d746
```

**Comment by ridiculousfish** [comment]
This is deliberate; see #1374. See #2022 for some ideas about what we can do.

**Comment by languitar** [comment]
Ok, didn't find that issue.

How is `PATH` currently handled? Because there it still seems to be a list. Maybe a special rule for certain variables?

**Comment by ridiculousfish** [comment]
Yes, we have a whitelist which is only `PATH`, `MANPATH`, and `CDPATH`.

**Comment by languitar** [comment]
Can `PYTHONPATH` be added there? It follows the same semantics and doesn't allow URIs.

**Comment by ridiculousfish** [comment]
We hope to never change the whitelist, to avoid different versions of fish behaving differently. However we may relax the rules for outgoing variables, so we won't split on colons on importing env vars but will add colons when exporting them. I think there's an issue tracking that idea somewhere.

**Comment by languitar** [comment]
Sure. Thanks for the explanations.

**Comment by Hwesta** [comment]
For the next person to run into this: I was having the problem where `set -xg PYTHONPATH /python/path/1/ /python/path/2/` produced `PYTHONPATH=/python/path/1//python/path/2/` which Python couldn't read properly.  The workaround seems to be `set -xg PYTHONPATH /python/path/1/:/python/path/2/` which allows Python to see a colon-delineated list, even though fish sees it as a string.
