### ISSUE TITLE
fish: Tries to print invalid wide character string

### ISSUE THREAD

**Issue by adham90** [fish-shell/fish-shell#2126]
`fish: Tries to print invalid wide character string`
i'm using arch linux and i have this error.
i set: `set --global --export LANG en_US.UTF-8`
and the prompt messed up but the msg gone how can i fix this error without **set UTF-8**

**config.fish**
```
set --erase fish_greeting
# Path
set --global --export PATH .                     $PATH
set --global --export PATH $HOME/bin             $PATH
set --global --export PATH $HOME/local/bin       $PATH
set --global --export PATH $HOME/.gem/ruby/*/bin $PATH

# Libraries
set --global --export PYTHONPATH $HOME/python/*/lib
set --global --export RUBYLIB    $HOME/ruby/*/lib

# Path to your oh-my-fish.
set fish_path $HOME/.oh-my-fish

# Path to your custom folder (default path is ~/.oh-my-fish/custom)
#set fish_custom $HOME/dotfiles/oh-my-fish

# Load oh-my-fish configuration.
. $fish_path/oh-my-fish.fish

# Custom plugins and themes may be added to ~/.oh-my-fish/custom
# Plugins and themes can be found at https://github.com/oh-my-fish/
Theme 'l'
Plugin 'theme'
Plugin 'git-flow'
Plugin 'localhost'
Plugin 'rails'
Plugin 'rvm'
Plugin 'ssh'
Plugin 'sublime'
Plugin 'gem'
Plugin 'fry'
Plugin 'fish-spec'
Plugin 'bundler'
Plugin 'ccache'
Plugin 'archlinux'
Plugin 'jump'
Plugin 'tiny'
```

**Comment by ridiculousfish** [comment]
This message is printed when `wcstombs` fails. I don't know what would cause this offhand.

**Comment by zanchey** [comment]
The easiest way is to remove "UTF-8" from LANG and then try to use a prompt containing Unicode characters (e.g. the Git prompt).

**Comment by RasmusWL** [comment]
I had this problem, and wanted to let the solution live on.
---
Check the output of `locale`. Even though `LANG` might be something with utf8, the others might not. I put 
```
export LC_ALL=en_US.utf8
```

in my `.profile` and everything was good!
