### ISSUE TITLE
Problem with fish_config

### ISSUE THREAD

**Issue by mukintaras** [fish-shell/fish-shell#2127]
Running fish_config I have this output:

Web config started at 'file:///home/taras/.cache/fish/web_config-F33XVB.html'. Hit enter to stop.
В текущем сеансе браузера создано новое окно. <--- This means "New web browser tab created" btw
::ffff:127.0.0.1 - - [09/Jun/2015 13:24:53] code 404, message File not found
::ffff:127.0.0.1 - - [09/Jun/2015 13:24:54] code 403, message Forbidden

And config itself is unusable, only partly loaded and not working at all, here's screenshot http://imgur.com/rrhOfBT

**Comment by ridiculousfish** [comment]
Thanks for the report! What web browser is this? Is it Chrome?

**Comment by mukintaras** [comment]
Yes, Chrome (not Chromium), ver 43, 64bit

**Comment by zanchey** [comment]
Are you running Ubuntu? My guess is that you are being bitten by an incorrectly-packaged version in Ubuntu or Debian - see #1860 or #1847.

**Comment by mukintaras** [comment]
Yes, this us Ubuntu 15.04. Thank you for the links

**Comment by ridiculousfish** [comment]
Closing as a dup of #1847
