### ISSUE TITLE
Exiting “sudo fish” renders terminal unusable

### ISSUE THREAD

**Issue by kseistrup** [fish-shell/fish-shell#2130]
If I sudo into `fish` with either `sudo fish` or `sudo fish -i` and then exit fish with a ^D, ENTER no longer gives me a new line — instead the prompt is repeated on the same line for each ENTER:

```sh
[kseistrup@home ~]$ sudo fish -i
root@home /h/kseistrup# ^D
[kseistrup@home ~]$ [kseistrup@home ~]$ [kseistrup@home ~]$ 
```

Environment:

```sh
$ uname -a
Linux home 4.0.5-1-ARCH #1 SMP PREEMPT Sat Jun 6 18:37:49 CEST 2015 x86_64 GNU/Linux
$ echo $TERM
xterm
$ fish --version
fish, version 2.1.2
$ 
```

Same thing happens if `$TERM == screen`.

**Comment by ridiculousfish** [comment]
Does `reset` fix this?

**Comment by kseistrup** [comment]
It does.

**Comment by zanchey** [comment]
Which terminal are you using? I can't reproduce this under screen, tmux or PuTTY (which claims to be Xterm).

**Comment by kseistrup** [comment]
I first ran into this problem on the `sakura` terminal emulator (“sakura version is 3.2.0”) and the same thing happens with a vanilla `xterm` (“XTerm(318)”), both of which have `TERM=xterm`. It is also reproducible in `buyobu` (“aur/byobu 5.90-1”) that uses tmux for multiplexing and have `TERM=screen`.

**Comment by faho** [comment]
@kseistrup:
Is this still an issue with current git? There were a few changes regarding terminal setup in the meantime that might have fixed this.

**Comment by kseistrup** [comment]
I just tried in `sakura`, `xterm` and `byobu`, and it is no longer a problem.

**Comment by faho** [comment]
Thanks, that's a close then.
