### ISSUE TITLE
Garbled git completion

### ISSUE THREAD

**Issue by xiaochuanyu** [fish-shell/fish-shell#2132]
I see the following output when I press TAB to list completions for "git checkout".
```
~ git checkout
... 
cbc7d9775e38                                                       (Tag)
tandard\ input\):1:\ \ dev-main1                                (Branch)
tandard\ input\):2:\*\ dev-main2                                (Branch)
...
```
All the completions for branches are garbled up. However tags appear to be fine.

I'm using fish 2.1.2 on OSX Yosemite.
git version is 2.4.2.
fish and git were installed through brew.

**Comment by xiaochuanyu** [comment]
I just tried a few different git repos. All have the same problem.

**Comment by ridiculousfish** [comment]
What does `__fish_git_branches` show? How about `command git branch --no-color -a`?

**Comment by xiaochuanyu** [comment]
Here they are:
```
~ __fish_git_branches
tandard input):1:  dev-main1
tandard input):2:* dev-main2
```
```
~ command git branch --no-color -a
...
 dev-main1
*dev-main2
...
```

**Comment by ridiculousfish** [comment]
Your `command git branch --no-color -a ` looks OK but `command git branch --no-color -a ^ /dev/null  | sgrep -v ' -> '` has garbled output. What does `functions sgrep` output? Here's mine (which is what is expected):

    function sgrep --description 'Call grep without honoring GREP_OPTIONS settings'
    	set -l GREP_OPTIONS
    	command grep $argv
    end

**Comment by xiaochuanyu** [comment]
My `sgrep` is identical to yours. However,  I think I know what's causing the problem now. In my config.fish, I have GREP_OPTIONS set as follows:
```
set -x GREP_OPTIONS '--color=always -Hn'
```
If I comment that out and reload fish, the problem disappears.

Here's an additional test with `GREP_OPTIONS` still set in my config.fish:
```
~ $ function hello
        echo $GREP_OPTIONS
        set -l GREP_OPTIONS hello world
        echo $GREP_OPTIONS
    end
~ $ hello
--color=always -Hn
hello world
```
It seems `GREP_OPTIONS` somehow leaked through to `grep` even though it was overridden locally.

**Comment by ridiculousfish** [comment]
I think there's a regression here. The `set -l` ought to prevent the variable from being exported, but it's not working.

**Comment by ridiculousfish** [comment]
Wow, this is a very longstanding bug from fish 2.0 on. If a variable is exported, and then a shadowing variable is not exported, we should not export the variable; instead we do. This is because I "simplified" the algorithm to only look at exported variables, missing the possibility that an unexported variable is shadowed.

**Comment by ridiculousfish** [comment]
Cherry-picked to Integration_2.0.0 as ea407476d0e8bfe8b179dbb43bdecb6bdbd2acbb. Thanks for reporting this!!

**Comment by ridiculousfish** [comment]
@xiaochuanyu if you're on master or the integration branch, I'd appreciate verifying that this fixes your bug. If not that's ok - thanks!
