### ISSUE TITLE
Looks like test -n is broken

### ISSUE THREAD

**Issue by sandric** [fish-shell/fish-shell#2133]
I may be get smth wrong, but [here](http://fishshell.com/docs/current/commands.html#test) is this example:
```
If the variable MANPATH is defined and not empty, print the contents:

if test -n $MANPATH
    echo $MANPATH
end
```

But in this mine function:

```
function myfunc
  set foo bar
  if test -n $foo
    echo exists
  end
end
```
It prints `exists` no matter if foo defined or not. Looks like for it to work correctly it should be just `if test $foo`, with no -n.

Is it bug, or I just misunderstood this behavior?

**Comment by ridiculousfish** [comment]
This is the unfortunate behavior that POSIX `test` requires. Basically `$MANPATH` is unset, so `test` only sees the argument `-n`, and so it falls into a single-argument special case. See [my answer here](http://stackoverflow.com/questions/23227590/test-command-difference-between-n-and-z/23233524#23233524) for more.

This is annoying and surprising enough that we ought to consider fixing it, despite (or perhaps to spite) POSIX.

**Comment by ridiculousfish** [comment]
I like the title here, because it sure does "look like" `test -n` is broken even if it's not. Keeping it :)

**Comment by sandric** [comment]
haha, ok)

**Comment by ridiculousfish** [comment]
I should add, the simple workaround is to quote it: `test -n "$MANPATH"`. Anyways thanks for filing this!

**Comment by ridiculousfish** [comment]
Actually I want to track in #2037. Closing as dup of that.
