### ISSUE TITLE
Recursion is limited to 125 times?

### ISSUE THREAD

**Issue by bucaran** [fish-shell/fish-shell#2134]
Just wondering why this could happen:

```fish
function len
  if set -e argv[1]
    if set -q argv[1]
      echo (len $argv) + 1 | bc
    else
      echo 1
    end
  end
end
```

```fish
len 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3

$ 124
```

But if I add one moreth (125th), it breaks like this:

```fish
fish: An error occurred while setting up pipe
pipe: Too many open files
(standard_in) 2: parse error
...
```

It seems this is due how fish handles recursion. How could I make this work without losing the recursive algorithm?

**Comment by ridiculousfish** [comment]
You're hitting the limit on open file descriptors, since each call creates a new pipe. I think we also have a hard limit `FISH_MAX_STACK_DEPTH` which is 128. Recursion is not exactly natural in shell scripts.

**Comment by bucaran** [comment]
Gotcha. Thanks @ridiculousfish!
