### ISSUE TITLE
"enumeration not supported on hosts"

### ISSUE THREAD

**Issue by plttn** [fish-shell/fish-shell#2137]
This is probably an edge case due to cygwin (2.0.4(0.287/5/3)), but using `ssh` and tab-completing spits out a few `Enumeration not supported on hosts` before printing usernames and hostnames.

fish, version 2.1.1

**Comment by plttn** [comment]
Issue was actually having data in my hosts file (unchecky). I'm curious, how often is hard coding stuff in hosts actually that relevant that it's in `__fish_print_hostnames` (my messy solve was to just override that function and remove that bit).

**Comment by zanchey** [comment]
We use it sometimes to fake up virtualhosts (and because we run NFS we also have lots of hosts defined in `/etc/hosts`, although they are in DNS as well).

**Comment by zanchey** [comment]
This is a limitation of Cygwin - `getent hosts` produces that error message.

**Comment by plttn** [comment]
Figured it was a cygwin issue, I'll just leave that custom function patch
until I get around to making a PR to turn that off on cygwin.

**Comment by bonds** [comment]
I'm still encountering this bug on OpenBSD. I'm working up a PR to fix it.
