### ISSUE TITLE
Any sudo command errors.

### ISSUE THREAD

**Issue by sky-shiny** [fish-shell/fish-shell#2146]
If I run 
 
    sudo htop 

I get     

    Unsupported use of '='. To run '$argv' with a modified environment, please use 'env pip=pip $argv…' in function 'sudo'
	called on standard input
	with parameter list 'su'

I am running fish, version 2.2b1-29-g18d7465, on OSX.

**Comment by ridiculousfish** [comment]
Probably `htop` invokes `$SHELL` with sh-script. Is `htop` a script? If so are you able to check what it's doing, or post its source?

**Comment by zanchey** [comment]
> function 'sudo'

I suspect this is the problem - what does the output of `functions sudo` show?

@sky-shiny mentioned on IRC that this happens with any command, not just `htop`.

**Comment by sky-shiny** [comment]
Yup, that's wierd. 
   
    $ functions sudo 
 
    function sudo
	    pip=pip $argv;
    end

**Comment by sky-shiny** [comment]
functions -e sudo 

Sudo's back!   Where did that function come from?

**Comment by ridiculousfish** [comment]
That's terrifying

**Comment by ridiculousfish** [comment]
Also nice catch @zanchey!

**Comment by zanchey** [comment]
:iiam:

My guess is that at some stage you ran `alias sudo pip=pip` instead of `alias pip="sudo pip"`.

**Comment by sky-shiny** [comment]
That kinda makes sense.  Not in my history, but I'll close this off as a user error.  That was fun :8ball: .
