### ISSUE TITLE
"Last Output" completion?

### ISSUE THREAD

**Issue by nyarly** [fish-shell/fish-shell#2147]
This might be a complete pipe dream but would it be possible to use tokens from the output of the last command as possible completions?

I'm thinking, for instance:
```
> git status | grep '^??'
?? a/file/you/didnt/add.txt
> git add didnt<TAB>
```

Other uses involve acting on items returned by various search and query commands - install a package from the last search, or edit a file from the last `ack` etc. 

Currently I use mouse or tmux commands to select these tokens, but being able to add completions for them would be 100% better.

**Comment by ridiculousfish** [comment]
This sounds like a powerful feature, but unfortunately it breaks the terminal model, where the program output does not go through the shell, and so the shell cannot read the output.

**Comment by nyarly** [comment]
But... fish is *magic!* Can't it do _anything?_

Seriously, though, the terminal gets the output, and the shell knows when programs run - is that about right? So, best case, would be some sort of hooks in fish around submitting a command, and the resulting process completing (leaving aside backgrounded jobs), and a companion script in the terminal to capture output to a tempfile or something?

**Comment by zanchey** [comment]
Full-stack is very in right now :-)

**Comment by ridiculousfish** [comment]
One possibility is integration with the terminal itself. It's not unreasonable for the terminal to report on output to the shell, though there would be security concerns.

**Comment by nyarly** [comment]
I may add to my TODO list a frankstein of a `--on-variable "_"` or `--on-event fish_prompt` and some urvxtperl thing to capture (some?) command output, and then `complete ... -a (cat last_out)` If I get around to it, I'll let you know how it goes.

**Comment by ptbrowne** [comment]
Today I wanted this kind of completion and since it is not available I ended up coding a little function that numbers the output of a command and assign each line to an environment variable so that I can use it easily.

```fish
function enum
        set i 0;
        while read x
            set -gx "$i" $x
            echo $i $x
            set i (math $i + 1)
        end
end

This allows me to do
```
$  touch a b c d e f
$  ls | enum
0 a
1 b
2 c
3 d
4 e
5 f
$ example   open $1
```

This is not perfect since I have to remember to add `enum` but I may use it in aliases for example.
Maybe it can be of some use to some people.

**Comment by faho** [comment]
Sorry, but I don't think this is going to happen. It's a rather invasive change for a small feature.

**Comment by magemore** [comment]
I think it's great time saving feature maybe add ability to insert "enum" at the end of each executed command automatically
