### ISSUE TITLE
Cannot create a function called 'exit'

### ISSUE THREAD

**Issue by brettanomyces** [fish-shell/fish-shell#2148]
I would like to implement a function called 'exit' so I can have different behavior on exit if fish is running from inside Neovim or not, ultimately the function would called the default exit command. Unfortunately it is not possible to do so because the default exit cannot be called via 'command exit'.

**Comment by zanchey** [comment]
You probably want `builtin exit`.

**Comment by ridiculousfish** [comment]
You can also define a function that fires on exit, like so:

    function exit_handler --on-process-exit %self
        echo Bye!
    end

**Comment by brettanomyces** [comment]
Awesome! Thanks you both the suggestions.
