### ISSUE TITLE
Annoying warning "unable to lock universal variable file" on NFS home

### ISSUE THREAD

**Issue by languitar** [fish-shell/fish-shell#2149]
I have a setup where my home directory is located on an NFS server. I constantly see warnings like:
```
Unable to lock universal variable file '/homes/xxx/.config/fish/fishd.b8ca3a83e1b9': Bad file descriptor
```
From having a quick look at the source code it seems that locking is actually expected to fail in certain NFS configurations. It would be nice if the shell wasn't spammed with these messages if they are expected.

**Comment by ridiculousfish** [comment]
EBADF is surprising. I guess you're on Linux - do you know what kernel version your client has?

**Comment by languitar** [comment]
```
jwienke@cinnabar:/homes/jwienke$ uname -a
Linux cinnabar 3.18.1-tf1-ll #1 SMP PREEMPT Fri Dec 19 16:49:31 CET 2014 x86_64 x86_64 x86_64 GNU/Linux
jwienke@cinnabar:/homes/jwienke$ dpkg -l | grep nfs
ii  libnfsidmap2:amd64                                          0.25-5                                              amd64        NFS idmapping library
ii  nfs-common                                                  1:1.2.8-6ubuntu1.1                                  amd64        NFS support files common to client and server
jwienke@cinnabar:/homes/jwienke$ fish
Unable to lock universal variable file '/homes/jwienke/.config/fish/fishd.b8ca3a83e1b9': Bad file descriptor
Unable to lock universal variable file '/homes/jwienke/.config/fish/fishd.b8ca3a83e1b9': Bad file descriptor
jwienke@cinnabar ~> ll /homes/jwienke/.config/fish/fishd.b8ca3a83e1b9
-rw------- 1 jwienke ai 1.3K Jun 25 00:06 /homes/jwienke/.config/fish/fishd.b8ca3a83e1b9
jwienke@cinnabar ~> cat /homes/jwienke/.config/fish/fishd.b8ca3a83e1b9
# This file is automatically generated by the fish.
# Do NOT edit it directly, your changes will be overwritten.
SET __fish_classic_git_prompt_initialized:\x1d
SET __fish_init_1_50_0:\x1d
SET fish_color_autosuggestion:555\x1eyellow
SET fish_color_command:005fd7\x1epurple
SET fish_color_comment:red
SET fish_color_cwd:green
SET fish_color_cwd_root:red
SET fish_color_error:red\x1e\x2d\x2dbold
SET fish_color_escape:cyan
SET fish_color_history_current:cyan
SET fish_color_host:\x2do\x1ecyan
SET fish_color_match:cyan
SET fish_color_normal:normal
SET fish_color_operator:cyan
SET fish_color_param:00afff\x1ecyan
SET fish_color_quote:brown
SET fish_color_redirection:normal
SET fish_color_search_match:\x2d\x2dbackground\x3dpurple
SET fish_color_selection:\x2d\x2dbackground\x3dpurple
SET fish_color_status:red
SET fish_color_user:\x2do\x1egreen
SET fish_color_valid_path:\x2d\x2dunderline
SET fish_key_bindings:fish_default_key_bindings
SET fish_pager_color_completion:normal
SET fish_pager_color_description:555\x1eyellow
SET fish_pager_color_prefix:cyan
SET fish_pager_color_progress:cyan
SET fish_user_paths:/homes/jwienke/\x2elocal/bin\x1e/usr/local/sbin\x1e/homes/jwienke/local/bin\x1e/usr/local/bin\x1e/homes/jwienke/\x2egem/ruby/1\x2e9\x2e1/bin
```

**Comment by zanchey** [comment]
I'm not sure if this is related to NFS locking. I haven't been able to reproduce this with NLM locking on and local locking off, NLM locking off and local locking on, or both NLM & local locking off.

The output of `strace fish` might show what is going on.

**Comment by languitar** [comment]
Here is the strace output: https://gist.github.com/languitar/0862593dbda9219d62d1

**Comment by zanchey** [comment]
Could you also show the output of mount | grep homes just in case there is a funny mount option affecting things?

**Comment by languitar** [comment]
```
fileserver.XXXXX:/export/XXXXX/homes/jwienke on /homes/jwienke type nfs (rw,nosuid,sloppy,vers=4,addr=SOMEIP,clientaddr=SOMEIP)
```

**Comment by zanchey** [comment]
I tried with NFSv4 (I didn't know people actually used that!) but still haven't managed to reproduce the problem. I wonder if this is because (from 2.6.12 onward) Linux translates exclusive `flock()` locks into whole-file `fcntl` write locks.

So fish opens the file for reading but then tries to get a write lock, which returns EBADF (at least that's what my reading of the kernel source says).

[Hooray](http://0pointer.de/blog/projects/locking.html).

**Comment by languitar** [comment]
Any way I can provide more information to find out what's going on?

**Comment by zanchey** [comment]
OK, I didn't actually test this properly - need to `set -U` something for the error message to appear.

I'm pretty sure the behaviour described above is what we're hitting. The minimal test case is https://gist.github.com/zanchey/64949b7e728f3fe04d9a - on NFSv3 this works fine and on NFSv4 it fails with EBADF.

I think the easiest way to work around this bizarre behaviour on Linux is to open the lock file for writing, which fixes the problem in my test case. Maybe going to fcntl-style locking is useful? I don't think we have the lock file open from more than one file descriptor per process which means that it *should* be safe to use `fcntl`.

**Comment by ridiculousfish** [comment]
Ooh, nice test case!

Opening the file for writing should be fine. I think we should also just remove the error message. If the lock fails, then simultaneous writes may be lost, but there won't be corruption.

This seems like something we ought to put into 2.2 - do you agree?

**Comment by zanchey** [comment]
Yes, I think so.

**Comment by zanchey** [comment]
Added to Integration_2.2.0 as e60db80 - @languitar, if you are able to test a compiled build from the Integration_2.2.0 branch that would be great, but I can confirm that it fixes things on my newly-NFSv4-ised machine.

**Comment by languitar** [comment]
Yes, warnings are gone with this branch.
