### ISSUE TITLE
gpg bugs

### ISSUE THREAD

**Issue by pickfire** [fish-shell/fish-shell#2150]
I use fish version 2.1.2. When I am completing `gpg --armor --export `, it shows:
```
Autistici\ /\ Inventati\ Staff\ \(www.autistici.org\ /\ www.inventati.org\)   (info@autistici.org)
Autistici\ /\ Inventati\ Staff\ \(www.autistici.org\ /\ www.inventati.org\),  (info@autistici.org)
...
```
I am using `Linux alarmpi 4.0.6-1-ARCH #1 SMP PREEMPT Tue Jun 23 20:05:34 MDT 2015 armv7l GNU/Linux`.

###### Status: **not fixed**

**Comment by zanchey** [comment]
The GnuPG completions need some work.

**Comment by pickfire** [comment]
When completing `gpg --keyserver pgp.mit.edu --send-keys` or `gpg --keyserver pgp.mit.edu --recv-keys`, it shows:
```
Autistici\ /\ Inventati\ Staff\ \(www.autistici.org\ /\ www.inventati.org\)   (info@autistici.org)
Autistici\ /\ Inventati\ Staff\ \(www.autistici.org\ /\ www.inventati.org\),  (info@autistici.org)
...
```
And it should be something like:
```
Autistici\ /\ Inventati\ Staff\ \(www.autistici.org\ /\ www.inventati.org\)  15FAD874
```

###### Status: not fixed

**Comment by pickfire** [comment]
No completion for `gpg -k` and `gpg -K` and a lot more.

###### Status: **not fixed**

**Comment by faho** [comment]
a265ee6f6f794a54b82530fa692d4890cfc3d7d2 should offer some improvement.

**Comment by faho** [comment]
Please try again and scream if it's gotten worse, open another issue with specifics if more fixes are needed and sing my praises if it's now perfect. Doesn't matter if you can sing or not since it won't be.

**Comment by pickfire** [comment]
I think I should be ready for a singing marathon, let me drink some water first.

In My Humble Opinion, I suggest that `gpg --send-keys` should put the `908695ADCBE90CAD` as grey and `(Autistici / Inventati Staff (www.autistici.org / www.inventati.org) <info@autistici.org>)` as the main suggestion. And the list does seems long. Good work.

**Comment by pickfire** [comment]
I think I have found another bug. When you *complete* `gpg --import`, it shows the keys you have and not the key file you need to import.

**Comment by faho** [comment]
As always, the man page sucks - are you saying `gpg --import` expects a filename for a key file?

That's easy to complete, of course.

**Comment by pickfire** [comment]
Yeah. Good luck and have a nice day!

**Comment by faho** [comment]
See 67ed58b0baa3aed96daca97a9263e55964fef49f.
