### ISSUE TITLE
Allow completing `$argv` when writing functions

### ISSUE THREAD

**Issue by Lucretiel** [fish-shell/fish-shell#2154]
When writing a function, $argv isn't autocompleted:

```
function foo
    echo $arg<tab>   ->   echo $
```

Should we consider allowing $argv to be autocompleted in this case? I can see the case against it- technically, the variable doesn't exist yet, so it'd be a very special case. I think it's worth it, though.

**Comment by floam** [comment]
I like the idea.

**Comment by krader1961** [comment]
Sorry, no. You can complete other variables that actually exist at the time you start defining a new function. If you first do `set argv x` then the completion works as expected. The complexity added by special-casing `$argv` while defining a function cannot be justified by the added convenience.
