### ISSUE TITLE
Ability to rename abbr

### ISSUE THREAD

**Issue by ElijahLynn** [fish-shell/fish-shell#2155]
I may be missing something obvious but I can't find a way to simply rename an abbreviation. 

I have to abbr -e name and then add it back again.

Any tips here?

https://github.com/fish-shell/fish-shell/issues/731

**Comment by ridiculousfish** [comment]
Just nobody's done it yet. I think it would be reasonable to add.

**Comment by ElijahLynn** [comment]
Oh, great, that would be nice! Thanks
