### ISSUE TITLE
Cannot get breakpoint to work

### ISSUE THREAD

**Issue by ElijahLynn** [fish-shell/fish-shell#2157]
I have been trying to get `breakpoint` to work by putting it in the function on line 1, then calling the function. I do not get a prompt while running the function. Should I?

**Comment by ridiculousfish** [comment]
What version of fish are you using? This works for me on master:

    > function do_breakpoint ; echo before ; breakpoint ; echo after ; end
    > do_breakpoint
    before
    >

Control-D to continue with the function.

**Comment by ElijahLynn** [comment]
Thanks for that example, okay it was working. Your example taught me how it works. I think I was expecting some more visual indicator of what breakpoint line number I was on. That would be a good example for the docs.

**Comment by ridiculousfish** [comment]
It would be nice to display some sort of indicator.

**Comment by zanchey** [comment]
I'm going to mark this as a duplicate of #1310 for now, and we can track there.
