### ISSUE TITLE
Offline documentation for fish-shell

### ISSUE THREAD

**Issue by nitishch** [fish-shell/fish-shell#2159]
Entire `bash` documentation can be found offline using `man bash`. Similarly, is there any way for accessing offline documentation of `fish-shell`?

**Comment by ridiculousfish** [comment]
Yes, use `man` to access fish's man pages. For example `man set`.

**Comment by zanchey** [comment]
You can also use `help` to open the manual in your web browser.

**Comment by pickfire** [comment]
Does `man` include the **full** documentation?

**Comment by nitishch** [comment]
I installed `fish-shell` from this repo but I cannot access `man` pages. There is no man page for `set` installed. As for using `help`, when I try `help set` it tries to open http://fishshell.com/docs/2.2b1-29-g18d7465-dirty/index.html but it encounters a 404 error.

**Comment by pickfire** [comment]
How did you install `fish-shell`?

**Comment by zanchey** [comment]
Make sure you have Doxygen installed (see the README) if you are building from source, or use a [nightly build if you are on Linux](https://github.com/fish-shell/fish-shell/wiki/Nightly-builds).

**Comment by nitishch** [comment]
Yup. I had Doxygen installed but it was 1.8.6. README says the project requires >= 1.8.7.
