### ISSUE TITLE
So, is 2.2.0 "released" or something like GM candidate?

### ISSUE THREAD

**Issue by geoff-codes** [fish-shell/fish-shell#2163]
Its in the latest "release", but not on the website, and not tagged "latest release".

± I'm asking whether I can/should bump the homebrew formula yet.

**Comment by ridiculousfish** [comment]
No, we still have a few fixes trickling in.

**Comment by zanchey** [comment]
Also, the homebrew formula should be based off a tarball, not off the Github release tag. Otherwise we end up with #1953, complaints about the documentation not being accessible, etc.

I've deleted the tag upstream for now.

**Comment by Globegitter** [comment]
@geoff-codes seems like it is released now. Would be great to see updated on homebrew.

**Comment by zanchey** [comment]
It's already up on Homebrew!

**Comment by geoff-codes** [comment]
:wink:
