### ISSUE TITLE
parser: should not interpret % universally as jobspec

### ISSUE THREAD

**Issue by geoff-codes** [fish-shell/fish-shell#2164]
Fish, I believe, is the **only** shell with this behavior:

``` fish
~> printf %s foo
664⏎
```

In the unlikely even the expected behavior is not obvious, it is:

``` bash
$ printf %s foo
foo⏎
```

I've checked every Korn-ish shell I can think of, _and_ [t]csh, where this `%` business came from in the first place.

It also seems like very "old parser" behavior to me; if a matching process isn't found, everything aborts and you get an insuppressible error message.

This not just a theoretical problem, I'm opening an issue about it because [it has recently come up](http://stackoverflow.com/questions/27652458/whats-the-best-way-to-embed-a-unicode-character-in-a-posix-shell-script?answertab=votes#tab-top).

**Comment by krader1961** [comment]
This is seriously FUBAR behavior. I just ran a bunch of `printf %a foo`, `printf %b foo`, etc commands and most of them printed seemingly random process IDs. A few resulted in errors like this:

```
$ printf %e foo
Unable to find a process 'e'
fish: printf %e foo
              ^
```

That is from `expand_pid()` in *src/expand.cpp*.

**Comment by krader1961** [comment]
Closing as a dup of #4230 where we are discussing how to improve this for the fish 3.0 release.
