### ISSUE TITLE
Output without newline is swallowed

### ISSUE THREAD

**Issue by nitishch** [fish-shell/fish-shell#2167]
The following command doesn't work in my installation of fish-shell:
```printf "%s" hello```

However this works:
```printf "%s\n" hello```

Actually this is not an issue with printf. `echo "hello"` works but `echo -n "hello"` doesn't work. So if the output doesn't contain a trailing newline, it is not printed.

I tried to debug this using `gdb fish`. In both with-newline and without-newline versions of printf , at `common.cpp` line `627`, appropriate output is printed to `stdout`. If `fish` is run under `gdb`, "hello" is printed in both the cases. But without `gdb`, for some reason I don't understand, "hello" doesn't appear in no-newline case and just the fish-prompt appears.

**Comment by ridiculousfish** [comment]
What OS and terminal are you using?

**Comment by nitishch** [comment]
Output of `uname -a`:

    Linux nitish 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:28:41 UTC 2015 i686 i686 i686 GNU/Linux

Terminal:

This problem happens in `gnome-terminal`, `xterm`, and also the tty accessed using `Ctrl-Alt-F1`

**Comment by nitishch** [comment]
Does this happen in other installations too or just in mine?

**Comment by zanchey** [comment]
I haven't been able to reproduce this either on 2.2b1 or on 2.1.1, with both single line and multiline prompts.

**Comment by pickfire** [comment]
I can't reproduce this in 2.1.2 either.

**Comment by faho** [comment]
I can't reproduce in 2.2.0 (on archlinux) either, not in konsole or xterm.

@nitishch: Do you still experience this?

**Comment by faho** [comment]
We can't reproduce, so it's possibly a fluke. @nitishch: If you ever figure this out, give us a call!
