### ISSUE TITLE
i3 status returned error

### ISSUE THREAD

**Issue by pickfire** [fish-shell/fish-shell#2169]
Look at the top right notification corner.

![2015-07-07-183806_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/8544372/56503c4e-24d7-11e5-9d19-c9b88926d0d6.png)

Maybe it is related to:
```
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
```
As `newsbeuter` does not work too because I had change the shell to `fish`.

**Comment by ridiculousfish** [comment]
It says "status_command process exited unexpectedly". Sounds like a bug in status_command?

**Comment by pickfire** [comment]
No, it is not a bug. It works with `zsh`. And it also seems that I cannot `set -U PATH "/usr/local/bin:/usr/bin:/home/ivan/.fzf/bin"` even when I replace `:` with ` `. `export` does not work too. This is what shows up:
```
set: Warning: path component /usr/local/bin:/usr/bin:/home/ivan/.fzf/bin ma
set: No such file or directory
set: Did you mean 'set PATH $PATH /usr/bin:/home/ivan/.fzf/bin'?
```

**Comment by ridiculousfish** [comment]
Probably what's going on is that `status_command` is trying to run POSIX code in `$SHELL` or something, which doesn't work with fish.

Don't try to set PATH as a universal variable. [Here is our new documentation](http://fishshell.com/beta/docs/current/tutorial.html#tut_path) on the best way to set PATH.

**Comment by pickfire** [comment]
After `set -U fish_user_paths /usr/local/bin /usr/bin`, `i3status` work. But `newsbeuter` still doesn't work:
```
setlocale failed: No such file or directory
```
And `locale` output:
```
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
I want to set:
```
# Enforce correct locales from the beginning:
# LC_ALL is unset since it overwrites everything
# LANG=en_GB.UTF-8 is used, except for:
# LC_MESSAGES=C never translates program output
unset LC_ALL  # Since it overwrites everything.
export LANG='en_GB.UTF-8'
export LC_MESSAGES=C  # Never translates program output.
```
Thanks for helping me to get `i3status` working. But I think that `locale` should not get any error or else some application will have problem running.

**Comment by pickfire** [comment]
Thanks. I think this is solved.
