### ISSUE TITLE
(Re)-binding \cj breaks enter key

### ISSUE THREAD

**Issue by chdorner** [fish-shell/fish-shell#217]
I wanted to have vim key mappings instead of the arrows with the following commands:

```
bind \ch 'backward-char'
bind \cl 'forward-char'
bind \ck 'up-or-search'
bind \cj 'down-or-search'
```

Which seems to work great, except that because of re-binding of the `\cj` key combination, the `enter` key stopped working.

Is that intended behavior or a bug?

**Comment by michaeljones** [comment]
+1, I've experienced the same situation coming to fish with a history of vim. I like home row key bindings and it has been possible one way or another in zsh & tcsh.  I can see there is a clear argument for them being indistinguishable but if it is possible in any standard way then it just makes things more flexible, I think.

**Comment by krader1961** [comment]
The reason \cJ seems to insert the same thing as [enter] is because the tty is in cooked mode with icrnl enabled -- that causes the tty driver to map carriage-return (aka \cM and [enter]) to newline (aka \cJ). See http://stackoverflow.com/questions/14615717/how-can-vim-tell-the-difference-between-ctrl-j-and-lf

I vote that fish disable icrnl mode so that \cJ can be rebound.

**Comment by krader1961** [comment]
P.S., I'm working on a change to implement this (i.e., separate \cJ from \cM) on UNIX. TBD is what, if anything, needs to change for MS Windows.

**Comment by michaeljones** [comment]
Thanks for the update! You've helped me realise that that is what I'm seeing as well. I think it has been sufficient for me on other shells to distinguish between \cJ and \cM which means being able to distinguish between Enter and \cJ as well as they don't represent the same input.

I saw that stackoverflow question too but unfortunately I am not wise in the lingo of terminal programming. I would welcome any help on this and would be happy to try to test something if you have a fork I could look at. Thanks again!

**Comment by faho** [comment]
>I vote that fish disable icrnl mode so that \cJ can be rebound.

@krader1961: Doesn't that just _move_ the problem to \\cm? At least that's how I understood the SO answer.

Of course \\cj is probably slightly more usual, what with vi-bindings and all, but it's not a real solution.
