### ISSUE TITLE
Better default man colour

### ISSUE THREAD

**Issue by pickfire** [fish-shell/fish-shell#2170]
The default `man` pages for `fish` is very hard to read. The **right** terminal in the image is `fish` and the **left** terminal is `zsh` with **prezto**. I hope that `fish` could have a better `man` page just like the one on the **left** below **by default**:

![2015-07-07-211133_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/8546740/c2c1f2a4-24ec-11e5-9f43-976494d40dcf.png)

**Comment by kcousot** [comment]
It seems that `most` is used as man pager in the left terminal.
Setting the environment variable `MANPAGER` accordingly should give you what you're looking for.

**Comment by pickfire** [comment]
I had checked, `most` is not installed, `less` is. And `MANPAGER` is not set, but the `PAGER` is set to `less`.

**Comment by kcousot** [comment]
It makes sense, as `less` is much more common than `most`.
Take a look at [this](https://wiki.archlinux.org/index.php/Man_page#Using_less_.28Recommended.29).

**Comment by pickfire** [comment]
Thanks for adding [that](https://wiki.archlinux.org/index.php/Man_page#Using_less_.28Recommended.29) to **archwiki**.

**Comment by kcousot** [comment]
I [am not](https://wiki.archlinux.org/index.php?title=Man_page&type=revision&diff=345111&oldid=335782) the one who added it on archwiki.
About making these settings default : it's not my call, wait for more replies.

**Comment by zanchey** [comment]
some notes on this in #600

**Comment by pickfire** [comment]
What is the conclusion? Will the **default** `man` colour change?

**Comment by ridiculousfish** [comment]
They do look nicer, but they may look worse with certain terminal colors. Does anyone want to put together a set of screenshots of what the colors would look like with different backgrounds and default text colors?

**Comment by pickfire** [comment]
Post those screenshots here? I only have the screenshot with solarized dark in st.

**Comment by floam** [comment]
Here.

**Comment by floam** [comment]
I think any colors should simply be set in terms of the existing variables. For instance, a good color to accompany bold stuff might be `fish_color match` or `fish_color_command` given how bold is typically used in man pages. So this should be unlikely to look bad. 

You can do `env LESS_TERMCAP_DEBUG=1 man fish` to check what termcap codes are in a man page to help figure out what to [translate.](http://unix.stackexchange.com/questions/108699/documentation-on-less-termcap-variables). 

I just noticed something, though. Our manpages are terribly boring! I suspect we have Doxygen or something configured to not turn <tt>'s into what we want on commands, arguments, etc. There is not much to colorize.

<img width="433" alt="screenshot 2016-07-12 at 12 01 02 am" src="https://cloud.githubusercontent.com/assets/291142/16758096/8f533922-47c4-11e6-8efc-8e7d286e8311.png">
<img width="459" alt="screenshot 2016-07-12 at 12 01 34 am" src="https://cloud.githubusercontent.com/assets/291142/16758097/8f760024-47c4-11e6-8864-1a944206a9b9.png">

Not sure what switches to flip to change that.

**Comment by floam** [comment]
I'm guessing this had to be done due to us sometimes printing manpages directly to stdout in lieu of abbreviated usage information.

**Comment by faho** [comment]
>I'm guessing this had to be done due to us sometimes printing manpages directly to stdout in lieu of abbreviated usage information.

Don't think so - `__fish_print_help` is supposed to be used for that, which does send the man page through `nroff`.

**Comment by zanchey** [comment]
We definitely don't want to set these by default; we could consider extending themes from the color picker to these variables as well but I don't know that it can be done robustly.

**Comment by ian-h-chamberlain** [comment]
Hey, I guess this is an old issue but I came here looking to see why builtins' `--help` argument seems to display differently than my usual `man` commands:
```sh
# Seems to just use my default $PAGER instead of $MANPAGER
MANPAGER='sh -c "col -bx | bat -plman"' printf --help
```
vs
```sh
# Does what I expect
MANPAGER='sh -c "col -bx | bat -plman"' man printf
```

I found this issue by digging into the builtin `--help` arg and finding `__fish_print_help`... is this something I should file a separate issue for? The scope seems somewhat smaller than this issue (just respect user's `$MANPAGER` if set)?

**Comment by faho** [comment]
@ian-h-chamberlain These issues are barely connected so please file a new one, yes.

This is about setting a *color scheme*, you're asking about reading a separate setting variable for general pager things. The only connective tissue is that this one mentions `__fish_print_help`.

**Comment by faho** [comment]
I don't believe anyone has any inclination of doing this, and I don't believe it's really our place to do it. Might be an idea for a "plugin" thing.
