### ISSUE TITLE
Vi mode: wrong behavior for `w` and `e`

### ISSUE THREAD

**Issue by 5nizza** [fish-shell/fish-shell#2171]
Hey!

When press `e` in the normal model, the cursor should go to the last letter of the current word, not after it. 
See picture (left is correct, right is `fish`):

![press-e](https://cloud.githubusercontent.com/assets/928552/8553178/75d62042-2496-11e5-8995-e8d8501eb347.png)

Similarly, when press `w` in the normal model, the cursor should go to the first last letter of the next word, not before it:
See picture (left is correct, right is `fish`):

![press-w](https://cloud.githubusercontent.com/assets/928552/8553206/ae357bf4-2496-11e5-9fab-2fcaefa9ac02.png)

`fish, version 2.2b1`

**Comment by krader1961** [comment]
This was, mostly, fixed by commit 879ee61a30aa495456649e2b53714664264ff1bb.
