### ISSUE TITLE
GOPATH can't work

### ISSUE THREAD

**Issue by justmao945** [fish-shell/fish-shell#2172]
* system: Mac OS X 10.10
* fish shell: a5fabc6875747ca35a14f3d6f15f2ce6e608ba39 (latest master)
* problem: GOPATH is wrong, and the command `go` can't work for multiple paths

```
$ echo $GOPATH
/Users/jianjun/Source/go /Users/jianjun/Source/go2 /Users/jianjun/Source/go3

$ go env
GOPATH="/Users/jianjun/Source/go/Users/jianjun/Source/go2/Users/jianjun/Source/go3"
```

The right `GOPATH` for command `go env` should be paths separated by `:`
```
GOPATH="/Users/jianjun/Source/go:/Users/jianjun/Source/go2:/Users/jianjun/Source/go3"
```

But works well in version fish 2.1.2
Any ideas ?

**Comment by ridiculousfish** [comment]
This is the same issue as #2125. fish no longer tries to translate between colon-delimited strings and arrays, except for a very short whitelist. Any *PATH style environment variables that you set in config.fish, or as universal variables, will need to change. We should definitely document this in the relnotes if we haven't already.

**Comment by justmao945** [comment]
Got it. Thank you for your quick reply! :smile:

**Comment by ridiculousfish** [comment]
Thanks for filing this! Let's close as dup of #2125
