### ISSUE TITLE
Prompt not refreshing when calling `ls -latrh` with kebinding

### ISSUE THREAD

**Issue by endrebak** [fish-shell/fish-shell#2177]
I have the following `fish.config`:

```fish
function lslatrh
  eval "  ls -latrh" # eval just to add space so lslatrh does not enter the fish history
end

function fish_user_key_bindings
    bind \cs lslatrh
end
```

When I use the function by writing it out it works fine, but when I activate it with `CTRL-s` it does not print a prompt afterwards (but if you start typing it acts as if the prompt was there all along).

I'm sure I can fix this for myself with a simple hack, I just thought you might be interested in knowing.

Using `--HEAD` from `homebrew`, so `--version` is `fish, version unknown`

**Comment by pickfire** [comment]
I think you should use `alias` rather than `eval`.

**Comment by endrebak** [comment]
The error still occurs without the magic above to disable storing the command in history.

**Comment by ridiculousfish** [comment]
Key bindings do not automatically repaint the command line, for performance reasons. Try writing this as:

    bind \cs 'lslatrh; commandline -f repaint'

**Comment by endrebak** [comment]
Did not work, but now I know this is not a bug at least.

**Comment by ridiculousfish** [comment]
Odd, it worked for me.

**Comment by endrebak** [comment]
With the latest fish it works (ecstatic about the new vi mode btw!)

**Comment by ridiculousfish** [comment]
Ok, let's close. Thanks!
