### ISSUE TITLE
Add option to dereference symbolic links to type.fish

### ISSUE THREAD

**Issue by eush77** [fish-shell/fish-shell#2181]
Example usage:

```
$ type -p gcc
/usr/bin/gcc
$ realpath (type -p gcc)
/usr/bin/gcc-4.6
$ type -Dp gcc
/usr/bin/gcc-4.6
```

I often find myself wondering what file exactly will be executed, and I think this behavior deserves a shortcut.

**Comment by pickfire** [comment]
You can also use `which`.
