### ISSUE TITLE
Application not using set http_proxy

### ISSUE THREAD

**Issue by pickfire** [fish-shell/fish-shell#2182]
I have set **http_proxy** by `set -Ux http_proxy http://localhost:8123` but it seems that some applications doesn't use that variable. It is working on `zsh`.

**Comment by ridiculousfish** [comment]
Which applications don't use the proxy? How did you determine that? How are those applications launched?

**Comment by pickfire** [comment]
> Which applications don't use the proxy? How did you determine that? How are those applications launched?

Sorry, I forgot to be informative.

There are two application that cannot use the proxy which is [**`surf` browser**](surf.suckless.org) and [**`youtube-dl`**](https://github.com/rg3/youtube-dl/). I launched those applications with [**`dmenu`**]( tools.suckless.org/dmenu/).

I determine that **`surf` browser** by **looking at it status** which doesn't show `P`, `P` stands for proxy on.

I determine that `youtube-dl` is not using proxy by `lsof -i` which doesn't show the port I am using for proxy. By default it will show something like:
```
firefox  1130 ivan   72u  IPv4 1018033      0t0  TCP localhost:54709->localhost:8123 (ESTABLISHED)
mutt     7160 ivan    3u  IPv4  831956      0t0  TCP localhost:40187->localhost:versiera (ESTABLISHED)
```

**Comment by ridiculousfish** [comment]
Thanks for that. One possibility is that `dmenu` is not launched from fish, and therefore doesn't inherit the environment variable. How does `dmenu` get launched?

**Comment by pickfire** [comment]
I am using [**`i3` window manager**](http://i3wm.org/). After I `startx`, I can just search for an application with *Ctrl+D* and `dmenu` will pop up. The default **$SHELL** is `fish`.

![2015-07-12-174555_1600x900_scrot](https://cloud.githubusercontent.com/assets/4687791/8637322/4681239c-28be-11e5-80db-2e6c4e05e89c.png)

**Comment by ridiculousfish** [comment]
I'm not sure how the plumbing works, but my guess is that `dmenu` isn't launched through invoking `$SHELL`, although that wouldn't explain how it works via zsh.

**Comment by pickfire** [comment]
I forgot to say that `dmenu` knows the *$fish_user_paths* or maybe *$PATH*.

**Comment by ridiculousfish** [comment]
Oh, perhaps you're being bitten by #1374, which breaks any environment variables with colons. The just-now-released fish 2.2.0 has a fix for this.

**Comment by pickfire** [comment]
I am currently using the **master** branch which the problem is still there.

**Comment by pickfire** [comment]
It seems that [**`aria2`**](http://aria2.sourceforge.net/) which is **run in terminal emulator** does not seem to use the *$http_proxy* too.

**Comment by ridiculousfish** [comment]
Does `env` show that the variable has the value you expect?

**Comment by pickfire** [comment]
Neither `env` nor `set -q` show the variable.

**Comment by ridiculousfish** [comment]
Err, if `set -q` doesn't show the variable, then `echo` surely won't see it. How did you invoke `set -q`?

**Comment by pickfire** [comment]
![2015-07-13-134504_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/8643365/66384b96-2965-11e5-9429-1fe70356eb94.png)

**Comment by pickfire** [comment]
I have also found another weird thing about enviroment variables which is that I had `set` the `LESS_TERMCAP_mb` and others once.

`echo $LESS_TERMCAP_mb`, `env` and `set -q` shows no output, but when I use `man`, the colors seems to be the colors I had `set` once.

**Comment by ridiculousfish** [comment]
Note that `set -q` uses its exit status, so you would write that as `set -q http_proxy; echo $status` where 0 means it's set.

It sure looks like the variable is just not being exported. You can run `set -x` to see what fish thinks it's exporting. If you want to dig further, you can also look in `~/.config/fish/fishd.*` to see the list of universal variables and which are being exported (SET_EXPORT).

**Comment by pickfire** [comment]
`export` shows the variables of `$LESS_TERMCAP_mb` and `$http_proxy`. I think the application should use that variable, but why doesn't it use the variable `http_proxy` only in `fish` and not in `zsh`?

**Comment by ridiculousfish** [comment]
It looks like `export` without arguments is buggy. `env` is trustworthy, since it's a separate process.

**Comment by pickfire** [comment]
`env | grep http_proxy` shows an error and `env | grep LESS_TERMCAP_me` show no value. But I can get both value with `export | grep`. I set the value with `set -Ux http_proxy http://localhost:8123/`.

**Comment by ridiculousfish** [comment]
Err, why would `env | grep http_proxy` show an error? What error?

**Comment by pickfire** [comment]
Because there is no such thing (variable: http_proxy) in `env`.

**Comment by ridiculousfish** [comment]
Ok, then as I wrote it's probably just not being exported. If I had this problem, here are the things I would try:

1. Run `set -Ux http_proxy http://localhost:8123/` again. Does it give an error message about a global variable with the same name existing? (If so, that tells you what the problem is!) Now check the value of `env`. Does the variable appear there?
2. Check the contents of `~/.config/fish/fishd.*`. Does the variable appear in there with a `SET_EXPORT`?
3. Maybe universal variables are busted. Try setting just an ordinary global: `set -gx http_proxy http://localhost:8123/` Does it then appear in `env`?
4. In general try to determine the difference between this variable and other, successfully exported variables.

That's how I'd approach it!

**Comment by pickfire** [comment]
Thanks, it works when I `set -Ux http_proxy http://localhost:8123/` again. I notice that the **man** pages for `set` seems a bit **long** and `set --help` is the same with `man set` except the it only show the bottom part. And I don't know why `fish` need to differentiate between *-U* and *-g*.

**Comment by ridiculousfish** [comment]
Glad you got it working. `set --help` outputs the same information as `man help` except that `man` uses the pager; `set --help` just dumps it all in the terminal.

The difference between -U and -g is important! A global variable is specific to this session, but a universal variable (-U) is shared across all instances of fish, now and in the future.

**Comment by pickfire** [comment]
This is resolved, thanks. But I still have a few questions:

> Glad you got it working. set --help outputs the same information as man help except that man uses the pager; set --help just dumps it all in the terminal.

I hope that `set -h` can display the **minimal help** such as help from tab completion and not from the dumped man page as it is too long and not easy to read.

> The difference between -U and -g is important! A global variable is specific to this session, but a universal variable (-U) is shared across all instances of fish, now and in the future.

I think the docs should put a note that there is differences between `-U` and `-g`.
