### ISSUE TITLE
fish_config doesn't show current theme on start

### ISSUE THREAD

**Issue by alanruttenberg** [fish-shell/fish-shell#2184]
For example, by background is white, but when I start fish_config it shows as black

**Comment by ridiculousfish** [comment]
You mean the background color of the terminal? Sadly fish has no good way of determining that. The background color you can set in `fish_config` is purely for demo purposes; it doesn't affect the color used by your terminal.

**Comment by alanruttenberg** [comment]
oh, that's confusing. Well you could at least persist the background chosen in that interface so that the next time it opens it looks the same time as last...

**Comment by ridiculousfish** [comment]
Sure, seems reasonable.

**Comment by pickfire** [comment]
What is the progress on the fish theme chooser?

**Comment by ridiculousfish** [comment]
Nobody's worked on it since it was rewritten to be a theme chooser instead of a color picker. It's an Angular app and its UI needs love!

**Comment by krader1961** [comment]
@alanruttenberg Do you think this can be closed as a duplicate of issue #2421? Both issues are about the same thing AFAICT: the fact that fish does not (can not) set the terminal window background color but the documentation and web UI obscure that fact.

**Comment by faho** [comment]
Closing as duplicate of #2421 - if anything but the background is lacking, please open a new issue!
