### ISSUE TITLE
Vi prompt

### ISSUE THREAD

**Issue by petermehle** [fish-shell/fish-shell#2185]
It used to be possible to customize vi prompt with fish_vi_prompt, but it does not work anymore. Is there any other way?

**Comment by jusga** [comment]
The function `fish_vi_prompt` was eliminated in 767742c7e7ee53c8aa7950f928d551c63d69448f.

Since then you can customize the vi prompt by redefining the function `fish_mode_prompt`. It has its output prepended to the output of `fish_prompt`.

**Comment by ridiculousfish** [comment]
Yes, you now just customize your prompt by redefining`fish_prompt` whether or not you are in vi mode. Closing - let me know if you disagree!
