### ISSUE TITLE
2.2.0 is not the latest release in the releases page

### ISSUE THREAD

**Issue by Raimondi** [fish-shell/fish-shell#2187]
It appears on the top, I guess as a tag, but the "Latest release" is 2.1.2. I noticed it because I was preparing a ticket to get fish updated in MacPorts and I was having trouble fetching the 2.2.0 release. I can work around this and get an archive from the git tag, but I prefer to wait a little bit to use the released archive.

**Comment by ridiculousfish** [comment]
Yeah, we have to update the Releases page in github

**Comment by ridiculousfish** [comment]
Releases page updated: https://github.com/fish-shell/fish-shell/releases . Thanks for filing this.

**Comment by Raimondi** [comment]
Thanks for the prompt response. The new release of fish is currently available in MacPorts.
