### ISSUE TITLE
Auto-escape pasted text

### ISSUE THREAD

**Issue by SirCmpwn** [fish-shell/fish-shell#2188]
When I paste in some text (i.e. a URL with `?`) in it, fish should automatically escape it for me so I don't get the hugely annoying issue with substitution. I never even use `?` properly, the only purpose it serves is to frustrate me.

**Comment by ridiculousfish** [comment]
I can't find it at the moment, but we do have an issue that describes a technique for detecting when the terminal is pasting, which in principle allows us to fix this. We also have #1503.

We may also just want to remove the ? wildcard, I'm not sure it's valuable.

**Comment by zanchey** [comment]
#967 - bracketed paste.

**Comment by pickfire** [comment]
You can just `'text'` but I think that causes me a lot of trouble.

I think there is also some problem when pasting a few lines text with indentation. `fish` will then show a lot of spaces, I hope that fish will also auto elimate indentation when pasting.

**Comment by maxnordlund** [comment]
Since I wrote about [bracketed paste][1] in #967 I more and more like the idea of automatically wrapping pasted input in quotes.

This seams to be the most reasonable thing to do, since you probably want to use it as an argument to some command and quoting neatly solves any special characters issue. Further more it should be wrapped in single quotes to prevent accidental interpolation.

Seams good?

[1]: https://cirw.in/blog/bracketed-paste

**Comment by ridiculousfish** [comment]
I may be copying and pasting from the terminal itself, in which case quoting would change the meaning of what I pasted.

**Comment by maxnordlund** [comment]
This is very true, but I'm not sure how to detect that. This is also true if fish escapes some characters, but at least wrapping it in a string will be more visible thanks to the syntax highlighting for it.

**Comment by zanchey** [comment]
Maybe alter the behaviour depending on whether the paste is in command position or as an argument?

**Comment by oconnor663** [comment]
Pasting terminal commands is pretty common. For example, it's the standard way to [install Homebrew](http://brew.sh/). I think quoting whole commands would cause more problems than it solves. If we did quoting it would have to be special cased like @zanchey suggested, but special cases can be confusing:

    echo foo ; and _  <--- Is this an argument position, or the start of a command?

**Comment by oconnor663** [comment]
I'm a huge fan of implementing safe paste by default though, so that newlines in the paste don't cause commands to get executed immediately. I agree about removing `?` as a wildcard like @ridiculousfish said, unless anyone else finds they use it.

The issue with getting wildcards unintentionally interpreted inside a paste, that @SirCmpwn originally brought up, is particularly bad because fish actually *executes* the command, without giving it the right argument, which is scary and confusing for me at least. There's a case to be made for bash's behavior, where you pass non-matching wildcards as arguments unmodified. That would work well in @SirCmpwn's example with URLs, but poorly in cases like this:

    read_some_yaml *.yaml *.yml   # these cause errors if passed literally

I think the cleanest behavior would be to refuse to execute with any non-matching globs, and also provide some prefix commands to modify the wildcard behavior as appropriate, so that the user could get what they want on the second try without too much editing, something like:

    emptyglobs read_some_yaml *.yaml *.yml
    noglobs wget http://foo.com?bar

(See also https://github.com/fish-shell/fish-shell/issues/1920. The error messages from the non-matching globs could suggest these sorts of commands.)

**Comment by SirCmpwn** [comment]
What if we're just smart about it? If you have started typing a command and then hit paste, escape it.

**Comment by ridiculousfish** [comment]
We should be conservative here because this is a layering violation: interpretation of pasted content is up to the terminal emulator, not the shell. For example, iTerm2 warns when pasting text that contains newlines; that's handling the issue at the right place IMO.

**Comment by SirCmpwn** [comment]
Counterexample: weechat warns when pasting multiple lines.

I think we can do whatever gives the most convenience to the user and mitigate conflicts with flags that can change how "smart" the feature is.

**Comment by maxnordlund** [comment]
I been thinking a bit about this, and maybe the autocomplete machinery can be used to do the right thing. If you paste and it should autocomplete a command then it should not escape., e.g. `$> <PASTE>`, `$> sudo <PASTE>`, `$> foo; and <PASTE>`, etc.

But if it just needs some other argument, then escape it using single quotes, e.g. `$> foo <PASTE>`, etc.

**Comment by loops** [comment]
Hi there,

Zsh user here and I just decided to try Fish and got caught-out by a bad paste that would have been fine had I still been using Zsh.   I'll offer my two cents for whatever it's worth.

You don't want to do any quoting for a paste that you don't already do when the user is typing something by hand.  That's going to get in the way more often than it's helpful.

Just make sure that nothing gets executed by a paste.  All newlines should be interpreted as ALT-ENTER so the user has a chance to use the multiline editing before manually pressing ENTER to execute it.

If I'm typing a URL in by hand, I must single quote it before typing it out.  The exact same thing should be true when i'm pasting a URL, I must manually type a starting single quote before the paste -- or paste from a source that already has it single quoted.

The above should be easier to implement than auto-quoting and has the virtue of not getting in the way of users who actually intend wildcards to be interpreted properly after a paste.

Looking forward to learning more about Fish!
Cheers.

**Comment by SirCmpwn** [comment]
My experience with zsh is that it auto-escapes ? in URLs when pasted without an opening '.

**Comment by loops** [comment]
Hi SirCmpwn,

That's not my experience.  Zsh is ultimately configurable, so it's possible to do that with
plugins though:

<https://github.com/zsh-users/zsh/blob/master/Functions/Zle/bracketed-paste-magic>
   (plus the contributed url-quote-magic widget)

But there are still some bugs with it.  At least in my experience, life is much better without magic quoting.  There's nothing worse than magic you can't avoid.  At least with the simple solution you can quote things yourself.   Having to undo magic quoting you didn't ask for or want, is infuriating.

Just my opinion of course, and I can understand the opposite view.

**Comment by SirCmpwn** [comment]
My experience with zsh is installing oh my zsh and using it out of the box until I got tired of not having my favorite things from fish. So I'm not sure. That being said, I would prefer to have the ? escaped without having to type a '.

**Comment by maxnordlund** [comment]
One more interaction is to interpret the first backspace after a paste as "remove the surrounding single quotes". This means you can easily remove them if needed and should be easy to discover, following [the law of discoverability](http://fishshell.com/docs/current/design.html#disc).

**Comment by pickfire** [comment]
Sometimes it isn't safe to paste something that you had copied from website. http://thejh.net/misc/website-terminal-copy-paste

**Comment by SirCmpwn** [comment]
Not everything in your clipboard came from a website.

**Comment by pickfire** [comment]
@SirCmpwn, yeah, that's right, but some do come from website, I am just reminding.

**Comment by jakwings** [comment]
Some terminal emulator already do this (like iTerm2). Another solution from bash: C-x C-e (open the editor and paste your commands, then save and quit the editor)

**Comment by SirCmpwn** [comment]
Haha, that's even more difficult than typing " and then pasting.

**Comment by pickfire** [comment]
@jakwings, fish doesn't do that (I am using fish_vi_mode).

**Comment by jakwings** [comment]
@SirCmpwn Pasting unsafe code is always dangerous. Or you can do it like this: `curl -I (pbpaste)` or `curl -I (xsel --clipboard)`

@pickfire I know. Now there are `funced` and `function --no-scope-shadowing`, so I think that's possible.

**Comment by jakwings** [comment]
@pickfire I've derive a `run` function from `funced`, you can bind a shortcut to it:

```fish
function run --description 'Edit commands in an editor, then run them.'
  set -l editor
  if set -q VISUAL
    set editor $VISUAL
  else if set -q EDITOR
    set editor $EDITOR
  end
  set -l interactive

  if test -n "$editor"
    # Break editor up to get its first command (i.e. discard flags)
    set -l editor_cmd
    eval set editor_cmd $editor
    if not type -q -f "$editor_cmd[1]"
      echo "run: The value for \$VISUAL or \$EDITOR '$editor' could not be used because the command '$editor_cmd[1]' could not be found"
      return -1
    end
  else
    echo "run: Cannot find available editors in \$VISUAL or \$EDITOR"
    return -1
  end

  set tmpname (mktemp -t fish_run.XXXXXXXXXX.fish)
  if not eval $editor $tmpname
    echo "run: Editing failed"
    return -1
  end
  set -l stat 0
  if test -s $tmpname
    source $tmpname
    set stat $status
  else
    echo "run: Editing cancelled"
  end
  rm -f $tmpname >/dev/null
  return $stat
end
```

**Comment by SirCmpwn** [comment]
Pasting a URL I just copied from the Firefox navbar that has a ? in it is not dangerous. It's not your place to police users security know-how.

**Comment by jakwings** [comment]
Well, I suggested the possible ways before the need to over-engineering, not just opposing your idea. Everyone can make a pull request and try to tell how incompetent I am.

**Comment by mixmastamyk** [comment]
Hi, could we get the "bracketed paste" support in fish?  It looks like a better solution than messing with quotes that the user may/not want done.  Or perhaps it is independent of that, getting the bracketed paste would be a good first step to the full solution.  Details below:

https://cirw.in/blog/bracketed-paste

**Comment by ridiculousfish** [comment]
Yes, bracketed paste is tracked in #967

**Comment by mixmastamyk** [comment]
Nice to hear, thanks.

**Comment by faho** [comment]
>Yes, bracketed paste is tracked in #967

Since that's the case, let's close this as a duplicate.
