### ISSUE TITLE
Error upgrading Fish

### ISSUE THREAD

**Issue by rpacheco-aa** [fish-shell/fish-shell#2189]
I upgraded to the latest fish using Macports and in the end of the process was left with this error:

```
/opt/local/share/fish/functions/fish_prompt.fish (line 16): function prompt_pwd -V args_pre -V args_post --description "Print the current working directory, shortened to fit the prompt"
                                                            ^
in . (source) call of file '/opt/local/share/fish/functions/prompt_pwd.fish',
	called on line 14 of file '/opt/local/share/fish/functions/fish_prompt.fish',

in command substitution
	called on line 6 of file '/opt/local/share/fish/functions/fish_prompt.fish',

in command substitution
	called on line 26 of file '/opt/local/share/fish/functions/fish_prompt.fish',

in function 'fish_prompt',
	called on standard input,

in command substitution
	called on standard input,


       function ‐‐ create a function

   Synopsis
       function [OPTIONS] NAME; BODY; end

function: Type 'help function' for related documentation

Current functions are: .  N_  abbr  add2virtualenv  alias  cd  cdsitepackages  cdvirtualenv  contains_seq  deactivate  delete-or-exit  dirh  dirs  down-or-search  eval  export  fish_config  fish_default_key_bindings  fish_indent  fish_mode_prompt  fish_prompt  fish_sigtrap_handler  fish_update_completions  fish_vi_cursor  fish_vi_key_bindings  fish_vi_mode  funced  funcsave  grep  help  history  hostname  isatty  la  ll  ls  man  math  mimedb  mktmpenv  mkvirtualenv  nextd  nextd-or-forward-word  open  popd  prevd  prevd-or-backward-word  prompt_pwd  psub  pushd  rmvirtualenv  seq  setenv  sgrep  trap  type  umask  up-or-search  vared  vf  workon  
command: Unknown option '--'
/opt/local/share/fish/functions/type.fish (line 3): command -s -- $i
                                                    ^
in command substitution
	called on line 121 of file '/opt/local/share/fish/functions/type.fish',

in function 'type',
	called on standard input,
	with parameter list '-p command-not-found'

in function '__fish_command_not_found_setup',
	called on line 6 of file '/opt/local/share/fish/functions/fish_prompt.fish',
	with parameter list 'prompt_pwd'

in event handler: handler for generic event 'fish_command_not_found'


       command ‐‐ run a program

   Synopsis
       command [OPTIONS] COMMANDNAME [ARGS...]

command: Type 'help command' for related documentation

fish: Unknown command 'prompt_pwd'
/opt/local/share/fish/functions/fish_prompt.fish (line 6): prompt_pwd
                                                           ^
in command substitution
	called on line 26 of file '/opt/local/share/fish/functions/fish_prompt.fish',

in function 'fish_prompt',
	called on standard input,

in command substitution
	called on standard input,
```

**Comment by BastienDuplessier** [comment]
I had the same problem. I've solved it by replacing `prompt_pwd` by `command pwd` in my fish_prompt function.
I don't know why but it seems that `prompt_pwd` is broken.

**Comment by zanchey** [comment]
Did you try exiting the running shell and starting a new instance? This problem is usually caused when you have an old fish executable running and it accesses the new function files, which contain syntax that the old version does not support.

**Comment by rpacheco-aa** [comment]
Interestingly I took this opportunity to go back to zsh. Not my choice though :(

> On 13 Jul 2015, at 09:27, David Adam <notifications@github.com> wrote:
> 
> Did you try exiting the running shell and starting a new instance? This problem is usually caused when you have an old fish executable running and it accesses the new function files, which contain syntax that the old version does not support.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/fish-shell/fish-shell/issues/2189#issuecomment-120837227>.
> 

--
Rui Pacheco
rpacheco@appannie.com




-- 
*This email may contain or reference confidential information and is 
intended only for the individual to whom it is addressed.  Please refrain 
from distributing, disclosing or copying this email and the information 
contained within unless you are the intended recipient.  If you received 
this email in error, please notify us at legal@appannie.com 
<legal@appannie.com>** immediately and remove it from your system.*

**Comment by ridiculousfish** [comment]
I agree with zanchey's analysis. Probably the old fish is barfing on the new `-V` option to `function`. What does `echo $FISH_VERSION` output?

**Comment by cmicali** [comment]
I am getting the same error, confirmed fish v2.2.0

**Comment by cmicali** [comment]
Actually - I take that back!

```
cmicali@cm-imac /Users/cmicali$ echo $FISH_VERSION
2.1.0
cmicali@cm-imac /Users/cmicali$ fish -v
fish, version 2.2.0
cmicali@cm-imac /Users/cmicali$
```

**Comment by ridiculousfish** [comment]
I'm sure you already know this, but you have fish installed twice :) You can try `which -a fish` to see if it can find all of them.

**Comment by cmicali** [comment]
Thanks!  Comment updated w/ details on how to fix.

**Comment by rpacheco-aa** [comment]
Sorry, can’t test now. I had to move on to zsh.

> On 13 Jul 2015, at 20:00, ridiculousfish <notifications@github.com> wrote:
> 
> I agree with zanchey's analysis. Probably the old fish is barfing on the new -V option to function. What does echo $FISH_VERSION output?
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/fish-shell/fish-shell/issues/2189#issuecomment-121007467>.
> 

--
Rui Pacheco
rpacheco@appannie.com




-- 
*This email may contain or reference confidential information and is 
intended only for the individual to whom it is addressed.  Please refrain 
from distributing, disclosing or copying this email and the information 
contained within unless you are the intended recipient.  If you received 
this email in error, please notify us at legal@appannie.com 
<legal@appannie.com>** immediately and remove it from your system.*

**Comment by pickfire** [comment]
> Sorry, can’t test now. I had to move on to zsh.

Is it resolved now, show we close this issue?

**Comment by 0xicl33n** [comment]
i ran into this issue too and would like to let you know how i fixed it incase someone else has the same problem, in my case it was a problem upgrading fish AND oh my fish

First i removed fish:
`make uninstall`

Then i removed the fish config directory
`rm -rf ~/.config/fish/`

And lastly, reinstalled fish:
`make install`

Now i could reinstall omf with  no issues, working just fine!

**Comment by faho** [comment]
>But omf still wont install.. i dont know why.. i think its an omf problem..

Should be back now, there was an issue with omf being down. Which is why curl outputs "error:Not Found". Which is then piped into fish, which tries to execute it. Which is another reason not to do that `curl | sh` stuff.
