### ISSUE TITLE
Cannot install fish on RHEL/CentOS 6 - package "hostname" unavailable

### ISSUE THREAD

**Issue by ryenus** [fish-shell/fish-shell#2190]
The yum package `fish` cannot be installed on RHEL/CentOS 6, due to the following error:

> --> Processing Dependency: hostname for package: fish-2.2.0-2.1.x86_64
--> Finished Dependency Resolution
Error: Package: fish-2.2.0-2.1.x86_64 (shells_fish_release_2)
           Requires: hostname

However the command `/bin/hostname` is already available, which is probably part of the [`net-tools` package][1].

[1]: http://rpmfind.net/linux/rpm2html/search.php?query=%2Fbin%2Fhostname&submit=Search+...&system=centos

**Comment by zanchey** [comment]
Can't really win here, can we? I think it got broken out of that package in Fedora, which meant that we ended up with issue #2062.

I'll try and adjust the dependencies to make it require one or the other.

**Comment by brgmnn** [comment]
I have exactly the same issue updating `fish` on CentOS 6.5.

**Comment by mbains** [comment]
+1 same issue on opensuse 13.2.

**Comment by zanchey** [comment]
2.2.0-3.1 should fix this problem; when I can work out how to do the conditional dependencies properly I will add those, but I think that will mean installing half a dozen VMs to test.

**Comment by zanchey** [comment]
As a note for myself, http://rpmfind.net/linux/rpm2html/search.php?query=%2Fbin%2Fhostname&submit=Search+...&system=&arch= is a helpful index.

**Comment by zanchey** [comment]
https://en.opensuse.org/openSUSE:Build_Service_cross_distribution_howto#Detect_a_distribution_flavor_for_special_code is useful too. RPM doesn't have the either-or dependency statement that dpkg has, unfortunately.
