### ISSUE TITLE
vi mode: 'r' doesn't work.

### ISSUE THREAD

**Issue by newhook** [fish-shell/fish-shell#2191]
It should replace the character under the cursor.

**Comment by pickfire** [comment]
Yeah, the current **replace** *mode* in `fish_vi_mode` works just like **append**.

**Comment by faho** [comment]
Soo.. either this should be seen as a duplicate of #1417 (we don't have a _proper_ replace mode after all), or that one should be closed since we _do_ have a replace mode, just a broken one.

**Comment by pickfire** [comment]
Close this duplicate?

**Comment by zanchey** [comment]
Yep, let's track in #1417.
