### ISSUE TITLE
fish tries to interpret a wildcard from a parameter

### ISSUE THREAD

**Issue by Philipp-M** [fish-shell/fish-shell#2195]
fish tries to solve the following and fails to pass the wildcarded arguments:
>     ~> yaourt -Syau --ignore nvidia* --ignore lib32-nvidia* --ignore opencl-nvidia
>     No matches for wildcard “nvidia*”.
>     fish: yaourt -Syau --ignore nvidia* --ignore lib32-nvidia* --ignore opencl-nvidia
>                                 ^
>     No matches for wildcard “lib32-nvidia*”.
>     fish: yaourt -Syau --ignore nvidia* --ignore lib32-nvidia* --ignore opencl-nvidia
>                                                  ^

The result is that those 2 arguments won't be "ignored"

Btw. I'm using the newest git version.

**Comment by pickfire** [comment]
There may be a problematic alternative method which is to:
```
yaourt -Syau --ignore 'nvidia*' --ignore 'lib32-nvidia*' --ignore opencl-nvidia
```

**Comment by Philipp-M** [comment]
Yep this works, thanks for the tip. But I think nevertheless this should be handled, shouldn't it?

**Comment by pickfire** [comment]
Yeah, I don't know how to handle this, I think you should wait for @ridiculousfish response.

**Comment by ridiculousfish** [comment]
We've been using #683 to track this, which also explains how and why fish differs from bash here. Please feel welcome to jump in there.
