### ISSUE TITLE
Fish 2.2 breaks the `XDG_DATA_DIRS` environment variable

### ISSUE THREAD

**Issue by mandx** [fish-shell/fish-shell#2198]
With Fish 2.1.1, when running:

    $ env
    [...]
    XDG_DATA_DIRS=/usr/share:/usr/local/share
    [...]

But with Fish 2.2.0:

    $ env
    [...]
    XDG_DATA_DIRS=/usr/share/usr/local/share
    [...]

Which makes pretty much impossible running any GUI program from the command line:

    $ gedit
    (gedit:11047): GLib-GIO-ERROR **: No GSettings schemas are installed on the system
    fish: “gedit” terminated by signal SIGTRAP (Trace or breakpoint trap)

I install Fish from the [Ubuntu PPA](https://launchpad.net/~fish-shell/+archive/ubuntu/release-2)

**Comment by ridiculousfish** [comment]
Where is XDG_DATA_DIRS being set? The only way this could happen is if it's being set as a list from fish.

**Comment by mandx** [comment]
[This is the line](https://github.com/oh-my-fish/plugin-xdg/blob/master/xdg.load#L2). It is using a space as a separator (and was working fine on Fish 2.1.1). If I replace the space with a colon, the output from `env` shows the colon and I can run GUI apps again.

**Comment by ridiculousfish** [comment]
Yeah, this was a deliberate design decision from #1374. Basically fish has stopped using colons as array separators because it interacted badly with non-array things, like URLs. It was an oversight that this wasn't mentioned in the relnotes.

**Comment by mandx** [comment]
So in that line what be used as the separator? The decision makes sense, but the only way of making it work is using colons (which now are deprecated as list separators). I can edit the line or remove the oh-my-fish plugin, but this is bound to be a issue in some other script.

**Comment by ridiculousfish** [comment]
Yes, you should use colons explicitly: `set XDG_DATA_DIRS /usr/share:/usr/local/share`

**Comment by zanchey** [comment]
Is there anything more to do here? Add something to the documentation or release notes?

**Comment by ridiculousfish** [comment]
I'm not sure if we've documented the new interaction between lists and environment variables.

**Comment by faho** [comment]
I'd call https://github.com/fish-shell/fish-shell/blob/master/doc_src/index.hdr.in#L752 documentation:

>`fish` automatically creates arrays from the variables `PATH`, `CDPATH` and `MANPATH` when it is started. (Previous versions created arrays from *all* colon-delimited environment variables.)

**Comment by krader1961** [comment]
FYI, there have been several discussions about providing a way to treat such vars as lists inside of fish while allowing the user to define the delimiter to be used when exporting the var. See, for example, issue #436.
