### ISSUE TITLE
Consider reinstating implicit cd in some form

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#22]
This bug tracks reinstating implicit cd in some form. Implicit cd is where you can switch to a directory by just typing its path, without explicitly typing cd. It's as if you execute the directory.

In decreasing order of implicitness:

1. Restore it to its state in fish trunk: implicit cd is active and respects CDPATH
2. Implicit cd only works for the current directory. CDPATH would still be respected, but only when using cd explicitly.
3. Implicit cd only works for paths starting with a dot, slash, or tilde
4. Implicit cd only works for '..' (and perhaps ../.., etc.)
5. No implicit cd.

There's also potential to make this configurable in some way.

Feel free to pile on with your desires / perspectives.

**Comment by faho** [comment]
Is this still an issue? For me, typing "directory/" works and respects CDPATH.

**Comment by ridiculousfish** [comment]
The current rules are that it has to lead with dots, a slash, or have a trailing slash.

**Comment by faho** [comment]
From the [docs for the `cd` builtin](http://fishshell.com/docs/current/commands.html#cd):

>Note that the shell will attempt to change directory without requiring cd if the name of a directory is provided (starting with ., / or ~, or ending with /).

I'm not sure where else it should be documented, so I'm closing this now.

**Comment by fjolnir** [comment]
It would be nice if the following worked:
```
> set icloud "/Users/me/Library/Mobile Documents/com~apple~CloudDocs/"
> $icloud/Subdir/
fish: Variables may not be used as commands. In fish, please define a function or use 'eval $icloud/Development/'.
```
