### ISSUE TITLE
Line number not displayed for history command

### ISSUE THREAD

**Issue by cmoulliard** [fish-shell/fish-shell#2200]
On macosx, the command history of fish doesn't display the line number of the command 

Should be 

```
  556  cd ..
  557  ll
  558  mkdir apiman-docker
  559  cd apiman-docker/
  560  subl Dockerfile
```

but here is what we get

```
chmoulli@dabou ~/C/r/keycloak> history | more
history
pwd
ls -la
history --help
exit
history | more
man history
```

**Comment by pickfire** [comment]
By default, `history` does not numbered the numbers. I think you should use `nl` for this. You should just:
```fish
history | nl | less
```
Reference: http://stackoverflow.com/questions/9443694/how-to-add-line-number-for-a-output

**Comment by cmoulliard** [comment]
Thx for the trick. Adding an alias will help me
