### ISSUE TITLE
Completion like oh-my-zsh

### ISSUE THREAD

**Issue by sollidsnake** [fish-shell/fish-shell#2204]
Is it possible to have a completion like oh-my-zsh, where you can control the current selection using arrow keys, or `Ctrl-p`, `Ctrl-n`, `Ctrl-f`...?
![6](https://cloud.githubusercontent.com/assets/1778350/8685563/c7cb504c-2a55-11e5-9c1f-dfadf9a23587.png)

**Comment by ridiculousfish** [comment]
Yes, just hit tab a few times and you'll see it in action.

**Comment by dgutov** [comment]
`Ctrl-p` or `Ctrl-n` don't do anything there, though.

**Comment by ridiculousfish** [comment]
What should ctrl-p and ctrl-n do?

**Comment by dgutov** [comment]
Move back and forward between completions, I think. (Not a zsh user, though).

**Comment by ridiculousfish** [comment]
At first blush that seems rather awkward and non-discoverable. fish currently uses arrow keys, or tab and shift-tab.

**Comment by dgutov** [comment]
How so?

Outside of this completion widget, `Ctrl-p` does the same as up arrow, and `Ctrl-n` the same as the down arrow. It would make sense to make their bindings the same during completion, too.

Especially for those of us who avoid the arrow keys.

**Comment by ridiculousfish** [comment]
It looks like in fish, these control-p and control-n manipulate history:

    bind \cp history-search-backward
    bind \cn history-search-forward

Of course you can rebind them as you like.

**Comment by sollidsnake** [comment]
I'm aware of `Tab` and `S-Tab`, but oh-my-zsh goes one step beyond and adds another dimension. It works like this:
```
/ ls [tab][tab]
bin@         dev/         home/        mnt/         run/         tmp/       
boot/        etc/         lib@         opt/         sbin@        usr/       
core.11396   hawaii/      lib64@       proc/        srv/         var/       
core.20101   Hawaii/      lost+found/  root/        sys/                    
```
In the case above, zsh will highlight the first candidate -- `bin@`, and now I can press right arrow or `Ctrl-f` to go to `dev`, or down arrow or `Ctrl-n` to go to `boot`.

Did I make myself clear? If not I'll try to record a video showing how it works

**Comment by ridiculousfish** [comment]
Yes, this is what fish does too.
![screen shot 2015-07-14 at 3 30 37 pm](https://cloud.githubusercontent.com/assets/920838/8686685/4bb41506-2a3d-11e5-858c-6df60a44a1b1.png)

**Comment by sollidsnake** [comment]
That's strange, I don't have that behavior. Does it work out-of-the-box or it needs some configuration?

**Comment by dgutov** [comment]
@ridiculousfish 

> It looks like in fish, these control-p and control-n manipulate history:

Just like up and down arrows do. That's my counterpoint about "non-discoverability".

How do I rebind `Ctrl-n` and `Ctrl-p` to behave like arrows during completion.

@sollidsnake You should keep in mind that the behavior discussed here is new to fish 2.2.0.

**Comment by sollidsnake** [comment]
Oh, that's what I suspected. I already started building the latest version from the git repo. The current version in archlinux repo is not up to date

**Comment by ridiculousfish** [comment]
@dgutov Are you proposing that control-P and control-N move vertically through the completion list? Sure, I'll be happy to merge a fix if you (or anyone) want to take it on.

**Comment by sollidsnake** [comment]
Yes, I was outdated. The latest version has this feature, thanks! About `ctrl-p` and `ctrl-n`, I think they're very useful for browsing the candidates. I'll try and see if I can come up with a patch.

**Comment by dgutov** [comment]
@ridiculousfish Can you tell me which file I should look into?

**Comment by ridiculousfish** [comment]
It may be as simple as changing the ctrl-p and ctrl-n bindings from `history-search-backward` binding to `up-or-search`, and likewise for `history-search-forward`. Start in `share/functions/fish_default_key_bindings.fish` and `share/functions/fish_vi_key_bindings.fish`

**Comment by dgutov** [comment]
> changing the ctrl-p and ctrl-n bindings from history-search-backward binding to up-or-search

Indeed, that works just fine, thank you.

> and share/functions/fish_vi_key_bindings.fish

Probably not there. `C-n` and `C-p` are the Emacs-style bindings. Vim users might want something different.

**Comment by pickfire** [comment]
*Basic* **keys bindings* for different editors, `Ctrl-F` and `Ctrl-B` currently works:

| Arrows | Vi-style | Emacs-style |
| -------------- | --------------- | ----------------------|
| **Up** |        `k`         |   `Ctrl-P`               |
| **Down** | `j` | `Ctrl-N` |
| **Left** | `h` | `Ctrl-B` |
| **Right** | `l` | `Ctrl-F` |

**Comment by zanchey** [comment]
I think this is sorted with #2205 being merged, so I'm closing this for now, thought speak up if I have the wrong impression.
