### ISSUE TITLE
exporting variables and perl

### ISSUE THREAD

**Issue by andrewsawczyn** [fish-shell/fish-shell#2209]
Can someone explain to me what is going on with my environment variables and fish 2.2.0?   Here's the issue...

I am trying to run a perl script.  To use this particular script, I need to set my PERL5LIB so that it can find perl modules that I have installed.  To do this I do the following...

```
set -x PERL5LIB /opt/perl-5.18.2/lib /opt/perl-5.18.2/lib/perl5
```
I then run my perl script, which fails...

```
Can't locate App/Options.pm in @INC (you may need to install the App::Options module) (@INC contains: /opt/perl-5.18.2/lib/opt/perl-5.18.2/lib/perl5 /Library/Perl/5.18/darwin-thread-multi-2level /Library/Perl/5.18 /Network/Library/Perl/5.18/darwin-thread-multi-2level /Network/Library/Perl/5.18 /Library/Perl/Updates/5.18.2 /System/Library/Perl/5.18/darwin-thread-multi-2level /System/Library/Perl/5.18 /System/Library/Perl/Extras/5.18/darwin-thread-multi-2level /System/Library/Perl/Extras/5.18 .) at /Users/andrew/Workspace/Rubicon/bin/mvnode line 10.
```
As you can see, the paths I set are appended to one another to form one long path, /opt/perl-5.18.2/lib/opt/perl-5.18.2/lib/perl5.  Thus, my perl script fails to run as it can not find my modules.

This is a new issue as I can download the previous version of fish and it works as expected.  Any ideas?  FYI, I'm using OS X 10.10.4 and fish installed through homebrew.

**Comment by ridiculousfish** [comment]
You're probably being bitten by the changes in #1374. fish has stopped using colons when exporting lists.  You need to use them explicitly now:

    set -x PERL5LIB /opt/perl-5.18.2/lib:/opt/perl-5.18.2/lib/perl5

**Comment by andrewsawczyn** [comment]
Thank you.  Adding a colon between paths has solved my problem.  Not cool.

**Comment by ridiculousfish** [comment]
Glad you got it working.
