### ISSUE TITLE
vi-mode: ^D logs you out.

### ISSUE THREAD

**Issue by newhook** [fish-shell/fish-shell#2219]
It should erase to the end of line.

**Comment by faho** [comment]
It logs out, yes, but why should it "erase to the end of line"? That's what "D" (i.e. shift and "d") should do, in normal mode, and it does.

What ^D (i.e. "\cd" in fish's notation and "C-d" in emacs') does in vim (with an empty vimrc) is in normal mode scroll down a page/screen, keeping the cursor at the beginning of the line. In insert mode, it shifts the current line to the left. Neither of which is particularly applicable to a shell.

What does it do in e.g. zsh's vi mode?

**Comment by newhook** [comment]
Yes, sorry you are completely correctly. However, what ^D does in bash is not boot you out :) It tries to run the current command.

**Comment by faho** [comment]
Okay, in zsh, after `bindkey -v`, in both input and normal mode ^D lists options for what's at the cursor (though I can't figure out how to use it). 

In bash's vi-mode (`set -o vi`), in both ^D is essentially the same as return/enter - it executes the current line.

(All this is through trial with bash 4.3.39, zsh 5.0.8 on archlinux)

**Comment by newhook** [comment]
Not log you out! :)

**Comment by faho** [comment]
How about just doing the same thing it does in emacs mode? ("delete-or-exit", though I can only get it to do the "or-exit" part, it does nothing instead of deleting if the line isn't empty)

See #2255 - if we don't have a compelling alternative, the vi bindings should do what the default bindings do.

**Comment by onnodb** [comment]
Personally, I really like ^D for logging out. For completeness: ^D actually inserts an "end-of-file" character, which is interpreted by some shells as an `exit` or `logout` command. In Bash, it's actually also a known behavior, albeit a behavior that's disabled in most default configurations by setting `set -o ignoreeof` in BASHRC.

**Comment by pickfire** [comment]
`^D` in `zsh` **vi-mode** does *logs you out*. And it seems that `bash` **vi-mode** *logs you out* **when no command is given** and *execute the command* **when a command is given**.

**Comment by krader1961** [comment]
Yes, [ctrl-D] should only cause the shell to exit in vi normal (i.e., command rather than insert) mode if the command line is empty. Why aren't we fixing such trivial issues sooner?
