### ISSUE TITLE
Wahoo Framework needs a Dad

### ISSUE THREAD

**Issue by bucaran** [fish-shell/fish-shell#2223]
Would you allow me to transfer Wahoo to *this organization* (as well as making me a collaborator so that I can continue working on the project as usual).

It would be best for the project if we could go from `bucaran/wahoo` to `wahoo/wahoo`, but this name was already being used. Of course, I could have started a new `github/wahoo-framework` org, but then I thought, ...hey how nice would it be if it we all could exist under the same umbrella of `fish-shell`.

Does that make sense?

Best regards

**Comment by ridiculousfish** [comment]
Sure thing! Go ahead and initiate the transfer.

**Comment by bucaran** [comment]
Great!

This is the first time I transfer a repo to an organization I don't own and it seems I need admin rights. You may give me temporary admin rights, and after I transfer I could simply be added to your collaborator teams with admin rights removed.

**Comment by bucaran** [comment]
@ridiculousfish I can transfer repos to any user, but in the case of an organization you need to have admin rights, silly but there's no other choice.

 You may give me temporary admin rights, and after I transfer I could simply be added to your collaborator teams with admin rights removed.

![t](https://cloud.githubusercontent.com/assets/8317250/8762572/f89137c2-2db7-11e5-9964-3c42b7eac597.png)

**Comment by sindresorhus** [comment]
@bucaran Or just transfer it to an admin of the org, and that admin can then transfer it to the org ;)

**Comment by ridiculousfish** [comment]
That sounds fine, transfer to me and then i'll move it

**Comment by bucaran** [comment]
@ridiculousfish  @sindresorhus Of course!

**Comment by bucaran** [comment]
@ridiculousfish Transfer completed. Now just waiting for it to be moved to the org.

:+1:

**Comment by ridiculousfish** [comment]
It's moved, and you should have admin access to it. Let me know if you have any problems.

**Comment by bucaran** [comment]
It's done. Thank you @ridiculousfish!

Now let's fish.

**Comment by bucaran** [comment]
@ridiculousfish I guess this is not an issue, and I am sorry I didn't mention this explicitly before, but one of the reasons I wanted to move Wahoo into an org is so that I could manage collaborator teams more easily. Since you have made an admin in the Wahoo team, I can in fact add collaborators to the team, but I would like to confirm with you before I do so.

**Comment by ridiculousfish** [comment]
Naturally. This is your baby!

**Comment by bucaran** [comment]
:+1:
