### ISSUE TITLE
Organization logo?

### ISSUE THREAD

**Issue by bucaran** [fish-shell/fish-shell#2225]
I just joined the org and noticed there was no logo.

I think we could use this →

![untitled 4](https://cloud.githubusercontent.com/assets/8317250/8764408/383690c0-2e12-11e5-952d-5b0677225fc1.png)

**Comment by pickfire** [comment]
+1

**Comment by Globegitter** [comment]
Not that I am in the organisation but :+1: Usually any logo is an improvement :)

**Comment by bucaran** [comment]
In smaller sizes, this one actually lets you distinguish the fish:
 
![fish](https://cloud.githubusercontent.com/assets/8317250/8848683/3d1914e0-3174-11e5-88f1-c90b34823d18.png)

**Comment by gretel** [comment]
:+1: for the first

**Comment by bucaran** [comment]
The one is nice but it is indistinguishable in smaller sizes, unfortunately.
