### ISSUE TITLE
vi mode: ^C in insert mode doesn't work as documented

### ISSUE THREAD

**Issue by vcunat** [fish-shell/fish-shell#2228]
[Docs](http://fishshell.com/docs/current/index.html#other) say it should switch to normal mode, but it kills the line instead. I suspect overlapping keybindings don't work as expected/intended.

EDIT: I tested this on 2.2.0.

**Comment by faho** [comment]
Nope, it's [actually bound to 'commandline ""'](https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_vi_key_bindings.fish#L194) i.e. clearing the commandline. Where in the docs does it say that? Your link is to the "other features" section, where I can't find any reference to vi mode or ^C or \\cc. If it says that, it's disagreeing with the code.

**Comment by ridiculousfish** [comment]
Any vi expert want to weigh in on what the right behavior should be?

**Comment by vcunat** [comment]
I tested in gvim that ^C does what's documented, and I find it very practical, as Esc key tends to be far from reach.

**Comment by faho** [comment]
I just tested with [ex-vi](http://ex-vi.sourceforge.net/) (sourceforge link) which is supposed to be a faithful vi (and is the default vi on archlinux at least) and vim: both exit insert mode.

So it seems like what's documented is the right behavior.

**Comment by pickfire** [comment]
I notice that too, it is just different in `fish_vi_mode`.

**Comment by pickfire** [comment]
![2015-08-17-151756_564x340_scrot](https://cloud.githubusercontent.com/assets/4687791/9299902/2a4bf2dc-44f3-11e5-93f7-807586c7b07b.png)

There is 2 mode indicator in the normal prompt, is this the intended feature?

**Comment by ridiculousfish** [comment]
No, that is not intended. Are you sure you don't have a custom prompt?

**Comment by pickfire** [comment]
No, I am currently using the **classic + git** prompt.

**Comment by faho** [comment]
What does `type fish_prompt` say? The default classic+git prompt only has the vi-mode thing in one place.

Also, this is really another issue, please open one.

**Comment by pickfire** [comment]
This only occur in when using **classic + git** theme, there is no problem when using **sorin** theme.

**Comment by ridiculousfish** [comment]
Oh, I see, classic+git has its own mode indicator. I think we can just remove that.

**Comment by ridiculousfish** [comment]
Fixed as 2b87705a467dfcfeb7d40ccd9f42f6f3c91e638a. Thanks for reporting this!
