### ISSUE TITLE
Replace or remove mime handling

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#2229]
I thought I'd just open a dedicated issue so we can track the discussion about this without spamming (mostly) unrelated PRs :smile:. See #2227 and #2211 for previous discussion. 

So what do we use mime-handling for?
----
There's now three places where it's used: share/functions/__fish_filter_mime.fish and share/functions/__fish_complete_mime.fish - the latter uses the former, but nobody uses either - and share/functions/__fish_complete_suffix.fish, but only for a description.

Contrary to what @zanchey said in #2211, the only mention of mime in the documentation I found is for complete_suffix, where it says "The mimetype database is used to find a suitable description".

It's also used on non-OSX systems as a fallback for share/functions/open.fish if xdg-open isn't available, but xdg-open is available pretty much always. If it isn't, you're probably not running a GUI in which case neither'd help you since they are pretty GUI-centric.

So, what could we use mime-handling for?
---
In theory, it'd be nice to print descriptions about what kind of a file it is we're completing, and also to filter the completed files to what an application can use.

However, for the former I'd argue that "XZ-compressed tar archive" as a description for files ending in "pkg.tar.xz" is redundant and only technically correct - yes, it's a tar.xz, but more importantly it's a pacman pkg (but to find that out, you'd need to actually open it and parse the files).

Filtering would be nice, of course, but for that we'd need a complete list of all mimetypes or suffixes a program can handle. This isn't always possible (e.g. emacs might or might not be able to open .pdf, depending on the compile flags), but sometimes a reasonable guess is - vlc for example should be able to open everything in "audio/*" and "video/*" (but should we also complete "image/*"? This is potentially better than going by suffix because those can lie, and finding a complete list of suffixes is pretty hard - try it for vlc.

So, what's wrong with the current solution?
---

`mimedb` (and `xdg-mime`, which I'd prefer never talking about again) looks at a fish-script and guesses it's either "application/octet-stream" (which is mimese for "dunno") or "text/x-matlab", so it's unusable for descriptions _and_ filtering.

So, what are the other utilities?
---

`file` is the only tool I've found that I've not been able to _completely_ stump - at least one of the guesses has so far always been right. That makes it hard to use for descriptions, but okay for filtering (which, again, in upstream fish nobody is using).

However, @zanchey [talks of security problems](https://github.com/fish-shell/fish-shell/pull/2211#issuecomment-122723298) - and those'd hit pretty bad. If you can get pwned by simply tab-completing _in a directory with a prepared file_.... \<INSERT JOKE HERE\>

So, oh green bearded one, what should we do?
---

There are three options I can see:

- Stick with mimedb

- Switch to file

- Ditch the mime-stuff altogether

Of those, the last seems the best option to me.

**Comment by zanchey** [comment]
Thanks @faho 

You're right that `__fish_complete_mime` and `__fish_filter_mime` aren't documented, and they certainly aren't used anywhere else on Github except in the source mentioned.

#1294 recommends removing mimedb on OS X and apparently it has been nuked from the OS X build for some time.

I also note that the documentation for `xdg-open` and `xdg-mime` recommends not running as root, which hints at concerns regarding security.

I am happy to drop the descriptions in `__fish_complete_suffix` as we have done that for other file completions to fix #279, and probably just replace them with "File" (which is a lot more translatable anyway!)

I'll post my mimedb-expunging branch shortly. The major user-visible changes will be:
 * `open` now just warns if it can't find a suitable executable for the platform to open the file
 * `__fish_complete_suffix` just returns "File" for descriptions
 * `mimedb` will be gone

Any objections?

**Comment by faho** [comment]
> `__fish_complete_suffix` just returns "File" for descriptions

Why? See the discussion in #254 (linked in 279), adityagodbole [makes a point](https://github.com/fish-shell/fish-shell/pull/254#issuecomment-7478064) -  when something's a directory it ends in "/", a description that just says "File" is redundant noise that takes away space.

**Comment by ridiculousfish** [comment]
Sounds good to me, and I'm also on board with no descriptions for `__fish_complete_suffix`. Colors are another avenue for descriptive information (#1599).

**Comment by zanchey** [comment]
My thinking is that `__fish_complete_suffix` probably should return _something_ as a description, or be moved to `__fish_print_suffix`, but I agree that a blank default is probably reasonable.

**Comment by zanchey** [comment]
Fixed with merger of #2235.
