### ISSUE TITLE
Custom event handlers

### ISSUE THREAD

**Issue by perfaram** [fish-shell/fish-shell#2231]
Hi !
I'm currently writing my own prompt for fish... But I'm having trouble with event handling. I wrote a custom "command not found" handler, tagging my function with `--on-event fish_command_not_found`.
But my function isn't the only one getting executed when `fish_command_not_found` is fired. The default handler gets executed right after mine, and the only solution I found was to erase a functions... oddly, it was `__fish_command_not_found_setup`.
Could anyone explain me why it is so, and how I can definitively override any other functions responding to `fish_command_not_found` ?
Thanks in advance !

**Comment by faho** [comment]
What's your functions name? Reading `type __fish_command_not_found_setup`, it seems to define a function `__fish_command_not_found_handler`, so if you want to stop that function from executing, you should be able to erase or simply override it.

**Comment by perfaram** [comment]
By override, I guess you mean define another function with the same name ? If so, that's what I did : 
```
function __fish_command_not_found_handler --on-event fish_command_not_found
  echo "Oops, no '$argv', try again!"
  return
end

**Comment by zanchey** [comment]
The problem is that `__fish_command_not_found_setup` gets defined in the shell initialisation, but not run (because it is quite expensive performance-wise, requiring half a dozen tests and at least one fork in the worst case).

What version are you running? If I define your handler before entering an incorrect command, it is erased (and replaced by the standard fish version); if I define it afterward, it overrides the defined handler.

In 2.2.0, the way to do it is define the function in your `config.fish` and erase `__fish_command_not_found_setup` at the same time.

**Comment by perfaram** [comment]
I'm using 2.1.2 - homebrew's formula isn't at 2.2.0 yet.

**Comment by zanchey** [comment]
[I'm pretty sure it is](https://github.com/Homebrew/homebrew/commit/8a108bed154ae79a766d59949f0e753484525a76)! You may need to run `brew update`.

**Comment by perfaram** [comment]
Weird...

**Comment by perfaram** [comment]
Okay, fixed permissions, ran `brew update`, it's OK now. But fish 2.2.0 doesn't fix it :
```
functions --erase __fish_command_not_found_setup

function __fish_command_not_found_handler --on-event fish_command_not_found
  echo "Oops, no '$argv', try again!"
  return
end
```
I get : `fish: Unknown command 'dfgn'`

**Comment by perfaram** [comment]
Update : 
```
function __fish_default_command_not_found_handler --on-event fish_command_not_found
  functions --erase __fish_command_not_found_setup
  #echo (functions -a | grep -i found)
  echo "Oops, no '$argv', try again bb!"
end
```
This works ! But you'll notice that I'm erasing `__fish_command_not_found_setup` each time. It's because it comes back, *while* the function is being executed ! I noticed it with the now-commented out `echo (functions -a | grep -i found)` line.

**Comment by zanchey** [comment]
Your original attempt should work following the merging of #2331.
