### ISSUE TITLE
does support the ^ wildcard?

### ISSUE THREAD

**Issue by Matrix-Zhang** [fish-shell/fish-shell#2234]
how to ls the files except any types?

for example,

ls \*.[^c]\*

**Comment by ridiculousfish** [comment]
This isn't supported - fish doesn't have very rich wildcards. The upside is that you don't have to remember to escape everything.

**Comment by zanchey** [comment]
See #1336 for some discussion of how it might look.

**Comment by Matrix-Zhang** [comment]
3ks. you two
