### ISSUE TITLE
Tab-completion gets truncated and matches more than intended.

### ISSUE THREAD

**Issue by occivink** [fish-shell/fish-shell#2237]
```
$ ls
aaz  abz  acy  ady 
$ ls z
```
At this point, tab-completion produces this
```
$ ls a
aaz  abz  acy  ady
```
Matching everything, even though I explicitly started the completion with 'z'. I would rather have the completion *somehow* match only `aaz` and `abz`.

**Comment by faho** [comment]
Works for me - what fish version are you using?

Do you have any custom functions or completion scripts?

**Comment by occivink** [comment]
2.1.1, so it may have changed. I don't have any custom functions that may interfere nor scripts.
What does `ls z` get updated to when you press tab?

**Comment by faho** [comment]
> What does ls z get updated to when you press tab?

It offers
> aaz abz

Which seems reasonable.

>2.1.1, so it may have changed

Lots of stuff changed, so if you can try 2.2.0, please do.

**Comment by occivink** [comment]
Indeed, it works as I would have liked. The 'z' is not highlighted in the suggestions, but that is a minor issue.
The new pager is very nice as well.

**Comment by pickfire** [comment]
Resolved?

**Comment by occivink** [comment]
I suppose. There is still
>The 'z' is not highlighted in the suggestions, but that is a minor issue.
But it's not so important to me.
