### ISSUE TITLE
Autocomplete CD to folder with "&" (ampersand) in name - eval error

### ISSUE THREAD

**Issue by smarek** [fish-shell/fish-shell#2242]
Running OSX 10.10.4, Fish version 2.2.0 from Homebrew distribution
Step-by-step reproduce:
  - Create folder with ampersand in name
  - write command to `cd` into that directory and after completing the name press TAB once more

```
> mkdir Folder\ \&\ With\ Spaces
> cd Folder\ \&\ With\ Spaces/fish: Unknown command 'With'
- (line 1): begin; printf "%s\n" Folder & With Spaces/*/ 
                                          ^
from sourcing file -
	called on line 60 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/eval.fish

in function 'eval'
	called on line 45 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/__fish_complete_cd.fish

in function '__fish_complete_cd'
	called on standard input

in command substitution
	called on standard input
```

**Comment by smarek** [comment]
Also I wonder where else does this eval/non-escaped problem exist in fish codebase

**Comment by ridiculousfish** [comment]
Dup of #562. AFAIK `cd` is the only one with this problem but there may be others. Thanks for filing!

**Comment by smarek** [comment]
No problem, sorry I missed that ticket when researching before filling in this one.
