### ISSUE TITLE
fish config error

### ISSUE THREAD

**Issue by eikooc** [fish-shell/fish-shell#2248]
I get this error when opening fish:
```
contains: Unknown option “--description”
/usr/share/fish/config.fish (line 104): contains --index $x $local_path
                                        ^
in command substitution
	called on line 102 of file /usr/share/fish/config.fish

in function “__fish_reconstruct_path”
	called on line 122 of file /usr/share/fish/config.fish

from sourcing file /usr/share/fish/config.fish
	called during startup


       contains -- test if a word is present in a list

   Synopsis
       contains [OPTIONS] KEY [VALUES...]

contains: Type “help contains” for related documentation
```

**Comment by faho** [comment]
Which fish version are you running? Do you have any custom functions or other configuration?

**Comment by ridiculousfish** [comment]
This looks like maybe you have a corrupt value for `$fish_user_paths`, perhaps containing `--description`. What does `echo $fish_user_paths` show?

**Comment by eikooc** [comment]
`echo $fis_user_paths` contains exactly what you described:
```
/opt/node/node-v0.12.6/bin --description
```

**Comment by ridiculousfish** [comment]
Ok, well, you should certainly fix that:

    set -e fish_user_paths[2]

More generally we should harden `contains` I guess.

**Comment by faho** [comment]
Well, where's the "--description" coming from? I'm assuming @eikooc doesn't have a directory literally called "bin --description".

**Comment by eikooc** [comment]
I can't seem to recall where it should come from.
@faho yes I do not have a directory called that.

Thanks for quick responses @ridiculousfish and @faho
