### ISSUE TITLE
support safe paste by default?

### ISSUE THREAD

**Issue by oconnor663** [fish-shell/fish-shell#2251]
Oh-my-zsh has a [safe paste plugin](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/safe-paste/safe-paste.plugin.zsh), which makes it so that pasting multi-line text into the terminal gives you a multi-line command to edit, rather than actually executing the first n-1 lines. This takes advantage of some black magic I don't understand called ["bracketed paste mode"](https://cirw.in/blog/bracketed-paste). It sounds like a great feature for fish to support by default, one of those things that almost everyone wants but almost no one takes the time to configure. Is it something we've considered before?

**Comment by faho** [comment]
Duplicate of #2188 - bracketed paste was also mentioned.

**Comment by oconnor663** [comment]
Thanks, I'll comment there.
