### ISSUE TITLE
fish_user_key_bindings in fish_vi_mode

### ISSUE THREAD

**Issue by martinklepsch** [fish-shell/fish-shell#2254]
I was trying to map `kj` to ESC.

Only thing I could come up with that worked was something like this:
```fish
fish_vi_mode
function my_vi_bindings
  fish_vi_key_bindings
  bind -M insert -m default kj backward-char force-repaint
end
set -g fish_key_bindings my_vi_bindings
```

Previously I tried defining `fish_user_key_bindings` but that didn't have any effect:
```
-> cat ~/.config/fish/functions/fish_user_key_bindings.fish
function fish_user_key_bindings
	bind -M insert -m default kj backward-char force-repaint
end
```

It seems that maybe the `fish_user_key_bindings` function is not called after setting up vi key bindings? I grepped the code to figure out where that might be but didn't find any invocations that seemed relevant. Only the one in [`__fish_reload_key_bindings`](https://github.com/fish-shell/fish-shell/blob/b32f770a69527eca4e76b9e8f648a39da17911cb/share/functions/__fish_config_interactive.fish#L160-L179).

**Comment by KonChalas** [comment]
Same problem here!

**Comment by ridiculousfish** [comment]
I think we should run it in all modes. Presumably a user wants to use either vi key bindings or normal, not both. If they do want to use both they can check for `$__fish_vi_mode`.

**Comment by faho** [comment]
I agree - `fish_user_key_bindings` is, as the name implies, written by the user - if they want to have vi-mode, they'll write them so they work with vi-mode.

**Comment by faho** [comment]
@kballard: What are your thoughts on this?
