### ISSUE TITLE
alias breaks completions

### ISSUE THREAD

**Issue by mwm** [fish-shell/fish-shell#2262]
I want to use the shorter "fs" instead of the full command name "fossil". I can do "alias fs fossil" and that works as expected - until I hit a tab to autocomplete. Whereas with fossil I get (having copied fossi.fish from 2.2.0) proper autocompletion, with fs I just get file names.

I can fix this by copying fossil.fish to fs.fish and globally substituting fs for fossil, but it seems like there ought to be a better way.

**Comment by ridiculousfish** [comment]
`alias` was enhanced to use the new `wraps` feature in 61ce9db4bac2da9f69487e828f627e4247ccc140, which is in 2.2.0. Are you on 2.2.0? What is `$FISH_VERSION`?

**Comment by mwm** [comment]
I was on 2.1.1 at the time. Didn't see an issue for aliases. Works in 2.2.0-130-g656ba88
