### ISSUE TITLE
Something went wrong with command substitution

### ISSUE THREAD

**Issue by Profpatsch** [fish-shell/fish-shell#2275]
```fish
> diff (find ~/Pictures/) (ssh 172.16.0.164 "find ~/Pictures/")
diff: extra operand '/home/philip/Pictures/'
diff: Try 'diff --help' for more information.
```

diff shouldn’t know about the `~`-expansion at all.

**Comment by Profpatsch** [comment]
Okay, happens on bash, too. Obvious, because `()` is command substitution.

In bash I do `<()` and it works, what would be the equivalent in fish?

**Comment by faho** [comment]
>In bash I do <() and it works, what would be the equivalent in fish?

[psub](http://fishshell.com/docs/current/commands.html#psub).

**Comment by Profpatsch** [comment]
@faho Thanks!

Is there an IRC channel for fish? Normally I wouldn’t open pull requests like this.

**Comment by ridiculousfish** [comment]
Maybe not a pull request, but an issue is OK :>

There's also https://gitter.im/fish-shell/fish-shell which is a fine place.
