### ISSUE TITLE
bug when adding abbreviations from fish_config 

### ISSUE THREAD

**Issue by despairblue** [fish-shell/fish-shell#2276]
Using fish_config and adding "rm" to "rm -i" leads to 
```
abbr -- '--' 'rm rm -i'
```
being added

**Comment by faho** [comment]
Urgh.... I can reproduce, and I've found the error.

In share/functions/abbr.fish:

```
	while set -q argv[1]
		if test $needs_arg = single
			set mode_arg $argv[1]
			set needs_arg no
		else if test $needs_arg = coalesce
			set mode_arg "$argv"
			set needs_arg no
			set -e argv
		else
			set -l new_mode
			switch $argv[1]
			case '-h' '--help'
				__fish_print_help abbr
				return 0
			case '-a' '--add'
				set new_mode add
				set needs_arg coalesce
			case '-e' '--erase'
				set new_mode erase
				set needs_arg single
			case '-l' '--list'
				set new_mode list
			case '-s' '--show'
				set new_mode show
			case '--'
				set -e argv[1]
				echo "Argv after removing -- $argv"
				break
			case '-*'
				printf ( _ "%s: invalid option -- %s\n" ) abbr $argv[1] >&2
				return 1
			case '*'
				break
			end
			if test -n "$mode" -a -n "$new_mode"
				# we're trying to set two different modes
				printf ( _ "%s: %s cannot be specified along with %s\n" ) abbr $argv[1] $mode_flag >&2
				return 1
			end
			set mode $new_mode
			set mode_flag $argv[1]
		end
		set -e argv[1]
	end
```

Yeah, that's a handful. The issue here is once "--add" is read, it will switch to "needs_arg=coalesce", so it won't remove the "--" anymore. In other words: `abbr` doesn't use `--` when adding abbreviations.

The question is if it should, and if it shouldn't we can just remove the "--" from webconfig.py.

Git lays blame on 48d35361, i.e. @zanchey. How do you defend yourself, ser?

**Comment by faho** [comment]
Please try fe687cec967b4b9774844a3f2ddb478cdad58375 which fixes it for me.

**Comment by faho** [comment]
If it's still not fixed, please say so.

**Comment by despairblue** [comment]
I just compiled master and it's still broken, though on master the web interface seems to be completely broken: all tabs are empty except for the *abbreviation* one.

**Comment by despairblue** [comment]
Oh not broken, I just didn't wait for the server to return the content.

But the *abbreviations* are still added like `abbr -- '--' 'rm rm -i'`

**Comment by despairblue** [comment]
Also deleting abbreviations in the web interface does not work on master. If I reload the page it's simply there again.

**Comment by faho** [comment]
Urgh, I never _merged_ that commit!

>Also deleting abbreviations in the web interface does not work on master. 

The "--remove" option in abbr was renamed to "--erase" in c0cf25cf0b28969dd9ef821f7952f42783ed6720, but nobody thought of changing it in webconfig as well.

Thanks for testing and reporting, I believe it should work again with 7fe8a63 and 4887429.

**Comment by zanchey** [comment]
I did change it in the web config with c0cf25cf0b but I think that got reversed in 9223b643b6c234.

**Comment by despairblue** [comment]
With 7fe8a63 everything works, adding and erasing! :+1: 

Thanks for making this shell :smiley:

**Comment by ivanershov51** [comment]
Sadly this bug persists. fish 2.2.0-5. Also deleting an abbreviation from the web doesn't work...
<img width="820" alt="screenshot_20160121_044701" src="https://cloud.githubusercontent.com/assets/11010943/12469140/55fed854-bffa-11e5-8931-5735fb5b6624.png">

**Comment by faho** [comment]
@ivanershov51: 2.2.0-5 from who? The "-5" is a distribution release, which means they've done _something_ to the package (which includes patching or rebuilding). It's possible they've backported 7fe8a63 but I consider that unlikely. Try fish directly from git, otherwise you probably won't have the fix.

**Comment by ivanershov51** [comment]
@faho, Arch Linux. Sorry for my incompetence in open source.

**Comment by faho** [comment]
@ivanershov51: You do _not_ have the fix. See https://projects.archlinux.org/svntogit/community.git/log/trunk?h=packages/fish. 2.2.0-5 is fish 2.2.0 with the docker completions removed/readded and twice rebuilt for library upgrades.

The two commits are fairly trivial to apply yourself, though.

>Understood, sorry for my incompetence in open source.

Nah, it's an opportunity to learn. We all went through that.

**Comment by ivanershov51** [comment]
@faho: Thank you :)
