### ISSUE TITLE
Tab completion doesn't work on aliases

### ISSUE THREAD

**Issue by morganastra** [fish-shell/fish-shell#2277]
Expected: Fish's tab completion for git commands is great if you type out the full git command. For example, if I type `git push origin <tab>`, it will (correctly) try to complete git branches. I use a fish function/alias so that I only have to type `g` rather than the whole word `git` (those two letters on every git command add up over time!), and I'd expect fish's tab complete to still work when I use the alias.

Actual: to use my example from earlier, when I type `g push origin <tab>` instead of offering to complete branch names, fish falls back to completing files in the current directory.

**Comment by faho** [comment]
Which fish vesion do you use? How exactly have you defined the alias? Since 06400b83b188156f31ed92216ec27122d29f88cd, aliases should "wrap" the aliased command, i.e. inherit its completions. This appeared first in 2.2b1.

**Comment by morganastra** [comment]
```fish
morgan@dev ~ [1]> fish --version
fish, version 2.1.0
morgan@dev ~> more .config/fish/functions/g.fish
function g
        git $argv;
end
```

**Comment by faho** [comment]
Updating fish should solve your problem. In 2.1.0 it's hard to do since it doesn't have a "--wrap" option for either function or complete.

Sorry.

**Comment by morganastra** [comment]
Okay, I updated to fish 2.2.0, but this issue is still present. Should I define my alias function in a different way?

**Comment by ridiculousfish** [comment]
If you wrote the function yourself (or used `funcsave` on an older version) you will have to edit it to add `--wraps`:

    function g --wraps git
            git $argv;
    end

**Comment by Kerosene2000** [comment]
hello, I wanted to know if something could work ?

```
function gp --wraps "git push"
	git push $argv
end
```

**Comment by ridiculousfish** [comment]
No, there's not yet a way to wrap a command and its arguments.

**Comment by Kerosene2000** [comment]
Ho ! Thanks !
But I can't tell the `fish autocompletion` to start to autocomplete from a certain point/level like the example above ?

**Comment by faho** [comment]
@Kerosene2000: Nope, that's #1976.

**Comment by krader1961** [comment]
@Kerosene2000 Your example is better served by an abbreviation: `abbr gp='git push'`. If you do that you can still type `gp ` and benefit from all the usual git completions.

**Comment by Kerosene2000** [comment]
Thanks a lot, I didn't see this `abbr` command in the tutorial or in the doc, but I think I was focus on the usage of the function keywird to do an alias !
(Sorry for the late response, I'm in france)

**Comment by gubikmic** [comment]
What's the current status on this?

When I use `alias gl="git log"` then the tab completion (for e.g. branches in that case) does not work.
With `abbr gl="git log"` it works, but I'd prefer these shorthands not to expand.

Is there a way to get tab completions with `alias`?

**Comment by krader1961** [comment]
@gubikmic, See issue #1976. The reality is that most people, including myself, use abbreviations to wrap commands like `git` which have subcommands. So we're not motivated to improve this specific use case. But neither are we opposed to making this work better. Which is why issue #1976 is open. We'd be happy to review a patch from someone like yourself who strongly wants this feature implemented.

**Comment by luispabon** [comment]
@krader1961 a lot of us, I dare say most, come from bash and definitely expect aliases to work the same.

**Comment by ryofurue** [comment]
> a lot of us, I dare say most, come from bash and definitely expect aliases to work the same.

I agree with this statement, having come to this thread exactly to solve this very problem.  After setting my aliases, it took me some time before I realized the cause of this "malfunctioning".

This is a "surprise" that former bash users don't want.

**Comment by faho** [comment]
@luispabon, @ryofurue: Good news for you two: 3.0 finally allowed completions to wrap arbitrary other completions, fixing it for aliases.

Also, commenting on years-old closed issues isn't really how this works - if you have a question or you've found a bug, try to find a still open issue, and if you don't, open a new one.

**Comment by ryofurue** [comment]
@faho Thank you for the good news!

> commenting on years-old closed issues isn't really how this works - if you have a question or you've found a bug, try to find a still open issue, and if you don't, open a new one.

Yes, but it's not that we've found a new bug or that we have a question.  We (at least I) wanted to convince the developers to re-open this very issue.  If I submitted a new issue of the same request,  "this is a duplicate of issue XXXX and is therefore closed" would be the fate of it, I guess.
