### ISSUE TITLE
Symlinks in release archives

### ISSUE THREAD

**Issue by oysteinkrog** [fish-shell/fish-shell#2286]
There are symlinks in the release archives, which makes it hard to unpack them under operating systems that do not support symlinks (e.g. Windows).

**Comment by faho** [comment]
It's just share/completions/..fish (i.e. the completions for the "." function aka source - btw we don't have completions for "source" even though "." is deprecated) , right?

**Comment by oysteinkrog** [comment]
Yes, that is the file I had issues with.
