### ISSUE TITLE
Allow ^C to kill tab completion. 

### ISSUE THREAD

**Issue by rohit507** [fish-shell/fish-shell#2291]
At the moment commands like "sudo apt-get <tab>" lead to tab-complete trying to display a huge list of options, taking quite a bit of time. 

Sometimes this is wanted, but most of the time I've forgotten to type the search prefix, or hit tab by mistake. Allowing tab-completion to be killed with "^c" or "^d" would allow recovery from these mistakes without having to wait for the action to complete.

**Comment by faho** [comment]
That's basically #23, if you're talking about stopping completions while they are gathering.

If you are talking about stopping the completions menu, escape does that.
