### ISSUE TITLE
ssh-copy-id fails if remote user uses fish

### ISSUE THREAD

**Issue by BalzGuenat** [fish-shell/fish-shell#2292]
When issuing the command `ssh-copy-id -i alice@server.com` where user `alice` uses fish fails with the following error:

```
fish: Expected a command name, got token of type “Run job in background”. Did you mean “COMMAND; and COMMAND”? See the help section for the “and” builtin command by typing “help and”.
Standard input:                 mkdir -p .ssh && cat >> .ssh/authorized_keys || exit 1 ;
                                               ^
```

The command works after changing the shell of `alice` to `bash`.

**Comment by ridiculousfish** [comment]
Dup of #150. Thanks for filing this!

**Comment by faho** [comment]
Not quite a duplicate, though - the issue here is that ssh (via ssh-copy-id) assumes the user's shell is fully sh-compatible. The "&&" is just one symptom.

Though all of that is an issue with ssh, not fish itself.

**Comment by zanchey** [comment]
There was some work in ssh to fix this - see http://www.gossamer-threads.com/lists/openssh/dev/42368 and https://lists.mindrot.org/pipermail/openssh-unix-dev/2008-February/026140.html but it doesn't look like it ever got merged.

**Comment by zanchey** [comment]
I'll see if I can get something like that merged upstream.
