### ISSUE TITLE
function -V causes "Unknown option" error in Cygwin

### ISSUE THREAD

**Issue by andrex-e-schulman** [fish-shell/fish-shell#2293]
In fish 2.2.0 in Cygwin (2.2.0):

    ASchulma@LC77E1AASCHULMA ~> function test -V arg
                                    echo
                                end
    function: Unknown option 'arg'
    
           function -- create a function

etc.  

In particular, this causes an error message to be issued at every prompt, because the stock prompt_pwd function uses `function -V`.  So at the moment in order to make fish 2.2.0 usable in Cygwin, I have to redefine prompt_pwd without -V:

    function prompt_pwd --description 'Print the current working directory, shortened to fit the prompt'
        set -l realhome ~
        echo $PWD | sed -e "s|^$realhome|~|" -e 's|^/cygdrive/\(.\)|\1/:|' -e 's-\([^/.]\)[^/]*/-\1/-g' -e 's-^\([^/]\)/:/\?-\u\1:/-'
    end

With that change, prompt_pwd works fine again.

Please label this issue as "bug" and "Windows" - I don't seem to have the ability to do that.

**Comment by ridiculousfish** [comment]
Any idea why -V is not working? It's a supported option for `function`.

**Comment by andrex-e-schulman** [comment]
Bug is invalid.  Caused by installation error.  Closing.
