### ISSUE TITLE
command -s causes "Unknown option" error in Cygwin

### ISSUE THREAD

**Issue by andrex-e-schulman** [fish-shell/fish-shell#2294]
In fish 2.2.0:

    ASchulma@LC77E1AASCHULMA ~> command -s ls
    command: Unknown option 'ls'
    
           command -- run a program

and so on.  In particular this breaks the `type` function, which calls `command -s`:

    ASchulma@LC77E1AASCHULMA ~> type bash
    command: Unknown option '--'
    /usr/share/fish/functions/type.fish (line 3): command -s -- $i

`type` is a very important function, so this makes fish 2.2.0 not ready to deploy in Cygwin.

Please label this issue as "bug" and "Windows".

**Comment by ridiculousfish** [comment]
Any idea why `-s` is not working? I wouldn't expect platform differences in argument parsing.

**Comment by andrex-e-schulman** [comment]
Bug is invalid - caused by an installation error.  Closing.
