### ISSUE TITLE
commandline --paging-mode causes "Unknown option" error in Cygwin

### ISSUE THREAD

**Issue by andrex-e-schulman** [fish-shell/fish-shell#2295]
In fish 2.2.0 in Cygwin 2.2.0:

    ASchulma@LC77E1AASCHULMA ~> commandline --paging-mode
    commandline: Unknown option '--paging-mode'
    
           commandline -- set or get the current command line buffer

and so on.  In particular, pressing the up arrow key will cause this error message to be printed, since up arrow runs `up-or-search`, which invokes `commandline --paging-mode`.

Please label this issue as "bug" and "Windows".

**Comment by ridiculousfish** [comment]
This is the third case where new options aren't working. It would be explained if you have fish 2.1 installed, but were using fish 2.2's function set. Is that's what's going on?

**Comment by andrex-e-schulman** [comment]
Ugh.

Yes, that's what happened. Cygwin-specific installation issue that I won't bore you with.  Thanks, and sorry for the noise.  Closing.

**Comment by ridiculousfish** [comment]
Hah, glad it's resolved
