### ISSUE TITLE
Can't add key bindings in config.fish

### ISSUE THREAD

**Issue by sjl** [fish-shell/fish-shell#230]
When add lines like:

    echo foo
    bind \cn clear

To my `config.fish` file, the `foo` will indeed be echoed to the screen when I start a new shell, but the new ctrl+n binding doesn't work (it does what ctrl+n usually does).

If I then run that exact same bind command manually, it *does* work.

Do I need to use a different syntax to bind things in the config file?

**Comment by jeff-hykin** [comment]
[SOLVED] 
My issue was that I downloaded the fish Mac app, then installed fish with homebrew 
Just using the app doesn’t trigger `~/.config/fish/config.fish` or `/usr/local/share/fish/functions/fish_default_key_bindings.fish` 

**Solution**
I just used 
chsh -s `which fish`` 
(ignore the second back-tic mark)  
to make fish the default shell, and then ndemou’s hack worked for me (even if I open fish via the app)

**Comment by ndemou** [comment]
Note that according to the [manual](http://fishshell.com/docs/current/commands.html#bind) the proper solution this issue is to "_put the bind statements into a function called fish_user_key_bindings, which will be [autoloaded](http://fishshell.com/docs/current/tutorial.html#tut_autoload)._"
