### ISSUE TITLE
cd completion acts funny when spaces are present in the path

### ISSUE THREAD

**Issue by tgkokk** [fish-shell/fish-shell#2300]
```shell
$ mkdir a\ b\ c
$ cd a\ [TAB]
```
Now, i would expect to autocomplete `a\ b\ c/`, but instead it offers completions for every directory in the CWD. I guess that it treats the space as an argument separator.

Other commands (e.g. `mkdir`) work fine.

**Comment by faho** [comment]
Same thing as #2299 - does  #2289 change anything?

**Comment by tgkokk** [comment]
Yeah, it autocompletes `a\ a\ b\ c/`. Still not perfect but better.

**Comment by faho** [comment]
>Other commands (e.g. mkdir) work fine.

There is no mkdir completion - it falls back to the generic file completion.

There's probably an issue with the completion comparison logic - it seems some of it happens before escaping.

**Comment by faho** [comment]
I actually can't reproduce this anymore. Closing.
