### ISSUE TITLE
"__fish_complete_python.fish" not work.

### ISSUE THREAD

**Issue by quininer** [fish-shell/fish-shell#2301]
![snapshot128](https://cloud.githubusercontent.com/assets/6286761/9269894/1b61492a-42a0-11e5-9aaa-c9177937d11b.png)

Maybe should `$PATH` or `__import__('sys').path` to get  Python library.

Arch Linux
Python, 3.5.3
fish, 2.2.0

**Comment by faho** [comment]
See #2256.

**Comment by quininer** [comment]
@faho thx
