### ISSUE TITLE
The `master` Branch's `help`Pages 404

### ISSUE THREAD

**Issue by trisys3** [fish-shell/fish-shell#2303]
When I run `help [command]` with the `master` branch, I get a 404 error. I believe I am supposed to get the main site, `fishshell.com, with the version as whichever `git` commit I am on.

I would understand if this happened with some random commit that wasn't the last commit; this would be inconvenient but you're running an older version of `fish` that isn't tagged. Couldn't the latest commit go to the latest version of the site, though? Alternatively, could each branch hold a version of the site, similar to the `fish_config` command, or is the site just too big? It doesn't seem that big, and it seems like it is mainly text and links to different parts of whatever page you are on, or am I just seeing part of the site?

**Comment by faho** [comment]
>When I run help [command]

Any specific command? Does a literal `help command` fail?

>with the master branch,

Which commit? `fish --version`

>I believe I am supposed to get the main site,

No - you are supposed to get a browser opened to a file in $__fish_help_dir.

Can you get the value of that and check what is in there?

What URL does your browser open?

>could each branch hold a version of the site

It already does - or at least it should.

**Comment by trisys3** [comment]
I thought I had `doxygen` the last time I built, but I guess I didn't complete the build. Building again made all the problems go away  Sorry for wasting your time, closing.
