### ISSUE TITLE
Error with ssh tab completion on CentOS 5

### ISSUE THREAD

**Issue by tgt** [fish-shell/fish-shell#2305]
On CentOS 5 tab completion for ssh results in the error `sed: invalid option -- E`

I have GNU sed version 4.1.5

In order to reproduce the issue type `ssh<space>` and then hit tab.

**Comment by faho** [comment]
This is a BSD/OSX-ism to accept extended regular expressions - GNU sed uses "-r" instead. It seems to be used in [__fish_print_hostnames.fish](https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_print_hostnames.fish#L17).

In all fairness, that expression _actually_ uses some extensions - in particular the "+", to mean "the last expression at least once".

My GNU sed 4.2.2 seems to accept it, though, and even that is from 2012.
