### ISSUE TITLE
Fish doesn't follow symlinks to fishd.* files

### ISSUE THREAD

**Issue by alphapapa** [fish-shell/fish-shell#2306]
I like to use the same Fish configuration on all of my systems (just like using the same `.bashrc`, etc).  I got tired of killing fishd and overwriting the local system's `fishd.*` file, so I made one `fishd.main` file and symlinked it to the appropriate `fishd.*` file on each system.  However, if I then make a change from within fish (like using `set -U`), fish overwites the `fishd.*` symlink with a normal file, instead of following the symlink and overwriting the symlinked file.

In a broader sense, is this machine-specific fishd file thing really a good idea?  I have never needed nor wanted such a feature in Bash.  All I want is to use the same configuration everywhere, and this isn't helping.  If I setup fish and my dotfiles on a new system, fish doesn't work like Bash, just reading the appropriate files; I have to run fish, kill fish, go to the fish config dir, figure out which fishd file is the one for the current system (couldn't it at least use the hostname?), and then overwrite it with my own fishd file, and finally restart fish.  Then, if I make any changes on a system, they don't propagate naturally; I have to do merging/overwriting to get the changes into the global fishd file that I commit into git.

Thanks for your work on fish.

**Comment by ridiculousfish** [comment]
Yeah, we should have a real story for people who like to sync their dotfiles.

**Comment by krader1961** [comment]
This is the same as issue #1912.
