### ISSUE TITLE
Can't use continue in function

### ISSUE THREAD

**Issue by onodera-punpun** [fish-shell/fish-shell#2307]
Function in question:

    # This function is used to skip admin command
    function admin
    	if test -z (grep \^$nick\$ $configdir/admin)
    		echoii "Check your privilege~"
      
    		continue
    	end
    end

This function gets called in in a loop but fish returns `'continue' while not inside of loop`

**Comment by ridiculousfish** [comment]
What do you hope to happen here? Is it that it will exit from the function and resume in the caller's loop?

**Comment by onodera-punpun** [comment]
It's just a part of code I repeat often in my script, continue if it doesn't meet a requirement.

in bash just just works, in fish it gives me the inside loop error, even though the function gets called inside a loop.

**Comment by ridiculousfish** [comment]
Holy cow, that does work in bash. Unbelievable!

fish will not support this for the same reason that Python, C, etc. don't support it: it's at odds with the principles of [structured programming](https://en.wikipedia.org/wiki/Structured_programming). functions are not supposed to be able to modify the caller's control flow.

Instead you should use techniques like checking the return value:

    function admin
        if test -z (grep \^$nick\$ $configdir/admin)
            echoii "Check your privilege~"
            return 1
        end
        return 0
    end

    admin ; or continue

We should start a bash WTF list.

Thanks for filing this!
