### ISSUE TITLE
Autosuggestions doesn't work under console/tty for non-root users

### ISSUE THREAD

**Issue by davispuh** [fish-shell/fish-shell#2308]
When I open tty with Ctrl+Alt+F2 and login with root then autosuggestions work, but if I login from non-root user then it doesn't display them. They do work with `sudo fish` for those users so it's something with permissions most likely. I added user to `video` group but that didn't change anything. Any idea what permissions user needs for it? Under X they work fine for all users.

**Comment by ridiculousfish** [comment]
This is really surprising. There's no special permissions needed at all. Is it possible that `$fish_color_autosuggestion` is set to something you can't see?

**Comment by davispuh** [comment]
Thanks, `$fish_color_autosuggestion` was set to grayish color, but tty didn't support that so it was casted to black and thus invisible.
These themes are such where it's casted to black:
*  fish default 
* Solarized Dark
* Bay Cruise
* Old School
* Mono Lace
* Mono Smoke (text is black too, can't even see what you type)

**Comment by ridiculousfish** [comment]
What's your terminal emulator, out of curiosity?

**Comment by davispuh** [comment]
Default kernel virtual console, $TERM says `linux`.
Anyway I switched to kmscon which supports 256 colors so don't have issue there :)
