### ISSUE TITLE
Arrow keys does not work in linux framebuffer

### ISSUE THREAD

**Issue by pickfire** [fish-shell/fish-shell#2309]
When I press an arrow key in linux framebuffer (`Ctrl+Alt+F2`), something like `OA` and `OD` will show up and it does not return to the previous command, **left** and **right** keys does not work too.

I want to use arrow keys, does anyone know how to fix that?

`uname -a`:
```
Linux alarmpi 4.1.5-1-ARCH #1 SMP PREEMPT Wed Aug 12 19:02:34 MDT 2015 armv7l GNU/Linux
```

`fish --version`:
```
fish, version 2.2.0-220-g0682c0f
```

**Comment by faho** [comment]
What's your keymap (in /etc/vconsole.conf)?

**Comment by pickfire** [comment]
I cannot find `/etc/vconsole.conf`.

**Comment by faho** [comment]
You're running archlinux arm, aren't you? In that case you probably have systemd, so the output of `localectl` (specifically the "VC Keymap") would be useful. If you haven't set it, you should probably create a /etc/vconsole.conf. See [the archwiki article](https://wiki.archlinux.org/index.php/Keyboard_configuration_in_console).

**Comment by faho** [comment]
I've added localectl completions in cb5d36d89f497abd7394c0228f8defa150495a7b, so you should have an easier time with setting the keymap.

**Comment by pickfire** [comment]
`localectl set-locale <TAB>` still does not work. How do I use tab completion for that?

**Comment by pickfire** [comment]
I have set `VC Keymap` to `unicode`. It still doesn't work.
```
   System Locale: LANG=en_US.UTF-8
       VC Keymap: unicode
      X11 Layout: n/a
```

**Comment by faho** [comment]
>localectl set-locale <TAB> still does not work. How do I use tab completion for that?

Well, you'd need to get [the completion script from current git HEAD](https://raw.githubusercontent.com/fish-shell/fish-shell/master/share/completions/localectl.fish) and drop it in ~/.config/fish/completions.

**Comment by pickfire** [comment]
Well now my `localectl` shows:
```
   System Locale: LANG=en_US.UTF-8
       VC Keymap: unicode
      X11 Layout: us
       X11 Model: pc104
     X11 Variant: ,qwerty
     X11 Options: terminate:ctrl_alt_bksp
```
It still doesn't work in framebuffer.

**Comment by faho** [comment]
Please reboot your system - if I don't after changing keymaps, I also have some keys not working.

**Comment by pickfire** [comment]
It still has the same problem after reboot.

**Comment by faho** [comment]
That's _weird_. Does it also have issues with other vc keymaps (after reboot, of course)? I'm guessing "unicode" is a fallback-thing. Why not choose your country-code?

**Comment by pickfire** [comment]
It still have the same result after reboot even after I set localectl to:
```
   System Locale: LANG=en_US.UTF-8
       VC Keymap: us
      X11 Layout: us
       X11 Model: pc105
     X11 Variant: ,qwerty
     X11 Options: terminate:ctrl_alt_bksp
```

**Comment by faho** [comment]
So, according to sheldon in #2330, it seems like, in bash, pressing ctrl-v and then a key will print its character sequence (we should get that function as well). Please try that with the affected keys.

**Comment by pickfire** [comment]
Using `bash` in **framebuffer**:
```
Up    : ^[OA
Down  : ^[OB
Right : ^[OC
Left  : ^[OD
```

**Comment by faho** [comment]
Then try the following:

```fish
bind \e0A up-or-search
bind \e0B down-or-search
bind \e0C forward-char
bind \e0D backward-char
```

or

```fish
bind ^[0A up-or-search
# and so on
```

(Add it to the fish_user_key_bindings function if you want to have it in config)

This is kinda weird since these for me send "^[[A", "^[[B" and so on (in a VT of course).

**Comment by pickfire** [comment]
If I add the following, what the other users do? Do they need to add it too. I hope fish can still follow its philosophy that [Configurability is the root of all evil](fishshell.com/docs/current/design.html).

**Comment by pickfire** [comment]
It seems that none of your solution works. I found one solution that works which **only** works in **emacs mode** (vi mode doesn't work) when I execute the following in *linux framebuffer* (adding in *~/.config/fish/config.fish* doesn't work):

```
bind \eOA up-or-search
bind \eOB down-or-search
bind \eOC forward-char
bind \eOD backward-char
```

> where we also have other term-specific keychords

What do you mean by that? There is an application ([**`st`**](st.suckless.org)) which the *delete* key doesn't work in `bash` and `fish` but works in `zsh` required to execute some code to make the *delete* key work. And the condition is the same as above (need to execute manually and *~/.config/fish/config.fish* doesn't work).

**Comment by faho** [comment]
>only works in emacs mode (vi mode doesn't work)

Yeah, for vi-mode you'd need to add it separately.

>bind \eOA up-or-search

Ah, that's the _letter O_ (as in Oscar)! Okay.

I still think it's weird your TERM behaves like this while mine doesn't.

**Comment by pickfire** [comment]
What do I need to do now?

I also have an issue which is almost the same as the current issue, should I open an issue request? The other issue is below in https://github.com/fish-shell/fish-shell/issues/2309#issuecomment-136609130.

**Comment by faho** [comment]
>What do I need to do now?

I'll check if these binds don't interfere with anything else and if they don't add them. If not we need to think of a different solution.

>There is an application (st) which the delete key doesn't work in bash and fish but works in zsh required to execute some code to make the delete key work.

What does the delete key in st output?

>adding in ~/.config/fish/config.fish doesn't work

Like I said above, you need to add binds to the `fish_user_key_bindings` function, not just anywhere in config.fish. (This is a bit of an annoying limitation and should probably be documented better, it's also not run in vi-mode currently)

**Comment by pickfire** [comment]
> What does the delete key in st output?

It just prints `[P`.

**Comment by faho** [comment]
Just `[P`, not `^[P`?

Try

```fish
bind "[P" delete-char
```

then (same rules as above apply)

**Comment by pickfire** [comment]
> I'll check if these binds don't interfere with anything else and if they don't add them. If not we need to think of a different solution.

It seems that your commit had fixed the problem. It seems that there is some commit that had removed color from the terminal in framebuffer and it has broken the `fish_vi_mode`.

**Comment by faho** [comment]
>It seems that there is some commit that had removed color from the terminal in framebuffer

f71e877f18037f71c00f81e30c1173f51c42a58c? That should have set the colors differently to a set that should "just work".

>it has broken the fish_vi_mode

How exactly?

**Comment by pickfire** [comment]
> f71e877? That should have set the colors differently to a set that should "just work".

The commit that is in the range of `e0e7325..5f080fc`. I need to check more about it.

> How exactly?

```
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
color not valid in TERM = linux: --bold[I] me@alarmpi ~>
```

> bind "[P" delete-char

That works. But from the suckless page, there is another alternative:

```
## Why doesn't the Del key work in some programs?

Taken from the terminfo manpage:

        If the terminal has a keypad that transmits codes when the keys
        are pressed, this information can be given. Note that it is not
        possible to handle terminals where the keypad only works in
        local (this applies, for example, to the unshifted HP 2621 keys).
        If the keypad can be set to transmit or not transmit, give these
        codes as smkx and rmkx. Otherwise the keypad is assumed to
        always transmit.

In the st case smkx=E[?1hE= and rmkx=E[?1lE>, so it is mandatory that
applications which want to test against keypad keys send these
sequences.

But buggy applications (like bash and irssi, for example) don't do this. A fast
solution for them is to use the following command:

        $ printf '\033[?1h\033=' >/dev/tty

or
        $ tput smkx

In the case of bash, readline is used. Readline has a different note in its
manpage about this issue:

        enable-keypad (Off)
                When set to On, readline will try to enable the
                application keypad when it is called. Some systems
                need this to enable arrow keys.

Adding this option to your .inputrc will fix the keypad problem for all
applications using readline.

If you are using zsh, then read the zsh FAQ
<http://zsh.sourceforge.net/FAQ/zshfaq03.html#l25>:

        It should be noted that the O / [ confusion can occur with other keys
        such as Home and End. Some systems let you query the key sequences
        sent by these keys from the system's terminal database, terminfo.
        Unfortunately, the key sequences given there typically apply to the
        mode that is not the one zsh uses by default (it's the "application"
        mode rather than the "raw" mode). Explaining the use of terminfo is
        outside of the scope of this FAQ, but if you wish to use the key
        sequences given there you can tell the line editor to turn on
        "application" mode when it starts and turn it off when it stops:

                function zle-line-init () { echoti smkx }
                function zle-line-finish () { echoti rmkx }
                zle -N zle-line-init
                zle -N zle-line-finish

Putting these lines into your .zshrc will fix the problems.
```

**Comment by faho** [comment]
Ah, okay, fish_vi_mode sets "--bold" - that actually works, so we should ignore it in the set_color override (or remove that entirely). I'll think about it.

**Comment by faho** [comment]
How do the keycodes change when you do that?

**Comment by pickfire** [comment]
> How do the keycodes change when you do that?

What do you mean?

**Comment by faho** [comment]
If you execute `tput smkx` and then press CTRL-v delete in bash, what does it output?

**Comment by pickfire** [comment]
Every one of the following fixed it:
```
printf '\033[?1h\033=' >/dev/tty
tput smkx
bind "[P" delete-char
```

But I think that we shouldn't only use `fish`-**specific** command.

> If you execute tput smkx and then press CTRL-v delete in bash, what does it output?

I doesn't know why, but it seems that I can't press `k`.

**Comment by pickfire** [comment]
In **bash**, it shows `^[[3~`. And it works by default in **zsh**.

**Comment by pickfire** [comment]
I have updated the last two coment. It seems that after I run **zsh** and close it. **fish** seems to have *delete* work.

**Comment by faho** [comment]
>printf '\033[?1h\033=' >/dev/tty
tput smkx
bind "[P" delete-char

Thanks. I'd rather not balloon all our key bindings with all escape codes for all terminals (and I dislike that "st" behaves this way when nearly everything else seems to work better), so I'd appreciate a solution where we can just execute something like `tput smkx` when needed (or at least not harmful). How do we detect that it's needed? Can it be harmful (i.e. make some keys not work)?

BTW: Does this improve the original situation with the VT - if you build without a21e44c and instead execute `tput smkx` do the arrows output more normal codes?

**Comment by pickfire** [comment]
> BTW: Does this improve the original situation with the VT - if you build without a21e44c and instead execute tput smkx do the arrows output more normal codes?

No, it just display the same weird codes.

> Thanks. I'd rather not balloon all our key bindings with all escape codes for all terminals (and I dislike that "st" behaves this way when nearly everything else seems to work better), so I'd appreciate a solution where we can just execute something like tput smkx when needed (or at least not harmful). How do we detect that it's needed? Can it be harmful (i.e. make some keys not work)?

I thought you said that there is some terminal specific ...?

**Comment by faho** [comment]
>I thought you said that there is some terminal specific ...?

Yes, there are some terminal-specific codes in our bindings, but I don't really like adding too many more. Of course we could make it more palatable by grouping things like

```fish
for k in \eOC \e\[C # right-arrow
    bind $argv $k forward-char
end
```

(and I might end up doing that anyway)

If it was only delete and only in st and then we'd be done I'd just add it, but I expect it to be more, even in st - what about shift-delete? 

Ideally terminfo would just have that info so we get it via `bind -k` - this would also improve the situation for users who create their own bindings and switch terminals. Detecting the terminal and then doing `tput smkx` (which really seems like a magic "do the right thing and not your stupid default" command to me) would also solve this, but I have no clue how to do that - "$TERM" is not going to help since everyone sets that to "xterm-256color" because too many programs expect it to be.

**Comment by faho** [comment]
I've just installed st, and here's a list of key combinations that don't work and what they print:

- delete: "[P"
- shift-delete: "[2K"
- ctrl-delete: "[M"
- insert: "[4h" (shift-insert inserts from the clipboard)
- ctrl-insert: "[L"
- shift-up: "[1;2A" (and B/C/D for the other arrows)
- ctrl-up: "[1;5A"

all of these seem to be fixed via `tput smkx`, and $TERM is set to "st-256color".

**Comment by pickfire** [comment]
I understand what you mean, bind everything...

> If it was only delete and only in st and then we'd be done I'd just add it, but I expect it to be more, even in st - what about shift-delete?

What is shift-delete for?

> Ideally terminfo would just have that info so we get it via bind -k - this would also improve the situation for users who create their own bindings and switch terminals. Detecting the terminal and then doing tput smkx (which really seems like a magic "do the right thing and not your stupid default" command to me) would also solve this, but I have no clue how to do that - "$TERM" is not going to help since everyone sets that to "xterm-256color" because too many programs expect it to be.

Yeah, there is [*terminfo* for st](http://git.suckless.org/st/tree/st.info#n182). By default, st uses [`st-256color`](http://git.suckless.org/st/tree/config.def.h#n66) and I uses that anyway as it did not broke anything.

I haven't tried shift-delete, ctrl-delete, insert, ctrl-insert, shift-up, ctrl-up as I seldom uses them, the most visible is *delete*. Maybe I could patch **st** for *delete* to work.

> all of these seem to be fixed via tput smkx, and $TERM is set to "st-256color".

What about `printf '\033[?1h\033=' >/dev/tty`?

**Comment by faho** [comment]
>What is shift-delete for?

Currently nothing - the point though is that this outputs something different in st than elsewhere.

>Yeah, there is terminfo for st. 

But it gives info for the smkx mode:

>	kdch1=\E[3~

It seems like st expects everyone to send it that - now it'd be nice to know why.

>What about printf '\033[?1h\033=' >/dev/tty?

Same thing, except the former uses the terminfo database. st has `smkx=\E[?1h\E=`.

@zanchey: You seem to know your way around this stuff. Anything we can do? Anything I got wrong?

**Comment by pickfire** [comment]
> It seems like st expects everyone to send it that - now it'd be nice to know why.

Should I ask in the mailing list about it?

**Comment by faho** [comment]
Let's check the archives first.

**Comment by faho** [comment]
Why not discuss this in #2139, actually? You opened it to track this, after all.

**Comment by pickfire** [comment]
Sorry, I forgot about that. The case for *linux framebuffer* is solved.
