### ISSUE TITLE
history --merge does not merge history in chronological order

### ISSUE THREAD

**Issue by brettanomyces** [fish-shell/fish-shell#2312]
Expected result: After `history --merge` commands in history should be shown in chronological order by the `history` command

Actual result: merged commands are shown after commands from the current session.

To reproduce:
Add `save.fish` to `~/.config/fish/functions`

```
function save
	echo "- cmd:" $argv >> ~/.config/fish/fish_history
	echo "  when:" (date "+%s") >> ~/.config/fish/fish_history
	history --merge
end
```

Open a new shell and type the following 
```
ls
save test
history
````
test appears below ls in the history, e.g.
```
save test
ls
test
...
```

fish, version 2.2.0-118-gaee71b5

**Comment by ridiculousfish** [comment]
Finally fixed this. Thanks for reporting it!
