### ISSUE TITLE
`-c` argument handling

### ISSUE THREAD

**Issue by lloeki** [fish-shell/fish-shell#2314]
Typical of `sh` shells is to have a `-c` flag that takes all the remainder arguments as a command. This allows for stuff like `bash -l -c foo "$@"` to work and splat the arguments properly, including strings with spaces.

Fish does not do this:

```
$ fish -l -c ls -1
fish: invalid option -- 1
$ fish -l -c "ls -1"
foo
bar
baz
```

While this allows to put `-c` anywhere as an argument, this isn't _quite_ as useful as passing actual arguments to the command to run within fish.

**Comment by ridiculousfish** [comment]
I can't get it to work:

    > bash -c echo abc
    (no output)
    > bash -c 'echo abc'
    abc

Which version of bash are you testing with? I have `GNU bash, version 4.3.30`

**Comment by lloeki** [comment]
OMG you're *so* right. I was basing myself on the man page:

       -c string If  the  -c  option  is  present, then commands are read from
                 string.  If there are arguments after the  string,  they  are
                 assigned to the positional parameters, starting with $0.

**Comment by ridiculousfish** [comment]
Heh:

    > bash -c 'echo $@' 1 2 3
    2 3

Like one would expect of course.

In fish:

    > fish -c 'echo $argv' 1 2 3
    (no output)

The 1, 2, 3 are just ignored in the presence of `-c`. (Otherwise they would be interpreted as filenames).

Any suggestions for what we ought to do with them?

**Comment by lloeki** [comment]
> Like one would expect of course.

Dammit. Like, for once, if I actually read the thing in front of me :sob: 

> Any suggestions for what we ought to do with them?

Well, the thing being useful there is preserving the array-ness of the args, thus saving the caller from having to interpolate it into the command string and thus from escaping the strings, so that's definitely a useful feature to have (behaving like bash I mean), all the more than it seems pretty consistent across shells (zsh, bash, dash, even csh).

**Comment by ridiculousfish** [comment]
Oh geez, that wasn't my intent! I was mocking bash for `echo $@ 1 2 3` outputting only `2 3`.

**Comment by lloeki** [comment]
Ah, ok :-) 1 is set as argv[0] so it replaces the command in ps output. That can be useful too.

**Comment by cbarrett** [comment]
Hm, drat, I just ran into a case where I need this. Consider the following snippet:

```bash
case ${SHELL##*/} in
    bash)	exec -l "${SHELL}" --login -c 'exec "$@"' - "$@" ;;
    ksh|sh|zsh)	exec -l "${SHELL}" -c 'exec "$@"' - "$@" ;;
    csh|tcsh)	exec -l "${SHELL}" -c 'exec $argv:q' "$@" ;;
    es|rc)	exec -l "${SHELL}" -l -c 'exec $*' "$@" ;;
esac

# Fall back on bash.
exec -l /bin/bash --login -c 'exec "$@"' - "$@"
```

The intention here is to re-exec underneath a login shell. (I can explain why it's doing this, I think.) Maybe I just need more coffee but I'm struggling to think of a workaround that won't blow-up on paths with spaces.

In addition to this issue, other shells' execs supports the -l option which - to the argv[0] like login(1).

**Comment by faho** [comment]
>I can explain why it's doing this, I think.

@cbarrett: I'd love that explanation. Usually, you do **not** want to run anything under an arbitrary shell. The reason being of course that there's no guarantee that $SHELL is compatible with whatever script you have. And in fact fish will be incompatible with all but the most trivial.

I'm assuming you're trying to get "the user's environment"?

**Comment by Pysis868** [comment]
I expected this capability today, trying to use `xargs` but split the piped input around using several variables in a fish subshell instead of a simple `-I'{}' ... '{}'` strategy.

So fish just ignores arguments for `-c` unlike the other shells?

**Comment by floam** [comment]
Kind of, except for the very particular case of `exec $@`... we have a hack to make fish compatible with an XDM configuration SuSE shipped with. This actually probably would have satisfied @cbarrett.

```
$ fish -l -c 'exec "$@"' foo asd
```
... will exec `asd`.

**Comment by floam** [comment]
(Please, for the love of God, do not rely on this behavior. We will remove it without notice sometime.)

**Comment by faho** [comment]
(This is encapsulated in a function called `fish_xdm_login_hack_hack_hack_hack`)

**Comment by Jakeler** [comment]
Any update on this?
```fish
fish -c 'echo $argv[1]' gg
```
Would have expected it behaving like bash, zsh, etc... outputting 'gg'.

**Comment by ridiculousfish** [comment]
Nobody's working on it as far as I know, but it seems like a reasonable first issue if someone wants to dive in!

**Comment by rogusdev** [comment]
This is how bash and zsh work in my testing around this:
```
bash -c 'echo $@' hi # nothing
bash -c 'echo $@' -c hi # hi
zsh -c 'echo $@' hi # nothing
zsh -c 'echo $@' -c hi # hi
```
I would expect the same from fish. I am using this for testing scripts in different shells, and need to be able to pass in arguments.

Is this what would be desired behavior if a PR were to go up?

**Comment by Jakeler** [comment]
@rogusdev From the bash manpage:

> ... the first argument is assigned to $0 and any remaining arguments are assigned to the positional parameters.  The assignment to $0 sets the name of the shell, which is used in warning and error messages.

So it does use that argument without double `-c`, but you get a empty line because `$@` excludes `$0` and starts with `$1`, `$2` etc. Add 'bash' or some other dummy first argument to get the output from all examples. Actually your second '-c' does not get parsed by bash and it instead sets `$0` to '-c'. Probably not what you intended, it would also show an error if it would parse it as command. On zsh it is exactly the same.

Fish can read and execute commands from multiple `-c`. 
Maybe we should add an extra option (-a or --argument=ARG) to make it more more clear and not break multiple commands?

**Comment by rogusdev** [comment]
@Jakeler wow /epicfail on my part, thanks for the clarification! I do see that this was discussed earlier in the thread but I did not see it as mapped to my scenario exactly so I did not recognize it.

So, the issue remains open then, yeah? Because still:
```
fish -c 'echo $argv' junk hi  # empty line, should be hi
```
Or are you saying that the plan/need is for some other way to pass in args here?

**Comment by Jakeler** [comment]
I think the "first argument sets the name of the shell" behavior is very confusing, at least it was for me when I first saw this and this thread is a good example as well. So I would just put the first argument in `$argv[1]` and so on, there is no `argv[0]` in fish as far as I know.

After reading your tests I noticed that it could cause conflicts with multiple commands, for example this is currently possible:
```sh
$ fish -c 'echo first' -c 'echo second' -c 'echo last'
first
second
last
```
Executed as 3 commands. With a argument handling implemented it would most likely become a single command with 4 arguments ('-c', 'echo second', '-c', 'echo last'). Don't know if anyone uses it like this, but that would break the script for them. That is why my idea is to pass arguments as extra option.

Both ways would be probably fine though, I guess after almost 5 years with nobody working on it, the biggest need is someone who looks into the code and actually makes a PR.

**Comment by faho** [comment]
Alright, I just made it read the arguments into $argv. No special handling of the first (if that's needed we can add another option - `fish --name foo -c 'dotheting' arg1 arg2 arg3`), and $argv just stays across separate `-c`s.

**Comment by rogusdev** [comment]
Thanks @faho for the fast turnaround! With this implementation, given that fish supports multiple `-c`s, what would happen in this case?
```
fish -c 'echo $argv' hi -c 'echo $argv' yo
```

**Comment by faho** [comment]
Fish only interprets options until the first non-option, so everything from the `hi` on is an argument.

(this isn't changed, btw)

**Comment by rogusdev** [comment]
Thank you for fixing this and really elaborating on how it will work! I really appreciate it :)
