### ISSUE TITLE
Emulate bash "insert-completions"

### ISSUE THREAD

**Issue by nyarly** [fish-shell/fish-shell#2318]
I'd like to be able to say

```
bind \e* insert-completions
```

So that 

```
> cat some-files/sbstr<Alt-*>
```

might product produce

```
> cat some-files/substring.txt some-files/substring.rtf some-files/substring.xml
```

(if such files existed)

I think all I need that I can't find in fish is a builtin to produce arbitrary completions - i.e. like the bind input function "complete" but that I can use in a `function insert-completions` together with commandline. It _looks_ like `__fish_print_path` (or actually `__fish_complete_path`) should do the trick... but it uses old-style prefix completion, not substrings. I've looked through the __fish functions in general, but nothing jumps out.

**Comment by ridiculousfish** [comment]
This nearly works:

    function insert_completions
        commandline -t --replace (complete --do-complete=(commandline -t) | cut -f 1 | tr \n ' ')
    end
    bind \cx insert_completions

It doesn't escape the completions - probably that can be done with some sed-fu, and later with the string builtin.

**Comment by nyarly** [comment]
Doh! How did I miss --do-complete? It was exactly what I was looking for. Is it a bug that it appears in the description but not the synopsis of `complete` ?

**Comment by ridiculousfish** [comment]
Yep, it ought to be in the synopsis. Good catch!

**Comment by nyarly** [comment]
Maybe this has to do with the escaping - I get "insertion mode switches cannot be used when not in insertion mode!" from commandline. I'm having trouble debugging the function, since --do-complete seems to only function "in context" so to speak... or something.

Here's what I'm seeing:

    > complete --do-complete="cat test/Wr"
    >
    > complete --do-complete="test/Wr"
    >
    > cat test/Wr<Tab>
    test/DataWrapper.js  test/MultiSourceDataWrapper.js

But `complete --do-complete="cat test/"` returns the whole dir worth of files and `complete --do-complete="test/"` returns just the directories.

Finally: `complete -C "test/"` outputs the same as `ls` vs `complete -C"test/"` is the same as `--do-complete="test/"` which is... not POSIX?

**Comment by ridiculousfish** [comment]
`complete -C` doesn't do fuzzy matching, only prefix matching. I'd like to turn on fuzzy matching, but we need to vet existing uses to make sure it won't break them. A script could reasonably assume that `complete -C`'s output will always be prefixed by its input.

**Comment by nyarly** [comment]
Maybe `complete -P|--do-fuzzy` ?

**Comment by ridiculousfish** [comment]
Completions should be fuzzy. We would fall back to that (and it would be a --not-fuzzy flag) if we determine that there's a legitimate need.

Basically the next step is to catalog the uses of `complete -C` and evaluate whether they're OK with fuzzy results.

**Comment by nyarly** [comment]
Looking at 

`share/functions/`

 it looks like 

```
__fish_complete_command
__fish_complete_svn_diff
__fish_complete_subcommand 
__fish_complete_file_url
```
use -C as a way of wrapping complete - so fuzzy would be what you want?

in `share/completions`
```
share/completions/git.fish
share/completions/xterm.fish
share/completions/svn.fish
share/completions/type.fish
share/completions/su.fish
share/completions/which.fish
```
generally use a pattern like `complete -C(commandline -ct)` to send one command as an argument to another - again, I think you want that to be the same as unwrapped shell completion?  The exception is in completions/git.fish: 

```
for name in (builtin complete -Cgit- | sed 's/^git-\([^[:space:]]*\).*/\1/')
```
I think fuzzy would actually break that - you want all the commands that start "git-" in the path, not 'gorram-it-all-to-heck-mal' ...  Of course, give that there is e.g. git-receive-pack in the path, fuzzy isn't considered, right? Still, seems a little sketchy.

**Comment by faho** [comment]
>for name in (builtin complete -Cgit- | sed 's/^git-\([^[:space:]]*\).*/\1/')

Isn't that just basically `$PATH/git-*`? Seems easy enough to replace.

**Comment by JoshCheek** [comment]
I think `expand_completions` would be a better name, as I don't immediately associate `insert` with the text at the prompt.

**Comment by faho** [comment]
do-complete is documented since 19112980ee5c3703e50f42a9e05781e5a32f1e88 if I'm reading correctly.

**Comment by nyarly** [comment]
@faho Maybe I missed something here, but I didn't think this had actually been implemented yet. Docs yes, but complete being fuzzy by default is still in the future, right?

**Comment by zanchey** [comment]
Agreed; reopening and retargeting.
