### ISSUE TITLE
fish_tests fails in 2.2.0

### ISSUE THREAD

**Issue by amluto** [fish-shell/fish-shell#2322]
I see:

```
0 / 5...done (2)
1 / 5...done (21)
2 / 5...done (401)
3 / 5...done (8001)
4 / 5...done (160001)
The function 'recursive' calls itself immediately, which would result in an infinite loop.
fish: recursive ;
      ^
in function 'recursive'
	called on standard input

fish: __fish_print_help function
      ^
in command substitution
	called on standard input

function: No function name given


fish: function '' ; echo fail; exit 42 ; end ; ''
      ^
The file '' is not executable by this user
fish: function '' ; echo fail; exit 42 ; end ; ''
                                               ^
....
```

**Comment by ridiculousfish** [comment]
These aren't failures, that's the expected output. It's hard to suppress since it's printed directly to stderr.

**Comment by amluto** [comment]
Indeed, I can't read.

I do, however, see this:

Testing complete
Error: Test failed on line 2000: completions.size() == 1
Error: Test failed on line 2001: completions.at(0).completion == L"r"
Error: Test failed on line 2005: completions.size() == 1
Error: Test failed on line 2006: completions.at(0).completion == L"r"
Error: Test failed on line 2010: completions.size() == 1
Error: Test failed on line 2011: completions.at(0).completion == L"r"
Testing input
Testing universal variables
................................................................................................................................................
Testing universal callbacks
Testing universal notifiers with strategy 1
Testing universal notifiers with strategy 2
Testing completion insertions
Testing scenarios that should produce no autosuggestions
Testing autosuggestion combining
Testing wcstring_tok
Testing history
Testing history merge
Testing history race conditions
Testing history_sample_fish_1_x
Testing history_sample_fish_2_0
Testing bash import
Testing history_sample_corrupt1
Encountered 6 errors in low-level tests

**Comment by ridiculousfish** [comment]
Hmm, I can't reproduce those. Does it still happen after a clean build? What OS are you on?

**Comment by amluto** [comment]
Strace says (among many other things):

stat("/bin/mkdirhier", {st_mode=S_IFREG|0755, st_size=483, ...}) = 0

Uninstalling imake (which provides /usr/bin/mkdirhier) from my system fixes
it.

--Andy

**Comment by ridiculousfish** [comment]
Ah, ok. Probably we should fix the test.
