### ISSUE TITLE
C-w (kill word) is really slow

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#233]
Using C-w takes about one second per keypress. It could be faster.

**Comment by faho** [comment]
Is this still an issue? I'm also (apparently) running an xsel-enabled build but for me C-w is instant.

**Comment by zanchey** [comment]
Yeah, it was because I was forwarding X over a slow link. The Right Fix is probably to run `xsel` in the background, but I'm not sure that anyone else actually runs into this problem.

**Comment by faho** [comment]
We no longer run xsel unless explicitly requested, so this should be fixed.
