### ISSUE TITLE
directory history not working with alt-left / alt-right on Terminal.app in OSX

### ISSUE THREAD

**Issue by sheldon** [fish-shell/fish-shell#2330]
Hi

I've tried a little debugging but can't seem to narrow this down. dirh works fine showing a list of previous directories. alt-left / alt-right work fine for skipping words or completing commands 1 argument at a time. For some reason alt-left / alt-right at an empty command line don't switch directories in the history.

Any chance there's some way I can figure this out? It seems like a great feature!

Thanks

**Comment by faho** [comment]
It should be in one of these bindings:

>bind \e\eOC nextd-or-forward-word
bind \e\eOD prevd-or-backward-word
bind \e\e\[C nextd-or-forward-word
bind \e\e\[D prevd-or-backward-word
bind \eO3C nextd-or-forward-word
bind \eO3D prevd-or-backward-word
bind \e\[3C nextd-or-forward-word
bind \e\[3D prevd-or-backward-word
bind \e\[1\;3C nextd-or-forward-word
bind \e\[1\;3D prevd-or-backward-word

So check if these are bound. If they are, your terminal might be sending a different string - which one are you using? (If that's the issue, you can confirm it by binding the functions to other keys)

**Comment by sheldon** [comment]
Hey @faho 

Thanks for the suggestion. I've tried checking in ~/.config/fish and can't find any references to nextd-or-forward-word, and when searching for bind the only thing I'm finding is ```SET fish_key_bindings:fish_default_key_bindings```. Do you think the defaults don't have these bound perhaps? Or is there a way to check that, or check what my terminal is sending?

**Comment by faho** [comment]
The defaults should have them, though it's possible we're missing an escape.

Just run `bind` to see your bindings.

**Comment by sheldon** [comment]
Here's my output, looks correct to me:
```
sels@marvin ~> bind | grep nextd-or-forward-word
bind \e\eOC nextd-or-forward-word
bind \e\e\[C nextd-or-forward-word
bind \eO3C nextd-or-forward-word
bind \e\[3C nextd-or-forward-word
bind \e\[1\;3C nextd-or-forward-word
```

thanks for the quick response and help :+1:

**Comment by sheldon** [comment]
I managed to track this down, so here's the solve in case anyone else is looking for it.

Running bash and using [ctrl-v followed by a keystroke will output it's character sequence](http://stackoverflow.com/questions/4200800/in-bash-how-do-i-bind-a-function-key-to-a-command). This shows alt-left and alt-right output `^[b` and `^[f` from Terminal.app in OSX. [`^\[` is the same as `\e`](http://unix.stackexchange.com/questions/116562/key-bindings-table/116614#116614).

The output from bind in fish shell has
```
bind \eb backward-word
bind \ef forward-word
```
which means Terminal.app won't search the directory history instead of word skipping when the command line is empty on that particular terminal app.

Not sure if this should remain a bug, but it took a while to figure out for me. Unless there's a reason not to, I think all bindings of forward-word and backward-word should be changed to the nextd-or-forward-word and prevd-or-backward-word variants? Especially to support that feature out the box on OSX's builtin Terminal.app

**Comment by faho** [comment]
>This shows alt-left and alt-right output ^[b and ^[f from Terminal.app in OSX.

Yeah, that's pretty broken - being unable to distinguish alt-left from alt-b... (*goes off to the corner to grumble*)

>Unless there's a reason not to, I think all bindings of forward-word and backward-word should be changed to the nextd-or-forward-word and prevd-or-backward-word variants?

I'd agree. Anyone else?

Nice work tracking this down by the way!

**Comment by jcrben** [comment]
Is there a recommended workaround for this since the fix hasn't shipped? For some reason I was having trouble binding the commands to those optional ones.

There is the workaround described at https://coderwall.com/p/ygcaqg/get-alt-arrow-keys-working-in-fish-on-os but it feels dirty

**Comment by faho** [comment]
@jcrben: That workaround (binding alt+arrow to more usual sequences) isn't actually bad. It would actually be the only thing to allow you to bind alt-b to something different from alt-left (and other combinations).

I'm actually a bit annoyed that that's not the default - those would be the sequences that actual xterm sends, and IIRC Terminal.app identifies as xterm (via $TERM).

**Comment by jcrben** [comment]
@faho it may not be bad in that sense, but I sometimes switch shells and I find that binding keys like this to the terminal rather than shell messes with things and confuses with me. shouldn't manually binding the key to the `nextd-or-forward-word` work?

**Comment by faho** [comment]
>shouldn't manually binding the key to the nextd-or-forward-word work?

Yes, that'll work.

I kinda like the workaround (and wish apple would just do it, turning it into a solution) because it brings Terminal.app in line with xterm, which it proclaims to be, and because it allows you to bind alt-left differently from alt-b - since currently it just tells the app that you've pressed alt-b when you pressed alt-left. There are some key combinations in a terminal that can't be distinguished from others (e.g. ctrl-i and tab), but it's a major PITA and they should be reduced as much as possible, not increased.

Now, I can see why you'd like alt-left to do the same thing as alt-b - in emacs modifier-b does some backwards-movement, i.e. ctrl-b is moving backwards a character, alt-b moving backwards a word, and this is also the readline (and hence bash) default, so by making alt-left send alt-b, you get that automatically. But it's bad to not allow binding them differently.

Anyway, I think I'll make the change in the defaults. I'm just annoyed that we have to.

**Comment by jcrben** [comment]
Are you sure about your conclusion? I'm using iTerm. 

Using the CTRL+V trick mentioned above, I get `^[[1;9D` for the alt+left arrow while alt+b is `^[b`.

I've also set alt keys to ESC+ and set the key mapping to the xterm defaults:
![image](https://cloud.githubusercontent.com/assets/5614134/20644576/107ec2ec-b3ee-11e6-8bb5-0d7208faf814.png)

**Comment by krader1961** [comment]
@jcrben: I don't see where you mentioned the terminal you were using prior to your most recent comment. The O.P. was using Terminal.app which does in fact have the behavior described. Whereas iTerm2 gets it right using the xterm default key bindings.

P.S., Fish includes a program named `fish_key_reader` which makes understanding what various keys send much clearer than the [ctrl-V] trick or using tools like `xxd` or `od`.

**Comment by jcrben** [comment]
Yeah, sorry about that. I was actually running fish 2.1.2 and now that I've upgraded to 2.4 it seems like it is working properly for me out of the box. Still absorbing a lot of new information... I'll report back if I find anything that needs changing, but right now it's 👍

**Comment by elias6** [comment]
Would it be possible to make alt-left and alt-right just work, without needing this workaround, by binding `\eb` to `'prevd-or-backward-word'` and `\ef` to `'nextd-or-forward-word'`?

My guess is it would be, although I haven't tried it. But is this a practical solution? Or is there some downside I'm unaware of?

**Comment by faho** [comment]
> Or is there some downside I'm unaware of?

That those are the same as alt+b / alt+f, which we use for other things.

**Comment by elias6** [comment]
@faho would my idea break anything important?

If the user has entered text on the command line, `backward-word` and `prevd-or-backward-word` do the same thing, and `forward-word` and `nextd-or-backward-word` do the same thing, so there would be no change in behavior if we call one instead of the other.

And if there is no text, `backward-word` and `forward-word` do nothing useful, so there would be no loss of functionality if we call something else instead. The worst that would happen is some users may get annoyed if they accidentally go back or forward, but that seems much better than the directory history not working at all for many users (without requiring awkward workarounds that are not at all obvious).

**Comment by faho** [comment]
This is a workaround for a bad design decision in a proprietary, single-platform terminal. Key combinations in a terminal are at a premium, and the terminal should offer as many as possible. Collapsing them is quite awkward.

Working around that should *not* impact more sensible terminals.

Again: Write a patch that checks $TERM_PROGRAM in the bind function. Make it bind \eb and friends, but *only* in Terminal.app.

**Comment by elias6** [comment]
Why was this closed?

Yes, it was a bad decision to make the Mac Terminal treat alt-left like alt-B and alt-right like alt-F, and I agree that terminals should offer as many key combinations as possible.

But is that not a reason to work around it by assigning the things we want alt-left to do to alt-B, and likewise for alt-right? I don't see how this is "collapsing" key combos. I don't see what the harm is in binding `\eb` and `\ef` in all terminals.

**Comment by faho** [comment]
>Why was this closed?

Because it was fixed in 7167ba6e085ff4cedc218c0ad902c442c9171389, by working around Terminal.app, by binding \eb to what alt-left does and \ef to what alt-right does.

**Comment by elias6** [comment]
What? If it was fixed, then why can't I go back and forward by pressing alt-left and alt-right?

**Comment by faho** [comment]
>What? If it was fixed, then why can't I go back and forward by pressing alt-left and alt-right?

Because it wasn't released yet?

**Comment by elias6** [comment]
Oh... I didn't understand that this was already fixed in a version that hasn't yet been released. I guess I will eagerly wait for it. Thanks for explaining.
