### ISSUE TITLE
test: Trying to add switches to display help information for a function, but fish treats the "-h" argument strangely.

### ISSUE THREAD

**Issue by terrycloth** [fish-shell/fish-shell#2332]
I'd like my function to display help information if there are no arguments, or if the first argument is either `-h` or `--help`.

``` fish
function foo
    if test -z "$argv"  -o "$argv[ 1 ]" = "-h"  -o  "$argv[ 1 ]" = "--help"
        echo "help"
    # Else if there are other arguments, do something else...
    end
end
```

This seems to work correctly when there are no arguments, or if the first argument is `--help`, but sending `-h` returns an error:

> <samp>test: Expected a combining operator like '-a' at index 5</samp>

I'm running fish on Fedora 22 x64. I've tried this on both the version available in the Fedora repos (2.1.1) and from compiling the latest release (2.2.0).

**Comment by faho** [comment]
The issue seems to be that `test` sees the "-h" as an option if it is after a "-o" or "-a".

Here are a few workarounds to tide you over until it is fixed:

```fish
test "x$argv[1]" = "x-h"
```

```fish
contains -- -h $argv
```

(which also enables position-independent options)

**Comment by terrycloth** [comment]
Hah! `contains` is probably a better solution, but your `test` is clever.

**Comment by faho** [comment]
Not my invention - it's a standard POSIX sh (and to a lesser degree bash) trick because that test sucks. I felt a little dirty suggesting it.

**Comment by ridiculousfish** [comment]
This looks like a bug in `builtin_test` to me. That's up for a rewrite anyways: I wrote it as this ridiculous recursive descent parser when really it can just do a linear scan.

**Comment by krader1961** [comment]
I inadvertently fixed this last week when I refactored *src/builtin.cpp* to move all the builtins into their own modules, normalize the code for flag parsing, and stop special-casing `-h` and `--help`.
