### ISSUE TITLE
alt + {left,right} fails on multi-line command

### ISSUE THREAD

**Issue by occivink** [fish-shell/fish-shell#2333]
The default binding " alt + {left,right} " used to move the cursor to word boundaries fails if the current command spans more than one line. The command doesn't seem to matter, something as simple as 
```
> ls
  ls
```
can cause it.

An error message like `test: Expected a combining operator like '-----' at index 2` gets prompted at the cursor position.

Using fish 2.2.0

**Comment by faho** [comment]
Thanks for the report, this should be fixed. It seems like "test" doesn't like newlines.
