### ISSUE TITLE
Completions cannot be overwritten.

### ISSUE THREAD

**Issue by Profpatsch** [fish-shell/fish-shell#2336]
When I test a completion implementation, I want to iterate. At the moment I do it by pasting the new version into a shell.
I noticed doing a second evaluation has no effect, I have to open a second shell.

That might be desirable, though I can’t think of a good reason why.

**Comment by faho** [comment]
Try `complete -e -c $COMMAND` before changing them. I'm not quite sure how overwriting completions would work generally - basically as soon as there's a condition involved it becomes tricky.

**Comment by Profpatsch** [comment]
Will `-e` erase all completions for a command?

**Comment by faho** [comment]
Yes.

Do note however that while `complete -e -c $COMMAND` works, `complete -c $COMMAND -e` doesn't seem to do anything. I'll need to open a bug about that.

**Comment by faho** [comment]
@Profpatsch: I'm closing this now because I'm not sure there's anything we should do about it. If you come up with anything say so.
