### ISSUE TITLE
Completion failed in some cirumstances

### ISSUE THREAD

**Issue by Mabinogiysk** [fish-shell/fish-shell#2337]
for example, if I have a folder named "test"
test
├── firstfolder
│   ├── 111.txt
│   └── 222.txt
└── secondfolder
    ├── 111.txt
    └── 222.txt
now I want to edit 111.txt in firstfolder, I type:
$vim test/firstfolder/111.txt
then I want to edit 111.txt in secondfolder, I ues  ↑ to get former command:
$vim test/firstfolder/111.txt
and I delete "firstfolder" so it becomes:
$vim test//111.txt
then I type sec[tab],but the completion can not work. It still display
$vim test/sec/111.txt 
and cursor jump from character "c" to the end of this command. I must type full name of the folder so it can get access to "111.txt".
In bash shell, completion works well so I regard it as a bug.
I hope you can fix it soon, thanks.

**Comment by faho** [comment]
Isn't this basically the same thing as #357?

**Comment by pickfire** [comment]
I think this issue should be closed and let the other issue track this issue.
