### ISSUE TITLE
Array indexes should start from 0

### ISSUE THREAD

**Issue by alphapapa** [fish-shell/fish-shell#2338]
Apologies if this has been posted here before, but I searched both open and closed issues, as well as Google, and I couldn't find anything.

I am converting a Bash script to Fish, and I just got bitten by this.  It is very confusing that Fish arrays start at 1 instead of 0.  I understand that starting at 0 seems unnatural, but in computer programming, it's nearly universal to start at 0.  I don't think this is a trend Fish should buck.  It's practically a universal standard.

When people are converting to Fish, they are not going to be expecting this.  And when people are converting existing scripts to Fish, going nearly line-by-line, this is going to be a constant hassle, having to mentally switch over and over.

**Comment by faho** [comment]
Changing that would mean breaking every existing fish script that uses array indices, so I don't think we're going to do so.

Sorry.

And FYI: zsh also does it this way.
