### ISSUE TITLE
Request: Capture set_color's escape code into variable

### ISSUE THREAD

**Issue by alphapapa** [fish-shell/fish-shell#2339]
I am converting a Bash script to Fish.  One of the things the script does is colorize some words in a string by using `sed` and escape codes.

It's really nice that Fish provides `set_color`; it's so much better than using lists of variables containing escape codes.  But there doesn't seem to be a way to capture the escape codes`set_color` sets.  I'd like to be able to do something like this:
```fish
set red (set_color red)
set normal (set_color normal)

set text (echo "fee fi fo fum" | sed 's/fi/'$red'fi'$normal'/g')
echo -e $text
```
And it would print `fee fi fo fum` with `fi` in red.

As it is I'm having to attempt a very hacky method that splits a string into tokens and prints each token separately, setting the color if the token is supposed to be colorized.  The result is so slow that it looks like a corny movie effect that prints a few characters at a time.

Of course, I could give up and use sed and a list of color escape codes, but that wouldn't be very fishy...

Thanks for your consideration.

**Comment by faho** [comment]
Your exact code works for me - what fish version do you use?

**Comment by alphapapa** [comment]
Well, I feel really silly right now.  I don't know what I was doing wrong, but it does indeed work.  Maybe I was up too late, haha.  Thanks for your help and kind reply!
