### ISSUE TITLE
"set var 1 2 3; echo foo$var" gives "foo1 foo2 foo3"?

### ISSUE THREAD

**Issue by alphapapa** [fish-shell/fish-shell#2341]
Sorry if this has been discussed before.  I just ran across this behavior by accident, and it seems undocumented, and I wonder if it's intentional.
```fish
$ set test 1 2 3
$ echo foo$test
foo1 foo2 foo3
$ echo "foo$test"
foo1 2 3
```
I can see how it could be handy, but also surprising.  If it's intentional, I think it should be prominently documented (as a nifty, map-like, functional-language feature, of course ;).  If not, it should probably be "fixed."

**Comment by faho** [comment]
It's not quite documented but very much intentional. Adding the appropriate tag to remind us.
