### ISSUE TITLE
test built-in can't handle unquoted array variables?

### ISSUE THREAD

**Issue by alphapapa** [fish-shell/fish-shell#2342]
I don't understand this:
```fish
$ set a 1 2 3
$ test -n $a; and echo yes
test: Expected a combining operator like '-a' at index 2
$ set a 1
$ test -n $a; and echo yes
yes
```
Shouldn't `test` be able to handle arrays?

Ok, I can quote the variable:
```fish
$ set a 1 2 3
$ test -n "$a"; and echo yes
yes
```
But that is very confusing, because one of the big selling points of Fish is that you don't have to quote variables.  If I have to remember to quote them under special conditions...well, I wouldn't say, "Might as well just use Bash," but some people might.  :)

Here's another example:
```fish
$ set a 1 2 3
$ test $a = "1 2 3"
test: Expected a combining operator like '-a' at index 1
```
Now I suppose it's arguable whether `$a` in this case is equal to `"1 2 3"`.  And of course, you can quote it:
```fish
$ set a 1 2 3
$ test "$a" = "1 2 3"
$
```
But again, this is confusing (at least, to me), because one of the biggest benefits of using Fish for scripting over Bash is that you don't have to worry about quoting variables.  At least, that's what I thought... :)

**Comment by faho** [comment]
The `test` parser isn't as good as it should be. See #2332 where @ridiculousfish talks about rewriting it.

**Comment by faho** [comment]
To go into more detail:

```fish
$ set a 1 2 3
$ test -n $a; and echo yes
test: Expected a combining operator like '-a' at index 2
```

This one is annoying and I'd call it a bug.

```fish
$ set a 1 2 3
$ test $a = "1 2 3"
test: Expected a combining operator like '-a' at index 1
```

This one is debatable as [the documentation](http://fishshell.com/docs/current/index.html#expand-variable) says:

>There is, however, an important difference in how variables are expanded when quoted and when unquoted. An unquoted variable expansion will result in a variable number of arguments. For example, if the variable $foo has zero elements or is undefined, the argument $foo will expand to zero elements. If the variable $foo is an array of five elements, the argument $foo will expand to five elements. When quoted, like "$foo", a variable expansion will always result in exactly one argument.

Though I think the more intuitive way is to allow it, but that might result in additional difficulties (variables that include an "=" element).

>one of the biggest benefits of using Fish for scripting over Bash is that you don't have to worry about quoting variables

I'd say it's that unquoted variables are actually useful - in bash you should quote basically everything while in fish both quoting and not quoting are useful at different times.

**Comment by alphapapa** [comment]
Thanks, I think I understand it better now.

**Comment by GReagle** [comment]
This might be obvious, but to clarify this issue's title's mention of "test built-in", the issue applies to `command test` (/usr/bin/test) as well.  It probably applies in other situations besides `test`, but I cannot think of any examples now.

To summarize, you don't have to worry about quoting in fish for the case that a variable has spaces in it, but you do have to worry about quoting in case a variable is an array.  Is that right?

**Comment by faho** [comment]
>To summarize, you don't have to worry about quoting in fish for the case that a variable has spaces in it, but you do have to worry about quoting in case a variable is an array. Is that right?

For this particular bug, yes. In general, that's incomplete. Unquoted variables in fish expand to exactly as many arguments as they have values (each value becoming an argument - no word-splitting or anything). If they are quoted, they expand to one argument containing all values joined with spaces (i.e. `set fish flounder catfish; printf "%s\n"` prints "flounder catfish" with a newline after it). So that means regarding our current test (or `command test`) you need to guard against both the "array" (i.e. more than one value) case _and_ the "undefined" (or zero values) case - see #2037.

Now there are some outright bugs in our current test parser (#2332), but plenty of it is also because `test` is currently one of the few places where we follow POSIX, which has some ridiculous requirements (like "`test -n` shall return true").

**Comment by GReagle** [comment]
Thank you faho.

**Comment by krader1961** [comment]
@floam Why did you add both the "question" and "enhancement" labels. Those are mutually incompatible. This should have been closed when @GReagle acknowledged the answer by @faho.

**Comment by floam** [comment]
I'd guessit had something to do with second thoughts after I added the first tag. "This one is debatable"
