### ISSUE TITLE
Execute an abbreviation from within a function/script

### ISSUE THREAD

**Issue by ByScripts** [fish-shell/fish-shell#2344]
I converted all my "simple" functions to abbreviations.

But some of complex function was using other functions (which are now abbreviations), and no longer works.

For example, I have an abbreviation "a2reload => sudo service apache2 reload" and I was using "a2reload" in another function.

Now I get the error "a2reload : command not found".

Could be great to be able to run an abbreviation with something like "abbr --run a2reload" for example.

Or maybe is there a workaround I don't know ?

Thank you.

**Comment by pickfire** [comment]
How did you set the *abbr*? `abbr a2reload  "sudo service apache2 reload"` or `abbr -a a2reload  "sudo service apache2 reload"`?

**Comment by ByScripts** [comment]
abbr a2reload 'sudo service apache2 reload'

Is there is difference when using `-a` option?

**Comment by pickfire** [comment]
```
       · -a WORD PHRASE or --add WORD PHRASE Adds a new abbreviation, where WORD will be expanded to PHRASE.
```

Well, I look in the examples provided to see how to use `abbr`. Try `abbr -h`.

**Comment by ByScripts** [comment]
There is no difference between `abbr xxx yyy` and `abbr -a xxx yyy`

I already read the help, the problem is not here. The abbreviation works well... but not when used inside a script/function ;)

**Comment by pickfire** [comment]
I think the abbrevation is only used on the shell and not in the script. Need to ask @ridiculousfish for this.

**Comment by ByScripts** [comment]
> I think the abbrevation is only used on the shell and not in the script.

Yes, it's exactly what I said :) It's for this reason I think it could be great to be able to run an abbreviation with something like `abbr --run a2reload` from within a function.

**Comment by pickfire** [comment]
Maybe you could try setting the abbreviation in the script.

**Comment by faho** [comment]
I'm pretty sure abbreviations are only expanded when interactive, though I'm not sure if we should keep that limitation.

>it could be great to be able to run an abbreviation with something like abbr --run a2reload from within a function

Well, it's _possible_ to add that to abbr, but since it's a fish script it would need to go through `eval` which I pretty much dislike, and it could result in weird edge-cases if we allow arguments to abbreviations - you'd need to double-escape parentheses and dollars.

**Comment by GReagle** [comment]
@ByScripts:  So you've learned that it is not necessarily appropriate to convert all your simple functions into abbreviations.  Change them back to functions if you want to use them inisde scripts.  What's wrong with functions?

**Comment by ByScripts** [comment]
The main reason is that functions don't allow to get the real command
in shell history

2015-09-24 19:57 UTC+02:00, GReagle <notifications@github.com>:
> @ByScripts:  So you've learned that it is not necessarily appropriate to
> convert all your simple functions into abbreviations.  Change them back to
> functions if you want to use them inisde scripts.  What's wrong with
> functions?
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/fish-shell/fish-shell/issues/2344#issuecomment-143004779


-- 
--

*Thierry Goettelmann*
Développement Web
thierry@byscripts.info
