### ISSUE TITLE
[doubt] Customize fish_greeting colors

### ISSUE THREAD

**Issue by felipebernardes** [fish-shell/fish-shell#2346]
Hello folks, I'm a fish new user and I couldn't customize my fish_greeting text colors - actually I don't even have a clue of how to do it, even if I've read it's documentation. 

Could you guys give me some directions on how to do it?

Thanks!

**Comment by pickfire** [comment]
You can create a `fish_greeting` function:
```fish
function fish_greeting
    echo Here is your message in (set_color red) red(set_color white).
end
```

**Comment by faho** [comment]
pickfire's pretty much right. See [the documentation](http://fishshell.com/docs/current/faq.html#faq-greeting):

>How do I change the greeting message?

>Change the value of the variable fish_greeting or create a fish_greeting function.

If you like, you can also see the definition - check share/functions/__fish_config_interactive.fish.

**Comment by pickfire** [comment]
Good luck and have a nice day! This issue is now solved.

Thanks for reporting this, @faho I hope you can bold the **function** and the **variable** in the documentation to make it more visible.

**Comment by felipebernardes** [comment]
@pickfire & @faho ,

Thank you very much for your attention and support. You guys (and fish shell) are awesome!
