### ISSUE TITLE
psub does not allow cooperative multitasking

### ISSUE THREAD

**Issue by kwaze** [fish-shell/fish-shell#2348]
In your Bash prompt enter `less -f <(yes | awk '{print NR}')`. Compare that to `less (yes | awk '{print NR}' | psub)` in Fish which makes the shell freeze.

**Comment by kwaze** [comment]
Using named pipes:
    mkfifo numbers.fifo
    yes | awk '{print NR}' > numbers.fifo&
    less numbers.fifo
and when you exit `less`, do
    rm numbers.fifo

**Comment by faho** [comment]
>That works. Maybe psub could be changed to work that way?

That's what psub is supposed to do unless invoked with the "-f"/"--file" option, but there's a bug. Try again with a17b9fdabaccb126b4e619b861cc914568616933.

**Comment by faho** [comment]
Oh, we actually already have a bug about this: #1040. Closing this as a duplicate.

**Comment by geoff-codes** [comment]
Actually, this is isn't #1040, its much more along the lines of #238 - #563 - #1396.
 Basically, bash forks at all command and process substitutions, fish does not.

 Using your example @kwaze, we can reproduce the same issue without sub with something like:

```fish
mkfifo numbers.fifo
function yesawk
  yes | awk '{print NR}'
end
yesawk > numbers.fifo &
... # hang
```

Which is definitely a big annoying fish bug. However, for your particular case, why is
```fish
yes | awk '{print NR}' | less -f
```
insufficient? Process substitution is always icky, even in other shells. Its all about the pipeline! :wink:

**Comment by faho** [comment]
>Actually, this is isn't #1040, its much more along the lines of #238 - #563 - #1396.

Some combination of those as applied to psub _is_ this and 1040.
