### ISSUE TITLE
fish_config (webconfig) doesn't install fish_right_prompt

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#2350]
The sorin theme has a fish_right_prompt function that is not installed if selected via fish_config (see #2100).
This is because webconfig.py only does a `funcsave fish_prompt`.

Of course it'd be easy to add `funcsave fish_right_prompt`, but I'm not convinced something as simple is the right thing to do. This is because the prompt selector only shows the left prompt, so there's no preview for the user, and not even a way of knowing if a theme has a right prompt (short of looking at the source). This might result in surprised users who didn't backup their hand-rolled right prompts (I for one have such a thing).

I see a few viable courses of action:
1. Disallow right prompts in themes
2. Also show the right prompt, always install it along with the left one
3. Also show the right prompt, add a checkbox to install it
4. Make right prompts completely separate

Now, the drawbacks and advantages for 1 are obvious - no nice right sample prompts shipping with fish (i.e. fish is less cool), but also no work.

2 is a little more work (especially the preview part) and always results in a consistent prompt-style. However users can't then easily pick and choose (that would involve copying fish_right_prompt, setting the prompt and copying it back).

3 means users get to keep their right prompts if they wish, but doesn't make it easy to choose a different one

4 could be a lot of work - I haven't dug too deep into the source - but also carries the most payoff.

There's also the five-minute hack of adding something like 

``` fish
functions -q fish_right_prompt; or function fish_right_prompt [...]
```

to the sorin prompt since that's the only fish_right_prompt currently in the repo.

Edit: #736 is also related, but that deals with the even more general problem of more functions in sample prompts.

**Comment by pickfire** [comment]
A win-win situation users and developers:
- **show preview** shows *fish_right_prompt* in `fish_config`
- `fish_config` set *fish_right_prompt* just like how it set *fish_prompt*
- Et Cetera.

This could make developers develop theme in the future more easily. I think we could just merge the right prompt into `webconfig.py`.

**Comment by krader1961** [comment]
Removing from the 2.6.0 milestone since this is clearly not a priority for the next minor release. Having said that my feeling is that we should use solution #2 in @faho's list of options. That's because when selecting a fish prompt you're really selecting a theme. Which is an all or nothing proposition in my opinion. Which means you get both the left and right prompt. Thus this issue boils down to the fact that `fish_config` does not display the `fish_right_prompt` if it is part of the theme.  That we don't do a `funcsave fish_right_prompt` is a trivial aspect of the fundamental problem.

**Comment by faho** [comment]
Duplicate of #736.
