### ISSUE TITLE
Maven Completion

### ISSUE THREAD

**Issue by jschneider** [fish-shell/fish-shell#2352]
I have created a maven completion file: 
Any interest to integrate that?

https://github.com/jschneider/fish-maven-completion

**Comment by faho** [comment]
Sure!

- Clone this repo

- Put your completion file in share/completions/

- Open a PR

Some guesses as to what could be improved (I'm not familiar with maven):

- It probably only takes one "command" - if that's the case, what I always do is put them into a local variable (called "commands", unsurprisingly), and then do `complete -c $COMMAND -n "not __fish_seen_subcommand_from $commands" -a "$SOMECOMMAND" -d "$SOMEDESCRIPTION"` - see e.g. the `timedatectl` completions

- You can cut on some sed invocations by using "-e EXPRESSION" to add multiple expressions to a single sed

- `complete`'s "-o" is for old-style single-dash options (like `find`'s "-name") that can't be grouped (unlike, say `ls -lah`) - does maven really use that?

- For all plugins at the bottom - are those always all installed? Is there a way to generate that list? Or wouldn't it be nice to add descriptions (either via the "-d" option, or by feeding the "-a" option something like "option\tdescription\noption\tdescription" with \t being a tab character and \n being a newline)

**Comment by zx8** [comment]
I use maven on a daily basis so would certainly like to see this make its way upstream! :smile:

**Comment by jschneider** [comment]
Pull request: https://github.com/fish-shell/fish-shell/pull/2387

**Comment by jschneider** [comment]
@faho: Thanks for your suggestions.
I will answer your suggestions within the pull request #2387
