### ISSUE TITLE
vi mode 't' and 'T' bindings are broken

### ISSUE THREAD

**Issue by cpick** [fish-shell/fish-shell#2357]
Input functions with non-zero arity (`forward-jump` and `backward-jump`) are broken when they're followed by another function in a binding.

For example, in vi mode, `fish_vi_key_bindings.fish` has the following two entries:
```
bind t forward-jump and backward-char
bind T backward-jump and forward-char
```

When `t` is pressed in normal-mode, the binding is evaluated and `input_mapping_execute()` starts going through `m.commands` in reverse.  If the function has a non-zero arity, `input_function_push_args()` reads and saves the arguments.  The function's code is then pushed into the front of the input's lookahead deque.

The trouble is that if the binding has a non-zero arity function followed by some other function (in the case of the above `t` binding: `forward-jump` followed by `and`) the second function's code (`R_AND`) will get pushed into the lookahead deque and than is erroneously read in as the argument for the non-zero arity function (`forward-jump`) in place of the next key typed by the user.  (`forward-jump` will then search for `R_AND` in the current line and then fail because it's never found, causing backward-char to be skipped and no effect overall.)

**Comment by krader1961** [comment]
Thank you for the exceedingly detailed explanation to my comments about the change.  This is very subtle.  In your example the 'x' is the argument to be passed as the argument to __forward-jump__ notwithstanding the presence of other operators in the binding. This does appear to solve that specific problem. The question is whether this correctly handles more complex patterns. I think it does but would like to see some unit tests.

**Comment by cpick** [comment]
There aren't any more complex patterns at this time: "forward-jump" and "backward-jump" are the only two non-zero arity functions that currently exist.  If/when more are added this solution may need to be rethought, but with just those two currently present this change works as users would expect.  Additionally, the unit test I added to cover the one existing case seems sufficient to me.  I'm happy to add more tests if any come to mind, but for now writing new tests for other zero-arity functions would seem to duplicate existing tests.

**Comment by krader1961** [comment]
Okay, I'm satisfied with this PR as it currently stands. I think @ridiculousfish should have the final say on merging it since he understands the logic being modified far better than I do.
