### ISSUE TITLE
MSYS, Mingw-w64: connect not recognized

### ISSUE THREAD

**Issue by IngwiePhoenix** [fish-shell/fish-shell#2360]
I followed the autotools instructions and generated the `configure` script. What happened is that it told me that `a socket library` was missing and `connect` was required. So I went and installed that:

```
pacman -Ss mingw-w64-x86_64-connect
```

That installed a `libconnect.a` inside the mingw folder. However, the configure script does not seem to pick it up and work with it.

Is there something I can do to get around this?

**Comment by zanchey** [comment]
That's not the right library - https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-connect/PKGBUILD suggests that's a SOCKS client.

You might want to have a look at the MSYS2 package (https://github.com/Alexpux/MSYS2-packages/blob/master/fish/PKGBUILD) and build using those flags.

**Comment by adamkruszewski** [comment]
Seems it will be of no use. Fish uses socket.h which isn't available under mingw. Someone would need to port it to use winsock.h when #define win32 is present.

**Comment by ridiculousfish** [comment]
We ought to be able to compile all of that out in Windows ("that" being check_running_fishd). it's just some compatibility junk. In fact we could probably even remove it for everyone in fish 2.3.0.

**Comment by krader1961** [comment]
We're so close to pushing 2.3.0 out the door I vote for removing that code after that's done. It's basically harmless, right? Other than causing build problems on MINGW, that is.

**Comment by ridiculousfish** [comment]
Yeah, let's do it.
