### ISSUE TITLE
error after installed vcprompt

### ISSUE THREAD

**Issue by jy03189211** [fish-shell/fish-shell#2363]
The shell prints errors as follows after I installed vcprompt
fish: Unknown command 'hg'
/usr/local/Cellar/fish/2.2.0/share/fish/functions/__fish_hg_prompt.fish (line 1): hg branch ^/dev/null
                                                                                  ^
in command substitution
	called on line 22 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/__fish_hg_prompt.fish

in function '__fish_hg_prompt'
	called on line 24 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

**Comment by faho** [comment]
I believe this is now fixed in cb5511c, if not, please comment.

Thanks for reporting this!

**Comment by ferologics** [comment]
I'm having the same issue, what should I do?

```fish
fish: Unknown command 'hg'
/usr/local/share/fish/functions/__fish_hg_prompt.fish (line 1): hg branch ^/dev/null
                                                                ^
in command substitution
	called on line 22 of file /usr/local/share/fish/functions/__fish_hg_prompt.fish

in function '__fish_hg_prompt'
	called on line 24 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input
}
```

**Comment by faho** [comment]
@ferologics: Either apply f94affa manually (`funced __fish_hg_prompt`, edit it in and then `funcsave __fish_hg_prompt`) or update to git fish. Or change your fish_prompt to not call hg - if you're not using it, the function call is wasted anyway.

**Comment by ferologics** [comment]
What about brew fish?

**Comment by faho** [comment]
@ferologics: As some searching tells me, `brew install --HEAD` would update your fish to the current development version (git HEAD). Do keep in mind that it might break stuff (nothing I'm aware of, though) - changing the fish_prompt or __fish_hg_prompt functions is definitely the safer approach. Not that I'm against more testing.
