### ISSUE TITLE
Don't complete arguments for non-existent commands

### ISSUE THREAD

**Issue by spider-mario** [fish-shell/fish-shell#2365]
Hi,

I use fish 2.2.0 on Arch Linux and if I open a new shell (the bug does not seem to occur twice in the same session) and type `xrandr` + space, I get the following output:

```
$ xrandr xrandr may be found in the following packages:
  extra/xorg-xrandr 1.4.3-1     /usr/bin/xrandr
/usr/share/fish/completions/xrandr.fish (line 1): xrandr -v | grep RandR | sed 's/^.\+\s\([0-9\.]\+\)$/\1/'
                                                  ^
in command substitution
        called on line -1 of file /usr/share/fish/completions/xrandr.fish

from sourcing file /usr/share/fish/completions/xrandr.fish
        called on standard input

in command substitution
        called on standard input

expr: syntax error
```

**Comment by faho** [comment]
>xrandr may be found in the following packages:
  extra/xorg-xrandr 1.4.3-1     /usr/bin/xrandr

It appears like you don't have xrandr installed.

There is a bug here, but it's a very minor one - if a program isn't installed, fish still tries to complete it (even though it could never run the resulting line).

That is of course unless I'm wrong - I'm a bit confused by the fact that it seems to be triggered via _space_, not _tab_ - did you rebind that?

**Comment by bucaran** [comment]
> I'm a bit confused by the fact that it seems to be triggered via space, not _tab_

AFIK fish autocomplete is always _on_ instead of being a separate mode. So we have continuous feedback while writing the cli, and not only when one presses tab.

**Comment by spider-mario** [comment]
> It appears like you don't have xrandr installed.

Yeah, I figured that bit out. :p Hence the title of the bug report.

No rebinding either, it indeed seems to be caused by continuous feedback.

> There is a bug here, but it's a very minor one - if a program isn't installed, fish still tries to complete it (even though it could never run the resulting line).

For certain completion scripts, this would not necessarily be a problem. For example, the completion script for `wget` does not seem to call `wget` (although it does call `ifconfig` without checking). The completion script for `valgrind` does, but it also contains an explicit check:

~~~fish
# Don't go invoking valgrind unless it is installed

set -l skin tool
if begin ; type valgrind >/dev/null ; and valgrind --version ^/dev/null | sgrep -- '-2\.[012]\.' >/dev/null ^/dev/null ; end
~~~

**Comment by faho** [comment]
>For certain completion scripts, this would not necessarily be a problem.

Yeah, I actually now managed to reproduce with xrandr (i.e. by uninstalling it and opening a new shell just to be sure).

The reason I stated the issue as such is that I can't see why you'd _ever_ want completion for a program that doesn't exist. Even if it could complete something (and options and such would certainly work), fish couldn't execute that line, so you actually couldn't do anything with it. Fish has definite knowledge of what it can execute and what it can't, so this should be perfectly doable - it already colors it in for you.

 >The completion script for valgrind does, but it also contains an explicit check:

Yeah, but that's annoying at scale. This means adding something like that to _every_. _single_. _completion_ _script_. (except dependencies of fish itself).

>although it does call ifconfig without checking whether it’s installed either

Removing ifconfig/adding another option is on my plate (and I'd try to get some nice abstractions) - though I tried to add `ip` completions first and that's... not something you should be doing if you wish to keep your hair.

**Comment by faho** [comment]
@fish-shell/contributors: Anyone know why we currently try completions even for commands we can't find? If there's a reason I'll go hack the individual scripts but I can't see one.

**Comment by pickfire** [comment]
I think I have some problems that are similar to this issue once. I forgot what is the problem.

**Comment by zanchey** [comment]
I actually like the fact that completions are invoked for non-existent commands because it helps me in testing, but I can't justify the behaviour in the general case. Expecting all completion authors to do `type -q xyz; and xyz` seems unfair.

**Comment by zanchey** [comment]
There is another small case where this is useful - if you are using the completion in a pipeline which generates the executable... e.g. `make fish; ./fish -<TAB>`. Pretty nice though.

**Comment by krader1961** [comment]
I agree with @faho that this should be solved in a generic manner. Which is to say, command completion should not be invoked if the command is not found. I think the situations where the current behavior can be useful, such as that mentioned by @zanchey on 10/29, are too atypical for this to be the default behavior. Especially when compared to the cost of requiring that every completion which needs to invoke the command in order to provide a meaningful completion (e.g., the __git__ completions) test whether the command is actually present.

**Comment by ridiculousfish** [comment]
Sometimes I want to tab complete invalid commands to get file paths, where I plan to go back and fix the command up later (usually after copying and pasting a long command). As a general principle, showing something for tab completion is usually better than showing nothing, if only to confirm the shell is responsive. So I think we should show at least file paths, if we can.

I propose we avoid *autoloading* completions for missing commands. The consequences would be:

1. Tab will stop producing error spew
2. Completions can still be tested by loading them manually: `source ./share/completions/xrandr.fish`
3. We'll still get generic file completions

What do you think?

**Comment by spider-mario** [comment]
How about simply running the completion script through `^> /dev/null` if the command that is being completed is not installed?

**Comment by ridiculousfish** [comment]
hmm, that's an interesting alternative...let me think about that

**Comment by faho** [comment]
That would make testing impossible, no?

One rather crazy option I could come up with was to always return to the command token if it's not found - the idea being that there's absolutely nothing fish can do if it can't find the command, so the user should fix that.

**Comment by floam** [comment]
> I propose we avoid autoloading completions for missing commands. The consequences would be:

I tried this in #3598.
