### ISSUE TITLE
set -x does not work when recursively defining functions

### ISSUE THREAD

**Issue by arthurfabre** [fish-shell/fish-shell#2367]
I have a function that defines another function, and then calls it.

    function foo
        set -x msg "This is bar!"
        function bar
            echo $msg
        end
        bar
    end

I would expect `msg` to be in scope in `bar`, but it isn't. Invoking `foo` prints a new line.
This works correctly when used directly at the prompt however:

    arthur@kef ~> set -x msg "This is test"
    arthur@kef ~> function test
                      echo $msg2
                  end
    arthur@kef ~> test
    This is test

**Comment by ridiculousfish** [comment]
`set` makes a variable scoped to the function by default. If you want to capture a variable, you can use `--inherit-variable` from cfc06203e7ad7707acadd160292d47b25d6daba6:

    function bar --inherit-variable msg ; echo $msg ; end

Alternatively, you can make the variable global with -g: `set -gx msg ...`.

**Comment by arthurfabre** [comment]
Thanks for the quick reply!

That seems to work for me.

Is there any interest in adding a flag to`function` to make it declare something that behaves more like a closure (ie it can inherit all variables from the scope it was defined in)?

**Comment by bucaran** [comment]
@arthurfabre Well, there is the `-S` or  `--no-scope-shadowing`, that can let you write a function that is able to access the variables declared in the calling function, thus making it somewhat similar to a closure in the fact that fish has no other scope than the global.

**Comment by arthurfabre** [comment]
Hadn't spotted that, thanks!
