### ISSUE TITLE
Is there a way to enforce an exclusive completion list per-program?

### ISSUE THREAD

**Issue by Fusty** [fish-shell/fish-shell#2368]
Let's say I have a function called "shish" and I want shish to take 1 argument.

That argument should ONLY be one of let's say 5 values "red blue orange green purple".

How can I define a completion such that things like "redOctupusUselessFile.txt" don't complete when present in the current directory?  Is there any way to achieve this behavior with fish?

**Comment by bucaran** [comment]
This should get you started.

```fish
complete --no-files -c shish -d "The Shish"
```

**Comment by Fusty** [comment]
Wow, thanks.  I thought I had already scoured the docs/man pages but it turns out I am blind.

-x is even better is it is exclusive and no files.  Thank you very much.

**Comment by zanchey** [comment]
I added the missing options to the synopsis in 8bf1e69.
