### ISSUE TITLE
Add `insert-comment` binding

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#2375]
In `bash`, out of the box, pressing `alt+#` results in the current line being commented out and executed (such that it's in your history, but not run): 

```
$ bash
$ bind -p | grep -a comment
"\e#": insert-comment
```

This is a common part of my daily workflow, e.g. I'll enter a long command, realise I need to run another command first, comment the current command out with `alt+#`, go back and run the other, the hit up twice uncomment the line, then execute it for real.

I've managed to replicate this behaviour in `fish` as follows:

```
function comment_line
  set -l cmd (commandline)
  commandline \#$cmd
  commandline -f execute
end
bind \e# comment_line
```

The only issue is - the line isn't repainted before it's executed, so syntax highlighting doesn't work properly. Any suggestions?

**Comment by zanchey** [comment]
I tried adding `commandline -f force-repaint`, but it didn't help.

I'm not sure this should go in the default bindings - the finger-mangling Alt+shift+3 on US keyboards doesn't seem to add much over Home, `#`, Enter. It works nicely for multi-line commands, though, thanks to the magic of Cartesian products.

**Comment by zx8** [comment]
@zanchey - I guess that's because of the following (from the `commandline` manpage):

<pre>
· -f or --function inject readline functions into the reader. __This option
cannot be combined with any other option.__ It will cause any additional
arguments to be interpreted as readline functions, and these functions will be
injected into the reader, so that they will be returned to the reader before
any additional actual key presses are read.
<pre>

So, since we're also `execute`ing it, it won't work. Trying to figure out a workaround.

**Comment by faho** [comment]
>So, since we're also executeing it, it won't work. Trying to figure out a workaround.

No, that just means that you can't call e.g. `commandline -op -f repaint`. We're calling `commandline` multiple times which is okay.

**Comment by zx8** [comment]
Ahh, right, got it. Thanks for the clarification.

**Comment by krader1961** [comment]
This request was also made by me in issue #2904. What we came up with was

```fish
function switch-comment-commandline --description 'Comment/Uncomment the current or every line'
    set -l cmdlines (commandline)
    commandline -r (printf '%s\n' '#'$cmdlines | string replace -r '^##' '')
    commandline -f execute
end

bind -M default -m insert \# 'switch-comment-commandline'
```

Obviously the binding is for vi-mode; use `\e#` if you're using emacs-mode. This requires you be running fish built from git head as I type this or the soon to be published 2.3.0 release.

We haven't decided if this should be part of the core features or simply documented as an unsupported, user contributed, feature.

**Comment by gechr** [comment]
@krader1961 Thanks. While this works well, as @zanchey mentioned in a previous comment, there's still an issue with repainting. That is, I tried adding `commandline -f force-repaint` before `commandline -f execute`, but the colours don't seem to update correctly.

**Comment by krader1961** [comment]
Operations that modify the appearance of the command, including moving the cursor, don't happen until the binding returns. And if the binding does a `commandline -f execute` then the appearance is not updated even if if it would have been had you manually commented or uncommented the lines. That's a limitation of the current key binding implementation. It's something I'd like to see changed but I don't think it's essential for this issue.

**Comment by gechr** [comment]
@krader1961 Cool, thanks for the explanation & PR. Much better than my attempt! 👍
