### ISSUE TITLE
Very strange issue with echo, set_color, and output redirection

### ISSUE THREAD

**Issue by alphapapa** [fish-shell/fish-shell#2378]
```
$ fish --version
fish, version 2.2.0
```
I've been converting a Bash script to Fish.  I have just encountered a very weird issue that is somehow causing `echo`'s output to go to more than just the terminal.  It seems to be getting passed to subsequently executed processes.  For example, here is a function in my script:
```fish
function setSinkInputVolume --description 'Set volume of sinkInputNumber'
    set volume $argv
    set sink $sinkInputNumber

    bash -c "echo  X\"pactl set-sink-input-volume $sink $volume\"X"
    bash -c "pactl set-sink-input-volume "$sink" "$volume
    python -c "import sys; print 'PYTHON'; print sys.argv" pactl set-sink-input-volume $sink $volume
    exit
end
```
The script is used to set a PulseAudio sink-input's volume.  The var `$sinkInputNumber` is set outside the function's scope, globally.  `$argv` is the volume to set.  (The calls to Bash and Python and the `exit` are there to help debug this problem.  Ideally it would just call `pactl` directly.)

Now I also have this function which I use to help debug:
```fish
function debug --description "Print debug message in yellow"
    set_color yellow
    echo "DEBUG: $argv" >&2
    set_color normal
end
```
I call it in a few places before the `setSinkInputVolume` function gets called.

Here is the strange behavior I am seeing:

1.  The third time I call `debug`, the text is not printed in color.
2.  When I then call `setSinkInputVolume`, somehow the color escape codes get passed as arguments to Bash and Python, as indicated by this output:
```
DEBUG: Playing /home/me/sound.mp4
DEBUG: ffplay PID: 23118
DEBUG: sink-input: 329
Xpactl set-sink-input-volume 329 5X
bash: -c: line 0: syntax error near unexpected token `('
bash: -c: line 0: `pactl set-sink-input-volume 329 5'
PYTHON
['-c', 'pactl', 'set-sink-input-volume', '\x1b[33m\x1b[30m\x1b(B\x1b[m329', '5']
```
As you can see, the second invocation of Bash picks up some of the escape codes and fails to parse its command because of finding a parenthesis.  Then you can see that Python picks up some of the escape codes as part of the `$sink` argument.

I have tried to isolate a minimal way to reproduce the problem, but so far I have failed.  The following code calls `debug` the same number of times with the same input as the problem script does, but it doesn't have the problem: 1) all `debug` calls print in yellow, and 2) there are no escape codes passed to Bash or Python:
```fish
#!/usr/bin/env fish

function debug --description "Print debug message in yellow"
    set_color yellow
    echo "DEBUG: $argv" >&2
    set_color normal
end

set volume 1
set sink 157
set sinkInputNumber 157
set player ffplay
set playerPID 13225

debug "Playing /tmp/test.mp4"
debug "$player PID: $playerPID"
debug "sink-input: $sinkInputNumber"

bash -c "echo  X\"pactl set-sink-input-volume $sink $volume\"X"
bash -c "pactl set-sink-input-volume "$sink" "$volume
python -c "import sys; print 'PYTHON'; print sys.argv" pactl set-sink-input-volume $sinkInputNumber $volume
```
Since I can't seem to isolate a way to reproduce it, I put the whole problem script in a gist: https://gist.github.com/alphapapa/c462b4a382367a8ce96e  To run it, you'll need these commands in your path:

* ffplay
* notify-send
* pactl

And then you should choose any random audio file and copy it to `/tmp/test.mp4`.  You should see output like this:
![argh](https://cloud.githubusercontent.com/assets/601365/9811540/8ebe5e6e-583d-11e5-9fd8-78782d60096a.png)

Note that if you comment out the `set_color` calls in `debug`, the problem goes away.

Thanks for your help.

**Comment by faho** [comment]
I think I've isolated the issue:

In `getSinkInputNumber`, redirect the `debug` call to stderr (again), like

```fish
function getSinkInputNumber --description "Get number of ffplay sink input from PA"
    set -l sinkInputNumber  # Define it as function-local because of Fish's block-local scoping

    # Wait for a result
    set i 0
    while test -z "$sinkInputNumber" -a $i -lt 10
        sleep 0.5
        set sinkInputNumber (pactl list sink-inputs | paawk '/'$player'/ { gsub("#", "", $3); print $3 }')
    end

    debug "sink-input: $sinkInputNumber" >&2

    # Make sure there's only one client
    if not test (count $sinkInputNumber) -eq 1
        die "More than one $player client found: $sinkInputNumber"
    end

    echo $sinkInputNumber
end
```

and it should work. It seems like the distinction between stdout and stderr is somehow lost in the command substitution, so the escapes end up in a variable.

**Comment by faho** [comment]
Nope, see your debug function again:

```fish
function debug --description "Print debug message in yellow"
    set_color yellow
    echo "DEBUG: $argv" >&2
    set_color normal
end
```

You're not redirecting `set_color`, so the output of that ends up in stdout, which ends up in your variables!

**Comment by alphapapa** [comment]
Ah, I see.  I didn't realize that `set_color` actually outputs; I thought it just set some internal shell state.  I just checked the documentation, and the help for the command doesn't explain that.

Maybe I'm wrong, but this still feels like a bug to me.

1.  Even though I didn't redirect `set_color` to STDERR, the `echo` statement still gets output with color (except for the last time).  This seems inconsistent; it seems like either a) one should have to use `set_color` with the same redirection as the echo statement, or b) calling `set_color normal` should not add escape codes to later command substitutions.
2.  It doesn't make sense--or, at least, it's completely unintuitive--that calling `set_color` in one place and using command substitution in another place causes the command substitution to pick up the escape codes from `set_color`.  Is there a buffer that needs to be flushed, or something like that?

Thanks for the tip about doing it all in one command.  I'll use that now.

By the way, if `echo` had a color option (as suggested in #2343), this could easily be avoided.  This seems like a "gotcha" that will likely bite people like myself who are converting Bash scripts to Fish to make use of Fish's features.  It doesn't seem like `set_color` should be so "dangerous" of a command.

I say this because it was _extremely_ confusing when I encountered this.  The errors I got from `pactl` made no sense, because even when I did `echo "pactl set-sink-input-volume $sink $volume"`, or used `eval`, or ran it through Bash, there was no apparent reason the command was failing.  The escape codes weren't visible, so it looked like `$sink` was merely a number, like it was supposed to be.  It was only when I passed it through Python that I was able to see the escape codes and figure out what was going on.

So, if `echo` had a color option that automatically reset to normal color, this whole issue could be avoided, and `set_color` could be documented as a command that should only be used when `echo --with-color` isn't suitable for some reason.

Or, at least, it might be easier to do that than fix this bug... ;)

Thanks for your help!

**Comment by faho** [comment]
>It doesn't make sense--or, at least, it's completely unintuitive--that calling set_color in one place and using command substitution in another place causes the command substitution to pick up the escape codes from set_color. Is there a buffer that needs to be flushed, or something like that?

It's actually completely logical. `set_color` outputs these codes to stdout, and when your terminal receives them, it interprets them. Try `set_color yellow | od -a` and compare to `set_color normal | od -a`. Now try `echo banana(set_color yellow)bread(set_color normal) | od -a`.

This is also why, even though you make good points from the user's perspective, I don't see too much for fish to do here other than document it better, though this isn't my strong suit.

@zanchey: Any thoughts?

**Comment by alphapapa** [comment]
> It's actually completely logical. set_color outputs these codes to stdout, and when your terminal receives them, it interprets them. 

That part makes sense, of course.  :)

But what doesn't make sense is for `set_color` to get captured into a later command substitution.  After all, that doesn't even go through the terminal.

It's also strange that I can't seem to simply reproduce the problematic behavior.  Here is my latest attempt:
```fish
#!/usr/bin/env fish

function debug
    set_color yellow
    echo "DEBUG: $argv" >&2
    set_color normal
end

debug blah
debug foo
debug bar
debug

set_color red
set date (date)
set one 1
set two 2

python -c "import sys; print sys.argv" a b $one $two $date
```
I've tried everything I can think of (at the moment...a bit tired haha) to somehow leave a dangling escape code for a `set` to catch, but it's not happening.  No escape codes are getting captured into any variables.  Python prints in red, but all the arguments are correct, free of escape codes.

So, as best I can tell, something is definitely fishy (and not in the good way ;) ).

**Comment by faho** [comment]
With your debug function above, just do

```fish
set -l bass (debug)
python -c "import sys; print sys.argv" $bass
```

You'll see "DEBUG: " in the terminal and python printing escape codes in argv.

Essentially, the `set_color` needs to be called in a command substitution without being redirected to stderr. The shortest example is this:

```fish
python -c "import sys; print sys.argv" (set_color yellow)
```

everything else boils down to this.

>But what doesn't make sense is for set_color to get captured into a later command substitution. After all, that doesn't even go through the terminal.

Of course it does - in a command substitution, stdout of the commands in it go to fish, which then takes what comes through there and puts it in place of the command substitution (substitutes it, as it where).

**Comment by alphapapa** [comment]
Okay, I think I get it now:
```fish
#/usr/bin/env fish

function debug
    set_color yellow
    echo DEBUG: $argv
    set_color normal
end
function getSomething
    debug "Getting something"
    echo foobar
end

set something (getSomething)
python -c "import sys; print sys.argv" $something
```
Yep, that does it:
```
['-c', '\x1b[33mDEBUG: Getting something', '\x1b[30m\x1b(B\x1b[mfoobar']
```
I knew there was something I wasn't getting.  I forgot that I was capturing output from functions that I also called debug inside of.

So, in conclusion:

1.  It seems that it's a best-practice (or maybe even a you-should-always-do-it-this-way-unless-you-really-know-what-you're-doing) to use the `echo (set_color color)$var(set_color normal)` pattern, rather than using `set_color` as separate commands before and after the `echo`.
2.  Again, I think that this makes a strong case for `echo` having a built-in color option.  This seems like a major gotcha waiting to bite people who do any moderately serious scripting in Fish, and giving `echo` a color option would completely solve it.
3.  Whether or not that ever happens, I think the docs need some kind of "NOTE" or "WARNING" box in the `set_color` section that gives an example of this behavior and how and why to avoid it.  Again, I say this because of how mind-boggling it was before I figured it out.  I had code like this:
```fish
echo "command $foo $bar"
command $foo $bar
```
And the output from `echo` looked completely correct, yet the `command` failed saying that it got an invalid argument.  Having to resort to using Python to be able to see the escape codes and figure it out seems like something we should try to help people avoid.  :)

Thanks again for your patient help with this.  I should have figured this out on my own, but I appreciate your helping me do it quicker.  :)

**Comment by faho** [comment]
>And the output from echo looked completely correct, yet the command failed saying that it got an invalid argument. 

I got it! The output from echo looked normal because the variable contained the equivalent of `(set_color yellow)(set_color normal)SOMETEXT` - it's not colored in because before any text the color is reset, and it's not showing any weird characters because your terminal swallows them.

>Having to resort to using Python to be able to see the escape codes and figure it out seems like something we should try to help people avoid. 

That's certainly correct and something `string escape` might help with once #2296 is merged.

**Comment by faho** [comment]
@alphapapa: My proposed text (to be inserted at the end of http://fishshell.com/docs/current/commands.html#status, before the examples):

>Since `set_color` works by printing escape sequences that are to be interpreted by the terminal,these may end up in variables or command substitutions. See <a href="commands.html#status">status</a> (in particular the "--is-command-substitution" option) for ways to guard against this.

Okay?

**Comment by alphapapa** [comment]
I'm confused, did you mean to link to the `set_color` command?

Thanks for pointing out `status --is-command-substitution`.  I hadn't thought of that.  I guess the problem could be worked around by using a `debug` function like this:
```fish
function debug_message --description "Output a debug message in color"
    if status --is-command-substitituion
        set -l prefix (set_color yellow)
        set -l suffix (set_color normal)
    else
        set -el prefix
        set -el suffix
    end
    echo {$prefix}{$argv}{$suffix} >&2
end
```
About the doc change, I would suggest making it clear that `set_color` immediately outputs escape codes to STDOUT.  As it is, the current description says that it "changes the color of the terminal," but it's not clear that it immediately gives output rather than setting some internal state that may affect future output.  I would suggest this:
> `set_color` outputs escape codes to change the foreground and/or background color of the terminal.  COLOR is one of black, red, green, brown, yellow, blue, magenta, purple, cyan, white and normal.
>...
>
> NOTE: These escape codes may be captured in command substitutions, which may cause problems if done unintentionally.  To avoid this, you may wish to use `status --is-command-substitution` to determine whether to call `set_color`.

And if you're not too concerned about the space, I'd suggest using this `debug_message` function in its entirety as an example after the note.

Thanks for your work on this.

**Comment by faho** [comment]
>I'm confused, did you mean to link to the set_color command?

Yes, sorry.

> set -l prefix (set_color yellow)
set -l actually does block-level scope, so this will be undefined later regardless (yes, there's a bug about that).

> echo {$prefix}{$argv}{$suffix} >&2
Without quotes, this does a cartesian product, meaning there's no argument if prefix or suffix is undefined.

>About the doc change, I would suggest making it clear that set_color immediately outputs escape codes to STDOUT

That's a good point. I would however like to keep the high-level "it changes colors" as the first thing the user reads - because that's what it does, the escape thing is an (unavoidable, it seems) implementation detail. It's sad that this abstraction leaks, but that doesn't mean we should stop using it completely.

>And if you're not too concerned about the space, I'd suggest using this debug_message function in its entirety as an example after the note.

Well, not every way you can read these escapes is in a command substitution - think of `while read`, and what you want to do depends on the situation. In your case for example you just needed to redirect set_color to stderr as well.

**Comment by alphapapa** [comment]
> I would however like to keep the high-level "it changes colors" as the first thing the user reads - because that's what it does, the escape thing is an (unavoidable, it seems) implementation detail. It's sad that this abstraction leaks, but that doesn't mean we should stop using it completely.

I understand.  I just suggest making it very clear (not buried in the middle of a paragraph) that `set_color` outputs escape codes immediately, rather than setting internal state.

> Well, not every way you can read these escapes is in a command substitution - think of while read, and what you want to do depends on the situation.

That's a good point.  I wonder, would it be good for the `status` command to have a `--in-pipeline` option to complement `--is-command-substitution`?

**Comment by faho** [comment]
>That's a good point. I wonder, would it be good for the status command to have a --in-pipeline option to complement --is-command-substitution?

There is `test -t`. The problem with adding it to "status" is that we have stdout, stderr and stdin, any one of which can be attached to a terminal or a pipe, so it would have to take an argument which is uncharacteristic for status.

**Comment by faho** [comment]
For the record: `test -t` is currently broken, see #1228. The workaround is `command test` i.e. /bin/test.

**Comment by alphapapa** [comment]
> There is test -t. The problem with adding it to "status" is that we have stdout, stderr and stdin, any one of which can be attached to a terminal or a pipe, so it would have to take an argument which is uncharacteristic for status.

Could `status --in-pipe` return true if any of stdout, stderr, or stdin are pipes?  It seems like that would be useful, and would avoid having to do something like
```fish
if test -t 0; or test -t 1; or test -t 2
```

**Comment by faho** [comment]
>Could status --in-pipe return true if any of stdout, stderr, or stdin are pipes?

What's the use case for that? Sure, the code is simpler, but what would you use it for?

You'd check if stdin is a tty to e.g. read from it if it isn't - you need special code for that.

You'd check if stderr is a tty for your original code here, because you want to color if your output goes to a terminal. (You'd check stdout if you want to output to stdout)

Either way, the code for output is bound to be different than the code for input, so if there's any difference between a tty and not-a-tty, you'll have to handle it separately.

**Comment by alphapapa** [comment]
The use-case I was thinking of was to avoid calling `set_color` when in a pipe to avoid sending escape codes to another process.  I guess you can use `test -t /dev/stdout` to handle most cases.

**Comment by faho** [comment]
>The use-case I was thinking of was to avoid calling set_color when in a pipe to avoid sending escape codes to another process.

If your output is going to stderr, you need to check stderr (and redirect set_color to it) because what do you care if stdout is not a tty? Or stdin, for that matter? This is not a case for an "any of these" check. 

I agree that it's a bit weird that the check is in `test` instead of `status`, but `test` is one of the parts we follow POSIX on, and that pretty much just codified stuff that evolved that way over the decades. An implementation in status would only be duplication, and I can't say I love that. 

We also have the `isatty` function (which currently works since it has a workaround for the bug) as a wrapper.

**Comment by zanchey** [comment]
@faho, did you end up merging this documentation change? I can't see it.

**Comment by faho** [comment]
@zanchey: Doesn't look like it.
