### ISSUE TITLE
Process expansion not working correctly

### ISSUE THREAD

**Issue by alphapapa** [fish-shell/fish-shell#2379]
```
$ fish --version
fish, version 2.2.0
```
```fish
#!/usr/bin/env fish

ffplay -nodisp -autoexit -loop 0 /tmp/test.mp4 >/dev/null ^&1 &

echo "Fish thinks the PID is: " %ffplay
ps %ffplay

echo

echo "The PID is actually: "(pgrep ffplay)
ps (pgrep ffplay)

killall ffplay
```
Output:
```
Fish thinks the PID is:  25516
  PID TTY      STAT   TIME COMMAND
25516 pts/1    S+     0:00 fish /tmp/test.fish

The PID is actually: 25653
  PID TTY      STAT   TIME COMMAND
25653 pts/1    Sl+    0:00 ffplay -nodisp -autoexit -loop 0 /tmp/test.mp4
```
All I want is to capture the PID of the last process put into the background.  All I can find in the manual is to use `%name` syntax, which isn't working.

Besides this apparent bug, doesn't Fish need an equivalent to Bash's `$!`?  For example, in Bash I would do:
```sh
ffplay &
pid=$!
```
But using Fish's `%name` syntax, if there were more than one process with a certain name, then `%name` wouldn't necessarily return the correct process.

**Comment by faho** [comment]
>Besides this apparent bug, doesn't Fish need an equivalent to Bash's $!?

`jobs`, specifically `jobs -lp`, though for some reason it still prints a line "Process".

**Comment by alphapapa** [comment]
Thank you!

**Comment by faho** [comment]
Anything we can do to improve it? Better documentation? (The % stuff could use some major love as well, but I think we already have a bug about that)

**Comment by alphapapa** [comment]
Well, I wouldn't mind if Fish had `$!`, but that's not very Fishy.  Since we have `%self`, it seems like `%last` would be a sensible keyword, or something like that.  It would be nice to be able to use that instead of `(jobs -lp)`.

Improved documentation would definitely help.  I grepped through the docs for `pid` and `$!`, but `jobs` didn't stand out as the proper equivalent of `$!` when I was quickly scanning.

There's probably already a bug for this, but I think it would great if there were a "From Bash to Fish" guide that would explain the Fishy equivalents of standard Bashisms (or just plain "`sh`isms").  It wouldn't need to be verbose, just a simple "translation" table with Bash/sh in the left column and Fish in the right column.

**Comment by ridiculousfish** [comment]
%last already exists:

    > cat & ; echo %last
    27667

**Comment by alphapapa** [comment]
It does?  Hm.  Am I missing something, or is it not documented anywhere?  I can't find it in any of the manual pages.

**Comment by faho** [comment]
>Well, I wouldn't mind if Fish had $!, but that's not very Fishy. Since we have %self, it seems like %last would be a sensible keyword, or something like that. It would be nice to be able to use that instead of (jobs -lp).

I find it kinda funny that we have something with the exact wording you suggested :laughing:. Anyway, I've added a line of documentation for now.

>There's probably already a bug for this, but I think it would great if there were a "From Bash to Fish" guide that would explain the Fishy equivalents of standard Bashisms

I don't think there is, and you're right that there should be, it's a great idea! I'll go open a bug.

**Comment by ridiculousfish** [comment]
Thanks faho. %last has been there since fish 1.x, it just was never documented!

**Comment by alphapapa** [comment]
That is funny.  I'm guess I'm Fishier than I realized.  :D 

Thanks!
