### ISSUE TITLE
Should a hashtag # start a comment even when not preceded by a space?

### ISSUE THREAD

**Issue by bucaran** [fish-shell/fish-shell#2380]
How come

```fish
echo a#
```

Prints `a#` instead of just `a`?

This can be a source of hard to find bugs if you forget to add a space:

```fish
set -l var ""# oops
...
echo $var
```

```
# oops
```

**Comment by faho** [comment]
I can't find a single occurence of that in our fish code - `grep "[^[:space:]\"'\\#]#" -r share/{functions/,completions/,tools/web_config/sample_prompts/}` prints some lines, but all of those are either already in comments (like "See #XYZ") or in quotes.

And bash behaves exactly like this; `echo a#b` there prints "a#b".

Overall, I don't know what to think about this.

**Comment by bucaran** [comment]
I have been bitten by this a couple of times, but I have grown to catch these in the spot.

Here is another example

```fish
function hi
  echo hi
end#
```

You may close the issue then, but now we have it for the record :smile:

**Comment by ridiculousfish** [comment]
This was done for #953. URLs are a motivator.

Closing, thanks bucaran!
