### ISSUE TITLE
(feature request) highlight command names

### ISSUE THREAD

**Issue by f1u77y** [fish-shell/fish-shell#2385]
fish highlights command names after `and` and `or`. i think it will be good to make such feature for common unix command such as `sudo` or `nohup`.

**Comment by ridiculousfish** [comment]
Yes! That's planned as part of #478. Once we have a programmatic description of the command's usage specs, we can do a better job colorizing and tab-completing arguments that are themselves commands.

Closing as dup of #478. Thanks for filing this!
