### ISSUE TITLE
environment is not available when sourcing /etc/fish/config.fish

### ISSUE THREAD

**Issue by Profpatsch** [fish-shell/fish-shell#2391]
My problem: I’m trying to source files in an env variable.

For that I append the following to my `/etc/fish/config.fish`

```fish
    echo DEBUG
    env
    echo DEBUG2
    for p in $FISH_SOURCE_PATHS
      echo "sourced $p"
      source "$p"
    end
```

a file foo `echo "echo foo" > ~/foo

and call

```fish
~> env -i FISH_SOURCE_PATHS=/home/philip/foo fish
DEBUG
FISH_SOURCE_PATHS=/home/philip/foo
HOME=/home/philip
PATH=/usr/bin:/bin
PWD=/home/philip/nixpkgs
SHLVL=1
USER=philip
__fish_bin_dir=/nix/store/aq5yv3i6ln4w84y2ais5m2j5a6z0djsz-fish-2.2.0/bin
__fish_datadir=/nix/store/aq5yv3i6ln4w84y2ais5m2j5a6z0djsz-fish-2.2.0/share/fish
__fish_help_dir=/nix/store/aq5yv3i6ln4w84y2ais5m2j5a6z0djsz-fish-2.2.0/share/doc/fish
__fish_sysconfdir=/nix/store/aq5yv3i6ln4w84y2ais5m2j5a6z0djsz-fish-2.2.0/etc/fish
DEBUG2
```

It should print `foo` after `DEBUG2`.

Even a simpler command like `for p in $EXISTINGVAR; echo "$p"; end` does not print anything.
Interestingly, for `$PWD` this prints an empty line.

**Comment by ridiculousfish** [comment]
I can't reproduce on OS X with ToT fish. What is your OS and fish version?

**Comment by Profpatsch** [comment]
Nixos, 2.2.0

**Comment by Profpatsch** [comment]
Oh, should have looked at the generated result. :)
It seems the generated code gets crippled.

**Comment by ridiculousfish** [comment]
Huh? What happened?

**Comment by Profpatsch** [comment]
I forgot to escape `$` and they got eaten by bash.

**Comment by ridiculousfish** [comment]
Ah-ha!
