### ISSUE TITLE
Occasional segfaults deep in glibc when execing?

### ISSUE THREAD

**Issue by amluto** [fish-shell/fish-shell#2392]
I'm seeing various abrt reports that generally look like [Fedora bug 1263052] (https://bugzilla.redhat.com/show_bug.cgi?id=1263052), which is the first one I've gotten since updating Fedora's package to fish 2.2.0.

My current best guess is that the iothread_drain_all hack isn't working right.

**Comment by amluto** [comment]
More info.  We're blowing up here in exec_job here:

                                bool builtin_io_done = do_builtin_io(outbuff.data(), outbuff.size(), errbuff.data(), errbuff.size());
                                if (! builtin_io_done)
                                {
                                    show_stackframe();
                                }

Something terrible is happening that causes show_stackframe() to segfault, in fprintf, but something must have already gone wrong before that.  As a wild guess, if write_loop fails due to EPIPE, bad things will happen.

Also, shouldn't show_stackframe use write_loop instead of fwprintf?

**Comment by amluto** [comment]
I bet I'm right.  The [open file descriptors] (https://bugzilla.redhat.com/attachment.cgi?id=1073481) were:

    0:/dev/pts/5 (deleted)
    pos:	0
    flags:	0100002
    mnt_id:	22
    
    1:/dev/pts/5 (deleted)
    pos:	0
    flags:	0100002
    mnt_id:	22
    
    2:/dev/pts/5 (deleted)
    pos:	0
    flags:	0100002
    mnt_id:	22

(and some more, stripped for brevity)

**Comment by ridiculousfish** [comment]
What is suspicious about those open file descriptors? That looks OK to me, except for `(deleted)` which I don't understand (what do those mean?)

**Comment by amluto** [comment]
I assume it means that the pty master (terminal) is gone.

**Comment by amluto** [comment]
See #2393 for a possible fix

**Comment by amluto** [comment]
I'm submitting Fedora updates-testing builds with these patch, and I'll ask the original reporter to test.

**Comment by ridiculousfish** [comment]
Assigning to me to remind myself to review this

**Comment by amluto** [comment]
FWIW, this is now in Fedora's updates-testing, so it should get some test coverage over the next few days.

**Comment by faho** [comment]
Fixed by merging #2393.
