### ISSUE TITLE
Using piped command with LESSOPEN produces artifacts

### ISSUE THREAD

**Issue by xguerin** [fish-shell/fish-shell#2396]
If LESSOPEN is defined as a pipe command, $PWD is echoed before the output of the piped command. 

```bash
$ mkdir -p some/dummy/dir
$ cd some/dummy/dir
$ echo "hello world" > data
$ set -gx LESSOPEN "| cat %s"
$ less data

~/some/dummy/directoryhello world
data (END)
```

I have not been able to reproduce this behavior with any other shell.

**Comment by faho** [comment]
Which fish version are you using? I can't reproduce with 7fe8a63 (and there shouldn't be any change after that).

What do you have in your ~/.config/fish/config.fish? Any custom functions (in particular wrappers for "cat", including aliases)? Fish _always_ opens all config files and leaves it up to the user to guard it with `if status --is-interactive`.

Does this also occur with `set -gx LESSOPEN "echo %s"?

**Comment by xguerin** [comment]
I'm using 08911e2. No custom function in my config.fish. I'm getting another type of error with echo:

```bash
$ less README.md
fish: Unknown command '-'
fish: -
      ^
EADME.md: No such file or directory
```

I'll recompile to a more recent version and try again. Mine is a bit old.

**Comment by faho** [comment]
Oh, and what's your OS?

**Comment by xguerin** [comment]
MacOS X 10.10.5. I installed fish through home-brew. Reinstalling HEAD does not help.

**Comment by xguerin** [comment]
Looking into it further, It seems to be coming from my terminal title escape sequence. It looks like the last character is chewed up. Investigating...

**Comment by faho** [comment]
>fish: Unknown command '-'
fish: -

Humm... `type echo`?

> EADME.md: No such file or directory

Is this a typo or does it really print that?

>MacOS X 10.10.5

Are you using iTerm2? AFAIK we have some integration with that which might be acting up.

**Comment by xguerin** [comment]
$ type echo
echo is a builtin
$ type less
less is /usr/bin/less

It's not a typo. The problem comes from my tmux escape sequence:

function set_tmux_title --description "Update TMUX title"
  printf "\033k%s\033\\" $argv[1]
end

fish does not seem to like the last escape character "\\" and eats up the subsequent incoming character... If I don't call that function, LESSOPEN works.

**Comment by faho** [comment]
How do you call that function and does it improve if you exchange double for single quotes?

**Comment by xguerin** [comment]
The function is called in a post-exec hook. Using single quote does not change anything.

**Comment by faho** [comment]
Could you post the post-exec hook (or your entire configuration)?

**Comment by xguerin** [comment]
Better yet, here is the minimum config.fish that reproduces it:

```fish
set -gx LESSOPEN "| cat %s"
set -gx LESS " -R"
set_tmux_title $PWD
```

**Comment by faho** [comment]
Okay, yeah, with that I can reproduce the issue.

And it seems to be that less doesn't directly call the LESSOPEN tool but rather calls fish (or rather your users default shell or something), which then calls "set_tmux_title" because it's not guarded by `if status --is-interactive`. This works:

```fish
set -gx LESSOPEN "| cat %s"
set -gx LESS " -R"
if status --is-interactive
  set_tmux_title $PWD
end
```

I'm inclined to say that this works as expected - as I said above, we always read all config files and leave it up to the user to decide when which part is supposed to be read.

**Comment by faho** [comment]
Yep, it calls the default shell - my root user has bash, so when I try to reproduce this as root I don't get it.

**Comment by xguerin** [comment]
That does make sense. Thanks a bunch for the help.
