### ISSUE TITLE
Keybindings busted

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#24]
Axel reports:

"On my machine, most key bindings seem to be broken. ^K does not kill, ^W
does remove text, but it seems not to be added to the actual kill ring. No
searching with up-arrow and down-arrow. Left arrow and right arrow do not
move around in the CD history when used on an empty command line. The bind
builtin implies that the bindings are still there, and the code to handle
these these commands seem to still be there in input*.cpp, so I guess
something is broken? (built from a tarball on Ubuntu 12.04)"

**Comment by faho** [comment]
This is very likely to be outdated.

**Comment by ridiculousfish** [comment]
Yeah, ancient history. Let's close. Thanks.
