### ISSUE TITLE
Fish doesn't colour over SSH

### ISSUE THREAD

**Issue by Fedjmike** [fish-shell/fish-shell#2404]
I'm running fish on a Solaris VM using [CSWfish](https://www.opencsw.org/package/fish/).

In the VM itself, fish colours things just fine. However when I SSH into it, fish doesn't think the terminal can support colours. `set_color` only sets the brightness.

    $ echo $TERM
    xterm

Colours *do* work fine over SSH, if I printf the right control characters they display fine. Other utilities like `ls` also colour their output.

**Comment by faho** [comment]
So, the version on csw is 2.1.0,REV=2013.11.14. That's two years old, there've been a ton of changes in the meantime. Can you try with a newer version?

>$ echo $TERM
xterm

How about when you `set TERM xterm-256color`? What does `tput colors` say (with xterm and xterm-256color)?

**Comment by Fedjmike** [comment]
$ tput colors
    8

The VM isn't running X. When I `set TERM xterm-256color`:

    $ set TERM xterm-256colors
    $ fish
    fish: Could not set up terminal

However when I set it to `ansi` colours work! I'm not sure what's gone on there. I don't know if this information is useful because of the version I'm running. I might get some time to try building a newer version later.

**Comment by zanchey** [comment]
Strange; 8 colours should at least give you _some_ colour. What terminal are you running the SSH client from? I'll try and get my Solaris VM running again because I'm pretty sure colours worked OK for me from there.

**Comment by zanchey** [comment]
I finally managed to get Solaris running. The `xterm` definition doesn't contain colours for me; `tput colors` returns `-1`.

**Comment by floam** [comment]
Not sure what we can do here if a termcap has that problem.

**Comment by floam** [comment]
Does this happen on 2.3.1?

**Comment by Fedjmike** [comment]
Sorry, I don't have access to the system where this was occurring anymore!

**Comment by floam** [comment]
OK, I'm closing it for now. Thanks for the help!
