### ISSUE TITLE
Cannot delete word on Mac

### ISSUE THREAD

**Issue by JoyceBabu** [fish-shell/fish-shell#2407]
I cannot delete previous word using <kbd>Alt</kbd> + <kbd>Backspace</kbd> on Mac. How can check my existing key bindings?

PS: <kbd>Ctrl</kbd> + <kbd>w</kbd> works though.

**Comment by faho** [comment]
Does it work in e.g. bash? This might be one of those keychords that are impossible in a terminal (like Ctrl-J, which does the same thing as escape, though for that vim somehow manages to make it work - we currently don't know how).

**Comment by JoyceBabu** [comment]
It was not working in bash too. In terminal profile settings, I enabled the option 'Use option as Meta key', and now it is working on both Fish and Bash.
