### ISSUE TITLE
Alt-left/right bindings for directory history navigation don't work in vi mode

### ISSUE THREAD

**Issue by netimen** [fish-shell/fish-shell#2412]
I'm running **fish 2.2** on Ubuntu. I start vi mode in my **config.fish** like this:

```
fish_vi_mode
function my_vi_bindings # https://github.com/fish-shell/fish-shell/issues/2254
    fish_vi_key_bindings
end
set -g fish_key_bindings my_vi_bindings
```

And now directory history navigation doesn't work when I press **Alt-left/right**.

**Comment by netimen** [comment]
I found a solution for this issue: I just add the bindings manually into my **config.fish**:

```
fish_vi_mode
function my_vi_bindings
    fish_vi_key_bindings

    bind \e\eOD prevd-or-backward-word
    bind \e\e\[D prevd-or-backward-word
    bind \eO3D prevd-or-backward-word
    bind \e\[3D prevd-or-backward-word
    bind \e\[1\;3D prevd-or-backward-word
    bind \e\eOC nextd-or-forward-word
    bind \e\e\[C nextd-or-forward-word
    bind \eO3C nextd-or-forward-word
    bind \e\[3C nextd-or-forward-word
    bind \e\[1\;3C nextd-or-forward-word
end
set -g fish_key_bindings my_vi_bindings
```

**Comment by faho** [comment]
What other keybindings should be included? Should vi-bindings include _all_ default bindings unless they do something different on the same binding? I mean we already have

```fish
  bind -M insert \ch backward-delete-char
  bind -M insert \cw backward-kill-word
  bind -M insert \cu backward-kill-line
  bind -M insert \cp history-search-backward
  bind -M insert \cn history-search-forward
  bind -M insert \cb backward-word
  bind -M insert \cf forward-word
```

so maybe all default bindings should be bound in insert mode?

**Comment by olbrew** [comment]
I just hit the same problem. Yes @faho adding all default bindings seems the best solution to me. I recently switched to fish-shell because of the newly available vi-mode and am loving it! But it can get confusing sometimes when I read something in the documentation which then doesn't work in vi-mode.

**Comment by faho** [comment]
So, everyone more versed in shell vi-modes than I, please test b743cce!

>But it can get confusing sometimes when I read something in the documentation which then doesn't work in vi-mode.

@olbrew: Our documentation has a section for vi-mode and a section for emacs-mode. If there's anything in the vi-mode documentation (or if the separation isn't clear enough) please mention that and we can fix it.

**Comment by olbrew** [comment]
@faho I just had the time to test it out and it seems to work. Although there is some weird behaviour. For example if I try to `dW` (delete word in vi), fish gives the error that 'kill-bigword' isn't known.

As for the documentation, there was a page describing some examples like the `dW` which wouldn't work with me, but I can't find the page back now. It is also unclear to me whether I have to put fish_vi_key_bindings in a fish_user_key_bindings or just fish_vi_mode in my config.fish?

**Comment by faho** [comment]
>if I try to dW (delete word in vi)

Hmmm.... I only know "dw" - what's the difference with "dW"?

>'kill-bigword' isn't known

It's possible this was added after your release - what fish version are you running?

>It is also unclear to me whether I have to put fish_vi_key_bindings in a fish_user_key_bindings or just fish_vi_mode in my config.fish?

In this case, you'd have to put the new fish_vi_key_bindings file somewhere in $fish_function_path before the $__fish_datadir ("/usr/share/fish/") part - usually in ~/.config/fish/functions, so that it overrides the file shipped with your fish installation. Or do you mean something different?

**Comment by olbrew** [comment]
> Hmmm.... I only know "dw" - what's the difference with "dW"?

dW deletes until the next space in vi(m) whereas dw only deletes until the next word. In a path with `/` as delimiter dw will only work until the next `/` while dW will delete the whole path.

> It's possible this was added after your release - what fish version are you running?

I'm running the latest release version, 2.2.0

> Or do you mean something different?

I've put your `fish_vi_key_bindings` in the fish/functions directory, but I also have a `fish_user_key_bindings` which contains: 

    function fish_user_key_bindings
        fish_vi_key_bindings
        bind -M insert -m default jj backward-char force-repaint
    end

while the official fish documentation says to: 
> To always start in vi mode, add fish_vi_mode to your config.fish file

I didn't know about the fish_vi_mode setting before though vi mode worked fine without it.
Thank you for your help!

**Comment by faho** [comment]
>dW deletes until the next space in vi(m) whereas dw only deletes until the next word. In a path with / as delimiter dw will only work until the next / while dW will delete the whole path.

So in other words it could reasonably be called "kill-bigword" ("kill" being "delete" in emacs-speak)? Neat - I should probably start using that, then.

>I'm running the latest release version, 2.2.0

So kill-bigword was probably added after that - it works on my bleeding edge build.

>I didn't know about the fish_vi_mode setting before though vi mode worked fine without it.

fish_vi_mode (see `type fish_vi_mode`) sets fish_vi_key_bindings and another variable to make the prompt aware of it.

**Comment by olbrew** [comment]
> So in other words it could reasonably be called "kill-bigword" ("kill" being "delete" in emacs-speak)?

Exactly. But to clarify it does work without error when I don't use your modified `fish_vi_key_bindings` but its behaviour equals the normal `dw`. With your file it gives the `kill-bigword isn't known` error.

> fish_vi_mode (see type fish_vi_mode) sets fish_vi_key_bindings and another variable to make the prompt aware of it.

Alright, I've added it to my config.fish. Now I'll have add support to my prompt for visually indicating in which vi-mode I'm currently in :). 

I'm already looking forward to the next release with the improved vim support!
Does this also mean that I then will be able to remove your `fish_vi_key_bindings` from my functions?

**Comment by faho** [comment]
>Does this also mean that I then will be able to remove your fish_vi_key_bindings from my functions?

Well, if this works out that'll be the default fish_vi_key_bindings function.
