### ISSUE TITLE
Tab completion very slow (30s), uninterruptable

### ISSUE THREAD

**Issue by ddrcoder** [fish-shell/fish-shell#2413]
I have some NFS directories in my `$PATH`. Recently, I my tab completions started taking a **long** time, like 30 seconds. The resolved commands take no time at all, though. Why would there be a massive disparity between completion and path lookup? Glancing at a stack trace taken during a completion, it seems to be doing some directory traversal...

**Comment by pickfire** [comment]
Which version of `fish` are you using?

**Comment by faho** [comment]
>Recently, I my tab completions started taking a long time, like 30 seconds. The resolved commands take no time at all, though.

I'm not quite sure I understand - do you mean `g<TAB>` is slow, while `git <TAB>` is fast? If so, that's to be expected. With the first one, we need to go through $PATH to get all possibilities, with the latte we check the git completion script.

 IIRC, bash et al cache the list of commands, which fish doesn't do, so that might explain any difference.

**Comment by pickfire** [comment]
Both is fast, but pasting **urls** is slow.

**Comment by faho** [comment]
@pickfire: That's a different issue (and IIRC there's one open about it already).

**Comment by faho** [comment]
@ddrcoder: Ping. What exactly is slow here? Which fish version are you using? Did older fish versions handle this better?

**Comment by ddrcoder** [comment]
I'm using a fresh cut as of 3ffbf9a7ea569b7ebb198bc7f9a04bde304d20a0. When I type in certain command prefixes and hit tab, it hangs. Most prefixes work fine, but for some reason prefixes fish just hangs. I've repro'd it under gdb, here's a stack trace;

```
#0  0x00007ffff6f59e25 in _xstat () from /lib64/libc.so.6
#1  0x00000000004847ca in stat (__statbuf=0x7fffffffba40, __path=<optimized out>) at /usr/include/sys/stat.h:457
#2  wstat (file_name=..., buf=0x7fffffffba40) at src/wutil.cpp:272
#3  0x0000000000482037 in wildcard_expander_t::expand_literal_intermediate_segment_with_fuzz (this=0x7fffffffc4a0, base_dir=..., base_dir_fp=0x7d1000, wc_segment=...,
    wc_remainder=0x7bbf24 L"conf") at src/wildcard.cpp:874
#4  0x00000000004819f9 in wildcard_expander_t::expand (this=0x7fffffffc4a0, base_dir=..., wc=<optimized out>) at src/wildcard.cpp:1012
#5  0x0000000000481931 in wildcard_expander_t::expand (this=0x7fffffffc4a0, base_dir=..., wc=<optimized out>) at src/wildcard.cpp:1004
#6  0x00000000004820da in wildcard_expander_t::expand_literal_intermediate_segment_with_fuzz (this=0x7fffffffc4a0, base_dir=..., base_dir_fp=0x7c8fc0, wc_segment=...,
    wc_remainder=0x7bbef4 L"scripts/bin/conf") at src/wildcard.cpp:887
#7  0x00000000004819f9 in wildcard_expander_t::expand (this=0x7fffffffc4a0, base_dir=..., wc=<optimized out>) at src/wildcard.cpp:1012
#8  0x0000000000481931 in wildcard_expander_t::expand (this=0x7fffffffc4a0, base_dir=..., wc=<optimized out>) at src/wildcard.cpp:1004
#9  0x0000000000481931 in wildcard_expander_t::expand (this=0x7fffffffc4a0, base_dir=..., wc=<optimized out>) at src/wildcard.cpp:1004
#10 0x0000000000481931 in wildcard_expander_t::expand (this=0x7fffffffc4a0, base_dir=..., wc=<optimized out>) at src/wildcard.cpp:1004
#11 0x00000000004820da in wildcard_expander_t::expand_literal_intermediate_segment_with_fuzz (this=0x7fffffffc4a0, base_dir=..., base_dir_fp=0x7c0f80, wc_segment=...,
    wc_remainder=0x7bbe9c L"FOO/scripts/bin/conf") at src/wildcard.cpp:887
#12 0x00000000004819f9 in wildcard_expander_t::expand (this=0x7fffffffc4a0, base_dir=..., wc=<optimized out>) at src/wildcard.cpp:1012
#13 0x0000000000481931 in wildcard_expander_t::expand (this=0x7fffffffc4a0, base_dir=..., wc=<optimized out>) at src/wildcard.cpp:1004
#14 0x0000000000481931 in wildcard_expander_t::expand (this=0x7fffffffc4a0, base_dir=..., wc=<optimized out>) at src/wildcard.cpp:1004
#15 0x0000000000481dea in wildcard_expand_string (wc=..., base_dir=..., flags=<optimized out>, output=<optimized out>) at src/wildcard.cpp:1071
#16 0x000000000045c02d in expand_string (input=..., output=0x7fffffffca90, flags=<optimized out>, errors=0x0) at src/expand.cpp:1822
#17 0x0000000000443f8a in completer_t::complete_cmd (this=0x7fffffffca80, str_cmd=..., use_function=true, use_builtin=true, use_command=<optimized out>,
    use_implicit_cd=<optimized out>) at src/complete.cpp:1150
#18 0x00000000004479c2 in complete (cmd_with_subcmds=..., comps=..., flags=6) at src/complete.cpp:1960
#19 0x000000000047a488 in reader_readline (nchars=<optimized out>) at src/reader.cpp:3373
```

Note that `FOO/scripts/bin/conf` doesn't exist, but `FOO/scripts/bin` does, and is in the path. Maybe we shouldn't keep doing fuzzy matching in this case?

**Comment by ddrcoder** [comment]
`FOO` was an NFS path, btw. Removing it stopped the bad behavior, but now I can't use those scripts without naming them or aliasing them in.

**Comment by ridiculousfish** [comment]
I need some way to simulate slow NFS mounts...

**Comment by ddrcoder** [comment]
I added a `printf` to `wstat`, then repro'd the issue. It ended up getting called more than a thousand times, and for directories that didn't look remotely comparable to the command. I don't want to share a dump of the file tree here, but one pattern which was particularly odd was this: For the path component `/mnt/vol/stuff/foo/scripts/bin`, it ended up recursing `stat`ing:

- `mnt/vol/stuff/foo/scripts/`
- `mnt/vol/stuff/foo/scripts/abc/`
- `mnt/vol/stuff/foo/scripts/def/`
- `mnt/vol/stuff/foo/scripts/ghi/`
- `mnt/vol/stuff/foo_admin2/scripts/`
- `mnt/vol/stuff/foo_admin2/scripts/abc/`
- `mnt/vol/stuff/foo_admin2/scripts/def/`
- `mnt/vol/stuff/foo_admin2/scripts/ghi/`
- `mnt/vol/stuff/foo_admin3/scripts/`
- `mnt/vol/stuff/foo_admin3/scripts/abc/`
- `mnt/vol/stuff/foo_admin3/scripts/def/`
- `mnt/vol/stuff/foo_admin3/scripts/ghi/`
- `mnt/vol/stuff-replica/foo/scripts/`
- `mnt/vol/stuff-replica/foo/scripts/abc/`
- `mnt/vol/stuff-replica/foo/scripts/def/`
- `mnt/vol/stuff-replica/foo/scripts/ghi/`
- `mnt/vol/stuff-replica/foo_admin2/scripts/`
- `mnt/vol/stuff-replica/foo_admin2/scripts/abc/`
- `mnt/vol/stuff-replica/foo_admin2/scripts/def/`
- `mnt/vol/stuff-replica/foo_admin2/scripts/ghi/`
- `mnt/vol/stuff-replica/foo_admin3/scripts/`
- `mnt/vol/stuff-replica/foo_admin3/scripts/abc/`
- `mnt/vol/stuff-replica/foo_admin3/scripts/def/`
- `mnt/vol/stuff-replica/foo_admin3/scripts/ghi/`

It looks like it's trying to fuzzy match the //path components of the serach path//, leading to an exponential explosion in directories scanned.

**Comment by ddrcoder** [comment]
Confirmed!

```
mkdir -p /tmp/search{,_{1,2,3}}/test{,_{1,2,3}}/bin
set PATH /tmp/search/test/bin
xyz<tab>
```

Shows that these directories are getting `stat()`d:

```
/tmp/search/test_2/
/tmp/search/test_3/
/tmp/search/test_1/
/tmp/search_3/
/tmp/search_3/test_2/
/tmp/search_3/test_3/
/tmp/search_3/test_1/
/tmp/search_2/
/tmp/search_2/test_2/
/tmp/search_2/test_3/
/tmp/search_2/test_1/
/tmp/search_1/
/tmp/search_1/test_2/
/tmp/search_1/test_3/
/tmp/search_1/test_1/
```

**Comment by zanchey** [comment]
> I need some way to simulate slow NFS mounts...

Install a Linux NFS server. Hiyoooo!

https://www.fsl.cs.sunysb.edu/docs/fsbench/slowfs.html might be useful.

**Comment by ridiculousfish** [comment]
@ddrcoder Nice repro steps! :+1:

**Comment by ridiculousfish** [comment]
aeaacedf75a99b06a93d8fe873ed7a795ed4f3dd should fix the unnecessary stat calls. Reopening to track "non-interruptible."

**Comment by ridiculousfish** [comment]
http://www.panix.com/~asl2/software/Pinefs/ worth investigating too.

**Comment by faho** [comment]
@ridiculousfish: The "non-interruptible" part is #23.

**Comment by ddrcoder** [comment]
Fix confirmed on my end, thanks @ridiculousfish!
