### ISSUE TITLE
'env FOO=bar utility' doesn't support functions

### ISSUE THREAD

**Issue by alco** [fish-shell/fish-shell#2415]
```
$ env FOO=bar help
env: help: No such file or directory
```

I don't remember encountering that in the docs and it's a real bummer because aliases are just functions, so I have to type out the whole command instead of being able to use an alias.

**Comment by pickfire** [comment]
In My Humble Opinion, you should use `abbr` or `alias` instead of using enviroment variables.

**Comment by faho** [comment]
This is a consequence of `env` not being in fish at all. `type env`:

> env is /usr/bin/env

And as such, it can't run fish functions because fish functions only exist inside fish.

We should probably document this (or find a better solution to the underlying issue), hence the label.

**Comment by GReagle** [comment]
To me, this does not seem like a bug in fish.  `env` expects a real command, so it doesn't work with bash aliases or functions either, for example.  If you want to temporarily set/change an environment variable for calling a fish function, I suggest the following:

`env FOO=BAR fish -c "help"`
 or 
`begin; set -lx FOO BAR; help; end`

**Comment by alco** [comment]
Thanks for explaining that.

Comparing it to Bash does not really apply here because there I would just write `FOO=BAR whatever`, and `whatever` would work regardless of whether it's an alias or a binary.

So that's a clunky part of Fish, in my opinion. But it's not `env`'s fault, so I'll close this.

**Comment by GReagle** [comment]
You're welcome alco.  The fish equivalent to `FOO=BAR whatever` is `begin; set -lx FOO BAR; whatever; end`.  It is definitely more verbose, but it does work with fish functions.

**Comment by faho** [comment]
Nope, documentation is still missing, so I'm reopening this.

**Comment by eush77** [comment]
>  The fish equivalent to `FOO=BAR whatever` is `begin; set -lx FOO BAR; whatever; end`

This doesn't work for me.

```fish
$ function baz; echo $foo; end
$ begin; set -lx foo bar; baz; end

```

The following does work (but it also leaks `$foo` into the shell env):

```fish
$ begin; set -x foo bar; baz; end
bar
$ echo $foo
bar
```

```fish
$ fish --version
fish, version 2.2.0
```

**Comment by GReagle** [comment]
Good catch @eush77 !  This is fascinating.  I have the same problem.  So `begin; set -lx FOO BAR; whatever; end` works fine when `whatever` is an external command but does not work when `whatever` is a fish function.  This seems like it might be a bug to me, but I don't have the fish expertise to be certain of that.  I wonder if there is a GitHub issue for it already.

If you do set -x without the -l local switch, there's no point in grouping with begin and end.  So the leak that you mention seems to be normal acceptable behavior to me.

**Comment by eush77** [comment]
@GReagle The point was not that it leaked, but that it worked without `-l`. I thought this is interesting and that it indicates the problem as being related to scopes.

**Comment by GReagle** [comment]
I see.  Thanks for the clarification.  Yes I agree with you.

**Comment by faho** [comment]
I actually can't see the difference between #438 and this, so I think we should track there. Closing this one.
