### ISSUE TITLE
nvim aliased to vim gives lots of error on tab completion.

### ISSUE THREAD

**Issue by onodera-punpun** [fish-shell/fish-shell#2416]
I aliased nvim (neovim) to vim using a simple function. Now when I tab complete in the shell I get the following:

```
/usr/share/nvim/runtime/tutor vim tufish: Unknown command 'vim'
- (line 1): begin; command vim --version 
                           ^
from sourcing file -
	called on line 60 of file /usr/share/fish/functions/eval.fish

in function 'eval'
	called on line 6 of file /usr/share/fish/functions/__fish_complete_/usr/share/nvim/runtime/tutor vim tufish: Unknown command 'vim'
- (line 1): begin; command vim --version 
                           ^
from sourcing file -
	called on line 60 of file /usr/share/fish/functions/eval.fish

in function 'eval'
	called on line 6 of file /usr/share/fish/functions/__fish_complete_vi.fish

in function '__fish_complete_vi'
	called on line 3 of file /usr/share/fish/completions/vim.fish
	with parameter list 'vim'

from sourcing file /usr/share/fish/completions/vim.fish
	called on standard input

in command substitution
	called on standard input

```

```
/usr/share/nvim/runtime/tutor vim tufish: Unknown command 'vim'
                                    ^ This is where I tab completed
```

**Comment by ridiculousfish** [comment]
Looks like the vim completions expect vim to be installed. As a workaround you might use a symlink instead of a function.

**Comment by faho** [comment]
>/usr/share/fish/functions/__fish_complete_/usr/share/nvim/runtime/tutor vim tufish

What's that? Doesn't look like our stuff.

In any case, __fish_complete_vi is bogus (dude), so I'll take a look at it. I must've missed it when I tried to remove all those weird completion-generating functions.

**Comment by onodera-punpun** [comment]
>What's that? Doesn't look like our stuff.

Two lines (my prompt `/usr/share/nvim/runtime/tutor` and the error) being mangled

**Comment by faho** [comment]
The change I just made eliminates that weird function and assumes that `{g,}vim{,diff}` always behave like vim, at least enough that our completions aren't wrong. It also handles `nvim` (if that differs from vim in commandline options, please say so and we'll add it) as a `vim`. The only thing it checks is if `vi` is really `vim`, since that occurs kinda often (AFAIK Debian does it by default). The check seems a bit simplistic (there are multiple `vi`s out there, maybe one of them has a "--version" switch), but it's the same the old function used.

**Comment by msteed** [comment]
Now typing `vim <TAB>` produces errors like the following:

```
  complete: Too many arguments
  /usr/share/fish/completions/vim.fish (line 8): complete vim -s c -r --description 'Execute  Ex command after the first file has been read'
                                                 ^
  from sourcing file /usr/share/fish/completions/vim.fish
          called on standard input

  in command substitution
          called on standard input
```

**Comment by faho** [comment]
Sorry, should be fixed now. It seems in my transformation a "-c" got
lost.

**Comment by msteed** [comment]
Thanks!
