### ISSUE TITLE
string builtin: Redirecting stdin doesn't work

### ISSUE THREAD

**Issue by Darkshadow2** [fish-shell/fish-shell#2422]
If stdin is redirected, the new string builtin complains it has too many arguments.

A simple test (write out to a file, make it executable):
```
string split ' ' "Hi Bye"
if $SHLVL -lt 3
    eval (source -f)
end
```

Running it, you get
```
Hi
Bye
Hi
Bye
```

But, if you run it with stdin redirected to anything (i.e. `./test </dev/null`), you get:
```
string split: Too many arguments
string split: Too many arguments
```

I say this is possibly only a bug on OS X because this test runs correctly on a Raspberry Pi I have (running Raspbian), but fails on my two OS X machines. One is running 10.10.5, the other is running 10.9.5.

I am not sure if it will fail the same way if stdin isn't a tty. Looking at the code, though, it appears it might. Anyone have an easy way to test that?

**Comment by ridiculousfish** [comment]
This ought to have been fixed as c1bd3b5824027f23b41bbac77c5e28f856c5dc18. Can you verify if you tested with that commit? Try updating to ToT.

**Comment by Darkshadow2** [comment]
Gah, you're right, it is fixed. I thought I had pulled that already.

Although, should this work: `fish -c 'string split -- "=" < fish.pc'` (run from inside the git dir)? It doesn't with ToT. I don't typically do anything like that, I only had that it my history because I was playing around with different ways of redirecting stdin.

**Comment by ridiculousfish** [comment]
It looks like `string` doesn't recognize --. I don't think any of our builtins do.

**Comment by Darkshadow2** [comment]
It's documented to accept -- as the end of options.

It seems `string` doesn't accept redirections at all with ToT. It did before. `string split "=" < fish.pc` doesn't print anything and returns a status of 1. I'm not sure if it was supposed to accept a redirection like that or not, though.

**Comment by faho** [comment]
The docs say it does:

>Arguments beginning with - are normally interpreted as switches; -- causes the following arguments not to be treated as switches even if they begin with -. Switches and required
       arguments are recognized only on the command line.

(I'd link to them, but it seems like the online docs on fishshell.com are for the current release?)

Btw: What does ToT stand for?

**Comment by faho** [comment]
>I'm not sure if it was supposed to accept a redirection like that or not, though.

Well, it accepts it via pipe - `cat fish.pc | string split "="`, so it should also via redirection. At least I've _never_ seen a tool behave otherwise.

**Comment by Darkshadow2** [comment]
ToT stands for 'Top of Tree', meaning the most current code in the repository.

**Comment by ridiculousfish** [comment]
My change special-cased `string` to check for whether it is receiving a pipe. I think we also need to check for whether it is receiving a direct redirection too.

**Comment by ridiculousfish** [comment]
Redirections should now be recognized properly with abeaac66328f83d8962d6a5a4b9ce8712edbbaa5 . Thanks for filing this!
