### ISSUE TITLE
The generated ls.fish does not work

### ISSUE THREAD

**Issue by Wonicon** [fish-shell/fish-shell#2425]
I find that the option `--group-directories-first` of `ls` cannot be auto-completed, so I use the `fish_update_completions` command but it has no effects on `ls`. It works after I use `source ls.fish` by hand.
I find there is a `ls.fish` file under `/usr/share/fish/completions`. After removing this file, the generated `ls.fish` works.
The `ls.fish` under `/usr/share/fish/completions` uses completion rules from `__fish_complete_ls.fish`, so is it better to get these default completion rule files updated?

**Comment by faho** [comment]
Any other options that are missing? Is this option a recent addition (i.e. should we guard this by ls-version)?

**Comment by Wonicon** [comment]
@faho The default completion of block size option is `--blocksize`, but my `ls` has the option `--block-size`. And I think that is all the difference, but I don't know whether other commands have the same problem.
The `ls` is from GNU coreutils 8.21, which is updated in January 2015 according to man page.
I think allowing user generated completions override the default ones may be an easy solution.

**Comment by faho** [comment]
> I think allowing user generated completions override the default ones may be an easy solution.

User-made completions override the default - put something into ~/.config/fish/completions called "ls.fish", and it will be used as the completion for "ls". What doesn't override is completions generated from man pages, and I believe that's the right solution as they are usually worse (sometimes _much_ worse) than our hand-rolled ones.

I'll fix our completions.

**Comment by faho** [comment]
Now you can try out overriding completions - download the ls.fish from that commit and put it into ~/.config/fish/completions.

Thanks for the report, I hope it's fixed now!
