### ISSUE TITLE
Retcon __fish_complete_* to mean "completes current commandline"

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#2440]
We have a number of __fish_complete_\* and __fish_print_\* functions. The current definition (that doesn't quite hold, see #747) from [the docs](http://fishshell.com/docs/current/index.html#completion) is

> Functions beginning with the string __fish_print_ print a newline separated list of strings. For example, __fish_print_filesystems prints a list of all known file systems. Functions beginning with __fish_complete_ print out a newline separated list of completions with descriptions. The description is separated from the completion by a tab character.

However, I don't see the use of that - the only thing that says is you need to cut it on a tab character if you're doing something other than completion, and you should check the output format of anything you use in a function anyway.

What I believe would be more helpful and more in line with naive expectations would be to take __fish_complete to mean "this acts on the current commandline and generates completion options for it".

There are of course other options:
- Invent a new convention for when a function has descriptions - this can also be used with the retcon ("__fish_complete_described_*")
- Make all functions that act on the commandline also have a mode where they don't, maybe via a standard option ("-c $INVENTEDCOMMANDLINE" or so)
- Do nothing - this is, as always, the easiest option

**Comment by zanchey** [comment]
The problem with always acting on the current command line is that it makes the output much harder to review, so adding a `-c INVENTEDCOMMANDLINE` would be helpful.

**Comment by faho** [comment]
Okay I don't believe this mass-renaming is really worth it, retracting.
