### ISSUE TITLE
Setting MANPATH breaks fish own man pages

### ISSUE THREAD

**Issue by bucaran** [fish-shell/fish-shell#2443]
`type man` to see fish custom `man` function:

```fish
# 
function man
	if not set -q MANPATH 
        # add fish own man path
	end
        # ...
end
```

If `MANPATH` is set we lose fish internal commands documentation via `man`. The workaround is to add fish man pages to `$MANPATH` ourselves, but that is not ideal.

EDIT: Related https://github.com/fish-shell/fish-shell/issues/2090

**Comment by zanchey** [comment]
Should be fixed in 57e22e87c2f76583fde01c9e5a89ff84fcde2ad7.
