### ISSUE TITLE
BUG: TAB will output some error messages if cd a dir whose name contains parentheses

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#2444]
For example, create a directory named "dir(name)" with 

    mkdir "dir(name)"

and cd into this directory:

    cd dir[TAB]

Some messages will be listed after the TAB

    in command substitution
            called on line -1 of file -

    from sourcing file -
            called on line 60 of file /usr/share/fish/functions/eval.fish

    in function “eval”
            called on line 45 of file /usr/share/fish/functions/__fish_complete_cd.fish

    in function “__fish_complete_cd”
            called on standard input

    in command substitution
            called on standard input

I know the directory name shouldn't contain symbols like parentheses, but the directory is from a downloaded archive file. I noticed this when trying to cd into it.

**Comment by ridiculousfish** [comment]
Dup of #562. Thanks for filing this!
