### ISSUE TITLE
Recursive glob expansion causes lag

### ISSUE THREAD

**Issue by Fedjmike** [fish-shell/fish-shell#2445]
$ fish -v
    fish, version 2.1.1
    $ /**

Merely typing that glob makes the shell freeze up.

**Comment by faho** [comment]
In ToT fish, maybe even 2.2.0 - which I _really_ recommend you upgrade to - this prints

>Illegal command name '/**'

But then that's not the issue. `echo /**`, I can attest to, still locks up the shell and, given a minute or so, your system. I narrowly got a root tty and killed fish (though the tty was still quite usable once I logged on - hurray for cgroups, I guess).

The issue isn't CPU - it's memory. When I killed that fish (and baked it with a bit of mustard sauce and a side of potatoes) it used about 3 gigs of memory (while my machine has 4).

**Comment by ridiculousfish** [comment]
Should we just have a limit on the number of items we will return?

**Comment by faho** [comment]
ARG_MAX? On my system that's 2097152. Though that would make it rather hard to work with more things.

**Comment by Fedjmike** [comment]
My main issue was that it appears to be evaluating this huge thing before it's even been fully typed, which stops you from typing it!

**Comment by faho** [comment]
@Fedjmike: Try 2.2.0 - it doesn't seem to be doing that (though I can't recall it ever doing that, I hardly use recursive globs).

**Comment by Fedjmike** [comment]
Indeed is fixed in 2.2.0.
