### ISSUE TITLE
Unexpected “Last login” message in El Capitan terminal

### ISSUE THREAD

**Issue by Aeron** [fish-shell/fish-shell#2454]
After update I started seeing messages like “Last login: Sat Oct  3 02:54:40 on ttys002” again. Have never seen these before on Fish.

How to reproduce the bug:

1. Run clean **Terminal.app**;
2. `cd somewhere` just to leave home directory, it was `cd /usr/local/Cellar/ ` in my case;
3. Open new tab. _Voila!_ Message is there.
4. [Bonus] Open new (third) tab. It opens in home directory somehow, instead of CWD. Maybe related to #2418, not sure.

It behaves the same with both “New tabs open with...” settings, ie `Same profile` + `Same working directory` and `Default profile` + `Same working directory`.

With Bash these messages can be turned off (completely on Mavericks and Yosemite) with existence of `~/.hushlogin`, but it is have no effect here.

If I restart terminal then tabs with home directory will be normal as expected, but tabs with other path will contain “Last login” message.

Fish’s greeting is turned off via `set -e fish_greeting` in config.

_Fish 2.2.0_ @ OS X El Capitan (10.11)

**Comment by ridiculousfish** [comment]
This is usually the `login` process. Try creating a file `~/.hushlogin`. Does that prevent it?

**Comment by ridiculousfish** [comment]
This is the `login` process outputting this, not fish. As you say, `~/.hushlogin` is supposed to squelch it.

**Comment by Aeron** [comment]
As I mention, `~/.hushlogin` have effect only for home directory. Same behavior was peculiar for pre-Mavericks, but for Mavericks and Yosemite effect was system-wide. So… looks like it’s El Capitan bug, right?

**Comment by ridiculousfish** [comment]
I was able to reproduce this. I'd guess it's a `login` bug. Maybe we can find a way to pass the `-q` flag to login? In any case, this happens before fish executes so it's definitely not a fish bug.

**Comment by Aeron** [comment]
Can be done via Terminal’s “_Preferences → Settings → [Profile] → Shell → Run command_”, but it feels deeply wrong :disappointed:

**Comment by ridiculousfish** [comment]
I was able to reproduce this under bash, so I'm going to close.

You might give iTerm2 a try. I was not able to reproduce it using its Duplicate Tab feature, which makes a new tab in the same directory.

Thanks for filing this. Always good to be aware of issues like this.

**Comment by rafaelrinaldi** [comment]
@ridiculousfish I'm experiencing this as well. Currently running the latest iTerm 2 version (Build 2.9.20160313). For the home directory it's fine but others will display that annoying message on top.

**Comment by ridiculousfish** [comment]
This message is from the `login` process, not fish.

**Comment by disrupted** [comment]
still, has anybody found out in the meantime how to effectively block this message for all folders?

**Comment by krader1961** [comment]
Change the login command to `/usr/bin/login -fpq krader` (replacing "krader" with your user name) in [profiles] -> [shell]. Unselect the "run inside shell" option.

**Comment by robb** [comment]
Alternatively, you can add this to your `config.fish`

```fish
function fish_greeting
    clear
end
```

**Comment by juliand665** [comment]
Adding onto what @robb said, in some terminals you can add `printf '\e[3J'` after clearing to clear the scrollback so the cleared text disappears entirely.

**Comment by nhooyr** [comment]
This login stuff can also cause big slowdowns in terminal.app, see https://apple.stackexchange.com/questions/41743/how-do-i-speed-up-new-terminal-tab-loading-time

I was never aware and just accepted that terminal.app takes 2 seconds to open a new terminal lol
