### ISSUE TITLE
Setting a value of list from command substitution seems not working

### ISSUE THREAD

**Issue by kimh** [fish-shell/fish-shell#2459]
I'm trying to create a list from the output of command substitution but it seems not handled as a list.

Fish version: 2.2.0
OS: OSX 10.10.4

```
$ set x (echo "1" "2" "3")
$ echo $x[-1]
1 2 3
```

I'm expecting `$x[-1]` will return 3 since $x is supposed to be a list. Am I missing anything?

**Comment by faho** [comment]
Currently, command substitutions are split on newlines if $IFS is set, and not split otherwise.

```fish
$ set x (printf "%s\n" "1" "2" "3")
$ echo $x[-1]
3
```

**Comment by faho** [comment]
See #2353.

**Comment by kimh** [comment]
Got it. Thanks!
