### ISSUE TITLE
auto completion doesn't work in some cases

### ISSUE THREAD

**Issue by songgao** [fish-shell/fish-shell#246]
The auto completion may not work for some cases. When:
+ `[` is included in the path
+ `[` is not the first character
+ `[` has been typed in by user
, the auto-completion can complete the rest of the path, but pressing Enter causes fish to complain about `'Unexpected end of string, parenthesis do not match'`.

Following steps can reproduce the issue:
1 Create a folder with `[` in its name

```
mkdir -p /tmp/issue_test/a\[a
cd /tmp/issue_test
```
2 Type in `cd a[`, and press [TAB]. It will be auto-completed into `cd a[a/`.
3 Hit Enter. The following error message will be displayed:

```
fish: Tokenizer error: 'Unexpected end of string, parenthesis do not match'
cd a[a/
   ^
fish: Tokenizer error: 'Unexpected end of string, parenthesis do not match'
cd a[a/
   ^
```

I was thinking in step 2, an expected auto-completion result could be `cd a\[a/`. I looked around the source code but could not figure out a way to fix it. Anybody has ideas?

**Comment by zanchey** [comment]
I'm going to dupe this into #562 as there's a bit more discussion there.
