### ISSUE TITLE
Understanding multiple redirection

### ISSUE THREAD

**Issue by kofalt** [fish-shell/fish-shell#2463]
Suppose I wanted to manipulate multiple output streams of a command, without changing or combining what output is sent to which stream. This is ideal for modularity, so that a convenience filter (or whatever) doesn't preclude other, later uses.

Creating an example `stuff` script that writes to stdout and stderr:

```bash
#!/bin/bash

echo "One"
echo "Two" 1>&2
```

I could fiddle with stdout via a pipe:

```fish
./stuff | sed 's/One/1/g'

# Stdout: 1
# Stderr: Two
```

To simultaneously fiddle with stderr, I wrap everything in a block and use `2>|`:

```fish
begin; ./stuff | sed 's/One/1/g'; end 2>| sed 's/Two/2/g' 1>&2

# Stdout: 1
# Stderr: 2
```

Success! Both streams were processed, without losing out/err information.

I think the closest analogue in Bash is the following:

```bash
./stuff 1> >(sed 's/One/1/g') 2> >(sed 's/Two/2/g' 1>&2)

# Stdout: 1
# Stderr: 2
```

This is bit more terse, but inferior to the fish example as the shell returns early.

---

I have two questions:

1. Is my fish example correct & reasonable?
2. Is there a better way to do multiple redirection in fish that I should be aware of?

Thanks! :sunglasses:

**Comment by kofalt** [comment]
Snippets updated for simpler reading.

**Comment by faho** [comment]
Well, there is some discussion related to this in #110, and #1786 which asks for an equivalent to your bash example.

An issue in your fish example is that it redirects stderr of _both_ stuff and sed, so if the latter prints anything, it'll be carried through the pipe.

Otherwise, yeah, that's basically it. We usually use "^" to refer to stderr redirections, i.e. "^|" would pipe stderr, but that's a cosmetic thing.

**Comment by pickfire** [comment]
I hope there is something short like `lfjao dkjo iojhfe &> log.txt` in fish, I think there isn't a think like this in fish if I am not mistaken, you can only `lfjao dkjo iojhfe > log.txt ^ log.txt`?

**Comment by faho** [comment]
@pickfire: Currently (IIRC), the best you can do is `somecommand 2>&1 > log.txt`.

If you'd like something else, please open a dedicated issue.

**Comment by kofalt** [comment]
Thanks! After playing with fish for a few hours, I'm very impressed.
This redirection problem was the main surprising aspect.

The limitation you mentioned (redirecting stuff *and* sed) is unfortunate, but acceptable for my use case.
If you feel that this ticket is fully encapsulated by the others you've linked, feel free to close.

**Comment by pickfire** [comment]
@faho, thanks that is a nice one for me to use `command 2>&1 > log.txt`.
