### ISSUE TITLE
double slash in cd

### ISSUE THREAD

**Issue by onodera-punpun** [fish-shell/fish-shell#2465]
since this commit: https://github.com/fish-shell/fish-shell/commit/0a99772572ab8632f103f05570da707683980d17 (I think) I'm getting double slashes at the end of cd completions.

Some examples: https://sr.ht/J0DS.png & https://sr.ht/YhIt.png

**Comment by TimWolla** [comment]
I can confirm the issue in fish, version 2.2.0-349-g0a99772.

**Comment by ridiculousfish** [comment]
Fixed as 434eabb7878178a095b8508ccbf5d232461e8d95. Thanks for reporting this.
