### ISSUE TITLE
env or env-alike builtin for running commands with one-off environments

### ISSUE THREAD

**Issue by Pysis868** [fish-shell/fish-shell#2467]
#### Background

I see that in issue #1288 you implemented commit c91f70523cbdf62292accf87b4465ad30ca8c159 "Rework error messages to be shorter and to handle more special bash-isms", which is great.
I have a question/suggestion concerning `ERROR_BAD_EQUALS_IN_COMMAND5` with its current value & place in `src/parse_constants.h` and `src/parse_execution.cpp`.
#### Suggestion

I was just thinking that since coming from `bash`, we're now setting variables using the `set` command, and doing away with the equals sign.  In this specific instance, why not have the same syntax as setting variables elsewhere?  `env` may function as `set` in this case, but then could it accept additional parameters by splitting the variable assignment apart and without using the equals sign?  Then it could recognize the following parameter(s) as the command(s) to execute, and if not, maybe it could follow something like the `command; and command;` syntax at that later point.
##### Example

bash: `<variable>=<value> <command(s)>;`
fish: `env <variable>=<value> <command(s)>;`
Suggested fish style 1: `env <variable> <value> <command(s)>;`
Suggested fish style 2: `env <variable> <value>; <command(s)>;`

Maybe this method specifically is an impossibility.  If so, is there could be another way to achieve it, or do you have a reason for not wanting to do it this other way?  I didn't see an existing issue for this topic being asked about before.

**Comment by faho** [comment]
One big issue with your proposal: `env` isn't _in_ fish - it's an actual command (/usr/bin/env), so this would entail making an `env` builtin or a wrapper function around it.

**Comment by Pysis868** [comment]
So that would be why fish doesn't have consistent syntax then; it just reuses an external command with its own syntax without having to write any extra code. 
Also, `env` allows multiple variables to be assigned: `env <variable>=<value> <variable>=<value> <command(s)>`.

I was merely proposing the consistency change to evaluate the work involved for matching the rest of the fish variable assignment syntax, as I was curious and hadn't seen this posted yet.  I'll leave the triage and work up project maintainers.

**Comment by krader1961** [comment]
This proposal is not backward compatible and we're never going to reinvent the `env` command as a builtin. At least not without supporting the existing semantics of that command which makes implementing this proposal impossible.
