### ISSUE TITLE
array slicing bug

### ISSUE THREAD

**Issue by mamiu** [fish-shell/fish-shell#2471]
When I try to slice the last element of an array with `echo (seq 5)[1..-1]` nothing will be sliced until I change the second slicing value to greater than 1 (e.g. to slice the last element I have to run `echo (seq 5)[1..-2]`).
Is this an expected behaviour?

**Comment by zanchey** [comment]
Array slices are inclusive (http://fishshell.com/docs/2.2/index.html#expand-index-range), and "-1" is the last element in the list - so I think so, yes.

**Comment by ridiculousfish** [comment]
Agreed, this is expected. `[1..-1]` means from the first to last value, inclusive.
