### ISSUE TITLE
Vi-mode: add binding for clearing terminal

### ISSUE THREAD

**Issue by rominf** [fish-shell/fish-shell#2472]
Clearing terminal is a very common operation. Please, add a default binding for this (Ctrl+L works only for Emacs mode).

**Comment by faho** [comment]
I'm testing a change where the vi-bindings would inherit the complete emacs bindings. Would that work for you? Or maybe just in normal-mode?

**Comment by pickfire** [comment]
@faho, do you mean you commit into the lastest HEAD by testing? I can't get `Ctrl+L` to work too.

**Comment by rominf** [comment]
@faho 
Yes, I think it would be nice!

**Comment by pickfire** [comment]
There seems to be some issue with this or previous commit which broke `^X` to auto-complete commands in insert mode.

**Comment by pickfire** [comment]
And it seems that it is overridden by **emacs-mode**'s `^F` for auto complete. Maybe the procedure is messed up.

**Comment by faho** [comment]
> broke ^X to auto-complete commands in insert mode.

@pickfire: That's "\cx" (ctrl+x), right? Why was that in vi-bindings but not emacs? It seems to do something completely different in vim and nothing at all in bash's vi-mode.

**Comment by pickfire** [comment]
And the commit that broke this is in between `54f2152..c0e8ad6` so I think this may be the commit and are those whitespaces in line 130..132 required? Adding the like that you deleted will do the trick:
```patch
-  bind -M insert \cx end-of-line
```
I think there are still some keys that are messed up other than `^f`.

Good luck and have a nice day!

**Comment by faho** [comment]
>I think there are still some keys that are messed up other than ^f.

What exactly is wrong with \cf? Before, it was bound to forward-word in insert mode and nothing otherwise, now it's just always bound to forward-word.

**Comment by pickfire** [comment]
> Why was that in vi-bindings but not emacs? It seems to do something completely different in vim and nothing at all in bash's vi-mode.

That's completion in vim, vi doesn't have it and the previous fish does it like that. @faho So it is wrong?

**Comment by pickfire** [comment]
> What exactly is wrong with \cf? Before, it was bound to forward-word in insert mode and nothing otherwise, now it's just always bound to forward-word.

I doesn't know what `^f` does in vim, it was to move a word forward in before this commit. Check http://sheet.shiar.nl/vi for what vi does in insert mode.

**Comment by faho** [comment]
>I doesn't know what ^f does in vim, it was to move a word forward in before this commit. 

and that's what it does now, so I don't see what you mean.

**Comment by faho** [comment]
Oh crap, it does forward-char now. Sorry.

**Comment by faho** [comment]
See 35bbc1d and the commit before that.

**Comment by pickfire** [comment]
In My Humble Opinion, I think that `^x` should be auto-completion instead of `^f`, what do you think? I don't think I can make the decision, this will affect the other users, let hear what they think. @rominf

**Comment by pickfire** [comment]
> See 35bbc1d and the commit before that.

What about `end-of-line`?

**Comment by faho** [comment]
@pickfire: Both keys you mentioned now do what they did before the change, in the modes they did it in (i.e. if they did nothing in a mode, they'll now do the emacs-thing instead)

>What about end-of-line?

That's what it was before - fish accepts suggestions if you move over them.

**Comment by pickfire** [comment]
Sorry, I didn't saw that.

**Comment by pickfire** [comment]
@faho, `^x` still doesn't work after commit `4e5e04bf`, I am still not sure what is the reason, but `^f` works now. I think I am going to be busy now.
