### ISSUE TITLE
`source` redirection and inability to detect whether stdout is a tty

### ISSUE THREAD

**Issue by mislav** [fish-shell/fish-shell#2477]
I'm using `[ -t 1 ]` to detect whether stdout is connected to a tty. This works as expected:

```fish
> fish --version
fish, version 2.2.0

> fish -c 'echo -n "tty: "; [ -t 1 ]; and echo yes; or echo no'
tty: yes

> fish -c 'echo -n "tty: "; [ -t 1 ]; and echo yes; or echo no' | cat
tty: no
```

However, when `[ -t 1 ]` appears within `source`d code, the tty status is always true, even if the result of `source` is redirected:

```fish
> echo 'echo -n "tty: "; [ -t 1 ]; and echo yes; or echo no' > test.fish

> source test.fish
tty: yes

> source test.fish | cat
tty: yes
```

The last line is unexpected. It should be "tty: no" because `source` is redirected to `cat`.

* * *

Generally it looks like `source` has problems with its output redirection. If I redirect to /dev/null, the output is indeed gone:

```fish
> source test.fish >/dev/null
(no output)
```

However if I redirect to a file, that file is empty.

```fish
> source test.fish >output.log
(no output)

> file output.log
output.log: empty
```

I expected the file to contain "tty: no".

**Comment by faho** [comment]
Unfortunately, test -t is currently broken. This has been reported in #1228.

Still thanks for filing this!

**Comment by faho** [comment]
Oh and, for the record, the workaround currently is to use `command test` (i.e. the actual `test` program at e.g. /bin/test).

**Comment by mislav** [comment]
Thanks! The workaround works.
