### ISSUE TITLE
How to insert a literal tab character?

### ISSUE THREAD

**Issue by rafaelrinaldi** [fish-shell/fish-shell#2478]
In bash <kbd>Ctrl+V</kbd> followed by <kbd>Tab</kbd> worked fine. Unfortunatelly this doesn't work on Fish.

**Comment by ridiculousfish** [comment]
For my own information, what's the use case for a literal tab?

**Comment by faho** [comment]
Usually, you'd insert a tab by inserting "\t" unquoted.

I.e. the following will append a literal tab to the "fish.log" file:

`echo -n \t >> fish.log`

What do you want a literal tab for?

**Comment by faho** [comment]
@ridiculousfish: You take the left, I'll take the right.

No, seriously, I've wished for a "insert the next sequence instead of interpreting it, in a format suitable for `bind`" function for a while now, mostly so we can easily check what codes a terminal sends. So far I've been going to bash for that (and feeling dirty, like I've been cheating).

**Comment by rafaelrinaldi** [comment]
On the Mac, `sed` don't recognize `\t`. So, the only way to represent a tab character is by using the sequence that I've mentioned (that will print the literal tab character).

**Comment by ridiculousfish** [comment]
sed is an external command, so you can pass a literal tab to sed by escaping it with \t (just not inside quotes).

**Comment by rafaelrinaldi** [comment]
I actually can't. It conflicts with Fish's autocomplete behavior.

**Comment by ridiculousfish** [comment]
Huh? I don't understand.

**Comment by faho** [comment]
Does this:

```fish
echo a\tb | sed "s/."\t"/b/"
```

work?

**Comment by rafaelrinaldi** [comment]
@faho Yup, it works, but it's quite different from what I'm trying to achieve.

```sh
$ echo foo\tbar | sed 's/\t/-/'
foo	bar
```
Expected result is `foo-bar`.

I would like to have the ability to use <kbd>Ctrl+V</kbd> and <kbd>Tab</kbd> to manually input the character (w/o relying on `/t`, which doesn't work). It works with `bash` though.

Thanks for the support, guys. Maybe I'm asking something that doesn't belong to Fish?

**Comment by faho** [comment]
$ echo foo\tbar | sed 's/\t/-/'

Umm... you need to open the quotes again in sed! This should be

    echo foo\tbar | sed 's/'\t'/-/'

**Comment by rafaelrinaldi** [comment]
@faho Yup, thanks. It's a workaround for `sed` and it works.

My question still remains with no real answer which is on how to input a literal tab character on the Fish shell.
Feel free to close the issue if you think it doesn't belong here.

**Comment by ridiculousfish** [comment]
Let's track in #1338. Thanks for filing this!
