### ISSUE TITLE
Add loop keyword

### ISSUE THREAD

**Issue by alexherbo2** [fish-shell/fish-shell#2482]
How about adding `loop` shortcut to `while true` loops?

**Comment by faho** [comment]
First of all: We welcome ideas here. Thank you for your idea. sincerely!

But I don't think it's a good one, so I'll have to say :-1:.

We have our [design](http://fishshell.com/docs/current/design.html) document that has a lot of big words, including the "Law Of Orthogonality". Now, while I'm the first to admit that philosophical purity for the sake of it is bad, I do believe the concern in this case is real.

This would take a keyword (i.e. every program called `loop` would always need to be invoked via `command`, and no function can ever have that name - which precludes overriding the command), so I'd set the bar pretty high. And this does a thing that's completely trivial to do. This trivial thing is also not something that occurs multiple times on a line, it probably only occurs once every thousand lines of fishscript or so (yes, that's a complete wild guess). It also adds more to the language, which means it's more to learn for those new to the ways of the fish. That trade-off just doesn't seem worth it.

So, I'm going to have to say sorry, but no.
