### ISSUE TITLE
Issue rendering completion when longer than terminal size

### ISSUE THREAD

**Issue by jpolitz** [fish-shell/fish-shell#2484]
On OSX 10.10.5, in both iTerm2 and in Terminal.  If I start to type a command that has a completion longer than the terminal window, I get quite odd behavior

After typing a single "s":

![screen shot 2015-10-12 at 9 50 14 pm](https://cloud.githubusercontent.com/assets/119891/10443648/40d4c772-712b-11e5-90f3-354e3ec2b234.png)

After typing a "c" from that state:

![screen shot 2015-10-12 at 9 50 46 pm](https://cloud.githubusercontent.com/assets/119891/10443652/52a6caae-712b-11e5-9398-edcd0034a99e.png)

After typing backspace once:

![screen shot 2015-10-12 at 9 51 22 pm](https://cloud.githubusercontent.com/assets/119891/10443663/69eb4906-712b-11e5-9b38-804603ecceff.png)

After typing backspace again:

![screen shot 2015-10-12 at 9 52 09 pm](https://cloud.githubusercontent.com/assets/119891/10443677/877cc382-712b-11e5-938f-6a4479039948.png)

In this state, typing backspace any more doesn't do anything, so it seems like the state of what's being shown doesn't match the currently-typed characters.

If I resize the terminal window so the whole completion fits, I don't run into any issues.

**Comment by pickfire** [comment]
Hi, what is your output of `fish --version`?

**Comment by jpolitz** [comment]
Oops, sorry: `fish, version 2.2.0`

**Comment by jpolitz** [comment]
Ah, and I tested for another important detail – this only happens when "Unicode East Asian Ambiguous Characters are Wide" is set in preferences.  Perhaps something about the width of the "…" character changes and that throws it off?

![screen shot 2015-10-13 at 3 17 56 pm](https://cloud.githubusercontent.com/assets/119891/10465594/9b65b4c0-71bd-11e5-9a16-3fbced374560.png)

**Comment by faho** [comment]
Compare #2224.

**Comment by faho** [comment]
And the (wonderfully titled) #1412.

**Comment by zanchey** [comment]
Could you try a build from the current master? `brew install --HEAD` will work if you're using Homebrew. I wonder if #2217 has improved this at all (though I doubt it).

**Comment by jpolitz** [comment]
I don't see a difference with `fish, version 2.2.0-369-g9788566`.  Happy to keep myself on HEAD and try changes if you ping me, though.

**Comment by ridiculousfish** [comment]
I think this is a dup of #1412 (thanks faho). Basically fish needs to know the current cursor position, which requires it to know the width of characters. But Terminal has a preference for how wide Unicode characters should be, and fish has no way of knowing what that setting is (AFAIK). So things can get out of sync.

**Comment by jpolitz** [comment]
FWIW, the reason this is relevant is that (in my experience) terminal Vim doesn't work right with wide Unicode characters without this setting on.  This is actually true for a lot of terminals with Vim; I was pleasantly surprised when I realized that iTerm2 and OSX terminal allowed this.  Even with all the combinations of `ambiwidth=double` etc. in .vimrc, in my experience it has needed help from the terminal to not have the Vim cursor jank around on wide characters.

**Comment by floam** [comment]
> But Terminal has a preference for how wide Unicode characters should be, 

Pretty much everything does given the broken system implementations. Fish could probably get a bit wiser. Fish's wcwidth is a few Unicode versions out of date, and OS X has changed recently. Try comparing it to https://github.com/jquast/wcwidth. Of course the source of thee bugs have nothing to do with the spec -

> and fish has no way of knowing what that setting is (AFAIK). So things can get out of sync.

One **can** loop through every character in the printable ranges and see how they affect the cursor position before and after, if you happen to be a program running inside a terminal emulator. This technique:

https://github.com/jquast/blessed/blob/master/bin/detect-multibyte.py

**Comment by floam** [comment]
It seems practical to try that on one ambiguous character in a way the user would not notice to suss out the behavior selected in the setting or determined by the locale. Use that to determine what math fish uses until the locale changes.

**Comment by jakwings** [comment]
For iTerm2, there is a relevant issue on GitLab: https://gitlab.com/gnachman/iterm2/issues/3615

My conclusion is: You'd better choose a font with all ambiguious-width characters with the same width of ASCII characters. Locale doesn't matter here. Regardless of ambiguious-width characters, there are bugs in wcwidth(), unless the terminal (emulator) and commandline apps both get the correct width, and have a way to know the actually width from the current font, it is impossible to solve the spacing problem perfectly.

**Comment by floam** [comment]
Attached are the character sizes in Terminal.app with_ Unicode East Asian Ambiguious characters are wide_ set to enabled:
[wcwidth-ambigwide.txt](https://github.com/fish-shell/fish-shell/files/170207/wcwidth-ambigwide.txt)

**Comment by floam** [comment]
And a diff: https://gist.github.com/floam/fa236f7ba2b356efa14f#file-ambiguous_narrow-vs-ambiguous_wide-diff

**Comment by floam** [comment]
Marking as fish-tanked bug. I certainly doin't think there is much we can do.

**Comment by pickfire** [comment]
@floam, are you really sure about writting your own emulator, haha fish emulator

**Comment by faho** [comment]
There's been a million changes to unicode handling, so I'm closing this.
