### ISSUE TITLE
Add support to use set_color to set a specific color by number from the 256color palette

### ISSUE THREAD

**Issue by etu** [fish-shell/fish-shell#2486]
Hello,

We all know these 256colors:
![2015-10-13-162052_642x212_scrot](https://cloud.githubusercontent.com/assets/461970/10457391/72e133ae-71c6-11e5-9d79-746676f41c3e.png)

It would be nice if it were possible to use `set_color` to select a color by number from this list.

To build my latest `fish_prompt` i had to do two helper functions to make the prompt-building easier:
```
# Function to set background color
function setBgColor
    builtin echo -e '\e[48;5;'$argv[1]'m'
end

# Function to set foreground color
function setFgColor
    builtin echo -e '\e[38;5;'$argv[1]'m'
end
```

It would probably have been slightly faster and nicer to use set_color directly. But I've selected colors from the 256colors list, so hex-codes and names doesn't really work that well for this.

My function to render the list of colors:
```
function 256colors
        for i in (seq 1 255)
                builtin echo -ne "\e[38;5;"$i"m"$i" "
        end
        builtin echo
end
```

**Comment by faho** [comment]
What would you like the syntax to be like?

**Comment by etu** [comment]
Was thinking, `-p` as in palette, or maybe `-n` as in number. But number is quite ambiguous. 

Maybe `-t` as in term-palette or term-color.

**Comment by pickfire** [comment]
What about support for terminal with true colors?

Is there something like `set_color #161616 'Hello'`?

**Comment by faho** [comment]
That's already in - see [the documentation](http://fishshell.com/docs/current/commands.html#set_color):

>If your terminal supports term256 (modern xterms and OS X Lion), you can specify an RGB value with three or six hex digits, such as A0FF33 or f2f. 

(though 24-bit color support is currently disabled IIRC, set_color already has the syntax for it)

**Comment by pickfire** [comment]
Sorry I didn't notice that, it is in the man page.

> ...  A0FF33 or f2f. fish will choose the closest supported color.

I think fish doesn't support [true colors](https://gist.github.com/XVilka/8346728) yet as it uses the nearest color.

**Comment by faho** [comment]
>I think fish doesn't support true colors yet as it uses the nearest color.

[Yeah it does](https://github.com/fish-shell/fish-shell/blob/master/src/output.cpp#L168-L181). Anyway, if you have any issues with that, please open a dedicated issue. This one's about using the terminal palette.

**Comment by pickfire** [comment]
I think you are correct then but the use of 24-bit color isn't documentated in the man page.

**Comment by faho** [comment]
And it's not supposed to be yet - though I'm not sure what we're waiting for - I'll ask @ridiculousfish.

Now please, if you have any more comments not on the topic of using the terminal color palette with set_color, please post them in another issue, possibly one you opened specifically to discuss that.

**Comment by ridiculousfish** [comment]
A new option tricky because of the interaction with `--background`. It might be simpler to have a variable like `$INDEXED_COLORS` or something.

My hope is that everyone switches to a Terminal with 32-bit color and we all use that :)

**Comment by ridiculousfish** [comment]
The reason 32 bit color support is not enabled by default is that there's no way to automatically determine if the terminal supports it. :(

**Comment by faho** [comment]
@ridiculousfish: See #2495 - for plenty of them it's possible.

**Comment by faho** [comment]
And it's 24-bit - I don't think there is a terminal with a dedicated alpha-channel.

**Comment by ridiculousfish** [comment]
Got me there.

**Comment by krader1961** [comment]
FWIW, This is what I wrote in issue #1464:

I'm ambivalent about adding support for referencing all palette entries by index using a scheme like colorN. I did implement it in my zsh color subsystem but found that I never use it so I'm not motivated to implement it. However, if someone else provides a change that implements it with minimal additional complexity I don't see any reason to object.

**Comment by jakwings** [comment]
How about this syntax:

```fish
set_color 16:NN  # from 16:1 to 16:16
set_color 256:NNN  # from 256:1 to 256:256
```

**Comment by krader1961** [comment]
That syntax seems needlessly complicated and confusing, @jakwings. Not to mention that there isn't any good reason to support the 16:NN variant since those are simply the first sixteen values in the 256:NNN variant.

I also would avoid introducing a new `set_color` option as suggested by @etu and @faho. The simplest, cleanest, solution is to extend the `named_colors` table to include an entry for each palette number, including aliases for the existing sixteen base colors. For example,

```
static const named_color_t named_colors[] =
{
    {L"black", 0, {0, 0, 0}},
    {L"color0", 0, {0, 0, 0}},
    {L"red", 1, {0xFF, 0, 0}},
    {L"color1", 1, {0xFF, 0, 0}},
    {L"green", 2, {0, 0xFF, 0}},
    {L"color2", 2, {0, 0xFF, 0}},
```

Obviously, the palette entries for 16 through 255 should be dynamically synthesized from the `kColors` table in function `term256_color_for_rgb` to ensure the RGB values are kept in sync.

**Comment by jrobeson** [comment]
the maxcdn folks solved color naming in a different way with shml https://maxcdn.github.io/shml/

**Comment by krader1961** [comment]
@jrobeson That solution is already present in fish; e.g., `echo (set_color yellow)yellow text(set_color normal)`. This issue is how best to extend that mechanism to the other 240 colors in the ANSI X3.64 (ISO 6429) color palette.

**Comment by derekstavis** [comment]
@jrobeson didn't know about shml. For fish there's [technicolor](https://github.com/oh-my-fish/plugin-technicolor) :100:

**Comment by krader1961** [comment]
I believe this issue should be closed. Each entry in the basic 16 color palette has a name (e.g., `red`, `brgreen`). More fine grained colors are available via explicit RGB values that are mapped to the closest matching value known to be supported by the terminal. There is very little value in supporting colors via names that index into the legacy 256 color palette. Having said that there might be value in supporting the symbolic names recognized by [HTML](http://www.w3schools.com/colors/colors_hex.asp). If anyone feels strongly about doing so please open a new issue to that effect.

**Comment by faho** [comment]
Let's close this.
