### ISSUE TITLE
sourcing Fish config keeps adding to PATH

### ISSUE THREAD

**Issue by fzakaria** [fish-shell/fish-shell#2487]
Every time I source my fish config (testing changes) I noticed that my PATH keeps expanding. This behavior is not what I would expect.

    fzakaria  ~  echo $PATH                                                      
    /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/opt/go/libexec/bin     /Users/fzakaria/Development/golang/bin /Users/fzakaria/scripts  /Users/fzakaria//tools/run

    fzakaria  ~  cat ~/.config/fish/config.fish                                 
    set -x GOPATH ~/Development/golang
    set -x GOROOT /usr/local/opt/go/libexec
    set PATH $PATH $GOROOT/bin $GOPATH/bin $HOME/scripts $HOME/tools/run

    fzakaria ~ source ~/.config/fish/config.fish

    fzakaria  ~  echo $PATH                                                      
    /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/opt/go/libexec/bin   /Users/fzakaria/Development/golang/bin /Users/fzakaria/scripts /Users/fzakaria/tools/run /usr/local/opt/go/libexec/bin /Users/fzakaria/Development/golang/bin /Users/fzakaria/scripts /Users/fzakaria/tools/run

**Comment by ridiculousfish** [comment]
heh:

`set PATH $PATH $GOROOT/bin $GOPATH/bin $HOME/scripts $HOME/tools/run`

That takes the existing `$PATH` and appends some stuff. Iterating that will make PATH longer and longer.

**Comment by fzakaria** [comment]
I understand that, but isn't that what the documents explain to do ?
I would've expected every source to 'refresh' all environment variables.

http://fishshell.com/docs/current/tutorial.html#tut_path

**Comment by ridiculousfish** [comment]
`source` is conceptually very simple: it executes the commands in a file, just as if you had typed them in by hand. It doesn't do anything else.

In general, config files only expect to be run once, at startup. There's nothing wrong with running them again, but the results can be unpredictable if the code doesn't expect it. That's shell scripting :)

Hope that clears things up!

**Comment by fzakaria** [comment]
I see. I was mimicking my bash/zsh workflow where if you change/editing
your source you simply reload it.

I guess there is no parallel.

Thanks!

**Comment by ridiculousfish** [comment]
Note that bash behaves the same way here. If you put `export PATH=$PATH:$HOME/tools/run` in your ~/.bashrc, then your $PATH will get longer every time you source that ,bashrc.
