### ISSUE TITLE
Alt↑ not working in vi mode

### ISSUE THREAD

**Issue by rstacruz** [fish-shell/fish-shell#2488]
From the docs:

> `Alt↑` recalls individual arguments, starting from the last argument in the last line executed.

However, on my terminal apps, (iTerm2 and OS X Terminal with fish in vi mode) this key combo doesn't seem to work. Is there a way to enable this in vi mode?

**Comment by faho** [comment]
You're reading the documentation for emacs mode (also I'm pretty sure you're reading an outdated version).

In any case, this was added in c0e8ad6f1feff09474e957773a1508d9813d4bbb.

**Comment by rstacruz** [comment]
thanks! I was reading v2.2.0's documentation.

**Comment by faho** [comment]
I don't think so - at least I can't find the passage you quoted on [the website](http://fishshell.com/docs/current/index.html) or the 2.2.0 I just installed.

**Comment by rstacruz** [comment]
I see it under this heading:

> Why doesn't history substitution ("!$" etc.) work?

**Comment by faho** [comment]
Ah, okay, sorry. Anyway, that's working now in git.
