### ISSUE TITLE
Load config.fish file when starting a new Terminal

### ISSUE THREAD

**Issue by mikebotazzo** [fish-shell/fish-shell#2491]
I am using OS X El Captain (10.11).
I created a file config.fish in ``` ~/.config/fish/config.fish``` to use new key bindings, 
exactly as specified in the [documentation](http://fishshell.com/docs/current/index.html#initialization).
Here is the content of my file:
```fish 
if status --is-login
 bind \x1b forward-word
 bind \x1d  backward-word
end
```
ps: I mapped the keys to unique ANSI key sequences based in the content of  #1806 ( the ```\c[``` didn't work to me )

Everything works fine if I type in the following in the current terminal:

```$ .  ~/.config/fish/config.fish```

However, I wish this were done automatically when I open a new terminal instance, it's annoying to type it all the time I load a new shell. How can I fix that?

**Comment by faho** [comment]
I think you're actually having a different problem - fish loads keybindings after config.fish, and the default key binding function erases all bindings.

This means you need to add all custom keybindings to a function called "fish_user_key_bindings" - see the [bind documentation](http://fishshell.com/docs/current/commands.html#bind).

To confirm it's always loading config.fish (and I'm quite sure of that, in fact it loads config.fish _always_, even for non-interactive shells), try putting a simple `echo` in there.

**Comment by mikebotazzo** [comment]
Thanks @faho , I haven't seen this line when I was reading. Now it works like a charm.
 I'll let my code with the modifications here for reference
```fish
function fish_user_key_bindings
    if status --is-login
     bind \x1b forward-word
     bind \x1d  backward-word
    end
end
```
