### ISSUE TITLE
$_ does not update when eval is used

### ISSUE THREAD

**Issue by bucaran** [fish-shell/fish-shell#2492]
```bash
function foo(){
  echo $FUNCNAME
}
function boo(){
  eval foo
}
boo
# foo
```

```fish
function foo
  echo $_
end
function boo
  eval foo
end
boo
# boo
```

To make things worse, there is no way to change the value of `$_` at runtime.

It would be awesome if `eval` was a builtin instead of a `share/functions` function.

**Comment by zanchey** [comment]
See the notes in #1743.

**Comment by faho** [comment]
>It would be awesome if eval was a builtin instead of a share/functions function.

It would be awesomer if we had something better than eval, something a bit more targeted - what exactly are you using it for now?

**Comment by bucaran** [comment]
Thanks.
