### ISSUE TITLE
Git completions for submodule not working

### ISSUE THREAD

**Issue by terlar** [fish-shell/fish-shell#2494]
https://github.com/fish-shell/fish-shell/blob/master/share/completions/git.fish#L512-L523

We refer to a function that is not defined, `__fish_git_seen_subcommand_from update`. I could easily fix it but I am not sure which function it should call or if we are missing a function.

It was introduce with this one, but the function was never defined:
https://github.com/fish-shell/fish-shell/commit/a828f90d38f615b60dc686598c1780904062b9ed

**Comment by pickfire** [comment]
I can confirm that `git submodule` produce an error when completing it.

**Comment by faho** [comment]
Sorry, that was meant to be `__fish_seen_subcommand_from`... Fixed now.
