### ISSUE TITLE
fish overwrites the previous line if it is missing a newline

### ISSUE THREAD

**Issue by Letheed** [fish-shell/fish-shell#2499]
When the last command did not print a final newline, fish overwrites the last line.
I think I remember that:
```
$ echo -n "foo"
$
```
should be:
```
$ echo -n "foo"
foo⏎
$
```

**Comment by ridiculousfish** [comment]
Indeed, this was 13479fbc2a130d97caeb66f7f56fb89c6be8c489. This is a serious regression so reverted as 036a29acf5d5184a4850475a1ae2f9512058744a. Thanks for filing this.
