### ISSUE TITLE
seems like pkg-config's `completionsdir` variable has not effect

### ISSUE THREAD

**Issue by xyb** [fish-shell/fish-shell#2500]
When I tried to fix homebrew's fish comletion issue in Homebrew/homebrew#45262, I found that pkg-config's `completionsdir` variable has not effect at all:

```
➜ completions git:(fishcomp) pkg-config --variable completionsdir fish
/usr/local/share/fish/vendor_completions.d
➜ completions git:(fishcomp) echo $fish_complete_path
/Users/xyb/.config/fish/completions /usr/local/Cellar/fish/2.2.0/etc/fish/completions /usr/local/Cellar/fish/2.2.0/share/fish/vendor_completions.d /usr/local/Cellar/fish/2.2.0/share/fish/completions /Users/xyb/.local/share/fish/generated_completions
```

Did I miss anything? Or it's a bug?

**Comment by zanchey** [comment]
Why does `pkg-config` think that the completions directory is in that location? Did you just edit the .pc file? That won't work - the way to approach it is to teach the configure process that the completions directory can be elsewhere, then work that into the build.

`fish` doesn't depend on `pkg-config` being available, so it doesn't derive the path from the .pc file.

**Comment by zanchey** [comment]
Some thoughts on this are in #2113.

**Comment by xyb** [comment]
What an idiot! @zanchey, Thank you!  But, why doesn't it work even I modified `fish.pc.in` before running `./configure`? And I have grep-ed sources, `completionsdir` be used in document only. How does the variable work?

**Comment by zanchey** [comment]
The vendor completions directory is currently set to `$__fish_datadir/vendor_completions.d`, with the contents of `$__fish_datadir` being set from [`determine_config_directory_paths()`](https://github.com/fish-shell/fish-shell/blob/b9b39f7c31d2514788f7b3bbacb966ad15578b5e/src/fish.cpp#L139).

**Comment by xyb** [comment]
@zanchey I know what's wrong. `determine_config_directory_paths()` is not related with `pkg-config`. The `completionsdir` variable neither compiled into binary nor included in `fish_complete_path`. So, the discoverable design based on `pkg-config` which described in [release 2.2.0](https://github.com/fish-shell/fish-shell/releases/tag/2.2.0) does not work at all. I will sent a PR to fix this.

**Comment by zanchey** [comment]
Well, it does work - you can control the directory at compile time, which is sort of the point. You just can't set the directory beyond changing the `datadir` prefix.

**Comment by faho** [comment]
>You just can't set the directory beyond changing the datadir prefix.

What I don't get here is why homebrew _needs_ anything else? Why can't completionsdir just be $datadir/completions when you set $datadir to /usr/local/share/fish?

@xyb: Why isn't that enough?

**Comment by zanchey** [comment]
See #2113 - Homebrew installs every package into its own private prefix, but some things need common prefixes.

**Comment by zanchey** [comment]
Closing - pkg-config's output is an effect, not a cause for fish's behaviour.
