### ISSUE TITLE
Async completion command

### ISSUE THREAD

**Issue by maxnordlund** [fish-shell/fish-shell#2501]
I'm not sure quite how auto completion works right now, or will after #478 happens. Independent of that it would be very nice if the command that generates the completions could be run asynchronous/non-blocking.

This would allow for very large completions to be used. I would love to be able to run `git show <TAB>` and get fuzzy matching (using the current pager/matcher) on all commitish+their description in the current repo.

I would like something simliar to `complete -c myprogram -a (expensive-or-long-output | psub)`.

**Comment by faho** [comment]
That's basically #23 and #238. I don't think the idea's been stated there directly, but I do believe that's the plan.

**Comment by maxnordlund** [comment]
That sounds amazing. I would love to help, but I don't know C++ unfortunately. You happen to know any good resources for learing?

**Comment by ridiculousfish** [comment]
What would the UI for this be? Is the idea that completions would come in over time, or would we show some progress indicator, or something else?

**Comment by faho** [comment]
@ridiculousfish: There is #2131.

As far as I see it, there's three possibilities:

- Completions just come in over time

- We just show a progress indicator

- We do both

I like the third one, though I'm not sure how workable it is.

**Comment by maxnordlund** [comment]
I like the third one as well, but instead of dots, like in #2131 why not use underline of the current line as a progress bar?

```
$ git show <TAB>
---
```
Except that the `-` would underline the `$ git show` row.

**Comment by maxnordlund** [comment]
or an ASCII propeller on the completion row

```
$ git show <TAB>
\ af34af (Some nice commet message)  afe54e (Other message)
```
Where the `\` would be spinning.

**Comment by Fuco1** [comment]
Not directly fish, but with `fzf` you can get a nice fuzzy interface like so

    git log --pretty=format:'%h %s' | fzf | cut -f 1 -d ' ' | xargs git show

They can handle huuuge lists (half a million+ items) and load the list async with new options being added on the fly.  It is very intuitive and works very well in practice that way.  So I would go with that if fish decides to add their own "fuzzy picker".

**Comment by maxnordlund** [comment]
I've been thinking a bit more about this and wonder if we can cheat a bit with completion instead of supporting true backgrounded functions.

What if we keep a fork of fish running in the background and have it execute the completion script?
Then just read the completions and populate the list as they come in, possible with an progress indicator of some sort.

The protocol for the two processes could just be JSON over stdin/stdout, or something like that.

**Comment by faho** [comment]
I'm closing this as a dup of #23 like I should have done originally.
