### ISSUE TITLE
`read` called from a file inserts an extra newline

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#2503]
As reported by onodera on IRC, with the file testfish:

``` fish
read somevar
echo $somevar
```

In fully interactive mode, this works as expected (or via source):

``` fish
$ . testfish
read> asdf
asdf
```

But when run as a file, an extra newline is inserted:

``` fish
$ fish testfish
read> asdf

asdf
```

**Comment by justuswilhelm** [comment]
I have the same issue with fish, version 2.2.0. Would be nice for it to have the same behavior as in interactive.

**Comment by pickfire** [comment]
@zanchey Oh, I didn't even notice that there is even an irc channel for fish. I hope that it is shown in fish.sh

**Comment by krader1961** [comment]
This problem no longer occurs so closing.
