### ISSUE TITLE
`jobs` has a different return code if used in a pipeline

### ISSUE THREAD

**Issue by Lucretiel** [fish-shell/fish-shell#2505]
While trying to write a simple `wait` command, I discovered that `jobs` behaves differently in a redirection or pipeline:

```fish
$ sleep 10 &
$ sleep 10 &
$ jobs
Job     Group   CPU     State   Command
2       ...     0%      running sleep 10 &
1       ...     0%      running sleep 10 &
$ jobs | cat
2       ...     0%      running sleep 10 &
1       ...     0%      running sleep 10 &
```

This makes perfect sense to me- many shell utilities have this behavior. However, jobs ALSO changes the return code if it is used in a pipeline:

```fish
$jobs; echo $status
jobs: There are no jobs
1
$ jobs > /dev/null; echo $status
0
```

This means that the following simple `wait` implementation doesn't work:

```fish
function wait
    while jobs > /dev/null
        sleep 0.1
    end
end
```

`jobs` should be changed to behave like `count`, `set -q`, etc. to return an error code if 0 jobs were found.

**Comment by maxnordlund** [comment]
I've encountered the same issue, but I'm not sure if it should return 0 when jobs are found. It makes more sense how it is now with it returning 0 if there are jobs to report on, e.g. `jobs --pid`.

**Comment by maxnordlund** [comment]
This should be resolved by the above commits, close this?

**Comment by ridiculousfish** [comment]
Thanks!
