### ISSUE TITLE
Text behind cursor unreadable

### ISSUE THREAD

**Issue by ohAitch** [fish-shell/fish-shell#2510]
I upgraded today from v2.1.0 to v2.2.0, and now the character behind my cursor stays the color it would have been if the cursor weren't there, as opposed to unilaterally black as previously. Optimally, things like bold and underline would hold over, but the color would still be something legible; as stands, I can just barely make out the first letter of any autocomplete.

2.1.0:
![screenshot 2015-10-29 15 18 58](https://cloud.githubusercontent.com/assets/1857414/10833601/82747b50-7e50-11e5-80a0-5eaa00f8f0b7.png)
![screenshot 2015-10-29 15 19 40](https://cloud.githubusercontent.com/assets/1857414/10833606/897edf4e-7e50-11e5-97c3-bd0a87c18c14.png)

2.2.0:
![screenshot 2015-10-29 15 19 50](https://cloud.githubusercontent.com/assets/1857414/10833610/94edc020-7e50-11e5-82ea-cb764ec74ba8.png)
![screenshot 2015-10-29 15 19 55](https://cloud.githubusercontent.com/assets/1857414/10833612/9acb17cc-7e50-11e5-8eb0-86de597c0f77.png)

**Comment by ridiculousfish** [comment]
Almost certainly #1821. Unfortunately there's no setting here that can make everyone happy.

What is your terminal app? I don't recognize that - is that classic iTerm?

**Comment by ohAitch** [comment]
Ah, indeed. I suppose I could locally revert the commit in question, though perhaps a configuration option?

Stock terminal, OS X 10.9.5 Mavericks :P

**Comment by ridiculousfish** [comment]
You could also tweak either the cursor color or autosuggestion color so that they're different. They blend together because they're the same.

Sadly I don't think there's anything that fish can do here. The old behavior was to not style the text under the cursor, which ended up looking extremely weird for those with vertical-bar style cursors.

I'm going to close. Thanks for filing this!

**Comment by pickfire** [comment]
@ohAitch The old behaviour would be weird if you use a bar cursor.

**Comment by ohAitch** [comment]
Yeah that's why the issue got closed. I ended up tweaking my autocomplete
to be slightly lighter, which is working well enough so far :3
