### ISSUE TITLE
echo $$ in bash and echo %self in fish are really the same?

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#2511]
Recently I was reading the book [The Linux Programming Interface](http://www.man7.org/tlpi/), and I did one practice at page 461 and another one at page 469, if you don't have the book, check the content from http://www.pdfiles.com/pdf/files/English/Operating_Systems/The_Linux_Programming_Interface.pdf, if you want to try it yourself, download the source code for the book and follow the steps in the book.

The weird thing is, the practice from page 461 for example, when I used `echo %self` to get the PID of the shell, and then `kill -40 the-PID-in-the-background`, the result of `si_pid` is not the same as the result of `echo %self`. 
But when I'm in bash, and use `echo $$` to get the PID of the shell, and then `kill -40 the-PID-in-the-background`, the result of `si_pid` is exactly the same as the result of `echo $$`.

So, how does the difference happen?

**Comment by faho** [comment]
>So, how does the difference happen?

Bash has a `kill` builtin, which means that the PID of `kill` is the PID of bash. Fish doesn't have one, so it executes /usr/bin/kill (or similar), which will then end up in the si_pid field.

**Comment by krader1961** [comment]
@c02y The explanation by @faho is correct. Also, you can verify that %self holds the PID of the shell by doing things like `ps -fp %self` or installing a signal handler and sending that signal:

```
$ function --on-signal USR1 my_usr1_handler
    echo whoa! received sigusr1
end
$ kill -usr1 %self
$ /bin/kill -usr1 %self
```

Do you have further questions? If not then please close this issue.

**Comment by c02y** [comment]
Thank you for the further explanation. You can close it now.
