### ISSUE TITLE
Slow response on unknown command

### ISSUE THREAD

**Issue by antoyo** [fish-shell/fish-shell#2513]
Hello.
When I write an unknown command in `fish`, for instance `l` (instead of `ls`), fish is slow to respond.
If I write the unknown command a second time, however, it will be faster.

I used `strace` to find out why it is slow.
The only thing that looked suspicious is that when it is slow, I have this line a lot of time:

```strace
select(8, [7], NULL, NULL, {0, 10000})  = 0 (Timeout)
```

If you need any other information, feel free to ask.

Thanks to fix this issue.

**Comment by faho** [comment]
Do you have any NFS mounts? If so, please see #2413 and, if possible, test the commit that fixed that.

**Comment by antoyo** [comment]
No, I do not have any NFS mounts.

**Comment by zanchey** [comment]
It would be worth trying to work out what's under file descriptor 8. If the hang is slow enough, you can check `ls -l /proc/PID_OF_HANGING_PROCESS/fd`.

Alternatively, you can look through the whole strace output (it's best done if you send it to a file, with something like `strace -o strace.output -tT -e trace=file`), and try and work out what is opening file descriptor 8 before the hang starts. Unfortunately, file descriptors can get reused which makes the process quite painstaking.

**Comment by ridiculousfish** [comment]
This 10000 usec timeout is only used in the call to `select_try()`, which is only invoked from `job_continue`, i.e. waiting for some job to complete. So we're waiting for some external command to complete.

@antoyo Can you try invoking fish as `fish -d 4` and then reproduce the hang? It should give us some clues as to which command is being slow.

**Comment by antoyo** [comment]
That was caused by the package search.
I disabled it with:

```fish
function __fish_default_command_not_found_handler --on-event fish_command_not_found
  functions --erase __fish_command_not_found_setup
  echo "fish: Unknown command '$argv'"
end
```

I tried this before, but for some reason `fish` did not load it correctly.

I never know when fish load config or environment variable. Is there a way to force the reload?

Thanks.

**Comment by ridiculousfish** [comment]
fish never automatically reloads config files. You can reload it manually via `source ~/.config/fish/config.fish`, but of course this will cause changes to double-up. The simplest thing to do is just start a new instance of fish.
