### ISSUE TITLE
'&&'  is error

### ISSUE THREAD

**Issue by olivetree123** [fish-shell/fish-shell#2520]
Expected end of the statement, but instead found a '&'
/usr/local/bin/virtualenvwrapper.sh (line 67): if [ "$OS" = "Windows_NT" ] && ([ "$MSYSTEM" = "MINGW32" ] || [ "$MSYSTEM" = "MINGW64" ])

the '&&' error，how should I do?

**Comment by ridiculousfish** [comment]
#150 is the request for && and || support.

You can use ['s boolean expression support:

    `if [ "$OS" = "Windows_NT" -a  "(" "$MSYSTEM" = "MINGW32" -o "$MSYSTEM" = "MINGW64" ")" ]` should do it.

However it's probably even easier to use `contains`:

    if begin; contains "$OS" Windows_NT ; and contains "$MSYSTEM" MINGW32 MINGW64; end...

**Comment by ridiculousfish** [comment]
Closing as a dup of #150; squawk if you disagree. Thanks for filing this!
