### ISSUE TITLE
Git Fetch completion does not complete remote branches

### ISSUE THREAD

**Issue by TensaiNiNaru** [fish-shell/fish-shell#2525]
```
$ fish -version
fish, version 2.2.0
```

I have added git.fish completions to my completion directory:
```
$ ls /home/max/.config/fish/completions/
composer.fish  git.fish
```

Now when I am in a directory with a git repo and type:
`git fetch origin <tab>`

I expect to get a list of remote branches from origin but what I get instead is this:
`git fetch origin origin`

Am I thinking wrong here expecting a list of remote branches ?

**Comment by faho** [comment]
>I have added git.fish completions to my completion directory:

Which? In general you don't need to add completions to your directory, unless you want to override the version shipped with your fish (e.g. with a newer version - though it's not guaranteed to work) or add new completions.

>Am I thinking wrong here expecting a list of remote branches ?

It's not wrong, just not implemented yet.

**Comment by TensaiNiNaru** [comment]
Thanks for answering so fast faho. I looked at the git.fish completion file in the Github repo and saw that you had done a lot of contributions. Do you know if someone is working on implementing this feature? I am kind of curious how the completion works so I will probably look into it myself.

Thanks for making fish shell more awesome. I love it :)

**Comment by faho** [comment]
> Do you know if someone is working on implementing this feature?

I don't know of anyone.

> I am kind of curious how the completion works so I will probably look into it myself.

Sounds great!

**Comment by leavengood** [comment]
This can be fixed by adding this:

```fish
complete -f -c git -n '__fish_git_using_command fetch' -a '(__fish_git_branches)' -d 'Branch'
```

To after this line:

https://github.com/fish-shell/fish-shell/blob/master/share/completions/git.fish#L179

I tested in my local fish. This was simple enough I did not bother with a PR. This also was just copied from the `pull` completions with the command name changed.

**Comment by faho** [comment]
@leavengood: I don't see how - you need a remote and _then_ a branch. Or as the git-fetch man page puts it, a "repository" and then a "refspec". That doesn't really gel well with fish's current completion setup but it's doable.

**Comment by leavengood** [comment]
The refspec is optional for both `git pull` and `git fetch`. My suggestion makes the fetch completions at least on par with pull. I need to learn a lot more about Fish completion to make anything more intelligent. Personally I think that is outside the scope of this particular issue.

**Comment by faho** [comment]
@leavengood: Yeah, we're already completing the remote. This is about what comes _after_. With your change,

`git fetch <TAB>` should offer both remotes and branches, but the branches aren't valid here! And then `git fetch origin <TAB>` would offer the same thing. I don't think that's an improvement.

**Comment by leavengood** [comment]
For the immediate term this makes the `fetch` completions more usable because at least you can see the branch options and choose a correct one, whereas now you get nothing. I agree something smarter would be better, but I think an incremental improvement would be nice before trying to make the better version.

https://en.wikipedia.org/wiki/Perfect_is_the_enemy_of_good

**Comment by leavengood** [comment]
I guess the solution for both fetch and pull (and maybe other things) is a function which determines whether a remote option has already been provided to choose which completions to show. It should be doable as you say. I'll look into it.
