### ISSUE TITLE
Shouldn't run scripts with #!/bin/sh as not POSIX compatible

### ISSUE THREAD

**Issue by sdroege** [fish-shell/fish-shell#2527]
fish should not run any scripts that use #!/bin/sh directly, e.g. when explicitly running such script from fish itself. As fish is not POSIX compatible, most of such scripts are going to fail in interesting ways.
It would be better to just use the real /bin/sh then

**Comment by zanchey** [comment]
Wait, are you running `fish somebashscript.bash`?

**Comment by sdroege** [comment]
Indeed that seemed to be the problem, sorry for the noise. (also it's not a bash script, just plain POSIX shell)
