### ISSUE TITLE
cd autosuggestion should descend "unique" hierarchies

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#2531]
If I intend to cd into a directory, and the directory has only one non-hidden child which is itself another directory, then it's a safe bet I want to descend into that child. And so on recursively. The cd autosuggestion should reflect that.

This is especially useful for e.g. Java source trees that have lots of empty directories.

**Comment by ridiculousfish** [comment]
We should relnote this

**Comment by faho** [comment]
@ridiculousfish: We now have a label for just that!

**Comment by ridiculousfish** [comment]
Why didn't I think of that!
