### ISSUE TITLE
Word separators are not consistently defined

### ISSUE THREAD

**Issue by JelteF** [fish-shell/fish-shell#2534]
If you have the line,
```fish
vim bla.txt
```
with the cursor at the end of the line. Pressing Alt+B (backward-word) moves the cursor to right behind the dot in `bla.txt`. Pressing Ctrl+W (backward-kill-word) however, removes the entire bla.txt argument. This is very inconsistent behaviour. Is there any reason why the separaters are different for the different commands?

**Comment by ridiculousfish** [comment]
Ctrl-W is backward-kill-path-component. Alt-Delete is backward-kill-word.

**Comment by JelteF** [comment]
Ah, I see now. In that case there are just two other issues. The first one is that `bind \cw` is called twice in the default key bindings: 
https://github.com/fish-shell/fish-shell/blob/10558644384ba53ff7a5402492824a53d76dc25d/share/functions/fish_default_key_bindings.fish#L79
https://github.com/fish-shell/fish-shell/blob/10558644384ba53ff7a5402492824a53d76dc25d/share/functions/fish_default_key_bindings.fish#L113

And the second is that the bind option is not documented:
http://fishshell.com/docs/current/commands.html#bind

As a last thing I have the request to have a backward/forward-path-component special input function as well.

**Comment by ridiculousfish** [comment]
Good finds!

**Comment by ridiculousfish** [comment]
The extra binding is removed in e50d1043996e5a232fe5cdea8bae50dc83b32a0c . Adding a tag to remind us to document the path-component bindings.

**Comment by andreaskern** [comment]
does that meanthat ctrl-w now behaves like 'GNU readline'?, namely killing until a whitspace
from the documentation of GNU readline

    backward-kill-word (M-DEL)
      Kill the word behind point. Word boundaries are the same as backward-word.

    unix-word-rubout (C-w)
      Kill the word behind point, using white space as a word boundary. The killed text is saved on the kill-ring.

**Comment by JelteF** [comment]
No, ctrl-w goes kills until a slash or whitespace.
