### ISSUE TITLE
autocomplete help wanted

### ISSUE THREAD

**Issue by jmwatte** [fish-shell/fish-shell#2535]
Hello,
2 questions: is it possible and example or  point me in the right direction.
I like to write an autocompletion for a program that  is structured like this.

Name of program: write
First level options: import -d'import stuff'
                                Edit -d'edit stuff'
As you can see these options don't have - or -- in front of them.
2 level options : import: -man -d' manually import'
                                       -auto -d'automatically import'
                          Edit: -left -d'left site'
Starting from the second level there are short and long options.
So is it possible that when i type at my fishprompt: 'write' I get the 1level options and help text and then when i start typing the 2level options i get heir options with help.
I can not find a way to add options without - or -- in the manual and how to go on from there.
Thx
Jmw

**Comment by faho** [comment]
Yes, it's quite possible, we have a ton of completions that work like that.

Off the top of my head [git](https://github.com/fish-shell/fish-shell/blob/master/share/completions/git.fish) and [systemctl](https://github.com/fish-shell/fish-shell/blob/master/share/completions/systemctl.fish) work like that - it's a bit trickier than options, but the gist is:

```fish
complete -c write -n "has_no_command" -a "import" -d "import stuff"
complete -c write -n "has_no_command" -a "edit" -d "edit stuff"
complete -c write -n "has_command import" -o man -d "manually import"
complete -c write -n "has_command import" -o auto -d "automatically import"
```

where has_command and has_no_command are functions that determine just that. For simple cases, you can use `__fish_seen_subcommand_from` (which takes a list of commands, so `not __fish_seen_subcommand_from import edit ...` would be your "has_no_command"). "-o" is "--old-option" - i.e. for options with one dash but multiple characters (unlike gnu-style short-options that can be grouped and such). See `complete --help`.

**Comment by jmwatte** [comment]
Thx a lot. Got it working now. Made my day.
