### ISSUE TITLE
Force short options over verbose options

### ISSUE THREAD

**Issue by lordlycastle** [fish-shell/fish-shell#2537]
Is there am option to force use of short options e.g. `-x` instead of `--extract`, when selecting them from completion, because a lot of the times the verbose options are wrong, and gives an error.

**Comment by faho** [comment]
Which long option are you talking about? If it gives an error, it should be fixed or removed from the completion.

**Comment by faho** [comment]
Are you by any chance on OSX or BSD? Those often don't have long-options, and we check for that in some completions (e.g. [ls](https://github.com/fish-shell/fish-shell/blob/master/share/completions/ls.fish) or [tr](https://github.com/fish-shell/fish-shell/blob/master/share/completions/tr.fish)). We are probably missing some.

If you tell me what they are, I can fix them.

**Comment by ridiculousfish** [comment]
Yes, what's an example of this?

**Comment by faho** [comment]
@lordlycastle: Ping?

**Comment by lordlycastle** [comment]
Sorry, for the late reply. I've noticed many times the more verbose auto completed options giving errors. I didn't know that they had to be removed, so didn't keep track of them. Most recent one, because of which I created this issue was `--lines/-n` option in `head` or `tail`. All the short ones from the auto-complete are correct but more verbose ones don't work i.e. `--bytes` doesn't `-c` does. Using long options give following error: `tail: illegal option -- -`.

I'm on OS X version, so perhaps that's the problem. Another generated option I've noticed is `-s` for `sudo`, it auto-completes to `-S` (capital) which gives an error.

**Comment by faho** [comment]
>I'm on OS X version, so perhaps that's the problem

I'm pretty sure it is.

Please report all other options that come to mind. This should be pretty easy to do by checking for status with a `--version` flag - can you confirm the affected tools error out in that case?

To be clear, the reason I don't like disabling it entirely or by-OS is because there's no telling if you e.g. have installed the GNU versions, and we try to stay away from the workaround kind of customization.

**Comment by faho** [comment]
>Another generated option I've noticed is -s for sudo, it auto-completes to -S (capital) which gives an error.

https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man8/sudo.8.html tells me it is supported in OSX 10.9.

**Comment by faho** [comment]
Please test 6336288 (put the files in $fish_complete_path, e.g. ~/.config/fish/completions) as I don't have an OSX machine. Generally the manpages are good enough to write completions from but you never know - for example is it true that `tail -q` works but `head -q` doesn't?

**Comment by lordlycastle** [comment]
@faho Working great, now I only see short options. 
> > Another generated option I've noticed is -s for sudo, it auto-completes to -S (capital) which gives an error.

> https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man8/sudo.8.html tells me it is supported in OSX 10.9.

This's very odd, I see the capital S in the man page too. According to the man page you're supposed to end the command with `\n` i.e. `sudo -S \n`. That works fine.

In the auto-complete the `-s` option is not available, and it's not the same as `-S`, so that probably needs to be added. Also noticed `which` command doesn't support long options, it also have other options that aren't mentioned in the man page, like `--skip-alias`, `--show-dot` etc. It only has `-a` and `-s`.

**Comment by faho** [comment]
See 917c727 for additions to sudo.

**Comment by faho** [comment]
See 3f12f75 for `which`.

**Comment by lordlycastle** [comment]
Thanks, seems good, now. I'll post if I find more.

**Comment by lordlycastle** [comment]
`rm`'s completions are incorrect too. None of the long options are supported. [Link to man page.](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/rm.1.html)

**Comment by faho** [comment]
@lordlycastle: a8a9ac0. Thanks!

**Comment by lordlycastle** [comment]
@faho Got one more. `mktemp` [man page](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/mktemp.1.html)
````fish
if mktemp --version >/dev/null ^/dev/null # GNU
	complete -c mktemp -s d -l directory	-d 'create a directory, not a file'
	complete -c mktemp -s u -l dry-run		-d 'do not create anything; merely print a name (unsafe)'
	complete -c mktemp -s q -l quiet		-d 'suppress diagnostics about file/dir-creation failure'
	complete -c mktemp -l suffix -r			-d 'append SUFF to TEMPLATE'
	complete -c mktemp -l tmpdir			-d 'interpret TEMPLATE relative to DIR'
	complete -c mktemp -l help				-d 'display this help and exit'
	complete -c mktemp -l version			-d 'output version information and exit'
else # OS X
	complete -c mktemp -s d 				-d 'create a directory, not a file'
	complete -c mktemp -s q					-d 'suppress diagnostics about file/dir-creation failure'
	complete -c mktemp -s t -r 				-d 'generate a template using PREFIX and TMPDIR (if set)'
	complete -c mktemp -s u					-d 'file will be unliked before mktemp exits (unsafe)'
end
````

**Comment by faho** [comment]
@lordlycastle: If you like, you can submit that as PR and get your name permanently engrained in fish history (fishstory?). Or of course I can just patch it in. Whichever you prefer.

**Comment by lordlycastle** [comment]
#2572 should fix this along others. 

I was wondering if there is a way to open the default manual page instead of fish'. For e.g. `open`'s manual page has almost nothing compared to OS X [default manual page](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/open.1.html). There also doesn't seem to be any completions for `open` is that because there aren't any possible options for GNU version?

**Comment by zanchey** [comment]
The fact that the `open` manual page gets installed on OS X is a bug (#2561).
