### ISSUE TITLE
(reverse-)i-search on command-line?

### ISSUE THREAD

**Issue by pluckytree** [fish-shell/fish-shell#2541]
In zsh/bash, I can use ctrl-r and ctrl-s for (reverse-)i-search on the command-line. I know that fish has its own history completion/searching mechanism which I love, but I really miss being able to search within a command that I am currently typing in the shell.

Am I missing a hidden feature?

**Comment by justuswilhelm** [comment]
You can try entering part of what you are looking for in the command-line and the do a history search by pressing the up and down keys. e.g.
```
$ www. <UP-KEY>
```
becomes
```
$ curl wwww.google.com
```

**Comment by pickfire** [comment]
There is currently no reverse search in `fish`, you can check https://github.com/fish-shell/fish-shell/issues/602 which track this issue. This issue is **DUPLICATED!**

Thanks for reporting. Good luck and have a nice day!

**Comment by faho** [comment]
The comments are correct - we don't currently have i-search as such, and that is tracked in #602. Thanks!
