### ISSUE TITLE
History file don't update on HEAD via homebrew

### ISSUE THREAD

**Issue by lukertty** [fish-shell/fish-shell#2550]
```bash
$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.8.5
BuildVersion:   12F2560
$ fish --version
fish, version 2.2.0-409-g5db8112
````

The file `~/.config/fish/fish_history` don't update after I upgrade 2.2.0 to HEAD.
But when I run `history` command, it shows history correctly.
And `count $history` shows the `$history` variable is updating... 

I want to search history in percol/peco by reading `~/.config/fish/fish_history` file.
So how to find the real history file ?

**Comment by ridiculousfish** [comment]
It's now in `~/.local/share/fish/fish_history`. See b13f0701a45f45568060d7dd7a5fed1052e9be60
