### ISSUE TITLE
Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.

### ISSUE THREAD

**Issue by Masshat** [fish-shell/fish-shell#2554]
bashrc (line 5): [[ $- != *i* ]] && return
                                   ^
from sourcing file .bashrc
	called on standard input

source: Error while reading file “.bashrc”

**Comment by faho** [comment]
This is pretty much working as expected - fish isn't POSIX-compatible (let alone bash), so reading configuration files or scripts written for other shells won't work.

**Comment by faho** [comment]
Though there is #150 talking about supporting &&, so this'd be a duplicate.
