### ISSUE TITLE
How should we complete for fg and bg?

### ISSUE THREAD

**Issue by danielmatz** [fish-shell/fish-shell#2555]
I was working on improving the completions for `fg` and `bg`, and I noticed a few issues.

1. I first wrote a function that printed out all of the job IDs, in the `%n` syntax, to use to complete the arguments for `fg` and `bg`.  But when I did that, the `%` would get completed as an escaped character, giving me something like `bg \%1`, and `fg` and `bg` wouldn't be able to accept it as an argument.
2. I went to the command line and typed `bg %<TAB>`, and I found that we actually have completion at that point, but it completes the PIDs of the jobs, and so you end up with something like `bg %10759`, which doesn't work as an argument for `bg` or `fg`.

The second issue should certainly be fixed.

Can the first issue be fixed?  If not, I would be willing to submit a pull request that completes `fg` and `bg` with PIDs, but without the `%`, which would end up giving something like `bg 10759`, which does work.

I'm willing to help fix any of these issues, really, but I'd need someone to point me in the right direction if I'd need to edit the source code.

**Comment by danielmatz** [comment]
Actually, I'd be willing to take a stab at the second issue, too, but someone would have to point me in the right direction in the source code...

**Comment by ridiculousfish** [comment]
Personally I always mess up the use of `fg` and `bg`. It's definitely silly that you can't use pid expansion with them and I'd love to have a fix. `builtin_fg` and `builtin_bg` in `builtin.cpp` are the places to start.

**Comment by danielmatz** [comment]
I think I found the code I need to change.  In `src/expand.cpp`, in the function `find_job`.  There is a special case for when the user has typed only `%`, and a comment saying it should expand to the last job backgrounded.  If I type `bg %<TAB>`, I would expect all of the jobs to be offered as options, but it only offers the last one backgrounded.  Easy enough to fix, but is this code also used if the user types `bg %<RETURN>`, which indeed runs `bg` on the last job backgrounded?  I'm worried about breaking something here...

**Comment by ridiculousfish** [comment]
I think your diagnosis is right! That empty job expansion logic in `find_job` should only fire if `EXPAND_FOR_COMPLETIONS` is not set in `info->flags`. That does look like a straightforward fix.

Don't worry about making a mistake, that's what code review is for :)

**Comment by danielmatz** [comment]
Just submitted a pull request that should hopefully address most of this.

The only thing I didn't look into is how to allow the completion engine to pass through an unescaped `%` character.  For now, completing `bg` and `fg` with job PIDs seems good enough.
