### ISSUE TITLE
`xsel: Can't open display: (null)` when pressing `^W`

### ISSUE THREAD

**Issue by devurandom** [fish-shell/fish-shell#2556]
When I `su -` to become root, and then `^W`, I always see this:
```
No protocol specified
xsel: Can't open display: (null)
: Resource temporarily unavailable
```

This is probably, because `su -` does not unset `$DISPLAY`, so Fish thinks it has proper access to an X-server. Together with the weird default behaviour of copying everything to the X-clipboard, this results in the observed behaviour.

As a temporary workaround, I ran `set -U FISH_CLIPBOARD_CMD cat` (as described in #772).

A better solution might be to first test whether `xsel` actually works, before enabling this behaviour. In addition to that, its stderr should be redirected to /dev/null, to prevent flooding the commandline with these errormessages. As a last step, copy-to-X-clipboard could be put to a key different from `^W` (#772).

**Comment by faho** [comment]
>As a last step, copy-to-X-clipboard could be put to a key different from ^W (#772).

There's no separate "copy-to-clipboard" function here - "\\cw" (in fish notation) is "backward-kill-path-component". All our functions that remove text (with, IIRC, the exception of things that only remove a character) copy it to clipboard.

>A better solution might be to first test whether xsel actually works

Running `xsel` with $DISPLAY set to something weird results in that text going to stderr and a return code of 1. So we could do a special case in __fish_config_interactive and override it with a global variable. I'd rather not actually start it, though - any way to find the socket corresponding to $DISPLAY and see if it's writeable or something?

**Comment by devurandom** [comment]
`$DISPLAY` is `:0`, which is perfectly valid. The reason for the call failing must lie in xauth or similar... But I'm not entirely sure about that, as I had a broken cookie in xauth for root before, and then xsel explicitly said that authentication failed. Now it just says `Resource temporarily unavailable` - without any hint about failed authentication.

Testing the socket for writability will probably not work, as we are talking about `root` here. Per definition he should have write access.

**Comment by pickfire** [comment]
@devurandom Hi, I think that you had mistaken something. In a nutshell, `^w` is the function of `kill-word` in other words, delete a word backward.

**Comment by devurandom** [comment]
@pickfire: @faho said it's `backward-kill-path-component`, not `kill-word`. However the name: It appears that Fish does not only kill the word or path-component, but also tries to store it in the X-clipboard, which for whatever reasons does not work anymore when I `su -`.  This would not be a problem (I don't use that feature anyway), but it also creates output to stderr, destroying the typed line and making it really difficult to further edit it.

**Comment by pickfire** [comment]
@devurandom I think so, maybe because I am using `fish_vi_mode`.

**Comment by faho** [comment]
This should be gone with the removal of our clipboard integration - #3061.

We now have bindings to explicitly copy to or paste from the clipboard, and these will throw errors in that case, but it should all be much more explicit - you tried to access the clipboard and it failed, so we inform you of that.
