### ISSUE TITLE
`make install` installs open(1) manpage on Darwin

### ISSUE THREAD

**Issue by mistydemeo** [fish-shell/fish-shell#2561]
fish doesn't define its `open` builtin on Darwin, due to the system utility by that name; however, it does still install the manpage for that builtin, which shadows the system utility's. It'd be great to avoid installing this on OS X, since it's confusing otherwise.

**Comment by ridiculousfish** [comment]
I thought we tried to avoid that...how are you installing fish?

**Comment by mistydemeo** [comment]
Via Homebrew, which essentially just runs `./configure --prefix=$PREFIX && make install`.

**Comment by ridiculousfish** [comment]
It looks like we prevent this at the point of building the man pages, when on Darwin. But when we give the tarball to Homebrew, we include prebuilt man pages, so that they can build without Doxygen; this tarball includes the open man page since it's intended to be cross platform. Probably we need to nix this man page at install time instead of build time, in the Makefile.

**Comment by zanchey** [comment]
Boo.

**Comment by krader1961** [comment]
There may be a related problem on Mac OS X (Darwin). Running `xcodebuild` results in `/tmp/fish.dst/usr/local/share/man/man1` containing just three files:

```
$ ls /tmp/fish.dst/usr/local/share/man/man1
fish.1  fish_indent.1  set_color.1
```

Running `build_tools/build_documentation.sh` creates a `./share/man/man1` directory that contains all of the fish man pages. Is that difference expected?

**Comment by ridiculousfish** [comment]
Yes, it's expected. Fish-specific man pages live in `usr/local/share/fish/man`

**Comment by floam** [comment]
The Linux `man open` would be more useful if it just showed the `xdg-open` manpage. The open script is a thin wrapper that doesn't any functionality. Why not just ship with a default abbr for `open` -> `xdg-open` iff. `xdg-open` is installed?

**Comment by krader1961** [comment]
I can't reproduce this problem. For me `make install` does not install the `open` man page on macOS. And looking at the build process it looks like that man page was blacklisted by commit 93dfb6f7 from 2013-02-16. Neither does it appear the *fish.app* bundle installs it.

Is this still a problem?

**Comment by zanchey** [comment]
It will still cause a problem if you install a release (eg using Homebrew) because the tarballs contain the prebuilt pages.

**Comment by krader1961** [comment]
Okay, I didn't test that and @floam's update of the issue summary is thus incorrect. Should we just blacklist that man page on every platform while still including it in the HTML docs?

**Comment by ridiculousfish** [comment]
On reflection it seems weird that fish would try to provide `open`. It's a pretty lame wrapper, and conflicts are certain. Does anyone object to removing fish's `open` function?

**Comment by ridiculousfish** [comment]
Well that was fast

**Comment by floam** [comment]
I messed up the PR and closed the branch. I'll redo it.

**Comment by zanchey** [comment]
I like it, I do use it, and I think nuking it in a minor release will take people by surprise.

**Comment by floam** [comment]
How about a default `abbr` for `open` to `xdg-open` where it exists?

**Comment by zanchey** [comment]
That's not much good if it's in scripts.

**Comment by floam** [comment]
An alias seems nicer here than an abbr.

**Comment by faho** [comment]
@floam: That's _exactly_ what we have now.

**Comment by floam** [comment]
You're right.
