### ISSUE TITLE
Command substitution problem

### ISSUE THREAD

**Issue by electricface** [fish-shell/fish-shell#2568]
in filsh-shell
```
gcc glibtest/rand_t1.c (pkg-config --cflags --libs glib-2.0)
glibtest/rand_t1.c:1:18: fatal error: glib.h: No such file or directory
 #include <glib.h>
                  ^
compilation terminated.
```

in bash
```
gcc glibtest/rand_t1.c `pkg-config --cflags --libs glib-2.0`
```
is ok

因为 fish 中 pkg-config 的输出结果被作为一个参数了，而 bash 中会把参数拆散。

**Comment by ridiculousfish** [comment]
pkg-config outputs space-separated text, which fish won't split. See [this SO answer](http://stackoverflow.com/a/28129450/1441328) which has a workaround at the bottom.

We don't want to change fish's behavior to split on all whitespace, so I'm going to close. Thanks for filing this!
