### ISSUE TITLE
Import Bash Settings

### ISSUE THREAD

**Issue by siteshwar** [fish-shell/fish-shell#257]
People coming from Bash would like to import their existing settings into Fish. So we need to write new scripts through which we can import Bash settings. Scripts should be preferably written in Python (since Fish already has many scripts written in Python), and they should be able to at least import aliases, variables and Bash prompt.

**Comment by pehrlich** [comment]
+1 via https://github.com/fish-shell/fish-shell/wiki/POSIX-compatibility-thoughts.  Perhaps I'm an outlier, but I would really like to `export` variables and type `&&` just like a normal person might..

**Comment by krader1961** [comment]
Sorry, but no. Adding support for `&&` and `||` has been debated to death and they're not going to be implemented. Things like `export` are trivial to implement as functions and that specific example is now part of the core fish package. Supporting bash completions might be feasible and is being discussed in issue #2856. But supporting zsh and other shells is highly unlikely to ever be implemented. Patches are, however, more than welcome. If someone is willing to make the effort to write the necessary code we'll be happy to review it and possibly include it in the core package.

**Comment by nafg** [comment]
I think one of the biggest problems is converting completions. Someone
should start a project that allows completions to be defined in some
declarative data format, and then (imperative) scripts for all of the major
shells generated from that.

**Comment by silviubogan** [comment]
[Here][1] it is said that a user can put this as the last line in its `.bashrc` file:
```
exec fish
```
to simulate fish being the default shell (this is what I use). Maybe this could be automated when running `fish` with a future newly implemented command line argument.

  [1]: https://wiki.archlinux.org/index.php/Fish#Modify_.bashrc_to_drop_into_fish

**Comment by aldanor** [comment]
That’s generally a pretty bad idea as it can interfere with running non-interactive scripts and spawning shells if not done very carefully (definitely not just `exec fish` at the end).

**Comment by skheria** [comment]
This worked for me: https://superuser.com/questions/446925/re-use-profile-for-fish

**Comment by ayekat** [comment]
@aldanor 

That shouldn't really be an issue. Given how awkwardly bash sources its files, it has become standard to include something like this at the top of any bashrc file:

    # If not running interactively, don't do anything
    [[ $- != *i* ]] && return

… thus essentially turning bashrc into an "interactive shell only" configuration. Putting `exec fish` at the end of it shouldn't cause any issues.
