### ISSUE TITLE
Autocomplete file names with prefix other than "--"

### ISSUE THREAD

**Issue by jonashaag** [fish-shell/fish-shell#2579]
`somecome --somearg=<TAB>` works well.

I'd like to see support for completion when typing
- `env FOO=<TAB>`
- `cc -I/usr/<TAB>`

Possibly other prefixes as well.

**Comment by faho** [comment]
The "=" (and ":") case is solved by 85dad6913e77d81730f3aea478695429f441ebd5.

The other case poses some problems, though - in particular related to option grouping, so I'm not sure we could turn it on unconditionally - doesn't `cc -I=/usr/` work?

**Comment by jonashaag** [comment]
> doesn't cc -I=/usr/ work?

Maybe for `cc`, but certainly not for all programs.

**Comment by krader1961** [comment]
I don't see us ever implementing file completion after arbitrary prefixes and the example, -I/usr/[tab] is easily handled by inserting a space between the flag and the path. While it is true that most option parsers don't allow using an equal sign to separate the flag and argument they do allow an optional space. The proposed enhancement is also ambiguous in the face of completions for the command which define those flags.

**Comment by jonashaag** [comment]
I agree -- it's terribly ambiguous. Maybe we could whitelist a few characters, `/` at least? Anyway, I think it's good enough now, you can always add a space.
