### ISSUE TITLE
Command grouping in Fish

### ISSUE THREAD

**Issue by oranja** [fish-shell/fish-shell#2581]
Hi all,
Here's something I never knew existed and never needed until recently: [Command Grouping] \(Bash\).
(Obviously, I don't do much shell scripting.)

In short, "When commands are grouped, redirections may be applied to the entire command list". It goes without saying that this is very different from piping or just running a list of commands consecutively.

**Potential use case # 1:**
```fish
{ cp libmysillylib.so /usr/lib/; ln -s /usr/lib/libmysillylib.so /usr/lib64/ } ^ errors.log
```
instead of
```fish
cp libmysillylib.so /usr/lib/ ^ errors.log; ln -s /usr/lib/libmysillylib.so /usr/lib64/ ^^ errors.log 
```

**Potential use case # 2:**
```fish
{ ls /usr/sbin; ls /sbin } | sort | uniq | column
```
instead of
```fish
begin
  set -l all_sbin (ls /usr/sbin) (ls /sbin)
  echo $all_sbin | tr [:space:] \n | sort | uniq | column
end
```
Another possible workaround could be to evaluate commands from a string:
```fish
eval 'ls /usr/sbin; ls /sbin' | sort | uniq | column
eval 'cp libmysillylib.so /usr/lib/; ln -s /usr/lib/libmysillylib.so /usr/lib64/' ^ errors.log
```
But I doubt that `eval` can be approved as a legitimate solution where command grouping is needed. I don't think there is any security concern with hard-coded commands but the escaping/quoting overhead and the patchy style of it are enough to deem this an ugly hack in my eyes. Imagine trying to make this work with regular expressions (e.g. `sed`) and deferred variable substitution.

Other than the workarounds above, I couldn't find a way to facilitate command grouping with the current command substitution capabilities in Fish (2.2.0).
These doesn't work:
```fish
(ls /usr/sbin; ls /sbin') | sort | uniq | column
command (ls /usr/sbin; ls /sbin') | sort | uniq | column
```
Something in the syntax of a parenthesis in the start of the command line just makes Fish wait for something more after pressing Return.

As for the Bash syntax, I personally find the command grouping syntax with either type of braces ('()' or '{ }') readable and intuitive in the examples above, but if anyone has bad experience with command grouping syntax in Bash or any other shell that supports it, it would be interesting to hear.

[Command Grouping]: http://www.gnu.org/software/bash/manual/html_node/Command-Grouping.html

**Comment by faho** [comment]
>{ cp libmysillylib.so /usr/lib/; ln -s /usr/lib/libmysillylib.so /usr/lib64/ } ^ errors.log

```fish
begin; cp libmysillylib.so /usr/lib/; ln -s /usr/lib/libmysillylib.so /usr/lib64/; end ^ errors.log
```

actually works.

**Comment by oranja** [comment]
Ok. I feel dumb now for not trying this. Replacing { and } with begin and end is so standard Fish, plus it's in the docs. I should have RTFM more thoroughly.
My apologies, and thank you.

**Comment by faho** [comment]
Haha, no problem.

Have a nice weekend!
