### ISSUE TITLE
Should I add a shebang to my script?

### ISSUE THREAD

**Issue by edouard-lopez** [fish-shell/fish-shell#2583]
I'm new to `fish`, but have some background in `zsh` and `bash`. 

As I'm working to make [pure-fish theme](https://github.com/rafaelrinaldi/pure) supported in `oh-my-fish`, I was a bit surprised that [`omf new theme my_theme`](https://github.com/oh-my-fish/oh-my-fish/wiki/Advanced#creating) command create boilerplate files without a shebang. 

I was expecting to see:

    #!/usr/bin/env fish

Should I add a shebang to my scripts? Is it a `fish` best-practice?

**Comment by terlar** [comment]
Depends on what you plan to do, the shebang is there if you plan to execute/run the script by itself, and doesn't really provide any value for fish scripts that are supposed to be sourced or not run by themselves.

**Comment by izumidamasa** [comment]
Hello. Does not make sense for your theme, which works OK to add ohmyfish support. Let me explain, instead omf should support your theme, or any theme I think.

And btw, I have being useing https://github.com/vkovtash/pure for a few months now. What is the difference with your theme?

**Comment by edouard-lopez** [comment]
@izumidamasa I'm not the author of the fish version, just working on the omf port.

**Comment by faho** [comment]
I'd say you SHOULD have a shebang if it's a standalone program that just happens to be written in fishscript, but you SHOULD NOT have one if it's meant to be sourced (like a function definition).

The reason being that running a function definition by itself is not useful. These files also should not have the executable bit on them.

Does that make sense?

**Comment by edouard-lopez** [comment]
Yep, nice explanation but if it not harmful, I like to have a prologue that tell what interpreter is needed.

**Comment by edouard-lopez** [comment]
Yep, nice explanation but if it not harmful, I like to have a prologue that tell what interpreter is needed.
