### ISSUE TITLE
history multiline commands

### ISSUE THREAD

**Issue by leiserfg** [fish-shell/fish-shell#2585]
There are a way to get multilines commands on history not as one single command (maybe by un-escaping the output).

**Comment by faho** [comment]
Depends on what exactly you want. `$history` will contain these things as one element, but you can then apply splitting manually - `set line (echo $history[1])` will do that to the most recent history element.

**Comment by leiserfg** [comment]
Thanks!

**Comment by faho** [comment]
@leiserfg: What is it you want to do with this, though?

**Comment by leiserfg** [comment]
I'm trying to improve the ctrl-r bind of fzf. I can do that by reading `cat fish_history|sed ...`  but it's not a clean way.

**Comment by faho** [comment]
Yeah, it'd work for that. (Your sample command contains a useless-use-of-cat, btw - sed can read files)
