### ISSUE TITLE
Command execution in folder completion

### ISSUE THREAD

**Issue by karlek** [fish-shell/fish-shell#2588]
__Steps to reproduce:__

```fish
$ mkdir "(firefox asdf) "
$ cd firefox[TAB][TAB]
# First tab: Becomes -> \(firefox\ asdf\)\ /
# Second tab: Will execute command "firefox" with the argument "asdf"
```

__Expected behaviour__
Not opening firefox.

**Comment by karlek** [comment]
Gives appropriate error messages if the command doesn't exist: i.e "(furfox asdf) ":
```fish
(^._.^)ﾉ @ /tmp $ cd \(furfox\ asdf\)\ /fish: Unknown command 'furfox'
- (line 1): furfox asdf
            ^
in command substitution
	called on line -1 of file -

from sourcing file -
	called on line 60 of file /usr/share/fish/functions/eval.fish

in function “eval”
	called on line 45 of file /usr/share/fish/functions/__fish_complete_cd.fish

in function “__fish_complete_cd”
	called on standard input

in command substitution
	called on standard input
```

**Comment by faho** [comment]
This should be fixed by 0a99772572ab8632f103f05570da707683980d17 (not in any release yet). The issue was that __fish_complete_cd used `eval`.

If it still occurs with that, please comment!

**Comment by karlek** [comment]
Thanks for the fix, but I unfortunately found a bug in your commit. The command execution problem was fixed, but folder tab-completion now inserts an extraneous `/`.

I cherry-picked the 0a99772 commit from the 2.2.0 release.

Example:
```fish
# In home directory.
$ cd Desk[tab]
# Completes to `Desktop//`, expected `Desktop/`
```

**Comment by faho** [comment]
@karlek: We already found that - you might want to cherry-pick 434eabb7878178a095b8508ccbf5d232461e8d95 too.

**Comment by karlek** [comment]
Awesome!
