### ISSUE TITLE
Next-Major to solve all broken syntax?

### ISSUE THREAD

**Issue by jakwings** [fish-shell/fish-shell#2597]
As a new comer, I am so surprised by all those ugly details about fish:

#159 No support for command substitution in quoted strings and the strange `count` function.
#354 The conflict between variable expansion and brace expansion.
#436 Fake arrays
#826 Array index out-of-bound errors
#2596 The magical PATH/CDPATH/MANPATH/… variables breaking the consistency of variable expansions.

fish is becoming another ugly bash

**Comment by ridiculousfish** [comment]
These are not ugly details! All software (especially user-facing software) has to balance competing concerns and make tradeoffs, and all of the issues you list reflect some compromise between power and simplicity, or consistency and convenience, etc. For example, if we fixed #354 and removed brace expansion, we'd get a new issue "No support for brace expansion" overnight. And that's OK: it's good to catalog our tradeoffs, and capture discussions about them.

These are all long-standing issues dating from fish 1.x, so I would dispute "becoming."

We're happy to have you as a user of fish and we welcome your ideas for improvements. Please do share them in the linked issues. Meanwhile I'm going to close this one, as it's not helpful.

**Comment by jakwings** [comment]
Thank you for the reply. May I create a wiki page to list all these ugly parts so new developers can find them easily and early?

Or could you give those issues a new tag like "DIFFICULT", not just "future", "tank" or "next-major"? because I can feel that such long-standing issues are not likely to be solved with a major version from what you said.

Time is precious, so I post this issue and ask for your/all developers' opinions and hope that less people will keep suffering from those compromises. I'm happy to keep using fish though it is uneasy to do some complicated work. Fish does have a good philosophy behind it. It can help to create more useful tools.

**Comment by ridiculousfish** [comment]
Yes, for sure! In particular see #2382 which is a request for a "cheat sheet" for users who are accustomed to bash. We'd put this right into the documentation and on the website, not just a wiki page.
