### ISSUE TITLE
Why using parenthese/command-substitution disables terminal color?

### ISSUE THREAD

**Issue by adamcavendish** [fish-shell/fish-shell#2604]
I have a perror function here, which set the terminal text color to red and print the error.

However, if I use the function inside a command-substitution, it prints out the error message, but not in red.

Why is it not setting the color?

```
function fext_error -d "Print error message to the console"
  set_color red
  echo $argv >&2
  set_color normal
  return 0
end

function getVal
  # do the check, if right, return "hello"
  if test (count $argv) -eq 1
    echo "hello"
    return 0
  end

  fext_error "No args"
  return 1
end

set -l value (getVal 100)
echo '---'
set -l value (getVal)
```

**Comment by ridiculousfish** [comment]
Command substitutions capture stdout but not stderr. Your `set_color` calls go to stdout, your `echo $argv` goes to stderr. Try sending set_color to stderr too: `set_color red >&2`

**Comment by adamcavendish** [comment]
First `set_color red >&2` works, Thx.

However, there's a question.
If I do `fext_error "Hello"` in console, it's output is red. Is it not a miss leading?

**Comment by ridiculousfish** [comment]
I think what's misleading here is that `set_color` looks like it manipulates some internal state, when really all it does is output an escape code to stdout. Unfortunately I don't think there's anything fish can do about this: the tty is what it is.

**Comment by adamcavendish** [comment]
Ok. I used to think that fish was maintaining it. I know bash is just escape characters, like `\e[0;1;49;39mBla Bla Bla\e[0m`

Would it be a better idea that fish maintaining it inside, which fish manually set the color before print and set back to normal afterwards?

**Comment by ridiculousfish** [comment]
Maybe, but I lean no. What's nice about the current design is that it's a very thin layer atop the underlying system: if you understand escape sequences you instantly understand `set_color`. What's bad about the current design is that that underlying system is pretty gross, and thin layers lets all of the grossness bubble up through. Despite that, I would say that the role of a shell is to expose the capabilities of the OS,  not to paper over them, so `set_color` should remain true to its underpinnings and just barf out ANSI escape sequences.

Or in other words, if `echo hello` does anything other than print 'hello' to stdout, we'll be adding more problems than we solve.

(Sorry for all of the mixed metaphors!)

**Comment by adamcavendish** [comment]
Ok, I understand. Thx so much.

**Comment by ridiculousfish** [comment]
Thank you for filing this issue.
