### ISSUE TITLE
`mount /dev/sd[tab]` only displays /dev/sda[0-9] not /dev/sd[a-z][0-9]

### ISSUE THREAD

**Issue by karlek** [fish-shell/fish-shell#2606]
I'm sorry for the awful issue title, but it was the most terse description I could write!

The problem is that even though I have two USB block devices connected, `sdb` and `sdc`, fish only recognizes (and autocompletes) `sda` partitions.

I expected all block devices to be visible with `/dev/sd[tab]`.

It seems the problem lies with the `mount`-commands completion. 

![out](https://cloud.githubusercontent.com/assets/1278705/11764691/c8bd6042-a13a-11e5-9ff6-9079b1767c85.gif)

![out28478](https://cloud.githubusercontent.com/assets/1278705/11764694/ea83c09a-a13a-11e5-9a50-846ecf936d5f.png)

**Comment by ridiculousfish** [comment]
It looks like the mount completion only looks in /etc/fstab. I don't know if this is correct or not (that file doesn't even exist on OS X)

**Comment by krader1961** [comment]
@karlek What OS and version are you using? What are your expectations? By which I mean do you expect the completion to only enumerate what is in /etc/fstab (or the equivalent for your OS) or all matching block devices in __/dev/__ or something else?

The current __mount__ completion code assumes the OS has a `/etc/fstab` file and the user only wants completions for mount points already defined in that file. Your question implies you are either not on a system with a `/etc/fstab` file or you expect different behavior. I'm betting the latter.

**Comment by pickfire** [comment]
@ridiculousfish I think it shouldn't look in `/etc/fstab` and instead find `/dev/sd*`. I didn't add anything to `/etc/fstab` so there is only one line but I will normally mount devices that is not in fstab.

@karlek I don't think `fish` only check `/etc/fstab` as autocompletion here checks for /dev/sda[1-3].

**Comment by faho** [comment]
>(that file doesn't even exist on OS X)

@ridiculousfish  So, how do I get the devices that `mount` can be called on without a mountpoint on OSX?

On linux at least, if `mount` is called with just a device or directory, it will check fstab for the other, so you only need to specify the one argument (nice for e.g. `mount /dev/sr0` or `mount /mnt/dvd` to mount a dvd).

Is that a thing on OSX?

Other than that, we currently _are_ missing the other devices. Is it correct to limit this to blockdevices? Probably theoretically not (one point is if "--bind" is given), though anything is better than what we have now.

I'll take a look.

**Comment by karlek** [comment]
@krader1961 As you deduced I expected the completion to include all block devices. (I use arch linux, fish 2.2.0)

@pickfire Hm, I only get entries from my `/etc/fstab`

**Comment by faho** [comment]
Okay, I now have a version that works on my system (also archlinux). There's a few open questions regarding OSX mount, though. So, @ridiculousfish, @krader1961:

- There's [a man page](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man5/fstab.5.html) for fstab, but from [this SO answer](http://superuser.com/questions/336455/mac-lion-fstab-is-deprecated-so-what-replaces-it-to-prevent-a-partition-from-m) it seems to not exist by default - do we care about fstab on OSX? If we don't, how do we find known devices to mount? (I.e. how do we call `getfsent`)

In case we do care:

- Does `mount /dev/XXX` work if /dev/XXX has an entry in fstab? It seems so from [the man page](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man8/mount.8.html), which has a form for "special | node"

- Does `mount UUID=` or `mount LABEL=` work?

For linux and BSD, this should work, while failing gracefully on systems without fstab:

```fish
function __fish_complete_blockdevice
	set -l cmd (commandline -ct)
	[ "" = "$cmd" ]; and return
	for f in $cmd*
		[ -b $f ]; and printf "%s\t%s\n" $f "Block device"
		[ -d $f ]; and printf "%s\n" $f/
	end
end

complete -x -c mount -a '(__fish_complete_blockdevice)'
# In case `mount UUID=` and similar also works
complete -x -c mount -a "(test -r /etc/fstab; and string replace -r '#.*' '' < /etc/fstab | string match -r '.+' | string replace -r ' ([^\s]*) .*' '\tMount point \$1')"
complete -x -c mount -a "(test -r /etc/fstab; and string replace -r '#.*' '' < /etc/fstab | string match -r '.+' | string replace -r '(^[^\s]*) ([^\s]*) .*' '\$2\tDevice \$1')"
```

**Comment by faho** [comment]
Thinking more about it, this doesn't worsen the situation on OSX (in fact it should improve it by checking for fstab readability), so I've just pushed it.

**Comment by ridiculousfish** [comment]
:+1:

**Comment by krader1961** [comment]
:+1: On OS X /etc/fstab is supported it's just not populated by default. It's most likely to be used by a power user with disks attached to their system they don't want automatically mounted at boot time. I didn't test your change but it looks like it should actually do something useful (beyond not spewing an error if /etc/fstab doesn't exist) for users who have created /etc/fstab.

**Comment by pickfire** [comment]
@karlek: Not everyone does that.
