### ISSUE TITLE
the "exec" command does not restore the non-fish terminal modes

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2609]
I noticed that my changes to resolve issue #217 result in the terminal modes inherited after a `exec` command are not the original terminal modes. That is, the exec'd program has ICRNL mode disabled which is wrong. This has always been broken but the problem is more visible with my change to disable the ICRNL tty mode to allow binding \cJ (or \n) separate from \cM (or \r).

The problem is that __safe_launch_process__ does not restore the non-fish tty modes before attempting to execute an external command. I'll fix this as soon as I understand the relationships among the functions involved in this scenario.

**Comment by ridiculousfish** [comment]
Cool, sounds good. Let me know if you have any questions.
