### ISSUE TITLE
Error message with ls command

### ISSUE THREAD

**Issue by viking777** [fish-shell/fish-shell#2621]
Every time I run the ls command with fish recently I get this error before the proper command output:
```
ls  /var/log/
test may be found in the following packages:
  
/usr/share/fish/functions/isatty.fish (line 26): 	command test -t "$fd"
                                                 	        ^
in function “isatty”
	called on line 9 of file /usr/share/fish/functions/ls.fish
	with parameter list “1”

in function “ls”
	called on standard input
	with parameter list “/var/log/”
```
What is this and how do I get rid of it?

Once the error message has been printed the command output is as you would expect. 
Using fish version 2.2.0-5 on Manjaro Linux

**Comment by faho** [comment]
Install something that provides a `test` in your $PATH - on linux, this should usually be in GNU coreutils.

**Comment by faho** [comment]
Can you provide the output of `type -a test` and `pacman -Qo /usr/bin/test`?

**Comment by viking777** [comment]
Here is a clue. If I downgrade to version 2.1.1-5 the error message goes away, but with any version of the 2.2 series it returns again.
taho the answer to your questions: 
```
type -a test
test is a builtin

pacman -Qo /usr/bin/test
error: failed to read file '/usr/bin/test': No such file or directory
```

**Comment by faho** [comment]
>If I downgrade to version 2.1.1-5 the error message goes away, but with any version of the 2.2 series it returns again.

Yep, that's because we worked around a bug in our `test` by calling the external one in `isatty`. (Which I'll grant is a bit silly)

Really, you want something to provide a `test` command, whether it be /bin/test or /usr/bin/test. Install that and this will work. On my archlinux system, the "coreutils" package contains such a thing. If manjaro strips it, they are doing something silly.

**Comment by viking777** [comment]
How strange? /usr/bin/test is listed in the coreutils package, but wasn't installed on my system. Reinstalled coreutils, /usr/bin/test appeared and the error message has gone!
Thanks taho,
Solved.
I will close the issue.
