### ISSUE TITLE
if/while Assertion failed: (job.production_idx == 0)

### ISSUE THREAD

**Issue by c22** [fish-shell/fish-shell#2625]
Fish doesn't like it when you start writing multiple line string input as the condition to an if/while

eg. type `if '<enter>`
if 'Assertion failed: (job.production_idx == 0), function job_should_be_backgrounded, file parse_tree.cpp, line 1717.
Abort trap: 6

or `while '<enter>`

while 'Assertion failed: (job.production_idx == 0), function job_should_be_backgrounded, file parse_tree.cpp, line 1717.
Abort trap: 6

**Comment by ridiculousfish** [comment]
Nice find! This was 'fixed' very recently in 8c707a4e2ffc30bae6d9ac3a28bd05fca0ff1195. However the assertion was real so we may only be masking the bug - still investigating.

**Comment by ridiculousfish** [comment]
Ok, the bug was that job_should_be_backgrounded was not handling unmaterialized nodes. In that recent fix, they happen to handle them correctly. So let's go with it. Closing as fixed in 8c707a4e2ffc30bae6d9ac3a28bd05fca0ff1195 - thanks for reporting this!
