### ISSUE TITLE
Spaces in arguments

### ISSUE THREAD

**Issue by stek29** [fish-shell/fish-shell#2629]
When I pass argument with spaces, enclosed in double quotes, in bash it is one argument.

However in fish it is two arguments. 

I use fish *2.20* on *OSX*, homebrew version.

Here's how I test it: I wrote tiny C program that prints out number of arguments and their values.

`./testarg "Hello World"` in `fish` gives me `3: "./testarg", "Hello", "World"`

But with `sh` same command gives me `2: "./testarg", "Hello World"`

**Comment by faho** [comment]
You mean

```fish
function banana
    for i in $argv
       echo $i
    end
end
banana "Mr Noodles"
```

will print

>Mr

>Noodles

? (in two lines rather than one)

That would be a rather large issue (and it doesn't behave that way for me).

**HOWEVER**, we require more information before we can do anything about it:

Which fish release are you using? Which function are you executing?

**Comment by stek29** [comment]
Sorry, I accidentally send unfinished comment

**Comment by faho** [comment]
@stek29: I'm afraid I still can't reproduce this. Not with a C-example of

```C
#include <stdio.h>
int main(int argc, char* argv[]){
		printf("%d\n", argc);
		return 0;
}
```

and neither fish 2.2.0 nor ToT fish (2.2.0-485-gd6d3977, i.e. current master). Both fish and bash print "2" for an invokation with `"Hello World"` - which is correct as argv[0] is the name of the called program.

**Comment by stek29** [comment]
Ok, thats pretty weird. This problem exist only when I build this with Xcode.

When I use command line `gcc` or `cc` it works great, but if I use Xcode build, it gives me 3 for `"Hello World"`
But in `sh` it gives me `2`!

**Comment by faho** [comment]
You mean building _fish_ with Xcode?

@ridiculousfish?

**Comment by stek29** [comment]
No, building example program with Xcode.
I'll upload my project to github tomorrow if I wouldn't be able to find problem at my own

**Comment by stek29** [comment]
Ok, I found problem. I stored path to binary in `bot` variable, and used `eval $bin "foo bar"`. And `"Hello World"` was for `eval`, but for `bin` it was `foo bar`, not `"foo bar"`.

**Comment by stek29** [comment]
So that was my problem, I'm sorry for this.
