### ISSUE TITLE
unexpected behavior between source and fish

### ISSUE THREAD

**Issue by macb** [fish-shell/fish-shell#2643]
Stumbled across some unexpected behavior when using `source` vs `fish`. 

The contents of `test.fish`:
```fish
set myvar (dirname (status -f))
echo $myvar
```

While using `fish` as my `SHELL` and using `source` to run the file the `myvar` variable is set to a relative path to the file being run.
```fish
➜ mydir source test.fish
.
```

However, when using `fish` to run the file the `myvar` variable is set to the absolute path to the file being run.
```fish
➜ mydir fish test.fish
/private/tmp/mydir
```

Is this expected? If so is there a workaround to keep the behavior consistent between the two of them? In this case we're expecting the absolute path to the file.

**Comment by ridiculousfish** [comment]
I think this has been fixed in ToT...bisecting now

**Comment by krader1961** [comment]
Both are technically correct and the documentation is ambiguous. It just says "prints the filename of the currently running script." without stating whether it will always result in an absolute path. Having said that I find the inconsistency surprising and would vote for updating the code and docs to state the path will always be absolute.

**Comment by ridiculousfish** [comment]
It's weird that fish would fully resolve the path when passed a file. This was introduced in 06fd1aa9f8aa2d9705ba942055c76518fb1da1f6 a long time ago (the call to `wrealpath` in main.c). I think we should get rid of that, so then `status -f` would always show the relative path used to invoke the script. Users can use `realpath` manually to resolve it. Any objections?

**Comment by krader1961** [comment]
Yeah, upon further reflection I agree that defining it to always produce a relative path if one was used in the first place makes more sense than always converting to an absolute path since there is a trivial command for doing the latter. Obviously if the user explicitly specifies an absolute path then that is what they'll get from `status -f`. It'd be good to update the status man page to clarify this point in addition to backing out that change.

**Comment by ridiculousfish** [comment]
bc3260402ad26664f704734c6b7168b4c647e970 makes the `fish ./test.fish` case not resolve paths, so it is consistent with `source` in returning a relative path. You can use `realpath` to resolve it explicitly.

Thanks for reporting this!

**Comment by macb** [comment]
Ah, thanks for taking a look! The absolute path without the need of another utility like `realpath` was pretty handy. Definitely better to be consistent though! Will update accordingly with that in mind.
