### ISSUE TITLE
Output of last command?

### ISSUE THREAD

**Issue by ElijahLynn** [fish-shell/fish-shell#2644]
Is there a variable for the output of the last command? Sometimes I get output that I want to capture and want to pipe it to my clipboard command.

**Comment by krader1961** [comment]
No, there isn't a magic var that contains the output of the last command. You have to explicitly capture it yourself: e.g.,

```
set myvar (ls)
```

If you're proposing that fish capture all the output of any command that is run how exactly would that work? What if the command is something like less or vim or you decide to cat a really large file? How much of the output should fish capture before giving up? Do we really want to pay the cost of setting up a pty or pipe for every external command without an explicit redirection of stdout?

**Comment by ElijahLynn** [comment]
Yeah, I think that is a no go. I remember looking at this a while ago for bash and the same conclusion was reached on how would you handle too large of an output.

Thank you for chiming in and for the example.

**Comment by hoverduck** [comment]
I was searching to see if this was possible, and from the above it sounds like the answer is reasonably no.  But for the benefit of anyone else looking for the same thing who comes across this issue, here's a function I hacked together to make a best effort at matching the functionality:

```fish
function rr
  set PREV_CMD (history | head -1)
  set PREV_OUTPUT (eval $PREV_CMD)
  set CMD $argv[1]
  echo "Running '$CMD $PREV_OUTPUT'"
  eval "$CMD $PREV_OUTPUT"
end
```

I've named it `rr` here for "rerun".  It just re-runs the previous command and captures the output, then executes the given command on that output.

Example:

```
user@hostname ~/tmp> ls *.txt
file1.txt file2.txt file3.txt
user@hostname ~/tmp> rr gvim
Running 'gvim file1.txt file2.txt file3.txt'
```

**Comment by Memphizzz** [comment]
This function is golden! Especially if you change it to the following:
function rs
  set PREV_CMD (history | head -1)
  eval "sudo $PREV_CMD"
end
Finally a real alternative to !! in bash!

**Comment by tojamrok** [comment]
That `rr` function is a solution to lack of `$(!!)` mentioned in https://github.com/fish-shell/fish-shell/issues/288.

**Comment by xster** [comment]
Thanks @hoverduck, that was really inspirational. Sorry if I'm spamming this 5 year old thread. I wanted to add my take on it too if anyone's looking for other options to increase ergonomics. 

Similarly, sometimes you might `ls` or `git status`, then you might want to do something with a line from the output. You can create a 

```fish
function __select_from_last
   set -l FZF_OUT (eval $history[1] | fzf)
   commandline -r $FZF_OUT
   commandline --cursor 0
end
```

Uses [fzf](https://github.com/junegunn/fzf) to fuzzy-search/select a line, changes your current command line buffer to the selection (so you can edit it a bit in case there's some noise in there) and puts the cursor to the beginning so you can add a "verb". Then `bind \er __select_from_last` or some such to trigger it by pressing alt-r after running the last command with output.

**Comment by liuml07** [comment]
Thank you @xster for sharing that.

I found it's nature to me to start with a command (e.g. `git diff`) and then realize I want choose from output of last command (e.g. `git status`). Also I may choose multiple times in the same command line, so adding a space in the end seems helpful. So I edited a bit:
```fish
function __select_from_last
	set -l FZF_OUT (eval $history[1] | fzf)
	if test -n "$FZF_OUT"
		commandline -a "$FZF_OUT "
		commandline -f end-of-line
	end
end
bind \cn __select_from_last
```

**Comment by bagohart** [comment]
Nice ideas! Here is another variation that I hacked together: It lets me choose which command I want to rerun, then lets me choose multiple lines of the old command (keeping the order), pastes those lines into the command line at the current cursor and then positions the cursor at the end of the new insertion.
```fish
function fzf_select_from_rerun_command_output
    set cmd (history | fzf --header "Choose the command to rerun.")
    if test -n "$cmd"
        set result (eval $cmd | fzf -m --header "Choose the line(s) from the repeated command\'s output to paste into the current command-line. (The order matters!)")
        if test -n "$result"
            commandline -i (string join " " $result "") # adds a space after the inserted line output
        end
    end
    commandline -f repaint
end

bind \e\cR fzf_select_from_rerun_command_output # bind to ctrl+alt+r

```

**Comment by linsomniac** [comment]
Sorry to reply on a closed thread, but here are a few ideas:

WRT "how to handle too large an output", I would imagine one could set a "window size" of say 4K and the capture buffer would just be a ring buffer of that size.  In my case, I'm wanting to make a shell alias that sends me a message with the output of the last command and exit code, so I really only need/want the last little bit.  Why not make it a wrapper?  Because sometimes I have a command running and don't want to kill or rerun it, but realize after the fact that I want it to notify me.  For example, last week I started a command but then it was still running when I went out to a meeting, I typed a "ntfy Command done" command in the terminal so it would run when the other command was done, but my coworker wanted me to send her the output and exit code.

One option I've found is that in tmux you can do "tmux capture-pane ; tmux save-buffer /tmp/pane" to save the tmux window text to a file.  I'm imagining I can get the same out of wezterm, so I'll probably do some more investigation.

**Comment by faho** [comment]
@linsomniac This is better handled in the terminal, we don't want to have all output flow through fish just in case you might want to use some. This would require fish to become a terminal (imagine what happens if the command wants to move the cursor or get the terminal's size).

**Comment by ElijahLynn** [comment]
OP here: follow up to this: I've been using the new Warp terminal (w/Fish), and it has a "copy output" on each command (w/shortcut) block that solves this need for me now.

**Comment by linsomniac** [comment]
@faho : Fair enough, but I'll add that there's a "good enough" option of saving the output without being fish becoming a terminal.  For example, for 30+ years and probably tens of thousands of times I've "cmd >file" and do something with that file that didn't require terminal emulation.  Not advocating for this feature, as I recognize the resistance.  Just responding to your terminal emulation mention.

As @ElijahLynn said, there are some pretty neat things being done in for example Warp with tracking commands vs output and operating on output, and I've come up with a case where retroactively having some access to previous stdout.

**Comment by ctison** [comment]
### Add a function that edit the command line
> https://fishshell.com/docs/current/cmds/commandline.html
```fish
# $fish_function_path[1]/alt-enter.fish
function alt-enter
  if test -n "$(commandline)"
    builtin commandline "set o ($(commandline))"
  else
    builtin commandline "set o ($(printf %s\n $history[1]))"
  end
  builtin commandline -a '; builtin printf %s\n $o'
  builtin commandline -f repaint
  builtin commandline -f execute
end
```
### Add a binding to `alt-enter`
> https://fishshell.com/docs/current/interactive.html#custom-bindings
> https://fishshell.com/docs/current/cmds/bind.html
```fish
# $fish_function_path[1]/fish_user_key_bindings.fish
function fish_user_key_bindings
  bind alt-enter  'alt-enter'
  # bonus: send $o to clipboard
  bind ctrl-alt-s 'printf %s\n $o | fish_clipboard_copy'
end
```

**Comment by sud0xenn** [comment]
Sorry for commenting on such an old issue but just an idea: How about fish uses a named pipe created using `mkfifo` which writes to it the output of last command? And before doing it clears the pipe so it only contains the last output? Named pipes are kernel memory only, lightweight and inexpensive.

EDIT: This would obviously mean that while working on multiple shells, it would still contain the last used so the limitation here would be to use the output right away or rerun the command. But in most of the cases when working with a single shell a fifo makes more sense.
