### ISSUE TITLE
Why am I allowed to add a character to a list of variables that I can't remove?

### ISSUE THREAD

**Issue by lfiolhais** [fish-shell/fish-shell#2647]
This is more of a question than an issue. I've noticed the following behavior to be confusing.
I've created the following list.
```fish
$ set -l test . 2 3 -
$ echo $test
. 2 3 -
```
When I try to remove the first or last element of the list it errors out.
```fish
$ set -e $test[1]
set: Invalid character '.' in variable name. Only alphanumerical characters and underscores are valid in a variable name.
```
Why does this happen? Isn't this counter intuitive?

**Comment by faho** [comment]
You need to pass the variable _name_ to `set`, not the value - in other words, drop the "$".

`set -e $test[1]` will try to execute `set -e .`, which means it'll try to erase a variable called ".".

`set -e test[1]` does what you want.

**Comment by lfiolhais** [comment]
Yes. Just figured it out. Thanks!
