### ISSUE TITLE
Executable search enhancing variable

### ISSUE THREAD

**Issue by rumkin** [fish-shell/fish-shell#2651]
Hi, I have my own applications directory structure that looks like this:

```text
~/apps/%name%/bin/application
``` 

I wish to make this applications be accessible like usual executable in $PATH. I looked at executable search function `path_get_path` but it has no any options to do so. I suggest it would be very useful to add variable like `__fish_complete*` to specify custom search util. This variable could be used after `$PATH` search failed to avoid compatibility issues.

**Comment by faho** [comment]
Why not add these directories to $PATH directly?

```fish
set PATH $PATH ~/apps/*/bin/
# or
set fish_user_paths ~/apps/*/bin/
```

?

**Comment by rumkin** [comment]
1. Because executable has name `app` and I actually not sure it will work.
2. Even if it work it will become slower with each new app, isn't it?
3. I think my case is just one of possible. Suggested solution is more flexible to make custom layouts.

**Comment by faho** [comment]
I'm afraid I don't quite understand what you want. What would you like this variable to contain? How should it be used?

>Because executable has name app and I actually not sure it will work.

You mean you have multiple directories ~/apps/$name/bin, and each of those contains an executable simply entitled "app"? No, that won't work with the normal $PATH scheme - the first entry wins.

>Even if it work it will become slower with each new app, isn't it?

It should be slower for commands that aren't found (or that are found only after checking most of $PATH), yes. However I suspect that as long as you don't add hundreds of paths it should perform fairly well.

Have you looked into using [abbreviations](http://fishshell.com/docs/current/commands.html#abbr)? These will expand when used interactively.

Or you could define functions:

```fish
for i in ~/apps/*
    function (basename $i) --inherit-variable i
        eval $i/bin/app (string escape -- $argv)
    end
end
```

(`string escape` is not in a release yet. It's used here to make the arguments eval-safe)

>I think my case is just one of possible. Suggested solution is more flexible to make custom layouts.

I believe something shouldn't be made flexible just for the sake of it - what other uses are there?

**Comment by rumkin** [comment]
I think it should contain an executable name or path (or list). This executable should get name of missed command as an argument and return an absolute path and exit status 0 or nothing if command was not found and exit status 1.

```shell
$ set __fish_cmd_search /usr/bin/my_cmd_search
$ some_cmd # /usr/bin/my_cmd_search some_cmd > /home/user/apps/some_cmd/bin/app
```

So in this way I could add hundreds or thousands of apps in `~/apps` directory. This way let me to add more efficient command search without garbaging the `$PATH`.

**Comment by faho** [comment]
>without garbaging the $PATH.

But this is what $PATH is _for_! That's literally the only thing it is good for! If there's an optimization possible there, it should be fixed instead of worked around!

>I think it should contain an executable name or path (or list). This executable should get name of missed command as an argument and return an absolute path and exit status 0 or nothing if command was not found and exit status 1. Returned path should be executed. Search command name should be provided as $CMD_SEARCH.

Anyway, if you'd like to do this, you can use a handler for fish_command_not_found:

```fish
function __fish_command_not_found_handler --on-event fish_command_not_found
  /usr/bin/my_cmd_search $argv
end
```

This will break completion and syntax highlighting (though you could use `commandline` to edit the commandline, allowing you to edit it - this would basically do the same thing as abbreviations).

We're not going to add this to fish, I think, but if you like you can cook something up for yourself.
