### ISSUE TITLE
Fish debian repo seems to be broken

### ISSUE THREAD

**Issue by Debilski** [fish-shell/fish-shell#2653]
$ curl -o - http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_7.0/Packages | head -15

    Package: fish
    Version: 2.2.0-1
    Architecture: amd64
    Maintainer: ridiculous_fish <corydoras@ridiculousfish.com>
    Installed-Size: 5458
    Depends: libc6 (>= 2.12), libgcc1 (>= 1:4.1.1), libncurses5 (>= 5.5-5~), libstdc++6 (>= 4.6), libtinfo5, passwd (>= 4.0.3-10), bc, gettext-base, man-db
    Recommends: python (>= 2.6), xsel (>= 1.2.0)
    Filename: ./amd64/fish_2.2.0-1_amd64.deb
    Size: 1722112
    MD5sum: 140e31df39226c87543102df8092c967
    SHA1: 33d3a3919a0f9bb351b7e40b4329be221e65bee7
    SHA256: c889c6a3ee0609c0f801b6d25ed216d000b712a10884e362d5a8783a8fac15f7
    Section: shells
    Priority: extra
    Homepage: http://fishshell.com/

    $ wget http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_7.0/./amd64/fish_2.2.0-1_amd64.deb
        --2016-01-04 14:21:55--  http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_7.0/amd64/fish_2.2.0-1_amd64.deb
    Resolving download.opensuse.org (download.opensuse.org)... 195.135.221.134, 2001:67c:2178:8::13
    Connecting to download.opensuse.org (download.opensuse.org)|195.135.221.134|:80... connected.
    HTTP request sent, awaiting response... 302 Found
    Location: http://ftp5.gwdg.de/pub/opensuse/repositories/shells:/fish:/release:/2/Debian_7.0/amd64/fish_2.2.0-1_amd64.deb [following]
    --2016-01-04 14:21:55--  http://ftp5.gwdg.de/pub/opensuse/repositories/shells:/fish:/release:/2/Debian_7.0/amd64/fish_2.2.0-1_amd64.deb
    Resolving ftp5.gwdg.de (ftp5.gwdg.de)... 134.76.12.5, 2001:638:60f:110::1:1
    Connecting to ftp5.gwdg.de (ftp5.gwdg.de)|134.76.12.5|:80... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 1717944 (1.6M) [application/x-deb]
    Saving to: ‘fish_2.2.0-1_amd64.deb’

    fish_2.2.0-1_amd64.deb                                      100%[===========================================================================================================================================>]   1.64M  6.60MB/s   in 0.2s   

    2016-01-04 14:21:55 (6.60 MB/s) - ‘fish_2.2.0-1_amd64.deb’ saved [1717944/1717944]

As you can see, the file size is different and leads to a failure in apt-get.

**Comment by jeremiejig** [comment]
Hello,

I see the same problem.

**Comment by Debilski** [comment]
To be more specific: This leads to a trust failure. As I see it, there is no way for me to be sure that the server or package can be trusted. I can’t even download a fish .deb file and put it into my own apt repo, because there is no way to download it without apt.

**Comment by zanchey** [comment]
I'm trying to work out if there's a way to fix this without triggering a full rebuild of all packages (which will trigger reinstallation for subscribers), but I don't think so.

**Comment by Debilski** [comment]
If it does not work to update them in the repo, would it be possible to at least enable https for accessing the packages?

**Comment by zanchey** [comment]
I've not got any control over OBS, and there's no support AFAIK for delivering over HTTPS (the GPG-signing of the packages obviates this and arguably provides better security for the actual package than HTTPS, although of course plain HTTP does not obscure the metadata of package downloads).

Rebuilding the packages didn't work and I haven't had any bites on the OBS mailing list - I've commented on https://github.com/openSUSE/open-build-service/issues/1130 and hope to hear back soon.

The nuclear option is to upload a new release (2.2.0-3 or whatever we're up to) but that is less than desirable.

**Comment by zanchey** [comment]
@Debilski and @jeremiejig, how are you downloading the package? Is it just with `apt-get`? If so, could you try and work out what User-Agent your version of apt sends?

The reason I ask is that the download server seems to send a different version of the package depending on the User-Agent of the client!

```
> curl -o - -L http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_7.0/./i386/fish_2.2.0-1_i386.deb | sha1sum
11425a07040b6fa60bc27e83c3e1c9fb5bf043eb -
> curl --user-agent "Debian APT-HTTP/1.3 (1.0.9.8.2)" -o - -L http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_7.0/./i386/fish_2.2.0-1_i386.deb | sha1sum
f201a586eb5fb058d3b732ac5bfa1a296ffbf648  -
```

**Comment by jeremiejig** [comment]
Hello,

Yep that was it, I use apt-cacher-ng, so the user agent was `Debian Apt-Cacher-NG/0.8.0`
The download worked with `Debian APT-HTTP/1.3 (1.0.9.8.1)` (apt-get without apt-cacher proxy)

So the bug seems to be opensuse related.

**Comment by zanchey** [comment]
I agree - I don't know that there's much we can do at present.

The next release is around the corner and that should resynchronise everything (I hope).

**Comment by zanchey** [comment]
This works fine with the new 2.3.0 builds.
