### ISSUE TITLE
[Feature request] Add ^n, ^p Emacs key bindings for completions

### ISSUE THREAD

**Issue by sachin21** [fish-shell/fish-shell#2656]
I couldn’t use `^n`, `^p` Emacs key bindings on fishshell.
I was using emacs keybindings with zsh. so I’m not used to cursor key.
I want to use `^n`, `^-p` Emacs key bindings for completions.

My environment is OS X `10.10.5` and fish `2.2.0`
<img width="620" alt="screenshot 2016-01-04 20 56 40" src="https://cloud.githubusercontent.com/assets/3052342/12108098/b14c00b0-b3b6-11e5-8bcf-c6848d827bf8.png">

**Comment by bucaran** [comment]
@sachin21 You can customize key bindings using `bind`.

See `man bind`.

For example:

```
bind \cn backward-word
```

Will be like traditional Ctrl+A.

**Comment by sachin21** [comment]
@bucaran Thank you very much! solved with that :smile:

**Comment by bucaran** [comment]
:+1:
