### ISSUE TITLE
Empty line gets printed when no fish_greeting is defined

### ISSUE THREAD

**Issue by femnad** [fish-shell/fish-shell#2660]
Since commit 834ebef53cf8f58ad53344b053f6d3225d78e0fd, if the user has not defined a fish_greeting function an empty line gets printed each time a new shell is created. Inspecting the commit I can see that the old implementation avoided printing anything if the fish_greeting variable is empty. Is this new behaviour intentional, in that the user has to explicitly define an empty fish_greeting if no greeting is desired?

**Comment by jrobeson** [comment]
fixed here? https://github.com/fish-shell/fish-shell/commit/4b2495f28fa420f6271b336b292556bce442b7d3

**Comment by ridiculousfish** [comment]
Looks like, thanks!
