### ISSUE TITLE
Get name of calling command

### ISSUE THREAD

**Issue by ElijahLynn** [fish-shell/fish-shell#2663]
I want to use the command `trash` instead of `rm`. Below is the function I have to help when I accidentally use `rm`.  I also have the command `z` (jump) and `z` uses `rm`. I want to have the check look for the name of the calling command to `contains trash` or something like that. So when I run trash, I get the message. But in scripts `rm` works as it should. Open to other ways too but that is my current use case.

```
function rm
    if status --is-login; and status --is-interactive
           echo "This is not the command you are looking for, use trash-put instead.";
    end
end
```

**Comment by ElijahLynn** [comment]
Because right now when I use `z` it fails badly.

**Comment by ridiculousfish** [comment]
Getting the caller's name is pretty exotic and there's no natural way to do it, though I guess you could hack up `status -t` if you are determined. I suggest using `command rm` at the blessed call sites to skip your wrapper.

**Comment by krader1961** [comment]
Checking the caller's name is fragile and therefore not a good solution. What you really want is a way to test whether a function was invoked directly from an interactive prompt. But you'll have to create a change to the `status` command to implement that behavior. You'll find it simpler to simply do what @ridiculousfish suggested and use `command rm` in your fish code.

**Comment by ElijahLynn** [comment]
Okay, thanks for the discussion guys. 

I didn't even realize I was using z-fish, it has been a while since I installed it. I was thinking I couldn't modify it because not everyone had fish. But turns out this repo is just for fish. I just made a PR https://github.com/sjl/z-fish/pull/7.
