### ISSUE TITLE
Tab completion with a folder with capital letters

### ISSUE THREAD

**Issue by danielcompton** [fish-shell/fish-shell#2672]
```sh
mkdir test
cd test
mkdir Application
mkdir application-extension
```

Now type `applica`, you will see

![screenshot of iterm2 11-01-16 3-54-15 pm](https://cloud.githubusercontent.com/assets/811954/12226096/93a8fbf2-b87b-11e5-854c-1f85c9ebe1d2.png)

but when you press tab, the tab completion ignores `Application`, and expands out fully to `application-extension`.

![screenshot of iterm2 11-01-16 3-55-16 pm](https://cloud.githubusercontent.com/assets/811954/12226106/bac25684-b87b-11e5-90cd-29493df7c1d6.png)

I think the reason for this is that it's not handling the capital letter in `Application` properly, as the same thing doesn't happen if it is in lower case.

**Comment by ridiculousfish** [comment]
The command line will show the case of the autosuggestion - see #335. In this case the special `cd` autosuggestion is preferring a case-insensitive match  over a case-sensitive one. That ought to be fixed. Nice find.

**Comment by ridiculousfish** [comment]
Thanks for reporting this!
