### ISSUE TITLE
Config for fish history length

### ISSUE THREAD

**Issue by dvcrn** [fish-shell/fish-shell#2674]
Hi, new fish user here!

I couldn't find how to set the maximum length for the fish history file. Is that even possible? 

On my mac for example, I prefer a very very long history to probably date back weeks. On my servers however, if I were to use fish, I want something small and light weld.

**Comment by zanchey** [comment]
I wrote some notes on this in https://github.com/fish-shell/fish-shell/issues/940#issuecomment-23636532 (and there are several related issues containing insightful comments), but the short answer is that fish uses a LRU list to manage history, that it's limited to 256k unique items, and that there's no configuration knob to control this. There's not been a compelling case made for changing this so far, so I'm going to close the issue for now although if you can think of something then definitely speak up.

**Comment by ridiculousfish** [comment]
To build on what zanchey said, fish de-duplicates history so history files are generally smaller than in other shells. In practice you can easily have years of history in a few 100 KB.  Or if you only run a few commands on the server, the files will be very small. If the history files are larger than you expect or want, please report that. Thanks for filing this.

**Comment by dvcrn** [comment]
Thanks for clearing that up! I just found it odd that fish didn't have that option and thought I must have missed it.

**Comment by alphapapa** [comment]
@ridiculousfish I was also curious about this.  I'm happy with the way it currently seems to work, but I would like to know, how much history does Fish keep?  Is it unlimited?

**Comment by krader1961** [comment]
@alphapapa: It is not unlimited. From `src/history.h`

```
#define HISTORY_SAVE_MAX (1024 * 256)
```

That limit is a trifle vague but it means that the most recently executed 256K (262,144) entries are saved. Why that limit? It's arbitrary and reflects the propensity of programmers to use power of two (2^n) values.

**Comment by ridiculousfish** [comment]
That's right! To be clear, those are 256K unique commands. Running the same command multiple times only requires one history "slot".

**Comment by alphapapa** [comment]
@krader1961 Thanks, I was going to look into that but you saved me the trouble.

@ridiculousfish Thanks.  I think that is probably enough.  :)  I'm currently at 12,400 unique commands since about this time last year (I must have wiped out the history around that time...oops).

**Comment by rsalmei** [comment]
Hey, I'm sorry to revive an old thread, but I'd like to ask a related question...

Please @ridiculousfish, you said that fish de-duplicates history, and I'm writing a small tool to import my zsh history, and change to fish for good.
So, in my tests, I do not see this behavior, does fish only de-duplicates if the it needs space?

Let's see, in one session:
```shell
- cmd: docker ps
  when: 1522644420
- cmd: docker ps -a
  when: 1522644435
- cmd: docker ps
  when: 1522644442
- cmd: docker ps -a
  when: 1522644451
```
Between sessions:
```shell
- cmd: pyenv shell 3.5.4
  when: 1522642627
- cmd: pyenv shell 3.5.4
  when: 1522642801
- cmd: pyenv shell 3.5.4
  when: 1522642808
```

Both are contiguous sections of the history file. In neither case it was de-duped... When this is actually applied? Thank you!!

**Comment by ridiculousfish** [comment]
fish deduplicates every 25 commands, starting at a random number (so the first dedup is probably fewer than 25 commands). See the logic around `countdown_to_vacuum` in `history.cpp`.

**Comment by rsalmei** [comment]
Nice @ridiculousfish, thanks!

Just one more question, please.
Why do some entries are written with a "path" component and some don't?
Example:
```shell
- cmd: echo (which fish) | sudo tee -a /etc/shells
  when: 1522978375
  paths:
    - /etc/shells
- cmd: mv /usr/local/Cellar/pyenv/1.0.3/versions/ /usr/local/Cellar/pyenv/1.2.2/
  when: 1521681288
  paths:
    - /usr/local/Cellar/pyenv/1.0.3/versions/
    - /usr/local/Cellar/pyenv/1.2.2/
```
but
```shell
- cmd: cat ~/.config/fish/functions/pyenv.fish 
  when: 1521684129
- cmd: time /usr/local/bin/zsh -i -c exit
  when: 1521000722
```

**Comment by ridiculousfish** [comment]
The paths indicate which arguments were file paths, as a hint to the autosuggestion machinery. For example, if I run `cat ../file.txt`, and there's a file at `../file.txt`, fish will only suggest that command when `../file.txt` is again a file. This helps avoid suggesting certain commands that would otherwise be invalid.

**Comment by rsalmei** [comment]
Ok, that's very nice.
But why aren't all paths extracted, like I've shown? `cd` for instance seems to never extract any paths.

**Comment by ridiculousfish** [comment]
The path detection is pretty naive and doesn't do any expansions, even tilde expansion. This is something that ought to be fixed some day.

**Comment by hashier** [comment]
@rsalmei could you share your script to import zsh history to fish history?

**Comment by rsalmei** [comment]
Hey @hashier, yes I could!
I can publish it in the next few days, I'll let you know 😉

**Comment by rsalmei** [comment]
Hello @hashier and anyone interested in migrating your zsh history to fish.
I'm happy to announce I've just published a python lib in PyPi to do this, check it out! 😃 
https://github.com/rsalmei/zsh-history-to-fish
