### ISSUE TITLE
Pipe Loop Output to File

### ISSUE THREAD

**Issue by zQueal** [fish-shell/fish-shell#2675]
I'm trying to generate seed data. For which I'm using a bunch of commands to generate data. (doesn't have to be random)

    while true
        sleep 1
        date +%s | sha256sum | base64 | head -c 32; echo
    end

I want to be able to let this file generate a string every 1 second, but to print to both stdout __and__ to a file on my HDD.

Anyone have a solution here? I've been searching the documentation but have come up empty.

I tried using standard operators to create and add a new file;

    while true
        sleep 1
        date +%s | sha256sum | base64 | head -c 32 >> data.seed
    end

Which _does_ work, however, there's no separation of newlines. All text is just in one large file with no spaces or new lines. I've also noticed that things like `echo \n` work, but when I add it to the echo command, all data output is replaced with a new line, instead of the data _and_ a new line.

**Comment by ridiculousfish** [comment]
Tried `tee`?

**Comment by krader1961** [comment]
As @ridiculousfish suggested the __tee__ command is typically used to solve your problem. Another option is to capture the output in a variable then use two __echo__ commands to write the contents of the var to stdout and a file. Which option is best depends on whether or not the buffering that occurs by piping the output through __tee__ is a problem.

**Comment by pickfire** [comment]
@zQueal `date +%s | sha256sum | base64 | head -c 32 | tee data.seed` just like what @ridiculousfish said.

**Comment by zQueal** [comment]
I feel a little ridiculous for not remembering that `tee` was a thing. Still doesn't solve one issue though. I need each new string on a new line. `tee` pipes the output directly to the file, which is one long string.

![qakwqedtbp](https://cloud.githubusercontent.com/assets/239193/12369869/807f5aa8-bbcd-11e5-9dec-8ba5b40d8873.png)

**Comment by krader1961** [comment]
Put the __tee__ command outside the __while__ block should work. For example,

```fish
while true
   whatever
end | tee -a data.seed
```

However I just tested that and it doesn't work. I consider that a bug but given fish doesn't claim to be POSIX compliant it may not be. I'll defer to @ridiculousfish for whether or not that is a bug.

Regardless, I'm pretty certain that even if that construct worked you would not find it satisfactory due to the buffering done by the stdio library when writing into a pipe. I'm willing to bet you want this formulation:

```fish
while true
    sleep 1
    set -l t (date +%s | sha256sum | base64 | head -c 32)
    echo $t
    echo $t > data.seed
end
```

**Comment by zQueal** [comment]
@krader1961 this works perfectly! Thanks for the help!
