### ISSUE TITLE
Can i use " * " as argument for a function?

### ISSUE THREAD

**Issue by demonking** [fish-shell/fish-shell#2678]
Can i use "*" as argument for functions?
Everytime i use it,  argv it return all files in the current directory.
I know, that I could use \* but would like to use it without escaping.

**Comment by ridiculousfish** [comment]
`*` is a wildcard and so must be escaped. You can escape it with double quotes `"*"`, or single quotes `'*'`, or backslash `\*`.

How would you like to see this work? How would you indicate whether * should be a wildcard or not without escaping? Or are you asking for * to be removed as a wildcard entirely?

**Comment by demonking** [comment]
Ok, there is no other solution, i only asked, because i wanted to create a function for this 
https://github.com/fish-shell/fish-shell/issues/1511

**Comment by krader1961** [comment]
I'm curious why you didn't simply add a comment to #1511? Regardless, you are correct there is currently no way to do what you want. We would need to augment fish to provide a means of defining a function with annotation that any wildcard arguments to it should not be expanded before invoking the function. Which would add considerable complexity for a very narrow use case. Please close this issue, @demonking, and if you still feel strongly about implementing this capability please continue the discussion in issue #1511.

**Comment by demonking** [comment]
@krader1961 because it's another question. I wanted to ask if it's possible to use the '*' as argument.
maybe i also wanted to use it in another example.
I close it here, because my question was answered.
