### ISSUE TITLE
IRC #fish topic references a URL that isn't useful

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2679]
@zanchey, I noticed that when I connect to the #fish IRC channel the topic says

```
The topic for #fish is: fish - The Friendly Interactive SHell | fish 2.2.0 released at http://fishshell.com | Finally, a command line shell for the 90s | https://irc-fish.herokuapp.com/
```

When I click on the herokuapp.com link it tells me "Date doesn't have data logged." Regardless of how many days back I explore by clicking the "Previous day" link. This is another, albeit weak, reason to drop raw IRC in preference to something like gitter.im. Could you, or someone, at least fix the link in the IRC topic so it does something useful or drop the link if it can't be made to do something useful?

**Comment by pickfire** [comment]
Yeah, shouldn't it be `fish.sh`?

**Comment by zanchey** [comment]
I think @xfix set that up, but I've dropped the link for now.
