### ISSUE TITLE
Modifiers à la zsh

### ISSUE THREAD

**Issue by rogorido** [fish-shell/fish-shell#2680]
Hi, many thanks for developing fish. It's very impressive.

I was just wandering if there are any plans to implement the so-called "glob qualifiers" of zsh. (http://linux.die.net/man/1/zshexpn). For instance:

ls *(.x)

shows only executable files.

**Comment by ridiculousfish** [comment]
Ohwow. Of course this has to be configurable: set either BARE_GLOB_QUAL or EXTENDED_GLOB, hang on tight, and don't look directly into the sun!

No plans yet but this seems useful. What would you like the syntax to be? Baking this into the syntax (using parenthesis) seems kind of terrible, but this might make sense as an option to a new `glob` command?

**Comment by rogorido** [comment]
Thnaks for your answer. I don't know which syntax is the best one for fish. I see fish already uses parenthesis for commands (instead of backsticks)...

**Comment by krader1961** [comment]
The only zsh glob qualifier I really miss is `**(.)` as shorthand for `(find . -type f)`. Rather than introducing new syntax we're probably better served by a new function (or possibly builtin) name __glob__ or __filter__ or something similar as proposed in issue #2661.

**Comment by rogorido** [comment]
Well I also miss `ls *(.m-1)` to see for instance the files modified in the last 24h.

**Comment by krader1961** [comment]
Sorry, but I think `ls *(.m-1)` definitely is a step too far. A strong case can be made for supporting a couple of really common use cases such as listing just files or directories (e.g., `grep xyz **(.)`). If you need more flexibility than that use the __find__ command. We definitely should not do what zsh has done and reimplement the __find__ command as a horrible, confusing, set of glob qualifiers.

**Comment by rogorido** [comment]
Well, I was just asking if this will be implemented in the future. I dont think `(.m-1)` is horrible and confusing. It's pretty clear what it's meant with it. But I understand that fish has not to become a new zsh.

**Comment by faho** [comment]
@ridiculousfish: I'm not actually sold on the idea of a `glob` builtin, I'd prefer to make it easier to use `find` (especially in a way that has no caveats like newlines-in-filenames). I believe with nice splitting it should cover all bases in a way that is more readable _and_ more powerful than glob qualifiers/modifiers and familiar to users of all shells. I also don't see a pronounced need for speed in this so I don't think the forks would matter. Should we discuss this or is your mind made up?

**Comment by krader1961** [comment]
Upon further reflection I'm inclined to agree with @faho. If I have to type something like `grep (glob --files **)` I might as well use the __find__ command. I think that trying to accommodate use cases like the examples provided by @rogorido will quickly cause fish to suffer from the problems that afflict zsh. Once you implement support for `*(.x)` (regular files with one of the execute bits set) or `*(.m-1)` (regular files modified in the past day) there will be an endless stream of people asking for yet another way to qualify the glob.

There is only one use case common enough to warrant a shorthand notation in fish: enumerating all the regular files in or below the PWD. That's what the zsh `**/*(.)` notation gives you. If people agree that use case warrants special notation we can then discuss what that would look like.

**Comment by oranja** [comment]
@faho Big question is: how do you imagine making `find` easier to use? Without adding too much mystery to the command line and without having to type the same as you would with `find`?

@krader1961 It sounds reasonable enough to provide a special notation for "all regular files in or below PWD", but as someone who doesn't come from `zsh` I find this specific notation unintuitive. I'd much rather use something along the lines of `**/*//f`. It makes me comfortable to think of it as kind of a mix between the `/pattern/flags` format in regular expressions and `find`'s `-type`. This expands nicely to `**/*//d` for ...... directories (and if you guessed it right that's a good sign). It does have its problems still, but I couldn't think of a better trade-off.
More powerful than this, you should probably call an expert (`find`).

**Comment by Kerosene2000** [comment]
I think they will parse this for example `**/*(.)` (no parentheses for fish) and call fish with the apprpriate parameters...

**Comment by krader1961** [comment]
> I find this (zsh) specific notation unintuitive.

First thing to note is zsh uses `**/*` where fish uses `**`. Zsh then allows you to append qualifiers to the glob pattern wrapped by parenthesis. The qualifiers can be combined and while some of them are intuitive (e.g., `**/*(x)` to select files and directories with the execute bit set) others are not, e.g., using a period to mean plain files or asterisk to mean executable plain files. And, as @ridiculousfish noted, whether or not you can even use a glob qualifier and the syntax for it depend on the value of two run-time options. As I said earlier we definitely do not want to emulate zsh in the regard.

I like your proposal, @oranja, to use something like a double slash to introduce the glob qualifier. So in fish terms this, `**//f`, would select all plain files in or below the PWD and this, `**//d`, would select all directories. The problem with that syntax is it's not backward compatible since today something like `**//f` will match every file named `f` below the PWD (but not in the PWD which is odd and seems wrong). Ideally any new syntactic sugar would be guaranteed not to alter existing behavior.

**Comment by oranja** [comment]
My original thought was `**/*|d`, but that would be a mess for the parser to distinguish from pipes, I guess.
I really hope we can come up with something backwards-compatible, but the common *nix filesystems are pretty lax when it comes to naming things, aren't they? I can't think of a character that will not be in someone's file name and doesn't have some other special meaning in Fish. For this reason I'm always going back in my mind to my happy place, where people use `find` when they need to match based on something more than a simple glob pattern. But... if people want it and realize that it comes with a certain small price, so be it.

:+1: The fact that `**/pattern` won't match files in the current folder is a bit baffling to me too.

**Comment by JoshCheek** [comment]
I'd really prefer this not be added to fish syntax. I'm with the others that it seems like it should just be a function/program. Eg I have a `ff` program to "find files", which makes my most common use cases very easy. If I wound up needing this with any frequency, I'd just add an extra flag `+x` and `-x` to handle it.

**Comment by krader1961** [comment]
You make a good point, @JoshCheek. I, @rogorido, and many others who have asked for special syntax to modify what `*` and `**` return are perhaps letting our past experience with other shells unduly influence our view of how fish should work. Your reference to a `ff` command made me realize that we can solve what I view as the only compelling use case with something like this:

```fish
function ff --description 'Like ** but only returns plain files.'
    find . -type f | sed -e 's/^\.\///'
end
```

Which can be used in my canonical example thusly: `grep pattern (ff)`. That isn't any more difficult to type than something like `grep pattern **//f`. And, of course, anyone who wants something a bit simpler than the __find__ command is free to write a globbing function with whatever syntax they want that implements their desired semantics.

I think we need to allow a few more days of commenting on this issue but I'm now leaning towards doing nothing more than perhaps adding the aforementioned __ff__ function as an example where the `**` syntax is discussed in the documentation.

**Comment by rogorido** [comment]
@krader1961, @JoshCheek: yes, that could be a good idea. Thanks.

**Comment by krader1961** [comment]
If file/directory names contain newlines do we care? I vote no. But I ask because using command substitution splits on newlines whereas special syntax like `**//f` would presumably not split on newlines. In other words we would be extending the existing semantics that a newline character (\n) is roughly analogous to a null (\0) character.

**Comment by krader1961** [comment]
> The fact that **/pattern won't match files in the current folder is a bit baffling to me too.

It turns out this is by design, @oranja. In fish you simply omit the slash; e.g., `echo ***.fish` in fish is the same as `echo **/*.fish` in zsh. I mention that in the change I just committed to clarify the behavior.
