### ISSUE TITLE
fish_vi_mode setting the modal indicator `[N]` and `[I]`

### ISSUE THREAD

**Issue by alexge233** [fish-shell/fish-shell#2682]
I really love fish, and I use it with [powerline-shell](https://github.com/milkbikis/powerline-shell) and *tmux* both remotely and locally.

Recently I discovered that fish supports *vi mode*, which I would like to use,
but I want to format or change the background and colour (if not the characters themselves) `[N]` and `[I]` characters appearing at the begging of the line.

This is related to `fish_vi_mode` only, and not the overall fish prompt which I configure from *powerline-shell*.
I found from #1403 that I may have to set:

```
fish_cursor_default
fish_cursor_insert
fish_cursor_visual
```

How could I go about this?
For example, I'd like to replace the `[N]` with some Unicode icon, and set the background colour myself.
Or how do I set the visual selection colour?

**Comment by zanchey** [comment]
Those cursor variables control the cursor shape, rather than the indicator.

In vi mode, a new prompt becomes active: `fish_mode_prompt`. You can remove this prompt with:

```
function fish_mode_prompt; end
```

and then add the functionality to your normal prompt by switching on `$fish_bind_mode`.

The current default behaviour of `fish_mode_prompt` is:

```fish
function fish_mode_prompt --description 'Displays the current mode'
    # Do nothing if not in vi mode
    if set -q __fish_vi_mode
        switch $fish_bind_mode
            case default
                set_color --bold --background red white
                echo '[N]'
            case insert
                set_color --bold --background green white
                echo '[I]'
            case visual
                set_color --bold --background magenta white
                echo '[V]'
        end
        set_color normal
        echo -n ' '
    end
end
```

**Comment by alexge233** [comment]
@zanchey Many thanks for the help!
Unfortunatelly this doesn't solve my problem:
*powerline-shell* sets its own prompt, and *fish_vi_mode* sets up the prompt before.
You can see in the attached screenshot what I mean by that.

My question is this:
Can I somehow from `fish_vi_mode` `export` the `mode` it currently is in, as a variable which, python / `powerline-shell` can use?

AFAIK 

![fish_vim_mode](https://cloud.githubusercontent.com/assets/6159747/12380681/9a44e972-bd70-11e5-910a-2e5d23fcc213.png)

**Comment by zanchey** [comment]
Yes - the current mode is set as `fish_bind_mode`, although it's not exported. You can erase the `fish_mode_prompt` as described.

**Comment by alexge233** [comment]
Thanks zanchey, this appears to be more of an issue integrating `powerline-shell` to fish, than the other way around.
