### ISSUE TITLE
building on Mac OS X

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2685]
When using `xcodebuild` to build fish on Mac OS X I see this doxygen warning: “Lexicon filter is not available”. @ridiculousfish pointed out that I need to run `make lexicon_filter`. Sure enough, running

```
autoconf
./configure
make lexicon_filter
xcodebuild
```

cause that specific warning to disappear. However it's replaced by multiple occurrences of these warnings:

```
sed: 1120: /Users/krader/projects/3rd-party/fish-shell/lexicon_filter: unused label 'entities'
sed: 1120: /Users/krader/projects/3rd-party/fish-shell/lexicon_filter: unused label 'commands'
```

The first question is can the xcodebuild config be modified to automatically run the prerequisite commands or do the docs on how to build fish on OS X need to be augmented?

The second question is how to eliminate the sed warnings?

I'm also seeing the following messages with and without having run `make lexicon_filter`. It's likely that one or more document files need to have those backslash sequences escaped.

```
/private/var/folders/1j/hh_xsz117m9c5t46yxdz7x8c0000gp/T/fish_doc_build_uWD8wN/printf.doxygen:68: warning: Found unknown command `\t'
/private/var/folders/1j/hh_xsz117m9c5t46yxdz7x8c0000gp/T/fish_doc_build_uWD8wN/string.doxygen:93: warning: Found unknown command `\sglq'
/private/var/folders/1j/hh_xsz117m9c5t46yxdz7x8c0000gp/T/fish_doc_build_uWD8wN/string.doxygen:118: warning: Found unknown command `\x07'
/private/var/folders/1j/hh_xsz117m9c5t46yxdz7x8c0000gp/T/fish_doc_build_uWD8wN/string.doxygen:201: warning: Found unknown command `\s'
/private/var/folders/1j/hh_xsz117m9c5t46yxdz7x8c0000gp/T/fish_doc_build_uWD8wN/string.doxygen:201: warning: Found unknown command `\s'
```

**Comment by krader1961** [comment]
After executing "brew upgrade --all" a few days ago I can no long3er build fish with `xcodebuild`. It fails with

```
Ld build/Release/fish normal x86_64
    cd /Users/krader/projects/3rd-party/fish-shell
    export MACOSX_DEPLOYMENT_TARGET=10.6
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -L/Users/krader/projects/3rd-party/fish-shell/build/Release -F/Users/krader/projects/3rd-party/fish-shell/build/Release -filelist /Users/krader/projects/3rd-party/fish-shell/build/fish.build/Release/fish_shell.build/Objects-normal/x86_64/fish.LinkFileList -mmacosx-version-min=10.6 -dead_strip -lncurses -lpcre2 -Xlinker -dependency_info -Xlinker /Users/krader/projects/3rd-party/fish-shell/build/fish.build/Release/fish_shell.build/Objects-normal/x86_64/fish_dependency_info.dat -o /Users/krader/projects/3rd-party/fish-shell/build/Release/fish
ld: library not found for -lpcre2
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Building via `autoconf; ./configure; make` produces a working fish binary with no build warnings or errors. I'm willing to bet the Travis-CI configuration for using Clang to build fish doesn't use the Mac OS X xcodebuild command.

**Comment by ridiculousfish** [comment]
Yikes. I wonder if the release build is broken.

**Comment by krader1961** [comment]
I figured out why _xcodebuild_ was reporting "ld: library not found for -lpcre2". I had run `xcodebuild install` then rebooted my server. That deleted the __/tmp/fish.dst__ directory. However, the __build/Release__ directory still had a symlink for the pcre2 library pointing to the __/tmp/fish.dst__ directory. For some reason `xcodebuild` (without the _install_ arg) blindly assumed the symlink was valid. Ugh! I hate tools that don't provide meaningful error messages; yet alone handle a situation like this in an intelligent fashion.

**Comment by krader1961** [comment]
The current sed based customization of the documentation (as codified in _lexicon_filter.in_) is extremely confusing. It is almost impossible to know when various constructs require an extra backslash. And at least one case, an empty single-quoted string (see issue #2699) doesn't even work when the quote marks are backslash escaped.

**Comment by DomT4** [comment]
> After executing "brew upgrade --all"

Apologies for drifting into your thread here, but the `--all` isn't required any more just so you know :smiley:. We reverted that change after user feedback was consistently against it.
