### ISSUE TITLE
Make fish autocomplete learn from history options and parameters

### ISSUE THREAD

**Issue by Penegal** [fish-shell/fish-shell#2686]
Hello, there.

I'm a fish enthusiast, using Debian Wheezy's 2.2.0, and had an idea about autocomplete. Currently, it proposes possibilities based, among others, on history, but only at the line level: once a single character is different from a past command, the autocomplete no longer proposes it, which is expected, but, then, I can't conveniently use arguments or options from the past command. If, for a custom command, a PHP script for instance, fish could learn this command's parameters from the past occurences, say the occurences with a 0 exit status to prevent learning misspelled options, it could propose them for next executions of this custom command, like integrated options for `grep` or others.

An example:
> $ php script.php 123 --try
> script.php said: OK
> $ php script.php █

At this point, fish could safely propose the `--try` option or the `123` parameter; it doesn't necessarily have to bother with the parameter order the command expects — although enforcing this could be useful, maybe with a fish config switch — but it could at least propose them. This could also be the case in this situation:
> $ php script.php 123 --try
> script.php said: OK
> $ nice -n 10 php script.php █

Hoping this suggestion could be safely implemented — unfortunately, my programming skills aren't enough to allow me to propose a pull request for that.

Regards.

**Comment by krader1961** [comment]
I don't see any practical way to implement this. In your first scenario the interaction with explicit completion rules is problematic. Which suggestions should be displayed? How would they interact? In your second scenario it would be flat out impossible without otherwise making the suggestions completely useless.
