### ISSUE TITLE
Quirky auto-completion with similar folder names and spaces i.e "directory 1" and "directory 2"

### ISSUE THREAD

**Issue by karlek** [fish-shell/fish-shell#2687]
When auto-completing folder names with similar names and contains spaces, fish makes some quirky suggestions. 

```fish
$ mkdir "directory 1" "directory 2"
$ cd dir[TAB][TAB]
# dir[TAB] -> directory\ 
# dir[TAB][TAB] -> directory\ directory
```

Would be much better if fish would enumerate between "directory 1" and "directory 2" upon completion.

```fish
$ cd dir[TAB]
# dir[TAB] -> directory\ 
# dir[TAB][TAB] -> directory\ 1
# dir[TAB][TAB][TAB] -> directory\ 2
```

Once again I apologize for the ridiculous issue names.

**Comment by krader1961** [comment]
I can reproduce this behavior and agree it is wrong.

**Comment by faho** [comment]
This seems to me to be the same thing as #2447.

**Comment by krader1961** [comment]
Yes, I concur and recommend closing this as a dup.

**Comment by faho** [comment]
Okay, dup it is.
