### ISSUE TITLE
Fish very slow to load

### ISSUE THREAD

**Issue by klaplong** [fish-shell/fish-shell#2688]
Hi,

Every time I open a terminal, it takes about 3-4 seconds before Fish loads. Everything else on my computer is rather fast. I have been looking around the internet for solutions, but have found none. Maybe someone here can help me?

Thank you!
Bas

**Comment by ridiculousfish** [comment]
A common reason for this is appending to universal variables in your `~/.config/fish/config.fish`, e.g. #1277. Try running `set -U`. Are there any extremely long lines?

**Comment by klaplong** [comment]
Except for `fish_greeting` and `fish_user_paths` there are no long lines in `set -U`. There are, however, only variables concerning fish. `fish_user_paths` is the only line in my config with `-U`. Should I change this to `-x`?

**Comment by pickfire** [comment]
@klaplong, don't set it with `-x`, it won't be preserved across reboot in this way.

**Comment by klaplong** [comment]
It will, because it gets executed every time I open a terminal.

**Comment by ridiculousfish** [comment]
In general there should be no `set -U` lines in config.fish. #2005 tracks warning for this case.

The reason is that `set -U` calls create variables that persistently remember their values, so running `set -U fish_user_paths $fish_user_paths /opt/bin` on each launch just make $fish_user_paths longer and longer.

You can undo this by just setting it to something, e.g.:

    set -U fish_user_paths ~/bin /opt/bin

Notice we aren't appending, just setting it directly.

If you really want to set this in config.fish, then you may as well set PATH directly:

    set -x PATH ~/bin $PATH

**Comment by klaplong** [comment]
Okay thanks very much. I changed the config and it now loads instantly!

**Comment by ridiculousfish** [comment]
Cool, let's call it a dup of #2005. Thanks for filling this!

**Comment by Rush** [comment]
@ridiculousfish your advice with `set -x` is wrong. It will cause the PATH variable to grow indefinitely with all visited directories.

**Comment by ridiculousfish** [comment]
@Rush sorry, I don't understand - my suggestion with `set -x PATH ~/bin $PATH` just runs at startup, not every time you switch directories.

**Comment by Rush** [comment]
@ridiculousfish my bad, thank you for your help. I was able to fix my slow loading issue by looking at `set -U` as well.

**Comment by skrat** [comment]
So what's the point then of `fish_user_paths` and how should it be used in this common use case where user wants to add their own local paths to it?

**Comment by faho** [comment]
@skrat The point is to just set it once, interactively. There is no reason to set it again and again and again in the config file, because it's already saved.

----

Please, in future, open a new issue instead of replying to random old ones.

**Comment by pickfire** [comment]
@faho How about enabling github discussions for these kind of discussions?

**Comment by ridiculousfish** [comment]
[Gitter](https://gitter.im/fish-shell/fish-shell) is a good option for low-key questions, while opening a new issue is for bug reports or fleshed-out ideas. It looks like GitHub Discussions is for topics that span multiple projects, but fish-shell just has one project so seems overkill.
