### ISSUE TITLE
Fish fails to access programs.sqlite on NixOS

### ISSUE THREAD

**Issue by maximvl** [fish-shell/fish-shell#2691]
Hi! I'm using NixOS (modern distribution becoming more and more popular, https://nixos.org/ ), and I found a problem using `which` command in Fish:
```
> which ps
DBI connect('dbname=/nix/var/nix/profiles/per-user/root/channels/nixos/programs.sqlite','',...) failed: unable to open database file at /run/current-system/sw/bin/command-not-found line 12.
cannot open database `/nix/var/nix/profiles/per-user/root/channels/nixos/programs.sqlite' at /run/current-system/sw/bin/command-not-found line 12.
```
Could you help me to figure out what is this `programs.sqlite` db for? How is Fish looking for it?

**Comment by faho** [comment]
I don't think fish _is_ looking for it - I'm not aware of us using any sqlite anywhere. As far as I can tell, you don't have `which` installed - use `command -s which`. This then triggers the command-not-found script, and it seems nixos's uses an sqlite database and it might have a bug.

How does this look when you try it in another shell (e.g. bash), and what does `/run/current-system/sw/bin/command-not-found which` (which is the exact command run by the fish command-not-found-handler on nixos) do?

**Comment by maximvl** [comment]
@faho ye, you are right, `which` was not installed, it's just bash and zsh have their own builtin `which`. After installing `which` problem is gone, thanks!

**Comment by faho** [comment]
@maximvl: I suggest you contact the nixos folks - that error message in the command-not-found script seems really weird, and I can't see how it's fish-specific.
