### ISSUE TITLE
LD_LIBRARY_PATH bizzare question

### ISSUE THREAD

**Issue by alexge233** [fish-shell/fish-shell#2693]
I am not sure if this is related to fish or not.
I have in my `.config/fish/config.fish`
````
set -x LD_LIBRARY_PATH $LD_LIBRARY_PATH /usr/local/cuda/lib64
````

Yet when I run a cuda app:

```
./convert_cifar_data.bin: error while loading shared libraries: libcudart.so.6.5: cannot open shared object file: No such file or directory
````

I know that `libcudart` is in fact in `/usr/local/cuda/lib64` 

```
locate libcudart
/usr/local/cuda-6.5/lib/libcudart.so
/usr/local/cuda-6.5/lib/libcudart.so.6.5
/usr/local/cuda-6.5/lib/libcudart.so.6.5.14
/usr/local/cuda-6.5/lib/libcudart_static.a
/usr/local/cuda-6.5/lib64/libcudart.so
/usr/local/cuda-6.5/lib64/libcudart.so.6.5
/usr/local/cuda-6.5/lib64/libcudart.so.6.5.14
/usr/local/cuda-6.5/lib64/libcudart_static.a
```

and that `cuda` is a symbolic link to `cuda-6.5`
```
lrwxrwxrwx   1 root staff    19 Jun 22  2015 cuda -> /usr/local/cuda-6.5/
drwxr-sr-x  18 root staff  4096 Jun 22  2015 cuda-6.5/
```

In bash, the same application runs without a problem.
In my `.bashrc ` I have the same export as with fish.
Why is the app not finding `libcudart` when run under fish?

**Comment by faho** [comment]
LD_LIBRARY_PATH is not a list (that's just PATH, CDPATH and MANPATH). You'll need to do is just like in your bashrc, with colons. I.e.:

```fish
set -x LD_LIBRARY_PATH "$LD_LIBRARY_PATH:/usr/local/cuda/lib64"
```

**Comment by alexge233** [comment]
that explains a lot, thank you!

**Comment by faho** [comment]
Note though that this will leave an awkward ":" at the start of your LD_LIBRARY_PATH if it is not defined.

If you are running git fish, you'll want something like

```fish
set -x LD_LIBRARY_PATH (string join ":" -- $LD_LIBRARY_PATH /usr/local/cuda/lib64)
```

if not, it looks a bit uglier:

```fish
set -x LD_LIBRARY_PATH (set -q LD_LIBRARY_PATH; and echo $LD_LIBRARY_PATH:; or echo)/usr/local/cuda/lib64)
```

**Comment by alexge233** [comment]
I clear it and redefine it, so it shouldn't be a problem.
Thanks for the help!

**Comment by faho** [comment]
Since this problem occurs kinda often, I think we might want to add variable listeners for these kinds of variables, something like 

```fish
function check_unlist_vars_for_list --on-variable LD_LIBRARY_PATH --on-variable GOPATH # and more
    set -l var $argv[3]
    if test (count $$var) -gt 1
        echo "$var is not a list like \$PATH, please set to one value with colon separators"
    end
end
```

or, you know, fix it there.
