### ISSUE TITLE
How to call a script from within launcher?

### ISSUE THREAD

**Issue by Alsan** [fish-shell/fish-shell#2694]
How can I call a script, which works fine under terminal, from a launcher (.desktop file)?

Many thanks.

**Comment by faho** [comment]
What's the script? 

Usually, it should work nicely if either

- You put the script into its own file, make the first line `#!/usr/bin/fish` (or applicable - it might be /usr/local/bin/fish), `chmod +x /path/to/file`, and then call that

or

- Make it a function (either in config.fish or autoloaded) and call `fish -c "NAMEOFFUNCTION"`

**Comment by Alsan** [comment]
Thanks @faho, this works.

I've written a script to startup my vm, it works in terminal, and I though that it should be just the same as bash, therefore, my laucher is writing like this: fish -c "/path/to/myscript.fish". This return me the script is not callable. Your second form is the right way for my usage.

**Comment by Alsan** [comment]
This cause me a rethink about the fish. The full path to the script is not provide with the calling from fish -c, that means the fish will re-init the whole environment everytime, am I correct? This seems a big penalty.

**Comment by ridiculousfish** [comment]
`fish -c /path/to/myscript.fish` will invoke fish and tell it to execute the script at that path. If that script does not begin with a shebang, it will not be a valid executable, so you get the "script is not callable" error. If it does begin with a shebang, it will work by executing fish, so you get double-initialization.

Better is simply `fish /path/to/myscript.fish`, with no `-c`. This will only initialize fish once.

This works the same as bash and other shells.

**Comment by Alsan** [comment]
Thanks @ridiculousfish, you clear me out what is going on, but my script is wrapped as a function, therefore it can't be execute with or without shebang. Rewrite the script without wrapping by function seems a better way to go.

**Comment by krader1961** [comment]
FWIW, @Alsan, a "script" is generally understood to be something that is executable in the same manner as a "binary" program. A "script" can be invoked by another program just as if the script were a binary program rather than a textual sequence of commands interpreted by another program like fish (or bash, awk, sed, etc.). Shell functions are not considered to be scripts since they require shell specific means to invoke them.

You are correct that writing your function as a script is better if you want to be able to invoke it from other, non-fish, programs.

**Comment by Alsan** [comment]
Thanks @krader1961 for clear me out the difference between shell script and shell function, and the usage scenario of the both.

**Comment by krader1961** [comment]
@Alsan If you are satisfied with the answers you have received please close the issue. Otherwise please provide more information about your situation.
