### ISSUE TITLE
Fish force quit when use command "cd" to the symbol folder name

### ISSUE THREAD

**Issue by yeungocanh** [fish-shell/fish-shell#2696]
~/D/i/iOS 9 Swift Programming Cookbook ❯❯❯ cd ~Get\ Your\ Files\ Here\ -\ www.appwikia.com/Assertion failed: (! start_point.empty() && start_point.at(0) == L'/'), function descend_unique_hierarchy, file src/highlight.cpp, line 144.

[Process completed]

**Comment by ridiculousfish** [comment]
Good find. Thanks for reporting this!
