### ISSUE TITLE
Set the number of rows/lines for completions

### ISSUE THREAD

**Issue by domoritz** [fish-shell/fish-shell#2698]
I have a large screen and would like to use more than 4 rows for autosuggestions. 

<img width="615" alt="screen shot 2016-01-26 at 20 38 53" src="https://cloud.githubusercontent.com/assets/589034/12604106/fd858250-c46c-11e5-8622-67d2ad8c9ad4.png">

I know tat I can hit tab again to get the complete list.

**Comment by oranja** [comment]
Supporting this customization is an easy change, but I doubt you will see it in fish, because fish tries to keep configuration options to a minimum. Your chances increase if you get more people who think that it should be customizable to comment here.

Since this is free software, you are always free to do whatever you want with your own copy.
The value you are looking for can be defined [here].
You can clone, edit, build and install your own modified fish in a fairly short time.

[here]: https://github.com/fish-shell/fish-shell/blob/b9b39f7c31d2514788f7b3bbacb966ad15578b5e/src/pager.h#L42

**Comment by krader1961** [comment]
I concur with @oranja that this should not be user configurable. This is the type of thing that fish should dynamically configure based on its environment (e.g., the number of rows displayed by the terminal). Assuming enough people feel this should by dynamically sized the question is what should the algorithm be? Should it be scaled linearly to the number of terminal rows; e.g., one autosuggestion line for every six terminal rows? Or should a non-linear equation be used; e.g., 4 autosuggestion lines for terminals up to 30 rows plus one line for every additional four rows up to a maximum of 10 lines? Note that I pulled those numbers out of the air to stimulate discussion and do not mean to imply I think those are good choices.

**Comment by domoritz** [comment]
Thank you @oranja and @krader1961. I think the fundamental problem may be a bit more than just the number of lines that are being shown. The problem is that the suggestions are not that useful but at the same time you want to avoid that the shell input moves too much. 

Also, there are many more options that just a fixed number of lines. The suggestions could just take as much space as is available. Or they could use as much space as they need (up to the whole screen size). This seems to be the default in my zsh setup. However, zsh also shows the most common command rather than a random selection. At least for me, fish shows three columns on a large screen and shows the first 4 rows from three columns that wrap somewhere I can't see it. this means some random commands starting with a, then f, then r.

<img width="1464" alt="screen shot 2016-01-31 at 15 20 20" src="https://cloud.githubusercontent.com/assets/589034/12705906/2c9c1878-c82e-11e5-9b35-faaf3fe1758e.png">

This is very arbitrary and I can't imagine that I find a useful command in that list. Moreover, because the suggestions are in three columns, it is hard to read them. 

Compare to the suggestions from zsh.

<img width="560" alt="screen shot 2016-01-31 at 15 21 56" src="https://cloud.githubusercontent.com/assets/589034/12705915/6644ac0c-c82e-11e5-8e28-d67d46893b2a.png">

Overall, I think I wish fish would show the most useful commands on the first tab and then all commands on the second tab. The most useful suggestions could either be a fixed number, fill the shell (and if there is no space, use n lines but also don't show more than m lines), or always fill the whole screen (move the input to the top. I prefer a fixed number that actually doesn't change with the screen size because what I can read doesn't change with the size.

**Comment by xylix** [comment]
+1 to this.
