### ISSUE TITLE
doc_src/string.txt generates warning when docs are built

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2699]
Building the documentation results in this warning:

```
/private/var/folders/1j/hh_xsz117m9c5t46yxdz7x8c0000gp/T/fish_doc_build_uWD8wN/string.doxygen:93: warning: Found unknown command `\sglq'
```

This is due to an empty single-quoted string in _doc_src/string.txt_:

```
string split '' abc
```

The resulting documentation shown by `man string` replaces the empty string with paired braces:

```
       string split {} abc
         Output:
         a
         b
         c
```

There is something in the __sglq__ substitutions in __lexicon_filter.in__ that is causing this.

**Comment by faho** [comment]
Replacing the single-quotes with double-quptes results in "dblq" being warned about rather than "sglq". Otherwise no change.

**Comment by krader1961** [comment]
> Replacing the single-quotes with double-quotes results in "dblq" being warned about...

Not surprising since the two are identical except for the type of quote character. But, yes, I should have mentioned that anyone fixing __sglq__ also needs to apply the same fix to __dblq__.

**Comment by MarkGriffiths** [comment]
I’ve been meaning to get on and fix these (I wrote the sed based doxygen filter), but have been buried in a startup intensity workload for many months. The lights starting to show at the end of the tunnel and will update the filter to fix the above and any other bugs in the issues queue.
