### ISSUE TITLE
What are some best practices for writing shell scripts using fish?

### ISSUE THREAD

**Issue by da99** [fish-shell/fish-shell#2703]
The [design section of fishshell.com](https://fishshell.com/docs/current/design.html) is one of my favorite parts of the documentatio.  However, are their any guidelines to writing fish shell scripts free from errors? (Other than the debugger, verbosity, and other fish startup options.)

I realize this may fall outside of fish shell, but I'm curious how others write scripts, esp. fish users.  Are there any other practices? Mounting file systems (for testing)? Mocking? Unit tests?

**Comment by ridiculousfish** [comment]
Honestly, shell scripting (including fish) is wonderful for glueing stuff together, but gets ugly quick when you start to push on it. IMO once you reach the point of thinking about mocks, etc., you're probably better off with a more full-featured programming language. That said a list of best practices would be very nice to have.

**Comment by krader1961** [comment]
Outside of $dayjob I would never expend the effort to create unit tests for a shell script. At $dayjob they have an extensive framework for unit testing bash scripts -- and bash scripts are the only ones allowed to run in production. Even then shell scripts are discouraged in favor of doing it in python for anything but the most trivial scripts.

As for best practices I think they're pretty much the same as for writing a bourne, bash, ksh script. First and foremost always check the exit status of an external command unless you know for a fact that a non-zero status can be ignored. In non-fish shells I typically always put `set -e` (or `set --errexit`) at the top of the script then explicitly test the exit status of any command which might return a non-zero status if I don't want that to terminate the script. Fish doesn't yet support the equivalent of `set -e` although it is being discussed in an open issue.

**Comment by da99** [comment]
@krader1961 Just out of curiosity, did they write their own testing framework  or use something external?

**Comment by krader1961** [comment]
> did they write their own testing framework or use something external?

For bash they wrote something from scratch. For python they use unittest2 with a bunch of enhancements (many of which were eventually back-ported into unittest2).

**Comment by bucaran** [comment]
@da99 

If you are a looking for a unit test framework, check out [Fishtape](https://github.com/fisherman/fishtape), it's the only complete solution which is also actively supported. It testes itself and other projects like [fundle](https://github.com/tuvistavie/fundle) and [Fisherman](http://fisherman.sh).

As for best practices, none that I know of. I tried writing something like a code style guide [once](https://github.com/bucaran/wahoo/blob/master/CONTRIBUTING.md#code-style), but I don't agree with some points anymore. I am currently trying to write a more complete manuscript, more like a book, [The Art of Fishing](https://github.com/bucaran/taof), if you have any feedback, specific requests or just want to join the project let me know.

**Comment by pickfire** [comment]
@bucaran Nice, it just sounds like taoup and instead taof. But I think it should be under fish-shell so that more contributors will help in contributing, what do you think?

**Comment by bucaran** [comment]
Yeah, why not. But first, need to get to actually write it. It's very drafty at the moment.

**Comment by krader1961** [comment]
It seems like this thread has run its course.
