### ISSUE TITLE
setenv vs set -x vs export

### ISSUE THREAD

**Issue by aristidesfl** [fish-shell/fish-shell#2704]
Is there a difference between these, and is there a preferred way to set env variables?

**Comment by bucaran** [comment]
The fish way to do this is using the builtin `set`.

```fish
set -x foo
```

In the example above, `foo` is an "environment" variable local to the current scope, so if you run that inside a function it will be local to that function. Instead, if you run that code at the CLI it will be global.

Either way, the variable will be set to any children process created while in the same scope.

```fish
function foo
    set -lx IFS "@"
    bar
end
```

In the example above, we set IFS to `"@"` and make it visible inside `bar` (let's assume `bar` is an external utility like those found in `/local/usr/bin`), but as soon as we exit the function `foo`, `IFS` will not be changed.

I guess `setenv` is how you would accomplish similar feats in other shells.

**Comment by faho** [comment]
There's an additional point:

```fish
> type set
set is a builtin
> type setenv
setenv is a function with definition 
[...]
> type export
export is a functio with definition
[...]
```

We ship functions called `export` and `setenv` for compatibility. These are simple shims that can be used to help you ease in to fish. If you wish to write idiomatic fish code, use `set -x`. (There's also a bit of overhead associated with these functions, but it should be minimal)

**Comment by aristidesfl** [comment]
Thank you for the detailed explanation!
