### ISSUE TITLE
Autocomplete causing weird spacing issues

### ISSUE THREAD

**Issue by ascott23** [fish-shell/fish-shell#2706]
When I type sometimes the autocomplete will cause odd spacing, like there's been text inserted when there hasn't been, see [this gif](https://imgur.com/EDcns5G) for an example of what I mean.
This is on OS X 10.11.2 using iTerm2, latest version of fish, OMF and iTerm2. It seems to happen most when the terminal width is less than half the width of the screen.

**Comment by krader1961** [comment]
I can't reproduce using OS X and iTerm2. However, I'm not using OMF but am using a fish built from github HEAD. Also, while the width of your screen can't possibly be a factor the width, in columns, of the iTerm2 window is likely to be relevant. I tried reproducing with a window as narrow as 30 columns without success.

Things to check:

1) Is TERM=xterm-256 ?

2) Does it still happen if you disable OMF?

3) If you have a custom left or right prompt does it happen if you disable either one or both of them?

**Comment by bucaran** [comment]
@ascott23 @krader1961 I recall seeing this bug when using OS X `Terminal.app`. Like the OP, I use  `iTerm2` now and have never experienced this again.

**Comment by ridiculousfish** [comment]
This happens when fish and the terminal disagree on the width of a character. This is probably due to the funny blue thing at the beginning. Which character is that? What value do you have for "Treat ambiguous-width characters as double width" in iTerm2 settings, under Preferences->Profiles->Text?

**Comment by ascott23** [comment]
@ridiculousfish It's the unicode symbol for benzene, and I've had trouble with unicode in the past with iTerm, so maybe that's the cause. I changed "Treat ambiguous-width characters as double width" to false in the settings and now it's not happening anymore. Thanks!

**Comment by ridiculousfish** [comment]
Eeeexcellent. Also see #1412.

**Comment by rien333** [comment]
I still have this a lot under iTerm2 (Build 3.1.beta.5) with "Treat ambiguous-width characters as double width" disabled. It most likely still has to with weirder unicode characters, as I for example experience the glitch on an autocomplete which suggests an emoji.  (fish version version 2.6.0-150-g4ef14ea6)
