### ISSUE TITLE
Operation with sudo

### ISSUE THREAD

**Issue by rocketraman** [fish-shell/fish-shell#2707]
In bash, if one does:

`sudo echo "foo" | grep foo`

one gets the sudo password prompt before grep finds the foo.

In fish, if one does the same thing, the sudo password prompt is not echoed to the terminal. And input from the keyboard is not sent to sudo.

The man page of sudo has:

-S, --stdin Write the prompt to the standard error and read the password from the standard input instead of using the terminal device.  The password must be followed by a new‐line character.

Not sure if fish can be made compatible with whatever sudo is doing.

**Comment by ridiculousfish** [comment]
This is because `grep` is a function and fish fully buffers function input and output. See #206, #2377. A workaround is `sudo echo "foo" | command grep foo`

Let's close as dup of #206, thanks for reporting this!

**Comment by rocketraman** [comment]
Thank you for the explanation!

**Comment by krader1961** [comment]
I can reproduce this on Mac OS X. If I \cZ then type `fg` the sudo password prompt appears and I can enter the password. But the grep fails to capture the echo output. I also have a grep function and either using the _command_ workaround or entering the full path to the external grep command works as expected. So this does appear to be a dup of #206.
