### ISSUE TITLE
Bright colors (e.g. brred) not working in Ubuntu

### ISSUE THREAD

**Issue by eugenesvk** [fish-shell/fish-shell#2709]
For some reason the bright color variants (e.g. `brred`) for the `set_color` function are not working in either of the terminals (Konsole, Terminator, Guake). Instead I get black.
`set_color -c` lists both `red` and `brred`.
I can output regular and bright versions with the usual echo codes, e.g. `echo -e "\e[31mRed \e[91mLightRed"`, also I can use the `FF5555`, which seems to be the value of `brred` from [color.cpp](https://github.com/fish-shell/fish-shell/blob/6943536ef30e9b6a84a162a2b1f065e0d5feff07/src/color.cpp#L176)
But I can't use `brred` :(

__OS__: Linux ubuntu 4.2.0-27-generic #32-Ubuntu SMP Fri Jan 22 04:49:08 UTC 2016 x86_64 GNU/Linux
__Fish_:  2.2.0-553-g1688b23

**Comment by krader1961** [comment]
Since I was the one to most recently touch that code, introducing the "bright" color variants, I'm curious what is going on in your environment. I synced the most recent fish source to my Ubuntu 14.04 server. That is running an older kernel than the one you reported but that should be irrelevant. I built and installed fish. I then ran the new fish binary and executed

```fish
$ echo (set_color brred)hello(set_color normal)
```

The output was as expected: the word "hello" was in bright red. Sending the output through _od_ shows the expected escape sequences:

```fish
$ echo (set_color brred)hello(set_color normal) | od -tx1z
0000000 1b 5b 39 31 6d 68 65 6c 6c 6f 1b 5b 33 30 6d 1b  >.[91mhello.[30m.<
0000020 28 42 1b 5b 6d 0a                                >(B.[m.<
0000026
```

What is your __$TERM__ set to? Please execute the `echo ... | od` I show above and report the results.

**Comment by eugenesvk** [comment]
@krader1961 thanks for a prompt response!
My __$TERM__ is set to __xterm__
The output of `echo (set_color brred)hello(set_color normal) | od -tx1z` is this:
```
0000000 1b 5b 33 39 6d 68 65 6c 6c 6f 1b 5b 33 30 6d 1b  >.[39mhello.[30m.<
0000020 28 42 1b 5b 6d 0a                                >(B.[m.<
0000026
```
where __39__ is the default foreground color as far as I understand. Rather strange.
Forgot to add that I'm running inside a VMWare virtual machine (not sure if it matters).

**Comment by eugenesvk** [comment]
Btw, also tested it on a **Ubuntu 12LTS** fresh install (also inside a VM), same issue.

**Comment by faho** [comment]
> My $TERM is set to xterm

That'll be your problem. You'll want to set $TERM to something where terminfo tells us it supports more than 8 colors, like "xterm-256color" or "konsole-256color" (since that's what you are actually using). I suggest adjusting your terminal configuration.

**Comment by krader1961** [comment]
On Feb 3, 2016 23:13, "Evgeny" <notifications@github.com> wrote:
>> @krader1961 thanks for a prompt response!
> My $TERM is set to xterm

Try

set -x TERM xterm-256color

The xterm definition normally only supports eight colors (thus no bright
variants). Your system might also have a xterm-16color variant but it would
be pretty odd for your terminal emulator to support that but not
xterm-256color.

**Comment by eugenesvk** [comment]
@krader1961 @faho 
Yes, it worked! Thank you, finally got the same look in my terminal as in OS X.
Just don't remember ever setting this var in OS X, so didn't even know about its existence.
