### ISSUE TITLE
Remap shift-arrow keys to jump 1 word backward/forward

### ISSUE THREAD

**Issue by eugenesvk** [fish-shell/fish-shell#2714]
In OS X, how do I remap `⇧←` and `⇧→` (shift-left/right arrow) to jump 1 word backward/forward instead of displaying  `[1;2D` and `[1;2C`?
I know that in `bash` I can add the following to `~/.inputrc`:
```
"\e[1;2D": backward-word
"\e[1;2C": forward-word
```
It's rather annoying to see those `[1;2D` appear when my muscle memory uses those shift-arrow combos to try to select words in a terminal.
Thanks

**Comment by bucaran** [comment]
@eugenesvk Have you looked at [`bind`](http://fishshell.com/docs/current/commands.html#bind) already?

See an example here: https://github.com/fish-shell/fish-shell/issues/2656

**Comment by eugenesvk** [comment]
@bucaran nope, have not found this command when searching for an alternative to `.inputrc` in `fish`. Will take a look, thanks.

**Comment by bucaran** [comment]
@eugenesvk Type `man bind` and read the docs. The `bind` docs are pretty verbose IMO, but two or three reads and you should be able to figure it out.

**Comment by bucaran** [comment]
@eugenesvk 

By the way, what you are looking for is `fish_user_key_bindings.fish`. Save a file with that name to your `~/.config/fish/functions/` and fish will take care of loading the bindings.

Here is one catch, they are loaded after `config.fish` is loaded, so any bindings you define in `fish_user_key_bindings` you can't override inside `config.fish`.

**Comment by pickfire** [comment]
Some tips:

You could actually use `Alt+f` and `Alt+b` to jump between words.

**Comment by eugenesvk** [comment]
@bucaran Thanks, it works!
Although it only works inside the `fish_user_key_bindings.fish` function. When I use exactly the same `bind` command inside the `config.fish` file nothing happens, the bindings are not set. This is fine by me, using functions is, it seems, the fish way ;), but a strange behavior nonetheless, was a bit puzzled at first why the bindings I was trying to test out in `config.fish` were not working.

**Comment by eugenesvk** [comment]
@pickfire thank you, but that's not convenient for me since I use `Alt+← /→` everywhere else (I understand the benefit of `Alt+f/b` for a heavy console typist, but that's just not me :)).

**Comment by bucaran** [comment]
@eugenesvk From the latest docs:

> Key bindings are not saved between sessions by default. **Bare `bind` statements in <a href="index.html#initialization">config.fish</a> won't have any effect because it is sourced before the default keybindings are setup.** To save custom keybindings, put the `bind` statements into a function called `fish_user_key_bindings`, which will be <a href="tutorial.html#tut_autoload">autoloaded</a>.

That should explain what was happening to you. By the way, in Fisherman you can install more than one plugin that defines key bindings and they will not overwrite each other. On your own, you will need to add and configure your bindings yourself inside `fish_user_key_bindings`, which is not terribly bad, but it's not great either.

**Comment by eugenesvk** [comment]
@bucaran ok, thanks for this clarification and the Fisherman tip. Let's `fish` with functions then!

**Comment by bucaran** [comment]
:fishing_pole_and_fish: !

**Comment by AlexWayfer** [comment]
OK, `bind` with `Shift+Left` works good:

```
$ bind -k \sleft backward-char
```

But what about `Shift+Up`?

```
$ bind -k \sup history-search-backward
bind: No key with name “sup” found
```

**Comment by AlexWayfer** [comment]
OK, made this so:

```
$ bind '[1;2A' history-search-backward
```

But how to simulate `Up` and `Down` keys? Like `history-backward` and `history-forward`, but I see only `history-search-*`, and it has another behavior.

**Comment by AlexWayfer** [comment]
OK, I found powerful using of `bind`:

```
$ bind -k up
bind -k up up-or-search
```

But when I' binding `Shift+Up` like this:

```
$ bind '[1;2A' up-or-search
$ bind '[1;2A'
bind '[1;2A' up-or-search
```

It still has a different behavior than only `Up` (similar to `history-search-backward`).
