### ISSUE TITLE
Fish shell on cmder?

### ISSUE THREAD

**Issue by bitemypikachu** [fish-shell/fish-shell#2717]
I just installed cmder but I can't seem to find a way to get fish shell working on it.

I've tried installing it using cygwin, but on cmder, it still comes up that 'fish' is not a recognized command.

Has anyone successfully got fish shell to run on cygwin? And if so, how did you do it?

**Comment by faho** [comment]
It's possible cmder sets $PATH differently - try running fish with an absolute path (to figure that out, run `which fish` in a terminal where you can run it).

**Comment by faho** [comment]
@bitemypikachu: Did you ever figure this out?

**Comment by krader1961** [comment]
No new information in a month so I'm going to assume the O.P. figured it out.

**Comment by rohitkrishna094** [comment]
was anyone able to figure this out? I am getting the same error that 'fish' is not a recognized command on cmder. I installed cygwin with fish shell selected during installation process. And I have cmder installed too.

**Comment by faho** [comment]
@rohitkrishna094: Can you try what we suggested in this thread and figure out where fish is installed?

If something isn't a known command, then that's because it isn't in a directory given in $PATH. So you need to add it, or execute it with the full path.

**Comment by rohitkrishna094** [comment]
So I installed Cygwin and then installed fish during installation. If I click Cygwin icon on desktop and then type fish command, I am able to get it. But when I open Cmder and then type fish it doesn't work and says that fish command in not on path. 

I am not sure what Cmder or Cygwin or fish shell is. Does anyone know how to fix this?

**Comment by ohk2kt3t4** [comment]
First time using Cmder, but this is what I did:

- Installed ‘cygwin‘, and installed ‘fish‘ using the package manager shown during cygwin install
- Installed Cmder
- Created a new Task in Cmder that runs the command ‘""\path\to\cygwin\...\fish.exe" --login -i"‘

**Comment by fifiteen82726** [comment]
Hi, I was trying to use fish shell through `msys2` and it seems almost works.
I download the msys2 and install the fish. 

In my cmder, I use `C:\msys64\usr\bin\fish.exe --login -i`

However, there are some bugs happend, anyone?

```bash
/etc/fish/msys2.fish (line 46): switch: Expected exactly one argument, got 0

switch $MSYSTEM
       ^
from sourcing file /etc/fish/msys2.fish
        called on line 17 of file /etc/fish/config.fish

from sourcing file /etc/fish/config.fish
        called during startup

      0 [main] cat (13668) C:\Program Files\Git\usr\bin\cat.exe: *** fatal error - cygheap base mismatch detected - 0x180330408/0x180317408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
      0 [main] uname (10352) C:\Program Files\Git\usr\bin\uname.exe: *** fatal error - cygheap base mismatch detected - 0x180330408/0x180317408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
/usr/share/fish/functions/__fish_pwd.fish (line 1): switch: Expected exactly one argument, got 0

switch (uname)
       ^
from sourcing file /usr/share/fish/functions/__fish_pwd.fish
        called on line 2 of file /usr/share/fish/functions/fish_title.fish

in command substitution
        called on line 2 of file /usr/share/fish/functions/fish_title.fish

in command substitution
        called on line 3 of file /usr/share/fish/functions/fish_title.fish

in function “fish_title”
        called on standard input

in command substitution
        called on standard input

/usr/share/fish/functions/fish_title.fish (line 1):
__fish_pwd
^
in command substitution
        called on line 3 of file /usr/share/fish/functions/fish_title.fish

in function “fish_title”
        called on standard input

in command substitution
        called on standard input

Welcome to fish, the friendly interactive shell
fish: Unknown command __fish_pwd
/usr/share/fish/functions/fish_title.fish (line 1):
__fish_pwd
^
in command substitution
        called on line 3 of file /usr/share/fish/functions/fish_title.fish

in function “fish_title”
        called on standard input

in command substitution
        called on standard input
```

**Comment by ridiculousfish** [comment]
@fifiteen82726 looks like [this issue](https://github.com/msys2/MSYS2-packages/issues/1634) from msys2.
