### ISSUE TITLE
allowing the read command to read bytes without regard to the character encoding

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2721]
While working with @jakwings on pull-request #2601 it occurred to me there might be value in enhancing the **read** builtin to allow reading individual bytes without regard to the current character encoding (e.g., from **LC_ALL** or **LANG**). A **--raw** or **--bytes** option would make the fix in that PR simpler. It could be useful in other contexts where we're reading a byte stream that is not valid UTF-8 in a UTF-8 locale. However, if we do this it begs the question of whether we should also have builtin commands for explicitly encoding and decoding UTF-8 (like you would find in Python). At which point we're on the edge of what is an appropriate problem domain for fish to handle. On the other hand UTF-8 is becoming increasingly common and fish should be able to deal with it gracefully.

Also, the problem in pull-request #2601 with **$PWD** not being serializable due to the wide-character after `set -lx LC_ALL=C` would not have existed had fish automatically re-encoded the env vars when the locale changed. Had fish done so the **$PWD** var would have been UTF-8 encoded and thus not contained any wide-characters. Automatically re-encoding vars when the locale changes between UTF-8 and ISO-8859 encodings is the right thing to do. It would allow fish to behave more sanely when started with a non-Unicode locale which changes when *config.fish* sets a Unicode locale (or vice-versa). But the cost in terms of code complexity might be too great to justify.

**Comment by pickfire** [comment]
This seems like a nice feature, I hope that the read command won't break when it is a UTF-8 or other rare encoding so that fish have a better portability.

**Comment by krader1961** [comment]
I've decided this enhancement isn't reasonable. A shell like fish is not meant to be a swiss army knife like C/C++. So I'm going to close it.
