### ISSUE TITLE
Detect that .profile has a fish shebang and warn before loading

### ISSUE THREAD

**Issue by josegonzalez** [fish-shell/fish-shell#2724]
So I'm a pretty stupid user, and have a `.profile` file with a bash shebang. It's all bash, all the time.

Anyhow, I was switching to fish (OS X 10.10 with fish from homebrew) and upon changing the shell to fish and opening up a new one, `fish` basically froze and was unable to do anything. CPU usage spiked to 100% (wooter scooter!) and no errors were output.

Once i moved it out and fish loaded *once*, it was able to properly deal with my `.profile` file being a bash script, shebang and all.

Not sure what the best course of action is here, but at least a warning would be nice :)

**Comment by ridiculousfish** [comment]
fish does not read `~/.profile` so this doesn't make any sense to me.

Which OS are you using? Can you take a sample of fish when its CPU is spiked?

**Comment by josegonzalez** [comment]
OS X 10.10, with fish installed from homebrew.

How do I take a sample? I'll see if I can replicate it, maybe it was a weird fluke of some sort?

**Comment by krader1961** [comment]
I'm running fish on OS X. Originally the homebrew version 2.2.0 and now one built from github head. I've never experienced anything like what you reported. And, as @ridiculousfish, points out fish doesn't read *$HOME/.profile*. When you say

> it was able to properly deal with my .profile file being a bash script, shebang and all.

What is "it"? A fish shell? How did you determine that?

Did you make fish your login shell with the `chsh` command? Or did you put a `/usr/local/bin/fish` line in your *.profile*?

**Comment by krader1961** [comment]
Also, did you put a `source ~/.profile` line in your *~/.config/fish/config.fish* script? If so remove it.

**Comment by josegonzalez** [comment]
I was led to believe that the file *was* loaded in the #fisherman slack channel (I was in the process of setting up fish+fisherman) hence the erroneous issue title. My homebrew was up to date, brew doctor is clean, etc. 

By `it`, I mean fish shell. I determined that by renaming `~/.profile` to `~/.profile-bash` and opening a new fish shell. This was a fresh fish install, with no config for fish at all.

I changed my shell from hombrew bash to homebrew fish by adding `/usr/local/bin/fish` to my `/etc/shells` file and then running the `chsh` command, as mentioned in both homebrew's help and the fisherman docs.

**Comment by krader1961** [comment]
Have you renamed `~/.profile-bash` back to `~/.profile` and verified you can open a new terminal window? I don't think this was a fluke. More likely is you've made some other change in the process of troubleshooting that fixed the problem. Also, I'm not using fisherman so if you're still having problems the first thing I would do is disable it to see if that makes the problem go away.

**Comment by ridiculousfish** [comment]
@josegonzalez If you can get fish to hang again, a good thing to try would be to run fish as `fish -d 5` and then paste the output.

**Comment by bucaran** [comment]
@krader1961 What happened was that a user in the Fisherman slack room commented that

> Canonically, `.profile` is to be sourced by your shell at startup.

Which may have led @josegonzalez to believe that Fish sources bash profile at startup. I knew this could not be so, but I was not sure as I had to verify with `src/fish.cpp` and by the time I had already figured out that it does not do this, @josegonzalez must have tried more than a handful of things troubleshooting this.

@krader1961 
@josegonzalez Can you reproduce the problem everytime you log off and log back in? I would supect that when you start OS X a sh/bash? login shell starts which is the one responsible for starting the desktop environment and would be responsibile for sourcing your profile where the bug could be?

**Comment by josegonzalez** [comment]
I literally created a new tab, which started a brand new shell with fish instead of bash (bash was never loaded afaik).

This was before setting up any extra stuff (like fisherman). I literally did the following:

```
brew install fish
nano /etc/shells
# added /usr/local/bin/fish as the first entry
chsh -s /usr/local/bin/fish
# opened a new tab
```

This was before *any* fish customizations, including (but not limited to):

- Modifying a `~/.config/fish/config.fish` (it didnt exist, still doesn't)
- Install fisherman or any other fish distro (I still havent')

I'll see if I can repro. Again, happy to close, I only opened the issue as I was led to believe that the `~/.profile` file was loaded (which is false).

**Comment by faho** [comment]
Closing this as a fluke.
