### ISSUE TITLE
Less hangs when piping from sort

### ISSUE THREAD

**Issue by Joshkunz** [fish-shell/fish-shell#2725]
This line of code will make less hang for me (instead of displaying the output of `sort`) about every 1/4 times I run it:
```bash
head -n 1000 /dev/urandom | sort -n | less
```
In bash this line works every time.

I think it has something to do with the way fish vs. bash cleanup file-descriptors that participate in pipes, and less is blocking waiting for the descriptor to hit EOF. Also, the `sort` appears to be critical. Without it I cannot reproduce the issue, which makes me think that it's something to do with the way `sort` uses file descriptors.

**Comment by ridiculousfish** [comment]
What is your OS?

**Comment by Joshkunz** [comment]
Debian Jessie
```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"                                             
$ uname -a
Linux iris 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt20-1+deb8u3 (2016-01-17) x86_64 GNU/Linux
```

**Comment by bucaran** [comment]
On OS X

![less](https://cloud.githubusercontent.com/assets/8317250/12965137/5909ce7a-d097-11e5-8683-d082fe0a1d53.gif)

**Comment by krader1961** [comment]
I can't reproduce on OS X or Ubuntu. When it hangs in another terminal capture some diagnostic data. Start with `ps -fu (whoami)`. Then find the **head**, **sort**, and **less** commands. It's possible the first two will no longer be running. For each command that is still running execute `lsof -p pid` where **pid** is the process id of the command you got from the ps output. Then `sudo strace -p pid` (you'll need to interrupt it after it shows the most recent syscall).

**Comment by ridiculousfish** [comment]
I wonder if this is due to locale differences. If it's UTF-8, well, not every byte stream is valid UTF-8 so that may be involved.

What does `locale` show when run in bash and in fish?

**Comment by Joshkunz** [comment]
@krader1961 
### sort
#### lsof
```
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
sort    3933 josh  cwd    DIR   0,38     1488     257 /home/josh
sort    3933 josh  rtd    DIR   0,18      166     256 /
sort    3933 josh  txt    REG   0,18   105832   10678 /usr/bin/sort
sort    3933 josh  mem    REG   0,16            10678 /usr/bin/sort (path dev=0,18)
sort    3933 josh  mem    REG   0,16           196627 /lib/x86_64-linux-gnu/libc-2.19.so (path dev=0,18)
sort    3933 josh  mem    REG   0,16           196623 /lib/x86_64-linux-gnu/libpthread-2.19.so (path dev=0,18)
sort    3933 josh  mem    REG   0,16           196624 /lib/x86_64-linux-gnu/ld-2.19.so (path dev=0,18)
sort    3933 josh  mem    REG   0,16           201826 /usr/lib/locale/locale-archive (path dev=0,18)
sort    3933 josh    0r  FIFO    0,8      0t0 8077182 pipe
sort    3933 josh    1w  FIFO    0,8      0t0 8077183 pipe
sort    3933 josh    2u   CHR  136,2      0t0       5 /dev/pts/2
```
#### strace
```
Process 3933 attached
read(0,
```

### less
#### lsof
```
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
less    3934 josh  cwd    DIR   0,38     1488     257 /home/josh
less    3934 josh  rtd    DIR   0,18      166     256 /
less    3934 josh  txt    REG   0,18   165296   19822 /bin/less
less    3934 josh  mem    REG   0,16           196627 /lib/x86_64-linux-gnu/libc-2.19.so (path dev=0,18)
less    3934 josh  mem    REG   0,16            12770 /lib/x86_64-linux-gnu/libtinfo.so.5.9 (path dev=0,18)
less    3934 josh  mem    REG   0,16           196624 /lib/x86_64-linux-gnu/ld-2.19.so (path dev=0,18)
less    3934 josh  mem    REG   0,16            19822 /bin/less (path dev=0,18)
less    3934 josh  mem    REG   0,16           201826 /usr/lib/locale/locale-archive (path dev=0,18)
less    3934 josh    0r  FIFO    0,8      0t0 8077183 pipe
less    3934 josh    1u   CHR  136,2      0t0       5 /dev/pts/2
less    3934 josh    2u   CHR  136,2      0t0       5 /dev/pts/2
less    3934 josh    3r   CHR    5,0      0t0    6618 /dev/tty
```
#### strace
```
Process 3934 attached
--- stopped by SIGTTOU ---
```
That signal is interesting.

@ridiculousfish 

### fish
```
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
### bash
```
$ locale
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
looks like UTF-8 on both.

**Comment by ridiculousfish** [comment]
`SIGTTOU` says that `less` tried to write to the terminal in the background. That's surprising since it ought to be in the foreground.

**Comment by krader1961** [comment]
The **head** command wasn't present in the **ps** output? Yet **sort** is still reading from the pipe that connects the two processes? That seems, odd, to say the least. I'd be curious what `lsof -a | grep 8077182` shows (substitute the node number from the lsof output for sorts fd0). Does it return just the sort process or additional processes?

If the SIGTTOU is because you backgrounded the pipeline so you could run the other commands I should have mentioned that I wanted you to run the diagnostic commands in a different shell.

**Comment by ridiculousfish** [comment]
`sort` has to suck up all data before it can output anything, so it's not too surprising that `sort` would outlive `head`.

**Comment by Joshkunz** [comment]
@krader1961 
`lsof | grep 8077182` returns just the sort process:
```
$ lsof | grep 8077182
head       3932                josh    1w     FIFO                0,8       0t0    8077182 pipe
sort       3933                josh    0r     FIFO                0,8       0t0    8077182 pipe
```

I did run `lsof` and `strace` in a new shell, and I didn't background the processes first.

`head` is still alive. I didn't notice you wanted the `lsof` and `strace` output from it as well. Here it is (from the same command as before, it's still hung):
### head
#### lsof
```
COMMAND  PID USER   FD   TYPE DEVICE SIZE/OFF    NODE NAME
head    3932 josh  cwd    DIR   0,38     1488     257 /home/josh
head    3932 josh  rtd    DIR   0,18      166     256 /
head    3932 josh  txt    REG   0,18    39496   10637 /usr/bin/head
head    3932 josh  mem    REG   0,16            10637 /usr/bin/head (path dev=0,18)
head    3932 josh  mem    REG   0,16           196627 /lib/x86_64-linux-gnu/libc-2.19.so (path dev=0,18)
head    3932 josh  mem    REG   0,16           196624 /lib/x86_64-linux-gnu/ld-2.19.so (path dev=0,18)
head    3932 josh  mem    REG   0,16           201826 /usr/lib/locale/locale-archive (path dev=0,18)
head    3932 josh    0u   CHR  136,2      0t0       5 /dev/pts/2
head    3932 josh    1w  FIFO    0,8      0t0 8077182 pipe
head    3932 josh    2u   CHR  136,2      0t0       5 /dev/pts/2
```
#### strace
```
Process 3932 attached
read(0, 
```

**Comment by krader1961** [comment]
> lsof | grep 8077182 returns just the sort process:

Look again. I see the **head** command writing data into the pipe that sort is blocked reading from. Which I see you realized as you included the lsof and strace for it :-)

If you look you'll see the head command is blocked reading from fd0. What doesn't make any sense if fd0 is open on your terminals tty. What does `type -a head` report? I'm wondering if you've got a fish function named head or some non-standard implementation.

**Comment by Joshkunz** [comment]
> Look again. I see the head command writing data into the pipe that sort is blocked reading from.
> Which I see you realized as you included the lsof and strace for it :-)

Yeah, there are two lines in the `lsof` ouput: `head` and `sort`, but there's only one program other than `sort`. The output in the comment above is verbatim.

> What does type -a head report?

It's definitely a binary:
```
$ type -a head
head is /usr/bin/head
$ head -c 4 /usr/bin/head
ELF
$ sha1sum /usr/bin/head
88ccf30079fbb8cff4c230cea478fcc259260748  /usr/bin/head
```

**Comment by krader1961** [comment]
Okay, so we've determined the reason for the hang: the **head** command is reading from your tty (so is **less**). The mystery is why **head** is doing that. The next is to trace the entire execution of **head**:

```
strace -o /tmp/strace.head /usr/bin/head -n 1000 /dev/urandom | sort -n | less
```

Then, when it hangs, kill the **head** command (careful not to kill the strace). That should "unhang" things and give us a complete execution trace of **head**.

**Comment by Joshkunz** [comment]
@krader1961 I tried doing that, and `head` terminated properly every time, but it still hung. While I was looking at the `ps` output I noticed that less is actually an alias (`alias less "less -R"` in my config):
```
$ type -a less
less is a function with definition
function less
	command less -R $argv;
end
less is /usr/bin/less
less is /bin/less
```
(`cmp /usr/bin/less /bin/less` shows they're the same by the way).
When I invoke less directly:
```
head -n 1000 /dev/urandom | sort -n | /usr/bin/less
```
I cannot reproduce the issue.

**Comment by krader1961** [comment]
Sigh. This looks like another manifestation of issue #206 (and #2707 and #2377 and probably others). Instead of that alias do `set -x LESS `-R'`. Obviously if you're already exporting that var simply amend the export to include the **-R** switch.

@ridiculousfish: We really need to make it a priority to fix that issue.

**Comment by Joshkunz** [comment]
@krader1961 Excellent, that had been bothering me for a while. I'll close this issue as a duplicate. Thanks to everyone for the help.
