### ISSUE TITLE
Can fish be used with nvm (node version manager)?

### ISSUE THREAD

**Issue by irae** [fish-shell/fish-shell#273]
I am trying to use fish with nvm, but nvm.sh didn't work. I went to look into it and discovered that nvm is a set of user defined functions:

https://github.com/creationix/nvm/blob/master/nvm.sh

Is it possible to run this kind of script inside fish?

**Comment by bucaran** [comment]
@irae Are you still using bash? A lot of fish users have asked for this, so I wrote a pure fish, [node version manager in fish](https://github.com/fisherman/fin).
