### ISSUE TITLE
Tab Completion is broken for directories with parentheses in them

### ISSUE THREAD

**Issue by chriseidhof** [fish-shell/fish-shell#2735]
This happens on OS X. Steps to reproduce:

1. Create a directory: `mkdir "My (Test)"`
1. type `cd My` and press Tab to autocomplete

I get the following error:

```
Unexpected end of string, parenthesis do not match
- (line 1): begin; printf "%s\n" My (T*/ 
 ;end <&3 3<&-
                                    ^
from sourcing file -
	called on line 60 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/eval.fish

in function 'eval'
	called on line 45 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/__fish_complete_cd.fish

in function '__fish_complete_cd'
	called on standard input

in command substitution
	called on standard input

source: Error while reading file '-'
```

**Comment by ridiculousfish** [comment]
Thanks for reporting this

**Comment by chriseidhof** [comment]
I actually wouldn't mind trying to solve it, but have no idea what's wrong. I don't even know how to debug this. I tried "echo $ctoken" to print the variable's contents to the stdout, but that didn't seem to print anything.

**Comment by faho** [comment]
@chriseidhof: I'm quite certain this is the same thing as #952 (though the title is unintuitive since it assumed it was in the c++ code) which we fixed in 0a99772572ab8632f103f05570da707683980d17 (and the following fixup). Can you try that?

**Comment by faho** [comment]
Further reading assures me it's 952. Thanks, already fixed!

**Comment by chriseidhof** [comment]
Yes, I just built and installed from master, and my issue has been solved. Thanks a lot!
