### ISSUE TITLE
git commands with a revision identifier using caret are parsed inconsistently

### ISSUE THREAD

**Issue by rocketraman** [fish-shell/fish-shell#2737]
Running commands with the caret character (git mechanism for identifying a revision) results in a fish error:

```
# git log 1608450^
Expected a string, but instead found end of the statement
fish: git log 1608450^
```

Now I recognize that the caret character is a redirect for stderr (and quoting the revision works fine), but other commands using the same character work correctly, seemingly if they do not start with a number e.g.:

```
git log c9ba59f^
```

works fine. So I don't know which is the correct behavior, but I suppose fish should at least be consistent.

**Comment by krader1961** [comment]
It's almost certainly because the number is being treated as a file-descriptor value; as in the construct `2>&1`. Which is weird and probably broken since `^` is just shorthand for `2>` and thus a numeric fd prefix makes no sense.

**Comment by ridiculousfish** [comment]
Yep, that's right

**Comment by faho** [comment]
This is basically the same as #1873, so let's track there.
