### ISSUE TITLE
Killring and clipboard content

### ISSUE THREAD

**Issue by occivink** [fish-shell/fish-shell#2740]
Hi,
It seems like the input functions that put data in the killring also overwrite the content of the X11 clipboard. Since I'm not especially interested in the killring feature, is there a way to disable that behaviour?

**Comment by ridiculousfish** [comment]
Setting the `FISH_CLIPBOARD_CMD` variable to something like `cat > /dev/null` ought to do it. Does that work for you?

**Comment by occivink** [comment]
It does, thank you.
