### ISSUE TITLE
fish_color_autosuggestion is not documented

### ISSUE THREAD

**Issue by rmccue** [fish-shell/fish-shell#2741]
The autosuggestion colour var isn't documented under the [list of colours](http://fishshell.com/docs/current/index.html#variables-color).

**Comment by faho** [comment]
Yes, it was missing. Thanks!

**Comment by rmccue** [comment]
Looks like it's missing from ["Other features > Syntax highlighting"](http://fishshell.com/docs/current/index.html#other) too.

Thanks for fixing the issue so quickly :)

**Comment by faho** [comment]
@rmccue: See 585c03db72fad2fe790937890dc0a82b4354baf6 - I've removed the duplication, instead referring to the dedicated section.

**Comment by rmccue** [comment]
Thank you! Loving fish too. :heart:
