### ISSUE TITLE
`replacement string too large` with pcre2 10.21

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#2743]
I've had a few test failures and tracked them down to the fact that I'm building against my system's pcre2 in version 10.21. Downgrading to 10.20 or building against the vendored pcre2 makes it work.

In particular, `string replace -r -a '(\w)' '$1$1' ab` fails with "replacement string too large" instead of printing "aabb". Removing the "-a" makes it work (printing "aab") which leads me to believe there's some kind of recursion at play.

I'm willing to bet that most (all?) linux distributions will want to build against system pcre2, so this would be a rather large issue.

**Comment by zanchey** [comment]
Perhaps @msteed can throw some light on the issue. There are quite a few suggestive changes in the [PCRE2 changelog](http://pcre.org/changelog.txt).

**Comment by floam** [comment]
FWIW, I built fish `without-included-pcre2`, compiled and linked against 10.21 on OS X. I can't reproduce that behavior.

**Comment by floam** [comment]
I used homebrew, and just pointed it at the 10.21 tarball instead of 10.20. It reported this ./configure line:
`./configure --prefix=/usr/local/Cellar/pcre2/10.21 --enable-pcre2-16 --enable-pcre2-32 --enable-pcre2grep-libz --enable-pcre2grep-libbz2 --enable-jit`

**Comment by faho** [comment]
The only one different there is readline, which seems very unlikely to change anything. Are you sure you've built correctly against that one (`ldd (type -p fish)`)?

Or it's not pcre2 but the compiler (gcc 5.3.0) or glibc (2.22).

**Comment by msteed** [comment]
I can reproduce the failure on Arch (fish 2.2.0-587-gbc9e3c7 and pcre2 10.21-1).

At first glance I don't have any particular insight into this except that something must be going very wrong in `pcre2_substitute()`. With @faho's test case, fish will start with a 16-wchar buffer to hold the output. If that fails with `PCRE2_ERROR_NOMEMORY`, fish will retry with successively larger buffers up to 1M wchars, and then finally fail with the `Replacement string too large` error.

I may be able to spend some time on this today or tomorrow, but I won't be sad if someone else figures it out first. : )

**Comment by floam** [comment]
No `ldd` on OS X, but yeah that's the new pcre2 in `/usr/local/opt`. 

```
~/s/fish-shell ❯❯❯ otool -L (type -p fish)                                                                                               
/usr/local/bin/fish:
	/usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	/usr/local/opt/pcre2/lib/libpcre2-32.0.dylib (compatibility version 4.0.0, current version 4.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

**Comment by floam** [comment]
Not sure what changed but I'm getting the exact same thing on OS X too now. No idea if it's my environment... probably just losing my marbles.

**Comment by msteed** [comment]
I see what's going on. I will submit a PR shortly.
