### ISSUE TITLE
fish doesn't recognize url as parameter of youtube dl

### ISSUE THREAD

**Issue by JosephEdselBonilla** [fish-shell/fish-shell#2750]
http://imgur.com/zxgFpHO

**Comment by faho** [comment]
This is a duplicate of #967.

The issue is that "?" is a single-character glob, so fish tries to match files in the local directory. The workaround is to quote the parameter - I always do `youtube-dl "` then press Ctrl-v, enter the second quote and then execute it.

**Comment by pickfire** [comment]
@JosephEdselBonilla remember to quote things that have `?` with either `'` or `"`.

**Comment by Librebowski** [comment]
Put the url in " "s like the other guys said. works great.
