### ISSUE TITLE
dnf auto-completion like yum auto-completion

### ISSUE THREAD

**Issue by nielsk** [fish-shell/fish-shell#2758]
There is an auto-completion for yum that can auto-complete package names when for example installing new packages.
yum is deprecated in Fedora23 and Fedora is switching to dnf. There is no auto-completion yet for dnf in fish.

**Comment by exploide** [comment]
I guess dnf autocompletion is already merged: #2638

But since there is no fish release since July 2015, a lot of new commits are not present in the version of fish which ship with our distributions.

**Comment by nielsk** [comment]
Thanks. But [#2638](https://github.com/fish-shell/fish-shell/pull/2638) adds with the assumption that yum and dnf do the same not all functions of dnf. But at least I get now package-completions.
I will see if I can find the time to read up on how to add the missing stuff.

**Comment by exploide** [comment]
That would be nice. I also noticed that this assumption might not hold true.

**Comment by pickfire** [comment]
It will be there soon, just 26 more issues for the next 2.x release.

**Comment by faho** [comment]
The good news is everything listed in http://dnf.readthedocs.org/en/latest/cli_vs_yum.html as dropped isn't in the completions in the first place, and I don't believe any of the other things apply.

That means I'll close this - if any of you notice anything that should be added, tell me or add it yourself and submit a PR.

**Comment by nielsk** [comment]
@faho The thing is that then either yum-completion is very incomplete or that document doesn't list a lot of new things

**Comment by faho** [comment]
@nielsk: Anything you're missing?

**Comment by nielsk** [comment]
@faho yes. The copr-commands are completely missing (I wrote about that on the mailing list), provides is missing (but it inherits "whatprovides" from yum which can be used instead but that might go in the future I guess), makecache is missing, history is also missing. And I did not have yet looked into the options.

**Comment by nielsk** [comment]
And when I open up zsh and start using its auto-completion for dnf it shows even more commands
