### ISSUE TITLE
fish_history is not valid YAML: use a YAML library or pick a more practical format.

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#2759]
I've been playing around with my large fish_history file in PyYAML to prototype some things and also see if I could figure out why it seems like there's  very little actual history for the completions to use.

Unfortunately fish isn't producing kosher YAML output and the actual parsers I've tried can't even load it - it's using reserved characters at the beginning of unquoted scalars (strings), for one:

```
/usr/local/lib/python3.5/site-packages/yaml/scanner.py in fetch_more_tokens(self)
    255         raise ScannerError("while scanning for the next token", None,
    256                 "found character %r that cannot start any token" % ch,
--> 257                 self.get_mark())
    258 
    259     # Simple keys treatment.

ScannerError: while scanning for the next token
found character '`' that cannot start any token
  in "<unicode string>", line 107, column 8:
    - cmd: `ls`
           ^
```

After correcting a handful of those (by enclosing them in single quotes), this looks like a mapping to it, those aren't allowed here:

```
- cmd: codesign -sf "Mac Developer: Aaron Gyes (P2ZV5TB538)"  .
  when: 1446131523
  paths:
```

and doesn't like this:

```
- cmd: [s aux |tail
  when: 1434196388
```

and this:

```
ParserError: while parsing a block node
expected the node content, but found ','
  in "<unicode string>", line 4389, column 8:
    - cmd: ,/sol
```

this means it's a tag:

```
ConstructorError: could not determine a constructor for the tag '!telnet'
  in "<unicode string>", line 381, column 8:
    - cmd: !telnet
```

I also found a region of my history apparently laid to waste when I was upgrading last summer: 

```
- cmd: brew unlink fish
  when: 0
- cmd: brew install --force --HEAD fish
  when: 0
- cmd:   when: 1433940652
  when: 0
- cmd:   when: 1433940656
  when: 0
- cmd:     - P-18355603z.pdf
  when: 0
- cmd:   when: 1433940657
  when: 0
- cmd:   when: 1433940658
  when: 0
- cmd: fish config
  when: 0
- cmd:   when: 1433940743
  when: 0
- cmd: fish_config 
  when: 0
- cmd:   when: 1433940746
  when: 0
- cmd:   when: 1433940842
  when: 0
- cmd:   when: 1433940856
  when: 0
- cmd:   when: 1433941642
  when: 0
- cmd:   when: 1433941644
  when: 0
- cmd:   when: 1433941664
  when: 0
- cmd:   when: 1433941984
  when: 0
- cmd:   when: 1433941987
  when: 0
- cmd:   when: 1433941996
  when: 0
- cmd:   when: 1433942012
  when: 0
- cmd:     - .config/fish/config.fish
  when: 0
- cmd:   when: 1433942052
  when: 0
- cmd:     - .config/fish/
  when: 0
- cmd:   when: 1433942055
  when: 0
- cmd:   when: 1433942056
  when: 0
- cmd:   when: 1433942060
  when: 0
- cmd:     - profile
  when: 0
- cmd:   when: 1433942099
  when: 0
- cmd:   paths:
  when: 0
- cmd:     - .
  when: 0
```

SO!

Part of the reason I was messing with this was because I've noticed for a long time that my history seems pretty short, I imagine history.cpp has been choking on parts for a while now. It would be nice if other tools could at least count on successfully parsing the document as a YAML document... I might suggest validating it in fish and simply deleting old entries that are no good. 

Moving forward it would be good if these were property single quote escaped (only when necessary)... if that means old versions of fish have no hope of reading it though, perhaps it'd be wiser to switch to block literals. Then you don't need to worry about escaping the newlines or anything. Perhaps you cuold try to kind of migrate in place? Could put a whole second document in the same file/stream after `---`. 

It would be great if it could use an actual C++ YAML parser.  This kind of feels like a rigid binary format in disguise right now.

**Comment by ridiculousfish** [comment]
The "cmd:   when: 1433942012" nonsense occurs when fish 1.x reads a fish 2.x history file. We actually have a little support for cleaning that up.

Making this actual YAML sounds like a worthy goal. This would be a breaking change so we would need to add a version marker to the history (e.g. in a file comment).

**Comment by floam** [comment]
Using folded block scalars seems like a pleasant way to go without having to escape the newlines.

```yaml
  - cmd: >
       function fishies; # check number of fish in pond
            count (ps | string match "*-fish*");
        end;
    when: 1193291223
    paths: 
        - "/lost+found/Filename: "
```
The `>` will result in block folding; Newlines before before and after the content will first be trimmed and then in the middle  whitespace in the middle will be treated in this fashion(left and right are equivalent):

<img width="502" alt="screenshot 2016-03-05 at 4 40 59 am" src="https://cloud.githubusercontent.com/assets/291142/13547558/ccea2b6c-e28c-11e5-8691-b9aefe5a4ed8.png">

It seems to match how fish works very much. If I am missing some obvious side effect it's also possible to just use the literal `|` (preserves all whitespace) or escape them.

There would have to be escaping lots of things, however at least they define what and [http://www.yaml.org/spec/1.2/spec.html#id2776092](how). The plain style explicitly has no such thing as escapes. 

The single flat map is very very long, probably some people may want to just follow the history backwards a little bit and not load up/parse such a beast just to grab off a bite. Fish appends as it goes line by line also - I had thought this was a problem and would make using a real library without serializing the entire thing difficult, but this is actually [a feature of YAML](http://www.yaml.org/spec/1.2/spec.html#id2779048) that I didn't know about:

> YAML uses three dashes (“---”) to separate directives from document content. This also serves to signal  
> the start of a document if no directives are present. **Three dots ( “...”) indicate the end of a document without starting a new one, for use in communication channels.**

```yaml
---
  - cmd: >
       function fishies; # check number of fish in pond
            count (ps | string match "*-fish*");
        end;
    when: 1193291223
    paths: 
        - "/lost+found/Filename: "
...
---
  - cmd: >
       ls
    when: 1193424554
    paths: 
        - "/lost+found/Filename: "
...
```

So it's actually totally OK to lazily read a chunk between "---" and "..." at a time and to append to it without reading/copying it. Unlike with "---" and "---" it's still one big data structure. [yaml-cpp supports this](https://github.com/jbeder/yaml-cpp/issues/160#issuecomment-87522853.)

Fish could separate each entry like above or do longer spurts. 

There might be some interesting things one could do with anchors and aliases. Repeated nodes, instead of being eliminated when found, could instead be replaced by a pointer to the last instance of that node. This would implicitly track usage counts (#2398) and preserve the integrity of the actual history a bit. (On that note there could conceivably also be an alternate method of walking through the log, where you follow a linked list,  node-to-previous-node letting you follow individual shell sessions alone and in chronological order even after the entries are wrecked by the LRU cache/frecency scrambling. (2312))

**Comment by floam** [comment]
https://github.com/tkf/rash has some cool ideas.

That is exactly the kind of stuff  I was hoping might be possible if outside fish scripts could  could try to augment the fields, generally work with it. d cool stuff  (without confusing/crashing fish.). 

FIxing this up to be YAML would be the correct thing, but since its not YAML now - is YAML really what would best serve fish?

**Comment by floam** [comment]
@ridiculousfish I should say I'm equally for either making this real YAML so that user scripts can work with it and extend the functionalit as I am just defining our own format. I'm equally fine with a binary format resulting from the most ideal data structures we could desire, especially if that may make it easier for fish itself to track things as well as `rash` and still be able to offer both the current `frezency`-like views of the data as well as actual correct accountings of past sessions. What do you think?

**Comment by floam** [comment]
(of course, a data structure we implement could also be serialized with libyaml to YAML for human-readable export too).
