### ISSUE TITLE
add an easy pick label?

### ISSUE THREAD

**Issue by jrobeson** [fish-shell/fish-shell#2762]
After some discussion in an unrelated bug, I was wondering if it was worth adding an Easy Pick label, for easy to fix issues. That does put more work on you maintainers to curate it. Please feel free to close if it's not worth the hassle. I've heard good things about projects that implement it, but they usually have bigger "core" teams.

**Comment by ridiculousfish** [comment]
Sounds reasonable. I added an Easy Pick label. Feel free to comment in any issues that you think are worthy. I'll keep it in mind during triage. Thanks!

**Comment by ridiculousfish** [comment]
Adding Easy Pick since this was easy ;)
