### ISSUE TITLE
glibc 2.23 breaks prompt

### ISSUE THREAD

**Issue by Shadowigor** [fish-shell/fish-shell#2766]
After an update to glibc 2.23, the fish prompt is broken. It might be a problem with glibc, but I can't find out what could cause the trouble.

### Reproduction Steps:

1. Install glibc 2.23
2. Run fish

### Expected behavior:

A normal command line prompt

### Observed behavior:

Error message: fish: Tried to print invalid wide character string
Commands can be entered, but the prompt doesn't show up (by prompt I mean something like 'fish@machine ~> '

### Additional information:

Downgrading glibc to 2.22 resolves the problem entirely. The error message seems to come from wcstombs, but that function doesn't seem to be broken in an isolated test.

---
Fish version: 2.2b1-50-ga5fabc6

Operating system: Arch Linux using fish-shell-git package

Terminal or terminal emulator: urxvt

**Comment by faho** [comment]
Works for me (same distro) - have you rebuilt fish after the upgrade, what's your locale (`locale`)?

>Fish version: 2.2b1-50-ga5fabc6

This version seems rather old - older than the stable fish package in the arch repos. 

>Operating system: Arch Linux using fish-shell-git package

The package is now called [fish-git](https://aur.archlinux.org/packages/fish-git/). You might want to update.

**Comment by Shadowigor** [comment]
You're right, I somehow had it installed from an old repo. I moved to fish-git and have version 2.2.0-658-gf2246df now. Still, the problem is the same. Output of locale:

locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
fish: Tried to print invalid wide character string

**Comment by faho** [comment]
> locale: Cannot set LC_CTYPE to default locale: No such file or directory

Those are weird. Try running uncommenting the set locale in /etc/locale.gen and running`locale-gen`. If that doesn't work, I'd like to see your /etc/locale.conf

**Comment by Shadowigor** [comment]
Ha! Solved it! I never would have gotten the idea to check the locale, but the output I posted seemed quite broken even with the strange prompt. Apparently the update removed my locale entirely. I had to uncomment it in /etc/locale.gen and regenerate it.
