### ISSUE TITLE
"which" doesn't work with aliases

### ISSUE THREAD

**Issue by nielsk** [fish-shell/fish-shell#2774]
When using "which" on an alias it doesn't work and just shows that it isn't in the path

### Reproduction Steps:

1. Create an alias in your config.fish
2. source your config
3. which your_new_alias

### Expected behavior:
fish should show something like:
alias mynewalias = 'that_is_some_bin --with --loads --of --arguments'

### Observed behavior:

which: no mynewalias in (/foo/bar)

### Additional information:

which works in zsh and bash, thus I would expect that it also works in fish  

---
Fish version: 2.2.0

Operating system: Fedora 23, installed via distribution package

Terminal or terminal emulator: urxvt

**Comment by ridiculousfish** [comment]
`which` is an external command `/usr/bin/which` that of course is unaware of fish's internal aliases. Are you perhaps looking for `type`?

**Comment by nielsk** [comment]
ok, I close this. I just found out that "which" is in my setup an alias itself (and apparently in all the distributions I tried recently) to: 

`which='(alias; declare -f) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot'`

Hm…then I have to figure out how I add this in my config.fish because it won't work that way

**Comment by nielsk** [comment]
@ridiculousfish thanks for the hint with type. That seems to do more or less what in other shells the posted which-alias does

**Comment by floam** [comment]
This reminded me of something... reported #2775
