### ISSUE TITLE
Path not searched for executable

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [fish-shell/fish-shell#2777]
I try to run an executable in a directory from the PATH but the executable is not found

### Reproduction Steps:

1. set my PATH in the .config 
2. try to run em++
3. The command is not found

### Expected behavior:

em++ compiler should start

### Observed behavior:

The output says the command is not found

### Additional information:

The path is correctly set 

```
> printenv | grep "PATH"
PATH=/home/guillaume/Downloads/emsdk_portable:/home/guillaume/Downloads/emsdk_portable/clang/fastcomp/build_master_64/bin:/home/guillaume/Downloads/emsdk_portable/node/4.1.1_64bit/bin:/home/guillaume/Downloads/emsdk_portable/emscripten/master:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
```

The executable exists and is executable 

```
> ls -l /home/guillaume/Downloads/emsdk_portable/emscripten/master/em++
-rwxrwxr-x 1 guillaume guillaume 477 févr. 28 22:51 /home/guillaume/Downloads/emsdk_portable/emscripten/master/em++*
```

It works fine with other shells and if I run fish as a child process of fish.

I set the PATH the way explained in the documentation (in config.fish)
```
> set PATH /new/path $PATH
```
  

---
Fish version: fish, version 2.2b1-18-g3a190bb

Operating system: Ubuntu 14.04.3 LTS ppa (if I remember well)

Terminal or terminal emulator: Terminator

**Comment by faho** [comment]
>Fish version: fish, version 2.2b1-18-g3a190bb

You should update - that's a beta version from before last release.

Could you post the output of the following commands:

`printf '%s\n' $PATH`

`command -s em++`

`which em++`

**Comment by GuillaumeLeclerc** [comment]
```
➤ printf '%s\n' $PATH
/home/guillaume/Downloads/emsdk_portable:/home/guillaume/Downloads/emsdk_portable/clang/fastcomp/build_master_64/bin:/home/guillaume/Downloads/emsdk_portable/node/4.1.1_64bit/bin:/home/guillaume/Downloads/emsdk_portable/emscripten/master
/home/guillaume/Downloads/emsdk_portable:/home/guillaume/Downloads/emsdk_portable/clang/fastcomp/build_master_64/bin:/home/guillaume/Downloads/emsdk_portable/node/4.1.1_64bit/bin:/home/guillaume/Downloads/emsdk_portable/emscripten/master
/usr/local/sbin
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/usr/games
/usr/local/games
guillaume@guillaumeX99A:~                                                                     
➤ command -s em++
guillaume@guillaumeX99A:~                                                                     
➤ command -s em++
guillaume@guillaumeX99A:~                                                                     
➤ which em++
/home/guillaume/Downloads/emsdk_portable/emscripten/master/em++
```

**Comment by faho** [comment]
>/home/guillaume/Downloads/emsdk_portable:/home/guillaume/Downloads/emsdk_portable/clang/fastcomp/build_master_64/bin:/home/guillaume/Downloads/emsdk_portable/node/4.1.1_64bit/bin:/home/guillaume/Downloads/emsdk_portable/emscripten/master

There's your issue - this printf call prints the elements of $PATH, one per line.

You added directories separated with a ":", when you should have added them as separate arguments, i.e.:

`set PATH /home/guillaume/Downloads/emsdk_portable /home/guillaume/Downloads/emsdk_portable/clang/fastcomp/build_master_64/bin $PATH` to prepend them.

**Comment by faho** [comment]
The underlying issue is that fish treats $PATH as a list, and these work a bit differently than you might be used to.

When you set a variable, you can give multiple values as arguments, like

```fish
set foo spam eggs # this will be a list with elements "spam" and "eggs"
```

and when you expand a variable that has multiple elements (i.e. is a list), each element will be a separate argument, so `set foo $foo` will keep the exact same elements, and `set foo $foo bacon` will have an additional element (bacon) appended.

Putting this together, `set PATH /bin /usr/bin` will be a path with elements "/bin" and "/usr/bin", while `set PATH $PATH /sbin /usr/sbin` will then append /sbin and /usr/sbin as separate elements.

Fish was treating your $PATH as having (among others) the single element "/home/guillaume/Downloads/emsdk_portable:/home/guillaume/Downloads/emsdk_portable/clang/fastcomp/build_master_64/bin:/home/guillaume/Downloads/emsdk_portable/node/4.1.1_64bit/bin:/home/guillaume/Downloads/emsdk_portable/emscripten/master". Since you have no such directory, it couldn't find anything there.

Now, because other applications expect $PATH to be colon-separated, fish adds those when exporting it, so `which` (an external program) could find it while `command -s` (a builtin) couldn't.

**Comment by GuillaumeLeclerc** [comment]
It works fine, but do you know where did you found the information path should be separated by spaces instead of ":" ? I could not find it in the documentation.

Moreover why `which` is working and not fish ?

Why does it work if I spawn a new fish:

```
guillaume@guillaumeX99A:~                                                                     
➤ em++
The program 'em++' is currently not installed. You can install it by typing:
sudo apt-get install emscripten
guillaume@guillaumeX99A:~                                                                     
➤ fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
guillaume@guillaumeX99A:~                                                                     
➤ em++ #Now it works fine
WARNING:root:no input files
```

**Comment by faho** [comment]
>Moreover why which is working and not fish ?

I just posted why, you probably missed it - which is an external command which expects $PATH to be separated by colons.

>where did you found the information path should be separated by spaces instead of ":" ? I could not find it in the documentation.

From [the tutorial section on $PATH](http://fishshell.com/docs/current/tutorial.html#tut_path):

>Unlike other shells, $PATH is a [list](http://fishshell.com/docs/current/tutorial.html#tut_lists), not a colon-delimited string.

The list section then explains how lists work in fish, complete with a concrete example on $PATH.

Maybe we should clarify the example in the PATH section though.

**Comment by GuillaumeLeclerc** [comment]
Thank you ! Do you know why it works in a child fish ? (Sorry for all that questions but I love understanding how things work)

**Comment by faho** [comment]
>Do you know why it works in a child fish ?

Good question! Simple Answer: When fish inherits $PATH, it turns it into a list by splitting it on colons.

**Comment by GuillaumeLeclerc** [comment]
Thank you, could not be clearer. I'll not make that mistake again !
