### ISSUE TITLE
the "command" builtin should have a `-a` option to obviate the need for "which"

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2778]
Recently a new contributor, @floam, brought to our attention a [problem](https://github.com/fish-shell/fish-shell/issues/2775) reported on the [fish-users](https://sourceforge.net/p/fish/mailman/fish-users/thread/CAO2Rqto6rTRfOzgpa%3Ds7r%2BardXVWc2NJRnEKXZzo2ajv0aendQ%40mail.gmail.com/#msg34630086) mailing list that occurs if someone creates a function named `which` that invokes the `type` builtin. Contributor @faho quickly eliminated the infinite recursion with this [change](https://github.com/fish-shell/fish-shell/commit/fb5a8a089e19d879f792ff836671121928e10125).

I'm opening this issue because I think a better fix is to implement a `-a` switch for the `command` builtin. In conjunction with the `-s` switch that will cause it to return all commands found in $PATH. That makes it a usable replacement for the `command which -a -- $i ^/dev/null` found in _share/functions/type.fish_ thus avoiding the need to spawn an external command for something fish can easily do itself (and already, mostly, does so).

**Comment by faho** [comment]
I thought about if I should just check $PATH manually in the script. I decided against it at the time because I wasn't sure if that was the entire algorithm, so I went with the simple change.

This is cleaner.
