### ISSUE TITLE
Idea: include numbers for easier `prevd X` or `nextd X` usage

### ISSUE THREAD

**Issue by hryanjones** [fish-shell/fish-shell#2786]
For example instead of ...

> $ dirh
> /home/hryanjones
> /home/hryanjones/Documents
> /home/hryanjones/Documents/github/hryanjones.github.io
> **/home/hryanjones/Pictures**
> /tmp
> /media/hryanjones/31E0-2252

... it would also show the relative numbers needed to nextd or prevd:

> $ dirh
> 3 /home/hryanjones
> 2 /home/hryanjones/Documents
> 1 /home/hryanjones/Documents/github/hryanjones.github.io
> **/home/hryanjones/Pictures**
> 1/tmp
> 2 /media/hryanjones/31E0-2252

Just an idea.

-Ryan

**Comment by krader1961** [comment]
Rather than modify `dirh` see my alternative proposal for a `mcd` (menu change directory) command in issue #2847. If that were adopted would you still want this feature request implemented?

**Comment by krader1961** [comment]
I'm willing to implement this proposal. I don't see how it could break anything in as much as `dirh` isn't meant to be scripted. Anyone using it in that manner probably deserves to have their script broken.

On the other hand I'm disinclined to do anything that makes using `prevd`/`nextd` easier since I think that idiom is fundamentally broken and I'd like to see it removed from future releases. This functionality predates the reorganization of the source code that occurred in 2006. My git'fu isn't strong enough to determine where this code was introduced prior to that date.

**Comment by floam** [comment]
I think you ca just ignore those system headers it cppcheck is too dumb to find. I run it like this:

`cppcheck src/ --enable=all --suppress=missingIncludeSystem`

**Comment by floam** [comment]
And if you have pygments:

```
 ~> cppcheck src/ --enable=all --suppress=missingIncludeSystem --force --xml --xml-version=2 --force 2> cppcheck.xml
...
~>cppcheck-htmlreport --title fish-HEAD --file=cppcheck.xml --report-dir=.
Parsing xml report.
Creating . directory
Processing errors
  src/builtin.cpp
  src/builtin_complete.cpp
  src/builtin_ulimit.cpp
  src/color.cpp
  src/common.cpp
  src/common.h
  src/complete.cpp
  src/env.cpp
  src/env.h
  src/env_universal_common.cpp
  src/expand.cpp
  src/fallback.cpp
  src/fish.cpp
  src/fish_indent.cpp
  src/fish_tests.cpp
  src/fish_version.cpp
  src/highlight.cpp
  src/history.cpp
  src/io.cpp
  src/key_reader.cpp
  src/kill.cpp
  src/lru.h
  src/parse_tree.cpp
  src/parse_tree.h
  src/parse_util.cpp
  src/parser.cpp
  src/postfork.cpp
  src/proc.cpp
  src/reader.cpp
  src/signal.cpp
  src/utf8.cpp
  src/wgetopt.cpp
  src/wildcard.cpp
  src/wutil.cpp
Creating index.html
Creating style.css file
Creating stats.html (statistics)


Open './index.html' to see the results.
```

**Comment by faho** [comment]
@floam: I think you've commented on the wrong issue :smile:.

**Comment by krader1961** [comment]
@hryanjones: Given the availability of a better idiom, my `mcd` command, do you still want to see this implemented?
