### ISSUE TITLE
Wrong highlight for wildcards in input redirection

### ISSUE THREAD

**Issue by f1u77y** [fish-shell/fish-shell#2789]
### Reproduction steps:
1. Type a command with a wildcard in input redirection in a such way that's exactly one match for that wildcard(let it be `cat < /dev/ur*ndom`)

### Expected behaviour
fish should highlight `/dev/ur*ndom` with `$fish_color_redirection` or don't execute command correctly

### Observed behaviour
fish highlights `/dev/ur*ndom` with `$fish_color_error` but executes command correctly

### Additional information
```
$ fish --version
fish, version 2.2.0
```

**Comment by ridiculousfish** [comment]
Nice find

**Comment by ridiculousfish** [comment]
We were neglecting to set the generation count for the background highlighting thread, so we were always cancelling the highlight (thinking we were interrupted).
