### ISSUE TITLE
getopt.h / wgetopt.h cleanup

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2790]
While working on issue #102 I noticed that *src/fallback.h* defines several values normally found in the systems *getopt.h* header. Which wouldn't be an issue except that it defines them piecemeal which means they can easily conflict with symbols defined before *src/fallback.h* is included. In practice that is extremely unlikely but is still a potential problem. What's worse, however, is the code uses fish's wgetopt implementation everywhere but *fish.cpp*, *fish_indent.cpp*, and *fish_tests.cpp*. It seems to me that those getopt symbols should be removed from *fallback.h* and those modules should be using fish's wgetopt implementation.

P.S., None of the existing labels are appropriate. I'd select something like "lint" or "cleanup" if they existed.

**Comment by krader1961** [comment]
I can't find any reason why a workaround for a missing getopt_long() function was needed in early 2006. Googling shows it had been part of the GNU library for several years by then. I can only surmise that some of the mainstream UNIX distros like Solaris may not have had an implementation at that time. But since BSD, OS X, Linux, Solaris all have it now there is no good reason to keep that baggage.

For the record the workaround for a missing getopt_long() function was introduced by ~axel on 2006-08-28 via commit 548e379d. It was to avoid doing the same check in *fishd.c*, *mimedb.c* and *set_color.c* none of which still exist. All of the changes to those lines of code since then only make non-functional changes (e.g., adding comments, lint removal).

The aforementioned workaround in *fallback.h* was introduced after the initial introduction of getopt_long() use guarded by `#ifdef HAVE_GETOPT_LONG` by ~axel in commit 89eb80f3a417897cc533746f3811458d0cbb291f on 2006-01-24.

**Comment by krader1961** [comment]
I also noticed, while addressing the original issue, that there is inconsistency in how the fish private **wgetopt_long()** function is used. Not to mention silly things like conflating the NULL pointer and zero (yeah, I know that isn't a problem in practice, but it's still ugly).

**Comment by krader1961** [comment]
I'm not going to convert *fish.cpp* and *fish_indent.cpp* to use **wgetopt_long** at this time. I (or someone else) needs to first ensure that such changes are compatible with locale settings that are not UTF-8.

**Comment by zanchey** [comment]
Sounds like a good idea. `wgetopt_long` didn't exist on Solaris 9, according to the [manual page archive on the FreeBSD website](https://www.freebsd.org/cgi/man.cgi?query=getopt_long&apropos=0&sektion=0&manpath=SunOS+5.9&arch=default&format=html), but was introduced in Solaris 10 as a compatibility shim.

**Comment by faho** [comment]
For those (like me) unfamiliar with Solaris, version 9 achieved EOL in October 2014, version 10 was released in January 2005.
