### ISSUE TITLE
Enable 24-bit support for neovim later

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#2792]
We currently explicitly disable 24-bit support for neovim because that had a release with a fubar'd implementation (all text would show up white).

We should enable it once that release either isn't supported or isn't in circulation anymore.

See #2768.

**Comment by mqudsi** [comment]
Fixed for 3.0

**Comment by ridiculousfish** [comment]
The commit bb419d4f5edc7e442a92cc24e725b99d65d23b58 appears to have broken the tests on my macOS and Linux boxes. Reverted as `c2a5e7ae27115f1e751deb0d6ef7c92a82b4e18c`. @mqudsi

**Comment by mqudsi** [comment]
I think it was the unprefix and in `if and not set`. Fixed again in 13fd9be.
