### ISSUE TITLE
clarify fish_config color scheme preview to more accurately and more fully represent/configure effects.

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#2794]
This is the color scheme preview:
<img width="444" alt="screenshot 2016-03-04 at 3 25 48 am" src="https://cloud.githubusercontent.com/assets/291142/13525873/dd0bc9da-e1b8-11e5-83fc-3294eb2c8a3f.png">

The "Bright vixens jump; dozy fowl quack" semantics instead of real command-line stuff is unhelpful:

The most prominent command on the preview is `/bright/vixens`. Users may believe they are picking a color for file paths, (maybe dozy is also a path? and echo gets the same color?) It can also initially be confused for the path part of the prompt as it's on the top left. If users do not try to customize the individual components or are just looking looking through the thumbnails this is very easy. Suggest use a recognizable command here or something with `/usr/bin` to make it unambiguous.  In real life fish (`/bright/vixens` doesn't exist) it would not even be that color.

<img width="301" alt="screenshot 2016-03-04 at 2 47 03 am" src="https://cloud.githubusercontent.com/assets/291142/13525544/6685a53a-e1b6-11e5-9a27-da2e49543174.png">

The line with an autosuggestion shows the incomplete command colored the command color but that's inaccurate, in fish it gets the error color as autosuggestions do not change the colors of partial commands:
<img width="308" alt="screenshot 2016-03-04 at 3 27 01 am" src="https://cloud.githubusercontent.com/assets/291142/13525909/30118aca-e1b9-11e5-878e-9a0196e8dec5.png">

In the gallery area of the page with the screenshots the redirection color component is cropped out entirely.

On the error example, it looks a lot like just a long string, and it's about as prominent as the regular foreground text on a prompt would be. The missing apostrophe causing the error is small, and is cropped out on the thumbnails. It ends up being that it's a little difficult to guess what a color scheme will really feel like when window shopping the configuration panel.

~~The colors in iTerm2 and Terminal.app are also often a ways off from what WebKit there was showing. For instance the autosuggestion grey is much brighter than what I picked. I perhaps wish that part were not configurable and it just used the dim option.~~

**Comment by faho** [comment]
This really looks like you have a terminal palette configured that doesn't match fish's expectation.

Can you post a screenshot of the following:

```fish
for i in (seq 31 49)
    echo $i \e\["$i"m
end
```

**Comment by floam** [comment]
<img width="444" alt="screenshot 2016-03-04 at 3 25 48 am" src="https://cloud.githubusercontent.com/assets/291142/13526044/2cda8bb2-e1ba-11e5-8e78-4b9dbe1befa3.png">

**Comment by floam** [comment]
<img width="226" alt="screenshot 2016-03-04 at 3 35 09 am" src="https://cloud.githubusercontent.com/assets/291142/13526047/351b197c-e1ba-11e5-92ef-4f86a826f5f1.png">

**Comment by faho** [comment]
![screenshot_20160304_123747](https://cloud.githubusercontent.com/assets/5185367/13526092/ee93a1c6-e205-11e5-9868-ac8b6b593240.png)


Also, which preset is that?

**Comment by floam** [comment]
It was Tomorrow Night but I rearranged the colors a bit.

**Comment by faho** [comment]
>It was Tomorrow Night but I rearranged the colors a bit.

Could you try with the stock preset? That way I've got a chance to reproduce it.

As you've (hopefully - as I said just yesterday, I'm red-green blind, so I try not to rely on how I preceive colors) seen there's a bit of difference between the colors your terminal prints and what mine (KDE Konsole on Linux, with the default "Linux colors" preset) does.

However there might also be an issue that "/bright/vixens" is probably not a valid command, and it's possible that some other colors aren't correct either (as in the wrong variable is picked, not the wrong color number).

**Comment by floam** [comment]
<img width="319" alt="screenshot 2016-03-04 at 3 53 31 am" src="https://cloud.githubusercontent.com/assets/291142/13526445/c2bf21f4-e1bc-11e5-9ec2-c103ca844035.png">

**Comment by faho** [comment]
![screenshot_20160304_125605](https://cloud.githubusercontent.com/assets/5185367/13526493/80fb3414-e208-11e5-86a2-114ef3a3c2e4.png)

Never mind my weird language :smile: ("Farbe" means color).

And the color preset file contains:

```
[Background]
Color=0,0,0

[BackgroundIntense]
Color=104,104,104

[Color0]
Color=0,0,0

[Color0Intense]
Color=104,104,104

[Color1]
Color=178,24,24

[Color1Intense]
Color=255,84,84

[Color2]
Color=24,178,24

[Color2Intense]
Color=84,255,84

[Color3]
Color=178,104,24

[Color3Intense]
Color=255,255,84

[Color4]
Color=24,24,178

[Color4Intense]
Color=84,84,255

[Color5]
Color=178,24,178

[Color5Intense]
Color=255,84,255

[Color6]
Color=24,178,178

[Color6Intense]
Color=84,255,255

[Color7]
Color=178,178,178

[Color7Intense]
Color=255,255,255

[Foreground]
Color=178,178,178

[ForegroundIntense]
Color=255,255,255

[General]
Description=Linux Colors
```

Try setting those and see what it looks like.

**Comment by floam** [comment]
Huh.. Just changed themes.
<img width="374" alt="screenshot 2016-03-04 at 3 56 16 am" src="https://cloud.githubusercontent.com/assets/291142/13526522/3f2e68ee-e1bd-11e5-9fee-058ef95cb9ee.png">

**Comment by floam** [comment]
I reset to a default nearly unconfigured profile in Terminal.app and I set the exact RGB values you have for 0-15, background, foreground and foreground bright. I don't have a background bright option exposed in the UI. I don't know why it suddenly started doing the full lines earlier. 
<img width="539" alt="screenshot 2016-03-04 at 4 13 54 am" src="https://cloud.githubusercontent.com/assets/291142/13526871/cc7158d6-e1bf-11e5-8b0c-66a9cc7660c6.png">

**Comment by faho** [comment]
And how close does the theme now feel?

**Comment by floam** [comment]
Still brighter on the actual terminal.
<img width="619" alt="screenshot 2016-03-04 at 4 40 53 am" src="https://cloud.githubusercontent.com/assets/291142/13527861/30904e7e-e1c7-11e5-9eb7-27359bb3f186.png">

**Comment by floam** [comment]
<img width="232" alt="screenshot 2016-03-04 at 5 12 35 am" src="https://cloud.githubusercontent.com/assets/291142/13527949/c88d4d76-e1c7-11e5-829a-49f2ea35e3d5.png">
Those blocks are #777 if I point a color picker at them. Like 4 shades off at 256 colors.

**Comment by faho** [comment]
Can you see which sequence fish ends up sending, e.g. via `set_color 555 | od -t x1z`?

**Comment by floam** [comment]
Yeah. It's sending "\e[38;5;240m". So that's actually [#585858 on Wikipedia's xterm-256 chart](https://upload.wikimedia.org/wikipedia/en/1/15/Xterm_256color_chart.svg). So I'd suppose the color inaccuracy is a bug with something in Terminal.app.

**Comment by floam** [comment]
>>It was Tomorrow Night but I rearranged the colors a bit.
>Could you try with the stock preset? That way I've got a chance to reproduce it.

Oh, no, I was talking about the color scheme I had picked for fish there, not reassigning colors at the terminal! And I didn't notice you were responding to that specifically. Sorry! Wasted your time.

**Comment by faho** [comment]
>So I'd suppose the color inaccuracy is a bug with something in Terminal.app.

Can you try in iTerm2 with and without $fish_term24bit set to 1?

**Comment by faho** [comment]
That is assuming you're running a new build of iTerm2, IIRC the last stable release doesn't support 24bit.

**Comment by floam** [comment]
With `$fish_term24bit` iTerm2 is doing #555555, without it's $585858.

**Comment by faho** [comment]
So it doesn't seem there's a fish issue here.

Long-term we should check if preferring 24bit sequences (i.e. converting from named colors to RGB) if available is worth it, so we get away from the reliance on the palette. Or we could set all our color variables to RGB values, though that would make the code uglier and only apply to our stuff, not `set_color` calls in user code.

**Comment by floam** [comment]
> So it doesn't seem there's a fish issue here.
Not with the color accuracy. The main point of this issue, the idiosyncratic sample text should get revised though.

**Comment by floam** [comment]
Also, absent in the sample shell session are any operators or command arguments. These should be there and have their colors set. These get rather not-great cyan, red colors from the ANSI palette set no mater what theme the user picks. Also, same thing with history matches, matched parenthesis, and everything in the pager.

I don't think those necessarily merit exposition on the configuration panel but at least they should have reasonable colors set for them to fit the rest of the chosen scheme when it is applied.

**Comment by floam** [comment]
I think this bug report of mine is incredibly vague and sucks.
