### ISSUE TITLE
remove doxygen markup in source code

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2795]
The *CONTRIBUTING.md* file says that source code should use Doxygen conventions. Yet I can not find anything in the project (including building the documentation) that depends on that. And most of the source code either does not adhere to that recommendation or is inconsistent with reality. For one trivial example consider the first line of *src/builtin.cpp* which says

```
/** \file builtin.c
```

I was intrigued by Donald Knuth's concept of "[Literate Programming](https://en.wikipedia.org/wiki/Literate_programming)" when I first read about it (I own hardbound copies of his TeX series of books which depend on the idea). But I don't see the value in this project if we're not going to be tough-minded about requiring the code adhere to that requirement. Not to mention actually doing something with the information.

@ridiculousfish seems to agree that these annotations should be removed given this [comment](https://github.com/fish-shell/fish-shell/issues/2319#issuecomment-189106574) where they say:

> D'oh! These ought to be updated, or removed outright, or whatever'd. If you're looking for an easy contribution cleaning that up would be appreciated!

**Comment by ridiculousfish** [comment]
When I was learning the fish codebase, I didn't find the doxygen-generated docs to be very useful. I think doxygen is great for libraries and APIs but not as useful for leaf-level applications, and so we shouldn't waste energy generating and hosting the doxygen docs for the internals. So I haven't bothered to keep up with that commenting style.

(To be clear this is for the C++ internals. Doxygen is pretty great for the fish command docs.)

**Comment by krader1961** [comment]
I agree that Doxygen is useful for the user facing ("command") documentation but is not particularly useful for the internal (C++) code which is not "library" code intended to be used by other projects. In no small part because in my experience the comments about source code are not authoritative unless the project is extremely hard-nosed about such things. Having said that, there is still value in encouraging people to document the API of public functions in the associated comment. I don't think that requires adhering to the Doxygen standard for source code since we're not doing anything with those comments.

**Comment by krader1961** [comment]
The work I'm doing to restyle the code to a consistent style is taking care of this to a limited extent. Closing this as it is redundant.
