### ISSUE TITLE
The dpkg autocompletion doesn't work as expected

### ISSUE THREAD

**Issue by marmistrz** [fish-shell/fish-shell#2798]
When trying to complete the `dpkg` command, the packages aren't autocompleted

### Reproduction Steps:

Type `dpkg -L cin <tab>`

### Expected behavior:
A list of installed packages, for example `cinnamon` should be suggested

### Observed behavior:

The autocomplete suggests the files/directories instead

---

Fish version: fish, version 2.2.0

Operating system: Linux Mint 17.3 Cinnamon, PPA

Terminal or terminal emulator: terminator

**Comment by faho** [comment]
The [man page](http://man.he.net/man1/dpkg) lists "-L" as an option to `dpkg-query`, not bare `dpkg`. I don't currently have a debian machine with me, so I can't test - does `dpkg -L cinnamon` actually work?

The [dpkg completion](https://github.com/fish-shell/fish-shell/blob/master/share/completions/dpkg.fish) is also rather bare bones, so improvements there are certainly possible.

**Comment by zanchey** [comment]
Annoyingly, `dpkg` almost (but not quite) wraps `dpkg-deb` and `dpkg-query` - so yes, `dpkg -{l,L} cinnamon` does work.

**Comment by zanchey** [comment]
This has been annoying me for a while, so I've added the most commonly used options from my history with `dpkg`.
