### ISSUE TITLE
Problem with environment variables in Java

### ISSUE THREAD

**Issue by aexmachina** [fish-shell/fish-shell#2800]
Environment variables defined in Fish aren't available to Java processes:

### Reproduction Steps:

1. `set -x ANDROID_HOME /usr/local/opt/android-sdk`
2. Create `Test.java` with [these contents](https://gist.github.com/aexmachina/7c7740c39b84212f2b96) and compile it using `javac Test.java`
3. `java Test`

### Expected behavior:

The script should output `ANDROID_HOME=/usr/local/opt/android-sdk`.

### Observed behavior:

The script outputs `ANDROID_HOME=null`.

### Additional information:

This prevents Gradle (a common Java build tool) from working without using a `local.properties` file.

---
Fish version: fish, version 2.2.0

Operating system: Mac OS 10.11.3, installed with Homebrew

Terminal or terminal emulator: iTerm 2

**Comment by krader1961** [comment]
Environment vars can definitely be exported by fish. Let's remove Java from the equation. What happens if you create and run a non-fish script:

```
set -x ANDROID_HOME /usr/local/opt/android-sdk
echo '#!/bin/sh' > /tmp/script
echo 'echo $ANDROID_HOME' >> /tmp/script
chmod 755 /tmp/script
/tmp/script
```

**Comment by aexmachina** [comment]
Sorry, it was obviously a problem with the shell session. Thanks for the quick response.

**Comment by ridiculousfish** [comment]
I was going to say it might be #2563, but i guess this has been resolved.
