### ISSUE TITLE
How do I completely uninstall Fish if I don't have access to shell anymore because of Fish?

### ISSUE THREAD

**Issue by corysimmons** [fish-shell/fish-shell#2801]
Have had Fish for years. Enjoy it. Tried to install Fisherman. Started getting "Failed to execute ." errors (assuming it was trying to source crap) which broke shell (never got access to the command line again -- it just displayed that error).

Tried to manually delete Fisherman folders from ~/.config. Fixed one error but then there was something else so I just deleted Fish folders hoping to eventually get back to bash.

Now I have this error and my terminal is completely fubar:

```fish
Standard input: echo $_ " "; __fish_pwd
                             ^
in command substitution
	called on standard input,

Standard input: __fish_pwd
                ^
in command substitution
	called on standard input,

in command substitution
	called on standard input,

Standard input: echo $_ " "; __fish_pwd
                             ^
in command substitution
	called on standard input,
```

At this point can someone please just instruct me on how to nuke Fish so I can use my Terminal again?

---

Macbook El Capitan, Homebrew, iTerm2 (but broken on Terminal as well)

**Comment by ridiculousfish** [comment]
You don't get back to bash by deleting fish :)

With iTerm2, choose Preferences->Profiles, General tab, and you can set the command to run to /bin/bash. This will give you a shell that you can use to repair or uninstall fish.

![screen shot 2016-03-07 at 1 49 50 am](https://cloud.githubusercontent.com/assets/920838/13565770/04e61122-e407-11e5-909b-30f2fc85fac7.png)

**Comment by corysimmons** [comment]
Awesome thanks for getting back to me so soon!

What's the deal with Fisherman? Is it good or do you get reports about it breaking stuff?

**Comment by ridiculousfish** [comment]
I'm not sure, but I think they would be appreciative if you opened an issue describing your problem and experience: https://github.com/fisherman/fisherman

**Comment by corysimmons** [comment]
Aight sorry. Thanks again for the quick reply. =)
