### ISSUE TITLE
fish: Unknown command '__fish_pwd'

### ISSUE THREAD

**Issue by lamiastella** [fish-shell/fish-shell#2806]
So I was trying to install fish shell in OSX Yosemite using brew and I ended up with this. Any help is greatly appreciated as I am stuck with this:

mona@ > history
fish: Unknown command '__fish_pwd'
fish: echo $_ " "; __fish_pwd
                   ^
in command substitution
    called on standard input

fish: Unknown command 'less'
- (line 1): begin; less 
                   ^
from sourcing file -
    called on line 60 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/eval.fish

in function 'eval'
    called on line 42 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/history.fish

in function 'history'
    called on standard input

fish: Unknown command 'sed'
/usr/local/Cellar/fish/2.2.0/share/fish/functions/prompt_pwd.fish (line 2):     echo $PWD | sed -e "s|^$realhome|~|" $args_pre -e 's-\([^/.]\)[^/]*/-\1/-g' $args_post
                                                                                            ^
in function 'prompt_pwd'
    called on line 6 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/fish_prompt.fish

in command substitution
    called on line 4 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/fish_prompt.fish

in function 'fish_prompt'
    called on standard input

in command substitution
    called on standard input

fish: Unknown command '__fish_pwd'
fish: echo $_ " "; __fish_pwd
                   ^
in command substitution

**Comment by ridiculousfish** [comment]
You may have borked your $PATH. What does `echo $PATH` show?

**Comment by lamiastella** [comment]
Fixed by deleting the config.fish file using the Finder Go to Folder utility and opening a new terminal window.

**Comment by RryLee** [comment]
@lamiastella  I can't fix thi problem, please give me some details

**Comment by faho** [comment]
@RryLee: "__fish_pwd" is among our default functions, so it should be installed alongside fish.

You should see a file called "__fish_pwd.fish" in $__fish_datadir/functions, and you should have $__fish_datadir/functions in $fish_function_path.

In code:

```fish
test -e $__fish_datadir/functions/__fish_pwd.fish; or echo "FILE NOT FOUND"
contains -- $__fish_datadir/functions $fish_function_path; or echo "VARIABLE WRONG"
```

should print nothing and return 0. If it doesn't, you have probably either broken your fish install or your configuration, so reinstalling fish or fixing your configuration should fix it.

**Comment by lamiastella** [comment]
@RryLee do you have an OSX? If you go to the config folders, there should be one for fish shell, basically delete the config.fish in that folder and open the terminal again and you'll be fine. You can also switch to bash by typing bash in the terminal. Hope it helps.

**Comment by RryLee** [comment]
@lamiastella Year, thank you, i just compile the fish-shell project to solve the problem

**Comment by cyrilmarois** [comment]
@monajalal  you saved my day !!

**Comment by Vistaus** [comment]
I have the same problem on Solus (Linux). I already deleted the fish config file, but the error keeps appearing.

**Comment by faho** [comment]
@Vistaus: Please run:

```fish
test -e $__fish_datadir/functions/__fish_pwd.fish; or echo "FILE NOT FOUND"
contains -- $__fish_datadir/functions $fish_function_path; or echo "VARIABLE WRONG" $fish_function_path
```

What does that print?

**Comment by boris-penev** [comment]
I encounter this if I run `make` but not `make install`. So if you see this error message after building from source, make sure you install it, and set the `CMAKE_INSTALL_PREFIX` if you want to change the install directory.

**Comment by blyatmobilebr** [comment]
> Fixed by deleting the config.fish file using the Finder Go to Folder utility and opening a new terminal window.

You saved my day! Thanks
