### ISSUE TITLE
Fish looses the current directory

### ISSUE THREAD

**Issue by albertz** [fish-shell/fish-shell#2811]
Sometimes, Fish looses the current directory and gets in a strange state.
This usually happens when I use auto-completion for directories but not always.

```
zeyer@sulfid ~> ls ~/.linuxbrew    # here, everything is still fine
zeyer@sulfid > ls ~/.linuxbrew
zeyer@sulfid > 
zeyer@sulfid > 
zeyer@sulfid > ls
zeyer@sulfid > echo foo
foo
zeyer@sulfid > ls
zeyer@sulfid > pwd
/u/zeyer
zeyer@sulfid > cd .linuxbrew
zeyer@sulfid > pwd
/work/asr2/zeyer/linuxbrew
zeyer@sulfid > cd
zeyer@sulfid > ls
zeyer@sulfid > echo (ls)
Documents/ ...
```

Fish version: 2.2.0 but this happened also in other Fish versions.

Operating system: Installed Fish via Linuxbrew, on Ubuntu 12.

**Comment by krader1961** [comment]
What does `ls -ld ~/.linuxbrew` report? Is it by any chance a symlink to the directory reported by `pwd`? If so that is the expected behavior for fish.

**Comment by albertz** [comment]
That is not what this error report is about.

You see in the prompt that it doesn't show the current directory anymore.
The normal prompt is only in the first line in my report.
Also, `ls` doesn't list anything and doesn't work anymore. It only works when run in a subshell (`(ls)`).

**Comment by floam** [comment]
It's the ~ going away at the top, not the last output.

**Comment by floam** [comment]
Does it do it every time you are in that location and type "ls ~/.linuxbrew " or ls something? Are you activating an autocompletion or typing it out fully?

If it does always happen, can you try not hitting enter, instead type it all out just like you did, or use the completion just like you did, but once it's fully entered hit backspace until you have no prompt, and then hit enter?

**Comment by albertz** [comment]
No, not every time. I cannot really reproduce it deterministically. I just tried and was not able to reproduce it at all. However, it still happens from time to time, maybe once per week or so. And always right after I used tab-autocompletion for some directory or file.

**Comment by albertz** [comment]
Also maybe related: Some of the file system, including my home directory, is a NFS mount. And sometimes we have some network lags and NFS sometimes just behaves a bit strange.

**Comment by floam** [comment]
Next time it happens, it would be interesting to try all three of `builtin pwd`, `prompt_pwd`, `/bin/pwd`, `echo $PWD`, and your prompt: `fish_prompt`.

As well as  `stat -x (pwd)`. 

I don't really know what's up.

**Comment by floam** [comment]
Is $fish_prompt_pwd_dir_length set (now, normally)?

**Comment by albertz** [comment]
Doesn't seem so:
```
zeyer@sulfid ~> echo $fish_prompt_pwd_dir_length

zeyer@sulfid ~> 
```

**Comment by krader1961** [comment]
How does */u/zeyer* relate to */work/asr2/zeyer* which you were in after the `cd .linuxbrew` command? Is the former a local filesystem while the latter NFS? Is your *~/.linuxbrew* a symlink as implied by the information you provided?

While fish provides a thin wrapper function around the ls program that wouldn't affect the ability of ls to enumerate the contents of a directory. Have you examined the system log for your machine for relevant errors? On Ubuntu that would be */var/log/syslog* and */var/log/kern.log*. It wouldn't surprise me if you find NFS related messages likely involving the phrase "stale file handle". If you can find a way to reproduce the problem running fish with the `-d5` option.

**Comment by floam** [comment]
Based on the paths shown and the context (the linux port of Homebrew, which symlinks into ~), that's probably a symlink to the NFS share.

So the other thing I'm wondering about is how his PATH being super slow to traverse might break stuff.

**Comment by albertz** [comment]
@krader1961 `/u/zeyer/.linuxbrew` is a symlink to `/work/asr2/zeyer`, and "~" is `/u/zeyer`. Both are on NFS mounts but not the same mount.

I don't have access to `/var/log/{syslog,kern.log}`. `dmesg | grep nfs` doesn't give me that much:
```
[13048654.234415] nfs: server raid4 not responding, still trying
[13048654.234678] nfs: server raid4 OK
[13051297.122657] nfs: server raid4 not responding, still trying
[13051297.122957] nfs: server raid4 OK
```
(I haven't restarted for quite some time and the problem happened multiple times since then.)

Another thing, maybe that is related:
```
zeyer@sulfid ~> cat .config/fish/config.fish 

function fish_preexec --on-event fish_preexec
        /u/zeyer/dotfiles/system-tools/helpers/local-history-add.py $argv &
end
```

**Comment by albertz** [comment]
Btw., as you mentioned `$PATH`, that it quite long in my case:
```
zeyer@sulfid ~> echo $PATH
/u/zeyer/environments/setup/common/bin /u/zeyer/environments/setup/common/bin/training /u/zeyer/environments/setup/common/bin/recognition /u/sge-6.2.5/bin/lx24-amd64 /u/zeyer/.gem/ruby/1.9.1/bin /u/zeyer/dotfiles/bin /u/zeyer/dotfiles/system-tools/bin /u/zeyer/tools/bin /u/zeyer/.local/bin /u/zeyer/.linuxbrew/bin /u/zeyer/environments/setup/common/bin /u/zeyer/environments/setup/common/bin/training /u/zeyer/environments/setup/common/bin/recognition /u/sge-6.2.5/bin/lx24-amd64 /u/zeyer/.linuxbrew/bin /u/zeyer/.gem/ruby/1.9.1/bin /u/zeyer/dotfiles/bin /u/zeyer/dotfiles/system-tools/bin /u/zeyer/tools/bin /u/zeyer/.local/bin /u/zeyer/environments/setup/common/bin /u/zeyer/environments/setup/common/bin/training /u/zeyer/environments/setup/common/bin/recognition /u/sge-6.2.5/bin/lx24-amd64 /u/zeyer/.linuxbrew/bin /u/zeyer/.gem/ruby/1.9.1/bin /u/zeyer/dotfiles/bin /u/zeyer/dotfiles/system-tools/bin /u/zeyer/tools/bin /u/zeyer/.local/bin /usr/lib/lightdm/lightdm /usr/local/bin /usr/bin /bin
```

**Comment by floam** [comment]
`__fish_sysconfdir`
`__fish_datadir`

**Comment by albertz** [comment]
```
zeyer@sulfid ~> echo $__fish_sysconfdir
/work/asr2/zeyer/linuxbrew/Cellar/fish/2.2.0/etc/fish
zeyer@sulfid ~> echo $__fish_datadir
/work/asr2/zeyer/linuxbrew/Cellar/fish/2.2.0/share/fish
```

**Comment by floam** [comment]
Locking nfs?

**Comment by krader1961** [comment]
That fish_preexec event handler could be relevant since a NFS problem could cause the command to hang which might, somehow, exacerbate the problem. Probably a long shot, though.

Try grepping your logs again only with the `-i` option to make it case-insensitive. It's also possible there is a relevant error message that does not include the word "nfs" so you'll probably need to visually scan the logs around the times you see the problem. Up until a few years ago I earned my living troubleshooting problems like this for two decades. My gut tells me the most likely explanation is a problem with the remote filesystems.

**Comment by albertz** [comment]
`dmesg | grep -i nfs` yields just the same. `dmesg` is quite cluttered with a lot of stuff, just today and also a few days ago I filled up all my memory and I see a lot of oom messages there which should all be unrelated. Then there is also this:
```
[13048745.972174] lockd: unexpected unlock status: 7
[13048745.972182] lockd: unexpected unlock status: 7
[13048745.972871] lockd: unexpected unlock status: 7
[13048745.972898] lockd: unexpected unlock status: 7
[13048746.000571] lockd: unexpected unlock status: 7
[13048746.000609] lockd: unexpected unlock status: 7
```
Btw., about NFS, I see a lot of these files:
```
zeyer@sulfid ~> ls -la .nfs000000000*
-rw-rwx--- 1 zeyer assi 23799 Feb  9 15:42 .nfs00000000000766e500000f56*
-rw-rwx--- 1 zeyer assi 23805 Feb  9 15:42 .nfs000000000007683f00000f57*
-rw-rwx--- 1 zeyer assi 23805 Feb  9 15:42 .nfs000000000007695700000f58*
-rw-rwx--- 1 zeyer assi 23805 Feb  9 15:42 .nfs00000000000769f600000f59*
-rw-rwx--- 1 zeyer assi 23805 Feb  9 15:43 .nfs0000000000076aab00000f69*
-rw------- 1 zeyer assi 12145 Dec 28 12:19 .nfs00000000000a2539000009e9
-rw-rwx--- 1 zeyer assi 23338 Feb 25 12:00 .nfs00000000000b762000001811*
-rw-rwx--- 1 zeyer assi 23338 Feb 25 11:29 .nfs00000000000b7bbf000017f8*
-rw------- 1 zeyer assi  4096 Feb 23 13:33 .nfs00000000001a725800001669
-rw-rwx--- 1 zeyer assi 24095 Jan 21 11:15 .nfs00000000003b5cf900000a97*
-rw-rwx--- 1 zeyer assi 24218 Jan 20 17:29 .nfs000000000062122700000a44*
...
```

**Comment by krader1961** [comment]
It's been awhile since I've had to debug NFS problems but my memory is that those get created when a file is removed while there is an outstanding reference to it (i.e., a process has it open). The number is the NFS file-handle ID of the deleted object.

**Comment by floam** [comment]
`set -U`
Show me your universal env vars? The scariest warning in the fish source, src/env_universal_common.cpp


```
...
  It's possible that the underlying filesystem does not support locks (lockless NFS). In this case, we risk data loss if two shells try to write their universal variables simultaneously. In practice this is unlikely, since uvars are usually written interactively.
    
    Prior versions of fish used a hard link scheme to support file locking on lockless NFS. The risk here is that if the process crashes or is killed while holding the lock, future instances of fish will not be able to obtain it. This seems to be a greater risk than that of data loss on lockless NFS. Users who put their home directory on lockless NFS are playing with fire anyways.
    ```
He does say unlikely.

**Comment by krader1961** [comment]
Those OOM messages could be relevant depending on what processes are being killed since fish depends on external programs to a much greater extent than other shells like bash and zsh.

**Comment by albertz** [comment]
```
zeyer@sulfid ~> set -U
__fish_init_1_22_0
__fish_init_1_50_0
fish_color_autosuggestion '555'  'yellow'
fish_color_command '005fd7'  'purple'
fish_color_comment red
fish_color_cwd green
fish_color_cwd_root red
fish_color_error 'red'  '--bold'
fish_color_escape cyan
fish_color_history_current cyan
fish_color_match cyan
fish_color_normal normal
fish_color_operator cyan
fish_color_param '00afff'  'cyan'
fish_color_quote brown
fish_color_redirection normal
fish_color_search_match --background=purple
fish_color_selection --background=purple
fish_color_valid_path --underline
fish_greeting Welcome\ to\ fish,\ the\ friendly\ interactive\ shell\nType\ \e\[32mhe…
fish_key_bindings fish_default_key_bindings
fish_pager_color_completion normal
fish_pager_color_description '555'  'yellow'
fish_pager_color_prefix cyan
fish_pager_color_progress cyan
zeyer@sulfid ~> 
```

Btw., here are some of my mount options:
```
raid4:/export/raid4/homes/sge-6.2.5 on /u/sge-6.2.5 type nfs (rw,noatime,vers=3,sloppy,addr=137.226.36.198)
raid4:/export/raid4/homes/zeyer on /u/zeyer type nfs (rw,noatime,vers=3,sloppy,addr=137.226.36.198)
asr-raid-2:/volume/work on /work/asr2 type nfs (rw,noatime,vers=3,intr,sloppy,addr=137.226.36.211)
```

**Comment by floam** [comment]
Is that a commercial NAS device or a standard linux box on the other end? Linux should be slow but does locking.

**Comment by albertz** [comment]
Not exactly sure. I remember a discussion with one of our admins where he talked about ZFS on Linux on some of our file servers. But this problem with the strange behavior of Fish also happened much earlier for me, since over a year now or so. For a very long time, I used some Git checkout with a few own modifications and I thought that I just had back luck with the Git revision I was based on. But now as I switched to Fish 2.2.0 (installed via Linuxbrew), it seems like the problem is still there.

**Comment by floam** [comment]
I doubt they would set you up for that knowingl. If your ~ is an NFS mount over the Internet and it doesn't do locking pretty much that's crazy, other stuff will break besides fish I should think. I wouldn't know what to do to see if the other side supports locking if I sat at your machine though.

Lockless makes sense for certain database configurations over a local network.

**Comment by krader1961** [comment]
Any new info, @albertz? We can try to make fish behave better when faced with remote filesystem failures (assuming that's the root cause of this issue) but we'll need more information. Best would be a way to reproduce the problem such as by making $HOME a NFS mounted directory then blocking traffic to/from the NFS server. Alternatively, obtaining a syscall trace by running `strace` against your shell might shed light on what's going on. In particular if there are syscall failures that fish isn't handling very well.

**Comment by krader1961** [comment]
@albertz Feel free to reopen this if you are able to provide additional information.
