### ISSUE TITLE
Document no clobber redirection support

### ISSUE THREAD

**Issue by ijanos** [fish-shell/fish-shell#2812]
noclobber is a feature available in bash and zsh, that prevents existing files being overwritten with the > operator. 

I think this a great ergonomic feature and it fits nicely into the mindset of fish shell. And I think it should be enabled by default.

**Comment by krader1961** [comment]
I vote no but let's see what others think. The one time I tried the feature long ago I found it more annoying than helpful. I found myself using the override syntax after a couple of days which caused me to disable the feature. Too, the philosophy of fish is to avoid configurable behaviors such as this unless there is a truly compelling reason.

**Comment by ridiculousfish** [comment]
fish already has this. `echo foo >? file.txt` is a no-clobber redirection.

**Comment by ridiculousfish** [comment]
It looks like this was never documented.

**Comment by ijanos** [comment]
Is there a way to make it default?

**Comment by ridiculousfish** [comment]
No way!

**Comment by ijanos** [comment]
Maybe I wasn't clear. Can I create something similar to an alias that will use `>?` when I type `>`  in the interactive shell.

**Comment by rumpelsepp** [comment]
an abbreviation should work. https://fishshell.com/docs/current/commands.html#abbr

**Comment by floam** [comment]
abbr.fish:
```
		# ensure the key contains at least one non-space character
		if not string match -qr "\w" -- $key
			printf ( _ "%s: abbreviation must have a non-empty key\n" ) abbr >&2```

It's not going to match a suitable key and value to change the behavior, for starters.

**Comment by zanchey** [comment]
Abbreviations can use non-string keys but they're not expanded except in the command position.
