### ISSUE TITLE
Referring to characters with values of HIGH/LOW SURROGATES (not printing them) causes Wide character ... has no narrow representation in all locales

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#2815]
Going through the character width numbers in the attachment I posted as an attachment on https://github.com/fish-shell/fish-shell/issues/2484#issuecomment-195464283, I was curious to see that one chunk of the output the script was suggesting the Terminal had moved the cursor 3 columns over for them, which was pretty curious. Actually it was probably just what it recorded after having caused a problem for fish.

It's the group starting at U+D800, HIGH and LOW SURROGATES ending at U+DFFF. They have no narrow representations, that is _true_.

Just typing \UD800 in to the terminal causes a number of error messages. Until a user hits enter there shouldn't be dangerous numbers or things they need to be concerned with, and operations like just piping the data to a file could work.

<img width="572" alt="screenshot 2016-03-11 at 6 06 02 pm" src="https://cloud.githubusercontent.com/assets/291142/13720030/fa30a656-e7b3-11e5-8063-b1908b4f9d80.png">

Not sure if this is hitting a sanity check or if got handled somewhere and may place it in an inconsistent state. Based on the number of outputs I guess the former. Only source code referring to these numbers specifically is in PCRE2 test code, where it appears to be checking for ranges of acceptable output.

**Comment by floam** [comment]
Neat, starting a new new fish session now and typing '\' causes it too, thought it's not what got printed for the autosuggestion. Got evaluated somewhere? 
<img width="493" alt="screenshot 2016-03-11 at 6 45 08 pm" src="https://cloud.githubusercontent.com/assets/291142/13720284/6af365ae-e7b9-11e5-9753-b63925e5817d.png">

It shows the prompt a time in the middle there but that is just it repeating the display of that for some reason. mid-error. entered '\' with the prompt at the top of the screen.

**Comment by floam** [comment]
I've cleaned it out of my history. Notice that this also interestingly seemingly caused the first empty path keys I've seen in my fish_history in quite a while FWIW.
[hist.txt](https://github.com/fish-shell/fish-shell/files/170242/hist.txt)

**Comment by krader1961** [comment]
> Not sure if this is hitting a sanity check or if got handled somewhere and may place it in an inconsistent state.

It is not a fish code sanity check. It's the libc support for Unicode correctly pointing out that a value in the range \xD800 thru \xDFFF has no meaning in a unicode aware locale (e.g., en_US.UTF-8) in isolation; i.e., not considering adjacent characters. See https://en.wikipedia.org/wiki/UTF-16

> ... and operations like just piping the data to a file could work.

That is unlikely since invalid surrogate pairs will produce unexpected behavior. Nonetheless, I do agree that fish should handle these characters in a more intelligent manner.

Note that I've explicitly labeled this an "enhancement" rather than a "bug" because it is an extreme corner case that 99.9999% of users will never notice.

**Comment by floam** [comment]
OK. But I think it's a (very rare) bug.

**Comment by floam** [comment]
Why does simply typing a `\U` literal cause these (perhaps reasonable) errors prior to evaluation?

**Comment by faho** [comment]
I've now simply moved the message from a warning to the "char-encoding" log class.
