### ISSUE TITLE
Multi-line prompt not clearing correctly upon resizing vte-based terminal emulators

### ISSUE THREAD

**Issue by ixjlyons** [fish-shell/fish-shell#2816]
When using a multi-line fish prompt and a gtk3 vte-based terminal emulator (e.g. termite, gnome-terminal), the prompt gets copied/mangled when resizing the emulator horizontally.

### Reproduction Steps:

1. Use a multi-line `fish_prompt`, such as: `printf '%s@%s\n$ ' (whoami) (hostname)`
2. Run fish in a vte-based emulator (note: vte based on gtk3 -- issue doesn't seem to be reproducible on gtk2-based emulators like xfce's emulator)
3. Resize the window horizontally to make it smaller (note: it doesn't have to be smaller than the length of the prompt)

### Expected behavior:

Unless the resize causes the emulator window to become smaller than the prompt, I would expect resizing to not affect the shell prompt at all.

### Observed behavior:

Here is a simple example using vte's `testvte` program with fish and zsh, showing the copying of the prompt upon window resize slightly with fish:

![testvte-resize](https://cloud.githubusercontent.com/assets/943602/13730736/db8be60e-e914-11e5-8f9d-30f47af0899a.png)

I use a tiling window manager, and the effect is amplified each time a new horizontal split is created, otherwise the pictured behavior wouldn't be all that much to complain about.

### Additional information:

I filed a bug report against vte [here](https://bugzilla.gnome.org/show_bug.cgi?id=763390). As you can see, the vte developer blames fish for this behavior. See comment 4 for his explanation of the potential cause and a possible solution. I found that the `\r \r` mentioned is implemented [here in `src/screen.cpp`](https://github.com/fish-shell/fish-shell/blob/10f3ea0008a4563c2baa4f29954c285d2d53d7dc/src/screen.cpp#L1447-L1450).

I have implemented his suggestion (replace `\r \r` with `\e[K`), which you can see [here](https://github.com/ixjlyons/fish-shell/commit/0fecba9bedbc219c35a2175d0a69ed2fa502587a). This does seem to work, but I don't understand it well enough to know if it will cause undesired side effects, hence no pull request.

**Comment by ridiculousfish** [comment]
Let's track in #2320.  Thanks for filing this!
