### ISSUE TITLE
directory jump like with Z

### ISSUE THREAD

**Issue by lee2sman** [fish-shell/fish-shell#2817]
What's the best way to be able to do directory jumping like [Z](https://github.com/rupa/z) does? 

Hello, I really love Fish shell and have been using it for a little less than year. I'm wondering if there's a built-in way to implement directory jumping, similar to [Z](https://github.com/rupa/z), or would be interested in hearing if anyone's installed Z directly. How well does it work with fishshell? 

I'm running fish installed with homebrew on os x.

**Comment by ridiculousfish** [comment]
Tried https://github.com/sjl/z-fish?

**Comment by lee2sman** [comment]
THANK YOU! Didn't find this in a search before! Appreciated.
