### ISSUE TITLE
Non C++11 compliant u_int (instead of uintX_t) in env_universal_common.cpp

### ISSUE THREAD

**Issue by eugenesvk** [fish-shell/fish-shell#2821]
When trying to build an updated version of fish under MSYS2 on Windows 10 I've encountered an error about `u_int` not being declared in this scope (see [log](https://github.com/Alexpux/MSYS2-packages/issues/204)). After some googling I realized it might be just a wrong declaration of a variable in this [line](https://github.com/fish-shell/fish-shell/blob/master/src/env_universal_common.cpp#L132), changed `u_int` to `uintmax_t` per [C++](http://www.cplusplus.com/reference/cstdint/) and it built just fine after that.
No idea really if it makes any difference on other systems, but might it be better to change this universally?

**Comment by ridiculousfish** [comment]
I think that variable should be `uid_t` instead of `uint_t`

**Comment by eugenesvk** [comment]
Would you please confirm which one it should be so that I know what to change it to? Just don't want to end up with a wrong var in my build that might be causing some weird problems.

**Comment by krader1961** [comment]
@ridiculousfish is probably correct that should be **uid_t** given the context. It's also the only place in the code to use that typedef. The **u_int** typedef is a non-standard variant of **uint** common to BSD based systems.
