### ISSUE TITLE
I'm having problems with a few of the custom prompts on OS X

### ISSUE THREAD

**Issue by Xavion** [fish-shell/fish-shell#2826]
I thought I should let you know that a few of the custom prompts are buggy on OS X.  Specifically, I get unwanted output when launching new fish sessions.  I'm using fish v2.2.0 via Homebrew on El Capitan (v10.11.3).

When I use "Nim", I get the following:
`type: Could not find 'acpi'`

I fixed it by changing line 49 of "fish_prompt.fish" to:
`if type acpi > /dev/null 2>&1`

When I use "Robbyrussell", I get the following:
```
fish: Unknown command 'hg'
fish: hg summary >/dev/null ^/dev/null
      ^
in function '_is_hg_repo'
	called on standard input

in function '_repo_type'
	called on line 2 of file ~/.config/fish/functions/fish_prompt.fish

in command substitution
	called on line 0 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input
```

When I use "Terlar", I get the following:
```
fish: Unknown command 'hg'
/usr/local/Cellar/fish/2.2.0/share/fish/functions/__fish_hg_prompt.fish (line 1): hg branch ^/dev/null
                                                                                  ^
in command substitution
	called on line 22 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/__fish_hg_prompt.fish

in function '__fish_hg_prompt'
	called on line 24 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input
```

I haven't bothered to fix the code for these last two prompts.  All of the other ones seem to work fine on my system.

**Comment by krader1961** [comment]
Someone should look for all statements that look like "if type some-command > /dev/null" since it is clear the error message should be suppressed. The correct solution is to add the "-q" option and drop the redirection.

**Comment by faho** [comment]
Thanks, it should now be fixed. The terlar prompt already uses our helper functions, so it should already work there.
