### ISSUE TITLE
Feature request: invoke vim (or EDITOR) to edit a shell command

### ISSUE THREAD

**Issue by ferriff** [fish-shell/fish-shell#2833]
This is a very useful feature of vi-mode found in other shells, which I did not find listed in the issues.
And it should calm down people expecting a shell to be a full text editor ;) Of course vi-features will be missing from fish, and rightly so. If you need them, just invoke the fully-fledged vim and enjoy.

**Comment by faho** [comment]
This is a duplicate of #1215, which also features some functions to do this.
