### ISSUE TITLE
Alt-Enter keybinding broken

### ISSUE THREAD

**Issue by muflax** [fish-shell/fish-shell#2834]
Recent git versions broken Alt-Enter for inserting a newline (eg in funced), probably when handling \n and \r as separate things was introduced.

The default key bindings in "fish_default_key_bindings.fish" have

    bind $argv \e\n "commandline -i \n"

and Alt-Ctrl-J still works. If I also define 

    bind $argv \e\r "commandline -i \n"

then Alt-Enter works again. 

(I don't know if there are any other broken key bindings for the same reason, I only noticed this one.)

**Comment by krader1961** [comment]
Good catch. I must have searched for occurrences of " \n" (note the leading space) because otherwise I don't see how I could have missed that binding while simultaneously finding the "execute" bindings that needed \r equivalents. Fix on the way.
