### ISSUE TITLE
Program description

### ISSUE THREAD

**Issue by maandree** [fish-shell/fish-shell#284]
Programs with a description in man section 1 are described in completion when programs are suggested.
Section 6 (games and other amusement) is also fit for this.
If have not tested but section 8 (admin commands) are also fit for this.

**Comment by faho** [comment]
Isn't this already the case? If I enter `man man<TAB>`, I get:

>man  (1: an interface to the on-line reference manuals)  

>manconv  (1: convert manual page from one encoding to another)  

>manpath  (1: determine search path for manual pages)

>man-pages  (7: conventions for writing Linux man pages) 

>mandb       (8: create or update the manual page index caches)

**Comment by faho** [comment]
I'm assuming this is already fixed. If not, please yell at me.
