### ISSUE TITLE
cygwin, pipe not working

### ISSUE THREAD

**Issue by Holt59** [fish-shell/fish-shell#2846]
I am trying to use fish-shell in cygwin, but pipes do not work correctly: I have to way till the end of the first program to get the second running.

### Reproduction Steps:

Typically this:

```
 function do_it
     for in in (seq 1 20)
         echo "Hello"
         sleep 1
     end
 end

~> do_it | cat
```

I get no output for 20 seconds, and then all the `"Hello"` are printed at once.

### Additional information:

When using fish on my Debian machine, everything is fine. Also, piping works normally in cygwin bash (I get one `"Hello"` everything seconds with the above command).

---
Fish version: 2.2.0

Operating system: Windows + Cygwin

Terminal or terminal emulator: xterm-256color (from cygwin)

**Comment by krader1961** [comment]
Try it again on you linux system. You should see the same behavior you're seeing on cygwin. I certainly do. This is because the output of functions is fully buffered. See issue #1396.
