### ISSUE TITLE
invoking commands reading from standard input in the fish_prompt function causes fish hanging

### ISSUE THREAD

**Issue by imcaizheng** [fish-shell/fish-shell#2848]
### Reproduction Steps:

Invoke the cat command without arguments in the fish_prompt function.

### Observed behavior:

fish hangs when starting a new terminal.

Fish version: fish, version 2.2.0-486-g1a3bcf6-dirty

### Digression:

I found that `fish --version >fish_version` doesn't work. I got an empty file.
Seems that the output from `fish --version` is written to stderr rather than stdout.

**Comment by krader1961** [comment]
Pointing a gun at your foot and pulling the trigger will also cause pain. There are an infinite number of ways you can make any shell, not just fish, behave in weird ways. There is no practical way to protect against all of them or even this specific instance. We could, I suppose, arrange for stdin to be opened on */dev/null* when running `fish_prompt` but that seems like a rather expensive thing to do just to keep people from shooting themselves in the foot.

Regarding `fish --version` writing to stderr that is definitely wrong. I'll fix it.
