### ISSUE TITLE
Turn on leak detection

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#2851]
[fish has some memory leaks](https://github.com/fish-shell/fish-shell/pull/2849). Once these are fixed, it would be a good idea to turn on leak detection in the Travis CI builds to avoid introducing any more.

This can be done by setting `detect_leaks` to 1 in `.travis.yml`.

**Comment by anordal** [comment]
Thanks for bringing this up! Do you think I should update that pull request with `detect_leaks=1`?

**Comment by krader1961** [comment]
> Do you think I should update that pull request with detect_leaks=1?

My preference is to enable automatic leak detection in a separate commit only once the code is known to be in a good state.
