### ISSUE TITLE
history not working

### ISSUE THREAD

**Issue by nonkr** [fish-shell/fish-shell#2853]
history not working just type ``history``, which show errors:
```
history: Invalid combination of options,
Use --search with either --contains or --prefix
```

**Comment by zanchey** [comment]
@nonkr, can you tell us what version of fish you are running, where you installed it from, and what your operating system is?

(Incidentally, did the issue template appear when you created this issue? It's supposed to have suggestions for all these questions.)

**Comment by nonkr** [comment]
![image](https://cloud.githubusercontent.com/assets/1668287/14014224/45142048-f1ec-11e5-93a5-df1ba5d735ac.png)

It always appears. For now, I create the ``~/.config/fish/functions/history.fish`` and rewrite the print process to avoid it
![image](https://cloud.githubusercontent.com/assets/1668287/14014238/615554c0-f1ec-11e5-8688-1be76fe86ead.png)

**Comment by floam** [comment]
Does it go away if you use that 2.0.0 package that you are showing there instead of 1.23.1? How about if you try [something newer](http://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A2&package=fish) available for CentOS 6?

**Comment by nonkr** [comment]
Thx a lot, I change the yum repositories and reinstall it, now fish version is 2.2.0, and is ok!
I think something wrong with the rpm package from rpmforge
![image](https://cloud.githubusercontent.com/assets/1668287/14015232/89eb080c-f1f2-11e5-8b9b-4c5d9af9d03d.png)
it show the fish version is 2.0.0r2, but when I installed it, the truly version is 1.23.1
