### ISSUE TITLE
Fish command prompt takes very long to appear

### ISSUE THREAD

**Issue by marmistrz** [fish-shell/fish-shell#2854]
I set up `fish` as my main shell with `chsh`. Now I experience it takes very long until the prompt appears.

### Reproduction Steps:

1. Launch terminal
2. The following text appears: 

> Welcome to fish, the friendly interactive shell
> Type help for instructions on how to use fish

### Expected behavior:

The command prompt appears immediately

### Observed behavior:

It takes about 10 seconds for the command prompt to appear

### Additional information:

I'm not sure if it'll last a reboot.
After typing any command, it takes even longer for the command prompt to appear. Probably some function takes a long time...

---
Fish version: 2.2.0

Operating system: Arch Linux x64

Terminal or terminal emulator: Terminator, Guake

**Comment by zanchey** [comment]
I wonder if it is your prompt function that is taking a long time. What does the output of `functions fish_prompt` look like?

**Comment by marmistrz** [comment]
```
function fish_prompt --description 'Write out the prompt'
	set -l home_escaped (echo -n $HOME | sed 's/\//\\\\\//g')
   set -l pwd (echo -n $PWD | sed "s/^$home_escaped/~/" )
   set -l prompt_symbol ''
   switch $USER
       case root toor; set prompt_symbol '#'
       case '*';  set prompt_symbol '$'
   end
   printf "[%s@%s %s%s%s]%s " $USER (hostname -s) (set_color $fish_color_cwd) $pwd (set_color normal) $prompt_symbol
end
```

**Comment by faho** [comment]
Is it just the first prompt in a given terminal that is slow, or the first prompt on a boot, or _every_ prompt?

In any case, it would be nice to have all your fish configuration - config.fish and all functions you made. (Btw `sed` uses the first character after a command as the separator, so you can use `sed 's:/:\\/:g'`, which doesn't look quite as awkward)

**Comment by marmistrz** [comment]
Every prompt. 
My prompt is just some modified built-in prompt, hence so awkward ;) I just removed some other sed.

I have no other functions, no `config.fish`, only `fishd.arch`:

```
# This file is automatically generated by the fish.
# Do NOT edit it directly, your changes will be overwritten.
SET __fish_init_1_50_0:\x1d
SET fish_color_autosuggestion:555\x1eyellow
SET fish_color_command:005fd7\x1epurple
SET fish_color_comment:red
SET fish_color_cwd:green
SET fish_color_cwd_root:red
SET fish_color_error:red\x1e\x2d\x2dbold
SET fish_color_escape:cyan
SET fish_color_history_current:cyan
SET fish_color_match:cyan
SET fish_color_normal:normal
SET fish_color_operator:cyan
SET fish_color_param:00afff\x1ecyan
SET fish_color_quote:brown
SET fish_color_redirection:normal
SET fish_color_search_match:\x2d\x2dbackground\x3dpurple
SET fish_color_selection:\x2d\x2dbackground\x3dpurple
SET fish_color_valid_path:\x2d\x2dunderline
SET fish_greeting:Welcome\x20to\x20fish\x2c\x20the\x20friendly\x20interactive\x20shell\x0aType\x20\x1b\x5b32mhelp\x1b\x5b30m\x1b\x28B\x1b\x5bm\x20for\x20instructions\x20on\x20how\x20to\x20use\x20fish
SET fish_key_bindings:fish_default_key_bindings
SET fish_pager_color_completion:normal
SET fish_pager_color_description:555\x1eyellow
SET fish_pager_color_prefix:cyan
SET fish_pager_color_progress:cyan
```

**Comment by krader1961** [comment]
BTW, you can do that $HOME substitution much more cheaply, without having to fork two external commands, if you're using fish built from git head (i.e., > 2.2.0). From the `mcd` command I recently announced:

```
set -l pwd $PWD
set -l home_dir (string match -r "$HOME(/.*|\$)" "$pwd")
if set -q home_dir[2]
    set pwd "~$home_dir[2]"
end
```

But that is unlikely to fix the slowness your seeing since those two sed invocations should add no more than a 100 ms to the time it takes to produce the prompt. So, like @faho, said I think we're going to need more details about your configuration. For example, have you defined any event handlers for `fish_prompt`, `fish_preexec`, or `fish_postexec`?

**Comment by marmistrz** [comment]
@krader1961 see my post above ^^^^ no other functions defined.

**Comment by krader1961** [comment]
What happens if you just type `fish_prompt` followed by the [enter] key? Does the prompt appear quickly or after several seconds have elapsed?

**Comment by marmistrz** [comment]
several secs again

**Comment by krader1961** [comment]
Okay, then execute each statement, one at a time, by cutting and pasting them into your interactive session. Which ones are really slow to complete? If your fish_prompt function is really as you showed us three hours ago it would have to be the first two `set` statements where you invoke `sed`. Also, show us the output of `functions -n`.

**Comment by faho** [comment]
>Okay, then execute each statement, one at a time, by cutting and pasting them into your interactive session.

A slightly less manual way of doing this is `fish --profile prompt.prof -ic 'fish_prompt; exit'; sort -nk 2 prompt.prof ` - though this will print _all_ your initialization stuff, it shouldn't matter in this case.

**Comment by marmistrz** [comment]
```
$ fish --profile prompt.prof -ic 'fish_prompt; exit'; sort -nk 2 prompt.prof
[marcin@arch ~]$ Time	Sum	Command
5	5	--> for x in $__fish_added_user_paths...
5	5	--> for x in $fish_user_paths[-1..1]...
8	8	-> function __fish_load_path_helper_paths...
8	8	-> function __fish_on_interactive --on-event fish_prompt...
8	8	--> not set -q fish_function_path
8	8	--> set -q XDG_DATA_HOME
9	9	-> function __fish_default_command_not_found_handler...
9	9	--> set -l x
10	10	-> function __fish_command_not_found_handler --on-event fish_command_not_found...
10	10	--> set -q XDG_CONFIG_HOME
11	11	-> for pathfile in /etc/paths.d/* ...
11	11	--> set -e __fish_added_user_paths
11	11	--> set prompt_symbol '$'
3	11	-> if set -q XDG_DATA_HOME...
12	12	-> function . --description 'Evaluate contents of file (deprecated, see "source")' --no-scope-shadowing...
12	12	-> set -e __fish_tmp_path
14	14	-> test -r /etc/paths
4	14	-> if set -q XDG_CONFIG_HOME...
16	16	-> function __fish_reconstruct_path -d "Update PATH when fish_user_paths changes" --on-variable fish_user_paths...
17	17	--> function fish_prompt --description 'Write out the prompt'...
17	17	-> set -l prompt_symbol ''
18	18	-> function fish_sigtrap_handler --on-signal TRAP --no-scope-shadowing --description "Signal handler for the TRAP signal. Launches a debug prompt."...
18	18	--> not set -q fish_complete_path
18	18	-> set -l userdatadir ~/.local/share
22	22	-> functions -e __fish_load_path_helper_paths
22	22	--> test -d /usr/xpg4/bin
23	23	----> set -q USERDOMAIN
13	24	-> switch $USER...
24	24	--> status --is-login
3	25	-> if test -d /usr/xpg4/bin...
26	26	-> set -g IFS \n\ \t
26	26	-> set -l configdir ~/.config
3	27	-> if status --is-login...
29	29	--> set fish_function_path $configdir/fish/functions    $__fish_sysconfdir/functions    $__fish_datadir/functions
29	29	--> set -xg PATH $local_path
30	30	--> not contains $__fish_datadir/completions $fish_complete_path
31	31	--> set_color normal
32	32	-> set -g __fish_tmp_path $PATH
33	33	-> set -xg PATH $__fish_tmp_path
3	33	-> if not contains $__fish_datadir/completions $fish_complete_path...
35	35	> exit
35	35	--> set -l local_path $PATH
42	42	--> not contains $__fish_datadir/functions $fish_function_path
42	42	--> set fish_complete_path $configdir/fish/completions  $__fish_sysconfdir/completions  $__fish_datadir/vendor_completions.d  $__fish_datadir/completions $userdatadir/fish/generated_completions
5	42	-> if not set -q fish_function_path...
3	45	-> if not contains $__fish_datadir/functions $fish_function_path...
6	66	-> if not set -q fish_complete_path...
110	133	---> source /usr/share/fish/functions/hostname.fish
124	151	> builtin source /etc/fish/config.fish 2>/dev/null
73	167	-> __fish_reconstruct_path
154	171	-> source /home/marcin/.config/fish/functions/fish_prompt.fish
234	234	--> set_color $fish_color_cwd
370	370	> builtin source /home/marcin/.config/fish/config.fish 2>/dev/null
632	1310	> builtin source /usr/share/fish/config.fish 2>/dev/null
2143	2143	--> echo -n $PWD | sed "s/^$home_escaped/~/"
75	2218	-> set -l pwd (echo -n $PWD | sed "s/^$home_escaped/~/" )
2421	2421	--> echo -n $HOME | sed 's/\//\\\\\//g'
70	2491	-> set -l home_escaped (echo -n $HOME | sed 's/\//\\\\\//g')
10011707	10011840	--> hostname -s
241	10012346	-> printf "[%s@%s %s%s%s]%s " $USER (hostname -s) (set_color $fish_color_cwd) $pwd (set_color normal) $prompt_symbol
94	10017361	> fish_prompt
```

**Comment by krader1961** [comment]
Notice that the `hostname -s` is taking ten seconds:

> 10011707    10011840    --> hostname -s

Also, even if it is much faster you still don't want to be invoking potentially expensive commands in your fish_prompt function. Especially for information, like the hostname, which doesn't change. The standard trick is to add something like the following to the top of your fish_prompt function to gather this information just once:

```
    # Just calculate this once, to save a few cycles when displaying the prompt
    if not set -q __fish_prompt_hostname
        set -g __fish_prompt_hostname (hostname | cut -d . -f 1)
    end
```

Then use `$__fish_prompt_hostname` where you currently have `(hostname -s)`.

**Comment by faho** [comment]
>10011707    10011840    --> hostname -s

So for some reason `hostname -s` takes 10s on your system. That's about 2000 as long as it takes on mine, and it doesn't seem like my hardware is that much more powerful. Do you have some more complicated hostname setup (domain stuff)? Have you also [set your hostname in /etc/hosts](https://wiki.archlinux.org/index.php/Network_configuration#Set_the_hostname)?

> Especially for information, like the hostname, which doesn't change. The standard trick is to add something like the following to the top of your fish_prompt function to gather this information just once

That's nice in general, but in this case it would still mean fish startup takes 10s.

**Comment by krader1961** [comment]
> That's nice in general, but in this case it would still mean fish startup takes 10s.

Yep, which is why I also wrote "Also, even if you manage to make it much faster...." :-) There is definitely something FUBAR with the DNS, YP, NIS or whatever handles hostname resolution on his system.

**Comment by marmistrz** [comment]
After setting it up in /etc/hosts, I get the wrong hostname... :( But immediately :)

```
#
# /etc/hosts: static lookup table for host names
#

#<ip-address>	<hostname.domain.org>	<hostname>
127.0.0.1	localhost.localdomain	localhost arch
::1		localhost.localdomain	localhost arch

# End of file
```

```
$ hostname -s
localhost
```

**Comment by faho** [comment]
That's how it behaves for me too.

It seems that `hostname -s` picks the first short name that is contained in the fqdn (the "localhost.localdomain"), so the ordering doesn't matter.

So you might want to do one of the following:

- Remove the "-s" - this is what I picked, and it seems to work everywhere I use it (though I have a simple setup with just a couple of linux-based machines)

- Set the fqdn to e.g. `arch.localdomain`

- Ditch `hostname` for `hostnamectl --transient` - this is systemd-specific

**Comment by krader1961** [comment]
We're far outside the realm of anything having to do with fish at this point. Is this a personal machine or a corporate computer? If the latter you should contact your company's IT staff. If the former we might be able to help you fix your hostname command behavior if you provide more details about your network. But the reality is you'll probably get better advice asking on a Arch Linux support forum.

**Comment by marmistrz** [comment]
Yep, closing
@faho: thanks!

**Comment by jamischarles** [comment]
Just successfully profiled a perf issue by using the command up above. Took a while to find the thread. Would love a "how do I profile fish startup time" in the FAQ or similar (assuming it doesn't exist yet. 👍

**Comment by gybfefe** [comment]
In my case only bash: command not found takes a long time to return prompt after a mistyped command. It takes about half minute to resolve the situation, rather rude punishment for clumsy fingers, we should say so.
