### ISSUE TITLE
Get Github to add fish to their supported languages.

### ISSUE THREAD

**Issue by onodera-punpun** [fish-shell/fish-shell#2861]
It's kinda annoying that all my fish scripts shows up as either shell, or nothing at all, I don't really know how languages on github are handled, but even languages like brainfuck or relatively new languages like red are supported.

**Comment by krader1961** [comment]
If the file ends with a `.fish` extension it should be correctly treated with respect to syntax highlighting. For comments in issues and pull-requests specify `fish` as the language in literal code blocks; e.g.,

&#96;&#96;&#96;fish
if true
  echo yes
end
&#96;&#96;&#96;

Github uses Linguist for this and  [support for fish](https://github.com/github/linguist/tree/master/samples) was added three years ago.

**Comment by onodera-punpun** [comment]
Oh sorry, I didn't know about this since I never end my files with `.fish`. However, it seems like github is also capable of detecting the language by shebang or something else in the file, see this repository for example: https://github.com/onodera-punpun/prt-utils-extra, this is a also a good example: https://github.com/onodera-punpun/bin, note how the vast majority of the scripts in bin are fish scripts, yet it only shows shell in the language bar.

**Comment by krader1961** [comment]
I don't know if Linguist has shebang detection. I haven't needed to look into its behavior because in my projects I always use an appropriate extension (e.g., sh, py, fish, etc.) then strip the extension when installing the scripts. It's possible the shebang detection for fish scripts is missing or incorrect (assuming Linguist does shebang detection).

**Comment by krader1961** [comment]
Also, as best I can tell all shells (e.g., sh, zsh, ksh, fish, etc) are classified as "Shell" in the language breakdown. That appears to be intentional.

**Comment by krader1961** [comment]
The [main linguist page](https://github.com/github/linguist) doesn't say anything about shebang detection. But it does describe two ways to force linguist to associate a specific language with a file: *.gitattributes* and editor modelines.

**Comment by ixjlyons** [comment]
See [linguist issue 2713]. Shebang detection is supposed to work for fish if the file is executable, but it does look like the files in the bin repo you linked to are executable...

[linguist issue 2713]: https://github.com/github/linguist/issues/2713

**Comment by onodera-punpun** [comment]
Thanks @ixjlyons, I opened a new issue: https://github.com/github/linguist/issues/2913

@krader1961 If all else fails I'll use .gitattribues :)

**Comment by krader1961** [comment]
The linguist [shebang detection module](https://github.com/github/linguist/blob/master/lib/linguist/shebang.rb) looks like it should be classifying your files as "fish" based on your shebang lines. And the couple of your files I looked at have the executable attribute. So I don't see any reason for it not to work. You'll probably need to ask for help over at the Linguist project. Do let us know what you learn and if there's something that needs to be changed vis-a-vis the support for fish by the Linguist project.

**Comment by krader1961** [comment]
Looks like the *languages.yml* file was missing an important piece of information and that has been corrected by https://github.com/github/linguist/pull/2995/.
