### ISSUE TITLE
fish_config tries to open html file from a nonexistent path

### ISSUE THREAD

**Issue by vegberg** [fish-shell/fish-shell#2862]
When running `fish_config`, it tries to open this path: `/Z:/home/vegberg/.cache/fish/web_config-3YE5OM.html`, which is nonexistent.

[Here](https://asciinema.org/a/0vhormq53oshie03v0edn82rv) is an asciinema recording of it.
In addition, this message box appears upon exiting fish_config:
![](http://i.imgur.com/ExAr2u6.png)  

---
Fish version: fish, version 2.2.0 (installed through Ubuntu's repositories)
Operating system: Ubuntu 15.10 wily
Terminal or terminal emulator: XFCE Terminal

**Comment by faho** [comment]
What is your $XDG_CACHE_HOME set to? Try `prinf "%s\n" $XDG_CACHE_HOME` - this allows us to see how it's divided into elements - each element should be a new line.

**Comment by krader1961** [comment]
I don't think the problem is with his $XDG_DATA_CACHE var having multiple values. Notice the first message after typing `fish_config` is the expected

```
Web config started at 'file:///home/vegberg/.cache/fish/web_config-X1Q4V2.html'.
```

Notice the very weird errors that follow:

```
fixme:exec:SHELL_execute flags ignored: 0x00000100
```

What seems to be happening is fish is trying to run a MS Windows browser via the Wine environment.

@vegberg: You've done something very unusual in setting up your Linux system. It looks like you've made a Wine based browser your default browser. Any idea how that happened and why your system is setup that way?

**Comment by faho** [comment]
That should teach me to watch the video!

And that explains the "Z:" part - by default, wine "mounts" the unix filesystem root (the path "/") as the windows "z:" drive.

**Comment by vegberg** [comment]
```
~ 
❯ printf "%s\n" $XDG_CACHE_HOME

                                                                                
~ 
❯ 
```
`$XDG_CACHE_HOME` appears to be empty.

![Screenshot of Preferred Applications](http://i.imgur.com/ZV5rObF.png)
Google Chrome is set as the default browser and opening a URL (e.g. http://google.com/) through `xdg-open`and `x-www-browser` opens the URL in Chrome.

**Comment by faho** [comment]
@vegberg:

Please try

```python
import webbrowser
webbrowser.open('https://github.com')
```

in a python. It's possible it doesn't use the same database.

**Comment by vegberg** [comment]
Running `python -c "import webbrowser; webbrowser.open('https://github.com/')"` works as expected, opening GitHub in a new Chrome tab.
This works with both Python 2.7.10 and 3.5.0+.

**Comment by floam** [comment]
Oh no, don't have him try to open a `https` url with the Python module and expect it to to do the same thing - because what fish does at that point situation for him is using his configured app for opening .html files. It's a file:// path. I'm guessing it's somehow falling back to wine/iexplorer.exe or something somehow.

**Comment by floam** [comment]
(I believe it is the behavior described in the documentation: 

[`webbrowser.open(url, new=0, autoraise=True)`](https://docs.python.org/2/library/webbrowser.html#webbrowser.open)
```

Display url using the default browser. If new is 0, the url is opened in the same browser
window if possible. If new is 1, a new browser window is opened if possible. If new is 2,
a new browser page (“tab”) is opened if possible. If autoraise is True, the window is raised if
possible (note that under many window managers this will occur regardless of the setting of this variable).

**Note that on some platforms, trying to open a filename using this function, may
work and start the operating system’s associated program. However, this is neither
 supported nor portable.**
```

**Comment by floam** [comment]
Either it's that or the stupid webbrowser.py is someone resolving his browser to some .exe file in _synthesize() or something in webbrowser.py.

**Comment by vegberg** [comment]
I tried opening a test html file through Python and `xdg-open`, and now I get `fixme:exec:SHELL_execute flags ignored: 0x00000100` again.

Do you have any ideas to resolve this?

**Comment by floam** [comment]
Do you have `mimeopen`? If it's using that fallback try `mimeopen -d file.html` it will prompt you to pick a new app. Otherwise I think your Linux destkop environment should et you do this in the settings or right in in xfce/nautilus/kde after navigation to such a file?

**Comment by floam** [comment]
If it's not using that fallback you need to [find a .desktop file for your desired app.](http://unix.stackexchange.com/questions/168947/how-to-change-my-file-url-association-across-all-my-dm-wm-without-using-the-gui)

**Comment by vegberg** [comment]
Apparently the default way to open HTML files was through Wine's browser (which is really odd how that was set to default in the first place). Running mimeopen didn't seem to do much for setting the default application, but it did work setting the default through xdg-mime.

Thank you!
