### ISSUE TITLE
Is there an option to pass on the original exported variable to child processes in functions after "local"  re-use?

### ISSUE THREAD

**Issue by da99** [fish-shell/fish-shell#2864]
I've read the fish docs on set and searched through fish-shell github issues and so far I don't see any option for set/export/etc to say: I want to use this local variable in this function, but pass on the original exported variable to all child processes.  For example:

```fish
function re_define
  my child process  # gets "original"
  set -l MY_VAR "new val"
  my child process  # gets nothing/null string, but should have gotten "original"
end

set -x MY_VAR "original"
re_define
```

Fish seems to do something similar of most shells. So far I've only found [mksh](https://www.mirbsd.org/mksh.htm) to pass on the original exported value to a child process after it has been "localized" by the function.

In a real-world scenario, I would not know what ENV variable the child process uses. So I might end up using a local variable, effectively erasing the value for the child process, causing errors.

Wouldn't this be a good option to have in `set` to help prevent clashing w/child processes and ENV variables? (Unless there is something else in the awesome Fish shell that helps to protect against ENV/child process name clashing.)

**Comment by ridiculousfish** [comment]
Today we have `set` options `--export` and `--unexport`. At first blush, it seems reasonable that if you don't specify either export or unexport, then you don't want to modify the environment at all. But as da99 points out, you may do this accidentally.

Some more discussion of this in #2611 - let's track in there. Thanks for filing this!
