### ISSUE TITLE
Why is Fish's psub so simple and effective compared to other shells?

### ISSUE THREAD

**Issue by da99** [fish-shell/fish-shell#2867]
The `psub` function works great for my needs. The implementation is simple and quite elegant. 

Fish's psub essence from: https://github.com/fish-shell/fish-shell/blob/master/share/functions/psub.fish#L49

    cat >/tmp/pipe.fish &
    echo /tmp/pipe.fish
    #     diff   (echo abc | psub )  (echo def | psub)

However, a non-Fish equivalent would not work. This would block in other POSIX-y shells:

    diff   $(echo abc | fishy.psub.sh )  $(echo def | fish.psub.sh)
    # blocks until you write to the named pipe

How does Fish get away with implementing process substitution like that?

**Comment by zanchey** [comment]
it is a mystery

I suspect it would be helpful if we could see the implementation of fish.psub.sh, as the FIFO implementation in fish doesn't actually a) work or b) get effectively used (see #1040).

**Comment by da99** [comment]
In `fishy.psub.sh`, it would be a direct translation of Fish's psub function:

      my_pipe=path/to/temp/file
      mkfifo $my_pipe
      cat > $my_pipe &
      echo $my_pipe

But, in a non-Fish shell, this would just block until output was sent to the named pipe from somewhere else.  In Fish, "it just works".

**Comment by da99** [comment]
"it is a mystery" is good enough for me.

In case anyone is curious how  Fish's process substitution can be implemented in other shells, there is this discussion (specific to `mksh`): http://unix.stackexchange.com/a/273227/42107

It's a lot trickier compared to Fish. One more way Fish stands out from the crowd.

**Comment by zanchey** [comment]
FYI, the `mkfifo` stuff in fish _does not work_ as it blocks with large enough outputs - psub always uses a temporary file.

**Comment by da99** [comment]
@zanchey Thanks for correcting me. Apologies for making you repeat yourself.

When do the temp. files `psub` creates get erased from the system? Reboot?

**Comment by zanchey** [comment]
After the pipe is closed - see the `function $funcname --on-job-exit caller` part of the `psub` function.

**Comment by da99** [comment]
Is this a unique feature to Fish? (`on-job-exit`)
I never encountered anything like that on other shells.
