### ISSUE TITLE
Add java completions

### ISSUE THREAD

**Issue by marmistrz** [fish-shell/fish-shell#2873]
In bash, when you run a class, then the completion

java -cp <completes directory, separated with slashes> package.<completes this one, separated with dots, (takes classpath into account) >

in Fish the generic completion kicks in, so you have to type the whole class name manually.

**Comment by ridiculousfish** [comment]
Looks like we don't have any java completions yet.

**Comment by marmistrz** [comment]
So we need Java completions :)

**Comment by krader1961** [comment]
Custom completions need to be written and submitted by someone motivated to do so. Like yourself, @marmistrz. We're happy to provide advice on how to do so. But without such a submission this issue will simply bit rot.
