### ISSUE TITLE
remove "doc" make target and rename "user_doc"

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2874]
The other day I wanted to verify that a change to the docs rendered correctly. So I ran `make doc` and was surprised to find the resulting web page looked nothing like that on fishshell.com. Turns out the correct command is `make user_doc`. The "doc" target is meant to build the documentation for the source code. Since it was recently decided that we would no longer require Doxygen markup of the source and have an open cleanup issue to remove it we should remove the `make doc` command. While we're at it we might as well rename the "user_doc" target to "doc".

**Comment by faho** [comment]
Personally, I don't use the current "doc" target, but IIUC it's supposed to also build the API docs, so this is related to #2795.
