### ISSUE TITLE
How to set background color of completion?

### ISSUE THREAD

**Issue by lepetitforgeron** [fish-shell/fish-shell#2878]
Ho do I set the background color of the completion? I always have this dark grey background and I don't know where it comes from. I can't find a color variable to set, that could change this background.

![bildschirmfoto 2016-03-31 um 11 36 08](https://cloud.githubusercontent.com/assets/4357576/14171839/59869d96-f735-11e5-9042-d5d9968ee0d4.png)

**Comment by faho** [comment]
From http://fishshell.com/docs/current/index.html#variables-color:

>fish_pager_color_secondary, the background color of the every second completion

**Comment by lepetitforgeron** [comment]
No, this only sets the color of every second completion. As you can see, I have done that. The color of the initial and every other completion is what I want to set.

**Comment by krader1961** [comment]
From *src/pager.cpp*:

```
int bg_color = secondary ? highlight_spec_pager_secondary : highlight_spec_normal
```

So the first, third, etc. entries use `highlight_spec_normal` which corresponds to variable `fish_color_normal`.

**Comment by krader1961** [comment]
And, yes, the documentation could be improved on this point. Patches welcome :-)

**Comment by krader1961** [comment]
No updates in over a month so I'm going to assume my answer was satisfactory.

**Comment by introom** [comment]
sorry, I didn't quite get it.

In order to change the gray background color as depicted in this pic:
http://imgur.com/a/lrwOO

what color setting should I change?

**Comment by faho** [comment]
@introom: $fish_color_search_match. We might want to change either the documentation or the behavior on that.

**Comment by introom** [comment]
@faho 
How can I change the foreground?
set fish_color_search_match 'blue'  '--background=e4e4e4'
won't make the foreground blue.

**Comment by floam** [comment]
`fish_pager_color_completion` will affect the foreground color of all items in the pager. Not certain at the moment if there's another variable set a specific highlighted foreground color, or if it's not supported yet.
