### ISSUE TITLE
Git completion on a branch when doing a force push

### ISSUE THREAD

**Issue by rocketraman** [fish-shell/fish-shell#2879]
When doing git completion, fish generally completes the branch name e.g.

    git push origin <completion here>

However, when doing a force push with a `+`, the branch completion does not work:

    git push origin +<no completion here>

---
Fish version: 2.2.0

Operating system: Fedora Linux

Terminal or terminal emulator: Konsole

**Comment by faho** [comment]
Yes, this needs to be implemented.

When it is, this should _not_ recommend all branches with a "+", but only complete branches even after a "+" and maybe give a standalone "+" with a description of "force push" or something. Everything else would cause way too many options, about half of them dangerous.
