### ISSUE TITLE
can't use ctrl+u in osx

### ISSUE THREAD

**Issue by nonkr** [fish-shell/fish-shell#2882]
can't use <kbd>ctrl-u</kbd> is osx EI Capitan10.11.4, the terminal just hangs up, I can't type anything, if I want to close the terminal, it will prompt: close the window will terminate the progress xsel.

**Comment by krader1961** [comment]
Works for me. What does `bind \cu` output? I don't quite understand what you mean by "if I want to close the terminal". Are you clicking on the red close-window button at the top of the terminal window? What terminal are you using? Apple Terminal, iTerm2, xterm, or something else?

**Comment by floam** [comment]
He means that when he tries to close the Terminal either the iTerm feature or the Terminal.app feature that shows a confirmation dialog if there is a running process besides the shell (or tmux, screen, etc.) is active. It's obviously hung up running `xsel` - do you have xsel in your PATH @krader1961? What version of Xquartz do you hae @nonkr?

**Comment by krader1961** [comment]
Hmmm. I'm running XQuartz 2.7.9_rc2, the latest and greatest, but there's no xsel program on my system and `brew search xsel` says there's no formulae for it. I know what it does I just don't see how @nonkr got it installed on OS X. I wonder if they've wrapped pbcopy and pbpaste in a script named xsel.

**Comment by floam** [comment]
I had it on OS X at one point. I don't remember how, but it was the real xsel. MacPorts I think?

**Comment by floam** [comment]
I can't find an easy way to get it - I can get xclip in homebrew-x11. 

Anyhow this should probably be made not to be broken on any systems that are a few years old. I know I had it 2010 or so: 

`-rw-r--r--  1 floam  staff  432 Aug  8  2010 /Users/floam/.xsel.log`

**Comment by floam** [comment]
I can't seven see where fish is using xsel to copy - only paste?

**Comment by floam** [comment]
(A symlink of pbpaste /usr/local/bin xsel actually "works" to paste, but it's going to direction that is not actually very interesting and it's completely unmanaged.

**Comment by floam** [comment]
> I just don't see how @nonkr got it installed on OS X
[it came with fish, of course!](https://github.com/fish-shell/fish-shell/commits/8cd8c3002e184840476d14dd847dbaa5aa266b8f/xsel-0.9.6.tar)

**Comment by krader1961** [comment]
@nonkr: Can you clarify which version of fish you are running (`fish --version`) and which xsel is on your system that might affect fish (`type -a xsel`)?

See also [issue](https://github.com/fish-shell/fish-shell/issues/2556) which discusses problems with xsel in the context of the \cw binding.

I am surprised to find that the current git head source has explicit invocations of `xsel` in the `kill_add()` function in *src/kill.cpp*. Also, that code only executes if **FISH_CLIPBOARD_CMD** is not defined and that env var is not defined anywhere.

**Comment by nonkr** [comment]
Hi, @floam @krader1961,
everything is OK now, I just reinstall the latest XQuartz-2.7.8, thanks for your help very much.:wink:

**Comment by krader1961** [comment]
Glad you got it fixed. If you can provide more details about what was wrong and how you fixed it that would be helpful. The information could save someone else who runs into this problem a lot of time.
