### ISSUE TITLE
logging related to universal vars isn't documented and is atypical

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2887]
The *src/env_universal_common* code defines a **UNIVERSAL_LOGGING_ENV_NAME** env var and **universal_log_enabled** function that controls whether errors related to universal vars get logged. Why does that exist rather than just using the `debug()` logging used everywhere else in the code? This smells like something meant to have a very short lifespan while support for universal vars was being introduced.

**Comment by krader1961** [comment]
@ridiculousfish: It looks like you introduced this 1.9 years ago in commit 2b11d1060ccf8f7c2a255c64b991f6f6788843ae which wasn't tied to an issue. Is there any reason to retain the current, undocumented, behavior?

**Comment by ridiculousfish** [comment]
We can remove the logging now. It was a debugging aid.
