### ISSUE TITLE
Use other keys than right arrow to complete

### ISSUE THREAD

**Issue by iven** [fish-shell/fish-shell#289]
Right arrow is too far away from the home row, and harder to press than the up arrow.

If I want to type `cd workspace/foo/bar`, and the completion gives me `cd workspace/foo`, then I have to move my hands to the right arrow and then back. That's boring.

**Comment by anotheredward** [comment]
@mrak Could you please tell me what the hex codes are for iTerm?

**Comment by mrak** [comment]
@anotheredward here you go

![screen shot 2015-06-15 at 09 05 48](https://cloud.githubusercontent.com/assets/491140/8164408/c36f2a98-133d-11e5-8668-d517c714acf5.png)

under __Preferences__ :arrow_right: __Profiles__ :arrow_right: __Keys__

**Comment by anotheredward** [comment]
Thanks!

**Comment by runvnc** [comment]
Does anyone know exactly how to change it to Shift-Enter in crosh or with bind?  Shift-Enter works a lot better for me than Ctrl-F or right arrow.  I can't figure out how to bind to Shift-Enter with the bind command.

**Comment by faho** [comment]
@runvnc: Try `fish_key_reader`, then press whatever key you want bound.

For me, it prints `bind -k enter 'do something'` or `bind \eOM 'do something'`.

**Comment by runvnc** [comment]
@faho thanks, I just tried your suggestions.  On my fish installation v 2.2 I cannot find a fish_key_reader command, and `bind \e0M accept-autosuggestion` did not seem to have any effect.

**Comment by faho** [comment]
@runvnc: fish_key_reader is only included in 2.3.1, you'll want to update.

Alternatively you could use e.g. `cat`, in which case the sequence should be echoed back - `^[` here would be "\e" in fish notation.

**Comment by hao-lee** [comment]
`Ctrl + F` Save my life!

**Comment by timvisee** [comment]
In addition to <kbd>Ctrl</kbd>+<kbd>F</kbd> (or of course <kbd>→</kbd>), the `fish` [documentation](https://fishshell.com/docs/current/) also mentions <kbd>Alt</kbd>+<kbd>F</kbd> (or <kbd>Alt</kbd>+<kbd>→</kbd>) to complete just a single word instead of the whole line.

**Comment by Ziewvater** [comment]
Came here to say that I was having issues with Ctrl+F as well, but found that it's actually an issue with the Vi bindings that I'm using with fish: 3541

Solution for me was to use `fish_hybrid_key_bindings` rather than `fish_vi_key_bindings`

**Comment by milushov** [comment]
Hey @mrak, is this still works? It doesn't for me

![image](https://user-images.githubusercontent.com/424326/83355559-d4c79f80-a368-11ea-84cb-90f0b34f122f.png)

0x1b 0x5b 0x46 0x0d

**Comment by mrak** [comment]
@milushov I admittedly no longer use this, as I simply press ctrl+e to complete an auto-suggestion. I have my capslock set to ctrl so this is convenient for me and works in all terminals and servers.
