### ISSUE TITLE
Fish silently fails on $()

### ISSUE THREAD

**Issue by marmistrz** [fish-shell/fish-shell#2892]
After typing this command:

     pacman -Rs $(pacman -Qqtd)

nothing happens

**Comment by rumpelsepp** [comment]
Omit the `$`

```
 pacman -Rs (pacman -Qqtd)
```

http://fishshell.com/docs/current/faq.html#faq-subcommand

**Comment by faho** [comment]
This should print an error message:

>$(...) is not supported. In fish, please use '(pacman)'.
fish: pacman -Rs $(pacman -Qdtq)

And it does for me. What fish version are you using?

(Btw, pacman supports reading from stdin, so `pacman -Qdtq | pacman -Rs -` works)

**Comment by anordal** [comment]
Silently? You're supposed to see this message:

```
$(...) is not supported. In fish, please use '(pacman)'.
fish: pacman -Rs $(pacman -Qqtd)
                 ^
```

The message works for me (in newest master and in version 2.2.0).

**Comment by marmistrz** [comment]
I have two shells open now. In one I get the error msg, in the other - not

**Comment by faho** [comment]
What's the difference between the two shells? Are they different versions (because you opened one, updated fish and then opened the other - `echo $FISH_VERSION`)? Did you change anything in the config? If you now open a new shell, which behavior does it exhibit?

**Comment by marmistrz** [comment]
Nope, I didn't update at all. The shell has been running for a long time. Nothing changed in the config.

Now I noticed that instead of the error message a ⏎ sign appears

**Comment by faho** [comment]
Okay, so which version are you running?

Also your config (are you using OMF or anything like that?) and universal variables (the fishd file) might be nice to have.

**Comment by marmistrz** [comment]
Fish 2.2.0

fishd.arch:
```
# This file is automatically generated by the fish.
# Do NOT edit it directly, your changes will be overwritten.
SET __fish_init_1_50_0:\x1d
SET fish_color_autosuggestion:555\x1eyellow
SET fish_color_command:005fd7\x1epurple
SET fish_color_comment:red
SET fish_color_cwd:green
SET fish_color_cwd_root:red
SET fish_color_error:red\x1e\x2d\x2dbold
SET fish_color_escape:cyan
SET fish_color_history_current:cyan
SET fish_color_match:cyan
SET fish_color_normal:normal
SET fish_color_operator:cyan
SET fish_color_param:00afff\x1ecyan
SET fish_color_quote:brown
SET fish_color_redirection:normal
SET fish_color_search_match:\x2d\x2dbackground\x3dpurple
SET fish_color_selection:\x2d\x2dbackground\x3dpurple
SET fish_color_valid_path:\x2d\x2dunderline
SET fish_greeting:Welcome\x20to\x20fish\x2c\x20the\x20friendly\x20interactive\x20shell\x0aType\x20\x1b\x5b32mhelp\x1b\x5b30m\x1b\x28B\x1b\x5bm\x20for\x20instructions\x20on\x20how\x20to\x20use\x20fish
SET fish_key_bindings:fish_default_key_bindings
SET fish_pager_color_completion:normal
SET fish_pager_color_description:555\x1eyellow
SET fish_pager_color_prefix:cyan
SET fish_pager_color_progress:cyan
```
No OMF installed

**Comment by faho** [comment]
Oooh, I don't get that message on 2.2.0  either, I do get it on git, though.

As far as I can tell @ridiculousfish added this in c91f70523cbdf62292accf87b4465ad30ca8c159, so it should already be fixed.
