### ISSUE TITLE
what is the purpose of the "ignore" special color?

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2893]
Cppcheck complains

```
[src/color.cpp:247]: style (unusedFunction): The function 'ignore' is never used.
```

Specifically, the `rgb_color_t::ignore()` method is never called to construct the "ignore" special color. There are places in the code that call the `rgb_color_t::is_ignore()` method. The "ignore" special color looks like an idea that was abandoned but the residual code that referenced it wasn't removed.

@ridiculousfish you added this way back on 2012-02-12 in commit 0a4c72e78b929237711717508746390e666f3811. Do you recall what the purpose of the "ignore" special color was? Should I just remove all references to it?

**Comment by floam** [comment]
It was there before that commit.

**Comment by krader1961** [comment]
According to git the *color.cpp* file was added by that commit: `git blame 0a4c72e^ -- color.cpp` reports that *color.cpp* doesn't exist. It's possible the code was moved from a different location but I'm not willing to put in the effort to figure that out.

**Comment by floam** [comment]
It's the only way to learn the purpose of the ignore special color. Here in output.h:the usage is described.

```c
/**
   Constants for various colors as used by the set_color function. 
*/
enum
{
	FISH_COLOR_BLACK,
	FISH_COLOR_RED,
	FISH_COLOR_GREEN,
	FISH_COLOR_YELLOW,
	FISH_COLOR_BLUE,
	FISH_COLOR_MAGENTA,
	FISH_COLOR_CYAN,
	FISH_COLOR_WHITE,
	/** The default fg color of the terminal */
	FISH_COLOR_NORMAL,
	FISH_COLOR_IGNORE,
	FISH_COLOR_RESET
}
;

/**
   The value to send to set_color to tell it to use a bold font
*/
#define FISH_COLOR_BOLD 0x80
/**
   The value to send to set_color to tell it to underline the text
*/
#define FISH_COLOR_UNDERLINE 0x100

/**
   Sets the fg and bg color. May be called as often as you like, since
   if the new color is the same as the previous, nothing will be
   written. Negative values for set_color will also be ignored. Since
   the terminfo string this function emits can potentially cause the
   screen to flicker, the function takes care to write as little as
   possible.

   Possible values for color are any form the FISH_COLOR_* enum,
   FISH_COLOR_IGNORE and FISH_COLOR_RESET. FISH_COLOR_IGNORE will
   leave the color unchanged, and FISH_COLOR_RESET will perform an
   exit_attribute_mode, even if set_color thinks it is already in
   FISH_COLOR_NORMAL mode.

   In order to set the color to normal, three terminfo strings may
   have to be written.

   - First a string to set the color, such as set_a_foreground. This
   is needed because otherwise the previous strings colors might be
   removed as well.

   - After that we write the exit_attribute_mode string to reset all
   color attributes.

   - Lastly we may need to write set_a_background or set_a_foreground
   to set the other half of the color pair to what it should be.

   \param c Foreground color.
   \param c2 Background color.
*/
}
```

**Comment by krader1961** [comment]
Okay, but that doesn't change the fact that `FISH_COLOR_IGNORE` and the constructor, `rgb_color_t::ignore()`, isn't used. From the few places in the code that test for that special color it looks like it might have been intended to indicate that only the foreground color was to be set. But those uses don't actually affect the behavior at this time.

**Comment by floam** [comment]
Darn it, someone broke my favorite set_feature color! 

I agree, I can't find anything it's doing.
