### ISSUE TITLE
Update and improve xcode project, determine what is desired and intended for it.

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#2895]
The xcode project settings I think would be better served by incorporating XCTests.

This is essential to get good CI going with Travis's Mac support. If Travis can tell us OS X guys that we're breaking Linux and vice-versa that'd be awesome. I'm working on this and making progress!  Does anyone have a secret stash of XCTests?

I propose that it switch to the C++11 target and use libc++ to better match the types of binaries produced in the MakeFile. This is trivial and I have done this. There may need to be a wider discussion about exactly what our own standard for C++ is, but this is just a build flag. 

I also propose we flip on all the great sanitizers and whatnot by default on Debug builds.

Questions: are we sure fish still runs on 10.6? If no, or if we want the advantages (not enumerated here), we may consider bumping that to 10.7.(They include, I think, some things that'd make the OS X notifyd/libnotify better. I need to consult the docs again to say exactly how besides suspend/resume notifications and I think we could use dispatch more easily.).

The resulting fish binaries themselves are missing any kind of versioning information in the mach headers. These would show up in CrashReports - I think it's good to not have them be 0.000000. We need a way to map release versions and git revs to floats. They can be scripted in easily.

Also, the fish.app bundle itself seems to just take a number from xcode entered manually - right now it's saying we're at 2.0.

I personally code-sign my fish binaries with my Apple Developer ID, since I paid the hundred bucks anyhow.

I don't like having something as essential as my shell at risk of being messed with. Could any of the maintainers here do this for releases? Consider possible future restrictions Apple might introduce in the future and compatibility.

Is continually hand-updating the xcodeproject the right way to go? Would it be better to harmonize the build by having Xcode do the autotools buiild, or use cmake to generate both?

The fish produced by xcode is wildly different than what the Makefile produces. I'll post a diff sometime.

**Comment by zanchey** [comment]
Signing is discussed in #753.

I'd prefer to only have one build process.

**Comment by floam** [comment]
Same here - the resulting builds are so different they really ought to have an identifier in the build string.

**Comment by zanchey** [comment]
CMake is the answer here, and is well on its way to maturing, so I'll close this for now.
