### ISSUE TITLE
`fish_indent` converts `2>&1` into `2>& 1` (note the space)

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2899]
Using `fish_indent` from git head as I type this I noticed that it converts `2>&1` into `2>& 1`. Is that really what we want for the canonical form of a file descriptor redirection?

This came to my attention as part of doing a final sanity check of the `make style` target I'm introducing to ensure code matches the style guide.

**Comment by faho** [comment]
I'd actually expect that form to be invalid and raise an error like "`2>&`: Expected file descriptor number".

**Comment by krader1961** [comment]
I too would have expected that syntax to be an error but it isn't as shown by a simple example:

```
$ echo yes >x 2>& 1 no
$ cat x
yes no
```
