### ISSUE TITLE
`fish_indent` should wrap lines to keep them <= 100 chars in length

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2900]
While working on implementing issue #571 I noticed that `fish_indent` completely ignores any explicit line continuations present in the original script. For example,

```
cppcheck -q --verbose --std=posix --std=c11 --language=c++ \
    --template "[{file}:{line}]: {severity} ({id}): {message}" \
    --suppress=missingIncludeSystem \
    --inline-suppr --enable=$cppchecks $cppcheck_args $c_files 2>&1
```

becomes a single line. A line that is so long it is hard to read. Is that really the behavior we want?

I can appreciate that enhancing `fish_indent` to wrap long lines may be more difficult than the value obtained from that enhancement. But it seems to me that it should respect any explicit wrapping done by the user to ensure lines are a reasonable length.

**Comment by faho** [comment]
fish_indent also does lines wrong the other way around (IMHO) - it will turn

`set -q argv[1]; or return 1`

into

```fish
set -q argv[1]
or return 1
```

So the question is when and how lines should be split.

I'd argue that 

- Lines should have a certain maximum length after which they should be split

- Continuing lines should be indented further than the line they are continuing

- One command per line with the exception of `; and` and `; or`, which should be split on the maximum length and then indented like continuing lines

I.e.:

```fish
set -q argv[1]; and return 1
somelongcommand that fills enough of the line that the "and" doesn't fit anymore
                and echo "It LIVES!"
```

**Comment by krader1961** [comment]
The parser does not encode explicit line continuations. Which is reasonable and not surprising. Too, `fish_indent` should ignore any, possibly bogus, explicit line splits. It should reformat the text based solely on the parsed, semantic, content. Implementing this is going to take more work than I'm willing to invest today so I'm un-assigning myself. I hope someone else is motivated to tackle this issue. We want `fish_indent` to break lines so they are no longer than 100 chars, if possible, while also appropriately indenting the second thru n'th lines.

**Comment by faho** [comment]
Okay, I've now made it so that semicolons are kept for `; and` and `; or`.

I also have a change lying around to break at X chars, but the problem with that is that we don't parse command substitutions, so

```fish
for f in (a rather long pipeline | with pipes and all that | goes over the limit | by a bit)
```

would become

```fish
for f in \
    (a rather long pipeline | with pipes and all that | goes over the limit | by a bit)
```

instead of

```fish
for f in (a rather long pipeline | 
    with pipes and all that | 
    goes over the limit | 
    by a bit)
```

or similar. It does keep the breaks, though.

But that seems weird enough that I don't think we want to merge it.

**Comment by faho** [comment]
Alright, I don't believe anyone is really very interested in this.

Personally I always find line length to be the least interesting part of autoformatting.
