### ISSUE TITLE
add  	__fish_complete_ignore_suffix.fish

### ISSUE THREAD

**Issue by nim65s** [fish-shell/fish-shell#2906]
Hi,

__fish_complete_suffix.fish is great, but sometimes I'd like to reverse its behaviour.

For example, my text editor can open most files in most directories, but not pdf nor images.
So it would take forever to tell it which files it can open, but some small filters on which files it can not open would really help.
### Reproduction Steps:
1. `complete -c vim -x -a "(__fish_complete_ignore_suffix .pdf)`
2. `touch article.tex article.pdf`
3. `vim a<tab>`
### Expected behavior:

Should complete `article.tex`, as it is the only non-.pdf file corresponding

**Comment by faho** [comment]
I could have sworn that we already had something like this, but I can't find it.

So I'll repeat my spiel:

In essence, this is not as useful as you think. For instance, vim _can_ open pdfs. There's even some plaintext parts in there that you might actually want to edit. We can't really know that. Then there's more filetypes than we can ever add here, and some aren't even identified via suffix. And then there's the issue that the supported filetypes depend on the program, the version and the compiletime options. E.g. emacs might actually be able to render pdfs, or it might not.

This'd end with you just playing whack-a-mole.

So I'm closing this. Sorry for the late reaction!
