### ISSUE TITLE
unable to bind a key

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#2908]
I tried to bind a key for Ctrl-l using the following three methods:

1. in config.fish

        bind \cl 'clear; commandline -f repaint; echo bind OK'

2. in config.fish

        function fish_user_key_bindings
               bind \cl 'clear; commandline -f repaint; echo bind OK'
        end

3. in ~/.config/fish/functions/fish_user_key_bindings.fish

        bind \cl 'clear; commandline -f repaint; echo bind OK'

None of them works, if I simply use this after terminal prompt

    bind \cl 'clear; commandline -f repaint; echo bind OK'

it will work for the current session, and I can see the definition from the output of **bind** command in terminal, but it does not work in the future sessions.

And I find a solution, since the Ctrl-l is already defined in /usr/share/fish/functions/fish_default_key_bindings.fish, if I change the definition line for the ctrl-l from

    bind $argv \cl 'clear; commandline -f repaint'

to

    bind \cl 'clear; commandline -f repaint; echo bind OK'

it works in future sessions.

Do I have to define a binding in /usr/share/fish/functions/fish_default_key_bindings.fish or this is a bug?

**NOTE**: this is nothing about rebinding, if I change \cl to other bindings that is not a default binding, it is the same result.

**Comment by c02y** [comment]
I did have another definition of **fish_user_key_bindings**, didn't know 
that I should put all user bindings inside one single 
**fish_user_key_bindings**, thank you.

**Comment by krader1961** [comment]
That's an easy mistake to make. I've made it myself. The important thing to remember is that your custom bindings are instantiated by running a function and there can be only one active definition of a function.

Rhetorical: In other words if you had the following two definitions of the same function name what would you expect to happen when invoking the function:

```
function test_me
    echo yes
end
function test_me
    echo no
end
```

**Comment by c02y** [comment]
I know that it's wrong to make multiple definition for one function, but I 
thought **fish_user_key_bindings** is builtin, every time you make a 
definition, the binding should be appended to a list or something.

Now I get it, it's just a regular function.
