### ISSUE TITLE
zsh-like menu for completions

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#291]
This issue tracks a zsh-like menu for completions, as discussed in https://github.com/fish-shell/fish-shell/issues/84

Note that in typical zsh fashion, the menu system requires some magic to enable, listed at http://www.refining-linux.org/archives/40/ZSH-Gem-5-Menu-selection/

**Comment by gilvaju** [comment]
How to use tab list completions with arrows keys?

**Comment by ridiculousfish** [comment]
When the pager list is shown, you can either press the Down arrow to start navigating it, or press tab again. When an item is highlighted the arrow keys let you navigate. Does that answer your question?

**Comment by gilvaju** [comment]
In my terminal that does not happen. When I press tab, the list of suggestions appears but prompt ever appears again.
![screen shot 2015-05-22 at 21 19 40](https://cloud.githubusercontent.com/assets/677039/7781624/a1879fb4-00c8-11e5-9753-b637277be868.png)

**Comment by ridiculousfish** [comment]
This feature is in 2.2, which isn't released yet. You can install the beta from http://fishshell.com/beta/.

**Comment by gilvaju** [comment]
Ah understood. How I would install the beta version via homebrew on osx? I thank the attention.

**Comment by oschrenk** [comment]
Not sure how to install a specific version but you can install directly from latest source if you like to live on the edge

```
brew install fish --HEAD
```

**Comment by gilvaju** [comment]
Perfect, worked !!!!!! Thank you !!!

**Comment by jordelver** [comment]
This feature is really awesome. Thank you :+1:

**Comment by pickfire** [comment]
The feature is here now. Should this issue be closed?

**Comment by faho** [comment]
The issue has been closed for almost a year now.

**Comment by pickfire** [comment]
Sorry about that.
