### ISSUE TITLE
Pasting text with valid paths causes pathological spawning of worker threads

### ISSUE THREAD

**Issue by froody** [fish-shell/fish-shell#2911]
Pasting valid paths takes unreasonably long

### Reproduction Steps:

1. Get a large clipboard full of valid paths, I use "find . | awk '!/^x/{printf $0" "}/^x/' | pbcopy" on OS X in the fish src root
2. Paste the contents of the clipboard into the same terminal
3. Wait for a long time as fish prints out the command, highlighting each character as it is appended to each path

### Expected behavior:

The paste happens almost instantaneously, as happens with bash or other shells

### Observed behavior:

On my mac pro, this takes over 7 minutes (pasting 37k characters on one line), see the sample here: 
[Sample of fish.txt](https://github.com/fish-shell/fish-shell/files/209238/Sample.of.fish.txt)

### Additional information:

I think it would really help if you kept a pool of iotheads around and block on a semaphore/condition variable instead of exiting, and then add_to_queue would just wake up a thread instead of creating a new one each time.

---
Fish version:  2.2.0

Operating system: OSX 10.11.4, brew install fish

Terminal or terminal emulator: iTerm2

**Comment by krader1961** [comment]
I can't reproduce. Using fish built from git head fish is noticeably faster than bash pasting the result of this command:

```
tr -d '\n' < src/wgetopt.cpp | pbcopy
```

I used the content of that file because its size is predictable. The find output depends on the state of the local git repo (contents of *.git*) and whether you've done a `make clean`.

I used the latest iTerm2.

**Comment by froody** [comment]
Ah cool, much faster on trunk, but now pressing 'return' doesn't do anything :(

**Comment by ridiculousfish** [comment]
My memory is that pressing return is broken when you run a ToT fish against 2.2.0 functions.  If you install trunk fish, it ought to work.

**Comment by froody** [comment]
yay!
