### ISSUE TITLE
`bind` documentation incorrect with respect to the available functions

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2914]
In _doc_src/bind.txt_ but not listed as a function by `bind -f`:
- [x] delete-line (kill-line?)
- [x] dump-functions
- [x] explain

In the `bind -f` output but not in _doc_src/bind.txt_:
- [x] and
- [x] backward-jump
- [x] beginning-of-buffer
- [x] cancel
- [x] down-line
- [x] end-of-buffer
- [x] execute
- [x] force-repaint
- [x] forward-jump
- [x] history-token-search-backward
- [x] history-token-search-forward
- [x] repaint
- [x] self-insert
- [x] up-line
- [ ] vi-arg-digit
- [ ] vi-delete-to

**Comment by faho** [comment]
`delete-line` was a thing until feec9579c285212e8b0544e5679337b5d4ce808d - in 2007.

I can't find dump-functions or explain.

**Comment by floam** [comment]
`command_list.txt`

**Comment by faho** [comment]
@floam: What's that? I can't find a file by that name in the repo.

**Comment by floam** [comment]
Sorry, I deleted it because I thought I misunderstood and you were confining that you also couldn't find it in the *code*. `explain` and `dump-functions`  are in bind.txt and command_list.txt. (latter is compiled, somehow.).

**Comment by laughedelic** [comment]
I was recently asking questions about these input functions in the gitter chat. Are there any updates/plans on this issue?

**Comment by krader1961** [comment]
> Are there any updates/plans on this issue?

Someone with the time and inclination to do so simply needs to read the source code and add appropriate verbiage to the documentation. Patches welcomed 😄

**Comment by laughedelic** [comment]
I see.. 😅

**Comment by gokulsoumya** [comment]
All the mentioned functions except `vi-arg-digit` and `vi-delete-to` are now in the docs, but the missing ones don't exist anymore I think. Grepping in src didn't turn up anything.

**Comment by zanchey** [comment]
Yes, you are right!
