### ISSUE TITLE
Suspect code in fallback.h: overrides __func__, hurts error quality.

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#2919]
Is this operating as in inteded, for our C++ project? I kind of think no.
```
/**
   Make sure __func__ is defined to some string. In C99, this should
   be the currently compiled function. If we aren't using C99 or
   later, older versions of GCC had __FUNCTION__.
*/

#if __STDC_VERSION__ < 199901L
# if __GNUC__ >= 2
#  define __func__ __FUNCTION__
# else
#  define __func__ "<unknown>"
# endif
#endif
```

The official word on `__STDC_VERSION__`  is this:
> This macro is not defined if the -traditional-cpp option is used, nor when compiling C++ or Objective-C.`

In reality it was often still defined for a long time, but as you get closer to C++11 it's safe to assume it's unset. 

And that was true for me last night with clang 3.9.0 on NetBSD-current (but I don't think the NetBSDness affected anything regarding this. 

Undefined causes the less-than case to occur here:
```#if __STDC_VERSION__ < 199901L```

So when undefined on this  C++ compiler, `__func__` gets replaces with  `__FUNCTION__`..

So our error output where it tries to identify function names we are causing to degrade from the default pretty-printed C++, ie. `void a::sub(int)`, to a situation where where that same function outputs as this in the old C formatter:  `sub`.

**Comment by floam** [comment]
I have a PR ready but I want to make sure maybe someone didn't actually do this for a good reason..

**Comment by krader1961** [comment]
For completeness: http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2004/n1642.html

I vote to just remove that block. One thing I've noticed about open source projects is they're often not aggressive enough about removing obsolete code. That block of code no doubt made sense in 2005 but a decade later does not make sense. We shouldn't be trying to remain compatibility with compilers that are older than many of our contributors.

**Comment by floam** [comment]
GREAT! I thought you might be afraid so near a release so I made went more carefully as I want this in this release for the beta testing.

**Comment by krader1961** [comment]
While I thought @zanchey had already tied the release tag to an earlier commit I'm not opposed to including this change in the 2.3.0 release. If it breaks someone using an ancient toolchain we can deal with that after the 2.3.0 release. But I don't understand why you think it should be in the 2.3.0 release. Why can't someone on NetBSD just build from whatever post-2.3.0 commit includes this change?

**Comment by floam** [comment]
Wait, what?
 

This has nothing to do with NetBSD.

**Comment by floam** [comment]
The reason to push this one in is so that we don't get crappy error reports due to `__STANDARD__`.

**Comment by floam** [comment]
> If it breaks someone using an ancient toolchain we can deal with that after the 2.3.0 release. 

I think you misunderstand the code here. This breaks new toolchains because on C++11 that should be undefined. In that case the macros actually consider it < ... and so they overwrite your `__func__`

**Comment by krader1961** [comment]
Without your change modern toolchains are potentially broken. With your change to remove the block of code ancient toolchains are potentially broken. My point is that the latter is unlikely and in any event we probably don't want to support them.

If this has "nothing to do with NetBSD" then why did you mention it in your original comment? My point was simply that for the platforms we currently target that incompatibility isn't an issue. And for anyone using a platform, such as NetBSD, where it is an issue they can simply build against a post-2.3.0 commit. So I'm still confused why you think this change has to be part of the 2.3.0 release.

**Comment by floam** [comment]
> If this has "nothing to do with NetBSD" then why did you mention it in your original comment? 

That's hog bug reports work. I told you my OS and toolchain. I've been working on 3 platforms this week and I might as well be explicit so people don't make strange assumptions.

**Comment by floam** [comment]
> Without your change modern toolchains are potentially broken.

Less, broken, than printing C++ functions without their pretty-printer C style.

**Comment by floam** [comment]
Even on the modern toolchains, it doesn't "break" them. it just makes the fish error output in the spots where it uses __func__ to report where it error'd less useful.

**Comment by ridiculousfish** [comment]
I merged floam's commit 574851f092358f5834afb0b529676924fcbd59c6 into master.

We may have a quick point release for BoUoLoW and this can go in there. I created and added a label for this.

**Comment by zanchey** [comment]
I think we should take it for the 2.3b1 release?

**Comment by ridiculousfish** [comment]
We should take it if we want to promote fish on bash-on...on-Windows

**Comment by floam** [comment]
I guess it could help a little on Windows! (but really, this one happens the same everywhere)

**Comment by krytarowski** [comment]
C++ `__func__` mismatch between NetBSD and the world has been noted in LLVM regression tests.

CC: @mgorny 

We are going to stop redefining it for c++11 and newer.
