### ISSUE TITLE
fish_config prompt rendering is wrong

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#2924]
Consider the preview for the Terlar theme:

<img width="388" alt="screenshot 2016-04-09 at 10 14 11 pm" src="https://cloud.githubusercontent.com/assets/291142/14408242/e8cf5570-fea0-11e5-9b3c-bd81b083a79d.png">

On my terminal it actually renders like this:

<img width="248" alt="screenshot 2016-04-09 at 10 11 04 pm" src="https://cloud.githubusercontent.com/assets/291142/14408243/f5960d08-fea0-11e5-9a1f-23f669e594ae.png">

There are issues:
 1. For certain glyphs like that lightning bolt, the webapp isn't picking the glyphs we'd like see at the terminal. 
 2. There is some bug with the colors likely not changing/ending the way they actually do in a terminal (color of the second line).
 3. All of the git-aware commands only have an indication and preview of their true nature if you happen to execute them in a git repo.

A PR for 1 is incoming. 2 is caused because that color changes depending on exit status... and for some reason that's always not 0 in the demonstrations I guess.

After looking over how these are rendered, I wonder if fish wouldn't be better off using a Javascript module that is capable of more accurately and fully rendering a string full of ANSI/vt100 escape sequences the  same way a terminal would. It would be neat to show color schemes and the prompt together, by feeding something like [tty.js](https://github.com/chjj/tty.js/) actual fish output.

**Comment by jakwings** [comment]
I remember there is a duplicate issue somewhere. The problem is: how do you actually get the color and font settings of your terminal?

**Comment by floam** [comment]
In this case the ugly glyph is caused by the webapp simply asking for "Courier New". Who they hell likes Courier New! 

The color issue isn't that it needs to use a color setting, I believe it's simply doing ANSI->HTML poorly.

**Comment by floam** [comment]
PR #2925 gets us closer, with crazy glyphs more often rendering as intended:

![screenshot](https://cloud.githubusercontent.com/assets/291142/14408309/175bc948-fea4-11e5-9018-35c6350f0d42.png)

**Comment by jakwings** [comment]
> Who the hell uses Courier New on a terminal? (Or generally likes it? :smiley:)

Regardless of the Courier (New) font, AFAICT, *lots* of front-end devs love those colorful emoji.

… Ah, emoji is not displaying well (#2199), so using single-width chars could be a saner default.

**Comment by floam** [comment]
> AFAICT, lots of front-end devs love those colorful emoji.
Huh, I knew that but I assumed this was a bug and that font never intended for the color lightning bolt to come through. After this change a glyph only available in Apple Color Emoji will show a color emoji glyph.

**Comment by floam** [comment]
> AFAICT, lots of front-end devs love those colorful emoji.

OK, I did find a few examples online of people using lightning bolts for git status in prompts and in their screenshots they seem to be matching the smaller, uncolored/re-colorable glyph I see on my terminal.
