### ISSUE TITLE
should we remove timing sensitive tests?

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2926]
For the umpteenth time I committed a change that failed one of the three unit tests because a timing sensitive [test timed out](http://clicks.travis-ci.org/track/click/30007208/travis-ci.org?p=eyJzIjoiWnZnS2dkTUJDWmVjTDVTbmxwbmxtN1NvUmJFIiwidiI6MSwicCI6IntcInVcIjozMDAwNzIwOCxcInZcIjoxLFwidXJsXCI6XCJodHRwczpcXFwvXFxcL3RyYXZpcy1jaS5vcmdcXFwvZmlzaC1zaGVsbFxcXC9maXNoLXNoZWxsXFxcL2J1aWxkc1xcXC8xMjIxNDc5MTFcIixcImlkXCI6XCI4ODRmYzYwOTdkOWY0YWRiOTM0ZmMzZjU4ZDI5NGEwMVwiLFwidXJsX2lkc1wiOltcIjVjYTc2YWM5N2Q5YmNhYTY3Y2IxMWY0ZThkYjQ3Y2Y3OTQ4NDlhNGJcIl19In0).

```
Error output differs for file bind.expect. Diff follows:
--- bind.expect.tmp.err	2016-04-11 02:39:20.248802508 +0000
+++ bind.expect.err	2016-04-11 02:37:16.330628774 +0000
@@ -1,17 +0,0 @@
-timeout
-    while executing
-"error $msg"
-    (procedure "abort" line 2)
-    invoked from within
-"abort "timeout""
-    invoked from within
-"expect {*}$expargs"
-    (procedure "expect_prompt" line 97)
-    invoked from within
-"expect_prompt -re {\r\nTENT\r\n} {
-    puts "t-binding success"
-} -nounmatched -re {\r\nfail} {
-    puts stderr "t-binding fail"
-} unmatched {
-    put..."
```

This is something that happens with sufficient frequency that it is annoying to the regular committers and causes needless concern for infrequent committers.  I can't recall the last time I saw such a failure on my local servers. It has happened on my local servers but with a frequency at least an order of magnitude less often than on Travis.

I'm strongly inclined to either completely remove those tests or greatly increase the timeouts. However, the latter would greatly reduce their utility since the whole point of those tests is to verify that timing sensitive interactive behavior behaves as expected.

**Comment by krader1961** [comment]
Not surprisingly simply forcing Travis to rerun the failing test caused it to pass.

**Comment by faho** [comment]
Yes, please! At least that one test is quite annoying - I'm not sure if we have others that regularly fail.

**Comment by krader1961** [comment]
I've decided to add an explicit retry for known flakey tests. Almost all of the *bind.expect* tests are timing sensitive so we can't just disable them. And my review of several failures suggests the problem is more fundamental than an operation taking more or less time than expected. It really looks like the output that should be present in the expect input buffer isn't there. I suspect a subtle race condition involving pipe/pty buffering that is causing a deadlock.
