### ISSUE TITLE
with the change to `status -f` output a `realpath` implementation would be useful

### ISSUE THREAD

**Issue by terlar** [fish-shell/fish-shell#2932]
If you are symlinking scripts that rely on `status -f` being resolved to the original source, you will get the wrong file. Is this the correct behaviour of `status -f` and if so, is there a way to get the real path of the currently executed script?

### Reproduction Steps:

1. `mkdir -p /tmp/dir1`
2. `mkdir -p /tmp/dir2`
3. `echo 'status -f' > /tmp/dir1/real.fish`
4. `ln -s /tmp/dir1/real.fish /tmp/dir2/link.fish`

### Expected behavior:

```
$ fish /tmp/dir1/real.fish
/tmp/dir1/real.fish
$ fish /tmp/dir2/link.fish
/tmp/dir1/real.fish
```

### Observed behavior:

```
$ fish /tmp/dir1/real.fish
/tmp/dir1/real.fish
$ fish /tmp/dir2/link.fish
/tmp/dir2/link.fish
```

---
Fish version: 2.2.0-747-ge395a0e

Operating system: Arch Linux, fish installed through AUR

Terminal or terminal emulator: termite

**Comment by faho** [comment]
See #2643, where this was changed. The intent was to be consistent whether you're using `source $file` or `fish $file`. 

This case in particular was also [mentioned](https://github.com/fish-shell/fish-shell/issues/2643#issuecomment-167907095):

>I think that resolving symlinks is bad, because some scripts are symlinked to each other and switch off their name to decide what to do.

In other words, this seems to be working as intended. @ridiculousfish: Any comments?

**Comment by terlar** [comment]
I see, I thought I remember something about that, but couldn't find it. However tools like `realpath` have been traditionally shakey, as it works different between systems and are in many cases not a default tool.

Perhaps a built-in solving this path resolution could be a thing? Or a switch to the `status` command?

**Comment by krader1961** [comment]
The current behavior was deliberately chosen to satisfy the broadest set of use cases. If you're on a distro like OS X which doesn't have a native `realpath` it probably has `readlink` which you can wrap in a  `realpath` function. And, of course, it's easy to install via `brew install coreutils` or `sudo apt-get install coreutils` (or whatever ArchLinux uses). Too, using other available tools such as python it's easy enough to write such as command. For example,

```
python2 -c 'import os, sys; print os.path.realpath(sys.argv[1])' symlinks/sms
```

**Comment by terlar** [comment]
Yes, I agree for personal use that is okay. But I was more thinking if there is some fish code that I want to distribute for other users. I have no idea what systems and setups they have, would be nice to have a reliable way to deal with that. However your suggestions are appreciated.

This was specifically that I wanted to add a custom fish functions path and a custom fish completions path relative from the script location and I wanted to symlink that script into the `conf.d`. However there might be better ways nowadays to handle custom fish scripts/addons with the vendor things and also through third party "plugin" environments.

**Comment by terlar** [comment]
I should probably use the `$__fish_datadir/vendor_completions.d`, `$__fish_datadir/vendor_functions.d` and `$__fish_datadir/vendor_conf.d`.

**Comment by krader1961** [comment]
I suppose we could add a `realpath` function that passes through to the command if it's available else uses one of the workarounds I listed above.
