### ISSUE TITLE
Key binding for undo autosuggestion

### ISSUE THREAD

**Issue by yshui** [fish-shell/fish-shell#2944]
When I accept an auto suggestion by mistake, I wish I can undo it quickly.

### Reproduction Steps:

1. Input incomplete command: ls /usr
2. Suggestion /usr[/something/super/long/path/name/here] comes up, accepted it by mistake
3. Have to remove the suggestion by hand

### Expected behavior:

Have some key binding which allows me to move the accepted suggestion in one key stroke.

**Comment by faho** [comment]
This is a special case of #1367 - we currently don't have an undo at all, and if we did it would also undo accept-autosuggestion.
