### ISSUE TITLE
`fish --history --contains` splits on newlines.

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#2947]
Try using the `history` builtin to search for and interactively delete a term common enough that it would appear inside some multiline history items. Like `echo`.

`fish --delete --contains echo`
...
```
[751] for i in (seq (random) -1 1) 
[752]            echo $i 
[753]            sleep 1 
[754]        end
```

the actual history line:
```yams
- cmd: for i in (seq (random) -1 1)\n           echo $i\n           sleep 1\n       end
  when: 1460323954
```

Deleting 752 doesn't work. It silently fails.

**Comment by faho** [comment]
This is #31 - yes, double-digits.
