### ISSUE TITLE
Environment variable for configuration snippet path

### ISSUE THREAD

**Issue by chris-martin** [fish-shell/fish-shell#2950]
I'm trying to figure out how to design a Fish plugin infrastructure for the [Nix package manager](https://nixos.org/nix/). This generally involves creating a shim that wraps the `fish` binary and appends paths of managed plugins to environment variables.

It seems that a Fish plugin may consist of three things:

1. Functions, in paths specified by `$fish_function_path`
2. Completions, in paths specified by `$fish_complete_path`
3. Configuration snippets, in `~/.config/fish/conf.d`

The first two are configured by environment variables that I can append to. For configuration snippets, I can't find any way to add additional paths. Is there something I'm missing, or can we add it?

What I want to do here is very similar to what the "vendor" directories faciliate, but the problem is that those paths are compiled into Fish, not settable by environment variables. I need to change the snippet directory every time the plugin list changes, and it would be unpleasant to have to recompile Fish every time.

**Comment by faho** [comment]
(I'm currently a bit sick, so please excuse it if I'm not fully coherent)

The user snippets are in $XDG_CONFIG_HOME/fish/conf.d, or ~/.config/fish/conf.d if XDG_CONFIG_HOME is unset. There's currently no $PATH-like variable here for multiple directories, and it wouldn't quite work with the same semantics as these things are `source`d too early.

Would making conf.d a symlink work for you?

**Comment by chris-martin** [comment]
> Would making conf.d a symlink work for you?

No - A nix package cannot place files into arbitrary places in users' home directories, symlink or otherwise. I wouldn't want to do that anyway, because I wouldn't want to overwrite any  existing `conf.d` they have. The idea is to create a fish wrapper that has *additional* snippets. The package-manager-provided snippets and user snippets need to go in different directories.

**Comment by chris-martin** [comment]
> these things are `source`d too early

Too early... to access an environment variable? I'm confused.

> it wouldn't quite work with the same semantics

Could it work with slightly different semantics?

**Comment by faho** [comment]
>The package-manager-provided snippets and user snippets need to go in different directories.

They already do. The package-manager-provided snippets are supposed to go into $__extraconfdir (which is set via our configure script at build-time) - which defaults to $__fish_datadir/vendor_conf.d - which is often /usr/share/fish/vendor_conf.d. We also have one for the admin, which is in $__fish_sysconfdir/conf.d (/etc/fish/conf.d).

The thing in $HOME is supposed to be used by the _user_ themselves.

>Too early... to access an environment variable? I'm confused.

If you are talking about an environment variable set in config.fish, it is. Now I might have misread what you meant and it is supposed to be set outside of fish, and that _might_ work, but I'd need to understand what you'd use it for.

**Comment by faho** [comment]
Oh, you can get the vendor configuration directory via `pkg-config --variable confdir fish`.

**Comment by chris-martin** [comment]
> it is supposed to be set outside of fish

Yeah, I'm talking about a variable that is set outside of fish. *After* fish-shell is compiled, but *before* the packaged-up fish executable is given to the user.

```
    User land                  ~/.config/fish/

+-------------------------------------------------------------------------------+

    Root land         +------------------------------------+
                      |                                    |
                      |      Fish with plugins             |
                      |                                    |
                      |      (adds its own functions,      |
                      |      completions, snippets         |
                      |      by appending to env vars)     |
                      |                                    |
                      |          +--------------+          |
                      |          |              |          |
                      |          |    Fish      |          |
                      |          |              |          |
                      |          +--------------+          |
                      |                                    |
                      +------------------------------------+
```

**Comment by faho** [comment]
> Yeah, I'm talking about a variable that is set outside of fish. After fish-shell is compiled, but before the packaged-up fish executable is given to the user.

And why doesn't symlinking vendor_conf.d work?

I don't know much about Nix - you've got your "reproducible" thing going on that means you want to put specific configurations into their own directories, named after some hash. But you can't have any one fish session have more than one configuration - the conf.d stuff is irreversible in a running fish, since it's sourced and we have no idea what side-effects there are. And it's only used on startup, so switching configurations could be done via altering a symlink and starting a new fish (re-sourcing will result in a weird franken-setup).

**Comment by chris-martin** [comment]
> The package-manager-provided snippets are supposed to go into [...] `/usr/share/fish/vendor_conf.d` [...] `/etc/fish/conf.d`

That's the problem. I need something similar to vendor directories, but it has to be something that I can change without recompiling fish.

The result of every package that Nix builds is hash-addressed and immutable. So when you build `fishWithPlugins`, I'll construct a `conf.d` directory that will exist at `/nix/store/<sha256 sum of the contents>-conf.d/`, and that path will change every time the package is built with different plugins.

**Comment by faho** [comment]
>That's the problem. I need something similar to vendor directories, but it has to be something that I can change without recompiling fish.

You might have just missed it - symlinks for vendor_conf.d?

**Comment by chris-martin** [comment]
I guess I did miss it. I don't follow. What symlinks?

**Comment by faho** [comment]
>I guess I did miss it. I don't follow. What symlinks?

I just made a comment before but I think that might not work - you want multiple fishes installed at the same time?

If the hash of the conf directory is only based on the hash of its contents, you can change extraconfdir to that via ´./configure --with-extra-confdir=`, or is that too early?

**Comment by chris-martin** [comment]
Yes, I definitely want multiple fishes installed at the same time.

> you can change extraconfdir to that via ´./configure --with-extra-confdir=`, or is that too early?

I can do that. But it would require recompiling fish every time I build this wrapper, right?

**Comment by faho** [comment]
@chris-martin: I believe my brain might be working again.

So you want an m-to-n mapping of fishes to "configurations", where configurations are dependent on what other packages the user has installed/built with fish scripts, right?

That's not going to work with the stuff I suggested, and environment variables are probably the best solution for this (I mean a commandline argument to fish would also work, but that'd be too visible for a very unusual configuration).

And for that, there's an easy solution - look at `share/__fish_build_paths.fish`. You'll want to replace the values with references to other variables, e.g. `set __extra_completionsdir $EXTRA_COMPLETIONSDIR`.

I'm not convinced we should carry something like this here - would it be acceptable to you to carry a simple patch (or sed-script) downstream?

**Comment by chris-martin** [comment]
Yeah, a patch is no problem.

Okay, I think I get it. `__extra_confdir` is not a path, but rather a fish expression that evaluates to a path? So if I replace in [`share/__fish_build_paths.fish.in`](https://github.com/fish-shell/fish-shell/blob/master/share/__fish_build_paths.fish.in) the line

    set __extra_confdir @extra_confdir@

with

    set __extra_confdir $EXTRA_CONFDIR

That has the effect of replacing the default vendor snippets path `${datadir}/fish/vendor.d` with a variable `EXTRA_CONFDIR` that will get resolved at runtime?

**Comment by faho** [comment]
>Okay, I think I get it. __extra_confdir is not a path, but rather a fish expression that evaluates to a path?

Yeah, it's a variable. `__fish_build_paths.in` is just a file that we run `sed` on via the Makefile to turn it into a proper fishscript that is then sourced.

>That has the effect of replacing the default vendor snippets path ${datadir}/fish/vendor.d with a variable EXTRA_CONFDIR that will get resolved at runtime?

Yes. Do note though that this invalidates the pkg-config stuff (`fish.pc` in the root directory of the repo), so you might need to change packages that add to the vendor directories via that, but I'm sure you need to do that anyway.

Also note that the code I gave you will _fail_ if EXTRA_CONFDIR is unset by not looking at any vendor directory at all. That's because later on it goes into a for-loop:

```fish
for file in $configdir/fish/conf.d/*.fish $__fish_sysconfdir/conf.d/*.fish $__extra_confdir/*.fish
```

Here, if $__extraconfdir is set to zero elements, the glob will expand to nothing, so the loop will effectively go through `$configdir/fish/conf.d/*.fish` and `$__fish_sysconfdir/conf.d/*.fish`.

If we added a patch for this, we'd probably do a default value if EXTRA_CONFDIR is unset, but my guess is you don't want that.

Anything else?

**Comment by chris-martin** [comment]
I think that settles it, thanks!

**Comment by zanchey** [comment]
If you're going to patch things, I'd suggest just patching the various setup in `share/config.fish`.

**Comment by faho** [comment]
@zanchey: I thought about that, but that's a more complex file - with `__fish_build_paths` you can replace it completely or sed-patch it, with little risk of the patch no longer applying. (I also tried `./configure --with-completionsdir='$EXTRACOMPLETIONSDIR'`, but that fails in interesting ways)
