### ISSUE TITLE
Emit events are not sent to other fish sessions

### ISSUE THREAD

**Issue by Markcial** [fish-shell/fish-shell#2954]
The emit events are not sent to another fish sessions
### Reproduction Steps:
1. Open two terminal sessions with fish shell
2. funced `event_listener`

``` fish
function event_listener --on-event plain-event
    echo event received
end
```
1. funcsave `event_listener`
2. Send event on one terminal `emit plain-event`
3. The event will only be displayed on one terminal, the other session will not receive the event.
### Expected behavior:

If the parameter is meant to be used only in the current session maybe is a behaviour that needs to be documented. If not could be a nice feature for background job manipulation or asynchronous fish scripting.
### Observed behavior:

The event emitted would be only received on the current session, all other sessions will be unaware of that event.
### Additional information:

I was trying to test event emission for job manipulation and handling for a async code snippets for fish.

---

Fish version: fish, version 2.2.0

Operating system: 
Distributor ID: Ubuntu
Description:    Ubuntu 15.10
Release:    15.10
Codename:   wily

curl from the fish website

Terminal or terminal emulator: terminator

**Comment by faho** [comment]
The events we currently specify (`fish_prompt`, `fish_preexec`, `fish_postexec`) really only make sense in one shell - it'd be quite annoying to get `fish_prompt` events from another running session. At least for those we should just document it.

I'm not against "universal events" per se, but we should flesh out for what they are useful and how they should work.

For that I'd need something more than "I was trying to test" - what did you want to _do_?

**Comment by Markcial** [comment]
I wanted to organize test suites to run asynchronously. So i started new fish sessions which would emit the `job-finished` event with the exit, stdout and stderr arguments, so when i catch a `job-finished` event i can display the information about that job to the current fish session.

a draft of the sample code trying to achieve that result

Session 1 
```fish
function run-test-suite
  set -l err (mktmp err.XXX)
  set -l out (mktmp out.XXX)
  fish -c "phpunit ^ $err > $out; and emit job-finished $status $out $err" &
  fish -c "behat ^ $err > $out; and emit job-finihed $status $out $err" &
end
```

Session 2
```fish
function job-listener -e job-finished
   echo Job finished with status $argv[1] out $argv[2] and err $argv[3]
end
```

Tl:dr the idea behind this feature would be event driven fish scripting with asynchronous handling via event publishing.

**Comment by zanchey** [comment]
You can probably use a universal variable as a semaphore with the `--on-variable` function annotation as a first approximation.

**Comment by Markcial** [comment]
Tested and it works. Thanks

**Comment by zanchey** [comment]
I'm going to leave this open as a reminder that it probably should be made clear in the documentation that events are a per-process construct.
