### ISSUE TITLE
Autocompleting arguments into a comma-separated list

### ISSUE THREAD

**Issue by dremelofdeath** [fish-shell/fish-shell#2956]
Hi there, I'm trying to write autocompletions for a that accepts comma-separated lists of values for its options, and that seems to be a major pain as I can apparently only autocomplete one at a time. I have no idea how to specify that the arguments can be repeated.

The basic layout of the command looks like this:

    kittymaster build deploy --realms DEV.NA,PROD.NA mybuild

Here's what I have so far:

    complete -c kittymaster -f -n '__kittymaster_uc build deploy' -l 'realms' -o 'r' --description 'Comma-separated list of target realms'
    complete -c kittymaster -f -n '__kittymaster_uc build deploy; and __kittymaster_last_any --realms -r' -a '$all_realms' --description 'Realm'

I can tab out pretty much everything, but when I get to the end, tabbing the DEV.NA gives me a space instead of a comma, and it would be pretty nice if I could figure out a way to make the arguments both exclusive to one another (so they can't be repeated) and complete them again if there's a comma at the end of it.

Is there a way to do this, or am I just making a complicated feature request? 😆 

---
Fish version: 2.2.0
Operating system: RHEL5 x64, compiled fish myself
Terminal or terminal emulator: OS X Terminal via ssh

**Comment by faho** [comment]
What you want is the `__fish_complete_list` function.

**Comment by zanchey** [comment]
@dremelofdeath, did that solve your problem?

**Comment by faho** [comment]
Assuming it's solved. @dremelofdeath: If it isn't, please comment.

**Comment by dremelofdeath** [comment]
@faho @zanchey Ah yeah, sorry about that -- spaced on this one (and had to move on to other tasks). It kinda works but I had to scrap it for some cases because autocompleting 40k+ results and making them lists is really slow.
