### ISSUE TITLE
fold include-what-you-use into `make lint`

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2957]
I really like ["Include What You Use"](https://github.com/include-what-you-use/include-what-you-use). @zanchey added support to the makefile in commit 299a383d on 2015-07-29. The problem with that change from my perspective is that the `make iwyu` target doesn't limit itself to the files being modified; or were modified by the most recent commit. I propose folding that functionality into the `lint` and `lint-all` targets I recently introduced.

Has anyone been running `make iwyu`? I ask because when I run that on my system it produces a large number of recommendations to improve the code.

**Comment by ridiculousfish** [comment]
IWYU is great, but one gotcha is that it can remove headers that are needed on other platforms. So it's best to do it in a branch and then make sure Travis can build it
