### ISSUE TITLE
Abbraviations --

### ISSUE THREAD

**Issue by Campano** [fish-shell/fish-shell#2958]
When saving an abbreviation via fish_config (for example `ls`for `ls -a`), it saves the commend as `--`and prepends the abbreviation to the command (so I get `--` for `ls ls -a`), and deletes all other abbreviations to keep only the last saved.

### Reproduction Steps:

1. type `fish_config`
2. go to the "abbreviations" tab
3. save one or more abbreviations
4. hit enter in shell to stop
5. type `fish_config` again  

---
Fish version: fish, version 2.2.0`

Operating system: OS X 10.11.13 `brew install fish`

Terminal or terminal emulator: Apple Terminal 2.6.1

**Comment by ridiculousfish** [comment]
Is this #2276?

**Comment by zanchey** [comment]
Yes, I think it's #2276, so I'm going to close this as a duplicate. @Campano, this should be fixed in the just-released 2.3b1 or the about-to-be-released 2.3.0.
