### ISSUE TITLE
Eliminate duplicated entries with set

### ISSUE THREAD

**Issue by anbotero** [fish-shell/fish-shell#296]
I’d like to know if perhaps it is possible to add something like `set -d`, to eliminate duplicated entries from variables.

Right now I’m thinking of it due to OS X [brew](https://github.com/mxcl/homebrew) requiring to have `/usr/local/bin` happen before `/usr/bin`. Installed through it, fish already loads `/usr/local/bin`, but after `/usr/bin`, which gives some problem.

For example, let’s say the current value of `$PATH` is this: `/usr/bin /bin /usr/sbin /sbin /usr/local/Cellar/fishfish/OpenBeta_r2/bin /usr/X11R6/bin /usr/local/bin`

If I were to include in my `config.fish` something like `set -dx /usr/local/bin $PATH`, then $PATH would become: `/usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/Cellar/fishfish/OpenBeta_r2/bin /usr/X11R6/bin`.

It would be a nice addition if fish just detected the paths in `/etc/paths`, and applied `set -d`  on it as well.

Sorry if I extended this issue too much. Anything else would go in comments. Thanks!

**Comment by c02y** [comment]
@maxfl justinmayer 

That is still not right, the `inc count` line should be 

     set count (math $count+1)

not need `function inc`, `varclear` now will work as expected.
