### ISSUE TITLE
Docker Completion Sanity Check

### ISSUE THREAD

**Issue by 8BitAce** [fish-shell/fish-shell#2960]
I'm experiencing a strange issue with fish-shell and Docker on a clean installation. When I type `docker run ` then press tab twice I get the following output:
```
eightbit@arch ~/test> docker run Cannot connect to the Docker daemon. Is the docker daemon running on this host?
                                 1.txt 
1.txt  2.txt  3.txt

```
I have to press Ctrl-C and then Enter to get back to a clean prompt.
I know this message is coming from Docker as I get the same message when running `docker info` as an unprivileged user.
Admittedly I do not know much about fish internals so this might be expected behavior but I can't understand why the shell should ever execute the binary before pressing Enter.

### Reproduction Steps:

1. Open a new instance of fish
2. Type "docker run " followed by two tab presses

### Expected behavior:

Fish should provide the standard completion suggestions.

### Observed behavior:

Fish outputs a message from Docker and prompt becomes unusable.

### Additional information:

This problem is 100% reproducible on my machine even after clearing all fish configuration files.

---
Fish version: fish, version 2.2.0

Operating system: Arch Linux 4.4.5-1-ARCH installed from default repos.

Terminal or terminal emulator: urxvt

**Comment by 8BitAce** [comment]
I realize this is a result of fish calling `docker ps` in order to list the containers. Apologies for my misunderstanding.
It would be helpful if there was some kind of check performed in this scenario as `sudo docker run` will still produce this error and my current configuration is set to restrict docker usage to root only.

**Comment by faho** [comment]
Docker has actually taken the fish completions upstream, so we don't ship them anymore (since 346d918555d3dee772f7c0c51ee087df69b19da).

Can you report the bug to them if it still occurs with their version? Feel free to notify us and we'll see if we can get this hashed out.

**Comment by faho** [comment]
>if it still occurs with their version?

Yeah, it does still occur with their version - that's what you're using (since the arch package is new enough and vendor_completions.d overrides our completions).

**Comment by 8BitAce** [comment]
Sure thing, I'll report it upstream. Thanks.
