### ISSUE TITLE
beta fish packages on OBS?

### ISSUE THREAD

**Issue by jrobeson** [fish-shell/fish-shell#2962]
I wonder if it'd be useful to provide a beta channel/repo for easier testing of fish releases. I'm not sure how much work goes into dealing with OBS, so it might not be worth it.

**Comment by krader1961** [comment]
What is "OBS"? Googling "linux OBS" returns a lot of hits that don't seem relevant and there's no use of that acronym in the fish git repo. Those questions notwithstanding I agree we should make testing new releases as easy as possible but keeping in mind there are literally a handful of core developers doing the grunt work in their spare time.

**Comment by ridiculousfish** [comment]
OBS = http://openbuildservice.org . @zanchey is our OBS big brain.

**Comment by zanchey** [comment]
@jrobeson did you mean [shells:fish:beta:2](http://software.opensuse.org/download.html?project=shells%3Afish%3Abeta%3A2&package=fish)?

**Comment by zanchey** [comment]
As well as the OBS Beta repository there, is an [Ubuntu PPA beta channel](https://launchpad.net/~fish-shell/+archive/ubuntu/beta-2).

**Comment by krader1961** [comment]
I don't see any mention of those terms in fish-shell or fish-site or wiki. If we currently, or plan to, support that service a bit of documentation is probably a good idea.

**Comment by jrobeson** [comment]
@zanchey: where is that mentioned on the site? I must have missed it somewhere

**Comment by jrobeson** [comment]
it sounds like this this just needs explicit mention on the site somewhere, and that'd be it.

@zanchey: how come you provide a ppa and OBS?

**Comment by jrobeson** [comment]
@krader1961 : i knew it was OBS because i saw this URL for the linux downloads (http://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A2&package=fish)  and assumed it was well known to the group :)

**Comment by zanchey** [comment]
It's on the release email and it should be on the staging website, although I see it isn't.

We provide a PPA because the user experience for installing a PPA compared to a third-party repository is much better.

**Comment by jrobeson** [comment]
@zanchey : it's certainly a better experience to use  COPR on Fedora than OBS repos,  since you can just type something like `dnf copr enable fish-shell/fish`  and then `dnf install fish`.  I wonder how hard that'd be to integrate into your workflow.   It's probably not worth the effort atm though.

If i ever figure out a simple way to publish to COPR from OBS, I'll let you know

**Comment by krader1961** [comment]
> i knew it was OBS because i saw this URL for the linux downloads...

I opened that URL and don't see any mention of OBS even when I click on the various icons. However, I see that at the bottom of the http://openbuildservice.org/ web page it says "The Open Build Service is an openSUSE project". In the absence of documentation in the fish-shell project how would I have known about our presence in OBS?

I get the feeling that the fish-shell project is not using OBS explicitly. Which begs the question of how our latest release showed up on that service. If we are using OBS, directly or indirectly, we should document that fact. If we're not then how did this release show up on that service?

Knowledge that is solely in the minds of long time contributors like @zanchey should be treated as non-existent. Any of those contributors could be hit by a bus tomorrow thus causing that information to be lost. This sort of thing has to be put into writing.

**Comment by jrobeson** [comment]
@krader1961 :  Debian, Fedora, and CentOS official fish repositories are provided by OBS.  The rest of the distros use their native packaging source (or native 3rd party repo like PPA)
