### ISSUE TITLE
Fish .pkg installer does not clean up old installations

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#2963]
Installing fish over an existing installation of fish on OS X gives no indication to the user that they may be messing up an existing installation (perhaps from homebrew) and give them the ability to bail.

Also, even if the the last version was installed with our installer, a new version blasts whatever it has onto / without cleaning up after the old installation. There is no uninstall option if you relaunch the .pkg installer. 

The OS X package system isn't providing any obstacles here, the receipts are in place and OS X knows what files we own, but the installer doesn't have any scripts it runs to check anything. It may be wiser to simply point a user at Homebrew than provide an iffy installer.

**Comment by floam** [comment]
Marked fixed, the .pkg installer now deletes files owned by the installer before extracting. It's not doing anything about detecting an installation from some other source it might collide with, homebrew for example, but a few years ago homebrew started defaulting to installing to /opt so it's not such a likely thing anymore.

**Comment by zanchey** [comment]
> homebrew started defaulting to installing to /opt

[Only on Apple Silicon](https://docs.brew.sh/FAQ#why-is-the-default-installation-prefix-opthomebrew-on-apple-silicon)
