### ISSUE TITLE
vi-mode shift+tab regression

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#2964]
Recent updates to fish's vi-mode appear to have broken the behavior of shift+tab.

When in the fuzzy file finder/autocomplete, tab moves between elements appropriately but shift+tab selects what was highlighted and then sends a tab to the console. 

shift+tab in regular insert mode causes the vi-mode to exit insert mode (and issues an autocomplete via tab).

**Comment by zanchey** [comment]
If this is a regression from 2.2 to 2.3, we'll need to make a note in the release notes.

**Comment by mqudsi** [comment]
I can probably test it out today and let you know.

**Comment by mqudsi** [comment]
This is not a regression from 2.2.0; so far as I can tell it was equally broken there.

**Comment by faho** [comment]
Ooh, we never actually bind `btab` in the vi-bindings!
