### ISSUE TITLE
vi-mode ctrl+c regression

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#2965]
Recent updates to fish master to the vi-mode behavior appear to have changed the expected functionality of ctrl+c.

On OS X under terminal.app using fish master in vi-mode, ctrl+c now results in a yellow `^C` to be posted to the line, followed by a blank line, and then a new line prompt.

Previously, ctrl+c just wiped out the contents of the current line.

(Question: is there an easy way to exit vi mode? Currently I have to remove that from my configuration file and then start a new shell)

**Comment by krader1961** [comment]
This is intentional. People wanted a [ctrl-c] experience closer to what they got from bash. Changed in commit 2f8d0e9aba3662fcb1032ffe33bc6faf2e04eb8f. See issue #2375.

**Comment by mqudsi** [comment]
Thanks, I briefly skimmed through the commit history but couldn't find the reference. I have no problem with this behavior (and probably wouldn't have flagged it if I had/knew an easier way of exiting vi mode!)

**Comment by krader1961** [comment]
> if I had/knew an easier way of exiting vi mode

I don't understand that comment since [ctrl-C] does not, and never did, exit vi mode. It has simply discards any pending interactive input. Other than that the pending input is still visible with the recent change are you seeing some other change in behavior?

**Comment by mqudsi** [comment]
No, sorry I wasn't clear. I have fish_vi_mode set in my config file. In order to compare behavior between vi mode and regular/emacs mode, it would be much easier if I could simply exit vi mode and compare. Currently I would have to remove that line from the config and then start a new shell.

**Comment by krader1961** [comment]
It will be much easier to switch between key bindings when https://github.com/fish-shell/fish-shell/pull/2939 is merged.
