### ISSUE TITLE
fish-2.3b1-2.1.x86_64.rpm doesn't install on CentOS 6.7

### ISSUE THREAD

**Issue by s4code** [fish-shell/fish-shell#2966]
On CentOS 6.7 '/bin/hostname' located in the net-tools package, but it doesn't provide 'hostname'. 
```
$ rpm -qf /bin/hostname
net-tools-1.60-110.el6_2.x86_64
$ rpm -q --provides net-tools
config(net-tools) = 1.60-110.el6_2
net-tools = 1.60-110.el6_2
net-tools(x86-64) = 1.60-110.el6_2
```
So, when I install [fish-2.3b1-2.1.x86_64.rpm] (http://download.opensuse.org/repositories/shells:/fish:/beta:/2/RHEL_6/x86_64/fish-2.3b1-2.1.x86_64.rpm)  I've got an error: 
```
$ sudo rpm -Uhv --nosignature fish-2.3b1-2.1.x86_64.rpm 
error: Failed dependencies:
	hostname is needed by fish-2.3b1-2.1.x86_64
``` 
The correct dependency is the full file path, i.e. '/bin/hostname'. I rebuilt fish-2.2.0 with 'Requires: /bin/hostname' in its spec-file and the package was successfully installed:
```
$ rpm -qRp fish-2.2.0-12.el6.x86_64.rpm 
/bin/hostname  
config(fish) = 2.2.0-12.el6
libc.so.6()(64bit) 
....
$ sudo rpm -Uhv fish-2.2.0-12.el6.x86_64.rpm 
Preparing...          ########################################### [100%]
   1:fish             ########################################### [100%]
$
```

**Comment by zanchey** [comment]
I tried to sort this out with #2190, but I didn't merge it for the 2.3b1 release - good pickup!

ed4b78918a944fe3b3a1e05ac553e89d5f1fa411 depends on net-tools or hostname depending on the platform, but if rpm will pick the right package if you give it a path that looks a lot simpler.

**Comment by zanchey** [comment]
The [Fedora Packaging Guidelines for File Dependencies](https://fedoraproject.org/wiki/Packaging:Guidelines?rd=Packaging/Guidelines#File_Dependencies) suggest that filesystem dependencies are less preferred but I think the benefits outweigh the costs here.

**Comment by simotek** [comment]
@zanchey See my comment on the commit with regards to openSUSE / SUSE Enterprise Linux support

**Comment by s4code** [comment]
@zanchey I've checked CentOS 6.7, Fedora 23, openSUSE Tumbleweed (20160321): `/bin/hostname` present in each distro. So you can safely write `Requires: /bin/hostname` in the spec-file :)

**Comment by zanchey** [comment]
I'm not actually sure how safe that is, because /bin is just a link to /usr/bin - and `dnf whatprovides /bin/hostname` finds no results, so I don't know if RPMs can depend on it. I'm going to try and investigate tonight.

**Comment by s4code** [comment]
@zanchey Unfortunately you're right. On Fedora works only when `Requires: /usr/bin/hostname` :(

**Comment by simotek** [comment]
openSUSE also has `/usr/bin/hostname` with `/bin/hostname` being a symlink, file based dependencies are also generally discouraged in openSUSE due to them being very slow to process.

**Comment by s4code** [comment]
[fish-2.3b2] (http://download.opensuse.org/repositories/shells:/fish:/beta:/2/RHEL_6/x86_64/fish-2.3b2-1.1.x86_64.rpm) doesn't  have the dependency problem. I think i can close this issue.
