### ISSUE TITLE
Tab completion gives unrelated completions in specific cases.

### ISSUE THREAD

**Issue by jldailey** [fish-shell/fish-shell#2972]
### Reproduction Steps:

1. `touch learn.txt`.
2. `vi lear<Tab>` becomes `vi fish_color_`
3. `vi lea<Tab>` becomes `vi ___fish_git_prompt_c`

### Expected behavior:

`vi lear<Tab>` should prefer to complete to items that begin with `"lear"`, or contain `"lear"`; e.g. to `"learn.txt"` here.

### Observed behavior:

Fish completes `vi lear<Tab>` as `vi fish_color_` (17 suggestions, none of them contain `"lear"`, the closest suggestion is `"fish_color_search_match"`, in that it does contain `"ear"`).

Also, `vi lea<Tab>` completes to `vi ___fish_git_prompt_c` (42 available completions, all internal fish variable names, only two actually contain the string `"lea"`).

### Additional information:

`vi le<Tab>` and `vi learn<Tab>` both behave correctly.

`vi lear<Right-arrow>` works correctly.

---
Fish version: fish, version 2.2.0-680-ga701264

Operating system: tested on Debian and OS X, installed from source and homebrew respectively.

Terminal or terminal emulator: the same on iTerm2, xfce4-terminal, gnome-terminal, etc.

**Comment by faho** [comment]
I can't reproduce this, neither with vim-as-vi nor with ex-vi-as-vi, and I don't know why this would happen.

The vi completions are quite simple, here's the complete current state:

```fish
# plain vi (as bundled with SunOS 5.8)
# todo:
# -wn : Set the default window size to n
# +command : same as -c command


# Check if vi is really vim
if vi --version > /dev/null ^ /dev/null
    complete -c vi -w vim
else
    complete -c vi -s s --description 'Suppress all interactive user feedback'
    complete -c vi -s C --description 'Encrypt/decrypt text'
    complete -c vi -s l --description 'Set up for editing LISP programs'
    complete -c vi -s L --description 'List saved file names after crash'
    complete -c vi -s R --description 'Read-only mode'
    complete -c vi -s S --description 'Use linear search for tags if tag file not sorted'
    complete -c vi -s v --description 'Start in display editing state'
    complete -c vi -s V --description 'Verbose mode'
    complete -c vi -s x --description 'Encrypt/decrypt text'
    complete -c vi -r -s r --description 'Recover file after crash'
    complete -c vi -r -s t --description 'Edit the file containing a tag'
    complete -c vi -r -c t --description 'Begin editing by executing the specified  editor command'
end
```

So I have a few questions here:

- Are you using our vi completions or third-party ones (like from an OMF plugin or such)? Something like `for i in $fish_complete_path/vi.fish; test -e $i; and echo $i; end` should help you identify which file takes precedence.

- Do you have anything interesting in your configuration? (It's always preferable if you upload the entire thing)

- Is there a reproduction step missing? Does this work in any kind of directory or a specifically prepared one in /tmp or only in your $HOME?

- Can you reproduce with git master (or the Integration_2.3.0 branch)? There's nothing specifically standing out, but it's always nice to compare

**Comment by jldailey** [comment]
Ahh maybe this is the culprit then:

`alias vi="env SHELL=/bin/bash vim"`

This is how `vi` is defined for me, maybe that isn't triggering the vi completion rules at all?

The completion rule that appears to be running is something like "search executables, fuzzy search variables, then search files" for completions.

For instance `vi le<Tab>` produces `vi less`, completing the executable `/bin/less`, `"lea"` and `"lear"` get a fuzzy match on variables, but only `vi learn<Tab>` completes to the file.  Perhaps you recognize this as some kind of default completion logic?

**Comment by jldailey** [comment]
Also, I didn't do anything manual to the vi completions, this is the output of that `for` loop.
```
/usr/local/stow/fish-latest/share/fish/completions/vi.fish
/home/jldailey/.local/share/fish/generated_completions/vi.fish
```

The generated completions all look right and normal.

**Comment by faho** [comment]
>Ahh maybe this is the culprit then:

>`alias vi="env SHELL=/bin/bash vim"`

Yes, it is. `alias` sets up wrapping completions, so it will set your `vi` to be an alias of `env`. In which case variable names are a sensible thing to complete.

What you probably want here is to set up a function instead:

```fish
function vi --wraps vim
    env SHELL=/bin/bash vim
end
```

**Comment by jldailey** [comment]
Thanks!
