### ISSUE TITLE
Tmux split window changes prompt in Git projects/directories

### ISSUE THREAD

**Issue by ForrestCKoch** [fish-shell/fish-shell#2973]
When inside a git project/directory within a split-window of tmux, the prompt is replaced with ">"

### Reproduction Steps:

Using **Fish**  with **Tmux** cd into git directory/project within a split-window of tmux

### Expected behavior:

Normal prompt to be shown

### Observed behavior:

Prompt replaced with ">"

### Additional information:

  

---
Fish version: 2.2.0

Operating system: 4.5.0-1 ARCH

Terminal or terminal emulator: tmux with konsole

**Comment by faho** [comment]
This is a duplicate of #904 - your tmux splits are so small that we think we couldn't display your full prompt, so we shorten it. Only we're a bit stupid  about it.

**Comment by ForrestCKoch** [comment]
Thank you! and sorry for the duplicate.  I did search, just not well enough apparently.

**Comment by faho** [comment]
@ForrestCKoch: Not surprising, the title for that wasn't great. I've now changed it to something hopefully better.
