### ISSUE TITLE
Autocomplete fails on directories that include parenthesis in the path

### ISSUE THREAD

**Issue by davidbarsky** [fish-shell/fish-shell#2975]
Whenever I’d tab autocomplete on a directory that includes a parenthesis in the path (such as `~/Dropbox/School\ \(Current\)/Middle\ Eastern\ Politics/Saudi\ Arabia/`—my most recent example...), fish throws a stack trace (see below). Weirdly, fish also completes the path.

```
- (line 1): current
            ^
in command substitution
	called on line -1 of file -

from sourcing file -
	called on line 60 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/eval.fish

in function 'eval'
	called on line 45 of file /usr/local/Cellar/fish/2.2.0/share/fish/functions/__fish_complete_cd.fish

in function '__fish_complete_cd'
	called on standard input

in command substitution
	called on standard input
```

### Reproduction Steps:

1. Find a path with round parenthesis in the name.
2. Try to tab-complete on the directory (using `cd`, in my case.)

### Expected behavior:

The tab-completion works.

### Observed behavior:

The tab completion works, but fish spits out a stack trace after each time `<tab>` is hit.

### Additional information:

I’m using Oh My Fish, but this problem has existed for a while now. 

Thanks for all the great work that y’all do! ❤️ 

---
Fish version: fish, version 2.2.0

Operating system: OS X 10.11.4, fish installed via Homebrew.

Terminal or terminal emulator: Apple Terminal

**Comment by davidbarsky** [comment]
Oh, my bad—I didn’t see that this issue was resolved in #2735.

**Comment by krader1961** [comment]
Technically it's a dup of #952 (#2735 is itself a dup of it) fixed by commit https://github.com/fish-shell/fish-shell/commit/0a99772572ab8632f103f05570da707683980d17 that is in the 2.3.0 release currently in beta testing.

**Comment by davidbarsky** [comment]
@krader1961 Ah, gotcha. Somehow I didn’t see those issues when writing this up. Thanks anyways!
