### ISSUE TITLE
fish_update_completion not capuring some man pages

### ISSUE THREAD

**Issue by wernight** [fish-shell/fish-shell#2977]
fish_update_completion not capuring some man pages and no way to debug.
### Reproduction Steps:
1. Install gcloud (e.g.: `curl -L https://sdk.cloud.google.com | bash`)
2. sudo $(which gcloud) meta generate-help-docs --manpage-dir=/usr/local/man/
3. fish_update_completions
### Expected behavior:

Should have captured `gcloud` completion under `~/.config/fish/generated_completions/`.

Could show which directories it looked at and any error it found.
### Observed behavior:

$ man --path
/usr/share/fish/man:/usr/local/buildtools/java/jdk/man:/usr/local/man:/usr/local/share/man:/usr/share/man

But there is no way to debug why it didn't include the directory with gcloud man pages.

Setting `MANPATH` to `/usr/local/man/` and running `fish_update_completions` does work.
### Additional info

`/usr/local/man` is symlinked to `/usr/local/share/man`.

`set -x MANPATH /usr/share/fish/man /usr/local/buildtools/java/jdk/man /usr/local/man /usr/local/share/man /usr/share/man` does **not** work: Not capturing gcloud.

`set -x MANPATH /usr/share/fish/man /usr/local/buildtools/java/jdk/man /usr/local/share/man /usr/share/man` does work: Capturing gcloud (i.e. removing `/usr/local/man`).

---

Fish version: fish, version 2.0.0

Operating system: Ubuntu LTS

**Comment by faho** [comment]
>Fish version: fish, version 2.0.0

That version is almost 3 years old. Can you try a newer one?

Also, what does `manpath` say, without setting $MANPATH? Mine contains /usr/local/share/man.

**Comment by zanchey** [comment]
You can run the utility directly to get more information - something like `/usr/share/fish/tools/create_manpage_completions.py --verbose 2`. As @faho says, there have been some major improvements in the last couple of years so it might be worth trying a newer version.

**Comment by wernight** [comment]
I wish but I'm bound to Ubuntu LTS on the machine I've that issue. Possibly already resolved.

`/usr/share/fish/tools/create_manpage_completions.py --verbose 2` seems to expect many arguments but not sure what in order to simulate `fish_update_completions`.

**Comment by zanchey** [comment]
Have a look at the output of `functions fish_update_completions` and see if you can work something out.

Our PPA does ship packages for Precise, if that would suit - if not you might need to contact the Ubuntu maintainer as we don't maintain 2.0.0 any more.

**Comment by wernight** [comment]
I managed to update to 2.2.0 and ran in verbose mode to get details:

````
Considering /usr/local/man/man1/gcloud.1
   /usr/local/man/man1/gcloud.1 parsed successfully
Considering /usr/local/share/man/man1/gcloud.1
   /usr/local/share/man/man1/gcloud.1 contains no options or is unparsable (tried parser Deroffing man parser)
````

**Comment by faho** [comment]
Here's what I get on both 2.2.0 _and_ HEAD master:

>Considering /usr/share/man/man1/gcloud.1.gz
   Trying parser Deroffing man parser
   /usr/share/man/man1/gcloud.1.gz parsed successfully
   Successfully parsed 1 / 1 pages

(different path because I've installed via my package manager)

It then generates a completions file, but it's.... rather barren, offering only options and not commands.

Which is unsurprising, considering that the man pages are heavily split - per-command, so you have gcloud(1), gcloud_init(1) and so on. I can't think of any other tool that does it that way and the generator doesn't handle subcommands (and I'm not sure it's possible to do reliably) so we'd need to write gcloud completions by hand.

@wernight: Can you upload your copy of gcloud.1? Maybe I've just installed a different version of it that's parseable. I'll also have to check what we rely on to parse this stuff, maybe one of your system utilities is offering slightly different output.

In any case, even if we fixed the generation for you, the generated completion won't be up to snuff.

**Comment by wernight** [comment]
I have better than that, here is a `Dockerfile`:

````
FROM debian:jessie

RUN apt-get update && \
    apt-get install -y ca-certificates curl

# Install gcloud
RUN echo "deb http://packages.cloud.google.com/apt cloud-sdk-jessie main" \
        | tee /etc/apt/sources.list.d/google-cloud-sdk.list && \
    curl -L https://packages.cloud.google.com/apt/doc/apt-key.gpg \
        | apt-key add - && \
    apt-get update && \
    apt-get install -y google-cloud-sdk

# Install Fish
RUN echo 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_8.0/ /' >> /etc/apt/sources.list.d/fish.list && \
    apt-get update && \
    apt-get install -y --force-yes fish

RUN gcloud meta generate-help-docs --manpage-dir=/usr/local/man/

RUN fish -c 'fish_update_completions'

RUN fish -c 'eval $__fish_datadir/tools/create_manpage_completions.py --manpath --cleanup-in ~/.config/fish/completions --cleanup-in ~/.config/fish/generated_completions --verbose 2 --progress ^err.txt'
RUN grep -C 1 gcloud.1 err.txt
````

Just create it in an empty directory and run `docker build .`. Output should end like:

````
Considering /usr/local/man/man1/gcloud.1
   Trying parser Deroffing man parser
   /usr/local/man/man1/gcloud.1 parsed successfully
Considering /usr/local/man/man1/gcloud_alpha.1
--
   /usr/local/man/man1/gcloud_version.1 contains no options or is unparsable (tried parser Deroffing man parser)
Considering /usr/local/share/man/man1/gcloud.1
   Trying parser Deroffing man parser
   /usr/local/share/man/man1/gcloud.1 contains no options or is unparsable (tried parser Deroffing man parser)
Considering /usr/local/share/man/man1/gcloud_alpha.1
--
   /usr/share/man/man1/from.1.gz parsed successfully
Considering /usr/share/man/man1/gcloud.1.gz
   Trying parser Deroffing man parser
   /usr/share/man/man1/gcloud.1.gz contains no options or is unparsable (tried parser Deroffing man parser)
Considering /usr/share/man/man1/gcloud_alpha.1.gz
````

Isn't Git also having many man pages? I'd be interesting to know if Fish can handle gcloud-like man pages or if it's an issue with gcloud (in which case I could bring it up to the gcloud team).

**Comment by faho** [comment]
Unfortunately it seems I can't get docker to work (fails resolving httpredir.debian.org, might be an issue with my internet).

However I've just tried the 2.2.0 version of the generator on my raspberry pi running Debian Jessie and it worked on the copy of the man page I have.

>I'd be interesting to know if Fish can handle gcloud-like man pages

The generator can't.

**Comment by bmintz** [comment]
@faho Regarding separate man pages for sub commands: although the git man pages do this, I imagine *those* completions are handled specially.

**Comment by zanchey** [comment]
I don't know that there's much more that we can do here; the gcloud command looks complex enough that it probably needs handwritten completions.

**Comment by krader1961** [comment]
I'm closing this because the `gcloud` CLI is sufficiently complex that there is absolutely no hope of fish generating useful completions from its man page. We would love to see someone who uses this tool provide us with a custom completion script.
