### ISSUE TITLE
makefile dependency maintenance is too brittle

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2978]
After committing my recent change to improve the include-what-you-use (IWYU) experience by folding the `make iwyu` target into the `make lint` target it occurred to me I didn't update the Makefile dependencies. There is a `make depend` build target but it produces ugly output. Worse, people need to remember to run it. Googling `makefile auto dependencies` turned up [this document](http://make.mad-scientist.net/papers/advanced-auto-dependency-generation/) which describes an elegant method for deriving the dependencies automatically when they are needed. This issue is for investigating whether such a mechanism can be employed by this project in order to eliminate the `make depend` build target.

**Comment by krader1961** [comment]
Note that the solution documented in the [link]((http://make.mad-scientist.net/papers/advanced-auto-dependency-generation/) I included in the original problem statement appears to have been incorporated into the official Gnu [make documentation](https://www.gnu.org/software/make/manual/html_node/Automatic-Prerequisites.html).

**Comment by zanchey** [comment]
Sounds good to me.

**Comment by mqudsi** [comment]
I'm closing this as with the recent switch to cmake it's no longer directly relevant.
