### ISSUE TITLE
[HELP] Fish likes spitting out 0; with a certain terminfo, need help debugging

### ISSUE THREAD

**Issue by ShadowKyogre** [fish-shell/fish-shell#2979]
I'm pretty sure this is an upstream bug with the terminfo provided in the README of <http://repo.or.cz/w/fbpad.git>. However, I wanted to ask here since I can only spot this problem with fish. I'm having trouble locating the relevant line(s) in fish so I can properly debug the terminfo and/or find out what escape codes it's printing so I can properly patch fbpad.

### Reproduction Steps:

0. Grab the [fbpad-256.info](https://ptpb.pw/tkf8.info) (Syntax highlighted copy: [fbpad-256.info](https://ptpb.pw/tkf8/terminfo))
1. Compile fbpad
2. Compile the terminfo provided and put it into where your system finds terminfos. EG: `tic -x -o /usr/share/terminfo path/to/fbpad-256.info`
2. Launch fish inside fbpad
3. Set the TERM variable to fbpad-256
4. Do any command after that

### Expected behavior:

No printing 0;'s before and after each command.

### Observed behavior:

Fish prints 0;'s before each command. See the attached screenshot for more details.

![fish-fbpad-256](https://cloud.githubusercontent.com/assets/673620/14860729/ec3e5316-0c5e-11e6-961a-66048f958ab4.png)

Here's a shot of bash in fbpad for comparison using the same TERM variables
![bash-fbpad-256](https://cloud.githubusercontent.com/assets/673620/14861340/ad6dad8c-0c61-11e6-8dc0-1183575bd04d.png)

### Additional information:

This problem only occurs when launching fish directly with the provided terminfo.

---
Fish version: fish, version 2.2.0

Operating system: Arch Linux

Terminal or terminal emulator: fbpad

**Comment by krader1961** [comment]
That's the result of fish trying to set the terminal title. See the section "Programmable title" in http://fishshell.com/docs/current/index.html. To inhibit this just add the following to your *config.fish*:

```
function fish_title
end
```

**Comment by ShadowKyogre** [comment]
Gotcha! Thanks for the info. The issue definitely lies in fbpad then. I'll put a workaround for this in my fish config and contact upstream on how to fix how it handles unknown escape codes.
