### ISSUE TITLE
Tab completion of git options broken?

### ISSUE THREAD

**Issue by seanh** [fish-shell/fish-shell#298]
Some git commands work and at least some options are suggested when you type - then hit tab, e.g.:

    git status -<tab>

Others tab-complete to --help right away without any other suggestions, e.g.

    git add -<tab>

Others take a long time, e.g.

    git log -<tab>

hangs for many seconds and finally suggests only --help, --pretty and --pretty=

What's going on?

Suggestions for the git subcommands do seem to work, e.g.

    git <tab>

prints out all the subcommands with help messages,

**Comment by paymog** [comment]
Running `fish_update_completions` fixed git tab completes for me too. However, aliased git commands don't get completed correctly. As an example, I've aliased `git checkout` to `gco`. Running `git checkout ma<tab>` successfully completes to `git checkout master` but `gco ma<tab>` does not complete at all.

**Comment by ridiculousfish** [comment]
How did you alias it?

**Comment by paymog** [comment]
In ```~/.config/fish/config.fish``` I have the following line: ```alias gco "git checkout"```

**Comment by ridiculousfish** [comment]
Ok, see [this comment](https://github.com/fish-shell/fish-shell/issues/393#issuecomment-52378150) and the 'gco' example. You might prefer using an abbreviation:

    set -U fish_user_abbreviations $fish_user_abbreviations 'gco git checkout'

Just run that once, don't put it in .config. See how you like that.

**Comment by paymog** [comment]
Oh, neat. Thanks!

**Comment by faho** [comment]
This is most likely outdated and should probably be closed.

**Comment by dgutov** [comment]
Maybe it should. `git add -` offers quite a few options now. `git log -` doesn't hang and offers completions right away; still the same three, though. So there are still quite a few missing.

**Comment by faho** [comment]
Quite frankly, there's been a ton of change in the git completion, including adding of options.

Compare 39a2fd1717dc69b9f4643bb6a2060713c2e5f636 (the state of git.fish when this was opened) to 8e0c1c70ce6c0f9ff3e3fadb983a712fcc57e3e6 (the current state). It now features options for all git commands I've ever used, custom commands, stashes.... Not that it's perfect, but the options _do_ show up, so this is, unless I just can't _reproduce_ it, outdated.

**Comment by dgutov** [comment]
They do. So if we understand the report as complaint of completions being "broken", then it should certainly be closed.

**Comment by ridiculousfish** [comment]
Yep, this is ancient history. Please speak up if you think this should remain open.

**Comment by pickfire** [comment]
Is it true that `fish_update_completions` not designed for performance as it uses `python`? It took me about 5 minutes to finish the command as it only uses single core.

**Comment by ridiculousfish** [comment]
Yeah, it's something designed to be run only rarely.

**Comment by pickfire** [comment]
I think it should have an option to run with multiple cores to make it faster.

**Comment by ridiculousfish** [comment]
Especially since fish is on a supercomputer #2099!

**Comment by pickfire** [comment]
So, make use of **threading**?

**Comment by nemoDreamer** [comment]
I know this issue is closed, but when I run `fish_update_completions`, I don't get `git.fish`:

```bash
 ~ > ll ~/.local/share/fish/generated_completions/ | grep git
-rw-r--r--  1 philip  staff   216B Oct 15 11:05 git-am.fish
-rw-r--r--  1 philip  staff   230B Oct 15 11:05 git-apply.fish
-rw-r--r--  1 philip  staff   271B Oct 15 11:05 git-branch.fish
-rw-r--r--  1 philip  staff   614B Oct 15 11:05 git-cat-file.fish
-rw-r--r--  1 philip  staff   249B Oct 15 11:05 git-checkout.fish
-rw-r--r--  1 philip  staff   733B Oct 15 11:05 git-config.fish
-rw-r--r--  1 philip  staff   251B Oct 15 11:05 git-diff-files.fish
-rw-r--r--  1 philip  staff   251B Oct 15 11:05 git-diff-index.fish
-rw-r--r--  1 philip  staff   317B Oct 15 11:05 git-diff-tree.fish
-rw-r--r--  1 philip  staff   233B Oct 15 11:05 git-diff.fish
-rw-r--r--  1 philip  staff   229B Oct 15 11:05 git-fsck.fish
-rw-r--r--  1 philip  staff   245B Oct 15 11:05 git-hash-object.fish
-rw-r--r--  1 philip  staff   396B Oct 15 11:05 git-log.fish
-rw-r--r--  1 philip  staff   227B Oct 15 11:05 git-p4.fish
-rw-r--r--  1 philip  staff   408B Oct 15 11:05 git-push.fish
-rw-r--r--  1 philip  staff   355B Oct 15 11:05 git-reflog.fish
-rw-r--r--  1 philip  staff   361B Oct 15 11:05 git-rev-list.fish
-rw-r--r--  1 philip  staff   346B Oct 15 11:05 git-rev-parse.fish
-rw-r--r--  1 philip  staff   235B Oct 15 11:05 git-send-email.fish
-rw-r--r--  1 philip  staff   534B Oct 15 11:05 git-send-pack.fish
-rw-r--r--  1 philip  staff   233B Oct 15 11:05 git-show.fish
-rw-r--r--  1 philip  staff   233B Oct 15 11:05 git-status.fish
-rw-r--r--  1 philip  staff   188B Oct 15 11:05 git-tag.fish
-rw-r--r--  1 philip  staff   391B Oct 15 11:05 git-update-index.fish
-rw-r--r--  1 philip  staff   245B Oct 15 11:05 git-verify-commit.fish
-rw-r--r--  1 philip  staff   236B Oct 15 11:05 git-verify-tag.fish
-rw-r--r--  1 philip  staff   899B Oct 15 11:05 git-worktree.fish
-rw-r--r--  1 philip  staff   1.5K Oct 15 11:05 gitk.fish
```

I've always installed git using homebrew, and even my aliases (configured in `~/.gitconfig`) used to complete fine:

```yaml
[alias]
  aa = add --all
  ap = add --patch
  br = branch
  ca = commit --amend
  ci = commit -v
  co = checkout
  df = diff
  lg = log -p
  st = status
```

Now, when I type `git [TAB]` or `git checkout [TAB]`, I get:

```bash
fish: Unknown command '__fish_git_needs_command'
in command substitution
	called on standard input
```

### Troubleshooting:

- `/Users/philip/.local/share/fish/generated_completions/` is in my `$fish_complete_path`
- I recently upgraded my oh-my-fish to v2 (`omf`)

**Comment by nemoDreamer** [comment]
Opened an issue w/ oh-my-fish/oh-my-fish/issues/126. Probably a better place.

**Comment by faho** [comment]
@nemoDreamer: I don't think it's omf-related. 

>I know this issue is closed, but when I run fish_update_completions, I don't get git.fish:

That's because git has more than one manpage, and our manpage parsing utility doesn't know that.

Even if it didn't, you still wouldn't want the generated version because we have a wonderful hand-rolled version that very handsome people have worked on, and that's the one you're calling.

Now, __fish_git_needs_command is defined in [share/completions/git.fish](https://github.com/fish-shell/fish-shell/blob/master/share/completions/git.fish), together with the completions that are calling them. This will be installed to (I think) $__fish_datadir/completions.

What I'd like to know is 

1. Your `fish --version`

2. The contents of your $__fish_datadir/completions/git.fish.

3. Your own customizations, mostly functions - there have been reports of fish breaking with weird aliases (at one point, defining something called `sgrep` caused a rather nice one, or defining a function called `_`)

**Comment by nemoDreamer** [comment]
Thanks for the speedy reply!!!

1. `fish, version 2.2.0`
2. A ton of stuff: https://gist.github.com/nemoDreamer/e44c6497f42587bd58da, but most importantly: `-rw-r--r--  1 philip  admin    25K Sep 14 01:00 git.fish`
3. I'll be happy to get normal usage (`git checkout [TAB]`) to work, and will add my aliases as fish abbr's if need be.

**Comment by nemoDreamer** [comment]
I `rm -rf ~/.local/share/fish/generated_completions/*` just to be sure, and restarted terminal.

And `$__fish_datadir` is definitely in my `$fish_complete_path`.

```
 ~ > echo $__fish_datadir
/usr/local/Cellar/fish/2.2.0/share/fish
 ~ > echo $fish_complete_path
/Users/philip/.local/share/omf/pkg/z/completions
/Users/philip/.local/share/omf/pkg/omf/completions
/Users/philip/.local/share/omf/pkg/git-flow.git/completions
/Users/philip/.local/share/omf/pkg/fish-nuggets/completions
/Users/philip/.config/fish/completions
/usr/local/Cellar/fish/2.2.0/etc/fish/completions
/usr/local/Cellar/fish/2.2.0/share/fish/vendor_completions.d /usr/local/Cellar/fish/2.2.0/share/fish/completions
/Users/philip/.local/share/fish/generated_completions
```

**Comment by nemoDreamer** [comment]
Ran `omf uninstall fish-nuggets` (I tried it's completions, but they were lacking. I'd manually removed it from my "bundle", but I guess that's not enough.)

Still getting the `__fish_git_needs_command` error.

**Comment by faho** [comment]
>A ton of stuff: https://gist.github.com/nemoDreamer/e44c6497f42587bd58da, but most importantly: -rw-r--r-- 1 philip admin 25K Sep 14 01:00 git.fish 

I actually meant the contents of _git.fish_ in there.

>/Users/philip/.local/share/omf/pkg/git-flow.git/completions

It's quite possible this has git completions.

See which completion takes precedence:

```fish
for dir in $fish_complete_path
  [ -f $dir/git.fish]; and echo $dir/git.fish; and break
end
```

if it's anything outside of fish's, try moving it aside. If it's git-flow, file an issue with that.

**Comment by bpinto** [comment]
I'd remove the `git-flow` plugin to make sure it's not affecting it as @faho suggested.

But adding `echo 'share/fish/completions/git.fish loaded'` to the top of `$__fish_datadir/completions/git.fish` should let you know if the file is being loaded by fish.

**Comment by nemoDreamer** [comment]
Damn, @faho ! That was it...! `/Users/philip/.local/share/omf/pkg/git-flow.git/completions/git.fish`
(Btw, I needed to add a space in front of that `]` in your snippet)

**Comment by nemoDreamer** [comment]
I guess this issue can be re-closed... :wink:
Thanks, everybody!

(Now I just need got flow completions that don't nuke fish's built-in ones)

**Comment by faho** [comment]
> (Btw, I needed to add a space in front of that ] in your snippet)

Yes, sorry, that was a typo.

>(Now I just need got flow completions that don't nuke fish's built-in ones)

Where's that git-flow thing maintained? What do these completions add? If they do add anything, maybe we could just take it upstream. (Or of course it could `source` the default completions)

**Comment by bpinto** [comment]
@faho 
I'm not a git-flow user myself, so I don't know if the completions are as expected, I could open a PR if you think they are.

We usually tell people to add completions directly to fish-shell, I don't remember why we didn't for this plugin though.

**Comment by faho** [comment]
> I'm not a git-flow user myself, so I don't know if the completions are as expected, I could open a PR if you think they are.

Why don't you open a PR and then we'll see what needs to be done? I did take a cursory look, and one thing I noticed is that it would need to go into share/completions/git.fish (and be guarded by `type -q git-flow` or similar).
