### ISSUE TITLE
stop bundling pcre2 

### ISSUE THREAD

**Issue by snnw** [fish-shell/fish-shell#2985]
Besides it being bad practice (cf. [here](https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies) and [here](https://fedoraproject.org/wiki/Bundled_Libraries?rd=Packaging:Bundled_Libraries)), bundling pcre2 has caused some build and security issues in the past (#2938, #2469, #2446).

I understand that there is currently a (more or less) valid reason for bundling pcre2 due to some distros not shipping it.  We should track which distros and make sure there are packaging requests filed. Maybe @krader1961 can expand here.

**Comment by zanchey** [comment]
- [ ] Apple OS X

**Comment by floam** [comment]
If it's just OS X - we should leave that up to the package vendor to properly install the dependency. It would be trivial to include a OS X libpcre2 pkg installer (generated by MacPorts) as part of the installed distribution as a subcomponent. Or make a CocoaPod for Xcode?

**Comment by floam** [comment]
[https://github.com/auriamg/macdylibbundler](macdylibbunlder) should take care of the .app we also distribute if that will continue.

**Comment by andrex-e-schulman** [comment]
- [ ] Cygwin

**Comment by yselkowitz** [comment]
@andrex-e-schulman [not anymore](https://cygwin.com/ml/cygwin-announce/2016-05/msg00051.html).

**Comment by DomT4** [comment]
> It's for users - this is best left to the package maintainer to properly pull down and install the dependency - Homebrew, fink, MacPorts all have pcre2 packages, and can be expected to make sure this is installed properly despite us including a modified pcre2 source tree.

Homebrew already enforces a `pcre2` dependency for `HEAD` & the beta releases FWIW. That'll be applied to stable as well when the time comes.

**Comment by faho** [comment]
Would it be possible to make our bundled pcre2 opt-in, i.e. requiring a "--with-bundled-pcre2" option?

Or should we stop doing the .app bundles? @ridiculousfish: Do you have any stats on how much these are used?

**Comment by zanchey** [comment]
It's autodetected and opt-out, so if there's a system version installed the build process uses that. You can use `--without-included-pcre2` to force the issue.

**Comment by faho** [comment]
Yeah, but how about making that the default, i.e. making it opt-in?

I'm asking because I just filed a bug against the archlinux package because it used the bundled version (even though I can personally confirm that the system version works), so presumably that maintainer didn't notice it.

By doing that, we could minimize the use of the bundled pcre2 and nudge distros towards packaging it.

**Comment by zanchey** [comment]
I think that's more likely to penalise those building from source than to encourage behaviour change downstream.

It also complicates the (Debian/RHEL) package building significantly, as the currently-supported versions of those distributions do not have PCRE2 and will not get it.

**Comment by yselkowitz** [comment]
Note that pcre2 is in EPEL, so EPEL's fish could also use it (currently it appears to use the bundled version).

**Comment by mqudsi** [comment]
I think overall we're happy with the pcre2 situation, primarily as it currently stands with the cmake build system. The option of using the platform pcre2 is there, and it's going to cause problems/complicate things greatly to drop the dependency entirely for some of our key target platforms.

If anyone would like to tackle this, including taking care of the distro packages to use the correct pcre2 dependency, feel free to reopen of course!
