### ISSUE TITLE
do actual Xcode builds on Travis or perhaps switch to another CI

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2986]
My recent changes to the non-Xcode builds of fish to make all *_.cpp_ modules independently compiled rather than `#include`'d into another module broke OS X Xcode project builds. That's because, despite being a long time user of OS X, I'm not a OS X developer and didn't think to verify that those changes didn't break the Xcode project configuration. We need a way to verify that changes to the non-Xcode build environment (i.e., traditional UNIX Makefiles) don't break Xcode project builds. A possible solution is to leverage Travis CI by asking it to build fish with xctool. Thanks to @floam for suggesting that potential solution to this issue.

**Comment by faho** [comment]
We now have Travis doing xcode builds.

**Comment by floam** [comment]
KIND OF! Not really.

We're using the Xcode SDK to do autotools builds, right now. It's Darwin, and Xcode is there, bot not testing the Xcode project.

I (or someone) still needs to get Travis taught to do *actual* `fish.xcodeproj` Xcode builds with `xctool`.

**Comment by krader1961** [comment]
FWIW, We've had numerous discussions on Gitter since this was opened where various contributors have expressed displeasure with Travis CI. Slant started a topic about the best CI tools: https://www.slant.co/topics/799/~best-continuous-integration-tools. It might be worth considering whether we should stick with Travis or switch.

**Comment by zanchey** [comment]
See also #3268 where I looked at some options. I can arrange hosting for most of those.

The other advantage of going to Buildbot, Jenkins or Gitlab CI would be that we can deploy tests on just about any OS - which would include FreeBSD, Cygwin (and even Solaris). This would give us a lot more coverage over various systems.

**Comment by faho** [comment]
We're not shipping xcode anymore, so this seems moot.
