### ISSUE TITLE
Resuming suspended programs

### ISSUE THREAD

**Issue by maandree** [fish-shell/fish-shell#299]
If you start `emacs -nw` and in it press C-z it is suspended.

In bash it can be resumed by any of `%emacs`, `fg emacs`  or `fg 1` (provided the job's ID is 1 which it is for the first started job).

In fish, when typing % (just the character) this is printed. `Warning: principal_parser called off of main thread. Break on debug_thread_error to debug.` and for every followning typed key it is printed again. And ENTER cannot be typed.

When running `fg emacs` this is printed:

```
troff: fatal error: can't open `/usr/share/fish/man/fg.1': No such file or directory
fg: Argument “emacs” is not a number
```

When running `fg 1` this is printed:

```
troff: fatal error: can't open `/usr/share/fish/man/fg.1': No such file or directory
fg: No suitable job: 1
```

**Comment by pickfire** [comment]
Is there any way for fish to resume suspended with `fg` by entering <kbd>ctrl</kbd> + <kbd>z</kbd> again in fish to behave like zsh?

**Comment by BarbzYHOOL** [comment]
When I type "fg 1" or "fg 2" it does nothing, but "fg %1" works

How to set it to use "fg 1" instead? like in bash
