### ISSUE TITLE
enhance *src/keyreader.cpp* so it provides more value than `xxd` and `od` provides

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2991]
Is *src/keyreader.cpp* used by anyone? I'm working my way through making the fish C++ code follow a consistent style and noticed the aforementioned module. It's not documented and doesn't do anything you can't do using other tools like `od` and `xxd`.

----
For 2.3.1 release:
- [x] Documentation needs to match program output
- [x] Fix HTML display error
- [x] Update release notes

**Comment by ridiculousfish** [comment]
`make key_reader` builds the tool `key_reader`. This is a little nicer than the alternatives (I use bash's `read`), but it's odd that it's part of fish. I have no objection to eliminating it.

**Comment by zanchey** [comment]
I use it sometimes; seems like a low-cost thing to keep, although perhaps adding it as a build target to the Travis CI builds would help make sure it doesn't bitrot.

**Comment by krader1961** [comment]
I'm inclined to agree that we should keep it; especially since a couple of trivial enhancements I have in mind would make it much more useful than the alternatives and thus worth maintaining. Furthermore, I think we should rename it `fish_key_reader` and install it just like we do `fish_indent`. That would have the side-effect of causing Travis CI to build it.

The trivial enhancements include

1) Adding inter-char timing data.

2) Display control chars using their \cX equivalent as well as any backlash equivalent (e.g., \e for 0x1b) recognized by fish.

3) Use a fixed width for the numeric fields so the information remains vertically aligned.

A straightforward, but non-trivial, enhancement  is to recognize sequences that correspond to key names recognized by the `bind` command and display the key name.

**Comment by floam** [comment]
The program output in the docs doesn't match the program output and the rendered HTML displays incorrectly.

**Comment by floam** [comment]
I got new docs into 2.3.1.
