### ISSUE TITLE
Fish's Debian repository on OBS is signed with a weak digest algorithm

### ISSUE THREAD

**Issue by hugomg** [fish-shell/fish-shell#2994]
I'm running Debian 8 and to get the latest version of Fish I installed it from [the repository](https://build.opensuse.org/package/show?project=shells%3Afish%3Arelease%3A2&package=fish) that is linked on fishshell.com. Everything is working fine but whenever I run `apt update` I get the following warning message:

> W: http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_8.0/Release.gpg: Signature by key 24A63B31CAB41B33EC48801E2CE2AC08D880C8E4 uses weak digest algorithm (SHA1)

Is there a way to fix the package signature so this doesn't happen anymore?

For reference, this is the line I am using in my /etc/apt/sources.list:

    deb http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_8.0/ /

**Comment by zanchey** [comment]
Hopefully when we release 2.3.0 the repository metadata will get rebuilt with the newer hashes. There's no reliable way to regenerate it, unfortunately.

**Comment by krader1961** [comment]
Closing since there is nothing we can do about the existing fish 2.2.0 package. if this warning still occurs after the 2.3.0 release please reopen.

**Comment by zanchey** [comment]
```
$ gpg2 --verify --verbose --keyring /etc/apt/trusted.gpg download.opensuse.org_repositories_shells:_fish:_release:_2
_Debian\%5f8.0_._Release.gpg download.opensuse.org_repositories_shells:_fish:_release:_2_Debian\%5f8.0_._Release
Version: GnuPG v1.0.7 (GNU/Linux)
gpg: armor header:
gpg: Signature made Sat 21 May 2016 07:43:30 AWST using RSA key ID D880C8E4
gpg: using PGP trust model
gpg: Good signature from "shells:fish OBS Project <shells:fish@build.opensuse.org>" [unknown]
Primary key fingerprint: 24A6 3B31 CAB4 1B33 EC48  801E 2CE2 AC08 D880 C8E4
gpg: binary signature, digest algorithm SHA256
```

so I think we're good!
