### ISSUE TITLE
env var `fish_log_forks` not documented and not idiomatic

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#2995]
While working on issue #2980 I noticed debugging `printf()` calls are predicated on the undocumented environment var `fish_log_forks`. That env var reference should be removed (as well as the `g_log_forks` var) from the source and those printf's converted to `debug(2, ...)` calls.

**Comment by ridiculousfish** [comment]
I think this should be folded into a new logging mechanism, where you can enable logging of particular events you're interested in.

**Comment by krader1961** [comment]
I totally agree, @ridiculousfish. But as an expedient change I'm just going to switch these to use `debug()`. At least that way when we rewrite the logging subsystem they'll be easy to find.

**Comment by krader1961** [comment]
Also, FWIW, the existing fork debug printf's don't cover the case where posix spawn is used and the fork counts are off by one. I'll fix those while I'm touching that code.

**Comment by ridiculousfish** [comment]
Ok, sounds fine. If you want to just remove them that's fine too. Thanks!
