### ISSUE TITLE
The example  make fish 2> | less  in the documentation does not work

### ISSUE THREAD

**Issue by andgra2** [fish-shell/fish-shell#3003]
Documentation->Syntax overview->Piping has the following example:

`make fish 2> | less`

It does not work. It gives an error message.

### Reproduction Steps:

Let's use  echo x  instead of  make fish  to make the problem easier to reproduce.

1. Run the command:  `echo x 2> | less`

### Expected behavior:

No error message. Bug or error in documentation?

### Observed behavior:

The following error message:

```
Expected a string, but instead found a pipe                                                                                             
fish: echo x 2> | less                                                                                                                  
                ^
```         
### Additional information:
---
Fish version: fish, version 2.2.0-876-g1c6f6df

Operating system: ubuntu 64-bit, installed fish from github source code

Terminal or terminal emulator: neovims built in terminal emulator.

**Comment by faho** [comment]
It's an error in the documentation. Fortunately it's already been fixed in f6f982226a4d16ed8e740a66fe9a505a8df86e8c.

**Comment by andgra2** [comment]
Do I need to compile the documentation from source in order to get the latest one? Or are there some other way? I was looking in the current online documentation.

**Comment by krader1961** [comment]
The online documentation is updated when a new fish version is released. We're currently beta testing version 2.3 so the online docs will be updated soon. You can, of course, do `make doc` and put the resulting file:// URL in your browser to see the latest and greatest.
