### ISSUE TITLE
Inconsistent behaviour in brace expansion

### ISSUE THREAD

**Issue by andgra2** [fish-shell/fish-shell#3004]
Brace expansion seems a bit inconsistent in its behaviour, see below. The documentation is also not so clear about this case.

### Reproduction Steps:

1. Run: `begin; set -l arr a b; echo x{$arr,c}y; end`
2. Run: `begin; set -l arr a b; echo x{{a,b},c}y; end`

### Expected behavior:

I expect 1. to give the same output as 2, ie: `xay xby xcy `

This for consistency and simplicity reasons. I expect `$arr` and `{a,b}` to work in the same way in cases when they are both expanded.

### Observed behavior:

1. Outputs:  `xay xcy xby xcy`
2. Outputs:  `xay xby xcy`

### Additional information:

---
Fish version: fish, version 2.2.0-876-g1c6f6df
Operating system: ubuntu 64-bit, compiled fish from github source 

Terminal or terminal emulator: The builtin terminal emulator of neovim.

**Comment by krader1961** [comment]
Those examples are just variations of the problem reported in issue #3002.

**Comment by andgra2** [comment]
I think this is quite different than #3002.

Here we have only one `,` in the outermost brace expression, but the problem in #3002 needs two `,` in order to reproduce.

**Comment by jakwings** [comment]
fish seems like doing `echo x{$arr,c}y` this way:

```
Step 1: join(x, join&merge([a, b], c), y)
Step 2: join(x, [a, c, b, c], y)
Step 3: join(x, a, y)  join(x, c, y)  join(x, b, y)  join(x, c, y)
Result: xay xcy xby xcy
```

As to `echo x{{a,b},c}y`, I imagine fish is doing this:

```
Step 1: join(x, merge({a, b}, c), y)
Step 2: join(x, {a, b, c}, y)
Step 3: join(x, a, y)  join(x, b, y)  join(x, c, y)
Result: xay xby xcy
```
