### ISSUE TITLE
$ binding in vi-mode doesn't work correctly

### ISSUE THREAD

**Issue by andgra2** [fish-shell/fish-shell#3005]
The `$` binding in vi-mode doesn't work as expected.
### Reproduction Steps:
1. Run:  `fish_vi_key_bindings` or `fish_vi_mode` if your running an older version.
2. Type and **don't** press enter:  `echo hi`
3. Hit the escape key.
4. Type and **don't** press enter:  `$`
### Expected behavior:

The expected behaviour is that the cursor should be at the character `i`.
### Observed behavior:

The cursor is to the right of the character `i`.
### Additional information:

---

Fish version: fish, version 2.2.0-876-g1c6f6df
Operating system: Doesn't matter.
Terminal or terminal emulator: Doesn't matter

**Comment by krader1961** [comment]
There are a huge number of ways in which fish's vi mode behaves differently than Vi users expect. I've been annoyed with it from the day I started using fish six months ago; just not enough to spend the time to improve it given all the other things that need attention. Patches are welcomed :smile:

**Comment by andgra2** [comment]
Patch #3006

**Comment by andgra2** [comment]
I did a quick fix similar to the way the `w` binding was fixed earlier, but ideally `end-of-line` should be fixed. Some other bindings depends on its current behaviour. For example `A`, but that could be handled.

**Comment by andgra2** [comment]
Similarly `forward-word` could be fixed, so that we don't need the `forward-char` correction in the `w` binding. However this is another thing.

**Comment by ninrod** [comment]
is this fixed by #3006?

**Comment by faho** [comment]
@ninrod: That wasn't merged.
