### ISSUE TITLE
should fish send the terminfo `keypad_xmit` (aka `smkx`) string

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3008]
While working on enhancements to the `key_reader` program (issue #2991) I noticed that my terminal's arrow keys were not being detected as such according to the terminfo database. In other words, pressing the left-arrow key does not emit the sequence defined by the terminfo database as a left-arrow key.

That's because the terminfo definitions for `xterm`, `xterm-256color`, `screen-256color` and many others assume the terminal has been put into "cursor application mode" by sending the `keypad_xmit` (aka `smkx`) char sequences. Because fish isn't setting that mode the terminal sends the "normal mode" sequences (see https://www.iterm2.com/faq.html). The only reason those keys work as expected is because someone added key bindings for the "normal mode" sequences  (e.g., `bind $argv \e\[D backward-char`) in *fish_default_key_bindings.fish* and *fish_vi_key_bindings.fish* in addition to binding the terminfo sequences (e.g., `bind $argv -k left backward-char`).

It seems to me that fish should send the `keypad_xmit` initialization sequence when it starts, and control returns from an external program, since it acts as if it was a "full screen" application. This wouldn't require any changes to the existing key binding scripts AFAICT but would be more sensible and allow my modified `key_reader` program to provide more sensible output.

**Comment by faho** [comment]
This is essentially #2139 - though we should change the title.

There's a ton of stuff there, but the short of it is @zanchey committed a66d44054c4aae44c307b10bb10469b4565e5027 to fix it, and that one caused gnome terminal to fail (#2406). So it seemed we could choose between suckless' st failing and gnome-terminal and putty failing.

Let's track in 2139.
