### ISSUE TITLE
Defining an alt-delete binding interferes with '[' input

### ISSUE THREAD

**Issue by occivink** [fish-shell/fish-shell#3009]
Hi,
If I define an alt-del binding like so `bind $argv \[3\;3~ kill-word` (`[3;3~` is the output of pressing alt-del in termite) the binding itself works fine, but inputting `[` is delayed, meaning that the character only appears I've input another one (e.g. I press `[`, nothing appears, I press `b` and then both characters appear).

I'm using fish 2.2.0 with termite.

**Comment by faho** [comment]
>[3;3~ is the output of pressing alt-del in termite

No, it's not. You're missing an escape character (which is non-printing, so it won't be echoed back).

`bind \e"[3;3~" kill-word` should work.

**Comment by occivink** [comment]
It does work, thanks. Another quick question, is it possible to use `bind -k`with alt or ctrl modifiers?

**Comment by faho** [comment]
Unfortunately not.

**Comment by krader1961** [comment]
FWIW, I'll be committing an improved `key_reader` program (soon to be renamed `fish_key_reader`), complete with documentation, that will be installed by default and make it much easier to find out what you need to bind to.
