### ISSUE TITLE
Backgrounding commands run with "fish -c <command>" does not work.

### ISSUE THREAD

**Issue by gtmax** [fish-shell/fish-shell#3015]
### Observed behavior:

If I run a command via "fish -c <command>", and Ctrl-Z'ing appears to interrupt the command instead.

```
> fish -c 'sleep 10; echo "Done!"' # Ctrl-Z
^ZDone!
> fg
fg: There are no suitable jobs
```
### Expected behavior:

Same SIGSTP/SIGCNT via bash:

```
> bash -c 'sleep 10; echo "Done!"' # Ctrl-Z
'bash -c 'sleep 10; echo "Done!"'' has stopped
> fg
Send job 1, 'bash -c 'sleep 10; echo "Done!"'' to foreground

Done!
```

---

Fish version: fish, version 2.2.0

Operating system: Mac OS X, El Capitan, install via Homebrew 

Terminal or terminal emulator: iTerm2

**Comment by krader1961** [comment]
This is closely related, and possibly a duplicate, of issue #563. The job control semantics of fish are unusual. I'm going to label this a bug because I think the behavior described by the O.P. is wrong despite the fact fish is explicitly not a POSIX compliant shell.

**Comment by pirate** [comment]
You can achieve the desired behavior by combining bash + fish:
```bash
function background --description "Run a fish command in the background using a bash subshell"
	bash -c "fish -c '""$argv""' &"
end

background "sleep 5; echo hi"
```

**Comment by faho** [comment]
Works for me with 3.0.

I'm assuming it's been fixed with all the job control improvements.
