### ISSUE TITLE
Add a notion of modifier keys to bind

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#3018]
This is related to #3017, in that it is also needed to allow cross-terminal bindings without accidentally hardcoding something.

I can bind something to "down" (`\e[B` here) with `bind -k down something`, but when I want to bind something to alt+down, I need to bind the sequence (`\e[1;3B` in my case).

It would be nice if it were possible to say e.g. `bind --modifier alt -k down something` (though of course there's the issue of alt vs escape).

**Comment by krader1961** [comment]
Why not just allow alt as a prefix to the name key; e.g., `bind -k alt+down` and/or `bind -k alt-down`?

As for alt vs escape is that really an issue? Unlike X11, native MS Windows, etc. apps there isn't any way for console based programs like fish to know that the [Alt] key was pressed except by modifying the sequence the key would normally send. And it seems like the accepted standard for doing so is to prefix the sequence with an extra escape character.

**Comment by faho** [comment]
Yes, that would work too.

**Comment by faho** [comment]
Fixed by #10359
