### ISSUE TITLE
Put directories first when completing filenames

### ISSUE THREAD

**Issue by maxfl** [fish-shell/fish-shell#302]
I think it would be useful when one could find subfolders in the beginning of the list, because you usually definitely know, what you want to find in  the current folder: file or subfolder. So separating them would simplify the task of finding, when you are not sure about the first letters.

**Comment by krader1961** [comment]
Adding the "RFC" label because I think this proposal requires more discussion before being implemented.

**Comment by faho** [comment]
Okay, it doesn't seem to have broad acceptance, so I'm closing this.
