### ISSUE TITLE
Is there a place that people can share or show their fish scripts?

### ISSUE THREAD

**Issue by freewind** [fish-shell/fish-shell#3027]
This is a question, Is there a place that people can share or show their fish scripts? So I can learn more fish skills from other people easily

**Comment by krader1961** [comment]
In olden times that would have been done via messages to mailing lists like the one set up for [fish](https://lists.sourceforge.net/lists/listinfo/fish-users). But the fish user community doesn't like the old school mailing list solution. The modern alternative seems to be opening GitHub issues like you did. But, perhaps like you, I'm not satisfied with that solution. The [Fish Wiki](https://github.com/fish-shell/fish-shell/wiki), or something like it, is probably the best solution.

**Comment by pickfire** [comment]
@freewind, there are a lot of fish in https://github.com/fishery, I guess @bucaran might be able to guide you.

**Comment by kopischke** [comment]
@pickfire were you meaning to link to https://github.com/fisherman?

**Comment by bucaran** [comment]
@pickfire fishery → fisherman

**Comment by freewind** [comment]
Thanks for the suggestions, I just browsed these urls and I found scripts in https://github.com/fisherman are a little bit heavy although it's very useful. A website like <http://www.commandlinefu.com/commands> is quite like what I'm thinking, but which may not be easy to build by ourselves

**Comment by krader1961** [comment]
We already have our first entry on our wiki: https://github.com/fish-shell/fish-shell/wiki/Bash-Style-History-Substitution-(!!-and-!$)

Someone with an interest (wink, wink) should come up with a structure for the wiki that makes adding and finding such tips easy.

**Comment by pickfire** [comment]
@kopischke, that's just a suggestion, of course it might be better to show someone about fish's plugin manager like fisherman.

**Comment by bucaran** [comment]
@pickfire Your link points to a dead link. Can you fix it?

**Comment by pickfire** [comment]
@bucaran Wow, what happened to fishery? I didn't know when it just went missing like that.

**Comment by bucaran** [comment]
@pickfire Dead link. Can you fix it? :)

**Comment by coderstephen** [comment]
If you're into "package manager" kind of code sharing, there's also [Oh My Fish](https://github.com/oh-my-fish/oh-my-fish). Quite a few people use the package system to share their functions with other users. You can try browsing the various [plugin repos](https://github.com/oh-my-fish?query=plugin) if you want to learn from others' scripts too.

**Comment by pickfire** [comment]
@coderstephen, woah, oh my fish is very, very slow, I won't even dare to use it any more.

**Comment by therealpxc** [comment]
@pickfire would you mind posting some examples or describing the problematic use cases? I can file a bug report on OMF for you if you want.

**Comment by bj** [comment]
@therealpxc Just like [wahoo]() was slow and not very well designed, omf inherited the same problems.

* https://github.com/fisherman/fisherman/issues/69#issuecomment-179661994

Here is just one of the many reasons:

> oh-my-fish needs to initialize itself on startup and runs heavy computations that slow down your shell, on every session. Startup time is almost half a second with ~5 plugins, and can take up to two seconds with more than 10 plugins.

**Comment by coderstephen** [comment]
@brj Points 3, 4 and 5 will be addressed in the next release or two, and will no longer be true. Point 2 is true of any plugin manager, since any plugin that runs on init will do so anyway. Point 1 is true to support the features that we do.

**Comment by brj** [comment]
Just want to address your generalization:

> Point 2 is true of any plugin manager, 

False. Sure snippet-like plugins will perform "roughly" the same across plugin managers (still slower in omf due to the reasons given above), etc., but not _all_ "plugin managers" are a victim of 2. 

Related: #Performance section in https://github.com/fisherman/fisherman/issues/69#issuecomment-179661994

**Comment by pickfire** [comment]
@therealpxc, maybe it's because I use it on a rpi.

**Comment by faho** [comment]
I believe this question has been answered.

@freewind: If you'd like to share nifty fish scripts, feel free to do so on our wiki! If you want to see fish scripts, look at the plugin stuff or the ones that ship with fish.

**Comment by freewind** [comment]
@faho Thanks!
