### ISSUE TITLE
Fish doesn't scroll down terminal window or refresh screen

### ISSUE THREAD

**Issue by rerime** [fish-shell/fish-shell#3028]
Mac OS X, Terminal

1. Type some commands
![screen shot 2016-05-14 at 13 16 11](https://cloud.githubusercontent.com/assets/7099570/15267877/b3b63e34-19d6-11e6-8db9-7742660cf765.png)

2. Type comand before autocomplete
![screen shot 2016-05-14 at 13 16 26](https://cloud.githubusercontent.com/assets/7099570/15267888/d233f810-19d6-11e6-933c-db07c23be3cf.png)

3. Hit Tab for autocomplete
![screen shot 2016-05-14 at 13 16 38](https://cloud.githubusercontent.com/assets/7099570/15267893/e57620f6-19d6-11e6-8735-8292f00504eb.png)

Cursor goes up, but previous symbols still there. Better behaviour scroll up for doesn't rewrite previous output.

**Comment by krader1961** [comment]
What you're proposing is not possible. In general fish has no knowledge of the screen contents other than the current prompt and command line. There is no way for it to refresh the screen.

**Comment by rerime** [comment]
Ок, thanks.
