### ISSUE TITLE
cd: error on tab completing paths with parenthesis

### ISSUE THREAD

**Issue by Alloyed** [fish-shell/fish-shell#3029]
### Reproduction Steps:

```
$ mkdir -p "/tmp/(my path)"
$ cd /tmp/\(<tab>
```

It probably triggers with other special characters but I haven't tested those 

### Observed behavior:
```
$ cd /tmp/\(mUnexpected end of string, parenthesis do not match
- (line 1): begin; printf \%s\n /tmp/(m*/ 
 ;end <&3 3<&-
                                ^
from sourcing file -
	called on line 60 of file /usr/share/fish/functions/eval.fish

in function “eval”
	called on line 24 of file /usr/share/fish/functions/__fish_complete_cd.fish

in function “__fish_complete_cd”
	called on standard input

in command substitution
	called on standard input

source: Error while reading file “-”
y_path\)/
```
The completion actually works as intended, but the traceback obscures that fact.

---
Fish version: fish, version 2.2.0

Operating system: Arch linux, distro package

Terminal or terminal emulator: gnome-terminal

**Comment by ridiculousfish** [comment]
This is the same as #562, which is fixed in the upcoming 2.3.0 release. Thanks for filing this!
