### ISSUE TITLE
Improve the way fish handles signals

### ISSUE THREAD

**Issue by levantis** [fish-shell/fish-shell#303]
Let's say we have a following script:

function testusr --on-signal USR1
    echo Got the signal
end
while true
    sleep 10
end

and we run it as a separate process, and then signal it SIGUSR1. We will have to wait from 0 to 10 seconds, until the shell that executes the script gets the control back, and then it runs testusr the number of times it caught the signal.

It seems as an intended behaviour, and in this case, you can just write
    for i in (seq 10); sleep 1; end
but I believe it is a big limitation, and it contradicts the documentation :(

**Comment by faho** [comment]
This is a consequence of #238 - we don't run multiple "threads" of fish code in parallel, so you can neither background them nor receive signals.

It would be fixed by the same thing. Because of that, I'm now closing this as a duplicate.
