### ISSUE TITLE
use narrow chars (UTF-8) rather than wide chars (wchar_t) internally

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3034]
I'd like to propose a major overhaul of the fish C++ code to use UTF-8
internally rather than wide characters (wchar_t, wcstring). Doing so
would greatly simplify the code.  For example, it would allow us to
eliminate the wgetopt code, among other simplifications.  It would also
potentially make issues like #2802 less likely.

Too, issues like #2721 to make the "read" command encoding agnostic
wouldn't be necessary since fish would simply, and consistently, read and
write UTF-8. The only question would be whether fish should also have a
"binary" string like Python 3 and associated flags for relevant builtins
like "read". I argue no because fish is not the right tool for manipulating
sequences of arbitrary bytes.

The UTF-8 Everywhere document, http://utf8everywhere.org/, provides good
arguments for making this change to the fish internals. The only potential
roadblock is what happens when fish is built in a Cygwin environment if
we adopt this proposal. Specifically, how would this affect interactions
with Cygwin/Windows APIs? Would we need to add a bunch of shims thus
negating many of the benefits?

**Comment by jakwings** [comment]
For Windows, see [WTF-8](https://simonsapin.github.io/wtf-8/).

**Comment by kopischke** [comment]
Quick perusal of [the relevant Cygwin documentation](https://cygwin.com/cygwin-ug-net/setup-locale.html) suggests that case would be handled just fine, which is to be expected, really, considering how pervasive UTF-8 has become on \*nix platforms.

**Comment by krader1961** [comment]
Another advantage of doing this is that fish would no longer have to reserve Unicode Private Use characters for its internal use. We could replace those code points with a three byte sequence **0b11111111 (0xFF) 0b10xxxxxx 0x10xxxxxx** Since the first byte isn't legal in UTF-8 it provides an unambiguous indicator that a fish special token is present. The second byte would be used to encode the token type and the third byte the value for that token type. This would require us to disallow ISO 8859 locales but I think we should do that in any case.

Note that this does not have to be a "big bang" change. We can implement this gradually. Most fish functions don't actually interpret the strings they receive. They only accept wide char strings because the caller happens to be using them. Consider the `debug()` and related functions. We could easily add parallel implementations that accept narrow char strings. Once all the callers have been converted the old wide char implementation can be removed.

**Comment by ridiculousfish** [comment]
Thumbs up, but you have a stronger stomach than me :)

I anticipate the nastiest parts are special characters such as `VARIABLE_EXPAND`. Code everywhere treats these as single characters, for example:

    if (instr.at(i - 1) != VARIABLE_EXPAND)
        new_in.push_back(INTERNAL_SEPARATOR);

Unfortunately most of these usages are in the gnarliest parts, like string parsing. A key task is to design a string interface that doesn't require that sort of code to deal with the multibyte nature of UTF-8.

**Comment by krader1961** [comment]
@ridiculousfish: This is definitely going to take a lot of grunt work. Including a lot of transition code (temporary scaffolding) that will ultimately be deleted. There will be many months (probably spanning a year given the volunteer nature of the project) when a casual reader of the code will be perplexed why narrow strings are used in one location and wide strings somewhere else.

I've done this type of thing a couple of time, albeit not involving Unicode encodings, and it's not as hard as it seems at first glance. As you note the hardest part of this problem may be designing a mechanism to replace the simple indexing into a string such as the example you gave. Closely related is dealing with all the locations that involve simple comparisons to a wchar_t. But the latter is probably not as hard as it seems since such comparisons are going to be either for single byte ASCII chars or one of the internal special tokens. There probably aren't any comparisons for any other type of character.

At this stage I'm mostly looking for feedback on two aspects of the proposal:

1) Does anyone see any insurmountable problems to making such a change?

2) Does anyone object to making fish incompatible with non UTF-8 encodings such as ISO-8859-1? And if so please explain why we should support such a hideous "standard"  nearly two decades after Unicode was created. Doing so is possible even if we switch to narrow chars internally but would greatly complicate the implementation by requiring that we support encoding and decoding code points between 128 and 255 (0x80 and 0xFF) on input and output so that they can't be confused with our extended UTF-8 sequences.

**Comment by krader1961** [comment]
Note that ISO 8859-1 is identical to the first 256 Unicode code points. So it's trivial to support. Other char sets such as ISO 8859-2 would require us to use a map to convert to/from Unicode on input/output (see http://ftp.unicode.org/Public/MAPPINGS/ISO8859/8859-2.TXT for an example). Asian char sets like GB2312 are huge and finding a good quality mapping table may be difficult. The Unicode consortium has some (http://ftp.unicode.org/Public/MAPPINGS/OBSOLETE/EASTASIA/) but their quality is questionable. So we can, in theory, support non UTF-8 locales but do we really need the baggage? And what should we do if the locale uses a char set for which we don't have a mapping table? Just treat it like ISO 8859-1? That would allow us to read and write strings in those char sets without munging them but will likely produce incorrect results when things like regular expressions are applied to them.

Related to the above is the question of whether our use of PCRE2 correctly handles non-ASCII characters correctly. Specifically with respect to patterns like `\w` to match a "word" character. If we're not setting the PCRE_UCP option then we're not correctly handling non-ASCII strings.

**Comment by zanchey** [comment]
I assume this wouldn't affect the C locale much either.

**Comment by krader1961** [comment]
> I assume this wouldn't affect the C locale much either.

I was pondering that question this morning while walking my dogs. Option #1 is to revert the change I made a couple of months ago and revert to C/POSIX == ASCII like GNU libc does. That would greatly simplify matters since ASCII is just the first 128 Unicode code points and are identical in UTF-8. But this would break the hack we currently have in *__fish_urlencode.fish*.

Option #2 is to treat it like ISO 8859-1, which is to say the first 256 Unicode code points. Clearly the second option is preferable. So regardless of whether we attempt to support other locales I think we have to support ISO 8859-1 and have to consider the current locale when accepting input and writing it back out. I was hoping to avoid that and only accept valid UTF-8 on input and only output UTF-8 but I don't think that is realistic.

**Comment by zanchey** [comment]
One other problem I thought of is that this might make it impossible to interact with files whose names are not valid UTF-8. Unix file names being just a string of bytes causes some quite tricky problems, and I don't see the [safename](https://lwn.net/Articles/686789/) proposal becoming universal any time soon.

**Comment by krader1961** [comment]
The implementation won't attempt to decode or re-encode strings if the locale is UTF-8. My plan is to use function pointers to the decode and encode functions. If the locale is UTF-8 those pointers will refer to functions that simply return the string pointer without alteration. If the locale is, say, ISO 8859-1 then those pointers will refer to suitable functions to encode/decode the chars to/from legal UTF-8. So file names with bogus UTF-8 sequences should be okay if you're using a UTF-8 locale. The only potential problem is if you attempt to treat such strings as legal UTF-8 such as using them as args to the `string` builtin. Too, if you're using ISO 8859 or C/POSIX then they'll be encoded in a fashion that is reversible when they're written.

**Comment by krader1961** [comment]
When we replace our `wgetopt()` with `getopt_long()` we'll need to deal with the POSIXLY_CORRECT env var. Perhaps just unset it and warn the user. See issue #3039.

**Comment by krader1961** [comment]
Also, I hope it won't be necessary but if we find that we need to treat UTF-8 sequences as characters (e.g., to do case conversion) we should standardize on the Boost locale library: http://www.boost.org/doc/libs/1_52_0/libs/locale/doc/html/main.html

**Comment by ridiculousfish** [comment]
Boost is a big decision. Let's cross that particular bridge if we come to it.

**Comment by krader1961** [comment]
> Boost is a big decision. Let's cross that particular bridge if we come to it.

I completely agree. I don't expect us to need it unless we do something like extend the `string` builtin to do things like case conversion. Then, from all the googling I've done, I don't see a better solution. So I wanted to get people thinking about the possibility of depending on it.

**Comment by krader1961** [comment]
In addition to ICU and Boost.Locale (which wraps ICU with a saner interface) there is a simpler [library for dealing with UTF-8[(http://utfcpp.sourceforge.net/) that might be adequate for our needs.

**Comment by floam** [comment]
The standard library isn't great, but with [C++11 there **are** unicode literals, you can do conversions, and validate byte sequences](http://coliru.stacked-crooked.com/a/56b47aa11d1d04b8). It ain't very pretty - but it seems like perhaps an option that exists without picking up a third party dependency in the future.

**Comment by krader1961** [comment]
A mention was recently made in the tmux project to the [utf8proc project](http://julialang.org/utf8proc/doc/index.html). It's actively maintained and used and I think the MIT license it uses is compatible with the fish project. It looks like it does everything we would need and quite a bit more. Adding it to this issue so we remember to take a closer look at it.

**Comment by krader1961** [comment]
If we use UTF-8 internally we will also need to decide what to do with locales like `zh_CN.GBK@cjknarrow`. Specifically, a locale that uses the [GB18030](https://en.wikipedia.org/wiki/GB_18030) encoding standard which is mandated in China. Sadly, given the existence of such national standards, we will have to support encoding our output to match those standards. That does not preclude using UTF-8 internally but does complicate how we do I/O. See issue #3528.

**Comment by krader1961** [comment]
Closing since this won't be implemented until we adopt something like the Boost library which seems unlikely to ever happen.
