### ISSUE TITLE
No completion offered for remote branch in git push

### ISSUE THREAD

**Issue by ashwin** [fish-shell/fish-shell#3035]
The command to push a local branch to a remote branch is:

```
git push remote_name local_branch:remote_branch
```

Fish does tab completion when typing `local_branch`, but does not complete when typing the `remote_branch` in the above command. The `remote_branch` completion works fine in other commands like `git merge remote_name/remote_branch`

---
Fish version: 2.2.0
Operating system: Ubuntu 14.04

**Comment by obfuscated** [comment]
There is another case which doesn't work:
```
git push remote_name 1245ac417df667b314f0344ac24d54ce4374b1f7:remote_branch
```
Here fish doesn't provide any completion for the remote_branch. If I type a space after : the completions work.
Running 3.0.2 here.
Is this the same issue or should I open new one?

**Comment by krobelus** [comment]
@obfuscated makes sense, I just fixed that

**Comment by obfuscated** [comment]
Cool, thanks for the fast response. :)
