### ISSUE TITLE
add ability to write debug output to someplace other than stderr

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3038]
There's a lot of things that would make the fish debug subsystem more useful. One improvement that should be relatively easy to implement is adding an option for sending the output to someplace other than stderr. This would nominally be a file but could be any object (e.g., a named pipe) accessible via a path name. The question is how should the user do this? Via a new flag such as `-F debug-file`? Or perhaps the `-d` flag should be modified to accept a string in a form such as "_level:backtrace-frame-count:file-name_" which it would split apart. If we do the latter then the `-D` /  `--debug-stack-frames` flags I just introduced would be removed.

**Comment by krader1961** [comment]
No one has a strong opinion regarding the UI for redirecting the debug output? I dislike adding new CLI flags so I'm inclined to extend the syntax accepted by the `-d` flag. However, I'm worried that will make it too difficult to change the manner in which we specify what debugging info to report in the future (I don't like the "debug level" idiom, especially as implemented by fish). So I'm going to add a `-F` (alternatively `--debug-file`) flag.

**Comment by ridiculousfish** [comment]
That sounds good to me.

**Comment by floam** [comment]
Bash 4.1 somewhat recently introduced a environmental variable, [BASH_XTRACEFD](http://mywiki.wooledge.org/BashGuide/Practices).

**Comment by floam** [comment]
and:

> There is a new configuration option (in config-top.h) that forces bash to
forward all history entries to syslog.

I kinda like that.

**Comment by krader1961** [comment]
> Bash 4.1 somewhat recently introduced a environmental variable, BASH_XTRACEFD.

That's an interesting idea but it's not an environment variable. It's a local var that affects where `set -x` output is written. It's potentially useful if we ever add something equivalent to `set -x` but not directly applicable to where `fish -dN` output should be written.

As for writing "all history entries" (whatever that means) to syslog I don't think that's a good idea for the type of information we currently log via the `-d` flag. The project I worked on at my previous $dayjob did what I think is being suggested. It serialized every single error, warning, info, and debug message to a service which added them to a searchable database. The project had a web UI that displayed and allowed searching those log messages. It was incredibly useful since the data interpolated into the log messages was independently serialized. That's not something we're likely to replicate in my lifetime in this project.

**Comment by ridiculousfish** [comment]
The BASH_XTRACEFD is sort of nuts, but the idea of fish scripts to control where logs get directed actually sounds useful. You can isolate parts of a script by temporarily setting the log target and then restoring it.

**Comment by floam** [comment]
On OS X you get a pretty nice UI for free through Console.app. It's
not so hard to use syslog/logger.

The way we use these log levels today sucks but I don't really see
issue with just fixing the mapping, something like below and I think
different levels should be directed towards different
files/destinations. Not all of them you will want to be required to
dump into the same place, manually, to get logging.

1. FATAL
2. ERROR
3. WARN
4. INF O
5. DEBUG
6. TRACE

The default of 1 makes not much sense. Obviously warnings, errors,
fatal errors should hit stdout/stderr by default.

I can imagine usefulness in being able to direct different levels
towards different files/mechanisms.

Perhaps copies of all terrible fatal errors that may go unrecorded if
they strike suddenly (fatal, error) or chronically (warn) and also
performance metrics (info) should go to syslog (or some .log file
somewhere, whatever.) so it can be queried later in aggregate.

Everything except two of those levels (debug, trace) should be
hard-configured to end up elsewhere 99% of the time. I think you can
get away with overloading -d (pretend it stands for "dragostics" or
something): `fish -d5=trace.log -d4=debug.log` but that doesn't mean
it's the most pleasant thing.

**Comment by floam** [comment]
The killer feature we lack with only using some kind of log level and
filenames, which bash has handled, is being able to hook that up at
runtime, and eg. being able to have my shell scripts use these same
mechanisms which also work well enough interactively to figure stuff out.

**Comment by floam** [comment]
> That's an interesting idea but it's not an environment variable. 

I don't know what it is, but this worked:

```
bash-4.3 $ export PS4='+ $BASH_SOURCE:$LINENO:'; export BASH_XTRACEFD=7; /usr/local/bin/bash -xlic "" 7>trace.out
```

**Comment by faho** [comment]
Flog has this.
