### ISSUE TITLE
Why does Ctrl-l erase the whole buffer of the terminal?

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#3040]
I use Ctrl-l to clear the content of the window in the terminal (not erase it) , and I use tmux, so I can scroll back to the whole buffer of the history of the commands and their output using the shortkey of tmux.

THIS IS WHAT I NEED!

But Ctrl-l of fish will erase the whole (not always whole, but only about maximum 40 lines on my screen) buffer of the current window, I am no longer able to scroll back to the content.

Currently the Ctrl-l is bound to 'clear; commandline -f repaint', how can I modify it so it will not erase the buffer of thye history?

**Comment by faho** [comment]
This is the same thing as #2855, which you opened before, and the same thing applies:

Bash and fish seem to do the exact same thing for me here - they print \e[H\e[2J to the terminal (either themselves or by executing /usr/bin/clear). This is with bash 4.3.42, fish 2.3b2-151-g8dc74de on linux with Konsole 16.04.1.

With both I can scroll up, with and without tmux.

Which terminal are you using, which fish version? Which other shell are you comparing it with? Which tmux version?

**Comment by krader1961** [comment]
@zanchey's answer at the bottom of issue #2855 is pretty close to what I think you want. Just remove the call to `clear` leaving us with

```
bind \cl 'for i in (seq 1 $LINES); echo; end; commandline -f repaint'
```

**Comment by c02y** [comment]
I opened it again because it is broken again after I updated it from the 
git version control. And I did a lot of tests but nothing works.

I got three computers,

Ubuntu 14.04 32-bit
Both fish and tmux were compiled from version control.
Both fish v2.2 and v2.3 (both dirty) were tested.
Tmux v2.2 and v2.3 were tested.
All of then works fine.

Centos 6.5 32-bit
fish v2.2 dirty
tmux v2.2
Works fine.

Fedora 23 64-bit
Tests are the same as in Ubuntu
None of them works.

Fish and tmux configuration are the same in three computers.

So I did more tests in my Fedora 23 box.

1. Tested in different terminal such as konsole and xfce-terminal, even in 
ctrl-alt-f2, none of them works as what I want.
2. Tested when using bash and tmux, ctrl-l is fine, so this is not the 
problem of tmux.
3. Remove all my fish configuration, and ctrl-l works the same as my 
configuration.

**Comment by krader1961** [comment]
Did you even test this solution:

```
bind \cl 'for i in (seq 1 $LINES); echo; end; commandline -f repaint'
```

Copy and paste that into your current fish session then press [ctrl-L]. If that doesn't do what you want then you haven't clearly communicated the problem. Also, when you say

> 2. Tested when using bash and tmux, ctrl-l is fine, so this is not the problem of tmux.

you're implying that bash does what you want. What behavior did you observe? Can you use [asciinema](https://asciinema.org/) to capture that behavior to help us understand what you expect fish to do? Because, frankly, your written descriptions of what you expect don't make any sense if the bind command I showed  earlier doesn't solve your issue.

**Comment by krader1961** [comment]
You also said

> it is broken again after I updated it from the git version control

Are you saying fish behaved as you expected until you did a "git pull upstream master" and built and ran that version? If so what version were you running before? Can you do the equivalent of `git bisect` to identify what change broke the behavior you want?

**Comment by c02y** [comment]
I got no access to the Fedora 23 box right now, so the binding cannot be 
tested. I'll give more information when I can.

**Comment by c02y** [comment]
I tried to git checkout into old fish (compile anger install) , but it did 
not work, I'll do other tests when I can.

**Comment by krader1961** [comment]
What does "compile anger install" mean? I am trying to make allowances for the fact that English is obviously not your primary language. But I think you should know that part of the reason you are not getting good answers to your questions is that we are having difficulty understanding what you are saying. So including concrete examples of how to reproduce the problem will help; that is, the commands and characters we should type. As will showing what happens on your computer using tools like [Asciinema](https://asciinema.org/).

**Comment by c02y** [comment]
It's obviously a typo, I'm using my smartphone to rely this email, "compile 
and install".

**Comment by krader1961** [comment]
No, it is not "obviously a typo", given your other comments.

**Comment by krader1961** [comment]
If you're posting you're comments from a "smartphone" I recommend that you stop doing so. Because the auto-correction it is doing makes a lot of your comments unintelligible.

**Comment by krader1961** [comment]
Can you provide any new information, @c02y? Have you tried the suggested solution to your problem?

**Comment by c02y** [comment]
Sorry about the delay, that solution will make the prompt line stop at the 
bottom of the terminal.

And it is not the problem of fish-shell itself, the clear command of my 
system will erase the content of the terminal.

I don't use Ctrl-l shortkey in my Fedora23 box anymore, just use an alias 
for 'tput reset', and when want the empty my terminal window, I just 
execute the alias since when I bound the 'tput reset' to Ctrl-l, the effect 
was different from executing the alias,weird.

**Comment by krader1961** [comment]
Doing `tput reset` may not be a good idea as it typically does a lot of things. For example, on my system with **TERM=xterm-256color** it sends the "reset to initial state", "80 column mode", "jump scroll", "soft terminal reset" and many other sequences. I suspect that additional testing would show that the "soft terminal reset" sequence is the most important one with respect to your expected behavior for "clearing" the screen.

That the effect of `tput reset` when bound to a key is different than running it as a command is not surprising unless you also force the command line to be repainted (i.e., by also doing `commandline -f repaint`) as is done by the standard `\cL` binding.

**Comment by c02y** [comment]
It works, thanks.

**Comment by kyleholzinger** [comment]
I know this was closed a super long time ago, but is there any way to revert this? I couldn't find any more information on making this optional, I'd love to make ctrl-l clear the previous lines as well (happy to open a new issue if you guys think it's prudent)

**Comment by faho** [comment]
>I couldn't find any more information on making this optional

@kyleholzinger:

To do that, you just have to bind ctrl-l yourself!

Try

```fish
bind \cl 'clear; commandline -f repaint'
```

interactively. If you like it, add it to a function called `fish_user_key_bindings`.

**Comment by kyleholzinger** [comment]
@faho this only scrolls the terminal to the top of the screen, but you can still scroll up. Is there any way to remove the old buffer as well?

**Comment by faho** [comment]
> Is there any way to remove the old buffer as well?

That's what `clear`, from ncurses 6.0,  does for me.  If it doesn't for you, you'll have to add either `tput E3` (which is the pedantically correct one) or `echo \e\[3J` to the binding.

Or your terminal just doesn't support this, in which case you'd have to switch to one that does.

**Comment by kyleholzinger** [comment]
Man that's nuts, I'm using iterm and maybe it doesn't support it? Does anyone else have this issue in iterm?

**Comment by faho** [comment]
iTerm is weird sometimes - they require (https://www.iterm2.com/documentation-escape-codes.html):

>^[]1337;ClearScrollback^G

In fish notation, that's `\e\[1337\;ClearScrollback\x7`. `echo` that and it should work.

**Comment by kyleholzinger** [comment]
Hmmm this is what I'm getting when I echo that... Am I doing something wrong?

![screen shot 2018-09-12 at 1 48 48 pm](https://user-images.githubusercontent.com/2652762/45443427-a1277c00-b692-11e8-8e3f-233d03b5831c.png)

(also, that's for helping me out @faho, this has been bothering me for a while haha)

**Comment by faho** [comment]
@kyleholzinger: Sorry, that `[` should be a `]`. (Normally it's the former, but in iTerm's proprietary sequences it's the latter)

**Comment by kyleholzinger** [comment]
You're a hero @faho ! Thank you so much. For anyone else using iTerm and fish, the binding I ended up using was:

```fish
bind \cl 'echo \e\]1337\;ClearScrollback\x7; clear; commandline -f repaint'
```
