### ISSUE TITLE
Weird behaviour with switch statement (\n in variable)

### ISSUE THREAD

**Issue by z3ntu** [fish-shell/fish-shell#3041]
Hello,
```
luca@g550jk ~> set -l variable1 (xrandr | grep "DP-1")
luca@g550jk ~> xrandr | grep "DP-1"
eDP-1 connected (normal left inverted right x axis y axis)
DP-1 disconnected (normal left inverted right x axis y axis)
luca@g550jk ~> echo $variable1
eDP-1 connected (normal left inverted right x axis y axis) DP-1 disconnected (normal left inverted right x axis y axis)
luca@g550jk ~> switch $variable1
                   case '*disconnected*'
                       echo "disconnected"
                   case '*'
                       echo "other"
               end
```
but the last "switch" command doesn't output anything at all.

Apparently the variable has a `\n` in it and messes up the switch statement. If you set the variable manually to the value without a `\n`, like
```
set -l variable1 "eDP-1 connected (normal left inverted right x axis y axis) DP-1 disconnected (normal left inverted right x axis y axis)"
```
, I get the output `disconnected` (which is correct).

**Comment by faho** [comment]
The variable does _not_ have a newline in it - the variable has more than one element.

Execute something like `printf '%s\n' $variable1` or (if you don't believe me) `for i in $variable1; echo "Var: $i"; end`.

By default, fish splits command substitutions into arguments on newlines, so every line becomes a separate argument. That means that, when used with `set`, every line becomes a separate element in the variable.

How you'd solve this depends on what you'd like to do. Here it seems likely that you'd want to work on every monitor separately, so you'd do `for display in $variable1; switch $display` and so on. If you really just care about some display being disconnected, you can also just quote the variable - `switch "$variable1"` - this will join the elements with spaces (so if you had a variable with elements "foo" and "bar", it would become "foo bar") and pass them as one argument.

We might want to give an error message here, though.

**Comment by z3ntu** [comment]
Yes, you are **100%** correct.
A error message would be very very nice as I really had no idea that this was going on. 
I was actually only testing if my switch statement actually works and the only `disconnected` port on my laptop is `DP-1`, but if you `grep` for `DP-1` you also get `eDP-1` (which is why there are two results). 

Two more questions:
* Is the `case '*'` like the `default` keyword in other programming languages?
* Do you know if the `.xinitrc` (called with `startx`) is executed with the default shell (`chsh`) or always with `bash`/`sh`?

**Comment by faho** [comment]
>Is the case '*' like the default keyword in other programming languages?

Yes. Be careful to use quotes, though, or otherwise the "*" will be interpreted as a glob and it will compare against files in the current directory (which can be useful at times, and is consistent with how every other command behaves).

>Do you know if the .xinitrc (called with startx) is executed with the default shell (chsh) or always with bash/sh?

Well, I can run it with fish as my shell and it works (and I don't recall any issue about it), so it's /bin/sh, most likely. Which is also the only correct solution - we've had a couple of issues with programs assuming the user's configured shell is POSIX-compatible (vim, for example) and using it to run its own scripts. Though in this case the user also wrote it.

> A error message would be very very nice as I really had no idea that this was going on. 

I'll check if we already have any issues about that and if not I'll open a new one.

If you have any more questions, feel free to ask! I'm closing this issue because your original question is answered.

**Comment by z3ntu** [comment]
Thank you very much for your (quick) help!

**Comment by z3ntu** [comment]
Another question: Is there an easy way to find out if a variable is a list or a string?

**Comment by kopischke** [comment]
@z3ntu conceptionally, fish strings are just one-item lists, so

```fish
test (count $var) -gt 1
```

is true for a multi-item list.

**Comment by faho** [comment]
If you only care that a variable has more than one element, you can also do `set -q var[2]` - i.e. "is the second element set?" (note the missing "$").
