### ISSUE TITLE
Documentation for fish_mode_prompt

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#3047]
The `fish_mode_prompt` introduced by #1988 needs to be documented.

**Comment by laughedelic** [comment]
Btw, I noticed that https://github.com/fish-shell/fish-shell/issues/1988#issuecomment-219303544 refers to  `fish_vi_mode` which is deprecated:

```
❯ fish_vi_mode
The `fish_vi_mode` function is deprecated.
Please switch to calling `fish_vi_key_bindings`.
```

**Comment by hastebrot** [comment]
Argh, this is very confusing.

>config.fish
~~~
fish_vi_key_bindings
fish_mode_prompt
~~~

This doesn't bring me the modal indicator `[N]`, `[I]` and `[V]` back.

**Comment by faho** [comment]
@hastebrot: `fish_mode_prompt` is a separate prompt function that is called by fish before the real prompt, so you shouldn't have to do anything to get it. In fish 2.3.0, calling either `fish_vi_key_bindings` or `set fish_key_bindings fish_vi_key_bindings` should enable it (by setting the variable to "fish_vi_key_bindings", which "fish_mode_prompt" checks). There should be no need for you to do anything apart from setting your bindings, no special support in the prompt or calling `fish_mode_prompt` manually or anything.

Are you saying that's not the case?

**Comment by hastebrot** [comment]
After switching to fish 2.3.0 the modal indicator is missing. It is missing when I use `fish_vi_mode` (which outputs a deprecation warning) and `fish_vi_key_bindings`. The actual key bindings work.

**Comment by faho** [comment]
Aaaaaaaaaaah! It seems in our rebasing we missed parts of 8ab980b793e80199f61257b1bc46826a93af8413.

`fish_mode_prompt` in 2.3.0 still checks $__fish_vi_mode, but the functions don't set it anymore. The easiest workaround is probably `set -g __fish_vi_mode 1`.

In case we do a stable release based on the Integration_2.3.0 branch that one should definitely be included.

Sorry!

**Comment by hastebrot** [comment]
Ahh, thanks! Here a summary:

before (fish 2.2):
~~~
fish_vi_mode
~~~

after (fish 2.3):
~~~
fish_vi_key_bindings
set -g __fish_vi_mode 1
~~~

**Comment by hastebrot** [comment]
I imagined to have three functions for vi functionality:

- `fish_vi_key_bindings` for key bindings only.
- `fish_vi_mode_prompt` for the model indicator prompt.
- `fish_vi_cursor` for the typical vi cursor for different modes.

**Comment by hastebrot** [comment]
BTW: There was also a strange problem with `apt upgrade` from fish 2.2 to 2.3 on Ubuntu. The packages `fish-common` and `fish` had some conflict with the `config.fish` file.

This fixed it:

~~~
sudo dpkg --remove fish
sudo dpkg --remove fish-common
sudo apt install fish
~~~

**Comment by faho** [comment]
@hastebrot: That's #3053.

**Comment by faho** [comment]
I'm gonna close this as a dup of #3232, since there's more discussion there.
