### ISSUE TITLE
why are abbreviations universal?

### ISSUE THREAD

**Issue by aeosynth** [fish-shell/fish-shell#3049]
why are abbreviations universal, instead of global? this behavior is confusing, since the only other function which by default persists config changes is `funcsave`.

**Comment by krader1961** [comment]
The assumption is if you have multiple fish sessions on a machine and create an abbreviation on the fly in one session you probably want it available in all the sessions. For example, if I've been repeatedly typing the same git command I might decide to create an abbreviation for it. If I switch focus to a different window where I'm working on the same project I'm likely to want that new abbreviation available without having to define it a second time.

**Comment by aeosynth** [comment]
you could make that same argument for `bind` and `function`; the issue is that the universality is unexpected in comparison

**Comment by krader1961** [comment]
Those aren't analogous situations.

Unless you add the binding to  your *fish_user_key_bindings* function it won't be available when you start a new session. What you're basically expecting is for that function to be stored in the universal var storage.

If you want a function you define on the fly available in other sessions simply run `funcsave`. That's not done automatically because you might be experimenting with a new definition and don't want to break your other sessions.

**Comment by aeosynth** [comment]
> Those aren't analogous situations.

that's the entire issue - why isn't `abbr` analogous to `bind` and `function`?

> What you're basically expecting is for [key bindings] to be stored in the universal var storage.

the reverse - i was not expecting abbreviations to be stored in universal storage

> If you want a function you define on the fly available in other sessions simply run funcsave. That's not done automatically because you might be experimenting with a new definition and don't want to break your other sessions.

experimenting with `abbr` can break my other sessions

**Comment by krader1961** [comment]
There are arguments for and against abbreviations being universal. The people who implemented this felt that, on balance, it was a better "out of the box" user experience if they were universal. I'm inclined to agree even though I started using fish just seven months ago. With issues like this it is impossible to please everyone but we try to make the majority of users happy.

Note that the fish manifesto strongly discourages configurable behavior via mechanisms like zsh's `setopt` command. And for good reason. That ability is why I switched from zsh to fish. It was basically impossible to know how my shell would behave unless I knew how the various config files had set all the configurable "knobs". If you propose a way to make abbreviations default to universal but possible to make global without a) breaking backward compatibility, and b) introducing a configuration option it is likely to be accepted. For example, you might propose adding a `-g` flag to the `abbr` command.

**Comment by zanchey** [comment]
This was a discussion that we had at the time - I wondered about a global/universal option, but we decided against it in #731.

**Comment by faho** [comment]
You should be able to have abbrs globally if you `set -g fish_user_abbreviations` (in config.fish of course, before adding any abbreviations) - the abbr function should be able to deal with it.

I don't think we should expose any more direct option.

@aeosynth: Would that work for you?

**Comment by krader1961** [comment]
> experimenting with abbr can break my other sessions

That's an interesting assertion. Care to provide an example? Abbreviations are only expanded in the command position and the expansion is pretty hard to miss.

**Comment by faho** [comment]
>That's an interesting assertion. Care to provide an example? Abbreviations are only expanded in the command position and the expansion is pretty hard to miss.

Not sure about _break_, but it can be a bit annoying if you add an abbr with the same name as an already existing command/function. E.g. `abbr --add pacman "echo HAHA"`. The issue is that it's slightly non-obvious what will stop the expansion - prefixing with `\` will, as will accepting an autosuggestion. But just pressing space won't.

Anyway: @aeosynth: Would setting fish_user_abbreviations to global suit your needs?

**Comment by aeosynth** [comment]
setting it to global works for me, but the issue is that 'universal by default' is confusing, and makes abbreviations not analogous to bind and function.

abbreviations can be easy to miss if you expand them by pressing enter, and the screen clears after.

closing since no one else seems to think this is confusing.

**Comment by chris-martin** [comment]
I also find this confusing. I lost quite a bit of time trying to figure out why the abbreviations I set in `config.fish` persisted after I removed them from `config.fish`.
