### ISSUE TITLE
fish_title, functions and job control

### ISSUE THREAD

**Issue by lledey** [fish-shell/fish-shell#305]
I have a function like the following:

``` fish
function emacs
                 command emacs -nw $argv
end
```

When I run this function, fish_title is "emacs  /home/lledey/somedirectory".
If I suspend emacs and then foreground it, fish_title will be "command  /home/lledey/somedirectory"

It's not a big issue, but it seems a little bit weird.

**Comment by krader1961** [comment]
Closing since I can no longer reproduce this.
