### ISSUE TITLE
Alt+Arrow key (Move cursor a word, emacs mode) not working

### ISSUE THREAD

**Issue by Fishrock123** [fish-shell/fish-shell#3056]
[Please include a short description of the problem here]

### Reproduction Steps:

1. Typed in some words into he fish shell, e.g. `git checkout master`
2. Press `Alt` + `←`
3. Note that the cursor has only moved one character, rather then past "master".

### Expected behavior:

The cursor should jump to the beginning of "master" or end of "checkout". (not sure which, doesn't particularly matter.)

### Observed behavior:

It acts as if I just pushed an arrow key, no difference.

### Additional information:

Has happened as long as I've known about `Alt` + `Arrow key`.

Mostly default settings. Only thing of note that is special about my setup is that I have a command shim of sorts to make `&&` translate to `; and`, even from pasted input.

---
Fish version: fish, version 2.2.0

Operating system: OS X 10.10.5 ... I think I installed via homebrew but that may not be correct as homebrew doesn't see it anymore. I also recently re-installed homebrew due to other brew issues.

Terminal or terminal emulator: OS X default terminal, Version 2.5.3 (343.7)

**Comment by brj** [comment]
Using `Alt` + `←` or `→` works just as expected for me in both Terminal.app and iTerm2.
![alt](https://cloud.githubusercontent.com/assets/8317250/15477575/476c4e90-2150-11e6-818b-976f0a7e8b6f.gif)
![alt2](https://cloud.githubusercontent.com/assets/8317250/15477574/4768252c-2150-11e6-9da4-a296c96cd9c6.gif)

>  Only thing of note that is special about my setup is that I have a command shim of sorts to make && translate to ; and, even from pasted input.

Does it do anything to your key bindings? And what key bindings have you defined?

**Comment by faho** [comment]
The obvious thing to find out here is if the sequence your terminal sends for those key combinations is bound to the right thing. We try to go via terminfo and bind key names (e.g. `bind -k left backward-char` instead of `bind \e'[D' backward-char`), but for modified keys (alt or ctrl+something) we don't currently allow this so we bind a variety of sequences directly.

For alt+left, those are

```fish
\e\eOD
\e\e\[D
\eO3D
\e\[3D
\e\[1\;3D
\e\[1\;9D
```

In current git master we have a utility called  `fish_key_reader` that will print keys you press, otherwise you can use e.g. `cat`, which should echo them back (then ctrl+d or ctrl+c to quit). The sequence that prints should be bound to `prevd-or-backward-word`.

**Comment by Fishrock123** [comment]
> Does it do anything to your key bindings? And what key bindings have you defined if any?

`~/.config/fish/functions/fish_user_key_bindings.fish`
```fish
function fish_user_key_bindings
  bind \& 'handle_input_bash_conditional \&'
  bind \| 'handle_input_bash_conditional \|'
end
```

Here is a gist of `handle_input_bash_conditional`: https://gist.github.com/Fishrock123/533b08b955b71bff9342e933452b6ed4

I'm not the original author, it was taken from https://github.com/fish-shell/fish-shell/issues/150#issuecomment-53133716. I forget if I had to modify it or not.

---

> The obvious thing to find out here is if the sequence your terminal sends for those key combinations is bound to the right thing.

What would be the easiest way to check that?

**Comment by faho** [comment]
@Fishrock123: Read the rest of the comment. If you can run `make fish_key_reader` from git master, run the resulting `fish_key_reader` program. Otherwise `cat` without options _should_ echo whatever it's given, but the notation is slightly different and I'm not 100% sure if OSX cat does the same thing.

**Comment by Fishrock123** [comment]
Cat doesn't seem to see my alt (option) key. I'll clone and check shortly.

**Comment by krader1961** [comment]
The `fish_key_reader` program is by far the easiest and clearest way to explore what keys send. Lacking that I use either `od -tx1z` or `xxd` though you need to press [ctrl-D] after pressing the key you're interested in.

**Comment by Fishrock123** [comment]
Right-arrow:
```
Jeremiah@Jeremiahs-MacBook-Pro ~/D/fish-shell> ./fish_key_reader
999999 usec  dec:  27  hex: 1b  char: \e (aka \c[)
   424 usec  dec:  91  hex: 5b  char: [
   353 usec  dec:  67  hex: 43  char: C
```
Alt (option) + Right-arrow:
```
Jeremiah@Jeremiahs-MacBook-Pro ~/D/fish-shell> ./fish_key_reader
999999 usec  dec:  27  hex: 1b  char: \e (aka \c[)
   364 usec  dec:  91  hex: 5b  char: [
   299 usec  dec:  67  hex: 43  char: C
```
Left-arrow:
```
Jeremiah@Jeremiahs-MacBook-Pro ~/D/fish-shell> ./fish_key_reader
999999 usec  dec:  27  hex: 1b  char: \e (aka \c[)
   388 usec  dec:  91  hex: 5b  char: [
   344 usec  dec:  68  hex: 44  char: D
```
Alt + Left-arrow:
```
Jeremiah@Jeremiahs-MacBook-Pro ~/D/fish-shell> ./fish_key_reader
999999 usec  dec:  27  hex: 1b  char: \e (aka \c[)
   433 usec  dec:  91  hex: 5b  char: [
   357 usec  dec:  68  hex: 44  char: D
```

**Comment by Fishrock123** [comment]
Maybe there's something up with my Alt / Option keys?

**Comment by krader1961** [comment]
You haven't configured your terminal emulator to treat [Alt] as a meta key that sends \e (escape) before the sequence sent by the key being modified. In OS X Terminal.app you need to open preferences, click on profiles, then the keyboard tab and check the "Use Option as Meta key" checkbox.

**Comment by krader1961** [comment]
Also, I'd strongly encourage you to switch to iTerm (aka iTerm2) as it is a much more capable terminal emulator; including support for 24 bit color.

**Comment by Fishrock123** [comment]
> You haven't configured your terminal emulator to treat [Alt] as a meta key that sends \e (escape) before the sequence sent by the key being modified. In OS X Terminal.app you need to open preferences, click on profiles, then the keyboard tab and check the "Use Option as Meta key" checkbox.

TIL. Thank you very much!

**Comment by faho** [comment]
>Also, I'd strongly encourage you to switch to iTerm

Don't forget fish 2.3.0! The new hotness!

>including support for 24 bit color.

Which fish 2.3.0 will then enable by default! Fish 2.3.0! Vote 2.3.0! (Paid for by the committee to spread fish 2.3.0)
