### ISSUE TITLE
OSX and fish 2.3.0

### ISSUE THREAD

**Issue by cvlmtg** [fish-shell/fish-shell#3059]
Since upgrading fish to 2.3.0 I have some random errors:

```
(develop) ~/d/html5-app npm run build/usr/bin/type: line 4: type: -q: invalid option
type: usage: type [-afptP] name [name ...]
/usr/bin/type: line 4: type: -q: invalid option
type: usage: type [-afptP] name [name ...]
fish: Unknown command 'down-or-search'
```

When it happens the arrow down button starts diplaying "fish: Unknown command 'down-or-search'" everytime I press it. Sometimes it happens with the arrow up key.

The error seems to happen at random times, so I haven't found yet a way to reproduce it reliably

---
Fish version: 2.3.0

Operating system: OSX 10.11.5, homebrew

Terminal or terminal emulator: iTerm2

**Comment by ridiculousfish** [comment]
This looks like you may have multiple instances of fish installed. What does `which -a fish` show?

**Comment by cvlmtg** [comment]
```
 ~ which -a fish
/usr/local/bin/fish
```

**Comment by cvlmtg** [comment]
btw during the upgrade brew told me to ```killall fishd``` but I had no fishd processes. However I see ```Applications/iTerm.app/Contents/MacOS/iTerm2 --server /usr/local/bin/fish```. I wonder if this is the process I need to restart...

**Comment by ridiculousfish** [comment]
No, that process is fine.

fish is not finding its `type` function, so it's invoking `/usr/bin/type`, which shouldn't happen. I wonder if the homebrew recipe is busted

**Comment by cvlmtg** [comment]
just to be extra sure I exited all my fish shells and restarted iTerm2. I'll report if the problem pops up again. thanks for the support!

**Comment by cvlmtg** [comment]
sorry, saw your edited message after my reply. here's the output:

```
 ~ functions -q type ; echo $status
0
```

**Comment by faho** [comment]
@cvlmtg: Did you by any chance upgrade from a fish before 2.2.0? That would explain the fishd message and might also explain this - it's possible it picked up on _some_ new functions but not the newer version of `type`.

That would be basically impossible to fix because it involves old running instances - and we literally can't patch those because then they'd be new instances.

**Comment by zanchey** [comment]
> That would explain the fishd message

No, that's a standard Homebrew message, which I'll send a PR to remove.

**Comment by cvlmtg** [comment]
@faho I don't remember the first version of fish I installed on this laptop. might have been 2.2.0 or earlier. Anyway I understand "fixing" the upgrade process is almost impossible, so I suppose it's always a good idea to exit all the running shells. Probably the message about fishd is a bit misleading, because it seems restarting that only process (which seems to not exists on my mac) is enough for a clean upgrade.

**Comment by zanchey** [comment]
@cvlmtg has this stopped happening since you restarted all your shells?

**Comment by cvlmtg** [comment]
@zanchey yeah, it seems so. As I said it appeared randomly, but after a couple of days I think I can say it's gone. thanks for the help!
