### ISSUE TITLE
support "cd -" to cd into previous directory or make syntax for existing support easier to find

### ISSUE THREAD

**Issue by lanterndev** [fish-shell/fish-shell#306]
In bash `cd -` changes directory to the previous directory you were in. Does fish support this with some other syntax? If not, could it? If so, it would be neat if it gave you a hint about it when you type `cd -` instead of the less helpful `cd: The directory '-' does not exist`, or at least covered it in `file://localhost/usr/local/share/doc/fish/commands.html#cd`

**Comment by xliiv** [comment]
> You can move back with ALT + Left Arrrow and forward with ALT + Right Arrow between working directories. ( just like we move back and forth between pages in web browsers )

I have `vi` mappings enabled and this doesn't work.

**Comment by faho** [comment]
>I have vi mappings enabled and this doesn't work.

@xliiv: What's your fish version? Since 2.4.0, this is in the bindings that are shared between vi-mode and emacs-mode.

Alternatively, your terminal sends some weird sequence for these, so please run `fish_key_reader` press these key combinations, then upload the output here.

**Comment by xliiv** [comment]
@faho thanks for quick response. You're right it looks like terminal (`tilix` ) does that.
Because when i run `fish_key_reader` in `gnome-terminal` i'm getting:
```fish
[21:18:22] xliiv@alef /home/xliiv (0) 
> fish_key_reader
Press a key

              hex:   1B  char: \c[  (or \e)
(  0.397 ms)  hex:   5B  char: [
(  0.305 ms)  hex:   31  char: 1
(  0.299 ms)  hex:   3B  char: ;
(  0.297 ms)  hex:   33  char: 3
(  0.313 ms)  hex:   44  char: D
bind \e\[1\;3D 'do something'
```
and in `tilix`
```fish
[21:17:48] xliiv@alef /home/xliiv (0) 
> fish_key_reader
Press a key


```

`Tilix` version
```fish
[21:16:04] xliiv@alef /home/xliiv (0) 
> tilix --version
Versions
	Tilix version: 1.8.3
	VTE version: 0.54
	GTK Version: 3.24.1

Tilix Special Features
	Notifications enabled=1
	Triggers enabled=0
	Badges enabled=1
```

**Comment by faho** [comment]
Ah, okay.

By default, tilix maps alt-arrow to moving around the split windows, so it doesn't pass them on.

@xliiv: You'll want to unbind these keys in tilix.

**Comment by xliiv** [comment]
@faho 
I unbinded `alt+arrow` but history navigation still doesn't work for me or i misunderstand it.
### Testing session
```fish
[21:35:25] xliiv@alef /tmp (0) 
> cd a
total 0
drwxr-xr-x. 3 xliiv xliiv 60 Jan  3 21:34 b/
[21:35:29] xliiv@alef /tmp/a (0) 
> cd b
total 0
drwxr-xr-x. 3 xliiv xliiv 60 Jan  3 21:34 c/
[21:35:33] xliiv@alef /tmp/a/b (0) 
[21:35:34] xliiv@alef /tmp/a/b (0) 
[21:35:35] xliiv@alef /tmp/a/b (0) 
```
Last 3 lines is reaction for pressing `alt+left-arrow`
I expect that i will go backwward to dir `b` and dir `a`.

**Comment by faho** [comment]
>Maybe because i have redefined cd?

You have actually just entirely shadowed the `cd` function, so it's falling back to the `cd` builtin.

And since the function is responsible for saving the directory history, yes, you broke it.

There is really no reason for keeping that function in a file called cd.fish. Since it's an event listener, you can't rely on autoloading (currently you're getting away with it because fish is sourcing that file when you `cd` anyway), but you should put it into config.fish or ~/.config/fish/conf.d/something.fish.

**Comment by xliiv** [comment]
I don't get it, but it's a bit off-topic so i'm not gonna dig it deeper here. Anyway thanks for help and for awesome shell!

**Comment by isaacItz** [comment]
> This feature is not new and was present in previous versions of fish. I can't speak for OS X but it's working fine for me on Linux. Directory switching is done by functions in "share/functions/nextd.fish" and "share/functions/prevd.fish"
> 
> Try to tweak key bindings for nextd-or-forward-word and prevd-or-backward-word in "share/functions/fish_default_key_bindings.fish" (or just add your own for nextd and prevd)

I did a bind like ALT left/right-arrow but with CTRL-P or CTRL-N. It's more comfortable for me
I did it in my config.fish, I hope it would be useful for someone

`function fish_user_key_bindings
    for mode in insert default visual
        bind -M $mode \cP 'prevd-or-backward-word'
        bind -M $mode \cN 'nextd-or-forward-word'
        bind -M $mode \cF forward-char
    end
end`
It didn't work with just `prevd` and `nextd` I don't know why.
PD: sorry for my english.
