### ISSUE TITLE
Updating from fish 2.2 to 2.3 breaks already-running shells

### ISSUE THREAD

**Issue by amluto** [fish-shell/fish-shell#3065]
Terminal A: run fish 2.2.0

Terminal B: Upgrade 2.2.0 -> 2.3.0

Terminal A:
```
~> cd /
bash: string: command not found...
/usr/share/fish/functions/__fish_urlencode.fish (line 14): 			if string match -q -r '[/._~A-Za-z0-9-]' $c
                                                           			   ^
in function “__fish_urlencode”
    called on standard input

```
This is on Fedora using the new 2.3.0 updates-testing packages.

I'm not sure whether this counts as a bug, but it's a bit annoying to users.  It might be nice if fish could at least detect this situation and print a useful error.

**Comment by krader1961** [comment]
See issue #3057. If you have a good idea for solving this type of problem that isn't worse than the problem itself please open a new issue that describes your proposed solution.
