### ISSUE TITLE
fish_mode_prompt not working in 2.3.0

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#3067]
From https://github.com/fish-shell/fish-shell/issues/3047#issuecomment-221537710:

Aaaaaaaaaaah! It seems in our rebasing we missed parts of 8ab980b.

fish_mode_prompt in 2.3.0 still checks $__fish_vi_mode, but the functions don't set it anymore. The easiest workaround is probably set -g __fish_vi_mode 1.

In case we do a stable release based on the Integration_2.3.0 branch that one should definitely be included. If it's instead based on master this is already fixed.

Sorry!

**Comment by ridiculousfish** [comment]
Yikes. Let's do a 2.3.1 release with this.

**Comment by zanchey** [comment]
Cherry-picked as fcbeddc3eb2.
