### ISSUE TITLE
2.3.0 bash "read" reads no characters when called in config.fish

### ISSUE THREAD

**Issue by dutchgecko** [fish-shell/fish-shell#3070]
This is occurring for me when running a bash script, which includes use of the bash builtin `read`, but only if `read` is called from within `.config/fish/config.fish`

### Reproduction Steps:

1. Add either a bash script which calls `read`, or just the command `bash -c read` to your config.fish
2. Start a new shell

### Expected behavior:

`read` is able to read characters and ends input when enter is pressed

### Observed behavior:

`read` reads no characters, and does not finish input when enter is pressed. Input can however be terminated by pressing ctrl+enter.

### Additional information:

I have only tested this over ssh sessions, I don't have a local linux machine to test with.

This only seems to happen for config.fish, not for fish scripts invoked from the command line.
  

---
Fish version: fish, version 2.3.0
Operating system: Debian Jessie, latest fish installed from repositories at opensuse.org

Terminal or terminal emulator: PuTTYTray p0,66-t028

**Comment by faho** [comment]
This is #2980. We have a fix in the pipeline, but it needs more testing. Sorry!
