### ISSUE TITLE
commandline operations in binding mess up multi-line prompts

### ISSUE THREAD

**Issue by kopischke** [fish-shell/fish-shell#3074]
When using a binding that ~~substitutes~~ manipulates the command line after returning from a curses display, Fish repeats all prompt lines but the first on screen.
### Reproduction Steps:
1. Install or configure a multi-line prompt like [pure.fish](https://github.com/brandon099/pure.fish)
2. `function testit; man fish; commandline -r 'fish trawl ended'; end`
3. `bind \cx testit`
4. press Control-x on a new, empty prompt → fish man page display
5. press q

### Expected behavior:

Current prompt line is set to “fish trawl ended”

### Observed behavior:

Line “fish trawl ended” appears below the current, empty prompt, on a new prompt line, but minus one line break. Illustration (notice the missing new line above the spurious prompt):

<img width="970" alt="fish prompt" src="https://cloud.githubusercontent.com/assets/80906/15575082/562765e8-2351-11e6-8ed8-353e5a27cca1.png">

### Additional information:

- Single line prompts are handled correctly
- Inserting into the prompt (`commandline -i`)~~works fine~~ exhibits the same behavior as replacing
- Adding `commandline -f [force-]repaint` to the function does not change the observed behavior
- ~~Workarounds like killing the line and appending instead of replacing the command line buffer are blocked by #3031~~

---
- Fish version: 2.3, Homebrew installed via `brew install fish --devel`
- Operating system: OS X 10.11.4
- Terminal or terminal emulator: Terminal.app

**Comment by kopischke** [comment]
Updated with “Additional Information” section.

**Comment by kopischke** [comment]
Further amended for erroneous report: inserting / appending exhibits the same behaviour as wholsale command line replacement.

**Comment by kopischke** [comment]
Issue persists after updating to OS X 10.11.5.

**Comment by kopischke** [comment]
I know this issue sounds very much like a “huh” case, but this kind of behaviour is really annoying when you try to integrate things like _fzf_ into Fish (my current use case).

**Comment by kopischke** [comment]
I’m wondering if this is related to #1388, which also affects multi-line prompts…

**Comment by plttn** [comment]
I'm having an issue similar to this, I'm curious, does it have a erroneous output when you have a non-existent completion, for example: `git ---<tab>`?

**Comment by iacore** [comment]
The last line gets eaten

**Comment by faho** [comment]
I can no longer reproduce this, closing.
