### ISSUE TITLE
The `enter` key stop working after upgrading to v2.3.0

### ISSUE THREAD

**Issue by minibikini** [fish-shell/fish-shell#3075]
After upgrading to v2.3.0 the `enter` key stop working.

### Reproduction Steps:
1. `brew update; brew upgrade`

### Expected behavior:
The `enter` key works. So I can run commands from the command prompt.

### Observed behavior:
The `enter` key doesn't work. I'm unable to run commands from the prompt. 😭 

### Additional information:
`enter` still works in bash.

---
Fish version: 2.3.0

Operating system:  OSX(10.11.3),  Homebrew

Terminal or terminal emulator: I've tried iTerm2 and the Terminal.app

**Comment by minibikini** [comment]
Hmm, weird: after I did

```
brew uninstall fish --force
brew install fish
```
everything went back to normal and `enter` is working.

**Comment by faho** [comment]
This was probably another issue with an old fish instance picking up new functions.

**Comment by krader1961** [comment]
Fish 2.3.0 turns of ICRNL mode in the tty driver which means the \cM (\r) sent by the [enter] key no longer gets mapped to \cJ (\n). Fish 2.3.0 added additional key bindings to accommodate that change in behavior. You probably just needed to start new fish shells to get everything in sync.

In the future we'll probably add a warning about this.

**Comment by lowne** [comment]
fwiw, same here. 

> You probably just needed to start new fish shells

The issue persisted after a reboot. `uninstall --force && install` fixed it for me as well.
