### ISSUE TITLE
Results of wildcard expansion changed in latest release?

### ISSUE THREAD

**Issue by davidcelis** [fish-shell/fish-shell#3077]
I have a function, called `d`, that acts as a sort of personal "fuzzy `cd`" utility into my code directory:

```fish
function d --description 'Like z, but d'
  cd $DEVELOPER
  for dir in $argv
    cd $dir*/; or begin
      echo "fish: No matches for wildcard '$dir*/'." >&2
      return 1
    end
  end
end
```

The result of this used to be that the first wildcard match would be passed to `cd`. Behavior looked something like this:

```sh
~ $ d dot
~Developer/dotfiles $ d gi gh
~Developer/git/ghi $
```

After updating to the latest release of Fish that's in homebrew, something about wildcard expansion changed, and now _every_ wildcard match appears to be passed to `cd`:

```sh
~ $ d dot
~Developer/dotfiles $ d gi gh
fish: No matches for wildcard 'gi*/'.
Too many args for cd command
~Developer $
```

### Reproduction Steps:

1. Add function `d`
2. `set -x $DEVELOPER $HOME/Developer # or some other directory with nested folders
3. Use `d` to try to `cd` several sub-directories deep into your Code directory where, somewhere along the way, the wildcard will expand to several possible matches

### Expected behavior:

The first match is passed to `cd`

### Observed behavior:

All matches are passed to `cd`, resulting in `cd` receiving too many arguments.

### Additional information:

This started when updating from Fish 2.2.x to 2.3.0. A workaround has been to re-define `d` to store matches in a variable and pull the first directly:

```fish
function d --description 'Like z, but d'
  cd $DEVELOPER
  for dir in $argv
    set -l matches (command ls -d $dir*/)

    if [ -n "$matches" ]
      cd $matches[1]
    else
      echo "fish: No matches for wildcard '$dir*/'." >&2
      return 1
    end
  end
end
```

---

Fish version: 2.3.0

Operating system: Mac OS X 10.11.5, Homebrew

Terminal or terminal emulator: Terminal.app

**Comment by faho** [comment]
Unlike what I first expected, this isn't this change from [the release notes](https://github.com/fish-shell/fish-shell/releases/tag/2.3.0):

>Unmatched globs will now cause an error, except when used with for, set or count (#2719, #2394)

There's something else here - 9d2b53450ac038bcef7c62191770e9b85b6017f9 made it so handing multiple arguments to cd would error out. Previously it only ever read $argv[1]. I'd argue that this is much less surprising, though it wasn't made explicit in the release notes or the commit.

>set -l matches (command ls -d $dir*/)

Please don't use ls here, it's at best redundant and at worst causes errors (with files that have newlines in the name) - `set -l matches $dir*/` will work just as well or better. Otherwise that's how the code should have looked like to begin with.

**Comment by krader1961** [comment]
I'll reinforce what @faho said. Using a construct like `cd $dir*/` is just plain wrong. The fact it happened to work in earlier releases is an accident; which is to say, a bug. If the pattern matches more than one path which one should be used? Not to mention that `cd`, by definition, should only accept a single directory (the new behavior).

**Comment by davidcelis** [comment]
Thanks for the `set` recommendation, @faho. That did indeed work perfectly for me.

> If the pattern matches more than one path which one should be used?

That's a good point, and one that I hadn't really thought about previously. After actually thinking about it, it does make much more sense to error out than to simply read `$argv[1]`. Thanks for the clarification, @krader1961 & @faho!
