### ISSUE TITLE
Is there any way to redirect the "No matches for wildcard" message?

### ISSUE THREAD

**Issue by davidcelis** [fish-shell/fish-shell#3078]
This is a little related to #3077, insofar as it's a problem with the same `d` utility that I describe within.

I have a function, called `d`, that acts as a sort of personal "fuzzy `cd`" utility into my code directory. I'm going to go with the modified version from the linked issue due so that the `cd` command actually works:

```fish
function d --description 'Like z, but d'
  cd $DEVELOPER
  for dir in $argv
    set -l matches (command ls -d $dir*/)

    if [ -n "$matches" ]
      cd $matches[1]
    else
      echo "fish: No matches for wildcard '$dir*/'." >&2
      return 1
    end
  end
end
```

If I try to `d` using a pattern that results at any point in no directory, I get a big, long error message that I can't seem to redirect to /dev/null:

```sh
~ $ d gi gi
No matches for wildcard '$dir*/'.
~/.config/fish/functions/d.fish (line 1): command ls -d $dir*/
                                                        ^
in command substitution
	called on line 0 of file ~/.config/fish/functions/d.fish

in function 'd'
	called on standard input
	with parameter list 'gi gi'

fish: No matches for wildcard 'gi*/'.
~Developer/git $
```

That last line is mine, and I'd like to keep that one, but none of the other likes are able to be redirected:

```
~ $ d gi gi >/dev/null ^&1
No matches for wildcard '$dir*/'.
~/.config/fish/functions/d.fish (line 1): command ls -d $dir*/
                                                        ^
in command substitution
	called on line 0 of file ~/.config/fish/functions/d.fish

in function 'd'
	called on standard input
	with parameter list 'gi gi'

~Developer/git $
```

### Reproduction Steps:

1. Add function `d`
2. `set -x $DEVELOPER $HOME/Developer # or some other directory with nested folders
3. Use `d some fragments >/dev/null ^&1` to try to `cd` into a directory that doesn't match a provided fragment

### Expected behavior:

The long "No matches for wildcard '$dir*/'." is redirected to `/dev/null`

### Observed behavior:

The long "No matches for wildcard '$dir*/'." is not redirected to `/dev/null` but is instead printed on the Terminal.

---

Fish version: 2.3.0

Operating system: Mac OS X 10.11.5, Homebrew

Terminal or terminal emulator: Terminal.app

**Comment by faho** [comment]
Currently no, though it might be worthwhile.

Your direct issue though is easily solved - like I mentioned in #3077, ditch the `ls`.

Like the releasenotes mention:

> Unmatched globs will now cause an error, except when used with `for`, `set` or `count`

So if you use `set -l matches $dir*/`, we won't print the error. We just won't set the variable to anything.

**Comment by faho** [comment]
The redirection request is #1674

**Comment by davidcelis** [comment]
> So if you use set -l matches $dir*/, we won't print the error. We just won't set the variable to anything.

Thank you!
