### ISSUE TITLE
man <tab> doesn't complete man page names, only section ids

### ISSUE THREAD

**Issue by mineo** [fish-shell/fish-shell#3085]
Typing `man <tab>` in a completely new fish installation only completes section ids (1,2, o, n, l, p, etc.) but no man page names.

### Reproduction Steps:

1. `rm -rf ~/.config/fish; rm -rf ~/.local/share/fish`
2. `fish`
3. `man <tab>`

### Expected behavior:

According to https://fishshell.com/docs/current/index.html#completion, this should suggests completions for man page names.

### Observed behavior:

```
man hash
1  (Program section)  4       (Device section)  7    (Misc section)  l  (Local section)  p                 
2  (Syscall section)  5  (File format section)  8   (Admin section)  n    (New section)  tcl  (Tcl section)
3  (Library section)  6        (Games section)  9  (Kernel section)  o    (Old section)  
```

(`hash` is the autosuggestion in this case)

### Additional information:

I can reproduce this on two different machines. `fish_update_completions` doesn't fix it.

---
Fish version: 

```
wieland@mineo ~> fish --version
fish, version 2.3.0
```

Operating system: Arch Linux

Terminal or terminal emulator: urxvt

**Comment by faho** [comment]
The man completions complete sections until you've entered _something_. Try `man h<TAB>`. Then it should complete man pages that include "h" in the name or description.

Which seems okay since there's a lot of man pages on a typical system (mine has about 16000).

If it doesn't work like that for you, please yell! Otherwise, this seems like it's working as intended.

**Comment by mineo** [comment]
It's the same if I've already added the section id though (I can open another issue for that if you want). Is the list of completions for man generated on demand? For comparison, `man <tab>` works on ZSH just fine with 22000 man pages on my (now 6 year old) notebook.

**Comment by faho** [comment]
>Is the list of completions for man generated on demand?

Yes - see the `__fish_complete_man` function.

To be clear: It's not a performance issue. It's that offering 16000 things isn't all that useful. You're not going to scroll through them, and if you enter something, it filters it down anyway. And if we offered 16000 things _plus_ the sections, the sections would be lost in the noise.

>It's the same if I've already added the section id though

You mean the offered man pages aren't exclusively in the section you entered? Yeah, that'd be useful.

**Comment by faho** [comment]
It already completed pages for the given section id, what it didn't do was show all pages for a given section (and it also shows section ids when pages where asked for).

I've now fixed that (plus it also always offered "0" and sometimes "1", since it used `count` and didn't silence the output).
