### ISSUE TITLE
git <tab> only completes to --help

### ISSUE THREAD

**Issue by mineo** [fish-shell/fish-shell#3087]
### Reproduction Steps:

1. `rm -rf ~/.config/fish; rm -rf ~/.local/share/fish`
2. `fish`
3. `git  --<tab>`

### Expected behavior:

All of the options to `git` should be suggested:

```
git --help
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
```

### Observed behavior:

Autocompletion to `--help`

### Additional information:

`fish_update_completions` doesn't help.

---
Fish version: 2.3.0

Operating system: Arch Linux

Terminal or terminal emulator: urxvt

**Comment by faho** [comment]
Yes, the git completions are partly incomplete (and they are always going to be, because git is _massive_).

>fish_update_completions doesn't help.

That's expected, because the git completions are hand-written. I don't think it's possible to write a man page parser that generates completions to this level.
