### ISSUE TITLE
if / else if / else handling is bizarre

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#309]
Here's how if / else if / else is currently handled:

An if command creates a new IF block.

When evaluating a command in an IF block, we look at the `if_expr_evaluated` variable. If it's set to false, we evaluate the command and then set the any_branch_taken flag as appropriate. If also sets the `skip` flag in the block.

`else` is either executed like a normal command, or from `skipped_exec()`. It inspects the properties of the IF block to determine whether to run its commands.

`else if` is handled yet a third way: upon encountering an `else if`, we set `JOB_ELSEIF` to true in the job. We then look for that flag in `parser_t::eval_job` and decide whether to unskip the block.

It would be great if we could unify if, else if, and else all under one approach instead of this mishmash.

**Comment by zanchey** [comment]
I think this can be closed since the new parser landed.

**Comment by ridiculousfish** [comment]
Yep, thanks.
