### ISSUE TITLE
string match -n does not work with -r -v

### ISSUE THREAD

**Issue by msteed** [fish-shell/fish-shell#3098]
`string match` with `-r` (regex) and `-v` (invert) does not respect `-n` (index).

### Reproduction Steps:

> $ string match -r -v -n a b

### Expected behavior:

`fish` should report the start position and length when `-n` is given, as it does without `-v`.

### Observed behavior:

> $ string match -r -v -n a b
> b

### Additional information:

I think this was introduced with the addition of the `(-v | --invert)` options to `string`. The problem appears to be here: https://github.com/fish-shell/fish-shell/blob/master/src/builtin_string.cpp#L378-L381 where the argument is reported without checking for `opts.index` as is done below.

---
Fish version: `fish, version 2.3.0`

Operating system: Arch linux, fish installed from the official package

**Comment by faho** [comment]
>fish should report the start position and length when -n is given, as it does without -v.

"--invert" is maybe a bit inaccurate here. What it does is ignore all arguments/lines without a match (taken straight from grep's `-v` or `--invert` option). I can't see how you can say where a non-match starts - unless it's always "1", and the length is always the length of the entire string.

**Comment by msteed** [comment]
Right, and this is the current behavior without `-r`:

> $ string match -n -v a bbb
> 1 3

**Comment by faho** [comment]
Yeah, maybe this is useful for someone.

I've now pushed a commit which I believe fixes it.

Thanks!

**Comment by ridiculousfish** [comment]
If we do a 2.3.1, we ought to take this too.

**Comment by floam** [comment]
I'm not sure I ever tried `-n` and `-v` together while I was adding `-v` -- never occurred to me that it should do anything. That it worked without `-r was just lucky. Are the exit codes as expected?
