### ISSUE TITLE
$status is always 0 in fish_postexec

### ISSUE THREAD

**Issue by paradox460** [fish-shell/fish-shell#3103]
The `$status` variable does not update to reflect the status of the process which just finished. It used to do this.

### Reproduction Steps:

1. Add this to your config.fish:
  ```
  function print_status -e fish_postexec
    echo $status
  end
  ```
2. Run a command, such as `true`. You get exit code 0, as expected
3. Run a command that returns non-0 exit code, such as `false`. You get 0, which is not expected

### Expected behavior:

`$status` should reflect the exit code of the just-run program.

### Observed behavior:

`$status` does not reflect the exit code of the just-run program inside of `fish_postexec` functions, instead always returning 0. It *does* reflect the status accurately in a new command, however.

---
Fish version: `fish, version 2.3.0-175-g0a40dcd`

Operating system: `OS X 10.11.5 (15F34)`, `Homebrew 0.9.9`

Terminal or terminal emulator: iTerm2 3.0.0

**Comment by faho** [comment]
It does for me.

Can you paste the output of `fish -d 5` when you run e.g. `false` and `true` inside of it?

Also your configuration might be nice.

Of course it would be nice to know _why_ you are doing this on that event and not e.g. in your `fish_prompt` function. What are you trying to do?

**Comment by paradox460** [comment]
[`fish -d 5` output](https://gist.github.com/paradox460/d79c2e1e88c8cb2fdc158e4e89c7b33e)

----

My configs are available at https://github.com/paradox460/.dotfiles/blob/master/.config/fish/config.fish, but the specific usage of this function is in a theme, https://github.com/paradox460/paradox-theme/blob/master/init.fish#L37, which is used to display lines between commands.

I could probably refactor the lines to be a part of the prompt, but doing it this way doesn't display a line on shell init.

That said, I figured I should open this ticket as it seems to be a regression in newer versions of fish

**Comment by faho** [comment]
Uhm... did you test your simplified example?

Because this:

```fish
if type jot >/dev/null ^/dev/null
      set -l last_status $status
```

_cannot_ work - the status there will always be 0 because you've now run a new command that, if the ´set` is executed, succeeded by definition. `set -l last_status $status` has to be the _first_ line here.

**Comment by paradox460** [comment]
Ah…damn. Thank you for your patience, I should have caught that, or tested the simplified example.

I'll close this ticket.
