### ISSUE TITLE
fish_history location changed after update

### ISSUE THREAD

**Issue by mart-e** [fish-shell/fish-shell#3105]
After update to 2.3, the history changed from `~/.config/fish/fish_history` to `~/.local/share/fish/fish_history` without moving the previous file, creation a new one.

### Reproduction Steps:

1. Have a nice and useful history
2. Upgrade
3. Discover the lost history

### Expected behavior:

When changing, the history is moved/copied from the previous location

### Observed behavior:

I need to manually move the `fish_history` file from config to local to benefit from the previous history.

### Additional information:

Archlinux, fish 2.3.0-1, Terminator 0.98-2

**Comment by ridiculousfish** [comment]
There is a function `history_t::populate_from_config_path()` which is supposed to migrate this file, and it's working for me.

Can you please double check that if you use bash to move the history file `~/.local/share/fish/fish_history` aside, and then start fish, that file does not get created with the contents of `~/.config/fish/fish_history`? In my tests it does.

**Comment by mart-e** [comment]
```
$ bash
$ mv ~/.local/share/fish/fish_history ~/.local/share/fish/fish_history.old
$ fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
$ ls -lh ~/.local/share/fish/fish_history
-rw-r--r-- 1 mat users 1.9M Jun  2 10:55 /home/mat/.local/share/fish/fish_history
```
Ok so it seems to work fine indeed. Is it possible this was not called during the upgrade of the package?

**Comment by mart-e** [comment]
Tested on another computer running archlinux as well, got no issues, the history was correctly moved.
Not sure what happened but I guess it's solved.
