### ISSUE TITLE
Roll a 2.3.1 release

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#3106]
It seems 2.3.0 isn't perfect and had some small issues. So it would be nice to make a quick release to fix all of those we can.

Things that should be included:

- Bug fixes - especially regressions and security issues (don't think we have one of those)

- Completion updates - these are self-contained and there's been some nice additions

- Documentation changes - there's no way of these breaking anything

So that means e.g. #3090 should _not_ be included.

We already have a [2.3.1 milestone](https://github.com/fish-shell/fish-shell/milestones/2.3.1) which should be added to all issues/PRs that should be fixed in 2.3.1, but we also need to add commits that don't have an issue or PR attached.

Anyone have a magic git incantation to show all commits that _actually_ aren't in 2.3.0 (even if they were cherry-picked)?

**Comment by faho** [comment]
Of course the alternative would be a slightly-less-quick 2.4.0 release that would include all the goodies since 2.3.0 - including e.g. `fish_key_reader`.

**Comment by zanchey** [comment]
> Anyone have a magic git incantation to show all commits that actually aren't in 2.3.0 (even if they were cherry-picked)?

`git cherry 2.3.0 master` should do the job, but it doesn't work with the cherry-picked commits in my tests.

**Comment by zanchey** [comment]
Let's do 2.3.1 in the next week. I've branched `Integration_2.3.1`.

**Comment by krader1961** [comment]
I've merged fish_key_reader (issue #2991, PR #3012).

**Comment by krader1961** [comment]
I've merge the fix for "Fish prints new lines when entering text" (issue #2859, PR #3151).

**Comment by krader1961** [comment]
I've merged the fix for passing \cV through the tty driver (issue #3064).

**Comment by krader1961** [comment]
I've merged the fix for setting the locale and terminfo vars (issue #3124, PR#3109, PR#3112, PR#3143).

**Comment by krader1961** [comment]
I've merged the fix for "Several ssh_config rules aren't being matched" (PR#3146).

**Comment by krader1961** [comment]
I've merged the enhanced autocompletions (PR#3123).

**Comment by krader1961** [comment]
I've merged the `git commit --<tab>` shows error message fix (PR#3114).

**Comment by krader1961** [comment]
I've merged the correct __fish_contains_opts to __fish_contains_opt fix (PR#3102).

**Comment by krader1961** [comment]
I've merged the string match -n does not work with -r -v fix (issue #3098).

**Comment by krader1961** [comment]
I've merged "Add Purge Subcommand Completion for Apt" (PR#3097).

**Comment by krader1961** [comment]
I've merged history --delete not working (issue #3054).

And with that cherry-pick I believe I've incorporated the commits for all the closed issues and PRs flagged for this release. That leaves just a couple of open issues to be integrated when the fixes for those issues are committed.

**Comment by ridiculousfish** [comment]
Cool - thanks krader!

**Comment by krader1961** [comment]
It didn't seem fair to make @zanchey deal with all of those. Especially since a couple of mine needed some surgery to backport them. He has enough work to do just creating the packages.

**Comment by krader1961** [comment]
Merging the fix for handling locale env vars inadvertently included part of the fix for handling TERMINFO so I've also labeled that issue for 2.3.1 and merged the rest of the change (issue #3060, PR #3109).

**Comment by zanchey** [comment]
Looks like we're good to go - I'll work on the release notes.

**Comment by krader1961** [comment]
I've back-ported the vastly improved `fish_key_reader` program. It now prints an example `bind` command and no longer prints a lot of information of little value for most users. Note that f-k-r wasn't part of the 2.3.0 release. Normally I wouldn't add a major change to what is ostensibly a bug release but the utility of this program is so great, and the risks nonexistent, that it seems worth breaking the usual rules about what is included in a minor release.

**Comment by floam** [comment]
I've fixed #3140 in `master` and `Integration-2.3.1`: 

https://github.com/fish-shell/fish-shell/commit/ca6cda20a36e91a764c17b218b07a8970d813663

**Comment by floam** [comment]
The `string` fallback in Integration is now a fall...forward per @zanchey's recommendation: since this issue is encountered typically during upgrades, we use `fish -c string ...` for a command that actually works.
