### ISSUE TITLE
process gets stuck.

### ISSUE THREAD

**Issue by stephennancekivell** [fish-shell/fish-shell#311]
Sometimes the fish process crashes using 100% cpu.

If I strace it I see its making this call all the time. Dont know what that means. Or how i can further debug it.

futex(0x7fe7c6e8cba0, 0xa0 /* FUTEX_??? */, 2) = -1 ENOSYS (Function not implemented)
futex(0x7fe7c6e8cba0, 0xa0 /* FUTEX_??? */, 2) = -1 ENOSYS (Function not implemented)

fish, version 1.23.1
linux 3.2.0-29-generic #46-Ubuntu

**Comment by faho** [comment]
There hasn't been any activity here in 3 years, so I'm closing this. If this is still an issue please comment and I'll reopen.
