### ISSUE TITLE
fish allocates all available memory

### ISSUE THREAD

**Issue by xdudi** [fish-shell/fish-shell#3111]
```
wget http://download.geofabrik.de/europe/great-britain/scotland-latest.osm.bz2
bzip2 -d scotland-latest.osm.bz2
cat scotland-latest.osm | grep -v addr | grep -i glasgow
```
This simple search operation made a crash on my system. :)

**Comment by faho** [comment]
This is #1396. We buffer input/output for functions - which `grep` is by default (a wrapper to pass "--color=auto").

As a workaround, use `command grep`.

**Comment by xdudi** [comment]
Is any limit of functions' i/o buffer?

**Comment by faho** [comment]
As far as I know not, and it doesn't seem like you're hitting it.

**Comment by xdudi** [comment]
@ridiculousfish 
Can you tell me why fish has unlimited i/o buffer for functions?
It makes a crash whole system, but bash works correctly.

**Comment by ridiculousfish** [comment]
fish buffers function output in some cases because fish uses the C stack to implement functions. This means only one function can execute at a time, so its output must be buffered. Limiting the size of the buffer seems like a smart idea.

**Comment by xdudi** [comment]
If this is important, it shouldn't be closed currently.

**Comment by zanchey** [comment]
It is important, but it's a duplicate of another issue, so we'll track there (#1396).
