### ISSUE TITLE
`git commit --<tab>` shows error message when outside of a repository

### ISSUE THREAD

**Issue by mineo** [fish-shell/fish-shell#3114]
### Reproduction Steps:

1. `git commit --<tab>`

### Expected behavior:

Just show me the list of options.

### Observed behavior:

```
wieland@mineo ~> git commit --fatal: Not a git repository (or any of the parent directories): .git

--amend  (Amend the log message of the last commit)  --help  (Display the manual of a git command)
```

### Additional information:

Trying to complete filenames at that point doesn't make sense, `git commit --filename` doesn't work.

---
Fish version: 2.3.0

**Comment by SunDwarf** [comment]
That's some damn fast bug resolution right there.
