### ISSUE TITLE
set: Tried to change the read-only variable SHLVL

### ISSUE THREAD

**Issue by lucasb-eyer** [fish-shell/fish-shell#3120]
Since updating to fish 2.3.0 (Arch Linux) I'm being greeted with that message all the time.

`fish` is my login shell, my flow is fish -> startx (awesomewm) -> urxvt (fish), and the second one is where the message appears, this is what I'm greeted with at a new terminal:

```
set: Tried to change the read-only variable “SHLVL”
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
:) [beyer@grimbergen:~ 22:37:41]
><((("> 
```

Also:

- `echo $SHLVL` -> `3`
- `ag SHLVL ~/.config/fish` (search `SHLVL` in all files in `~/config/fish`) turns up nothing.
- The message also appears when I do ssh with tunneling using ProxyCommand, but probably just because that runs a shell at some point, I don't really know.

**Comment by ridiculousfish** [comment]
Can you please post the output of `fish -d4`? That will give us some clues as to who is trying to set SHLVL

**Comment by lucasb-eyer** [comment]
Wow, thanks, this shows it's my own fault.

It's not the update to 2.3.0, but a single command that I've added to my `confif.fish` right after the update to 2.3.0 related to #3092 (and then forgot about) that causes this behaviour. The command was:

```
env -i HOME=$HOME sh -c 'printenv' | sed -e '/_/d ; /PWD/d ; /PATH/s/:/ /g ; s/=/ / ; s/^/set -x /'
```

which sets a bunch of default variables from `sh` (as populated for sh/bash/zsh-only by the distro via `/etc/profile` and friends) in `fish`, but forgets to skip `SHLVL`.

Thank you, closing, and my apologies for the noise as it's entirely my own fault.

**Comment by touhidulShawan** [comment]
I am new at the fish shell. I setup fish shell and oh my fish plugin manager in my arch machine. When I worked with nvm then shell give this same message ` set: Tried to change the read-only variable “SHLVL” `  I am not understanding it. The last line says not sourcing `.config/fish/config.fish` but the configuration is being loaded from `~/.config/fish/conf.d/omf.fish` file. How can I solve it
The output of  `fish -d4` here
```
<2> fish: exec_path: '/usr/bin/fish', argv[0]: 'fish'
<2> fish: Using compiled in paths:
<2> fish: determine_config_directory_paths() results:
paths.data: /usr/share/fish
paths.sysconf: /etc/fish
paths.doc: /usr/share/doc/fish
paths.bin: /usr/bin
<2> fish: curses var TERM='xterm-256color'
<2> fish: curses var TERMINFO missing or empty
<2> fish: curses var TERMINFO_DIRS missing or empty
<2> fish: 256 color support enabled for TERM=xterm-256color
<2> fish: default emoji width: 2
<2> fish: sourcing /usr/share/fish/config.fish
<2> fish: 256 color support enabled for TERM=xterm-256color
<2> fish: 'fish_term24bit' preference: 24-bit color enabled
<2> fish: sourcing /etc/fish/config.fish
<2> fish: not sourcing /home/shawan/.config/fish/config.fish (not readable or does not exist)
```

**Comment by faho** [comment]
@touhidulShawan You have something in your configuration that tries setting $SHLVL, you need to remove that.

Since your configuration is oh-my-fish, you might want to ask the oh-my-fish folks.

**Comment by touhidulShawan** [comment]
@faho Thanks for your reply. Ok

**Comment by BlakeHolifield** [comment]
@touhidulShawan @faho Sorry to poke a closed issue, but in my case, this was caused by a strange `fisher` and `omf` conflict. `omf destroy` fixed it all right up. Hope this helps someone in the future!
