### ISSUE TITLE
fish_config doesn't load prompt page

### ISSUE THREAD

**Issue by RSully** [fish-shell/fish-shell#3121]
fish_config may be incompatible with Python installed from conda.

### Reproduction Steps:

1. Install anaconda with Python 3.5 ([link](https://www.continuum.io/downloads))
2. Put the conda bin at the beginning of PATH to override system Python (can be done automatically from the anaconda installer)
3. Open a fish shell
4. Run fish_config
5. Click on "prompt" tab

### Observed behavior:

Prompt page does not load (no options, no current prompt)

The fish webpage outputs "The request received an error. Perhaps the server has shut down."

The shell shows this:

```
----------------------------------------
Exception happened during processing of request from ('::1', 45592, 0, 0)
Traceback (most recent call last):
  File "/data/anaconda3/lib/python3.5/socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/data/anaconda3/lib/python3.5/socketserver.py", line 344, in process_request
    self.finish_request(request, client_address)
  File "/data/anaconda3/lib/python3.5/socketserver.py", line 357, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/data/anaconda3/lib/python3.5/socketserver.py", line 684, in __init__
    self.handle()
  File "/data/anaconda3/lib/python3.5/http/server.py", line 415, in handle
    self.handle_one_request()
  File "/data/anaconda3/lib/python3.5/http/server.py", line 403, in handle_one_request
    method()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 769, in do_GET
    output = self.do_get_sample_prompts_list()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 696, in do_get_sample_prompts_list
    sample_results = pool.map(self.read_one_sample_prompt, paths, 1)
  File "/data/anaconda3/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/data/anaconda3/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
  File "/data/anaconda3/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/data/anaconda3/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/share/fish/tools/web_config/webconfig.py", line 682, in read_one_sample_prompt
    result = self.do_get_sample_prompt(func, extras_dict)
  File "/usr/share/fish/tools/web_config/webconfig.py", line 648, in do_get_sample_prompt
    return self.do_get_prompt(cmd, text.strip(), extras_dict)
  File "/usr/share/fish/tools/web_config/webconfig.py", line 629, in do_get_prompt
    prompt_demo_html = ansi_to_html(prompt_demo_ansi)
  File "/usr/share/fish/tools/web_config/webconfig.py", line 250, in ansi_to_html
    span_open = append_html_for_ansi_escape(component, result, span_open)
  File "/usr/share/fish/tools/web_config/webconfig.py", line 196, in append_html_for_ansi_escape
    special_escapes = get_special_ansi_escapes()
  File "/usr/share/fish/tools/web_config/webconfig.py", line 151, in get_special_ansi_escapes
    curses.setupterm()
_curses.error: setupterm: could not find terminfo database
----------------------------------------
```
  
### Workaround

In fish if I modify PATH to remove the conda bin then run fish_config it works.

---
Fish version: 2.3.0

Operating system: Ubuntu 16.04, PPA

Terminal or terminal emulator: default Ubuntu Terminal

**Comment by zanchey** [comment]
> `_curses.error: setupterm: could not find terminfo database`

Well, there's your problem.

**Comment by krader1961** [comment]
Works for me.

```
$ python
Python 3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:24:55)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import curses
>>> curses.setupterm()
>>>
```

If you run the above by hand like I did does it succeed or fail in the same manner as the fish webconfig app? What TERM&ast; vars are in your environment?

**Comment by RSully** [comment]
Hmm, that fails too:

```
> python
Python 3.5.1 |Anaconda 4.0.0 (64-bit)| (default, Dec  7 2015, 11:16:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import curses
>>> curses.setupterm()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_curses.error: setupterm: could not find terminfo database
```

TERM is `xterm-256color`, TERMINFO is not set.

**Comment by krader1961** [comment]
Did you confirm that TERM is actually exported; e.g., `env | grep TERM`? Does `infocmp $TERM` output the definition for you term type? The latter is to verify there is actually a matching terminfo file since I don't believe python will use termcap files. This anaconda issue might be relevant: https://github.com/ContinuumIO/anaconda-issues/issues/455

**Comment by RSully** [comment]
```
> env | grep TERM
TERM=xterm-256color
> infocmp $TERM
infocmp: couldn't open terminfo file (null).
```

**Comment by krader1961** [comment]
> infocmp: couldn't open terminfo file (null).

There's the real problem. You need to install the terminfo support files on your system. On my Ubuntu 16.04 system those are provided by the `ncurses-base` and `ncurses-term` packages. I'll bet `dpkg --list|grep ncurses` doesn't list them as being installed on your system.

**Comment by RSully** [comment]
Installing `ncurses-term` with apt didn't help. `ncurses-base` was already installed. If I remove my anaconda bin from PATH then it works fine. 

```
$ fish
> echo $PATH
/usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin
> python
Python 2.7.11+ (default, Apr 17 2016, 14:00:29) 
[GCC 5.3.1 20160413] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import curses
>>> curses.setupterm()
>>> 
> set -x PATH /data/anaconda3/bin $PATH
> python
Python 3.5.1 |Anaconda 4.0.0 (64-bit)| (default, Dec  7 2015, 11:16:01) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import curses
>>> curses.setupterm()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_curses.error: setupterm: could not find terminfo database
>>> 
```

Sounds like this only a problem with the ncurses package from conda-forge. Do you have ncurses installed with conda, and which version?

**Comment by RSully** [comment]
I'm going to close this as it is clearly a non-fish issue. Can still use this as a discussion thread though.

**Comment by jakirkham** [comment]
Are you using `ncurses` from conda-forge? If so, it may be issue ( https://github.com/conda-forge/ncurses-feedstock/issues/17 ). If you would like to try the proposed fix in PR ( https://github.com/conda-forge/ncurses-feedstock/pull/19 ), I'd appreciate the feedback, @RSully.

**Comment by preachermanx** [comment]
Sorry to necro this thread, but I am experiencing the same issue.
I was able to debug it and it was due to Scientific Linux's python being way out of date (on this install which is EOL SL6.2).  Soon as I used a userland python greater than 2.6.6 webconfig page for the prompt worked and rendered correctly.

**Comment by miaobuao** [comment]
that can be solved by
```sh
conda deactivate
```
then:
```sh
fish_config
```
