### ISSUE TITLE
Completions for herbstluftwm/herbstclient

### ISSUE THREAD

**Issue by wilriker** [fish-shell/fish-shell#3122]
Hi,

I first want to say, I only recently switched to `fish` and I love it! After realizing that I configured my `zsh` so much that I ended up basically having a `fish` anyway this was the right next move. ;-)

So, I am also using `herbstluftwm`. a manual tiling window manager for X. This is running as a daemon that is controlled by a CLI interface called `herbstclient`. There is no provided completion file for it and man-page-generated completion also only works for `herbstclient` parameters. Usually though it is used like
`herbstclient <COMMAND> [ARGS]`

Fortunately `herbstluftwm` already provides some means for completion and can be seen [here](https://github.com/herbstluftwm/herbstluftwm/blob/master/share/herbstclient-completion) for `bash` completion or [here](https://github.com/herbstluftwm/herbstluftwm/blob/master/share/_herbstclient) for `zsh` completion.

Based on this approach I ended up with the following code

```
function _get_herbstclient_completion
    set -l tokens (commandline -op)

    # If the user only just entered "herbstclient" return everything
    if test (count $tokens) -eq 1
        herbstclient -q complete 0
        return
    end

    set -l parameters $tokens[2..-1]
    set -l position (math (count $parameters) - 1)

    # TODO: This should be reused in case below if statement evaluates false
    set -l completions (herbstclient -q complete $position $parameters)

    # If the last parameter equals the only result increase the position to get the next token
    if test (count $completions) -eq 1
        and string match -- $completions[1] $parameters[-1]
        set position (math $position + 1)
    end
    herbstclient -q complete $position $parameters
end

complete -xc herbstclient -d "" -a '(_get_herbstclient_completion)'

complete -c herbstclient -f -s n -l no-newline -d 'Do not print a newline if output does not end with a newline.'
complete -c herbstclient -f -s 0 -l print0 -d 'Use the null character as delimiter between the output of hooks.'
complete -c herbstclient -f -s l -l last-arg -d 'When using -i or -w, only print the last argument of the hook.'
complete -c herbstclient -f -s i -l idle -d 'Wait for hooks instead of executing commands.'
complete -c herbstclient -f -s w -l wait -d 'Same as --idle but exit after first --count hooks.'
complete -c herbstclient -f -s c -l count -r -d 'Let --wait exit after COUNT hooks were received and printed.'
complete -c herbstclient -f -s q -l quiet -d 'Do not print error messages if herbstclient cannot connect to the running herbstluftwm instance.'
complete -c herbstclient -f -s v -l version -d 'Print the herbstclient version.'
complete -c herbstclient -f -s h -l help -d 'Print the herbstclient usage with its command line options.'
```

This already works mostly. Using e.g.
`herbstclient <tab>` provides a list of all commands
or
`herbstclient t<tab>` provides a list of all commands starting with `t`
or
`herbstclient toggle <tab>` provides a list of available parameters to the command `toggle`
or
`herbstclient -<tab>` provides the list of options to `herbstclient` itself.

The problem now comes in when I try to combine option parameters to `herbstclient` with commands that will be sent from `herbstclient` to `herbstluftwm` like
`herbstclient -n <tab>`
This will never result in anything but file/dir completions (even though I disabled them, as far as I understood the `complete` builtin).

Can this be done at all?

Best regards
Manuel

**Comment by faho** [comment]
>This will never result in anything but file/dir completions (even though I disabled them, as far as I understood the complete builtin).

That's #112.

**Comment by wilriker** [comment]
I think I was a bit unclear. My main concern was not that I got these file completions (they are a bit annoying but still ok) but that I could not combine option completions (those at the bottom of the code snippet) with the command completion. But that was my fault in the implementation. I thought(!) it would not even trigger the command completion code but it did and what I had to do was to filter out the `-<something>` tokens in the function `_get_herbstclient_completion`. Now it works.

Sorry for bothering, I will close this now.

**Comment by faho** [comment]
>My main concern was not that I got these file completions (they are a bit annoying but still ok) but that I could not combine option completions (those at the bottom of the code snippet) with the command completion.

Sorry, I just didn't have enough time to look at the main issue and wanted to link the related issue immediately so I wouldn't forget.

>what I had to do was to filter out the -<something> tokens in the function _get_herbstclient_completion. Now it works.

I think your issue is more that `commandline -op` will ignore the current token if it is empty. The workaround is to check if `commandline -ct` is empty and then adding an empty token to the end if it is.

**Comment by wilriker** [comment]
> I think your issue is more that `commandline -op` will ignore the current token if it is empty. The workaround is to check if `commandline -ct` is empty and then adding an empty token to the end if it is.

I realized this as well, also as mentioned before there was another bug: I did not ignore those tokens that represent a `herbstclient` option. Meanwhile I ended up with (just the function, everything below that is the same)

```
function _get_herbstluftwm_completion
    set -l tokens (commandline -op)

    # Delete "herbstclient"
    set -e tokens[1]

    # Filter herbstclient options
    set -l index (count $tokens)
    for token in $tokens[-1..1]
        if string match --quiet -- "-" (string sub -l 1 -- $token)
            set -e tokens[$index]
        end
        set index (math "$index - 1")
    end

    set -l position (count $tokens)

    # If we have tokens but and cursor sits on a word (not space) decrease position due to 0-based in hlwm and 1-based in fish
    if test $position -gt 0 -a -n (commandline -ct)
        set position (math "$position - 1")
    end
    herbstclient -q complete $position $tokens
end
```
This is working now as supposed except a few cases where a parameter sent to `herbstluftwm` will start with a dash (these a rare though). Thanks for pointing me to `commandline -ct` and checking for empty. That simplified my code a lot (I did the same thing but way more complicated).

**Comment by faho** [comment]
```fish
# Filter herbstclient options
    set -l index (count $tokens)
    for token in $tokens[-1..1]
        if string match --quiet -- "-" (string sub -l 1 -- $token)
            set -e tokens[$index]
        end
        set index (math "$index - 1")
    end
```

Your `string match` is kinda weird - do you want to check if it starts with "--"? Then why not do `string match -q -- "--" $token`? Also you can get by without calling `math` if you just add all tokens you want to keep to a new variable, like

```fish
set -l tok
for token in $tokens
    if not string match -q -- '--*' $token
        set tok $tok $token
    end
end
```

(Also github has fish syntax highlighting if you start a codeblock with ````fish`)

**Comment by wilriker** [comment]
I was wondering how I could get github to use `fish` syntax highlighting. Thanks!

> Your string match is kinda weird - do you want to check if it starts with "--"? Then why not do `string match -q -- "--" $token`?

Totally forgot about globbing capabilities of `string match`! What I actually wanted to check was if a token starts with a single dash to also find short options like `-n`.

Based on your proposal I reimplemented this check to only remove `herbstclient` options at the beginning of the commandline (where they can appear) until the first parameter not starting with a dash is found. This way I prevent issues with commandlines such as
`herbstclient -n use_index -1 <tab>`
which also got the `-1` near the end removed and therefore endlessly proposed `+1` and  `-1` instead of completing with (the only viable option) `--skip-visible` which in turn was also ignored that lead to another endless completing. ;-)

```fish
# Filter herbstclient options
for token in $tokens
    if string match -q -- "-*" $token
         set -e tokens[1]
    else
        break
    end
end
```
Thanks for all the support!
