### ISSUE TITLE
Why does `set_color reset` exist?

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3128]
Why does `set_color reset` exist? It isn't documented. A cursory glance at the set_color() function shows that it is special cased but my informal testing shows that it produces the same output as set_color normal. It is used in the core fish code in just two files: _share/functions/vared.fish_ and _tests/test_util.fish_.

I noticed this when working on issue #2980 when trying to understand when and why `term_donate()` was setting the colors to "normal". I then noticed that there was a "reset" color which seems to have the same effect.

**Comment by floam** [comment]
The intended distinction is documented [here](https://github.com/fish-shell/fish-shell/blob/53e865b65434fa9ec12afc11a076aec244cd3c43/src/output.h#L35). It forces the behavior even if it think it is already "normal"?

**Comment by krader1961** [comment]
Good catch. Note that none of those enum symbols are actually used anywhere in the code. Sigh.

And it doesn't explain why it isn't documented.

It looks like there has been way too many years where people were making incremental changes without adding "TODO" comments to remind people to finish the change by removing dead wood.

**Comment by brj** [comment]
I don't know if this is related, but in Travis logs, when you print something, echo xxx, it's white bright. If you change colors with set_color, that works as you'd expect, but when you set_color back to normal, the output is **no** longer white bright as in the original echo, but that terminal foreground white (which is gray).

**Comment by krader1961** [comment]
There was a discussion earlier today about `set_color reset`. The result was @floam creating creating commit bd03c3fbc to change it to `set_color normal` in share/functions/vared.fish. I then created commit 2e81ade66 to do the same for tests/test_util.fish. So as of this comment there is no code in the fish project which uses `set_color reset`.

TBD is whether `set_color reset` was ever documented and thus needs to be maintained for backward compatibility. If it was then the `set_color` documentation needs some verbiage about its deprecated status. Otherwise it should simply be removed from the code.

**Comment by krader1961** [comment]
@floam: Is there some reason we should continue to recognize `set_color reset`? The comment in the [link](https://github.com/fish-shell/fish-shell/blob/53e865b65434fa9ec12afc11a076aec244cd3c43/src/output.h#L35-L37) you provided is no longer present. You removed it with your commit 36698056 on 2016-07-21. My testing has failed to show any difference in behavior between `set_color reset` and `set_color normal`. Even if I attempt to contrive a situation where the the latter might be unneeded. For example:

```
function wtf
	set_color normal
        set_color reset
	set_color normal
end
```

**Comment by floam** [comment]
'reset' does have a unique meaning versus 'normal', but not through the builtin. Try setting some fish_color_* variables to one or the other.

**Comment by krader1961** [comment]
@floam, The doc string for `output_color()` sort of explains why `reset` exists; however, the logic is dense enough that I can't be bothered to figure out what is actually going on. And nowhere in our documentation is this magic value documented. Nor can I find it used in any of the sample prompts. Neither is it used in the default color scheme or any of the sample color schemes available via `fish_config`. Since you seem to be the only person who understands why this magic color value exists would you please add some documentation explaining why and when it makes sense to use it?

**Comment by floam** [comment]
Today we use `::reset()` in `builtin_set_color.cpp`, and I'm closing this.
