### ISSUE TITLE
Unexpected crash when using pkill

### ISSUE THREAD

**Issue by mikroskeem** [fish-shell/fish-shell#3129]
Fish crashes, when I try to write pkill command

### Reproduction Steps:

1. Install Arch Linux
2. `pacman -S fish && fish`
3. Try to write `pkill curl`

### Expected behavior:

I should be able to complete my command

### Observed behavior:

```
fish: src/complete.cpp:442: void complete_add(const wchar_t*, bool, const wcstring&, complete_option_type_t, int, const wchar_t*, const wchar_t*, const wchar_t*, complete_flags_t): Assertion `option.empty() == (option_type == option_type_args_only)' failed.
fish: 'fish' terminated by signal SIGABRT (Abort)
```

---
Fish version: `fish, version 2.3.0`

Operating system: Arch Linux, `pacman -S fish`

Terminal or terminal emulator: urxvt

**Comment by krader1961** [comment]
This is clearly a bug since an assert() should never fail. However, I can't reproduce on OS X or Ubuntu 16.04. When you say

> Try to write `pkill curl`

Do you mean you pressed [tab] after entering that string? Or that you pressed [tab] after entering `pkill` at which point `curl` was appended then the failure occurred? Or something else?

**Comment by mikroskeem** [comment]
> I should be able to complete my command
By that I meant that I could write `curl`, but shell crashes after I start writing it. I don't press [tab] at all

https://asciinema.org/a/cpy9m386bvcy1ofc2ts1acr8o this might help.

**Comment by faho** [comment]
I can't reproduce this on arch, so I have a few questions:

- Is this a first-time install or did you upgrade? Do you have any history?

- Do you have any custom completions or functions?

- Is curl running or not? Does it make a difference if it is?

**Comment by mikroskeem** [comment]
@faho 

First time install of fish shell

No, I don't have custom completions and functions

And no, it doesn't make difference.

**Comment by mikroskeem** [comment]
Reproduced it on fresh Arch Linux install.

**Comment by faho** [comment]
We're missing something here. I've installed the official Arch fish 2.3.0 package, run fish as a new user and cannot reproduce this.

Since the suggestions are hooked up to completions, it seems that triggers it, but there has to be a reason it's breaking the assert.

Does this only happen in a particular directory (e.g. can you try it while you're in a new, empty, directory?)? Does this only happen with "c"? I'm thinking we're maybe doing something wrong locale-wise. What is your `locale` (and $LANGUAGE)?

**Comment by mikroskeem** [comment]
My locale is `et_EE.UTF-8`. When I do `set LANG C`, then it won't crash

No, it doesn't matter what directory I use

**Comment by faho** [comment]
With that locale, I can reproduce.

**Comment by krader1961** [comment]
> With that locale, I can reproduce.

Let me guess, if you revert 0b385f145 the problem disappears? If so I'm really starting to hate the locale subsystem.

**Comment by faho** [comment]
No, it also acts like that on 2.3.0.

**Comment by krader1961** [comment]
> No, it also acts like that on 2.3.0.

&lt;me&gt;Wipes brow in relief.&lt;/me&gt; Given a UTF-8 locale we really shouldn't be seeing failures like this since the et_EE portion should only affect localization of messages, date/time formatting, etc. It's probably another character classification problem similar to issue #2576.

**Comment by krader1961** [comment]
I can reproduce on Ubuntu 16.04 I can reproduce using fish from git head. I cannot reproduce on Mac OS X.

**Comment by krader1961** [comment]
The problem is with the signal map. In the C locale:

```
$ env LC_ALL=et_EE.utf8 fish -d1
$ __fish_make_completion_signals
$ echo "$__kill_signals"
1 HUP 2 INT 3 QUIT 4 ILL 5 TRAP 6 ABRT 7 BUS 8 FPE 9 KILL 10 USR1 11 SEGV 12 USR2 13 PIPE 14 ALRM 15 TERM 16 STKFLT 17 CHLD 18 CONT 19 STOP 20 TSTP 21 TTIN 22 TTOU 23 URG 24 XCPU 25 XFSZ 26 VTALRM 27 PROF 28 WINCH 29 POLL 30 PWR 31 SYS
```

In the et_EE.UTF-8 locale:

```
$ env LC_ALL=et_EE.utf8 fish -d1
$ __fish_make_completion_signals
$ echo "$__kill_signals"
1 H UP      2 IN T      3 Q UIT     4 ILL 5 TRAP     6 ABR T     7 B US 8 FPE 9 KILL 10 USR1 11 SEGV    12 USR2 13 PIPE    14 ALRM 15 TERM    16 S TKFLT  17 CHLD 18 CON T    19 S TOP    20 TSTP    21 TTIN 22 TTOU    23 URG     24 XCPU    25 XFSZ    26 VTALRM  27 PROF 28 WINCH 29 POLL 30 P WR     31 S YS
```

Those are actual spaces in some of the signal names (not tabs or weird unicode chars). Those spaces cause the `complete -c pkill` commands in the *pkill.fish* completion script to have bogus values. For example,

```
$ echo "#$__kill_signals[1]#"
#1 H#
$ echo "#$__kill_signals[2]#"
#UP      2 IN#
$ echo "#$__kill_signals[3]#"
#T      3 Q#
$ echo "#$__kill_signals[4]#"
#UIT     4 ILL#
```

**Comment by krader1961** [comment]
One step closer to solving this. This command from *__fish_make_completion_signals.fish*

```
kill -L | sed -e 's/\([0-9][0-9]*\)  *\([A-Z,0-9][A-Z,0-9]*\)/\1 \2\n/g;s/ +/ /g'
```

produces completely bogus output in the et_EE.UTF-8 locale.

**Comment by krader1961** [comment]
The broken locale is really weird. Step one, collapse all the whitespace:

```
$ kill -L | sed -e 's/^ //; s/  */ /g'
1 HUP 2 INT 3 QUIT 4 ILL 5 TRAP 6 ABRT 7 BUS
8 FPE 9 KILL 10 USR1 11 SEGV 12 USR2 13 PIPE 14 ALRM
15 TERM 16 STKFLT 17 CHLD 18 CONT 19 STOP 20 TSTP 21 TTIN
22 TTOU 23 URG 24 XCPU 25 XFSZ 26 VTALRM 27 PROF 28 WINCH
29 POLL 30 PWR 31 SYS
```

Looks perfectly reasonable. Now split the signo signame pairs by inserting newlines:

```
$ kill -L | sed -e 's/^ //; s/  */ /g; s/\([0-9][0-9]* [A-Z][A-Z0-9]*\) /\1\n/g'
1 HUP 2 INT 3 QUIT 4 ILL
5 TRAP 6 ABRT 7 BUS
8 FPE
9 KILL
10 USR1 11 SEGV 12 USR2 13 PIPE
14 ALRM
15 TERM 16 STKFLT 17 CHLD
18 CONT 19 STOP 20 TSTP 21 TTIN
22 TTOU 23 URG 24 XCPU 25 XFSZ 26 VTALRM 27 PROF
28 WINCH
29 POLL
30 PWR 31 SYS
```

Whoa! In the C locale (or en_US.UTF-8) each word pair is printed on a separate line. There is some really weird character classification being done in the et_EE.UTF-8 locale. Running the output through `od -tx1z` shows just ASCII chars -- no funky unicode.

**Comment by krader1961** [comment]
I also noticed while investigating this that the GNU kill command installed on OS X by Homebrew supports `kill -L` but the output is incompatible with the *__fish_make_completion_signals.fish* script. So deal with that as well when fixing the original problem.

**Comment by floam** [comment]
That will be `gkill` if one installs from Homebrew.

**Comment by floam** [comment]
(I think we can assume there aren't very many folks on BSD installing GNU utilities and manually placing them unprefixed in their $PATH or on Linux doing vice-versa - that's a pain and they should expect all kinds of thing to break.)

**Comment by krader1961** [comment]
You're missing the point, @floam. There are GNU versions of kill that aren't compatible with our script. Are you confident that version of the command will never appear on a Linux distro? And if so how did you determine that?

**Comment by floam** [comment]
Maybe I misunderstand. Installing the gnu utilities doesn't mess up the script for me. I assumed you wanted to use `gkill -L` instead of falling back to `kill -l`when `kill -L` fails.

**Comment by floam** [comment]
I looked into this a bit, FYI there are a couple kinds of output you can expect on Linux with `kill -L` and like 3 or 4 `kill` utilities at least.: procps and util-linux support ` -L` for a table. That looks like:
```
1 HUP      2 INT      3 QUIT     4 ILL      5 TRAP     6 ABRT     7 BUS
 8 FPE      9 KILL    10 USR1    11 SEGV    12 USR2    13 PIPE    14 ALRM
15 TERM    16 STKFLT  17 CHLD    18 CONT    19 STOP    20 TSTP    21 TTIN
22 TTOU    23 URG     24 XCPU    25 XFSZ    26 VTALRM  27 PROF    28 WINCH
29 POLL    30 PWR     31 SYS
```
However coreutils `kill -L` looks like:
```
 1 HUP    Hangup: 1
 2 INT    Interrupt: 2
 3 QUIT   Quit: 3
 4 ILL    Illegal instruction: 4
 5 TRAP   Trace/BPT trap: 5
 6 ABRT   Abort trap: 6
 7 EMT    EMT trap: 7
 8 FPE    Floating point exception: 8
 9 KILL   Killed: 9
10 BUS    Bus error: 10
11 SEGV   Segmentation fault: 11
12 SYS    Bad system call: 12
13 PIPE   Broken pipe: 13
14 ALRM   Alarm clock: 14
15 TERM   Terminated: 15
16 URG    Urgent I/O condition: 16
17 STOP   Suspended (signal): 17
18 TSTP   Suspended: 18
19 CONT   Continued: 19
20 CHLD   Child exited: 20
21 TTIN   Stopped (tty input): 21
22 TTOU   Stopped (tty output): 22
23 IO     I/O possible: 23
24 XCPU   Cputime limit exceeded: 24
25 XFSZ   Filesize limit exceeded: 25
26 VTALRM Virtual timer expired: 26
27 PROF   Profiling timer expired: 27
28 WINCH  Window size changes: 28
29 INFO   Information request: 29
30 USR1   User defined signal 1: 30
31 USR2   User defined signal 2: 31
```

Coreutils does not document `-L`. The source code has a comment where they make it do the same thing as their `-t` saying it's there for procps compatibility. It seems likely to just cause problems though. Maybe we should check the usage information output instead of exit code upon trying `-L`.

**Comment by krader1961** [comment]
> or try -t

I like that better than what I was going to do which was

```
if kill -L ^/dev/null >/dev/null
and not kill -L | __fish_sgrep -iq 'hangup:'
```

**Comment by krader1961** [comment]
The `assert()` failure is because the *pkill.fish* completions script was running

```
complete -c pkill -o '' -d ''
```

in the problematic locale due to the screwed up behavior of `__fish_make_completion_signals`. If you run that complete command any locale the assert fires. That should be more intelligently handled by the builtin `complete` argument parser.

**Comment by floam** [comment]
I'll also notice that BSD sed and GNU sed will cause the coreutils output to render differently here:
`gkill -L | sed -e 's/^ //; s/  */ /g; s/\([0-9][0-9]* [A-Z][A-Z0-9]*\) /\1\n/g'` 
vs.
`gkill -L | gsed -e 's/^ //; s/  */ /g; s/\([0-9][0-9]* [A-Z][A-Z0-9]*\) /\1\n/g'
So I'd suggest that whatever is done uses `string match`.

**Comment by krader1961** [comment]
Yes, I also noticed the difference in sed behavior. Most notably you can't use `\n` in a sed substitute (`s/x/\n/`)' on BSD. So I replaced that with the sed transliterate (`y/x/\n/`) command which does allow that on both platforms. Interestingly I haven't done `brew install gnu-sed` on my OS X systems but did do `brew install coreutils`. I didn't create any symlinks but did add */usr/local/opt/coreutils/libexec/gnubin* to the start of my `$PATH`.

These types of issues really argue for more builtin fish functionality despite that being anathema to the original ethos of the project.
