### ISSUE TITLE
Problem with autocomplete function

### ISSUE THREAD

**Issue by suspiciousfellow** [fish-shell/fish-shell#3133]
[Please include a short description of the problem here]

### Reproduction Steps:

1. Create Directory /Volumes/Projects (on Box)/Live Projects/
2. cd to /
3. Start autocompleting a cd to said directory

### Expected behavior:

Autocomplete works normally

### Observed behavior:

On autocompletng to Live Projects get the following error:

➤ cd Volumes/Projects\ \(on\ Box\)/Lifish: Unknown command 'on'
- (line 1): on Box
            ^
in command substitution
	called on line -1 of file -

from sourcing file -
	called on line 60 of file /usr/local/share/fish/functions/eval.fish

in function 'eval'
	called on line 45 of file /usr/local/share/fish/functions/__fish_complete_cd.fish

in function '__fish_complete_cd'
	called on standard input

in command substitution
	called on standard input

### Additional information:

Doubt it's relevant, but in the actual example here the directory is mounted  

---
Fish version: 2.2.0
Operating system: Mac OS X, installed through Brew

Terminal or terminal emulator: OSX Terminal

**Comment by faho** [comment]
You'll want to upgrade to 2.3.0, this is #952, which is fixed there.
