### ISSUE TITLE
fishshell.com release notes need updating for 2.3.0

### ISSUE THREAD

**Issue by alphapapa** [fish-shell/fish-shell#3135]
The release notes on fishshell.com haven't been updated for 2.3.0 yet.  Also it lists the release date for 2.3.0 as being in April, which is when the first beta was released.  :)

**Comment by ridiculousfish** [comment]
D'oh! Bad merge from the fish-site repo I think. Thanks for noticing.

**Comment by ridiculousfish** [comment]
Fix is live. Thanks for reporting this.
