### ISSUE TITLE
fish_config doesn't work in fish.app

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#3140]
The fish 2.3.0 OS X application (fish.app) doesn't correctly support fish_config.

```
> fish_config
The __fish_bin_dir environment variable is not set. Looking in $PATH...
fish could not be found. Is fish installed correctly?
```

(It works if you have fish installed with Homebrew or the installer, which is probably why we haven't noticed in the past!)

**Comment by floam** [comment]
I get that output but it does launch the web browser.

**Comment by floam** [comment]
I noticed what looks to be an issue with spaces in the fish.app name (after downloading it a second time, I had a "fish 2.app":

```
2.app/Contents/Resources/base/share/fish/tools/web_config/webconfig.py: No such file or directory
$ 
```

**Comment by floam** [comment]
#3170 was a hint. In https://github.com/fish-shell/fish-shell/blob/master/src/fish.cpp#L125 we expect the path of the `fish` binary to have a suffix of "Contents/MacOS/fish"  - it fails completely as you can see with these by these debug statements:

```
<3> fish: /Users/floam/Library/Developer/Xcode/DerivedData/Build/Products/Debug/fish.app/Contents/Resources/base/bin/fish
<3> fish: paths.data is /
<3> fish: paths.sysconf is /
<3> fish: paths.doc is /
<3> fish: paths.bin is /
```

The doc and bin dirs get nuked in fish.cpp after they do not represent a valid path after appending `/` with "/share/fish", etc.

As you can see the binary is not in is not `Contents/MacOS` in the bundle -- we're execing `Resources/base/bin/fish` and that is where the fish binary is copied by the xcode project. That is an inappropriate spot for this executable, it belongs in MacOS alongside fish_launcher. I'm fixing this.

**Comment by floam** [comment]
Might have fixed this one in https://github.com/fish-shell/fish-shell/commit/63120a99629595a1d913b134235861d070e6a586. Can someone test?

**Comment by floam** [comment]
It's fixed. https://github.com/fish-shell/fish-shell/commit/3d8e8a871597b85262fdc9cc3c4bc46fc7ebd56a
