### ISSUE TITLE
Input redirection to cat fails with "Expected a string..."

### ISSUE THREAD

**Issue by Oogy** [fish-shell/fish-shell#3145]
When redirecting STDIN to cat, it fails with "Expected a string, but instead found a redirection". 

### Reproduction Steps:

1. [First Step]
`cat << anything`

### Expected behavior:

Should redirect input to cat until `anything` is recieved as input, at which point anything entered as input up to and including `anything` should be concatenated to output. 

### Observed behavior:

```
Expected a string, but instead found a redirection
fish: cat << anything
           ^
```

Fish version: `fish, version 2.3.0`

**Comment by floam** [comment]
Per the [docs](https://fishshell.com/docs/current/index.html#redirects):

> To read standard input from a file, write `<SOURCE_FILE`
> To write standard output to a file, write `>DESTINATION`
> To write standard error to a file, write `^DESTINATION`
> To append standard output to a file, write `>>DESTINATION_FILE`
> To append standard error to a file, write `^^DESTINATION_FILE`

Try `cat < anything`.

**Comment by Oogy** [comment]
anything in my case is not a file in the sense that I have a file named anything. I meant it as input from keyboard.
`cat << anything` 
`>some stuff`
`>some more stuff`
`>$(ls)`
`>anything` 

Should then output...

`some stuff`
`some more stuff`
`dir1/ dir2/ dirN/`
`anything`
 
and return to prompt.

**Comment by floam** [comment]
Ah,

This is #540. What exactly are you trying to do that this would make easier?

**Comment by Oogy** [comment]
Oops! Sorry I was unaware of the term, I tried searching issues for redirects and cat. But I just had to do this exact thing for part of an exercise in using redirects for a LinuxAcademy course I am taking.

**Comment by floam** [comment]
No problem, I'm going to close this if you're good to go.
