### ISSUE TITLE
Side effect of `__fish_cancel_commandline` implementation

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#3156]
[__fish_cancel_commandline.fish#L10-L11](https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_cancel_commandline.fish#L10-L11)

When hitting `CTRL-C` to abort/clear the current command, *"clear to EOL (to erase autosuggestion)"* clears **everything** after the cursor, not just autosuggestions.

### Reproduction Steps:

- Enter a command:
```
$ ls /usr/local/bin/git
  ^~~~~~~~~~~~~^         <-- typed text
               |         <-- cursor
                ^~~~~~^  <-- autosuggestion
```
- Move cursor back a few characters:
```
$ ls /usr/local/bin/git
  ^~~~~~~~~~~~~^         <-- typed text
          |              <-- cursor
                ^~~~~~^  <-- autosuggestion
```
- Hit `CTRL-C`

### Expected behavior:

How `bash` handles it (i.e. typed text after the cursor is not erased):
```
$ ls /usr/^Ccal/
  ^~~~~~~~~~~~~^         <-- typed text
          |              <-- cursor
                ^~~~~~^  <-- autosuggestion
```

### Observed behavior:

How `fish` handles it  (i.e. typed text after the cursor is erased):
```
$ ls /usr/^C
  ^~~~~~~~~~~~~^         <-- typed text
          |              <-- cursor
                ^~~~~~^  <-- autosuggestion
```

**Comment by krader1961** [comment]
That change was made by @ridiculousfish with commit b064da8d having this comment:

> Erase the autosuggestion in fish_cancel_commandline by clearing to EOL

My original change to implement the new ^C behavior didn't do that (i.e., it acted like bash). Both behaviors can be justified. It's not obvious that one is preferable to the other.

**Comment by zx8** [comment]
Right, I see. However, neither of the implementations are quite what I'm suggesting here.

If you check the Expected example, I'm suggesting that the autosuggestion should be suppressed (as @ridiculousfish's change does), while leaving any text that the user has actually typed/accepted intact (as your implementation does) - it's a middle ground between the two.

**Comment by krader1961** [comment]
That behavior is impossible at this time due to how `commandline -f` works (the function isn't run until the bound function returns). I've proposed changing the behavior to execute the function immediately but it's unclear if that will ever be done.
