### ISSUE TITLE
Document how to erase/delete a variable from $PATH - $fish_user_paths

### ISSUE THREAD

**Issue by ElijahLynn** [fish-shell/fish-shell#3161]
I wrote up some [documentation](http://superuser.com/questions/776008/how-to-remove-path-from-path-variable-in-fish/1091983#1091983) for how to erase a $PATH entry, now it just needs to be made into a PR and nursed along until merge. Easy task for someone who is looking to contribute. The code to modify is here https://github.com/fish-shell/fish-shell/blob/master/doc_src/tutorial.hdr#L530.

**Comment by krader1961** [comment]
From a recent update to duplicate issue #2639:

> Since this issue shows up high on Google but doesn't yield a clear answer, here's a link to a directly applicable solution:
>
> http://superuser.com/questions/776008/how-to-remove-a-path-from-path-variable-in-fish/1091983#1091983?newreg=73ef956cba5a413aa6f2d21a85d88f5f
