### ISSUE TITLE
disallow and complain about binding `\c\cX` sequences

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3162]
I've seen a couple of instances of people asking why `bind \c\n` (i.e., binding [ctrl-enter]) doesn't work. The answer is that binding [ctrl-enter] doesn't make any sense. The [enter] key normally sends a carriage-return; \r, aka \cM. In other words, [enter] is already a control character. So applying the \c modifier doesn't make any sense. It's equivalent to `bind \c\cJ` or `bind \c\cM`. Depending on whether you're talking about fish <= 2.2.0 or >= 2.3.0 respectively.

So we should modify the code to disallow people trying to apply the `\c` (control) modifier to a a control character.

P.S., The most recent instance of this was on [superuser.com](http://superuser.com/questions/1056536/ctrl-enter-for-fish-shell/). I also saw the same question on stackexchange.com recently (I don't know if it was from the same person).

**Comment by faho** [comment]
Fixed by #10359
