### ISSUE TITLE
set_color normal in Terminal.app on OSX causes other colored characters to appear lighter

### ISSUE THREAD

**Issue by wyqydsyq** [fish-shell/fish-shell#3163]
I'm trying to customize my fish prompt using some powerline-style characters which involves swapping the foreground and background colours to alternate the arrow segments.

The issue I'm experiencing is when I use:
```
    set_color -b $altColor
    set_color $current_bg
    echo -n "$segment_separator"
    set_color -b normal
    set_color $altColor
    echo -n "$segment_separator "
```

Which is meant to set the background to the normal terminal one, set the foreground to the primary colour, and echo the separator in $primaryColor. For some reason when I set the background to normal, following characters appear lighter (possibly an issue with Terminal.app's background transparency, but making it 100% opaque didn't help). You can see this below:

![image](https://cloud.githubusercontent.com/assets/621277/16291587/e6663c96-394b-11e6-86e4-2e921f696b11.png)

The tip of the arrow at the end should be the same colour as the background of the one before it, but it's lighter despite it's foreground colour being exactly the same as the background colour of the previous character.

If I change the background to anything other than normal, it behaves as expected:
![image](https://cloud.githubusercontent.com/assets/621277/16291597/0584598c-394c-11e6-8070-8b795cac81a1.png)

But of cause that means that arrow tip has a background that doesn't match the rest of the terminal which is what I'm trying to achieve.

This bug is immediately visible if you try to use the Oh My Fish theme "Agnoster" on Terminal.app.

It seems this is specific to Terminal.app, so I could get around it by using something like iTerm instead but this is the only issue I've ran across using fish in Terminal.app, and since I use tmux using something like iTerm would be overkill to just get `set_colour -b normal` behaving.

---
Fish version: 2.3.0

Operating system: Mac OSX El Capitan

Terminal or terminal emulator: Terminal.App

**Comment by krader1961** [comment]
What are the values for the variables in your example?

**Comment by wyqydsyq** [comment]
In my example I've got:

```
set primaryColor 268BD2
set altColor 186aa3
```

As the variables, however this behaviour also occurs with named colours:

```
set primaryColor green
set altColor blue
```
![image](https://cloud.githubusercontent.com/assets/621277/16292259/0efd31c6-3953-11e6-99e1-0ecf188f6a15.png)

**Comment by krader1961** [comment]
You did not include the value for `$current_bg` or `$segment_separator`. The former is probably the source of your issue. How did you determine that `$current_bg` matches the RGB value of the background used by your terminal? That is, how did you determint that `set_color $current_bg` matches your terminal's background color?

**Comment by krader1961** [comment]
I should clarify my previous response. In general there is no way for fish (or any other shell) to know your terminal's background color. So the result of `set_color -b normal` is unknown to fish. When you attempt to use an explicit "background" color as the current foreground color for the subsequent text it is only going to match the actual background color by accident.

**Comment by Darkshadow2** [comment]
It's a bug in Terminal.app, and happens for _any_ color. Basically, it renders colors differently based on if they have a background color set or not. The way to fix your prompt is to edit it to have it set the background to a color that matches your terminal background color instead of using normal.

You can see this in action if you do this (this assumes your background color is black):
```echo (set_color -o red) Hello (set_color -b black -o red) Hello (set_color normal)```

The first 'Hello' will noticeably be a different color than the second one.

**Comment by wyqydsyq** [comment]
@krader1961  I'm on my Linux machine at the moment, will check the other of the variables when I'm on the Mac again but I've provided what I think they were by memory.

$current_bg is just to track whether it's got the colours alternated or not, $segment_separator is whatever unicode character the powerline patched fonts use for the arrow character seen in the screenshots

@Darkshadow2 I tried matching my terminal background but due to fish approximating hex values to the nearest colour it can produce it was pretty far off the solarized background colour. If it's actually a bug in Terminal.app as you say I guess I'll just have to use an alternative.

**Comment by krader1961** [comment]
> $current_bg is just to track whether it's got the colours alternated or not,

That's not what your original problem statement shows. It shows the value being passed to `set_color` to be used as the foreground color for `$segment_separator`. If that doesn't exactly match the default background color of the terminal you'll see the sort of perceptual shift you're reporting.

Also, fish recognizes iTerm.app as being able to handle 24-bit colors whereas Terminal.app can not. So `echo $fish_term24bit` in the former should output "1" and nothing in the latter. That will also affect how the colors are rendered in Terminal.app since the color value might be rounded to the nearest 1 of 256 colors it supports.

**Comment by Darkshadow2** [comment]
@krader1961 It's not a problem with setting the color, it's entirely a problem with Terminal.app. He even wrote that it was specific to Terminal.app in the OP.

I wrote my own powerline prompt, and I see this in Terminal.app too. Problem will go away if you set a background color for the last separator, but that only works well if fish can match your background color.  Here's two pics to show it, first is Terminal.app, second is iTerm. Same exact prompt functions being used in both.

![screen shot 2016-06-24 at 11 51 21 am](https://cloud.githubusercontent.com/assets/896142/16343099/4d422e2c-3a03-11e6-9953-056f07d69f7f.png)

![screen shot 2016-06-24 at 11 53 11 am](https://cloud.githubusercontent.com/assets/896142/16343107/53f493c2-3a03-11e6-8faf-7e324e74a39e.png)

I moved to using iTerm, so I took out setting the background color for the last separator. In Terminal.app you can see how they are lighter than the preceding background, although they are the same exact color. Terminal.app just has a strange way of rendering colors.

**Comment by floam** [comment]
Indeed, I am guessing this is a side effect of some kind of tweak
Terminal.app is doing to attempt to improve contrast in certain situations
and/or improve the overall appearance of the color rendered by taking into
account the background color and the fact most users can't really control
them (and can only be as specific as picking from 256 of 'em). Those are
different colors.

**Comment by krader1961** [comment]
Closing since there doesn't seem to be anything fish can do about this.
