### ISSUE TITLE
scp to fish throws 'Could not set up terminal'

### ISSUE THREAD

**Issue by dmos62** [fish-shell/fish-shell#3165]
scp doesn't seem to work, both machines use fish. Tried running in and outside tmux.

#### Reproduction Steps:

1. `scp remote-host:remote-file .` (remote host uses fish)

#### Expected behavior:

Download of file.

#### Observed behavior:
```
fish: Could not set up terminal
fish: src/env.cpp:915: const wchar_t* env_var_t::c_str() const: Assertion `! is_missing' failed.
```
#### Additional information:

I'm on a fairly barebones void linux install and have been getting a lot of funny hiccups because of commonly assumed programs not being installed, though this looks like a problem with fish. 

---
Fish version: 2.3.0

Operating system: Void Linux (musl)

Terminal or terminal emulator: tmux and st.

**Comment by krader1961** [comment]
Known issue. Already fixed by commit ecf4517ffebad625ab0b8879a46637eb0739a8ce that's in the git master branch and the 2.3.1 release branch.
