### ISSUE TITLE
fish's `timef()` function should kill the program if `gettimeofday()` fails

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3167]
The current behavior of `timef()` dates back to at least commit 14c84ffb made in 2009-02-23 (I couldn't be bothered to trace it back farther than that). Returning NaN is silly. It is a can't happen, the computer is on fire, situation if `gettimeofday()` fails in that function. If that does happen `timef()` should kill the process.

This came to my attention when @floam made some changes to the *fish_key_reader.cpp* source. Note that there isn't a single place in the fish source code, other than @floam's recent change, that calls `isnan()`.

**Comment by floam** [comment]
I'll note here that [my checking](https://github.com/fish-shell/fish-shell/blob/0d6bdb38e62ec434cf9ee861e66428370c96bd5a/src/fish_key_reader.cpp#L121) for a NaN here isn't for the `timef()/gettimeofday() failure` - it's what I initialized the value to and check it after I've done some math involving that variable. It's nan() on the first loop through (or when gettimeofday() fails! Hate it when that happens!).

nan was certainly used so there would not need to be checks in the code - it's "safe" to do math on and toss into a `printf()` - `timef()` is basically only used for debuggey output like `fish -p`.
