### ISSUE TITLE
Using the output of a command as input for another command does not work

### ISSUE THREAD

**Issue by flavius** [fish-shell/fish-shell#3171]
### Reproduction Steps:

1. ```pacman -Qo `which ip` ```

### Expected behavior:

Output: ```/usr/bin/ip is owned by iproute2 4.5.0-2```

### Observed behavior:
```
error: failed to find '`which' in PATH: No such file or directory
error: failed to find 'ip`' in PATH: No such file or directory
```

---
Fish version: 2.3.0

Operating system: ArchLinux

Terminal or terminal emulator: [ROXTerm

**Comment by faho** [comment]
Fish does not use the backtick syntax (and it's not recommended in bash either, in favor of `$()`).

Use parentheses, like `pacman -Qo (which ip)`.

**Comment by zanchey** [comment]
@flavius, did that solve your problem? I agree with @faho's answer (and it's in the [FAQ](https://fishshell.com/docs/current/faq.html#faq-subcommand)) so I'm going to close this for now, but if it's not working please speak up.
