### ISSUE TITLE
The taskwarrior autocomplete is incomplete

### ISSUE THREAD

**Issue by marmistrz** [fish-shell/fish-shell#3179]
When autocompleting this command:

```
task config urgency.user.project.Home.coefficient
```

I hit tab at 

```
task config urgency.user.
```

and what I get is `tag.next.coefficient`
After the first time the project was autocompleted, it shows up.

**Comment by krader1961** [comment]
Fish doesn't ship with any custom completions for taskwarrior (whatever that is). So you're only going to get the default filename completions. We welcome new completions so if you care to take a stab at writing one that would be great.

**Comment by faho** [comment]
>So you're only going to get the default filename completions.

Either that or the completions generated from the man page. Which won't be complete for something of this complexity.

**Comment by krader1961** [comment]
Custom completions need to be written and submitted by someone motivated to do so. Like yourself, @marmistrz. We're happy to provide advice on how to do so. But without such a submission this issue will simply bit rot.
