### ISSUE TITLE
setting `TZ` doesn't change fish's idea of localtime

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3181]
While reviewing PR #3175 (add option to print history timestamps) I noticed that nowhere does fish call `tzset()`. I doctored one of the builtin commands to call and print the result of `localtime_r()` and `localtime()`. Not surprisingly, setting `TZ` then running that doctored builtin shows no effect on fish's idea of the local timezone. We should augment the code to handle `TZ` in a manner analogous to `TERM` and the locale env vars since it should be possible to change the timezone on the fly.

**Comment by bbarenblat** [comment]
This surprises me. POSIX [specifies](http://pubs.opengroup.org/onlinepubs/9699919799/functions/localtime.html) that ‘Local timezone information is used as though _localtime_() calls _tzset_()’, so `TZ` should affect `localtime`. What OS did you observe this behaviour on?

**Comment by krader1961** [comment]
The `localtime_r()` function never calls `tzset()`. Only `localtime()` calls `tzset()` and only if it hasn't already been called. Which means that if **TZ** is modified after the initial call to `tzset()` it won't affect subsequent calls to `localtime()` unless `tzset()` is explicitly called.
