### ISSUE TITLE
enhance fish_key_reader to emit a `bind` command that can be copy/pasted

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3183]
There have been multiple requests to enhance the `fish_key_reader` command to emit a `bind` command that can be copy/pasted as the basis for a key binding in response to pressing a key or sequence of keys. This issue will track implementing that feature.

I also did some testing that shows that fish depends on the `input_common_readch()` function decoding multi-byte sequences into a single wide char. In other words, you can't actually bind the sequence of individual bytes that comprise a non-ASCII wide char. So `fish_key_reader` should not override the user's locale by forcing the use of the C/POSIX locale. It's unlikely that anyone will notice the current behavior is incompatible with `fish` because it is unlikely that any fish users are binding sequences of non-ASCII chars. Nonetheless, the fish_key_reader program should deal with such occurrences in a manner analogous to fish.

----
For 2.3.1:
- [x] Document "bind" command synthesis in user docs
- [x] Update release notes

**Comment by floam** [comment]
Generation of the "bind" command is not documented, it should be.

**Comment by floam** [comment]
I updated the manpage to document the `bind` command feature and the commands that currently work and trimmed some fat from the word count.
