### ISSUE TITLE
Add custom fish keybindings

### ISSUE THREAD

**Issue by Alaya-in-Matrix** [fish-shell/fish-shell#3186]
I am new to fish(just switch from bash this morning...) and I want to use `Ctrl + L` to clear my screen. 

So I added `~/.config/fish/functions/fish_user_key_bindings.fish`:

```fish
function fish_user_key_bindings
    echo test keybinding
    bind -M insert \cl 'clear; commandline -f repaint'
end
```

However,  after terminal is lunched, the "test keybinding" message was not printed, also, the new keybinding is not added.

Then, if I manually run `source ~/.config/fish/config.fish`, The new keybinding is still not added and I got the following error message:

```
functions: Function “__original_fish_user_key_bindings” already exists. Cannot create copy “fish_user_key_bindings”
~/.local/share/omf/init.fish (line 26):   and functions -c fish_user_key_bindings __original_fish_user_key_bindings
                                          ^
from sourcing file ~/.local/share/omf/init.fish
	called on line 10 of file ~/.config/fish//config.fish

from sourcing file ~/.config/fish//config.fish
	called on standard input


       functions -- print or erase functions

   Synopsis
       functions [ -a | --all ] [ -n | --names ]
       functions -c OLDNAME NEWNAME
       functions -d DESCRIPTION FUNCTION
       functions [ -e | -q ] FUNCTIONS...

functions: Type “help functions” for related documentation
```

Finally I can add the keybinding by manually run `fish_user_key_bindings` on the terminal

Could anybody please tell me what did I do wrong, why wasn't the new keybinding autoloaded?

The system I am using is Ubuntu 16.04

**Comment by siteshwar** [comment]
It looks like you are using oh-my-fish which has defined the ```fish_user_key_bindings``` function. This is not an issue with fish-shell itself and you may want to follow up this issue on https://github.com/oh-my-fish/oh-my-fish

**Comment by ridiculousfish** [comment]
siteshwar! 💯

**Comment by derekstavis** [comment]
In fact it's an issue in Oh My Fish. We're backing up the original key bindings and overriding it so we can load packages and themes key bindings. I will make and test a quick fix for the issue. Thanks @siteshwar for pointing the direction 👍

**Comment by floam** [comment]
OK.  I'll close this one up once it's fixed there.
