### ISSUE TITLE
fish_indent on empty file hangs

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#3188]
Given an empty file to reindent, `fish_indent` gets stuck.

### Reproduction Steps:

1. `> touch foo.fish`
2. `> fish_indent foo.fish`

### Expected behavior:

1. `fish_indent` would print nothing or print a newline and then exit.

### Observed behavior:

It sits there.

**Comment by krader1961** [comment]
I can't reproduce this problem on OS X El Capitan or Ubuntu 16.04 using fish from git head. Both `fish_indent foo.fish` and `fish_indent <foo.fish` exit immediately without producing any output. On what platform did you observe the hang? Can you use dtruss or strace to provide some insight into why it is not exiting?

**Comment by floam** [comment]
This is happening in Integration_2.30 and not `master`, with empty files and non-empty files. It seems I didn't realize fish_indent in Integration is not accepting paths to a file to indent.

**Comment by krader1961** [comment]
I'm going to close this since this is a problem that exists in the 2.3.0 release. That version of `fish_indent` only reads from stdin. It does not handle script file names on the command line. This has been fixed (i.e., improved) in subsequent versions with the addition of the `-w` flag.

**Comment by floam** [comment]
Yeah, nothing to see here. newer fish_inden

**Comment by floam** [comment]
Whoops. We both hit that at same time. Closed.

**Comment by floam** [comment]
This was just me getting too accustomed to the nicer fish_indent in master and thinking that it has always done supported taking a path. This is invalid or perhaps a duplicate of #3037.
