### ISSUE TITLE
Windows port?

### ISSUE THREAD

**Issue by mcandre** [fish-shell/fish-shell#319]
Any interest in making Fish available on Windows as a stand-alone terminal window?

**Comment by bucaran** [comment]
Does fish run on Windows?

**Comment by tomByrer** [comment]
@bucaran, for my fresh Cygwin installation, `Cygwin.bat` looked like this:
```bash
@echo off

C:
chdir C:\p\s\cygwin\bin

bash --login -i
```
I simply changed `bash` to `fish`.
