### ISSUE TITLE
Redirecting with tee

### ISSUE THREAD

**Issue by luolong** [fish-shell/fish-shell#3190]
Today I wanted to run some program several time storing one particular line of output of the program to a file.

It was relatively easy with something like this:
```shell
$ for x in (seq 10)
      echo $x
      myprogram | grep "Total time" >> stats.txt
end
```

But since the program ran for fairly long time, I wanted to be able to see the output.

in bash, I would have called the `tee` like this:
```shell
      myprogram | tee >(grep "Total time" >> stats.txt)
```

But fish shell complained:
> Invalid redirection target: (grep "Total time" >> stats.txt)

It is possible I am doing something wrong, but at least in case of bash, the same redirection seems to be working like a charm...

Here's a minimal test case:
```fish
> for x in (seq 500); echo $x >> source.txt; end
> cat source.txt | tee >(grep 450 > 450.txt)
Invalid redirection target: (grep 450 > 450.txt)
fish: cat source.txt | tee >(grep 450 > 450.txt)
                           ^
```

I would have expected this snippet to print out all 500 lines from `source.txt` to stdout and written a file `450.txt` with one line containing `450` in it.

**Comment by krader1961** [comment]
Fish is not bash (or zsh, to state the obvious). Specifically, fish is only partially POSIX compliant. The first thing to note is that in fish `(a_command)` is how you capture the output of a command. In bash that would be written `$(a_command)`.  So even if fish allowed it what you're trying to do is use the output of `grep 450 >450.txt` as the place to redirect the stdout of tee to. And that doesn't make any sense since you redirected the output of grep so the `(...)` output will be empty which means you're trying to `... tee >` with nothing following the redirect symbol.

The way I would do it is like this:

```
myprogram | tee /dev/tty | grep "Total time" >> stats.txt
```

**Comment by zanchey** [comment]
It looks to me like @luolong is trying to use process substitution for output (the `>()` construct), but unfortunately fish only has process substitution for input (see #1786).

**Comment by krader1961** [comment]
> It looks to me like @luolong is trying to use process substitution for output

Agreed. And it's an overly complicated, hard to understand, way of achieving their goal in this specific use case. In fact, it is counterintuitive. The `tee` command copies its input to the named files and stdout. But at first glance you're ostensibly redirecting tee's stdout to the stdin of another command and didn't name any other files to "tee" the output into. So why does that result in the output also going to /dev/tty? The answer, of course, is that the construct `>()` does not redirect stdout it replaces the construct with a synthesized file name so you're effectively doing something like `| tee /tmp/a_pipe_to_grep`. Which for anyone not familiar with this idiom is highly surprising.

We should not want to support the `>()` syntax. We might want to provide some other way of doing that but that particular syntax is too confusing to be something we want to adopt.

**Comment by luolong** [comment]
@krader1961 wrote:
> The way I would do it is like this:
>     `myprogram | tee /dev/tty | grep "Total time" >> stats.txt`

Thanks, this worked like a charm :)

I agree, that using `tee` in this manner is probably not the most intuitive task (as witnessed by my futile attempts at making this work). This seems to fall flatly in the realm of nontrivial use of terminal shell. I was simply cargo-culting exampled from the internet, most of them being bash scripts. My shell-scripting-fu is definitely not on that level yet.

I really love most of fish shell. The only constant irritation is that it is damned hard to find help for obscure features like this tee example here...

_By the way, I do not think that the `>()` syntax is all that confusing. Specially when using as an argument to `tee`. Seemed to make sense. Syntactically at least..._

Should I close this issue or should this be kept open as a platform for discussing possible alternative syntax for `>(grep foo)` syntax?

**Comment by krader1961** [comment]
The fish equivalent to what you were trying to do involves `psub` and it's being discussed in issue #1040 so closing this issue.
