### ISSUE TITLE
youtube-dl -F

### ISSUE THREAD

**Issue by simon1tan** [fish-shell/fish-shell#3192]
getting a parameter error:

"fish: youtube-dl -F https://www.youtube.com/watch?v=4zhpdQa_qbI
                    ^
Usage: youtube-dl [OPTIONS] URL [URL...]

youtube-dl: error: You must provide at least one URL.
Type youtube-dl --help to see a list of all options."

That same command works in bash.

**Comment by faho** [comment]
This is the same thing as #967 (and #2750).

The issue is that "?" is a single-character glob, so fish tries to match files in the local directory. The workaround is to quote the parameter - I always do youtube-dl " then press Ctrl-v, enter the second quote and then execute it.

**Comment by WillyWinkel** [comment]
but if I have a function like:
`function you-mp3`
`youtube-dl -x --audio-format mp3 -o "%(title)s.%(ext)s" "$argv"`
` end `

I still get the wildcard error. Is there a way to solve this?
