### ISSUE TITLE
fish_key_reader not in fish.app, Mac fish installer

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#3193]
This is an apparent oversight: After releasing fish 2.3.1, it was noticed that while `fish_key_reader` was assumed to be shipped in our packages, in reality the tool is neither in fish.app or our official OS X installer. Actually the xcode project did not get taught to build a fish_key_reader binary in the first place. Only the Makefile was addressed.

A `fish_key_reader` target needs to be created in the xcode project and and the `base` target needs to be modified to include it.

**Comment by ridiculousfish** [comment]
FYI key_reader was originally not intended to be part of the fish distribution - it's was envisioned as more of a development tool. Of course we can choose to ship it now if we please.

**Comment by floam** [comment]
There wasn't much discussion about this but it after improving it a bit @krader1961's intent was that it build by default and [be something we include with 2.3.1](https://github.com/fish-shell/fish-shell/issues/3106#issuecomment-229851934). 

Someday if we can provide a decent enough experience it could be nice for users wanting to configure their keybinds. It could probably just be a builtin `bind` option.

**Comment by krader1961** [comment]
Right. The problem with telling people to use `cat -vt`, `xxd`, or `od -tx1z` to figure out what a key sends is that the output is hard for non-programmers to deal with. With the latest improvements proposed by @faho (single-shot mode) and @floam (output a bind command which can be copy/pasted) that I implemented it's a much friendlier alternative.

**Comment by ridiculousfish** [comment]
Sounds great then.

I love floam's idea of tying this in with bind. "Type what you want to type" is definitely the right UI.

**Comment by krader1961** [comment]
@floam, Should this still be a blocking item for the fish 2.4.0 release? You recently retracted your pull-request to add it to the macOS xcode project configuration. Will you be able to submit a new change for review in the next two weeks? If not this should probably be retargeted to the `next-2.x` milestone.

**Comment by krader1961** [comment]
FWIW, I think there is more value in having you focus on issue #3353 to improve the `cd -` completion for the 2.4.0 release than working on this issue. Especially since it might make more sense to make the fkr program unnecessary by incorporating it into the builtin `bind` command.

P.S., I'm not convinced we can completely replace fkr with an enhanced bind builtin but it's an intriguing idea.

**Comment by krader1961** [comment]
I'd love to see this be fixed for the 2.4.0 release but there is no reason it should block that release so removing that milestone.

**Comment by krader1961** [comment]
This was fixed by commit 4ba1f9e3 (whose commit comment didn't mention this issue).
