### ISSUE TITLE
[i] Displays prior to prompt

### ISSUE THREAD

**Issue by alice-em** [fish-shell/fish-shell#3201]
- [x] Did you do [a quick search?](/issues?utf8=✓&q=is:issue+user:fish-shell)
- [x] Try [with the latest](/fish-shell/fish-shell/releases/tag/2.3.1) fish version? **both stable and nightly**

The problem is on `fish, version 2.3.1-356-ga8d911b
 & fish, 2.3.1` with *ubuntu 16.04* and **Oh-my-fish** installed.

## Reproduction steps
1. Launch fish

## Expected results
Fish should…
display without an `[I]` before the omf prompt

## Actual results
	`[I]  ⚓  ~ `

## Additonal Information
I don't know what exactly caused it, or whether or not `[I]` is a shell error message or not.

**Comment by floam** [comment]
That's the indicator you get when you are in vi mode (It's like vi - hit escape key and hit i or : or v, etc.) so you have vi mode on which is not the default. You probably want to go back to emacs mode.

**Comment by floam** [comment]
Since you seem surprised by it, it is not the default, and you are using OMF, I wonder if perhaps some prompt or plugin you are using has turned it on for you.

**Comment by nwoeanhinnogaehr** [comment]
I'm also seeing this behaviour after updating today on Arch Linux. I do not use oh-my-fish.

This may not be related, but it showed up at the same time: A ')' character is immediately typed after the prompt when fish starts. It needs to be deleted before I can use any commands.

```
[I] me@decim ~ (master)> )
```

**Comment by floam** [comment]
Can you show me the output of `set`?

**Comment by nwoeanhinnogaehr** [comment]
Oh, I should have mentioned, I am using vi keybindings, but was surprised because the mode didn't show before 2.3.1.

Anyway, I managed to get rid of it by doing this:
```
function fish_mode_prompt
end
```

**Comment by alice-em** [comment]
~ set
     
     CLUTTER_IM_MODULE xim
     CMD_DURATION 3
     COLUMNS 69
     COMPIZ_BIN_PATH /usr/bin/
     COMPIZ_CONFIG_PROFILE ubuntu
     DBUS_SESSION_BUS_ADDRESS unix:abstract=/tmp/dbus-cJzpwk56C1
     DEFAULTS_PATH /usr/share/gconf/ubuntu.default.path
     DESKTOP_SESSION ubuntu
     DISPLAY :0
     FISH_VERSION 2.3.1-356-ga8d911b
     GDMSESSION ubuntu
     GDM_LANG en_US
     GNOME_DESKTOP_SESSION_ID this-is-deprecated
     GNOME_KEYRING_CONTROL ''
     GNOME_KEYRING_PID ''
     GPG_AGENT_INFO /home/alicemod/.gnupg/S.gpg-agent:0:1
     GTK2_MODULES overlay-scrollbar
     GTK_IM_MODULE ibus
     GTK_MODULES gail:atk-bridge:unity-gtk-module
     HOME /home/alicemod
     IFS \n\ \t
     IM_CONFIG_PHASE 1
     INFINALITY_FT_AUTOHINT_HORIZONTAL_STEM_DARKEN_STRENGTH 10
     INFINALITY_FT_AUTOHINT_INCREASE_GLYPH_HEIGHTS true
     INFINALITY_FT_AUTOHINT_SNAP_STEM_HEIGHT 100
     INFINALITY_FT_AUTOHINT_VERTICAL_STEM_DARKEN_STRENGTH 25
     INFINALITY_FT_BOLD_EMBOLDEN_X_VALUE 0
     INFINALITY_FT_BOLD_EMBOLDEN_Y_VALUE 0
     INFINALITY_FT_BRIGHTNESS 0
     INFINALITY_FT_CHROMEOS_STYLE_SHARPENING_STRENGTH 0
     INFINALITY_FT_CONTRAST 0
     INFINALITY_FT_FILTER_PARAMS '11 22 38 22 11'
     INFINALITY_FT_FRINGE_FILTER_STRENGTH 0
     INFINALITY_FT_GAMMA_CORRECTION '0 100'
     INFINALITY_FT_GLOBAL_EMBOLDEN_X_VALUE 0
     INFINALITY_FT_GLOBAL_EMBOLDEN_Y_VALUE 0
     INFINALITY_FT_GRAYSCALE_FILTER_STRENGTH 0
     INFINALITY_FT_STEM_ALIGNMENT_STRENGTH 25
     INFINALITY_FT_STEM_FITTING_STRENGTH 25
     INFINALITY_FT_STEM_SNAPPING_SLIDING_SCALE 40
     INFINALITY_FT_USE_KNOWN_SETTINGS_ON_SELECTED_FONTS true
     INFINALITY_FT_USE_VARIOUS_TWEAKS true
     INFINALITY_FT_WINDOWS_STYLE_SHARPENING_STRENGTH 10
INSTANCE ''
     JOB unity-settings-daemon
     LANG en_US.UTF-8
     LANGUAGE en_US
     LIBVIRT_DEFAULT_URI qemu:///system
     LINES 26
     LOGNAME alicemod
     MANDATORY_PATH /usr/share/gconf/ubuntu.mandatory.path
     NODE_PATH /usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
     OMF_CONFIG /home/alicemod/.config/omf
     OMF_INVALID_ARG 3
     OMF_MISSING_ARG 1
     OMF_PATH /home/alicemod/.local/share/omf
     OMF_UNKNOWN_ERR 4
     OMF_UNKNOWN_OPT 2
     OMF_VERSION 2
     PATH '/home/alicemod/.nvm/versions/node/v6.2.1/bin'  '/home/alicemod/'…
     PWD /home/alicemod
     QT4_IM_MODULE xim
     QT_ACCESSIBILITY 1
     QT_IM_MODULE ibus
     QT_LINUX_ACCESSIBILITY_ALWAYS_ON 1
     QT_QPA_PLATFORMTHEME appmenu-qt5
     SESSION ubuntu
     SESSIONTYPE gnome-session
     SHELL /usr/bin/fish
     SHLVL 1
     SSH_AUTH_SOCK /run/user/1000/keyring/ssh
     TERM xterm-256color
     UPSTART_EVENTS 'xsession started'
     UPSTART_INSTANCE ''
     UPSTART_JOB unity7
     UPSTART_SESSION unix:abstract=/com/ubuntu/upstart-session/1000/2157
     USER alicemod
     VTE_VERSION 4205
     WINDOWID 58720262
     XAUTHORITY /home/alicemod/.Xauthority
     XDG_CONFIG_DIRS /etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg
     XDG_CURRENT_DESKTOP Unity
     XDG_DATA_DIRS /usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/sh…
     XDG_GREETER_DATA_DIR /var/lib/lightdm-data/alicemod
     XDG_RUNTIME_DIR /run/user/1000
     XDG_SEAT seat0
     XDG_SEAT_PATH /org/freedesktop/DisplayManager/Seat0
     XDG_SESSION_DESKTOP ubuntu
     XDG_SESSION_ID c2
     XDG_SESSION_PATH /org/freedesktop/DisplayManager/Session0
     XDG_SESSION_TYPE x11
     XDG_VTNR 7
     XMODIFIERS @im=ibus
     _ set
     __fish_active_key_bindings fish_vi_key_bindings
     __fish_added_user_paths /home/alicemod/.nvm/versions/node/v6.2.1/bin
     __fish_bin_dir /usr/bin
     __fish_config_interactive_done
     __fish_datadir /usr/share/fish
     __fish_help_dir /usr/share/doc/fish
     __fish_init_1_50_0
     __fish_init_2_3_0
     __fish_sysconfdir /etc/fish
     __oceanfish_glyph_anchor ⚓
     __oceanfish_glyph_flag ⚑
     __oceanfish_glyph_radioactive ☢
     budspencer_colors '000000'  '083743'  '445659'  'fdf6e3'  'b58900'  'cb4b16'  'dc121f'  'af005f'  '6c71'…
     budspencer_cursors '\033]12;#268bd2\007'  '\033]12;#b58900\007'  '\033]12;#af005f\007'  ''…
     budspencer_day '000000'  '333333'  '666666'  'ffffff'  'ffff00'  'ff6600'  'ff0000'  'ff0033'  '3300'…
     budspencer_night '000000'  '083743'  '445659'  'fdf6e3'  'b58900'  'cb4b16'  'dc121f'  'af005f'  '6c71'…
     budspencer_nocmdhist 'c'  'd'  'll'  'ls'  'm'  's'
     budspencer_pwdstyle 'short'  'long'  'none'
     budspencer_sessions_active
     budspencer_sessions_active_pid
     fish_bind_mode insert
     fish_color_autosuggestion '555'  'yellow'
     fish_color_command 5f87ff
     fish_color_comment red
     fish_color_cwd 00875f
     fish_color_cwd_root red
     fish_color_end bcbcbc
     fish_color_error 'red'  '--bold'
     fish_color_escape cyan
     fish_color_history_current cyan
     fish_color_host cyan
     fish_color_match cyan
     fish_color_normal 5f5f5f
     fish_color_operator cyan
     fish_color_param 5f87ff
     fish_color_quote brown
     fish_color_redirection normal
     fish_color_search_match --background=purple
     fish_color_selection --background=purple
     fish_color_user cyan
     fish_color_valid_path --underline
     fish_complete_path '/home/alicemod/.config/fish/completions'  '/home/alicemod/.loca'…
     fish_escape_delay_ms 100
     fish_function_path '/home/alicemod/.config/fish/functions'  '/home/alicemod/.local/'…
     fish_greeting Welcome\ to\ fish,\ the\ friendly\ interactive\ shell\nType\ \e\[32mhe…
     fish_key_bindings fish_vi_key_bindings
     fish_pager_color_completion normal
     fish_pager_color_description '555'  'yellow'
     fish_pager_color_prefix cyan
     fish_pager_color_progress cyan
     fish_term24bit 1
     fish_user_paths /home/alicemod/.nvm/versions/node/v6.2.1/bin
     history 'fish -v'  'gedit ~/.config/fish/config.fish '  'clear'  'fish'  'sudo ap'…
     omf_init_path /home/alicemod/.local/share/omf/pkg/omf
     status 0
     umask 0002

**Comment by floam** [comment]
@alice-em You are using the budspencer theme which only works in vi mode, so it forces it on.

> Oh, I should have mentioned, I am using vi keybindings, but was surprised because the mode didn't show before 2.3.1.

This is a change in 2.3.1: https://github.com/fish-shell/fish-shell/pull/2939. Are you merely surprised, or had you intentionally not used the mode prompt in 2.3.0 and unhappy it was enabled? Just curious.

**Comment by alice-em** [comment]
I didn't know what it was.  Visually, I'm not a fan, but I guess there is a way to remove it now.

**Comment by nwoeanhinnogaehr** [comment]
Yes, add that to your config.fish.

**Comment by alice-em** [comment]
Alrighty!  I'll test these out when I get home later tonight.  I'll confirm the solutions then.

**Comment by goocastro** [comment]
Same here.
Always used `fish_vi_key_bindings` but since last update a wild `[I]` appeared.

Applied the same solution to my `config.fish`:

    function fish_mode_prompt
    end

**Comment by zanchey** [comment]
There was a mode indicator in 2.2.0 and it disappeared in 2.3.0 accidentally! So we brought it back in 2.3.1.

**Comment by alice-em** [comment]
Oh fancy!   The `[I]` went away with @nwoeanhinnogaehr solution.

**Comment by jcelliott** [comment]
I was surprised by this as well. I'm not sure that modifying the user's prompt when they set their key bindings is the right behavior. Also, having to override the function to remove it from your prompt seems "unfriendly". Maybe we should have a variable `fish_vi_mode_prompt` (unset by default) that enables this behavior. Where is this called from anyway? I don't see it anywhere in `<install-dir>/share/`.

**Comment by abhigenie92** [comment]
After adding to the config file, it appears on the right.
```
function fish_mode_prompt
end
```

**Comment by faho** [comment]
@abhigenie92: Can you please open a new issue with a bit more description on your problem? This is about the mode prompt being enabled by default.

**Comment by yurighensev** [comment]
You might have enabled vi-mode by mistake. Emacs-mode is the default, just [do this to go back to it](https://fishshell.com/docs/current/interactive.html#emacs-mode-commands):
```sh
fish_default_key_bindings
```
