### ISSUE TITLE
ssh auto-completion broken for multi-pattern Hosts

### ISSUE THREAD

**Issue by Pyppe** [fish-shell/fish-shell#3202]
- [x] Did you do [a quick search?](/issues?utf8=✓&q=is:issue+user:fish-shell)
- [ ] Try [with the latest](/fish-shell/fish-shell/releases/tag/2.3.1) fish version?

**Version**: `fish, version 2.3.0`
**OS**: `Xubuntu 14.04 LTS`

#### Contents of `~/.ssh/config`:
```
Host foo bar xyzzy loremipsum
  Hostname %h.example.org
```
## Expected results
Fish should detect foo, bar, xyzzy, and loremipsum as separate hosts when using the auto-complete.

For example `ssh lore\<TAB>` should yield `ssh loremipsum` (or `ssh loremipsum.example.org`?).

## Actual results
`ssh lore\<TAB>` yields `ssh foo\ bar\ xyzzy\ loremipsum`.

**Comment by floam** [comment]
I can't reproduce this with master - your config file gives the expected output, and `__fish_print_hostnames` is splitting on " " which I assumed it must have needed to have added to it.

**Comment by floam** [comment]
This was fixed two weeks ago (#3146) and the fix is in 2.3.1. I think that should fix it for you when you can upgrade from 2.3.0.
