### ISSUE TITLE
Confusing completion behavior on similar nested folders.

### ISSUE THREAD

**Issue by lunixbochs** [fish-shell/fish-shell#3211]
- [x] Did you try [a quick search?](/issues?utf8=✓&q=is:issue+user:fish-shell)
- [x] Try [with the latest](/fish-shell/fish-shell/releases/tag/2.3.1) fish version?

Talk about the the issue here.

**fish verison installed**: 2.3.1
**OS/terminal used**: OS X / Terminal.app

## Reproduction steps

1. `mkdir -p at-dr2/asdf dr`
2. `cd dr/a<tab>`

## Expected results
Fish should not remove manually typed valid directories when performing completion. This should result in an error and no completion should occur.

## Actual results
	~ $ cd at-dr2/asdf/

**Comment by llwu** [comment]
I don't agree with the "no completion" verdict. Dropping a menu for fuzzy completions instead of automatically selecting them could be a good idea though (or allowing it to be configured).

**Comment by ridiculousfish** [comment]
I think it's reasonable to say, if there's an exact match of a path component, do not attempt fuzzy completion on that component even if we get no completions.

**Comment by ridiculousfish** [comment]
Fixed as c0c2e1d4fa5665637a35cc8319a5589231a20155 . Thanks for filing this!
