### ISSUE TITLE
When interactive programs are used as subcommands, they go to the background and are made unrecoverable

### ISSUE THREAD

**Issue by getkey** [fish-shell/fish-shell#3212]
Interactive programs in subcommands go to the background. Trying to bring them to foreground fails silently.

## Reproduction steps

```fish
> echo (top)

> jobs
Tâche	Groupe	CPU	État	Commande
2	4242	0%	arrêtée	top
> fg 4242
Mettre la tâche 2, 'top' en premier plan
> jobs
Tâche	Groupe	CPU	État	Commande
2	4242	0%	arrêtée	top

```

## Bash's behavior

Bash's behavior when doing `echo $(top)` is to block until the user sends a `^C`, which seems more logical to me since top is waiting for user input to quit. Which of course cannot happen because the user has no access to `top`'s stdin.

**fish version installed**: 2.3.1
**OS/terminal used**: gnome-terminal on Arch Linux

**Comment by faho** [comment]
This is the same thing as #1949, if you squint a bit. The root cause is that we are claiming stdin is a tty, while it's not _actually_ connected.

Sorry for the inconvenience.
