### ISSUE TITLE
Sudo breaks scripts that use "read" command to prompt users for input.

### ISSUE THREAD

**Issue by terrycloth** [fish-shell/fish-shell#3223]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
2.3.1

**OS/terminal used**: 
Fedora 24 (64-bit) / gnome-terminal 3.20.2

I've written a script that uses the `read` command to prompt the user for information. If I run the script as a normal user, or as root, it works as expected. But if I run the script with sudo, it throws an error message:

> fish: Couldn't grab control of terminal
> tcsetpgrp: Interrupted system call

...Which is similar to the original post in issue #1258, but possibly for different reasons? Running the script as root instead of via sudo is a workable, if maybe inconvenient workaround.

Here is a simple example script if you need to test:

``` fish
#!/usr/bin/fish
echo "Who are you?"
read -x  username
echo "Hello, $username!"
```

**Comment by faho** [comment]
>...Which is similar to the original post in issue #1258, but possibly for different reasons?

It seems similar enough to me that I'll close this one as a duplicate. Thanks!
