### ISSUE TITLE
`history` builtin doesn't complain about contradictory sub commands

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3224]
Recent changes to fix handling of the `-t` (`--with-time`) flag caused me to notice that the history command doesn't report an error if the user does something nonsensical such as ask for the history to be merged and searched in a single command. Since the implementation only performs one of the requested actions it should complain if the user asks for more than one action to be performed.

Those recent changes also changed the format of the search timestamp field without discussion so revert to the timestamp format that was agreed to before the original change was merged.

**Comment by floam** [comment]
It looks like I might have broken `history foo` - it's popping up a pager and not exactly searching for that. I was thinking after reading this issue that is another example of something that should be to made to give an argument error but I just checked fish 2.3.1 and it's equivalent to `history --search foo` and `history --search --contains foo` there. That is undocumented behavior though.

What is it that  *supposed* to do? 

I hope we don't want that to cause a search. Especially as the current usage is all over the map and not great, most would agree as it is. If someday we decide to improve `history` usage one thing we could possibly consider is `<command> [<args>] STRING` syntax (like `string match -r foo`) and it could be trivial to continue supporting existing documented search syntax in that situation, but not this fish 2.3.1 behavior.

**Comment by krader1961** [comment]
Searching (the `-s` or `--search` flag) is intended to be the default behavior if no other sub-command is specified. Similarly `--contains` is the default search behavior if `--prefix` wasn't given. The `history` wrapper function deliberately runs the output of the builtin through the user's pager if stdout is attached to a tty in order to provide "friendly" behavior. Those behaviors should be documented so I'll take care of that while fixing this issue. I also noticed there is a problem with the *history.txt* file: the `--delete` option isn't correctly formatted. Unit tests to prevent regressions will also be added.

Switching to the more typical `history sub-command [flags]` style syntax will be left for another day.

**Comment by krader1961** [comment]
The fix for this issue is going to be considerably larger than I anticipated for two reasons. First, the history builtin and fish script function were in worse shape than I realized. For example, the two CLIs were only superficially compatible. Second, there aren't any substantive tests of the history UI. The output of `git diff` is currently ~650 lines long and I haven't even written a new unit test. So I'm going to create a PR for the core change. I'll do a second PR with the necessary unit tests in a few days. I'm also going to reclassify this as a bug fix because the change fixes several bugs in addition to adding sanity checks for invalid combinations of CLI args.

**Comment by krader1961** [comment]
Also, it looks like there is some inconsistency as to whether the history entries are ordered newest to oldest or vice-versa depending on the subcommand and arguments. The man page is silent on the topic. My preference is newest to oldest (e.g., equivalent to `ls -ltr`). Please comment if you feel strongly it should be oldest to newest (e.g., equivalent to `ls -lt`). Whichever we choose I want to document it as part of fixing this issue and ensure consistent behavior for all combinations of args.

**Comment by krader1961** [comment]
I'm going to defer the ordering of history entries to a separate issue. The size of the changes related to the original reason for this issue are already uncomfortably large.
