### ISSUE TITLE
`source` command  should error out if reading from the tty

### ISSUE THREAD

**Issue by ymmtmdk** [fish-shell/fish-shell#3227]
Fish hangs when run binded the source command.

- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version 2.3.1-384-gf08ac96

**OS/terminal used**: 
OSX / iTerm2

## Reproduction steps

1. Launch fish
2. Run bind \cx source
3. Hit \cx
4. Hit \cd but fish responds nothing

**Comment by pranav-prakash** [comment]
Isn't this because source itself needs to have a file argument? Like you could do `bind \x 'source ~/.profile` or something.

**Comment by krader1961** [comment]
Setting aside for the moment that running `source` without a filename is an error that should be treated as such what are you trying to accomplish with that key binding?

**Comment by ymmtmdk** [comment]
Thank you for comments.
I have nothing to accomplish with that key binding, indeed.
Accidentally, found this behaviour and have reported this.

**Comment by zanchey** [comment]
> Setting aside for the moment that running source without a filename is an error

You can redirect into `source`, so it's not necessarily an error.

You should be able to escape out of `source` with Ctrl-D; if not, then there is a problem.

**Comment by ymmtmdk** [comment]
Was examined a little more.
Now I can reproduce the problem by a file.

```
echo perl > perl.src
bind \cx source perl.src
# \cx will cause hang up
```

**Comment by krader1961** [comment]
Okay, I see there could be legitimate use cases for constructs like `some_command | source` where `some_command` writes fish commands to its stdout. The `source` man page needs to be updated to reflect that use case. Nonetheless it seems to me we should modify the `source` command to disallow reading from the tty on general principal since it'a a rather nonsensical thing to be doing and probably indicates an error by the user.

**Comment by floam** [comment]
Huh! That seems strange that works, but neato. I think of source as very much an action that includes data from a file path it's given and then evaluates it. So I'd suppose I'd have thought `echo echo hi | eval` or actually `echo echo hi | source /dev/stdin` could work but not just `| source`! I'm not sure I ever tried this in a shell before.  Learn something new every day.

**Comment by floam** [comment]
This also makes sense: `echo /usr/local/share/fish/completions/*.fish | source` but doesn't do what I'd have guessed earlier.

**Comment by faho** [comment]
We've had this discussion before in #2633.

Let's discuss there, since that's still open.
