### ISSUE TITLE
vim bindings without indicator

### ISSUE THREAD

**Issue by theScrabi** [fish-shell/fish-shell#3232]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
2.3.1

**OS/terminal used**: 
Linux/gnome-terminal

I like the fish vim bindings, but I don't like the vim indicator at the beginning of the prompt. Is it possible to enable vim bindings without having that ugly indicator shown up?

1. Launch fish
2. enable vim bindings

**Comment by aloiscochard** [comment]
:+1: 

I did browse the source code but was not able to find a way to remove this (terribly) ugly indicator (or customize it with utf-8 character at least).

If someone could point me on the right direction, I did look on `fish_vi_key_bindings` but found nothing.

**Comment by aloiscochard** [comment]
Okay, I found it in `share/functions/fish_mode_prompt.fish`, it can be override in your config with:

```
function fish_mode_prompt
  # NOOP - Disable vim mode indicator
end
```

**Comment by floam** [comment]
> I did browse the source code but was not able to find a way to remove this (terribly) ugly indicator (or customize it with utf-8 character at least).

I found a few characters that I think work kinda well [[gist](https://gist.github.com/floam/e89ed4a882eb629b0a70040f876479c6)]:
![screenshot](http://i.imgur.com/EfDNgJH.png)

**Comment by krader1961** [comment]
Seems like the documentation could be improved to make it easier to discover where the VI mode indicator comes from and how to customize it.

**Comment by floam** [comment]
Seems reasonable - a number of people just do not dig it. If the default we have in place is very unpopular (hard to know, but at least a few people have filed issues), can anyone suggest a reasonable (UTF-8 isn't necessary a problem, but rare glyphs like above probably are) better default?

Personally the fact that it absorbs three whole columns, and is on the leftmost area on the prompt was something I didn't love.

**Comment by floam** [comment]
Also, we could set the tab title separately from the window title (they are identical now), and insert a spelled-out, theoretically translatable, `INSERT` in the window title bar, if we wanted. (You only care about the vi mode if the focused terminal session.)

**Comment by aloiscochard** [comment]
I was just thinking, maybe we could change the background color of the line (as it happen when fish gives feedback during completion), instead of adding new characters at the begin of the prompt.

I'm quite confident that current approach isn't much popular among vi users, we can surely agree on a better default.

**Comment by theScrabi** [comment]
@aloiscochard Yep I totally agree. I use powerline prompt, so any character before my prompt messes the design up.

**Comment by callahad** [comment]
I wonder if it would be more palatable if we hid the indicator when in insert mode, but showed it for the others, since insert mode is the common mode for CLI interactions.

Also, a simple `touch ~/.config/fish/functions/fish_mode_prompt.fish` is enough to disable the built-in prompt; no need to add a no-op function body.

**Comment by faho** [comment]
This has been documented, so there's nothing more to do here.

**Comment by nijotz** [comment]
I had to use https://github.com/fish-shell/fish-shell/issues/3232#issuecomment-232670506 to figure out how to customize this. I would say it's not well documented.

**Comment by krader1961** [comment]
Fair enough, @nijotz, but it would help if you provide some ideas on how to improve it. Even better would be creating a change that you believe improves the documentation.

**Comment by nijotz** [comment]
Sounds good. I'm playing with it now, I can document what I'm learning. Where to?

**Comment by nijotz** [comment]
I believe I found it here:
https://github.com/fish-shell/fish-site/blob/master/site/docs/current/commands.html#L1114

**Comment by krader1961** [comment]
If you're comfortable using git just open a github pull-request. Otherwise, just add a comment with a copy/paste (or `diff`) of what you think would help and a core dev will incorporate the change.

**Comment by nijotz** [comment]
I'll PR it, thanks @krader1961

**Comment by faho** [comment]
@nijotz: Please note that the documentations in the fish-site repo are generated from [the doc_src directory](https://github.com/fish-shell/fish-shell/tree/master/doc_src) in this repo, so you'll want to work on doc_src, **not fish_site*.

**Comment by nijotz** [comment]
Ahh, good to know, thx
