### ISSUE TITLE
Tab completion doesn't work for abbreviations

### ISSUE THREAD

**Issue by willwhitney** [fish-shell/fish-shell#3233]
When typing an abbreviation, it would be really nice if you could hit tab to complete that abbreviation. For example, I have an abbreviation `devgpu` that expands to `ssh <my_server>`, but when I type `dev <tab>` I don't get `devgpu` as a suggestion.

While it is a little weird to complete something that's not a real command, I still expected the completion to show up, and it would definitely make things quicker for me.

**fish version installed** _(`fish --version`)_: 2.3.0

**OS/terminal used**: Mac OS 10.11, iTerm2 3.0.4

**Comment by krader1961** [comment]
Odd that I've never noticed that, but you're right. Abbreviations really should be part of the command completions. Patches welcomed. 😺

**Comment by floam** [comment]
Would the completion expand it into the expected final, right-hand-side of an abbr definition when you've typed part of the left hand "before" side of the abbreviation? What would you see in the pager? 

Just adding `complete`'s for one side or another isn't exactly enough, right?

**Comment by willwhitney** [comment]
My expectation is that it would suggest the "before" part and it wouldn't expand until space or enter as usual.

**Comment by floam** [comment]
Except on enter, what it actually does is expand and execute. That's probably too much to have occur when the interactive experience might have prepared you for a different result where your command doesn't get swapped out like that.

**Comment by ThomasAH** [comment]
I experienced this today, too.
I wanted to use an abbreviation like an alias, in my case:
"backup-mt-eject" to "ssh backup sudo mt-eject"
and
"backup-bconsole" to "ssh -t backup bconsole".

So "bac<tab>" should have completed to "backup-"
and "backup-m<tab>" to "backup-mt-eject"

Only after pressing Enter (or Space) the abbreviation should transfer into the expanded result on the command line (as it currently already does). So the same thing that @willwhitney said.

I understand @floam's concerns, but as this is not different from what would happen if I had entered "backup-mt-eject<Enter>" myself, this is only as confusing as the current situation if you have abbreviations you don't know.

**Comment by ridiculousfish** [comment]
@ThomasAH Do I  correctly that your request is simply that tab-completions should expand abbreviations?

**Comment by ThomasAH** [comment]
@ridiculousfish No, tab-completion should complete abbreviations. Only Enter or Space should expand them.

**Comment by marcvangend** [comment]
This enhancement would be very welcome. I have never written a line of C++ in my life but I'd be happy to help test patches/PR's.

**Comment by BarbzYHOOL** [comment]
I stumbled upon this issue too when I made an abbreviation that is kind of lenghty (instead of a function/alias). Need it!!

**Comment by ridiculousfish** [comment]
Fixed in 202bf0bedea34e855396f61a9a547b6e04927464

**Comment by BarbzYHOOL** [comment]
awesome @ridiculousfish

**Comment by c02y** [comment]
Weird, tab doesn't complete any of my abbrs
fish, version 3.0.2 here

**Comment by ridiculousfish** [comment]
@c02y can you share steps to reproduce - abbreviations that fail and what you try? Thanks

**Comment by c02y** [comment]
It seems working again, sorry about that, maybe I just didn't restart fish.
