### ISSUE TITLE
How can I auto complete the grey suggested item ?

### ISSUE THREAD

**Issue by qharlie** [fish-shell/fish-shell#324]

**Comment by AndriiRubtsov** [comment]
https://fishshell.com/docs/current/tutorial.html

"Right arrow" also works and seems more convenient to me.

**Comment by kozie** [comment]
I prefer using Ctrl + F but it doesn't seem to work in tmux. Or can it be that fzf conflicts with this, even tho i'm using its legacy keybindings?

**Comment by faho** [comment]
@kozie:

Execute `fish_key_reader`, press Ctrl + F. That should tell you what sequence fish gets (it should be `\cF`). Then execute `bind \cF` (obviously substituting the sequence you just got) to see what it's bound to (by default it's "forward-char"). If it isn't bound like you want, you'll have to bind it. Make a function called "fish_user_key_bindings" (e.g. via `funced`) and add e.g. `bind \cf forward-char` or `bind \cf accept-autosuggestion` as you like.

**Comment by kozie** [comment]
Thanks for the tip @faho! It works like a charm now ^_^

**Comment by maksimmuravev** [comment]
What about if I'm in VIM mode?

**Comment by maheshbansod** [comment]
Also want to know the shortcut key for vim mode.

**Comment by faho** [comment]
Any key that moves over the autosuggestion will accept that part of it, except for the regular "forward-char" which will accept all of it.

In vi-mode forward-char is "l" in normal mode, and "$" moves to the end of the line and will accept the entire suggestion from wherever.

**Comment by maheshbansod** [comment]
That works, thanks! 
`<Esc>$$` for accepting the full completion. or `<Esc>w` to accept a word

**Comment by davinkevin** [comment]
Hello @faho, 

I'd like to leverage such feature (`ctrl+f`) in `vi` insert mode, is that possible?
I tried to to `bind \cf forward-char` but it was unsuccessful, so far. What do you recommend?

**Comment by faho** [comment]
@davinkevin: By default, `bind` binds things in "default" mode. For vi-bindings, that's what vi calls the "normal" mode.

To bind it in insert mode, use `bind --mode insert \cf forward-char`.
