### ISSUE TITLE
remove interactive deleting of individual history entries

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3242]
The `history --delete` (function, not builtin) behavior is broken (see issue #31). The addition of displaying timestamps adds another way to break that command. I'd like to propose removing the ability to delete individual history entries by number. This would still leave the current behavior of showing all the matching entries and asking if the user wants to delete all of them or do nothing. If someone really wants to delete a subset of the matching entries they can either specify a more restrictive search term or manually edit the history file.

Regardless I intend to change the behavior to require actually typing "yes" (rather than just "1") to actually delete all the matching history entries.

**Comment by floam** [comment]
I'll refer to [my comment in #31](https://github.com/fish-shell/fish-shell/issues/31#issuecomment-232859470) regarding what I think would work more nicely for referring to individual fish history entries.

**Comment by krader1961** [comment]
It's interesting that adding the `history` builtin, including the ability to delete entries, was first mentioned in issue #1 a little over four years ago:

> fish needs a history built-in, for things like deleting unwanted history items. bash and zsh both have this.

That's the sum total of the argument for being able to delete entries. The bash man page says this is done by specifying an "offset" but doesn't clearly say what that is: `history -d offset`. The zsh man page doesn't make any mention of being able to delete entries that I can find. In typical zsh fashion It does talk about a complicated push/pop mechanism and a bazillion other options.

I'm still at a loss for what the use case is for deleting single entries. But if we're going to support the feature then I agree with @floam that it should be done using a hash of the timestamp and command string to uniquely identify an entry. That, obviously, requires an option to display the hash (e.g., like `ls -i` prefixes the file name with its inode number) and an option to specify the hash when searching/deleting.

**Comment by zanchey** [comment]
I use the deleting interface occasionally (there's about a dozen occurrences in my history), and mostly with `--contains` rather than `--prefix`. It's also available in `fish_config`, although that's not much good remotely.

**Comment by floam** [comment]
I think we can use timestamps and quietly boost the resolution stored:

```yaml
  when: 1468740748.1
- cmd: ./configure2
  when: 1468740748.5
- cmd: ./configure3
  when: 1468740748.8
- cmd: ./configure4
  when: 1468740749.0
- cmd: make
```
...
```
Sun Jul 17 00:32:29 2016 ./configure4
Sun Jul 17 00:32:28 2016 ./configure3
Sun Jul 17 00:32:28 2016 ./configure2
Sun Jul 17 00:32:28 2016 ./configure
```

It seems existing fish is just ignoring the decimal points but still getting the time right without apparently trouble. Future fish could use a little bit more precision to make base36'ing (pick your favorite encoding) just the timestamps workable. 

The advantage with the timestamps vs. foolproof string hashes is they are easily sortable and a person can grok what would be meaningful sequences. Identical history items would be problematic without salting with another piece of info (like the date.) anyhow.

**Comment by krader1961** [comment]
@zanchey It wasn't clear from your comment if you're actually deleting just one entry at a time from multiple entries matched by `history --delete text`.

@floam The history vector should always be ordered chronologically. If that isn't the case I would argue that is a bug which needs to be fixed. It shouldn't be necessary to sort the entries at the time the `history` command is run; other than possibly in the case of `history --merge`.

**Comment by faho** [comment]
This seems like it could be improved with #2805 instead.

**Comment by krader1961** [comment]
> This seems like it could be improved with #2805 instead.

Maybe although it's unclear how multiline commands would be handled. Too, implementing that feature is probably not going to happen in the immediate future. Whereas we can fix the main problem with the interactive history delete feature with a very straightforward change that probably won't take me more than two or three hours of work.

**Comment by floam** [comment]
>we can fix the main problem with the interactive history delete feature with a very straightforward change that probably won't take me more than two or three hours of work. 

Sorry - not sure which potential fix that would be. The removal of the feature as this issue seeks? (What is the main problem with the interactive delete?)

**Comment by krader1961** [comment]
Implementing a uuid for each history entry which can be returned by `history --search` and passed to `--history delete`. Of course, just removing the feature would be even easier and require no more than a few minutes of work.

**Comment by krader1961** [comment]
What I find interesting is that five days after opening this issue and sending an email to the fish-users mailing list only one person has argued against removing this feature. And their argument for not removing the feature basically boils down to "it's already implemented so why remove it?" However, given the current implementation is seriously broken in a manner that can easily result in unexpected history entries being removed I don't find that a compelling argument. Nor could I find any instances of people reporting problems with the behavior of `history --delete` other than issue #2947 opened by the same individual and #31 opened shortly after the feature was implemented. Which suggests to me that no one is using it &mdash; or at least so few people so infrequently that no one is likely to complain if the feature is eliminated.

The only reason I'm not going to proceed with removing this feature is that a) it appears relatively simple to fix the fatal flaw in its implementation, and b) I've already invested some effort in fixing other problems with the implementation (see commit b53f42970ceacae428788f7b9b933fc458fb6042). I'm going to let this bake for a few more weeks to see if anyone else has a strong opinion.

**Comment by krader1961** [comment]
There are people using the ability of the `builtin history --delete` to remove individual entries that exactly match a given command. A fix is pending to reinstate that behavior in the `history` function (as opposed to the builtin). Whether or not there are people using the interactive ability to match, then select, multiple commands to be deleted is unclear. Nonetheless, the feature mostly works so we might as well retain it. Too, see issue #2110 which quite reasonably asks for a way to delete auto-suggested history entries.

We'll track fixing the problems with deleting multiline commands in issue #31.

**Comment by johann-koebbe** [comment]
@krader1961 

> I'm still at a loss for what the use case is for deleting single entries

I inadvertently typed

```fish
$ bundle install --path vendor/bundlea
```

Notice the trailing `a`. Even though I've typed it correctly since, that's the first item that shows up when I try to bundle install again, so I end up using the wrong command. Just today I started wondering about deleting individual history entries, which brought me to this issue. I'll follow along at #31 now, but I wanted to respond to your statement here to keep it in context.

**Comment by oyalhi** [comment]
I would like to delete a single entry from history as well.  I have wrongly typed the following:

git push tag --all
git push tags
git push --tags

The first two are wrong and the last one is correct. So I would like to delete the wrong ones from history as I don't use this command often I tend to forget and the history becomes very handy - unless you have wrongly typed commands. 

This is just one example.

Thanks for a great product!

**Comment by ridiculousfish** [comment]
A quick way when you see an unwanted command is to *run* that command, and then delete the last command in history:

```
git push tags
history --delete $history[1]
```

It will give you a chance to confirm.
