### ISSUE TITLE
fish doesn't honor .ssh/config files

### ISSUE THREAD

**Issue by jackcviers** [fish-shell/fish-shell#325]
## Steps to recreate
1. create the following ~/.ssh/config file:
   Host somehost
   HostDomain somehost.com
   User someUser
   
   Host *
   User userName
2. open a fish shell
3. ssh somehost.com
## Expected

ssh uses someUser@somehost.com as defined in ~/.ssh/config file
## Observed behavior

Default user  is always used.
ssh uses userName@somehost.com (which, since userName is local to the local machine, doesn't exist)
## Workaround

None.
## FishFish Version

fish, version 1.23.1

**Comment by Dundee** [comment]
HostName is not mandatory option in ssh/config.

This is valid config for the host:

```
Host example.com
        User root
```

Fish should complete this hosts as well.

**Comment by zanchey** [comment]
@Dundee, `__fish_print_hostnames` should already do this; if not, could you open a new issue?

**Comment by Dundee** [comment]
@zanchey Thanks, I confirm that it's already fixed in master.
