### ISSUE TITLE
Want to remove vim mode indication

### ISSUE THREAD

**Issue by marshallcroes** [fish-shell/fish-shell#3254]
![screen shot 2016-07-20 at 1 41 54 am](https://cloud.githubusercontent.com/assets/10128228/16970326/855bf1f4-4e1b-11e6-9959-53be4a415e32.png)
I'm currently running fish, version 2.3.1, and been using vim mode. Since the update I got this green [I] to show me what mode I'm in. Is there anyway I can get rid off it?

**Comment by krackers** [comment]
See: https://github.com/fish-shell/fish-shell/issues/3232
