### ISSUE TITLE
Prompt functions cannot be overwritten

### ISSUE THREAD

**Issue by talgendler** [fish-shell/fish-shell#3257]
**fish version installed** *(`fish --version`)*: 2.3.1

**OS/terminal used**: OSX/iterm2(3.0.5)

I want to use a different prompt function instead of the default one. After choosing one with the _fish_config_ I can see that there is a _~/.config/fish/functions/fish_prompt.fish_ file. However when I launching a new shell the fish_prompt function is reseted to be: 
__> functions fish_prompt__
```fish
function fish_prompt
	fish_fallback_prompt
end
```
when I delete this function with __functions -e fish_prompt__ the prompt becomes what I want it to be and the _fish_prompt_ function becomes:
__$ functions fish_prompt__
```fish
function fish_prompt --description 'Write out the prompt'
	if not set -q __fish_git_prompt_show_informative_status
		set -g __fish_git_prompt_show_informative_status 1
	end
	if not set -q __fish_git_prompt_hide_untrackedfiles
		set -g __fish_git_prompt_hide_untrackedfiles 1
	end
........
```
However like I said above launching a new shell instance will reset this behaviour

**Comment by floam** [comment]
What is your `$TERM`? I know you are using iTerm but for some reason it looks like it's going through the code in `__fish_config_interactive` (see: `type fish_config_interactive`) towards the end where it overwrites `fish_prompt` to protect simple-minded linux virtual terminals.

So, I'd suspect that also your `set_color` function is overwritten with the one there - `type set_color` can confirm this, as would an error message when trying to use colors we disallow there - `echo (set_color brblue) test`.

**Comment by talgendler** [comment]
Thank you @floam 
I checked this and the terminal was set to be "linux". Now when I changed it to be "xterm-256color" everything is working as expected.
