### ISSUE TITLE
"bind \e\n ..." doesn't work anymore

### ISSUE THREAD

**Issue by mamiu** [fish-shell/fish-shell#3258]
Till now I used `bind \e\n accept-autosuggestion execute` to execute the autosuggestion with <kbd>Alt</kbd>+<kbd>Return</kbd>  

With the newest version (2.3.1) this doesn't work anymore. The bind command is in the `~/.config/fish/fish_user_key_bindings.fish` and works if I change the `\e\n` to another keybinding.

**Comment by faho** [comment]
This is a result of our fix for #217. To be able to distinguish between control-j and return, we've had to set some terminal stuff, which also causes decoupling of `\n` and `\r`.

Try `bind \e\r` instead.

**Comment by krader1961** [comment]
Expanding on @faho's answer. Note that `\n` is just another name for `\cJ` so you should be able to invoke your key binding by pressing [esc][ctrl-J]. Similarly, `\r` is just another name for `\cM`. The [enter] key usually sends `\cM`, aka `\r`. Fish used to configure the tty driver to map the latter to the former but no longer does so. This allows both control chars to be bound independent of each other.

**Comment by mamiu** [comment]
@faho & @krader1961: Thank you both! That solved the issue for me. :+1:
