### ISSUE TITLE
fish scripts always print the $fish_greeting welcome message before the "read" command prompt

### ISSUE THREAD

**Issue by terrycloth** [fish-shell/fish-shell#3261]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
2.3.1

**OS/terminal used**: 
Fedora 24 (64-bit) / GNOME Terminal 3.20.2

I'm writing a simple script that uses the `read` command to get info from the user before continuing. Every time the script runs, when it gets to the first `read` line, it prints the `$fish_greeting`, which I find a little distracting.

The only workaround I've been able to figure out is to set `fish_greeting` to an empty string -- however, even when I use `set --local`, that seems to permanently remove the fish greeting for all future sessions, not just when running the script. Some users of my script may not like that.

Here's an example script that consistently prints the fish greeting when it reaches the `read` line.

``` fish
#!/usr/bin/fish
echo "What's your name?"
read name
echo "Hello, $name!"
```

**Comment by floam** [comment]
This is #1401.

It looks like the fix for it in e1f623f548c0e6241642db96c522c411cd84d755 is no longer present.

**Comment by terrycloth** [comment]
Wow, that was fast. Thanks!

**Comment by ridiculousfish** [comment]
This got reverted as 88688d02b2c799ed5af5a8441c120576d36ded82

**Comment by ridiculousfish** [comment]
It took me a while to reconstruct what happened.  It looks like 88688d02b2c799ed5af5a8441c120576d36ded82 actually reverted 3d0ea5fe79759d3d310a2fa014ed9e466ca41453, 3a7a6f16eff4591415898b97f54f9521692f2b45, and ec292ec51b5e1a06db4ed566160353c4c0ce6449, not merely the commit it named. After this reversion, HEAD is back at d252704fdbc8e77f1391d96be6233dad2d01fad6

**Comment by floam** [comment]
Aye ye ye: more like "trashing":.. I literally thought `origin` on that Windows machine I was using git on (without fish handy) was *my* remote but it was `fish-shell` (I normally make it upstream).

I was trying  to essentially stash the commit log and break `__fish_config_interactive` such that I wouldn't forget about actually testing that one with `fish` available when I got home. I even pushed a second time when it didn't seem to take. I didn't realize for a few hours that it was actually on `fish-shell/master`. I'm sorry.

**Comment by ridiculousfish** [comment]
Ah, that makes sense. No harm done.
