### ISSUE TITLE
fish_key_reader `bind` command output has a problem with spaces

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#3262]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: fish, version 2.3.1-415-gecb40a4-dirty

**OS/terminal used**: OS X

A space character easily causes confusing output which is showing a string used during another part of the program. It's also not properly escaped:

## Reproduction steps
```fish
#              hex:   68  char: h
#( 58.072 ms)  hex:   65  char: e
#(137.634 ms)  hex:   6C  char: l
#( 39.800 ms)  hex:   70  char: p
#(176.035 ms)  hex:   20  char: \x20  (aka "space")
#( 84.025 ms)  hex:   6D  char: m
#( 92.070 ms)  hex:   65  char: e
#(112.010 ms)  hex:   20  char: \x20  (aka "space")
bind help\x20  (aka "space")me\x20  (aka "space") 'do something'

**Comment by faho** [comment]
Same thing with "del" - `bind \x7F  (aka "del") 'do something'`.
