### ISSUE TITLE
Bind arrow keys to void

### ISSUE THREAD

**Issue by sassanh** [fish-shell/fish-shell#3263]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version 2.3.1

**OS/terminal used**: 
OS X 10.11 - Iterm2 3

Talk about the the issue here. 
I can't disable arrow keys with bind commands. Is it possible at all?

**Comment by krader1961** [comment]
What did you try? Running `bind -k \e\[C 'true'` on my system disables the right-arrow key, for example. Running `fish_key_reader` can help you identify the proper bind sequence.

**Comment by sassanh** [comment]
`'true'` solved it, I was using `-e`. Thanks.

**Comment by floam** [comment]
> bind -k \e\[C 'true'  on my system disables the right-arrow key

With `-k`? That should error out.

**Comment by sassanh** [comment]
Yeah I removed `-k` to, forgot to mention that.

**Comment by sassanh** [comment]
Actually `fish_key_reader` prints out thew whole binding command except for its action part.
