### ISSUE TITLE
abbr -e completion mis-escapes things

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#3267]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

The completion of `abbr -e` can expand such that it escapes single quotes when we don't want that.

**fish version installed** *(`fish --version`)*: 2.3.1

**OS/terminal used**: OS X
## Reproduction steps

1. `abbr \&\& '; and'`
2. `abbr -e <TAB>`
3. Select the completion we just made

## Expected results
It should expand to `abbr -e '&&'` or `abbr -e \&\&`

## Actual results
Expands to this, which causes an error:

	> abbr -e \'\&\&\' 
	abbr: no such abbreviation ''&&''

**Comment by faho** [comment]
The issue here was that `abbr --show` already escapes things, so we complete an escaped thing and escape it again.
