### ISSUE TITLE
fish completion from man page parses some format incorrectly

### ISSUE THREAD

**Issue by feigaochn** [fish-shell/fish-shell#3272]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version 2.3.1

**OS/terminal used**: 
macOS El Capitan 10.11.6 (15G31)
iTerm2 Build 3.0.20160702-nightly

**Talk about the the issue here. **
Completions auto generated from man pages did not process some format correctly.
Take `aria2c` as an example, in man page, it contains format like this
```
    -D, --daemon[=true|false]
```
So fish completes the command with `\[` suffix
```
$ aria2c --daemon\[
```

## Reproduction steps
Hard to explain? Link to [a screen recording](https://asciinema.org)

1. Launch fish
2. `aria2c --dae[Tab]`

## Expected results
Fish should output `aria2c --daemon`

## Actual results
	~ $ aria2c --daemon\[

**Comment by floam** [comment]
Can you give git master a try?

**Comment by feigaochn** [comment]
thanks, it is working correctly now (with $FISH_VERSION 2.3.1-432-gb77e2a6).
