### ISSUE TITLE
Command pipeline works unexpectedly

### ISSUE THREAD

**Issue by roy2220** [fish-shell/fish-shell#3277]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.3.1

**OS/terminal used**: Fedora

1. Install FZF (https://github.com/junegunn/fzf-bin)
2. Launch fish
3. Execute `alias fzf 'fzf'`
4. Execute `echo test | fzf` repeatedly

Sometimes FZF shows up, sometimes it doesn't show, then you can find it in process list (stay in the background).
It never behaves like this in bash.

## Expected results
FZF shows up always.

**Comment by floam** [comment]
How many times do you need to repeat `echo test | fzf` before you get a case of it not working? I'm trying to reproduce this but am not (yet) having luck.

**Comment by krader1961** [comment]
When you say "Execute `echo test | fzf` repeatedly" do you mean you are entering that statement and pressing [enter] when presented with an interactive prompt prompt? Are you pressing [ctrl-C], [ctrl-Z], or anything else that might interfere with the execution of the statement? Also, it is not clear what you mean by "Sometimes FZF shows up, sometimes it doesn't show".  Can you capture the problem using [asciinema](https://asciinema.org/)?

**Comment by floam** [comment]
If you do ` while echo test | fzf; end` and hold down enter causing it to run and quite over and over and over perhaps hundreds of times, does the problem occur? I'm just trying to make it happen here.

**Comment by floam** [comment]
I'd guess [this](https://github.com/junegunn/fzf/issues/60). Are you using current `fzf` from git and did you install it using their script?

**Comment by roy2220** [comment]
@floam @krader1961 here is the  asciinema record https://asciinema.org/a/81453 , I forgot to mention is use the `alias fzf 'fzf --no-256'`, maybe it causes this bug in fish

**Comment by krader1961** [comment]
What does `--no-256` do? If you remove the alias and replace it with an abbreviation

```
abbr -a fzf 'fzf --no-256'
```

does that alter the behavior?

**Comment by krader1961** [comment]
I watched your asciinema recording several times. I can't tell what the problem is. But it did look like the very first `echo a | fzf` left a fzf process running in the background. Which implies that you can reproduce the problem on demand rather than "sometimes it doesn't show".

**Comment by floam** [comment]
I'm pretty sure this has to be the same thing I linked above.

**Comment by roy2220** [comment]
@floam @krader1961 `abbr -a fzf 'fzf --no-256'` and then `echo a | fzf` repeatedly  DO NOT encounter this problem!

**Comment by roy2220** [comment]
my test:
   `echo a | fzf`  -> don't encounter this problem
   `alias fzf 'fzf --no-256'; echo a | fzf` -> encounter this problem
   `abbr -a fzf 'fzf --no-256'; echo a | fzf` -> don't encounter this problem

conclusion:
   seems to be caused by buggy alias?

**Comment by roy2220** [comment]
@floam I updated the problem reproduction steps, `alias fzf 'fzf'` can reproduce this problem.

**Comment by floam** [comment]
Yeah I can reproduce that too with that shorter alias. I assume you have the fish scrips fzf comes with installed. This might do what you want: `alias fzf "eval (__fzfcmd --no-256)"`

**Comment by floam** [comment]
More info: https://github.com/fish-shell/fish-shell/issues/1362

**Comment by floam** [comment]
To be clear, that alias I shared does not work around the real issue e.g. this won't work:
`echo (echo test | fzf)`
It's sure uglier than the abbr.

**Comment by krader1961** [comment]
Is this a dup of #1362 or not? If it is a dup please close.

**Comment by floam** [comment]
Looks like it. They even mention the `fzf` thing specifically.

**Comment by Ambrevar** [comment]
Note that this issue breaks fzf's default config, not only the alias, as it uses `eval (__fzfcmd)` to start fzf.
Calling
```
ls | eval fzf
```
will fail randomly.
