### ISSUE TITLE
Drop stickers PSD from repo/tarball?

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#3278]
I have never noticed it before but there is a file [`doc_src/branding/logo.psd`](https://github.com/fish-shell/fish-shell/blob/master/doc_src/branding/logo.psd) checked into master. It's around 3.8MB large. We also have been including it in our [releases](https://github.com/fish-shell/fish-shell/releases/download/2.3.1/fish-2.3.1.tar.gz) it seems, where even after being gzipped it's making the tarball about a third larger than it'd otherwise be. It seems to me this would have a better home in a clean branch other than `master`, or better another repo entirely like `fish-site`.

The ~4MB PSD doesn't seem to represent the most official logo of fish (despite the filename), instead it seems to be a cool fan-art composition of the ASCII fish with a template for laser-cutters, for having stickers made. What's the thinking here? Nobody downloading fish will need it. Someone searching for fish stickers likely won't find it with it buried there. Shouldn't it go on the website, if anywhere?

**Comment by ridiculousfish** [comment]
Oh god, how did that get in there. Yes, let's move it to fish-site.

**Comment by floam** [comment]
I'll yank it. How do you want to show it on the actual site of fish-site? I suppose another way to do it is host it in the repo with the README pretty much like this one was and mention on Wiki or something.

**Comment by ridiculousfish** [comment]
I think interest in the artwork itself will be low, so it's OK to link to it from an obscure place (like the wiki). But users might like to have a place to buy stickers - that might merit a small link on the site.

**Comment by floam** [comment]
OK, "moving" this issue over to fish-site with the magic button in a [browser extension](https://github.com/ZenHubIO/support). It can be discussed there.

**Comment by floam** [comment]
Issue moved to [fish-shell/fish-site #41](https://github.com/fish-shell/fish-site/issues/41) via [**ZenHub**](https://www.zenhub.com/)
