### ISSUE TITLE
Virtualbox Autocompletion

### ISSUE THREAD

**Issue by ikzk** [fish-shell/fish-shell#3280]
The commands for virutalbox are notorious complex (especially `vboxmanage`). I find that bash and zsh have the autocompletion functionality for these commands (e.g. https://github.com/zsh-users/zsh-completions/commit/79efbc8d353f603f56c8cde39d43a8a82d9b26a9 and https://github.com/tfmalt/bash-completion-virtualbox). I am not sure whether this will be easy to implement on fish (since I am not an expert on this). After using fish shell for about half a year, I greatly appreciate the simplicity and user-friendliness of it. It will be great to add this autocompletion on fish shell!

**Comment by krader1961** [comment]
Custom completions need to be written and submitted by someone motivated to do so. Like yourself, @ikzk. We're happy to provide advice on how to do so. But without such a submission this issue will simply bit rot.
