### ISSUE TITLE
Unexpected `builtin read` behavior

### ISSUE THREAD

**Issue by roy2220** [fish-shell/fish-shell#3281]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.3.1

**OS/terminal used**: Fedora

## Expected results
```
$ cat | read X           # no use  the --array option
^C                       # CTRL-C
$ count $X
1                        # variable X is set to an empty string
```

## Actual results
```
$ cat | read X
^C
$ count $X
0                                # variable X is set to an empty array, why?
```

**Comment by krader1961** [comment]
Why do you expect `X` to be set to an empty string? It didn't read anything from the pipe because you interrupted the `cat` command. Not to mention you interrupted the entire command. The behavior you observed is exactly what I would expect.

**Comment by roy2220** [comment]
I expect `X` to be set to an empty string because I have not use the `--array` option, intuitively it should not be an array.
But now I realize maybe every variable in fish is an array. That's ok.

**Comment by krader1961** [comment]
> But now I realize maybe every variable in fish is an array.

Correct. That is arguably the one behavior of fish that is the most difficult to become accustomed to for people coming from other shells.
