### ISSUE TITLE
add completions for `swift` command (the programming language CLI)

### ISSUE THREAD

**Issue by rymcol** [fish-shell/fish-shell#3289]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations _(check `sh -c 'env HOME=$(mktemp -d) fish'`)_?

**fish version installed** _(`fish --version`)_:

fish, version 2.3.1

**OS/terminal used**: 

macOS Sierra 10.12 beta 4 / Terminal Version 2.7 (376)

When attempting to tab autocomplete on `swift`, such as `swift build`, the auto-complete suggests directories instead of swift commands. 
## Reproduction steps

Hard to explain? Link to [a screen recording](https://asciinema.org)
1. Launch fish
2. Type "swift b"
3. Press tab
## Expected results

Fish should suggest build as the autocompletion. 
## Actual results

```
~ $ swift b
Dropbox/  Library/  Public/  webroot/
```

**Comment by faho** [comment]
The swift completions just haven't been written yet. Patches welcome!

**Comment by rymcol** [comment]
@faho where are the completions stored?

**Comment by faho** [comment]
share/completions/$command.fish in this repo.

**Comment by faho** [comment]
Though if you'd like to write one, put it in ~/.config/fish/completions/swift.fish.

**Comment by krader1961** [comment]
Custom completions need to be written and submitted by someone motivated to do so. Like yourself, @rymcol. We're happy to provide advice on how to do so. But without such a submission this issue will simply bit rot.
