### ISSUE TITLE
Porting steeef.zsh-theme prompt

### ISSUE THREAD

**Issue by aristidesfl** [fish-shell/fish-shell#329]
![steeef](http://i.imgur.com/HK3YC.png)

Would it be possible to port this awesome theme from zsh?
https://github.com/robbyrussell/oh-my-zsh/blob/master/themes/steeef.zsh-theme

**Comment by krader1961** [comment]
Closing since no one has been motivated to implement this in the four years it has been open parts of it have subsequently been added to the fish project (e.g., the terlar prompt).
