### ISSUE TITLE
documentation for `$__fish_sysconfdir/conf.d` needs improvement

### ISSUE THREAD

**Issue by joedborg** [fish-shell/fish-shell#3291]
Talk about the the issue here. 
Taking 2.3.1 tag from GitHub, I'm trying to migrate from BASH.  I am running Fedora 24 with the standard Gnome terminal emulator (although I'm sure that is not useful information for this).

I am trying to set a system wide http_proxy.  In BASH, I do this by placing a file in `/etc/profile.d/`, in this case named `proxy.sh`, which exports the environment variable using `export`.  This runs for all users on the system that use BASH (or SH) for their login shell.  This means I don't have to update it per user.

To achieve the same in Fish, I have read through the docs and issue #1956.  From this, I deduced that I should put a script into `/etc/fish/conf.d/` to get a similar affect.  In this case, I've added `proxy.fish` and set the `http_proxy` variable using `set -gx`.  This seems to work fine for `root` user, but for no one else (the permissions allow read and execute globally).  If I copy this script into `~/.config/fish/conf.d/`, it works fine for my user.

## Reproduction steps
1. Create a script in `/etc/fish/conf.d/`

## Expected results
Fish should…
(I believe) Execute that script for all system users using Fish as the login shell.

## Actual results
Only run for `root`.

**Comment by zanchey** [comment]
My suspicion is that your script in `/etc/fish/config.d` is owned by root, and not readable by other users.

Could you show us the output of `ls -al /etc/fish/config.d` ?

**Comment by joedborg** [comment]
Hi @zanchey,
Do you mean `config.d` or `conf.d`?  The docs say `conf.d` http://fishshell.com/docs/current/index.html#initialization.

To check the permissions are correct, I have checked that I can list `conf.d` and cat `proxy.fish` as a normal user.

**Comment by joedborg** [comment]
Hi @zanchey,
Do you mean `config.d` or `conf.d`?  The docs say `conf.d` http://fishshell.com/docs/current/index.html#initialization.

To check the permissions are correct, I have checked that I can list `conf.d` and cat `proxy.fish` as a normal user.

**Comment by joedborg** [comment]
To further check, I've just tried to run `source` on the file as a normal user and it sources fine; just doesn't seem to happen on login.

**Comment by faho** [comment]
@joedborg: Do you have a file by the same name (i.e. "proxy.fish") in ~/.config/fish/conf.d?

>Do you mean config.d or conf.d?

Yes, it is "conf.d". More precisely, it is "$__fish_sysconfdir/conf.d".

What does `echo $__fish_sysconfdir/conf.d` output? That variable can be set at compile time, it's possible your configuration set it to something else.

**Comment by joedborg** [comment]
Hey @faho,
That's the issue.  `$__fish_sysconfdir` is set to `/usr/local/etc/fish`.  Just for reference, I just cloned the 2.3.1 tag, so I guess this was set by `./configure`?

Anyway, placing the script there works fine.  Thanks for the tip.

**Comment by faho** [comment]
I'm reopening this because the documentation is shitty.
