### ISSUE TITLE
Problem with Cmake  -D argument

### ISSUE THREAD

**Issue by FlavouredGeorge** [fish-shell/fish-shell#3292]
Hello,
I've noticed a problem which gave me a lot of problem until I realized it was coming from me using fish instead of bash.

When I ran the command "cmake –Daws-sdk-cpp_DIR=/path/to/file/aws-sdk-cpp-build ."
cmake did not "see" the path I linked with -D, I tried various other combinations (space before D, adding CMAKE_PREFIX_PATH="/path...etc" before the cmake command)... etc, none worked.

Once I switched to "bash" everything worked fine.

I'm not sure if this is a behavior inherent to fish and its problems with env variables exporting/sourcing stuff or if it is a problem with cmake. Anyway, I thought I should report it here since it was quite annyoing and for an inexperienced programmer like myself quite hard to figure out (ate a good 40+ minutes of my time trying to fuck around with the cmake argument and with the CMakeList.txt)

Is this an issue for fish ? Is it an issue with CMake which I should report there ? Is it just the way things are and I should really stop using fish and go back to a more established shell if I want my shell to work properly ?

**Comment by faho** [comment]
What was the path? Did it contain a variable (especially one that was unset)? Did it contain a "~"?

If you replace `cmake` with `echo`, does it output the correct thing?

**Comment by FlavouredGeorge** [comment]
The path was /home/user.name/AlphaProject/S3DownloadAndParsing/aws-sdk-cpp

The only thing weird about it is the ' . ' in the username and echo-ing it outputs the correct thing

echo /home/user.name/AlphaProject/S3DownloadAndParsing/aws-sdk-cpp
 /home/user.name/AlphaProject/S3DownloadAndParsing/aws-sdk-cpp

Is the output of the console

**Comment by faho** [comment]
The most likely way that fish gets in the way here is that it passes the wrong thing (or no thing at all).

Once cmake receives the arguments, fish's part in calling it is over.

So it stands to reason that, if this works with bash, but not with fish, that there's something wrong with how fish interprets the argument.

`echo` was probably a mistake on my part - that lets you see the argument, but not if it is split.

So, please see if `printf '%s\n' –Daws-sdk-cpp_DIR=/path/to/file/aws-sdk-cpp-build`, with the actual path filled in, prints exactly one line with exactly the text you'd expect. If it does, there's something very funky going on here. If it doesn't, you have probably misunderstood some of fish's syntax. In particular if it prints the text on more than one line you've probably missed a quote somewhere.

**Comment by faho** [comment]
One more thing is possible: Did you copy the invocation from e.g. https://aws.amazon.com/blogs/developer/using-cmake-exports-with-the-aws-sdk-for-c/? That particular site has a common web formatting mistake.

I'm gonna copy the exact text they have in their code block here:

```fish
cmake –Daws-sdk-cpp_DIR=<path to your SDK build> <path to your source>
```

In particular, the "–D" is _not_ the same thing as "-D", because the "–" is one of those fancy dashes - an em-dash or en-dash or something.

Additionally, it seems cmake doesn't mind and just ignores the argument.

**Comment by faho** [comment]
Yes, the actual code you pasted here has an en-dash. That won't work, and I don't think fish should do anything about it.

**Comment by floam** [comment]
I'd love for fish to syntax highlight en-dashes in the beginning of parameters with smso or something. It's a common mistake.

**Comment by FlavouredGeorge** [comment]
Yep, my keyboard dash is ' - ', the command I indeed copied and it has '  – '. I'm not in the position (not at that computer) to test it now but its true. Probably bash turned  the elongated dash into a normal one ? (I did use the exact same argument with bash)

**Comment by FlavouredGeorge** [comment]
Yep, can confirm, everything worked fine when I wrote the normal " - " dash and executed the exact same setps to make my project (all using fish)
