### ISSUE TITLE
Visual feeback when using pathname expansion with globs or braces

### ISSUE THREAD

**Issue by olivergondza** [fish-shell/fish-shell#3304]
Environment:
- fish, version 2.3.1
- rxvt-unicode (urxvt) v9.22 - released: 2016-01-23
- Linux arch 4.1.17-1-lts #1 SMP Mon Feb 1 16:35:08 CET 2016 x86_64 GNU/Linux

Fish provides visual aids while typing the pathname and pressing `<TAB>` by listing all possible matches. Bash, for instance, does that even when glob or `[...]` is used. This is great help to check what the expression is going to evaluate to before the command is started.

## Reproduction steps

In fish
```
$ mkdir test; cd test; touch 01 02 03 04
$ rm 0<TAB>
01  02  03  04
$ rm 0{1,2}<TAB> # No feedback
$ rm 0?<TAB> # No feedback
$ rm 0*<TAB> # No feedback
```

In bash
```
$ mkdir test; cd test; touch 01 02 03 04
$ rm 0<TAB>
01  02  03  04
$ rm 0[12]<TAB>
01  02
$ rm 0?<TAB>
01  02  03  04
$ rm 0*<TAB>
01  02  03  04
```

## Expected results

It would be great if fish can be as useful as bash in these cases.

**Comment by faho** [comment]
This is basically the same thing as #954. We need to improve completion (and possibly highlighting) for these expansions.
