### ISSUE TITLE
wildcard is not showing results for single directory using ls

### ISSUE THREAD

**Issue by danielb2** [fish-shell/fish-shell#3306]
**fish version installed** *2.3.1*:

**OS/terminal used**: 

iTerm

## Reproduction steps

```
$ ls 1.*
No matches for wildcard '1.*'.
fish: ls 1.*
         ^
$ mkdir 1.2.1
$ ls 1.*
$ ls -d 1.*
1.2.1
$ touch 1.3.1
$ ls 1.*
1.3.1

1.2.1:
$ ls -d 1.*
1.2.1 1.3.1
```

## Expected results
Should display the `1.2.1/` folder when it's the only match to the glob

## Actual results

Does not display the `1.2.1/` folder. Only displays the folder if there are other matches, such as another file or folder present. (example only shows with another file present, but another folder works too)

**Comment by faho** [comment]
It does expand to "1.2.1", only `ls` decides not to display anything because the directory is empty. You can confirm with `echo 1.*`.

bash behaves the same here.

**Comment by krader1961** [comment]
You have to actually have at least one file or directory inside `1.2.1` for the `ls` to display it. This has nothing to do with fish globs. You can reproduce your problem by simply typing `ls 1.2.1`. That's simply how `ls` behaves. You can see for your self after the `mkdir 1.2.1` that the glob is expanded by instead doing `echo 1.*`.
