### ISSUE TITLE
Code-sign OS X binaries before 10.12 is released

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#3308]
There have been requests before for us to code sign our binaries from security-minded users. But there will be more practical complications caused by our unsigned binaries sometime soon.

Applications and installers quarantined by GateKeeper (anything downloaded from the Internet, basically) in MacOS Sierra will refuse to run, and the system preference that enables one to bypass this requirement is gone. An identified developer registered with Apple's Developer program needs to code sign the binaries.

<img width="377" alt="screenshot 2016-08-18 at 12 13 51 am" src="https://cloud.githubusercontent.com/assets/291142/17765152/f25fc00e-64d8-11e6-82af-97032567d5d3.png">

It's possible to work around - it isn't to the point where the kernel is enforcing signatures across the board,  so one can remove the Quarantine bit in the xattrs, or signal intent by right clicking and doing an "Open" in Finder, or executing through Terminal.app after downloading, but I think we don't want that kind of experience for our users. 

There are good reasons to sign the binaries anyhow. Particularly if we're advocating adding to `/etc/shells`. It's a real benefit to our users for us to get this figured out, aside from saving them time during installation. 

I'm not sure who all on the team has a Developer ID from Apple and can sign binaries for distribution, but I can do it. I've been registered since 2007 or so. 

<img width="690" alt="screenshot 2016-08-18 at 12 13 05 am" src="https://cloud.githubusercontent.com/assets/291142/17765102/91d4deae-64d8-11e6-8ffb-c4ffce62046e.png">

**Comment by ridiculousfish** [comment]
The user experience today definitely sucks, but last I checked getting a code sign identity costs $100 a year. I wonder how other open source projects manage this - if they use a developer's personal account or something else.

**Comment by floam** [comment]
In my case it's something I pay for anyhow and there wouldn't really be any additional cost. 

A cursory survey of open source projects shows it's typically an individual developer footing the bill - or they don't code sign. I assume this is a bit like web hosting costs.

**Comment by floam** [comment]
Our glorious leader is now code signing the .app bundle.
