### ISSUE TITLE
Completions for P4

### ISSUE THREAD

**Issue by nomaed** [fish-shell/fish-shell#3311]
I am currently working on a completions file for Perforce (that's what we use at work).
I added most of the important commands that I use daily, but there are *a lot* of commands for Perforce, so I don't know when and if I'll finish them all.

Currently, it is very usable and handy:
https://github.com/nomaed/dotfiles/blob/master/completions/p4.fish

The reason for opening an issue is that I wonder whether you would be willing to accept a version that is still work-in-progress with placeholders for many of the subcommand options, or would you accept a pull request only after the entire thing is ready?

What is the process, in general? Anything specific that I should pay attention to?
(I did look at the contribution guide, but it's mostly focused on core c++ code contributions)

**Comment by zanchey** [comment]
I think we'd take a completion that is incomplete but functional - make sure you run your new file through `fish_indent`, which `make style` should do for you.

**Comment by nomaed** [comment]
Done, it passes.

Another question though.
Would it be possible to add an `.editorconfig` file in the root directory of the project? It has a very wide support, currently using plugins.

**Comment by zanchey** [comment]
Great. Do you want to make a PR? Or should I pull it from your repo?

> Would it be possible to add an .editorconfig file in the root directory of the project? It has a very good editors/IDEs support, although currently it's mostly using plugins.

I think we'd take a PR for that, although I don't use editorconfig.

**Comment by nomaed** [comment]
.editorconfig PR: #3313 
p4 completions PR: #3314 

Closing the issue.
