### ISSUE TITLE
Different command for invoking pager and expanding autocompletion?

### ISSUE THREAD

**Issue by sandric** [fish-shell/fish-shell#3315]
**fish version installed** _fish, version 2.3.1_

**terminal version** _iterm2_
## Reproduction steps

I wish to have one command for showing pager with available autocompletions and other for expanding preselected completion. Right now there's not very obvious algorithm to display available autocompletions as for me. There's notion of "in place" autocompletion,  that is printed right after your entered characters in command line, and "pager's autocompletion" which is showing all the autocompletions in list-like menu. While second one is pretty straightforward, first one dissects onto two types: 
- from "history" - your's entered characters matching against all history commands and if matchs exists - append last of those to your entered characters.
- from "autocompletion" - if there's only one autocompletion available in full completion list (the one that is displayed via pager) - it is appended to your characters.

But here's the problem. I can not distinguish by seeing "in place autocompletion" if there's other autocompletions available or not because this autocompletion can mean ether history one which is not eliminating availability of other completions, or "the last and only one" completion that mean that there's actually no such left.

And even biggest problem that if I think thats what I see in this "in place" completion is actually from history one, and trying to hit `<tab>` to see all available, if I was wrong and its "the only one left" completion, then it expands.
## Expected results

I want to have two different and understandable commands - one to see all available completions via pager, and other to expand "in-place", or "autosuggested" completion substituted by fish after characters I entered. Right now there's one command for both of those different actions - `<tab>` and one command `complete` defined [here](https://github.com/fish-shell/fish-shell/blob/93b9e7443e5e91e2908bfdc29c476c59b6765566/share/functions/__fish_shared_key_bindings.fish#L26).

To fix this I see the easiest way is to stop expansion on `<tab>` if there's only one completion exists and displaying it with pager as it should be done if there was more that one completion available. And leave expansion completion to `<end>` button (I can not find binding for it) which is also performs only one action - expands.

So can someone point me how can you disable this `<tab>` auto expansion in `complete` function if there's only one completion exists, and display it in pager instead?

**Comment by faho** [comment]
First some terminology:

>There's notion of "in place" autocompletion, that is printed right after your entered characters in command line

We call this the "suggestion".

>and "pager's autocompletion" which is showing all the autocompletions in list-like menu

What happens when you press TAB is the "completion". The pager shows them when there's more than one.

>[suggestion] dissects onto two types: 

And some more. AFAIK we at least also offer a file under certain circumstances.

And now for the answer:

Have you tried `bind \t complete-and-search`? This opens the pager immediately and starts searching. Press e.g. ESCAPE to get out of it.

**Comment by faho** [comment]
Sorry, that doesn't open the pager if there's only one result. Back to the drawing board on my answer.

**Comment by faho** [comment]
>I can not distinguish by seeing "in place autocompletion" if there's other autocompletions available or not because this autocompletion can mean ether history one which is not eliminating availability of other completions, or "the last and only one" completion that mean that there's actually no such left.

Why does this matter? Why do you want to know?

>And even biggest problem that if I think thats what I see in this "in place" completion is actually from history one, and trying to hit <tab> to see all available, if I was wrong and its "the only one left" completion, then it expands.

I can see how getting an expansion that you don't want and then having to undo it would be annoying. A keybinding to just delete the current token would help here, I think (I don't believe we have that yet). That's also more general - if you've e.g. gotten a line from history and want to change a token it would also be useful.

Try `bind \cg "commandline -rt ''"` (or another key combination of your choosing).

My issue here is that in general I believe expanding on the first press is the right thing (tm). For example I'll enter the first few characters of a file, until I think it's unambiguous. Then I'll press TAB to get the rest, and I'm done. If I had to press TAB, wait for the pager to show (well, a few milliseconds), and then ENTER, that'd obviously be slower. This seems to me to be the usual case.

Of course there _could_ be an option to do it differently, but we try not to do those. Though an additional function you could bind would be less of an issue than a variable or switch (think of `shopt`, and how much useful stuff is hidden behind it in bash).

**Comment by sandric** [comment]
@faho yes, I saw that and tried, the same logic there too(. I ended up reading [here](https://github.com/fish-shell/fish-shell/blob/9b5625a66bf81b798432c384260a150794db25a6/src/complete.cpp#L1440) but there's not very easy code and not very clear to me how pager specifically is called, and it took pretty much couple of seconds to compile all code on my old mac..

**Comment by sandric** [comment]
@faho I tried `bind \cg "commandline -rt ''"` and looks like it deletes all I entered before expansion but if I expanded - does nothing.
I trying this apart from what I described when I use pager in pure term, because I want to manage autodrop pager everytime I enter character in emacs term. And I did this by advising hook with entering tab everytime what I entered is simple character. As you can see thats working badly because of that autoexpanding if only one completion left..

**Comment by faho** [comment]
Okay, the right thing to do here is to add undo, so you can see what you got and then undo the expansion.

Closing in favor of #1367.
