### ISSUE TITLE
Fish gives warning at start on Haiku

### ISSUE THREAD

**Issue by miqlas** [fish-shell/fish-shell#3317]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations _(check `sh -c 'env HOME=$(mktemp -d) fish'`)_?

**fish version installed** _(`fish --version`)_:
2.3.1
**OS/terminal used**: 
Haiku gcc2h, hrev50498, with gcc 5.4.0

At starting fish in Haiku terminal i get the following:

```
socket: Address family not supported by protocol family
socket: Address family not supported by protocol family
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
```
## Reproduction steps

Hard to explain? Link to [a screen recording](https://asciinema.org)
1. Launch fish
2. Read the warnings
3. ???
4. Solve the warnings
5. Profit
## Expected results

Fish should not write warnings to the terminal.
## Actual results

```
~ $ math 2 + 2
```

4
(but just on my laptop, the real result could be something else, so no guarantee. The result here is under MIT license.

**Comment by zanchey** [comment]
I wonder if Haiku supports UNIX domain sockets? That would be the first thing to check.

**Comment by miqlas** [comment]
As far as i know Haiku supports Unix domain sockets.
Here is my actual recipe for fish: https://github.com/haikuports/haikuports/pull/776

**Comment by miqlas** [comment]
Yes, Haiku support the unix domain sockets: http://cgit.haiku-os.org/haiku/tree/src/add-ons/kernel/network/protocols/unix

**Comment by floam** [comment]
Can you run fish with `fish -d2 -D2` from git HEAD and share the output?

**Comment by floam** [comment]
It's got to be the crazy assumptions we make in `env_universal_common.cpp`. (interfaced is called "eth0"? Linux! "en0"? BSD!)

**Comment by floam** [comment]
I had noticed when debugging the issue with FreeBSD 11 that on that system (my interfaces were re0 if I used one driver, something else different with another) that this was failing, so it was falling back to having to use just the hostname for naming the uvar file. It seemed a bit of an assumption that it maps to the platform the way we hope:

https://github.com/fish-shell/fish-shell/blob/master/src/env_universal_common.cpp#L902-L930
```c++
// Linux
#include <net/if.h>
static bool get_mac_address(unsigned char macaddr[MAC_ADDRESS_MAX_LEN],
                            const char *interface = "eth0") {
    bool result = false;
    const int dummy = socket(AF_INET, SOCK_STREAM, 0);
...
}
// OS X and BSD
#include <ifaddrs.h>
#include <net/if_dl.h>
static bool get_mac_address(unsigned char macaddr[MAC_ADDRESS_MAX_LEN],
                            const char *interface = "en0") {
    // BSD, Mac OS X
    struct ifaddrs *ifap;
    bool ok = false;
}

```

**Comment by floam** [comment]
Though it seems it is just the preprocessor picking by `HAVE_GETIFADDRS`/`SIOCGIFHWADDR` and whatever we do when inside of `get_mac_address` itself is not OK on Haiku.

**Comment by miqlas** [comment]
floam, thanks for your help.
Have you seen my patch file for Haiku? Look here: https://github.com/miqlas/haikuports/blob/d4bb14e6a6ca5753759139f15197d4323fb23a85/app-shells/fish/patches/fish-2.3.1.patchset

**Comment by floam** [comment]
I hadn't.

**Comment by miqlas** [comment]
Ok, here is the fish -d2 -D2 output:

`
~/D/fish-shell ❯❯❯ /boot/home/Desktop/fishinst/bin/fish -d2 -D2 >log.txt
<2> fish: handle_curses() called in response to 'TERM' changing
<2> fish: Sorry, but your system does not support backtraces
<2> fish: curses var TERM='xterm'
<2> fish: Sorry, but your system does not support backtraces
<2> fish: handle_locale() called in response to 'LC_TIME' changing
<2> fish: Sorry, but your system does not support backtraces
<2> fish: locale var LC_TIME='hu.UTF-8'
<2> fish: Sorry, but your system does not support backtraces
<2> fish: handle_locale() setlocale(): 'hu.UTF-8'
<2> fish: Sorry, but your system does not support backtraces
<2> fish: handle_locale() called in response to 'LC_NUMERIC' changing
<2> fish: Sorry, but your system does not support backtraces
<2> fish: locale var LC_NUMERIC='hu.UTF-8'
<2> fish: Sorry, but your system does not support backtraces
<2> fish: handle_locale() setlocale(): 'hu.UTF-8'
<2> fish: Sorry, but your system does not support backtraces
<2> fish: handle_locale() called in response to 'LC_MONETARY' changing
<2> fish: Sorry, but your system does not support backtraces
<2> fish: locale var LC_MONETARY='hu.UTF-8'
<2> fish: Sorry, but your system does not support backtraces
<2> fish: handle_locale() setlocale(): 'hu.UTF-8'
<2> fish: Sorry, but your system does not support backtraces
<2> fish: handle_locale() called in response to 'LC_MESSAGES' changing
<2> fish: Sorry, but your system does not support backtraces
<2> fish: locale var LC_MESSAGES='hu.UTF-8'
<2> fish: Sorry, but your system does not support backtraces
<2> fish: handle_locale() setlocale(): 'hu.UTF-8'
<2> fish: Sorry, but your system does not support backtraces
<2> fish: handle_locale() called in response to 'LC_CTYPE' changing
<2> fish: Sorry, but your system does not support backtraces
<2> fish: locale var LC_CTYPE='hu.UTF-8'
<2> fish: Sorry, but your system does not support backtraces
<2> fish: handle_locale() setlocale(): 'hu.UTF-8'
<2> fish: Sorry, but your system does not support backtraces
<2> fish: handle_locale() called in response to 'LC_COLLATE' changing
<2> fish: Sorry, but your system does not support backtraces
<2> fish: locale var LC_COLLATE='hu.UTF-8'
<2> fish: Sorry, but your system does not support backtraces
<2> fish: handle_locale() setlocale(): 'hu.UTF-8'
<2> fish: Sorry, but your system does not support backtraces
<2> fish: 256 color support enabled for TERM=xterm
<2> fish: Sorry, but your system does not support backtraces
<2> fish: sourcing /boot/home/Desktop/fishinst/share/fish/config.fish
<2> fish: Sorry, but your system does not support backtraces
<2> fish: sourcing /boot/home/Desktop/fishinst/etc/fish/config.fish
<2> fish: Sorry, but your system does not support backtraces
<2> fish: not sourcing /boot/home/.config/fish/config.fish (not readable or does not exist)
<2> fish: Sorry, but your system does not support backtraces
socket: Address family not supported by protocol family
socket: Address family not supported by protocol family
<2> fish: 256 color support enabled for TERM=xterm
<2> fish: Sorry, but your system does not support backtraces
<2> fish: Fork #1, pid 8226: external command 'u' from '/boot/home/Desktop/fishinst/share/fish/functions/__fish_pwd.fish'

<2> fish: Sorry, but your system does not support backtraces
<2> fish: Fork #2, pid 8227: keepalive fork for 'echo "begin; $argv "\n" ;end <&3 3<&-" | source 3<&0'
<2> fish: Sorry, but your system does not support backtraces
<2> fish: Fork #3, pid 8228: internal builtin for 'echo'
<2> fish: Sorry, but your system does not support backtraces
<2> fish: Fork #4, pid 8229: external command '/' from '-'

<2> fish: Sorry, but your system does not support backtraces
<2> fish: Fork #5, pid 8230: internal builtin for 'command'
<2> fish: Sorry, but your system does not support backtraces
<2> fish: Fork #6, pid 8231: external command 's' from '<no file>'

<2> fish: Sorry, but your system does not support backtraces
<2> fish: Fork #7, pid 8232: external command 's' from '<no file>'

<2> fish: Sorry, but your system does not support backtraces
<2> fish: Fork #8, pid 8233: external command 's' from '<no file>'

<2> fish: Sorry, but your system does not support backtraces
`

**Comment by miqlas** [comment]
Yes, you have right, the interfaces could have different names.
In VmWare under Haiku it is :  `/dev/net/pcnet/0`. So yeah, it is a bit different than in the *nixes.

**Comment by ridiculousfish** [comment]
Cool, nice patch! Thanks for writing that!

The check for `__HAIKU__` can go away - the `MAP_FILE` one can be standard in `config.h` and the `p->ifa_addr` check can be used for all platforms.

**Comment by miqlas** [comment]
It is already committed: https://github.com/fish-shell/fish-shell/commit/a872d9c2991d814d5da2a27e8475de6e379973cc

But terer is something wrong with the IPV6 support in Haiku, and the warnings aren't nice at the start.

**Comment by zanchey** [comment]
Fixing the `MAP_FILE` issue will also help on Solaris/IllumOS (#3340).

**Comment by miqlas** [comment]
Any other idea about the warning? I'm just a bit tired about it.

**Comment by zanchey** [comment]
Can you show the current warnings? I imagine it's something along the lines of `socket: Address family not supported by protocol family` ?

**Comment by miqlas** [comment]
There is nothing else there.

**Comment by miqlas** [comment]
The warning happens here:
https://github.com/fish-shell/fish-shell/blob/master/src/fish.cpp#L210

In the latest haiku patch i just commented this line out. I know it isn't ideal, but it doesn't break anything, and it will never upstreamed.

Btw i'm all ears if somebody have better idea how to silence the wrnings.

**Comment by miqlas** [comment]
Okm Haiku supports only AF_UNIX SOCKS_STREA, but not the required SOCK_DGRAM. That not implemented yet, that's why i get the warnings at start.

See here: https://github.com/haiku/haiku/blob/master/src/add-ons/kernel/network/protocols/unix/unix.cpp#L435

**Comment by miqlas** [comment]
I think we can close this issue.

**Comment by ridiculousfish** [comment]
The socket code is super-old at this point and only used to detect old versions of fish running. I think we can remove it at this point. #3669 tracks removing it.

**Comment by miqlas** [comment]
Oh, thanks for the info, i had no idea, why this socket handling code required.
It would be great to not get warnings all the time if i start a terminal. it is just a bit disturbing.
Thanks again!
