### ISSUE TITLE
Jobs command prints a header for every line

### ISSUE THREAD

**Issue by JoshCheek** [fish-shell/fish-shell#3320]
**fish version installed**
2.3.1

**OS/terminal used**:
OSX 10.11.5
iTerm2 build 3.0.5

**Dotfiles**
https://github.com/JoshCheek/dotfiles/tree/67950cd6d38a8fe1ebf428cf2d16a47204e89701/fish
(shouldn't matter, I just tried it from `sh -c 'env HOME=$(mktemp -d) fish'` and saw the same behaviour)

**Description**
The `jobs` command prints a header for every line.

Consider the example below, the second command shows that every other line is `Job	Group	State	Command`, which is very distracting. I'd prefer it be like before where it just listed the arguments, similar to the bottom example (though I like the initial header). I'd also be okay with periodically adding the header, but having it on every other line is too noisy.

![screen shot 2016-08-21 at 11 23 14 pm](https://cloud.githubusercontent.com/assets/77495/17843658/4866d062-67f6-11e6-814b-ad701ab35154.png)

Here is the fish command I ran:

```sh
$ fish -c 'for _ in (seq 5); cat ^/dev/null &; end; jobs'
```

Here is the equivalent bash command:

```sh
$ bash -c 'for _ in `seq 5`; do cat 2>/dev/null & done; jobs'
```

**Comment by faho** [comment]
This has already been fixed by 9d2092bf9fa65450bb8a021c4ecd42af1b7bf11b.
