### ISSUE TITLE
VCS prompts occasionally print errors during terminal window resize

### ISSUE THREAD

**Issue by q-p** [fish-shell/fish-shell#3321]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations _(check `sh -c 'env HOME=$(mktemp -d) fish'`)_?

Does not occur with the (vcs less) default prompt

**fish version installed** _(`fish --version`)_: 2.3.1

**OS/terminal used**: Terminal.app in OS X 10.11.6 "El Capitan"

When using a vcs_prompt in a directory with a git-repository, while resizing the window, occasionally the following errors are printed on redraw. This looks a bit like a race-condition somewhere somehow...

```
~/t (master|✔)> (standard_in) 1: parse error
test: Missing argument at index 2
test: Missing argument at index 2
~/t (master|✔)> (standard_in) 1: parse error
test: Missing argument at index 2
test: Missing argument at index 2
~/t (master|✔)> test: Missing argument at index 2
~/t (master|✔)> (standard_in) 1: parse error
test: Missing argument at index 2
test: Missing argument at index 2
~/t (master|✔)> (standard_in) 1: parse error
test: Missing argument at index 2
test: Missing argument at index 2
~/t (master|✔)> (standard_in) 1: parse error
test: Missing argument at index 2
test: Missing argument at index 2
~/t (master|✔)> (standard_in) 1: parse error
test: Missing argument at index 2
test: Missing argument at index 2
~/t (master|✔)> test: Missing argument at index 2
~/t (master|✔)> test: Missing argument at index 2
~/t (master|✔)> (standard_in) 1: parse error
test: Missing argument at index 2
test: Missing argument at index 2
~/t (master|)> (standard_in) 1: parse error
test: Missing argument at index 2
test: Missing argument at index 2
```
## Reproduction steps
1. Launch fish
2. In fish_config, select a VCS prompt (I used informative_vcs)
3. `mkdir t`
4. `cd t`
5. `git init`
6. Quickly drag the window frame larger and smaller to trigger the output on redraw
## Expected results

Fish's vcs_prompt should just redraw the prompt, and not spew errors during resizing
## Actual results

```
~/t (master|✔)> (standard_in) 1: parse error
test: Missing argument at index 2
test: Missing argument at index 2
~/t (master|✔)> 
```

**Comment by faho** [comment]
>(standard_in) 1: parse error

This looks like something `bc` would print. We use that in `math`, which we only call in the git prompt if informative mode is enabled, i.e. $__fish_git_prompt_show_informative_status is set. Do you have that set? Does the issue still occur if you unset it?

I can't reproduce this on linux, so it's also possible that your `bc` is more annoying than mine. Can anyone on OSX reproduce this? @floam, @krader1961?

**Comment by q-p** [comment]
I see this problem with `Informative Vcs` from fish_config, but not `Classic + Vcs`, so it might have something to do with `informative`.

`bc --version` yields
```
bc 1.06
Copyright 1991-1994, 1997, 1998, 2000 Free Software Foundation, Inc.
```

**Comment by faho** [comment]
>bc 1.06
Copyright 1991-1994, 1997, 1998, 2000 Free Software Foundation, Inc.

I love apple's GPL3 policy. bc 1.06 is _actually_ from November 2000. Though bc development is almost dead, my version, bc 1.06.95 is from 2006.

This is also why we can't use $BC_LINE_LENGTH and instead resort to joining lines manually.

----

Anyway, I'm not quite sure what to do about it. We can just silence stderr (though we probably want to do it in the git prompt, not the `math` function because erroring when something's wrong is usually useful), but that would still cause the git prompt to act weirdly. With this, we could not determine if your state is dirty, so we'd invariably switch while you're resizing the term. Still probably better to default to one than writing errors everywhere, but not fantastic.

It's _possible_ this is related to #1949 - `bc` might think that stdin or stdout is a tty and therefore read $COLUMNS (or equivalent) and then determine that it's too small for in/output. Though we connected both ends of the pipe to builtins, so that'd mean we also forget to say it's not a tty in more cases than mentioned in that issue.

In any case, this is one more argument for making our own `math` builtin, see #3157.

**Comment by q-p** [comment]
The weird thing is that the error only occurs occasionally (i.e. when dragging the terminal window frame around wildly for 5 seconds, I get ~3 instances of the error), which smells like a bit of a race to me.

I've also never seen this on older (pre 2.3) versions of fish.

**Comment by faho** [comment]
@q-p: Please try 4e2d2c125c60518e7d4a2d17cb6eb694cd5dd442.

**Comment by q-p** [comment]
I now get less error spew; it no longer contains the `test` errors and looks like this
```
~/t (master|✔)> (standard_in) 2: parse error
~/t (master|✔)> (standard_in) 1: parse error
~/t (master|✔)> (standard_in) 2: parse error
~/t (master|✔)> (standard_in) 2: parse error
~/t (master|✔)> (standard_in) 2: parse error
~/t (master|✔)> (standard_in) 1: parse error
~/t (master|✔)> (standard_in) 2: parse error
~/t (master|✔)> (standard_in) 1: parse error
~/t (master|✔)> (standard_in) 2: parse error
~/t (master|✔)> (standard_in) 2: parse error
~/t (master|✔)> (standard_in) 1: parse error
~/t (master|✔)> (standard_in) 1: parse error
~/t (master|✔)> (standard_in) 2: parse error
~/t (master|✔)> (standard_in) 2: parse error
~/t (master|✔)> (standard_in) 1: parse error
~/t (master|✔)> 
```

**Comment by faho** [comment]
Okay, every single `math` call in the git prompt has now been silenced, That means every single math call in the informative+vcs prompt has also been, with the exception of one in the svn-prompt, which you most likely aren't triggering here.

So it seems those errors are coming from somewhere else. Do you have any customization that calls `math` or `bc`?

**Comment by q-p** [comment]
I don't think so, especially as I can repo in a clear environment (i.e. `sh -c 'env HOME=$(mktemp -d) fish'` followed by `fish_config` and selecting `Informative Vcs` prompt).

I'm running in a directory that only contains a git repository, not svn.

**Comment by faho** [comment]
Okay, there's something borked with our redirections. You can't actually redirect the `math` errors.

Try `math + >/dev/null ^/dev/null`.

That's #2927.

A workaround currently seems to be to add an option to `math` so that it does the redirection.

**Comment by q-p** [comment]
Yup, that doesn't redirect as expected
```
~/t (master|✔)> math + >/dev/null ^/dev/null
(standard_in) 1: parse error
~/t  (master|✔) [1]> 
```

**Comment by faho** [comment]
This is not a thing anymore with the shiny new math builtin.
