### ISSUE TITLE
Improve the fish_config/bindings page

### ISSUE THREAD

**Issue by jinliu** [fish-shell/fish-shell#3325]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(2.3.1)*:

**OS/terminal used**: archlinux / konsole

I'd like to make some changes to the "bindings" page.

Rationale:
The purpose of this page is for end user to discover fish keybindings, not for technical details ("bind" command is for that).

1. Remove information useless to end user.
Example:
self-insert	''
'begin;end'

2. Group together different keybindings to the same command. Merge char sequences that shown as the same key.
Example:
Five duplicate nextd-or-forward-word	ALT - Right Arrow

3. Fix obvious key name errors:
Example:
execute	r (should be \r, or simply remove this line as the user probably doesn't know how to input \r)
backward-delete-char	 (incorrect handling of backspace)
end-of-line	~ (incorrect handling of control sequence)

**Comment by floam** [comment]
I agree. It's hard to read that and understand what you need to press to cause what.

We could perhaps leave the raw commands in a tooltip, else able to be toggled and/or with a "copy raw `bind` command to clipboard" button. Non-developers still might use that as a launching point to modify bindings, not just for help discovering them.

**Comment by floam** [comment]
Wow - I just noticed that we actually already have some kind of toggle action I never before noticed. Clicking "Right Arrow" flips it to `right` in a way that is really confusing. 

This should be made obvious with some kind of hint as to what clicking will do and that you can click, by changing the pointer and maybe displaying some indication.

The font could be sans-serif for the friendly text and monospaced for the raw commands.

Another thought is that `fish_key_reader` could benefit from having access to the same simple names.

**Comment by floam** [comment]
.. and that weird toggling only seems to apply to the `bind -k` commands (I think), not others that were simplified.

**Comment by floam** [comment]
Marking bug and enhancement as there are bugs outlined above and also proposed enhancements. 👍if you'd like to take a swing at improving the experience and fixing stuff!

**Comment by jinliu** [comment]
> Wow - I just noticed that we actually already have some kind of toggle action I never before noticed. Clicking "Right Arrow" flips it to right in a way that is really confusing.
> This should be made obvious with some kind of hint as to what clicking will do and that you can click, by changing the pointer and maybe displaying some indication.
> The font could be sans-serif for the friendly text and monospaced for the raw commands.

For that purpose, I think it's better to show raw commands (instead of the -k keyname). E.g.
nextd-or-forward-word ALT - Right Arrow
(click some down arrow to expand into:)
bind \e\eOC nextd-or-forward-word
bind \e\e\[C nextd-or-forward-word
bind \eO3C nextd-or-forward-word
bind \e\[3C nextd-or-forward-word
bind \e\[1\;3C nextd-or-forward-word
bind \e\[1\;9C nextd-or-forward-word

**Comment by floam** [comment]
Yep, totally.

**Comment by faho** [comment]
Fixed by merging #3326.
