### ISSUE TITLE
Regression: the "Filter" box in the "bindings" tab of fish_config has no effect

### ISSUE THREAD

**Issue by jinliu** [fish-shell/fish-shell#3328]
Commit bfee664 broke the "Filter" box in the "bindings" tab of fish_config.
The problem is caused by the above commit changing the structure of json data passed to the web page, breaking the filter code.
The original structure:
```
[
{"command":"up-or-search", "readable_binding":"Up Arrow", "binding":"up", "description":null},
{"command":"up-or-search", "readable_binding":"CTRL - p", "binding":null, "description":null},
...
]
```
New structure:
```
[
{"command":"up-or-search", "description":null, 
   "bindings": [
    {"readable_binding":"Up Arrow", "raw_bindings": ["bind \e\[A up-or-search", "bind -k up up-or-search"]},
    {"readable_binding":"CTRL - p", "raw_bindings": ["bind \cp up-or-search"]}
    ]
},
...
]
```
Bindings to the same command are grouped together.

## Reproduction steps

1. fish_config
2. In the "bindings" tab, type "kill" in the "Filter" box

## Expected results
Only those commands containing "kill" shown.

## Actual results
All commands shown.

**Comment by floam** [comment]
Thanks - I merged it
