### ISSUE TITLE
--no-execute detects an error even it's correct syntax

### ISSUE THREAD

**Issue by yuutayamada** [fish-shell/fish-shell#3330]
- [X] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [X] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
I checked with git version (fish, version 2.3.1-483-g476ffe1)

**OS/terminal used**: 
Ubuntu16.04 LTS/urxvt

Talk about the the issue here. 

when I checked `fish -n foo.fish`, which has only `abbr -a gco git checkout`,
the command output:
```sh
$ fish -n foo.fish                                                                           (master ⚡↑) 
foo.fish (line 1): abbr -a gco git checkout                                                (master ⚡↑) 
                   ^
```

I copied the `abbr -a gco git checkout` from example section of `man abbr` and
it seems working fine. (I tried to type gco and it was expanded correctly)

## Reproduction steps
1. make a file (foo.fish) with following content:

   ```sh
   abbr -a gco git checkout
   ```
2. Launch fish
3. do `fish -n ./foo.fish`

## Expected results
Fish should not detect the error

## Actual results
```sh
$ fish -n foo.fish                                                                           (master ⚡↑) 
foo.fish (line 1): abbr -a gco git checkout                                                (master ⚡↑) 
                   ^
```

**Comment by faho** [comment]
What fish is complaining about here is that it can't find anything by that name because it's a function. $fish_function_path is defined in a script which is also not executed, so fish can't know which functions exist in this mode.

We should probably just stop checking that (since we can never get the user's full function path without executing anything).

**Comment by faho** [comment]
This has already been reported as #977 (though it's weird that it now only prints the line and marker, not the actual message).
