### ISSUE TITLE
Make string commands available as top-level builtins?

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#3349]
In #3348, @floam said:

> I wish maybe I had considered how many times I'd type out "string match", "string split" int the future and >realized when this was on the drawing board it'd get very tiring for human hands (how often do you use `string >match`  interactively instead of `grep`?), and noticed that it's not really the best possible addition to our >language. It seems obvious to me in hindsight that most of these could have just had `string` omitted: 
> 
> ``` fish
> echo a b c d | string join '-'
> 
> echo a b c d | join '-'
> ```
> 
> ``` fish
> string match (uname) "Linux"
> 
> match (uname) "Linux"
> ```
> 
> Too bad. abbr can help. 
> 
> I mean: string escape $x: what else are you going to escape in a shell other than a string most days? Shells deal with strings.

Is this something we want?

One obvious counter is that these names are really generic and some of them might be used by something else.

In my simple search I found that `join` and `split` are in both GNU coreutils and plan9port, while mysql for some reason has a `replace` command. `match` is in an implementation of the logo educational programming language called "ucblogo".

This would mean that every user trying to launch these commands would need to specify `command replace` or `command match`. OTOH these things seem to be reasonably obscure (I always forget that "join" exists, and that's probably the most useful of these).

**Comment by floam** [comment]
`join` could be seen as more generic than `string join`, or `fish_join_tool`, but I think it's clearly more concise and specific - which isn't something you normally think of as a defining characteristic of a overly-generic term. I'll point out that both he coreutils and plan9 split are actually not kickass utilities for chopping up strings at the command-line, but for splitting large files up in a way that can be recombined later (to fit in emails and on floppies?).

**Comment by krader1961** [comment]
I used to use the external split and join commands pretty regularly. Now it's a handful of times a year, if that. Still, I think we want as few builtins as we can get away with while still providing a useful shell. Anyone who wants to avoid the `string` prefix when using them interactively can simply do `abbr join 'string join'`, etc. And if they want to use the short form in non-interactive situations simply create auto-loaded functions such as `function join; string join $argv; end`. Given the fish architecture I think the current implementation strikes the right balance while easily allowing people who dislike the verbosity to avoid it. We might even want to document this on the `string` man page for newcomers who are annoyed by the verbosity but whom don't immediately recognize how to eliminate it.

**Comment by floam** [comment]
> ` function join; string join $argv; end 

That'd be a terrible practice, and obviously would prevent anyone from understanding your code. In an ideal world, the language would have at least named them `string-match`.  Isn't it kind of odd to be invoking what are logically 5 heavy duty builtin functions by calling a builtin that only servers to group them together and display help output, by calling it  them with a first argument that selects the desired builtin?  It feel like a tool in my $PATH more than a first class language feature - the parser can't even make the "replace" be colored like a builtin. It's not one. It's goofy!

Was there original some plans for some kind of global options that one might use on just `string` by itself that might later affect the other builtins? I guess that'd make sense.

**Comment by krader1961** [comment]
I am strongly opposed to this proposed change. If for no other reason than the `string` builtin has now existed long enough that we have support it at least until the next major release. And I see very little value in making its subcommands top level commands. Too, the arguments for making the `string` subcommands top level commands also apply to `status`, `history`, etc. As I said earlier minimizing the number of builtin top level commands should be a highly valued goal for a command shell like fish as it minimizes the likelihood of collisions with the available external commands.

**Comment by faho** [comment]
@floam: Okay to close?
