### ISSUE TITLE
completion for `cd -`

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#3353]
I've started trying to use the directory history feature. The provided nextd and prevd would be more likely to be noticed if they were named cdnext and cdprev, because they'd appear as completions for `cd`.

~~Also, the completions seem to include something that doesn't work: "-/":
![http://i.imgur.com/pVFmjHK.png](http://i.imgur.com/pVFmjHK.png)~~

**Comment by floam** [comment]
> Also, the completions seem to include something that doesn't work: "-/":

Yeah, this happens if you have a directory called '-' in ~.

**Comment by floam** [comment]
Actually, bad idea, now cd<TAB> wouldn't show directories in $PWD. The right way to expose this is adding a completion for `cd -` with a description saying it will take you back a directory (it could show what that directory is for bonus points).

Which then make you wonder: why doesn't cd - work like an abbr and just place the path into the command line?

**Comment by krader1961** [comment]
> adding a completion for cd - with a description saying it will take you back a directory. 

Seems reasonable.

> why doesn't cd - work like an abbr and just place the path into the command line?

How would that work? Abbreviations are simple substitutions. Unlike functions there is no possibility of executing commands. Furthermore, it's not obvious to me that I'd want `cd /path/to/prev/directory` in the history rather than `cd -`.

**Comment by floam** [comment]
>  Furthermore, it's not obvious to me that I'd want cd /path/to/prev/directory in the history rather than cd -.

The idea would be that you'd know where you're going before hitting enter. The completion description could also help here (if you hit tab).

**Comment by floam** [comment]
( Of course, the argument against what I asked is: ' "~" doesn't do that, why should "-"?  ')

**Comment by floam** [comment]
I'm reopening this - the completion is kind of problematic IMO.

**Comment by floam** [comment]
I'm not sure this would be the right approach to try to do this from fish script - there's C++ involved too.

For me right now i's completing directly to `-` from `cd<TAB>` when there are no other directories - it should be an equal sibling to "..". Also, it's literally sticking a `-` in the command line and closing the pager, instead of letting me browse and "change into it" like the others. 

The way it's showing a clue that it will take you somewhere is kind of jarring. For one thing it can make the columns wider: 

[Completion for -](http://i.imgur.com/iJjNMUB.png)

There might just be a bug - but aside from that: How about make it act more like a symbolic link, and look more the way something might look if you added a decoration to an entry in`ls -F` output. I don't think we want the normal description design here (or typical long-winded descriptive labels).

**Comment by floam** [comment]
It strikes me that the progress bar "... and 32 more rows" is pretty wide. It should probably accommodate showing the entire description for a highlighted completion. That'd let us have them turned off for `cd` like we (did) or turn it off it more areas. Would obviously help here.

**Comment by faho** [comment]
>The way it's showing a clue that it will take you somewhere is kind of jarring. For one thing it can make the columns wider.

Well, what we can do here is shorten it a bit. Try

```fish
function __fish_complete_previous_dir
    set -l dir
    if test "$__fish_cd_direction" = "next"
        set dir $dirnext[-1]
    else
        set dir $dirprev[-1]
    end
    if set -q dir[1]
        set dir (string replace -r '.+(.{50})$' '…$1' -- $dir)
        printf '%s\t%s\n' - "Previous dir: $dir"
    end
end
```

where "50" is a completely arbitrary number. In contrast to the git completions, we trim from the beginning, since that's more likely to be the same. Or we could shorten like we do for `prompt_pwd` with `string replace -ar '(\.?[^/]{'"$fish_prompt_pwd_dir_length"'})[^/]*/' '$1/'`. We should probably not use the variable here. Ideally we'd use the maximum value that lets us stay inside a certain limit.

**Comment by floam** [comment]
Unless we can do it without `--description` I don't think we can keep it from wasting columns, I believe  `pager.cpp` will always try to give it a certain fraction.

**Comment by floam** [comment]
![Imgur](http://i.imgur.com/r1DKEmm.png)

I think we'd want to be like ~20 characters fewer, maybe better to just not to fulfill my request for the completion.

**Comment by faho** [comment]
Okay, so what should this look like? Should we put the actual directory there, maybe trimmed somehow to keep a certain length? Or do we just want "Go back" or something?

**Comment by jcpetkovich** [comment]
Having a completion for `-` sounds like a good idea at first, but in practice having it as the first option in the list of directories is kind of bad/irritating. It's the wrong "first" completion about 90% of the time. I'm for the completion if it isn't put right at the top of the list.

**Comment by onodera-punpun** [comment]
@jcpetkovich I agree, not only do I need to press tab one more time *every time* I try to autocomplete cd, I've also selected `-` by accident a few time, which completely destroys my "flow" and takes a few seconds to recover from since my initial reaction is to use alt-left.

**Comment by ridiculousfish** [comment]
I reverted the "cd -" completion as eeea3f3b3c07dc91d6fdc30989022b4c836d9987. Let's reintroduce it once we understand some of the unintended consequences and UI issues. (In its current state, it was driving me 🍌🍌🍌.)

**Comment by krader1961** [comment]
I recommend closing this. There really isn't enough value IMHO to warrant implementing this. And the experience from the first attempt shows that doing this is annoying. As @onodera-punpun wrote above if someone wants `cd -` they a) know they want it and b) know where it will take them. It's fundamentally different from typing `cd prefix<tab>` to quickly select a long path.

**Comment by faho** [comment]
Agreed, closing.
