### ISSUE TITLE
git clone is no more working

### ISSUE THREAD

**Issue by M5oul** [fish-shell/fish-shell#3356]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
2.3.1
**OS/terminal used**: 
Fedora 24 with GNOME Terminal

### Issue
- `git clone` is no more working via https and ssh:
```fish
git clone git@gihub.com:/YunoHost/package_linter.git
Clonage dans 'package_linter'...
```
I wait a long time like that.

- it works with  `sh -c 'env HOME=$(mktemp -d) fish'` and with bash.
- it don't think it comes from the conf file, I moved `~./config/fish/conf.fish`, and restarted the shell, it's the same.

**Comment by krader1961** [comment]
Fish doesn't automatically read *~/.config/fish/conf.fish* so I'm not surprised that renaming that file didn't affect the behavior. It does read *config.fish* in that directory. Was that a typo, @M5oul? The fact that telling fish to use an empty user config directory strongly implies a customization you've made is the cause of the problem. What does `type git` output? Does running git clone in verbose mode, `git clone -v`, provide any hints as to where it is stuck? When you say "is no more working" you're implying it was working at some point in the past. Any idea what you changed between when it was working and now? Did you upgrade fish? Edit your fish config?

**Comment by M5oul** [comment]
```fish
type git
git is /usr/bin/git
```
git clone verbose say nothing.

Yep, it was working, I added configuration, then removed it.
I don't remember exactly what did I do.
I put some `export` things which wasn't working.
Then, now, I still have some `set -x` confs:
```bash
cat ~/.config/fish/conf.fish
# Sakia
## Python path
set -x PYTHONPATH /home/moul/projects/sakia_dev/src

# Duniter
#set -x DUNITER_DIR /home/moul/projects/duniter
#set -x DEV_MODE yes
#source $DUNITER_DIR/duniter.sh
```

I did not upgrade fish. Started from 2.3.1.

**Comment by faho** [comment]
>cat ~/.config/fish/conf.fish

That won't work. Usually I'd say you've made a typo, but this is the second time. The fish configuration file is `~/.config/fish/config.fish`. Please check again that you are using that path, not "conf.fish".

Additionally, we read some files in ~/.config/fish. Can you post those files or move them out of the way one by one? Since you haven't made a function named git, you're actually executing the `git` binary directly. 

This tells me the most likely cause is some variables you've set. This means you've either still got a `set` call in one of your configuration files, or you have something in your universal variables. The output of `env` would be useful.

**Comment by M5oul** [comment]
- Yep, sorry, It's well `config.fish`.

In `~/.config/fish`, there is `fishd.moulinette` file which contains:
```fish
# This file is automatically generated by the fish.
# Do NOT edit it directly, your changes will be overwritten.
SET __fish_init_1_50_0:\x1d
SET __fish_init_2_3_0:\x1d
SET fish_color_autosuggestion:555\x1eyellow
SET fish_color_command:005fd7\x1epurple
SET fish_color_comment:red
SET fish_color_cwd:green
SET fish_color_cwd_root:red
SET fish_color_end:green
SET fish_color_error:red\x1e\x2d\x2dbold
SET fish_color_escape:cyan
SET fish_color_history_current:cyan
SET fish_color_host:normal
SET fish_color_match:cyan
SET fish_color_normal:normal
SET fish_color_operator:cyan
SET fish_color_param:00afff\x1ecyan
SET fish_color_quote:brown
SET fish_color_redirection:normal
SET fish_color_search_match:\x2d\x2dbackground\x3dpurple
SET fish_color_selection:\x2d\x2dbackground\x3dpurple
SET fish_color_user:green
SET fish_color_valid_path:\x2d\x2dunderline
SET fish_greeting:Bienvenue\x20dans\x20fish\x2c\x20le\x20shell\x20amical\x20et\x20interactif\x0aTapez\x20\x1b\x5b32mhelp\x1b\x5b30m\x1b\x28B\x1b\x5bm\x20pour\x20des\x20instructions\x20sur\x20l\x27utilisation\x20de\x20fish
SET fish_key_bindings:fish_default_key_bindings
SET fish_pager_color_completion:normal
SET fish_pager_color_description:555\x1eyellow
SET fish_pager_color_prefix:cyan
SET fish_pager_color_progress:cyan
```

I removed it, started new fish shell, still, I can't clone.

### Env
```fish
env
COLORTERM=truecolor
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
DESKTOP_AUTOSTART_ID=10daf689fea127cebb147315800751397500000017200002
DESKTOP_SESSION=gnome-wayland
DISPLAY=:0
GDMSESSION=gnome-wayland
GDM_LANG=fr_FR.UTF-8
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
HOME=/home/moul
LANG=fr_FR.UTF-8
LOGNAME=moul
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:
PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
PWD=/home/moul/.config/fish
QT_IM_MODULE=ibus
QT_QPA_PLATFORMTHEME=qgnomeplatform
SESSION_MANAGER=local/unix:@/tmp/.ICE-unix/1720,unix/unix:/tmp/.ICE-unix/1720
SHELL=/usr/bin/fish
SHLVL=1
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
TERM=xterm-256color
USER=moul
USERNAME=moul
VTE_VERSION=4402
WAYLAND_DISPLAY=wayland-0
XDG_CURRENT_DESKTOP=GNOME
XDG_MENU_PREFIX=gnome-
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_SESSION_DESKTOP=gnome-wayland
XDG_SESSION_ID=2
XDG_SESSION_TYPE=wayland
XDG_VTNR=2
XMODIFIERS=@im=ibus
```

**Comment by faho** [comment]
Okay, it's actually much simpler. Read your commandline again:

`git clone git@gihub.com:/YunoHost/package_linter.git`.

**gihub.com**.

Most likely you've typed it correctly in bash and the new fish.

**Comment by M5oul** [comment]
If fact, thanks, it works.
I am very sorry for the invalid bug report.
That auto-completion is so good :+1: that I didn't check what's written :smile:

**Comment by faho** [comment]
No worries, we also missed it at first. Also, we allow questions here, so it's not a problem.
