### ISSUE TITLE
"changeWorkingDirectory: does not exist"

### ISSUE THREAD

**Issue by chris-martin** [fish-shell/fish-shell#3359]
This morning I upgraded to NixOS 16.09 and got Fish 2.3.1.

Every time I run `ls`, I get this message:

```
chris@renzo ~> ls
test: testcases: changeWorkingDirectory: does not exist (No such file or directory)
desktop  documents  downloads  pictures
```

I've also tried switching over to bash and zsh and confirmed that this only happens with fish.

**Comment by faho** [comment]
First we need to see what `ls` is actually running. The output of `type ls` is great for that.

Secondly, there's no occurence of the string "changeWorkingDirectory" in our entire repository. Any idea where that came from?

I know Nix has a bunch of changes to make fish integrate with that "functional" package management stuff they do, so it might be possible it's there. Can you look through the files belonging to your fish package for that string?

**Comment by chris-martin** [comment]
```
chris@renzo ~> type ls
ls is a function with definition
test: testcases: changeWorkingDirectory: does not exist (No such file or directory)
function ls --description 'List contents of directory'
    set -l param --color=auto
    if isatty 1
        set param $param --indicator-style=classify
    end
    command ls $param $argv
end
```

**Comment by chris-martin** [comment]
The stnirg `changeWorkingDirectory` also doesn't appear anywhere in the Nix package repo, nor anywhere in my home directory. So... that's strange.

**Comment by faho** [comment]
How about "testcases" then? We also don't have that.

**Comment by krader1961** [comment]
Given that this happens with both your `ls` function and the `type` function, and both of them invoke `isatty 1` at the point the unexpected error message is seen, and the `isatty` function has exactly one `test` invocation:

```
command test -t "$fd"
```

I'm willing to bet if you run that by hand (replace the `"$fd"` with `1`) you'll see that error.

**Comment by chris-martin** [comment]
I think this is an exception thrown from something written in Haskell.

https://hackage.haskell.org/package/unix-2.7.2.0/docs/System-Posix-Directory.html#v:changeWorkingDirectory

**Comment by faho** [comment]
There's a bunch more code being run here, to set $LS_COLORS, but it should only be executed when "ls.fish" is sourced ,i.e. when the `ls` function is autoloaded. Can you confirm that this happens twice when you run `ls` twice in one shell? If not, please execute this in a new shell _before executing `ls`_:

```fish
set -q LS_COLORS; or echo "LS_COLORS unset"
type dircolors
type sed
```

**Comment by krader1961** [comment]
Do you get the error if you run `command test -t 1`?

**Comment by chris-martin** [comment]
@krader1961 you're right about that:

```
chris@renzo ~> command test -t 1
test: testcases: changeWorkingDirectory: does not exist (No such file or directory)
```

Though I don't know what that means.

**Comment by krader1961** [comment]
It means your `test` program is broken.

**Comment by chris-martin** [comment]
My `test` program is something from `hasktags`. What do you expect it to be?

```
chris@renzo ~> which test
/home/chris/.nix-profile/bin/test
chris@renzo ~> stat /home/chris/.nix-profile/bin/test
  File: '/home/chris/.nix-profile/bin/test' -> '/nix/store/p8pk8dr2gm015vy9ykmcf1mp54k3mx81-desktopEnv/bin/test'
  Size: 63              Blocks: 8          IO Block: 4096   symbolic link
Device: fe01h/65025d    Inode: 1451600     Links: 1
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-09-07 13:40:35.011436322 -0400
Modify: 1969-12-31 19:00:01.000000000 -0500
Change: 2016-09-07 13:40:34.977435732 -0400
 Birth: -
chris@renzo ~> stat /nix/store/p8pk8dr2gm015vy9ykmcf1mp54k3mx81-desktopEnv/bin/test
  File: '/nix/store/p8pk8dr2gm015vy9ykmcf1mp54k3mx81-desktopEnv/bin/test' -> '/nix/store/vxygsqw2li9i1q99k6jq5yb4crvby4jl-hasktags-0.69.2/bin/test'
  Size: 68              Blocks: 8          IO Block: 4096   symbolic link
Device: fe01h/65025d    Inode: 2902332     Links: 3
Access: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2016-09-07 13:40:34.357424975 -0400
Modify: 1969-12-31 19:00:01.000000000 -0500
Change: 2016-09-07 12:26:03.678044883 -0400
 Birth: -
```

**Comment by faho** [comment]
Something from coreutils.

**Comment by krader1961** [comment]
> What do you expect it to be?

No idea. I've never used NixOS and I don't recall any of the other fish devs saying they use it. You'll probably get better help with that question from the NixOS community.

**Comment by chris-martin** [comment]
Okay, I'm guessing that `test` being in the bin output for hasktags is a mistake. I'll take this issue elsewhere. Thanks a ton for the support, y'all.
