### ISSUE TITLE
When you attempt to tab complete a brew command an error is thrown

### ISSUE THREAD

**Issue by Nocturnhabeo** [fish-shell/fish-shell#3360]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.3.1

**OS/terminal used**: OSX 10.11.6 El Capitan 

When I try to tab complete `brew install kali` it fails with: 
     No matches for wildcard '$formuladir/*.rb'.
     /usr/local/Cellar/fish/2.3.1/share/fish/completions/brew.fish (line 3):     ls $formuladir/*.rb | sed 's/.rb$//' | sed "s|^$formuladir||"
                                                                               ^
      in function '__fish_brew_formulae'
	     called on standard input

in command substitution
	 called on standard input

## Reproduction steps
1. type brew install kali
2. hit tab

**Comment by Nocturnhabeo** [comment]
I can't get the error message the format correctly but the ^ is pointed to the $formuladir

**Comment by faho** [comment]
This should already be fixed by #3309.

**Comment by floam** [comment]
Homebrew should probably want to backport that change in master for their package. @Nocturnhabeo if you want to file an issue there this might get it fixed quicker for you (and others) on 2.3.1
