### ISSUE TITLE
Allow customizing `history -t` formatting?

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#3361]
While working on #3333, which adjusted the default output of the `history` builtin, @krader1961 mentioned an obvious downside: it halves the number of results one can see on screen at a time. 

Certainly it would sometimes be preferable to use a different format - I sometimes would like a super-narrow  `date  +"%a%I%p"` format myself -- but it can't be default and I don't always want that. A low-effort solution would be for us to add an optional parameter to `-t`, which is a string with a `strftime` format specification in it.

In addition to accommodating any date format and allowing for the timestamp to be on the same line or on a different line in the output (just omit the ending "\n"), this also should allow for the raw unix timestamp to be accessed (through the `%s` format specifier) which should likely be wanted if one is parsing the output with unix utilities:

```console
> history --with-time="%s\t"
1473309769	open -a xcode-beta -s OSX10.12 -h cwchar
1473309709	man strnvisx
```

It *could* default to `# %Y-%m-%d %H:%M:%S \n` to match the current output --  but does anyone have any suggestions on how to improve what we went with? With the format being able to be specified for specialized uses a different default could be justified.

Thoughts appreciated.

**Comment by krader1961** [comment]
I'm going to go ahead and implement this so we can make improving `history` a theme of the 2.4.0 release. I propose replacing the current default with `%c`. I don't like that format when used in situations where a fixed-length string is needed (e.g., when including the timestamp as a prefix to each history entry) but it's perfectly reasonable as `--with-time='# %c\n'`.

**Comment by floam** [comment]
Should we add  a "%cmd" or something so it's obvious where the command will be in the format?

**Comment by floam** [comment]
(And possible to not just have it at the end).

**Comment by krader1961** [comment]
> Should we add a "%cmd" or something so it's obvious where the command will be in the format?

That strikes me as something that is unlikely to ever be used. It would also greatly complicate the implementation which seems hard to justify given that it seems unlikely to be used by anyone.

**Comment by floam** [comment]
The main use case I was thinking of, is it could be useful to be able to do this:
`history --with-time="- cmd: .%{cmd}\n    when: %s\n" ... `

This would generate a history file matching a search, or without arguments it'd essentially export the history (sans paths, unfortunatelyl... for now). 

Also, if a user wanted to right-align the date (or just have it trail the commands) it'd be easier having the order not hard-coded.

**Comment by krader1961** [comment]
Being able to abuse `--show-time` (or the soon to be legacy `--with-time`) flag to produce pseudo YAML output is a really bad idea not least because it's fragile. If that's deemed useful we should add a `--yaml` flag.

> Also, if a user wanted to right-align the date (or just have it trail the commands) it'd be easier having the order not hard-coded.

I think you're wrong. If the user is going to pipe the output through some history formatting program to extract the timestamp and do something with it the simplest, easiest, solution is `--show-time='%s '` then you just split the first word from the rest of the output. Of course either solution suffers from the problem we currently have that you can't ask for multi line history entries to be formatted in a manner that allows them to be unambiguously parsed when written by `history search`. Which is similar to the issue with most definitions of CSV format.

**Comment by floam** [comment]
You're probably right - it won't escape characters the same, that's for sure.

**Comment by floam** [comment]
The first reason why it'd be much better with a format string @krader1961 is because history can be really long and, and fish buffering is no fun. The performance aspect here would be pretty compelling. I didn't imagine the user piping out to get them right aligned - they'd do that in the format string itself. (My imagined implementation would use GNU/BSD extended printf to do the replacement).

I figure it could make it easier to alter the output for multiline entries to get picked up by our fish as well.

**Comment by floam** [comment]
>  I didn't imagine the user piping the output to get them right aligned though - they'd do that in the format string itself.

If it isn't obvious, printf is the key to like the easiest way to right align stuff in a shell I've come up with:
```
# no need to sanity check COLUMNS - in no case will printf truncate - and fish gives 0 here if not in a TTY.
printf '%*s' $COLUMNS "this is right-aligned"
```

**Comment by krader1961** [comment]
@floam, I am not going to overload the `--show-time` flag. Even if we did so it wouldn't allow you to reliably extract the timestamp and right align the value on the user screen. Please drop it.
