### ISSUE TITLE
Command not found handler is broken in openSUSE Tumbleweed

### ISSUE THREAD

**Issue by vovams** [fish-shell/fish-shell#3366]
When i type a command which is not installed in my system into fish command prompt, i get this:

```
vovams@vovams-s-comp ~> foo
--: searching ...Cannot not open database file '/usr/share/scout/bin-foo.db'
--: command not found                   
```

I have fish 2.3.1 and openSUSE Tumbleweed 20160907.

This issue has already been discussed in #1570 and #1208 and fixed in a previous version of fish. However, the fix relied on distribution detection using `/etc/SuSE-release`. That file does not exist in my system anymore. After some googling i found that a while ago the content of that file was like following for someone:

```
openSUSE 20151030 (x86_64)
VERSION = 20151030
CODENAME = Tumbleweed
# /etc/SuSE-release is deprecated and will be removed in the future, use /etc/os-release instead
```

So, i think a recent Tumbleweed update finally removed this file. The content of `/etc/os-release` on my system is as follows:

```
NAME="openSUSE Tumbleweed"
# VERSION="20160907"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="20160907"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20160907"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```

**Comment by faho** [comment]
We should probably read os-release for this. The question is if there's any other place where we could use it and if we want to use ID or ID_LIKE.

From the os-release man page:

```man
   ID=
       A lower-case string (no spaces or other characters outside of 0–9, a–z, ".", "_" and "-") identifying the operating system, excluding any version information and suitable for
       processing by scripts or usage in generated filenames. If not set, defaults to "ID=linux". Example: "ID=fedora" or "ID=debian".

   ID_LIKE=
       A space-separated list of operating system identifiers in the same syntax as the ID= setting. It should list identifiers of operating systems that are closely related to the
       local operating system in regards to packaging and programming interfaces, for example listing one or more OS identifiers the local OS is a derivative from. An OS should
       generally only list other OS identifiers it itself is a derivative of, and not any OSes that are derived from it, though symmetric relationships are possible. Build scripts and
       similar should check this variable if they need to identify the local operating system and the value of ID= is not recognized. Operating systems should be listed in order of
       how closely the local operating system relates to the listed ones, starting with the closest. This field is optional. Example: for an operating system with "ID=centos", an
       assignment of "ID_LIKE="rhel fedora"" would be appropriate. For an operating system with "ID=ubuntu", an assignment of "ID_LIKE=debian" is appropriate.
```

It seems to me like "ID_LIKE" might allow us to have this work also on e.g. Suse enterprise (that's still a thing, right?). Checking ID is simpler and has less chance of false-positives. I mean in general we prefer feature tests (i.e. here we'd prefer it if the suse and ubuntu thing were either the same or had different names), but there might be some other places where we need to use something like this.
