### ISSUE TITLE
replace `history --command` with `history command`

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3367]
The use of long options for history subcommands is an anti-pattern (i.e., so unusual it serves as an example of what not to do). It appears the original justification for doing so was to allow invoking more than one subcommand with a single `history` command. However, no one liked that as it was ambiguous, confusing, and made it too easy to shoot yourself in the foot. So a recent change was merged that only allows one of the long options that specifies a subcommand.

This issue is to take the next logical step and actually introduce subcommands; e.g., `history search` rather than `history --search`. The long option form will still be supported for the foreseeable future but will be deprecated. As part of this change we'll also remove the short options for the subcommands per [this comment](https://github.com/fish-shell/fish-shell/issues/3307#issuecomment-246110715). That includes removing, for consistency, `history -s` to mean `history --search` or `history search`.

**Comment by krader1961** [comment]
Note that there is one backward incompatible aspect to this proposal: `history search something` will no longer search for `search something`, it will search for `something`. Similarly `history delete something` will no longer search for `delete something` it will instead delete an entry that exactly matches `something` (assuming neither `--contains` or `--prefixes` is specified).

**Comment by c22** [comment]
I agree with the sentiment of this issue, though it is unfortunate that the change would be backward incompatible. I will add that switching to a subcommand pattern isn't mutually exclusive to having (or not having) shorthand syntax.

eg. `history search == history s`

Tab completion is a good argument against the need for shorthand syntax though.

**Comment by krader1961** [comment]
Yes, but how often do you search for the word "search" or "delete"? Also, the long option form (e.g., `--search`) will remain valid for the foreseeable future; it will simply be deprecated and no longer prominent in the documentation. Also, the "search" subcommand keyword will be optional unless you want to search for the word "search".

**Comment by krader1961** [comment]
Also, note that supporting short versions of the keywords increases the number of words that cannot be implicitly searched for without having to say `history search`. Tab completion or an abbreviation (e.g., `abbr --add hs 'history search'`) seem like better ways to minimize the amount the user has to type.

**Comment by c22** [comment]
Agreed. Also I'm just one user of fish, but I almost exclusively use archaic form `history | grep` and when I use builtin search functionality it's usually with the modifiers such as `history --prefix`. To that end, intuitively I would expect `history --prefix search` to be expanded to `history search --prefix search` though the amount of times I can ever see myself doing that in practice is close to none.

**Comment by krader1961** [comment]
Note that due to how flags are parsed by the `history` function and builtin doing something like `history --prefix search` will actually search for the word "search"; i.e., it's equivalent to `history search --prefix search`. So that behavior won't be changed. Note that `--prefix` does not take any arguments so `history --prefix --with-time search` also works. This is something that was ambiguous in the old history man page which I hope I've clarified with my recent change.

P.S., It's also a good example of why I feel very strongly that other places where fish allows flags to appear anyplace on the command line should be changed to stop processing flags after the first non-flag argument.

**Comment by c22** [comment]
> stop processing flags after the first non-flag argument

I believe the POSIXLY_CORRECT behaviour of GNU getopts behaves in a similar way. Making fish more POSIXy aligns nicely with high level goals of fish as a well.

**Comment by floam** [comment]
Overly strict argument requirements which reject the user when we could otherwise figure it out don't strike me as a particularly worthy goal. It's something we might be stuck with if we can't "figure it out" - but for instance not being able to handle `history search foo --prefix` or `history search foo --with-time` is being unhelpfully pedantic. Ideally we should not have to worry much about order. In my own history I see a lot of options at the end of the commands - typically I hit the up arrow and then an argument to adjust the results.

**Comment by krader1961** [comment]
> Overly strict argument requirements which reject the user when we could otherwise figure it out...

I strongly dislike the `wgetopt_long()` default behavior to permute the sequence of tokens and thus allow options to appear anywhere on the command line. For example, if I modify `builtin_history()` by removing the leading `+` in the short option string the following causes the `-t` to be treated as the `-t` (i.e., `--with-time`) flag rather than a string to be searched for:

```
builtin history search wtf -t
```

You, @floam, on the other hand like that behavior. Given that almost all of our `wgetopt_long()` long invocations implement the behavior you prefer I'll change `builtin_history()` to match. But I'm wondering if the existing behavior was a conscious decision or an accident.

Too, note that the POSIX mandated behavior is my preferred behavior. It's also what is easiest to implement in a fish script such as *share/functions/history.fish*. I'll open another issue to discuss this and whether we should modify fish C++ code to uniformly use a leading `+`, `-`, or neither. Please don't argue for one of those behaviors here as it is orthogonal to the point of this issue. We can have that discussion in the issue I intend to open (assuming I don't find an already open issue on this topic). I'm simply going to change the existing `builtin_history()` behavior to match that of most of the fish builtins as part of addressing this issue.

**Comment by floam** [comment]
One thing that's wrong in `string`, is any command that takes subcommands ought to take `command help`. `string help` is not valid - but our help system prints out the manpage in that instance so it often "works".

But this will not work: `string help match` -- it should and hopefully we'll get that right here. 

>  As part of this change we'll also remove the short options for the subcommands per this comment. 

I didn't really suggest that - `history search -t` (or `history search foo -t`) shouldn't mess things up, and the reason why is because `-t` is easy to type and destined to be often-used. It's fine and not a bad idea for search utilities --  further: I doubt many of us are confused by or prefer not to use the more common `grep` options searching other logs.

(And if `grep foo bar -n` breaks POSIX and can only be `grep -n foo bar` by the book -- I guess that wouldn't be a surprise. But I do it in the same types of cases I (too to) append `-t`  to the end - the ambiguity isn't problematic I just don't expect any different: "of course" when searching for an option-looking-string starting with a hyphen, I'd need to use -- and I'd probably quote the full string.

**Comment by krader1961** [comment]
@floam, I meant that this change will remove the short option equivalent for the flags that represent subcommands. For example, `history --search` will still be valid but `history -s` will not be valid. The options that apply to a specific command (e.g., `-p`) will continue to have both short and long forms.

Regarding your example involving grep there are good arguments for both behaviors with respect to recognizing, or not, the `-n` flag in arbitrary locations. I personally prefer the POSIX behavior. But I can live with either behavior. I'm simply pointing out that at the moment fish a slightly inconsistent and the documentation is totally silent on the matter. Please don't reply here as the topic is orthogonal to this issue. As soon as I find a relevant open issue or open a new one we can continue this discussion there.

**Comment by olbrew** [comment]
@krader1961  
> Yes, but how often do you search for the word "search" or "delete"?

I'm on 2.4b1 and actually wanted to delete all uses of the "--delete" from my history. (Why should it even be added to the history in the first place? If you want to delete a certain operation from your history it implies that you probably don't want the delete operation, mentioning the terms you wanted to delete in the first place, to show up in your history.)
But it seems impossible with the search term "--delete", quoted or not, both with the new subcommand and old option syntax.

**Comment by faho** [comment]
@olbrew: Tried `history delete -- --delete`? From a quick reading of the function, that should work.

**Comment by krader1961** [comment]
@olbrew: @faho's suggestion will work. All fish commands (but not necessarily all commands on your system) support `--` to terminate parsing the command line for flags. Simply quoting the argument doesn't help because the command parser strips the quotes as it splits the command line into tokens before passing the tokens to the command. So the history command still gets `--delete` without quotes.

As for why it's added to the history in the first place it's a question of consistency and what is least surprising to a user. As soon as you start special-casing things like `history --delete` the documentation gets longer and it's more likely someone will be surprised. The KISS principle usually trumps most other considerations.

**Comment by olbrew** [comment]
@faho Thank you, that worked indeed. 

@krader1961 
> Simply quoting the argument doesn't help because the command parser strips the quotes as it splits the command line into tokens before passing the tokens to the command. So the history command still gets --delete without quotes.

That makes sense I'll remember it for the future!

> As for why it's added to the history in the first place it's a question of consistency and what is least surprising to a user. As soon as you start special-casing things like history --delete the documentation gets longer and it's more likely someone will be surprised. The KISS principle usually trumps most other considerations.

Didn't think about it like that but I definitely have to agree now. I'll just keep manually deleting them then :).

**Comment by c22** [comment]
@olbrew Handy tip, if you don't want a command to show in your history (at least under default conditions), just add a space to the start of it.

So when you do a `history --delete` just add a space before the `history` command to omit it from the history.
