### ISSUE TITLE
completion: lost all candidates when they have command prefix

### ISSUE THREAD

**Issue by EMayej** [fish-shell/fish-shell#3369]
First we have this as a feature in fish.
```
If there is more than one completion, fish will write out the longest prefix that all completions have in common.
```

The problem is that, when I complete fasd, I type some filename, then hit Tab.
fasd returns multiple candidates, all of them are absolute paths and they have some common prefix.
But fish just print the common prefix of the candidates.

When I hit Tab again, now fasd tries to use the prefix as inputs, my filename is gone.
Thus all candidates in previous Tab are dropped.

How could I solve this?
Could fish also show all candidates when print common prefix to commandline?

**Comment by faho** [comment]
Have you tried fish from git master? We've changed it so the longest common prefix _isn't_ inserted anymore when you're not completing the prefix. E.g. when I complete files in the share/function directory, I'll type complete `inter` and get `__fish_print_interfaces.fish` and `__fish_config_interactive.fish` as candidates, but it won't insert the "__fish_" part anymore.

**Comment by EMayej** [comment]
Just tried, I think it is OK now.

Thank you all for making this great shell.
