### ISSUE TITLE
Write a fish script can do `echo 123 | cat` and `cat (echo 123 | psub)`

### ISSUE THREAD

**Issue by pwwang** [fish-shell/fish-shell#3377]
Probably it's not an issue, I just wonder how to implement it in Fish.
So that the script can do both:
`echo 123 | script` and `script (echo 123 | psub)`
`$argv` cannot deal with the former one.

**Comment by faho** [comment]
In the latter case, you'll get the name of a file that you'll have to read. In the former, you'll read from stdin.

You need to determine when to use stdin and when to use a file. A good idea is probably to use stdin only when no argument has been given and when it's not a tty.

So something like

```
function script
    if set -q argv[1]
        # Read from file
    else if not isatty stdin
        # Read from stdin
    else
        # Neither - fail?
    end
end
```

Reading from stdin can be done via just invoking a command that does it or

```fish
while read -l line
    # do something with the line
end
```

Reading from a file can be done via redirecting - like

```fish
while read -l line
    # do stuff
end < $file
```

Unfortunately, I can't find a _nice_ way to set "$file" to stdin so you can use the same code for both and just set $file.

Does that help?

**Comment by floam** [comment]
The [read](https://fishshell.com/docs/current/commands.html#read) function.

```fish
function script
	set -l input
	if set -q argv[1]
		set input $argv
	else
		read input
	end
	echo I got: $input
end
```

```console
floam@rMBP~> echo abc | script
I got: abc
floam@rMBP~> script 123
I got: 123
```

**Comment by pwwang** [comment]
Both worked, thank you so much! @floam @faho
