### ISSUE TITLE
Cant Set Env Variable Value having equals sign when using fish

### ISSUE THREAD

**Issue by sidhant92** [fish-shell/fish-shell#3379]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
2.3.1
**OS/terminal used**: 
Mac OS X 10.11.3/ Default Terminal
Talk about the the issue here. 
When i am using fish and i set an evironment variable which has equals sign in its value the variable does not get set. Without fish this works fine.
## Reproduction steps
1. export test='abc=123'
2. echo $test
3. No output

**Comment by floam** [comment]
Wait, a minute here. It works for me.

Can you copy and paste the whole terminal window? And type `set` with no arguments and press enter, can you show the output?
```
>export test='abc=123'
/u/local (master↑1↓2|…) $ echo $test
abc=123
```

**Comment by floam** [comment]
Are you sure you are using export in this case? We also have the `setenv` convenience function which is similar to `export` (both wrap `set`) - except it does not have the ability to handle foo=bar.
 on = (both use set -gx, which just yells at the user if it gets an equal sign.)

**Comment by sidhant92** [comment]
Sorry just found out after upgrading to 2.3.1 its working fine.
