### ISSUE TITLE
Running (fish_config) as root does not open a browser

### ISSUE THREAD

**Issue by silverhook** [fish-shell/fish-shell#3384]
- [ ] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.1.1

**OS/terminal used**: Mageia 5, GNU/Linux, KDE 4.14.5, Yakuake 2.9.9

When I try to run `fish_config` as root – to set up my root user’s settings – the internet browser doesn’t launch (but calibre does for some reason).

## Reproduction steps
1. `su -`
2. `fish_config`

## Results

Calibre opens, and can’t do anything useful with it.

```
Launch the main calibre Graphical User Interface and optionally add the ebook at
path_to_ebook to the database.

Whenever you pass arguments to calibre that have spaces in them, enclose the arguments in quotation marks. For example "C:\some path with spaces"

calibre: error: no such option: --detach /tmp/tmp.OuMfv2PysM/.cache/fish/web_config-N1ZLT6.html
Opening "/tmp/tmp.OuMfv2PysM/.cache/fish/web_config-N1ZLT6.html" with calibre  (text/html)
```

## Workaround

1. Copy-paste the URL in Calibre’s console output to a web browser you started as root.
2. Use as intended.

**Comment by faho** [comment]
It actually does for me. It depends on what it thinks your browser is. I can't quite figure out what logic [the python module we're using](https://docs.python.org/3.5/library/webbrowser.html) is following.

Try setting `$BROWSER`.

**Comment by silverhook** [comment]
I did, but it doesn’t help one bit, unfortunately.

~~~~.fish
root@hermes:~                                                                                                                           
➤ echo $BROWSER 

root@hermes:~                                                                                                                           
➤ set BROWSER /usr/bin/firefox 

root@hermes:~                                                                                                                           
➤ echo $BROWSER 
/usr/bin/firefox

root@hermes:~                                                                                                                           
➤ fish_config 
Web config started at 'file:///root/.cache/fish/web_config-PZ56R3.html'. Hit enter to stop.
START /usr/bin/calibre --detach /root/.cache/fish/web_config-PZ56R3.html
Raba: calibre [options] [path_to_ebook]

Launch the main calibre Graphical User Interface and optionally add the ebook at
path_to_ebook to the database.


Whenever you pass arguments to calibre that have spaces in them, enclose the arguments in quotation marks. For example "C:\some path with spaces"

calibre: error: no such option: --detach /root/.cache/fish/web_config-PZ56R3.html
Opening "/root/.cache/fish/web_config-PZ56R3.html" with calibre  (text/html)
^C
Shutting down.
~~~~

**Comment by faho** [comment]
@silverhook: You'll want to set it globally and exported. `set -gx BROWSER /usr/bin/firefox`.

**Comment by silverhook** [comment]
@faho, ah thanks, that actually worked.

Still, odd that I had to do select it. Bug in distro or something that Fish should fix?

**Comment by faho** [comment]
>Bug in distro or something that Fish should fix?

Not really either. As I stated before, I'd need to find an authoratative source on what the python webbrowser module does, but in general DEs and file associations as root don't work all that great on linux. Usually you'll want to execute `xdg-open` to "just open this with the right app", but that's broken surprisingly frequently (and distros package random git commits, so it's a crapshoot).

**Comment by silverhook** [comment]
…and on Mageia I found that there’s also `www-browser`, which is a script with several `if` loops that in case `xdg-open` fails, tries to detect the DE and launch the most appropriate browser. This of course adds to the confusion.

**Comment by zanchey** [comment]
Is there anything more to do here, or have we answered the question?

**Comment by silverhook** [comment]
@zanchey That is a good question.

I did manage to work around the issue. The question remains whether that’s a bug or not.

**Comment by faho** [comment]
The question here is if we want to do something about the situation or punt it to somewhere else - that'd be either the python "webbrowser" module or xdg-open, which [should be first priority](https://hg.python.org/cpython/file/3.5/Lib/webbrowser.py#l415).

My guess is the culprit is something that should be fixed there, and anything we could do to work around it would be incomplete and buggy in other cases.

@silverhook: What happens when you run `xdg-open THATFILEURL`, where "THATFILEURL" is the "file:///" url that `fish_config` should print in its output? If that also runs calibre, then your issue is with either your configuration or xdg-open, and should be fixed there. We also expose it via our `open` function, so that would have the same issue.

**Comment by silverhook** [comment]
> What happens when you run xdg-open THATFILEURL, where "THATFILEURL" is the "file:///" url that fish_config should print in its output?

If I run `xdg-open` on the HTML file provided by `fish_config`, it again opens in Calibre.
But if I run `xdg-open` on a website URL, it opens up Firefox.

**Comment by faho** [comment]
@silverhook: You need to fix your configuration. Calibre is associated with html files, we just do what the config says.

**Comment by silverhook** [comment]
@faho OK, so it’s probably a distro fault (I don’t remember messing with configs). Thanks for helping me analyse it :)
