### ISSUE TITLE
Feature idea: profile exporting

### ISSUE THREAD

**Issue by Lucretiel** [fish-shell/fish-shell#3385]
One of my favorite features of fish is how it replaces a monolithic rc file with the various things in 
"~/.config/fish"– functions, universal variables, and so on. However, one of the inconvenient parts of this design is that it's not very straightforward to transfer your profile– here defined as your combination of user saved fish functions, universal variables, completions, and config files– to a new host.

My proposal is a new command, `fish_profile`, which can be used as follows:

```
# host1:
fish_profile export profile.fp
scp profile.fp host2:

# host2:
fish_profile import profile.fp [--force]
```

This profile is a file with an unspecified format that contains all the user-specific fish profile data as described above. The `fish_profile` command should probably be a new binary, rather than a builtin.

Thoughts? If there's interest I can see about whipping up a prototype.

**Comment by floam** [comment]
So, the part of fish that is right now responsible for dealing with shoving settings into fish from the outside is fish_config. It seems to me that's probably the most logical place to want to put this "export" feature. Indeed, it is an external process (Python), and it can basically hack fish if it wants to. 
We also run a **web server** (albeit locally) here.

I'd imagine... " a cloud with a downward or upward facing "download" arrow icon" somewhere in the web config and like`--export-settings=FILE`/`--shove-settings-to...` with better names that the CLI. 

A problem that exists today is that you can't even visit the fish_config page (with serious effort) on a remote server despite it being web-based. Doing this could make that easier, but there are likely some interesting possibilities if we can manage to set our users up with secure tunneled transport off the local machine somehow. 

How does fish report the current state to the python app or any utility? Hopefully most of this could be stuff done like how you can (could?) pipe the output of `bind` on one host into the eval() on another host (or sneaker-net it) and inherently have the same bind setup on the other side. 

That's kind of where this is hard - how do we actually serialize and sanely capture the whole of fish? We don't presently even manage to save the old prompt before fish_config nukes it. It's quite "basic" how we are storing our included prompts. Also, functions like `funcsave` are very naive with regards to the implications of autoloading...

**Comment by krader1961** [comment]
I'm not sure I see a need for a fish specific utility. Your entire config could normally be copied via `scp -pr .config/fish new_host:` or equivalent. The only part of migrating your config that would need some assistance is universal vars since they are currently stored in a file whose name depends on the host. And that wouldn't be necessary if we implemented my proposal to have a truly universal var file. See issue #1912.

Also, what I do is put my *~/.config/fish* directory on Dropbox and symlink to that on each of my machines. That way whenever I edit my fish config on one host, excluding uvars, those changes are automatically seen on all my other hosts.

**Comment by floam** [comment]
> Your entire config could normally be copied via scp -pr .config/fish new_host:

That file should not be called a config file. The true "config" of fish ends up being something that emerges from collection of uvars set and the autoloaded functions defined in a couple spots.

**Comment by floam** [comment]
(I don't even have a "config" (initialization) file - but there is a lot of user configuration in fish.)

```
 cd fish
 $ ls
fish_history  fishd.a45e60bdb6f9  functions/
$ pwd
/Users/floam/.config/fish
```

**Comment by krader1961** [comment]
> That file should not be called a config file.

I did not refer to a specific file in the comment to which you made that reply. I referred to the directory that contains the auto-loaded functions, completions, and similar files.

> I don't even have a "config" (initialization) file - but there is a lot of user configuration, still, in my fish.

And how does that invalidate what I said? Nowhere did I imply that copying *~/.config/fish/config.fish* (the file you seem to be alluding to) was the sum total of what needed to be copied. Quite the contrary.

**Comment by floam** [comment]
You're right - I misread it - my apologies: I mischaracterized your comment.

**Comment by faho** [comment]
@Lucretiel: Is there anything outside of ~/.config/fish you can think of? Otherwise this doesn't seem like an improvement over `scp -r`.

**Comment by Lucretiel** [comment]
I had two main goals here:
- Don't ship the fish_history, or anything else that might be considered not part of the user profile
- Create a single file that can be easily distributed to other machines
   - I suppose this is easily accomplished by doing a `tar -z`
