### ISSUE TITLE
Turn on branch protection

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#3387]
Unfortunately, perhaps due to overzealous Xcode configuration, we dropped some commits on master today. The distributed nature of Git meant that the commits weren't lost (phew) and that a merge commit tidied things up nicely, but this isn't the first time that a force commit has caused problems.

I think it's time to turn on [branch protection](https://help.github.com/articles/configuring-protected-branches/) for master - @ridiculousfish, if you agree, would do so?

**Comment by ridiculousfish** [comment]
I agree. Let's start with the default settings of disabling force push and preventing deletions. We can dial it up or down based on feedback.

**Comment by ridiculousfish** [comment]
Branch protection of master done, thanks for thinking of this.
