### ISSUE TITLE
Build failure on Arch Linux

### ISSUE THREAD

**Issue by z3ntu** [fish-shell/fish-shell#3388]
I am trying to compile the package `fish-git` from the AUR, but it fails because of the error:

> ...more stuff...
  CXX      obj/util.o
  CXX      obj/wcstringutil.o
  CXX      obj/wgetopt.o
  CXX      obj/wildcard.o
  CXX      obj/wutil.o
  CXX LD   fish
obj/wutil.o: In function `safe_strerror(int)':
src/wutil.cpp:(.text+0xaed): warning: `sys_errlist' is deprecated; use `strerror' or `strerror_r' instead
src/wutil.cpp:(.text+0xae3): warning: `sys_nerr' is deprecated; use `strerror' or `strerror_r' instead
  CXX      obj/fish_indent.o
src/fish_indent.cpp:87:23: warning: comparison of integers of different signs: 'int' and 'size_type' (aka 'unsigned long') [-Wsign-compare]
        if (nextc_idx < source.size()) nextc = source[node.source_start + node.source_length];
            ~~~~~~~~~ ^ ~~~~~~~~~~~~~
1 warning generated.
  CXX      obj/print_help.o
  CXX LD   fish_indent
obj/wutil.o: In function `safe_strerror(int)':
src/wutil.cpp:(.text+0xaed): warning: `sys_errlist' is deprecated; use `strerror' or `strerror_r' instead
src/wutil.cpp:(.text+0xae3): warning: `sys_nerr' is deprecated; use `strerror' or `strerror_r' instead
  CXX      obj/fish_key_reader.o
src/fish_key_reader.cpp:57:14: warning: 'const' type qualifier on return type has no effect [-Wignored-qualifiers]
static char *const sequence_name(wchar_t wc) {
             ^~~~~~
src/fish_key_reader.cpp:160:27: warning: comparison of integers of different signs: 'int' and 'size_type' (aka 'unsigned long') [-Wsign-compare]
        for (int i = 0; i < bind_chars.size(); i++) {
                        ~ ^ ~~~~~~~~~~~~~~~~~
2 warnings generated.
  CXX LD   fish_key_reader
obj/wutil.o: In function `safe_strerror(int)':
src/wutil.cpp:(.text+0xaed): warning: `sys_errlist' is deprecated; use `strerror' or `strerror_r' instead
src/wutil.cpp:(.text+0xae3): warning: `sys_nerr' is deprecated; use `strerror' or `strerror_r' instead
 CAT AWK   doc_src/commands.hdr
  SED = '/usr/bin/sed'
 SED       toc.txt
  AWK = 'gawk'
 AWK CAT      doc_src/index.hdr
 HDR_FILES doc.h
  FGREP = '/usr/bin/grep -F'
SEDFGREPSE lexicon.txt
/bin/sh: line 2: @: command not found
make: *** [Makefile:421: lexicon.txt] Error 127

Tested on x86_64 and armv6h

**Comment by zanchey** [comment]
Yes, this is broken unless you configure `--without-doxygen`.

**Comment by floam** [comment]
Sorry about that - it should be fixed now.

**Comment by z3ntu** [comment]
Yes, it seems that https://github.com/fish-shell/fish-shell/commit/02ba7933e04ba606de2693815bfa57dd534f10d6 fixed it. It works again on both x86_64 and armv6. Thanks :)
