### ISSUE TITLE
`make test` no longer runs the `test_fishscript` target

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3394]
I noticed a couple of days ago that `make test` was no longer running the `test_fishscript` target. This came to my attention because I expected the *history.in* test to fail since I had modified the associated code but updated the tests in a manner I knew contained a bug. I was surprised the test didn't fail.

Either commit 02ba7933e04ba606de2693815bfa57dd534f10d6 or commit 30b71fbb7807730922f0699823eddfffd02dcba0 is likely the culprit. I can't verify which since checking out the latter commit fails due to a bug in the makefile the former commit fixes.

**Comment by floam** [comment]
Before I went with `bo` for bold I was using `$(b)` - my sed-fu changed all`$(b)'s to `$(bo)`, which another part of the makefile was also using unbeknownst to me.
