### ISSUE TITLE
`make test` always fails the *bind.expect* test on my server

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3395]
Two weeks ago I started seeing `make test` always fail the *bind.expect* tests on my macOS server. Yet the same test always passed on my Linux server and TravisCI. I ignored the failure because of a comment made by @faho on Gitter that suggested to me this was a known problem that would be fixed in the near future. But two weeks later it's still failing.

It's failing for me because I'm running the tests inside tmux in an iTerm terminal on macOS which results in env var `ITERM_PROFILE` being set to `System tmux` (note that the actual value of that var doesn't matter it is simply what it is set it to on my system).

Commit cac3b239 introduced this problem. This is another situation where the unit tests are not sufficiently hermetic. Specifically, they can be influenced by the user's env vars in a surprising way. I'll fix this since I noticed it and it's apparently only affecting me at this point in time.

**Comment by faho** [comment]
Yes, sorry. I had fixed the issue that the vi-cursor appeared under e.g. emacs/screen, but had forgotten that it would break in normal terminals since just at that time I had switched my $TERM.

Sorry!
