### ISSUE TITLE
builtins should not print entire usage summary on invalid use

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#3404]
Consider

``` console
~ $ bind \e\c foo
Invalid token '\e\c'
fish: bind \e\c foo
           ^
```

This seems like it ought to be:

``` console
~ $ bind \e\c foo
fish: bind \e\c foo
           ^
Invalid token '\e\c'
```

Further: 

``` console
~ $ functions -x
functions: Unknown option '-x'

       functions ‐‐ print or erase functions

   Synopsis
       functions [ ‐a | ‐‐all ] [ ‐n | ‐‐names ]
       functions ‐c OLDNAME NEWNAME
       functions ‐d DESCRIPTION FUNCTION
       functions [ ‐e | ‐q ] FUNCTIONS...

functions: Type 'help functions' for related documentation
```

We should place the error _after_ the usage information. Sometimes it can be long and the error, far away.

**Comment by floam** [comment]
(And the command in this particular instance probably ought to identify itself: `bind: Invalid token '\e\c'`)

**Comment by krader1961** [comment]
> We should place the error after the usage information.

No. The error should be foremost (i.e. "front and center"). That `functions -x` outputs usage text rather than a mention to run `man functions` is itself a bug IMHO.

**Comment by ridiculousfish** [comment]
Agreed with @krader on both counts. Outputting the full usage spec just obscures the error message. I'd be in favor of replacing the "output full usage on error behavior" with a pointer to how to access the usage, e.g. to run `man functions`.

**Comment by floam** [comment]
That works too. The main issue is when the usage spec pushes the actual error off screen.

**Comment by zanchey** [comment]
> That functions -x outputs usage text rather than a mention to run man functions is itself a bug IMHO.

Shall we track that here then?

**Comment by floam** [comment]
What might be the issue is not that we output the usage output output at all, but how "full" this manpage-derived usage output can be unnecessarily.

typical manpage-parsed output:
```
$ __fish_print_help fish_realpath

       fish_realpath ‐‐ Convert a path to an absolute path without symlinks

   Synopsis
       fish_realpath path

   Description
       This is an implementation of the external realpath command that
       doesn’t support any options. It’s meant to be used only by scripts
       which need to be portable. In general scripts shouldn’t invoke this
       directly. They should just use realpath which will fallback to this
       builtin if an external command cannot be found.

       If the path is invalid no translated path will be written to stdout
       and an error will be reported. This implementation behaves like the
       GNU command being invoked with ‐‐canonicalize‐existing.
```

should be more like 1-2 lines (and is where I did this by hand):


`$ realpath`
`usage:` **`realpath`** `file …`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;` resolves files as absolute paths without symlinks`

**Comment by faho** [comment]
Yeah, I just removed the summary. It's fluff, people can use the man page or help.

**Comment by floam** [comment]
I sure wish we had a nice way to spit out a usage line.

**Comment by floam** [comment]
I think we could have kept the man page thing and just more carefully cut up the output.
