### ISSUE TITLE
Fedora 24 support

### ISSUE THREAD

**Issue by Arjoni** [fish-shell/fish-shell#3407]
Do you support fedora 24? I don't see a package for it.

**Comment by krader1961** [comment]
Yes. See https://build.opensuse.org/package/show/shells:fish:nightly:master/fish

Not sure why the linux/fedora link on http://fishshell.com/ isn't working.

**Comment by Arjoni** [comment]
Is there one for stable version (not nightly)?  BTW opensuse is down for maintenance. The link for fedora on homepage only showed repos for fedora 23 and below.

**Comment by Arjoni** [comment]
https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A2&package=fish 
No fedora 24...

**Comment by faho** [comment]
@Arjoni: What exactly do you want here? Tried `dnf install fish` yet?

Fish is in the [fedora repositories](https://admin.fedoraproject.org/pkgdb/package/rpms/fish/), and there are rpms for fish 2.3.1 for 23 and 24.

Usually you'll want those, our packages are mostly for nightlies and when you can't get an up-to-date version (like for debian or ubuntu), but the fedora packages are up-to-date.

**Comment by zanchey** [comment]
Added the Fedora 24 repositories to the release project, but yes - it's well maintained in Fedora.
