### ISSUE TITLE
Universal events?

### ISSUE THREAD

**Issue by alphapapa** [fish-shell/fish-shell#3408]
I found #2954 because I found the universal-variable-as-universal-event method to work well, but I wonder whether it would still make sense to have universal events.  In Bash, you can run blocks of code in a subshell, e.g.:

``` sh
(
  echo "Now it's $(date)"
  sleep 1
) &
```

But in fish, this isn't possible, so you have to do something like:

``` fish
fish -c 'echo "Now it is "(date); sleep 1' &
```

It's very powerful to be able to trigger events using `function --on-event`, but doing this from a subprocess like that doesn't work, since `emit` doesn't reach other processes.  So one can do `set -U` and `function --on-variable` instead, but it...well, feels hacky, if you know what I mean.  It would feel a lot cleaner to be able to do something like:

``` fish
function say_it_changed --on-event it_changed
    echo "It changed!"
end

fish -c '
set last_mtime (stat %Y filename)
while true
    set current_mtime (stat %Y filename)
    if test $current_mtime = $last_mtime
        sleep 5
    else
        set last_mtime $current_mtime
        emit -U it_changed
    end
end' &
```

**Comment by krader1961** [comment]
There are a lot of questions and details that need to be addressed. For example, which fish processes receive the event? Does the current shell (the one in which `event -U` is run) receive the event if it has an `--on-event` handler for the event? If more than one shell has such a handler do they all run? Or just the first one to receive the event? Should this allow sending events between arbitrary fish processes or just those with a parent/child relationship? Should there even be a way to specify that a specific fish process receive the event (e.g., `emit -U --pid=1234 it_changed`)?

What happens if the same event is emitted more than once before an event handler runs? Are the events queued or coalesced? Do we need to attach additional information to the event (e.g., the pid that emitted it and the time it was sent) and provide a way to retrieve that information? What happens if no fish process currently has a handler for the event: is it queued for deliver when a handler is defined or is it thrown away? How would the sender know whether or not there is a process with a handler for the event? What about race conditions?

And those are probably just the tip of the iceberg. If you feel strongly about this @alphapapa I'd ask that you flesh out this proposal with some answers to those questions so we have a better idea of how you expect this to work.

**Comment by krader1961** [comment]
Also, if we do decide to do something like this we should a) consider prior art and b) whether this should be done as a general purpose remote method invocation API. For example, JavaSpaces, Java RMI, MQSeries. Too, we've talked about, and many of use strongly believe, that universal variables should be truly universal. That is, not stored in a file whose name is based on a characteristic of the machine the fish shell is running on (e.g., network interface MAC addr). What would it mean for this proposal if we allowed sending events between fish processes on different machines? Or should that be explicitly disallowed?

**Comment by alphapapa** [comment]
Kurtis, thanks for your thoughts.  Those are all very good points and questions.  Overall, I think what would be most useful is a very simple and straightforward message-sending feature, without any fancy features like queueing or coalescing; I think anyone needing those should look to more advanced solutions.  

I'll try to address your specific questions here.  Please keep in mind that I am not giving much consideration to implementation difficulty, so forgive any pie-in-the-sky ideas.  :)

**Which Fish processes receive the event?**

My first thought is that all interactive Fish processes running as the current user should receive the event.  However, it could be very powerful to also be able to send to non-interactive Fish processes running scripts.  So I would propose something like this:

    # Emit to current shell
    emit signal
    
    # Emit to all interactive shells
    emit --all-interactive signal
    
    # Emit to all non-interactive shells
    emit --all-non-interactive signal
    
    # Emit to all shells, both interactive and non-interactive
    emit --all signal

That feels a bit verbose, but at least it's clear.  Trying to use combinations of short options might be confusing, but could be added if desired.  

I like the "universal" term, but `--all-non-interactive` seems long enough already; `--universal-non-interactive` seems like too much.

**Does the current shell (the one in which event -U is run) receive the event if it has an &#x2013;on-event handler for the event?** 

Yes, the current shell should receive it.  

I can imagine situations in which it would be desired to send it to only other shells.  In this case, there are a few possibilities:

1.  The current shell could redefine or erase the event-handling function for itself, after launching any other processes that will receive the events.

2.  The event-handling function could check which process it's running in and ignore the event as desired.

**If more than one shell has such a handler do they all run? Or just the first one to receive the event?**

I think all shells that have a handler should run it.  Again, I can imagine it being useful to restrict it to just the first, but I think that is getting too complex.  I don't think this feature should be used to write things that really need to work that way, like web servers.  Sure, you could write a web server in Fish (people have done it in Bash), but why?  =)

As an example of something that this could be used for, it could serve as a "poor man's history sync," to cause other shells to run `history --merge` when a command is run.

**Should this allow sending events between arbitrary fish processes or just those with a parent/child relationship?**

I think, by default, it should be "universal", and all Fish processes should receive the events.  But I could imagine it being useful to have an option, like `emit --children signal`, or `emit --parent signal`.  Maybe that could be implemented fairly simply under-the-hood.

**Should there even be a way to specify that a specific fish process receive the event (e.g., emit -U &#x2013;pid=1234 it<sub>changed</sub>)?**

I'm not sure about this.  My first thought is that, no, that shouldn't be necessary, because part of the idea here is to avoid having to worry about PIDs.  PID-specific signals can already be sent with `kill` and `trap`, although there are a limited number available.  But I wouldn't be opposed to having a `--pid` option.

**Whether this should be done as a general purpose remote method invocation API**

I feel like that's out-of-scope for this idea, and that people who need that sort of thing should use appropriate solutions, not shell scripts.  :)

**What would it mean for this proposal if we allowed sending events between fish processes on different machines? Or should that be explicitly disallowed?**

I also feel like that's out-of-scope.  I'm just looking for a simple way for Fish processes on a machine to pass signals to each other, mostly to help make up for the lack of subshells in Fish.  Universal variables seem to work surprisingly well for this, but they also seem messy in that they leave entries in the `fishd` file after being used.

**Message-passing vs. event signals**

Another thought I just had: it seems inevitable that if this were implemented, someone would eventually want a way to send messages associated with the events, i.e. give the emitted signal a value as well as a name.  I guess if this were thought of as a special case of universal variables, it wouldn't be difficult to this.

**Conclusion**

I'm not sure if this feature makes sense for Fish, but I think it's definitely worth considering.  It seems like a simple way to pass messages or signals between Fish processes running on the local machine would be very useful and powerful.  Thanks for your thoughts.

**Comment by faho** [comment]
Like I said in #2954, I feel like we need to figure out what this is _for_, and also if there are enough use cases for this to be worthwhile.

Personally I've not yet found a situation where I'd want this.

The example from 2954 is a job notification scheme. I feel like that might also be served by sending a notification to the desktop or the terminal (some terms have this feature).

Again, I'm not dead set against this, but I'd like to have some proof of usefulness.

**Comment by alphapapa** [comment]
Here's what I'm using it for right now.  I use MPD to play music.  While music is playing, I have a Fish script that displays the current track's info.  It runs two Fish processes in the background, one that waits until the track is supposed to finish playing, and another that checks every 5 seconds to see if the track has been manually changed.  When either process detects that the track has changed, it sets a universal variable to the path of the new track.  The script sets the `fish_prompt` function to watch that universal variable, and when it changes, the prompt is redisplayed, displaying the information for the new track.

The script also makes it easy to add tags to the tracks using a Python script, so the modified prompt displays the track's current tags and uses `commandline` to prefill the tagging command (which has tab-completion ready to go).

In order to get this kind of behavior without subprocesses and universal variables, I'd have to either use a bunch of loops that constantly read and write tempfiles, or write the whole thing in another language, like Python, which would take a lot more code.  All of this fits in about two pages of Fish script.  Even writing this in Bash, which supports subshells directly (rather than through `fish -c`), would take a lot more work because of the lack of universal variables and `function --on-variable`.

So this is a really nice feature, a way that Fish really shines in comparison to Bash, and having "universal events" would make it even better, a bit less hacky.  :)

**Comment by krader1961** [comment]
Closing because there isn't a compelling use case that can't be handled with universal vars and as noted in #2954 there are problems with this idea.
