### ISSUE TITLE
Unknown option '-g'

### ISSUE THREAD

**Issue by jkodroff** [fish-shell/fish-shell#3409]
- [ x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [ x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
2.3.1

**OS/terminal used**: 
OSX, iTerm2 3.0.10

Talk about the the issue here. 

When my terminal session starts, I get the following error message:

```
usage: mktemp [-d] [-q] [-t prefix] [-u] template ...
       mktemp [-d] [-q] [-u] -t prefix
contains: Unknown option '-g'
/usr/local/Cellar/fish/2.3.1/share/fish/config.fish (line 147): contains --index $x $local_path
                                                                ^
in command substitution
	called on line 145 of file /usr/local/Cellar/fish/2.3.1/share/fish/config.fish

in function '__fish_reconstruct_path'
	called on line 165 of file /usr/local/Cellar/fish/2.3.1/share/fish/config.fish

from sourcing file /usr/local/Cellar/fish/2.3.1/share/fish/config.fish
	called during startup


       contains ‐‐ test if a word is present in a list

   Synopsis
       contains [OPTIONS] KEY [VALUES...]

contains: Type 'help contains' for related documentation

Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
jkodroff@jkodroff01-mac ~>
```

I suspect this is due to upgrading using Homebrew.

**Comment by faho** [comment]
This seems like somehow a "-g" slipped into $PATH, and we don't guard the `contains` here with a "--". Can you `echo $PATH`? If that doesn't yield anything, can you do it in another shell?

What I _don't_ get is how the `mktemp` comes into play here. Can you `grep -r mktemp /usr/local/Cellar/fish/2.3.1`? It should show matches in the mktemp completions and the `funced` and `psub` functions, neither of which I see called here.

**Comment by jkodroff** [comment]
```
jkodroff@jkodroff01-mac ~> echo $PATH
/Users/jkodroff/src/go/bin /Users/jkodroff/src/go/binset -g fish_user_paths /usr/local/sbin /usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/go/bin
```

The above thing came from me doing a bad `echo` and redirect to my `config.fish` file (no newline), but the thing that's confusing the heck out of me is that that line is _not_ in my `~/.config/config.fish`, so I have no idea where it's getting that bad line.

```
jkodroff@jkodroff01-mac ~/.c/fish> grep -r mktemp /usr/local/Cellar/fish/2.3.1
Binary file /usr/local/Cellar/fish/2.3.1/bin/fish matches
Binary file /usr/local/Cellar/fish/2.3.1/bin/fish_indent matches
Binary file /usr/local/Cellar/fish/2.3.1/bin/fish_key_reader matches
/usr/local/Cellar/fish/2.3.1/share/fish/completions/mktemp.fish:if mktemp --version >/dev/null ^/dev/null # GNU
/usr/local/Cellar/fish/2.3.1/share/fish/completions/mktemp.fish:	complete -c mktemp -s d -l directory    -d 'create a directory, not a file'
/usr/local/Cellar/fish/2.3.1/share/fish/completions/mktemp.fish:	complete -c mktemp -s u -l dry-run      -d 'do not create anything; merely print a name (unsafe)'
/usr/local/Cellar/fish/2.3.1/share/fish/completions/mktemp.fish:	complete -c mktemp -s q -l quiet        -d 'suppress diagnostics about file/dir-creation failure'
/usr/local/Cellar/fish/2.3.1/share/fish/completions/mktemp.fish:	complete -c mktemp -l suffix -r         -d 'append SUFF to TEMPLATE'
/usr/local/Cellar/fish/2.3.1/share/fish/completions/mktemp.fish:	complete -c mktemp -l tmpdir            -d 'interpret TEMPLATE relative to DIR'
/usr/local/Cellar/fish/2.3.1/share/fish/completions/mktemp.fish:	complete -c mktemp -l help              -d 'display this help and exit'
/usr/local/Cellar/fish/2.3.1/share/fish/completions/mktemp.fish:	complete -c mktemp -l version           -d 'output version information and exit'
/usr/local/Cellar/fish/2.3.1/share/fish/completions/mktemp.fish:	complete -c mktemp -s d                 -d 'create a directory, not a file'
/usr/local/Cellar/fish/2.3.1/share/fish/completions/mktemp.fish:	complete -c mktemp -s q                 -d 'suppress diagnostics about file/dir-creation failure'
/usr/local/Cellar/fish/2.3.1/share/fish/completions/mktemp.fish:	complete -c mktemp -s t -r              -d 'generate a template using PREFIX and TMPDIR (if set)'
/usr/local/Cellar/fish/2.3.1/share/fish/completions/mktemp.fish:	complete -c mktemp -s u                 -d 'file will be unliked before mktemp exits (unsafe)'
/usr/local/Cellar/fish/2.3.1/share/fish/functions/funced.fish:    set tmpname (mktemp -t fish_funced.XXXXXXXXXX.fish)
/usr/local/Cellar/fish/2.3.1/share/fish/functions/psub.fish:		set dirname (mktemp -d "$TMPDIR[1]"/.psub.XXXXXXXXXX); or return
/usr/local/Cellar/fish/2.3.1/share/fish/functions/psub.fish:		set filename (mktemp "$TMPDIR[1]"/.psub.XXXXXXXXXX)
/usr/local/Cellar/fish/2.3.1/share/fish/functions/psub.fish:		set dirname (mktemp -d "$TMPDIR[1]"/.psub.XXXXXXXXXX)
jkodroff@jkodroff01-mac ~/.c/fish>
```

**Comment by faho** [comment]
>The above thing came from me doing a bad echo and redirect to my config.fish file (no newline), but the thing that's confusing the heck out of me is that that line is not in my ~/.config/config.fish, so I have no idea where it's getting that bad line.

Ah, okay.

What probably happened is that you set $fish_user_paths, which is a universal variable - that means it's stored in a file. You'll want to set it to a correct value again.

So what's left to do here is to add the guards to the `contains` - we should still error then because the path doesn't exist.

**Comment by jkodroff** [comment]
Do you know what file it's stored in?  I would've expected that anything I customize is stored in `~/.config/config.fish`.

**Comment by faho** [comment]
> I would've expected that anything I customize is stored in ~/.config/config.fish.

Nope, it's in a separate file - `~/.config/fish/fishd.YOURMACADDRESS`. We don't want to mess around in your configuration file, especially not considering we want other shells to automatically pick up changes to universal variables. Half-reading config.fish would be rather confusing, and completely sourcing it again on change would also lead to weird edge-cases. 

This file however should be an implementation detail. Just `set fish_user_paths` to what you want and it'll be okay.
