### ISSUE TITLE
completions for brew services

### ISSUE THREAD

**Issue by sijad** [fish-shell/fish-shell#3410]
- [X] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [X] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:

fish, version 2.3.1

**OS/terminal used**: 

macOS 10.12

competition for [brew services](https://github.com/Homebrew/homebrew-services) should be implemented. currently when user type `brew ser` and press `tab` button it'll changes to `brew search` instead of `brew services`. it because compilation for `brew services` isn't implemented yet.

## Reproduction steps
1. type `brew ser` in your terminal.
2. press `tab` button.

## Results
```console
~ $ brew ser↹
~ $ brew search
```

**Comment by sijad** [comment]
can I work on this?

**Comment by krader1961** [comment]
> can I work on this?

Absolutely. We really appreciate users who request a feature doing at least some of the work so that all we have to do is review it :smile:
