### ISSUE TITLE
Colour of partial matched suggestion in light terminal theme is un-readable

### ISSUE THREAD

**Issue by feigaoxyz** [fish-shell/fish-shell#3412]
- [X] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [X] Tried fish without third-party customizations _(check `sh -c 'env HOME=$(mktemp -d) fish'`)_?

**fish version installed** _(`fish --version`)_:
fish, version 2.3.1-541-gf9115b5

**OS/terminal used**: 
iTerm

The colour for partial match in completion suggestion is whitish and I found no way to customise it. This is fine for dark themes in terminal. But if I use light themes in my terminal (e.g. iTerm), such as "Light Background" or "Solarized Light", the characters become un-readable. Check attached screenshots.

Dark Theme:
![dark theme](https://cloud.githubusercontent.com/assets/5907519/18859107/c6df832a-84a3-11e6-92f2-4e007f1fb493.png)

Light Theme:
![light theme](https://cloud.githubusercontent.com/assets/5907519/18859108/c9114eee-84a3-11e6-9424-02ca93f51bb5.png)

**Comment by floam** [comment]
Hm, it looks like this here:

<img width="401" alt="untitled 4" src="https://cloud.githubusercontent.com/assets/291142/18883790/88b633e6-8499-11e6-8e5d-4ad274fb9252.png">

**Comment by faho** [comment]
@feigaoxyz: You'll want to change $fish_color_autosuggestion. Also consider picking a colorscheme via `fish_config`.

**Comment by floam** [comment]
There were some changes made to how colors work rather recently - if by chance it looks like that for you wth an official color scheme or defaults from an older version of fish  - let me know and we can address trying to automatically reset `fish_color_autosuggestion` for 2.4.0.

**Comment by floam** [comment]
Are you sure that's fish_color_autosuggestion? The problem is the prefixed match parts.

**Comment by floam** [comment]
"br" in "brctl", etc.

**Comment by faho** [comment]
>Are you sure that's fish_color_autosuggestion @faho? The problem is the prefixed match parts.

Sorry, $fish_pager_color_match. I'd blame my color-blindness but there's no red or green involved (I think), so it's just me being a dumbo.

**Comment by feigaoxyz** [comment]
Thanks, @faho, `$fish_pager_color_prefix` is the answer for me.

@floam 
The screenshots are taken under new fish profile (by `sh -c 'env HOME=$(mktemp -d) fish'`), so I guess it is the official color scheme.
And I used iTerm with default "Dark Background" and "Light Background" color presets, respectively.

**Comment by DivineGod** [comment]
I switched to a light theme and encountered this issue as well, some digging suggest that the way the `fish_pager_color_prefix` is configured at default is with a `white --bold --underline` which is used in [`highlight.cpp`](https://github.com/fish-shell/fish-shell/blob/a928517e95aa0c3886749c4403f464d93ed5da4f/src/highlight.cpp#L42)

More intuitively would be if any color definitions would use the thematic definitions of colors and those colors should in turn probably rely on `(set_color ...)` in any fish config

**Comment by changyuheng** [comment]
https://github.com/fish-shell/fish-shell/blob/49e98cde4cdcbe7ab0d61f43325d3b9ea81a1f5e/share/functions/__fish_config_interactive.fish#L35
By running this file, the suggestion color will be very light so it's hard to read in light background.
The default color scheme has been changed since https://github.com/fish-shell/fish-shell/commit/90e535f66f27e2ef39f8522840abb74db12d2f17

**Comment by morberg** [comment]
I don't think changing the color theme in fish sets any `fish_pager_color_*` variables, only `fish_color_*` seems to be affected?

**Comment by faho** [comment]
>I don't think changing the color theme in fish sets any fish_pager_color_* variables, only fish_color_* seems to be affected?

Yes, that's true. No theme currently includes pager colors. In general the fish_config colorscheme stuff could use some love (ideally the color schemes would also be available without going via js, to make an in-terminal colorscheme-picker). Patches very much welcome!
