### ISSUE TITLE
What IDE/editor support fish?

### ISSUE THREAD

**Issue by edouard-lopez** [fish-shell/fish-shell#3413]
I created a small package to add basic [fish syntax highlighting in JetBrains](https://github.com/edouard-lopez/fish-syntax-highlighting) products (_i.e._  Pycharm, IntelliJ, WebStorm, PHPStorm, etc.). 

But I was wondering if there is any -lighter- **IDE/editor that support `fish` syntax/code completion?**

**Comment by faho** [comment]
There is [vim-fish](https://github.com/dag/vim-fish) and [emacs-fish](https://github.com/wwwjfy/emacs-fish).

Since emacs is the only editor anyone should ever need (*ducks*), that should be sufficient. :laughing:

**Comment by onodera-punpun** [comment]
I'm using micro (https://github.com/zyedidia/micro), I wrote some fish addons that calls fish_indent, and some pretty good working fish syntax file.

**Comment by jinliu** [comment]
vscode has fish highlighting, too.

**Comment by chamini2** [comment]
[atom/atom](https://github.com/atom/atom) has syntax highlighting and code snippets

**Comment by faho** [comment]
I think this has now been answered. Let's close this.

Of course if you have another editor to mention, feel free to do so.
