### ISSUE TITLE
string command fails if input starts with a dash

### ISSUE THREAD

**Issue by sijad** [fish-shell/fish-shell#3416]
- [X] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [X] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:

fish, version 2.3.1

**OS/terminal used**: 

macOS Sierra 10.12 (16A323)

running `string` with a  dash `-` in input will fails.

## Reproduction steps
1. run `string sub -l 1 '-test'` for instance.

## Results
```console
~ $ string sub -l 1 '-test'
string sub: Unknown option '-test'

       string ‐‐ manipulate strings

   Synopsis
       string length [(‐q | ‐‐quiet)] [STRING...]
       string sub [(‐s | ‐‐start) START] [(‐l | ‐‐length) LENGTH] [(‐q | ‐‐quiet)]
                  [STRING...]
       string split [(‐m | ‐‐max) MAX] [(‐r | ‐‐right)] [(‐q | ‐‐quiet)] SEP
                    [STRING...]
       string join [(‐q | ‐‐quiet)] SEP [STRING...]
       string trim [(‐l | ‐‐left)] [(‐r | ‐‐right)] [(‐c | ‐‐chars CHARS)]
                   [(‐q | ‐‐quiet)] [STRING...]
       string escape [(‐n | ‐‐no‐quoted)] [STRING...]
       string match [(‐a | ‐‐all)] [(‐i | ‐‐ignore‐case)] [(‐r | ‐‐regex)]
                    [(‐n | ‐‐index)] [(‐q | ‐‐quiet)] [(‐v | ‐‐invert)] PATTERN [STRING...]
       string replace [(‐a | ‐‐all)] [(‐i | ‐‐ignore‐case)] [(‐r | ‐‐regex)]
                      [(‐q | ‐‐quiet)] PATTERN REPLACEMENT [STRING...]

string: Type 'help string' for related documentation
```

**Comment by sijad** [comment]
`echo '-test' | string sub -l 1` works. I'm not sure if it's a real bug or not.

**Comment by krader1961** [comment]
This is normal behavior. Nearly all of our commands use classic getopt behavior which allows flags to appear anywhere on the command line. Standard practice is to use `--` to tell getopt to stop looking for additional flags. For example, `string sub -l 1 -- '-test'`. In general it's a good idea to use `--` unless you know the following arguments cannot begin with a dash.

**Comment by reitzig** [comment]
Quite a gotcha! Would it be possible to probide a more helpful error message? Seems to me the error scenario is quite specific.

**Comment by faho** [comment]
Unfortunately no, because we have no way of knowing whether you meant to provide an option but typoed it or not.

**Comment by reitzig** [comment]
We don't know _which_ option it is, but we know the two options. Are there more?

Dumping the man page there for sure doesn't help -- it doesn't even mention the issue at hand, nor the solution! `help string` sends us to the full command reference. 
Maybe it's standard practice; I know I've seen the need for adding `--` before. But when an error message as the OPs (sometimes) bubbles up out of some script or function it can be hard to see what's happening.

How about something like this?

```
~ $ string sub -l 1 '-q something'
string sub: Unknown option “-q something”

Did you mean:
 - string sub -l 1 -q 'something'
 - string sub -l 1 -- '-q something'
```

The first option could even be dropped if it's known that `-xyz` is not a valid parameter.

**Comment by zanchey** [comment]
Suggesting `--` seems like a reasonable thing to do for `string`, although I don't know how easy the argument handling framework makes it.
