### ISSUE TITLE
terminal side artifacts?

### ISSUE THREAD

**Issue by gertcuykens** [fish-shell/fish-shell#3421]
I have side artifacts in my fish, version 2.3.1 OSX terminal see borders of terminal screenshot. Looks like a grey [  and  ] on each side?

![image](https://cloud.githubusercontent.com/assets/863731/19062062/b6f24e9a-89f6-11e6-9481-0e2499d7fbcb.png)

PS Everything else is working smooth out of the box

**Comment by floam** [comment]
What you are seeing are Marks, a Terminal.app feature, working correctly.

Terminal.app will identify lines which have a prompt. You can navigate back through these through the menu or key combinations. If you dislike it you can disable the automatic behavior:

<img width="563" alt="marks" src="https://cloud.githubusercontent.com/assets/291142/19063046/1b74e3f2-89b4-11e6-8c33-4f529259bf45.png">

**Comment by gertcuykens** [comment]
Thank you :D closing
