### ISSUE TITLE
tab special input function

### ISSUE THREAD

**Issue by gertcuykens** [fish-shell/fish-shell#3424]
I would like to set a rule that pressing tab will block at the input cmd line if there are multiple suggestions and just wait for me to manually press the down button to go into the select menu or  wait for me to simple start typing more characters.

Example fish, version 2.3.1
![image](https://cloud.githubusercontent.com/assets/863731/19096231/17153518-8a9b-11e6-8bba-224ec4efb06e.png)

Until now everything fine but here's where I get frustrated a little :)
![image](https://cloud.githubusercontent.com/assets/863731/19096266/4948c266-8a9b-11e6-8314-1a8849e5cbcd.png)

Once you are in the menu you can't go back to the letters you typed. Meaning you have to back space all the way back to the letter `h` if you wanted to type `hi` for example instead of `he` 

Al I ask is a config rule that stops tab from entering the menu and simple stop doing anything at all unless there is only one possible completion left or I press the down button manually to select.

The tab should just be ignored until I type more text or press the down arrow to go into the menu.

My proposal is a `set fish_tab wait` that enables tab to wait for more key characters behavior.

Or to put it in other words tab never goes into menu mode without pressing the down arrow :) , just showing more suggestions is no problem if there are many more but the cursor and cmd input line should not change.

PS A similar style of tab completion can be tested by using vscode for example, where tab always completes the first solution and never goes into menu mode no matter how many solutions there are. It does show the menu but tab never goes in it.
![image](https://cloud.githubusercontent.com/assets/863731/19096126/6dda1cb6-8a9a-11e6-8aa9-9ea11f3bf07d.png)

EDIT: faho idea for a new special bind function instead of flag is way better
https://fishshell.com/docs/current/commands.html#bind

EDIT2: ridiculousfish idea backspace exit like esc is the best so far I think

**Comment by floam** [comment]
For me hitting the escape key works to "back out".

**Comment by floam** [comment]
(Annoyingly though, it used to be instant but the delay added in recent times adds some inertia you must fight to do this.)

**Comment by krader1961** [comment]
> it used to be instant but the delay added in recent times adds some inertia you must fight to do this.

We can undoubtedly do better here but as a quick-fix if you're not using vi-mode does `set -u fish_escape_delay_ms 10` improve the experience? If you're using vi-mode you can also try other values less than 300 which is the default but note that depending on numerous factors the smaller the escape delay the more likely it is you'll see weird behavior. We might even want to lower that default timeout value since very few people are likely to be using vi-mode in an environment where obscene delays occur between the escape char and the next character other than when the [escape] key is pressed. And that will almost always be because the user wants to go from insert to normal/command mode.

**Comment by gertcuykens** [comment]
`Esc` works, and I can imagine for users that also use the vim editor current behavior is perfect and natural. For the users that uses notepad however they go `...%$&^*&*(&!!!` :D I am only suggesting a optional set flag unless I am forgetting a scenario where it's going to get very difficult to implement?

**Comment by floam** [comment]
It may make sense to have vi mode and emacs mode have different behavior here?

**Comment by faho** [comment]
@floam: They already do. emacs mode timeout is lower than vi.

@gertcuykens: What I would suggest here is, instead of some weird variable (which is something we try to keep to a minimum) a different bind command - "complete-no-page" or something like that. This will need changes to the c++ code, specifically reader.cpp.

**Comment by gertcuykens** [comment]
You mean like `bind \t complete-no-page` right? That would be even better :D I don't know about the fish naming conventions I leave that up to you. But binding tab to an alternative behavior sounds awesome and way better than using a set flag.

**Comment by ridiculousfish** [comment]
What if delete did the same as escape here: close the menu and restore the command line? That seems natural to me.

**Comment by gertcuykens** [comment]
Also very nice idea :D and probably better solution then mine, but is it much work to implement? I would like to try it out :D

**Comment by ridiculousfish** [comment]
You can do it with bindings like so:

    bind \x7f 'if commandline --paging-mode ; commandline -f cancel; else; commandline -f backward-delete-char; end'

**Comment by gertcuykens** [comment]
This is sooo much better, thanks :D I even think floam will like this beacuse its instand without delay. Please consider this default, i am sure allot of people are going to like this :)

**Comment by floam** [comment]
I dig it. Delay aside, this makes a lot of sense to me on backspace.

**Comment by ridiculousfish** [comment]
We already have some logic in the C++ to end paging on backspace; probably that's where this should be fixed.

**Comment by faho** [comment]
This seems basically solved with the changes to the pager system - we no longer search immediately, so it's much easier to get out of the pager.

**Comment by ridiculousfish** [comment]
Thanks for this amazing cleanup of old issues 😍
