### ISSUE TITLE
On start fish prints unknown escape sequence ESC]7

### ISSUE THREAD

**Issue by legovini** [fish-shell/fish-shell#3425]
When I start fish in the "st" terminal I get the following error:

erresc: unknown str ESC]7

meaning that the terminal got that unknown escape sequence. (In order to see this error it is necessary to start the terminal from another terminal, as the message is printed to stdout/stderr.)

What is this sequence for?
Shouldn't fish check for the terminal capabilities before sending escape sequences?

**Comment by faho** [comment]
> Shouldn't fish check for the terminal capabilities before sending escape sequences?

We do. What is your $TERM set to? Most likely it's not the correct value - AFAIK that should be `st-256color`.

**Comment by legovini** [comment]
It is correctly set:

```
$ echo $TERM
st-256color
```

**Comment by faho** [comment]
I think I've found the sequence. We integrate with certain terminals (vte and apple terminal.app) and do 

`printf \e\]7\;file://\%s\%s\a (hostname) (echo -n $PWD | __fish_urlencode)`

Only, this is only triggered `if test "0$VTE_VERSION" -ge 3405 -o "$TERM_PROGRAM" = "Apple_Terminal"`. Is either of those conditions true? It should _not_ be in st.

**Comment by legovini** [comment]
OK, then the problem is that if I start `st` from a VTE terminal it inherits `VTE_VERSION`, and then fish thinks it's a VTE terminal. Not sure if there's an easy way to prevent this.

**Comment by faho** [comment]
Add

```fish
if string match -q "st-*" "$TERM"
    set -e VTE_VERSION
end
```

to your config.fish.

We can't support it in general since there's no way to enumerate all $TERM values for vte-based terminals.

**Comment by legovini** [comment]
Thanks for the quick reply and workaround!
