### ISSUE TITLE
Automatically add `.exe` on Windows for unknown commands

### ISSUE THREAD

**Issue by jhasse** [fish-shell/fish-shell#3428]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations _(check `sh -c 'env HOME=$(mktemp -d) fish'`)_?

**fish version installed** _(`fish --version`)_: 2.3.1

**OS/terminal used**: MSYS2 on Windows

On Windows (with MSYS2, haven't tried Cygwin) running a command automatically adds `.exe` if needed. It would be great if this was also considered when searching packages for unknown commands.
## Reproduction steps
1. Type an unkown command, like `tree`
2. No suggestion which package to install. Add `.exe` will work though.

## Results

``` console
> tree
fish: Unknown command 'tree'
> tree.exe
tree.exe may be found in the following packages:
  msys/tree 1.7.0-1     /usr/bin/tree.exe
```

**Comment by krader1961** [comment]
For anyone wondering where that logic exists it's the `__fish_command_not_found_handler` function defined in *share/functions/__fish_config_interactive.fish*.

**Comment by faho** [comment]
Which handler is that? msys uses arch's pacman, does it also have pkgfile? The output certainly looks like it.

Just to be clear, if you _had_ installed `tree`, running `tree` would run `tree.exe`? How is that realized? With symlinks?

I'm actually a bit surprised that they haven't patched pkgfile to do that as well.

**Comment by jhasse** [comment]
> Which handler is that? msys uses arch's pacman, does it also have pkgfile? The output certainly looks like it.

Yes, I've forgot to mention that: I have pkgfile installed and it wouldn't work at all without it.

> Just to be clear, if you had installed tree, running tree would run tree.exe? How is that realized? With symlinks?

Yes, both `tree` and `tree.exe` work. I don't know how that's realized, but I'm pretty sure it isn't symlinks, because Windows doesn't support them out-of-the-box.

> I'm actually a bit surprised that they haven't patched pkgfile to do that as well.

You're right, this might actually be a pkgfile bug rather then a fish bug.

```
pkgfile --binaries --verbose -- tree
```

should also search for tree.exe on Windows. I'll create an issue for MSYS2.

**Comment by krader1961** [comment]
@jhasse, Do you now believe this is not something fish should be enhanced to deal with? As @faho pointed out (and should have been obvious to me) the pkgfile command under MSYS2 should probably transparently handle this. On the other hand we're not opposed to adding workarounds for shortcomings in the environments that fish runs in. The question is whether a workaround can be implemented cleanly and with minimal overhead and without causing additional problems (i.e., breaking existing behavior).

**Comment by jhasse** [comment]
Yeah, this should probably be handled by MSYS2 or maybe even by pkgfile. I've created an issue (see above) for it.

**Comment by zanchey** [comment]
In that case, I'll close this issue as "not for fish".
