### ISSUE TITLE
Fish tries to read non-existent /etc/mtab under FreeBSD for mountpoints autocompletion

### ISSUE THREAD

**Issue by PenegalECI** [fish-shell/fish-shell#3431]
- [ ] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed**: 2.2.0 (FreeBSD packaged version)

**OS/terminal used**: FreeBSD 10.3-RELEASE-p7

fish uses a FreeBSD-incompatible way to retrieve mountpoints for autocompletion, disturbing output at the same time.

## Reproduction steps
Try to autocomplete a mount point, for example after typing `umount`

## Results
```
penegal@Aethelthryth-FreeBSD ~> umount /mecat: /etc/mtab: No such file or directory
dia/discat: /etc/mtab: No such file or directory
k
```

Looks like fish attempts to read `/etc/mtab` to autocomplete in this case, but, as this file does not exist under FreeBSD, it fails and disturbs output by repeating `cat: /etc/mtab: No such file or directory` on each press on the ↹ key. It should use a FreeBSD-compatible way to do so, for example by reading the `mount` output; this way could replace the current one, making it more portable at the same time, as the output of `mount` is similar on all Unix flavors, at least all the ones I know about: Linux (Debian), FreeBSD and macOS.

Note that I report the bug here instead of to the FreeBSD package maintainer, as it is unlikely that the package maintainer added a FreeBSD-specific bug.

**Comment by faho** [comment]
This has already been fixed by 78d4f22ce4cc017a9955c02b42f5d653a3b43f5f.

Please upgrade to 2.3.0.
