### ISSUE TITLE
FreeBSD: LANG environment variable sent via ssh is not set

### ISSUE THREAD

**Issue by karolyi** [fish-shell/fish-shell#3434]
**fish version installed** *(`fish --version`)*:
fish, version 2.3.1

**OS/terminal used**: 
OSX Terminal

Talk about the the issue here. 
Hey,

I just changed to fish as my default shell on my server, and after logging in, I realize that the `LANG` variable previously set with bash is not set with fish, when I login via Terminal and ssh. Setting `LANG` worked before with using bash.

## Reproduction steps
1. setup SendEnv/AcceptEnv with LANG accordingly
2. login, and then echo $LANG outputs nothing

![image](https://cloud.githubusercontent.com/assets/987055/19192223/d92c28f8-8ca5-11e6-99e2-fa2ff5aac402.png)

## Results
```console
karolyi@flix ~> echo $LANG

karolyi@flix ~> 
```

**Comment by karolyi** [comment]
I can try to test this with an ubuntu virtual machine later on, if needed.

**Comment by faho** [comment]
I have an archlinux client and debian server (meaning I connect from arch to debian), and for me it works with both bash and fish, after I removed the "LANG=" line from /etc/default/locale. Before the changed locale would never be visible because it would immediately be trampled.

Maybe BSD is doing something similar here?

**Comment by karolyi** [comment]
okay, it seems it's my bad, wrongly targeted fish when I have had targeted FreeBSD itself. it's controlled by `login.conf`, and it seems that openssh's acceptenv stopped working. or, it still works but the freebsd system overrides it by login.conf.

**Comment by karolyi** [comment]
I don't think any users will arrive here with the same problem, but here's the solution:

Preliminary condition:
Set the `SendEnv` and `AcceptEnv` directives in their respective `ssh_config` and `sshd_config`

Linux:
like @faho said, comment out `LANG` in `/etc/default/locale`

FreeBSD:
-if you have any `lang` lines enabled in `/etc/login.conf` or `~/login_conf`, uncomment it, since it will override your sent environment settings.
