### ISSUE TITLE
fish no longer builds on cygwin

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3435]
I wanted to verify that the changes I'm making to silence a bunch of warnings about signed to unsigned comparisons didn't break fish on windows (since some of the changes involve #define's used in comparisons to wchar_t).

The first thing I noticed is that the final link phase fails with an error about not finding the `basename()` function. Hacking around that by redefining our `wbasename()` function produced a fish binary but a bunch of unit tests are now failing. Including the tests for `printf`:

```
$ printf "Hello %d %i %f %F %g %G\n" 1 2 3 4 5 6
Hello 1 2 3.000000 4.000000 5 6
```

That's the expected result. Here is what is happening now:

```
$ printf "Hello %d %i %f %F %g %G\n" 1 2 3 4 5 6
Hello 1 2 0.000000 0.000000 1.29002e-4944 1E+9999
```

git-bisect shows that this is due to commit 30b71fbb7807730922f0699823eddfffd02dcba0. Comparing the *config.h* files from that commit and the prior commit the only difference is the good build includes `#define HAVE_NAN 1`. The *Makefile*'s are radically different as expected due to the nature of the commit that broke fish on Cygwin. But the most significant difference is we went from `CXX = g++` to `CXX := clang++`.

When I'm home again I'll see if manually reverting the one key difference in each of the *config.h* and *Makefile* files produces a fish which passes the unit tests and doesn't require hacking `wbasename()`. It may be that simply forcing the use of g++ on Cygwin is all that's needed.

**Comment by krader1961** [comment]
Should this be a blocking issue for the 2.4.0 release? We have a link to Cygwin at fishshell.com but it's not clear who updates the Cygwin fish package.

**Comment by krader1961** [comment]
I have confirmed that changing the two aforementioned lines in *config.h* and *Makefile* after running `autoconf; ./configure` produces a working fish and all of the unit tests which had been passing in the previous commit now succeed (there are a few tests that fail regardless of this issue).

@floam, Can you take ownership of this and ensure that when building on Cygwin we always use g++? Alternatively, fix whatever is wrong when using clang++?

**Comment by floam** [comment]
So git master works with `make CXX=g++`? Nuts.

**Comment by floam** [comment]
And that's a build error it fixes, or the printf bug?

**Comment by floam** [comment]
I decided to just go back to letting autoconf do it's thing here. 

@krader1961 can you confirm this fixes things?

**Comment by floam** [comment]
Didn't really mean to close this, it really isn't fixed until we can make sure fish builds on clang on Cygwin IMO.

**Comment by krader1961** [comment]
I've verified this has been fixed by reverting back to g++ on Cygwin.

There are still plenty of problems (e.g., the universal var notifier stuff doesn't work) but as best I can tell those problems have been present for a very long time. Certainly predating my attempts to use fish on Cygwin a year ago.

@zanchey, Not sure if you need to do anything to ensure the Cygwin fish package corresponding to our 2.4.0 release includes this fix.

**Comment by krader1961** [comment]
FWIW, I like the attempt to force the use of clang++ since it is generally a better compiler. I would be happy to see that aspect of @floam's earlier change reinstated if an exception can be easily made for building on Cygwin using g++. At least until such time as clang++ has comparable behavior to g++ on that platform.

**Comment by floam** [comment]
I agree - but without access to or experience with Cygwin I'm going to have to leave that to someone else to try to fix before reinstating the behavior.

**Comment by andrex-e-schulman** [comment]
FYI, I maintain the fish package for Cygwin. If there are build failures or workarounds I need to know about, please mention me in the ticket and I'll pay attention.

fish 2.4b1 builds fine in Cygwin BTW.
