### ISSUE TITLE
brew info auto completion is broken

### ISSUE THREAD

**Issue by goofansu** [fish-shell/fish-shell#3436]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(2.3.1)*:

**OS/terminal used**: macOS 10.11.6 / iTerm2

`brew info` auto completion is broken.

## Reproduction steps
1. `brew info co` then press `tab`
2. error in shell
    ``` bash
    No matches for wildcard '$formuladir/*.rb'.                                                                                                                                                                          11:38:27
![image](https://cloud.githubusercontent.com/assets/1143191/19217773/037ccf6a-8e16-11e6-87bb-89acb40e96c9.png)

/usr/local/Cellar/fish/2.3.1/share/fish/completions/brew.fish (line 3):     ls $formuladir/*.rb | sed 's/.rb$//' | sed "s|^$formuladir||"
                                                                               ^
in function '__fish_brew_formulae'
	called on standard input

in command substitution
	called on standard input
    ```

![image](https://cloud.githubusercontent.com/assets/1143191/19217774/0859187c-8e16-11e6-9580-2774d16a92b6.png)

**Comment by krader1961** [comment]
I can not reproduce this problem. I am using fish built from git head. It appears to have been fixed by commit ca929e08 which was merged after the 2.3.1 release. I am pretty confident this has been fixed. @goofansu are you able to build and test from git head to confirm my conclusion?

**Comment by goofansu** [comment]
@krader1961 I installed fish via homebrew. I'll build from git head and give you feedback later.

**Comment by faho** [comment]
This was just what 5dd959070ce9b1af98634b8731e9ef7b0563c637 addressed.
