### ISSUE TITLE
fish_tests.cpp has unused parameter "notifier" in static function

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3439]
```
src/fish_tests.cpp:2402:68: warning: unused parameter 'notifier' [-Wunused-parameter]
static void trigger_or_wait_for_notification(universal_notifier_t *notifier,
```

Now that we have a clean build (i.e., no spurious warnings from the compiler) I noticed that `make test` produces the above warning. 

@ridiculousfish it looks like you wrote that code in 2014-05-01 with commit 186b0f62. It looks to me like the test isn't doing what was intended. Or perhaps it is and the notifier parameter is simply not needed to verify the behavior and can be dropped.

**Comment by krader1961** [comment]
Oy Vey! Given that I've complained about being assigned to an issue by someone else without my consent I feel the need to say "mea culpa" in this instance. In my defense I think it was justified since you wrote the code under discussion and therefore are the person in the best position to determine the appropriate fix.

**Comment by ridiculousfish** [comment]
No problem! I don't mind at all.

**Comment by krader1961** [comment]
As part of fixing issue #3587 I'm just going to remove the unused `notifier` parameter. We can always reinstate it if the tests are modified to require its presence.
