### ISSUE TITLE
Rename _ function to make clashes harder

### ISSUE THREAD

**Issue by Dietr1ch** [fish-shell/fish-shell#3451]
I've just had a fun time debugging the error that `alias _=sudo` introduces on autocompletion.

`_` is a nice identifier to waste on gettext.

The problem should be independent of these, but still:
**fish version installed** *(`fish --version`)*:
fish, version 2.3.1
**OS/terminal used**: 
manjaro (arch) / yakuake (konsole)

**Comment by krader1961** [comment]
It's probably too late to change that convention. First, it's also used in the C++ code. Consistency between the C++ and fish script code is a good thing (at least for people making changes to the fish source code). Second, there may be third-party fish scripts which now expect `_` to be a function that performs localization of the string. Third, it's a fairly standard convention in many languages that an identifier that starts with an underscore is "private" to the implementation. The obvious exception being the `$_` variable. However, The fish definition of that variable is different than that of bash/zsh and fish doesn't allow `set _ abc` so it's moot.

**Comment by Dietr1ch** [comment]
Yes, I thought of outside the project code, probably most of completions are set up elsewhere, and that could make this change take long (thanks debian),  but still it's possible to make it.

At least, a huge warning should be issued if internals are being changed. A lot of time passed between I migrated my aliases and when some completions started failing, so the alias was not obviously the problem.

**Comment by krader1961** [comment]
> a huge warning should be issued if internals are being changed

That is impossible in general. What would you expect fish to do if you defined functions named `man`, `type`, `help`, etc.? Those, and many more, are all functions that could be considered "internal" in that they provide core functionality for fish that if carelessly redefined would confuse people. If you know what you are doing do you really want a "huge warning" to be issued if you redefine those functions? See issue #3000 for an example of why this is non-trivial. And that issue only deals with defining functions that shadow builtin commands. What you're proposing here is more complex.

**Comment by Dietr1ch** [comment]
@krader1961 on #3000 you propose to warn on shadowing and add a flag to ignore the warning. That would do.  The goals is to only be able to shoot yourself on purpose.

**Comment by krader1961** [comment]
> you propose to warn on shadowing and add a flag to ignore the warning. 

Yes, and I actually implemented that solution. Which was then reverted because it caused more problems than it solved. 😃  In other words you need to provide more details about how you expect your proposal to work especially with regard to backward compatibility.

**Comment by Dietr1ch** [comment]
Hmm, that other patch should be preceded with one allowing unknown options on functions, but then similarly, how could you get help on typos on function options?

Maybe unknown options need to be allowed and generate less visible warnings? That would allow to extend functions options in the future (and someday merge the `--shadow-builtin`). A step onto this kind of extensibility has to be taken someday.

Damn, small changes are incredibly harder when you have to maintain old unattended machines :/

**Comment by krader1961** [comment]
> Damn, small changes are incredibly harder when you have to maintain old unattended machines

Yes, breaking backward compatibility is normally only acceptable when changing the major release number of a project and even then needs a lot of discussion and planning (consider going from Python 2 to 3). We have made backward incompatible changes with minor releases. But only when the behavior being changed has existed for a short interval and changing the behavior is deemed so valuable, and the risk of breaking existing users so small, that the change is justified. That is not the case with your proposal.

> that other patch should be preceded with one allowing unknown options on functions

How exactly would that work without introducing other problems? You seem to be suggesting that invoking `_` as `_ --unknown-flag` should be silently allowed by ignoring `--unknown-flag`. Or did I completely miss your point?

**Comment by Dietr1ch** [comment]
> How exactly would that work without introducing other problems? You seem to be suggesting that invoking _ as _ --unknown-flag should be silently allowed by ignoring --unknown-flag. Or did I completely miss your point?

Sorry, I should avoid using deixis here (like there :P).
I meant that a patch should allow unknown identifiers, and be out for a while, before trying to make the patch for `shadow-builtin`.

**Comment by faho** [comment]
>It's probably too late to change that convention. First, it's also used in the C++ code.

I feel it's important to note that it's not just our thing - this is a gettext thing, which is rather widespread.

You want the function name for localization to be as short as possible because you want it to distract from the code itself as little as possible. "_" is kinda meaningless, but fits this purpose nicely. Since it's a convention, the chances of people understanding it are maximized. For any other function, this is an awful name. You don't want to use it.

That means I'm against this.

**Comment by Dietr1ch** [comment]
Considering that convention, then it's probably a bad idea to ignore it.
