### ISSUE TITLE
NO man page for fish itself?

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#3455]
I build and install fish-shell from the latest git source with the following command:

    autoconfig
    /configure --prefix=/usr; make
    sudo make install

building the last step, is is saying:

    Installing more man pages
    /usr/bin/install: cannot stat ‘share/man/man1/fish.1’: No such file or directory                                               
    /usr/bin/install: cannot stat ‘share/man/man1/fish_indent.1’: No such file or directory
    /usr/bin/install: cannot stat ‘share/man/man1/fish_key_reader.1’: No such file or directory
    Checking for legacy binaries...

and **man fish** says:

    No manual entry for fish
    See 'man 7 undocumented' for help when manual pages are not available.

How to fix this?

**Comment by zanchey** [comment]
My guess is you don't have an appropriate version of Doxygen installed - you will need 1.8.7 or newer (per the README).

**Comment by zanchey** [comment]
(See #2159, #1598, #124.)

**Comment by zanchey** [comment]
@c02y, did this solve your problem?

**Comment by c02y** [comment]
Yes, I got the point, my doxygen is old. Thanks.
