### ISSUE TITLE
CDPATH not defined by default

### ISSUE THREAD

**Issue by nhooyr** [fish-shell/fish-shell#3463]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version 2.3.1

**OS/terminal used**: 
macOS Sierra 10.12 and iterm2 3.0.10

https://fishshell.com/docs/current/index.html#variables-special says "By default, the fish configuration defines CDPATH to be a universal variable with the values . and ~."

But I do not have any such variable defined. aka `echo $CDPATH` does nothing.

And `cd Documents` (where Documents is a folder in `~`) throws an error.

**Comment by krader1961** [comment]
The docs need to reflect the behavior of the C++ code as this comment in the code explains:

```
// 1. An empty CDPATH should be treated as '.'
```

Care to create a PR for us, @nhooyr ?

**Comment by faho** [comment]
I have removed this from the documentation in 4acfdcb0a0d5b26aba0991af4141965e1ca59e3d (after seeing it on gitter).

We no longer set CDPATH by default since 0e4f2cca01ea911e9b6efabe1b2ae4d3eb1d0ec0.
