### ISSUE TITLE
Weird behavior where autocomplete suggestions appear over existing text if not enough empty space at bottom

### ISSUE THREAD

**Issue by prasant94** [fish-shell/fish-shell#3464]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations _(check `sh -c 'env HOME=$(mktemp -d) fish'`)_?

**fish version installed** _(fish, version 2.3.1-627-ge8ed45e)_:

**macOS Sierra v10.12/Terminal Version 2.7 (377)**: 

If there is not enough room for autocomplete suggestions to appear at the bottom, instead of pushing the existing text up, the suggestions appear over the text and the prompt and the command are overwritten as well.
## Reproduction steps
1. Execute a command who's output reaches the bottom of the screen.
2. Type a small portion of a command and hit tab

couldn't install asciinema but here's a gif:
![screencast_fish_bug](https://cloud.githubusercontent.com/assets/6421803/19415415/41a66b8a-938d-11e6-9b34-dc08fe2ce940.gif)
## Results

Last few lines of the existing output will be overwritten by the suggestions including the prompt and the command we typed.

**Comment by faho** [comment]
So, this is weird and I've never seen it.

It seems related to the terminal - can you try a different one? I hear good things about iTerm2.

Also, can you consistently reproduce this, or does it depend on the kind of output?

Can anyone else reproduce this? @krader1961, @floam?

**Comment by prasant94** [comment]
> can you try a different one? I hear good things about iTerm2.

Works fine with iTerm2.

> Also, can you consistently reproduce this, or does it depend on the kind of output?

Yes, same behavior every time.

**Comment by floam** [comment]
What version of Terminal.app?

**Comment by prasant94** [comment]
Version 2.7 (377)

**Comment by floam** [comment]
That's MacOS Sierra. Same one I'm running. I can't seem to reproduce it though. Maybe I need to study your screen capture longer...

**Comment by prasant94** [comment]
Here's a different screencast of the same behavior in case the initial one isn't clear. This one doesn't show the keystrokes though.

https://asciinema.org/a/er0e2pe0vzmocq1ke5rxyo9t6

**Comment by krader1961** [comment]
I can't reproduce this using fish built from git head. I strongly suspect `$TERM` is set incorrectly or possibly a bug we've already fixed.

@prasant94, Feel free to reopen this if you can reproduce using fish 2.5.0 or newer. Please include the value of `$TERM`. I would also first run `script completion.txt`, type the absolute minimum to reproduce the problem, then exit that subshell and upload *completion.txt*.
