### ISSUE TITLE
complete -C fails when recursing?

### ISSUE THREAD

**Issue by Ambrevar** [fish-shell/fish-shell#3474]
fish: 2.3.1, Arch Linux, urxvt 9.22

Enter `complete -C"type p"`: only functions and builtins will get printed.
`type` has the following completion definition:

`complete -c type -a "(complete -C(commandline -ct))" -x`

Can you confirm the issue?

**Comment by faho** [comment]
Yes, I can reproduce this one. I could swear that it has already been reported, but I can't find that report currently.

The cause is probably that the inner `commandline` still gets the _real_ commandline, while `complete -C` should enter an environment with a fake one.

**Comment by krobelus** [comment]
This might be the same issue:
```
$ complete -c xx -fa 'arg'
$ complete -c zz -fa '(complete -C"xx ")'
$ complete -C"zz " # prints nothing (expected: arg)
```

Observe that interactive completion `zz <TAB>` completes `arg` just fine.

**Comment by krobelus** [comment]
Apparently fish has never supported recursive calls to `complete`, going back to when `complete` was added. Perhaps this can be changed now (or at least print a warning informing the user).
https://github.com/fish-shell/fish-shell/commit/521d09b6d0264aaac17b9359ebcb1a0cb6ca8906#diff-886dfa5a4f8c2403307d30799f49b9efR460
