### ISSUE TITLE
Request: option to strip escape sequences in string command

### ISSUE THREAD

**Issue by alphapapa** [fish-shell/fish-shell#3476]
In my prompt, based on the terlar git prompt, I use both right-side and left-side strings.  I use the length of the left string to calculate how many spaces to insert to align the right string at the right edge of the terminal.  However, this does not work well when in a directory with a git repo, because the terlar git prompt inserts colored strings, and the control characters are counted by `wc` even though they don't affect the visible length of the string.

One can use, e.g. `sed` to remove the control characters, but this adds yet another process to be run on every prompt invocation.  Not a big deal, however...

It would be very nice if the new `string length` builtin had an option to ignore control characters when calculating the length of the string.  This would be much faster and more lightweight than using two external processes (`sed` and `wc`).  :)

Thanks.

**Comment by krader1961** [comment]
Perhaps I'm misunderstanding why you need this feature. But nearly all terminals use some variant of the X3.64 standard. And in that standard for setting visual attributes a "CSI" is used (typically `\e[`) followed by non-control characters. For example:
 
```
$ set_color blue | od -tx1z
0000000 1b 5b 33 34 6d                                   >.[34m<
0000005
```

Just ignoring the escape, the only control char in that sequence, will give you an accurate count of the visible characters.

**Comment by floam** [comment]
We have a function in C++ that tries to do this. It's not super straight-forward.

**Comment by faho** [comment]
Also, if we did this, it would be $TERM specific. Many sequences are reasonably well-supported, more are reasonably well-ignored (I can send truecolor sequences to emacs ansi-term and it'll strip them), but others aren't.

As a concrete example, this will have length 0 in e.g. konsole/terminal.app/vte-based terminals, but the length of `7;file://$PWD\a` (where $PWD is url-encoded) in ansi-term:

```fish
printf \e\]7\;file://\%s\%s\a (hostname) (echo -n $PWD | __fish_urlencode)
```

Also, wouldn't this be more useful as a separate command, `string strip` or so, that just returns the characters that will be printed literally?

**Comment by floam** [comment]
> Also, wouldn't this be more useful as a separate command, string strip or so, that just returns the characters that will be printed literally?

Something that strips the input (whether that's a dedicated subcommand, or somehow an option to `trim` or `escape`) makes sense to me, since folks can just `string length` it and it's sometimes wanted to get that output.

**Comment by alphapapa** [comment]
> Just ignoring the escape, the only control char in that sequence, will not give you an accurate count of the visible characters.

@krader1961 Oops, I meant escape sequences, not control chars.  I updated the title.  Thanks.

> Also, wouldn't this be more useful as a separate command, string strip or so, that just returns the characters that will be printed literally?

Yeah, that would be composable and seems to make sense.  It would still be plenty fast being a builtin.  I'll change the title to that...

**Comment by floam** [comment]
Actually, stripping and getting the length of that doesn't solve every problem. Consider escape sequences which would widen the output.

**Comment by faho** [comment]
>Consider escape sequences which would widen the output.

Any examples? I can't come up with any.

Of course there's additional issues - how long is `foo\rbar`? `string length` says it's 7. It might also be 3 if its on its own line, or 3 + something else + another 3 if its on the same line as something else (`echo -s ggggg foo\rbar` - here 5 + 7 = 8).

**Comment by floam** [comment]
> Any examples? I can't come up with any.

So, imagine a string starting with 'x', followed by an escape to move the cursor to right 10 columns, then another 'x'.

**Comment by floam** [comment]
(This isn't meant to be an argument against implementing what this PR wants - not something this needs to cover.)

**Comment by alphapapa** [comment]
> Of course there's additional issues - how long is foo\rbar? string length says it's 7. It might also be 3 if its on its own line, or 3 + something else + another 3 if its on the same line as something else (echo -s ggggg foo\rbar - here 5 + 7 = 8).

I guess for the purposes mentioned here, it would make sense to not count the `\r`, so the length with control/escape characters/sequences stripped should be 6.  It'd be good to make this explicit in the docs.

**Comment by faho** [comment]
>I guess for the purposes mentioned here, it would make sense to not count the \r

Well, no. Because that wouldn't get you a "display-length" that you could use to align. 

(as a sidenote, now I want to do a fish_prompt that displays on the right and a fish_right_prompt that displays on the left, just to confuse people)

**Comment by krader1961** [comment]
FWIW, zsh solves this by requiring the user to surround non-space taking sequences with `%{...}`. It also has a `%G` modifier that can be used within such sequences to specify a different width than zero. This isn't friendly but does ensure the correct length is calculated by the prompt display mechanism if the user doesn't make a mistake. I think the question boils down to whether we can implement a solution that will, without user supplied hints, calculate the correct length 99.99% of the time. If not then a zsh like solution that involves the user providing hints is better than nothing.

**Comment by alphapapa** [comment]
> Well, no. Because that wouldn't get you a "display-length" that you could use to align. 

Ah, okay.  I was thinking that the line break wouldn't matter, and would probably indicate a bug in the prompt string, but you're probably right, and it might be useful to be able to do that and still get the visual width of the string.  I guess that would require splitting the string on line breaks and taking the length of the longest one.

On that note, maybe another possibility would be to have a `--visual-width` or `--visual-length` option to `string`, which would be expressly for returning the length that would be displayed in a terminal.  That might be more clear and purposeful than a "remove escape sequences or control characters" option.

By the way, while we're talking about this, would it be a good idea to support a standard `fish_right_prompt` function that would automatically be displayed on the right edge of the terminal, starting on the same line as the left prompt?  (If so, we could discuss it on a separate issue.)

**Comment by ridiculousfish** [comment]
`fish_right_prompt` is such a good idea that it's been in for a long time ;)

**Comment by alphapapa** [comment]
> fish_right_prompt is such a good idea that it's been in for a long time ;)

Um...yeah...I forgot about that... But I have a good excuse: #1706  :)  You see, I'm using a prompt like this:
```
user@host:~/directory|git-rev                          (1h2m3s) 23/21:35:00
➤
```
The right-side string has the execution time of the last command, the current date, and current time.  The prompt is on the second line, after the arrow.  But if I use `fish_right_prompt` for the right-side string, the prompt is forced onto the same line after the git-rev.  So I have to do the whole prompt in the `fish_prompt` function and calculate the offset for the right-side string manually (which is why I need the ability to calculate the visual length of the prompt strings).

So if #1706 were solved, this issue might be moot...  :)

**Comment by Darkshadow2** [comment]
@alphapapa There's an easier way to do that. Use ```fish_right_prompt``` but add some ```tput``` commands to move the cursor:

```
function fish_right_prompt
    tput sc; tput cuu1; tput cuf 2
    
    your normal right prompt here

    tput rc
end
```

This will save the cursor position, move it up one line, and move it to the right two spaces (not sure why but it seems when you move it up one line it gets two spaces added - possibly from the escape sequences ```tput``` outputs but I'm not sure). Then your normal right prompt stuff, and at the end it restores the cursor position.

**Comment by alphapapa** [comment]
@Darkshadow2 Wow, it works!  I didn't even know tput could do that sort of thing.  Thanks!

Unfortunately, I'm not sure if it's possible to use that to achieve the effect that @stefanmaric demonstrated, with a background color set for the whole first line of the prompt.  I tried that out and like it a lot, but I guess doing that requires outputting spaces with the background color set, and the built-in `fish_right_prompt` special functionality seems to not work by outputting spaces, so there's a gap between the left and right prompts without a background color set.  I guess you can't have everything every way.  :)  Thanks, though, this is a very nice solution otherwise.

**Comment by Darkshadow2** [comment]
@alphapapa Yes, in that case, you'd still have to get the length of the string without the escape sequences to do it right. Though if you go this route (using ```fish_right_prompt```), it's probably easier to do it in ```fish_prompt```. Moving the cursor like that, it will just overwrite whatever was there, so it won't matter that the prompt put spaces in that spot. Makes it a _tiny_ bit easier to do, since you just need to figure out how long the prompt is and then write spaces to the end of the line.

**Comment by alphapapa** [comment]
@Darkshadow2 That's a great idea, thanks!

**Comment by krader1961** [comment]
I'm going to close this because there is no way for the `string` command to do everything needed. We can get pretty close but there will be enough edge cases we don't handle correctly that it seems like a bad idea to even give the user the idea that the requested solution is robust. Too, there are alternative means of solving this involving the `fish_right_prompt` function and careful use of the `tput` command.
