### ISSUE TITLE
sample fish prompts call `hostname` too often

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3480]
Some of the sample fish prompts (in *share/tools/web_config*) run `hostname` every time the prompt is displayed. That command can be slow if, for example, there is a problem with DNS. All of the prompts should use this pattern:

```
# Just calculate this once, to save a few cycles when displaying the prompt
if not set -q __fish_prompt_hostname
        set -g __fish_prompt_hostname (hostname|cut -d . -f 1)
end
```

That's from *share/functions/fish_prompt.fish*. Obviously we can now do it slightly faster using the `string` builtin.

This issue was triggered by issue #3479.

**Comment by floam** [comment]
Is there anything we can do to have the cached name time out or trigger hostname to re-run?

**Comment by faho** [comment]
>Is there anything we can do to have the cached name time out or trigger hostname to re-run if it changes?

Not really. Well, we would theoretically be able to set up some kind of notification, but that's quite a bit of code for very little gain.

This is one of the cases where you should just restart your shell if it bugs you that much.

>Some of the sample fish prompts (in share/tools/web_config) run hostname every time the prompt is displayed.

This is also an opportunity for cleanup. Even the prompts that do the right thing all have the code duplicated.

We should introduce a function, `fish_prompt_hostname` that does this caching and just echoes the hostname.
