### ISSUE TITLE
set --append?

### ISSUE THREAD

**Issue by alphapapa** [fish-shell/fish-shell#3485]
It would be nice if `set` had a `-a, --append` option so that you could do this:

``` fish
$ set list 1
$ set -a list 2
$ echo $list
1 2
```

...instead of this:

``` fish
$ set list 1
$ set list $list 2
$ echo $list
1 2
```

**Comment by krader1961** [comment]
I was thinking about proposing this same thing a few days ago. The question is whether the syntax (i.e., new flag) can be conceptually jusitfied or the speedup is worthwhile.

**Comment by faho** [comment]
This has actually already been requested - #1326. Though that goes a bit further by also requesting string-concatenation (and a bunch of other completely unrelated stuff).

Still, let's close this as a duplicate.
