### ISSUE TITLE
How to concat string with command result?

### ISSUE THREAD

**Issue by julien-f** [fish-shell/fish-shell#3486]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.3.1

**OS/terminal used**: Debian/urxvt

I want to concat a string with the result of a subcommand.

## Reproduction steps

I've tried: 

1. `echo foo(cat data.txt)` but `foo` gets concat with all chunks in `data.txt`
2. `echo "foo(cat data.txt)"` but it gives me the string `foo(cat data.txt)`
3. `echo "foo$(cat data.txt)"` but I get an error, saying `$(...)` is not supported

**Comment by faho** [comment]
Currently, you'll need a two-step if the data has multiple lines, and it will remove the newlines.

```fish
set foo (cat data.txt)
echo "foo$foo"
```

You could also use `while read -l data; set foo $data\n; end < data.txt`, but that will add a trailing newline that you would need to remove.

This is tracked in #159. Sorry for the inconvenience.

**Comment by julien-f** [comment]
No problem, thanks for the fast answer :)
