### ISSUE TITLE
Fish_Update_Completitions processes btrfs' mans wrongly 

### ISSUE THREAD

**Issue by ar-qun** [fish-shell/fish-shell#3490]
**fish version installed** _(`fish --version`)_: fish, version 2.3.1

**OS/terminal used**:  Arch Linux

Generated btrfs competition plugins do not work.

```
.local/share/fish/generated_completions/btrfs-balance.fish
.local/share/fish/generated_completions/btrfs-check.fish
.local/share/fish/generated_completions/btrfsck.fish
.local/share/fish/generated_completions/btrfs-convert.fish
.local/share/fish/generated_completions/btrfs-debug-tree.fish
.local/share/fish/generated_completions/btrfs-device.fish
.local/share/fish/generated_completions/btrfs-filesystem.fish
.local/share/fish/generated_completions/btrfs-find-root.fish
.local/share/fish/generated_completions/btrfs-image.fish
.local/share/fish/generated_completions/btrfs-inspect-internal.fish
.local/share/fish/generated_completions/btrfs-map-logical.fish
.local/share/fish/generated_completions/btrfs-property.fish
.local/share/fish/generated_completions/btrfs-qgroup.fish
.local/share/fish/generated_completions/btrfs-quota.fish
.local/share/fish/generated_completions/btrfs-receive.fish
.local/share/fish/generated_completions/btrfs-replace.fish
.local/share/fish/generated_completions/btrfs-rescue.fish
.local/share/fish/generated_completions/btrfs-restore.fish
.local/share/fish/generated_completions/btrfs-scrub.fish
```

This files are generated, the content of .local/share/fish/generated_completions/btrfs-subvolume.fish

```
# btrfs-subvolume
# Autogenerated from man page /usr/share/man/man8/btrfs-subvolume.8.gz
# using Deroffing man parser
complete -c btrfs-subvolume -s i --description '.'
complete -c btrfs-subvolume -l commit --description 'options to wait until the operation is safely s… [See Man Page]'
complete -c btrfs-subvolume -s c -l commit-after --description '.'
complete -c btrfs-subvolume -s C -l commit-each --description '.'
complete -c btrfs-subvolume -s p --description 'is given, then parent <ID> is added to the outp… [See Man Page]'
complete -c btrfs-subvolume -s a --description '.'
complete -c btrfs-subvolume -s g --description '.'
complete -c btrfs-subvolume -s o --description '.'
complete -c btrfs-subvolume -s u --description '.'
complete -c btrfs-subvolume -s q --description '.'
complete -c btrfs-subvolume -s R --description '.'
complete -c btrfs-subvolume -s t --description '.'
complete -c btrfs-subvolume -s s --description '.'
complete -c btrfs-subvolume -s r --description '.'                              complete -c btrfs-subvolume -s G -o ']<value>' --description '.'
complete -c btrfs-subvolume -l sort --description '.'
```

As far as I get it, because name of the man is "btrfs-subvolume" this is used as the name of command instead of "btrfs". Probably it has to do with how different btrfs is from any other command.

I can than type by hand "btrfs-subvolume" and get autocompletition as, but it obviously will not execute.
## Reproduction steps
1. ´fish_update_completitions´
2. ´btrfs \t\t´
3. Nothing happens

The question is: what the best way to handle this issue?

It's either about fixing Fish_Update_Completitions´, or writing and constantly maintaining ´btrfs.fish´.  What's your thoughts?

P.S. Not sure how mans are, or how the function is for that matter. May be there is a way to parse them.

**Comment by faho** [comment]
>It's either about fixing Fish_Update_Completitions´, or writing and constantly maintaining ´btrfs.fish´. What's your thoughts?

There are a couple of tools with man pages like this. `git´ comes to mind, though we have hand-written completions.

The question here is if we can detect this case - is it as simple as a man page existing that has a "-" in it where the part before the "-" is a command and the entire thing isn't?

Plus, there's always the question if this leads to usable completions. This also does not read the descriptions properly, and I'm not sure if it can get the arguments right - it's not just taking files.

E.g. the git completions are pretty much impossible to autogenerate because the generator can't quite tell what a "tag" or "commit" is, let alone a "tree-ish".

So I'm leaning towards hand-rolling. If you'd like, you can try. Maybe use the generated ones as basis.

**Comment by ar-qun** [comment]
I would prefer to make it automatic, because it would be much easier to have completions update this way if mans are.

I am looking at git and btrfs man right now. They both have similar sections:

```
COMMANDS
       balance
           Balance btrfs filesystem chunks across single or several devices.

           See btrfs-balance(8) for details.

       check
           Do off-line check on a btrfs filesystem.

           See btrfs-check(8) for details.
```
and

```
GIT COMMANDS
       We divide Git into high level ("porcelain") commands and low level ("plumbing") commands.

HIGH-LEVEL COMMANDS (PORCELAIN)
       We separate the porcelain commands into the main commands and some ancillary user utilities.

   Main porcelain commands
       git-add(1)
           Add file contents to the index.

       git-am(1)
           Apply a series of patches from a mailbox.

       git-archive(1)
           Create an archive of files from a named tree.
```
man btrfs-check and man git-add then have synopsis, which reflect the way it look in terminal...

P.S. It's always bothered to me why mans are basically zipped text when json, or something type of data that has arrays and dictionaries, would save everybody so much time. That's another story though.

**Comment by krader1961** [comment]
FWIW, I don't think our time is spent well by improving how we autogenerate completions from man pages. Fish already does an excellent job. Obviously if someone can point to an obvious bug we will fix it. If someone is willing to spend the time to improve how scenarios like the btrfs man page is parsed we'll be happy to review and merge those changes. But this strikes me as something of very limited value and is therefore unlikely to be improved by any of the core developers. There are at least 300 other open issues that would benefit more people than this one.
