### ISSUE TITLE
funced always has second line indented with a tab

### ISSUE THREAD

**Issue by nhooyr** [fish-shell/fish-shell#3498]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: fish, version 2.3.1

**OS/terminal used**: iTerm 3.0.1

## Reproduction steps
1. `funced fish_mode_prompt`
2. Remove indent on second line and line it with the third line.
3. Exit the editor.
4. `funced fish_mode_prompt`
5. Notice that the second line is indented with a tab again.

**Comment by krader1961** [comment]
Already reported in issue #1472; although that issue didn't mention the `funced` command.
