### ISSUE TITLE
`string split' returns status 1 when successful

### ISSUE THREAD

**Issue by terlar** [fish-shell/fish-shell#3501]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`2.3.1-674-g7ea2dc4`)*:

**OS/terminal used**: `Arch Linux 4.8.4-1-ARCH/termite`

Talk about the the issue here. 

## Reproduction steps
1. Run `set lines hello world`
2. Run `string split \n -- $lines`
3. Run `echo $status` to check status

![2016-10-27-174244_624x202_scrot](https://cloud.githubusercontent.com/assets/280235/19774392/312f545e-9c6d-11e6-8160-c2b1a92418ed.png)

## Results
```console
~ $ set -l lines hello world
~ $ string split '\n' -- $lines
hello
world
~ $ echo $status
1
```

I would expect the split command to return a status of `0`, since it successfully split the `lines` variable.

**Comment by faho** [comment]
>I would expect the split command to return a status of 0, since it successfully split the lines variable.

Nope, it wasn't successful. There's no "'\n'" in $lines, so it didn't split anything. The reason it is printing two lines is because it is getting two arguments - this is equivalent to `string split '\n' -- $lines[1] $lines[2]`.

Also, you are splitting on the literal string "\n" here, not a newline character.

**Comment by terlar** [comment]
Ah, I miss-understood it due to this reason, so the way to do this would be with `printf '%s\n' $lines`?

I thought there was a way to do this kind of operation with the `string` built-in. My use case is saving output which is multi-line to a variable and then later try to restore that variable content either through a pipe or some other way.

**Comment by faho** [comment]
>so the way to do this would be with printf '%s\n' $lines?

It depends. That will always add a trailing newline, which may or may not have existed previously.

If you don't want that, you should use `string join \n -- $lines`.

In both cases, as soon as you use it in another command substitution, you'll lose the newlines again as we split those on newlines.

This is tracked in #159.
