### ISSUE TITLE
newline after exit

### ISSUE THREAD

**Issue by nhooyr** [fish-shell/fish-shell#3502]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations _(check `sh -c 'env HOME=$(mktemp -d) fish'`)_?

**fish version installed** _(`fish --version`)_: fish, version 2.3.1

**OS/terminal used**: iTerm 2 3.0.10

Talk about the the issue here. 
## Reproduction steps
1. sh -c 'env HOME=$(mktemp -d) fish'
2. exit

Should look like:

```
❯ sh -c 'env HOME=$(mktemp -d) fish'                                                                                                                                                                       
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
nhooyr@ezekiel /U/nhooyr> exit

~
❯
```

What's with the newline after exit?

**Comment by krader1961** [comment]
It's from the `writestr(L"\n");` in `reader_interactive_destroy()` in *reader.cpp*. That was in the first git version, commit 149594f, from Sep 2005. Your guess is as good as mine as to why that is present. Is it causing a problem?

**Comment by floam** [comment]
It's mildly annoying. Perhaps trying to clear out something line-buffered?

**Comment by nhooyr** [comment]
No actual problem but is annoying.

**Comment by floam** [comment]
No obvious ill effects from getting rid of the `writestr` line after testing for 15 minutes. We also reset the colors right after that and it doesn't seem to have any side-effects such as allowing us to accidentally leave a color set or anything, either.

**Comment by floam** [comment]
I'd like it nuked if we can't justify printing the spurious newline somehow or the other.

**Comment by krader1961** [comment]
It's possible it solved a problem that no longer exists. But I think it more likely it was added to deal with unusual configurations. Such as having a multiline left and right prompt. Since its presence is harmless I think we need to be extremely confident that removing it won't cause a problem before doing so.

**Comment by gMan1990** [comment]
how to fix or hidden the msg: "fish: Wide character 9166 has no narrow representation"

**Comment by krader1961** [comment]
@gMan1990, You asked

> how to fix or hidden the msg: "fish: Wide character 9166 has no narrow representation"

I fail to see what that has to do with this issue. Having said that it means the Unicode ["return" symbol](https://www.fileformat.info/info/unicode/char/23ce/index.htm) used by fish to indicate the output of the previous command did not end with a newline character could not be converted to a sequence of bytes by the `wcrtomb()` function. Please open a new issue and provide details about your operating system and locale (e.g., the output of `locale`).

**Comment by gMan1990** [comment]
@krader1961 on windows 7 zh-cn
![qq 20161028112955](https://cloud.githubusercontent.com/assets/5050994/19794044/19af790e-9d02-11e6-8eff-95dfd1c4ed8a.png)

**Comment by krader1961** [comment]
@gMan1990, Please open a [new issue](https://github.com/fish-shell/fish-shell/issues/new) and provide details about your operating system environment. For example, fish isn't a native MS Windows app so presumably you're running this inside Cygwin on Windows 7. So in addition to knowing that you're running fish on MS Windows 7 we need to know what version of Cygwin you are using. Also, please provide the output of the `locale` command.

Please do not update this issue with your answers since your problem is unrelated to this issue. Instead open a [new issue](https://github.com/fish-shell/fish-shell/issues/new).

**Comment by krader1961** [comment]
Changing this from a question to a proposed enhancement. Frankly, unless someone can explain why the reason the newline was added long ago is no longer applicable I don't think we should change the behavior. Unless, of course, someone can show that the current behavior causes problems which seems unlikely given that the current behavior has existed for eleven years. I propose closing this three months from today if no one can explain why changing the behavior is close to zero risk.

**Comment by floam** [comment]
I've been using this without the newline for a couple weeks. I can't find any issues with multiline prompts or right prompts.

**Comment by ridiculousfish** [comment]
I think we should just remove this newline. Any time there's code we're scared to touch, it's a bad sign. The worst case is we learn why it was put there in the first place.

**Comment by krader1961** [comment]
Okay, then we should do it right away; as in today. The longer the change is in place before 2.5.0 the better. I'll take care of it. And while it seems likely the newline served a purpose when it was added I also think it probable that reason no longer exists. It's a shame the person who added that newline didn't think "people will wonder why this is here so I'd better add a comment." We'll soon find out if it still serves some purpose.

**Comment by floam** [comment]
OK, it is gone. (Sorry, I hadn't noticed you self-assigned this, @krader1961.)

**Comment by ridiculousfish** [comment]
Labelling relnotes so that if anyone is bitten, they'll have a path to figuring out why.
