### ISSUE TITLE
Implement the noglob modifier

### ISSUE THREAD

**Issue by legovini** [fish-shell/fish-shell#3504]
Fish currently misses a `noglob` precommand modifier. It should work like in Zsh, that is:

> Filename generation (globbing) is not performed on any of the words.

so that `echo *` prints a literal `*`.

**Comment by faho** [comment]
This has been discussed before, and the answer is no.

`noglob` is a weird parser hack. If you wish to use arguments that may be expanded somehow literally, quote them. `echo '*'` and `echo "*"` both will print the literal.
