### ISSUE TITLE
 function available is deprecated

### ISSUE THREAD

**Issue by abhigenie92** [fish-shell/fish-shell#3505]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [ ] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
```
fish --version
fish, version 2.3.1-675-gf382fa8
```
**OS/terminal used**: 
```
 ~  uname -a
Linux neon 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
 ~  lsb_release -a
No LSB modules are available.
Distributor ID: neon
Description:    KDE neon User Edition 5.8
Release:        16.04
Codename:       xenial
```

Talk about the the issue here. 
```
[ ~ warning: function available is deprecated and will be removed soon.
called on line 254 of file ~/.config/fish/functions/fish_prompt.fish
warning: function available is deprecated and will be removed soon.
called on line 255 of file ~/.config/fish/functions/fish_prompt.fish
warning: function available is deprecated and will be removed soon.
called on line 256 of file ~/.config/fish/functions/fish_prompt.fish
]
```
## Reproduction steps
1. omf update caused it, before it was fine.

**Comment by krader1961** [comment]
That's not an error message from fish. You have a custom `fish_prompt` function that is apparently calling another function named `available` that is warning you it will be removed in a future update. Since we have no idea what `available` used to do we can't advise you on what to replace it with in your prompt.
