### ISSUE TITLE
the `status` option parsing is badly broken

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3509]
While working on eliminating lint warnings I noticed that `builtin_status()` in _builtin.cpp_ allows multiple, mutually exclusive, options to be used in a single `status` invocation. This code should use something like the `set_hist_cmd()` function I introduced for the `history` command to ensure only one of several mutually exclusive options is allowed.

For a concrete example of why the current behavior is fubar open an interactive fish shell and run `status -i -b` then `status -b -i`. Notice that that first one exits with a status of one while the second exits with a status of zero. Neither one writes a message to stderr about the conflicting flag.

This is a poster child example of giving the user too much rope to hang themselves.

**Comment by faho** [comment]
>For a concrete example of why the current behavior is fubar open an interactive fish shell and run status -i -b then status -b -i.

That is bananas. 

>This is a poster child example of giving the user too much rope to hang themselves.

I don't think so. Most of the flags aren't actually conflicting - something can be an interactive login shell currently executing a command substitution inside a block. Of course `status --is-interactive-job-control --is-no-job-control` makes no sense, but the others work, and it might be nice to allow `status -il; and echo "Interactive login"`.

That requires defining it, though.

**Comment by krader1961** [comment]
> Most of the flags aren't actually conflicting...

There are a handful, at most, combinations of flags that make sense. Your example is one of those. But it's not at all obvious we should complicate the implementation and documentation to support those handful of compound flags that are meaningful. Under what circumstances does it make sense to combine `-t`, `-j`, `-b`, `-c`, `-n`, `-f` with any other flag?

Given that the documentation currently, albeit implicitly, says that only one flag can be specified I think we should modify the implementation to make that explicit. Rather than complicate the implementation, and documentation, to allow the handful of combinations that make sense. Especially since we're likely to add new options to `status` and this is thus an exponential problem.

Anyone wanting to condition an action on the shell being interactive and login can simply do

```
if status --is-interactive; and status --is-login
   echo do something
end
```

I see no reason to support the shorthand

```
if status --is-interactive --is-login
    echo do something
end
```

**Comment by krader1961** [comment]
Also, this seems to me to be another example of the UI problem that the `history` command had. That is, conflating mutually independent and incompatible subcommands by using flags rather than actual subcommands. That is `status is-login` rather than `status --is-login` is preferable to make it 100% clear that only one subcommand can be specified.

**Comment by krader1961** [comment]
Also, in case it isn't clear the current implementation behaves as I propose making the explicit behavior. Albeit with newly introduced error messages if the user tries to do something silly; i.e., specify more than one flag that specifies a subcommand.

**Comment by krader1961** [comment]
Does anyone have a strong objection to modifying the `status` command to have subcommands and deprecate the flags like I recently did for the `history` command? As I said earlier there are only a very small number of flag (subcommand) combinations that make sense. The vast majority of them do not make any sense. And as we add more features to the `status` command the disparity will only increase. Too, as I showed in an earlier comment it is trivial to do a compound test where allowing multiple flags/subcommands actually does make sense. For example,

```
if status --is-interactive; and status --is-login
   echo do something
end
```

Please note that the implementation currently does not allow multiple flags/subcommands. It's simply silent if the user does so. It also silently allows nonsense like `fish -c 'status -i -f wtf'`. That is, it acts on the last flag that specifies a subcommand and ignores any spurious arguments.

**Comment by floam** [comment]
So, my main thought is that subcommands should be verbs. I'm not sure it makes as much sense here.

**Comment by faho** [comment]
Also, this is used much more (and much more non-interactively, where we can't just show an error and the user will type it correctly next time), so the potential breakage isn't really worth it.

**Comment by floam** [comment]
I guess the verb could be 'is' -- `status is interactive`

**Comment by krader1961** [comment]
Anyone doing something like `status -i -f wtf` or `status --is-login --is-interactive` is already getting undefined behavior that is unlikely to be what they expected. I'm not proposing a fatal exit. But we should issue an error message and return a status of one (`STATUS_BUILTIN_ERROR`) just like every other builtin when it is invoked with invalid arguments. It's not clear to me why the `status` command should be different from every other command in this regard.

**Comment by faho** [comment]
@krader1961: Oh, I'm not arguing that `status -i -f wtf` isn't wrong. It is, and that should definitely be an error. You are correct that this is "undefined behavior" and that we can just change this without regards for compatibility.

My last comment was about the "subcommand" idea. I don't think it's worth it to switch from `status -i` to `status is-interactive`, even via deprecation and such.

I have also come around on the multiple-option thing. I now agree that `status -i -l` should error.

**Comment by krader1961** [comment]
I feel it's worth copying the following comment from PR#3526 into this issue:

We certainly don't have to introduce non-flag subcommands in order to fix the core problem. But imagine if we had made the string command use flags for the subcommands. Instead of string match you'd be writing string --match. I think everyone would agree that's bizarre. The only reason you don't feel that way about status --is-login is that it's been that way for several years. With this change some additional changes I'm contemplating to extend the behavior of current-filename and current-line-number result in a more natural syntax.
