### ISSUE TITLE
`help` is useless if you ssh into a machine

### ISSUE THREAD

**Issue by Soares** [fish-shell/fish-shell#351]
Sometimes I ssh into a machine running fish. `help` dutifully opens the help in a web browser on a monitor that's miles away from me, which is pretty useless when I'm struggling to figure out what a command does in the first place.

I understand that fish is trying to be really user friendly with the in-browser documentation and everything, but it would be really really nice to have a `help --local` option or something of the sort for those times when I'm sshing (or when I just don't feel like touching my mouse).

**Comment by faho** [comment]
The man wrapper has been added, help opens a browser. Methinks the only thing left to do is documentation.

**Comment by pickfire** [comment]
Do you mean opening a text-based browser for `help`?

**Comment by faho** [comment]
If you set one as $BROWSER or OS default, yes. I just tested and both w3m and links work.

**Comment by faho** [comment]
I just checked, and the [Help section](http://fishshell.com/docs/current/index.html#docs) of our documentation (not to be confused with the section on the `help` function) already says:

>fish also has man pages for its commands. For example, man set will show the documentation for set as a man page.

So I'm considering this done.
