### ISSUE TITLE
aliases that contain double-quotes are now broken

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3510]
Commit 2d46969d makes it impossible to define an alias that contains double-quote characters. For example, `alias h 'builtin history search -15 --show-time="%a %m-%d %R  "'` now results in these error messages when starting a fish shell:

```
Unable to find a process 'm-%d'
- (line 1): function h --wraps builtin --description "alias h builtin history search -15 --show-time="%a %m-%d %R  "";  builtin history search -15 --show-time="%a %m-%d %R  " $argv; end
                                                                                                          ^
from sourcing file -
        called on line 63 of file ~/projects/3rd-party/fish-shell/share/functions/alias.fish

in function 'alias'
        called on line 7 of file ~/.config/fish/aliases.fish
        with parameter list 'h builtin history search -15 --show-time="%a %m-%d %R  "'

from sourcing file ~/.config/fish/aliases.fish
        called on line 15 of file ~/.config/fish/interactive.fish

from sourcing file ~/.config/fish/interactive.fish
        called on line 27 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
        called during startup
```

The problem is due to the 100% redundant inclusion of the body of the alias in the description. Redundant since the body of the function being created has that very same text.

@floam, I was tempted to just revert your commit but decided to give you a chance to fix it. Please start by removing the alias definition from the function description. It adds no value. Neither does including the name of the alias since that's identical to the name of the function. What might add value is including the output of `status -f` if that took a number so you could ask for the second most recent stack frame. Unfortunately I don't think it is worth trying to parse the output of `status -t` just to include useful info about where the `alias` command was invoked from.

**Comment by krader1961** [comment]
Also, your subsequent commit had a typo in the documentation: "craete" should be "create". Too, it's not at all obvious that running a bare `alias` should list aliases rather than do what it did before your change: emit a short help message. I'm wondering if it wouldn't  be better to add `-l` and `--list` flags. Or perhaps add an `aliases` command. That would more closely mimic `function` versus `functions`.

**Comment by floam** [comment]
Sorry, I'll fix this.

**Comment by floam** [comment]
For the sake of trying to match POSIX sh (what this ostensibly exists for) I'm not sure it's right to add an `aliases` - at least unless/until we add some kind of first-class alias modality.

**Comment by floam** [comment]
I just fixed the error rather than change what I'm putting in the description. It might be redundant - but I don't really see the harm with most aliases being short.

**Comment by floam** [comment]
And for me - it'd make sense to see that line in the pager - it's handy. But actually I can't quite figure out why function descriptions are no showing up in the pager ever right now. We do get what looks like apropos output for external commands.

**Comment by krader1961** [comment]
Okay but I intend to change the description to be of the form "alias defined interactively" or "alias defined on line 7 of /some/script.fish" if and when the `status` command is enhanced to make it easy to get that information from the call stack.

As for having `alias` with no args mimic the behavior of bash, et. al., I agree. Although, that output should also include the info about where the alias was defined once that's available.
