### ISSUE TITLE
`jobs` does not expand variables in args of command called inside of function

### ISSUE THREAD

**Issue by f1u77y** [fish-shell/fish-shell#3511]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** : 2.3.1

## Reproduction steps
1. Make a function that runs some command, e.g.
```
function man
    command man $argv
end
```
2. Run it like `man fish`
3. Stop it with C-z
4. Run `jobs`

## Results
```
 $ jobs
3	30854	0%	stopped	command man $argv
```

**Comment by krader1961** [comment]
That's the expected behavior. You'll see the same thing if you don't use a function. For example:

```
$ set time 30
$ sleep $time
press [ctrl-Z]
$ jobs
Job	Group	State	Command
1	5592	stopped	sleep $time
```

Is there something in the documentation that leads you to believe the vars should be expanded when the command is shown by `jobs`?

**Comment by floam** [comment]
I'll note that this matches the behavior of other shells as well, AFAIK.
