### ISSUE TITLE
should we continue to predicate our behavior on the value of `$TERM`?

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3512]
While working on eliminating lint warnings I noticed that `is_screen_name_escape_seq()` contains `string_prefixes_string(L"screen", term_name)` (where `term_name` is equivalent to `$TERM`) to decide if an escape sequence beginning with `\ek` is meaningful. That is bogus. I happen to have my `$TERM` set to `tmux-256color` when inside of a tmux session (in order to have italics available). That is, I have a custom terminfo config based on `screen-256color`.

There is one other place, `reader_write_title()`, where a similar test is present.

The code history is a bit confusing but this dates back to at least January 2012 with commit a359f45df.

It's quite likely there isn't a better solution and we have to continue to test the terminal config name. If so we should add `"tmux"` every place we check for `"screen"` since the former is also recommended by the tmux project as an alternative if you need a tmux specific terminal config. But ideally we would ignore the $TERM value except for ancient historical values (e.g., `xterm`) where there is no other option but to infer capabilities based on the value.

**Comment by faho** [comment]
Is this just about those specific cases or a broader point?

Because there's other places where we check $TERM, like the vi-cursor or truecolor checks (in share/functions/fish_vi_cursor.fish and share/config.fish), quite simply because there seems to be no alternative.

**Comment by krader1961** [comment]
> Is this just about those specific cases or a broader point?

Both. I took ownership to special case `tmux` everywhere we special case `screen`. But the broader point is that there doesn't seem to be any good reason for `is_screen_name_escape_seq()` to even test the $TERM name; it should just recognize that sequence. Which makes me wonder how many other places we test for specific values of $TERM when doing so isn't necessary. Having said that I do recognize that auto-enabling features like truecolor will need to test $TERM for the foreseeable future.
