### ISSUE TITLE
How to force long paths in prompt ?

### ISSUE THREAD

**Issue by ianjohnspain** [fish-shell/fish-shell#3513]
Hi,

I am using fish and the prompt always seems to truncate itself, for example

~/D/a/hello-mobile (master) [130]>

the D above is for Developer
a is for Angular

is there anyway to get it to render the full path, I keep having to do PWD to find out where I am.

Thanks in advance

**Comment by floam** [comment]
Sure, set `fish_prompt_pwd_dir_length` to 0 to get the full paths, or any other number to have it truncate after that many characters.

**Comment by ianjohnspain** [comment]
Thanks. Worked a treat. Placed it in my fish.config

**Comment by floam** [comment]
Actually if you use the `-U` there, it will persist - only necessary to run it once and doesn't need to place it in the config file.

**Comment by ianjohnspain** [comment]
Ah, open, thanks. I will remove it from the config.
