### ISSUE TITLE
Missing Ubuntu Yakkety PPA for fish nightlies

### ISSUE THREAD

**Issue by TimWolla** [fish-shell/fish-shell#3516]
The official fish nightly PPA does not provide packages for the newest Ubuntu “Yakkety” 16.10: https://launchpad.net/~fish-shell/+archive/ubuntu/nightly-master

It would be great if this could be changed!

**Comment by zanchey** [comment]
Thanks - I've added it to the build targets and copied the Xenial packages for now.

It's moderately annoying there's no easy way of telling `dput` to upload to "all supported series", but I've set a reminder for April and October to try and avoid this happening again.

**Comment by jimmed** [comment]
@zanchey It seems this has happened again! There's no 2.7.x build for Yakkety in the PPA

**Comment by zanchey** [comment]
Yakkety was EOL when 2.7.0 was released, and PPA builds are not accepted for EOL releases.

**Comment by jimmed** [comment]
Apologies, I realised this shortly after I posted the comment above! Sorry to disturb :)
