### ISSUE TITLE
set_color not working thus black&white prompt in login shell on a container

### ISSUE THREAD

**Issue by suut** [fish-shell/fish-shell#3518]
Hi there,

I've set up a systemd-nspawn container with Debian unstable in it, and set fish as my login shell. When I login onto the container, the prompt is black and white and the set_color builtin doesn't do anything.

Issuing the terminal escape color codes works as usual, TERM is set to xterm-color256; and the strangest is that if I launch another instance of fish inside that login shell, color actually works.

So what I've done for now is setting up a bash script that launches fish as my login shell, but there must be a workaround to this.

A screenshot is attached:

![2016-11-02-214622_1920x1080_scrot](https://cloud.githubusercontent.com/assets/519995/19946840/d255dcd6-a145-11e6-8252-28d130ac1603.png)

Thank you in advance for your help.

**Comment by krader1961** [comment]
You wrote that "TERM is set to xterm-color256" but the usual spelling is "xterm-256color".

What does `echo $FISH_VERSION`, echo `$TERM`, and `tput colors` report? All of that in both the original fish shell which has the problem and the fish subshell you start that does not.

**Comment by floam** [comment]
What's the output of `set_color red | xxd` ?

**Comment by faho** [comment]
@suut: I'm quite certain that the systemd stuff sets $TERM to "vt220" (for some reason - I have no idea why they don't just inherit $TERM).

If you are setting $TERM to something else in e.g. config.fish, you need a fish build with eb834f47efeca3c2100163e892ab41df670b0687 - which is 2.3.**1** at least. This would explain why launching another fish inside it works - without that commit, setting $TERM inside config.fish is too late.

**Comment by suut** [comment]
Sorry about forgetting to include the version: it is 2.2.0.

faho: yeah, this was the default value of `TERM`, but I changed it to `xterm-256color` in many places, including in the command line for systemd-nspawn which boots the container (but maybe it does only work with bash-compatible shells), but also in config.fish, to be sure that it gets the right value at any stage of its load. My fish is 2.2.0, so you're certainly right.

floam: absolutely nothing. But `set_color -o red` outputs the code for bold `\033[1m` but nothing about red.

krader1961: yeah sorry I misspelt it in the question, I wanted to say `xterm-256color`.
So, `FISH_VERSION` is `2.2.0` in both shells, `TERM` is `xterm-256color` in both terms too, and the same thing for the output of `tput colors` which is `256` in both shells. As faho said, the thing is that systemd-nspawn sets the term type to `vt220` at boot, and it seems that it gets changed to `xterm-256color` only after fish has started, and `set_color` cached the first value or something.

I'm upgrading to the latest fish version, that should solve this, thank you all for your help !
