### ISSUE TITLE
fish_vi_cursor needs to suppress error output of tput

### ISSUE THREAD

**Issue by TieDyedDevil** [fish-shell/fish-shell#3519]
- [ ] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [ ] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
This applies to commit 2a5ad198bf9e7f2c5a9b927e3dcf7496217a00ac .

**OS/terminal used**: 
Fedora/st

Talk about the the issue here. 

## Reproduction steps
1. Run fish-shell in st terminal.

## Results
See error message from tput:
```
tput: unknown terminfo capability 'Ss'
```

**Comment by faho** [comment]
@TieDyedDevil: Thanks, nice catch!

@zanchey: You'll want to cherry-pick b9b6679 one for 2.4.0.
