### ISSUE TITLE
macOS completions

### ISSUE THREAD

**Issue by elnappo** [fish-shell/fish-shell#3525]
This issue should track progress for macOS specific tab completions.

- [x] defaults
- [x] mdfind
- [x] diskutil
- [x] mdls
- [ ] launchctl (WIP)
- [ ] plutil
- [x] nvram
- [ ] log
- [ ] pmset
- [ ] softwareupdate
- [ ] qlmanage
- [ ] scutil
- [ ] brctl
- [x] caffeinate
- [x] mddiagnose
- [x] mdimport
- [x] mdutil
- [ ] networksetup
- [ ] say
- [ ] screencapture
- [ ] security (hard)
- [ ] serverinfo (easy)
- [ ] sharing
- [ ] systemsetup
- [ ] tccutil (simple)
- [ ] textutil
- [x] tmutil

This list is probably not complete.

**Comment by floam** [comment]
`log` added in 10.12 would be a good addition. Maybe `brctl`.

**Comment by elnappo** [comment]
thanks, also added `pmset`. If someone is using one of these tools, please stand up to set priorities.

**Comment by floam** [comment]
> please stand up to set priorities.
I've rearranged some of the items in this issue based just on my usage of the commands. Sorry for messing up the alphabetical order.

**Comment by krader1961** [comment]
Custom completions need to be written and submitted by someone motivated to do so. Like yourself, @elnappo. We're happy to provide advice on how to do so. But without such a submission this issue will simply bit rot.
