### ISSUE TITLE
Ctrl-C fail

### ISSUE THREAD

**Issue by Estirp** [fish-shell/fish-shell#3527]
- [x] Have you checked if problem occurs with [fish 2.3.1](/fish-shell/fish-shell/releases/tag/2.3.1)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.3.1

**OS/terminal used**: Linux with Guake or Terminator

When I type
```
for a in (tail -f Z/a)
  end
^C^C^C
```
with Z/a an existing file, typing Ctrl-C does not interrupt the loop and does nothing.
I must use kill to stop the process.
The Ctrl-C should interrupt the script.

**Comment by krader1961** [comment]
This is trivial to reproduce. It's probably related to issue #1362 and #1826. I'm too tired and focused on other issues to dig deeper.

**Comment by ridiculousfish** [comment]
Nice find

**Comment by krader1961** [comment]
I just verified that this bug has been fixed as a result of the job control improvements made since the 2.5.0 release.
