### ISSUE TITLE
Broken dependencies in fish 2.4 for Debian?

### ISSUE THREAD

**Issue by TimWolla** [fish-shell/fish-shell#3534]
Today I got notification of a fish upgrade from 2.3.1 to 2.4.0. I am running the official repositories:

```
fish:
  Installed: 2.3.1-1
  Candidate: 2.4.0-1
  Version table:
     2.4.0-1 0
        500 http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_8.0/  Packages
 *** 2.3.1-1 0
        100 /var/lib/dpkg/status
     2.2.0-3~bpo8+1 0
        100 http://http.debian.net/debian/ jessie-backports/main amd64 Packages
```

When trying to update `fish` `apt` tries to install a ton of other dependencies, including `cpp`, the C preprocessor of GCC:

```
[root@example~]apt install fish
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  cpp cpp-4.9 fish-common libcloog-isl4 libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libelf1 libfile-basedir-perl libfile-desktopentry-perl libfile-mimeinfo-perl libfontenc1 libgl1-mesa-dri libgl1-mesa-glx
  libglapi-mesa libisl10 libllvm3.5 libmpc3 libnet-dbus-perl libpciaccess0 libtie-ixhash-perl libtxc-dxtn-s2tc0 libx11-protocol-perl libx11-xcb1 libxaw7 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0
  libxcb-shape0 libxcb-sync1 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxft2 libxi6 libxinerama1 libxml-twig-perl libxml-xpathengine-perl libxmu6 libxrandr2 libxrender1 libxshmfence1 libxtst6 libxv1
  libxxf86dga1 libxxf86vm1 x11-utils x11-xserver-utils xdg-utils
Suggested packages:
  cpp-doc gcc-4.9-locales libunicode-map8-perl libunicode-string-perl xml-twig-tools mesa-utils nickle cairo-5c xorg-docs-core gvfs-bin
Recommended packages:
  xsel
The following NEW packages will be installed:
  cpp cpp-4.9 fish-common libcloog-isl4 libdrm-intel1 libdrm-nouveau2 libdrm-radeon1 libelf1 libfile-basedir-perl libfile-desktopentry-perl libfile-mimeinfo-perl libfontenc1 libgl1-mesa-dri libgl1-mesa-glx
  libglapi-mesa libisl10 libllvm3.5 libmpc3 libnet-dbus-perl libpciaccess0 libtie-ixhash-perl libtxc-dxtn-s2tc0 libx11-protocol-perl libx11-xcb1 libxaw7 libxcb-dri2-0 libxcb-dri3-0 libxcb-glx0 libxcb-present0
  libxcb-shape0 libxcb-sync1 libxcomposite1 libxcursor1 libxdamage1 libxfixes3 libxft2 libxi6 libxinerama1 libxml-twig-perl libxml-xpathengine-perl libxmu6 libxrandr2 libxrender1 libxshmfence1 libxtst6 libxv1
  libxxf86dga1 libxxf86vm1 x11-utils x11-xserver-utils xdg-utils
The following packages will be upgraded:
  fish
1 upgraded, 51 newly installed, 0 to remove and 3 not upgraded.
Need to get 20.7 MB of archives.
After this operation, 71.5 MB of additional disk space will be used.
Do you want to continue? [Y/n] n
```

Can you check this, please?

**Comment by TimWolla** [comment]
I just checked the dependencies and assumed this to be caused by the `Recommends` on `xdg-utils` (maybe `xsel`). In any case: Installing fish without the recommended dependencies looks sane:

```
[root@example~]apt install fish --no-install-recommends
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  fish-common
Recommended packages:
  xsel xdg-utils
The following NEW packages will be installed:
  fish-common
The following packages will be upgraded:
  fish
1 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 1,347 kB of archives.
After this operation, 306 kB of additional disk space will be used.
Do you want to continue? [Y/n] n
```

**Comment by krader1961** [comment]
@zanchey handles our packaging and since he's in Australia it will be a few hours before he notices this. In the mean time I'll point out the obvious: The compiler related dependencies can perhaps be explained if it's having to build from source. But almost all the extra packages are related to the X subsystem and that's obviously wrong.

There was a big refactoring of the Debian packaging confg files in commit 45ae726d on 2016-10-02. That's probably the source of the problem. On Ubuntu 16.04 running `apt-cache showpkg xdg-utils` shows that it depends on x11-utils and others so that's probably the the reason those packages are being installed. And the reason we depend on xdg-utils is because we use the `xsel` command. Too, that requirement was present before an after that commit.

**Comment by TimWolla** [comment]
> Are you sure it wasn't automatically installing those recommended packages with the prior fish versions?

Yes. I run fish on three different headless server boxes and none of them have got `xdg-utils` installed. Maybe something changed during the upgrade from Debian Wheezy to Debian Jessie, fish was installed with Wheezy and the whole box then upgraded to Jessie some time afterwards.

Looking at the possible dependencies a `Suggests` instead of `Recommends` looks better to me: IIRC a `Suggests` is not automatically installed. This is perfect for headless servers, a desktop machine would have `xdg-utils` installed already because of other packages more often than not anyway, no?

**Comment by jurgenhaas** [comment]
Not sure if mine is related. I was able to update to fish 2.4.0 on Ubuntu 14.04 and it is working fine, except for Ctrl-V, it throws this error when logged into remote hosts, it does work on my local host correctly:

```
 xsel: Can't open display: (null)
: Inappropriate ioctl for device
commandline: Invalid combination of options,
insertion mode switches can not be used when not in insertion mode
/usr/share/fish/functions/fish_clipboard_paste.fish (line 5):         commandline -i -- (xsel --clipboard)
                                                                      ^
in function “fish_clipboard_paste”
	called on standard input


       commandline -- set or get the current command line buffer

   Synopsis
       commandline [OPTIONS] [CMD]

commandline: Type “help commandline” for related documentation
```

xdg-utils are installed and still I'm getting this error.

**Comment by faho** [comment]
@jurgenhaas: The error is this:

>xsel: Can't open display: (null)

`xsel` can't open "the display" (i.e. the connection to the X server), probably because you aren't running one.

We might want to make the error message a bit nicer (probably only run the `commandline` bit if `xsel` succeeded, which would silence our own error but let xsel's through), but it's expected that the functionality isn't working in that situation.

>Not sure if mine is related.

It's not - this is about how much we want `xsel` to be installed along with fish. We only need it for this function, and this function only works inside X, so if you don't run X, installing xsel doesn't help.

>Looking at the possible dependencies a Suggests instead of Recommends looks better to me: IIRC a Suggests is not automatically installed. 

@TimWolla: That might be the correct action. How do other debian packages with optional X support handle this? Are you expected to use `--no-install-recommends` if you don't run X in other cases?

**Comment by TimWolla** [comment]
> How do other debian packages with optional X support handle this? Are you expected to use --no-install-recommends if you don't run X in other cases?

I have never used that option before. No idea whether it is due to other packages using `Suggests` or other packages simply not requiring X.

**Comment by c22** [comment]
Perhaps even "Suggests" would make sense here.

> This is used to declare that one package may be more useful with one or more others. Using this field tells the packaging system and the user that the listed packages are related to this one and can perhaps enhance its usefulness, but that installing this one without them is perfectly reasonable.

Re: What other packages do, in my experience they do whatever they want. I've seen some packages "recommend" docs but I'd consider not installing docs to be perfectly reasonable and therefore aligns closer to the definition of "suggests".

**Comment by faho** [comment]
@zanchey: Mind chiming in? Sounds like "suggests" would be better.

**Comment by faho** [comment]
@zanchey: Mind chiming in? Sounds like "suggests" would be better.

**Comment by zanchey** [comment]
I've been thinking about this all day! The change was introduced in 6add8a7df90899e28d317b399e1196a56f24fbb6, but the in-repository metadata didn't get used to build the package until 2.4b1.

This a tricky thing to get right, and I thought I'd actually copied the downstream Debian packaging here - but that is not the case. I can't be sure, but I think the case I was thinking of is the average user who installs fish on their laptop or PC. They would expect the `open` command to work, while I don't know that network-only server administrators would. Too, the former would probably already have `xdg-utils` as it is required by `task-desktop`, and the `open` function fails gracefully-ish if `xdg-open` is not available.

I'll change the metadata and rebuild the 2.4.0 package for Debian and Ubuntu! It will become 2.4.0-2 on those platforms.

**Comment by zanchey** [comment]
Incidentally, would you consider adding the beta channel to one of the machines you use? https://software.opensuse.org/download.html?project=shells%3Afish%3Abeta%3A2&package=fish That would help us pick up this sort of thing earlier.

**Comment by zanchey** [comment]
Currently waiting for the scheduler to pick up the rebuilt packages, so hopefully this will be sorted in the next hour or so. I do have to go to sleep for now!

**Comment by TimWolla** [comment]
> I'll change the metadata and rebuild the 2.4.0 package for Debian and Ubuntu! It will become 2.4.0-2 on those platforms.

Looks better now:
```
[root@example~]apt install fish
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  fish-common
Suggested packages:
  xdg-utils
Recommended packages:
  xsel
The following NEW packages will be installed:
  fish-common
The following packages will be upgraded:
  fish
1 upgraded, 1 newly installed, 0 to remove and 4 not upgraded.
Need to get 1,347 kB of archives.
After this operation, 306 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
```

> Incidentally, would you consider adding the beta channel to one of the machines you use? 

I'd rather not as I'm using fish as the root shell and thus prefer stable releases. I'm using fish nightly on my personal computer, though. Unfortunately ( ;) ) it already had got `xdg-utils` installed.

**Comment by zanchey** [comment]
> Unfortunately ( ;) ) it already had got xdg-utils installed.

Indeed; all my machines on the nightly channels are single-user desktops as well.
