### ISSUE TITLE
Fish as remote shell through SSH mangles unicode characters (POSIX locale)

### ISSUE THREAD

**Issue by stephanedaviet** [fish-shell/fish-shell#3536]
**fish version installed** *(`fish --version`)*: 2.3.1

**OS/terminal used**:  Arch Linux/Gnome terminal

## Reproduction steps
1. Open a terminal in a host computer with a user with fish or bash as current shell,
2. Open an SSH connection to a remote computer with a user with fish as his default shell.

## Results
- With an `ls` command, files with unicode characters (french accent like _é_, _à_ for instance) are mangled: e.g. `Stéphane` is displayed `'St'$'\303\251''phane'`,
- `locale` command displays `"POSIX"` for all locales attributes,
- Same steps with target shell defined as bash for the user gives the expected result: filenames are not mangled and `locale` displays `fr_FR.utf8`.

**Comment by krader1961** [comment]
> locale command displays "POSIX" for all locales attributes

There's your problem. My recommendation is to add `SendEnv LANG TERM` to your *~/.ssh/config* so that the value of those vars on the system you're running `ssh` are propagated to the remote system. The reason bash works is probably because /etc/profile is setting LANG. Fish 2.4.0 now attempts to set the locale if none of the locale env vars are set. See issue #277.

**Comment by faho** [comment]
>Fish 2.4.0 now attempts to set the locale if none of the locale env vars are set.

In particular, it will set encoding to UTF-8 if it cannot get any locale, which should fix the filename display.

@stephanedaviet: Can you try this with 2.4.0?

**Comment by stephanedaviet** [comment]
@krader1961 I have put `SendEnv LANG LC_* TERM` in the `~/.ssh/config` of my host and `AcceptEnv LANG LC_* TERM` in `/etc/ssh/sshd_config` on the remote machine without success. `locale` always displays `POSIX`.

@faho Fish 2.4.0 is not yet in Arch repositories, neither community, neither AUR. Will test when it will be.

**Comment by krader1961** [comment]
That's odd. Works for me. Which implies that either your *~/.config/fish/config.fish* or one of the global config files is setting it. You might want to sanity check that you can forward env vars by adding a custom var to your ssh/sshd config then setting that before running `ssh` and  verifying the target machine receives it. I added a `TESTME` var to my ssh config, did a `set -x TESTME hello`, then ssh'd and did `echo $TESTME` to verify that whitelisted env vars are indeed passed over the connection. If that works it's pretty strong evidence that something on arch is mucking with your locale settings.

**Comment by faho** [comment]
>Fish 2.4.0 is not yet in Arch repositories, neither community, neither AUR. Will test when it will be.

It is now.

>If that works it's pretty strong evidence that something on arch is mucking with your locale settings.

How about the server, though? If I understand @stephanedaviet correctly, the _client_ is an arch machine. What OS is the server running? That would also be the machine you'd need fish 2.4.0 on.

**Comment by stephanedaviet** [comment]
@krader1961 In fact, it's working with `AcceptEnv` on the server and `SendEnv` on the client. Seems I have missed something last time.

@faho I have tested with fish 2.4.x on the server, it works perfectly. Without `AcceptEnv` in `sshd_config`, it seems it takes the locale of the user as defined on the server, with it, it takes the locale send by the client.

All works like a charm.
