### ISSUE TITLE
empty argument breaks command line

### ISSUE THREAD

**Issue by andrewrk** [fish-shell/fish-shell#3539]
Tested with latest git master which is currently 7356987e6efa15814f93d462cd7e2b6cd91299c5.

```
andy@andypad ~/d/fish-shell> echo (echo -n 'a')(echo -n 'b')(echo -n 'c')
abc
andy@andypad ~/d/fish-shell> echo (echo -n 'a')(echo -n '')(echo -n 'c')

andy@andypad ~/d/fish-shell> 
```

In the second command I expect 'ac' to be printed but instead nothing is printed.

**Comment by faho** [comment]
This works as expected. See http://fishshell.com/docs/current/index.html#cartesian-product.

This is to make things like `for file in $PATH/*` work, even if $PATH is empty or has one element or fifteen or whatever.

**Comment by krader1961** [comment]
That's the expected behavior. Fish doesn't simply concatenate the values -- it creates a [cartesian product of the argumenst](http://fishshell.com/docs/current/index.html#cartesian-product)l

**Comment by andrewrk** [comment]
This sounds related to #159.

Then I could do:

```
andy@andypad ~> echo "$(echo -n 'a')$(echo -n '')$(echo -n 'c')"
$(...) is not supported. In fish, please use '(echo)'.
fish: echo "$(echo -n 'a')$(echo -n '')$(echo -n 'c')"
            ^
```

**Comment by faho** [comment]
Yes.

**Comment by andrewrk** [comment]
Duplicate of #159 .
