### ISSUE TITLE
`set_color normal` outputs a \cO inside screen or tmux which confuses `less`

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3547]
I'm opening this issue solely to document what I've learned in the hope that others may find this issue and benefit from that knowledge.

The `screen` and `tmux` programs use a terminfo definition where the sgr0 attribute includes a [ctrl-O] to "switch in" (i.e., select) the ASCII characters. This is to switch back from using the DEC VTxxx family of terminal's line drawing characters. The xterm family of terminfo definitions use the ISO 2022 sequences for switching between ASCII and DEC VTxxx line drawing characters. The latter are recognized by the `less` pager when invoked with `-R` or `--RAW-CONTROL-CHARS`. The former is not -- instead the [ctrl-O] is displayed as a `^O`.

What this means is that doing `make lint-all | less -R` outside of tmux results in nicely colored cppcheck output. Doing that inside tmux also colors the cppcheck output but also inserts a bunch of `^O` characters from the `set_color normal` invocations that `less` then displays. Making the output rather noisy and confusing. And it's not just `make lint` or `make lint-all`; it's any use of `set_color normal` when running fish inside screen or tmux and looking at the output with `less -R`.

This is not a bug in fish or screen or tmux. It's sadly the result of evolving standards and imperfect adherence to those standards. In this case it's the `less` command that is at fault although this may not rise to the level of a "bug"; but rather a needed enhancement. One way to deal with this is to use `less -r` (lowercase r). That has its own quirks but does make the `^O` chars disappear.

I'm going to explore enhancing `less` to recognize the [ctrl-N] and [ctrl-O] chars as "raw" control chars when invoked with the `-R` or `--RAW-CONTROL-CHARS` flags.

**Comment by krader1961** [comment]
Also, I've been using less v458 that ships with macOS. However, upgrading to less v481 via Homebrew doesn't improve the experience.

**Comment by faho** [comment]
Did you close this on purpose?

**Comment by krader1961** [comment]
> Did you close this on purpose?

Yes because there really isn't anything the fish project can do to fix this. But it's been bothering me for several months and I finally decided to investigate to identify the root cause. It initially seemed like it was a fish bug. Then I realized it was a bug in `less` (or missing feature if you prefer). I opened this just to record the results of my investigation in the hope that it will save us some time if someone else complains about running fish inside tmux causing colored output to display weird inside `less`.

Sadly the `less` project is not very open. You have to email the author with your bug report and hope he responds. AFAICT there is no public issue database. Just a static web page of issues the author is tracking showing just the issue summary. Makes me wonder if it's time to look around for a different pager.
