### ISSUE TITLE
up-or-search doesn't seem to work even when completions are available

### ISSUE THREAD

**Issue by artagnon** [fish-shell/fish-shell#3551]
<kbd>ctrl</kbd>+<kbd>p</kbd> has no effect, although <kbd>ctrl</kbd>+<kbd>e</kbd> would complete it just fine. This happens for many commands; I think this is a history bug? I don't think my `history --merge` has anything to do with it. It works sometimes though.

```
bind \cp 'history --merge ; up-or-search'
```

<img width="138" alt="screenshot 2016-11-14 14 50 53" src="https://cloud.githubusercontent.com/assets/37226/20280448/8c1ca586-aa7a-11e6-98e4-58bfe4b12e06.png">

**Comment by artagnon** [comment]
Also, a <kbd>ctrl</kbd>+<kbd>p</kbd> on a blank line takes me to the second last command, and this is very annoying. I suspect this is due to the `history --merge` being called at the wrong time?

**Comment by artagnon** [comment]
I think I had major issues with that keybinding: it was functioning normally today, after I removed it. I've also observed #405 on different occasions.

**Comment by spinningarrow** [comment]
I've had a similar issue (please let me know if I should create a new issue for that). I had bound `up` to merge history and then search, using this:

     bind \e\[A 'history merge ; and up-or-search'

This had been working very well for quite a while but broke when I upgraded to fish 2.4. Pressing up would ignore the last command entered, which wouldn't show up at all.

**Comment by faho** [comment]
I can't reproduce this anymore, presuming it's fixed.
