### ISSUE TITLE
Command substitution in 'description' argument of 'complete' function not supported?

### ISSUE THREAD

**Issue by haarts** [fish-shell/fish-shell#3552]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.4.0

**OS/terminal used**: Arch Linux/Terminator

I'm writing a bunch of completions for `lxc`/`lxd`. One of the lines I have is this:
```
complete --condition '__fish_lxc_no_subcommand' --command lxc --no-files --arguments list --description '(__fish_description_from_lxc_subcommand list)'
```

The argument to the `--condition` flag is substituted nicely. The argument to the `--description` flag is not. This strikes me as odd. The documentation of [complete](https://fishshell.com/docs/current/commands.html#complete) mentions command substitution explicitly when talking about the `-a` flag but only implies it with the `-n` flag.
Am I correct in assuming not all flags are subject to substitution? If so is there a way around it?

BTW the function I try to call is this:
```
function __fish_description_from_lxc_subcommand --argument-names 'subcommand' --description 'Pluck the first line from the subcommand help output'
    lxc $subcommand ^&1 | head -n 1
end
```

**Comment by krader1961** [comment]
The `-n` (`--condition`) flag takes a shell command that itself can include command substitutions. It's as if the command was the body of a function that was run and whose return value was evaluated.

The `-a` (`--arguments`) value is a bit of an oddball. AFAICT it only treats it as a command substitution to be run if it is enclosed in parentheses. Otherwise it is used as a literal string.

AFAIK no other `complete` flags allow for executing code when the completion is invoked; as opposed to when it is defined.

@faho is our expert on completions so let's see what he has to say.

**Comment by terlar** [comment]
A workaround for dynamic content is to use the `-a` with a function `(__fish_lxc_completions)` and have that function output everything as `subcommand\tdescription` (subcommand tab separated and then description) each separated by a newline. If you output this all these commands will get corresponding completion and description.

Static example:
```
function __fish_description_from_lxc_subcommand --argument-names 'subcommand' --description 'Pluck the first line from the subcommand help output'
    echo subcommand1\tDescription of subcommand1
    echo subcommand2\tDescription of subcommand2
end

complete --condition '__fish_lxc_no_subcommand' --command lxc --no-files --arguments (__fish_description_from_lxc_subcommand list)'
```

**Comment by haarts** [comment]
Ah yes, I see.
Okay. Let me ponder a bit on which option I prefer. Either I just type it out and maintain it or go for this TSV approach. (I feel I'm leaning toward the manual way: less magic.)

**Comment by terlar** [comment]
Yet another way would be to write a manpage that is compatible with the `fish_update_completions` and then run that.

**Comment by floam** [comment]
Docopt... someday?

**Comment by haarts** [comment]
I thought it best to get started: https://github.com/fish-shell/fish-shell/pull/3554

I'll look into that docopt.
