### ISSUE TITLE
completions occasionally bomb out with "complete: -d requires a non-empty string"

### ISSUE THREAD

**Issue by c22** [fish-shell/fish-shell#3557]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version 2.4.0
**OS/terminal used**: 
OSX El Capitan Version 10.11.6
iTerm2 3.0.10

I alluded to this bug in another issue. I still have not been able to reliably reproduce this, best I can tell it just happens if you type too fast sometimes.

Just now I typed `m l<TAB>`

## Results
```
m lcomplete: -d requires a non-empty string
```

It's not specific to a particular completion, I have seen it happen with others.

It also doesn't seem to be to do with custom completions or generated completions, it seems related to auto-completions from shell history.

**Comment by floam** [comment]
Can you try to use fish started as `fish -d3` and see if you can reproduce it, then share the log?

**Comment by krader1961** [comment]
That error can occur in only one way AFAICT: a `complete ... -d ''` command was run. Do you have a  `m.fish` completion script? What does it contain?

**Comment by floam** [comment]
My guess is there is some completion with a `-d $foo` or `--description $foo`.

**Comment by krader1961** [comment]
Yep, that's my guess as well. Or perhaps the equivalent `complete -c m -d (some_command_outputing_an_empty_string)`. Also, @c22, if `m` is a function that wraps another command then we're interested in the completion script for the wrapped command.

**Comment by c22** [comment]
m refers to m-cli for macOS, it turns out there is a vendor completion file that I hadn't noticed before. As mentioned above, I am fairly certain I have seen this behaviour with utilities other than m-cli but I could be mistaken.

https://raw.githubusercontent.com/rgcr/m-cli/v0.1.9/completion/fish/m.fish is the file I have in my release, I can see there is one occurrence of `complete ... -d ''` in the completion file, though I'm not sure why I'm running into this.

@rgcr this might be something you can help with?

**Comment by floam** [comment]
That's definitely going to be what is causing your error. Removing `-d ''` will fix it.

**Comment by c22** [comment]
I'm a bit puzzled as to why this only shows up sometimes and why it shows up for completions that don't have blank descriptions, seems a bit inconsistent but I'm happy for this to be closed and addressed via m-cli.

**Comment by faho** [comment]
What I don't get here is why we print an error in this case?

To me it seems like an empty description should just be a noop.

**Comment by krader1961** [comment]
The author of that bit of code probably expected that if there was no description you would just omit the `-d`/`--description` flag. And if you did specify that flag you probably made an inadvertent mistake if you didn't provide a description. I agree that is a silly restriction which should be removed. Also, the option parsing for that command is also atypical in how it handles flags with missing mandatory values.
