### ISSUE TITLE
"Exportability" must not be a property of environment variable, but separete "scope", or something like that

### ISSUE THREAD

**Issue by tribals** [fish-shell/fish-shell#3559]
- [+] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [+] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version 2.4.0

**OS/terminal used**: 
Ubuntu 15.10/urxvt 9.21

There is no need to mix variable scopes with exportability. These two intended to achieve different tasks in different contexts. Variable scopes intended to be used in shell programming. Exportability intended to be used in command shell.

May be it is better to have different builtins to do these two things.

## Reproduction steps
No one.

**Comment by faho** [comment]
How exactly would this help?

You're asking to have something like `set -g foo bar; export foo`? That just seems more annoying to use, though maybe I just don't notice the advantage.

**Comment by tribals** [comment]
The point is not in separating builtins but separating concepts. Don't be fooled by word "variable". If both is "variables" not means they are the same. Actually they are different.

This may help in configuring environment for command shell.

I asking for removing "exportability" property from variables and turning it into different scope or something like that.

**Comment by jinliu** [comment]
From my personal experience, I constantly use two types of export: 1) a "universal" export that works in all shells and future; 2) a "temporary" export that works only in one shell. So if you want export to be a separate scope, I guess it should actually be two scopes: "universal-export" and "global-export", which is just one scope ("local-export") short of the current system...

**Comment by faho** [comment]
>one scope ("local-export") short of the current system...

We need that too. For functions that temporarily override an exported variable.

E.g. in `__fish_urlencode` we `set -lx LC_ALL C`, to work on a string byte-by-byte. You do not want that to leak into the overall environment, or suddenly everything's in english ASCII.

**Comment by krader1961** [comment]
The current behavior cannot be changed in the manner you're suggesting as it would break backward compatibility. In theory we could live without the `set -lx` case by forcing the user to save the current value in a temp var and restore it before leaving the block. For example,

```
if test "$what" = "do something"
    set -l saved_lc_all $LC_ALL
    set -x LC_ALL C
    external_command
    if set -q saved_lc_all[1]
        set -x LC_ALL $saved_lc_all
    else
        set -e LC_ALL
    end
end
```

But notice how cumbersome that is. It's also a backward incompatible change.

**Comment by zanchey** [comment]
The fact that shell variables and environment variables are distinct but overlapping concepts is one of the more confusing things for people coming newly to shell programming, but they are entrenched for those of us who have been doing it for a while.
