### ISSUE TITLE
ctrl-c does not clear line in 2.4.0

### ISSUE THREAD

**Issue by kyleholzinger** [fish-shell/fish-shell#3561]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.4.0

**OS/terminal used**: macOS

When hitting ctrl-c, it does not clear the line, it actually performs a \r\n. Not sure if this is intended, but if not I'd definitely be interested in knowing how to change back to the old behavior:

## Reproduction steps
1. type in some command
2. click ctrl-c
3. new line is generated

<img width="760" alt="screen shot 2016-11-18 at 10 27 38 am" src="https://cloud.githubusercontent.com/assets/2652762/20435396/eea5af70-ad79-11e6-820a-641f18dcb1c5.png">

## Results
```console
~ ♦ ls^C
~ ♦ fish -v
fish, version 2.4.0
~ ♦
```

**Comment by faho** [comment]
This is intentional. To get the old behavior back,

```fish
function fish_user_key_bindings
    bind \cc 'commandline ""'
end
```

**Comment by kyleholzinger** [comment]
Ah wonderful, thank you!

**Comment by sidpagariya** [comment]
So I tried this in my config.fish but it doesn't seem to work on 2.7.0...
Any help would be great!

Thanks,
Sid.

**Comment by faho** [comment]
@sidpagariya: Do you have any other keybinding related things in config.fish? What does `functions fish_user_key_bindings` say?

**Comment by sidpagariya** [comment]
I have the following in `config.fish` file:
<img width="262" alt="screen shot 2017-12-03 at 9 40 12 am" src="https://user-images.githubusercontent.com/10685754/33526367-0e1804ba-d80e-11e7-8e84-e5a7617a592a.png">

**Comment by faho** [comment]
You've bound `\cC` - that's "hold down control _and shift_ and press c".

Bind `\cc` (with a lowercase c) and it should work.

**Comment by sidpagariya** [comment]
I actually switched `\cc` that was there earlier since it didn't work, to `\cC`...
Weird... it didn't work before and it works now...do I have to restart my shell?

And thanks once again! Cheers!
Sid.

**Comment by faho** [comment]
Ah, crud, you were too quick.

For posterity: I posted a comment along the lines of "That's control-shift-c, try a lowercase 'c' and it should work", but then I actually tested it and it didn't work since we can't seem to distinguish those two cases (and `fish_key_reader` always prints the uppercase form).

>do I have to restart my shell?

Sure. Anytime you make changes in config.fish, they'll only take effect in a new shell or if you explicitly `source` that file again (which may cause side-effects - e.g. if you append to variables or such).

**Comment by sidpagariya** [comment]
Thanks so much, @faho!

**Comment by trisys3** [comment]
Why was this changed? Also, are there any plans to add another binding that causes the old behavior?

Sorry, I know this issue is already closed.

**Comment by kyleholzinger** [comment]
@trisys3 does [the first answer](https://github.com/fish-shell/fish-shell/issues/3561#issuecomment-261569481) not work for you? I imagine that the behavior was implemented because that's the default bash behavior. In any case, this ticket is closed. No more questions from me :)

**Comment by trisys3** [comment]
Yes, the first answer was fine. I was just thinking if another key binding were added, assuming there was "space" in the binding map, we could have both behaviors when we wanted them. I imagine it would sometimes be useful to know what the previous line was, but it's usually distracting, plus tbh it looks kinda ugly.

I could definitely add another question, but I wanted to know why the behavior was changed.

**Comment by kyleholzinger** [comment]
@trisys3 if you want to clear the command prompt, use whatever combination of `ctrl-u`, `ctrl-k`, `ctrl-a`, `ctrl-e` is appropriate-- probably `ctrl-u` most of the time
