### ISSUE TITLE
Keep part of the prompt_pwd the full length.

### ISSUE THREAD

**Issue by sorahn** [fish-shell/fish-shell#3566]
Hey guys, I am trying to have my `prompt_pwd` command spit out something like this `~/s/[project]/f/o/o/b/a/r` and I was directed here to try and figure out a generic way to do it.

Ideally the directory that it would keep is the top level folder once you're inside any git repository.

Ideas I had:
* some `fish_expand_directory_in_pwd_by_index` setting that is set to some int. (lazy copout to a real solution)
* testing for existence of a .git directory? (is this too expensive?)
* string matching with something like `git rev-parse --show-toplevel`

Let me know what you guys think.

**Comment by krader1961** [comment]
For git using either `git rev-parse --show-prefix` or `git rev-parse --show-toplevel` is probably the best solution. Both because it is almost certainly faster than having fish walk the directory hierarchy looking for a *.git* directory (although that should be benchmarked) and because it's considerably simpler than doing it "by hand".

Ideally we would also do this for SVN and Mercurial assuming it is cheap enough. Trying each in order and using the first one that is successful. If doing this is expensive (say more than 10 ms) cache the result in a global var that is updated using a `--on-variable PWD` function to calculate a new short form for use in the prompt.

**Comment by faho** [comment]
We already have these at least for hg and git (dunno if the svn one could actually print the toplevel repo directory), and they are already run once every prompt, at least if you are using the `__fish_vcs_prompt` function (which the samples are. And yes, the dunderscore should be removed).

I'd say they are reasonably cheap - whatever you do with git is basically lightning fast unless your repo is huge, mercurial is dog-slow (IIRC half a second just for "is this a repo?"), but we sidestep it.

However, it's going to be tricky doing this without needing to execute these functions twice, especially if it's supposed to be prompt-agnostic (i.e. just a function you stick in there to shorten the pwd with project, and another to print the branch).

Also, I'm unsure how this should look and if it should be turned on by default, or if it would be too unfamiliar and therefore confusing. Maybe another function, `prompt_project_pwd` or so? Or an option, `prompt_pwd --project` or "--vcs"?

Anyway, I have a quick'n'dirty prototype:

```fish
function prompt_pwd --description 'Print the current working directory, shortened to fit the prompt'
    set -q argv[1]
    and switch $argv[1]
        case -h --help
            __fish_print_help prompt_pwd
            return 0
    end

    # This allows overriding fish_prompt_pwd_dir_length from the outside (global or universal) without leaking it
    set -q fish_prompt_pwd_dir_length
    or set -l fish_prompt_pwd_dir_length 1

    set -l tmp
    if set -l gitdir (git rev-parse --show-toplevel ^/dev/null)
        set tmp (string replace -- $gitdir '' $PWD)
        set gitdir \[(string replace -r '.*/' '' -- $gitdir)\]
        set tmp $gitdir$tmp
        # TODO: Shorten everything after the gitdir
        echo $tmp
    else
        # Replace $HOME with "~"
        set realhome ~
        set tmp (string replace -r '^'"$realhome"'($|/)' '~$1' $PWD)
        if [ $fish_prompt_pwd_dir_length -eq 0 ]
            echo $tmp
        else
            # Shorten to at most $fish_prompt_pwd_dir_length characters per directory
            string replace -ar '(\.?[^/]{'"$fish_prompt_pwd_dir_length"'})[^/]*/' '$1/' $tmp
        end
    end
end
```

**Comment by faho** [comment]
>some fish_expand_directory_in_pwd_by_index setting that is set to some int. (lazy copout to a real solution)

`prompt_pwd` now takes a `--full-length-dirs` option to be set to the number of directories to be kept at full length.

>string matching with something like git rev-parse --show-toplevel

This was asked for more specifically in #8880.

Because the first is done I'm closing this, the second request is tracked in #8880.

**Comment by dominikh** [comment]
It should be noted that OP asked for an arbitrary element of the path to be kept at full length, whereas `--full-length-dirs` only allows specifying a suffix.
