### ISSUE TITLE
fish_config does not work when IPv6 is disabled

### ISSUE THREAD

**Issue by vovams** [fish-shell/fish-shell#3575]
When i run `fish_config`, my browser reports a "Connection refused" error. This happens because the web server started by fish_config accepts connections only on the IPv6 `::` address:

```
vovams@vovams-s-comp ~> netstat -anlp | grep 8000
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
tcp        0      0 :::8000                 :::*                    LISTEN      9061/python         
```

However, i have no IPv6 interfaces, not even loopback, because IPv6 is disabled in my system:

```
vovams@vovams-s-comp ~> sysctl net.ipv6.conf.all.disable_ipv6
net.ipv6.conf.all.disable_ipv6 = 1
vovams@vovams-s-comp ~> sysctl net.ipv6.conf.lo.disable_ipv6
net.ipv6.conf.lo.disable_ipv6 = 1
vovams@vovams-s-comp ~> ip addr show dev lo
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
```

If i enable IPv6 for `lo` (`sudo sysctl net.ipv6.conf.lo.disable_ipv6=0`), fish_config works as expected. I think this is a recent regression, because i remember using fish_config without problems before, i do not remember changing `/etc/sysctl.conf` recently, and i have recently upgraded to 2.4.0 :smile:. I do not remember whether it worked on 2.3.1, though.

Related issue: #1754.

Versions information:
```
vovams@vovams-s-comp ~> fish --version 
fish, version 2.4.0
vovams@vovams-s-comp ~> cat /etc/os-release 
NAME="openSUSE Tumbleweed"
# VERSION="20161116"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="20161116"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20161116"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
vovams@vovams-s-comp ~> uname -a
Linux vovams-s-comp 4.8.7-1-default #1 SMP PREEMPT Thu Nov 10 17:06:41 UTC 2016 (c8f02a2) x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by krader1961** [comment]
It's actually due to a quirk of some versions of Python. I merged a workaround eleven days ago with commit 47a9f99. That fix is not in 2.4.0. The problem also exists in older versions of fish but you may or may not notice depending on the version of Python you have installed.

Can you build from git head and verify that fixes your issue?

**Comment by vovams** [comment]
I was too lazy to download and build from HEAD, so since your commit only changes a python script, i just downloaded that script and replaced the one in my system. This did not fix the issue. I tried adding `print(socket.has_ipv6)` just before the `HOST = "::" if ...` line and got the following output:

```
vovams@vovams-s-comp ~> fish_config 
True
Web config started at 'file:///home/vovams/.cache/fish/web_config-0ANEHN.html'. Hit enter to stop.
```

Also, `python --version` says 2.7.12.

**Comment by vovams** [comment]
Ok, i am sorry, i have just rebooted my PC and `fish_config` now works with the original `webconfig.py`. However, after i execute the following command, it stops working again:

```
sudo iptables -t nat -A POSTROUTING -j MASQUERADE
```

Running `sudo iptables -t nat -D POSTROUTING 1` fixes it again.

**Comment by vovams** [comment]
After more testing, i found that regardless of that `iptables` command fish_config's web server listens on the `::` address with both 2.4.0 and HEAD versions of `webconfig.py`, but without that command my browser still somehow is able to connect to it, even though IPv6 is disabled.

Anyway, it looks like the issue was caused by a bad network configuration in my system, so you probably do not need to address this. That `socket.has_ipv6` check might not work as expected though.

I apologize for opening this issue before double checking everything.

**Comment by krader1961** [comment]
Yeah, not much we can about about firewall rules that break routing traffic through the localhost interface. You'll need to ask for help on a linux networking mailing list.
