### ISSUE TITLE
Homebrew broken under fish; all interaction results in NoMethodError for nil:NilClass

### ISSUE THREAD

**Issue by davidbarsky** [fish-shell/fish-shell#3576]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

Expanding on number 2: I ran the following:

```bash
brew `sh -c 'env HOME=$(mktemp -d) fish'`
```

...and had the same issue occur.

**fish version installed** *(`fish --version`)*: `fish, version 2.4.0`

**OS/terminal used**: macOS 10.12.2 Beta 3. Using Terminal.app.

Talk about the the issue here. 

## Reproduction steps
1. Open fish.
2. Run any `brew` command.
3. See error.

The same does not occur when running `zsh`. Examples are below.

## Results

Under zsh:

```bash
$ brew
Example usage:
  brew search [TEXT|/REGEX/]
  brew (info|home|options) [FORMULA...]
  brew install FORMULA...
  brew update
  brew upgrade [FORMULA...]
  brew uninstall FORMULA...
  brew list [FORMULA...]

Troubleshooting:
  brew config
  brew doctor
  brew install -vd FORMULA

Developers:
  brew create [URL [--no-fetch]]
  brew edit [FORMULA...]
  https://github.com/Homebrew/brew/blob/master/docs/Formula-Cookbook.md

Further help:
  man brew
  brew help [COMMAND]
  brew home
```

Under fish:

```bash
$ brew
/usr/local/Homebrew/Library/Homebrew/utils.rb:304:in `which_all': undefined method `split' for nil:NilClass (NoMethodError)
	from /usr/local/Homebrew/Library/Homebrew/gpg.rb:5:in `find_gpg'
	from /usr/local/Homebrew/Library/Homebrew/gpg.rb:17:in `gpg2'
	from /usr/local/Homebrew/Library/Homebrew/gpg.rb:20:in `<class:Gpg>'
	from /usr/local/Homebrew/Library/Homebrew/gpg.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/requirements/gpg2_requirement.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/requirements.rb:3:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/dependency_collector.rb:5:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/software_spec.rb:7:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/formula.rb:10:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/readall.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/tap.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/compat/tap.rb:1:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/compat.rb:2:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/global.rb:61:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/Homebrew/Library/Homebrew/brew.rb:14:in `<main>'
```

**Comment by faho** [comment]
I'd imagine your $PATH in fish does not contain the path to gpg2. In zsh run `whence gpg2`. In fish, see if $PATH contains that directory.

**Comment by krader1961** [comment]
Notice that the error is from a Ruby module named *gpg.rb*. So this is almost certainly going to be due to a difference in your environment variables.

**Comment by krader1961** [comment]
On my macOS system there is no program named gpg2 -- at least not in my `$PATH`. There is, however, */usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/gpg2*. So this may not have anything to do with your `$PATH` var but probably does have something to do with your environment vars. Try running `env` under each shell and comparing the output.

**Comment by davidbarsky** [comment]
@faho Checked that, wasn't the issue. Kurtis’ suggestions got me going in the right direction. Thanks anyways!

@krader1961 You're entirely right about there being a difference in the `env` output. I previously had `set -gx PATH /usr/local/bin $PATH` at the start of my `config.fish`, but then moved it to the bottom (which solved the issue). Haven't the faintest as to why that would solve the issue with my [dotfiles](https://github.com/davidbarsky/dotfiles/blob/master/fish/.config/fish/config.fish).

(In fairness, this is kinda getting off topic. Just curious _why_ this broke the way it did.)

Again—thanks to both of you for your help! Greatly appreciated. 😄

**Comment by faho** [comment]
Okay, so the "split" call is in [`which_all`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/utils.rb#L302-L313), which uses `env["PATH"]`. There's a comment linking to https://github.com/Homebrew/legacy-homebrew/issues/32789, where $PATH had a malformed and hence non-existent component.

@davidbarsky: Please double-check that your $PATH in fish is set correctly, particularly that all components exist and that, if you `set PATH` anywhere in your configuration, you do so _without_ ":", e.g. `set PATH /usr/bin $PATH`, not `set PATH /usr/bin:$PATH`.

**Comment by davidbarsky** [comment]
@faho My `$PATH` doesn't have the colons, but thanks for the tip! What solved my problem is adding `set -gx PATH /usr/local/bin $PATH` to the bottom of config.fish.

**Comment by krader1961** [comment]
If moving the `set -gx PATH` to the bottom of your *config.fish* fixes the problem that implies you're also setting the path somewhere else in your config script (or a script it sources, etc.). That's because an external command might exist in more than one of the directories in your `$PATH`. Looking at your config I see you have this pattern:

```
set -gx PATH /usr/local/bin $PATH
set PATH $HOME/.cargo/bin $PATH
set PATH $HOME/.local/bin/ $PATH
```

It's usually better to do `set PATH $PATH /new/path`. That way the paths in the preceding assignments have higher priority. Which means that as you read from top to bottom you know the top assignment is highest precedence, the next, second highest, etc. With your pattern it's the inverse.

**Comment by faho** [comment]
>What solved my problem is adding set -gx PATH /usr/local/bin $PATH to the bottom of config.fish.

So that file you linked was the previous, non-working version and the change to the new working one is simply moving that line to the bottom? In that case, I'd still assume that a component of your $PATH doesn't exist (or at least brew has problems with it), and that that code (I don't know ruby) stops after it has found what it's looking for.

Can you compare `env | grep PATH` from before and after? Any component between the new /usr/local/bin position and the old one is a suspect.

Btw, you can also add paths to /etc/paths, which should (AFAIK, I don't have macOS) also add them to other programs.
