### ISSUE TITLE
Treat '-' and '_' alike for fuzzy completions

### ISSUE THREAD

**Issue by introom** [fish-shell/fish-shell#3584]
I have three functions, namely foobar, foo_xxx, and foo_yyy

when I type: foo-<TAB>, fish won't show up with foo_xxx and foo_yyy.

this also indicates, typing fo-xx<TAB> won't complete.

'_' is mostly used in functions, the above issues will all resolve if we define the function as foo-xxx, foo-yyy at first hand, but that violates some how the function naming style.

is fish able to automatically convert between  -/_ ?

this really saves typing pain.

**Comment by krader1961** [comment]
On Fri, Nov 25, 2016 at 9:32 PM, Shiyao.Ma <notifications@github.com> wrote:

> I have three functions, namely foobar, foo_xxx, and foo_yyy
>
> when I type: foo-, fish won't show up with foo_xxx and foo_yyy.
>
> this also indicates, typing fo-xx won't complete.
>
> '_' is mostly used in functions, the above issues will all resolve if we
> define the function as foo-xxx, foo-yyy at first hand, but that violates
> some how the function naming style.
>
> is fish able to automatically convert between -/_ ?
>

No, as your experiment clearly shows. Please open an enhancement request if
you believe you can argue successfully that fish should treat '-' and '_'
as equivalent when performing completions.It might be "friendly" (as in
"fish is the friendly shell") if it did so. However, such a change in
behavior might result in more problems than it solves. Which means making
this change in behavior will require extensive discussion.

-- 
Kurtis Rader
Caretaker of the exceptional canines Junior and Hank

**Comment by ridiculousfish** [comment]
Treating `-` and `_` identically for function names seems like a non-starter to me, but having the fuzzy completion logic treat `-` and `_` the same seems safe and doable. One way would be to essentially treat `-` as the uppercase version of `_`.
