### ISSUE TITLE
fish_vi_cursor not work!

### ISSUE THREAD

**Issue by atreeyang** [fish-shell/fish-shell#3593]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version 2.4.0
**OS/terminal used**: 
MacOS 10.12.1 (16B2657)
Iterm2 Build3.0.12

Talk about the the issue here. 

I use fish_vi_key_bindings. but the cursor do not change according to mode.
fish_vi_cursor not work.

## Reproduction steps
1. `sh -c 'env HOME=$(mktemp -d) fish'`
2. fish_vi_key_bindings
3. press ESC. the cursor do not change.

## Results
```console
> type fish_vi_cursor_handle
type: Could not find 'fish_vi_cursor_handle'
```

**Comment by atreeyang** [comment]
also tried add

> 
> set -g fish_cursor_insert line
> set -g fish_cursor_default block
> set -g fish_cursor_visual underscore
> fish_vi_key_bindings 
> fish_vi_cursor
> 

in my fish.config
not work.

**Comment by faho** [comment]
This was discussed in #3481. We currently disable vi_cursor if `tput Ss` returns > 0 (i.e. "false"y), even in iTerm.

We could reenable it, but that would lead to weird issues in multiline prompts. It seems like currently iTerm can't handle the particular order of sequences we do when we redraw the prompt and change the cursor.

I haven't decided on what to do.

**Comment by krader1961** [comment]
FYI, The sequence for changing the cursor shape on iTerm2 is documented here: https://www.iterm2.com/documentation-escape-codes.html. It looks like we're selecting the `__fish_cursor_konsole` function on iTerm2 which does not send the correct sequences. I verified that the documented sequences work by manually running

```
printf '\033]1337;CursorShape=1\007'
```

to switch from the default block cursor I prefer to a vertical bar.

Should be as simple as implementing a `__fish_cursor_iterm2` function and using that.

**Comment by faho** [comment]
Urgh:

>The OSC command 50 used to be used but it conflicts with xterm, so it is now 1337.

50 is what konsole still uses, otherwise these are completely equivalent. I'm actually torn between adding another function and determining if it's konsole or iTerm (of a version that has the changed number) in that function.

**Comment by krader1961** [comment]
If we differentiate between the terminals in a single function I'd prefer to rename it to something more generic; i.e., replace "konsole" with some other term. Any ideas?

**Comment by faho** [comment]
We could add the code to fish_vi_cursor, though that sounds like it's purely for vi-mode. Or we keep the "konsole" because it's a konsole-ish sequence. The xterms sequence is also used by things that aren't technically xterm.

Or we do the event handling stuff in fish_vi_cursor and put the term detection in fish_cursorshape or so, that could also be used at startup. Of course the question then is where the rather expansive support check should be - we don't want to maintain that beast twice.
