### ISSUE TITLE
werid behavior regarding emacsclient and fish on macos

### ISSUE THREAD

**Issue by introom** [fish-shell/fish-shell#3594]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [ ] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:

fish, version 2.4.0

**OS/terminal used**: 
macOS serria
iTerm2

Talk about the the issue here. 

emacsclient -t -a "" (SOME_COMMAND |psub) fails.

WORSE, subsequent call to emacsclient, even without process substitution also fails.

## Reproduction steps
1. 
emacsclient -t -a ""  (ps |psub)

this fails to launch emacsclient.

2. …
Now, in the same pty, even 
emacsclient -t -a ""

also fails.

I tested all the above on Linux, it works fine.

**Comment by faho** [comment]
This works for me on Linux as well, I don't have the ability to test on macOS.

However, I'm not sure this is a fish issue. Have you tried with e.g. bash? 

Do you have the same emacs version on both systems?

**Comment by faho** [comment]
@introom: Have you tried this some more?

**Comment by introom** [comment]
@faho Sorry, I don't have access to macOS machines these days.

**Comment by faho** [comment]
In that case, let's close this.
