### ISSUE TITLE
New fish conda-forge package: Looking for maintainers, MacOS issues

### ISSUE THREAD

**Issue by mdraw** [fish-shell/fish-shell#3597]
I have created a conda-forge feedstock for fish: https://github.com/conda-forge/fish-feedstock.
If you don't know conda-forge, you can read about it on https://conda-forge.github.io/. Basically this means that you can now easily install fish with the conda package manager (http://conda.pydata.org/docs/).

Currently I am the only maintainer of the feedstock. If anyone of the fish-shell team wants to be added as a recipe maintainer, please tell me!

For now there are only builds for Linux. MacOS is disabled because of this pcre2 build issue: https://github.com/conda-forge/fish-feedstock/issues/1.
The code that is executed when building the recipe is located at https://github.com/conda-forge/fish-feedstock/blob/master/recipe/build.sh. I probably did something wrong there.

**Comment by zanchey** [comment]
I don't think there's anything for us to do here, so I'm going to close this for now.

**Comment by krader1961** [comment]
I'm a big fan of the Conda project since I'm also a fan of Python. Nonetheless, I agree with @zanchey that at this time we can't take on this dependency.
