### ISSUE TITLE
SEGV when $HOME is unset and $USER contains a user name not in the system's user database

### ISSUE THREAD

**Issue by stephane-chazelas** [fish-shell/fish-shell#3599]
With current git HEAD (121109ee4d2ce9f23a6dfe4e377800c75566de85)

```
$ env -u HOME USER=foo ./fish -c ''
zsh: segmentation fault  env -u HOME USER=foo ./fish -c ''
```

Fixed with:

```
diff --git a/src/builtin.cpp b/src/builtin.cpp
index 91c5601..1e5f12f 100644
--- a/src/builtin.cpp
+++ b/src/builtin.cpp
@@ -2450,6 +2450,7 @@ static int builtin_cd(parser_t &parser, io_streams_t &streams, wchar_t **argv) {
         dir_in = env_get_string(L"HOME");
         if (dir_in.missing_or_empty()) {
             streams.err.append_format(_(L"%ls: Could not find home directory\n"), argv[0]);
+	    return 1;
         }
     } else {
         dir_in = env_var_t(argv[1]);
diff --git a/src/env.cpp b/src/env.cpp
index cf49e7e..6241d32 100644
--- a/src/env.cpp
+++ b/src/env.cpp
@@ -426,7 +426,7 @@ void env_init(const struct config_paths_t *paths /* or NULL */) {
         const env_var_t unam = env_get_string(L"USER");
         char *unam_narrow = wcs2str(unam.c_str());
         struct passwd *pw = getpwnam(unam_narrow);
-        if (pw->pw_dir != NULL) {
+        if (pw != NULL && pw->pw_dir != NULL) {
             const wcstring dir = str2wcstring(pw->pw_dir);
             env_set(L"HOME", dir.c_str(), ENV_GLOBAL | ENV_EXPORT);
         }
```

**Comment by floam** [comment]
Thanks for reporting. I think I've got it fixed.

**Comment by floam** [comment]
It's not necessary to modify `cd` to fix this particular problem, because when `pw == NULL` while trying to dig up a `$HOME`, we can go back and force `$USER` to set itself using `getpwuid`. It didn't do it the first time around because we let it be if it was not missing or empty. With a good `$USER` in place, we can then get `HOME` set.

**Comment by stephane-chazelas** [comment]
`cd` is still wrong.

```
> set -e HOME
> cd
fish: src/env.cpp:733: const wchar_t* env_var_t::c_str() const: Assertion `!is_missing' failed.
zsh: abort      ./fish
```

**Comment by floam** [comment]
Thanks. f47ebc4b1cb3795666eca992b903c4c2c9bbcc25 should have this fixed.

**Comment by stephane-chazelas** [comment]
Thanks, but that now outputs two error messages:

```
> cd
cd: Could not find home directory
cd: $HOME not set
```

See also (with HOME set):

```
> cd ''
cd: $HOME not set
```

See my original patch, you'd want to return straight away with an error if `cd` is called without argument and `$HOME` is not set or empty.

**Comment by floam** [comment]
I considered the second error clarifying. That is indeed a bug with `cd ''`. It's checking `dir_in` too late.

How would you expect `cd` with no arguments to behave when `$HOME` is unset or empty?

**Comment by stephane-chazelas** [comment]
I'd expect it to return with an error (either one of the two `fish` is currently outputting look fine to me) like most other shells do.

**Comment by zanchey** [comment]
How does this even happen.

**Comment by floam** [comment]
I addressed my dumb error output in a8b2da840540e76798eefb5fc97f4cb7fe9b7d42.

**Comment by floam** [comment]
> How does this even happen.

It's quite a thing, both crashers had something to do with `$HOME`, but were totally independent bugs.

**Comment by ridiculousfish** [comment]
@floam can you please add a test for this case?
