### ISSUE TITLE
functions -c broken

### ISSUE THREAD

**Issue by Darkshadow2** [fish-shell/fish-shell#3601]
- [ ] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
2.4.0-175-gf47ebc4

**OS/terminal used**: 
OpenBSD 5.9, macOS 10.11.6
iTerm, Terminal.app

Talk about the the issue here. 

`functions -c` seems to be broken in this build. Any attempt to use it tells you that the function name you are copying it to is invalid.

## Reproduction steps
$ functions -c cd mycd

## Results
```
functions: Illegal function name “mycd”

       functions -- print or erase functions

   Synopsis
       functions [ -a | --all ] [ -n | --names ]
       functions -c OLDNAME NEWNAME
       functions -d DESCRIPTION FUNCTION
       functions [ -e | -q ] FUNCTIONS...

functions: Type “help functions” for related documentation
```

**Comment by floam** [comment]
Bisected to 320cb6857f2b8c44e2caf76553ae931a15e10e81 @krader1961

**Comment by floam** [comment]
This is because `wcsfuncname` was changed not to return a pointer any longer to the first invalid character encountered, returning the `NULL` at the end of the string if it is OK. It's a bool now, and the logic is inverted, while copying it checks if the value is `0` for success.

**Comment by xdudi** [comment]
I have very similar problem:
```
~> function -d 'any text' test_func
       echo $argv
   end; and test_func 1 2 3
function: Illegal function name '-d'
~> 
```

**Comment by krader1961** [comment]
@xdudi: That's a deliberate change. See issue #2827. The function name has to be the first argument after the `function` keyword. I'm curious how you came to write the definition in that form since it's never been documented as being legal.

**Comment by floam** [comment]
>  I'm curious how you came to write the definition in that form since it's never been documented as being legal.

I think it's pretty natural, and that this change will trip people up. A lot of utilities typically take arguments *before* the name of the object or filename they are about to create, modify, or work on. Most of the time people do not use options when they make a function. When they do, I think it's a bit of a gamble to assume they will think to put the function name first.

**Comment by floam** [comment]
(still, I like the simplification. What might be nice is a more helpful error message, though. And it's too bad completions don't work on it to guide folks.)
