### ISSUE TITLE
__fish_print_hostnames broken

### ISSUE THREAD

**Issue by Darkshadow2** [fish-shell/fish-shell#3603]
@krader1961 Commit [11a60c8](https://github.com/fish-shell/fish-shell/commit/11a60c8374c21c299bab35ae12a30b54a44bc9e3) broke ```__fish_print_hostnames```.

Lines 13 - 16 were broken up and had a comment in the middle of it, so ```fish_indent``` put the comment at the end of line 13, and started a new line that starts with a pipe. That should actually all be on line 13, I guess with the comment removed (which is, amusingly enough, 'Strip comments').

**Comment by krader1961** [comment]
Thanks for catching that. I'll fix it asap then convert this issue into one to investigate why `fish_indent` did that.

**Comment by krader1961** [comment]
I see I've already opened issue #2928 documenting the `fish_indent` bug responsible for this issue. Closed with commit 1ca166778.
