### ISSUE TITLE
`fish -c ')'` (invalid syntax) should exit with a non-zero status

### ISSUE THREAD

**Issue by CGamesPlay** [fish-shell/fish-shell#3606]
Fish exits cleanly, despite the fact that invalid input was supplied. This differs from every other case I can think of, where fish exits 127. For example, `(` and `end` both return 127 in this case.
Reproduces in 2.4.0.

## Reproduction steps
1. `fish --no-execute -c ')'; echo $status`

## Results
```console
~ $ fish --no-execute -c ')'; echo $status
Illegal command name ')'
fish: )
      ^
0
```

## Expected results
```console
~ $ fish --no-execute -c ')'; echo $status
Illegal command name ')'
fish: )
      ^
127
```

**Comment by krader1961** [comment]
I concur. Note too that omitting the `--no-execute` flag doesn't change the exit status.
