### ISSUE TITLE
Keep sorting for completions

### ISSUE THREAD

**Issue by terlar** [fish-shell/fish-shell#361]
If I have a completion method that returns results in the relevant order, I'd like to have the possibility to keep this order instead of sorting alphabetically.

Perhaps a switch that tells the completion to leave this alone?

**Comment by danielcompton** [comment]
This would be a really great feature, I also have the same problem where tags are sorted ahead of branches.

**Comment by ridiculousfish** [comment]
I wonder how bad it would be to only sort file completions. I'll take a crack at this.

**Comment by krader1961** [comment]
FYI: Some completion scripts do not deduplicate their output and instead rely on the existing fish sorting of the suggestions to do so. So if this is ever implemented we need to decided whether to retain de-duping of the suggestions without sorting them or require that such completions handle the de-duping on their own.

**Comment by mqudsi** [comment]
I just ran into this with `git commit --fixup`, where fish actually ends up sorting all commits ever by sha1 instead of showing them in reverse order, rendering completions useless here.
