### ISSUE TITLE
Doc: "Autoloading functions" applying to aliases?

### ISSUE THREAD

**Issue by cmarqu** [fish-shell/fish-shell#3612]
The [Autoloading functions](http://fishshell.com/docs/current/index.html#syntax-function-autoloading) section doesn't mention whether the autoloading also applies to aliases.
The last sentence in the section immediately before seems to suggest that ``alias`` is just a shortcut for a function and thus _may_ fall under autoloading: "To easily create a function of this form, you can use the alias command."

**Comment by faho** [comment]
Check `type alias`. Aliases _are_ functions, so everything that applies to functions also applies to aliases.

Note that if you execute `alias key value`, it will do the equivalent of `function key; value; end`, so if you do that in a running session (or config.fish) it will load the function directly. But if you do `alias key value` and then `funcsave key`, it will store the function in a "key.fish" file which will then be autoloaded.

Any ideas on how to make the docs clearer on this?

**Comment by krader1961** [comment]
I created commit ee669145 to make it clear that autoloading is not applicable to aliases.
