### ISSUE TITLE
The "alt+h" manpage binding could detect git subcommands

### ISSUE THREAD

**Issue by radomirbosak** [fish-shell/fish-shell#3618]
So that after writing
```console
$ git add
```
and pressing alt+h the manpage for git-add would be displayed. If no known git subcommand could be recognized, the manpage for git would be displayed.

I know it's not nice to have exceptions from rule just for one command, but git is so frequently used that it would be IMO worth it.

**Comment by faho** [comment]
This is easy to do in a hacky manner, but I'd rather have a slightly more general solution and that's gonna be tough.

There's a few commands that organize their man pages like this. On my system there's at least flatpak, ostree, mu and ip. So this would be nice to have for them as well.

One reasonable approximation would be to get a "subcommand" (in this case just the first thing after the command that doesn't start with a "-") and try to get a command-subcommand man page. That way `git --no-pager add foo` would work, but `git --work-tree /bar add` wouldn't. 

The remaining question is if there are going to be any false-positives that way.

Any more intelligent solutions would require a hook into the completion system (@ridiculousfish: worth looking into for docopt?).
