### ISSUE TITLE
having `fish_indent` retain alignment of command args

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3622]
The `fish_indent` command has a couple of behaviors that are controversial. For example, how it formats the following:

```
x
or y

if x
    or y
    do_something
end
```

Many people would prefer those statements to be formatted differently. However that isn't why I'm opening this issue. Those particular cases will be handled by issue #2646.

This issue is to discuss what to do about sequences of statements like this one from *share/completions/abook.fish*:

```
complete -c abook -s h -d 'Show usage'
complete -c abook -s C -l config -d 'Use an alternative configuration file' -r
complete -c abook      -l datafile -d 'Use an alternative addressbook file' -r
...
complete -c abook      -l informat -d 'Input file format' -xa '(__fish_complete_abook_formats in)' -n $convert
complete -c abook      -l outformat -d 'Output file format' -xa '(__fish_complete_abook_formats out)' -n $convert
complete -c abook      -l infile    -d 'Input file (default: stdin)' -r -n $convert
```

Notice the imperfect attempt to keep a given flag vertically aligned in that example. Other completion scripts do a better job at having a consistent vertical alignment of flags. The problem is that `fish_indent` doesn't preserve such alignment. Which means we can't run it against our completion scripts without potentially annoying some people. On the other hand the non-trivial completion scripts  which contain more than `complete` commands tend to have major style bogosities (such as inconsistent indentation) and it would be nice to normalize those to a consistent style. It would also be nice if we could do `make style-all` and have it affect all fish scripts in this project without having to exclude completion scripts.

Note that our official style for C++ code does not preserve such vertical alignment. And while we don't have an official style for Python (given how little of it we have) most style guides (e.g., Google's) also do not preserve vertical alignment for such sequences of lines. That's primarily because doing so is so complex as to be impractical.

This issue is to discuss whether someone feels strongly enough about preserving vertical alignment that they will do the hard work of modifying `fish_indent` to do so.

**Comment by ridiculousfish** [comment]
Interesting idea. I'd love to find a way to do this, but need to learn more about how state-of-the-art formatters work to judge if I could take it on.

**Comment by krader1961** [comment]
I too would like to find a way to do this, @ridiculousfish, but it isn't practical. Even if we only did this for consecutive sequences of `complete` commands take a look at *share/completions/abook.fish* which has a `set -l` in the middle. Ignoring something like that then requires parsing the entire script and identifying common sub-blocks of `complete` commands. And what do we do if a `complete` command appears inside another block and at the file level? Then there is the issue of identifying which flags should be aligned.

The only semi-practical solution is to retain internal (but not leading) whitespace for specific commands such as `complete`. That obviously doesn't do anything to make the alignment consistent but at least wouldn't lose the manual attempt at alignment. There isn't any way to do this in general. We could only do it by special casing certain statements.

**Comment by krader1961** [comment]
Note that the "parsing the entire script and identifying common sub-blocks" in my previous comment means a radical rewrite of `fish_indent` since it currently rewrites the fish script approximately linearly as it is parsed rather than looking at the global picture of the script.

My original comment was a bit of a straw-man since I don't really think anyone is willing to step up and say they are going to implement vertical-alignment behavior. At best we could modify `fish_indent` to regurgitate a statement, including its original whitespace, if the initial command is `complete`.  And even that is likely to be so difficult to implement as to be not worth the effort.

**Comment by ridiculousfish** [comment]
My understanding is that advanced formatters treat it as an optimization problem. They assign penalties for misaligning, breaking in weird places, etc. and then try to minimize the cost function. This reflects the subjective nature of formatting, and should be better than trying to juggle lots and lots of rules and special cases.

A super-easy thing we can do is add directives in comments (i.e. pragmas) to hint the formatter. e.g.:

    # fish_indent: disable
    complete -c abook -s h -d 'Show usage'
    complete -c abook -s C -l config -d 'Use an alternative configuration file' -r
    complete -c abook      -l datafile -d 'Use an alternative addressbook file' -r
    # fish_indent: enable

**Comment by krader1961** [comment]
I should point out that a casual review of our completion scripts show that few of them attempt to maintain any sort of consistent vertical alignment of flags. And those that do make the attempt often fail.

> A super-easy thing we can do is add directives in comments (i.e. pragmas) to hint the formatter.

I don't know about "super-easy" but that's probably the only practical solution. And, yes, the general case is an optimization problem. The problem with preserving, let alone improving, internal whitespace is that it necessarily requires special-casing certain constructs. You don't want the formatter to preserve odd internal whitespace in situations like this

```
for       i      in      (commandline         -opc)
   for x in a  b   c    d     e      f
        echo $i $x
   end
end
```

The formatter is normally working at a semantic rather than lexical level. Switching from the former to the latter introduces a lot of complexity and opportunities for bugs.

**Comment by krader1961** [comment]
I reformatted all 500 completion scripts. An inconsequential number of changes were internal whitespace elimination for `complete` commands. And one example where preserving that whitespace doesn't make much sense; e.g., *share/completions/expand.fish*. A huge number of changes involved the functions defined within those scripts. To be fair there are a small number of completion scripts, such as *share/completions/gphoto2.fish*, where the manual vertical alignment is both consistent and valuable to a human reading the script. But even those examples are really weak arguments for preserving such internal whitespace IMHO.

**Comment by krader1961** [comment]
I've removed the RFC label because the only practical solution is a pragma such as the `# fish_indent: disable` proposed by @ridiculousfish to cause subsequent statements to be regurgitated verbatim.

**Comment by krader1961** [comment]
I'm closing this because I do not believe the effort to implement it can be justified. Definitely not in relation to at least 100 other open issues. Such as making it possible to change which command history file is used. Also, many other language reformatting tools such as `gofmt` and guidelines for languages like Python explicitly disallow such vertical alignment. Obviously that is due to the difficulty in supporting such vertical alignment whitespace. Too, introducing a pragma that allows people to wholesale avoid the usual fish script formatting rules is likely to be abused. It would be better to improve `fish_indent` to either preserve explicit line splits and/or split lines an acceptable line width (currently 100 characters).

**Comment by floam** [comment]
Why say we will not implement? It's not easy, but there is no consensus that we wouldn't all like to see it.

**Comment by faho** [comment]
We have now restyled our codebase without alignment and it's *fine*, so let's just close this again.
