### ISSUE TITLE
Cursor not changed on tmux window change

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#3623]
See https://github.com/fish-shell/fish-shell/issues/3429#issuecomment-264756649.

Tmux sends a sequence on window change that we ignore. We should use it to change the cursor again.

**Comment by nilehmann** [comment]
I might add that this should also be done when entering/exiting copy mode. I don't know if this can be solved the same way.

**Comment by faho** [comment]
Oooh, this and #4788 are the same thing. Closing this because that one has a nicer comment.
