### ISSUE TITLE
Filename completion: Exclude files by suffix

### ISSUE THREAD

**Issue by paddor** [fish-shell/fish-shell#3624]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: `2.4.0-144-gaad2848`

**OS/terminal used**: Tmux on Ubuntu Linux

When completing filenames, I don't want to see backup files (`*~`). How to achieve that?

**Comment by krader1961** [comment]
AFAIK you can't customize file name completions. It's a core part of the C++ code and isn't configurable. The best you can do today is to create a custom completion for specific commands. See issue #988 for an example.

**Comment by paddor** [comment]
Thank you! :)
