### ISSUE TITLE
Current directory is missing from tab title in Apple Terminal

### ISSUE THREAD

**Issue by azixMcAze** [fish-shell/fish-shell#3629]
**fish version installed** *(`fish --version`)*: 2.4.0

**OS/terminal used**: OSX 10.10.5 (Yosemite) with Apple Terminal 2.5.3

Since I upgraded to fish 2.4.0, the tab title no longer displays the current directory, it only displays the current job, i.e. `fish` instead of `fish /Users/username`

I could not fix it by using `fish_title` because it is reset everytime I open a new tab.
The culprit seems to be `__fish_config_interactive` that overwrites `fish_title` when using Apple Terminal

Removing the function overwrite from `__fish_config_interactive` fixed the problem for me

**Comment by faho** [comment]
@azixMcAze: Can you try 18cc06b38ffde91e3ccf8c0999cfaa701423e0f8?

The idea behind removing fish_title for that particular terminal was that adding our default title would make things _worse_ than what the term does on its own. Of course the user should still be able to customize it, which is what that commit does.

**Comment by azixMcAze** [comment]
@faho 18cc06b allows me to customize `fish_title`

But In my case, the default title was working correctly with fish v2.3.1 and is working correctly in version 2.4.0 if I remove the overwrite.
My version of Apple Terminal does not seems to require this workaround. Was it added for newer versions of OSX ?

**Comment by faho** [comment]
>Edit : This issue is a duplicate of #3578

That one was explicitly about a _custom_ title. If I understand you correctly, you don't have one?

>Was it added for a newer versions of OSX where Terminal displays a better title by defaut ?

I have no idea. @floam?

**Comment by faho** [comment]
>Edit : This issue is a duplicate of #3578

That one was explicitly about a _custom_ title. If I understand you correctly, you don't have one?

>Was it added for a newer versions of OSX where Terminal displays a better title by defaut ?

I have no idea. @floam?

**Comment by faho** [comment]
>Edit : This issue is a duplicate of #3578

That one was explicitly about a _custom_ title. If I understand you correctly, you don't have one?

>Was it added for a newer versions of OSX where Terminal displays a better title by defaut ?

I have no idea. @floam?

**Comment by faho** [comment]
>Edit : This issue is a duplicate of #3578

That one was explicitly about a _custom_ title. If I understand you correctly, you don't have one?

>Was it added for a newer versions of OSX where Terminal displays a better title by defaut ?

I have no idea. @floam?

**Comment by faho** [comment]
>Edit : This issue is a duplicate of #3578

That one was explicitly about a _custom_ title. If I understand you correctly, you don't have one?

>Was it added for a newer versions of OSX where Terminal displays a better title by defaut ?

I have no idea. @floam?

**Comment by faho** [comment]
@floam: Is it possible that Terminal.app's own title isn't all that great in some versions? Should we maybe conditionalize the override on the version?

**Comment by floam** [comment]
Maybe. @azixMcAze, can you post a screenshot of what the preferences look like in the Yosemite Terminal.app? Specifically the screen that configures the tab title. 

And, what is the output of `echo $TERM_PROGRAM_VERSION`?

**Comment by azixMcAze** [comment]
@floam `$TERM_PROGRAM_VERSION` is `343.7`

What the terminal looks like with the empty `fish_title` from 18cc06b:
![capture d ecran 2016-12-15 a 18 38 39](https://cloud.githubusercontent.com/assets/1919205/21235142/db30fb02-c2f5-11e6-8fb9-9a6b85a02a1e.png)
What it looks like without  `fish_title` defined:
![capture d ecran 2016-12-15 a 18 38 58](https://cloud.githubusercontent.com/assets/1919205/21235177/fdaa5f7a-c2f5-11e6-9981-d6969f78ab7b.png)
The preference windows does not allow to configure the tab title, only the window title:
![capture d ecran 2016-12-15 a 18 20 11](https://cloud.githubusercontent.com/assets/1919205/21234764/4a38b302-c2f4-11e6-88f1-ddf96f82c756.png)
The tab inspector allows to put a custom title but it is a custom message and it will be overwritten the next time the shell prompt is presented:
![capture d ecran 2016-12-15 a 18 25 13](https://cloud.githubusercontent.com/assets/1919205/21234789/5fcfeaaa-c2f4-11e6-8aa6-e2d0b17afa28.png)

**Comment by floam** [comment]
So, you are getting the current directory shown with the home icon and the word 'matthieu' in the main window title. I guess you cannot configure this version of Terminal.app to show you the same information in the tab title. I guess we could disable this behavior for versions of Terminal.app as old as this if people generally prefer to prior behavior.

**Comment by azixMcAze** [comment]
Yes I think this new behaviour should only enabled for new versions of Terminal. I am 2 versions of OSX behind. I don't know how it behaves with OSX El Capitan

**Comment by zanchey** [comment]
I am really struggling to get my head around all the changes to OS X Terminal titles; are we planning to change the behaviour here? @floam @faho

**Comment by faho** [comment]
@zanchey: floam's idea was that new Terminal.app's will set a nicer title on their own than we provide by default. So he stopped us from setting the title. In this issue it came to light that older Terminal.app versions will not set a good title, so we need to predicate that change on the version.

@floam: I suggest we only defer to Terminal.app if it is at least the version you are currently using, or any older version you can personally verify.

(Thanks for double-checking, btw!)

**Comment by zanchey** [comment]
Thanks - is the fix reasonably straightforward? Can we try for 2.5b1?

**Comment by faho** [comment]
@zanchey: Yes, the fix is very simple. I could do it, all I need is the minimum Terminal.app version that should set the title. And we don't even really need the actual minimum, just the smallest version we know will set a good title.

Alternatively, we could revert the entire thing. If we can't pick a version before 2.5b1, I'd suggest doing that.

@floam: Which version should we use?

**Comment by floam** [comment]
300 I think.

**Comment by faho** [comment]
Okay, so here's what we're gonna do:

- In Integration_2.5.0: Revert the empty fish_title in Terminal.app

- In master: Only empty fish_title for $TERM_PROGRAM_VERSION >= 300

**Comment by faho** [comment]
Since @azixMcAze has $TERM_PROGRAM_VERSION = 343.7, we're gonna need a higher version.

**Comment by azixMcAze** [comment]
Hello,

OSX 10.11.5 (El Capitan) has $TERM_PROGRAM_VERSION = 361.1 and displays a nice title like macOS Sierra. So you need a version between 343.7 and 361.1.
I can check if I find a mac with an earlier version of El Capitan. However I think one can assume that Terminal.app from El Capitan 10.11.0 would have same behaviour as 10.11.5 and that you could use 343.7 as the max version.

The mac used to submit this bug-report (Yosemite 10.10.5) has crashed and I had to update to macOS Sierra 10.12. If you fix this in fish 2.5.0, it will be a bit difficult for me to test it :(

**Comment by faho** [comment]
5996962749974aa350882dd737f9184e03ef3cfa removes this from 2.5.0.

>OSX 10.11.5 (El Capitan) has $TERM_PROGRAM_VERSION = 361.1 and displays a nice title like macOS Sierra. So you need a version between 343.7 and 361.1.

Okay, I'll use 361 as the minimum version for blanking fish_title.

**Comment by zanchey** [comment]
@faho, did you make this change in master? I'm going to merge your changes for 2.5.0 back into master.

**Comment by faho** [comment]
@zanchey: I did not. Merging it back is okay.
