### ISSUE TITLE
fish_clipboard_paste with empty clipboard reports error from commandline

### ISSUE THREAD

**Issue by TieDyedDevil** [fish-shell/fish-shell#3637]
- [ ] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [ ] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: fish, version 2.4.0-222-g05a640b-dirty

**OS/terminal used**: Fedora 25 / st

Talk about the the issue here. 

Given vi key bindings and an empty X clipboard, invoking `fish_clipboard_paste` via the `\cv` keystroke emits this message:

```
commandline: Invalid combination of options,
insertion mode switches can not be used when not in insertion mode
/usr/local/share/fish/functions/fish_clipboard_paste.fish (line 9):             commandline -i -- $data
                                                                                ^
in function “fish_clipboard_paste”
        called on standard input


       commandline -- set or get the current command line buffer

   Synopsis
       commandline [OPTIONS] [CMD]

commandline: Type “help commandline” for related documentation
```

This could be prevented with a check in `fish_clipboard_paste`, but I suspect that the underlying problem may be that `commandline` needs to be able to insert zero arguments.

## Reproduction steps

Clear the clipboard:
$ xsel --clipboard -c

Type ctrl-v

## Results

See above.

**Comment by faho** [comment]
Ah crud. I just assumed an empty clipboard would result in a non-zero exit code.

Fixing.
