### ISSUE TITLE
The '-A' switch of 'complete' command is not documented

### ISSUE THREAD

**Issue by radomirbosak** [fish-shell/fish-shell#3640]
The `-A` switch of the `complete` command

is used
```console
$ grep -r complete share/completions/ | grep " \-A " | wc -l
35
```
but not documented
```
$ grep " \-A " doc_src/complete.txt | wc -l
0
```

**Comment by krader1961** [comment]
It's short for `--authoritative` which is also not documented. Neither are their counterparts `-u` and --unauthoritative`. I couldn't find any others  that are undocumented.

**Comment by faho** [comment]
The idea was that "authoritative" completions specify _all_ possibilities, so everything that isn't in the completions can be marked as an error.

This was apparently removed when the parser was rewritten and the documentation was removed in 19112980ee5c3703e50f42a9e05781e5a32f1e88.

We should either re-add that feature or remove it - either from our code or completely (i.e. print an error when it is passed).

**Comment by krader1961** [comment]
It seems like adding a warning if it is used is the appropriate course of action because, again, we need to be sensitive about backward compatibility. At the same time there is no reason to use those flags in the completions we ship so their presence should be removed.

@radomirbosak: Do you want to take a stab at cleaning this up?

**Comment by krader1961** [comment]
@radomirbosak: See the `builtin_complete` function in *src/builtin_complete.cpp*. You also need to remove the `authoritative` member from the `completion_entry_t` class and mentions of it.

**Comment by radomirbosak** [comment]
@krader1961 thanks for help. In PR #3660 I did what you suggested.
