### ISSUE TITLE
put the whole command in $argv for fish_command_not_found

### ISSUE THREAD

**Issue by aliva** [fish-shell/fish-shell#365]
Sometimes i enter command in my other layout.

so it will call the `fish_command_not_found` function
I want to fix the entred command and rerun the fixed command in this function.

my problem is with  `fish_command_not_found` function arguments:

`$argv` only contins the command (It doesn't have arguments of the wrong command)
I want to have access to command and arguments both.

I have asked a question in [mailing list](http://sourceforge.net/mailarchive/message.php?msg_id=29985272) and no one answered so I thought it may be a bug.

**Comment by RomanHargrave** [comment]
I am currently working on a hack using the fish_command_not_found event to pass things that look like `:cd dir` on to neovim using RPC and also think that this would be a great improvement.

**Comment by RomanHargrave** [comment]
I have fixed this problem in #2030

**Comment by ridiculousfish** [comment]
Fix merged in 3559f20c8ffca8b036ff4aa6833e9e4c67eea7fc. Thanks for reporting this!

**Comment by zanchey** [comment]
I haven't had a chance to test, but at least some `command_not_found` handlers are likely to be confused by this - see #1918. It's probably worth using `$argv[0]` in the `__fish_command_not_found` handler.

**Comment by ridiculousfish** [comment]
You're right, that absolutely breaks `/usr/lib/command-not-found` on Ubuntu. Nice catch!

**Comment by ridiculousfish** [comment]
Fix to only pass the command name to command_not_found in 7a1fc028e309beef98fda54060d8f77aac377e6d
