### ISSUE TITLE
fish should handle CRLF line endings in a manner consistent with bash/zsh

### ISSUE THREAD

**Issue by sagebind** [fish-shell/fish-shell#3655]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.4.0

**OS/terminal used**: Alpine Linux / GNOME terminal

Escaping line endings to spread commands across multiple lines does not work as expected when using CRLF line endings. I have not verified this, but my understanding is that this happens under any OS.

This has caused much headache for us ([Oh My Fish](https://github.com/oh-my-fish/oh-my-fish)) in the past when users clone our repo with Git set to convert to CRLF on checkout. Recently [solved using .gitattributes](https://github.com/oh-my-fish/oh-my-fish/pull/458), but very much seems like a workaround for unexpected behavior.

I understand that using backslashes on line endings to write commands across multiple lines is probably a side effect of escape handling, but it is perceived as a feature that should be fixed to escape an entire CRLF or just CR sequence if present.

## Reproduction steps
Example command that demonstrates the issue:

```fish
echo echo this should print exit: \\\r\nexit\r\n | fish
```

Executes a script like this:

```fish
echo this should print exit: \
exit
```

but with using CRLF line endings. The LF line ending version works as expected:

## Results
Expected:

```fish
~ $ echo echo this should print exit: \\\r\nexit\r\n | fish
this should print exit: exit
```

Actual:

```fish
~ $ echo echo this should print exit: \\\r\nexit\r\n | fish
this should print exit:
```

**Comment by krader1961** [comment]
Sorry, but UNIX programs expect just LF as a line ending. Bash and zsh provide a more useful error in this situation:

```
$ echo echo this should print exit: \\\r\nexit\r\n | bash
this should print exit:
bash: line 2: $'exit\r': command not found
$ echo echo this should print exit: \\\r\nexit\r\n | zsh
this should print exit:
zsh: command not found: exit^M
```

Fish should probably be modified to produce a similar diagnostic message.

FWIW, If you create a file using DOS/Windows line ending conventions and try to use it on UNIX you'll get weird behavior. And that isn't just restricted to shell scripts.

**Comment by anordal** [comment]
Note that the hashbang won't work either, in a script that has underwent `unix2dos`, and that the hashbang interpreter is outside our control – it is what invokes fish in the first place.

Example:

    #!/usr/bin/env fish

Result:

    /usr/bin/env: ‘fish\r’: No such file or directory

**Comment by mqudsi** [comment]
Given the broken hashbangs, there's not much fish can do here.
