### ISSUE TITLE
Alt-left and alt-right word left-right not working

### ISSUE THREAD

**Issue by rocketraman** [fish-shell/fish-shell#3656]
- [ ] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [X] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version 2.3.1

**OS/terminal used**: 
Konsole

```
~ echo $TERM
xterm-256color
```

Talk about the the issue here. 

The alt-left and alt-right key bindings to move a word left and right are not working. Output of `fish_key_reader` for `alt-left` and `alt-right` respectively:

```
~ fish_key_reader 
Press a key

              hex:   1B  char: \c[  (or \e)
(  0.175 ms)  hex:   5B  char: [
(  0.151 ms)  hex:   44  char: D
bind \e\[D 'do something'
~ fish_key_reader 
Press a key

              hex:   1B  char: \c[  (or \e)
(  0.111 ms)  hex:   5B  char: [
(  0.082 ms)  hex:   43  char: C
bind \e\[C 'do something'
```

**Comment by krader1961** [comment]
Something is wrong with your terminal. Normally when people talk about [alt-some_other_key] or [meta-some_other_key] they mean that the normal sequence sent by "some_other_key" will be sent but prefixed by `\e` (escape). The data you provided shows that we're just receiving the normal sequence for the [left] and [right] arrow keys. There should either be a second `\e` or an entirely different escape sequence.

It's possible, even likely, that Konsole by default uses the [alt] key to compose non-ASCII characters. If it's like iTerm2 there should be a way to configure it to treat the [alt] key as I described above.

**Comment by krader1961** [comment]
Also, note that fish already has the bindings you expect. From *__fish_shared_key_bindings.fish*:

```
    bind $argv \e\e\[C nextd-or-forward-word
    bind $argv \e\e\[D prevd-or-backward-word
```

You just need to configure your terminal to treat the [alt] key like a meta key in the sense the Emacs editor uses the term (which is where the idea originated).

**Comment by faho** [comment]
@rocketraman: This works for me, in konsole 16.08.3, though mine sends a different sequence - `\e[1;3D` for alt-left.

Konsole actually has configurable sequences. Can you check that the keyboard setting for the current profile is the default - "XFree 4", and not "Linux-Console" or "Solaris-Console"?

**Comment by rocketraman** [comment]
> Konsole actually has configurable sequences. Can you check that the keyboard setting for the current profile is the default - "XFree 4", and not "Linux-Console" or "Solaris-Console"?

Indeed, my Konsole was set to "Linux Console", which apparently I changed it too at some distant point in the past. Switching it back to "XFree 4" fixes the issue. Thanks!

**Comment by fent** [comment]
was having this issue with the cathode terminal, after turning off the option "Option is meta" it's fixed

![image](https://user-images.githubusercontent.com/933490/69444511-7fa63380-0d1e-11ea-8838-ead4d4844f29.png)
