### ISSUE TITLE
why does `writestr()` exist?

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3657]
While working on issue #3497 I noticed that the code I was touching called `writestr()`. AFAICT there is no need for that function. It is used in a handful of places in *src/reader.cpp* and one place in *src/screen.cpp*. It doesn't do anything that a simple `fwprintf()` wouldn't do AFAICT. If there is some reason it is needed its docstring should explain why it is needed. I strongly suspect it served a purpose in the distant past but no longer does so and can be removed. I need to look at the change history to see if I can figure out what that purpose might have been.

@ridiculousfish, or anyone else, do you have any idea why that function exists?

**Comment by radomirbosak** [comment]
The oldest mention of `writestr` I found is in the oldest commit in history: 149594f974350bb364a76c73b91b1d5ffddaa1fa .

It was in the file `output.c` back then and moved twice to different files.

This was its definition:
```c
...
/**
   Write a wide character string to FD 1.
*/
void writestr( const wchar_t *str )
{
	while( *str != 0 )
		writech( *(str++) );
}
```

`writech` was used in around 6 functions in `reader.c`, `output.c` and `fish_pager`.
```c
...
/**
   Write a wide character to fd 1.
*/
int writech( wint_t ch )
{
	static mbstate_t out_state;
	char buff[MB_CUR_MAX];
	size_t bytes = wcrtomb( buff, ch, &out_state );
	int err;
	
	while( (err =write( 1, buff, bytes ) ) )
	{
		if( err >= 0 )
			break;
		
		if( errno == EINTR )
			continue;
		
		wperror( L"write" );
		return 1;
	}
	
	return 0;
}
...
```

**Comment by krader1961** [comment]
There is only one legitimate use of `writestr()` and that is in *src/screen.cpp*. The ones in *src/reader.cpp* are incorrect; or at least not needed. This confusion about `writech()` and `writestr()` exists because of the ENCODE_DIRECT_BASE mechanism. Which itself appears to be used incorrectly in several places in the code. Clearly supporting non-ASCII (or at least non-ISO-8601) locales is hard ☹️
