### ISSUE TITLE
Starting a line with '%' will output an error

### ISSUE THREAD

**Issue by terlar** [fish-shell/fish-shell#366]
If you enter the character `%` in your terminal it will yeild the following error.

```
➤ Warning: find_process called off of main thread. Break on debug_thread_error to debug.
➤ %
```

This occurred in both OSX 10.8.2 and Ubuntu 12.04.1

**Comment by Ryan-Factual** [comment]
I encounter this problems too.
My OS is OSX 10.10.1, I also encounter it in 10.9.x
My fish version is 2.1.1

Could you help me about this?

**Comment by zanchey** [comment]
@Ryan-Factual, can you confirm that when you start `fish` and type just a `%` that you get the error message listed above? If not, it would be worth opening a new issue.

**Comment by Ryan-Factual** [comment]
Thanks! @zanchey 
when I type `cd %`, `ls ^%`, `COMMAND ^%` , I will get the error. 
but these case will not: `%something`, `ls %`.

**Comment by bucaran** [comment]
@zanchey Correct. The error occurs when typing `cd %` or `ls ^%`, etc. Typing just a `%` causes no problems.

![err](https://cloud.githubusercontent.com/assets/8317250/5717432/24e28d1e-9b44-11e4-9935-0cb561da75ea.gif)

**Comment by zanchey** [comment]
Right, got it. I can also reproduce these in 2.1.1 but they are fixed in the current git master builds (e.g. 2.1.1-1176-g6e2132e) so they will be ok in the next release.

**Comment by Ryan-Factual** [comment]
@zanchey Thanks!
when is the next release?

**Comment by ridiculousfish** [comment]
It's way overdue.  My fault!
