### ISSUE TITLE
completion for `bzr` command has duplicate entries

### ISSUE THREAD

**Issue by radomirbosak** [fish-shell/fish-shell#3661]
It seems that completion for `bzr` introduced in commit 3a94f6e8b368c731132a0cf781a4b9cacbf69e30 and located in `share/completions/bzr.fish` has been generated automatically:
```
#
# Command specific completions for the bzr command.
# These completions were generated from the commands
# man page by the make_completions.py script, but may
# have been hand edited since.
#
...
```
Many of its long options are specified multiple times. Upon looking at the bzr manpage, the `bzr` command has a lot of subcommands, which the completion generator probably ignores.

```console
$ grep "\-l help" share/completions/bzr.fish
complete -c bzr -l help -s h --description 'Show help message'
complete -c bzr -l help -s h --description 'Show help message'
...
complete -c bzr -l help -s h --description 'Show help message'

$ grep "\-l help" share/completions/bzr.fish | wc -l
67
```

**Comment by faho** [comment]
Personally, I don't think these completions are all that useful. We should either enhance them to the point that they at least suggest the most common subcommands (and maybe arguments to those subcommands, which is always the most interesting part), or remove them.

Is there actually much improvement over what the generator outputs?

I've never used bzr and am not interested in learning another vcs, so a PR by a bzr user would be much appreciated.

**Comment by cprieto** [comment]
I am giving a try to this one.
