### ISSUE TITLE
Remove useless completions

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#3662]
While reading #3661, it occured to me that we have a bunch of completions that are either too small to be useful, or that are for a dead application. We should remove them.

The former is something like `mc`, where the shipped completions are basically equivalent to what the generator creates, so there's not much use keeping them around. 

The latter is something like `dcop`, which was used with KDE3. I can't find a package for it in debian oldstable, so I'm assuming it's dead.

I'm running a script now to check what completions refer to commands that aren't in the arch repositories, that should be a good first pass.

**Comment by faho** [comment]
Okay, the results are in:

- anamnesis - Clipboard manager, last update 2013.
- arc - Needs comment saying it's for arcanist, not the archiver by that name.
- composer.phar - is that ".phar" really a thing?
- dcop
- djview3 - Transition package to djview4 even in debian oldstable
- effectv - Is it https://github.com/Elive/effectv? The last effective update was in 2013.
- elatex - All these TeX things are ungoogleable - is this still a thing?
- lppasswd - Presumably a cups thing, can't find it.
- meat - A dead archlinux "AUR helper". Last commit 2013.
- omega - Yet another TeX wrapper thing.
- pdfelatex - I only know of "pdflatex" without the "e".
- pftp - Some kind of ftp thing?
- prt-get - Could possibly be a Crux Linux package management tool. Script contains completions also for "prt-cache" that would have to be moved out.
- rgrep - Is this a thing?
- update-eix-remote - I can only find stuff for "eix-update".
- update-eix - Ditto.
- vim-addons - I can only find "vim-addon-manager", and that doesn't seem to have a CLI tool.

**Comment by zanchey** [comment]
> elatex - All these TeX things are ungoogleable - is this still a thing?

We have `xelatex` but not `elatex`.

> lppasswd - Presumably a cups thing, can't find it.

Yep - in the Debian package cups-client.

> rgrep - Is this a thing?

From the GNU grep manpage: "`rgrep` is the same as `grep -r`".

**Comment by radomirbosak** [comment]
`pftp` is `ftp -p` (ftp with passive mode on). It's installed as part of `ftp` package (at least in fedora).

**Comment by faho** [comment]
Okay, so here's what I'd like to remove for now:

- anamnesis

- dcop

- djview3

- effectv

- meat

As you might recognize, that's the list of projects that I've found to be _dead_ for a couple of years. The stuff I didn't find can stay for now.

I'll do this after 2.5.0, so users who need any of these can pick them up from that release.

**Comment by zanchey** [comment]
@faho do you want to give this a shot now?
