### ISSUE TITLE
fish snap package

### ISSUE THREAD

**Issue by thibran** [fish-shell/fish-shell#3664]
It would be nice if fish would be released as [snap package](http://snapcraft.io/docs) too. Snap packages are confined and can be installed on a number of Linux distributions (Ubuntu, Arch, Debian, Gentoo, Fedora, Suse..). If you are interested I could start working on a snap, but would probably need some help.

**Comment by faho** [comment]
I've taken a look at this, but I don't think a "confined" or "sandboxed" shell is all that useful.

**Comment by thibran** [comment]
A confined shell would be for sure less capable. Canonical is moving Ubuntu into a fully confined future (desktop, phone, and server with Snappy Ubuntu Core). The open question is, how much could be done with a confined shell. If the user has access to his home folder, the installed default binaries like wget, rsync... and other command-line snaps it might be good enough.

Snap packages are currently still in development, maybe for a shell to be packed as snap and be useful there need to be some new [interfaces](http://snapcraft.io/docs/reference/interfaces) or new snap-plugs. Without trying we never know, it's about starting and figure out on the way whats needed.

**Comment by krader1961** [comment]
Frankly, @thibran, unless someone like yourself who is motivated to make the necessary changes this will never happen.

**Comment by mqudsi** [comment]
I'm closing this due to lack of interest, @thibran or anyone else: please feel free to comment back if there's any change here. IMHO it doesn't look like snap has gone anywhere, and perhaps this is best left to the snap community rather than being an official fish release at this time.

**Comment by thibran** [comment]
I took the time and created an initial snap package which can be found [here](https://github.com/thibran/fish-shell-snap). It works – tested on Ubuntu 16.04 LTS and Ubuntu 17.10 – and tracks the fish master branch. Right now the snap is **not** published, I just created the snap build file.

It is usual that snaps have an icon, I took the one from the fish website and augmented it with a [dark blue background](https://github.com/thibran/fish-shell-snap/blob/master/snap/fish_logo.png). Hope this is okay, if not, I remove/replace it with an official one from you.

I need some feedback and testing if all is right. Then the package could be submitted to the [snap build and publish service](https://build.snapcraft.io/), which is super easy to configure and use. Right now the snap build file is in a separate repository, which is fine – if snap is useful to you, it could be added to the fish repo.

The other open question would be, who should be the owner of the snap in the snap-store and how should the package be named. The snap is build like it is recommended for third-party developers, e.g. the snap has a suffix `-thibran`, but if I would get the official blessing, I could change the package name to just `fish`.

**Comment by mqudsi** [comment]
cc @zanchey @ridiculous_fish

**Comment by tim-sueberkrueb** [comment]
@thibran thank you! I tested it on Ubuntu 17.10. I have chips installed and I get this warning when starting it:
```
$ fish-thibran.fish 
~/.config/fish/config.fish (line 4): The file '.' is not executable by this user
if [ -e ~/.config/chips/build.fish ] ; . ~/.config/chips/build.fish ; end
                                       ^
from sourcing file ~/.config/fish/config.fish
	called during startup
```
Besides of that, it seems to work just fine for me so far.
Maybe you could create a post in [the Snapcraft Forum](https://forum.snapcraft.io/) to get more people to test the snap.

**Comment by thibran** [comment]
@tim-sueberkrueb [It seems like](https://superuser.com/a/84624/222677) newer versions of fish no longer support `.` to source files. So if I'm right, it's because you use an up-to-date fish-shell now :smile: 

Asking the Snapcraft forum for feedback is a good idea, but first I wait to get some answer here about how the snap package should move on.
