### ISSUE TITLE
make it harder to add file names to the project that are identical other than letter case

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3667]
We recently had an incident where a PR was merged which caused problems for people working with this project on macOS/OS X and MS Windows but not Linux. The problem was the PR included a completion script whose name was mixed case. It included another script with the same name in all lowercase. For example, *share/completions/AbcDef.fish* and *share/completions/abcdef.fish*. This is fine on traditional UNIX implementations since the two files are distinct. However, it causes problems on systems that preserve file name letter case when creating a file while otherwise ignoring letter case since the two files are no longer distinct.

A lot of googling surprisingly turned up very few relevant articles. The most relevant result was https://github.com/pre-commit/pre-commit-hooks which includes the *check_case_conflict.py* hook we need. However, it in turn depends on https://github.com/pre-commit/pre-commit which I'm not interested, at this time, in adding as a dependency. We might want to add that complexity in the future but for now I'm going to simply integrate the one check we need.

**Comment by krader1961** [comment]
While I love Git it appears the enforcing a pre-commit check to preclude two path names that are identical other than letter case is impossible. See, for example, http://stackoverflow.com/questions/3703159/git-remote-shared-pre-commit-hook/3703207

Attempting to `git add .git/hooks/pre-commit` fails with this output:

```
error: Invalid path '.git/hooks/pre-commit'
error: unable to add .git/hooks/pre-commit to index
fatal: adding files failed
```

If someone with more knowledge of Git can implement this check that would be very useful. However, I've already spent two hours looking into this and can't find a way to make it work so I'm going to disengage.

**Comment by zanchey** [comment]
Seems like a feature GitHub would be well-suited to implementing as part of protected branches.

**Comment by krader1961** [comment]
FWIW I created a support request with the subject "feature req: disallow merging if two file names differ in letter case" and this body:

> Like many git projects some of our contributors work on systems, like macOS and MS Windows, where letter case is preserved in path names but ignored when deciding if a path is already present. The https://github.com/fish-shell/fish-shell project recently had an incident where a contributed created a commit with two files whose names were identical other than letter case which caused some pain for several of the core developers (see https://github.com/fish-shell/fish-shell/issues/3667). It would be helpful if enabling protected branches either disallowed such commits from being merged by default, or there was a sub-option to enable such protection.

**Comment by krader1961** [comment]
Meh! After reading about git hooks in the book "Version Control with Git: Powerful tools and techniques for collaborative software development" I've concluded that implementing this is more bother than it's worth. We'll just have to be more attentive in the future when reviewing a change from a third party.
