### ISSUE TITLE
Remove check_running_fishd and  socket-handling code

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#3669]
fish has some code to detect old versions of fish (that used fishd to implement universal variables), rooted at `check_running_fishd()` and including `try_connect_socket()`.

In #3317 we saw this code emit a warning on Haiku. This fishd check has done its job and we can very likely remove it.

**Comment by faho** [comment]
fishd was removed with 2.2.0, according to our CHANGELOG.md.

That version was released 2015-07-12, so almost 1.5 years ago.

My questions are:

- What exactly happens without this code? Are there large (i.e. not solved by rebooting) issues upgrading from <2.2.0 to after the removal?

- If there are, are there any longer-term-support distributions we would like to support? I know the current Debian stable doesn't include fish at all, oldstable has 1.23.1.

- If there are, do we expect them to carry a patch when version N has an old enough fish and N+1 gets a fish with this removed?

**Comment by ridiculousfish** [comment]
Great questions!

The code's purpose is to print the "Old versions of fish appear to be running...restart all running instances of fish." message. It doesn't do anything beyond print the message.

The issue is that changes to universal variables may not propagate between < 2.2.0 and 2.2.0+. The solution is to end the <2.2.0 sessions. Rebooting, `killall fish`, etc will do it. I think this a reasonable path for an upgrade script on a LTS distro, or just do nothing since the consequences are relatively mild.

Beyond that, this check has caused this Haiku issue and some headaches on Cygwin (#2152) so I think it's causing more problems than it's solving.

**Comment by faho** [comment]
>I think this a reasonable path for an upgrade script on a LTS distro, or just do nothing since the consequences are relatively mild.

Yes. Especially considering upgrading from one distro version to the next will already require a reboot.

So: Kill it, please. Of course mentioning that old instances should still be killed in the release notes seems to be prudent.
