### ISSUE TITLE
Fish cannot update the completions database on Haiku

### ISSUE THREAD

**Issue by miqlas** [fish-shell/fish-shell#3671]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version unknown
it is 2.4.0 with Haiku specific patches, not in mainline yet.

**OS/terminal used**: 
Haiku hrev 50762 x86_64, Terminal

Fish should be packaged for Haiku. The packaging happens in chrooted environment, so fish cannot generate the completions database during the compiling process.
After installing the package it cannot update the database because this:

> ~ ❯❯❯ fish_update_completions 
> Traceback (most recent call last):
>   File "/packages/fish-2.4.0-2/.self/data/fish/tools/create_manpage_completions.py", line 929, in <module>
>     file_paths.extend(get_paths_from_manpath())
>   File "/packages/fish-2.4.0-2/.self/data/fish/tools/create_manpage_completions.py", line 860, in get_paths_from_manpath
>     proc = subprocess.Popen(['manpath'], stdout=subprocess.PIPE)
>   File "/packages/python-2.7.12-1/.self/lib/python2.7/subprocess.py", line 711, in __init__
>     errread, errwrite)
>   File "/packages/python-2.7.12-1/.self/lib/python2.7/subprocess.py", line 1343, in _execute_child
>     raise child_exception
> OSError: [Errno -2147459069] No such file or directory

I see the following if i run fish like fish -d5 -D5:
`<4> fish: Exec job 'python -B $__fish_datadir/tools/create_manpage_completions.py --manpath --progress --cleanup-in '~/.config/fish/completions' --cleanup-in '~/.config/fish/generated_completions'' with id 2`

Currently installed Python versions:
 2.7.12 and 3.5.2

## Reproduction steps
1. install Fish on Haiku (with HaikuPorter)
2. try to update the completions with `fish_update_completions`
3. No profit :(

## Results
```console
~ $ math 2 + 2
4
```

**Comment by ridiculousfish** [comment]
This is dying on a call to `manpath`, which is not present. Dumb question: does Haiku have manpages? If so, how is the path to them discovered?

**Comment by miqlas** [comment]
Of course we have! :) They live in `/boot/system/documentation/man` folder.

HaikuPorter using the runConfigure procedure for passing the args to the auto* based configure scripts automatically.

See here: https://github.com/haikuports/haikuports/blob/master/app-shells/fish/fish-2.4.0.recipe#L62
and here: https://github.com/haikuports/haikuporter/blob/71a83f90aa1edcd682d06f7e40dbe42858eb49c9/HaikuPorter/Port.py#L1098

**Comment by miqlas** [comment]
Haikuporter calls the configure script (according to the configure.log):

>   $ ./configure --docdir=/packages/fish-2.4.0-2/.self/documentation/packages/fish --libexecdir=/packages/fish-2.4.0-2/.self/lib --datarootdir=/packages/fish-2.4.0-2/.self/data --infodir=/packages/fish-2.4.0-2/.self/documentation/info --localstatedir=/packages/fish-2.4.0-2/.self/var --libdir=/packages/fish-2.4.0-2/.self/lib --datadir=/packages/fish-2.4.0-2/.self/data --prefix=/packages/fish-2.4.0-2/.self --includedir=/packages/fish-2.4.0-2/.self/develop/headers --sysconfdir=/packages/fish-2.4.0-2/.settings --sharedstatedir=/packages/fish-2.4.0-2/.self/var --sbindir=/packages/fish-2.4.0-2/.self/bin --mandir=/packages/fish-2.4.0-2/.self/documentation/man --bindir=/packages/fish-2.4.0-2/.self/bin --oldincludedir=/packages/fish-2.4.0-2/.self/develop/headers --build=x86_64-unknown-haiku --without-included-pcre2

**Comment by miqlas** [comment]
However i see this during the build process:

> fish is now configured.
>   FISH_BUILD_VERSION = 'unknown'
>   CXX = 'g++'
>   CXXFLAGS = '-D_BSD_SOURCE -fno-exceptions -Wextra -I/packages/libpcre2-10.22-1/.self/develop/headers '
>   MKDIR_P = '/bin/mkdir -p'
>   prefix = '/packages/fish-2.4.0-2/.self'
>   sysconfdir = '/packages/fish-2.4.0-2/.settings'
>   docdir = '/packages/fish-2.4.0-2/.self/documentation/packages/fish'
>   extra_completionsdir = '/packages/fish-2.4.0-2/.self/data/fish/vendor_completions.d'
>   extra_functionsdir = '/packages/fish-2.4.0-2/.self/data/fish/vendor_functions.d'
>   extra_confdir = '/packages/fish-2.4.0-2/.self/data/fish/vendor_conf.d'
>   SED      fish.pc
>   SED      share/__fish_build_paths.fish
> Collecting files to be packaged ...
>   FISH_BUILD_VERSION = 'unknown'
>   CXX = 'g++'
>   CXXFLAGS = '-D_BSD_SOURCE -fno-exceptions -Wextra -I/packages/libpcre2-10.22-1/.self/develop/headers '
>   MKDIR_P = '/bin/mkdir -p'
>   prefix = '/packages/fish-2.4.0-2/.self'
>   sysconfdir = '/packages/fish-2.4.0-2/.settings'
>   docdir = '/packages/fish-2.4.0-2/.self/documentation/packages/fish'
>   extra_completionsdir = '/packages/fish-2.4.0-2/.self/data/fish/vendor_completions.d'
>   extra_functionsdir = '/packages/fish-2.4.0-2/.self/data/fish/vendor_functions.d'
>   extra_confdir = '/packages/fish-2.4.0-2/.self/data/fish/vendor_conf.d'
> fish has now been built.
> Run make install to install fish.
>   HAVE_GETTEXT = '1'
> Installing translations...
>   datadir = '/packages/fish-2.4.0-2/.self/data'
>   mandir = '/packages/fish-2.4.0-2/.self/documentation/man'
>  Installing fish
>  Installing fish_indent
>  Installing fish_key_reader
> Creating sysconfdir tree
> Creating datadir tree
> Creating placeholder vendor/'extra_' directories
> Installing pkgconfig file
> Installing the fish completion library...
> Installing fish functions
> Installing man pages
> Installing helper tools
> Installing online user documentation
> Installing more man pages
> /bin/install: cannot stat 'share/man/man1/fish.1': No such file or directory
> /bin/install: cannot stat 'share/man/man1/fish_indent.1': No such file or directory
> /bin/install: cannot stat 'share/man/man1/fish_key_reader.1': No such file or directory
> Checking for legacy binaries...

**Comment by miqlas** [comment]
The "Not such file or directory" comes from the Makefile:

# Manual pages to install
#
MANUALS := $(addsuffix .1, $(addprefix share/man/man1/, $(PROGRAMS)))

There is no man dir in the source tree.

**Comment by faho** [comment]
>There is no man dir in the source tree.

@miqlas: It's generated - the "doc" make target should build it, which requires `doxygen`. If you don't have that, we won't build the documentation, so neither `help` nor `--help` nor `man` will work for fish's pages.

Anyway, that's probably a different issue.

Do you have a `manpath` tool in $PATH? The python script that generates completions from makefiles calls that to find the man pages.

**Comment by miqlas** [comment]
@faho: ok, clear now. there is doxygen port for haiku, but i disabled it, because it is optional dependency.
About manpath: there is no manpath in Haiku and there is no port for that command, but technically it is the same as 'man --path', right?

**Comment by faho** [comment]
> there is doxygen port for haiku, but i disabled it, because it is optional dependency.

You probably want it. Like I said, without it there's no fish documentation.

>About manpath: there is no manpath in Haiku and there is no port for that command, but technically it is the same as 'man --path', right?

On `man`s that support it, yes. From my research, "man-db"'s has both, FreeBSD's has only `manpath`, OpenBSD has _neither_ (so I believe we'll also fail there).

We could of course try this approach:

- Check `manpath` (since it's the most supported)

- Check `man --path` (for Haiku and potentially other systems)

- Fall back to a default ("/usr/share/man"?)

**Comment by miqlas** [comment]
faho: there is a port in our package repository, but it is just too old (1.6.3), while fish require minimum 1.8.7 (according to configure.ac). While we have recipe for 1.8.10, there is no package for that, so if somebody want to reproduce my results, needs to compile it too if i enable it.

I just tested it for you in bash (it seems, fish have a man.fish function):
> bash-4.4# man --path
> /boot/system/documentation/man/hu:/boot/system/documentation/man
> bash-4.4#

**Comment by faho** [comment]
@miqlas: This is essentially another side of #2194 - we don't try enough ways to get $MANPATH.

As I've commented there, can you test [my manpath branch](https://github.com/faho/fish-shell/tree/manpath)?

**Comment by miqlas** [comment]
I'll do it and report back, thanks!

**Comment by miqlas** [comment]
@faho : just tested your branch: it works nicely on Haiku. Can't wait to see your changes in the mainline!

**Comment by miqlas** [comment]
Actually we can close this with #2194 , right?

**Comment by faho** [comment]
Yes, this can be closed.
