### ISSUE TITLE
on macOS after 'cd /Volumes/DRIVE', ls behaves weird

### ISSUE THREAD

**Issue by gyakovlev** [fish-shell/fish-shell#3680]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version 2.4.0, installed from homebrew
**OS/terminal used**: 
macOS 10.12.2 / iTerm 3.0.13

In iTerm if I go to /Volumes/DRIVE directory and issue an ls command it does not show files occasionally. The drive has to be FAT32 one. Maybe NTFS, have no tools to create NTFS filesystem right now.

## Reproduction steps
1. Insert a FAT32/mbr formatted flash drive into computer, with some files/folders in the root of the drive.
2. cd /Volumes/DRIVE
3. ls
4. ls -F <---breaks here
5. running ls /Volumes/DRIVE works

sometimes it breaks for running just ls, or running /bin/ls with options.
the most reliable way to get the bug is to try and run ```ls -F``` while in a fat32 mounted drive root directory.
I tried to capture different breakages in the following screenshot and screencast.
I rely on ```ls -F``` sometimes, with my vision colored directories is not enough sometimes, so I like those extra slashes.

<img width="1136" alt="screen shot 2016-12-26 at 10 32 30 pm" src="https://cloud.githubusercontent.com/assets/168902/21492875/fc27811c-cbbc-11e6-96ab-d15037be4f6d.png">

[![asciicast](https://asciinema.org/a/8x9v1oc85w39juclemwf88j33.png)](https://asciinema.org/a/8x9v1oc85w39juclemwf88j33)
Reproducible  iTerm and Terminal.app with a FAT32 formatted USB drive. 
Works ok in bash, Works fine with my HFS+ encrypted time machine usb disk.

That has to be something with FAT32.

## Disk info
```console
ya@geo ~> diskutil list disk4
/dev/disk4 (external, physical):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:     FDisk_partition_scheme                        *4.1 GB     disk4
   1:                 DOS_FAT_32 4GB                     4.1 GB     disk4s1
ya@geo ~> mount -t msdos
/dev/disk4s1 on /Volumes/4GB (msdos, local, nodev, nosuid, noowners)

```

**Comment by ridiculousfish** [comment]
Googling turns up [this discussion](https://github.com/robbyrussell/oh-my-zsh/issues/4161#issuecomment-153442082) which suggests this has something to do with code that sets the title of the window. Also see [iTerm2 bug](https://gitlab.com/gnachman/iterm2/issues/3686) which suggests it's due to the OS filesystem driver. I think there's nothing fish can or should do about this.

**Comment by gyakovlev** [comment]
Hey, thanks for explanation. I googled first with no results, but realized it's related to fat32 while writing the report and did not re-google it =)
Definitely it's that mentioned bug with OSX. I'll close the issue then.
