### ISSUE TITLE
Fish fails to set the terminal title

### ISSUE THREAD

**Issue by jusga** [fish-shell/fish-shell#3686]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)? -> it doesn't
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed**:
01dbfb0a3f62c5a2765fbed481e17752191ac755

**OS/terminal used**: 
Arch Linux, Xfce4-Terminal

## Reproduction steps
1. Configure Xfce4-Terminal as follows:
Preferences -> General -> Title
Dynamically-set title: Replaces initial title
2. Run `fish` in the terminal.

## Results
Observe that the terminal title is "Untitled", not "fish /home/$USER" as expected.

## Comments

This was introduced in 01dbfb0a3f62c5a2765fbed481e17752191ac755 by @krader1961, the previous commit works fine.

I see the same behaviour with Lilyterm,  `urxvt` and `st`.

**Comment by jusga** [comment]
The following patch fixes my issue, but I don't see why, so I didn't open a PR.

```diff
diff --git a/src/reader.cpp b/src/reader.cpp
index 6c867c2..bb0bbf9 100644
--- a/src/reader.cpp
+++ b/src/reader.cpp
@@ -698,17 +698,17 @@ void reader_write_title(const wcstring &cmd, bool reset_cursor_position) {
     proc_push_interactive(0);
     if (exec_subshell(fish_title_command, lst, false /* ignore exit status */) != -1 &&
         !lst.empty()) {
-        fputs("\e]0;", stdout);
+        fputws(L"\e]0;", stdout);
         for (size_t i = 0; i < lst.size(); i++) {
             fputws(lst.at(i).c_str(), stdout);
         }
-        fputc('\a', stdout);
+        fputwc(L'\a', stdout);
     }
     proc_pop_interactive();
     set_color(rgb_color_t::reset(), rgb_color_t::reset());
     if (reset_cursor_position && !lst.empty()) {
         // Put the cursor back at the beginning of the line (issue #2453).
-        fputc('\r', stdout);
+        fputwc(L'\r', stdout);
     }
 }

 ```

**Comment by krader1961** [comment]
Gah! Stupid standards: http://pubs.opengroup.org/onlinepubs/007904975/functions/xsh_chap02_05.html

BSD (specifically, macOS) does the right thing and allow you to mix wide and narrow stdio functions. However, the aforementioned standard allows implementations, like GNU libc, to prohibit wide functions if the first I/O to the stream was done with a narrow function.
