### ISSUE TITLE
Use XDG_DATA_HOME for extensibility

### ISSUE THREAD

**Issue by daleeidd** [fish-shell/fish-shell#3688]
Currently both OMF and Fisherman place functions from packages installed by their respective CLIs in `$XDG_CONFIG_HOME/fish/functions`. This is due to the aforementioned directory being where functions are loaded from. I don't believe this conforms to XDG standards as users shouldn't be committing installed files into their repository. This directory should be purely for functions the user writes.

I propose that fish also looks in `$XDG_DATA_HOME/fish/functions` for plugin managers to use.

**Comment by faho** [comment]
We don't define anything here, it's up to OMF/Fisherman where they put their stuff, and they can then extend $fish_function_path as they please, either by asking the user to extend config.fish or by adding a file in conf.d. I fail to see what more is needed.

Note that, while we are open to add hooks so you can add customization, we don't support OMF or Fisherman (or tacklebox or any of the other plugin manager things I've forgotten about) - for that you'll have to talk to the maintainers of whatever it is you are using.

I'm closing this for now. If you have a concrete request for what should be changed _in fish_, we can reopen or open another issue. If any plugin manager people are reading: If you have any requests or questions, feel free to ask!

**Comment by daleeidd** [comment]
My apologies. I missed `$fish_function_path` in the documentation. Thanks.
