### ISSUE TITLE
Support fish_vi_cursor on iTerm2

### ISSUE THREAD

**Issue by nhooyr** [fish-shell/fish-shell#3696]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: latest master, more specifically, https://github.com/fish-shell/fish-shell/commit/89e48ba0b3b2ff0f254443117483814402f8f6cd

**OS/terminal used**: macOS 10.12.2 and iTerm 3.0.13

Watch: https://asciinema.org/a/152yxzpdz3m9igtqz8q5ags4x

**Comment by nhooyr** [comment]
manually executing `__fish_cursor_1337` works fine and changes the cursor mode.

**Comment by faho** [comment]
Yes. The issue here is our detection uses `tput Ss`, and that particular definition isn't included in the macOS "xterm" terminfo.

I've got a fix in the pipeline but it needs a whole bunch more testing - this stuff is _gnarly_.

**Comment by nhooyr** [comment]
works!

**Comment by nhooyr** [comment]
@faho though now I am getting #3481

**Comment by nhooyr** [comment]
Except, I noticed that pressing `A` (move to the end of the line and enter insert mode from normal mode) also reproduces the bug.

**Comment by nhooyr** [comment]
@faho and the cursor should begin blinking when entering insert mode. it doesn't do that

**Comment by faho** [comment]
>the cursor should begin blinking when entering insert mode. it doesn't do that

@nhooyr: We don't have blinking enabled anywhere currently. IIRC it's a different argument to the sequence (e.g. 3 instead of 2 for blinking line and 5 instead of 4 for blinking block or something like that).

**Comment by faho** [comment]
Oh no, sorry. The xterm sequence supports blink, our iTerm and konsole functions (the sequences are nearly the same) currently don't. I'd have to look up what they use.

**Comment by faho** [comment]
I actually can't find documentation on this - the [iterm proprietary escapes list](https://iterm2.com/documentation-escape-codes.html) doesn't have anything on it, and I can't find documentations for konsole. So it seems that these terminals don't actually support this.

Anyway, that's a different issue. This one is about us not changing the cursor in iTerm, which is currently blocking on #3481.

**Comment by tbodt** [comment]
Will this be fixed anytime soon?

**Comment by ridiculousfish** [comment]
Doesn't seem like anyone is actively working on it.

**Comment by faho** [comment]
Okay, I've cleaned up the cursor detection, but as it turns out the issue on iTerm is really frickin' weird, so I've disabled it explicitly and added a "--force-iterm" flag, so you can run `fish_vi_cursor --force-iterm`.

**Comment by nhooyr** [comment]
@faho is it fixable in fish or should a bug be filled with iTerm instead?

**Comment by faho** [comment]
@nhooyr Sure, if someone with access to iTerm fixes #3481. That won't be me tho, as I don't have access to iTerm and this entire thing is weird enough that it really needs to be tested first hand.

**Comment by zanchey** [comment]
Should that flag be in the documentation? `fish_vi_cursor` does not have a manpage, only a cursory reference in the main manual.

**Comment by nicu-chiciuc** [comment]
@faho For almost half a year now I've been using this approach:
```
function fish_mode_prompt --description 'Displays the current mode'
    switch $fish_bind_mode
        case default
            set_color --bold --background red white
            printf '\e]50;CursorShape=0\x7'
            # echo '[N]'
        case insert
            set_color --bold --background green white
            printf '\e]50;CursorShape=1\x7'
            # echo '[I]'
        case replace_one
            set_color --bold --background green white
            printf '\e]50;CursorShape=2\x7'
            # echo '[R]'
        case visual
            set_color --bold --background magenta white
            # echo '[V]'
    end

    set_color normal
end
```
I think you mentioned in another thread that using `fish_mode_prompt` for such purposes is not a good idea but alas it worked pretty well. I've tried the `--force-iterm` approach and it seems to work although there are some problems. Specifically, when pressing ESC to exit from insert mode, a newline is inserted and I get several empty lines, as seen in the screen shot below. Also sometimes the cursor stay in normal mode even though fish is in insert mode.
![Screen Shot 2020-10-22 at 20 29 09](https://user-images.githubusercontent.com/4076804/96908399-42ee3980-14a5-11eb-8339-4684e1f3c0b9.png)

The approach with amending the `fish_mode_prompt` worked good enough until I tried to use tmux.

I don't know too much about the codebase of `fish` yet I'm pretty willing to help if needed. It seems that if `ITERM_PROFILE` is set the `__fish_cursor_1337.fish` is used. I was wondering if it would make sense to create a new `__fish_cursor_iterm.fish` function that would work just for iterm?

**Comment by FraserEmbrey** [comment]
> @faho For almost half a year now I've been using this approach:
> 
> ```
> function fish_mode_prompt --description 'Displays the current mode'
>     switch $fish_bind_mode
>         case default
>             set_color --bold --background red white
>             printf '\e]50;CursorShape=0\x7'
>             # echo '[N]'
>         case insert
>             set_color --bold --background green white
>             printf '\e]50;CursorShape=1\x7'
>             # echo '[I]'
>         case replace_one
>             set_color --bold --background green white
>             printf '\e]50;CursorShape=2\x7'
>             # echo '[R]'
>         case visual
>             set_color --bold --background magenta white
>             # echo '[V]'
>     end
> 
>     set_color normal
> end
> ```
> 
> I think you mentioned in another thread that using `fish_mode_prompt` for such purposes is not a good idea but alas it worked pretty well. I've tried the `--force-iterm` approach and it seems to work although there are some problems. Specifically, when pressing ESC to exit from insert mode, a newline is inserted and I get several empty lines, as seen in the screen shot below. Also sometimes the cursor stay in normal mode even though fish is in insert mode.
> ![Screen Shot 2020-10-22 at 20 29 09](https://user-images.githubusercontent.com/4076804/96908399-42ee3980-14a5-11eb-8339-4684e1f3c0b9.png)
> 
> The approach with amending the `fish_mode_prompt` worked good enough until I tried to use tmux.
> 
> I don't know too much about the codebase of `fish` yet I'm pretty willing to help if needed. It seems that if `ITERM_PROFILE` is set the `__fish_cursor_1337.fish` is used. I was wondering if it would make sense to create a new `__fish_cursor_iterm.fish` function that would work just for iterm?

Thanks fo this, I feel like it used to work at some point…I wish this would just work properly by default.

**Comment by ridiculousfish** [comment]
This seems to be working for me with b41c0869842210ffea571246389513fff6a4a084. I'd appreciate any testing.
