### ISSUE TITLE
complete: wrapping a command does not wrap -f option

### ISSUE THREAD

**Issue by nhooyr** [fish-shell/fish-shell#3700]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.4.0

**OS/terminal used**: macOS 10.12.2 iTerm 3.0.13

Wrapping a command with `complete -c cmd -w git` for example, will still complete filenames on cmd. To make it behave properly, I had to `complete -c cmd -w git -f`

**Comment by nhooyr** [comment]
Maybe this is expected, I just want to confirm because the docs have this specific example but they do not include `-f`.

**Comment by faho** [comment]
This works as expected for me, i.e. no files.

**Comment by nhooyr** [comment]
huh, it's working for me now too... If I can reproduce again I'll reopen this issue.
