### ISSUE TITLE
Bufferless pipes

### ISSUE THREAD

**Issue by almson** [fish-shell/fish-shell#3702]
It's a recognized problem in bash/unix that it's not possible to control whether pipes are buffered. This causes problems for things like `tail | grep` because text doesn't move through the pipe until enough of it accumulates or the first process exits.

I think Fish can offer a solution here.

**Comment by krader1961** [comment]
Actually, there isn't any way for fish to do what you're proposing. Whether output is buffered is determined by the stdio library that is linked into most programs. It's not a function of the pipe created by fish. The stdio code uses rules to determine whether the output is unbuffered, line buffered, or fully buffered. Also, the application itself can call one of the `setbuf()` family of functions to control the buffering. There is nothing fish can do to influence that.

Having said that fish does have one really annoying behavior. It fully buffers the output of commands in a pipeline. It's on our list of things to be changed. See, for example, issue #1040.

**Comment by ridiculousfish** [comment]
To elaborate on this, fish is indeed responsible for setting up pipes between processes, and can certainly adjust the pipe buffer size via `fcntl`. However as krader points out, data is often buffered at a higher level, such as by C's stdio library, and there's nothing fish can do about that.

For the record, it's not the case that data only moves through pipes when enough of it accumulates. Data is available to be read as soon as it is written.
