### ISSUE TITLE
explicit docs that complete-and-search moves back in the pager

### ISSUE THREAD

**Issue by nhooyr** [fish-shell/fish-shell#3703]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.4.0

It is not immediately clear that the bind function name `complete-and-search` is what moves back a selection in the pager.

**Comment by faho** [comment]
Yeah, this is another one of those cases where we've overloaded a function with meaning we'd like to have on the default combination.

"btab", i.e. shift+tab is a logical combination for moving backwards in the pager, since tab (bound to `complete`) moves forward.
