### ISSUE TITLE
Bizzarre contents in de.po

### ISSUE THREAD

**Issue by maxried** [fish-shell/fish-shell#3721]
**fish version installed** *(`fish --version`)*:
fish, version 2.4.0-327-g4bed9ea5-dirty, current HEAD

The German localization file contains a lot of rather weird or even wrong translations. Some of them seem to be mixed up, some just seem to be baldy translated. 

E.g.:
Mixed up:
Original English: "%ls: Key with name '%ls' does not have any mapping\n"
de.po: "%ls: Funktion '%ls' existiert nicht\n"
Backtranslation from de.po: "%ls: Function '%ls' does not exist\n"

Wrong:
Original English: "%ls: Expected exactly two names (current function name, and new function name)\n"
de.po: "%ls: Erwartete genau einen Funktionsnamen\n"
Backtranslation from de.po: "%ls: Expected exactly one function name\n"

Akward:
Original English: "Emit an event"
de.po: "Debian-Version auslassen"
Backtranslation from de.po: "Skip Debian version" or "Exclude Debian version"

Misunderstood:
Original English: "continue command while not inside of loop"
de.po: "Schleifensteuerungsbefehl 'while' nicht innerhalb einer Schleife"
Backtranslation from de.po: "Loop control command 'while' not inside of loop"

Translation changed the meaning:
Original English: "Unknown command '%ls'. Did you mean 'set %ls %ls'? See the help section on the set command by typing 'help set'."
de.po: "Unbekannter Befehl '%ls'. Meinten Sie 'set VARIABLE WERT'? Zu Informationen zum Festlegen von Variablenwerten schauen Sie in der Hilfe zum set-Befehl nach oder geben Sie 'help set' ein."
Backtranslation from de.po: "Unknown command '%ls'. Did you mean 'set VARIABLE VALUE'? For informations about setting of values of variables have look at the set command's help or enter 'help set'."

Weird:
English: "This is a login shell\n"
de.po: "Login-Shell erstellen"
Backtranslation: "Create login shell"

Weird:
English: "This is not a login shell\n"
de.po: "Login-Shell erstellen"
Backtranslation: "Create login shell" [sic!]

Weird:
English: "printf: not enough arguments"
de.po: "Dateiargumente nicht sortieren"
Backtranslation: "Do not sort file arguments."

Wrong:
English: "Test if adb has yet to be given the subcommand"
de.po: "Test, ob an apt noch ein Unterbefehl gegeben werden muss"
Backtranslation: "Test, if apt has to be given a subcommand"

I could go on for hours.
What's wrong there?

**Comment by faho** [comment]
Heh... I noticed the same thing just yesterday.

I'm assuming there's been a copy-paste mixup.

@zanchey: How exactly did you create 665314b240a911560b8f412a25dc931ef5081019?

Since I'm german, I'm taking ownership of this.

**Comment by faho** [comment]
Also, the mimedb stuff can go.

**Comment by zanchey** [comment]
I'm pretty sure that was Make-generated output - `xgettext` does tend to do some funny things.

**Comment by zanchey** [comment]
Might be worth backing that entire commit out.

**Comment by faho** [comment]
I've now gone over the translations and pushed 1baaeee17e2377ab6a63720e3f0fa07acf53fb66 that should fix the worst of this.
