### ISSUE TITLE
Strange config file behavior on Haiku

### ISSUE THREAD

**Issue by miqlas** [fish-shell/fish-shell#3725]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [ ] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
2.4.0

**OS/terminal used**: 
Haiku x86_64
Haiku Terminal

**Talk about the the issue here. **
Fish stores the config  files in ~/config/settings/fish on Haiku. Sometimes when i start it, it creates a clean one in ~/.config/fish and ~/.local/share/fish. Dot folders in Home not welcomed on Haiku.
It happend 3-4 times in the last some months.

Fish gets the ~/config/settings/ path from XDG env, so maybe this doesn't sourced. Maybe it is a Haiku bug. Maybe a bug in the matrix.
I also noticed, when i login trough ssh to Haiku, theese dot folders created automatically too. It is 100% reproducible.

Yesterday night i was deep in coding, everything was okay, rebooted Haiku, started Terminal, and got this problem again. I haven't tried to login trough ssh, but i started an zsh session before the shutdown.
Zsh installs a symlink as "/bin/sh" on Haiku, so it replaces bash. Every Haiku bootscript using #!/bin/sh hashbang, so maybe it is a zsh-bash difference, but it also happened before too. Sorry, i don't remember the details anymore.

There is surely a config file priority order in fish, so if there dot folder in the home, fish using that instead of the corrct location, so it gets wrong config.

## Reproduction steps
No idea, it happens randomly, will check carefully in the future.

## Results
```console
~ $ math 2 + 2
4
```

**Comment by miqlas** [comment]
I noticed, as long as zsh installed on Haiku, it happens all the time.
I used to update the Haiku zsh port/recipe in the past, so maybe this is the reason, why it happend before. Uninstalling zsh solves the problem.

I think we can close this issue. Sorry for the noise.

**Comment by faho** [comment]
The directory we use is $XDG_CONFIG_HOME/fish or ~/.config/fish if that isn't set.

So what is it set to in the different situations here? Maybe zsh sets it to something else?

**Comment by faho** [comment]
@miqlas: Closing since you don't seem interested anymore.

I'd still like to get to the bottom of this, though!

**Comment by miqlas** [comment]
@faho, i think i got new information :
- it isn't depends on zsh or any other shell
- the dot folders created every time as i initiate an shh connection to the Haiku box, where the login shell is fish
- sshd spawns an new fish instance, but only with minimal environment variables
- the XDG dirs defined in a file, what doesn't gets sourced before fish starts
- fish finds no XDG vars, thus creates a dot folder in $HOME

I don't know, how bash does it, but i'll look into it, as it is still happens.
Tried to pass env vars to the ssh session, but it gets parsed by the shell, not by sshd.
Maybe the .ssh/environment file could hel here, but i don't know yet.

Have you got any idea?
