### ISSUE TITLE
How to integrate powerline, tmux, and fish?

### ISSUE THREAD

**Issue by rschulman** [fish-shell/fish-shell#3726]
- [X] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [X] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.4.0

**OS/terminal used**: Mac OS X Yosemite, iTerm2

Talk about the the issue here. 

Powerline installation in tmux involves including the following line in your `.tmux.conf` config file:
```
source /usr/local/lib/python3.5/site-packages/powerline/bindings/tmux/powerline.conf
```
This line doesn't appear to work in fish (because that `powerline.conf` file uses `if-shell` which isn't a fish command). I haven't seen anyone else having this problem through Googling. Is there an obvious way to fix this problem that I'm not seeing? If not, is the answer to rewrite that `powerline.conf` file to use fishy syntax?

Thanks.

**Comment by faho** [comment]
>because that powerline.conf file uses if-shell which isn't a fish command

`if-shell` isn't a fish command, but it's not a bash-command either. It's a _tmux_ command.

>If not, is the answer to rewrite that powerline.conf file to use fishy syntax?

That "powerline.conf" isn't in shell syntax - it's in _tmux config_ syntax.

It includes a shell script, but it's one which is fish-compatible, at least in my version.

Here's the contents of powerline.conf on my system:

`if-shell 'env "$POWERLINE_CONFIG_COMMAND" tmux setup' '' 'run-shell "powerline-config tmux setup"'`

I just installed powerline and tmux and made a ~/.tmux.conf that consists of the line

```
source /usr/lib/python3.6/site-packages/powerline/bindings/tmux/powerline.conf
```

and it works for me.

Do you see any error messages here? What exactly happens?

**Comment by rschulman** [comment]
Ok, so doing a bit more testing, here is what is happening for me.
Calling tmux starts it with no errors that I see (except for `rvm` complaining at the top of launch about the PATH not being set correctly, I assume that's just a fish config issue I haven't addressed yet), but there is no powerline across the bottom.
Running zsh from inside a fish shell, then running tmux gives the proper result, as does changing my shell back to zsh and running in a fresh term.
Finally, if I run `powerline-config tmux setup; tmux` from fish, everything works properly that time, and every time I run tmux from that same terminal afterward.

Hope that helps us figure this out. Also happy to continue testing with any suggestions you have.

**Comment by faho** [comment]
What happens if you add this to config.fish:

```fish
    if string match -q 'screen*' -- $TERM
        powerline-config tmux setup
    end
```

and then start tmux? That'd be a good deal simpler than that config file ping-pong.

>Running zsh from inside a fish shell, then running tmux gives the proper result, as does changing my shell back to zsh and running in a fresh term.

This points towards some environment setup difference. Can you compare the output of `env` in those situations and post a diff? Obviously feel free to censor any personal information - we're not interested in your private gpg key or home address.

Also, which powerline and tmux versions are you using? I have tmux 2.3 and powerline 2.5.

**Comment by rschulman** [comment]
Including that snippet in my config.fish seems to have done the trick. Thanks! 

Out of curiosity, what does the fact that `screen*` is in the TERM tell you here?

**Comment by faho** [comment]
>Out of curiosity, what does the fact that screen* is in the TERM tell you here?

It's a poor man's way to detect that you're running tmux. Of course it'll break if you ever run GNU screen instead. It should probably also check that $TMUX is set.

Could you still check the `env` difference? I'd still like to know why the default recommendation isn't working for you since it might point to a real problem.

**Comment by krader1961** [comment]
FWIW, keep in mind that TERM might also be set to `tmux` or `tmux-256color` inside a tmux session. That's less common than using the screen terminfo but it's still a good idea to handle both.

**Comment by faho** [comment]
@rschulman: Could you give us the output of `env` if you run zsh and if you run fish, or are you no longer interested in this?

**Comment by krader1961** [comment]
@rschulman: I'm going to close this due to inactivity plus I think we've answered your question. You are welcome to reopen it if you are still having problems using fish in conjunction with tmux. Which I do on a daily basis so if you're still having problems I'm motivated to fix them.
