### ISSUE TITLE
Explicitly send output to stdout/stderr

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#3728]
As @krader1961 and I discussed in #3705, we currently use a bunch of output functions (`wprintf` and similar) that don't explicitly require an output stream.

We should replace them with `fwprintf` and similar so one can grep for "stdout", and in the process evaluate whether some of that output is more suitable for stderr, like it was in 3705 for the `test` errors.

**Comment by krader1961** [comment]
I ran `grep '[^fst](puts|putws|putc|putwc|[^w]printf|wprintf)' src/*` which should find most instances that need to be converted along with a few false positives such as the `builtin_printf()` definition. I'll clean those up.
