### ISSUE TITLE
subdir completion prefix

### ISSUE THREAD

**Issue by eoli3n** [fish-shell/fish-shell#3732]
**fish version installed** *(`fish --version`)*:
fish, version 2.4.0

**OS/terminal used**: 
Archlinux 4.8.13-1-ARCH #1 SMP PREEMPT Fri Dec 9 07:24:34 CET 2016 x86_64 GNU/Linux
rxvt-unicode (urxvt) v9.22 - released: 2016-01-23

Strange behaviour while tab completion in a subdir

## Reproduction steps
1. $ ls /some/dir/with/some/fi [tab][tab]
2. become blind

![alt](http://ptpb.pw/zWSR.png)

Is there a way, as we know the subdir we are searching for files, to just print filenames ?
``filename`` instead of ``...user/filename``

Redondant information.

**Comment by krader1961** [comment]
Seems like a good idea to me although I'm inclined to include the leading `.../` to make it crystal clear that the file names have a path prefix. TBD is what to do if someone uses a `./` prefix; e.g., `feh ./<tab>`. Do we really need to go to the trouble of special-casing that to treat it as if no path prefix was given?

**Comment by eoli3n** [comment]
An information is crystal clear by itself... 'cause it's an information.
When i say, ``it's blue``, it's pretty clear that the thing is blue. I don't need 15th of my friends repeating after me ``hell yeah it's clearly blue`` ``my god it's BLUE !`` ``wow a nice deep blue...`` :)

So if the user is not blind, he can see the path prefix in prompt.
It you want to make it crystal clear, use relative information which requires user to read his prompt by only using `.../filename` instead of ``...some_truncated_namedir/filename``.

**Comment by eoli3n** [comment]
![zsh](1484634312.png) Here my zsh, i doesn't see any problem with that, the underlining feature is cool.

**Comment by krader1961** [comment]
I now think, in light of @eoli3n's additional comments, that this behavior requires a lot more discussion before being changed. So I've added the RFC label.

**Comment by eoli3n** [comment]
Thanks, to finish, that behaviour could be usefull if we could autocomplete with some different dirs with a single ``[tab] action``.
```
ls file **/file[tab tab]
...dir1/file1
...dir2/file2
...dir3/file3
```
AFAIK, it's impossible, this ``...some_truncated_namedir`` will never change with a single ``tab action``

**Comment by gutenye** [comment]
Agreed with @eoli3n , people coming from zsh/bash are very happy with existing direction completions. And can not get used to this new style at first, and to me, this new style is annoying

**Comment by faho** [comment]
Okay, I'm rejecting this.
