### ISSUE TITLE
dynamic descriptions with dynamic arguments / options

### ISSUE THREAD

**Issue by bamarni** [fish-shell/fish-shell#3733]
- [X] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [X] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

While looking at how to define dynamic completion for argument / options, I couldn't find a way to describe dynamic descriptions at the same time.

For instance [here with tmux](https://github.com/fish-shell/fish-shell/blob/381404c4f45c59d90524adfa3ee746bd608aea9d/share/completions/tmux.fish#L101), option arguments are dynamic but their description is static. In that case it makes sense of course but in some other cases descriptions might be dynamic, is this currently supported?

Thanks

**Comment by krader1961** [comment]
I think you're looking for this feature described on the `complete` man page:

> Command substitutions found in OPTION_ARGUMENTS are not expected to return a space- separated list of arguments. Instead they must return a newline-separated list of arguments, and each argument may optionally have a tab character followed by the argument description. Any description provided in this way overrides a description given with -d or --description.

There are a few completions which use this feature. For example, from valgrind.fish

```
complete -c valgrind -n "__fish_valgrind_skin massif" -x -l format --description "Profiling output format" -a "html\t'Produce html output' text\t'Produce text output'"
```

The `-a` argument can also be a command substitution or a simple function name.

**Comment by bamarni** [comment]
Sounds good :) Thanks
