### ISSUE TITLE
distro provided env and path handling, need advice

### ISSUE THREAD

**Issue by gyakovlev** [fish-shell/fish-shell#3736]
Hello,

Currently I'm trying to create a mechanism for Gentoo Linux to make fish respect OS specific environmental variables set by various tools and packages after installation.

In Gentoo, packages install files with variables to export to _/etc/env.d/xxx_ and some tools or user can modify those files.
a special tool, called _env-update_ gathers all mentioned files and writes a file, _/etc/profile.env_ which is used by system to propagate those variables to user environment.
This may contain standard _$MANPATH, $PAGER, $LANG_ and many other important settings.

It's almost llike macOS's _/etc/paths.d_, but not only for paths.

I'm trying to make fish respect those settings.
Here is the code we ended up with.
This code is placed into _/usr/share/fish/vendor_conf.d/00-profile-env.fish_

```fish
# only apply profile.env for login shells, as we'd like fish to
# inherit existing shell environment without overriting it
if status --is-login
	# since fish supports export via upstream provided function
	# we can source directly, only ommiting $PATH and comments.
	grep -Ev "^(#|export (PATH|ROOTPATH)=)" /etc/profile.env | source

	# strip unneded stuff from bash export lines
	# apply paths and cleanup
	if [ "$EUID" = "0" ] ; or [ "$USER" = "root" ]
		set -l _rootpath (grep -o " ROOTPATH='.*'" /etc/profile.env | sed "s@.*'\(.*\)'@\1@;s@:@\n@g")
		set -xg PATH /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin $_rootpath
	else
		set -l _userpath (grep -o " PATH='.*'" /etc/profile.env | sed "s@.*'\(.*\)'@\1@;s@:@\n@g")
		set -xg PATH /usr/local/bin /usr/bin /bin $_userpath
	end

	# Re-prepend $fish_user_paths
	 __fish_reconstruct_path
end
```

#### 2) Why does fish prepend paths from $fish_user_path if run non interactively ( from a file with #!/bin/fish shebang). Is it intentional?
 here is commented testcase

just some info

```console
$ echo $SHELL
/bin/fish
$ echo $FISH_VERSION
2.4.0
```

here is current path, set by fish itself, xdm and set -U fish_user_paths
script /usr/share/fish/vendor_conf.d/00-profile-env.fish mentioned above is not used in this example
fish is started without any modifications, only non vanilla setting is fish_user_paths which contains ~/bin

```console
$ echo $PATH
/home/ya/bin /usr/local/bin /usr/bin /bin /opt/bin /usr/x86_64-pc-linux-gnu/gcc-bin/4.9.4 /usr/games/bin
$ echo $fish_user_paths
/home/ya/bin
```

here is a script I use to test non-interactive invocation

```fish
#!/bin/fish
echo $PATH
```

here is a simple test, add a new directory to PATH
as you can see I appears as a first element.
```console
$ set PATH /var/empty $PATH
$ echo $PATH
/var/empty /home/ya/bin /usr/local/bin /usr/bin /bin /opt/bin /usr/x86_64-pc-linux-gnu/gcc-bin/4.9.4 /usr/games/bin
```

when running script, fish prepends /home/ya/bin (from $fish_user_paths)
while I expect it to leave /var/empty as fist element of PATH array.

```console
$ echopath
/home/ya/bin /var/empty /usr/local/bin /usr/bin /bin /opt/bin /usr/x86_64-pc-linux-gnu/gcc-bin/4.9.4 /usr/games/bin
$
```

**Comment by krader1961** [comment]
> Is there anything wrong with this approach from your point of view?

Not that I can see but @faho and @zanchey have more expertise with this type of issue.

> Why does fish prepend paths from $fish_user_path if run non interactively...

Yes, that is intentional. Mostly because that variable is normally a universal variable. And uvars apply to all fish instances, not just interactive ones. This allows users to modify `$PATH` for all fish instances, interactive and non-interactive, without having to add code to their *~/.config/fish/config.fish* script. Having said that some people have questioned whether that variable should even exist. But that's a discussion for another issue.

**Comment by faho** [comment]
>1) Is there anything wrong with this approach from your point of view?

No. The approach is sound, as long as you can guarantee that the syntax is restricted to what fish will understand (with compatibility functions). As soon as someone adds e.g. a `${var]`, this _will_ fail.

You also might want to see if it's faster with `string match` instead of grep (we usually beat it in startup time).

>2) Why does fish prepend paths from $fish_user_path if run non interactively ( from a file with #!/bin/fish shebang). Is it intentional?

Yes, it's intentional. We try not to let the difference between interactive/non-interactive login/non-login get too large.

And in this case, `fish_user_path` is a part of $PATH. Imagine how it'd work if it weren't used in non-interactive shells. If you used a command in $fish_user_paths, that would suddenly not be found in a non-interactive shell.

The stuff we only do in interactive shells tends to be stuff that's not useful at all in non-interactive ones - like input bindings. So it's more of an optimization than a change in behavior.

**Comment by gyakovlev** [comment]
Thank you for your input.

I came up with this code with string match
also using csh env, as it's closer to fish
```fish
if status --is-login
	string match -r -v '^(#|setenv (PATH|ROOTPATH) )' < /etc/csh.env | source
	if [ "$EUID" = "0" ] ; or [ "$USER" = "root" ]
		string match -r '^setenv ROOTPATH .+' < /etc/csh.env | string replace -ra '\'|\:' ' ' | source 
		set -gx PATH /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin $ROOTPATH
		set -e ROOTPATH
	else
		string match -r '^setenv PATH .+' < /etc/csh.env | string replace -ra '\'|\:' ' ' | source
		set -gx PATH /usr/local/bin /usr/bin /bin $PATH
	end
	__fish_reconstruct_path
end
```
We are still deciding what to use for Gentoo here
https://bugs.gentoo.org/show_bug.cgi?id=545830

I'll leave this issue open for a little while if you don't mind. After we close gentoo bug I'll update this issue with final solution and close it.

**Comment by gyakovlev** [comment]
we came up with this solution, maybe someone hitting the search will find it useful.
re-using csh file (as it's simpler to consume) and parsing PATH|ROOTPATH variables using fish's string
/etc/csh.env is generated by package manager as needed and it does not allow {} or any code, just setenv statements.

```fish
if status --is-login
	string match -r -v '^(#|setenv (PATH|ROOTPATH) )' < /etc/csh.env | source
	if [ "$EUID" = "0" ] ; or [ "$USER" = "root" ]
		string match -r '^setenv ROOTPATH .+' < /etc/csh.env | string replace -ra '\'|\:' ' ' | source 
		set -gx PATH /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin $ROOTPATH
		set -e ROOTPATH
	else
		string match -r '^setenv PATH .+' < /etc/csh.env | string replace -ra '\'|\:' ' ' | source
		set -gx PATH /usr/local/bin /usr/bin /bin $PATH
	end
	__fish_reconstruct_path
end
```

still gathering feedback from users, but it looks like it works pretty damn good.

**Comment by gyakovlev** [comment]
Thanks for the help. We decided not to add this parser, as it completely omits /etc/profile.d/* sh files.
will advice users just to ```exec fish``` at the bottom of bashrc.
