### ISSUE TITLE
blinking cursor with fish_vi_cursor in iTerm2

### ISSUE THREAD

**Issue by nhooyr** [fish-shell/fish-shell#3741]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.4.0

**OS/terminal used**: iTerm2 3.0.13

In #3696, I mentioned that the cursor does not blink in insert mode with fish_vi_cursor.

@faho was unable to find the documentation on blinking for iTerm2. Neovim handles this fine, so perhaps @justinmk knows.

**Comment by krader1961** [comment]
iTerm2 supports the [DECSCUSR](http://www.vt100.net/docs/vt510-rm/DECSCUSR.html) command: CSI, Ps, space, "q". It implements two extensions: Ps=5 sets a blinking vertical bar, Ps=6 sets a non-blinking vertical bar. In the iTerm2 source look for `VT100CSI_DECSCUSR` in *sources/VT100Terminal.m*.

Fish implements a subset of these options in `__fish_cursor_xterm`. It looks like xterm supports the blinking variants according to this [document](http://invisible-island.net/xterm/ctlseqs/ctlseqs.html) and some other references I found.

**Comment by krader1961** [comment]
Also, FWIW, I think these functions should be named based on the capability implemented rather than a terminal that happens to support the capability; e.g., `__fish_cursor_decscusr` rather than `__fish_cursor_xterm`.

**Comment by faho** [comment]
>I think these functions should be named based on the capability implemented rather than a terminal that happens to support the capability

`__fish_cursor_xterm` is the version for xterm, while `__fish_cursor_konsole` is the one for konsole and `__fish_cursor_1337` is for newer iTerm (the only difference to konsole is that the number is 1337 instead of 50).

All of them handle the same capability, but in different terminals.

>It looks like xterm supports the blinking variants according to this document and some other references I found.

For xterm, this is already implemented.

>It implements two extensions: Ps=5 sets a blinking vertical bar, Ps=6 sets a non-blinking vertical bar

Good to know. So there's no blinking block or underscore?

**Comment by krader1961** [comment]
> So there's no blinking block or underscore?

It does, same as iTerm2. It's just that a real VT520 doesn't support vertical bar; hence no Ps 5 or 6. Per the documents I linked to:

```
CSI Ps SP q
          Set cursor style (DECSCUSR, VT520).
            Ps = 0  -> blinking block.
            Ps = 1  -> blinking block (default).
            Ps = 2  -> steady block.
            Ps = 3  -> blinking underline.
            Ps = 4  -> steady underline.
            Ps = 5  -> blinking bar (xterm).
            Ps = 6  -> steady bar (xterm).
```

**Comment by faho** [comment]
So the change needed here should be simple: Use `__fish_cursor_xterm` on iTerm as well. That leaves only konsole as the odd one out, but I can't find any way to set a blinking cursor there.

**Comment by christhekeele** [comment]
My iTerm2 reports as `xterm-256color`, so to work around instead of putting `fish_vi_cursor` in my config I did:

`fish_vi_cursor and if string match -i -r xterm $TERM and __fish_cursor_xterm`

**Comment by devsnek** [comment]
was this ever fixed? fish still overrides vertical bar in vi mode for me

**Comment by ridiculousfish** [comment]
@devsnek It sounds like you don't want fish's vi mode to adjust the cursor shape. Does no-oping `fish_vi_cursor` (e.g. `function fish_vi_cursor ; end`) solve this for you?

**Comment by devsnek** [comment]
@ridiculousfish yes, thanks
