### ISSUE TITLE
git tab completion missing a lot of options for 'git log'

### ISSUE THREAD

**Issue by adymitruk** [fish-shell/fish-shell#3743]
Some of the more common tab completions is git log do not appear.

Reproduce:
enter "git log --" and hit tab a couple of times. You only get 3 options.

Doing the same thing in bash gets you 100 options.

Some of the more common ones missing are: graph decorate oneline

**Comment by faho** [comment]
As you already know, this just hasn't been written yet.

I'd appreciate a PR that includes these options (and possibly some for other git subcommands), ideally with hand-written (i.e. not just copied from the git man pages, since those are often inscrutable) descriptions.

**Comment by moverest** [comment]
I think we can do some other improvements as well. On top of my head:

Fish completes:

```
git push origin --s<tab>
git push origin --set-upstream-to
```

But `set-upstream-to` doesn't exist; `set-upstream` does (on git 2.11 AFAIK).

```
git push origin --delete some<tab>
git push origin --delete origin/some-branch
```

But git expects `some-branch` and not `origin/some-branch`.

I'll do a PR within a few days with `git log` options if I have time to do it.

**Comment by faho** [comment]
>But set-upstream-to doesn't exist; set-upstream does (on git 2.11 AFAIK).

See 96a28df0183a860ca007eb84a8e46d43d9efe7b7. Now, apparently this was a misunderstanding - set-upstream-to is only for `git branch`, where set-upstream was deprecated in git 1.8. `git pull` still uses set-upstream, and doesn't have set-upstream-to at all.

That's git for ya.

**Comment by moverest** [comment]
They sure do know how to make things confusing. :-/

**Comment by cprieto** [comment]
I just finished with some fixing for the bzr completion and I can take a look at this now that I warmed up :) is ok @faho and @moverest ?

**Comment by moverest** [comment]
I have a half baked fix. If you want to finish it, go ahead. :-)

https://gist.github.com/moverest/f72e73df809ef4aad0a8e90200d9ee07

**Comment by faho** [comment]
All yours, @cprieto!
