### ISSUE TITLE
Different colors with same config files betweem two Debian servers

### ISSUE THREAD

**Issue by Holt59** [fish-shell/fish-shell#3750]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.4.0

**OS/terminal used**: Debian 8.7

I have installed fish on a new server, moved my configuration files between my old and my new server but I have different colors between my old and my new server (both running fish 2.4.0 on Debian 8.7).

On my old server, I installed fish 2.3.1 and then upgraded to 2.4.0, while on the new server I directly installed 2.4.0... Maybe it could be the problem.

Old server:
![screenshot from 2017-01-20 17 06 30](https://cloud.githubusercontent.com/assets/2393288/22156388/514ce734-df33-11e6-8d1a-be03baec1543.png)

New server:
![screenshot from 2017-01-20 17 07 51](https://cloud.githubusercontent.com/assets/2393288/22156339/2350cbac-df33-11e6-828c-bfeac6819810.png)

**Comment by faho** [comment]
The most likely difference here are the actual variable values.

The colors are stored in variables, and those variables are usually "universal", which means they are stored in a file in ~/.config/fish. This file is named after the mac address or hostname, so it's not directly used when copied to another machine.

To confirm, check that `set | string match -r "^fish_.*color.*"` prints different things on the two machines. To use the same, you need to move the definitions over. The easiest way to do that is to rename the "fishd.*" file in ~/.config/fish to the correct name. Open them up to see which is which - the one with the correct color definitions is the old one and needs to be moved over the new one.

See also #1912, where we are discussing if we should keep this scheme of machine-dependent universal variables.

**Comment by Holt59** [comment]
@faho Thanks, this was actually the problem, I renamed the file and now it works correctly.
