### ISSUE TITLE
edit_command_buffer function doesn't handle multi line commands

### ISSUE THREAD

**Issue by kevenwyld** [fish-shell/fish-shell#3758]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
this function is not available in fish 2.4.0
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?
Same result

fish, version 2.5b1

fedora 25 / rxvt-unicode

It seems the relatively new and very cool function edit_command_buffer.fish doesn't correctly handle multi line commands when the command has been broken with backslashes or when you attempt to break it with backslashes after it has been opened in an editor.  In this case I'm using vim.

For example:

`[ localhost~ ] > sudo nmap \`
`-Pn \`
`-A \`
`-O \`
`localhost`

Pressing Alt+e or Alt+v and then saving the file without making any changes results in:

`[ localhost~ ] > sudo nmap \`
`              -Pn \`
`              -A \`
`              -O \`
`              localhostcommandline: Unknown option “-Pn \”`
`/usr/local/fish-2.5b1-1/share/fish/functions/edit_command_buffer.fish (line 36):         commandline -r (cat $f)`
`                                                                                         ^`
`in function “edit_command_buffer”`
`	called on standard input`
``
``
`       commandlinecommandline - set or get the current command line buffer`
`        -`
``
`   Synopsis`
`       commandline [OPTIONS] [CMD]`
``
`commandline: Type “help commandline” for related documentation`

Sorry about the formatting.

**Comment by krader1961** [comment]
Good catch and the fix is trivial. This is a consequence of the standard practice for fish commands to allow flags anywhere on the command line rather than stop parsing after the first non-flag argument is seen. But I can't help but ask why in the world are you using backslash interactively?

**Comment by kevenwyld** [comment]
Thanks for the quick response!  My use case here was a very long automatically generated qemu launch command which I was trying to make a bit easier to read.  It was a a weird case I admit but it happened to expose this bug.

**Comment by zanchey** [comment]
Seems like we should take this for 2.5.0?

**Comment by krader1961** [comment]
The fix is trival -- the obvious insertion of `--` before the command substitution. So zero risk. I'll cherry-pick it in a few hours when back from the morning walk if you don't beat me to it.

**Comment by zanchey** [comment]
Done.
