### ISSUE TITLE
Long wrapping commands break autocomplete

### ISSUE THREAD

**Issue by christhekeele** [fish-shell/fish-shell#3763]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: fish, version 2.4.0

**OS/terminal used**: MacOS Sierra 10.12.2 + iTerm2 Build 3.0.13

Talk about the the issue here.

## Reproduction steps
1. Launch a clean shell:

    `sh -c 'env HOME=$(mktemp -d) fish'`

2. Run a command long enough to wrap:
    ```console
    > echo asdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdf
    ```

3. Type the first letter of the long command to observe autocomplete suggesting it.

## Results

The letter you typed (`e`) is in the correct place, as is the rest of the autocomplete (`cho asdf...`), but your cursor is offset 1 character too far to the right (under the `h`) for the rest of that command editing session. Further interactions with autocomplete (like typing the next expected `c`) exacerbate the problem further, further offsetting the the cursor for each letter typed in accord with the suggestion. Deleting everything you've type so far leaves you in the middle of the line with a bunch of junk in between where you should be, and where you are.

Curiously, this issue is **not** apparent in the [asciinema](https://asciinema.org/a/a8uvyfvpsz4aj8gxhm1aw6o3a) recording, which might help isolate the cause of the bug. (In practice, the 4th and 6th times I type an `echo` command in that recording, my session gets all skewed once autocomplete displays the wrapping command, despite what the asciinema shows.)

My 'fix' was to delete the long command from my history, which is good enough for me! Fish's multiline command support is good enough only pasted commands should get that way, and you can always `<C^c>` or `<Enter>` into a new valid editing session.

**Comment by zanchey** [comment]
I can't reproduce this on OS X 10.11 with iTerm 2 3.0.13 and fish 2.4.0 or 2.5b1.

It seems unlikely that this is caused by the prompt, but it might be worth sharing your `fish_prompt` function to be sure.

**Comment by christhekeele** [comment]
I can no longer reproduce; the issue persisted for several days but I must have done something right. 🤷‍♂️
