### ISSUE TITLE
Navigating history in vim-mode should transition from insert to normal mode

### ISSUE THREAD

**Issue by christhekeele** [fish-shell/fish-shell#3768]
[enhancement] [vim-mode]

**fish version installed** *(`fish --version`)*: 2.4.0

Currently in `vim-mode` you edit commands by default in `insert` mode. When you press <kbd>⇡</kbd> to walk the history, you stay in the mode you were in.

I find that when I'm going through my history I'd *always* prefer to be put from `insert` into `normal` mode, so that I can easier jump around the historical command I want to edit.

Note that I don't think pressing <kbd>⇡</kbd> and other history interactions should *always* take you to `normal` mode. The behaviour of history interactions with issued from `visual` and `replace` modes is undefined in this feature request, since I'm not sure what the behaviour there should be. But if you're in `insert` mode I think it makes lots of sense.

**Comment by krader1961** [comment]
I was going to suggest implementing this as a custom key binding but the solution isn't entirely satisfactory. You can do `bind -M insert -m default \e\[A up-or-search`. Which does leave you in default/vi-command mode after pressing up-arrow (assuming your [up] key sends that sequence). However, the mode indicator is still `[I]` which is obviously going to cause confusion. Adding `force-repaint` to the commands to run doesn't help.

I no longer use fish's vi-mode despite using Vim for all my file editing. Nonetheless, I think there is some merit to the proposal. Whether there is enough to change existing behavior, which will undoubtedly cause some users to complain, needs to be debated.

**Comment by faho** [comment]
Okay, I'm rejecting this. If you want to switch mode, use keys to switch the mode.
