### ISSUE TITLE
fish nightly hang during startup

### ISSUE THREAD

**Issue by TimWolla** [fish-shell/fish-shell#3770]
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
`fish, version 2.4.0-408-g31adc22`
**OS/terminal used**:
```
timwolla@node42:~$ gnome-terminal --version
GNOME-Terminal 3.18.3
timwolla@node42:~$ uname -a
Linux node42 4.4.0-59-generic #80-Ubuntu SMP Fri Jan 6 17:47:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

After the most recent upgrade of fish it hangs during startup. My dpkg log shows:

`2017-01-24 16:17:12 upgrade fish-common:all 2.4.0-390-gf447610-1~xenial 2.4.0-408-g31adc22-1~xenial`

Thus the issue must have been introduced somewhere between commit f447610 and 31adc22.

Tracing fish during startup shows the following. The writes look pretty much like my prompt, the `stat` is the last thing that appears:

```
write(1, "\33", 1)                      = 1
write(1, "[", 1[)                        = 1
write(1, "3", 13)                        = 1
write(1, "0", 10)                        = 1
write(1, "m", 1m)                        = 1
write(1, "\33", 1)                      = 1
write(1, "(", 1()                        = 1
write(1, "B", 1B)                        = 1
write(1, "\33", 1)                      = 1
write(1, "[", 1[)                        = 1
write(1, "m", 1m)                        = 1
write(1, "\33]0;fish  /home/", 16)               = 9
socket(PF_INET, SOCK_STREAM, IPPROTO_IP) = 3
ioctl(3, SIOCGIFHWADDR, {ifr_name="eth0", ifr_hwaddr=*snip*}) = 0
close(3)                                = 0
stat("/home/timwolla/.config/fish/fishd.*snip*", {st_mode=S_IFREG|0600, st_size=2291, ...}) = 0
```

Tracing a fish without customizations reveals lots of IOPS on the search of completions or something like that.

**Comment by TimWolla** [comment]
I just bisected the issue: ac9a0f0dbfeb8b76207202dcda2032faff6ad541 is the first bad commit

```
timwolla@node42:/tmp/fish-shell$ git bisect bad
ac9a0f0dbfeb8b76207202dcda2032faff6ad541 is the first bad commit
commit ac9a0f0dbfeb8b76207202dcda2032faff6ad541
Author: ridiculousfish <corydoras@ridiculousfish.com>
Date:   Mon Jan 23 13:56:43 2017 -0800

    Rework iothread_perform for void return types
    
    Need to use a template specialization so we don't try to create
    a variable of type void

:040000 040000 0da9e3643de9d52cff7d48de9c50c7e0cab8e97e 9ea44bab9bff81035a0963ba24b1ddd048a6c90a M	src
timwolla@node42:/tmp/fish-shell$ git bisect log
git bisect start
# bad: [bf2d61c6fd3cc8800ff563369f9ae75b50d28605] Revert "improve sanity check code"
git bisect bad bf2d61c6fd3cc8800ff563369f9ae75b50d28605
# good: [f4476100f28880e7fad660fefed118ef2521633c] Remove comment about job_iterator_t being used from signal handlers
git bisect good f4476100f28880e7fad660fefed118ef2521633c
# good: [fe8e99138d3ccd8467aac129e210d1c37c58079a] Adopt lambda-style perform_on_main in expand.cpp
git bisect good fe8e99138d3ccd8467aac129e210d1c37c58079a
# good: [699d294ac18c2f692cd093d78a9b0b8488eb4e63] Adopt iothread_perform-lambdas in fish_tests.cpp
git bisect good 699d294ac18c2f692cd093d78a9b0b8488eb4e63
# bad: [7e6543c4cd0158e1da6810e89ab1c785eb8681c3] improve sanity check code
git bisect bad 7e6543c4cd0158e1da6810e89ab1c785eb8681c3
# bad: [ac9a0f0dbfeb8b76207202dcda2032faff6ad541] Rework iothread_perform for void return types
git bisect bad ac9a0f0dbfeb8b76207202dcda2032faff6ad541
# first bad commit: [ac9a0f0dbfeb8b76207202dcda2032faff6ad541] Rework iothread_perform for void return types
```

**Comment by krader1961** [comment]
Thanks for the bisect, @TimWolla. I see that @faho also reported strange behavior on Gitter and I commented that it might have been the SIGHUP fix I merged last night since Travis is also failing two of the four test environments; albeit in ways that shouldn't be affected by my SIGHUP fix.

I'm guessing that change is making use of a feature that may not be properly (i.e., correctly) supported with an old gcc. Can you tell us what `gcc --version` reports on your system? Or `clang --version` if that's what you're using.

**Comment by TimWolla** [comment]
No idea what the OpenSuse build servers use for the nightlies. A build during the bisect revealed:

```
timwolla@node42:/tmp/fish-shell$ make -j 4
  FISH_BUILD_VERSION = ''
  FISH_BUILD_VERSION = '2.4.0-406-gac9a0f0d'
  CXX = 'g++ -std=c++11'
  CXXFLAGS = '-g -O2 -fno-exceptions -Wextra -Ipcre2-10.22/src '
  MKDIR_P = '/bin/mkdir -p'
  CPPFLAGS = '-DLOCALEDIR="/tmp/fish-test/share/locale" -DPREFIX=L"/tmp/fish-test" -DDATADIR=L"/tmp/fish-test/share" -DSYSCONFDIR=L"/tmp/fish-test/etc" -DBINDIR=L"/tmp/fish-test/bin" -DDOCDIR=L"/tmp/fish-test/share/doc/fish" -iquote. -iquote./src/ -DFISH_BUILD_VERSION="2.4.0-406-gac9a0f0d"'
  MAKE     pcre2-10.22/.libs/libpcre2-32.a
```
and
```
timwolla@node42:~$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by faho** [comment]
@krader1961: This also happens with gcc 6.3.1, so it's not just "an old gcc".

Looking at [the Travis build history](https://travis-ci.org/fish-shell/fish-shell/builds), it also doesn't appear to be your recent commits but @ridiculousfish's recent work - most recently ac9a0f0dbfeb8b76207202dcda2032faff6ad541. So your reverts appear to be unnecessary.

**Comment by TimWolla** [comment]
@faho In fact that's the exact commit I bisected above :wink:

**Comment by faho** [comment]
@ridiculousfish: I've pushed 1040b25, which reverts ac9a0f0 for the time being. If you wish to try again, I'm happy to help test.

@krader1961: 7e6543c4cd and 31adc221d92a can go back in, at your discretion.

**Comment by TimWolla** [comment]
Can confirm working with `fish, version 2.4.0-411-g1040b25`, thanks.
