### ISSUE TITLE
Character at beginning of each new line.

### ISSUE THREAD

**Issue by davedodea** [fish-shell/fish-shell#3774]
Each time I enter a command or start a shell/tab, there is a character at beginning of each new line.

Mac OS X 10.11
Fish 2.4

Issue remains even after changing theme, see screenshot attached:

![screen shot 2017-01-24 at 22 03 13](https://cloud.githubusercontent.com/assets/9055118/22268965/69ac30d6-e281-11e6-8aa2-37e309e3927f.png)

**Comment by krader1961** [comment]
Are you referring to the `[I]`? If yes that is the vi-mode indicator telling you that you're in vi insert mode (as opposed to `[N]` meaning you're in normal/command mode). You can remove it by defining an empty `fish_mode_prompt` function. In the fish 2.5.0 release (currently in beta test) you'll have more control over where that information appears.

**Comment by davedodea** [comment]
@krader1961 thanks for the reply. Is there any way to have no character at all, just the username?

**Comment by krader1961** [comment]
Yes, define your own `fish_mode_prompt` function that outputs whatever you like or nothing at all. Run `type fish_mode_prompt` to see the current function.

**Comment by davedodea** [comment]
Perfect, thank you.
