### ISSUE TITLE
Add yarn tab completions

### ISSUE THREAD

**Issue by adymitruk** [fish-shell/fish-shell#3776]
Yarn is a replacement for npm used by a lot of users due to npm's deficiencies. Currently, the yarn autogenerated tab completions don't reflect the proper commands based on the man page or help message from yarn.

**Comment by faho** [comment]
I think @cprieto wanted to take a crack at this.

**Comment by cprieto** [comment]
Indeed @faho I already started this but this is my last week at my current job so it has been a little busy... Let it to me and this weekend I will push the changes ;)

**Comment by faho** [comment]
This has been done with #3816. Thanks @cprieto!

**Comment by portenez** [comment]
Hi there, so how do we need to get the completions?

I'm on yarn `0.21.3`, and fish `2.6.0`

**Comment by cprieto** [comment]
It should be included and work automatically on fish 2.6.0, if not, please fill a ticket and I will take a look.

**Comment by portenez** [comment]
I updated my arn to 0.27 and now see completions, but only till the command level. Meaning: I can do `yarn <tab>` and I see the available commands. But, then If do something like `yarn remove <tab>`, I don't get correct completions. Is this as expected?

**Comment by cprieto** [comment]
May I ask you add a ticket with something like "command level completion in yarn" or similar, and I will start working on it.
