### ISSUE TITLE
expansion of glob pattern in file expression should not halt the execution

### ISSUE THREAD

**Issue by jsilhan** [fish-shell/fish-shell#3779]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.3.1 and upstream version ec19159

**OS/terminal used**: Linux Fedora 25 / Gnome terminal 3.20

When I give into some command file path with glob expression and directory does not exists it will halt whole execution instead skipping the extraction of star and passing the expression as it is into the command
See:
```fish
⟩ echo /fdsf/*
No matches for wildcard “/fdsf/*”.
fish: echo /fdsf/*
           ^
```
vs
```bash
⟩ bash
$ echo /fdsf/*
/fdsf/*
```

When you use it in `cat` it does not evaluate it at all:
```fish
cat /usr/bin/*.sh /not/exist/*
No matches for wildcard '/not/exist/*'.  (Tip: empty matches are allowed in 'set', 'count', 'for'.)
fish: cat /usr/bin/*.sh /not/exist/*
```
while in bash it outputs all .sh files in `/usr/bin`

result of `cat /usr/bin/*.sh /not/exist/*` should be IMO consistent with `cat /usr/bin/*.sh /not/exist/file` - it should not halt the execution. In bash this works how one would expected.

## Reproduction steps
1. `echo /fdsf/*`

## Results
```console
~ $ echo /fdsf/*
No matches for wildcard “/fdsf/*”.
fish: echo /fdsf/*
           ^
```

**Comment by krader1961** [comment]
The behavior you observed is intended. It was debated extensively in issue #2394 (as well as some others). The solution is to use this pattern:

```
set var /usr/bin/*.sh /not/exist/*
cat $var
```

This is documented [here](http://fishshell.com/docs/current/index.html#expand):

> Note that for most commands, if any wildcard fails to expand, the command is not executed, $status is set to nonzero, and a warning is printed. This behavior is consistent with setting shopt -s failglob in bash. There are exactly 3 exceptions, namely set, count and for. Their globs are permitted to expand to zero arguments, as with shopt -s nullglob in bash.
