### ISSUE TITLE
can no longer interrupt interactive loops

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3780]
Commit ab189a75abeeeaf5cbddc2ffc7e865567fb39bc6 merged two days ago broke [ctrl-C] handling. You can no longer interrupt this loop:

```
while true; echo here; sleep 1; end
```

**Comment by krader1961** [comment]
From the current github master head I did

```
git checkout -b sigint`
git revert ab189a75abeeeaf5cbddc2ffc7e865567fb39bc6
```

and [ctrl-C] worked. I've spent an hour or two looking at that change and don't understand why it breaks handling SIGINT but it clearly does so.

**Comment by ridiculousfish** [comment]
Yikes. I'll take a look.

**Comment by ridiculousfish** [comment]
It ended up being in `handle_child_status`. The new line `for (process_ptr_t &p : j->processes...` introduces a variable `p` that shadows the top-level `p`. Thus the `if (p && found_proc) parser_t::skip_all_blocks` check fails.

I need to beef up the ctrl-c cancellation tests, they should have caught this. Thanks for bisecting!
