### ISSUE TITLE
AC_DEFINE_MACRO_DIRS is not available in travis (precise)

### ISSUE THREAD

**Issue by ZyX-I** [fish-shell/fish-shell#3782]
**fish version**: ec1915958040eb8abf6609488f30df2723b76224

**OS/terminal used**: Ubuntu 12.04.5 LTS

Trying to build fish using [script](https://github.com/powerline/bot-ci/blob/5a3c3822c0fde10e25b3950fd4a2e33b1a4f1bfa/scripts/build-fish.sh)

```Sh
sed -r -i -e '1i m4_pattern_allow(AC_CONFIG_MACRO_DIRS)' ./configure.ac
autoreconf --version
autoreconf --no-recursive
./configure --prefix="$OPT_DIRECTORY"
make
./fish --version
make install
```

results in

```
+cd pcre2-10.22
+autoreconf
libtoolize: `./ltmain.sh' is newer: use `--force' to overwrite
libtoolize: `m4/libtool.m4' is newer: use `--force' to overwrite
libtoolize: `m4/ltoptions.m4' is newer: use `--force' to overwrite
libtoolize: `m4/ltversion.m4' is newer: use `--force' to overwrite
+cd ..
+sed -r -i -e 1i m4_pattern_allow(AC_CONFIG_MACRO_DIRS) ./configure.ac
+autoreconf --version
autoreconf (GNU Autoconf) 2.68
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+/Autoconf: GNU GPL version 3 or later
<http://gnu.org/licenses/gpl.html>, <http://gnu.org/licenses/exceptions.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Written by David J. MacKenzie and Akim Demaille.
+autoreconf --no-recursive
+./configure --prefix=/home/travis/opt/fish
checking if autoreconf needs to be run... no
checking if autoheader needs to be run... no
./configure: line 2594: syntax error near unexpected token `m4'
./configure: line 2594: `AC_CONFIG_MACRO_DIRS(m4)'
```

: https://travis-ci.org/powerline/bot-ci/jobs/195483039. Without `sed` it would be

```
+autoconf
configure.ac:89: error: possibly undefined macro: AC_CONFIG_MACRO_DIRS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
```

I don’t get any errors locally (autoconf-2.69) if I just drop the AC_CONFIG_MACRO_DIRS line completely, but this is not the case on travis: apparently 2.68 does not know about C++11 macros.

For travis autoreconf to work it is needed to replace `AC_CONFIG_MACRO_DIRS` with `m4_include(m4/ax_cxx_compile_stdcxx_11.m4)` (I actually added two m4_include calls: for both macro files in m4/).

**Comment by faho** [comment]
Our own [.travis.yml](https://github.com/fish-shell/fish-shell/blob/master/.travis.yml) defines `dist: trusty` (16.04 if I'm not mistaken). Any reason you need to use 12.04? It's almost 5 years old at this point.

@zanchey might know what that we use that macro for.

**Comment by ZyX-I** [comment]
@faho `trusty` is not default and is beta, I do not want to change anything until they make it default and I am definitely not switching to beta.

Macro is a replacement for `m4_include` which does not require to list all files in a directory, allows defining macros in a separate file. Needed to get macros for checking whether compiler supports C++11. I did not investigate why there are two included macro files, while code actually uses macro from only one of them.

**Comment by ZyX-I** [comment]
Additionally neovim switched to trusty and it appeared to be running on slower machines. Not sure whether situation changed since the last time I heard complains.

**Comment by zanchey** [comment]
One macro depends on the other; you will need both. This is the reason that we use `AC_CONFIG_MACRO_DIRS` rather than `m4_include` - so that we don't have to maintain a dependency list of specific `m4_include` entries.

Fish requires Automake 1.13 to build from git source for aclocal and `AC_CONFIG_MACRO_DIRS`; Precise does not support this version. You might be able to pull in a newer version of Automake into the Precise Travis environment.

I am not particularly thrilled about the idea of dropping this dependency. It is only needed for git builds; for tarballs the toolchain generates the appropriate files and neither autoconf nor automake are needed.

**Comment by zanchey** [comment]
I don't think we're going to change this, so I'm going to close for now, but if the workaround isn't workable then please let speak up!
