### ISSUE TITLE
Feature: inhibit filename completion for the whole command

### ISSUE THREAD

**Issue by leoboiko** [fish-shell/fish-shell#379]
There are many commands that, when no options are provided, never take filenames as arguments (ip, ifconfig, route, wget, ps...)

In fish, we can prevent filename completion for certain options, with e.g. `complete -c cmd -l opt -f` or `complete -c cmd -l opt -x`.  However, there seems to be no way to inhibit it when no options are present.  This makes tab completion offer files for such commands to consume, which is a bit jarring.  It would be cool to have a syntax like `complete -c cmd -f` , or (for subcommands) `complete -c cmd -a sub -f` (or some other syntax).

**Comment by faho** [comment]
This is the same as #112, no?
