### ISSUE TITLE
The behavior of `test -p /dev/stdin` is different from bash

### ISSUE THREAD

**Issue by NomadBlacky** [fish-shell/fish-shell#3792]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.4.0

**OS/terminal used**: Ubuntu 14.04

### bash

```bash
$ echo something | test -p /dev/stdin ; echo $?
0
$ test -p /dev/stdin ; echo $?
1
```

### fish

```fish
$ echo something | test -p /dev/stdin ; echo $status
1
$ test -p /dev/stdin ; echo $status
1
```

Is this the specification?

**Comment by krader1961** [comment]
This is probably another manifestation of issue #1228. I'll take a closer look and close this as a dup if it is.

**Comment by ridiculousfish** [comment]
fish does not fork to execute its builtin `test`, so `/dev/stdin` will not be a pipe.

One "workaround" is to use `command test` to avoid the builtin.

Is this just something you noticed, or is it causing problems?

**Comment by NomadBlacky** [comment]
My problem was solved using this.
Thank you.

**Comment by ridiculousfish** [comment]
Yay!

**Comment by faho** [comment]
@NomadBlacky: What exactly _was_ your problem?

**Comment by uohmak4fvpqe** [comment]
That would be nice for the man page to mention that.

In fact, fish's version of ```test``` could as well just miss the -p option. Or does it have any functioning purpose ?

**Comment by zanchey** [comment]
`/dev/stdin` isn't a named pipe/FIFO, at least on any system I've got access to.
