### ISSUE TITLE
Unable to run locally installed npm scripts. Unknown command 'x'

### ISSUE THREAD

**Issue by mrmartineau** [fish-shell/fish-shell#3795]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.4.0

**OS/terminal used**: iTerm

I am unable to run locally installed npm scripts; globally installed packages are working without any issues. My project uses the gulp task manager which is one of the many that aren't working - this issue is not related to gulp.

My fish setup is fairly clean, I have only added a few aliases and one function (although, I have tested the issue again by removing all of them, to no avail).

Is there some config or setting I can change that would fix my issue? Has someone come across this

## Reproduction steps
1. Install project with gulp dependency and it's own gulp scripts
2. run one of the gulp task e.g. `gulp css`
3. see error message below

## Results
```console
fish: Unknown command 'gulp'

# Below are the other comands that could be used when I navigated to the `node_modules/.bin` directory:

$ ls
JSONStream          express             mime                specificity
acorn               find-versions       mkdirp              sshpk-conv
atob                fractal             node-gyp            sshpk-sign
babylon             gifsicle            node-sass           sshpk-verify
bin-version-check   gulp                nopt                strip-dirs
browser-sync        gzip-size           not-in-install      strip-indent
browserslist        handlebars          not-in-publish      strip-json-comments
buble               har-validator       npm-scripts-info    stylehacks
colorguard          html-beautify       nunjucks-precompile stylelint
css-beautify        in-install          optipng             svgo
css-rule-stream     in-publish          pngquant            throttleproxy
csso                jpegtran            pretty-bytes        uglifyjs
dev-ip              js-beautify         rc                  user-home
doiuse              js-yaml             regjsparser         uuid
dox                 jsesc               release-it          webpack
doxme               json5               rimraf              weinre
editorconfig        jsonfilter          sassgraph           which
errno               loose-envify        seek-bunzip         window-size
eslint              lpad-align          seek-table          xo
esparse             lt                  semver
esvalidate          marked              sha.js
executable          miller-rabin        shjs
~/c/k/k/n/.bin (nucleus-styleguide|●1✚7) $ xo --fix
fish: Unknown command 'xo'
```

Let me know if there's any more info needed.

Much appreciated in advance.

**Comment by krader1961** [comment]
When you get an error like `fish: Unknown command 'gulp'` it means that either you haven't defined a function by that name or if it's an external command its directory is not in the `$PATH` env var. In this case it looks like you need to execute `set PATH ~/node_modules/.bin $PATH`. If you're using a helper command to setup your environment, including `$PATH`, you may need to use a fish compatible version or invoke it with the [bass](https://github.com/edc/bass) helper command.

**Comment by mrmartineau** [comment]
Hi @krader1961, thanks for your help, but I don't think your solution helped.. Here are the items on `$PATH` (before adding your suggestion, by running `printf "%s\n" $PATH`):

```console
/usr/local/Cellar/node/7.4.0/bin
/usr/local/opt/fzf/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
```

By adding your suggestion, I get this error:

```console
set: Warning: $PATH entry "/Users/zander/node_modules/.bin" is not valid (No such file or directory)
```

The issue is not with globally installed packages, but local, project-specific ones, why would adding your path work. Does that make sense? What else could it be? A rogue fish setting elsewhere?

The only item that I have added to `$PATH` manually is `set -xg PATH (yarn global bin) $PATH` for the yarn package manager, the other item, fzf is being added elsewhere.

Thanks again for your help

**Comment by krader1961** [comment]
Sorry, I just assumed the reference to `node_modules/.bin` was relative to $HOME. If it's relative to your cwd just do `set PATH ./node_modules/.bin $PATH`. I don't use NodeJS and can only guess what you mean by "local, project-specific, packages". Pretty sure this has nothing to do with a "rogue fish setting". You're simply failing to add the appropriate directory for those "local, project-specific, packages" to $PATH.

**Comment by mrmartineau** [comment]
HI @krader1961, thanks again for your help. Unfortunately your suggestion did not work. I also tried to explicitly set the working folder in `$PATH` to no avail. I'm fairly certain that I should not have to add every project folder to `$PATH` each time so I can only assume it is something else. I am quite familiar with bash so have been trying quite a few other things to fix this, again to no avail...

**Comment by mrmartineau** [comment]
@krader1961 I have just noticed something interesting.. I am able to run `npm run` scripts which but not the actual contents of the run script. For example if `npm run compile` had a value of `grunt compile`, it would run as expected, but running `grunt compile` by itself does not work.. I think this maybe a npm-related bug now so I will raise a ticket there.

**Comment by krader1961** [comment]
People using fish have mentioned npm in the [past](https://github.com/fish-shell/fish-shell/issues?utf8=%E2%9C%93&q=is%3Aissue%20npm). For example, issue #2370. You might find the answer to your problem in issue #3023.

**Comment by zanchey** [comment]
It sounds like this was a local configuration problem (from the linked npm bug), so I'm closing this for now - but do reopen if I'm mistaken!

**Comment by Crypt0Graphic** [comment]
Well. Angular & Ionic didn't work with Fish. I installed them again with fish and no problem. Other solutions didn't work for me.

**Comment by mehmetnyarar** [comment]
I have this problem

> fish: Unknown command eslint

I've tried [this](https://github.com/fish-shell/fish-shell/issues/3023#issuecomment-387944920) and [this](https://github.com/fish-shell/fish-shell/issues/3023#issuecomment-477745484) but it's not working.

**Comment by faho** [comment]
@mehmetnyarar: The same idea applies. Find where the "eslint" command is and add that directory to your $PATH.

**Comment by mehmetnyarar** [comment]
@faho it's under `node_modules`. i can't do this for every node project, it isn't efficient. Is there any other way?

**Comment by faho** [comment]
>it's under node_modules. i can't do this for every node project, it isn't efficient. Is there any other way?

$PATH can also contain relative entries, so adding `node_modules/bin` would also work.
