### ISSUE TITLE
Using a space within curly braces results in 'mismatched brackets' error

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#3802]
- [x] Have you checked if problem occurs with [fish 2.4.0](/fish-shell/fish-shell/releases/tag/2.4.0)?
- [ ] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version 2.4.0-472-gf48291b

**OS/terminal used**:
Bash on Linux, FreeBSD 10

## Reproduction steps
1. execute the following:
`echo {hi, hello} world`

## Results
```
mqudsi@ZBook /m/c/U/M/g/easyre> echo {hi, hello} world
Mismatched brackets
```

Re-running without the space after the comma proceeds OK:

```
mqudsi@ZBook /m/c/U/M/g/easyre> echo {hi,hello} world
hi hello world
```

The same happens for spaces within a word (i.e. not immediately after or next to a comma within the braces).

**Comment by krader1961** [comment]
The current behavior is more or less consistent with bash; albeit bash does not issue a warning, it just emits the literal string. If you do `bash -c 'echo x{a , b ,c}x'` you get `x{a , b ,c}x` as output. That is, it does not do the brace expansion. The bash man page says

> Patterns  to be brace expanded take the form of an optional preamble, followed by either a series  of  comma-separated  strings  or  a  sequence  expression between a pair of braces, followed by an optional postscript.... A  correctly-formed  brace  expansion  must  contain  unquoted  opening and closing braces, and at least one unquoted comma or a valid sequence expression.  Any incorrectly  formed  brace  expansion  is left unchanged.

However it is silent on whether those strings can contain embedded whitespace but the observed behaviors says, no, they cannot. It's not obvious whether fish should deviate from bash in this regard. The reason fish deviates by issuing an error rather than just regurgitating the invalid expansion is to let the user know they aren't going to get the result they expected.

For the record, @mqudsi, do you expect `echo x{a , b ,c}x` to output `xax abx acx` or `xa x x b x xcx`?

**Comment by krader1961** [comment]
@mqudsi: ping? What do you expect to happen in the examples in my previous comment?

**Comment by mqudsi** [comment]
This is obviously "here be dragons" purely-subjective territory here, but from my observations, shell scripts don't care about whitespace. Correct me if I'm wrong, but it's ignored everywhere else?

Can we compromise with a "ignore whitespace unless it's in quotes" approach? 
`echo x{a, b , c   }x` should output `xax xbx xcx` and if the user wants the quotes, they can use echo `x{" a ", "b " , c}x` to output `x a x xb  x xcx`, perhaps?

The bracket expansion already (opinionatedly?) adds whitespace between bracket elements, I agree that it doesn't make sense to respect spaces in the elements. So basically treat array elements the way you would parameters and disregard spaces unless they're quoted or escaped (w/ a backslash). 

The only question becomes what you do with `echo {hello, hi, good morning}, friend!` Is that just illegal syntax or do you still just split on comma, trim start/end, and output as-is?

**Comment by faho** [comment]
>shell scripts don't care about whitespace.

That's a good point. However, this is quite a breaking (and hard to check for) change. So if we did it at all we should do it with care and a strong consensus, in a major release.

>The bracket expansion already (opinionatedly?) adds whitespace between bracket elements

It doesn't. It _splits_ every result of a bracket expansion. What adds the whitespace is `echo`. The result of a bracket expansion `x{foo,bar}` will be a list `["xfoo", "xbar"]`.

See:

```fish
>printf '%s' "Hello ,"{Friend,Enemy}
Hello ,FriendHello ,Enemy
```

>The only question becomes what you do with echo {hello, hi, good morning}, friend! Is that just illegal syntax or do you still just split on comma, trim start/end, and output as-is?

Logically, this would be `["hello,", "hi,", "good morning,", "friend!"]`, so the output would be `hello, hi, good morning, friend!`. That's with the change, without it would have " hi" and " good morning", with a leading space.

**Comment by mqudsi** [comment]
Ah, thanks for clearing up the spaces-between-parameters thing. That makes more sense. 

My question about the "good morning" was what you'd do when you have a space in the middle of an unquoted parameter, though. I'm not clear on whether your reply was taking that into account.

**Comment by faho** [comment]
>My question about the "good morning" was what you'd do when you have a space in the middle of an unquoted parameter, though. I'm not clear on whether your reply was taking that into account.

My idea was that the separator here is ",". We'd ignore/skip whitespace around it, but if there is no separator then we'd use the whitespace.

Anyway, I think the biggest hurdle here is the idea that this is sufficiently better than the status quo that it's worth breaking somebodies script over it (and you can be sure someones script will be broken).

I'm gonna add the RFC tag here to invite more discussion.

**Comment by mqudsi** [comment]
I'm wondering if it's possible to do this without breaking any scripts as an initial step? Currently, a fish script with spaces around the comma is an error.. Changing just that behavior wouldn't break anything, would it?

**Comment by faho** [comment]
>I'm wondering if it's possible to do this without breaking any scripts as an initial step? Currently, a fish script with spaces around the comma is an error.. Changing just that behavior wouldn't break anything, would it?

Ouch, sorry, yeah. I misremembered what happened currently. So it wouldn't be breaking, since no script that currently uses the syntax is valid.

**Comment by krader1961** [comment]
> My idea was that the separator here is ",". We'd ignore/skip whitespace around it, but if there is no separator then we'd use the whitespace.

Agreed. That is also consistent with the recent change I made to how we parse integers to ignore both leading and trailing whitespace. Note that quoted strings inside the braces are already handled as @mqudsi expects:

```
$ echo x{"a b ",c," d e"}y
xa b y xcy x d ey
```

So all we need to do is ignore the unquoted leading and trailing whitespace around the strings inside the braces.

It's just a small matter of writing the code :smile:

**Comment by mqudsi** [comment]
I'd be happy to give it a try if you could just point me to where the code responsible for creating the parameters is located.

**Comment by krader1961** [comment]
@mqudsi: See `expand_brackets()` in *src/expand.cpp*. Also, if you do decide to proceed with implementing this proposal please rename that function to `expand_braces()`.  And replace "brackets" with "braces" in the related enums, etc. Both because the documentation refers to the construct as brace expansion and because "brackets" normally refers to the square variant, `[]`, while "braces" is usually used for the curly variant: `{}`.

**Comment by mqudsi** [comment]
I haven't run it through a debugger, but it seems to me that modifications are actually somewhere up the chain since it looks like `syntax_error` is only set in `expand_braces` if there is no terminating brace; which means the string is being chopped at the non-quoted whitespace before it is being passed in to `expand_braces` for evaluation?

**Comment by mqudsi** [comment]
This was definitely _not_ as straightforward as we'd originally thought, it required low-level modifications to the tokenizer to get it to not split on spaces within braces before sending it to the expand function.

Additionally, the original tokenizer code would have required code exponential in length to the number of modes (regular text, subshell, slices) that made it virtually impossible to add another mode (braces) without changing the way that was written.

It passes all the tests and I added some new ones, but I might have missed something.
