### ISSUE TITLE
fish 2.5.0 sha256 mismatch

### ISSUE THREAD

**Issue by nijikon** [fish-shell/fish-shell#3807]
https://fishshell.com/files/2.5.0/fish-2.5.0.tar.gz - 03733fc4ec6dbdd10b3711ca5646436610d13ce0c3a14399787ab29471b2c24e
https://github.com/fish-shell/fish-shell/releases/download/2.5.0/fish-2.5.0.tar.gz - f8c0edadca2de379ccf305aeace660a9255fa2180c72e85e97705a24c256b2a5

Something is not right :)

Homebrew/homebrew-core#9599
Homebrew/homebrew-core#9600

**Comment by zanchey** [comment]
I generated the second tarball - I assume @ridiculousfish generated the first?

**Comment by nijikon** [comment]
It looks like the tarball on the page is https://github.com/fish-shell/fish-shell/archive/2.5.0.tar.gz instead of https://github.com/fish-shell/fish-shell/releases/download/2.5.0/fish-2.5.0.tar.gz.

**Comment by nijikon** [comment]
https://github.com/fish-shell/fish-shell/archive/2.5.0.tar.gz - 03733fc4ec6dbdd10b3711ca5646436610d13ce0c3a14399787ab29471b2c24e

**Comment by zanchey** [comment]
Don't use https://github.com/fish-shell/fish-shell/archive/2.5.0.tar.gz - it is an incomplete archive (lacks documentation and configure script).

**Comment by nijikon** [comment]
You should probably update https://fishshell.com/files/2.5.0/fish-2.5.0.tar.gz with the release file then :)

**Comment by zanchey** [comment]
If I could, you think I'd still be here? :-)

Ping @ridiculousfish

**Comment by ridiculousfish** [comment]
Yikes, nice catch. I did indeed upload the wrong tarball.

I've fixed the site. The invalidation has to filter through CloudFront, but you can see the new stuff at http://fishshell.com.s3-website-us-east-1.amazonaws.com now
