### ISSUE TITLE
fish_update_completions not working if MANPATH is set

### ISSUE THREAD

**Issue by Darkshadow2** [fish-shell/fish-shell#3808]
**fish version installed** *(`fish --version`)*:
fish, version 2.5.0-150-g3e17b8f

**OS/terminal used**:
macOS 10.12.2, iTerm

if `MANPATH` is set, `fish_update_completions` fails with

```
Traceback (most recent call last):
  File "/fish/share/fish/tools/create_manpage_completions.py", line 943, in <module>
    file_paths.extend(get_paths_from_manpath())
  File "/fish/share/fish/tools/create_manpage_completions.py", line 874, in get_paths_from_manpath
    if not parent_paths or proc.returncode > 0:
UnboundLocalError: local variable 'proc' referenced before assignment
```

This was introduced in [03e0f1e](https://github.com/fish-shell/fish-shell/commit/03e0f1eb21e9df76ed792cbd8349d04ec29b8906)

I can see what's happening. If `MANPATH` is set, proc is never defined and so the test checking the response fails.

Python being used is the system standard, `Python 2.7.10`.

**Comment by faho** [comment]
Nice catch! This should be fixed by b3d5fb71f484de4dae8103ab4ac099377b3b698c.
