### ISSUE TITLE
function: Illegal function name '-'

### ISSUE THREAD

**Issue by aureooms** [fish-shell/fish-shell#3810]
- [x] Have you checked if problem occurs with [fish 2.5.0](/fish-shell/fish-shell/releases/tag/2.5.0)?
- [ ] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.5.0

**OS/terminal used**: Arch Linux/Terminator

Seems this function name was allowed before 2.5.0.

## Reproduction steps
1. Open Terminator
2. ...
3. Profit!

## Results
```console
function: Illegal function name '-'
- (line 1): function - --wraps cd --description 'alias -=cd -';  cd - $argv; end
            ^
from sourcing file -
	called on line 68 of file /usr/share/fish/functions/alias.fish

in function “alias”
	called on line 6 of file ~/.config/fish/aliases.fish
	with parameter list “-=cd -”

from sourcing file ~/.config/fish/aliases.fish
	called on line 221 of file /usr/share/fish/config.fish

in function “.”
	called on line 15 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup
```

**Comment by krader1961** [comment]
That's the expected, correct, behavior since function names can't begin with a hyphen. Try this instead: `abbr -a -- - 'cd -'`.

**Comment by krader1961** [comment]
The reason is that it looks like a flag/option to the `function` command.

**Comment by aureooms** [comment]
Your fix works great, thanks!
