### ISSUE TITLE
git config options not tab completing

### ISSUE THREAD

**Issue by adymitruk** [fish-shell/fish-shell#3812]
git config is one of the more frustrating commands to get right. At the very least, it should show --system, --local and --global. But then, it should also auto complete all possibilities like git config log.decorate and core.autocrlf

**Comment by cprieto** [comment]
Git config is pretty long, for example, if we want to do this:

```
git config --<tab> and show [add|replace|unset] etc... 
```

That will be easy but it can be complicated because extended completion as

```
git config <tab>
```

and then show *all* the git config options available (which are a lot of them).

I propose using the simplest right now, just completion of double dash values, what do you think about it?

**Comment by faho** [comment]
From my count, it's about 400 options. That would probably be okay by itself (though of course it'd make the completion script even further if we can't come up with a way to generate it programmatically).

Another solution is to complete _categories_ (i.e. the part before the first ".") first, so it would show 

> advice. (Help messages for new users)

> core. (Core settings)

> color. (Color settings)

and so on.

When you then complete "color.", it'd show

> color.diff (Add color to patches in diff, log, show)

And if you completed that, it would allow a value of `always`, `auto`, `true` and `false`.

Note that this is a large task if we don't find a way to automate it, so the most important options (not "core.packedGitLimit", which is probably only useful if you're paying people to know about it, but stuff like color or gpg signing or maybe even autocrlf) are okay as a first pass.
