### ISSUE TITLE
add support to blacklist commands from being added to the history

### ISSUE THREAD

**Issue by fbarriga** [fish-shell/fish-shell#3815]
What do you think about having the option to have a blacklist (via a regex?) to avoid storing some commands on the history (for security reasons/privacy) ? This is handy if you're sharing your screen with somebody and you don't want to show by mistake some commands that you have executed previously.

Some use cases:
- $ mongo admin -u user -p 'super_secret'
- $ curl https://my_public_server.org/hidden_path/
- $ mpv ~/music/best_of_spice_girls/*
- $ cd ~/torrents/the_pirate_bay/
- $ cd ~/Documents/donkey_shows/

**Comment by krader1961** [comment]
Note that fish already supports the same mechanism that bash and zsh provide for keeping commands from being put in the history: just begin it with a space. We also have a very easy to use `history delete` command. And if I ever get around to finishing the change I've started working on you'll be able to easily and temporarily avoid using any command history at all (see issue #102). I'm not convinced a blacklist has enough utility to justify implementing it.

**Comment by ridiculousfish** [comment]
You can get pretty far building this yourself, e.g.:

```
function cleanup_history --on-event fish_postexec
    set last $history[1]
    if echo $last | grep -q nope
      history delete --exact --case-sensitive -- "$last"
    end
end
```

This is complicated by the fact that the last history item is not the command most recently executed, but the one before that, so the deletion is lagged by one command.

**Comment by zanchey** [comment]
This is a non-answer, but I want to remind other users reading this question that entering any password on the command line is not safe if there are other users on your system - the arguments to any program are accessible to all other local users on most operating systems that fish runs on.

**Comment by fbarriga** [comment]
Thanks for all the answers.
I didn't know that the `history` command was so easy to use and the trick of using a whitespace before a command to avoid storing it on the history.
I think that blacklisting history doesn't make too much sense now.

ps: thanks @ridiculousfish for the script.
