### ISSUE TITLE
`-` no longer a valid function name, breaks `alias - 'cd -'`

### ISSUE THREAD

**Issue by oschrenk** [fish-shell/fish-shell#3820]
**fish version installed** *(`fish --version`)*:
2.5.0

**OS/terminal used**:
Build 3.0.20170131-nightly

## Reproduction steps
1. Create alias `alias - 'cd -'`
2. Source config
3. Get error in fish 2.5.0

```
function: Illegal function name '-'
- (line 1): function - --wraps cd --description 'alias - cd -';  cd - $argv; end
            ^
from sourcing file -
        called on line 68 of file /usr/local/Cellar/fish/2.5.0/share/fish/functions/alias.fish

in function 'alias'
        called on line 5 of file ~/.config/fish/aliases.fish
        with parameter list '- cd -'

from sourcing file ~/.config/fish/aliases.fish
        called on standard input
```

As I used this alias quite often it would be lovely to get it back. Any workaround?

**Comment by krader1961** [comment]
Sorry about that. That function name was always meant to be invalid but was inadvertently valid due to a mistake in the implementation. It was fixed as a byproduct of other changes. Do this instead: `abbr -a -- - 'cd -'`.
