### ISSUE TITLE
history race failure

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3825]
When I merged a simple code style cleanup the Travis macOS (OS X) tests failed with 

```
Testing history race conditions
Error: Item dropped from history: 7815 222
Error: Expected 2561 items, but instead got 2560 items
Testing history_sample_fish_1_x
```

The OS in this case is probably not relevant as a race condition failure is likely to occur on multiple platforms. The challenge is how to both increase the likelihood of triggering this failure and determine the root cause. Since I could not find any previous reports of this failure mode it is presumably rare.

**Comment by ridiculousfish** [comment]
Yes, the history doesn't handle heavy contention exactly right. I have a fix for it that I've been holding onto. I'll merge it later today.

**Comment by krader1961** [comment]
FWIW, the history race test fails with much greater frequency on my FreeBSD 12 VM than any other environment I use to test fish behavior. Out of eight test runs three failed this specific test.

**Comment by faho** [comment]
We don't really see this often. If there is a specific race we can work on it, but I don't see the use in keeping this open.
