### ISSUE TITLE
function name starting with `-`

### ISSUE THREAD

**Issue by wprater** [fish-shell/fish-shell#3827]
**fish version installed** *`2.5`*:

I used to be able to create a function/alias like such `alias - 'cd -'`, but now there is an issue, do I need to escape it in some way, or would this no longer be supported?

```
function: Illegal function name '-'
- (line 1): function - --wraps cd --description 'alias - cd -';  cd - $argv; end
            ^
from sourcing file -
	called on line 68 of file /usr/local/Cellar/fish/2.5.0/share/fish/functions/alias.fish

in function 'alias'
	called on line 2 of file ~/.config/fish/aliases.fish
	with parameter list '- cd -'

from sourcing file ~/.config/fish/aliases.fish
	called on line 141 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup
```

**Comment by krader1961** [comment]
Do this instead: `abbr -a -- - 'cd -'`

**Comment by wprater** [comment]
thank you. I was searching around trying to find an alternative.

**Comment by krader1961** [comment]
N.P. I'm going to add it to the fish FAQ. And while you can search for `cd -` in this project in github  it actually ignores the `-` and just returns every issue containing the word `cd` which isn't particularly helpful. Unless you happen to notice the subject lines that indicate this has been asked before :smile:
