### ISSUE TITLE
git checkout tab completions should show local branches first

### ISSUE THREAD

**Issue by danielcompton** [fish-shell/fish-shell#3830]
- [x] Have you checked if problem occurs with [fish 2.5.0](/fish-shell/fish-shell/releases/tag/2.5.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:

```
fish, version 2.5.0
```
**OS/terminal used**:

macOS 10.12.2 (16C67)
iTerm2 Build 3.0.10

Talk about the the issue here.

## Reproduction steps
1. Develop on a repo with many remote branches, but only a handful of local branches
2. Type `git checkout <tab>`

https://asciinema.org/a/7xgdf4fcji8icta5vcjd6tqyf

## Expected

The local branches in my repo that I see when I run `git branch` are sorted to the top of the completions list (sorted by recency of use, recency of commit, or alphabetically, not sure exactly), with remote branches sorted below, and tags at the bottom.

## Actual

Branches are sorted alphabetically, with remote branches sorted together with local branches. Tags are sorted at the bottom.

I'm sorry if this is a duplicate issue, I had a look and couldn't find anything covering this specific case. Relates to #361, #675, #2628.

**Comment by krader1961** [comment]
Note that this can't be implemented until issue #361 is addressed.

**Comment by aristidesfl** [comment]
@krader1961 #361 is now closed. Has it been addressed?

**Comment by krader1961** [comment]
@aristidesfl, the fix for #361 is in the git `major` branch. That is, it's staged for the upcoming fish 3.0 release. If you build from source after doing `git checkout major` you can take advantage of the new `--keep-order` / `-k` flag for the `complete` command. This specific issue hasn't been addressed but a related one for the `git commit` command was done in commit 34c2bf0f55673d6a89d24705a9aa68afeaa9944e.

**Comment by mqudsi** [comment]
I just merged bca17db96ebb8bfb70223ed5f21e711a33dc5251 which uses `complete -k` to preserve the internal ordering of branch/tag listings.

The order of completion _categories_ themselves for the command is not being explicitly specified (as in remote before local, etc) but the completions are no longer being mixed together (i.e. mixing remote and local branches together) and the order within completion categories is preserved (not alphabetical).

@zanchey what do you think, can we close this?

**Comment by Anenth** [comment]
Doesn't it autocomplete if am using an alias? eg `gco `

**Comment by faho** [comment]
@Anenth: Due to #1976, aliases can only be completed like the main command. So `gco` will be completed like `git`. I recommend using abbreviations instead.

**Comment by mqudsi** [comment]
@faho can we get tags below branches? local branches are currently above remote branches, so that's all what's left here.

**Comment by faho** [comment]
>can we get tags below branches?

So you mean if I do  `git checkout <TAB>`, I get local branches, then tags, then remote branches? (Note that this might require making a second `git branch` call again)

Which other commands should this apply to, btw? Should they have the same order?

**Comment by mqudsi** [comment]
I meant local branches, remote branches, then tags. Unless you think tags are more used than remote branches? The problem with tags is that you generally only want the latest (unless you know the exact tag you wanted beforehand), and there can be so many of them that they push everything else out of view, imho.

**Comment by jduan** [comment]
Is there a way to configure it such that tab autocompletion **ONLY** looks like local branches? That will save me a lot of time when working with large repos. Thanks!

**Comment by faho** [comment]
@jduan: You can search the description in the pager. E.g. enter `git checkout <TAB>`, press ctrl-s, enter "local" and it should only show local branches.

You don't, in general, want to limit completions so that you _don't_ see anything.

**Comment by jduan** [comment]
@faho thanks for your reponse! `Ctrol-S` doesn't seem to work for me. There's still a long pause before it becomes responsive again.

**Comment by faho** [comment]
The idea is that it does all the completions, and then you filter it with ctrl-s. So it'll of course take the exact same amount of time.

The solution for that is #23, not limitting candidates arbitrarily.

**Comment by faho** [comment]
c27c8801af0b418bb5afc61693a43c595dac0305
