### ISSUE TITLE
return w/o output in function causes issues when used as a subcommand

### ISSUE THREAD

**Issue by soumya92** [fish-shell/fish-shell#3831]
- [X] Have you checked if problem occurs with [fish 2.5.0](/fish-shell/fish-shell/releases/tag/2.5.0)?
- [X] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.5.0

**OS/terminal used**: macOS 10.12, iTerm2 3.0.14

If a function "return"s without any output, it can't be used as a subcommand for output capturing. The example does a much better job of explaining the issue.

## Reproduction steps
1. A function that returns without output, e.g. `function t; if [ "$argv[1]" = "ret" ]; return; end; echo ''; end`
2. Use it as a subcommand, e.g. `echo XX(t)XX` and `echo XX(t "ret")XX`

## Results
```console
~ $ function t; if [ "$argv[1]" = "ret" ]; return; end; echo ''; end
~ $ echo XX(t)XX
XXXX
~ $ echo XX(t "ret")XX

```

**Comment by krader1961** [comment]
That is the expected behavior. Fish uses a [cartesian-product](http://fishshell.com/docs/current/index.html#cartesian-product) algorithm for interpolating variable and command expansion output. You should use an intermediate `set` command and additional checks to avoid that behavior.

**Comment by soumya92** [comment]
Huh. Fair enough. Just bit me when coming from a different shell :)
