### ISSUE TITLE
write program to validate language translations have correct format specifiers

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3835]
Issue #3834 was the result of a typo in the German language translation -- a `%s` was used in the translated message where `%d` was needed. While fixing that I noticed, and fixed, several similar errors; e.g., `%s` where it should have been `%ls`. We should write a program, probably in Python, to automate validating the translated strings have the same format specifiers.

**Comment by faho** [comment]
As I've noted in https://github.com/fish-shell/fish-shell/commit/f27407bbf962d45cd4b7248bac7943de873a5f37, GNU's `msgfmt` (which we use to build the translations) has various "--check" flags, among them "--check-format".

This should probably be enabled.

TBD remains how this works on macOS, and if that option can just always be enabled in the build or if it should be part of the tests.

**Comment by krader1961** [comment]
I installed the gettext package on Ubuntu and ran `msgfmt --check-format de.po`. It did find the error on line 338. But it didn't catch any of the other five format errors I found. And there may be errors I didn't find because I was doing it by eyeballing the text. So running `msgfmt --check-format` is better than nothing but not by much.

**Comment by faho** [comment]
This is checked in https://github.com/fish-shell/fish-shell/blob/master/tests/checks/check-translations.fish, which uses msgfmt.
