### ISSUE TITLE
Some ncurses programs not resizing on terminal size change

### ISSUE THREAD

**Issue by ferreum** [fish-shell/fish-shell#3839]
- [Yes] Have you checked if problem occurs with [fish 2.5.0](/fish-shell/fish-shell/releases/tag/2.5.0)?
- [Yes] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version**: anything including and after commit 2be1288

**terminal**: Tested in urxvt, xterm, tmux

**affected applications**: ranger, ncdu

I bisected this to commit 2be1288. From this commit on, the environment variables LINES and COLUMNS are exported by fish. Some ncurses programs seem to use these instead of the actual terminal size if they are set.
The programs work correctly when starting them with `env -uLINES -uCOLUMNS ranger`.

## Reproduction steps
1. start fish
2. start ranger or ncdu
3. resize the terminal

## Results
The application repaints as if the size hadn't changed. This causes only a small area of the terminal being used (if the size was increased), or a chaotic screen (if the size was reduced).

**Comment by krader1961** [comment]
My bad. Those vars should not be exported when referenced if they were not already exported. In that case they are meant to be private to that fish shell. Thanks for reporting this.
