### ISSUE TITLE
mount -t completions fail on FreeBSD

### ISSUE THREAD

**Issue by asomers** [fish-shell/fish-shell#3841]
- [x] Have you checked if problem occurs with [fish 2.5.0](/fish-shell/fish-shell/releases/tag/2.5.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
2.5.0

**OS/terminal used**:
FreeBSD/any

Talk about the the issue here.
`share/functions/__fish_print_filesystems.fish` contains a Linuxism.  The `mount.*` helpers are Linux specific.  On FreeBSD, they're called `mount_*`, a convention that dates to 386BSD if not older.

## Reproduction steps
1. type "mount -t" and press tab.
2. Various filesystems should be listed.  Instead, an error appears.

> No matches for wildcard '$PATH/mount.*'.
> /usr/local/share/fish/functions/__fish_print_filesystems.fish (line 1): string replace -ra ".*/mount." "" -- $PATH/mount.*
>                                                                                                              ^
> in command substitution
> 	called on line 1 of file /usr/local/share/fish/functions/__fish_print_filesystems.fish
> 
> in function '__fish_print_filesystems'
> 	called on standard input
> 
> in command substitution
> 	called on standard input
> 

For now, I've worked around the issue by patching that file in FreeBSD's build system.  It's effective if inelegant, but the same bug likely affects other operating systems.  It would be better to fix the bug here, but I can't find any other examples of fish function or completion files that get modified during the build.
Downstream bug: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=216032

**Comment by krader1961** [comment]
I happened to be investigating a different problem on FreeBSD 12.0 when this was opened and can confirm this is a bug.

@asomers: We would love to see you submit a patch for review and merging. You're obviously someone who cares about making fish behave better on FreeBSD and we would love to see someone like yourself contributing FreeBSD platform specific improvements.
