### ISSUE TITLE
do not assume /tmp is a valid location for temporary files

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3845]
We have places in our code that assume */tmp/* is a valid location for temporary files. That is an invalid assumption. Such as when running in [Termux](https://termux.com/) for Android devices. PR #3604 was opened to address this but the initial change had some issues and the author of change has not addressed the problems in the 2.5 months since the pull-request was created. So I'm opening this issue to remind us to fix this sooner rather than later.

The recommended sequence is using the $TMPDIR env var if it's defined, else the P_tmpdir macro from stdio.h if it is defined, else _PATH_TMP from paths.h. This should be implemented as a function that everyplace that needs to create a temporary file can call.

**Comment by nyeecola** [comment]
I would like to try and fix this issue, but I'm new here so I have a few questions.

Should I use `env_universal_t` to store a global variable for the /tmp/ path?
Also, I saw that in the previous merge request (the one that was closed for inactivity), _PATH_TMP is defined in a GNU header called <paths.h>. Is it safe to assume that every platform we build has that same header? If not, won't that break the build?

**Comment by krader1961** [comment]
@nyeecola, Thank you for taking an interest in improving fish. You should not create or rely on a universal variable for this issue. This [PR comment](https://github.com/fish-shell/fish-shell/pull/3604#issuecomment-268436509) documents the best practice for deriving a temporary file directory. What is needed is an API within fish that can be called to return a directory for temporary files.

**Comment by nyeecola** [comment]
@krader1961 Ok, I'll do as you say.

But if you don't mind me asking, why is it not okay to create a global variable for this? You don't need to answer this if you don't want to. (or don't have time)

Anyway, I'll try to fix this as soon as I can. (Probably next week.)

**Comment by krader1961** [comment]
A universal variable is not the same thing as a global variable in fish. Creating a C++ variable with global scope might be okay. But since we also need a function that can be handed a path relative to the temp dir and which returns an absolute path prefixed with the correct temp directory it probably makes more sense to create another function that returns just the temp dir path name. Global variables should, in general, be avoided.
