### ISSUE TITLE
is `node = NULL` assignment in lru.h necessary?

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3849]
While running `make lint-all` I noticed this warning from cppcheck:

```
[src/lru.h:96] warning (uselessAssignmentPtrArg):
 Assignment of function parameter has no effect outside the function. Did you forget dereferencing it?
```

The statement, `node = NULL;`, at line 96 in *src/lru.h* looks like a no-op to me. It was introduced recently by commit e52a04e34. Does that assignment serve some purpose? It looks like magic to me :smile: Replacing it with an explicit `delete node` causes a fatal error with `make test`:

```
Testing LRU cache
fish_tests(76616,0x10ea2f3c0) malloc: *** error for object 0x7fdc363007d8: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
make: *** [test_low_level] Abort trap: 6
```

**Comment by ridiculousfish** [comment]
`node` is a dangling pointer here - nulling it out makes sense to me, the same way you might null out a pointer after `free`ing it. What would you advise in this case?

**Comment by krader1961** [comment]
> What would you advise in this case?

I don't know. Since `node` isn't referenced in `evict_node()` past line 96 the assignment does not appear to serve any purpose. But I'm speaking as someone who is comfortable with C but not C++. It seems to me the assignment is a noop.

**Comment by ridiculousfish** [comment]
I removed it. Thanks for filing this.

**Comment by ridiculousfish** [comment]
> Does that assignment serve some purpose? It looks like magic to me 😄 Replacing it with an explicit delete node causes a fatal error with make test

To answer this question, node points to an entry in the node map. The call `node_map.erase(node->iter)` causes the map to delete the node. The NULL assignment only aspired to make it clear that `node` was dangling after the call to erase().
