### ISSUE TITLE
alias function not correctly extracting and sanitizing the first word of the command being aliased

### ISSUE THREAD

**Issue by jrduncans** [fish-shell/fish-shell#3860]
- [x] Have you checked if problem occurs with [fish 2.5.0](/fish-shell/fish-shell/releases/tag/2.5.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: fish, version 2.5.0

**OS/terminal used**: MacOS, iterm2

If you define an alias where the first word of the command ends in a semicolon, the resulting function isn't defined quite right and errors are printed

## Reproduction steps
1. `alias foo "echo 'foo'"`
2. `alias bar "foo; and echo 'bar'"`
3. bar

## Results
```console
~ $ bar
fish: Unknown command '--description'
in function 'bar'
	called on standard input

foo
bar
```

**Comment by jrduncans** [comment]
```console
~ $ functions bar
function bar
	--description alias\ bar\ foo\;\ and\ echo\ \'bar\';  foo; and echo 'bar' $argv;
end
```

**Comment by krader1961** [comment]
Note that this would have been slightly easier to diagnose if issue #1625 were addressed.
