### ISSUE TITLE
set $MANPATH globally instead of locally in the man function

### ISSUE THREAD

**Issue by nhooyr** [fish-shell/fish-shell#3862]
- [x] Have you checked if problem occurs with [fish 2.5.0](/fish-shell/fish-shell/releases/tag/2.5.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: fish, version 2.5.0-170-g0970cc8

**OS/terminal used**: macOS 10.12.3 iTerm 3.0.14

See `type man`. Since `$MANPATH` is only set locally in the function, trying to access the fish manpages in neovim through its man plugin does not work because it cannot find them. This is very easy to fix, just set `set -xg MANPATH "$__fish_datadir/man"`. I think this should be done as a default instead of making the user.

Also, in the `man` function, the line setting `$MANPATH` is 
```
set -l fish_manpath (dirname $__fish_datadir)/fish/man
```
😄

**Comment by krader1961** [comment]
The current behavior is deliberate. We do not want to pollute the global man name space with fish commands. Is there some reason you can't simply add these lines to your *config.fish*?

```
set MANPATH (dirname $__fish_datadir)/fish/man:$MANPATH
```

**Comment by nhooyr** [comment]
Not every user knows that they need to add that. Having it work out of the box would be nice. I think it's worth the better user experience.

Also, that last sentence was a joke because the line can be simplified to just 

```
set -l fish_manpath "$__fish_datadir/man"
```

so I really only would need to set

```
set -xg MANPATH "$__fish_datadir/man:$MANPATH"
```

**Comment by ridiculousfish** [comment]
We don't set fish's man path in the MANPATH so that if you invoke bash from fish and then run `man set`, you see the bash man page instead of fish.

bash is not so polite to fish of course :)

**Comment by nhooyr** [comment]
Alright, fair enough. I'll try and get a change merged into neovim to make it work seamlessly.
