### ISSUE TITLE
making Makefile honor gettext LINGUAS

### ISSUE THREAD

**Issue by gyakovlev** [fish-shell/fish-shell#3863]
- [X] Have you checked if problem occurs with [fish 2.5.0](/fish-shell/fish-shell/releases/tag/2.5.0)?
- [X] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.5.0

**OS/terminal used**: Gentoo Linux/any

Hi!
I'm working on this [gentoo bug](https://bugs.gentoo.org/show_bug.cgi?id=409969)
Is it possible to make fish's configure/Makefile support gettext linguas variable?
Iet's say I'd like to pass ```env LINGUAS="de" ./configure``` and have fish install only 
_de/LC_MESSAGES/fish.mo_, but not for other languages.

It's certainly possible to delete unwanted files before install but Gentoo's going away from  adding such hacks to packages if possible.
Is it something you are open to work on?

## Reproduction steps
1. ```env LINGUAS="de" ./configure --with-gettext; make; make install```
2. po files are installed into localedir regardless of LINGUAS variable

PS. Building --without-gettext works fine and fish does not install any mo files at all, that works fine.

**Comment by krader1961** [comment]
We're probably not interested in making this change ourselves given that we have just a handful of translations, the translation files are small, and thus installing all of them is not much of a burden on a distro. We'd be willing to accept a patch from the Gentoo community if someone wants to do the work to implement this.

**Comment by gyakovlev** [comment]
That is definitely not a burden, but it's considered as a bug in Gentoo and there are control freaks using the system who want to this to work correctly =)
Thanks for explanation.
I'll try to dig a bit deeper into this and contribute a solution.

**Comment by zanchey** [comment]
[The Gettext manual](https://www.gnu.org/software/gettext/manual/gettext.html#Installers) documents this variable.
