### ISSUE TITLE
configure does not test for ncurses headers

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#3866]
- [X] Have you checked if problem occurs with [fish 2.5.0](/fish-shell/fish-shell/releases/tag/2.5.0)?
- [X] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
git head

**OS/terminal used**:
Ubuntu

Talk about the the issue here.

## Reproduction steps
1. `autoreconf`
2. `./configure`
3. `make`

## Results
Build fails during make if `libncurses-dev` is not installed. Installing libncurses-dev then compiling again with `make` still fails, one must call `./configure` again then recompile.

**Comment by krader1961** [comment]
It looks to me like it checks for ncurses headers and libs. See these lines in *configure.ac*:

```
AC_SEARCH_LIBS( setupterm, [ncurses tinfo curses], , [AC_MSG_ERROR([Could not find a curses implementatio...

AC_CHECK_HEADERS([getopt.h termios.h sys/resource.h term.h ncurses/term.h ncurses.h ncurses/curses.h ...
```

So I'm guessing what you're really reporting is that we don't fail the initial `./configure` invocation if no curses implementation can be found.

@zanchey, Care to comment? I'm no autoconf expert but is that really the responsibility of  the configure step? Is it even feasible or practical to make configure fail if it fails to find a mandatory dependency?

**Comment by zanchey** [comment]
@mqudsi, could you give us more information about how Make fails? In particular, a copy of the terminal output for the steps you run above would be helpful.

Generally speaking `./configure` should fail if the ncurses libraries are not available. It does on my system. When this happens no Makefile is generated, so `make` won't work until you re-run `./configure`.

If that's not what's happening, we can look into why.

**Comment by mqudsi** [comment]
`./configure` actually fails to find any headers for ncurses, but then succeeds. `make` obviously then fails.

[make.txt](https://github.com/fish-shell/fish-shell/files/802086/make.txt)
[configure.txt](https://github.com/fish-shell/fish-shell/files/802087/configure.txt)

**Comment by zanchey** [comment]
`configure` certainly should try and bail out if mandatory dependencies are not found; I'm surprised we didn't hit this with #1322.

**Comment by zanchey** [comment]
I can reproduce this on an Ubuntu system with `libtinfo-dev` installed but not `libncurses5-dev`. I think the problem is similar to #2952 - `AC_SEARCH_LIBS` checks for the ability to link a function, not whether it is defined.
