### ISSUE TITLE
rbenv init - : Unexpected end of string, square brackets do not match

### ISSUE THREAD

**Issue by ElijahLynn** [fish-shell/fish-shell#3868]
- [ ] Have you checked if problem occurs with [fish 2.5.0](/fish-shell/fish-shell/releases/tag/2.5.0)?
- [ ] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*: 2.4.0

**OS/terminal used**: Ubuntu 14.04/Guake/rbenv 1.1.0

## Reproduction steps
1. I originally opened the issue here https://github.com/rbenv/rbenv/issues/973
2. Basically when I add `status --is-interactive; and source (rbenv init -|psub)` to my config.fish, which evaluates to:
```
setenv PATH '/home/elijah/.rbenv/shims' $PATH
setenv RBENV_SHELL fish
source '/home/elijah/.rbenv/libexec/../completions/rbenv.fish'
command rbenv rehash 2>/dev/null
function rbenv
  set command $argv[1]
  set -e argv[1]

  switch "$command"
  case rehash shell
    source (rbenv "sh-$command" $argv|psub)
  case '*'
    command rbenv "$command" $argv
  end
end
```
3. When launching a new shell I get:

```
Unexpected end of string, square brackets do not match
/tmp/.psub.FyzEPvHVma (line 7):   set -e argv[1]
                                                             
from sourcing file /tmp/.psub.FyzEPvHVma
        called on line 11 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
        called during startup

source: Error while reading file “/tmp/.psub.FyzEPvHVma”
```
4. I am still trying to debug but figured I would crosslink this here in case anyone has ideas.

**Comment by zanchey** [comment]
It might be worth trying to capture the contents of the psub temporary file. `funced psub` to edit the autoloaded function in a single shell instance is probably the way to go - does that make sense?

**Comment by ElijahLynn** [comment]
Thanks. I was trying to look at the file but didn't know how to capture it. I was able to edit psub and `cp` the temp file before it erased it. I saw the output and immediately knew what was going on. 

I have my `cat` command wrapped around `pygmetize`. Like this:

```
function cat
	pygmentize -g $argv
end
```

And it outputs colors to the screen, so the output was like this:
```
setenv[39;49;00m [39;49;00mPATH[39;49;00m [39;49;00m[33m'/home/elijah/.rbenv/shims'[39;49;00m [39;49;00m$PATH[39;49;00m
setenv[39;49;00m [39;49;00mRBENV_SHELL[39;49;00m [39;49;00mfish[39;49;00m
```

And I knew that `psub` probably had a `cat` somewhere without the `command cat` that it should. So here is a PR for that #3869.

Thanks!

**Comment by zanchey** [comment]
You almost certainly want to improve your cat function to only output colours when connected directly to a TTY; try:

```fish
function cat
    if command test -t 1
        pygmentize -g $argv
    else
        command cat $argv
    end
end
```

(You need to use `command test` thanks to #1228.)

**Comment by krader1961** [comment]
@zanchey's advice is good in general but this is a case an abbreviation is probably a better choice. That way you can still do `cat some_file | less` and get the colorization without having to worry about your cat function breaking all other uses of cat. Alternatively, and this is what I would do, name your function something like `ccat` (for colorize cat).

**Comment by faho** [comment]
>`source (rbenv "sh-$command" $argv|psub)`

This can just be `rbenv "sh-$command" $argv | source`, no need to invoke psub at all.

**Comment by ElijahLynn** [comment]
Thanks everyone,

Yeah, I was doing `command cat` when I wanted to output to the clipboard. I'll ponder the suggestions to modify cat, make ccat or make an abbreviation for cat.
