### ISSUE TITLE
Import bash history after first run

### ISSUE THREAD

**Issue by f3rn4nd0-c354r** [fish-shell/fish-shell#3870]
- [X ] Have you checked if problem occurs with [fish 2.5.0](/fish-shell/fish-shell/releases/tag/2.5.0)?
- [X ] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version 2.5.0

**OS/terminal used**:
Linux Laguz 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u1 (2017-02-22) x86_64 GNU/Linux

Talk about the the issue here.

I had my zsh/bash history in a custom location when I ran fish for the first time. How can I imported it now?

**Comment by faho** [comment]
The easiest way is probably

- Remove ~/.local/share/fish/fish_history without fish running

- Start fish

**Comment by f3rn4nd0-c354r** [comment]
Can I then "merge" the bash history and my fish history?

**Comment by krader1961** [comment]
No, the procedure recommended by faho does not let you merge your existing fish history with your bash history. The bash history import mechanism assumes you're running fish for the first time and thus there wouldn't be any fish history to merge with the bash history. Similarly we don't provide any way to import "new" bash history if you continue to use bash after running fish for the first time.

You'll have to decide which is more important: keeping your fish history or importing your bash history.

**Comment by f3rn4nd0-c354r** [comment]
Thanks.

**Comment by ridiculousfish** [comment]
Here's something you can try:

1. Move your fish history aside (may be at `~/.local/share/fish/fish_history`)
2. Start a new instance of fish to import your bash history
3. Append your old fish_history to the newly imported one, e.g. `cat ~/saved_history >> ~/.local/share/fish/fish_history`

This ought to just work! Let us know how it goes.

**Comment by f3rn4nd0-c354r** [comment]
It seems it worked!
However... I think now I have duplicate entries...

**Comment by faho** [comment]
Use it some more, fish only flushes the history every once in a while.

**Comment by f3rn4nd0-c354r** [comment]
ok. Thanks!

**Comment by smolin** [comment]
I thought, "how cool would it be if the Bash and Fish histories were unified" so I added this to my ~/.config/fish/config.fish. Not perfect: Bash doesn't know what you've done in Fish, and all Bash history ends up before all Fish history, but better than nothing. (I'm not sure the "history save" commands are necessary),

function prompt_jumble --on-event fish_prompt
  cat ~/.local/share/fish/history-save >> ~/.local/share/fish/fish_history ; history merge ; history save
  functions -e prompt_jumble
end

function on_exit --on-process %self
    history save
    mv ~/.local/share/fish/fish_history ~/.local/share/fish/history-save
end

**Comment by guss77** [comment]
@smolin this looks to be working, but a word of caution - if your bash history is large (my history file is ~5MB), then this slows down fish start very noticeably. On my not at all shabby system, fish takes ~20 seconds to start, everytime, with the "history merge on every startup" functionality.
