### ISSUE TITLE
Can't see path in bash mode

### ISSUE THREAD

**Issue by matthew-groth** [fish-shell/fish-shell#3873]
**fish version installed** *(`fish --version`)*:

fish, version 2.5.0

**OS/terminal used**:

When I switch to bash, I can no longer see my path

## Reproduction steps
1. 'bash'
2. 'cd _anything_'

Path does not appear, forced to constantly type "ls".

**Comment by krader1961** [comment]
Insufficient data. However, try `bash -l` to force a bash login shell. Because that is how it is invoked when it is you login shell which means different config scripts are run compared to a normal interactive shell. If that doesn't fix your problem you'll need to provide more information.

**Comment by matthew-groth** [comment]
`bash -l ` fixed my problem. Thanks!

**Comment by faho** [comment]
@matthew-groth: You probably want to fix your bash configuration - it seems like you're setting your prompt in bash_profile (e.g. ~/.bash_profile or /etc/profile). Instead you'll want to either set it both there and in ~/.bashrc or `source` one file from the other.

**Comment by krader1961** [comment]
More likely is he's setting it in *~/.bash_login* but your point, faho, is still valid that their bash config probably needs to be refactored.

**Comment by faho** [comment]
This might reflect the color of my beard, but I've never seen someone use ~/.bash_login. From my reading of the bash man page, it seems like it's a fallback to bash_profile. Is there anything in particular that uses it?

**Comment by matthew-groth** [comment]
Sorry I am actually a beginner and could use a little more help understanding. Currently, I have to input 'bash -l' in order to see my current directory, and I have to reenter it every time I open a new terminal. I did not have this issue before installing Fish.

I am on MacOSX, which I read somewhere starts in ~/.bash_profile. So I need to switch it to ~/.bashrc? How would I do that? I'm not sure what file I am supposed to edit, but here are copies of two of mine that seem useful, but I am having trouble interpreting:

**/private/etc/profile**

'# System-wide .profile for sh(1)

if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi

if [ "${BASH-no}" != "no" ]; then
	[ -r /etc/bashrc ] && . /etc/bashrc
fi
'

**/private/etc/bashrc**

/# System-wide .bashrc file for interactive bash(1) shells.
if [ -z "$PS1" ]; then
   return
fi

PS1='\h:\W \u\$ '
# Make bash check its window size after a process completes
shopt -s checkwinsize

[ -r "/etc/bashrc_$TERM_PROGRAM" ] && . "/etc/bashrc_$TERM_PROGRAM"

**Comment by krader1961** [comment]
I don't understand. If you don't want fish as your login shell just change it. Depending on what you did to make fish your login shell that might mean removing it from your *~/.bashrc*, or *~/.bash_profile* script. Or you may need to run `chsh -s /bin/bash`.

**Comment by matthew-groth** [comment]
No, I like fish. I just switch sometimes because I'm still learning and sometimes when copy a command from online for bash, it's easier to just put it into bash than convert it to fish syntax. 

I am fine using the command you gave me to see my current directory in bash, so this issue is resolved. I just thought you and @faho were recommending for me to change my bash config.

**Comment by krader1961** [comment]
If you look at the bash man page (`man bash`) you'll see that there are multiple config scripts bash may read from depending on how it is started. The wording isn't very clear but basically it won't read *~/.bash_profile* or *~/.bash_login* unless started with the `-l` (or `--login`) flag. So if you're defining your prompt in one of those files then just running `bash` won't use that definition. Things you always want done when starting an interactive shell, whether it is a login shell or not, should be put in your *~/.bashrc* file.

**Comment by matthew-groth** [comment]
ok, thanks for the tip!
