### ISSUE TITLE
test: Missing argument at index 2 when using fish_vi_key_bindings, tmux

### ISSUE THREAD

**Issue by danzimm** [fish-shell/fish-shell#3876]
- [x] Have you checked if problem occurs with [fish 2.5.0](/fish-shell/fish-shell/releases/tag/2.5.0)?
- [x] Tried fish without third-party customizations *(check `sh -c 'env HOME=$(mktemp -d) fish'`)*?

**fish version installed** *(`fish --version`)*:
fish, version 2.5.0

**OS/terminal used**:
macOS 10.12.1, Terminal and iTerm Build 3.1.beta.1

Talk about the the issue here.

## Reproduction steps
1. In .config/fish/fish.config add the line `fish_vi_key_bindings`
2. Open a new instance of fish
3. Spawn tmux
4. See error test: Missing argument at index 2

The culprit is line 38 of `fish_vi_cursor.fish`:
```fish
or test (string replace -r "XTerm\((\d+)\)" '$1' -- $XTERM_VERSION) -ge 280
```
which errors due to `XTERM_VERSION` not being set.

The fix I found was to change this to
```fish
or begin
    set -q XTERM_VERSION
    and test (string replace -r "XTerm\((\d+)\)" '$1' -- $XTERM_VERSION) -ge 280
end
```

**Comment by faho** [comment]
One thing I don't quite understand here is why $ITERM_PROFILE isn't set, which is checked before.

Either way, that was a gap in the checks.
