### ISSUE TITLE
Debian 7 is no longer supported?

### ISSUE THREAD

**Issue by geraldus** [fish-shell/fish-shell#3880]
Hi folks!

I'm trying to install __fish__ on Debian 7.  All guides suggest me to add: `http://download.opensuse.org/repositories/shells:/fish:/release:/2/Debian_7.0/` to sources list.

However, there is no `Debian_7.0` directory in `http://download.opensuse.org/repositories/shells:/fish:/release:/2/`.  Does this mean __fish shell__ no longer supports Debian Wheezy? 

### [SOLUTION]

It is possible to install **fish 2.4.0** on Debian 7.  It is the latest applicable version for Wheezy.  
Also, **python** is required for auto-generated command completions and the `fish_config` command.

Follow [these instructions][instructions] for **Debian 7** and **RHEL** 5 & 6.

#### Debian 7 use case

Debian repository URL provided in instructions is wrong because of missing slash.  
The correct URL is:
```
http://download.opensuse.org/repositories/shells:/fish:/release:/2:/2.4.0/Debian_7.0/
```
So, correct example should be:
```bash
echo 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/2:/2.4.0/Debian_7.0/ /' > /etc/apt/sources.list.d/fish.list 
apt-get update
apt-get install fish
```

```
root@ffccad29e8f8 /# fish --version
fish, version 2.4.0
```

[instructions]:https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A2%3A2.4.0&package=fish

**Comment by faho** [comment]
This is unfortunately true. See the release notes for 2.6.0:

>Starting with version 2.5, fish requires a more up-to-date version of C++, specifically C++11 (from 2011). This affects some older platforms:
Linux

>For users building from source, GCC's g++ 4.8 or later, or LLVM's clang 3.3 or later, are known to work. Older platforms may require a newer compiler installed.

>Unfortunately, because of the complexity of the toolchain, binary packages are no longer published by the fish-shell developers for the following platforms:

    Red Hat Enterprise Linux and CentOS 5 & 6 for 64-bit builds
    Ubuntu 12.04 (EoLTS April 2017)
    Debian 7 (EoLTS May 2018)

>Installing newer version of fish on these systems will require building from source.

Wheezy has gcc 4.7, while we need 4.8 for C++11 support.

**Comment by zanchey** [comment]
It looks like the 2.4.0 binaries were removed when 2.5.0 was published, but I kept a copy so I will upload them somewhere - then you can at least get some version of fish running.

**Comment by geraldus** [comment]
Thank you for fast reply!

I'll try existing binary from __Files__

**Comment by zanchey** [comment]
Do not use 2.1. It contains a number of serious security problems which can allow others to take over your system.

**Comment by geraldus** [comment]
Wow.  Good to know.  But I think it's OK to use it inside docker container.  Can you ping me when you'll upload v2.4?  Feel free to close this (or close this after upload).

**Comment by zanchey** [comment]
Could you try the Debian packages from https://github.com/fish-shell/fish-shell/releases/tag/2.4.0 ?

**Comment by geraldus** [comment]
@zanchey 
I've tested and complains about `libc` and `libstdc++6`:

```
Unpacking fish (from .../fish2/fish_2.4.0-2_amd64.deb) ...
dpkg: dependency problems prevent configuration of fish:
 fish depends on libc6 (>= 2.15); however:
  Version of libc6:amd64 on system is 2.13-38+deb7u11.
 fish depends on libstdc++6 (>= 4.9); however:
  Version of libstdc++6:amd64 on system is 4.7.2-5.
 fish depends on fish-common (= 2.4.0-2); however:
  Package fish-common is not installed.
```

**Comment by geraldus** [comment]
@zanchey can you upload a new version compiled with proper libraries if it's ever possible?

**Comment by krader1961** [comment]
Debian 7 went EOL eleven months ago and is currently receiving only security fixes if I'm reading the Debian support page correctly. On the other hand it was released in 2013 so I'm very surprised it doesn't have the minimum C++11 support we need. Regardless, we're definitely not going to expend any effort trying to get anything newer than fish 2.4.0 working on that platform. And maybe not even 2.4.0 if doing so is going to require creating a custom package just for Debian 7. But that's up to @zanchey since he wrangles our prebuilt packages.

@geraldus, I'm curious. Have you been using any version of fish successfully on that platform or are you trying to use fish for the first time on that platform? If we told you how to get the fish 2.4.0 source code installed on your system and the commands to run to build a binary would that be sufficient?

**Comment by geraldus** [comment]
@krader1961 I use fish shell for a quite long time already and I absolutely love it.  And yes, I've used fish on Debian 7 early, moreover it was version 2, but I can't remember exact version.  Let me explain current situation a bit: usually I keep everything up to date (or even using edge packages), however I have to use a VPS where Debian 7 installed.  That server is managed by other people than me and they scare to upgrade things.

**Comment by zanchey** [comment]
Right, I uploaded the packages from Debian 8 instead of Debian 7. Sorry. I'll see what else I can try.

**Comment by faho** [comment]
@zanchey: Have you had any progress on this?

Also, has anyone actually tried gcc 4.7 to confirm it doesn't work?

**Comment by zanchey** [comment]
Yes!

https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A2%3A2.4.0&package=fish should work for RHEL 5 & 6 and Debian 7.

Perhaps we can add this to the fishshell website as "legacy downloads" or similar - could include the old OS X packages as well.

**Comment by zanchey** [comment]
@geraldus, any luck with those packages?

**Comment by geraldus** [comment]
@zanchey Hey Hey!

Soooory for such loooong response!  Finally, I have built test image with Debian 7 and tested packages you mentioned.  I was not able to accomplish this part of instructions:
```
echo 'deb http://download.opensuse.org/repositories/shells:/fish:/release:/2:2.4.0/Debian_7.0/ /' > /etc/apt/sources.list.d/fish.list 
apt-get update
apt-get install fish
```
because of `http://download.opensuse.org/repositories/shells:/fish:/release:/2:2.4.0/Debian_7.0/` is not available (error 404).

I tried then to follow a second part of manual
```
wget -nv http://download.opensuse.org/repositories/shells:fish:release:2:2.4.0/Debian_7.0/Release.key -O Release.key
apt-key add - < Release.key
apt-get update
```
and install `fish`.  Fish shell was installed indeed, but `fish --version` shown me version `1.23`.

Finally, I tried to grab binary directly and install it via `dpkg`.  This does not succeeded, because missing `fish-common` dependency.  I tried to install it via `apt-get`, but without success with following error:
```
E: Unable to locate package fish-common
```

**Comment by zanchey** [comment]
It looks like there's a slash missing in the instructions, which are automatically generated.

Try http://download.opensuse.org/repositories/shells:/fish:/release:/2:/2.4.0/Debian_7.0/ as the URL instead.

**Comment by geraldus** [comment]
Oh, great!  Will be able to test it in 15–20 hours.

**Comment by geraldus** [comment]
@zanchey ah I didn't catch from the beginning which slash are you talking about.  Just to clarify for other people there is indeed missing slash between `/release:/2:` and `2.4.0`.

Ok, I was able to install **fish** and it works, though with error message on startup:

Version check
```
root@ffccad29e8f8 /# fish --version
fish, version 2.4.0
```

Also I've found that **python** is required too because **fish** uses it under the hood.

Thank you very much @zanchey !

**Comment by krader1961** [comment]
What error message, @geraldus? It is not clear from your comments what "error message on startup" you are seeing.

Also, fish has required python for auto-generated command completions and the `fish_config` command for quite a while.

**Comment by geraldus** [comment]
I will edit issue description adding actual solution and close it.  You may refer to this issue somewhere.

**Comment by geraldus** [comment]
@krader1961 oh, sorry I left mention of error by mistake.  I've edited my comment and removed it.  Indeed, the error was related to missing python command during an attempt to handle completions.

Thank you guys!

**Comment by geraldus** [comment]
I will ping you when I will edit description, I have to go right now!

**Comment by geraldus** [comment]
Closing this.
Ping @zanchey @krader1961 
Thank you guys!
