### ISSUE TITLE
Autocomplete for ifconfig results in a: cd /sys/class/net

### ISSUE THREAD

**Issue by rvanlaar** [fish-shell/fish-shell#3881]
When I tab complete ifconfig's interfaces it changes my cwd (current working directory) to /sys/class/net.
Expected behavior is autocompletion for interfaces but no change in my cwd.

See also: https://asciinema.org/a/c34jiuksxwv71q133e1tgdidz

The regular questions:
Version: fish, version 2.3.1
Uname: Linux MiSus 4.8.0-39-generic #42-Ubuntu SMP Mon Feb 20 11:47:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
TERM: xterm-256col
The bug also works without 3rd party customizations.

**Comment by faho** [comment]
This has already been fixed with 59eb75021bbcc39a0c75ea77bb9dd1382dc22f0e, to be released in 2.6.0.
