### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by lunaryorn** [fish-shell/fish-shell#3883]
Hey folks,

I just went from zsh to fish and I'm really loving it.  So much easier to grok than zsh, way better defaults, much nicer syntax, etc.  Shrunk my shell config to about 10%, with almost similar features.

So, that's it: I just wanted to say thank you from my heart for the awesome work you're doing on this project. I'm really grateful to have fish under my hands every day!

Thanks  👍 👏 ❤️ ❤️ ❤️ 🎆 🎆 🎉

**Comment by geoffmacintosh** [comment]
👍

Not only is fish great, the people maintaining it are great too!

**Comment by faho** [comment]
Aww... you're making us blush.

Of course, if your issue is that fish is too awesome, that's something we won't fix, so I'm closing this 😜 .

**Comment by lunaryorn** [comment]
❤
