### ISSUE TITLE
Odd issue with autosuggestions (gif)

### ISSUE THREAD

**Issue by ElijahLynn** [fish-shell/fish-shell#3885]
Fish 2.4.0

Having an odd issue with my echo command. I did try to echo and 'echo' at one point, I forget what I was doing. I have deleted the offending command from history via the `fish_config` GUI but it persists. 

My `echo` function is not overridden but it is using Fish's version of echo. 

Here is the gif of what is happening. 

![output](https://cloud.githubusercontent.com/assets/1504756/23775060/9980694a-04db-11e7-92a2-b169c759cc18.gif)

**Comment by ElijahLynn** [comment]
Hrm, so I just typed `echo <newtext> + enter` and it appears to have taken precedence in the autosuggestion queue and now the issue no longer happens.

**Comment by ElijahLynn** [comment]
Closing, quite the edge case I am sure. Would be good to find out why but I don't think it needs to be open.

**Comment by krader1961** [comment]
FWIW, you don't need to use the GUI to manage your command history. The `history` command has a nice interactive deletion mode. Try `history delete --prefix echo` (without the `--prefix` it will match any command with `echo` anywhere).

**Comment by ElijahLynn** [comment]
Ahh, nice tip!!!
