### ISSUE TITLE
Nonexistent directories in MANPATH breaks fish_update_completions

### ISSUE THREAD

**Issue by danielcompton** [fish-shell/fish-shell#3889]
# Setup

```
$ fish --version
fish, version 2.5.0
$ echo $version
2.5.0
```

```
$ uname -a
Darwin <hostname> 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
$ echo $TERM
xterm-256color
```

macOS 10.12.3

# Reproduction

It seems like `fish_update_completions` breaks if it is given a path that doesn't exist. This was unexpected to me, as $PATH handles missing directories.

```
$ sh -c 'env HOME=$(mktemp -d) fish'
$>
set -x MANPATH /usr/local/non/existent
$> fish_update_completions
No paths specified
```

**Comment by krader1961** [comment]
It does handle missing directories. The error is telling you that the only directory you specified wasn't valid. When you define `MANPATH` fish uses that without any fallbacks. So if your `MANPATH` value consists solely of invalid directories you get the `No paths specified` error.

**Comment by krader1961** [comment]
Also, note that if instead you had done `set -x MANPATH /usr/local/non/existent:/usr/share/man` then it does ignore your non-existent directory and does parse the man pages below */usr/share/man*.

**Comment by danielcompton** [comment]
Sorry, I see the problem now. The actual problem I was seeing (before I reduced it down for reporting) had several other directories in the MANPATH as well. After checking now, they didn't exist either, but I had also included the `:` to make it search the default paths. When I added the new one as well that must have broken it. Sorry for the interruption.
