### ISSUE TITLE
Making a function named `test` breaks the shell.

### ISSUE THREAD

**Issue by DevJac** [fish-shell/fish-shell#3890]
My fish version is `fish, version 2.5.0`.

When I run `function test; echo hi; end;` in fish the prints lots of errors and no combination of Ctrl-C, Ctrl-Z, etc, can get the shell to be usable again.

I tried running the same command (`function test; echo hi; end;`) in a shell started with `sh -c 'env HOME=$(mktemp -d) fish'` and the shell no longer breaks, but the prompt gets messed up.

It looks like maybe "test" is a reserved function name?

**Comment by krader1961** [comment]
It's not a reserved function name but is the name of a builtin command. Type `man test` at a fish prompt. In general you should not define a function with the same name as a builtin command. Type `builtin --names` to see the list of builtin commands.

See issue #3000 where we're discussing how to keep people from shooting themselves in the foot like this. Unfortunately are first attempt at solving this problem introduced backward compatibility problems.

**Comment by DevJac** [comment]
That makes sense. Thank you for taking the time to explain it to me.
