### ISSUE TITLE
how to log every command with its duration time

### ISSUE THREAD

**Issue by amosbird** [fish-shell/fish-shell#3894]
Hi, how can I log every command with its duration time to a persistent place. It would be even better that we could log sub commands in a hierarchy way.

**Comment by krader1961** [comment]
Define a function which is run when the `fish_postexec` event occurs. For example:

```
function record_runtime --on-event fish_postexec
    echo "cmd_duration: $CMD_DURATION, argv: $argv" >> /tmp/data
end
```

It is not clear what you mean by "sub commands" but you probably mean something like `sleep 3; echo yes` being recorded as two distinct commands when run interactively. I strongly disagree.

I do wonder why the command duration (i.e., execution time) isn't recorded in the interactive command history file. That seems like a useful enhancement.

**Comment by amosbird** [comment]
Nice! Thank you.

**Comment by amosbird** [comment]
Hmm, this has some drawbacks. It cannot record background commands and it records empty command when pressing `return`.

**Comment by krader1961** [comment]
Dealing with an empty command is obvious and trivial. Backgrounded commands require checking if `&` is the last character of the command and defining a function with `--on-job-exit`. See the example in `man function`. Details are left as an exercise for the student.

**Comment by krader1961** [comment]
I think the original question has been answered so I'm going to close this. Whether a function defined with `--on-event fish_postexec` should also be invoked when a backgrounded job completes is an interesting question. If anyone feels strongly in the affirmative I encourage them to open an enhancement request. But before doing so consider what that means for jobs that have been stopped (e.g., via [ctrl-Z]) then restarted (rinse, lather, repeat).
