### ISSUE TITLE
Piping sudo command hides password prompt

### ISSUE THREAD

**Issue by andystanton** [fish-shell/fish-shell#3896]
## System Information

```sh
$ fish --version
fish, version 2.5.0
```

```sh
$ echo $version
2.5.0
```

```sh
$ uname -a
Darwin lagrange2 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
```

```sh
$ echo $TERM
xterm-256color
```

## Steps to reproduce

Tested with both my user fish shell and without third party customisations as recommended in the instructions.

1. Log in as non-root user who has sudo permissions.
2. Pipe sudo command into some other command e.g. `sudo ps -ef | grep anything`

## Expected results

* sudo password prompt is displayed followed by output after password is entered correctly.

## Actual results

* Neither the password prompt nor any other output is displayed.

## Asciinema recording

https://asciinema.org/a/64451vfaa4elwdn1r9yrroc5z

I'm basing my expectations on the behaviour of bash and zsh, but this may be incorrect. Please let me know if this is the case, and if there is a recommended way to achieve the desired behaviour. I could do something like `sudo echo; and sudo ps -ef | grep anything` but that doesn't seem right.

**Comment by krader1961** [comment]
It's a bug due to how using a function on the right hand side of a pipe works in fish. See issues #206 and #1362. For now you'll have to either remove the grep function or use `sudo ... | command grep ...`.
