### ISSUE TITLE
funced the whole .fish file contents, not only function body

### ISSUE THREAD

**Issue by maxfl** [fish-shell/fish-shell#391]
Sometime the <function>.fish file contains not only the function definition, but some variable definitions. Sometimes the function definition depends on a system, so there is if/function/else/function construction.

When funced is invoked it let you edit only the function name, options and body. After applying funcsave all the other information is lost.

It would be very helpful if function could contain the whole contents of the .fish file instead. So when you type funced, you can also modify the preceeding variables, conditions and comments.

**Comment by krader1961** [comment]
This should be easy to do after issue #3295 is implemented.

**Comment by krader1961** [comment]
As discussed in issue #3701 we should do two things:

1) Make it possible to edit the file in which the function was originally defined using the `funced` command.

2) Warn the user about losing their edits if they don't invoke `funced` with the `--save` or `--perm` flag (the flag name is still open for discussion).

To be determined is whether we can, or should, attempt to protect the user from doing `funcsave $func_name` when the file in which the function was defined contains other statements and comments.
