### ISSUE TITLE
fish's `while` doesn't send data immediately to its children

### ISSUE THREAD

**Issue by kristianlm** [fish-shell/fish-shell#3911]
Hi! I'm relatively new to fish and I'm enjoying it a lot. I've come across some surprising behaviour, though, and though I'd ask what's going on. First things first:

```
 ➤  fish --version
fish, version 2.5.0
 ➤ uname -a
Linux kth 4.10.2-1-ARCH #1 SMP PREEMPT Mon Mar 13 17:13:41 CET 2017 x86_64 GNU/Linux
 ➤ echo $TERM 
xterm-256color
```
In `sh` I can do this:

```
 ➤ sh -c 'while true ; do echo hi ; sleep 1 ; done | head -n 1'
hi
```

It prints `hi` immediately, waits about a second and then exits. The same thing with `fish`, however, hangs forever and doesn't print `hi` until I Ctrl-C:

```
 ➤ while true ; echo hi ; sleep 1; end | head -n 1
^Chi
```

Why is this? How can I make `fish` behave like `sh` in this case? Does this have anything to do with how `SIGPIPE` is handled?

**Comment by faho** [comment]
In this case, fish buffers the output. This is a long standing issue - #1396.
