### ISSUE TITLE
bracketed paste causes pasting a string with single-quotes to lose the quotes

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3913]
I was working on a fix for issue #738 and was copying and pasting various `string match` commands. I noticed that if there were single-quotes in the string being pasted they are stripped. That seems suboptimal :smile: For example, if I copy this string to my clipboard:

```
string match -r '^(([ugoa]|)([=+-]|)([rwx]*))(,(([ugoa]|)([=+-]|)([rwx]*)))*$'
```

And then paste it to a fish shell the single-quotes are stripped.

**Comment by faho** [comment]
This was a simple case of a missing escape - single-quotes need to be escaped even inside the COMMAND argument to `bind`.

It seems I neglected to test the case of pasting without single-quoting first over the special one with.

Sorry!
