### ISSUE TITLE
sudo fails in command substitution

### ISSUE THREAD

**Issue by ntsuji** [fish-shell/fish-shell#3921]
```fish
$ fish --version
fish, version 2.4.0
```
I want to do something like this using command substitution.
```fish
sudo ls | xargs echo
```
In other shells, this works correctly.
```bash
echo `sudo ls`
```
In fish, I thought this would work.
```fish
echo (sudo ls)
```
But it does not prompt for password, and `sudo ls` remains as stopped job.

**Comment by krader1961** [comment]
Known issue. See #1362. Work around is to do it like this: `sudo ls | read -z var; echo $var`. Splitting on the newlines is an exercise left for the student :smile:
