### ISSUE TITLE
How to assign value if variable unset/null in fish shell ?

### ISSUE THREAD

**Issue by edouard-lopez** [fish-shell/fish-shell#3926]
### Env

```
$ fish --version
fish, version 2.5.0
```

```
$ uname -a
Linux x1 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
echo $TERM
screen-256color
```

### Question

What is the equivalent of the following bash assignment?

    XYZ=${XYZ:=whatever}

**Comment by faho** [comment]
There's no special-syntax shortcut here, you need to use something like

```fish
set -q XYZ; or set XYZ whatever
```

if the variable needs to be _totally_ undefined for the default value to take effect, or

```fish
set -q XYZ[1]; or set XYZ whatever
```

if it can also be an empty list or

```fish
string length -q -- $XYZ; or set XYZ whatever
# or
test -n "$XYZ"; or set XYZ whatever
```

if it can also be the empty string (which includes the empty list).

**Comment by krader1961** [comment]
Just to clarify @faho's excellent answer.... The specific case of `${var:=val}` is done in fish by the second example:

```
set -q XYZ[1]
or set XYZ[1] "whatever"
```

that will set the first element of `XYZ` to `whatever` if it is either not defined or has no values or the first value is an empty string. That is weird because bash is weird. Do this in bash:

```
x=('' 'second')
set | grep '^x='
echo ${x:=y}
set | grep '^x='
```

Depending on whether or not `$x` is an array in bash the behavior varies. That doesn't happen in fish.

**Comment by edouard-lopez** [comment]
Thanks, could you elaborate on the `XYZ[1]`? Why the array?

**Comment by faho** [comment]
>Thanks, could you elaborate on the XYZ[1]? Why the array?

In fish, every variable is a list. That means, there are two different kinds of what could be called "undefined", and three different kinds of "empty".

See

```fish
# Before any `set` calls, the variable is completely undefined
# All checks including `set -q XYZ` would be false
set -g XYZ # this variable _exists_ - the name is known, but there's nothing in it
# `set -q XYZ` is true, `set -q XYZ[1]` is false
set -g XYZ "" # this variable has one element - the empty string
# `set -q XYZ` true, `set -q XYZ[1]` is true
# `string length -q -- $XYZ` and `test -n "$XYZ" are false 
# (beware of quoting when using test - `test -n $XYZ` is true because `test -n` is!)
set -g XYZ "" "" "" # this variable consists of _three_ empty elements
# Same
set -g XYZ "aaa" # this variable actually has something in it!
# All checks true
```

**Comment by jonlorusso** [comment]
Any chance things have changed in the ~2.5 years since this issue was closed?

**Comment by ridiculousfish** [comment]
If you prefer you can use `||` syntax, e.g. `set -q XYZ || set XYZ stuff` but there's no support for bash-style modified expansion.
