### ISSUE TITLE
Random fish crash at exit

### ISSUE THREAD

**Issue by miqlas** [fish-shell/fish-shell#3928]
Please tell us which fish version you are using by executing the following:

  fish --version
  echo $version

fish, version 2.5.0

Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

Haiku x86_64, Haiku Terminal

uname -a:
Haiku shredder 1 hrev51041 Mar 25 2017 08:25:03 x86_64 x86_64 Haiku

echo $TERM:
xterm

Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:

  sh -c 'env HOME=$(mktemp -d) fish'

NOPE, random crash.

Tell us how to reproduce the problem. Including an asciinema.org recording is useful for problems that involve the visual display of fish output such as its prompt.

1) Start Terminal, fish is already a default shell
2) Close Terminal
3) Goto 1
4) ???
6) PROFIT!

Debug log: https://pastebin.com/raw/8BkTcN2B

**Comment by krader1961** [comment]
The odds are very good that we've already fixed this with commit 56e05dab (PR #3724, Issue #3644). If you can reproduce with fish built from that, or a newer commit, please reopen.
