### ISSUE TITLE
Alias completion

### ISSUE THREAD

**Issue by hauleth** [fish-shell/fish-shell#393]
It will be nice if we can make completion work for aliases too. I.e.

```
function g; git $argv; end
completion -c g --alias git
```

And now everything that will be completed in `git <tab>` will work also in `g <tab>`.

**Comment by najamelan** [comment]
For people wondering about git aliases, I can say that it works if you set your alias in .gitconfig instead of in fish configuration.

**Comment by niedzielski** [comment]
Thanks! This is very convenient! Worth building `master` for!

**Comment by joar** [comment]
This does not seem to solve the issue when you've abbreviated `git add` to `ga`.

Using 
```
function --wraps 'git add' ga
	git add $argv;
end
```
does not help, and using 
```
function --wraps 'git' ga
	git add $argv;
end
```
gives you completions for `git` instead of `git add`. Presumable since the completions for giit sub-commands are defined using conditions, e.g:
```
complete --no-files \
	--command git \
	--arguments '(__fish_git_add_files)' \
	--condition '__fish_git_using_command add'
```

**Comment by zanchey** [comment]
Correct, abbreviations only support the token in command position - see #1976 for some discussion.
