### ISSUE TITLE
Fish populates /usr/local/bin but not /usr/local/sbin to PATH

### ISSUE THREAD

**Issue by samdmarshall** [fish-shell/fish-shell#3930]
I happened to run `brew doctor` today and i got the following message:
```
Warning: Homebrew's sbin was not found in your PATH but you have installed
formulae that put executables in /usr/local/sbin.
Consider setting the PATH for example like so
  echo 'set -g fish_user_paths "/usr/local/sbin" $fish_user_paths' >> ~/.config/fish/config.fish
```

I thought this was odd because I don't recall ever setting `/usr/local/bin` to my path explicitly; and sure enough when i checked my config files, i am not setting `/usr/local/bin` to be included in my PATH at all, but fish seems to automatically populate this correctly. I was able to test out the case of not loading any of my shell config files:
```
env -i HOME=(mktemp -d) /usr/local/bin/fish                                                                                                   [23%]
<E> fish: Could not set up terminal
<E> fish: TERM environment variable not set
<E> fish: Using fallback terminal type 'ansi'

Samantha@Tolva /U/S/P/fish-shell> env
HOME=/var/folders/m5/j4zdc7f9157659_pd5p0_n980000gn/T/tmp.Wbnkxwx4
LC_CTYPE=en_US.UTF-8
PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PWD=/Users/Samantha/Projects/fish-shell
SHLVL=1
TERM=ansi
USER=Samantha
```

and noticed that even then, fish seems to populate my `PATH` with `/usr/local/bin`. I wasn't able to find any references to `/usr/local/bin` explicitly in the fish source code, so i'm wondering if it gets automatically included as the `dirname` of where `fish` lives? If that is the case then I think a warning should be given, because that is rather unexpected behavior (at least from my perspective).

If this is not the case, and i missed something in the source code, then I think that `/usr/local/sbin` should be added as well.

fish version: 2.5.0
uname: `Darwin Tolva.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64`
TERM: `ansi`

**Comment by krader1961** [comment]
I'm willing to bet that if you `cat /etc/paths` you will find */usr/local/bin* in that file. See the block of code in */usr/local/share/fish/config.fish* that begins with this comment:

```
# OS X-ism: Load the path files out of /etc/paths and /etc/paths.d/*
```

There are similar mechanisms in place for other UNIX flavors. If you want */usr/local/sbin* to also be in your `$PATH` either add it to */etc/paths*, or do what `brew doctor` recommended (but which I do not recommend), or explicitly set `$PATH` in your private *~/.config/fish/config.fish*.

**Comment by samdmarshall** [comment]
Is that entry in `/etc/paths` there by default or is it something that would have been added? I don't recall ever adding that in there myself, and would like to keep the way i add these entries uniform.

**Comment by krader1961** [comment]
I don't know. It's present on both of my macOS computers. I don't know if it is there by default, I added it manually, or the first time I installed HomeBrew it modified the file. But it isn't anything that fish did. It is, however, the standard mechanism on macOS/OS X for setting a global default for `$PATH`.

**Comment by krader1961** [comment]
Also, even if fish added the directory it was in to `$PATH` (which it doesn't) it does not follow that it should also add the `sbin` directory at the same level to `$PATH`.
