### ISSUE TITLE
[enhancement request] output folding

### ISSUE THREAD

**Issue by matthew-groth** [fish-shell/fish-shell#3933]
It could be really useful to be able to hide and show outputs from previous commands. Is this realistically possible?

**Comment by faho** [comment]
>Is this realistically possible?

No. This would require fish to buffer _all_ the output, which is the terminals job. It would be possible for both to cooperate on this, but that would need buy-in from terminal developers. 

If you ever achieve this, I'd be happy to add support for it, but until that happens, I'm closing this.
