### ISSUE TITLE
commandline --cut-at-cursor doesn't work correctly with --tokenize

### ISSUE THREAD

**Issue by HuwCampbell** [fish-shell/fish-shell#3934]
fish, version 2.5.0

If one typing in the middle of a word, that word is dropped when using --tokenize.

`opttest --build` with the character on u becomes
`opttest --b` with `commandline --cut-at-cursor`; and
`opttest` with `commandline --cut-at-cursor --tokenize`

**Comment by krader1961** [comment]
What behavior do you expect? There are only three choices:

1) Exclude the partial token under the cursor (current behavior).
2) Include the entire token under the cursor.
3) Include only that portion of the token to the left of the cursor.

Personally I don't think option 3 makes any sense. Option 1 and 2 differ in whether the first or last character of the token has to be prior to the current cursor position. If you can make a convincing case for option 2 we might change it. Whether we can do so in a minor release is going to require careful consideration of how such a change might break existing users.

**Comment by HuwCampbell** [comment]
I actually would have expected 3. I thought the tokenized version would give back the same thing as the non tokenized version, apart from it being split up.

[This](https://github.com/pcapriotti/optparse-applicative/pull/256) is the PR I'm working on; it provides a contextual command line completion script for any haskell program using [optparse-applicative](https://github.com/pcapriotti/optparse-applicative) for zsh and fish (including documentation). It's awesome.

Currently I'm having to call `commandline` twice to determine both where I am and get the entry the user is entering.

I wouldn't change it to 2 as it would break things (my script included in this case), and also doesn't match the non tokenized version.

I'm happy to close, as I have something working, I was however surprised by the current behaviour.

**Comment by zanchey** [comment]
I think `commandline -ct` and `commandline -co` are supposed to be complementary.

**Comment by krader1961** [comment]
I see from the PR you linked to this statement:

```
set -l cl (commandline --tokenize --current-process)
```

It is obvious, to me, that our documentation for `commandline` sucks. Because the fish implementation makes those flags incompatible. That is, only one of them (the latter) is honored. Yet that is not obvious from the documentation.

I'm wondering what you expect those two flags to do in combination.

**Comment by krader1961** [comment]
Note that your addition of the `--current-process` flag to the `--tokenize` flag in the PR you linked to is incorrect and only "fixes" your problem by accident. That is, it is an implementation detail that is not guaranteed to work in the future.

**Comment by HuwCampbell** [comment]
That appears to do what I'm after, which is give me the tokens of only the command which is being edited
```
hcampbell@localhost ~> function t; echo; printf "|%s|\n" (commandline --tokenize --current-process); end
hcampbell@localhost ~> cut -d this | cat that
|cat|
|that|
# now moving the cursor over this
hcampbell@localhost ~> cut -d this | cat that
|cut|
|-d|
|this|

```

**Comment by HuwCampbell** [comment]
(one needs to bind t to something to use this, I used `bind \cT t`)

**Comment by krader1961** [comment]
The phrase 

> ... which is give me the tokens of only the command which is being edited

implies that you do not want the `--cut-at-cursor` flag. The addition of the `--current-process` flag is likely to cause unexpected behavior.

I am confused when you say

> only the command which is being edited

If you want the entire statement being edited why are you using the `--cut-at-cursor` flag?

**Comment by krader1961** [comment]
Also, when I said earlier that `--current-process` fixes your problem by accident I mean that it only causes `commandline` to return all the text before and up to the next command (i.e., the text between `|` characters). This is another case of the documentation needing more verbiage.

**Comment by HuwCampbell** [comment]
Well, I'm providing a completion for the current (haskell program). And would like to be able to pipe into it as well. The way the completion works is by running the program like this
```
program --bash-completion-index 3 --bash-completion-word program --bash-completion-word arg1 --bash-completion-word arg2
```
Where the `--bash-completion-*` arguments are provided for this purpuse. The program then writes to std out all possible completions after `program arg1 arg2`.

The way I see what `arg1` and `arg2` are in the fish completion script is with commandline. If I didn't have the --current-process switch on something like this would happen
```
hcampbell@localhost ~> function t; echo; printf "|%s|\n" (commandline --tokenize ); end
hcampbell@localhost ~> cut -d this | program arg1 arg2
|cut|
|-d|
|this|
|program|
|arg1|
|arg2|
```
calling
```
program --bash-completion-index 5 --bash-completion-word cut  --bash-completion-word -d  --bash-completion-word this --bash-completion-word program --bash-completion-word arg1 --bash-completion-word arg2
```
which is gibberish. I can't complete a program I don't know about.

The --cut-at-index is so I can move the cursor back and complete a previous argument. Like correcting the first file in `cp first second` and still having completions.

**Comment by HuwCampbell** [comment]
The extra call to `commandline` is so I can see where I am (using the cut version) and get the word I am completing.

**Comment by faho** [comment]
>`set -l cl (commandline --tokenize --current-process)`

>It is obvious, to me, that our documentation for commandline sucks. Because the fish implementation makes those flags incompatible. That is, only one of them (the latter) is honored. Yet that is not obvious from the documentation.

That's not what happens.

```fish
function print_tokenized_process
    commandline --tokenize --current-process
end
$ bind \cs print_tokenized_process
$ echo banana | echo sausage # with cursor over "banana"
# press \cs
echo
banana
```

Without "--tokenize", this would print "echo banana" on one line,
without "--current-process", this would print "echo\nbanana\necho\nsausage\n" (yes, pipes are ignored - see #3823).

-----


Okay, so the documentation sucks - that's correct. I've tried to improve it a bit (these examples weren't there before!) but it's never really been specified so I'm not quite sure how it's supposed to work.

I've tried to write a proper opinion on the issue at hand, but I've noticed that I don't fully understand it yet and need to research more.

In particular, what matters here are use-cases. `commandline` has essentially two kinds - completions and bindings. Completions are a complicated field, and we'll need to see how they use this, and if the current uses are subtly buggy. E.g. they'll often check if an option has been given, and with grouped options ("-opc" is three options "-o", "-p" and "-c") that can also be in the current token. Bindings are essentially the wild west where anything goes as long as the user finds it useful. Can we make it easier to achieve useful things, and if so would we break current useful things in the process?

**Comment by HuwCampbell** [comment]
Nah the docs aren't that bad... I do think the tokenise behaviour is odd though, in that it's quite distinct from that of the function call without that flag when `--cut-at-cursor` is on.

My use case is currently working very well, so I'm selfishly satisfied with no changes (you should change your [stack](https://github.com/fish-shell/fish-shell/blob/master/share/completions/stack.fish) script to use it).

The things which would have made it easier for me however would be:
- number 3 above;
- a flag like `-C` which gives the word instead of the current character; or
- a tokenising function, to which I could have passed the string produced with `--cut-at-cursor`.

**Comment by krader1961** [comment]
I still don't have any idea what is being requested but since others apparently do I'm removing the "needs-more-info" label. As for the assertion that

> I actually don't think writing completions by hand is a good idea, as they'll always be out of date, incomplete, and version incompatible. One's option parsing libraries should do it for them instead.

I can't parse that. What "option parsing libraries"? How would the fish completion code get the information needed to auto-generate completions in a manner better than what it currently does by trying to extract that information from man pages? There is a proposal (issue #478) to use "docopt" to derive argument parsing for fish builtins and functions. That is useful but insufficient for completions in the general case.

**Comment by floam** [comment]
Yeah, even with docopt, we'll inevitably need to write completions by hand (in a very pleasant way) for a good many tools. I do know that @ridiculousfish had an idea of making some kind of online repository of docopt signatures for many many tools at some point, crowdsourced and separate from fish-shell. But those will still be largely hand-spun. The only generic solution is likely trying to interpret the manual pages - and we already do that to varying success.

**Comment by HuwCampbell** [comment]
> Yeah, even with docopt, we'll inevitably need to write completions by hand

This is currently true. I was trying to say it shouldn't be (and it least isn't for some programs now).

Sorry, this is only tangentially related to the issue at hand.

What I was trying to get at is that every program written with [optparse-applicative](https://github.com/pcapriotti/optparse-applicative) can use the same ~20 line fish script (or bash script, or zsh script). All it really does is run the program in question asking: "what can be completed from here?"; and it works really well.

There are a few other libraries which do something like this: argcomplete is probably the most widely used. If you're in python land and use argparse and argcomplete, completions are essentially free.

What I would like to see, overly optimistically, is for this behaviour to be standardised in some way. So if one writes a program, the shell can just know how to ask a program for what is a good completion.

**Comment by faho** [comment]
Closing in favor of #7375 as this has gotten stale.
