### ISSUE TITLE
Create a Dash/Zeal docset 

### ISSUE THREAD

**Issue by edouard-lopez** [fish-shell/fish-shell#3935]
**related:** 
* Kapeli/Dash-User-Contributions#1355
* dan-c-underwood/fish-dash#1

---

[Zeal](http://zealdocs.org/) _is an **offline** documentation browser for software developers._ compatible with [Dash](https://kapeli.com/dash) docsets.
I use it for various language (Python, Node, Bash, etc.) but sadly there is no Fish docset.

There is a [guide and scripts to generate docset](https://kapeli.com/docsets) based on existing doc. 

### Question

Would you mind having a look at it and give feedback on the **feasibility?**

**Comment by faho** [comment]
@edouard-lopez: I'm not sure I understand this completely. So, you want the documentation for fish-script (i.e. not our C++ code comment stuff) to appear in Zeal, and to do this we'd need to generate a "Dash docset" and carry it in the fish-shell repo? Or would we contribute it somewhere else? What exactly is the advantage of this system?

Anyway, it seems this is compatible with doxygen, which we already use for our documentation.

@MarkGriffiths: Is this something we want and can do?

**Comment by edouard-lopez** [comment]
@faho Yep, I'm talking about the content of https://fishshell.com/docs/current/ but it look like they [already have something](https://github.com/Kapeli/Dash-User-Contributions/blob/master/docsets/fish/README.md). I will keep you up to date

Interest is zeal/dash are faster than web and can be **used offline** (i.e. train/flights)

**Comment by edouard-lopez** [comment]
@dan-c-underwood have done one https://github.com/dan-c-underwood/fish-dash

**Comment by zanchey** [comment]
If it's any help, all the fish packages that I know of come with documentation included for offline use.

**Comment by krader1961** [comment]
True, you get the man pages but I'm not aware of them including the equivalent of what is hosted at fishshell.com. I took a few minutes earlier today to install Dash on my mac and use the fish-dash app to bundle the documentation. I'm impressed enough to consider paying for the app (it's fully functional but nags you if you don't have a license). I think we should consider publishing Dash/Zeal compatible "doc sets".

**Comment by zanchey** [comment]
> I'm not aware of them including the equivalent of what is hosted at fishshell.com

Definitely should - the `help` command will try to open a local copy. They're in the Debian packages, RPMs and are installed by Homebrew in `$__fish_help_dir`.

**Comment by krader1961** [comment]
Ah, yes, I see that now and looking at the fish-dash app I see that it uses those files in constructing the "doc set". Still, the Dash app is very cool. It's similar to the difference between an IDE like Xcode or a straight editor like Vim. And while I'm old school (not a fan of IDEs) I do like the improved documentation reading experience provided by Dash. Granted I've only been playing with it for a couple of hours but I'm likely to make it a regular member of my toolkit.

**Comment by nhooyr** [comment]
For anyone who wants a similar experience but free, there is https://devdocs.io

**Comment by davewongillies** [comment]
There's already a fish docset for dash/zeal [here](https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets/fish).

For future reference for any Zeal users, [this feed](https://zealusercontributions.herokuapp.com/docsets/fish.xml) can be added in Tools -> Docsets -> Add feed.

**Comment by krader1961** [comment]
Thanks for the pointer @davewongillies. The problem with that docset is it is out of date as it's for fish 2.3 and a lot has changed since then. It would be nice if we had a way to generate a Dash docset as part of running `make doc`. That way anyone building fish from source can be assured of always looking at the corresponding documentation. It would also be nice if we made uploading a new docset to https://github.com/Kapeli/Dash-User-Contributions/tree/master/docsets whenever we do a new release.

**Comment by faho** [comment]
This appears to not be happening, sorry!
