### ISSUE TITLE
setenv.fish broken when trying to make it behave like export

### ISSUE THREAD

**Issue by jeffkowalski** [fish-shell/fish-shell#3937]
Recent changes (d9b30ab09013ef803314d9656e669bc7577b585e) have broken setenv.fish

* Version info
fish, version 2.5.0-296-g28bc309f
Linux wafer 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

* Command
setenv PATH /bin

* Response
$/ is not a valid variable in fish.
/usr/local/share/fish/functions/setenv.fish (line 9):                 set -gx $v $$v
                                                                                  ^
in function “setenv”
        called on standard input
        with parameter list “PATH /bin”

**Comment by krader1961** [comment]
Thanks for catching that. I had somehow gotten it into my head that `setenv` used the same `var=val` syntax as `export`. I'll add unit tests for both functions to help ensure we don't introduce a regression in the future.
