### ISSUE TITLE
Suggestion: make ...[.[.]] understand successive parent directories

### ISSUE THREAD

**Issue by favdish** [fish-shell/fish-shell#3946]
I have an extended cd command that allows to go two directory levels up with cd ..., three with cd .... etc. It would great if fish tab completion understood these shorthands (though that is something I think I can probably do myself one of these days by looking at the completion code).

It would be even better if fish could support this notion in its internal commands. That is an altogether different proposition, of course, and probably will bring all sorts of complications I am not even dimly aware of.

**Comment by krader1961** [comment]
This has been discussed and rejected in issue #2671.
