### ISSUE TITLE
color problems in omf themes

### ISSUE THREAD

**Issue by balabi0github** [fish-shell/fish-shell#3958]
fish --version shows 2.5.0
echo $TERM shows xterm-256color

I just upgrade to win 10 creator, and bash now support 256 colors. However, agnoster theme in oh my fish is still ugly in color.

here is my snapshot
http://pasteboard.co/4TuPOIiJl.png

How to correctly set up colors for agnoster

**Comment by faho** [comment]
Note that the [agnoster prompt](https://github.com/oh-my-fish/theme-agnoster/blob/master/fish_prompt.fish) only uses named colors - see the `prompt_segment` calls. Those are already part of the 8 color palette, and hence not influenced by the fact that the term supports 256 colors.

You can confirm that e.g. `set_color black | od -t x1z` says it prints "1b 5b 33 30 6d" (i.e. `\e\[30m`). At that point, it's up to the terminal to print something black (or blue, or magenta, or cyan). And it seems in this case the palette that the win10 terminal uses is unusual.

Also note that the agnoster theme isn't an official fish-shell project, so if you have problems with that specifically you should direct your queries to the [oh-my-fish/theme-agnoster](https://github.com/oh-my-fish/theme-agnoster/issues) repository.

**Comment by balabi0github** [comment]
@faho Thank you very much for quick reply
