### ISSUE TITLE
hang on launch

### ISSUE THREAD

**Issue by Darkshadow2** [fish-shell/fish-shell#3964]
fish 2.5.0-305-ge7d68646

macOS 10.12 & 10.11
OpenBSD 5.9

@krader1961 I believe I found an edge case with the signal stuff you've done.

I've run into an issue where fish will hang on launch. I believe it's related to the signal handling because if I edit `src/signal.cpp` and change `ignore_signal_block` to false, this problem doesn't happen. It also seems to happen before the `FISH_NO_SIGNAL_BLOCK` var is read (setting that makes no difference).

So, some background. First, I need to apologize to you, because I actually ran into this problem a while ago and forgot about it (I found a workaround). So when I first ran into this, it was on OpenBSD. This was right after you pushed the signal stuff and before you reverted and then later reapplied it.

In OpenBSD, I had fish set as the shell in cron. cron (there) uses what you set as `SHELL` to launch any job (basically `$SHELL -c 'command'`). I found after that commit that fish was hanging on launch. I needed to fix it (the OpenBSD machine is my gateway, and some of those cron jobs are related to my network), so after I figured out that it was because of the `SHELL` variable, I reset it to sh. I meant to go back and investigate, but never did and forgot about it.

Forward to now. On my main (OS X) machine, I created a utility to run some scripts when it sleeps/wakes. I had noticed lately that it didn't seem to be running, but I've been busy and really hadn't paid it much mind (none of the things I have running there is critical in any way). Yesterday, however, I was working in the terminal and noticed a TON of fish processes just sitting around. Looking at them, I realized it's all the scripts that should have been running on sleep/wake.

So, I've been trying to narrow down at least a little what is going on, but I haven't really been able to. Fish seems to get into a state where select is being called, timing out, and repeating that forever. I managed to create a test based on my utility that reliably triggers the hang.  So, here you go, a sample of when fish is hung, debug output (-d6) from fish when it hangs, and the test (note the test will only compile and run on OS X). There's a little setup needed for the test, I included a README file with it.

When fish hangs it ignores INT, TERM, HUP, or QUIT signals. I have to send it the KILL signal to quit it.

[sample.txt](https://github.com/fish-shell/fish-shell/files/926743/sample.txt)
[debug.txt](https://github.com/fish-shell/fish-shell/files/926744/debug.txt)
[fht.tar.gz](https://github.com/fish-shell/fish-shell/files/926746/fht.tar.gz)

**Comment by krader1961** [comment]
Thanks for the bug report. I'll see if I can reproduce or make sense of the data you've provided.

**Comment by krader1961** [comment]
I confirmed that commit e0f62c178 introduces the problem and simply changing the `bool ignore_signal_block = true;` var initialization to false "fixes" the issue. TBD is what is going on. I also confirmed that the recent job control changes introduced to implement a `disown` command does not affect the behavior.

**Comment by krader1961** [comment]
FWIW, I hope to get to root cause and fix this for the 2.6.0 release but can't promise to do so. Rather than hold up the 2.6.0 release it may be preferable to simply revert to the old, expensive, signal blocking behavior so that we can create a 2.6.0 release (doing so is a one line change). This is the only open issue that would block that release and there are already a large number of very useful improvements queued for that release.

**Comment by krader1961** [comment]
The problem is that when launched via the dispatch framework (`man 3 dispatch`) a bunch of signals are blocked:

```
WTF sigprocmask oset FBFEE007
WTF procmask sig 0 Unknown set
WTF procmask sig 1 SIGHUP set
WTF procmask sig 2 SIGINT set
WTF procmask sig 3 SIGQUIT set
WTF procmask sig 14 SIGALRM set
WTF procmask sig 15 SIGTERM set
WTF procmask sig 16 SIGURG set
WTF procmask sig 18 SIGTSTP set
WTF procmask sig 19 SIGCONT set
WTF procmask sig 20 SIGCHLD set
WTF procmask sig 21 SIGTTIN set
WTF procmask sig 22 SIGTTOU set
WTF procmask sig 23 SIGIO set
WTF procmask sig 24 SIGXCPU set
WTF procmask sig 25 SIGXFSZ set
WTF procmask sig 26 SIGVTALRM set
WTF procmask sig 28 SIGWINCH set
WTF procmask sig 29 SIGINFO set
WTF procmask sig 30 SIGUSR1 set
WTF procmask sig 31 SIGUSR2 set
```

When launched "normally" no signals are blocked when fish starts running. This isn't a problem when running without my signal optimization because the `signal_unblock()` function fish calls repeatedly blindly unblocks all signals regardless of whether or not they were blocked by some mechanism other than the `signal_block()` fish function.

The fix is to always ensure no signals are blocked when fish starts running.

**Comment by Darkshadow2** [comment]
Whoa, that's crazy. 

Ah, I see, the dispatch framework sets up a signal mask. That's not in the documents anywhere!

I see you already pushed a fix for this, but I also see how to fix this in my source. Either use `sigprocmask` (with fork), or `posix_spawnattr_setsigmask` (with posix_spawn) with an empty mask.
