### ISSUE TITLE
`bind` mode names should be valid as a variable or function name

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3965]
While reviewing PR #3962 @faho and I had a brief discussion about the advisability of restricting `bind` mode names to the same rules that govern variable and function names. At the moment `bind` mode names can contain arbitrary characters; e.g., `bind -M "argle/bargle me"`. However, that flexibility isn't needed and causes problems when the value is incorporated into variable or function names.

Changing this is strictly speaking not a backward compatible change. However, I checked every Oh-My-Fish and Fisherman plugin and could not find a single one that defined a new mode. Let alone one that contains characters that would be illegal if this change is made.

**Comment by krader1961** [comment]
I see we have `wcsvarname()` and `wcsfuncname()` functions, with differing implementations (including return values), despite both being used in the same way to validate those identifiers. They are also badly named since they don't actually construct a var or func name object. They return a truth value.

I should have noticed this when I refactored the code to fix issue #3050 seven months ago (commit 92dd6de7). The relevant code is an inconsistent mess. This includes the error messages emitted for invalid variable versus function names.

I can't find where in the documentation valid identifiers are defined. Running `grep identifier doc_src/*` returned no documents. And visually scanning the documentation I couldn't find anything relevant. Not to mention that `grep underscore doc_src/*` returns no relevant lines.

Can anyone point me to documentation for valid fish variable or function names?

**Comment by faho** [comment]
>Can anyone point me to documentation for valid fish variable or function names?

I can't find any either.

The rules seem to be, for function names:

- Can't contain a "/"
- Can't start with a "-"
- Can't be empty

while variable names must only contain alphanumeric characters and "_" and also can't be empty. This means that variable names are strictly more limited.

I'd argue that bind mode names should have the same limitations as _variable_ names, since they are used in variable names.

Also, we should document these rules.

**Comment by krader1961** [comment]
Thanks, @faho, for confirming my conclusion. I'll first update the code and documentation to make the existing rules clearer. Then I'll do a second change to impose the var name validation on `bind` mode names.
