### ISSUE TITLE
Upgrade the PPA for Ubuntu 17.04 (Zesty Zapus)

### ISSUE THREAD

**Issue by FrederikNS** [fish-shell/fish-shell#3966]
I'm running fish shell from ppa:fish-shell/release-2, I just upgraded to Ubuntu 17.04 (Zesty Zapus), and discovered that the PPA only have fish packages for 16.10 (Yakkety Yak).

The yakkety release work perfectly for me, so the build shouldn't need any big changes.

**Comment by zanchey** [comment]
I actually have a reminder set in my calendar to do this, but I never know exactly what day the release comes out so it's set for May.

I'll copy the binaries across.
