### ISSUE TITLE
Proofread Homebrew's Caveats process message for beginners.

### ISSUE THREAD

**Issue by ryo-endo** [fish-shell/fish-shell#3976]
Hi, developpers.

### my background
I'm beginner for mac & shell.
I was recommended the fish by my friend.
But, I got a install trouble.

### issue
I went to https://fishshell.com/ and installed with `$ brew install fish`.
Install completed.
But, I can't understand what Caveats process says.

```
==> Caveats
You will need to add:
  /usr/local/bin/fish
to /etc/shells.
```

I don't know `/etc/shells`.
I mixed up I should make symbolic link to `/etc/shells`.
So, I run command `mv /usr/local/bin/fish /etc/shells`.
(of course, my env will be broken)

### my suggestion

I propose to change the Caveats message. like this.
Its friendly for beginners.
```
==> Caveats
You will need to add:
  /usr/local/bin/fish
to /etc/shells.

Run this command:
$ echo /usr/local/bin/fish >> /etc/shells
```

### my env
fish, version 2.2.0
Homebrew 0.9.5 (git revision 937e; last commit 2016-02-13)
OS X 10.11.3

Thankyou and best regards.

**Comment by krader1961** [comment]
Sorry you had problems but telling people to blindly append to a file can itself cause problems. Also, that operation needs to be done as root so it won't work as written. It would have to be something like `sudo sh -c 'echo /usr/local/bin/fish >>/etc/shells'`. I think the current message is adequate. However, if you, or anyone else, feels strongly about this you are welcome to make a pull-request against the Homebrew project as outlined in [this](http://thecoatlessprofessor.com/programming/updating-a-homebrew-formula/) blog post.
