### ISSUE TITLE
Termux completion issue: An error occurred while redirecting file '/etc/passwd'

### ISSUE THREAD

**Issue by christianrondeau** [fish-shell/fish-shell#3980]
> fish --version
    fish, version 2.5.0
    > echo $version
    2.5.0
    > uname -a
    Linux localhost 3.18.14-10780217 #1 SMP PREEMPT Fri Feb 24 13:45:03 KST 2017 aarch64 Android
    > echo $TERM
    xterm-256color

On linux distributions that do not (and cannot) read `/etc/passwd`, fish autocompletion fails. More specifically, on https://github.com/termux.

Exemple:

    ssh mi

Then I press <kbd>tab</kbd> and I get:

    ssh mi<W> fish: An error occurred while redirecting file '/etc/passwd'
    open: No such file or directory
    <W> fish: An error occurred while redirecting file '/etc/passwd'

The problem is that we take for granted that `/etc/passwd` will be readable in multiple scripts, like this: https://github.com/fish-shell/fish-shell/blob/11a60c8374c21c299bab35ae12a30b54a44bc9e3/share/functions/__fish_complete_users.fish#L8

This would also be true for any `/etc/*` files.

This is happening on a barebone fish installation.

I'm not sure what the best fix would be...

1. In every place we try to read this file, we add a `if [ -f /etc/passwd ]`
2. We check once in a central script, and store the result somewhere (a shared function?)
3. We create a series of patch the `fish` distribution on termux https://github.com/termux/termux-packages/tree/master/packages/fish

What are your thoughts?

**Comment by christianrondeau** [comment]
Note that the issue is similar to the one raised by @krader1961 in https://github.com/fish-shell/fish-shell/issues/3845

**Comment by faho** [comment]
>In every place we try to read this file, we add a if [ -f /etc/passwd ]

I think that'd be preferable in this case. We don't read too many files from /etc (`grep "/etc/" -r share/` shows 86 matches, but some of those are either already tests or after tests, and a bunch in descriptions and such so it's maybe 10 sites).

Though note that we prefer the explicit `test` form - `test -r /etc/passwd`.

Ideally, we'd have some other way to complete users/groups on termux, but I don't think it uses them in the same way.

Also, there's some weirdness relating to "__fish_print_users" and "__fish_complete_users" - I have no idea why both of those exist and do basically the same thing. There's a difference related to macOS and I have no idea which is better.

**Comment by krader1961** [comment]
I concur with @faho. Just predicate the reading of */etc/passwd* on `test -r /etc/passwd`.

Why there are two nearly identical functions is from commit 06de2602c which made them standalone functions. Prior to that commit they were both defined in *__fish_config_interactive* prefaced with this comment:

```
       #
       # A few minor convenience functions
       #
       # The naming heuristic is that __fish_complete_* prints completions
       # and descriptions, while __fish_print_* only prints the completions
       # and no descriptions
       #
```

Looking at how the two functions are used it does appear that we need the distinction. Although I would prefer to implement `__fish_print_users` by having it run `__fish_complete_users` and strip the description. That way we only have to modify one function when improving how users are enumerated. Also, add a comment to each function that explains why each exists and references its counterpart.

@christianrondeau: Care to take a stab at improving this? While we aren't going to teach you how to use git we're happy to help with anything unique to this project such as code style, submitting a change for review, etc.

**Comment by christianrondeau** [comment]
Sounds simple enough, I'll do it (adding 86 `if` clauses doesn't sound very nice, but I don't have a better idea), the fix itself is very simple to make and to test, since the `.fish` files don't even need to be built from source.

If I'm to fix all/most of them, my only question is how to test? I didn't see that many tests related to autocompletion in the tests folder, should I manually test all cases? On which platforms? Or should I only go and do my best, and rely on a code review?

**Comment by christianrondeau** [comment]
Well there was only three actual cases like this in autocompletions, and `dcop` is not on Termux, so I fixed the other two and created a pull request. I tests and it works on termux.

Let me know if this works for you, otherwise I am fully prepare to put in the efforts and do more if you have recommendations.
