### ISSUE TITLE
It doesn't show us command histories when we try to show them by C-n or C-p

### ISSUE THREAD

**Issue by pythonissam** [fish-shell/fish-shell#3982]
Please tell us which fish version you are using by executing the following:

```
$ fish -v
fish, version 2.5.0
```

-------------------------------

Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

```
`$ uname -a`
Darwin Neumann.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64
```

__This issue occurs only on iMac (27 inch)__

--------------------------------

Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:

```
$ sh -c 'env HOME=$(mktemp -d) fish'
```

No, the issue still occurs.

-----------------------------------

Tell us how to reproduce the problem. Including an asciinema.org recording is useful for problems that involve the visual display of fish output such as its prompt.

## It doesn't show us command histories when we try to show them by `C-n` or `C-p`.

The point is:
- This issue occurs on iMac (27 inch), but not on MacBook Pro (15 inch)
- It worked fine until v2.3.1, and doesn't work from v2.4.0

**Comment by krader1961** [comment]
Hi, @pythonissam. I'm a fish developer who uses macOS. I do not see the problem you are describing and cannot recall anyone else reporting a similar problem. The most likely explanation is that either your shell history file has been corrupted or your key bindings are broken. What does typing `bind \cp` output? It should be `bind \cp up-or-search`. If you run `type up-or-search` it should output a function that begins with a line like this:

```
# Defined in /usr/local/share/fish/functions/up-or-search.fish @ line 1
```

What does `builtin history search -t -5` output?

Note that the recommendation to test using `sh -c 'env HOME=$(mktemp -d) fish'` will, by definition result in your existing history not being available. However if you a command such as `ls` pressing [ctrl-P] should show it. Does that not happen?

**Comment by pythonissam** [comment]
Hi, @krader1961. It seems to be solved...

> What does typing `bind \cp` output?

`bind \cp up-or-search`

> type `up-or-search`

```
function up-or-search --description 'Depending on cursor position and current mode, either search backward or move up one line'
    # If we are already in search mode, continue
    if commandline --search-mode
        commandline -f history-search-backward
        return
    end

    # If we are navigating the pager, then up always navigates
    if commandline --paging-mode
        commandline -f up-line
        return
    end

    # We are not already in search mode.
    # If we are on the top line, start search mode,
    # otherwise move up
    set lineno (commandline -L)

    switch $lineno
        case 1
            commandline -f history-search-backward

        case '*'
            commandline -f up-line
    end
end
```

> What does builtin history search -t -5 output?

```
# Sun Apr 23 12:16:53 2017
type up-or-search
```

> Note that the recommendation to test using sh -c 'env HOME=$(mktemp -d) fish' will, by definition result in your existing history not being available. However if you a command such as ls pressing [ctrl-P] should show it. Does that not happen?

Yeah, now it shows! Excuse me:(
I used to use a plugin manager of fish and some snippets seem to have remained...
I erased them all and it works fine! Thank you:)

**Comment by krader1961** [comment]
I'm glad we were able to help you figure out what was wrong. We prefer that people open an issue to report a problem even if it turns out to be due to something other than a bug or shortcoming in the fish project. Because knowing about those problems may still help us improve fish.
