### ISSUE TITLE
builtin string defines its own unique status enums

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#3985]
While working on issue #3957 I noticed the `string` command documentation says:

> In addition to the exit codes documented below, all the string subcommands exit with a value of 2 to indicate that an error occurred.

Which is patently wrong. That caused me to look at the code and notice this line introduced in the original implementation of the `string` builtin command:

```
enum { BUILTIN_STRING_OK = 0, BUILTIN_STRING_NONE = 1, BUILTIN_STRING_ERROR = 2 };
```

AFAICT only *src/builtin_string.cpp* defines its own return codes in this manner. I believe this should be removed and the string builtin should simply use the symbols defined in *src/proc.h* such as `STATUS_BUILTIN_OK` and `STATUS_BUILTIN_ERROR`. If we need a magic value for errors that represent usage errors rather than no matches or replacements being done it should be added as a `#define` to *src/proc.h*. It is not obvious to me that such a distinction is necessary. But if it is then we should be doing so in a uniform manner across all the builtin commands (something we are not doing as I write this).

Opinions?

**Comment by krader1961** [comment]
I also see that *src/builtin_test.cpp* has

```
enum { BUILTIN_TEST_SUCCESS = STATUS_BUILTIN_OK, BUILTIN_TEST_FAIL = STATUS_BUILTIN_ERROR };
```

That is innocuous in as much as it simply defines aliases rather than defining new return values. Nonetheless it should also be eliminated and the primary symbols (e.g., `STATUS_BUILTIN_OK`) used in that code. Renaming the values in that manner only serves to obfuscate the code.

**Comment by zanchey** [comment]
I would like to avoid breaking changes for commands people are likely to have scripted; can we ensure this does not blow up in the faces of our users?

**Comment by krader1961** [comment]
@zanchey: How likely is it that anyone is doing the equivalent of this:

```
$ string invalid-sub-command
$ if test $status -eq 2
```

The only reasons `string` returns 2 is if the invocation is invalid. That is, the subcommand isn't recognized, an unrecognized flag is parsed, an illegal combination of args is given, or a mandatory arg (e.g., a pattern) is missing. It otherwise returns one if the invocation is legal but failed to match any strings, perform a replacement, etcetera. No other builtin does this AFAICT. I'm not opposed to such a convention but we should be consistent. Too, the `string` man page is wrong, or at best misleading, about the return value.

**Comment by krader1961** [comment]
Unless someone can explain why fish commands should set `$status` to `2` rather than `1` when invoked with invalid arguments, like the `string` builtin does, I'm going to simplify that code and remove the `BUILTIN_STRING_ERROR` enum. Also, even if we decide we want a distinct return value for when commands fail due to invalid arguments we should do so uniformly over all our commands. Which means the `BUILTIN_STRING_ERROR` enum value unique to the *src/builtin_string.cpp* code should be moved to *src/proc.h* and become an alternative to `STATUS_BUILTIN_ERROR` that is used by other commands when a command is invoked with invalid arguments.

**Comment by krader1961** [comment]
Upon further reflection I think there is value in having a distinct return value when the command invocation is invalid. Not just that the requested operation failed (e.g., `string match` didn't match any strings) but the arguments don't make any sense. But that value should not be `2` and should not be unique to the `string` command. It should instead by a "high" value like 121 which currently doesn't have a special meaning within fish.

Furthermore, these special status codes should be defined in *src/common.h* (or similar file) rather than in *src/proc.h*. The latter defines numerous fish specific return values such as `STATUS_READ_TOO_MUCH` in addition to `STATUS_BUILTIN_OK` and `STATUS_BUILTIN_ERROR`. Note that we should also expose and use at least a few of the aforementioned symbols for use in fish functions.

**Comment by krader1961** [comment]
Removing the RFC (request for comment) label since I have decided that having a distinct return value for invalid fish command invocations is potentially useful. We just need to codify that idiom and implement it across all fish builtins and functions. As opposed to it being something unique to the `string` builtin.

**Comment by krader1961** [comment]
Ugh! I have changed my mind after spending a couple of hours trying to implement this consistently across all builtin commands. I do not see a way to meaningfully distinguish between invalid arguments to a command versus those that simply result in the command failing. For example, if `bg` is run with a syntactically valid job ID but one which doesn't exist should that return 1 or 121? What about the `test` command? If it is passed an invalid expression should it return 1 or 121?

I hope you get the idea. The pattern established by the *src/builtin_string.cpp* code to try and distinguish between invalid arguments versus some other failure, such as not matching any strings, isn't going to be useful in practice. The use of any returned status value other than zero or one should be reserved for special situations where it is crystal clear that something other than one to represent a generic failure is useful.

Please tell me I'm wrong soon. Otherwise I'm going to revert that distinction from the code.

**Comment by faho** [comment]
> For example, if bg is run with a syntactically valid job ID but one which doesn't exist should that return 1 or 121? What about the test command? If it is passed an invalid expression should it return 1 or 121?

We already treat those differently - the latter prints an error (`test -a foo`). Running `bg` with a non-existent job ID is _okay_ - the job might have quit in the meantime. Running `test` with an invalid expression _isn't_ - that's a bug in the calling script.

That being said, if the only use of this is "distinguish failure in case you've silenced stderr", then I don't really see a need. It'd be nice to have, but since it seems to be a whole bunch of work I don't think we need to bother.

**Comment by krader1961** [comment]
Thanks, @faho, for commenting on this issue. The only use I can see for the `string` behavior is to make debugging problems easier; such as by examining the output of `fish -d5 some_script`.  That is because no fish script is going to explicitly test that the preceding `string` command failed because the arguments were invalid; e.g., `if test $status = 2`. I am not convinced the debugging benefit is worth the complexity and ambiguity.

**Comment by krader1961** [comment]
I went ahead and merged my change since I had already done 98% of the work. There are probably some cases I missed or got wrong but we can fix those as they are found.
