### ISSUE TITLE
__terlar_git_prompt breaks my fish views

### ISSUE THREAD

**Issue by mizunashi-mana** [fish-shell/fish-shell#3986]
https://github.com/fish-shell/fish-shell/blob/master/share/functions/__terlar_git_prompt.fish#L77
This line breaks my fish terminal.  
![screenshot_resized-0](https://cloud.githubusercontent.com/assets/11599514/25376718/176e1180-29e0-11e7-8377-fb6d0e1733e0.png)

The suspect is ⚡ (Unicode: `U+26A1`, UTF-8: `\xE2\x9A\xA1`).

Because I have less experiences for fish, I couldn't find the ill codes on fish.  Help me!

## Information

```bash
$ fish --version
fish, version 2.5.0
$ cat ~/.config/fish/functions/fish_right_prompt.fish
function fish_right_prompt --description "Write out right prompt"
  segment_right black magenta [(prompt_pwd)]
  segment_right black green
  segment_right black normal (__terlar_git_prompt)
  segment_close
end

$ fisher ls
getopts segment shark  z
$ uname -a
Linux local 4.10.6-1-ARCH #1 SMP PREEMPT Mon Mar 27 08:28:22 CEST 2017 x86_64 GNU/Linux
$ locale
LANG=en_US.utf8
LC_CTYPE="en_US.utf8"
LC_NUMERIC="en_US.utf8"
LC_TIME="en_US.utf8"
LC_COLLATE="en_US.utf8"
LC_MONETARY="en_US.utf8"
LC_MESSAGES="en_US.utf8"
LC_PAPER="en_US.utf8"
LC_NAME="en_US.utf8"
LC_ADDRESS="en_US.utf8"
LC_TELEPHONE="en_US.utf8"
LC_MEASUREMENT="en_US.utf8"
LC_IDENTIFICATION="en_US.utf8"
LC_ALL=
```

**Comment by zanchey** [comment]
Which terminal are you using? Could you show the current setting of `$TERM`?

**Comment by mizunashi-mana** [comment]
@zanchey Oh, i forgot, sorry.

I'm using [Terminator](https://gnometerminator.blogspot.jp/p/introduction.html) v1.91-5.  And, `bash` prints ⚡ well on my terminator.

terminal environments:

```bash
TERM=xterm-256color
TERMINAL=terminator
```

**Comment by faho** [comment]
The issue here is terminator assumes ⚡ is 2 wide. When you e.g. echo "a⚡b", it ends up as "a⚡ b".

That's wrong _in terminator_ and needs to be fixed there. I'm not sure if there's anything fish can do to workaround this.

**Comment by krader1961** [comment]
Just to expand on @faho's answer, fish correctly treats that character as having width == 1. Whereas your terminal appears to treat it as having width == 0.5; i.e., a half-width character. On macOS iTerm2 and Terminal.app both render it as taking half a character width. This character was added in Unicode v4 so it isn't surprising there are implementation issues. See

https://codepoints.net/U+26A1?lang=en
http://unicode.org/reports/tr11/tr11-8.html

There isn't anything fish can do about this. If you add a single space after that character you'll probably find that things render better.

**Comment by mizunashi-mana** [comment]
Thank you for responses.

My understandings:
* Terminator thinks ⚡ is 2 wide character although ⚡ should have a width (and fish thinks so).
* fish is correct, and terminator is wrong.
* If I want to fixed this issue, I change to use other application (e.g. urxvt) or fix terminator code.

@krader1961 @faho Is this correct?

In iTerm2 case, ⚡ is rendered a half-width character.  So, the opposite problem (too short shows be appeared) happens, right?

**Comment by krader1961** [comment]
Yes. The basic problem is that there is a lot of confusion about the width of various emoji characters. Making matters worse is that the Unicode standard itself has redefined the width of some characters as new versions of the standard are released. So you're going to run into problems like this for the foreseeable future. Meaning that sometimes you'll need to pick a different emoji.
