### ISSUE TITLE
<E> fish: Unable to open universal variable file '...': Permission denied

### ISSUE THREAD

**Issue by nirvdrum** [fish-shell/fish-shell#3988]
The JetBrains suite of IDEs have an embeddable terminal option. Generally, this is quite handy because you can have a shell right alongside your code, but like you'd be able to achieve with something like emacs or vim. However, when I try to use the terminal with fish as my shell, I see a lot of `<E> fish: Unable to open universal variable file '/opt/idea-2017.1.1/plugins/terminal/fish/fishd.melchior': Permission denied` printed out.

This is a multi-user system and the IDE is globally installed with restricted permissions in /opt. Changing permissions of the plugin directory isn't really ideal and may not even be doable in some environments.

There's likely some option I haven't found that can fix all this. But I'm reporting it because at the very least it's a usability problem. Other shells don't have problems running this way. At first blush, it also looks like fish should maybe failover into writing in a user-owned directory. My current solution is to ignore the messages at startup and just switch to bash.

Environment info:

```
> fish --version
fish, version 2.5.0

> echo $version
2.5.0
```

OS: Ubuntu 17.04 64-bit.
IDE: IntelliJ IDEA 2017.1.1

The reproduction involves [downloading a version of IntelliJ IDEA](http://www.jetbrains.com/idea/?fromMenu#chooseYourEdition) and untarring it to /opt. Then run the IDE and activate the terminal tab with fish set as the default user shell.

**Comment by faho** [comment]
What are the values of $USER and $HOME inside that environment?

How about $XDG_CONFIG_HOME?

Those are the variables fish uses to figure out the uvar file path, and it seems like they are set to a location that isn't writeable to fish, and it seems that IDEA does that on purpose. I have no idea why, though.

**Comment by nirvdrum** [comment]
Huh. I didn't realize that's how it worked. Thanks for the lead.

```
> echo $USER
nirvdrum

> echo $HOME
/tmp/tmp.ptDgOqO5Nw

> echo $XDG_CONFIG_HOME
/opt/idea-2017.1.1/plugins/terminal
```

It looks like they ship with their own base fish config. There's a file at `/opt/idea-2017.1.1/plugins/terminal/fish/config.fish` with the following contents:

```
if test -n "$OLD_XDG_CONFIG_HOME"
  set XDG_CONFIG_HOME "$OLD_XDG_CONFIG_HOME"
end

if test -f ~/.config/fish/config.fish
  . ~/.config/fish/config.fish
end

if test -n "$JEDITERM_USER_RCFILE"
  . $JEDITERM_USER_RCFILE
  set -e JEDITERM_USER_RCFILE
end

if test -n "$JEDITERM_SOURCE"
  . $JEDITERM_SOURCE
  set -e JEDITERM_SOURCE
end
```

And `$OLD_XDG_CONFIG_HOME` appears to be empty. They must bootstrap their own fish config and then try to swap it back. If that's the case, this looks like a bug in their code. If that's the case, sorry for starting here.

**Comment by nirvdrum** [comment]
In case anyone else is interested, this is being [tracked upstream](https://youtrack.jetbrains.com/issue/IDEA-169111). I'm going to close the issue out since this appears not to be a problem with fish. Thanks again for the help!

**Comment by bodolsog** [comment]
It's because PyCharm terminal plugin search your fish config file in this location:  `/opt/idea-2017.1.1/plugins/terminal/fish/fishd.melchior`. And you have no `fishd.melchior` file there (is in `.config/fish/` directory.

link between both locations solve problem:
```
sudo ln -s ~/.config/fish/fishd.melchior /opt/idea-2017.1.1/plugins/terminal/fish/fishd.melchior
```

**Comment by luispabon** [comment]
Unfortunately this solution above won't work with intellij (phpstorm, etc) installed via snaps.

**Comment by Cstyler** [comment]
@luispabon Sure. I'm getting this error when I open terminal in PyCharm IDE: 
`<E> fish: Unable to open universal variable file '/snap/pycharm-professional/107/plugins/terminal/fish/fishd.khan-ThinkPad-T520': Read-only file system`

And creating symbolic link as @bodolsog said doesn't work:
`sudo ln -s ~/.config/fish/fishd.khan-ThinkPad-T520 /snap/pycharm-professional/107/plugins/terminal/fish`
`ln: failed to create symbolic link './fishd.khan-ThinkPad-T520': Read-only file system`

**Comment by morten-b** [comment]
I had a similar issue but with the fish_variable files: With the above suggestion from @bodolsog I ran `sudo ln -s ~/.config/fish/fish_variables  /usr/share/rider/plugins/terminal/fish/fish_variables` which fixed the problem for JetBrains Rider

**Comment by josselinbuils** [comment]
I had the issue with Ubuntu 18, the solution described there worked: https://youtrack.jetbrains.com/issue/IDEA-169111#focus=streamItem-27-2518787.0-0.

**Comment by ezalivadnyi** [comment]
> It's because PyCharm terminal plugin search your fish config file in this location: `/opt/idea-2017.1.1/plugins/terminal/fish/fishd.melchior`. And you have no `fishd.melchior` file there (is in `.config/fish/` directory.
> 
> link between both locations solve problem:
> 
> ```
> sudo ln -s ~/.config/fish/fishd.melchior /opt/idea-2017.1.1/plugins/terminal/fish/fishd.melchior
> ```

Thanks. I fix similar problem with following command:
`sudo ln -s /home/username/.config/fish/fish_variables /opt/pycharm/plugins/terminal/fish/fish_variables`

**Comment by itsthejoker** [comment]
Confirming that @josselinbuils' answer fixed my issue on Ubuntu 19.04 with Pycharm 2019.1.1.

**Comment by duongricky** [comment]
> > It's because PyCharm terminal plugin search your fish config file in this location: `/opt/idea-2017.1.1/plugins/terminal/fish/fishd.melchior`. And you have no `fishd.melchior` file there (is in `.config/fish/` directory.
> > link between both locations solve problem:
> > ```
> > sudo ln -s ~/.config/fish/fishd.melchior /opt/idea-2017.1.1/plugins/terminal/fish/fishd.melchior
> > ```
> 
> Thanks. I fix similar problem with following command:
> `sudo ln -s /home/username/.config/fish/fish_variables /opt/pycharm/plugins/terminal/fish/fish_variables`

Hi, I am a Vietnamese, I am can not find folder pycharm in folder opt, help me please

**Comment by nelsonmfinda** [comment]
I tried all instructions passed here, but it doesn't solved my problem.

```
ln: failed to create symbolic link '/snap/pycharm-professional/132/plugins/terminal/fish/fish_variables': Read-only file system
```
```
ln: failed to create symbolic link '/snap/pycharm-professional/132/plugins/terminal/fish/fishd.marco': Read-only file system
```

**Comment by Valerie-Hanoka** [comment]
> I tried all instructions passed here, but it doesn't solved my problem.
> 
> ```
> ln: failed to create symbolic link '/snap/pycharm-professional/132/plugins/terminal/fish/fish_variables': Read-only file system
> ```
> 
> ```
> ln: failed to create symbolic link '/snap/pycharm-professional/132/plugins/terminal/fish/fishd.marco': Read-only file system
> ```

That's because PyCharm's fish shell integration is trying to write to the read-only snap mount directory.
Go to Settings > Tools > Terminal and unselect  `Shell integration`. Then restart your PyCharm terminal, and your problem should be fixed.

c.f.  https://youtrack.jetbrains.com/issue/PY-28526

**Comment by mattyclarkson** [comment]
IntelliJ IDEA:

  * `Ctrl + Alt + S`
  * Search for _Terminal_
  * Set shell path to `/usr/bin/env XDG_CONFIG_HOME=$HOME /usr/bin/fish`

**Comment by MichalDolinski-awin** [comment]
In Tools -> Terminal un-checking "Shell Integration" solves this issue.

**Comment by lethallunatic** [comment]
I had the same issue, was easy to fix though as it was a permission issue

Do cd ~/

Then type in ls -la 

and check the permissions for the .config file. If it looks different than the other files like for example it shows root root instead of your username username or something like username staff or username 935 whatever it is.

Type in chown username:username .config

or chown username:staff (whatever shows on that list dominantly)

After you've done this reload your fish shell and check once more if it is working as it should or not without that permission issue.

Turning of shell integration will remove a lot of functionality so I do not recommend it unless you're not going to use the shell very often
