### ISSUE TITLE
What is the equivalent variable of `$OSTYPE` in zsh

### ISSUE THREAD

**Issue by gutenye** [fish-shell/fish-shell#3994]
I need different settings  for different OS (e.g. macOS and Linux), in zsh, it has `$OSTYPE` variable.

How to do it in fish?

**Comment by gutenye** [comment]
Found it in http://stackoverflow.com/questions/26258244/is-there-a-way-to-detect-os-in-fish-shell-akin-to-the-ostype-variable-in-bash

**Comment by krader1961** [comment]
I use a combination of `uname -s` and `uname -r`. I don't like zsh's `OSTYPE` variable because it is set when zsh is compiled rather than when the shell is run. This means it might be incorrect; especially with respect to the version number.
