### ISSUE TITLE
The web config page ought to integrate with a remote component

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#4]
Imagine a server that stores color configurations.
- Users could vote on popular ones (think Adobe Kuler)
- Users could upload their own preferred scheme, and so have access to it on all their machines

This would be integrated into the web config page.

**Comment by floam** [comment]
How about a [base 16 template](https://github.com/chriskempson/base16)? I feel like every worthwhile color scheme has already been made. Actual definitions could be thrown around as JSON or YAML.

**Comment by faho** [comment]
We have theme file support, so people can upload their themes wherever they want and share them, without them being arbitrary code.

I feel like that's a better solution than connecting to a web page.

We could upload themes to fishshell.com and link to that?
