### ISSUE TITLE
eval doesn't cooperate with exec

### ISSUE THREAD

**Issue by sagebind** [fish-shell/fish-shell#4006]
I noticed that `eval` and `exec` don't cooperate as I might have expected. For example, I would expect the following:

```
nemo@2b30462d0060 ~> eval "exec sh"
```

to behave the same as:

```
nemo@2b30462d0060 ~> exec sh
```

Instead, fish seems to just get stuck in some weird background state. A session for example:

```fish
nemo@a03d1ab50f21 ~> pstree -p
fish(1)---pstree(35)
nemo@a03d1ab50f21 ~> fish
nemo@a03d1ab50f21 ~> pstree -p
fish(1)---fish(44)---pstree(62)
nemo@a03d1ab50f21 ~> eval "exec sh"
'fish' has stopped
nemo@a03d1ab50f21 ~> pstree -p
fish(1)-+-pstree(95)
        `-sh(44)---fish(90)
nemo@a03d1ab50f21 ~> jobs
Job     Group   CPU     State   Command
1       44      0%      stopped fish
nemo@a03d1ab50f21 ~>
```

Basically, instead of executing the given command and replacing the current process interactively, it executes `sh` (which also has a child `fish` process???) and then goes in the background. When not in a subshell, this behavior closes the terminal. Is it sending `SIGSTOP` to itself?

I don't know if this is the expected behavior, but it seems pretty odd to me.

I tested this in a clean `fish:2.5.0` Docker image. Standard issue info:

```fish
nemo@2b30462d0060 ~> fish --version
fish, version 2.5.0
nemo@2b30462d0060 ~> echo $version
2.5.0
nemo@2b30462d0060 ~> uname -a
Linux 2b30462d0060 4.9.13-moby #1 SMP Sat Mar 25 02:48:44 UTC 2017 x86_64 Linux
nemo@2b30462d0060 ~> echo $TERM
xterm
```

**Comment by krader1961** [comment]
This is due to weirdness in how fish manages jobs and the controlling tty. You're basically only going to see this problem when exec'ing another shell. If you exec practically any other command things work fine; e.g., `eval 'exec /bin/echo yes'`.

I'm curious why you're using `eval` to do this? It's not needed in you example. Too, eval is inherently dangerous and should be avoided if at all possible and usually can be in fish. So I'm wondering if your example is a stripped down version of what you're really trying to do.

**Comment by sagebind** [comment]
True, it's not needed in the example, but I was trying to narrow down the problem. :)

I'm exploring different ways of structuring a larger, multi-command Fish tool. One approach is to have a list of command names mapping to functions, and then select and call them dynamically. This is the specific calling mechanism I came up with:

```fish
set -l function ... # function name determined by first arg
echo "$function \$argv" | source - $command_args
```

This works great, _except_ for commands that are intentionally using `exec`.

**Comment by faho** [comment]
@sagebind: So what you really want isn't eval, but something like the `call` builtin discussed in #154 and #3596.

`eval` has a number of issues - it does some weird stuff with job control (and exposes some bugs there), it doesn't care about the division of arguments (i.e. it handles `eval arg1 arg2` just like `eval "arg1 arg2"`, so handing multiple commands to it is annoying) and most importantly: It parses the arguments _again_, so `eval $PAGER` would fail if your $PAGER includes a space in the filename. It'll execute command substitutions and expand globs (and other stuff). `call` wouldn't have those - it would just expand the commandline as usual and then execute it, as usual. `call $PAGER` would differ from `env $PAGER` only in that it could also call functions.

Obviously, the job-control issue that is exposed here should be resolved, but I'm confident that's just a manifestation of our other job-control issues, like #3952 or #206.

So I feel your pain, we have thought of a better solution for what you want to do and we already know about the bugs. So I'm closing this as a duplicate.

**Comment by sagebind** [comment]
@faho Fair enough, though just so you are aware, using `source` as described above _doesn't_ re-evaluate the arguments, they're passed in verbatim at sourcing time (hence the escape in `\$argv`).

My current workaround is to create a temporary function (if anyone else is looking for a workaround). Here's a `call` implementation using that technique:

```fish
function call -a func
  echo "function __call_wrapper; $func \$argv; end" | source
  __call_wrapper $argv[2..-1]
end
```
