### ISSUE TITLE
Yakuake displays the first letter 

### ISSUE THREAD

**Issue by opaldes** [fish-shell/fish-shell#4011]
Using fish 2.5

After using tab autocompletion i cant delete my command completly.
The first letter stays like its part of the prompt.

It seems to be an issue with thertain prompts(Nim(1letter) AcidHub(3letters))
Classic seems to work.

**Comment by krader1961** [comment]
This is usually due to either your terminal not using the same character encoding as fish or your prompt contains characters whose width fish and your terminal don't agree on. What does `locale` output? What terminal are you using and what char encoding is it configured to use? What does `fish_prompt | od -tx1z` output? If your od command doesn't support those flags try `fish_prompt | xxd`.

**Comment by opaldes** [comment]
locale: 
mostly de_DE.UTF-8.

for the prompt ouputs look at my paste:
https://pastebin.com/FY19z6Eu

**Comment by faho** [comment]
>What terminal are you using

As stated in the title, "yakuake", which is a quake-style drop-down terminal based on KDE's konsole. Incidentally, it's also the terminal I use.

>It seems to be an issue with thertain prompts(Nim(1letter) AcidHub(3letters))

I'm assuming you mean the "Nim" and "AcidHub" presets we ship.

I can't reproduce it with either, with yakuake 3.0.4 and konsole 17.04.0.

**Comment by faho** [comment]
> mostly de_DE.UTF-8.

What do you mean "mostly"? Which isn't? For me it's _entirely_ de_DE.UTF-8.

Can you record a session with [asciinema](https://asciinema.org/)?

Also, which versions of yakuake and konsole are you using?

**Comment by opaldes** [comment]
Same version as @faho.
Seems like some locale are missing.
asciinema doesnt start with an error telling me that UTF-8 locale is needed to be run

**Comment by krader1961** [comment]
Your prompt contains two non-ASCII chars: 

U+252C [BOX DRAWINGS LIGHT DOWN AND HORIZONTAL(http://www.fileformat.info/info/unicode/char/252c/index.htm)
U+2500 [BOX DRAWINGS LIGHT HORIZONTAL](http://www.fileformat.info/info/unicode/char/2500/index.htm)

The first appears once in the prompt and the second appears three times in the prompt. Fish thinks both have a width of one. If your terminal thinks either character has a width other than one you'll see the sort of artifact you're reporting. Does the problem go away if you replace those chars with a simple hyphen, `-`?

Also, as @faho asked, what do you mean "mostly de_DE.UTF-8"? When I type `locale` I get this:

```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL=
```

You should see something very similar. We want to see exactly what it outputs on your system.

**Comment by opaldes** [comment]
┬─[opaldes@opaldes-pc:~/asciinema]─[22:46:50]
╰─>$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_DE.UTF-8
LC_CTYPE="en_DE.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_DE.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES="en_DE.UTF-8"
LC_PAPER=de_DE.UTF-8
LC_NAME=de_DE.UTF-8
LC_ADDRESS=de_DE.UTF-8
LC_TELEPHONE=de_DE.UTF-8
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION=de_DE.UTF-8
LC_ALL=

**Comment by krader1961** [comment]
I see I missed a special char in your prompt:

U+2570 [BOX DRAWINGS LIGHT ARC UP AND RIGHT](http://www.fileformat.info/info/unicode/char/2570/index.htm)

Those locale error messages suggest some locale files are missing or corrupt. That will definitely cause problems.

**Comment by faho** [comment]
Ah, yes, the old "en_DE". Sometimes KDE's formatting settings will bug out and produce invalid locales like that one. Fix those and it'll work. In particular LC_CTYPE _must_ be an actual existing locale, otherwise many apps won't work correctly.

**Comment by opaldes** [comment]
could you tell me where i can edit locale?

**Comment by faho** [comment]
In systemsettings ("Systemeinstellungen"), go to "Regionaleinstellungen" -> "Formate". I've just picked "Deutschland - Deutsch" as the "Region" and skipped all the rest.

As far as I can tell, messing with the detailled settings will cause this.

Though now I see they actually have a setting for Kölsch, which seems kinda ridiculous.

![screenshot_20170504_235534](https://cloud.githubusercontent.com/assets/5185367/25726598/3a2f3108-3125-11e7-82e1-971d95dbaabd.png)

**Comment by krader1961** [comment]
I don't use KDE so I can't advise on how to fix it so the locale is correct when you open a new terminal window. But you can fix this within a given terminal by doing

```
set -x LANG de_DE.UTF-8
for v in (set --names | string match 'LC_*')
    set -e $v
end
```

After that `locale` shouldn't report any errors.

**Comment by opaldes** [comment]
@krader1961 worked like a charm thanks guys
