### ISSUE TITLE
Don't print help on error

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#4015]
In a quest to not be so darn verbose, it would be nice if our various builtins (and possibly functions) would stop printing their help if an error occured. As it is currently it can be hard to see the actual error in case of a typo or similar.

E.g. just

```
$ string banana
string: Unknown subcommand 'banana'
```

or possibly

```
$ string banana
string: Unknown subcommand 'banana'. See `string --help` for more information.
```

would be nicer than the error followed by the help synopsis.

**Comment by krader1961** [comment]
I agree with @faho. I think the existing behavior tries too hard to be friendly; to the point I find it unfriendly. Whether it should be `string --help` or `man string` is open for debate. I prefer the latter as the output will be run through my pager while the former just spews the entire doc to my screen. Although it may be better to have the `cmd --help` output also automatically run the output through the users preferred pager.

**Comment by zanchey** [comment]
I think it's very helpful for new users, as long as the manual page output is not longer than the current screen (which it often is). I wonder if there's any way to print just the synopsis or similar.

**Comment by faho** [comment]
>I wonder if there's any way to print just the synopsis or similar.

That's already what happens. The issue is that the synopsis is often already too long - for `string` it's 20 lines, while the error is one line.

E.g. for `ulimit -`, this is the output:

```fish
ulimit: Invalid limit '-'

       ulimitulimit - set or get resource usage limits
        -

   Synopsis
       ulimit [OPTIONS] [LIMIT]

ulimit: Benutzen sie 'help ulimit' für mehr Information

```

and for `string banana`:

```
string: Unknown subcommand 'banana'

       stringstring - manipulate strings
        -

   Synopsis
       string length [(-q | --quiet)] [STRING...]
       string sub [(-s | --start) START] [(-l | --length) LENGTH] [(-q | --quiet)]
                  [STRING...]
       string split [(-m | --max) MAX] [(-r | --right)] [(-q | --quiet)] SEP
                    [STRING...]
       string join [(-q | --quiet)] SEP [STRING...]
       string trim [(-l | --left)] [(-r | --right)] [(-c | --chars CHARS)]
                   [(-q | --quiet)] [STRING...]
       string escape [(-n | --no-quoted)] [STRING...]
       string match [(-a | --all)] [((-e | --entire)] [(-i | --ignore-case)] [(-r | --regex)]
                    [(-n | --index)] [(-q | --quiet)] [(-v | --invert)] PATTERN [STRING...]
       string replace [(-a | --all)] [(-f | --filter)] [(-i | --ignore-case)] [(-r | --regex)]
                      [(-q | --quiet)] PATTERN REPLACEMENT [STRING...]
       string repeat [(-n | --count)] [(-m | --max)] [(-N |Â --no-newline)]
                     [(-q | --quiet)] [STRING...]

string: Benutzen sie 'help string' für mehr Information
```
(Note: That last line means "Use 'help COMMAND' for more information". For some reason it's not changing when I change $LANG)


Now, I'd propose we cut that indented stuff - the synopsis. Either remove it completely, or at least make it a bit more compact. Remove the empty lines at least.

This is particularly annoying when the error is deep down in some function, so it might be okay to at least not print the help when the output (stdout _or_ stderr) is redirected.

For comparison, when you use an invalid command with git, it just says "'something' isn't a git command. See 'git --help'."

And then potentially some existing commands that are similar to the invalid argument (e.g. for `git lag` it suggests "log" and "tag").

**Comment by krader1961** [comment]
The main problem with the current behavior is it obscures the error message. Even for a total newbie it seems to me that making it harder to see the actual error is a net negative. Far better to put the error front and center and provide a hint about how to learn more about why the command issued that error. Especially since most of the time the error message itself is likely sufficient (obviously I'm basing this solely on my personal experience).

A CLI shell is a very different animal from a GUI program. Our current behavior is easy to justify in a GUI program. I don't think it works nearly as well in a CLI shell. What caused @faho to open this issue is something that has annoyed me from day one and still does. While some other fish behaviors initially annoyed me and I have subsequently come to love them this error message behavior is not one of them.

**Comment by krader1961** [comment]
Ugh! Type `git pull upstream master --tabs` (not the typo: `--tabs` rather than `--tags`). That produces something very similar to the current fish behavior. 

```
$ git pull upstream master --tabs
error: unknown option `tabs'
usage: git pull [<options>] [<repository> [<refspec>...]]

    -v, --verbose         be more verbose
    -q, --quiet           be more quiet
    --progress            force progress reporting
```

Plus a lot more output from `git`. I am still not a fan of that behavior.

**Comment by zanchey** [comment]
See also #3404.

**Comment by faho** [comment]
So, this is a duplicate of #3404.
