### ISSUE TITLE
allow vi (xterm mechanism) title to be set as tab title

### ISSUE THREAD

**Issue by jlsjonas** [fish-shell/fish-shell#4018]
provide an option to allow xterm titles to be passed to the tab (maybe using a custom env var so you can still customize it using fish_title?)

**Comment by faho** [comment]
I'm sorry, I don't quite understand what you mean.

What is an "xterm title" in this context, what does vi have to do with it?

**Comment by krader1961** [comment]
Like @faho I don't understand what you are requesting, @jlsjonas, since xterm does not support tabbed windows AFAIK.

**Comment by faho** [comment]
@jlsjonas: Ping? We don't understand what you are asking, so we're gonna need some more explanation.

**Comment by krader1961** [comment]
@jlsjonas: I'm going to close this because we don't understand the change in behavior you are requesting and you haven't responded to our requests for clarification. Please reopen this if you can provide more details regarding the change you desire.
