### ISSUE TITLE
Question: Separating funced from the VISUAL variable

### ISSUE THREAD

**Issue by okamsn** [fish-shell/fish-shell#4022]
Hello,

I am currently enjoying my Fish experience on Linux Mint 18, and have a question.

For various applications, I have the VISUAL and EDITOR variables set to nano.
For Fish's function 'funced', it uses these variables to open nano to edit the function. I would prefer to just use Fish's own commandline editor for this, given the colorful feedback and tabbing interactions.

Is there a way to separate the editor Fish uses ( which I wish to be it's own) while keeping these variables set? Some variable "fish_editor" or similar of which I'm unaware? I've gone through the documentation on the website, but have yet to find an answer.

 Thank you.

**Comment by krader1961** [comment]
No, but you can get the desired result by typing `funced -i $func_name`. But note that the internal editor has serious limitations. In particular if the length of the function is longer the the height of the terminal. So I don't advice it except for tiny functions.

**Comment by faho** [comment]
I am assuming this question has been answered, so I'm closing this.

If you have any follow-ups, feel free to ask here. If you have any unrelated problems or questions, please open another issue.
