### ISSUE TITLE
document limitations of fish "default/emacs" and "vi" mode editor

### ISSUE THREAD

**Issue by simonnier** [fish-shell/fish-shell#4023]
I am using fish, version 2.5.0

I set fish_vi_key_bindings in my configure.

vi mode is great. However, I found number + b is not working, for example 5b doesn't move backward 5 words. But moving back and forth is the  most frequent operation in shell.

**Comment by krader1961** [comment]
Fish vi mode does not support numeric prefixes. Neither does emacs (i.e., default) mode. And probably never will. Or at least not in my lifetime. See the `edit_command_buffer` function that was introduced a few months ago and is bound to `\ev` and `\ee` (e.g., by pressing [alt-V]) to drop you into your preferred editor when you need to use advanced editing capabilities such as numeric prefixes. The reality is that fish will never implement more than a very tiny subset of emacs/vi/vim.

Having said that we'd love to see someone, like yourself, who is sufficiently motivated implement this feature within fish.

**Comment by balabi0github** [comment]
@krader1961 Thank you so much for quick reply : )

**Comment by krader1961** [comment]
@balabi0github, Do you have any suggestions for how we can better document the limitations of our internal editor? I don't really expect you, or any other user, to improve it despite my previous, somewhat snarky, response. But it would be helpful to know how we can improve the documentation. How did you learn about fish support for vi mode editing?

**Comment by balabi0github** [comment]
@krader1961 Yeah, you are right. I am not software engineer with that capability : )   I learned vi mode in the official documentation. I read it again just now, and it seems that it doesn't mention that vi mode is limited.  And to a vi user, number+command is somewhat a trademark for vi, so I thought it maybe implemented.

**Comment by krader1961** [comment]
Good to know, @balabi0github. We will try to improve our documentation to make such limitations clearer. I am going to leave this open, and change the heading, to make it clear we need to better document the limitations of fish vi mode.

**Comment by faho** [comment]
We have documented the editor.
