### ISSUE TITLE
preexec event functions should get the expanded command line

### ISSUE THREAD

**Issue by nhooyr** [fish-shell/fish-shell#4037]
I'm on fish 2.5.0 and macOS 10.12.5

1. `sh -c 'env HOME=$(mktemp -d) fish'`
2.
```fish
function preexec --on-event fish_preexec
  echo $argv
end
```
3. `echo ~/tmp`

I'd expect the preexec function to get the command line with `~/tmp` expanded but instead, it gets literally `~/tmp`. This is a problem with FASD, because it needs to keep tracks of paths, it does not do path expansion on its own because it expects the shell to do it.

And `$argv` should be an array of the arguments, not just a string.

**Comment by nhooyr** [comment]
In addition, I noticed that `preexec` is not triggered before running `cd`. I think this is intended, and if I want to trigger it, I would have to redefine cd as a function?

**Comment by nhooyr** [comment]
With all of fish's autocompletion, I think fasd is unnecessary so I've just removed it. Unless this behaviour is considered a bug and unintended, I think this issue can be closed.

**Comment by zanchey** [comment]
#477 requested that the arguments be parsed before being passed to the preexec function, but the implementation does not do that at this stage.

**Comment by nhooyr** [comment]
That issue points out another problem with the implementation, the event should be emitted for every single job, not the entire command line like it currently is.

**Comment by krader1961** [comment]
> I'd expect the preexec function to get the command line with ~/tmp expanded but instead, it gets literally ~/tmp.

Why would you expect that? The documentation says that the function for that event gets the command line as the first parameter. Should variable references also be expanded? If not why should path names be treated differently? And if such things are expanded 

You also say that

> the event should be emitted for every single command, not the entire command line.

But the documentation is reasonably clear that it is called for the entire command line, not individual commands.

We couldn't change the behavior of the `preexec` event even in a major release. The disruption would be too great. It might be useful to add new events. For example, one that receives the individual tokens for each command about to be executed. That is, `$argv` would be an array of the command tokens after all expansions and interpolations for such an event. But we can't modify the `preexec` function to behave that way. Feel free to open an enhancement request explaining why such a feature would be useful and how it should work in concrete details.
