### ISSUE TITLE
Git auto-completes produces invalid paths

### ISSUE THREAD

**Issue by Dorian** [fish-shell/fish-shell#4041]
### Steps:

```
> mkdir bug
> cd bug/
> git init
Initialized empty Git repository in /Users/d/src/tmp/bug/.git/
> touch a_a
> touch a_b
> git add a_ # tab
fatal: pathspec 'a_' did not match any files
```

### Expected:

Auto-completes with `a_a` and rotate to `a_b` if tabbed again.

### Actual:

Auto-completes to `a_` which is an invalid git path.

### System info

```
> fish --version
fish, version 2.5.0
> echo $version
2.5.0
> uname -a
Darwin D 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64
> echo $TERM
xterm-256color
``

**Comment by faho** [comment]
Press TAB again. We complete to the common element first, and only open the pager after another TAB. When this happens, the cursor stays at the end of the token - if we managed to complete something fully, we add a space.

This isn't specific to the git completions.

**Comment by Dorian** [comment]
@faho Thanks
