### ISSUE TITLE
Is there a way to set the whole current edit line rather than just append to it?

### ISSUE THREAD

**Issue by plainas** [fish-shell/fish-shell#4042]
I would have much use to such feature. Trigger the autocomplete, but then, instead of appending to the current line, the selected contents would be put in the editline, replacing whatever was there.

Is this possible?

**Comment by faho** [comment]
What is your use for this? Do you have an example?

It is possible to programmatically alter the commandline in a variety of ways, e.g. `commandline -r something` will replace the commandline with "something". I don't think it is possible to get the completion system to do this.

If I understand you correctly, what you want is a way to trigger our pager to do other things - see #4036, which is still being discussed.

**Comment by plainas** [comment]
The use case is having the autocomplete trigger something that outputs a list of runable commands, possibly tricky or long, and being able to either execute them or tweaking the a little bit.

For example, I could put a bunch of one line snippets in a file and than have autocomplete trigger `cat myoneliners.txt` to pick one.

I will look into #4036 and check if it does what I want.

**Comment by zanchey** [comment]
Am I correct in understanding that you are talking about completion (what happens when you push tab), not autosuggestion (the automatically-presented history-derived hint)?

**Comment by plainas** [comment]
Completion.

I think, as suggested by faho, the problem could be solved by being able to trigger the pager from a script or function. If I can do that, then I can call `commandline -r` ( which I was not aware of) and place whatever I want in the current command buffer.

**Comment by faho** [comment]
Yes. Closing in favor of #4036 then. If that was implemented, you could set up a binding to do this.
