### ISSUE TITLE
ipconfig opens a separate console window in Cygwin

### ISSUE THREAD

**Issue by andrex-e-schulman** [fish-shell/fish-shell#4044]
In Cygwin fish, when I run the Windows command `ipconfig`, a new terminal window opens, the output flashes on it, and then the terminal closes. It all happens too fast for me to see and then is gone, so I can't see the results.

By comparison, in Cygwin bash when I run `ipconfig`, I get output in my console. That output apparently doesn't come through stdout or stderr, since when I try to grep it the result is always empty. But at least it stays in my same console window where I can read it.

fish 2.6b1 in Cygwin 2.8.0-1 x86_64, using mintty. I tried without 3rd-party customizations and got the same result. I get the same results in a native console window (`TERM=cygwin`) or mintty with screen (`TERM=screen-256color`).

**Comment by faho** [comment]
The obvious thing to check here is `type ipconfig`.

**Comment by andrex-e-schulman** [comment]
Good point.

    ASchulma@host ~> type ipconfig
    ipconfig is /win/c/Windows/System32/ipconfig

**Comment by krader1961** [comment]
Works for me. However I do not have a */win* directory and `type ipconfig` reports */cygdrive/c/WINDOWS/system32/ipconfig*. My config, both fish and cygwin, is bog standard. Also, doing `ipconfig >output` works fine in fish and bash inside a cygwin mintty window. So I submit to you that the ipconfig command you're running is not the normal one.

What does `type ipconfig` report for bash? Is it perhaps a different path than that reported by fish?

**Comment by andrex-e-schulman** [comment]
`/win` is a red herring - sorry. It's just my custom cygdrive prefix, as I set in the "cygdrive" line of /etc/fstab. If I change that back to the default /cygdrive, then I get the same response as you:

    ASchulma@host ~> type ipconfig
    ipconfig is /cygdrive/c/Windows/System32/ipconfig

and the behavior is the same. So that is the system ipconfig command.

In bash though, I find that ipconfig is aliased:

    $ /cygdrive/c/Windows/System32/ipconfig  # new console window opens, flashes and is gone
    $ alias ipconfig
    alias ipconfig='cmd /C ipconfig'
    $ cmd /C C:/windows/system32/ipconfig
    Windows IP Configuration
    
    Ethernet adapter Bluetooth Network Connection:
    ...

So bash has the same problem, and apparently I found a workaround there and made an alias for it, back when I was using bash. But that workaround doesn't work for me in fish:

    ASchulma@host ~> cmd /C C:/Windows/System32/ipconfig # nothing happens at all: no new console window, no output
    ASchulma@host ~>

So the issue is a little different than I thought:

* ipconfig opens a separate console window in both bash and fish, so that's apparently not a fish issue.
* `cmd /C ipconfig` returns output for me in bash, but not in fish.

**Comment by krader1961** [comment]
I don't have such an alias. And typing `cmd /C C:/windows/systems32/ipconfig` in bash and fish behaves just fine. Which it should since you're just doing the rough equivalent of `sh -c ipconfig`. Note that I'm doing this with Cygwin 2.7.2 on Windows 10. I'll update Cygwin to see if that changes the behavior but that seems pretty unlikely. More likely is you're using a different version of MS Windows which for some reason has a ipconfig that behaves differently.

**Comment by krader1961** [comment]
I updated Cygwin to 2.8.0 and this still works correctly for me. I can even `ipconfig | grep Default` from bash and fish and it properly filters the output. So something is definitely broken on your system and it's not fish.

**Comment by andrex-e-schulman** [comment]
OK. Yeah, I just checked on another Windows 7 host, and it works as expected there. So you're right, not fish's fault. Thanks for looking into it, and sorry for the noise.
