### ISSUE TITLE
Help is broken (different error then the other bug report)

### ISSUE THREAD

**Issue by gregcoit** [fish-shell/fish-shell#4045]
fish, version 2.5.0
3.10.0-514.10.2.el7.centos.plus.x86_64
xterm-color

Installed via source and from the http://download.opensuse.org/repositories/shells:fish:release:2/CentOS_7/shells:fish:release:2.repo repo - both have the same error:

```
root@greg ~# help
fish: Unknown command 'file:///usr/local/share/doc/fish/index.html'
- (line 1): begin; file:///usr/local/share/doc/fish/index.html
                   ^
from sourcing file -
	called on line 60 of file /usr/local/share/fish/functions/eval.fish

in function “eval”
	called on line 149 of file /usr/local/share/fish/functions/help.fish

in function “help”
	called on standard input

root@greg ~#
```

**Comment by faho** [comment]
It appears you don't have a browser installed.

To check, please run `type htmlview x-www-browser firefox galeon mozilla konqueror epiphany opera netscape rekonq google-chrome chromium-browser htmlview www-browser links elinks lynx w3m ^/dev/null`?

Now this is supposed to print a nicer error message and exit (that's a bug), but without a browser, help won't actually function.

**Comment by faho** [comment]
@zanchey: I recommend 036b708 for 2.6.0.

**Comment by krader1961** [comment]
I can reproduce this error on a Ubuntu server with no web browser (or desktop environment for that matter) installed. And @faho's change fixes it by producing a more useful error message.

**Comment by zanchey** [comment]
Cherry-picked to 2.6.0 as 3cca94b.
