### ISSUE TITLE
can't execute substitutive portion of a command

### ISSUE THREAD

**Issue by nzimas** [fish-shell/fish-shell#4046]
Fish, version 2.2.0

MacOS 10.2
Darwin blah.local 16.0.0 Darwin Kernel Version 16.0.0: Mon Aug 29 17:56:20 PDT 2016; root:xnu-3789.1.32~3/RELEASE_X86_64 x86_64

Terminal: xterm-256color

I sometimes need to clean up all my Docker images and containers.
If I do it from BASH, the command **docker rm $(docker ps -a -q)** will get all containers removed, as expected.
In order to make the same command run in FISH, I change it to **docker rm '(docker ps -a -q)'**
Nevertheless, Docker won't execute the substitution properly and claims that **'(docker ps -a -q)'** is the name of a container.

_Error response from daemon: No such container: (docker ps -a -q)_

**Comment by faho** [comment]
It's `docker rm (docker ps -a -q)` without the quotes.

**Comment by nzimas** [comment]
Thanks a lot for the quick reply!

I've merely followed Fish's own suggestion after executing the substitution part a la BASH (or my understanding of them).

_> docker rm $(docker ps -a -q)
$(...) is not supported. In fish, please use '(docker)'.
fish: docker rm $(docker ps -a -q)_

**Comment by faho** [comment]
Huh, yeah that clarifies the misunderstanding. I'm not quite sure if removing the quotes would clarify the message.

I mean we have other messages like `fish: $@ is not supported. In fish, please use $argv.` without quotes, but since parentheses can also be used in an english sentence it seems likelier that it might be misinterpreted. Backticks ("`", used for code-blocks in markdown) wouldn't be better than quotes and depending on the font might even look like them.

It would be possible to introduce color here, but that's a bigger undertaking.

Do you have any ideas?

**Comment by faho** [comment]
Oh, also:

>Fish, version 2.2.0

You really want to upgrade. We have made 3 releases since then and are in beta for the fourth.

**Comment by krader1961** [comment]
> I'm not quite sure if removing the quotes would clarify the message.

Doing so might be marginally better in this specific message. Although as you noted, @faho, a bare pair of parens has its own ambiguity. In general we use quotes in such situations to wrap the portion that is meant to be treated literally (i.e., copy-pasted). I think we should continue to use that convention. And to the extent there are similar messages which don't use that pattern the quote chars should be added.

**Comment by krader1961** [comment]
Closing since the original question has been answered and it seems pretty clear we want to retain the quote characters in these types of messages.

**Comment by BugKiller-tech** [comment]
> It's `docker rm (docker ps -a -q)` without the quotes.

This is not working for me. Please help me out for this issue.

**Comment by faho** [comment]
@BugKiller-tech Please put yourself in our shoes. We don't sit at your computer, we don't know you, we have literally no context. Without that, we have no way to help you.

So: What are you trying to do? What happens when you do it?
