### ISSUE TITLE
autosuggestion hides the same history navigation item

### ISSUE THREAD

**Issue by maxfl** [fish-shell/fish-shell#405]
I found that I can not use 'Up' key to get the last item from the history if item is autosuggested.
For example:

``` sh
echo test_string #Enter
echo tes<Cursor>
```

echo test_string is then autosuggested and I can not get it from the history by pressing 'UP' key. This is very annoying, since it requires distinguishing which key should be pressed: Up or CtrlF. 

I can see two ways of solving this: whether use Up key to use autosuggestion first, either not to delete autosuggested item from the history.

**Comment by krader1961** [comment]
Closing. No comments in 4.3 years to justify changing the current behavior.

**Comment by gagarine** [comment]
I installed fish, and that was the first things I searched.
