### ISSUE TITLE
How can I get the full path of a file except the extension like bash shell?

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#4056]
in bash:

    file=/tmp/test.cpp
    echo "${file%.*}"

will get

    /tmp/test

but the expression `echo "${file%.*}"` is not valid in fish shell, how can I do that in fish shell in a simple way like bash shell?

**Comment by krader1961** [comment]
```
set x abc.def.ghi
echo (string split -r -m1 . $x)[1]
```

**Comment by c02y** [comment]
Sorry about that, I should have checked [documentation](https://fishshell.com/docs/current/index.html) first .
