### ISSUE TITLE
`somebuiltin -h` no longer works

### ISSUE THREAD

**Issue by kballard** [fish-shell/fish-shell#4058]
In previous versions of Fish, most builtins accepted the `-h` flag and would show their manpage. In current master this appears to be broken; every builtin I've tried it with just emits a single blank line. `man somebuiltin` still works, so the manpages are installed.

Example:

```
prompt> function -h

prompt>
```

Reproduced with fish 2.5.0-405-ga71bb03f

**Comment by kballard** [comment]
I just confirmed, `status -h` worked in version 2.2.0-639-gd8a4974, fails in current master.

**Comment by kballard** [comment]
I figured it out. It's because `"$__fish_datadir/groff"` isn't installed when installing with Xcode, but 222a07e907c239f7dab541512b109730a07828dc added the `-mfish` flag to `nroff`, so now `nroff` is failing because it can't find the macro "fish".

**Comment by kballard** [comment]
Looks like there's actually a bunch of stuff that `xcodebuild install` misses. We should probably remove the instructions to do that and have everybody just use `make` instead.

**Comment by krader1961** [comment]
Does the macOS fish.pkg we make available on fishshell.com have the same problems? If so we need to fix this. If not then, yes, anyone installing fish by hand on macOS should just be using `make install` and we should drop the instructions about using xcodebuild.

**Comment by kballard** [comment]
@krader1961 Yep, it's missing it.

<img width="808" alt="screen shot 2017-05-23 at 8 00 37 pm" src="https://cloud.githubusercontent.com/assets/714/26385165/818524f0-3ff2-11e7-9569-720084f36d22.png">

I also ran both `xcodebuild install` and `make install DESTDIR=/tmp/foo` and diffed the contents and there's a lot of stuff missing from the xcode version. So if we're going to fix the Xcode install we need to handle all of those too. It's probably easier just to fix the package creation to use `make install` instead of Xcode though.

**Comment by kballard** [comment]
I'm going to file this as a separate ticket because I have a patch to fix specifically `status -h` right now.

**Comment by kballard** [comment]
Filed as #4060.
