### ISSUE TITLE
`trap` broken on macOS

### ISSUE THREAD

**Issue by kballard** [fish-shell/fish-shell#4059]
The `trap` command is very broken on macOS. This is because it ends up calling (non-GNU) `getopt`, which itself is rather broken and doesn't quote the output. This means that a line like `trap 'echo foo' EXIT` gets interpreted exactly the same as `trap echo foo EXIT` and thinks `foo` is the signal.

It looks like `umask` is also using this broken `getopt`, but I'm not sure if it actually matters here.

**Comment by krader1961** [comment]
I hadn't noticed this bug because I use Homebrew to install GNU variants for things like `getopt`. This is another example for why we really should ship our own `fish_getopt` function that leverages our *wgetopt.cpp* module.

**Comment by kballard** [comment]
I completely agree. I almost filed a ticket suggesting specifically that, but I hadn't yet searched to make sure we didn't already have something similar lying around.

**Comment by krader1961** [comment]
This should be fixed with my recent changes to implement the `argparse` builtin and updating the `trap` function to use it.
