### ISSUE TITLE
Included themes should define colors for special characters

### ISSUE THREAD

**Issue by melissaboiko** [fish-shell/fish-shell#406]
I think it would be cool if all special characters came in a different color by default.
- Currently, `>`,`<`, and `^` are not highlighted in any way unless the user sets `fish_color_redirection` explicitly . Coming from sh, I was a bit surprised that `grep ^foo file` didn't work as expected, until I realized `^` was special.
- It seems there's no way to set a different color for `&` , `|`, `;` .

**Comment by floam** [comment]
> & , |, ; .

`set fish_color_end magenta`.

You can get all this stuff, I think, between: `fish_color_operator`, `fish_color_end`, `fish_color_redirection`, `fish_color_escape`.

**Comment by floam** [comment]
> I think it would be cool if all special characters came in a different color **by default**.

**Comment by KiranWells** [comment]
This should just require adding an "operator" and "escape" setting in colorutils.js, right? Although controller.js might need to be modified to allow "escape".

Wanted to make sure before I start working on this.

**Comment by faho** [comment]
>This should just require adding an "operator" and "escape" setting in colorutils.js, right? Although controller.js might need to be modified to allow "escape".

@KiranWells Yes, that seems correct. Of course they'd have to have sensible values (for which I'm of approximately no help).

**Comment by faho** [comment]
Okay, all our themes now have $fish_color_operator, $fish_color_escape and $fish_color_redirection set. I believe that covers everything.
