### ISSUE TITLE
Xcode install missing a lot of files, pkg installer broken

### ISSUE THREAD

**Issue by lilyball** [fish-shell/fish-shell#4060]
`xcodebuild install` is missing a lot of files that `make install` installs. #4057 adds a separate `make install-doc` that can be used with the Xcodebuild install to get docs, but here's a list of all the other files that are missing:

```
/usr/local/bin/fish_key_reader
/usr/local/etc/fish/conf.d
/usr/local/share/fish/__fish_build_paths.fish
/usr/local/share/fish/groff
/usr/local/share/fish/vendor_completions.d
/usr/local/share/fish/vendor_conf.d
/usr/local/share/fish/vendor_functions.d
/usr/local/share/man/man1/fish_key_reader.1
/usr/local/share/pkgconfig
```

It seems the package installer on fishshell.com is built using the Xcode install, because it's also missing all of these files/folders.

**Comment by ridiculousfish** [comment]
I'll see what it takes to get these added.

**Comment by kballard** [comment]
For most of this, we could refactor `make install` into a separate script that installs all the ancillary files, and then both the Makefile and an Xcode script phase build step could simply invoke that step.

Not sure about `fish_key_reader` though. That appears to be a binary that is compiled by `make`, and Xcode is apparently not compiling it at all.

**Comment by zanchey** [comment]
Hopefully CMake will help here.

**Comment by faho** [comment]
I'm assuming this is fixed by us not shipping an xcode script anymore.
