### ISSUE TITLE
history-token-search-backward stopped including redirection targets

### ISSUE THREAD

**Issue by nyarly** [fish-shell/fish-shell#4065]
Fish 2.5 on
Linux perlman 4.9.24 #1-NixOS SMP Fri Apr 21 07:31:39 UTC 2017 x86_64 GNU/Linux
and urxvt

Since updating to 2.5, I've noticed that Alt+Up no longer includes redirection targets.

e.g.
```
⮀ echo test > target
⮀ cat [Alt+Up]test
```
where what I want and expect is `target`. Behavior is the same under stock `fish`.

**Comment by krader1961** [comment]
Thanks for the bug report. This bisects to my lint cleanup in commit 21521b295397f44d073e94276b8b761f009410ea on 2016-10-22. Apparently there was something subtle about the use of the `switch` statement somewhere in the code that I didn't appreciate when I eliminated a bunch of "too few branches in switch statement" lint warnings.

**Comment by krader1961** [comment]
Okay, I found the mistake. I'll cherry-pick the fix into the 2.6.0 branch as soon as I've reviewed the rest of the change for any other mistakes of that sort.
