### ISSUE TITLE
[Question] Guide to version controlling fish config

### ISSUE THREAD

**Issue by pruett** [fish-shell/fish-shell#4067]
```
> fish --version
fish, version 2.5.0

> uname -s
Darwin
```

I'm struggling a bit with finding a good way to version control my fish config for use on multiple machines. In particular, I'm not sure how to handle the `fishd.<id>` file. Additionally, I'm not sure how to handle the integration with [fisherman](https://github.com/fisherman/fisherman) as it installs `.fish` files in the `functions` directory which are treated as symlinks. At the moment I'm simply symlinking `~/path/to/my/dotfiles/config` folder to `~/.config`.

Is there a preferred way to handle version control/symlinking of the config folder?

**Comment by krader1961** [comment]
For version control just use whatever RCS tool you're comfortable with. For me that's `git`. Just `cd ~/.config/fish; git init; git add .; git commit`. However, I suspect your real question is something different. I get the sense you're really asking how to keep the "global" parts of your config (e.g., the *~/.config/fish/config.fish* file) in sync across all your machines while not stomping on local customizations. Such as the uvar file or a plugin you've installed on one machine but not others.

**Comment by pruett** [comment]
@krader1961 correct, apologies as I'm a newcomer to fish and don't know what a `uvar` file is...is that the `fishd.<id>` file?

For reference this is my dotfiles repo at the moment, https://github.com/pruett/d0t

Most of the functions https://github.com/pruett/d0t/tree/master/config.dotfile/fish/functions are symlinked...this is not an issue with fish at all, but I'm curious if I'm doing something wrong or if I should `.gitignore` all the fisherman-installled functions?

Any advice suggestions are very welcome. Thanks so much!

**Comment by krader1961** [comment]
Yes, "uvar" is short for "universal variable" and they are stored in the *fishd* file.

As long as the symlinks are relative their existence shouldn't matter. I use two methods to sync my config. For my three primary systems, the ones I use every day, have my *~/.config* stored on Dropbox and symlink to it. That way they always have the same config without any need to manually sync my config. For the other systems I use infrequently (mostly virtual machines) I have a shell script named *sync-home* that I run. It contains commands like the following:

```
rsync --verbose --archive --delete -L --exclude 'fishd.*' $server:.config .
rsync --verbose --archive --delete -L $server:.vim .
```

Where `$server` is the FQDN of my primary server.

**Comment by kballard** [comment]
Personally, I use [Unison](http://www.cis.upenn.edu/~bcpierce/unison/) to sync config files (among other things).

**Comment by krader1961** [comment]
Unison is awesome. For the benefit of the O.P. I am not using it for this specific problem because I never want bidirectional syncing. If I modify my fish config on anything other than my three primary systems I do not want those changes reflected back to those primary systems. I would use Unison to sync my three primary systems but I find it easier and more flexible to use a remote filesystem like Dropbox to host the files.

**Comment by kballard** [comment]
Oh yeah, if I'm not on one of my primary systems and I want to grab config, I just rsync it off of the server I use for syncing my Unison stuff.

**Comment by krader1961** [comment]
Closing since I believe we have answered the question. Feel free to reopen if that is not true.
