### ISSUE TITLE
`type -a $cmd` no longer produces correct output

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#4070]
I recently noticed that `type -a ls` reports that every command in $PATH matches `ls`. Looks like commit a3f28e221 to remove our dependency on `which` broke this.

**Comment by faho** [comment]
AAAARGH!

Yes, of course!

The issue is simple - `for file in $PATH/*` should be `for file in $PATH/$i`.

I'll commit.

**Comment by faho** [comment]
@zanchey: This _needs_ to be in 2.6.0.

**Comment by krader1961** [comment]
> This needs to be in 2.6.0.

Done: commit 44830589a on the integration branch.
