### ISSUE TITLE
should we localize completion and function descriptions?

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#4073]
While working on addressing issue #4068 I could not find any documentation for how to update the message localization files in the *po* directory. Reading *Makefile.in* suggested I should run `make messages.pot` but that fails (on Ubuntu) with 

```
xgettext: error while opening "share/fish.config" for reading: No such file or directory
Makefile:542: recipe for target 'messages.pot' failed
```

Even if I am missing the obvious this should be documented in the *CONTRIBUTING.md* file.

**Comment by faho** [comment]
>"share/fish.config"

Well, that's obviously an error in the makefile - it's "config.fish", not "fish.config". I've fixed it now.

So, where would you expect documentation regarding localization? In README.md? The wiki? CONTRIBUTING.md?

**Comment by zanchey** [comment]
I took it out of the manual and moved it to https://github.com/fish-shell/fish-shell/wiki/Translations

**Comment by krader1961** [comment]
Thanks for the pointer, @zanchey. It seldom occurs to me to check the Wiki. I'll add the relevant paragraph about the make target to the contributing doc along with a pointer to the wiki.

**Comment by zanchey** [comment]
Relevant commit was 8214ae9b15a which predated the contributing guide as such.

**Comment by krader1961** [comment]
Another question: I ran `make po/de.po` to see how big the diff would be. It was huge. What I noticed is that a lot of translations were being removed. One that caught my eye was this one:

```
-#~ msgid "Specify the http username"
-#~ msgstr "http-Benutzername angeben"
```

Some of the descriptions from *share/completions/wget.fish* that aren't being extracted:

```
complete -c wget -l http-user --description "Specify the http username" -xa "(__fish_complete_users)"
complete -c wget -l http-passwd --description "Specify the http password" -x
complete -c wget -f -r -l secure-protocol -a 'auto SSLv2 SSLv3 TLSv1 PFS' --description "Choose secure protocol"
```

I can't see a pattern. Similar `complete` commands are getting their description extracted. Can someone with more experience doing this (@faho?) take a look?

**Comment by zanchey** [comment]
It's because those descriptions have the `--description` keyword in an odd-numbered position!

We're relying on a bug in `xgettext` here - there is significant discussion in #1675 and discussed upstream at https://lists.gnu.org/archive/html/bug-gettext/2014-11/msg00004.html

The right thing to do here is to build a small `fish_xgettext` helper which uses the parser to dump out all the description strings from fish files.

**Comment by krader1961** [comment]
I've written a simple implementation of @zanchey's proposed `fish_xgettext` script and incorporated it into the makefile `messages.pot` build target. It results in 6334 additional messages being included in the *de/de.po* translation file as measured by `grep -c '^msgid ' po/de.po`. A significant percentage of those additional messages are due to my rewriting `-d` to `--description` so as to be recognized by xgettext. Note, the current xgettext extraction doesn't recognize messages defined by the description short flag -- only the long flag. A smaller percentage is due to working around the xgettext quirk discussed above.

So this begs the question. Do we really want to translate every `complete` and `function` description?

Here is the implementation I just tested:

```
#!/usr/bin/env fish
# This is needed to work around a quirk (or bug depending on your viewpoint) of the xgettext
# command. See https://lists.gnu.org/archive/html/bug-gettext/2014-11/msg00006.html.
sed -E -n -e '/(^| )(complete|function) .* (-d|--description) /s/^.* (-d|--description) [\'"]([^\'"]+).*/command x --description "\2"/p' \
    share/config.fish share/completions/*.fish share/functions/*.fish | sort -u > /tmp/x
```

I modified the *Makefile.in* to call that and then invoke `xgettext` against */tmp/x* rather than the original scripts.

**Comment by zanchey** [comment]
I don't think it's worth it - it would be better to have complete descriptions for the fish messages first - but I don't use a translation.

**Comment by krader1961** [comment]
@zanchey, What if we could make it clear that some messages are from the core C++ implementation and others are not and thus wholly optional to be translated? Speaking for myself I don't think we can justify translating any messages in the fish scripts we ship. But I am biased as a native English language user. I do however think we need to either abandon any attempt to completion and function description in fish script or properly handle them. The current situation of translating what amounts to a random subset of those descriptions is not acceptable.

**Comment by krader1961** [comment]
I have changed the summary line for this issue because the original problem was trivial and has been fixed. Which caused me to realize there is a deeper problem. Specifically, most `complete` and `function` descriptions are not in the message translation files. As I wrote in my previous comments I think we should either

a) stop trying to translate `complete` and `function` descriptions, or
b) correctly handle all such messages.

Even my tentative fix is not guaranteed to recognize 100% of such descriptions since it is based on a simplistic regex. But I'm willing to bet it handles 99.9% of them. The question is whether we want to include more than 6300 new messages from those scripts in the translation files.

**Comment by zanchey** [comment]
The messages in `share/functions` are worth translating, but I don't think the `share/completions` messages are.

**Comment by faho** [comment]
>The messages in share/functions are worth translating, but I don't think the share/completions messages are.

I respectfully disagree - the point of translating something is that people can then enjoy it in their native language, especially _if they don't speak the original_. If we have some things we deem "not worthy of translation", then that means we don't deem those things worthy of being read by our users.

Of course translation isn't an "all or nothing" thing. It's not like an incomplete version is worthless, but it's a gradient - the closer to complete, the better.

>The question is whether we want to include more than 6300 new messages from those scripts in the translation files.

Well, that's just the amount of messages we have (and there are gonna be a bunch more, since I haven't really been diligent with using gettext everywhere).

**Comment by zanchey** [comment]
That's a good way of looking at it - I'm aware that I have never needed translations in my software!

**Comment by krader1961** [comment]
I see my earlier comment said something other than what I intended. We definitely want every message explicitly tagged to be localized via the `N_` and `_` functions (the core messages) to be extracted and translated. What is harder to justify is the 6000+ description strings for completions and functions. I do think they should be extracted into the translation file. But ideally they would appear at the end of the file with a clear header explaining how they are used and that they are of secondary importance. Primarily so that people motivated to provide translations can readily focus on the most important messages. Then, if they are so inclined, also translate the descriptions.

**Comment by faho** [comment]
> But ideally they would appear at the end of the file with a clear header explaining how they are used and that they are of secondary importance. Primarily so that people motivated to provide translations can readily focus on the most important messages. Then, if they are so inclined, also translate the descriptions.

And that's okay. These messages are less likely to be seen (only if you use a particular command, which you might not even _have installed_), and they have smaller effect - obviously an error that you need to react to has more importance than something that just describes the kind of argument you are completing.

**Comment by krader1961** [comment]
OMFG! The current mechanism for extracting messages that need to be localized from fish script is badly broken. Beyond the issue discussed above. The `xgettext` tool does not correctly parse single quoted strings. Or strings that have backslashed quote characters. Or strings that are not quoted but use backslashes to escape space characters. And many other constructs that appear in our scripts. There are a large number of explicitly localized messages that are not extracted into the translation file by `xgettext`. Such as this one from *completions/emerge.fish*:

```
'@preserved-rebuild\t"'(_ 'Packages that are linked to preserved libs')'" '\
```

I'll grant you that is a particularly obtuse example. Nonetheless, the reality is that the current mechanism for extracting messages for translation is more broken than I realized when I opened this issue.

**Comment by krader1961** [comment]
Here is another example of how broken fish script translations are at this time. Consider this line in *share/functions/help.fish*:

```
printf (_ '%s: Could not find a web browser.\n') help
```

The current message extraction doubles the backslash. Which doesn't happen for C++ source code. That additional backslash in the msgid in the translation file means that the translation file contains this:

```
#~ msgid "%s: Could not find a web browser.\\n"
#~ msgstr "Konnte keinen Webbrowser finden.\\n"
```

In addition to the extra backslash the `#~` prefix means the message is not present in the source at this time. That is, the message is obsolete. Yet the message is present.
