### ISSUE TITLE
How to change the path order/priotiry of PATH variable?

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#4087]
- fish, version 2.5.0
- platform: CentOS 6.5, 32-bit

I installed multiple versions of python in my system, such as python2.6 (builtin), python2.7, python 3.4, they are all installed in `/usr/lib` or `/usr/local/lib` and the executable files such as python2.7 or python3.4 are in `/usr/bin` or `/usr/local/bin`.

Then I found anaconda is very useful and I wanted to use anaconda as the default python and packages manager, so I installed it in `$HOME/anaconda3`, and added `$HOME/anaconda3/bin` to `PATH` variable in `config.fish` file , but when I execute python or python3 or with `--version`  or `which python3` in the terminal, the path will be in `/usr/bin` or `/usr/local/bin` but what I want is the executable file in `$HOME/anaconda3/bin/python3`, other packages such as `ipython` with the same names are both existed in `/usr/bin` or `/usr/local/bin` and `$HOME/anaconda3/bin`.

So when multiple executable files are in different path such as system path like `/usr/bin` and another path in my home directory such as `$HOME/anaconda3/bin`, how to I set the PATH variable in fish-shell to let the terminal know that search the executable file in the specific path such as `$HOME/anaconda3/bin` first?

**Comment by krader1961** [comment]
The elements of `$PATH` are searched left to right. The first match found is used. To have fish (or bash, zsh, ksh, etc.) use a command in a different directory you simply put the directory earlier in the list of paths to be searched.

I also use Anaconda to manage multiple python environments. There may be a better solution but at the time I switched to fish I couldn't find one I liked so I wrote my own pair of fish functions: `con` to activate a anaconda environment and `coff` to deactivate it.

```
$ type coff
coff is a function with definition
# Defined in /Users/krader/.config/fish/functions/coff.fish @ line 2
function coff --description 'Deactivate a conda environment.'
    if set -q argv[1]
        echo "Too many args -- expected no args, got: $argv" >&2
        return 1
    end

    if not set -q CONDA_DEFAULT_ENV
        echo "There doesn't appear to be any conda env in effect." >&2
        return 1
    end

    # Deactivate the environment.
    set -gx PATH $CONDA_PATH_BACKUP
    set -e CONDA_PATH_BACKUP
    set -e CONDA_DEFAULT_ENV
end
```

And:

```
$ type con
con is a function with definition
# Defined in /Users/krader/.config/fish/functions/con.fish @ line 2
function con --description 'Activate a conda environment.'
    if test (count $argv) -eq 0
        conda info -e
        return 0
    end

    if test (count $argv) -ne 1
        echo 'Too many args -- expected at most one conda environment name.'
        return 1
    end

    set -l conda_env $argv[1]

    if not command conda '..checkenv' fish $conda_env
        return 1
    end

    # Deactivate the currently active environment if set.
    if set -q CONDA_DEFAULT_ENV
        coff
    end

    # Try to activate the environment.
    set -l new_path (command conda '..activate' fish $conda_env)
    or return $status

    set -g CONDA_PATH_BACKUP $PATH
    set -gx PATH $new_path $PATH
    set -gx CONDA_DEFAULT_ENV $conda_env
end
```

The only requirement is the directory containing the `conda` command is in `$PATH`.

**Comment by c02y** [comment]
It turned out that I set my `PATH` in wrong way:

    set -gx PATH $PATH $HOME/anaconda3/bin $HOME/.local/bin

it won't work even I put the `$HOME/anaconda3/bin` at the beginning of the `PATH`, the right way should be: 

    set -gx PATH $HOME/anaconda3/bin $HOME/.local/bin $PATH

now the executable files in `$HOME/anaconda3/bin` should be use by default.

Thanks for the snippet of `con` and `coff`.

And I found other functions from https://penandpants.com/2014/02/28/using-conda-environments-and-the-fish-shell/ , hope you can find something useful.

    function condalist -d 'List conda environments.'
      for dir in (ls $HOME/anaconda3/envs)
        echo $dir
      end
    end
    
    function condactivate -d 'Activate a conda environment' -a cenv
      if test -z $cenv
        echo 'Usage: condactivate <env name>'
        return 1
      end
    
      # condabin will be the path to the bin directory
      # in the specified conda environment
      set condabin $HOME/anaconda3/envs/$cenv/bin
    
      # check whether the condabin directory actually exists and
      # exit the function with an error status if it does not
      if not test -d $condabin
        echo 'Environment not found.'
        return 1
      end
    
      # deactivate an existing conda environment if there is one
      if set -q __CONDA_ENV_ACTIVE
        deactivate
      end
    
      # save the current path
      set -xg DEFAULT_PATH $PATH
    
      # put the condabin directory at the front of the PATH
      set -xg PATH $condabin $PATH
    
      # this is an undocumented environmental variable that influences
      # how conda behaves when you don't specify an environment for it.
      # https://github.com/conda/conda/issues/473
      set -xg CONDA_DEFAULT_ENV $cenv
    
      # set up the prompt so it has the env name in it
      functions -e __original_fish_prompt
      functions -c fish_prompt __original_fish_prompt
      function fish_prompt
        set_color blue
        echo -n '('$CONDA_DEFAULT_ENV') '
        set_color normal
        __original_fish_prompt
      end
    
      # flag for whether a conda environment has been set
      set -xg __CONDA_ENV_ACTIVE 'true'
    end
    
    function deactivate -d 'Deactivate a conda environment'
      if set -q __CONDA_ENV_ACTIVE
        # set PATH back to its default before activating the conda env
        set -xg PATH $DEFAULT_PATH
        set -e DEFAULT_PATH
    
        # unset this so that conda behaves according to its default behavior
        set -e CONDA_DEFAULT_ENV
    
        # reset to the original prompt
        functions -e fish_prompt
        functions -c __original_fish_prompt fish_prompt
        functions -e __original_fish_prompt
        set -e __CONDA_ENV_ACTIVE
      end
    end
    
    # aliases so condactivate and deactivate can have shorter names
    function ca -d 'Activate a conda environment'
      condactivate $argv
    end
    
    function cda -d 'Deactivate a conda environment'
      deactivate $argv
    end
    
    # complete conda environment names when activating
    complete -c condactivate -xA -a "(condalist)"
    complete -c ca -xA -a "(condalist)"
