### ISSUE TITLE
Include `--quiet` option in math function

### ISSUE THREAD

**Issue by thalesmello** [fish-shell/fish-shell#4088]
The idea would be to allow for easier bath in if statements without having to forward the output to `/dev/null`.

For example

```
if math -q '1 == 1'
    echo true
end
```

Would allow for much cleaner scripting, as opposed to

```
if math '1 == 1' > /dev/null
    echo true
end
```
version:
fish, version 2.5.0-412-gf9e7ca86

**Comment by krader1961** [comment]
Do we want to encourage this pattern by making it easier to use? The `test` command is the canonical way to test values. I've personally never seen `math` (or `bc`) used in this way. The closest is this pattern in ksh and bash: `if (( $x / 2 > 5)); then` to perform math ops and a comparison in a single command. I'm not convinced we need or even want to support that.

**Comment by zanchey** [comment]
Stick with `test`.

**Comment by thalesmello** [comment]
I wasn't aware of the test command.

Anyhow, what would be the Fish philosophy in this regard? A Pythonic style,
in the sense there should be only one way of doing things, or a Perl (or
Ruby) style in the sense there are plenty of ways to achieve the result, so
you choose whatever you like the most.

I would prefer to use a "math -q" option, but that's just a personal
preference. I'm ok with whatever decision the core development team
prefers.

**Comment by krader1961** [comment]
We try to follow Python's maxim that ideally there should be only one obvious way to do something. Which is not the same as saying there should be only one way. This is balanced by other goals such as DRY: don't repeat yourself. We'll leave this open at least a week to see how people feel but so far you have two core devs not in favor :smile:

**Comment by krader1961** [comment]
By the way, `test` and it's magic alias `[ ]` date back to the very first Bourne shell forty some years ago. I'm amazed you've been doing UNIX shell scripting without being aware of that command.

**Comment by thalesmello** [comment]
I didn't know test and [ were aliases. That's indeed very useful to know,
thanks for that.

Also, don't take me bad, they have been around for 40 years but I started
Unix scripting for about 2, so I have a lot to keep up.

But the way, as I was writing my first ever fish function yesterday, I
thought `math` function was the default way of doing conditional tests in
Fish, as I was writing my first function. I figured it would be interesting
to have a "quiet" option. That's why I created this issue.

As I said, I would be ok if the devs choose to not implement it. Thanks for
your comments anyway.

**Comment by thalesmello** [comment]
Ok. Thanks for the discussion anyways. ☺️

**Comment by krader1961** [comment]
Closing since I'm reasonably certain we don't want to make using `math` to perform conditional tests easier.

**Comment by floam** [comment]
There are certain types of mathematical tests that `bc` can do that `test` cannot. It seems reasonable to me.
