### ISSUE TITLE
pushd +NUMBER doesn't work

### ISSUE THREAD

**Issue by wgslr** [fish-shell/fish-shell#4091]
Hi
I'm using fish version 2.5.0. The documentation for `pushd` says 

> pushd +NUMBER rotates the stack counter-clockwise i.e. from bottom to top
> pushd -NUMBER rotates clockwise i.e. top to bottom.

But all I get is 
```fish
~> dirs
/tmp/c /tmp/b /tmp/a /tmp
~> pushd +1
cd: The directory “+1” does not exist
```

# Steps to reproduce:
1. Create temporary environment as suggested in the issue creation template: `sh -c 'env HOME=$(mktemp -d) fish'`
2. Create subdirectories:
```
/tmp> mkdir a b c
```
3. Create some dirs stack:
```fish
/tmp> pushd a
/tmp/a> pushd ../b
/tmp/b> pushd ../c
/tmp/c> dirs
/tmp/c /tmp/b /tmp/a /tmp
```
4. Try to use `pushd +1`:
```
/tmp/c> pushd +1
cd: The directory “+1” does not exist
/tmp/c> dirs
/tmp/c /tmp/c /tmp/b /tmp/a /tmp
```

# Expected result:  
Current directory changed to `/tmp/b`, dirs stack is `/tmp b /tmp/a /tmp /tmp/c`

**Comment by krader1961** [comment]
Introduced by commit 3702616b6, 2016-08-28, which was trying to do the right thing by switching to local variables in the function but introduced them inside a `if...end` block which means they aren't visible to the rest of the function.

**Comment by faho** [comment]
The issue is this:

```
if count $argv
   set -l rot_l
end

# And now we're using rot_l
