### ISSUE TITLE
Only one version of fish in repo on opensuse.org

### ISSUE THREAD

**Issue by AlexBaranowski** [fish-shell/fish-shell#4105]
### Background.
System I'm using is EuroLinux - RHEL like operating system in version 7. I'm using Fish from official repository provided on fishshell.com.
I had problem with Fish 2.6.0 when changing from Fish 2.5.x. I started to make minimal working reproducible example for issue on github,  then I found out that problem is not with Fish, but with my old virtualenv activate.fish scripts.

### Problem
In the middle of the process I thought that I would maybe downgrade Fish in order to make sure that it's problem of newest one only. So I run 
```bash
sudo yum history package fish    
# 315 | Updated        | fish-2.5.0-1.1.x86_64                                
# 315 | Update         |      2.6.0-1.1.x86_64 
# Output is truncated 
```
Then I run
`sudo yum downgrade fish` and it *installed version 2.3.1-1 from EPEL 7.*

Next I checked that only available lower version than 2.6.0 is 2.3.1 and surprisingly it's true.
```bash
sudo yum list available fish --showduplicates
#Available Packages
#fish.x86_64                                           2.3.1-1.el7                                           epel                 
#fish.x86_64                                           2.6.0-1.1                                             shells_fish_release_2
```

So as Fish user I'm unable to return to lower version of Fish, and what is even worse because of that I'm unable to determine if new release is source of problem.
I'm unable to find any archive in path http://download.opensuse.org/repositories/shells:/fish:/ . No matter how stable and tested Fish is, it's always good idea to keep older version just in case.
Any help / thoughts are much appreciated.

**Comment by zanchey** [comment]
Unfortunately OBS overwrites previous versions, so unless we create a new repository for each version there is no easy way of accessing old versions.

**Comment by AlexBaranowski** [comment]
OK I didn't know that. I will write to guys from OBS then. I close issue then.
Help you very much anyway.
