### ISSUE TITLE
completion for ~/.ssh/config entries is broken in 2.6.0 on macOS

### ISSUE THREAD

**Issue by predmijat** [fish-shell/fish-shell#4107]
`fish, version 2.6.0`

`16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64 i386 MacBookPro12,1 Darwin`
`xterm-256color`

I updated via `brew` today and noticed that `ssh abc<TAB>` will not auto-complete entry from `~/.ssh/config` "abc123". Editing symlink from:
`fish -> ../Cellar/fish/2.6.0/bin/fish` to
`fish -> ../Cellar/fish/2.5.0/bin/fish`
fixes the issue.

`__fish_print_hostnames` doesn't print entries from `~/.ssh/config`

**Comment by faho** [comment]
This is most likely fixed by #4104. If you can, please try that. Since it only modifies the `__fish_print_hostnames` function, you can simply copy the file to ~/.config/fish/functions.

**Comment by martin-g** [comment]
Same problem here on Ubuntu 17.04 after upgrading to Fish 2.6.0.

I've downloaded https://raw.githubusercontent.com/fish-shell/fish-shell/master/share/functions/__fish_print_hostnames.fish to `~/.config/fish/functions/__fish_print_hostnames.fish` and started a new shell but still there is no auto-completetion.
Should I do something more ?

**Comment by faho** [comment]
@martin-g: Wrong branch - you'll want the one from #4104 (which isn't merged yet): https://raw.githubusercontent.com/daleeidd/fish-shell/1616300e38cdd74bf9e0d91e8ec828c61948e0ab/share/functions/__fish_print_hostnames.fish.

**Comment by martin-g** [comment]
Thanks, @faho !
I confirm that this fixes the problem here!
Keep the great work!

**Comment by faho** [comment]
Fixed by merging #4104.
