### ISSUE TITLE
Errors with fish prompt

### ISSUE THREAD

**Issue by sascha-andres** [fish-shell/fish-shell#4109]
Sorry if I am at the wrong location.

I am using fish version 2.5.0-462-gc263c593

After the output of each program output ( like ls ) I do get a lot of error messages ( long enough I need to scroll ):
```
~/.config/fish/functions/fish_prompt.fish (line 6): Array index out of bounds
      set budspencer_current_bindmode_color $budspencer_colors[5]
                                                               ^
in function “__budspencer_prompt_bindmode”
        called on line 864 of file ~/.config/fish/functions/fish_prompt.fish

in command substitution
        called on line 862 of file ~/.config/fish/functions/fish_prompt.fish

in function “fish_prompt”
        called on standard input

in command substitution
        called on standard input

~/.config/fish/functions/fish_prompt.fish (line 7): Array index out of bounds
      echo -en $budspencer_cursors[2]
                                   ^
in function “__budspencer_prompt_bindmode”
        called on line 864 of file ~/.config/fish/functions/fish_prompt.fish

in command substitution
        called on line 862 of file ~/.config/fish/functions/fish_prompt.fish

in function “fish_prompt”
        called on standard input

in command substitution
        called on standard input

~/.config/fish/functions/fish_prompt.fish (line 1): Array index out of bounds
set_color -b $budspencer_colors[2]
                                ^
in command substitution
        called on line 672 of file ~/.config/fish/functions/fish_prompt.fish

in function “__budspencer_prompt_left_symbols”
        called on line 864 of file ~/.config/fish/functions/fish_prompt.fish

in command substitution
        called on line 862 of file ~/.config/fish/functions/fish_prompt.fish

in function “fish_prompt”
        called on standard input

in command substitution
        called on standard input

~/.config/fish/functions/fish_prompt.fish (line 1): Array index out of bounds
set_color -o $budspencer_colors[12]
                                ^
in command substitution
        called on line 672 of file ~/.config/fish/functions/fish_prompt.fish

in function “__budspencer_prompt_left_symbols”
        called on line 864 of file ~/.config/fish/functions/fish_prompt.fish

in command substitution
        called on line 862 of file ~/.config/fish/functions/fish_prompt.fish

in function “fish_prompt”
        called on standard input

in command substitution
        called on standard input

~/.config/fish/functions/fish_prompt.fish (line 1): Array index out of bounds
set_color $budspencer_colors[2]
                             ^
in command substitution
        called on line 672 of file ~/.config/fish/functions/fish_prompt.fish

in function “__budspencer_prompt_left_symbols”
        called on line 864 of file ~/.config/fish/functions/fish_prompt.fish

in command substitution
        called on line 862 of file ~/.config/fish/functions/fish_prompt.fish

in function “fish_prompt”
        called on standard input

in command substitution
        called on standard input

~/.config/fish/functions/fish_prompt.fish (line 1): Array index out of bounds
set_color $budspencer_colors[2]
                             ^
in command substitution
        called on line 672 of file ~/.config/fish/functions/fish_prompt.fish

in function “__budspencer_prompt_left_symbols”
        called on line 864 of file ~/.config/fish/functions/fish_prompt.fish

in command substitution
        called on line 862 of file ~/.config/fish/functions/fish_prompt.fish

in function “fish_prompt”
        called on standard input

in command substitution
        called on standard input
```

I am using the same configuration on another machine which works just fine.

**Comment by faho** [comment]
The issue here is that your prompt is reading elements from $budspencer_colors, which doesn't have those elements defined. As a workaround, try setting that variable to something - since you have another install that is working, check what that variable is set to there.

I'd try to talk to the [budspencer people](https://github.com/oh-my-fish/theme-budspencer/issues), because it seems like they aren't checking if that variable has enough elements enough (which I admit is annoying, but is the long-standing behavior of fish).

**Comment by sascha-andres** [comment]
I opened an issue there: https://github.com/oh-my-fish/theme-budspencer/issues/48
As I sync my settings from the working computer to the non working one, there should be no difference. But I search for a diff over ssh to double check

**Comment by krader1961** [comment]
> I sync my settings from the working computer to the non working one

How do you sync the settings? It is likely these are universal variables. Which, at the moment, are stored in a file whose name is unique to each machine. For example, on the machine I'm typing this it is *~/.config/fish/fishd.406c8fb84b26*. So using something like scp or rsync to simply copy your *~/.config/fish* folder isn't sufficient to keep uvars in sync across machines.

**Comment by sascha-andres** [comment]
I rsynced. So I probably have to take a closer look how to sync fish settings across machines. @krader1961  Do you do this?

**Comment by krader1961** [comment]
I do sync my config across machines and I do use rsync to do so. However, I have not automated syncing the contents of the universal variable file. So I simply end up with multiple uvar files like this (from one of my systems) in *~/.config/fish*:

```
-rw-r--r--  1 krader staff  1569 Apr 24  2016 fishd.000c2951832d
-rw-r--r--  1 krader staff  1979 Jun  7 20:24 fishd.406c8fb84b26
-rw-r--r--  1 krader staff  2067 Jun  4 13:30 fishd.80e650051cec
```

Since I haven't changed the color variables in over a year this hasn't been a problem for me. When I was experimenting with different color themes I simply extracted the vars on one machine (e.g., `set -U | grep color`) and applied them on the other systems.

**Comment by sascha-andres** [comment]
Thanks, closing as this is not a real issue

**Comment by krader1961** [comment]
See issue #1912 where we are discussing changing the uvar file so it is not machine specific -- at least by default. If anyone reading this issue is interested in contributing a change I'd encourage you to consider working on that issue.
