### ISSUE TITLE
Fish 2.6.0: version unknown

### ISSUE THREAD

**Issue by sascha-andres** [fish-shell/fish-shell#4122]
Hi,

I cloned fish-shell on a new computer. I used the latest master and fish --version tells me : `fist, version unknown`. At compile time I see 2.6.0-commit. Therefore installation of oh-my-fish failed ( requiring at least v 2.2.0 ). I also tried using 2.6.0 tag, but that had the same problem.

Any tips?

Kind regards,
Sascha

**Comment by krader1961** [comment]
The string "version unknown" should be impossible and means your build of fish is broken. Also, I don't know what you mean by "At compile time I see 2.6.0-commit". What operating system are you using? How did you "clone" fish? What commands did you run to compile it?

**Comment by faho** [comment]
Do you have a file called "version" in your clone of the fish repo? Is that file readable by the user you used to build fish?

Fish generates the version at build time with the build_tools/git_version_gen.sh script, which has this bit in it:

```sh
if test -f version
then
        VN=$(cat version) || VN="$DEF_VER"
# ...
fi
```

"$DEF_VER" here is "unknown". So you appear to have a file called "version", yet for some reason `VN=$(cat version)` fails. The most likely way that happens is if the file is unreadable.

**Comment by sascha-andres** [comment]
No I do not have one, I cloned from git. So maybe this is the problem

**Comment by faho** [comment]
>No I do not have one, I cloned from git. So maybe this is the problem

That means it is not the problem. These symptoms could be caused by you having one.

Also, would it be possible for you to answer @krader1961's questions:

>What operating system are you using? 

>How did you "clone" fish? 

>What commands did you run to compile it?

?

**Comment by sascha-andres** [comment]
OS: neon.kde.org 5.10.2
Clone: git clone git@github.com:fish-shell/fish-shell.git
Compiling:
```
autoreconf --no-recursive                                                                                                                                                   
./configure --prefix=/usr/local                                                                                                                                             
make                                                                                                                                                                        
sudo make install    
```

**Comment by sascha-andres** [comment]
I tried downloading the release tarball, that has worked

**Comment by faho** [comment]
>I tried downloading the release tarball, that has worked

@sascha-andres: Yes, that points to the git_version_gen.sh script being the problem. Can you run that? I.e. in the git clone, run `build_tools/git_version_gen.sh`? If it doesn't print anything, remove the file "FISH-BUILD-VERSION-FILE" and run it again.

**Comment by krader1961** [comment]
The answer is simple. If you don't have a *.git* directory we can't determine the version so `build_tools/git_version_gen.sh` outputs `FISH_BUILD_VERSION = unknown`.  So your "clone" of the fish source tree, @sascha-andres, was incomplete.

**Comment by sascha-andres** [comment]
@krader1961  I had a .git directory.  I could switch branches / checkout tags just fine. I couldn't have done this if it was incomplete.

I cloned again ( this time using https instead of git ) and still it happened. @faho calling build-tools/git_version_gen.sh prints `FISH_BUILD_VERSION = 2.6.0-122-gaf22bf35`

**Comment by krader1961** [comment]
Whatever you have done means that the *build_tools/git_version_gen.sh* script is not able to determine and save the version of the code being built. What does `/bin/sh -x build_tools/git_version_gen.sh` output? Then do `rm FISH-BUILD-VERSION-FILE` followed  by `/bin/sh -x build_tools/git_version_gen.sh` and then `cat FISH-BUILD-VERSION-FILE`.

There is something odd about about your environment that is keeping fish from determining its version. Whether we can, or should, work around that quirk is TBD.

**Comment by krader1961** [comment]
Closing due to no response in a week. If you still need help, @sascha-andres, or have more data that would help us understand why the version could not be determined please reopen this issue.

**Comment by Hunsu** [comment]
I installed fish from the nightly ppa and I have this issue.

**Comment by zanchey** [comment]
Thanks @Hunsu - I've confirmed that the PPA builds are not currently putting the version number in properly and have reopened this issue.
