### ISSUE TITLE
Fish debugger is a bit under documented. 

### ISSUE THREAD

**Issue by AttilaVM** [fish-shell/fish-shell#4125]
Where can I find the keybindings for Fish's built-in debugger?
The [official documentation](http://fishshell.com/docs/current/index.html#debugging) doesn't contain it.

Seemingly it is a problem for others too. This [issue](https://github.com/fish-shell/fish-shell/issues/2157) also occurred because the OP didn't have enough prior information when he started the debugger.

**Comment by krader1961** [comment]
The key bindings are whatever is in effect before you enter the debugger. That is, default (emacs) or vi bindings plus whatever custom bindings you have added. However I'm guessing you're really asking what commands are available in the debugger. The answer is any command you can type at a normal interactive shell prompt. For example, after hitting a `breakpoint` you'll get your fish prompt. Now type `status print-stack-trace`. Think of it as a nested interactive session running in the context of the `breakpoint` statement. When you type `exit` or [ctrl-D] you leave the nested interactive session and execution continues with the statement following `breakpoint`. There are no commands unique to the debugger.
