### ISSUE TITLE
pgrep & pkill completing issue when process name exceeding the limit

### ISSUE THREAD

**Issue by cirfi** [fish-shell/fish-shell#4132]
Fish version: 2.5.0
OS: Arch Linux
Term: rxvt-unicode-256color

When I kill telegram-desktop, whose name is exceeding the 16 bytes limit, ```pkill telegram-desktop``` doesn't work at all. Instead, I need to use ```pkill telegram-deskto```

However, fish completes the command ```pkill telegram``` to ```pkill telegram-desktop``` not ```pkill telegram-deskto```. Fish compltes ```pgrep``` the same way.

```sh
$ pgrep -l telegram-desk
23560 telegram-deskto
$ pgrep -l telegram-deskto
23560 telegram-deskto
$ pgrep -l telegram-desktop
$
```

```pkill```'s ```-f``` option helps a lot. I now alias ```pkill``` to ```pkill -f``` and it works well. Thanks for krader1961's helping.

**Comment by krader1961** [comment]
On my system, macOS 10.12 (a BSD system), there is no such limit. On Ubuntu 16.10 (a Linux distro) I do see such a limit. Neither system documents a limit on the command name for these commands. The problem occurs because each OS has a different limit on the number of characters in the command as shown by `ps` with no options. On BSD it is the entire command name. On GNU it is the first 16 characters. Using the `-f`, `--full`, `-a`, or `--list-full` flag allows you to match the entire command name on GNU.

This is a problem that may be difficult to fix so that it works correctly in all situations. We probably do not want to arbitrarily limit the command name completion to 16 characters in every situation as doing so will result in false positives. That is, commands being matched that should not be matched. It is not clear to me that adding a bunch of tests for the OS and the flags already seen is worth the cost.

**Comment by krader1961** [comment]
@cirfi, You should not add new information to a comment by editing it. It is better to add a new comment. That makes the discussion easier to understand.

**Comment by cirfi** [comment]
I don't know if it necessary to let fish support up-to-16-byte process names. On my side, the issue is solved. So I just edited the issue.
I tried in oh-my-zsh which supports completing both with or without ```-f``` option. It doesn't means that fish need to support the feature.

**Comment by faho** [comment]
Is this a limitation of this particular implementation of pgrep (mine is from procps-ng) or linux?

My pgrep man page states:

>The  process  name  used  for  matching  is limited to the 15 characters present in the output of /proc/pid/stat.  Use the -f option to match
       against the complete command line, /proc/pid/cmdline.

Soo... do other pgreps always use /proc/pid/cmdline on linux? What's the reason for not using it in the first place (it's just another file, right)?

Shortening the completion if "-f" isn't given is trivial, but we need to figure out when that should happen.

**Comment by mqudsi** [comment]
This isn't a Linux-only limitation.

[Linux](https://linux.die.net/man/1/pgrep):

> The process name used for matching is limited to the 15 characters present in the output of /proc/pid/stat. Use the -f option to match against the complete command line, /proc/pid/cmdline.

[SunOS/Solaris](https://docs.oracle.com/cd/E19455-01/806-0624/6j9vek5cu/index.html):

> Both utilities match the ERE pattern argument against either the pr_fname or pr_psargs fields of the /proc/ nnnnn /psinfo files. The lengths of these strings are limited according to definitions in <sys/procfs.h> . Patterns which can match strings longer than the current limits may fail to match the intended set of processes.

[FreeBSD](https://www.freebsd.org/cgi/man.cgi?query=pgrep&sektion=1):

>     If any pattern operands are specified, they are used as regular expres-
>     sions to match the	command	name or	full argument list of each process.
>     If	the -f option is not specified,	then the pattern will attempt to match
>     the command name.	However, presently FreeBSD will	only keep track	of the
>     first 19 characters of the	command	name for each process.	Attempts to
>     match any characters after	the first 19 of	a command name will quietly
>     fail.

[OS X has no such limit](https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/pgrep.1.html). 

NetBSD [isn't documented as having a limit](http://netbsd.gw.com/cgi-bin/man-cgi?pgrep+1+NetBSD-current), either.

[OpenBSD](https://man.openbsd.org/pgrep.1):
> If any pattern operands are specified, they are used as regular expressions to match the command name or, if -f is specified, the full argument list of each process. However, presently OpenBSD will only keep track of the first 16 characters of the command name for each process. Attempts to match any characters after the first 16 of a command name will silently fail.

**Comment by mqudsi** [comment]
It seems the procfs.h definition is only for Solaris. I think it's `PRFNSZ`.
