### ISSUE TITLE
Repository for Debian 9 (Stretch)

### ISSUE THREAD

**Issue by TimWolla** [fish-shell/fish-shell#4140]
As you might know Debian Stretch was released yesterday. I am using the fish repositories to get a more current version than the official Debian repositories. I noticed that they don't support Debian 9 yet (at least not officially, I did not test): https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A2&package=fish

Could you please check whether it is possible to support Debian 9 already?

**Comment by zanchey** [comment]
I'll add them, but you can just use the Debian 8 repositories - the packages are forward compatible.

**Comment by zanchey** [comment]
Done! 🚀

**Comment by TimWolla** [comment]
Upgraded one of my machines using the new repository, can confirm working :ok_hand:
