### ISSUE TITLE
COLUMNS incorrect for the first prompt in a session

### ISSUE THREAD

**Issue by soumya92** [fish-shell/fish-shell#4141]
fish, version 2.6.0
macOS 10.12.5 (16F73)
iTerm2 Build 3.0.15

With a fish_prompt of 
```fish
function fish_prompt
    echo "$COLUMNS > "
end
```

I see some weird behaviour. Specifically, the first prompt of any fish invocation prints 80, while subsequent prompts print 120 (actual width).

This happens for new tabs, new windows, and even nested fish shell invocations.

Pressing return, resizing the window (in either dimension), pasting something (presumably because of the syntax highlighting), or even pkill -SIGWINCH fish in another session, all fix the prompt.

I have a ["-d 3" log of fish](https://gist.github.com/soumya92/cfafa10b523c9883471d6073c3745510), where all I do is press return to update columns and then quit.

**Comment by krader1961** [comment]
Good catch. Thanks for reporting this. It turns out that we currently don't interrogate the size of the terminal until after the first time `fish_prompt` is run when fish needs to decides whether its output will fit on the screen.

**Comment by soumya92** [comment]
Thanks for the quick fix! 🎉
