### ISSUE TITLE
Is there any update info?

### ISSUE THREAD

**Issue by Mabinogiysk** [fish-shell/fish-shell#4144]
Hi, 
I have been using version 2.2 for many years, now I find there is a version 2.6. I would like to know is there any way I can find what has been updated in each version? I have searched it in home page and find nothing.

Kind regards

**Comment by zanchey** [comment]
Have a look at the [release notes](https://fishshell.com/release_notes.html) linked from the homepage, or through the [GitHub releases page](https://github.com/fish-shell/fish-shell/releases).

**Comment by krader1961** [comment]
And, of course, the release notes are just a copy of the [CHANGELOG](https://github.com/fish-shell/fish-shell/blob/master/CHANGELOG.md) file you'll find in the project source code if you `git clone` it.

**Comment by faho** [comment]
@Mabinogiysk: I'm assuming that answers your question, so I'm closing this. If you have anything else, feel free to ask!
