### ISSUE TITLE
Prioritise SSH config in ssh-like tab completion

### ISSUE THREAD

**Issue by alexrussell** [fish-shell/fish-shell#4146]
I see that the other day the [SSH tab completion was updated](https://github.com/fish-shell/fish-shell/commit/2b4f61f2944205eaf2f3aeeb876d58121f1cb862) to actually read the SSH config file(s) (before, the SSH config file discovery code was broken, I was just opening an issue about this when I realised it'd recently changed). I have installed from the current `master` code and the tab completions from the SSH config now work. However, they are mixed in with `known_hosts` and maybe some other discovered potential hosts.

That's fine - I get why fish parses `known_hosts`. However, I feel like if it could prioritise the config hosts that'd be more sensible. I know fish's tab completion includes a search-as-you-type feature, so it's not too hard to find what you are looking for, but at an initial glance, the tab completion output is somewhat messy (including a bunch of IP-based hosts which match my SSH config host aliases.

Is there any way to do this prioritisation, or does fish not support this?

**Comment by faho** [comment]
>Is there any way to do this prioritisation, or does fish not support this?

This is currently not supported, but has been requested before in #361. Let's track there!

**Comment by alexrussell** [comment]
Ahh my bad. Thanks for the triage :)
