### ISSUE TITLE
__fish_not_contains_opt: Unknown option

### ISSUE THREAD

**Issue by fundon** [fish-shell/fish-shell#4155]
### Fish Version

```console
 λ ~ > fish --version
fish, version 2.6.0
```

### Error

```console
 λ ~ > node -__fish_not_contains_opt: Unknown option --version
__fish_not_contains_opt: Unknown option --version
__fish_not_contains_opt: Unknown option --version
__fish_not_contains_opt: Unknown option --eval
 λ ~ > node --version
v8.1.2
```

### Node

```console
 λ ~ > echo $PATH
/Users/fundon/.nvm/versions/node/v8.1.2/bin /Users/fundon/.yarn/bin /Users/fundon/.config/yarn/global/node_modules/.bin /Users/fundon/.cargo/bin /Users/fundon/Dev/goroot/bin /Users/fundon/Library/Android/sdk/tools /Users/fundon/Library/Android/sdk/platform-tools /usr/local/bin /usr/bin /bin /usr/sbin /sbin
 λ ~ > which node
/Users/fundon/.nvm/versions/node/v8.1.2/bin/node
```

**Comment by krader1961** [comment]
This was fixed 12 days ago by commit a0c8a9e8e. The problem is that the person who wrote the `node` completion script thought the arguments passed to `__fish_not_contain_opt` were supposed to include the leading `-` or `--`.

You can get the fix by building fish from git head or copying the [updated completion script] to your *~/.config/fish/completions* directory.

**Comment by karuppiah7890** [comment]
@krader1961 I am not able to find the completions directory anywhere

**Comment by faho** [comment]
@karuppiah7890: If $XDG_CONFIG_HOME is set, it's at $XDG_CONFIG_HOME/fish/completions. If not, it's at ~/.config/fish/completions. Either way it should be the first element of $fish_complete_path.  If it doesn't exist, create it.

**Comment by karuppiah7890** [comment]
@faho Thanks but I couldn't get it. Anyways, I got the nightly release and things are okay now :)

**Comment by karuppiah7890** [comment]
I am Ubuntu Xenial. And there was no $XDG_CONFIG_HOME. There was only $XDG_CONFIG_DIRS and I couldn't find fish's completions directory

**Comment by faho** [comment]
Okay, let me try that again.

$XDG_CONFIG_HOME isn't set, so it is ~/.config/fish/completions. If that directory does not exist, create it - `mkdir -p ~/.config/fish/completions`.

**Comment by karuppiah7890** [comment]
Okay, so creating that new directory with the node completions in it will override any completions already present ? I didn't think about that. But next time if I find any issues, I will do that !

**Comment by faho** [comment]
>Okay, so creating that new directory with the node completions in it will override any completions already present ?

Yes.

It's the same with completions and functions - both have a list of directories where earlier entries override later ones. This is like the components of $PATH.

**Comment by karuppiah7890** [comment]
Makes sense. Thanks for enlightening me! :smile:
