### ISSUE TITLE
How to run `fish -c ...` without loading the config?

### ISSUE THREAD

**Issue by Ambrevar** [fish-shell/fish-shell#4165]
Is there a way to tell fish to start without loading the user config?
I'd like to run some fish command with `fish -c` with reproducible results.

**Comment by krader1961** [comment]
The usual way is `env HOME=(mktemp -d) fish`. If you absolutely have to have `HOME` refer to your real home directory just put `exit 0` at the top of your *~/.config/fish/config.fish*. However that still leaves your user defined autoloaded functions accessible to whatever you're testing.

**Comment by Ambrevar** [comment]
Yes, I need `HOME`.

What do you mean with the `exit 0`? That would also change the behaviour of normal fish sessions and I don't want to do that.

**Comment by krader1961** [comment]
The idea is you only add that line (or rename *config.fish*) just long enough to do you test. Beyond that someone who is motivated, like yourself, will need to add something like the bash `--norc` flag.

**Comment by Ambrevar** [comment]
Ok, that'll we do for my use case. Thanks.
