### ISSUE TITLE
How to enable Ctrl+s back in the terminal

### ISSUE THREAD

**Issue by sidahmed-malaoui** [fish-shell/fish-shell#4168]
I used to use the shortcut `Ctrl+s`  in the terminal to freeze my programs to get some informations from their output. This used to work fine in other shells, but it ain't working anymore when I make fish my default shell. Even though I launch fish, then I launch another shell, this shortcut is not working anymore.

Please give this feature back, or show me what option should I use to restore it. This is really a helpful feature fol developers, and it is really a big handicap not having it.

**fish, version :** 2.6.0
**Operating system :** Linux Del-B5 4.10.0-24-generic # 28-Ubuntu SMP Wed Jun 14 08:14:34 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
**Terminal :** I am using terminix, but the command `echo $TERM` gave me 'xterm-256color'
**How to reproduce the problem :** Just install fish shell and trie to use the shortcut `ctrl+s` in the terminal, it won't freeze the terminal output any more.

**Comment by faho** [comment]
Currently, this isn't possible to change from your end. We just unconditionally disable it.

Changing this has been requested in #2315. I'm closing this as a duplicate. Sorry for the inconvenience!
