### ISSUE TITLE
How would "{ cmd 1 fails | cmd 2; } || cmd 3" be translated to fish?

### ISSUE THREAD

**Issue by da99** [fish-shell/fish-shell#4176]
I've looked at various places in (Fish docs, github issues) and I've still haven't been able to translate the following from ZSH to fish:

```zsh
  { cmd 1 fails | cmd 2; } || cmd 3
```

The idea is if `cmd 1` exists non-0, then the output will be from `cmd 3`. But, if it passes, pipe the output to `cmd 2`. 

In `fish 2.6.0`, I'm getting the output from `cmd 2`, even when cmd 1 exists: 
```fish
     false | cut -d'/' -f2; or echo "i gotta be me"
```
(I've read the previous discussions on proposals for fish pipefail here on github and I still haven't made much progress on the translation. My current solution is to have intermediate local variables and check for empty output on `cmd 1`.) 

So my question would be what would be the recommended way to translate this to fish?

**Comment by faho** [comment]
I have honestly never used that idiom - what is it useful for? Can you post an actual use of it?

The usual translation for `{ cmd; }` is `begin; cmd; end`, so this would look like

```fish
begin; false | cut -d'/' -f2; end; or echo "i gotta be me"
```

but I'm assuming this might not have all the properties you want.

**Comment by da99** [comment]
It was meant to be used within a variable set/declaration:
```
   my_var=$(cmd 1 | cut -d'/' -f1 || some other output)
```
I tried the begin/else alternative (that @faho suggested), but I'm getting empty output even when `cmd 1` fails since the pipe (`| cmd 2`) still runs regardless of `cmd 1` exit status.

It's ok though. @faho is right: it's not a common enough idiom for me to worry about.

**Comment by krader1961** [comment]
@da99, You seem to be slightly confused about how the zsh example you provided works. Specifically you say "the pipe... still runs regardless of cmd1 exit status". That is true in zsh as well as fish, bash, etc. You also seem to think the exit status of the left-hand side of the pipe determines whether the `|| some other ouput` is executed. That isn't true. Try this in zsh:

```
> { sh -c 'echo yes; exit 11' | sh -c 'cat; exit 0' } || echo failed
yes
```

This behavior is documented in the zshall man page:

> The value of a pipeline is the value of the  last  command,....

However, if you set the `PIPE_FAIL` option then it sort of works the way you describe. Contrast the earlier behavior with this option set:

```
> set -o PIPE_FAIL
> { sh -c 'echo yes; exit 11' | sh -c 'cat; exit 0' } || echo failed
yes
failed
```

That global options like `PIPE_FAIL` make it practically impossible to predict how a given statement or function will behave in zsh is why I abandoned it for fish.

**Comment by da99** [comment]
@krader1961 You are completely right. I was running the code in a ZSH script where I had `set -o pipefail` at the top. I completely forgot about the option. Those global options are one of the reasons that led me to fish. Thanks for pointing it out (and for leaving them out of fish's design.)
