### ISSUE TITLE
Building On OpenBSD

### ISSUE THREAD

**Issue by mytchel** [fish-shell/fish-shell#4184]
Both the source tar ball of 2.6.0 and git 83ecf84392b7857a90499bef171187812e3af17a using both GCC 4.9.4 and clang 4.0.0 build on OpenBSD 6.1, however the configure script doesn't let them build, claiming that errno is not thread safe. The man page claims it is. Or at least how I read the Thread section on the errno man page makes me think it should be. Removing the test results in a binary that works so far as I can tell. 

I did some research and it could be because it is not compiling the test with -pthread but I do not know how configure scripts work so it may be doing that.

The latest git version does the same but does not compile as it can not find the xlocale.h header included by src/builtin_read.cpp which doesn't seem to use anything in xlocale.h. Removing the included solves this builds fine.

**Comment by zanchey** [comment]
The test is failing because `pthread_join` returns the undocumented ENOENT.

Regardless, the test is probably not really robust enough; perhaps it would be enough to check that the address of errno is different in different threads.

**Comment by zanchey** [comment]
Hang about, no it doesn't (and shouldn't); `pthread_create` on OpenBSD sets `errno` but isn't supposed to.

**Comment by mytchel** [comment]
Well I'm confused. If you put a printf before pthread_create errno is zero as it should be. Maybe it's a bug with OpenBSD?

**Comment by zanchey** [comment]
I suspect checking errno in the absence of an error condition is technically undefined behaviour.

**Comment by zanchey** [comment]
OK, I couldn't get an answer on StackOverflow on [how to check if errno is threadsafe](https://stackoverflow.com/questions/45435987/configure-check-for-threadsafe-errno), so I'm removing the test which was really just there to try and avoid problems from #3340 resurfacing.

**Comment by mytchel** [comment]
Awesome, but it still doesn't build because of src/builtin_read.cpp including xlocal.h which doesn't exist. Removing the include lets it build so I'm not sure why it's there unless it is different on other systems.

**Comment by zanchey** [comment]
I think `xlocale.h` is needed on OS X for the `MB_CUR_MAX` symbol - at least according to include-what-you-use. fish still builds on OS X without that reference, though.

**Comment by zanchey** [comment]
@krader1961, any thoughts? We don't include `xlocale.h` in any of the other files we use `MB_CUR_MAX` in.

**Comment by mqudsi** [comment]
@zanchey I don't speak autoconf or m4, but a lot of build systems have "include this header if it exists" or "include but don't fail if not found" - can we do that?

**Comment by zanchey** [comment]
No need - `stdlib.h` is the correct header according to [POSIX:2008](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/stdlib.h.html). @mytchel, could you try a build either from the master branch or the Integration_2.7.0 branch? I think it should work now.

**Comment by mytchel** [comment]
master builds find now. Thank you @zanchey and co.
