### ISSUE TITLE
Does the builtin pager have "progressively filterable"/fuzzy-find options?

### ISSUE THREAD

**Issue by da99** [fish-shell/fish-shell#4186]
When I try to complete a command using fish's pager (using the builtin `complete` command), the menu goes away once I start after the menu shows up:

```fish
~> ls  --<tab>(menu appears)a(menu disappears)
```
I think this is the normal behaviour. 

However, I am used to the "fuzzy finder" way of search: the menu eliminates non-matching items from the list (instead of disappearing).  This is really useful when the list of options is big and I am only interested in a subset. I believe ridiculousfish brought it up in a [previous issue](https://github.com/fish-shell/fish-shell/issues/1264), but he called it "Progressively filterable". Sometimes it is called  "incremental search".  Was anything like this ever implemented into fish's completion or pager functionality?

**Comment by faho** [comment]
You need to press TAB more 😄.

No, I'm serious. Pressing TAB once will show a peak, pressing it twice will fully open it, and pressing it three times will start the selection-mode - then you can select a candidate with e.g. the arrow keys, or start typing to filter the pager.

**Comment by da99** [comment]
@faho That solved it. Thanks for the quick reply.

**Comment by da99** [comment]
@faho Is it possible to force  the pager to always use a single column? 
![img_20170705_044052](https://user-images.githubusercontent.com/1551848/27858781-24cab96c-613c-11e7-9d44-c113536c79dc.jpg)

**Comment by faho** [comment]
No. The idea is that multiple columns allow you to reach more candidates faster.
