### ISSUE TITLE
Somebody explain me, in fish shell, where did "it" get the PATH variable ? "/etc/profile"file ?? i dont think so

### ISSUE THREAD

**Issue by narutowindy** [fish-shell/fish-shell#4192]

**Comment by faho** [comment]
Fish does not read /etc/profile, since that file is a POSIX-sh shell script.

Instead it just takes what it inherits from its parent process (if you're running a graphical environment that's the terminal), or if it doesn't get anything, it falls back to `/usr/bin` and `/bin`.

**Comment by narutowindy** [comment]
where should i write/store my PATH variable to work globally on fish ?

**Comment by krader1961** [comment]
That depends on your OS distro, @narutowindy. Personally, I don't rely on PATH being set correctly by whatever launches my shell. I always set it explicitly in my *~/.config/fish/config.fish* script. I have a sequence of commands that set it up based on what machine I'm running on since I use the same config of very different systems. For example:

```
# Customize the PATH.
set -x PATH

test -d /usr/local/go/bin
and set PATH $PATH /usr/local/go/bin

if string match -q 'CYGWIN*' (uname -s)
    set -x PATH $HOME/symlinks $HOME/bin $HOME/sbin /usr/local/bin $PATH
else
    set -x PATH $HOME/symlinks $HOME/bin $HOME/sbin \
        /usr/local/bin /usr/local/sbin $PATH /usr/bin /usr/sbin /bin /sbin
    if test -d /opt/X11/bin
        set PATH $PATH /opt/X11/bin
    end
end

if test -x /usr/local/git/bin/git; and not test -x /usr/local/bin/git
    # We must be on my OS X Snow Leopard VM with an old git from the official DMG image rather than
    # from 'brew install git'.
    set PATH /usr/local/git/bin $PATH
end
```

**Comment by krader1961** [comment]
Closing since there hasn't been any followup in several days. Feel free to reopen if you still have questions.
