### ISSUE TITLE
Is there a way to detect when an autosuggestion in being shown to the user?

### ISSUE THREAD

**Issue by da99** [fish-shell/fish-shell#4193]
I see `commandline` has options `--search-mode` and `--paging-mode`, but is there something similar to detect when a command suggestion is being show to the user? For example:

![echo](https://user-images.githubusercontent.com/1551848/27943584-22815e70-62a6-11e7-92e5-7110a50aa79a.png)

**Comment by krader1961** [comment]
No. How would that be useful? The suggested command is displayed solely based on what has been entered so far. How would it be useful for a key binding to detect that the characters typed so far matches a history entry?

**Comment by da99** [comment]
Thanks for the quick reply. This is enough for me to close the issue.

(I guess my key bindings and preferences are "unusual". I came across the question on a dumb edge case not worth discussing.)
