### ISSUE TITLE
Fish not considering hosts in ~/.ssh/config

### ISSUE THREAD

**Issue by spacekookie** [fish-shell/fish-shell#4195]
Fish version: fish, version 2.6.0
OS: Arch Linux

I have oh-my-fish and a few plugins via it installed but this issue still occurs without them.

My problem is that when typing "ssh" and trying to tab-complete hosts that fish will only consider hosts from `~/.ssh/known_hosts` and not my ssh config. My ssh config is a valid syntax, for example:

```

Host icarus
  User            spacekookie
  HostName        <ip-address-here>
  IdentitiesOnly  yes
  IdentityFile    ~/.ssh/<keyfile-here>
  Port            22
```

Yet trying to type `ssh ic` and tab-completing doesn't sugest "icarus"  but rather try to auto-complete folders in my current directory. I've seen closed issues about this before that were dated back a few years and apparently it was fixed. And I could swear that fish used to do this. Is it maybe a regression with something in a newer version? Would be nice if you could get this working again.

If you need more information from me, please tell me what to post. Thanks

**Comment by faho** [comment]
This should already be fixed in the next release via #4104.

If you want it earlier, you can download the new version of the `__fish_print_hostname` function and store it in your $fish_function_path.

**Comment by spacekookie** [comment]
Ah, thanks. I didn't check the pull requests for info before making an issue. When can I expect the feature roughly then? 2.7? Or is there gonna be a patch version before then?

**Comment by faho** [comment]
>When can I expect the feature roughly then? 2.7? Or is there gonna be a patch version before then?

Yes, 2.7, which is currently planned for September.
