### ISSUE TITLE
Where zsh command in fish

### ISSUE THREAD

**Issue by diazgilberto** [fish-shell/fish-shell#4201]
This is more of a question... In `zsh` I type `where python` and I get back all the path of any python installation in my system. Also, I type `which python` and I get the path of the current python I'm using. I notice that fish does have the `which` command but looks like fish doesn't have this command. What is the `where` `zsh` command for fish?

**Comment by faho** [comment]
>I notice that fish does have the which command

Not really. `which` is an external application that we previously depended on. You can install it, but it's no longer necessary.

What you want is either `command -sa python` (the "-s" means "search" as opposed to executing it, and the "-a" is short for "--all", which means it doesn't stop looking after the first match) if all you are interested in is python binaries in $PATH, or `type -a python` if you also wish to include functions and builtins by that name.

**Comment by diazgilberto** [comment]
I'm closing since I got my answer. Thank you @faho
