### ISSUE TITLE
fish confuses find(8) on argument -exec with '+'

### ISSUE THREAD

**Issue by Avispa** [fish-shell/fish-shell#4202]
### Reproduce
run `find . -iname index.html\* -exec echo {} +` (same with `... \+` or `... \\+`)

### Expected behaviour
Echo/execute as many results of find in one **echo**(1) command.

### Actual behaviour
Error status 1: `find: missing argument to '-exec'`.

Same system, same terminal, same everything, just bash: **find**(8) behaves as expected.

Site-note: `... -exec echo {} \;` runs fine even in **fish**(1).

fish is version 2.6.0 out of _Debian_ package repository.

**Comment by Avispa** [comment]
Correction: `find ... -exec {} \;` doesn't drop an error but also behaves wrong and prints empty lines (in case of **echo**(1))

**Comment by krader1961** [comment]
The problem is the empty brace expansion. In fish `{}` expands to nothing. Bash special-cases it to a literal `{}`. See issue #1109 where we've discussed possibly changing this. The solution for now is to put quotes around the braces.

**Comment by zanchey** [comment]
I'm adding this to the FAQ as we've had this often.
