### ISSUE TITLE
How does fish interpret ANSI escape sequences?

### ISSUE THREAD

**Issue by phpHavok** [fish-shell/fish-shell#4203]
Hi, all. I didn't realize you could actually post questions to the issues board until I saw the "question" label. This is a general development question that has no relevance to a specific version of fish or operating system.

I've been reading the source code for a week or so, and I cannot seem to figure out what I feel like should be an obvious thing. How does fish interpret ANSI escape sequences? For example, when I press the "right arrow key," my terminal emulator, rxvt-unicode, sends fish the escape sequence `ESC[C`. If fish were blindly echoing characters to STDOUT, this would move my cursor to the right with no respect to the boundary of the line. However, fish respects the end of the line, so I know it doesn't blindly echo characters. Thus, fish must know to wait upon seeing `ESC` to determine if an escape sequence is being given, if so what the sequence is, and then to interpret the sequence for internal use (i.e., my "up arrow" does not move my cursor up, but instead cycles history).

I've been all throughout the source code, and I've found little breadcrumbs like `wait_on_escape_ms` and others, but I haven't deciphered how this is being handled. I appreciate any insight on this matter.

Thanks!

**Comment by krader1961** [comment]
See the `bind` command and scripts like *share/functions/fish_vi_key_bindings.fish* and *share/functions/fish_default_key_bindings.fish*. We use a combination of named keys as defined in your $TERM terminfo definition and a lot of hardcoded sequences that we know from experience are sent by terminals but don't always have a terminfo entry.

**Comment by krader1961** [comment]
Also, most of the logic for scanning input that matches bindings is in *src/input.cpp* and *src/src/input_common.cpp*.

**Comment by phpHavok** [comment]
Thanks! I think I was able to tie things together given your hints. As a suggestion, could fish limit the search space based on a prefix match? (I could be wrong, but I don't *think* it's currently doing that.) For example, suppose the complete list of bindings is as follows (`*` represents the default binding).

```
\e[C => move cursor to right, respecting boundaries
\e[D => move cursor to left, respecting boundaries
^Axy => do something
^Bzz => do something else
* => echo character to STDOUT
```

Now, if fish receives a `\e` character, it will still build its look-ahead buffer, but on the second character, it only needs to search this space (instead of all mappings):

```
\e[C => move cursor to right, respecting boundaries
\e[D => move cursor to left, respecting boundaries
```

Then, if the second character is say `y`, fish can immediately know that none of the bindings are going to match (search space reached size 0). Thus, it can stop processing without waiting for the timeout.

**Comment by krader1961** [comment]
I'm the person who fixed issue #1356 by implementing the `fish_escape_delay_ms` var and increasing the default delay so that you can use escape as a meta prefix reliably. As part of implementing that change I noted that the current binding matching algorithm is suboptimal and should be rewritten along the lines you propose. Although I can't find an open issue there is a related discussion in issue #3398.

We'd love to see you improve this or any of the 400+ other open issues :smile: There are too few contributors willing to touch the C++ code.

**Comment by phpHavok** [comment]
Thanks for the additional information. I can look into it. The code doesn't scare me, it's just understanding the underlying architecture that is difficult without significant experience with the project. It will take me a while (month or so) to get to it due to my other responsibilities. I'm currently working on my own shell as part of a Master's project, and I'm looking to fish for inspiration, haha.

**Comment by krader1961** [comment]
We'd love to see a CS post-grad contribute improvements. Feel free to ask for help. We've got a [contributing](https://github.com/fish-shell/fish-shell/blob/master/CONTRIBUTING.md) doc that talks about things like the coding style for the project. Good luck with your project.

**Comment by phpHavok** [comment]
Thanks :) Hope I can contribute something useful.
