### ISSUE TITLE
Standalone Windows installer

### ISSUE THREAD

**Issue by mcandre** [fish-shell/fish-shell#4212]
For Windows users, could fish be separated out from cygwin as a standalone installation? That would make it easier for Windows users to get up and running with fish!

**Comment by krader1961** [comment]
That would require a significant amount of work. Fish requires POSIX APIs that Cygwin and the new Windows 10 WSL environment provide. Fish doesn't use the Windows APIs and adding that support is unlikely to ever happen.

**Comment by trajano** [comment]
I'm kind of wondering what kind of POSIX APIs does a shell need?  Maybe a subset without some of the functionality can be done in Windows, I mean they already have `bash` so it may be doable.

**Comment by faho** [comment]
https://github.com/fish-shell/fish-shell/discussions/10123#discussioncomment-7682503
