### ISSUE TITLE
crashes on Haiku OS doing drag-and-drop file at the terminal window

### ISSUE THREAD

**Issue by miqlas** [fish-shell/fish-shell#4216]
Fish version: fish, version 2.6.0
OS: Haiku x86_64 hrev51272
echo $TERM : xterm (Haiku standard Terminal application)

Tested without third-party mods, with clean settings. Reproducible.

Steps to reproduce:

* open Terminal (i suppose fish is he default shell, you can set it in /boot/system/settings/etc/passwd , it requires reboot)
* write "ls " and drop a file from file manager to the terminal, it should add the file path to the command line
* Fish crashes
* profit :(

**Comment by miqlas** [comment]
It crashes somewhere here:

"0xcccccc0074726f80	0x1ab311bcccf	history_t::save_internal(bool) + 0x97"

I'll provide better bugreport later.

**Comment by miqlas** [comment]
Here is the full backtrace.
[backtrace.txt](https://github.com/fish-shell/fish-shell/files/1150612/backtrace.txt)

**Comment by krader1961** [comment]
@miqlas, You're going to have to provide more information. Especially since several recent problems involving fish on Haiku OS have been due to Haiku OS bugs. I've looked at the `history_t::save_internal()` code in light of this issue and your backtrace. There is no obvious reason for fish to fail due to  a SIGSEGV error in that code path. You're going to have to build a custom fish that has debug `printf()` calls in the `history_t::save_internal()` method which shed more light on where the failure occurs.

**Comment by miqlas** [comment]
@krader1961 : I can do that. Where you wish the debug printfs? OR should i do after every operation, like printf"1", then printf"2"? I can do that too.

**Comment by krader1961** [comment]
For this type of problem I start by adding `fwprintf(stderr, L"WTF line %d\n", __LINE__);` calls at strategic points in the code. Then once I've identified a single statement (or small number of likely statements) where the failure is occurring I add additional detail to the printf's such as the value of variables that are used by the code that is failing.

**Comment by miqlas** [comment]
It seems to be already solved in the latest git version, haven't digged further, but it works as it supposed to.
I just close this ticket and reopen it if i met with it again.

Thanks @krader1961!

**Comment by krader1961** [comment]
Fantastic. I can't think of any changes we've made since 2.6.0 was released that would have fixed this problem but it's great that it appears to have been fixed.

**Comment by miqlas** [comment]
Maybe something fixed at Haiku side.. I've Seen some changes in terminal-handling recently.
