### ISSUE TITLE
Using Option-V in tmux gives editor that interacts weirdly with Cmd-V

### ISSUE THREAD

**Issue by jacobsa** [fish-shell/fish-shell#4219]
I'm running fish 2.6.0, tmux 2.5, and vim 8.0.717 on macOS 10.12.5, all installed via homebrew. (I also see this problem with fish and tmux on Linux, over SSH from the macOS terminal.)

I have `EDITOR` set to `/Users/jacobsa/.homebrew/bin/vim`. When I use Option-V from a tmux session to open the editor from fish, vim successfully launches. However it behaves really weirdly with respect to pasting using Cmd-V.

I can reproduce as follows:

1. Open a new terminal window.
2. Run `tmux new -s foo` to start tmux, getting a fish prompt.
3. `sh -c 'env HOME=$(mktemp -d) fish'`
4. `set -x EDITOR /Users/jacobsa/.homebrew/bin/vim`
5. Press escape and then Option-V to open vim.
6. Press `i` to enter insert mode.
7. Type `cd /foo/`.
8. In any application, highlight the character `1` and press Cmd-C.
9. Go to the terminal and press Cmd-V.

Instead of getting `cd /foo/1` in vim as expected, the character `1` doesn't show up and instead the cursor moves to the beginning of the line. It's as if vim interprets the paste as a series of commands (whose contents I'm not sure about).

In contrast, when I do this after just running `vim` from the prompt in tmux, or when I've used Option-V from fish *outside* of tmux, this doesn't happen. The result is `cd /foo/1` as expected.

Any idea what's going on here? I'm aware it's totally possible this is a bug in tmux or in vim or in my configuration rather than in fish, but I have no idea what it might be.

**Comment by krader1961** [comment]
That's because bracketed paste mode is still enabled. Already fixed by commit 352cea165 on June 5.

**Comment by jacobsa** [comment]
Indeed, I can no longer reproduce this after using `brew upgrade -v --HEAD fish` to get to version 2.6.0-246-g06d071dd. Thanks for the quick response! Closing.
