### ISSUE TITLE
Extra output for unknown command

### ISSUE THREAD

**Issue by terlar** [fish-shell/fish-shell#4221]
When the command not found output is displayed it also displays another line without output which seems wrong.

Output:
```
$ unknown
fish: Unknown command 'unknown'
fish: 
$ 
```

Asciinema: https://asciinema.org/a/den6qEoTKGwVRNarWKIYkGPiJ

Version: `fish, version 2.6.0-247-g3e226f0a`
OS: `Linux blackbird 4.11.9-1-ARCH #1 SMP PREEMPT Wed Jul 5 18:23:08 CEST 2017 x86_64 GNU/Linux` (ArchLinux)
Term: `xterm-termite`

**Comment by zanchey** [comment]
Bisects to 385e40540c904a8d16e8b6fcb46ec892ca98bf67

**Comment by krader1961** [comment]
Note that this was originally broken by commit 08d42a0 to fix issue #3649. Then fixed by commit 65c762f to fix issue #4000. Then broken again by commit 385e405. What does that tell you about the code in question? Bueller? Anyone?
