### ISSUE TITLE
`exec_subshell()` function should collect stderr as well as stdout

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#4224]
While working on the fix for issue #4211 I noticed that the `exec_subshell()` function only collects the stdout of the sub shell. This means that any output written to stderr by fish script run via that function is written to file descriptor 2 and cannot be redirected (e.g., to /dev/null) or otherwise processed by the code that calls `exec_subshell()`. This is broken. It's also an example of how the current fish design for managing file descriptors and stdin/stdout/stderr is problematic.

I'm going to work around this by documenting that `argparse` validation code write error messages to stdout rather than the more natural stderr. But having to do so is quite annoying.

**Comment by krader1961** [comment]
This problem also means that commands, such as `test`, run within the argparse argument validation context that write to stderr cannot be captured and redirected by the `argparse` implementation.

**Comment by anordal** [comment]
Is this the cause of #1035 ?

**Comment by krader1961** [comment]
Closing as dup of #1035.
