### ISSUE TITLE
argparse: short-only option that requires an argument considered invalid

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#4232]
With fish version 2.6.0-278-g72968bec (from major):

```fish
$ argparse 'C=' -- -C /home/alfa/
argparse: Invalid option spec 'C=' at char 'C'
```

Since argparse is in 2.7.0, this should be fixed there.

**Comment by faho** [comment]
Just to be clear, "C/banana=" works.

**Comment by krader1961** [comment]
Good catch. Obviously some more unit tests are needed as they should have caught that.
