### ISSUE TITLE
Need help adding synchronization to debug and debug_safe

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4245]
I'm trying to tackle #4235 , starting with the race condition in the output. I'm not familiar enough with fish's threading/ipc model to figure out why nothing other than opening a named semaphore is working.

If I add the following to `debug` and `debug_safe` in `src/common.cpp`, the race condition in `stderr` output disappears:

```C++
    sem_t *debug_semaphore = sem_open("ipc safe", O_CREAT | O_EXCL, 0644, 1);
    sem_wait(debug_semaphore);

    ...

    sem_post(debug_semaphore);
```

But if I do this instead (as I see in other places in fish code):

```C++
pthread_mutex_t debug_lock = PTHREAD_MUTEX_INITIALIZER;
void debug(..) {
    scoped_lock lock(debug_lock);
    ...
}

void debug_safe(..) {
    scoped_lock lock(debug_lock);
    ...
}
```

That doesn't work.

Neither does creating an unnamed semaphore specifically set to allow IPC sharing:

```C++
sem_t debug_semaphore = nullptr;

void init_onetime() {
    //some std::call_once logic, verified to only be called once
    sem_init(&debug_semaphore, 1, 1);
}

void debug(..) {
    //either pthread_once or std::call_once to initialize debug_semaphore
    sem_wait(&debug_semaphore);
    ...
    sem_post(&debug_semaphore);
}

void debug_safe(..) {
    //either pthread_once or std::call_once to initialize debug_semaphore
    sem_wait(&debug_semaphore);
    ...
    sem_post(&debug_semaphore);
}
```

Nor does a shared `std::mutex` do the trick:

```C++
std::mutex debug_mutex;

void debug(..) {
    std::lock_guard<std::mutex> lock(debug_mutex);
    ...
}

void debug_safe(..) {
    std::lock_guard<std::mutex> lock(debug_mutex);
    ...
}
```

I don't understand why unnamed semaphores/mutexes are not working. Shouldn't variables declared in `common.cpp` be shared between the parent and child processes pre/post-`fork`?

(In all cases, synchronization is needed and a race condition does exist without it).

**Comment by mqudsi** [comment]
Placing it in a shared memory segment works.

**Comment by krader1961** [comment]
Do not use IPC semaphores or shared memory. They're not portable. After `fork()` the child has its own copy of each page of memory. Which is why threads and `fork()` don't work well together. See https://github.com/fish-shell/fish-shell/wiki/fish's-Fork-and-Pthread-Manifesto.

If you absolutely have to introduce a shared page that contains a mutex you should use `mmap()`. However, convincing me that is the only viable solution is going to be difficult.
