### ISSUE TITLE
Auto-complete for sub-commands

### ISSUE THREAD

**Issue by singerb** [fish-shell/fish-shell#425]
I work with several source control systems, and all of the use the pattern of having a single executable which runs sub-commands; for example:

```
p4 opened
p4 diff
p4 add foo.c
```

or

```
hg qrefresh
hg qdiff
```

etc. I'm sure the pattern is common and well-known to developers everywhere.

I would love it if there's some way for fish to automatically get:

a) the subcommands as possible completions; right now if I do `p4 r<TAB>` I get `p4 resources/` suggested from my current directory; instead, I'd love to see it suggest revert, rename, etc as completions.
b) the options and arguments to those subcommands. Following on from the above, it would be great if fish knew that p4 revert can take `-c changelist` and `-a -n -k`, while p4 add can take `-t type`, `-c changelist`, etc.

After using the tools for a bit, obviously you get the most common operations you do in your history, and a quick right arrow will pull them up, but for serious use, it'd be great to have the full auto-complete. I imagine that this could be done with custom completions, but in the spirit of fish it'd be great if it could happen automatically.

**Comment by krader1961** [comment]
We now have well established patterns for completing commands with subcommands. And the VCS completions use those patterns. So I think we can consider this to be resolved.

**Comment by navossoc** [comment]
Hey @krader1961 where can I find this patterns?
