### ISSUE TITLE
inconsistent path completion behavior when some paths are upper-case

### ISSUE THREAD

**Issue by thibran** [fish-shell/fish-shell#4264]
version: 2.6.0
$TERM: xterm-256color (alacritty 0.1.0)
Linux: 4.11.8-2-default x86_64

```
# ~/.config/fish/functions/foo.fish
function foo
        echo "zot"
end
```

```
# ~/.config/fish/completions/foo.fish
function __complete_foo
  set -l cmd (commandline -ct)
  if [ $cmd = "" ]
      return 1
  end

  echo -e '/foo/downloads\n/foo/documents\n/foo/.dotfiles'
  #echo -e '/foo/Downloads\n/foo/Documents\n/foo/.dotfiles'
end

complete -c foo -a '--show' -f
complete -c foo -a '(__complete_foo)' -l show -x
```

### Okay

When using `echo -e '/foo/downloads\n/foo/documents\n/foo/.dotfiles'` and typing:

 `foo --show do[tab]`

The completion-list shows, as expected and how it should be, all 3 paths:

`/foo/.dotfiles  /foo/documents  /foo/downloads`

### Problem

But when using `echo -e '/foo/Downloads\n/foo/Documents\n/foo/.dotfiles'`. The completion auto-inserts `/foo/.dotfiles`, swallowing the other results, which is kind of surprising, resulting in: `foo --show /foo/.dotfiles` (the completion list is not displayed).

**Comment by krader1961** [comment]
You're not doing path completion when you use `complete -a '(subcommand)'`. The case-insensitive path matching only applies to implicit file completion not explicit completion args. The behavior you're requesting already has an open issue: #3978.
