### ISSUE TITLE
tutorial should cover basic flow control and comparing values (don't assume the user is familiar with /bin/sh)

### ISSUE THREAD

**Issue by gnzlbg** [fish-shell/fish-shell#4266]
I was trying to find how to compare two values in `fish` shell, e.g. to see if a string is empty, but the tutorial doesn't even mention any comparisons operators at all. It might be a good idea to show them when introducing conditionals at least for strings and numbers (e.g. how to check whether two numbers are equal, or one smaller than the other, or how to check whether two strings are equal, one string is the empty string, two paths are equal, etc.).

**Comment by geoffmacintosh** [comment]
I think you're looking for (test)[http://fishshell.com/docs/current/commands.html#test]! I got this wrong initially as well, and spent an embarrassing amount of time learning the correct words.

**Comment by gnzlbg** [comment]
The tutorial doesn't even mention test at all. 

I want to do something like

```fish
if count($argv) == 0 or count($argv) == 3 
  echo "Something"
else
  echo "Something else"
end
```

And its impossible to even guess what the syntax for that is from the tutorial.

**Comment by krader1961** [comment]
Yes, we should probably augment the tutorial. At the moment it assumes you have had prior experience with the Bourne shell (/bin/sh) or one of its descendents like ksh or bash and mostly focuses on how fish is different.

To answer your specific question the first thing to keep in mind is fish syntax is not like that of other programming languages you might be familiar with. There is no `count()` function. There is a `count` command that takes zero or more arguments. So it's `count $argv` not `count($argv)`. Second, as @geoffmacintosh, points out the command for testing things like string equality is `test`. Third, to substitute the output of a command as an argument for another command you use parenthesis. Putting it all together we get this:

```
if test (count $argv) -eq 0 -o (count $argv) -eq 3
```

**Comment by faho** [comment]
`test` is now mentioned in the tutorial, in the section on "Conditionals".

It has been before the sphinx conversion AFAICT, so I'm closing this without a milestone.
