### ISSUE TITLE
set -U in presence of similarly-named global variable behavior & messages

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4267]
I think there's something unintuitive about the behavior of `set -U ...` when there is a conflicting global variable already defined.

``` fish
> set -g TEST_VARIABLE foo
> set -U TEST_VARIABLE bar
set: Warning: universal scope selected, but a global variable 'TEST_VARIABLE' exists.
> echo $TEST_VARIABLE
foo
```

Either this is a warning letting you know that there _was_ an existing global variable that has been overwritten or it is an error letting you know that it couldn't be set because there is a conflicting global variable already defined.

**Comment by krader1961** [comment]
This warning was implemented in response to issue #806. The behavior is actually different from both of your hypothesis. It's also more subtle. The uvar is set. However, the resolution order is local -> global -> universal. So after doing `set -g var` followed by `set -U var` resolving `$var` stops with the global scope. But if you start a new fish instance it will resolve the universal instance assuming you haven't explicitly done `set -g var` in, say, *~/.config/fish/config.fish*. A more accurate warning would be something like

"universal var 'TEST_VARIABLE' created but shadowed by global var of the same name. New fish shells will see the value of the universal instance unless they also do `set -g TEST_VARIABLE`."

Sadly I don't think there is any reasonable length warning we could emit that would be clear to a typical user. We should probably instead replace most of the text with a URL to the relevant documentation at fishshell.com.

**Comment by mqudsi** [comment]
Thanks for clarifying. `set -e TEST_VARIABLE` results in the `bar` declaration becoming visible, which makes sense. 

I guess we can just close this?

**Comment by krader1961** [comment]
Let's leave it open a couple of days to see if anyone thinks we can do better such as by replacing most of the message with a link to fishshell.com. Or perhaps reword the message along these lines (my previous verbose message minus the second sentence):

"Universal var 'TEST_VARIABLE' created but shadowed by global var of the same name."

**Comment by mqudsi** [comment]
fwiw, I like that message.

**Comment by zanchey** [comment]
I've updated the language slightly in 5d2a806a.
