### ISSUE TITLE
brew cask completion

### ISSUE THREAD

**Issue by dikti** [fish-shell/fish-shell#4271]
If trying to install some homebrew cask (`brew cask install foo<tab>`), it completes the current directory instead. With regular Homebrew (`brew install foo<tab>`), completion works. Using a fresh unconfigured fish, the problem persists.

    $ echo $version
    2.6.0
    $ uname -a
    Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
    $ echo $TERM
    xterm-256color # its iTerm2

**Comment by krader1961** [comment]
Someone simply needs to enhance the `brew` completions script to handle that case. Patches welcomed.

**Comment by laughedelic** [comment]
JFYI, I'm working on this now, rewriting brew completions including brew cask. The current completions lack a lot of commands.

**Comment by zanchey** [comment]
This is another case where having the completions upstream would make a lot of sense - perhaps you would look at submitting them?

**Comment by laughedelic** [comment]
@zanchey yes! I was going to ask about it: if a program provides completions on installation (like bash and zsh) already, wouldn't it make more sense to add fish ones there too. This would have an advantage of evolving together with the tool, instead of being stuck with the fish release cycle.

**Comment by laughedelic** [comment]
Hey @dikti, I just published a plugin for improved brew completions: https://github.com/laughedelic/brew-completions

Check it out. I also includes completions for `brew cask`. I'm still working on it (mainly cachin to improve completions speed), but it's pretty much usable already.

Feedback is welcome.

**Comment by MindTooth** [comment]
https://github.com/fish-shell/fish-shell/pull/4647

Care to take a look?

**Comment by zanchey** [comment]
Fixed with #4647.
