### ISSUE TITLE
is_forked_child() checks wrongly pass after fork

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4273]
A lot of places in the codebase need to be called specifically from the main thread of the main process and not a forked child.

In common.cpp, there is a fork guard:

```cpp
void setup_fork_guards(void) {
    // Notice when we fork by stashing our pid. This seems simpler than pthread_atfork().
    initial_pid = getpid();
}
```

which is first set up then compared via the `is_forked_child()` function, which tests the current pid against the stored one:

```cpp
bool is_forked_child(void) {
    // Just bail if nobody's called setup_fork_guards, e.g. some of our tools.
    if (!initial_pid) return false;

    bool is_child_of_fork = (getpid() != initial_pid);
    if (is_child_of_fork) {
        debug(0, L"Uh-oh: getpid() != initial_pid: %d != %d\n", getpid(), initial_pid);
        while (1) sleep(10000);
    }
    return is_child_of_fork;
}
```

However, if fish forks then execs itself, the main fish entrypoint will be called and `setup_fork_guards()` will be called again, overwriting the existing `initial_pid` value with the pid of the _forked_ process, making future checks for `is_forked_child()` from the forked process pass rather than fail.

Is this intentional, i.e. the fork guards are only to protect from calling a function before calling exec and it's OK if those functions are called via a spawned/fork-exec'd fish instance?

**Comment by krader1961** [comment]
Keep in mind that a lot of this code was written more than 12 years ago by someone who had some great ideas but not a good grasp of UNIX process management and job control (including tty ownership).

If fish execs itself then the entry point should be run and `setup_fork_guards()` called. That process is independent of the fish instance which did the `fork()`. The logic you're looking at is solely intended to deal with fish processes that have called `fork()` but not `exec()`.

Whether that mechanism is useful or the best way of achieving the goals it was implemented for is another question. Personally, I would like to eliminate this logic in favor of ensuring that all threads are quiescent before calling `fork()`.

**Comment by krader1961** [comment]
Also, did you get my private email about becoming a core fish committer?

**Comment by mqudsi** [comment]
This is pretty closely related to the discussion in #4183 but I think this is the problem behind #2915 

I thought if I added this test to `setup_fork_guards`:

```cpp
void setup_fork_guards(void) {
    // Notice when we fork by stashing our pid. This seems simpler than pthread_atfork().
    if (initial_pid != 0) {
        debug(0, "Calling setup_fork_guards from forked child!\n");
    }
    initial_pid = getpid();
}
```

that everything would blow up everywhere, but surprisingly it only appeared during the multithreaded history tests (which doesn't always pass on FreeBSD, btw. I'll bug it., which leads me to believe that it is, in fact, not intentional.

This explains why #2915 was getting into a seemingly impossible state (the RAII `scoped_lock` not owning the thread it locked in its destructor) and why none of the `assert(!is_forked_child())` tests caught it earlier.

Not sure if there's a point in tracking this one down if we're going to tackle the underlying issue with forks and thread states.

**Comment by krader1961** [comment]
Perhaps I'm misunderstanding what you're saying but I don't see how `if (initial_pid != 0) {` would ever be true. We call that function exactly one place: from `main()`. And that is only run when a new process is instantiated via the `exec()` family of functions. That new process shares nothing with its parent shell. If we were somehow calling `main()` after `fork()` (but before `exec()`) then, yes, there would be a bug. But it wouldn't have anything to do with how `initial_pid` is used.

**Comment by mqudsi** [comment]
You didn't misunderstand, it's as weird as it sounds :)

This is where my lack of familiarity with the codebase comes in. I wouldn't want to presume that fish's main was being improperly called and would have presumed that any calls to it (and not via exec) were deliberate, in which case I presumed the error was in the overwriting of `initial_pid`.

It is indeed odd but that check does indeed trigger:

```
Testing history merge
Testing history race conditions
<E> (ignore): 22252: initial_pid is being re-initialized from its previous value of 22064 by process 22252
<E> (ignore): 22253: initial_pid is being re-initialized from its previous value of 22064 by process 22253
<E> (ignore): 22254: initial_pid is being re-initialized from its previous value of 22064 by process 22254
<E> (ignore): 22255: initial_pid is being re-initialized from its previous value of 22064 by process 22255
<E> (ignore): 22256: initial_pid is being re-initialized from its previous value of 22064 by process 22256
<E> (ignore): 22257: initial_pid is being re-initialized from its previous value of 22064 by process 22257
<E> (ignore): 22258: initial_pid is being re-initialized from its previous value of 22064 by process 22258
<E> (ignore): 22259: initial_pid is being re-initialized from its previous value of 22064 by process 22259
<E> (ignore): 22260: initial_pid is being re-initialized from its previous value of 22064 by process 22260
<E> (ignore): 22261: initial_pid is being re-initialized from its previous value of 22064 by process 22261
```

**Comment by krader1961** [comment]
Okay, that is seriously broken. Add a `show_stackframe(L'E');` after you print that message. It should be impossible to call `main()` more than once and it shouldn't be called after `fork()`. I wonder if something is wrong with the way we're invoking callbacks on the main thread from other threads. Probably a good idea to add a `ASSERT_IS_MAIN_THREAD();` after the show_stackframe as well.

**Comment by mqudsi** [comment]
On taking a closer look, it seems that `setup_fork_guard()` (which sets `initial_pid`) is actually being called from outside of `main()`... but only in the test code. 

```cpp
    pid_t children[RACE_COUNT];
    for (size_t i = 0; i < RACE_COUNT; i++) {
        pid_t pid = fork();
        if (!pid) {
            // Child process.
            setup_fork_guards();
            test_history_races_pound_on_history(ITEM_COUNT);
            exit_without_destructors(0);
        } else {
            // Parent process.
            children[i] = pid;
        }
    }
```

I think it's working correctly given how it's used?

**Comment by krader1961** [comment]
> I think it's working correctly given how it's used?

Yes, but it makes my skin crawl. It's wrong for *fish_tests.cpp* to do that because the assumption is that is the only thing necessary to ensure the child process is in an equivalent state to the parent after it has done its setup in `main()` but before doing any work. What's really needed is a way to ensure we only fork after ensuring all threads are blocked at a point where they hold no mutexes; that is, are quiescent.

**Comment by mqudsi** [comment]
Yes, I understand and agree. I think I might tackle that next.
