### ISSUE TITLE
execute:  date -s "`date +'%F %T' --date='+1 hour'`"  error

### ISSUE THREAD

**Issue by iclodq** [fish-shell/fish-shell#4274]
fish version:2.6.0
`uname -a` : Linux ubuntu 3.16.0-30-generic #40~14.04.1-Ubuntu SMP Thu Jan 15 17:43:14 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
`echo $TERM`:xterm

I executed the cmd: 
```bash
#in bash, it's ok. 
date -s "`date +'%F %T' --date='+1 hour'`"
#or 
date -s "`date +"%F %T" --date="+1 hour"`"
#And in fish, it's error.
#error msg:  date: invalid date ‘`date +"%F %T" --date="+1 hour"`’
```

**Comment by krader1961** [comment]
Your example fails for me using bash as my shell. That is, it is not okay in bash. On either macOS or Ubuntu 16.10.

Having said that, fish does not recognize or implement using backticks to invoke subcommands. That is a feature of POSIX compatible shells. Fish has only minimal compatibility with the POSIX 1003 shell standard.

**Comment by iclodq** [comment]
Sorry, the cmd is error ,I modified it right .
Now, I know why it dose incorrectly , thanks for your explanation , and I will read the docs of fish  later.
But,  how could I do that add an hour at now in fish?

**Comment by krader1961** [comment]
See the section about command substitution in the tutorial: http://fishshell.com/docs/current/tutorial.html#tut_command_substitutions

```
set new_time (date +"%F %T" --date="+1 hour")
date -s "$new_time"
```
