### ISSUE TITLE
emit sometimes doesn't work.

### ISSUE THREAD

**Issue by sassanh** [fish-shell/fish-shell#4275]
```
> fish --version
fish, version 2.6.0
> echo $version
2.6.0
> uname -v
Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64
> echo $TERM # I'm using iTerm
xterm-256color
```

I'm using `virtualfish` ~2 years, I've created lots of virtual environments with it so far. I usually use
```
function activate_X --on-event virtualenv_did_activate:X
    set -gx DJANGO_SETTINGS_MODULE X.settings.development
end
```
and it used to work alright till now. Now I created another virtualenv with vf, created the function and saw that it doesn't get called (I added a `echo 123` inside it and it's not being called).

If I do a `funced activate_X` and then `vf activate X` it works.
If i do a `functions --details activate_X` and then `vf activate X` it works.
But in a new terminal without doing above it doesn't work. seems like I somehow should introduce my function to fish with above lines.
The function is stored with `funcsave` in `~/.config/fish/functions/`.
It works for other virtual environments.

I opened `/usr/local/lib/python3.6/site-packages/virtualfish/virtual.fish` and added `echo (basename $VIRTUAL_ENV)` before `emit virtualenv_did_activate:(basename $VIRTUAL_ENV)` and it prints "X", so it's not a problem in virtualfish. I even changed `emit virtualenv_did_activate:(basename $VIRTUAL_ENV)` to `emit virtualenv_did_activate:X` and it didn't work.

What information can I provide so that you can debug it?

**Comment by faho** [comment]
> The function is stored with funcsave in ~/.config/fish/functions/.

The issue is these files are autoloaded. They only get `source`d when the function is called, and only then are they registered to their events (how is fish supposed to know that the definition includes an "--on-event" without reading the file?).

Store the function in a file in ~/.config/fish/conf.d or in config.fish and it'll work.

**Comment by sassanh** [comment]
Thanks for quick reply.
