### ISSUE TITLE
fish_config does not work in centos 7 installed from epel repo

### ISSUE THREAD

**Issue by dajiaonao** [fish-shell/fish-shell#4283]
Hi,
I have installed fish on my centos 7

> Linux  3.10.0-514.26.2.el7.x86_64 #1 SMP Tue Jul 4 15:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

And the info of the package is:

> Name        : fish
> Arch        : x86_64
> Version     : 2.3.1
> Release     : 1.el7
> Size        : 7.4 M
> Repo        : installed
> From repo   : epel
> Summary     : A friendly interactive shell
> URL         : https://fishshell.com/
> License     : GPLv2
> Description : fish is a fully-equipped command line shell (like bash or zsh) that is
>             : smart and user-friendly. fish supports powerful features like syntax
>             : highlighting, autosuggestions, and tab completions that just work, with
>             : nothing to learn or configure.
> 

The problem is that when I run fish_config, I get

> fish_config 
Failed to execute process '/usr/share/fish/tools/web_config/webconfig.py'. Reason:
The file '/usr/share/fish/tools/web_config/webconfig.py' does not exist or could not be executed.

If i check the file, it does exist, but the  first a few lines are:

> head /usr/share/fish/tools/web_config/webconfig.py
```
#!%{__python34}

from __future__ import unicode_literals
# Whether we're Python 2
import sys
import multiprocessing.pool
import os
import operator
import socket
IS_PY2 = sys.version_info[0] == 2
```
If I try
> python /usr/share/fish/tools/web_config/webconfig.py

It works. So it seems the problem is due the the header of the file is not correctly parsed during the installation.

It might already be solved in later versions, but I didn't find issues about it by a quick search in the issue list and release notes.... or maybe it's not a problem of fish. But I think it's better to report it.

Thanks for the pretty shell...

**Comment by krader1961** [comment]
Not sure what went wrong or whose fault it is but there isn't anything we can do about that old version. The current version for RHEL7 has the correct header. You can find the package here: https://build.opensuse.org/package/binary/shells:fish:nightly:master/fish?arch=x86_64&filename=fish-2.6.0%2B289.g067892c4-1.1.x86_64.rpm&repository=RHEL_7

**Comment by zanchey** [comment]
This is the same issue as #4121 and should be reported to the EPEL maintainers.
