### ISSUE TITLE
remove the `.` (dot) command as an alias for `source`

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#4294]
Fish 3.0 is a good opportunity to remove the `.` (dot) command. It is superfluous as the `source` command provides a superset of its capabilities and we'd prefer people use the `source` command. See issue #1501 for an example of why `.` is problematic.

**Comment by krader1961** [comment]
When I say "`source` provides a superset of its capabilities" I mean that `source` can read its input from stdin while `.` cannot. So you can do `echo fish script | source` but not `echo fish script | .`.

**Comment by krader1961** [comment]
Note that the `.` command was deprecated by issue #310 and commit 5818289c2 four years ago. I think that's a long enough deprecation period :smile:

**Comment by krader1961** [comment]
Fixed with commit 55bef3cd2ee.

**Comment by zanchey** [comment]
@xfix will be pleased :-)
