### ISSUE TITLE
eval $(minik4ube docker-env) not working

### ISSUE THREAD

**Issue by JenneyJ** [fish-shell/fish-shell#4296]
Please tell us which fish version you are using by executing the following:

  fish --**version (2.4.0)** 
  echo $version

Im using **mac 10.12.14**

While trying to run this command 
`eval $(minik4ube docker-env)`

I got error:
`$(...) is not supported. In fish, please use '(minik4ube)'`

I tried to use 
`eval '(minik4ube docker-env)'`

```
Illegal command name '(minik4ube docker-env)'
- (line 1): begin; (minik4ube docker-env) 
                   ^
from sourcing file -
	called on line 60 of file /usr/local/share/fish/functions/eval.fish

in function 'eval'
	called on standard input

source: Error while reading file '-'
```

How can I run it in fish ?

The command is from
https://kubernetes.io/docs/getting-started-guides/minikube/#reusing-the-docker-daemon

**Comment by JenneyJ** [comment]
Please tell us which fish version you are using by executing the following:

  fish --version (2.4.0) 
  echo $version

Im using mac 10.12.14

While trying to run this command 
eval $(minik4ube docker-env)

I got error:
$(...) is not supported. In fish, please use '(minik4ube)'

I tried to use 
eval '(minik4ube docker-env)'


Illegal command name '(minik4ube docker-env)'
- (line 1): begin; (minik4ube docker-env) 
                   ^
from sourcing file -
	called on line 60 of file /usr/local/share/fish/functions/eval.fish

in function 'eval'
	called on standard input

source: Error while reading file '-'

How can I run it in fish ?

**Comment by zanchey** [comment]
Are you supposed to run `minikube` or `mini4kube`?

**Comment by JenneyJ** [comment]
IM using minikube
installed via - brew cask install minikube

**Comment by zanchey** [comment]
And are you running the command `minikube`, or the (possibly incorrect) `mini4kube` like your transcripts suggest?

**Comment by JenneyJ** [comment]
Im running minicube but the command should be eval $(minik4ube docker-env)

**Comment by krader1961** [comment]
This, ```eval '(minik4ube docker-env)'```, won't work because fish does not do command substitution inside quoted strings (fish 3.0 will probably support that). The quotes in the error message aren't meant to be included. If you omit the single quotes it might work. but only if `minik4ube docker-env` outputs statements compatible with fish. If it outputs statements that will only work in a POSIX compatible shell like bash then it won't work. However, if it's just setting variables then the [bass](https://github.com/edc/bass) plugin can usually  transform the output into a form compatible with fish.

**Comment by JenneyJ** [comment]
I want to test it with fish 3, Does the upgrade remove the history ?
what is the simplest way to upgrade on MAC?

Thanks! Fish is awesome !

**Comment by krader1961** [comment]
The only way to test fish 3.0 at the moment is to build from source; specifically `git checkout major; ./configure --prefix=/usr/local; make install`. Note that we have not yet implemented support for command substitution inside quoted strings. That's on the [to do](https://github.com/fish-shell/fish-shell/milestone/18) list. As is changing the history file format.

**Comment by faho** [comment]
@JenneyJ: I believe the question at hand has been answered. To reiterate:

- Use `eval (command)` (without quotes) or (preferred) `command | source`

- Most likely the script your command prints won't be compatible with fish, so you need to transform it.

**Comment by soad1982** [comment]
I run this script after the minikube start command.

`minikube docker-env > variables.temp`
`sed -i.back 's/export/set -g -x/g' variables.temp`
`sed -i.back 's/=/ /g' variables.temp`
`cat ~/.config/fish/config.fish | grep -v DOCKER > config.temp`
`cat variables.temp >> config.temp`
`rm ~/.config/fish/config.fish`
`mv config.temp ~/.config/fish/config.fish`

It might be not the best approach but configures my environment.

**Comment by dangets** [comment]
I created a function to parse output from (minikube docker-env).  [gist](https://gist.github.com/dangets/837d09d2c381bcdc0a56a18cb2d8ae4c)
