### ISSUE TITLE
Sudo Highlighting

### ISSUE THREAD

**Issue by MggMuggins** [fish-shell/fish-shell#4297]
From the guidelines:
```
$ fish --version
fish, version 2.6.0
$ uname -a
Linux Orion 4.9.39-1-MANJARO #1 SMP PREEMPT <date> x86-64 GNU/Linux
$ echo $TERM
xterm-color
```
Alright, this is more of a question/enhancement than a proper issue, but I thought I'd file it since this is the appropriate place to do so. I prefer to use sudo rather than su to do root actions (because a root shell makes me nervous...). What would it take to get syntax highlighting for sudo similar to the regular prompt? I mean highlighting an argument in red if it isn't a valid command, that sort of thing. If you need me to elaborate, I'm happy to.
Thanks for fish!

**Comment by krader1961** [comment]
Already been asked. See issue #2953.
