### ISSUE TITLE
completions at blank prompt should disappear on interrupt

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4298]
Scenario:

```
$ <tab> <Ctrl+C>
```

At the first `<tab>` the completions prompt appears, but at `<ctrl+c>` (any number thereof) the completions persist. Following the principle of least surprise, I propose that if `<ctrl+c>` when no command is running resets the prompt, then it should accordingly also close the completions dialog.

**Comment by floam** [comment]
Yeah, I'd expect the pager to disappear too.
