### ISSUE TITLE
compile failed

### ISSUE THREAD

**Issue by jinleileiking** [fish-shell/fish-shell#4300]
from latest git
centos 6

```
➜  fish-shell git:(master) autoreconf --no-recursive
configure.ac:89: error: possibly undefined macro: AC_CONFIG_MACRO_DIRS
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1```

**Comment by zanchey** [comment]
From the README:

> autoconf 2.60 or later, as well as automake 1.13 or later, are required to build from git versions

Automake shipped with CentOS 6 is too old. If you do need to run a git version, can I suggest [our master packages](https://software.opensuse.org/download.html?project=shells%3Afish%3Anightly%3Amaster&package=fish)?

**Comment by jinleileiking** [comment]
@zanchey centos6 == redhat ?  5, 6 or 7?

**Comment by zanchey** [comment]
The versions are equivalent - so RedHat 6 packages should work fine.

**Comment by jinleileiking** [comment]
[root@tjwq01-ibu-video007106 yum.repos.d]# yum install fish
Loaded plugins: fastestmirror, security
Setting up Install Process
Repository epel is listed more than once in the configuration
Loading mirror speeds from cached hostfile
 * ius: mirror.ehv.weppel.nl
runner_gitlab-ci-multi-runner-source/signature                                                                                                                                                                         |  836 B     00:00
runner_gitlab-ci-multi-runner-source/signature                                                                                                                                                                         |  951 B     00:00 ...
Resolving Dependencies
--> Running transaction check
---> Package fish.x86_64 0:2.0.0r2-1.el6.rf will be updated
---> Package fish.x86_64 0:2.6.0+298.g5d2a806a-1.1 will be an update
--> Processing Dependency: libc.so.6(GLIBC_2.15)(64bit) for package: fish-2.6.0+298.g5d2a806a-1.1.x86_64
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.18)(64bit) for package: fish-2.6.0+298.g5d2a806a-1.1.x86_64
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.15)(64bit) for package: fish-2.6.0+298.g5d2a806a-1.1.x86_64
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.14)(64bit) for package: fish-2.6.0+298.g5d2a806a-1.1.x86_64
--> Processing Dependency: hostname for package: fish-2.6.0+298.g5d2a806a-1.1.x86_64
--> Finished Dependency Resolution
Error: Package: fish-2.6.0+298.g5d2a806a-1.1.x86_64 (shells_fish_nightly_master)
           Requires: libc.so.6(GLIBC_2.15)(64bit)
Error: Package: fish-2.6.0+298.g5d2a806a-1.1.x86_64 (shells_fish_nightly_master)
           Requires: hostname
Error: Package: fish-2.6.0+298.g5d2a806a-1.1.x86_64 (shells_fish_nightly_master)
           Requires: libstdc++.so.6(GLIBCXX_3.4.14)(64bit)
Error: Package: fish-2.6.0+298.g5d2a806a-1.1.x86_64 (shells_fish_nightly_master)
           Requires: libstdc++.so.6(GLIBCXX_3.4.18)(64bit)
Error: Package: fish-2.6.0+298.g5d2a806a-1.1.x86_64 (shells_fish_nightly_master)
           Requires: libstdc++.so.6(GLIBCXX_3.4.15)(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by jinleileiking** [comment]
cannot work

**Comment by jinleileiking** [comment]
[root@tjwq01-ibu-video007106 yum.repos.d]# yum install fish --skip-broken
Loaded plugins: fastestmirror, security
Setting up Install Process
Repository epel is listed more than once in the configuration
Loading mirror speeds from cached hostfile
 * ius: mirror.ehv.weppel.nl
Resolving Dependencies
--> Running transaction check
---> Package fish.x86_64 0:2.0.0r2-1.el6.rf will be updated
---> Package fish.x86_64 0:2.6.0+298.g5d2a806a-1.1 will be an update
--> Processing Dependency: libc.so.6(GLIBC_2.15)(64bit) for package: fish-2.6.0+298.g5d2a806a-1.1.x86_64
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.18)(64bit) for package: fish-2.6.0+298.g5d2a806a-1.1.x86_64
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.15)(64bit) for package: fish-2.6.0+298.g5d2a806a-1.1.x86_64
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.14)(64bit) for package: fish-2.6.0+298.g5d2a806a-1.1.x86_64
--> Processing Dependency: hostname for package: fish-2.6.0+298.g5d2a806a-1.1.x86_64

Packages skipped because of dependency problems:
    fish-2.6.0+298.g5d2a806a-1.1.x86_64 from shells_fish_nightly_master

**Comment by zanchey** [comment]
Thanks, I'll take a look.

**Comment by jinleileiking** [comment]
I am trying to upgrade automake and build from git.

**Comment by zanchey** [comment]
I'm a bit confused - there isn't an x86_64 package for that version. Did you take the RHEL 7 repo instead?

**Comment by jinleileiking** [comment]
I have tried the 3 repo. All cannot work.

**Comment by jinleileiking** [comment]
centos 6 cannot install gcc4.8+...

fish cannot swim in centos6 :(

**Comment by zanchey** [comment]
It works for me:

```
bash-4.1# cd /etc/yum.repos.d/
bash-4.1# wget http://download.opensuse.org/repositories/shells:fish:nightly:master/RedHat_RHEL-6/shells:fish:nightly:master.repo
bash-4.1# yum install fish
bash-4.1# fish --version
fish, version 2.6.0-298-g5d2a806a
bash-4.1# cat /etc/redhat-release
CentOS release 6.9 (Final)
```

**Comment by jinleileiking** [comment]
[root@tjwq01-ibu-video007106 yum.repos.d]# yum --showduplicates list fish | expand
Repository epel is listed more than once in the configuration
Loaded plugins: fastestmirror, security
Loading mirror speeds from cached hostfile
 * ius: mirror.ehv.weppel.nl
Available Packages
fish.x86_64          1.23.1-1.el6.rf                  dag
fish.x86_64          2.0.0r2-1.el6.rf                 dag
fish.i686            2.6.0-1.1                        shells_fish_release_2
fish.i686            2.6.0+298.g5d2a806a-1.1          shells_fish_nightly_master
[root@tjwq01-ibu-video007106 yum.repos.d]#

**Comment by jinleileiking** [comment]
why x86_64 has no version 2.6?

**Comment by jinleileiking** [comment]
yum install fish.i686 ok

**Comment by zanchey** [comment]
There's no 64-bit version because of the G++ 4.8 requirement - getting that on a 64-bit build machine turned out to be basically impossible (after about 40 hours of trying). There's almost no benefit from the 64-bit version, so I decided that was an acceptable tradeoff.

**Comment by floam** [comment]
<blockquote>(after about 40 hours of trying)</blockquote>

I just want you to know that I appreciate everything you do. I have lit a candle for you.
