### ISSUE TITLE
The warning message about exiting with active jobs is not expressive enough

### ISSUE THREAD

**Issue by peoronoob** [fish-shell/fish-shell#4303]
Coming from bash, I'm surprised every time I get the following message when I try to exit a shell:
```
There are still jobs active (use the jobs command to see them).
A second attempt to exit will terminate them.
```

I've been coexisting with this "issue" for a while now, either by leaving the shell running or by killing the active processes (stuff like my browser, usually) and rerunning them through my DE's launcher.
I tired to look up the issue on Google a bunch of times, but the first Google result was something like #3737, which seemed unrelated and made me desist.
Now I just spent more than 5 minutes digging, and finally understood what's going on.

I believe that most users would have an easier time if the exit warning were a little clearer; something similar to the following would have been ideal for me:
```
echo "There are still jobs active:"
jobs
echo
echo "Use `disown [PID]` to let them live independently from fish."
echo "A further attempt to exit will terminate the active jobs."
echo "See `man 1 jobs`, `man 1 disown` or $LINK_TO_FISH_FAQ for further details."
```
Could this become a thing?

In case, I tried to patch fish implenting this behavior ( https://github.com/peoronoob/fish-shell/commit/06edb7cbb4d5955bff2c80e59cec3643c865a7b2 ), but am unsure about how to proceed for what concerns translations and tests.

**Comment by krader1961** [comment]
Seems a trifle verbose to me although I don't have any objection to displaying the jobs and adding the sentence to let the user know they can use the `disown` command. I'd drop the final sentence. If someone using the shell doesn't know to type `man disown` or `help disown` they probably shouldn't be putting jobs in the background :smile:

With respect to changing a message you don't have to worry about translations. They're a best effort thing and if there is no matching translation the english text will be displayed. Updating unit tests, however, is required.
