### ISSUE TITLE
Consider switching to C++11 regex instead of depending on pcre

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4304]
Just a thought, but as we require a fully C++11-compatible compiler to build fish, perhaps we can consider using the native [C++11 regex support](http://en.cppreference.com/w/cpp/regex) instead of depending on pcre?

**Comment by faho** [comment]
I love the idea of removing a dependency.

However, I have two questions:

- How compatible is the dialect? So far I haven't seen any difference apart from `$&` being supported in std::regex, but that's currently an error in `string`, so it wouldn't be an issue.

- Is the performance _good enough_? It doesn't have to be _faster_, it can even be a bit slower. But `string match -r` shouldn't suddenly slower than `echo | grep` for simple matches. https://stackoverflow.com/questions/41481811/why-pcre-regex-is-much-faster-than-c11-regex says std::regex is about 100x slower than pcre. That might be problematic.

**Comment by mqudsi** [comment]
I fully agree with your comments, but I've learned not to take any benchmarks I find online except with a grain of salt.

I forked @rust-leipzig's regex benchmark (originally by sljit) and added support for C++11's regex library to get some real numbers.

The end result is that C++11's regex performance is no rocket, but it's not *that* bad, either:

```
mqudsi@ZBook /m/c/U/M/D/r/build> ./src/regex_perf -f ../3200.txt -o ./results.csv | tee results.txt
'../3200.txt' loaded. (Length: 16013977 bytes)
-----------------
Regex: 'Twain'
[      pcre] time:     3.1 ms (+/- 223.6 %), matches:      811
[  pcre-dfa] time:    12.5 ms (+/- 55.9 %), matches:      811
[  pcre-jit] time:    18.8 ms (+/- 37.3 %), matches:      811
[       re2] time:     3.1 ms (+/- 223.6 %), matches:      811
[      onig] time:    15.6 ms (+/-  0.0 %), matches:      811
[       tre] time:   196.9 ms (+/-  4.3 %), matches:      811
[     hscan] time:     3.1 ms (+/- 223.6 %), matches:      811
[rust_regex] time:     0.0 ms (+/- -nan %), matches:      811
[     cpp11] time:   265.6 ms (+/-  0.0 %), matches:      811
-----------------
Regex: '(?i)Twain'
[      pcre] time:    50.0 ms (+/- 14.0 %), matches:      965
[  pcre-dfa] time:    65.6 ms (+/- 10.6 %), matches:      965
[  pcre-jit] time:    15.6 ms (+/-  0.0 %), matches:      965
[       re2] time:    56.2 ms (+/- 15.2 %), matches:      965
[      onig] time:    84.4 ms (+/- 10.1 %), matches:      965
[       tre] time:   259.4 ms (+/-  3.3 %), matches:      965
[     hscan] time:     3.1 ms (+/- 223.6 %), matches:      965
[rust_regex] time:    31.2 ms (+/-  0.0 %), matches:      965
[     cpp11] time:   628.1 ms (+/-  1.1 %), matches:      965
-----------------
Regex: '[a-z]shing'
[      pcre] time:   325.0 ms (+/-  2.2 %), matches:     1540
[  pcre-dfa] time:   509.4 ms (+/-  1.7 %), matches:     1540
[  pcre-jit] time:    15.6 ms (+/-  0.0 %), matches:     1540
[       re2] time:   109.4 ms (+/- 10.1 %), matches:     1540
[      onig] time:    15.6 ms (+/-  0.0 %), matches:     1540
[       tre] time:   296.9 ms (+/-  0.0 %), matches:     1540
[     hscan] time:     6.2 ms (+/- 136.9 %), matches:     1540
[rust_regex] time:     6.2 ms (+/- 136.9 %), matches:     1540
[     cpp11] time:   393.8 ms (+/-  1.8 %), matches:     1540
-----------------
Regex: 'Huck[a-zA-Z]+|Saw[a-zA-Z]+'
[      pcre] time:    18.8 ms (+/- 37.3 %), matches:      262
[  pcre-dfa] time:    18.8 ms (+/- 37.3 %), matches:      262
[  pcre-jit] time:     6.2 ms (+/- 136.9 %), matches:      262
[       re2] time:    37.5 ms (+/- 22.8 %), matches:      262
[      onig] time:    31.2 ms (+/-  0.0 %), matches:      262
[       tre] time:   293.8 ms (+/-  2.4 %), matches:      262
[     hscan] time:     3.1 ms (+/- 223.6 %), matches:      977
[rust_regex] time:     6.2 ms (+/- 136.9 %), matches:      262
[     cpp11] time:   387.5 ms (+/-  3.4 %), matches:      262
-----------------
Regex: '\b\w+nn\b'
[      pcre] time:   496.9 ms (+/-  1.4 %), matches:      262
[  pcre-dfa] time:   731.2 ms (+/-  1.0 %), matches:      262
[  pcre-jit] time:    78.1 ms (+/-  0.0 %), matches:      262
[       re2] time:    34.4 ms (+/- 20.3 %), matches:      262
[      onig] time:   568.8 ms (+/-  1.5 %), matches:      262
[       tre] time:   493.8 ms (+/-  1.7 %), matches:      262
[     hscan] time:   115.6 ms (+/-  7.4 %), matches:      262
[rust_regex] time:   165.6 ms (+/-  5.2 %), matches:      262
[     cpp11] time:  2384.4 ms (+/-  0.6 %), matches:      262
-----------------
Regex: '[a-q][^u-z]{13}x'
[      pcre] time:   393.8 ms (+/-  1.8 %), matches:     4094
[  pcre-dfa] time:  1362.5 ms (+/-  0.5 %), matches:     4094
[  pcre-jit] time:     0.0 ms (+/- -nan %), matches:     4094
[       re2] time:   162.5 ms (+/- 14.6 %), matches:     4094
[      onig] time:    34.4 ms (+/- 20.3 %), matches:     4094
[       tre] time:   775.0 ms (+/-  1.1 %), matches:     4094
[     hscan] time:    46.9 ms (+/-  0.0 %), matches:     4094
[rust_regex] time:  2846.9 ms (+/-  1.5 %), matches:     4094
[     cpp11] time:   859.4 ms (+/-  0.0 %), matches:     4094
-----------------
Regex: 'Tom|Sawyer|Huckleberry|Finn'
[      pcre] time:    21.9 ms (+/- 39.1 %), matches:     2598
[  pcre-dfa] time:    21.9 ms (+/- 39.1 %), matches:     2598
[  pcre-jit] time:    21.9 ms (+/- 39.1 %), matches:     2598
[       re2] time:    40.6 ms (+/- 21.1 %), matches:     2598
[      onig] time:    37.5 ms (+/- 22.8 %), matches:     2598
[       tre] time:   487.5 ms (+/-  1.4 %), matches:     2598
[     hscan] time:     3.1 ms (+/- 223.6 %), matches:     2598
[rust_regex] time:    37.5 ms (+/- 22.8 %), matches:     2598
[     cpp11] time:   656.2 ms (+/-  4.8 %), matches:     2598
-----------------
Regex: '(?i)Tom|Sawyer|Huckleberry|Finn'
[      pcre] time:   268.8 ms (+/-  2.6 %), matches:     4152
[  pcre-dfa] time:   262.5 ms (+/-  2.7 %), matches:     4152
[  pcre-jit] time:    59.4 ms (+/- 11.8 %), matches:     4152
[       re2] time:   103.1 ms (+/-  8.3 %), matches:     4152
[      onig] time:   343.8 ms (+/-  0.0 %), matches:     4152
[       tre] time:   718.8 ms (+/-  0.0 %), matches:     4152
[     hscan] time:     3.1 ms (+/- 223.6 %), matches:     4152
[rust_regex] time:    40.6 ms (+/- 21.1 %), matches:     4152
[     cpp11] time:  2087.5 ms (+/-  1.6 %), matches:     4152
-----------------
Regex: '.{0,2}(Tom|Sawyer|Huckleberry|Finn)'
[      pcre] time:  3412.5 ms (+/-  0.4 %), matches:     2598
[  pcre-dfa] time:  2540.6 ms (+/-  2.0 %), matches:     2598
[  pcre-jit] time:   206.2 ms (+/-  3.4 %), matches:     2598
[       re2] time:    40.6 ms (+/- 21.1 %), matches:     2598
[      onig] time:    68.8 ms (+/- 12.4 %), matches:     2598
[       tre] time:  1500.0 ms (+/-  1.0 %), matches:     2598
[     hscan] time:     3.1 ms (+/- 223.6 %), matches:     2598
[rust_regex] time:    34.4 ms (+/- 20.3 %), matches:     2598
[     cpp11] time:  1862.5 ms (+/-  0.4 %), matches:     2598
-----------------
Regex: '.{2,4}(Tom|Sawyer|Huckleberry|Finn)'
[      pcre] time:  3496.9 ms (+/-  2.4 %), matches:     1976
[  pcre-dfa] time:  2903.1 ms (+/-  0.5 %), matches:     1976
[  pcre-jit] time:   218.8 ms (+/-  0.0 %), matches:     1976
[       re2] time:    37.5 ms (+/- 22.8 %), matches:     1976
[      onig] time:    65.6 ms (+/- 10.6 %), matches:     1976
[       tre] time:  2196.9 ms (+/-  0.4 %), matches:     1976
[     hscan] time:     3.1 ms (+/- 223.6 %), matches:     2598
[rust_regex] time:    31.2 ms (+/-  0.0 %), matches:     1976
[     cpp11] time:  2025.0 ms (+/-  2.1 %), matches:     1976
-----------------
Regex: 'Tom.{10,25}river|river.{10,25}Tom'
[      pcre] time:    53.1 ms (+/- 16.1 %), matches:        2
[  pcre-dfa] time:    62.5 ms (+/- 17.7 %), matches:        2
[  pcre-jit] time:    12.5 ms (+/- 55.9 %), matches:        2
[       re2] time:    43.8 ms (+/- 16.0 %), matches:        2
[      onig] time:    62.5 ms (+/- 17.7 %), matches:        2
[       tre] time:   378.1 ms (+/-  4.5 %), matches:        2
[     hscan] time:     3.1 ms (+/- 223.6 %), matches:        4
[rust_regex] time:    25.0 ms (+/- 34.2 %), matches:        2
[     cpp11] time:   403.1 ms (+/-  1.7 %), matches:        2
-----------------
Regex: '[a-zA-Z]+ing'
[      pcre] time:   793.8 ms (+/-  3.2 %), matches:    78424
[  pcre-dfa] time:  1143.8 ms (+/-  1.5 %), matches:    78424
[  pcre-jit] time:    65.6 ms (+/- 10.6 %), matches:    78424
[       re2] time:    96.9 ms (+/-  7.2 %), matches:    78424
[      onig] time:   625.0 ms (+/-  0.0 %), matches:    78424
[       tre] time:   387.5 ms (+/-  1.8 %), matches:    78424
[     hscan] time:    15.6 ms (+/-  0.0 %), matches:    78872
[rust_regex] time:    12.5 ms (+/- 55.9 %), matches:    78424
[     cpp11] time:   946.9 ms (+/-  0.9 %), matches:    78424
-----------------
Regex: '\s[a-zA-Z]{0,12}ing\s'
[      pcre] time:   331.2 ms (+/-  2.1 %), matches:    55248
[  pcre-dfa] time:   446.9 ms (+/-  1.9 %), matches:    55248
[  pcre-jit] time:    87.5 ms (+/-  9.8 %), matches:    55248
[       re2] time:    56.2 ms (+/- 15.2 %), matches:    55248
[      onig] time:    68.8 ms (+/- 12.4 %), matches:    55248
[       tre] time:   528.1 ms (+/-  1.3 %), matches:    55248
[     hscan] time:    15.6 ms (+/- 70.7 %), matches:    55640
[rust_regex] time:    40.6 ms (+/- 21.1 %), matches:    55248
[     cpp11] time:   612.5 ms (+/-  1.1 %), matches:    55248
-----------------
Regex: '([A-Za-z]awyer|[A-Za-z]inn)\s'
[      pcre] time:   737.5 ms (+/-  1.8 %), matches:      209
[  pcre-dfa] time:   809.4 ms (+/-  5.9 %), matches:      209
[  pcre-jit] time:    31.2 ms (+/-  0.0 %), matches:      209
[       re2] time:    84.4 ms (+/- 10.1 %), matches:      209
[      onig] time:   137.5 ms (+/-  9.5 %), matches:      209
[       tre] time:   612.5 ms (+/-  2.8 %), matches:      209
[     hscan] time:     3.1 ms (+/- 223.6 %), matches:      209
[rust_regex] time:    34.4 ms (+/- 20.3 %), matches:      209
[     cpp11] time:   634.4 ms (+/-  1.3 %), matches:      209
-----------------
Regex: '["'][^"']{0,30}[?!\.]["']'
[      pcre] time:    43.8 ms (+/- 16.0 %), matches:     8886
[  pcre-dfa] time:    62.5 ms (+/- 17.7 %), matches:     8886
[  pcre-jit] time:     3.1 ms (+/- 223.6 %), matches:     8886
[       re2] time:    50.0 ms (+/- 34.2 %), matches:     8886
[      onig] time:    59.4 ms (+/- 11.8 %), matches:     8886
[       tre] time:   296.9 ms (+/-  5.3 %), matches:     8886
[     hscan] time:    15.6 ms (+/-  0.0 %), matches:     8898
[rust_regex] time:     9.4 ms (+/- 91.3 %), matches:     8886
[     cpp11] time:   312.5 ms (+/-  0.0 %), matches:     8886
-----------------
Regex: '∞|✓'
[      pcre] time:     0.0 ms (+/- -nan %), matches:        2
[  pcre-dfa] time:    12.5 ms (+/- 55.9 %), matches:        2
[  pcre-jit] time:     0.0 ms (+/- -nan %), matches:        2
[       re2] time:     0.0 ms (+/- -nan %), matches:        2
[      onig] time:    28.1 ms (+/- 24.8 %), matches:        2
[       tre] time:   246.9 ms (+/-  5.3 %), matches:        2
[     hscan] time:     0.0 ms (+/- -nan %), matches:        2
[rust_regex] time:    40.6 ms (+/- 21.1 %), matches:        2
[     cpp11] time:   387.5 ms (+/-  3.4 %), matches:        2
-----------------
Regex: '\p{Sm}'
[      pcre] time:   331.2 ms (+/-  2.1 %), matches:       68
[  pcre-dfa] time:   465.6 ms (+/-  1.5 %), matches:       68
[  pcre-jit] time:    40.6 ms (+/- 21.1 %), matches:       68
[       re2] time:    34.4 ms (+/- 20.3 %), matches:       68
Onig compilation failed
TRE compilation failed with error 10
[     hscan] time:     0.0 ms (+/- -nan %), matches:       68
[rust_regex] time:    34.4 ms (+/- 20.3 %), matches:       69
C++11 compilation failed
-----------------
Total Results:
[      pcre] time:  10778.1 ms, score:     15 points,
[  pcre-dfa] time:  11431.2 ms, score:     16 points,
[  pcre-jit] time:    881.2 ms, score:     43 points,
[       re2] time:    990.6 ms, score:     30 points,
[      onig] time:   2246.9 ms, score:     19 points,
[       tre] time:   9668.8 ms, score:      0 points,
[     hscan] time:    243.8 ms, score:     69 points,
[rust_regex] time:   3396.9 ms, score:     54 points,
[     cpp11] time:  14846.9 ms, score:      0 points,
```

With regards to compatibility... until a few years ago (~2013), that was a real problem since GCC decided to claim that `std::regex` was "implemented" even though it was basically fully broken, and clang's release would segfault with certain inputs. The situation today is much, much better though.

AFAICT, the C++11's basic regex is a variant of ECMAScript ([ECMA-262](http://ecma-international.org/ecma-262/5.1/#sec-15.10)), with the differences documented here: http://en.cppreference.com/w/cpp/regex/ecmascript

Additionally, `grep`, `egrep`, `awk`, `basic`, and `extended` variants of the C++11 regex are available and can be specified at compile time.

**Comment by mqudsi** [comment]
(then again, who doesn't have pcre available?)

**Comment by krader1961** [comment]
I'm not especially worried about differences in performance unless it really is two orders of magnitude. The main problem is it isn't 100% compatible with PCREs. Although it looks like the ECMAscript grammar it implements is very close to being fully compatible with PCRE. Still, we could only do this in a major release. And I think the other items we want included in fish 3.0 are far more valuable than dropping our dependency on the PCRE lib. On the other hand the longer we go without making the switch the greater the risk of breaking existing uses.

So far I've been the only one working on the fish 3.0 wish list AFAIK. If others are going to step up and commit to, for example, replacing our dependency on `bc` then I'd be willing to see this added to the 3.0 wish list. But even then it should be the lowest priority change.

**Comment by faho** [comment]
>The end result is that C++11's regex performance is no rocket, but it's not that bad, either. As I expected beforehand, the results compared to dedicated standalone regex libraries are "sometimes better, sometimes worse, overall slower":

I actually don't agree with that characterization. The first result in particular is troubling - a factor of 85 _is_ bad.

I would expect with that difference it would make `string` noticeably worse, possibly to the point of making it worse than calling external tools for many of our uses.

Of course, the only way to know for sure is to actually implement it. I'd expect it would make the code simpler (and allow us to kill our embedded copy of pcre with fire), and it is possible it's not commonly bottlenecked in the actual regex matching (I'd expect one major point of slowdown is that string is only ever run once all the input is buffered, like all of our builtins), so it might still be worthwhile to do.

Plus, this would allow us to check the compatibility issue. Imagine we'd replace our regex dialect with the one used by grep - that'd be a major PITA since it would require changing anything that uses `()` groups or `$1` backreferences. By my count that's about 100 expressions in our code alone (and there's bound to be more differences).

So:

If anyone wants to try to implement this, we'll take a look at it and take it for a spin. But I don't want to merge anything that's a major performance regression or compatibility break.

**Comment by mqudsi** [comment]
Just to be clear, I'm not convinced we should switch just because I'm the one that opened the ticket :)

I would never use the native C++11 regex library if writing a product that needed regex to be fast (say, a grep replacement or the search feature in vim), but I would also never use the full-blown pcre library just to match text outside the critical path with relatively short inputs. I think like you say, @faho, really the only way to tell would be to give it at try. 

I may be wrong, but I highly doubt we'd have any problems from a performance perspective. I imagine the construction/compilation time for the regexes would probably overshadow any actual runtimes for the majority of our usecases, and that (and here I could be way off) the majority of them are restricted to inputs significantly shorter than Mark Twain's *The Adventures of Tom Sawyer*.

Honestly, my biggest reservation comes from the fact that I've been bit before by both clang and gcc's wholly bungled approach to implementing regex support, back in the day.

@krader1961 I'm not so sure this would need to be a major version release; I don't see why it can't be, e.g., 3.1 so long as it passes all the unit tests (and perhaps some additional ones especially focusing on regex) - unless we guarantee pcre compatibility for all regular expressions the user may run through the `string` builtin (among others)?

**Comment by krader1961** [comment]
> ... unless we guarantee pcre compatibility ...

From the `string` man page: "The dialect is that of PCRE2." Now, like some of the backward incompatible changes we snuck in the various 2.x releases, it might be okay to do this in a 3.x where x > 0 release. But only if someone can find a document that explains how the ECMAscript, and by extension the C++11 implementation, differs from PCRE2. And if we then decide such deviations are unlikely to be noticed by any fish users.

**Comment by mqudsi** [comment]
From http://www.pcre.org/pcre2.txt

       PCRE2_MATCH_UNSET_BACKREF

       If  this  option  is set, a back reference to an unset subpattern group
       matches an empty string (by default this causes  the  current  matching
       alternative  to  fail).   A  pattern such as (\1)(a) succeeds when this
       option is set (assuming it can find an "a" in the subject), whereas  it
       fails  by  default,  for  Perl compatibility. Setting this option makes
       PCRE2 behave more like ECMAscript (aka JavaScript).

and

       4.  The  following Perl escape sequences are not supported: \l, \u, \L,
       \U, and \N when followed by a character name or Unicode value.  (\N  on
       its own, matching a non-newline character, is supported.) In fact these
       are implemented by Perl's general string-handling and are not  part  of
       its  pattern matching engine. If any of these are encountered by PCRE2,
       an error is generated by default. However, if the PCRE2_ALT_BSUX option
       is set, \U and \u are interpreted as ECMAScript interprets them.

but I can't find more info than that. 

I think the best approach to seeing what would break would be for someone to try and compile the PCRE2 test suite with the C++11 regex engine and see what breaks.

**Comment by faho** [comment]
Honestly, it doesn't look like we want this.

If someone implemented it, we could take a look, and if it isn't as bad as it currently looks maybe even merge it, but it doesn't appear like it.

**Comment by Qix-** [comment]
Another :-1: - Apple's implementation of `std::regex` doesn't correctly handle EcmaScript backreferences.

**Comment by ridiculousfish** [comment]
:/ [I fixed that bug](https://reviews.llvm.org/D32635) but couldn't find a reviewer.

**Comment by mqudsi** [comment]
Such a small world!

**Comment by Qix-** [comment]
The unsung hero @ridiculousfish. Is the diff still good for latest head?

**Comment by ridiculousfish** [comment]
@Qix-  No idea, if I could identify a reviewer I would fix it up though.

**Comment by Qix-** [comment]
From oftc irc:

```
23:35 < LebedevRI> junon: normally a weekly "ping" comment on a review is ok
```

I added a ping to the reviewer that Herald auto-assigned. I'm surprised this hasn't been addressed by others given the popularity of Node.js and whatnot.

**Comment by jwakely** [comment]
@mqudsi ...

> that was a real problem since GCC decided to claim that std::regex was "implemented" even though it was basically fully broken

That's wrong, it was never claimed to be complete at that time. It was explicitly documented as not implemented: https://gcc.gnu.org/onlinedocs/gcc-4.8.5/libstdc++/manual/manual/status.html#status.iso.2011
