### ISSUE TITLE
fish_right_prompt sometimes triggers extraneous new line

### ISSUE THREAD

**Issue by thorstenkampe** [fish-shell/fish-shell#4306]
Fish 2.6.0

A newline appears in the prompt when using the native Windows terminal or ConEmu (see screenshot) in connection with `fish_right_prompt` (but not `fish_prompt`). It does not appear with the native Cygwin terminal emulator MinTTY. 

There were a few issues regarding `fish_prompt` and ConEmu but they seem to have been fixed. Is this a known issue?
![image](https://user-images.githubusercontent.com/475462/29155784-7181c39e-7d9e-11e7-843b-25a4ba7087f2.png)

**Comment by faho** [comment]
This is not just an issue with ConEmu, it also happens with VTE-based terminals (GNOME-Terminal etc). #4243 does not fix it.

I don't think we have another issue tracking it, so let's keep it here!

**Comment by faho** [comment]
@thorstenkampe: Can you test #4554?

**Comment by thorstenkampe** [comment]
Sorry, not sure how to do that. Check out your git branch and then compile it under Cygwin?

**Comment by faho** [comment]
>Check out your git branch and then compile it under Cygwin?

Yes. See our [instructions for building from source](https://github.com/fish-shell/fish-shell#building-from-source-1). I think that should just work under cygwin, but I'm not experienced with it.
