### ISSUE TITLE
Unable to open universal variable file on nfs 

### ISSUE THREAD

**Issue by PeterDaveHello** [fish-shell/fish-shell#4307]
Related with #3362 

 - fish version: v2.5.0
 - OS: FreeBSD 11.1-RELEASE amd64
(`FreeBSD home 11.1-RELEASE FreeBSD 11.1-RELEASE #0 r321309: Fri Jul 21 02:08:28 UTC 2017     root@releng2.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64`)
 - error message:
```
<E> fish: Unable to open universal variable file '/home/peter/.config/fish/fishd.home.test': No locks available
```
 - nfs mount info:
```
nfsv3,tcp,resvport,soft,intr,cto,lockd,sec=sys,acdirmin=3,acdirmax=60,acregmin=5,acregmax=60,nametimeo=60,negnametimeo=60,rsize=65536,wsize=65536,readdirsize=65536,readahead=1,wcommitsize=16777216,timeout=2,retrans=5
```

**Comment by zanchey** [comment]
This version works for me on a very similar setup (hard mount instead of soft mount, otherwise mount options are effectively the same, FreeBSD 11.0 instead of 11.1).

I would check that `rpc.statd` and `rpc.lockd` are running on the NFS server. One way of doing so is to run `rpcinfo -p SERVERNAME` and checking that there are entries for `nlockmgr` and `status`.

**Comment by PeterDaveHello** [comment]
Sorry for my late response, here is my rpcinfo, not sure if it's correct:
```
   program vers proto   port  service
    100000    4   tcp    111  rpcbind
    100000    3   tcp    111  rpcbind
    100000    2   tcp    111  rpcbind
    100000    4   udp    111  rpcbind
    100000    3   udp    111  rpcbind
    100000    2   udp    111  rpcbind
    100000    4 local    111  rpcbind
    100000    3 local    111  rpcbind
    100000    2 local    111  rpcbind
    100005    1   udp    961  mountd
    100005    3   udp    961  mountd
    100005    1   tcp    961  mountd
    100005    3   tcp    961  mountd
    100003    2   udp   2049  nfs
    100003    3   udp   2049  nfs
    100003    2   tcp   2049  nfs
    100003    3   tcp   2049  nfs
```

**Comment by zanchey** [comment]
@PeterDaveHello, it looks like the problem is that that your NFS client is set up to use NFS locking, but the server isn't set up to support it. Either remount your NFS share with `nolockd`, or ask the server administrator to start the lockd and statd daemons.
