### ISSUE TITLE
How to disable completions for a certain prefix without defining my own

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4310]
I'm trying to write a completion script for `s3cmd`, and I have the "providing suggestions" part down, but I can't figure out the right way to prevent fish from suggesting paths when it's not appropriate to do so.

This is what I have right now:

```fish
function __s3cmd_is_valid_remote_path
	commandline -ct | string match -r -- "^s3://.*?/.*"
end

function __s3cmd_is_remote_path
	commandline -ct | string match -r -- "^s3://[^/]*\$"
end

complete -c s3cmd -n "__s3cmd_is_valid_remote_path" -a "(s3cmd ls (commandline -ct) | tr -s ' ' | cut -d ' ' -f3)"
```

It works fine to suggest completions once `s3://BUCKETNAME/` has been entered, but not before `BUCKETNAME/` has been added to the `s3://` prefix. 

The problem is that `s3://<tab>` brings up the native path completions for the `/` directory, which is obviously neither correct nor wanted in this case.

The ideal behavior is

```
s3cmd f<TAB> #default completions for files starting with f
s3cmd s3://<TAB> #nothing
s3cmd s3://bucketname<TAB> #nothing
s3cmd s3://bucketname/<TAB> #completion script from above kicks in
```

How can I block the existing completions but only for that portion of the path, without disabling the native filesystem completions where they should be used?

**Comment by faho** [comment]
I'd expect a condition would do the trick:

```fish
complete -c s3cmd -f -n "__s3cmd_is_valid_remote_path; and string match 's3://*' -- (commandline -ct)" -a "(s3cmd [...])"
complete -c s3cmd -n "not string match 's3://*' -- (commandline -ct)"
```

**Comment by mqudsi** [comment]
@faho thanks for chiming in, but unless I'm missing something, that's adding additional checks to perform what the code in the original post already did? Namely, it calls `s3cmd` to propagate completions for `s3://bucketname/...` and doesn't for "regular" (non-`s3://` arguments) but it doesn't solve the outstanding issue: namely that fish still suggests completions after `s3://<TAB>` but before `s3://validbucketname/<TAB>`

**Comment by mqudsi** [comment]
However, your use of the `-f` parameter was the crucial point. I had tried to supply an empty `-a` or no arguments and a `-e` but didn't consider the `-f` flag. The rules in my original question combined with a simple `complete -c s3cmd -f -n "string not match 's3:/*' -- (commandline -ct)"` did the trick.

I'll submit a PR with the full completions soon.

Thanks for the help, @faho

**Comment by faho** [comment]
>thanks for chiming in, but unless I'm missing something, that's adding additional checks to perform what the code in the original post already did?

Oh, yeah, sorry. That second `complete` is unnecessary. You really just need to add a "-f" and make sure that your completions only kick in when there's an "s3://".

>"string not match 's3:/*' -- (commandline -ct)"

I'm assuming this is a typo - it's `not string match` (the `not` is a separate builtin).

**Comment by mqudsi** [comment]
Yes, it was. I actually just call the two functions without any not. If `remote_path` disable file completions, if `valid_remote_path` use `s3cmd` to generate completions.

Is there a way to append custom completions to autogenerated completions? Can I `source` the auto-generated completions file instead of copying its contents to my custom completion?

**Comment by faho** [comment]
>Is there a way to append custom completions to autogenerated completions? Can I source the auto-generated completions file instead of copying its contents to my custom completion?

Sure you can - it's a fish script.

However, for inclusion in fish, I'd request that the auto-generated completions are added to the script.

Also, while I have you here, @mqudsi, have you gotten your invitation to https://gitter.im/fish-shell yet?

Anyway, the question is answered, so I'm closing.

**Comment by mqudsi** [comment]
I did get the invite, though I didn't get a chance to log in and check it out. I'll do so now.

My question was indeed about for inclusion in fish; I had been sourcing the hard-coded path to the auto-generated completion locally.
