### ISSUE TITLE
Unexpected behavoir of 'or' statement after 'and begin' block

### ISSUE THREAD

**Issue by warptozero** [fish-shell/fish-shell#4311]
An `or` statement placed after an `and begin` block reacts to the exit status of the last command in the block instead of the command that conditionally executed the `and` statement as would be expected.

Fish version: 2.3.1
Fedora 26
No customizations other then vi_mode

The following code:
```
echo true
and begin
   echo and
   test -d asdfasdf
end
or echo or
```
Produces the following output:
```
$ ./begin_and_or 
true
and
or
```

**Comment by faho** [comment]
How would you expect this to work instead?

Here's what currently happens:

- Execute `echo true` - it succeeds, so $status is set to 0 (i.e. true)

- Check if $status is 0 for the `and` - it is, so enter the block

- Execute `echo and`, set status to 0

- Execute `test -d NONEXISTENTFILE`, which fails, so $status is set to 1

- Exit block, keep $status

- Check if $status != 0, which is true, so enter the `or`

- Execute `echo or`, set $status to 0

There is no associative property, no "first this, then that", this is just command-after-command.

Changing this would require either messing with how $status is propagated (which would break stuff in subtle and interesting ways), or messing with the grammar - currently `and` and `or` are, for the most part, conceptually just `commands` that could be replaced with functions doing stuff like `if test $status = 0; #execute block; end`.

Also, if you wish to do THINGA if a command succeeds and THINGB if not, do

```fish
if COMMAND
    THINGA
else
    THINGB
end
```

**Comment by warptozero** [comment]
Ah I see. I think I'm making the same conceptual mistake as #1648. I was actually trying to use multiple `and`/`or` combinations as shorthand replacement for `if; else; end`.

The idea I got from reading the docs was that everything executed in an `and` and `or` statement would not change the current exit status and that a `begin; end;` block would have it's own separate exit status variable because it has it's own variable scope.

**Comment by faho** [comment]
>I was actually trying to use multiple and/or combinations as shorthand replacement for if test $status = 0; else; end.

Honestly, don't.

Being explicit is good, and combining and/or can get hard to read quickly.

Fish doesn't try to enable the shortest scripts, the syntax is made to enable _readable_ scripts.

> a begin; end block would have it's own separate exit status variable because it has it's own variable scope.

Well... It has its own variable scope, but it's "non-shadowing". That means any variables already set will be used. Only variables that are newly defined in that block will be removed when the block returns.

E.g.

```fish
set -l fish salmon
begin
    set fish mackerel
    echo $fish # mackerel
end
echo $fish # mackerel
```

Either way it's moot, because $status is actually _global_. This makes a function without an explicit return return whatever its last command did. (which in turn makes aliases easier)

**Comment by warptozero** [comment]
Ah yes, that's clear. I think I started off with the right idea but the following line "`...` does not change the current exit status." must have set me on the wrong path. Maybe this can be expanded just a little.

> Honestly, don't.

I will better my ways. 🙌

Thanks for the great answers!

**Comment by faho** [comment]
>the following line "... does not change the current exit status." must have set me on the wrong path. Maybe this can be expanded just a little.

I tried to clarify this a bit in 4dbb274.
