### ISSUE TITLE
sudo completions: rm command not found

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4321]
I'm not sure what's going on here, but the first time I execute `sudo rm foo<TAB>` in a shell, I get the following:

```
mqudsi@ZBook ~/r/fish-shell> sudo rm ~/funcCommand 'rm' is available in '/bin/rm'
rm: command not found
/usr/local/share/fish/completions/rm.fish (line 2):
if rm --version >/dev/null ^/dev/null # GNU
   ^
from sourcing file /usr/local/share/fish/completions/rm.fish
        called on line 2 of file /usr/local/share/fish/functions/__fish_complete_subcommand.fish

in command substitution
        called on line 0 of file /usr/local/share/fish/functions/__fish_complete_subcommand.fish

in command substitution
        called on line 0 of file /usr/local/share/fish/functions/__fish_complete_subcommand.fish

in function '__fish_complete_subcommand'
        called on line 3 of file /usr/local/share/fish/functions/__fish_complete_subcommand_root.fish

in function '__fish_complete_subcommand_root'
        called on standard input
        with parameter list '-u -g'

in command substitution
        called on standard input
```

I'm not sure how `rm` can be not found. Obviously `/bin` is in `$PATH` for super users:

```
mqudsi@ZBook /m/c/U/Mahmoud> sudo env
HOME=/home/mqudsi
LANG=en_US.UTF-8
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
TERM=xterm-256color
MAIL=/var/mail/root
LOGNAME=root
USER=root
USERNAME=root
SHELL=/bin/bash
SUDO_COMMAND=/usr/bin/env
SUDO_USER=mqudsi
SUDO_UID=1000
SUDO_GID=1000
```

**Comment by faho** [comment]
`sudo` completions call `__fish_complete_subcommand_root`, which prepends /sbin and /usr/sbin to $PATH.

The exact call used is

```fish
    set -lx -p PATH /sbin /usr/sbin ^/dev/null
```

This fails, setting $PATH to just `/sbin /usr/sbin` instead.

It seems like this goes wrong because the existing $PATH is global, while the new one is local:

```fish
function prepend-foo
    set -lxp foo aaa
    echo $foo
end
set -g foo bbb
prepend-foo # prints aaa
echo $foo # prints bbb
```

@krader1961?

**Comment by krader1961** [comment]
Yes, that's a bug since the local scope flag in conjunction with the prepend flag is not supposed to affect finding the nearest copy of the var -- only the scope of the new copy. Good catch. I'll fix that and add the appropriate unit tests.

**Comment by krader1961** [comment]
I changed the mileston from 2.7.0 to 3.0.0 because the feature in question, `set --prepend` or `set --append`, only exists in our upcoming major release.

**Comment by krader1961** [comment]
The first unit test I added that appends to `var6` in a `begin..end` block failed with this output from `set --show var6`:

```
-$var6: set in local scope, unexported, with 1 elements
-$var6[1]: length=3 value=|mno|
-$var6: set in global scope, unexported, with 2 elements
-$var6[1]: length=3 value=|ghi|
-$var6[2]: length=3 value=|jkl|
-$var6: not set in universal scope
```

With the appropriate fix is shows this output:

```
-$var6: set in local scope, unexported, with 3 elements
-$var6[1]: length=3 value=|ghi|
-$var6[2]: length=3 value=|jkl|
-$var6[3]: length=3 value=|mno|
-$var6: set in global scope, unexported, with 2 elements
-$var6[1]: length=3 value=|ghi|
-$var6[2]: length=3 value=|jkl|
-$var6: not set in universal scope
```

Note that both test outputs are without the test output being updated which is why they both show unexpected output. However, the latter output correctly shows the local scope has been based on the global scope.
