### ISSUE TITLE
Completion pager navigation issues

### ISSUE THREAD

**Issue by laughedelic** [fish-shell/fish-shell#4331]
I noticed two problems (unexpected behavior) with the navigation (^P/^N while in the list of suggestions):

1. I can go through the list (with TAB or ^N) and after the last option I will return to the beginning, but it **doesn't work another way round**: if I'm on the first suggestion and press ^P, it will just remove the suggestion and that's it.

2. If there are 2 columns of suggestions and I go through them with TAB/^N, it will cycle on the second column (instead of returning to the first suggestion).

----

* Fish v2.6.0
* OS X El Capitan 10.11.6
* iTerm2 3.1.beta.5

I'll record an asciinema demo later.

**Comment by krader1961** [comment]
This has come up several times in the recent past that I can recall. There is at least one open issue describing the same issue, #3115, so closing as a dup of that.
