### ISSUE TITLE
Unable to locate data directory derived from $HOME

### ISSUE THREAD

**Issue by mdomin45** [fish-shell/fish-shell#4334]
The problem
-------------

When I enter the fish shell, I get a number of errors:
```
<E> fish: Your history will not be saved.
<E> fish: Unable to locate data directory derived from $HOME: '/Users/matthew/.local/share/fish'.
<E> fish: The error was 'Permission denied'.
<E> fish: Please set $HOME to a directory where you have write access.
```

Relevant information
---------------------

fish --version
`2.6.0`

uname -a
`Darwin mbp.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 23 18:25:34 PDT 2016; root:xnu-3248.60.10~1/RELEASE_X86_64 x86_64`

echo $TERM
`xterm-256color`

I've tried `sh -c 'env HOME=$(mktemp -d) fish'` and the problem does not persist when using this.

ls -ld $HOME
`drwxr-xr-x+ 59 matthew  staff  2006 Aug 16 01:03 /Users/matthew`

ls -ld $HOME/.config/
`drwx------  9 matthew  staff  306 Aug 10 21:42 /Users/matthew/.config/`

ls -ld $HOME/.config/fish/
`drwx------  4 matthew  staff  136 Aug 17 10:46 /Users/matthew/.config/fish/`

**Comment by krader1961** [comment]
Notice the path it complains about: */Users/matthew/.local/share/fish*. That's where fish stores data like the command history. The directory you checked for correct permissions is the fish config directory. What does `ls -ld $HOME/.local` and `ls -ld $HOME/.local/share` report?

**Comment by mdomin45** [comment]
ls -ld /Users/matthew/.local
`drwx------  4 root  staff  136 Jul 25 09:42 /Users/matthew/.local`

ls -ld /Users/matthew/.local/share
`ls: /Users/matthew/.local/share: Permission denied`
^^^ I'm assuming this is what is creating the problem ^^^

sudo ls -ld /Users/matthew/.local/share
`drwx------  4 root  staff  136 Jul 19 09:05 /Users/matthew/.local/share`

**Comment by krader1961** [comment]
> I'm assuming this is what is creating the problem

Yes, notice that the *~/.local* directory is owned by root and no other users can read/write/search it. You need to `sudo chown matthew /Users/matthew/.local`.

**Comment by mdomin45** [comment]
The problem persists after running  
`sudo chown matthew /Users/matthew/.local`
`sudo chown matthew /Users/matthew/.local/share`

I tried
`sudo chown matthew /Users/matthew/.local/share/fish`
but then `ls -ld /Users/matthew/.local/share/fish` still produces
`ls: /Users/matthew/.local/share/fish: Permission denied`

**Comment by krader1961** [comment]
You need to have read, write, and search (execute) permission as well as be the owner. For example, from my macOS server:

```
$ find ~/.local -type d | xargs ls -ld
drwxr-xr-x    3 krader staff   102 Oct 30  2015 /Users/krader/.local
drwxr-xr-x    3 krader staff   102 Jun  6  2016 /Users/krader/.local/share
drwxr-xr-x    8 krader staff   272 Aug 17 11:00 /Users/krader/.local/share/fish
drwxr-xr-x 1334 krader staff 45356 Aug 15 15:16 /Users/krader/.local/share/fish/generated_completions
```

In addition to the directories if the files within them are now owned by root you'll need to fix their ownership as well. Also, it's not likely but you might have also marked the directories and files as immutable (see `man chflags`). We're happy to help but I hope you understand this has nothing to do with fish.
