### ISSUE TITLE
RE: Remove all `forks` except when followed by `exec`

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4339]
_Opening this discussion here rather than via email or gitter so it is preserved for future reference and searchable via GitHub's issue search._

In order to finally put to rest the issues with state corruption when a process forks and there are active threads in a non-quiescent state, I was looking into eliminating all `fork` calls that are not more-or-less immediately followed by an `exec` of some sort, so that `fish`'s concurrency model is exclusively via threads and not via a mixture of threads and forks.

I was expecting to find a few `fork` calls littered in the codebase here and there, but I was actually surprised, it seems that the only `fork` calls are actually now contained to the `exec_job` function, where they are all (now) funneled into `do_fork` lambda. The only targets executed by the child process of the `fork` are `exec_write_and_exit`, `do_builtin_io`, and `safe_launch_process` (aka `exec`).

Additionally, `fish_tests.cpp` and `pcre2grep.c` also contain some usage of `fork`, but I'm not considering those here at all.

So far as I can tell, these are all very contained operations that do not do anything outside of a very specific boundary and do not interact in any way with the state of the rest of the program.

What I mean to say is that despite our recent discussions on the matter (see #4183, #4273, #2915) may have been in error, as it does not seem that fish (any more, at least) uses `fork()` in a manner that would cause any thread other than the main job control thread to be forked, and the resulting process does not interact with any sort of shared state. Or am I missing something?

**Comment by krader1961** [comment]
It may be, and almost certainly is, true that we only fork from the main thread and the child side does not need to interact with any state in the parent. However, the child still shares state with the parent. Specficially, you still have the problem of mutexes possibly being held by other threads when the fork occurs. Such as a thread holding a malloc mutex. This is why fish currently has functions like `debug_safe()`.

**Comment by mqudsi** [comment]
Yes, I guess what I was saying is that any fish-local mutexes (such as all the ones we use the fork_guards for) are actually protected. I don't believe we currently use new/malloc post-fork, so if we presume we're fine with that and it's not a problem to keep on going that way, is there anything else that can cause problems from the exec_job forks with regards to shared state and threads?

What I mean is, something like #2915 can't be related to forks in exec_job, can it?

**Comment by krader1961** [comment]
I am not convinced we cannot invoke new/malloc indirectly post-fork because we do a lot of work before invoking `execve()` (which appears to be the only `exec()` family of syscalls we use). Post `execve()` it looks like fish may be safe from doing anything that could block on a mutex held when the parent process forked. And, of course, it isn't just new/malloc we have to worry about it is also any stdio functions, etcetera. Note that I am only concerned here with libc/stdlib functions since we should not be using 3rd-party libraries which might cause problems relevant to this issue.

**Comment by mqudsi** [comment]
There's a very simple and reliable solution to all our fork woes, but for some reason I'm not feeling more than lukewarm about it: create a helper application (say, `fish-spawn`) which we `fork` and `execve` *immediately* thereafter, which takes command line arguments that indicate what course of action it will take.

I'm planning on replacing all forks for purposes of builtin IO with threads since they don't take advantage of process-unique features (such as pgrp or signals) which a) decreases the number of forks, b) speeds up fish. 

All what would be left is the code that is used to spawn child processes. If we move that to its own helper application, that could leave fish free of any code that operates in the limbo between `fork` and `exec`.

(another alternative is to switch to something like jemalloc which basically every open source project of substantial size now uses as their primary memory allocator to provide consistent, threadsafe memory allocations across all platforms. But I fell like that would be overkill.)

**Comment by mqudsi** [comment]
I think my questions regarding this have been answered. In summary: fish no longer uses forks for concurrency. All concurrency is via the thread model. Our use of fork is constrained to launching new processes, which could be done more safely. Synchronization issues in fish that involve mutexes, etc. such as #2915 are likely not caused by our use of `exec` (which means something else is wrong).

**Comment by ridiculousfish** [comment]
Yeah, the forks are hopefully contained. Replacing forks with threads for builtin IO sounds reasonable if we can do it in such a way that the synchronization is obviously fine, i.e. doesn't call into random fish global state like the variables. More generally I hope to switch to a model where we no longer use the C stack when awaiting processes, which will allow a powerful cooperative multitasking model (a la libuv), but that's a ways off. Go for it.
