### ISSUE TITLE
Brace expansion getting in the way in git stash apply

### ISSUE THREAD

**Issue by jamesgecko** [fish-shell/fish-shell#434]
The following git command breaks when I use it in fish.

In fish:

     [1] ><((ˣ> g stash apply stash@{3}
     fatal: ambiguous argument 'stash@3': unknown revision or path not in the working tree.
     Use '--' to separate paths from revisions

In bash:

     bash-3.2$ git stash apply stash@{3}
     # On branch working
     # Changes not staged for commit:
     #   (use "git add <file>..." to update what will be committed)
     #   (use "git checkout -- <file>..." to discard changes in working directory)
     #
     #	modified:   spec/data/stuff.dat
     #
     # Untracked files:
     #   (use "git add <file>..." to include in what will be committed)
     #
     #	routes
     no changes added to commit (use "git add" and/or "git commit -a")

**Comment by faho** [comment]
We now have tab completion that offers the properly escaped versions, so it should be easy to pick one and it should be clear that escaping is necessary. I believe this issue is fixed.
