### ISSUE TITLE
`git show` completion should support files, too

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4343]
Currently the completions for `git show` suppress file paths and only list commits as possible suggestions. `git show` completions should also include file paths since `git show local/path` can be used to see the history of changes to a file. (basically `git show` and `git log` should have the same completions *I think*, `git log` does both file and commit completions correctly).

**Comment by zanchey** [comment]
`git show` won't show files (so plain paths don't work, but it will work with blob selectors like `branch:path`. See [gitrevisions(7)](https://git-scm.com/docs/gitrevisions) for more examples.

**Comment by mqudsi** [comment]
@zanchey I'm not sure I understand:

```git
mqudsi@ZBook ~/r/fish-shell> git show src/complete.cpp
commit e76c1fd139d70c797344616c3e09b31ccc6b49d8
Author: Mahmoud Al-Qudsi <mqudsi@neosmart.net>
Date:   Fri Aug 18 14:26:35 2017 -0500

    Remove custom lock types in favor of native C++11 mutexes

    No longer using RAII wrappers around pthread_mutex_t and pthread_cond_t
    in favor of the C++11 std::mutex, std::recursive_mutex, and
    std::condition_variable data types.

diff --git a/src/complete.cpp b/src/complete.cpp
index f70dc20..d570c4c 100644
--- a/src/complete.cpp
+++ b/src/complete.cpp
@@ -178,7 +178,7 @@ static bool compare_completions_by_order(const completion_entry_t *p1,
 }

 /// The lock that guards the list of completion entries.
-static pthread_mutex_t completion_lock = PTHREAD_MUTEX_INITIALIZER;
+static std::mutex completion_lock;

 void completion_entry_t::add_option(const complete_entry_opt_t &opt) {
     ASSERT_IS_LOCKED(completion_lock);
@@ -1552,7 +1552,7 @@ wcstring complete_print() {
 }

 /// Completion "wrapper" support. The map goes from wrapping-command to wrapped-command-list.
-static pthread_mutex_t wrapper_lock = PTHREAD_MUTEX_INITIALIZER;
+static std::mutex wrapper_lock;
 typedef std::map<wcstring, wcstring_list_t> wrapper_map_t;
 static wrapper_map_t &wrap_map() {
     ASSERT_IS_LOCKED(wrapper_lock);
```

**Comment by zanchey** [comment]
Right, but that's only for files in your most recent commit, so it's not terribly useful. Compare `git show src/builtin_set.cpp` or `git show Dockerfile` for example.

**Comment by mqudsi** [comment]
My takeaway from this is that git's ui is an abomination.

**Comment by faho** [comment]
This isn't useful, so we shouldn't do it.
