### ISSUE TITLE
$FISH_VERSION versus $version

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#4351]
I would like to reopen an old discussion given that we are working on a major release that will contain backward incompatible changes. There was a lengthy, and rancorous, discussion in issue #3072 about the merits of supporting `$version` versus `$FISH_VERSION`. The `$version` variant was reintroduced as a side-effect of commit 90e535f66 that was ostensibly meant only to fix how fish handles coloring output.

See also, issue #374 where the introduction of `$FISH_VERSION` was discussed five years ago.

There are a couple of problems with the current situation. First and foremost is that `$version` can be modified whereas `$FISH_VERSION` cannot:

```
$ echo $version
set-local-scope/3.0.0b-217-g335f3972
$ echo $FISH_VERSION
set-local-scope/3.0.0b-217-g335f3972
$ set version WTF
$ echo $version
WTF
$ set FISH_VERSION WTF
set: Tried to change the read-only variable 'FISH_VERSION'
$ echo $FISH_VERSION
set-local-scope/3.0.0b-217-g335f3972
```

That should not be possible.

Second, neither bash, ksh, or zsh support `$version` as an alias for `$BASH_VERSION` or `$KSH_VERSION`, or `$ZSH_VERSION` respectively. I feel quite strongly that support for `$version` should be removed. If not then it should become a read-only variable, like `$FISH_VERSION`, that cannot be modified by the user.

**Comment by krader1961** [comment]
Also, `$FISH_VERSION` is documented in *doc_src/index.hdr.in* but AFAICT `$version` is not documented anywhere.

**Comment by floam** [comment]
`$FISH_VERSION` was a mistake to add, and it was a mistake to remove the `$version` electric variable. The commit referenced tried to ameliorate the compatibility situation caused by the original removal of `$version`. $FISH_VERSION is not exported, it should not be capitalized, it should just be $version. I'd love to see the original behavior restored. I feel pretty strongly about this.

**Comment by floam** [comment]
> Second, neither bash, ksh, or zsh support $version as an alias for $BASH_VERSION or $KSH_VERSION

See csh.

**Comment by faho** [comment]
>$FISH_VERSION was a mistake to add, and it was a mistake to remove the $version electric variable. 

I disagree.

>$FISH_VERSION is not exported, it should not be capitalized, it should just be $version. 

$FISH_VERSION is consistent with how other shells do it, which makes it more discoverable. Note that bash and zsh are used probably orders of magnitude more than csh (AFAIK, FreeBSD defaults to tcsh, OpenBSD defaults to ksh, basically everything else defaults to bash).

It's also been documented for longer.

$FISH_VERSION is unambiguous, $version is _not_.

> I'd love to see the original behavior restored. I feel pretty strongly about this.

Do we really want to flip-flop on this?

-------

Honestly, if we can't convince @floam, I'm okay with keeping the status quo - I _don't_ feel strongly about this. I do prefer $FISH_VERSION, though.

**Comment by krader1961** [comment]
> $FISH_VERSION is not exported, it should not be capitalized, it should just be $version. 

Tell that to ksh, bash, zsh.

> See csh.

Frankly, the "csh has it" argument is not compelling. Let me know how successful you are convincing the bash and zsh teams to add `$version` with that argument.

Csh has quite a few features that no sane shell would adopt today. My team used it for a few years in the late 1980's as our interactive shell only because the only alternative was the Bourne shell. We did 100% of our scripting with /bin/sh. Even then it was recognized that using csh for scripting was a bad idea. When the Korn shell became available we switched to that for both interactive use and scripting.

> Do we really want to flip-flop on this?

No, but I'm unhappy that `$version` was snuck in via an unrelated change when it was clear just one person wanted it reinstated; then and now. If we're going to keep the `$version` variant it a) needs to be documented, and b) made a read-only variable like `$FISH_VERSION`.

**Comment by floam** [comment]
@zanchey, any thoughts?

**Comment by zanchey** [comment]
`version` and `FISH_VERSION` are both crappy names in their own way, but `FISH_VERSION` is less bad. This is bikeshed territory but I think the status quo is reasonable; certainly it does not appear to have tripped anyone up yet.

(At least this isn't cache invalidation.)

**Comment by krader1961** [comment]
> This is bikeshed territory but I think the status quo is reasonable...

I have no objection to the status quo; i.e., keeping both variables. The problem is that a) we don't document that `$version` is a valid way to interrogate the version and b) it isn't a read-only variable like `$FISH_VERSION` which means that it can be changed. If we're going to retain the `$version` variant it should be documented and made read-only like `$FISH_VERSION`. There is no good argument I can think of why it should remain undocumented and behave differently. On the other hand I don't see a good reason to usurp another variable name likely to be used by user scripts since doing so doesn't add any value. If we were talking about another 2.x release I wouldn't bother raising the issue. But a major release is the right time to decide one way or the other. Remove it or document it.

**Comment by krader1961** [comment]
Also, I just noticed that on macOS `csh` is actually `tcsh`. And in that case the `$version` variable is rather verbose whereas `$tcsh` is what fish users would expect:

```
% echo $version
tcsh 6.18.01 (Astron) 2012-02-14 (x86_64-apple-darwin) options wide,nls,dl,bye,al,kan,sm,rh,color,filec
% echo $tcsh
6.18.01
```

Both can be overridden and are thus unreliable.

Whereas on Ubuntu 16.10 csh does not understand the `$version` variable:

```
% echo $version
version: Undefined variable.
```

But tcsh does:

```
% echo $version
tcsh 6.18.01 (Astron) 2012-02-14 (x86_64-unknown-linux) options wide,nls,dl,al,kan,sm,rh,nd,color,filec
% echo $tcsh
6.18.01
```

So it appears that our `$version` is really meant to mimic the tcsh `$tcsh` variable. Not the csh `$version` variable since that doesn't have a predefined meaning. And not even the tcsh `$version` variable. Given all of that I don't understand why our current, undocumented, `$version` variable can be justified on the basis of compatibility with csh.

**Comment by krader1961** [comment]
See also this stackoverflow question which also highlights the fact that csh (but not tcsh) does not have any way to interrogate its version: https://stackoverflow.com/questions/14259723/how-can-i-determine-my-csh-version. So I am still confused why the "csh provides $version" argument is compelling. Even if we're conceding that "csh" is an alias for "tcsh".

**Comment by floam** [comment]
Whoops, I accidentally deleted a comment here. Uh, sorry.

**Comment by floam** [comment]
fb8ae04f80c3a129f789e7b718464d014508315f intended to settle this.

**Comment by shofel** [comment]
Hey there!

I've got a helper script to calculate a new version for the release of my application based on a list of git tags. And the variable is occasionally named `version`. The script is broken after upgrading the fish from `2.7.x` to `3.0.2`.
``` sh
$ set version 1                                                                   
set: Tried to change the read-only variable “version” 
```

Is there any conventions to choose variable names in fish such a way to not clash with the read-only ones? I've tried to find the answer to this question but haven't succeeded.

I was surprised that the name `version` is somehow a special name that I can't use. I don't see anything special about this word.

To wrap up: I'm just giving a feedback that this experience was not intuitive nor logical for me.

**Comment by floam** [comment]
Prior to fish 2.7.x, you would also have the same issue. It just so happened that 2.7 had a last minute change that made `$version` a regular global variable set in a fish script because of the temporary rename to `$FISH_VERSION`. But it still included the fish version number.

The docs list the special variables, and there are not likely to be a huge number of new ones in the future. But a convention that will ensure you never have a conflict would be to do something like `$shofel_version`. We don't have any name-spacing. Sorry for the inconvenience.

**Comment by faho** [comment]
>The docs list the special variables, and there are not likely to be a huge number of new ones in the future

And even if we do add new ones, they won't have names like this. $version is an awful name, but we're stuck with it since it goes back to the very first fish version, and since its sole purpose is to provide the version, it _needs_ to stay stable so you can react to it.

If we do add new special variables, they'll be like $fish_emoji_width - a name that makes it clear it's ours.

**Comment by floam** [comment]
>If we do add new special variables, they'll be like $fish_emoji_width - a name that makes it clear it's ours.

Not necessarily true, a `$fish_` prefix for something that is a really core piece of shell functionality, a real part of our language, on par with status or history, should not have a prefix like that configuration variable does.

Like, we just added `$pipestatus`. Anybody using that name in their scripts is just out of luck, and that's okay.

**Comment by faho** [comment]
>a $fish_ prefix for something that is a really core piece of shell functionality, a real part of our language, on par with status or history, should be considered a mistake

Sure. But that doesn't happen often.

**Comment by floam** [comment]
Should we consider allowing some of these to not be read-only, perhaps shadowing allowed limited to local scope only?

**Comment by faho** [comment]
>Should we consider allowing some of these to not be read-only

Nooooooooooooo.... we've been down that road, and you've _just_ said:

>and it was not wise to overwrite it.

These are API, you should count on them being there, and you don't need variable names urgently enough that you should opt out of API.
