### ISSUE TITLE
`echo $history[1]` returns entire fish history as a single string

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#4353]
```
$ fish --version
fish, version 2.6.0-544-gc95b9f06
```

[As discussed on Gitter](https://gitter.im/fish-shell/fish-shell?at=599d7890614889d4757b03ba), `echo $history[1]` returns my entire fish history, while `echo $history[2]` is empty.

**Comment by krader1961** [comment]
You can cherry pick commit b69df4fe72 from https://github.com/krader1961/fish to fix this.

**Comment by zx8** [comment]
Thanks @krader1961!

Out of curiosity, why are you opting to not raise an upstream PR in this instance?

**Comment by mqudsi** [comment]
I've taken the liberty of cherry-picking said commit into master. Thanks for the fix, @krader1961.
