### ISSUE TITLE
`history` searches should support writing results oldest to newest

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#4354]
The `history` command in bash, csh, and ksh all write the search results in oldest to newest order. Fish writes the results in newest to oldest order. I prefer the order of the other shells because it's easier to read from the bottom up when looking at the sequence of commands. We can't change the default but it would be nice if there was an option added to select the reverse order for consistency with other shells.

**Comment by krader1961** [comment]
As happens all too often there was a lot of discussion in the pull-request that really belongs in this issue. That's because the discussion was not about the code. It was about the reason for the change. What follows are some of the questions and my responses raised in the PR.

@floam said:

> Couldn't someone avoiding the fish history pager just as easily abbr/alias in a tac or (bsd) tail -r command to reverse the output as they could do such to prefer this reversed mode? Is there sufficient need to offer a reversed output mode specifically on this builtin?

To which @faho replied:

> That's a philosophical argument, and it's not invalid.

> ... and apparently BSD-ish systems don't have tac - I'd prefer if we offered one way that worked everywhere.

And my response to the above:

Correct, macOS for example, does not have tac. And tail -r is problematic because there is no way to unambiguously say you want every single line. You have to instead provide an absurdly large -n value. Too, people who want the output sorted oldest to newest (like every other shell does) shouldn't have to pay a performance penalty to get it.

Also, tac and tail -r mangle multiline commands. There isn't any sensible way to do this by piping the output of history through another command even if the performance penalty was acceptable.

Also, regarding the default history function behavior of piping the output through a pager. That has it's own problems. Most notably if your pager uses the alt-screen feature when you exit the pager the contents are no longer visible. I long ago configured less to not do that but that is something the average user won't bother with. Especially since doing so requires using less's --no-init flag or creating custom terminfo definitions.

It is also very rare that I want to see more than the most recent 10 to 20 commands. Which is why I use an alias named h that calls builtin history -n20.... If I want more results I only need to invoke it with a larger limit and can append |less. Which, because I have run abbr l less, means I only need to type two more characters. And scrolling to the bottom requires just typing G. So while I can appreciate that the default behavior is friendly to typical users it isn't friendly to a power user. This change simply makes it possible for power users to get behavior that is better suited to their needs.

Whenever the choice is between being friendly to average users or power users we should always favor the former. But that doesn't mean we can't or shouldn't provide ways to meet the needs of power users if doing so can be done without making fish less friendly for the average user.

**Comment by floam** [comment]
I'm convinced, I hadn't thought it through very well in my original comment - `tac`/`less` would not be a good solution for the reasons offered, this seems like a nice feature to add.
