### ISSUE TITLE
Command substitution

### ISSUE THREAD

**Issue by hamon-e** [fish-shell/fish-shell#4362]
What's the equivalent for <code>"$(command)"</code> in fish ?

It pass the result of the command in only one argument without spliting

**Comment by ridiculousfish** [comment]
Unfortunately nothing so convenient - it's a known and acknowledged hole.

Often though it's unnecessary, since fish splits on newlines and not arbitrary whitespace. What's your use case?

**Comment by hamon-e** [comment]
Nothing atm but I was asking cause i had to do this in the past

**Comment by zanchey** [comment]
I think this is a duplicate of #159 (!)
