### ISSUE TITLE
The `history` var is extremely expensive and should be replaced by a `history item` command

### ISSUE THREAD

**Issue by krader1961** [fish-shell/fish-shell#4366]
When I fixed issue #4353 it got me thinking about the cost of that var. On my main computer my history has 29,579 entries. Typing `set -g` takes a minimum of 170 ms (best of five runs). If I build fish with a one line change to exclude `history` from that output the run time drops to 2 ms. The following two functions makes the difference even more stark:

```
function histcopy
    set -l histcopy $history
    for i in (seq 1000)
        echo $i: $histcopy[$i]
    end
end
function hist
    for i in (seq 1000)
        echo $i: $history[$i]
    end
end
```

Then I ran this sequence several times:

```
histcopy
echo $CMD_DURATION
hist
echo $CMD_DURATION
```

Iterating over the copy takes 30 seconds and iterating over `$history` takes 190 seconds. Which means that ignoring all the common overhead expanding `$history[$i]` takes ~160 ms longer than expanding `$histcopy[$i]`.

A third way to show the overhead is this:

```
set -g histcopy $history
set --show histcopy
echo $CMD_DURATION
set --show history
echo $CMD_DURATION
```

The `history` var also does not expose when the job was run or anything else we might save about the job, now or in the future. A better interface would be modeled on `functions --details $funcname`. I propose `history item $i`. Or possibly `history entry $i` though I prefer `item`. This would allow us to expose everthing we currently save with each history entry and can be safely extended in the future if we save more data about the job (e.g., the CWD when the job was run).

Because of the backward incompatible nature of this change, and the trivialness of implementing it, this is a good candidate for fish 3.0.

**Comment by krader1961** [comment]
Note that fish 2.x is approximately 30 ms slower (20%) at expanding `$history` because it first constructs the history as a flat string then converts it to a vector. The improvement I did for fish 3.0 to always store fish vars as vectors internally avoids that extra representation conversion step.

**Comment by krader1961** [comment]
The `history count` command I just implemented does the same thing as the above functions in 1719 ms using this function and redirecting its output to /dev/null:

```
function hist2
    for i in (seq 1000)
        echo $i: (builtin history item $i)[1]
    end
end
```

That's 94.3% faster than the `histcopy` function and 99.1% faster than the `hist` function above.

**Comment by floam** [comment]
Per discussion in #4404, we don't dig the idea of killing `$history` to make it faster. Closed.

**Comment by alphapapa** [comment]
@floam I don't see any discussion in #4404 about this change.

1.7 seconds vs. 190 seconds is a huge performance improvement.  And as Kurtis said, it would allow metadata about each history entry to be accessed.

Maybe there are good reasons to not go this route, but it doesn't seem to have been discussed here.  It would be a shame to throw away this feature without seriously considering it.

**Comment by floam** [comment]
Wrong number, sorry. #4461

**Comment by alphapapa** [comment]
Thanks.
