### ISSUE TITLE
fish_update_completions: math: Invalid expression: Unexpected token ";48279/1000 " found at position 7.

### ISSUE THREAD

**Issue by timofonic** [fish-shell/fish-shell#4373]
!  ~  fish --version                         Fri 01 Sep 2017 06:26:57 PM CEST
fish, version 2.6.0-566-gc8cf8a66

  ~  echo $version                              Fri 01 Sep 2017 06:27:56 PM CEST
2.6.0-566-gc8cf8a66

Linux xxxxxxx 4.13.0-1035f22af3e97 #1 SMP PREEMPT Fri Sep 1 06:05:09 CEST 2017 x86_64 GNU/Linux

 ~  lsb_release --all
LSB Version:    1.4
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a

 ~  echo $TERM                             s  Fri 01 Sep 2017 06:32:01 PM CEST
xterm-256color

(but I'm using Terminology)
 ~  terminology --version                      Fri 01 Sep 2017 06:32:03 PM CEST
Version: 1.0.99

##How to reproduce it
 ~  fish_update_completions           1211ms  Fri 01 Sep 2017 04:55:06 PM CEST
Parsing man pages and writing completions to /home/timofonic/.local/share/fish/g
enerated_completions/
  4944 / 4944 : zramctl.8.gz
math: Invalid expression: Unexpected token ";48279/1000 " found at position 7.

 ~  sh -c 'env HOME=$(mktemp -d) fish'         Fri 01 Sep 2017 06:30:10 PM CEST
Welcome to fish, the friendly interactive shell
timofonic@xxxxx /h/timofonic> fish_update_completions
Parsing man pages and writing completions to /tmp/tmp.CxPB3IHSBg/.local/share/fish/generated_completions/
  4944 / 4944 : zramctl.8.gz
timofonic@xxxxxxx /h/timofonic> exit
math: Invalid expression: Unexpected token ";33857/1000 " found at position 7.

**Comment by krader1961** [comment]
Note that `bc` treats `;13272/1000` as a valid expression but the new MuParser based implementation does not. Note that the first failure happens after typing `exit` and the second does not. Which suggests that  lies in your `fish_prompt` or a function it calls. There is no place in the stock fish code that calls `math` with a divisor of `1000` AFAICT. That looks suspiciously like something in your prompt trying to convert `$CMD_DURATION` from milliseconds to seconds and, for some inexplicable reason, prefacing the expression with a semicolon.

**Comment by krader1961** [comment]
I'll bet, @timofonic, you're using theme-bobthefish/fish_right_prompt.fish. Which should just call `bc` directly rather than our `math` wrapper because it does the following. Note how it directly sets the scale rather than using the `--scale` flag. It also has a bug. The `string replace -r '\\.0$' ''` will only work with `scale=1`. For the calculation with `scale=2` the `string replace` will never match.

```
function __bobthefish_cmd_duration -S -d 'Show command duration'
  [ "$theme_display_cmd_duration" = "no" ]; and return
  [ -z "$CMD_DURATION" -o "$CMD_DURATION" -lt 100 ]; and return

  if [ "$CMD_DURATION" -lt 5000 ]
    echo -ns $CMD_DURATION 'ms'
  else if [ "$CMD_DURATION" -lt 60000 ]
    math "scale=1;$CMD_DURATION/1000" | string replace -r '\\.0$' ''
    echo -n 's'
  else if [ "$CMD_DURATION" -lt 3600000 ]
    set_color $fish_color_error
    math "scale=1;$CMD_DURATION/60000" | string replace -r '\\.0$' ''
    echo -n 'm'
  else
    set_color $fish_color_error
    math "scale=2;$CMD_DURATION/3600000" | string replace -r '\\.0$' ''
    echo -n 'h'
  end

  set_color $fish_color_normal
  set_color $fish_color_autosuggestion

  [ "$theme_display_date" = "no" ]
    or echo -ns ' ' $__bobthefish_left_arrow_glyph
end
```

Whether fish should try to detect this and mutate the expression is debatable.

**Comment by HcsOmot** [comment]
I had the same problem. Running 
```
omf update
```
solved the problem, as it was, indeed, Bob's fault.

```
tomo@omot  ~  
 omf update                                                                                    Pon 09:16
Oh My Fish is up to date.
You are now using Oh My Fish version 5.
z successfully updated.
batman is already up-to-date.
bobthefish successfully updated.
default is already up-to-date.
fishbone is already up-to-date.
```

```
 N  tomo@omot  ~  
 fish_update_completions                                                                9,5s  Pon 09:19
Parsing man pages and writing completions to /home/tomo/.local/share/fish/generated_completions/
3165 / 3165 : zramctl.8.gz                             
 N  tomo@omot  ~  
                                                                                       22,5s  Pon 09:23
```

**Comment by timofonic** [comment]
I orgot to read this. Sorry. I'll update...
