### ISSUE TITLE
COLUMNS gets out of sync when resizing

### ISSUE THREAD

**Issue by soumya92** [fish-shell/fish-shell#4381]
`fish --version`:
```
fish, version 2.6.0
```

`uname -a`:
```
Linux ada 4.9.0-3-amd64 #1 SMP Debian 4.9.30-2+deb9u3 (2017-08-06) x86_64 GNU/Linux
```

`echo $TERM`:
```
xterm-256color
```

`tilix --version`:
```
Versions
	Tilix version: 1.6.4
	VTE version: 0.46
	GTK Version: 3.22.11

Tilix Special Features
	Notifications enabled=0
	Triggers enabled=0
	Badges enabled=0
```

On each resize, `$COLUMNS` contains the previous size, while `tput cols` outputs the current size.
Occurs without any customisations.

https://asciinema.org/a/InhKQPwcKK814m8UlkTn83s36

I used `function fish_prompt; echo "t:"(tput cols)" c:$COLUMNS>"; end`, and resized the terminal program. In my case, the resizing was achieved by opening and closing new "panes" within Tilix, but the same behaviour can be observed with a tiling WM and opening a new window, or even quickly resizing a freeform window. (Although on a freeform window, the difference is less noticeable because it only trails by 1)

**Comment by krader1961** [comment]
This is a consequence of SIGWINCH only invalidating the currently cached terminal size. It doesn't actually cause fish to immediately query the new size. This can race with other fish actions which do result, as a side-effect, in querying the terminal size. This code is like the job control (and tty process group management) code in that it needs an overhaul to simplify it and make it more robust.

**Comment by soumya92** [comment]
Interesting. Not a big deal for me because I can just use (tput cols) instead of $COLUMNS, and it doesn't sound like an easy fix, so I'll leave it up to you whether you want to close it, put it in fish-future, or do something else.

Thanks for taking a look!
