### ISSUE TITLE
Builtin string match error message typo when using --entire and --index

### ISSUE THREAD

**Issue by externl** [fish-shell/fish-shell#4386]
This affects master branch and at least `v2.6`. I didn't check back any further.

Running `string match --index --entire $pattern $some_string` results in the following error message:

```
$ string match --index --entire $pattern $some_string
match: Invalid combination of options,
--enter and --index are mutually exclusive
```

`--enter` should be `--entire`

See: https://github.com/fish-shell/fish-shell/blob/master/src/builtin_string.cpp#L903

**Comment by faho** [comment]
Nice catch, fixed!
