### ISSUE TITLE
Doxygen swaps quotes in man page output

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#4389]
- fish master/Integration 2.7.0

- doxygen 1.8.13

In our `test` man page, there's an example that looks like 

```fish
if test -n '$MANPATH'
```

in the man output. It should be 

```fish
if test -n "$MANPATH"
```

like it is in the source.

It's unclear if this happens anywhere else.

Also see #4016. Only in this case it's not just cosmetics, but actual _meaning_.

**Comment by krader1961** [comment]
Any reason not to mark this a duplicate of #4016 and change the subject of that issue to something like "Doxygen produces invalid man pages from fish documentation"?

**Comment by mqudsi** [comment]
If the resulting documentation comes out wrong, then this really should be fixed for 2.7.0, no?

**Comment by faho** [comment]
@mqudsi: If we could, we'd release the perfect shell as 2.7.0. It'd even make pancakes. 

But since we're 5 weeks past the initial date set for the 2.7.0 release and we AFAIK don't know what causes this, it should not hold up the release any longer - we really should start to stop working on it and release it instead.

Anyway, yeah, this should have been marked as a duplicate, so I'm closing it.
