### ISSUE TITLE
Host completion ignores SSH hosts with custom ports

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#4392]
In #1355, @Pyppe points out that fbd53f2da lost the improvements from #1380 where `__fish_print_hostnames` picks up SSH configurations which specify hostnames with custom ports.

**Comment by faho** [comment]
@zanchey: #4378 was meant to fix that. Can you confirm that it is broken even with that?

**Comment by zanchey** [comment]
Right, of course - mea culpa.

**Comment by faho** [comment]
@zanchey: I think you forgot to close this?
