### ISSUE TITLE
Bare variables in `math` are accepted

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#4393]
95162ef19d11c reverted 56d91345343a89 to remove the LRU for math expressions, but the commit contained more than the commit message suggested. I fixed the documentation changes in 91a0ba9be5ec. However, bare variable names in `math` are broken:

```fish
> set -l one 1
> set -l two 2
> math $one + $two
3
> math one + two
0
```

Note that these do not work in fish 2.x, so I'm not certain that we want to keep them - if not, we need to revert bd18736ee55.

**Comment by krader1961** [comment]
Works for me. Are you sure you don't have the legacy `math` function installed? Note that it silently converts anything not a valid int to zero:

```
$ set x 1
$ set y 2
$ echo 'x + y' | bc
0
$ builtin math x + y
3
```

Note that the new builtin math does the same thing using the following block of code. Whether or not that's the right thing to do is debatable.

```
    auto var = env_get(var_name, ENV_DEFAULT);
    if (!var) {
        // We could report an error but we normally don't treat missing vars as a fatal error.
        // throw mu::ParserError(L"Var '%ls' does not exist.");
        return &zero_result;
    }
    if (var->empty()) {
        return &zero_result;
    }
```

**Comment by ridiculousfish** [comment]
I didn't follow the `math` development but I'm very surprised that `math one + two` is expected to work. In general only commands that manipulate variable values (`set`, `read`, etc.) should be able to work with bare variable names. I'll take a look at bd18736ee55e28651db0bb2b9c9630e8a57ec200 - thanks for noticing zanchey

**Comment by ridiculousfish** [comment]
I reverted bd18736ee55e28651db0bb2b9c9630e8a57ec200 as a5fd0b317ed7f7eccc9b9621065e1d0345d31a55 . Closing, thanks.

**Comment by zanchey** [comment]
@krader1961, you were right about having the old math function - sorry for the noise.

**Comment by floam** [comment]
The reverted commit does not actually kill bare variables, as I think it may have intended to, it just removed the uses of it in our scripts.

```fish
$ set a 5
$ math 'a*3'
15
```

**Comment by zanchey** [comment]
Yes, I forgot about this - I think reverting c95b9f06e1d81e34a91c47381e114d2e7d095345 will do.

**Comment by ridiculousfish** [comment]
I removed this for real. I surveyed our math use in functions and completions and didn't find any bare-variable uses, though of course it's still possible it's being used in omf or elsewhere.
