### ISSUE TITLE
Remove caret (^) as redirector for stderr

### ISSUE THREAD

**Issue by ThomasAH** [fish-shell/fish-shell#4394]
I propose removing the caret (^) as a redirector for stderr in fish 3.0.

**Reason 1:** This is surprising for users of other shells and may lead to data loss

There are many commands using the caret on the command line for special purposes, e.g. git (see #1873). While some special handling has been introduced to reduce the need for quoting (see Reason 2), this does not help in all cases, e.g. `git log ^refA refB` will create a file `refA` containing the error message of git.
Many other programs use ^, too, for me the most notable problem is grep.
I often use the command `dpkg -l|grep -v ^ii` to check for problems with not fully installed or purged Debian packages. In fish this prints nothing, and grep's error message is sent to the new file `ii`.
Or I use `ps auxww|grep ^theuser` to quickly find processes of some users.
Or `grep ^http someconfigfile` to see if the config file contains a setting about httpserver or httpproxy or ...

While this often just results in a stray file (which is already bad enough), this can easily overwrite existing files, because sometimes I am looking for something where a file of the same name exists, e.g. Makefile targets (which luckily can often be rebuilt), or filtered output of `ls`, e.g. `ls | grep -v ^README` to show me everything but README (which is now overwritten) and various README.foo files. Or `ls | grep -v ^access.log | grep -v ^error.log` to hide the current and rotated web server log files and see what other files are present. Yes, I could add quotes and I should add a backslash in front of the dot in the regexp, but I really don't expect a file `accessblog` here, so I don't do it in interactive use.

**Reason 2:** Workarounds have been introduced, but they introduce even more surprising behavior.

To workaround the problem in git (#1873), the handling of ^ was changed to be different than the handling of >, so `echo foo^bar` prints `foo^bar`, but `echo foo ^ bar` prints `foo` and creates an empty file `bar`. This is different from e.g. `echo foo>bar` and `echo foo > bar` which both do the same thing.

The need for this workaround indicates that using the caret as a redirection character is problematic.

**Reason 3:**  The law of orthogonality (https://fishshell.com/docs/current/design.html#ortho)

`^` is just a shortcut for `2>`, so this syntax saves only a single character.
The user still has to know the difference between stdout and stderr to use this feature.
The user still has to know about file descriptors to redirect both, stdout and stderr, to the same file with `echo Hello > all_output.txt ^&1`.

**Comment by mqudsi** [comment]
I would be on board with this. It's just not a feature worth having.

**Comment by ridiculousfish** [comment]
I like this too.

**Comment by zx8** [comment]
Wow, I thought I was the only one who considered this a misfeature! I'm very for this as well.

**Comment by krader1961** [comment]
FWIW, I agree this "feature" should be removed. But note that it doesn't affect just `^/a/path` to redirect stderr to */a/path*. It also affects `^| a_command`. We have two such uses of the latter in the fish project: *share/completions/apm.fish* and *share/functions/__fish_print_make_targets.fish*. That there are only two such instances in the fish code suggests that use case is relatively rare. Nonetheless it is another use of the feature which will be broken if we implement this change.

**Comment by ThomasAH** [comment]
`^|` is nice for some situations, but there are already some alternative ways to do this:

`if apm -h ^| string match -q "*Atom Package Manager*"`
can be changed to
`if apm -h 2>&1 | string match -q "*Atom Package Manager*"`

`make -C $directory -d g1 -rn >/dev/null ^| awk ...`
can be changed to
`make -C $directory -d g1 -rn 2>&1 >/dev/null | awk ...`

If some really needs to print stdout and just wants to pipe/filter stderr, both can be swapped, e.g.:
```
ls -ld /etc /missing /invalid 3>&2 2>&1 1>&3 | grep miss
drwxr-xr-x 196 root root 12288 Sep 12 15:54 /etc
ls: cannot access /missing: No such file or directory
```

If above syntax is considered too complicated, the behaviour of `|` could be adjusted to match the behaviour of `>` by allowing file descriptors, so `2|` would pipe stderr. This is more consistent, allows piping of other file descriptors, and accidents are far less likely to cause data loss, because e.g. `grep foo 2|grep bar` will not clobber existing files.

**Comment by mqudsi** [comment]
There's already a good workaround for it, one that is even less likely to be triggered by accident.

```fish
mqudsi@ZBook /m/c/U/Mahmoud> fish -c "echo hello >&2" | grep foo
hello
mqudsi@ZBook /m/c/U/Mahmoud> fish -c "echo hello >&2" 2>| grep foo
mqudsi@ZBook /m/c/U/Mahmoud> fish -c "echo hello >&2" 2>| grep hello
hello
```

**Comment by scooter-dangle** [comment]
What's fish's story on deprecation warnings? I pretty liberally use `^/dev/null` when I intend to ignore errors. (Although it will be pretty annoying to get a deprecation notice on stderr if I'm already explicitly ignoring errors for a particular command/function.)

**Comment by ridiculousfish** [comment]
The 3.0 release is making these sort of changes without a deprecation phase, in part for the reason you say

**Comment by kballard** [comment]
No deprecation phase is problematic because it means existing scripts will simply break without warning. This apparently includes [fisherman](https://github.com/fisherman/fisherman) and at least one fisherman plugin.

Could we at least add a deprecation phase for `master` which we then turn off when releasing 3.0? That way people testing on `master` can try and at least flag shared components (like fisherman) that need to be updated.

**Comment by ridiculousfish** [comment]
Reopening so we can think harder about how to manage this.

**Comment by lrm29** [comment]
I've just run into this breaking the fish scripts in (https://github.com/cea-hpc/modules). Would have been useful to have seen a deprecation message rather than "^: No such file or directory"!

Note that also need to update the doc to remove references to the caret:

https://fishshell.com/docs/current/tutorial.html#tut_pipes_and_redirections

**Comment by alcarithemad** [comment]
For "reasons", I've been writing a parser for the fish shell language, and found this issue while looking to see if `echo a^/dev/null` was a reported bug, as the behavior surprised me. I quite like ^ as an operator and am somewhat sad to see it go, but it does make my parsing work easier.

I'd comment more on the removal but in short: I disagree with reason 1, think the workaround is reason 2 is bad, and have no opinion on reason 3. Fish should either go all-in on ^ being exactly like > and <, or get rid of it.

**Comment by ridiculousfish** [comment]
UIs are a messy affair.

**Comment by faho** [comment]
#4940 includes this as one of our "feature" flags, so we do have actual deprecation now.

Closing!

**Comment by jorgebucaran** [comment]
👏 Good job everyone and thank you, @ThomasAH for getting the ball rolling on this.

**Comment by adeftu** [comment]
Issue is marked with fish 3.0.0 milestone and closed. However current 3.0.0 version does not include it.

**Comment by floam** [comment]
It's hidden behind a feature flag, `stderr-nocaret`.

**Comment by ron-wolf** [comment]
@floam Doesn’t that kind of defeat the purpose? Either run into weird behavior with `^`—which is un-`fish`-like for [the reasons](https://github.com/fish-shell/fish-shell/issues/4394#issue-256497982) @ThomasAH mentioned above—or add an extra line to your config files, to handle your otherwise smooth shell’s one weird behavior.

**Comment by faho** [comment]
@ron-wolf The feature flag is purely a transition thing, and will be removed in a future version of fish.

**Comment by faho** [comment]
For posterity: All code for the `^` redirection has been removed in fish 3.5.0, after it was disabled by default in fish 3.3.0.

The feature flag remains available to *check*, but it will always return true. See #8857 for more information.
