### ISSUE TITLE
Abbreviations with cursor in the middle of a command?

### ISSUE THREAD

**Issue by purohit** [fish-shell/fish-shell#4399]
Is it possible to have an abbreviation that fills out a command and puts your cursor at an arbitrary location? For example, I'd like an abbreviation `gr` that fills out the following and puts my cursor in the middle of the function where the black box is, rather than at the end:

`grep █ * -R`

(fish, version 2.6.0)

Thanks! Great work on `fish`, it's amazing.

**Comment by faho** [comment]
Currently, it's not possible.

This has been asked for before in #2287, so let's track there!
