### ISSUE TITLE
cd completion is overzealous

### ISSUE THREAD

**Issue by dnnr** [fish-shell/fish-shell#4402]
Consider the following situation:

1. `mkdir -p verylongname/a/b/c`
2. `touch verylongname/.somefile`

Now if you want to change into the `verylongname` directory to work with `.somefile`, there seem to be only two ways available:

* Either do `cd very<Tab>`, get `cd verylongname/a/b/c`, then do `cd ../../..` to actually get where you want
* Type `cd verylongname` without using completion

In this scenario, it's obviously preferable to not have the completion trying to be overly clever but simply add just one path component per tab key press.

I can't seem to find any way to configure this behavior, and as far as I could tell, this is built into fish and not implemented in a (customizable) function, right?

(I tested this on version 2.6.0-559-g6b7bcdb)

**Comment by zanchey** [comment]
The autosuggestion was extended in #2531.

One option here is to only accept one component of the autosuggestion at a time with Alt-Right or Alt-F.

**Comment by dnnr** [comment]
Thanks for the reference.

I'm a bit confused about your suggestion though: Unlike tab-completion, the autosuggestions are based on history entries, right? So this only works if I did that specific `cd...` command before?

**Comment by zanchey** [comment]
No, autosuggestions are special for `cd` - they automatically suggest the longest unambiguous path.

I think when walking the tree fish should check for any files, not just subdirectories.

**Comment by zanchey** [comment]
Right, it already does, except for ".somefilename" - `descend_unique_hierarchy()` ignores all "hidden" files which start with a dot.

**Comment by dnnr** [comment]
Not ignoring hidden files would certainly help in this scenario.

To be honest, though, I'd suggest abandoning that longest path mechanism altogether.
After all, it shouldn't require the existence of a file to justify a user's need to change into a directory that is not the end of a longest unambiguous path.

**Comment by zanchey** [comment]
I think it makes sense for the autosuggestion, but not for the tab completion.

**Comment by dnnr** [comment]
Agreed!

**Comment by ridiculousfish** [comment]
Makes sense to me.

**Comment by heinrich5991** [comment]
I don't know how this relates to `git add`. For `git add` it makes sense to complete to the longest unambiguous path.

**Comment by zanchey** [comment]
@heinrich5991, `git add` uses separate completion logic and will be unaffected.

**Comment by mtbrock** [comment]
Anyone working on this? I can't see how this behavior could be desirable but I'm skeptical as to whether a change to this would be accepted. Someone chose to make it that way, after all. Maybe I'll take a crack at it and see what happens...

**Comment by dnnr** [comment]
Judging from ridiculousfish's comment, I'd expect a change to be accepted. I'll be glad to see it happen, just haven't had the time myself... 👍

**Comment by faho** [comment]
>Anyone working on this?

I've tried my hand, yeah, but if you want to work on it, go for it!

>I can't see how this behavior could be desirable

Well, like @zanchey [said](https://github.com/fish-shell/fish-shell/issues/4402#issuecomment-329455034):

>I think it makes sense for the autosuggestion, but not for the tab completion.

I've gotten it to do that (in a rather hackish way), but I'm not sure that's the right way to go. Maybe we want to have _both_ offers for the tab completion, with the shorter one first?

>Someone chose to make it that way, after all.

Yeah, and someone chose to interpret `foo-{,,,}` as `foo- foo-, foo-`, and we've just changed that. 

>Maybe I'll take a crack at it and see what happens...

Sure. I'd suggest you look at what you do and how often you do it, and then try to find behavior that works.

**Comment by mtbrock** [comment]
It seems like it's as simple as removing the `descend_unique_hierarchy` part from `try_add_completion_result()` from wildcard.cpp. `descend_unique_hierarchy()` is not referenced anywhere else in the code so it seems it was created just to provide this feature. This occurs in `try_add_completion_result()`:

```
// Hack. Implement EXPAND_SPECIAL_FOR_CD by descending the deepest unique hierarchy we
// can, and then appending any components to each new result.
if (flags & EXPAND_SPECIAL_FOR_CD) {
    wcstring unique_hierarchy = this->descend_unique_hierarchy(abs_path);
    if (!unique_hierarchy.empty()) {
        for (size_t i = before; i < after; i++) {
            completion_t &c = this->resolved_completions->at(i);
            c.completion.append(unique_hierarchy);
        }
    }
}
```

Correct me if I'm wrong but it seems all this does is provide the exact functionality this issue references. I commented out that block and cd seems to function as desired. E.g., typing `very<TAB>` results in `verylongdir/`, another tab for `verylongdir/a/`, another tab for `verylongdir/a/b/`, etc. I'll do some more testing I guess to see if it effects anything else but I'm 99% sure it does not.

If you want to try for yourself just comment out that block (lines 589 - 597) and give it a go.

**Comment by mtbrock** [comment]
OK so removing the part from `try_add_completion_result()` in `src/wildcard.cpp` that adds the unique hierarchy to the cd completion (lines 589-597) allows cd to function normally but it also removes the unique hierarchy from the auto-suggestion. Obviously it is desired to have the unique hierarchy in the auto-suggestion so that's not quite got us there.

I'll try to add the unique hierarchy only the autosuggestion while leaving the completion alone. Will report back.

**Comment by faho** [comment]
>I'll try to add the unique hierarchy to autosuggestion while leaving the completion alone. Will report back.

Sounds good!

**Comment by mtbrock** [comment]
OK I've got it working properly now. The cd autosuggestion is unaltered and the tab completion will not descend the unique hierarchy. I'll adjust the test cases and send a pull request.
