### ISSUE TITLE
can_be_encoded failing under conhost/WSL

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4406]
When using `read --silent` under WSL/conhost, the character emitted to the terminal in place of what was actually typed is a space/blank character and not the intended "circle symbol" (`●`) or the `#` fallback that should be emitted, per `src/common.cpp:496':

```cpp
// solid circle unicode character if it is able, fallback to the hash character
obfuscation_read_char = can_be_encoded(L'\u25cf') ? L'\u25cf' : L'#';  
```

What I actually see:

![image](https://user-images.githubusercontent.com/606923/30514623-875730a2-9ade-11e7-9dc6-f2d70a2cc9e4.png)

Apart from the apparent bug in `can_be_encoded()`, is there a reason we don't just use an asterisk?

**Comment by krader1961** [comment]
This works for me using Cygwin on Windows 10; both inside the native cygwin terminal and ConEmu. Note that `can_be_encoded()` is a trivial function that is only broken if the libc we link against is broken. Perhaps you're not using a Unicode locale. What does `locale` output? It's also weird that you're seeing spaces since even if we can't encode that Unicode char you should be seeing `#`'s. So there is definitely something odd with your fish build or environment.

**Comment by mqudsi** [comment]
I think it may be the font I'm using, then. I presumed since `#` was not being printed, that meant `can_be_encoded` was returning true when it should have been false.

Perhaps we really need to be using some mythical `can_be_displayed` where it checks if the character can be shown on screen, but afaik that functionality is not exposed by the shell.

**Comment by krader1961** [comment]
Then, yes, it seems reasonable to conclude your font does not support that unicode code point. You'll probably also see problems with the "RETURN SYMBOL" unicode char. For example, while I see the filled-in circle when I run `read --silent` I get a question-mark wrapped by a box (meaning the font doesn't have a glyph for the code point) when I do `echo -n hello` under ConEmu. But under the native Cygwin terminal I see the expected glyph.

**Comment by mqudsi** [comment]
>  But under the native Cygwin terminal I see the expected glyph.

You're not using the same font for both?

**Comment by krader1961** [comment]
> You're not using the same font for both?

No, although I have no idea why not. Since I only use Windows when I have to (such as investigating how fish behaves on Windows) I've put a bare minimum of effort into setting it up and have done zero customization of those environments.

**Comment by mqudsi** [comment]
So this is probably ok to close, but I have to reiterate my question: is there really a benefit in using a special Unicode character instead of a plain asterisk?

**Comment by krader1961** [comment]
> is there really a benefit in using a special Unicode character instead of a plain asterisk?

This "feature" strikes me as someone saying to themselves "hey, wouldn't it be cool if we used a non-ASCII glyph in these situations." And when this behavior was introduced it was probably not justified. But in 2017, with support for Unicode being fairly ubiquitous, it is equally hard to justify removing it.
