### ISSUE TITLE
bind ignoring \e in binding

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4408]
I'm running into an odd issue with fish where binding one key sequence is actually mapping another.

```fish
mqudsi@Blitzkrieg /m/c/U/Mahmoud> bind -k dc delete-char
mqudsi@Blitzkrieg /m/c/U/Mahmoud> bind -k dc
bind -k dc delete-char
mqudsi@Blitzkrieg /m/c/U/Mahmoud> bind \e\[3~ kill-word
mqudsi@Blitzkrieg /m/c/U/Mahmoud> bind -k dc
bind -k dc kill-word
```

`\[3~` is my delete character.

**Comment by krader1961** [comment]
I don't understand. Binding the raw sequence, `bind \e\[3~ ...`, is equivalent to binding to a key name that is defined to send the same sequence. So it is to be expected that `bind \e\[3~ kill-word` affects the output of `bind -k dc` since the former is equivalent to `bind -k dc kill-word`. What do you expect to happen?

**Comment by mqudsi** [comment]
Isn't `\e` the meta/alt modifier?

**Comment by krader1961** [comment]
> Isn't \e the meta/alt modifier?

Yes, but it's also the prefix for nearly every sequence sent by a key that isn't a simple control character. You can see that `dc` sends that sequence by running `infocmp -1L | grep key_dc`. If you want to also have a meta variant of that key you would need to `bind \e\e\[3~ kill-word`.

**Comment by mqudsi** [comment]
Thanks for the `infocmp` hint. I've been using alt_demokeys from ncurses combined with my own raw keycode viewer.

`bind \e\e\[3~ kill-word` doesn't override the behavior of the del key, but it also doesn't trigger on alt+del.

**Comment by krader1961** [comment]
Yes, most terminals need to be configured to send a different sequence when alt/meta is applied to some keys. For example, I use iTerm2 most of the time and while I have it configured to prefix the sequence sent by the second key with `\e` that doesn't work for all keys. It works for [alt-tab], for example, but not [alt-delete]. The `fish_key_reader` program is handy for answering these types of questions.
