### ISSUE TITLE
parser rejects certain 8-character hexadecimal \U unicode sequences

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4409]
While [the fish documentation states](https://fishshell.com/docs/current/index.html#escapes) `\Uxxxxxxxx` where `xxxxxxxx` is a hexadecimal representation of a 32-bit value is a valid token, the parser rejects it:

```fish
mqudsi > echo \U1b5b337e
fish: Invalid token '\U1b5b337e'
echo \U1b5b337e
     ^
```

However this is allowed:

```fish
> echo \U0000000a
```

and this, too:

```fish
> echo \U1b5b3 #5 characters
```

Somewhere in between those two cases, the parsing breaks.

**Comment by krader1961** [comment]
That isn't a valid code point. The maximum valid code point in Unicode is U+10FFFF which is correctly handled: `echo \U0010FFFF | od -tx1x`. But adding one to that fails as I would expect:

```
$ echo \U00110000 | od -tx1x                                18 ms
fish: Invalid token '\U00110000'
echo \U00110000 | od -tx1x
     ^
```

**Comment by ridiculousfish** [comment]
What krader said.
