### ISSUE TITLE
Allow shell functions to output arrays

### ISSUE THREAD

**Issue by xiaq** [fish-shell/fish-shell#441]
(I posted this on the mailing list, but the issue tracker seems better suited for such proposals and gets a bit more attention from ridiculous_fish. :-)

Currently the output of command substitutions is split on newlines (more precisely first char of IFS). This is suitable in simple cases, but when it comes to some serious programming, the limitation of lack of structure is obvious. Structure should be explicit, instead of being inferred from the data.

The basic goal is to make the following possible and correct (the `quote` function is stolen from https://github.com/fish-shell/fish-shell/pull/354 ):

``` fish
function quote
    for a in $argv
        yield $a
    end
end

set arr a a\na a\0a a\0x1ea
set brr (quote $arr)
test (count $arr) = (count $brr); and echo "Bravo!"
```

I thought of several possible approaches, but gradually I came to prefer one solution using asymmetric [coroutine](http://en.wikipedia.org/wiki/Coroutine)s (also known as generators), elaborated as follows.

`yield` is implemented using another builtin `_yield` which only does the essential stuff:

``` fish
function yield
    for a in $argv
        printf '%s' $a
        _yield
    end
end
```

Each function call is executed in a callee coroutine, with the _caller coroutine handler_ set up beforehand. `yield` suspends the _callee coroutine_, passes the current output buffer to the caller, and clears the output buffer afterwards when control is returned to the callee.

The caller side is set up a bit differently depending on the context. In commands substitutions, when the callee yields, the handler inserts a word. Outside command substitutions, it prints the output, behaving like `echo`. They all give the control back to the callee after that.

This mimics the behavior of Python generators, hence the name `yield`.

**Comment by krader1961** [comment]
It is now more than four years since the issue was opened and the last comment was made. It is not sufficient to allow fish functions to emit lists of arrays. That is not consistent with how the output of external command is handled. Fish is not Python, Perl, or any similar language. This cannot be implemented without a radical rewrite.
