### ISSUE TITLE
fish crashing after typing "cmake -<TAB-key>"

### ISSUE THREAD

**Issue by piotrekg2** [fish-shell/fish-shell#4410]
Hi,
I'm getting the following cash report after typing `cmake -<TAB>` (hit tab key immediately after dash):

<E> fish: src/pager.cpp:181: failed assertion: desc_remaining >= 2
<E> fish: Backtrace:
<E> fish: 0   fish() [0x4a30aa]
<E> fish: 1   pager_t::completion_print(unsigned long, unsigned long const*, unsigned long, unsigned long, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, std::vector<pager_t::comp_t, std::allocator<pager_t::comp_t> > const&, page_rendering_t*) const + 600
<E> fish: 2   pager_t::completion_try_print(unsigned long, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, std::vector<pager_t::comp_t, std::allocator<pager_t::comp_t> > const&, page_rendering_t*, unsigned long) const + 510
<E> fish: 3   pager_t::render() const + 468
<E> fish: 4   pager_t::update_rendering(page_rendering_t*) const + 71
<E> fish: 5   fish() [0x4c47ae]
<E> fish: 6   reader_readline(int) + 1400
<E> fish: 7   reader_read(int, io_chain_t const&) + 528
<E> fish: 8   main + 3031
<E> fish: 9   __libc_start_main + 234
<E> fish: 10  _start + 42

Additional info:
`$ fish --version`
`fish, version 2.6.0`

`$ uname -a`
`Linux brutus 4.12.12-1-ARCH #1 SMP PREEMPT Sun Sep 10 09:41:14 CEST 2017 x86_64 GNU/Linux`

`$ echo $TERM`
`xterm`

The problem **can** be reproduced when fish is started like this: `  sh -c 'env HOME=$(mktemp -d) fish'`

**Comment by zanchey** [comment]
I can't reproduce this on 2.6.0, Integration_2.7.0 or master in either a non-CMake directory or in pcre-10.20/, which is a CMake-containing directory. Is there a CMake file in the directory where the crash occurs? Is it something you can post publicly?

**Comment by krader1961** [comment]
This is a duplicate of #4179 and has already been fixed for fish 2.7.0. The problem is that the description for one of the completion entries being displayed has one or more control characters (likely [backspace]).

**Comment by piotrekg2** [comment]
The problem no longer occurs on master. This issue can be closed.
