### ISSUE TITLE
vi command ';' does not work

### ISSUE THREAD

**Issue by dgsb** [fish-shell/fish-shell#4411]
fish version: 2.6.0
os: OS X Darwin Kernel Version 16.6.0
terminal: Terminal.app + screen

The ';' command is supposed to repeat the previous 'f', 'F', 't' or 'T'.
This command has no effect at all.
This command is quite practical to jump between a separator on a line by typing a single key.

**Comment by ridiculousfish** [comment]
Also from #4412 :

>The ',' command is supposed to repeat the reverse motion of the previous 'f', 'F', 't' or 'T' motion command.
>Currently this command has no effect at all.
>This command is quite practical to jump between a separator on a line by typing a single key.

**Comment by nesmyslny** [comment]
AFAIK, `;` and `,` should work with version 3. From the [changelog](https://github.com/fish-shell/fish-shell/releases/tag/3.0.0):
> vi-mode now supports ';' and ',' motions. This introduces new {forward,backward}-jump-till and repeat-jump{,-reverse} bind functions (#5140).

But I can't get it work.
* If I use `fish_vi_key_bindings` and type `;` or `,` nothing happens at all.
* If I use `fish_hybrid_key_bindings`, which I prefer, `;` and `,` get inserted as characters.

Do I need to add bindings to get this working?

Any help would be greatly appreciated :) Thanks!

(Also tagging @cttttt as author of #5140; hope that's ok :) )

**Comment by faho** [comment]
@nesmyslny: Works for me?

These repeat the last "f" or "t" motion, so you'll have to do e.g `fn` to jump to the next "n", and then you can jump to another n with ";" or ",".

Also confirm that you're running 3.0 with `echo $version`.

**Comment by nesmyslny** [comment]
Ugh, I feel so dumb. I was so sure fish got upgraded to 3 on Arch, but indeed I'm still on 2.7.1.
I'm so sorry for the noise and thanks @faho for the quick reply.

So I think #5140 added this feature and this issue can be closed.

**Comment by cttttt** [comment]
Phew.  Still works :)
