### ISSUE TITLE
vi command ',' does not work

### ISSUE THREAD

**Issue by dgsb** [fish-shell/fish-shell#4412]
fish version: 2.6.0
os: OS X Darwin Kernel Version 16.6.0
terminal: Terminal.app + screen

The ',' command is supposed to repeat the reverse motion of the previous 'f', 'F', 't' or 'T' motion command.
Currently this command has no effect at all.
This command is quite practical to jump between a separator on a line by typing a single key.
see #4411

**Comment by ridiculousfish** [comment]
Thanks for filing! Let's track these together in #4411
