### ISSUE TITLE
string trim does not remove blank lines

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4417]
Per the documentation:

>`string trim` removes leading and trailing whitespace from each STRING. If -l or --left is given, only leading whitespace is removed. If -r or --right is given, only trailing whitespace is trimmed. The -c or --chars switch causes the characters in CHARS to be removed instead of whitespace. Exit status: 0 if at least one character was trimmed, or 1 otherwise.

```fish
~> echo -e "\n hello\n" | string trim

hello

~> echo -e "\n hello\n" | string trim -c "\n\r\t "

hello

```

The documentation does not mention that whitespace is removed on a line-by-line basis (a la `sed`). Either this is a documentation bug or a `string trim` bug, as the general definition of whitespace is `[\r\n\t ]`.

**Comment by faho** [comment]
This is just how `string` works in general. From the documentation:

>STRING arguments are taken from the command line unless standard input is connected to a pipe or a file, in which case they are read from standard input, one STRING per line.

Note the "one STRING per line". (Obviously, phrasing suggestions are welcome!)

This is also how unix tools traditionally behaved - not just `sed`, but also `grep` and `tail` and `head` and `cut` and `paste` and...

Documenting it separately for every `string` subcommand seems wasteful.

Though it would be nice to have something to remove blank lines. So far, `string match -r '.+'` is the shortest I can come up with.

**Comment by mqudsi** [comment]
`string match -r '.+'` does not do the same, since it will remove blank lines from the middle of the output as well. 

```fish
~> echo \nhello\n\nhi\n | string match -r '.+'
hello
hi
```

versus

```fish
> echo \nhello\n\nhi\n | perl -077 -pe 's/\s*?(\S.*?)\s*$/$1\n/igs'
hello

hi
```

except that's one hell of an ugly script.

**Comment by faho** [comment]
>string match -r '.+' does not do the same, since it will remove blank lines from the middle of the output 

I thought that was what you intended. Any reason why you'd throw away empty lines at the beginning and end but not in the middle?

>as well as leading whitespace on each line.

Huh? Why should it? `.` matches _everything_ including whitespace, and since the `+` is greedy, it'll always match the entire line if there is _anything_ on it - meaning that even lines that only have whitespace would pass.

You'd need `string match -r '.+' | string trim` to also remove whitespace on each line. The `match` was purely meant to remove empty lines. Sorry for the confusion!

**Comment by mqudsi** [comment]
Sorry, I confused trim and match.

**Comment by faho** [comment]
@mqudsi: Do you still believe there's something to be done here?

I mean the wording could surely be improved, but as I said I don't think we should explain string's general behavior again for every subcommand.

**Comment by mqudsi** [comment]
No, I guess not. I think I'll open a pr for adding --multiline or something to the string builtin, there are a lot of cases where the behavior is unexpected, for instance, I could see `string escape` being a lot more useful if it could encode newlines.
