### ISSUE TITLE
Unable to run a Homebrew cleanup script beyond first loop iteration with reads

### ISSUE THREAD

**Issue by pcascio** [fish-shell/fish-shell#4418]
[This is a copy of the comment in #4178. I'm creating a new issue here instead. Sorry about that.]

I also have this problem when trying to run this script for cleaning up my unused Homebrew formulae: https://github.com/connorworley/dotfiles/blob/master/.bin/brew-autoremove

> fish --version 
fish, version 2.6.0
> echo $version 
2.6.0
> uname -a
Darwin Cascio-MBP 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
> echo $TERM
ansi

My stack:
> ./brew-autoremove.sh 
Searching for formulas not depended on by other formulas...
activemq is not depended on by other formulas. Remove? [Y/n] n
<E> fish: src/reader.cpp:1559: failed assertion: input_initialized
<E> fish: Backtrace:
<E> fish: 0   reader_push(wchar_t const*) + 1056
<E> fish: 1   builtin_read(parser_t&, io_streams_t&, wchar_t**) + 1482
<E> fish: 2   builtin_run(parser_t&, wchar_t const* const*, io_streams_t&) + 334
<E> fish: 3   exec_job(parser_t&, job_t*) + 3736
<E> fish: 4   parse_execution_context_t::run_1_job(parse_node_t const&, block_t const*) + 1204
<E> fish: 5   parse_execution_context_t::run_job_list(parse_node_t const&, block_t const*) + 117
<E> fish: 6   parse_execution_context_t::run_if_statement(parse_node_t const&) + 461
<E> fish: 7   parse_execution_context_t::run_1_job(parse_node_t const&, block_t const*) + 529
<E> fish: 8   parse_execution_context_t::run_job_list(parse_node_t const&, block_t const*) + 117
<E> fish: 9   parse_execution_context_t::run_for_statement(parse_node_t const&, parse_node_t const&) + 378
<E> fish: 10  parse_execution_context_t::run_1_job(parse_node_t const&, block_t const*) + 357
<E> fish: 11  parse_execution_context_t::run_job_list(parse_node_t const&, block_t const*) + 117
<E> fish: 12  parse_execution_context_t::eval_node_at_offset(unsigned int, block_t const*, io_chain_t const&) + 403
<E> fish: 13  parser_t::eval_block_node(unsigned int, io_chain_t const&, block_type_t) + 140
<E> fish: 14  parser_t::eval(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, io_chain_t const&, block_type_t, parse_node_tree_t) + 230
<E> fish: 15  parser_t::eval(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, io_chain_t const&, block_type_t) + 134
<E> fish: 16  internal_exec_helper(parser_t&, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, unsigned int, block_type_t, io_chain_t const&) + 1017
<E> fish: 17  exec_job(parser_t&, job_t*) + 2885
<E> fish: 18  parse_execution_context_t::run_1_job(parse_node_t const&, block_t const*) + 1204
<E> fish: 19  parse_execution_context_t::run_job_list(parse_node_t const&, block_t const*) + 117
<E> fish: 20  parse_execution_context_t::eval_node_at_offset(unsigned int, block_t const*, io_chain_t const&) + 403
<E> fish: 21  parser_t::eval_block_node(unsigned int, io_chain_t const&, block_type_t) + 140
<E> fish: 22  parser_t::eval(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, io_chain_t const&, block_type_t, parse_node_tree_t) + 230
<E> fish: 23  reader_read(int, io_chain_t const&) + 1877
<E> fish: 24  main + 3118
<E> fish: 25  start + 1
fish: './brew-autoremove.sh' terminated by signal SIGABRT (Abort)

**Comment by krader1961** [comment]
This looks like a dup of #4206 and has already been fixed in the Integration_2.7.0 branch.

**Comment by pcascio** [comment]
Ok, thanks. I'll wait for the 2.7 release.
