### ISSUE TITLE
muparser has taken over ./configure output

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4420]
In fish 3.0, `/.configure` configures the muparser sources as the final step. muparser has a very visible message in its output that provides instructions on the next steps to build and install muparser. After that prompt, we post a short message saying fish has been configured.

```
...
checking for nm... nm
checking for command to install directories... /usr/bin/install -c -d
checking if make is GNU make... yes
checking for dependency tracking method... gcc
configure: creating ./config.status
config.status: creating Makefile
config.status: creating build/autoconf/muparser.pc

 ----------------------------------------------------------------
  Configuration for muparser 2.2.4 successfully completed.
  Summary of main configuration settings for muparser:
  - STATIC mode
  - RELEASE build
  - SAMPLES disabled
  Now, just run make.
 ----------------------------------------------------------------

fish is now configured.
mqudsi@ZBook ~/r/fish-shell>
```

Users could be forgiven for thinking the instructions in muparser's configuration output are instructions for building fish (not that they're not more or less correct)

**Comment by zanchey** [comment]
What do you think would help? "`Type make to build fish`"?

**Comment by floam** [comment]
Let's replace

```
 ----------------------------------------------------------------
  Configuration for muparser 2.2.4 successfully completed.
  Summary of main configuration settings for muparser:
  - STATIC mode
  - RELEASE build
  - SAMPLES disabled
  Now, just run make.
 ----------------------------------------------------------------
```

with:

```
muparser is now configured.
```

**Comment by mqudsi** [comment]
Ideally, we'd do what @floam suggested (without diverging the muparser build code too much from upstream, if possible? How?) and print our own message akin to what muparser does, big and bold, with fish compilation instructions.

**Comment by zanchey** [comment]
The CMake build swallows this message.

**Comment by ridiculousfish** [comment]
Soon the CMake build won't invoke configure in muParser (I hope)...

**Comment by faho** [comment]
Moot now.
