### ISSUE TITLE
first completion shows up as a blank

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4424]
If you run this script:

```fish
mkdir completions_test
cd completions_test

for i in (seq 3 10)
    set fname ""
    for j in (seq 0 $i)
        set fname {$fname}a
    end
    echo $fname
    touch $fname
end
```

And then attempt to see the generated completions:

```fish
touch ./a<TAB><TAB>
```

Fish autocompletes sthe `a` to `aaa` (the first matching prefix) and then shows the following as the completion options:

```fish
mqudsi@ZBook ~/r/f/completions_test> touch ./aaa
        ./aaaaa   ./aaaaaaa   ./aaaaaaaaa   ./aaaaaaaaaaa
./aaaa  ./aaaaaa  ./aaaaaaaa  ./aaaaaaaaaa
```

Where the first matching result should appear (`aaa`) is a blank.

Whereas under fish 2.6.0:

```fish
mqudsi@ZBook ~/r/f/completions_test> touch ./aaa
./aaa   ./aaaaa   ./aaaaaaa   ./aaaaaaaaa   ./aaaaaaaaaaa
./aaaa  ./aaaaaa  ./aaaaaaaa  ./aaaaaaaaaa
```

**Comment by mqudsi** [comment]
It's not a bug with the actual completions since

```fish
echo "cat ./a" | complete -C
```

returns all the results.

I'm not sure how to test the pager with a script for bisecting.

**Comment by ridiculousfish** [comment]
Bisects to 4152bdc6985d0f488658923373e564f666157a11

**Comment by ridiculousfish** [comment]
Cherry-picked to Integration-2.7.0 as 43d00161258e53926aed645ee0ade7771080e3bb

**Comment by mqudsi** [comment]
@ridiculousfish awesome, thanks! 

Were you able to automate the bisection via a script? If you don't mind sharing how you tested the pager output without manually using the shell, I'd be grateful.

**Comment by ridiculousfish** [comment]
Nope, it was manual - but bisecting is very fast even when done manually, around ~10 attempts. What made it easy was your great repro steps!
