### ISSUE TITLE
fish hanging on Linux subsystem

### ISSUE THREAD

**Issue by knarka** [fish-shell/fish-shell#4427]
When directly starting fish in the Windows Linux subsystem (Bash on Ubuntu on Windows), e.g. by running `bash -c fish` or by adding `exec fish` to the user's `.bashrc`, with `~/.config/fish/config.fish` not present, fish hangs indefinitely. Creating `~/.config/fish/config.fish`, even if it's an empty file, resolves this issue. Running `fish` in a bash session works as well, regardless of config file.

`echo $version` gives `2.6.0`
`uname -a` gives `Linux tadtci 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux`
`echo $TERM` gives `xterm-256color`

**Comment by mqudsi** [comment]
This is a WSL bug, you can see https://github.com/Microsoft/BashOnWindows/issues/1653

We worked around this in fish 3.0, which you can obtain by building fish from the git source. See README.md for instructions (or the main page of this repo).
