### ISSUE TITLE
Make fish special variable names more consistent

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4429]
Apart from the debate about uppercase vs lowercase, I think we need to take advantage of fish 3.0 to rename some variables. I didn't look into it at depth, but I just ran into `$__fish_datadir` and co vs `$__fish_help_dir`.  These should probably all have an `_` before `dir` because that makes intelligent completion work (`~> $_dir<TAB>`) but either way works, so long as we stick to it.

**Comment by ridiculousfish** [comment]
Makes sense to me.
