### ISSUE TITLE
'echo $SHELL' returns 'zsh' when I'm using 'fish' in macOS

### ISSUE THREAD

**Issue by 3xp10it** [fish-shell/fish-shell#4430]
'echo $SHELL' returns 'zsh' when I'm using 'fish' in macOS.
I have execute:
```
brew install fish
echo "/usr/local/bin/fish" | sudo tee -a /etc/shells
chsh -s /usr/local/bin/fish
restart my computer
```

my /etc/shells content
```
/bin/bash
/bin/csh
/bin/ksh
/bin/sh
/bin/tcsh
/bin/zsh
/usr/local/bin/fish
```

env:
macOS sierra
fish2.6.0
tmux
iterm2

**Comment by mqudsi** [comment]
fish doesn't set the `SHELL` environment variable. I don't know if it ever did.

**Comment by krader1961** [comment]
The most likely explanation is that your terminal program has been configured to launch zsh when opening a new terminal window. Start by confirming that your default login shell really is fish (replace `username` with your username):

```
dscl . -read /Users/username UserShell
```

Assuming that reports `/usr/local/bin/fish` open your terminal configuration and verify that you have not forced it to use *zsh* when opening a terminal window.

Note that the `SHELL` variable is not meant to reflect the shell currently running. It's meant to reflect your preferred interactive shell. Well behaved shells simply honor (that is, retain) its value if already in the environment. If `SHELL` is not in the environment it will ask the OS for your preferred shell and set it to that value -- not the name or path of the current shell --  but won't normally export it.

**Comment by krader1961** [comment]
Note that fish does not set `SHELL` if it is not already set in the environment. That isn't technically a bug. Bash sets it to the preferred shell but does not export it. Zsh and csh doesn't even do that. There isn't any standard, defacto or official, regarding the preferred or correct behavior in this situation. That's because the expectation is that `/bin/login` or whatever launches your login shell has already exported `SHELL` with the value of your default login shell.

**Comment by 3xp10it** [comment]
`dscl . -read /Users/username UserShell` get `UserShell: /usr/local/bin/fish`,
then I uninstall iterm2 and reinstall iterm2,run `echo $SHELL` still get `/bin/zsh`.

**Comment by floam** [comment]
Do you get the same thing in Terminal.app? Are you sure iTerm2 isn't set to run zsh in the preferences?

**Comment by 3xp10it** [comment]
@floam I get the same in Terminal.app. I am sure iTerm2 isn't set to run zsh in the preferences.

**Comment by floam** [comment]
Let's say you do `chsh -s /bin/ksh` - is `$SHELL` correct?

Does `set -U | grep SHELL` print anything in fish?

**Comment by 3xp10it** [comment]
@floam `set -U | grep SHELL` print nothing in fish.
`chsh -s /bin/ksh` 's `$SHELL` is correct as /bin/ksh.

**Comment by 3xp10it** [comment]
I found the reason,I have set up my .tmux.conf file:
```
set -g default-shell /bin/zsh
set -g default-command /bin/zsh
```
Thanks for all your solution.
Later I changed it to:
```
set -g default-shell $SHELL
set -g default-command $SHELL
```

**Comment by siddhuKantipudi** [comment]
I am having the same issue. When i execute 

```
set -g default-shell $SHELL
```
I was getting this error: 
`Variable name 'default-shell' is not valid. See 'help identifiers.'`

Thank you for your help.

**Comment by faho** [comment]
@siddhuKantipudi: Your error message looks like you're executing that inside fish. That code is supposed to go into tmux.conf instead.

**Comment by siddhuKantipudi** [comment]
@faho oh i see. Thank you. I created the file .tmux.conf with the following config. 
```
set -g default-shell $SHELL
set -g default-command $SHELL
```
Then can u help me with the next steps.?. I am getting the following error when i execute 
`chsh -s `which fish`
```
Changing shell for siddhuKantipudi.
Password for siddhukantipudi: *password*
chsh: /usr/local/bin/fish: non-standard shell
HQSML-1649535%
```

**Comment by siddhuKantipudi** [comment]
@faho Thank you again. Even though, i successfully ran the command 
`chsh -s /usr/local/bin/fish`, when i open a new tab in `iterm2`, my `zsh` is set as default instead of `fish`. Am i missing anything?.

**Comment by faho** [comment]
@siddhuKantipudi: Did you log out and back in? Otherwise check iTerm's settings.

**Comment by siddhuKantipudi** [comment]
@faho I successfully updated the settings by running following commands.
`sudo echo /usr/local/bin/fish >> sudo /etc/shells`
`chsh -s /usr/local/bin/fish`
For some reason, the fish is not copied to shell when i execute 
`sudo cp  /usr/local/bin/fish /etc/shells` previously. So append the line and executed chsh. All good now with my fish :). Thanks for your help.
