### ISSUE TITLE
how to set up config.fish to auto run tmux every time start fish

### ISSUE THREAD

**Issue by 3xp10it** [fish-shell/fish-shell#4434]
I try to add 
```
test $TERM != "screen"; and exec tmux
```
to my config.fish as <a href="https://askubuntu.com/questions/560253/automatically-running-tmux-in-fish">here</a> tells,but find it not work for me.

env:
iterm2
tmux
fish 2.6.0
macOS sierra

**Comment by krader1961** [comment]
It's safer to test if the `TMUX` variable is set. You'll also want to ensure you only do this in an interactive shell. You should put this at the top of your *config.fish* since there isn't any point doing any of the other things in that script if you're going to immediately replace the shell with a tmux client.

```
if status is-interactive
and not set -q TMUX
    exec tmux
end
```

Also, just saying it doesn't work is less helpful that telling us how it behaved. For example, was there an error message? Did you just get a normal interactive fish shell not nested inside a tmux session? If so what does `echo $TERM` show?

**Comment by 3xp10it** [comment]
when I add
```
if status is-interactive
and not set -q TMUX
    exec tmux
end
```
to the top of my config.fish,it works,but still exists another problem as <a href="https://github.com/fish-shell/fish-shell/issues/4432">here</a>

**Comment by krader1961** [comment]
> ... but still exists another problem as here

That is almost certainly because the target machine does not have a fixed *config.fish*. You will need to login to that system and manually fix its *config.fish.*.

**Comment by 3xp10it** [comment]
After I updated both two machines' config.fish as <a href="https://github.com/3xp10it/config.fish/blob/master/config.fish">here</a> ,then I try to execute below command:
```
✔︎ mytools (master) scp 3xp10it@25.7.52.242:/Users/3xp10it/1.md /tmp/
Password:
TERM environment variable not set.
192.168.89.190
```
It still cannot scp file successfully.

**Comment by krader1961** [comment]
The first problem I saw was this block of code in your *config.fish*:

```
if status is-interactive 
and not set -q TMUX
    exec tmux
end
clear
```

You should not, and can not, run any command such as `clear` the requires an interactive shell if the shell it not interactive. Doing so will break things like `scp` because the output of commands like `clear` assume an interactive shell. If the shell session is not interactive running commands like `clear` will cause the the the type of problem you are seeing. In fact it looks like all or your *config.fish* commands should only be done within a

```
if status is-interactive
...
end
```

block.

**Comment by 3xp10it** [comment]
I try to make my config.fish as below shows:

```
if status is-interactive 
and not set -q TMUX
    exec tmux

    export LC_ALL=zh_CN.UTF-8
    export LANG=zh_CN.UTF-8
    [ -f /usr/local/share/autojump/autojump.fish ]; and . /usr/local/share/autojump/autojump.fish
    alias ll='ls -al'
    alias la='ls -A'
    alias l='ls -CF'
    alias vi='vim'
    alias 2sqlmap='cd /usr/share/sqlmap'
    alias 2tamper='nautilus /usr/share/sqlmap/tamper'
    alias pg='ping www.google.com'
    alias pb='ping www.baidu.com'
    alias 2output='nautilus ~/.sqlmap/output' 
    alias 2log='cd ~/.sqlmap/output; and ls -al' 
    alias 2images='nautilus /usr/share/images'
    alias 2tamper1='cd /usr/share/sqlmap/tamper'
    alias Cknife='java -jar /usr/share/Cknife/Cknife.jar'
    alias vs='vim ~/myblog/_posts/2016-09-25-notes.md'
    alias z='cd ~/Desktop; or cd ~/桌面'
    alias v="vim ~/tmp.txt"
    alias c="rm ~/.vimswap/tmp.txt.swp"
    alias b='cd ~/myblog'
    alias p='cd ~/myblog/_posts; and ls -lh'
    alias 2tamper="cd /usr/share/sqlmap/tamper; and ls -al"
    alias mt="cd /usr/share/mytools; and ls -al"
    alias jt="python3 /usr/share/mytools/mysnippingtool.py"
    alias upa="bash /usr/share/mytools/up.sh"
    alias macosbak="bash /usr/share/mytools/macosbak.sh"
    alias bl="python3 /usr/share/mytools/blog.py"
    alias sm="sqlmap --smart --threads 4 --random-agent -v 3 --batch -u "
    alias smt="sqlmap --smart --threads 4 --random-agent -v 3 --batch --tamper='randomcase,between,space2dash' -u "
    alias smc="sqlmap --smart --threads 4 --random-agent -v 3 --batch --crawl=3 -u "
    alias smct="sqlmap --smart --threads 4 --random-agent -v 3 --batch --crawl=3 --tamper='randomcase,between,space2dash' -u "
    alias ns="python3 /usr/share/mytools/newscript.py"
    alias py="cd ~/mypypi/; and ls -al"
    alias s0="shutdown -r +0"
    alias pj="pkill jekyll;pkill ruby"
    echo "ifconfig" | zsh | grep -oe 'inet.*netmask.*broadcast' | awk '{print $2}'
    alias od='tmux splitw -h -p 38; and tmux splitw -v -p 30; and tmux selectp -L; and tmux splitw -v -p 30; and tmux selectp -U; and ranger'
    alias pp='pkill -9 python'
    alias 2p="cd (pip3 show exp10it | egrep 'Location:' | egrep -o '/.*')"

    alias mvim='/Applications/MacVim.app/Contents/MacOS/Vim'
    alias vim='mvim'
    alias py2="python2"
    alias py3="python3"
    export EDITOR=vim
end
```

No more scp problems come out,but find I cannot use all my alias short command in my fish shell if all the alias commands are in 
```
if status is-interactive
end
```
as upon config.fish content.

**Comment by mqudsi** [comment]
Maybe I'm missing something, but in this case doesn't tmux technically host fish and not the other way around? Can tmux be set up as your login "shell" in your terminal, and have that configured to run `fish` at startup?

**Comment by 3xp10it** [comment]
Are you talking about adding below content to iterm2 preference:
```
tmux attach -t base || tmux new -s base
```
it works.

**Comment by zanchey** [comment]
Great!

**Comment by mahesh-maximus** [comment]
I'm using a docker image so, I have set the below to make the fish as default shell, Below will create a new fish shell for every tmux session.

`RUN chsh -s $(which fish)`

[Related code available here](https://github.com/mahesh-maximus/mdb/tree/main/tools)

**Comment by ayamir** [comment]
```fish
if status is-interactive
and not set -q TMUX
    exec tmux -u new -A -D -t f4h
end
```

**Comment by cowboyliao** [comment]
I don't like everytime I new a terminal, it will creat a new session.
```
if status is-interactive
    if tmux has-session -t home
        tmux attach-session -t home
    else
        tmux new-session -s home
    end
end
```
by this it will auto attach to a exist session called "home", and if there is not home, it will creat one. 
```
#!/usr/bin/env fish
set session (find . ~/ ~/.config ~/pg -mindepth 1 -maxdepth 1 -type d | fzf)
set session_name (basename "$session"|tr . _)

if  tmux has-session -t "$session_name" 2>/dev/null 
  tmux new-session -s "$session_name" -d -c "$session" 
end
tmux switch-client  -t "$session_name"
```
with this tmux-sessionizer it's really handy.

**Comment by gretaSamsa** [comment]
new versions of tmux support an argument `tmux -A session_name` which will attach you to a session if it exists, and if it doesn't it will be created

**Comment by arthurbailao** [comment]
> new versions of tmux support an argument `tmux -A session_name` which will attach you to a session if it exists, and if it doesn't it will be created

The correct command is actually `tmux new-session -A session_name`.

**Comment by Song-Tianxiang** [comment]
> The correct command is actually `tmux new-session -A session_name`.
`tmux new-session -As session_name` work for me.
