### ISSUE TITLE
export VAR=value exit status is 1 (but set -x exits cleanly)

### ISSUE THREAD

**Issue by spinningarrow** [fish-shell/fish-shell#4435]
```
fish --version: fish, version 2.6.0
uname -a: 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
$TERM: screen-256color
```

I understand that the idiomatic way to export variables in fish is using `set -x`. However, `export` is also available for compatibility. When I use `export`, the variable gets set and exported, but the exit code of the export function is 1. Is this normal?

**Comment by floam** [comment]
This is because set retains the status of the previous command if all goes well (#3651). In `export.fish`, we're stuck returning 1 when we hit the `else` clause after the check with `contains` check fails. We can work around this in `export.fish` by resetting the status ourself.

**Comment by floam** [comment]
Fixed, thanks!
