### ISSUE TITLE
Fish should hard-code italics and dim capabilities on MacOS/xterm-256color

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#4436]
`set_color -i; echo -n foo` and `set_color -d; echo -n foo` both do not work in Terminal.app or iTerm due to MacOS shipping a really old terminfo, despite Terminal.app and iTerm supporting the features. 

There is an open radar report I filed with Apple over a year ago. It seems unlikely that Apple will update ncurses - it has shipped with a version from 2013 for years. High Sierra did not touch it.

On this platform, fish should override `enter_italics_mode` and `enter_dim_mode` with the correct escape to make the features usable.

**Comment by zanchey** [comment]
This got reverted in Integration_2.7.0, and I don't want to take it for now.

**Comment by mvolkmann** [comment]
Bummer. This seems like a very useful fix. In my new fish article at https://mvolkmann.github.io/fish-article/#Colors (see "To enable the use of") I had to go into quite a bit of detail and include several links to explain how to fix this on a Mac. It would be great if none of that was necessary.

**Comment by floam** [comment]
>  It would be great if none of that was necessary.

I agree, and eventually it will not be. @zanchey isn't the bad guy here!

I don't want to speak for him, but I *think* what he was referring to with the "not take this for now" yhinh is not taking this for 2.7.0 - as it was milestoned - which is being rolled as we speak as a first beta. I'd have liked to see this fixed for 2.7 - I'd like to see it in a 2.7 beta - that's not in the cards - but regardless it remains fixed in our 3.0/master branch and I don't predict anyone reverting that so this is on a slow boat towards making it to everyone. (I'd perhaps like to see this make it into a 2.7.1 if one ever exists just because it's a TERRIBLY annoying broken feature on macOS, but no promises as that'd really need buy-in from other developers.)

And the one who reverted this patch from the 2.7 integration branch was **me** - I had cherry-picked it from 3.0 but some changes made since the source diverged caused it not to work so I immediately reverted it. One would need to re-do the patch for 2.7 to get the same behavior and functional italics/dim. Had I been quicker about coming up with a 2.7-specific patch it's possible I might have been able to sneak this fix in for 2.7.

**Comment by zanchey** [comment]
Indeed.
