### ISSUE TITLE
Command substitution with an empty result and strings

### ISSUE THREAD

**Issue by nsf** [fish-shell/fish-shell#4438]
fish, version 2.6.0

In short: if command substitution returns an empty string, the whole argument it is a part of turns into an empty string. E.g.

```sh
nsf@crey ~> echo "hello:"(echo -n "")

nsf@crey ~> echo "hello:"(echo -n "1")
hello:1
```

As a programmer I find this behaviour very confusing, tried to find something about it in documentation and in issues, no luck. Is this a bug or a feature? What is the logic behind it?

No matter how fancy it is:

```sh
nsf@crey ~> echo "hello:"(echo -n "")"234"(echo -n "1")"234"

nsf@crey ~> echo "hello:"(echo -n "1")"234"(echo -n "1")"234"
hello:12341234
```

Works fine with empty strings:
```sh
nsf@crey ~> echo "123"""''"2"
1232
```

**Comment by floam** [comment]
You're getting our [cartesian product behavior](https://fishshell.com/docs/current/#cartesian-product). An empty element will cause no output.

You can use `echo -s` and separate things into multiple arguments:

```shell
$ echo -s "hello:" (echo -n "") "234" (echo -n "1") "234"
hello:2341234
```

**Comment by nsf** [comment]
Thanks for clarification. But I guess the unexpected part was that command substitution which returns nothing is not an empty string, but an empty list (as all variables in fish are lists).

Anyways, I can see the difference between an empty list and a list with a single empty string manifests itself in other places as well, e.g.: https://github.com/fish-shell/fish-shell/issues/2037. I guess it's not something that is easy to fix. Perhaps having command substitution within string literals would be a solution to this problem. Because as https://github.com/fish-shell/fish-shell/issues/2037 suggets one can force a variable to a string via `"$x"`, would be logical to offer the same for command substitutions e.g. `"$(echo -n "")"`. Don't get me wrong, I don't want to start another discussion here, I'm sure there are plenty of comments which suggest a need for command substitutions within string literals. Just a comment.
