### ISSUE TITLE
Alt-Hash (alt+#) messes up highlighting

### ISSUE THREAD

**Issue by heinrich5991** [fish-shell/fish-shell#4439]
Enter any command that generates interesting highlighting, e.g. `git status README.txt` when `README.txt` exists in the current folder. Press `alt+#` (which puts a `#` in front of the line) and see how the highlighting still matches the line without the `#`.

Example output:
![alt-hash](https://user-images.githubusercontent.com/366230/31054626-c3ddd1a0-a6b6-11e7-8526-413798fd7fed.png)

(first I entered the line and pressed `enter`, then I entered the line and pressed `alt+#`, and finally, I pressed `up`, to view the previous line).

```
$ fish --version
fish, version 2.6.0
$ echo $version
2.6.0
$ uname -a
Linux arch6 4.12.12-1-ARCH #1 SMP PREEMPT Sun Sep 10 09:41:14 CEST 2017 x86_64 GNU/Linux
$ cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"

$ xfce4-terminal --version
xfce4-terminal 0.8.6 (Xfce 4.12)

Copyright (c) 2003-2017
	The Xfce development team. All rights reserved.

Written by Benedikt Meurer <benny@xfce.org>,
Nick Schermer <nick@xfce.org>
and Igor Zakharov <f2404@yandex.ru>.

Please report bugs to <http://bugzilla.xfce.org/>.
```

I tried finding this issue on the issue tracker, but searching for special symbols is surprisingly hard. I hope that this isn't a duplicate.

**Comment by mqudsi** [comment]
This is weird, it seems the presence of `commandline -f execute` in `__fish_toggle_comment_commandline` suppresses the coloring change. Even an explicit `commandline -f repaint` doesn't help.

**Comment by faho** [comment]
I can no longer reproduce this, I'm assuming it's been fixed.

**Comment by heinrich5991** [comment]
I can confirm it's fixed.
