### ISSUE TITLE
FIGNORE-like support

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4440]
Bash and ZSH support `$FIGNORE` and `$fignore` respectively, [which lists patterns that should not be included in autocomplete suggestions](https://docstore.mik.ua/orelly/unix3/upt/ch28_07.htm). The exact behavior differs depending on the shell, but this can be used to manipulate both head and tail autocompletions (i.e. command name and arguments), blocking files that match these patterns from being suggested (unless they are the only match).

I'm sure I don't agree with merging both head and tail autocomplete ignore patterns into the same list like bash/zsh do, but is having two separate blacklists overkill?

Note that this (in the form of head pattern block lists) is required to work around PATH pollution, [such as this bug (IMHO, at any rate) in WSL](https://github.com/Microsoft/BashOnWindows/issues/2515) that imports _all_ dll files in the system32 directory as executable, meaning trying to autocomplete command names in fish becomes useless:

![image](https://user-images.githubusercontent.com/606923/31074785-8da97942-a772-11e7-8ded-f4f2e5e5ab47.png)

Tail pattern blacklisting is useful for blocking `~`, `.swp` temporary/swap files on a global level (vs setting up, say, a vim completion rule that provides files that aren't `.bak` or `.swp` from being suggested). This would address #985, among others.

**Comment by mqudsi** [comment]
Since fish already has intelligent completions for arguments, I would suggest that one variable would control what files are imported from `PATH`, while another variable could be used as a global blocklist for actual file completions. 

i.e. `*.dll` in the head block list would prevent anything matching the expression `*.dll` from being suggested as an un-pathed completion, while another variable would basically filter the results of `complete -f` on a global level.

**Comment by mqudsi** [comment]
So this is actually more-or-less implemented now as of https://github.com/fish-shell/fish-shell/commit/a9b582d2a806a7ded75adc004e90cb378a17c82b except the `FIGNORE` pattern is hard-coded (to `*.dll`) and it's only executed if running under WSL, and applies only to the head.

I was going to extend this further to allow `FIGNORE` to be set via a fish variable, but I found that there was nothing I wanted to *globally* block from being considered for tab completions. Even things like `*.swp` or `~*` temporary files - even though I definitely don't want them to come up when I type in `nvim foo<TAB>`, I _do_ want to be able to do `rm foo<TAB>` to remove those temporary files. 

(I suspect users of `FIGNORE` also have a GUI for their installation, something I do not have/use so the console is my main means of interacting with these files.)

I also cannot think of any files that are marked as executable under Linux that should not be considered for execution (i.e. completed as a possible command head), except in the case of WSL where basically all files are `+x` and there's no way to unset that (as `+x` has a different meaning in the Windows world and the permissions are actually translations of NTFS ACLs), therefore the commit hardcodes the `FIGNORE` pattern, restricts it to WSL, and limits it to head completions only.

**Comment by michkot** [comment]
Could this be extended to a user-configurable way / in a way so that MSYS2 users could benefit from it? @mqudsi 

I am now using bash and `EXECIGNORE=*.dll`, but I can not find matching functionality in fish (and zsh).

I got here from:
https://github.com/microsoft/WSL/issues/2515#issuecomment-611620347
