### ISSUE TITLE
eval scope

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4443]
Is the following a bug or a feature?

```fish
eval set -l foo bar
if not echo "bar" | string match -q $foo
    echo Assertion failed!
end
```

`eval` isn't explicitly documented as creating a scope.

(note that this "feature" caused some consternation in the implementing of #4442)

**Comment by mqudsi** [comment]
See https://github.com/fish-shell/fish-shell/issues/565#issuecomment-259046107

Still not clear on whether it's a bug or not, though.

**Comment by mqudsi** [comment]
@ridiculousfish any thoughts on this?

**Comment by ridiculousfish** [comment]
It's a bug due to eval's implementation as a function.

**Comment by mqudsi** [comment]
This should work correctly now.

**Comment by faho** [comment]
Okay, so the `eval` builtin doesn't create a new scope, but `source` still does?

I think we might want to change it in `source` as well?

**Comment by mqudsi** [comment]
I keep remembering I need to reply to this and then forgetting to do so.

TBH, I like that `source` has its own scope -- since you're typically editing the files out-of-band and they're expected to play nice regardless of how they're loaded, etc. I feel it would be counter-intuitive for `source` to use the existing scope. I'd prefer just officially changing that from "bug" to "feature" and explicitly documenting that `source` creates a new scope.

**Comment by zanchey** [comment]
Noted in the docs.

**Comment by mqudsi** [comment]
Thanks, @zanchey!
