### ISSUE TITLE
Unable to access npm/fish interface, unless I bash, then reinitiate fish shell

### ISSUE THREAD

**Issue by jodriscoll** [fish-shell/fish-shell#4445]
**Completing the Issue Requirements:**
- `fish, version 2.6.0`
- `16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64`
- `xterm-256color`
![env-output](https://user-images.githubusercontent.com/996636/31128248-35b5f0aa-a81f-11e7-8c35-7a3aedb42457.png)
- `Oh My Fish version 5`
---
**Issue Description:**
Forced to execute `> bash; fish` to validate and support `npm`, `nvm`, etc...

![npm_requiring_bashing](https://user-images.githubusercontent.com/996636/31128528-133f9962-a820-11e7-9b6e-566fdc343b21.gif)
![fish_config](https://user-images.githubusercontent.com/996636/31128530-15b9fc3c-a820-11e7-84fa-987f47e43777.png)

**Additional Perspective:**
I've noticed that when interacting with the IntelliJ suite of software, their terminal has a similar error, however, it is slightly different as I must complete the same executions in order to display the appropriate shell interface – see below.

![intellij_fish_bashing](https://user-images.githubusercontent.com/996636/31128754-b2d9d424-a820-11e7-918c-20d0406279db.png)

**Summary:**
I'm looking towards eliminating the need to execute `bash; fish` every single time I interact with my terminal.

I'm a massive fan of the shell, just trying to get the configuration sorted to make it a benefit, rather than a burden.

Thanks ahead of time!

**Comment by zanchey** [comment]
My guess is that something is setting up the path for NPM etc. in a bash-specific way. How have you installed npm?

**Comment by jodriscoll** [comment]
Hello @zanchey – Not entirely sure what I could provide you to answer your question(?), but I'll give it a shot.

- **Node**, **NPM** and **NVM** has been installed globally

Executing `bash -x`, produces a few references to NPM; hopefully this will help isolate my issue?
```bash
++ export NVM_BIN=/Users/**redacted**/.nvm/versions/node/v6.11.3/bin
++ NVM_BIN=/Users/**redacted**/.nvm/versions/node/v6.11.3/bin
++ '[' '' = true ']'
++ local NVM_USE_OUTPUT
++ '[' 1 -ne 1 ']'
++ '[' _v6.11.3 '!=' _system ']'
++ local NVM_USE_CMD
++ NVM_USE_CMD='nvm use --delete-prefix'
++ '[' -n v6.11.3 ']'
++ NVM_USE_CMD='nvm use --delete-prefix v6.11.3'
++ '[' 1 -eq 1 ']'
++ NVM_USE_CMD='nvm use --delete-prefix v6.11.3 --silent'
++ nvm_die_on_prefix 0 'nvm use --delete-prefix v6.11.3 --silent'
++ local NVM_DELETE_PREFIX
++ NVM_DELETE_PREFIX=0
++ case "$NVM_DELETE_PREFIX" in
++ local NVM_COMMAND
++ NVM_COMMAND='nvm use --delete-prefix v6.11.3 --silent'
++ '[' -z 'nvm use --delete-prefix v6.11.3 --silent' ']'
++ '[' -n '' ']'
++ '[' -n '' ']'
++ nvm_has npm
++ type npm
++ local NVM_NPM_PREFIX
+++ npm config --loglevel=warn get prefix
++ NVM_NPM_PREFIX=/Users/**redacted**/.nvm/versions/node/v6.11.3
++ nvm_tree_contains_path /Users/**redacted**/.nvm /Users/**redacted**/.nvm/versions/node/v6.11.3
++ '[' -n '' ']'
+ '[' -s /Users/**redacted**/.nvm/bash_completion ']'
+ . /Users/**redacted**/.nvm/bash_completion
++ nvm
++ [[ -n '' ]]
++ complete -o default -F __nvm nvm
```

Output for my current configuration:
```bash
 ~ > node -v
v6.11.3
 ~ > npm -v
5.4.2
 ~ > nvm --version
0.33.2
 ~ > fish --version
fish, version 2.6.0
```

**Comment by zanchey** [comment]
I think what's happening here is that you have `npm` installed somewhere that isn't in the `PATH` variable, so fish doesn't know how to find it. When you start bash, something in the startup files adds the right path to your `PATH`, so when you start fish again it inherits the existing value of the variable and can now find npm. Running `echo $PATH; type npm` before and after running bash may help to clarify that.

This is not a fish problem, so I probably can't help you further (though others may have ideas). I use Homebrew to install Node and NPM without trouble, so that might be worth a go instead of whatever method

**Comment by faho** [comment]
@jodriscoll: Please try what @zanchey suggested:

>Running `echo $PATH; type npm` before and after running bash may help to clarify that.

**Comment by faho** [comment]
No answer in a while, closing.
