### ISSUE TITLE
Cannot not open database file '/usr/share/scout/bin-foo.db' when command not found

### ISSUE THREAD

**Issue by CeleritasCelery** [fish-shell/fish-shell#4447]
Using:
fish, version 2.6.0
SUSE Linux Gnome Desktop 2.28.2
Gnome Terminal

It looks like others have had this same problem on other distributions as in #1570, #1208, and #3366. 

I am having the problem where if a command is not found rather then getting the "correct" output I get `Cannot not open database file '/usr/share/scout/bin-foo.db'`. I have tried this without third-packages and the result is the same.

**Comment by krader1961** [comment]
Run `type __fish_command_not_found_handler`. You should see that it is defined thusly:

```
function __fish_command_not_found_handler --on-event fish_command_not_found
    /usr/bin/command-not-found $argv[1]
end
```

The problem is with the */usr/bin/command-not-found* command on your system.

**Comment by CeleritasCelery** [comment]
```
function __fish_command_not_found_handler --on-event fish_command_not_found
    command-not-found -- $argv[1]
end
```
after looking into it more it looks like the `--` is causing the problem. If I remove that part of the function it works. well, at least it just returns some error code. What is the expected behavior of `command-not-found`?

**Comment by faho** [comment]
@CeleritasCelery: Can you post the contents of /etc/os-release?

The issue here is we're not detecting that you are running suse (which we unfortunately need to since Ubuntu also has a command named "command-not-found" that behaves differently).

**Comment by CeleritasCelery** [comment]
`/etc/os-release`
```
NAME="SLES"
VERSION="11.4"
VERSION_ID="11.4"
PRETTY_NAME="SUSE Linux Enterprise Server 11 SP4"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:11:4"
```

**Comment by faho** [comment]
>Its seems the problem is the code is only looking for suse while sles (suse enterprise) is also valid.

Urgh... yeah, that's it. Fix incoming.

**Comment by mikemhenry** [comment]
After an update, I'm running into the same issue. Nothing looks obviously wrong in the way 2.7.1 parses os-release, but my `__fish_command_not_found_handler` has `--` added. If I run  `command-not-found -- foo`  I get: 

```
 --: searching ...Cannot not open database file '/usr/share/scout/bin-foo.db'
--: command not found  
```

But if I remove the `--` ie `command-not-found foo` I get: 

`foo: command not found `


Let me know if you have any idea, thanks!
I've include some info below.

```    
/etc/os-release
```

```
NAME="openSUSE Tumbleweed"
# VERSION="20180427"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20180427"
PRETTY_NAME="openSUSE Tumbleweed"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:tumbleweed:20180427"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
```



`type __fish_command_not_found_handler`

```
__fish_command_not_found_handler is a function with definition
function __fish_command_not_found_handler --on-event fish_command_not_found
    command-not-found -- $argv[1]
end
```
`fish --version `

`fish, version 2.7.1`

**Comment by faho** [comment]
@mikemhenry: That's the Ubuntu handler. Suse's is slightly different, as you can see here.

The issue is that Tumbleweed has _yet another os string_, and we're not reading ID_LIKE as a "space-separated list" like the documentation tells us to.

Fix incoming.

**Comment by faho** [comment]
@mikemhenry: e02e485cc6e712879d10fc99034543b7424567fb should solve your problem.

**Comment by mikemhenry** [comment]
Yes there was quite the uproar on the mailing list when that changed so I
had a hunch I'd see the fallout eventually.

**Comment by mikemhenry** [comment]
Fix works! Thanks!
