### ISSUE TITLE
redirect stdout to multiple commands

### ISSUE THREAD

**Issue by gorliver** [fish-shell/fish-shell#4449]
I used to run something in bash like:
`cat README.txt | tee >(tr '[:lower:]' '[:upper:]' > README.txt.up) >(gzip > README.txt.gz) | wc -l`
I tried in fish (version 2.6.0) but it doesn't work. Is there a fish equivalence for this?

**Comment by faho** [comment]
>Is there a fish equivalence for this?

Currently no. See #1786.

The best you can do right now is to store the output in a variable and then `printf` that to the commands, like

```fish
set -l readme (cat README.txt)
printf '%s\n' $readme | tr '[:lower:]' '[:upper:]' > README.txt.up
printf '%s\n' $readme | gzip > README.txt.gz
```

**Comment by gorliver** [comment]
That works, Thank you!
