### ISSUE TITLE
`list` builtin proposal

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#445]
This issue tracks a proposal for a `list` builtin, which is meant to address some common problems in fish scripting. This is based on the discussions in #354, in particular the `array` or ` ideas, but attempts to simultaneously address additional problems.

One problem is that strings with newlines get turned into arrays after command substitutions, whether you want them to or not: https://github.com/fish-shell/fish-shell/issues/159 which makes them hard to use: https://github.com/fish-shell/fish-shell/issues/348

The opposite problem is that generating an "array literal" requires using newlines:

    (echo a\nb\nc)

This clumsy syntax makes command substitutions an unsuitable replacement for bracket expansion, which we would like to remove: https://github.com/fish-shell/fish-shell/pull/354

The proposal to address these is to introduce a new builtin for manipulating arrays: `list`. `list` is a primitive operation like `set`, and therefore possesses magic powers. Its magic power is to behave slightly differently from other commands in command substitutions.

`list` can be used to construct an array:

    list $a $b $c

This prints to stdout the elements of $a, $b, and $c, separated by newlines. In that sense, `list` is like this:

    function list
        for arg in $argv
            echo $arg
        end
    end

However, the behavior is subtly different when it is the last (or only) command in a command substitutions:

    (list $a $b $c)

In this case, the command substitution is *not* split on newlines. The result is an array containing the elements of $a, $b, and $c, regardless of their contents.

Brace expansion would be replaced with:

    ls fish.(list h cpp)

`list` also supports the arguments `--split` and `--join`, which can be used for string munging. `--split` makes its argument(s) into an array:

    (list --split \t $a)

The above outputs an array containing the elements of `$a`, where each is split on the given string. If used at the end of a command substitution, the resulting array is *not* split on newlines (unless the splitting character is a newline).

`list --join` is different in that it takes its input on stdin instead of as an argument. It joins the lines into a single element, separated by the following argument (usually \n, but possibly an empty string). This enables easy capture of multi-line output. Soares's example from #348 becomes:

    set -l gs (git status --porcelain | cut -c1-2 | sort | list --join \n)

Joining an array that's already in a variable is doable, if a little weird:

    set -l $str_var (list $array_var | list --join \n)

This ought to be a rare case; most of the time you can join at the end of a command substitution.

Preemptively answer questions:

* Why not 'array'?

list is shorter and more of a verb. I propose changing the fish documentation to replace "array" with "list" everywhere.

* Why not `?

Users who do not have LISP experience are unlikely to associate backticks with lists. Users with experience in other shells are likely to be confused as well, since backticks are used for command substitutions.

* Will list be slower than bracket expansion?

Because it is a builtin, it can be optimized. For example, it's feasible to recognize it and treat it like bracket expansions.

* How does list know not to split on newlines?

It will be special cased in the shell.

* In `(list $a $b $c)`, what if `$a` is a modifier like '--split'?

Only literal arguments will be treated as modifiers, again through special casing. (There is precedent for this: `count` only interprets `--help` if it is literal, and treats it like a normal argument if it comes from a variable.)

* If a function is invoked in a command substitution and the function in turn invokes `list`, does the command substitution get the `list` treatment?

Not initially, but perhaps in the future depending on interest.

**Comment by szhu** [comment]
I found a way to invert the list splitting done by command substitution [inspired by [this](http://unix.stackexchange.com/a/205310/64762)]

```fish
set results (ls)
echo -ns $results\n
# $results\n: The cartesian product of $results and \n (aka, $result\n for result in $results)
# echo -n: Do not add a newline at the end
# echo -s: Do not separate arguments with spaces
```

The output of this will always be identical to that of `ls` itself.

Not too sure if this thread is the right place to put it, but I think this code would be useful for list joining if it were to get implemented as a function.

**Comment by ridiculousfish** [comment]
Very clever :)

The string remains split within the variable however.

**Comment by faho** [comment]
Don't we basically have this in `string split` already (with a slightly different syntax), the only thing remaining being the super powers?

**Comment by ridiculousfish** [comment]
Yeah, I say so. In particular `list a b c` can be written as `string join \n a b c` which is longer but more flexible. Closing!

**Comment by krobelus** [comment]
I think it would still be nice to ship `list`, even if it's just an alias to `string join -- \n`
