### ISSUE TITLE
$SHELL should contain the path to fish itself (POSIX compat)

### ISSUE THREAD

**Issue by berdario** [fish-shell/fish-shell#4450]
fish sets the `SHELL` environment variable to `fish`, but [`POSIX` specifies that it should contain the path to the shell, not the executable name](https://unix.stackexchange.com/a/79249)

I know that fish is intentionally non-POSIX, but this small difference causes some [incompatibility with ssh](https://bugzilla.mindrot.org/show_bug.cgi?id=2791)

Do you think this small detail might be adjusted?

old body:

--------------------

Fish 2.6.0 on Macos Sierra

At work we have something like in our /etc/ssh_config

```
Match host *.example.com exec /usr/bin/true
  ProxyCommand /usr/local/bin/ssh-helper %h %p
```

Unfortunately, this always fails with this error, when `SHELL=fish`

    Unable to execute '/usr/bin/true': No such file or directory
    command '/usr/bin/true' exited abnormally
    /etc/ssh_config line 46: match exec '/usr/bin/true' error

**Comment by berdario** [comment]
Nevermind, I realized that this is some old customization that I set up years ago, and that it caused issues only now.

Incidentally, I had to do it, because (unlike bash, afaik) fish doesn't set $SHELL, thus making it awkward when another process wants to fork/drop me in my usual shell

**Comment by krader1961** [comment]
FWIW, neither bash or fish set the SHELL variable. You can prove this for yourself. From a fish shell prompt do this (substitute another shell if you don't have */bin/ksh*):

```
$ set SHELL /bin/ksh
$ bash
bash> echo $SHELL
```

The `$SHELL` variable is supposed to reflect your preferred login shell, not the currently running shell. It's supposed to be set by */bin/login* or a similar program (perhaps your terminal emulator) before the shell is launched.
