### ISSUE TITLE
Move documentation to readthedocs

### ISSUE THREAD

**Issue by ruipacheco** [fish-shell/fish-shell#4453]
Why not move the documentation from the current fish website into readthedocs.org, like most open source projects do? Given how they integrate with GitHub and Bitbucket it should be fairly easy to automate documentation generation.

**Comment by mqudsi** [comment]
> like most open source projects do

Quantifiable statement without citation detected.

**Comment by ruipacheco** [comment]
It's the whole point of readthedocs, to host documentation for FOSS projects, and it does so very well.

**Comment by mqudsi** [comment]
I haven't debated the merits of the proposal with you, but I am pointing out that for a request framed the way yours was, the request itself is incomplete and unconvincing. I've been doing open source for over a decade and I've never come across readthedocs. Your point about "most open source projects" using it is a really big claim that requires similar proof.

You mention how it would be easy to move fish's documentation to readthedocs but you do not mention any of the benefits of such a move. What does readthedocs provide that our current solution doesn't, what paint points does such a move address, what benefits are gained in exchange for lost control and autonomy, increased complexity, etc. what documentation generators are supported by rtd, and so on and so forth.

You are proposing a big change (both technically and from a managerial perspective). Your post should therefore match the gravity of your suggestion.

**Comment by krader1961** [comment]
What @mqudsi said. But I'll also point out that at the moment hosting fish documentation on readthedocs would be difficult because we don't use MarkDown or reStructuredText. Given all the problems we've experienced with Doxygen (c.f., #4016, #4389, and others) the fish team might want to consider reopening issue #980 to switch from Doxygen to Sphinx.

**Comment by zanchey** [comment]
Yeah, I don't think we're going to do this for now - there's a somewhat complex toolchain which generates the documentation, and replacing that is going to take a reasonably large amount of work before we could consider adding external hosting like readthedocs. Thanks for the suggestion though!
