### ISSUE TITLE
Extraneous reference to `fish_update_completions` in FAQ

### ISSUE THREAD

**Issue by iamitava** [fish-shell/fish-shell#4458]
This is an issue with the fish shell FAQ on the website, not fish itself.

The line "Use the fish_update_completions command." appears twice: at the end of the answer to "How do I get the exit status of a command?", and, as the answer to "How do I update man page completions?". The first occurrence is clearly a typo. I'll submit a PR removing it from `doc_src/faq.hdr`.

**Comment by mqudsi** [comment]
I'm presuming this is closed by #4459
