### ISSUE TITLE
OS X builds on Travis are not failing when they should?

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4460]
fish is my first exposure to Travis, so if someone more familiar with it than me could take a look at this:

https://travis-ci.org/fish-shell/fish-shell/builds/284438585

All builds should have failed `make test` since the unit test isn't compatible with the changes from #4407 but the OS X project builds report success:
https://travis-ci.org/fish-shell/fish-shell/jobs/284438589

I'm not sure how long this has been going on.

**Comment by floam** [comment]
The Xcode project does not run `make test` - we have not implemented XCTests.

**Comment by floam** [comment]
Wait a minute, I forgot that we don't use the Xcode project on the Mac VM. It's autotools.

**Comment by zanchey** [comment]
The test ran - but it passed!

**Comment by floam** [comment]
It's pretty strange. If I check out 8ffc3ab242303b9d995a1633c4ba9e55096f29df (the commit before the tests were changed), on macOS High Sierra, the tests fail as expected.

**Comment by floam** [comment]
Basically: no idea what happened.

**Comment by faho** [comment]
I'm declaring it now: It was gremlins.
