### ISSUE TITLE
fish doesn't work properly when using ssh from win10

### ISSUE THREAD

**Issue by shi-yan** [fish-shell/fish-shell#4466]
fish, version 2.5.0-367-g09ce297
2.2.0

xterm

```
Linux 4.10.0-35-generic #39~16.04.1-Ubuntu SMP Wed Sep 13 09:02:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

=====================

I found fish can't work properly if I ssh into my linux (running fish) from a window 10 machine's ubuntu prompt.

specifically, when press up, down, left and right button, fish can't recognize them as navigation command anymore. instead it prints the escaped command.

for example, pressing the up button, I wasn't able to get the previous command. instead I saw "[A" being printed.

**Comment by mqudsi** [comment]
Try upgrading to the latest version of fish; I have no problems SSHing into fish instances from Windows 10. 

Also, what version of Windows 10? Creator's Update introduced many WSL conhost improvements.

**Comment by faho** [comment]
Closing for lack of response. @shi-yan: If you still have this problem with fish 2.7.0, I'll be happy to reopen.
