### ISSUE TITLE
Can't save abbreviations from the web interface

### ISSUE THREAD

**Issue by vvug** [fish-shell/fish-shell#4469]
Steps to reproduce:
- Open a new terminal and run `fish_config`;
- Go to the abbreviations page, modify an abbreviation, click on Save;
- Quit fish_config by hitting `enter` on the terminal where it was started
- Type `abbr`, see how the abbreviation has not been updated;
- Run a new shell (open a new terminal), type `addr`, the abbreviation is still the old one;
- Run `fish_config` again, and again see that the abbreviation has not been saved.

Typing `abbr -a <name> <newcommand>` correctly modifies the abbreviations.

```
~ $ fish --version
fish, version 2.6.0
~ $ echo $TERM
st-256color
~ $ uname -srv
Linux 4.13.0-1-amd64 #1 SMP Debian 4.13.4-1 (2017-10-01)
```

**Comment by ridiculousfish** [comment]
Do you change the abbreviation key or its expansion?

The way that abbreviations are stored has been changed in master. Are you perhaps mixing 2.6.0 and newer sessions?

**Comment by vvug** [comment]
I'm changing its expansion. It could be that I used a newer version in the past (but since then I rebooted several times, so I don't think I'm mixing sessions). I'll try with a pristine `.config/fish/` and eventually close the issue.

**Comment by vvug** [comment]
That was it indeed. Thank you.
