### ISSUE TITLE
fish doesn't seem to support cdable_vars

### ISSUE THREAD

**Issue by David-A-RogersHS2** [fish-shell/fish-shell#4475]
[09:21:17 ~/projects/fish-shell]$fish --version
fish, version 2.6.0
[09:29:10 ~/projects/fish-shell]$echo $version
2.6.0

fish doesn't seem to support cdable vars. So I tweaked cd.fish to add it.  I though you might consider adding it to the project.  I really like cdable_vars much better than CDPATH.  I tried CDPATH for a while under bash and ended up in the wrong directory way too often. But I work in a number of directories with deep paths and cdable vars fill the bill.

The code is simple, but let me know if you'd like me to submit it as a pull request. Just add the following code to the top of cd.fish.

```
    if [ $argv ]; and set -q $argv; and test -d $$argv
        # argv is a non-empty variable and $$argv is a directory
        set argv $$argv
    end

```

**Comment by zanchey** [comment]
To be clear, this allows you to define a variable (say `set fishsrc ~/src/fish-shell`) and then use that as an argument to `cd` (so that `cd fishsrc` changes directory to `~/src/fish-shell`)?

I don't think we'd merge this as-is, because there are too many opportunities for it to cause mayhem.

Abbreviations should solve this use-case in general and even for dynamic values of variables would do the job (eg `abbr -a fishsrc "cd $fishsrc"`).

**Comment by David-A-RogersHS2** [comment]
Yes. That's exactly what it does.  What comes to mind when you think "opportunities for it to cause mayhem"?

I found it useful in bash. And it's really just a typing saver so that you can type `cd kit` instead of `cd $kit`.

It's true that if you have an actual directory 'kit' that you want to cd into, you'd have to type cd ./kit. But that sort of thing happens in CDPATH as well.

My head doesn't like the the abbr solution. I think it's because as soon as I decide I need to go somewhere else I automatically type 'cd'. But I realize that's just me.

Thanks for all those who work on fish. You made something that was easy for me to make work the way I wanted.

**Comment by faho** [comment]
>I found it useful in bash. And it's really just a typing saver so that you can type cd kit instead of cd $kit.

Honestly, that doesn't look like it's worth it to me - it's just a single character. And saving that brings with it more potential for confusion.

>I tried CDPATH for a while under bash and ended up in the wrong directory way too often.

Note that fish's `cd` completions have descriptions if $CDPATH is used. E.g. I have my `~/Videos` directory in there, so when I enter `cd S<TAB>` it'll tell me `Short (CDPATH ~/Videos)`.

(The case where ./Short exists is currently broken in the completions - they'll say "CDPATH ~/Videos", while `cd Short` will actually go to ./Short - I'm about to fix that)

**Comment by faho** [comment]
Alternatively, it might be possible to complete variables whos values exist as directories for cd.

So e.g. `cd <TAB>` would offer `$XDG_CONFIG_HOME`.

**Comment by David-A-RogersHS2** [comment]
I'll give fish's cdpath a try. The completion thing might be useful. It would mean you could add to it to get to directories below the cd variable.

**Comment by David-A-RogersHS2** [comment]
Ok. Tried CDPATH. Two things.

1. I'd really like it to expand the specified path as well as downstream paths. i.e. if I have ~/.config/fish in CDPATH, I'd like it to expand if I type `cd fish<tab>`. Reasoning: If I want to jump to the root of the xxx project, then I have to add `~/projects/` to CDPATH. But that means I'm going to get all my other projects suggested as well - which I don't want.

2. cd will work case independently if you specify from the beginning of the directory i.e. a directory named `Source` can be accessed `cd sour<tab>`. But if you specify from the middle of a directory, you have to enter the correct case. i.e. a directory `DominosKit` cannot be accessed by `cd kit<tab>` but can by entering `cd Kit<tab>`.  Dunno if that's by design, but it'd be nice if the lowercase version worked.

Sorry about the thread drift. Let me know if I should start a new issue for these.

**Comment by zanchey** [comment]
Opportunities for mayhem refers to the fact that if you have a variable that has a directory as its value, it is now suddenly a target for `cd`, which may cause some surprise (especially in scripts).

**Comment by ridiculousfish** [comment]
I think a good option here is to create a special directory, fill it with symlinks whose names correspond to your cd-able variables, then add that directory to your CDPATH. Of course it's also possible to override `cd` if you prefer.

We aren't going to merge this, but thanks for filing and sharing your ideas!

**Comment by David-A-RogersHS2** [comment]
@ridiculousfish Just wanted to say that I got CDPATH set up and the idea about creating a dir with symlinks is a much better solution than what I had. Thanks for suggesting it.
