### ISSUE TITLE
`help SECTION` doesn't work on macOS

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#4480]
On git master on macOS, `help variables` (or any section) no longer takes you to the relevant section. It just takes you to index.html without an anchor.

**Comment by mqudsi** [comment]
(I was probably the last person to touch the help code)

**Comment by mqudsi** [comment]
Works for me on fish 2.6.0-648-g2dd2867

What browser does it launch for you? For me, the `www-browser` path is taken (which is symlink'd to `links`).

**Comment by floam** [comment]
Is this on macOS? It works fine on other platforms or if I force it to use lynx or something. It's something to do with the osascript thing probably.

**Comment by floam** [comment]
Hm - even this doesn't work here (High Sierra): `osascript -e 'open location "file:///usr/local/share/doc/fish/index.html#foo"'` -- the #foo is omitted . I thought `osascript` was the hack around `open` specifically to ensure that the hash symbol makes it through?

**Comment by mqudsi** [comment]
Perhaps it's a High Sierra regression? Apple has never placed a premium on backwards compatibility of applescripting.

**Comment by mqudsi** [comment]
@floam can you please try https://github.com/mqudsi/fish-shell/tree/help_section_workaround

I removed the `osascript` workaround for OS X and instead modified `help` to launch `file.html?section=foo#foo` and added a very simple bit of JS to the bottom of the help file HTML template to jump to the section in question if the fragment were stripped from the URL.

You'll need to rebuild the help docs too.

**Comment by mqudsi** [comment]
_removed regression tag since it does not seem to be an issue with fish but rather a defunct workaround that needs to be updated_

**Comment by floam** [comment]
Sorry I missed this!

**Comment by floam** [comment]
OK, just pulled master, and it doesn't work.

`osascript: file:///usr/local/share/doc/fish/index.html?section=variables#variables: No such file or directory`

**Comment by thomcc** [comment]
Yeah, #4581 doesn't work at all, and completely breaks `help` on macOS, it attempts to pass the URL directly to `osascript`, e.g. the applescript interpereter binary, which is never valid. You probably wanted to use `open`, or `osascript -e 'open location "<url>"'` or something, IDK.

Also, the attempt to work around both of them dropping fragments by using query strings doesn't work at all either, query strings are dropped as well for `file` protocols. (The reason for seems to be that `open` considers this the same as opening the file locally -- e.g. if it's a local  HTML file, it will use whatever application is registered to open that file type, so it's really treating the file URL as if it were the same as a file path)

Anyway, fragments (and queries) work fine when calling `open` on a remote (http/https) url, so you could make mac fail the test [here](https://github.com/fish-shell/fish-shell/blob/master/share/functions/help.fish#L120) and everything would be fine, so long as you replaced `osascript` with either `open` or made it do the `-e "open location ..."` dance.

As far as I can tell, the only way to successfully open a file URL with a fragment/query on mac is by trampolining it, that is, the following works for me 

```
echo '<meta http-equiv="refresh" content="0;URL=\'file:///usr/local/Cellar/fish/HEAD-8a78dca/share/doc/fish/index.html#variables\'" />' > /tmp/test.html
open file:///tmp/test.html
``` 
Certainly is ugly though, and as I mentioned above, the file needs to end in `.html` for `open` to do the right thing, so using mktmp will require some gross munging a la https://github.com/fish-shell/fish-shell/blob/master/share/functions/funced.fish#L76-L77

**Comment by mqudsi** [comment]
> Also, the attempt to work around both of them dropping fragments by using query strings doesn't work at all either, query strings are dropped as well for file protocols. (The reason for seems to be that open considers this the same as opening the file locally -- e.g. if it's a local HTML file, it will use whatever application is registered to open that file type, so it's really treating the file URL as if it were the same as a file path)

I actually never considered the `file:///` case, in my testing the command always loaded the fish website remotely. Thanks for catching that.
