### ISSUE TITLE
Alias support for subcommands

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4482]
Suggestion for fish 3.0: support aliasing `command subcommand` to something

Reason: it'll let you do cool things with git (surprise!) like `alias 'git log' 'git log --name-status'` since there is not yet a git option for `log.nameStatus` or similar.

It would be very straightforward to simply check if `arg == aliased arg` and call the alternative command in its place or else shell out to the actual command.

**Comment by floam** [comment]
Be warned, the standard answer you will get here will be "use an abbr". But this could be useful.

**Comment by mqudsi** [comment]
Thanks @floam. 

The way I view aliases with the same name as an existing command is that they should provide the same service in a compatible fashion, just with added niceties. I like to only use standard tools where possible; I prefer not to grow reliant on custom scripts and wrappers to an extent that I don't know how to live without them.

e.g. `ls` is aliased to `ls --color` on almost all systems. If you go to a machine without that alias, you'll live just fine. 

aliasing `git log` to something entirely different would be a huge no-no for me, but simply enhancing its output to make my life a little easier is something I'm onboard with, yet not something I'd give up the muscle memory of typing `git log` for (e.g. if I created a `git lg` abbreviation).

**Comment by zanchey** [comment]
It's not terribly complex to do that kind of thing with a function:

```fish
function git
    if test -n "$argv[1]"
        switch $argv[1]
            case log
                command git log --graph $argv[2..-1]
            case '*'
                command git $argv[1..-1]
        end
    end
end
```

**Comment by faho** [comment]
Of course, @zanchey's proposal will fail if you have any other argument before the subcommand (e.g. `git -C /some/path log`). To make it bullet-proof, this would require something like `__fish_git_needs_command` in the git completions.

Which goes to show that making this work for arbitrary commands, just via `alias "$command $subcommand"="$command $subcommand $options"` is probably not going to work.

So we could either live with that limitation, or we could ask users to define a function.

Personally, I don't want to expand `alias`. I like it that fish has no special notion of aliases - it's all just functions. So I'd like it if `alias` stays for simple `a=b` type stuff, and functions or abbrs for more complicated things.

**Comment by faho** [comment]
@mqudsi: I don't think this is going to work, so I'm closing this. If you come up with a plan for how to do this, I'd be happy to talk about it. But as it stands, this would require that we do a commands argument parsing for it.
