### ISSUE TITLE
git rm completions do not support file paths

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4485]
```fish
mkdir test
cd test
touch foo
git init .
git add foo
git commit -m "whatever"
git rm <TAB>
```

this results in no completions

**Comment by AlexWayfer** [comment]
When approximately there will be a new release?

**Comment by faho** [comment]
@AlexWayfer: Check [the milestone](https://github.com/fish-shell/fish-shell/milestone/18). 3.0 will be released once those issues are solved.

**Comment by AlexWayfer** [comment]
> @AlexWayfer: Check the milestone. 3.0 will be released once those issues are solved.

Awesome, thanks.
