### ISSUE TITLE
Uninstalling Fish

### ISSUE THREAD

**Issue by ItsPugle** [fish-shell/fish-shell#4486]
I was just wondering how you can completely uninstall fish?

**Comment by mqudsi** [comment]
It depends on how you installed it. If you used a package manager, remove it with the same. If you built it from source, then `sudo make uninstall` will do the trick.

**Comment by ItsPugle** [comment]
Thanks for your help; `brew uninstall fish` did the job :)

**Comment by ronjouch** [comment]
Passersby, note that recent `fish` no longer provides a `make uninstall` rule. You should now follow https://fishshell.com/docs/current/faq.html#uninstalling-fish, which as of today says:

> Should you wish to uninstall fish, first ensure fish is not set as your shell. Run `chsh -s /bin/bash` if you are not sure.
> 
> Next, do the following (assuming fish was installed to /usr/local):
> 
> ```sh
> rm -Rf /usr/local/etc/fish /usr/local/share/fish ~/.config/fish
> rm /usr/local/share/man/man1/fish*.1
> cd /usr/local/bin
> rm -f fish fish_indent
> ```

**Comment by mqudsi** [comment]
When we switched over to CMake, the `Makefile` was rewritten from scratch. I'm not comfortable adding a `Makefile` rule for this without proxying it to CMake, which is the only one that has knowledge of `$PREFIX`. If anyone wants to open a PR with a custom CMake target `uninstall` that does just that, I think it would be OK.

**Comment by zanchey** [comment]
https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake

**Comment by Sunmax5545** [comment]
It's not uninstalling 😩😩
