### ISSUE TITLE
Feature Request: an easy way to run bash commands from within fish

### ISSUE THREAD

**Issue by ndemou** [fish-shell/fish-shell#4488]
I think it would be useful for many fish users to be able to type something like this(note the pipe as the first character):

    |rsync -a a:/fofo ./ && (ls|while read FILE; do mv "file" "file".bak; done)

and have fish call bash -c passing the rest of the line (after the  pipe) exactly as it is to bash for execution.

**Rationale:**

It's all too common to want to run a semi-complex to complex bash command (e.g. while copying from a how to). You can use `bash -c bash-command` but if the command has quotes and special symbols like the above example you have to pay attention to proper quoting. Proper quoting is not fun to do and if the bash command uses both single and double quotes it's painful. Opening a bash subshell has it's own set of problems (a major one is that you don't have a nice history of the commands you've entered in one place).

P.S.
Thanks for all the fish! I enjoy it.

**Comment by faho** [comment]
>You can use bash -c bash-command but if the command has quotes and special symbols like the above example you have to pay attention to proper quoting. 

Nope, you don't.

If the cursor is inside single-quotes, fish will escape any pasted text so that you can just close the quote again and use it as a single token.

E.g. type `bash -c '`, then paste your code and type another `'`. Any `'` and `\` inside your pasted text should be escaped.

**Comment by mqudsi** [comment]
In a perfect world, this would work admirably:

```fish
function b
    bash -c (read)
end
```

Alas, due to broken function redirections, it won't.

**Comment by faho** [comment]
@ndemou: Does our special paste support work for you?

**Comment by ndemou** [comment]
@faho: Yes it does! Nice trick.

**Comment by faho** [comment]
In that case, there's no need to implement this.

**Comment by okovalov** [comment]
@faho I was trying to run it using `bash -c '....'` having it escaped , but it did not work.. here is the command
```bash
git branch -r | awk '{print $1}' | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk '{print $1}' | xargs git branch -d
```

and here is how I ran it

```fish
 bash -c ' git fetch --prune; git branch -r | awk \'{print }\' | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk \'{print }\' | xargs git branch -d '
```

and here is the output of the command

```
error: branch '*' not found.
error: Cannot delete branch 'master' checked out at '/Users/okovalov/prj/OneLedger/ons-ui-electron'
error: branch '2edf6ab' not found.
error: branch '[origin/master]' not found.
error: branch 'Merge' not found.
error: branch 'pull' not found.
error: branch 'request' not found.
error: branch '#50' not found.
error: branch 'from' not found.
error: branch 'XXX/OLP_494_eth_poc' not found.
```

what I did wrong? thank you

**Comment by faho** [comment]
@okovalov: Apparently you didn't copy the `$1`?

**Comment by okovalov** [comment]
@faho I did actually. it was dropped from the output automatically , and I have not noticed it right away. so to fix it I had to escape the `$` as well, so for anyone else who would need that in the future, here is the working code
```fish
abbr -a gclean "bash -c 'git fetch --prune; git branch -r | awk \'{print \$1}\' | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk \'{print \$1}\' | xargs git branch -d'"
```

and to answer you question, - I did copied it, but I had to escape it , to make sure it is properly processed

**Comment by faho** [comment]
@okovalov So the issue there is that you're *double*-quoting - the outer quotes are `"`, not `'`, so the `$1` is expanded as a variable. And since that variable probably isn't defined it ends up as `awk \'{print }\'` in the defined abbr.

**Comment by okovalov** [comment]
@faho hm.. not sure what do you mean by double quoting here.. but , anyhow, as I have said - I figured out a working abbreviation

```
abbr -a gclean "bash -c 'git fetch --prune; git branch -r | awk \'{print \$1}\' | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk \'{print \$1}\' | xargs git branch -d'"

```
and it works just perfectly fine. 
thank you though!

**Comment by aneeshdurg** [comment]
He meant using ' (single quote) vs (") double quote. Expansion in strings works differently depending on which quote you use in fish.

**Comment by jffiorillo** [comment]
What are the difference between ' (single quote) vs " (double quotes)? regarding expansion in String for fish?

Thanks

**Comment by faho** [comment]
@jffiorillo http://fishshell.com/docs/current/index.html#quotes:

>Sometimes features such as parameter expansion and character escapes get in the way. When that happens, the user can write a parameter within quotes, either ‘’(single quote) or"(double quote). There is one important difference between single quoted and double quoted strings: When using double quoted string, variable expansion still takes place. Other than that, no other kind of expansion (including brace expansion and parameter expansion) will take place, the parameter may contain spaces, and escape sequences are ignored.

I recommend you open another issue or ask on https://gitter.im/fish-shell/fish-shell instead of on closed issues.

**Comment by jffiorillo** [comment]
Great, thank you @faho
