### ISSUE TITLE
Tokenization of single quoted double backslash eats backslash

### ISSUE THREAD

**Issue by externl** [fish-shell/fish-shell#4489]
```
$ fish -v
fish, version 2.6.0
```
```
$ echo $TERM
xterm-256color
```
> Please tell us if you tried fish without third-party customizations

yes 

----
While trying to parse compare the output of `commandline --tokenize` with output of `commandline --current-buffer` I was confused with the handling of `\\`.

Consider a command line with the following:
```
 echo '\\' '\\n' '\n' '\t'
```

It produces the following output / tokens if you run:

```
\ \n \n \t 
```

Shouldn't `\\` be treated like other escape sequences inside single quotes? I was unable to find anything in the documentation addressing double vs single quote escape sequences.

Bash and ZSH behave equally differently behavior:

```
bash-4.4$ echo "\n \\"
\n \
bash-4.4$ echo '\n \\'
\n \\
```

```
zsh-5.4.2$ echo '\\ \n'
\

zsh-5.4.2$ echo "\\ \n"
\
```

Thoughts, maybe I'm missing something?

**Comment by ridiculousfish** [comment]
[The docs do address this](https://fishshell.com/docs/current/index.html#quotes): "The only backslash escape accepted within single quotes is \', which escapes a single quote and \\, which escapes the backslash symbol."

None of the control-style escapes like \n are active within any quotes in fish. This may be surprising coming from other shells, but it's nice to have a nearly raw-style string form. It's also quite established, so not something we can change.

Hope that clears things up, thanks for filing this!f

**Comment by externl** [comment]
Thanks, @ridiculousfish!
