### ISSUE TITLE
Replace `read -i` with `read -s`

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4490]
`read`'s support for `--silent` [came late in the game](https://github.com/fish-shell/fish-shell/issues/838) and `-s` was already being used for `--shell`.

How does everyone feel about making `-s` for `--silent/--secure` similar to bash and others, and changing `--shell` to something else? It seems the only place `read -s` is currently used in our code is just in `funced.fish`.

**Comment by ridiculousfish** [comment]
This makes sense to me. Maybe `-i/--interactive` for the existing `--shell` behavior.

**Comment by faho** [comment]
`-i` sounds nice, but if we used something else, we could add it to 2.7.0 for a nicer upgrade path in case anyone uses `--shell`.

So just `-S` for `--shell`?

**Comment by ridiculousfish** [comment]
I like the `-S/--shell` idea.

**Comment by cben** [comment]
another option is leave `--shell` without a short option.
