### ISSUE TITLE
How to manually modify my shell initialization file?

### ISSUE THREAD

**Issue by lomoY** [fish-shell/fish-shell#4496]
I use fish to install n, the node version manager,.
the run the following command: 

```
npm install -g n
sudo rm -rf /usr/local/lib/node_modules
sudo rm -rf /usr/lib/node_modules
curl -L -o /tmp/n-install-script https://git.io/n-install
bash /tmp/n-install-script -y
```

after the finish the last command, I got this information:

```
-- Cloning https://github.com/tj/n to '/Users/Lomo/n/n/.repo'...
-- Running local n installation to '/Users/Lomo/n/bin'...
n-install: WARNING:
  Automatic modification of the initialization file for shell
  /usr/local/bin/fish is not supported.
  For n and the Node.js versions managed by it to work correctly,
  you must MANUALLY ADD THE EQUIVALENT OF THE FOLLOWING TO YOUR SHELL'S
  INITIALIZATION FILE:

  export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  # Added by n-install (see http://git.io/n-install-repo).
-- Shell initialization file '' updated.
-- Installing helper scripts in '/Users/Lomo/n/bin'...
-- Installing the requested Node.js version(s)...
   1 of 1: stable...

     install : node-v8.6.0
       mkdir : /Users/Lomo/n/n/versions/node/8.6.0
       fetch : https://nodejs.org/dist/v8.6.0/node-v8.6.0-darwin-x64.tar.gz
######################################################################## 100.0%
   installed : v8.6.0

=== n successfully installed.
  The active Node.js version is: v8.6.0

  Run `n -h` for help.
  To update n later, run `n-update`.
  To uninstall, run `n-uninstall`.

  IMPORTANT: Modify your shell initialization file as described above
             before using n and Node.js.
===
```
I know little about shell tools, after this, I need to run: `exec $SHELL # To re-initialize the PATH variable` , since variables may not be used as commands in fish, and I made a mistake!! **I changed my shell from fish to bash!! And change it back to fish after doing nothing with bash...**
Then, the problem is coming, when I run: `n -v` it said '`fish: Unknown command 'n'`'. However, n is valid before I did the 'shell changing' things, so how can I make it like before?

the second question is, how to
 ```
MANUALLY ADD THE EQUIVALENT OF THE FOLLOWING TO MY SHELL'S
  INITIALIZATION FILE:

  export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  

```

**Comment by lomoY** [comment]
I am new to coding, and know little about shell, forgive me if my question is stupid.

**Comment by lomoY** [comment]
I run the command follow the [this tutorial](http://steelbrain.me/2016/07/19/how-i-manage-multiple-node-js-versions.html)

**Comment by zanchey** [comment]
Instead of manually adding the equivalent of that code to your fish configuration file, I suggest running this command once:

```
set -U fish_user_paths $HOME/n fish_user_paths
```

That will add the path to all current and running shells, which has the same effect as the gnarly code suggested for your initialization file.

**Comment by mvolkmann** [comment]
A reason that I typically prefer modifying PATH inside ~/.config/config.fish instead of setting fish_user_path in a terminal is that I periodically need to setup a new computer with the same configuration as my primary computer. It's nice to able to just copy ~/.config/config.fish to the new computer.

**Comment by zanchey** [comment]
@lomoY, has this solved your question?

**Comment by faho** [comment]
I'm assuming this question has been answered.

**Comment by mrchief** [comment]
This hasn't been answered, especially this part: 

> MANUALLY ADD THE EQUIVALENT OF THE FOLLOWING TO MY SHELL'S
>  INITIALIZATION FILE:
> 
>  export N_PREFIX="$HOME/n"; [[ :$PATH: == *":$N_PREFIX/bin:"* ]] || PATH+=":$N_PREFIX/bin"  
> 

I believe the `config.fish` equivalent would be something like:

```
set -x N_PREFIX "$HOME/n"    # equivalent of export N_PREFIX="$HOME/n";

if not contains -- $N_PREFIX/bin $PATH
  set PATH $PATH $N_PREFIX/bin
end

```

I'm not an expert on bash, much less fish but this is what I gathered from the docs and it seems to work on my mac so :man_shrugging:

**Comment by ezalivadnyi** [comment]
> This hasn't been answered, especially this part:
> 
> > MANUALLY ADD THE EQUIVALENT OF THE FOLLOWING TO MY SHELL'S
> > INITIALIZATION FILE:
> > export N_PREFIX="$HOME/n"; [[ :$PATH: == _":$N_PREFIX/bin:"_ ]] || PATH+=":$N_PREFIX/bin"
> 
> I believe the `config.fish` equivalent would be something like:
> 
> ```
> set -x N_PREFIX "$HOME/n"    # equivalent of export N_PREFIX="$HOME/n";
> 
> if not contains -- $N_PREFIX/bin $PATH
>   set PATH $PATH $N_PREFIX/bin
> end
> ```
> I'm not an expert on bash, much less fish but this is what I gathered from the docs and it seems to work on my mac so

Thanks, this help me in Linux Mint 19.1
