### ISSUE TITLE
Missing `-l` option when pressing tab after `chsh -`

### ISSUE THREAD

**Issue by BruceChen2017** [fish-shell/fish-shell#4497]
fish, version 2.3.1 on fedora 26
```
> chsh -[tab]
output: --help  -u  (Display help and exit)  --shell  -s  (Specify your login shell)  --version  -v  (Display version and exit)
```

**Comment by ridiculousfish** [comment]
Looks like `-l` is a macOS-ism. Feel free to add it to `share/completions/chsh.fish` if you want, but we'll have to ensure it's only on Mac.

**Comment by ridiculousfish** [comment]
I'm going to close because I don't think it's worth tracking this, but we'll take a PR if you want to do the work. Thanks for filing it!

**Comment by BruceChen2017** [comment]
@ridiculousfish  I have fixed this! Just add   
`complete -c chsh -s l -l list-shells --description 'Print the list of shells listed in  /etc/shells and exit.'` to `/usr/share/fish/completions/chsh.fish`.  
Thanks!

**Comment by ridiculousfish** [comment]
@BruceChen2017 thanks, but the annoying part is that option is only on macOS. So you will have to add a `uname` check that this is running on macOS.

**Comment by faho** [comment]
>the annoying part is that option is only on macOS.

That's not actually true.

It's even more convoluted than that.

util-linux's chsh [has -l](https://linux.die.net/man/1/chsh), and it is the same as "--list-shells". 

Ubuntu uses chsh from passwd, and it apparently [does not have -l](http://manpages.ubuntu.com/manpages/artful/en/man1/chsh.1.html).

FreeBSD's chsh [has -l if compiled with NIS support](https://www.unix.com/man-page/FreeBSD/1/chsh/) which appears to stand for "local".

macOS's chsh [has -l](https://www.unix.com/man-page/osx/1/chsh/), and it stands for "location" (and requires an argument).

For the latter two, I'm not even sure it does anything sensible with chsh - it appears to be an artifact of these only having a "chpass" utility to change more than the user's shell, and "chsh" as an alternative name for that.

So, what we'd need to do:

- Check for util-linux chsh, ignoring passwd chsh (possibly via "--version")

- Check for FreeBSD's chsh with NIS support (no idea how to do that)

- Check for macOS's chsh (or just macOS)
