### ISSUE TITLE
Change in status output

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#4499]
While preparing the 2.7b1 changelog, I've noticed the following differences between 2.6.0 and the current Integration_2.7.0 branch:

```patch
--- 2.6.0       2017-10-22 22:14:41.603032031 +0800
+++ head        2017-10-22 22:14:37.247231712 +0800
@@ -1,4 +1,4 @@
 > status current-filename
-Standard input
+stdin
 > status current-function
-Not a function
+N/A
```

Unless there's a clear rationale for the change, I'd like to set it back to how it was.

**Comment by floam** [comment]
Yick, yeah, the prior strings were way better. When did they change?

**Comment by ridiculousfish** [comment]
Looks like 30368d5526d591df44127624f5c92c6b2a43c0d3 . +1 for changing them back.

**Comment by zanchey** [comment]
On further thought, these strings are translated - so them being unstable might be ok as they shouldn't be relied upon anyway.

**Comment by zanchey** [comment]
Cherry-picked into 2.7.0 as f9eb826d.
