### ISSUE TITLE
Consider integrate with cdargs

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#45]
This issue tracks considering integrating with cdargs.

Pierre Baillet writes:

"Hello,

Fish looks nice and sweet. I hope it will succeed in changing the shell landscape for ever :).

I've just written a function file for cdargs the directory alias manager, aliases for cv and ca and supports completion for the cv command.

Available here:

https://gist.github.com/2881699

Cheers,
"

Here is the code:

function ca
  command cdargs --add=":$argv:$PWD"
end
function cv
  cdargs "$argv"; and cd (cat "$HOME/.cdargsresult")
end

function _cdargs_completion
  cat ~/.cdargs | cut -d' ' -f1 | xargs echo
end

**Comment by anordal** [comment]
I have this alternative: https://github.com/anordal/reljump.fish

**Comment by krader1961** [comment]
FWIW, I am not using either at this time but from the documentation I prefer @anordal's [reljump solution](https://github.com/anordal/reljump.fish) over [cdargs](https://gist.github.com/2881699). I was considering adding a more limited version of either implementation to my [`mcd`](https://github.com/fish-shell/fish-shell/issues/2847) command but will instead ponder how to integrate @anordal's reljump implementation.

**Comment by krader1961** [comment]
Closing since this is now very old and no one has been motivated to implement it. It's also trivial to support which means there isn't a compelling reason to ship support for cdargs with fish. And there are other alternatives, like reljump, which seem superior.
