### ISSUE TITLE
tparm_solaris_kludge is wrong

### ISSUE THREAD

**Issue by nbuwe** [fish-shell/fish-shell#4502]
From source code inspection after trying to build on NetBSD.

NetBSD by default uses X/Open `tparm`(3) with fixed number of arguments.  This makes fish use tparm kludge, which, unfortunately, is buggy.  Visually this manifests as broken completion display.

The problem is that `tparm_solaris_kludge` is indeed a horrible kludge that explicitly checks for a number of capabilities.  `parm_left_cursor` is not one of them, so when screen.cpp uses it to move cursor back after displaying a completion, nothing happens as the parameter (number of columns) is not passed to the real `tparm`.

Since you are using C++ what the kludge should actually do is to define a function with the same signature as fixed-arg `tparm` but with default values for the parameters that just calls real `tparm`.

**Comment by ridiculousfish** [comment]
Yeah, that's a pretty gross kludge all right... The fix sounds fine if you want to do a PR, otherwise I can take a whack at it later. Either way thanks for filing!

**Comment by nbuwe** [comment]
Do patches still exist in this brave new world?

I'd rather avoid the hassle of a pull request song and dance.

[http://www.stderr.spb.ru/~uwe/fish-tparm.diff](url)  - I had to manually edit it, b/c I had const char there to build on netbsd.   I hope I didn't mess the patch with that, but anyway it should be obvious what's going on here.

Hope it helps.

**Comment by floam** [comment]
Sure, git can import unified diff patches just fine, we're happy to take them.

**Comment by floam** [comment]
Something about your markdown messed up the URL above. Inside `[` and `]` should be a description or name of some sort, the `(url)` part should contain an actual URL.

**Comment by floam** [comment]
And basically looks good to me.

**Comment by zanchey** [comment]
Committed as 8f0f05ca although perhaps it would be better to convince NetBSD to compile against the varargs prototypes instead? See #969.

**Comment by nbuwe** [comment]
NetBSD exposes variadic prototype when `TPARM_VARARGS` is defined.

https://github.com/NetBSD/src/blob/c434ab62b670194bcb13938171da847b7fac86d7/lib/libterminfo/term.h#L1991-L1995
