### ISSUE TITLE
Implement `history insert`

### ISSUE THREAD

**Issue by admirabilis** [fish-shell/fish-shell#4506]
I have created two functions that would be interesting to have ported as plugins. One is a precision calculator directly from the prompt (ex. running `3*(1/2)` returns `1.5` instead of expanding globbing and command substitution, and the other runs [thefuck](https://github.com/nvbn/thefuck) automatically on the fish_command_not_found event.

Now, both of them write to the history file, and would benefit greatly from a `history insert` command. I'm currently using the following:

    if set -q XDG_DATA_HOME
        set __fish_history $XDG_DATA_HOME/fish/fish_history
    else
        set __fish_history ~/.local/share/fish/fish_history
    end

    echo -e '- cmd: '(commandline)'\n  when: '(date +%s) >>$__fish_history
    history --merge

The problem with this approach is that `commandline` is written to the history file as is (without considering newlines, without escaping special characters, etc.) and, of course, `history --merge` brings the undesired side-effect of merging history from all other sessions.

**Comment by ridiculousfish** [comment]
`history push` sounds OK to me if you want to do it!

**Comment by mqudsi** [comment]
Note that writing directly to the history file should not be done. We obtain a lock in the C++ code any time we write to it to prevent cross-thread/process corruption of the history file.

The only way this could be done without C++ code _somewhere_ would be if we switched the history file lock to `flock`, which I would personally be averse to.

**Comment by zanchey** [comment]
The history file does lock with `flock`, although it doesn't try very hard (and is particularly unreliable on NFS, and also is implemented in terms of `fcntl` on systems without `flock`).

**Comment by mqudsi** [comment]
Awesome, I should have checked instead of presuming it was a mutex. Thank you!
