### ISSUE TITLE
fish_key_reader doesn't build from Xcode on 2.7b1

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#4510]
The Xcode package build fails with 2.7b1 because `fish_key_reader` won't link:

```
Undefined symbols for architecture x86_64:
  "builtin_argparse(parser_t&, io_streams_t&, wchar_t**)", referenced from:
      builtin_datas in builtin.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

As a result there are no macOS packages for 2.7b1.

`xcodebuild` is not enough to reproduce this, but building fish.app from within Xcode will produce the error.

**Comment by ridiculousfish** [comment]
Sorry for the delay. Looks like this has been fixed in master but I pushed a fix to Integration 2.7.0 as 8dc26ba8b992cf55ece212b9104831034435ebff
