### ISSUE TITLE
Namespace idea

### ISSUE THREAD

**Issue by xiaq** [fish-shell/fish-shell#453]
Let's add some namespacing mechanism to fish. The idea:
- Namespacing is supported in both function namespace (holding builtins and functions) and variable namespace. The namespace delimiter is `:`.
  - Rationale for `:`: Traditionally namespaces are delimited either by `.` or `::`. `.` delimits filename extensions, so that can be a visual burden if used also as namespace delimiter in shells. It also appear in names of some external commands (I believe there are commands called `foo.py`, but I can't recall one) which messes namespace up. `::` looks good but is too long.
- In addition to autoload functions, there are autoload _modules_, whose filenames look like `namespace:.fish`. Modules reside in `$fish_function_path` too (subject to change).
- Bare names within modules are decorated with `namespace:` when accessed outside the module. Say I have the following in `foo:.fish`:
  
  ```
  set var 'Hahaha'
  function func
  echo $var
  end
  ```
  
  Outside `foo:.fish` I access the variable `var` as `foo:var`, and function `func` as `foo:func`.
- Scoping rules still need some thoughts; Python's [local-global-builtin rule](http://docs.python.org/2.7/tutorial/classes.html#python-scopes-and-namespaces) looks like a good starting point.

**Comment by nixpulvis** [comment]
As I've been updating the structure of my dotfiles this is something I've found myself wanting badly. The ability to use modules (namespaces) as a means of both organization and system cohesion would be nice. I use the same set of dot files across both Linux and macOS.

As a small note I'd be in favor of `::` as the delimiter, coming from languages like Rust, Ruby, and C++.

**Comment by krader1961** [comment]
The devs talked about this some more. It's pretty clear this will never be implemented unless a company adopts fish and assigns a team of SWEs to work on it full time.
