### ISSUE TITLE
Autocompletion overwrites previous output in Terminal.app

### ISSUE THREAD

**Issue by elmigranto** [fish-shell/fish-shell#4532]
*Thank you everyone who works on fish, this is most sane shell which finally got me to script stuff* ❤️

**What's Wrong**

When I hit <kbd>TAB</kbd>, if autocomplete stuff "does not fit" (e.g. more lines than left in terminal viewport), it overwrites stuff from first line, not the line where cursor was. Same behaviour in folowing situations as well:

  - right after `brew install fish`;
  - with `sh -c 'env HOME=$(mktemp -d) fish'` after some customization (mostly functions and env exports);
  - on a fresh ubuntu mini install (I sshed from Terminal.app and installed fish from [your PPA](https://github.com/fish-shell/fish-shell#packages-for-linux)).

<hr/>

**Terminal.app**

I expect this to be an issue with Termnial.app, maybe I have to toggle some setting? I tried guessing and was toggling *Paste newlines as carriage returns* with no success. Here are what I currently have:

<details>
<summary>Screenshots of my Terminal.app settings</summary>
<img width="779" alt="screenshot 2017-11-10 20 49 00" src="https://user-images.githubusercontent.com/886388/32666254-a6d47746-c658-11e7-9e8c-1c07f93d99a6.png">

<img width="779" alt="screenshot 2017-11-10 20 48 38" src="https://user-images.githubusercontent.com/886388/32666265-b2b64422-c658-11e7-92b5-2edbbee2b2e4.png">
</details>
<hr/>

**Video**

Idk how better explain, so here's a video:

https://youtu.be/qb-3042lXO0

<hr/>

**Versions**

``` sh
# fish --version; and echo $version
fish, version 2.6.0
2.6.0

# fish was instealld from brew, so maybe this helps as well
# brew info fish
fish: stable 2.6.0 (bottled)
Poured from bottle on 2017-11-08 at 17:21:24

# uname -a
Darwin elmacbook 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64

# TERM stuff from env
TERM=ansi
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=400
```

**Comment by elmigranto** [comment]
Shell loaded:

<img width="660" alt="screenshot 2017-11-10 20 56 37" src="https://user-images.githubusercontent.com/886388/32666583-b542e80c-c659-11e7-9102-44531539f798.png">

I type `git`, <kbd>Space</kbd>, <kbd>Tab</kbd>, <kbd>Tab</kbd>, <kbd>Tab</kbd>, <kbd>Control</kbd> + <kbd>C</kbd> right after:

<img width="713" alt="screenshot 2017-11-10 20 57 30" src="https://user-images.githubusercontent.com/886388/32666614-cbe5d60a-c659-11e7-837b-295eee6de8bf.png">

**Comment by floam** [comment]
Why are you setting your terminal as `ansi`? What happens if you use `xterm-256color`?

**Comment by elmigranto** [comment]
Oh my, thanks, @floam. (Guess I accidentally scrolled it from default).
