### ISSUE TITLE
read builtin doesn't support backspace, C-W, C-U when used in fish_greeting

### ISSUE THREAD

**Issue by amarqueslee** [fish-shell/fish-shell#4533]
```
dre@eldin ~ >><((('> fish --version
fish, version 2.6.0
dre@eldin ~ >><((('> echo $TERM
xterm-256color
dre@eldin ~ >><((('> uname -a
Linux eldin 4.4.0-53-generic #74-Ubuntu SMP Fri Dec 2 15:59:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

I'm actually using Linux Mint 18.1 Serena (MATE edition), if that matters at all. My terminal emulator is indeed `xterm`. Today I discovered this bug on both on the Mint-provided v2.2.0 and PPA-provided v2.6.0 versions of `fish`.

Essentially, it seems that the `read` builtin, when used as part of a `fish_greeting`, doesn't seem to support backspace, Ctrl-W, or Ctrl-U. Printable characters appear to work as expected.

My `fish.config`:

```
dre@eldin ~/.c/fish >><((('> cat config.fish 

# look in install dirs for executables
set -x PATH "$HOME/install/bin" $PATH

# set vim as editor
set -x EDITOR vim

#.net core stuff
set -x DOTNET_CLI_TELEMETRY_OPTOUT 1
set -x ASPNETCORE_ENVIRONMENT "Development"

# fix HOSTNAME to work like in bash
set -g HOSTNAME (hostname|cut -d . -f 1)

#disable fish greeting (reset as a function for interactive shells)
set -x fish_greeting ""
```

And my smallest illustrative `fish_greeting`:

```
dre@eldin ~/.c/fish >><((('> cat functions/fish_greeting.fish 
function fish_greeting
  read foo
end
```

So far I'm really enjoying scripting with fish, and as such I'd love to be able to get it to do more of the heavy lifting when I log in for the day and open up a terminal. Thanks in advance to the community for any bug fixes/suggested workarounds that you can offer in response to this.

**Comment by faho** [comment]
This happens because `fish_greeting` is executed before the keybindings are defined. It would be easy enough to change.

However: Why are you trying to `read` there? What are you actually trying to accomplish?

**Comment by amarqueslee** [comment]
Well, to be honest, in my case I’d like to prompt myself once a day for my 3 goals for the day.

fish_greeting seemed like a quick-and-easy way to confront myself with that and make sure I don’t forget.

**Comment by ridiculousfish** [comment]
This can be done with `fish_preexec`:

    function prompt_me --on-event fish_preexec
       read -p "echo 'How are things? '" res
       functions --erase prompt_me
    end

I don't think it's worth changing the order of `fish_greeting` at this point. Thanks for filing though!

**Comment by amarqueslee** [comment]
@ridiculousfish and @faho, thanks for taking some time to look at this.

I would not protest at a viable workaround in lieu of changing the order of `fish_greeting`. The one suggested above seems like a reasonable workaround to me in theory.

However, I must report that I was unable to get the example to work on fish 2.6.0.

If I place the above code snippet in a file `~/.config/fish/functions/prompt_me.fish`, then `prompt_me` only executes once I explicitly call it (and only once, as I would expect looking at the `functions --erase` invocation).

More interestingly, if I paste the function directly into `~/.config/fish/config.fish`, it executes, but only once I write my first command or hit enter.

The second alternative is not ideal but possibly workable. Perhaps I have misunderstood your suggestion? Might there be anything else I can do to get it to work better?

Thanks again to both for your assistance.

**Comment by amarqueslee** [comment]
So... I just discovered a potential workaround by modifying my `fish_prompt`:

```
function fish_prompt --description 'Write out the prompt'

  if not set -q _first_prompt
    set -g _first_prompt
    read -p "echo 'How are things? '" res
  end
  #etc
end
```

I'm a bit concerned about doing it this way in case I'm breaking something else, but... it seems to work so far...?
