### ISSUE TITLE
Tab completion and .ssh/config problem

### ISSUE THREAD

**Issue by dcpc007** [fish-shell/fish-shell#4536]
fish, version 2.6.0
CentOS release 6.9 (Final)
No config (first test)

I use .ssh/config file for host and user aliases like : 
Host vldtest
        Hostname vld-test
        User toto

in Fish, when i type "ssh vldte", it shows the end and a <right arrow> + <enter> works as expected.
But, if i type "ssh vld" and tab-tab to show all, it add a '-' and show me a liste of full hostname only, without my aliases. and then try to connect with current user if i do enter.

More, if i type "ssh vldt", he shows me "vldtest" in possible completion, but hit tab shows me vld-<many values>
<many-values> = "vld-" + many hostnames even starting with other than T letter. Not sure but maybe alist like "vld-*t*" ... but no vldtest from .ssh/config in the list.

Is there a specific config to have this ? (In bash_completion, i got the 2 possibilities after "ssh vld" + tab : vld-test and vldtest)

**Comment by ridiculousfish** [comment]
Thanks for filing. I wasn't able to reproduce this with your sample .ssh/config. What does `__fish_print_hostnames` have - does it contain both `vldtest` and `vld-test`?

**Comment by dcpc007** [comment]
Scuse, miss the notification ...
yes it has both
Note : i reboot and no problem now ... i don't remember if i got an update ... but i don't modifiy anything, i had not use fish the 15 last days.
Now vld + tab tab guive all vld* and vld-* (
In fact in my.ssh/config i alias server names to remove the "-" and sometimes do a real alias (like adm for my admin node)

**Comment by dcpc007** [comment]
i close. The problem not reproducible.
