### ISSUE TITLE
Using empty string variables can interfere with commands execution.

### ISSUE THREAD

**Issue by llde** [fish-shell/fish-shell#4538]
Hi sorry if this issue was already reported or is not a bug.

I'm trying to port archiso building script form bash to fish. I'm current  the mantainer of Architect Linux (an AIF based installer for archlinux). My plan is to port the entire installer to fish as bash is truly horrible.

The script define an empty variable with `set verbose ""` . This variable is supposed to hold "-v" param if the script is executed with the verbose option, and it's optionally setted in a conditional block currently commented.

I have then multiple lines with mkarchiso command invoked. For example:

```
setarch $arch mkarchiso $verbose -w "$work_dir/$arch" -C "$pacman_conf" -D "$install_dir"  init
```
(If I remove setarch $arch is the same)

The command fail with the message:
```
[mkarchiso] ERROR: Invalid command name ' '
```

If I remove $verbose or define it as set verbose "-v" the command work.

Used fish version : fish, version 2.6.0
OS: Archlinux x86_64
Kernel: Linux  4.13.11-1-covolunablu-gaming #3 SMP PREEMPT Fri Nov 3 14:24:53 CET 2017 x86_64 GNU/Linux
Terminal: Terminology

**Comment by floam** [comment]
Try double-quoting the variable, eg. `"$verbose"`.

**Comment by llde** [comment]
Thanks it works. Shouldn't this use case be better documented?

**Comment by ridiculousfish** [comment]
Thanks for filing. We have pretty good docs around variable expansion [here](http://fishshell.com/docs/current/index.html#variables) but it can always be better. If there's particular language that would have helped you, please write it or open a PR, for the next person with the same question!
