### ISSUE TITLE
cannot make two read in script

### ISSUE THREAD

**Issue by Estirp** [fish-shell/fish-shell#4541]
fish, version 2.6.0
Linux localhost 4.13.11-1-ARCH #1 SMP PREEMPT Thu Nov 2 10:25:56 CET 2017 x86_64 GNU/Linux
xterm

> cat bug 
#!/bin/fish
read
read
> ./bug 
read> (press enter)
<E> fish: src/reader.cpp:1559: failed assertion: input_initialized
<E> fish: Backtrace:
<E> fish: 0   reader_push(wchar_t const*) + 1964
<E> fish: 1   /bin/fish() [0x436ac5]
<E> fish: 2   builtin_run(parser_t&, wchar_t const* const*, io_streams_t&) + 256
<E> fish: 3   exec_job(parser_t&, job_t*) + 1427
<E> fish: 4   parse_execution_context_t::run_1_job(parse_node_t const&, block_t const*) + 1230
<E> fish: 5   parse_execution_context_t::run_job_list(parse_node_t const&, block_t const*) + 174
<E> fish: 6   parse_execution_context_t::eval_node_at_offset(unsigned int, block_t const*, io_chain_t const&) + 1680
<E> fish: 7   parser_t::eval_block_node(unsigned int, io_chain_t const&, block_type_t) + 242
<E> fish: 8   parser_t::eval(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&, io_chain_t const&, block_type_t, parse_node_tree_t) + 533
<E> fish: 9   /bin/fish() [0x4c4e09]
<E> fish: 10  reader_read(int, io_chain_t const&) + 1130
<E> fish: 11  main + 2717
<E> fish: 12  __libc_start_main + 234
<E> fish: 13  _start + 42
fish: './bug' terminated by signal SIGABRT (Abandon)

I think it is self explanatory.

Maybe related to #4199

**Comment by ridiculousfish** [comment]
This bisects to 71af1a95663cf616150c0422e8d2d0ddfaa56296 which was fixed in 2.7.0. Thanks for filing!
