### ISSUE TITLE
Add support for recovery of stale mount-points to cd.fish

### ISSUE THREAD

**Issue by wilhelmy** [fish-shell/fish-shell#4543]
I propose the following change for cd.fish:

```
--- /usr/share/fish/functions/cd.fish	2017-10-12 08:34:42.000000000 +0200
+++ .config/fish/functions/cd.fish	2017-11-19 02:08:40.773047643 +0100
@@ -27,6 +25,12 @@
         return $status
     end
 
+    # allow explicit "cd ." if the mount-point became stale in the meantime
+    if test "$argv" = "."
+	cd "$PWD"
+	return $status
+    end
+
     builtin cd $argv
     set -l cd_status $status
```

which can help recycling windows where the mountpoint has disappeared and reappeared since. (e.g. stale sshfs mountpoint, which becomes unreachable in case you suspend your machine, which you can recover by rerunning sshfs and then doing another "cd ." in all affected fish shells.)

**Comment by ridiculousfish** [comment]
cd is certainly not the right place to fix this, but this fix makes this slightly less annoying in the meantime.

**Comment by zanchey** [comment]
I've added this with some documentation in 9afc4b41.
