### ISSUE TITLE
document $fish_color_selection

### ISSUE THREAD

**Issue by nhooyr** [fish-shell/fish-shell#4544]
I believe this is the colour for selections made in vi mode.

I cannot find any documentation on it though.

**Comment by ridiculousfish** [comment]
That's right, it's used for selections in visual mode. easy fix if someone wants to do it.

**Comment by mohamadLy** [comment]
I can take it, if it's alright with you.

**Comment by nhooyr** [comment]
Sounds good to me.

**Comment by mohamadLy** [comment]
Sorry for my ignorance, it's my first time trying to contribute. I did not fully understand what $fish_color_selection command does. nhooyr said "it is colour for selections made in vi mode" but I am still not getting it. 

I have changed the value of $fish_color_selection to be red, and I've switched to to visual mode in vi mode for selection purposes. For me the selected text should be redrawn to red. But it is not, it is always in white. See picture attached.
![fish_color_selection](https://user-images.githubusercontent.com/9387199/33696952-8ececc12-dad2-11e7-8c92-c63798e416f6.png)

**Comment by ridiculousfish** [comment]
Only the background is used for `fish_color_selection`:

<img width="541" alt="screen shot 2017-12-22 at 12 45 39 pm" src="https://user-images.githubusercontent.com/920838/34312040-0e507d60-e716-11e7-89cc-97f10bce72fa.png">

this isn't at all obvious.

**Comment by nhooyr** [comment]
> Only the background is used for fish_color_selection:

The commit that documents `fish_color_selection` does not mention that. I think we should reopen this issue until its documented that only the background of `fish_color_selection` is used.
