### ISSUE TITLE
Is fish still actively developed?

### ISSUE THREAD

**Issue by gkatsanos** [fish-shell/fish-shell#4545]
With the number of open issues, the autocomplete performance issues (still waiting for 2.7 to be released) I am starting to contemplate going back to zsh or bash (with plugins).
I love most of the features of fish but It just doesn't feel someone's maintaining it.

**Comment by mqudsi** [comment]
Thanks for your concern and warm thoughts, but there's no need to post questions like this on GitHub (or, really, any open source project). The answer to your question can be seen here: https://github.com/fish-shell/fish-shell/commits/master

tl;dr obviously.

**Comment by gkatsanos** [comment]
No reason to take it personal, it was an honest question. I saw the commits
indeed, but why is your issue tracker so busy?

**Comment by mqudsi** [comment]
Precisely because fish _is_ under active development and we are constantly seeking to improve it further yb adding new features and fixing old bugs.

**Comment by gkatsanos** [comment]
I just received a private email from an ex maintainer who confirms changes occur at a snails pace.

**Comment by zanchey** [comment]
Hey, everyone's a critic.

I'm locking this issue. There is no constructive action arising from it.
