### ISSUE TITLE
Cant store result of command in a variable

### ISSUE THREAD

**Issue by perfecto25** [fish-shell/fish-shell#4547]
fish, version 2.6.0

running this in fish, 

```
mike@mrxmaster2 ~/d/b/a/b/additionals (master)> var=$(grep ExecStart bitbucket.service)

mike@mrxmaster2 ~/d/b/a/b/additionals (master)> var=$(grep ExecStart bitbucket.service)

mike@mrxmaster2 ~/d/b/a/b/additionals (master)> var=$(grep ExecStart bitbucket.service)

mike@mrxmaster2 ~/d/b/a/b/additionals (master)> var=$(grep ExecStart bitbucket.service)
```

it just repeats the line, the $var never gets set with output of $(grep ...) command,

switching to Bash, the command works properly, 

```
mike@mrxmaster2:additionals]$ var=$(grep ExecStart bitbucket.service)
[mike@mrxmaster2:additionals]$ echo $var
ExecStart=/opt/atlassian/bitbucket/5.4.0/bin/start-bitbucket.sh
```

**Comment by kartoffelsup** [comment]
If you checked the documentation, you would know that sub commands are run this way (cmd) https://fishshell.com/docs/current/faq.html#faq-subcommand :)

**Comment by faho** [comment]
Please read [the documentation](http://fishshell.com/docs/current/index.html). I'd recommend starting with [the tutorial](http://fishshell.com/docs/current/tutorial.html). You most likely also have a copy on your system, accessible via the `help` command.

Fish's syntax is different from bash's. In particular, setting variables is done via `set variablename value1 value2...`. Command substitutions (where you run a command and pass its output as arguments to the outer command) are written as `(command)`.

So this would be:

```fish
set var (grep ExecStart bitbucket.service)
```

**Comment by faho** [comment]
I'm assuming the question has been answered. If you have any additional questions, feel free to ask!

**Comment by mattbishop** [comment]
I've spent hours trying to figure out how to contact strings into a var without spaces between them.

I am trying:
```fish
set second '2nd'
set myVar 'first' $second 'third'
```
to be `first2ndthird` but instead it produces `first 2nd third`. I can't find a way in the `set` docs to eliminate the space delimiter.

I also have tried a command approach:

```fish
set myVar (string join0 'first' $second 'third')
```
But it just sets myVar to 'first'

Neither the docs or the tutorial have been helpful so forgive what is clearly a new user error.

**Comment by faho** [comment]
`string join0` puts a null-byte between the arguments. Because that is the string terminator, that won't work when passing to a command (and `set` isn't special-cased here).

What you want is to put *nothing* in between, so

```fish
string join '' first $second third
```

Which puts `''` between all the elements, which is the empty string i.e. nothing.

Or simply

```fish
set myvar first"$second"third
```

Here the quotes are used to make it clear the variable is named "second" and not "secondthird". You could use braces to accomplish the same thing.

**Comment by mattbishop** [comment]
Thanks for the guidance! I'm liking fish, and committed to learning it over bash.

**Comment by JulesGM** [comment]
Being able to do 
```
ls | set -a x
```
to put the array into `x` would be very nice I think
