### ISSUE TITLE
Hang when bad internet connection

### ISSUE THREAD

**Issue by gabm** [fish-shell/fish-shell#4548]
I'm using fish shell 2.6, but this happened already earlier...

When I have a bad internet connection (for example in public Wifis with Login Portal or 3G/4G), then the fish shell tends to hang... It does not accept any input and does not bring up the command prompt. Also opening more shells does not help, because they all have the same problem. There are only two workarounds: a) waiting or b) disconnecting the wifi.

Sometimes disconnecting is fine - but other times (bad 3G/4G coverage) its quite annoying!

All this makes me wonder:
- what is my shell communicating with the internet? Per default I don't expect fish to do that, and maybe its really something else?!
- why is that done in the "ui" thread, blocking my work?

**Comment by floam** [comment]
Are you on a filesystem mounted over a network? What exactly is slow? Prompt input? Completions?

**Comment by floam** [comment]
Fish shouldn't do anything itself over the Internet, with the exception of things like ssh/scp remote directory completions.

**Comment by gabm** [comment]
local filesystem, i have no remote fs, no ssh, no scp...

Usecase1: I startup a new terminal (Konsole). The windows stays blank for a minute or so. Then the prompt input appears and I can type my commands
Usecase2:  I have an open Konsole window, with a prompt (from an earlier session). I type but nothing appears on the screen. After a minute or so fish is displaying the characters and I can continue as normal

**Comment by floam** [comment]
It sounds like maybe something is slow on your system before fish is even launched. If you start a new `fish` process once you are in fish in Konsole, by typing `fish` and hitting enter, does the same delay occur before you get a new prompt when on slow Internet?

**Comment by gabm** [comment]
> It sounds like maybe something is slow on your system before fish is even launched.

it also affects running sessions (see Usecase 2)

> If you start a new fish process once you are in fish in Konsole, by typing fish and hitting enter, does the same delay occur before you get a new prompt when on slow Internet?

I can't type anything in these moments...

Sometimes I switch my shell to bash when this happens often (on the go with 3G for example) and then the problem vanishes..

**Comment by floam** [comment]
Can you run `mount` and show me the output?

**Comment by gabm** [comment]
of course, here we go:


```
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
sys on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
dev on /dev type devtmpfs (rw,nosuid,relatime,size=8159312k,nr_inodes=2039828,mode=755)
run on /run type tmpfs (rw,nosuid,nodev,relatime,mode=755)
efivarfs on /sys/firmware/efi/efivars type efivarfs (rw,nosuid,nodev,noexec,relatime)
/dev/mapper/root--vg-root--arch on / type ext4 (rw,relatime,discard,data=ordered)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/unified type cgroup2 (rw,nosuid,nodev,noexec,relatime,nsdelegate)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,name=systemd)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=38,pgrp=1,timeout=0,minproto=5,maxproto=5,direct)
mqueue on /dev/mqueue type mqueue (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime,pagesize=2M)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
configfs on /sys/kernel/config type configfs (rw,relatime)
tmpfs on /tmp type tmpfs (rw,nosuid,nodev)
/dev/mapper/data--vg-home--arch on /home type ext4 (rw,relatime,discard,data=ordered)
/dev/mapper/root--vg-root--arch on /var/lib/docker/plugins type ext4 (rw,relatime,discard,data=ordered)
/dev/mapper/root--vg-root--arch on /var/lib/docker/devicemapper type ext4 (rw,relatime,discard,data=ordered)
tmpfs on /run/user/1000 type tmpfs (rw,nosuid,nodev,relatime,size=1633512k,mode=700,uid=1000,gid=1000)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
```

I'm on arch linux, in case that matters.. thanks for your efforts!

**Comment by gabm** [comment]
I just checked with `sudo netstat --inet -ape` for open connections and fish doesn't show up... thats good news somehow

**Comment by floam** [comment]
Are you using fisherman or oh-my-fish? Do you have anything installed from them? Does it still occur if you launch `sh -c 'env HOME=$(mktemp -d) fish` from bash when the Internet is slow? That command will launch fish with an out-of-the-box clean configuration.

**Comment by faho** [comment]
>what is my shell communicating with the internet? Per default I don't expect fish to do that, and maybe its really something else?!

Let's get the obvious out of the way: Fish does not communicate with the internet by itself. There's no phoning home or checking updates or anything. Obviously third-party scripts might, and it's possible we've missed a case in our completions, but it sounds like you're not completing.

There are two cases where I expect something fish does to result in a network connection:

- If any file fish tries to access is on the net (via smb or sshfs or nfs or something)

- If fish tries to query your user database and that has been configured to go over the net

I'd wager the latter is happening here.

@gabm: There are numerous cases where we call `getpwuid` and friends, which might result in a network connection. If I've checked correctly, this happens when:

- uid is 0
- $USER is empty
- $HOME is empty
- $XDG_RUNTIME_DIR points to a non-existing or inaccesible directory (or is empty)

Can you check if one of those is true for you, and if so, can you try to remedy it before launching fish?

>why is that done in the "ui" thread, blocking my work?

If it is that, it's done during initialization, so there's no multi-threading yet.

>I just checked with sudo netstat --inet -ape for open connections and fish doesn't show up... thats good news somehow

IIUC, fish wouldn't show up, but whatever is doing the lookup on behalve of fish would.

**Comment by gabm** [comment]
@floam Thanks for your detailed analysis. none of the mentoined cases is true, uid is 1000, user, home are set and runtime_dir points to a location is my home folder..


> Are you using fisherman or oh-my-fish?

I just checked: it seems i have oh-my-fish installed (guess for some colors or smthg. like that.. ) I suspect something like this to be the problem. Also it seems that the problem does not occur with: `sh -c 'env HOME=$(mktemp -d) fish`

I will re-create my config and remove omf and start from 0. Thank you for pointing me to this completely forgot... I'll close now and report back once I find time. Thank you both for your help!

**Comment by floam** [comment]
Ah, I use neither and so am not sure, but I'd guess it's doing something like checking for updates on startup, or one of the installed plugins happens to do something over the net.
