### ISSUE TITLE
cd causes strange unicode/powerline character in prompt

### ISSUE THREAD

**Issue by mpcsh** [fish-shell/fish-shell#4553]
- version: 2.7.0
- `uname -a`: `Darwin Marks-MacBook-Pro.local 17.2.0 Darwin Kernel Version 17.2.0: Fri Sep 29 18:27:05 PDT 2017; root:xnu-4570.20.62~3/RELEASE_X86_64 x86_64`
- `$TERM`: `xterm-256color`
- did executing without customizations affect behavior: no

This is new as of fish 2.7.0, I believe. Whenever I launch my terminal or `cd`, I get this powerline-looking character before my prompt.
<img width="1680" alt="screen shot 2017-11-26 at 10 55 27 pm" src="https://user-images.githubusercontent.com/2894019/33251561-2f3fc10c-d2fd-11e7-9070-90f4f82edc1c.png">

**Comment by ridiculousfish** [comment]
That blue triangle is [iTerm 2's shell integration mark](https://www.iterm2.com/documentation-shell-integration.html). If you prefer you can disable it at Preferences->Profiles->Terminal->"Show Mark Indicators."

Hope that helps! Closing.

**Comment by mpcsh** [comment]
thank you @ridiculousfish :)
