### ISSUE TITLE
Fish Issue on startup after Update

### ISSUE THREAD

**Issue by simo98** [fish-shell/fish-shell#4574]
<!--
Please tell us which fish version you are using by executing the following:

**Fish: version 2.7.0
OS: Manjaro 17.1pre3 Hakoila
Terminal: Gnome-Terminal 3.26.2 
uname -a`: Linux simone-pc 4.9.65-1-MANJARO #1 SMP PREEMPT Fri Nov 24 10:42:19 UTC 2017 x86_64 GNU/Linux
`echo $TERM`: xterm-256color**

_I see the following error message on each startup of the terminal, this issue appeard after an update, the error message is_: 

~/.config/fish/functions/fish_prompt.fish (line 240): function: Unknown option '-q'
~/.config/fish/functions/fish_prompt.fish (line 240): 
function type -q -a name -d "Check if a function or program is type -q."
^
from sourcing file ~/.config/fish/functions/fish_prompt.fish
	called on standard input

in command substitution
	called on standard input

       functionfunction - create a function
        -

   Synopsis
       function NAME [OPTIONS]; BODY; end

function: Type 'help function' for related documentation

function type -q -a name -d "Check if a function or program is type -q."
  type "$name" ^/dev/null >&2
^
from sourcing file ~/.config/fish/functions/fish_prompt.fish
	called on standard input

in command substitution
	called on standard input

**Comment by faho** [comment]
Your old fish sessions are picking up the new files, so they attempt to reload them. Which won't work great because there's a new builtin.

Just quit all of the old fish sessions and it'll go away.
