### ISSUE TITLE
plan9 rc-like quoting rule (no backslash) within single quotes

### ISSUE THREAD

**Issue by xiaq** [fish-shell/fish-shell#458]
Backslashes are sometimes desired in their literal form, esp. when writing regular expressions. In POSIX-compatible shells you write

```
grep 'foo\|bar\\'
```

to `grep` for lines containing either `foo` or `bar\`. Since fish use backslashes for escaping within single quotes this lead one to write

```
grep 'foo\\|bar\\\\'
```

Which is somewhat tedious. The escaping rule for single quotes adopted by plan9 `rc` is worth considering: like single quotes in POSIX-compatible shells, single quotes know no escape sequences, but two single quotes make for one literal single quote. Since this originally means two singly-quoted strings concatenated together, which is never useful, nothing is lost by altering its meaning. So

```
echo '\\'
echo 'I''m'
```

Outputs two lines, `\\` and `I'm`.  Finally this rule makes it extremely simple to quote a literal string:

```
function quote
    echo -n "'"
    echo -n "$argv" | sed -e "s/'/&&/g"
    echo -n "'"
end
```

Trivia: I believe this quoting rule does not originate from plan9 rc, but I've adopted the term "rc-like quoting rule" like the zsh people did.

**Comment by liyanrui** [comment]
Escaping a single quote with two of them is an bad idea. Eg, if replace '\' with nothing, I could do as follows:

$ echo 'a\\b' | sed -e 's/\\\//g'
=> ab
$ echo 'a\\b' | sed -e 's/\\\\//g'
=> ab

However if I want to replace '\\' with '\', 

$ echo 'a\\bccc\\c' | sed -e 's/\\\/\\/g' 
=> sed: -e expression #1, char 8: unterminated `s' command

$ $ echo 'a\\bccc\\c' | sed -e 's/\\\/\\\/g' 
a\bccc\c

$ echo 'a\\bccc\\c' | sed -e 's/this is a hell/\\\/g' 
a\bccc\c

very confusion!

**Comment by krader1961** [comment]
Closing because a) this can't be changed since it breaks backward compatibility, and b) it's been four years and no one has argued how this might be done without breaking existing scripts and doing the work to create a commit.
