### ISSUE TITLE
Keychain workaround

### ISSUE THREAD

**Issue by Vintodrimmer** [fish-shell/fish-shell#4583]
```
➤  fish --version
fish, version 2.7.0
➤ uname -a
Linux chrysalis 4.14.4-chrysalis #2 SMP PREEMPT Fri Dec 8 19:23:34 CET 2017 x86_64 GNU/Linux
➤ echo $TERM
st-256color
```

I'm trying to run 
```
eval `keychain --eval --agents ssh github`
```
but get the following error:
```
fish: Unknown command '`keychain'
- (line 1):
begin; `keychain --eval --agents ssh github`
       ^
from sourcing file -
        called on line 60 of file /usr/share/fish/functions/eval.fish

in function “eval”
        called on standard input
```

If I try to run it as follows: `eval (keychain --eval --agents ssh github)`, I get the following errors:
```
 * keychain 2.8.4 ~ http://www.funtoo.org
 * Found existing ssh-agent: 9119
 * Known ssh key: /home/eichhorn/.ssh/github

- (line 1): Unsupported use of '='. In fish, please use 'set SSH_AUTH_SOCK /tmp/ssh-BSemsj3nLWGP/agent.9118'.
begin; SSH_AUTH_SOCK=/tmp/ssh-BSemsj3nLWGP/agent.9118; export SSH_AUTH_SOCK; SSH_AGENT_PID=9119; export SSH_AGENT_PID;
       ^
from sourcing file -
        called on line 60 of file /usr/share/fish/functions/eval.fish

in function “eval”
        called on standard input

- (line 1): Unsupported use of '='. In fish, please use 'set SSH_AGENT_PID 9119'.
begin; SSH_AUTH_SOCK=/tmp/ssh-BSemsj3nLWGP/agent.9118; export SSH_AUTH_SOCK; SSH_AGENT_PID=9119; export SSH_AGENT_PID;
                                                                             ^
from sourcing file -
        called on line 60 of file /usr/share/fish/functions/eval.fish

in function “eval”
        called on standard input

```

I understand that fish is not POSIX compatible and it's probably not going to work directly.

My workaround right now is to launch `dash`, run the comand there and then launch `fish` from the `dash`. That way everything works as it should, but it's rather inconvenient.

What would be a better way of doing that?

I tried doing it with a script:
```
#!/bin/sh
KEY=$1

eval `keychain --eval --agents ssh ${KEY}`
```
 but there is no effect as I still get the "Permission denied error".

**Comment by zanchey** [comment]
`keychain` determines what kind of output to produce based on your `$SHELL` environment variable, which is set (usually) by your login process.

One method would be to put `begin; set -lx SHELL $__fish_bin_dir/fish ; eval (keychain --eval --agents ssh github); end` in your `.config/fish/config.fish`.

However, a preferred method is to start keychain in your login or interactive shells only, and then to source the files it produces:

```fish
if status --is-interactive
    keychain --quiet --agents ssh github
end

begin
    set -l HOSTNAME (hostname)
    if test -f ~/.keychain/$HOSTNAME-fish
        source ~/.keychain/$HOSTNAME-fish
    end
end
```

**Comment by Vintodrimmer** [comment]
> `keychain` determines what kind of output to produce based on your `$SHELL`

Didn't know that, thank you!

Your second solution works, but requires me to activate keychain and insert the password when I launch terminal with `fish`, which is not the best way for me, especially if I need just one key from many.

So I ended up with the following function:

```
➤ function kchain
      export SHELL=fish
      eval (keychain --eval --agents ssh $argv)
      export SHELL=dash
  end
```

One small question, is there a way to pass a number of arguements? As $1 $2 and so on in bash?

**Comment by zanchey** [comment]
You can slice `$argv`, which is a list:

```fish
function foo
   echo First argument $argv[1]
   echo Second argument $argv[2]
   echo And the rest $argv[2..-1]
   echo All arguments backwards $argv[-1..1]
end
foo (seq 1 6)
First argument 1
Second argument 2
And the rest 2 3 4 5 6
All arguments backwards 6 5 4 3 2 1
```

**Comment by Vintodrimmer** [comment]
Thanks!

**Comment by gour** [comment]
@Vintodrimmer Hello, can you please share the whole snippet required to have working keychain with ssh,gpg agents under fish shell?

**Comment by Vintodrimmer** [comment]
@gour Good evening! I use the version posted above, since my only use for GPG right now is "pass".

If you want both gpg and ssh, I'd suggest something like this:
```
➤ cat ~/.config/fish/functions/kchain.fish
function kchain
        export SHELL=fish
        eval (keychain --$argv[3] --eval --agents $argv[1] $argv[2])
        export SHELL=dash
end
```
You need `$argv[3]` for the GPGv2 support, as the keychain defaults to the GPGv1.

Now if you want to use GPGv2 key "arst" you would go `kchain gpg arst gpg2`, for GPGv1 you would go `kchain gpg arst` and for SSH `kchain ssh arst`.

If you use exclusively GPGv1 or GPGv2, you can just hardcode it into the snippet and remove the 3rd argument.

**Comment by gour** [comment]
> If you want both gpg and ssh, I'd suggest something like this:

How/when do you invoke kchain.fish function?

I'd expect to run it after login...

> You need $argv[3] for the GPGv2 support, as the keychain defaults to the GPGv1.

I see that keychain now has `--gpg2` parameter...

> If you use exclusively GPGv1 or GPGv2, you can just hardcode it into the snippet and remove the 3rd argument.

I believe there is no need for GPGv1 here any longer, so I can hardcode GPGv2 usage...

**Comment by Vintodrimmer** [comment]
@gour I actually run it from the console when/if I need some particular key. I'm too lazy to enter all the passwords for every key at login.

But there are options for that. I think the second post should do that.

**Comment by zanchey** [comment]
I use something along the lines of this in my `.config/fish/config.fish`:

```
if status is-login
    keychain --clear --quiet
end

if test -f ~/.keychain/(hostname)-gpg-fish
    source ~/.keychain/(hostname)-gpg-fish
end

if test -f ~/.keychain/(hostname)-fish
    source ~/.keychain/(hostname)-fish
end
```

**Comment by gour** [comment]
What do you think about submitting some more info to the keychain in order to have complete example for fish shell, since it seems that the current snippet:

```
For the fish shell, use the following format:

        if status --is-interactive
            keychain --eval --quiet -Q id_rsa | source
end
```

is both incomplete - no gpg(2) agent), as well as incorrect?

**Comment by zanchey** [comment]
It's not incorrect, but I'll submit them a patch to match the other examples.

**Comment by zanchey** [comment]
https://github.com/funtoo/keychain/pull/99

**Comment by gour** [comment]
@zanchey that does not work for me & gpg2:

```
$  keychain id_rsa  0123ABCD

 * keychain 2.8.5 ~ http://www.funtoo.org
 * Found existing ssh-agent: 1686
 * Warning: can't find 0123ABCD; skipping
 * Known ssh key: /home/gour/.ssh/id_rsa
```

Any hint?

**Comment by zanchey** [comment]
You might have to explicitly specify the use of the GPG agent. The following works for me:

```
keychain --agents ssh,gpg id_rsa 0xFCA50E480C273BBA
```

**Comment by bergercookie** [comment]
In the latest keychain version that I'm using the manpage gives very clear instruction on how to do this.

```
       For the fish shell, use the following format:
           if status --is-interactive
               keychain --eval --quiet -Q id_rsa | source
           end
```

**Comment by eoli3n** [comment]
I use this, which asks for passphrase and start the agent
```
if status --is-interactive
    keychain --eval --agents ssh -Q id_rsa | source
    keychain --eval --agents gpg --gpg2 -Q 6FAF4042 | source
end
```
But I noticed that the gpg keychain line produce no env vars
This kills only ssh agent, I need to pkill gpg-agent manually
```
$ pkill gpg-agent

$ keychain -k all

 * keychain 2.8.5 ~ http://www.funtoo.org
 * All user's ssh-agents stopped: 22341
```
This prompts for my passphrase in pinentry, but ``--eval`` should print some env vars to be sourced
```
$ keychain --eval --agents gpg --gpg2 -Q 6FAF4042 

 * keychain 2.8.5 ~ http://www.funtoo.org
 * Starting gpg-agent...

 * Known gpg key: 6FAF4042
```
If i use ``--dir`` instead of ``--eval``, same problem, generated scripts are empty
```
$ keychain --dir ~/.ssh/.keychain --agents gpg --gpg2 -Q 6FAF4042

 * keychain 2.8.5 ~ http://www.funtoo.org
 * Starting gpg-agent...
 * Known gpg key: 6FAF4042

$ cat ~/.ssh/.keychain/*
setenv 

```

Any idea ?

**Comment by faho** [comment]
@eoli3n This looks like a question for the keychain people rather than us.

I would expect the gpg thing to no longer print anything because the gpg socket is now (since gnupg 2.1.0, released in 2014, if I'm reading [the release notes](https://gnupg.org/download/release_notes.html) correctly) typically at a fixed path, so there's no real need for variable trickery anymore.

Also on my system keychain seems to just trigger the gpg-agent, which is then supervised by systemd, so you would have to ask *it* to quit.

**Comment by eoli3n** [comment]
thanks @faho, I found my issue and edited my comment for posterity :)

**Comment by sascha-wi** [comment]
I followed the instructions but I am still not able to get keychain working. Maybe my understanding of keychain is wrong, but my goal would be to only have to enter my ssh passphrase once.

I start fish shell from my terminal emulator config, alacritty in this case. aka its not a login shell. I tried to copy paste the 
`if status --is-interactive
    keychain --eval --agents ssh --quiet -Q id_rsa | source
    keychain --eval --agents gpg --quiet --gpg2 -Q long_key_id_here | source
end`
into a keychain.fish function, but it gave me an error when starting new terminal windows:
` * Warning: can't find id_rsa; skipping
- (line 1): Unsupported use of '='. In fish, please use 'set SSH_AUTH_SOCK /tmp/ssh-XXXXXXPLGsV0/agent.12680'.
from sourcing file -
	called on line 2 of file ~/.config/fish/conf.d/keychain.fish
from sourcing file ~/.config/fish/conf.d/keychain.fish
	called on line 246 of file /usr/share/fish/config.fish
from sourcing file /usr/share/fish/config.fish
	called during startup
source: Error while reading file “<stdin>”
 * Warning: can't find long_key_id_here; skipping`
 
 Any help appreciated.

**Comment by faho** [comment]
@sascha-wi Your keychain fails to turn on the fish output, most likely because you haven't made fish your login shell and so $SHELL isn't "fish". Try this:

```fish
if status --is-interactive
    set -lx SHELL fish
    keychain --eval --agents ssh --quiet -Q id_rsa | source
    keychain --eval --agents gpg --quiet --gpg2 -Q long_key_id_here | source
end

**Comment by sascha-wi** [comment]
First let me thank you for your blazing fast reply! Much love. Now I get the following when opening a new terminal:
` * Warning: can't find id_rsa; skipping
 * Warning: can't find long_key_id_here; skipping`

**Comment by faho** [comment]
Well, you quite possibly want to insert your long key id there.

**Comment by sascha-wi** [comment]
Yeah I just noticed, I am not familiar with how to find the id. I will need to check. Give me sec.

**Comment by sascha-wi** [comment]
Regardless of what ID I use it doesn't seem to find the correct key. I checked my gpg verson on my debian installation:
`gpg (GnuPG) 2.2.40
libgcrypt 1.10.1
Copyright (C) 2022 g10 Code GmbH
License GNU GPL-3.0-or-later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Home: /home/sascha/.gnupg
Supported algorithms:
Pubkey: RSA, ELG, DSA, ECDH, ECDSA, EDDSA
Cipher: IDEA, 3DES, CAST5, BLOWFISH, AES, AES192, AES256, TWOFISH,
        CAMELLIA128, CAMELLIA192, CAMELLIA256
Hash: SHA1, RIPEMD160, SHA256, SHA384, SHA512, SHA224
Compression: Uncompressed, ZIP, ZLIB, BZIP2`

so there should be no need to regenerate my keys like @eoli3n mentioned I guess? Output of my gpg --list-keys:
![image](https://user-images.githubusercontent.com/123939946/215503214-a8ca3cad-9ecd-405d-9703-5b2ce379d822.png)

**Comment by sascha-wi** [comment]
For me the way keychain is setup it doesn't seem to consider what is set up it ~/.gnupg/gpg-agent.conf.
I would also happily use an alternative to keychain if it works more reliably with fish shell.

**Comment by sascha-wi** [comment]
```
 * Error: Problem adding; giving up
- (line 1): Unsupported use of '='. In fish, please use 'set SSH_AUTH_SOCK /tmp/ssh-fOHp5YWR3YgD/agent.1624'.
SSH_AUTH_SOCK=/tmp/ssh-fOHp5YWR3YgD/agent.1624; export SSH_AUTH_SOCK;
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
from sourcing file -
source: Error while reading file '<stdin>'
```
Recently this happens, is there maybe a way how to handle ssh/gpg keys in fish shell without the use of keychain? I am really fed up with this.

**Comment by faho** [comment]
@sascha-wi: Please see [my above comment](https://github.com/fish-shell/fish-shell/issues/4583#issuecomment-1408657051), you're getting the non-fish output again.

**Comment by sascha-wi** [comment]
As can be seen in my previous comment, I just entered the plain command which is part of the fish config from your linked comment, so I don't understand why you think this not a fish output.

**Comment by faho** [comment]
> I don't understand why you think this not a fish output.

`keychain` is not printing the fish-compatible script that it is capable of, and so `source` fails.

It isn't detecting that it should. Usually these things either have a "--shell=fish" option or detect it by reading $SHELL.

Which I explained in my older comment.

**Comment by sascha-wi** [comment]
I am really baffled, because all of this worked for quite some time until yesterday. I never changed my login shell before and used your
`if status --is-interactive
    set -lx SHELL fish`
 snippet. Weirdly enough whenever I did echo $SHELL it was still shown as bash.
 Now I jumped the gun and changed my login shell (instead of the interactive way) and keychain works again proplery and echo $SHELL is also showing fish now.
 
 I am on debian btw and use alacritty as my terminal, where I configured that fish is to be used as my shell. *cluessless*

**Comment by faho** [comment]
> Weirdly enough whenever I did echo $SHELL it was still shown as bash.

Yes, $SHELL is set to the user's login shell. That's the one you configure with `chsh`. No shell or terminal that I know touches this because that's what it's meant to be. (that's also why keychain using it to detect "the shell I am running in" is a heuristic that may fail in some cases. If I made keychain I'd add a "--shell=[fish|bash|zsh|...]" option, but I suspect they would tell you to set $SHELL temporarily instead)

It *would* show $SHELL outside of that specific block, because I told you to override it only in that one block.

I.e.

```fish
if status is-interactive
   set -lx SHELL fish # this sets a *local* version of $SHELL only for this block
   echo $SHELL # prints fish
end

echo $SHELL # prints bash, or whatever else you set with chsh
```

This is why you need to run `keychain --eval` *inside that block*. If I had to guess I would assume you accidentally moved it outside of that block.

**Comment by swaits** [comment]
FWIW, here's my solution for starting `keychain` in fish:

```fish
# Define SSH key paths
export SSH_PRIVATE_KEYS \
    ~/.ssh/id_ecdsa \
    ~/.ssh/id_ecdsa_personal \
    ~/.ssh/id_ed25519

# Define GPG key identifiers
export GPG_PRIVATE_KEYS \
    0xBEEFDEAD \
    0xDEADBEEF

# Only run this on Linux interactive shells
if test (uname) = Linux; and status is-interactive
    keychain --agents "gpg,ssh" --quiet --eval $SSH_PRIVATE_KEYS $GPG_PRIVATE_KEYS \
        | sed -E 's/^([^=]+)=(.*); export \1;/set -gx \1 \2/g' \
        | source
end
```

The trick is using `sed` to convert from Bash/Zsh environment variable assignment to Fish.

**Comment by philfuster** [comment]
@swaits Thank you for that! Helped me get mine working. Not sure if I misread other comments or not, but for other people coming here and looking to add @swaits solution for starting `keychain` into their fish configuration file, you need to set the SSH_PRIVATE_KEYS and GPG_PRIVATE_KEYS variables correctly using fish syntax:

Change

```
# Define SSH key paths
export SSH_PRIVATE_KEYS \
    ~/.ssh/id_ecdsa \
    ~/.ssh/id_ecdsa_personal \
    ~/.ssh/id_ed25519

# Define GPG key identifiers
export GPG_PRIVATE_KEYS \
    0xBEEFDEAD \
    0xDEADBEEF
```

to

```
set -gx SSH_PRIVATE_KEYS <paths-to-your-keys>
set -gx GPG_PRIVATE_KEYS <paths-to-your-keys>
```

**Comment by swaits** [comment]
Oh yeah, sorry about that. I have a fish function called "export", for the sake of convenience. 😀

**Comment by zanchey** [comment]
Seeing as this is the top result in Google results for "keychain fish shell", I have rewritten the function @swaits has provided.

```fish
# Only run this on Linux interactive shells
if status is-interactive; and test (uname) = Linux
    set SSH_PRIVATE_KEYS \
        ~/.ssh/id_ecdsa \
        ~/.ssh/id_ecdsa_personal \
        ~/.ssh/id_ed25519

# Define GPG key identifiers
    set GPG_PRIVATE_KEYS \
        0xBEEFDEAD \
        0xDEADBEEF

    SHELL=fish keychain --agents "gpg,ssh" --quiet --eval $SSH_PRIVATE_KEYS $GPG_PRIVATE_KEYS \
        | source
end
```

Putting the status test first avoids a slowdown on non-interactive shell start, as there is no fork to run uname. The variables do not need to be exported (and there is an export function in fish since 2.2, incidentally). Finally, rather than mangling the output of keychain with sed, keychain will happily output fish-compatible syntax as discussed above.

**Comment by philfuster** [comment]
> Seeing as this is the top result in Google results for "keychain fish shell", I have rewritten the function @swaits has provided.
> 
> 
> 
> ```fish
> 
> # Only run this on Linux interactive shells
> 
> if status is-interactive; and test (uname) = Linux
> 
>     set SSH_PRIVATE_KEYS \
> 
>         ~/.ssh/id_ecdsa \
> 
>         ~/.ssh/id_ecdsa_personal \
> 
>         ~/.ssh/id_ed25519
> 
> 
> 
> # Define GPG key identifiers
> 
>     set GPG_PRIVATE_KEYS \
> 
>         0xBEEFDEAD \
> 
>         0xDEADBEEF
> 
> 
> 
>     SHELL=fish keychain --agents "gpg,ssh" --quiet --eval $SSH_PRIVATE_KEYS $GPG_PRIVATE_KEYS \
> 
>         | source
> 
> end
> 
> ```
> 
> 
> 
> Putting the status test first avoids a slowdown on non-interactive shell start, as there is no fork to run uname. The variables do not need to be exported (and there is an export function in fish since 2.2, incidentally). Finally, rather than mangling the output of keychain with sed, keychain will happily output fish-compatible syntax as discussed above.

Very nice. Thank you for sharing!
