### ISSUE TITLE
history search doesn't respect arguments

### ISSUE THREAD

**Issue by urxvtcd** [fish-shell/fish-shell#4588]
`history search` with `-1`, `-n 1` or `--max=1` doesn't limit the output

    > fish --version
    fish, version 2.7.0
    > uname -a
    Linux go-hard-or-go-home 4.9.67-1-lts #1 SMP Tue Dec 5 13:07:07 CET 2017 x86_64 GNU/Linux
    > echo $TERM
    rxvt-unicode-256color

`sh -c 'env HOME=$(mktemp -d) fish'` doesn't fix the issue.

**Comment by faho** [comment]
Sorry about that. As it turns out ee1d3106517c5fb31e290002028715535e8a9906 has this bit in its commit message:

>This also fixes a bug in the `history` function with respect to how it handles the `-n` / `--max` flag.

We missed that and didn't backport it to 2.7.0.

**Comment by urxvtcd** [comment]
No problem, it's easy to just `head -n`. Thanks for quick reply!

**Comment by azag0** [comment]
I used `-n 5000` to speed up listing of the history. 5k was almost instant, the full ~35k had a noticeable lag. Subjectively, the history listing got a little faster in 2.7, so it's not such an issue anymore, but it would still be nice to speed up the history output. Is there some way now, or do I wait till 3.0?

**Comment by faho** [comment]
@azag0: First off, what I'd like to know is what you are executing `history` that often for? Is there any particular usecase that we might be able to address better?

Note that `history search` should be fast even without the limiting bit, so if you are doing something like `history | grep string`, that would better be done as `history search string`.

Alternatively, you can wait for 3.0, build fish from git master or backport that commit.

**Comment by azag0** [comment]
I'm using history with fzf so that every time I hit ctrl+R, history is [executed](https://github.com/junegunn/fzf/blob/7b5ccc45bc76f289fe2c48cf91e895b9ca99b1e2/shell/key-bindings.fish#L38-L58), and loaded as a buffer into fzf, which then does the filtering/searching.

**Comment by faho** [comment]
>I'm using history with fzf so that every time I hit ctrl+R, history is executed, and loaded as a buffer into fzf, which then does the filtering/searching.

Ah, okay, that makes sense.

As it turns out, the only thing you need from that commit is [this part](https://github.com/fish-shell/fish-shell/commit/ee1d3106517c5fb31e290002028715535e8a9906#diff-b773416b0e7805970a4c3dfde41fc8b8R40):

```fish
-    set -l max_count $_flag_max
+    set -l max_count
+    set -q _flag_max
+    set max_count -n$_flag_max
```

(yes, the "-n" was missing)

which applies to the history _function_. So you can also override that locally. You'll have to remove it again for fish 3.0.
