### ISSUE TITLE
Fedora 27 repo?

### ISSUE THREAD

**Issue by ardrigh** [fish-shell/fish-shell#4590]
I am looking to update to Fedora 27 from Fedora 26, but I notice there is no repo listed for Fedora 27 on the [Linux downloads page](https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A2&package=fish)

Since the older Fedora releases are unsupported, is it possible for someone to add Fedora 27 and consider removing F23 and F24 listings?

I am not sure if there will be much different between packaging for each Fedora version, but it would be good to have the current release listed. I couldn't see anywhere else to request the new repo.

**Comment by zanchey** [comment]
Sorted; thanks for the heads up.

**Comment by zanchey** [comment]
I've been trying to work out how we can do this automatically; openSUSE/open-build-service is one feature request that may help.
