### ISSUE TITLE
Feature request: auto-replace `&&` to `; and` (optionally?)

### ISSUE THREAD

**Issue by actionless** [fish-shell/fish-shell#4591]
I've tried:
```fish
abbr "&&" "; and"
```
but it's not working

And the same for `||`.

**Comment by faho** [comment]
See [our wiki](https://github.com/fish-shell/fish-shell/wiki/Bash-Style-Command-Chaining-(&&-and-%7C%7C)) for a common solution.

The reason abbrs won't work here is because they are only expanded in command position.

**Comment by actionless** [comment]
thanks!
