### ISSUE TITLE
built-in support for identifying errors and sourcing (ba)sh scripts?

### ISSUE THREAD

**Issue by indirectlylit** [fish-shell/fish-shell#4594]
Thanks for a wonderful project!

Feel free to close this if it's not feasible or desirable, but since you're scoping out 3.0...

----

When I'm helping less technical people (e.g. interns and designers) set up a project...

* I always encourage them to use `virtualenv` because best practices
* I want to encourage them to use `fish` because it makes the command line more approachable

Unfortunately, google results for ["using virtualenv"](https://www.google.com/search?q=using+virtualenv) assume a bash compatible shell, so I typically skip `fish` to keep setup and learning curve easier.

#522 was an interesting read - I had no idea that [`bass`](https://github.com/edc/bass) existed, and I never thought to look because `fish` does generally work out-of-the-box with nothing new to learn or configure, as described on the label :)

Here's what I'd imagine might be possible if something like `bass` was integrated as a first-class feature:

```
~/projects/temp $ virtualenv ~/envs/main
New python executable in /Users/usr/envs/main/bin/python2.7
Also creating executable in /Users/usr/envs/main/bin/python
Installing setuptools, pip...done.
~/projects/temp $
~/projects/temp $ source ~/envs/main/bin/activate
Missing end to balance this if statement
~/PythonEnvs/main/bin/activate (line 78): if [ -n "$BASH" -o -n "$ZSH_VERSION" ] ; then
                                          ^
from sourcing file ~/PythonEnvs/main/bin/activate
	called on standard input

source: Error while reading file '/Users/usr/envs/main/bin/activate'

WARNING: It looks like you're trying to source a bash script. If so, try running:
bass source ~/envs/main/bin/activate
~/projects/temp $
~/projects/temp $
~/projects/temp $ bass source ~/envs/main/bin/activate
(main)~/projects/temp $
```

I'm sure this glosses over technical difficulties, but at a high level I'd be more inclined to recommend `fish` to novices if it helped them deal with cross-shell issues out-of-the-box.

A similar warning might be thrown if sh scripts are run, e.g.

```
WARNING: It looks like you're trying to run a bash script. If so, try running:
sh ./myscript.sh
```

**Comment by ridiculousfish** [comment]
Do I understand the main thrust of the idea is a sh-compatibility mode? See also #522

**Comment by indirectlylit** [comment]
Not quite - I understand that is not feasible.

The high-level suggestions are:

1. Improved user feedback. If `fish` detects a common class of user error, provide guidance on how to move forward.
2. Built-in support for [`bass`](https://github.com/edc/bass). It solves a big class of compatibility issues as mentioned in https://github.com/fish-shell/fish-shell/issues/522#issuecomment-250950281: "recognize changes to environment vars made by scripts like nvm.sh and incorporate those changes into the current fish environment".
