### ISSUE TITLE
yarn autocompletion: add context aware completions to `yarn run` by parsing package.json

### ISSUE THREAD

**Issue by nthapaliya** [fish-shell/fish-shell#4597]
I've slightly modified the yarn autocompletion script.

It adds context aware completions to `yarn run` by parsing the package.json file, if available. For command line json parsing, I'm using `jq` (https://stedolan.github.io/jq/). It checks to see if jq is available too. If those two conditions are true, then it reads the package.json file for the 'scripts' keys, and presents those to the auto completion script.

This way I can type `yarn run <TAB>` and be shown the possible scripts available.

I am opening this issue to gauge if its a feature people want. If yes, I can open a PR with the tweaks I've made.
```
> fish --version
fish, version 2.7.0
> uname -a
Darwin MacBook-Pro.local 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
> echo $TERM
screen-256color
```

**Comment by faho** [comment]
Sure that sounds fine. Note that [the npm completions](https://github.com/fish-shell/fish-shell/blob/master/share/completions/npm.fish) already do something like this. Also, the [composer completions](https://github.com/fish-shell/fish-shell/blob/master/share/completions/composer.fish) read json via python.

I'd assume that python is still more commonly available (we use it for some of our ancillary programs), but jq should probably be fine.

**Comment by nthapaliya** [comment]
@faho I feel silly I didn't look at the npm completion script. It had almost exactly what I had implemented. Goes to say, if you think you have a new idea, somebody already had it a long time before you.

**Comment by nthapaliya** [comment]
Closing because the code addressing this issue has been merged into master.

**Comment by liubko** [comment]
@nthapaliya I have `fish, version 2.7.1` but when I type `yarn run` and hit tab it doesn't give me any suggestions.

**Comment by liubko** [comment]
@faho ok, thanks.

what if I just copy whole
https://raw.githubusercontent.com/PenegalECI/fish-shell/7355696266b6a0cbef7cebba52b6155d6284d128/share/completions/yarn.fish
to `~/.config/fish/completions/yarn.fish`?

I think this should work, but it doesn't. When hitting tab nothing shows up

**Comment by faho** [comment]
@liubko: Do you have `jq` installed? Looking at that script, that's what it uses.

Also, I'm assuming you've restarted fish?

**Comment by liubko** [comment]
yes, I had a problem with `jq`, after `brew install jq` it works. @faho Thanks a lot!
