### ISSUE TITLE
ls is stuck, does not terminate

### ISSUE THREAD

**Issue by ctongfei** [fish-shell/fish-shell#4599]
Environment: Fish 2.7.0; Linux login 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux; $TERM=xterm-256color

```
 ~  /bin/ls                                                                                                                 Thu 14 Dec 2017 02:02:21 PM EST
app  backup  data  dump  exp  job  lib	proj  sandbox  scripts
 ~  ls                                                                                                                      Thu 14 Dec 2017 02:02:23 PM EST

```

This is a remote machine. Running `/bin/ls` is completely fine -- but running `ls` it never terminates -- even Ctrl+C cannot stop it from running. `ps aux` shows that a process below is running and it does not stop.
```
tongfei  25839  0.0  0.0  18968  1536 ?        DN   13:22   0:00 ls --color=auto --indicator-style=classify /home/tongfei
```

**Comment by faho** [comment]
I have a couple of questions:

Does

```fish
command ls --color=auto --indicator-style=classify /home/tongfei
```

work? I.e. the exact thing the wrapper function is doing?

Is this dependent on what directory you're running it in?

Is the remote machine debian/ubuntu with fish 2.7.0?

**Comment by ctongfei** [comment]
I cannot reproduce it anymore. It works properly now.

Before this it is dependent on the directory -- it only fails on home (`~`).
Yes, it's remote machine, debian, fish 2.7.0.

**Comment by faho** [comment]
>I cannot reproduce it anymore.

In that case, let's assume it was a weird fluke - some solar flare or a butterfly flapping its wings wrong or something.
