### ISSUE TITLE
Scripts run by the '.' command get a strange argv

### ISSUE THREAD

**Issue by ncraike** [fish-shell/fish-shell#460]
If other args are given after the command being "sourced", the sourced command's argv is just those args. But if no args are given after the command being "sourced", the argv is the name of the command being sourced.

```sh                                                     
$ cat echo_argv.fish
echo $argv
$ . echo_argv.fish
echo_argv.fish
$ . echo_argv.fish something
something
```

This makes it really hard for a script designed to be sourced to figure out if its been given one arg or no args (without hardcoding the name of the script).

It'd be nice if $argv either always contained the name of the command being sourced at argv[1], or was empty if no args are given after the sourced command's name.

**Comment by faho** [comment]
As mentioned, this is a duplicate.
