### ISSUE TITLE
Problems in AFS folder

### ISSUE THREAD

**Issue by sterni1971** [fish-shell/fish-shell#4602]
Hello!

Environment:
fish, version 2.6.0
Linux mynode 4.13.0-19-generic #22-Ubuntu SMP Mon Dec 4 11:58:07 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
xterm-256color
no third party extension

Problem:
cd in directory located on AFS (https://www.openafs.org/) hangs for several minutes. If I look into debug output the problem is IMHO the automatic search for git repositories

<4> fish: Exec job 'command git rev-parse --git-dir --is-inside-git-dir --is-bare-repository --is-inside-work-tree HEAD ^/dev/null' with id 6

this hangs also in bash if I start it directly.

Solution:
It would be nice if the automatic git search could be configured with a white or blacklist.

**Comment by sterni1971** [comment]
The problem is in the "informative vcs" prompt. Maybe I could add
something like to "informative vcs"

if [ (stat -f -c '%T' .) = 'afs' ]
      return 1
 end

as it seems there is no way to switch the prompt on the command line

**Comment by faho** [comment]
Afs is a network-filesystem if I'm reading correctly? Those would tend to have widely diverging performance, dependent on how the network is setup. How is yours?

Also, is there any particular part of that `git rev-parse` call that is slow? I.e. try

```fish
git rev-parse --git-dir
git rev-parse --is-inside-git-dir
git rev-parse --is-bare-repository
git rev-parse --is-inside-work-tree
git rev-parse HEAD
```

which of these is slow? We might be able to do some caching - everything but the "HEAD" part is unlikely to change.

>`if [ (stat -f -c '%T' .) = 'afs' ]`

That appears to be invalid on [FreeBSD's stat](https://www.unix.com/man-page/FreeBSD/1/stat/), which doesn't have a "-c" option. That's most likely also true on macOS. That means we'd have to find a different way to do it.

**Comment by sterni1971** [comment]
AFS is not only a network fs it is a global file system (which makes it in terms of 
latency even force).

Our network is quite fast and a simple write and read works perfectly on AFS.
The problem seems the huge amount of small IO from GIT.

So I tried the command you send and they all run exactly 2min and they all
give on stderr
>>>
fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
<<<

what is about 
`test -e .git; or return 1`

**Comment by faho** [comment]
> test -e .git; or return 1

Nope. We need to test if there's a ".git" in the current directory _or any previous one_. Plus I'm never quite sure if there isn't some weird configuration where the ".git" directory can be somewhere else or called something else.

-------

Note that, if you want a blacklist, it's rather easy to do. Check your `fish_prompt` or `fish_right_prompt` function for a call to `__fish_vcs_prompt` or `__fish_git_prompt`, then replace that with `if stat ...; thatfunction; end`.

**Comment by ridiculousfish** [comment]
Someday we'll have proper async prompt support (#1942). Closing as a dup of that. For now, the options are to either customize the prompt or switch to a git-oblivious one. Thanks for filing!
