### ISSUE TITLE
Description of command in suggestion list not showing

### ISSUE THREAD

**Issue by sanjibukai** [fish-shell/fish-shell#4603]
Hello,

I made some custom aliases (using `function` not `alias`) and I tried the complete feature that fish shell provide.
And I noticed two problems:
- Command description is not displayed at all in autocomplete suggestions list
- Argument description is displayed sometimes in autocomplete suggestions list

As suggested I recorded the behavior https://asciinema.org/a/ykzBJHPSnKlYv1Z0g7QV4JJyx

Here you can see (at the beginning) that the description of my commands (for example **`g`** and **`ga`** in the first screen) are not showing.
Then you can see (from 0:26) that some arguments descriptions is displayed but not all.
But in the end (from 0:52) those descriptions are displayed.

In order to have some descriptions, I "tricked" my aliases so that I defined a main alias (for example here **`g`** for git) and I defined all the aliases (related with git) as argument for this pseudo-command:

Here is my `g.fish` file including all the `complete` commands:

    function g
      eval $argv[1]
    end

    complete -xc g -d "Git Main Alias file"
    complete -xc g -a "gst glg ga ga. gau gco gci gcim gac gacm grls grao gpush"
    complete -xc g -a gst -d "Status Short"
    complete -xc g -a glg -d "Log Graph Short"
    complete -xc g -a ga -d "Add"
    complete -xc g -a ga. -d "Add ALL"
    complete -xc g -a gau -d "Add Untracked"
    complete -xc g -a gco -d "Git checkout"
    complete -xc g -a gci -d "Commit Verbose"
    complete -xc g -a gcim -d "Commit with CLI Message"
    complete -xc g -a gac -d "Add ALL AND Commit Verbose"
    complete -xc g -a gacm -d "Add ALL AND Commit with CLI Message"
    complete -xc g -a grls -d "List remotes"
    complete -xc g -a grao -d "Remote Add Origin"
    complete -xc g -a gpush -d "Push Master to Origin"

Can anyone confirm if this is a bug or if I misused the `complete` feature?

Fish Version: fish, version 2.6.0
OS: Linux manjaro-vm 4.13.2-1-MANJARO
Terminal: xterm-256color

**Comment by faho** [comment]
Is this using `function --description`? If so, the issue there is that the description is only known once the function has been loaded - which means you'd have to execute it once if you're storing it in a function file, since fish lazy-loads those. See #328.

**Comment by faho** [comment]
Ah, no, wait!

Remove this line:

```fish
complete -xc g -a "gst glg ga ga. gau gco gci gcim gac gacm grls grao gpush"
```

This adds the commands without a description, which means the later descriptions won't be used.

**Comment by zanchey** [comment]
@sanjibukai, did this fix your problem?

**Comment by faho** [comment]
Assuming this is answered.
