### ISSUE TITLE
showing the next (or previous) suggestion

### ISSUE THREAD

**Issue by tt6** [fish-shell/fish-shell#4606]
is it possible to make the shell display next or previous suggestions starting with the same 'prefixes'?

for instance it would be handy to cycle through

    nmcli con

commands in history

**Comment by zanchey** [comment]
Does pushing the up key do what you want?

**Comment by faho** [comment]
@tt6: Ping? Have you tried just entering that `nmcli con` and pressing the up-arrow? Does that work for you?

**Comment by faho** [comment]
Closing for lack of answer. @tt6: I'd be happy to reopen if there is still something to discuss here.

**Comment by tt6** [comment]
thanks, i thought `c-p` and `c-n` would go back in history but now i see that they are bound to `up-or search` to consider the previous string on the commandline
