### ISSUE TITLE
Relase patch version for iTerm fix

### ISSUE THREAD

**Issue by chamini2** [fish-shell/fish-shell#4607]
As asked for in [this comment](https://github.com/fish-shell/fish-shell/commit/879c62cbe14d8bc16e8bc1998bae87d4159589dc#commitcomment-26064762) and [this comment](https://github.com/fish-shell/fish-shell/issues/4521#issuecomment-352222926). The PR https://github.com/fish-shell/fish-shell/pull/4575 fixed a problem for iTerm users that every time we open the terminal interferes with our workflow.

I think this is a perfect example where semver shines, please release a 2.7.1 version with this small fix, cherry-picked if necessary.

**Comment by getaaron** [comment]
👍👌🏻🎊

**Comment by chamini2** [comment]
Are we getting this for the homebrew release?

**Comment by lgarron** [comment]
Looks like the homebrew formula just updated!
https://github.com/Homebrew/homebrew-core/commit/4cf95cf37d23641082805402a4244961bc505bc1
