### ISSUE TITLE
The help command visit a 404 page on macOS

### ISSUE THREAD

**Issue by wimi9u0** [fish-shell/fish-shell#4613]
fish version 2.7.0
macOS 10.13.2
The help command takes me to visit "https://fishshell.com/docs/2.7/index.html" which is a 404 page.

**Comment by zanchey** [comment]
I suspect @ridiculousfish hasn't had a chance to upload the documentation yet.

**Comment by ridiculousfish** [comment]
Oh shame on me. This really needs to be automated - someday I'll migrate to GitHub pages. Anyways they're uploaded now. Thanks for filing!
