### ISSUE TITLE
test returned eval errors invalid precision 

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#4614]
fish, version 2.7.0-581-g884092d1

I just compiled and installed fishshell from latest clone of git, after that there will be two lines of error messages after every prompt:

    test returned eval errors:
               invalid precision:

Nothing more.

1. So what is the meaning of these two lines?

2. Most importantly, what are the line numbers of those lines that cause the errors?
I think this problem has been mentioned by many user, fish-shell does not tell the line number where `test` expression is not correct.

3. Actually, there is another error caused  by the new version of fish-shell, the `.`(dot) command, which is used to load another fish snippet file into config.fish. When I use this in config.fish:

        . /path/file.fish

    It says:

         The file "." is not executable by this user

**Comment by faho** [comment]
>Actually, there is another error caused by the new version of fish-shell, the .(dot) command, which is used to load another fish snippet file into config.fish.

The `.` function has been removed. Use `source`, which it was an alias for.

>Most importantly, what are the line numbers of those lines that cause the errors?

Yes, we should add those.

>So what is the meaning of these two lines?

The only mention of "invalid precision" I can find in our codebase is in the `printf` builtin. It's printed when you have a format like `%.*f`, and the next argument (which is used for the `.*` precision specifier) is larger than INT_MAX.

I.e.

```fish
printf '%.*f\n' 23000022222220 2525
```

will print `invalid precision: 23000022222220`.

How `test` gets that error I don't know, and it's kind of hard to figure out when that message just comes out of nowhere.

See #4617.

**Comment by c02y** [comment]
>The only mention of "invalid precision" I can find in our codebase is in the printf builtin. It's printed when you have a format like %.*f, and the next argument (which is used for the .* precision specifier) is larger than INT_MAX.

> I.e.

> printf '%.*f\n' 23000022222220 2525

> will print invalid precision: 23000022222220.

> How test gets that error I don't know, and it's kind of hard to figure out when that message just comes out of nowhere.

> See #4617.

But the same configuration file is not wrong when I'm using previous version of fish (2.7b1)

**Comment by faho** [comment]
>But the same configuration file is not wrong when I'm using previous version of fish (2.7b1)

Which is why I'd love to figure out where this is coming from. But with how unclear that error message is, and how common using `test` is, it's kinda hard to figure out.

**Comment by floam** [comment]
I imagine some level of the `-d` flag when starting fish might point to where this is cropping up.

**Comment by c02y** [comment]
I'll try to bisect my whole config.fish to get the wrong positions.

**Comment by floam** [comment]
That's kind of strange, the error ought to be "invalid integer". I wonder why that one is being reported.
