### ISSUE TITLE
No rule to make target `include/muParserFixes.h', needed by `muParser_lib_muParser.o'.  Stop.

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#4616]
I was trying to compile and install fish-shell from the latest clone of git according to the following instructions:

    autoreconf --no-recursive #if building from Git
    ./configure
    make
    sudo make install

In step "make", it printed the following error messages: 

    make[1]: Entering directory `/home/chz/fish-shell/muparser-2.2.5'
    make[1]: *** No rule to make target `include/muParserFixes.h', needed by `muParser_lib_muParser.o'.  Stop.
    make[1]: Leaving directory `/home/chz/fish-shell/muparser-2.2.5'
    make: *** [muparser-2.2.5/lib/libmuparser.a] Error 2

**Comment by faho** [comment]
This works for me on 884092d13baa6151a52a2e1625fa7b76647f7746, with those precise instructions.

When you say "the latest clone of git", which commit do you mean? Is it before or after ec2b38053e4d70a54167a18da52920104c2abe2f? See `git log`s output.

**Comment by c02y** [comment]
I'm using the same commit(884092d)

**Comment by faho** [comment]
What are the versions of the tools involved? `make --version` and `autoreconf --version`?

**Comment by zanchey** [comment]
Probably you need to run `make clean` before `make` as a one-off.

**Comment by c02y** [comment]
> What are the versions of the tools involved? make --version and autoreconf --version?

@faho 

    $ make --version
    GNU make 3.8.1
    $ autoreconf --version
    autoreconf (GNU Autoconf) 2.69

**Comment by c02y** [comment]
> Probably you need to run make clean before make as a one-off.

@zanchey  

I compiled and installed fish-shell from git many times, normally, I don't have to `make clean` and after I `make`, the `./fish --version` will be something like "fish, version 2.7.0-581-g884092d1"

According to your suggestion, I "make clean" and "make", no errors, but `./fish --version` is "fish, version unknown", and after I "sudo make install", there are many errors after every prompt.

    set: Unknown option “-a”
    /usr/share/fish/functions/history.fish (line 20):
        set -a options 'h/help' 'c/contains' 'e/exact' 'p/prefix'
        ^
    in function “history”
            called on line 1037 of file ~/.config/fish/config.fish
            with parameter list “--merge”
    
    in function “h”
            called on line 158 of file ~/.config/fish/config.fish
    
    in function “fish_prompt”
            called on standard input
    
    in command substitution
            called on standard input
    
    set: Unknown option “-a”
    /usr/share/fish/functions/history.fish (line 21):
        set -a options 'C/case-sensitive' 'R/reverse' 'z/null' 't/show-time=?' 'n#max'
        ^
    in function “history”
            called on line 1037 of file ~/.config/fish/config.fish
            with parameter list “--merge”
    
    in function “h”
            called on line 158 of file ~/.config/fish/config.fish
    
    in function “fish_prompt”
            called on standard input
    
    in command substitution
            called on standard input
    
    set: Unknown option “-a”
    /usr/share/fish/functions/history.fish (line 24):
        set -a options 'S-search' 'D-delete' 'M-merge' 'V-save' 'X-clear'
        ^
    in function “history”
            called on line 1037 of file ~/.config/fish/config.fish
            with parameter list “--merge”
    
    in function “h”
            called on line 158 of file ~/.config/fish/config.fish
    
    in function “fish_prompt”
            called on standard input
    
    in command substitution
            called on standard input
    
    argparse: No option specs were provided
    set: Unknown option “-a”
    /usr/share/fish/functions/history.fish (line 20):
        set -a options 'h/help' 'c/contains' 'e/exact' 'p/prefix'
        ^
    in function “history”
            called on line 1038 of file ~/.config/fish/config.fish
            with parameter list “--save”
    
    in function “h”
            called on line 158 of file ~/.config/fish/config.fish
    
    in function “fish_prompt”
            called on standard input
    
    in command substitution
            called on standard input
    
    set: Unknown option “-a”
    /usr/share/fish/functions/history.fish (line 21):
        set -a options 'C/case-sensitive' 'R/reverse' 'z/null' 't/show-time=?' 'n#max'
        ^
    in function “history”
            called on line 1038 of file ~/.config/fish/config.fish
            with parameter list “--save”
    
    in function “h”
            called on line 158 of file ~/.config/fish/config.fish
    
    in function “fish_prompt”
            called on standard input
    
    in command substitution
            called on standard input
    
    set: Unknown option “-a”
    /usr/share/fish/functions/history.fish (line 24):
        set -a options 'S-search' 'D-delete' 'M-merge' 'V-save' 'X-clear'
        ^
    in function “history”
            called on line 1038 of file ~/.config/fish/config.fish
            with parameter list “--save”
    
    in function “h”
            called on line 158 of file ~/.config/fish/config.fish
    
    in function “fish_prompt”
            called on standard input
    
    in command substitution
            called on standard input
    
    argparse: No option specs were provided

**Comment by c02y** [comment]
If I checkout into 2.7.b1 branch, everything is normal, no errors in compiling and installation process and no errors after fish prompt, but if I checkout into 2.7.0 branch or using the latest version of commit when I posted this issue(884092d) or the latest version of commit currently(9907a8df), the result are the same, just like my early posts.

**Comment by faho** [comment]
>after I "sudo make install", there are many errors after every prompt.

That's your old fish sessions picking up the new functions. Close all existing fish sessions and it'll work.

**Comment by c02y** [comment]
> That's your old fish sessions picking up the new functions. Close all existing fish sessions and it'll work.

Yes, indeed. Those "many errors" are gone. Now I got https://github.com/fish-shell/fish-shell/issues/4614

And another question, after compiling and installing, the version of fish will be "fish, version unknown", but I really like the old "fish, version 2.7.0-581-g884092d1" format, why changing it?

**Comment by faho** [comment]
>And another question, after compiling and installing, the version of fish will be "fish, version unknown", but I really like the old "fish, version 2.7.0-581-g884092d1" format, why changing it?

It's an issue related to changes in the build system - we'd like to switch to cmake.

So, this seems to be fixed - it just needed a `make clean`.
