### ISSUE TITLE
fish_update_completions doesn't work when using asdf python plugin

### ISSUE THREAD

**Issue by jschank** [fish-shell/fish-shell#4618]
Using Fish version 2.7.0
uname -a = Darwin sulaco 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
$TERM = xterm-256color

I understand this is probably not directly a problem with fish, but I am hoping you can offer some advice as to why it happens.

When I use asdf (see: https://github.com/asdf-vm/asdf) to manage my project specific ruby, nodejs, and python. I get this behavior.

$ fish_update_completions
No such command in 2.7.14 of python

Similarly, if I run 
$ fish_config
No such command in 2.7.14 of python

----

When I removed asdf's python plugin. Correct functionality returned.

I believe the blame lies with asdf's python plugin. But I was wondering if you had any thoughts as to why python would get involved in updating completions, etc.

Thanks
jschank

**Comment by faho** [comment]
>But I was wondering if you had any thoughts as to why python would get involved in updating completions, etc.

That's easy to answer: The man page parser and the fish_config "web server" are python utilities. See [share/tools](https://github.com/fish-shell/fish-shell/tree/master/share/tools). They are invoked via functions (see `functions fish_config` and `functions fish_update_completions`).

I don't really know asdf - what does this do? Maybe there's some way we can make this work together.

**Comment by faho** [comment]
@jschank: Does that answer your question?

**Comment by jschank** [comment]
Yep, it does help. Asdf is a tool like rbenv, rvm, chruby, nvm, virtualenv, etc. but it is a single too that is supposed to work with many languages. I suspect, that when using asdf for python, it is interfereing with whatever system/native python that fish uses. It seems to me, that *if* there is a fix to be made, it would lie in asdf or its python plugin.

**Comment by faho** [comment]
What is confusing me is that both of these things essentially do something like this

```fish
function fish_config --description Launch\ fish\'s\ web\ based\ configuration
    set -lx __fish_bin_dir $__fish_bin_dir
    if command -sq python3
        python3 "$__fish_datadir/tools/web_config/webconfig.py" $argv
    else if command -sq python2
        python2 "$__fish_datadir/tools/web_config/webconfig.py" $argv
    else if command -sq python
        python "$__fish_datadir/tools/web_config/webconfig.py" $argv
    end
end
```

So they just call the first python they find to execute a ".py" script, with the full absolute path and some arguments. Where is that "no such command" coming in?

Could you post the output of `type python{3,2,}`?

**Comment by jschank** [comment]
Sorry it took so long, I had to re-install the python plugin for asdf, and then install python with it.
The strange thing is that things appear to be working now...
```
$ asdf install python 2.7.14
python-build 2.7.14 /Users/jschank/.asdf/installs/python/2.7.14
python-build: use openssl from homebrew
python-build: use readline from homebrew
Downloading Python-2.7.14.tar.xz...
-> https://www.python.org/ftp/python/2.7.14/Python-2.7.14.tar.xz
Installing Python-2.7.14...
python-build: use readline from homebrew
Installed Python-2.7.14 to /Users/jschank/.asdf/installs/python/2.7.14
```
To answer your original question...
```
$ type python{3,2,}
python3 is /usr/local/bin/python3
python2 is /Users/jschank/.asdf/shims/python2
python is /Users/jschank/.asdf/shims/python
```
Perhaps there was an update to asdf, or the python plugin... lemme dig into that a little

**Comment by jschank** [comment]
hmmm, asdf was released recently - but it looks like these commits have to do with updating shellcheck to lint the scripts.

The asdf-python plugin hasn't been updated since  end of october, so I doubt that's a factor.

**Comment by faho** [comment]
>`python3 is /usr/local/bin/python3`

That means it's not calling the asdf shim, since these functions try python3 first.

What happens if you try

```fish
python2 "$__fish_datadir/tools/web_config/webconfig.py"
```

?

**Comment by jschank** [comment]
> That means it's not calling the asdf shim, since these functions try python3 first

I would expect that, because I didn't install any python3 versions. Only 2.7.14 (which is ahead of the normal system python - I think that's 2.7.10)

```
$ python2 "$__fish_datadir/tools/web_config/webconfig.py"
Web config started at 'file:///Users/jschank/.cache/fish/web_config-MERX25.html'. Hit enter to stop.
::ffff:127.0.0.1 - - [29/Dec/2017 16:53:59] code 403, message Forbidden, path /apple-touch-icon-precomposed.png
::ffff:127.0.0.1 - - [29/Dec/2017 16:53:59] code 403, message Forbidden, path /apple-touch-icon.png

Shutting down.
```

Also tried python3

```
$ python3 "$__fish_datadir/tools/web_config/webconfig.py"                                                                      13.2s
Web config started at 'file:///Users/jschank/.cache/fish/web_config-FQ1DDE.html'. Hit enter to stop.

Shutting down.
```

In both cases, the fish configurator opened in a browser.

**Comment by faho** [comment]
Okay, so there was probably some issue with your previous asdf install.

**Comment by jschank** [comment]
Agreed. I think closing it is best. I appreciate you spending so much time on this. Your initial answer will point me in the right direction, should the problem resurface.

Happy New Year!

**Comment by jpinnix** [comment]
Thanks to this issue I was able to get on the right path to get `fish_config` working again. I just had to reshim Python 3 again.
