### ISSUE TITLE
Unexpected printf behaviour with printf empty string command substitution

### ISSUE THREAD

**Issue by jensbrks** [fish-shell/fish-shell#4623]
```
> fish --version
fish, version 2.7.0
> echo $version
2.7.0
> uname -a
Linux laptop 4.14.6-1-ARCH #1 SMP PREEMPT Thu Dec 14 21:26:16 UTC 2017 x86_64 GNU/Linux
> echo $TERM
rxvt-unicode-256color
```
First of all, this is my first time opening an issue so if there's anything I can/should improve, please let me know. I'm all ears.

**Problem**:
Whenever a `printf` command substitution passes an empty string to `printf`, the text following the command substitution, in the same string, doesn't print.

**Steps to reproduce**:
1. Start a fish shell
2. type in `printf '%s\n' (printf '')'Hi'` and hit enter
3. Start a bash shell
4. type in `printf '%s\n' $(printf '')'Hi'` and hit enter

I have, as suggested, posted an asciinema clip to better illustrate the issue:
https://asciinema.org/a/RwyrrJ1LAmh81P2SIiMBVie1f
(Please excuse the grammar mistake 'wheter', this should've been 'whether')

**Comment by faho** [comment]
Soo... this has absolutely nothing to do with `printf`. It's an expansion thing - printf receives no arguments (after the format) in this case, so it prints nothing.

See http://fishshell.com/docs/current/index.html#cartesian-product.

You know brace expansion? That `echo {/usr,}/{s,}bin` thing? That expands "everything with everything". In fish, all expansions work like that. So when you do `$PATH/something`, you'll get `/usr/bin/something` and `/bin/something` and so on. Only, when one of the expansions expands to nothing, expanding "everything with everything" collapses the entire thing.

To avoid this, either first assign the command substitution to a variable and use quotes, or change it so it always prints at least an empty line - here `(printf '\n')` would work.

**Comment by jensbrks** [comment]
Thank you for clarifying.
Indeed it does print if `greet` executed `printf '\n'` when no arguments were given.
I'm closing this as it's clearly stated in the documentation, silly me.

Keep up the good work!
