### ISSUE TITLE
Can't launch app with custom variables

### ISSUE THREAD

**Issue by damien-lloyd** [fish-shell/fish-shell#4625]
If I type this command in bash:

LIBGL_DRI3_DISABLE=1 steam

It works. That same command doesn't work in the fish shell. Just typing the app works in both shells, except fish doesn't seem to handle variable assignment and app execution in a single command.

**Comment by krader1961** [comment]
Fish doesn't support that syntax. Use the `env` command: `env LIBGL_DRI3_DISABLE=1 steam`.
