### ISSUE TITLE
Add dedicated section about array variables, generated commands and argv handling to documentation

### ISSUE THREAD

**Issue by wilhelmy** [fish-shell/fish-shell#4630]
Any opinions?

Personally, I think the documentation could be more extensive in this area and it's something I fumble around with clumsily.

I might write one given positive resonance (if I write it, I want to know I'm not wasting my time and see it merged and I will keep working on it until it meets the demands of any possible criticism) and enough time in the weeks to come.

**Comment by faho** [comment]
What exactly would you like to add? What do you "fumble around with clumsily"?

We have a [section on variables](https://fishshell.com/docs/current/index.html#variables) with a subsection "Arrays". That contains the information, though it could probably do with some polish, and we might want to reorder it to come before universal variables and maybe even scope.

I'm not sure what you mean with "generated commands", and I think "argv handling" basically boils down to handling arrays.

Obviously all our documentation could do with some actually nice writing - I always feel like whatever I add is both too matter-of-fact and convoluted.

**Comment by wilhelmy** [comment]
I'd like to add information on reordering array elements as well as generating arrays in order to execute them as commands as well as looping over arrays in order to handle parameters as well as what exactly happens in terms of variable expansion when an array is part of a statement. Maybe this belongs into a tutorial instead of the documentation.

**Comment by zanchey** [comment]
Examples of that kind would work well in the manual, I think.
