### ISSUE TITLE
cmake/ninja build does not update test files

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#4633]
When the test files (in tests/) are updated, the cmake build does not get them, so another `ninja test` run will still run the old tests.

This just bit me again in #4632.

**Comment by mqudsi** [comment]
@mrpilot2 @ridiculousfish does 843ac2554dec950df21420be06b808fc01d14b0b close this issue?

**Comment by faho** [comment]
It was meant to - the "fixes" tag was dropped when it was merged, but it was in the PR. So I'm closing.
