### ISSUE TITLE
Problems with fish and docker

### ISSUE THREAD

**Issue by italomaia** [fish-shell/fish-shell#4635]
fish, version 2.6.0

When I attach to a docker container with fish, I get the message below:

```
Welcome to fish, the friendly interactive shell
<W> fish: Current terminal parameters have rows and/or columns set to zero.
<W> fish: The stty command can be used to correct this (e.g., stty rows 80 columns 24).
```

When using the console under this circunstance, the text breaks quite badly. To reproduce, run a ubuntu docker, install fish and, from another terminal, docker exec -it into it running the fish command.

**Comment by faho** [comment]
>`docker exec -it`

The man page for `docker-exec` tells me the "-t" option is short for "--tty". That's likely to have an impact here. Have you tried without it? E.g. just `docker exec`?

**Comment by faho** [comment]
I can't reproduce this with fish 2.7.1, which is the current version in [our PPA](https://launchpad.net/~fish-shell/+archive/ubuntu/release-2). And the "-t" is indeed necessary.

Can you try upgrading to that?

**Comment by italomaia** [comment]
With fish version 2.2.0-3 I could not reproduce the error. Weird. Thanks for the feedback.
