### ISSUE TITLE
More accurate & space-efficient multi-line?

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4637]
I'm curious as to whether this was a purposeful decision or if it's just the case as a result of the particular approach taken to implement a certain feature/component: in fish, the first soft line break in a command *appears* indented to begin at the same column as the head, but in reality, it's not.

e.g.

```fish
mqudsi@Blitzkrieg /m/c/U/Mahmoud> echo "Hello
                                  world"
Hello
world
```

Whereas in other shells, eg bash, a soft line break (shift+enter) starts off at the start of the screen line (with a `> ` indicator):

```bash
mqudsi@Blitzkrieg:/mnt/c/Users/Mahmoud$ echo "Hello
> world"
Hello
world
```

I think this is a bit confusing since it may be hard to tell what's actually indented and what's not in applications where the indentation matters/you're not just writing a fish script in the repl where indentation is just a form of syntax highlighting, if you will.

Additionally, imagine a standard 80px terminal with a long prompt:
```
################################################################################
#mqudsi@Blitzkrieg customized_prompt /m/c/U/Mahmoud> echo "Hello               #
#                                                    world"                    #
#Hello                                                                         #
#world                                                                         #
################################################################################
```

The amount of space available is severely constrained.

Apologize if this has been discussed; I couldn't find an existing issue by searching.

**Comment by faho** [comment]
#3382 is definitely related, though I can see how you wouldn't find that.

**Comment by faho** [comment]
On second thought, let's keep this in #3382!
