### ISSUE TITLE
Improve $history lookup times

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#4650]
Since the solution in https://github.com/fish-shell/fish-shell/pull/4461 was rejected, it would be great to have an alternative/performant way of referencing history items, at the least for the "most recent history item" (which is certainly the most common use case).

For example, I have the following setup (to mimic [bash's `!!` functionality](https://stackoverflow.com/a/15137462)):

```fish
function bind_bang
  switch (commandline -t)
  case "!"
    commandline -t $history[1]; commandline -f repaint
  case "*"
    commandline -i !
  end
end

bind ! bind_bang
```

And it's noticeably slower than @krader1961's alternative (i.e. using `history item 1` rather than `$history[1]`), to the point it actually interrupts my thought process while I wait for it to complete the previous command.

**Comment by ridiculousfish** [comment]
54cefeb5b14bfed76451679e9fea356f8789f2b4 makes the normal history slicing like `$history[1]` much faster by special casing it in variable expansion. That should satisfy this - thanks for filing!
