### ISSUE TITLE
No apt completion for command policy

### ISSUE THREAD

**Issue by Ygster** [fish-shell/fish-shell#4652]
Environment :
---
Fish version : fish, version 2.7.0
Linux 4.14.0-2-amd64 #1 SMP Debian 4.14.7-1 (2017-12-22) x86_64 GNU/Linux

-----
The is no completion for the apt policy command unlike with apt install for example.

**Comment by faho** [comment]
That command doesn't appear to be a thing, according to [the man page](https://manpages.debian.org/unstable/apt/apt.8.en.html).

**Comment by Ygster** [comment]
It's the command apt-cache policy directly with apt.
It's the same for apt-cache search and apt search.
The command works but indeed I don't find any reference in any documentation.

**Comment by zanchey** [comment]
Yeah, it's only in Debian 9's version of apt (1.4), not in 1.0.
