### ISSUE TITLE
Strange prompt with powerline

### ISSUE THREAD

**Issue by namkhaib** [fish-shell/fish-shell#4658]
`fish --version` & `echo $version`: 2.7.1
`uname -a`: 4.14.12-1-MANJARO x86_64 GNU/Linux
`echo $TERM`: xterm-256color

Using powerline in fish results in a very strange prompt(s):

![fishbug](https://user-images.githubusercontent.com/33267474/34902269-0d8878e8-f7e6-11e7-9733-72cf1ef29314.png)

~/.config/fish/config.fish:

>#Neofetch
>#neofetch --ascii_bold off
>
>#Editor
>export EDITOR=vim
>
>#Powerline
>set fish_function_path $fish_function_path "/usr/lib/python3.6/site-packages/powerline/bindings/fish"
>powerline-setup
>
>#Tmux
>#test $TERM != "screen"; and exec tmux new-session -A -s $USER
>#tmux -Ltest kill-server
>#tmux -vv -Ltest -f/dev/null new
>
>#Fortune
>#fortune | lolcat

It can be a <a href=https://github.com/powerline/powerline>powerline</a> bug?

**Comment by faho** [comment]
I would assume this is a powerline bug - "kwargs" is a python term, short for "keyword arguments". So I'd assume that there's an issue with your theme or something there.

Also the powerline people are much more likely to be able to help you. Once you've opened an issue there, feel free to CC me!
