### ISSUE TITLE
down-line in pager doesn't wrap

### ISSUE THREAD

**Issue by hamon-e** [fish-shell/fish-shell#4669]
Hello,

Seems that last update (2.7.1) broke circular tab completions

See this example,
(first command pressing lot of TAB)
(second command pressiong lot of SHIFT-TAB)
https://asciinema.org/a/bShqIYrla3TCMwILAyAZShYRs

As we can see the first completion doesn't return to the beginning

**Comment by faho** [comment]
This works for me on both 2.7 and master.

What are these keys bound to? E.g. what does `bind \t` say?

**Comment by hamon-e** [comment]
This is the output

`bind \t complete`

**Comment by hamon-e** [comment]
Well in fact it's linked to the function `down-or-search` as this issue #4331 said.

**Comment by faho** [comment]
Wait... which keys are you pressing? Can you reproduce this issue purely by pressing tab, or shift-tab?

**Comment by hamon-e** [comment]
This this how to reproduce

`
function the_complete
  if commandline --paging-mode
    down-or-search
  else
    commandline -f complete
  end
end
`

`bind -M insert \t the_complete` (because i use vi mode)
(btw it's not really usefull that bind \t doesn't show the bindings for \t in all mode)

**Comment by faho** [comment]
Note: `down-or-search` is a function that in this case just executes the "down-line" bind function.

You'll notice the same if you use ctrl-n (which is bound to down-line). The issue is that our pager logic doesn't properly wrap in a number of cases.
