### ISSUE TITLE
Build Issue: FISH-BUILD-VERSION-FILE is not created on macOS builds

### ISSUE THREAD

**Issue by dsMrP** [fish-shell/fish-shell#4671]
Using the build instructions for macOS: https://github.com/fish-shell/fish-shell#xcode-build-and-install the following failure occurs...

```
/Users/david/dev/fish-shell/src/fish_version.cpp:12:10: fatal error: 'FISH-BUILD-VERSION-FILE' file not found
#include "FISH-BUILD-VERSION-FILE"
         ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

** INSTALL FAILED **
```

It appears that the generate-version-header target is not executed in the (xcodebuild install) command

**Comment by dsMrP** [comment]
Regressed from change d09210c

**Comment by zanchey** [comment]
Yes, although the plan is to move to CMake-only Xcode builds at some stage, we're not there yet!

**Comment by dsMrP** [comment]
Works like a bought one. Thanks!
