### ISSUE TITLE
Unknown builtin 'funced'

### ISSUE THREAD

**Issue by bryaan** [fish-shell/fish-shell#4677]
I'm trying to redefine the fish builtin `funced`.  Following the suggestion from https://github.com/fish-shell/fish-shell/issues/224 I tried prefixing with both `builtin` and `command` but neither work.

```fish
function funced
  command funced --editor $EDITOR $argv
end

fish: Unknown command 'funced'
~/src/dotfiles/build/shell/fish.fish (line 1):
command funced --editor $EDITOR
        ^
in function 'funced'
	called on standard input
	with parameter list 'fish_prompt'
```

```fish
function funced
  builtin funced --editor $EDITOR $argv
end

~/src/dotfiles/build/shell/fish.fish (line 15): Unknown builtin 'funced'
  builtin funced --editor $EDITOR
```

**Comment by faho** [comment]
As `type funced` will tell you, `funced` is a function.

That means to use it in a function you make yourself, you have three options:

- Modify it directly (`funced funced`)

- Call your wrapper something different and invoke `funced` from it

- Copy the original funced to some other name (`functions --copy funced SOMENEWNAME`)

**Comment by bryaan** [comment]
Thanks.
