### ISSUE TITLE
builtin file __fish_git_prompt.fish

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#4679]
fish, version unknown

There is a builtin file which is located in /usr/share/fish/functions/__fish_git_prompt.fish
(other two are svn and hg files, they are combined with one single file named __fish_vcs_prompt.fish which is very nice)

I have been using another [git_prompt configuration file](https://github.com/mariuszs/informative_git_prompt) since a long time ago. The git prompt is like this:

    (master|✚2166…)

But recently I decide to search for/write a configuration file for svn-prompt, so this builtin file came across to me.

But I I notice that the builtin git version is very week comparing to svn version, builtin git prompt shows only branch name even though there are many files which are modified or deleted or something like that.

builtin svn-prompt version(with colors):
    
    (890|M?!)

builtin git-prompt version:

    (master)

So maybe you can get some useful info from https://github.com/mariuszs/informative_git_prompt and improve __fish_git_prompt.fish.

**Comment by faho** [comment]
>So maybe you can get some useful info from https://github.com/mariuszs/informative_git_prompt and improve __fish_git_prompt.fish.

Read the README there:

>Informative git prompt was merged into Fish shell!

>https://github.com/fish-shell/fish-shell/pull/880

The issue is that fish's git prompt has a few configuration options. So you'll have to do something like

```fish
set -g __fish_git_prompt_show_informative_status yes
```

to get the informative version.

**Comment by c02y** [comment]
> Read the README there:

Sorry, didn't notice that. 

But after 
> set -g __fish_git_prompt_show_informative_status yes

all parts of info in git-prompt are the same colors, not like svn-prompt, check the following screenshot, the left is in a svn repo, the right is in a git repo. 
![snapshot6](https://user-images.githubusercontent.com/2135996/35269086-f7d0b488-0065-11e8-9595-06816f3d7660.png)

=====================
**UPDATE**:

After `fish_config` and choose "Informative Vcs", it seems I have to add a lot of color-related configurations such as:

    if not set -q __fish_git_prompt_show_informative_status
        set -g __fish_git_prompt_show_informative_status 1
    end
    if not set -q __fish_git_prompt_hide_untrackedfiles
        set -g __fish_git_prompt_hide_untrackedfiles 1
    end

    if not set -q __fish_git_prompt_color_branch
        set -g __fish_git_prompt_color_branch magenta --bold
    end
    if not set -q __fish_git_prompt_showupstream
        set -g __fish_git_prompt_showupstream "informative"
    end
    if not set -q __fish_git_prompt_char_upstream_ahead
        set -g __fish_git_prompt_char_upstream_ahead "↑"
    end
    if not set -q __fish_git_prompt_char_upstream_behind
        set -g __fish_git_prompt_char_upstream_behind "↓"
    end
    if not set -q __fish_git_prompt_char_upstream_prefix
        set -g __fish_git_prompt_char_upstream_prefix ""
    end

    if not set -q __fish_git_prompt_char_stagedstate
        set -g __fish_git_prompt_char_stagedstate "●"
    end
    if not set -q __fish_git_prompt_char_dirtystate
        set -g __fish_git_prompt_char_dirtystate "✚"
    end
    if not set -q __fish_git_prompt_char_untrackedfiles
        set -g __fish_git_prompt_char_untrackedfiles "…"
    end
    if not set -q __fish_git_prompt_char_conflictedstate
        set -g __fish_git_prompt_char_conflictedstate "✖"
    end
    if not set -q __fish_git_prompt_char_cleanstate
        set -g __fish_git_prompt_char_cleanstate "✔"
    end

    if not set -q __fish_git_prompt_color_dirtystate
        set -g __fish_git_prompt_color_dirtystate blue
    end
    if not set -q __fish_git_prompt_color_stagedstate
        set -g __fish_git_prompt_color_stagedstate yellow
    end
    if not set -q __fish_git_prompt_color_invalidstate
        set -g __fish_git_prompt_color_invalidstate red
    end
    if not set -q __fish_git_prompt_color_untrackedfiles
        set -g __fish_git_prompt_color_untrackedfiles $fish_color_normal
    end
    if not set -q __fish_git_prompt_color_cleanstate
        set -g __fish_git_prompt_color_cleanstate green --bold
    end

    if not set -q __fish_prompt_normal
        set -g __fish_prompt_normal (set_color normal)
    end

Why not make it the default value for git-prompt?

===============
**UPDATE**:

    set -g __fish_git_prompt_showcolorhints true

**Comment by faho** [comment]
>Why not make it the default value for git-prompt?

Because

- It's a bunch of information that people might not know what to do with

- It's quite slow on larger repositories

Anyway, that should answer your question.

**Comment by c02y** [comment]
> It's a bunch of information that people might not know what to do with

Yes, and the doc part at the beginning of the files is a good thing.

> It's quite slow on larger repositories

Indeed, so I use the following configuration to disable the fish_vcs_prompt when it is slow:

    set -g enable_fish_vcs_prompt 1
    function fdv -d 'Once prompt is slow, disable fish_vcs_prompt using this function'
        set -g enable_fish_vcs_prompt 0
    end

    ## put the following part in fish_right_prompt
    # builtin support for git/svn/hg
    if test $enable_fish_vcs_prompt -eq 1
        __fish_vcs_prompt
    end

And I'm trying to make the **disable** automatic according to the time of execution of `__fish_vcs_prompt`.
