### ISSUE TITLE
<(command) in fish

### ISSUE THREAD

**Issue by theScrabi** [fish-shell/fish-shell#4682]
Hello in bash there is this construct existing `<( )`. The stdout of the command inside the brackets is redirected, and a file descriptor is returned:
```
$ echo <(echo "hallo welt")
/dev/fd/63
```

So You can write constructs like this:
```
$ cat <(echo "hallo welt")
hallo welt
```

Is something like this possible with fish?

**Comment by faho** [comment]
Fish has the `psub` command that writes its input to a file and prints the name of that file.

So you'd do

```fish
cat (echo "Hallo Welt" | psub)
```

See [the documentation for psub](http://fishshell.com/docs/current/commands.html#psub).

**Comment by theScrabi** [comment]
That is cool :D, but it's a file and no pipe right?

**Comment by faho** [comment]
Short answer: Yes.

Longer answer: By default, yes, but psub technically supports a flag to use a fifo instead. Only that has some issues so I wouldn't currently recommend using it (unless you can guarantee that your output will be smaller than the pipe buffer).

Any reason you want a pipe?

**Comment by theScrabi** [comment]
I see.

**Comment by theScrabi** [comment]
A pipe uses kernel buffer which
1. Is faster
2. May useup write cycles on an ssd
3. When you try to pass passwords or keys /tmp might be unsave
