### ISSUE TITLE
git add from subdirectory broken in master

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4688]
I believe this stems from the recent changes to the git completion scripts, but this time I'm running `git version 2.16.1.72.g5be1f00`.

Attempting to complete `git add` a path from within a subdirectory results in the path relative to the git root being completed.

e.g. (untested pseudocode):

```fish
git init .
mkdir -p subdir
echo "hello" > subdir/file
git add subdir/file
git commit -m "initial commit"
cd subdir
echo "hi" >> file
git add fi<TAB> #this expands to `git add subdir/file` instead of `git add file` 
#this fails with ENOENT if executed
```

(git completions are insanely complicated, it's like another project all unto its own!)

_@faho please feel free to unassign if it's not related to your changes_

**Comment by faho** [comment]
>@faho please feel free to unassign if it's not related to your changes

Nope, that was my fault. Sorry!

The completions used to do something like

```fish
set -l root (command git rev-parse --show-toplevel ^/dev/null)
string replace -- "$PWD/" "" "$root/$file" | string replace "$root/" ":/"
```

which I missed. `git status --porcelain`, like the commands we used previously, always prints all paths relative to the root, so we need to fiddle with that to get paths relative to $PWD instead.

>(git completions are insanely complicated, it's like another project all unto its own!)

Yes, they indeed are!
