### ISSUE TITLE
Using Fish in the Windows 10 WSL environment

### ISSUE THREAD

**Issue by zoomclub** [fish-shell/fish-shell#4689]
After working with the default WSL Bash shell I'm thinking of installing Fish instead, just have a major concern I'd like to verify before I do.

What I discovered to my dismay is that editing .bashrc or .bash_profile files in Windows editors like VSCode does not work. After editing them the WSL side will no longer source them correctly. Here are the issues discussing this: 

https://github.com/Microsoft/WSL/issues/87
https://github.com/Microsoft/WSL/issues/45

My question, is it possible to edit any of the Fish config files in VSCode and still have them be operational via the terminal after the edit? I'm just hoping to setup a bunch of abbr and functions and using a decent text editor to do this is the way to go!

Also, with Fish v3 coming should I wait or still install the current Fish, what will the upgrade experience be like?

**Comment by faho** [comment]
>My question, is it possible to edit any of the Fish config files in VSCode and still have them be operational via the terminal after the edit?

No. Reading those issues, you'll find that it's a problem with windows' filesystem. There's nothing that any WSL-hosted application can do about that.

>Also, with Fish v3 coming should I wait or still install the current Fish, what will the upgrade experience be like?

It'll probably be mostly smooth - we haven't really done too many backwards-incompatible changes. See [the section in CHANGELOG.md](https://github.com/fish-shell/fish-shell/blob/master/CHANGELOG.md#notable-non-backward-compatible-changes).

**Comment by zoomclub** [comment]
Good to know! Looking forward to Fish v3 :1st_place_medal:

**Comment by mqudsi** [comment]
@zoomclub you can always use a symlink to your ntfs partition, and then edit the source file in Windows. 

i.e.

```fish
touch /mnt/c/Users/xxxx/Documents/config.fish
ln -s /mnt/c/Users/xxxx/Documents/config.fish ~/.config/fish/config.fish
```
