### ISSUE TITLE
fish is very unresponsive; how do I debug?

### ISSUE THREAD

**Issue by jacobsa** [fish-shell/fish-shell#4690]
```
> fish --version
fish, version 2.7.1
> uname -a
Linux fourier.syd.corp.google.com 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux
> echo $TERM
screen-256color
```

I find that sometimes fish is extremely unresponsive, apparently taking several seconds before starting commands after I type them and taking awhile after they exit to go back to the prompt. This seems to be worse when my system has recently been under heavy load, but it persists after the load goes away.

I thought for awhile this was the system itself for some reason taking a long time to start processes, but it doesn't happen in bash.

It also doesn't happen when I run `sh -c 'env HOME=$(mktemp -d) fish'`, so I guess it must have to do with my customizations. But I have no idea how to debug this. How can I get information that would help me figure out which local customizations are at fault?

**Comment by faho** [comment]
>How can I get information that would help me figure out which local customizations are at fault?

There are a few things here that can impact this. 

>taking several seconds before starting commands after I type them

After you press enter, what'll happen is that fish fires the "fish_preexec" event. Then it'll execute the command, and then fire the "fish_postexec" event, the "fish_prompt" event and then it'll show the prompt, by executing the "fish_prompt", "fish_right_prompt" and "fish_mode_prompt" functions.

Unfortunately, we don't currently have any form of introspection for events - there's no builtin to for example "list all functions listening to the fish_preexec event", so the best I can recommend is to `grep`.

Something like `egrep -r -- "function .*(-e|--on-event).*" ~/.config/fish` should show all event-listening functions in your fish configuration directory.

**Comment by jacobsa** [comment]
Thanks very much; I'll use that as a starting point.

**Comment by zanchey** [comment]
You can also run your whole fish process under profiling with `fish --profile myprofile.txt`, which times each operation and can give you some insight into slow commands.

**Comment by jacobsa** [comment]
@faho @zanchy: is it possible that fish re-parses its configuration after it starts? My config sources some files from a remote file system that is slow and flaky.

**Comment by faho** [comment]
It doesn't reparse the _config_ as such (as far as I'm aware), but it does reload function files - the stuff in ~/.config/fish/functions.

**Comment by jacobsa** [comment]
To be more specific, I have this in `~/.config/fish/config.fish`:

```
if test -e ~/foo.fish
  . ~/foo.fish
end
```

Then in `~/foo.fish` I have:

```
. /slow/flaky/file/system/bar.fish
source_foo_fish_package hg
```

/slow/flaky/file/system/bar.fish in turn has:

```
function source_foo_fish_package -a pkg
    set -g fish_complete_path /slow/flaky/file/system/$pkg/completions $fish_complete_path
    set -g fish_function_path /slow/flaky/file/system/$pkg/functions $fish_function_path
end
```

Will this cause any files to be read off of `/slow/flaky/file/system` after the initial shell startup?

**Comment by zanchey** [comment]
That will add `/slow/flaky/file/system/$pkg/functions` to the search path, so every command is going to try and stat `/slow/flaky/file/system/hg/functions/whatever_command.fish`... which probably will be slow, yes!

**Comment by faho** [comment]
To be clear: Autoloading kinda throws a wrench into the thing here. Since fish tries to load a function on every command execution (and load function names just when typing for syntax highlighting!), and since it also reloads functions that have changed on disk, this will do a bunch of IO on your slow and flaky file system.

So you don't want to store functions on a slow and flaky filesystem. If you must, instead of putting that directory into $fish_function_path, I'd suggest `source`ing all the files on startup.

**Comment by jacobsa** [comment]
Thanks very much, I think that explains the issue.
