### ISSUE TITLE
Fish showing non-existing --gui command suggestion for gradle 4.4

### ISSUE THREAD

**Issue by skytreeLouis** [fish-shell/fish-shell#4691]
fish, version 2.7.1
Darwin User-MacBook-Air.local 16.7.0 Darwin Kernel Version 16.7.0: Mon Nov 13 21:56:25 PST 2017; root:xnu-3789.72.11~1/RELEASE_X86_64 x86_64
no customizations

about --gui in gradle: 
https://github.com/gradle/gradle/issues/995

steps to reproduce:
1. open fish shell
2. type gradle --
3. press tab

expected behaviour:
--gui not shown

actual behaviour:
--gui shown

**Comment by faho** [comment]
Fixed, thanks!
