### ISSUE TITLE
Function wrapping "cd" doesn't get correct completions

### ISSUE THREAD

**Issue by hamon-e** [fish-shell/fish-shell#4693]
If i write this function:
```
function cdtest -w cd
    cd $argv
end
```
and write `cdtest <TAB>` it doesn't autocomplete like cd does.
Is there something wrong with my function ?

```
fish --version
fish, version 2.7.1-708-gea897fcc
```

**Comment by faho** [comment]
> Is there something wrong with my function ?

No. The issue here is that anything called `cd` itself gets special treatment by the completion machinery - see https://github.com/fish-shell/fish-shell/blob/master/src/complete.cpp#L1468.

This is supposed to go through the "wrap chain", but it seems like it's not doing that correctly.

**Comment by jchilders** [comment]
@hamon-e FYI, I was able to create a `cd` wrapper using the following syntax:

```
function cd --wraps cd
  echo "Using our cd function"
  builtin cd $argv
end
```

This was on 2.7.1.

**Comment by krobelus** [comment]
Fixd by #7843
