### ISSUE TITLE
Where is the color of the selected item in the tab-completion-list defined?

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#4695]
fish, version unknown, compiled and installed from the latest source code.

When you hit `TAB` key in the fish prompt, fish will list all the files/directories in a drop-list, and hitting `TAB` or `S-TAB` will select one item in the list one by one.

I'm using green-on-black as my terminal colour scheme, so the colour of the selected on in the list is basically the same as others (it is just bold). 

If I change the colour scheme of my terminal to black-on-white, the colour of the selected one is terrible too.

So how can I change the attribute (such as colour of fg/bg, underline, bold, etc.,) of the selected one in the list?
![snapshot12](https://user-images.githubusercontent.com/2135996/35673033-3d15cbde-077b-11e8-9b79-e2ee9f4395df.png)

![snapshot13](https://user-images.githubusercontent.com/2135996/35673044-48f8328e-077b-11e8-97f2-b1c5c2d91a69.png)

**Comment by faho** [comment]
It's $fish_color_search_match. Specifically, it only reads the background part of that.

So to set it to blue, use `set fish_color_search_match --background=blue`.

(We should probably change that - both introduce a new variable and allow the foreground to be specified as well)

**Comment by c02y** [comment]
Thanks, it seems good enough.
