### ISSUE TITLE
Exiting fish too soon after startup throws broken pipe error

### ISSUE THREAD

**Issue by Redmega** [fish-shell/fish-shell#4699]
**Version:** fish, 2.7.1
**`uname -a`**: `Darwin USERNAME-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64`
**`echo $TERM`**: `xterm-256color` (iTerm2)

No third party customizations, this is a fresh install of `fish`.

When I exit I get a broken pipe error from iterm2 unless I first call a command or wait 15 seconds.

That is to say, immediately exiting results in a broken pipe error. Ideally it should just exit and not throw an error.

**Comment by faho** [comment]
>No third party customizations, this is a fresh install of fish.

That might not be entirely true. iTerm has this shell integration feature, which causes it to add a bunch of configuration to fish. Can you check in the options menu for that setting and disable it if it is enabled?

And can you print the output of `type fish_prompt`?

**Comment by Redmega** [comment]
I've actually uninstalled fish. I love it but I'm getting a new computer soon so I'd rather try again on the new one. If I have issues I'll open another request. Thanks!

**Comment by liamtoney** [comment]
I'm able to reproduce this issue as well. I'm using iTerm2 and shell integration is not enabled. The output of `type fish_prompt` is
```
fish_prompt is a function with definition
# Defined in /Users/liamtoney/miniconda3/etc/fish/conf.d/conda.fish @ line 42
function fish_prompt
    set -l last_status $status
    if set -q CONDA_LEFT_PROMPT
        __conda_add_prompt
    end
    return_last_status $last_status
    __fish_prompt_orig
end
```
i.e. a miniconda install modified the prompt.

**Comment by zanchey** [comment]
Can you show the error you get?

**Comment by liamtoney** [comment]
One day later, and I am no longer able to reproduce. Please close. I'll comment with the error if I encounter this again. Sorry for the excess notifications. Cheers.
