### ISSUE TITLE
apparent races in signal handling

### ISSUE THREAD

**Issue by JanKanis** [fish-shell/fish-shell#470]
Tracing through the signal handling code a bit, it appears that there's no kind of synchronization or atomics or volatiles used anywhere. The compiler is reordering the hell out of it, so it's probably full of races.

**Comment by faho** [comment]
There's been a whole bunch of changes here (`signal_block` doesn't exist anymore), so I'm guessing this is fixed.

Either way there's been no comments in 6 years, so it doesn't seem useful to keep open.
