### ISSUE TITLE
Hardcoded values in config_cmake.h.in are overriding dynamic results

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4701]
In trying to figure out why the cmake build was `SIGSEGV`ing on Solaris, I finally tracked it down to a mismatch between the curses header (ncurses) and the linked curses library (libcurses, not libncurses) causing all hell to break loose, but I couldn't figure out why that was the case since all the debug/trace code I could add to `CMakeLists.txt` indicated that `HAVE_NCURSES_H` was false.

It turns out there are hardcoded values for all these defines in `config_cmake.h.in` that are overriding the values that are determined when `cmake` is actually run. For example, `#cmakedefine HAVE_NCURSES_H 1` was to blame for that problem on my end.

I'm presuming this isn't intentional, it looks like it may have been created before the appropriate tests were added to the `CMakeLists.txt` and co files, but I wanted to be sure before I ripped it all out.

**Comment by zanchey** [comment]
The `#cmakedefine` lines are the [template instructions for CMake](https://cmake.org/cmake/help/v3.10/command/configure_file.html?highlight=cmakedefine), and should get replaced appropriately.

**Comment by zanchey** [comment]
No, this is definitely right - let's track in #4503 for the problems with curses.

**Comment by mqudsi** [comment]
Yup, you're correct. I was confused because some variables were being defined there and others weren't, but it was the ones that weren't defined that were the problem. See #4704 

Thanks!
