### ISSUE TITLE
math: add bc's -l flag

### ISSUE THREAD

**Issue by igalic** [fish-shell/fish-shell#4703]
exposing bc's `-l` flag would give `math` for full math(lib) support, or at least the support of the following functions:

```
       s (x)  The sine of x, x is in radians.

       c (x)  The cosine of x, x is in radians.

       a (x)  The arctangent of x, arctangent returns radians.

       l (x)  The natural logarithm of x.

       e (x)  The exponential function of raising e to the value x.

       j (n,x)
              The Bessel function of integer order n of x.
```

aside from the question whether this is useful to anyone else, or desired by anyone else… a possible caveat is that `-l` automatically sets the scale to 20, thereby potentially interfering with our `-s` option

**Comment by faho** [comment]
`math` no longer uses `bc`, so there's nothing to expose.

**Comment by zanchey** [comment]
Incidentally we did a bunch of thrashing around on this topic in #1643 and #1723.

**Comment by faho** [comment]
Oh, and since you are interested in mathematical functions, like sin() and such:

Those are now included directly, so e.g. `math -s 5 'sin(3.14)'` will print "0.00159".

**Comment by mvolkmann** [comment]
@faho said "math no longer uses bc", but the documentation at https://fishshell.com/docs/current/commands.html#math still says "It is a very thin wrapper for the bc program".

**Comment by faho** [comment]
@mvolkmann: The docs there are for 2.7.0, I'm talking about git master (which will become 3.0).

**Comment by mvolkmann** [comment]
Ah, thanks for clarifying that.
