### ISSUE TITLE
Start without prompt string and greeting 

### ISSUE THREAD

**Issue by 22459** [fish-shell/fish-shell#4706]
This may very well be an unreasonable request:
I'm trying to address the 3rd. point here, at least on my machine: https://github.com/tmux-plugins/tmux-resurrect/issues/81
It looks like the following:

```
host@host /m/d/agda>
Welcome to fish, the friendly interactive shell
host@host /m/d/agda>
Welcome to fish, the friendly interactive shell
host@host /m/d/agda>
Welcome to fish, the friendly interactive shell
host@host /m/d/agda>
Welcome to fish, the friendly interactive shell
host@host /m/d/agda>
Welcome to fish, the friendly interactive shell
```
So I'm wondering if it's possible to start fish without a greeting and a prompt string via some flag or something, and then I can *probably* make tmux-resurrect call fish with the flag if it's restoring a pane, which should hopefully solve this.

**Comment by 22459** [comment]
My temporary(?) workaround is to call fish via `env fish_greeting= fish`, however that completely disables the greeting.

I solved the other part by wrapping the prompt in a flag that checks whether it's the first prompt, and that detects resurrection by checking if there has been a reboot since the last time a prompt has executed. This however is obviously a hack. Please don't make me keep using this. :'D

```fish
function fish_is_tmux_resurrect #HAXXX (will break. WILL BREAK)
    #hopefully something can be implemented on the tmux resurrect side to avoid hax

    # deduces whether this shell was resurrected by checking whether the last boot or last prompt is newer
    # the boot time is deduced from the uptime and the epoch
    ##
    # deduces the last time a fish prompt was run from the last time a command was run
    # its not a problem that this is global for all shells (at least until i get namespaceing for my projects)
    # because all shells behave the same wrt boot time
    ##
    # basically this will produce bad behaviour (no prompt on first line) when run after a reboot in a non-resurrect context
    # it will also look weird if by an impossible chance (?) a terminal prompt gets truncated and then there is a restore
    #  thats about all the edge cases i could come up with real quick
    set epoch (date '+%s')
    set upseconds (cut -f1 -d. /proc/uptime)
    set lastboot (math $epoch - $upseconds)
    set fish_prompt_last_run (history search --show-time='%s ' -n 1 '.' | cut -d" " -f1)
    return ([ $lastboot -ge $fish_prompt_last_run ]; echo $status) #resurrected if this is the first since last reboot
end

# wrapper around the prompt that doesnt display a prompt on the first command after a temux resurrect
# supposed to fix accumulating prompts in the scrollback when repeatedly restoring a pane without doing anything in it
set fish_is_first_session_prompt_flag 0
function fish_prompt
    set rval (fish_is_tmux_resurrect; eval echo $status) #TODO: there has to be a better way than this
    # if !(firstsession && resurrect), note that true is 0
    if not begin [ $fish_is_first_session_prompt_flag -eq 0 ]; and [ $rval -eq 0 ]; end;
        _fish_prompt
    end
    set fish_is_first_session_prompt_flag 1
end

function _fish_prompt --description 'Write out the prompt'
    set -l color_cwd
    set -l suffix
    switch $USER
        case root toor
            if set -q fish_color_cwd_root
                set color_cwd $fish_color_cwd_root
            else
                set color_cwd $fish_color_cwd
            end
            set suffix '#'
        case '*'
            set color_cwd $fish_color_cwd
            set suffix '>'
    end

    echo -n -s "$USER" @ (prompt_hostname) ' ' (set_color $color_cwd) (prompt_pwd) (set_color normal) "$suffix "
end
```

**Comment by krader1961** [comment]
> This may very well be an unreasonable request

Yes, it is an unreasonable request, IMHO. Since you're sophisticated enough to be attempting this you don't need the fish interactive greeting. Just add this to your *~/.config/fish/config.fish* (which is in my *config.fish*):

```fish
# No greeting when starting an interactive shell.
function fish_greeting
end
```

I'm a grey beard. I use `tmux` every single day because I want to be able to attach to terminal sessions from my primary desktop server or laptop. I too have wanted to "resurrect" tmux sessions but recognize that is impossible other than in very limited situations. So I don't even bother attempting to do so. What the project you linked to is attempting is a fools errand. It cannot be solved for the general case (whether or not the `fish` shell is involved).

You're better off creating a script that you can run which sets up the tmux environment to a known state. For example, I have a `tmux-init` script which I run after a reboot that uses `tmux send-keys` to establish a base line configuration in all my tmux sessions. That script establishes windows, panes, etc., without regard to the state of the system before it was rebooted. It doesn't bother trying to resurrect the state of programs within each tmux window because that is impossible.

You're either making this more complicated than it needs to be or you haven't adequately explained the problem. Frankly, if you're rebooting the system that hosts your tmux sessions so often that this feature is needed something is wrong with your computer or workflow.

**Comment by 22459** [comment]
My computer is a bit unstable when it's running off battery and I haven't been able to figure out why yet.

To be honest all I really expect out of it is to keep my history and scrollback so i can come back to whatever I was working on a while later and still get a good general idea of where exactly I left off and have access to the commands I needed (I find this preferable to writing a "where I left off" file). I never expected to work for executed tasks (though I've run across work on "checkpointing" by accident).

**Comment by 22459** [comment]
It's like having a large lab but every few hours the cleaners wipe the slate.

**Comment by ridiculousfish** [comment]
What would a solution look like here? Could be done by having tmux-resurrect set an environment variable, and having fish_prompt check for the variable and print nothing if set?

**Comment by 22459** [comment]
The main reason I have reservations with regards to doing anything here is that tuning to tmux-resurrect seems very specific and limited to a small portion of users, if there even is anyone other than me. (but it would be great if you did do something for this! :) )

So, I can confirm that my current solution does actually work insofar as the restart detection works. I think it's fair to delegate the greeting setting to tmux-resurrect or to just disable the greeting.

The other issue is prompt hiding on a "first command". I think the cleanest way to handle that would probably be as you said; to have an environment variable that enables hiding the prompt on the first command, and then delegate setting the variable that to tmux-resurrect.

After that it's a matter of patching tmux-resurrect, which I have not done yet.

I don't know if there would be a way to make this a more generally useful feature?

**Comment by ridiculousfish** [comment]
I think checking (and then clearing) the env variable in `fish_prompt` and possibly `fish_greeting` is the right way to go. It doesn't sound like there's much here for fish to do so I'm going to close.

Thanks for filing. This sounds like a highly ambitious task! (Also hope your laptop stability improves!)

**Comment by 22459** [comment]
Wait...it's possible to change environment variables externally on the fly?

**Comment by ridiculousfish** [comment]
I'm not sure what you mean by "externally," my suggestion was as simple as:

    function fish_prompt
        if set -q did_tmux_restore
            set -e did_tmux_restore
            return
        end
        echo -n "> "
     end

**Comment by 22459** [comment]
I can't remember actually. I'll maybe try looking into the tmux side of things in a few days.
