### ISSUE TITLE
Wrong completion for a file named “~”

### ISSUE THREAD

**Issue by EFanZh** [fish-shell/fish-shell#4707]
Fish version: 2.7.1

1. Run `touch '~'` in an empty directory
2. Input `ls` in the shell, then press <kbd>Space</kbd> key, then press <kbd>Tab</kbd> key.

Expect `\~` being completed, but actually, `~` is completed.

This bug caused me deleting partial of my home directory, because instead of `ls` command, I was using `rm -r` command.

**Comment by faho** [comment]
Duplicate of #2274. Sorry!
