### ISSUE TITLE
String Match Invert with empty variable / no second argument

### ISSUE THREAD

**Issue by tommyknows** [fish-shell/fish-shell#4714]
Fish Version: `fish, version 2.7.1`
uname: `4.10.0-35-generic` - Linux Mint Sonya
No difference without third party resources

Problem:
The builtin `string` seems to have an odd behavior when called with empty variables (or no second argument). Both of these commands have exit status 1:
```
string match "*s" 
string match --invert "*s"
```
I think this is odd, as "no string" should either match or not match with some given expression.
However, it does both.

**Comment by faho** [comment]
This actually looks okay to me at first glance - both return true when there is an argument that fullfills the condition. And `grep` behaves the same way - `true | grep banana` returns 1 with and without "-v".

I suspect you have some larger piece of code that you want to use this for. Can you explain that a bit?

**Comment by tommyknows** [comment]
Okay, that makes sense to me. Thanks for the clarification.
I'm trying to write a small function that stays inside the while loop until the regex matches. It should match the "s" at the end.
My problem is that the command sometimes returns nothing, -> the while loop ends.
But it should stay inside that loop until it has a string that ends with "s".
```
set var (somecommand)
while string match --invert "*s" $var >/dev/null
  sleep 1
  set  var (somecommand)
end
```

Thanks

**Comment by faho** [comment]
>I'm trying to write a small function that stays inside the while loop until the regex matches. It should match the "s" at the end.

Okay. Why? What are you trying to do?

As it stands now, you could add an explicit check - `while test -z "$var"; or string match`, but I'd have to know why you are doing this to know if that's the right thing to do.

(Also, `string match` has a "-q" option you can use instead of redirecting the output)

**Comment by tommyknows** [comment]
Yes, the explicit check works fine. 
And thanks for the tip with `-q` 

I just thought it wasn't needed, but with your explanation it makes sense.
Thanks
