### ISSUE TITLE
find . -name "*" -exec cp {} * \;  result:  cp: : No such file or directory

### ISSUE THREAD

**Issue by idewindy** [fish-shell/fish-shell#4716]
fish version
2.7.1
env
Mac OS 10.13

The current path to determine this file，but prompt 'No such file or directory'

**Comment by faho** [comment]
```fish
find . -name "*" -exec cp {} * \;
```

There's two issues here. One is that last `*`, which will expand to all files in the current directory, which you _probably_ don't want.

The other is the `{}`, which in fish 2.7.1 will expand to nothing - it's read as a brace expansion (the `{foo,bar}baz` thing) with no elements. That's changed for 3.0 - see #1109, #4632. Now a literal `{}` won't be expanded at all, it'll just be passed along.

**Comment by idewindy** [comment]
@faho thanks, already solved
