### ISSUE TITLE
Highlighting/color broken in command substitution

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4718]
I feel like this is probably bugged somewhere else but I haven't been able to find it. Token highlighting within a command substitution block (aka fake subshell aka parentheses) is broken/non-functioning, valid commands and nonsense strings are all highlighted identically:

![image](https://user-images.githubusercontent.com/606923/36040323-b90b3dd6-0d8a-11e8-9953-bc0eeca0a288.png)

I have no experience with the parser, but I'm wondering if it's possible to stick it in a stack such that we can reset the state each time a command substitution block is encountered.

**Comment by Darkshadow2** [comment]
Isn't it supposed to be that way, since it's not valid syntax until you close the parentheses?

I always thought so, anyway.

**Comment by mqudsi** [comment]
I think I used to think that. But in that case, only the opening parentheses should be in red.

**Comment by Darkshadow2** [comment]
But everything from the opening parenthesis to the end of the line is invalid until you close it. I can see why it's all in red.

It doesn't really matter to me one way or another how it's highlighted in this case, but wouldn't what you're asking for be somewhat difficult to parse? The parser would have a syntax error, but then have to try to keep going.

**Comment by mqudsi** [comment]
No, my suggestion is to stick the highlighting parser in a stack, and start a new one when a parentheses is opened.

The benefit should be obvious, it's the same benefit as top-level syntax highlighting. You'll be able to see at a glance what the correct paths are and which commands were found vs which weren't.

**Comment by zanchey** [comment]
This is longstanding, going back to at least 2.2.0.

**Comment by faho** [comment]
I've looked into the highlighter a while back, and I found what causes this. The parser just simply gives a syntax error because of the incomplete statement (https://github.com/fish-shell/fish-shell/blob/master/src/highlight.cpp#L1121). This needs to do something like complete does (https://github.com/fish-shell/fish-shell/blob/master/src/reader.cpp#L2535-L2539) - that can operate on an incomplete command substitution.

**Comment by krobelus** [comment]
fixed in 3.1.2, possibly earlier
