### ISSUE TITLE
`fish` process is eating 100% CPU again

### ISSUE THREAD

**Issue by minchenkov** [fish-shell/fish-shell#472]
Hello,

I have similar problem like described in issue #422.
fish was built from source code, commit  87baa4d3d224939698926dc119b46e6d87a8b9e8 (so fix for #422 included).

How to reproduce: login to server via ssh, run something like "tail -f /var/log/messages", close terminal window. If login again, there will be `fish` process that eating 100% CPU.

OS Debian GNU/Linux wheezy/sid

**Comment by faho** [comment]
There hasn't been any activity here for 2 years, so I'm closing this.
