### ISSUE TITLE
How do I create my own `complete`?

### ISSUE THREAD

**Issue by JoshCheek** [fish-shell/fish-shell#4721]
```fish
# computer 1
$ fish --version
fish, version 2.4.0

$ uname -a
Darwin Joshs-MacBook-Air-2.local 15.6.0 Darwin Kernel Version 15.6.0: Mon Aug 29 20:21:34 PDT 2016; root:xnu-3248.60.11~1/RELEASE_X86_64 x86_64

$ echo $TERM
xterm-256color


# computer 2
$ fish --version
fish, version 2.6.0

$ uname -a
Darwin C02V22B7HTD6 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64

$ echo $TERM
xterm-256color
```

Hi. I've been avoiding using complete for a couple years, because it has a tendency to lock the entire shell when I press `tab`. It would clearly be nice if I could provide an example, but I don't remember what situations I was in previously, just that I've grown more and more scared of it. Instead, I rely on autosuggest, and history.

Independently, I have commands I want to run, where there are only a very small number of possibilities, but I can never quite remember what they are. I realized it would be really nice to be able to add them to the completion, but I'm scared to use completion since it might lock the shell.

As I thought about what I wanted from it, I realize that there isn't a way to know the completions in advance, because they're custom to my project. Doing some research, I realized that I can add a program to check if a completion applies, but I don't want to put the program in the check, because it would be too expensive. In retrospect, this is probably what's going on with the builtin completions.

An example of the kind of program would be something like `gulp --tasks-simple`, which seems to take 5 seconds or more, the first time I run it (cold cache, I guess). Another example is `rake -T`, but for a Ruby on Rails project, it must load all the dependencies before it can tell me what tasks are available. I've worked on projects where loading all that code could take 30 seconds, just to print the task names. I got in the habit of `rake -T > tasknames` just so I could grep that file instead of running it dynamically.

So, I was thinking about what I'd like it to do, and figured that instead of providing a program to determine the answer, I should provide the completion with a BNF grammar or something, and provide a program to get some set of values that the grammar might need, eg the names of the tasks that I can run, or of the git branches that I have available. And it should run that program once and remember the results until I tell it to refresh, at which point, I am intentionally incurring that cost, because it has some value to me. This seems like it would provide nearly as much power as the `--condition` flag, but with a much lower runtime cost.

So, figured I'd try to write that tool. I eventually figured out that I could, for example, do something like this:

```fish
function joshcomplete
  commandline -a (ruby -r pp -e '
    puts
    pp [:full, :cursor].zip(ARGV).to_h
  ' -- (commandline -b) (commandline -C))
end

bind \t joshcomplete
```

The ruby program there, could then be some executable I build, or a function that calls out to a server that I could supply.

What I haven't figured out is how to invoke the pager that the builtin `complete` uses. Initially I wanted to just hand different results to the pager, it keeps the scope of the tool much smaller, but as I thought about it, I realized I'd be willing to take on those responsibilities, as they would afford me a lot of power to introduce small improvements and tailor it to my preference. But then, how do I do that without taking control of the entire line? Fish's command-line interface is better than any other tool I've used, I frequently compose 20 and 30 line scripts straight off the terminal, I don't want to try to reproduce that, mine will inevitably be worse.

So, I'm a bit unsure where to draw the boundaries, and unsure of how to invoke the pager (the source makes it look like it straight prints the results it finds, and something above it passes the output through the pager. Ideally I wouldn't have to recompile to introduce my `complete` function, is that possible?

**Comment by faho** [comment]
> I'm scared to use completion since it might lock the shell.

See #23. Also, ctrl-c will abort completions.

> I got in the habit of rake -T > tasknames just so I could grep that file instead of running it dynamically.

What I'd do here is to put that bit into the completion script, and then to use that as a cache. See e.g. https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_print_packages.fish#L47-L58.

>What I haven't figured out is how to invoke the pager that the builtin complete uses.

That's #4036 (which was #2805). Currently, it's not possible to invoke fish's pager from the outside, and the code needs to be decoupled somewhat to make that possible. But it absolutely is something I'd love to see.

**Comment by faho** [comment]
I'm assuming this has been answered. If you have any follow-ups, feel free to ask!
