### ISSUE TITLE
Add setting the vi-mode cursor shape variables to the documentation

### ISSUE THREAD

**Issue by kmoschcau** [fish-shell/fish-shell#4723]
Hi, I've been digging through the documentation and even some of the function definitions relating to the vi-mode, wondering why the changing of the cursor shape did not seem to work at all. (Vi-mode itself works just fine)
The documentation makes it look like it should work right out of the box.
After a while I figured out, that the cursor shape variables are not set at all.
So after adding the following to my conf.fish, it works:
```fish
# Set the cursor shapes for the different vi modes.
set fish_cursor_default     block      blink
set fish_cursor_insert      line       blink
set fish_cursor_replace_one underscore blink
set fish_cursor_visual      block
```

It would be nice, if the documentation would mention, that you have to set those yourself in order for it to work.
(Now I only have to figure out, why it only works in tmux and not in plain terminal...)

**Comment by kmoschcau** [comment]
I've figured out, why it did not work in my plain terminal: The terminfo entry for the xterm-256color-italic terminal I use, did not have xterm's custom "Ss" and "Se" capabilities.

**Comment by ridiculousfish** [comment]
Glad you figured it out @kmoschcau , do you think there's something that fish could do here?

**Comment by kmoschcau** [comment]
I'm not sure. The TERM I use was something I found after a lot of searching on how to get truecolor and italics working in (neo)vim and tmux in a terminal. I don't think it's that widely used. Most people will have either `xterm` or `xterm-256color`. In my case it was just two capabilities, that were missing in the terminfo entry.

If anyone else encounters this problem, this is what I used in the end:
```shell
# A xterm-256color based TERMINFO that adds the escape sequences for italic.
cat <<EOF | tic -x -
xterm-256color-italic|xterm with 256 colors and italic,
	sitm=\E[3m, ritm=\E[23m, Ss=\E[%p1%d\sq, Se=\E[2\sq,
	use=xterm-256color,
EOF
```

**Comment by mqudsi** [comment]
`ncurses` now ships with a `tmux`-specific `tmux-256color` which I highly recommend. Make sure to use the latest versions of `tmux`, `ncurses`, and `neovim` and I think all those features will just work (under fish).

**Comment by kmoschcau** [comment]
I now encountered a slighty different problem: The cursor shape changing works outside of tmux 100% of the time. While in tmux, it works for less than a second after a mode change, then just reverts back to a blinking block. Do you guys want me to open a separate issue for this or is this an easy fix on my side?

**Comment by kmoschcau** [comment]
And again, I made the same mistake. It seems to work now. All I had to do was add the `Ss` and `Se` entries to my tmux terminfo entry as well. @mqudsi do those terminfo entries support xterm compatible italics and cursor shapes as well?

**Comment by kmoschcau** [comment]
Now I found another situation where it does not work: Whenever you switch the focus from one pane or window to another. In other words, fish would need to check it's vi-mode when gaining focus and send the according cursor shape control sequence. Do you want me to open a separate issue for this?

**Comment by zanchey** [comment]
That's probably a separate issue.

**Comment by kmoschcau** [comment]
This has been added to the documentation. Therefore I am closing this issue.
