### ISSUE TITLE
Result of bind execution

### ISSUE THREAD

**Issue by baronTommy** [fish-shell/fish-shell#4725]
# I want to finish after echo

## Current
`Ctr + e`
```
>hello

```

## Request
`Ctr + e`
```
>hello
>  # I want to end properly
```

- https://github.com/baronTommy/dotfiles/blob/master/fish/functions/hi.fish
- https://github.com/baronTommy/dotfiles/blob/master/fish/functions/fish_user_key_bindings.fish

## With it
```
>echo $status
>0  #0? hi return 1 ?
```

---

```
>echo $version
2.7.1
```

**Comment by zanchey** [comment]
To confirm, the problem is that the return code from a function executed by a key binding is not available to the current execution environment - is that right?

Is there a particular reason you need this information?

**Comment by baronTommy** [comment]
problem solving

```
commandline -f repaint
```

**Comment by baronTommy** [comment]
@zanchey 
`echo $status`
> Is there a particular reason you need this information?
I only wanted to know if possible
Is it impossible to acquire?

**Comment by faho** [comment]
> Is it impossible to acquire?

@baronTommy: Currently, yes. And I don't think changing $status is a good thing to do here.

Imagine you have a binding that happens to execute some script. If you happen to press that while typing `echo $status`, that will override it and stop you from getting the last command's $status.

If you have something you want to do here, we can think about some other way of enabling it.

**Comment by baronTommy** [comment]
@faho 
Thank you very much.
I just worried about why I can not get it
