### ISSUE TITLE
Alias Bug

### ISSUE THREAD

**Issue by Salil999** [fish-shell/fish-shell#4732]
Please tell us which fish version you are using by executing the following:

  fish --version: `fish, version 2.7.1`
  echo $version: `2.7.1`

Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

uname -a output:
`Darwin Shank 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64`

echo $TERM output (using iTerm2):
`xterm-256color`

Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:
sh -c 'env HOME=$(mktemp -d) fish'

Can't really simulate behavior with a clean copy... If anything, I launched it without third-party customizations and when I type in `alias status 'git status'`, it doesn't run it.

Tell us how to reproduce the problem. Including an asciinema.org recording is useful for problems that involve the visual display of fish output such as its prompt.

I added an alias of:
`alias status 'git status'`
But this, apparently, runs `git status` every time I launch a new instance of iTerm2 (tabs or windows). I have other commands of git aliased, but this is the only one that runs for some reason.

<img width="553" alt="screen shot 2018-02-17 at 3 58 40 pm" src="https://user-images.githubusercontent.com/8891729/36346014-810fb048-13fb-11e8-844c-69cf9b33167d.png">

**Comment by krader1961** [comment]
That's because `status` is a builtin that is used in many scripts, but especially your *~/.config/fish/config.fish* startup script. In general you shouldn't define a function with the same name as a builtin unless your function extends the functionality of the builtin.

**Comment by Salil999** [comment]
Ah, my apologies. I was not aware of that. I will alias it to something else - thanks!
