### ISSUE TITLE
duplicate print with match

### ISSUE THREAD

**Issue by Estirp** [fish-shell/fish-shell#4733]
with fish 2.7.1
I have a minor  bug :
> string match --regex -- '^(-f|--force)$' '--force'
--force
--force

"--force" should be printed only once.

Thank you for your work.

**Comment by Darkshadow2** [comment]
The first result is everything that matched the regex, and any following lines are groups that matched.

For instance `string match --regex -- 'Hello (.*)' 'Hi Hello Goodbye'` returns:
`Hello Goodbye`
`Goodbye`

**Comment by faho** [comment]
I'm assuming this has been answered.
