### ISSUE TITLE
Disable specific command completions?  Git, mostly

### ISSUE THREAD

**Issue by ifreecarve** [fish-shell/fish-shell#4744]
```
$ fish --version
fish, version 2.6.0
$ echo $version
2.6.0
$ uname -a
Darwin ALT00238 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 15 17:36:27 PDT 2017; root:xnu-3789.70.16~2/RELEASE_X86_64 x86_64
$ echo $TERM
xterm-256color
$ # note that this is just Apple terminal Version 2.7.3 (388.1.1)
```

This may be a duplicate of #1363 but I want to call it out specifically.  I've enjoyed the fish shell quite a bit in the past few months, but I continue to get hung up on the completion of git commands that reference the filesystem.  It's nice that fish tries to be helpful in guessing which file I might be trying to do a particular git operation with, but (1) there's a noticeable delay every time and (2) in some cases it picks the wrong file.

I don't like being faster at typing out file paths than my shell is.  Either fish can run git in milliseconds and get me exactly what I want, or it should get out of my way and just be a "dumb" bash-style path completer.  

More broadly, what I'm talking about here is a global timeout (user-configurable?) on how long fish will spend waiting for one of the completion commands to return a result.  I'd like to keep that threshold very short, if possible, so that I don't keep typing over the autocompleted result that arrives late.

**Comment by faho** [comment]
>This may be a duplicate of #1363 but I want to call it out specifically.

The issue you want to look at is actually #23.

>I continue to get hung up on the completion of git commands that reference the filesystem.

The good news is that we've done a bunch of work for the upcoming 3.0 release to speed just that bit up. See #4673.

Also, 2.7.0 improves the situation if you have a bunch of git aliases (say more than my 3).

>in some cases it picks the wrong file.

Obviously, that's a bug.

**Comment by ifreecarve** [comment]
Perfect, thank you

**Comment by ianfixes** [comment]
> > in some cases it picks the wrong file.
> 
> Obviously, that's a bug.

Just for posterity: the "bug" was just muscle memory caused by not knowing the difference between hitting tab and (1) instantly getting no results vs (2) getting results after a few seconds.  By assuming (1), I would type extra characters and that would mess up the overall command that was typed.
