### ISSUE TITLE
Newline above prompt that includes fish_mode_prompt

### ISSUE THREAD

**Issue by pruett** [fish-shell/fish-shell#4746]
```bash
λ(~) echo $version
2.7.1
```

```bash
λ(~) uname -a
Darwin 17.4.0 Darwin Kernel Version
```

```bash
λ(~) echo $TERM
xterm-256color
```
I'm looking to **add a newline above my full prompt**. Everything I tried does not seem to work.
I ran into https://github.com/fish-shell/fish-shell/blob/master/doc_src/fish_mode_prompt.txt#L37 file that states "multiple lines is not supported in `fish_mode_prompt`"

Currently:
```bash
λ(~) la | grep fish
lrwxr-xr-x     1 pruett  staff    25B Feb 21 15:29 .hushlogin -> .dotfiles/fish/.hushlogin
λ(~) 
```

Expected:
```bash
λ(~) la | grep fish
lrwxr-xr-x     1 pruett  staff    25B Feb 21 15:29 .hushlogin -> .dotfiles/fish/.hushlogin
# [newline] <----
λ(~) 
```

Is there no way around this as long I'm using a `fish_mode_prompt`?

**Comment by faho** [comment]
>Is there no way around this as long I'm using a fish_mode_prompt?

The way fish's prompt handling works is that it prints the output of `fish_mode_prompt` (with newlines removed), then the output of `fish_prompt`, and then (on the right side) `fish_right_prompt`.

`fish_mode_prompt` is simply a function that is supposed to print a character or so to tell you what vi-mode you're currently in.

I'm not seeing that in your output above, so I'm not actually sure you're using it.

However, if you want to include a mode-display _and_ have a newline _before_ that (which I don't understand the reason for), then you can simply disable `fish_mode_prompt` by replacing it with a function that prints nothing, and include the mode-handling in your actual `fish_prompt`.

E.g. something like

```fish
function fish_mode_prompt; end

function fish_prompt
    echo # To print an empty line
    set -l mode (fish_default_mode_prompt) # or some other way of printing the mode
    set -l ppwd (prompt_pwd)
    printf '%s' $mode 'λ(' $ppwd ')'
end
```

**Comment by pruett** [comment]
@faho here's my `fish_mode_prompt`:

```fish
function fish_mode_prompt --description 'Displays the current mode'
  # Do nothing if not in vi mode
  if test "$fish_key_bindings" = "fish_vi_key_bindings"
      switch $fish_bind_mode
          case default
              set_color --bold 8116C0
              echo λ
          case insert
              set_color --bold brblack
              echo λ
          case replace_one
              set_color --bold 8116C0
              echo λ
          case visual
              set_color --bold brblack
              echo λ
      end
      set_color normal
      printf ""
  end
end
```

**Comment by pruett** [comment]
@faho great, that worked! thanks!

**Comment by endersstocker** [comment]
@faho This no longer works. If the mode-handling is moved to `fish_prompt` it does not actually update. I only noticed the unexpected behavior this month.

**Comment by faho** [comment]
@endersstocker The behavior has been refined in fish 3.1. To update the mode display, we have to re-execute the prompt. And since some prompts take a bit to execute that's a bit of an awkward experience if you need to wait for it to finish after pressing e.g. escape or "i".

So we made it so that we only reexecute `fish_mode_prompt`, unless that produces no output (or doesn't exist). So you need to define an empty fish_mode_prompt function - `function fish_mode_prompt; end`.
