### ISSUE TITLE
"Search within autosuggestions" feature broken

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#4749]
```
$ fish --version
fish, version 2.7.1-815-g0f62161b
```

```
$ uname -a
Darwin mac.local 15.6.0 Darwin Kernel Version 15.6.0: Tue Jan  9 20:12:05 PST 2018; root:xnu-3248.73.5~1/RELEASE_X86_64 x86_64 i386 MacBookPro11,3 Darwin
```

---

**Steps**
```
$ sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
zx8@mac /U/zx8> cd (mktemp -d)
zx8@mac /p/v/f/_/w/T/tmp.8MyScugyEq> mkdir (seq 1 1000)
zx8@mac /p/v/f/_/w/T/tmp.8MyScugyEq> cd 3<TAB><TAB>

# Type the number '2' to further filter results within autosuggestions
```
**Expected Behaviour**
```
# List of autosuggestions containing the number '2'
```

**Actual Behaviour**
```
$ cd 3/2
```

**Comment by faho** [comment]
First, some terminology:

- "Autosuggestions" is the greyed-out text that appears _in_ the commandline, that you accept with right-arrow or ctrl-f or similar

- "Completions" are the things you select from a menu with TAB

So this is related to the _completions_ pager.

In #2249 (commit 5c2e6734c1e547da172b3fe0615e070ba84451e3), @ridiculousfish changed it so you need to explicitly trigger searching, via the new "pager-toggle-search" bind function, bound to ctrl-s by default (and I believe "/" in vi-normal mode).

So you need to press Ctrl-S now.

**Comment by zx8** [comment]
Got it, thanks. 

Very disapponted that something I've been using for over a year now was changed without a way of reverting back to the old behaviour (e.g. `fish_legacy_pager`). 

I'm sure I'll adapt and I’ve no problem with manual toggling being the default, but not being able to reinstate the old behaviour via a flag seems slightly short-sighted!

**Comment by ridiculousfish** [comment]
@zx8 thanks for the feedback. fish of course has the ["configurability is the root of all evil"](https://fishshell.com/docs/current/design.html#design-configurability) design principle which is why this sort of thing is not controlled by flags. You can follow the discussion that lead to this change in #2249 . If you have suggestions for how the UI can be improved we're still very open to it, a lot of this stuff is "try it and see how it feels."
