### ISSUE TITLE
libc++abi.dylib: terminate called throwing an exception

### ISSUE THREAD

**Issue by pazooki** [fish-shell/fish-shell#475]
I installed fish with no problem, I followed the instruction but since I made ~/.config/fish/functions/ directory and /fish_prompt.fish file and pasted : 
  function fish_prompt
    set_color $fish_color_cwd
    echo -n (prompt_pwd)
    set_color normal
    echo -n ' > '
  end
in that file I can't open a new shell anymore, as soon as I open any shell with Terminal or iTerm2 I get this error message and it closes the shell:
"libc++abi.dylib: terminate called throwing an exception"
I removed that file and directory but it didn't help. Please let me know if there is a solution to this problem, I can go back and set bash as my default shell that's not a problem but I want to be able to use fish.

Thansk.

**Comment by zanchey** [comment]
There's been no movement on this for a while. @pazooki, did you ever have any luck with fish?

**Comment by pazooki** [comment]
@zanchey oh man this is really old! I think the issue is resolved. I recently installed fish on osx with homebrew with no problem. it works perfectly fine.

**Comment by zanchey** [comment]
Good to hear!
