### ISSUE TITLE
set: Unknown option '-a' in __terlar_git_prompt

### ISSUE THREAD

**Issue by pruett** [fish-shell/fish-shell#4752]
```fish
λ(~) fish --version
fish, version 2.7.1

λ(~) uname -a
Darwin 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64

λ(~) echo $TERM
xterm-256color
```

I've attempted to copy `fish-shell/share/functions/__terlar_git_prompt.fish` and write it to my `fish_right_prompt.fish`. I'm receiving the following error:

**`set: Unknown option '-a'`**

Is this not supported by the right prompt?

**Comment by krader1961** [comment]
`set -a` is the same as `set --append` and is a new feature in the master branch (the next major release). Just replace `set -a var val` with `set var $var val`.

**Comment by faho** [comment]
@krader1961 is right - this is a new feature that isn't available in a release yet.

Note that, in general, when you copy functions from a newer fish version to an older one, it's not guaranteed to work.

We add features to fish all the time, and we tend to use them in our own functions. So when that happens in a function in git, you need to either build fish from git completely (not just cherry-picking improvements), or wait for a release.

**Comment by pruett** [comment]
thanks @krader1961 @faho i assumed master pointed at latest release
