### ISSUE TITLE
Debian release key expired in OpenSuse repo

### ISSUE THREAD

**Issue by todeveni** [fish-shell/fish-shell#4753]
Key expired in 2018-02-24 rendering repo unusable.

`The following signatures were invalid: EXPKEYSIG 2CE2AC08D880C8E4 shells:fish OBS Project <shells:fish@build.opensuse.org>`

```
pub   rsa2048 2013-10-08 [SC] [expired: 2018-02-24]
      24A6 3B31 CAB4 1B33 EC48  801E 2CE2 AC08 D880 C8E4
uid           [ expired] shells:fish OBS Project <shells:fish@build.opensuse.org>
```

**Comment by zanchey** [comment]
It's been extended (at the beginning of the month), but you'll need to update your copy:

```
wget https://download.opensuse.org/repositories/shells:fish:release:2/Debian_8.0/Release.key -O- | sudo apt-key add -
```

**Comment by zanchey** [comment]
See also #2618.

**Comment by todeveni** [comment]
Will the key update on key servers automagically?
We use `apt-key` and keyservers on provisioning.

`apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 2CE2AC08D880C8E4`

**Comment by zanchey** [comment]
I've sent it to a few keyservers, including hkp://keyserver.ubuntu.com:80, so it should get picked up soon.

**Comment by todeveni** [comment]
Updated and working. Thanks!
