### ISSUE TITLE
Docker doesn't work in fish

### ISSUE THREAD

**Issue by holms** [fish-shell/fish-shell#4761]
```
roman@debian:~$ fish --version
fish, version 2.7.1

roman@debian:~$ uname -a
Linux debian 4.9.0-5-amd64 #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04) x86_64 GNU/Linux
```
* Term is screen when in fish.
* No third parties.

Once I type fish in the bash, I enter to screen somehow..? Then I need to type fish again, to enter a fish prompt. I think this is might be an issue because in screen docker socket is not found, also as I can't copy test to X clipboard, while I'm in bash it works.

Work in bash: 

```
roman@debian:~$ docker ps
CONTAINER ID        IMAGE                        COMMAND                  CREATED             STATUS              PORTS               NAMES
```

Once I enter `fish` and it doesn't anymore:

```
roman@debian:~$ docker ps
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.35/containers/json: dial unix /var/run/docker.sock: connect: permission denied
```

Can someone please explain, why I'm ending up in screen in the first place? Once I'll get there everything dies, all my ssh agents, gpg agents and etc. I've read something about having bottom line is the only way to use screen, I'd gladly refuse to use bottom line, if there will be no screen needed

**Comment by faho** [comment]
>Once I type fish in the bash, I enter to screen somehow..?

That's the part you need to figure out. Obviously fish doesn't automatically start screen by default. There are a bunch of places where this _could_ happen, but the most likely is some configuration file for fish.

Check your ~/.config/fish/config.fish. If you can't find anything in there, try `env HOME=$(mktemp -d) fish` in bash. If that still launches screen, check `type fish` in bash.

**Comment by holms** [comment]
Here you go:


```
roman@debian:/mnt$ env HOME=$(mktemp -d) fish
Welcome to fish, the friendly interactive shell

roman@debian:/mnt$ type fish
fish is hashed (/usr/bin/fish)

roman@debian:/mnt$ cat ~/.config/fish/config.fish
if status --is-interactive
    keychain --quiet --agents ssh
end
set GPG_TTY (tty)
```

There's also omf installed in `~/.config/fish/conf.d`.

All of these shouldn't  bring up screen right?

**Comment by faho** [comment]
@holms: Try without all of that. Either move your ~/.config/fish out of the way, or try `env HOME=$(mktemp -d) fish` like I suggested.

Also:

>There's also omf installed in ~/.config/fish/conf.d.

That's a third party thing! When the issue template asked you about that, you should have said so.

**Comment by holms** [comment]
@faho Sorry, I've missed that one.  Removing omf solved the problem,  now it enters directly to fish prompt, and docker works too. Thank you.
