### ISSUE TITLE
Slow git auto-complete... how to turn off? 

### ISSUE THREAD

**Issue by nipunarora** [fish-shell/fish-shell#4762]
fish version = 2.7.1
Darwin Kernel Version 16.7.0: Thu Jan 11 22:59:40 PST 2018;

I have a huge git repo, and the auto-complete in git for git add is super slow, is there any way to simply turn it off? I think I can work faster with regular auto-complete instead of git based auto completion.

**Comment by ridiculousfish** [comment]
Do you want to disable all custom git completions or just those for `git add`?

To disable all git completions you can put an empty file at `~/.config/fish/completions/git.fish`, that will be loaded in preference to the normal git completions.

If it's just `git add`, probably the easiest thing to do is to copy `/usr/local/share/fish/completions/git.fish` to `~/.config/fish/completions/git.fish` and then edit it to disable the `add` command.

**Comment by faho** [comment]
Also, we've improved performance quite a bit for 3.0. See #4673.

**Comment by mqudsi** [comment]
I can vouch for what @faho said, even on WSL with its horrible IO performance.

**Comment by nipunarora** [comment]
ahh... I should get the latest version, is it only available through git or do we have it on brew?

**Comment by mqudsi** [comment]
You can use `brew install fish --head`

**Comment by faho** [comment]
The question has been answered.

**Comment by Flimm** [comment]
For the record, I still experience this issue in Fish 3.6.0 on Ubuntu 23.04.

**Comment by marcus302** [comment]
> Do you want to disable all custom git completions or just those for `git add`?
> 
> To disable all git completions you can put an empty file at `~/.config/fish/completions/git.fish`, that will be loaded in preference to the normal git completions.
> 
> If it's just `git add`, probably the easiest thing to do is to copy `/usr/local/share/fish/completions/git.fish` to `~/.config/fish/completions/git.fish` and then edit it to disable the `add` command.

This and restarting my shell worked for me. Too bad it's too slow to use effectively.
