### ISSUE TITLE
[math/tinyexpr] Division by 0 results in LONG_MIN

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#4768]
```
$ fish --version
fish, version 2.7.1-856-gfd6a1a43

$ math 1 / 0
-9223372036854775808
```

Ping @faho

**Comment by zx8** [comment]
Also, an unrelated nit not worth raising a separate issue for:

```
$ math
math: Error: Too few arguments
''
 ^
```
```
$ math ""
math: Error: Too few arguments
''
 ^
```

The former should probably not show the extra `^` output as I didn't input any arguments.

**Comment by faho** [comment]
Huh, okay.

I'm assuming you're expecting an error here? We currently only return _parse_ errors, and that expression parses okay. We should probably add some computation errors - division/modulo by zero, over/underflow (see #4479). Note that division currently literally does `a / b` in C code, which for doubles returns INFINITY.

So `math -s 15 1 / 0` will print "inf", `math -s 15 1 '%' 0` will print "-nan". The LONG_MIN comes from us coercing it into a `%ld` format specifier.

We could also make a NaN/Infinity return value an error.

>The former should probably not show the extra ^ output as I didn't input any arguments.

Should this be an error or operation-as-expected with no output? With muparser, it printed `math: Invalid expression: Expression is empty.` and returned 1. With `bc`, it printed "math: Expected at least 1 args, got only 0".

**Comment by faho** [comment]
>We could also make a NaN/Infinity return value an error.

This might sound weird. The reason I'm proposing it is that

- I don't think there are sensible computations where this occurs. (I might be wrong on this)

- `math` doesn't accept these as _arguments_. `math inf - inf` is a bogus expression.

- It's really easy to add - `std::isfinite(v)`

**Comment by zx8** [comment]
> I'm assuming you're expecting an error here?

Yeah, a "divide by zero" error seems to the most common:
```
$ python3 -c '1/0'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ZeroDivisionError: division by zero

$ ruby -e '1/0'
Traceback (most recent call last):
	1: from -e:1:in `<main>'
-e:1:in `/': divided by 0 (ZeroDivisionError)

$ perl -e '1/0'
Illegal division by zero at -e line 1.

$ node -pe '1/0'
Infinity

› echo 1/0 | bc
Runtime error (func=(main), adr=3): Divide by zero
```

> Should this be an error or operation-as-expected with no output?
I think the current output is more or less fine, but with slight tweaking to remove the additional caret in the case when no arguments are supplied (`math` vs `math ""`), i.e.
``
$ math
math: Error: Too few arguments

$ math ""
math: Error: Too few arguments
''
 ^

**Comment by faho** [comment]
>I think the current output is more or less fine, but with slight tweaking to remove the additional caret in the case when no arguments are supplied (math vs math ""), i.e.

I just used one of our generic errors - `math: Expected at least 1 args, got only 0`.

**Comment by faho** [comment]
Okay, I've now pushed something that returns an error if the result is too large for long, infinite or nan.

That should also catch division by 0 (because with IEEE754 floats that returns infinite). It's admittedly not brilliant (it can't tell you that it's a division by 0 or where it occured), but it'll do for now.
