### ISSUE TITLE
New preexec-like event, emitted for each single job, with the parsed argument list available

### ISSUE THREAD

**Issue by xiaq** [fish-shell/fish-shell#477]
This proposal stems from an attempt to implement [fasd](https://github.com/clvv/fasd) in fish.

In zsh, `preexec` is fired before the command being executed. What it does essentially is calling the hook functions with `"$history[1]"`. It can be partially emulated with the `fish_prompt` event (this is the same trick fasd uses for `bash` and `tcsh` where there is no `preexec`), but the latter happens _after_ the command is executed, so the shell state is likely to have changed, invalidating the last command (eg. when the user `cd`ed, file names from last history is no longer valid). Also, peeking into `$history[1]` in a `fish_prompt` event handler doesn't really work - instead of the last history, you get the last but one - but that's another story.

Instead of replicating the behavior of `preexec` hook with a `preexec` event, I propose for something better.
- The event is called `job-parsed`.
  - **Update**: Use `job_parsed` instead to be consistent with `fish_prompt`.
- The event is emitted for each single job, so that
  
  ```
  echo a; echo b
  ```
  
  causes _two_ `job-parsed` events to be emitted. This is much more useful for tools like fasd.
- The **fully parsed** (with all expansions including command substitutions done) job argument list should be made available. However, (unlike hook functions) event handlers in fish can't get any arguments yet. To work around this, the list is placed in the array `$job_words` before `job-parsed` is fired. It's not called `$job_argv` since the command name is also included. The motivation for a parsed list stems from the difficulty to redo the expansions in shell without side effects.
  - **Update**: As pointed out by @JanKanis, event handlers can get arguments. So instead of `$job_words`, the words are just passed as arguments to the handlers of `job_parsed`.

**Comment by zanchey** [comment]
Retargeting - fully parsed command lines is probably out of scope for 2.2.0.

**Comment by krader1961** [comment]
I'm closing this since it is very old and there have been many changes since it was opened that are relevant. Too, it is not clear whether this is still an unresolved issue. In particular, the enhancement by @kballard seems to address some, if not all, of this issue.
