### ISSUE TITLE
Bash if/else statement not parsed correctly

### ISSUE THREAD

**Issue by epheterson** [fish-shell/fish-shell#4771]
fish, version 2.7.1
Darwin ELPro 17.5.0 Darwin Kernel Version 17.5.0: Thu Feb 22 20:37:12 PST 2018; root:xnu-4570.50.293~11/DEVELOPMENT_X86_64 x86_64
xterm-256color
I've not modified fish at all, defaults across the board.

I thought I was doing the simplest thing, and would have no problem, but fish must hate me.

This works in bash, but not in fish:
`if true; then echo YES; else echo NO; fi;`

I can't find a combo that works in both. I wish that fish could process this the same as bash, since it seems so utterly basic.

**Comment by krader1961** [comment]
Fish is not a POSIX compatible shell. It doesn't understand bash/zsh/ksh syntax. Something else you'll notice it doesn't support (although it might in the future) is `$(...)` syntax to perform command substitution (fish currently uses bare parens for that: `(a-command)`). See the [tutorial]http://fishshell.com/docs/current/tutorial.html). So the fish version of your script is

```fish
if true
    echo YES
else
    echo NO
end
```

You can replace the newlines with semicolons.

**Comment by epheterson** [comment]
So it sounds like if I wanted to create bash scripts to function for users with either shell, I simply cannot? Is there an issue tracking the option to enable POSIX compatibility?

**Comment by krader1961** [comment]
Since fish is not, and never will be, compatible with bash you can't write a script that works in both shells. Your question is like asking "can I write a script that works in csh and bash?" The answer is "no"  since those two shells implement different syntax. Just like fish implements a different scripting language than bash. Is there a change to the fish documentation that would have made this clearer to you?

**Comment by epheterson** [comment]
It'd be nice if I could somehow tell fish to execute a particular block in another shell and return the text output as it executes it. Is that possible? If not, although I see the many advantages of fish, it is too much of a burden to maintain scripts for.

I do think the documentation could have addressed this – I actually don't see it mentioned anywhere. The term "compatibility" doesn't appear at all, and the term "bash" does, but not in way that makes it obvious the two are totally incompatible. 

Much of this is me not realizing precisely what having a different shell environment means – the documentation does clarify that there are differences, but doesn't mention that anything you've made for one environment is potentially useless in another, and list the cases.

**Comment by krader1961** [comment]
> It'd be nice if I could somehow tell fish to execute a particular block in another shell and return the text output as it executes it. Is that possible?

Yes. Put the script in a file with an appropriate hash-bang header. For example, put the following in a file named *trivial* in a directory in your `$PATH`:

```
#!/bin/bash
if true; then echo YES; else echo NO; fi;
```

Now you can use the `trivial` command in fish; e.g., `echo (trivial)`. That's how all the scripting languages in UNIX work. For example, no one expects bash to execute python. But you can put the python code in a file like the above example then use that script in bash. It's just another program.

If you don't want to create a file then do this: `bash -c 'if true; then echo YES; else echo NO; fi;'`

**Comment by epheterson** [comment]
These two options really help and clarify things, thanks! 

I think it would be very useful to include that in the documentation, as I did check there first and searched for "bash". (Though I do understand how many people who change their shell may already know that.)
