### ISSUE TITLE
man autocomplete incorrectly includes fish commands

### ISSUE THREAD

**Issue by cesarandreu** [fish-shell/fish-shell#4774]
### Information
fish version: 2.7.1.
Operating system: macOS 10.13.3.
Built-in Terminal.app. No third-party customizations.

### Issue
man autocomplete incorrectly includes fish commands despite having set a section which shouldn't include them.

### How to reproduce
Type `man 4 a` and hit tab. The autocomplete choices will include multiple fish commands.

<img width="837" alt="screen shot 2018-03-03 at 04 02 56" src="https://user-images.githubusercontent.com/656870/36934037-eca8efc6-1e97-11e8-9ebe-22242b334b6a.png">

### Expected behavior
Autocomplete choices should only include fish commands when no section has been specified or when the section value is 1.

**Comment by zanchey** [comment]
Fixed by #4775.
