### ISSUE TITLE
Output of time is unreadable

### ISSUE THREAD

**Issue by obfuscated** [fish-shell/fish-shell#4780]
Here is an example:
```
$ time echo "bla"
bla
0.00user 0.00system 0:00.00elapsed ?%CPU (0avgtext+0avgdata 1704maxresident)k
0inputs+0outputs (0major+74minor)pagefaults 0swaps

```
Running 2.6.0 on gentoo linux.

Not sure if #117 is related to this or not.

**Comment by krader1961** [comment]
The `time` command is not a fish builtin or function. Therefore the format of its output isn't controlled by fish. If someone ever implements #117 hopefully they will use a friendly presentation of the data than the GNU implementation.

**Comment by mqudsi** [comment]
For reference, you can always use `type` to identify what type of command a head is. e.g.

```fish
mqudsi@ZBook /m/c/U/M/g/r/chrometools> type time
time is /usr/bin/time
```

vs

```fish
mqudsi@ZBook /m/c/U/M/g/r/chrometools> type echo
echo is a builtin
```

@krader1961 is right, this has nothing do with fish. 

@krader1961 I actually wrote a complete time builtin as one of my first contributions, but I didn't know how to actually plug it into fish at the time (as I needed the cooperation of the parser to eval the arguments). I wonder if I still have the code somewhere.

**Comment by zx8** [comment]
@mqudsi Sorry to dig up an old thread, but did you manage to find that code anywhere? 😸

Would be incredibly useful to have this committed upstream!

**Comment by nhooyr** [comment]
fyi, you can use `time -p` to get the nicer format from bash.
