### ISSUE TITLE
Incorrect UI display of parameter

### ISSUE THREAD

**Issue by EdwinVanRooij** [fish-shell/fish-shell#4792]
**Fish version**
2.7.0

**Operating system (uname -a output)**
Linux solus 4.15.7-60.current #1 SMP PREEMPT Thu Mar 1 13:02:55 UTC 2018 x86_64 GNU/Linux

**Terminal (echo $TERM output)**
xterm-256color
Using gnome-terminal through i3-sensible-terminal.

**Goal**
I'd like to use 'cd ...' instead of 'cd ../..' to go 2 directories back, 'cd ....' instead of 'cd ../../../' and 'cd .....' instead of 'cd ../../../../'. I've noticed this is a frequent use case for me, especially returning to the root of a java directory from the package (imagine: ./src/main/java/com/io/domain/etc.)

I've successfully created a function to accomplish this task:

```
function cd
    if count $argv > /dev/null
	    set path $argv[1]
	    switch $path
		case ".."
		    cd-wrapper "../"; and ls
		case "..."
		    cd-wrapper "../../"; and ls
		case "...."
		    cd-wrapper "../../../"; and ls
		case "....."
		    cd-wrapper "../../../../"; and ls
		case "-"
	   	    cd-wrapper -
		case '*'
		    cd-wrapper $argv[1]; and ls
	    end
    else
	# No param given, execute builtin
	cd-wrapper; and ls
    end
end
```
Note: cd-wrapper is most likely irrelevant to this problem. It is an _exact_ copy of '/usr/share/fish/functions/cd.fish', but renamed to cd-wrapper. I had to do this to make 'cd -' work as a command to return to the previous directory.

**Problem**
Fish incorrectly displays parameter as invalid.

When I type 'cd ...' and I hit enter, the behavior is as expected. I return to 2 directories up.
Example:
/home/eddy/.config/fish> cd ...
/home/eddy> 

The problem is that the parameter "..." is marked in red, as being invalid. Concluded: there is something wrong with the way fish interprets this command. It thinks '...' is an invalid command' but it is actually valid for my function.

Any solution to this?

**Comment by hamon-e** [comment]
I think it's related to #4693

**Comment by zanchey** [comment]
This is because the highlighter checks that the argument to cd is a valid path (see `autosuggest_validate_from_history` under `if (parsed_command == L"cd"...)`.

**Comment by zanchey** [comment]
I'm not sure what the right thing to do here is. Highlighting valid and invalid paths is sensible for 99% of the users of `cd`, and detecting whether it is a builtin or a function would require moving the current function logic into the builtin.

**Comment by hamon-e** [comment]
Don't you think it would be a nice thing to add a builtin to control this behaviour ?
(To be able to control the UI a little the same way as completion works)

**Comment by EdwinVanRooij** [comment]
I can see the issue. I'll just use these aliases then.

```
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
```

The reason I wanted the 'cd ...' function, is because I've usually already typed 'cd' before realizing I want to go back much further, out of muscle memory. I'll get used to the shorter '...'.

This issue can be closed for me.
