### ISSUE TITLE
cmake builds don't execute expect tests

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4794]
As per the title, the cmake builds don't run the interactive `expect`-based tests (not locally and not on travis). It would be nice to take advantage of this to parallelize the tests as well, that would speed things up _considerably_. Seeing as there's no persistence of state between individual tests, I don't think it should be at all difficult.

**Comment by faho** [comment]
>It would be nice to take advantage of this to parallelize the tests as well, that would speed things up considerably.

AAAAAAAAAAAAAAAAAHHHHHHHHHH!

DON'T DO THIS!

The expect tests are heavily timing dependent, and on Travis frequently fail because of resource starvation. This would pour oil on the fire!

I'm not actually sure why these tests aren't run - is there a problem?

**Comment by mqudsi** [comment]
> AAAAAAAAAAAAAAAAAHHHHHHHHHH!
>
> DON'T DO THIS!

😂

No worries, I imagine the concurrency could be managed with a cmake variable. (not to mention there are a lot of tests that could be converted away from `expect` at some point in the future.)

> I'm not actually sure why these tests aren't run - is there a problem?

No problems that I can see. I assumed they hadn't been ported over.

**Comment by faho** [comment]
>tests that could be converted away from expect

What alternative do you have in mind? Also, the issue is that there are a bunch of tests  (like the ones that test the escape timeout) that actually _require_ timing, so whatever tool we use to run them needs some amount of CPU/IO within that time, and that's at a premium on travis, and presumably every other CI provider we can get for free.

>No problems that I can see. I assumed they hadn't been ported over. Did they ever run?

I don't think they did.

**Comment by mqudsi** [comment]
tbh, I don't like that we hardcode the actual strings in the tests and just do a naive string comparison; it's not testing only what matters (basically, stdin, stdout, stderr, and exit code) for most things. Obviously things like the completions and prompt (or anything actually relying on timing) should continue to use expect, but I think a lot of tests would benefit from real integration testing instead of simple output tests. Tests taking over the terminal directly (instead of fd-agnostic reads from stdin or writes to stdout) would obviously need to use `expect` as well (e.g. `read` tests).

I think a more sane approach would be to turn a lot of the functionality tests into individual fish scripts that invoke outside commands as needed to double-check assumptions. For example, to test the backgrounding a process there would be an integration test verifying that a) the process is still running, b) the job's pid has been stashed away correctly, by backgrounding the process then exiting `kill -0` against its pid and verifying that the signal succeeded. That way we can test more than just what fish _says_ happened, but actually assert the global changes to the system state.

Other tests like operators (`and`, `or`, `not`, `&&`, `!`, `||`, `;`) just have to assert that an input gives the required output, they don't need the overhead and complexities of `expect` nor the burden of verifying the prompt, etc. and writing tests would be a lot saner than listing all expected stdout in one file and stderr in another with no synchronization between them.

**Comment by zanchey** [comment]
The `expect` tests definitely run under the autotools-based builds.

**Comment by mqudsi** [comment]
@zanchey sorry, I was asking if they ever ran under cmake.
