### ISSUE TITLE
Backtracking during iteration of argument completions breaks on duplicate entries

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4796]
This would be closed if #4795 is implemented, but an additional bug in the current argument completion behavior is that reversing iteration direction after iterating to argument suggestion from history for the 2nd+ time acts as if the iterator were on the _first_ suggestion of that argument.

To illustrate:

```fish
touch file1
touch file2
touch file1
touch file3
touch file1
touch file4
touch file5
touch file<UP>
```

The argument suggestions from history will be: `file5`, `file4`, `file1`, `file3`, `file1`, `file2`, `file1`

If you `<UP>` repeatedly until the suggestion is `file1` for the 3rd time (i.e. the last in history), then press `<DOWN>` the iterator will be moved to an incorrect location and `file4` will be shown instead of `file2`. It seems that the iterator position isn't actually saved but rather the text of the argument is (without regards to how many times it has been suggested) and the suggestion engine assumes when it comes across `file1` for the first time that this was the previous position of the iterator before `<DOWN>` was pressed, and `file4` is displayed (incorrectly).

**Comment by faho** [comment]
Fixed along with #4795.
