### ISSUE TITLE
"<|" causes weird error (was: Is the reverse pipe operator a real thing in fish?)

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4803]
```fish
~> proc2 <| proc1
<W> fish: Error while opening input stream
fdopen: Invalid argument                 
```

which would, presumably, be equivalent to

```fish
~> proc1 | proc2
```

I'm assuming fish is trying to open an actual file called `|` which results in the error above.

**Comment by faho** [comment]
It's not and I don't think it ever was, and bash doesn't have it either.

How did you get this idea?

Do you believe this is actually useful?

**Comment by mqudsi** [comment]
My wry sense of humor is sometimes hard to detect in formal, written bug reports. 🤷‍♂️

**Comment by faho** [comment]
Sorry, I must have used up my daily allotment of humor. I should go and fill out a requisition form for additional humor units (hunits).

**Comment by faho** [comment]
I get "fish: Expected a string, but found a pipe" now, which seems acceptable.

**Comment by mqudsi** [comment]
@krobelus Is the new parser going into 3.1.2? I'm pretty sure that's where the new message comes from.

**Comment by zanchey** [comment]
That message is in 3.1.2.

**Comment by mqudsi** [comment]
Thanks, @zanchey.
