### ISSUE TITLE
`prompt_hostname` no longer returns short hostname

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#4804]
As a result of https://github.com/fish-shell/fish-shell/commit/5cf67e20a5e256beab8a05a0ba8871f8d8b15427, `prompt_hostname` has regressed to returning the full hostname rather than the shortened form (i.e. stripping everything including & after the first `.`):

```sh
# Used to return this
$ hostname -s
mac

# Now returns this
$ hostname
mac.local
```

Am aware I can fix this myself by redefining `prompt_hostname` to:
```sh
function prompt_hostname 
  set hostname_short (echo $hostname | string split '.')[1]
  echo $hostname_short
end
```

But haven't raised a PR to fix it as I'm not sure if this was an intentional change or not.

Ping @mqudsi

**Comment by mqudsi** [comment]
Incidental. Thanks for catching.
