### ISSUE TITLE
CD's Completion Skips Empty/Hidden Nested Directories

### ISSUE THREAD

**Issue by timkite** [fish-shell/fish-shell#4811]
Running fish version 2.7.1 on MacOS High Sierra (10.13.3), RHEL6 (6.9), and RHEL7 (7.4)

Behavior still exists after running `sh -c 'env HOME=$(mktemp -d) fish'`

This may be intentional, but this quirk of autocomplete behavior isn't helpful to me so wanted to see if it is intentional and if so if there's a workaround. If I have a directory structure that looks like this:

```
/dir
/dir/.hiddendir
/dir/visibledir
```

In fish, if I type `cd /di <tab>`, assuming /dir is the only match for "di", it will complete all the way to `/dir/visibledir`, ignoring that there are other (hidden) directories. Additionally, with a structure like this:

```
/dir
/dir/emptydir
/dir/emptydir/website
```

If I enter `cd /dir/empty <tab>` (assuming there are no other matches for "empty"), it will complete all the way to `/dir/emptydir/website/`, which is less than convenient if I really just wanted to get to "emptydir".

This *only* applies to cd. Using path completion with other functions/programs produces the expected behavior (where I'd have to keep pressing tab to get to the subsequently nested directories) that I see for cd in other shells. In fact, using the implied cd of typing a path alone produces the expected results. It only "jumps" to the last visible, non-empty directory when using tab completion with cd.

The autosuggestion *is* displaying the full path that ultimately completes, so I'm not surprised it's completing more than I want, and I can still use Alt+arrows to get where I want, but that's a lot less convenient than just hitting tab.

**Comment by zanchey** [comment]
Yes, this is intentional. See #88 (!)

**Comment by timkite** [comment]
OK, that at least explains skipping the hidden directories (and come to think of it, the directory auto-complete in functions other than cd also skip hidden). What about cd's auto-complete skipping empty directories, though?

**Comment by faho** [comment]
>If I enter cd /dir/empty <tab> (assuming there are no other matches for "empty"), it will complete all the way to /dir/emptydir/website/, which is less than convenient if I really just wanted to get to "emptydir".

This has been changed in #4402. Now only suggestions will do it.

I don't think we want to change the behavior regarding hidden directories, so I'm closing this.
