### ISSUE TITLE
Toggling time attribute being displayed in Fish Terminal 

### ISSUE THREAD

**Issue by vipulgupta2048** [fish-shell/fish-shell#4815]
**Outputs that were needed for more information:**
**fish --version:**  fish, version 2.2.0
**uname -a:**  Linux 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux [_Actually its Xubuntu 16.04_]
**$TERM:**  xterm
##########################################
I was searching the web if there was some way I could toggle the time that was being displayed on the terminal screen. Turns out there wasn't any. Personally, I think it's of no use to display time down to the seconds in the command-line. Its distracting, it's useless, and it's annoying when scripts run with a lot of arguments resulting in it taking a fair bit of extra space on the screen. 
In the config.fish file, there should be a parameter for turning on and off the time attribute easily. If someone wants to use that feature they can and is also able to customize how time is shown. 

Suggestion - add a 0 or 1 parameter to the time option or give developers a way to use that space for good. We can let the community decide on that one.

**Comment by vipulgupta2048** [comment]
I would like to take this up too, as I would love to contribute to Fish and developing a fix for it.

**Comment by zanchey** [comment]
Hm, my terminal doesn't show this at all - can you show a screenshot? I wonder if this is coming from your chosen prompt function?

**Comment by faho** [comment]
> fish, version 2.2.0

Also note that that fish version is rather old. You might want to switch to using [our PPA](https://launchpad.net/~fish-shell/+archive/ubuntu/release-2), where you can get 2.7.1.

**Comment by vipulgupta2048** [comment]
@faho  Thanks for that, I don't know why it hasn't updated yet when I ran sudo apt update or sudo apt upgrade. I downloaded fish by the method giving on the official website. 
@zanchey Yes, I just checked. I switched prompts to see if there are any change, and true enough it was in the case of the git prompt that I use. 
I want to know if there is any way to get rid of it and still keep using the git prompt.

**Comment by faho** [comment]
>I want to know if there is any way to get rid of it and still keep using the git prompt.

You need to modify the function then. Check `fish_prompt` (or `fish_right_prompt` if it's on the right) and any functions that calls for anything like `date` (via e.g. `functions fish_prompt`), `funced` that function and `funcsave` it once you are happy.

**Comment by vipulgupta2048** [comment]
@faho I installed the updated version that you referred to and kept getting this error (refer image) 
It wasn't coming before. I followed these steps to run fish as root but to no avail. Any solutions?
https://askubuntu.com/questions/848030/fish-shell-as-default

![adsd](https://user-images.githubusercontent.com/22801822/37507561-288de0f0-2915-11e8-8669-10032de09c9d.jpeg)
Ps. That fish is my greeting message by the way.

**Comment by vipulgupta2048** [comment]
Also, is it fish_prompt or the user-made fish_prompt.fish file in the .config folder. If it is the latter then where can I find it. There are many in the root directory.

**Comment by vipulgupta2048** [comment]
@faho I implemented your suggestion like [this](https://github.com/vipulgupta2048/dotvfiles/blob/master/fish/functions/fish_right_prompt.fish). I added this for future reference if anyone else would need it. Toodles.

**Comment by faho** [comment]
@vipulgupta2048: Did you put the `chsh` part in your config.fish? That's not necessary. You just needed to run it once, which changed your system configuration (/etc/passwd, most likely).
