### ISSUE TITLE
set -l in `if` scope should be consistent with new for scope

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4820]
Since #1935 has been committed, the following behavior changes from "enhancement" to "bug" since there's now an inconsistency in fish's syntax:

```fish
~> if not set -l output (somecmd && echo "success")
                      echo "command failed!" 1>&2
      end
      echo "Output is: "$output
Output is: 
```

**Comment by mqudsi** [comment]
@faho @zanchey are there other keywords that would need this change?

**Comment by faho** [comment]
I'd imagine `while` and possibly `begin`. Of the other keywords, `command` and `exec` can't possibly set a local variable, the booleans already work like this, and the others don't take a command.

Logically, either `begin` is special or 

```fish
begin set -l foo bar
# do stuff
end
```

is different from

```fish
begin
set -l foo bar
# do stuff
end
```

**Comment by mqudsi** [comment]
Shouldn't the first form just be illegal, like a command after `end`? It's too syntactically ambiguous, a `;` should be required after it if trying to execute on the same line?

**Comment by faho** [comment]
In #986 we decided to just keep it as-is, as

>it seems relatively harmless

**Comment by mqudsi** [comment]
You are a treasure trove of fish history, @faho 👍

**Comment by mqudsi** [comment]
I think #4443 is the opposite of this, a scope is being created for `eval`.

**Comment by ridiculousfish** [comment]
I went ahead and fixed this for `if` and `while` but left `begin` alone, since there's no reason why you would set a variable inside a `begin` block if you wanted it outside.

**Comment by mqudsi** [comment]
Awesome, thanks @ridiculousfish
