### ISSUE TITLE
Makefile completion should detect --file argument

### ISSUE THREAD

**Issue by dbeckwith** [fish-shell/fish-shell#4826]
Right now the [Makefile completion](https://github.com/fish-shell/fish-shell/blob/master/share/completions/make.fish) doesn't give any indication of the `--file` option to [`__fish_print_make_targets`](https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_print_make_targets.fish). It assumes the target Makefile you're using is one of `{GNUmakefile,Makefile,makefile}` and so will only complete targets from those files. It would be nice if it could parse for the `--file` option in your command line just like it does with the `--directory` argument. I can submit a PR at some point since this seems pretty easy, if it seems like a good idea.

**Comment by faho** [comment]
Go for it!
