### ISSUE TITLE
`source` does not handle multiple arguments

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4827]
```fish
~> echo 'echo hi' > 1.fish
~> echo 'echo bye' > 2.fish
~> source 1.fish 2.fish
hello
~>
```

**Comment by faho** [comment]
Like [the documentation](http://fishshell.com/docs/current/commands.html#source) says:

>Synopsis
>source FILENAME [ARGUMENTS...]

>Description
>[...]
> If additional arguments are specified after the file name, they will be inserted into the $argv variable.

**Comment by mqudsi** [comment]
Oops!
