### ISSUE TITLE
`fish_postexec` should probably not be emitted on blank enter

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4829]
The `fish_postexec` event is documented as being emitted "right after executing an interactive command" and is noted to also be executed when an invalid command is entered (e.g. command not found).

However, in implementation the event is emitted too generously, e.g.

```fish
~> <ENTER>
fish_postexec called
~>
```

There's already a `fish_prompt` that is called each time the prompt is displayed.

**Comment by zanchey** [comment]
I think `fish_postexec` is useful also for terminal integration or other software that may ship a configuration snippet rather than modifying `fish_prompt`.

**Comment by krobelus** [comment]
resolved by #7085
