### ISSUE TITLE
Escape sequence for color normal

### ISSUE THREAD

**Issue by Jomik** [fish-shell/fish-shell#4832]
I have been completely unable to find the escape code for setting normal color. I need this for a theme, to change the "normal" output, as it doesn't work very well with a light background. I suppose I could change the prompt to use a different color than 'normal', but this isn't really what I want, and I will have issues with stuff like the headers in `exa -lah` then.

How do I change the color of `normal`?

Trying to do something along these lines:
`printf '\033]4;0;rgb:00/00/00\007'`

**Comment by faho** [comment]
Which "normal" are you talking about and why do you want the escape sequence?

Usually when dealing with colorization in fish, you'll want to use `set_color`, which takes colors (named or as RGB values) and translates them to the appropriate escape sequence. That does take a "normal" name, which it translates to the "sgr0"/"exit_attribute_mode" sequence (see `man terminfo`). That just returns the terminal to its "normal" text (including color), so to change that you'll have to change it in your terminal. I am unaware of an escape sequence to change that configuration.

Or do you mean the color of "normal" (unhighlighted) text inside fish? For that, set the `$fish_color_normal` variable.

**Comment by Jomik** [comment]
Yeah, I meant the `$fish_color_normal`, and the reason I want to change them with escape sequences, is because I'd like to be able to change the full 256 colors, I suppose. I'd also rather not decide what color the user want to use as `$fish_color_error`, if they choose "red", then it'd be translated through the palette set by the escape codes to the theme's red color.
Changing `$fish_color_normal` doesn't seem to have any effect when using `set_color normal`?

![screenshot from 2018-03-17 21-14-31](https://user-images.githubusercontent.com/699655/37559539-3a8b23da-2a28-11e8-9f94-882f3b9ad27e.png)

**Comment by faho** [comment]
>Changing $fish_color_normal doesn't seem to have any effect when using set_color normal?

Yeah, because `set_color normal` means "reset to the terminals normal display", while `$fish_color_normal` is the color fish uses for its "unhighlighted" text.

To set the color to fish's unhighlighted color, use `set_color $fish_color_normal`.

>because I'd like to be able to change the full 256 colors

What do you mean by that? Do you mean change the terminal's palette? Then change the terminal's configuration.

>I'd also rather not decide what color the user want to use as $fish_color_error,

Is this for your own config or for something you're developing for others?

>Also, is there a way I can check if fish thinks my term supports the full 256 colors?

Currently, the best you can do is to check what sequences `set_color` uses. I'd be open to adding something better. Also 256 colors isn't "full" anymore - we support RGB, so 16 million is "full" :smile:.

**Comment by Jomik** [comment]
Oh god. Yeah, you're right. RGB is full :+1: 

I meant that it seemed like fish's normal color didn't actually use the terminal's palette..
But, of course you do! You don't use color 8, you use the foreground color :joy: 
I figured it out... I can change the terminal's foreground, which is what `set_color normal` defers to.
So, for anyone else:
Make foreground black
`printf '\033]10;rgb:00/00/00\007'`
make background black
`printf '\033]11;rgb:00/00/00\007'`

Thank you for the answers!
