### ISSUE TITLE
Build breakage on macOS: muParserTokenReader.cpp

### ISSUE THREAD

**Issue by dsMrP** [fish-shell/fish-shell#4838]
Clone a the repo (or pull to grab the latest). Then perform a build from *clean*

`** INSTALL FAILED **

The following build commands failed:
	CompileC build/fish.build/Release/muparser.build/Objects-normal/x86_64/muParserTokenReader.o muparser-2.2.5/src/muParserTokenReader.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/fish.build/Release/muparser.build/Objects-normal/x86_64/muParserBase.o muparser-2.2.5/src/muParserBase.cpp normal x86_64 c++ com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)`

**Comment by faho** [comment]
Yup, the xcode build hasn't been updated for the muparser/tinyexpr switch. I have no idea how to do that, and I don't have a machine to test it on, so I'll leave it up to @ridiculousfish, @zanchey or whoever else wants to take it.

**Comment by ridiculousfish** [comment]
We should remove the Xcode build as the CMake build is almost ready; I think all that's missing is the building of installation packages.

**Comment by mqudsi** [comment]
Especially since CMake can generate XCode project files.

That said, there are a few open issues regarding the cmake build, @ridiculousfish. I think I filed separate issues for each.
