### ISSUE TITLE
man page format error

### ISSUE THREAD

**Issue by harryoooooooooo** [fish-shell/fish-shell#4840]
I am using fish version 2.7.1 on archlinux with xterm-256color.
There are errors  in the man page of fish and the fish shell builtin commands.
```
fish(1)                                                         fish                                                         fish(1)

NAME
       fishfish - the friendly interactive shell
        -

   Synopsis
       fish [OPTIONS] [-c command] [FILE [ARGUMENTS...]]

```
The command name appear twice in the category NAME,
and all categories after NAME have a unnecessary indent.

**Comment by faho** [comment]
Duplicate of #4016, which you'll be happy to know has been fixed for fish 3.0.
