### ISSUE TITLE
wait command crashes fish

### ISSUE THREAD

**Issue by YaLTeR** [fish-shell/fish-shell#4847]
Trying to use the `wait` command, for example `wait 1`, crashes fish.
```
#0  0x00007f6fc89e2e36 in __strlen_sse2 () from /usr/lib/libc.so.6                                                                                                                                                                                         
#1  0x00007f6fc89a7c48 in vfwprintf () from /usr/lib/libc.so.6                                                                                                                                                                                             
#2  0x00007f6fc89be4dd in vswprintf () from /usr/lib/libc.so.6
#3  0x000056034b912716 in append_formatv(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >&, wchar_t const*, __va_list_tag*) ()
#4  0x000056034b8deb97 in output_stream_t::append_format(wchar_t const*, ...) ()
#5  0x000056034b90f96f in builtin_wait(parser_t&, io_streams_t&, wchar_t**) ()
#6  0x000056034b8de7c2 in builtin_run(parser_t&, wchar_t const* const*, io_streams_t&) ()
#7  0x000056034b939262 in ?? ()
#8  0x000056034b93b2b0 in exec_job(parser_t&, job_t*) ()
#9  0x000056034b97831b in parse_execution_context_t::run_1_job(tnode_t<grammar::job>, block_t const*) ()
#10 0x000056034b97858d in parse_execution_context_t::run_job_conjunction(tnode_t<grammar::job_conjunction>, block_t const*) ()
#11 0x000056034b97c6e6 in parse_execution_result_t parse_execution_context_t::run_job_list<grammar::job_list>(tnode_t<grammar::job_list>, block_t const*) ()
#12 0x000056034b979a42 in parse_execution_context_t::eval_node(tnode_t<grammar::job_list>, block_t const*, io_chain_t const&) ()
#13 0x000056034b98a868 in int parser_t::eval_node<grammar::job_list>(std::shared_ptr<parsed_source_t const>, tnode_t<grammar::job_list>, io_chain_t const&, block_type_t) ()
#14 0x000056034b988347 in parser_t::eval(std::shared_ptr<parsed_source_t const>, io_chain_t const&, block_type_t) ()
#15 0x000056034b989aad in parser_t::eval(std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >, io_chain_t const&, block_type_t) ()
#16 0x000056034b9981a1 in reader_run_command(parser_t&, std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> > const&) ()
#17 0x000056034b9a037f in ?? ()
#18 0x000056034b9a0977 in reader_read(int, io_chain_t const&) ()
#19 0x000056034b9b4be1 in main ()
```
```
fish, version 2.7.1-995-g316303d7
```
Arch Linux x64, Konsole

**Comment by krader1961** [comment]
What does `locale` output? That error looks a lot like a localization error. That is, a localized message that references an argument no longer included in the formatting of the string.

Looking at the localized messages I see that the *po/en.po* translation file incorrectly uses a `%s` placeholder where `%d` is correct:

```
po/en.po-#, fuzzy, c-format
po/en.po:msgid "%ls: Could not find job '%d'\n"
po/en.po-msgstr "%s: Could not find “%s”\n"
```

**Comment by YaLTeR** [comment]
Here's my `locale` output:
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by zx8** [comment]
Ping @s417-lama @tasq0

**Comment by s417-lama** [comment]
Pong

I could reproduce the bug. It seems to be an error around localization.
In `builtin_wait.cpp`,
```
streams.err.append_format(_(L"%ls: Could not find job '%d'\n"), cmd, pid);
```
this section causes the error. And,
```
%ls: Could not find job '%d'\n
```
is translated to
```
%s: Could not find %s\n
```
by `wutil.cpp:wgettext()`.

Updating .po files would solve this issue.

**Comment by s417-lama** [comment]
And also, removing process expansion (#4230) disabled waiting for jobs by job id, such as
```
wait %1
```
and using the job id as an argument like below is not supported now.
```
wait 1
```

We may not distinguish a job id and a process id only by the number (consider the case there are so many jobs).
However, it is much preferable to be able to wait for jobs by their job id. Is there any ideas?

**Comment by mqudsi** [comment]
Yes, the `jobs` builtin should have an option to get the pid(s) of jobs by number, i.e. `wait (jobs -p 1 12 7)`

**Comment by faho** [comment]
>
Additionally, the wait builtin should probably have a --job/-j parameter (that can optionally be repeated).

_Can_ `wait` wait for anything that is not under fish's control? If it can't, it could just take a job number by default.

**Comment by s417-lama** [comment]
> Can `wait` wait for anything that is not under fish's control?

No. The syscall `waitpid()` used in `wait` command can wait only for child processes.

> If it can't, it could just take a job number by default.

Yes, I prefer it. It would make the args simpler.
However, it would be a bit confusing to the users from `bash` , and so on. They write
```
$ wait %1
```
to wait for `job 1`.
So I suggest that only `wait` command take the job id as `%id` the same as before.

**Comment by mqudsi** [comment]
Whatever approach we take, it's important that it be uniformly supported by job management builtins, so it should work in at least `bg`, `fg`, `wait`, and possibly `jobs`.

**Comment by faho** [comment]
Double-fixed:

I've corrected the translations, and stopped using fuzzy translations.
