### ISSUE TITLE
Suggestion: wait for processes by their name

### ISSUE THREAD

**Issue by s417-lama** [fish-shell/fish-shell#4848]
Due to #4230, process expansion was removed. So we could not write like this:
```
$ for i in (seq 10); sleep 10 &; end
$ wait %sleep
```
When other processes are running in background, it is useful that it waits only for processes of the same name.

### Suggestion
```
$ wait sleep
```
would wait for the processes whose name is `sleep`.

How about this behaviour?
If you like this, I would implement it willingly.

**Comment by ridiculousfish** [comment]
This seems like a nice idea, I'd be happy to merge it. I look forwards to your PR :)
