### ISSUE TITLE
replacing backticks with (...) does not seem to work

### ISSUE THREAD

**Issue by stephanecharette** [fish-shell/fish-shell#4855]
Using fish 2.6.0 on Ubuntu 17.10, xterm-256color.

In bash, when I want to compile something, I'd run something similar to this:

> g++ example_01.cpp `pkg-config --cflags --libs gtk+-2.0`

In fish, from what I read I need to replace backticks with parentheses, so I tried this:

> g++ example_01.cpp (pkg-config --cflags --libs gtk+-2.0)

But it looks like the output from (...) is possibly given to g++ as a single long string instead of individual parameters.  This is the error that g++ gives me when I try the line above:

> g++: error: unrecognized command line option ‘-pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -lgtk-x11-2.0 -lgdk-x11-2.0 -lpangocairo-1.0 -latk-1.0 -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lpangoft2-1.0 -lpango-1.0 -lgobject-2.0 -lglib-2.0 -lfontconfig -lfreetype’

Am I using it wrong, or is this a bug?

**Comment by krader1961** [comment]
It's not a bug. It is a FAQ :smile:

Fish only splits the output of subcommands on newlines. POSIX shells like bash split on the value of the `IFS` var which by default is space, tab and newline. This was most recently discussed in issue #4822 just a few days ago. See issue #982.

Note that the bash (more generally POSIX shell) behavior is dangerous and fragile. If you change the value of `IFS` that will probably break the subcommand expansion. In bash do this:

```
for f in $(pkg-config --cflags --libs gtk+-2.0); do echo $f; done
```

Then do this:

```
IFS=$'\n'; for f in $(pkg-config --cflags --libs gtk+-2.0); do echo $f; done
```

See the difference in how the output of `pkg-config` is tokenized?

**Comment by stephanecharette** [comment]
Yikes, I see I'm not the first to get stuck on this exact issue!  But what is not obvious from those two other issues you linked is what in the world are users supposed to do?  The FAQ should at least mention it along with the solution.

For now I've gone back to using bash when building because I need to call pkg-config.  But I've been a fish user for years now and this is the very first time I've had to go back to bash after I couldn't figure out some sort of solution.

**Comment by faho** [comment]
> But what is not obvious from those two other issues you linked is what in the world are users supposed to do?

```fish
g++ example_01.cpp (pkg-config --cflags --libs gtk+-2.0 | string split " ")
```

>The FAQ should at least mention it along with the solution.

That sounds like a good idea.
