### ISSUE TITLE
Support --autostash for completing git pull commands

### ISSUE THREAD

**Issue by EFanZh** [fish-shell/fish-shell#4857]
Currently, I can use `git pull --rebase --autostash` (see [here](https://git-scm.com/docs/git-pull#git-pull---autostash)) to update my local repository. But `--autostash` is missing from fish completions.

**Comment by faho** [comment]
Some day I'll find out why some PRs don't auto-close the issue, even though they explicitly include a `Fixes #ISSUE`. Today is not that day.
