### ISSUE TITLE
git completions break checkout of remote branch

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4858]
The (latest version of?) the git completions breaks checkout of unique remote branches by checking out a detached head instead of creating a local branch to track the remote one.

e.g. given `origin/master` and `origin/foo` and a cloned repository on branch `master` tracking `origin/master`, `git checkout foo` will create a local branch called `foo` tracking `origin/foo` (the desired result) but `git checkout origin/foo` will check out `origin/foo` in a detached head state with no local branch to match (not desired).

The problem is that the git completions take `git checkout f<TAB>` and change it to `git checkout origin/foo`.

**Comment by faho** [comment]
>The (latest version of?) the git completions breaks checkout of unique remote branches by checking out a detached head instead of creating a local branch to track the remote one.

That's a bit of a dramatic way to phrase it.

What you mean is "the git completions don't support unique remote branches anymore". The other stuff is just a consequence of that. And the good news is that I looked at the official bash completions for git, which have a way of doing that by using "the same heuristics git checkout uses".

The bad news is that I need to test it more and it definitely will not be part of 3.0.

**Comment by gechr** [comment]
FWIW a quick workaround I've been using until this is fixed is to add `-t/--track` to the end of your checkout command, i.e.
```sh
$ git checkout f<TAB>  →  git checkout origin/foo  →  git checkout origin/foo -t
Branch 'foo' set up to track remote branch 'foo' from 'origin' by rebasing.
Switched to a new branch 'foo'
```

Not ideal, but good enough for me.
