### ISSUE TITLE
`read` supports no args but `read -s` does not

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4859]
In fish 3.0, `read` without args is taken to mean "proxy a line from stdin to stdout" but `read -s` is not aware of this and insists that read expects at least one argument but zero were provided (which is another bug, it should probably read 'variable' and not 'argument' as `-s` is at least one argument).

**Comment by zanchey** [comment]
Does `read -s` piping straight to stdout make sense? I presume for something like `read -s | login_process --take-password-from-stdin`?

**Comment by mqudsi** [comment]
My use case is actually something like `mysql -ufoo -p(read -s)` (except mysql doesn't need that any more since `-p` without a value prompts to read from stdin), which lets you "save" this command in history without the password being there, too.

**Comment by mqudsi** [comment]
Thanks, @faho
