### ISSUE TITLE
read tokenization broken

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4861]
OK, so I'm slowly trying to force myself to use fish bulitins instead of basic unix commands when writing scripts for internal consumption, but I'm having a hard time getting `read` to behave as - I think - the docs say it should:

>read reads from standard input and stores the result in one or more shell variables. **By default, one line (terminated by a newline) is read into each variable.** Alternatively, a null character or a maximum number of characters can be used to terminate the input. Unlike other shells, there is no default variable (such as REPLY) for storing the result.

```fish
mqudsi@Blitzkrieg /m/d/r/tig> echo -ne "hello world\nnew line\n"
hello world
new line
mqudsi@Blitzkrieg /m/d/r/tig> echo -ne "hello world\nnew line\n" | read -l line1 line2
mqudsi@Blitzkrieg /m/d/r/tig> echo $line1
hello
mqudsi@Blitzkrieg /m/d/r/tig> echo $line2
world
mqudsi@Blitzkrieg /m/d/r/tig>
mqudsi@Blitzkrieg /m/d/r/tig> echo -ne "hello world\nnew line\n" | string escape | read -l line1 line2
mqudsi@Blitzkrieg /m/d/r/tig> echo $line1
'hello
mqudsi@Blitzkrieg /m/d/r/tig> echo $line2
world'
```

**Comment by faho** [comment]
The documentation is wrong here. `read` doesn't read different "lines" (separated either by \n or by \0 if -z is used) into variables. It reads one "line" and splits it into the variables on characters in $IFS (this is the one place where we actually use the value of it) or the string given with "-d".

To read multiple lines, you need to use `while read`.

It does not really "tokenize", but just uses the characters - so quoting doesn't matter.

So there's two things to do here:

- Correct the documentation WRT multiple variables

- _Add_ some way to tokenize - either to `read`, or some other builtin - this was discussed in #3823.

**Comment by mqudsi** [comment]
I imagine a new `read --line` (too bad `read -l` has a different definition) could work here, overriding or temporarily setting `IFS`.

**Comment by faho** [comment]
>overriding or temporarily setting IFS.

`read --delimiter` already exists, defining the delimiter between variables (or elements with "--array"). `read` still reads until \n (or \0 if "-z" has been given).

**Comment by mqudsi** [comment]
So a `read --by-line` would act akin to `read --delimiter \n -z`, except trailing line breaks would need to be removed.

**Comment by mqudsi** [comment]
Re-opening as the actual issue isn't resolved. There's no way to read n lines into n variables with a single call to `read` (without consuming the entire input stream).
