### ISSUE TITLE
`fish_indent` mangles comments within line continuations

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#4870]
@ridiculousfish recently made some (unrelated) changes and I assume ran `fish_indent` once he was done, unwittingly breaking Git branch completions, case in point: https://github.com/fish-shell/fish-shell/commit/6e56637cf0a6036fdea4105e9f33314a3d6e8e78#diff-30e3179ef52ea52043bbe1a27c514e22R20

Somewhat related: https://github.com/fish-shell/fish-shell/pull/4807

**Comment by ridiculousfish** [comment]
Bleh, I reviewed carefully and am embarrassed I missed that. Looks like `fish_indent` has some bugs to be worked out.

**Comment by ridiculousfish** [comment]
Should be fixed in 358e9def5bfd513d0ad243f744c55318e95d56a4 - thanks!
