### ISSUE TITLE
argparse documentation confusing on one point

### ISSUE THREAD

**Issue by rfrancis** [fish-shell/fish-shell#4871]
So at least as of fish 2.7.1, there's an oddity in the manual page for argparse -- it mentions : and :: as trailing modifiers for options in examples, but it doesn't actually appear to document them.  Reading around for other examples in the wild, it appears to me that they are maybe the equivalent of = and =?, but I'm not certain enough of that to just send a PR, so issue it is...

Since this is a documentation issue, I'm skipping any discussion of my environment, etc; I went ahead and looked at [argparse.txt](https://github.com/fish-shell/fish-shell/blob/2.7.1/doc_src/argparse.txt) directly to be sure of what I was (or rather was not) seeing.

**Comment by zanchey** [comment]
Those were initially the specifiers but were removed in b3d3e07c55b9a7e183 - they should be removed from the documentation.
