### ISSUE TITLE
argparse too verbose for scripts

### ISSUE THREAD

**Issue by luc-j-bourhis** [fish-shell/fish-shell#4875]
As of version 2.7.1, argparse prints the like of

```
mirror_live: Unknown option '-j'
../mirror_live (line 17): 
argparse -n $program_name 'h/help' 'v/version' -- $argv ^&1
^
```

This is fine when used in a `function` but if one wants to use `argparse` in a script, this output is too verbose: the user of the script would be interested only in the first line, which mention the faulty option, not in the implementation details conveyed in the subsequent lines. Thus it would be nice to have an extra option to `argparse` to request terser error messages.

**Comment by faho** [comment]
This happens because argparse uses `builtin_print_help`, which is also discussed in #3404. So let's call this a duplicate!
