### ISSUE TITLE
Running ls executes file in directory called 'test'

### ISSUE THREAD

**Issue by medakk** [fish-shell/fish-shell#4879]
Please tell us which fish version you are using by executing the following:

  fish --version
  echo $version
```
fish, version 2.6.0
2.6.0
```

Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

```
# Kubuntu 17.04
Linux kkaranth-pc 4.15.0-041500-generic #201802011154 SMP Thu Feb 1 11:55:45 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
xterm-256color
```

Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:

  sh -c 'env HOME=$(mktemp -d) fish'
```
# Same behaviour even without third party customizations.
```

Tell us how to reproduce the problem. Including an asciinema.org recording is useful for problems that involve the visual display of fish output such as its prompt.

I have a folder with a single executable called "test". When I cd into this folder in fish and run ls, the file `test` executes:
```
/tmp/fishbug$ cat test
#!/bin/sh
echo "fire breathing dragons"

/tmp/fishbug$ ls
fire breathing dragons
test*
```

This does not occur in bash:
```
$ ls
test
```
The permissions of the file are `-rwxrwxr-x`. The issue only occurs with executables named "test" with the executable bit set.

**Comment by krader1961** [comment]
Your description implies your `PATH` var includes `.`. Which is a very dangerous thing to do. You should never include `.` in `$PATH`.

The reason this happens with fish and not bash is that in fish `ls` is a function on Linux which in turn uses the `isatty` command which is also a function that uses the `test` command.

**Comment by medakk** [comment]
Oops, looks like that is what is happening. `.` is in my `$PATH`. I'm not able to figure out where it has been added though.
@krader1961 - Any idea where this is being added? `.` is in my `$PATH` even with all environment variables and profiles disabled.
```
~$ env -i bash --noprofile --norc
bash-4.4$ echo $PATH
/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:.
```

Sorry for bringing this up in the fish shell issues!

**Comment by krader1961** [comment]
> Any idea where this is being added?

There are so many possibilities it's hard to know where to begin. Your system may have a */etc/paths.d* directory or */etc/paths* file. Or perhaps the sysadmin has configured PAM (pluggable authentication modules) subsystem to include it. Or someone has modified one of the global shell init scripts such as */etc/profile*, a file in */etc/profile.d* or */etc/bash.bashrc* to add `.` to `PATH`.

> `.` is in my $PATH even with all environment variables and profiles disabled.

From the bash man page:

> The default path is system-dependent, and is set by the administrator who installs bash.  A common value is `/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin`.

So it would seem that whomever built bash for your system thought that including `.` was a good idea.  They're wrong :smile: FWIW, I see that on OpenSuse and Ubuntu the default PATH is slightly different but both include `.` as the last entry.

**Comment by medakk** [comment]
> FWIW, I see that on OpenSuse and Ubuntu the default PATH is slightly different but both include . as the last entry.

Very unfortunate. I'll look into this elsewhere. Thanks!
