### ISSUE TITLE
Update user documentation

### ISSUE THREAD

**Issue by xiaq** [fish-shell/fish-shell#488]
http://ridiculousfish.com/shell/user_doc/html/ is badly outdated. The footer says: Generated on Fri May 25 02:21:14 2012 for fish by  doxygen 1.5.9 

@ridiculousfish Perhaps write a script to update the user doc automatically :)

**Comment by faho** [comment]
The docs at http://fishshell.com/docs/current/index.html document the latest release, so there's nothing to do here ("improve documentation" is pretty much an ongoing task that can just stay implicit).
