### ISSUE TITLE
setpgid: Permission denied

### ISSUE THREAD

**Issue by Bfgeshka** [fish-shell/fish-shell#4884]
fish, version 2.7.1-1046-g36693341-dirty
Linux 4.16 x86_64
dvtm-256color

This message appears sometimes after prompt, i.e:
```
~/  fish --version
setpgid: Permission denied
fish, version 2.7.1-1046-g36693341-dirty
```

regardless of last finished command, even can occur right after fish start.

Appears only in `dvtm` (latest master) AFAIK. It doesn't break much, only prints this line.

**Comment by faho** [comment]
I just built dvtm from git (ending up with "dvtm-v0.15-37-gb45828d"), and my fish is 2.7.1-1046-g36693341 (i.e. the exact same as yours, modulo whatever patch you applied).

I can't reproduce.

@Bfgeshka: Can you try running without your configuration?

**Comment by Bfgeshka** [comment]
Reproduced on root instance (where fish config is default).

**Comment by mqudsi** [comment]
I fixed a few instances of this in fish 3.0, can you please test it with that?

**Comment by Bfgeshka** [comment]
Actually I've rebuilt it just now at 14d59c53. It's hard to say for sure yet, but so far so good. I've tried to run several dozens of commands and everything is fine.

**Comment by Bfgeshka** [comment]
Nah, it still happens, but quite less often somehow.

**Comment by mqudsi** [comment]
What version of glibc is this? Does this happen when background a task?

**Comment by Bfgeshka** [comment]
glibc is 2.26.

Nah, it happens even without background tasks.

**Comment by mqudsi** [comment]
To revisit our favorite rant: the job code is so divergent, we should really be using vfork-and-exec (which is what posix_spawn uses under the hood) which is so much faster than a full-blown fork-and-exec *and* resolves all race conditions to boot (control does not pass back to the parent until the child has been exec'd, so guaranteed pgid, etc) and would eliminate all these setpgid calls in the first place.

**Comment by krader1961** [comment]
Note that `vfork()` is not required to share the address space between the parent and child. And, in fact, on OpenBSD it does not. So you can't have the child side of the vfork modify a global var in the parent. Whether or not that is a problem given how the fish job code is structured is an open question. But it definitely caused problems for ksh which is why ksh no longer uses vfork.

**Comment by mqudsi** [comment]
Yup, but I don't think we need to share any state back from the child as the startup sequence should be deterministic, i.e. we should know fully what we want the child initialization to perform before forking.

I didn't know about OpenBSD not sharing the state, however. That is interesting as it would require a COW approach with all its associated caveats to gain the performance benefits, plus additional synchronization to block the parent until the child has exec'd.
