### ISSUE TITLE
What happened to ^ operator?

### ISSUE THREAD

**Issue by kballard** [fish-shell/fish-shell#4889]
With current git master, the `^` operator seems to have disappeared. Previously it was used to redirect stderr.

I assume this was intentional, and justified by it being kind of weird and nonstandard and I bet a lot of people didn't realize it existed. However, removing it breaks existing scripts. For example, it seems to have broken [fisherman](https://fisherman.github.io).

Instead of removing it, we should keep it around but deprecate it, and then go ahead and remove it later. Deprecation can be handled by printing a message to the terminal when it's used (maybe limited to once per pipeline or job though).

**Comment by faho** [comment]
#4394 removed it.

**Comment by kballard** [comment]
Hmm, that PR explicitly says no deprecation phase. I'll close out this one and comment in there instead.
