### ISSUE TITLE
Idea: "custom sigil" to simulate zsh's "=cmd" command fullpath expansion (and many others)

### ISSUE THREAD

**Issue by xiaq** [fish-shell/fish-shell#489]
I keep a few dozens of scripts in `~/bin` (which in turn is part of my `$PATH`), and I edit them now and then. In zsh I could write `vim =script`, which is roughly equivalent to `vim $(which script)`, to edit the scripts directly; in fish I have to go the old way and write `vim (which script)`.

In zsh, the expansion of `=cmd` into its full path is part of its filename expansion. I said it is *roughly* equivalent to `$(which cmd)`, since the failure of `=cmd` will prevent the whole command from executing, while `$(which cmd)` can't. That's the only difference I can tell.

I understand how such trivial things should not be part of the shell core, but being a lazy typist, I propose an idea to make this possible in fish, i.e. **custom sigil**s:

* A custom sigil is just a function with a single-char non-alphabetical name, like `=`.
* Calling a custom sigil has the semantics of command substitution; thus `=vim` will call `=` with `vim` and substitute its output; this is different with `(= vim)` only in the following aspect:
* However, when a custom sigil fails (i.e. return non-zero), the expansion of the whole command fails.

So the custom sigil `=` can be implemented trivially with:

```
function '='
    which $argv
end
```

Challenges:

* Since custom sigils alter the semantics of commands; e.g. the output of `echo =vim` depends on whether the custom sigil `=` is defined, their *scope* should be limited in some way.

Open questions:

* Can custom sigils nest? How?
* How do I pass multiple arguments to a custom sigil?

**Comment by faho** [comment]
Adding more syntax isn't something we're enamored with.

This can be done with storing the output in a variable and checking $status, the rest is syntactic sugar.

**Comment by floam** [comment]
To be fair, we *do* have process expansion, which is useful maybe 1/10th as often as this.
