### ISSUE TITLE
How to use autojump?

### ISSUE THREAD

**Issue by Fangyh09** [fish-shell/fish-shell#4890]
macOS 10.13.2, fish=2.6.0

`autojump` need to append this line into ~/.bashrc or ~/.zshrc. 
But I don't find ~/.fishrc, are there optional ways to do it?
```bash
[[ -s $(brew --prefix)/etc/profile.d/autojump.sh ]] && . $(brew --prefix)/etc/profile.d/autojump.sh
``

**Comment by faho** [comment]
> But I don't find ~/.fishrc, are there optional ways to do it?

Fish's configuration file is at ~/.config/fish/config.fish.

You also need to adjust your script, as fish isn't compatible with bash/zsh syntax. I believe autojump includes a "autojump.fish" file that you want to use, so it would be something like

```fish
set -l file (brew --prefix)/etc/profile.d/autojump.fish
test -s "$file"; and source $file
```

**Comment by Fangyh09** [comment]
@faho Thanks!
