### ISSUE TITLE
need a way to start fish without configuration

### ISSUE THREAD

**Issue by jorda0mega** [fish-shell/fish-shell#4891]
I am unable to use the fish shell because during the last upgrade some of the configuration files got corrupted. As you can see below, I am unable to execute any command because I get an error when doing so. Typically I would modify the files with the errors and source them so the new content is loaded but I can't even do that because I cannot execute source. Is there a way to start the shell without any configuration? Is there a possible workaround? https://github.com/fish-shell/fish-shell/issues/3288

<img width="876" alt="screen shot 2018-04-10 at 10 26 18 am" src="https://user-images.githubusercontent.com/484084/38563070-03c2fdde-3caa-11e8-92fe-838f66d20cf8.png">

**Comment by faho** [comment]
>Typically I would modify the files with the errors and source them so the new content is loaded but I can't even do that because I cannot execute source.

You really can't execute anything? What happens when you do `vi<RETURN>` (or any other editor)?

-----

The obvious workaround is to open your config file in some other way - you've got a graphical session running, so edit ~/.config/fish/config.fish in a graphical editor. Then close your terminal session and open a new one.



Now, as to providing a "--norc" option: I've softened a bit since #3288. We could probably add it, though for internal reasons it would still have to read /usr/share/fish/config.fish (which isn't so much a _config_ file as _initialization_).

**Comment by Darkshadow2** [comment]
I ran into a similar situation a while ago when `__fish_datadir` was renamed to `__fish_data_dir`. I have all of my custom scripts in a git repo, and decided a while ago to create my own autoload and conf.d dirs inside it, and created a script to load from those, which is placed in `__fish_sysconf_dir/conf.d`. It does this for the autoload:

```fish
set fish_function_path[-1] $git_path/autoload
set fish_function_path $fish_function_path $__fish_data_dir/functions
```

...which before I renamed it was `__fish_datadir`. Of course, when the name changed, it meant that the default fish functions *were not in the path*, and caused fish to just lock up. I couldn't even type anything. It just sat there after spewing a lot of lines about unknown commands.

So, if you add a `--norc` flag, could it also skip loading anything from any of the conf.d dirs?

**Comment by jorda0mega** [comment]
@faho any command simply results in "fish: Unknown command '__budspencer_preexec'" like in that last line of the screenshot. I also tried modifying the config files but the changes are not getting picked up (maybe I need to source them but that too will result in the unknown command error). I've tried restarting my terminal and machine to see if the config changes get picked up but nothing. I'm pretty sure I'm missing something but can't figure out what. At this point I think my best bet would be to uninstall and reinstall.

**Comment by faho** [comment]
>any command simply results in "fish: Unknown command '__budspencer_preexec'"

@jorda0mega: The budspencer theme _[rebinds \r](https://github.com/oh-my-fish/theme-budspencer/blob/master/key_bindings.fish#L12)_! :man_facepalming: 

Which means you're never actually _executing_ anything.

You need to solve that before you can actually execute anything, which probably means uninstalling that "theme", or at least its keybindings.

--------------------

>So, if you add a --norc flag, could it also skip loading anything from any of the conf.d dirs?

@Darkshadow2: Sure.

**Comment by mqudsi** [comment]
fwiw, budspencer should use fish's event mechanism (unless it wants to determine whether a command is invoked or not which fish's event mechanism does not support as it is a unidirectional notification).

**Comment by faho** [comment]
This was already proposed in #1256, closing as a duplicate.
