### ISSUE TITLE
fish adding a fake character at the beginning of the line

### ISSUE THREAD

**Issue by rgalbo** [fish-shell/fish-shell#4892]
This is some rather strange behavior, could use some help diagnosing this.

![fish_fuckups](https://user-images.githubusercontent.com/6351996/38574806-613a3652-3cbf-11e8-96d6-0ae29e2a4334.gif)

**Comment by faho** [comment]
This looks like #4539, so I'm going to close it as a duplicate. It should be much improved in the upcoming 3.0.

**Comment by rgalbo** [comment]
a whole semantic version is exciting

**Comment by faho** [comment]
Have fun perusing [the CHANGELOG](https://github.com/fish-shell/fish-shell/blob/master/CHANGELOG.md)!

If you want, you can also try it out. If the issue still occurs, there's a new "--disable-internal-wcwidth" build option that might fix it.
