### ISSUE TITLE
Testing file math.in ... fail

### ISSUE THREAD

**Issue by kekePower** [fish-shell/fish-shell#4893]
$ fish --version
fish, version 2.7.1-1060-g14d59c53
$ echo $TERM
xterm

Distro: Mageia 6 x86_64
$ uname -a
Linux dellirium 4.14.33-server-1.mga6 #1 SMP Sun Apr 8 19:42:31 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ make test
!SNIP!
Testing file math.in ... fail
Error output differs for file math.in. Diff follows:
--- math.tmp.err        2018-04-10 22:23:07.583405488 +0200
+++ math.err    2018-04-10 22:21:04.763115791 +0200
@@ -26,5 +26,5 @@
 math: Expected at least 1 args, got only 0
 math: Error: Result is too large
 '2^650'
-math: Error: Result is too large
+math: Error: Result is infinite
 '1 / 0'

**Comment by faho** [comment]
@kekePower: How did you compile fish? What options did you use?

Please compile the following program:

```c++
#include <iostream>
#include <cmath>

int main(int argc, char** argv) {
    double a = strtod(argv[1], NULL);
    double b = strtod(argv[2], NULL);
    std::cout << a / b << std::endl;
    std::cout << std::isinf(a / b) << std::endl;
    return std::isinf(a / b);
}
```

with `g++ /path/to/file`, and run `./a.out 1 0`.

**Comment by kekePower** [comment]
Hi.

I just ran configure without options, then ran make -s j8.
After than I ran make test.

Also unable to compile your test.
```
$ g++ test.c
test.c: In function ‘int main(int, char**)’:
test.c:5:36: error: ‘strtod’ was not declared in this scope
     double a = strtod(argv[1], NULL);
```

**Comment by faho** [comment]
Oooh, sorry, I misread the diff. It's not failing in `1 / 0`, but `2 ^ 650`.

Please try:

```c++
#include <iostream>
#include <cmath>

int main(int argc, char** argv) {
    double a = strtod(argv[1], NULL);
    double b = strtod(argv[2], NULL);
    std::cout << pow(a,b) << std::endl;
    std::cout << std::isinf(pow(a,b)) << std::endl;
    return std::isinf(pow(a,b));
}
```

and call it with `./a.out 2 650`. If that prints "1" in the second line, try making the second argument smaller until it becomes 0.

**Comment by kekePower** [comment]
1023 is the highest I can go with the second line staying at 0.
```
$ ./test 2 1023
8.98847e+307
0
```

**Comment by faho** [comment]
I really think I need to get some coffee.

It **is** the `1 / 0` part. Your results are first (the "-" lines in the diff) and the expected ones are second. Math prints the message first and then the expression.

Which makes this

```
$ ./a.out 1 0
inf
1
```

all the more confusing. That's the _correct_ result!

**Comment by faho** [comment]
Okay, this is now officially _weird_. I just installed Mageia 6 in a VM. It got me gcc 5.5.

I then cloned the fish-shell repo and built the master branch.

I ran the tests and.... **NO ERRORS**.

**Comment by faho** [comment]
I still have not been able to reproduce this, so I'm closing this.

If anyone else manages to, please speak up and I'll reopen!
