### ISSUE TITLE
Unabel to redirect input to GDB

### ISSUE THREAD

**Issue by CiraciNicolo** [fish-shell/fish-shell#4894]
$ fish --version
fish, version 2.7.1
$ echo $TERM
xterm-256color

Distro: Kali Linux
$ uname -a
Linux ciraci 4.14.0-kali3-amd64 #1 SMP Debian 4.14.17-1kali1 (2018-02-16) x86_64 GNU/Linux

If I try to redirect the output of a command to the stdin of an application running in gdb I get "fish: Expected a string, but instead found a redirection"

Expected behaviour (if GDB has bash as SHELL):
```
r < <(echo "TEST")
Starting program: /home/ciraci/a.out < <(echo "TEST")
[Inferior 1 (process 118486) exited with code 0355]
```

Actual result (with Fish):
```
r < <(echo "TO STDIN")
Starting program: /root/Downloads/start < <(echo "TO STDIN")
fish: Expected a string, but instead found a redirection
exec /root/Downloads/start < <(echo "TO STDIN")
                             ^

During startup program exited with code 127.
```

**Comment by faho** [comment]
I don't think this is gdb opening your $SHELL "behind your back" - if I understand this correctly, you're explicitly telling it to do something with it. If that's the case:

Fish does not support `<()`. Instead, use `(command | psub)`.

**Comment by faho** [comment]
Also, instead of the process substitution, you could just directly pipe the output - `echo "TO STDIN" | r`.

**Comment by faho** [comment]
The question here appears to have been answered.
