### ISSUE TITLE
Array indexing behavior when using invalid range start/end is inconsistent with fish

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4897]
```fish
~> set test 1
~> echo $test[1]
1
~> echo $test[2]

~> echo $test[2..-1]
1
```

This behavior is "correct" per the documentation, which states:
> Note that invalid indexes for either end are silently clamped to one or the size of the array as appropriate.

However, since everywhere else in fish we treat a reference to an invalid index as an empty result, it makes no sense to discard with that convention here, it is inconsistent with the way fish handles unset variables everywhere else.

An example of where this would cause problems:

```fish
function foo
    # print the first argument and pass all other arguments to bar
    echo $argv[1]
    bar $argv[2..-1]
end
```

This will not handle `foo bar` in the expected manner.

I propose that this behavior be changed for fish 3.0 to return nothing. A negative index beyond negative `length of string` should be treated as index zero (i.e. not even index 1) and a positive index beyond the end of the string should be treated as index `length of string + 1` (i.e. not even the last character).

**Comment by faho** [comment]
What currently happens is:

- `-1` is translated to the last element, which is `1`

- The slice is now `2..1`, which means it goes in reverse direction

- Element `2` is ignored

- Element `1` is printed

-----

We want to support both negative indices and reverse slices, so I'm not _quite_ sure how to solve this.

How about not doing a reverse slice if the end is negative? That would solve this, but it would also mean doing `[4..-3]` on a list with 4 elements expands to nothing.

`[2..-1]` needs to work, whatever we do.

**Comment by mqudsi** [comment]
I think your proposal makes sense as it makes no sense to start from the left then backtrack but counting from the right, but I could see someone pedantically complaining. We could disable negative reverse slices only if the start is invalid? It feels almost like hack, though.

**Comment by faho** [comment]
>We could disable negative reverse slices only if the start is invalid?

That makes the direction depend on the number of elements in the list, which isn't great.

----

How about this: When just the start is negative, always reverse, and when just the end is negative, always forward.

That means:

```fish
$ set -l list 1 2 3 4 
$ echo $list[-3..1]
2 1
$ echo $list[-6..1]
# nothing - element -6 is "before the first", and we reverse, so this collapses
$ echo $list[5..-1]
# nothing - like the example here, we iterate from 5 forwards, so this collapses
$ echo $list[3..-1]
3 4
$ echo $list[4..-2]
# nothing - element -2 is element 3, and we go forwards, so this collapses
```

I struggle coming up with anything better, especially if we don't want to force adding a "step" if it's != 1 or add new syntax for referring to "to the end" - like omitting the end (`[start:]`) in python.

**Comment by faho** [comment]
Ooh, this actually started in 2.7.0!

That means I'd remove it from the list of blockers for 3.0, since it's already out there, so we should rather test the solution some more.

**Comment by faho** [comment]
Merged #
