### ISSUE TITLE
A way to submit current commandline?

### ISSUE THREAD

**Issue by mwgkgk** [fish-shell/fish-shell#4899]
There doesn't seem to be one, other than to grab the text and run `eval`, which prints the error stack on wrong input, rather than fail graciously. Appending `\r` `\n` or `^M` to commandline doesn't seem to work.

What I'm trying to do is run `fg` on empty input and submit the command otherwise:

```
function bind_enter
  set -l cmdline (commandline)
  if test -z (string trim "$cmdline")
    echo ;and fg
    commandline -f repaint
  else
    echo ;and eval $cmdline
    commandline -f kill-whole-line repaint
  end
end

# ...in fish_user_key_bindings:
bind \r bind_enter
```

Any improvements or suggestions are welcome.

**Comment by mwgkgk** [comment]
The above approach also makes the input invisible in some but not all child processes: `bash`, `guile`, `ex`

**Comment by faho** [comment]
Have you tried `commandline -f execute`?

**Comment by mwgkgk** [comment]
Exactly what I needed, thank you.
