### ISSUE TITLE
complete is many times slower than the provider command it's running

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4901]
I was trying to add history-based completions for `ssh`, but I ran into an issue with a pathological case of `complete` that made it unusable. For some reason, using `complete` with this provider hangs the shell for a full ~2 seconds while the command itself executes in approximately 11 milliseconds - including shell startup - as measured with `hyperfine`.

This is what I have:

```fish
function __ssh_history_completions --argument limit
	if echo $limit | string match -q ""
		set limit 25
	end

	set -l tokens (commandline --current-process --tokenize)
        # using sed instead of the equivalent `string replace` is around twice as fast
        # because string replace is slow but has no invocation overhead, but here we only run it once
	history --prefix ssh | sed -rn "s/.* ([A-Za-z0-9._:-]+@[A-Za-z0-9._:-]+).*/\1/p"
end

complete -k -c ssh -a '(__ssh_history_completions 25)' -f
``` 

sourcing that and then running `ssh mqudsi@<TAB>` causes the shell to hang. The output of the `history` filtering is only 107 lines. The command `history --prefix ssh | sed -rn "s/.* ([A-Za-z0-9._:-]+@[A-Za-z0-9._:-]+).*/\1/p"` takes no time at all to run.

**Comment by mqudsi** [comment]
I'm no longer able to reproduce this. *shrug*

**Comment by kballard** [comment]
BTW if you want to diagnose timing issues with fish, the `--profile` flag to `fish` can emit timing information to a file.
