### ISSUE TITLE
Autocompletion for brace expansion inserts space after completed string

### ISSUE THREAD

**Issue by frangio** [fish-shell/fish-shell#4904]
`cat f{i<Tab>` will result in `cat f{ile<Space>`. The space at the end is never useful because the user will want to write either a comma or a closing brace.

**Comment by mqudsi** [comment]
In fish 3.0 it's OK since whitespace within `{}` is allowed, both before the closing `}` or before a `,` (and ignored per-token if leading/trailing and not escaped).

Does that adequately address the concern here?

**Comment by frangio** [comment]
For the record @mqudsi refers to #3802 and its fix in https://github.com/fish-shell/fish-shell/commit/d385248cc8533d7895a80d35e36fbcd1ef7c8f54.

In a sense it is addressed, because with this you do not need to delete the inserted space to get something syntactically valid. However, I don't like spaces before commas or before curly braces, so I'd still change the completion behavior to not insert them.

**Comment by mqudsi** [comment]
So long as it's just stylistic as a matter of personal preference!

(Thanks for finding the relevant commits and issues, btw)

**Comment by frangio** [comment]
Would you mind pointing at where the code for this is so I can try and fix it?

**Comment by mqudsi** [comment]
I'm actually not too sure. The bulk of the completions code is in `src/complete.cpp`. Searching for `BRACE` should point you in the right direction.

**Comment by mqudsi** [comment]
I'm closing this as this is no longer a valid bug for fish 3.0 and whether a trailing space is inserted or not is simply stylistic. Since in general completions add trailing spaces everywhere (as they start a new argument), this would be a hard break with all the existing completions code and risks running into some dangerous territory.
