### ISSUE TITLE
Singel quotes like Bash?

### ISSUE THREAD

**Issue by Charles-Neil** [fish-shell/fish-shell#4907]
When I want to substitute `\\` for `\` I write this
```
$ echo "\\\\" | sed 's/\\\\/\\/g'
```
Then I got an error message `sed: -e expression #1, char 8: unterminated 's' command`

Turns out that single quotes and double quotes are the same in **fish**. If I want this to work, I have to do this
```
$ echo '\\\\' | sed 's/\\\\\\\\/\\\\/g'
```

---
Is there a way *(like single quotes in bash)* that can preserve the literal value of each character within the quotes?  (Didn't find one in the docs.)

If there is no such way, do you guys have any plan to implement it in the future?

By the way, thanks for the shell you created. it's really great.
OS: ubuntu

fish-version:2.7.1

kernel: 4.14.13-041413-generic

**Comment by faho** [comment]
Terribly sorry for the delay, this must have slipped through the cracks!

>Is there a way (like single quotes in bash) that can preserve the literal value of each character within the quotes? (Didn't find one in the docs.)

No. The closest thing we have is to paste the text you want. If it is inside single quotes, fish will escape any backslashes and single quotes you pasted for you.

The reason `'` quotes still interpret backslashes is so you can embed single quotes inside single quotes - e.g. `'Don\'t do that!'`. The alternative would be `'Don'\''t do that!'` (or to use double quotes, which would then need more escaping), which is quite ugly.

>If there is no such way, do you guys have any plan to implement it in the future?

I don't think so. Changing the behavior of single quotes now is quite the compatibility break, and adding yet another way of quoting doesn't sound appealing.

**Comment by zanchey** [comment]
I don't think we're likely to change that.
