### ISSUE TITLE
`history` should coalesce ignoring tokenized whitespace

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4908]
```fish
~> history delete 'ssh mqudsi@php.'
[1] ssh mqudsi@php.neosmart.net
[2] ssh mqudsi@php.neosmart.net
[3] ssh mqudsi@php.

Enter nothing to cancel the delete, or
Enter one or more of the entry IDs separated by a space, or
Enter "all" to delete all the matching entries.

Delete which entries? > 3
```

The duplicate entries (1 & 2) should be coalesced in the UI as one entry, which (when deleted) removes both. The same coalescing should be used for history search and autocompletion.

**Comment by mqudsi** [comment]
Actually, it's probably smarter to just store a normalized version of the command. That would affect the formatting for multi-line commands, however.

**Comment by kballard** [comment]
Testing on latest `master` right now, I can't get `history delete` to list any duplicate entires, much less `history search`. Are you sure lines 1 and 2 don't have some difference, e.g. trailing whitespace? (We should probably strip trailing whitespace when determining if two history entries are identical)

**Comment by krader1961** [comment]
> Testing on latest master right now, I can't get history delete to list any duplicate entries 

I can trivially reproduce this by first doing `ssh macpro2` then `ssh macpro2 . `.

> We should probably strip trailing whitespace when determining if two history entries are identical

What about leading whitespace? What about embedded whitespace that doesn't affect the meaning of the statement? What about any other difference that is irrelevant to the semantics of the statement?

> The duplicate entries (1 & 2) should be coalesced in the UI as one entry, which (when deleted) removes both. The same coalescing should be used for history search and autocompletion.

No. If the coalescing is done it should be done as part of recording history. Not by commands that process the history. This is especially important for something like the interactive `history delete` functionality since it explicitly and deliberately only deletes history entries that exactly match those chosen by the user to be deleted. If you change it to do fuzzy deletion the user can no longer depend on what they selected being the only entries being deleted.

**Comment by kballard** [comment]
> I can trivially reproduce this by first doing `ssh macpro2` then `ssh macpro2`.

I can't. What version are you using? I'm using something built from `master` 3 days ago (and none of the commits since then appear to be at all related). I just ran 2 identical `ssh` commands and I still only get one in my history.

> What about leading whitespace? What about embedded whitespace that doesn't affect the meaning of the statement? What about any other difference that is irrelevant to the semantics of the statement?

We should store a normalized tokenized form. Any whitespace that's not visible to the command being executed should not affect the history.

**Comment by krader1961** [comment]
@kballard Do `ls x` then the same command with a trailing space. Then `history search | head | cat -evt`. You should see two entries that differ only in the trailing whitespace.

> We should store a normalized tokenized form. Any whitespace that's not visible to the command being executed should not affect the history.

That has implications for multiline commands among other things. It also begs the question about normalizing quoting (e.g., single versus double) and probably other things that don't affect the semantics of the command being recorded.

If anything is done in this regard it should be limited to stripping leading and trailing whitespace. Anything more is begging for more problems than the solution solves. And that stripping sure as hell should not be done by `history search` or `history delete`. It needs to be done in the core code that appends commands to the history.

**Comment by kballard** [comment]
> You should see two entries that differ only in the trailing whitespace.

At the time I replied to your comment, your comment listed 2 identical commands. This is why I originally asked "Are you sure lines 1 and 2 don't have some difference, e.g. trailing whitespace?"

> That has implications for multiline commands among other things. It also begs the question about normalizing quoting (e.g., single versus double) and probably other things that don't affect the semantics of the command being recorded.

Fair enough. In that case I will say that we should at a minimum strip trailing whitespace. We should probably strip leading whitespace too, and probably collapse inter-argument whitespace consisting of multiple space characters down to a single character (but leave inter-argument whitespace consisting of other whitespace characters, e.g. newlines, alone).

> And that stripping sure as hell should not be done by `history search` or `history delete`. It needs to be done in the core code that appends commands to the history.

I completely agree.

**Comment by krader1961** [comment]
> ... and probably collapse inter-argument whitespace consisting of multiple space characters down to a single character (but leave inter-argument whitespace consisting of other whitespace characters, e.g. newlines, alone).

I can't make sense of that statement. You seem to be suggesting that

```
echo abc  def
```

and

```
echo abc def
```

be treated identically with regard to recording interactive command history. I don't see how that can be justified. Furthermore, your proposal means that multiline commands with indentation will not appear in `history search` output even remotely like what was originally entered.

I am somewhat sympathetic to the original problem description which solely involves trailing whitespace. Normalizing the input by stripping trailing whitespace should be harmless. But I am 100% against doing any other normalization other than possibly leading whitespace.

**Comment by kballard** [comment]
> I don't see how that can be justified.

It's justified by the argument that a) having extra spaces like that is likely to be unintentional, and b) it tokenizes identically.

I don't see why this would affect multiline commands with indentation though. A multiline command has, by definition, non-space characters in between arguments. I suppose it would mean that 

```
echo foo \
garbly baz \
qux    wat
```

would get recorded instead as 

```
echo foo \
garbly baz \
qux wat
```

but that seems like a rather extreme edge case.

That said, I don't feel particularly strongly about the inter-argument space issue.

**Comment by mqudsi** [comment]
This all is what went through my mind when I initially posted, and why I phrased it the way I did. I knew there would be an argument made both ways.  

 I too feel inter argument spacing (new lines excepted) shouldn’t be preserved as it doesn’t affect tokenization, but if the goal is to preserve what the user entered as they entered it then the other option is to hash entries to a digest of their tokenized form and group them accordingly. But that seems like a lot of work for little benefit.

**Comment by zanchey** [comment]
Leading spaces prevent the command from being stored in history, although removing a leading newline (does that even happen in practice?) might be useful.

**Comment by mqudsi** [comment]
@kballard I agree with you on the coalescing of "whitenoise" inter-argument spacing but I believe @krader1961's point about multiline commands is about cases like this:

```
begin 
    foo;
    bar;
end
```

(with leading spacing applied automatically by the reader class in realtime) which would risk devolving into 

```
begin
foo;
bar;
end
```

or else requiring reformatting before being displayed.

In all cases, `history_item_t` gets an unparsed/raw string as its input, and so removing inter-argument spacing would necessitate instantiating a parser here to break the string down into its token components, and a) that's needless overhead, b) I'm personally not about to write that code 😁.

**Comment by mqudsi** [comment]
@zanchey I found the corner case! https://github.com/fish-shell/fish-shell/commit/f702c42068591ed6fca2509b4696df00b64e2843#diff-2828fdc80a4dab9f661b8e6da4b99fffL3459
