### ISSUE TITLE
can't login super user (root)

### ISSUE THREAD

**Issue by vandpurnama** [fish-shell/fish-shell#4910]
Why i cant login as super user anyone can help me ?

i using fish version :
  fish --2.7.1
  echo $2.7.1

![image](https://user-images.githubusercontent.com/33601181/38777556-63dce080-40d4-11e8-8245-de3c281233b1.png)

**Comment by zanchey** [comment]
Your root shell is set to `/usr/local/bin/fish`, which may not be where fish is actually installed. Try running `sudo chsh --shell (which fish) root` from your fish prompt.

**Comment by vandpurnama** [comment]
ok thanks a lot ... i used sudo -s command and it works..
![image](https://user-images.githubusercontent.com/33601181/38785474-aaaa4680-414a-11e8-86fb-b0462dff7fb8.png)
