### ISSUE TITLE
Job control (bg, fg, wait, ..) by job ID

### ISSUE THREAD

**Issue by s417-lama** [fish-shell/fish-shell#4913]
Process expansion was removed in #4230, so we cannot control jobs by their job id, like:
```
$ bg %1
```
```
$ fg %1
```
```
$ wait %1
```
As discussed in #4847, I think we should allow specifying the job id with `%` charactor only for job control commands.

However, there is a problem that `kill` commnad is not a builtin command of fish, so we cannot specify a job id for `kill` command without process expansion.
It is incoherent that we can specify job ids for `bg`, `fg` and `wait` but not for `kill`.

Is there any suggestion?

**Comment by s417-lama** [comment]
Sorry, I overlooked the commits yesterday supporting them.
Thank you @mqudsi !

**Comment by mqudsi** [comment]
No problem. Even `kill` supports job expansion now :)
