### ISSUE TITLE
Incorrect cursor shape with custom fontconfig DPI in st

### ISSUE THREAD

**Issue by Vintodrimmer** [fish-shell/fish-shell#4920]
```
➤ fish --version
fish, version 2.7.1

➤ uname -a
Linux chrysalis 4.16.2-chrysalis #1 SMP PREEMPT Mon Apr 16 11:00:03 CEST 2018 x86_64 GNU/Linux

➤ echo $TERM
st-256color
```

The problem doesn't show when I view the asciinema recording, so I'll try to use screenshots and description instead.

I've set a custom DPI (211) in fontconfig so my fonts render correctly.
I'm using `st` for a terminal with cursor shape set to a thin vertical bar ("|"),
When I start `fish`, the cursor changes shape to the block ("█") and stays that way even if I exit `fish`.
Cursor returns to the correct form if I set the DPI of 96.

Is there a way to avoid getting a block cursor instead of the bar?

Here's a gif of the process: ![cursor.gif](https://raw.githubusercontent.com/Vintodrimmer/docs/master/cursor.gif)

For some reason, asciinema shows cursor as a block from the very beginning: [![asciicast](https://asciinema.org/a/79Xt96YPOaAYpCySdTtyeSFQw.png)](https://asciinema.org/a/79Xt96YPOaAYpCySdTtyeSFQw)

**Comment by Vintodrimmer** [comment]
```
➤ for var in (set -n | grep fish_cursor)
          echo $var $$var
  end
fish_cursor_unknown block blink
```

I am indeed using Vim mode.
Sorry, I should have run  without the customisations as suggested in the issue template, but forgot that I had made any changes.

There is no problem in the default mode.

**Comment by faho** [comment]
>fish_cursor_unknown block blink

Soo.. since that's the only defined variable, it's used in all modes. So fish just sets your cursor to a block.

I'm not sure why DPI should change anything here, and if anything, it's _breaking_ the 96-DPI case!

Try defining e.g. `$fish_cursor_insert` and `$fish_cursor_default`

**Comment by Vintodrimmer** [comment]
Setting the `$fish_cursor_insert` fixes that completely, thank you very much!

I double checked and 96 DPI just makes default font so small that block looks like a line.

Thanks again and sorry for the incorrect report!
