### ISSUE TITLE
xsel: Can't open display: (null)  Inappropriate ioctl for device when hitting Ctrl-x

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#4923]
fish shell v2.7.1
Ubuntu 16.0.4 X86_64 LTS without GUI
$TERM: xterm-256color

It is the same result when running `sh -c 'env HOME=$(mktemp -d) fish'`

When hitting `Ctrl-x` inside fish which is bound `fish_clipboard_copy` (`Ctrl-v` for `fish_clipboard_paste`)

    /usr/share/fish/functions/__fish_shared_key_bindings.fish:29:    bind $argv \cx fish_clipboard_copy

Error message is printed in fish prompt:

    >> xsel: Can't open display: (null)  
    : inappropriate ioctl for device

Since I am using ssh to access to the remote machine, so it has $DISPLAY is empty.

I tried Ctrl-x in GUI terminal, it works fine.

Since i using Emacs+tmux+fish, Ctrl-x is a key for Emacs, and Meta-c is the prefix for tmux, so I accidentally hit Ctrl-x in tmux a lot, but every time I hit Ctrl-x in fish prompt, it will print the error message, so it is really annoying.

I can check the $DISPLAY and disable the key in my config.fish, but I think it is smarter to disable such kind of bindings/features when $DISPLAY is not available in fish built-in configuration.

BTW: 
It seems I cannot unbind Ctrl-x in my config.fish (`source` it after modifying it) using:

    function fish_user_key_bindings
        if not test $DISPLAY
            bind --erase --key \cx
        end
    end

What is wrong with it?

**Comment by c02y** [comment]
Thanks, `bind --erase \cx` works, I used `bind \cx ""` after the post, it works too.

**Comment by c02y** [comment]
Is this problem going be fixed in fish-future (fixed in built-in fish configuration) or not? 

Sine it marked as fish-future but it is closed, I'm not sure if I can remove the bind line in the future.

**Comment by faho** [comment]
Sorry, forgot to change the milestone. It _is_ fixed in master, which will become 3.0.

**Comment by c02y** [comment]
Thanks.
