### ISSUE TITLE
Add string match -o

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4925]
`string match` should have a `--only/-o` option to print only the matching substring for a regex expression, similar to `grep -o`. Currently, it's necessary to use `string replace -r '.*(...).*' '$1'` instead.

**Comment by faho** [comment]
>Currently, it's necessary to use string replace -r '.*(...).*' '$1' instead.

Not quite.

In regex-mode, printing just the matching part is the default!

E.g.

```fish
$ string match -r '/.*/' -- some/weird/stuff
weird
```

In fact that's why "-e"/"--entire" exists.

**Comment by mqudsi** [comment]
Thanks, @faho. I guess this can be closed!
