### ISSUE TITLE
Do not update CMD_DURATION when pressing enter with no command

### ISSUE THREAD

**Issue by MauricioA** [fish-shell/fish-shell#4926]
The variable CMD_DURATION stores how long the last command took to run.
When pressing enter without writing anything in the terminal, CMD_DURATION is updated, as if simply pressing enter was a command (that is, it's replaced with 0 most times).

The way I see it, this is inconsistent with history and with the status variable:
- history doesn't consider an empty line as a command, and nothing gets stored in the history if you simply press enter in a terminal
- the status variable doesn't get modified when you press enter on an empty line

For consistency, it might make more sense to only update CMD_DURATION if an actual command was run.

This would be helpful for me, since I'm trying to print the duration of the last command with fish_right_prompt.

If there's a reason for not changing this, then can you tell me if there's a way to tell if the last command was an actual command and not an empty line?

fish, version 2.6.0
Linux 4.9.0-6-amd64 #1 SMP Debian 4.9.82-1+deb9u3 (2018-03-02) x86_64 GNU/Linux
screen-256color

[![asciicast](https://asciinema.org/a/Q6OK1aQz09P8aj6Cc9bJDbkAT.png)](https://asciinema.org/a/Q6OK1aQz09P8aj6Cc9bJDbkAT)

**Comment by faho** [comment]
Sounds alright.

**Comment by mqudsi** [comment]
Possibly related to #4829

**Comment by swayamraina** [comment]
I will be happy to contribute and fix this.
I have cloned the repo and made changes. I need to test the changes. Can anyone guide how to build and test?

**Comment by ridiculousfish** [comment]
Sure, see the [Building](https://github.com/fish-shell/fish-shell#building) instructions in the readme
