### ISSUE TITLE
Intellij plugin to support Fish - thoughts?

### ISSUE THREAD

**Issue by paulbhart** [fish-shell/fish-shell#4930]
This is a question to help me decide an approach or whether to create a plugin for intellij to syntax highlight, etc fish shell code.

I have taken a look at the code for the plugin that does Bash [https://github.com/jansorg/BashSupport](https://github.com/jansorg/BashSupport )and it will be a significant effort to recode the grammar from bash to fish.  What I am curious is whether anyone else has thought about how this and has ideas on how to accomplish it and/or if and more important if anyone that knows the fish code would be willing to ramp me up a bit on the parsing algorithm so I could figure out the effort / approach to create fish plugin.  

If this isn't the appropriate forum just point me to the correct way to discuss with the community of fish developers.

**Comment by ridiculousfish** [comment]
Wow, that plugin looks huge.

Parsing fish (as any non-trivial language) is complicated. fish has a well-defined grammar in [parse_grammar.h](https://github.com/fish-shell/fish-shell/blob/master/src/parse_grammar.h). There is also significant parsing to do within a token, e.g. variables within quoted string; this is currently ad-hoc.

Honestly I think the easiest thing to do would be a big regex. That won't be able to handle e.g. nested command substitutions, but it will get you 90% of the way there. This regex doesn't exist yet unfortunately.

Thanks for filing!

**Comment by windware** [comment]
Why close?

This is the reason I'm rewriting my backup script to bash because I feel better editing on IntelliJ than on vim. And I liked it better as a fish script. I think it helps fish adoption if there is such a plugin.

Some simple syntax highlighting and auto completion of variables would be very helpful.

**Comment by faho** [comment]
Because it's not our problem. This is something that someone motivated and knowledgeable about IntelliJ should tackle.

**Comment by floam** [comment]
I think this may do a bit of highlighting for fish for that product: https://github.com/edouard-lopez/fish-syntax-highlighting
