### ISSUE TITLE
Running fish from non standard location

### ISSUE THREAD

**Issue by bikeseat** [fish-shell/fish-shell#4933]
I've got fish compiled to run on ios/tvos but I can't figure out how to specify a directory for fish to look in at startup for the .fish scripts (on which fish heavily depends). 

Is there an environment variable I can pass at startup to set the directory for fish to look in? 

Do I need to pass any arguments to ./configure to be able to run from /jb/ ?

I'm running fish from /jb/bin/fish

Here's the output I get:
```
-bash-3.2# /jb/bin/fish
fish:
echo $_ " "; __fish_pwd
             ^
in command substitution
	called on standard input

fish:
__fish_pwd
^
in command substitution
	called on standard input

in command substitution
	called on standard input

fish:
echo $_ " "; __fish_pwd
             ^
in command substitution
	called on standard input

root@Apple-TV >
```

**Comment by Darkshadow2** [comment]
The directories should be compiled into fish itself. If you do `echo $__fish_data_dir` (or `$__fish_datadir` if you're compiling an older (not master) version of fish), does it output anything? That should be where it's looking for stuff, and if you specified `/jb` as the prefix to ./configure (i.e. `--prefix=/jb`) it should be `/jb/share/fish`.

**Comment by bikeseat** [comment]
OK, thanks for the reply. Just used --prefix=/jb and it worked great!
