### ISSUE TITLE
fish-shell doesn't set any locale, regardless of env settings

### ISSUE THREAD

**Issue by timbertson** [fish-shell/fish-shell#4935]
Regardless of the LC_* environment variables I set, fish doesn't seem to adopt any locale. At least that's what it looks like, from the following debug line:

```
<2> fish: init_locale() setlocale(): '(null)'
```

I believe this comes from https://github.com/fish-shell/fish-shell/blob/Integration_2.7.1/src/env.cpp#L396-L398, and (if I'm reading the docs correctly), means that a locale could not be set.

```
    char *locale = setlocale(LC_ALL, "");
    fish_setlocale();
    debug(2, L"init_locale() setlocale(): '%s'", locale);
```

According to https://fishshell.com/docs/current/#variables-locale, `$LC_ALL` should definitely have an effect. Full log:

```
$ env LC_ALL=en_AU.UTF-8 fish --debug-level 2 -c 'echo -n hello'
<2> fish: exec_path: '/nix/store/l58h3wcfvvphwyngzzrg8h06nnm30yal-fish-2.7.1/bin/fish'
<2> fish: determine_config_directory_paths() results:
paths.data: /nix/store/l58h3wcfvvphwyngzzrg8h06nnm30yal-fish-2.7.1/share/fish
paths.sysconf: /nix/store/l58h3wcfvvphwyngzzrg8h06nnm30yal-fish-2.7.1/etc/fish
paths.doc: /nix/store/l58h3wcfvvphwyngzzrg8h06nnm30yal-fish-2.7.1/share/doc/fish
paths.bin: /nix/store/l58h3wcfvvphwyngzzrg8h06nnm30yal-fish-2.7.1/bin
<2> fish: locale var LANG='en_AU.UTF-8'
<2> fish: locale var LANGUAGE='en_AU:en'
<2> fish: locale var LC_ALL='en_AU.UTF-8'
<2> fish: locale var LC_ADDRESS=''
<2> fish: locale var LC_COLLATE='en_AU.UTF-8'
<2> fish: locale var LC_CTYPE='en_AU.UTF-8'
<2> fish: locale var LC_IDENTIFICATION=''
<2> fish: locale var LC_MEASUREMENT=''
<2> fish: locale var LC_MESSAGES='en_AU.UTF-8'
<2> fish: locale var LC_MONETARY=''
<2> fish: locale var LC_NAME=''
<2> fish: locale var LC_NUMERIC=''
<2> fish: locale var LC_PAPER=''
<2> fish: locale var LC_TELEPHONE=''
<2> fish: locale var LC_TIME=''
<2> fish: init_locale() setlocale(): '(null)'
<2> fish: curses var TERM='xterm-256color'
<2> fish: curses var TERMINFO=''
<2> fish: curses var TERMINFO_DIRS=''
<2> fish: 256 color support enabled for '256color' in TERM
<2> fish: sourcing /nix/store/l58h3wcfvvphwyngzzrg8h06nnm30yal-fish-2.7.1/share/fish/config.fish
<2> fish: sourcing /nix/store/l58h3wcfvvphwyngzzrg8h06nnm30yal-fish-2.7.1/etc/fish/config.fish
<2> fish: sourcing /home/tim/.config/fish/config.fish
<2> fish: locale var LANG='en_AU.UTF-8'
<2> fish: locale var LANGUAGE='en_AU:en'
<2> fish: locale var LC_ALL='en_AU.utf8'
<2> fish: locale var LC_ADDRESS=''
<2> fish: locale var LC_COLLATE='en_AU.UTF-8'
<2> fish: locale var LC_CTYPE='en_AU.UTF-8'
<2> fish: locale var LC_IDENTIFICATION=''
<2> fish: locale var LC_MEASUREMENT=''
<2> fish: locale var LC_MESSAGES='en_AU.UTF-8'
<2> fish: locale var LC_MONETARY=''
<2> fish: locale var LC_NAME=''
<2> fish: locale var LC_NUMERIC=''
<2> fish: locale var LC_PAPER=''
<2> fish: locale var LC_TELEPHONE=''
<2> fish: locale var LC_TIME=''
<2> fish: init_locale() setlocale(): '(null)'
<2> fish: Fork #1, pid 32743: spawn external command '/usr/bin/test' from '/home/tim/.config/fish/config.fish'
<2> fish: Fork #2, pid 32744: spawn external command '/usr/bin/which' from '/home/tim/.config/fish/config.fish'
<2> fish: Fork #3, pid 32745: spawn external command '/home/tim/.local/nix/bin/direnv' from '/home/tim/.config/fish/config.fish'
<2> fish: Fork #4, pid 32750: internal builtin for 'echo'
<2> fish: Fork #5, pid 32751: internal builtin for 'echo'
<2> fish: Fork #6, pid 32752: internal builtin for 'echo'
<2> fish: Fork #7, pid 32753: internal builtin for 'echo'
<2> fish: Fork #8, pid 32754: internal builtin for 'echo'
<2> fish: Fork #9, pid 32755: internal builtin for 'echo'
<2> fish: Fork #10, pid 32756: internal builtin for 'echo'
<2> fish: Fork #11, pid 32757: internal builtin for 'echo'
<2> fish: Fork #12, pid 32758: internal builtin for 'echo'
<2> fish: Fork #13, pid 32759: internal builtin for 'echo'
<2> fish: Fork #14, pid 32760: internal builtin for 'echo'
<2> fish: Fork #15, pid 32761: internal builtin for 'echo'
<2> fish: Fork #16, pid 32762: spawn external command '/usr/bin/test' from '/home/tim/.config/fish/config.fish'
<2> fish: Fork #17, pid 32763: spawn external command '/home/tim/bin/status-check' from '/home/tim/.config/fish/config.fish'
<2> fish: Fork #18, pid 32764: spawn external command '/home/tim/bin/status-check' from '/home/tim/.config/fish/config.fish'
<2> fish: Fork #19, pid 32765: spawn external command '/home/tim/bin/status-check' from '/home/tim/.config/fish/config.fish'
hello~
```

I noticed this because after an upgrade, fish has started printing `~` after a command which doesn't have a trailing newline, instead of the fancy unicode return symbol. I'm assuming this is because it thinks I'm in some simple locale which doesn't support UTF-8.

--

```
$ fish --version
fish, version 2.7.1

$ echo $version
2.7.1
```

**Comment by krader1961** [comment]
What OS and version? Fish is simply saying that your locale isn't valid according to the libc `setlocale()` function on your system:

```
<2> fish: init_locale() setlocale(): '(null)'
```

On my system fish debug output says:

```
<2> fish: init_locale() setlocale(): 'en_AU.UTF-8'
```

What does the following command output:

```
env LANG='en_AU.UTF-8' LANGUAGE='en_AU:en' LC_ALL='en_AU.UTF-8' LC_COLLATE='en_AU.UTF-8' LC_CTYPE='en_AU.UTF-8' LC_MESSAGES='en_AU.UTF-8' locale
```

**Comment by krader1961** [comment]
The `env ... locale` command I asked you to run is probably not probative unless you can show that the `locale` program in that statement was equivalent to running `fish` in your "nix" environment.

> does that mean LC_ALL isn't valid since it's supposed to take priority? Or could there the other issues which make my locale invalid?

No and yes. That is, with a typical fish installation in a standards conforming environment `LC_ALL` has priority over the other locale env vars. But you're running fish inside "nix" which by your own admission is a nonstandard environment.

Let's try a slightly different approach. After you start the "nix" fish what does running `locale` from that fish prompt report? Note that fish doesn't modify the locale env vars it inherits unless you do so in your *~/.config/fish/config.fish* or related files. So the `locale` command run from that fish shell should report results consistent with the fish debug output you captured.

**Comment by timbertson** [comment]
Thanks for the help in narrowing down where the problem may be. Sounds like it could be nix's fault, but I'd be surprised. From my (`nix`-built) fish, `locale` gives the following:

```
$ locale
LANG=en_AU.UTF-8
LC_CTYPE=en_AU.UTF-8
LC_NUMERIC="en_AU.UTF-8"
LC_TIME="en_AU.UTF-8"
LC_COLLATE=en_AU.UTF-8
LC_MONETARY="en_AU.UTF-8"
LC_MESSAGES=en_AU.UTF-8
LC_PAPER="en_AU.UTF-8"
LC_NAME="en_AU.UTF-8"
LC_ADDRESS="en_AU.UTF-8"
LC_TELEPHONE="en_AU.UTF-8"
LC_MEASUREMENT="en_AU.UTF-8"
LC_IDENTIFICATION="en_AU.UTF-8"
LC_ALL=
```

Note that I do not have LC_ALL set (and I don't modify any locale vars in `~/.config/fish/config.fish` and friends), I just added it in the initial example because I thought that would remove ambiguity.

Would the `locale` program account for issues with actually setting the locale? Or is it just printing the relevant locale environment variables? My C is rusty, but I'm going to write a simple program which calls `setlocale()` and compile it inside/outside nix, to see if its behaviour differs.

**Comment by timbertson** [comment]
Hmm, looks like it is a nix problem after all:

```
$ env LC_ALL=en_AU.UTF-8 ./setlocale-nix
locale = (null)

$ env LC_ALL=en_AU.UTF-8 ./setlocale 
locale = en_AU.UTF-8
```

the nix version works for `LC_ALL=C`, so possibly there's some missing locale data which is causing a failure. Thanks again for your help!

**Comment by krader1961** [comment]
> ... so possibly there's some missing locale data which is causing a failure.

Yes, that is almost certainly the answer. Specifically, the `en_AU.UTF-8 ` locale definition files that would typically be found in a non-nix environment anchored at */usr/share/locale* are missing in your nix environment.
