### ISSUE TITLE
Issue to set default shell with commands mentoned in README.md 

### ISSUE THREAD

**Issue by Bonsitar** [fish-shell/fish-shell#4937]
Hi there.
Info required:
*Version: fish, version 2.6.0*
*OS: Fedora Workstation 27, GNU/Linux*
*Terminal emulator: Terminator (xterm-256color)*
*Installed fish via official F27 repo (dnf-package manager) and oh-my-fish freamwork with agnoster theme from git.*

The matter that I opened this issue is that; When I want to change my default shell to fish-shell with `chsh -s /usr/local/bin/fish` (mentioned in README.md file) I got:
> chsh: "/usr/local/bin/fish" does not exist

while in `/etc/shells` I have had:
> /bin/sh
/bin/bash
/sbin/nologin
/usr/bin/sh
/usr/bin/bash
/usr/sbin/nologin
/usr/bin/fish
/usr/bin/zsh
/bin/zsh
/bin/csh
/bin/tcsh
/usr/bin/csh
/usr/bin/tcsh

as you can see there is no `/usr/local/bin/fish` in `/etc/shells` file so that I entered `echo /usr/local/bin/fish | sudo tee -a /etc/shells` (mentioned in README.md), next time I ran `cat /etc/shells` I got;
> /bin/sh
/bin/bash
/sbin/nologin
/usr/bin/sh
/usr/bin/bash
/usr/sbin/nologin
/usr/bin/fish
/usr/bin/zsh
/bin/zsh
/bin/csh
/bin/tcsh
/usr/bin/csh
/usr/bin/tcsh
/usr/local/bin/fish

in the last line you should see `/usr/local/bin/fish` thus `chsh -s /usr/local/bin/fish` command now should work right but the matter is right there! when ran `chsh -s /usr/local/bin/fish` got;
> chsh: "/usr/local/bin/fish" does not exist

while it shouldn't go like that since I have `/usr/local/share/bin/fish` in `/etc/shells`! 
Now, What should I do to fix it?
_I also searched for similar issues but no luck!_
Hope to be cleared :)
Regards.

**Comment by Bonsitar** [comment]
Hooooooorayyyyy. Now I have found my answer in fish-shell wiki (sorry guys!). [The wiki](http://fishshell.com/docs/current/faq.html#faq-default) says: 
> You may need to adjust the above path to e.g. /usr/bin/fish. Use the command which fish if you are unsure of where fish is installed.

Now I have one more question! Why my installed path is differ from others? (I looked at some issues and have found that most of the users' fish installed path is in `/usr/local/bin/fish` this is exactly the path that mentioned in fish's wiki while my installed path was in `/usr/bin/fish`!)

**Comment by zanchey** [comment]
Packages installed by your package manager go into a different location than the files installed by compiling fish yourself (by default). Using the package manager is almost always a better idea! It handles the updates to `/etc/shells` for you.
