### ISSUE TITLE
Completions for stable rustc produce an error (but succeed)

### ISSUE THREAD

**Issue by sarum9in** [fish-shell/fish-shell#4941]
```shell
$ fish --version
fish, version 2.7.1
$ rustc --version
rustc 1.25.0
```

Autocompletion for `rustc` has the following:
```shell
set -l rust_docs (rustc -Z help \
    | string replace -r -i '(\s+)-Z(.+)--(\s+)([^\n]+)' '$2 $4' \
    | string trim \
    | string match -r '^.*[^:]$')
```

The problem is that on a stable rustc `-Z` flag produces an error message:
```shell
$ rustc -Z help
error: the option `Z` is only accepted on the nightly compiler
```

So when I try to use `rustc` for the first time in a shell I get this:
```shell
# Typing "rustc v"
$ rustc verror: the option `Z` is only accepted on the nightly compiler
```

Not sure what is the right solution here, maybe redirecting `stderr` to `/dev/null`?

**Comment by faho** [comment]
Already fixed by e1c90cac8872f68867e175ec4b4f5379dbfa27b1 and reported in #4888.

**Comment by sarum9in** [comment]
Apologies, I did not look for closed `rustc` issues when checked for known issues.

**Comment by faho** [comment]
No worries!
