### ISSUE TITLE
Syntax checking error for switch variables with --no-execute

### ISSUE THREAD

**Issue by xiamaz** [fish-shell/fish-shell#4943]
In fish 2.7.1 syntax checking for switch cases does not produce expected output for switching based on variables.

For example this simple example
```
set moo "foo"
switch $moo
case foo
    echo "hello"
end
```

Will show the followoing error when run with `fish -n`.
```
bug (line 2): switch: Expected exactly one argument, got 0

switch $moo
```

But the script will run correctly, when executed. Disabling third-party extensions does not change this behavior.

**Comment by ntkme** [comment]
The issue is not limited to `switch $variable`. It also applies to `switch (command substitution)`.

#5677 is probably also closely related to this in some way.
