### ISSUE TITLE
where are fish "default" global variables stored

### ISSUE THREAD

**Issue by bochen2014** [fish-shell/fish-shell#4944]
Hi experts,
I can't remember when/how I set up my `$http_proxy` and `$https_proxy`, but the value of `$https_proxy` is wrong, and I want to set it to the correct value. 

So far I  have tried to erase that global var and reset it by 
```
set -eg https_proxy
set -Ux https_proxy $http_proxy
```

this seems to work until I starts a new login session.  Somehow the old value comes back after I re-login, any idea??

here is my `~/.config/fish/fishd.hostname`. My understanding is that here is the storage for **universal** variables . NOT global variables.
```
SET_EXPORT https_proxy:http\x3a//correct-proxy
```
but this doesn't work because there is already a global `$https_proxy` which shadows it.

so where does the global `$https_proxy` stored? (it has the wrong value now , and I don't know how to deleted it permanently)

**Comment by bochen2014** [comment]
## setup
i have `~/.bashrc` which set `$http_proxy`, `$https_proxy` and `$no_proxy` correctly;
I also have http proxy setup via `System Settings \ Network \ Network proxy` setup correctly;

## start fish from bash
if I change my default shell to `/bin/bash` , and start `fish` from `bash`, it show the correct env vars ;  So fish inherit from current env vars (which were set by `bash`);

## start fish directly
However, if I  change default shell to `/usr/bin/fish`, logout and re-login, and start `fish` directly, it shows the wrong env vars. 
1.  it read `$http_proxy` from somewhere (I suspect from ubuntu system settings, **definitely not ~/.bashrc**,  and build `$https_proxy` itself by replacing `http` to `https`, but `https://proxy.com` doesn't exits;
2.  it resets `$no_proxy` to system default (localhost,127.0.0.0/8,::1)

**Comment by krader1961** [comment]
Fish does not read *~/.profile* (or */etc/profile) so your first conclusion is wrong. If you're running a relatively new version of fish running `set --show http_proxy` will help. Everything you've written implies that var is an env var that is exported before fish is launched. Environment vars are imported as global vars when fish starts and will shadow any universal var of the same name.

You didn't tell us either the OS or fish version you're running so we can't provide much more useful advice. But I'm pretty confident that you're setting that var in a manner that makes it an env var for whatever your login shell is. You say

> i have ~/.bashrc which set $http_proxy, $https_proxy and $no_proxy correctly;

If you're doing that for bash why can't you do the same thing for fish by setting them in your *~/.config/fish/config.fish*?

P.S., Doing `set $https_proxy correct-value` won't do what you want. The correct syntax is `set https_proxy correct-value` (note the lack of a dollar-sign).

**Comment by bochen2014** [comment]
thanks for your reply. 
1. fish version and OS version
```sh
fish -v
fish, version 2.2.0

uname -a
Linux bo-westpac 4.13.0-39-generic #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
2. yes i can set it up in my `~/.config/fish/config.fish`. I'm just curious how fish get `$http_proxy` from
as it gets `$http_proxy` correct but `$https_proxy` wrong. It's weird isn't?
3. it was a typo. I do have `set https_proxy $http_proxy` in my config.fish file

thanks again for your reply

**Comment by krader1961** [comment]
> it gets $http_proxy correct but $https_proxy wrong. It's weird isn't?

Not at all. If those are environment variables that fish imports this simply tells me you set those env vars somewhere outside of fish (probably long ago) and those values are no longer correct. If you remove setting those vars in *~/.bashrc* and set bash as your login shell I would expect it to import the same incorrect values.

Also, fish 2.2.0 is really old (as in ~3 years). You should upgrade.

**Comment by bochen2014** [comment]
just updated `fish` to 2.7.1 and did a `set --show`, here is result
```sh
fish -v
fish, version 2.7.1

 set --show http_proxy
$http_proxy: not set in local scope
$http_proxy: set in global scope, exported, with 1 elements
$http_proxy[1]: length=34 value=|http://proxy.somewhere.com.au:8080/|
$http_proxy: not set in universal scope

 set --show https_proxy
$https_proxy: not set in local scope
$https_proxy: set in global scope, exported, with 1 elements
$https_proxy[1]: length=35 value=|https://proxy.somewhere.com.au:8080/|
$https_proxy: not set in universal scope

set --show no_proxy
$no_proxy: not set in local scope
$no_proxy: set in global scope, exported, with 1 elements
$no_proxy[1]: length=25 value=|localhost,127.0.0.0/8,::1|
$no_proxy: not set in universal scope

```

My question remains the same, when `fish` starts, where does it read to pre-populate is "global scope variables", e.g. `$http_proxy` and `$https_proxy` in my example?

**Comment by krader1961** [comment]
> when fish starts, where does it read to pre-populate is "global scope variables", e.g. $http_proxy and $https_proxy in my example?

Fish does not "read" those vars from anywhere since they are not set as universal vars. They are inherited from the environment vars that exist when fish is launched. Or your fish config file (which includes your OMF plugins) are doing `set -e http_proxy`. But that is extremely unlikely.

As I wrote earlier if you stop setting those vars in your *~/.bashrc*, make bash your default shell, then launch a bash shell I would expect you to see exactly the same incorrect values. This has nothing to do with fish.

**Comment by bochen2014** [comment]
got it. thanks so much!!

another question, I've been confused by the concept of 'universal variable' in fish, as there is no counterpart in bash;
is it correct to say that ` Univeral variables === Global Variables + Persistant + shared between all fish instance `?

**Comment by krader1961** [comment]
> is it correct to say that...

Yes, that is a pretty good definition. Although at the moment the uvars are per-machine rather than truly global. In general I personally do not recommend using universal vars for things like `http_proxy`. It tends to cause more problems than it solves. Universal vars are best used, IMHO, for essentially cosmetic things like the fish prompt theme.

**Comment by bochen2014** [comment]
@krader1961 I did what you said ,  I removed `export http_proxy somewhere; expor https_proxy somewhere`   stuff from `~/.bashrc`   and   `chsh -s /bin/bash`;  I logged out and re-logged in,  then did a `echo $http_proxy $https_proxy`. the result is empty;

so I think `fish` does "read" from somewhere to pre-polulate its initial global vars, which totally makes sense to me

**Comment by bochen2014** [comment]
![image](https://user-images.githubusercontent.com/8207081/39287399-d6276db4-4966-11e8-9c0f-b9e6cc34519c.png)

**Comment by bochen2014** [comment]
my `~/.profile`
![image](https://user-images.githubusercontent.com/8207081/39287437-f7594b1a-4966-11e8-9f47-54da31615b1d.png)

**Comment by bochen2014** [comment]
but I trust you are correct. it's not `fish` who read that `$wtf` from `~/.profile`
it's either `Xorg`, or `systemd`, or some startup daemon that does that;  and because fish starts after those startup daemons, it automatically inherits those global vars.

i could be wrong though, as I'm not an expert

**Comment by bochen2014** [comment]
or `gnome-terminal` does that.....

**Comment by krader1961** [comment]
> it's either Xorg, or systemd, or some startup daemon that does that; and because fish starts after those startup daemons, it automatically inherits those global vars.

That is exactly what is happening. Also, when I said to add a variable I meant one that was not exported; e.g., `wtf=hello`. Fish is not POSIX compatible. So unless your *~/.profile* is trivial (e.g., nothing but `export` commands) fish would not be able to read it.

**Comment by bochen2014** [comment]
If you don’t export, then it is locally scoped. The caller, whoever it is, will never have a chance to know about it

**Comment by bochen2014** [comment]
But remember when I delete my bashrc, and start bash, $https_proxy was empty

I think this is worth investigate

**Comment by krader1961** [comment]
> If you don’t export, then it is locally scoped. The caller, whoever it is, will never have a chance to know about it

That's not how files like *~/.profile* work. They are processed as if the `source ~/.profile` was executed. That means any non-exported vars defined in that file will still be visible after the profile has been read. You can prove this easily:

```
$ bash -l
macbook:~ krader$ echo $wtf
hello
macbook:~ krader$ cat .profile
wtf=hello
macbook:~ krader$
```

**Comment by bochen2014** [comment]
Cool, thanks for letting me know. will try it latter.

**Comment by bochen2014** [comment]
no. that didn't work on my ubuntu. what I did
1. `vim ~/.profile` and add `wtf=hello`
2. logoff and login again
3. `echo $wtf`, show empty

**Comment by krader1961** [comment]
> I feel like i've stumbled on a very messy area

Yes, you have. And once you understand why those two cases yield different results you'll have a much better understanding of how your shell environment, whether bash or fish, gets initialized.

**Comment by bochen2014** [comment]
right... so `~/.profile` is only used by login shells

**Comment by faho** [comment]
I'm assuming the question has been answered. If you have any follow-ups, feel free to ask!

**Comment by bochen2014** [comment]
finally figured it out.. 

fish reads gsettings, same way as most applications do (e.g. chrome)
```
gsettings list-recursively org.gnome.system.proxy.http 
org.gnome.system.proxy.http host 'proxy.corp-proxy.com.au'
org.gnome.system.proxy.http port 8080
org.gnome.system.proxy.http use-authentication false
org.gnome.system.proxy.http authentication-password ''
org.gnome.system.proxy.http authentication-user ''
org.gnome.system.proxy.http enabled false
```

**Comment by bochen2014** [comment]
also found this, which is exactly what happened to me

https://github.com/Microsoft/vscode/issues/47684
