### ISSUE TITLE
The file <filename> is marked as an executable but could not be run by the operating system.

### ISSUE THREAD

**Issue by ElijahLynn** [fish-shell/fish-shell#4946]
rubber ducking this here

fish 2.3.1

rhel 7.4, guake, tmux

Same issue as https://github.com/fish-shell/fish-shell/issues/1281 but I don't have hidden lines at beginning. 

Trying to run https://github.com/yudai/sshh that I downloaded and made executable. I get 

> Failed to execute process '/home/elynn/bin/sshh'. Reason:
> exec: Exec format error
> The file '/home/elynn/bin/sshh' is marked as an executable but could not be run by the operating system.

A `file ~/bin/sshh` returns:

> sshh: ASCII text

**Comment by ElijahLynn** [comment]
Works in `bash` but not in `fish`, and was because shebang line was incorrect which I didn't even think to look at. I made a PR here https://github.com/yudai/sshh/pull/2. 

I never fathomed bash would work and fish would not because of a bad shebang line.

@krader1961 Explains the behavior here https://github.com/fish-shell/fish-shell/issues/1281#issuecomment-265788224

**Comment by termuxbeginhack** [comment]
You can use my fisherror tool by execute `
pkg install git
git clone https://github.com/termuxbeginner/fish-excut-error`

**Comment by wyaadarsh** [comment]
@linuxteralb  the repository is inaccessible and i am still getting this error. can anyone help here?

**Comment by linuxteralb** [comment]
> @linuxteralb the repository is inaccessible and i am still getting this error. can anyone help here?

run 
`pkg update
 pkg upgrade
 pkg install git
 git clone https://github.com/linuxteralb/fish-error
 bash fisherrorinstall`

**Comment by prantoran** [comment]
Hi :) First of all, I love the fish shell and happy that I found it.

About this error, not sure why am I getting this same error in Ubuntu 19.10 when I try to run bash scripts located in /home/$USER/bin. The scripts run normally in the bash shell. 

I tried fish both as the login shell and from within the bash shell, and I get the same error.

**Comment by x13robotx** [comment]
> > @linuxteralb el repositorio es inaccesible y sigo recibiendo este error. ¿Alguien puede ayudar aquí?
> 
> correr
> `pkg update && pkg upgrade && pkg install git && git clone https://github.com/linuxteralb/fish-error && bash fisherrorinstall`

Bro it

> > @linuxteralb el repositorio es inaccesible y sigo recibiendo este error. ¿Alguien puede ayudar aquí?
> 
> correr
> `pkg update && pkg upgrade && pkg install git && git clone https://github.com/linuxteralb/fish-error && bash fisherrorinstall`

the git clone asks me for my github id and password I put it and it still does not work help bro please

**Comment by TinKurbatoff** [comment]
Add a line:
#!/bin/sh
in the first line of your script. fish is picky... 
you may also add:
#!/usr/bin/env fish
OR
#!/usr/bin/env bash
as suggested by unix docs...
