### ISSUE TITLE
Case-insensitive completion of command arguments

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#4948]
_(...on case-insensitive filesystems.)_

Use-case: I have a case-insensitive filesystem and, rather than typing `command git` to skip my `git` alias, I often just uppercase the first letter (`Git`, similar to `\git` in bash) as it's far easier than typing out `command`, which in turn breaks fish's tab completion.

**Comment by zx8** [comment]
Oops, dupe: https://github.com/fish-shell/fish-shell/issues/3978

**Comment by faho** [comment]
Dupe of #2538, no?
