### ISSUE TITLE
Select Shortened Option

### ISSUE THREAD

**Issue by mustaqimM** [fish-shell/fish-shell#4953]
In `zsh`, I can select an option or it's shorthand version (as seen [here](https://my.mixtape.moe/xuffrv.webm)) but in `fish` only the version that is placed first can be selected

**Comment by faho** [comment]
Okay. Why would you want to do this?

Unless the completion is wrong (in which case it should be fixed) both forms should be equivalent, so which you pick shouldn't matter.

**Comment by floam** [comment]
A use case is: completion suggests `--foo`, the version installed only supports `-f`. Happens with GNU/BSD differences.

**Comment by mqudsi** [comment]
@floam imho that's not a use case, that's a bug in the completion.
