### ISSUE TITLE
make file completion broken in 2.7

### ISSUE THREAD

**Issue by karlseguin** [fish-shell/fish-shell#4967]
File completion for Makefile arguments became broken in 2.7 (tested on both OSX and Ubuntu)

To reproduce, create a dummy Makefile:

```
F=

test:
	ls $(F)
```

in 2.6, typing `make test F=<TAB>` brings up autocomplete. In 2.7, it doesn't.

Removing `complete -x -c make -a "(__fish_complete_make_targets (commandline -c))" --description "Target"` from the make completion "solves" this problem, but I don't think that's the correct fix.

I asked in the gitter channel, and the suggesting was that #68527f broke this and I should open this issue.

**Comment by faho** [comment]
I'd imagine this is due to #112 - 68527ff20 only changes "--description".

>Removing complete -x -c make -a "(__fish_complete_make_targets (commandline -c))" --description "Target" from the make completion "solves" this problem

That's because, before 112, when `__fish_complete_make_targets` fell back on file completion. After 112, "--no-files"/"-f" (or in this case `-x`, which is just shorthand for `-r` and `-f`), really means no files.

I'm not too familiar with make - why is a file valid here? In general, when does make accept files?

Would it be sufficient to allow files after a "="?

**Comment by mqudsi** [comment]
Make itself never accepts files as arguments, it accepts the name of the target which *may* be a file, but is often a file that doesn't yet exist (so file-based completions are useless). Any `foo=bar` after `make` is a variable assignment, and `foo` can be literally anything, as can `bar`. For instance, I have makefiles that take a URL (`make update URL=https://....`) or a version number (`make upgrade VERSION=17.2`).

That said, I would just remove the -x or -f entirely, and provide file-based completions in addition to target-based completions (which I presume are still working?).

**Comment by faho** [comment]
>In a perfect world where our make completions get all targets

Our make completions call `make`. That is pretty likely to get it right.

>automatic suffix transformation

That actually seems to be handled! With a `*.c` rule, `make -pn` prints it for all available `.c` files!

**Comment by mqudsi** [comment]
Oh, I didn't realize we were using `make` to generate the list of targets - very nice! That should handle most (if not at all) cases, then. That just leaves `foo=` which can be followed up by literally anything.
