### ISSUE TITLE
`string match -e "" -- foo` does not return any output

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4971]
I'm not certain if this is intentional, but a brief perusal of the relevant docs does not seem to indicate it's an explicit special case. When programmatically generating text to filter by literally (e.g. via `commandline -ct`), it is possible to evaluate `string match -e "" -- ...`, in which case the assumption would be that all text would match. In practice, this is an effective "match none" instead of "match all" filter.

My gut instinct is that this behavior isn't correct, but seeking feedback or comments before I patch this.

**Comment by faho** [comment]
This uses glob-mode. In that, the expression _needs_ to match the entire string. So `""` can never match anything - it'd have to be `"*"`.

Which makes "-e" entirely (HA!) useless, so we should probably change it.

**Comment by faho** [comment]
>In that, the expression needs to match the entire string

Not actually true - `string match -e "f" -- foo` _does_ print "foo"!

Which takes this into bug territory!

**Comment by mqudsi** [comment]
Yeah, that was my initial understanding of the `-e` flag. I was still trying to understand what you meant when you clarified! Thanks.

**Comment by faho** [comment]
From the code:

```c++
        if (opts.entire && !wcpattern.empty()) {
            if (wcpattern.front() != ANY_STRING) wcpattern.insert(0, 1, ANY_STRING);
            if (wcpattern.back() != ANY_STRING) wcpattern.push_back(ANY_STRING);
        }
```

That pattern was already present in 5b6814d6a. I have no idea why that "!wcpattern.empty()" is there, and the code or commit message do not contain any explanation. I'll just try removing it.
