### ISSUE TITLE
Please add a sh-compatibility mode

### ISSUE THREAD

**Issue by paddor** [fish-shell/fish-shell#4973]
I get that fish is different, and I love that it is useful out of the box and has sane completion features, but I just can't get used to the syntax. Like `cmd1; and cmd2`, why? Everybody knows `cmd1 && cmd2`. This "simplicity" doesn't actually make anything simpler IMHO.

**Comment by faho** [comment]
When it comes to `&&`, `||` and `!`, you'll be pleased to hear that we've implemented that - #4620.

If you really want something 100% sh-compatible, fish isn't it, and won't be. In that case, I suggest looking elsewhere.
