### ISSUE TITLE
set produces segmentation fault

### ISSUE THREAD

**Issue by zonk911** [fish-shell/fish-shell#4974]
Hi *,

i played around with set and i found a reproducible (at least on my machine :D) segmentation fault. 

When i execute as normal or root user `set -lgx` then fish is crashing with a segmentation fault. I tried different variations like `set -lx` or `set -gx` but these do not produce the error. 

Let me know if i can support you. 

BR Christian 

---
fish, version 2.7.1

Ubuntu 18.04 (Upgraded from 17.10)
Linux t470s 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

xterm-256color (tried terminator and gnome-shell -> same behavior)

sh -c 'env HOME=$(mktemp -d) fish'
-->
set -lgx
Segmentation fault (core dumped)

**Comment by faho** [comment]
This seems to no longer happen with current master, so I'd imagine one of the numerous changes in `set` fixed it.

Also note that `set -lg` is nonsense - a variable can't be both global and local at the same time!

**Comment by zanchey** [comment]
@faho, could you reproduce this with 2.7.1? If not (I can't) then I'm not certain we can be confident it is fixed.

**Comment by faho** [comment]
>could you reproduce this with 2.7.1?

I can reproduce _something_ `set -lg banana` prints:

>set: Variablenbereich kann nur universell, global oder lokal sein
����������������������������������������������������������������������������������������������嗋

So it's reading something that's not a string - possibly some other memory location. So I'm assuming that depending on what else you've done in your initialization, this could lead to a crash.

But I'm not seeing that with master.

**Comment by zonk911** [comment]
@faho sure you are right that it is nonsense, but it should not try to access a memory location which it is not allowed to.

I'm not sure how you handle major release changes, but i would say this is a bug in major release 2 and it should be fixed in 2. I don't mind if you don't want to fix it, i just wanted to fulfill my duty as a good responsible user of fish shell and let you know what i found out.

**Comment by ridiculousfish** [comment]
I can't reproduce even with address sanitizer. I wonder if it's related to running in a different locale?

We don't really have the capacity to maintain 2.x and 3.x release trains, outside of perhaps serious security issues.

**Comment by krader1961** [comment]
I was able to reproduce this when but now can't. Note that the failure is from this block of code:

```
    // Variables can only have one scope.
    if (local + global + universal > 1) {
        streams.err.append_format(BUILTIN_ERR_GLOCAL, cmd);
        builtin_print_help(parser, streams, cmd, streams.err);
        return STATUS_INVALID_ARGS;
    }
```

So, yes, this is almost certainly a localization bug. Specifically, *po/de.po* has this invalid translation (note the second `%ls` format directive with no equivalent in the english format):

```
#: src/builtin.h:48
#, fuzzy, c-format
msgid "%ls: Variable scope can only be one of universal, global and local\n"
msgstr ""
"%ls: Variablenbereich kann nur universell, global oder lokal sein\n"
"%ls\n"
```

As does *po/fr.po*:

```
#: src/builtin.h:48
#, fuzzy, c-format
msgid "%ls: Variable scope can only be one of universal, global and local\n"
msgstr ""
"%ls: La portée des variables peut seulement être universelle, globale ou "
"locale\n"
"%ls\n"
```

**Comment by krader1961** [comment]
Also, the "global and local" in english should really be "global or local".

**Comment by faho** [comment]
Note: Both of these translations are marked as "fuzzy" - we no longer use those. See e.g. #4847.

(I have no idea why this even attempts to use translations with different formats)
