### ISSUE TITLE
Why is my fish not installed in /usr/local/bin ??

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#4976]
I use Zorin 9 (ubuntu 14.04) and I want to set fish as my default shell but it's installed in /usr/bin/fish

Why is it there and not in /usr/local/bin/fish ??

Just being curious if I did something wrong (I installed it with apt-get)

**Comment by faho** [comment]
Packages typically don't install to /usr/local - that directory is reserved for stuff not managed by the system.

You didn't do anything wrong.

**Comment by BarbzYHOOL** [comment]
Then why does it say to type:

    chsh -s /usr/local/bin/fish

Because I just tried to type:

    chsh -s /usr/bin/fish

and it asked for a password, i put my sudo password and then I relaunch my gnome terminal but it's still using Bash and not Fish

**Comment by faho** [comment]
Because that's the directory you'd use if you had installed it via `make install`.

>chsh -s /usr/bin/fish

That's correct in your case.

>then I relaunch my gnome terminal but it's still using Bash and not Fish

You may need to login again for the change to take effect.

**Comment by BarbzYHOOL** [comment]
Oh ok, and since we're on github, we're supposed to make install.

Alright, maybe you could add in the installation readme:

    which fish

Or:

    chsh -s "which fish"

PS: I log back and I come back!

**Comment by BarbzYHOOL** [comment]
Ok it's working fine, might need to add it to the documentation (that we need to log back)

Thank you!
