### ISSUE TITLE
Feature request: Ctrl+F to complete one character at a time

### ISSUE THREAD

**Issue by m-cat** [fish-shell/fish-shell#4984]
Hi, thanks for Fish. Love it.

Let's say I start typing out `fish --` and the completion for `fish --version` pops up. If I press `Ctrl+E`, the entire line is completed. Pressing `Ctrl+F` does the same thing. I was wondering if we couldn't make `Ctrl+F` do something different: complete one character at a time.

For another example, if I type out `cargo` the completion appears for `cargo test --features="use-mock-routing" -- --nocapture`. Well, sometimes I just want the `cargo test` or `cargo test --features` part, so completion character-by-character would be useful to have. It also would be consistent with `Ctrl+E` going to end of line and `Ctrl+F` going one character forward in many editors.

I think this would be an easy change to make the "friendly interactive shell" a tiny bit friendlier :)

**Comment by mqudsi** [comment]
Doesn't right arrow already do that? And alt+right completes a single word. You could just add a binding?

**Comment by m-cat** [comment]
> Doesn't right arrow already do that?

No, it apparently has the same behavior as Ctrl+E. I also would like to avoid using the arrow keys as I don't generally take my hands off the home row.

> And alt+right completes a single word.

So it does. Is there an alternative that doesn't use an arrow key? This would actually be useful for me, as would character-wise completion in some circumstances.

> You could just add a binding?

Ah I'll read up on that when I have time, thanks for the response :)

**Comment by mqudsi** [comment]
Yeah, bindings should address your concerns. They're really easy to use, too :)

**Comment by zanchey** [comment]
`forward-char` always accepts the full autosuggestion, though, so there's definitely an enhancement possibility here.

**Comment by cskrisz** [comment]
> Is there an alternative that doesn't use an arrow key?
You can use emacs shortcuts, e.g. Alt+F for completing one word.

**Comment by m-cat** [comment]
@cskrisz That inserts a little ƒ symbol for me, in Iterm2 at least. I would love to have fully featured Emacs-style completion/navigation though :)

**Comment by m-cat** [comment]
@cskrisz Cool beans -- thanks!

> You can set the left and right key separately so you can still type special characters if you want.

Hmm, don't think I ever needed to type a special character in the terminal :)

**Comment by rien333** [comment]
Yes, this is fairly annoying and feels inconsistent given that `forward-word` does not complete the full suggestion. There is enough bindings to complete the autosuggestion as is (ctrl+e, right key). Would altering the ctrl+f behaviour be better as a variable, or should ctrl+f by default _only_ perform forward char operations?

**Comment by PoignardAzur** [comment]
Adding my support to this feature request. I already use the `End` key when I want to complete to the end of a prompt; being able to complete only one character would be convenient (right now I end up auto-completing a single word with `ctrl+right`, then backspacing to the character I wanted).

**Comment by PoignardAzur** [comment]
**Adding a summary for posterity:**

There is no default keybinding to complete a single character at the time. However, you can create your own binding by typing the following command in the shell:

```sh
bind \cf forward-single-char     # Complete a single char when pressing Ctrl+F
```

or:

```sh
bind \e\[C forward-single-char   # Complete a single char when pressing right arrow
```

To get you desired keybinding in every session, add one of the above lines to your `~/.config/fish/config.fish` file.

**Comment by m-cat** [comment]
Nice, thank you very much for your efforts. It is unfortunate that the solution will not be the default -- "this breaks existing behavior" is a bad argument for not fixing behavior that is obviously faulty. This change is an obvious improvement, and if the right people had chimed in on your contribution, this would have been the default. It's too bad I wasn't aware of that PR.
