### ISSUE TITLE
Docs missing about starting fish on main site

### ISSUE THREAD

**Issue by vfonic** [fish-shell/fish-shell#4986]
Hi guys!

I'm just on my way to switch from zsh to fish and first thing I noticed is that, after installing fish shell with `brew install fish`, I didn't know how to start it. Of course, I could've looked in the readme here (which I did and found the answer) as well as the output of brew installation. I just wanted to give a quick feedback that, if you land on the homepage, there's no clear way how to start or setup fish shell as your default shell. I think that should be there.

**Comment by ridiculousfish** [comment]
Thanks, that's easy to add if anyone wants to take it on!

**Comment by sabinem** [comment]
I would take this over in case that I understand what you want to be added and where: I just installed fish with brew and did not find anything missing, since brew tells you what to do after the installation. 
Do you want this to be added to the tutorial or make an extra paragraph after the "Go Fish" Section?

**Comment by vfonic** [comment]
@sabinem 
Yes, you got it right! Either add something below "Go Fish" (http://fishshell.com/) or in the tutorial (http://fishshell.com/docs/current/tutorial.html). The tutorial assumes that you've already started fish shell.

Basically, this information is nowhere to be found on the website. (as far as I checked)

**Comment by sabinem** [comment]
I will work on this today, I might just be a bit slow, since I still have to figure out how to contribute to this project. I have not much contributed in open source so far, but I really want to get started with contributing more frequently. So please be patient.

**Comment by sabinem** [comment]
So this issue can be closed now, since the starting instructions have been added to the tutorial and the   PR request #5025 above was merged?

**Comment by zanchey** [comment]
Yep - thanks!
