### ISSUE TITLE
Resizing terminal breaks underlines

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#4988]
Resizing the terminal window breaks underlines in fish, causing them to stretch to the end of the line when the window is enlarged or shrunk.

Before:
![image](https://user-images.githubusercontent.com/606923/40147723-696f64b8-5930-11e8-8ba7-004ccf0bf765.png)

After:
![image](https://user-images.githubusercontent.com/606923/40147726-6d141fe6-5930-11e8-8e59-41776ba8f92f.png)

**Comment by faho** [comment]
This does not happen for me, and it is quite possible this is a terminal issue. Fish explicitly quits the underline mode.

Try:

```fish
echo (set_color -u)banana(set_color normal)
```

Also, an asciinema recording would be quite helpful here!

**Comment by mqudsi** [comment]
Good thought about asciinema. The recorded output plays back without the issue so it must be a WSL terminal problem.
