### ISSUE TITLE
What does `commandline -t ""` do?

### ISSUE THREAD

**Issue by da99** [fish-shell/fish-shell#4999]
I came across this snippet:

```
   commandline -t ""
   commandline -it -- (string escape $result)
   commandline -it -- " "
   commandline -f repaint
```
I know `-it/--insert --current-token` means, "insert after the current token". 
But, what does `commandline -t ""` by itself do?

**Comment by krader1961** [comment]
It's arguably a bug that `commandline -t some-string` is allowed. When a replacement string is present the `-t` is ignored and the string replaces the current token on the command line. So an empty string removes the current token. You can experiment with this by binding to an unused key. For example, `bind \co 'commandine -t ""'`. The type a couple of words and press [ctrl-O].

**Comment by da99** [comment]
Oh, I see. It seems obvious now. Thank you. 

And `commandine -t " "` (single space command strings) adds a space when no token is selected, but replaces the token with a space if a token is selected:

```
   # command -t " "
   abc def ghi[cursor]     -> abc def[space space]
   abc def[space cursor] -> abc def[space space]
```
