### ISSUE TITLE
sudo Command Auto-Completion Broken

### ISSUE THREAD

**Issue by maxried** [fish-shell/fish-shell#5004]
`fish --version`: 2.7.1-1197-g0a337a9d-dirty (Though it's also broken on latest 1b3154e50e9c5f12146b3c715ea86c34f26e5648)

`uname -a`: Darwin gotthold 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64 (That's macOS 10.13.4 (17E202))

`echo $TERM`: xterm-256color

Terminal application is iTerm2.
`sh -c 'env HOME=$(mktemp -d) fish'` has no problem.

Problem:
Starting with 0a337a9d8ed7e8cd0b2fc6f7e9d075ed7ec59efe the autocompletion for commands after `sudo` does not work for me anymore.

Symptom:
- If I'm in fish's build root, typing `sudo make insta\t` prints `sudo make insta`.
- Typing `sudo nm\t` prints `sudo nm`.

Expected behavior:
- If I'm in fish's build root, typing `sudo make insta\t` should autocomplete to `sudo make install`.
- Typing `sudo nm\t` prints `sudo nmap`.

**Comment by mqudsi** [comment]
@faho it turns out `__fish_complete_subcommand_root` wasn't actually superfluous to my sudo completion changes; that one completes the _command_ to be executed, while my changes to the script provide completions for _that_ command.
