### ISSUE TITLE
`set` documentation missing some flags

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5006]
I just came across `set -p` in the completion scripts and couldn't find it in the documentation. It's actually pretty handy. It seems there are other flags in need of documentation, too.

**Comment by faho** [comment]
https://github.com/fish-shell/fish-shell/blob/master/doc_src/set.txt#L26?

I'm assuming you've looked online at http://fishshell.com/docs/current/index.html, but that always describes the latest _release_ - "--append" and "--prepend" is new in 3.0.

**Comment by mqudsi** [comment]
Thanks, I didn't realize `-p` was new. I was indeed going off a comparison between code and web.
