### ISSUE TITLE
ls always printing a number

### ISSUE THREAD

**Issue by ChaosCA** [fish-shell/fish-shell#5010]
### System info
Fish version, 2.7.1
Ubuntu 18.04

Error still occurs after running `sh -c 'env HOME=$(mktemp -d) fish'`

### Problem

For some weird reason, whenever I use the `ls` command, I will get the following output:
```
me@me /h/m/test> ls
5
5
5
5
```

It doesn't matter what directory I'm in, there will always be 5 number 5's printed before the result.
```
me@me /h/me> ls
5
5
5
5
Desktop/      Documents/  examples.desktop  Pictures/  snap/       Videos/
Development/  Downloads/  Music/            Public/    Templates/
```

it's such a weird issue. It does not happen in bash:

```
me@me:/home/me$ ls
Desktop      Documents	examples.desktop  Pictures  snap       Videos
Development  Downloads	Music		  Public    Templates
```

From what I can tell, it's ONLY `ls` that has this issue.

Any ideas?

**Comment by krader1961** [comment]
`ls` is normally a function. What does `type ls` output?

**Comment by krader1961** [comment]
On your system it should be a function that uses another function, `isatty`, so also show what `type isatty` outputs. For that matter, what does `isatty 1` output?

**Comment by faho** [comment]
>So it looks like it's related to built in functions?

@ChaosCA: Unlikely. Please try `command test -t 1`.

You probably have a `test` command somewhere in $PATH that is _not_ a UNIX `test` utility. In that case you should remove it and call it something else.

**Comment by krader1961** [comment]
@ChaosCA As @faho said it is almost a certainty you have a `test` command that is not the UNIX `test ` command. Running `command -a test` should show you all the directories with a `test` command and the first one is going to be the troublemaker.

**Comment by ChaosCA** [comment]
Thank you. Turns out it was the Golang test executable in the GOBIN path being ran.
