### ISSUE TITLE
Universal variables are busted on Fedora 29 on s390x

### ISSUE THREAD

**Issue by amluto** [fish-shell/fish-shell#5013]
The fish build is failing its tests.  See:

https://bugzilla.redhat.com/attachment.cgi?id=1442100

The first part of the error says:

```
Testing universal variables
Error: Wrong value for key key_1_0: expected <missing>, got val_1_0
Error: Wrong value for key key_4_1: expected val_4_1, got <missing>
Error: Wrong value for key key_4_2: expected val_4_2, got <missing>
Error: Wrong value for key key_4_3: expected val_4_3, got <missing>
Error: Wrong value for key key_4_4: expected val_4_4, got <missing>
Error: Wrong value for key key_4_5: expected val_4_5, ot <missing>
```

I don't know what's wrong, and I won't have time to dig into it seriously soon, but I would guess it's some kind of bad interaction with the updated glibc in Fedora Rawhide.

**Comment by ridiculousfish** [comment]
Thanks for filing. This test is a little flaky TBH, it could just be timing differences.

**Comment by zanchey** [comment]
Is there an easy guide on getting a s390x VM running, or access to a build machine to see if this reproduces? I tried to read the Hercules documentation but couldn't work it out; https://fedoraproject.org/wiki/Architectures/s390x looks many years out of date.

**Comment by amluto** [comment]
This is presumably a race.  I did a "scratch" rebuild of exactly the same code and it worked.

I'll see if I can figure out how to get s390x booted.  I know how to boot an s390x kernel, but I've never tried to run any userspace at all.

**Comment by faho** [comment]
Honestly, I'd just chalk this up to the test being a bit iffy - we occasionally get that failure even on x86(_64), and nobody has complained that uvars actually don't work on s390x.
