### ISSUE TITLE
Bind history to environmental parameters

### ISSUE THREAD

**Issue by sassanh** [fish-shell/fish-shell#5015]
It's a feature request:
It would be nice to store some environmental parameters in each history item row. Parameters like the directory command executed in, the version control branch, the virtual environment, and the result of a function* running on previous commands executed before the command in the history item was executed (I explain this function later.) We can even store parameters like day of week, time in day (these 2 can be extracted from the timestamp I suppose currently is being stored.)
These information in my opinion have a lot of potential to ease the use of history. First thing I can think of is to prioritize the commands in history that have more parameters in common with current situation and more frequency when suggesting auto completions. This way when you `git checkout X` and do some stuff and then type  `git check` it doesn't suggest `out X` just cause it's last command executed with `git check` header. It'll prioritize the `git checkout Y` because you ran it when you were in branch X and you never executed `git checkout X` when you were in branch X.

* The function I mentioned above is a function we should find that somehow hashes the history of commands since you started the shell till you executed the command that's going to be stored. It just came to my mind while typing this issue and I don't know what would it be. But thought maybe mentioning it here triggers some idea in someone else's mind.

**Comment by faho** [comment]
>Parameters like the directory command executed in

That's #120.

>the version control branch

Fish doesn't _know_ the version control branch, so this would require a bunch of integration or customization, and to be entirely honest I don't believe it's worth it.

Because the result is that you get _maybe slightly better_ autosuggestions.

So I'm closing this. Sorry!
