### ISSUE TITLE
Is there any way to do process substitution output?

### ISSUE THREAD

**Issue by scolby33** [fish-shell/fish-shell#5016]
I'm using fish 2.7.1 with Terminal.app on macOS 10.13.4.

I understand how to use `psub` for input, but is there any equivalent for this construction?

```
$ pbpaste | sed -e 's/whatever//' | tee >(pbcopy)
```

On macOS, `pbpaste` sends the clipboard to stdout and `pbcopy` sets the clipboard from stdin. I'd like to see the output of `sed` in my terminal while also passing it to a follow-on command.

The obvious
```
$ pbpaste | sed -e 's/^whatever//' | tee (psub | pbcopy) 
```
doesn't work and seems to sometimes leave a `psub` running in the background when stopped with Ctrl-C.

**Comment by mqudsi** [comment]
What you tried won't work because tee takes the name of the file as a parameter. 

The easiest way is to cheat and use tee to write to `/dev/tty`, and cut `psub` out entirely:

```fish
pbpaste | sed .... | tee /dev/tty | pbcopy
```

**Comment by faho** [comment]
This was asked for previously in #1786, so let's track there!

**Comment by scolby33** [comment]
I did some more thinking on this, and moreutil's `pee` can do something reasonable:
```
$ pbpaste | sed ... | pee cat pbcopy
```
`pee` copies its stdin to the stdins of every command it's given in arguments.

The real goal I'm shooting for is something that allows me to inspect the middle of a pipeline:
```
$ echo 'intermediate result' | magic_inspection_command | sed -e 's/intermediate/final/' | pbcopy
intermediate result
```
But that would get messy with large inputs becoming interlaced, I suppose. The downsides of process substitution or even `pee` in this case are clear:
```
$ echo 'intermediate result' | pee 'cat' 'sed -e "s/intermediate/final/" | pbcopy'
intermediate result
$ pbpaste
final result
```
And every further intermediate inspection would result in another nested level of quotes...not fun.

Maybe I'm trying to push my shell too far.
