### ISSUE TITLE
'disown' doesn't work

### ISSUE THREAD

**Issue by simonbcn** [fish-shell/fish-shell#5018]
```
fish, version 2.7.1
Arch Linux
```

I have created this alias: `alias st 'gedit $argv >/dev/null 2>&1 &; disown'` like explains here: https://fishshell.com/docs/current/commands.html#disown but when I execute this command: `disown: '.config/fish/config.fish' is not a valid job specifier`

What's the problem?

**Comment by krader1961** [comment]
The `alias` command is just shorthand for creating a trivial function. Note that `alias x y` is equivalent to

```
function x
    y $argv
end
```

So in your example `$argv` is being interpolated twice: where you explicitly include it and after the `disown`.

**Comment by zanchey** [comment]
Try this instead:

```fish
function st
    gedit $argv >/dev/null 2>&1 &
    disown
end
funcsave st
```

**Comment by simonbcn** [comment]
Thanks.
