### ISSUE TITLE
`__fish_describe_command` results in `awk` error

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#5022]
```
$ fish --version
fish, version 2.7.1-1236-gebc5e189
```

Probably caused by https://github.com/fish-shell/fish-shell/commit/72e9d41dcc6439963349749d3775db4b27a7d386

```
$ /usr/bin/apropos<TAB>awk: cmd. line:4: l   		if (names[name] ~ ^apropos* *\([18]\) ) {
awk: cmd. line:4: 			                  ^ syntax error
awk: cmd. line:4: 			if (names[name] ~ ^apro.* *\([18]\) ) {
awk: cmd. line:4: 			                           ^ backslash not last character on line
```

Ping @faho

**Comment by faho** [comment]
**Definitely** not _caused_ by 72e9d41! All that did was fix a crash.

**Comment by faho** [comment]
Though it does have an issue, it's not this one.

@zx8: Can you try `__fish_describe_command git` or something like it?

This looks like your awk implementation is weird.

Also try:

```fish
function __fish_describe_command --description 'Command used to find descriptions for commands'
    apropos ".?$argv" 2>/dev/null | string replace -rf '^(.*) \(.*\)[^-]* - (.*)$' '$1\t$2' \
        | string sub -l 40
end
```

**Comment by faho** [comment]
>$ /usr/bin/a<TAB>awk

@zx8: Did you do `apropos<TAB>` or `/usr/bin/apropos<TAB>`?

The latter is fixed by 8de5af5f9e4978f661f860cd41b89a1db07bc8ae - I missed the "/".

**Comment by zx8** [comment]
Thanks. I did `/usr/bin/apropos<TAB>` 👍

**Comment by faho** [comment]
In that case, please try 8de5af5 to confirm it's fixed.

**Comment by zx8** [comment]
Yep, fixed.

**Comment by faho** [comment]
Sorry for the inconvenience. 

Hopefully I've learned not to say "definitely" ever again!
