### ISSUE TITLE
Nightly Build for ARM

### ISSUE THREAD

**Issue by amiller27** [fish-shell/fish-shell#5024]
Any chance a nightly build for ARM could be added to the fish-shell/nightly-master ppa?  I'd like to use the most recent version of fish on an aarch64 computer, and it would be extremely convenient not to have to build from source.

**Comment by zanchey** [comment]
Sure! Is that ARM ARMv8 (arm64), ARM ARMv7 Soft Float (armel), or ARM ARMv7 Hard Float (armhf)?

**Comment by amiller27** [comment]
For me personally it's ARMv8, I want it for a Cortex A57 (on the NVIDIA Jetson TX2)

**Comment by zanchey** [comment]
Thanks - I've enabled arm64 builds and they're being uploaded.
