### ISSUE TITLE
Strange argv handling in fish_vi_key_bindings

### ISSUE THREAD

**Issue by YaLTeR** [fish-shell/fish-shell#5028]
I was trying to make fish enter normal mode by default with `fish_vi_key_bindings`, and while reading the source to figure out how to do that I noticed the following:

Multiple checks are done only on the first argument:
https://github.com/fish-shell/fish-shell/blob/7659554deafd7a6f8c710fc42b52328be4561c05/share/functions/fish_vi_key_bindings.fish#L13-L18

This includes what seems to be the default mode variable:
https://github.com/fish-shell/fish-shell/blob/7659554deafd7a6f8c710fc42b52328be4561c05/share/functions/fish_vi_key_bindings.fish#L51-L56

However, this code located before the check overwrites the first argument if `-s` is not present among the arguments:
https://github.com/fish-shell/fish-shell/blob/7659554deafd7a6f8c710fc42b52328be4561c05/share/functions/fish_vi_key_bindings.fish#L21-L23

Later the arguments are passed directly to `bind` as follows:
https://github.com/fish-shell/fish-shell/blob/7659554deafd7a6f8c710fc42b52328be4561c05/share/functions/fish_vi_key_bindings.fish#L64

I tried issuing `fish_vi_key_bindings default -s` (`-s` is present so it doesn't override the first argument, and `default` is the first argument so it should set the mode to normal), however it doesn't quite work (in `config.fish` it doesn't seem to affect the default mode, and when simply entered it prevents all input somehow), presumably because the said `default` is not erased from the arguments and passed directly `bind`s.

fish, version 2.7.1-1235-g56198818

**Comment by mqudsi** [comment]
Nice catch, @YaLTeR 

Does moving the `-s` check from lines 21 to 23 below lines 51 to 56 solve the problem?

**Comment by faho** [comment]
Why not always add `-s`? It should even be harmless if it's passed multiple times.

**Comment by YaLTeR** [comment]
Somewhat related, I found no way of setting the default mode. The variable the function sets in the end, `fish_bind_mode`, seems to be completely ignored when changed from `config.fish` (even though changing it after the shell is running does result in mode change).

**Comment by faho** [comment]
>The variable the function sets in the end, fish_bind_mode, seems to be completely ignored when changed from config.fish

This is most likely down to the same thing that causes bare bind statements in config.fish to not work - we call the binding functions again after config.fish, because you might set the binding mode (as in "vi" vs "default") via `$fish_key_bindings`.

Yes, the binding system needs a bit of an overhaul.
