### ISSUE TITLE
feature-request: Add `fc` "fix command"  command, like the shell builtin

### ISSUE THREAD

**Issue by ElijahLynn** [fish-shell/fish-shell#5030]
I just learned about the bash builtin `fc` command. It takes the last command and opens it in your editor, so you can tweak it, then when you save it, it runs that new command and adds it to history. 

> fc: usage: fc [-e ename] [-lnr] [first] [last] or fc -s [pat=rep] [command]

Would love to see fish ship this command in core.

**Comment by krader1961** [comment]
Fish already has that feature. Simply [up-arrow] or [ctrl-p] to retrieve the command then press [alt-e] or [alt-v].

**Comment by icemac** [comment]
It is documented here: https://fishshell.com/docs/current/index.html#shared-binds

But it does not work out of the box in my iTerm2. [alt-e] prints `€` and [alt-v] prints `√`
Anything I missed?

**Comment by krader1961** [comment]
@icemac You need to configure iTerm2 to treat [alt] as a meta key that prefixes the sequence with the escape char. Open `Preferences` -> `Profiles` -> `Keys`. Bottom right-hand corner change the left and/or right alt key behavior to `Esc+`. Too, if you type fast enough you can just press [esc] followed by `e` or `v`.

**Comment by krader1961** [comment]
And, of course, you can bind the function to any key of your choosing; e.g., `bind \cf edit_command_buffer`.

**Comment by ElijahLynn** [comment]
@krader1961 Thanks, I just tried `alt+v` as well as `edit_command_buffer` and it opens up in vim, but the command is missing. Fish 2.7.1.

**Comment by krader1961** [comment]
Works for me and everyone else AFAIK. Note that [alt-v] edits the current command. So if you want to edit a previous command you entered you first have to retrieve it such as by pressing [up-arrow].

**Comment by ElijahLynn** [comment]
Ah, that was it. I wasn't hitting up-arrow. I suppose this solution works. I do think a built-in `fc` function to pop the last command off the stack and run `edit_command_buffer` would be good, as people coming from bash will inevitably try `fc` first and may not realize that they can do a up-arrow + alt+e or alt+v. 

OR, maybe ship a built-in `fc` function that when run, does nothing and just tells the user to do the above.

**Comment by krader1961** [comment]
What about people coming from `csh`, `zsh`, `xonsh`, `elvish` or any other random shell that has a different mechanism for doing the same thing? I recognize that bash is widely used but the whole point of fish is that it is not bash or any other POSIX shell. As for

> they may not realize that they can do a up-arrow + alt+e or alt+v.

That is a valid point. Improvements to the documentation are always welcome and arguably more valuable than changes to the implementation.

**Comment by horacimacias** [comment]
I often use _fc_ to re-run several commands again, e.g. 

> fc -3 -1

is there any way to achieve that using fish? 
e.g. "re-run the last 3 commands, in the same order they've been ran"

**Comment by lengyijun** [comment]
```
function fc
    commandline -t $history[1]; edit_command_buffer
end
```
