### ISSUE TITLE
How to edit shortcut Alt+L to display "ls -lat"?

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5032]
fish 2.7

I use "l" to list directories which is an alias to "ls -lat"

By accident I pressed Alt+L and found that it's a "ls". Can I turn it into a "l" ? How?

EDIT: and bonus, how can I add "history --show-time" to Alt+H ?

**Comment by faho** [comment]
- Check what sequence the key combination sends with `fish_key_reader` (here it's `\el`)

- Check what that is bound to with `bind \el` (here it's `__fish_list_current_token`)

- See if that is a "real" function or a special bind function with `type __fish_list_current_token`

- Since it's a real fish-script function, edit it with `funced`, save with `funcsave` once you like it

Repeat for alt+h.

**Comment by BarbzYHOOL** [comment]
Very nice tutorial, I discover all these new functions. But is it saved in my fish user config/functions? if I want to export these to another computer

**Comment by faho** [comment]
>But is it saved in my fish user config/functions?

`funcsave` will store it in ~/.config/fish/functions/. See `help funcsave´ or `type funcsave`.

**Comment by BarbzYHOOL** [comment]
Ok, awesome, this can be closed then.

**Comment by faho** [comment]
>And where are the binds saved?

They're not. There are functions that define bindings by executing `bind` commands `fish_default_key_bindings` if you are using the default set, `fish_vi_key_bindings` if you use the vi-mode and any of your own bindings should be put into `fish_user_key_bindings`.

**Comment by BarbzYHOOL** [comment]
I'm glad I asked because on the doc it says:

> To save custom keybindings, put the bind statements into a function called fish_user_key_bindings, which will be autoloaded.

It doesn't say anything about `fish_default_key_bindings` so it should be updated?

**Comment by faho** [comment]
>It doesn't say anything about fish_default_key_bindings so it should be updated?

It's mentioned in the [command line editor](http://fishshell.com/docs/current/index.html#editor) section of the docs. I'd say that's enough, especially considering it's not really something you want to edit.

**Comment by faho** [comment]
>I don't think I'm using Vi mode (just to be sure, how do I verify? but I'm 99.9% sure I don't use it)

`echo $fish_key_bindings`.

**Comment by BarbzYHOOL** [comment]
> It's mentioned in the command line editor section of the docs. I'd say that's enough, especially considering it's not really something you want to edit.

It's related to the bind command so it should be there. It just requires to add what you just told me `echo $fish_key_bindings` or to simply add "(this file in vi mode, and this file in normal mode)". But as you wish lol

Anyway thank you very much, it can be closed
