### ISSUE TITLE
Expected a command, but instead found a redirection

### ISSUE THREAD

**Issue by bboyz269** [fish-shell/fish-shell#5035]
Hi, I got error trying to install Node Version Manager (nvm - a script to install/update nodejs) .
```
~> \. "$NVM_DIR/nvm.sh"
~/.nvm/nvm.sh (line 25): Expected a command, but instead found a redirection
  >&2 nvm_echo "$@"
  ^
from sourcing file ~/.nvm/nvm.sh
	called on line 230 of file /usr/share/fish/config.fish

in function “.”
	called on standard input

source: Error while reading file “/home/me/.nvm/nvm.sh”
```
The [source](https://raw.githubusercontent.com/creationix/nvm/master/nvm.sh) in question is
```
nvm_err() {
  >&2 nvm_echo "$@"
}
```

Any help is greatly appriciated!

**Comment by kartoffelsup** [comment]
This is a (ba)sh script and not a fish script. You should run it with `bash nvm.sh`

**Comment by bboyz269** [comment]
Tried with `bash`, It indeed run but does install `nvm` properly. 

But there's a ` nvm` plugin for `fisher` man which solved my problem.
