### ISSUE TITLE
"command ls" doesn't show any color

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5039]
fish 2.7.1

To reproduce:
```
cd /etc
command ls
```

Result = no colors.

I discovered it with that alias

```
function l --wraps ls --description 'alias l=ls -lhat'
	command ls -lhat $argv;
end
```

If I remove the "command" part, then it shows all colors. Maybe it's intended but at first sight, it looked like a bug.

if intended, when should I use "command" to make an alias?

**Comment by krader1961** [comment]
This is working as intended. When you invoke the external `ls` command in that fashion you're bypassing the fish `ls` function. The external `ls` command does not color the output by default.

The first time you type `ls` fish determines if your `ls` command supports coloring and how to turn it on. It then defines a `ls` function that invokes the external command with the necessary flag. On my system that function looks like this:

```
$ type ls
ls is a function with definition
# Defined in /usr/local/share/fish/functions/ls.fish @ line 34
function ls --description 'List contents of directory'
    command ls -G $argv
end
```

Notice the `-G` flag. That tells the ls command on my system to color the output.

Practically the only time you want the explicit `command` prefix is if you are creating a function with the same name as a external or builtin command (for the latter you would use the `builtin` prefix).

**Comment by krader1961** [comment]
You should probably read the documentation for the ls command: `man ls`.

**Comment by BarbzYHOOL** [comment]
Thank you, I had already read about "command" but had forgotten the use case.

       -G, --no-group
              in a long listing, don't print group names

It's the switch "--color" for color

**Comment by BarbzYHOOL** [comment]
Ah ok!!

> You missed the part where I said "on my system."

Today I learned that "on my system" = macOS!! (just joking, thank you)
