### ISSUE TITLE
Error while using export command with flags

### ISSUE THREAD

**Issue by Kefir100** [fish-shell/fish-shell#5041]
Hi, I've got some problem.

Typing in a command: `export -p` (or any other flag) which works perfectly in bash returns the following error:
```
/usr/local/Cellar/fish/2.7.1/share/fish/functions/export.fish (line 9): $- is not a valid variable in fish.
                set -gx $v $$v
                            ^
in function 'export'
	called on standard input
	with parameter list '-p'
```

>`fish --version`
 fish, version 2.7.1
`uname -a`
Darwin MacBook-Pro-Username.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64
`echo $TERM`
xterm-256color

I am using iTerm2 v3.1.6

Thanks in advance.

**Comment by faho** [comment]
The `export` command is purely for superficial compatibility - e.g. when you have a command that prints stuff like `export VAR=VALUE`, you can then pipe it to `source`. Or when you copy-paste something.

We're not planning on full compatibility. In fish, use `set -x` to list all exported variables.

**Comment by Kefir100** [comment]
Ok. I was unaware of this command. Thanks!
