### ISSUE TITLE
Tab Completion with wildcards freezes the shell

### ISSUE THREAD

**Issue by sabinem** [fish-shell/fish-shell#5045]
I tried Tab Completion with Wildcards since the documentation mentioned:

> - Completion of filenames, even on strings with wildcards such as '`*`', '`**`' and '`?`'.

When I open a new shell and type `**` and then hit the tab key, the shell freezes and I am unable to do anything. The only thing that helps in this case is closing the shell window.

These are my parameters as you suggested to write them down:
`fish --version`: fish, version 2.7.1, 
`echo $TERM`: xterm-256color, 
`uname -a`: Darwin Sabines-MacBook-Pro.local 16.7.0 Darwin Kernel Version 16.7.0: Tue Jan 30 11:27:06 PST 2018; root:xnu-3789.73.11~1/RELEASE_X86_64 x86_64
`sh -c 'env HOME=$(mktemp -d) fish'`: Welcome to fish, the friendly interactive shell

**Comment by faho** [comment]
That's most likely just doing a whole bunch of work. `**` expands all files, recursively, so if you do it e.g. in $HOME, it's going to expand to quite a few arguments.

Also, #4579 improved glob performance quite a bit, so this should be much faster in 3.0.

>The only thing that helps in this case is closing the shell window.

Have you tried pressing ctrl-c?

**Comment by sabinem** [comment]
@faho : yes I did, that moved the cursor one space to the right, but the window remained frozen. Keys did not work in it any more.
