### ISSUE TITLE
Commas in process output are used as separators in brace expansion

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5048]
_I originally thought that [this bug](https://github.com/fish-shell/fish-shell/commit/35a7e1ef0eb9892c6ec73a7f3fee4d3f6ee9580b#r29369994) affected only fish 3.0 with [the changes to brace expansion](https://github.com/fish-shell/fish-shell/commit/d385248cc8533d7895a80d35e36fbcd1ef7c8f54) that imbued it with significantly more functionality and flexibility, but it turns out that even fish 2.7.1 is affected by this bug._

```fish
~> set -l tokens "foo,bar"
~> printf "'%s' " {$tokens}
'foo,bar'
~> printf "'%s' " {(echo $tokens)}
'foo' 'bar'
```

The output of a process should never be evaluated in this fashion, as this poses a major security risk.

**Comment by faho** [comment]
>as this poses a major security risk.

I would actually dispute that characterization - the output is not "evaluated" as _code_. It's "parsed" as a certain form of expression.

You can't use this to `rm` anything or `cat` anything else. There's really no way for anyone malicious to abuse this.

So I'd merely call it a bug.

**Comment by mqudsi** [comment]
It's not arbitrary code execution, but it it _is_ a vulnerability. Imagine privileged code that executes some command based off of usernames, perhaps something like a script that changes a user's password. It's pretty much along the lines of classical SQL injection vulnerabilities due to lack of argument escaping.

Let's say there's are sensitive resources located on a server that can only be accessed by the user and shared resources that can be accessed by anyone. Charlie wants to gain access to Alice's file and finds somewhere where the sysadmin unwittingly wrote the following code, assuming it to be safe:

```fish
for file in {(get-username), shared}.txt
    echo $file:
    cat $file
end
```

By creating an account with the name `bob,alice` in the system, Charlie gets access to `alice.txt` because `{(get-username), shared}.txt` now evaluates to `[bob.txt, alice.txt, shared.txt]` instead of `[bob,alice.txt shared.txt]`.

Security. Fun stuff.

**Comment by faho** [comment]
>By creating an account with the name bob,alice in the system

If Charlie can create accounts, then why not create alice directly?

**Comment by mqudsi** [comment]
> If Charlie can create accounts, then why not create alice directly?

Because `alice` is already taken by Alice.

**Comment by anordal** [comment]
How is this not just yet another way to split a string into an array? If that's what the privileged code needs to do – fine!

I don't get why the privileged code would be asking for trouble by doing this and then not expecting it to happen.

**Comment by anordal** [comment]
If this was nothing more than yet another way to split a string into an array, then it wouldn't be a security issue.

The crux of the point is that you don't expect it to happen.

```fish
printf '%s\n' rm -f /home/{(echo alice,bob),charlie}
```

Expected:

```
rm
-f
/home/alice,bob
/home/charlie
```

Actual:

```
rm
-f
/home/alice
/home/bob
/home/charlie
```

**Comment by ridiculousfish** [comment]
This is a surprising behavior but it's not a security issue. Someone might hypothetically expect different behavior and introduce a vulnerability, but that's true for any surprising behavior.

We should fix this, but it doesn't have to go into fish 3.0. Moving the milestone and retitling ("unsafe evaluation" makes it sound like shellshock or something)
