### ISSUE TITLE
fish shell hangs on startup

### ISSUE THREAD

**Issue by ashish01** [fish-shell/fish-shell#5049]
fish, version 2.7.1
OS, CentOS

My fish shell just hangs on startup. strace -p prints this

```
select(12, [6 11], NULL, NULL, {0, 10000}) = 0 (Timeout)
select(12, [6 11], NULL, NULL, {0, 10000}) = 0 (Timeout)
select(12, [6 11], NULL, NULL, {0, 10000}) = 0 (Timeout)
select(12, [6 11], NULL, NULL, {0, 10000}) = 0 (Timeout)
select(12, [6 11], NULL, NULL, {0, 10000}) = 0 (Timeout)
select(12, [6 11], NULL, NULL, {0, 10000}) = 0 (Timeout)
select(12, [6 11], NULL, NULL, {0, 10000}) = 0 (Timeout)
select(12, [6 11], NULL, NULL, {0, 10000}) = 0 (Timeout)
select(12, [6 11], NULL, NULL, {0, 10000}) = 0 (Timeout)
select(12, [6 11], NULL, NULL, {0, 10000}) = 0 (Timeout)
select(12, [6 11], NULL, NULL, {0, 10000}) = 0 (Timeout)
select(12, [6 11], NULL, NULL, {0, 10000}) = 0 (Timeout)
select(12, [6 11], NULL, NULL, {0, 10000}) = 0 (Timeout)
select(12, [6 11], NULL, NULL, {0, 10000}) = 0 (Timeout)
select(12, [6 11], NULL, NULL, {0, 10000}) = 0 (Timeout)
select(12, [6 11], NULL, NULL, {0, 10000}) = 0 (Timeout)
select(12, [6 11], NULL, NULL, {0, 10000}) = 0 (Timeout)
select(12, [6 11], NULL, NULL, {0, 10000}) = 0 (Timeout)
```

**Comment by faho** [comment]
How are you running fish? On a desktop in an xterm? Via ssh? In cron?

**Comment by ashish01** [comment]
I am running it as mosh -> bash -> tmux -> bash -> fish

**Comment by faho** [comment]
Please try dropping some of those steps to see if that makes the issue go away. Maybe just ssh -> bash -> fish for a start?

**Comment by zanchey** [comment]
Can you provide the whole output of `strace fish`?

**Comment by ashish01** [comment]
Rescuing the hops do not help. strace is printing this out in an endless loop.

**Comment by krader1961** [comment]
> Reducing the hops do not help. strace is printing this out in an endless loop.

Seeing the syscalls that lead up to the endless loop is likely to provide insights. For example, what are the two file descriptors, 6 and 11, open on that are being selected for input? Of course, the output of `lsof` would also tell us that but seeing the other syscalls may provide important context.

**Comment by mqudsi** [comment]
You can run `fish -d3` instead to get debug output.

**Comment by ridiculousfish** [comment]
Try also running fish with HOME set to a temp directory. e.g. from bash `HOME=$(mktemp -d) fish`. Does that work? If so this is due to some local configuration.

**Comment by ashish01** [comment]
Hi Guys

I have come to depend on fish shell a lot and at this point my history files knows more than me :)

So to unblock myself I made a backup of my history file, then deleted everything fish related and reinstalled it from scratch and then restored my history file. Now everything works fine. I am sorry I couldn't be much help in getting to root of this issue.
