### ISSUE TITLE
Time command doesn't seem to work

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5050]
fish 2.7.1

When I type "time ls -la" it always shows 00s

In bash it works.

What am I doing wrong?

**Comment by krader1961** [comment]
In bash `time` is a keyword and builtin. In fish it has no special meaning and the first external command of that name found in `PATH` is used.

**Comment by krader1961** [comment]
In fish run `type time` to see which program it is using to time the command.

**Comment by BarbzYHOOL** [comment]
It's `/usr/bin/time` but what do you suggest? that this program doesn't work or doesn't exist?

**Comment by krader1961** [comment]
> It's /usr/bin/time but what do you suggest? that this program doesn't work or doesn't exist?

Obviously it exists and works in as much as it runs the command handed to it and reports, whether accurately or not, how long the command took to run. You didn't provide enough information but I'll take a stab at an answer. The bash `time` builtin has a resolution of 1 millisecond. The */usr/bin/time* command has a resolution of 10 milliseconds. So if the command takes more than 1 millisecond but less than ten you'll see a non-zero value in bash and zero for the external command.

In bash compare `time ls` with `/usr/bin/time ls`.

**Comment by krader1961** [comment]
Try running a command that takes longer; e.g., `time sleep 1.5`.

**Comment by BarbzYHOOL** [comment]
Ok, you nailed it.

Can I make it show time < 10 milliseconds?

**Comment by krader1961** [comment]
> Can I make it show time < 10 milliseconds?

Probably not. Check the documentation for your system; e.g., `man time`. Fish has no control over it.

**Comment by BarbzYHOOL** [comment]
yeah, there is nothing in the doc

thank you anyway!
