### ISSUE TITLE
Syntax error produced 0 exit status

### ISSUE THREAD

**Issue by sabinem** [fish-shell/fish-shell#5052]
Shouldn't syntax errors produce an exit code >0?

I tried the following:
```
>|
fish: Expected a command, but instead found a pipe
>echo $status
0
```
(fish, version: 2.7.1-1246-geca4273f-dirty)

In `bash` I got instead:
```
>|
bash: syntax error near unexpected token `|'
>echo $?
258
```

To me it seems that wrong syntax should change the exit code to some value that is not 0, so it can be recognized that the command was not executed.

**Comment by kartoffelsup** [comment]
I might be totally missing something, but the exit status can be retrieved via the $status variable

**Comment by sabinem** [comment]
@kartoffelsup: sorry, I messed it up when I made that post: I just corrected it: 

`$status` is often 0 after syntax errors such as an empty pipe, even though `fish` complains about it and marks it as a syntax error.

**Comment by faho** [comment]
This doesn't actually produce a _0_ exit status. Instead, it does not _alter_ $status, because nothing is executed.

When you do this interactively, you'll notice that the commandline remains filled after you tried to execute it.

When you do it non-interactively (e.g. in a file that you then execute with `fish /path/to/file`), you'll see that it does nothing but print the error. E.g.:

```fish
echo before function definition
function with_error
    echo $(echo banana)
end
echo after

echo before call
with_error
echo after call
```

put it into test.fish, call `fish test.fish`, and find:

```
test.fish (line 3): $(...) is not supported. In fish, please use '(echo)'.
    echo $(echo banana)
         ^
<W> fish: Error while reading file test.fish
```

I feel like this is the correct thing to do - you don't want to run different code based on syntax errors, you want to figure out you have syntax errors and then correct them.

**Comment by sabinem** [comment]
@faho: thanks for explaining this to me. I could see how the commandline remained filled, you are right on this and it is probably just a matter of taste then. 

But, there are just 3 things to consider here in my opinion:
1. I feel the difference is not big between false syntax and unknown command: but the behaviour is: when the command can not be found such as `>some-bogus-command` the shell sets `$status`to a value `>0`,  and gives me a new prompt, even though also in that case the command was not executed.
2. All other shells, that I tested (`bash`, `zsh`, `tcsh`, ...) behave for syntax error in that way that they set the status `$?` and give me a new prompt.
3. I found it annoying, if I type a long command with a syntax error and cannot get a new prompt unless I correct the command or delete all I wrote.

So I do not think this must be fixed, but it is worth thinking about, if `fish` really wants to depart from other shells in this regard.

**Comment by faho** [comment]
>I found it annoying, if I type a long command with a syntax error and cannot get a new prompt unless I correct the command or delete all I wrote.

That's when you press ctrl-c.

The reason we're keeping it is that your error might just be a typo, in which case it's much nicer to correct that one bit than typing all of it anew.

**Comment by sabinem** [comment]
@faho: Okay, then that is settled. 

Do you think this should be added to the documentation? Then I would opt to do that. What do you think?

**Comment by faho** [comment]
>Do you think this should be added to the documentation?

I don't think it needs to, no. But if you do decide differently, feel free to add it!
