### ISSUE TITLE
Support for GoLang native completion

### ISSUE THREAD

**Issue by druchoo** [fish-shell/fish-shell#5056]
Is [GoLang native completion](https://godoc.org/github.com/jessevdk/go-flags#hdr-Completion) supported?

**Comment by faho** [comment]
That seems like it would work with  something like

```fish
complete -c somecommand -a '(set -lx GO_FLAGS_COMPLETION 1; set -l args (commandline -opc; commandline -ct); set -e args[1]; somecommand $args)'
```

There's no specific support required, but it also shouldn't be done automatically, because

>it is up to the user to make sure there are no negative side effects (for example from init functions).

If you know of any tool that actually uses this, we can test it.

**Comment by druchoo** [comment]
@faho ,

[Coucourse fly CLI](https://github.com/concourse/fly) supports this feature. Your example seems to work. I added `-f` argument to `complete` though as it seems to make sense in this case.

**Comment by faho** [comment]
>Your example seems to work.

Okay, nice to know!

I'm closing this then because the question has been answered.
