### ISSUE TITLE
command substitution in strings

### ISSUE THREAD

**Issue by sabinem** [fish-shell/fish-shell#5061]
I just noticed that command substitution in strings does work in other shells, but not in fish, I want to discuss this as an possible enhancement, since I feel it improves user friendlyness:

In `bash` and `zsh` you can do:
```
> echo "I am in $(pwd)"
I am in /Users/sabinemaennel
```

In fish you get instead: (my fish version is 2.7.1-1246-geca4273f-dirty)
```
> echo "I am in $(pwd)"
fish: $(...) is not supported. In fish, please use '(pwd)'.
echo "I am in $(pwd)"
              ^
```
What the message suggests does not work within string delimiters, in `fish` you would need instead to do this:
```
> echo "I am in $PWD"
I am in /Users/sabinemaennel
```

In this case using a special variable is indeed even better, but if there was no variable for another such command, you would have to make one, just because you cannot use command substitution within a string in `fish`. This is a inconvenience, as I see it.

Conclusion: This is by no means urgent, but it would be a nice enhancement in my opinion if we could use command substitution within string delimiters also in `fish`.

**Comment by ridiculousfish** [comment]
This is tracked in #159. Thanks for filing!
