### ISSUE TITLE
Support changing prompt when a command is run

### ISSUE THREAD

**Issue by xixixao** [fish-shell/fish-shell#5072]
I have time in my prompt. I would like to use this time to easily time any command. The problem is, the prompt reflects the time of when the last command (or "enter") finished. Could we add support for changing the prompt at the beginning of running a command?

**Comment by krader1961** [comment]
> I have time in my prompt. 

Me too.

> Could we add support for changing the prompt at the beginning of running a command?

Seems like a lot of added complexity for something that already has a couple of solutions. First, you can just press enter to get a fresh prompt with the current time before entering the command. Second, the time the command was run is stored in the command history. I have a `h` command that by default shows the twenty most recent commands I ran with the time each was run:

```
alias h builtin history search -R -20 --show-time="%a %m-%d %R  "
```

Here are the last few lines from running `h` in one of my sessions:

```
Mon 06-25 10:30  git blame src/cmd/ksh93/sh/args.c
Mon 06-25 10:30  vim src/cmd/ksh93/sh/args.c
Mon 06-25 10:33  git commit -a
Mon 06-25 10:34  gitvim
Mon 06-25 10:36  git commit --amend -a
Mon 06-25 11:07  bin/lint all >/tmp/x
```

**Comment by xixixao** [comment]
@krader1961 that's awesome, thanks! Don't have -R, guess I'm on an old version. Looks like it doesn't store the time the command finished, but I guess I have that in the prompt so I could infer the duration. What I'm really looking for I guess is a command that just tells me how long the previous command ran (`time` obviously doesn't work, as most interesting commands that I want the duration of are not easily reproducible).

**Comment by xixixao** [comment]
Ok, so `echo $CMD_DURATION` is all I needed. AMAZING! Thanks @krader1961 !
