### ISSUE TITLE
Autocomplete (annoyingly) greedily autocompletes multiple folders when each folder only contains one folder

### ISSUE THREAD

**Issue by rben01** [fish-shell/fish-shell#5078]
Info:

```
$ fish --version
fish, version 2.7.1
```

Operating system: macOS
Terminal: Terminal.app

Running without third party customizations did not fix the issue.

**The issue**
Say you have the following folder hierarchy: `~/organisms/animals/mammals/cats` (`mkdir -p ~/organisms/animals/mammals/cats` will create this for you) where each folder only contains a single folder (`organisms` only contains `animals`, `animals` only contains `mammals`, `mammals` only contains `cats`). If you `cd ~` and then type `cd org <TAB>`, this will greedily autocomplete all the way to `cd organisms/animals/mammals/cats`. I suppose that the logic here is that this is unambiguously the longest path that can be completed. However, many times I don't want the longest path -- I just want to complete the first directory so that I can work with it. Or I want the first two directories completed, etc. It's annoying to have the full longest path completed and then have to delete from the completed path a bunch of extraneous items (`mammals` and `cats`, say) that I never wanted in the first place.

**Comment by faho** [comment]
Already fixed in #4402, to be included in the next release.
