### ISSUE TITLE
fish only parses argument once in fish shell script

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#5079]
fish, version 2.7.1

I'm not sure the title is correct. Here is my problem.

Since built-in `watch` command `/usr/bin/watch` cannot accept aliases or defined functions in config.fish, so I decided to define my own `watch` command

    function watch1 -d 'wrap default watch to support aliases and defined functions'
        while test 1
            date; eval $argv
            sleep 1; echo
        end
    end

so I use this function command `watch1` to execute a command in while loop as you can see.

and I defined another alias in config.fish

    alias ll 'ls -lh'

so I use 

    watch1 ll ~/dir/*

to list files/directories in `~/dir` repeatedly.

But if I put new files into the `~/dir/` after I run `watch1 ll ~/dir/*` command, this command cannot recognize new files, it can only recognize all the files when I execute the command.

so my question is how to make the wildcard in `~/dir/*` re-parsed in fish shell script?

**Comment by faho** [comment]
>so my question is how to make the wildcard in ~/dir/* re-parsed in fish shell script?

Quote it. Otherwise it'll be expanded before being passed to `watch1`, so that will never see the wildcard.

```fish
watch1 ll '~/dir/*'
```

**Comment by c02y** [comment]
Thanks, it works for both `watch1` and `watch` in command line.

But if I typed `watch ll ~/dir/*` without single quote, how may I change the `function watch1` to make it work? I tried to change `eval $argv` to `eval '$argv'` or `eval "$argv"`, neither of them work.

`eval '$argv'`: it will print error message saying 
    (line 1): Variables may not be used as commands. In fish, please define a function or use 'eval $argv'.
begin; $argv

`eval "$argv"`: it doesn't work as expected.

**Comment by faho** [comment]
>But if I typed watch ll ~/dir/* without single quote, how may I change the function watch1 to make it work?

You can't. Like I said, the function never sees the wildcard!

Whatever the function does, if you don't quote the arguments, it will get the expanded version - e.g. `/home/c02y/dir/somefile` and `/home/c02y/dir/someotherfile`. There's no more `*` there then!

That's a fundamental part of fish (and UNIX-style shell scripting in general), and there's no way around it.

Quote the argument here, like you'd quote the argument everywhere else. That way you have to learn that one thing, as opposed to one thing for some commands and another for others.

**Comment by c02y** [comment]
OK, thanks.
