### ISSUE TITLE
wcwidth9 license incompatible

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#5081]
wcwidth9's licensing is [a bit weird](https://github.com/joshuarubin/wcwidth9/issues/1), but it's probably at least in part Apache v2, which the FSF considers to be incompatible with the GPLv2, which is fish's license (c.f. https://www.apache.org/licenses/GPL-compatibility.html).

So this needs to be hashed out before we release it, which would involve:

- Removing wcwidth9 (and finding an alternative)

or

- Getting upstream to change wcwidth9's license, which would unfortunately require a bunch of parties to agree

CC @zanchey.

**Comment by ridiculousfish** [comment]
Introducing [widecharwidth](https://github.com/ridiculousfish/widecharwidth), in the public domain.
