### ISSUE TITLE
Another Mapping for the Previous Ctrl-C Behavior

### ISSUE THREAD

**Issue by trisys3** [fish-shell/fish-shell#5082]
Feature request:

Could we get another key binding for the original Ctrl-C behavior, where it blanked out the line but didn't start another line? I liked the old behavior, and I know there is an easy way to add it back. Issue #3561 suggests to add to or create the `fish_user_key_bindings` function, e.g.:

  function fish_user_key_bindings
    # make Ctrl-c clear the line like it used to
    bind \cc 'commandline ""'
  end

However, that means you don't get the new behavior anymore. I imagine that new behavior was added for a reason, and it is useful to know what the previous line was.

With a new binding, we get both behaviors when we want them.

Pros:
Get both bindings when we want them, without adding yet another key binding or introducing some kind of switching behavior.

Cons:
Extra key binding for the key binding map. I'm not sure how many bindings there currently are, but I can't imagine there are too many to add just one more.
Extra maintenance?

By the way, why was the behavior changed in the first place? The original behavior was fine for most cases, in my opinion. Was it for compatibility with `bash`?

Finally, the current behavior when clearing is kind of ugly, to be honest. I guess that extra `^c` is useful, but it's another color, at least on my terminal. Plus, it could be at the end of the line or something. Sorry, I'm nitpicking, it's fine, plus that's a whole other feature request that's not relevant here.

**Comment by faho** [comment]
If you want both, bind them to different keys. 

That code also works if you substitute `\cg` for `\cc`.

>By the way, why was the behavior changed in the first place?

The idea was that you'd still see what you pressed.

There really is no need to bind both by default, this is easily left up to the user to customize.

**Comment by trisys3** [comment]
I know I could just add another binding. I thought it might be nice for it to be a built-in binding, for discoverability etc., but I figured it might be too much of a maintenance cost. Thanks for answering, at least.

**Comment by trisys3** [comment]
OK, then, I'll just close the issue. Sorry for the noise.
