### ISSUE TITLE
Git tab path autocompletion problem

### ISSUE THREAD

**Issue by LandonSchropp** [fish-shell/fish-shell#5083]
Fish version: 2.7.1
OS: macOS 10.13.5

Let's say I have the following directory structure:

```
example/
└── hellos
    ├── hello.txt
    └── hola.txt
```

When I type `ls ex` and hit tab, it autocompletes to `ls example`. The second tab gets me `ls example/hellos`. The third gives me `ls example/hellos/h` and the fourth lets me tab through the available options. All of this seems perfectly intuitive.

However, if I try typing `git add ex` and hit tab, it immediately autocompletes to `git add example/hellos/h`. This is annoying because I often want to hit enter and add the directory containing both files, but Git will exit with an error in this scenario.

**Comment by faho** [comment]
I've now committed a simple fix that just offers the parent directory to any file. I did not offer all the parent directories, e.g. if "share/completions/git.fish" changed, this offers "share/completions", and not "share/" because I believe that to be noise in most cases.

**Comment by LandonSchropp** [comment]
Thank you @faho! That's exactly what I was looking for. 😃
