### ISSUE TITLE
 [I] in promt apeared and won't be deleted. (it's green)

### ISSUE THREAD

**Issue by Drunkenpanda2000** [fish-shell/fish-shell#5098]
Version:2.7.1
OS:Manjaro

I have no idea why but after installing some OMF themes a [I] appeared in my prompt and i am unable to make it dissapear. uninstalling Oh-My-Fish and deleting my fish_prompt.fish@ file did not fix the issue.

Running the following command fixes the issue.

  sh -c 'env HOME=$(mktemp -d) fish'

But ofc only for that one session.
Note at this moment i should not have anny addons installed.

**Comment by faho** [comment]
This is the mode-prompt. It displays which vi-mode you are in, which happens because one of your themes activated vi-style key bindings.

To disable it, replace the `fish_mode_prompt` function with something else, like

```fish
function fish_mode_prompt; end
```

**Comment by ridiculousfish** [comment]
what faho said: if you want to keep vi key bindings but hide the mode indicator you can redefine `fish_mode_prompt`, and if you want to go back to emacs style bindings run `fish_default_key_bindings`. Closing, please reopen if this doesn't answer your question. Thanks for filing!
