### ISSUE TITLE
\uF400, \UF401, etc are treated as wildcard characters

### ISSUE THREAD

**Issue by kballard** [fish-shell/fish-shell#51]
If I try to run `echo \uF400` this is treated identically to `echo ?`. Similarly `\uF401` is treated as `*`. `\uF402` is treated as some other character but I have no idea what; trying `echo \uF402` hangs until I type `^C`, at which point it says `fish: Could not expand string '\uF402'`.

**Comment by krader1961** [comment]
This specific issue no longer occurs due to my changes with respect to how reserved chars are handled. There is more work to be done but this particular case is no longer a problem.
