### ISSUE TITLE
'fish: Runtime path not available' issue on WSL Ubuntu18.04 on Win10 when '/tmp' point or mount NTFS path

### ISSUE THREAD

**Issue by cjun714** [fish-shell/fish-shell#5115]
**Fish version:**
``` shell
> fish --version
fish, version 2.7.1
> uname -a`
Linux DESKTOP-1700X 4.4.0-17134-Microsoft #137-Microsoft Thu Jun 14 18:46:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
> echo $TERM
xterm-256color
```

**Environment:**
WSL Ubuntu18.04 + Windows10 1803
Terminal: wsltty 1.9.0.2
fish is installed through "apt install"

**How to reproduce issue:**
``` shell
> sudo ln -s /<other_NTFS_path> /tmp
> fish
Welcome to fish, the friendly interactive shell
cjun@DESKTOP-1700X ~> <E> fish: Runtime path not available.
<E> fish: Try deleting the directory /tmp/fish.John and restarting fish.
```

I have tried setting XDG_RUNTIME_DIR [#1887](https://github.com/fish-shell/fish-shell/issues/1887#issuecomment-70234859), but no help.

If /tmp point(or mount) to any NTFS path, issue will happen.

Please help, thanks a lot!

**Comment by mqudsi** [comment]
_Note that https://github.com/neovim/neovim/pull/7330 affects fish as well, thanks to my relegating wsl detection to a zero-cost buildtime value_

**Comment by mqudsi** [comment]
What did you try setting `XDG_RUNTIME_PATH` to? The following should work:

```fish
mkdir -p $HOME/.tmp
env XDG_RUNTIME_PATH=$HOME/.tmp fish
```

**Comment by cjun714** [comment]
@mqudsi very sorry for the late response.

I haven't use WSL these days, and I test it again today , this issue never happen now, I mounted /tmp to a NTFS path and fish never raise any error.
Perhaps WSL update resolved this issue, because I didn't update fish or any other apt packages in these days, every thing is ok now.
Thanks  a lot for  your care and support!

**Comment by mqudsi** [comment]
Thanks for the info.
