### ISSUE TITLE
docs/css: code snippet styling prevents linebreaks on Firefox

### ISSUE THREAD

**Issue by jnns** [fish-shell/fish-shell#5116]
The combination of `body.overflow: hidden` and

```
tt, code, pre, .fish {
    […]
    white-space: pre-wrap;
    word-wrap: break-word;
}
``` 

leads to a lot of text being cut off in the documentation in Firefox. Only a fraction of it is readable without switching to another browser or disabling the relevant CSS directives. 

I experience this with Firefox 63 and this is probably a bug in Firefox. The culprit being `word-wrap: break-word`, I wonder [why it is there in the first place](
https://github.com/fish-shell/fish-shell/blob/eb3541be8608df17d69f090527769dae79ba1d4f/doc_src/user_doc.css#L155)?

**Comment by jnns** [comment]
I just tested it again with Firefox 63.0a1 (2018-07-29) and the issue remains. It does not occur on every page of the docs, but definitely on every page when the viewport is resized manually to something along the lines of 700px in width. 

With a small browser window, one can toggle `.fish_right_bar { margin-left: 25rem; }` to see that word-wrap breaks only when the margin is applied.

**Comment by ridiculousfish** [comment]
Thanks. Can you please provide steps to reproduce? For example is this with the built documentation from master, or something visible on a site? What is a URL that repros this?

**Comment by mqudsi** [comment]
It's visible on the site.

![image](https://user-images.githubusercontent.com/606923/46696538-03af6180-cbd8-11e8-9a58-7417c8606880.png)

Notice that the horizontal scrollbar is gone (and attempting to scroll/swipe sideways does not work).

```css
body { overflow: hidden; }
```

just needs to be changed to 
```css
body { overflow-x: scroll; }
```

The existing CSS preserves the reflow for screens wider than 700px, but under 700px users can manually scroll to the side to see the cut-off content.

**Comment by ridiculousfish** [comment]
@mqudsi what link, and browser version did you use? What is the horizontal scrollbar you're referring to?  I still don't know how to reproduce this.

**Comment by jnns** [comment]
> Thanks. Can you please provide steps to reproduce? For example is this with the built documentation from master, or something visible on a site? What is a URL that repros this?

It occured on every page in the docs that had one of the following elements in it: `tt`, `pre`, `code`, `.fish` and it showed on the documentation on fishshell.com/docs. 

But now that I'm on Firefox 64.0a1 (2018-10-10) I can not reproduce it anymore.

**Comment by mqudsi** [comment]
@ridiculousfish Firefox 63 browsing https://fishshell.com/docs/current/commands.html

There are no special steps, just keep narrowing the width of the browser window. The content reflow, reflows, reflows, reflows, then cuts off.

The horizontal scroll bar in question is the scrollbar at the bottom of the viewport that lets you scroll sideways. Here's what that same screenshot above looks like with my css fix implemented:

![image](https://user-images.githubusercontent.com/606923/46909724-b3e4d900-cefc-11e8-94f7-f0ba93ab9945.png)

As you can see, a scrollbar has appeared on the bottom and I can scroll sideways to bring text that would have been cut off into view:

![image](https://user-images.githubusercontent.com/606923/46909732-bf380480-cefc-11e8-90dc-c884699545ef.png)

**Comment by mqudsi** [comment]
Yes, that is the bug.

**Comment by mqudsi** [comment]
@ridiculousfish the problem is that on mobile the default size is already cropped without scroll/reflow:

![image](https://user-images.githubusercontent.com/606923/46991756-d6c5e780-d0cc-11e8-8808-0388f64bb093.png)

**Comment by zanchey** [comment]
This no longer happens with Sphinx.
