### ISSUE TITLE
Line wrapping results in blank first line

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5118]
Line wrapping seems to be broken for the first line of shell text, upon wrap the entire contents are shifted to a new line rather than at the end of the prompt.

I haven't had a chance to check it against 2.7.1 but I'm pretty sure this is a regression; this behavior feels different from what I'm used to.

This is probably best illustrated with a recording: https://asciinema.org/a/EoICnLy8zF9VRefsAf1LHJ1Yk

**Comment by ridiculousfish** [comment]
Can you try git bisecting it?

**Comment by faho** [comment]
@mqudsi: Ping?

Does this still happen to you? I don't think anybody else has been able to reproduce it.

**Comment by mqudsi** [comment]
It still happens, and on multiple machines too. I need to get around to bisecting it, I didn't want to do that on my slower machine given configure and build times.

**Comment by mqudsi** [comment]
OK, this drove me nuts trying to pin it down! One minute it would bisect to something that makes no sense, such as @zanchey updating the changelog and the next it would reproduce with fish 2.0! To make matters worse, I tried on my MacBook thinking it could be a conemu glitch (though I knew that couldn't be the case, as it reproduces in the asciinema in my initial report, which means it's more or less interpretation of the shell output) and was able to reproduce it there, too.

It turns out this only happens if `$COLUMNS` is less than 77. At 76 columns wide or less, upon reaching the end of the terminal display the entire contents of the line are shifted down to the next row.

**Comment by mqudsi** [comment]
I imagine this is the code responsible: https://github.com/fish-shell/fish-shell/blob/master/src/screen.cpp#L988

**Comment by faho** [comment]
That actually seems like it's intended to work that way. Would you like that to be changed, and if so how?

**Comment by mqudsi** [comment]
I don't think there's a need for that extra functionality at all? Given that this behavior was foreign to all of us and it only kicks in when the left prompt takes up 33% of the terminal width and a subsequent argument is entered that would softwrap, I think it's unnecessary and just makes the behavior of the shell confusing/unexpected.

Content either fits on the line or it doesn't. If the left prompt wants an entire line for itself, so be it. But for text that fit (and was followed by whitespace) to be wrapped around to the next line just because I entered another argument afterwards.. the behavior just doesn't add up.

How do you guys feel about that?

**Comment by faho** [comment]
Have a look at #904, in which people asked for the prompt to either wrap or truncate if the terminal is too small.

Sounds like this is supposed to essentially do that, but doesn't do a good job of it.

**Comment by mqudsi** [comment]
I think that is different functionality because this doesn’t kick in until the command line reaches the terminal edge (and notably doesn’t affect the prompt at all, only the text). But thanks for linking that issue, I do think any resolution for this should take that into account.

**Comment by faho** [comment]
Okay, this doesn't have to be in 3.0.

**Comment by floam** [comment]
Hm. I kinda like the current behavior - it's easier to read a long line if it's not broken up into two lines with a large prompt.

**Comment by mqudsi** [comment]
The entire premise is weird, though. "The prompt is too narrow.. instead of trying to smush things up to save space, let's waste space instead!"

But all that aside, the problem is that it moves text that it has no business moving. The text is already written, it's disconcerting to see it all move around the screen to where you're not expecting it. The UX for reaching the end of a line is well-understood and this breaks with how fish handles this in all other cases. Look at how long it took us to figure out what was even going on - it's such a hard break (no pun intended) from the prevalent behavior everywhere else in fish when it comes to line wrapping. It's jarring and it's inconsistent (e.g. why should this behavior only happen at 77 columns and not 78 columns?).

**Comment by floam** [comment]
I think the premise works a little better if you frame it as "the prompt has gotten too long" versus "the terminal window is too narrow" - it's not based on the terminal window being under a certain size, depending on your prompt length, the cutoff could be over 80. The prompt can get really long if you're deep in some directory, every command you enter get word-wrapped early is kinda jarring.

**Comment by floam** [comment]
It's not specifically 78 columns, but 33%. If your prompt is wider than 33% of the terminal width then it will start this wrapping behavior. Do you think you would be helped if we adjusted that? I mean, do you think that if there are only for example 10 characters left next to the prompt in the window, it's definitely nicer to wrap like this? At that length you wouldn't even be able to read many command names easily. So what should the cutoff be?

**Comment by faho** [comment]
Okay, I just removed the functionality since it's more confusing than helpful.
