### ISSUE TITLE
[Feature request] Custom callback after "Unknown command".

### ISSUE THREAD

**Issue by JanKaifer** [fish-shell/fish-shell#5119]
Hi,
It's super common that I find an awesome command (it was nload this time) and I try to use it. Sometimes it works (It's installed as a dependency or by me a long time ago) but sometimes it doesn't' and then I almost always try to install package with the name of the command. And that's the step I would like to automate.
Is there any recommended way to achieve this in fish?
Thx.

**Comment by moverest** [comment]
You can create a function that is triggered by the `fish_command_not_found` event like so:
```
function my_own_cmd_not_found_handler --on-event fish_command_not_found
    echo The command: $argv[1]
end
```

Then you pass the command name to whatever tool that help you find the package name. Since I don't know your OS, I can't help you with the specifics.

**Comment by ridiculousfish** [comment]
Thanks moverest! Closing since no response.
