### ISSUE TITLE
complete's "--require-parameter"/"-r" does not take grouped options into account

### ISSUE THREAD

**Issue by jski3** [fish-shell/fish-shell#5127]
I’m using 2.7.1 fish on CentOS 7.2 1511.

I downloaded it from the fish shell website as source and built it. No modifications post installation.

I was in the fish shell (2.7.1) and tried to expand a file name:

$ rpm -qf /usr/lib64/libnc

I double tabbed at this point and fully expecting to see:

...lib64/libncurses.so.5

as an option.

Nope, nothing. Even though libncurses.so.5 is certainly there.

**Comment by moverest** [comment]
There is the same bug with `pacman -Qo` as well. It works as intended if you type `rpm -q -f`.

It seems like it doesn't take into account the `-r` option in:

```fish
complete $rpm_select -s f -l file -d 'Query package owning specified file' -r
```
https://github.com/fish-shell/fish-shell/blob/master/share/completions/rpm.fish#L79

 but uses
```fish
complete $rpm_select -a "(__fish_print_packages)"
```
https://github.com/fish-shell/fish-shell/blob/master/share/completions/rpm.fish#L77
to complete.

**Comment by mqudsi** [comment]
@faho I thought `complete` supported concatenation of multiple short commands, i.e. `-qf` is handled the same as `-q -f`?

**Comment by faho** [comment]
@mqudsi: Yeah, it's supposed to.

This appears to me like "-r" fails to check that somewhere.
