### ISSUE TITLE
Questions regarding the documention

### ISSUE THREAD

**Issue by sabinem** [fish-shell/fish-shell#5129]
fish, version 2.7.1-1246-geca4273f-dirty

Since I am working on an doumentation overhaul, see [issue 740](https://github.com/fish-shell/fish-shell/issues/740), I am checking everything, whether it works as documented.

In that regard questions come up. I want to open a new issue, just for my questions regarding the doumentation, if that is okay. 

## Special variables:

These two variables were not set in my shell: 

> - CMD_DURATION, the runtime of the last command in milliseconds.
> - FISH_VERSION, the version of the currently running fish
> - LC_ALL, LC_COLLATE, LC_CTYPE, LC_MESSAGES, LC_MONETARY, LC_NUMERIC and LC_TIME set the language option for the shell and subprograms. See the section Locale variables for more information.

So are they old? Or have they been replaced? I guess FISH_VERSION has been replaced by `version`? Can I delete these passages from the documentation?

I know `locale` shows settings for LC_ALL, etc, but the variables themselves do not seem to be set in the shell, just LANG is set.

Explanations are appreciated.

**Comment by faho** [comment]
I'm assuming this question has been answered.
