### ISSUE TITLE
What is the recommended way to prevent SIGINT propagation using Ctrl-C (SIGINT) from an interactive shell?

### ISSUE THREAD

**Issue by da99** [fish-shell/fish-shell#5139]
Let's say I am on an interactive shell. I run a process that starts a child process, and that starts another child process:

```
  $ my_first_process
        |- child_process
            |- inner_child
```
If I wanted to send a SIGINT to only the `my_first_process` (and not to the child_process or inner_child) when I hit Ctrl-C, what would be the recommended way? (Maybe putting the child_process in a different session group?)

Is there any documentation on how Fish handles and propagates the INT signal (via CTRL-C in an interactive shell)? Or does it follow some published standard?

**Comment by da99** [comment]
This question seems outside the scope of Fish. I think it's best to just close it.

**Comment by zanchey** [comment]
See https://stackoverflow.com/questions/20103521/prevent-control-c-from-sending-sigint-to-all-process-group-children and https://www.gnu.org/software/libc/manual/html_node/Signal-Characters.html#Signal-Characters:

> The INTR (interrupt) character raises a SIGINT signal for all processes in the foreground job associated with the terminal.

**Comment by da99** [comment]
@zanchey Thanks very much.
