### ISSUE TITLE
Improving vi mode support

### ISSUE THREAD

**Issue by matthewvilim** [fish-shell/fish-shell#5144]
I'm interested in improving vi support by implementing vi's full grammar (http://takac.github.io/2013/01/30/vim-grammar/) Notably missing right now are repetitions and text objects.

Naturally, this would involve adding additional state into the core. For example, parsing d2i" requires some logic to keep track of command state and can't be handled in a fish script alone.

Are you open to accepting a pull request for this or would you prefer to keep vi specific stuff out of the core at the expense of limited vi emulation?

**Comment by rickard-von-essen** [comment]
This IMHO would be great. Now it's hard to know what will work and what doesn't.

**Comment by faho** [comment]
>Are you open to accepting a pull request for this

Of course, provided it's reasonably clean!

See also [the vi-mode label](https://github.com/fish-shell/fish-shell/labels/vi-mode). Text objects in particular are tracked in #1842.

**Comment by faho** [comment]
Okay, closing this as nothing happened and all the enhancements are tracked elsewhere, e.g. #1842. Just "improve" isn't actionable.
