### ISSUE TITLE
I can't use the tab key

### ISSUE THREAD

**Issue by YuMuuu** [fish-shell/fish-shell#5146]
I use  completion. bad view error.

press tab
↓
fish: Unknown command 'expand:choose-next'

help me ...

**Comment by faho** [comment]
That is the output you would get if you bound tab to `expand:choose-next`, which is not a thing in fish itself.

It is, however, a thing in https://github.com/oh-my-fish/plugin-expand, so it looks like you didn't install or remove that one correctly.

**Comment by faho** [comment]
Assuming this has been answered.
