### ISSUE TITLE
fish's printf differs from bash's

### ISSUE THREAD

**Issue by favba** [fish-shell/fish-shell#5148]
fish, version 2.5.0

on fish:
```
fish~> printf %s "/home"
74883
```

bash:
```
bash-3.2$ printf %s "/home"
/home
```

Is this intended?

**Comment by faho** [comment]
This is just triggering job expansion - the `%s` is replaced with the PID of a process whose command starts with "s".

It's been removed in git master and won't be in 3.0. For fish before that, just quote everything that starts with `%` - `printf "%s" "/home"`.

**Comment by favba** [comment]
Thanks for the workaround!
