### ISSUE TITLE
feature request: add an option to determine ambiguous characters' width.

### ISSUE THREAD

**Issue by BurningLutz** [fish-shell/fish-shell#5149]
This option is important to Asian users because many fonts of Asian language treat and render ambiguous characters as double-width.

Just like iTerm's `Treat ambiguous-width characters as double-width` and vim's `ambiwidth`, problems caused by different treatment of ambiguous characters' width between different fonts may be resolved if such option is provided.

**Comment by ridiculousfish** [comment]
I added this as `fish_ambiguous_width`, it was easy. Thanks!
