### ISSUE TITLE
Traversal order of tokens in history has regressed

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#5150]
Caused by https://github.com/fish-shell/fish-shell/commit/e51e854d8d11c154a17d48ab781a1f05222829ff / https://github.com/fish-shell/fish-shell/issues/4795 (ping @ridiculousfish)

The traversal order of history tokens has ever so slightly changed/broken (i.e. `history-token-search-{forward,backward}`) since the above change was implemented.

**Prior/expected behaviour:**
```sh
$ echo foo bar baz
foo bar baz
# alt-.
$ baz
# alt-.
$ bar
# alt-.
$ foo
```

**Current/unexpected behaviour:**
```sh
$ echo foo bar baz
foo bar baz
# alt-.
$ echo
# alt-.
$ foo
# alt-.
$ bar
```

---

Would it be possible to reinstate the old traversal order? More often than not, whenever I press `alt-.`, it's to recall the _last_ argument of the previous command. This would also be consistent with bash.

**Comment by mqudsi** [comment]
Please try this in the latest `master`.
