### ISSUE TITLE
How to make fish as my default shell if I got no sudo permission (cannot edit /etc/shells file)

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#5152]
I just installed fishshell from the latest code of "git clone"

1. autoreconf --no-recursive
2. configure --prefix=$HOME/.local
3. make && make install

in the end, it says:

    To use fish as your login shell:
     * add the line '/home/user/.local/bin/fish' to the file '/etc/shells':
       echo '/home/user/.local/bin/fish' | sudo tee -a /etc/shells > /dev/null
     * run 'chsh -s /home/user/.local/bin/fish'

But I installed it in a linux server (Ubuntu 16.04.5 LTS, no gui) with multiple users, and I got no root permission, I cannot edit `/etc/shells` file

If I execute `chsh -s /home/user/.local/bin/fish` directly, it says:
    
    chsh: /home/user/.local/bin/fish is an invalid shell

Then how can I make fish as my login shell without editing `/etc/shells` file or any workaround?

BTW:
I installed old fish shell using `sudo apt` long time ago, so the old fish in /usr/bin/fish already exists in `/etc/shells`, and my default $SHELL currently is `/usr/bin/fish`, but recently the permission was changed by administrator, normal users got no sudo permission, so I installed the latest fish shell in my home directory and want my default $SHELL to `/home/user/.local/bin/fish`.

**Comment by faho** [comment]
>Then how can I make fish as my login shell without editing /etc/shells file or any workaround?

You don't. `chsh` won't do it without the shell being listed in /etc/shells, and other ways of editing that configuration also require root permissions. That's just the way it is.

What you _can_ do instead is to simply start fish in other ways - e.g. by setting your terminal to start it, or by adding something like

```bash
if [[ $- = *i* ]]; then
   exec fish
fi
```

to your ~/.bashrc or similar.

**Comment by c02y** [comment]
Since my current $SHELL is already fish (`/usr/bin/fish`), so config.fish will be loaded instead of .bashrc when login, so how can I make config.fish to load `~/.local/bin/fish`?

**Comment by esclerofilo** [comment]
I guess you could add
```
if status is-interactive; and test -z $LATEST_FISH
    set -x LATEST_FISH "yes"
    exec $HOME/.local/bin/fish
end
```
to your `~/.local/bin/fish`, or you could simply `chsh` to bash and then use faho's answer.

**Comment by c02y** [comment]
@esclerofilo Since I use fish most of time, but I have to switch to bash sometimes, so I cannot chsh to bash and cannot exec fish in .bashrc. 

I tried to add your snippet in config.fish, and it works. Thanks.

**Comment by faho** [comment]
You can put the code to start fish into one of the files bash reads only on login, like ~/.bash_login or ~/.bash_profile (though check that your bashrc does not source it).

Or you can detect that bash is a login shell with `shopt -q login_shell && echo 'Login shell' || echo 'Not login shell'`.

Or you can use a variable to automatically start fish.

Or you can simply start `fish` if you want it.
