### ISSUE TITLE
Possible to enable arm (aarch64) builds for other OSes as well?

### ISSUE THREAD

**Issue by iggy** [fish-shell/fish-shell#5154]
I'm specifically looking for Debian 9 which is built on the openSUSE build service. I looked around for a bit to see if I could find a definitive answer whether aarch64 was supported by OBS, but couldn't find anything.

Trying to pimp out my Samsung Chromebook Plus now that it got Linux support.

```
$ arch
aarch64
$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 9.5 (stretch)
Release:        9.5
Codename:       stretch
```

Related to: #5024 (ish)

**Comment by zanchey** [comment]
It is supported (https://build.opensuse.org/project/meta/Debian:9.0) - I'll try turning it on for nightlies and see how it goes, although 2.7.0 release builds use quite a different build system.

**Comment by zanchey** [comment]
Yes - built for both nightlies and 2.7.0 release.

With the more... exotic architectures, I'm not sure about turning them all on by default. OBS and PPAs are free resources and I don't want to overdo our use of them. I'm closing this for now but if anyone has any other opinions please speak up.
