### ISSUE TITLE
Create an option to prevent fish from shortening the prompt line.

### ISSUE THREAD

**Issue by lsevero** [fish-shell/fish-shell#5156]
I wanted to have an option to completely disable this behavior and always show the full prompt line no matter how big the line is and how small the screen width is.
That could be done by checking a environment variable or something similar in this line 
https://github.com/fish-shell/fish-shell/blob/27cd74e16c0842552defc9b26be0693e1f8d37c2/src/screen.cpp#L864

**Comment by zanchey** [comment]
This is tracked in #904, so I'll close this as a duplicate for now. Thanks.
