### ISSUE TITLE
Unhandled error: Unknown command 'screen'; -ls __fish_i_don_t_think_this_will_be_matched

### ISSUE THREAD

**Issue by KGOH** [fish-shell/fish-shell#5157]
When I write `screen` in terminal for the first time after opening it will yield this:
```puck at uranus in ~ 
↪ screen fish: Unknown command 'screen'
- (line 1): 
begin; screen -ls __fish_i_don_t_think_this_will_be_matched 
       ^
from sourcing file -
        called on line 60 of file /usr/share/fish/functions/eval.fish

in function “eval”
        called on line 2 of file /usr/share/fish/completions/screen.fish

in command substitution
        called on line 0 of file /usr/share/fish/completions/screen.fish

in function “__fish_detect_screen_socket_dir”
        called on line 50 of file /usr/share/fish/completions/screen.fish

from sourcing file /usr/share/fish/completions/screen.fish
        called on standard input

in command substitution
        called on standard input
```
I don't need to press enter or do something, error will raise when I just wrote `screen`

After installing `screen` package error is gone. I think you should add proper handling of case if `screen` not installed

P.S: I got this error while using tmux. Didn't tried without it, so I don't know if tmux has any effect on this, saying just in case

**Comment by faho** [comment]
Fixed by 4414d5c8885b5cd53c7ab42f70bd2824050907f0, which closed #4782. So I'm counting this as a duplicate.

Not that the screen completions are brilliant - they could use some work.
