### ISSUE TITLE
Cd previous dir in function/script

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5159]
fish 2.7

I want to go in the upper dir ".." then go back to the initial dir. It's for fish_prompt.

$OLDPWD not working, so I tried "cd $dirprev[-1]" in a script but it's not working as intended.

```
while test -n (cd .. ; git rev-parse --show-superproject-working-tree ; cd $dirprev[-1] ;)
  echo "PWD: $PWD"
  echo "dirprev: $dirprev[-1]"
  echo "pas submodule"
  sleep 6
end
```

I tried to add this in a function.
Basically it's always the same dirprev, it's like it's using the user's dirprev instead of the "script" dir prev.

Also tried to add this in a fish script (#!/usr/bin/fish) but then dirprev was always "/home/user".

Note: I suppose the `test -n (cd .. ; git rev-parse --show-superproject-working-tree ; cd $dirprev[-1] ;)` is not proper but I have not found any other way to check if a git submodule is inside another git submodule.

**Comment by BarbzYHOOL** [comment]
Ok, but I really can't make that thing work. How do I stop the while loop?

`git rev-parse --show-superproject-working-tree` returns empty if it's a super repo, but returns something if it's a submodule repo, so I made this basic dumb thing:

```
if test -z (git rev-parse --show-superproject-working-tree)
  echo "not submodule"
else if test -z (cd .. ; git rev-parse --show-superproject-working-tree )
  echo "sub-submodule"
else
  echo "submodule"
end
```

The second "if" covers if there is a "sub-submodule" but I would have liked to detect any depth of submodule (even if not very useful, just to have something well done).

So I thought "while" was the right idea but I'm not sure anymore

**Comment by krader1961** [comment]
I have no idea what you're trying to do. Specifically what is the distinction between "submodule" and "sub-submodule"? If you could explain what you're trying to achieve it would help.

**Comment by BarbzYHOOL** [comment]
sub-submodule would be like this

```
super repo
--------------/submodule
--------------/submodule/submodule
```

**Comment by zanchey** [comment]
It sounds like this is sorted, but if not please speak up.
