### ISSUE TITLE
Overwriting fish sessions

### ISSUE THREAD

**Issue by hritikgupta** [fish-shell/fish-shell#5164]
I am running fish, version 2.2.0 on Ubuntu 16.04. Skeptical if this is a bug : on switching to fish session from bash once, running `fish` command lets say, thrice, I have to exit the session four time to come back to bash. On the contrary, the current fish session should be overwritten. 
![screenshot from 2018-08-28 16-36-01](https://user-images.githubusercontent.com/24262284/44719552-47934f00-aae1-11e8-89ea-247b7cf3f4b0.png)

**Comment by zanchey** [comment]
This looks right to me - you've started four fish instances, so you need to exit each one in turn.

If you want to overwrite the current session, use `exec fish` instead.

I'll close this for now but if I have misunderstood, please speak up.
