### ISSUE TITLE
environment variables separator '\x1e' is not recognized by python

### ISSUE THREAD

**Issue by thuzhf** [fish-shell/fish-shell#5169]
fish version: 2.7.1
uname -a: Linux VM_155_10_centos 3.10.0-327.36.3.el7.x86_64 #1 SMP Mon Oct 24 16:09:20 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
echo $TERM: screen

How to reproduce the problem:
define a environment variable in fish using `set -lx a 1 2 3`, and in python, just use `import os; os.environ.get('a')` and you can see the environment variable is not separated by spaces or colons but by `\x1e` which is not recognized by python which probably can result in that the environment variable are unrecognizable (e.g., LD_LIBRARY_PATH will not work as expected if it has more than 1 directory).

Please see the following video for more details.
[![asciicast](https://asciinema.org/a/qSFg0QUoLA16s3mJxp9GrLDSa.png)](https://asciinema.org/a/qSFg0QUoLA16s3mJxp9GrLDSa)

In bash, the same program works fine. I think python doesn't recognize '\x1e' as the separator which leads to this problem. How can I solve this problem?

**Comment by ridiculousfish** [comment]
We're tracking rethinking env var separators in #436; feel free to weigh in there. Thanks for filing!
