### ISSUE TITLE
UTF-8 offests bug

### ISSUE THREAD

**Issue by FFY00** [fish-shell/fish-shell#5171]
This might be related to #1502 but it doesn't actually affect the right prompt.

I-m using tilix but I can reproduce in other terminals.

Some recordings:
![paste](https://i.imgur.com/38xhimq.gif)
(I pasted `test` from the clipboard)

![temp home](https://i.imgur.com/PH5prtZ.gif)
(I pasted `⯈` in a clean fish setup)

**Comment by ridiculousfish** [comment]
What version of fish are you using? Can you confirm the width that your terminal renders this character (0x2BC8) at? Can you check if this repros on master? There has been a big Unicode overhaul in master - see #2652.

**Comment by ridiculousfish** [comment]
Great, if you want to share what you did I'm sure future googling folks will appreciate it :)

**Comment by FFY00** [comment]
As I said, the selected locale wasn't genetated. Just ass it to `/etc/locale.gen` and run `locale-gen`.
