### ISSUE TITLE
fish is slow on sshfs + .git - over 30 sec

### ISSUE THREAD

**Issue by hrvoj3e** [fish-shell/fish-shell#5185]
fish is too slow when doing any operation (`cd` `ll` ...) in folder over sshfs which has a git repo.

When using `  sh -c 'env HOME=$(mktemp -d) fish'` it works normal.

I tried using [this](https://github.com/fish-shell/fish-shell/issues/3083#issue-157333480) fix **but no luck**.

Is this connected to this https://github.com/fish-shell/fish-shell/issues/3083 ?
Or this https://github.com/oh-my-fish/oh-my-fish/issues/624 ?

**Comment by faho** [comment]
First the obvious: It is entirely expected that git is a bit slow on sshfs, because sshfs is a bit slow. Git does a whole bunch of IO, and all that needs to go over the network with sshfs.

Then, if this:

```fish
function __fish_git_prompt
    set branch_name (git symbolic-ref HEAD 2>/dev/null)
    if test -n "$branch_name"
        echo " $branch_name" | sed 's!refs/heads/!!'
    end
end
```

is still slow for you, we can basically 100% chalk it up to git. I don't think there is anything that much faster than `symbolic-ref HEAD`. At that point, you'll have to disable the git prompt in that directory.

Use something like

```fish
# Where your prompt calls __fish_git_prompt:
if not string match -q '/path/to/repo/*' -- $PWD
    __fish_git_prompt
end
```

I would still like some profile data, so if you could upload the FILE generated by running `fish --profile FILE -c '__fish_git_prompt'`, that'd be nice.

**Comment by faho** [comment]
@hrvoj3e: Ping? Can you confirm it's git being slow?

**Comment by hrvoj3e** [comment]
@faho Sorry. Here is my [FILE](https://pastebin.com/dM4Qspen)

**Comment by faho** [comment]
That's 55ms for `git symbolic-ref HEAD`, 100ms for `git rev-parse` (which tells us if we're in a git repo, and some other advanced info, and 50ms for some miscellaneous `test -d` calls (to figure out if we're rebasing).

Which totals ~200ms for the slow function (and ~60ms for the fast one), which is a far cry from the 30s you initially stated. So I'm closing this as a duplicate of #3083, which itself is closed because, while 200ms is annoying, it's not really a deal breaker. Especially when you consider that the minimum is ~60ms.

**Comment by faho** [comment]
>Hm... It must be something else then on my end.

@hrvoj3e: Wait, so you still actually get the 30s wait?

Did you profile that git prompt in one of the affected directories? If not, please do that.

If you did, please profile your entire prompt. Something like `fish --profile FILE -c 'fish_prompt; type -q fish_right_prompt; and fish_right_prompt'`.

You can then check `sort -nk 2 FILE` (that "FILE" btw is just a filename, so you can put something else there if you want, you just have to be consistent) to quickly get at what is using the most time.

**Comment by hrvoj3e** [comment]
Wow - this is extreme ...

I am beginning to suspect `git status --porcelain`

```
1551	21309	> builtin source /usr/share/fish/config.fish
858465	858465	-----> command git symbolic-ref --short HEAD ^/dev/null
89	858554	----> and begin
171	858934	---> git_branch_name
170	859104	--> echo -n -s " on " $repository_color (git_branch_name) $normal_color " "
442907419	442907419	-------> command git status --porcelain
696	442908115	------> echo (command git status --porcelain)
433	442908548	-----> test -n (echo (command git status --porcelain))
47	442908595	----> and begin
379	442909424	---> git_is_touched
41	442909590	--> if git_is_touched...
35	443769332	-> if git_is_repo...
328	443771699	> fish_prompt
```

**Comment by faho** [comment]
>I am beginning to suspect git status --porcelain

That looks like it, yes.

Also: That isn't our git prompt. We don't have these `git_is_` functions. If your prompt _also_ does those, and not just call our `__fish_git_prompt`, then that should explain why it's taking so much longer than it. I suggest you remove it from your prompt.

**Comment by hrvoj3e** [comment]
Hm... New to fish. 
It was the default OMF prompt to blame.

**Comment by faho** [comment]
@hrvoj3e: Could you do me a favor and see how long

```fish
git diff --no-ext-diff --quiet
```

takes compared to `git status --porcelain`?

**Comment by hrvoj3e** [comment]
Like this? (duration is really inconsistent)
```
laptop ~/c/s/t/e/w/d/public> git diff --no-ext-diff --quiet
laptop ~/c/s/t/e/w/d/public> echo $CMD_DURATION
114504
laptop ~/c/s/t/e/w/d/public> git status --porcelain 
laptop ~/c/s/t/e/w/d/public> echo $CMD_DURATION
29782
laptop ~/c/s/t/e/w/d/public> git diff --no-ext-diff --quiet
laptop ~/c/s/t/e/w/d/public> echo $CMD_DURATION
15772
laptop ~/c/s/t/e/w/d/public> git status --porcelain 
laptop ~/c/s/t/e/w/d/public> echo $CMD_DURATION
10401
laptop ~/c/s/t/e/w/d/public> git diff --no-ext-diff --quiet
laptop ~/c/s/t/e/w/d/public> echo $CMD_DURATION
346
laptop ~/c/s/t/e/w/d/public> git status --porcelain 
laptop ~/c/s/t/e/w/d/public> echo $CMD_DURATION
12828
laptop ~/c/s/t/e/w/d/public> git status --porcelain 
laptop ~/c/s/t/e/w/d/public> echo $CMD_DURATION
2180
laptop ~/c/s/t/e/w/d/public> git diff --no-ext-diff --quiet
laptop ~/c/s/t/e/w/d/public> echo $CMD_DURATION
3479
```
Dir `~/c/s/t/e/w/d/public` is mounted via `sshfs`.
```
sshfs $HOST:$REMOTE_DIR $MOUNT_DIR \
    -o compression=no \
    -o transform_symlinks \
    -o Ciphers=aes128-gcm@openssh.com \
    -o auto_cache \
    -o reconnect
```

**Comment by faho** [comment]
>Like this? (duration is really inconsistent)

It's a network filesystem, so a bit of variation is to be expected.

But this is varying so wildly that I can't really draw any conclusions. So we'll have to wait for someone with a more stable connection to give information - I asked in the OMF issue. Thanks anyway!

**Comment by pickfire** [comment]
I got a similar result, 25s for me to get a prompt on a git sshfs.
