### ISSUE TITLE
"rvm gemset" dont work

### ISSUE THREAD

**Issue by sgspaulo** [fish-shell/fish-shell#519]
I want to change the gemset with the command 'rvm gemset use-name-' but does not work.

```shell
~/w/relatorio 1.9.3@report (work) $ rvm gemset use pde
Using ruby-1.9.3-p194 with gemset pde
~/w/relatorio 1.9.3@report (work) $ rvm gemset list

gemsets for ruby-1.9.3-p194 (found in /home/paulo/.rvm/gems/ruby-1.9.3-p194)
   controle_frota
   demo
   eleicao
   estudos
   global
   pde
   pivotal
   rails4
=> report
   siscop
   teste
   todolist
```

my config.fish:
```shell
function fish_prompt
    set_color normal
    echo -n (prompt_pwd)
    echo -n ' '
    set_color green
    echo -n (~/.rvm/bin/rvm-prompt v g)
    set_color yellow
    echo -n ' ('
    echo -n (git branch 2> /dev/null | grep -e '^*' | sed 's/* //')
    echo -n ') $ '
    set_color normal
end
```

**Comment by faho** [comment]
This can't really work properly, so I'm closing.

**Comment by danielpclark** [comment]
RVM does work in the fish shell with the instructions provided at: https://rvm.io/integration/fish

Which is summed up in two things to do:

---

Download the fish functions from GitHub.

    curl -L --create-dirs -o ~/.config/fish/functions/rvm.fish https://raw.github.com/lunks/fish-nuggets/master/functions/rvm.fish
And activate the default Ruby manually in your config.fish file:

    echo "rvm default" >> ~/.config/fish/config.fish

---

They use the function file from https://github.com/lunks/fish-nuggets/blob/master/functions/rvm.fish .  I've personally updated the source and verified it works with RVM where-ever it is installed.  And I've even gone as far as to verify that this will now work in a container image such as Docker.

If you would like to add RVM back to this and **fish-future** I believe it's ready.

**Comment by faho** [comment]
>@faho If you would like to add RVM back to this and fish-future I believe it's ready.

What would you have us do for fish-shell? The way this works is the same way it has always worked - via some kind of wrapper. And I don't think we want to ship these kinds of wrappers in fish-shell proper, they can stay in third-party plugins.
