### ISSUE TITLE
umask tests failing

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5201]
@zanchey @faho any ideas why this is failing? https://travis-ci.org/fish-shell/fish-shell/builds/431269794

I didn't touch anything to do with the `umask` code, all changes where to the `string` builtin.

**Comment by faho** [comment]
`umask` is a function. It uses a whole bunch of `string` in the background (especially since it was written pre-builtin-math, so skipping that was important).

Though I don't see any `-e` in there.

**Comment by mqudsi** [comment]
The problem is here: https://github.com/fish-shell/fish-shell/blob/f823611c2ebfc575cb3f79820f182e84d67f5406/share/functions/umask.fish#L71

I think #3116 has to be closed as won't fix. `string match -r` is used extensively to operate on captured groups, in which case it is not only valid but required that a zero-width match be reported (and even before other non-zero-width matches). 

In this case, it's the expression on line 60: https://github.com/fish-shell/fish-shell/blob/f823611c2ebfc575cb3f79820f182e84d67f5406/share/functions/umask.fish#L60

**Comment by krader1961** [comment]
I would recommend turning line 60 into a proper unit test added to *tests/string.in*.
