### ISSUE TITLE
fg command not seems to work in script

### ISSUE THREAD

**Issue by Estirp** [fish-shell/fish-shell#5202]
fish, version 2.7.1
The fg command not seems to work in script.

>\> cat script 
#!/bin/fish
gedit &
jobs
fg

>\> ./script 
Job	Group	CPU	State	Command
1	16461	0%	running	gedit &
fg: There are no suitable jobs

It should put gedit in the foreground of the script, and the script should wait for gedit termination.

If I execute
>\> gedit &
>\> fg

in the command line directly, it works as expected.

**Comment by faho** [comment]
Another appearance of #5036 - for some reason, fish disables part of the job control in scripts.

Workaround: Add `status job-control full` to the start of that script and it should work.
