### ISSUE TITLE
Multi-line variables as command line parameters

### ISSUE THREAD

**Issue by reisub0** [fish-shell/fish-shell#5205]
`fish --version` = 2.7.1

This issue is possibly related to #159. I have a binary called echocat which echoes the parameters given on the command line, and then defers to cat(Reconnects stdin). (Very useful in debugging python scripts as the initial input can be fed into a file, and then pdb commands can be executed interactively)

Contents of echocat
```
#!/usr/bin/env sh
(echo -e "$@" && cat)
```
`in` here is a file containing the sample input to the program. (Contains both spaces and newlines, both are significant)
This works perfectly in bash.
```
echocat "$(cat < in)" | ./prog.py
```
However, its equivalent in Fish
```
echocat (cat < in) | ./prog.py
```
fails as newlines and spaces are treated the same in fish and is split on it.

Is there any way to avoid this behaviour on fish?

**Comment by faho** [comment]
In fish 3.0, you'll be able to use `echocat (string split0 < in) | ./prog.py`.

Until then, the best you can do is to set IFS to empty:

```fish
begin
    set -l IFS
    echocat (cat in) | ./prog.py
end
```

**Comment by ridiculousfish** [comment]
Closing assuming the question has been answered.

**Comment by mqudsi** [comment]
I wonder if ` .. | read -z foo` should be the canonical answer for storing multi-line output in a single variable.
