### ISSUE TITLE
Avoiding the ? interpretation

### ISSUE THREAD

**Issue by wavic** [fish-shell/fish-shell#5207]
Hello!
I am trying to write an alias for youtube-dl

What I am doing:
`function yd3
    youtube-dl -x --audio-format mp3 "$argv"
end`

This downloads the video and saves the audio as mp3 using ffmpeg. However, in the address, there is a question sign '?' which is interpreted in fish as part of a re. I am putting quotes as you see but it doesn't work at all.
I have tried to escape them, to put the $argv between brackets: "($argv)".
Few more ways too but all of that didn't change anything.

How to fix this issue?

**Comment by wavic** [comment]
Yes, I invoke it without quotes.
`yd3 https://www.youtube.com/watch?v=MlW7T0SUH0E`
I know quoting will work but I was hoping I can pass the argument as a string literal.

I don't expect to pass multiple arguments. Just the web address.

So I should quote the argument? This is an extra typing but if I have to I will swallow it.

Thanks for the quick response!

**Comment by faho** [comment]
> I know quoting will work but I was hoping I can pass the argument as a string literal.

Quotes are how you write a "string literal"!

>So I should quote the argument? This is an extra typing but if I have to I will swallow it.

Yes, you should quote the argument, like you should quote all arguments with special characters.

You always do the same thing, no surprises. Fish's goal has never been to minimize typing. Minimizing surprises is much more important.

**Comment by mqudsi** [comment]
fish 3.0 un-special-cases the `?` character (though the behavior is currently behind a feature flag).
