### ISSUE TITLE
Keybinding: simulate press "q" to exit from view

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5208]
Fish 2.7

I added this keybinding:

```
    ## [Alt]+[g] -> Git status
    bind \eg 'git status'
```

but when i press alt+g, it requires me to press "q" to exit from this, unlike when you type `git status` which is annoying.

How can I exit that view?

**Comment by faho** [comment]
It doesn't actually require anything to exit out, it just won't repaint the commandline until you press something else.

Use

    bind \eg 'git status; commandline -f repaint'

**Comment by BarbzYHOOL** [comment]
Cool thank you!!!
