### ISSUE TITLE
Variable-as-command bug

### ISSUE THREAD

**Issue by Darkshadow2** [fish-shell/fish-shell#5209]
fish, version 2.7.1-1452-ga4836436

There seems to be a bug when setting a variable to `command` and using it as a command. It will print the help for `command` rather than run a command:

```fish
$ set -l t command
$ $t echo hello
```

...will print the help.  Interestingly, using flags works fine:

```fish
 $ $t -s echo
/bin/echo
```

I played around with a few other fish builtins and it seems this is specific to `command`. I didn't test them all, however. Just `test`, `echo`, `random`, `set_color`, and `string`. All of those worked normally.

**Comment by mqudsi** [comment]
`command` is treated differently in the parser as it's considered a decorator. You'll probably run into the same thing with `exec` and `builtin`.

**Comment by ridiculousfish** [comment]
Yes, `command` is a keyword. Variables can't become keywords because otherwise fish couldn't be statically parseable (e.g. consider a variable that expands to `end`). Closing as behaves correctly, thanks for filing!
