### ISSUE TITLE
eval in config.fish inside a second instance stops the shell

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#5210]
Running 2.7.1-1449-gdeb6d477

If you have the following in your `config.fish`:

```fish
if status is-interactive
   eval (touch /dev/null)
end
```

Then when starting a new instance of fish inside an existing instance, the behaviour is as follows:

```
> echo $SHLVL
1
> fish
Job 1, 'fish' has stopped
> echo $SHLVL
1
> jobs
Job	Group	State	Command
1	26930	stopped	fish
> fg
Send job 1, 'fish' to foreground
zanchey@oxygen ~> echo $SHLVL
2
zanchey@oxygen ~> exit
> echo $SHLVL
1
```

This bites me because I have `eval (python3 -m virtualfish)` in my `config.fish`.

**Comment by faho** [comment]
>This bites me because I have eval (python3 -m virtualfish) in my config.fish.

That should just be `python3 -m virtualfish | source`. Does that work? 

If it does the problem here is `eval`s weird job control stuff.

**Comment by faho** [comment]
Yup:

```fish
status job-control full
echo echo wurst | source # stops
status job-control interactive
echo echo wurst | source # does not
```

This is probably caused by fa66ac8d8cf487d3dbbb6f876391470abbd47e8e and friends.

**Comment by faho** [comment]
Definitely fa66ac8. This works:

```fish
status job-control full
command echo echo wurst | source
```

while `builtin echo command echo | source` still STOPs.

I think this is an issue with our keepalive process.

**Comment by mqudsi** [comment]
I toyed with using [owl](https://github.com/ianh/owl) to create a parser for fish expressions that would enable creating a logical process dependency chain to enable both simultaneous evaluation of non-dependent subshells, parallel commands, functions, or builtins and allow us to get rid of the keepalive process by instead creating a wait chain where each function only waits on the process(es) needed for its input streams to become ready but ran into [two](https://github.com/ianh/owl/issues/3) [issues](https://github.com/ianh/owl/issues/4) that prevented me from progressing down that track.
