### ISSUE TITLE
Keybinding that opens highlighted text in text editor

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5211]
Fish 2.7

How can I add a keybinding that opens my text editor automatically with the highlighted path in the terminal (and if multiple pathes, open them all).

Example:
ls
blabla /home/barbz/readme.md blabla

I select/highlight /home/barbz/readme.md, then I press Alt+O and it opens that file in my $VISUAL editor

Same if I highlight multiple pathes

**Comment by faho** [comment]
Do you highlight it with the mouse? If so, that's just something your terminal does and fish has no knowledge of.

**Comment by BarbzYHOOL** [comment]
Yes with the mouse (it's not possible with keyboard I guess)

Ok then :'(
