### ISSUE TITLE
How to bind clear command with ls

### ISSUE THREAD

**Issue by zhengwenjiee** [fish-shell/fish-shell#5214]
fish --version: 2.7.1

I am new to fish and first push an issue. if anything I say wrong. please forgive me.
and my bad English.

I want when I type control + l:
first, clear the screen, then list the file where I stay

I don't know how to use bind achieve my purpose, please help me, and thanks.

**Comment by faho** [comment]
What you need to do is run `clear`, then run `ls` and then repaint the commandline because bindings don't usually do that. So that is:

```fish
bind \cl 'clear; ls; commandline -f repaint'
```

Try it out interactively, if you like it put it into a function called `fish_user_key_bindings` and save that (e.g. with `funced` and `funcsave`).

**Comment by zhengwenjiee** [comment]
thank you @faho 
this is what I need, I kind of understand how it works.

my question similar like this issues [unable to bind a key](https://github.com/fish-shell/fish-shell/issues/2908)
if anyone with the mistake at **fish_user_key_bindings**, check out.
