### ISSUE TITLE
fish 3.0 git completion quick question

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5222]
A quick question:

Is there now git completion for things like `git add` where it selects file waiting to be staged?

What are the new git completion features mentioned in changelog?

**Comment by faho** [comment]
Yes.

See [the history](https://github.com/fish-shell/fish-shell/commits/master/share/completions/git.fish). The first commit not in 2.7.X was 34c2bf0f55673d6a89d24705a9aa68afeaa9944e, " Using new complete --keep-order option for __fish_git_recent_commits" - which of course relied on that new option to `complete`.

It's faster, doesn't always sort alphanumerically, suggests better kinds of files, suggests only files after a "--", doesn't error in bare repositories...

**Comment by BarbzYHOOL** [comment]
Ok thank you!!
