### ISSUE TITLE
Doxygen changes quotes in documentation

### ISSUE THREAD

**Issue by nickeb96** [fish-shell/fish-shell#5225]
Using: fish 2.7.1
On a mac running high sierra and iterm2

If you type `man test` and go down to the examples section, you will see an examples that tests  if the variable `MANPATH` is non-zero.

```
if test -n '$MANPATH'
    echo $MANPATH
end
```

This is not correct, `$MANPATH` should be double quoted not single quoted.  I'm not sure why the man pages are showing single quotes because in /doc_src/test.1 there are double quotes around the variable.  Perhaps it has something to do with how troff/groff processes it?

**Comment by faho** [comment]
Urgh... I initially reported this as #4389, and closed that in favor of the more general #4016. Only it turns out the fix for that didn't include this.

**Comment by nickeb96** [comment]
Honestly, I don't think the fix for #4016 really solved what it was supposed to solve either because I still get duplicate command names at the top of all the man pages too.

```
test(1)                              fish                              test(1)



NAME
       testtest - perform tests on files and text
        -


   Synopsis
       test [EXPRESSION]
       [ [EXPRESSION] ]
```

The fix for #4016 is about a year old and I would assume it would be in the latest release by now, but I guess I could be wrong.

There are honestly a lot of little problems I see in the documentation all over.  For example if you type `help`, it opens the docs in a browser.  Then click on *tutorial* at the top, and scroll about 3/4 of the way down.  You will see that all of the text, down to the bottom of the page, is erroneously styled as fish shell code.

It's everything below "To remove /usr/local/bin from $PATH, you can write:" to be exact.  I'm sure this should be in it's own separate issue though.

**Comment by faho** [comment]
>You will see that all of the text, down to the bottom of the page, is erroneously styled as fish shell code.

69f066dc1b4f8fad127fcb51f3468487751d8451.

**Comment by faho** [comment]
This seems fixed by switching to sphinx.
