### ISSUE TITLE
password changed?

### ISSUE THREAD

**Issue by Leuchtmarker** [fish-shell/fish-shell#5227]
So I tried to install fish (I used [this](https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A2&package=fish) instructions) on my Debian 9 Server. Everything worked fine in the first moment. I tried to set fish as my default shell with `chsh -s /usr/local/bin/fish` which didn't work because there was no `fish` directory in `/usr/local/bin`so I wanted to try it later. I closed fish with `exit` and I logged out of ssh. A few minutes later, I've tried to log me in via ssh to finish what I started but I wasn't able to because my permission was denied. I am 100% the password is correct. I can't even use sftp or anything else where I need my password.

**Comment by faho** [comment]
@Leuchtmarker: One common issue with `ssh` is that fish will _always_ read its configuration, and `ssh` really doesn't like when it gets output it doesn't expect. So if your config.fish prints anything, `ssh` and `scp` et al will fail.

**Comment by Leuchtmarker** [comment]
@faho is there anything I can do?

**Comment by faho** [comment]
I think `ssh -c /bin/bash` should work to give you a bash, where you can then fix your config.fish.

**Comment by Leuchtmarker** [comment]
Mhm.. `ssh -c /bin/bash`doesn't work: `Unknown cipher type '/bin/bash'`

**Comment by faho** [comment]
Sorry, force of habit. `ssh $host /bin/bash`

**Comment by Leuchtmarker** [comment]
same problem: `Permission denied (publickey,password).`

**Comment by faho** [comment]
Do you have other methods of accessing the machine?

@zanchey might know more here - I've never used ssh much.

**Comment by Leuchtmarker** [comment]
Unfortunately not, I could reinstall it but I would avoid this.

But thank you anyway @faho!

**Comment by zanchey** [comment]
If you've set your shell to something nonexistent, Debian will deny you login with a message like this:

```
User xyz not allowed because shell /usr/bin/nonexistent does not exist
```

Normally, chsh will not allow you to set a shell that does not exist, but if you run it as root this restriction is lifted. Unless you can log in as root, or another user, you are out of luck over SSH; if you have console access, you will probably have to use one of the [tricks for breaking back into your machine](http://www.debianadmin.com/how-to-reset-debian-root-password.html).

**Comment by Leuchtmarker** [comment]
@zanchey I tried to login via VNC which was kinda successful. I was able to see the login message for less than 1 second. So I tried this instruction you linked but It wasn't successful. When I tried to reboot the system this message appeared: `Failed to talk to init daemon.`. `reboot -f` was successful but of course it still didn't work because this don't contact the init.

**Comment by mqudsi** [comment]
You are probably missing the an appropriate entry in `/etc/shells` (speaking from my own miserable experience with this once upon a time).

**Comment by Leuchtmarker** [comment]
@mqudsi is there anything I can do now?

**Comment by mqudsi** [comment]
Log in in single-user mode (from the grub boot menu), then type in `chsh -s $(which bash) YOUR_USER_NAME`

**Comment by Leuchtmarker** [comment]
That worked for me! Thank you @mqudsi!

**Comment by mqudsi** [comment]
No problem, glad it worked! I generally don't trust myself to set the shell without fat-fingering it so I always use `which ...` in a subshell as a parameter to `chsh -s` and to echo to `/etc/shells`.
