### ISSUE TITLE
Cannot git autocomplete single file from newly-added subdirectory

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5229]
```fish
mkdir foo; cd foo;
git init .
mkdir bar
touch bar/baz
git add bar<TAB> # or git add bar/<TAB>
```

The git completion is not aware of the contents of the new subdirectory `bar`, and does not offer `bar/baz` as a completion no matter what.

**Comment by faho** [comment]
`git --version`?

This offers ´bar/` for me, which is a result of using "-unormal" instead of "-uall". We might want to rethink that.

**Comment by faho** [comment]
Note that "uall" can be _quite_ slow, so we might want to couple this with limiting to the current directory (via `commandline -ct`)

**Comment by mqudsi** [comment]
Thanks for digging into it. Normally fish does not dig into a directory (nor offer recursive completions) unless that directory has been typed out at the command prompt, so I imagine we can special-case the completion code to use `-uall` when `commandline -ct | string match -qe /` is true?

**Comment by faho** [comment]
> I imagine we can special-case the completion code to use -uall when commandline -ct | string match -qe / is true, then restrict the search to commandline -ct | string replace -r '/.*' '/'?

No need to even do something that complex - it turns out that commandline arguments are always checked, so `git status -unormal (commandline -ct)*` would work. There's some ramifications to that, and I'm not sure if _we_ want to do the glob or let git do it.

**Comment by mqudsi** [comment]
> I'm not sure if we want to do the glob or let git do it.

With my recent experience in mind: whichever one is faster 😄

**Comment by mqudsi** [comment]
@faho I don't know if you'd prefer a separate issue for these, but

- [ ] `git checkout COMMITISH <TAB>` should complete files that were in the repo at that time
- [ ] `git show <TAB>` should offer local and remote branches, not just commitishes
- [ ] `git show COMMITISH:<TAB>` should complete files that were in the repo at that time
- [ ] `git bisect` has a well defined format (that also stupidly breaks with all git conventions) and takes a sub-sub-command instead of an argument. It should be straightforward, though.

**Comment by faho** [comment]
>git show <TAB> should offer local and remote branches, not just commitishes

It [does](https://github.com/fish-shell/fish-shell/blob/master/share/completions/git.fish#L757).

The rest just haven't been added. Any idea how to complete "files at the time"?

(This is why I said that doing git completions could be a full time job)

**Comment by faho** [comment]
>git bisect has a well defined format (that also stupidly breaks with all git conventions) and takes a sub-sub-command instead of an argument.

Not really - `stash` also does sub-subcommand.

**Comment by mqudsi** [comment]
> It does.

You're right. In a repo like fish, it's just impossible to see them in the autocompleter because of the ordering of results.

Can you please universally add a rule for `--`? `git checkout -- ` should complete files (theoretically from HEAD, but it's OK if just locally) but instead it exhibits #5237

**Comment by faho** [comment]
>git checkout -- should complete files (theoretically from HEAD, but it's OK if just locally)

Well.. no? I mean if you do `git checkout -- README.md`, and README.md exists and is known to git, that won't error out, but unless README.md is deleted or modified that command should be useless.

Which is why checkout already has:

```fish
complete -k -f -c git -n '__fish_git_using_command checkout' -a '(__fish_git_files modified deleted)'
```

If we can reliably determine which files are useful we should only offer those, because the other files are just noise.

Or am I missing something?

(This probably triggers 5237 because of the "--")

**Comment by mqudsi** [comment]
Hmm, I can't remember now but it was in the middle of a partial rebase and I needed to checkout the file to restore some changes or something. I will post back if/when I can repro.
