### ISSUE TITLE
Command "touch" doesn't work as zsh or bash do

### ISSUE THREAD

**Issue by yiran7324** [fish-shell/fish-shell#5230]
fish, version 2.7.1
Oh My Fish version 6

I want to create multiple files using command "**touch**". It appears to  be generating continuous file series like: `200.c, 201.c, 202.c, 203.c, 204.c, 205.c` in zsh or bash (I used to use zsh and it worked) when we use:
```shell
touch {200..205}.c
```

But fish seems just to make a file named "**200..205.c**".

<img width="105" alt="screen shot 2018-10-05 at 1 34 40 am" src="https://user-images.githubusercontent.com/30183249/46492118-44f1eb00-c83f-11e8-872c-f87cfe64023c.png">
<img width="288" alt="screen shot 2018-10-05 at 1 34 59 am" src="https://user-images.githubusercontent.com/30183249/46492121-458a8180-c83f-11e8-95ae-a3cd770483e0.png">

I'm new here and I wonder if there is some wrong with fish or fish just touch multiple files in different way.

**Comment by faho** [comment]
`touch` works exactly the same as it does in bash or zsh, as it is an external command.

The difference is that Fish does not support range expansions. Use `seq` instead, like

```fish
touch (seq 200 205).c
```
