### ISSUE TITLE
change cursor keyboard shortcut in fish

### ISSUE THREAD

**Issue by zhengwenjiee** [fish-shell/fish-shell#5233]
hi, I just got a trouble
in the command line, my tmux hotkey **Ctrl + F** conflict with cursor hotkey **Ctrl + F**(meaning move forward one character.).
I am very comfortable with tmux's key. I want to change cursor key to **Ctrl + R**.
is anybody known how to solve this in both bash and fish shell?
I will be very grateful. thank you.

**Comment by faho** [comment]
In fish, you'll need to use `bind`. We write "ctrl + f" as `\cf`, so `bind \cf` will show you what that is bound to. `\cr` is the way to write "ctrl + r", so:

```fish
bind \cr forward-char
```

will bind ctrl + r to forward-char.

In the current fish releases, you'll need to create a function called `fish_user_key_bindings` and add it there. The upcoming fish 3.0 makes that unnecessary, so you could just add it to your config.fish directly.

(Also in general if you want to know what sequence we call a key, you can use `fish_key_reader`)

----

In bash, there are two ways to change it: One to change it just in bash, and one to change it for every program using "readline", which includes not just bash but also for example python and mysql.

First, you'll want to figure out what ctrl-f is bound to. Do something like `bind -p | grep C-f`. It'll print something like `"\C-f": forward-char`, so we know that "\C-f" is bound to "forward-char".

Now you can either use 

```bash
bind '"\C-r": forward-char'
```

(yes, the quotes are that weird) in .bashrc, .bash_profile or some other bash configuration file, or you can put

```
"\C-r": forward-char
```

into ~/.inputrc or /etc/inputrc to set it for every program using readline.

**Comment by zhengwenjiee** [comment]
is really helpful, very thanks @faho 
it gives me a lot of useful information. Now I have the more clear mind to handle this.
you're the hero.
