### ISSUE TITLE
Where is the $PAGER var defined?

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5234]
Where is the $PAGER variable set?

I was fiddling with it yesterday but today I realized it is always set to "less -R" by typing `export | grep -i less`

Is it a native variable from fish? I grepped my fish directory and found nothing about pager

Also I noticed it is set for bash too? I thought environment variables were specific to the shell.

**Comment by floam** [comment]
You can check your fish installation with `set --show PAGER` - maybe you set a universal variable at one time.

**Comment by BarbzYHOOL** [comment]
Ok, i note this down
