### ISSUE TITLE
Allow regular completions after `git rebase .... --exec `

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5236]
@faho everything passed to `git rebase` after `--exec` is interpreted as a sequence of commands to be executed for each revision. I'm not suggesting anything too fancy here, if we could just relax the `-x` so that I can autocomplete `--exec ./build_tools/<TAB>` that would be nice.

If this requires changing everything, it might be worth just closing it as won't fix *shrug*.

**Comment by mqudsi** [comment]
(Similarly, I believe any git command treats any parameters after `--` as a filename and nothing else, I don't know if each case where file names are supported in some arcane use cases are handled by the current completions, but if there is some way to globally revert to file-based completions after `--` is encountered, I think that would be a nice win.)

**Comment by faho** [comment]
> if we could just relax the -x so that I can autocomplete --exec ./build_tools/<TAB> that would be nice.

Yeah, that's probably alright. This actually takes script for $SHELL, but we can't necessarily complete that. If it's fish we could, but there'd be some weirdness with quoting....

**Comment by faho** [comment]
>Similarly, I believe any git command treats any parameters after -- as a filename and nothing else

As always with git, it's not quite that simple. We've added some of this - `reset` has:

```fish
# reset can either undo changes to versioned modified files,
# or remove files from the staging area.
# Deleted files seem to need a "--" separator.
complete -f -c git -n '__fish_git_using_command reset; and not contains -- -- (commandline -op)' -a '(__fish_git_files all-staged modified)'
complete -f -c git -n '__fish_git_using_command reset; and contains -- -- (commandline -op)' -a '(__fish_git_files all-staged deleted modified)'
complete -f -c git -n '__fish_git_using_command reset; and not contains -- -- (commandline -op)' -a '(__fish_git_reflog)' -d 'Reflog'
```

Yes, deleted files are only valid after `--`.
