### ISSUE TITLE
Pathological case file globbing performance

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5240]
_I'm not sure if this is "the new normal" but I'm proceeding on the good faith assumption that there is a pathological case I'm hitting that's giving me these results._

I have a script that was working fine on one PC and it suddenly wouldn't work on my laptop, hanging the shell each time I ran it. I thought it was a bug in my job blocking code in the 5219 branch, but it kept reproducing under master.

It turns out the script called `for f in **.tex` to get a list of tex fles (recursively) for processing, but on this PC the directory I placed it in happens to contain more files (or a particular arrangement of files) that caused this to take around 30 seconds to execute.

```
mqudsi@ZBook /m/c/U/m/Documents> hyperfine -S fish 'echo **' 'fd'
Benchmark #1: echo **

  Time (mean ± σ):     30.622 s ±  0.817 s    [User: 6.306 s, System: 24.295 s]

  Range (min … max):   29.766 s … 32.485 s

Benchmark #2: fd

  Time (mean ± σ):      88.0 ms ±   5.0 ms    [User: 136.4 ms, System: 443.8 ms]

  Range (min … max):    82.3 ms … 101.0 ms

Summary

'fd' ran
  347.90x faster than 'echo **'
```

fd is fast, there's no doubt about it. But it shouldn't be 347 times faster. A better comparison would be to `find` but hyperfine takes many minutes to complete its run because of how bad fish's performance is in this case, so here's fd vs find in the same directory:

```
mqudsi@ZBook /m/c/U/m/Documents> hyperfine 'find .' 'fd'
Benchmark #1: find .

  Time (mean ± σ):     291.9 ms ±  13.1 ms    [User: 20.2 ms, System: 271.6 ms]

  Range (min … max):   276.6 ms … 321.8 ms

Benchmark #2: fd

  Time (mean ± σ):      83.6 ms ±   2.2 ms    [User: 129.7 ms, System: 435.6 ms]

  Range (min … max):    80.5 ms …  89.1 ms

Summary

'fd' ran
    3.49x faster than 'find .'
```

I'm going to have to dig in more, one directory at a time, to see if there's any obvious culprit. It's the "My Documents" folder and it's not by any means _insanely_ huge:

```fish
mqudsi@ZBook /m/c/U/m/Documents> fd | wc -l
6137
mqudsi@ZBook /m/c/U/m/Documents> find . | wc -l
10331
```

In the normal case, `**` file globbing is slow, but only ~3x slower than `find`:

```
mqudsi@ZBook /m/c/U/m/Downloads> hyperfine -S fish 'echo **' 'find .'
Benchmark #1: echo **

  Time (mean ± σ):     780.8 ms ±  18.2 ms    [User: 359.8 ms, System: 418.4 ms]

  Range (min … max):   753.4 ms … 814.1 ms

Benchmark #2: find .

  Time (mean ± σ):     258.5 ms ±   2.1 ms    [User: 15.4 ms, System: 241.9 ms]

  Range (min … max):   255.7 ms … 263.1 ms

Summary

'find .' ran
    3.02x faster than 'echo **'
```

So I'm thinking there's definitely something wrong here.

**Comment by mqudsi** [comment]
Interesting that fish's `echo **` spends such a backwards ratio of time between user cpu and system cpu for what should be a very light system call: `[User: 6.306 s, System: 24.295 s]`.

**Comment by faho** [comment]
There's a few things that may be at fault here. One is that `find` (and I strongly suspect `fd` as well) doesn't follow symlinks by default.

@mqudsi: Can you compare `find -L`?

**Comment by mqudsi** [comment]
That definitely plays a role, nice catch.

```
mqudsi@ZBook /m/c/U/m/Documents> fd -u . | wc -l
8956
mqudsi@ZBook /m/c/U/m/Documents> fd -u -L . | wc -l
232392
```

`fd` is stupid fast (@sharkdp 👍):

```
mqudsi@ZBook /m/c/U/m/Documents> hyperfine 'fd -L .'
Benchmark #1: fd -L .

  Time (mean ± σ):      2.696 s ±  0.162 s    [User: 1.542 s, System: 10.109 s]

  Range (min … max):    2.542 s …  3.006 s
```

Both `find` and `echo **` suck, but we're better than `find` if it's any consolation:

```
mqudsi@ZBook /m/c/U/m/Documents> hyperfine -i -S fish 'echo **' 'find -L .'
Benchmark #1: echo **

  Time (mean ± σ):     32.692 s ±  0.609 s    [User: 7.471 s, System: 25.166 s]

  Range (min … max):   31.696 s … 33.629 s

Benchmark #2: find -L .

  Time (mean ± σ):     55.411 s ±  0.408 s    [User: 28.532 s, System: 82.233 s]

  Range (min … max):   55.009 s … 56.005 s

  Warning: Ignoring non-zero exit code.

Summary

'echo **' ran
    1.69x faster than 'find -L .'
```

**Comment by faho** [comment]
>Both find and echo ** suck, but we're better than find if it's any consolation

Well.... if we're actually faster than `find`, then it's quite likely that the only reason `fd` is faster because it:

>Ignores hidden directories and files, by default.
Ignores patterns from your .gitignore, by default.

So you probably want to compare `fd -HIL .`, because we can't ignore those things.

**Comment by mqudsi** [comment]
There are a lot of reasons why fd is fast. I thought -u would be the same as -HI, but it's not.

```
mqudsi@ZBook /m/c/U/m/Documents> hyperfine 'fd -HIL .'
Benchmark #1: fd -HIL .

  Time (mean ± σ):      3.883 s ±  0.234 s    [User: 1.773 s, System: 20.297 s]

  Range (min … max):    3.626 s …  4.324 s
```

**Comment by sharkdp** [comment]
I guess the `**` glob in `fish` does not include hidden files, but everything else. So you probably want to compare against `fd -IL .`, which follows symlinks (`-L`) and does *not* respect `.gitignore` files (`-I`).

**Comment by mqudsi** [comment]
@sharkdp thanks for chiming in. There's still some mismatch between the two, but it's a lot closer. 

```fish
mqudsi@ZBook /m/c/U/m/Documents> printf '%s\n' ** | wc -l
232407
mqudsi@ZBook /m/c/U/m/Documents> fd -IL . | wc -l
232391
```

(I'm not questioning the correctness of either implementation in all cases.)

**Comment by sharkdp** [comment]
It would be interesting to know what the difference is, could you please run
```
diff <(printf '%s\n' ** | sort) <(fd -IL .)
```
?

**Comment by mqudsi** [comment]
Well, that syntax doesn't work under fish 😁 but here you go:

```
16178,16182d16177
< Downloads/regex-performance/vendor/tre/utils/compile
< Downloads/regex-performance/vendor/tre/utils/config.guess
< Downloads/regex-performance/vendor/tre/utils/config.sub
< Downloads/regex-performance/vendor/tre/utils/depcomp
< Downloads/regex-performance/vendor/tre/utils/install-sh
16186d16180
< Downloads/regex-performance/vendor/tre/utils/missing
16188d16181
< Downloads/regex-performance/vendor/tre/utils/test-driver
142046d142038
< git/grub/include/grub/cpu/efi/i386
142244d142235
< git/grub/include/grub/machine/i386
142394d142384
< git/grub/include/grub/x86_64/efi/i386
229556,229559d229545
< My Music
< My Music (1)
< My Pictures
< My Pictures (1)
229566,229567d229551
< My Videos
< My Videos (1)
```

```fish
mqudsi@ZBook /m/c/U/m/Documents> file Downloads/regex-performance/vendor/tre/utils/compile
Downloads/regex-performance/vendor/tre/utils/compile: broken symbolic link to /usr/share/automake-1.15/compile
mqudsi@ZBook /m/c/U/m/Documents> file git/grub/include/grub/cpu/efi/i386
git/grub/include/grub/cpu/efi/i386: broken symbolic link to i386
mqudsi@ZBook /m/c/U/m/Documents> file 'My Videos'
My Videos: unreadable symlink `My Videos' (Permission denied)
mqudsi@ZBook /m/c/U/m/Documents> file 'My Videos (1)'
My Videos (1): broken symbolic link to /mnt/c/$WINDOWS.~BT/NewOS/Users/Mahmoud/Videos
```

A very fair difference of opinion.

**Comment by sharkdp** [comment]
Thank you! So it's only broken symlinks and directories that we can read the name from (but can not enter).

> A very fair difference of opinion.

Agreed ;-)

**Comment by faho** [comment]
Okay, I'm closing this because it's not specifically actionable.

It's possible to be faster at globbing, but it's always possible to be faster at everything and in current fish we're not awful.
