### ISSUE TITLE
Force autocompletion of a file path

### ISSUE THREAD

**Issue by swarmer** [fish-shell/fish-shell#5248]
Hi, everyone. I'm typing a command that accepts a file and it seems that fish isn't aware that the argument is a file so it doesn't offer any autocompletions even if it highlights the partial path as a valid path prefix. So tab or alt-right arrow do nothing.

How can I force fish to provide me an autocompletion for what looks like a beginning of an existing path? I don't care if fish doesn't have autocompletions for my particular command -- I would never hope that it can handle all commands anyway. I just want to force fish to give me file completions.

I guess either I'm blind not being able to find this, or this is a feature request.

I'm using fish 2.7.1.

And thanks for your time and efforts working on this wonderful shell.

**Comment by swarmer** [comment]
Yup, you're right, it seems to be broken only with this one command.
`pip install -Ur <filepath>` is when it fails.

**Comment by swarmer** [comment]
Alright, this makes sense.
I want to piggyback a related question though. How can I disable broken autocompletions or override with my own? `complete -c pip -e` works, but only if execute it manually. I can't find a place where I can put it so it's used automatically. `config.fish` doesn't work and neither does `.local/share/fish/completions/pip.fish`.

**Comment by swarmer** [comment]
Oh nevermind, it should be `.config/completions`.
Thanks for your help.

**Comment by Tyilo** [comment]
Sorry for bumping an old issue, but I often have the same problem with different tools, so I would like to have a shortcut to force autocompletion of paths.

Currently I have the following problem where autocompletion doesn't work:
```
mvn install:install-file -Dfile= $HOME/Downloads/<TAB>
```

There is also a problem with `dd`:
```
dd if= $HOME/<TAB>
```

**Comment by krobelus** [comment]
@Tyilo your issues with the `dd` and `mvn` completion scripts should be fixed by 73b13315d

since file completion is the default, it's should be enough if completion scripts are fixed

**Comment by krobelus** [comment]
that's a different problem: fish doesn't know how to safely complete incomplete
tokens (there is an unclosed quote). Bash won't do that either.
We can try to fix that for some cases but it's not so easy

**Comment by JeanMertz** [comment]
> I just stumbled upon another problematic command:
> 
> ```
> curl -i https://example.com/ -F 'file=@/home/tyilo/Downloads/<TAB>
> ```
> 
> The autocompletion also fails in this case.
> 
> Of course the autocompletion of `curl` should be fixed, but I would still like a way to force to autocomplete by path, so that non-optimal autocompletions cannot disable it.

I came here for this same issue. However, I should note that the path autocomplete in general doesn't trigger if it's prefixed with a character, even if there aren't unclosed quotes.

E.g. I have a custom command `jp query @./foo|` with the cursor at `|` but even if I have a `./foo.txt` file in the current working directory, it will not auto-complete. It would be great if that could be configured to work somehow (globally, without writing autocomplete for individual commands).
