### ISSUE TITLE
Can't cd to /

### ISSUE THREAD

**Issue by Darkshadow2** [fish-shell/fish-shell#5250]
fish, version 2.7.1-1528-g8de34a3f

If I try to `cd` to `/`, I just get an error message (`cd: Permission denied: '/'`). It doesn't matter what user I use, and doesn't matter if I use `builtin cd`, either. I always get the permission denied error.

`cd` is the stock fish function - I haven't overridden it.

I know it's not actually a permission error, as I can make a symlink and `cd` into the symlink (`ln -s / root && cd root` works), and `ls /` will show it.

This bisects to 0f0bb1e10f0f9d749b3d4a48de3a9d86376a7825

**Comment by zanchey** [comment]
Yes indeed!

**Comment by ridiculousfish** [comment]
🤦‍♂️
