### ISSUE TITLE
SIGINT swallowed when running non-interactively

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5253]
Typing the following in at an interactive prompt, hitting enter, then `^C` works (i.e. it stops);
```fish
while true
    echo hi
end
```

but execute the following script and try to stop it with ctrl+c and it never stops:
```fish
#!build/fish
while true
    echo hi
end
```

But it _can_ be backgrounded via ctrl+z, so it's not that signals are blocked, the issue appears to be specific to ctrl+c.

**Comment by ridiculousfish** [comment]
In non-interactive mode, fish squashes SIGINT and instead looks at the exit status of external commands. But if SIGINT arrives while fish is in the foreground then the signal will be dropped. In this case we're only executing builtins so fish is always in the foreground.

Let's just try allowing SIGINT to trigger cancellation.
