### ISSUE TITLE
Caret is invisible after right/left motion

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5254]
I'm not sure what changed in my setup, but I've found myself unable to navigate the command line buffer productively because after keying right/left I have no clue where the caret is because it's invisible until it blinks a full 0.5-1 second later.

Since you can't know how many spaces to the right or left you moved without the feedback from the caret, it should remain visible instead of remaining invisible while moving around in the buffer.

**Comment by faho** [comment]
Tried a different terminal?

We don't _display_ the cursor. We give the terminal commands as to where to move it.

**Comment by mqudsi** [comment]
Verified as being a WSL issue by testing the same fish build on two different versions of WSL.
https://github.com/Microsoft/console/issues/284

**Comment by faho** [comment]
>We don't use any of the cursor shaping APIs to dictate block mode, blink style, etc?

Well... there is `fish_vi_cursor`, but that only takes effect in vi-mode, and then only if you have set it up IIRC.

**Comment by mqudsi** [comment]
I stopped using fish's vi mode a long time (many years) ago. But I notice that sometimes the fish cursor is displayed as a block and sometimes as an underscore insertion symbol, but I can never pin down when it happens. Any clue?
