### ISSUE TITLE
Improve set -q for interactive use

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5256]
When running `set -q` in an interactive session and not as part of a pipeline (not e.g. `if set -q ..`) or command substitution, i.e. when the literal contents of the commandline buffer start with `set -q` and end with the name of the variable (so accounting for `set -q foo && echo foo`), `set` should print "debug info" to the terminal, including the variable name, the scope(s) it is defined in, and its value if it's a plain variable or its length if it's an array.

**Comment by faho** [comment]
That's what `set --show` is for.

**Comment by faho** [comment]
Example output:

```fish
$ set --show EDITOR
$EDITOR: not set in local scope
$EDITOR: set in global scope, exported, with 1 elements
$EDITOR[1]: length=9 value=|emacs -nw|
$EDITOR: not set in universal scope

```

**Comment by mqudsi** [comment]
I forgot about `--show`.
