### ISSUE TITLE
funced fails when EDITOR is empty

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5257]
```fish
mqudsi@ZBook /m/c/U/m/r/fish-shell> set -g EDITOR ''
mqudsi@ZBook /m/c/U/m/r/fish-shell> funced foo
- (line 1): The file “/tmp/fish.bi0zSv/foo.fish” is not executable by this user
begin;  /tmp/fish.bi0zSv/foo.fish 
        ^
from sourcing file -
        called on line 61 of file /usr/local/share/fish/functions/eval.fish

in function “eval”
        called on line 84 of file /tmp/fish.Byn9to/funced.fish

in function “funced”
        called on standard input
        with parameter list “foo”

Editing failed or was cancelled
```

**Comment by faho** [comment]
If it's string-empty, yeah.

An error message might be nice here, but really the underlying cause is user-error.

**Comment by mqudsi** [comment]
I don't know, I think you're being a little too kind. It's a bug because it's not validating the value before using it and the result is that `funced` is unusable. But I'm not going to bike shed over the github label 😄

**Comment by faho** [comment]
>the result is that funced is unusable

Note that `git commit` errors out when you set $EDITOR to the empty string, because it's "unable to start editor ''".

**Comment by faho** [comment]
Okay, as it turns out there was an attempt to handle an empty value in there anyway, only it failed to do anything about it.

Now we print an error and use fish's commandline.

**Comment by mqudsi** [comment]
Thank you, @faho.
