### ISSUE TITLE
Fish does not parse PATH from /etc/paths.d correctly on MacOS

### ISSUE THREAD

**Issue by astorath** [fish-shell/fish-shell#5260]
```
~ fish --version
fish, version 2.7.1
~ uname -a
Darwin Andreis-MacBook-Pro 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64
~ echo $TERM
xterm-256color
```

We have the following path defined at `/etc/paths.d/dotnet-cli-tools` (this is from default dotnet sdk install, no customization):
```
~/.dotnet/tools
```

It works normal in bash environment. But fish does not even parse this (relative) path:
```
~ sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
andy@Andreis-MacBook-Pro /U/andy> echo $PATH
/usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/share/dotnet /Library/Frameworks/Mono.framework/Versions/Current/Commands
andy@Andreis-MacBook-Pro /U/andy>
```

**Comment by mqudsi** [comment]
As a sidenote, this should be working in the general case as it's been heavily covered: https://github.com/fish-shell/fish-shell/issues?q=is%3Aissue+%22paths.d%22+is%3Aclosed

**Comment by astorath** [comment]
@mqudsi If I change relative path `~/.dotnet/tools` to absolute `/Users/andy/.dotnet/tools` - it works fine:
```
~ sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
andy@Andreis-MacBook-Pro /U/andy> echo $PATH
/usr/local/bin /usr/bin /bin /usr/sbin /sbin /usr/local/share/dotnet /Users/andy/.dotnet/tools /Library/Frameworks/Mono.framework/Versions/Current/Commands
andy@Andreis-MacBook-Pro /U/andy>
```

So I'm pretty sure this is fish issue.

**Comment by mqudsi** [comment]
Note that `~/foo` is not a relative path. It's an unexpanded absolute path.

**Comment by astorath** [comment]
@mqudsi yep, misnamed it

**Comment by astorath** [comment]
@mqudsi 

In fish 3.0 these are being added to PATH, but not expanded, so the issue stands...

**Comment by faho** [comment]
This is really just a special case of #6641 - we might want to expand "~" in $PATH.
