### ISSUE TITLE
Improve discoverability of special variables

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5262]
A common issue for me (don't judge) whenever I set up fish on a new machine is trying to remember if it's `fish_user_paths` or `fish_user_path` (I just checked, it's `fish_user_paths` even though the variable everyone knows and ~~loves~~ loves to hate is `PATH` without the `S`). This wouldn't be an issue if it were defined in a clean fish installation, i.e. if I could use `set fish_user_<TAB>` to autocomplete the name.

For `fish_user_paths`, it's a straightforward matter of ensuring the variable is initialized to an empty array in case it doesn't already exist, but I wonder if there are other fish values where an empty or undefined value causes fish to behave differently than if the variable weren't defined at all? 

If so, instead of predefining them it might be necessary to explicitly add them to the completion script for `set` so that it can be aware of them even when they are not defined.

**Comment by faho** [comment]
>If so, instead of predefining them it might be necessary to explicitly add them to the completion script for set so that it can be aware of them even when they are not defined.

That might be nicer even if it isn't necessary, given that we could add descriptions.

**Comment by charego** [comment]
I believe this can be closed. See https://github.com/fish-shell/fish-shell/issues/5884

**Comment by mqudsi** [comment]
That was a single example, I believe there are others.
