### ISSUE TITLE
Orphaned jobs remain running under WSL

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5263]
I imagine this is a case of fish relying on some posix behavior that isn't enforced under WSL, but the following results in backgrounded "unreachable" processes under fish/WSL:

```fish
~> nvim &
~> exit
```

Which is not the case under other platforms (just tested under macOS). Under WSL, the processes are dissociated from fish, as if `disown` or `nohup` were used.

As I develop fish primarily under WSL, in 1b1bc28c0ae0fd10e9d3854b1d8cc8125623e1d9 I added an explicit `kill_background_jobs()` function to emulate fish's behavior on `exit` for `exec`; I imagine this should simply be called on `exit` under WSL? 

Unless the right thing here is for fish not get involved and let the OS do its thing? Then again, job control is purely in the domain of the shell, so inconsistent behavior across platforms in that department is fish's job, right?

(So WSL used to terminate all background processes, disowned or not, when the last WSL terminal window closed. They made an architectural decision to spawn a new `init` per terminal window (crazy, I know) which remains alive to support `nohup`d jobs or services, but in the process `init` doesn't kill backgrounded jobs whose session has ended, leading to this PR.)

**Comment by ammgws** [comment]
Does this still happen in WSL2?

**Comment by mqudsi** [comment]
WSL2, aside from the nfs, io, and networking interop with Win32, is essentially an unmodified Linux distribution installation running the stock upstream kernel that ships with the distribution. fish may include or should include interop functionality for launching userland processes (e.g. open url in web browser), clipboard integration, etc. but otherwise would need no core patches or workarounds.

**Comment by ridiculousfish** [comment]
[Microsoft says](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq) "We currently have no plans to deprecate WSL 1" but it seems inevitable that it will be sooner or later. I don't think it makes sense to invest more work improving fish's WSL1 support, but @mqudsi you can if you like :)
