### ISSUE TITLE
Robbyrussell prompt is slow in git repository

### ISSUE THREAD

**Issue by gagarine** [fish-shell/fish-shell#5266]
I take almost a second for the prompt to show when hitting enter.

This only append when using the Robbyrussell prompt when in a git repository.
![screenshot 2018-10-19 at 12 24 21](https://user-images.githubusercontent.com/164074/47213029-14ab6000-d39a-11e8-8bb3-d79291151c09.png)

Using lonetwin, that also show git branch, do not have this problem.
![screenshot 2018-10-19 at 12 24 35](https://user-images.githubusercontent.com/164074/47213019-0f4e1580-d39a-11e8-9fc7-8114264f9153.png)

➜  fish --version
fish, version 2.7.1
➜   echo $version
2.7.1
➜ uname -a
Darwin computer.local 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

**Comment by faho** [comment]
Yup. This prompt uses its own git stuff, and it's bad. It calls `git` a bunch, which is slow.

Honestly, I'd be okay with just removing it, unless someone steps up to get it up to speed.

**Comment by mqudsi** [comment]
Should all these ship out of the box with fish, anyway? Do we have any idea what the usage numbers are like vs externally maintained plugins/scripts?

**Comment by faho** [comment]
>Should all these ship out of the box with fish, anyway?

It's a nice showcase to have pretty things, and this particular prompt style is broadly popular.

We should probably polish them up a bunch, though, and maybe trim some fat.

**Comment by floam** [comment]
@faho committed https://github.com/fish-shell/fish-shell/commit/eb0dd1ea7891b16d2964cc480e1f7f4457c280f4 today which may speed the robbyrussel prompt up.

**Comment by faho** [comment]
That commit sped it up from 825ms to 161ms. Which is still slow, but ~140ms of that is "hg summary", which doesn't have anything to do with being in a git repo (and we can repurpose some code from the hg prompt here).

So I'm declaring this done, because the git part is.

**Comment by faho** [comment]
Okay, this has now been double-fixed. Outside of a git repo, this prompt now takes 9ms for me. Used to be ~160ms.
