### ISSUE TITLE
After IO buffer is overrun, IO buffering is broken for future commands

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5267]
`all-the-package-names` has recently passed the 10MiB boundary, which uncovered some problems:

```fish
mqudsi@Blitzkrieg /m/d/r/fish> math (all-the-package-names | wc -c) / 1024 / 1024
10.534367
```

When the io buffer boundary is reached, the shell can be left unusable:

```
mqudsi@Blitzkrieg /m/d/r/fish> fg
/usr/local/share/fish/config.fish (line 279): Too much data emitted by command substitution so it was discarded

    builtin fg (__fish_expand_pid_args $argv)
               ^
in function “fg”
        called on standard input
```

Obviously, `$argv` is empty here and wouldn't have returned any data, let alone > 10MB.

To reproduce,

rubish.fish:
```fish
function foo1
    for i in (seq 1 20)
        cat /usr/share/dict/words
    end
end

# Entire list of packages is too long to be used efficiently in a `complete` subcommand.
# Search it for matches instead.
function foo2
    foo1 | string match -re -- ^(commandline -ct) #| head -n 50
end

complete -c rubbish -xa '(foo2)'
```

followed by the following:

```fish
source ./rubbish.fish
touch ./rubbish
chmod +x ./rubbish
./rubbish <TAB>
fg
```

**Comment by faho** [comment]
> I'm pretty sure this was caused by 4197420, which never shipped in any release.

Sure, yeah.

More specifically, the "read too much" flag on the buffer is probably never reset.

Also, since we now have something that actually outputs 10MiB.... should we increase the limit?

I mean that entire thing came about because somebody noticed that reading from (IIRC) /dev/zero would "hang" fish and be generally unhelpful. So it just needs to be large enough that it's "hang detection", not something to discourage you from using the shell. So 100MiB or even 1GiB would probably be alright on most systems (obviously if you ran this on a raspberry pi with 256MiB of RAM and no swap the latter won't really work).

**Comment by faho** [comment]
Oh, wait, there actually is an underlying limit: ARG_MAX.

If we're over that the OS won't accept the arguments anyway. On my system `getconf ARG_MAX` returns 2097152, which is 2MiB.

So that 10MiB won't work anyway.

**Comment by mqudsi** [comment]
> If we're over that the OS won't accept the arguments anyway. On my system getconf ARG_MAX returns 2097152, which is 2MiB.

No, the problem is that IO buffering is not only used for command substitution but also where it _shouldn't_ be used such as piping output from a function's stdout to another function or process' stdin.

If you look at the example you'll note that there's no command substitution (apart from `(commandline -ct)`, that is) going on. It's all stdout buffering.

**Comment by faho** [comment]
>If you look at the example you'll note that there's no command substitution

The `(foo2)` in

```fish
complete -c rubbish -xa '(foo2)'
```

is a command substitution.

**Comment by faho** [comment]
I can only confirm this with `rubbish <TAB>`, but not `rubbish a<TAB>`, and if I replace `(foo2)` with `(foo2 | string match -re ^a)`, it also works.

So it really does seem like it's the command substitution buffer being used for a command substitution.

**Comment by faho** [comment]
>I'm pretty sure function output is buffered even without command substitution

Yup - #1396.

**Comment by mqudsi** [comment]
Ah, yes. That's the one.

The reason function stdout buffering doesn't run into this bug is that functions there's no limit on how big the function buffer can get, they're explicitly allowed an uncapped buffer.

**Comment by faho** [comment]
This behaves kind of weird.

```fish
$ rubbish <TAB>
fish: Too much data emitted by command substitution so it was discarded #....
$ fg
fish: Too much data emitted by command substitution so it was discarded
$ echo (echo abc)
$ fg
fg: There are no suitable jobs
```

Do we somehow share buffers sometimes?

**Comment by mqudsi** [comment]
I just ran into this working on the `yarn` completions again. It's definitely not fixed.

**Comment by mqudsi** [comment]
It’s a recent master build but I know the test as documented here was fixed since I confirmed as much at the time. But the issue can be triggered differently.

**Comment by mqudsi** [comment]
This worked (it's an even simpler test than the original one):

```fish
mqudsi@Blitzkrieg /m/d/D/CPSA Board> function foo
                                         bar (all-the-package-names)
                                     end
mqudsi@Blitzkrieg /m/d/D/CPSA Board> function bar
                                     end
mqudsi@Blitzkrieg /m/d/D/CPSA Board> foo
fish: Too much data emitted by command substitution so it was discarded

bar (all-the-package-names)
    ^
in function “foo”
        called on standard input

mqudsi@Blitzkrieg /m/d/D/CPSA Board> fg
/usr/local/share/fish/config.fish (line 267): Too much data emitted by command substitution so it was discarded

    builtin fg (__fish_expand_pid_args $argv)
               ^
in function “fg”
        called on standard input
```

**Comment by faho** [comment]
Okay, this works for me with 29c627.

In addition, I'm going to increase the read limit to 100MiB. That still might not blow up your little Raspi, and you could possibly pass it in multiple passes. I don't think fish is used on smaller machines, so we don't need to optimize for those.
