### ISSUE TITLE
Unify string handling

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#5268]
This is something I've been thinking about for a while, but I'm still not sure if it's a good thing to do.

We use wchar_t* all over the place, and frequently have overloads like

```c++
bool wildcard_has(const wcstring &, bool internal);
bool wildcard_has(const wchar_t *, bool internal);
```

to allow wchar_t* and wcstring& to be used (though without the latter a wcstring would automatically be constructed IIUC).

Frankly, I like the wcstring stuff more, and the old-style chars have some issues in handling, like:

- Avoiding accidentally using NUL as a terminator (see #4605)

- Accidentally writing a [Shlemiel The Painter's algorithm](https://www.joelonsoftware.com/2001/12/11/back-to-basics/) by calling wcslen/strlen again and again and again

So what I'd like to see is:

- Remove wcslen/strlen etc uses by replacing them with wcstring::length()
- Remove wcscmp by replacing them with "=="
- Figure out what to do for wcscasecmp
- Stop reflexively creating wchar_t* versions everywhere

I'm not calling for a complete ban on wchar_t, just a reevaluation and simplification _where it makes sense_, which IMHO seems to be almost everywhere.

------

(Note that it would be possible to switch to std::string instead, and skip the "widechar" stuff entirely. From what I've read, that seems to be the usual thing to do in C++ projects, but it would also be much more work and I have no idea how e.g. `string length` would be affected. But that's a much bigger thing.)

----

Does this make sense to anyone else?

**Comment by faho** [comment]
>imho the lack of an std::sprintf is a horrible, horrible shame; all to force people to use the cumbersome and unwieldy sstream interface instead

C++ is a 33 year exercise in seeing how long you can force people to put up with string handling.

C is a nailbed, C++ removes one nail every year.

-----

So, really, what I'd like is for wchar to be the fallback, not the default.

And I'd also like some consensus on overloads - the `escape_string` with wchar_t* is apparently unused or can be silently casted to. Do we need to keep it?

How about all those helper functions that can't be casted? If I convert all the callsites, can I remove them?

**Comment by mqudsi** [comment]
Some of this stuff is called in hot paths though, where allocation needs to be avoided. I would not be for this if it means constructing a wcstring at the call site to allow the usage of the wcstring function (or silently casting to a wcstring, unless that's provably allocation-free). Things like the the autocompletion routines, etc. are called in tight loops each time a character is input and need to stay efficient (fast isn't as important as the autocomplete is running in a background thread), so as long as it's done on an instance-by-instance basis taking the context into account and fixed from the ground up (when a variable is first introduced/mutated) passing a (const &) wcstring down from there, I'd think it's OK.

(I also hope none of this happens before the job control changes can be merged, that would be one hell of a merge conflict.)

**Comment by faho** [comment]
>Can you find out if silent casting of a wchar_t * variable into a const wcstring & leads to a reallocation of the buffer in a -O2 build?

Yeah, that seems to allocate. I removed the "wcs2str(const wchar_t*)" overload and measured memory using valgrind's massif. It changed from 535 to 537KiB, with the majority going to std::__cxx11::basic_string.

Or how does one figure something like that out?

>I would not be for this if it means constructing a wcstring at the call site to allow the usage of the wcstring function

Note that the few commits I've added all involved _removing_ conversions. Plenty of things already have a wcstring and then drop down to wchar_t*. And that's the first thing that should go, really, especially if it involves a wcslen.

**Comment by mqudsi** [comment]
> Or how does one figure something like that out?

Someone with more time to waste than myself would just look at the assembly, but I resorted to this:

```cpp
#include <string>

void foo(const std::string str) {
	printf("Received a string with data buffer at address 0x%p\n", str.data());
}

int main(int argc, const char *argv[]) {
	const char *str = "foo";
	printf("Sending string at 0x%p to function with silent conversion to std::string\n", str);
	foo(str);
}
```

which produces the following:

```
Sending string at 0x0x400a38 to function with silent conversion to std::string
Received a string with data buffer at address 0x0x7ffff7657a28
```

**Comment by floam** [comment]
Do we have an open issue regarding getting away from `std::wstring` and `L""` towards just using narrow `std::string` and `u8""`? Is that a bad idea for some reason?

**Comment by zanchey** [comment]
@floam, that's #3034, closed as "known to the state of California to cause cancer, birth defects or other reproductive harm".

**Comment by ridiculousfish** [comment]
We'll never switch to `std::string`, it's too easy to misuse and its Unicode handling is non-existent. We'll have our own string type, probably with ASCII and wide representations internally.

**Comment by faho** [comment]
This seems to be obsolete now.
