### ISSUE TITLE
Make accessing config directories easier

### ISSUE THREAD

**Issue by Scrumplex** [fish-shell/fish-shell#5270]
the fish shell currently provides different variables to work with. These include

* `fish_complete_path`
* `fish_function_path`

But what I am missing is a `fish_data_path` variable which includes **all paths** where fish config files can be stored.

At the moment one can use `fish_config` (usually `~/.config/fish`) or `__fish_datadir` (`/usr/share/fish` on my system), where both are only one of the several paths I would expect.

`fish_data_path` should include the respective parent directories of `fish_function_path` paths.

**Comment by faho** [comment]
>But what I am missing is a fish_data_path variable which includes all paths where fish config files can be stored.

If we added this, it would look like you could change it, and you couldn't (because it would already have been used by the time you could change it).

Also $__fish_data_dir/config.fish is internal to fish, not something you are supposed to mess with.

What you mean is $__fish_sysconf_dir/config.fish, which is what you'd use if you wanted to add configuration for multiple users, e.g. if you are a sysadmin.

What I'd like to know is: Why do you want this? What do you want to do with it? Or is it just for symmetry?

**Comment by Scrumplex** [comment]
`$__fish_sysconf_dir` is not set on my system.

I am running fish version 2.7.1 from the official Arch Linux repositories (community/fish 2.7.1-1).

---
I want this so I can implement system wide packages in a fish package manager.

I would need to know where all data directories are too look for installed packages.

**Comment by Scrumplex** [comment]
As you can see [here](https://github.com/fish-shell/fish-shell/blob/master/share/config.fish#L93). The `fish_function_path` variable is initialized with several other fish variables.

**Comment by faho** [comment]
>$__fish_sysconf_dir is not set on my system.

We've renamed these for 3.0, it's $__fish_sysconfdir before.

>I want this so I can implement system wide packages in a fish package manager.

In that case, there are three directories, they are all given as their own variables, which is correct because we need to treat them differently. I don't really see the point of adding another variable.

**Comment by Scrumplex** [comment]
If I echo $fish_function_path I get the following directories:

```fish
$ echo $fish_function_path                       
/home/scrumplex/.config/fish/functions /etc/fish/functions /usr/share/fish/vendor_functions.d /usr/share/fish/functions
```

I now just want a quick way to find the following paths
```
/home/scrumplex/.config/fish /etc/fish /usr/share/fish
```

**Comment by faho** [comment]
>    set fish_data_path $fish_config $__fish_data_dir $__fish_data_dir

Almost - `$__fish_sysconf_dir $__fish_data_dir`, and `$fish_config` doesn't exist. The logic is

```fish
set fish_config ~/.config/fish
set -q XDG_CONFIG_HOME; and set fish_config $XDG_CONFIG_HOME/fish
```

Also since there is no moment when both versions of the "dir" variables are set, you can just use both:

```fish
set fish_data_path $fish_config $__fish_sysconf_dir $__fish_sysconfdir $__fish_data_dir $__fish_datadir
```

I'd be inclined to add `$__fish_config_dir` to point to the ~/.config/fish one.

**Comment by Scrumplex** [comment]
Would this be something worth adding to the default config.fish?

**Comment by faho** [comment]
Added in 6c988ab.

So now, if you only care about supporting fish >= 3.0, you can use:

```fish
set -l fish_config_path $__fish_config_dir $__fish_sysconf_dir $__fish_data_dir
```

**Comment by Scrumplex** [comment]
Thanks!
