### ISSUE TITLE
fish reader loses it when there's a blank line in an indented block

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5274]
Paste the following at the prompt:
```fish
	clang --autocomplete='--std=' |

		string replace -r -- '^([^ ]+)\s*(.*)' '$1\t\$2'
```

Observe that the text on the first row does not match what was pasted. Try navigating back and forth/up and down with the arrow keys on the different lines. Press ^C and observe that the prompt isn't cleared.

fish loses it.

https://asciinema.org/a/TsAwarGwkZTpVQL3aQ72Dkvkr

**Comment by faho** [comment]
Simplified test case:

```fish
commandline -i -- "" \ta
```

An empty line, then a line starting with a tab character.

**Comment by mqudsi** [comment]
Note that [I reverted](https://github.com/fish-shell/fish-shell/commit/6df29b2fd1757f6548a98a879f6babfde71cc6e7) the commit [that disabled ONLCR](https://github.com/fish-shell/fish-shell/commit/3f820f0edf637bc5769602dd7fff1fb22b2329cc) due to a very similar issue.
