### ISSUE TITLE
Clean up functions

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#5279]
After 3.0, I'd like for us to look into cleaning up our functions directory. This means removing some functions, but mostly moving functions which are only used by a single completion script into that completion script.

I've done some grep-foo, and I've come up with the following list (after the ":" is where these functions appear to be used):

# functions for moving into the completion script:
- [x] __fish_bind_test1.fish: completions/bind.fish functions/__fish_bind_test1.fish
- [x] __fish_bind_test2.fish: completions/bind.fish functions/__fish_bind_test2.fish
- [x] __fish_can_complete_switches.fish: functions/__fish_should_complete_switches.fish functions/__fish_can_complete_switches.fish
- [x] __fish_commandline_test.fish: completions/commandline.fish functions/__fish_commandline_test.fish
- [ ] __fish_complete_abook_formats.fish: completions/abook.fish functions/__fish_complete_abook_formats.fish
- [x] __fish_complete_ant_targets.fish: completions/ant.fish functions/__fish_complete_ant_targets.fish
- [x] __fish_complete_file_url.fish: completions/evince.fish functions/__fish_complete_file_url.fish
- [x] __fish_complete_lsusb.fish: completions/lsusb.fish functions/__fish_complete_lsusb.fish
- [x] __fish_complete_setxkbmap.fish: completions/setxkbmap.fish functions/__fish_complete_setxkbmap.fish
- [ ] __fish_complete_svn_diff.fish: completions/svn.fish functions/__fish_complete_svn_diff.fish
- [x] __fish_complete_tar.fish: completions/tar.fish functions/__fish_complete_tar.fish
- [x] __fish_complete_unrar.fish: completions/unrar.fish functions/__fish_complete_unrar.fish
- [x] __fish_complete_wvdial_peers.fish: completions/wvdial.fish functions/__fish_complete_wvdial_peers.fish
- [x] __fish_filter_ant_targets.fish: functions/__fish_filter_ant_targets.fish functions/__fish_complete_ant_targets.fish
- [x] __fish_first_token.fish: completions/unzip.fish functions/__fish_first_token.fish
- [x] __fish_is_git_repository.fish: completions/climate.fish functions/__fish_is_git_repository.fish
- [x] __fish_parent_directories.fish: completions/yarn.fish functions/__fish_parent_directories.fish
- [ ] __fish_parse_configure.fish: completions/configure.fish functions/__fish_parse_configure.fish
- [x] __fish_portage_print_available_categories.fish: functions/__fish_portage_print_available_categories.fish
- [x] __fish_portage_print_installed_categories.fish: functions/__fish_portage_print_installed_categories.fish
- [ ] __fish_portage_print_repository_names.fish: completions/emaint.fish functions/__fish_portage_print_repository_names.fish
- [ ] __fish_ports_dirs.fish: completions/ports.fish functions/__fish_ports_dirs.fish
- [x] __fish_prev_arg_in.fish: completions/optipng.fish functions/__fish_prev_arg_in.fish
- [ ] __fish_print_abook_emails.fish: completions/mutt.fish functions/__fish_print_abook_emails.fish
- [x] __fish_print_arch_daemons.fish: completions/rc.d.fish functions/__fish_print_arch_daemons.fish
- [ ] __fish_print_debian_services.fish: completions/invoke-rc.d.fish functions/__fish_print_debian_services.fish
- [ ] __fish_print_function_prototypes.fish: completions/valgrind.fish functions/__fish_print_function_prototypes.fish
- [ ] __fish_print_lsblk_columns.fish: completions/lsblk.fish functions/__fish_print_lsblk_columns.fish
- [x] __fish_print_make_targets.fish: completions/make.fish functions/__fish_print_make_targets.fish
- [x] __fish_print_ninja_targets.fish: completions/ninja.fish functions/__fish_print_ninja_targets.fish
- [x] __fish_print_ninja_tools.fish: completions/ninja.fish functions/__fish_print_ninja_tools.fish
- [ ] __fish_print_xdg_desktop_file_ids.fish: completions/xdg-mime.fish functions/__fish_print_xdg_desktop_file_ids.fish
- [x] __fish_print_xrandr_modes.fish: completions/xrandr.fish functions/__fish_print_xrandr_modes.fish
- [x] __fish_print_xrandr_outputs.fish: completions/xrandr.fish functions/__fish_print_xrandr_outputs.fish
- [ ] __fish_print_zfs_bookmarks.fish: completions/zfs.fish functions/__fish_print_zfs_bookmarks.fish
- [ ] __fish_print_zfs_filesystems.fish: completions/zfs.fish functions/__fish_print_zfs_filesystems.fish
- [ ] __fish_print_zfs_volumes.fish: completions/zfs.fish functions/__fish_print_zfs_volumes.fish
- [x] __fish_prt_no_subcommand.fish: completions/prt-get.fish functions/__fish_prt_no_subcommand.fish
- [x] __fish_prt_packages.fish: completions/prt-get.fish functions/__fish_prt_packages.fish
- [x] __fish_prt_ports.fish: completions/prt-get.fish functions/__fish_prt_ports.fish
- [x] __fish_prt_use_package.fish: completions/prt-get.fish functions/__fish_prt_use_package.fish
- [x] __fish_prt_use_port.fish: completions/prt-get.fish functions/__fish_prt_use_port.fish
- [ ] __fish_systemd_machine_images.fish: completions/machinectl.fish functions/__fish_systemd_machine_images.fish
- [x] fish_md5.fish: completions/gradle.fish functions/fish_md5.fish

# functions for removal:
- [x] __fish_test_arg.fish: completions/xterm.fish functions/__fish_test_arg.fish
- [x] __fish_complete_subcommand_root.fish: functions/__fish_complete_subcommand_root.fish
- [ ] fish_fallback_prompt.fish
- [N/A] fish_key_reader.fish
- [ ] __fish_sgrep.fish
- [x] string.fish

The removal list is more critical - `string.fish` and `fish_key_reader.fish` are a thing purely for compatibility with pre-2.3.1 fish, which is still sort of important because of old but still supported distros (like Ubuntu 14.04 and 16.04). On the other hand this is one of _two_ compatibility measures, the other in share/config.fish, and we don't really support this configuration anyway.

`__fish_sgrep` has been deprecated a while, there are [a few uses on github](https://github.com/search?q=__fish_sgrep&type=Code) though.

**Comment by faho** [comment]
Okay, the `fish_key_reader` script was introduced in 95385eda80ec2fbabd05ee0f01fac42a70cf6dad. The commit message says:

>Create a fish_key_reader wrapper ala fish_indent

>Needed for fish_key_reader to work in a .app bundle without
    fish previously installed.

And fish_indent.fish also exists (unlike fish_key_reader, fish_indent is used in scripts to my grepping didn't pick up on it).

I have no idea if that's still helpful or needed, so unless somebody explains that they aren't, I'd leave them be.

**Comment by floam** [comment]
Yes, they are still required to work. They make an alias like this:

`alias fish_key_reader /private/var/folders/0q/8cc45czd1ps_vbn96jn87xhc0000gn/T/AppTranslocation/69F19971-992D-4FA6-89E8-E0CE87693C16/d/fish.app/Contents/Resources/base/bin/fish_key_reader`

If I delete the alias in fish-the-app, and temporarily move my installed `/usr/local/bin/fish_*` binaries aside, `fish_stuff` gives command-not-found errors. The directory (which can also just be something like `/Users/foo/Downloads/fish.app/Contents/Resources/base/`, if the OS doesn't translocate it) in the app bundle, relative to $__fish_bin_dir, is not in $PATH.

If we don't like these, we could detect when we are in an app bundle, and add $fish_bin_dir to $fish_user_paths.

**Comment by faho** [comment]
>If we don't like these, we could detect when we are in an app bundle

Nah, it's alright. These are entirely non-critical when it comes to performance (or we'd have moved them to builtins long ago), so we can just leave it as-is.

**Comment by faho** [comment]
Some of these can actually be removed entirely:

```
__fish_portage_print_available_categories.fish
__fish_portage_print_installed_categories.fish
# rc.d is not a thing anymore in arch, so both this and the completion can go
__fish_print_arch_daemons.fish: completions/rc.d.fish functions/__fish_print_arch_daemons.fish
__fish_complete_subcommand_root.fish: functions/__fish_complete_subcommand_root.fish
```

**Comment by faho** [comment]
`__fish_gnu_complete` can also be removed. It's only used by `sed` and `df`, and removes the long options there if not running a GNU system, for the few cross-compatible options these share (4 for sed, 6 for df).

**Comment by faho** [comment]
Okay, I removed the two portage functions. As it turns out, they weren't in a release yet. Most likely they were leftovers from an earlier version of the PR that added them.

**Comment by faho** [comment]
The "hostname" function is also probably useless now. It's a workaround for cygwin, but we have $hostname now.

**Comment by floam** [comment]
Can I take that you did not self-assign to mean you'd be OK with others going through and doing some of these?

Maybe modify the post to have checkboxes (tasks), so they can get crossed off as progress is made.

**Comment by faho** [comment]
I've done some more work on this, I removed __fish_test_arg.fish because it's equivalent to one simple `string match` call.

**Comment by faho** [comment]
On fifth look let's keep the ones that aren't explicitly for one particular tool. This includes:

- [ ] __fish_first_token.fish: completions/unzip.fish functions/__fish_first_token.fish
- [ ] __fish_is_git_repository.fish: completions/climate.fish functions/__fish_is_git_repository.fish
- [ ] __fish_parent_directories.fish: completions/yarn.fish functions/__fish_parent_directories.fish
- [ ] __fish_prev_arg_in.fish: completions/optipng.fish functions/__fish_prev_arg_in.fish
- [ ] fish_md5.fish: completions/gradle.fish functions/fish_md5.fish

unless they are bogus like `__fish_test_arg` was.

**Comment by faho** [comment]
Also:

- [ ] fish_vi_mode: Been deprecated for years, actually prints a message to stderr.

**Comment by ammgws** [comment]
@faho  I think they are all done now.
