### ISSUE TITLE
Question: what does %d mean in fish

### ISSUE THREAD

**Issue by Charles-Neil** [fish-shell/fish-shell#5281]
fish, version 2.7.1

#### what does %d in fish mean?
I accidentally used the **%d** in `stat`(I know that I should wrap %d in quotes now)
`stat ./somefile -c %d
`
then I got something like:
```
stat: cannot stat '3058': No such file or directory
stat: cannot stat '3148': No such file or directory
stat: cannot stat '3410': No such file or directory
stat: cannot stat '17845': No such file or directory

```
Looks like that **%d** will be expanded in fish shell. `echo` also expands %d like the following:
user@machine/tmp> echo %d
2980 3058 3148 3410 17845
user@machine/tmp> 

so what does %d mean? Is there other marks in fish like %d?

Didn't find %d in the doc so I came here in search of help :) .

**Comment by krader1961** [comment]
It's a misfeature that has been removed from the upcoming fish 3.0 release. It's doing [process expansion](http://fishshell.com/docs/current/index.html#expand-process).

**Comment by Charles-Neil** [comment]
Thanks for your reply krader1961. I am gonna to close this issue.
