### ISSUE TITLE
Custom key binding not recognised

### ISSUE THREAD

**Issue by manuel-uberti** [fish-shell/fish-shell#5282]
Hi,

thanks for this awesome shell. It's been with me for a while now.

I am using version 2.7.1, on Ubuntu 18.04 with GNOME Terminal (xterm-256color). I added this line to `~/.config/fish/functions/fish_user_key_bindings.fish`:
```
bind \cs 'prepend_command sudo'
```
Which in turns uses `~/.config/fish/functions/prepend_command.fish`:
```
function prepend_command
    set -l prepend $argv[1]
    if test -z "$prepend"
        echo "prepend_command needs one argument."
        return 1
    end

    set -l cmd (commandline)
    if test -z "$cmd"
        commandline -r $history[1]
    end

    set -l old_cursor (commandline -C)
    commandline -C 0
    commandline -i "$prepend "
    commandline -C (math $old_cursor + (echo $prepend | wc -c))
end
```
However, whenever I hit <kbd>Ctrl+s</kbd> nothing happens, meaning `sudo` is not added at the beginning of the line as I am expecting.

If you need more tests or details, feel free to ask.

**Comment by manuel-uberti** [comment]
Actually, I fixed it already. 

Before `~/.config/fish/functions/fish_user_key_bindings.fish` looked like this:
```
# Prepend sudo with C-s
bind \cs 'prepend_command sudo'
```
Now it looks like this:
```
function fish_user_key_bindings
    fish_default_key_bindings

    # Prepend sudo with C-s
    bind \cs 'prepend_command sudo'
end
```

**Comment by faho** [comment]
Note that in 3.0 the `fish_user_key_bindings` function will be unnecessary.

You can just put your bindings into config.fish and it'll work. Or you can go on and use that function.

**Comment by manuel-uberti** [comment]
Awesome, even simpler. Thanks for the update.
