### ISSUE TITLE
Update docs on process/job expansion

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5286]
The documentation needs to be updated to reflect all the changes to job/process expansions, new fish variables, etc.

**Comment by faho** [comment]
There really isn't all that much mention of job and process expansion remaining.

Grepping doc_src/ for `%` finds just:

>"`%self`" can be specified as an alias for `$fish_pid`

Which IIRC is still correct.

"process expansion" is only in disown, "job expansion" finds nothing.

So it seems there is that one mention in disown to change, and some more mentions of $fish_pid and $last_pid to add?

**Comment by zanchey** [comment]
`wait`, `bg`, `fg`, `kill` (ugh) and `disown` all call `__fish_expand_pid_args`, which allows for psuedo-job-expansion; this should probably be described.

**Comment by mqudsi** [comment]
It's kind of been eating at me that I implemented that via a fish proxy, tbh.

**Comment by zanchey** [comment]
Yes, it's not ideal. Is there another approach other than wholesale restoration of job expansion?

**Comment by zanchey** [comment]
Also the combining expansion subsection still mentions PID expansion.

**Comment by faho** [comment]
>Is there another approach other than wholesale restoration of job expansion?

You mean to be able to `kill %2`? You can do `kill (jobs -p %2)`, which I don't think is too onerous. (For some reason, `jobs` accepts PIDs by default, so the "%" is necessary)

**Comment by floam** [comment]
Which builtin? We don't have a `kill` builtin.

**Comment by mqudsi** [comment]
@floam already worked around:

```
~> type kill
kill is a function with definition
# Defined in /usr/local/share/fish/config.fish @ line 282
function kill
    command kill (__fish_expand_pid_args $argv)
end
```
