### ISSUE TITLE
read to array tokenization is confusing

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5287]
```
mqudsi@ZBook /m/c/U/M/Downloads> printf 'hello world\ngoodbye world\n' | read -al hello
mqudsi@ZBook /m/c/U/M/Downloads> showargs $hello
"hello" "world"
```

The expected result is `"hello world" "goodbye world"`

The docs say 

> read reads from standard input and stores the result in one or more shell variables. By default, one line (terminated by a newline) is read into each variable. Alternatively, a null character or a maximum number of characters can be used to terminate the input. Unlike other shells, there is no default variable (such as REPLY) for storing the result.

and 

> -a or --array stores the result as an array in a single variable.

Which does not imply that there would be any change to the tokenization behavior when reading into an array.

Fish 3.0 introduces `-A` for `--all-lines`, but that does not address the root issue.

**Comment by faho** [comment]
From the documentation:

>By default, read reads up to the next newline and splits it into given variables on spaces or tabs.

The "array" bit doesn't affect what you think it does: It means to store all the delimited strings into the one variable, not to read more.

This is a bit of a rerun as you've personally introduced "--all-lines", which does that.

**Comment by mqudsi** [comment]
Thanks. 😳

**Comment by mqudsi** [comment]
I got confused because `-A` still needs `-a` to actually do what I want:

```fish
mqudsi@ZBook /m/c/U/m/Downloads> printf 'hello world\ngoodbye world\n' | read -A hello
mqudsi@ZBook /m/c/U/m/Downloads> echo $hello[1]
hello world
goodbye world
```

vs 

```fish
mqudsi@ZBook /m/c/U/m/r/fish-shell> printf 'hello world\ngoodbye world\n' | read -Aa hello
mqudsi@ZBook /m/c/U/m/r/fish-shell> echo $hello[1]
hello world
mqudsi@ZBook /m/c/U/m/r/fish-shell> echo $hello[2]
goodbye world
```

Should `-A` imply `-a`? This is what I wrote in the docs:

> - `-A` or `--all-lines` splits input into the given variables, separated by line breaks. The entire input stream is consumed and interactive mode is disabled. **Probably only useful with `-a` to read all lines into a single array variable.** Where possible, ` | while read --line` should be preferred over ` | read --all-lines` as the latter will block until the input stream has been consumed, leading to latency and decreased responsiveness.

But maybe it should just be automatic?

**Comment by mqudsi** [comment]
> It actually is just a shortcut for -d \n -z

Right. Man, my memory is like a sieve right now.

Since it's just a shortcut, I guess it makes sense to extend it to `-d \n -z -a`?

**Comment by mqudsi** [comment]
I think the reason I keep getting caught up on this is that it's the only (@faho please correct me if I'm wrong!) place in fish where the default separator for input tokenization is a space rather than a line. `read` breaks with that mental model and that's why I'm always forgetting how to use the darn thing.

I'm sure it's way too big of a break with tradition, but imho it would make more sense if `-d ' '` were the special case here.
