### ISSUE TITLE
\r should be stripped by shell builtins

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5288]
I was working on a CSV exported from MS Excel (which naturally has CRNL endings) and ran into some confusing behavior:

```fish
mqudsi@ZBook /m/c/U/m/r/fish-shell> printf 'hello world\r\ngoodbye world\r\n' | read -aAl foo
mqudsi@ZBook /m/c/U/m/r/fish-shell> echo $foo[1]
hello world
mqudsi@ZBook /m/c/U/m/r/fish-shell> echo $foo[2]
goodbye world
mqudsi@ZBook /m/c/U/m/r/fish-shell> echo $foo[1] $foo[2]
 goodbye world
```

I thought perhaps it was just `read`, but `string split` and presumably others have the same problem:

```
mqudsi@ZBook /m/c/U/m/r/fish-shell> printf 'hello world\r\ngoodbye world\r\n' | string split '\n'
hello world
goodbye world
mqudsi@ZBook /m/c/U/m/r/fish-shell> set parts (printf 'hello world\r\ngoodbye world\r\n' | string split '\n')
mqudsi@ZBook /m/c/U/m/r/fish-shell> echo $parts[1] $parts[2]
 goodbye world
```

**Comment by ridiculousfish** [comment]
What's the ask here - to silently strip carriage returns? If so that doesn't seem wise, we shouldn't be silently removing characters.

**Comment by mqudsi** [comment]
> What's the ask here - to silently strip carriage returns?

Not universally, no. But for builtins that have a concept of a line to strip `\r` when preceding a trailing `\n` or the end of the string, I guess? Aka redefine line from `(.*)\n` to `(.*)\r\n` anywhere "line" is used?

**Comment by krader1961** [comment]
I'm inclined to agree with @ridiculousfish. If you need to handle DOS/Windows text files on a UNIX version of fish you should probably be running them through `dos2unix` or a similar command. Presumably, @mqudsi, you ran into this while using fish on MS Windows via Cygwin or WSL. In both cases you're running fish in a UNIX like environment and fish shouldn't be silently stripping carriage-return chars. Silently dropping carriage-returns that immediately precede a newline is likely to be safe to do even on UNIX like systems most of the time when reading "lines of text"j. But that still begs the question of what to do when doing something like `read -z` followed by subsequent `string` commands on the captured text. It seems dangerous to have those subsequent commands silently drop the carriage-returns.

**Comment by mqudsi** [comment]
I think reading until null means it’s fair game to preserve everything as-is, including when explicitly splitting on \n subsequently. Fish shouldn’t prevent people from defining lines as they see fit in their own scripts, just better handle detritus from failed line endings. 

(This was actually on a Mac but with an excel-exported csv file that had Windows like endings.)

**Comment by krader1961** [comment]
> I think reading until null means it’s fair game to preserve everything as-is...

Yes, but your original comment suggested that the `string` command should somehow recognize that carriage- returns should be silently elided. Yes, the specific example you gave would have resulted in the carriage-returns being eliminated as a consequence of splitting the input to `string` into "lines" as a consequence of the pipe and thus `string` itself not being aware of the carriage-returns. But to my mind that makes the magic ignoring of carriage returns even more problematic.

**Comment by mqudsi** [comment]
Feel free to ignore my examples, they were for illustration purposes only.

**Comment by ridiculousfish** [comment]
I see how this could be confusing, but fish is the wrong layer in which to address this.

Note there's lots of characters that could conceivably mess up the command line - for example, ESC beginning an escape sequence. `dos2unix` can be used to convert line endings.

**Comment by faho** [comment]
It seems like there's rough consensus that we don't want to do this, so I'm closing this.
