### ISSUE TITLE
fish aggressively polls instead of blocking on certain commands

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#5292]
On master:`fish -c 'sleep 10'`

Run top and you'll see that fish is using 50% to 100% CPU. This is because it is not blocking correctly in `waitpid()`.

**Comment by mqudsi** [comment]
(I’m on my phone)

I imagine this worked before today’s 203de7?

**Comment by mqudsi** [comment]
Ah, it's because I was only blocking if the foreground job was under job control. When I disable the self pgid and job control predicates this goes away.

https://github.com/fish-shell/fish-shell/pull/5293

I just want to run it a bit before merging.
