### ISSUE TITLE
vim doesn't load ~/.vimrc in git commands

### ISSUE THREAD

**Issue by Zlopez** [fish-shell/fish-shell#5297]
Hi,

I'm having issue with using git commands in fish. When using git command, which opens an editor (`set EDITOR vim` in `.config/fish/config.fish`), the editor doesn't load `~/.vimrc` automatically. I don't have this issue in bash shell or if I run `vim` directly.

How to reproduce
----------------------
(requires) `~/.vimrc`
(requires) `set EDITOR vim`
1. Change directory to any git project
2. Run git command that needs editor (`git command --amend` for example)

Current output
------------------
vim is started with default configuration

Expected output
---------------------
vim loads `~/.vimrc`

`uname -u`: 4.18.16-200.fc28.x86_64
`fish --version`: 2.7.1
`git --version`: 2.17.2
`vim --version`: 8.1

**Comment by faho** [comment]
>set EDITOR vim

Use `set -gx EDITOR vim`. Otherwise the variable is not exported, which will cause git to not pick it up, in which case it will default to _vi_, not _vi**m**_, which will basically look like vim without the rc.

**Comment by Zlopez** [comment]
@faho 
Thanks, this helped. I will update my `~/.config/fish/config.fish`.

Sorry for opening the issue.

**Comment by faho** [comment]
>Sorry for opening the issue.

No problem, we do allow questions here!
