### ISSUE TITLE
Piping stops shell with "Could not send own process" and "setpgid: Operation not permitted" errors

### ISSUE THREAD

**Issue by comfortablynick** [fish-shell/fish-shell#5298]
fish, version 2.7.1-1636-g913f65cd
Ubuntu on WSL

Here is an example of what is happening:
```fish
echo 'test' | sed /s/es/ess/
```
Returns this:
```
Could not send own process 2362, 'sed' in job 1, 'echo 'test' | sed s/es/ess/' from group 2264 to group 2361
setpgid: Operation not permitted
tesst
```
I have also been getting these errors on other scripts, for example, trying to install Fundle.  I rebuilt this morning from latest master and it is still happening.  I have no choice but to close the terminal window and start a new session.

This also happens when running fish without customizations.

**Comment by mqudsi** [comment]
What version of Windows 10? 

Presumably you are running into the lack of zombie processes, which were not worked around in 2.7.1 and just had that workaround dropped from `master`.

**Comment by mqudsi** [comment]
The last commit with the keepalive hack would have been 9454397e4c30982db5b75b26267bcc3af1e1d749, if you are so inclined.

**Comment by faho** [comment]
@mqudsi: Might it be worth it to keep the hack for 3.0, considering that some users apparently haven't upgraded yet and it's quite a bad experience?

**Comment by comfortablynick** [comment]
I had to turn on Insiders builds to get access to 1809 since Microsoft pulled the update. It works great now, thanks. The shell was pretty unusable on 1803.

**Comment by mqudsi** [comment]
@faho yes, I'm reconsidering. I added [an info/warning message](https://github.com/fish-shell/fish-shell/commit/dfcf140e00c323953cf55a1829d14627a779f546), but it might be worth re-adding the keepalive hack. We can also detect the WSL version and use it conditionally.

**Comment by faho** [comment]
@mqudsi: Hey, how did this end up? Did you put back the keepalive hack, or is the warning sufficient by now (I think 1809 is back?)?

This seems important for 3.0 on WSL, no?

**Comment by ridiculousfish** [comment]
I don't think we should add back the keep alive hack, it is an invasive change that won't receive a lot of testing. As a general principle we should only support the most recent WSL, at least until it stabilizes.

**Comment by mqudsi** [comment]
Yes, I think dfcf140e00c323953cf55a1829d14627a779f546 is enough.

@faho you are correct, the 1809 rollout was resumed mid-November.

**Comment by Jitsusama** [comment]
I'm running into this issue and am force on Windows 10 1803 due to corporate IT policies regarding updates. I'm utilizing WSL and the Fish PPA repository. Is there some way I can get a version of Fish 3.0 that doesn't have this issue in this environment?

**Comment by mqudsi** [comment]
Even old releases of fish are broken under those WSL versions. It just didn't warn you.

**Comment by Jitsusama** [comment]
Thanks for the heads up.
