### ISSUE TITLE
fish could get speed boosts by changing how syntax checking is done

### ISSUE THREAD

**Issue by Appadeia** [fish-shell/fish-shell#5305]
After running some scripts to compare fish with other shells, fish has always been extremely slower.
Here's an [asciinema](https://asciinema.org/a/SFSFn7oUewjDgv68U5O5Ei3T5) of the test script. This is being run by a user with no configuration files, so all shells are stock, more or less. The Fish shell was compiled from the git repo as of [this commit](https://github.com/fish-shell/fish-shell/commit/b23bda8ed6ea8d9c17dbabe3d0e5e3f52fe2b820). The script can be found [here](http://termbin.com/wnhn).

After poking through the source a bit, and talking with other people on Discord, it seems that a fair amount of the execution time is redundant syntax checking. As far as I and some other people are able to tell, the syntax checker seems to be called for every command, rather than the script as a whole. So a simple `for i in (seq 1 10000); [ 1 = 1 ];end` loop would need to call the syntax checker around 10000 times. 

That doesn't seem efficient. It would probably be a lot faster if it was just called once per script.

![callgraph](https://cdn.discordapp.com/attachments/257592796704145429/507313507981721603/fish.png)
*Callgraph*
Judging by the callgraph, actual execution of commands takes up half than less the time here. *I'm not the best at interpreting callgraphs and the actual functions being run, so check for yourself.*

[Here's a link to the callgrind.out](https://cdn.discordapp.com/attachments/257592796704145429/507317499336065024/callgrind.out.15836).

I love using Fish shell, but the slowness means that I often use lots of `bash -c ""` statements and tempfiles rather than native Fish alternatives to not be cripplingly slow.

**Comment by mqudsi** [comment]
Great job with the `math` builtin, @faho! That really pays off with `offset + 1` calculations or `set i (math i + 1)` in a loop.

I didn't realize master was that much faster than 2.7.1 across the board, though. That's rather nice.

**Comment by faho** [comment]
Okay, there's a bit of a misunderstanding here.

@Appadeia: That stuff called "parser_*" isn't all purely parsing in the traditional sense. Shells are highly dynamic and have to interleave parsing and execution. 

For instance of the 12.19% spent in `parse_execution_context_t::run_for_statement()`, most is actually spent in setting up environment variables. In particular the loop variable $i.

That's necessary work, and can't all be done upfront.

Which makes this boil down to "make faster", which is just always a goal and doesn't need a particular open issue.

-------

What I would like to know is when you find `bash -c` to be faster? I took the liberty of looking through your dotfiles, and found https://github.com/Appadeia/dotfiles/blob/master/fish/fish/functions/__sf_section_git.fish#L27:

```fish
if bash -c "git status --porcelain > /dev/null 2>&1"
		set git_count (git status --porcelain | wc -l)
		set git_count " $git_count"
end
```

Now, from my experience there's basically no way starting bash to then just start git is going to be any faster, and testing confirms - 6ms from fish vs 10ms bash+git.

What _would_ save about half the time here is to use `set` together with a command substitution:

```fish
if set -l git_count (git status --porcelain 2>/dev/null)
    set git_count " "(count $git_count)
end
```

In my tests the former takes 18ms, while this takes 6ms, and the difference should only become more pronounced in larger git repositories.

**Comment by faho** [comment]
Okay, the idea here doesn't seem applicable to me, so this boils down to "make faster", which we don't need an open issue for. Closing!
