### ISSUE TITLE
Env completions don't allow files for variables

### ISSUE THREAD

**Issue by jordansamuels** [fish-shell/fish-shell#5306]
Hi, I may be missing something but it looks like this bug (https://github.com/fish-shell/fish-shell/issues/2178) is back in fish 2.7.1 or an intervening version, after it was fixed in https://github.com/fish-shell/fish-shell/commit/85dad6913e77d81730f3aea478695429f441ebd5?  

Here are repro steps:
```
docker run -ti --entrypoint bash ubuntu:latest
# apt-get update
# apt-get install fish
# fish
% env var=/usr<TAB>
```
Also fails on OSX.

**Comment by faho** [comment]
Not quite. The env completion script disables file completion in this case:

```fish
complete -c env -n 'not __fish_complete_env_subcommand' -a "(set -n)=" -x
```

And for a while, we did file completion if nothing else was offered, so this didn't take effect until #112.

We should probably allow files here, since we do for `set` and it might just be what you're looking for.
