### ISSUE TITLE
Add pcre2 style for `string escape`

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5309]
There are quite a few times when I am working on completion scripts that need to filter by the start of a value that I end up having a choice between using `string match -a foo` and getting too many results or `string match -r ^foo` and risk the unknown/dynamic contents of `foo` not being pcre2-safe.

There should be a `--style pcre2` option for `string escape` that would take unknown/unsafe content and escape it for use in a regex match.

**Comment by faho** [comment]
I've thought about this a bunch.

I believe requiring everyone to use `string escape` correctly every time is a bit much to ask.

I'd rather we had a "--prefix" option that made it so we just matched the start as if `foo*` was given, without interpreting additional glob characters. Similarly `--suffix` and `--literal` or `--equal` (since "--entire" is already taken) would be nice.

**Comment by faho** [comment]
Alternatively, it might be possible to add a "--argument=" option to allow inserting literal arguments, but that would require a placeholder. With `{}`:

```fish
string replace -r '^{}` --argument=".*banana^" -- $argv
```

Specifying "--argument" multiple times will match them to the placeholders in-order.

That's a bit more ambituous, and `--prefix` would presumably solve 95.4% of the issue.

**Comment by mqudsi** [comment]
I like the placeholder idea but don't think that extending plaintext search (which I'm not _against_) is sufficient because there will always be a need to pattern match against dynamic content (e.g. match `--foo` where `foo` is dynamic).

**Comment by ridiculousfish** [comment]
`string --index` returns the index of the match, is testing that against 0 not sufficient?

**Comment by mqudsi** [comment]
@ridiculousfish sure, that works for the specific example highlighted, but it really doesn't address the root problem (and neither do @faho's suggestions for worthy extensions to `string`). For example, today I needed to replace a programmatically generated string but only if it's at the end of an input.

Actually, I don't think `string match --index` would help here either if the goal were the end of the string, you'd need to subtract the index from the length of the string to determine whether or not the match were at the end.

I'm surprised `pcre2.h` doesn't offer a `pcre2_escape` function.
