### ISSUE TITLE
Document color options properly.

### ISSUE THREAD

**Issue by crocket** [fish-shell/fish-shell#5314]
* I didn't know that the background color of `fish_color_search_match` sets the background color for the selected item in the completion pager. The documentation doesn't say this.

![2018-11-04_sun_06 21 33](https://user-images.githubusercontent.com/748856/47960959-58ae8e00-e045-11e8-9738-531b1bfca7e8.png)

* The font for the selected item in the pager becomes bold in some circumstances. I don't know when and why it becomes bold. According to my test, if I set `fish_pager_color_completion` to something other than `normal` that has bright variant, the selected item of a pager becomes bold.

**Comment by crocket** [comment]
I will think about submitting a pull request when I figure out when fonts become bold in a completion pager.

**Comment by floam** [comment]
> The font for the selected item in the pager becomes bold in some circumstances. I don't know when and why it becomes bold.

It's hardcoded (https://github.com/fish-shell/fish-shell/blob/master/src/output.cpp#L277) for internal parts of fish (not `set_color`) where a background color is used, for example the selected item in the pager or the pager progress bar. Ostensibly to make things easier to read. I don't really like that.
