### ISSUE TITLE
Improve Solarized Light and Solarized Dark

### ISSUE THREAD

**Issue by crocket** [fish-shell/fish-shell#5315]
I chose solarzied light and solarized dark from fish_config and made changes to `fish_color_search_match`, `fish_pager_color_completion`, and `fish_pager_color_prefix` to make the completion pager more readable.

Variables for solarized light

```
__fish_classic_git_prompt_initialized
__fish_init_2_39_8
__fish_init_2_3_0
fish_color_autosuggestion 93a1a1
fish_color_cancel -r
fish_color_command 586e75
fish_color_comment 93a1a1
fish_color_cwd green
fish_color_cwd_root red
fish_color_end 268bd2
fish_color_error dc322f
fish_color_escape 'bryellow'  '--bold'
fish_color_history_current --bold
fish_color_host normal
fish_color_match --background=brblue
fish_color_normal normal
fish_color_operator bryellow
fish_color_param 657b83
fish_color_quote 839496
fish_color_redirection 6c71c4
fish_color_search_match 'bryellow'  '--background=white'
fish_color_selection 'white'  '--bold'  '--background=brblack'
fish_color_status red
fish_color_user brgreen
fish_color_valid_path --underline
fish_greeting 'Welcome to fish, the friendly interactive shell'
fish_key_bindings fish_default_key_bindings
fish_pager_color_completion green
fish_pager_color_description 'B3A06D'  'yellow'
fish_pager_color_prefix 'cyan'  '--underline'
fish_pager_color_progress 'brwhite'  '--background=cyan'
```

Variables for solarized dark

```
__fish_init_2_39_8
__fish_init_2_3_0
fish_color_autosuggestion 586e75
fish_color_cancel -r
fish_color_command 93a1a1
fish_color_comment 586e75
fish_color_cwd green
fish_color_cwd_root red
fish_color_end 268bd2
fish_color_error dc322f
fish_color_escape 'bryellow'  '--bold'
fish_color_history_current --bold
fish_color_host normal
fish_color_match --background=brblue
fish_color_normal normal
fish_color_operator bryellow
fish_color_param 839496
fish_color_quote 657b83
fish_color_redirection 6c71c4
fish_color_search_match 'bryellow'  '--background=black'
fish_color_selection 'white'  '--bold'  '--background=brblack'
fish_color_user brgreen
fish_color_valid_path --underline
fish_greeting 'Welcome to fish, the friendly interactive shell'
fish_key_bindings fish_default_key_bindings
fish_pager_color_completion cyan
fish_pager_color_description 'B3A06D'  'yellow'
fish_pager_color_prefix 'cyan'  '--underline'
fish_pager_color_progress 'brwhite'  '--background=cyan'
```

**Comment by mqudsi** [comment]
@crocket would you like to open a pull request with the relevant changes?

**Comment by crocket** [comment]
I would. But, would it require modifying color code so that I can specify fish_color_search_match, fish_pager_color_completion, and fish_pager_color_prefix in color themes?

**Comment by crocket** [comment]
I tried to fix this issue by myself. But, the color code is too difficult for me.

**Comment by faho** [comment]
@crocket: The solarized themes are defined https://github.com/fish-shell/fish-shell/blob/master/share/tools/web_config/js/colorutils.js#L268-L306. Have you tried adding lines like `search_match : "bryellow"` to that?

That doesn't seem all that complicated?

**Comment by crocket** [comment]
1. I want to set the background of `search_match`. The current codebase can't do it without refactoring.
2. Setting `fish_pager_color_completion` and `fish_pager_color_prefix` is going to require more refactoring.

**Comment by faho** [comment]
>The current codebase can't or is not supposed to set the background color without refactoring

Yes it can. Just add it to the string, with "--background=".

>Setting fish_pager_color_completion and fish_pager_color_prefix is going to require more refactoring.

Indeed.

**Comment by crocket** [comment]
You set `fish_pager_color_*` directly in the color themes. Does fish process this properly? Or, is it just a reminder for the future?

**Comment by floam** [comment]
Can you provide a screenshot of how this is supposed to look, @crocket?
