### ISSUE TITLE
got syntax error with `math`

### ISSUE THREAD

**Issue by efazati** [fish-shell/fish-shell#5324]
```
fish, version 2.7.1

$ uname -a
Linux ME 4.15.0-36-generic #39-Ubuntu SMP Mon Sep 24 16:19:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ echo $TERM 
rxvt-256color
```

when I use multiply in math I got syntax error but + and - work probebly 
what you think?

```
$ math 5 * 4
(standard_in) 1: syntax error

```

**Comment by faho** [comment]
The "*" is the glob character. That means it will expand to all files in the current directory. At which point it's not a valid math expression anymore.

You need to quote it, like `math "5 * 4"`.

**Comment by efazati** [comment]
Thanks it worked :+1:
