### ISSUE TITLE
`man` command throws extra error info if it does not exist

### ISSUE THREAD

**Issue by meain** [fish-shell/fish-shell#5329]
fish version : `2.7.1`
uname -a : `Linux ad391270d4b7 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64 GNU/Linu` (docker `archlinux/base` image)

Man command might not exist and that will through an output something like this 

```
root@ad391270d4b7 /# man man
fish: Unknown command 'man'
/usr/share/fish/functions/man.fish (line 23):
    command man $argv
            ^
in function “man”
    called on standard input
    with parameter list “man”
```

instead of just 
```
fish: Unknown command 'man'
```

Might want to check if man exists in https://github.com/fish-shell/fish-shell/blob/master/share/functions/man.fish

**Comment by zanchey** [comment]
More work done on this in 59197d12e0ef3a59fa8232bf788a858097b93696.
