### ISSUE TITLE
Tab auto-completion's suggestions list displays improperly (mintty, cygwin, ssh)

### ISSUE THREAD

**Issue by joeyfernau** [fish-shell/fish-shell#5331]
When the text has reached the bottom of the terminal, auto-completion's suggestions list moves the cursor up to make room for the list, and it prints suggestions over top of previously entered commands. 

It really is quite disorienting: [image](https://i.imgur.com/D0CHXrN.png).

Fish version: 2.2.0
OS: Linux 4.4.0-128-generic # 154-Ubuntu SMP Fri May 25 14:15:18 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Terminal: cygwin

I've `ssh`d into my Linux machine through Cygwin's `mintty` (running within Windows 10). I tried running `sh -c 'env HOME=$(mktemp -d) fish'`; the issue persists. The issue only starts to occur once the output of the suggestions list hits the bottom of the terminal screen and wraps around back to the cursor position (e.g. in the attached image, the cursor was lifted up to the top of the screen, but it does not always get lifted there).

A partial solution for this issue is to allow for some mechanism to disable the auto-completion list. I made the following comment for issue #4473:
> I'd like to disable it because my terminal emulator does not fare well with it; changing the color to black will still emit the characters to the terminal emulator. It is not a solution in my case (even though it is a solution for people with better terminals).
> 
> Also, getting a better terminal is not always an option. For instance, one may only be able to ssh into their desired environment. They may be limited locally with respect to their choice of a terminal.

**Comment by joeyfernau** [comment]
@faho, thanks! I'll update when I get the chance to (probably this week).

**Comment by faho** [comment]
@joeyfernau: Ping?
