### ISSUE TITLE
Wrapped functions create ghost `complete` entries

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#5334]
On master, run: 
```fish
function foo --wraps foo
    echo foo
end
```
Now run `complete`, you will witness 'empty' entries added along with the correct ones:

```fish
$ complete
...
complete --command  --wraps 
complete --command foo --wraps foo
```

Didn't occur in 2.7.1.

**Comment by floam** [comment]
@mqudsi Bisects to 3cda5ac59be2e603d0319417f13a107a6a4f997c

**Comment by faho** [comment]
This seems to be entirely benign, so it doesn't seem critical for the 3.0 beta.

**Comment by floam** [comment]
Yeah, it's not a big deal. Even if you did `eval` the `complete` output, those lines wouldn't actually break anything. I definitely don't mean that the first beta should be delayed for a fix.

My reflex for any regression introduced between releases was just to milestone it for the next release.

**Comment by krobelus** [comment]
Seems to be fixed
