### ISSUE TITLE
`forward-bigword` command misbehaving with autosuggestions

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#5336]
```
$ fish --version
fish, version 2.7.1-1680-g7257c699
```

I have the following keybindings set up:
```
alt+right  : forward-word
ctrl+right : forward-bigword
```

They work correctly for regular commandline arguments, however the `forward-bigword` keybinding acts as `forward-word` when used with autosuggestions, i.e. in the following screenshot, when pressing the `forward-bigword` keybind, I'd expect the cursor to be moved to the right of the letter `j`:

![image](https://user-images.githubusercontent.com/8544900/48408526-70ff6680-e731-11e8-8e85-4768ab23078b.png)

But instead it behaves as `forward-word` and moves to the right of the letter `e`.

**Comment by faho** [comment]
Yup. The issue here is that "accept_autosuggestion" (in reader.cpp) only takes a bool to decide if it should accept _all_ of the suggestion, or only one word.

Instead, it should probably get the move_word_style, like the actual movement in the "active" commandline does.
