### ISSUE TITLE
Consider coloring ip output

### ISSUE THREAD

**Issue by exploide** [fish-shell/fish-shell#5340]
For me, the main benefit of fish is it's sane default configuration. E.g. `grep` output is colored by default. :+1:

Today, I realized that the output of `ip` can be colorized too, by calling `ip -c`, which greatly improves readability.

Would it make sense for fish to make this the default?

**Comment by mqudsi** [comment]
That does drastically improve the speed of finding the most important info in the output, thanks for teaching me about that @exploide!

**Comment by mqudsi** [comment]
@exploide why don't you submit a PR modelled after `grep.fish`?

**Comment by exploide** [comment]
Usually I'm waiting for feedback from maintainers to see if the proposal is appreciated.

I'll conduct a PR soon :P

**Comment by exploide** [comment]
That was fairly easy :yum: 

See #5356

**Comment by exploide** [comment]
Contrary to my last comment, it turned out it is not that easy for reasons explained in #5356.

If I understand correctly, this is currently blocked by #1396.

After #5635 was fixed by 5eade35 at least `ip monitor | command grep dev` works now. However `ip monitor | grep dev` still does not work when using the colored ip fish function. So maybe we really need to wait for #1396.

**Comment by zanchey** [comment]
@krobelus, I suggest backing this out due to the breakage identified in the [comments above](https://github.com/fish-shell/fish-shell/issues/5340#issuecomment-487144739).

**Comment by faho** [comment]
Reverted as cf4f8ae929f05f9a794bd329de3599918dc95aab (also in Integration_3.2.0)

**Comment by krobelus** [comment]
my bad, I thought the breakage was because of piped `isatty` :facepalm:

**Comment by exploide** [comment]
Meanwhile, iproute2 got a [compile-time option](https://github.com/iproute2/iproute2/commit/5e704f4b5ba20700a7b379781a219e6247cac72c) to set the coloring behavior as the package maintainer likes.

Fedora uses this to set coloring to auto. Debian will do so in the next release, too. I think other distributions should also do this.

This is the better and shell-independent solution. Works for me :)
I'm fine with closing this but feel free to reopen.
