### ISSUE TITLE
Fish no longer gracefully handles "deleted" directories when cd'ing

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#5341]
```
$ fish --version
fish, version 2.7.1-1691-gf56c317b
```

In previous versions of fish (presumably prior to the ["virtual PWD"](https://github.com/fish-shell/fish-shell/commit/786c0c5abb936eeb10eae45b508132a313bc8abc) changes), when the current working directory was deleted, fish would fall back to the closest directory which still existed.

This is relatively common for me as I switch between Git branches and sometimes a directory which existed on the previous branch no longer exists in the current branch. The old behaviour meant I could continue working in my current session, but the new behaviour means I have to launch a completely new session or `cd` to the absolute path that still exists, which I sometimes don't even know, depending on the level of nesting directories I'm in.

**Previous Behaviour (fish 2.7.1)**
```
$ cd (mktemp -d)
$ mkdir -p a/b/c
$ cd a/b/c
$ pwd
/var/folders/_0/wrr145xs4nj6b_8lncqmp9mm0000gn/T/tmp.mmj1Z9VijH/a/b/c
# rm -rf directory `c` from a new tab
$ cd ..
<E> fish: getcwd() failed with errno 2/No such file or directory
$ pwd
/var/folders/_0/wrr145xs4nj6b_8lncqmp9mm0000gn/T/tmp.mmj1Z9VijH/a/b
```

**New Behaviour**
```
$ cd (mktemp -d)
$ mkdir -p a/b/c
$ cd a/b/c
$ pwd
/var/folders/_0/wrr145xs4nj6b_8lncqmp9mm0000gn/T/tmp.mmj1Z9VijH/a/b/c
# rm -rf directory `c` from a new tab
$ cd ..
cd: The directory '..' does not exist
$ pwd
/var/folders/_0/wrr145xs4nj6b_8lncqmp9mm0000gn/T/tmp.mmj1Z9VijH/a/b/c
```

**Comment by faho** [comment]
Huh? This works for me on linux.

Is there some OS-specific behavior here? Or did you override the `cd` function?

**Comment by zx8** [comment]
I'm using macOS High Sierra (10.13.6) and I haven't modified `cd':

```
› type cd
cd is a function with definition
# Defined in /usr/local/Cellar/fish/HEAD-f56c317/share/fish/functions/cd.fish @ line 4
```

**Comment by faho** [comment]
For me, I see this:

```
/tmp► mkdir -p a/b/c
/tmp► cd a/b/c/
/tmp/a/b/c► pwd
/tmp/a/b/c
/tmp/a/b/c[128]► env LC_ALL=C git status
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
/tmp/a/b/c[128]► # rm -rf c from another tab
/tmp/a/b/c[128]► env LC_ALL=C git status
fatal: Unable to read current working directory: No such file or directory
/tmp/a/b/c[128]► ls
/tmp/a/b/c► cd ..
/tmp/a/b► pwd
/tmp/a/b
```

This is with 2.7.1-1690-g1fffdbce7 (which is code-wise identical to yours, the addtional commit is just a change to CHANGELOG.md).

**Comment by floam** [comment]
I can reproduce this on macOS 10.14, if and only if I `set -e CDPATH`. If it's set to a path, it fails as shown above.

**Comment by floam** [comment]
I'll note that `/var/` is a symlink to `/private/var` on macOS. Likely relevant.

Also does this if the directory has been deleted:
```

**Comment by zx8** [comment]
> I'll note that /var/ is a symlink to /private/var on macOS. Likely relevant.

Don't think it's relevant – I tested with `~/Desktop` and observed the same behaviour.

Also my `CDPATH` isn't set:

```
$ set -q CDPATH; or echo unset
unset
```

**Comment by faho** [comment]
> If it's set to a path, it fails as shown above.

I imagine you mean "if CDPATH is set, `cd ..` works"?

$CDPATH does not make a difference for me. With or without, it works.

And going by the code, I have no idea why $CDPATH would make a difference.

The way this goes:

In builtin_cd.cpp:

```c++
    if (argv[optind]) {
        dir_in = argv[optind];
    } else { # ...
    }
#...
    if (!path_get_cdpath(dir_in, &dir)) {
        if (errno == ENOTDIR) {
            streams.err.append_format(_(L"%ls: '%ls' is not a directory\n"), cmd, dir_in.c_str());
#...
```

where `path_get_cdpath` is in path.cpp, and goes like:

```c++
    if (dir.at(0) == L'/') {
        // Absolute path.
        paths.push_back(dir);
    } else if (string_prefixes_string(L"./", dir) || string_prefixes_string(L"../", dir) ||
               dir == L"." || dir == L"..") {
        // Path is relative to the working directory.
        wcstring path;
        if (!wd.empty()) path.append(wd);
        path.append(dir);
        paths.push_back(path);
    } else {
        // Respect CDPATH.
#...
   }
#...
    bool success = false;
    for (const wcstring &dir : paths) {
        struct stat buf;
        if (wstat(dir, &buf) == 0) {
```

So $CDPATH should never be checked, because `string_prefixes_string(L"../", dir)` is definitely true!

-------

This would be explained by `stat("..", &buf)` returning different things on Linux and macOS in this case.

(@floam: The `realpath` thing is a good catch, but a different issue)

**Comment by floam** [comment]
> I imagine you mean "if CDPATH is set, cd .. works"?

Yes. My bad.

**Comment by floam** [comment]
`$CDPATH` really does determine if it crashes or works fine though. No fooling.

**Comment by floam** [comment]
> So $CDPATH should never be checked, because string_prefixes_string(L"../", dir) dir == L".." is definitely true!

dir is `.`:

```patch
bool path_get_cdpath(const wcstring &dir, wcstring *out, const wcstring &wd,
                     const env_vars_snapshot_t &env_vars) {
    int err = ENOENT;
    if (dir.empty()) return false;

    assert(wd.empty() || wd.back() == L'/');
+    debug(0, L"%s", dir.c_str());

    wcstring_list_t paths;
    if (dir.at(0) == L'/') {
        // Absolute path.
        paths.push_back(dir);
```

```
~/D/a/b/c $ cd ..
<E> fish: .
cd: The directory '..' does not exist
```

**Comment by faho** [comment]
@floam: It's a wcstring (i.e. a string<wchar_t>), so you need `%ls` in the format string.

**Comment by floam** [comment]
Doh.

>Doesn't matter though, since the CDPATH path should still not be taken since there's also a dir == L"." there. 
Yeah, I just thought that was surprising and inexplicable.

**Comment by floam** [comment]
I thought unsetting CDPATH was "fixing" it, because after I unset it, I could do a cd .. successfully. Turns out, the second attempt always just succeeds to change the directory.

**Comment by floam** [comment]
This only happens on APFS. It also only happens if I'm cd'd in with fish. I can't reproduce with bash. I'm very confused.

```
~/a/b/c $ stat ..
stat: ..: stat: No such file or directory
~/a/b/c [1] $ stat ..
16777221 8628494056 drwxr-xr-x 2 floam staff 0 64 "Nov 15 09:26:15 2018" "Nov 15 09:26:09 2018" "Nov 15 09:26:09 2018" "Nov 15 09:10:33 2018" 4096 0 0 ..
```

**Comment by floam** [comment]
Whatever the reason it didn't happen in bash, it's to do with it using a builtin. `/usr/bin/stat` does the same thing in bash that it does in fish.

**Comment by ridiculousfish** [comment]
This repros for me on 10.13 but NOT on 10.14.

**Comment by zx8** [comment]
I'm using 10.14 on my other laptop and can reproduce it as described in the OP.

I'm downloading the 10.14.1 update so will check again when it's finished later. @ridiculousfish Are you using 10.14 or 10.14.1?

**Comment by ridiculousfish** [comment]
I am using 10.14.

@zx8 if you replace `cd` with `builtin cd` does it still repro? This fixes it for me. But bizarrely even if I `functions --erase cd` it still repros with `cd ..` and NOT with `builtin cd ..`. Extremely strange.

**Comment by floam** [comment]
I'm reproducing it on 10.14.2 beta 18C38b.

**Comment by zx8** [comment]
> @ridiculousfish [...] replace `cd` with `builtin cd` does it still repro?

Repros with both for me.

**Comment by floam** [comment]
Are you using APFS on both 10.13 and 10.14, @ridiculousfish?

**Comment by ridiculousfish** [comment]
Yes, APFS.

**Comment by ridiculousfish** [comment]
I think this is a funny race between the directory being unlinked and actually removed. The use of `path_get_cdpath` in `builtin_cd` looks somewhat bogus to me.

**Comment by ridiculousfish** [comment]
This is quite annoying to fix because we can't just normalize the path. That is, `cd ./not_a_directory/..` should not succeed. It's only if the working directory is missing, that it should succeed.

**Comment by ridiculousfish** [comment]
@zx8 @floam can you please try with #5347 ?
