### ISSUE TITLE
Builtin jobs with failed redirections aren't removed correctly

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5346]
fish, version 2.7.1-1699-g7b21f1c3

I used https://github.com/fish-shell/fish-shell/wiki/Nightly-builds to install the latest version on debian 9 (first time)

I have two errors when connecting:

1) When I connect, it tells me this error related to https://github.com/oh-my-fish/plugin-sudope
`sudope: The requested sequence is already in use: --preset \cs pager-toggle-search`

I suppose it means that the ctrl+s hotkey is now taken by something else called "pager-toggle-search", right? what does it do though? and why isn't my plugin overriding it?

2) When I connect to my container in SSH, I have 2 background jobs immediately started. If I try to reload, I get this msg:
```
Reload aborted. There are background jobs:

Job	Group	CPU	State	Command
12	-2	0%	running	string replace -r '\|.*' '' < $Z_DATA | string escape

```

If I try to exit, I have to type "exit" twice. Very annoying

If I type `jobs`:
`12	-2	0%	running	string replace -r '\|.*' '' < $Z_DATA | string escape`

If I type `ps -eaf | grep "string escape"`:
 `my_cont+ 32438 31405  0 19:11 pts/2    00:00:00 grep --color=auto string escape`

the process id keeps changing too

This happened also on last official 2.7.1 but only on my remote debian 9 container

**Comment by faho** [comment]
>When I connect, it tells me this error related to https://github.com/oh-my-fish/plugin-sudope

Yup. We have bound \cs now, so the sudope people need to update their stuff. Preferably they should switch to a different sequence by default, but they could also just overwrite our binding, or they could leave it to the user to pick.

Your workaround: `set -g sudope_sequence somethingunused`.

The other thing is from https://github.com/jethrokuan/z, I have no idea why or how it runs `string` in the background. Let's see if I can find something.

**Comment by faho** [comment]
@BarbzYHOOL: In your container, what is $Z_DATA set to?

**Comment by BarbzYHOOL** [comment]
For the Z error:

omg I forgot to tell that I had another error (mostly because my fish_greetings is big so I didn't see it):

<W> fish: An error occurred while redirecting file '/home/my_container/.local/share/z/data'
open: Permission denied

So it was an error from me, and $Z_DATA points to this dir. I just need to set correct permission. Sorry :(

-----------

For sudope:

How can I overwrite? I could add it to the plugin's code directly

And what is the "pager-toggle-search" about? I typed "funced pager-toggle-search" and it is empty

**Comment by faho** [comment]
>How can I overwrite? I could add it to the plugin's code directly

Look at the plugin's key_binding.fish (https://github.com/oh-my-fish/plugin-sudope/blob/master/key_bindings.fish). Should be pretty self-explanatory.

>And what is the "pager-toggle-search" about? I typed "funced pager-toggle-search" and it is empty

It's a proper bind function, implemented in c++ directly. If you have the pager open (the thing that lets you pick completions), activate that function (by pressing ctrl-s) and then you can search the pager. Previous fish versions automatically searched, the new behavior is to close the pager and let you change the commandline instead.

**Comment by faho** [comment]
>So it was an error from me, and $Z_DATA points to this dir. I just need to set correct permission. Sorry :(

Ooh, no, that's actually relevant. It seems when the redirection fails we no longer quit the job correctly. @mqudsi?

Easy way to reproduce: `true < /banana`

**Comment by BarbzYHOOL** [comment]
Yeah, for `true < /banana`

For pager function, ok I tried it and the ctrl+s starts only if you start selecting an item, else it does nothing. I don't get how it worked on the previous version though (I have both versions on diff OS).
Also, is there a list of all the functions and their use-case somewhere? without having to read the code :D

**Comment by faho** [comment]
>Also, is there a list of all the functions and their use-case somewhere?

`help bind`.

**Comment by mqudsi** [comment]
Ugh, don't call `fg` after the job fails. I called it out of habit when I got the 

>There are still jobs active:
>
>   PID  Command
>     0  true </banana

message, and the shell just hangs indefinitely since we're waiting on a job that doesn't exist to exit.

**Comment by BarbzYHOOL** [comment]
@faho there is nothing about `pager-toggle-search` :'(

**Comment by faho** [comment]
@BarbzYHOOL: Did you build the documentation locally (which requires doxygen)? If not, `help` will open the online version, which is always at the latest _release_. Since pager-toggle-search was added after 2.7.1, those docs obviously don't include it.

Anyway, there's not a lot https://github.com/fish-shell/fish-shell/blob/master/doc_src/bind.txt#L128:

>`pager-toggle-search`, toggles the search field if the completions pager is visible.

**Comment by BarbzYHOOL** [comment]
no I didn't

ok ty, but are these all the functions I would need to look at in fish? actually everytime i need to look at a fish function it was for a bind I guess so it solves this need, but maybe there are other functions described somewhere else?
