### ISSUE TITLE
Exporting EDITOR with arguments breaks on import

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#5348]
As observed in #5258:

    > set -Ux EDITOR emacs -nw
    > ./fish
    > $EDITOR ~/file.txt

This fails because the exported universal variable is imported as a single word, not a list.

**Comment by neersighted** [comment]
What's the usual expected behavior for exported lists in non-fish children, by the way?

I would expect `set -gx MY_LIST "of space" separated values` to result in `$MY_LIST` with a value of `"of space separated values"` in children, as this is the least surprising behavior, but I suppose that loses information for child fish shells.

**Comment by neersighted** [comment]
Ultimately I think losing information is fine, and less surprising than the current separator behavior (this is what bash does here). Exporting lists is a niche I think, and exporting them to children even more so. As long as the inherited variable is correctly imported (with whitespace), I don't think users will be surprised.

**Comment by faho** [comment]
And allow me to clarify: Universal variables aren't necessary here.

The same thing happens with `set -gx EDITOR emacs -nw`. The problem is with export/import, not uvars.

**Comment by ridiculousfish** [comment]
In fish 2.7, `set -gx EDITOR emacs -nw` would export using array separator which is probably worse than exporting with spaces.

**Comment by faho** [comment]
Exporting with array separators is worse when the child is not fish, but better when it is.

Exporting with spaces is better when the child isn't fish, but worse when it is.

Unless we can figure out some scheme to solve both cases, this is a tradeoff. And I can't come up with one that doesn't have some weird edge-cases. For example we could have a separate variable that includes splitpoints - $FISH_SPLITS with a value like "EDITOR:5;PAGER:7", but that would break if there is another process in between the two fishes that changes the value, and it would break in _weird_ ways. Alternatively we could export the variables in both forms ("$EDITOR" and "$EDITOR_LIST"), but that would show up in non-fish children, and could also go out of sync.

I would imagine that having a child fish is fairly unusual, having a child fish using imported variables even more so, so it's possible that we should simply live with this issue.

**Comment by floam** [comment]
In ksh, if you export an array, only the first element will be seen by the child process. I think this is not terrible, because flattening things quietly is just likely to cause trouble. It's up to the user to get what they need into the first element.

In bash, you can export a bash function. It works in a child process:
```shell
bash-3.2$ fn() { echo hi there $1; }; 
bash-3.2$ export -f fn
bash-3.2$ fish
fish ~ $ env
env
...
BASH_FUNC_fn%%=() {  echo hi there $1
}
...
fish ~ $ bash
bash-3.2$ fn foobar
hi there foobar
```

Maybe we could do something like this. First element exported in the variable name, plus some kind of prefixed `$FISH_VAR_` variable with special encoding for the separators that fish knows to look for.

**Comment by floam** [comment]
(The %%'s are purposeful: shells will generally not let you have a variable name like that. Fish tries to complete it, but it can't be expanded.)

**Comment by faho** [comment]
>In ksh, if you export an array, only the first element will be seen by the child process. I think this is not terrible, because flattening things quietly is just likely to cause trouble. 

That only really works because of wordsplitting. I've said this before: The reason to keep $EDITOR as a list with two elements is because that allows you to use it as a variable.

```fish
$EDITOR /some/file
# becomes
emacs -nw /some/file
#instead of
"emacs -nw" /some/file
```

>In bash, you can export a bash function

Yeah, that's what directly lead to shellshock.

**Comment by floam** [comment]
Sorry, how does word splitting factor into it?

**Comment by faho** [comment]
>Sorry, how does word splitting factor into it?

If I `set EDITOR emacs -nw`, then I can do `$EDITOR /some/file`. If I do `set EDITOR "emacs -nw"` I can't, because fish doesn't split it. In ksh, I could do `EDITOR="emacs -nw"` and `$EDITOR /some/file`, because it splits it. So I don't really _have_ to use an array here, so exporting it as one element is alright.

**Comment by floam** [comment]
I'm talking about arrays.

**Comment by faho** [comment]
I know. I'm talking about ksh not needing arrays for common cases for $EDITOR et al, because of word splitting.

**Comment by floam** [comment]
I was referring to the behavior ksh93 has with exported arrays, that we might just refuse to export more than the first element.

**Comment by faho** [comment]
I know. I'm saying that ksh frequently does not need arrays, so that the export behavior isn't as important as it is for fish.

Fish needs an array for $EDITOR here, because we don't do word splitting. More than the first element needs to be exported so that child processes get the proper value.

**Comment by faho** [comment]
Another possibility: Escape spaces inside variables when exporting, and then split on spaces when importing.

Because as it stands, a $EDITOR with a space in the filename won't be understood by at least git:

```fish
set -gx EDITOR "an editor" # this is literally ~/.local/bin/"an editor"
git commit # won't find it
$EDITOR # will
set -gx EDITOR "an\ editor"
git commit # will find it
$EDITOR # won't
```

That still has the problem that we have no idea where the variable comes from.

**Comment by j-f1** [comment]
How about creating `FISH_VAR_FOO_LENGTH` and `FISH_VAR_FOO_n` variables for lists? Child fishes could read those special variables and create the list by iterating over values of `n`, while other programs could just use the space-joined string in the main variable.

**Comment by faho** [comment]
@j-f1: That's basically the same as my "$FISH_SPLITS" idea, only over multiple variables.

And the problem remains the same:

If you start any other program that then happens to start a fish, these variables become stale with no way to detect the correct state.

E.g.

```fish
$ set -gx EDITOR emacs -nw 
# sets $FISH_VAR_EDITOR_LENGTH 2,
# $FISH_VAR_EDITOR_1 emacs
# $FISH_VAR_EDITOR_2 -nw
$ bash
$ EDITOR=vim fish
$ echo $EDITOR # is it emacs or vim?
```

Plus, inheriting from other programs (e.g. your terminal) remains broken.

**Comment by faho** [comment]
>interpreting it as a shell command is a deficiency in git

Doesn't really matter, that's how it is.

And it's not just git and $EDITOR. It's also e.g. man and $PAGER.

Weirdly enough `systemctl` understands both `set -gx PAGER "a pager"` and `set -gx "a\ pager"`, but also `set -gx PAGER "less -R"`. Not sure what's going on there.

>importing them with standard whitespace splitting.

We don't typically split on whitespace, and there are a bunch more reasons to have whitespace in variables.

**Comment by ridiculousfish** [comment]
I discovered that [zsh has this same issue](https://stackoverflow.com/questions/8299610/zsh-command-not-found-for-editor) so I feel a little better about it.

**Comment by neersighted** [comment]
I agree there are plenty of reasons to have whitespace in variables, but thanks to environmental variable semantics, we either have to loose information in child fish shells, or make exported arrays incompatible with other programs.

    # personally, I prefer being able to write this
    set -gx LESS -rR -x
    # as opposed to this
    set -gx LESS '-rR -x'

The fish 3.0 behaviour is better in my opinion, and generally consistent with shell behaviour. I'm generally with @faho on this (my previous comments were evidently at an odd hour): fish should simply export arrays as a string (as we do today), and import them as a single string (as we do today).

The semantics attached to `$EDITOR` and its ilk are the result of other, non-fish programs, which essentially pass `$EDITOR` and the like straight to `execvp(3)`. I don't think there's really anything to be done here, outside of documentation, as this is expected for the vast majority of commands, and if we split on whitespace, it would be in defiance of fish's normal whitespace-splitting conventions.

**Comment by ridiculousfish** [comment]
I just ran into this with `fish_user_paths` which apparently I was exporting as a non-path variable. The experience was pretty bad since $PATH then had a single big component with spaces in it. I really hope we can figure out a more general solution.

**Comment by faho** [comment]
>I just ran into this with fish_user_paths which apparently I was exporting as a non-path variable

`fish_user_paths` should probably be a path var by default - it's used in $PATH, so it can't have colons anyway.

**Comment by faho** [comment]
Okay, I'm going to call this one. We haven't figured out any better way to handle it, so the current way stays. If anyone ever figures out something (unlikely because other shells have similar issues), then we can of course use that.
