### ISSUE TITLE
Variable interpolation in strings confused by underscores

### ISSUE THREAD

**Issue by mattmc3** [fish-shell/fish-shell#5357]
I am using fish 2.7.1. I was creating a function to make a shortcut for creating a git branch name, and ran into a problem with variable interpolation when the variables are separated by underscores. In bash if I ran into this issue, I would just surround my variables with curly braces (ie `${var}`), but fish doesn't let me do that. Here's an example of the problem:

```fish
function string_problem
  # have to do this outside the string b/c fish doesn't support evals inside a string
  set -l datepart (date '+%Y%m%d')

  # using underscores doesn't work
  set -l resultval "prefix_$datepart_$argv_suffix"

  # using dashes works
  # set -l resultval "prefix-$datepart-$argv-suffix"

  echo $resultval
end
```

If I call `string_problem abc`, the output is just "prefix_". If I use dashes, I get "prefix-20181120-abc-suffix". In bash, I could do this in a 1-liner like this:

`f(){ echo "prefix_$(date '+%Y%m%d')_${1}_suffix";};f abc`

**EDIT** Sorry all - I had this problem and could not find the answer any way I searched, [and then stumbled upon this](https://stackoverflow.com/questions/20136470/unexpected-lack-of-variable-expansion-in-fish-shell).

It appears I should just be ending my quotes like so:
`set -l resultval "prefix_"$datepart"_"$argv"_suffix"`

**Comment by faho** [comment]
Underscores are legal characters in variable names, dashes aren't. So when you do `$argv_suffix`, that looks like the variable name is "argv_suffix", not "argv" with a literal "_suffix" after it.

The solution is to stop the quotes again:

```fish
set -l resultval prefix_"$datepart"_"$argv"_suffix
```

(quoting literals doesn't make a difference, so you can safely leave them outside)

**Comment by mattmc3** [comment]
Thanks faho. I wish I found that in an FAQ in the fish docs. I appreciate the help. This resolves the issue for me.

**Comment by Darkshadow2** [comment]
You can also use curly braces in fish, but the `$` for the var has to be _inside_ them.

```fish
set -l resultval prefix_{$datepart}_{$argv}_suffix
```

Do note that they won't work inside quotes, though. If you try that, the curly braces become part of the string.

**Comment by zx8** [comment]
Side question: What's the rationale behind _not_ supporting the `${VAR}` syntax? I find the `{$VAR}` syntax more clunky and – as @Darkshadow2 pointes out – more limited, in that they can't be used inside quotes?

**Comment by j-f1** [comment]
The `{$VAR}` syntax isn’t a real syntax, it’s just the standard `{foo,bar}` syntax with only one entry.

**Comment by zx8** [comment]
@j-f1 Wow, thanks, I had never realised that! Seems obvious and makes a lot more sense as to its behaviour now. Had me confused in the past...
