### ISSUE TITLE
Reboot required to set $PATH / $fish_user_paths

### ISSUE THREAD

**Issue by dwrz** [fish-shell/fish-shell#5359]
fish version: 2.7.1
OS: Arch GNU/Linux 4.19.2 x86_64
TERM: rxvt-unicode-256color

I'm sorry that this is another question related to this topic. I've read through the other issues, but I had some puzzling behavior yesterday, and I'm trying to figure out if it's a potential bug that I should investigate, or (more likely) what it is that I don't grasp about how `fish` handles variables.

I was trying to add my global `npm` folder to `$fish_user_paths` yesterday, and mistakenly forgot to specify the `bin` directory. I was able to remove the erroneous entry, and then set the correct directory. But the changes seemed to only persist for one terminal, as soon as I opened another, the incorrect path was still there. This was the case even if I set the `universal` variable and erased the `global` one completely. 

Eventually, I rebooted, and finally it the `universal` values I'd set took over. 

1. Why did a reboot work?
2. Is that expected, or is there a way to set $fish_user_paths without rebooting?

For what it's worth, I did also try to set $PATH directly, but had similar issues.

This is the current output of `set --show fish_user_paths`:
```                                                                                                                                                                                  
$fish_user_paths: not set in local scope
$fish_user_paths: set in global scope, exported, with 3 elements
$fish_user_paths[1]: length=22 value=|/home/user/.local/bin/|
$fish_user_paths[2]: length=19 value=|/home/user/.go/bin/|
$fish_user_paths[3]: length=27 value=|/home/user/.npm-global/bin/|
$fish_user_paths: set in universal scope, exported, with 3 elements
$fish_user_paths[1]: length=22 value=|/home/user/.local/bin/|
$fish_user_paths[2]: length=19 value=|/home/user/.go/bin/|
$fish_user_paths[3]: length=27 value=|/home/user/.npm-global/bin/|
``` 

Interestingly, if I run `fish` without any plugins, and execute the same command, I get:
```
$fish_user_paths: not set in local scope
$fish_user_paths: set in global scope, exported, with 3 elements
$fish_user_paths[1]: length=22 value=|/home/user/.local/bin/|
$fish_user_paths[2]: length=19 value=|/home/user/.go/bin/|
$fish_user_paths[3]: length=27 value=|/home/user/.npm-global/bin/|
$fish_user_paths: not set in universal scope
```
Any insights, or anything I can do to help diagnose this as bug / expected behavior?

**Comment by faho** [comment]
>Is that expected

No.

Okay, most likely you have `set -g fish_user_paths` (or just `set fish_user_paths` without the "-U") somewhere in your configuration. that sets a global variable. Global variables have a "smaller" scope than universal ones, and therefore take precedence.

That means whatever change you do to the universal $fish_user_paths won't propagate to other shells, because they already have the global variable.

>This was the case even if I set the universal variable and erased the global one completely.

Did you erase it in the correct shell? The global variable is per-shell, which means it needs to be erased in every shell for which the universal is supposed to take effect. Or just remove it from your config.

**Comment by faho** [comment]
@dwrz: Ping?

**Comment by dwrz** [comment]
@faho My apologies for the late reply -- and thanks for the insights! I can't seem to find anything in my configuration that sets `fish_user_paths` except for the `fish.d` file, which I haven't touched. 

> Did you erase it in the correct shell? The global variable is per-shell, which means it needs to be erased in every shell for which the universal is supposed to take effect. Or just remove it from your config.

If I'd run `set -g fish_user_paths` by accident at some point (rather than `-U`), how would I **persistently** unset it? If I open one terminal and then unset it there, would that work? Or would I have to quit the graphical session, have only one CLI session open, and do it there? What does **every shell** mean?

**Comment by faho** [comment]
> the fish.d file, which I haven't touched.

That's the universal variable. The "fishd.SOMETHIN" file is the store for universal variables.

>If I'd run set -g fish_user_paths by accident at some point (rather than -U), how would I persistently unset it?

Global variables aren't persistent. If it shows up as a global variable, that means that something is setting it _on startup_. This is either something in the configuration (config.fish, conf.d/*.fish) or anything called by them, including plugins. Or it's inherited - your `set --show` output indicates it is exported, so it could be coming from a parent process. Anything that isn't fish is unlikely to do this, however.

But:

>Interestingly, if I run fish without any plugins, and execute the same command, I get:

I'm assuming you've done `sh -c 'env HOME=$(mktemp -d) fish'`? That fish would still inherit $fish_user_paths since it's exported. That would appear as a global variable. Try `set -eg fish_user_paths` before you start it.

-----

To have the global variable unset, you'd have to not set it. You'd have to find the code that does that and remove it.

>I can't seem to find anything in my configuration

Did you include /etc/fish and ~/.config/fish/conf.d in your search?

**Comment by dwrz** [comment]
Thanks again for your patience with this. 

I still haven't been able to find anywhere where `fish_user_paths` is set. I checked `/etc/fish` and double checked everything in `~/.config`, but still no luck.

Interestingly, this seems to still keep the `global` var:

```
user@machine ~  set --show fish_user_paths                                                                                                                                                                                          
$fish_user_paths: not set in local scope
$fish_user_paths: set in global scope, exported, with 3 elements
$fish_user_paths[1]: length=22 value=|/home/user/.local/bin/|
$fish_user_paths[2]: length=19 value=|/home/user/.go/bin/|
$fish_user_paths[3]: length=27 value=|/home/user/.npm-global/bin/|
$fish_user_paths: set in universal scope, exported, with 3 elements
$fish_user_paths[1]: length=22 value=|/home/user/.local/bin/|
$fish_user_paths[2]: length=19 value=|/home/user/.go/bin/|
$fish_user_paths[3]: length=27 value=|/home/user/.npm-global/bin/|

user@machine  ~  set -eg fish_user_paths
                                                                                                                                                                                              
user@machine  ~  set --show fish_user_paths                                                                                                                                                                                       
$fish_user_paths: not set in local scope
$fish_user_paths: not set in global scope
$fish_user_paths: set in universal scope, exported, with 3 elements
$fish_user_paths[1]: length=22 value=|/home/user/.local/bin/|
$fish_user_paths[2]: length=19 value=|/home/user/.go/bin/|
$fish_user_paths[3]: length=27 value=|/home/user/.npm-global/bin/|

user@machine  ~  sh -c 'env HOME=$(mktemp -d) fish'                                                                                                                                                                                   

Welcome to fish, the friendly interactive shell

user@machine /h/user> set --show fish_user_paths 
$fish_user_paths: not set in local scope
$fish_user_paths: set in global scope, exported, with 3 elements
$fish_user_paths[1]: length=22 value=|/home/user/.local/bin/|
$fish_user_paths[2]: length=19 value=|/home/user/.go/bin/|
$fish_user_paths[3]: length=27 value=|/home/user/.npm-global/bin/|
$fish_user_paths: not set in universal scope
```
I'll try to dig some more.

**Comment by faho** [comment]
>set in universal scope, exported

oooooohhhhh.... I missed that!

You're exporting the universal variable. Any child processes will _import_ it as a global, which is stronger than a universal (#5258).

So you have a fish somewhere as a parent process, that means every other fish already inherits it from there.

Do `set -Uu fish_user_paths $fish_user_paths`, reboot once more and it should work from then on.

**Comment by dwrz** [comment]
Looks like I'm set:
```
$fish_user_paths: not set in local scope
$fish_user_paths: not set in global scope
$fish_user_paths: set in universal scope, unexported, with 3 elements
$fish_user_paths[1]: length=22 value=|/home/user/.local/bin/|
$fish_user_paths[2]: length=19 value=|/home/user/.go/bin/|
$fish_user_paths[3]: length=27 value=|/home/user/.npm-global/bin/|
```
> So you have a fish somewhere as a parent process, that means every other fish already inherits it from there.

I'm not too sure as to the potential cause -- but I do have `fish` set as my default shell, and have this line in my `i3config`: `exec urxvt -e tmux new -s team-user`.

In any case -- many thanks!
