### ISSUE TITLE
How to clear console without exiting Python?

### ISSUE THREAD

**Issue by yiran7324** [fish-shell/fish-shell#5360]
fish, version 2.7.1

It's easy to clear the console using `clear` when you are just there, but when I launch Python and write several lines of code I find my prompt `>>>` at a very low position of the window since very time entering, this `>>>` just drops one line, eating my empty up. But I cannot do any moving-perspective things without exiting Python.

And I want to keep this `>>>` at the center level of my console or at least, find a way to clear (make the console empty) it. Is there any way to get it done?

Thanks!

**Comment by faho** [comment]
The `python` interpreter uses the readline library, the same thing that bash uses in the background.

So: Press ctrl-l.

(Also, strictly speaking this has nothing to do with fish)
