### ISSUE TITLE
`type --help` doesn't work

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#5361]
type.fish has logic to print out the help, but it's broken.

```console
$ type --help
type: Expected at least 1 args, got only 0
```

**Comment by faho** [comment]
Keeping "--help" in the options with "--min-args" would require some addition to argparse to have it recognized as a "command". I don't think that's worth it just for this.

So we either remove "--help" from the options, or we remove the "--min-args".

And considering that type without any arguments simply returns 1:

```fish
    # For legacy reasons, no argument simply causes an unsuccessful return.
    set -q argv[1]
    or return 1
```

returning 1 without error on `type --path` or `type --query` seems alright.

**Comment by floam** [comment]
Not really - we can just check for the argument ourselves before using argparse, or print help if argparse fails instead of letting argparse print its error.

**Comment by floam** [comment]
Which reminds me: Probably, printing the usage/synopsis should be what we do for our functions that are documented, if there is an argument error. We do it for the builtins with `__fish_print_help`.

**Comment by faho** [comment]
>we can just check for the argument ourselves before using argparse

Which means checking before and after argparse, in which case argparse is hindering us instead of helping.

>print help if argparse fails

We already print help too often - #3404!

**Comment by faho** [comment]
This same issue happens also for:

- funced

- funcsave

- open

- realpath (why is that function a thing?)

**Comment by floam** [comment]
(That's my bug! I don't want to stop printing usage, I just want it minimized. We should really just print the actual usage section, and that's it, and get rid of the tabs, Synopsis heading.)

**Comment by floam** [comment]
So I was going to commit this:

```patch
diff --git a/share/functions/type.fish b/share/functions/type.fish
index 32ddc4ef..8abd482e 100644
--- a/share/functions/type.fish
+++ b/share/functions/type.fish
@@ -3,15 +3,14 @@ function type --description 'Print the type of a command'
     set -q argv[1]
     or return 1
 
+    for flag in $argv
+        contains $flag -h --help && __fish_print_help && break
+    end
+
     set -l options 'h/help' 'a/all' 'f/no-functions' 't/type' 'p/path' 'P/force-path' 'q/quiet'
     argparse -n type --min-args=1 -x t,p,P $options -- $argv
     or return
 
-    if set -q _flag_help
-        __fish_print_help type
-        return 0
-    end
-
     set -l res 1
     set -l mode normal
```

There's nothing needed *after* `argparse` does its thing.

**Comment by floam** [comment]
I think your quick fix is a little less than ideal, because we do not catch missing required arguments anymore.

**Comment by faho** [comment]
>I think your quick fix is a little less than ideal, because we do not catch missing required arguments anymore.

We do for the other functions (see 
3a835eb), just not for `type`, given that that treats no arguments specially.

Your solution is what I meant when I said "remove help from argparse". You've technically left it there, but there's no way to trigger it.

So the difference is whether we let argparse check for --help, or check for missing arguments. Six of one, half a dozen of the other.

**Comment by floam** [comment]
OK, that's fine that the others work then. What's the historic reason `type` silently does that?
