### ISSUE TITLE
Nested index errors out

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#5362]
```fish
echo $list[$var[1]]
```

now errors out with "fish: Unexpected end of string, square brackets do not match". Where previously it expanded the inner variable and then used it as an index to the outer one.

`git bisect` points to f508a1f274b9ba8599cd1be7704d86bc2b75d7f2 as the culprit.

I feel like this should block 3.0.

**Comment by ridiculousfish** [comment]
Yes, that check should just be removed .Nice find.
