### ISSUE TITLE
Why this

### ISSUE THREAD

**Issue by myfreess** [fish-shell/fish-shell#5364]
ls | xargs -I{} echo "{} is in workdir"
xargs: {} is in workdir: No such file or directory
I didnt use fish syntax,just use xargs,Why?

**Comment by faho** [comment]
The `{}` looks like a brace expansion, so fish expands the "-l{}" to nothing. 

You'll have to quote it:

```fish
ls | xargs -l"{}" echo "{} is in workdir"
```

In the upcoming fish 3.0, a literal `{}` will not be expanded.

**Comment by myfreess** [comment]
Thanks @faho
