### ISSUE TITLE
Tokenization problems in command substitution

### ISSUE THREAD

**Issue by TheZeus121** [fish-shell/fish-shell#5365]
Fish version: 2.7.1
OS: Arch Linux with Linux kernel 4.19.2
The bug is reproducable without 3rd party customizations.

The problem is that when tokenizing the output from a `()` substitution, the last token gets appended any whitespace that is at the end of the substitution.

The bug in action in fish:
```fish
> cat test.cpp
#include <iostream>

int main() {
	std::cout << "hOi!" << std::endl;
	return 0;
}

> pkgconf --libs zlib
-lz 

> g++ test.cpp -lz # succeeds

> g++ test.cpp (pkgconf --libs zlib)
/usr/bin/ld: cannot find -lz 

> echo \"(pkgconf --libs zlib)\"
"-lz "

> g++ test.cpp "-lz "
/usr/bin/ld: cannot find -lz 
collect2: error: ld returned 1 exit status

> printf "\"%s\"\n" (pkgconf --libs zlib)
"-lz "
```

The same done in sh:
```sh
$ g++ test.cpp -lz # succeeds

$ g++ test.cpp $(pkgconf --libs zlib) # succeeds

$ g++ test.cpp "-lz "
/usr/bin/ld: cannot find -lz 
collect2: error: ld returned 1 exit status

$ echo \"$(pkgconf --libs zlib)\"
"-lz "

$ printf "\"%s\"\n" $(pkgconf --libs zlib)
"-lz"
```

I managed to reproduce the bug on my phone running termux (except not with `pkgconf` as they are providing `pkg-config` which strips away the whitespace after the flags), so it's not a machine-dependent bug.

**Comment by faho** [comment]
This is working as intended.

Fish does not split on space or tab, only newlines. Use `string trim` and `string split " "` as needed.

**Comment by TheZeus121** [comment]
> This is working as intended.
> 
> Fish does not split on space or tab, only newlines. Use `string trim` and `string split " "` as needed.

Oops, didn't notice that when reading the docs.

But is it explained anywhere why was this design choice made?

**Comment by faho** [comment]
>But is it explained anywhere why was this design choice made?

Because it's the right thing to do? Wordsplitting is commonly known as the single worst design choice in sh.

See how much of http://mywiki.wooledge.org/BashFAQ is dedicated to it.

90% of the time, you want to split on newlines only. Most of the remaining 10% you don't want to split at all. Only in a tiny minority of cases, most involving some tool named `*-config` (because they all just blindly copied pkg-config) you want to split on spaces.

**Comment by TheZeus121** [comment]
Thank you! :+1:
