### ISSUE TITLE
The argparse command should have an option to skip over unknown options

### ISSUE THREAD

**Issue by mattmc3** [fish-shell/fish-shell#5367]
I have a small feature request.

When using the `argparse` fish builtin command, you are required to define all the possible options you'll be receiving before hand, and cannot cherry pick the options you care about and then just ignore the rest. I have found that I frequently don't care about all the options being passed to my script - I just want to parse what I have defined and skip over the rest, or handle the remaining elsewhere. This is especially useful if you are wrapping other functionality or farming off small bits of processing to other functions.

I propose adding an `-i/--ignore-missing` or `-u/--skip-undefined` flag to parse what we can and skip the rest.

Example:
```fish
# works great when I know about all the flags (-a,-b,-c)
argparse 'a=+' 'b=+' 'c=+' -- -a alpha -b bravo -c charlie

# but not when there are others
argparse 'a=+' 'b=+' 'c=+' -- -a alpha -b bravo -c charlie -t tango
# > Unknown option '-t'

# proposing a -i/--ignore-missing flag
argparse --ignore-missing 'a=+' 'b=+' 'c=+' -- -a alpha -b bravo -c charlie -t tango
# $_flag_a, $_flag_b, $_flag_c are set
# $_flag_t wasn't defined, so it is not...
```

Currently, in places where I would love to use `argparse`, I find myself picking apart `$argv` in a loop or using `string match` magic to regex my way through the problem. While that's workable, it feels like it's a deficiency in `argparse`, which really should be the one best way to handle command arguments.

Note: I looked into the `-s/--stop-nonopt` option, but it only concerns itself with arguments and not flags, and isn't really the behavior I am describing.

**Comment by mattmc3** [comment]
> The "-t" can only be assumed to be a boolean option (i.e. like "t", not "t=+"), so the "tango" would remain in $argv.

Yes, I agree completely. `argparse` won't be able tell the difference between `-t tango` as one argument with a value, or a boolean flag `-t` and another argument `tango` - _and that's perfectly fine_. This new option in argparse should leave anything not defined in `$argv`, letting you parse your arguments incrementally with future calls to argparse or just throw the rest away.

**Comment by faho** [comment]
The solution I went with was to keep all unknown options in $argv (in the correct order, which meant disabling getopt's reordering!). That's the most flexible because it allows you to deal with them later. The alternative, to remove all unknown options, seems mostly useless.

**Comment by lesderid** [comment]
@faho Any idea when this will be in a release? I could use this for a script I'm working on.

**Comment by faho** [comment]
@lesderid It'll be in 3.1.0, which doesn't have a due date yet. I'd guess it'll come out in a month or two, but that depends on some of the kinks introduced by some refactoring being ironed out quickly enough.
