### ISSUE TITLE
hotkey to select current word

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5368]
fish 2.7.1

What about "ctrl+!" = select the current word? (idea taken sublimetext)

And if you don't like the idea, how can I add it for myself?

**Comment by faho** [comment]
Ctrl-! is unfortunately one of those key combinations that are not usable in a terminal.

This can be bound via something like

```fish
bind \cg backward-bigword begin-selection forward-bigword
```

I don't think we need to add it, though the selection stuff is a bit of an afterthought in general.

**Comment by BarbzYHOOL** [comment]
ah hmm can't copy the word to my clipboard (with ctrl+c or mouse click) so i guess that wasn't really a good idea lol

also it stays highlighted until i pressed ctrl+g again

but thank you for the help!

**Comment by BarbzYHOOL** [comment]
there is a "if pbcopy" exists, and I have a plugin called pbcopy, hope it won't conflict (i mean it's the fault of the plugin to be called exactly like that but well :D)

**Comment by faho** [comment]
If your thing has a function called `pbcopy`, then we'll use it. If it's not compatible with pbcopy, then it should be renamed.
