### ISSUE TITLE
Ctrl+v to paste on remote server

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5369]
fish 2.7.1-1714-gc729a97c

When I try to paste something with ctrl+v from my local to my remote host (through ssh), it says:

```
 xsel: Can't open display: (null)                                                                                                      18:02:25
: Inappropriate ioctl for device
```

Ok i feel like it's normal but isn't there a workaround to be able to use ctrl+v rather than that annoying middle mouse button??

**Comment by faho** [comment]
The problem is that ctrl-v relies on an external tool to get your clipboard through, and ssh doesn't do that (at least not without X forwarding).

In this situation you'll have to use your terminal's pasting.

**Comment by BarbzYHOOL** [comment]
Ok, I tried with X forwarding and it works. I guess I'm going to ssh with -X all the time now o_0

Thank you
