### ISSUE TITLE
Terminfo string s is undefined in terminal of type "terminology"

### ISSUE THREAD

**Issue by toonn** [fish-shell/fish-shell#5371]
When `TERM=terminology`, which seems to work fine with ncurses unlike `xterm-terminology` for example, I get the following message:
```
<E> fish: Tried to use terminfo string s on line 599 of src/screen.cpp, which is undefined in terminal of type "terminology". Please report error to fish-users@lists.sourceforge.net
```

Ordinarily I wouldn't report this because this `TERM` setting isn't standard, however, it working fine with ncurses unlike other made up settings seems to indicate maybe it should work.

**Comment by faho** [comment]
Which fish version is this? Which operating system? ncurses version? terminology version?

**Comment by faho** [comment]
Okay, I'm assuming this is 2.7.1, in which case the line number is completely misleading. Line 597-600 of screen.cpp are:

```c++
static void s_write_mbs(data_buffer_t *b, char *s) {
    scoped_buffer_t scoped_buffer(b);
    writembs(s);
}
```

where "s" is an argument. As it turns out, we only call `s_write_mbs` with "clr_eol" and "clr_eos", and we check the latter for availability. I don't think I've ever encountered a terminal that doesn't _have_ the former, but the "terminology" terminfo entry indeed does not have the `el` capability.

I have no idea how we'd do without that cap, but we could certainly add a check so we don't print an error.

**Comment by faho** [comment]
I've just installed terminology 1.3.0 from the arch repos, so you want to upgrade.

That defaults to $TERM=xterm and provides an option to switch to xterm-256color instead, so I'm not sure why you feel the need to switch?

**Comment by toonn** [comment]
I'm testing some other software. As I said I wouldn't ordinarily report this, I know my usecase is niche.

**Comment by faho** [comment]
As far as I can tell:

- the "xterm-terminology" terminfo entry does not exist, which explains any errors you get (that means it's invalid as a value for $TERM!)

- the "terminology" entry is shipped by ncurses but not used by terminology, which means it's probably an old mistake (like e.g. the "gnome" and "konsole" entries). It should not be used anymore.

- Terminology defaults to xterm, which means it _can_ do el, which means the entry is actively wrong.

Like I said, we could silence this error, but I'm not sure that would work in terminals that _actually_ can't do el. If such a terminal exists, I want it to error.

I'm not sure what your usecase here is? The real entry you should be using is "xterm-256color". "terminology" is old cruft.

**Comment by toonn** [comment]
It's a program that tries to figure out the running terminal through `TERM`.

**Comment by faho** [comment]
That won't work. Most terminals now use $TERM=xterm(-256color). E.g. konsole, anything using vte (gnome-terminal et al), IIRC even iTerm2.

$TERM needs to fit the terminal, it's not just a simple user-friendly string that you can set as you please.

**Comment by toonn** [comment]
Yep, that's the hard part. I don't know of a better way to find out what terminal you're actually running in.

**Comment by faho** [comment]
The best I've been able to figure out is $TERM in combination with variables. E.g. if $TERM is xterm-*, check:

- $KONSOLE_PROFILE_NAME for Konsole
- $VTE_VERSION for anything using VTE (e.g. gnome-terminal)
- $XTERM_VERSION for actual xterm
- $ITERM_PROFILE for iTerm

in addition, use $TERM=st for st, $TERM=Linux for linux vts and $TERM_PROGRAM=Apple_Terminal for Terminal.app.

**Comment by faho** [comment]
And $TERMINOLOGY=1 for terminology.

**Comment by floam** [comment]
> $ITERM_PROFILE for iTerm

Can simplify the logic for Terminal.app and iTerm by just checking TERM_PROGRAM for them both.

We do for one very special annoyance, override the terminfo entries for enter italics, exit italics, and dim when we know we are running on Terminal.app. We also, just in proc.cpp, do manually produce `clr_eol`/`el` (terminfo, termcap names) if TERM isn't set/working at all:
```c++
                if (cur_term != NULL) {
                    tputs(clr_eol, 1, &writeb);
                } else {
                    fwprintf(stdout, L"\x1B[K");  // no term set up - do clr_eol manually
                }
```

**Comment by faho** [comment]
>We also, just in proc.cpp, do manually produce clr_eol/el (terminfo, termcap names) if TERM isn't set/working at all

WHAT?

That's... 1. Not how this works. 2. Apparently never triggered since this is the first I'm hearing about this issue.

I'm inclined to remove that.

**Comment by faho** [comment]
Okay, for me TERM=terminology actually _crashes_. Maybe it's some other circumstances, maybe it's changes in 3.0.

I'm pushing checks for clr_eol now.

**Comment by floam** [comment]
> That's... 1. Not how this works. 2. Apparently never triggered since this is the first I'm hearing about this issue.

Not necessarily, because it's checking `cur_term`, so if this can run before we have tried to set up the terminal, it would still print the correct escape. Doesn't appear worried enough about a a working terminal but missing symbol there, because it didn't check for that..
