### ISSUE TITLE
Math is not rounding correctly

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5377]
2.7.1++ and 2.7.1

> - `-sN` or `--scale=N` sets the scale of the result. `N` must be an integer. A scale of zero causes results to be rounded down to the nearest integer. So `3/2` returns `1` rather than `2` which `1.5` would normally round to. This is for compatibility with `bc` which was the basis for this command prior to fish 3.0.0. Scale values greater than zero causes the result to be rounded using the usual rules to the specified number of decimal places.

```
## CORRECT
math -s0 "10/3"
3
math -s1 "10/3"
3.3

## INCORRECT?
math -s0 "10/6"
1
math -s1 "10/6"
1.7
```

Shouldn't it round to 2 in the second example?

Note: on the 2.7.1 it returned "1.6" instead of "1.7" so apparently you guys already worked on this recently

**Comment by faho** [comment]
>A scale of zero causes results to be rounded down to the nearest integer.

>rounded **down**

This does not "round" so much as it truncates.

This is working as intended - the previous function did it, and if you're using a scale of 0 you most likely want integers.

**Comment by BarbzYHOOL** [comment]
Ok wasn't sure for rounded down (i noticed it but i'm not english)

>, and if you're using a scale of 0 you most likely want integers.

1.99 will result in 1 instead of 2, to me it seems like a big issue

(Btw I would have used -s1 if the command "test" didn't return me "invalid integer" but I didn't find a solution)

**Comment by faho** [comment]
test can do floats in 3.0.

Am Fr., 30. Nov. 2018, 23:12 hat Barbz <notifications@github.com>
geschrieben:

**Comment by ridiculousfish** [comment]
I added 'round' support to math in 5012fb0e3642839c6855b67982621f875340c7e0, odd that it was omitted from tinyexpr.

**Comment by BarbzYHOOL** [comment]
Ok cool guys !
