### ISSUE TITLE
Echo a dynamic variable

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5378]
2.7.1

I'm making a simple script but I'm stuck at some basic stupid level.

```
set WORLDSERVER_TOTAL_CRASH_COUNT 0
set INFINITE_CRASH_MSG "Total crashes: $WORLDSERVER_TOTAL_CRASH_COUNT"
set WORLDSERVER_TOTAL_CRASH_COUNT 3

echo $INFINITE_CRASH_MSG
->Total crashes: 0
```

How to make the echo display `Total crashes: 3`??

I know I could change the order of the variables like that:

```
set WORLDSERVER_TOTAL_CRASH_COUNT 0
set WORLDSERVER_TOTAL_CRASH_COUNT 3
set INFINITE_CRASH_MSG "Total crashes: $WORLDSERVER_TOTAL_CRASH_COUNT"

echo $INFINITE_CRASH_MSG
```

But it would make the script less readable and I feel like I'm missing some very basic knowledge here. How to proceed?

**Comment by faho** [comment]
One possibility is to set one variable to a printf format string:

```fish
set WORLDSERVER_TOTAL_CRASH_COUNT 3
set INFINITE_CRASH_MSG "Total crashes: %s"

printf $INFINITE_CRASH_MSG $WORLDSERVER_TOTAL_CRASH_COUNT
```

another is to make it a function instead:

```fish
function print_crash_message
    echo "Total crashes: $WORLDSERVER_TOTAL_CRASH_COUNT"
end

set -g WORLDSERVER_TOTAL_CRASH_COUNT 3 # or set it -lx, or pass it as an argument
print_crash_message
```

**Comment by BarbzYHOOL** [comment]
```
set WORLDSERVER_TOTAL_CRASH_COUNT 0
set INFINITE_CRASH_MSG "Total crashes: %s"
set WORLDSERVER_TOTAL_CRASH_COUNT 3

printf $INFINITE_CRASH_MSG $WORLDSERVER_TOTAL_CRASH_COUNT
```

Works fine and is very simple! **Thank you**
We can't use the same thing with echo? I never know if I should use printf or echo 


Method 2, yes, I haven't made any function in that script, I could.

**Comment by BarbzYHOOL** [comment]
That's some printception

Thank you, I discovered how to use printf today then with only one command (I cut it in several parts)
