### ISSUE TITLE
There should be an EXPAND_INTERRUPTED return value for expand_string()

### ISSUE THREAD

**Issue by JanKanis** [fish-shell/fish-shell#538]
Currently interruption in the wildcard expander is treated as a generic error and `EXPAND_ERROR` is returned, which in many cases causes an error to be print to the terminal. The function should have a separate error code for this case, and callers should handle it correctly. 

Note: this is a spinoff from bug #516, but I didn't find the time to update all the callers. 
Note to whoever will be fixing this: I did find out that in `parser_t::eval_args` a correct behavior in case of an `EXPAND_INTERRUPTED` on line parser.cpp:831 is to only set `do_loop` to 0 and nothing else is needed.

**Comment by faho** [comment]
Okay, this has one *quite* stale.
