### ISSUE TITLE
Missing tmux flags

### ISSUE THREAD

**Issue by daylightbrightledlight** [fish-shell/fish-shell#5380]
I found a missing auto-completion entry for `tmux`. It is missing the `-A` flag for the entry `tmux new-session -A`. On that note, it is also missing the `-D` flag.  I've already used `fish_update_completions` for fish 2.7.1 on macOS installed using Homebrew with tmux 2.8 and term xterm-256color.

**Comment by daylightbrightledlight** [comment]
This fix uses the file https://github.com/fish-shell/fish-shell/blob/master/share/completions/tmux.fish

**Comment by faho** [comment]
Sure. Feel free to open a PR!

**Comment by daylightbrightledlight** [comment]
There are actually many other missing flags. The file is a bit messy because its style is inconsistent with others.

**Comment by faho** [comment]
Feel free to restyle it if you want - `fish_indent -w tmux.fish` should do it.

**Comment by krobelus** [comment]
closed by #5500
