### ISSUE TITLE
Filetype preference for completions

### ISSUE THREAD

**Issue by schwukas** [fish-shell/fish-shell#5383]
Hi there,

I wonder whether fish offers the option to prefer specific filetypes for ~auto suggestions~ completions.
For instance, I like to take notes in Markdown and convert them to pdf every time I save the file. Now, when I'm coming back after some time to add something to the markdown file, I type `nvim no<Tab> ` which of course suggests both `notes.md` and `notes.pdf`. I then have to complete the file ending in order to get the markdown file in this case.

Since it's not that usual for me to open pdfs with vim or markdown-files with my pdf reader, I thought there might be some option for a priority list. In the given example this would mean, that files like `.txt`,`.md` or `.xml` would be preferred over others when opened with vim. Some file types could be ignored alltogether, like opening movies with vim, python code with vlc and so on.

I looked through the documentation, but I couldn't find anything appropriate. Or maybe I just didn't understand correctly.

**Comment by mqudsi** [comment]
You can create a custom completion for `nvim` that uses the `-k` option to save the ordering of generated completions. To generate the completions themselves, you would just call `__fish_complete_suffix` and then sort the results by extension.

**Comment by schwukas** [comment]
Thanks for your comment. However, it's not entirely clear to me how or where to invoke the `-k` option. Could you give one example of how such a line might need to look?

Thanks :)

**Comment by faho** [comment]
We already have `__fish_complete_suffix`, it just needs to be used in cases where it's actually useful.

Unfortunately, that's not as often as you'd think!

For instance for neovim, it's basically impossible to list all extensions it will or will not read. It probably won't have full support for pdfs, but there are things like https://github.com/larki/PDFViewer, and pdfs are actually sort of editable!

This gets worse when you swap neovim for the (obviously far superior) emacs, which might be able to render pdfs, depending on compile-time options!

Or when you think about extensions not actually meaning much on unix.

So, just like #2906, I'm closing this.

If you have a specific completion with a specific set of extensions that you want to see, report it and we'll add it, if it makes sense. Most of the time, it doesn't.
