### ISSUE TITLE
Command "set" doesn't return status code?

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5385]
fish, version 2.7.1-1748-g5615351f

If you type a wrong command, then you type "set variable", it will return the wrong command status code, and not "success" from the "set" command which is very confusing

How to reproduce:

```
$blablo                                                                                                                                     15:39:30
fish: Unknown command 'blablo'
$echo $status
127
$set test "blabla"                                                                                                                      3ms|15:39:32
$echo $status
127
$echo $test                                                                                                                                 15:39:44
blabla
```

I have disabled my prompt for the test

**Comment by zanchey** [comment]
From the `set` documentation:

> In assignment mode, set does not modify the exit status. This allows simultaneous capture of the output and exit status of a subcommand, e.g. if set output (command).

This appears to be behaving as intended.

**Comment by BarbzYHOOL** [comment]
ah ok
