### ISSUE TITLE
ConEmu vagrant ssh fish

### ISSUE THREAD

**Issue by mrmeszaros** [fish-shell/fish-shell#5387]
## System info:
* Windows 10
* fish, version 2.7.1
* TERM=cygwin

## Issue:

When using Cmder (conemu) and ssh to a vagrant virtual box, the fish shell prompt is broken:

<img width="483" alt="cmder-conemu-ssh-fish-glitch" src="https://user-images.githubusercontent.com/15245298/49576145-aff59600-f944-11e8-903e-53329ac932ec.png">

**Comment by faho** [comment]
What seems to be happening here is that fish is printing various escape sequences, including e.g. `\e[30m` for the "normal" color, but something in your setup mangles that, probably by stripping the leading escape character.

I have no idea what `vagrant ssh` does exactly, in particular I don't  know what it does with $TERM.

Can you do `echo $TERM` and `tput colors` inside the ssh session?

**Comment by mrmeszaros** [comment]
Hey,
Some clarification:
* I am using Cmder - it sets the TERM variable to cygwin
* `vagrant ssh` does nothing to environment variables (in my setup)
  - I use it to connect to my local linux in VirtualBox

Inside the ssh session `echo $TERM` yields `cygwin` and `tput colors` yields `8`.

**Comment by faho** [comment]
>vagrant ssh does nothing to environment variables (in my setup) 

It looks like it should! Because all of those sequences are things that work in a "cygwin" terminal, and apparently vagrant (or something that vagrant calls) breaks it (e.g. by not passing on non-printable characters like escape).

So it needs to either be changed to not break those sequences, or it needs to be changed to indicate that it can't handle them, e.g. by setting $TERM to "dumb".

It's possible this can be done by fiddling with the settings, or it needs actual changes somewhere in the vagrant stack. Like I said, I'm not familiar with it so you might have better luck in a vagrant forum.

**Comment by mrmeszaros** [comment]
Setting the TERM to dumb fixed the issue with the non-printable characters bloating the prompt.

Sadly it is not vagrant that does this: plain old ssh also does it:

<img width="432" alt="cmder-conemu-ssh-fish-glitch-fix" src="https://user-images.githubusercontent.com/15245298/49583019-213e4480-f957-11e8-9684-94dbe88b3cb5.png">

**Comment by mrmeszaros** [comment]
I also tried [Terminus](https://github.com/Eugeny/terminus) without `vagrant` - just plain old ssh.

This is what I get - same, but different:

<img width="478" alt="terminus-fish-glitch" src="https://user-images.githubusercontent.com/15245298/49584493-d07d1a80-f95b-11e8-98af-d5164444791b.png">

I tried in WSL (Windows Subsystem for Linux) - no glitch:
<img width="275" alt="wsl-fish-no-glitch" src="https://user-images.githubusercontent.com/15245298/49584859-f951df80-f95c-11e8-93aa-92ac8978fccc.png">

So rather this must be related to the ssh, or another part of the system - maybe?

Also, I would like to Thank You for the quick responses 👍

**Comment by faho** [comment]
That "rÅÄ" (or something like it) is most likely a weird interpretation of our missing newline trick. This is supposed to display as "⏎", but only if the previous command's output did not end in a newline.

It seems terminus does not quite get that.

It's a different issue.

**Comment by mrmeszaros** [comment]
I was able to find an option that may cause this:
* `ConEmu Settings > Features > In-console options > Inject ConEmuHk`
* When this is disabled, the coloring works, when this is enabled, Coloring causes the aforementioned issue
* Should I be right, this needs to be reported the ConEmu's issue tracker

Should I create a separate issue here for the `ΓÅÄ` thing?

**Comment by faho** [comment]
>Should I be right, this needs to be reported the ConEmu's issue tracker

Probably.

>Should I create a separate issue here for the ΓÅÄ thing?

That's a terminus issue.
