### ISSUE TITLE
SSH input does not appear when using -i and -c options

### ISSUE THREAD

**Issue by harrisonthorne** [fish-shell/fish-shell#5389]
Fish version: **2.7.1**
Operating system: **Arch Linux 4.19.4**
Terminal: The error has been reproduced in **alacritty** and **kitty** so far.

I like to use rofi to launch an ssh session in a terminal. However, recently, it seems the functionality is broken.

I have rofi configured to launch the following command in a new terminal window:

`/usr/bin/fish -i -c "ssh $hostname"`

where `$hostname` is a host to connect to. Input is registered just fine; I can type in a password and successfully log into the ssh server. However, any input after that doesn't appear. The ssh server uses `bash`.

This issue has been replicated by launching the ssh session from within another terminal like so:

`alacritty -e /usr/bin/fish -i -c "ssh $hostname"`

Interestingly enough, when opening a new terminal and then entering `ssh $hostname`, input displays as expected.

If I run the same command except with `bash`, input displays as expected as well:

`alacritty -e /bin/bash -i -c "ssh $hostname"`

Using `bash` is an acceptable workaround for now, but I thought I would bring up this issue anyways. :)

**Edit:** corrected alacritty commands

**Comment by faho** [comment]
This works for me.

Please check if this works without your fish configuration. I.e. run

```fish
sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'
```

and then in that one run alacritty.

**Comment by harrisonthorne** [comment]
Seems that this was fixed with an update :)
