### ISSUE TITLE
Is there a fish way to print string without ANSI color code?

### ISSUE THREAD

**Issue by edouard-lopez** [fish-shell/fish-shell#5390]
**related:** [stackoverflow](https://stackoverflow.com/q/53666154/802365)

---

In a [discussion for `pure` theme](https://github.com/rafaelrinaldi/pure/pull/68#discussion_r239634119) we are looking for a way to counting a string symbol without, i.e. ignoring the ANSI code:

```fish
❯ set -l user (set_color red)root
❯ set -l at (set_color grey)@
❯ set -l host (set_color blue)remote
❯ set user_and_host "$user$at$host"

❯ echo $user_and_host
root@remote  
❯ string length $user_and_host
26  # should be 11
```

One possible [solution using `sed`](https://superuser.com/a/380778/174465) is:

    sed 's/\x1b\[[0-9;]*m//g'

### Question

Is there a more fish/generic way to do that?

**Comment by faho** [comment]
Another alternative: Construct the prompt as a `printf` format string, with `%s` placeholders for the colors.

E.g.

```fish
set prompt_host "%s"$USER"%s"@"%s"$host"%s":

# Calling printf with no arguments will print the format string with all placeholders removed
set length (printf "$prompt_host" | string length)
# (with the color sequences stored in variables
set colored (printf "$prompt_host" $usercolor $normal $hostcolor $normal)
```

The obvious issue here is that "%" can't appear in the components - it needs to be escaped by being doubled - `string replace -a '%' '%%'`.

**Comment by faho** [comment]
I would say the question has been answered.

**Comment by edouard-lopez** [comment]
Yes, thanks for your reply.

We went for the [`string replace` method](https://github.com/rafaelrinaldi/pure/pull/68/files#diff-e9f1f7c746c11daaa758ba5df307a175)
