### ISSUE TITLE
Incorrect behavior of command-not-found on openSUSE Leap 15

### ISSUE THREAD

**Issue by cavalheiro** [fish-shell/fish-shell#5391]
On openSUSE Leap 15, whenever I type a command that does not exist, I have the following behavior:

> / command-that-does-not-exist
> --: searching ...Cannot not open database file '/usr/share/scout/bin-command-that-does-not-exist.db'
> --: command not found

This is due to the fact that in `/etc/osrelease` the var `ID_LIKE` has now value "suse opensuse" instead of only "suse".

I have a possible fix for this and will open a PR soon.

Environment: 
> Fish version: 2.7.1
> Linux alphatwo 4.12.14-lp150.12.25-default #1 SMP Thu Nov 1 06:14:23 UTC 2018 (3fcf457) x86_64 x86_64 x86_64 GNU/Linux
> xterm-256color

I am using a fresh install of fish without any third-party customizations.

**Comment by zanchey** [comment]
This is a duplicate of #4447 and is fixed in the next release (soon!)

**Comment by zanchey** [comment]
Apologies, no it isn't!

**Comment by cavalheiro** [comment]
Well, I actually think the situation is similar: openSUSE thumbleweed also has "ID_LIKE="opensuse suse" on `/etc/osrelease` which causes the problem in the first place. I have proposed a fix on PR#5392, but the fix proposed on https://github.com/fish-shell/fish-shell/commit/e02e485cc6e712879d10fc99034543b7424567fb also seems to work.

**Comment by faho** [comment]
Duplicate of #4447

**Comment by cavalheiro** [comment]
Seems this is already fixed on the master branch. Closing as discussed on PR #5392.
