### ISSUE TITLE
wildcard for mv not working

### ISSUE THREAD

**Issue by Kejia** [fish-shell/fish-shell#5393]
i use fish 2.7.1 on macos. 

> $ uname -a
> uname -a                                                                                                                                                                                       
> Darwin crystal.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
> $ echo $TERM                                                                                                                                                                                     
> xterm-256color
> $ sh -c 'env HOME=$(mktemp -d) fish'                                                                                                                                                             
> Welcome to fish, the friendly interactive shell

the wildcard does not work for the command **mv**:

> $ ls *.png                                                                                                                                                                                       
> after.png  before.png
> $ mv *.png sreen2/                                                                                                                                                                               
> usage: mv [-f | -i | -n] [-v] source target
>        mv [-f | -i | -n] [-v] source ... directory
> $ ls *.png 
> after.png  before.png

**Comment by faho** [comment]
This works for me?

Do you have an `mv` function (or alias)? `type mv` should tell you!
