### ISSUE TITLE
Extra output from commands when using SSH through termius

### ISSUE THREAD

**Issue by Holt59** [fish-shell/fish-shell#5400]
When running some commands on my server through SSH using termius (iOS app), I get some strange extra outputs from fish commands:

```
user@hostname ~> ks
fish: Unknown command 'ks'
fish /home/user                    <-- Here
user@hostname ~> fish --version
fish, version 2.7.1
0;fish /home/user                  <-- Here
```

I don't get such output with other shells such as bash, and I only get those when connecting using termius.

My server is running debian, and I have no extra third party extensions for fish installed. Some extra environment variables:

**Comment by faho** [comment]
That's fish setting the terminal title, which apparently termius can't deal with.

**Comment by floam** [comment]
Should we disable setting the title for that terminal?

**Comment by faho** [comment]
>Should we disable setting the title for that terminal?

We could query the "XT" capability, but that has only been added in 2010 (https://unix.stackexchange.com/a/292701), tmux doesn't have it,....

And there's barely any terminal that doesn't support it.

@Holt59: What's $TERM in termius?

**Comment by floam** [comment]
> So that means there literally is no way for us to detect it.
Unless it happens to set TERM_PROGRAM or something like that.

Many terminals claim to be xterm when they aren't, and don't have full xterm compatibility. However, puking when given `\e]0;foo\a;` is pretty egregious. They should really fix that.

**Comment by zanchey** [comment]
> Unless it happens to set `TERM_PROGRAM` or something like that.

That doesn't get passed over SSH by default.

I don't think there's much we can do about this. @Holt59, does the workaround @faho posted work for you?
