### ISSUE TITLE
Key binding fail on beta version of 3.0

### ISSUE THREAD

**Issue by hovnatan** [fish-shell/fish-shell#5410]
Using beta version of fish 3.0 my custom key binding `bind \t complete-and-search` doesn't work anymore.

**Comment by faho** [comment]
How do you bind that? In 3.0, this should work both inside the `fish_user_key_bindings` function and just anywhere in your configuration. And I have just confirmed that that works for me.

Does `bind \t` say:

```fish
bind --preset \t complete
bind \t complete-and-search
```

?

**Comment by hovnatan** [comment]
It does say 

    bind --preset \t complete
    bind \t complete-and-search

but it doesn't work. Before, in 2.7.1, if I pressed Tab twice then started typing the typed string would be searched, but now after double-Tab the current choice will be used as starting point for the next typed string. I hope this is understandable.

**Comment by hovnatan** [comment]
Nope, only Shift-TAB does that.

**Comment by hovnatan** [comment]
You can have a look at my fish configs [here](https://github.com/hovnatan/dotfiles/tree/master/.config/fish)

**Comment by faho** [comment]
Your config.fish contains this bit about bindings:

```fish
function hybrid_bindings --description "Vi-style bindings that inherit emacs-style bindings in all modes"
    for mode in default insert visual
        fish_default_key_bindings -M $mode
    end
    fish_vi_key_bindings --no-erase
    bind \cp up-or-search
    bind \cn down-or-search
    bind \t complete-and-search
    fzf_key_bindings
end

set -g fish_key_bindings hybrid_bindings
```

So you're using a vi-ish binding style with different modes. Because you've not specified $fish_bind_mode anywhere, this defaults to "insert" on startup. Only `bind \t complete-and-search` binds it in default mode.

The binding in insert mode can be queried with `bind -M insert \t`, it should tell you that it's still "complete". Add `bind -M insert \t complete-and-search` to also bind it in insert mode.

**Comment by hovnatan** [comment]
Ok. thanks a lot, it worked. One last question -- when I press TAB in search mode it cycle through entries in reverse order (starts from the end), is it possible to cycle in direct order?

**Comment by faho** [comment]
>is it possible to cycle in direct order?

Currently not. The binding functions are coupled a bit too tightly for that.
