### ISSUE TITLE
`test` -gt, -lt integer overflow

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#5414]
In fish 3:

```shell
$ test 9223372036854775808 -lt 42 && echo true || echo false
true
```

Previously:
```shell
test returned eval errors:
	invalid integer '9223372036854775808'
```

This happened when `test` was extended to take floats. (Technically, `long long`, `double` pairs because of precision requirements).

**Comment by floam** [comment]
We need to explicitly check errno for `ERANGE`, (a different topic, but shouldn't this ought to be `intmax_t` rather than `long long`, using `wcstoimax()`?

**Comment by floam** [comment]
We now catch the error, and have different output for different kinds of errors:

```shell
$ test 9324234234234234234234234.56 -lt 5
test returned eval errors:
	Result too large: '9324234234234234234234234.56'
$ test 2345a.44 -gt 1
test returned eval errors:
	Integer 2345 in '2345a.44' followed by non-digit
$ test '' -gt 1
test returned eval errors:
	Invalid argument: ''
```

**Comment by zanchey** [comment]
This seems like something suitable for 3.0?

**Comment by ridiculousfish** [comment]
Yeah let's pick it into 3.0

**Comment by floam** [comment]
I've had it in Integration for a couple hours
