### ISSUE TITLE
builtin math: doesn't respect localization

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#5421]
`math` will accept as input, and only will print as output dots (.) as decimal separators. I think this is not right.

```shell
~ $ set -lx LC_NUMERIC fr_FR.UTF-8; math 1,2
math: Error: Too many arguments
'1,2'
  ^
~ $ set -lx LC_NUMERIC fr_FR.UTF-8; math 1.2
1.2
```

I think `math` should match the behavior we implemented for printf:
```shell
$ set -lx LC_NUMERIC fr_FR.UTF-8; printf %f 1,2
1,200000
$ set -lx LC_NUMERIC fr_FR.UTF-8; printf %f 1.2
1,200000
```

We are flexible with input, but always output localized numbers. A user with `fr_FR.UTF-8` should be able to use output from `/usr/bin/printf`, `builtin printf`, even `awk` which will have commas in them because of LC_NUMERIC without thinking, and also be able to expect to get numbers printed out that make sense in their country. ksh93 gets this right although it is more strict about input than I would like.

**Comment by faho** [comment]
Let's keep this in #5420, there's no need for two separate issues!

**Comment by floam** [comment]
This is about following LC_NUMERIC, the other is about uses spaces for the argument separator.

**Comment by faho** [comment]
>This is about following LC_NUMERIC, the other is about using spaces for the argument separator.

Okay, then let's discuss this here.

-----


So, I absolutely hate this!

>We are flexible with input, but always output localized numbers

Being flexible with input would be acceptable, but outputting localized numbers is _wrong_. Like I said in #5420, my awk does not accept "," as a radix. Neither do python or bc.

All of them exclusively use ".".

My /usr/bin/printf does _not_ accept "," in the input, though it exclusively uses it in the output - this seems wrong.

>also be able to expect to get numbers printed out that make sense in their country.

Using "," in this context does _not_ make sense in my country.

**Comment by floam** [comment]
On my system:
```
set -lx LC_NUMERIC fr_FR.UTF-8; echo 5,29 | awk '{ print int($1), sqrt($1) }'
2,3
set -lx LC_NUMERIC fr_FR.UTF-8; echo 5.29 | awk '{ print int($1), sqrt($1) }'
2,3
```

I don't know why your tools aren't localizing things, but how can it **break** things if the input if the input is flexible?

> Using "," in this context does not make sense in my country.

I mean by being readable in the way numbers are taught at school and printed on signs.

**Comment by floam** [comment]
> my awk does not accept "," as a radix

I just tried this on Linux, it accepted a ',' (although it does seem stuck outputting dots):

```
$ set -lx LC_NUMERIC fr_FR.UTF-8; echo 5,29 | awk '{ print int($1), sqrt($1) }'
5 2.23607
$ awk --version
GNU Awk 4.1.3, API: 1.1 (GNU MPFR 3.1.4, GNU MP 6.1.0)
```

**Comment by floam** [comment]
I originally reported the output two comments above wrong after failing to copy and paste correctly. It is now correct. My `awk` will quietly choke on dots if the locale uses commas. It always outputs things formatted for the locale.

**Comment by faho** [comment]
>I don't know why your tools aren't localizing things, but how can it break things if the input is flexible? 

Like I said, I don't have much against flexible input, except for then needing #5420  - commas just make a bunch of sense there, but considering we have two functions that read more than one argument, changing that wouldn't be too bad. Also, accepting "," only when the locale fits is a bit annoying, and I don't see an easy fix.

>I mean by being readable in the way numbers are taught at school and printed on signs.

Yes, but this is a different context. I think I've shown that basically everything wants dots here. And reading a different radix character isn't rocket surgery.

>My awk will quietly choke on dots in input if the locale uses commas.

I would assume your awk is buggy.

Though mine is... weird:

```fish
$ echo 5,29 | awk '{ print int($1), sqrt($1) }'
5 2.23607
$ echo 5.29 | awk '{ print int($1), sqrt($1) }'
5 2.23607
$ awk '{ print int(5.29), sqrt(5.29) }'
5 2.23607
$ awk '{ print int(5,29), sqrt(5,29) }'
awk: Kommandozeile:1: { print int(5,29), sqrt(5,29) }
awk: Kommandozeile:1:                 ^ Unzulässige Argumentzahl 2 für int
# awk: commandline:1:                  ^ invalid number of arguments 2 for int
```

**Comment by floam** [comment]
Wait a minute, the square root of 5.29 is actually 2.3...

**Comment by faho** [comment]
>Wait a minute, the square root of 5.29 is actually 2.3...

Does it matter? Awk is probably using a weird algorithm or rounding mode here.

**Comment by floam** [comment]
Well, I think I might have the correct and incorrect output backwards. 2.23607 is the square root of 5.0.

**Comment by floam** [comment]
the awk behavior is explained here: https://www.gnu.org/software/gawk/manual/html_node/Locale-influences-conversions.html

**Comment by faho** [comment]
>the awk behavior is explained here:

I.e. gawk hides it behind $POSIXLY_CORRECT. Which is where GNU puts stuff in POSIX that they disagree with.

**Comment by faho** [comment]
I'm closing this.
