### ISSUE TITLE
Failed to open connection to "session" message bus Error

### ISSUE THREAD

**Issue by Radi8621** [fish-shell/fish-shell#5422]
Using Elementary OS with following versions
  fish-version 2.7.1
  4.15.0-42-generic #45-Ubuntu 

When using fish in root I always get this error message and sadly cannot make any sense of it:

"Failed to open connection to "session" message bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken."

Would be very helpful even just showing me in the right direction 
Thanks in advance

**Comment by Shnatsel** [comment]
Oh yeah, that does sound like the process completion notifications malfunctioning. [Here's the code](https://github.com/elementary/terminal/blob/master/data/pantheon_terminal_process_completion_notifications.fish) that pantheon-terminal puts in fish.

I don't think I've seen this when I open a regular terminal and then do `sudo -s` to get a root shell. How do you run your terminal as root?

**Comment by Radi8621** [comment]
Just tried opening the shell over New Root Tab Option when I right click the shell
After login like this fish works without any errors

**Comment by Shnatsel** [comment]
Okay, please report this issue on elementary/terminal repository.
