### ISSUE TITLE
3.0b1 build error on wcwidth in Cygwin

### ISSUE THREAD

**Issue by andrew-schulman** [fish-shell/fish-shell#5423]
fish-3.0b1
CYGWIN_NT-10.0 LZ77E1AASCHULMA 2.11.2(0.329/5/3) 2018-11-08 14:34 x86_64 Cygwin

With fish-3.0b1.tar.gz and ffab420, `cmake; make` chokes on wcwidth in fallback.cpp:

```
[ 56%] Building CXX object CMakeFiles/fishlib.dir/src/fish_version.cpp.o
In file included from /home/ASchulma/dev/cygwin/fish/fish-3.0b1-1.x86_64/src/fish-3.0b1/src/parse_util.h:10:0,
                 from /home/ASchulma/dev/cygwin/fish/fish-3.0b1-1.x86_64/src/fish-3.0b1/src/expand.cpp:45:
/home/ASchulma/dev/cygwin/fish/fish-3.0b1-1.x86_64/src/fish-3.0b1/src/parse_tree.h:74:5: warning: multi-line comment [-Wcomment]
     ///   echo abc | \
     ^
/home/ASchulma/dev/cygwin/fish/fish-3.0b1-1.x86_64/src/fish-3.0b1/src/expand.cpp: In function ‘size_t parse_slice(const wchar_t*, wchar_t**, std::vector<long int>&, std::vector<long unsigned int>&, size_t)’:
/home/ASchulma/dev/cygwin/fish/fish-3.0b1-1.x86_64/src/fish-3.0b1/src/expand.cpp:245:22: warning: suggest parentheses around comparison in operand of ‘!=’ [-Wparentheses]
             if (tmp1 > -1 != tmp > -1) {
                 ~~~~~^~~~
/home/ASchulma/dev/cygwin/fish/fish-3.0b1-1.x86_64/src/fish-3.0b1/src/fallback.cpp: In function ‘int fish_wcwidth(wchar_t)’:
/home/ASchulma/dev/cygwin/fish/fish-3.0b1-1.x86_64/src/fish-3.0b1/src/fallback.cpp:294:20: error: ‘wcwidth’ was not declared in this scope
             return wcwidth(wc);
                    ^~~~~~~
/home/ASchulma/dev/cygwin/fish/fish-3.0b1-1.x86_64/src/fish-3.0b1/src/fallback.cpp:294:20: note: suggested alternative: ‘width’
             return wcwidth(wc);
                    ^~~~~~~
                    width
make[2]: *** [CMakeFiles/fishlib.dir/build.make:1122: CMakeFiles/fishlib.dir/src/fallback.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```
wcwidth is declared in /usr/include/wchar.h:
```
int    wcwidth (const wchar_t);
```
So I guess we need to include wchar.h. But I don't know enough about cmake to know how to do that. Suggestions?

**Comment by faho** [comment]
>So I guess we need to include wchar.h.

It's already included? https://github.com/fish-shell/fish-shell/blob/ffab420e4318c65387a72a8572f2e40e301d0028/src/fallback.cpp#L21

```c++
#include <wchar.h>
```

Without it, you'd get basically _nothing_ because we use it all over the place.

It's possible this is failing somewhere in the #ifdefs - we've added a separate compile-time option to pick your own wcwidth.

You can try that one with `cmake -DINTERNAL_WCWIDTH=OFF`.

**Comment by andrew-schulman** [comment]
> You can try that one with `cmake -DINTERNAL_WCWIDTH=OFF`.

No luck. I'll debug the #ifdefs and see what I can figure out.

**Comment by zanchey** [comment]
I'm not going to hold 3.0.0 for this if the autotools build still works, but will definitely have it fixed for 3.1.

**Comment by zanchey** [comment]
OK, this is because the autotools build sets `_GNU_SOURCE` in `config.h`, but the CMake build doesn't. `configure.ac` calls [`AC_USE_SYSTEM_EXTENSIONS`](https://www.gnu.org/software/autoconf/manual/autoconf.html#Posix-Variants), but `CMAKE_CXX_EXTENSIONS` doesn't do the same thing.

**Comment by andrew-schulman** [comment]
Hm. I tried rerunning with `cmake -D_GNU_SOURCE=1`, but it didn't help.

The autotools build does still work for now.

**Comment by zanchey** [comment]
That defines _GNU_SOURCE in CMake, not as a definition in the compilation process. Try `cmake -DCMAKE_CXX_FLAGS=-D_GNU_SOURCE` (which fixes the build for me).

**Comment by andrew-schulman** [comment]
Yes, that works. Or a little more simply in cygport, `CXXFLAGS+=" -D_GNU_SOURCE"`.

**Comment by zanchey** [comment]
Does the build pass the test suite and/or run correctly? `make test` is hanging on my Windows Server 2008R2 installation in the Ctrl-C cancellation and the actual binary does not want to launch correctly.

**Comment by andrew-schulman** [comment]
Yes, `ninja test` fails on the Ctrl-C cancellation, and fish.exe hangs.
