### ISSUE TITLE
fish_key_reader assertion when using a shell pipe

### ISSUE THREAD

**Issue by aleflamed** [fish-shell/fish-shell#5424]
Fish version 2.7.1
Fedora 29
~ $ rpm -qf (which fish)
fish-2.7.1-4.fc29.x86_64

~ $ uname -a
Linux myputer.localdomain 4.18.16-300.fc29.x86_64 #1 SMP Sat Oct 20 23:24:08 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

~ $ echo $TERM
xterm-256color

terminal is tilix (I don't think it is relevant)

Problem reproduces under clean shell (using sh -c 'env HOME=$(mktemp -d) fish')

Steps to reproduce:
1. run
 fish_key_reader | cat
2. press ctrl-c

Expected result:
return to prompt

Actual result:
assertion message and stack trace repeating in a loop. Recorded by adding a step 0 "script", here is the beginning of the recording in typescript file:

Script started on 2018-12-18 08:31:15+02:00
<snip escape codes for readablity> 
fish_key_reader | cat
<snip some more escape codes for readbility>
<W> fish_key_reader: Current terminal parameters have rows and/or columns set to zero.
<W> fish_key_reader: The stty command can be used to correct this (e.g., stty rows 80 columns 24).
Press a key

              hex:    3  char: \cC
Press [ctrl-C] again to exit
<E> fish_key_reader: src/common.cpp:1994: failed assertion: pthread_mutex_lock(lock_obj): errno 22 (Invalid argument)
<E> fish_key_reader: Backtrace:
<E> fish_key_reader: 0   scoped_lock::scoped_lock(pthread_mutex_t&) + 0
<E> fish_key_reader: 1   wgettext[abi:cxx11](wchar_t const*) + 185
<E> fish_key_reader: 2   fish_key_reader(+0x3345a) [0x55c0acf4945a]
<E> fish_key_reader: 3   /lib64/libpthread.so.0(+0x13070) [0x7efc4941d070]
<E> fish_key_reader: 4   __write + 24
<E> fish_key_reader: 5   _IO_file_write + 45
<E> fish_key_reader: 6   /lib64/libc.so.6(+0x7cccf) [0x7efc48f06ccf]
<E> fish_key_reader: 7   _IO_do_write + 25
<E> fish_key_reader: 8   _IO_wdo_write + 189
<E> fish_key_reader: 9   _IO_wfile_sync + 61
<E> fish_key_reader: 10  fflush + 161
<E> fish_key_reader: 11  std::ostream::flush() + 34
<E> fish_key_reader: 12  std::ios_base::Init::~Init() + 68
<E> fish_key_reader: 13  /lib64/libc.so.6(+0x3accc) [0x7efc48ec4ccc]
<E> fish_key_reader: 14  on_exit + 0
<E> fish_key_reader: 15  __libc_start_main + 250
<E> fish_key_reader: 16  _start + 42

<snip - repeats endlessly with increasing stack levels, i.e. recursively hitting the same assert>

fish: Process 3375, “fish_key_reader” “fish_key_reader | cat” terminated by signal SIGSEGV (Address boundary error)

I cannot upload the asciinema cast file (too large I guess) so I'll attach it.

**Comment by faho** [comment]
I can reproduce this with 2.7.1, but not with the 3.0 beta (https://github.com/fish-shell/fish-shell/releases/tag/3.0b1), because of e76c1fd139d70c797344616c3e09b31ccc6b49d8.

This is apparently an issue in our old custom locks.
