### ISSUE TITLE
Cannot remove invalid entries from fish_user_paths

### ISSUE THREAD

**Issue by e102** [fish-shell/fish-shell#5427]
```
Please tell us which fish version you are using by executing the following:
```
fish, version 2.7.1

```
Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.
```
OS: macOS Mojava 10.14.2 (18C54)
term: xterm-256color

```
Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:

  sh -c 'env HOME=$(mktemp -d) fish'
```
It temporarily fixes my problem but that's expected given my issue relates to fish_user_paths being corrupted. When I go back to my normal config `i have the same issue

The problem: I added a bad path (Applikcations/flutter) to `fish_user_paths`. When I try to add new paths, remove the bad path or even just clear `fish_user_paths`, I get an error.
```
srdjanmiletic@TABLT0232-SrdjanMiletic~> echo $fish_user_paths
Applications/flutter /usr/local/sbin /Users/srdjanmiletic/.rbenv/shims
srdjanmiletic@TABLT0232-SrdjanMiletic~> set -U fish_user-paths
set: Variable name 'fish_user-paths' is not valid. See `help identifiers`.

       setset - display and change shell variables.
        -

   Synopsis
       set [SCOPE_OPTIONS]
       set [OPTIONS] VARIABLE_NAME VALUES...
       set [OPTIONS] VARIABLE_NAME[INDICES]... VALUES...
       set ( -q | --query ) [SCOPE_OPTIONS] VARIABLE_NAMES...
       set ( -e | --erase ) [SCOPE_OPTIONS] VARIABLE_NAME
       set ( -e | --erase ) [SCOPE_OPTIONS] VARIABLE_NAME[INDICES]...
       set ( -S | --show ) [SCOPE_OPTIONS] [VARIABLE_NAME]...

set: Type 'help set' for related documentation
```

**Comment by tsaber** [comment]
fish_user-paths => fish_user_paths ?
aside from that if you also have it with this corrected I had a similar thing. You can't unset some path fish_user_path combination without a lot of unknown command messages spinning. the universal and global scope multiplies my confusion. 
My path keeps getting longer with the same three addons that must be added somewhere else. profile I think.

**Comment by mqudsi** [comment]
If you recursively add to `fish_user_paths`, e.g. `set fish_user_paths /foo $fish_user_paths` in your `config.fish`, it'll grow indefinitely. You should instead export a modified view of `fish_user_paths` in the global scope: `set -g fish_user_paths /foo $fish_user_paths`.

**Comment by tsaber** [comment]
ya i got rid of the /etc/profile.d/*
