### ISSUE TITLE
Error on Openwrt

### ISSUE THREAD

**Issue by haodong** [fish-shell/fish-shell#5428]
v2.7.1
I use the tab-completion to complete command `xarg` to `xargs` with the following error.
```shell
root@OpenWrt ~# echo | xargfish: Unknown command 'apropos'
in function '__fish_describe_command'
        called on standard input
        with parameter list 'xarg'

in command substitution
        called on standard input


⏎
```

**Comment by zanchey** [comment]
This is fixed in e8a35bfaa83c3a93cd7e9c214c410a01eeb8781b, which is in the 3.0b1 beta and will be in the soon-to-be-released 3.0.0, so I'm closing this for now.
