### ISSUE TITLE
`source`ing, keybinds, and interactivity

### ISSUE THREAD

**Issue by Synthetica9** [fish-shell/fish-shell#5435]
I have a bind for a custom history view using [`fzf`](https://github.com/junegunn/fzf):

```fish
function fish_user_key_bindings
  bind \ch "history --null | fzf --read0 --preview '' --multi --tiebreak=index | source"
end
```

However, when I use this binding to execute "interactive" commands, they typically fail. The same thing also happens when directly entering the command `history --null | ... | source`. A few ways in which they fail:

### `ipython3`

```
Python 3.7.1 (default, Oct 20 2018, 06:25:16) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.1.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: Do you really want to exit ([y]/n)?
```

Immediate exit, but does give a prompt

### `bash`

No prompt, no nothing

### `nmtui`

Renders the interface, but disappears when using arrow keys

### `fzf` 

Fails with:

```
Failed to read /dev/tty
```

### `ncdu`

Fails with:

```
Standard input is not a TTY. Did you mean to import a file using '-f -'? 
```

### `ghci`

Immediately exits, but draws the startup message and prompt (similar to Bash)

```
GHCi, version 8.4.4: http://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /home/synthetica/.ghci
Prelude
λ> Leaving GHCi.
```

## Proposed solution

My proposed solution is adding a flag to `source` that allows you to run programs as if they were entered manually. So they would appear in history, appear to be entered after the prompt, have full ncurses capabilities, 

(Version, if it matters: 2.7.1)

**Comment by Synthetica9** [comment]
@faho That's still not quite interactive behaviour though, it doesn't get written to history, and the prompt isn't re-drawn, and ctrl-d doesn't work to exit out of interactive programs.

**Comment by mqudsi** [comment]
Doesn't fzf forcefully take over the terminal?

**Comment by mqudsi** [comment]
Yes, because this works:

```fish
bind \ch "eval (history --null | fzf --read0 --preview '' --multi --tiebreak=index; stty sane);"
```

**Comment by Synthetica9** [comment]
I found a command that does exactly what I want:

```fish
bind \ch "commandline -r (history --null | fzf --read0 --preview '' --multi --tiebreak=index)"
```

This also allows me to edit the command before executing it, and puts it in the history. Thanks to everyone who helped!
