### ISSUE TITLE
Testing syntax highlighting fails on Fedora

### ISSUE THREAD

**Issue by ignatenkobrain** [fish-shell/fish-shell#5436]
I'm maintainer of fish in Fedora and while trying to compile new release 3.0.0 I've found that few tests are failing:

```
Testing syntax highlighting
Error: Wrong color in test at index 16 in text (expected 0x2, actual 0x1):
cat /dev/null | less 2>
                ^
Error: Wrong color in test at index 17 in text (expected 0x2, actual 0x1):
cat /dev/null | less 2>
                 ^
Error: Wrong color in test at index 18 in text (expected 0x2, actual 0x1):
cat /dev/null | less 2>
                  ^
Error: Wrong color in test at index 19 in text (expected 0x2, actual 0x1):
cat /dev/null | less 2>
                   ^
```

**Comment by ignatenkobrain** [comment]
This might be related:

```
tcgetattr: Inappropriate ioctl for device
tcgetattr: Inappropriate ioctl for device
tcgetattr: Inappropriate ioctl for device
tcgetattr: Inappropriate ioctl for device
tcgetattr: Inappropriate ioctl for device
tcgetattr: Inappropriate ioctl for device
```

**Comment by faho** [comment]
This apparently happens when `less` isn't installed - because it then highlights it with the "missing command" color.

So the test is bogus.

**Comment by faho** [comment]
Fixed in master.

If you want to run the tests, I suggest either cherry-picking 742fde0, or depending on `less` for running the tests.

**Comment by zanchey** [comment]
I've been thinking about getting the tests running under the Open Build Service as we're generating packages there anyway, so this is another good reason to do so.

**Comment by zanchey** [comment]
We're running the tests on Fedora under OBS now, so we should catch this sort of thing earlier in the future.
