### ISSUE TITLE
Fish 3.0 documentation is not online

### ISSUE THREAD

**Issue by gladhorn** [fish-shell/fish-shell#5437]
https://fishshell.com/docs/3.0/index.html should work, it's the fallback when there is no local documentation.

**Comment by zanchey** [comment]
Yep. It will get there; @ridiculousfish is in a very different timezone to me!

**Comment by ridiculousfish** [comment]
Sorry for the delay, /docs/current was updated but now this is fixed as well.

**Comment by gladhorn** [comment]
Thanks :)
