### ISSUE TITLE
build fails if ncurses built with tinfo/termlib

### ISSUE THREAD

**Issue by gyakovlev** [fish-shell/fish-shell#5439]
fish 3.0.0
ncurses built with separate tinfo
and fish fails to build:
```
/usr/bin/x86_64-pc-linux-gnu-g++  -march=native -O2 -pipe -frecord-gcc-switches -fdiagnostics-color=always  -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0    -rdynamic CMakeFiles/fish_indent.dir/src/fish_indent.cpp.o CMakeFiles/fish_indent.dir/src/print_help.cpp.o  -o fish_indent  libfishlib.a -lcurses -pthread -ldl -lpcre2-32 && :
FAILED: fish_indent
```

Hi!
basically same issue as here https://github.com/fish-shell/fish-shell/pull/1322 but now with cmake.
we allow separate tinfo library because some (usually  binary-only ) applications require it.

I'm not very good with cmake, any ideas where to look at to properly detect this and add `-ltinfo` to the build flags if needed?

**Comment by gyakovlev** [comment]
found I can pass `-DCURSES_EXTRA_LIBRARY=tinfo` to cmake, it works but probably should be somehow autodetected.

**Comment by zanchey** [comment]
https://gitlab.kitware.com/cmake/cmake/blob/master/Modules/FindCurses.cmake looks like it should handle this properly as arranged by https://bugs.gentoo.org/468622.

I'd refer this initially to the CMake developers, as fish just uses `FIND_PACKAGE(Curses REQUIRED)`.

**Comment by gyakovlev** [comment]
if I pass `-DCURSES_NEED_NCURSES=ON` it'll go and check for cbreak in `ncurses` and will link to `tinfo` if required by setting proper `CURSES_EXTRA_LIBRARY`.

but if I don't pass `-DCURSES_NEED_NCURSES=ON` it'll ignore that if block and will never set `CURSES_USE_NCURSES` at all..

I can live with passing `-DCURSES_NEED_NCURSES=ON` because we only support ncurses.

looks like it's exactly what I needed. thanks for pointing to the right direction.

and I found that gentoo provides a symlink for `-lcurses`
`/usr/lib64/libcurses.so -> libncurses.so`

so probably cmake finds that `libcurses` (missing **n**) and does not set `CURSES_USE_NCURSES` in that block. 
https://github.com/Kitware/CMake/blob/9bbfbd54ba04e07b0bf2eb8bb1056bca53d639c5/Modules/FindCurses.cmake#L63-L65

thanks again for the help. now it works, tests pass. closing.
