### ISSUE TITLE
How to fake executable is missing?

### ISSUE THREAD

**Issue by edouard-lopez** [fish-shell/fish-shell#5444]
**related:** https://sqa.stackexchange.com/q/37094/28461

---

I'm in the process of [testing `pure` theme](https://github.com/rafaelrinaldi/pure/pull/96) for `fish`.

I want to test the following conditional branch from our [__pure_prompt_first_line.fish_](https://github.com/rafaelrinaldi/pure/blob/25b7671378/functions/_pure_prompt_first_line.fish#L5):

    if not type -fq git
        return 1
    end

But I need a way to fake `git` is missing. 

How could I achieve this as I have git install?

**Comment by mqudsi** [comment]
Personally, I temporarily change that `git` to `git_` or something and observe the error path then change it back. You would probably have to install `git` to its own location and include that in `PATH` but not when testing this branch, although perhaps someone has a better idea.

**Comment by faho** [comment]
Either:

- set $PATH so it's not included, but that means you can't use any other executable in the same directory

- override `type` to return 1 when asked about `git`:

```fish
functions --copy type oldtype
function type
    if test "x$argv" = "x-fq git"
        return 1
    end
    oldtype $argv
end
```

**Comment by edouard-lopez** [comment]
After mocking `type` you have to **restore the built-in mechanism** so other test cases don't fail unexpectedly:

```fish
functions --erase type
functions --copy builtin_type type  # restore 'type' for following tests case
```

Full test suite
```fish
test "fails when git is missing"
    (
        functions --copy type builtin_type
        function type  # mock
            if test "x$argv" = "x-fq git"
                return 1
            end
            builtin_type $argv
        end

        _pure_prompt_first_line
        set --local exit_code $status
        
        functions --erase type  # remove mock
        functions --copy builtin_type type  # restore built-in behavior for following test cases
        echo $exit_code
    ) = 1
end

test " another test"
    (
        …
    ) = 1
end
```
