### ISSUE TITLE
set -ex from Bash - Exits on first error and display commands being run

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5445]
fish 2.7

Just discovered set -x (and set -e) in bash, it's awesome, would love it in fish.

`set -e` exits the script on first error (for example when a command doesn't exist)
`set -x` displays the command being run before running it (debug mode?)

I read like 5 issues and I think they were all closed because of duplicate issue that are not exactly related (or closed too) so I opened this one.

**Comment by faho** [comment]
#3427 is still open, as is #510.
