### ISSUE TITLE
CentOS 7/RHEL 7 fish 3.0.0 RPMs can't resolve dependency

### ISSUE THREAD

**Issue by bnied** [fish-shell/fish-shell#5448]
When trying to install `fish` via the official RPMs, it can't resolve the dependency for `libpcre2-32.so()(64bit)`:

```
[bnied@vm-rhel7 ~]$ sudo yum install fish
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-manager
Resolving Dependencies
--> Running transaction check
---> Package fish.x86_64 0:3.0.0-1.1 will be installed
--> Processing Dependency: libpcre2-32.so()(64bit) for package: fish-3.0.0-1.1.x86_64
--> Finished Dependency Resolution
Error: Package: fish-3.0.0-1.1.x86_64 (shells_fish_release_3)
           Requires: libpcre2-32.so()(64bit)
**********************************************************************
yum can be configured to try to resolve such errors by temporarily enabling
disabled repos and searching for missing dependencies.
To enable this functionality please set 'notify_only=0' in /etc/yum/pluginconf.d/search-disabled-repos.conf
**********************************************************************

Error: Package: fish-3.0.0-1.1.x86_64 (shells_fish_release_3)
           Requires: libpcre2-32.so()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

`uname -a` Output: `Linux vm-rhel7 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 15 17:36:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Enabled repos:

```
[bnied@vm-rhel7 ~]$ sudo yum repolist
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-manager
repo id                                     repo name                               status
epel/x86_64                                 Extra Packages for Enterprise Linux 7 - 12,778
rhel-7-desktop-extras-rpms/x86_64           Red Hat Enterprise Linux 7 Desktop - Ex     47
rhel-7-desktop-optional-rpms/7Client/x86_64 Red Hat Enterprise Linux 7 Desktop - Op 19,371
rhel-7-desktop-rpms/7Client/x86_64          Red Hat Enterprise Linux 7 Desktop (RPM 18,851
shells_fish_release_3                       Fish shell - 3.x release series (RHEL_7      3
repolist: 51,050
```

**Comment by bnied** [comment]
FWIW, building `fish` 3.0.0 with the "old" specfile (i.e, pre-[cmake](
https://github.com/fish-shell/fish-shell/commit/725062d3607f1d0e07e001e08cac6f7f6c6f5a22#diff-60c5d6340c8f5b21d7778e1d18778bdf)) doesn't have the same issue. Maybe something's weird the CMakeLists?

**Comment by zanchey** [comment]
Yes, this is true on RHEL 6 as well. It's probably been broken for months as the changes were introduced in 725062d3607f1d0e07e001e08cac6f7f6c6f5a22 on May 29, 2018!

**Comment by zanchey** [comment]
Another argument for getting tests working in OBS as this would have been picked up on the spot - I am working on this.

**Comment by zanchey** [comment]
This is thanks to the CMake macros used with RPM, which set `-DBUILD_SHARED_LIBS:BOOL=ON`. For some reason. Others have had the same issue, eg in https://github.com/zealdocs/zeal-packaging/pull/37 - I will test and apply a fix shortly.

**Comment by zanchey** [comment]
I've committed a fix for this to master, and also rebuilt the 3.0.0 binaries so that they should work.
