### ISSUE TITLE
Exec inside a function does not work

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#5449]
```fish
$ function ouch
     exec fish
 end
$ ouch
There are still jobs active:

   PID  Command
     0  ouch
```

as described by @scorphus on gitter, and https://github.com/oh-my-fish/oh-my-fish/issues/664.

This is caused by us checking for running jobs before doing `exec` now (1b1bc28c0ae0fd10e9d3854b1d8cc8125623e1d9), in conjunction with the hierarchical job changes.

I think we might just get away with warning only with _background_ processes (i.e. those where `is_foreground()` is false). @mqudsi?

The obvious question is if this is important enough to warrant a 3.0.1, or a quick 3.1.

**Comment by mqudsi** [comment]
I would say if you publish now, it's a quick 3.0.1. If you put it off, it might become a 3.1.

**Comment by ridiculousfish** [comment]
This went into 3.0.1 as 60ced5dbc70a
