### ISSUE TITLE
Export function

### ISSUE THREAD

**Issue by AuHau** [fish-shell/fish-shell#5455]
Is it possible to export fish function? Similar to Bash's `export -f gitrack_prompt`?

Tried `set -x fish_prompt fish_prompt` without success.

**Comment by faho** [comment]
No, and given that that's directly responsible for shellshock, I'm not convinced there should be.

What do you want to do?

**Comment by AuHau** [comment]
Thanks for the reply! 

I am writing a utility which manipulates the shell's prompt and I wanted to be the changes "temporarily persistent", in a sense I don't want to make the changes persistent in the way of writing those into `config.fish`, yet wanted to keep the changes active across subshells.
