### ISSUE TITLE
'commandline -o' to return trailing newline

### ISSUE THREAD

**Issue by maxfl** [fish-shell/fish-shell#546]
It turned out that 'commandline -o' output does not distinguish cases with and without trailing spaces:
'git checkout|' and 'git checkout ' (see #393). 

I propose to add and extra newline to 'commandline -o' if there is an extra space in the command line, at least optionally. This feature should simplify the 'commandline -o' usage with 'complete -C'.

**Comment by krader1961** [comment]
This would appear to be non-backward compatible change so I've changed the milestone to "next-major".

**Comment by faho** [comment]
We've closed #5084, which essentially implements this, so we should close this too.

It simply does not seem worth it to make the change, considering that `commandline -ct` can be used to get the rest.
