### ISSUE TITLE
Ship tarballs with better compression

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#5460]
A colleague has pointed out to me that we currently ship our source in the least-efficient popular compression method, and that we should move to xz (LZMA). I'm not sure whether some of the more niche platforms support it, so if not we should at least look at bzip2.

```
-rw------- 1 zanchey gumby 6.2M Jan  1 21:26 fish_3.0.0-21-g742fde0d.orig.tar.gz
-rw------- 1 zanchey gumby 4.8M Jan  1 21:26 fish_3.0.0-21-g742fde0d.orig.tar.bz2
-rw------- 1 zanchey gumby 3.0M Jan  1 21:26 fish_3.0.0-21-g742fde0d.orig.tar.xz
```

**Comment by faho** [comment]
Most systems should already have xz installed (e.g. NetBSD apparently [switched some parts to xz](https://gnats.netbsd.org/53697). If not, https://tukaani.org/xz/ lists the supported platforms as:

    GNU/Linux (GCC, LLVM/Clang, ICC)
    GNU/HURD (GCC)
    DragonflyBSD (GCC)
    FreeBSD (GCC, LLVM/Clang)
    MirBSD (GCC)
    NetBSD (GCC)
    OpenBSD (GCC)
    MINIX 3 (GCC) [1]
    Haiku (GCC4)
    Mac OS X (GCC)
    Solaris 8, 9, 10, 11 (GCC, Sun Studio) [3]
    Solaris 2.6, 7 (GCC)
    HP-UX (GCC, HP ANSI C) [2]
    Tru64 (GCC, Compaq C compiler) [1]
    IRIX (MIPSpro) [1]
    AIX (GCC, IBM XL C)
    QNX (compilers?)
    OpenVMS (HP C compiler) [1]
    OpenVOS 17 (GCC)
    Windows 95 and later (GCC/MinGW, GCC/MinGW-w64, GCC/Cygwin, GCC/Interix) [1]
    OS/2, eComStation (GCC)
    DOS e.g. FreeDOS and MS-DOS (GCC/DJGPP) [1]

**Comment by zanchey** [comment]
Yes, it's more a matter of toolchain support - RHEL 6 may be the sticking point here.

**Comment by j-f1** [comment]
You could release both gz (for compatibility) and xz (for size).

**Comment by zanchey** [comment]
XZ is fine on RHEL 6, so I'll look at this in the near future.

**Comment by zanchey** [comment]
My old friend macOS doesn't support XZ/LZMA out of the box. D'oh! Does that matter? You can't build the tarball without third-party tools anyway (CMake).

**Comment by floam** [comment]
Are you sure macOS doesn't do XZ? Finder seems to extract tar.xz without any tools installed for a few years now.

**Comment by zanchey** [comment]
Hey, it does too - even in `tar` - there's just no binary for it.
