### ISSUE TITLE
../test/root/bin/fish: No such file or directory

### ISSUE THREAD

**Issue by Mno-hime** [fish-shell/fish-shell#5463]
`gmake test` run in Bash fails on OpenIndiana like this:

```make
Encountered 0 errors in low-level tests
cd tests; ../test/root/bin/fish test.fish
/bin/bash: ../test/root/bin/fish: No such file or directory
make[1]: *** [Makefile:387: test_fishscript] Error 127
```

`root/bin` does not exist, however `root/usr/bin/fish` does.

It might be due to `bindir` configured to `/usr/bin` (via autotools), but it did not propagate to `test` target and `/bin` was assumed?

```
...
configure ... --bindir=/usr/bin
...
Installing miscellaneous helper resources
  CPPFLAGS = '-D_UNICODE=1 -DLOCALEDIR="./share/locale" -DPREFIX=L"." -DDATADIR=L"./share" -DSYSCONFDIR=L"/etc" -DBINDIR=L"/usr/bin" -DDOCDIR=L"./share/doc/fish" -iquote. -iquote./src/ -DFISH_BUILD_VERSION="3.0.0"'
...
```

**Comment by Mno-hime** [comment]
Maybe the problem is that `SYSCONFDIR` and `BINDIR` _did_ propagete, but should not? `DATADIR` and `DOCDIR` look more like "relative" path.

**Comment by faho** [comment]
I'd probably set prefix instead of bindir here.

Also, can you reproduce this with cmake? We're trying to switch away from autotools, and both this and #5462 (plus the warning about "rm" being "inferior") seem like they only really apply there.

**Comment by Mno-hime** [comment]
> I'd probably set prefix instead of bindir here.

That's what the OI build system does for autotools-based projects. But CMake can be used as well.

> Also, can you reproduce this with cmake? We're trying to switch away from autotools, and both this and #5462 (plus the warning about "rm" being "inferior") seem like they only really apply there.

I tried CMake infra before, but wasn't able to find the test suite target. What's the right target for `ctest`?

**Comment by faho** [comment]
>I tried CMake infra before, but wasn't able to find the test suite target.

"test", just like for autotools?

>What's the right target for ctest?

Or is that not just a typo?

Basically, with cmake, instead of running `make test`, you end up running `make test`.

**Comment by zanchey** [comment]
The confusion is that CMake ships a utility called CTest, which is often used instead of a test target (and indeed is something that should be considered, post autotoolscalypse).

**Comment by Mno-hime** [comment]
There is a failure I see only with CMake:

```
Testing shell invocation functionality
Testing file invocation/bad-switch.invoke ... fail
    -Z
Error output differs for file invocation/bad-switch.invoke. Diff follows:
--- invocation/bad-switch.tmp.err       2019-01-02 20:11:20.214943116 +0000
+++ invocation/bad-switch.err   2019-01-02 20:10:48.318305541 +0000
@@ -1,2 +1,2 @@
-./fish: illegal option -- Z
+./fish: invalid option -- 'Z'
 RC: 1
```

Log: [test-64-results.txt](https://github.com/fish-shell/fish-shell/files/2721706/test-64-results.txt)

**Comment by Mno-hime** [comment]
How can I get rid of the colored output?

**Comment by faho** [comment]
>There is a failure I see only with CMake:

@Mno-hime: See e7221a21efcc290f4425771dea41d9100509ee8a.

>How can I get rid of the colored output?

https://cmake.org/cmake/help/latest/variable/CMAKE_COLOR_MAKEFILE.html, so 

`cmake -DCMAKE_COLOR_MAKEFILE=OFF`

**Comment by mqudsi** [comment]
```diff
--- invocation/bad-switch.tmp.err	2019-01-02 20:11:20.214943116 +0000
+++ invocation/bad-switch.err	2019-01-02 20:10:48.318305541 +0000
@@ -1,2 +1,2 @@
-./fish: illegal option -- Z
+./fish: invalid option -- 'Z'
```

*This* is the problem with using hard-coded string comparison as the testing framework. It's incredibly rigid and cannot account for any sort of (still correct) variability in the output.

**Comment by Mno-hime** [comment]
Thanks @faho, that did the trick. 

The original problem is not present when CMake is used, so I am fine closing this.

**Comment by faho** [comment]
Okay, let's close this!
