### ISSUE TITLE
building with netbsd-curses issues

### ISSUE THREAD

**Issue by protonesso** [fish-shell/fish-shell#5468]
Hi everyone. I have issues with fish. I'm building fish version 3.0.0 (some problem on older versions) with netbsd-curses 0.2.2 (drop-replacement to ncurses) with musl libc 1.1.20. My uname -a is ```Linux jiznost 4.9.0-8-amd64 #1 SMP Debian 4.9.135-1 (2018-11-11) x86_64 GNU/Linux``` (I build it under chroot environment). There is a log: https://pastebin.com/ELvtatnJ
Thanks!

**Comment by faho** [comment]
@protonesso: You'll want to include #5406, which was merged after 3.0, as aaee5dd..9b980f5.

**Comment by faho** [comment]
Going through the log, those are exactly the errors I fixed in #5406.

So, given that master is currently ~80 commits ahead of master, I'd recommend just building that, otherwise rebase #5406 on top of 3.0.0 and build that.

**Comment by protonesso** [comment]
I will consider to update my netbsd-curses

**Comment by faho** [comment]
>I will consider to update my netbsd-curses

Not netbsd-curses, fish!

We've made some changes to fish, to fix exactly the problem you are having.

**Comment by protonesso** [comment]
Okay, thank you a lot!
