### ISSUE TITLE
Update docs on special variables to include $hostname 

### ISSUE THREAD

**Issue by ipwnponies** [fish-shell/fish-shell#5469]
fish 3.0.0 introduced `$hostname` as a special variable (#4422). Attempting to set this value leads to errors:
```
set: Tried to change the read-only variable “hostname”
```

The fish [docs on special variables](https://fishshell.com/docs/current/index.html#variables) have not been updated to include this. I had some functions that used this variable name but the error was swallowed into the abyss, leading to some time spent debugging.

In addition to updating the docs, I thought I bring up possible user experience proposals (let me know if these warrant separate issue). As a user, I'd expect to have either:
* docs updated to list all special variables (or make it clear how to discover values  #5262)
* or ability to shadow `$hostname` variable in function scope

I'm also going to link the `$version` discussion (#3072) to introduce existing context and motivations for design decisions. The use of `$hostname` feels like it is contrary to the conclusion vs. using fish specific variable (i.e. `$FISH_HOSTNAME`).

**Comment by ridiculousfish** [comment]
This was picked into 3.0.1 as 3855608c690cec92555d5ec8a95703422403137f
