### ISSUE TITLE
tab completion Tab key does not start pager navigation

### ISSUE THREAD

**Issue by ipwnponies** [fish-shell/fish-shell#5470]
fish 3.0.0 updated the tab completion and pager behaviour. But it seems the former tab behaviour of using `Tab` to start pager navigation is not working. i.e. The first `Tab` will list completions but subsequent `Tab` do nothing. Arrow keys start pager navigation and the `Tab` key can be used as before, after entering this mode.

The documentation states this behaviour, which was the same in previous versions:
> If there is more than one completion, fish will write out the longest prefix that all completions have in common. If the completions differ on the first character, a list of all possible completions is printed. The list features descriptions of the completions and if the list doesn't fit the screen, it is **scrollable by using the arrow keys, the page up/page down keys, the tab key** or the space bar.

**Comment by faho** [comment]
Works for me. What is tab bound to? `bind \t` should tell you.

**Comment by ipwnponies** [comment]
Nice debugging tip, this is not a fish 3.0 issue: 
```
bind --preset \t complete
bind -m expand \t expand:execute
```

This is from the [`expand` plugin](plugin-expand
), which overrides `\t` binding. I've opened oh-my-fish/plugin-expand#2 to follow up there.
