### ISSUE TITLE
`string replace` in regex-mode requires waaaay too many backslashes for the replacement

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#5474]
(I could swear we already discussed this somewhere, but I can't find it. Anyway I'm pretty sure it's been closed, and I want to rerun it)

`string replace -r` currently does an additional unescaping pass on the replacement (see the `interpret_escapes` function in builtin_string.cpp), and just the replacement.

That means  if you e.g. want to add a backslash to any a or b, you'll have to do this:

```fish
string replace -ra '([ab])' '\\\\\\\$1' a
```

with one or two backslashes, it just prints "a", with three to six backslashes, it prints `$1`. With seven to ten, it prints the desired `\a`.

If we removed `interpret_escapes` instead:

- one or two backslashes prints `$1`

- three or four prints `\a`

- five or six prints `\$1`

- seven or eight prints `\\a`

This is explainable - `\` is an escape character in fish even in single-quotes, so `\\` is reduced to just `\` before it reaches fish. `\$` isn't reduced, because `$` doesn't need to be escaped. So both `\$` and `\\$` result in `\$` being passed to fish.

Similarly, `\\\$` and `\\\\$` reduce to `\\$`, which is taken by string to mean "a literal backslash, and then the dollar replacement".

The major issue with this is backwards-compatibility. There is, as far as I can see, no way to make a common subset to easily write expressions that work with both interpretations.

So we'd have to do something:

-  `string replace --real-regex` or `string replace --regex --replacement-without-annoying-backslashes`
- or a feature flag
- or break stuff and tell people to check $version

I still feel like this is worth it, simply because the current behavior is ridiculous.

**Comment by faho** [comment]
I'm pretty sure we'd have to fix the paste escaping in fish_clipboard_paste.

Also of note is that the tests currently do _not_ cover this.

**Comment by zanchey** [comment]
> `string replace -r` currently does an additional unescaping pass on the replacement

Any idea why?

**Comment by faho** [comment]
It's been that way since string was added, so I'm assuming it's pure oversight.

There's no logic to it that I can see.

**Comment by floam** [comment]
https://github.com/fish-shell/fish-shell/issues/3381 I think talked about the second unescape.

**Comment by faho** [comment]
Ah, indeed, it did.

And... well, there's no good reason why we do the second unescape, and there's mentions of backwards compatibility, and of breakage. So basically what I expected.

And I have to say that the breakage is not going to be as large as expected. It's not _fantastic_ to audit, but something like the above `grep "string replace -.*r.*\\\\\\\\"` gets you reasonably close. The difference is that this only affects the replacement string, not the match expression. So e.g alias is not affected, even though it does `set -l tmp (string replace -ra -- "([^\\\ ])((\\\\\\\)*) " '$1\n' $body)`, because that has no backslashes in the replacement.

The biggest problem is finding a way to support cross-compatible expressions.

**Comment by floam** [comment]
The feature name is a real mouthful. Maybe this could be `regex-slashless`. I think it should be the default behavior.

**Comment by floam** [comment]
It seems like `set -a fish_features string-replace-fewer-backslashes` doesn't work until you restart fish.

**Comment by faho** [comment]
>It seems like set -a fish_features string-replace-fewer-backslashes doesn't work until you restart fish.

That's features in general.

**Comment by faho** [comment]
Note the feature was renamed "regex-easyesc" by #5805.
