### ISSUE TITLE
`eval` doesn't properly handle exported variables

### ISSUE THREAD

**Issue by imcaizheng** [fish-shell/fish-shell#5480]
> fish, version 3.0.0

Given the following example:

```
set -lx message 'Oh, fish!'

function receiver
echo message is "`$message`"
end

receiver # works
eval 'begin; echo message is "`$message`"; end # still works
eval 'receiver' # doesn't work
```

I don't know whether it is a feature or a bug.

**Comment by mqudsi** [comment]
It's a symptom of a known bug, see #4443. `eval` is (wrongly) implemented as a function, which means scoping breaks.

**Comment by mqudsi** [comment]
This is now fixed.
