### ISSUE TITLE
fish no longer warns when a path entry is invalid

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5487]
I don't remember this being a deliberate change?

fish 2.7.1:

```fish
mqudsi@ZBOOK /m/c/U/m/r/fish2> echo $version
2.7.1
mqudsi@ZBOOK /m/c/U/m/r/fish2> set -g fish_user_paths /foo
set: Warning: $PATH entry "/foo" is not valid (No such file or directory)
```

fish 3.0:

```fish
mqudsi@ZBOOK /m/c/U/m/r/fish2> echo $version
3.0.0-54-gd6d7b2bb8
mqudsi@ZBOOK /m/c/U/m/r/fish2> set -g fish_user_paths /foo
mqudsi@ZBOOK /m/c/U/m/r/fish2>
```

**Comment by faho** [comment]
From the CHANGELOG:

>Setting `$PATH` no longer warns on non-existent directories, allowing for a single $PATH to be shared across machines (eg via dotfiles) (#2969).

This is intentional.

**Comment by mqudsi** [comment]
(Perhaps this warning can be emitted in interactive mode, i.e. after `config.fish` has been loaded, which would have the best of both worlds.)
