### ISSUE TITLE
Nim prompt on mac does not work

### ISSUE THREAD

**Issue by gudstrand** [fish-shell/fish-shell#5490]
version 3.0.0
Darwin saturn 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
xterm-256color

1) new installation of fish via brew
2) added fish to /etc/shells
3) ran fish
4) ran fish_config
5) went to prompt and selected Nim and clicked on set prompt

when I now do an ls I see the following:
┬─[gudstrand@saturn:~/.c/fish]
╰─>$ ls
config.fish    fish_variables functions
fish: Unknown command '_nim_prompt_wrapper'
~/.config/fish/functions/fish_prompt.fish (line 29):
    _nim_prompt_wrapper $retc '' (date +%X)
    ^
in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

┬─[gudstrand@saturn:~/.c/fish]
╰─>$

[nim.prompt.txt](https://github.com/fish-shell/fish-shell/files/2731758/nim.prompt.txt)

**Comment by ridiculousfish** [comment]
Picked into 3.0.1 as 96f7924661016a29231c2523f68c794dcb2e5a89
