### ISSUE TITLE
Cannot source .bashrc

### ISSUE THREAD

**Issue by AviSoomirtee** [fish-shell/fish-shell#5491]
fish, version 2.7.1

Linux DESKTOP-H7RJEHF 4.4.0-17134-Microsoft #471-Microsoft Fri Dec 07 20:04:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

xterm-256color

sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell

The issue is that i cannot source .bashrc in fish!

**Comment by faho** [comment]
Fish isn't bash-compatible on purpose.

What are you trying to do?
