### ISSUE TITLE
Make fish deb package independent from python2.7

### ISSUE THREAD

**Issue by tnir** [fish-shell/fish-shell#5492]
While currently the fish deb package depends (to be exact `Recommends: python (>=2.6)` via `fish-common`), we should move to python3 as possible if it is available.

### on Ubuntu 18.04 (bionic)
```
# python3 -V
Python 3.6.7
# apt update -qq && apt install -qqy software-properties-common
(snipped)
# apt-add-repository ppa:fish-shell/release-3
(snipped)
# apt install fish
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following additional packages will be installed:
  bc bsdmainutils fish-common gettext-base groff-base libbsd0 libgdbm5
  libpipeline1 libpython-stdlib libpython2.7-minimal libpython2.7-stdlib
  libx11-6 libx11-data libxau6 libxcb1 libxdmcp6 man-db multiarch-support
  python python-minimal python2.7 python2.7-minimal xsel
Suggested packages:
  cpp wamerican | wordlist whois vacation xdg-utils groff gdbm-l10n apparmor
  less www-browser python-doc python-tk python2.7-doc binutils binfmt-support
The following NEW packages will be installed:
  bc bsdmainutils fish fish-common gettext-base groff-base libbsd0 libgdbm5
  libpipeline1 libpython-stdlib libpython2.7-minimal libpython2.7-stdlib
  libx11-6 libx11-data libxau6 libxcb1 libxdmcp6 man-db multiarch-support
  python python-minimal python2.7 python2.7-minimal xsel
0 upgraded, 24 newly installed, 0 to remove and 0 not upgraded.
Need to get 9226 kB of archives.
Preparing to unpack .../8-fish-common_3.0.0-1~bionic_all.deb ...
Unpacking fish-common (3.0.0-1~bionic) ...
Selecting previously unselected package fish.
Preparing to unpack .../9-fish_3.0.0-1~bionic_amd64.deb ...
Unpacking fish (3.0.0-1~bionic) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Setting up groff-base (1.22.3-10) ...
Setting up gettext-base (0.19.8.1-6ubuntu0.1) ...
Setting up libpipeline1:amd64 (1.5.0-1) ...
Setting up libgdbm5:amd64 (1.14.1-6) ...
Setting up libbsd0:amd64 (0.8.7-1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Setting up libxdmcp6:amd64 (1:1.1.2-3) ...
Setting up bsdmainutils (11.1.2ubuntu1) ...
update-alternatives: using /usr/bin/bsd-write to provide /usr/bin/write (write) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/write.1.gz because associated file /usr/share/man/man1/bsd-write.1.gz (of link group write) doesn't exist
update-alternatives: using /usr/bin/bsd-from to provide /usr/bin/from (from) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/from.1.gz because associated file /usr/share/man/man1/bsd-from.1.gz (of link group from) doesn't exist
Setting up bc (1.07.1-2) ...
Setting up libx11-data (2:1.6.4-3ubuntu0.1) ...
Setting up libpython2.7-stdlib:amd64 (2.7.15~rc1-1ubuntu0.1) ...
Setting up libxau6:amd64 (1:1.0.8-1) ...
Setting up python2.7 (2.7.15~rc1-1ubuntu0.1) ...
Setting up libpython-stdlib:amd64 (2.7.15~rc1-1) ...
Setting up man-db (2.8.3-2ubuntu0.1) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
Building database of manual pages ...
Setting up libxcb1:amd64 (1.13-1) ...
Setting up python (2.7.15~rc1-1) ...
Setting up libx11-6:amd64 (2:1.6.4-3ubuntu0.1) ...
Setting up xsel (1.2.0-4) ...
Setting up fish-common (3.0.0-1~bionic) ...
Setting up fish (3.0.0-1~bionic) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...
```

### refs
- cf. https://wiki.ubuntu.com/Python

**Comment by zanchey** [comment]
Yep. I'll add it as `python3 | python` as our scripts should all be agnostic.

**Comment by tnir** [comment]
Thanks 👍

**Comment by mqudsi** [comment]
@zanchey do you know who does the FreeBSD packages? It would greatly benefit from dropping the python requirement altogether.

**Comment by zanchey** [comment]
@mqudsi https://www.freshports.org/shells/fish/ shows the current maintainer

**Comment by faho** [comment]
>It would greatly benefit from dropping the python requirement altogether.

@mqudsi: What do you mean by that? I think the python dependency is best expressed as a debian "recommends". Which means that, by default, it's installed automatically, but the user can opt-out.

A debian "suggests" or archlinux-style "optional" dependency that is purely informative and has to be handled manually is also acceptable, especially on systems like arch where the user is expected to care about these things, but no dependency at all is pretty bad.

Or is there some FreeBSD specific bit I'm missing? Does it not have a way of expressing "some python"?

**Comment by mqudsi** [comment]
On FreeBSD, the fish package currently has a hard dependency on python2. I agree with your recommendation.

**Comment by zanchey** [comment]
FreeBSD ports only have hard dependencies; there's no recommend/suggest-like option. RPM is the same and at present the fish.spec file depends on Python.

**Comment by floam** [comment]
> I also never used fish_config even as a newbie to fish.

I honestly think you're in the minority here. However I think I agree with this for the FreeBSD port, although that is actually out of our control - we could make it easier for them by doing as you say and having fish give some nice output when you run `fish_config` without Python installed. And we should probably even suggest it upfront for the sake of man page completions and preventing surprises later. `fish_greeting` would be a good spot to suggest installing python if it doesn't exist to get the full feature set.

**Comment by zanchey** [comment]
> having fish give some nice output when you run `fish_config` without Python installed.

This is a great idea.

Also it would be worth suggesting to the FreeBSD maintainer that they might want to add a message that suggests Python which appears after the installation is complete.

**Comment by floam** [comment]
I've committed a nice error message and also hints on how to configure the prompt and colors by hand.

**Comment by mqudsi** [comment]
@asomers hey thanks for responding so fast! Thanks for taking care of the FreeBSD fish package ♥.

**Comment by ridiculousfish** [comment]
This was picked into 3.0.1 as 749347ff4c45fd217054714f53c6df064bb87a1d

**Comment by tnir** [comment]
@ridiculousfish Thanks 👍
