### ISSUE TITLE
Downgrading 3.0 on MacOS with Brew

### ISSUE THREAD

**Issue by joshmedeski** [fish-shell/fish-shell#5497]
How do I downgrade to v2.7.1 with Homebrew on MacOS? Help would be appreciated 😄

**Comment by zanchey** [comment]
You might be better off asking in the Homebrew issues, but here are some things to try.

If you haven't run `brew cleanup`, you probably still have 2.7.1 installed. Try `brew list --versions fish`. 

If 2.7.1 is there, you can run `brew switch fish 2.7.1` and then `brew pin fish` to keep it at 2.7.1.

If not, you might be able to do something like this:
```
cd (brew --repository homebrew/core)
git checkout 2827b020c3366ea93566a344167ba62388c16c7d -- Formula/fish.rb
brew remove fish
brew install fish
brew pin fish
git checkout master -- Formula/fish.rb
```

**Comment by joshmedeski** [comment]
Thanks, @zanchey this was very very helpful!

**Comment by halilertekin** [comment]
@zanchey  Thank u soo much. it's work.  👍

**Comment by Lordnibbler** [comment]
thank you
