### ISSUE TITLE
Fish hangs while trying to write a Git command after upgrading to 3.0

### ISSUE THREAD

**Issue by ktonga** [fish-shell/fish-shell#5499]
Version: 3.0.0
OS: Ubuntu 18.10
Term: Termite and Yakuake

It does not happen if I run fish with an empty home.

To reproduce it you just have to start writing a git command and as soon as you type the first char after the git sub-command it will hang forever (eg: `git checkout m`), not even attempting to complete with tab so might be related to suggestions maybe.
I let the terminal open for several minutes to see if it was just slow but it never comes back, I have to kill the terminal.

Let me know if you need any more info or help debugging it.

Cheers.

**Comment by mqudsi** [comment]
What theme are you using?

**Comment by ktonga** [comment]
@mqudsi `bobthefish`

**Comment by ktonga** [comment]
I'm closing this since I cannot reproduce it when I disable Oh My Fish. Sorry about the noise.

**Comment by vonpupp** [comment]
I am actually having an issue that sounds pretty much as your description and I am also using bobthefish and fish 3.0. Both my computers started to behave weird after I upgraded. Did you manage to solve this?

**Comment by ktonga** [comment]
@vonpupp Not really. I was only able to narrow it down to "has something to do with OMF", so I have it disabled by now and I opened this issue https://github.com/oh-my-fish/oh-my-fish/issues/672 but I haven't heard from then yet.

**Comment by vonpupp** [comment]
Thank you @ktonga, I will give a thumbs up on that issue since I am having the same issue. It seems to be related with OMF + git, whenever I am within a git repo, it is highly probable that the terminal hangs, it is becoming unusable. I will have to disable OMF also.
