### ISSUE TITLE
yarn completions: Missing "--file"

### ISSUE THREAD

**Issue by cvlmtg** [fish-shell/fish-shell#5502]
```
 ~ fish --version
fish, version 3.0.0
 ~ echo $version
3.0.0
 ~ uname -a
Darwin mecbucpro.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
 ~ echo $TERM
xterm-256color

terminal: kitty
```

there's a strange behaviour regarding path autocompletion which I don't understand. I've tested the problem with `sh -c 'env HOME=$(mktemp -d) fish'` as suggested and the issue persists.

If I type, e.g.

```
yarn run standalone --file ~/Downl
```

and then press tab to autocomplete the path, fish complains and doesn't allow me to complete the path. obviously if I type

```
ls ~/Downl
```

autocompletion works. I don't understand why it doesn't work when trying to write the arguments to my other command. BTW If I type enough to make the suggestion appear, I can complete it with the right arrow, but the Tab key still refuses to work.

thanks!

**Comment by faho** [comment]
The problem here is the `~`.

Scripted completions receive that literally, and then pass it on literally. But `~` isn't actually a valid path (well, most likely not), it's expanded to /home/whatever.

**Comment by cvlmtg** [comment]
It's not the `~`. even If I try without it, I still can't get tab completion to work. only the right arrow completion works

**Comment by faho** [comment]
Okay, it seems like the `yarn` completions don't know about the "--file" option.

**Comment by cvlmtg** [comment]
no it doesn't because it's not an option of yarn, it's an option of a script I put in my package.json. does fish need to know every option of every command to complete a path? can't it just complete it by default? completion trough suggestions works, so I expect to have tab completion work in the same manner too

**Comment by zanchey** [comment]
I think the problem here is that the yarn completions set `--no-files` aka `-f` on the arguments to `yarn run` - see https://github.com/fish-shell/fish-shell/blob/master/share/completions/yarn.fish#L146-L156

**Comment by cvlmtg** [comment]
@zanchey mh... If I understand it correctly the purpose is: "when the argument to `yarn` is `run`, complete the script name from package.json", which is really nice, but in my example the script name has already been entered and then I added other options, so file completions could be enabled again. is this a limitation of fish completion mechanism?

**Comment by faho** [comment]
>is this a limitation of fish completion mechanism?

It's not. The script simply needs to be adjusted.

**Comment by cvlmtg** [comment]
ok thanks :)

**Comment by ridiculousfish** [comment]
Picked into 3.0.1 as ec77135cf28f3ab6e62fb98459c5f9232eb4956a
