### ISSUE TITLE
Fish "forget" commands after upgrading to 3.0.0

### ISSUE THREAD

**Issue by YevhenKap** [fish-shell/fish-shell#5503]
After upgrading fish to 3.0.0 version by brew I tried to install Flutter, but this command 
```bash
export PATH=$PATH:[PATH_TO_FLUTTER_GIT_DIRECTORY]/flutter/bin
```
always throw this error and then any command doesn't executed.
```bash
fish: Unknown command 'basename'
~/.config/fish/functions/fish_prompt.fish (line 1): 
basename (prompt_pwd)
^
in command substitution
	called on line 34 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input

fish: Unknown command 'git'
~/.config/fish/functions/fish_prompt.fish (line 1): 
command git symbolic-ref HEAD ^/dev/null | sed -e 's|^refs/heads/||'
        ^
in command substitution
	called on line 5 of file ~/.config/fish/functions/fish_prompt.fish

in function '_git_branch_name'
	called on line 11 of file ~/.config/fish/functions/fish_prompt.fish

in command substitution
	called on line 36 of file ~/.config/fish/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input
```
**fish --version** - fish, version 3.0.0
**echo $version** - 2.7.1
**uname -a** - Darwin MacBook-Pro-Kapelianovych.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
**echo $TERM** - xterm-256color
After executing 
```bash
sh -c 'env HOME=$(mktemp -d) fish'
```
error aren't throwing, but commands are still unknown.

**Comment by faho** [comment]
You're still running 2.7.1. I suggest restarting your terminal.

Am Mi., 9. Jan. 2019, 18:35 hat Yevhen <notifications@github.com>
geschrieben:

**Comment by YevhenKap** [comment]
@faho I restarted terminal and execute 
```bash
brew cleanup```
Also I tried reinstall fish. The problem is the same.

**Comment by faho** [comment]
Argh.... you're doing the posixy thing!

In fish, $PATH is a list. And lists expand like brace expansions, in a
cartesian product.

That means `PATH=$PATH:something` will expand to `PATH=$PATH[1]:something
PATH=$PATH[2]:something` and so on. Which will confuse the export function
(it'll set PATH again and again and again), and it will end up setting
$PATH to a bogus value (its last element and the "something").

In 3.0, just quoting this should work - `export "PATH=$PATH:something"`.

Thr fishy way to do this is to use `set --append PATH something`.

Am Mi., 9. Jan. 2019, 20:45 hat Yevhen <notifications@github.com>
geschrieben:

**Comment by YevhenKap** [comment]
@faho Yeah... You are right:
```bash
set PATH $PATH /Users/{username}/flutter/bin 
```
This command append Flutter binaries to PATH and the problem is gone. This is my fault. Thanks for help!
