### ISSUE TITLE
Poll: What Fish shell version do you depend on?

### ISSUE THREAD

**Issue by edouard-lopez** [fish-shell/fish-shell#5507]
**related:** rafaelrinaldi/pure#123

---

As a maintainer of `pure` theme I'm trying to get a sense of **versions usage of fish shell**, in order to elaborate our support strategy (bug, tests, etc.).

To help get an understanding, I created **a poll**, it will only take a few second to contribute:

> [What Fish shell version do you depend on?](https://framadate.org/MHFdhP4OHGnKrbFD)

Thanks :heart:

**Comment by zanchey** [comment]
You might be better off posting this on the fish-users mailing list.

**Comment by floam** [comment]
A fish-shell issue isn't really the right place to try to gather feedback to guide development of this neato prompt. That's nothing against the pure project - a GitHub issue *could* be the right place to, for example, discuss the idea of upstreaming a prompt like pure into fish-shell proper. As @zanchey points out, the fish-users mailing list might be a more appropriate place to try to get feedback.
