### ISSUE TITLE
resolving a full path from $CDPATH

### ISSUE THREAD

**Issue by nhooyr** [fish-shell/fish-shell#5508]
Lets say I have `~/code` in my `$CDPATH` and I want to edit a file `~/code/meow/bar.foo`.

I want to be able to do something like `vim (cdp meow/bar.foo)` which will expand to `vim ~/code/meow/bar.foo`. This functionality could also be provided via additional syntax to make it more clean.

Effectively, I'd like to turn `$CDPATH` not into a directories i just CD into, but a list of my favourite directories with subdirectories that have important files in them where I don't want to cd into a dir every time I want to access a file.

Also see #5504

**Comment by faho** [comment]
This is actually quite simple to write:

```fish
function cdp
    for arg in $argv
        for path in $CDPATH
            if test -e $path/$arg
                echo $path/$arg
                break
            end
        end
   end
end
```

**Comment by nhooyr** [comment]
Thanks that works great for me. But why loop over `$argv`?

**Comment by faho** [comment]
Loop over $argv so you can pass multiple arguments and get the first match
for each.

I.e. `cdp banana sausage` is valid and will do a sensible thing - print the
first banana and the first sausage in CDPATH.

To make completions, you'd have to basically print all directories inside
$CDPATH, onlx removing the CDPATH component again.

```fish
for dir in $CDPATH
    # the trailing / is so we match only directories.
    set -l matches $dir/*/
    string replace -- $dir/ '' $matches
end
```

Advanced usage incorporates the current commandline token (`commandline
-ct`) to go deeper - you probably don't want to match the complete
hierarchy (or you could use `**`).

Am So., 13. Jan. 2019, 21:27 hat Anmol Sethi <notifications@github.com>
geschrieben:

**Comment by zanchey** [comment]
I don't think we'd merge something like this to be distributed with fish - there's a few sharp edges (eg files vs directories) and it doesn't seem to be a particularly common use case, so I agree with @faho in tagging this as a question only.

**Comment by nhooyr** [comment]
> there's a few sharp edges (eg files vs directories

Not sure what you mean, what are the sharp edges?

> it doesn't seem to be a particularly common use case

Why doesn't it seem to be a common use case? I can definitely see people who use `$CDPATH` to want to access one particular file in it but not cd into it.

**Comment by zanchey** [comment]
`some_command (cdp foo)` will act on a file or directory named foo and there's no way of knowing what `some_command` will accept. Mind you, * has that problem at present.

**Comment by nhooyr** [comment]
It'd be nice if you could use `tab` to expand a command substitution or `*`.

**Comment by floam** [comment]
Interesting idea.

**Comment by nhooyr** [comment]
I'll file that as a separate issue.

**Comment by faho** [comment]
Okay, the question has been answered.
