### ISSUE TITLE
Informative VCS prompt is one character short in Chrome terminal

### ISSUE THREAD

**Issue by cflewis** [fish-shell/fish-shell#5509]
```
/t/cursortest (master|✔) $ fish --version
fish, version 3.0.0
/t/cursortest (master|✔) $ echo $version
3.0.0
/t/cursortest (master|✔) $ echo $TERM
xterm-color
```

# Repro:
1. Use the [Chrome SSH Extension](https://chrome.google.com/webstore/detail/secure-shell-app/pnhechapfaindjhompbnflcldabbghjo?hl=en) to SSH into your machine
2. Use the Informative VCS prompt
3. Use VI mode (may or may not be related, I am not sure)
4. Create a Git repository

# What I expect to see:
The cursor appear at the end of the line like it does when the VCS output doesn't exist.

# What I see instead:
The cursor is one character behind the end of line, and is sat on top of the last character.

![screenshot 2019-01-10 at 9 16 55 am](https://user-images.githubusercontent.com/43708/50985730-e8474180-14b9-11e9-9c91-58f4c5af7d57.png)

This seems to happen using various VCS type prompts to varying degrees (such as the cursor sitting halfway from the end, which was super weird).

I haven't seen this in other shells like ZSH, but I am happy to accept a quick and dirty hack for my `config.fish` that might fix this, as I expect it might be a Chrome SSH thing. I do not have the problem on my local machine using `gnome-terminal`.

**Comment by mqudsi** [comment]
fish and chrome's shell are disagreeing over the width of a character (almost certainly the emoji checkmark). If you use a non-emoji characters instead the issue would go away.

I'm pretty sure this is a bug in the javascript terminal, as the checkmark is fairly well supported on other terminals.

**Comment by cflewis** [comment]
This sounds entirely reasonable.

Is there a (simple) way to switch between prompts whether I am SSH'd or not? If not I'll just suck it up, but it would be nice to not have to squint when SSH'd 😄

**Comment by mqudsi** [comment]
Yup, you can use `if [not] set -q SSH_CLIENT` in your `config.fish` to gate the prompt.

**Comment by zanchey** [comment]
You can customise the characters used in the prompt as well, with the `__fish_git_prompt_char_cleanstate` variable and its friends: https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_git_prompt.fish#L663-L674

**Comment by cflewis** [comment]
@zanchey : Genius!

I used `set -g __fish_git_prompt_char_cleanstate "="` to get rid of the Unicode. I think this will fix it.

Thank you for all the help!

**Comment by mqudsi** [comment]
And then you can take it to the next level by only doing that if `SSH_CLIENT` is set and you’ll be golden.
