### ISSUE TITLE
return inside while does not return correct status

### ISSUE THREAD

**Issue by orefalo** [fish-shell/fish-shell#5513]
This was working fine in fish 2.0 now with 3.0 this is what I get

```fish
function read_confirm
        while true
              read -l -P 'Do you want to continue? [y/N] ' confirm

              switch $confirm
                    case Y y
                          return 0
                    case '' N n
                          return 1
              end
        end
  end

if read_confirm
        echo 'Do stuff'
  end
Do you want to continue? [y/N] n
Do stuff

if read_confirm
        echo 'Do stuff'
  end
Do you want to continue? [y/N] y
Do stuff
```

no matter the answer... y/n.. the function always return 0

no wonder why all my scripts are failing?!

**Comment by orefalo** [comment]
forgot to mention - fish 3.0.0/osx brew

**Comment by faho** [comment]
The issue is actually `while`:

```fish
function a
    while true
        return 1
    end
end

a
echo $status # prints 0???

This seems to be caused by #4982.

**Comment by mqudsi** [comment]
I fixed this and added some regression tests. This should definitely be included in 3.0.1 (and makes it imperative that we do a 3.0.1 release asap, even if other issues are not yet fixed and that means we need a 3.0.2 later).

**Comment by orefalo** [comment]
tks

**Comment by orefalo** [comment]
confirmed working, installed with

```
brew unlink fish
brew install fish --HEAD
```

also seemed to have fixed the intermittent auto-complete lockups I was getting from time/time

**Comment by orefalo** [comment]
Maybe a push to brew will hold all these Mac users who are wondering why fish locks up are behaves different than expected ;-/

```
brew info fish
fish: stable 3.0.0 (bottled), HEAD
User-friendly command-line shell for UNIX-like operating systems
https://fishshell.com
```

version still shows as 3.0.0

tks

**Comment by floam** [comment]
3.0.1 isn't released yet, he was noting that we've cherry-picked the fix for this issue in our branch where we are preparing for a 3.0.1 release.
