### ISSUE TITLE
Valid path highlighting broken

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#5514]
```
$ fish --version
fish, version 2.7.1-1971-g6c9065e9
```

From [Gitter](https://gitter.im/fish-shell/fish-shell?at=5c386929317e2407cd149594):

> Seems a recent commit has broken valid path highlighting:
> 
> ![image](https://user-images.githubusercontent.com/8544900/51027173-198e4300-1588-11e9-9710-744be02b7a46.png)
>
> But `a/b/c` exists and the `cd` succeeds.

**Comment by zx8** [comment]
Seems this applies to abbreviations as well:

![image](https://user-images.githubusercontent.com/8544900/51028048-4f342b80-158a-11e9-9798-7160b948b301.png)

**Comment by floam** [comment]
I think @ridiculousfish fixed this in 82170b0862f61e3d845aa9da2fae2d8d174fcc7f

**Comment by zanchey** [comment]
Still broken for me 82170b08 (master); bisects to 3b170918

**Comment by faho** [comment]
This works for me again with db1d694ae. I can confirm 6c9065e9e as broken.

**Comment by zanchey** [comment]
Yep, confirmed fixed.
