### ISSUE TITLE
Add kubectl completions

### ISSUE THREAD

**Issue by xordspar0** [fish-shell/fish-shell#5516]
It would be great if fish had completions for kubectl subcommands and resources, but is it really possible? Certainly we could do subcommands, but the resources vary from server to server.

This is similar to Gradle tasks. It looks like [Gradle completions](https://github.com/fish-shell/fish-shell/blob/master/share/completions/gradle.fish) are done by running `gradle tasks` and parsing the output. We *could* do that with `kubectl get`, but doesn't that mean going over the network to the server and asking what resources it allows?

Alternatively, we could just have a static list of common resources.

Finally, kubectl has a built-in feature to generate completions for bash and zsh. Maybe support for fish should be added at that end instead. This would either require adding fish support to the [cobra](https://github.com/spf13/cobra) library (with would be great) or building a custom completion generator into kubectl itself.

Any other ideas? Whatever we decide, I'm eager to do the work for this and submit a PR.

**Comment by xordspar0** [comment]
I just found that there's an open PR in cobra that would allow kubectl to generate its own completions: https://github.com/spf13/cobra/pull/754

Maybe it's better to let kubectl take care of this on its own? I'm not sure what fish's preference is for where completions live.

**Comment by zanchey** [comment]
Definitely preferred upstream. That way they stay in sync with the features offered.

**Comment by zanchey** [comment]
Let's leave this to the upstream project.
