### ISSUE TITLE
fish_title has extra spaces

### ISSUE THREAD

**Issue by jadenPete** [fish-shell/fish-shell#5517]
This is a very simple bug, so I'm not going to provide unnecessary information. The `fish_title` function displays extra spaces, and it should be changed from:

```
function fish_title
    echo (status current-command) " " (__fish_pwd)
end
```

to:

```
function fish_title
    echo -s (status current-command) " " (__fish_pwd)
end
```

**Comment by zanchey** [comment]
This goes all the way back to 2005! I'm wondering if it was intentional, although I think it's fine to remove.
