### ISSUE TITLE
Handling of symlink home directories

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#5525]
On 3.0.0 and master, starting a shell with a home directory that is a symlink resolves the link, meaning that the prompt makes it look like you aren't in your home directory.

```fish
> mkdir /tmp/realhome
> ln -s /tmp/realhome /tmp/linkhome
> cd /tmp/linkhome
> pwd
/tmp/linkhome
> env HOME=/tmp/linkhome fish
Welcome to fish, the friendly interactive shell
zanchey@mussel /t/realhome>
```

**Comment by mqudsi** [comment]
This same behavior led me to open #5300. I agree that this behavior is unexpected.

**Comment by mqudsi** [comment]
I should mention that under FreeBSD the default home directory for each user is a symlink `/home/jdoe` pointing to `/usr/home/jdoe`.

**Comment by ridiculousfish** [comment]
Cool, here's what would help
```
$ gdb fish
...
Program received signal SIGSEGV, Segmentation fault.
0x000000000048aa4c in env_get_runtime_path[abi:cxx11]() ()
(gdb) quit
A debugging session is active.

	Inferior 1 [process 19601] will be killed.

Quit anyway? (y or n) 
```

From within gdb, it would be good to get a backtrace `bt`, a thread list: `info threads`, and a register dump: `info registers`

**Comment by floam** [comment]
This is the wrong issue I believe, @ridiculousfish

**Comment by ridiculousfish** [comment]
Whoops, thanks!

**Comment by ridiculousfish** [comment]
This is totally baffling! fish has code [that respects incoming PWDs](https://github.com/fish-shell/fish-shell/blob/3847d2e9d1b96293407d331dea986c4757e39f13/src/env.cpp#L1009), and only asks the kernel for help (via `getcwd`) if $PWD is not provided as an incoming environment variable.

What I see is that `env` shows that $PWD is set, but fish doesn't see it in `envp`. As I said, baffling...

**Comment by ridiculousfish** [comment]
Picked into 3.0.1 as dfa61926e8f48a012872873e8b889c02401d898e
