### ISSUE TITLE
Highlighting: Parentheses matched with $fish_color_operator instead of $fish_color_match

### ISSUE THREAD

**Issue by serban** [fish-shell/fish-shell#5527]
## Expected Behavior

Parentheses are highlighted with `$fish_color_match`, as per the documentation:

> The following variables are available to change the highlighting colors in fish:
>
> fish_color_match, the color used to highlight matching parenthesis
> fish_color_operator, the color for parameter expansion operators like '*' and '~'

## Observed Behavior

Parentheses are highlighted with `$fish_color_operator`.

## Environment

```
$ fish --version
fish, version 3.0.0

$ echo $version
3.0.0

$ uname -a
Darwin iMac 17.7.0 Darwin Kernel Version 17.7.0: Fri Nov  2 20:43:16 PDT 2018; root:xnu-4570.71.17~1/RELEASE_X86_64 x86_64

$ echo $TERM
xterm-256color
```

## Steps To Reproduce

```
$ set -g fish_color_match blue
$ set -g fish_color_operator magenta
$ echo outer (echo inner)
```

Observe that the parentheses are highlighted magenta, not blue.

## Demo

[![asciicast](https://asciinema.org/a/221201.svg)](https://asciinema.org/a/221201?t=12)

**Comment by floam** [comment]
This actually works as expected. 

emphasis mine:
> fish_color_match, the color used to highlight **matching parenthesis**

Fire up `read` and type in `foo ( bar )`, leaving the cursor next to the right parenthesis. both matching parenthesis will get the background color likely set for `fish_color_match`. It's indicating the nearby parenthesis that matches the one next to your cursor. This is the only place where we highlight matching parenthesis. It's a lamer type of highlighting for when we can't expect fish code to be entered and thus can't do syntax highlighting. The highlighter used at the prompt for syntax uses the foreground color from `fish_color_operator`, which is more appropriate.

**Comment by floam** [comment]
It could be cool to additionally tint the background color for parens, quotes, etc. that match up with the one under the cursor in our syntax highlighting, like some text editors do, but someone would need to improve the feature a lot before you would want that. Play around with `read` a bit, and you'll see that just moving the cursor around with the arrow keys messes it up and it's a pretty lame feature as-is.

**Comment by zanchey** [comment]
Sounds like this is working as intended.
