### ISSUE TITLE
math: expression is bogus

### ISSUE THREAD

**Issue by dwrz** [fish-shell/fish-shell#5533]
- I'm on `fish` `3.0.0`.
- Arch Linux, kernel 4.20.1 x86_64
- $TERM: rxvt-unicode-256color

With my regular setup, and using the `omf/bob-the-fish` theme, I occasionally get this output:

```
math: Error: Expression is bogus
'scale=1;15081/1000'
```
I haven't been able to replicate this with `sh -c 'env HOME=$(mktemp -d) fish'`, so perhaps the issue is with how the theme invokes `math`.

Upgrading to `3.0.0` is what caused this issue to come up on two machines.

**Comment by faho** [comment]
Fish 3 features a new `math` builtin that is no longer a simple function that wraps bc. In particular, it makes no effort to present a programming-ish language, and sticks to the math, but instead offers modulo _and_ floats at the same time.

So you're gonna have to port your expression. Fortunately it's quite simple because bc's scale option was exposed as math's `-s` option a while back (and later a long `--scale` version was added).

So this is:

```fish
math -s1 15081/1000
```

**Comment by faho** [comment]
Wait, the bobthefish theme [already does that for any fish >= 2.4.0](https://github.com/oh-my-fish/theme-bobthefish/blob/4ccdd7bdcfd615e991321dbc811be69d3b94f2d7/fish_right_prompt.fish#L44-L50).

@dwrz: What are you doing when this happens? Presumably you are running a command that runs longer than 5 seconds (https://github.com/oh-my-fish/theme-bobthefish/blob/4ccdd7bdcfd615e991321dbc811be69d3b94f2d7/fish_right_prompt.fish#L11-L21), but what kind of command, and what are you doing in the meantime?

**Comment by dwrz** [comment]
Thanks so much, @faho. The command that I used to get the error is an alias that updates the Arch mirrors and then updates all packages -- it usually takes longer than 5 seconds. I didn't do anything else after issuing the command. I don't think I did anything else after issuing the command, though.

Running `sleep` with 1, 5, and 10 seconds didn't result in the error from `math`, though...

**Comment by floam** [comment]
The machine that is having the issue has a prompt installed that is not fully compatible with fish 3.0.

**Comment by faho** [comment]
@dwrz: Can you try updating the bobthefish theme?

The required change isn't all that new, but it's still possible that you're missing it.

**Comment by dwrz** [comment]
@faho -- thanks so much again for your help. That was it.
