### ISSUE TITLE
fish_config Bindings tab summarizes every bind as "--preset"

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#5534]
Yikes, this has not been right since `--preset` was added to `bind`.

<img width="1098" alt="bind" src="https://user-images.githubusercontent.com/291142/51215176-f55a9b00-18d4-11e9-9d6c-c78ebd115e11.png">

**Comment by faho** [comment]
Yup, sorry! Mea culpa!

**Comment by ridiculousfish** [comment]
Picked into 3.0.1 as 72423c517a788843caa0f7cfaf99aa32b4b9a5fa
