### ISSUE TITLE
Ability to load history from a file

### ISSUE THREAD

**Issue by ideasman42** [fish-shell/fish-shell#5538]
fish, version 3.0.0

Both bash and zsh have the ability to load history from a file, eg:

bash: `history -r ~/.shell_history_permanent`
zsh: `fc -R ~/.shell_history_permanent`

This is useful since I like to clear my history periodically, but keep some commands always in the history for reference.

From fishes `history --help` it seems this isn't possible:

Suggest `history read` subcommand to load in history from a file, with the option to add before/after current history.

**Comment by zanchey** [comment]
I mean, I guess? I think we'd take a patch for that.

> This is useful since I like to clear my history periodically, but keep some commands always in the history for reference.

This seems like loads of work, which fish's history recall is designed to eliminate for you.

You can also delete history items, if that's more helpful.

**Comment by ridiculousfish** [comment]
I don't think we need a special command for this. It's OK to just overwrite the history file, and fish will notice and start using it. Thanks for filing!
