### ISSUE TITLE
Documentation outdated for searching within tab completions

### ISSUE THREAD

**Issue by undergroundquizscene** [fish-shell/fish-shell#5547]
At [the current documentation page](https://fishshell.com/docs/current/index.html#completion), tab completion is still described as only requiring the user to type once they’ve entered the suggestions list. However, the behaviour has changed (as pointed out [here](https://github.com/fish-shell/fish-shell/issues/4749)) to require activating the search feature.

**Comment by ridiculousfish** [comment]
Picked into 3.0.1 as 88ee55443cd6001a74db799c58e58d268ad01ec4
