### ISSUE TITLE
Junk before prompt at FreeBSD vty with sc driver

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5552]
This has bugged me for a while but I've never filed it. On the "physical" vty under FreeBSD, fish emits some invalid/unrecognized character codes that appear as garbled letters *before* each `fish_prompt` call.

Here's a screenshot (clean fish install from `master`):

![image](https://user-images.githubusercontent.com/606923/51419201-28f42a00-1b4e-11e9-8301-8dc419f3cedc.png)

If using the new `vt` (aka `newcons`) console driver (used by KMS drivers and the UEFI framebuffer), the problem goes away:

![easyre deployment freebsd 12 -2019-01-18-18-26-44](https://user-images.githubusercontent.com/606923/51419266-ab7ce980-1b4e-11e9-8bd9-cb19275befdc.png)

It's not a huge deal since `vt` is the default on FreeBSD 11 and up, but `sc` is still supported (and required if you want to use a driver without KMS support).

However, it bugs me because there's nothing funky in the default prompt that should result in this behavior in the first place, as it's all ascii and standard color escapes (which seem to be working fine). The default `$TERM` at the console is `xterm` for both drivers, and the problem persists under `tmux` where `$TERM` defaults to `screen` instead.

**Comment by floam** [comment]
I think that's the omitted newline character.

**Comment by mqudsi** [comment]
Why would that be triggered in the default prompt, though? Unless it's the "always emit then try to hide it" problem showing up.

**Comment by floam** [comment]
@mqudsi It wouldn't be coming from the prompt. I don't think you'll see it before the first printed prompt. It will happen after things are executed. The way the character works is that it's always emitted but yes, hidden, unless the last thing printed did not have a newline after it.

**Comment by floam** [comment]
And so there are two issues you're seeing with the old console driver: it can't render the glyph, and also it is always shown. 

In the newer console if you do a `printf foo`, do you see those two incorrect characters or something that actually renders?

**Comment by mqudsi** [comment]
F

**Comment by floam** [comment]
I agree on the `read` obfuscation character - \u2022 renders just as nicely here and is more likely to be supported by various fonts. I think that can be changed across the board.

I agree that the pilcrow is ideal for a lot of situations due to how many kernel's consoles always have the glyph, however our current glyph I like more on terminal emulators with basically any fonts available. We've used it for a long, long time with not many complaints of missing glyphs. Maybe we could guess based on if it seems we're in a vt or not (by looking for a lack of fancy terminfo attributes?).

**Comment by mqudsi** [comment]
The related issues are #789 and #3672. In particular, the discussion in #789 contains valuable information that may possibly be used to better improve the detection of end-of-line behavior or else to force it.
