### ISSUE TITLE
ConPTY - a hope for native Windows version

### ISSUE THREAD

**Issue by Kenya-West** [fish-shell/fish-shell#5554]
Microsoft introduced [Windows Pseudo Console (ConPTY)](https://blogs.msdn.microsoft.com/commandline/2018/08/02/windows-command-line-introducing-the-windows-pseudo-console-conpty/) infrastructure and API, which is available in the latest Windows 10 October 2018 update. This update (finally!) started rolling out as automatic for all Windows users two days ago.

Windows Console (includes CMD, Powershell, and Linux shells) [supports VT](https://blogs.msdn.microsoft.com/commandline/2018/12/10/new-experimental-console-features/), advanced coloring, different cursors and [other stuff](https://blogs.msdn.microsoft.com/commandline/) can be seen only in Linux. With all these innovations, it becomes easier to port any Linux-compatible solution to Windows 10.

It's time to implement the native solution to a OS that starts getting friendly to developers!

**Comment by faho** [comment]
We have no interest in that at this time.

Fish runs fine on WSL.
