### ISSUE TITLE
Elegant solution for repeating the last command with sudo?

### ISSUE THREAD

**Issue by Siilwyn** [fish-shell/fish-shell#5560]
After upgrading from fish 2 to 3 I found my alias to sudo the last command to not remove itself from history. This is the alias:
```sh
alias doh='commandline -i "sudo $history[1]"; history delete --exact --case-sensitive "$history[1]"'
```

Now `doh` shows up in my history, what is a nice solution for Fish 3.0? Also I don't mind if the previous command is immediately executed.

Sorry about this silly question. :P

**Comment by avarun42** [comment]
You could try the "thefuck" python program. It's a little bit overkill for your needs but it has fish support https://github.com/nvbn/thefuck/wiki/Shell-aliases

**Comment by Siilwyn** [comment]
Oof that is a solution but quite a heavy one by the looks of it, if anybody has an alternate lightweight solution I'm all ears.

**Comment by zanchey** [comment]
I still get `doh` in my history on 2.7.1, as the history deletion removes the original command, not the execution of `doh`; my suggestion is to create a binding instead:

`bind \cg doh` binds Ctrl-G to run the `doh` function.

**Comment by jorgebucaran** [comment]
@Siilwyn I thought I might look at this. The following works for me in fish **3.0**.

```fish
alias doh='commandline -i "sudo $history[1]";history delete --exact --case-sensitive doh'
```

```
$ alias doh='commandline -i "sudo $history[1]";history delete --exact --case-sensitive doh'
$ sleep 1
$ doh
$ sudo sleep 1
Password: **
$ printf "%s\n" $history | awk 'NR<4'
sudo sleep 1
sleep 1
alias doh='commandline -i "sudo $history[1]";history delete --exact --case-sensitive doh'
$ 
```

And `doh` is not in `$history` as you can see.

**Comment by Siilwyn** [comment]
@jorgebucaran cheers!
