### ISSUE TITLE
read echoes input when not run interactively

### ISSUE THREAD

**Issue by InspectorMustache** [fish-shell/fish-shell#5562]
I thought this was related to #5519 and maybe it is but the problem still persists for me after the commit that fixed that issue so I'm opening another one.

Whether or not I'm using the `--silent` flag, when I run `read` non-interactively, it always echoes the input.
```
$ fish -c 'read'
read> bla
bla
$ fish -c 'read --silent'
read> ●●●
bla
```

I'm on ArchLinux and I tried this with termite, xfce-terminal and alacritty.

**Comment by faho** [comment]
Works for me.

Please check `fish --version` - most likely that's opening a fish that doesn't have that commit (https://github.com/fish-shell/fish-shell/commit/3cc581fbb024cf40a26fc1ec82d3b6c32a53f7b0)

**Comment by floam** [comment]
Are you not expecting read to print the actual string it was passed? How could `read` work when used in a command substitution then? It won't print anything to stdout if you give it a variable name to use.

**Comment by InspectorMustache** [comment]
Erm... yeah, good point. How embarrassing. Sorry for wasting your time.
