### ISSUE TITLE
Subcommand 'current-command' is not valid

### ISSUE THREAD

**Issue by mathpunk** [fish-shell/fish-shell#5563]
When I upgrade to fish 3.0.0, for any command I issue, I get `status: Subcommand 'current-command' is not valid` before and after the output. For some commands, I get errors in what looks like the function definitions. For example, 

```
$ history
status: Subcommand 'current-command' is not valid
set: Unknown option “-a”
/usr/share/fish/functions/history.fish (line 20): 
    set -a options 'h/help' 'c/contains' 'e/exact' 'p/prefix'
    ^
in function “history”
        called on standard input

set: Unknown option “-a”
/usr/share/fish/functions/history.fish (line 21): 
    set -a options 'C/case-sensitive' 'R/reverse' 'z/null' 't/show-time=?' 'n#max'
    ^
in function “history”
        called on standard input

set: Unknown option “-a”
/usr/share/fish/functions/history.fish (line 24): 
    set -a options 'S-search' 'D-delete' 'M-merge' 'V-save' 'X-clear'
    ^
in function “history”
        called on standard input

argparse: No option specs were provided
status: Subcommand 'current-command' is not valid
```

However, if I try commands after cleaning the environment with `sh -c 'env HOME=$(mktemp -d) fish'`, these errors no longer occur.

System details:
```
$ fish --version
fish, version 3.0.0
$ uname -a
Linux manifold 4.14.91-1-MANJARO #1 SMP PREEMPT Sat Dec 29 15:40:39 UTC 2018 x86_64 GNU/Linux
$ echo $TERM
xterm-kitty
```

**Comment by floam** [comment]
In the terminal where you are getting the errors, do an `echo $version`. I suspect you have not restarted the shell session and are still on a previous version.

**Comment by mathpunk** [comment]
Ah, you're right. I was certain I'd restarted the shell but, nope, this does it. :roll_eyes:  Thanks!
