### ISSUE TITLE
Git prompt strange new line behaviour

### ISSUE THREAD

**Issue by benmezger** [fish-shell/fish-shell#5564]
For some reason, after upgrading to version `3.0.0`, whenever I am in a `git` repository, it randomly adds a new line when executing my `git` right prompt script. See `asciinema` video.

I am using [gitline](https://github.com/mengelbrecht/gitline) with [slim-fish prompt](https://github.com/mengelbrecht/slimfish).

Asciinema: https://asciinema.org/a/cJ7KOzLjyZhC9W1xsxXJYsL1x

Fish version: `fish, version 3.0.0`

```
$ uname -a
  Darwin MacBook-Pro-de-Ben.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64
$ echo $TERM
  xterm-256color
```

**Comment by ridiculousfish** [comment]
Thanks for filing. I watched the video but I wasn't able to see any errant newline. Can you perhaps highlight it in a screenshot?

**Comment by benmezger** [comment]
@ridiculousfish some some reason asciinema doesn't record the specific error. Here is a screenshot.

![image](https://user-images.githubusercontent.com/915606/51546669-d5365900-1e4b-11e9-82f0-682d533ce20a.png)

This happens on al git repositories.

**Comment by faho** [comment]
@benmezger: Your terminal and fish disagree on the width of a character in your prompt that only appears in git repositories.

Try `set -g fish_emoji_width 2`

**Comment by benmezger** [comment]
@ridiculousfish no go, fish still behaves the same. I wonder what has changed from version 2.7 to 3 that caused this.

**Comment by floam** [comment]
Try setting fish_emoji_width to 1.

**Comment by benmezger** [comment]
@floam still no go :( . Also, maybe it's good for me to mention I am using `tmux` on Iterm2

**Comment by faho** [comment]
Okay, it's possible this not an "emoji" (which for our purposes is a character that was narrow in Unicode 8 but wide in Unicode 9), but an ambiguous character, so you'd have to set a different variable:

```fish
set -U fish_ambiguous_width 1
```

(or 2).

**Comment by benmezger** [comment]
@faho same results, no go. I wonder why this is happening. It doesn't seem to have a unicode character anywhere except the right prompt.

**Comment by benmezger** [comment]
@faho thanks for the clarification. I have tried to set `fish_ambiguous_width` both in my config and in runtime, but still no luck. I have tried `fish_ambiguous_width` set to 1 and to 2, same with `fish_emoji_width` to 1 and to 2.

**Comment by faho** [comment]
@benmezger: That leaves a few possibilities for things to be wrong, unfortunately it basically requires you to remove some of your symbols from your prompt.

That is unless your terminal has some option to fix it, like "Treat ambiguous-width characters as double-width.". Changing that (and setting fish's setting to correspond) _might_ work if it treats any of the other characters also as ambiguous.

Or you've compiled fish to use the system-provided wcwidth, in which case all those variables had no effect (sorry about that!), and you might want to change it to use the included one. How did you install fish?

Or tmux is interfering with any of this (you don't have a split open, do you?)?

**Comment by benmezger** [comment]
@faho I think I managed to fix it. I have set `fish_ambiguous_width` to 1 and disabled "Ambiguous characters are double-width" and "Use Unicode version 9 widths" in iTerm2 (Profiles -> Text). I have then uninstalled `fish` which I installed using `homebrew`, and recompiled manually using `fish`'s `wcwidth`.

I will close this issue and reopen in case this happens again.
