### ISSUE TITLE
fish doesn't work on Windows10 + msys2

### ISSUE THREAD

**Issue by cjun714** [fish-shell/fish-shell#5569]
fish --version: 3.0.0

fish doesn't work on window10 + msys2.
I have reinstalled msys2 and fish, but issue still exists.

``` shell
> pacman -S fish
> fish
D:/tool/dev/msys64/usr/bin/fish.exe: error while loading shared libraries: msys-pcre2-16-0.dll: cannot open shared object file: No such file or directory
> pacman -S pcre2
> fish --version
fish, version 3.0.0
> fish  <------------- dead here
```

Please help to check, thanks a lot!

**Comment by bitraid** [comment]
See issue #5426

**Comment by zanchey** [comment]
Yes, this is a duplicate of #5426 which we hope to have fixed in the upcoming 3.0.1. Thanks for filing though!

**Comment by mqudsi** [comment]
In the future please search past issues before filing. Thanks!

**Comment by VACUUMSONG** [comment]
pacman -S pcre2
pacman -S libpcre2_16
pacman -S mingw-w64-x86_64-pcre2
