### ISSUE TITLE
Valid path highlighting broken (containing variables)

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#5571]
Similar to https://github.com/fish-shell/fish-shell/issues/5514

```
$ fish --version
fish, version 3.0.0-217-gb23403ee
```

### Case 1

`$SCRIPT_PATH/1.sh` should not be highlighted as invalid/red:

![image](https://user-images.githubusercontent.com/8544900/51533588-40c3fa80-1e3b-11e9-8676-5b398fd7457b.png)

### ~Case 2~ (edit: see https://github.com/fish-shell/fish-shell/issues/5571#issuecomment-456457812 this is not a bug)
~`$SCRIPT_PATH/1.sh` should be underlined/valid as follows:~

![image](https://user-images.githubusercontent.com/8544900/51533698-85e82c80-1e3b-11e9-97e3-b35d8c5b5658.png)

~But instead is not:~

![image](https://user-images.githubusercontent.com/8544900/51533732-a1ebce00-1e3b-11e9-9a59-0ec2c8313a23.png)

**Comment by zx8** [comment]
@zanchey I think this is actually a regression?

**Comment by ridiculousfish** [comment]
Yeah we aren't providing the entire variable set to highlighting. I broke it and will fix it.

**Comment by ridiculousfish** [comment]
Good instinct but this is not broken in 3.0.0, only in master.
