### ISSUE TITLE
Abbreviations with punctuation characters no longer work

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#5573]
This abbreviation of mine worked in 2.7.1:

`abbr find. 'find . -name'`

Now, `abbr.<SPACE>` does not expand it.

**Comment by faho** [comment]
Still works in 3.0.1, but not in master.

@ridiculousfish: This kinda looks like the variable-sharing stuff again?

**Comment by floam** [comment]
From Gitter, a guy walked in wanting to alias `-` to `prevd`. In suggesting to him this could work well as an abbr, it was noticed that `abbr -- - foo` works in 3.0.2 but does not work in git master..

**Comment by floam** [comment]
I think this was busted by the commit that got rid of the case.
