### ISSUE TITLE
Allow `math --scale=max` for maximum digits

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#5579]
`math` should have an easier way of showing the maximum digits possible for floating point numbers than increasing `-s` until you get an error (15 currently, which corresponds to `FLT_DIG`. This could perhaps go up a little bit if we decided to use `long double` - I plan to do this to tinyexpr.cpp).

The most straightforward thing would be just letting the user pass -1 for a scale that is limited only by precision.

**Comment by faho** [comment]
Do we want just "-1", or also -2, -3 and so on, which seems kinda useless?

Or do we want `--scale=max`?

**Comment by floam** [comment]
> Do we want just "-1", or also -2, -3 and so on, which seems kinda useless?

Seems useless to me. The way I did it was just the special value of -1: https://github.com/floam/fish-shell/commit/cbb7fcbe1cb6464c1709de50c4ee9ebe5cdbd4e5

> Or do we want --scale=max?

That might be a better experience for the user.

**Comment by faho** [comment]
Fixed in ca5b7c0ec429f4581a9a592c1801bba4a14cb7e9.

**Comment by floam** [comment]
Cool!
