### ISSUE TITLE
Some Ctrl-Alt-* bindings switch to normal mode

### ISSUE THREAD

**Issue by InspectorMustache** [fish-shell/fish-shell#5581]
With `fish_vi_key_bindings` and `fish_hybrid_key_bindings`, some keybindings that use Control and Alt switch into normal mode, even though this isn't specified by what they're bound to. For example:
Ctrl+Alt+q
Ctrl+Alt+r
Ctrl+Alt+w
Ctrl+Alt+e
...

Is this because these bindings send an additional escape sequence?
I am using 3.0 on ArchLinux. I'm guessing this could be related to how X interprets keyboard sequences.

**Comment by faho** [comment]
@InspectorMustache: Ping?

**Comment by faho** [comment]
Closing for lack of response.

@InspectorMustache: If you're still interested, comment and we'll reopen.

**Comment by InspectorMustache** [comment]
Aaaah sorry! Yes, you are very much right, I hadn't bound these to anything and was unaware of the specifics of key processing. I have to admit, to me the way that keybindings are processed in the terminal seems like one of those unix (or whatever) relics that should be much more straightforward in the 21st century. But that might just be because I've been tripped up by this in a lot of TUI applications.
