### ISSUE TITLE
fish_config should print the commands it runs

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#5584]
`tools/web_config/webconfig.py` is the web server that runs fish commands. It should print at least some of the commands it runs, to help understanding and debugging. In particular it should print the commands for any changes made.

**Comment by floam** [comment]
I did this, but I'm not happy with how many pages of output are caused by setting the prompt.

I think rather than defining the function as a long command before it is `funcsave`ed, we could instead `source path/to/web_config/sample_prompts/...` and then `funcsave`.
