### ISSUE TITLE
Promote and document __fish_git_prompt

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#5586]
From #5555:

> The git prompt is the single most configurable part of fish; it probably deserves promoting to `fish_git_prompt` and documenting as a proper command.

**Comment by faho** [comment]
I've been working on this, and there's a few related questions to tackle:

- Do we keep a compatibility shim - a `__fish_git_prompt` that just calls `fish_git_prompt`?

- Do we also promote the other vcs-prompt functions? `__fish_hg_prompt`, `__fish_svn_prompt` and `__fish_vcs_prompt`? (it would even be possible to only promote vcs_prompt, to stop people from accidentally only picking git when making third-party prompts)

- Do we rename the helper functions (I vote no)?

- Do we rename the variables?

- Do we use this opportunity to revamp the git prompt? E.g. it has variables for when a segment is _done_, which seems barely useful - do you really want e.g. a different background color after the untracked files but before the stash state? For foregrounds this should essentially be a noop anyway unless the next segment has no color.

**Comment by faho** [comment]
Also $__fish_git_prompt_show_informative_status is an inconsistent variable name - it'd have to be `showinformativestatus` without all the underlines.

Also we still have the terlar git prompt, and some other sample prompts that do their own git thing.

**Comment by zanchey** [comment]
> * Do we keep a compatibility shim - a `__fish_git_prompt` that just calls `fish_git_prompt`?

Yes.

> * Do we also promote the other vcs-prompt functions? `__fish_hg_prompt`, `__fish_svn_prompt` and `__fish_vcs_prompt`? (it would even be possible to only promote vcs_prompt, to stop people from accidentally only picking git when making third-party prompts)

`vcs_prompt` sounds better.

> * Do we rename the helper functions (I vote no)?

No.

> * Do we rename the variables?

Ouch. Good question; the underscored names are not pleasant but a migration path might be difficult.

> * Do we use this opportunity to revamp the git prompt? E.g. it has variables for when a segment is _done_, which seems barely useful - do you really want e.g. a different background color after the untracked files but before the stash state? For foregrounds this should essentially be a noop anyway unless the next segment has no color.

The idea was to have feature parity with the bash git prompt, I think.

**Comment by faho** [comment]
Okay, searching for "__fish_git_prompt_color done" on github finds not a single match that isn't a copy of __fish_git_prompt.

It seems _nobody_ is using these variables.

**Comment by faho** [comment]
>The downside of fish_vcs_prompt is it will waste time looking for hg and svn working copies

For both, if they aren't installed this is just one `command -sq`. Which takes on the order of microseconds.

If hg is installed, we still check for .hg ourselves via `fish_print_hg_root`, which takes less than a millisecond (scaling linearly with directory depth).

This is entirely negligible, so I'd like to enable these by default. Which they have been for a while now. At least our sample prompts have, with the exception of nim and terlar been adjusted since 2.3.0.

>About the only thing that's even marginally useful is __fish_git_prompt_color_done

Yeah, I've thought about that as well.

Even there, I'm not sure if keeping it is worthwhile since I've not found _any_ use of it on github (searches just find copies of __fish_git_prompt).

**Comment by lilyball** [comment]
> For both, if they aren't installed this is just one `command -sq`. Which takes on the order of microseconds.

macOS has `/usr/bin/svn` so it's always present. And I do actually have `hg` installed, I just don't use it.

> This is entirely negligible, so I'd like to enable these by default.

Encouraging the use of `fish_vcs_prompt` is fine. But I'd like the git prompt to still be officially supported at a public name. Whether this name is `fish_git_prompt` or `__fish_git_prompt` I don't really care.

**Comment by mqudsi** [comment]
> macOS has `/usr/bin/svn` so it's always present.

Note for future reference and posterity: every FreeBSD install ships with a copy of `svn`... except it's an alternate implementation of the client called `svnlite` (and, as the name implies, lacks certain features).

**Comment by faho** [comment]
For some reason merging #5633 didn't close this.
