### ISSUE TITLE
Can't erase global variables

### ISSUE THREAD

**Issue by MikaAK** [fish-shell/fish-shell#5591]
- `fish, version 3.0.0`
- `Darwin Mikas-MacBook-Pro.local 18.2.0 Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64 x86_64`

- `xterm-256color`

`fish_user_paths` is being set into my global variables somehow even if I erase it using `set -eg fish_user_paths` upon opening a new shell it's still there and has more elements than my universal `fish_user_paths`. 

```
$fish_user_paths: not set in local scope
$fish_user_paths: set in global scope, unexported, with 3 elements
$fish_user_paths[1]: length=15 value=|/usr/local/sbin|
$fish_user_paths[2]: length=21 value=|/usr/local/opt/qt/bin|
$fish_user_paths[3]: length=17 value=|/Users/mika/n/bin|
$fish_user_paths: set in universal scope, exported, with 1 elements
$fish_user_paths[1]: length=17 value=|/Users/mika/n/bin|
```
=

**Comment by faho** [comment]
>$fish_user_paths: set in universal scope, exported, with 1 elements

It's set as a universal variable _and exported_. This means if you start a child process, that'll inherit it _as a global variable_.

Remove the export bit via `set -Uu fish_user_paths $fish_user_paths`.

>and has more elements than my universal fish_user_paths.

Do you have any third-party things? OMF and such? Those might be modifying it.

**Comment by faho** [comment]
@MikaAK: Ping?

**Comment by MikaAK** [comment]
I do have fisher installed, perhaps that's causing the issue?

**Comment by faho** [comment]
@MikaAK: Sure could. Well, fisher by itself probably not (I don't think it does anything if not explicitly called).

Check e.g. `grep -r "fish_user_paths" ~/.config/fish`. That probably includes `set -g fish_user_paths` somewhere.

**Comment by faho** [comment]
I'm assuming this has been solved. Feel free to comment here and we'll reopen!
