### ISSUE TITLE
Setting `export IGNOREEOF=66` in Fish shell?

### ISSUE THREAD

**Issue by llinfeng** [fish-shell/fish-shell#5593]
* Fish version: 2.7.1
* OS: Linux T 4.4.0-17763-Microsoft #253-Microsoft Mon Dec 31 17:49:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux

## Current understanding
* On Bash, Ctrl + D (`<c-d>`) will send `EOF` to the console, 
* Fish will exit when it sees an `EOF`.
* In `~/.bashrc`, if one specifies `export IGNOREEOF=66`, then, it will take a good number of `<c-d>`-pressing to eventually "accidentally" quit bash.
* Yet, per my Fish configuration, I cannot reproduce the bash behavior.

## Problem
Setting `export IGNOREEOF=66` did add a new environmental variable when inspecting through `set -xg`. However, when I press `<c-d>` multiple times (less than 66 times), the `EOF` will be issued nevertheless.

Does Fish assume an implicit upper bound for how many `EOF` it sees before eventually quitting the shell?

I have also tried the syntax with `set` command, but it did not register to the list of environmental variables. I tried `set IGNOREEOFF 67`, but did not see the new entry upon reloading Fish.

Please advise a proper way to implement the setting, so that accidental `<c-d>` won't quite the entire shell.

**Comment by faho** [comment]
>Please advise a proper way to implement the setting, so that accidental <c-d> won't quite the entire shell.

The way to bind c-d is to `bind \cd`. By default it is bound to "delete-or-exit". If you want one \cd to only delete, and two to delete-or-exit, do something like

```fish
bind \cd delete-char
bind \cd\cd delete-or-exit
```

**Comment by faho** [comment]
>Got an error after putting in bind --erase --preset \cd

"--preset" is new in fish 3.0. Sorry, I missed your version!

>Should it not go to ~/.config/fish/config.fish?

In 3.0, yes. Before that, you'll have to put it into a function called `fish_user_key_bindings`.

So you'd have to do

```fish
function fish_user_key_bindings

**Comment by llinfeng** [comment]
Great. It worked! I got the following to my `~/.config/fish/config.fish`, and things worked like magic!
```
function fish_user_key_bindings
    bind \cd delete-char
    #bind \cd\cd\cd\cd\cd exit
end
```
The snippet above has avoided `<c-d>` from issuing the scancode for `EOF`. If leaving line-3 uncommented, hitting 1 up to 4 times of `<c-d>` does not trigger anything, and hitting it for the fifth time shall issue an `EOF`.

**Comment by sshaikh** [comment]
FWIW on 3.1.2 (arch), I had to still put the bind erase in a function for it to be effective:

```
function fish_user_key_bindings
  bind --erase --preset \cd
end
```

However this isn't the case for a custom binding to \cd, so this also works, although you do end up with *something* assigned to \cd if you do:

```
bind \cd delete-char
```

My stab in the dark is that the default bindings check for assignment first, and happen after profile.fish.

**Comment by faho** [comment]
>FWIW on 3.1.2 (arch), I had to still put the bind erase in a function for it to be effective:

No, what you do if you wish to change a key to do *nothing*, is to bind it to `true` or a similar no-op instead:

```fish
bind \cd true
```

>My stab in the dark is that the default bindings check for assignment first, and happen after profile.fish.

You mean config.fish, and this is roughly correct. Bindings are indeed only set after config.fish, because you could set $fish_key_bindings there.

**Comment by sshaikh** [comment]
I'm slightly confused. From https://github.com/fish-shell/fish-shell/issues/5593#issuecomment-458270155:

> > Got an error after putting in bind --erase --preset \cd
> 
> "--preset" is new in fish 3.0. Sorry, I missed your version!
> 
> > Should it not go to ~/.config/fish/config.fish?
> 
> In 3.0, yes. Before that, you'll have to put it into a function called `fish_user_key_bindings`.

So what is the "correct" approach to disable ctrl-d from exiting the session? `bind --erase --preset` in a function or binding to a no-op?

I also see that `bind --erase --preset` works once you're in the session, so is its purpose just to temporarily unbind things? Why not just set it to `true`?

**Comment by faho** [comment]
>I'm using > 3.0 so I'm surprised I need the function.

You *don't* need the function to *add* keybindings (like the no-op binding).

The problem is that *erasing* before the function doesn't work, because the binding is only added *after config.fish*.

So you erase a non-existent binding, then fish goes and adds the binding, so erasing had no effect.

>So what is the "correct" approach to disable ctrl-d from exiting the session? bind --erase --preset in a function or binding to a no-op?

As a user, you shouldn't have to deal with `--preset` at all. Add the no-op.

**Comment by CWEzio** [comment]
```
    # require multiple c-d to exit the terminal
    bind \cd true
    bind \cd delete-char
    bind \cd\cd\cd delete-or-exit
```
I have added the above to my config.fish file. However, when I press ctrl + d, the terminal exits with only a single press. I am using fish 3.7.1.  Why this does not work? Thank you.

**Comment by CWEzio** [comment]
> On Wed, Nov 06, 2024 at 02:42:22AM -0800, Chen Wang wrote: ``` # require multiple c-d to exit the terminal bind \cd true bind \cd delete-char bind \cd\cd\cd delete-or-exit ``` I have added the above to my config.fish file. However, when I press ctrl + d, the terminal exits with only a single press. I am using fish 3.7.1. Why this does not work? Thank you.
> works for me. What's `bind | grep cd`?

Thanks, I just find out that the issue is because I use the vim mode. In vim mode, to correctly do the binding, I need to bind the key for both modes:
    bind --mode default \cd delete-char
    bind --mode insert \cd delete-char

**Comment by krzysztof-plachta** [comment]
> > On Wed, Nov 06, 2024 at 02:42:22AM -0800, Chen Wang wrote: `# require multiple c-d to exit the terminal bind \cd true bind \cd delete-char bind \cd\cd\cd delete-or-exit` I have added the above to my config.fish file. However, when I press ctrl + d, the terminal exits with only a single press. I am using fish 3.7.1. Why this does not work? Thank you.
> > works for me. What's `bind | grep cd`?
> 
> Thanks, I just find out that the issue is because I use the vim mode. In vim mode, to correctly do the binding, I need to bind the key for both modes: bind --mode default \cd delete-char bind --mode insert \cd delete-char

Thank you for this one!
```
bind --mode default \cd delete-char
bind --mode insert \cd delete-char
```
