### ISSUE TITLE
low level tests failing under Debian build infrastructure

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#5599]
I'd appreciate some more eyeballs on this!

Since 91a9c989, the low level syntax highlighting tests fail on OBS build for Debian 8 and 9 with "Error: Wrong color in test at index 5 in text (expected 0x104, actual 0x4)":

```
[  400s] [31mError: Wrong color in test at index 5 in text (expected 0x104, actual 0x4):
[  400s] echo test/fish_highlight_test/foo &
[  400s]      ^[0m
[  400s] [31mError: Wrong color in test at index 6 in text (expected 0x104, actual 0x4):
[  400s] echo test/fish_highlight_test/foo &
[  400s]       ^[0m
[  400s] [31mError: Wrong color in test at index 7 in text (expected 0x104, actual 0x4):
[  400s] echo test/fish_highlight_test/foo &
[  400s]        ^[0m
[  400s] [31mError: Wrong color in test at index 8 in text (expected 0x104, actual 0x4):
[  400s] echo test/fish_highlight_test/foo &
[  400s]         ^[0m
<<snip>>
[  415s] Encountered 80 errors in low-level tests
[  415s] CMakeFiles/test_low_level.dir/build.make:60: recipe for target 'CMakeFiles/test_low_level' failed
```

The full logfile for a more recent revision is [available](https://github.com/fish-shell/fish-shell/files/2805954/shells-fish-nightly-master-Debian_8.0-x86_64-fish_log.txt).

I don't really know where to start debugging this - I especially don't understand why that commit started tickling the problem!

**Comment by mqudsi** [comment]
I can run the low-level tests on Debian 9 just fine. It occurs to me that you might want to check on the value of `$TERM`?

**Comment by zanchey** [comment]
`TERM` is `screen-256color`, so I don't think that's it.

They run fine in Debian 9 from my normal session, but under `pbuilder` or `sbuild` fail - which usually means a missing dependency or assumption that something exists.

**Comment by faho** [comment]
>(expected 0x104, actual 0x4)

So, this means that the expected highlight is "highlight_spec_param | highlight_modifier_valid_path", but the actual highlight is just "highlight_spec_param".

I.e. these aren't highlighted as valid paths.

So, if https://github.com/fish-shell/fish-shell/commit/91a9c98974ed8bb775629167c83f9bd48d020ad4 is important, that would suggest that fish inherits a non-canonical $PWD. And then it would probably have to canonicalize it somewhere it currently doesn't to check if the path is valid.

What's `pwd` and `pwd -P` in this case?

**Comment by zanchey** [comment]
I added the `pwd` and `pwd -P` commands to the low level test target in the CMake build, and the output is:

```
make[4]: Entering directory '/build/fish-3.0.0-264-g4064ab81/obj-x86_64-linux-gnu'
pwd
/build/fish-3.0.0-264-g4064ab81/obj-x86_64-linux-gnu                                                                              pwd -P
/build/fish-3.0.0-264-g4064ab81/obj-x86_64-linux-gnu
```

**Comment by ridiculousfish** [comment]
This is pretty weird! I still think the most reasonable explanation is some sort of virtual PWD mixup. The syntax highlighting uses the $PWD variable, while `touch` uses the resolved working directory, so if `$PWD` were an invalid path it would completely explain this.

GNU `pwd` resolves symlinks unless -L is passed. @zanchey can you please try:

1. checking `pwd -L`
2. Adding the line `env_stack_t::principal().set_pwd_from_getcwd();` line at the top of `test_highlighting()`

If #1 shows a different PWD and #2 fixes the test failure, then we have our answer.

**Comment by ridiculousfish** [comment]
Oh FFS:

http://git.savannah.gnu.org/cgit/coreutils.git/tree/src/pwd.c#n320

GNU `pwd -L`only outputs the logical PWD if `stat` succeeds AND it matches the physical PWD. So if we were in a nonmatching virtual PWD, `pwd -L` wouldn't tell us.

If you want to keep digging you might try printing `getenv("PWD");`,  I'm 99% sure this will show the disconnect. Adding the `set_pwd_from_getcwd()` line in main(), probably after the `signal_reset_handlers()` call, seems like a fine fix to me.
