### ISSUE TITLE
Completion on pre-existing argument

### ISSUE THREAD

**Issue by glykos** [fish-shell/fish-shell#5609]
This enhancement request is for fish v.3.0.0.

An example to demonstrate the issue. Say that I just typed

```
# diff file test/file
```

and I want to repeat this command but in the form `diff file otherdir/test/file`. In bash, I can bring back the first command, move the cursor to the letter `t` of `test`, start typing part of the `otherdir`, hit TAB, and get the expected completion of `otherdir/test/file`. In fish (after hitting TAB) I'm getting something along the lines of

```
# diff file othtest/file
```

**Comment by zanchey** [comment]
I thought we had this as an issue somewhere already, but I couldn't find it.

**Comment by exploide** [comment]
I think this is  #6687

**Comment by krobelus** [comment]
> I think this is #6687

Yep, let's track that there

We can probably support this, I remember having expected this to work as you describe several times before I eventually got used to it.
