### ISSUE TITLE
Command substitution buffers closed too early

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#5616]
In master, with some commands the buffer can be closed too early.

E.g.

```fish
$ set -l tmp (curl wttr.in)
# ...
curl: (23) Failed writing body (1381 != 4320)
```

(and a $status of 23)

Running bisect now.

**Comment by faho** [comment]
Most likely this is also what causes fzf to not work: https://github.com/fish-shell/fish-shell/commit/6f682c84052a8bd52f14122a36e878037cbb868e#r32184217.

For some weird reason, however, bisection is unsuccessful - whenever I run from the build directory it _works_. I can only confirm that 09ca268d5 works, but 9a4153f5e and c7656e662 are broken.

Which means it's down to the io_buffer stuff.

@ridiculousfish?

**Comment by ridiculousfish** [comment]
Nice find. The problem is that the shutdown flag is left uninitialized; I wrongly thought that `std::atomic` would zero-initialize values. C++ strikes again.
