### ISSUE TITLE
"set --erase" does not function on OpenWRT

### ISSUE THREAD

**Issue by haodong** [fish-shell/fish-shell#5617]
fish version: [3.0.0](https://github.com/openwrt/packages/tree/master/utils/fish)
OS: [OpenWRT 18.06.02 x86-64](https://downloads.openwrt.org/releases/18.06.2/targets/x86/64/)

Usage:
```shell
root@OpenWrt ~# set a1 1 2 3
root@OpenWrt ~# set a2 $a1
root@OpenWrt ~# set -e $a2[1]
root@OpenWrt ~# echo $a2
1 2 3
root@OpenWrt ~# set --erase $a2[1]
root@OpenWrt ~# echo $a2
1 2 3
```

Expected (on macOS):
```shell
> set a1 1 2 3
> set a2 $a1
> set -e a2[1]
> echo $a2
2 3
```

**Comment by faho** [comment]
`set` takes a variable _name_.

If you do `set -e $a2[1]`, that expands to `set -e 1`, so it erases the variable called "1".

What you want is `set --erase a2[1]`.

**Comment by haodong** [comment]
Got it. This is very beautiful. :)
