### ISSUE TITLE
[regression?] `Fill io_buffer via background thread` commit breaks fzf "go to folder" keybindings

### ISSUE THREAD

**Issue by ronjouch** [fish-shell/fish-shell#5618]
Fzf is a *"A command-line fuzzy finder "*, and has [Fish bindings](https://github.com/junegunn/fzf#fish-shell). Commit "Fill io_buffer via background thread" / 6f682c84052a8bd52f14122a36e878037cbb868e breaks the keybinding. Scenario:

1. Install [fzf Fish bindings](https://github.com/junegunn/fzf#fish-shell).
2. Press the kebyoard combination to invoke fzf's "Go to directory" command, <kbd>Alt</kbd>+<kbd>C</kbd>, type something that yields results, press ENTER.

Results:

- Expected: fzf navigates to selected result
- Actual, with ec29a5b9130d2d509a08dd1af6f7009c1230a68f (the commit right before 6f682c84052a8bd52f14122a36e878037cbb868e): 👍 fzf navigates to selected result / `pwd` is modified.
- Actual, with 6f682c84052a8bd52f14122a36e878037cbb868e: 👎 fzf fails to navigate to selected result / `pwd` is unmodified.

Information:

- OS: reproduced under both Ubuntu Linux 18.10 and Arch Linux.
- uname: `Linux xps 4.20.6-042006-generic #201901310331 SMP Thu Jan 31 08:33:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- $TERM: `xterm-256color`
- Terminal emulator: gnome-terminal 3.30.1
- I haven't tried fish in a mktemp, as it looks like a clear regression. Can do if asked to.
 
Is this expected breakage and I should report to fzf, or is this a regression?

**Comment by ridiculousfish** [comment]
Thanks for filing! I am hopeful this has been fixed via 2e542d782286e6e9783b22a1827717f6d197e3ab; can you please try on that?

**Comment by faho** [comment]
I can reproduce the issue and confirm the fix.

**Comment by ronjouch** [comment]
Fix confirmed too! Thanks everyone for the fishes.
