### ISSUE TITLE
`status is-command-sub` does not work (though `status --is-command-sub` does)

### ISSUE THREAD

**Issue by codesections** [fish-shell/fish-shell#5624]
According to the documentation for `status` the command `status is-command-sub` should work, and the command `status --is-command-sub` is depricated. 

However, as reflected in the screenshot below, the first (new) command is not recognized, though the depricated command still works. 

![image](https://user-images.githubusercontent.com/35405463/52382889-f8185e00-2a44-11e9-8228-ab2fda05561f.png)

**Comment by faho** [comment]
Yeah, the docs are wrong - this is only available as "is-command-substitution" (with or without "--") or "-c".
