### ISSUE TITLE
Hyphen character is underlined in man page tab completion list

### ISSUE THREAD

**Issue by abeintopalo** [fish-shell/fish-shell#5626]
For some reason my man page tab completion looks weird and can't figure out why. The hyphen characters are underlined in the completion suggestion list at the beginning of the lines. (See the attached screenshot) Anyone knows how I can get rid of this decoration?

My setup:
- fish, version 3.0.0-304-gd3fa58d6, (also same in 2.5 so it is not a regression)
- Iterm2, Build 3.2.7 (it is not terminal specific, same happens with macOS terminal app)
- Same behaviour for me even when using `sh -c 'env HOME=$(mktemp -d) fish'`

<img width="911" alt="man_pages_tab_completion" src="https://user-images.githubusercontent.com/7497004/52414277-8a277180-2aec-11e9-8c5d-b7bca17f2b49.png">

**Comment by faho** [comment]
Because it's the completion prefix, the bit of the token that is already there.

Set $fish_pager_color_prefix to a value that doesn't include "--underline" to remove the underline.

**Comment by abeintopalo** [comment]
Yes, that was it. Thank you so much. 👍
