### ISSUE TITLE
fish occasionally hangs, mostly when pasting, but sometimes when typing

### ISSUE THREAD

**Issue by toph-allen** [fish-shell/fish-shell#5627]
I'm running fish 3.0.0. This issue is a regression from 2.7.1.

My OS and terminal:
- `Darwin toph.ecohealthalliance.org 18.5.0 Darwin Kernel Version 18.5.0: Thu Jan 31 01:17:54 PST 2019; root:xnu-4903.250.319~62/RELEASE_X86_64 x86_64`
- ` xterm-256color`
- iTerm2 Build 3.2.7beta4

The issues most often occurs when pasting in text. fish will often hang after pasting text. Most often, this happens to me when pasting a URL after `git clone`. Mostly it happens instantly, but sometimes it happen when typing a space immediately after pasting, or hitting Ctrl + A to move the cursor to the start of the line.

Sometimes it doesn't hang, even with third party integrations enabled. I'm not sure what the causal factor is here. Sometimes it hangs every time, and sometimes it'll work just fine.

And as I was writing this bug report, was attempting to remove a third-party customization, and fish froze as I was typing, without pasting anything, leaving me with `fisher rm p` at the prompt.

When I first encountered the issue, after installing 3.0.0, I wiped and re-installed my fish customizations. I'm running `fisher`, and have the following packages installed:

```
oh-my-fish/plugin-fasd
oh-my-fish/plugin-osx
oh-my-fish/plugin-virtualfish
oh-my-fish/theme-robbyrussell
```

When running fish without any customizations, the issue doesn't seem to occur, but because it occurs inconsistently anyway, I can't tell if it just didn't happen, or if it is dependent on the plugins. It certainly seems more common with plugins installed.

I tried uninstalling and reinstalling individual, and then all, plugins, and wasn't able to find a conclusive trigger. Briefly:
- I uninstalled `oh-my-fish/plugin-fasd`, and was able to trigger the issue.
- I ran `fisher ls | fisher rm` to remove all plugins, and wasn't able to trigger the issue.
- But after I reinstalled `fasd` only, I was able to trigger the issue.

Sorry this bug report is so vague. If there's anything I can provide to help, let me know.

**Comment by faho** [comment]
This looks like https://github.com/oh-my-fish/plugin-fasd/issues/15

https://github.com/fish-shell/fish-shell/commit/4a3ac6e, included in the upcoming 3.0.1.
