### ISSUE TITLE
Can't find variable in documentation

### ISSUE THREAD

**Issue by edouard-lopez** [fish-shell/fish-shell#5630]
I have met several occurrences of variables being used in code where I was [unable to find documentation](https://fishshell.com/docs/current/index.html) about them. Latest occurrence being `fish_hybrid_key_bindings`.

Where Can I find information about such a variable? Is there a place tracking this?

Cheers

**Comment by faho** [comment]
fish_hybrid_key_bindings isn't a variable, it's a function.

See `type fish_hybrid_key_bindings`.

And yes, we should be better about documenting our functions, especially those that don't start with `__`.

**Comment by faho** [comment]
Oh, I forgot:

If you have any other variables or functions where you can't find the documentation, it'd be great if you could list them here, so we know what to document!

**Comment by faho** [comment]
Okay, let's consolidate this in #6695, as that has a list.
