### ISSUE TITLE
only long options can be selected from completion pager

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#5634]
If a command has a completion that has both a short and long variant with the same description, it's not possible to select an item in the pager and have the short option go onto the command line. The entires are coalesced into the same row on the pager, and the long option is always placed on the command line.

Having stuff like `patch --strip 0 --directory src < file.patch` in history is annoying. Having commands that are really long makes autosuggestions harder to see in entirety, and when the long format is something the person usually does not use, you will not get history matches against previous times you've typed the command normally using the short options. It's unusual for anyone to actually use the long options for many system utilities, and this is also true for a lot of our builtins, think `command -s foo`.

If we changed the behavior so that the short option is picked instead out of the two when a pager item with both forms is selected, this would allow the user to pick what they want, because they could still type `--<TAB>` to get the long one.

I do not think UX is harmed, because the user doesn't benefit from the self-documenting feature of long options here: they already saw the description in the pager, this was selected interactively, they know exactly what the option does.

**Comment by mqudsi** [comment]
I actually prefer long options for things I'm not typing non-stop because it's easier to search history and understand what was going on at the time. But I exclusively do so by typing `--<TAB>`, so I would have no problem with that.

**Comment by floam** [comment]
Yeah, I prefer the long options for many things that aren't used daily, I don't mean to give them the short shrift overall. It's just problematic that one cannot get the completion system to complete short options.

**Comment by floam** [comment]
Yeehaw, this is fixed. As a bonus with the short options first, since they're all two characters wide, things line up in columns nicer:

![image](https://user-images.githubusercontent.com/291142/54472742-f56b0000-478a-11e9-8f76-e89d3f1b0aa8.png)



I'm also now sorting `__` stuff after A-Z stuff in completions, which in e.g. `set` completions means there's more meaningful stuff at the beginning of the pager, not our `__fish` junk.
