### ISSUE TITLE
fish 2.7.1 breaks 2.6.0 scripts with caret/circumflex stderr redirection

### ISSUE THREAD

**Issue by Avispa** [fish-shell/fish-shell#5644]
I have my (same) config scripts for fish distributed over multiple systems and just noticed that on all machines, where I already run (the literally **same** binary of) fish 2.7.1 my config broke because of the re-directions of _stderr_ via `^`. 

Simple example:
```
echo 4 ^/dev/null
```
Results in..
* `4 ^ /dev/null` for fish 2.7.1
but should result in..
* `4` as like as in fish 2.6.0.

I checked the change log and the only note I could find about is, that it will be deprecate with fish 3. However this still wouldn't mean, even for fish 3, that it breaks.

__Info:__
System Linux 4.13.0 *vs* Linux 4.12.14 
fish 2.7.1 (from source) *vs* fish 2.6.0 (apt)

**Comment by faho** [comment]
Doesn't happen for me with 2.7.1 or 3.0.1, with ^ enabled.

**Comment by mqudsi** [comment]
The obvious question is whether or not you have the feature flag enabled (regardless of whether you flipped that switch or not).

**Comment by faho** [comment]
@mqudsi: 2.7.1 didn't have the feature flag.

**Comment by mqudsi** [comment]
Oh, I'm sorry. Then I'm proposing that "fish 2.7.1 (from source)" might mean "I built fish and now `echo $version` says 2.7.1," which can still be the case when using the 3.0 sources from master if you didn't pull in the tags.

**Comment by faho** [comment]
@Avispa: Ping?

Like I said, I can't reproduce it on 2.7.1 or 3.0 with the instructions you have given, so we're missing something.

**Comment by faho** [comment]
No response, closing.
