### ISSUE TITLE
Missing project.pbxproj file - macOS build failure

### ISSUE THREAD

**Issue by dsMrP** [fish-shell/fish-shell#5645]
Updated master branch to commit 1c6efc637861d63cac9aeca92c6505e63ca475de

Then attempted to build fish...

```[david@fumes 12:41:25]:~/d/fish-shell (master=) xcodebuild install
xcodebuild: error: Unable to read project 'fish.xcodeproj'.
	Reason: Project /Users/david/dev/fish-shell/fish.xcodeproj cannot be opened because it is missing its project.pbxproj file.
[david@fumes 12:41:28]:~/d/fish-shell (master=)```

**Comment by dsMrP** [comment]
The command got truncated...

```
[david@fumes 12:41:25]:~/d/fish-shell (master=) xcodebuild install
xcodebuild: error: Unable to read project 'fish.xcodeproj'.
	Reason: Project /Users/david/dev/fish-shell/fish.xcodeproj cannot be opened because it is missing its project.pbxproj file.


[david@fumes 12:41:28]:~/d/fish-shell (master=)
```

**Comment by floam** [comment]
We no longer ship a hand-made Xcode project. Instead, you can use CMake to generate an Xcode project:

`cmake -GXcode`

It'll create a `fish.xcodproj` bundle in the same directory.

**Comment by floam** [comment]
We should perhaps document this.

**Comment by dsMrP** [comment]
Note there is an `fish.xcodeproj` that exist in the repository. Perhaps that should be removed also. Also, please document where `cmake` can be obtained from. Thanks

**Comment by zanchey** [comment]
> Note there is an `fish.xcodeproj` that exist in the repository.

It got removed in 9396f79e3ecb6c8, but I've noticed that git occasionally fails to remove deleted directories when you update a working copy; `git clean --interactive -d` will give you a list of non-repository files/directories in your current working directory, and then pushing 's' for "select by numbers" will give you an interactive way of deleting them.

I'll add something about CMake to the README, but you can get it either from https://cmake.org/ or via `brew install cmake`.

**Comment by dsMrP** [comment]
I tried `git clean -df` also, and it didn't remove it. Removing it manually did the trick.

Thanks for the documentation update.

**Comment by ridiculousfish** [comment]
Xcode itself will put files inside the xcodeproj directory (these files are .gitignored), that's why it doesn't get removed automatically for some users.

**Comment by zanchey** [comment]
I've updated the README with the merging of #5711.
