### ISSUE TITLE
completion not work properly when using sudo -e 

### ISSUE THREAD

**Issue by Austaras** [fish-shell/fish-shell#5646]
`fish --version`: fish, version 3.0.1

`uname -a`: Linux magi-achiral 4.19.20-1-lts #1 SMP Wed Feb 6 21:46:51 CET 2019 x86_64 GNU/Linux

 `echo $TERM` : xterm-256color

when using `sudo -e`, only path can be auto completed, while file cannot so auto completion is not quite useful

however completion for files in current path works fine

**Comment by faho** [comment]
Works for me. Do you maybe have old `sudo` completions in $fish_complete_path somewhere?

Run

```fish
for f in $fish_complete_path/sudo.fish
    test -r $f; and echo $f; and break
end
```

to see which fish is using.

**Comment by SamHH** [comment]
I don't know if it's related, but I've discovered that I can reliably hang Fish as follows:

`sudo -E<tab>`

This is on `3.0.1` on Arch Linux.

**Comment by faho** [comment]
@SamHH: I can't reproduce that, also with the official fish 3.0.1 package on arch.

I suggest checking if your customization is at fault.

Also I'm 90% sure that's unrelated.

**Comment by SamHH** [comment]
@faho Figured out the repro, create an alias in config: `sudo -s`

Let me know if I should make a new ticket, or if I'm being stupid. :stuck_out_tongue:

**Comment by faho** [comment]
>create an alias in config: `sudo -s`

 `alias sudo="sudo -s"`?

**Comment by Austaras** [comment]
I got 
`/usr/share/fish/completions/sudo.fish`
which is 
`#
# Completion for sudo
#

function __fish_sudo_print_remaining_args
    set -l tokens (commandline -opc) (commandline -ct)
    set -e tokens[1]
    # These are all the options mentioned in the man page for Todd Miller's "sudo.ws" sudo (in that order).
    # If any other implementation has different options, this should be harmless, since they shouldn't be used anyway.
    set -l opts A/askpass b/background C/close-from= E/preserve-env=?
    # Note that "-h" is both "--host" (which takes an option) and "--help" (which doesn't).
    # But `-h` as `--help` only counts when it's the only argument (`sudo -h`),
    # so any argument completion after that should take it as "--host".
    set -a opts e/edit g/group= H/set-home h/host= '1-help'
    set -a opts i/login K/remove-timestamp k/reset-timestamp l/list n/non-interactive
    set -a opts P/preserve-groups p/prompt= S/stdin s/shell U/other-user=
    set -a opts u/user= T/command-timeout= V/version v/validate
    argparse -s $opts -- $tokens 2>/dev/null
    # The remaining argv is the subcommand with all its options, which is what
    # we want.
    if test -n "$argv"
        and not string match -qr '^-' $argv[1]
        echo $argv
        return 0
    else
        return 1
    end
end

function __fish_sudo_no_subcommand
    not __fish_sudo_print_remaining_args >/dev/null
end

function __fish_complete_sudo_subcommand
    set -l args (__fish_sudo_print_remaining_args)
    complete -C"$args"
end

# All these options should be valid for GNU and OSX sudo
complete -c sudo -n "__fish_no_arguments" -s h -d "Display help and exit"
complete -c sudo -n "__fish_no_arguments" -s V -d "Display version information and exit"
complete -c sudo -n "__fish_sudo_no_subcommand" -s A -d "Ask for password via the askpass or \$SSH_ASKPASS program"
complete -c sudo -n "__fish_sudo_no_subcommand" -s C -d "Close all file descriptors greater or equal to the given number" -a "(seq 0 255)"
complete -c sudo -n "__fish_sudo_no_subcommand" -s E -d "Preserve environment"
complete -c sudo -n "__fish_sudo_no_subcommand" -s H -d "Set home"
complete -c sudo -n "__fish_sudo_no_subcommand" -s K -d "Remove the credential timestamp entirely"
complete -c sudo -n "__fish_sudo_no_subcommand" -s P -d "Preserve group vector"
complete -c sudo -n "__fish_sudo_no_subcommand" -s S -d "Read password from stdin"
complete -c sudo -n "__fish_sudo_no_subcommand" -s b -d "Run command in the background"
complete -c sudo -n "__fish_sudo_no_subcommand" -s e -r -d "Edit"
complete -c sudo -n "__fish_sudo_no_subcommand" -s g -a "(__fish_complete_groups)" -x -d "Run command as group"
complete -c sudo -n "__fish_sudo_no_subcommand" -s i -d "Run a login shell"
complete -c sudo -n "__fish_sudo_no_subcommand" -s k -d "Reset or ignore the credential timestamp"
complete -c sudo -n "__fish_sudo_no_subcommand" -s l -d "List the allowed and forbidden commands for the given user, or the full path to the given command if it is allowed"
complete -c sudo -n "__fish_sudo_no_subcommand" -s n -d "Do not prompt for a password - if one is needed, fail"
complete -c sudo -n "__fish_sudo_no_subcommand" -s p -d "Specify a custom password prompt"
complete -c sudo -n "__fish_sudo_no_subcommand" -s s -d "Run the given command in a shell"
complete -c sudo -n "__fish_sudo_no_subcommand" -s u -a "(__fish_complete_users)" -x -d "Run command as user"
complete -c sudo -n "__fish_sudo_no_subcommand" -s v -n "__fish_no_arguments" -d "Validate the credentials, extending timeout"

# Complete the command we are executed under sudo
complete -c sudo -x -a "(__fish_complete_sudo_subcommand)"
`

**Comment by faho** [comment]
@Austaras: That is the correct file.

What is sudo? `type sudo` should tell you if it's a function or something.

**Comment by Austaras** [comment]
@faho  `sudo is /usr/bin/sudo`

**Comment by faho** [comment]
The thing that should take precedence here is this line:

```fish
complete -c sudo -n "__fish_sudo_no_subcommand" -s e -r -d "Edit"
```

That means: For the command `sudo`, if the condition `__fish_sudo_no_subcommand` is true (i.e. that function returns 0), then it'll offer the short option "-e", with the description "Edit", and it requires an argument ("-r"). Because no "-f"/"--no-files" is given, file completion is not inhibited.

@Austaras: If you do `complete -C"sudo -e "`, does that print a bunch of files?

**Comment by Austaras** [comment]
@faho yes, it prints every file and directory in current path
I found that it only breaks when path contains '/', auto completion for files in current dir works fine

**Comment by faho** [comment]
>I found that it only breaks when path contains '/', auto completion for files in current dir works fine

Ah, okay, that explains it.

My previous reading _was_ incorrect, this _is_ inhibiting the file completion. What it's doing is command completion, only ours is kinda bad when you've not entered anything.

**Comment by floam** [comment]
Yeah, I think the bug here is "command completion is file completion before 1 character"

**Comment by faho** [comment]
>Yeah, I think the bug here is "command completion is file completion before 1 character"

Just to be clear: That _masks_ the bug.

The bug itself is that we don't get file completion here when we should.

What complicates matters is that specifying when exactly file completions should be done is quite brittle and confusing.

**Comment by jethrokuan** [comment]
I get the same issue with `sh -c`, where I believe it used to complete path:

```
➜ complete -C"sh -c "
Desktop/
Downloads/
...
```

**Comment by Austaras** [comment]
weirdly `sudoedit` works fine for me
