### ISSUE TITLE
Autocompletion for git add doesn't work if file was already added

### ISSUE THREAD

**Issue by danrot** [fish-shell/fish-shell#5648]
I have a git project, and I am using the auto completion a lot for `git add`, so that it shows all the files not being staged for a commit according to `git status`. This works quite well, however, if I have already added a file using `git add` and edit the same file again, then the autocompletion doesn't suggest the file.

This seems always to happen if a file is listed in the "Changes to be commited:" and in the "Changes not staged for commit:" section of `git status`.

**Comment by zanchey** [comment]
I see this on 3.0.0-326-g2f48851e.
