### ISSUE TITLE
PATH not taken into account and erroneously evaluated

### ISSUE THREAD

**Issue by glecetre** [fish-shell/fish-shell#5649]
**Fish version**: 2.7.1
**Operating system**: Linux hpi-latitude 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux (Linux Mint 19)
**Terminal**: screen

Hello, here is the issue I am facing with my PATH in fish.

My `PATH` variable is not taken into account. When using `eval $PATH` to check its content, the following error is displayed:

```
15:53:29 ~
> eval $PATH
- (line 1): The file “/home/jeahel/.config/yarn/global” is not executable by this user
begin; /home/jeahel/.config/yarn/global /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin 
       ^
from sourcing file -
        called on line 61 of file /usr/share/fish/functions/eval.fish

in function “eval”
        called on standard input
```

When checking the permissions on the incriminated folder:

```
15:53:33 ~
> ls -la /home/jeahel/.config/yarn/
total 12
drwxr-xr-x  3 jeahel jeahel 4096 Feb 12 13:48 ./
drwxr-xr-x 38 jeahel jeahel 4096 Feb 12 13:48 ../
drwxr-xr-x  3 jeahel jeahel 4096 Feb 12 13:48 global/
```

The folder is indeed mine.

Thanks :)

**Comment by zanchey** [comment]
`eval $PATH` tries to run your PATH as a command with arguments, which is probably not what you want - directories cannot be commands.

Try `echo $PATH` instead.

**Comment by glecetre** [comment]
My bad, I incorrectly set my path. Terribly sorry for the inconvenience.
