### ISSUE TITLE
math can't multiply

### ISSUE THREAD

**Issue by Konstruktionist** [fish-shell/fish-shell#5650]
fish v 3.0.1
Darwin Kernel Version 18.2.0

`math 1*2` or `math 1 * 2` produces:  
```
fish: No matches for wildcard '1*2'. See `help expand`.
math 1*2
     ^
```
Tried the same on the [rootnroll website](https://rootnroll.com/d/fish-shell/) and the same result there

---
On my Mac:

`math -s0 3 * 4` produces:  
```
math: Error: Unknown variable
'3 conf.d config.fish fish_variables functions README.md 4'
      ^
```

I don't know what to make of this error message.  
Apparently the `*` somehow got expanded to some sort of directory listing of my fish dir (_while I'm in there_). The `.gitignore` is the only file ommited.  
If I do this in `~` I get a listing of my home dir, with `math: Error: Missing operator`.  

If I do `math -s0 3*4` we're back to:

```
fish: No matches for wildcard '3*4'. See `help expand`.
math -s0 3*4
         ^
```

**Comment by faho** [comment]
`math` is an ordinary command.

That means that expansions will be applied to the commandline before it is run.

`*` is the glob/wildcard character. So fish will expand it to filenames, just like in `rm *`.

What you need to do is to quote or escape it:

```fish
math 5 \* 4
math '5 * 4'
math 5 "*" 4
```

all work.

(We've had ideas of allowing "x" as multiplication character, but that clashes with `0x` hexadecimal numbers)

**Comment by Konstruktionist** [comment]
Ah, of course now that you mention it this is obvious.
But then the documentation is not clear [math docs](https://fishshell.com/docs/current/commands.html#math).  
Nowhere is it explicitly stated that the `*` operator should be escaped or quoted in the math context. It is also absent in the examples section.  
Exceptions like this of the "normal" behaviour of a command seems to me a prime example for the Examples section.

**Comment by faho** [comment]
>Keep in mind that parameter expansion takes before expressions are evaluated. This can be very useful in order to perform calculations involving shell variables or the output of command substitutions, but it also means that parenthesis and the asterisk glob character have to be escaped or quoted.

We should probably actually add the character there instead of naming it, and a multiplying example would also be welcome, yes.

**Comment by Konstruktionist** [comment]
Or maybe all math expressions should be within single quotes?

**Comment by faho** [comment]
You can use single quotes, if you want. `math` doesn't care.
