### ISSUE TITLE
`ls` hangs for specific directory.

### ISSUE THREAD

**Issue by recolic** [fish-shell/fish-shell#5654]
- system info

Fish version: fish, version 3.0.0

uname: Linux RECOLICPC 4.20.6-arch1-1-ARCH #1 SMP PREEMPT Thu Jan 31 08:22:01 UTC 2019 x86_64 GNU/Linux

I tried fish with `sh -c 'env HOME=$(mktemp -d) fish'` and the problem still exists.

I CAN NOT reproduce this problem easily, however this is my 4th time to observe the problem, so I'm reporting it. It seems to reproduce randomly.

- the problem

My workdir is `/home/recolic` and I run `ls`. However it hangs and nothing happens. I tried `ls <otherDir>` and it works. I tried `bash -c ls` and it works.

I tried:
```
~ ❯❯❯ sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
recolic@RECOLICPC /h/recolic> ls
^C⏎                                                                                                                                                                                           
recolic@RECOLICPC /h/recolic> ls tmp/
 1.html   a.s               fish_ls.log                     proj1-subm.zip         snap-0202-161232.png   snap-0204-012134.png   snap-0210-023101.png   snap-0211-165856.png    w2.mp3
 2.html   c/                fuck-mcdvoice/                  snap-0130-021248.png   snap-0202-161427.png   snap-0204-200251.png   snap-0210-235635.png   snap-0212-152812.png    w.mp3
 3.html   cs164-software/  'Hackers Delight.pdf'            snap-0130-114024.png   snap-0202-161459.png   snap-0208-010212.png   snap-0211-013307.png   srg1.png                writing.pdf
 a.cc     cs267.pdf         iozone3_487/                    snap-0201-213813.png   snap-0202-162224.png   snap-0208-012908.png   snap-0211-015204.png   srg2.png                ww/
 a.ii     exp*              offbyone.png                    snap-0202-160452.png   snap-0202-163900.png   snap-0209-202758.png   snap-0211-020422.png   Thumbs.db
 a.o      exp.c             photo_2019-02-04_18-23-35.jpg   snap-0202-161009.png   snap-0203-173218.png   snap-0209-202823.png   snap-0211-020434.png   Thumbs.db:encryptable
 a.out*   fish_ls_gdb.log   _proj1-subm.zip/                snap-0202-161032.png   snap-0204-012109.png   snap-0210-022428.png   snap-0211-020552.png   tmp.cc
```

I tried to restart fish and the problem still exists. In previous case, restarting linux will work.

Here's the strace log and gdb log. (backtrace included!)

https://recolic.net/tmp/fish_ls.log (Please let me know if I should translate chinese to english)
https://recolic.net/tmp/fish_ls_gdb.log

**I can collect more information through gdb, if you can let me know what should I do as soon as possible.**

Here's the definition of ls.
```
~ ❯❯❯ type ls
ls is a function with definition
# Defined in /usr/share/fish/functions/ls.fish @ line 6
function ls --description 'List contents of directory'
    set -l param --color=auto
    if isatty 1
        set -a param --indicator-style=classify
    end
    command ls $param $argv
end
```

**Comment by faho** [comment]
Try just `command ls`. 

Also the output of `type -a isatty test` would be useful.

**Comment by faho** [comment]
Also:

>fish, version 3.0.0

You'll want to upgrade to 3.0.1, which is already in the arch repos.

**Comment by ridiculousfish** [comment]
Based on the fish backtrace and strace, it really looks like it's `ls` that's hanging.

Does `ls -GF tmp/` hang on other shells? Can you please collect a backtrace of `ls`?

**Comment by recolic** [comment]
> Based on the fish backtrace and strace, it really looks like it's `ls` that's hanging.
> 
> Does `ls -GF tmp/` hang on other shells? Can you please collect a backtrace of `ls`?
ls -GF doesn’t hang in bash...

**Comment by recolic** [comment]
> Try just `command ls`.
> 
> Also the output of `type -a isatty test` would be useful.

`command ls` works.

The output of `type -a isatty test` is here: recolic.net/tmp/o.log

**Comment by faho** [comment]
@recolic: Exactly how large is this directory? How many files/directories are in there?

And how long have you waited for `ls` to complete?

**Comment by floam** [comment]
What is /sbin/test?

**Comment by recolic** [comment]
@faho There're 26 entries (hidden not counted) in my home directory. Its size is 170GB.

I waited for about 20 seconds and nothing happened, then I interrupted it.

There's an interesting thing: I have an NFS drive mounted at `~/nfs` and the server is unreachable. After having the NFS server fixed, the problem disappears. I'll try to reproduce the situation tonight.

**Comment by floam** [comment]
Is it mounted at `~/nfs` or is `~/nfs` a symlink?

`ls -F`/`ls --indicator-style=classify` has to do a little more work than bare `ls` to stick those indicators in. For the symlink indicator, it dereferences the symlink, and it's like doing `ls` on the target, which I would expect e.g. `ls /mnt/nfs` to hang on.

**Comment by recolic** [comment]
> Is it mounted at `~/nfs` or is `~/nfs` a symlink to the mount?
> 
> `ls -F`/`ls --indicator-style=classify` has to do a little more work than bare `ls` to stick those indicators in. For the symlink indicator, it dereferences the symlink, and it's like doing `ls` on the target, which I would expect e.g. `ls /mnt/nfs` to hang on.

It's mounted at `~/nfs`. Please wait for a while. I'm trying to reproduce the problem...

**Comment by floam** [comment]
This isn't a fish bug, though, this is just fish applying `--indicator=classify` AKA `-F` to your `ls` commands. Something is making those terribly slow or making them hang entirely for you because of the extra sys calls that must go over NFS. The quick fix for you is going to be removing that option from the `ls` wrapper.

You might look into the `rdirplus` option nfs has, it sounds relevant:

```man
rdirplus
             Used with NFS v3/v4 to specify that directory read operations
             should retrieve additional information about each entry (e.g. use
             the NFSv3 ReaddirPlus RPC).  This option typically reduces RPC
             traffic for cases such as directory listings that use or display
             basic attributes (e.g.  ``ls -F'' and ``find . -type f'' ).  Note
             that the long directory listing format case (i.e.  ``ls -l'' )
             may not be helped much when the file system does not natively
             support extended attributes.  Older implementations tended to
             flood the vnode and name caches with prefetched entries which may
             not be referenced.  The current implementation avoids creating
             those entries until they are referenced.  Try this option and see
             whether performance improves or degrades. Probably most useful
             for client to server network interconnects with a large bandwidth
             times delay product.
```

**Comment by floam** [comment]
> ls -GF tmp/

Not exactly equivalent to what fish does for hm, because he's using GNU ls which does not use `-G` to turn on colors, but that `-F` ought to have done something.

**Comment by recolic** [comment]
> > Does `ls -GF tmp/` hang on other shells?
> 
> Not exactly equivalent to what fish does for him, because he's using GNU ls which does not use `-G` to turn on colors, but that `-F` ought to have done something.

These information is helpful. But currently I can not reproduce the problem. I think I can close the issue and reopen it if I collect more useful information.

**Comment by floam** [comment]
No problem, good luck!
