### ISSUE TITLE
share/functions/man.fish is harmful if MANPATH is respected, but empty

### ISSUE THREAD

**Issue by coypoop** [fish-shell/fish-shell#5657]
Using version 3.0.0, and on NetBSD,

NetBSD planets 8.99.34 NetBSD 8.99.34 (GENERIC) #5: Thu Feb  7 11:10:08 IST 2019  fly@planets:/current/obj/sys/arch/amd64/compile/GENERIC amd64

I noticed "man gcc" doesn't do anything any more, even though gcc.1 exists.
After an investigation, I found out this is because of the adjustment in https://github.com/fish-shell/fish-shell/blob/f0aa63cc11276be705ffee7efbb2be88990a5878/share/functions/man.fish#L21-L25

My MANPATH is empty, so after line 24, MANPATH is set to /usr/pkg/share/fish/man.
Setting MANPATH overrides the list of directories to search, so it doesn't find any of the regular man pages.

**Comment by faho** [comment]
>My MANPATH is empty

Do you have it explicitly set to empty? Might I ask why?

**Comment by floam** [comment]
Do we need an empty path component (a colon with nothing after it) here?

**Comment by coypoop** [comment]
oh, I don't have MANPATH set at all, sorry

**Comment by faho** [comment]
We do add an empty component iff $MANPATH is _unset_. If it is set, we trust it.

And that seems like a reasonable approach, which is why I'm asking if we're missing something.

**Comment by faho** [comment]
So the function should be setting MANPATH to `$fish_manpath ''`.

Which should cause `man` to search in fish's dir, and then the system default?

**Comment by floam** [comment]
That is my understanding of what empty MANPATH components are supposed to do.

**Comment by faho** [comment]
Apparently NetBSD's man doesn't do that.

**Comment by faho** [comment]
I _HATE_ how man is basically completely unstandardized.

NetBSD does not have `manpath` or `man --path`, it has `man -p`. man-db man only has the former two.

**Comment by floam** [comment]
Is `man -m` something that works everywhere? It augment the paths according to the NetBSD man (heh) man page.

**Comment by floam** [comment]
I'd say we just special-case this on `uname` or some identifying invocation of `man ...`,  figure out something that will work for NetBSD.

**Comment by faho** [comment]
>Is `man -m` something that works everywhere?

Nope. Because of course not.

Mine _has_ a "-m" option, but it apparently is short for "--systems=", where you can specify other operating systems that you might have man pages for. Like "NewOS".

**Comment by floam** [comment]
I was thinking to myself, "well, let's just figure out how to do it within POSIX, we're probably relying on some GNU behavior".

[The Open Group Base Specifications Issue 7, 2018 edition: `man`](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/man.html)

They hardly standardized it at all. One option.

**Comment by faho** [comment]
>let's just figure out how to do it within POSIX

HAHAHAHAHAHA. You've not looked into this yet? HAHAHAHA

-----

Okay, here's my fool-proof idea:

```fish
set -lx MANPATH $__fish_data_dir/fish/man
if not command man $argv
    set -el MANPATH
    command man $argv
end
```

I.e. just call `man` twice.

**Comment by floam** [comment]
👍

**Comment by floam** [comment]
(Be sure to send stderr to /dev/null, obviously.)

**Comment by floam** [comment]
Wait, no, that would throw away necessary error messages. I think we should try to somehow identify this MANPAGE syndrome rather than just try it twice on error.

**Comment by floam** [comment]
@faho, the reason I set this as a bug, is because the shell will cause `man` to fail to be able to show any manual page on NetBSD. In my opinion a enhancement would be just if we failed to show fish man pages.

Apparently this might be a thing in [OpenBSD](https://github.com/ocaml/opam/issues/1318) and [FreeBSD](https://github.com/ocaml/opam/issues/1786) as well.

**Comment by mqudsi** [comment]
@faho which version of NetBSD are you referring to?

```
$ uname -a
NetBSD  8.0 NetBSD 8.0 (GENERIC) #0: Tue Jul 17 14:59:51 UTC 2018  mkrepro@mkrepro.NetBSD.org:/usr/src/sys/arch/amd64/compile/GENERIC amd64
$ man man
...skipping...
     -m      Augment the list of standard directories which man searches for
             man pages.  The supplied path must be a colon (":") separated
             list of directories.  These directories will be searched before
             the standard directories or the directories specified using the
             -M option or the MANPATH environment variable.  The
             subdirectories to be searched, and their search order, is
             specified by the "_subdir" line in the man configuration file.
```

**Comment by mqudsi** [comment]
In addition to the `man -m` option, I just quickly checked FreeBSD, Linux, macOS, NetBSD, and OpenBSD and it seems that the only one where `man -p` is a valid flag (regardless of what it does) is NetBSD.

That means we can also check for `MANPATH`, `man -p`, and then `manpath`, in that order.

**Comment by floam** [comment]
> @faho which version of NetBSD are you referring to?

By "mine", I take it he was referring to the `man` on his Linux machine. The question I asked was if `-m` might work on the other `man`s, and no, it would not.

**Comment by faho** [comment]
>By "mine", I take it he was referring to the `man` on his Linux machine.

Indeed, yes. I can see how that might be confusing, sorry!

>it seems that the only one where `man -p` is a valid standalone flag (regardless of what it does) is NetBSD.

That's good to know. I was thinking maybe some other implementation takes it to mean "--print", and sends all matching man pages to the printer.

------

So, I'm 90% sure calling `man` twice would work - and if stderr was silenced just for the first, you'd still get the errors on the second.

But since it seems that it's really _just_ NetBSD (that is the proper capitalization, which I am glad to see we are all following - go us!), so doing

```fish
if set -q MANPATH
    # use it
else if set -l p (man -p 2>/dev/null)
    # use the normal path
else
    set path ''
end
```

would be more conservative, and seems like the way to go.

(This is really one of those cases where I lay the blame squarely on the POSIX standard)

**Comment by faho** [comment]
Okay, the "-p" option is basically broken. `man -p` prints stuff like `/usr/share/man/man1`. Which is a directory containing man pages like `man.1`.

So I run `env MANPATH=/usr/share/man/man1 man man`, and it doesn't find the man page. (man: no entry for man in the manual.)

What you have to do is set MANPATH to just "/usr/share/man/".

So it might work to strip the last component? It'd leave a few wrong components in there (the default has "man8", but also "man8/amd64" which would leave "/usr/share/man/man8"), but that seems harmless?

**Comment by floam** [comment]
Can't we use `-m` to augment the paths - just add the fish path?

**Comment by faho** [comment]
That requires us to check that "-m" does that thing.

There is more than one "-m".

**Comment by faho** [comment]
As in: If you do that for man-db man, it'll break.

It's possible to do it after a `uname` check, but you know how much I love those. (Next bug report: `man` breaks when I use NetBSD's man on Linux)

**Comment by floam** [comment]
Right, I mean only for NetBSD `man`. We can identify it by the fact that `man -p` won't return an error.

**Comment by floam** [comment]
(According to @mqudsi, he tried a lot of `man` implementations, and only on NetBSD is `-p` with no argument after it valid.)

**Comment by faho** [comment]
So that would require us to run `man -p` first, then discard its output, then run `man -m`?

Nah. Just removing the last path component seems preferable.

**Comment by floam** [comment]
> So that would require us to run `man -p` first, then discard its output, then run `man -m`?

Yeah, that was the idea. We still have to run `man -p` once, and `man` is ran afterwards either way.

It seemed like it would be less likely to do something surprising if funny configurations could change `-p` output. Like, apparently from reading over `man.c`, there weird magic going on for paths from the configuration that end in `/`, it changes how they are looked up and it stops assuming things will be in subdirs. I'm not sure I'm confident it will always be safe to take whatever `-p` gives us and use it with the last component chopped off. `man -m /our/paths` seemed kinda bulletproof OTOH.

**Comment by mqudsi** [comment]
> So that would require us to run `man -p` first, then discard its output, then run `man -m`?

No, we would do what we do with other commands like `ls`. In `man.fish`, we do `if command map -p >/dev/null 2>/dev/null` at startup, then define the function based on the output.

**Comment by mqudsi** [comment]
Update: `man -p` is also valid under OmniOS (and presumably other Solaris/IllumOS-based distros), but it functions the same way NetBSD's does, so we're good there too.

**Comment by faho** [comment]
>Update: `man -p` is also valid under OmniOS (and presumably other Solaris/IllumOS-based distros)

OpenIndiana has `man -p`, but the output is even worse than NetBSD's - "/usr/share/man,1,1m,1s,1t,1c:/usr/gnu/share/man:/usr/share/man", and it does **not** have `-m`. It has `-M`, but that requires specifying the entire thing.

However, it at least can handle setting MANPATH to the output of `man -p`, so since the `string replace` doesn't change anything it actually works. Switching to trying `man -p` and then doing `man -m` wouldn't work.

So it's best to leave this as-is.
