### ISSUE TITLE
`command $foo` broken highlighting

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5658]
fish 3.0 added support to use `command $foo` to execute the command whose name/path is stored in `$foo`, but the syntax highlighting code was not updated to take into account that a variable ~is now~ can be a valid execution target, and as a result `$foo` is always highlighted in red (since there is no executable literally named `$foo`).

e.g.

![image](https://user-images.githubusercontent.com/606923/52755617-273e4a80-2fc4-11e9-9f2d-af17bfbf9f2f.png)

**Comment by floam** [comment]
Same thing with `builtin $foo` after 038fea1a47c4288ca331188962cdfe14216ed8e3.

**Comment by mqudsi** [comment]
and plain, old `$foo`:

![image](https://user-images.githubusercontent.com/606923/56006067-109d3280-5c99-11e9-92fb-01b1a7fbaefb.png)

**Comment by ridiculousfish** [comment]
Yeah I've been chewing over how to fix this for a while

**Comment by zx8** [comment]
Related: https://github.com/fish-shell/fish-shell/issues/5571
