### ISSUE TITLE
NetBSD already ships with fish

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5659]
Guys, there's no need for us to bother with any fixes for NetBSD, fish is apparently maintained by the core NetBSD developers and ships out-of-the-box on a new installation 😄

![image](https://user-images.githubusercontent.com/606923/52756247-59e94280-2fc6-11e9-9a85-bf678b773281.png)

Seriously though, for some reason NetBSD ships with path to the "games" component (when installed) with a higher priority than `/usr/local/bin`, so the default fish prefix results in a `PATH` that doesn't contain the (right) fish.

Here's the stock `~/.profile`:

```
#       $NetBSD: dot.profile,v 1.9.26.1 2018/04/12 13:51:41 martin Exp $
#
# This is the default .profile file.
# Users are expected to edit it to meet their own needs.
#
# The commands in this file are executed when an sh user first
# logs in.
#
# See sh(1) for details.
#

# Set your editor. Default to explicitly setting vi, as otherwise some
# software will run ed and other software will fail. Can be set to
# emacs or nano or whatever other editor you may prefer, but of course
# those editors must be installed before you can use them.
export EDITOR=vi

# vi settings: set show-match auto-indent always-redraw shift-width=4
#export EXINIT="se sm ai redraw sw=4"

# VISUAL sets the "visual" editor, i.e., vi rather than ed, which if
# set will be run by preference to $EDITOR by some software. It is
# mostly historical and usually does not need to be set.
#export VISUAL=${EDITOR}

# Set the pager. This is used by, among other things, man(1) for
# showing man pages. The default is "more". Another reasonable choice
# (included with the system by default) is "less".
#export PAGER=more

# Set your default printer, if desired.
#export PRINTER=change-this-to-a-printer

# Set the search path for programs.
PATH=$HOME/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/X11R7/bin:/usr/pkg/bin
PATH=${PATH}:/usr/pkg/sbin:/usr/games:/usr/local/bin:/usr/local/sbin
export PATH

# Configure the shell to load .shrc at startup time.
# This will happen for every shell started, not just login shells.
export ENV=$HOME/.shrc
```

I'm not sure what we should do about this (if anything).

**Comment by floam** [comment]
NetBSD ought to abandon the silly old game.

Or, we need to be `fishfish` or something via a patch there.

**Comment by floam** [comment]
I think we should try to file an issue or bring it up on a NetBSD mailing list, and just see what happens.

**Comment by mqudsi** [comment]
I was just thinking ending `cmake --target install` with a quick check and a warning.

**Comment by zanchey** [comment]
Many (most?) users won't receive the software via a source install, but via a binary package. As an advocacy measure, it would be worth discussing with the NetBSD maintainers, but I don't think there's much we can do here.

**Comment by floam** [comment]
So, /usr/local/ is our default prefix, but the NetBSD folks will certainly install it into `${PREFIX}` for their package. Where is that? I seem to recall `/usr/pkg`. Does that come before the games in `$PATH` @mqudsi?

**Comment by mqudsi** [comment]
Ah I didn’t know that. This is my second time only with NetBSD. And, yup, it does. I posted the default PATH above.

**Comment by faho** [comment]
@coypoop: Do you know if it might be possible to rename the game or something?

I think this particular game is known as "go fish", so a binary name of "gofish" would also work. (Though it may make people think it's written in go)

**Comment by tungol** [comment]
as a datapoint, this game is available on FreeBSD from the bsdgames package, which installs it as "fish-game" specifically to avoid this conflict. It used to be in freebsd base as "fish", but that was a while ago now.

**Comment by faho** [comment]
Okay, no contact from the NetBSD people, I'm not going on any mailing list and there's nothing in fish-shell to do. Closing!
