### ISSUE TITLE
"read -S" Unknown option

### ISSUE THREAD

**Issue by BebeSparkelSparkel** [fish-shell/fish-shell#5660]
Looking at the [read doc](https://fishshell.com/docs/current/commands.html#read) `read -S` is supposed to be the same as `--shell`. However for me, `read --shell` works but `-s` does not. This does seem to be a regression.

> -S or --shell enables syntax highlighting, tab completions and command termination suitable for entering shellscript code in the interactive mode. NOTE: Prior to fish 3.0, the short opt for --shell was -s, but it has been changed for compatibility with bash's -s short opt for --silent.

```fish
> uname -a
Darwin MacBook-Air-3.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Jun 21 20:07:40 PDT 2018; root:xnu-3248.73.11~1/RELEASE_X86_64 x86_64
> fish -v
fish, version 3.0.1
> read --shell PRB_BUG
read>
> read -S PRB_BUG
read: Unknown option '-S'

       read - read line of input into variables

   Synopsis
       read [OPTIONS] [VARIABLE ...]

read: Type 'help read' for related documentation
```

**Comment by mqudsi** [comment]
I think that was me. I was bit by the duplication of values for the two separate getopts arrays.
