### ISSUE TITLE
On fish 3 user exit back to bash user - can no longer see what i type in bash

### ISSUE THREAD

**Issue by caffeinejolt** [fish-shell/fish-shell#5663]
I tried out fish 3.0.1 upgrading from 2.7.1 in a VM to see how smooth and upgrade it would be.  I did an RPM upgrade using this package: https://download.opensuse.org/repositories/shells:/fish:/release:/3/RHEL_7/x86_64/fish-3.0.1-1.1.x86_64.rpm

I noticed two things that seem to not work compared to behavior in 2.7.1 - 1) minor: curl auto-complete no longer works and 2) a bigger issue imo: when switching from a user with a bash shell to a user with a fish shell - and then exiting fish - i can no longer see what i type in bash.

I recorded the issue: https://drive.google.com/file/d/1tNfTse3Ki53rcy1_-ZRiZExlXxPGUBLp/view

Not running any special fish scripts on startup - stock as available from rpm
fish, version 3.0.1
Linux marge 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
xterm-256color

**Comment by faho** [comment]
>1) minor: curl auto-complete no longer works

#56654.

>when switching from a user with a bash shell to a user with a fish shell - and then exiting fish - i can no longer see what i type in bash.

So... this is most likely down to fish not resetting terminal modes on exit when run in this fashion (and bash not resetting them after it does - but that's intended).

I have no idea why the user would have any effect, so this might be down to what `su` does.

As a weird test, can you see if `sudo -i` exhibits the same issue?

Also @mqudsi is the expert here, so his input would be appreciated.

**Comment by caffeinejolt** [comment]
I get the same result with sudo -u $USER -i fish - so possibly not specific to su

**Comment by zgracem** [comment]
I also see this behaviour (macOS 10.14.3, fish 3.0.2). Typing `reset` at the bash prompt and hitting Enter, although nothing echoes to the screen, does successfully return the terminal to a useable state.

Happy to provide more info if necessary.

**Comment by zanchey** [comment]
Before typing `reset`, it would be useful to have the output of `stty -a`.

**Comment by zgracem** [comment]
This is the output of `stty -a` when bash is in its post-fish non-echoing state:

```
speed 38400 baud; rows 42; columns 144;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; start = ^Q; stop = ^S; susp = ^Z; dsusp = ^Y; rprnt = ^R;
werase = ^W; lnext = ^V; discard = ^O; status = ^T; min = 1; time = 0;
-parenb -parodd cs8 hupcl -cstopb cread -clocal -crtscts
-ignbrk brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr -icrnl -ixon -ixoff ixany imaxbel iutf8
opost -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig -icanon -iexten -echo echoe echok -echonl -noflsh -tostop -echoprt -echoctl echoke -flusho -extproc
```

**Comment by faho** [comment]
Ah, okay. The issue is "-icanon -iexten -echo". Fish turns these off because it handles them itself, but is supposed to turn them on again on exit.

One possibility is that we're confusing pgroup and pid (again):

```c++
    if (getpid() != tcgetpgrp(STDIN_FILENO)) return;
```

55b3c45f95ba09efa4b9eaad8ec49256a7435823 changed it so that fish doesn't always move into its own pgroup, so the assumption that pid == pgroup no longer holds.

@caffeinejolt, @zgracem: Please test 2418e1e50b636a3457b58a77feb0a2b14cbf82f9.

**Comment by faho** [comment]
(One of these days I'll understand when and how github exactly closes issues or marks them as duplicate. Today is not it)

**Comment by zgracem** [comment]
@faho `2418e1e` fixed it for me!
