### ISSUE TITLE
Completion doesn't work correctly on Arch Linux

### ISSUE THREAD

**Issue by EFanZh** [fish-shell/fish-shell#5664]
- OS: Arch Linux
- Fish Version: 3.0.1

I noticed some completion issues in fish on Arch Linux.

The following issues are tested after calling `fish_update_completions`:

1. No completion for curl: typing `curl -`, then press <kbd>Tab</kbd>, there is no completion.
2. Typing `man 1 `, then press <kbd>Tab</kbd>, only built-in commands are displayed, executables in `$PATH` are not shown.

You can reproduce the problems using a docker image:

```dockerfile
FROM archlinux/base:latest

RUN pacman -Sy awk grep fish man-db python --noconfirm

# Add a non-root user.

RUN useradd -m john

USER john

WORKDIR /home/john

RUN fish -c fish_update_completions

CMD fish
```

Downstream bug report: https://bugs.archlinux.org/task/61770.

**Comment by faho** [comment]
Fish provides a hand-written completion for curl, so the generated ones don't take effect.

I suggest copying ~/.local/share/fish/generated_completions/curl.fish to ~/.config/fish/completions/ for the time being.

**Comment by EFanZh** [comment]
Is the hand-written completion broken? I got no completion at all.

**Comment by faho** [comment]
The hand-written completion is exactly this:

```fish
# mqudsi: Given the size and scope of curl's arguments, I don't have the time
# to add proper completions, but want to enable path completion for data file
# parameters, which allow specifying the path to a payload to upload as @path,
# which fish won't complete otherwise.

complete -c curl -n 'string match -qr "^@" -- (commandline -ct)' -xa "(printf '%s\n' -- @(__fish_complete_suffix (commandline -ct | string replace -r '^@' '') ''))"

```

I'm about to commit a lightly cleaned-up version of the autogenerated ones to go with that, so you get both the options and that.

**Comment by EFanZh** [comment]
What about the other problem, where `man 1 <Tab>` is missing completion items?

**Comment by faho** [comment]
Completions aren't always perfect.

However, the `man` completions are hand-written and generally working. On my system it shows everything, as confirmed by comparing the length of `apropos -s 1 '.*'` to `complete -C'man 1 '`.

**Comment by faho** [comment]
Also that would be a different issue.

**Comment by EFanZh** [comment]
I know why `man 1 <Tab>` only shows built-in commands. I have to run `mandb` command before fish showing completion.
