### ISSUE TITLE
Fish shows error with ls

### ISSUE THREAD

**Issue by gbrls** [fish-shell/fish-shell#5665]
` gabriel@gabriel-pc ~> fish --version
fish, version 3.0.0 `

`gabriel@gabriel-pc ~> uname -a && echo $TERM
Linux gabriel-pc 4.19.20-1-MANJARO #1 SMP PREEMPT Wed Feb 6 21:33:34 UTC 2019 x86_64 GNU/Linux
xterm-256color`

Error: when I run the `/bin/ls` command, it shows `2019/02/16 20:51:59 unable to find pop config file` this message, which can be seen here https://asciinema.org/a/81FrshYbTdt57yF2XFSb1JbF9 ; and it only happens with FISH, BASH video: https://asciinema.org/a/cLhM1J0M5AH9vbUj5vMhx3G6E .

**Comment by floam** [comment]
It looks like you've got something from one of your Go paths interfering with things. "unable to find pop config file" is not a fish error. Googling suggest it's Go-related.

**Comment by floam** [comment]
I'd guess it is `isatty` in `ls.fish`, which tries to run `command test` to do something the `test` builtin can't do. This is not the first time we've seen ls break due to surprising Go binaries named test. Maybe we should run `command [` to decrease the odds of such a conflict happening.

**Comment by floam** [comment]
most recently: https://github.com/fish-shell/fish-shell/issues/5561

**Comment by floam** [comment]
I've committed something that will work around the issue that I believe you are having, but you probably will want to get rid of the bogus `test` binary installed anyhow. Please let us know if you're still having problems.

**Comment by andrew-schulman** [comment]
@faho asked whether this issue is fixed in Cygwin. In fish 3.0.2, I'm not able to reproduce it in Cygwin. Not sure if there's more information I can provide.
