### ISSUE TITLE
fish 3.0.2

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#5671]
Issue #5647 is blowing up and I think we should do a 3.0.2 release containing it.

#5647 is a regression introduced by the 3.0.1 fix #5525. #5525 allowed for PWD and getcwd to disagree; however apparently lots of tools set cwd, but not PWD, and just expect PWD to be fixed up. That's what the fix for #5647 does.

I've added an Integration_3.0.2 branch and milestone containing the fix for #5647.

@zanchey sound OK?

**Comment by zanchey** [comment]
Works for me. Is it ready to go?

**Comment by ridiculousfish** [comment]
#5647 seems to be working based on comments, looks GTG

**Comment by zanchey** [comment]
I can't make the website updates apply without a huge diff, so I might leave that to you @ridiculousfish - otherwise we are done here.

**Comment by ridiculousfish** [comment]
Amazing! Thank you!!

**Comment by twlz0ne** [comment]
@ridiculousfish The issue still exists when `split-window` with path in Tmux:

```sh
⋊> [~/Downloads] fish --version
fish, version 3.0.2
⋊> [~/Downloads] split-window -c "#{pane_current_path}"

--------

⋊> [/V/H/U/g/Downloads]
```
![tmux-split-window-with-panel-current-path](https://user-images.githubusercontent.com/2653486/57933722-9479b880-78f0-11e9-8d1f-241316e76bcd.png)

**Comment by faho** [comment]
@twlz0ne Different issue - #5699. The problem there is that tmux determines the PWD in a weird way, and that fails here.

**Comment by evantravers** [comment]
@faho should we tell tmux that? It looks like the conversation was closed when @caksoylar closed https://github.com/tmux/tmux/issues/1889.
