### ISSUE TITLE
type command doens't recognize abbr's definition

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#5672]
fish, version 3.0.1

I use `type` command to show the definition a command, this command could be the following types:

1. binary file in $PATH like `git`
2. builtin keyword like `if`
3. alias I defined in config.fish like `ll`
4. function I defined in config.fish like [`fu`](https://github.com/c02y/dotfiles/blob/87e6a874773c57dad142e9d79c57e95add02bb8b/fish/.config/fish/config.fish#L452)

and I defined a function called `fu` to show the definition of it no matter what the type is, I used to use `functions` to do that, but I found that `type` is better, so `fu` is basically wrapper of `type` command with extra features.

I defined a lot of aliases and functions in my [config.fish](https://github.com/c02y/dotfiles/blob/87e6a874773c57dad142e9d79c57e95add02bb8b/fish/.config/fish/config.fish), but I never used an abbr before, recently I noticed abbr command, so I decided to replace all my aliases with abbrs.

But the problem is, `type` command is unable to show the definition of a command if it is an abbr, I know I can use the command like `abbr -s CMD`, but I have to know CMD is an abbr, like I said, I use `fu` to show definitions of all commands, no matter what the type is.

Could you please make `type` command supports abbr's definition?

**Comment by faho** [comment]
The problem here is that `abbr` are, in a very real sense, not a thing.

If I do e.g.

```fish
if type -q thing
```

and it's true, then I expect to be able to call `thing`. With abbrs, that's not possible. They purely exist in the interactive reader.

**Comment by floam** [comment]
Also consider, `type` doesn't show you variables. It's really just commands and stuff.
