### ISSUE TITLE
type command doesn't not show the file and line number where an alias is defined.

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#5673]
fish, version: 3.0.1

When you `type CMD`, if the CMD is a function defined in some fish script files, it will show the file and line number like:

    $ type fu
    fu is a function with definition                                                                                     │
    # Defined in /home/user/.config/fish/config.fish @ line 455 
    # ...definition...

but if the CMD is an alias, it only shows:

    $ type l
    l is a function with definition                                                                                      │
    # Defined in - @ line 0 
    # ...definition...

I don't know which file and line number where the alias is defined.

I wrapped `type`  as a function my in config.fish to do extra actions such as open the position for editing or something like that, and I have to do extra work if I want this feature work once the CMD is an alias.

So I think if `type` command can also display the file and line number of an alias, that is better.

And like I mentioned in #5672 , once `type` supports displaying the definition of an abbr, the result should contains the file and line number of an abbr's definition too.

**Comment by faho** [comment]
So, `alias` is a function that mainly does

```fish
echo "function $youralias; $whatitdoes; end" | source
```

That means there's no such thing as an "alias" in fish itself, and figuring out the line for the function definition here is not simple, because it's defined _inside_ the alias function, on `source`s stdin. So we'd need to, in that case, step back not one, but two steps.

My recommendation is, and always has been, to stop using `alias` and define actual functions directly instead.

**Comment by c02y** [comment]
Thanks, I'll use `abbr` then and I can tweak my `fu` function to support displaying the definition of an abbr, and to get the line/position as well.


So, the question is, how can I tell if a command is abbr or not? if I know it is an abbr, I just use `abbr -s` to show it's definition. (Maybe I should post this question in #5672)

**Comment by faho** [comment]
>So, the question is, how can I tell if a command is abbr or not?

If it shows up in `abbr --list`. So if `abbr --list | string match -q thething` succeeds.

We should probably add a "--query" option to `abbr` (compare #5631).

**Comment by c02y** [comment]
`type` in #5631 is really powerful. As I said early, it is great if `type` supports abbr type.

Anyway, I can use `abbr --list` you suggested to check if a CMD is abbr or not.

`abbr --query` is nice, looking forward to it.

I'll close it for now. Thanks.
