### ISSUE TITLE
command substitution with 'timeout' breaks fish_greeting

### ISSUE THREAD

**Issue by ilevantis** [fish-shell/fish-shell#5683]
On fish 3.0.0 setting fish_greeting.fish to:
```
function fish_greeting
  echo (timeout 4 echo test)
end
```
causes fish to lock up on start.

If the line with the timeout command substitution is commented out then fish will start normally as expected. Once fish is started the line can be uncommented, and then `fish_greeting` can be called from within a fish session without any problem.

This was not an issue on my previous version of fish, however I'm not sure what version number that was.

OS: OpenSUSE Tumbleweed with kernel 4.20.6-1-default

**Comment by faho** [comment]
I can reproduce this in 3.0.2 - the timeout process exits but fish doesn't reap it - it waits on its own pgroup, instead of on timeout's.

Good news is it's fixed in master, I'm guessing via a95bc849c57d02e4bc2b3b0.
