### ISSUE TITLE
ubsan: signed integer overflow in uniform_int_distribution implementation

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#5684]
I'm not sure about this one in our `random` builtin. We run `random` with ranges like this in our tests:

`random -- -9223372036854775807 1023423432432423`

UBSan catches this overflow caused by `1023423432432423 - -9223372036854775807`, but it's not in our code:

```c++
~ $ random -- -9223372036854775807 1023423432432423
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/
usr/include/c++/v1/algorithm:3117:35: runtime error:
signed integer overflow: 1023423432432423 - -9223372036854775807 cannot be represented
in type 'long long'
    #0 0x10e27c40d in long long std::__1::uniform_int_distribution<long long>::operator()
<std::__1::linear_congruential_engine<unsigned int, 48271u, 0u, 2147483647u> > >
(std::__1::linear_congruential_engine<unsigned int, 48271u, 0u, 2147483647u>&, 
std::__1::uniform_int_distribution<long long>::param_type const&) algorithm:3117
```

The UB is supposedly happening in libc++. What I can't figure out is if we are doing something wrong by giving too large a range to `std::uniform_int_distribution`, or if this is a bug in llvm/libc++, or a false positive.

we instantiate it with these two arguments in builtin_random.cpp:
```c++
std::uniform_int_distribution<long long> dist(start, real_end);
```
Argument `a` (`start`) is subtracted from `b` (`real_end`) and it clearly overflows:
![image](https://user-images.githubusercontent.com/291142/53202900-8ad80180-35dc-11e9-9d95-2da595b9c281.png). 
![image](https://user-images.githubusercontent.com/291142/53203628-89a7d400-35de-11e9-8917-d59366d240f5.png)

I know that the behavior is undefined if  `a > b` but that's it and we ensure that doesn't happen. Are we also supposed to be able to assert that `real_end - start <= std::numeric_limits<long long>::max()` aka `start >= std::numeric_limits<long long>::min() + real_end`?

**Comment by ridiculousfish** [comment]
This is a libc++ bug which was [fixed upstream](https://github.com/llvm/llvm-project/commit/2dd5335204da085718e926d839f3200dc5227fc9#diff-b9ea4a6113478f4a3d6f9477015230c2).

We should add an `__attribute__((no_sanitize("integer")))` or equivalent to our function to work around this bug. If you have the time go for it!

**Comment by zanchey** [comment]
Can be added as a blacklist to `build_tools/ubsan.blacklist` - something like `integer:*/algorithm` might do the job, but would need testing.

**Comment by zanchey** [comment]
Long fixed elsewhere, I don't think there's anything worth doing here.
