### ISSUE TITLE
No color in terminal when printing python in fish_prompt.fish

### ISSUE THREAD

**Issue by edouard-lopez** [fish-shell/fish-shell#5686]
**related:** timofurrer/colorful#21

---

### Actual
When invoking the script with Python (above) I got the correct output, same when invoking `fish_prompt` manually (middle). However, when it's automatically invoked by `fish` there is no color (below).

![dev_231](https://user-images.githubusercontent.com/1212392/53250415-a31e4e00-36ba-11e9-8745-85bc10a5e35b.png)

### Python

```python
import colorful


def prompt(last_command_status=0):
    print(colorful.red('red'))
    symbol = '❯'
    return symbol


if __name__ == "__main__":
    print("%s " % (prompt()))
```

### Fish
Above code is invoked through a snippet in _~/.config/fish/functions/fish_prompt.fish_:

```fish
function fish_prompt
    python3 ~/projects/purish/pure/prompt.py $status
end
```

### Question

Am I missing something here?

**Comment by edouard-lopez** [comment]
Fixed on `colorful` side:

    colorful.setup(colormode=colorful.ANSI_256_COLORS)
    print(colorful.red('last_command_status'), last_command_status)

**Comment by faho** [comment]
Just out of curiosity: What do you want colorful for? It seems like it's basically `set_color`.

**Comment by edouard-lopez** [comment]
@faho I'm working on a cross-shell implementation of `pure` prompt in Python so I don't want to rely on the shell-specific feature.
