### ISSUE TITLE
Opening a shell from ranger doesn't work properly in fish

### ISSUE THREAD

**Issue by GinGin3203** [fish-shell/fish-shell#5687]
Hi!

When using ranger file manager invoked from fish, the "open terminal" function (`S` keybinding) returns to terminal with error `Job 1, 'ranger' has stopped` and throws you at the `$HOME`directory. As someone has noticed in ranger bugtracker (https://github.com/ranger/ranger/issues/1479), a similar thing happens in other programs, so it can be a bug on the side of fish. 

**fish 3.0.1**
**Arch, gnome-terminal/st**
**No 3rd party extensions**

**Comment by faho** [comment]
This works for me, on archlinux.

Can you try without your customization (even your own)?

What "utilities unrelated to ranger" fail in this way?

**Comment by GinGin3203** [comment]
Okay, I've managed to get rid of the `Job 1, 'ranger' has stopped` by not executing `fish` from my `.bashrc` but making it my default shell. 

But still, invoking `S` brings me to '$HOME' directory, even with all-default configuration.

I don't really know about any other appications which introduce the similar issue.

**Comment by faho** [comment]
>But still, invoking `S` brings me to '$HOME' directory, even with all-default configuration.

That's fixed in 3.0.2 - fish 3.0.1 inherits $PWD and trusts it, which turned out to be wrong.

(Arch has not yet updated to 3.0.2)

**Comment by GinGin3203** [comment]
Oh. Sorry for taking your time!
