### ISSUE TITLE
Wrong tab completion for valgrind

### ISSUE THREAD

**Issue by bluehood** [fish-shell/fish-shell#5688]
Tabbing on valgrind suggests options such as `--logfile` and `--logfile-fd` which are not present (at least in the valgrind versions I have access to). The correct spelling is `--log-file` and `--log-fd`.

Environment:
```
fish version 3.0.1
OS: Debian buster/sid, Arch linux
terminal: gnome-terminal
valgrind version: 3.14-0
```

Offending lines (as far as I can tell):
https://github.com/fish-shell/fish-shell/blob/38d86acbc3868c4275a04fe2f1df83b06efafe0f/share/completions/valgrind.fish#L38-L39

**Comment by faho** [comment]
Yup, thanks!
