### ISSUE TITLE
[Question] Builds for jailbroken iOS devices?

### ISSUE THREAD

**Issue by chexo3** [fish-shell/fish-shell#5694]
I’ve seen a script for building fish for iOS, but do you plan to put it on one of the larger repos (IE BigBoss)? Or host builds for iOS?

**Comment by ridiculousfish** [comment]
I think we would need someone to act as packager for this platform - the committers don't have resources to test on jailbroken iOS so we can't produce official builds for them. However I'd be happy to put up a link on fishshell.com if someone were to take it up.  Thanks for filing!

**Comment by chexo3** [comment]
I'll look into packaging. Maybe I can find something.
