### ISSUE TITLE
Remaining Sphinx bits

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#5696]
Here's stuff remaining to do for Sphinx:

- [x] Support the prebuilt documentation path (if we care, maybe we no longer care)
- [x] `install` targets to install docs
- [x] Linux package building to work
- [x] macOS package building to work
- [x] Fix remaining Sphinx build warnings
- [x] Fix certain '<a' style links in the Sphinx docs
- [ ] Make a nicer theme and clean up the TOC
- [x] Make a `fish_indent` based syntax highlighter
- [x] Figure out what (if anything) should replace `lexicon_filter`
- [x] Test that the `open` man page isn't installed on macOS

**Comment by faho** [comment]
A few things:

- `help $command` doesn't work as it links to commands.html#$command, but the commands are at cmds/$command.html.

- The synopsis for commands doesn't look great - I've tried putting them in literal blocks but I'm not sure about that.

- The highlighter seems to stumble over `{}`. 

- What do we do with `@key{$key}`?

- What's the general state of the documentation? Do we need to reapply any changes to doc_src?

- Do we want to keep the directory as sphinx_doc_src?

**Comment by zanchey** [comment]
I've done the following:

> * Support the prebuilt documentation path (if we care, maybe we no longer care)
> * Linux package building to work
> * Test that the `open` man page isn't installed on macOS

as part of #5711.

**Comment by zanchey** [comment]
The original lexicon filter is an amazing piece of work, which as I understand it built a filter that Doxygen applied to enable some helpful macros and also provide information for the syntax highlighter. Sphinx has builtin macro support, so I don't think we need that component, but I'm not sure I fully understand everything the lexicon filter did!

@MarkGriffiths was the original author and might be able provide any insight into other roles it had.

**Comment by MarkGriffiths** [comment]
The lexicon filter was totally geared towards Doxygen - It would scan the current state of fish's command lexicon and automatically apply the correct styling macros and syntax colouring to the examples in the source documentation files adding the appropriate style declarations for both html and manpage output.

Some places required a manual override, which is where `@key{$key}` was used as well as the `\fish{}…\endfish` blocks.

If Sphinx is able to do all the syntax colouring in the examples, `lexicon_filter` can go away.

**Comment by ridiculousfish** [comment]
I'm working on a Pygments highlighter that shells out to `fish_indent`, it's nearly done.

**Comment by faho** [comment]
Okay, I did some more work to replace some of the leftover markup.

In particular, I picked 

```
:kbd:`thing`
```

as the `@kbd{thing}` replacement (yes, github requires me to use a block because it doesn't allow escaping backticks).

I think it still requires a custom style to actually be rendered?

There are still a few `@cursor_key` remaining.

**Comment by faho** [comment]
Now with #3404 closed, it's probably important to note that `help $cmd` doesn't currently work because of the change to commands.html.

It would have to open cmds/$cmd.html if it exists.

**Comment by faho** [comment]
Okay, all key markup should be replaced, and I've switched `help` to go to the correct command page.

If we decide we don't want single-command-pages, we'll have to change it back.

**Comment by faho** [comment]
Okay, one of the build warnings is really tough to get rid of:

```
index.rst:281: WARNING: Inline literal start-string without end-string.
```

The offending line:

```rst
- ``\\ `` escapes the space character
```

I have absolutely no idea how to get `\ ` in a verbatim block in rst. I've tried doubling, tripling, quadrupling the backslashes, I've tried singling it, I've tried adding another space, removing backticks.... I can't find anything on google or in the docs.

And the other is an "Anonymous hyperlink mismatch: 1 references but 0 targets." in license.rst which doesn't even give a line number!

**Comment by faho** [comment]
Another thing:

Some of the tutorial especially uses styling to approximate how text appears on the terminal. E.g. there's 

```html
    <outp>Type <span class="cwd">help</span> for instructions on how to use fish</outp>
```

or 

```
``fish`` will underline valid file paths as you type them::

    >_ cat <u>~/somefi</u>___
```

`<outp>` is probably the biggest of these.

I think these require additions to the stylesheet, and would have to be used like 

```
:outp:`output`
```

instead.

**Comment by ridiculousfish** [comment]
My custom syntax highlighter knows about > for prompts, I'll try to get that posted soon.

**Comment by ridiculousfish** [comment]
ef88e959ac4ba056908ab02a7871a52ace0b6359 merges the new syntax highlighter

**Comment by faho** [comment]
@ridiculousfish: The style is a bit weird - I get underlined spaces, so it looks like `echo_hello_world`.

**Comment by faho** [comment]
Okay, I've fixed the underlines - it was an explicit text-decoration which might have made sense at some point or maybe in other browsers (I'm on firefox), but it looked awful in my case so I removed it.

One thing left is that we use `>_` as the prompt indicator, and that underline stays. @ridiculousfish should we replace that with just `>`?

Also there is at least one reference in a code-block - in the brace expansion section, theres a reference to cartesian-product.

And I still have no idea how to display "`\ `".

**Comment by ridiculousfish** [comment]
I think `>` is a little nicer but I don't care either way. If you want to support `>_` it's simple to extend `fish_indent_lexer.py` for that.

**Comment by faho** [comment]
> If you want to support >_ it's simple to extend fish_indent_lexer.py for that.

Done - I've made the `_` optional, both `>` and `>_` at the beginning of a line indicate a prompt now.

Also I've removed the `<outp>` tags that are now useless, and defaulted the highlighting language, so cmds/ is now also highlighted.

**Comment by faho** [comment]
Okay, one more problem:

The tutorial features a bunch of explicit styling, so we show code-blocks with formatting as it would be in the terminal. For some things (like marking `help` in the greeting) this is superfluous, but for things like showing suggestions or how a prompt would appear, this is actually useful. One way to support this is to add some language for it to the lexer, another would be to just incorporate screenshots.

**Comment by zanchey** [comment]
I fixed the synopsis formatting in 02d82dcf850c5be0f1857339cb920a89a6f1c84f

**Comment by faho** [comment]
There are no more build warnings and I've removed the coloring for now.

I'd be okay with leaving the theme for after 3.1.0.

**Comment by markstos** [comment]
@faho If the theme can be deferred than is "clean up the TOC" the only item that remains open on this issue for the 3.1.0 release?

**Comment by faho** [comment]
@markstos That's entirely non-critical as well.

**Comment by faho** [comment]
The necessary sphinx bits for 3.1.0 have been resolved, closing this.
