### ISSUE TITLE
 homebrew package is broken

### ISSUE THREAD

**Issue by ydesgagn** [fish-shell/fish-shell#5703]
The homebrew package is broken.

==> Satisfying dependencies
==> Downloading https://github.com/fish-shell/fish-shell/releases/download/3.0.2/fish-3.0.2.app.zip

curl: (22) The requested URL returned error: 404 Not Found
Error: Download failed on Cask 'fish-app' with message: Download failed: https://github.com/fish-shell/fish-shell/releases/download/3.0.2/fish-3.0.2.app.zip

**Comment by zanchey** [comment]
Can you show the exact command you used to install with? That's not the standard Homebrew formula.

**Comment by sanssecours** [comment]
I can reproduce the error using

```sh
brew cask install fish-app
```

. I opened a [pull request](https://github.com/Homebrew/homebrew-cask/pull/59490) in the [GitHub repo of Homebrew Cask](https://github.com/Homebrew/homebrew-cask) that should fix the problem.

**Comment by vitorgalvao** [comment]
@zanchey It’s the cask, that installs `fish.app`. Out of curiosity (Homebrew Cask maintainer here), what exactly does the app do? What’s its point?

**Comment by floam** [comment]
The app is portable - the entire installation is in the .app bundle and does not need to be installed into `/usr/local`.

**Comment by floam** [comment]
The idea is that it's easy to download and try. I don't imagine many homebrew users would actually want that compared to the regular fish formula.

**Comment by vitorgalvao** [comment]
> I don't imagine many homebrew users would actually want that compared to the regular fish formula.

Not many, no. There were only 18 install requests in the last 90 days, 10 of those in the last 30. I think we should remove that cask, it doesn’t make much sense. Thank you for the explanation.

**Comment by faho** [comment]
https://github.com/Homebrew/homebrew-cask/pull/59490 is merged, so this appears to be fixed.

Either way, there's nothing really to do from the fish-shell side.
