### ISSUE TITLE
How to automatically source config.fish if it gets modified?

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#5707]
fish, version: 3.0.1

I wrote a function/alias called `fsr` to `source ~/.config/fish/config.fish`, every time I modified `config.fish`, I have to manually execute `fsr` to source my config.fish. And I wrote another abbr called `vimf` to edit config.fish with vim and after editing, source it.

    abbr vimf 'vim $FISH_CONFIG_PATH; source $FISH_CONFIG_PATH; echo $FISH_CONFIG_PATH reloaded!'

But most of time, I'm writing/debugging/testing a function in config.fish, I open two terminals/panes side-by-side using tmux, so I can edit config.fish in one pane and test it in another, and I don't want to save it after editing (not exit the editor yet) in one pane and manually execute `fsr` in another.

So is there a way to source config.fish automatically if it is changed before executing my command I typed in fish prompt symbol?

**Comment by c02y** [comment]
That's all right, I figured it out:

~~~
function reload --on-event fish_preexec -d 'reload config.fish if gets modified!'
    set -q FISH_CONFIG_TIME
    if test $status -ne 0
        set -g FISH_CONFIG_TIME (date +%s -r $FISH_CONFIG_PATH)
    else
        set FISH_CONFIG_TIME_NEW (date +%s -r $FISH_CONFIG_PATH)
        if test "$FISH_CONFIG_TIME" != "$FISH_CONFIG_TIME_NEW"
            fsr
            set FISH_CONFIG_TIME (date +%s -r $FISH_CONFIG_PATH)
        end
    end
end
~~~

**Comment by bmalehorn** [comment]
@c02y Hey! I found this snippet to be really handy. hope you don't mind, I published it as a package so others can install it easily: https://github.com/bmalehorn/fish-auto-source

```
fisher add bmalehorn/fish-auto-source
```

**Comment by c02y** [comment]
@bmalehorn That's OK, feel free to use or publish it. I'm happy it is useful.

**Comment by c02y** [comment]
Since `fish_preexec` in fish-v.3.2.1 is not triggered for empty command like just `Enter` in the prompt, change `--on-event fish_preexec` to `--on-event fish_prompt` would be better.
