### ISSUE TITLE
Command expansion failing to split

### ISSUE THREAD

**Issue by henryiii** [fish-shell/fish-shell#5710]
I have an output from a command delineated by spaces that needs to be inserted exactly as typed. In my case, it is:

```fish
python-config --include
# Returns:
-I/usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/usr/local/Cellar/python@2/2.7.15_3/Frameworks/Python.framework/Versions/2.7/include/python2.7
```

If I put this into a command in fish, it is treated as if I added quotes around it, as so:

```fish
c++ compile_example.cpp (python-config --include) -undefined dynamic_lookup
# Output
compile_example.cpp:1:10: fatal error: 'Python.h' file not found
#include <Python.h>
```

If I run exactly the same code in bash (just adding a `$` infront of the `()`), or copy-paste the output string into the command manually in fish, it works. From looking at `echo (...)[N]`, I have come to the conclusion that fish is treating this as 1 array element, then passing it through as if it was inside quotes. I haven't found a way to get it to split on spaces, and I'm not sure this should be a workaround for this very common use case (or it should be mentioned in the docs). Most configure programs, like Python's own `python-config` demoed above, produce output like this that is supposed to be added to a compile line.  

I am running fish, version 3.0.1. Running on macOS through homebrew. My original problem was in accessing the include list from `python3 -m pybind11 --includes`.

The little example program I'm compiling is one line long:

```cpp
#include <Python.h>
```

**Comment by faho** [comment]
Unlike (ba)sh, Fish does not split on spaces and tabs, only newlines.

Use `string split " "` to split on spaces, like 

```fish
c++ compile_example.cpp (python-config --include | string split " ")
```

**Comment by faho** [comment]
This has an [FAQ entry](http://fishshell.com/docs/current/faq.html#faq-pkg-config), btw.

**Comment by henryiii** [comment]
I'd like to request a note added with a link to that FAQ entry in the docs where command substitution was listed. I tried some combinations of string split but didn't realize I needed to pipe it, and looking in the docs for command substitustions didn't help me find the FAQ page.

Thanks for the help!

**Comment by henryiii** [comment]
Edit: I must have been in an older version of the docs. I see it when getting there directly from fishshell's page. Nevermind!
