### ISSUE TITLE
Setting a local variable if a global variable doesn't exist is ugly

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5712]
The typical approach for conditionally setting a local variable is to locally declare the variable without a value and then use an undecorated `set` in the conditional to modify the value of the variable closest in scope (i.e. in this case, the local variable).

However, using this approach to set a variable *locally* if such a variable is not defined globally/universally is ugly:

```fish
set -l foo
if not set -qg foo && not set -qU foo
    set foo "foo"
else
    set -e foo
end
```

A small improvement would be to allow `set -qgU` (currently complains about multiple scopes not allowed) which would shorten the conditional. But the inversion of logic (set it first, then unset it if we find out it *does* exist) is still ugly...

**Comment by faho** [comment]
I'd say #565 covers this.
