### ISSUE TITLE
TERM_PROGRAM_VERSION can contain a second decimal point.

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#5725]
I updated to the 10.14.4 beta 4, and now on launch with Terminal.app:

```
	Integer 421 in '0421.1.1' followed by non-digit
```

Because `TERM_PROGRAM_VERSION` is `421.1.1` now. I haven't seen this kind of version number in the past. And of course the PWD notifications don't happen.

**Comment by lilyball** [comment]
10.14.4 is now out. We should consider doing a release that includes this fix.

**Comment by ridiculousfish** [comment]
I'm actually not able to repro this on 10.14.4 with fish 3.0.2, does anyone else see it?

It looks like the version check was introduced in ba9c38759056cc70e883360fc844b78571c700f6 which is not in 3.0.2. So I don't think we need this in a 3.0.3 release.

@floam can you confirm?

**Comment by zanchey** [comment]
I was wondering why we hadn't had any duplicates!

**Comment by floam** [comment]
You're not seeing `421.1.1`?
