### ISSUE TITLE
git-prompt: Change default symbols

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#5726]
For some reason, the default git-prompt mode features characters different from the "informative" mode.

In particular:

| character | default | informative |
| ------------- | --------- | --------------- |
| upstream_ahead | > | ↑
|     upstream_behind | < | ↓
|     dirtystate   | * |   ✚
|     invalidstate | # |   ✖
|     stagedstate | + |    ●
|     untrackedfiles | % | …

Personally, I feel like the "informative" symbols are much nicer, but I can't say that most of these immediately communicate what they represent (with the possible exception of the upstream ones).

I have no idea why these differ. The informative mode mostly enables _counting_ these things, so it'll display "5 things are dirty" instead of "some things are dirty", which makes it quite a bit slower and doesn't seem all that useful to me. But as it stands, it looks nicer so there's a bit of temptation to enable it.

**Comment by zanchey** [comment]
@lilyball might know if there's something behind this.

**Comment by faho** [comment]
I would assume that it's historical - the "informative" prompt was taken from https://github.com/olivierverdier/zsh-git-prompt, while the non-informative version was taken from [the official bash git prompt](https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh).

So they differ because they've been taken from two different places, and one is more conservative than the other.

I question that those are good defaults, though.

**Comment by lilyball** [comment]
It is indeed historical.

That said, I am strongly against changing it today. I don't want unicode characters in my prompt. We could absolutely add a config flag for "use the unicode characters in the non-informative mode" though, just don't change the defaults.
