### ISSUE TITLE
argparse: optional values don't seem to be stored

### ISSUE THREAD

**Issue by InspectorMustache** [fish-shell/fish-shell#5730]
```
$> function func
       argparse 'a=' -- $argv
       echo $_flag_a
   end
$> func -a blah
blah
```
This works as expected. However, when I make the value optional:
```
$> function func
       argparse 'a=?' -- $argv
       echo $_flag_a
   end
$> func -a blah
 # no output
```
Is this a bug or am I doing something wrong? I would expect the output for both functions to be the same as the docs for argparse say:
> If the flag is seen then _flag_n and _flag_name will be set with the value associated with the flag if one was provided else it will be set with no values.

I'm using Fish 3.0.1 on ArchLinux.

**Comment by faho** [comment]
Unfortunately not a bug, but down to weirdness in getopt (which this is built on).

For short-options, optional arguments have to be directly attached.

E.g. if you want to set the "-a" value to "blah", you have to use "-ablah".

Long-options can use `=` for optional arguments, so `--alpha=blah` would be acceptable.

**Comment by InspectorMustache** [comment]
I see. That is indeed strange. Are there any plans to work around getopt for this? Otherwise maybe this could be added to the Notes section of the argparse documentation.

**Comment by faho** [comment]
>Are there any plans to work around getopt for this?

No. For one, I was wrong, and arguments can't use "=" for short-options regardless if they are optional or mandatory - `-a=b` interprets the argument to be "=b".

So the only thing left for optional arguments is to use b as the argument in `-a b`, which is a breaking change and contrary to argparse's goal, which is to be compatible to getopt so it can be used in completions.

Plus optional arguments are really quite rare, and even rarer to short options (I only recall `complete -C`, and that has the same behavior).

**Comment by floam** [comment]
Wait, so how does one do optional arguments with argparse? `getopt_long` does optional arguments.

**Comment by faho** [comment]
>Wait, so how does one do optional short arguments with argparse?

In the optspec, you mean? `=?` is the magical bit, e.g. `a/alpha=?`.

Only that causes argparse to interpret the following:

```fish
foo -ab # argument is "b"
foo -a=b # argument is "=b"
foo -a b # no argument
foo --alphab # unknown option "alphab"
foo --alpha=b # argument is "b"
foo --alpha b # no argument
```

which is consistent with `getopt_long` (in fact the entire thing works by _calling_ `getopt_long`).

**Comment by floam** [comment]
Oh, that's okay then. I misunderstood the issue.

**Comment by floam** [comment]
That's just how it goes, @InspectorMustache. It's not an argparse thing. Our builtins using `getopt_long` directly with optional arguments, like `history -t`/`history --show-time=` behave the same way.

**Comment by InspectorMustache** [comment]
Thank you very much for the replies and the explanation. I don't think this is a crucial feature or something that actually needs to be changed. To me, it just doesn't seem very fish-y since this behavior is neither very intuitive (law of user focus) nor easily discoverable (law of discoverability). I could see how appropriate parsing would be very hard to implement, though.
