### ISSUE TITLE
How to set abbrs in conf file correctly?

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5734]
fish 3

Do we need to set this in the conf file to set abbreviations, or is it not needed now?

```
if not set -q my_abbrs

    ### GREP
    abbr --add --global egrep               'grep -E'
    abbr --add --global grep                'grep -n'
    abbr --add --global gri                 'grep --exclude-dir=.git -nri'
    abbr --add --global grex                'grep --exclude-dir=.git -nr --exclude="*.html" --exclude="*.js" --exclude="*.css"'


    set -U my_abbrs
end
```

I'm talking about `if not set -q my_abbrs`

Because I don't know, if I try to re-add an abbr or even re-add a variable, it just overwrites it, it doesn't duplicate it. So why do that? to avoid loading the abbr and gain a bit of time?

**Comment by faho** [comment]
>So why do that? to avoid loading the abbr and gain a bit of time?

That was the idea, yes. Though by now `abbr` is fast enough that you probably won't notice. Also if you set them as global the entire thing won't work because it's now only set in the first shell to read this file.

**Comment by BarbzYHOOL** [comment]
>Also if you set them as global the entire thing won't work because it's now only set in the first shell to read this file.

what?

**Comment by faho** [comment]
The "global" in `abbr --global` refers to global _scope_.

Imagine this:

```fish
if not set -q universal_variable
    set -g global_variable isset
    set -U universal_variable
end
```

That `not set -q` will only ever be true the first time this is executed, because after that the universal variable is set.

That means that the global_variable will only ever be set the first time it's executed.

**Comment by BarbzYHOOL** [comment]
```
if not set -q universal_variable
    set -U global_variable isset
    set -U universal_variable
end
```

Would work the same way, no?

**Comment by faho** [comment]
No.

The difference is that universal variables are persistently stored, on disk, and shared across instances.

If you run `set -g foo bar`, that sets $foo to bar, once, in that instance. If you open up another fish (e.g. in another tab), that won't have $foo set to bar.

If you, on the other hand, run `set -U foo bar`, that'll set $foo to bar on all fishes you have open at that moment, and all fishes you'll open after.

And with your `abbr` code, we check if a universal variable is set, which means it'll only run once in any fish (unless you `set --erase` that variable explicitly), but then set a bunch of global variables, which are only a thing in that one fish.
