### ISSUE TITLE
inconsistent cmake output on FreeBSD

### ISSUE THREAD

**Issue by tungol** [fish-shell/fish-shell#5735]
The cmake_install.cmake file generated by cmake seems to be different on FreeBSD depending on whether or not fish is installed at the time it's generated. If fish is not installed, it works as expected. If fish is installed, it generates a usable make file but it doesn't include a series of directory files to be installed:

${CMAKE_INSTALL_PREFIX}/etc/fish/conf.d
${CMAKE_INSTALL_PREFIX}/etc/fish/completions
${CMAKE_INSTALL_PREFIX}/etc/fish/functions
${CMAKE_INSTALL_PREFIX}/share/fish
${CMAKE_INSTALL_PREFIX}/share/fish/completions
${CMAKE_INSTALL_PREFIX}/share/fish/functions
${CMAKE_INSTALL_PREFIX}/share/fish/groff
${CMAKE_INSTALL_PREFIX}/share/fish/man/man1
${CMAKE_INSTALL_PREFIX}/share/fish/tools
${CMAKE_INSTALL_PREFIX}/share/fish/tools/web_config
${CMAKE_INSTALL_PREFIX}/share/fish/tools/web_config/js
${CMAKE_INSTALL_PREFIX}/share/fish/tools/web_config/partials
${CMAKE_INSTALL_PREFIX}/share/fish/tools/web_config/sample_prompts

It seems to be checking if these directories already exist, and not including them if they do. This creates a problem for common upgrade patterns on FreeBSD, because the FreeBSD port system expects fish build process to create the same set of files every time. Most of these end up getting created anyway, because they contain regular files, but the ones under ${CMAKE_INSTALL_PREFIX}/etc/fish are empty directories which get dropped entirely, and cause problems.

Can the cmake output be made to include these directories every time, even if they already exist at the moment when cmake is run?

This behavior started appearing with fish 3.0. I'm currently still on 3.0.0, but I can reproduce it with newer releases as well. I have not tried to reproduce without customizations, but this bug does not involve actually running fish, so I don't think it's relevant.

**Comment by faho** [comment]
The code that creates these:

```cmake
FUNCTION(FISH_CREATE_DIRS)
  FOREACH(dir ${ARGV})
      IF(NOT EXISTS ${CMAKE_INSTALL_PREFIX}/${dir})
        INSTALL(DIRECTORY DESTINATION ${dir})
      ENDIF()
  ENDFOREACH(dir)
ENDFUNCTION(FISH_CREATE_DIRS)

FUNCTION(FISH_TRY_CREATE_DIRS)
  FOREACH(dir ${ARGV})
    IF(NOT IS_ABSOLUTE ${dir})
      SET(abs_dir "\$ENV{DESTDIR}\${CMAKE_INSTALL_PREFIX}/${dir}")
    ELSE()
      SET(abs_dir "\$ENV{DESTDIR}${dir}")
    ENDIF()
    INSTALL(SCRIPT CODE "EXECUTE_PROCESS(COMMAND mkdir -p ${abs_dir} OUTPUT_QUIET ERROR_QUIET)
                         EXECUTE_PROCESS(COMMAND chmod 755 ${abs_dir} OUTPUT_QUIET ERROR_QUIET)
                        ")
  ENDFOREACH()
ENDFUNCTION(FISH_TRY_CREATE_DIRS)
```

That second function is used for the pkg-config directory, and if I understand correctly it works?

What if you remove the ` IF(NOT EXISTS ${CMAKE_INSTALL_PREFIX}/${dir})` from the former (in cmake/Install.cmake)?

**Comment by cglogic** [comment]
> The code that creates these:
> 
> ```cmake
> FUNCTION(FISH_CREATE_DIRS)
>   FOREACH(dir ${ARGV})
>       IF(NOT EXISTS ${CMAKE_INSTALL_PREFIX}/${dir})
>         INSTALL(DIRECTORY DESTINATION ${dir})
>       ENDIF()
>   ENDFOREACH(dir)
> ENDFUNCTION(FISH_CREATE_DIRS)
> 
> FUNCTION(FISH_TRY_CREATE_DIRS)
>   FOREACH(dir ${ARGV})
>     IF(NOT IS_ABSOLUTE ${dir})
>       SET(abs_dir "\$ENV{DESTDIR}\${CMAKE_INSTALL_PREFIX}/${dir}")
>     ELSE()
>       SET(abs_dir "\$ENV{DESTDIR}${dir}")
>     ENDIF()
>     INSTALL(SCRIPT CODE "EXECUTE_PROCESS(COMMAND mkdir -p ${abs_dir} OUTPUT_QUIET ERROR_QUIET)
>                          EXECUTE_PROCESS(COMMAND chmod 755 ${abs_dir} OUTPUT_QUIET ERROR_QUIET)
>                         ")
>   ENDFOREACH()
> ENDFUNCTION(FISH_TRY_CREATE_DIRS)
> ```
> 
> That second function is used for the pkg-config directory, and if I understand correctly it works?
> 
> What if you remove the ` IF(NOT EXISTS ${CMAKE_INSTALL_PREFIX}/${dir})` from the former (in cmake/Install.cmake)?

It helped, as for me. Have the same issue with fish on FreeBSD.

**Comment by zanchey** [comment]
That's from 71329a250, and I'm not clear that it is desired behaviour.

**Comment by tungol** [comment]
The comment on that implies that it avoided a problem with trying to create the pkgconfig directory. Would it make sense to have a separate function for creating directories that are always going to be managed by fish, versus directories that are system locations that fish uses?

**Comment by faho** [comment]
>Would it make sense to have a separate function for creating directories that are always going to be managed by fish, versus directories that are system locations that fish uses?

It would, and in fact that's why these two functions exist. :smile: 

TRY_CREATE_DIRS is supposed to only _try_ to create dirs. Why CREATE_DIRS tries _less hard_ to do that is unclear to me.

pkg-config should probably just be TRY_CREATE_DIRS.
