### ISSUE TITLE
\c~ should not be valid

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#5738]
`^~` isn't a valid control character, but fish tries to do it. It ends up producing the same output as `\c^`.  This should produce an error.

```
~ $ echo \c~|vis -b
^^
```

**Comment by faho** [comment]
Compare #3800, #3162.

**Comment by floam** [comment]
Pretty sure there is just a mistake here:

https://github.com/fish-shell/fish-shell/blob/master/src/common.cpp#L1378

It shouldn't be adding 32 to `L'a'`, because that's going beyond L`z` and trying characters that can't be modified in that way. I'll be committing a fix shortly but not before reading those two linked issues @faho to make sure I didn't miss something.

**Comment by floam** [comment]
(Looking at an ASCII table is handy here. The current code would also try to do `\c{`, `\c|`, `\c}` incorrectly as well however they cause a parse error or end the command statement so that it can't try.

**Comment by faho** [comment]
Is this actually incorrect? Looking at [an ascii table](http://www.asciitable.com/index/asciifull.gif), `~` is 7E, so subtracting 60 results in 1E, which is the "RS" record separator.

**Comment by floam** [comment]
Right, that's `\c^`. Our code is trying to do the user a favor and make a-z work as well as A-Z since they are the same literal keys. I don't think it should be happening to allow `control-~` produce a random control char. Unless you're telling me terminals actually pass that.

**Comment by faho** [comment]
I also get ctrl-~ when I press ctrl+~ in `cat`?

**Comment by floam** [comment]
Okay then. None of the terminals I tried did anything but make the terminal UI beep, and it's not exactly listed as a C0 control code sequence.

**Comment by faho** [comment]
konsole, gnome-terminal and xterm send it, so I don't think we can call this a bug.

I don't think it's worth it as an enhancement either because it's not like there are a lot of users trying this and failing to do anything.

**Comment by floam** [comment]
Yep.
