### ISSUE TITLE
relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#5745]
fish 3.0.2

I dunno which command I ran, I guess it was an abbreviation that lenghtened to "exa ..." (exa program)

And then I saw this:
```
fish: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_readline_unlocked
```

Can't reproduce, I just report to keep a track or if it happened to others before

**Comment by faho** [comment]
Not a fish error.

This can be caused by a library being relocated or incomplete, but considering that fish does not provide libnss (that's glibc), it's not our problem.

**Comment by BarbzYHOOL** [comment]
ok but it was written "fish:"

**Comment by faho** [comment]
Because fish wrote that error, but it comes from elsewhere.

**Comment by zanchey** [comment]
Brief Googling suggests this is caused by in-progress or incomplete package upgrades on Ubuntu, so unless it recurs I think you can leave this.

**Comment by BarbzYHOOL** [comment]
ok :)
