### ISSUE TITLE
hg vcs prompt does not indicate untracked files

### ISSUE THREAD

**Issue by psartini** [fish-shell/fish-shell#5749]
fish, version 3.0.2
Mercurial Version 4.9
Linux perdix 4.20.15-200.fc29.x86_64 #1 SMP Mon Mar 11 16:01:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

regression from 2.7.1

Problem: The mercurial prompt does not indicate a dirty state. In the example below I am just adding a new, unversioned file named "a"

With 3.0.2:
```
/test|(default|@)✓> touch a
/test|(default|@)✓> 
```

What is expected?
```
/test|(default|@)✓> touch a
/test|(default|@)⚡>
```

Solution:
The fix is to remove -q switch from the `hg status` call:

fish_hg_prompt.fish, line 41-43
```
    # For some reason, "-q" still prints the same output, but ~20% faster.
    # Disabling color and pager is always a good idea.
    set -l repo_status (hg status -q --color never --pager never | string sub -l 2 | sort -u)
```

changing to:
```
    set -l repo_status (hg status --color never --pager never | string sub -l 2 | sort -u)
```

fixes the issue.

**Comment by faho** [comment]
Fixed, thanks!
