### ISSUE TITLE
How to change the shell title patern

### ISSUE THREAD

**Issue by FFY00** [fish-shell/fish-shell#5754]
How can I change the shell title patern, for let's say remove the path? I would still want the process name to show up and update automatically, just not the path.

**Comment by faho** [comment]
The `fish_title` function prints the title. The default is

```fish
function fish_title
    echo (status current-command) (__fish_pwd)
end
```

so just edit it to

```fish
function fish_title
    echo (status current-command)
end
```

**Comment by FFY00** [comment]
Worked, thanks!
