### ISSUE TITLE
Question Mark folder icon on title bar with macOS's Terminal.app, fish 3.0

### ISSUE THREAD

**Issue by LdBeth** [fish-shell/fish-shell#5758]
After an update my title bar comes with a question marked folder icon.

<img width="546" alt="螢幕快照 2019-03-21 下午4 10 03" src="https://user-images.githubusercontent.com/22933696/54790560-ca9e0300-4bf3-11e9-8479-2b46434a19c3.png">

Related to this thread https://apple.stackexchange.com/questions/75751/why-does-the-folder-icon-in-my-terminal-have-a-question-mark-overlaid
> The question mark (and disabled popup menu items) indicates that Terminal thinks the working directory is on a remote computer, and therefore you cannot navigate to it in Finder using the popup menu. If you look at the last item in the popup menu (Command-Click on the “proxy” icon) you'll see the computer/host that Terminal thinks the working directory is on. You should find that it is not the computer’s current name.

My `hostname` command gives a `XXX.hsd1.ca.comcast.net`, rather than typical `XXX.local` due to my ISP's config, possibly causes the problem. Using system's default `bash` has no such a problem.

I'm using the prebuilt binary from https://pkgsrc.joyent.com, the version number is `3.0.0` according to package description, although `echo $version` gives `unknown`. macOS Mojave version `10.14.3`
Can be reproduced using the AppleScript bundle (version `3.0.2-1-g6f940d72d`) downloaded from homepage.
Not reproducible with locally compiled `2.7.1` version, which gives an expected normal icon.

<img width="587" alt="螢幕快照 2019-03-21 下午4 11 10" src="https://user-images.githubusercontent.com/22933696/54790611-f4572a00-4bf3-11e9-8846-ee83acc10f20.png">

I suppose the function informs the terminal about CWD has changed since 3.0 but no longer works with this corner case.

**Comment by floam** [comment]
That question mark appears when a bad path is reported to the terminal through the OSC 7 mechanism. What path do you see if you right click and hit Show Inspector? It'll be listed after Directory:

**Comment by floam** [comment]
(Just to confirm if it's really the hostname or maybe something else is going on.)

**Comment by floam** [comment]
Also, giving the Directory: from 2.7.1 to compare would be handy.

**Comment by faho** [comment]
Changes to the OSC 7 handling since 2.7.1:

- 920be02fe9c9a4fd15783fe390444a3bda2115fb, which uses $hostname instead of the `hostname` command.

- 5faa425df1afe9bb713634bbdbec1e6650eecaf5, which disables it in iTerm.

I imagine if $hostname is different from what `hostname` outputs that could trigger this.

**Comment by LdBeth** [comment]
> That question mark appears when a bad path is reported to the terminal through the OSC 7 mechanism. What path do you see if you right click and hit Show Inspector? It'll be listed after Directory:

it's `file://XXXXXXX-XXXXX.hsd1.ca.comcast.../Users/ldbeth`.


> Changes to the OSC 7 handling since 2.7.1:
> 
> * [920be02](https://github.com/fish-shell/fish-shell/commit/920be02fe9c9a4fd15783fe390444a3bda2115fb), which uses $hostname instead of the `hostname` command.
> * [5faa425](https://github.com/fish-shell/fish-shell/commit/5faa425df1afe9bb713634bbdbec1e6650eecaf5), which disables it in iTerm.
> 
> I imagine if $hostname is different from what `hostname` outputs that could trigger this.

You're right.
`echo $hostname` gives `XXXXXXX-XXXXX.hsd1.ca.comcast...` 
while `hostname` gives `XXXXXXX-XXXXX.hsd1.ca.comcast.net`. 

So it seems my hostname somehow get truncated because it's too long. 😭

**Comment by floam** [comment]
I have no idea why we're truncating at 32 characters. Up to 255 should be fine.

```
/// Maximum length of hostname. Longer hostnames are truncated.
#define HOSTNAME_LEN 32
```

**Comment by floam** [comment]
Okay, this should work correctly for you in git master.
