### ISSUE TITLE
Command substitutions busy-spinning, using 100% CPU

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#5761]
With some commands, like the kind `fzf` uses, fish spins, using up CPU while it's running.

I've managed to reduce it to

```fish
begin; echo "begin; cat;end <&3 3<&-" | source 3<&0; end | cat
```

I.e. the redirection-part of `eval` connecting two cats.

This is a regression from 3.0.2.

**Comment by faho** [comment]
`echo (cat | cat)` also exhibits the same problem.

**Comment by mqudsi** [comment]
This bisects to 6f682c84052a8bd52f14122a36e878037cbb868e

I imagine we need to make the `waitpid` call block in more situations to handle this.

**Comment by mqudsi** [comment]
For future reference (as I forgot to cc this issue in the commit message), the fix was continued in https://github.com/fish-shell/fish-shell/commit/04a96f6c6e1ec585dc24f30c6330468ae0190aa0.

**Comment by zx8** [comment]
@faho @mqudsi I'm running into this, specifically with `fzf`, using https://github.com/fish-shell/fish-shell/commit/6c1d29e14d7aeb5d0e6b659b06ad066a87aba113 / macOS 10.14.5 / iTerm2 3.3.0beta89. I'm happy to open a new issue if you'd like, but it seems very similar to what's described in this issue.

The reproduction steps are:
- Hit keybind to launch `fzf`
- While the `fzf` interactive picker is still displayed, hit `Command+Q` to quit iTerm. At this point, I'd expect `fish` to be killed, as well as any child processes.
- However, neither `fish` nor `fzf` die, and `fzf` and goes from consuming 0% CPU to 100% after a few seconds and causes my fans to go crazy. The only solution is to open Activity Monitor and kill the `fish` (or `fzf`) process manually.

Launching a new session and executing `pstree`, I see the following:

```
-+= 00001 root /sbin/launchd
 \-+= 28211 root /usr/bin/login -fqpl zx8 /Applications/iTerm.app/Contents/MacOS/iTerm2 --launch_shell
   \-+- 28212 zx8 -fish
     |--= 28463 zx8 (gawk)
     |--- 28466 zx8 (gsed)
     \--- 28467 zx8 fzf --history /Users/zx8/.local/share/fzf/history --select-1 --no-sort --query  --preview echo {}                          | sed 's|~/|/Users/zx8/|'                          | xargs -I% exa --color=always -T -L2 --group-directories-first '%'
```

I can reproduce it reliably with my own config, but when I use `env sh -c 'env HOME=$(mktemp -d) fish'` and copy/paste the function & bindings I'm using, I can't reproduce it.

**Comment by faho** [comment]
>I'm happy to open a new issue if you'd like, but it seems very similar to what's described in this issue.

Can you reproduce it with `echo (cat | cat)`? If not, please open a new issue, and include the function & bindings you are using.

Also by "I can reproduce it reliably", do you mean it happens "always" or just "often"?

Also ensure you're using the latest fzf release, and seeing *where* it's hanging via something like dtrace/dtruss is always helpful.

**Comment by zx8** [comment]
@faho Can't repro with `echo (cat | cat)`. Will open a new issue.

By "I can reproduce it reliably", I mean "I can reproduce 100% of the time, with my specific setup". I can't reproduce it with `env sh -c 'env HOME=$(mktemp -d) fish'` and then manually  `source`ing the function/bindings in question, though.

I'm using `fzf` v0.18.0, which is the currently latest release.

The odd part is that `fish` isn't exiting either, even after I've fully quit iTerm2.
