### ISSUE TITLE
[regression] "input_cleanup" merge causes prompt to fail to update on Ctrl+L, and disappears on Ctrl+L twice

### ISSUE THREAD

**Issue by ronjouch** [fish-shell/fish-shell#5766]
The `input_cleanup` merge ( a2a9709fd93a2a23fa5f350e3dfc04a491bb0f25 ... b270ca88049bf1fac77a53a70d3fb07cfd42e67d , by @ridiculousfish ) caused prompt regressions:

1. On pressing <kbd>Ctrl</kbd>+<kbd>L</kbd>, the prompt fails to update. For example, an in-prompt git status will fail to update to reflect changes for a git repo at $PWD.
2. On pressing <kbd>Ctrl</kbd>+<kbd>L</kbd> two times, the prompt disappears. See GIF below.

Problem is still present in HEAD as of now, eeec6cc2fc7e0636d8ea9f50f1fa62a65db1472a.

Thanks for fish.

## GIF demonstrating 2.

![fish-regression-prompt](https://user-images.githubusercontent.com/522085/54982357-0f71c300-4f81-11e9-8718-383cc992bc04.gif)

## Notes

- Problem reproduced with zero config/customization
- Terminal: problem reproduced in both GNOME Terminal 3.32.0 using VTE 0.56.0, and kitty 0.13.1
- uname -a: `Linux t 5.0.4-arch1-1-ARCH #1 SMP PREEMPT Sat Mar 23 21:00:33 UTC 2019 x86_64 GNU/Linux`

**Comment by rien333** [comment]
Just to add, this happens with some other default shortcuts as well (I know for sure it happens with `alt+l` for listing the cwd)

**Comment by ridiculousfish** [comment]
Great bug report, easy to repro! Bisects to 14663089c87f5acdd44acb90a0e21c3643887e79

**Comment by ridiculousfish** [comment]
@ronjouch I think I got this fixed in 0aa0dceeb323b9248eda6401ab202c7457804801 which is in master can you please try? Thanks!!

**Comment by rien333** [comment]
@ridiculousfish fixed it all the prompt disappearing issues for me. Thank you so much!

**Comment by ronjouch** [comment]
> Great bug report, easy to repro! Bisects to 1466308

@ridiculousfish welcome! Being myself maintaining a few projects, there's little I loathe more than _The One-Line, Misphrased, Entitled And Unprecise Bugreport Of Death Expecting Maintainer To Read Users Mind, Who By The Way Outperforms Themselves By Passively Complaining You, Volunteer Maintainer Giving Away Your Software, Do Not Answer Fast Enough To Their Enlightened Requests_, whose accumulation over the years progressively encouraged me to try to do better, when I myself report bugs. I take pride in a good precise and concise bugreport; thanks for the pat on the back, glad it's acknowledged.

> I think I got this fixed in [0aa0dce](https://github.com/fish-shell/fish-shell/commit/0aa0dceeb323b9248eda6401ab202c7457804801) which is in master, can you please confirm? Thanks!!

@ridiculousfish yay, fix confirmed for both issues 🙂. Thanks for fish! Closing.
