### ISSUE TITLE
Tab + multi-byte Unicode causes strange artifacts

### ISSUE THREAD

**Issue by buggymcbugfix** [fish-shell/fish-shell#5769]
![fish](https://user-images.githubusercontent.com/17603372/54926374-1b6d6e80-4f08-11e9-8f13-1061a27b83a3.gif)
Sorry, this GIF is a bit slow, but it illustrates what I see when pressing <kbd>tab</kbd> and then deleting the entire line. When recording with Asciinema this is not visible in the output, see [here](https://asciinema.org/a/QIaJyYyxmDtOCi1orrv5CeYRl). Is this likely to be a Terminal.app issue?

```
~ ✔︎ fish --version
fish, version 3.0.0
~ ✔︎ uname -a
<redacted> 17.7.0 Darwin Kernel Version 17.7.0: Fri Nov  2 20:43:16 PDT 2018; root:xnu-4570.71.17~1/RELEASE_X86_64 x86_64
~ ✔︎ echo $TERM
xterm-256color
```
I have the following in my `~/.config/fish/config.fish`:
```
function fish_prompt
  set -l exit_status $status
  dirs | tr -s '\n' ' '
  if test $exit_status -eq 0
    set_color green
    echo -n '✔︎ '
    set_color normal
  else
    set_color red
    echo -n '✘ '
    set_color normal
  end
end
```

**Comment by buggymcbugfix** [comment]
Update: this also happens in the built-in VSCode terminal.

**Comment by faho** [comment]
That ✔︎ is a "heavy check mark" emoji. Is it displayed 1 or 2 characters wide?

If it is displayed as wide as 2 normal characters, you need to `set -g fish_emoji_width 2`, otherwise `set -g fish_emoji_width 1`. Alternatively, adjust your terminal (though note that "2" is the value from Unicode 9 on, so changing to 1 is really sticking to the past).

**Comment by faho** [comment]
Also:

>fish, version 3.0.0

You _really_ want 3.0.2.

**Comment by buggymcbugfix** [comment]
Neither of those two settings change the behaviour described. I see that there is a U+FE0E (VARIATION SELECTOR-15) character after the check mark. Could that have anything to do with the issue?

Am updating fish, thanks.

**Comment by buggymcbugfix** [comment]
Ok, it seems that the variant selector causes the issue:

```
function fish_prompt
  set -l exit_status $status
  dirs | tr -s '\n' ' '
  if test $exit_status -eq 0
    set_color green
    printf '\U2714 '
    set_color normal
  else
    set_color red
    echo -n '✘ '
    set_color normal
  end
end
```

So it seems like there is some inconsistent handling of character widths that gets triggered when <kbd>tab</kbd>-completing.

**Comment by faho** [comment]
>I see that there is a U+FE0E (VARIATION SELECTOR-15) character after the check mark. Could that have anything to do with the issue?

Oh, wait, 15? Sorry, I misread it as FE0F, i.e. 16, which was fixed in 3.0.0.

Yeah, that's fixed by 6aa2f299011747b20af9bde4dc129cb572244bfc, which isn't in a release yet.

**Comment by faho** [comment]
For now, the obvious workaround is to remove the variation selector. Whether you pick a different char or not.

**Comment by buggymcbugfix** [comment]
Thanks. What about the underlining artifact that you can see in the GIF after I delete the line? (Not super important.)

**Comment by faho** [comment]
Same thing.

**Comment by buggymcbugfix** [comment]
It remains even after the `printf '\U2714 '` fix.
