### ISSUE TITLE
fish 3.0.3?

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#5772]
As requested by @lilyball in #5725, it might be prudent for us to create another bugfix release.

We have an issue that causes an error to spew in every terminal.app in the newest macOS release, which is pretty annoying.

But there are also some other issues worth fixing and some small enhancements worth releasing without waiting for a 3.1.0 (that would require fixing some regressions).

Some proposed issues/PRs to include, in no particular order:

- #5759 - makes help work on WSL in more cases (non-critical)
- #5769 (6aa2f299011747b20af9bde4dc129cb5) - makes variation selector 15 work better
- #5648 - plus some other git completion bugs
- #5639 - `builtin $var` does not work
- #5594 - a workaround for exported $fish_user_paths
- #5660 - `read -S` does not currently exist
- #5662 - an edgecase related to /etc/paths
- #5665 - a workaround for a surprisingly common problem with isatty
- #5722 - should mostly make $fish_emoji_width unnecessary
- #5689 - error spew on archlinux
- #5675 - broken sudo completions
- #5663 - we don't always restore term modes correctly
- #5664 - the curl completions are basically broken (currently worse than the auto-generated version!)
- 9796a331bca5082dd6cd7de67392eb0a9d62cc22
- 552af31ab045b63aa7c3cbbad700528b304f75a2

**Comment by faho** [comment]
- #5456 (#5767) - /etc/paths reordering in child fishes - this one made a big splash initially and the fix is quite simple, so it might be worth adding

**Comment by faho** [comment]
I'd love to have confirmation that #5665 works on cygwin. @andrew-schulman: Does cygwin provide a `[` _command_?

**Comment by floam** [comment]
I'd like to do another bug fix release. A lot of people are going to hit #5725.

**Comment by andrew-schulman** [comment]
Cygwin does provide a `[` command (/usr/bin/[). I'm currently working through some packaging issues with fish 3 in Cygwin, but I should be able to test this soon, and also #2980.

**Comment by mqudsi** [comment]
@faho if you're including #5759 then we should definitely include 9796a331bca5082dd6cd7de67392eb0a9d62cc22 and 552af31ab045b63aa7c3cbbad700528b304f75a2

**Comment by zanchey** [comment]
OK by me, though I'm nervous about #5722 and would rather hold that for 3.1.

I'll set a preliminary date of April 11 (Australian time). I'll start cherry-picking soon.

**Comment by faho** [comment]
>OK by me, though I'm nervous about #5722 and would rather hold that for 3.1.

@zanchey:

What was merged for #5722 is quite a bit simpler than the original proposal: https://github.com/fish-shell/fish-shell/commit/c633c06e11adace516cd8202916106f590cf1b05.

This only takes effect if $fish_emoji_width wasn't set, it doesn't ever use a guess of 0 or -1 (or even more non-sensical), it doesn't change anything for the ever-important Terminal.app or iTerm. It's purely a heuristic-switch, so we hopefully get 90% of people with the correct width instead of 60%. Worst-case we get 40% instead.

Since it doesn't switch the guess to the older result, it's also not worse for the new-client-sshing-to-old-server case.

But if you remain unconvinced, it's alright to hold off on.

**Comment by faho** [comment]
Made a milestone: https://github.com/fish-shell/fish-shell/milestone/23

**Comment by rien333** [comment]
Not sure if this an appropriate thing to ask, but any change of including https://github.com/fish-shell/fish-shell/issues/5766? It concerns a small---but imo annoying---regression, that probably needed only small changes to the code base.

**Comment by faho** [comment]
@rien333: #5766 is a regression between 3.0.X and master, the cause of which won't be included in 3.0.3. So there's no need to include the fix for it either.

**Comment by ridiculousfish** [comment]
It looks like the bug in #5725  is not actually in 3.0.2 so I don't think it needs to go into a 3.0.3.

**Comment by mqudsi** [comment]
We should hold off to see what the deal is with https://github.com/fish-shell/fish-shell/issues/5817

**Comment by zanchey** [comment]
I didn't get round to this last week, but without the pressure of something everyone will hit I think it's reasonable to go a bit slower.

I'm still happy to do a bugfix release as 3.1 is likely to be held up somewhat by Sphinx.

**Comment by ronjouch** [comment]
> > OK by me, though I'm nervous about #5722 and would rather hold that for 3.1.
> 
> @zanchey:
> 
> What was merged for #5722 is quite a bit simpler than the original proposal: [c633c06](https://github.com/fish-shell/fish-shell/commit/c633c06e11adace516cd8202916106f590cf1b05).
> 
> This only takes effect if $fish_emoji_width wasn't set, it doesn't ever use a guess of 0 or -1 (or even more non-sensical), it doesn't change anything for the ever-important Terminal.app or iTerm. It's purely a heuristic-switch, so we hopefully get 90% of people with the correct width instead of 60%. Worst-case we get 40% instead.
> 
> Since it doesn't switch the guess to the older result (EDIT: What I mean is it doesn't guess Unicode 8- where it previously guessed 9+), it's also not worse for the new-client-sshing-to-old-server case.
> 
> But if you remain unconvinced, it's alright to hold off on.

@zanchey @faho confirming here that c633c06e11adace516cd8202916106f590cf1b05 fixed long-standing emoji problems for me, under two Linuxes (Arch + Kitty terminal emulator, Ubuntu + Kitty terminal emulator). YMMV and it's only two additional data points, but I wanted to mention it in case it helps evaluate readiness of this piece of code.

**Comment by caffeinejolt** [comment]
Is the plan to no longer do a 3.0.3?

**Comment by zanchey** [comment]
I still want to do it, but it requires about six continuous hours of clear air which I haven't had for a while.

**Comment by dkambersky** [comment]
Sorry for the bump, but any movement on this?

**Comment by zanchey** [comment]
Let's work on getting 3.1.0 out the door instead.
