### ISSUE TITLE
Auto complete for commands expecting = sign

### ISSUE THREAD

**Issue by torkelrogstad** [fish-shell/fish-shell#5773]
How do I provide tab completion for option arguments that expect a `=` sign right after the argument? An example:
```fish 
foo --bar=baz # valid
foo --bar baz # invalid
```

`complete -c foo -l bar -a baz ` leads to `foo --bar baz` and `complete -c foo -l bar= -a baz` leads to `foo --bar= baz`.

I have not written the software I'm trying to make completions for, so I cannot change how it parses arguments. 

### System information: 

```fish
$ fish --version
fish, version 2.7.1

$ echo $version
2.7.1
```

I'm on Ubuntu 18.10.

**Comment by faho** [comment]
You'll have to skip the option part of `complete`, and instead handle it as arguments.

E.g.

```fish
complete -c foo -xa '--bar={a,b,c}'
```

If you know the options before or can generate them in one go. If you don't, use `commandline -ct` to get the current token and act accordingly.

**Comment by torkelrogstad** [comment]
How would this be handled in the cases where the option argument is completely dynamic? I.e. a file name

**Comment by faho** [comment]
Use a command substitution to execute a script to get the files.

E.g.

```fish
complete -c foo -xa '--bar=(set -l files /tmp/banana/*; printf %s\n $files)'
```

will offer "--bar=/tmp/banana/file1" and "--bar=/tmp/banana/file2".

If that's too much for you, you can also start offering them only if the current token starts with `--bar=` by adding

```fish
-n 'string match -q -- "--bar=*" (commandline -ct)'
```

as the condition.

**Comment by torkelrogstad** [comment]
Thank you! That last suggested line prevented the auto-complete output from being completely unreadable. 

It'd be nice to have `=` as a separator after an option as a configurable thing.
