### ISSUE TITLE
How to get the count of options when using argparse

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#5774]
fish v3.0.2

I'm writing a function with argparse, it may contain options or not.

When a specific option is given, I do action A, when no option is given I do action B,

So when there are multiple options available(only parse one at a time), I want to check is there any option first, and if no option, do action B, then check other available options.

but 
~~~
if test (count $argv) -eq 0
~~~
is not working since option like '-h' of argparse is not in $argv, and there is no useful info from the `argparse --help`.

Currently I check available options and use the final else for the situation when there is no option given.

But is there a simple way for the situation that no option is given?
How can I check the number or existence of the options of argparse?

**Comment by faho** [comment]
There are a few ways to go about this.

The main issue with your `test` was that you're testing _after_ you've done the `argparse`.

What that does is save all the non-options in $argv, so if you execute `foo --bar baz`, $argv before would be "--bar baz" and after would be "baz" (unless "--bar" takes arguments, in which case $argv would be empty).

The main question here is if you're really interested in if there's no _option_ given or no _argument_ in general?

If you want to know if there's zero _arguments_, simply do the `if test (count $argv) -eq 0` before the `argparse`.

If you're really interested in the number of _options_, there's no direct variable or anything you can check, but there's a few ways.

One is to check `count $_flag_x $_flag_y $_flag_z` for all the flags  you've defined and see if that's 0.

The other is to save `count $argv` from before the argparse, and compare it to the count afterwards.

E.g.

```fish
set -l allargs (count $argv)
argparse x/xylophone y-yankeedoodle z -- $argv
or return # exit on error
if test (count $argv) -eq $allargs
    # If argparse didn't remove anything from $argv,
    # there can't have been an option
else
    # There was at least one option
end
```

**Comment by c02y** [comment]
Sorry about the confusion here, I'm talking about options (like -h) instead arguments.

I guess, builtin variable like `_flag_cnt`  should be defined in fish to show how many options are there.

**Comment by faho** [comment]
>I'm talking about options (like -h) instead arguments.

Then do one of my latter two suggestions.

>I guess, builtin variable like _flag_cnt should be defined in fish to show how many options are there.

To be honest, the number of options given is seldom useful, so this doesn't seem necessary, especially since it can be achieved via other means.

**Comment by c02y** [comment]
OK, thanks.
