### ISSUE TITLE
Documentation for some commands contains raw HTML

### ISSUE THREAD

**Issue by 0ion9** [fish-shell/fish-shell#5775]
For some commands (eg `bg`, `fg`),  `man $cmd` or `$cmd --help` includes raw `<a href=...>`

eg.

```
fg  brings  the specified <a href="index.html#syntax-job-control">job</a> to the foreground, resuming it if it is stopped. While a foreground job is
       executed, fish is suspended. If no job is specified, the last job to be used is put in the foreground. If PID is specified, the job with the  speci‐
       fied group ID is put in the foreground.
```

IMO the correct rendering would give the link location directly, eg.
```
fg  brings  the specified job (see index.html#syntax-job-control) to the foreground, resuming it if it is stopped. While a foreground job is
       executed, fish is suspended. If no job is specified, the last job to be used is put in the foreground. If PID is specified, the job with the  speci‐
       fied group ID is put in the foreground.
```

Just in case it matters:

fish version 3.0.2-770-g1937e409f

**Comment by faho** [comment]
Yup. It's fallout from the switch to sphinx/ReST, which has its own reference syntax.

Grepping for "a href" shows 65 matches in the docs.

**Comment by faho** [comment]
Fixed via https://github.com/fish-shell/fish-shell/commit/203927245d7422038814913bbfb676b6d2ebdf6f (I mistyped the issue number, sorry!)

**Comment by faho** [comment]
Not quite fixed - there are still quite a few remaining.
