### ISSUE TITLE
We should be able to specify an array that argparse will alter/set

### ISSUE THREAD

**Issue by bool3max** [fish-shell/fish-shell#5778]
We're able to provide a list of arguments that `argparse` will go through (the ones after the `--` argument), but not the variable which `argparse` alters/sets (it always sets `argv`). 

This could be useful in some cases.

The manual page for `argparse` also states that 

> If $argv is not empty then it is checked for flags -h, --help, -n and --name. If they are found **they are removed from the arguments** and local variables (more on this [below](https://fishshell.com/docs/current/argparse-local-variables)) are set so the script can determine which options were seen.

leading the end user to believe that `argparse` simply filters through `argv` (removing matched flags in the process), while it in fact sets it every single time (even if it is empty). 

Also, the hyperlink for the **below** keyword in the above blockquote leads to a 404.

**Comment by faho** [comment]
Sorry, I don't see the use. If you want to use a different name afterwards, simply copy it to that name.
