### ISSUE TITLE
builtin --help output is missing section headers

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#5782]
Our Sphinx-generated man pages are not getting the right treatment anymore in `--help` output. We now have normal section headers and when they are stripped away it makes the output confusing. Compare `man cd` to `cd --help`: headers like EXAMPLES are just missing.  `__fish_print_help` needs adjusting.

**Comment by faho** [comment]
```fish
    # The original implementation trimmed off the top 5 lines and bottom 3 lines
    # from the nroff output. Perhaps that's reliable, but the magic numbers make
    # me extremely nervous. Instead, let's just strip out any lines that start
    # in the first column. "normal" manpages put all section headers in the first
    # column, but fish manpages only leave NAME like that, which we want to trim
    # away anyway.
```

> "normal" manpages put all section headers in the first column, but fish manpages only leave NAME like that

Yup, that's just wrong now.

I'm not entirely sure what the intention here is? Remove the header line with "command(1)" and such, and then the trailing "COPYRIGHT" one, and also the "NAME" line because that's obvious?

Anyway, I tried limiting this to printing after the "NAME" line and to stop at the "COPYRIGHT" line, only my `man` prints the NAME line as `N\bNA\bAM\bME\bE`. Is that normal? Or does my man include an april fool's joke or something?

**Comment by zanchey** [comment]
> Anyway, I tried limiting this to printing after the "NAME" line and to stop at the "COPYRIGHT" line, only my `man` prints the NAME line as `N\bNA\bAM\bME\bE`. Is that normal? Or does my man include an april fool's joke or something?

That's how `groff` prints bold characters, in case you are piping your output to an actual typewriter.

**Comment by faho** [comment]
> in case you are piping your output to an actual typewriter.

Wait... draw the character, move back, draw the character again? Yeah, that would look bold, wouldn't it?

**Comment by floam** [comment]
Yep.

**Comment by floam** [comment]
The old method of removing the first few lines and last lines that the quoted comment derided probably will get us decent output. I'd also like to unindent things, though.

**Comment by floam** [comment]
When interactive, I think there is a good question as to why we don't just launch actual `man`.
