### ISSUE TITLE
fish_escape_delay_ms not respected

### ISSUE THREAD

**Issue by tsoernes** [fish-shell/fish-shell#5783]
Setting fish_escape_delay_ms to 10 produces no change; exiting vi-mode is still very slow.

fish 2.7.1, kernel 5.0.3-200.fc29.x86_64, tried both tilix and urxvt

**Comment by faho** [comment]
It works for me - `set -g fish_escape_delay_ms 300` makes things work quite slowly.

What exactly did you execute? Did you set it in config.fish or elsewhere?

**Comment by tsoernes** [comment]
I've tried both setting manually and in the config. It is not correct of me
to say that the setting is not respected. Setting to 5 seconds makes it
take 5 seconds. But setting to 10 msec and it's still like 400-600 msec. I
do not have this problem in Bash vi mode with `set keyseq-timeout 0.01` in
`.inputc`. Then the delay is unnoticable. With fish and 10 msec it's nearly
half a second. I've also noticed now that entering insert mode from command
mode also takes a very long time, same as escape; at least 300 msec. So
this issue is perhaps not related to the aformentioned setting.

man. 1. apr. 2019 kl. 13:58 skrev Fabian Homborg <notifications@github.com>:

**Comment by faho** [comment]
I just reinstalled 2.7.1 (I recommend upgrading to 3.0.2 btw!), and I can't say I can reproduce this.

What does `bind \e; bind -M insert \e` say?

**Comment by tsoernes** [comment]
```
bind \e cancel
bind -M insert \cy yank
bind -M insert \ey yank-pop
bind -M insert -k right forward-char
bind -M insert -k left backward-char
bind -M insert \e\[C forward-char
bind -M insert \e\[D backward-char
bind -M insert -k ppage beginning-of-history
bind -M insert -k npage end-of-history
bind -M insert \cx fish_clipboard_copy
bind -M insert \cv fish_clipboard_paste
bind -M insert \e 'if commandline -P; commandline -f cancel; else; set fish_bind_mode default; commandline -f backward-char force-repaint; end'
bind -M insert \t complete
bind -M insert -k btab complete-and-search
bind -M insert \e\n commandline\ -i\ \\n
bind -M insert \e\r commandline\ -i\ \\n
bind -M insert -k down down-or-search
bind -M insert -k up up-or-search
bind -M insert \e\[A up-or-search
bind -M insert \e\[B down-or-search
bind -M insert \e\eOC nextd-or-forward-word
bind -M insert \e\eOD prevd-or-backward-word
bind -M insert \e\e\[C nextd-or-forward-word
bind -M insert \e\e\[D prevd-or-backward-word
bind -M insert \eO3C nextd-or-forward-word
bind -M insert \eO3D prevd-or-backward-word
bind -M insert \e\[3C nextd-or-forward-word
bind -M insert \e\[3D prevd-or-backward-word
bind -M insert \e\[1\;3C nextd-or-forward-word
bind -M insert \e\[1\;3D prevd-or-backward-word
bind -M insert \e\[1\;9C nextd-or-forward-word
bind -M insert \e\[1\;9D prevd-or-backward-word
bind -M insert \e\eOA history-token-search-backward
bind -M insert \e\eOB history-token-search-forward
bind -M insert \e\e\[A history-token-search-backward
bind -M insert \e\e\[B history-token-search-forward
bind -M insert \eO3A history-token-search-backward
bind -M insert \eO3B history-token-search-forward
bind -M insert \e\[3A history-token-search-backward
bind -M insert \e\[3B history-token-search-forward
bind -M insert \e\[1\;3A history-token-search-backward
bind -M insert \e\[1\;3B history-token-search-forward
bind -M insert \e\[1\;9A history-token-search-backward
bind -M insert \e\[1\;9B history-token-search-forward
bind -M insert \e. history-token-search-backward
bind -M insert \el __fish_list_current_token
bind -M insert \ew 'set tok (commandline -pt); if test $tok[1]; echo; whatis $tok[1]; commandline -f repaint; end'
bind -M insert \cl echo\ -n\ \(clear\ \|\ string\ replace\ \\e\\\[3J\ \"\"\)\;\ commandline\ -f\ repaint
bind -M insert \cc __fish_cancel_commandline
bind -M insert \cu backward-kill-line
bind -M insert \cw backward-kill-path-component
bind -M insert \e\[F end-of-line
bind -M insert \e\[H beginning-of-line
bind -M insert \ed 'set -l cmd (commandline); if test -z "$cmd"; echo; dirh; commandline -f repaint; else; commandline -f kill-word; end'
bind -M insert \cd delete-or-exit
bind -M insert -k f1 __fish_man_page
bind -M insert \eh __fish_man_page
bind -M insert \ep __fish_paginate
bind -M insert \e\# __fish_toggle_comment_commandline
bind -M insert -m paste \e\[200\~ __fish_start_bracketed_paste
bind -M insert \r execute
bind -M insert \n execute
bind -M insert '' self-insert
bind -M insert -k home beginning-of-line
bind -M insert -k end end-of-line
bind -M insert -k dc delete-char forward-char backward-char
bind -M insert -k backspace backward-delete-char
bind -M insert \b backward-delete-char
bind -M insert -k sdc backward-delete-char
```

**Comment by tsoernes** [comment]
This is the full extent of my fish config:
```
fish_vi_key_bindings

set -U fish_escape_delay_ms 10

function fish_prompt
    powerline-shell --shell bare $status
end

# Paths to your tackle
set tacklebox_path ~/.tackle ~/.tacklebox

# Theme
#set tacklebox_theme entropy

# Which modules would you like to load? (modules can be found in ~/.tackle/modules/*)
# Custom modules may be added to ~/.tacklebox/modules/
# Example format: set tacklebox_modules virtualfish virtualhooks

# Which plugins would you like to enable? (plugins can be found in ~/.tackle/plugins/*)
# Custom plugins may be added to ~/.tacklebox/plugins/
# Example format: set tacklebox_plugins python extract

# Load Tacklebox configuration
. ~/.tacklebox/tacklebox.fish
```

**Comment by faho** [comment]
Ah, okay.

Yeah, see that "force-repaint" there? That forces fish to repaint the prompt. And since it doesn't know which part will be different, it has to execute the entire thing.

Which means it'll call `fish_prompt`, `fish_right_prompt` and `fish_mode_prompt`. One of those must be slow for you. Make your prompt faster and the delay should disappear.

I also recommend upgrading to 3.0.2, since that's generally quite a bit faster.

**Comment by tsoernes** [comment]
So regular bash don't have to repaint the prompt? I'm using the same prompt there

**Comment by faho** [comment]
Yes, bash does not have the assumption that the prompt can change because of vi-mode. It doesn't feature a mode indicator.

**Comment by tsoernes** [comment]
Problem solved by changing to a lighter prompt. Is there a way to get a thin and blocky cursor for insert mode and command mode respectively?

**Comment by faho** [comment]
>Is there a way to get a thin and blocky cursor for insert mode and command mode respectively?

If your terminal supports it, `set -g fish_cursor_default block; set -g fish_cursor_insert line`.

**Comment by faho** [comment]
Okay, I've now added a commit that makes it so this only reexecutes the `fish_mode_prompt` function.

That should cut the time down significantly.

**Comment by faho** [comment]
After some careful thought, I've added 99dd6d7394576d1e6e9600efef8a8375d50ba6e which only uses fish_mode_prompt if it exists. Otherwise it acts like a normal repaint.

I'd assume there are people out there who have a mode indicator at another place in their prompt, and they seem to be okay with the time it takes. So they'd simply have to not define a fish_mode_prompt function (i.e. an empty file, not just an empty function) at all.

**Comment by floam** [comment]
Huh I didn't even know about `fish_cursor_default` - lets feature this more prominently in the documentation and a selector in `fish_config`.

**Comment by neon64** [comment]
@faho this has broken my config on the latest master - in which I have my own mode prompt inside `fish_right_prompt` (so it displays N, I, V etc.. on the right hand side of the screen). Is this regression intended, and if so, is there a workaround to manually re-execute `fish_right_prompt` every time my mode changes?

**Comment by faho** [comment]
Remove fish_mode_prompt. I.e. create an empty file at ~/.config/fish/functions/fish_mode_prompt.fish

**Comment by neon64** [comment]
Thanks that worked! - perhaps this behavior ought to be mentioned in the docs somewhere though

**Comment by zanchey** [comment]
Updated to make even clearer in c5e535e79.
