### ISSUE TITLE
git with --cached does not include staged

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5785]
The completions for `git checkout`/`git diff`/`git reset` (and others?) ignore the `--cached` switch, when present the completions should be generated from a list of files with staged changes.

**Comment by faho** [comment]
>The completions for git checkout/git diff/git reset (and others?) ignore the --cached switc

`git checkout` and `git reset` _have no_ "--cached" switch, according to the man page.

**Comment by mqudsi** [comment]
I need to review my git switches. Is it just `git diff` then?

----

nope:

```
mqudsi@Blitzkrieg /m/c/U/Mahmoud> rg -z -P 'git (?!(git|diff)).*cached' /usr/share/man/man1/git* -o
/usr/share/man/man1/git-diff.1.gz
864:[Omitted long matching line]

/usr/share/man/man1/git-diff-files.1.gz
805:[Omitted long matching line]

/usr/share/man/man1/git-diff-index.1.gz
805:[Omitted long matching line]
1798:git write\-tree\fR + \fIgit diff\-tree\fR\&. Thus that\(cqs the default mode\&. The non\-cached

/usr/share/man/man1/git-diff-tree.1.gz
811:[Omitted long matching line]

/usr/share/man/man1/git-filter-branch.1.gz
93:git rm \-\-cached
206:git rm\fR yields a significantly faster version\&. Like with using \fBrm filename\fR, \fBgit rm \-\-cached
212:git filter\-branch \-\-index\-filter \*(Aqgit rm \-\-cached

/usr/share/man/man1/git-format-patch.1.gz
516:[Omitted long matching line]

/usr/share/man/man1/git-log.1.gz
3454:[Omitted long matching line]

/usr/share/man/man1/git-read-tree.1.gz
263:[Omitted long matching line]

/usr/share/man/man1/git-remote.1.gz
241:git ls\-remote <name>\fR; cached

/usr/share/man/man1/git-rm.1.gz
35:git rm\fR [\-f | \-\-force] [\-n] [\-r] [\-\-cached
40:[Omitted long matching line]
145:git rm \-\-cached
153:[Omitted long matching line]

/usr/share/man/man1/git-show.1.gz
2044:[Omitted long matching line]

/usr/share/man/man1/git-status.1.gz
597:git status\fR will automatically refresh the index, updating the cached

/usr/share/man/man1/git-submodule.1.gz
36:git submodule\fR [\-\-quiet] status [\-\-cached
```

**Comment by faho** [comment]
>Is it just git diff then?

>nope:

Welll.... a bunch of these are either plumbing commands we don't currently complete (e.g. diff-index, read-tree) or refer to other commands like `git diff --cached` (log, format-patch, show). Or they just feature the word "cached" (status, remote).

So its:

- submodule status/summary (but the option behaves differently as far as I can tell)
- rm
- diff

(As a sidenote, I _loathe_ the wording of this option, and how git in general can't decide between "index", "staging area" and "cache", especially since two of those seem tailor-made for confusion)

**Comment by mqudsi** [comment]
Thanks, @faho.
