### ISSUE TITLE
Fish should have a POSIX-sh mode

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#5787]
This is probably heretical, but fish ought to have a POSIX-sh mode. Perhaps when executed as /bin/sh. This will enable distributions to consider making fish the default shell. Fish Just Works, and the user base and interest can increase exponentially if some OS or Linux distribution decides to take the leap. I'm interested in hearing opinions of other committers and users.

**Comment by floam** [comment]
A good counter-argument is that every system already ships with a perfect `/bin/sh`, and that is what should be used for that kind of code. But in my opinion without such support built-in, fish will never gain meaningful traction.

**Comment by faho** [comment]
We've discussed this a bunch over the years, and the end result is always that it's not worth it. There's no huge need to run sh script in fish directly - you either run it in an external sh, or you have to 'source' some stuff and bass works well enough for that.

posix script also has enough awful parts (see our issues with test) that I don't want to work on it.

I.e.: A massive -10000, with a cherry on top, from me.

**Comment by faho** [comment]
And I don't care about "traction". I care about making a good shell.

**Comment by faho** [comment]
And I don't care about "traction". I care about making a good shell.

**Comment by floam** [comment]
I care about making working with computers nicer for as largest a number of people as possible. I think pretty soon we will be the fastest shell, doing sub shells in threads, and there will be practical reasons for people to consider it for everything. Users new to shells will be well served by fish instead of bash. Obviously, +10001 from me. :wink:

**Comment by faho** [comment]
Do you want to write it and take care of compliance bugs and all the issues that come along with having two dialects interact with each other?

New users are better served by having a better language, not the old historically grown BS with all decades old mistakes ingrained.

**Comment by floam** [comment]
It would take a saint to implement, but I think it should b ea goal.

**Comment by floam** [comment]
In the mean-time, we can continue to do what we can to make the bash -> fish transition easier.

**Comment by floam** [comment]
To be clear, what I am suggesting is that fish can be considered able to be `/bin/sh`. Not bash. People will interactively experience fish and not sh. They will not write new `sh` scripts because our language is better.

**Comment by floam** [comment]
Hell, we could literally pull in BSD-licensed mksh code.

**Comment by floam** [comment]
There are some thoughts here: https://github.com/fish-shell/fish-shell/wiki/POSIX-compatibility-thoughts

**Comment by mqudsi** [comment]
There's nothing stopping a distribution from shipping with fish as the default user shell but a separate (minimal) /bin/sh for system use. None do, as far as I know.

**Comment by floam** [comment]
Yeah I think that was a flawed assumption I made. That a users' default shell really ought to be `/bin/sh`. Even on embedded systems, a tiny `/bin/sh` is not a big deal if they can also fit in a fish binary.

**Comment by inigosola** [comment]
+1
