### ISSUE TITLE
Wrong work of bindings forward-word and backward-word with dashes

### ISSUE THREAD

**Issue by zveber** [fish-shell/fish-shell#5789]
if I have a command "app --arg" in history and entered "app" in the command line it is expected that pressing of key bound to forward-word will type "--arg". But instead it inserts a dash, "-".  I repeat pressing. It types the second dash and the third pressing types the word "arg".
> fish -v                                   
fish, version 3.0.2

**Comment by faho** [comment]
Duplicate of #2266
