### ISSUE TITLE
How to ignore abbreviation

### ISSUE THREAD

**Issue by brandoncc** [fish-shell/fish-shell#5792]
I'm using fish 2.71 on MacOS. Is it possible to ignore abbreviations? I have been using ghostscript quite a bit lately which is very annoying since when I type `gs` it expands to `git status`. Is there a way to skip the expansion? I have to use ghostscript in a different shell at the moment.

Thanks

**Comment by zanchey** [comment]
If you write `command gs` then that will skip the expansion, but if you only want to skip expansion in the current shell you can abbreviate it to itself:

```fish
abbr --add --universal gs git status
abbr --add --global gs gs
```

**Comment by brandoncc** [comment]
Ah, perfect. Thanks!
