### ISSUE TITLE
Consider supporting gitstatus with fish git prompt?

### ISSUE THREAD

**Issue by lilyball** [fish-shell/fish-shell#5799]
I just ran across https://github.com/romkatv/gitstatus which advertises a 10x faster alternative to `git status` intended to be used to drive shell prompts. It uses a background daemon `gitstatusd` that maintains state and talks with it using pipes.

If someone has the spare time it might be nice to add support to this to the built-in fish git prompts.

**Comment by zanchey** [comment]
I am terrified by the build script in that package, but it seems like a reasonable thing to try.

**Comment by lilyball** [comment]
We don't need to care about the build script, just convert `gitstatus.plugin.zsh` to fish and add a toggle to let the user say "please use `gitstatus`" (which will just assume that the binary is in the path).

**Comment by floam** [comment]
I mean, if `command -sq gitstatus` works, it would make sense for it to just kick in that set of completions automatically, right?

**Comment by faho** [comment]
*I* am terrified of gitstatus.plugin.zsh. There's a whole bunch of weird arcane magic in there, one major thing is that we don't have a way to set a timeout, so we could `read` the response fd and it would hang indefinitely.

Plus I _really_ don't want to be responsible for daemons. Really, this should have a client that you can use that handles the IPC stuff and just prints the output you're looking for, otherwise I don't consider it workable.

(I mean I don't get why this is a separate project, at all, this should really be done in git proper, but it is what it is)

**Comment by floam** [comment]
We should give `read` a timeout feature but that's for another issue. Several times I've hit hard walls trying to do things because I couldn't control when it'd stop reading well enough.

**Comment by floam** [comment]
> Plus I *really* don't want to be responsible for daemons

Just to be clear, this does not require `fish` to implement any daemons. Merely to interact with one. We should consider things preventing us from doing so where other shells can as inadequacies to be addressed.

**Comment by faho** [comment]
> Just to be clear, this does not require fish to implement any daemons. Merely to interact with one.

The zsh "plugin" runs it and kills it and deals with pids and file locking and all that jazz. That's what I mean.

Really, realistically, the best chance this has of getting implemented is to write a "client" for this daemon that we can just call. That would also help everyone.

**Comment by floam** [comment]
It's a young project, maybe they can be led to the light.

**Comment by floam** [comment]
I mean, it's already written in c++, so extending in that way is not out of the question at all.

**Comment by mqudsi** [comment]
As soon as I saw the word "daemon" in the original comment I immediately wanted to say what @faho did. Calling an alternative `git` client to get results if it exists is along the lines of what we do for everywhere for cross-compatibility reasons and I'd be open to that, but starting, stopping, etc. a background service is way out there and I'd be completely against that.

**Comment by faho** [comment]
Okay, as it stands, I'm closing this, as it can't currently be implemented, and I don't think we should add the facilities to allow it to be. Instead, a simple client that can be called by all shells would make things easier for everyone involved. If that appears, we'll use it.
