### ISSUE TITLE
"for" does not validate variable names

### ISSUE THREAD

**Issue by 0ion9** [fish-shell/fish-shell#5800]
`for a,b in y 1 z 3; echo $a,$b; end`

*Expected result*: either an error or (ideally) setting a=y b=1, iterating once, then setting a=z b=3; printing each of those pairs on its own line.

*Actual result*: 4 blank lines

Proof of what is actually happening:

`for a,b in y 1 z 3; set -l; end`

Result:
```
a,b y
a,b 1
a,b z
a,b 3
```

In other words, `for` is assigning to a variable named "a,b".

This variable cannot be expanded (`echo $a,b` expands correctly to nothing ($a is not set, and therefore the product of it with ",b" is nothing)), nor can the user set, query, or erase this variable.

----

fish version 3.0.2-824-gbf40f84b0

**Comment by 0ion9** [comment]
List of invalid characters that `for` accepts in a variable name:

```
,-!$#%^&*()=+[]
;:"/?.><|\`~
```
So, basically all of them, and in any position (for example `for , in 1 2 3; set -l;end`)

**Comment by floam** [comment]
Yeah, that's a bug. It actually is created, too, neat:

```
$ for a,b in a;
        set|grep 'a,b'
    end
a,b a
```

**Comment by floam** [comment]
fixed:

```fish
for a,j in i v; echo foo; end
fish: invalid var name: a,j
for a,j in i v; echo foo; end
    ^
```
