### ISSUE TITLE
Segfault trying to run script in docker

### ISSUE THREAD

**Issue by locallycompact** [fish-shell/fish-shell#5807]
Hi, I'm trying to execute a fish script which runs fine on my local machine on NixOS, but fails in a NixOS docker. fish --version works in the docker and returns 3.0.2, but attempting to run a script results in many lines of the form.

```
<4> fish: Set status of job 2194 (test ...) to 0 using short circuit
<3> fish: Created job 2194 from command 'test -f /etc/fish/config.fish' with pgrp -2
<4> fish: Start job 2194, gid -2 (test -f /etc/fish/config.fish), COMPLETED, NON-INTERACTIVE
<5> fish: intern /etc/fish/config.fish
<5> fish: intern /etc/fish/config.fish
<5> fish: intern /etc/fish/config.fish
<5> fish: intern /etc/fish/config.fish
<5> fish: intern /etc/fish/config.fish
<4> fish: Skipping fork: no output for internal builtin 'test'
```

Full Log here:

https://gitlab.com/zenhaskell/infra-dockers/pipelines/56255895

**Comment by faho** [comment]
What's the script you're trying to run, and what does your /etc/fish/config.fish contain?

**Comment by locallycompact** [comment]
Any script will fail with a segfault. Something as simple as

```
#!/usr/bin/env fish
echo "foo"
```

will fail. There's no /etc/fish/config.fish either on my host or in the docker.

**Comment by faho** [comment]
Ah, okay. This seems like a nix issue, as it appends this bit to /etc/fish/config.fish:

```fish
if test -f /etc/fish/config.fish
      source /etc/fish/config.fish
end
```

which will loop sourcing /etc/fish/config.fish until it eventually runs out of memory and crashes. (https://github.com/NixOS/nixpkgs/blob/master/pkgs/shells/fish/default.nix#L40-L42)

@matthewbauer, @profpatsch?

**Comment by Profpatsch** [comment]
Please open an issue in nixpkgs.

**Comment by locallycompact** [comment]
Raised here https://github.com/NixOS/nixpkgs/issues/59357

**Comment by faho** [comment]
Closing this as a nix issue.
