### ISSUE TITLE
Empty lines in /etc/paths.d cause . to appear in PATH on macOS Mojave

### ISSUE THREAD

**Issue by Strayer** [fish-shell/fish-shell#5809]
I recently discovered that my PATH contains a `.` between the default paths of macOS from /etc/paths*:
```
sh-3.2$ sh -c 'env HOME=$(mktemp -d) /usr/local/bin/fish'
Welcome to fish, the friendly interactive shell
strayer@wolf359 /U/s/.config> echo $PATH
/usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin /Applications/VMware Fusion.app/Contents/Public /Library/TeX/texbin . /Applications/Wireshark.app/Contents/MacOS
strayer@wolf359 /U/s/.config> echo $fish_user_paths
```

One of the files in /etc/paths.d contains empty lines (/etc/paths.d/TeX to be specific):
```
strayer@wolf359 /U/s/.config> cat /etc/paths /etc/paths.d/*
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/opt/X11/bin
/Applications/VMware Fusion.app/Contents/Public/Library/TeX/texbin


/Applications/Wireshark.app/Contents/MacOS
```

When I manually remove these empty lines, the dot doesn't appear in PATH anymore:
```
sh-3.2$ sh -c 'env HOME=$(mktemp -d) /usr/local/bin/fish'
Welcome to fish, the friendly interactive shell
strayer@wolf359 /U/s/.config> echo $PATH
/usr/local/bin /usr/bin /bin /usr/sbin /sbin /opt/X11/bin /Applications/VMware Fusion.app/Contents/Public /Library/TeX/texbin /Applications/Wireshark.app/Contents/MacOS
```

fish version, installed via Homebrew:
```
strayer@wolf359 ~> fish --version
fish, version 3.0.2
strayer@wolf359 ~> echo $version
3.0.2
```

TERM: xterm-256color
macOS Mojave 10.14.4 (18E226)
Terminal: iTerm2 Build 3.3.0beta2

**Comment by floam** [comment]
Can reproduce.

**Comment by floam** [comment]
There is a small problem with the logic causing empty elements to be put into $PATH. And I did not know this until now but we translate these to `.` on purpose.

```c++
/// Ensure the content of the magic path env vars is reasonable. Specifically, that empty path
/// elements are converted to explicit "." to make the vars easier to use in fish scripts.
static void init_path_vars() {
    // Do not replace empties in MATHPATH - see #4158.
    fix_colon_delimited_var(L"PATH", env_stack_t::globals());
    fix_colon_delimited_var(L"CDPATH", env_stack_t::globals());
}
```

**Comment by floam** [comment]
I don't understand this business of sticking `.` into `$PATH` or `$CDPATH` here. What am I not getting? If someone prepended an empty component to `$PATH`, they'd be in a potentially dangerous situation when in a directory with unfortunately-named binaries.

**Comment by floam** [comment]
Oh, I didn't realize that empty $PATH components usually *are* equivalent to `.` in most shells.

**Comment by faho** [comment]
Does the official path_helper thing handle this in the same way?

**Comment by faho** [comment]
Does the official path_helper thing handle this in the same way?

**Comment by floam** [comment]
Yes. Blank lines are ignored.

**Comment by floam** [comment]
[path_helper.c](https://opensource.apple.com/source/shell_cmds/shell_cmds-203/path_helper/path_helper.c.auto.html)
