### ISSUE TITLE
caret positioned incorrectly or not shown in errors expanding in command position

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#5812]
This happens when the expansion happens in a command position:

```
$ if $,asd
fish: $, is not a valid variable in fish.
if $,asd
 ^
$ command $,asd
fish: $, is not a valid variable in fish.
command $,asd
 ^
```

No carat at all is shown here, but one should be shown.
```
$ command (asd)
fish: Command substitutions not allowed
```

**Comment by floam** [comment]
Fixed:

```
~ $ if $,,,
fish: $, is not a valid variable in fish.
if $,,,
    ^
~ $ builtin (asd)
fish: Command substitutions not allowed
builtin (asd)
        ^
```

**Comment by zanchey** [comment]
The caret is still positioned wrong in non-interactive mode:

```
> fish -c 'echo $,foo' # correct
fish: $, is not a valid variable in fish.
echo $,foo
      ^
> fish -c 'if $,,,; end' # wrong
fish: $, is not a valid variable in fish.
if $,,,; end
 ^
> fish -c 'command (foo)' # very wrong
fish: Command substitutions not allowed
command (foo)
^
```

**Comment by floam** [comment]
Have you got any idea what is the big difference here between interactive and non-interactive? Most of these seem to be off by 3, as in the 3 characters of `if `. For instance this one should be pointing under '`a`':

```
fish -c 'if $fooo[a]; end'
fish: Invalid index value
if $fooo[a]; end
      ^
```

But not all parse errors in this if construct have the issue:

```
fish -c 'if }; end'
fish: Unexpected '}' for unopened brace expansion
if }; end
   ^
```

**Comment by krobelus** [comment]
> Have you got any idea what is the big difference here between interactive and non-interactive?

It seems that interactive mode is using `parse_util_detect_errors` to find this error, and non-interactive `expand_to_command_and_args`.
