### ISSUE TITLE
eval docs are misleading and in one case clearly wrong.

### ISSUE THREAD

**Issue by 0ion9** [fish-shell/fish-shell#5816]
> Note that fish does not support the use of shell variables as direct commands;

False for a while now .

```set cmd ls
$cmd
```

> eval can be used to work around this.

Obsolete justification, followed by an example that probably would properly be written using shell variables as direct commands rather than eval.

Here's a modified example that somewhat justifies eval:

          set cmd ls \| cut -c 1-12
          eval $cmd

..since we still do not support *compound-commands*-in-shell-variables and are unlikely to ever do so.

(If there's some issue like 'it has to also be uploadable on the website to cover the last stable version', then I apologize for the churn. But it seemed reasonable to expect that the locally installed documentation would be fairly accurate to the locally installed version (3.0.2-824-gbf40f84b0 , FWIW))

**Comment by mqudsi** [comment]
> If there's some issue like 'it has to also be uploadable on the website to cover the last stable version',

Nope, the documentation in trunk should be inline with the code, the website docs are from a separate branch.

Would you like to file a PR for this?

**Comment by 0ion9** [comment]
Ok, done, thanks for the prompt. As noted in the PR, there is also a bit of stuff lying around in .po files which I left alone for the time being as I wasn't certain how correct removing it would be.
