### ISSUE TITLE
R_CANCEL should abort history search

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#5818]
From the gitter chat, escape is supposed to abort a history search but it doesn't:

> hi all, i've started using fish for a couple of weeks and i find it awesome. however it seems i'm not able to abort history search. the documentation says hitting `Esc` will abort the search, but nothing happens when i try it. am i doing something wrong? can you help me to fix this? (using fish version 3.0.2, macos 10.14, apple terminal)

Credit to 'mrrech' for spotting this.

**Comment by mrrech** [comment]
Hi @ridiculousfish,
thanks for opening this. How can I help to track down the bug (or if it is actually a bug)?

**Comment by mqudsi** [comment]
@mrrech nothing for you to do, this is just filing it in the system and giving you a head's up. Now that you've commented you'll receive a notification when it's resolved.
