### ISSUE TITLE
yum install on CentOS is broken

### ISSUE THREAD

**Issue by jhdxr** [fish-shell/fish-shell#5821]
following the link on fishshell.com, I was redirect to https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A3&package=fish
however, the link for RHEL7 (http://opensuse.ucom.am/repositories/shells:/fish:/release:/3/RHEL_7/src/fish-3.0.2-1.5.src.rpm) is broken. I'm not sure if this is maintained by fish shell, but since I got this link from fishshell.com, I think it's ok to open a ticket here.

**Comment by Evil4Fish** [comment]
same error
` http://download.opensuse.org/repositories/shells%3A/fish%3A/release%3A/3/RHEL_7/x86_64/fish-3.0.2-1.5.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found                                   ]  0.0 B/s |    0 B  --:--:-- ETA 
Trying other mirror.
To address this issue please refer to the below wiki article 

https://wiki.centos.org/yum-errors

If above article doesn't help to resolve this issue please use https://bugs.centos.org/.



Error downloading packages:
  fish-3.0.2-1.5.x86_64: [Errno 256] No more mirrors to try `

**Comment by zanchey** [comment]
Seems to be working how, I suspect a mirror was broken.
