### ISSUE TITLE
Multiple functions in same file

### ISSUE THREAD

**Issue by Afsar-Pasha** [fish-shell/fish-shell#5823]
Allow defining multiple function names in a single filename separated with spaces.
e.g., If a file named `x y.fish` then auto completion should the shown for x and y.

fish version 3.0.2

**Comment by faho** [comment]
No.

Function files can contain multiple functions, but they'll only be loaded with the one their named after.

**Comment by Afsar-Pasha** [comment]
@faho, I don't think you understand what I meant, anyways just checked that functions can contain spaces, so it would be impossible to define multiple function names **for auto completion** in a single file name separated by spaces.

**Comment by ridiculousfish** [comment]
Yes let's never assign meaning to filenames containing spaces.

**Comment by floam** [comment]
You might be able to use symlinks to accomplish what you want FWIW.
