### ISSUE TITLE
`jobs` broken in functions

### ISSUE THREAD

**Issue by amiller27** [fish-shell/fish-shell#5824]
The `jobs` command seems to be broken in functions; creating a background job in a function, and then calling `jobs` lists nothing.  For example, creating the following script and running it prints out "jobs: there are no jobs", followed by "blerg" a second later:
```
function mytest
    fish -c 'sleep 1; and echo blerg' &
    jobs
end
mytest
```

A git bisection search traces this to 04a96f6, which was a fix for #5803.
This was all tested in an Ubuntu 16.04 docker container and an Ubuntu 18.04 machine.

**Comment by mqudsi** [comment]
Thanks for reporting this. I've taken care of it with 8ca264185745d3a92d7f504801b427bf48890e44 and will have to rethink the approach for eliding the traditional cruft from fish `jobs` calls.

**Comment by amiller27** [comment]
Should this be added to the tests? It seems like problems like this which are inadvertently broken should be in the tests so they don't get broken inadvertently again.

**Comment by zanchey** [comment]
Added in 4ddfd730.
