### ISSUE TITLE
Good Idea / Bad Idea: CWD Event

### ISSUE THREAD

**Issue by robacarp** [fish-shell/fish-shell#583]
RVM's behavior under a bash compatible shell is to wrap `cd` so it can check for .rvmrc files whenever a directory is changed.

Many of the workarounds people have taken to get rvm working under fish involve this pattern:

```
function cd
  builtin cd $argv
  #rvm stuff
end
```

I think fish's event broadcast system is a better idea, so I did this instead:

```
function cd --description "Change working directory"
  builtin cd $argv
  emit cwd
end

function __check_rvm_at_cwd --on-event cwd
  #rvm stuff
end
```

This will allow me to hook into the cd in several places, should the need arise.  I notice that implicit directory changing seems to call `cd` explicitly, so it even works in the event that I don't explicitly call the wrapper.

Given that the two existing global events are `fish_prompt` and `fish_command_not_found`, I expect that firing an event is a pretty fast operation, since those are probably fired quite often.

For what its worth, I also have a hunch that Issue #87 could be solved by listening to a cwd event.

**Comment by artagnon** [comment]
For this implementing autols:
```
function l --on-variable PWD
        ls $argv
end
```

I get:
```
ls: PWD: No such file or directory
ls: SET: No such file or directory
ls: VARIABLE: No such file or directory
```

Is $argv somehow polluted because of this event handling?

**Comment by faho** [comment]
>Is $argv somehow polluted because of this event handling?

Yes. It is set to "VARIABLE SET PWD".

Why not just use `ls`? It defaults to the current directory anyway.

**Comment by krader1961** [comment]
It's an undocumented aspect of event callbacks. If you had instead erased the variable (e.g., `set -e PWD` assuming it was a regular var) then `$argv` would be `VARIABLE ERASE PWD`.

Why are you passing `$argv` to the `ls` command? Are you trying to create a function that can be used interactively as well as via an event callback? If so you'll need to split this into two functions.

**Comment by artagnon** [comment]
I was curious about this behavior. Thanks for clearing it up.

**Comment by artagnon** [comment]
See `function ll` in the tutorial: http://fishshell.com/docs/current/tutorial.html#tut_startup - I'd blindly put in the $argv without thinking.

**Comment by floam** [comment]
I didn't know we do this - interesting.
