### ISSUE TITLE
Incorrect tab-completion escaping with certain characters

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#5831]
```
$ fish --version
fish, version 3.0.2-948-g4ddfd730
```

Repro:

```
$ touch foo foo[bar]
$ ls foo[<TAB>
$ ls foo[bar\]
```

This should have completed to either `foo[bar]` or `foo\[bar\]`, but not `foo[bar\]`:

![image](https://user-images.githubusercontent.com/8544900/56443342-1ffd2b00-62ec-11e9-8a08-e2b35c1fec06.png)

**Comment by ridiculousfish** [comment]
I like the new approach better too! Merged as bc3dde997decd8db318bed322c8d31d0528f4879 . Thank you!
