### ISSUE TITLE
fish process name shows as `-fish` in certain cases

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5839]
Under certain conditions (it happens to me when fish is the login shell on a remote machine that I ssh into, connecting to both FreeBSD and Fedora 28 server), the name of the fish process appears as `-fish` rather than `fish` :

![image](https://user-images.githubusercontent.com/606923/56526597-194ffd00-6512-11e9-9540-b708ea625f17.png)

There may be other cases, too. I don't know if it happens with fish 2.0, but I have been seeing this behavior for at least a year.

edit: and tmux

![image](https://user-images.githubusercontent.com/606923/56527025-adba5f80-6512-11e9-9074-09a18c1c8cc2.png)

**Comment by floam** [comment]
That's what a login shell is. `login` will exec `$SHELL` as `-$SHELL`.

**Comment by mqudsi** [comment]
But on my main machine (Ubuntu 18.04 via WSL) I don't see that:

![image](https://user-images.githubusercontent.com/606923/56527063-b9a62180-6512-11e9-94e5-fc4b0f7038c9.png)

(and I've verified chsh lists `/usr/local/bin/fish` as the login shell)

**Comment by zanchey** [comment]
https://superuser.com/questions/278859/dash-in-front-of-bash
