### ISSUE TITLE
error message references "array" not "list"

### ISSUE THREAD

**Issue by danielb2** [fish-shell/fish-shell#5846]
fish, version 3.0.2

```
$ echo $PATH[0]
fish: array indices start at 1, not 0.
```

to be consistent with documentation, the error message should read `list indices start at 1, not 0`

**Comment by faho** [comment]
>to be consistent with documentation

https://github.com/fish-shell/fish-shell/blob/master/sphinx_doc_src/index.rst#arrays exists.

I'm not sure we want to always talk about "lists", because "array" is a well-known term as well.

**Comment by danielb2** [comment]
Would it be prudent then to switch out all references to just say array instead of list? I'm weary of using one terminology in one place, and another in another. It creates confusion

**Comment by ridiculousfish** [comment]
Yes, please do a PR to make this consistent. I like "list" slightly more because it's shorter but no strong opinions.

**Comment by zanchey** [comment]
List is a better term for non-programmers.

**Comment by faho** [comment]
Okay, closed. I decided to mention the term "array" (and keep a bit where we say `Other shells use the term "arrays"`), and it's still `read --array` (altering that would have been a bit embarassing).

**Comment by zanchey** [comment]
Should we add `--list` as a synonym?

**Comment by zanchey** [comment]
Done in 225b1204d6928b484335917af8fbfb0de20e6f90
