### ISSUE TITLE
recent argparse destroys args after second "--", unless -s option is given

### ISSUE THREAD

**Issue by 0ion9** [fish-shell/fish-shell#5857]
I'm guessing this might be related to the recent addition of -i option to argparse.
I was using this multiple-`--` convention previously with the same function, with no problems. It's a way to group args -- the actual usecase involves specifying one command between the first and second `--`, and another command between the second and third `--`.

Minimal test case:

```
function apbug
    echo "Before argparse,  '$argv'" 1>&2
    argparse o/output= i/interval= d/date-format= -- $argv
    echo "After argparse,  '$argv'" 1>&2
    set -l
end
```

`apbug -o /tmp/log -- some args -- more args, all of these will be discarded`

Actual output:

```
Before argparse,  '-o /tmp/log -- some args -- more args, all of these will be discarded'
After argparse,  ''
_flag_o /tmp/log
_flag_output /tmp/log
argv
```
The options are correctly parsed, but the remaining arguments are destroyed.
 
Expected output:
```
Before argparse,  '-o /tmp/log -- some args -- more args, all of these will be discarded'
After argparse,  'some args -- more args, all of these will be discarded'
_flag_o /tmp/log
_flag_output /tmp/log
argv some args -- more args, all of these will be discarded
```
(this last line will actually be ellipsized, but I wrote it out fully for clarity)
In the expected output, the args after `--` are preserved, which I understand is normal for GNU getopt or at least fish builtins. For example `string join , -- -- --` produces the string `--,--`, implying that the first -- is treated as '<end of option parsing>' and the following `--` are treated as literal strings.

Current fish version: 2:3.0.2.r1021.g649d3ac10-1
Previous fish version: 2:3.0.2.r960.g82052a6cc-1 (this argparse call worked as expected in this version)

Testing in a clean environment makes no difference to the outcome.

Changing `argparse` to `argparse -s` prevents the destruction of args after second `--`. This is an acceptable solution for this particular usecase, but I thought I should report this bug anyway, as it seems to be a regression.

**Comment by faho** [comment]
Yeah, it's a regression. GNU getopt shuffles the non-option arguments until _after_ all the options, so then you can just read them all in one nice for-loop. I had to turn that functionality off to allow ignore-unknown to work right (or it would have the unknown options shuffled before the non-options, and also it's modifying frickin' *const* variables!). Only you still need the for-loop to read all the arguments that getopt ignored because they were after a `--`.
