### ISSUE TITLE
fish_config appers blank and unresponsive

### ISSUE THREAD

**Issue by irvall** [fish-shell/fish-shell#5863]
**Environment:**
```
Fish version: 3.0.2
echo $TERM: xterm-256color
OS: macOS Mojave 10.14.4 (18E226)
Terminal emulator: iTerm2
```

When accessing `fish_config` the website appears almost empty, and no hyperlinks seem to work.

![Blank fish_config](https://i.imgur.com/PWuCUBq.png "Blank fish_config")

Steps tried:

- Uninstall running `brew uninstall fish`
- Removed `.config/fish` directory
- Removed `/usr/local/bin/fish`
- Reinstalled everything with same results

**Comment by irvall** [comment]
Also – just to state the obvious: I seem to remember it opened up a server on localhost – this seem to be a generic HTML page as well.

**Comment by faho** [comment]
So... what does it say in the terminal?

YOur browser looks like firefox, which is having some... issues at the moment. Can you try another browser to rule out any weirdness? Or do you have javascript disabled?

**Comment by irvall** [comment]
That's a bingo!

Switched the default browser to Safari, and it opened looking like normal on `localhost`. Not sure how this relates to Firefox Nightly, but it sure seems like odd behaviour.

Thank you.

**Comment by robinwhittleton** [comment]
Just hit this with Firefox Nightly as well. Can this bug be re-opened until the root problem in Firefox is identified, or a fix can be put in for fish_config?

(I’d look into it myself but time is a problem at the moment. If it’s still a problem in 3 weeks I’ll take the bug over)

**Comment by faho** [comment]
>Can this bug be re-opened until the root problem in Firefox is identified, or a fix can be put in for fish_config?

I dont think there *is* a fix for fish_config. The root problem appears to be a bug or misconfiguration in firefox, so that needs to be fixed, but it's nothing to do with fish specifically, so there's no use in reopening this.

**Comment by robinwhittleton** [comment]
Fair enough. I’ve opened https://bugzilla.mozilla.org/show_bug.cgi?id=1553962 to track this problem from the Firefox end.
