### ISSUE TITLE
argparse cannot use twice the same validation function

### ISSUE THREAD

**Issue by kewlfft** [fish-shell/fish-shell#5864]
~~~
fish, version 3.0.2
Arch Linux
~~~

To reproduce type:
`argparse 'i=!_validate_int' 'o=!_validate_int' -- $argv`
Error message:
`argparse: Long flag '_validate_int' already defined`

I would like to be able to use the same validate function more than once in the argparse arguments, this is not a long flag.

**Comment by faho** [comment]
Muahahaha: This actually defines a long option "_validate_int", and sets $_flag_validate_int if you parse `-i2`.

**Comment by faho** [comment]
Yup. Turns out the reason was we use c-style pointer-strings here, and we left the pointer before the validation string.
