### ISSUE TITLE
pthread usage

### ISSUE THREAD

**Issue by gim913** [fish-shell/fish-shell#5867]
Hello,

I haven't looked at all usages of pthreads, so this might be dumb question:
since this is cpp-project is there a reason to use pthread library rather than std::thread? (std::thread should be avail in cpp11)

I'm asking cause it would make creating native windows port bit easier.

**Comment by mqudsi** [comment]
There were earlier efforts to replace pthreads with c++11 equivalents, but recent changes to the codebase (incidentally?) saw the re-introduction of a number of pthread dependencies.

**Comment by ridiculousfish** [comment]
Not a dumb question. The problem is that `pthread_create` is guaranteed to inherit the calling thread's signal mask, and `std::thread` doesn't make any similar guarantees.

What Windows port do you have in mind? fish runs on Cygwin and WSL.

**Comment by mqudsi** [comment]
@ridiculousfish I feel like in practice `std::thread` on posix platforms is guaranteed to be implemented via `pthread_create` in the first place where the same guarantee would apply (without extending to non-posix platforms' implementations of `std::thread`)?

**Comment by faho** [comment]
>I'm thinking of native windows version - no cygwin, no WSL

@gim913: That's basically unworkable. Even if it "ran" on windows, all of our assorted scripts expect a unixoid environment, and I don't think we want to keep a special set of windows-scripts.

**Comment by gim913** [comment]
@faho assuming you have gnu-tools (i.e. from msys2) I believe (although I'm probably very wrong about it), most script would actually work.

fish is one of the modern shells and as such does not have whole baggage of other sh-like shells, which really would make it good candidate for a native windows shell.

**Comment by faho** [comment]
>assuming you have gnu-tools (i.e. from msys2) I believe (although I'm probably very wrong about it), most script would actually work.

If you need to install tools anyway, why not just use cygwin or wsl to begin with? What does a native fish help? You're overestimating the usefulness and underestimating the amount of work required - threads are the smallest of your problems. I'm pretty sure you've not looked at fork/exec/posix_spawn and signals and environment variables and argument passing and....

**Comment by gim913** [comment]
until WSL2 comes out, WSL is basically unusable (due to I/O issues)

> You're overestimating the usefulness and underestimating the amount of work required

quite likely, although mind that initial question was only about std::thread vs posix threads

> I'm pretty sure you've not looked at fork/exec/posix_spawn

from what I see it is in huge ifdef...
signals - y would be problematic
environment variables + argument passing - that's quite similar and should be pretty easy part compared with other stuff

I'm certainly not asking or forcing you to make ready to use port. I simply asked about facilities, that would make things at least *bit* easier.

**Comment by faho** [comment]
Okay, I think the question has been answered. To summarize:

- It's possible pthread makes more guarantees on the platforms fish currently runs on (The *BSDs, Linux and macOS mainly), especially regarding the signal mask

- If someone ports to std::thread, and that works as well on those platforms, we'd probably merge it

- A windows port is *much* more work than that, and of dubious value
