### ISSUE TITLE
`-k` argument to `complete` results in reversed set of arguments to what is expected

### ISSUE THREAD

**Issue by gustafj** [fish-shell/fish-shell#5868]
<details>
  <summary>Environment</summary>

```sh
> fish --version
fish, version 3.0.2
> echo $version
3.0.2
> uname -a
Linux hostname 5.0.13-arch1-1-ARCH #1 SMP PREEMPT Sun May 5 18:05:41 UTC 2019 x86_64 GNU/Linux
> echo $TERM
xterm-kitty
```

This is not a regression from 2.7 as far as I can see.

</details>

The `-k` flag to `complete` results in "reversed added order".
I would expect it to return the set of arguments in the *same* order as they were added 

E.g. for `git checkout <tab>` it seems logical to get the local recent commits first, followed by local branches, followed by remotes etc as seems to be what the author intended see:
https://github.com/fish-shell/fish-shell/blob/master/share/completions/git.fish#L897-L901
But instead the "unique remote branches" are returned first.

### What I get
```sh
> complete -f -c foobar -d 'a test for ordering'
> complete -k -f -c foobar -a 'a d c b'
> complete -k -f -c foobar -a '1 4 3 2'
> complete -k -f -c foobar -a 'X y Z q w r'
> foobar <tab>
X  q  1  2  c
y  w  4  a  b
Z  r  3  d  
```

### What I am expecting to see (preserving the order in which arguments are added)
```sh
> foobar <tab>
a  b  3  y  w
d  1  2  Z  r
c  4  X  q 
```

### Without `-k` (as expected, case insensitive sort):
```sh
> foobar <tab>
1  4  c  r  y
2  a  d  w  Z
3  b  q  X 
```

**Comment by faho** [comment]
Inverse order also makes quite a bit of sense (if you add another `complete`, you expect it to go first).  It's also, in some sense "what the author" intended, because this puts the most important thing, the modified files, last.

How about we just pick a good order for the things and document that this puts later complete calls first?

Recent commits is the 50 last commits.

**Comment by gustafj** [comment]
Documenting the behavior as is, instead of changing, is perfectly fine by me, and has fewer implications for existing scripts :+1: 

However I would propose a different set of ordering for the git completions than what was done in https://github.com/fish-shell/fish-shell/commit/50ed5126f1185e317b91bf265d0d1282dcd35af4 .
I would prefer to have the "local list of branches" before any "unique remote branches" as is now those come after the (potentially huge list) of "unique remotes", what do you think?

**Comment by faho** [comment]
Yup, makes sense - c27c8801a.
