### ISSUE TITLE
Brace expansion should skip braces with no commas

### ISSUE THREAD

**Issue by lilyball** [fish-shell/fish-shell#5869]
At some point we changed brace expansion to not trigger if the braces were empty, e.g. `foo{}` expands to `foo{}`. We should extend this to not trigger if the braces have no (unescaped) comma. This would match Bash/Zsh behavior.

In particular, I want this because of how much Git uses braces (without commas) as special syntax. For years now I've had a global variable `u` bound to the string `@{u}` so I can write e.g. `master$u` to refer to master's upstream, but that doesn't help with any of the other braced expressions, such as `@{1}`.

More generally, I can't think of any good reason to perform brace expansion when there are no (unescaped) commas, because all that does is delete the braces without adding anything.

**Comment by faho** [comment]
What about `{$var}`?

Lily Ballard <notifications@github.com> schrieb am Fr., 10. Mai 2019, 20:23:

**Comment by lilyball** [comment]
You mean if `$var` contains commas? That doesn't trigger brace expansion.

```fish
> set foo one,two,three
> echo bar{$foo}
barone,two,three
```

**Comment by faho** [comment]
>You mean if $var contains commas? That doesn't trigger brace expansion.

It does. That *is* brace expansion. If it wasn't, the braces would still be there in the output.

What I'm getting at is this:

It's possible that we can come up with a rule that allows `HEAD@{0}`, but it would have to treat `{$var}` as it is currently, or we've got a *big* backwards-incompatibility on our hands. And the rule would have to be simple enough to explain, or it might also not be worth it.

**Comment by lilyball** [comment]
Oh I see, I completely forgot that Fish uses `{$foo}` instead of `${foo}` in order to terminate the variable reference when it's immediately followed by identifier characters. That's frustrating.

We could say "if the braced text contains no commas or variable references, the braces are left intact". That's a fairly simple rule. It solves the `HEAD@{0}` case while still allowing `{$var}foo`.

**Comment by 0ion9** [comment]
The only case I can think of where this would be annoying is a 'fill this in later' type scenario

`for x in {foo}.png; stat -c %Y $x; end | sort -rn| head -1`

where you are expecting to fill in additional items after foo as you refine your idea.

`for x in {foo,bar,baz}.png; stat -c %Y $x; end|sort -rn | head -1`

special casing 'no commas' would mean the 'single literal value' cannot be written with the implication of being intended to become an array, as the expansion of `{foo}` is then not a subset of the expansion of `{foo,bar,baz}`

Personally it seems quite plausible that someone would work in this manner, but I don't personally work in this manner. Overall it seems like a reasonable change that will fix more than it breaks.

**Comment by faho** [comment]
>We could say "if the braced text contains no commas or variable references, the braces are left intact". 

In principle, that sounds alright. I've had a look at the code required, and that's no fun. The issue is that variables are expanded before braces, which means that, by the time brace expansion runs, they won't know that there's a variable in there. And crucially, we *need* `{$var}` to expand the braces even if $var has one element (so `set -l var 1; echo {$var}abc` results in `1abc`, not `{1}abc`).

So you think we'd swap the expansion order, which sounds alright in principle, but then you have the problem of `{$var}abc` expanding to `$varabc` and then to the value of "$varabc".

None of this is insurmountable, it's just annoying.

**Comment by lilyball** [comment]
You say variables are expanded before braces, and yet commas in the variable expansion aren't treated as significant for brace expansion, which means the commas must be extracted at parse time, yes? In that case, can we change the parse tree to represent "braces that should be expanded" separately from "braces that shouldn't be expanded" (which is to say, represent braces without commas or variables as just text)? This could be done as a quick pass over the AST after the initial parse (for every braced group, check the immediate children and see if there are any commas or variable references) but before any expansion runs.

**Comment by faho** [comment]
> I'll be quite surprised if we don't tokenize, parse into an AST of sorts, and then run all our processing on the AST.

Be surprised. The variable expansion runs the wonderfully named `unescape_string` on its input string, and the following stages then get the string with e.g the
 `BRACE_START` private use codepoint instead of `{`.

Which means something like you proposed is possible (only insert BRACE_START if it includes something to trigger brace expansion), it's just a tad uncleaner than you expected.

**Comment by lilyball** [comment]
Ugh. If we're not working on a tree how are we doing syntax coloring then? Does the syntax coloring routine e.g. keep a stack of the open punctuation characters so it can tell when they're unbalanced?

**Comment by faho** [comment]
That part is working on the tree, just the expansions aren't.

**Comment by lilyball** [comment]
So the syntax coloring routine builds a tree and then colors it, but the actual expansion routine just operates on the original string? That's honestly pretty strange. Is that due to syntax coloring operating basically completely independently of everything else?

In any case, even without a tree, this seems doable. Whatever pass converts braces into `BRACE_START` can just keep track of the unbalanced pairs and whether it's seen commas or variable references in the most recent pair, and when it hits the brace end, if it hasn't seen either, just go turn the `BRACE_START` back into a brace. The hardest part is just making sure commas/variables inside nested constructs are ignored.

**Comment by faho** [comment]
> Is that due to syntax coloring operating basically completely independently of everything else?

My guess? It's newer than the expansion code.

**Comment by floam** [comment]
There are a few bugs where syntax highlighting suggests something will be expanded differently than it actually will be, it seems like maybe long term it would be good if these were better unified in some way.

**Comment by floam** [comment]
(Like, `echo $}`, `$}` ought to be highlighted as an error, but it's not.)

**Comment by faho** [comment]
> Whatever pass converts braces into BRACE_START can just keep track of the unbalanced pairs and whether it's seen commas or variable references in the most recent pair

The most recent pair isn't enough - `echo {a,{b}}` and `echo {{a}, b}` both need the inner one unexpanded and the outer one expanded.

I have a WIP implementation of this, and the best I could do was to keep two vectors. We might be able to ditch the one that keeps the separators, but that's only possible *iff* we expand braces even if only the inner braces contain an expansion.

I.e. should `echo {{a,b}}` expand to `a b` or `{a} {b}`?

(Yes, this is quite hairy!)

**Comment by lilyball** [comment]
Right, I meant keep a vector of all unbalanced open brace locations.

In the `echo {{a,b}}` case I'd assume that it would expand to `{a} {b}`, because the outer pair doesn't contain a comma or a variable reference. Similarly `echo {(echo a,b)}` would expand to `{a,b}`. And of course `echo {a\,b}` would expand to `{a,b}`.

**Comment by lilyball** [comment]
It occurs to me that this change also means `echo {foo` is now legal syntax, as this should echo the string `{foo`. `echo {foo,` would still be illegal of course.

**Comment by faho** [comment]
>It occurs to me that this change also means echo {foo is now legal syntax

That'll have to wait until later - as it turns out, the tokenizer *checks* matching braces. See #2485.

**Comment by faho** [comment]
Done.

**Comment by lilyball** [comment]
I went ahead and filed #5880 specifically about `echo {foo`, as #2485 doesn't clearly cover this specific case.

**Comment by olets** [comment]
Any chance of getting a patch release for this? Not being able to use Git's `@{-N}` syntax (I often use it many times a workday) has me pausing my looking into switching to fish. I could build from source but just a couple days ago I was talking up both fish and `@{-N}` to a team… would be sweet if the change was readily available to all.

Recognize you might not want to set a precedent for users requesting patch releases, and haven't looked into whether this is tangled up with other changes. But on the other hand [sounds like we shouldn't hold our breath for 3.1](https://github.com/fish-shell/fish-shell/issues/5934#issuecomment-570934276) 😆

**Comment by faho** [comment]
Definitely not. This is *entirely* non-critical and the workaround is super
easy: Just quote or escape the braces.

That's not something that warrants a patch release. in fact if something
like this is in a patch release that's a massive red flag.

Henry Bley-Vroman <notifications@github.com> schrieb am Mo., 6. Jan. 2020,
15:49:

**Comment by olets** [comment]
For anyone else holding off on fish until this was released: it went out last month in [3.1](https://github.com/fish-shell/fish-shell/releases/tag/3.1.0)
