### ISSUE TITLE
Is there a way to run RAILS_ENV=production rake db:migrate in fish ？

### ISSUE THREAD

**Issue by dfang** [fish-shell/fish-shell#587]
i know set , but it's not convient .  i'd like to run commands like RAILS_ENV=production rake db:migrate  directly ......

thanks !

**Comment by kakra** [comment]
As with `make`, you can pass variables as arguments to rake, thus it should work with `rake RAILS_ENV=production db:migrate`.

**Comment by janwerkhoven** [comment]
Instead of adding `RAILS_ENV=production` to all your commands, you can also set it once and it will apply to all subsequent commands:

```
bin/rails db:environment:set RAILS_ENV=production
bin/rails db:drop;
bin/rails db:create;
bin/rails db:migrate;
bin/rails db:seed
```

```
bin/rails db:environment:set RAILS_ENV=development
bin/rails db:migrate
```
