### ISSUE TITLE
'cd someDirectory' hangs forever

### ISSUE THREAD

**Issue by zoetian** [fish-shell/fish-shell#5873]
My setup:

fish, version 3.0.2
Darwin tn608865 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64

Running w/o customized env w/ (sh -c 'env HOME=$(mktemp -d) fish' )

I can 'cd' into the next directory I need in this env, but cannot 'cd' normally when exit this environment.

This is a rather new issue for me after upgrading to fish shell version 3.0.x, all of a sudden I cannot cd into my local github directory, and sometimes cannot cd into some of subdirectories as well. I have to manually 'cmd+c' to kill it and navigate to my directory. 

Did anyone had this issue before or know how to solve this problem?
A thousand thanks!

**Comment by ridiculousfish** [comment]
Thanks for filing.

What does `functions cd` show?

When this happens, can you please use Activity Monitor to take a sample of fish and share it?

**Comment by zoetian** [comment]
Hello!

So `functions cd` returns 

```
# Defined in /usr/local/Cellar/fish/3.0.2/share/fish/functions/cd.fish @ line 4
function cd --description 'Change directory'
	set -l MAX_DIR_HIST 25

    if test (count $argv) -gt 1
        printf "%s\n" (_ "Too many args for cd command")
        return 1
    end

    # Skip history in subshells.
    if status --is-command-substitution
        builtin cd $argv
        return $status
    end

    # Avoid set completions.
    set -l previous $PWD

    if test "$argv" = "-"
        if test "$__fish_cd_direction" = "next"
            nextd
        else
            prevd
        end
        return $status
    end

    # allow explicit "cd ." if the mount-point became stale in the meantime
    if test "$argv" = "."
        cd "$PWD"
        return $status
    end

    builtin cd $argv
    set -l cd_status $status

    if test $cd_status -eq 0 -a "$PWD" != "$previous"
        set -q dirprev
        or set -l dirprev
        set -q dirprev[$MAX_DIR_HIST]
        and set -e dirprev[1]
        set -g -a dirprev $previous
        set -e dirnext
        set -g __fish_cd_direction prev
    end

    return $cd_status
end
```
As for the sample:

```
Sampling process 11086 for 3 seconds with 1 millisecond of run time between samples
Sampling completed, processing symbols...
Analysis of sampling fish (pid 11086) every 1 millisecond
Process:         fish [11086]
Path:            /usr/local/Cellar/fish/3.0.2/bin/fish
Load Address:    0x1084da000
Identifier:      fish
Version:         0
Code Type:       X86-64
Parent Process:  bash [11080]

Date/Time:       2019-05-13 10:36:27.120 -0400
Launch Time:     2019-05-13 01:12:59.462 -0400
OS Version:      Mac OS X 10.14.4 (18E226)
Report Version:  7
Analysis Tool:   /usr/bin/sample

Physical footprint:         5068K
Physical footprint (peak):  5080K
```
The entire output is really long, so I pasted the full output here:
https://gist.github.com/zoetian/c74a32100daf5929f5ba227c42f63195

Please let me know if you need more info. Thanks! =)

**Comment by faho** [comment]
@zoetian: One possibility is that you have an infinite loop somewhere. E.g. if you have a listener for the $PWD variable event that does `cd` again.

The output of `functions --handlers` would be nice, and if you have a line saying `PWD somefunction`, the output of `functions somefunction`.

A good thing for you to try would be to clean out your fish configuration - just move `~/.config/fish` away, and see if the issue persists.

**Comment by zoetian** [comment]
Hi @faho!

So `functions --handlers` returns

```
functions --handlers
Event signal
SIGTRAP fish_sigtrap_handler
SIGWINCH __fish_winch_handler

Event variable
PWD vcs.refresh
fish_color_cwd __fish_repaint
fish_color_cwd_root __fish_repaint_root
fish_key_bindings __fish_reload_key_bindings
fish_user_paths __fish_reconstruct_path

Event generic
fish_command_not_found __fish_command_not_found_handler
fish_exit __fish_disable_bracketed_paste
fish_preexec __fish_disable_bracketed_paste
fish_prompt __fish_enable_bracketed_paste
init_vcs init
```
and `functions vcs.refresh` returns
```
# Defined in /Users/ZoeTian/.local/share/omf/init.fish @ line 8
function vcs.refresh --on-variable PWD
	set -l path /Users/ZoeTian/.local/share/omf/pkg/vcs
	autoload -e $path/functions/{git,hg,svn,none}

    if set -l vcs (vcs.name)
      autoload $path/functions/$vcs
      return 0
    end

    autoload $path/functions/none
    return 1
end
```

**Comment by faho** [comment]
>and functions vcs.refresh returns

Aha, okay. That's an oh-my-fish thing. I suggest you try running `function vcs.refresh; end` and then try `cd` again. If that works, then the issue is with that function, so you need to either update oh-my-fish, or take it up with them.

Also note that OMF's vcs stuff isn't as performant as it could be, so in some directories it'll take a *long* time.

**Comment by zoetian** [comment]
Thank you so much, it works now!! @faho
