### ISSUE TITLE
fish_indent removes quotes from the word "in"

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#5876]
`fish_indent --version`  3.0.2-1121-ge7e5f3f1b

`fish_indent` formats input like

```fish
'a' 'in' 'out'
```

as

```fish
a in 'out'
```

Presumably because the "in" is parsed as the "in" in `for var in list`.

Obviously, it would be possible to enforce no unnecessary quotes, but if we decide to do so it should be done regardless of which particular *word* is used.

**Comment by faho** [comment]
Okay, as it turns out it's not just `in`. It's _all the keywords_. If you use `"begin"` as a regular old argument, it will be stripped of quotes.

That's because the node has an associated keyword, even if it isn't in position for that keyword. And its type is set to "string", so I have no idea how to distinguish those cases.

@ridiculousfish: Do you know how this is supposed to work?

**Comment by ridiculousfish** [comment]
Ok let's just have it print whatever text the user entered. Fixed as 8e640cdcc549bd6a14a7a04f5354d75356303992
