### ISSUE TITLE
Rethink some of fish_indent's style

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#5877]
I've just tried restyling OMF, and ignoring that they (mostly) use two-space indents (which I patched fish_indent to use as well, so I could see the other things it changed), there's a few style points that would be possible to adopt for us.

In particular:

- `switch` and `case` on the same level:

```fish
switch $command
case install
    # do install
case remove
    # do remove
end
```

- `and`/`or` indented one more:

```fish
test -d /some/directory
    and echo have
    or return 1
```

This is one thing that I'd like consensus on, so if we don't get any, I intend to close this in a month or so.

**Comment by zanchey** [comment]
I dislike the first and like the second, but I have no strong feelings and am aware of the bikeshed potential.

**Comment by ridiculousfish** [comment]
Agreed with zanchey's post above.

**Comment by faho** [comment]
Okay, I've hacked fish_indent to include the second. Some examples of it in action:

From abbr:

```fish
    if not set -q _flag_add[1]
            and not set -q _flag_rename[1]
            and not set -q _flag_erase[1]
            and not set -q _flag_list[1]
            and not set -q _flag_show[1]
            and not set -q _flag_query[1]
        if set -q argv[1]
            set _flag_add --add
        else
            set _flag_show --show
        end
    end
```

cd

```fish
    if test $cd_status -eq 0 -a "$PWD" != "$previous"
        set -q dirprev
            or set -l dirprev
        set -q dirprev[$MAX_DIR_HIST]
            and set -e dirprev[1]

        # If dirprev, dirnext, __fish_cd_direction
        # are set as universal variables, honour their scope.

        set -U -q dirprev
            and set -U -a dirprev $previous
            or set -g -a dirprev $previous

        set -U -q dirnext
            and set -U -e dirnext
            or set -e dirnext

        set -U -q __fish_cd_direction
            and set -U __fish_cd_direction prev
            or set -g __fish_cd_direction prev
    end
```

Note that my quick hack has issues with one situation from hostname.fish:

```fish
set -q USERDOMAIN
    and switch (uname)
    case 'CYGWIN_*'
```

Also I really need to check the codebase for `honour` - that "u" is gouing tou driuve me nuuts.

**Comment by floam** [comment]
The first `abbr` example of the implemented behavior looks really wrong to me.

**Comment by floam** [comment]
Maybe I'm missing something, but nothing about the new indentation here suggests to me that ` if set -q argv[1]` is code that can be hit when`_flag_query` is set... this seems worse than the existing behavior of `and` lines being indented to the same level as the previous command, and actually indenting less rather than deeper makes more sense to me:

```
    if not set -q _flag_add[1]
        and not set -q _flag_rename[1]
        and not set -q _flag_erase[1]
        and not set -q _flag_list[1]
        and not set -q _flag_show[1]
        and not set -q _flag_query[1]
            if set -q argv[1]
                set _flag_add --add
            else
                set _flag_show --show
            end
    end
```

**Comment by faho** [comment]
Another possibility:

- Remove unnecessary quotes (i.e. those that don't change anything)

E.g.

```fish
set var "foo" "bar" "baz" 'banana'
set var foo bar baz banana
```

or

```fish
test "$var" = "foo"
test "$var" = foo
```

**Comment by faho** [comment]
>Remove unnecessary quotes (i.e. those that don't change anything)

I basically [0] have that working. It changes a whopping 270 files with changes like

```fish
- echo $filename $symname $matches[3] ":" $vardecl
+ echo $filename $symname $matches[3] : $vardecl

- for a in 'clients' 'workspaces'
+ for a in clients workspaces

- convert -list color | awk '{ print $1"\t"$2" "$3} ' | sed '1,/----/d'
+ convert -list color | awk '{ print $1"\t"$2" "$3} ' | sed 1,/----/d
```

This saves on characters, so it makes it more likely to stay under that holy line-length-limit that fish_indent actually does not have (and TBH I think that bit is a bit overrated).

Also it makes it obvious that those strings aren't special in any way - I sometimes see fishscript looking like

```fish
set var "foo" "bar" "baz" "bonko" "bargagaga" "coocoo"
```

and there's a bit of a fundamental misunderstanding at the root of this - people believing, at least in part, that adding quotes makes it a "string". So removing the quotes points people towards the underlying model, which is that *everything is a string*, only one in which some things are expanded.

On the other hand, as soon as you *add* an expansion, you need to re-add the quotes, and if you remove one, fish_indent would remove them again. So that might be too annoying?


----
[0]: I'd love to actually use "the parser" for this, but so far the best I've figured is to use unescape_string, but that does much more than remove quotes, because it already performs some escapes. What I'd love is basically to run a thing, and then check if the resulting string has any expansion markers (VARIABLE_EXPAND and friends).

As an additional point, I would want to leave `?`, `^`, `%` and `{}` as special characters for this, at least for the time being, to allow cross-compatible code.

**Comment by faho** [comment]
Okay, no consensus on these proposals, closing!

We can obviously still change fish_indent's style in future, but there's no need to leave this open.
