### ISSUE TITLE
fish_user_paths not autocompleted

### ISSUE THREAD

**Issue by dancojocaru2000** [fish-shell/fish-shell#5884]
Simple issue.

In fish 3.0.2, typing `set -U f` doesn't autocomplete with fish_user_paths, even if this is the recommended way of adding stuff to path, which is a thing people have to do quite often, especially since all tutorials instruct towards editing `.bashrc` or `.zshrc`.

**Comment by floam** [comment]
Yeah, because it is not set by default. We indeed could extend the completions to describe unset-but-meaningful configuration variables.
