### ISSUE TITLE
Cannot index an array whose name is a variable

### ISSUE THREAD

**Issue by simonrouse9461** [fish-shell/fish-shell#5886]
Is there a way to index an array without a fixed name?
What I'm trying to do is something like this
```
set array 1 2 3
set name array
echo ${$name}[1]
```
It's supposed to return 1, but this is a syntax error.
Alternatively, I can do it in this way:
```
set temp $$name
echo $temp[1]
```
but it is really inconvenient to use an intermediate variable.

**Comment by ridiculousfish** [comment]
Seems like there's not, `$` binds more tightly than indexing.

**Comment by faho** [comment]
Here's one thing that works:

```fish
echo $$name[1][1]
```

which should be good enough - if you want to expand *all variables given by $name* you need to use `$$name[1..-1][1]`, but that shouldn't happen all that often.

The trick is that you need to give *both* stages indices (or all three if you use `$$$`).

**Comment by faho** [comment]
Okay, I've just added (more of) this to the docs, because giving multiple indices works and isn't too odious.

Changing either how the brackets bind or adding more syntax doesn't seem necessary, and is at worst backwards-incompatible.
