### ISSUE TITLE
How can i use CUDA_VISIBLE_DEVICES

### ISSUE THREAD

**Issue by luckysheep861** [fish-shell/fish-shell#5889]
fish, version 3.0.1
xterm
Linux cu10 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

How can i use CUDA_VISIBLE_DEVICES？

**Comment by faho** [comment]
It's an environment variable: `set -gx CUDA_VISIBLE_DEVICES somevalue`.

I have no idea what the value should be, but it's the same as everywhere else.
