### ISSUE TITLE
Move `brew` completions into Homebrew itself

### ISSUE THREAD

**Issue by lwolfsonkin** [fish-shell/fish-shell#5892]
In Homebrew/brew#6172, I proposed integrating completions from [this repo](https://github.com/fish-shell/fish-shell/blob/master/share/completions/brew.fish) as well as [an extensive external repo](https://github.com/laughedelic/brew-completions/blob/master/completions/brew.fish) into Homebrew itself in order to guarantee wider availability and quicker updates.

Pending your agreement, I would love to combine these together and get them into Homebrew itself. Thoughts?

**Comment by faho** [comment]
If Homebrew wants to take it and maintain it, that's brilliant.

>an extensive external repo

I'm not quite sure why that's not been merged in the first place or if there's actually anything left there, but sure. @laughedelic: Any reason you didn't propose a PR?

**Comment by laughedelic** [comment]
Hi! I've commented some time ago with the same suggestion: https://github.com/fish-shell/fish-shell/issues/4271#issuecomment-320505630. I haven't proposed a PR to the Homebrew repo because it was WIP and I wanted to polish it more, but in the end I didn't have time and forgot about it. I completely support the idea of moving all brew completions to Homebrew.

**Comment by zanchey** [comment]
Yes please - this has been on my todo list for a long time!

**Comment by lwolfsonkin** [comment]
Now that Homebrew/brew#6217 has been merged, fish completions are officially shipped with Homebrew, and installed into `vendor_completions.d`! :D 

Should a copy of `brew.fish` continue to live in this repo, or should any outstanding changes missing be migrated (if anyone finds any), and then `brew.fish` gets removed from here?

**Comment by faho** [comment]
>Should a copy of brew.fish continue to live in this repo

vendor_completions.d lives before our own, so keeping a copy is harmless. Let's keep one for a release or so, just in case (though AFAIK brew pushes upgrades aggressively?).

**Comment by lwolfsonkin** [comment]
Yeah, they are rather agressive. Functionally, the next time anyone uses `brew`, they will have the completions pushed into their path since `brew` updates itself when you do most of the brew operations.

I guess at minimum, could we somehow mark the brew completions here as "deprecated" and direct anyone who wishes to change them to instead go to [the main `brew` repo](https://github.com/Homebrew/brew/blob/master/completions/fish/brew.fish)?

**Comment by faho** [comment]
Yeah, I've removed them and left a note, like we're doing with the docker completions. If they're *that* aggressive, there's no need to keep them for another release, since by the time we make that they'll already be useless.
