### ISSUE TITLE
disown not working in an alias in fish config

### ISSUE THREAD

**Issue by carl-frederick** [fish-shell/fish-shell#5893]
fish version 2.7.1

uname -a
Linux birch 3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

echo $TERM
tmux-256color

sh -c 'env HOME=$(mktemp -d) fish'
set: Warning: $PATH entry "/tmp/tmp.95PGEy0Pjt/.config/yarn/global/node_modules/.bin" is not valid (No such file or directory)
Welcome to fish, the friendly interactive shell

To repro just create an alias in config.fish that has a disown after a backgrounded command.

**Comment by carl-frederick** [comment]
Then in a terminal, execute the alias to make the backgrounded task.  Then kill the terminal and the backgrounded task will also die.  If I create the alias right at the terminal and use it then the backgrounded task will not die upon quitting the terminal.

Thanks!

**Comment by carl-frederick** [comment]
I didn't close this, at least not intentionally.  Please re-open.

**Comment by faho** [comment]
@carl-frederick: Mind just posting the actual alias?

**Comment by zanchey** [comment]
I can't reproduce this with `alias foo="sleep 101 &; disown"`, although I notice that it disappears from the output of `ps` because it doesn't have a controlling terminal (need `ps x`) - perhaps that caused some confusion?

**Comment by carl-frederick** [comment]
In trying to make a case for you to test we found we couldn’t repro the issue any more.  I guess we can close this for now, thanks.

**Comment by faho** [comment]
Sure! If you ever do find a reproducer, please do get back to us!
