### ISSUE TITLE
abort in compare_completions_by_tilde

### ISSUE THREAD

**Issue by PerBothner** [fish-shell/fish-shell#5895]
This is a crash in git master, introduced by:

    commit 5bf21f29283feb363ab23be2e6d101ca7832ae33 (HEAD)
    Author: Fabian Homborg <FHomborg@gmail.com>
    Date:   Mon May 6 17:07:29 2019 +0200

        Penalize files ending in ~ in suggestions
    
        Fixes #985.

Reproduce it by typing `echo foo` followed by Alt-Enter, followed by `pwd`, followed by Enter.

This crashes in `compare_completions_by_tilde` because one of the arguments is the empty string, which then causes `back()` to fail.

A fix is to either make `compare_completions_by_tilde` more robust (so it can handle an empty string), or make sure the array passed to `stable_sort` does not contain an empty string.  Or something else - the value of `search_string` is `L"echo foo\npwd"`, which seems dubious. I don't know enough about the logic to know what is the correct fix.

**Comment by faho** [comment]
>Reproduce it by typing echo foo followed by Alt-Enter, followed by pwd, followed by Enter.

Doesn't reproduce for me - I'm pretty sure you're getting a *suggestion* that triggers the crash, but the general idea makes sense.

**Comment by PerBothner** [comment]
Thanks.  That fixes it.
