### ISSUE TITLE
env: shell: No such file or directory

### ISSUE THREAD

**Issue by jby** [fish-shell/fish-shell#5898]
fish --version
fish, version 3.0.2

I have 3 Macs, all running the same version of macOS (10.14.5) and all setup the same way.
On 2 I have no problem, but on my main workstation in the office I get this every time I start a new fish from the command line or if I ssh into it:

```
fish
Darwin HOSTNAME 18.6.0 x86_64
18:39  up 13 days,  4:18, 9 users, load averages: 1.56 1.59 1.49
env: shell: No such file or directory
env: shell: No such file or directory
```
I have the exact same fish and omf config on all three.

What could be causing this? How do I troubleshoot it?

And, yes, of course the test without third-part customisations does NOT show this...

**Comment by jby** [comment]
AND if I copy all customisations from my regular $HOME to the TMPDIR created it also works fine, it's just if I have everything in my regular $HOME I experience this...

**Comment by faho** [comment]
There is something here that runs `env something shell`.

Run `grep 'env.* shell` on your config to find out.

**Comment by jby** [comment]
Yeah, I can't find anything - can I somehow debug the startup sequence to try to find it?

**Comment by jby** [comment]
Ok, never mind, I've figured out it's in omf, I'll go there instead.

**Comment by faho** [comment]
There is `fish --debug LEVEL`, but that's more for fish internals.

Personally, I'd probably add an `env` function that prints a stack-trace:

```fish
function env
    command env $argv
    or status stack-trace >&2
end
```
