### ISSUE TITLE
Question: are there syntax highlighting bindings for vim when editing .fish files?

### ISSUE THREAD

**Issue by tommyjcarpenter** [fish-shell/fish-shell#5899]
Note, I'm not asking about bindings that make fish "behave like vim", I'm asking whether there is a vim plugin such that when editing .fish files, for example `config.fish`, vim knows how to highlight syntax and or lint it? Right now my vim has 0 highlighting for fish.

**Comment by tommyjcarpenter** [comment]
The only one I found is 6 years old: https://github.com/dag/vim-fish

**Comment by faho** [comment]
That is the only one I know of.

**Comment by kmarius** [comment]
I created a fork a while ago, mainly to include changes to the highlighting and indentation. You can find it here: https://github.com/kmarius/vim-fish

The fork with the most recent updates is this one: https://github.com/Stautob/vim-fish. No idea how they compare.

**Comment by faho** [comment]
Question appears to have been answered, closing.
