### ISSUE TITLE
New debugging produces broken output on glibc

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#5900]
Unfortunately, glibc does not allow mixing wide and narrow IO, so the current FLOG implementation produces broken output on my system.

The fix is using wide IO everywhere, including wide literals. The main problem is dealing with the char overloads.

See #3704.

A random sampling:

```
proc-job-runStart job 4, gid -2 (set -l fish_prompt_pwd_dir_length $argv[1]), COMPLETED, NON-INTERACTIVEproc-job-runStart job 4, gid -2 (set -l tmp), COMPLETED, NON-INTERACTIVEproc-job-runStart job 4, gid -2 (set -l gitdir), COMPLETED, NON-INTERACTIVEproc-job-runStart job 5, gid 4974 (command git rev-parse --show-toplevel 2>/dev/null), UNCOMPLETED, NON-INTERACTIVEproc-job-runStart job 4, gid -2 (set gitdir (command git rev-parse --show-toplevel 2>/dev/null)), COMPLETED, NON-INTERACTIVEproc-job-runStart job 4, gid -2 (set realhome ~), COMPLETED, NON-INTERACTIVEproc-job-runStart job 5, gid -2 (string replace -r '^'"$realhome"'($|/)' '~$1' $PWD), COMPLETED, NON-INTERACTIVEproc-job-runStart job 4, gid -2 (set tmp (string replace -r '^'"$realhome"'($|/)' '~$1' $PWD)), COMPLETED, NON-INTERACTIVEproc-job-runStart job 4, gid -2 (test $fish_prompt_pwd_dir_length = 0), COMPLETED, NON-INTERACTIVEproc-job-runStart job 4, gid -2 (echo -s $gitdir $tmp), COMPLETED, NON-INTERACTIVEproc-job-runStart job 3, gid -2 (prompt_pwd $i), COMPLETED, NON-INTERACTIVEproc-job-runStart job 2, gid -2 (set pwd (prompt_pwd $i)), COMPLETED, NON-INTERACTIVEproc-job-runStart job 3, gid -2 (string length -- $prompt_host_nocolor$pwd$last_status$delim' '), COMPLETED, NON-INTERACTIVEproc-job-runStart job 2, gid -2 (set -l len (string length -- $prompt_host_nocolor$pwd$last_status$delim' ')), COMPLETED, NON-INTERACTIVEproc-job-runStart job 2, gid -2 (test $len -lt $COLUMNS), COMPLETED, NON-INTERACTIVEproc-job-
```

**Comment by faho** [comment]
Ah, okay, it appears that most of the FLOGs that use narrow strings replaced debugs that did the same, so I'd imagine that they're no more broken than before. One that didn't was

```c++
FLOG(exec_job_exec, "Executed job", j->job_id, "from command", j->command_wcstr(), "with pgrp",
         j->pgid);
```

from exec.cpp, which did trigger the issue.

**Comment by zanchey** [comment]
Awesome - I had noticed this but not had a chance to dig in

**Comment by faho** [comment]
One thing I'm not sure about: `__FUNCTION__`. Apparently that's a special thing, so just using it as a wchar_t* doesn't work.

Can we call

```c++
FLOGF(category, L"something in function %s", __FUNCTION__)
```

?

**Comment by faho** [comment]
Yup, turns out we can.

So all the FLOGs that use narrow strings should just be FLOGF instead.

I'm committing that and removing the narrow overloads, because they don't *work* on glibc.

**Comment by faho** [comment]
Okay, so we now never call FLOG with a narrow _literal_. The narrow functions are still called as part of some calls, including where we use PACKAGE_BUGREPORT, but I haven't seen an issue with that.

(Also can we just all agree that wchars are annoying?)

**Comment by ridiculousfish** [comment]
Nice fix!

Yep wchars are annoying and it's a long-term todo to remove them.

**Comment by ridiculousfish** [comment]
I decided to extend this by using `fwprintf()` in the narrow printing functions, so it's safe to mix narrow and wide string literals in FLOG. b20bdcebfa7c9ffaec6ba36cdb57482228e0fbd9
