### ISSUE TITLE
pipe array variable into commands

### ISSUE THREAD

**Issue by dwaite** [fish-shell/fish-shell#5902]
```
 ~> fish --version; echo; uname -a; echo; echo $TERM
fish, version 3.0.2

Darwin Samus-2.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

xterm-256color
```

Question: I can set the output of a command to a variable via

```
set foo (bar)
```

which will set each line of bar's output to $foo array entries.

Is there a clever / quick reverse? So far I've only found `string join`:

```
string join \n $foo | awk "{ print $2 }"
```

**Comment by faho** [comment]
Either that or `printf %s\n $foo | thing`.

**Comment by faho** [comment]
Question appears to have been answered, closing.
