### ISSUE TITLE
Reuse auto-completions for defined function

### ISSUE THREAD

**Issue by romariolopezc** [fish-shell/fish-shell#5903]
fish, version 3.0.2
Darwin arcus-mbp.lan 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
xterm-256color

Hello everyone.

I defined some functions (aliases) for git, ie. functions.fish

```fish
function gco
  git checkout $argv
end
```

How do I reuse the auto-completions of the git checkout command?

gco `tab` and shows all the options

**Comment by faho** [comment]
Use `function gco --wraps "git checkout"`.
