### ISSUE TITLE
Universal variables re-narrow path again and again and again

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#5905]
In something like

```fish
for i in (seq 1000)
    command true
end
```

about 20% of the total time is taken up in wcs2string, much of that coming from universal_barrier() (which is triggered here because it's an external command - this does not happen with `builtin true`).

And that does wcs2string because it is narrowing the uvar path, again and again and again, even though it stays the same 99.999% of the time.

I propose we cache the narrow versions of these kinds of paths - we still need the wide version for output. Unfortunately this means changing from our nice and friendly "waccess" et al wrappers, because they do the narrowing for you.

**Comment by zanchey** [comment]
Should it be able to change while running at all? Does that make any sense?

**Comment by faho** [comment]
>Should it be able to change while running at all? Does that make any sense?

Maaaayyybbee? Possibly if $XDG_CONFIG_HOME changes.

**Comment by faho** [comment]
Okay, no, we don't seem to change the uvar path currently.

It asks `path_get_config`, which in turn just returns a static variable:

```c++
static const base_directory_t &get_config_directory() {
    static base_directory_t s_dir = make_base_directory(L"XDG_CONFIG_HOME", L"/.config/fish");
    return s_dir;
}
```
