### ISSUE TITLE
The `-f` switch of `complete` causes unexpected side effect

### ISSUE THREAD

**Issue by thomsj** [fish-shell/fish-shell#5907]
Version: 3.0.2

Tested with:
- Ubuntu 18.04.2 and GNOME Terminal (xterm-256color)
- [rootnroll](https://rootnroll.com/d/fish-shell/) (xterm)

Behaviour occurs without third-party customisations.
I do not know if the behaviour in fish 2.7 is the same.

The `-f`/`--no-files` option of the [`complete`](https://fishshell.com/docs/current/commands.html#complete) command supresses filename completions not only for the argument the completion was written for, but also for the command of the completion.

[![asciicast](https://asciinema.org/a/BvnBzsRbO2kBXFKdoVR6BfisF.svg)](https://asciinema.org/a/BvnBzsRbO2kBXFKdoVR6BfisF?t=40&loop=1&rows=20&speed=2)

**Comment by faho** [comment]
This is as expected. Your offending call is:

```fish
complete -c hello -a foo -f
```

That has no condition, no option, so it's used "always". It says to offer "foo" as argument, and to not complete files.

If you do add an option without "-f", then it'll offer files, and if it's possible to sometimes have files as normal arguments you'll have to add a condition for this one.

**Comment by faho** [comment]
Note that we have issues open regarding file/no-file being a bit confusing, e.g. #5646.

But this isn't actually a case where I'd argue it's too confusing. Nevertheless, what I'm gonna do is add a "--force-files" flag to `complete`, that forces file completion if a condition is true even if it's been inhibited elsewhere.

**Comment by thomsj** [comment]
Thanks @faho. I, mistakenly, thought that:

```fish
complete -c hello -a foo -f
```

was equivalent to:

```fish
complete -c hello -a foo
complete -c hello -n "__fish_seen_subcommand_from foo" -f
```
