### ISSUE TITLE
Rename --debug-level to --debug

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#5910]
From #5879 

> The long option for -d is --debug-level, which is obviously not right for these new categories; perhaps we change it to just --debug? I presume the level arguments will stop working completely once FLOG is used everywhere.

We should rename `--debug-level` to just `--debug`.

**Comment by Yogendra0Sharma** [comment]
@ridiculousfish I am working on this issue.

**Comment by zanchey** [comment]
This is not quite done as the documentation still needs to be updated.

**Comment by norio-nomura** [comment]
`share/completions/fish.fish` still contains `--debug-level`:
https://github.com/fish-shell/fish-shell/blob/6d66c47f70ccf66e5604a65b5be3df3a8ef0474f/share/completions/fish.fish#L9
