### ISSUE TITLE
tab suggestion both uppercase and lower case - case sensitive

### ISSUE THREAD

**Issue by huyhoang8398** [fish-shell/fish-shell#5911]
fish, version 3.0.2
In zsh, if we use cd n<tab>, they will suggest all the directory starting with n ( both upper case and lower case ).  Can we have the same thing in fish?

**Comment by ridiculousfish** [comment]
fish will show completions for case-insensitive matches, if there are no case-sensitive matches. In my tests zsh always matches case when tab completing (though no doubt there's some config here).

I think completing case-insensitive matches all the time would be too noisy so I will close this. Thanks for filing.
