### ISSUE TITLE
Did my history/autocomplete get "checkpointed"?

### ISSUE THREAD

**Issue by Gurpartap** [fish-shell/fish-shell#5914]
Every so often (maybe a week or two), fish appears to be creating a sort of "checkpoint" effect for my history.

Even though I see my history going back to years in `~/.local/share/fish/fish_history`, I'm not able to "up" to any previously used commands. Autocomplete doesn't work either.

However, it works as expected for any commands subsequent to this "checkpoint".

As indicated in some other [related issues](https://github.com/fish-shell/fish-shell/issues/2335), I verified that my fish files in ~/.local/ and ~/.config/ are owned by my user. If anything, I did use sudo before restarting (after which I had this issue).

```sh
> fish --version
fish, version 3.0.2

> uname -a
Darwin Gurpartaps-MacBook-Pro.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

> echo $TERM
xterm-256color
```

**Comment by Gurpartap** [comment]
And just like that, an hour and many shells later, I noticed that autocomplete/history began working as expected again (including the commands prior to the above mentioned "checkpoint").

This has happened before. I don't have any more clues to help any better. Let me know if there's something I can do for when it occurs again.

**Comment by faho** [comment]
>Even though I see my history going back to years in ~/.local/share/fish/fish_history, I'm not able to "up" to any previously used commands. Autocomplete doesn't work either.

The obvious question there is if that is the history file that fish should be using.

Do you ever set $XDG_DATA_HOME or $fish_history? Do you use a network or overlay mount or something like that?

**Comment by Gurpartap** [comment]
> The obvious question there is if that is the history file that fish should be using.
I haven’t reconfigured fish to use any other file for my history. I see my shell commands being appended to that file. 

> Do you ever set $XDG_DATA_HOME or $fish_history? Do you use a network or overlay mount or something like that?
I don’t think so.

**Comment by faho** [comment]
Closing this as a presumptive fluke.
