### ISSUE TITLE
Lines dis- and reappearing

### ISSUE THREAD

**Issue by heyarne** [fish-shell/fish-shell#5915]
```
$ fish --version
fish, version 3.0.2
$ uname -a
Linux plume 5.1.5-arch1-2-ARCH #1 SMP PREEMPT Mon May 27 03:37:39 UTC 2019 x86_64 GNU/Linux
$ echo $TERM
xterm-256color
```

I have trouble with disappearing lines / garbled output; the whole issue is described here: https://github.com/jwilm/alacritty/issues/2491

> I am in a git repo, current `HEAD` is `f33dc95`. The output of `git log` looks like this (notice the beginning is cut off):
> 
> ![2019-05-30-102425_670x462_scrot](https://user-images.githubusercontent.com/525780/58619583-74210500-82c5-11e9-8ac3-dc94b04bbe4d.png)
> 
> This is what it looks like when I press the down arrow once (scrolling as expected given the previous state):
> 
> ![2019-05-30-102601_670x462_scrot](https://user-images.githubusercontent.com/525780/58619596-797e4f80-82c5-11e9-9d23-79a95bcfceba.png)
> 
> And this is what it looks like when I press the up arrow again (notice the glitch in the second line):
> 
> ![2019-05-30-102613_670x462_scrot](https://user-images.githubusercontent.com/525780/58619604-7d11d680-82c5-11e9-9154-56b5a62ca9dc.png)
> 
> I am experiencing several glitches, especially with commands that have lots of output, that I think all have something to do with this. I would appreciate any help with debugging it.

Even though in the other issue I claimed this was happening independent of my chosen shell that turned out to be not true; when changing the shell via `chsh` and restarting the terminal session I could not reproduce it with bash 5.0.1 or zsh 5.7.1. I noticed also that it happened across terminals. Trying it with `sh -c 'env HOME=$(mktemp -d) fish'` showed the same behavior. I can reproduce it in another git repository, where it also happens as soon as the first line is forced to wrap.

**Comment by faho** [comment]
Works for me and it's kind of unlikely that fish would have any effect here.

The only thing I can think of are terminal  modes, but the output of `stty -a` are the same for me on bash (where I haven't modified them) and fish (which sets them to the same value always), with the exception of flow control, which is unrelated.

Do you have a git function or any settings for your pager (less, configured via $LESS) that's different across bash and fish?

**Comment by faho** [comment]
Or $PAGER itself, or a different $HOME?

Comparing the output of `env` across shells would be useful, as would checking it inside bash-started-in-fish and fish-started-in-bash.

**Comment by heyarne** [comment]
This was indeed caused by having set `$LESS` to `-r` (instead of `-R`, which is what I wanted). Thanks!
