### ISSUE TITLE
Feature Request: Extend `function`'s "-a" option to list

### ISSUE THREAD

**Issue by antoine-gallix** [fish-shell/fish-shell#5917]
Feature Request: Extend `function`'s `-a` option to list

Right now the behavior of function -a is the following:

```shell
function compress -a output inputs
    echo input files: $inputs
    echo output file: $output
end
```

```shell
❯ compress output.zip file.ext
input files: file.ext
output file: output.zip

❯ compress output.zip a_file.ext another_file.ext
input files: a_file.ext
output file: output.zip
```

Only the first input file is captured by the `inputs` variable.

It doesn't seems to exist a way to capture a list of argument instead of only one using the `-a` option or similar. The desired behavior would be:

```
❯ compress output.zip a_file.ext another_file.ext
input files: a_file.ext another_file.ext
output file: output.zip
```

It's probably not desirable to break the current behavior, so maybe a new option could be used for a list argument, like:

```
function compress -a output -A inputs
```

**Comment by Darkshadow2** [comment]
If every argument after your first is to be used like that, then it's easier to just use `argv`. You can remove the first argument (`set -e argv[1]`), and then just use it.

**Comment by antoine-gallix** [comment]
Yes that's what I'm doing right now. It's not that I can't do it, it precisely a feature request to make it doable via the `-a` option, or something similar.

The `-a` option is also a convenience to assign variables, and one can manually assign them to names in the first lines of the function, yet the option is there to reduce the boilerplate. So extending this option seems to make sense to me.

**Comment by floam** [comment]
Don't think we're going to do this. Maybe we will revisit `-a` if we ever get into docopt or something. As it is now, argparse is your friend.
