### ISSUE TITLE
Clarify docs on global/universal vars and exports

### ISSUE THREAD

**Issue by pikeas** [fish-shell/fish-shell#5920]
OS X 10.14.5 // fish 3.0.2

Relevant links:

- https://fishshell.com/docs/current/faq.html#faq-exported-uvar
- https://fishshell.com/docs/current/index.html#variables

I have multiple shell variables which need to be set so that my CLI tools will work. For example: `AWS_*`, `FZF_*`, `GOPATH`, and `PYTHONDONTWRITEBYTECODE`. These variables can be set for long term use in at least four ways:

- `set -g VAR # in config.fish`
- `set -gx VAR # in config.fish`
- `set -U VAR # at prompt, saved to fish_variables`
- `set -Ux VAR # at prompt, saved to fish_variables`

It's not clear *in the docs* when each of these is the appropriate choice. I think that both shell veterans migrating from bash/zsh and newer users would benefit from explicit guidance on when to use each kind of variable declaration in their configs.

Specifically, it would be great if either the FAQ or the variable section of the docs specifically answered:

- "When should I export a variable instead of just setting it with -g/-U?"
- "When should I use a universal variable instead of a global variable?"

**Comment by faho** [comment]
> It's not clear when each of these is the appropriate choice.

If external commands need to read these, which they do for all of your examples, you **need** to export them (since that's what exporting does).

Global vs universal for these is entirely a matter of taste - do you prefer to see them right there in your config.fish, or to set them once and forget about them?

**Comment by pikeas** [comment]
> > It's not clear when each of these is the appropriate choice.
> 
> If external commands need to read these, which they do for all of your examples, you **need** to export them (since that's what exporting does). So that leaves just `-gx` and `-Ux`.

I've edited my post to clarify that it's not clear *in the docs*.

> 
> Global vs universal for these is entirely a matter of taste - do you prefer to see them right there in your config.fish, or to set them once and forget about them?

When there are multiple ways to accomplish something, it's a better user experience when there's clear guidance on choosing between the options.

**Comment by pikeas** [comment]
Great docs update on how variable exports work! It looks like you decided that global vs universal doesn't need to be clarified?
