### ISSUE TITLE
recent checkin breaks shell integration

### ISSUE THREAD

**Issue by PerBothner** [fish-shell/fish-shell#5923]
The checkin ff5524944778965e935de4b9b1bf64da535118e1 breaks "shell integration" as implemented in ITerm2 and (my working copy of) DomTerm.  The problem appears to be that the shell integration attaches a watch function (`-v`) on the `$_` variable to detect the end of command input and start of command output, and that watch function is no longer being called.

To test this, source the following file (after `gunzip`)::

[shell-integration.fish.gz](https://github.com/fish-shell/fish-shell/files/3257965/shell-integration.fish.gz)

Then type `pwd` and exit.

The expected result (as produced by earlier versions): 

    _underscore_change pstarted: 0
    fish_mode_prompt
    fish_prompt
    _underscore_change pstarted: 1
    _underscore_change pstarted: 1
    fish_mode_prompt
    fish_prompt
    _fishprompt_exit

The actual result:

    fish_mode_prompt
    fish_prompt
    fish_mode_prompt
    fish_prompt
    _fishprompt_exit

Is there a better way to "hook" after command input but before command execution?  Zsh has precmd/preexec, while bash has PS0 (since 4.4) and DEBUG traps.

**Comment by faho** [comment]
>Is there a better way to "hook" after command input but before command execution? Zsh has precmd/preexec, while bash has PS0 (since 4.4) and DEBUG traps.

The fish_preexec event?

```fish
function something --on-event fish_preexec
```

**Comment by faho** [comment]
Note that `$_` is deprecated since 3.0.0.

The fish_preexec and fish_postexec events exist since 2.2.0, which is the absolute minimum relevant fish version (it's in still supported LTS distributions).

**Comment by PerBothner** [comment]
_"The fish_preexec event?"_

Thanks - I'll try that.

Note that https://iterm2.com/shell_integration/fish uses the "watch-underscore" trick.  Perhaps it was written before 2.2.0. (The bash version does not use `$PS0` so that should perhaps also be updated).

**Comment by faho** [comment]
Ah, okay, going by the commit message this is on purpose:

>The last one means that we no longer support event handlers for implicit
sets like (example) argv. Instead only the `set` builtin (and also `cd`)
post variable-change events.

And since the events exist and $_ is deprecated anyway, I'm closing this unless that somehow doesn't work for you.

>Perhaps it was written before 2.2.0.

AFAIK it was.

**Comment by PerBothner** [comment]
Feel free to close the issue for my sake (assuming fish_preexec works), though perhaps you might want to notify the iTerm2 maintainer(s).

**Comment by faho** [comment]
Yeah, that's probably a good idea.

@gnachman: You'll want to update the fish integration to use `--on-event fish_preexec` instead of watching the `$_` variable. I'm not sure what the "precmd" function is supposed to do or when exactly it's supposed to fire. It possibly needs the "fish_prompt" event, which is fired before the prompt is displayed?

**Comment by zanchey** [comment]
I have a suspicious feeling there is going to be more fallout from this change.

**Comment by gnachman** [comment]
This commit modernizes the fish shell integration script:
https://github.com/gnachman/iterm2-website/commit/f8253d5de1554f6985a6e5fadff7095a3edad97b

I'm betting that fish_preexec is old enough that I can use it safely (was added in commit 646d9ab431f102588dfbc90e1c54ff879d164a8a, but I'm not sure what the oldest version of fish is that offers i). The original shell integration code is from 2014, and seems to have predated its existence.

**Comment by zanchey** [comment]
`fish_preexec` was added for 2.2.0.
