### ISSUE TITLE
still abort in compare_completions_by_tilde 

### ISSUE THREAD

**Issue by PerBothner** [fish-shell/fish-shell#5929]
Followup to issue #5895 - I'd re-open it, but I didn't see how to.

This still aborts when I do a `touch /tmp/x`. Gdb shows:

    #4  0x000000000066c6f0 in compare_completions_by_tilde (a=..., b=...)
        at /home/bothner/Software/fish-shell/src/complete.cpp:247
    247	           (a.completion.back() == L'~') < (b.completion.back() == L'~');
    (gdb) p a
    $1 = (const completion_t &) @0x7f6318009020: {completion = L"", 
      description = L"", match = {type = fuzzy_match_exact, 
        match_distance_first = 0, match_distance_second = 0}, flags = 128}
    (gdb) p b
    $2 = (const completion_t &) @0x7f63180093c0: {completion = L"xx", 
      description = L"", match = {type = fuzzy_match_prefix, 
        match_distance_first = 2, match_distance_second = 0}, flags = 0}

Maybe:

    return b.completion.empty() ||
        (! a.completion.empty() &&
            (a.completion.back() == L'~') < (b.completion.back() == L'~'));

**Comment by mqudsi** [comment]
@faho  does

https://github.com/fish-shell/fish-shell/commit/9ae3b345c881157d15d24a493d18c421dbde70fe#diff-a393fef0d14c228698352a4b1a83f6deR246

suffer from the operator precedence issue? Do the individual comparisons need to be enclosed in parentheses?

**Comment by mqudsi** [comment]
@faho I think it's the same comparison operator precedence issue I previously patched for that same line: https://github.com/fish-shell/fish-shell/commit/097d6c3c5b910e03c934fd7db6ed384ac771912a

Which means 

```cpp
(a.completion.empty() < b.completion.empty()) || (a.completion.back() == L'~') < (b.completion.back() == L'~')
```

needs to become

```cpp
(a.completion.empty() < b.completion.empty()) || ((a.completion.back() == L'~') < (b.completion.back() == L'~'))

**Comment by PerBothner** [comment]
I'm not a C++ expert (any more) but I believe that fails if  `a.completion.empty()`. In that case the part before `||` is `true < ANY` which is `false`.  Hence we get `false || RAISE_EXCEPTION`. Oops.

**Comment by mqudsi** [comment]
Yeah, that `<` should also be `^` but I'm on my phone

**Comment by faho** [comment]
Blech... screw C++'s operator precedence, I'm just gonna add some `if`s before.
