### ISSUE TITLE
Possible fish_opt -r flag bug and documentation ambiguity

### ISSUE THREAD

**Issue by AnthonyMonterrosa** [fish-shell/fish-shell#5931]
Using fish version `3.0.2`.

OS: `Linux 4.19.45-1-MANJARO`.

Two things I'd like to discuss:
1. The documentation on [fish_opt](http://fishshell.com/docs/current/commands.html#fish_opt).
2. Possible issue with the `-r` flag not making a difference when used.

For 1, I see that, for the `-r` flag, the long versions `--required` and `--required-val` are mentioned in the documentation. Not sure which is correct. In the examples and EBNF of the command `--required-val` is used, but `--required` is used in the list of flags under `Description`.

Examples (bold is mine) below.

EBNF:
> fish_opt ( -s X | --short=X ) [ -l LONG | --long=LONG ] [ --long-only ] \ 
>     [ -o | --optional-val ] [ -r | **--required-val** ] [ --multiple-vals ]

Example:
> set -l options (fish_opt -s h -l help)
> set options $options (fish_opt -s m -l max **--required-val**)
> argparse $options -- $argv

Description:
> -r or **--required** means the option being defined requires a value. If the option is seen more than once when parsing arguments only the last value seen is saved. This means the resulting flag variable created by argparse will have exactly one element.

Maybe I'm misunderstanding, but this is confusing.

For 2, I have a file where I make this call to `fish_opt`:
```
  set --local options $options (fish_opt \
    --short d                            \
    --long  delimiter                    \
    --long-only                          \
    --required                           \ # or --required-val, or -r
    )
```
but not giving the argument `--delimiter` when executing the script does not result in an error. Am I doing something wrong?

If you all would like additional information on 2, I'd gladly share the whole program, the line I used when calling the command in the terminal, and the output.

**Comment by faho** [comment]
>but not giving the argument --delimiter when executing the script does not result in an error. Am I doing something wrong?

Yes. "required-val" here means that *the argument to the option*, aka "the value" is required.

Meaning if you pass "--delimiter", you also have to give it a delimiter, like `--delimiter=b` or `--delimiter b`.

Meaning `foo` is okay, and `foo --delimiter bar` is okay, but `foo --delimiter` is not.

"--required" is an error in the docs, indeed.

**Comment by AnthonyMonterrosa** [comment]
Ah, I see. Is there a way with to have it so:

`foo` is an error, `foo --delimiter` is an error, but `foo --delimiter bar` is not?

**Comment by faho** [comment]
>foo is an error, foo --delimiter is an error, but foo --delimiter bar is not?

Check if `$_flag_delimiter` has been set after you run `argparse`:

```fish
argparse $options -- $argv
if not set -q _flag_delimiter
    echo "No delimiter" >&2
    return 1
end
```

**Comment by AnthonyMonterrosa** [comment]
Right, that works too. Thanks!
