### ISSUE TITLE
Cannot add complex pipeline as a job

### ISSUE THREAD

**Issue by buckle2000** [fish-shell/fish-shell#5932]
> fish, version 2.7.1

Suppose I want to launch the following pipeline as a single job. How can I achieve that in fish?

![graph](https://user-images.githubusercontent.com/10850402/59194966-3b611580-8b7a-11e9-8d5f-a8642d72dd6c.png)

It would be equivalent to

```fish
mkfifo /tmp/b /tmp/d
B < /tmp/b | C & # however, stdout and stderr of C and B is muted
D < /tmp/d | E > file & # same for D and E
A | tee /tmp/b > /tmp/d
```

However, I would like them to be a single job, which can be interrupted by ^C.

**Comment by faho** [comment]
Sorry, this isn't in our plans. Pipelines as complex as these don't really tend to happen all that often, so using fifos is alright.
