### ISSUE TITLE
Support `>file` to create (or empty) a file

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#5933]
This may be considered a fairly controversial suggestion by some of the fish purists, but having been using fish exclusively as my shell for several years, this is one shortcut I _still_ miss from bash every now and again, when I quickly want to either 1) quickly create a file or 2) empty an existing file.

The shortest equivalent to `>file` that works in fish is `:>file`, but this is less intuitive to me and it seems to me that if the latter works, the former should also work.

I don't feel too strongly about this, of course, it's more of a nice-to-have than anything, but still curious to hear others' opinions!

**Comment by faho** [comment]
That's what `touch file` is for. Saving 5 chars isn't worth it here.
