### ISSUE TITLE
Running brew-installed ctags resulting in error in fish

### ISSUE THREAD

**Issue by duanwei913** [fish-shell/fish-shell#5935]
When I'm running `ctags --version` in fish. It gave me the following error msg:

fish: Unknown command `brew
- (line 1):
function ctags --wraps '`brew --prefix`/bin/ctags' --description 'alias ctags `brew --prefix`/bin/ctags';  `brew --prefix`/bin/ctags $argv; end
                                                                                                           ^
in function 'ctags'
	called on standard input
	with parameter list '--version'

I'm using fish 3.0.2 and running on Macbook Mojave, my ctags version is 
Exuberant Ctags 5.8, Copyright (C) 1996-2009 Darren Hiebert
  Compiled: Aug 19 2018, 23:32:48
  Addresses: <dhiebert@users.sourceforge.net>, http://ctags.sourceforge.net
  Optional compiled features: +wildcards, +regex

which I can get by running `ctags --version` in bash

**Comment by faho** [comment]
Fish does not support the `\`command\`` syntax. Use `(command)`.

Though it doesn't support running those as commands, so you'll have to do

```fish
function ctags
    set -l pref (brew --prefix)
    $pref/bin/ctags
end
```

or simply add `(brew --prefix)/bin` to your $PATH.

**Comment by duanwei913** [comment]
@faho thanks man. Saved my day. ^^
