### ISSUE TITLE
Make it possible to turn off deduplication of history

### ISSUE THREAD

**Issue by voider1** [fish-shell/fish-shell#5938]
I'd like there to be a configuration option to optionally turn off history deduplication. You might ask why I would want such a thing, but the reason is that I have written a script which shows me my most used commands. That way I can optimize my terminal usage. This, of course, is impossible with history dedup.

**Comment by faho** [comment]
The thing to do here isn't to add an option, but to keep tally of how often a command was executed. And that's #2398.

**Comment by zanchey** [comment]
You can fake this in the meantime with a function which runs on the `fish_preexec` event.

**Comment by timvisee** [comment]
> You can fake this in the meantime with a function which runs on the `fish_preexec` event.

Are you sure, I've added this in `~/.config/fish/config.fish`, but it doesn't really seem to do anything (fish 2.7.1).

```fish
function fish_preexec --description "Track fish history in file"
    echo $argv >> ~/.fish_history
end
```

**Comment by zanchey** [comment]
You need an event handler for `fish_preexec`, rather than a function called that (otherwise you could only have one event handler for a given event).

Try:

```fish
function my_hist --on-event fish_preexec --description "Track fish history in file"
    echo $argv >> ~/.fish_history
end
```

**Comment by timvisee** [comment]
@zanchey This is brilliant. Thanks for the heads up!
