### ISSUE TITLE
argparse unexpected behaviour when using '=?' conditional argument modifier

### ISSUE THREAD

**Issue by cxor** [fish-shell/fish-shell#5941]
Fish version used: 3.0.2
OS: Archlinux
Term: Tilix

The output of argparse buitin is unexpected when using a switch which can or can not have an argument, for example `argparse 'd/debug=?' -- $argv`, where 'd/debug' is a generic switch name which conditionally accepts an argument.

In this case I guess that the expected behavior should be the following:
**Case (1)` somefunc -d <arg>`**
Expected behavior: sets "_flag_d" and "_flag_debug" to "<arg>"; the same should apply when using long option '--debug'
**Case (2) `somefunc -d`**
Expected behavior: sets with null value both "_flag_d" and "_flag_debug"; the same applies when using long option '--debug', as in Case (1).

Case (2) is working as expected. Case (1) is not: the only way to get it working as previously described is to use `somefunc -d"<arg>"` (note that there must be no spaces between -d and the argument, and the latter must be quoted) or `somefunc --debug=<arg>` (seems mandatory the "=" mark, `somefunc --debug <arg>` does not work either).

**Comment by faho** [comment]
Yeah, that's getopt behavior.

The idea is that a flag with an optional argument is just a boolean by default, and any other arguments are usually normal arguments to the command. If you want to specify arguments to the option, you'll have to attach them.

I don't think we want to deviate here.
