### ISSUE TITLE
Enhance argparse with option to set variable names.

### ISSUE THREAD

**Issue by AnthonyMonterrosa** [fish-shell/fish-shell#5946]
Small suggestion: would it be a reasonable request to ask that the variables set by `argparse ` have an option to be named? As in, instead of `_flag_X` for `x/X`, the input instead could be `x/X:variable_name` and then `variable_name` would hold the value of flag X? This would be nice if the name of the flag used by the user isn't the best name that could be used by the developer, because of different levels of understanding. Also would help reduce visual noise IMO, as the `_flag_` prefix feels unnecessary in most cases, at least in my use.

What do ya'll think?

**Comment by faho** [comment]
If you want to rename a flag, then just duplicate it: `set -l variable_name $_flag_X`.

Adding more things onto the DSL makes it *more* confusing, not less, because there's more features to learn for dubious gain.
