### ISSUE TITLE
Error when trying to open QtCreator through command line.

### ISSUE THREAD

**Issue by ragreenburg** [fish-shell/fish-shell#5950]
Open up terminal
start typing 'qtcreator' before finishing it sends the error message "fish: Error while search for command "/usr/bin/qtcreator""

**Comment by faho** [comment]
@ragreenburg: This is missing quite a lot of information. Which fish version are you using, on what system? Do you have any customization, especially third-party things like oh-my-fish or fisher?

Can you clarify that the error happens *before* you execute qtcreator? I.e. you've just typed `qtcreator`, not pressed enter yet?

Does this happen with any other executable? Do you have qtcreator installed or not?

Can you re-check the error message, or just add a screenshot of the error?

**Comment by ragreenburg** [comment]
Sorry, I typed all of that in but must have been in the wrong section. I am using Ubuntu 18.04.2 with the gnome-terminal and my version of fish is 2.7.1 and I am not using any third party customization. The only change I've made is changing the theme through `fish_config`. Yes, this happens before touching enter. So right now if I open up the terminal and type `qtc` it will immediately end the command and give `<W> fish: Error while searching for command “/usr/bin/qtcreator”
access:`
As far as I have seen it hasn't happened with any other executable but I may run through some and see if I can find any.

**Comment by faho** [comment]
Okay, that's an error from the "access" function, which we call to figure out if this is a valid command (which we do before you execute anything for syntax highlighting).

There should be another line explaining the error, but that might be an issue of locale and should be unrelated to this.

`access()` can fail for a number of reasons, most of which we handle specially. On sensible systems (which I'd typically count Ubuntu as), the only remaining trigger of this error should be ELOOP, meaning you have a symlink loop (there's also `EROFS`, but we don't need write access here, so I don't think that's it?).

I'd suggest checking `readlink /usr/bin/qtcreator`.

**Comment by ragreenburg** [comment]
Alrighty, when I type that in I get `./qtcreator`

**Comment by faho** [comment]
>Alrighty, when I type that in I get ./qtcreator

That indeed means the link is broken. It points to a file at "./qtcreator", but that's BS, because that's a relative path.

I would imagine that actually launching it doesn't work?

**Comment by ragreenburg** [comment]
If by launching you mean clicking on the icon, then yes that still works.

**Comment by faho** [comment]
>If by launching you mean clicking on the icon, then yes that still works.

No, I mean running `/usr/bin/qtcreator` inside of a shell.

**Comment by ragreenburg** [comment]
That makes a lot more sense. Yes, that doesn't work.

**Comment by faho** [comment]
Yep, that file is borken. I'd suggest either fixing it yourself or reporting a bug to whoever packaged it.

**Comment by ragreenburg** [comment]
Alright, thank you for the help!
