### ISSUE TITLE
List of fish color codes

### ISSUE THREAD

**Issue by Aracki** [fish-shell/fish-shell#5952]
There is a nice [list](https://unix.stackexchange.com/a/124409/292407) for bash but couldn't find it for fish. I went through official docs and haven't found any resource.

**Comment by ridiculousfish** [comment]
You can use `set_color --print-colors` to get some classic ANSI colors. On a modern terminal you can use RGB colors, e.g. `set_color FF0000` for a 24 bit hex color. Hope that helps!
