### ISSUE TITLE
More intuitive forward iteration of last history command

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5953]
The issue of whether a single ↑ movement brings up the most recent completion for the text present at the commandline or whether it brings up the second most recent (with the most recent being available via → instead) but I would like to suggest that when reverse reverse iterating history (back forwards again), the final history item shown should be the last true match.

e.g.

```
> foo1
> foo2
> foo3
> foo
     |-- → foo3

     |-- ↑ foo2
         ↑ foo1
         ↓ foo2
         ↓ foo3 # this one is new in this proposal
         ↓ foo
```

**Comment by faho** [comment]
@mqudsi: You've missed some text there.

**Comment by mqudsi** [comment]
Yes, sorry about that. My daughter started smashing the keyboard as I was still typing out the issue title. IMHO GitHub should not allow issues without changes to the default body text, but that's neither here nor there.

**Comment by lilyball** [comment]
I disagree with this proposal. If I press ↑ twice, pressing ↓ twice should bring me back to where I started. If I wanted that final history item I would have pressed → instead, and in fact I still can after getting back to where I started.

**Comment by faho** [comment]
Alright, this doesn't appear to have found interest.
