### ISSUE TITLE
Allow undo of → history completion

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#5954]
Just a suggestion for a minor tweak to history completion behavior: after completing to the most recent history match for a command (`> foo→`), it should be possible to return to the uncompleted state if the very next input is a down arrow, so that `> foo→↓` behaves the same way `> foo↑↓` would. 

(I would suggest `> foo→←`, but that is often used when one wants to change the text of the previous completion and obviously would not do.)

**Comment by ridiculousfish** [comment]
That sounds good to me. Of course this applies to all autosuggestions, not just those for history.

**Comment by ridiculousfish** [comment]
On reflection this is probably a better candidate for the `undo` feature - #1367 

btw 'completions' feature tag is for changes to individual completions, not the infrastructure.

**Comment by mqudsi** [comment]
> btw 'completions' feature tag is for changes to individual completions, not the infrastructure.

I was just thinking about how they're sometimes conflated!

**Comment by faho** [comment]
Okay, I'm gonna close this as a "duplicate" (really: "part of") #1367.
