### ISSUE TITLE
test -e /dir/wild*card throws "no matches for wildcard" - How to better test this?

### ISSUE THREAD

**Issue by ElijahLynn** [fish-shell/fish-shell#5960]
Fish 3.0.2 - How to better test for a wildcard file being present in this Ansible script without throwing this error/warning?

`git clone https://github.com/ansible/ansible.git`
`source ./hacking/env-setup.fish`

> ❯ source ./hacking/env-setup.fish
./hacking/env-setup.fish (line 69): No matches for wildcard “$PREFIX_PYTHONPATH/ansible*.egg-info”. See `help expand`.
    if test -e $PREFIX_PYTHONPATH/ansible*.egg-info
               ^
in function “gen_egg_info”
        called on line 88 of file ./hacking/env-setup.fish
from sourcing file ./hacking/env-setup.fish
        called on standard input

**Comment by faho** [comment]
Wildcards already, by definition, test for existence.

So you know that it exists if the wildcard expands to something.

I.e. either of these is fine:

```fish
set files $PREFIX_PYTHONPATH/ansible*.egg-info
if set -q files[1]
# or
if count $PREFIX_PYTHONPATH/ansible*.egg-info >/dev/null
```

**Comment by ElijahLynn** [comment]
Thanks @faho, submitted a PR to fix with your suggestion.
