### ISSUE TITLE
Building from source (macOS) - Xcode... not complete?

### ISSUE THREAD

**Issue by jorpoka** [fish-shell/fish-shell#5961]
At the bottom of the Readme.md, it shows how to build on the Mac:

```
mkdir build; cd build
cmake .. -G Xcode
```

But other than mentioning that there is an Xcode project in the build directory, there aren't any more instructions.

Previously I would run

```
xcodebuild
xcodebuild install
ditto /tmp/fish.dst /
```

`xcodebuild install` doesn't seem to install the shell in `/usr/local/bin` or some files into `/tmp` like it would previously.

Can Readme.md be updated to show how a complete installation of fishshell on macOS using the xcodebuild process is done?

> HEAD detached at 3.0.2
> 
> Darwin MacBook-Pro.local 19.0.0 Darwin Kernel Version 19.0.0: Thu Jun 13 21:52:56 PDT 2019; root:xnu-6110.0.0.121.5~2/RELEASE_X86_64 x86_64
> 
> xterm-256color

**Comment by faho** [comment]
>But other than mentioning that there is an Xcode project in the build directory, there aren't any more instructions.

The xcode project was removed when we switched to cmake.

I would assume that this works just like other build tools work with cmake: Run cmake, then run the actual build tool.

```fish
mkdir build; cd build
cmake .. -G Xcode
xcodebuild
xcodebuild install
ditto /tmp/fish.dst /
```

**Comment by jorpoka** [comment]
> The xcode project was removed when we switched to cmake.
> 
> I would assume that this works just like other build tools work with cmake: Run cmake, then run the actual build tool.
> 
> ```fish
> mkdir build; cd build
> cmake .. -G Xcode
> xcodebuild
> xcodebuild install
> ditto /tmp/fish.dst /
> ```

That's the problem, there's no file gets installed at `/tmp/fish.dst`. It seems like the steps to build on macOS are not complete or the created project is no longer functioning as intended.

Is this not a recommended process for building anymore on the Mac? Should I just be using the **all platforms** process?

**Comment by faho** [comment]
>Should I just be using the all platforms process?

As far as I know: Yes.

**Comment by zanchey** [comment]
Xcode should work. I'll write it up.
