### ISSUE TITLE
Resizing terminal confuses `fish`

### ISSUE THREAD

**Issue by raichoo** [fish-shell/fish-shell#5962]
I'm having some issues when resizing terminals running `fish`, presumably it has something to do with the right prompt.

When increasing the size horizontally I get the following result.

![2019-06-25-100125_664x364_scrot](https://user-images.githubusercontent.com/151506/60080662-a3922880-9730-11e9-85e3-3ab7204a81b5.png)

Interestingly enough the prompt gets repainted (timestamp updates) but the new terminal size seems to be ignored.

Clearing the terminal fixes this issue.

What's worse though is if I decrease terminal size and start typing. Then I end up with this:

![2019-06-25-100139_464x364_scrot](https://user-images.githubusercontent.com/151506/60080820-e7852d80-9730-11e9-9776-76a5f7fc0e0f.png)

I've tested this with `xterm` and `sakura` both yielding the same result. I'm running `fish, version 3.0.2-1318-g27e4d1d6`.

**Comment by faho** [comment]
Okay, so what is supposed to happen here is that we get a SIGWINCH, which triggers a handler function that does `commandline -f repaint`.

Only repainting does not query the new window size, so it just paints the same size again (you'll notice $COLUMNS staying the same).

As a workaround, execute a command, then it should get the correct size again.

**Comment by faho** [comment]
Okay, no, repainting *does* query the window size. This repaint seems to be skipped (we coalesce repaints without any change inbetween).

**Comment by raichoo** [comment]
@faho I usually run `clear` as a workaround. Fun fact, doing this just triggered #5963, but that's probably totally unrelated.

**Comment by faho** [comment]
Huh, no, this goes deeper (reminder: bind functions are queued up, so debug echos before and after will show up first). It's in screen somewhere, we don't update something correctly. What's that saying about cache invalidation?

Good thing is it worked in 3.0.2, so lemme just bisect it.

**Comment by faho** [comment]
Uh... WOT?

This bisects to 7ed1022cf41cd1b0111a7c280528324527fc8570. And it doesn't just bisect to it, if I revert that it works again.

@ridiculousfish: Any ideas why that would trigger this? The reproduction steps are:

- Add a right prompt. Any will do (I've been using `echo banana`)
- Resize the terminal to under the size where we should remove the right prompt
- Observe that the right prompt remains
- Enter some text, observe staircasing

Signals are obviously involved (SIGWINCH, caught by a signal handler set up in __fish_config_interactive), and UB is always a possibility, but I can't think of anything.

@raichoo: Can you confirm that reverting 7ed1022cf41cd1b0111a7c280528324527fc8570 helps?

**Comment by raichoo** [comment]
Reverting that commit seems to help.

**Comment by faho** [comment]
Then let's do that, considering it was supposed to be just cleanup.

**Comment by ridiculousfish** [comment]
Ugh. Thanks.

**Comment by ridiculousfish** [comment]
The breaking change was to only install signal handlers once. However if fish script asks to observe a signal (e.g. `__fish_winch_handler`) then we would reset the signal handler to a default handler. Later we would then overwrite that default handler the next time we went interactive. It was a mess.

Now we just have one signal handler function so there's no way to ever have the "wrong" handler.
