### ISSUE TITLE
`fish` moves process into the background instead of executing

### ISSUE THREAD

**Issue by raichoo** [fish-shell/fish-shell#5963]
I've been observing this issue since yesterday. Instead of executing a program `fish` seems to randomly move processes into the background. I don't know how to reproduce this faithfully, it seems quite random. My prompt indicates background processes by showing a red dot at the beginning of the line (without that I wouldn't even know that this happened). I have to manually send the process into the foreground.  I'm running `fish, version 3.0.2-1318-g27e4d1d6`.

![2019-06-25-102314_567x93_scrot](https://user-images.githubusercontent.com/151506/60082030-4f3c7800-9733-11e9-9a96-9c680e3f2763.png)

**Comment by faho** [comment]
Probably 536216134371696222b60dc2d29d50cc03fa56b3.

**Comment by ridiculousfish** [comment]
Aw hell. That change was supposed to make random backgrounding less common.

**Comment by raichoo** [comment]
@ridiculousfish Sadly this makes it happen so often now that it renders some terminal sessions more or less unusable by backgrounding almost every command I issue. :/

**Comment by ridiculousfish** [comment]
@raichoo what is your OS / terminal? Can you confirm whether 3f1d7bbdc5e300bd1b6cbd93901ec4aa5578bc0b fixes this?

**Comment by raichoo** [comment]
@ridiculousfish OS is FreeBSD and the bug shows up in `xterm` as well as in `sakura`. I'll give it a shot and will report back if I find anything suspicious (or if it seems to have fixed the issue). Thanks for the work :)

**Comment by raichoo** [comment]
The issue didn't show up over the weekend nor today. So I guess this can be considered fixed.
