### ISSUE TITLE
Fish sometimes starts displaying symbols in a wrong position or skipping them.

### ISSUE THREAD

**Issue by kchibisov** [fish-shell/fish-shell#5964]
`fish --version` : `fish, version 3.0.2-1319-g8f7a47547`

`uname -a` :  `Linux NightLord 5.1.14-arch1-1-ARCH #1 SMP PREEMPT Sat Jun 22 16:28:48 UTC 2019 x86_64 GNU/Linux`.

`echo $TERM`: `alacritty`, (also tested with `tmux-256color` and `xterm-256color`).

everything was tested with `sh -c 'env HOME=$(mktemp -d) fish'`
and tried in different terminal emulators (`alacritty`, `konsole` and `kitty`). I wasn't able to reproduce this issue with `bash`, `zsh`. 

Steps to reproduce:
Open terminal and hold a key. (you can use `xset r rate 200 255` to speed up things in case you're on `X11`, but `xset r rate 200 30` was sufficient to reproduce the issue).

At some point you should notice wrong rendering or something like that.

This screenshot should help you understanding the issue. I've just opened a terminal, pressed `l` key and after sometime hit `enter`.

![Screenshot_20190626_020528](https://user-images.githubusercontent.com/27620401/60140106-278ff300-97b9-11e9-87d3-7fdba1297fbc.png)

**Comment by faho** [comment]
This looks like fish is missing the highlighting window before the next character is added.

We've sped that up by a surprising amount in git master, so you'll be unlikely to hit it. If you could try with git master that'd be lovely.

**Comment by kchibisov** [comment]
@faho Yes seems like it was fixed on the latest master. Thanks!
