### ISSUE TITLE
Constantly Executing Command Fish

### ISSUE THREAD

**Issue by SL1MEY-T0AD** [fish-shell/fish-shell#5966]
Info:
fish, version 2.7.1
Linux DESKTOP-G8HNNLM 4.4.0-17763-Microsoft #379-Microsoft Wed Mar 06 19:16:00 PST 2019 x86_64 GNU/Linux
xterm-256color

Detail:
It may be a user error, apologies if it is the case. But when running certain commands from ~/.config/fish/config.fish fish can get stuck in an infinite loop. 

if I run something like echo "test" from ~/.config/fish/config.fish - I get the expected output of seeing the word test appear once when the shell loads. However, if I run a command such as script ~/start_fish_log - the command will run infinitely. 

Screenshots attached.
![fish1](https://user-images.githubusercontent.com/47655229/60186491-db02f100-9866-11e9-9fb9-e2a2e6bea4a7.png)

![infiniteloopfish](https://user-images.githubusercontent.com/47655229/60186493-db9b8780-9866-11e9-8575-191849bf2383.png)

**Comment by faho** [comment]
>However, if I run a command such as script ~/start_fish_log - the command will run infinitely.

That is because `script` starts a new fish. And that fish will then also read config.fish, so it will execute `script`, which will start a new `script`.

**Comment by SL1MEY-T0AD** [comment]
Thanks for explaining Faho much appreciated - left me scratching my head for a while! For anyone looking for the solution please see above!
