### ISSUE TITLE
Ctrl-D/delete-or-exit clears current line instead of forward deleting

### ISSUE THREAD

**Issue by rien333** [fish-shell/fish-shell#5967]
Previous versions of fish performed a forward delete of one character from the current pointer when pressing `ctrl-d`. Now, it clears the whole line, kinda like entering `ctrl-c` when you've typed some text, and exits the shell if there is no text.  This key is, and was, bound to the internal function `delete-or-exit`:

```fish
$ find
...
bind --preset \cd delete-or-exit
```

Given that the name of the function did not change, I'm not sure if this new behavior is intentional. If it is, I think users should be provided the option to restore the old behavior (i.e. a definition of a `delete-or-exit` function that behaves as it once did), because the behavior of fish shell is now different from basically all other "TUIs"/shells, e.g. bash, emacs and programs that use readline  (say, the interactive python interpreter). It is definitely  annoying to exit out of your shell when pressing `ctrl+d` a few times out of habit, and it's kinda unclear for me why we need another key to clear the the current line when `ctrl+c` does the job fine.

System info:
```fish
$ fish --version
fish, version 3.0.2-1346-g22d262071
$ uname -a
Linux HOST 5.1.14-arch1-1-ARCH #1 SMP PREEMPT Sat Jun 22 16:28:48 UTC 2019 x86_64GNU/Linux
$ echo $TERM
xterm-kitty # pretty much the same as xterm256
```

**Comment by faho** [comment]
>Given that the name of the function did not change, I'm not sure if this new behavior is intentional. 

It is not. I reimplemented it in C++ and misunderstood the "delete" part.
