### ISSUE TITLE
Add Alacritty support

### ISSUE THREAD

**Issue by cig0** [fish-shell/fish-shell#5970]
Hi,

My sys specs:
 
- Fish version: 3.0.2 installed and managed with Homebrew
- OS: macOS Mojave 10.14.5
- $TERM: xterm-256color

Can you please consider shipping future Fish releases with Alacritty integration? https://github.com/jwilm/alacritty/blob/master/INSTALL.md#shell-completions

All the best

**Comment by zanchey** [comment]
I don't think we'll do this, because if the completions are already maintained upstream we would just be forever shipping an inferior version.

I'll close this for now, though happy to hear other views.

**Comment by cig0** [comment]
Hi @zanchey,

That's a good point that I didn't think about, I'll head to the Homebrew formula maintainers.

Thanks!
