### ISSUE TITLE
Complete username after ~ in filepath

### ISSUE THREAD

**Issue by tbodt** [fish-shell/fish-shell#5972]
For example if I type ~r<tab> it should offer ~root as a completion.

**Comment by faho** [comment]
We do?

Which command did you try?

**Comment by faho** [comment]
Also obviously which fish version, operating system, ...

But mainly: What are you doing? Does `ls ~<TAB>` complete the users or not?

**Comment by tbodt** [comment]
Actually it does work, except my computer has a ton of network usernames that aren't in my /etc/password. There's probably some way for me to override the completion to just the usernames that are useful to me.
