### ISSUE TITLE
shell-integration - how distringuish winch repaint from ctrl-c cancel

### ISSUE THREAD

**Issue by PerBothner** [fish-shell/fish-shell#5973]
I'm trying to specify and implement a more fancy "shell integration" protocol.  See this [draft protocol proposal](https://gitlab.com/PerBothner/terminal-specifications/blob/master/proposals/semantic-prompts.md) and a (draft) [blog article](http://per.bothner.com/blog/2019/shell-integration-proposal/) that discusses (with screenshots) some features and problems.  (The latter link also has instructions for trying out the implementation.)

A mostly-working fish script is [here](https://github.com/PerBothner/DomTerm/blob/shell-integration/tools/shell-integration.fish).  However, I have one problem - how to distinguish two scenarios:

* The user types ctrl/c during input editing, canceling the command.  In that case we want to display the partial input line, followed by `^C`, followed by the prompt for the next command.

* The user resizes the window during input editing. Fish receives a SIGWINCH and repaints the input line(s).  In that case we want the terminal to clear out the input area, and replace the current command.

How can I reliably distinguish these cases?  In neither case is fish_command_not_found or fish_preexec or fish_postexec called.

I can use heuristics: Did the user type ctrl-c? Did the windows size change?  However, this seems ugly and lacks robustness.

**Comment by faho** [comment]
>How can I reliably distinguish these cases?

Currently: You don't. These things both just end up repainting the commandline. ctrl-c will also clear it, but that's not really reliable as something else could also clear it, or it could have been clear for unrelated reasons.

This would need changes on the fish-side.

Though note that the current ctrl-c handling isn't entirely uncontroversial - we used to just clear the commandline, and the main issue with that was that you'd entirely lose what you entered before. That could also be done with undo instead.

**Comment by PerBothner** [comment]
Could we add something like this somewhere:

    event_fire_generic(parser, L"fish_cancel");

The problem is I haven't figured out the logic for how ctrl-c is handled (tracing with gdb hasn't worked so far), so I have no idea where something that should be.

**Comment by faho** [comment]
>The problem is I haven't figured out the logic for how ctrl-c is handled 

It's a binding.

```fish
> bind \cc
bind --preset \cc __fish_cancel_commandline
> type __fish_cancel_commandline
__fish_cancel_commandline is a function with definition
# Defined in /home/alfa/.config/fish/test/functions/__fish_cancel_commandline.fish @ line 2
function __fish_cancel_commandline

    commandline -f cancel

    set -l cmd (commandline)
    if test -n "$cmd"
        commandline -C 1000000
        if set -q fish_color_cancel
            echo -ns (set_color $fish_color_cancel) "^C" (set_color normal)
        else
            echo -ns "^C"
        end
        commandline -f suppress-autosuggestion
        if command -sq tput
            # Clear to EOL (to erase any autosuggestion).
            echo -n (tput el; or tput ce)
        end
        for i in (seq (commandline -L))
            echo ""
        end
        commandline ""
        commandline -f execute
    end
end
```

One possibility would be to add `emit fish_cancel` to it - that won't fire with custom bindings, but I don't think you care about those?

**Comment by PerBothner** [comment]
Adding `emit fish_cancel` after the final `commandline -f repaint` (not `commandline -f execute`) seems to work. I'll do some more testing and experimenting before I create a pull request.

I don't think custom bindings are a problem: I expect they either use `__fish_cancel_commandline` in which case no problem, or they would do more extensive scripting and the shell-integration script breaks anyway.

**Comment by PerBothner** [comment]
I got it to work without changing fish itself or adding a `fish_cancel` signal:

    functions -c __fish_cancel_commandline _fishprompt_saved_cancel
    function __fish_cancel_commandline
      _fishprompt_saved_cancel $argv
      printf "\033]133;Z;cancel;aid=%s\007" $_fishprompt_aid
      set _fishprompt_started 0
      set _fishprompt_postexec 0
    end

A downside of this is it depends on what appears to be an undocumented function `__fish_cancel_commandline`.  Adding an `emit fish_cancel` to `__fish_cancel_commandline` might be more future-proof.  Which approach do you think is best?

**Comment by faho** [comment]
>Adding an emit fish_cancel to __fish_cancel_commandline might be more future-proof. Which approach do you think is best?

Definitely adding the `emit` to the function directly. Copying it and calling it adds more confusion when a user goes digging through the bindings, and is really entirely unnecessary if you can just change the source itself.
