### ISSUE TITLE
Add `string sub --end`

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#5974]
Would be neat if `string sub --length` accepted negatives indexes, just like `string sub --start`, e.g. 

```fish
$ string sub --length -2 -- foobar
foob
```

AFAIK, the only way to achieve this at the moment is:
```fish
$ set s foobar
$ string sub --length (math (string length -- $s) - 2) -- $s
foob
```

(Also, feel like this option should be (re?)named `--end` to match `--start`)

**Comment by faho** [comment]
That's an entirely different thing?

Like... with a length of 3, you'd go from a start of e.g. 2 to an end of 5.

Which is an okay thing to add, I just don't see why we should remove --length for it.

**Comment by faho** [comment]
E.g. `string sub --start 2 --length 3 foobar` prints "oob" (a 3-long string starting with the second character).

`string sub --start 2 --end 3 foobar` should print either `oo` or just `o`. (Arguably it'd be better to include the end, like we include the start, so `oo`)

**Comment by zx8** [comment]
Aha, misunderstood `--length`, got it!
