### ISSUE TITLE
Completions for iw

### ISSUE THREAD

**Issue by exploide** [fish-shell/fish-shell#5977]
The completions for the `ip` command are extremely useful, because it even completes the horrible interface names e.g. in `ip l set enp0s31f6 up`.

The `iw` command behaves similar but unfortunately there are no completions, yet. I.e. it would be awesome to be able to complete something like `iw dev wlp0s20f3 set type managed` without typing the interface name completely by hand.

**Comment by faho** [comment]
Sure, if anyone wants to write some, I'd be happy to provide guidance!

Since the iw interface is pretty similar to the ip one, that should be useful as a skeleton.

**Comment by exploide** [comment]
fixed in #6232, thanks @rianadon
