### ISSUE TITLE
Add pushenv/popenv for environment variables

### ISSUE THREAD

**Issue by DianaNites** [fish-shell/fish-shell#5978]
It'd be useful in scripts that want to ensure the environment remains clean and consistent to provide an "environment stack" similar to the "directory stack", allowing blocks of code to add environment variables without polluting the rest of the script and causing unexpected(Especially variables such as `MAKEFLAGS`, `CC`, and the like.)

as an example, i'd like this or similar to work

```fish
#!/bin/fish
set -x FOO BAR
pushenv
#
echo $FOO # prints BAR
set -xp FOO
echo $FOO # prints FOO BAR
set -x CC cc
echo $CC # prints cc
set ENV_CC $CC
echo $ENV_CC # prints cc.
#
popenv
echo $FOO # still prints BAR
echo $CC # prints nothing, undefined
echo $ENV_CC # prints cc
```

**Comment by faho** [comment]
This is what `begin; end` and local-scoped variables do:

```fish
set -l foo bar
begin
echo $foo  prints bar
set -l foo foo $foo
echo $foo # prints foo bar
set -l CC cc
set ENV_CC $CC
echo $ENV_CC # prints cc
end
echo $FOO # still prints bar
echo $CC # prints nothing
echo $ENV_CC # prints cc
```

(really "local" scope should have been called "block" scope)

**Comment by DianaNites** [comment]
Those are *shell* variables, not *environment* variables. Note that i said *environment* and passed `set` the `-x` flag.

```fish
echo $FOO # Prints nothing
begin
	set -x FOO BAR
	echo $FOO # prints BAR
end
echo $FOO # Still prints bar, FOO still exists.
```

**Comment by Darkshadow2** [comment]
You can use `set -lx` in a `begin; end` block to both have it scoped to that block and exported.

**Comment by DianaNites** [comment]
I never would've guessed that, thanks! That should work for my purposes.
