### ISSUE TITLE
MacOS 10.15 Beta - Slow Fish Prompts

### ISSUE THREAD

**Issue by zikphil** [fish-shell/fish-shell#5980]
Hello, I am running latest fish (3.0.2) and since the upgrade to MacOS Catalina (10.15 Beta) I've noticied that fish prompts that includes vcs info are very slow to return. Each new line takes a good second before returning.

Also going in the prompts tab in fish_config also takes 5-8 seconds to load.

**Comment by faho** [comment]
It would be nice to know which part is slow here, and if there's anything we can do about it (it's possible that the system is just slow).

E.g. if you execute `__fish_vcs_prompt` and then `echo $CMD_DURATION` does that show a large number (for comparison on my system in the fish-shell repo I get ~40 there)?

Also the output of `fish --profile /tmp/profile -c fish_prompt; sort -nk2 /tmp/profile` would be nice (at least the last ~10 lines, ideally the entire /tmp/profile file).

**Comment by zikphil** [comment]
Hello,

First output: ```~/p/d/xx-cli (master|✚1) $ __fish_vcs_prompt                                                                                                                                                              11:03:44
 (master|✚1)⏎                                                                                                                                                                                                        ~/p/d/xx-cli (master|✚1) $ echo $CMD_DURATION                                                                                                                                                             11:03:47
460```

Second: https://pastebin.com/g8ChnfQk

**Comment by zikphil** [comment]
![Example](https://i.imgur.com/0rXBQll.gif)

**Comment by faho** [comment]
Yeah, you're apparently using svn here, that's taking up ~400ms of the total ~460ms.

**Comment by faho** [comment]
Okay, I added a change that would not attempt hg and svn if git succeeded - that's really the only thing we *can* do here, because the thing that figures out if svn exists (`svn info`) is apparently ~10x slower on your system than mine.

**Comment by zikphil** [comment]
This could be a 10.15 specific thing. Thank you I will test the change :)

**Comment by zikphil** [comment]
Much faster, thank you :) We can close

**Comment by zikphil** [comment]
Update: Actually installing svn solved the issue. Seems like it is no longer included in OSX versions past 10.15 and it causes a delayed error message to pop-up when you try to call it.

**Comment by faho** [comment]
>Seems like it is no longer included in OSX versions past 10.15 and it causes a delayed error message to pop-up when you try to call it.

That means there's still an "svn" command available - if it weren't we'd skip the prompt entirely (we check `command -sq svn`).

Which is... unfortunate.

**Comment by gonejack** [comment]
After upgraded to MacOS 10.15.4 in this morning, fish get slow with any command.

By running @faho 's suggesting ```fish --profile /tmp/profile -c fish_prompt; sort -nk2 /tmp/profile```

The most slowest is 
![image](https://user-images.githubusercontent.com/2720676/77515683-f2354480-6eb3-11ea-9f9d-1e3c6cf6eabc.png)

Then I type `svn` in my terminal, it said ```svn is not more provided by Xcode```.

So I do ```brew install svn``` and fish normal again.
