### ISSUE TITLE
The alt+h keybinding should ignore sudo at the beginning of a command

### ISSUE THREAD

**Issue by jay-tuckey** [fish-shell/fish-shell#5982]
```
# My Details
~> fish --version
fish, version 3.0.2
~> uname -a
Linux jtuckey-x1-ubu 5.0.0-20-generic #21-Ubuntu SMP Mon Jun 24 09:32:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
~> echo $TERM
xterm-256color
```
One of the handy features of fish is that you can use `alt-h` to quickly pull up the man page for something, however if you have your terminal currently on `sudo command -x -y -z` and hit `alt+h` you get the man page for `sudo`, when it would be nice to get the man page for `command` instead. Not sure how easy this would be to fix, but it would be awesome if it could be made to behave this way. :smile:

**Comment by faho** [comment]
Yeah, sure.

`sudo`, and probably also `doas`, and `env`. The tricky bit is to ignore any options. But with `argparse` that's really just what's known in german as "Fleißarbeit".
