### ISSUE TITLE
`go` cannot be used with Fish shell

### ISSUE THREAD

**Issue by CermakM** [fish-shell/fish-shell#5983]
I am struggling with running `go` in the **fish shell**.

A) I followed the installation procedure and installed `go` as specified in the [documentation](https://golang.org/doc/install?download=go1.12.7.linux-amd64.tar.gz)

However, when I run `go version`, I am getting a fatal error:
```
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

When I initialize the git by `git init`, I receive another error:
```
error: pathspec 'version' did not match any file(s) known to git
```

I have the paths configured in my fish **config** as follows:
```
set -gx GOPATH /home/<user>/go
set -gx PATH $PATH /usr/local/bin/go $GOPATH/bin
```

where `/usr/local/bin/go` is an output of `which go` in both `bash` and `fish`

<br>

Running it like `bash -c 'go version'`, however, **works without any problems** (even without the git directory).

<br>

B) Also tried `gofish` and `dnf` to install go, the same results

Any help is greatly appreciated!

<br>

Additional info:

- Fish version: `fish, version 3.0.2`
- Operating system: Fedora 30

**Comment by CermakM** [comment]
Related SO question: https://stackoverflow.com/questions/56972032/using-go-with-fish-shell

**Comment by CermakM** [comment]
Oh my... I had an alias set for `git checkout` (facepalm). Resolved, thanks!

**Comment by faho** [comment]
>where /usr/local/bin/go is an output of which go in both bash and fish

Don't use `which` - it's an external command, so it *can* only tell you about external commands. Use `type`, in both.
