### ISSUE TITLE
Emacs tramp hangs when open a file with doas

### ISSUE THREAD

**Issue by bbuccianti** [fish-shell/fish-shell#5985]
fish --version
  fish, version 3.0.2

  uname -a
  Linux i5 4.19.58-0-vanilla #1-Alpine SMP Wed Jul 10 12:40:48 UTC 2019 x86_64 Linux

  echo $TERM
  screen-256color (rxvt-unicode)

  TERM=DUMB under Emacs Tramp

I've setted this in order to work in Emacs with fish.

# Disable fish_prompt for tramp
if test "$TERM" = "dumb"
    function fish_prompt
        echo "\$ "
    end

    function fish_right_prompt; end
    function fish_greeting; end
    function fish_title; end
end

I'm trying to edit a file with root permissions. Using Emacs I open file with /doas::/etc/fstab but Emacs hangs and I can see this on the debug output:

09:39:08.377189 tramp-get-connection-property (7) # check-remote-echo nil
09:39:08.377325 tramp-get-connection-property (7) # check-remote-echo nil
09:39:08.378741 tramp-accept-process-output (10) # *tramp/doas root@i5* run t
[?2004h⏎                                                                              
⏎ 

$ 
$ exec env TERM='dumb' INSIDE_EMACS='26.2,tramp:2.3.5.26.2' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
09:39:08.378855 tramp-get-connection-property (7) # check-remote-echo nil
09:39:08.378972 tramp-get-connection-property (7) # check-remote-echo nil
09:39:08.382216 tramp-accept-process-output (10) # *tramp/doas root@i5* run t
[?2004h⏎                                                                              
⏎ 

$ 
$ exec env TERM='dumb' INSIDE_EMACS='26.2,tramp:2.3.5.26.2' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
$ exec env TERM='dumb' INSIDE_EMACS='26.2,tramp:2.3.5.26.2' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
09:39:08.382377 tramp-get-connection-property (7) # check-remote-echo nil
09:39:08.382515 tramp-get-connection-property (7) # check-remote-echo nil
09:39:08.382785 tramp-accept-process-output (10) # *tramp/doas root@i5* run t
[?2004h⏎                                                                              
⏎ 

$ 
$ exec env TERM='dumb' INSIDE_EMACS='26.2,tramp:2.3.5.26.2' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
$ exec env TERM='dumb' INSIDE_EMACS='26.2,tramp:2.3.5.26.2' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
[?2004lThere are still jobs active:

   PID  Command
  6413  $py $update_args >/dev/null 2>&1 &

A second attempt to exit will terminate them.
Use 'disown PID' to remove jobs from the list without terminating them.
[?2004h
09:39:08.382966 tramp-get-connection-property (7) # check-remote-echo nil
09:39:08.383095 tramp-get-connection-property (7) # check-remote-echo nil
09:39:08.383392 tramp-accept-process-output (10) # *tramp/doas root@i5* run t
[?2004h⏎                                                                              
⏎ 

$ 
$ exec env TERM='dumb' INSIDE_EMACS='26.2,tramp:2.3.5.26.2' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
$ exec env TERM='dumb' INSIDE_EMACS='26.2,tramp:2.3.5.26.2' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
[?2004lThere are still jobs active:

   PID  Command
  6413  $py $update_args >/dev/null 2>&1 &

A second attempt to exit will terminate them.
Use 'disown PID' to remove jobs from the list without terminating them.
[?2004h⏎                                                                              
⏎ 

$ 
09:39:08.383554 tramp-get-connection-property (7) # check-remote-echo nil
09:39:08.383674 tramp-get-connection-property (7) # check-remote-echo nil
09:39:09.385256 tramp-accept-process-output (10) # *tramp/doas root@i5* run nil
[?2004h⏎                                                                              
⏎ 

$ 
$ exec env TERM='dumb' INSIDE_EMACS='26.2,tramp:2.3.5.26.2' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
$ exec env TERM='dumb' INSIDE_EMACS='26.2,tramp:2.3.5.26.2' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
[?2004lThere are still jobs active:

   PID  Command
  6413  $py $update_args >/dev/null 2>&1 &

A second attempt to exit will terminate them.
Use 'disown PID' to remove jobs from the list without terminating them.
[?2004h⏎                                                                              
⏎ 

$ 
09:39:09.385664 tramp-get-connection-property (7) # check-remote-echo nil
09:39:09.385885 tramp-get-connection-property (7) # check-remote-echo nil
09:39:10.387041 tramp-accept-process-output (10) # *tramp/doas root@i5* run nil
[?2004h⏎                                                                              
⏎ 

$ 
$ exec env TERM='dumb' INSIDE_EMACS='26.2,tramp:2.3.5.26.2' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
$ exec env TERM='dumb' INSIDE_EMACS='26.2,tramp:2.3.5.26.2' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
[?2004lThere are still jobs active:

   PID  Command
  6413  $py $update_args >/dev/null 2>&1 &

A second attempt to exit will terminate them.
Use 'disown PID' to remove jobs from the list without terminating them.
[?2004h⏎                                                                              
⏎ 

$ 
09:39:10.387458 tramp-get-connection-property (7) # check-remote-echo nil
09:39:10.387729 tramp-get-connection-property (7) # check-remote-echo nil
09:39:11.388666 tramp-accept-process-output (10) # *tramp/doas root@i5* run nil
[?2004h⏎                                                                              
⏎ 

$ 
$ exec env TERM='dumb' INSIDE_EMACS='26.2,tramp:2.3.5.26.2' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
$ exec env TERM='dumb' INSIDE_EMACS='26.2,tramp:2.3.5.26.2' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
[?2004lThere are still jobs active:

   PID  Command
  6413  $py $update_args >/dev/null 2>&1 &

A second attempt to exit will terminate them.
Use 'disown PID' to remove jobs from the list without terminating them.
[?2004h⏎                                                                              
⏎ 

$ 
09:39:11.388909 tramp-get-connection-property (7) # check-remote-echo nil
09:39:11.389047 tramp-get-connection-property (7) # check-remote-echo nil
09:39:12.390655 tramp-accept-process-output (10) # *tramp/doas root@i5* run nil
[?2004h⏎                                                                              
⏎ 

$ 
$ exec env TERM='dumb' INSIDE_EMACS='26.2,tramp:2.3.5.26.2' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
$ exec env TERM='dumb' INSIDE_EMACS='26.2,tramp:2.3.5.26.2' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
[?2004lThere are still jobs active:

   PID  Command
  6413  $py $update_args >/dev/null 2>&1 &

A second attempt to exit will terminate them.
Use 'disown PID' to remove jobs from the list without terminating them.
[?2004h⏎                                                                              
⏎ 

$ 
09:39:12.391068 tramp-get-connection-property (7) # check-remote-echo nil
09:39:12.391270 tramp-get-connection-property (7) # check-remote-echo nil
09:39:13.392408 tramp-accept-process-output (10) # *tramp/doas root@i5* run nil
[?2004h⏎                                                                              
⏎ 

$ 
$ exec env TERM='dumb' INSIDE_EMACS='26.2,tramp:2.3.5.26.2' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
$ exec env TERM='dumb' INSIDE_EMACS='26.2,tramp:2.3.5.26.2' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
[?2004lThere are still jobs active:

   PID  Command
  6413  $py $update_args >/dev/null 2>&1 &

A second attempt to exit will terminate them.
Use 'disown PID' to remove jobs from the list without terminating them.
[?2004h⏎                                                                              
⏎ 

$ 
09:39:13.392815 tramp-get-connection-property (7) # check-remote-echo nil
09:39:13.393040 tramp-get-connection-property (7) # check-remote-echo nil
09:39:14.394841 tramp-accept-process-output (10) # *tramp/doas root@i5* run nil
[?2004h⏎                                                                              
⏎ 

$ 
$ exec env TERM='dumb' INSIDE_EMACS='26.2,tramp:2.3.5.26.2' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
$ exec env TERM='dumb' INSIDE_EMACS='26.2,tramp:2.3.5.26.2' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=\#\$\  PS2='' PS3='' /bin/sh 
[?2004lThere are still jobs active:

   PID  Command
  6413  $py $update_args >/dev/null 2>&1 &

A second attempt to exit will terminate them.
Use 'disown PID' to remove jobs from the list without terminating them.
[?2004h⏎                                                                              
⏎ 

$ 
09:39:14.395245 tramp-get-connection-property (7) # check-remote-echo nil
09:39:14.395469 tramp-get-connection-property (7) # check-remote-echo nil
09:39:14.501954 tramp-open-shell (5) # Opening remote shell ‘/bin/sh’...failed
09:39:14.502622 tramp-maybe-open-connection (3) # Opening connection for root@i5 using doas...failed

Any idea of why this is happening?

**Comment by faho** [comment]
So, it seems like you or doas are running

```fish
exec env TERM='dumb' INSIDE_EMACS='26.2,tramp:2.3.5.26.2' ENV='' HISTFILE=~/.tramp_history PROMPT_COMMAND='' PS1=#$\ PS2='' PS3='' /bin/sh
```

I.e. "/bin/sh, in a simplified environment". Then fish is complaining about:

>There are still jobs active:

>PID Command
>6413 $py $update_args >/dev/null 2>&1 &

Which is it generating the manpage completions for the first time. It's complaining because it's being asked to `exec`, which is akin to exitting, and it doesn't want to just stop that job.

Then it may be attempting that a few more times (I'm not sure, emacs' output here is always a mess), and then it stops.

If that's correct, the solution should simply be to let that process run to completion *once*. Or, if you can't, `mkdir ~/.local/share/fish/generated_completions` on the system. If that exists, fish shouldn't be attempting that again.
