### ISSUE TITLE
Fish shell iterates once over empty list

### ISSUE THREAD

**Issue by mlindner** [fish-shell/fish-shell#5986]
fish, version 3.0.2
3.0.2
archLinux 5.0.11

To reproduce the problem run:
```
for foo in ''
    echo "loop ran"
end
```

Expected results:
No output
Actual output:
prints "loop ran"

**Comment by faho** [comment]
This isn't an empty list. It's a list consisting of one empty string.

This is very much by design, and the entirely correct thing to do - otherwise `''` would be useless.

**Comment by mlindner** [comment]
Why do these produce different output:

```
set foo
for bar in $foo
    echo "loop ran"
end
```
Prints nothing

```
for bar in "$foo"
    echo "loop ran"
end
```
Prints "loop ran"

The behavior of these two pieces of script should not be different.

**Comment by faho** [comment]
>The behavior of these two pieces of script should not be different.

Yes it should be!

One is the list as the list itself. It has zero elements, so it expands to zero arguments, so the loop runs zero times.

The other is the list quoted, which guarantees that it'll result in one argument. So it'll run the loop once.

**Comment by mlindner** [comment]
This sounds like we are just repeating the bad mistakes of previous shell programs, not improving on them.

**Comment by faho** [comment]
The major mistake of previous shells was second-guessing your variables by splitting them again.

This doesn't second guess. It's either giving the thing as the list, or as one string. Any other thing we could do would require that second guessing - pass it as one or more arguments depending on what kind of thing it is.
