### ISSUE TITLE
string split returns empty array when all elements are empty

### ISSUE THREAD

**Issue by ssjhv** [fish-shell/fish-shell#5987]
Fish version 3.0.2
OS: Debian Linux

"string split" has explicit option (-n or --empty) to whether return empty elements or not. This works as intended, usually. 

~> count (string split / a/)
2
~> count (string split / /a)
2
~> count (string split -n / a/)
1
~> count (string split -n / /a)
1

However, there is an edge case

~> count (string split / /)
0
~> count (string split -n / /)
0

And the returns non-zero status. This feels somewhat inconsistent with the other cases.

- With -n or not, the returned status should be zero, because there was a split.
- The invocation without -n (string split / /) should return array of two empty strings.

**Comment by faho** [comment]
The issue isn't in string, it's in command substitutions. `string split / /` will print two empty elements, which results in two newlines right after each other.

So `string split / /` prints the same thing as `echo \n` or `printf \n\n`. Only `string split` is handled specially in command substitutions (it marks its output as "explicitly split"), and it seems that bit fails in this case.

@ridiculousfish?

**Comment by ssjhv** [comment]
Thanks for the explanation. However, it doesn't seem to explain string returning non-zero status. Does command substitution do something unusual in this case?

**Comment by lilyball** [comment]
The bug does appear to be in `string split` after all; `string split / /` doesn't print any newlines.

```
> echo \n


> string split / /
>
```

**Comment by lilyball** [comment]
Well, come to think of it, I think this is probably a bug in the buffer type that provides the explicit splitting feature. Most likely as long as its character count is `0` it won't produce any output, even though it has explicitly-split empty components. Adding a single character to the output somewhere (e.g. `string split / a///`) makes it produce the expected string. But my overall point is it's not just a bug when `string split` is used in command substitutions.

**Comment by faho** [comment]
>The bug does appear to be in string split after all; string split / / doesn't print any newlines.

That's not true for me?

Which fish version are you running? I'm on 42f38bb80.

![Screenshot_20190719_212318](https://user-images.githubusercontent.com/5185367/61560048-7739a580-aa6b-11e9-9e42-412b20809efc.png)

**Comment by faho** [comment]
Huh, okay, with 3.0.2 I get one newline with `string split / /`, but two show up with `string split / / | od -t x1z`.

With 42f38bb I get two newlines in both.

I would assume this is due to one of the numerous changes in how builtin output is handled, and it's a bug fix.

So that part is already handled, the command substitutions remain an issue.

**Comment by ridiculousfish** [comment]
Whoops, we were incorrectly discarding "empty" buffers where "empty" means zero characters. It should have been checking for zero elements. Nice find.
