### ISSUE TITLE
string repeat does not process beyond the first argument

### ISSUE THREAD

**Issue by ssjhv** [fish-shell/fish-shell#5988]
Fish version 3.0.2
OS: Debian Linux

string commands handle multiple arguments, e.g., "string length a bb ccc dddd" return four elements 1 2 3 4.

It looks like string repeat is an exception here.

~> string repeat -n 2 a bb ccc dddd
aa

It would be better if string repeat handles multiple arguments consistently with the other string commands.

(My motivation here is to use "string repeat -n 1 $var" as a way to return array $var. Currently one can either manually loop and echo, or use "string join \n $var", but loops are too long, and string join feels like it returns a single element, and automatic unpacking via newline split feels weird. I feel string repeat could be a good alternative to these.)

**Comment by faho** [comment]
>It would be better if string repeat handles multiple arguments consistently with the other string commands.

What is "consistently" here? Would it repeat each element n times, for "a a bb bb ccc ccc dddd dddd", or go through the list n times, for "a bb ccc dddd a bb ccc dddd"? Or something else?

>My motivation here is to use "string repeat -n 1 $var" as a way to return array $var

What do you mean by this? You mean "print the variable, one line per element"? That's typically done via `printf %s\n $var`. I'd think `repeat` would be the absolute last thing I'd reach for.

**Comment by ssjhv** [comment]
If I understand correct, all (other than repeat) string commands handle multiple arguments equivalent to
`for arg in $argv; string ... $arg; end`

So "consistent" repeat should return "aa bbbb cccccc dddd".

**Comment by ssjhv** [comment]
Oops. "aa bbbb cccccc dddddddd".

**Comment by ssjhv** [comment]
By the way, I tried "printf %s\n $var" to print variable, one line per element. And in my opinion this is not a good solution, because it prints one empty line when `[ (count $var) -eq 0 ]`.

```
~> set -l temp
~> count $temp
0
~> count (printf %s\n $temp)
1
```

**Comment by ridiculousfish** [comment]
You might like `set --show temp` for understanding a variable's value.

**Comment by ridiculousfish** [comment]
In 7a0bddfcfa60a4cc5b57792bd1fa88168fec0ce4 we repeat each argument in turn.
