### ISSUE TITLE
Dpkg and switching between account gives me error.

### ISSUE THREAD

**Issue by Duoquote** [fish-shell/fish-shell#5993]
**Fish version:** 2.2.0
**Term output:** xterm
**uname output:** Linux vmi244476.contaboserver.net 4.15.0-54-generic #58~16.04.1-Ubuntu SMP Mon Jun 24 13:21:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
**Current terminal:** bash

Don't know if reproducable, fish was installed for about 1 month but I didn't use it for that time, then now I decided to use it as main shell and typed `chsh -s /usr/bin/fish` to use it. And... tried to `sudo -i` to do some stuff, it logs me into root but gives me an error:

```bash
duoquote@vmi244476:~$ sudo -i
Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.
/bin/lesspipe (line 34):        isoinfo -d -i "$1" | grep -q ^Rock\.Ridge && iiopts="$iiopts -R"
                                                                           ^
fish: Error while reading file /bin/lesspipe
```

I thought it was fine as I am not going to be switching that fast but then I tried to install some package and it gave me that error:

```bash
duoquote@vmi244476:~$ sudo apt-get install nano
Reading package lists... Done
Building dependency tree
Reading state information... Done
nano is already the newest version (2.5.3-2ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Unsupported use of '||'. In fish, please use 'COMMAND; or COMMAND'.
fish: /usr/sbin/dpkg-preconfigure --apt || true
                                         ^
E: Sub-process /usr/sbin/dpkg-preconfigure --apt || true returned an error code (127)
E: Failure running script /usr/sbin/dpkg-preconfigure --apt || true
```

And thus I am not able to uninstall fish via apt command as it is broken for now, so how do I fix that? What did I do wrong?

**Comment by faho** [comment]
>Fish version: 2.2.0

That fish version is ancient, it's expected that `||` doesn't work.

Something here uses $SHELL to interpet arbitrary scripts, which it shouldn't do.

Switch the shell back to bash, uninstall fish and install a version that isn't 5 years old via [our PPA](https://launchpad.net/~fish-shell/+archive/ubuntu/release-3)

**Comment by Duoquote** [comment]
how do I install something while dpkg is not working

**Comment by faho** [comment]
>Update: Nevermind fixed it by: sudo rm /bin/sh and sudo ln -s /bin/bash /bin/sh

Wait, what? You linked /bin/sh to fish? Yeah, that's approximately 3000% not supported or recommended, and *will break*. Fish is not POSIX-compatible, so it absolutely cannot be used as sh or bash. It is usually entirely possible to use it as *your shell*, but not by changing what /bin/sh points to (and `chsh` doesn't do that either).
