### ISSUE TITLE
history errors with "fish: Unknown command 'less -R'"

### ISSUE THREAD

**Issue by toonn** [fish-shell/fish-shell#5994]
fish --version: `fish, version 3.0.2`
echo $version: `3.0.2`
uname -a: `Darwin terra 17.7.0 Darwin Kernel Version 17.7.0: Wed Apr 24 21:17:24 PDT 2019; root:xnu-4570.71.45~1/RELEASE_X86_64 x86_64`
echo $TERM: `xterm-256color`

sh -c 'env HOME=$(mktemp -d) fish': Couldn't verify, after doing `set PAGER less` `history` worked and then when I later did `set PAGER less -R` for testing it still worked.

Here is an excerpt of the session with the original error, which I can no longer reproduce. Note that I never set `PAGER=less -R` or anything else for that matter in any of my configurations.

```
toonn@terra ~> history
fish: Unknown command 'less -R'
/nix/store/m8j4gqqkdy3nm0v738kjivimnlqkdqpx-fish-3.0.2/share/fish/functions/history.fish (line 99): 
                builtin history search $search_mode $show_time $max_count $_flag_case_sensitive $_flag_reverse $_flag_null -- $argv | $pager
                                                                                                                                      ^
in function 'history'
	called on standard input

toonn@terra ~> set PAGER less
toonn@terra ~> echo $PAGER
less
toonn@terra ~> history
echo $PAGER
set PAGER less
env PAGER=less history # <- this didn't work because history's a function probably
```

Pinging @aanderse and @adisbladis who ran into the same issue.

**Comment by adisbladis** [comment]
I can reliably reproduce the issue when setting env vars in bash and sourcing them with fish-foreign-env.
I _think_ the issue lies in how fish-foreign-env cannot expand "less -R" to a fish array.

**Comment by faho** [comment]
>I think the issue lies in how fish-foreign-env cannot expand "less -R" to a fish array.

Indeed. It'll have to be fixed there.

**Comment by toonn** [comment]
@faho, I'm not sure what you mean by "there?" Are you referring to ["plugin-foreign-env"](https://github.com/oh-my-fish/plugin-foreign-env)? I don't have that installed.

**Comment by faho** [comment]
@toonn: For you, something did the equivalent of `set PAGER "less -R"`, which won't work.

For @adisbladis, that something was apparently the foreign-env plugin.

There's really nothing we can do about that - the setting is wrong, it needs to be equivalent to `set PAGER less -R`.

**Comment by adisbladis** [comment]
@toonn Ahh. Since we were discussing this in `#nixos` I was under the impression that you were also using fish on NixOS, and the NixOS fish module is using fenv to source it's environment.

**Comment by toonn** [comment]
@adisbladis, I *am* using `programs.fish` from home-manager. But like I said, I can't find a trace of that plugin.

@faho, but it worked after running ` set PAGER less -R`, rather than break again because of that?

**Comment by adisbladis** [comment]
@toonn It's happening here https://github.com/rycee/home-manager/blob/601619660de5a86ae6eb95936b7bffc03227dbc2/modules/programs/fish.nix#L156

**Comment by faho** [comment]
>@faho, but it worked after running set PAGER less -R, rather than break again because of that?

Yes, because that's the correct setting. The wrong setting has it as one element `"less -R"`.

**Comment by toonn** [comment]
@adisbladis, ah yes, thanks for pointing it out.

@faho, ah the quotes are significant. Thank you! Taking this to the `plugin-foreign-env` repository.
