### ISSUE TITLE
Status for Pipefail?

### ISSUE THREAD

**Issue by 58bits** [fish-shell/fish-shell#5997]
fish, version 3.0.2   

I've been reading the threads here - https://github.com/fish-shell/fish-shell/issues/2039  and here https://github.com/fish-shell/fish-shell/pull/5632 - but $pipestatus seems to have been removed from fish. I cannot find any reference in the tutorial or man pages.

I'm trying to test the following - specifically if the mysqldump command fails...

`mysqldump -uroot -p -h 127.0.0.1 database_name | gzip > "$filename"`

Something like 

```
if mysqldump -uroot -p -h 127.0.0.1 recoftc_dev | gzip > "$filename"
    #we're good
else
   #we failed
end
```

...and had thought that something like $pipestatus[1] might help.

Is there another, or preferred way to do this in fish?

**Comment by faho** [comment]
It's in the upcoming 3.1 release.
