### ISSUE TITLE
buggy repaints in paging applications with colorized text

### ISSUE THREAD

**Issue by skivvies** [fish-shell/fish-shell#600]
At a certain point while I'm using fish, something will screw up its repainting while I'm using paging applications like less and vim with colorized text. Here's a screwed up session next to a fresh one:

![Screen Shot 2013-02-26 at 5 08 27 PM](https://f.cloud.github.com/assets/475147/198626/e41b428e-8061-11e2-9a97-93d4b82798b0.png)

While displaying the less buffer, the screwed up fish session doesn't paint all the text correctly. It repaints it incorrectly in a different way every time I scroll.

I'm on OS X 10.8.2 running fish from homebrew's HEAD formula built on 2013-02-19.

**Comment by c02y** [comment]
> Slick! Here's my fish port if anyone cares:
>
> 	    set -x LESS_TERMCAP_mb \e'[01;31m'       # begin blinking
> 	    set -x LESS_TERMCAP_md \e'[01;38;5;74m'  # begin bold
> 	    set -x LESS_TERMCAP_me \e'[0m'           # end mode
> 	    set -x LESS_TERMCAP_se \e'[0m'           # end standout-mode
> 	    set -x LESS_TERMCAP_so \e'[38;5;246m'   # begin standout-mode - info box
> 	    set -x LESS_TERMCAP_ue \e'[0m'           # end underline
> 	    set -x LESS_TERMCAP_us \e'[04;38;5;146m' # begin underline

If you are using Fedora, this is not working unless you add `set -x GROFF_NO_SGR yes` in your `conf.fish` file.

**Comment by pickfire** [comment]
> Slick! Here's my fish port if anyone cares:
>
>      set -x LESS_TERMCAP_mb \e'[01;31m'       # begin blinking
>      set -x LESS_TERMCAP_md \e'[01;38;5;74m'  # begin bold
>      set -x LESS_TERMCAP_me \e'[0m'           # end mode
>      set -x LESS_TERMCAP_se \e'[0m'           # end standout-mode
>      set -x LESS_TERMCAP_so \e'[38;5;246m'   # begin standout-mode - info box
>      set -x LESS_TERMCAP_ue \e'[0m'           # end underline
>      set -x LESS_TERMCAP_us \e'[04;38;5;146m' # begin underline

That seems a bit hard to read, what about:
```
export LESS_TERMCAP_mb=$'\E[01;31m'      # Begins blinking.
export LESS_TERMCAP_md=$'\E[01;31m'      # Begins bold.
export LESS_TERMCAP_me=$'\E[0m'          # Ends mode.
export LESS_TERMCAP_se=$'\E[0m'          # Ends standout-mode.
export LESS_TERMCAP_so=$'\E[00;47;30m'   # Begins standout-mode.
export LESS_TERMCAP_ue=$'\E[0m'          # Ends underline.
export LESS_TERMCAP_us=$'\E[01;32m'      # Begins underline.
```

**Comment by c02y** [comment]
> @pickfire
> That seems a bit hard to read, what about:
> 
> export LESS_TERMCAP_mb=$'\E[01;31m'      # Begins blinking.
> export LESS_TERMCAP_md=$'\E[01;31m'      # Begins bold.
> export LESS_TERMCAP_me=$'\E[0m'          # Ends mode.
> export LESS_TERMCAP_se=$'\E[0m'          # Ends standout-mode.
> export LESS_TERMCAP_so=$'\E[00;47;30m'   # Begins standout-mode.
> export LESS_TERMCAP_ue=$'\E[0m'          # Ends underline.
> export LESS_TERMCAP_us=$'\E[01;32m'      # Begins underline.

You better convert it to fish-shell style, so if people want to try yours they don't have to do extra work.

And try my configuration, I personally think this is better:

    set -gx LESS_TERMCAP_so \e'[01;44m'          # begin standout-mode – info
    set -gx LESS_TERMCAP_mb \e'[01;31m'         # enter blinking mode
    set -gx LESS_TERMCAP_md \e'[01;38;5;75m' # enter double-bright mode
    set -gx LESS_TERMCAP_me \e'[0m'                # turn off all appearance modes (mb, md, so, us)
    set -gx LESS_TERMCAP_se \e'[0m'                 # leave standout mode
    set -gx LESS_TERMCAP_ue \e'[0m'                 # leave underline mode
    set -gx LESS_TERMCAP_us \e'[04;38;5;200m' # enter underline mode

**Comment by faho** [comment]
It seems nobody can actually reproduce this and I don't get how it's supposed to be triggered by fish, so I'm closing this.
