### ISSUE TITLE
Inconsistent Emoji Spacing

### ISSUE THREAD

**Issue by mbabatunde** [fish-shell/fish-shell#6004]
## Issue
Hi,
I'm currently setting up my `config.fish` and recently ran into an issue with certain emojis. I created a simple function to reload the shell as shown below. 

However, whenever I run `reload` the spacing between the emojis is not consistent. I've seen 
a previous issue talk about this (#2652) and I thought it was handled in `3.0.x` versions, but I'm not sure if it works for all emojis. Are there any workarounds to this issue?

## Function
```fish
function reload
    echo ⚒Loading...
    source ~/.config/fish/config.fish
    echo ✅Done
end
```

## Result
<img width="191" alt="Screen Shot 2019-07-24 at 12 52 06 AM" src="https://user-images.githubusercontent.com/21072448/61766094-ade62780-adad-11e9-92c6-43b01ac660fb.png">

## Details
```fish
$ fish --version
fish, version 3.0.2
$ echo $TERM
xterm-256color
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132
```

**Comment by faho** [comment]
I'm afraid fish has no influence on how your terminal renders things.

**Comment by mbabatunde** [comment]
@faho So this is an iTerm issue and not a fish issue, correct?

**Comment by faho** [comment]
If it's about how things look, it's a terminal issue, yes.

**Comment by mbabatunde** [comment]
Thank you for your response!
