### ISSUE TITLE
Stash not shown in informative prompt

### ISSUE THREAD

**Issue by pe** [fish-shell/fish-shell#6006]
When I stash something the prompt doesn't show this.

Configuration should be correct
```shell
set __fish_git_prompt_show_informative_status
set __fish_git_prompt_showstashstate 'yes'
```

I think I've narrowed it down to this line: 
https://github.com/fish-shell/fish-shell/blob/822b53c67a70ff923ba0370d763e44532e2c4c44/share/functions/fish_git_prompt.fish#L552

```shell
> fish --version
fish, version 3.0.2
> set -l stashstate 0
> set -l stashfile ".git/logs/refs/stash"
> test -e "$stashfile" && echo $status
0
> set -q __fish_git_prompt_showstashstate; and echo $status
0
# -> the if's conditions are met
> count < $stashfile
0
# but count returns zero???
> cat $stashfile
0000000000000000000000000000000000000000 4655827d8dfb538017c0be911536ebc01e85ee03 Me <me@example.com> 1564036193 +0200	WIP on feature/spike: 186df4772009 WIP
```

But this is as far as I can get. Any Ideas how to fix this?

**Comment by pe** [comment]
I've done some further digging. @faho replaced wc with count in 18d7123ff4f2c5cdc37728b446d37c83e57492bf
```shell
> wc -l $stashfile | string match -r '\d+'
1
```

So before that change it worked.

**Comment by faho** [comment]
>> fish --version
fish, version 3.0.2

Yeah, that won't work. You're using a newer prompt than your fish version. Generally this works, but not in this case since the `count` builtin only learned to count from stdin in e7a964fdfad1ad2125902896b04dcce441f0c6ed.
