### ISSUE TITLE
fish_config throw error [unable to find utility "python3", not a developer tool or in PATH]

### ISSUE THREAD

**Issue by hanachan1026** [fish-shell/fish-shell#6013]
`fish --version 3.0.2`

`Darwin Kernel Version 19.0.0: Thu Jul 11 18:37:36 PDT 2019; root:xnu-6153.0.59.141.4~1/RELEASE_X86_64 x86_64
MacOS Catalina beta4`

sh -c 'env HOME=$(mktemp -d) fish'
`Welcome to fish, the friendly interactive shell`

Tell us how to reproduce the problem. Including an asciinema.org recording is useful for problems that involve the visual display of fish output such as its prompt.

`fish_config`

**Comment by faho** [comment]
So `fish_config` starts our web config tool, which is written in python.

To do this, it checks for any command called `python3`, `python2` or simply `python` in $PATH and uses that to start the .py file.

That error is coming from your `python3` "command", which is seemingly just a stub. There is no way for us to detect it, so you need to fix it.

**Comment by hanachan1026** [comment]
OK, so I'll look into it. Thank you.
