### ISSUE TITLE
Bash history feature not working in fish like !10

### ISSUE THREAD

**Issue by kirankotari** [fish-shell/fish-shell#6015]
Fish: `version 3.0.2`
Operating System: `Darwin Kernel Version 17.7.0`

In the bash shell, I used to type history command and then `$!10`
to re-run the commands, which is not working in fish.!
Is there any workaround, please let us know?

**Comment by faho** [comment]
This feature is not included in fish on purpose.

If you wish to find a command in history, use other means like the up-arrow, which also allows you to search if you've typed anything before.

**Comment by kirankotari** [comment]
@faho is there any conflicts or drawbacks?

**Comment by ridiculousfish** [comment]
See #288
