### ISSUE TITLE
cannot set $PATH

### ISSUE THREAD

**Issue by markboston34** [fish-shell/fish-shell#6020]
fish --3..0.2
echo $version 3.0.2

i am using endeavoros which is based on arch. i am using konsole not sure which version whatever the latest is. 

i just installed fish so i have no 3rd party customizations. 

try to add a folder to path unable to do so.

i am trying to add a folder to my path ive used tons of commands each from the terminal and putting them in the config file. i get a unable to parse variable message no matter what command i use.

**Comment by exploide** [comment]
Maybe you messed up your variables?! Try to look at `~/.config/fish/fish_variables` and delete lines that were probably corrupted through your previous tries. If that does not work, I guess you can delete the entire file. Maybe also delete the config file you mentioned, you don't need it for setting your `PATH`. Not sure it's really necessary but better log out and log in again after you got rid of your broken customizations.

Now, that the environment is clean again:

```
set -U fish_user_paths /the/dir/you/want/to/add/to/path $fish_user_paths
```

The `fish_user_paths` variable is automatically prepended to `PATH`, so it is the most convenient way to add a directory to the `PATH`.

This is also documented here: https://fishshell.com/docs/current/tutorial.html#tut_path

**Comment by zanchey** [comment]
Can you please give us both the command you are using and the full error message?

**Comment by markboston34** [comment]
i deleted fish and switched back to bash.

**Comment by markboston34** [comment]
but judt for referance any command i typed even the one that the documentation says to use does not work

**Comment by faho** [comment]
@markboston34 Can you just give us the actual command and the error? Just literal copy and paste would do nicely.
