### ISSUE TITLE
Is there a way to get the FISH_SOURCE within a fish shell script?

### ISSUE THREAD

**Issue by bf4648** [fish-shell/fish-shell#6029]
Here's my info: 

```shell
fish --version
fish, version 3.0.2
```

```shell
uname -a
Darwin work 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
```
```shell
echo $TERM
xterm-256color
```

In bash I can do the following to get the full path of the present working directory of the bash script that I am working with: 

```shell
script_pwd=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
```
How do I do the same thing in a fish shell script?  Is there a FISH_SOURCE variable or something similar that I don't know about?

**Comment by faho** [comment]
`status current-filename`will print it, so you want

```fish
set script_pwd (status current-filename)
```

I don't think the `cd` is actually necessary - at most it should canonicalize the PWD, if you used `pwd -P` (also I believe getting "the script directory" is overused, but that's beside the point).

**Comment by bf4648** [comment]
@faho  That was really close to what I was wanting.  I wanted to be able to call a fish shell script from any directory and assign a variable to the full path of the currently executing script.  I had to use `realpath`. 
This is what works for me: 

```shell
set -l script_pwd (realpath (status current-filename))
echo "$script_pwd"
```

**Comment by kirankotari** [comment]
> @faho That was really close to what I was wanting. I wanted to be able to call a fish shell script from any directory and assign a variable to the full path of the currently executing script. I had to use `realpath`. This is what works for me:
> 
> ```shell
> set -l scriptDir (dirname (realpath (status current-filename)))
> echo "$scriptDir"
> ```

Small correction, `dirname` with `set -l` is not giving the folder directory instead it showing `dirname <script-path>` 
I have used `-x` option to make it working as expected.

**Comment by faho** [comment]
@kirankotari If you use `set -l`, that creates a variable that is *l*ocal to that block of fish script. It's not passed to external commands.

If you use set with the `-x` option, that e*x*ports the variable, passing it to any external commands as well.

Without `-l` the default scope at the top level of the script is global, so your variable will also be visible in any function you call.

I suggest you re-read fish's documentation, this isn't specific to getting the directory at all, and so it's not a "correction". You're doing something else wrong. I'm assuming you're calling a function and expect to be able to use the variable inside it, in which case `-l` will indeed prevent you from doing that.

**Comment by kirankotari** [comment]
When I read, I was blank because I understand same as you, but somehow the results are different for ‘dirname’. Maybe I might have said question then correction. 😂

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by faho** [comment]
> somehow the results are different for ‘dirname’

The difference between `set -l` and `set -x` is scoping and exporting. If `set -l` doesn't work for you but `set -x` does, then that's because your script has a scope bug.

If you run the actual code of the comment you replied to:

```fish
set -l scriptDir (dirname (realpath (status current-filename)))
echo "$scriptDir"
```

You'll see that it does print the script directory.

Since you haven't given the code you used we can't give a definitive answer, but two possible problems you might have:

```fish
begin # or if, or while, or for
    set -l scriptDir (dirname (realpath (status current-filename)))
end # <- this deletes the local variable defined above!
echo $scriptDir
```

or

```fish
set -l scriptDir (dirname (realpath (status current-filename)))

function print_script_dir
    echo $scriptDir
end

print_script_dir # won't have the local variable!
```

Both of these would be "fixed" by using `set -x` instead, because you're no longer defining a *local* variable.

But just sprinkling around options without understanding them won't really help you because you'll just keep running into problems.

**Comment by kirankotari** [comment]
> > somehow the results are different for ‘dirname’
> 
> The difference between `set -l` and `set -x` is scoping and exporting. If `set -l` doesn't work for you but `set -x` does, then that's because your script has a scope bug.
> 
> If you run the actual code of the comment you replied to:
> 
> ```fish
> set -l scriptDir (dirname (realpath (status current-filename)))
> echo "$scriptDir"
> ```
> 
> You'll see that it does print the script directory.
> 
> Since you haven't given the code you used we can't give a definitive answer, but two possible problems you might have:
> 
> ```fish
> begin # or if, or while, or for
>     set -l scriptDir (dirname (realpath (status current-filename)))
> end # <- this deletes the local variable defined above!
> echo $scriptDir
> ```
> 
> or
> 
> ```fish
> set -l scriptDir (dirname (realpath (status current-filename)))
> 
> function print_script_dir
>     echo $scriptDir
> end
> 
> print_script_dir # won't have the local variable!
> ```
> 
> Both of these would be "fixed" by using `set -x` instead, because you're no longer defining a _local_ variable.
> 
> But just sprinkling around options without understanding them won't really help you because you'll just keep running into problems.

@faho Thanks a lot for you explanation and the time. I understood what went wrong in my case.
