### ISSUE TITLE
fish_user_paths, prepend vs append and security

### ISSUE THREAD

**Issue by markstos** [fish-shell/fish-shell#6040]
`$fish_user_paths` is recommended as a way to augment $PATH.

The documented behavior is that `$fish_user_paths` will be prepended to `$PATH`. Thus, it will be searched first and override any binaries of the same name found in $PATH. 

This is useful if you want to override a system binary with a private copy.

However, the prepend approach is also a security risk.

For example, say `./node_modules/.bin` is added in to `$fish_user_paths`.  Now any binary distributed by NPM will be added to your path when an NPM module is installed.  If there's a malicious dependency in the NPM dependency tree, it could install a binary with the same name as  system binary, overriding an important system function. 

Besides security, this could also be a vector for confusion if bug if system binaries start exhibiting different behavior. 

A safer default behavior would be to  *append* to $PATH. If Fish users actually intend to override binaries, it could be worth handling that separately so users are opting into the security risk more explicitly.

The NPM ecosystem uses an alternate way to handle this.  Using `npx` is recommended to run local, NPM-specific binaries. By using `npx some-binary`, you are explicitly asking for the local NPM search path to be checked, but all the other binaries that might have come from NPM aren't persistently added to $PATH.  I like that approach OK, but there are still a number of other source repos that encourage users to "just add directory to your path". There's often not a disclosure that the extra path could be used to override system binaries.

As a defense-in-depth measure, I recommend Fish take the secure-by-default approach of *appending* `$fish_user_paths` to the system path rather than *prepending*.

**Comment by faho** [comment]
>However, the prepend approach is also a security risk.

It is not. The user decided to add it. The user could also modify $PATH.

> If there's a malicious dependency in the NPM dependency tree, it could install a binary with the same name as system binary, overriding an important system function.

If there is a malicious dependency in the NPM dependency tree, you have already lost. Presumably you'd execute it at some point anyway.

>As a defense-in-depth measure, I recommend Fish take the secure-by-default approach of appending $fish_user_paths to the system path rather than prepending.

Sorry, but no. That makes $fish_user_paths much less useful.

**Comment by markstos** [comment]
Thanks for the swift response anyway. 👍
