### ISSUE TITLE
Add shell completions for new git commands

### ISSUE THREAD

**Issue by tony-sunny** [fish-shell/fish-shell#6045]
### Fish version

3.0.2

Git 2.23.0 added new commands `restore` and `switch` which separates the duty for `checkout` command (https://github.blog/2019-08-16-highlights-from-git-2-23/#experimental-alternatives-for-git-checkout)

It'd be nice if someone can add shell completions for these two commands

**Comment by axionl** [comment]
I personally have a temporary solution to this problem and expect official support.

https://gist.github.com/axionl/1b038aeebd26dd8584558460204942fc

**Comment by zanchey** [comment]
Fixed with #6047 though completing the remaining options is left as an exercise.
