### ISSUE TITLE
Use pbcopy instead of xsel on Mac OS X

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#605]
I don't know how desirable this is - I don't really use the xsel integration - but setting `FISH_CLIPBOARD_CMD` to `pbcopy` will provide at least the copy functionality on OS X. `pbpaste` could also be used.

**Comment by krader1961** [comment]
Closing this as a dup of issue #2894. I'm going to kill this "feature". If anyone thinks a fish_clipboard function (akin to fish_title) is a good idea I ask that a new enhancement request be opened with a suitable argument for its addition. Please provide scenarios illustrating why this would be useful and how such a function might be used in key bindings.
