### ISSUE TITLE
Inconsistent job ids

### ISSUE THREAD

**Issue by horst5000** [fish-shell/fish-shell#6053]
I must admit that the job handling is very weird in fish, since the job id seems to be pretty random. Quick example, where I start different tools in the prescribed order and send them to background (`ccmake, nano, man gcc, vim, vi` where vi is an alias to `nvim -O`). The output of jobs is extremely unexpected, since `man gcc` will receive jobid 5 instead of 3. `vim` started as fourth tool will receive 4. The `nvim` alias started last will receive 7.

```
jobs
Job     Group   CPU     State   Command
7       30462   0%      stopped nvim  $argv
4       30393   0%      stopped vim
5       30348   0%      stopped command man $argv
2       30308   0%      stopped nano
1       30273   0%      stopped ccmake .
```
Or simply starting `man gcc` and then `vim` results in job 1 and 2 not even being present
```
Job     Group   CPU     State   Command
4       1716    0%      stopped nvim  $argv
3       1660    0%      stopped command man $argv
```
In short, the job ids are not consecutive, which is weird, but even worse they are not even monotonically increasing. This effectively makes the use of commands using these ids such as `fg/bg %id` trial and error and significantly less useful compared to most other shells.

fish version: 3.0.2
Sys: Ubuntu 18.04

**Comment by zanchey** [comment]
Can I ask what you expect to be able to do with the job numbers? Is it that the highest number is always the most recent job? Or that the "fifth job I backgrounded" is always job 5?

The actual ID of the job, at least in fish, is an implementation detail - at present it picks the lowest ID possible at the time of job creation.

**Comment by horst5000** [comment]
In bash or zsh the jobs will simply be numbered in consecutive order. The highest number is the most recent job started. If I launch `prog1, prog2, prog3, ..., progN` in this order the job ids will be `1,2,3,...,N`, no matter if running, suspended or backgrounded. It's essentially a stack, so closing a program in between will not change the other ids.

If I have a single job running in background and start a second one, I know that I can always access the first by `fg 1` and the second by `fg 2`, without having to think about the id (I typically have at most 2 or 3 jobs running at once).
In fish the first job may receive id 3 the second 2, the third 4 (see above example). Thus if you have more than one job where `fg` simply works, you always have to look up the id first using `jobs` before you can use `fg`/`bg`.

**Comment by zanchey** [comment]
I think that's probably reasonable to expect.

**Comment by ridiculousfish** [comment]
This is probably because some of these are functions. For example `man` is a function that wraps the command, so running `man` will effectively spawn two jobs. I didn't appreciate (until now) a reason to not assign a job ID to a function.

**Comment by horst5000** [comment]
This would explain the gaps within the ids but not why they do not increase monotonically. However, without gaps they probably would increase monotonically.

**Comment by zanchey** [comment]
They don't increase monotonically because the code always picks the lowest available job ID.

**Comment by mqudsi** [comment]
> This is probably because some of these are functions. For example `man` is a function that wraps the command, so running `man` will effectively spawn two jobs. I didn't appreciate (until now) a reason to not assign a job ID to a function.

Well, the issue isn't that functions are assigned a job id, it's that functions are jobs in the first place. `bash` treats functions as source code, and doesn't assign them a job before executing them, so they don't get a job id. The fish parser creates a new job for each and every function call (which has caused us a serious amount of headaches dealing with job control), but since it does that, it doesn't make sense *not* to give it a job id (e.g. make it an anonymous job).

**Comment by horst5000** [comment]
Before running into this issue I didn't even know about the details of the single shells' job systems.
Would it be an option to distinguish between internal job ids and user-facing job ids, e.g. giving internal jobs always a negative id and user-facing a positive one? This may solve the issue.
Furthermore, remember that my primary intention was not to completely change the job system, but to be able to use commands like fg / bg on user-facing jobs in a more straightforward way. If there's a simple solution to achieve this, I'd be fine with it.

**Comment by ridiculousfish** [comment]
I think where we'll end up is trying to match bash: if you run a single function (no pipeline) in the foreground (not background) then it will not be assigned a job id.

**Comment by danzimm** [comment]
For the sake of SEO: this is the issue I was looking for when searching for "alias creates extra job" or "function creates extra job". I have some spare time today (and this bugs me enough), so I'll see if I can take a stab at this issue.

**Comment by zanchey** [comment]
This is marked as fixed, but actually we've ended up with something different from the original request. The "monotonically" bit is fixed, but not the "increasing" - job identifiers are still reused (`sleep 10 &; sleep 20 &; sleep 30 &; jobs; kill %1; sleep 40 &; jobs` will demonstrate). I don't think that warrants holding 3.1.0 or backing out 8e17d29 but perhaps is worth considering further.

**Comment by ridiculousfish** [comment]
Assuming "monotonically increasing" means "larger than all currently running jobs," then this is easy to add.

**Comment by ridiculousfish** [comment]
In 1da09f2c525a55b0282d464d011e2cd4fdb9d7a3, new jobs always have a larger ID than any running job.

**Comment by horst5000** [comment]
Great work, looking forward to fish 3.1! Thanks a lot for these fixes!
