### ISSUE TITLE
"kubectl patch" command is not able to use .yaml  

### ISSUE THREAD

**Issue by vichaos** [fish-shell/fish-shell#6055]
Regarding to https://kubernetes.io/docs/tasks/run-application/update-api-object-kubectl-patch/ I'm not able use yaml to patch k8s resource via ```kubectl patch``` command

<img width="1600" alt="Screen Shot 2562-08-23 at 00 04 13" src="https://user-images.githubusercontent.com/724055/63535115-e444cd00-c53a-11e9-980b-34f32e8a54f8.png">

**Comment by zanchey** [comment]
This is because the command substitution splits the JSON/YAML on newlines, meaning you pass too many arguments.

Command substitutions don't work inside quotes in fish, so you'll need to use something like:

```fish
kubectl patch ... -p (cat some.yaml | string split0) ...
```

**Comment by zanchey** [comment]
Hopefully this answered the question.

**Comment by vichaos** [comment]
Thank you!
