### ISSUE TITLE
`math` incorrect parenthesis error on missing term

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#6063]
```fish
mqudsi@ZBOOK ~/r/fish-shell> math "(42 - )"
math: Error: Missing closing parenthesis
'(42 - )'
       ^
```

Obviously the closing parenthesis is there, the error should probably be something along the lines of "incomplete expression before closing parenthesis" or similar.

**Comment by 0x005c** [comment]
I found `math '()'` also cause the same error.
