### ISSUE TITLE
`kill-bigword` should affect *escaped* spaces

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#6064]
With the cursor at the marked position and the text in the terminal as follows:

```
~> f̲oo\ bar baz
```
executing `kill-bigword` should result in the following:
```
~> b̲az
```

Currently it results in

```
~>  ̲ bar baz
```

**Comment by lilyball** [comment]
I think there's a valid case for movement by space-delimited words independently of fish escaping. In particular, if I have a long quoted string, I might want to be able to move by bigwords within the string.

Also see #2014 that asks for separate bindings for killing arguments.

**Comment by faho** [comment]
Let's close this in favor of #2014.
