### ISSUE TITLE
Support some saner switches for `test`

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#6065]
I would like to add `-gte` and `-lte` as aliases for `-ge` and `-le` to `test` (even if undocumented).

**Comment by faho** [comment]
Blergh.

A single letter difference to still have a cryptic abbreviation does not seem good to me.

**Comment by mqudsi** [comment]
It's not so much to fix how cryptic it is so much as it is to make it compatible with other syntaxes.

**Comment by faho** [comment]
Which other syntaxes? I've not seen "-gte" anywhere, ever?

If this were actually much more understandable I'd be for it, but if you understand `-gte` you also understand `-ge`.

Also if e.g. you wanted to find all greater-or-equal comparisons you'd now have one more thing to grep for, it's one more thing to learn if you read someone's script, it's one more possible point of accidental incompatibility with old fish versions...

**Comment by floam** [comment]
I've accidentally tried `test ... -gte` before, but I'm not sure if that means there's a `[` out there that takes it.

**Comment by mqudsi** [comment]
Those are fair points. I didn't mean compatible with other `test` implementations but rather with other abbreviations. ColdFusion-inspired things use it, such as conditional comments in HTML, and it's used a lot in data query languages.

**Comment by floam** [comment]
Because I prefer in theory `-gte` over `-ge` and think the former is simply better, and because I've unsuccessfully tried stuff like `[ $foo -gte 3` only to be disappointed, I'm inclined to agree with doing this. However I don't think it's a great idea to have two such similar ways of doing the same thing, particularly when incompatible with POSIX `test`, for little gain.

This seems like a great place for a fishy error message that teaches.

```
$ test 3 -gte 5
test: unexpected argument '-gte': Use '-ge' for a greater-than or equal comparison
```

**Comment by faho** [comment]
>This seems like a great place for a fishy error message that teaches.

That sounds completely okay to me.

**Comment by faho** [comment]
Yeah let's go with a proper replacement for `test`, like zanchey's `is` (#6124), instead of putting lipstick on a pig.
