### ISSUE TITLE
Reserving <= and >= (and similar) literals

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#6066]
I would like to work on improving the usability of conditionals and `test` expressions by allowing the usage of "natural" expression operators rather than switches (it's supposed to be a friendly shell). To that end, I would like to special case certain symbols and operators from being treated as possible paths/filenames.

I am proposing that `<=` never be considered "read from a file called `=`" and `>=` never be considered "write to a file called `=`". Aside from the fact that if someone is actually intending to create files called `=` or `!` or similar they quite rightly deserve to have their code broken (and they can use `>"="` or perhaps `> =` with a space in between if they really want to), and apart from enabling us to support more natural expressions, I think it will only serve to make it possible for the shell to catch a class of errors that currently proceed with unintended "technically correct" results, making for a friendlier UX overall.

**Comment by faho** [comment]
We could reserve `<=`, but we could not reserve `< `. Which actually makes it more inconsistent?

**Comment by mqudsi** [comment]
Right. Obviously. Sorry.
