### ISSUE TITLE
check whether current command line contains a specific argument in complete

### ISSUE THREAD

**Issue by Neboer** [fish-shell/fish-shell#6068]
fish version 3.0.2

I am confused about how to check whether the current command line already has a specific argument in fish complete script. I have tried using `__fish_contains_opt` but it always return 1 and I don't know how to make it work; after this, I tried to use `-n 'contains myarg in $argv'` in my complete script but it also always return false. In fact, I can't get the current command line through anything in my complete script, this confused me a lot. 

Can anyone help me to understand how to refer the current command line arguments in fish?

**Comment by krobelus** [comment]
`$argv` is set only when executing the commandline. For completions you'll want to inspect the current state of the commandline with `commandline`.

**Comment by Neboer** [comment]
Thank you for asking my question, and it works. I'm sorry for starting a question here and now the issue will be closed.
