### ISSUE TITLE
trap fails

### ISSUE THREAD

**Issue by dmilith** [fish-shell/fish-shell#607]
http://dmilith.verknowsys.com/Public/Sshots/s04-13:37:26.jpg

**Comment by birnam** [comment]
I've been able to trap more complex commands by escaping the space. e.g. `trap "ls\ -la"`

**Comment by dremelofdeath** [comment]
@dideler (and others who may care...) For what it's worth, I have been able to avoid using pushd/popd in my fish scripts by using a subshell:

    if not fish -c "cd ~/Music; your_command_here"
      return
    end

It works with Ctrl-C and keeps all the directory traversal stuff neatly in a different space, preserving nextd/prevd as well.

**Comment by krader1961** [comment]
I'm closing this because the link in the original problem statement no longer works so I can't figure out what the problem was. Also, doing `trap 'ls -la' INT` on macOS and typing [ctrl-C] works as expected. So that works now.
