### ISSUE TITLE
The default behavior of `history delete` doesn't match the official document

### ISSUE THREAD

**Issue by nekotokurasu11** [fish-shell/fish-shell#6070]
According to https://fishshell.com/docs/current/commands.html#history, the behavior of `history delete` is explained as follows.

- delete deletes history items.　Without the --prefix or --contains options, the exact match of the specified text will be deleted.
- -e or --exact searches or deletes items in the history that exactly match the specified text string. This is the default for the delete subcommand.

From my understanding, the default option of `history delete` is `-e or --exact`.
However, `history delete` actually behaves as `history delete --contains`.

File : fish-shell/share/functions/history.fish
Line : 112
https://github.com/fish-shell/fish-shell/blob/af4b54e63567906f51b777ba6118b49686e22f6e/share/functions/history.fish#L112

I propose the following changes.
```
and set search_mode "--exact"
```

( I understand that it is similar to #3270.
Certainly, the fixed script of 2f3b842 is `and set search_mode "--exact"`.
However, In f490b56 , it was `and set search_mode "--contains"`. )

**Comment by zanchey** [comment]
Wow, that's amazing detective work. Thanks! I think this was probably an oversight at the time - a reminder about the usefulness of `git show` before pushing a commit, perhaps.

**Comment by rien333** [comment]
`history delete foo` doesn't work for me anymore, likely due to this commit. Irregardless of the search term, it now outputs:
```fish
> history delete foo
builtin history delete --exact requires --case-sensitive
```

Is this intentional? If not, I could open up a new issue. If it is, it's kinda annoying to be required to provide the history command with some extra options.

**Comment by zanchey** [comment]
Thanks, should be fixed now.
