### ISSUE TITLE
Git command completion

### ISSUE THREAD

**Issue by GuillaumeLescure** [fish-shell/fish-shell#6073]
Hi,

I recently moved to Fish and I first want to say : "It's a really amazing shell ! Thanks :smile: "

But I quicky note that git commands are not totally supported by autocompletion.
For example :

`$ git g<TAB>`
should propose `git gui`
`$ git fetch --a<TAB>`
should propose `git fetch --all`

Did I miss something or is it a bug ?

---
My setup :
* fish, version 3.0.2
* Manjaro GNU/Linux 4.19.66-1 x86_64
* Konsole 19.04.3
* xterm-256color

**Comment by zanchey** [comment]
The completions are not, uh, complete - especially for sprawling interfaces like Git. If you would like to help to add some, take a look in `share/completions/git.fish` in the source.

**Comment by charego** [comment]
I'll try to add completions for [git-restore](https://git-scm.com/docs/git-switch/2.23.0) and [git-switch](https://git-scm.com/docs/git-switch/2.23.0).

[Experimental alternatives for git checkout](https://github.blog/2019-08-16-highlights-from-git-2-23/#experimental-alternatives-for-git-checkout)

**Comment by faho** [comment]
Sorry, already added in #6054 and #6047.

**Comment by faho** [comment]
(and let's close the issue because "add more stuff for git" is sooo open-ended with how much it has and adds that it's useless to keep as an open issue because we could keep it around forever)
