### ISSUE TITLE
fish_config won't exit, until I "force close" the Terminal.

### ISSUE THREAD

**Issue by mrillusi0n** [fish-shell/fish-shell#6077]
Fish Version: 3.0.2
OS: Mac OS X (10.7.5)

In addition to that, I don't see the built-in prompts, and the navigation of the config page is buggy, because I can't see the changes happening as I switch between tabs (prompts, functions, variables,...)

**Comment by zanchey** [comment]
Which browser are you using? Is there any output on the terminal?

**Comment by mrillusi0n** [comment]
> Which browser are you using? Is there any output on the terminal?

No output on the terminal, add to that, I could not even quit the config task by pressing Enter/Return. I had to force-quit it by ^C.

As for Chrome, the latest version supported by the OS was being used. Unfortunately, I no longer have that environment and won't be able to provide more info. Hence closing the issue.
