### ISSUE TITLE
Can't find package in path (global install from yarn)

### ISSUE THREAD

**Issue by mtjn** [fish-shell/fish-shell#6078]
Trying to run the command `nlf`.

Installed using yarn: `yarn global add nlf`
Location: `/home/USER/.yarn/bin/nlf`

Node version is set by NVM. NVM is managed with [nvm-fast-fish](https://github.com/brigand/fast-nvm-fish)

**Output of `echo $PATH`**
`/home/USER/.nvm/versions/node/v12.9.1/bin /usr/local/bin /usr/bin /bin /usr/games`

**Output of `echo $fish_user_paths`**
`/home/USER/.nvm/versions/node/v12.9.1/bin /home/USER/.yarn/bin /home/USER/local/bin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /snap/bin`

**Env info**
Fish version: `3.0.2`
System info: `Linux COMPUTERNAME 5.0.0-25-generic #26-Ubuntu SMP Thu Aug 1 12:04:58 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
Terminal: `xterm-256color`

**Did problem still occur after disabling customizations?**
Yes

**How to reproduce**
I tried to reproduce in a docker environment, but wasn't able to reproduce the error quickly

Using `buildpack-deps:disco-curl` (didn't install sudo)

```
apt-get install software-properties-common
apt-get install fish
apt-get update
apt-add-repository ppa:fish-shell/release-3
fish
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
yarn add global nlf
nlf
```

Maybe (?) because of the lack of sudo, yarn installed `nlf` into `/usr/local/bin` in this docker environment.

**Comment by zanchey** [comment]
`/home/USER/.yarn/bin/nlf` is not in `$PATH`. Are you setting `$PATH` directly at any point? Doing so will wipe out any changes imported from `fish_user_paths`.

**Comment by faho** [comment]
There's not been any activity in a while, closing.

**Comment by mtjn** [comment]
Sorry for the slow reply. I think the problem may have been related to incorrectly setting `fish_user_paths`. I was setting it with the paths as a string like this:

`set -U fish_user_paths "path/1 path/2 path/3" $fish_user_paths`

Even though `echo $PATH` and `echo $fish_user_paths` still seemed to show a valid list of separate paths, the paths appended via `fish_user_paths` weren't being recognised by fish when searching for binaries.

Using `set -U fish_user_paths path/1 path/2 path/3 $fish_user_paths` seems to have resolved the issue
