### ISSUE TITLE
Build failures on OSX Mojave/clang9

### ISSUE THREAD

**Issue by talios** [fish-shell/fish-shell#6079]
Most recently tried with commit `753f49dba9b207`, running:

```
cd build
cmake ..
make
```

fails to build on OSX Mojave with:

```
[  2%] Built target CHECK-FISH-BUILD-VERSION-FILE
[  2%] Built target build_fish_pc
[  2%] Building CXX object CMakeFiles/fishlib.dir/src/autoload.cpp.o
In file included from /Users/amrk/Dropbox/fish-shell/src/autoload.cpp:4:
In file included from /Users/amrk/Dropbox/fish-shell/src/autoload.h:7:
In file included from /Users/amrk/Dropbox/fish-shell/src/common.h:6:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/errno.h:32:15: fatal error: 'errno.h' file not found
#include_next <errno.h>
              ^~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/fishlib.dir/src/autoload.cpp.o] Error 1
make[1]: *** [CMakeFiles/fishlib.dir/all] Error 2
```

Googling shows this appears to be a common issue with clang9's stdlib, and possible resolved in a similar manner to https://github.com/sakra/cotire/issues/139#issuecomment-373424917.

**Comment by zanchey** [comment]
Do any of the solutions listed at https://stackoverflow.com/a/52530212/125549 work for you?

**Comment by ridiculousfish** [comment]
Also try `sudo xcode-select --install`

**Comment by talios** [comment]
Running `open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
` seemed to solve the problem.

Command line tools were already installed and working fine for other things. Silly apple.
