### ISSUE TITLE
Fish is still running in the background process

### ISSUE THREAD

**Issue by donnisnoni95** [fish-shell/fish-shell#6081]
#### INFO
Fish Version: `3.0.2`
OS Info:
```
Linux DEV 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
More System Info: https://termbin.com/mlt0

Terminal Info: `xterm-256color`
Terminal Emulator: `gnome-terminal`

#### Step To Reproduce:
every time I close the terminal, the fish seems to be still running. and this will be repeated. I mean 3x I exit the terminal, then 3x also fish is still running.

#### GIF
![](https://images2.imgbox.com/4e/f6/9TDglPca_o.gif)

**Comment by ridiculousfish** [comment]
What's supposed to happen here is that when you close the window, the terminal emulator sends SIGHUP which causes fish to exit.

**Comment by donnisnoni95** [comment]
@ridiculousfish Then how it can't be closed ??

**Comment by ridiculousfish** [comment]
I'll try to reproduce.

**Comment by donnisnoni95** [comment]
@ridiculousfish Nice.... Thank you very much :smiley:

**Comment by zanchey** [comment]
It would be interesting to see what the process tree looks like before and after you close the terminal - something like `ps -o pid,ppid,user,args (pgrep fish)`. If you have `pstree` installed, that's useful too - `pstree -pgs fishPID`, where _fishPID_ is the still-running fish instance.

I see there has been trouble with gnome-terminal in the past: https://stackoverflow.com/questions/18002639/gnome-terminal-cmd-leaving-processes-open-after-closing-parent-window

**Comment by donnisnoni95** [comment]
Maybe that it's true ... if I have to try with another terminal to prove that this isn't the gnome-terminal cause ??

**Comment by ridiculousfish** [comment]
I wasn't able to reproduce on Ubuntu 18 with fish set as my shell. How are you launching fish? Is it your default shell or have you put something in .bashrc, etc?

**Comment by donnisnoni95** [comment]
Yes... i set it as my default shell.

![Fish Shell as default shell](https://i.imgur.com/OrdcdNO.png)

**Comment by mqudsi** [comment]
Good chance there's a dangling read/write operation from the theme or prompt. Have you tried with a clean fish configuration? (`env HOME=(mktemp -d) exec fish`)

**Comment by donnisnoni95** [comment]
@mqudsi Thank you very much bro !!! It works !!!

**Comment by mqudsi** [comment]
@donnisnoni95 glad it worked. For future reference and to help people searching github issues in the future, do you mind naming and shaming the theme or prompt that caused the problem?

Thank you.
