### ISSUE TITLE
File browsing in fish

### ISSUE THREAD

**Issue by user-b** [fish-shell/fish-shell#6082]
Hi. I have been using fish maybe for a year or two, totally happy with it (thanks!). But I'm still discovering some of it's features so this issue is maybe, more of a question.

_Short version: It's possible or could someday be possible to call fzf with custom params when doing `Ctrl-t` inside fish?_ 

I do use ranger for file browsing and recently discovered fzf. So now my question is about which method is better/faster to use by default when doing file browsing: Fzf inside ranger (inside a xmonad workspace exclusivelly dedicated to ranger) sometimes is not bad. By calling fzf with pre-configured --bind parameters it's possible to proccess the resulting file with any command. But still, you have to escape fzf to move upward in ranger. It's good for searching files inside a project folder but not for general file browsing.

In the other hand, there is the Ctrl+T shortcut in fish, which is awesome. But still for opening a file it's neccesary to use it in the old fashion like "emacsclient -n `<Ctrl+t>`  ..file.. `<CR>`". This has the inconvenience of having to decide the action before searching for the file, doing CR to confirm the (already selected) action and of course having to type the whole command. 

So I'm wondering if there is any faster approach to use fish as a file browser. One good solution would be to pass (user made) pre-configured --bind parameters to fzf when doing Ctrl+T. So opening files in emacsclient from fish would simply become "`<Ctrl+t>` ...file.. `<Ctrl+e>`"  where <Ctrl+e> is the fzf --bind param: `fzf --bind "ctrl-e:execute-silent(emacsclient -n {})"`. This way a dedicated file browser is not needed any more but I don't know if it's possible to accomplish this. And of course, any other approach to ultra-fast file browsing in fish is totally welcomed.

Sorry for the bad english and of course, many thanks!.

**Comment by ridiculousfish** [comment]
Thanks for filing!

fzf itself has a lot of configuration: `FZF_CTRL_T_COMMAND`, `FZF_CTRL_T_OPTS`, etc. I recommend starting there.

From the fish side, you can ask fish what the control-T binding is:

    > bind \ct 
    bind \ct fzf-file-widget

And you can see what the function is:

    > functions fzf-file-widget
    function fzf-file-widget --description 'List files and folders'
        ...

In terms of "choosing the file first", one technique is to use control-A:

1. control-T to select a file
2. control-A to go to beginning of line
3. Type the command you want

I've heard of ranger but haven't used it a lot so I can't comment. Hope that gives you some ideas where to start looking.

**Comment by user-b** [comment]
Excellent, FZF_CTRL_T_OPTS does the job.

> export FZF_CTRL_T_OPTS="--bind 'ctrl-p:toggle-preview,ctrl-e:execute-silent(emacsclient -n {})+abort' --preview-window=right:60%:hidden --preview 'bat --color=always {}'"


Still I think we are lacking a quick interactive hierarchical "inline" file/dir browser & dir changer, similar to nerd-tree (vim) or neo-tree (emacs) but working seamlessly with fzf in the shell. This would be much better than fzf + dedicated file manager or fzf + regular "cd" (and related) shell commands. Even better would be a hierarchical mode for the Ctrl+t command. But I know this does not relates very much to fish so i'll look somewhere. Thank you!

**Comment by ridiculousfish** [comment]
Yes I want to reimplement the pager to support streaming in completions, more advanced filtering, etc. A first step is to support concurrent execution of fish functions which is a big project. Anyways thanks for filing!
