### ISSUE TITLE
`string` hangs reading from fd 0 in nested interactive function call with piped input

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#6090]
With the following functions defined:
```fish
function __fish_filter_hosts
    string replace -rf '^\s*(?!(?:#|0|127)\.)\S+\s*(\S+)' '$1' <&0
end

function hang_fish
    getent hosts | __fish_filter_hosts
end
```

then attempting to run the calling function `hang_fish` in an interactive session:

```fish
mqudsi@Blitzkrieg /m/d/r/fish> source hang.fish
mqudsi@Blitzkrieg /m/d/r/fish> hang_fish


^C^C^C

^C^C^C^C^C


^Z
^Z
```

*Not visible is the `^D` attempted in between the `^C` and `^Z` to no avail.*

This is the same *scenario* as #5714 but it now fails in a much more ugly fashion, with the entire terminal hanging indefinitely and no way out besides killing the `fish` process externally. I *think* this is the same behavior fish exhibited in 2.x; in fish 3.0 (or at least leading to 3.0) it was "fixed" via one or more of the overhauls to job and fd management in the sense that it no longer hung indefinitely but rather attempted to read from `/dev/tty` instead (still incorrect behavior).

**Comment by ridiculousfish** [comment]
fish doesn't fork to execute functions, so when you pipe to a function it reads from the pipe's fd, not fd 0. My guess is there is no way to make this "work" without special casing fd 0, 1, and 2, which doesn't seem like a good idea either.

**Comment by faho** [comment]
I can no longer reproduce this.

With actual `getent hosts` it completes with $status of 1 and no output (I don't have a match), same thing with `cat /tmp/bigfile` (where bigfile is 100k lines long). Running `__fish_filter_hosts` is abortable with ctrl-d.

I'm assuming this is fixed.
