### ISSUE TITLE
`exec` incorrectly reports syntax error

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#6098]
When `exec` fails because the process cannot be found, the default command-not-found handler is automatically executed. However, fish also emits a blank syntax error message, pointing to the name of the process that can't be launched:

```
mqudsi@Blitzkrieg /m/d/r/fish> exec fg
fg: command not found
fish:
exec fg
     ^
```

I believe the output should simply be

```
~> exec fg
fg: command not found
~> 
```

**Comment by faho** [comment]
Fixed in master by 3534c07584fec4fc7d69842ce4dc32ca8c407f16.
