### ISSUE TITLE
Convert autogenerated sh script with env set to fish format

### ISSUE THREAD

**Issue by dmilith** [fish-shell/fish-shell#610]
I have .profile generated by my software which sets up my environment in zsh/sh.

Is there any way of "converting on the fly" of those env setup for fish?
It's one of missing features for me, cause I use software which generates sh scripts.

**Comment by krader1961** [comment]
Seems like this has been addressed. We support a bash compatible `export` command (and `setenv`). There is also the [bass](https://github.com/edc/bass) extension.
