### ISSUE TITLE
`echo` and `string repeat -n 0` not playing nicely with each other

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#6102]
Using https://github.com/fish-shell/fish-shell/commit/58cd1a5140c00c2a899811c3ad1b391cc6f69277

**Actual**
```
$ echo (string repeat -n 2 foo)bar
foofoobar

$ echo (string repeat -n 0 foo)bar

```

**Expected**
```
$ echo (string repeat -n 2 foo)bar
foofoobar

$ echo (string repeat -n 0 foo)bar
bar
```

**Comment by faho** [comment]
`string repeat -n 0` produces no output, so the cartesian product expands to nothing. This is as expected.
