### ISSUE TITLE
`jobs -l` seems to always return `1`

### ISSUE THREAD

**Issue by PhilLavoie** [fish-shell/fish-shell#6104]
## Environment

fish: 3.0.2
OS: Ubuntu 18.04

## Description

When using the `-l` switch with the `jobs` command, it seems that one always has a status code of `1`, regardless of if there is or isn't a background job.
I would expect it to be `0` when there is at least one background job, as described here: https://fishshell.com/docs/current/commands.html#jobs

## How to reproduce
```sh
> sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
> sleep 20 &
> jobs -l
Job	Group	CPU	State	Command
1	27183	0%	running	sleep 20 &
> echo $status 
1
```

**Comment by zanchey** [comment]
Yes, I see this in current master as well.
