### ISSUE TITLE
test --help emits no output

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#6114]
With the documentation built and installed, `test --help` emits no output and exits without any errors, setting `$status` to `0`.

**Comment by floam** [comment]
This is by design. `test $x` returns 0 if `x` is not empty. "`--help`" is not empty. It would break compatibility with POSIX test and existing uses in fish.

**Comment by floam** [comment]
Note that all of the switches `test` works on require another argument. `test -f` with no more arguments is not looking for file existence or reporting an error about a missing argument. It's returning 0 because `-f` is not empty.

**Comment by mqudsi** [comment]
Would it really break existing uses, though?

**Comment by faho** [comment]
Yes, it would.

`test` fundamentally sucks, let's not try to paint lipstick on a pig.

**Comment by faho** [comment]
In particular, `test` does not *support* `--`.

So because this necessitates a compatibility break, let's close this. Personally, I'd recommend looking for alternatives to test instead.
