### ISSUE TITLE
colon is escaped during completion with `scp`

### ISSUE THREAD

**Issue by melomac** [fish-shell/fish-shell#6115]
An issue with the `scp` command and completion was introduced during this commit: f7dac82ed601135754d0c65536f79d07d83e9fae

**Issue**

* input: `scp hostname.domain:`
* press the [tab] key for completion
* the input becomes: `scp hostname.domain\:`
* the remote host path completion no longer works

**Expected**

`:` isn't escaped and the remote host path completion works

**Notes**

Reverting commit f7dac82ed601135754d0c65536f79d07d83e9fae fix the issue.
Issue was found on macOS.

**Comment by krobelus** [comment]
Thank you, yeah this is causing some problems.
Maybe we can find a general solution, there are some ideas in https://github.com/fish-shell/fish-shell/pull/6099, or just revert.

**Comment by zanchey** [comment]
Fixed as 3ae12ac4d3b9.
