### ISSUE TITLE
macOS and Terminal: bullet char and new Tab

### ISSUE THREAD

**Issue by melomac** [fish-shell/fish-shell#6116]
**Description**

On macOS, in the Terminal application, opening a new Tab ends up with a bogus working directory path if the path contains the bullet character.

**Steps to reproduce**

* open Terminal application
* run the following commands:

```
$ mkdir /tmp/•test 
$ cd /tmp/•test/
$ pwd
/tmp/•test
```

* make sure the defaults preference _New tabs open with: Same Working Directory_ is active in the _General_ panel of the _Preferences_ window
* create a new Tab in the same window
* in the new Tab, `prompt_pwd` and `pwd` outputs are wrong:

```
$ pwd
/tmp/â¢test
```

* create another new Tab in the same window
* this time, macOS isn't able to set the working directory:

```
## cd /tmp/â¢test ##
```

**Comment by floam** [comment]
What version of fish? This works for me in git master. I think we fixed a problem with the url-escaping that was causing issues with non-ascii characters a while back.

**Comment by floam** [comment]
https://github.com/fish-shell/fish-shell/issues/5322

**Comment by melomac** [comment]
Thanks for your reply. As a matter of fact, and your response pointed me to the solution, it turns out this works fine when I enable "Set local environment variables at startup" advanced preference!

**Comment by floam** [comment]
Hm. Does it work in bash without Terminal setting the locale variables?

**Comment by faho** [comment]
Duplicate of #2613

**Comment by floam** [comment]
Ah.
