### ISSUE TITLE
Posix-like backquote escape within double quotes

### ISSUE THREAD

**Issue by lassik** [fish-shell/fish-shell#6117]
In fish, backslash escapes inside double-quotes work like Posix and traditional `/bin/sh` -- with one exception: the backquote as in

    echo "\`"

preserves the backslash character in the output string (which means that fish is not interpreting it as an escape sequence, but is instead preserving it verbatim).

Can the fish syntax still be changed at this point so that an escaped backquote within double-quotes outputs just the backquote without the escaping backslash?

This would mean that generic shell-quoting algorithms that produce double-quoted strings can use the Posix rules and people can also copy-paste the resulting command lines into fish with no changes.

[The relevant part of the Posix shell spec](https://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_02_03) is "Shell Command Language" section 2.2.3 "Double-Quotes".

I'm using fish version 3.0.2 from Homebrew.

**Comment by lassik** [comment]
Please note that generic quoting algorithms cannot simply leave out the backslash before a backquote. That's because most sh-derived shells interpret a non-escaped backquote as a magic sub-shell expansion character. There's no portable way to put a backquote inside double-quotes without using the backslash.

Forgoing double-quotes altogether and instead using single-quotes or barewords with backslash-escaping poses its own problems. Double-quotes are a pretty nice way to quote things save for the present problem.

**Comment by faho** [comment]
Sorry, but no. Fish isn't sh, and backticks aren't special to fish at all.

Pasting into fish isn't guaranteed to work in other ways as well, and the posix spec doesn't really matter to fish.

Changing this would be an annoyingly subtle backwards-incompatible change, and posix-script should ideally not be using backticks anyway, and the character is of very little use anyway.
