### ISSUE TITLE
omitted-newline string emitted after fish_prompt event

### ISSUE THREAD

**Issue by PerBothner** [fish-shell/fish-shell#6118]
One feature of "shell integration is to mark each command (input+output) with some kind of frame or [horizonal line between commands](http://per.bothner.com/blog/2019/shell-integration-proposal/).  It seems the cleanest way to do this is to use the fish_prompt and/or fish_postexec events to create the boxes.  (Using the fish_prompt function as opposed to the event has the problem is that the function may be re-evaluated and re-printed many times per command.)  However, this interferes awkwardly with the omitted-newline string that is printed to mark output that is not terminated by a newline.

The problem is that the omitted-newline string is printed *after* the fish_postexec event *and* after the fish_prompt event, which makes it logically part of the *next* command.  It would be better to print the omitted string *before* the fish_prompt event is emitted. 

I've attached on possible solution (omitted-newline.patch.txt).  I'll submit a pull request after I've given people a chance to comment.  I've also attached my current version of the shell-integration script (integration.txt), which depends on this patch.

[omitted-newline-patch.txt](https://github.com/fish-shell/fish-shell/files/3614384/omitted-newline-patch.txt)

[integration.txt](https://github.com/fish-shell/fish-shell/files/3614388/integration.txt)

**Comment by zanchey** [comment]
That seems like a reasonable change, though I'm not sure about the actual mechanics - why not submit a PR? Github's review tools are pretty useful.

**Comment by PerBothner** [comment]
I created a pull request #6148.  Sorry for the delay - I was working to stabilize the DomTerm  changes that benefit from this patch (plus one more coming soon).

To answer your question "why not submit a PR": For many workflows you're supposed to create an issue first, before creating a pull-request referring to the issue, and it wasn't clear to me it that applies to Fish. (I note the pull-request template asks for an issue number.  I also note you can't reference a not-yet-existing pull-request in a checkin, but you can reference an issue number.)

These are some of the negatives with the pull-request way of working.  Much better in my opinion if pull-requests were a sub-class of issue: You first create an issue, and then you associate a proposed solution (pull-request or patch) as part of the data associate with an issue, rather than have separate pull-requests.  But GitHub doesn't support that workflow very well.

**Comment by zanchey** [comment]
There was a push at one stage to always have issues created before PRs; it's probably not a bad idea.

**Comment by ridiculousfish** [comment]
I merged the PR. Thank you!
