### ISSUE TITLE
Interpolate functions when expanding abbreviations.

### ISSUE THREAD

**Issue by caillou** [fish-shell/fish-shell#6119]
Given the following abbreviation:

```fish
abbr -a ggl 'git pull origin (git_branch_name)'
```

I would expect the abbreviation to be expanded as follows:

```fish
git pull origin master
```

Instead, currently, it expands to `git pull origin (git_branch_name)`.

**Comment by zanchey** [comment]
To be clear, do you have `git_branch_name` defined as a function?

I think what you're asking for here is fundamentally #751 - the ability to expand a command substitution within the command line editor.

**Comment by caillou** [comment]
@zanchey Thanks for your quick answer.

Indeed, `git_branch_name` is a function, which I would like to expand/interpolate when the abbreviation is expanded.

```bash
$ ggl[SPACE]
# is expanded to
$ git pull origin (git_branch_name)
# but this is what I am looking for
$ git pull origin master
```

I tried to make sense of the discussion in #751, but I am not sure this is the exact same requirement.

**Comment by zanchey** [comment]
The linked issue talks about having a way to expand the substitution in-line (eg a hotkey or similar), although probably starting with non-command substitutions initially. As such, I'll close this as a duplicate (certainly I would not implement automatic expansion, as it's just too easy to have functions that have unintended side-effects).
