### ISSUE TITLE
Web interface does not accept functions for abbreviations.

### ISSUE THREAD

**Issue by caillou** [fish-shell/fish-shell#6120]
If I try to create the following abbreviation through the web interface, the `(git_branch_name)` part is stripped away:

```bash
abbr -a ggl 'git pull origin (git_branch_name)'
```

## Steps to reproduce

1. Open a new terminal and run `fish_config`.
2. Create the following abbreviation: `'git pull origin (git_branch_name)'`.
3. Reload the page.
4. The abbreviation looks as follows: `'git pull origin'` .

**Comment by ridiculousfish** [comment]
Weird, I can't reproduce! What is your test environment?

**Comment by zanchey** [comment]
Yes, this works for me on 22811ebc with Chrome 76 on macOS 10.13.6.

**Comment by faho** [comment]
Okay, I can reproduce with 3.0.2, the trick is to include the single-quotes - which seems like the correct thing to do, because that's how the others are presented on the web interface.

**Comment by faho** [comment]
Can reproduce with master. This is because fish_config runs `abbr --add 'ggl' ''git pull origin (git_branch_name)''` because it doesn't escape the input.

(note: You need to reload the tab to see the real result)

**Comment by faho** [comment]
Okay I just pushed 70fc261, which ends up ignoring all `'` surrounding the input.
