### ISSUE TITLE
set -U overwrite fish_variables

### ISSUE THREAD

**Issue by lra** [fish-shell/fish-shell#6121]
# Specs

```sh
$ fish --version 
fish, version 3.0.2

$ uname -a
Darwin mbp.lan 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64

# Also happens on Debian GNU/Linux

$ echo $TERM
xterm-256color
```

# Short version

Fish overwrite linked config files.

```sh
$ rm .config/fish/fish_variables
$ echo "# test" > linked_file
$ ln -s linked_file .config/fish/fish_variables

# Everything is fine
$ ls -l .config/fish/fish_variables
lrwxr-xr-x  1 analogue  staff  11 Sep 16 23:03 .config/fish/fish_variables -> linked_file

$ set -U a b
# Each time Fish updates the file, it overwrites the link
$ ls -l .config/fish/fish_variables
-rw-r--r--  1 analogue  staff  137 Sep 16 23:04 .config/fish/fish_variables
```

# Long version

I symlink my `.config/fish/fish_variables` in a folder that I share across computers using Mackup. You can see fish referenced here: https://github.com/lra/mackup/blob/master/mackup/applications/fish.cfg

The problem is that each time fish updates the `fish_variables` file, e.g. when doing `set -U abc def`, fish replaces the link with a regular file.

I'd expect fish to act as any other program and just write to the file the links points to, and not replace the link with a regular file.

A workaround is to not use `set -U` and set my env vars in `config.fish` but I don't understand why Fish does not play well with links.

Thanks for looking into this.

**Comment by zanchey** [comment]
This is because fish tries to write the file in an atomic way - by creating a new file, writing out the universal variables, then moving the new file over the old one.

To work around this, you could symlink the entire directory, or use a link in the other direction.

**Comment by zanchey** [comment]
I assume this has been answered.
