### ISSUE TITLE
Speed of the quoted vs unquoted fish shell script code

### ISSUE THREAD

**Issue by Anton-Latukha** [fish-shell/fish-shell#6128]
There seems to be a sense of extensive proper `'` and `"` quoting of everything, with a reason to make the script parsing more strict, and as such - unload parsing logic from the shell.

This, strict quoting to simplify parsing logic, was a serious reason to quote in `shell`-like interpreters, and was not even under question in them, when I was developing in them.

The quoting in `fish` has lesser speed impact, and as such a debatable question, but also a reasonable question.

### Example
```fish
quoted.fish

for i in (seq 10000)
  command -v 'emacs' > '/dev/null'
  printf "$HOME" > '/dev/null'
end
```

```fish
unquoted.fish

for i in (seq 10000)
  command -v emacs > /dev/null
  printf $HOME > /dev/null
end
```

<details><summary>Example results -> (spoiler):</summary>
<p>

```fish
time fish ./quoted.fish ; time fish ./unquoted.fish

# Trial #1

3.89user 3.41system 0:06.86elapsed 106%CPU (0avgtext+0avgdata 11764maxresident)k
0inputs+0outputs (0major+1205554minor)pagefaults 0swaps

4.18user 3.92system 0:07.61elapsed 106%CPU (0avgtext+0avgdata 11828maxresident)k
0inputs+0outputs (0major+1128927minor)pagefaults 0swaps

# Trial #2

4.77user 4.25system 0:08.43elapsed 107%CPU (0avgtext+0avgdata 11864maxresident)k
0inputs+0outputs (0major+1195554minor)pagefaults 0swaps

4.95user 4.95system 0:09.23elapsed 107%CPU (0avgtext+0avgdata 11732maxresident)k
0inputs+0outputs (0major+1108907minor)pagefaults 0swaps

# Trial #3

4.90user 4.84system 0:09.08elapsed 107%CPU (0avgtext+0avgdata 11508maxresident)k
0inputs+0outputs (0major+1203298minor)pagefaults 0swaps

5.01user 5.07system 0:09.41elapsed 107%CPU (0avgtext+0avgdata 11680maxresident)k
0inputs+0outputs (0major+1098883minor)pagefaults 0swaps

# Trial #4

4.20user 3.79system 0:07.56elapsed 105%CPU (0avgtext+0avgdata 11876maxresident)k
0inputs+0outputs (0major+1205562minor)pagefaults 0swaps

4.32user 4.10system 0:07.92elapsed 106%CPU (0avgtext+0avgdata 11540maxresident)k
0inputs+0outputs (0major+1173899minor)pagefaults 0swaps

```

</details>

---

##### Special case №1

Thou,
```fish
tooExtensiveQuoted.fish

for i in (seq 10000)
  'command' -v 'emacs' > '/dev/null'
  printf "$HOME" > '/dev/null'
end
````

is slower then the unquoted version. So:

```fish
'command' <args>
```

Is a currently a slow operation, when fish discerns that this quoted string is a execution directive.

##### Special case №2

```fish
effectivelyQuoted.fish

for i in (seq 10000)
  command -v 'emacs' > /dev/null
  printf "$HOME" > /dev/null
end
```

is currently faster then the `quoted.fish` version.

So:
```fish
command > /path/to/file

### seems to be, on the surface paradoxically, currently faster then 

command > '/path/to/file'
```

---

There is interest to get thoughts/response from developers about the question, and these special cases.

P.S.

I could asked in the chat.
Asking it here, so it would be very internet searchable for interested people, and easy to send to.

**Comment by Anton-Latukha** [comment]
I raise this questions, because effective quotation code style in projects and local configuration leads to faster and better terminal.

**Comment by faho** [comment]
Yeah, sorry, no, those results are completely dominated by any system usage differences. It's not that they're non-existent, but there's waaaaaaaaaaaayyyyyy more low-hanging fruit.

So there's no real point in handling this, so I'm closing. Sorry!

**Comment by Anton-Latukha** [comment]
I do not understand your response. I not asked to implement anything.

I am asking what is the proper effective quotation standard.

**Comment by Anton-Latukha** [comment]
I just researching how to quote effectively in fish shell, for example my `fish_prompt.fish` script, and I found no standard or documentation on that. 

And my empirical trials show that there is indeed seems to be a difference in speed, if to know how to quote properly.

**Comment by faho** [comment]
What I am saying is that there is no meaningful difference. Your measurements differ, but they differ more among runs than among quoted vs unquoted.

On my system that difference is even less (as the entire script takes ~1s, most likely because I'm on fish master, which has some performance improvements).

Any other change, e.g. removing a call to an external tool, either in favor of builtins or by doing more in a call, will absolutely entirely dominate this. E.g. try using `command printf` instead of `printf` and see how it's suddenly slower by 7x. Or just use `seq 4999; seq 5000 10000` and see how that *single* non-repeated call already makes the quoted script slower.

That means there is no use in caring about this. Quote like you want, it doesn't matter  (in case there is no expansion, of course). Personally I quote anything that "looks special", so "normal" words like `command` or `/dev/null` don't have to be, but that's a question of taste.

**Comment by Anton-Latukha** [comment]
Thank you from my heart. This response is amazing.

Can't wait for new release.
