### ISSUE TITLE
Slow startup

### ISSUE THREAD

**Issue by hasit** [fish-shell/fish-shell#6136]
```
~ $ fish --version
fish, version 3.0.2
~ $ uname -a
Darwin HASMISTR-M-33ST 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
```

Hello,

Recently, opening and new window/tab in iTerm2 using fish has gotten slower. It takes ~7s to login into shell and start fish. I have no idea what is causing this. Could someone help me with this issue?

**Comment by zanchey** [comment]
Does the slowdown occur if you start a new fish process within an existing window? If so, you can use `fish --profile profile.txt`, exit the new shell once it starts, then look in `profile.txt` to see what is taking so much time.

If you have any third-party customisations enabled (oh-my-fish, fisher, tacklebox etc.) you could try disabling those and see if that helps.

(This is an FAQ which should be added to the FAQ, cf https://github.com/fish-shell/fish-shell/issues/2854#issuecomment-329679685)

**Comment by hasit** [comment]
@zanchey,

The slowdown occurs whenever I open start a new windown/tab in my terminal. Here is the profile.txt file from your suggestion. 
[profile.txt](https://github.com/fish-shell/fish-shell/files/3648425/profile.txt)

I do not have any third-part customizations enabled.

**Comment by floam** [comment]
Does launching `fish` from within an already open window or tab like when you got that profile output have the same slowdown? If no, this could be slowness from `login` pouring over logs to cause the "Last login" output. `touch ~/.hushlogin` may fix it if that's the case.

**Comment by hasit** [comment]
@floam,

Launching `fish` from within an already open window is now slow. However, opening a new window or a tab is extremely slow. I ran `touch ~/.hushlogin`. It caused no change in the startup time.

**Comment by floam** [comment]
Okay, turns out `.huslogin` just causes the last login time not to be displayed but it doesn't speed up the asl logs. Deleting the logs or updating to a newer version of macOS may make it faster. See discussion here: https://apple.stackexchange.com/questions/41743/how-do-i-speed-up-new-terminal-tab-loading-time

**Comment by hasit** [comment]
Yeah. Looks like a slow login.

I made a symlink of `fish` called `fishln` and made a different profile to run `fishln` at startup, as suggested in the article mentioned above. Opening a new tab after that was very quick at startup. Now my question is, how do I speed up login?

**Comment by zanchey** [comment]
My new windows are often slow because `xcodebuild` is doing... something...

You could try changing the profile to a non-login shell as suggested in https://apple.stackexchange.com/a/195467/87344 (Command - change Login Shell to Command - set to `/usr/local/bin/fish`)

Otherwise I have no ideas.

**Comment by hasit** [comment]
@zanchey 

Followed what that article suggests and the start up is now significantly faster. I will close this issue for now. We can revive it if we find a better solution.

Thank you.

**Comment by erran** [comment]
In case this helps someone in the future:

My slow login was caused appending duplicate `fish_user_paths` on fish version 3.1.1. Remedying the situation was:

```fish
echo $fish_user_paths > fish_paths.txt

# NOTE: This will change the order so make sure the new paths are in the order you would like.
# Edit fish_paths.txt to be only unique entries in the order you need.
# In my case I used sort -u to get unique entries then re-ordered entries.
cat fish_paths.txt | sort -u

# If you're happy with that then set the actual value:
set fish_user_paths (cat fish_paths.txt)
```

The root cause was me appending via fish config. Conditionally appending the values prevents the duplicate paths being appended when opening new fish sessions.

```fish
# ~/.config/fish/config.fish
contains /usr/local/bin $fish_user_paths; or set -Ua fish_user_paths /usr/local/bin
contains /usr/local/opt/curl/bin $fish_user_paths; or set -Ua fish_user_paths /usr/local/opt/curl/bin
contains /usr/local/opt/qt/bin $fish_user_paths; or set -Ua fish_user_paths /usr/local/opt/qt/bin
contains /usr/local/opt/python@3.8/bin $fish_user_paths; or set -Ua fish_user_paths /usr/local/opt/python@3.8/bin
contains /usr/local/opt/helm@2/bin $fish_user_paths; or set -Ua fish_user_paths /usr/local/opt/helm@2/bin
contains ~/.rbenv/shims $fish_user_paths; or set -Ua fish_user_paths ~/.rbenv/shims
contains ~/.tfenv/bin $fish_user_paths; or set -Ua fish_user_paths ~/.tfenv/bin
contains ~/go/bin $fish_user_paths; or set -Ua fish_user_paths ~/go/bin
contains ~/.bin $fish_user_paths; or set -Ua fish_user_paths ~/.bin

```

**Comment by madprops** [comment]
The answer from @erran made me realize I had a lot of duplicates in fish_user_paths, which was causing the shell to be a bit slower (and my cpu to be a bit hotter). What I did was clear the list with `set -U fish_user_paths` and then reboot just in case.
