### ISSUE TITLE
Passing the cursor position to edit_command_buffer

### ISSUE THREAD

**Issue by rien333** [fish-shell/fish-shell#6138]
The `alt+e` bind to `edit_command_buffer` - that is, opening the current command in `$EDITOR` - is  very handy. However, often I only realize half way editing a command that using my `$EDITOR` would be more convenient. In such cases, it's pretty cumbersome and superfluous to navigate to where I had my cursor in the fish shell, before I started my `$EDITOR` session. 

Fortunately, editors like emacs (and maybe also vim) can be told to open a file at a specific line and column:
```bash
emacsclient --help
Usage: emacsclient [OPTIONS] FILE...
Tell the Emacs server to visit the specified files.
Every FILE can be either just a FILENAME or *[+LINE[:COLUMN]]* FILENAME.
```
Therefore, it would be great if `edit_command_buffer` could be told about the current cursor column (and possibly line). Afaik, there is currently no  good way to  pass such information to `edit_command_buffer`. I'm also not sure if it's possible to get the cursor's current column, and then pass that as some kind of argument to `edit_command_buffer`.

**Comment by zanchey** [comment]
So, there's `commandline --cursor`, which prints the offset from the origin of the line, which would work fine for the singe-line case. You could probably hack that into a lines/column thing in script, though my version is not terribly elegant:

```fish
function coord
    set -l offset (math (commandline --cursor ) + 1)
    set -l col 1
    set -l line 1
    set -l IFS
    set -l currpos 1
    set -l cmdline (commandline)
    while test $currpos -le $offset
        set -l curr (string sub --start $currpos --length 1 -- $cmdline)
        if test "$curr" = \n
            set line (math $line + 1)
            set col 0
        else
            set col (math $col + 1)
        end
        set currpos (math $currpos + 1)
    end
    echo $line:$col
end
```

Anyway, the output of the coord function can be passed along to `emacsclient`.

I don't think we're likely to change `edit_command_buffer`, because of the minimal support for the concept - happy to hear other ideas though.

**Comment by krobelus** [comment]
I think we can support passing the cursor position to some editors without breaking anyone. Most editors I can think of support some variation of `+line:col file` or `file:line:col`.

**Comment by rien333** [comment]
Certainly terminal editors (even nano, apparently).

**Comment by zanchey** [comment]
Switching on `$EDITOR` seems reasonable, though will probably have a lot of false negatives.

`ee`, `joe` and `vim` seem to only support line number, not column. At least for `vim` you can use a `-c` argument to move the cursor after starting.
