### ISSUE TITLE
为什么那么怎么长时间了还不发布新版本

### ISSUE THREAD

**Issue by eonun** [fish-shell/fish-shell#6141]
为什么那么怎么长时间了还不发布新版本？通过Linux包管理器安装的还是一直都是老版本，难道这么长时间还没出一个正式版的发布吗

(Google Translate: Why are you still not releasing a new version after a long time? Installed through the Linux package manager is still an old version, has it not been published for a long time?)

**Comment by zanchey** [comment]
What version do you have installed?

(您使用什么版本？ via Google Translate)

**Comment by akiirui** [comment]
Please check https://github.com/fish-shell/fish-shell/milestone/20

Version 3.1.0 coming soon. only 3 issues open, until this reply.

**Comment by faho** [comment]
Yeah, version 3.1.0 will come out when it's ready. If you want a newer fish than what you have, check the installation options on https://fishshell.com/. It is quite possible we have a PPA for your distribution so you can upgrade to 3.0.2.

That should answer the question, so I'm closing this issue.

**Comment by eonun** [comment]
fish, version 3.0.2   都半年那么长了都没新的正式版吗
