### ISSUE TITLE
Trigger function on command line input

### ISSUE THREAD

**Issue by BVollmerhaus** [fish-shell/fish-shell#6146]
I'm currently trying to write a function that analyzes the current command line text for things like character occurrences, length, etc. and outputs the result on the prompt (repainting it via `commandline -f repaint`). However, so far I've been unable to properly detect user input (from standard input, not key bindings) to trigger a custom function.

Is there a way to trigger a function on user input? If not, maybe it would make sense to add such an event to the `function` event handlers. I'm aware that this may lead to performance issues, but I'd like to see whether my implementation is possible at all.

**Comment by faho** [comment]
The easiest thing to do is to just bind the function to a key, and then press that.

There is currently no way to trigger a function on *any key* or *any kind of change to the commandline*.

**Comment by BVollmerhaus** [comment]
That's unfortunate, in that case I'll have to put my fish implementation on hold for now. It would be great if this could be implemented in a future release. I suppose it could *theoretically* be realized with an external script listening for X input events and sending a signal, but that would be about as hacky as it gets.

**Comment by BVollmerhaus** [comment]
That's unfortunate; in that case, I'll have to put my fish implementation on hold for now. It would be great if this could be implemented in a future release. I suppose it could *theoretically* be done with an external script listening for X input events and sending a signal, but that would be about as hacky as it gets.

**Comment by peey** [comment]
Somewhat related: like we can override `fish_prompt`, is it possible to put a script after command is entered by the user and before it's processed by fish?

**Comment by faho** [comment]
>Somewhat related: like we can override fish_prompt, is it possible to put a script after command is entered by the user and before it's processed by fish?

@peey I'm going to be honest, your question smacks of an XY-problem.

Most likely you want the fish_preexec event, to do "something" before the command is executed:

```fish
function dothing --on-event fish_preexec
    echo hello
end
```

(put in config.fish, not in a function file)

If not, you can rebind `\r` ("carriage return", what the return key sends) or other things that execute the "execute" bind function:

```fish
bind \r 'echo hello; commandline -f execute'
```

**Comment by peey** [comment]
@faho, thanks. That's good enough for what I wanted to do.

**Comment by faho** [comment]
Yeah, I don't see us doing this. The use case isn't clearly defined, the implementation tough and the impact would potentially be huge (run a function after every key press? Holy slowdowns, batman).

So I'm closing this. Sorry!
