### ISSUE TITLE
`function` takes invalid variable names for --argument-names

### ISSUE THREAD

**Issue by ammgws** [fish-shell/fish-shell#6147]
When running the following function,

```
function testscope
  set DEBUG 1

  function test1 --no-scope-shadowing --argument-names a b
    echo (status function)" debug=$DEBUG (args: $argv)"
  end

  function test2 --argument-names a b --no-scope-shadowing
    echo (status function)" debug=$DEBUG (args: $argv)"
  end

  function test3 --argument-names "a b" --no-scope-shadowing
    echo (status function)" debug=$DEBUG (args: $argv)"
  end

  set names "a b"
  function test4 --argument-names $names --no-scope-shadowing
    echo (status function)" debug=$DEBUG (args: $argv)"
  end

  test1 "foo" "bar"
  test2 "foo" "bar"
  test3 "foo" "bar"
  test4 "foo" "bar"
end
```

I get this output:
> test1 debug=1 (args: foo bar)
 test2 debug= (args: foo bar)
 test3 debug=1 (args: foo bar)
 test4 debug=1 (args: foo bar)

I take it this happens because REQUIRE_ORDER is used when parsing the flags [here](https://github.com/fish-shell/fish-shell/blob/508c3a800570ea91976af80f9b79150ec2e0239f/src/builtin_function.cpp#L38-L52)? 
> REQUIRE_ORDER means don't recognize them as options; stop option processing when the first non-option is seen. This is what Unix does. This mode of operation is selected by using `+' as the first character of the list of option characters.

Should this be documented in the docs for `function`, or does it go without saying?

**Comment by faho** [comment]
Well, no. This isn't using `REQUIRE_ORDER` specifically.

It's understanding `--no-scope-shadowing` as a name for a variable.

Which is awful because `$--no-scope-shadowing` can't be expanded as a variable (because `-` isn't actually valid in variable names!)

**Comment by faho** [comment]
Test-case:

```fish
function testfun --argument-names a b c --no-scope-shadowing
   set -l
end
```

Presumably this should error out.

**Comment by ohk2kt3t4** [comment]
Cheers. 

Just to check: `REQUIRE_ORDER` is needed so that `NAME` in `function NAME [OPTIONS]` keeps its position before `OPTIONS`, otherwise getopts will move to the end where it could become an arg to `--argument-names` if that was the last defined option?
