### ISSUE TITLE
Where does the $PATH get populated from?

### ISSUE THREAD

**Issue by in3rsha** [fish-shell/fish-shell#6151]
- fish, version 2.7.1
- Linux 5.0.0-25-generic #26~18.04.1-Ubuntu

I am trying to clear up my $PATH as it has a paths that I no longer need. I have cleared out any settings for the $PATH, but old paths keep getting populated in to it.

```
$ echo $fish_user_paths
(nothing)
```

```
cat .config/fish/config.fish
(nothing)
```

How can I clear my $PATH so I can start from fresh? It seems to keep getting populated and I don't know where it's coming from.

**Comment by faho** [comment]
The most likely culprit is your fish's parent process. $PATH is an environment variable that is typically inherited from e.g. your terminal.

It's possible `set --show PATH` and `set --show fish_user_paths` give you more information if e.g. you've set a universal $PATH as well and there's some weirdness there.

**Comment by in3rsha** [comment]
Thank you. It appears that these `$PATH` settings were set in my `.bashrc` and the fish shell is inheriting them from bash.
