### ISSUE TITLE
local-exported variables not correctly exported when another block is in-between

### ISSUE THREAD

**Issue by lilyball** [fish-shell/fish-shell#6153]
If I override `PATH` as a local variable, `type` respects this if the local scope is the current scope, but not if it's an enclosing scope.

For the following code, assume `/opt/brew/bin/brew` exists on disk but isn't in my normal `PATH`:

```
> type brew
type: Could not find 'brew'
> set -lxp PATH /opt/brew/bin
> type brew
brew is /opt/brew/bin/brew
> begin; type brew; end
type: Could not find 'brew'
```

I first ran into this when `eval type brew` didn't work but `type brew` did, which is explained by this bug as `eval` establishes a nested scope.

fish, version 3.0.2

**Comment by krobelus** [comment]
A similar example; the first invocation of `foo` sees x, the other one doesn't.
```fish
fish -c 'function foo; echo $x; end; set -lx x outer; foo; begin; foo; end'
```

I think this can be fixed without unintended side effects by defining `foo` (and `type`) with `--no-scope-shadowing`, however, the behavior without `--no-scope-shadowing` is surprising and should probably be changed.

**Comment by faho** [comment]
Yeah this is in no way specific to `type`. It's a bug in the scoping.

**Comment by lilyball** [comment]
Wasn't scoping rewritten on `master`? I'd be interested to know if this bug still happens there. I'm not currently set up to compile fish on this machine at the moment though.

**Comment by krobelus** [comment]
Yes, it still happens on master
