### ISSUE TITLE
Documented shared bindings not working in vi mode within OSX terminal

### ISSUE THREAD

**Issue by leoauri** [fish-shell/fish-shell#6157]
fish, version 2.7.1
2.7.1
Linux sc-moodle-dev 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
xterm-256color
Over ssh in OSX Terminal Version 2.8.3 (404.1)

[Fish docs on Shared bindings](https://fishshell.com/docs/current/index.html#shared-binds) say:

> Alt← and Alt→ move the cursor one word left or right, or moves forward/backward in the directory history if the command line is empty. If the cursor is already at the end of the line, and an autosuggestion is available, Alt→ (or AltF) accepts the first word in the suggestion.

It doesn't do so in my case.

Reproduce:
- `fish`
- start typing a command with an associated history entry
- press Alt→
Sometimes nothing happens, sometimes the letter "f" is typed, sometimes command mode is activated.

Other than that, I can find no way of accepting the gray suggested completion.  Control-E and  Alt→ both work as documented in emacs mode, but not in vi mode.

Thanks

**Comment by leoauri** [comment]
Output of `fish_key_reader` -> Alt→ is:
```
              hex:   1B  char: \c[  (or \e)
(  0.408 ms)  hex:   66  char: f
bind \ef 'do something'
```

`bind \ef`
`bind: No binding found for sequence '\ef'`
`bind -M insert \ef`
`bind: No binding found for sequence '\ef'`

In Emacs mode:
`bind \ef`
`bind \ef forward-word` :point_left:
`bind -M insert \ef`
`bind: No binding found for sequence '\ef'`

**Comment by faho** [comment]
Yeah, your terminal sends alt-f for Alt→, which is a rather unusual sequence (and also definitely not what xterm sends, so your terminal is *wrong* - fyi iTerm gets this right).

Which is also what #2330 is about, so I'm closing this as a duplicate.

**Comment by leoauri** [comment]
Thanks for the info - sorry for the nuisance
