### ISSUE TITLE
mouse support for completion menu

### ISSUE THREAD

**Issue by PerBothner** [fish-shell/fish-shell#6187]
When tab-completion prints a menu of completion candidates, it would be nice if clicking on one of them selected it, just as for normal menus.  This is a kind of "shell integration" and would presumably require some new escape sequence protocol.

The simplest solution may be a hook to wrap the output of `pager_t::completion_print_item` with some _menu-item-start_ and _menu-item-end_ escape sequence which would make corresponding region clickable.  On a click, the terminal can send to fish the appropriate arrow-key sequences followed by an Enter. It can figure out the arrow-key sequence if the _menu-item-start_ has a code to indicate the currently selected item.

Another possible feature: If the entry is truncated one could display the description on mouse-hover.

A more radical but flexible approach: A callback function `__fish_display_menu` which would be passed a list of completion candidates, and return the index of the selected candidate, with the function being responsible for the UI.  That would allow the ultimate in flexibility.  For example the terminal could do a true popup menu, using a scrollbar instead of a pager if there are too many to fit.

**Comment by floam** [comment]
I think this is thinking a little too hard here - nothing new would need to be invented, just a feature implemented. This would require implementing mouse reporting support for the pager.

**Comment by floam** [comment]
Different modes are described here, https://invisible-island.net/xterm/ctlseqs/ctlseqs.html#h2-Mouse-Tracking

Terminals with mouse support will each all basically support the most basic modes and the exotic modes will be more hit or miss. I know my Terminal.app can do 1017.

**Comment by floam** [comment]
... Of course I don't know how much that will please you because I get it that you're trying to do something fundamentally different with DomTerm. But we don't support mouse clicks in regular terminals which could support this as right now. Any work on this would need to first and foremost address existing terminals.

**Comment by PerBothner** [comment]
Using standard xterm-style mouse tracking (which of course I've implemented in DomTerm) is reasonable and mostly-portable. There are some issues, though:

* Xterm-style mouse tracking is (to simplify) all-or-nothing. For selecting in a menu you'd like it to only report left-button clicks, but do the default terminal action for right-button clicks (typically open a context menu). There is no portable way to do that.
* Mouse reporting can't be limited to part of a window.  If you want to select some text in previous output, enabling mouse reporting will prevent that.
* This is even more of an issue for the related task of moving the cursor by clicking elsewhere in the input line.  (DomTerm already implements this for fish and other shells, controlled by my [proposed shell integration specification](https://gitlab.freedesktop.org/Per_Bothner/specifications/blob/master/proposals/semantic-prompts.md).)  Disabling context menus and selection-by-dragging may be tolerable (though undesired) during context menu selection, but it would be intolerable during regular input editing.
* It might be worth specifying a new mouse reporting mode allowing finer-grained control (right-clicks or clicks above the current line handled by terminal), perhaps in a way that falls back to xterm-standard mouse reporting.
* Specifically when it comes to completion menu, I'm not suggesting a DomTerm-specific hook, but a __fish_display_menu hook (which if defined would "take over" the display and UI) could be quite general.  For example it might be desirable to have a more traditional menu complete with scrollbar, as in these [screenshots](https://web.archive.org/web/20150211213445/http://finalterm.org/) form the (discontinued) finalterm.

**Comment by faho** [comment]
Closing in favor of #4918 as I don't think we really want to invent any new escapes.
