### ISSUE TITLE
Low complexity, high reward feature request: Add "selected" style to site navigation

### ISSUE THREAD

**Issue by clozach** [fish-shell/fish-shell#6189]
The fishshell.com site is harder to navigate than it should be because the current page isn't reflected in the navigation. These four pages, in particular, look virtually identical, which can be unnecessarily disorienting:

https://fishshell.com/docs/current/index.html
https://fishshell.com/docs/current/tutorial.html
https://fishshell.com/docs/current/commands.html
https://fishshell.com/docs/current/faq.html

I meant to fix the issue myself and offer a PR, but I had trouble figuring out how the docs are built. If it's easy to fix, please do!

If not, I'd be happy to help if someone can get me steered in the right direction for building and editing the docs locally. 🤓

**Comment by krobelus** [comment]
Good point, the documentation is getting a new look in the next release (see #5696)
Building the documentation requires at least `cmake` and `python-sphinx` (probably `python3-sphinx` on Debian)
Building the docs seems to work like this:
`mkdir build && cd build && cmake .. && make sphinx-docs`.
The html is in `build/user_doc/html`.

**Comment by Delapouite** [comment]
Here's what it looks. The default theme does not seem to handle the "selected" class in the main navigation: 
![image](https://user-images.githubusercontent.com/39315/66592658-cdfbda80-eb95-11e9-854e-62237e24742c.png)

**Comment by ridiculousfish** [comment]
Yes we've done no customization of the Sphinx theme. If someone wants to take it on I'd appreciate it!

**Comment by clozach** [comment]
Wow, awesomely fast response. Thanks, @krobelus, @zanchey & @ridiculousfish!
