### ISSUE TITLE
Add option to disable virtual PWD

### ISSUE THREAD

**Issue by clarfon** [fish-shell/fish-shell#6191]
Essentially, filing a proper issue for [this comment from #3350](https://github.com/fish-shell/fish-shell/issues/3350#issuecomment-461238738):

> I too loved the old behavior. Conceptually, it prevented me from seeing symlinked directories as distinct from their source. An option to go back (akin to `set -o physical` in bash) would be very helpful.

Essentially, it would be nice to have some way to configure fish so that `cd $path` is always equivalent to `cd (realpath $path)`, and that `pwd -L` and `pwd -P` always return the same thing.

Open to suggestions about what the UI should look like. Main issue with overriding the `cd` function manually is that the `cd` function already adds additional functionality on top of the builtin, and it'd be nice to not have to overwrite that.

**Comment by faho** [comment]
Sorry, no, an option makes this worse and more confusing for everyone.

If you want just make an `rcd` function that calls `cd (realpath $path)`.

**Comment by clarfon** [comment]
So, this has been closed for months but I feel the need to comment on this because this came up again recently. The original behaviour was used because the alternative was considered worse and more confusing for everyone. Now, this new behaviour is added and the old behaviour is considered the same.

Normally, I'd be fine with replacing the `cd` function, but the issue is that I'm forced to choose a new name, as the built-in `cd` is already overriden by a function. Would it not be possible to at least make it easier to do this?

**Comment by zanchey** [comment]
You can override the function if you don't want any of the functionality (directory history), or just copy it and then write a new one (best done in `config.fish`):

```fish
functions --copy cd _fish_cd
function cd
    if test "$argv" = "-"
        _fish_cd -
    else
        _fish_cd (realpath $argv)
    end
end
```
