### ISSUE TITLE
Document how `source` resolves relative paths, particularly consideration of $PATH

### ISSUE THREAD

**Issue by markstos** [fish-shell/fish-shell#6193]
The `bash` `source` command uses `$PATH` to resolve file locations when using `source`. 

I checked the docs for the `fish` `source` command and it didn't mention this behavior, so I made a simple test. I put "a.fish" in a sub directory and it `source b.fish` and that I had `b.fish` just contain an `echo` statement.

I ran the the test from a directory above so my current directory was not the same dir the scripts were in. Bash worked as documented by working when `PATH` was set to include the directory.  `fish` was not compatible in this regard. I tried setting my PATH for fish like this. 

       env PATH="/home/mark/tmp/foo:$PATH" fish foo/a.fish

I don't mind that `fish` differs from `bash` in this regard. I find the `bash` behavior intuitive, as it never occurred to me that `source` would use `$PATH` for files to read, not execute. 

As part of researching this, I found #2382 which lead me to these docs which compare [how the `source` command differs from shell to shell](http://hyperpolyglot.org/unix-shells#source-note). 

From there I learned that the `source` command in `fish` differs from both `bash` and `zsh`.  This is all the more reason to be explicit about how relative paths work. I recommend adding a sentence like:

> fish will search the working directory to resolve relative paths but unlike Bash will not search $PATH.

If there's support, I can submit a PR.

**Comment by ridiculousfish** [comment]
Sure, that seems reasonable to me!

**Comment by markstos** [comment]
Since the PR is opened, I'll go ahead and close this issue. Conversation can continue there if needed.

**Comment by faho** [comment]
We keep issues open until the PR is merged (which github will usually do once it's merged, if it uses the correct "fixes #thing) - it's better to have a solved issue open than to close something that's not done.
