### ISSUE TITLE
Add option to disable & when not preceded by a space

### ISSUE THREAD

**Issue by mikejsavage** [fish-shell/fish-shell#6194]
Hi

I paste URLs multiple times every day but I almost never make background tasks. It would be nice if I could disable & in the middle of words to optimise for the common case.

Fish already has qmark-noglob, which was added for the same reason, so I don't think this is unreasonable!

**Comment by faho** [comment]
Hint: If you paste inside single-quotes (e.g. you enter `youtube-dl '` and then paste), fish will escape it so you can close the single-quotes after.

I don't think  changing the `&` semantics in this teensy way is really worth it, especially considering that it's backwards-incompatible.

Especially considering that #1381 is still open - we might want to redo backgrounding properly, not with some obscure symbol.
