### ISSUE TITLE
macOS cannot background process

### ISSUE THREAD

**Issue by lucifersears** [fish-shell/fish-shell#6199]
fish, version 3.0.2
Darwin halo.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
xterm-256color

I am unable to background a process on macOS.

For example, on macOS you'll notice how hello prints only after `ping` exits:
```
ping -c2 google.com & echo hello
PING google.com (172.217.9.46): 56 data bytes
64 bytes from 172.217.9.46: icmp_seq=0 ttl=53 time=705.591 ms
64 bytes from 172.217.9.46: icmp_seq=1 ttl=53 time=625.601 ms

--- google.com ping statistics ---
2 packets transmitted, 2 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 625.601/665.596/705.591/39.995 ms
hello
Job 1, 'ping -c2 google.com &' has ended
```

This is not the case on Linux however.

**Comment by zanchey** [comment]
Does this happen if you remove your configuration (ie start fish with `env HOME=(mktemp -d) fish`)?

One problem is that fish functions cannot be backgrounded (#238), so if your `ping` is a function it will not work.
