### ISSUE TITLE
Question: How do I package a fish-shell based script?

### ISSUE THREAD

**Issue by terlar** [fish-shell/fish-shell#620]
If I am writing a tool purely in fish-shell, what is the best way to package it?

Would also be nice to have some guidelines for the testing.

Right now I have figured I have my project like this:
```
project
project/share/project/completions/project.fish
project/share/project/functions/__project_private_function.fish
project/share/project/functions/project_function.fish
project/share/project/functions/project_other_function.fish
project/share/project/project.fish
```

I was then thinking I could have something like this in `config.fish`:
```
. some_path_to_project/share/project/project.fish
```

and then inside `project.fish`:
```
set -l project_path some_path_to_project/share/project
set fish_function_path $project_path/functions $fish_function_path
set fish_complete_path $project_path/completions $fish_complete_path
```

Any suggestions how to package a third-party fish-shell script?

**Comment by faho** [comment]
This can now be done with the conf.d stuff.

**Comment by floam** [comment]
If I were to distribute a script I'd probably not keep completions separate. This `foo.fish` works fine to autoload both the function and completion:
```fish
complete -c foo -a bar --exclusive

function foo
    echo Thanks for stopping by with arguments $argv
end
```
