### ISSUE TITLE
Intermittent, non-determinisitc 'argv' failure in a custom function

### ISSUE THREAD

**Issue by orf** [fish-shell/fish-shell#6200]
Fish 3.0.2. Latest MacOS, but this has happened on 2 prior major versions as well.

I have a peculiar intermittent issue with one of my custom functions. The function looks like this:

```fish
function open-project -d "Open a project"
  set filter $argv
  or set filter '""'
  set chosen_project (list-some-projects | fzf -q "$filter")
  $EDITOR $chosen_project
end
```

Occasionally, and without seemingly any pattern, invocations of this command will invoke `fzf` with a literal `""` as the query parameter despite one being given to the command (`open-project searchstring`):

<img width="293" alt="Screenshot 2019-10-13 at 23 45 19" src="https://user-images.githubusercontent.com/1027207/66723658-9a2de880-ee13-11e9-9eda-0aace666742e.png">

However most of the time running this function without any arguments invokes `fzf` with an empty query correctly (that's the point of the or):

<img width="285" alt="Screenshot 2019-10-13 at 23 46 39" src="https://user-images.githubusercontent.com/1027207/66723666-b9c51100-ee13-11e9-8ae8-0daa20f500b3.png">

I'm not a fish expert by any means, but the code I've written above seems to be ok. I cannot explain the non-determinism of it at all. Could this be a bug in fish somehow? If I'm invoking the command with an argument I would always expect the first branch of the `set` to be taken and never fall back to the `""` case.

Why would invoking the above function sometimes (maybe 2% or less of the time) cause a differing result?

**Comment by floam** [comment]
So, when `set` is assigning it never set an exit status. It's not that it always succeeds returning 0, but it always preserves the `$status` from before.

I'm not sure what you are trying to do with this but it is the source of your issues:

```fish
  set filter $argv
  or set filter '""'
```

The `or` line will get ran whenever your function is ran with a non-zero `$status` going in - like after a rare failed command 2% of the time or so.

**Comment by floam** [comment]
Are you trying to set `$filter` to those literal quotes if `$argv` was empty? You will need to check for that explicitly.

**Comment by orf** [comment]
Ahh, yes I am. I believe I took the answer from https://github.com/fish-shell/fish-shell/issues/3926#issuecomment-290442534 or somewhere else.

Thank you @floam, much appreciated.
