### ISSUE TITLE
Add $fish_ppid ; PID of the parent process

### ISSUE THREAD

**Issue by Clyybber** [fish-shell/fish-shell#6203]
It would be a nice feature if fish provided `$fish_ppid` in addition to the already provided `$fish_pid`.
Bash and dash provide this in `$PPID`.

**Comment by faho** [comment]
What would you want this for?

Note that it's already possible to get via `ps -o ppid -p $fish_pid`, and I don't think this needs to be optimized?

**Comment by Clyybber** [comment]
Ah, I see. Yeah I agree. Sorry for the noise :)
