### ISSUE TITLE
commandline -p does not split on double ampersand or double pipe

### ISSUE THREAD

**Issue by krobelus** [fish-shell/fish-shell#6214]
`commandline -p` prints the current process. This works for processes separated by semicolon, but not when they are separated by `&&` or `||`:

```fish
bind \eg 'printf "\nProcess: <%s>" (commandline -p)'
a; and b2
Process: < and b>
a && b
Process: <a && b>
```

Some completion scripts complete based on the tokens in `commandline -p`, those completions break here.

**Comment by ridiculousfish** [comment]
Nice find!
