### ISSUE TITLE
Ctrl+v results in paste on macOS  (it should not)

### ISSUE THREAD

**Issue by masukomi** [fish-shell/fish-shell#6224]
> Please tell us which fish version you are using by executing the following:

3.0.2

> Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

macOS 10.14.6 (18G95)
`$TERM` says xterm-256color
Terminal emulator is iTerm2 OR Terminal.app 

> Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:

yes tried. no didn't change anything.

The problem goes away if i switch to bash and comes back when I exit bash.

> Tell us how to reproduce the problem

1. put something on your clipboard
2. type control+v  (not command+v)
3. watch the contents of your clipboard get pasted

> What happened:

clipboard was pasted to terminal

> What should have happened:

`Ctrl+v` tells the terminal to not interpret the following character, so `Ctrl+v Ctrl-i` will display a tab character, `Ctrl+v Ctrl+m` displays `^M` So, nothing visible should have happened.

For non-mac users: Command+v is paste, not Control+v

**Comment by faho** [comment]
It should.

>Ctrl+v tells the terminal to not interpret the following character

It does not. It's not a terminal thing, it's a bash (or more specifically libreadline) thing that fish does not implement. If you want to see the key you've pressed, use `fish_key_reader` or `cat -v`.

>For non-mac users: Command+v is paste, not Control+v

Command+v is your *terminal*'s paste, but that has numerous issues and limitations. Chiefly unless the terminal implements bracketed paste pasted text can trigger arbitrary keybindings, including most importantly the "execute" one. Typically a newline is enough.

E.g. paste this into a terminal running bash:

```bash
echo foo
echo bar
```

Before you had a chance to review the `echo foo` has already been executed.

Our ctrl-v binding on the other hand uses `pbpaste` to read the clipboard, so this can't happen.

**Comment by masukomi** [comment]
closing because working as designed. Thanks for the enlightenment @faho

**Comment by bram2000** [comment]
Sorry for commenting on a closed issue, but I've been trying to figure out how to do the bash verbatim mode (ctrl-v) on fish shell and it led me here.

Say I want to use sed to strip DOS newline (^M or Ctrl-M) characters, how can I do this using fish shell?

I want to run `sed 's/^M//'`

Thanks!
