### ISSUE TITLE
builtin's --help should use pager when the output does not fit in the screen

### ISSUE THREAD

**Issue by krobelus** [fish-shell/fish-shell#6227]
E.g. `complete -h` prints a bunch of useful information but I almost always need to scroll up a or use a pager (`\ep` or `\eh` in this case). I think it should use a pager by default if the output is a tty and there are more lines than one screenful, just like `git diff` and others.

Probably also for functions.

**Comment by floam** [comment]
This is a good idea, and it doesn't need to be implemented in the builtins: `__fish_print_help` is the fish function invoked for this and it's easy to improve.
