### ISSUE TITLE
SCPing a file to a server running fish fails when config.fish prints anything

### ISSUE THREAD

**Issue by robacarp** [fish-shell/fish-shell#623]
In my fish config, I have this little bit of logic that takes care of some command incompatibilities between OS X's bsd `ls` and a Debian `ls`:

https://github.com/robacarp/config_files/blob/master/.config/fish/config.fish#L13

Through some poking at a problem I was having using SCP to copy to a remote server using the same config file, I found out that something about printing from a config.fish on a remote host causes the scp transfer to fail silently.

**Comment by nicovalencia** [comment]
@robacarp just found this after 20 minutes of headbashing! Haha! Thanks @xfix !
