### ISSUE TITLE
Fish hangs instead of closing properly when using disown command via kitty terminal

### ISSUE THREAD

**Issue by alxpettit** [fish-shell/fish-shell#6256]
Running Fish 3.0.2 on Arch Linux (up to date) with [Kitty terminal](https://sw.kovidgoyal.net/kitty/).

```
Welcome to fish, the friendly interactive shell
a@ad1 ~> fish --version
fish, version 3.0.2
a@ad1 ~> uname -a
Linux ad1 5.3.7-arch1-1-ARCH #1 SMP PREEMPT Fri Oct 18 00:17:03 UTC 2019 x86_64 GNU/Linux
a@ad1 ~> echo $TERM
xterm-kitty
```

Have tried after ` sh -c 'env HOME=$(mktemp -d) fish'`. Produces same result. `disown` command operates normally under XFCE Terminal. I have not tested on other terminal emulators. Steps to reproduce:

1. Open Kitty terminal.
2. Open test background job (e.g., `sleep 1000 &`)
3. `disown`
4. Ctrl+D or `exit`

**Comment by rien333** [comment]
Works fine for me under kitty. You have to add `close_on_child_death yes` to your `kitty.conf`.  See [Configuring kitty — kitty 0.14.6 documentation](https://sw.kovidgoyal.net/kitty/conf.html#opt-kitty.close_on_child_death) -> `close_on_child_death`

**Comment by alxpettit** [comment]
Thank you! That solved it :)
