### ISSUE TITLE
Fish cannot run batch files on Windows

### ISSUE THREAD

**Issue by amyspark** [fish-shell/fish-shell#6257]
Terminal: `cygwin` (`MINGW64_NT-10.0-18362 Windows 3.0.7-338.x86_64 2019-07-03 15:16 UTC x86_64 Msys`)

Fish version: 3.0.2 (installed from the Git-Bash SDK)

Hey all,

Bash from Git-Bash can run batch files directly (even though, for obvious reasons, they lack the shebang and are not marked as executable by `ls -xla`). Doing the same in Fish results in:
```
fish: Unknown command tlmgr.bat
```
and, when run from the folder itself,
```
fish: The file '/d/tlpretest/bin/win32/tlmgr.bat' is not executable by this user
```

I don't know if this is a problem with Fish itself or with my setup.

**Comment by zanchey** [comment]
I'm a bit surprised that that works in Git-Bash, because all the posts I can find online suggest that it doesn't; it might be worth asking the Git-Bash developers first if you can definitely reproduce this.

**Comment by ronnac** [comment]
You need to call the batch file with winpty. You can create an alias for that.
