### ISSUE TITLE
In-tree builds are flagged dirty

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#6264]
Running CMake in-tree builds (as done in Homebrew, for example) overwrites the `Makefile` shipped in git, leaving to the build being flagged dirty:

```
> git clone https://github.com/fish-shell/fish-shell.git
Cloning into 'fish-shell'... done.
> cd fish-shell
> git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
> cmake .
...
> git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Makefile
```

I thought of moving the shipped `Makefile` to `GNUmakefile`, but that will only make things worse.

Either we should remove the `Makefile` from git, or expressly not support in-tree builds. The former is my preference, though there is lots of code supporting the latter/allowing for both.

**Comment by faho** [comment]
IMHO we should remove the Makefile (and the BSDmakefile), since it's just a dumb wrapper around cmake anyway.

**Comment by faho** [comment]
Yeah, done.

**Comment by zanchey** [comment]
@mqudsi added these, I think, so would appreciate his thoughts.

**Comment by mqudsi** [comment]
Respectfully, I disagree for the same reasons that the makefiles were added:

```
commit 20db22f0fe25e7daaac11111aea1a14481d8ac5c
Author: Mahmoud Al-Qudsi <mqudsi@neosmart.net>
Date:   Tue Apr 9 19:58:48 2019 -0500

    Add basic `make` shim for CMake

    This lets non-developers simply `cd` into the fish source directory and
    execute `make` to build the project. The Makefile searches for CMake and
    hands over the build to it if it is available, otherwise an error
    message is emitted. All dependency checking is left to CMake.

    Non-fish-devs shouldn't have to concern themselves with what build
    system fish developers have chosen, and building a random C++ project
    should not be a chore in familiarizing one's self with all the various
    build platforms out there.
```

There is a cleaner fix here (which is also more semantically correct) to revert https://github.com/fish-shell/fish-shell/commit/326f5586deb33cc8d711d51b36a400c85d44185e and simply rename `Makefile` to `GNUmakefile` (to parallel `BSDmakefile`), which does not conflict with any of the CMake generated makefile names.

**Comment by zanchey** [comment]
The problem is that `GNUmakefile` will always take precedence over the generated `Makefile`, effectively eliminating the ability to perform in-tree builds.

There's explicit support for in-tree builds through the fish build system. I'm not sure that I understand the aversion to them.

**Comment by mqudsi** [comment]
Right, I missed that. It's easy enough to work around though, as we are free to use the full GNU extensions by virtue of renaming it to `GNUmakefile`:

```diff
diff --git a/GNUmakefile b/GNUmakefile
index dedfec76c..246b2940e 100644
--- a/GNUmakefile
+++ b/GNUmakefile
@@ -17,6 +17,16 @@ else
 BUILDFILE = Makefile
 endif
 
+
+# If CMake has generated an in-tree Makefile, use that instead (issue #6264)
+MAKE_DIR:=$(shell dirname $(realpath $(firstword $(MAKEFILE_LIST))))
+ifeq ($(shell test -f $(MAKE_DIR)/Makefile && echo 1), 1)
+
+all:
+	@+$(MAKE) -f $(MAKE_DIR)/Makefile $(MAKECMDGOALS) --no-print-directory
+
+else
+
 all: .begin build/fish
 
 PHONY: .begin
@@ -28,7 +38,8 @@ build/fish: build/$(BUILDFILE)
 	$(CMAKE) --build build
 
 build/$(BUILDFILE): build
-	cd build; $(CMAKE) .. -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -G "$(GENERATOR)" -DCMAKE_INSTALL_PREFIX="$(PREFIX)" -DCMAKE_EXPORT_COMPILE_COMMANDS=1
+	cd build; $(CMAKE) .. -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -G "$(GENERATOR)" \
+		-DCMAKE_INSTALL_PREFIX="$(PREFIX)" -DCMAKE_EXPORT_COMPILE_COMMANDS=1
 
 build:
 	mkdir -p build
@@ -52,3 +63,5 @@ run: build/fish
 .PHONY: exec
 exec: build/fish
 	exec ./build/fish
+
+endif # CMake in-tree build check
```

It's not "pure" by any means, but imho aside from our dignity we don't lose anything by doing this.
