### ISSUE TITLE
[feature request] Display the certain part of the tab completion to the right of the cursor

### ISSUE THREAD

**Issue by etoombs-encircle** [fish-shell/fish-shell#6266]
So, when you type the first part of a command, fish displays autosuggestions in grey to the right of the cursor. These autosuggestions are based on the command history and a subset of all possible tab completions, whose boundaries are unclear. It would be really cool if there were an option for fish to also display the certain part of tab completions to the right of the cursor.

By "certain part of a tab completion", I'm referring to the string fish inserts for you (if any) when you hit tab once. From now on, I'll call this string the *green string*.

So, the idea is after every keypress, fish calculates the green string and displays it to the right of the cursor in green (or some other colour as long as it's different from the grey string's colour). If the green string matches the beginning of the autosuggestion, then the remainder of the autosuggestion (if any) is displayed after the green string. If the autosuggestion does not match, it is not displayed, because it is probably now invalid. When the user actually hits tab, the cursor just jumps to the other side of the green string and the green string gets highlighted the same way all of the text to the left of the cursor gets highlighted.

**Comment by zanchey** [comment]
FWIW, the term "grey string" is known as an autosuggestion and is derived both from history and from tab completions.

So, what I think you're suggesting is that the part of an autosuggestion that matches the only available completion should be displayed in a different colour?

I'm not actually sure that that happens all that often, at least unambiguously - in the majority of cases there isn't part of the autosuggestion that will definitely be inserted on a single tab. Happy to hear what others think, though.

**Comment by etoombs-encircle** [comment]
The reason I didn't think the autosuggestion was derived from tab completions was because many unambiguous tab completions don't appear in the autosuggestion unless they are in the history. Like for instance, `man clock_nano|`.

Especially when long filenames are involved, unambiguous tab completions happen all the time.

**Comment by faho** [comment]
>So, the idea is after every keypress, fish calculates the green string

Sorry, but that's prohibitively expensive. Completions can take a bunch of time, in bad cases seconds. But even in good cases they can take milliseconds, and waiting for that after every keypress is unworkable. Not waiting for it is too complicated to implement, so I'm rejecting this.
