### ISSUE TITLE
Binding Ctrl-Alt-<key> requires \e\c<key> and not \c\e<key>

### ISSUE THREAD

**Issue by RasmusWL** [fish-shell/fish-shell#6274]
If I want to bind Ctrl-Alt-`<key>`, only the sequence `\c\a<key>` works, and `\a\e<key>` does not work. Wouldn't it be awesome if fish could tell me that I should use the one thing and not the other? :blush:

For example, trying to bind Control-Alt-w in the two different ways, only the first one will succeed, but no output to indicate so
```
$ bind \e\cw backward-kill-bigword
$ bind \c\ew kill-whole-line
```

On the output from `bind -a` we can see that something went wrong
```
$ bind -a
...
bind \e\cw backward-kill-bigword
bind \x1cew kill-whole-line
```

I am running fish version `3.0.2`, on Ubuntu 18.04.

**Comment by ridiculousfish** [comment]
If you run `fish_key_reader` and then type in the key sequence you would like to bind, does it show the right thing?

**Comment by RasmusWL** [comment]
yes, it does! (cool tool, did not know about this)

```
$ fish_key_reader
Press a key

              hex:   1B  char: \c[  (or \e)
(  0.301 ms)  hex:   17  char: \cW
bind \e\cW 'do something'
```

**Comment by faho** [comment]
>Wouldn't it be awesome if fish could tell me that I should use the one thing and not the other?

It can't. `e\cw` names a correct, valid, sequence of characters. It's the one you'd get if you press escape and then control-w (within $fish_escape_delay_ms milliseconds), and your terminal could be configured to send it for something.

Our advice is always to check `fish_key_reader` in the terminal you want, and use whatever sequence that names.

Closing as the question has been answered, but feel free to ask follow-ups here, in a new issue or on https://gitter.im/fish-shell/fish-shell.

**Comment by RasmusWL** [comment]
@faho thanks for looking into this. I think it was not quite clear what my problem was (since I messed up the key sequences in my original description -- just fixed that).

My problem was that when I tried to bind Control-Alt-W I used `bind \c\ew` (which did not work) instead of `bind \e\cw` (which does work). I would have loved for `bind` to tell me that the key sequence `\c\ew` is invalid, and that I should have used `\e\cw`.

I just checked `Escape + Control-w`, and if I'm fast enough that will trigger my `\e\cw` binding.

I think a solution could that would have prevented my problem and frustration, would be if the documentation for `bind` would scream _use fish_key_reader_ loud and clear, but in my man-page for `bind` it does not even mention it (fish version 3.0.2).

P.S. I just noticed I pust the key sequences all wrong in the original description, fixed that up.

**Comment by faho** [comment]
>My problem was that when I tried to bind Control-Alt-W I used bind \c\ew (which did not work) instead of bind \e\cw (which does work). I would have loved for bind to tell me that the key sequence \c\ew is invalid, and that I should have used \e\cw.

OOoooh, okay. Yeah, that's a long-standing issue - #2008.
