### ISSUE TITLE
Error on string match -eq is confusing

### ISSUE THREAD

**Issue by krobelus** [fish-shell/fish-shell#6282]
Since 66938d206a0a801ecee87e21863badef7d0d5587, `string match -eq` returns an error.
Previously, it would print the match even though `-q` is given.

I currently think we should allow the combination and make it output nothing, but with the matching semantics of `-e`. Additionally we should be clear in the documentation that `-e` only changes the pattern by adding wildcards left and right, e.g. enables matching any substring.
Because regex mode does substring matching by default `-rqe` would be the same as `-rq`.
But without `-r` it makes a difference.

Otherwise we need to fix usages of `-eq`, see #6265

In general I find the behavior of the `-e` flag confusing. I would expect `string match` without it to match substrings by default (like `grep -Fo` or even `grep -F`) but it's probably not good too change that.

**Comment by faho** [comment]
>In general I find the behavior of the -e flag confusing.

Yeah, glob mode was a mistake. A simple "substring" mode (with "--start" and "--end" options to anchor at the start/end) would have been much more intuitive.

>it's probably not good too change that.

Unfortunately yes.

-----

So, the usage in #6265 was `-e` as a shortcut for `*THING*`, which we shouldn't break.
