### ISSUE TITLE
Quick way to change the colors of the [I] and [N] in insert and normal mode vi_mode?

### ISSUE THREAD

**Issue by cjappl** [fish-shell/fish-shell#6284]
Hi all,

Getting around to customizing the colors a bit, and so far it's been very easy to change all of my colors minus the [I] and [N] for normal and insert mode.

I did a quick search of open issues and couldn't find anything.

Is there a variable that can be set somewhere to affect these colors?

![Screen Shot 2019-11-04 at 8 47 44 AM](https://user-images.githubusercontent.com/14171107/68134766-d23ebd80-fedf-11e9-832d-f5af7047d145.png)

**Comment by krobelus** [comment]
You can to create a function called `fish_mode_prompt`, see
http://fishshell.com/docs/current/commands.html#fish_mode_prompt

**Comment by cjappl** [comment]
Beautiful! Thank you so much!
