### ISSUE TITLE
`$<TAB>` completing variables which fuzzily-match the word "history" is slow

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#6288]
Using https://github.com/fish-shell/fish-shell/commit/4f1fa9513cc8aeb6c64df20d5a21e7f263fba538

I have around ~1100 environment variables exported in both bash and fish (not manually! various scripts automatically export them e.g. https://github.com/techwizrd/fishmarks). Fish is significantly slower than bash.

Pretty simple to repro:

* In fish, `$<TAB>` takes ~3-5 seconds
  * Note – `complete -C '$'` is instant
* In bash, `$<TAB>` is instant.

~What's going on? I suspect it's the fact that `<TAB>` is filling in the description as well, while fish's `complete` / bash don't deal with descriptions. If that's the case I suppose there's not too much we can do about speeding it up?~ 

---

**Edit:** Figured it out...

> https://github.com/fish-shell/fish-shell/issues/6288#issuecomment-549784545 Tab-completion of variables which fuzzily-match the word `history` are significantly slower than other tab-completions.

**Comment by zx8** [comment]
Interesting, I went through the alphabet one by one typing `$[A-F]<TAB>` completions were all instant. When I reached `$H<TAB>`, it took ~2-3 seconds to complete and the only completions I got were:

```
$HOME  (Variable: /Users/zx8)
$HOMEBREW_NO_ANALYTICS  (Variable: 1)
$HOMEBREW_NO_INSTALL_CLEANUP  (Variable: 1)
```

What's special about `$H<TAB>`?

**Comment by krobelus** [comment]
Should work fine now, that's a hefty speedup :sweat_smile:

**Comment by zx8** [comment]
Confirmed.

Your recent contributions to fish have been incredibly useful to me @krobelus – thanks a lot! 😃
