### ISSUE TITLE
$history can be very expensive

### ISSUE THREAD

**Issue by krobelus** [fish-shell/fish-shell#6290]
Histories can be huge. I have a `$history` of around 50k commands and I'm sure there are larger ones out there. Issue #6288 shows that completions can take multiple seconds because of that, when they should take no time. I think the [fix](23eb6e9c09fa5b022eba254fcb07007ffcfc3b14) for it only solved one instance of particular problem.

For example, the completions for `set ` use `set -l`, `set -g` and `set -U` to compute possible variables, all of which compute `$history`. The value of variables is shown in the description of the completions. Also completions for `vared` are affected.

This suggests that `set` should not print the (full) value of `$history`.
It feels weird to expose history as a variable, since variable access is expected to be cheap.

I wonder if we can remove `$history` (I think the `history` function/builtin does all one would need).
Or limit its size.

But maybe it's already enough to not print it in `set`, then you only pay when explicitly requesting the value of the variable.

**Comment by krobelus** [comment]
939d4674e49ffa0474ae40b3634af5ad75ee2027 might be a satisfactory fix because the problem performance problem should not be visible anymore (when using variable name completions). It may still be wise to phase out `$history`.

**Comment by zx8** [comment]
> @krobelus I wonder if we can remove $history (I think the history function/builtin does all one would need).

Worth noting that there was a previous PR to remove `$history` entirely https://github.com/fish-shell/fish-shell/pull/4461, which was rejected.

**Comment by krobelus** [comment]
Oh wow I feel stupid for not searching issues.
Anyway it might not be a problem anymore since it's fixed for `set -g` and variable name completions, and something like `$history[1]` does not compute the full history (54cefeb5b14bfed76451679e9fea356f8789f2b4).
On current master `set | string match -re '^history'` shows `history Full history of interactive commands` with my fix. I guess we could also show the first couple of items in the history, see https://github.com/fish-shell/fish-shell/pull/4461#issuecomment-336474213

**Comment by zanchey** [comment]
> current master `set | string match -re '^history'` shows `history Full history of interactive commands` with my fix

I really dislike this - can we go back to showing the first few items?

**Comment by krobelus** [comment]
Makes sense, done in 3d9c0d3c6982180d9900a17359cf16f476cb9d35
