### ISSUE TITLE
Autocompletion for pacman -Qo provides package names instead of filepaths

### ISSUE THREAD

**Issue by martinpelikan** [fish-shell/fish-shell#6297]
Typing `pacman -Qo <tab>` provides a completion list of package names, not file paths as is expected. This command is used to determine which package owns the provided file.

fish: 3.0.2
pacman: 5.2.1-1

I'm not proficient with writing my own completions, but made sure there aren't any custom completions interfering with the expected usage. 

It looks like this is the relevant line:
https://github.com/fish-shell/fish-shell/blob/d242ff18082bf94a14eba32a63efce9627784cc7/share/completions/pacman.fish#L118

**Comment by martinpelikan** [comment]
Looks like a recent commit might have actually fixed this:
https://github.com/fish-shell/fish-shell/commit/0ec954a8c265313318a8f4449638ce28fd5b8ba2#diff-b03048ed4cefa1aa59bb09dd8b5a7c3dR119

**Comment by zanchey** [comment]
Yep, duplicate as such of #6238
