### ISSUE TITLE
prompt disappear when input new line in replace mode in vi mode

### ISSUE THREAD

**Issue by 0x005c** [fish-shell/fish-shell#6298]
In replace mode, Enter key clears prompt.
![Screenshot from 2019-11-08 14-48-47](https://user-images.githubusercontent.com/52650857/68452874-21198980-0237-11ea-8183-5ae7e474808d.png)
You can reproduce this bug by typing Esc key and then 'r', then Enter key in vi mode.

fish version: `fish, version 3.0.2-1757-g47c0b5f9`

**Comment by krobelus** [comment]
This is because the enter key inserts a carriage return. Seems reasonable to insert a newline instead.
