### ISSUE TITLE
Option to disable private mode message

### ISSUE THREAD

**Issue by teake** [fish-shell/fish-shell#6299]
Hi, first time issue poster here. First off, thanks for developing fish. It's awesome!

I've recently discovered private mode, and it looks very useful for screencasts with [asciinema](https://asciinema.org). However, when I start a recording with `asciinema rec -c 'fish --private'` the private mode prints the message:
```
.
fish is running in private mode, history will not be persisted.
```
The first line is a bug when the greeting message is empty. This is handled correctly in https://github.com/fish-shell/fish-shell/blob/d242ff18082bf94a14eba32a63efce9627784cc7/share/functions/__fish_config_interactive.fish#L126-L135 
but not in 
https://github.com/fish-shell/fish-shell/blob/d242ff18082bf94a14eba32a63efce9627784cc7/share/functions/__fish_config_interactive.fish#L33-L36
But the reason I'm posting this issue is that I would like an option to remove the private mode message altogether, so that it doesn't show up in a screencast. Perhaps something like mechanism for the normal greeting message, http://fishshell.com/docs/current/faq.html#faq-greeting?

Btw, I'm running fish 3.0.2 on macOS 10.14.

**Comment by krobelus** [comment]
On fish 3.0.2 if you create a function instead of the variable, this already works
`fish --private -C 'function fish_greeting; end'`

I also fixed it to not print anything if `$fish_greeting` is empty.

**Comment by teake** [comment]
Great, thanks!
