### ISSUE TITLE
Outdated documentation section on Debugging

### ISSUE THREAD

**Issue by equwal** [fish-shell/fish-shell#6304]
http://fishshell.com/docs/current/index.html#debugging

Breakpoints now change the prompt by default, whereas the section says it does not change the prompt (and was confusing when that was the way to do it).

**Comment by zanchey** [comment]
That documentation on the website is for the most-recently-released version of fish (3.0.2) - the change to breakpoint prompt behaviour is #1310, which will be in the upcoming 3.1.0. The confusing sentence to which you allude has been removed.

It would probably be a good idea to mention `fish_breakpoint_prompt` in the documentation, though.

**Comment by equwal** [comment]
Closing this since the edit was added to 3.1.0 12 days ago.

**Comment by equwal** [comment]
I have 3.0.2, and I have a special prompt for breakpoints. ![image of my breakpoint prompt](https://spensertruex.com/static/frob-flollop.png)
