### ISSUE TITLE
fish_read_limit is not a great way to do it.

### ISSUE THREAD

**Issue by equwal** [fish-shell/fish-shell#6305]
Setting the maximum data from a command substitution to 10MB seems like a bad idea with respect to the [design documentation](https://fishshell.com/docs/current/design.html). 
```shell
set example (cat ~/Documents/calculus-book.pdf ) # 70MB
fish: Too much data emitted by command substitution so it was discarded
```
I propose a change to this:
- In an interactive shell: change this warning to mention the `fish_read_limit` variable, and its current value.
- For scripts: remove the limit (no limit).

Does that sould like a good idea?

**Comment by floam** [comment]
Hear hear, in fact I’m not positive it was a great idea at all. But I think the interactive limit could be 500MB. 

I like the idea of setting the terminal title to “reading...” or something of that sort with progress if stdout is a TTY. 

–
Aaron

**Comment by zanchey** [comment]
Original discussion in https://github.com/fish-shell/fish-shell/issues/3712 (fish_read_byte_limit)

**Comment by faho** [comment]
It's now 100MB (IIRC). The main problem with removing it is that it doesn't *work*, because the operating system has ARG_MAX. If you need to handle data that large, a shell script isn't the right way to do it.

**Comment by equwal** [comment]
@floam this seems like a really good use for the default title, which otherwise doesn't do much at all. It would be much better than writing to the terminal without asking.

**Comment by equwal** [comment]
> It's now 100MB (IIRC). The main problem with removing it is that it doesn't _work_, because the operating system has ARG_MAX. If you need to handle data that large, a shell script isn't the right way to do it.

I didn't understand this detail. In this case it is out the hands of `fish` to raise it. I'm going to close unless someone has a path forward.
