### ISSUE TITLE
Provide a browse function

### ISSUE THREAD

**Issue by equwal** [fish-shell/fish-shell#6307]
I am working on the[ open_github plugin for Oh My Fish](https://github.com/patrickf3139/open_github), and we need to open a web brower. Ideally it would be exactly the same as the help docs behaviour (same browser). I just copied all the code from `help` and made an [`open_browser` function](https://github.com/patrickf3139/open_github/pull/17/commits/1772a608d1fe5802043ecd20d815b065e925fa87#diff-c3363986195f74f8241fea2d81c09cce). Could that kind of thing be included in fish? Maybe call it 
```shell
browse URL -- open a web browser at the URL.
```

Fish relies so heavily on the web browser that it would make sense to have this available in the base.

**Comment by faho** [comment]
We provide an `open` function that defers to OS-provided open tools - on linux/bsd/etc that's `xdg-open`, on macOS it's a thing actually called `open`.

Pass it a URL and it should figure it out.

Or set $BROWSER and use that, it's a common-enough convention.

I don't think there's a need for a specific "browse" function.
