### ISSUE TITLE
Change files sorting when Tab pressed

### ISSUE THREAD

**Issue by rusnasonov** [fish-shell/fish-shell#6317]
fish, version 3.0.2
3.0.2
Darwin perseus 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
xterm-256color

Is the way to change file sorting when I press <kbd>Tab</kbd> button? Usually I want order file by date added, but sometimes by file size. I don't understand which sorting algorithm using now.

**Comment by faho** [comment]
There is no way to pick the sorting order, it just sorts by name.

Custom completions can choose to use `--keep-order` to let the completion system keep the items in the provided order, but the built-in file completions provide no options, and I don't think we want to add any.

**Comment by rusnasonov** [comment]
=(

**Comment by krobelus** [comment]
@rusnasonov If you need this often you can define a keybinding that completes files in a different order.
`fzf` or `sk` come in handy here;

```fish
function my_complete_current_token_with_fzf
    set -l files (commandline -ct)*
    set -l file (string join \n $files | sort -r | sk)
    if string length -q $file
        commandline -rt $file
    end
end
bind \eg 'my_complete_current_token_with_fzf'
```
Sorting can be changed by changing the way you compute `files` or the call to `sort`
