### ISSUE TITLE
Sublime theme support

### ISSUE THREAD

**Issue by fdcds** [fish-shell/fish-shell#6318]
It would be great if I could use the same colour theme in fish that is also used by my terminal emulator or my pager. I would hope that this would simplify making the shell prompt, the shell, the paged output and the terminal emulator look readable and consistent.

[bat](https://github.com/sharkdp/bat) uses Sublime themes (*.tmTheme):
* https://github.com/sharkdp/bat#adding-new-themes
* https://www.sublimetext.com/docs/3/color_schemes_tmtheme.html

**Comment by faho** [comment]
So the "tmtheme" format is xml, and sublime's newer one is json.

This would work nicely with a converter that takes a sublime theme and spits out fish `set` statements. A python-based solution would probably be easiest as we already opt-depend on python and that should have acceptable xml/json things in the stdlib IIRC.

(or plug it into webconfig)

If someone wants to work on it, go for it!

**Comment by Nunuvin** [comment]
is anyone interested? I could give it a stab.

**Comment by faho** [comment]
@Nunuvin This is up for grabs, so go for it!

It's py3 - compatibility with py2 is a bonus, but that's dead (https://pythonclock.org/) so I don't think we should keep requiring it. Also if at all possible no new dependencies - this should run after the user installs just python3.

**Comment by Nunuvin** [comment]
Just to check my understanding of the problem: it should be a standalone (or stored somewhere specifically?) script which can take .xml or .json sublime theme and convert it into fish code which will set respective settings?

**Comment by faho** [comment]
@Nunuvin Sounds about right, yeah. Essentially take the themes and spit out

```fish
set -U fish_color_host SOMERGBVALUE
set -U fish_color_user SOMEOTHERRGB
```

(bonus: add an option to change that "-U" to "-g").

where "SOMERGBVALUE" is something that works as an option to our `set_color` builtin.

You'll have to make some decisions here regarding which sublime theme variable translates to which fish theme variable - I assume they don't match 100%. That's alright, it's also possible that you'll have to ignore some sublime variables entirely.

**Comment by JanczarKurek** [comment]
Hi
Because last update to this issue was few months ago, I decided to implement something myself.
After examining documentation of sublime-color-scheme, I realized it supports quite bunch of things. I implemented minimal skeleton for this that you can see here https://github.com/JanczarKurek/fish-shell/commit/0af1d4554af73835438f2f2d0a5e1361684561bf (I am not sure whether I should put it as a merge request, as it is WIP), you can check if this approach is ok, because tbh I'll rather get some green light before matching all fish_color_* variables.

My main question is, which features of sublime themes should be supported as a baseline, and which can be (maybe) added later in separate issue / MR. Those are part of so called minihtml, in particular:

- Additional color expressions, HSL or others
- Variable specification with usage var(variable_name)
- functional expressions regarding color: https://www.sublimetext.com/docs/3/minihtml.html#color-mod_function

**Comment by charego** [comment]
Nice @JanczarKurek. I implemented something as well (https://github.com/charego/fish-shell/commit/113086ed02ca9be5c8e730852d438c25ce6a825c). It's a simple program supports `.tmTheme` and limited `.sublime-color-scheme`. Note python is not my primary language; your implementation looks cleaner.

```
> ./theme.py Monokai.tmTheme
set --universal fish_color_normal F8F8F2
set --universal fish_color_selection --background=49483E
set --universal fish_color_match --background=3E3D32
set --universal fish_color_search_match --background=FFE792
set --universal fish_color_comment 75715E
set --universal fish_color_autosuggestion 75715E
set --universal fish_color_param --italics FD971F
set --universal fish_color_quote E6DB74
set --universal fish_color_command A6E22E
```
```
> ./theme.py -g ayu-mirage.sublime-color-scheme
set --global fish_color_normal cbccc6
set --global fish_color_selection --background=34455a
set --global fish_color_match --background=191e2a
set --global fish_color_search_match --background=ffcc66
set --global fish_color_comment --italics 5c6773
set --global fish_color_autosuggestion --italics 5c6773
set --global fish_color_param d4bfff
set --global fish_color_quote bae67e
set --global fish_color_end cbccc6
set --global fish_color_command ffd580
```

**Comment by charego** [comment]
Regarding your question, we could check popular sublime themes to see how they specify colors. Here's the support matrix for reference.

| Format | Example | .tmTheme | .sublime-color-scheme |
|---------|----------|------------|----------|
| Hex RGB | #FF0000 | X | X |
| Hex RGBA | #FF000080 | X | X |
| RGB notation | rgb(255, 0, 0) |  | X |
| RGBA notation | rgba(255, 0, 0, 0.5) |  | X |
| HSL notation | hsl(0, 100%, 100%) |  | X |
| HSLA notation | hsla(0, 100%, 100%, 0.5) |  | X |
| Named (X11) | aquamarine | X |  |
| Named (CSS) | lemonchiffon |  | X |
| Variables | var(--bluish) |  | X |
| Color mods | color(var(--background) alpha(0.25)) |  | X |

**Comment by JanczarKurek** [comment]
Could you give some opinion on the subject @faho?

**Comment by faho** [comment]
>My main question is, which features of sublime themes should be supported as a baseline

That's the question? I don't have a particular list of *features*. The guideline I'd use is "if it's useful and doesn't break immediately, or breaks in an acceptable way". So if you give it a couple of the most popular themes it should either produce something usable or an error that it can't handle it yet.

That way there's no harm in adding something, even if it's not perfect or entirely done.

Note also that e.g. RGBA is unsupportable for us - at least I don't know of terminals with a separate alpha channel. Ignoring the alpha is probably the way to go?

**Comment by charego** [comment]
RGBA and HSLA can be blended with the background to produce hex if we need to.

Example: https://github.com/tdekoning/rgba-to-hex-converter

**Comment by faho** [comment]
>RGBA and HSLA can be blended with the background to produce hex if we need to.

We have no way to get the background.

**Comment by mattmc3** [comment]
I know this has been out here for 3 years now, but I thought I'd share a different (and I think much simpler) approach to generating themes from files like these. Tools like [`yq`](https://github.com/mikefarah/yq) and [`jq`](https://stedolan.github.io/jq/) let you parse YAML or JSON on the command line. Using that, and the Alacritty YAML color schemes from [iTerm2](mbadolato/iTerm2-Color-Schemes), you have access to hundreds of popular themes with a couple small, simple Fish functions:

```fish
function alacritty_to_theme \
    --description "Make fish theme from an alacritty color scheme" \
    --argument-names ymlfile

    if not type -q yq
        echo >&2 "Required tool 'yq' not found. Install from https://github.com/mikefarah/yq."
        return 1
    end
    if not test -e $ymlfile
        echo >&2 "File not found '$ymlfile'."
        return 1
    end

    # turn yaml into fish set var statements and eval
    set --local code (
        yq -o=props $ymlfile |
            string match -rev '^\#' |
            string replace -r '^' 'set ' |
            string replace -a '.' '_' |
            string replace -r '= (#|0x)' ''
    )
    eval (string join ';' $code)

    generate_theme \
        (path change-extension '' $ymlfile | path basename) \
        $colors_primary_background $colors_normal_blue $colors_normal_magenta \
        $colors_bright_yellow $colors_normal_yellow $colors_normal_white \
        $colors_normal_red $colors_bright_black $colors_bright_black
end

function generate_theme \
    --description "Generate fish theme from colors" \
    --argument-names theme_name bg_color command_color param_color \
        terminator_color quote_color redirecton_color \
        error_color comment_color autosuggest_color

    set --local theme \
        "# name: '$theme_name'" \
        "# preferred_background: $bg_color" \
        "" \
        "fish_color_normal normal" \
        "fish_color_command $command_color" \
        "fish_color_quote $quote_color" \
        "fish_color_redirection $redirecton_color" \
        "fish_color_end $terminator_color" \
        "fish_color_error $error_color" \
        "fish_color_param $param_color" \
        "fish_color_comment $comment_color" \
        "fish_color_match --background=brblue" \
        "fish_color_selection white --bold --background=brblack" \
        "fish_color_search_match bryellow --background=brblack" \
        "fish_color_history_current --bold" \
        "fish_color_operator brcyan" \
        "fish_color_escape brcyan" \
        "fish_color_cwd green" \
        "fish_color_cwd_root red" \
        "fish_color_valid_path --underline" \
        "fish_color_autosuggestion $autosuggest_color" \
        "fish_color_user brgreen" \
        "fish_color_cancel -r" \
        "fish_color_host normal" \
        "fish_pager_color_completion normal" \
        "fish_pager_color_description B3A06D yellow" \
        "fish_pager_color_prefix normal --bold --underline" \
        "fish_pager_color_progress brwhite --background=cyan" \
        "fish_pager_color_selected_background --background=brblack" \
        "fish_color_option $param_color" \
        "fish_color_keyword $command_color" \
        "fish_color_host_remote yellow" \
        "fish_color_status red"
    printf '%s\n' $theme
end
```

Now, let's say you want the TokyoNight color scheme. You simply do this:

```fish
$ # Let's grab a repo full of Alacritty YAML color schemes
$ set iterm2cs ~/repos/iterm2cs
$ git clone --depth 1 https://github.com/mbadolato/iTerm2-Color-Schemes $iterm2cs
$ set ymlfile $iterm2cs/alacritty/tokyonight.yml
$ alacritty_to_theme $ymlfile > $__fish_config_dir/themes/tokyonight.theme
```

I know we're talking about  Sublime Text JSON `*.sublime-color-scheme` files, not Alacritty YAML files, but the concept is exactly the same - use `jq` to make theme files. It wouldn't take too much effort to adapt a similar Fish function to do this.

Is this something that would just be better as a an external Fish plugin written in Fish script, rather than something that ships with Fish itself written in Python? I'd vote to close this one.

**Comment by faho** [comment]
Yeah, this can just be an external thing - it's gotten simpler since the introduction of .theme files, so someone just needs to do the mapping and conversion.
