### ISSUE TITLE
completions/git: completions only match the first git command in an `&&`

### ISSUE THREAD

**Issue by evantravers** [fish-shell/fish-shell#6321]
`git checkout && git fetch -<TAB>`

When I'm using tab completion on a command that's part of a phrase, the tab completion results are for the first command on the left hand of the `&&`, not the last command on the right hand.

[asciinema recording](https://asciinema.org/a/vOWDwqprvBudyX0SUJcyNyHQG)

## Technical Details

`fish --version`
> fish, version 3.0.2

`uname -a`
> Darwin Evans-MBP 19.0.0 Darwin Kernel Version 19.0.0: Thu Oct 17 16:17:15 PDT 2019; root:xnu-6153.41.3~29/RELEASE_X86_64 x86_64

`echo $TERM`
> screen-256color

I'm in OSX Catalina and using [kitty](https://github.com/kovidgoyal/kitty) as a terminal.

**Comment by krobelus** [comment]
Fixed in master as of 2fed311d4ccb6d337cdd6014ed10b0611e15718d, thanks anyway for the report!
