### ISSUE TITLE
Pipe(|) and redirect(>) operators are redirecting the literal command instead of stdout

### ISSUE THREAD

**Issue by jlmurphysa** [fish-shell/fish-shell#6322]
Fish Version: `fish, version 3.0.2`
OS Version: `Darwin Kernel Version 19.0.0`
TERM: `screen-256color`
**No problem on vanilla(un-customized) fish**

**Summary:** the pipe and redirect operators are not working as expected within my fish environment (both inside and outside of tmux).

Two examples of the behaviour were demonstrated in the recording below:
https://asciinema.org/a/Gyf5b1i0L6Gho0ELZxn5xyBcA

```
❯ echo "some string" > file.txt
~
❯ cat file.txt
echo some string
```

This has been an issue for me for a few weeks now, but I can't seem to crack it.
I'm clearly missing something... any suggestions as to what could be happening?

**Comment by zanchey** [comment]
Probably your [`fish_postexec` hook script](https://github.com/jlmurphysa/dotfiles/blob/master/fish/conf.d/__fasd_run.fish), which unsafely calls `eval echo $argv`.

I think you can probably replace this with `$argv`, or possibly `(string escape -- $argv)`.

I thought we had another issue describing this, but I can't find it.

**Comment by zanchey** [comment]
https://github.com/oh-my-fish/plugin-fasd/blob/master/init.fish has it right.

**Comment by jlmurphysa** [comment]
@zanchey Spot on.

Turns out I had installed `fasd` from an unmaintained fork... 
Replaced it with `oh-my-fish/plugin-fasd` and I'm back in business.

Thanks for the help!
