### ISSUE TITLE
How to  unbind history search

### ISSUE THREAD

**Issue by hupfdule** [fish-shell/fish-shell#6324]
Fish version 3.0.2

I can't get used the the fish history search. I currently use [re-search](https://github.com/jbonjean/re-search) which I have bound to `Ctrl-R`. But still the built-in history search via up-arrow always gets in my way. 

When I press the up-arrow I want to always get to the previous command and never do a history search.

How can I rebind the up-arrow to achieve this?

I tried to erase the existing binding via 

```
bind -e -k up
```

but that does nothing.

And actually I also have no idea to which function to bind it to.

**Comment by krobelus** [comment]
Run `fish_key_reader` to see which sequence is actually sent when you press the up arrow.
It's `\e\[A` here. You can bind it to a custom function overriding the preset.
The function would walk the `$history` array.

**Comment by faho** [comment]
@krobelus `bind -k up` is entirely okay here - that looks up terminfo for the "up" key.


@hupfdule: `bind --erase` (or `bind -e`) will erase your *custom* binding and leave the preset binding intact. Since you don't have a custom binding it does nothing.

What you instead want to do is to just bind what you want, in this case that's

```fish
bind -k up up-line
```

**Comment by hupfdule** [comment]
@faho Thanks for your help, but it doesn't work yet.
See the following fish session:
![fish](https://user-images.githubusercontent.com/36069345/68874501-971f6400-0701-11ea-9bf1-861b8766c0be.png)

I issues some `echo` commands and afterwards some `println` commands. Then I rebind the up-arrow key.

Now when I press the up arrow, I get the last entered command, the `bind` command. This is expected.

Now if I type `ec` fish autosuggests the last command containing `ec`, which is `echo "c"`. This is also expected.

But when I now press the up arrow, fish replaces the commandline with `echo "b"`. This is not what I expected. It seem to still do the history search.

---

I also tried to bind `up-line` to `ctrl-p`:

```
bind \cp up-line
```

But now pressing `ctrl-p` doesn't do anything anymore. So this clearly behaves differently than binding to the up-arrow, but both methods don't do what I expect.

**Comment by faho** [comment]
Aaaah, there's some additional weirdness here:

1. We bind some common arrow sequences explicitly in case your terminfo is bogus (plenty of terminals claim to be "xterm" and then don't behave anything like it), and these seemingly take precedence. (Also keypad mode, which is one of those absolute terminal bogosities that we've never quite got a handle on). So yeah, you currently do want to check `fish_key_reader` and use the sequence that gives you.

2. `up-line` really just goes up a line. I was under the impression it'll also do the history switching, but it apparently doesn't.

3. We don't actually have a bind function for just stepping through the history. Everything we have searches if there is any input.

**Comment by faho** [comment]
Ah, turns out this was already filed in #1671.

**Comment by hupfdule** [comment]
Ah, thank you.

@krobelus actually gave another hint on implementing that functionality until #1671 is resolved.

> The function would walk the $history array.

I know I can iterate over that array with something like

```
for h in $history; echo $h; end
```

but I don't know how to iterate it one step further on each press to UP/Ctrl-P (and reset the iteration after pressing some other key).

Do you have any hints or even an example on that?

**Comment by krobelus** [comment]
It's probably not worth, but you can do something like
```
bind -k up 'set -g history_index (match $history_index + 1); commandline -r $history[$history_index]'
bind -k down 'set -g history_index (match $history_index - 1); commandline -r $history[$history_index]'
```
You'd have to initialize and reset `$history_index`, it's not easy to do that on every other key, but you can use an [event handler](http://fishshell.com/docs/current/index.html#event).

**Comment by hupfdule** [comment]
Well that really looks quite complicated. 
I'd therefore prefer if #1671 gets fixed.

But many thanks for your help!
