### ISSUE TITLE
stdbuf does not behave as expected when used inside a function

### ISSUE THREAD

**Issue by JohnDowson** [fish-shell/fish-shell#6325]
Fish version 3.0.2
rxvt-unicode-256color v9.22
Archlinux with **5.3.10-arch1-1** kernel

Example: grepping a stream in real-time
This does not work: `caflog log/developement.log | rg '\..ms\)'` , output only appears after `tail` is terminated.
```
# Defined in /tmp/fish.vGolSo/caflog.fish @ line 2
function caflog --description 'Clears and tails specified log file'
	if test -n "$argv"
        echo "" | sudo tee $argv && clear && stdbuf -o0 tail -f $argv;
    else
        echo "No log file to follow"
    end
end
```
This does work:
`echo "" | sudo tee log/development.log && clear && stdbuf -o0 tail -f log/development.log | rg  '\..ms\)'`

`stdbuf caflog` obviously doesn't work either.

**Comment by faho** [comment]
Duplicate  of #1396 

Fish buffers blocks and functions. In the upcoming release it'll do less of it.
