### ISSUE TITLE
Automated completions generation from zsh/bash

### ISSUE THREAD

**Issue by gjmveloso** [fish-shell/fish-shell#6328]
Hi Team,

Is it technically feasible to extend man pages completion generation tool to support automated completions generation from zsh/bash, for example?

Most of packages distributed by Homebrew on macOS, for instance, contains upstream zsh/bash completions, stored on those two locations:

`/usr/local/share/zsh/site-function`
`/usr/local/etc/bash_completion.d`

In terms of user experience, ideally when triggering `fish_update_completions` from the terminal it would do the trick and transpiling zsh/bash completions to fish.

**Comment by faho** [comment]
1. bash/zsh completions don't have descriptions, so you end with bad completions

2. We already have a sizable library of completions that should cover the most-used programs (if not file issues for that)

3. Many of these are basically just what you'd get from the man page

This might have been worth it when fish started out, as an alternative or addition to the man page generator, but nowadays it's not really all that helpful anymore.

**Comment by floam** [comment]
If someone wants to go ahead and implement it, we'd look at a PR. Just don't expect us to do it.
