### ISSUE TITLE
Fish inserts a bunch of whitespace chars after canceling `cat` with `Ctrl + C`

### ISSUE THREAD

**Issue by kchibisov** [fish-shell/fish-shell#6331]
`version` fish, version 3.0.2-1758-g19b59fc54
`uname`: Linux 5.3.11-arch1-1 SMP PREEMPT Tue, 12 Nov 2019 22:19:48 +0000 x86_64 GNU/Linux
`TERM`: alacritty
everything was tested with  sh -c 'env HOME=$(mktemp -d) fish'.

During some testing in `alacritty`, it was discovered that `fish shell` fills the rest of the line with whitespaces in the following case.

Use `cat` and then terminate it with `Ctrl + C`, so the end of line after `⏎` char will be just whitespace chars. My main question is what the idea behind this filling and why it's required here (bash and zsh just inserts new line)?

The problem with this approach is that if your terminal has a `reflow` then on the next terminal **shrink** you'll insert new line for a thing when `reflow` shouldn't occur from the user perspective (because of those whitespaces).

You can repro it in `alacritty`, `termite` and `gnome-terminal` at least, I mean the visual effect of the `reflow`.

P.s. I've initially asked about this behavior on IRC, since I'm not sure that it's an actual bug or not, but it was a bit silent in this regard.

**Comment by faho** [comment]
This happens because fish tries to get the prompt onto the next line, so it does an old trick to do so, which is also what leaves the "⏎" visible (it's *always* inserted, but when the last line of the command's output ends in a newline it's overwritten).

Zsh also does this (but with a "%"), so I'm  unsure why that doesn't disturb your reflow.

>P.s. I've initially asked about this behavior on IRC, since I'm not sure that it's an actual bug or not, but it was a bit silent in this regard.

Yeah our IRC channel is basically dead and we should remove it from the documentation.

**Comment by kchibisov** [comment]
@faho zsh inserts a new line instead of whitespace chars from our testing. The reflow is correct from a terminal perspective, but not from the user one. Do you need some screenshots on what zsh/bash and fish are doing in the following scenario?

**Comment by faho** [comment]
A screenshot would not help here, as this is about non-visible characters.

**Comment by kchibisov** [comment]
@faho I can make them visible ;- )

**Comment by faho** [comment]
Also inserting just "a newline" would not work.

The trick, as we're doing it, is to insert a sentinel character ("⏎" for us, "%" for zsh) and enough whitespace to fill the line. If you've started in first column (because the last character was a newline) this leaves the cursor just at the end of the line. If you then print a carriage-return (`\r`), any subsequent prints would overwrite the sentinel.

Now we'd have to somehow explain to the terminal that that whitespace isn't "real", it's just for cursor movement, and we'd have to do it in such a way that all the crap terminals out there don't break entirely.

**Comment by kchibisov** [comment]
Each whitespace from pty is a `z` now eventually, so on a screenshot you can see `fish`, then `bash`, then `zsh`.

Before reflow

![picture](https://user-images.githubusercontent.com/27620401/68995241-822b0800-089c-11ea-85be-d3cedeb7b983.png)

After reflow

![picture](https://user-images.githubusercontent.com/27620401/68995275-d209cf00-089c-11ea-9513-c3592581abbc.png)

**Comment by faho** [comment]
>P.s. I'm not sure how I can get zsh to print %.

Try e.g. `printf '%s' a`. That won't end the line in a newline, which will leave the sentinel.

**Comment by kchibisov** [comment]
@faho Yep, that behaves exactly like the fish shell.

**Comment by faho** [comment]
Huh...

I think it might be possible zsh doesn't do the thing if the process was killed via signal.

**Comment by kchibisov** [comment]
@faho It's actually interesting zsh does insert whitespace chars, but it seems like it's clearing all the thing afterwards, when bash just do CRLF.

all escapes from zsh and bash during cat (I've typed `Z` before `^C`)

You can notice CSI K CSI J and a bunch of whitespace chars in zsh recording. As you can see it inserts inverted `%`, but then removes it?

[zsh.recording.txt](https://github.com/fish-shell/fish-shell/files/3854373/zsh.recording.txt)

[bash.recording.txt](https://github.com/fish-shell/fish-shell/files/3854374/bash.recording.txt)

**Comment by ridiculousfish** [comment]
@kchibisov can you tell how it's clearing the whitespace afterwards? Assuming the whitespace pushes it to the next line, I would expect that erase-to-right and clear-below would NOT erase the previously-printed whitespace?

**Comment by kchibisov** [comment]
@ridiculousfish Oh, you're correct the doesn't touch the line with ^C, however it's behavior is very strange to be honest.

If you disable `CSI K` and `CSI J` handling in alacritty (by patching it), change all whitespace chars to `z` and repeat the cat `Ctrl + C` thing, you'll notice that It leaves the line with `Ctrl + C` untouched, moves cursor to next line, prints it's inverted `%`, fill this line with whitespace chars and after that erase the entire line and print the prompt, it's a bit confusing but ok. Just looking through more logs of zsh (ref tests), I see it's doing this insert `%` + erase line each time I press enter(request a new prompt, I hope you've understood it), so I assume that in this specific scenario with `Ctrl + C` they're trying to avoid inserting `%`, etc.

![picture](https://user-images.githubusercontent.com/27620401/69207547-36f54b80-0b61-11ea-9d16-083184cda985.png)

This is a bit different case when the behavior is identical `printf "%s" a`. I've noticed that it behaves exactly like fish shell with `cat` + `Ctrl + C` in terms of the amount of `z` I see on a screen. So it inserts sentinel, fills the line with whitespace chars, move to the next line and erases it's with `CSI K`.

![picture](https://user-images.githubusercontent.com/27620401/69207636-92273e00-0b61-11ea-9117-f3f84ce418dd.png)

So at this point fish is doing fine and changing the behavior to follow `zsh` is arguable and I leave it up to you. Since I've initially was just curious and tried to avoid bringing this discussion to bug tracker.

P.s.
I wonder why both zsh and fish always fill the entire line with whitespace chars and then erasing it, but they are not doing the same thing when printing sentinel is involved. They just call erase, which I guess is enough, but I feel like there's something behind this fill the entire line with whitespace chars and then erase.

**Comment by faho** [comment]
>So at this point fish is doing fine and changing the behavior to follow zsh is arguable and I leave it up to you.

Okay, so let's not.
