### ISSUE TITLE
Instructions to install fish on CentOS 8

### ISSUE THREAD

**Issue by yetangye** [fish-shell/fish-shell#6333]
Could U provide instructions to install fish on CentOS 8? Thank U very much.

Even though I installed ncurses-devel, When I install the fish rpm package, It still tell me libncurses and other two packages be needed.
➜  ~ rpm -i ./fish-3.0.2-1.13.x86_64.rpm 
        libncurses.so.5()(64bit) 
        libtinfo.so.5()(64bit) 
        python 
        
And I also think, as a Shell program, fish should shakes python dependency off.

**Comment by yetangye** [comment]
CentOS 8 default installation provides python3, but no python 2.

**Comment by zanchey** [comment]
Where have you downloaded the package from? Probably using `yum` or `dnf` is the way to go to fulfill the dependencies correctly.

**Comment by yetangye** [comment]
On [Fish Shell CentOS Subscribe or Download](https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A3&package=fish), Click RHEL.
First I use the subscription method, It now works for CentOS 8.
Then I downloaded the rpm for RHEL 7 (no rpm for RHEL 8 yet)

**Comment by zanchey** [comment]
Gotcha. It looks like OBS is not adding RHEL 8, only CentOS 8, so I'll try and get some builds up soon.

**Comment by zanchey** [comment]
There have been some issues with getting CentOS 8 working on OBS, but the maintainers are working on it.

**Comment by zanchey** [comment]
So OBS can finally build CentOS 8 packages, but fish 3.0 fails lint checks requiring the use of a specific Python. This is fixed in git so I'd rather work on getting 3.1 out the door in the next week or two. I guess I'd take a patch in OBS itself, but I suspect it would rebuild all the packages which might cause some surprises if not done right.

**Comment by AmericanY** [comment]
@zanchey any update for Centos 8? i keep following and waiting for the release.

**Comment by zanchey** [comment]
I don't want to make a promise I can't keep.

**Comment by phattja** [comment]
I workaround on rhel8 by this

rpm -ivh --nodeps https://download.opensuse.org/repositories/shells:/fish:/release:/3/RHEL_7/x86_64/fish-3.0.2-1.14.x86_64.rpm&&cd /lib64&&ln -s libncurses.so.6.1 libncurses.so.5&&ln -s libtinfo.so.6.1 libtinfo.so.5&&fish
![Screenshot_20200117-141808_Termux](https://user-images.githubusercontent.com/59993890/72592508-4ad8e600-3935-11ea-8f95-a8036b17acfc.jpg)

**Comment by samtuke** [comment]
Also looking forward to this release :slightly_smiling_face:

**Comment by AmericanY** [comment]
@zanchey am still unable to see it under "yum search fish"

**Comment by zanchey** [comment]
Have you followed the directions at https://software.opensuse.org//download.html?project=shells%3Afish%3Arelease%3A3&package=fish ?

**Comment by AmericanY** [comment]
```
[root@A ~]# cd /etc/yum.repos.d/
[root@A yum.repos.d]# wget https://download.opensuse.org/repositories/shells:fish:release:3/CentOS_8/shells:fish:release:3.repo
--2020-02-12 18:12:18--  https://download.opensuse.org/repositories/shells:fish:release:3/CentOS_8/shells:fish:release:3.repo
Resolving download.opensuse.org (download.opensuse.org)... 195.135.221.134, 2620:113:80c0:8::13
Connecting to download.opensuse.org (download.opensuse.org)|195.135.221.134|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://download.opensuse.org/repositories/shells:fish:release:/3/CentOS_8/shells:fish:release:3.repo [following]
--2020-02-12 18:12:18--  https://download.opensuse.org/repositories/shells:fish:release:/3/CentOS_8/shells:fish:release:3.repo
Reusing existing connection to download.opensuse.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://download.opensuse.org/repositories/shells:fish:/release:/3/CentOS_8/shells:fish:release:3.repo [following]
--2020-02-12 18:12:18--  https://download.opensuse.org/repositories/shells:fish:/release:/3/CentOS_8/shells:fish:release:3.repo
Reusing existing connection to download.opensuse.org:443.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://download.opensuse.org/repositories/shells:/fish:/release:/3/CentOS_8/shells:fish:release:3.repo [following]
--2020-02-12 18:12:18--  https://download.opensuse.org/repositories/shells:/fish:/release:/3/CentOS_8/shells:fish:release:3.repo
Reusing existing connection to download.opensuse.org:443.
HTTP request sent, awaiting response... 200 OK
Length: 297
Saving to: ‘shells:fish:release:3.repo’

shells:fish:release:3.repo                100%[====================================================================================>]     297  --.-KB/s    in 0s       
2020-02-12 18:12:18 (13.3 MB/s) - ‘shells:fish:release:3.repo’ saved [297/297]

[root@A yum.repos.d]# yum install fish
Last metadata expiration check: 0:03:09 ago on Wed 12 Feb 2020 06:09:17 PM EET.
Error:
 Problem: conflicting requests
  - nothing provides python needed by fish-3.1.0-2.1.x86_64
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
[root@A yum.repos.d]# python --version
Python 3.6.8
[root@A yum.repos.d]#
```

**Comment by zanchey** [comment]
Right, there's no actual plain `python` package on RHEL/CentOS 8, which is annoying.

I have made some changes to the spec file which should fix this, though you'll have to wait for the builds to complete and the repositories to upload. Apparently nobody is testing either the nightly builds or the beta packages on RHEL/CentOS 8, which is a shame.

**Comment by zanchey** [comment]
I've got a CentOS 8 VM now, and it appears that this is properly fixed with fish 3.1.0-3.1 RPMs.

**Comment by kmplngj** [comment]
CentOS 8 Stream :(

`sudo yum install -y --nobest fish
Letzte Prüfung auf abgelaufene Metadaten: vor 0:03:47 am Mi 04 Mär 2020 08:41:49 CET.
Fehler:
 Problem: conflicting requests
  - nothing provides python needed by fish-3.1.0-3.1.x86_64
(try to add '--skip-broken' to skip uninstallable packages)`

**Comment by atonicode** [comment]
Yes it's working for me on my CentOS 8 server.
