### ISSUE TITLE
Very slow alias creation compared to other shells

### ISSUE THREAD

**Issue by hugoh** [fish-shell/fish-shell#6337]
fish, version 3.0.2 on macOS 10.14.6

I've been trying to define the aliases from https://github.com/ahmetb/kubectl-aliases using fish.

That's 788 aliases that can be defined with:

```
git clone https://github.com/ahmetb/kubectl-aliases.git
source kubectl-aliases/.kubectl_aliases
```

fish is significantly slower than zsh and bash at doing this. Without some very elaborate benchmarking, here are some timings I got from running:

```
date +%s.%N && source kubectl-aliases/.kubectl_aliases && date +%s.%N
```

Here are the results:
* fish: 2.692s
* zsh: 0.046s
* bash: 0.018s

As you can see, fish is *much* slower.

I haven't had a chance to look at what's going on under the hood yet.

**Comment by faho** [comment]
Yes, `alias` is just a function that defines functions - see `type alias`. Fish itself has no knowledge of aliases.

If you wish to make this any faster, define functions instead. Which you can also autoload, which takes 0 time unless you use the function.

**Comment by hugoh** [comment]
Got it. So, the following will help then:

`funcsave (alias | string replace -r '^alias (\w+) .*' '$1')`

I still think that the tax on calling `alias` looks very high.

**Comment by faho** [comment]
>Got it. So, the following will help then:

That, or using `abbr`, or a wrapper function that takes shorter commands (a la git-aliases).
