### ISSUE TITLE
Prefix files starting with - with ./ when tab complet

### ISSUE THREAD

**Issue by mjarkk** [fish-shell/fish-shell#6340]
- Version: **fish, version 3.0.2**
- OS: **arch linux (Linux CRASHTOP 5.3.11-arch1-1 x86_64)**
- Same result with no 3th part customizations: **yes**

So i have the wired addiction to place a `-` before files if i don't want programs to use them for example config files.  

But most programs see `-` as argument what makes tab to complete useless when using those files in commands like this:
```
mark@CRASHTOP /h/m/g/s/g/a/gocui> mv -go.mod go.mod
mv: invalid option -- 'g'
Try 'mv --help' for more information.
``` 

The solution for this is to place `./` before the file name but when using tab to select a file in fish this doesn't work and makes me go back to the start of the file name and add `./` myself

Reproduce:  
```
touch ./-a
rm # press tab to auto complete "-a"

# See the error:
# rm: invalid option -- 'a'
# Try 'rm ./-a' to remove the file '-a'.
# Try 'rm --help' for more information.
```

**Comment by zanchey** [comment]
See also #1519

**Comment by mqudsi** [comment]
I've fixed it for completions generated in fish code (i.e. via `__fish_complete_suffix`) but not in the main code. The core completions code doesn't distinguish between file and argument so it can't be patched there, but it can be patched lower down where the directories are traversed, though it *might* have some odd side effects. https://github.com/fish-shell/fish-shell/commit/6dc8a1d3a78eea93638d5062faa2703d61b98213 should be safe, though.

**Comment by ridiculousfish** [comment]
Let's track in #1519 . This has been a longstanding issue (with every shell). Thanks for filing!
