### ISSUE TITLE
Danish keyboard: Fish pastes clipboard when pressing æ, ø or å

### ISSUE THREAD

**Issue by M0rtenB** [fish-shell/fish-shell#6341]
Suddenly, when pressing the æ, ø or å key on my Danish keyboard, I don't get the relevant char, but the clipboard contents pasted into my macOS standard terminal window.
Only in fish, not bash.
Removing .config/fish doesn't change anything.
Brew uninstall fish and brew install fish doesn't either.

Any ideas?

Fish version 3.0.2
MacOS 10.15.1

**Comment by faho** [comment]
Please start `fish_key_reader` and press those keys. What does it say?

**Comment by M0rtenB** [comment]
```
17:06:18 /Users/mortenb > fish_key_reader 
Press a key

              hex:   16  char: \cV
(  0.298 ms)  hex: F700  char: \uF700
(  0.323 ms)  hex: F700  char: \uF700
bind \cV\uF700\uF700 'do something'
17:06:24 /Users/mortenb > fish_key_reader
Press a key

              hex:   16  char: \cV
(  0.296 ms)  hex: F700  char: \uF700
(  0.315 ms)  hex: F700  char: \uF700
bind \cV\uF700\uF700 'do something'
17:06:26 /Users/mortenb > fish_key_reader
Press a key

              hex:   16  char: \cV
(  0.294 ms)  hex: F700  char: \uF700
(  0.301 ms)  hex: F700  char: \uF700
bind \cV\uF700\uF700 'do something'
17:06:29 /Users/mortenb > 
```

**Comment by faho** [comment]
Well, that registers as ctrl-v and something, which triggers fish's ctrl-v binding, correctly. Your keyboard or terminal are misconfigured.

**Comment by faho** [comment]
Well, that registers as ctrl-v and something, which triggers fish's ctrl-v binding, correctly. Your keyboard or terminal are misconfigured.

**Comment by M0rtenB** [comment]
Hm, it may be as simple as unchecking "Escape non-ASCII input with Control-V" in the Terminal app's settings. No idea how that got checked.
Anyway, thanks for helping me troubleshooting!
