### ISSUE TITLE
Suggestion: Higher brace expansion priority

### ISSUE THREAD

**Issue by sniperrifle2004** [fish-shell/fish-shell#6343]
I have been playing around with brace expansion rules and its interaction with variable expansion and command substitution and it seems to me that it would make more sense for brace expansion to have a higher priority than both variable expansion and command substitution. With the current priority you get a Cartesian product of your brace expansion:
```fish
echo {$var}
# Intermediate result is echo
# Outputs empty line
echo {a,$var}
# Intermediate result is echo 
# Outputs empty line
echo {$var}a
# Intermediate result is echo 
# Outputs empty line
set -l var a b
echo {a,$var}
# Intermediate result is echo {a,a} {a,b}
# Outputs a a a b
echo {a,a$var}
# Intermediate result is echo {a,aa} {a,ab}
# Outputs a aa a ab
```
I find that in most cases this is not what I want at all (Especially as the amount of literals constructed in the brace expansion increases). Instead I want to add/construct elements in the brace expansion list from the command substitution or variable expansion:
```fish
echo {$var}
# Intermediate result is echo $var
# Outputs empty line
echo {a,$var}
# Intermediate result is echo a $var
# Outputs a
echo {$var}a
# Intermediate result is echo $vara, with $var already identified as a variable,
# so a doesn't become part of the identifier as it would regularly
# Outputs empty line
set -l var a b
echo {a,$var}
# Intermediate result is echo a $var
# Outputs a a b
echo {a,a$var}
# Intermediate result is echo a a$var
# Outputs a aa ab
```
I used just variables here, but all of this also applies to command substitution.

As far as I can tell, this can be accomplished by simply prioritizing brace expansion over command substitution and variable expansion, aside from the fact that you can't do this naively due to the variable identifier collision in the second example.

I realize this is a major breaking change, so I don't expect it to change any time soon (if at all), but I would be interested in your thoughts on this.

**Comment by ridiculousfish** [comment]
Nice write up! Is there a real-life example to motivate this?

**Comment by sniperrifle2004** [comment]
For instance this command to move some files into a subfolder
```fish
mv dir/{$files, sub}
```
Or retrieving a bunch of files from a host in different folders:
```fish
wget http://host.domain/{$files,sub/$subfiles,sub2/$sub2files}
```
Now all of this can be achieved currently without problems (besides arguably being a little inconvenient) if you construct your list into a variable beforehand instead of using brace expansion. Which brings me to an interesting property of Cartesian products of brace expansions :
```fish
set -l var1 a b
set -l var2 c d
echo {$var1, $var2}
# Intermediate result: echo {$var1, c} {$var1, d}
# Intermediate result: echo {a, c} {b, c} {a, d} {b, d}
# Outputs a c b c a d b d
```
That expands into the flattened Cartesian product of two lists! This happens for any brace expansion with two or more variables with more than one element. I haven't been able to find such an easy way to express that in my proposed scenario. So it does seem that increasing the priority would make the language somewhat less expressive. However, I have yet to find *a single scenario* in which such a Cartesian product list is **useful** (And I have looked. It seems like such an interesting possibility on the surface). Besides, if you start to add other stuff or more variables into the brace expansion it quickly gets out of hand and the result list becomes really hard to reason about and increasingly useless. Consider what would happen in the wget example.

**Comment by faho** [comment]
Yeah, I don't think we want to change this.

It's quite subtle and awful to check for, while not being massively better, so in this case backwards compatibility wins.
