### ISSUE TITLE
Does scp Work

### ISSUE THREAD

**Issue by DennisFaucher** [fish-shell/fish-shell#6345]
echo $version
3.0.2-1-g6f940d72d

uname -a
Darwin dennis-mbp 18.7.0 Darwin Kernel Version 18.7.0: Sat Oct 12 00:02:19 PDT 2019; root:xnu-4903.278.12~1/RELEASE_X86_64 x86_64

echo $TERM
xterm-256color

scp pi@pwnagotchi.local:~/handshakes/2019-11-23/* .
fish: No matches for wildcard 'pi@pwnagotchi.local:~/handshakes/2019-11-23/*'. See `help expand`.
scp pi@pwnagotchi.local:~/handshakes/2019-11-23/* .
       ^

**Comment by DennisFaucher** [comment]
Interesting tilde slash seems to mean strike-through in GitHib.

**Comment by faho** [comment]
Of course it works, you just need to quote the wildcard.

Bash has what we view as a bit of a misfeature, where it'll try to match wildcards, and if they don't match pass them through unaltered (by default, this can be changed via the "nullglob" and "failglob" options).

So fish doesn't do that. It tries to match wildcards, and if they fail, it'll fail the command (unless it's `for`, `set` or `count`, in which case it'll pass through nothing instead).

So your command should be

```fish
scp 'pi@pwnagotchi.local:~/handshakes/2019-11-23/*' .
```

or

```fish
scp pi@pwnagotchi.local:~/handshakes/2019-11-23/"*" .
```

or

```fish
scp pi@pwnagotchi.local:~/handshakes/2019-11-23/\* .
```

**Comment by DennisFaucher** [comment]
Thank you
