### ISSUE TITLE
Only allow bold text in prompt

### ISSUE THREAD

**Issue by nhooyr** [fish-shell/fish-shell#6346]
I'd like to use bold text exclusively for my prompt. It makes it much easier to find in a sea of output. But when other commands start bolding their output, it becomes very difficult to find my prompt and understand my shell history.

It'd be nice if fish could strip the bold escape sequences from every command I run but allow me to use them in my prompt.

**Comment by faho** [comment]
Fish does not alter command output, and it can't, because most command output does not pass through fish. I'm afraid that's pretty fundamental.
