### ISSUE TITLE
Backtrace for test built-in reports wrong line number

### ISSUE THREAD

**Issue by ammgws** [fish-shell/fish-shell#6350]
A bug (empty variable not quoted) in the fisher plugin [done](https://github.com/franciscolourenco/done/blob/master/conf.d/done.fish) caused fish to show a backtrace, however the line numbers were off by a factor of two or so.

`done` is a script that displays notifications after long-running tasks finish, in the output below it has run after a pacman system update:
```
(6/7) Updating the desktop file MIME type cache...
(7/7) etckeeper: post-transaction commit
Parsing man pages and writing completions to /home/ammgws/.local/share/fish/generated_completions/
  4112 / 4112 : zramctl.8.gz                                        
test: Missing argument at index 2

~/.config/fish/conf.d/done.fish (line 88): 
	if test $__done_initial_window_id != (__done_get_focused_window_id)
	  ^
in function '__done_is_process_window_focused'
	called on line 152 of file ~/.config/fish/conf.d/done.fish
in function '__done_ended'
in event handler: handler for generic event “fish_prompt”

(Type 'help test' for related documentation)
```

Fish reports line 88, however the actual line is on line 45 (if start counting from 1).
Fish also reports line 152, however the actual line looks to be line 80.

fish: version 3.0.2-1833-g80a4898e7
terminal: kitty 0.14.6
OS: Arch Linux 5.3.12

Haven't tried without third-party customisations yet since trying to figure out how to reproduce the issue.

**Comment by faho** [comment]
Yeah, can reproduce with an event handler, but the `test` isn't actually necessary, because it's an issue in our line number counting.

```fish
#
# 
# some comments
# some more comments

function t --on-event fish_prompt
    status line-number
end
```

The line number will be the real line number times two, minus one. So if it's on line 5 you'll get line 9 reported.

**Comment by faho** [comment]
Okay, this also needs to be done interactively. That means either in conf.d or config.fish. It also happens in 3.0.2.

**Comment by sniperrifle2004** [comment]
Based on the examples given and a quick look at the relevant code it seems to me that it is because the parser adds the function definition line number to the line number from the execution context in `get_lineno()`. It's easy to fix, but it is hard to say whether this would break other cases in which this would actually be necessary.
