### ISSUE TITLE
High CPU usage when idle

### ISSUE THREAD

**Issue by themoah** [fish-shell/fish-shell#6353]
Super high CPU usage when idle -

$ top | grep fish
```
PID    COMMAND          %CPU TIME     #TH   #WQ #PORTS MEM    PURG   CMPRS  PGRP  PPID  STATE    BOOSTS      %CPU_ME %CPU_OTHRS UID FAULTS    COW     MSGSENT    MSGRECV    SYSBSD     SYSMACH     CSW         PAGEINS  IDLEW    POWER INSTRS CYCLES USER               #MREGS RPRVT VPRVT VSIZE KPRVT KSHRD
1481   fish             98.6 06:07:37 3/1   0   16     6640K  0B    6616K 1480  1480  running  *0[1]      0.00000 0.00000    501 79335    18714  7098820+   3549150+  284879    6919      59319483+  480     4       98.6  3714658207 2810609295 avivdozorets       N/A    N/A   N/A   N/A   N/A   N/A
28540  fish             0.0  00:00.41 1     0   14     3528K  0B    0B    28539 28539 sleeping *0[1]      0.00000 0.00000    501 5274     1427   131        53        17043     415       2270       59      0       0.0   0          0          avivdozorets       N/A    N/A   N/A   N/A   N/A   N/A
```

fish --version 
3.0.2  (same happens with 3.0.0)

$ uname -a 
`Darwin Avivs-MBP.lan 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64`

same happens on both iTerm2 (build 3.3.7) and Mac Terminal (Catalina 10.5).

any idea what's causing it / how to fix it ?
thanks in advance

**Comment by zanchey** [comment]
You could try taking a sample to see what it's doing: `sample [PID] 5 -file myfishsample.txt` will generate a profile over 5 seconds in `myfishsample.txt`, which can then be inspected and upload.

**Comment by themoah** [comment]
@zanchey thanks ! looks like some old pipe was running in background. Killed it :)
