### ISSUE TITLE
isatty returns true even inside a WM

### ISSUE THREAD

**Issue by equwal** [fish-shell/fish-shell#6355]
Running isatty from my `xterm` returns successfully. Oddly enough, my `tty` does not return `/dev/ttyN`, so it looks like the problem is with fish.

My system:
StumpWM :1st_place_medal: 
Xterm :100: 
fish α

**Comment by zanchey** [comment]
The documentation is misleading here. From the glibc manual: `isatty` tests whether a file descriptor refers to a terminal.

The behaviour is correct, but the documentation refers to "a tty", which I suppose could mean a terminal, a virtual console, a serial console or a teletypewriter (presumably would nearly always be false).

**Comment by equwal** [comment]
> The documentation is misleading here. From the glibc manual: `isatty` tests whether a file descriptor refers to a terminal.
> 
> The behaviour is correct, but the documentation refers to "a tty", which I suppose could mean a terminal, a virtual console, a serial console or a teletypewriter (presumably would nearly always be false).

the behaviour I desired was more something like a /login shell/.

Here is broken code:
```fish
if isatty stdin
  echo "I should only run in a login shell, right?
end
```

**Comment by zanchey** [comment]
Try `if status is-login`.

**Comment by equwal** [comment]
> Try `if status is-login`. `isatty` is for (eg) working out whether your function is running in a pipeline or connected directly to the terminal.

This works. I think this issue may be more about me misunderstanding the perhaps ambiguous docs.
