### ISSUE TITLE
Web URLs generated by `help` are broken for anchored links

### ISSUE THREAD

**Issue by ohk2kt3t4** [fish-shell/fish-shell#6362]
**Expected behaviour**
When help files cannot be found locally on the system, `help` [sends you to](https://github.com/fish-shell/fish-shell/blob/b5d00754067bbbbac3be1ed19aed4376853c2bbe/share/functions/help.fish#L147) the online docs.

**Actual behaviour**
For some reason (escaping the hash char?) anchored links have a  [backslash prepended before the anchor](https://github.com/fish-shell/fish-shell/blob/b5d00754067bbbbac3be1ed19aed4376853c2bbe/share/functions/help.fish#L109-L116) 
in the source code which ends up producing an invalid URL which cannot be accessed.
e.g. `help globbing` tries to send me to `https://fishshell.com/docs/3.0/index.html/#expand` which 404s. Removing the slash produces a valid URL: `https://fishshell.com/docs/3.0/index.html#expand`

![image](https://user-images.githubusercontent.com/24377231/69779644-0b6f0280-11ec-11ea-9136-6ed028b80875.png)

**Observations**
The script can end three different ways:
1) $fish_browser /c "start $page_url"
2) eval "$fish_browser $page_url &"
3) eval $fish_browser $page_url
For 2 and 3, eval deals with the escaped hash character, but in the first case the raw string is being passed which causes the invalid URL.

**Fix**
Wrap 1) with an eval to match 2) and 3). Have tested this and it resolves the issue.

(or don't quote the hash character in the first place, is it even necessary?)

Environment:
- fish, version 3.0.2-1861-gb5d00754 (freshly built from master)
- running under WSL on Windows 10

**Comment by ammgws** [comment]
Will be fixed with #6358
