### ISSUE TITLE
[Documentation] Typo: Pipes and Redirections

### ISSUE THREAD

**Issue by ChristoferK** [fish-shell/fish-shell#6376]
A potential typographical error in the online documentation under the [_Pipes and Redirections_](http://fishshell.com/docs/current/tutorial.html#tut_pipes_and_redirections) section, found in the following extract:

> `stdin` and `stdout` can be redirected via the familiar `<` and `>`. `stderr` is redirected with a `>2`.
> ```
> > grep fish < /etc/shells > ~/output.txt 2> ~/errors.txt
> ```

### Suggested Edit

> `stdin` and `stdout` can be redirected via the familiar `<` and `>`. ***`stderr` is redirected with a `2>`.***

#### <sub>Rationale</sub>
&nbsp;&nbsp;&nbsp;&nbsp;<sup>**1)** The description is clear that it is `stderr` that would be redirected [***to*** _something], rather than _something_ that would be redirected ***to*** `stderr`, which is what `>2` is better described by;</sup>
&nbsp;&nbsp;&nbsp;&nbsp;<sup>**2)** The code snippet immediately following confirms that it is, indeed, `stderr` getting redirected, and correctly does so using `2>`.</sup>

**Comment by faho** [comment]
https://github.com/fish-shell/fish-shell/commit/8e41e3337c4f2685505b82bbdf99d2b04125519e already fixed this in master
