### ISSUE TITLE
Have ctrl-c trigger redraw prompt line

### ISSUE THREAD

**Issue by ktm5j** [fish-shell/fish-shell#6394]
Hi Folks

I wanted to suggest an "enhancement".  I frequently scroll back up through my terminal output while viewing the output of past commands... with bash and other shells I could simply hit ctrl-c as a simple (and generally safe) way of returning to the bottom.  However if you hit ctrl-c in fish, it doesn't kill the prompt line and draw a new one like bash, and so it does not tell my terminal emulator that there's been input and it should scroll back down.

Now I don't think fish should adopt the same behavior that bash has, as it wastes a line of output space.  However if you could redraw the active prompt line over top of itself (instead of drawing a new one) then I think that should trigger my terminal to scroll down.

The other ways of getting my terminal to scroll back to the prompt are: 1. Hitting enter (dangerous!), 2. Typing text (passing input, could cause unwanted effects if there's a program waiting for input) or 3. Hitting the 'up' arrow (still passing input).

Does anyone else think this would be useful?  I'd be happy to write the code if there's interest.  It seems to me like this change wouldn't break anything or affect users.

**Comment by krobelus** [comment]
Makes sense, right now pressing ctrl-c in `xterm` and `konsole` does not scroll to the bottom if the commandline is empty (since no new output is generated).
A fix should be done in `share/functions/__fish_cancel_commandline.fish`.

**Comment by faho** [comment]
This works for me?

`__fish_cancel_commandline` does `commandline -f repaint`, which instructs fish to redraw the commandline (including the prompt)?

This does scroll to the bottom for me in both konsole, gnome-terminal and xterm?

**Comment by krobelus** [comment]
It works unless the commandline is empty

**Comment by faho** [comment]
Ah, okay. That's easy to fix then - we only repaint if the commandline isn't empty. So we just change it to repaint always.

**Comment by ktm5j** [comment]
Thanks!! Much appreciated
