### ISSUE TITLE
How do I edit fish so I can cd into directories that have spaces without quotations/slashes

### ISSUE THREAD

**Issue by Joe23232** [fish-shell/fish-shell#6399]
If I want to cd into a directory, or start a file or whatever, I wish I can do it without using quotations or slashes.

Example I want to cd into a folder named `New Folder`. I would have to do `cd "New Folder"`. Is there some config file I can modify so that I can type 'cd New Folder' without having to use quotations or slashes, just like with cmd on Windows?

And the same goes for starting a file or creating a file or anything. Example `nano file name.txt` or another example `mkdir New Folder`?

Lastly lets say I list out all the files in a directory via `ls` command

```
 Folder/  'New Folder'/
```
So now if I double click on `Folder` it will highlight it. But if I want to double click to highlight `New Folder` it is not possible. Is there a way to change this so I can double click and it will high light `New Folder`?

**Comment by faho** [comment]
Sorry, but no. Quoting is a fact of life and the only things we could do here would make cd different from anything else, which makes things more inconsistent and therefore worse.

**Comment by Joe23232** [comment]
I am not asking if the team can change it, I am asking if _I_ can change it via config file?

**Comment by Joe23232** [comment]
@faho I am not asking if the team can change it, I am asking if _I_ can change it via config file?

**Comment by faho** [comment]
You could modify the `cd` function. See `funced cd`. The gist is to remove the check for number of arguments and pass `"$argv"` in quotes to `builtin cd`. I don't recommend it.

**Comment by zanchey** [comment]
OK, you have three questions here...

The first is about the `cd` command, which is actually quite possible though difficult to get 100% right. You would need to write a new `cd` function, ideally wrapping the default function or similar, which can be as simple as this:

```fish
functions --copy cd orig_cd
function cd
    orig_cd -- "$argv"
end
```

However, this breaks tilde expansion, and might have other unforseen side effects.

The second, the more general case (eg nano, other programs), is not possible without losing the ability to pass command-line switches and multiple arguments. Even `cmd.exe` can't do this:

```
C:\Users\zanchey>cd Application Data
C:\Users\zanchey\Application Data>cd ..
C:\Users\zanchey>icacls Application Data
Invalid parameter "Data"
```

Finally, mouse selection is not handled by fish, but is handled by your terminal. You may be able to configure it to select in a different way, but maybe not.
