### ISSUE TITLE
`type` should have a "succinct" option that does not expand functions

### ISSUE THREAD

**Issue by hivehand** [fish-shell/fish-shell#6402]
The `type` command is currently a bit inconsistent in terms of its expressiveness. If I ask for the type of an executable file, I'm told that:

```
<file> is <path>
```

Likewise, if I ask for the type of a builtin, I am told that:

```
<command> is a builtin
```

If, on the other hand, I ask for the type of something that turns out to be a function, I may very well get a screenful or two of function body.

Most of the time, what I want when I invoke `type -a` are the answers to two questions:

1. What will be run if I invoke this command?
2. What other things have the same name, but are currently overridden by the answer to #1?

Having to wade through the function source code makes answering those questions harder rather than easier.

I would therefore like a flag of the form `-s/--summary`, applicable to both bare `type` and `type -a`, that limits the output for functions to something like:

```
<command> is a function (loaded from <path>)
```

If the path isn't available (because `<command>` is a function generated by an alias in my `config.fish`, for example), then just:

```
<command> is a function
```

If no one immediately screams at me that this is the dumbest idea they've ever heard, I may take a crack at implementing it myself.

**Comment by faho** [comment]
It does: `type -t`

**Comment by hivehand** [comment]
Sorry, I should have been clearer. I'll use `ls` as an example. On my system (a Mac) there are three of them. I have an alias, `ls`, which is a wrapper around fish's original `ls` function, just with a few extra arguments. Then there's GNU `ls`, which came as part of the `coreutils` package I installed via Homebrew, and which the `ls` function ultimately invokes. Underneath all of that is the BSD `ls` that originally came with macOS.

`type -t ls` only tells me that `ls` is of type `function`.

What I actually want to know is the hierarchy: how many layers there are, and what's obscuring what. I'd _like_ to see `type -a -s ls` tell me:

```
ls is a function
ls is /usr/local/opt/coreutils/libexec/gnubin/ls
ls is /bin/ls
```

Right now, the closest I can come is `type -a ls`, which throws the actual definition of the `ls` function in there. When a function is, unlike my alias wrapper in this instance, substantive, the path to the function can be separated from the paths to the additional executables by screenfuls of function code. I'd like all of them to appear in a concise block.

If I actually want to see the definition of the function, I can get that via my shortcut to `functions`, just as when one of the executables is a script, I can see its source by pointing my pager at the path that `type -a -s` kindly provided.

I hope that clarifies what I'd like and why. Let me know if it doesn't.

**Comment by faho** [comment]
`type -at ls` will tell you the type for all the matches (something like "function", "path", "path" ). I suppose we could add a mode that tells you the actual path for all commands and the function.

I feel that showing the function definition by default is the correct thing, because you might not even be aware that's a thing you can show.

**Comment by hivehand** [comment]
Oh, I have no interest whatsoever in changing the default. That almost  _never_ works out well.

I'd just like an option to get what I want when I want it. 😁

I've taken a first stab at implementing what I have in mind, and will open a pull request momentarily. Let me know if you think it's remotely reasonable.

**Comment by faho** [comment]
I could swear at one point merging PRs that said "fixes XYZ" closed the issue, but it doesn't seem to work now.

**Comment by zanchey** [comment]
Has to be in the commit message.
