### ISSUE TITLE
Reuse information from command ouput

### ISSUE THREAD

**Issue by eetievent** [fish-shell/fish-shell#6404]
I really appreciate fish completion features.
I would like to suggest a feature to replace the mouse when copying and pasting information from the output the last command(s). It could be:
* _alt-shift-up_:
 to complete elements from the previous command output(s), like _alt-up_ from command history, or
* _alt-o_:
  a menu to select from the last lines of command output (like with _tab_ completion)
  (or maybe entering the external editor like _alt-e_ but with the content of last command output)

Perhaps it's possible to create such a shortcut with fish?
I currently use _|xsel -bi_ then _ctrl-v_, too long and not easy to select.

Also I havent't found a shortcut to search within the current command line.

Thanks

**Comment by faho** [comment]
This would require fish to capture all that command output (which it doesn't). That would be terrible, performance-wise, and quite hard to do especially when you're considering fullscreen applications like editors etc. Sorry, but that's not feasible.

**Comment by eetievent** [comment]
Ok, I understand.
To avoid the problem, may be it's be possible to do it one shot on demand?
Example: you run a find or grep command and you want to open one file from the result.
So this would be a shortcut to execute the current command (find), take its output, then give a selection menu to select one line from the output and begin a new command line with this line.
(other possibility: open the command external editor with the whole output).

**Comment by krobelus** [comment]
Yeah both is easily possible with custom functions.

> Example: you run a find or grep command and you want to open one file from the result.
> So this would be a shortcut to execute the current command (find), take its output, then give a selection menu to select one line from the output and begin a new command line with this line.

```fish
function output-to-commandline
    set -l cmd (commandline -o)
    commandline --replace ($cmd | fzf)
end
bind \ec output-to-commandline
```
Then type `find` and press Alt-c

> (other possibility: open the command external editor with the whole output).

```fish
bind \eg 'commandline --append "| vim -"; commandline -f execute'
```
