### ISSUE TITLE
`functions --details` output is at odds with its documentation

### ISSUE THREAD

**Issue by hivehand** [fish-shell/fish-shell#6407]
fish: 3.0.2
macOS: 10.14.6
iTerm 2: 3.3.7

The documentation for `functions` reads, in part, "-D or --details reports […] stdin if the function was defined interactively or on the command line or by reading stdin"

In actuality, `functions -D`, when applied to a function that was defined interactively, reports a single dash:

```
-
```

This would seem to affect, among other things, `type`, since the latest version in the repository examines the output of `functions --details` and looks for `stdin` rather than `-`.

**Comment by faho** [comment]
As I mentioned in #6411, it does say `stdin` for me.

Can you explain how you defined the function? If you just do

```fish
$ function banana; echo banana; end
$ functions -D banana
```
in an interactive session, does that print "-"?

**Comment by hivehand** [comment]
D'oh! Sorry, I think I just realized what's going on.

First and foremost, if I define `banana` interactively, as in your example above, then I do get `stdin`, as expected.

However, if I then do

```fish
$ alias plantain="echo 'Like a banana, but greener'"
$ functions -D plantain
```

I get "-".

So my fundamental mistake was thinking that functions created by `alias` counted as interactively defined. They are evidently their own thing, at least as far as `functions --details` is concerned. (In my defense, I don't deal with true interactively-defined functions on a regular basis, but have a bunch of aliases in my `config.fish`, because creating a slew of files containing one-line functions feels like overkill. Feel free to tell me that that's a terrible idea.)

Assuming that `functions --details` emitting `-` for `alias`-produced functions is considered the correct behavior, then the fix to this issue is simply to to add mention of that fact to the documentation. I'll take a first pass at drafting that.
