### ISSUE TITLE
Conditionally redirect output

### ISSUE THREAD

**Issue by keyboard-clacker** [fish-shell/fish-shell#6409]
This might be more of a general question, but I couldn't find any references to anything related to exactly what I want. My question is: Is it possible to conditionally redirect stdout in fish? I want to effectively do something akin to:

```fish
function update
  argparse --name="update" 'd/debug' -- $argv
  if test -n "$_flag_debug"
    set -l out_stream $stdout
  else
    set -l out_stream /dev/null
  end
  
  echo "Initiating complex update process..."
  git pull > $out_stream
  yarn install > $out_stream
  echo "Done"
end
```

Basically what I want to be able to do is generally have this `update` command not log anything, but if I pass `-d`, have it log out everything. the `echo` is just an example, but imagine having 5 or 10 of them. Right now I have two almost identical functions instead of setting `out_stream`, where I named one `_short_update`, and one `_debug_update`, where `_short_update` has `echo "Hello!" > /dev/null`, whereas `_debug_update` omits the redirection and just has `echo "Hello!"`. Thank you for reading! Let me know if this is unclear... I'm a bit fuzzy on the specific lexicon to use here haha.

**Comment by zanchey** [comment]
You can set `out_stream` to `/dev/tty` or `/dev/fd/1`, at least on Linux, macOS and FreeBSD. Setting it to `'&1'` doesn't work, but perhaps that will be enough for you.

**Comment by keyboard-clacker** [comment]
Hmmm maybe I'm doing it wrong, but when I try to redirect to a constant, it gives me an error @zanchey 
```
Invalid redirection target: $out_stream
```

**Comment by krobelus** [comment]
> Hmmm maybe I'm doing it wrong, but when I try to redirect to a constant, it gives me an error @zanchey
> 
> ```
> Invalid redirection target: $out_stream
> ```

This is fish preventing you from redirecting to an empty variable. You need to define the local variables in the outer scope:

```fish
function update
   ...
   set -l out_stream
   if test -n "$_flag_debug"
     set out_stream /dev/tty
   else
     set out_stream /dev/null
   end
   ...
end
```

**Comment by mqudsi** [comment]
Fish has some unresolved bugs in this area, but generally the "fishy" way *would* be to redirect the pipe to a `begin; ...; end` block, perform the logic in there, and then output to the desired target. Sadly there are some kinks in this workflow.

**Comment by keyboard-clacker** [comment]
Oooo that sounds interesting, thanks @mqudsi ! And @krobelus I see, I didn't know `if` created its own scope! Thank you, that worked for me 🎉
