### ISSUE TITLE
`type -p` and `type -P` behaviors are at odds with its documentation

### ISSUE THREAD

**Issue by hivehand** [fish-shell/fish-shell#6411]
fish: 3.0.2-1940-g15c6d8fd-dirty
macOS: 10.14.6
iTerm 2: 3.3

`type -p` and `type -P` do not currently behave, in all cases, as their documentation indicates.

`xs` is a function defined in its own file.
`xa` is an interactively-defined function.
`frotz` is a random word referring to neither a function nor an executable.

Neither of the functions have executable counterparts.

Invoking `type -p xs`, produces the path to its file, as expected.
Invoking `type -p xa`, produces a single dash (`-`) as output, rather than nothing.
Invoking `type -p frotz`, produces `type: Could not find 'frotz'`, rather than nothing.

Invoking `type -P` on all of the above produces `type: Could not find '<argument>'`, rather than nothing.

I believe that I have a fix for these in place, and will submit it shortly.

**Comment by faho** [comment]
> Invoking type -p xa, produces a single dash (-) as output, rather than nothing.

I can't reproduce this.

For me, it works like this:

```fish
$ function banana; echo banana; end
$ functions --details banana
stdin
$ type -p banana
$
```

`functions --details` does *not* print "-", it prints "stdin" like documented?

**Comment by hivehand** [comment]
Sorry. As I just noted in #6407, it turns out that only functions created by `alias` cause `functions --details` to emit a dash. This does not affect the implementation of `type` in the current release (3.0.2), but it does affect `type` at top-of-tree. I think that the fix for that aspect of the issue is a one-liner, and will update my related pull request shortly.
