### ISSUE TITLE
cd command in keybindings doesn't completes

### ISSUE THREAD

**Issue by ephemerr** [fish-shell/fish-shell#6413]
fish, version 2.7.1

I do binding like: 

`bind \cs "cd .."`

When I press Ctrl-s nothing happens, then I press Enter and fish go to parent folder. 

Is there a way to workaround this by telling to apply entered command immediately?

**Comment by faho** [comment]
It's not that fish doesn't do the cd, it's that it doesn't know to redraw the prompt, so you can't see that it did.

So bind `'cd ..; commandline -f repaint'`.

**Comment by faho** [comment]
I'm assuming the question has been answered.
