### ISSUE TITLE
Informative prompt broken

### ISSUE THREAD

**Issue by mcarans** [fish-shell/fish-shell#6416]
When I use the informative prompt, I get error:
Standard input (line 7): 
    if test $stat -gt 0
       ^
in function '_fishprompt_saved_prompt'
called on line 1 of file ~/.config/fish/shell-integration.fish in command substitution
called on line 1 of file ~/.config/fish/shell-integration.fish in command substitution
called on line 21 of file ~/.config/fish/shell-integration.fish in function 'fish_prompt' in command substitution

fish version is fish, version 3.0.2-1898-g1be8277f

I'm using qtdomterm on Linux Mint 19.2

I tried without 3rd party extensions and got another error:
test: Missing argument at index 2

~/.config/fish/functions/fish_prompt.fish (line 7): 
    if test $stat -gt 0
       ^
in function 'fish_prompt'
in command substitution

**Comment by krobelus** [comment]
Yeah, that should have been `$last_status`.
Fixed in master by 2f1a5e65d8a8d639926517df0b8ece2613b1f04c, thanks for filing!

**Comment by mcarans** [comment]
Thank you! I rebuilt and can confirm issue is resolved.
