### ISSUE TITLE
CDPATH .. ../.. etc. sets $PWD to relative path ie. path with ".."

### ISSUE THREAD

**Issue by sdothum** [fish-shell/fish-shell#6417]
fish, version 3.0.2
Linux 5.3.15_1 #1 SMP PREEMPT Thu Dec 5 10:45:59 UTC 2019 x86_64 GNU/Linux
alacritty terminal

If CDPATH includes ".. ../.." etc. cd's that are resolved with the relative ".." references cause $PWD to become a relative reference as well, eg..

    set -x CDPATH . .. ../..
    cd ~/.vim/after/plugins
    cd colors  # expecting $PWD == ~/.vim/colors

Instead, $PWD becomes "../../colors"

**Comment by krobelus** [comment]
Good catch, this should be fixed in master already by 5e274066e3ec199dd56d81f43db6ea276b6da019
