### ISSUE TITLE
How to change the default shell to fish for Ubuntu (windows subsystem)

### ISSUE THREAD

**Issue by Joe23232** [fish-shell/fish-shell#6425]
On Arch-Linux based distro I could easily change it via this command `chsh -s /bin/fish`, however for Ubuntu Linux sub system for Windows I get an error message `chsh: /bin/fish is an invalid shell`

Also how do I change its colours when it shows the current directory that I am in and when I output all the folders in the current directory (via the `ls` command)?

**Comment by ohk2kt3t4** [comment]
Are you sure that is the right path to fish on WSL?

I have fish set as my default shell in WSL and it's at `/usr/local/bin/fish` because I installed from master, but before that I am pretty sure it was at `/usr/bin/fish`.

What's the output of `which fish`?

**Comment by Joe23232** [comment]
@ohk2kt3t4 If I ran `chsh -s /bin/bash` then it runs fine but not for fish :/

`chsh -s /usr/bin/fish` This seems to run just fine, but how do I get it to run by default on Windows since I have to type in `bash` just to get the Ubuntu system to run on my command prompt? I want to get fish to run instead of bash.

> What's the output of `which fish`?

The output is `/usr/bin/fish`.

Do you know how to change the colors of fish in terms of when it outputs the current directory that I am in etc?

**Comment by krobelus** [comment]
> Do you know how to change the colors of fish in terms of when it outputs the current directory that I am in etc?

Run `help color`, it's probably `$fish_color_cwd`

**Comment by Joe23232** [comment]
> Run help color

I ran this command I get this output error.

```
Start : This command cannot be run due to the error: The system cannot find the file specified.
At line:1 char:1
+ Start "file:///usr/share/doc/fish/index.html#color"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCo
   mmand
```

**Comment by krobelus** [comment]
> > Run help color
> 
> I ran this command I get this output error.
> 
> ```
> Start : This command cannot be run due to the error: The system cannot find the file specified.
> At line:1 char:1
> + Start "file:///usr/share/doc/fish/index.html#color"
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOperationException
>     + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.Commands.StartProcessCo
>    mmand
> ```

Oh sorry this should be fixed in the imminent release
meanwhile use https://fishshell.com/docs/current/index.html#variables-color

e.g. `set fish_color_cwd blue`

**Comment by krobelus** [comment]
> `chsh -s /usr/bin/fish` This seems to run just fine, but how do I get it to run by default on Windows since I have to type in `bash` just to get the Ubuntu system to run on my command prompt? I want to get fish to run instead of bash.

Run the "Ubuntu" app in windows instead of "bash", then you get a terminal with your login shell

**Comment by ohk2kt3t4** [comment]
Can also open it by running `wsl` (assuming you only have one distro installed)

**Comment by Joe23232** [comment]
@krobelus Hi, it works thanks mate, but how do I set a specific colour using hex value?

**Comment by Joe23232** [comment]
@ohk2kt3t4 Is there a way to get Hyper terminal (for windows) to automatically use the fish shell from Ubuntu?

**Comment by ohk2kt3t4** [comment]
I've never used it so I have no idea, but it sounds like a telnet/SSH program - can't you just use SSH or whatever from within WSL itself?

**Comment by Joe23232** [comment]
Hyper terminal is a replacement for cmd. I just use it over cmd cause its more customisable @ohk2kt3t4

**Comment by ohk2kt3t4** [comment]
So if you run `wsl` from there, it should bring up your Ubuntu WSL. Then all you should have to do is chsh if fish isn't the default shell alreayd.

**Comment by Joe23232** [comment]
@ohk2kt3t4 That actually works mate thanks bro :)

One other thing, do you know how to change colour of text to a specific colour using hex value?

**Comment by krobelus** [comment]
see `set_color --help`, so like `00FF00`
find current settings in the output of `set -U | grep color`
there is also a web interface `fish_config` but that might not work until the release

**Comment by Nishant-Pall** [comment]
I tried using `chsh -s /usr/bin/fish`, it doesn't give any error but it doesn't seem to work as well. I have tried restarting the terminal as well

**Comment by zanchey** [comment]
> I tried using `chsh -s /usr/bin/fish`, it doesn't give any error but it doesn't seem to work as well. I have tried restarting the terminal as well

@Nishant-Pall it would be helpful if you could tell us what version of fish you are using, whether you are using Windows Subsystem for Linux (I assume yes) and what distribution, and what you mean by "doesn't seem to work". In general I would recommend opening a new issue or asking in https://gitter.im/fish-shell/fish-shell

`getent passwd (whoami)` should show you the current shell setting.

**Comment by Nishant-Pall** [comment]
> @Nishant-Pall it would be helpful if you could tell us what version of fish you are using, whether you are using Windows Subsystem for Linux (I assume yes) and what distribution, and what you mean by "doesn't seem to work". In general I would recommend opening a new issue or asking in https://gitter.im/fish-shell/fish-shell

My bad, I will keep that in mind. I was using WSL, and I managed to find the solution.
