### ISSUE TITLE
fd check failing on RHEL/CentOS 6

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#6435]
d6c71d77a968fe4d7169c added a littlecheck for file descriptors that is currently failing on RedHat 6:

```
Testing file checks/fds.fish ... Failure in checks/fds.fish:

  The CHECK on line 6 wants:
    0 1 2

  which failed to match line stdout:1:
    0 1 2 3

  when running command:
    ../test/root/bin/fish -C "set helper ../test/root/bin/fish_test_helper" checks/fds.fish
```

I've managed to reproduce this locally; a full log may be available at https://build.opensuse.org/package/live_build_log/shells:fish:nightly:master/fish/RedHat_RHEL-6/x86_64 (though OBS is currently offline).

**Comment by zanchey** [comment]
File descriptor 3 is open, and appears to be pointing to the `fish-shell/build/tests/checks/fds.fish` (inherited from parent?)

**Comment by zanchey** [comment]
Oh wow, this is because RHEL 6 still uses Python 2.6, where `subprocess.Popen` has `close_fds=False` by default.

**Comment by ridiculousfish** [comment]
Nice!
