### ISSUE TITLE
Patch parser to allow `time` to be followed by an expression

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#6439]
*I tried to do this myself but I don't have the time to dedicate to this at the moment.*

The [newly-added `time` builtin](https://github.com/fish-shell/fish-shell/commit/e5e66ac6d7e28db8b483359e1255d6e37fb8b84e) works great with both fish scripts (builtins, functions, aliases, etc) and external code and supports collecting clock/time info for both fish itself and all spawned children (meaning the cumulative wall/cpu clock can be reported after the execution of a function, comprehensive of all spawned processes or internal executions) but the parser does not treat it as anything other than a command, meaning while this works:

```fish
function foo
    for n in (seq 1 10000)
        test $n -eq 42
    end
end

time foo
```

this, on the other hand, does not:

```fish
time for n in (seq 1 10000)
    test $n -eq 42
end
```

because the parser isn't "reset" after the `time`.

I had it semi-working by adding it as a statement decorator, but I don't think that's the correct spot for it since it shouldn't be part of a pipeline (e.g. `time foo | bar` should be `time (foo | bar)` and `foo | time bar` should not be allowed).

**Comment by faho** [comment]
In general I don't think the current solution really *works*. The problem is that it's double-parsing - `time complete -C'git add '` complains that it has "too many arguments".

Let me know if you'd prefer another issue, I'd chalk this up to time not being hooked into the parser. It should be a decorator, not a proper builtin.

**Comment by mqudsi** [comment]
Yeah, that's an example of what I'm talking about. `time "complete -C'git add'"` works, but that's not how we want it to look.

**Comment by mqudsi** [comment]
OK, I changed the existing boolean job decorator into a generic job decorator (we can't use a statement decorator) and added `time` as one in 664d6fb13298976f35ae9278ebb7a08e9beb6feb.

```
mqudsi@ZBOOK ~/r/fish-shell> time complete -C"git add"
permission-reset        Alias for !git diff -p -R --no-color | grep -E "^(diff|(old|new) mode)" --color=never | git apply
add     Add file contents to the index

________________________________________________________
Executed in  197.07 millis    fish           external
   usr time  125.00 millis  125.00 millis    0.00 micros
   sys time   62.50 millis   62.50 millis    0.00 micros
```

**Comment by zanchey** [comment]
This appears fixed?

**Comment by faho** [comment]
Yeah, fixed.
