### ISSUE TITLE
time is implemented with clock_gettime, which is not portable

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#6440]
The merging of the builtin time function has caused some fallout on older platforms.

RHEL 6 has `clock_gettime` in librt, which is a reasonably easy fix in CMake which I'll try and get to shortly.

However, there is _no_ `clock_gettime` in macOS pre-10.12. These versions are out of security support, but we still have a number of other hacks in place to support versions older than 10.7.

Either a fallback needs to be put in place, or we need to formally decide to drop support for these older versions.

**Comment by zanchey** [comment]
(and if dropping support, remove the configure check and `#ifdef` used elsewhere for `clock_gettime`)

**Comment by faho** [comment]
Does anyone still use macOS 10.11? 10.12 was released in 2016 and it's not an OS for servers or embedded systems, and Apple seems fairly aggressive about enticing people to upgrade.

**Comment by Darkshadow2** [comment]
I still have a system running 10.11

**Comment by ridiculousfish** [comment]
For measuring wall time we should use the `chrono` stuff added in C++11. It's not pretty but it's portable.

example:

    using namespace std::chrono;
    auto t1 = steady_clock::now();
    ....
    auto t2 = steady_clock::now();
    double duration_sec = std::chrono::duration<double>(t2 - t1); // seconds as double
    long duration_ms = duration_cast<std::chrono::milliseconds>(t2 - t1); // msec as long

**Comment by mqudsi** [comment]
(I'm still using macOS 10.10)

I started off intending on using the C++11 chrono library but needed to use posix apis anyway to get cpu time (rather than wall time) and figured I'd just go all in because it let me use clock_monotonic_raw on Linux (which is resilient to ntp adjustments).

I can switch it back to chrono.
