### ISSUE TITLE
time needs docs

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#6442]
Since we now have a time builtin/decorator, it needs docs.

In particular there's apparently a way to toggle "verbose" output (I'd imagine it's the default, since that's pretty frickin' verbose), and I have no idea how.

**Comment by krobelus** [comment]
I've been thinking about tweaking the design of `time` to resolve some issues.
The solution might be to make it an ordinary builtin (like before),
or to change its position in the grammar, perhaps making it behave like `not` (that should fix 4.).

Some issues with time as it stands now as part of the grammar:

  1. time is not listed as builtin/does not have help output (easily fixable)
  2. time cannot be used as a function name anymore
  3. adding options to time would be quite unorthodox and complicate the grammar further
  4. `true && time sleep 1` surprisingly runs `/bin/time` on my system, same for `and time foo`
  5. time output is not redirectable

time as builtin/function:

- does not work for `time begin; ...; end` or `time for a in *; ...; end`
   users need to write functions instead
- does not apply to an entire job, but only a single process, but frankly i don't think this matters

So we can provide it as a normal builtin/function, which is well understood but does not have all the bells and whistles, or keep a grammar based implementation that does, at the cost of a more complex implementation. A builtin/function implementation also lets the user override `time` to use GNU time or something.

Tbf most of those issues probably only matter in a fraction of real-world uses.. but we should definitely fix `make && time something`.

**Comment by faho** [comment]
>time cannot be used as a function name anymore

I don't think it's possible to allow that.

Otherwise is `time foo` calling the "time" *function* with the argument "foo" or the command "foo" decorated with "time"?

>adding options to time would be quite unorthodox and complicate the grammar further

If we are to have a "verbose" output mode options seem like the simplest way to allow that?

>true && time sleep 1 surprisingly runs /bin/time on my system, same for and time foo

Yeah that needs to be fixed. Which is weird because `true && command sleep 1` runs the command "sleep", not "command"?

>So we can provide it as a normal builtin/function, which is well understood but does not have all the bells and whistles, or keep a grammar based implementation that does, at the cost of a more complex implementation. A builtin/function implementation also lets the user override time to use GNU time or something.

A function/builtin does *not* cut it here. Understanding blocks is *important*, because people actually do `time for`.

**Comment by krobelus** [comment]
Sounds fair, we can support a grammar similar to what bash uses:
`[time [-p]] [ ! ] command [ [|⎪|&] command2 ... ]`
(configured with TIMEFORMAT)

bash also does not support redirecting the output of time, so I expect no complaints about that
