### ISSUE TITLE
Regression in recursive function redirection to variable 

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#6443]
I'm not sure if this is the simplest reproduction for the bug or not, but the parser's detection of a valid redirection target was subtly broken (the naive case still works OK) in 33aff87c10d1f24cf87a4ffbae11f7317a426153 (per `git bisect`).

I discovered this issue when attempting to run my `pbpaste` implementation after installing a recent build: https://github.com/mqudsi/fish-config/blob/master/functions/pbpaste.fish, in particular this bit: 

https://github.com/mqudsi/fish-config/blob/master/functions/pbpaste.fish#L1-L6

For now, the simplest repro is the following:

```fish
mqudsi@ZBOOK ~/r/fish-shell> function foo
                                 if set -q argv[1]
                                     foo > $argv[1]
                                 end
                                 echo foo
                             end
mqudsi@ZBOOK ~/r/fish-shell> foo bar
fish: Invalid redirection target: $argv[1]
foo > $argv[1]
    ^
in function 'foo'
in function 'foo' with arguments 'bar'
foo
```

cc @ridiculousfish

**Comment by krobelus** [comment]
Seems to be fixed by 97dd5ece2.

**Comment by mqudsi** [comment]
Reopening to remind myself to add a test. 

(On mobile!)

**Comment by ridiculousfish** [comment]
pushing out of 3.1

**Comment by faho** [comment]
Adding to the 3.1 milestone, there really is no need to mark this as 3.2 because of a missing test.
