### ISSUE TITLE
Mere presence of uncalled statement causes erratic exit code 130

### ISSUE THREAD

**Issue by kseistrup** [fish-shell/fish-shell#6444]
# Problem

Mere presence of uncalled statement causes erratic **exit code 130**.

First observed in an 11 KiBi fish script, spanning more than 1400 lines, that has now been stripped to its bare essentials.

# Dramatis personæ

* **fish-1939**
  * git describe --long: `3.0.2-1939-gea7868988`
  * commit `ea7868988a4081d4a3351e3eb575967cee624d9b`
* **fish-2022**
  * git describe --long: `3.0.2-2022-g3274dbacf`
  * commit `3274dbacf49390a3dd428f15b40613c1183958f3`
* A simple fish script: `simple.fish`
* An even simpler fish script: `even-simpler.fish`

### Simple fish scripts

```sh
# This is the simple.fish script

function simple_main
    exit 127
    true
end

simple_main

# eof
```

and

```sh
# This is the even-simpler.fish script

function simple_main
    exit 127
    #true
end

simple_main

# eof
```

The only functional difference between the two scripts is that the latter has the call to `true` commented out:

```diff
--- simple.fish	2019-12-20 21:37:02.000000000 +0100
+++ even-simpler.fish	2019-12-20 21:37:53.000000000 +0100
@@ -1,8 +1,8 @@
-# This is the simple.fish script
+# This is the even-simpler.fish script
 
 function simple_main
     exit 127
-    true
+    #true
 end
 
 simple_main
```

It is worth noting that `true` is never reached in `simple.fish`.

# Observed behaviour

```sh
> fish-1939 simple.fish
[127]>
> fish-2022 simple.fish
[130]>
```

I.e., when run with `fish-1939`, the scripts exits with **exit code 127**, as expected, and when run with `fish-2022`, the scripts exits with **exit code 130** (which sounds like `SIGINT` or `^C`).

But wait, there's more:

```sh
> fish-1939 even-simpler.fish
[127]>
> fish-2022 even-simpler.fish
[127]>
```

Both scripts exit with the expected **exit code 127**.

```sh
$ uname -a
Linux finpe 5.4.5-arch1-1 #1 SMP PREEMPT Wed, 18 Dec 2019 19:48:51 +0000 x86_64 GNU/Linux
```
:paperclip: [simple.fish](https://github.com/fish-shell/fish-shell/files/3990244/simple.fish.txt)
:paperclip: [even-simpler.fish](https://github.com/fish-shell/fish-shell/files/3990246/even-simpler.fish.txt)

**Comment by kseistrup** [comment]
Bisecting (done by Adam Sjøgren, who doesn't have an MS Github account) reveals that d4daa286909c14f4bba5bc9db287fcea7fa66e5c is the first bad commit: “Correctly set the exit status in block and function processes.”

**Comment by zanchey** [comment]
Cool work bisecting; I can reproduce this on macOS and Linux with ec11bd4af
