### ISSUE TITLE
[Feature request] Ctrl+Alt+N and Ctrl+Alt+P to search through tokens

### ISSUE THREAD

**Issue by brainplot** [fish-shell/fish-shell#6449]
As an Emacs user, I use the Emacs keybindings a lot when using Fish.
For example, I move my cursor with <kbd>CTRL</kbd>+<kbd>A</kbd>, <kbd>CTRL</kbd>+<kbd>E</kbd>, <kbd>CTRL</kbd>+<kbd>F</kbd>, <kbd>CTRL</kbd>+<kbd>B</kbd>, cycle through my history with <kbd>CTRL</kbd>+<kbd>P</kbd> and <kbd>CTRL</kbd>+<kbd>N</kbd> etc...
As a result, my left pinky is basically always sitting near the left <kbd>CTRL</kbd> and the rest of my hands/fingers are near the center of the keyboard or near the home row, with my right index on the <kbd>P</kbd> and my right thumb on the <kbd>N</kbd>.

I really like the feature which allows to search through my history by tokens, currently bound to <kbd>Alt</kbd>+<kbd>↑</kbd> and <kbd>ALT</kbd>+<kbd>↓</kbd>. However, it's very uncomfortable for me to use because it forces me to stretch out my right pinky in order to reach for the arrow keys. I acknowledge the fact that someone who's not used to the Emacs keys may think that I could just lift my hand a little and use the arrow keys but it really doesn't come natural for me when 99% of the time my hands are basically fixed in one position.

My suggestion is, can we have some more emacs-y keys for searching through the history by tokens? Initially I was thinking about <kbd>ALT</kbd>+<kbd>P</kbd> and <kbd>ALT</kbd>+<kbd>N</kbd> but, from the Fish documentation on key bindings found [here](https://fishshell.com/docs/current/index.html#editor), I see that <kbd>ALT</kbd>+<kbd>P</kbd> is already bound and of course I don't want to break anybody's workflow!
I was thinking about <kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>P</kbd> and <kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>N</kbd> but that's just a suggestion.

Thanks for your attention and for the great work with this shell! :slightly_smiling_face:

**Comment by krobelus** [comment]
`history-token-search-backward` is also bound to <kbd>Alt</kbd>+<kbd>.</kbd> (as in other shells). There's no corresponding binding for `history-token-search-forward` though.

**Comment by faho** [comment]
Bind it yourself:

```fish
bind \e\cP history-token-search-backward
bind \e\cN history-token-search-forward
```

I don't think this is a great binding as ctrl-alt-n is quite hard to press (in fact I find alt-up easier?) and it's quite the emacsism, so I'd leave it up to personal customization.

**Comment by faho** [comment]
Yeah, closing it as a question because it's easy to do yourself if you happen to favor a different binding.
