### ISSUE TITLE
<W> fish: An error occurred while redirecting file '/etc/paths.d/Wireshark' open: Permission denied

### ISSUE THREAD

**Issue by simphide** [fish-shell/fish-shell#6450]
**1. fish --version:** fish, version 3.0.2
**2. uname -a:** Darwin Simons-MacBook-Pro.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
**3. echo $TERM:** xterm-256color

I am getting the following error when I start iTerm2:
`
Last login: Mon Dec 23 11:32:48 on console
<W> fish: An error occurred while redirecting file '/etc/paths.d/Wireshark'
open: Permission denied
Welcome to fish, the friendly interactive shell
`

I have not changed anything.

Does somebody else have this problem?

**Comment by krobelus** [comment]
Is `/etc/paths.d/Wireshark` a file that is not readable by your user?
That would trigger this error in https://github.com/fish-shell/fish-shell/blob/master/share/config.fish#L181

**Comment by simphide** [comment]
Yes, for some reason the file was not readable for everyone. I modified the permissions and now it works.

Thanks for your help!
