### ISSUE TITLE
[QUESTION] fish function as $EDITOR value?

### ISSUE THREAD

**Issue by lambdadelta34** [fish-shell/fish-shell#6451]
I'm using fish function to run my editor from terminal and i'm happy about it. And now i'm wondering - is it possible to somehow use same function as EDITOR env value? Git and psql, for instance are trying to run command under bash, and it expectedly fails to find it.

**Comment by krobelus** [comment]
If you want to use a fish function outside fish, you should create a script.
```fish
#!/usr/bin/fish
my-function $argv
```
Or create a `/bin/sh`-script for `$EDITOR`, which can then be used from any shell/IDE...

**Comment by lambdadelta34** [comment]
@krobelus Thank you, i thought there might be a way without creating extra files.
