### ISSUE TITLE
fuzzy find command history does not work when use tmux

### ISSUE THREAD

**Issue by oouxx** [fish-shell/fish-shell#6452]
fish, version 3.0.2

Linux wxx-pc 5.3.15-1-MANJARO #1 SMP PREEMPT Thu Dec 5 11:01:29 UTC 2019 x86_64 GNU/Linux

screen-256color

on-my-fish and gpakosz/.tmux
-->

**Comment by faho** [comment]
We're going to need some more info. In particular

- What are you trying to do?
- What happens?

**Comment by oouxx** [comment]
My wrong. I forgot to set tmux default shell. The zsh was launched
