### ISSUE TITLE
Pipenv completions fails

### ISSUE THREAD

**Issue by and-semakin** [fish-shell/fish-shell#6454]
This errors occurs each time when fish tries to autocomplete `pipenv` command first time, and then `pipenv` just works without completions.
```
$ pipenv run dv-: Command substitutions not allowed
from sourcing file -
	called on line 2 of file /usr/local/Cellar/fish/3.0.2/share/fish/completions/pipenv.fish

from sourcing file /usr/local/Cellar/fish/3.0.2/share/fish/completions/pipenv.fish
	called on standard input

in command substitution
	called on standard input

source: Error while reading file '-'
```

Additional information:

```
~ $ cat /usr/local/Cellar/fish/3.0.2/share/fish/completions/pipenv.fish
if command -sq pipenv
    pipenv --completion 2>/dev/null | source
end
```
```
~ $ pipenv --completion
_pipenv_completion() {
    local IFS=$'\t'
    COMPREPLY=( $( env COMP_WORDS="${COMP_WORDS[*]}" \
                   COMP_CWORD=$COMP_CWORD \
                   _PIPENV_COMPLETE=complete-bash $1 ) )
    return 0
}

complete -F _pipenv_completion -o default pipenv
```

I use `fish` installed from Homebrew repos on Mac.

```
~ $ fish --version
fish, version 3.0.2
~ $ echo $version
3.0.2
~ $ uname -a
Darwin Andreis-MBP.lan 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
~ $ echo $TERM
xterm-256color
```

I'm wondering what does this error with `'-'` mean.

**Comment by faho** [comment]
>I'm wondering what does this error with '-' mean.

"-" here is code for "standard input". It's because the input is piped directly to `source` - `pipenv | source`.

As you might see, the issue is that pipenv prints the completions for *bash*. It apparently determines the shell by checking $SHELL, and in your case that's not fish (most likely because it's not your login shell).

The solution is simple: Override $SHELL for the `pipenv` call.

**Comment by and-semakin** [comment]
Thank you for a quick response @faho! It works!

**Comment by faho** [comment]
Okay, no, $SHELL doesn't always work, so we're forcing it some more in 0e0d63c0df9a8718835297434d861312c3bb1e8.

(Really not a massive fan of click-completion and how convoluted it all is - just provide a flat file in the package, especially if all it's doing is calling your tool again!)
