### ISSUE TITLE
Fish irc channel

### ISSUE THREAD

**Issue by mindfulmonk** [fish-shell/fish-shell#646]
Both zsh and bash have channels on irc(bash is more than 500 a day). How about a #fish one? :)

**Comment by orbisvicis** [comment]
Mirror them: https://github.com/jhuckaby/Mirror-Bot.

**Comment by krader1961** [comment]
Closing since there is no clear rationale justifying the trouble of switching IRC networks.

**Comment by jcrben** [comment]
Sad choice. Almost everyone here wanted Freenode.

**Comment by zanchey** [comment]
Probably just as well in the end.
