### ISSUE TITLE
Fish completions for numeric parameters

### ISSUE THREAD

**Issue by jbarlow83** [fish-shell/fish-shell#6460]
Is there any way to write a fish completion that specifies the parameter should be a number (integer or float) that falls in a certain range?

An example of programs that could benefit would be `ffmpeg`. There are parameters that require an integer (like `-ac`, the number of channels) and those that can accept a float. Sometimes the number of possible values is too many to enumerate.

In most cases it wouldn't be acceptable for fish to actually complete an integer, but it could show description text to indicate the acceptable range of numbers.

Example:
```
$ ffmpeg -vol [TAB]
> (change volume [256=normal])

```

Other examples of common programs with many numeric parameters where a list of integers won't cut it: ImageMagick (convert/mogrify), img2pdf, Ghostscript, oggenc, `head`, `tail`...

Is there any way to do this right now? If there isn't, I think this would be a nice feature.

(Using fish 3.0.2.)

**Comment by faho** [comment]
Use `seq`:

```fish
complete -c whatever -a '(seq 0 256)'
```

Tho to be honest it's often not super useful to specify this as competing 256 saves no key strokes over typing it, and it accepting a number is usually clear already.

I had an idea about completion "hints" to explain the *kind* of argument that is expected - #2201. That would be much more useful than offering 256 candidates, especially when you can do other things as well, or when the number of candidates is even larger (like if a command accepts ip addresses - have fun enumerating those).

**Comment by jbarlow83** [comment]
Yes, hints is the kind of thing that would be helpful here.
