### ISSUE TITLE
mess with completion with odd unicode character

### ISSUE THREAD

**Issue by Estirp** [fish-shell/fish-shell#6464]
fish, version 3.0.2
Linux localhost 5.4.6-arch1-1 #1 SMP PREEMPT Sat, 21 Dec 2019 16:34:41 +0000 x86_64 GNU/Linux
xterm-256color

When I have some odd character in filename, fish do not print character correctly : it print some character multiple times. The real command executed is still correct.
exemple : 
> touch a🎧
> ls aa🎧 
> a🎧

Thanks.

**Comment by faho** [comment]
Set $fish_emoji_width to 2. This will be done for you in the upcoming 3.1 release (#5722).
