### ISSUE TITLE
`printf` inside subshell can break tty interaction of later command in parent shell

### ISSUE THREAD

**Issue by 0ion9** [fish-shell/fish-shell#6467]
Steps to reproduce:

`1`. Save the following function:

```
function l3
  argparse 1 b c d r s t u v w z C M -- $argv
  # the below line borks most's tty interaction
  set -l newargs  (set -l f _flag_{1,b,c,d,r,s,t,u,v,w,z,C,M}; printf %s\n $$f)
  # comment the above line and uncomment the following line in order to make most work:
  # set -l newargs

  for arg in $argv
    if string match -qr '^[+][0-9]+$' $arg
      set -a newargs $arg
    else
      # 1. existing file
      # 2. function
      #
      # eg `l3 l3` will, on my system, open the function definition for l3.
      set -a newargs (if test -e $arg; printf %s\n $arg; else; type -p $arg 2>/dev/null; end)
    end
  end

#  echo most $newargs
  most $newargs

end
```

It is a cut down version of a 'most' wrapper I was working on.
Note the two 'set -l newargs' lines. 

`2`. Run this function normally, possibly with debugging : `fish -d 5 -c 'l3 l3'`
`3`. The subshell call in the first `set -l newargs` line, causes the later invocation of 'most' to have no display or ability for user interaction (eg. quitting). You must then go to a different terminal tab and `killall most`. At this point, fish will exit normally, showing that it is not fish itself that locked up.
`4`. Comment the first 'set' line and uncomment the second. Now there is no subshell in use.
`5`. Run this modified function : `fish -d 5 -c 'l3 l3'`
`6`. Interaction with 'most' will work as normal.

*OS etc*:

`fish --version`: fish, version 3.0.2-2058-gd0edd984d
`uname -a`: Linux cooler 5.4.6-arch3-1 #1 SMP PREEMPT Tue, 24 Dec 2019 04:36:53 +0000 x86_64 GNU/Linux
`$TERM`: xterm-256color

Problem still exists in clean fish install :   Yes

**Comment by 0ion9** [comment]
Further narrowing down:

The following formulation of the `set` line is equivalent to the subshell version, and still causes `most` to hang. Therefore, the subshell is probably not the culprit.

```set -l f _flag_{1,b,c,d,r,s,t,u,v,w,z,C,M}
printf %s\n $$f | read -l newargs```

I initially typoed the `|` as `||` -- which caused `most` to operate normally. Therefore, I conclude that it is actually `read` which is interfering with the tty.

**Comment by krobelus** [comment]
Seems to be specific to `most`, because one argument is an empty string:
```
$ set -S newargs
$newargs: set in local scope, unexported, with 1 elements
$newargs[1]: length=0 value=||
$newargs: not set in global scope
$newargs: not set in universal scope
```

Running `most ""` gives me the same behavior (also in other shells). Observe that `most` reads any character (even <kbd>Ctrl</kbd>+<kbd>d</kbd>) without doing anything.

```
$ strace most ""
...
read(0, "a", 16383)                     = 1
read(0, "\r", 16382)                    = 1
read(0, "\4", 16381)                    = 1
read(0, "\3", 16380)                    = 1
```

**Comment by 0ion9** [comment]
Huh.
Seems you are right.
I thought that `$newargs`, as opposed to `"$newargs"`, would expand an array whose only content was an empty string, to 0 arguments. Apparently I'm wrong on that.

**Comment by faho** [comment]
>I thought that $newargs, as opposed to "$newargs", would expand an array whose only content was an empty string, to 0 arguments. Apparently I'm wrong on that.

$newargs expands to the array elements, each a separate argument.

In this case your `$newargs` has been set like `set newargs ""` because that `printf` prints an empty line (like `printf %s\n`, which is equivalent to `echo` without any arguments - which in itself isn't super clean, but waaaay too late to change, especially considering `printf` is a posix thing).

Closing as the question has been answered.

**Comment by 0ion9** [comment]
> $newargs expands to the array elements, each a separate argument.

hmm, I was probably confusing 'array with no elements' with 'array with a single empty element' then. I thought completely empty elements expanded to nothing rather than an argument.
