### ISSUE TITLE
hyphen/underscore-insensitive completion

### ISSUE THREAD

**Issue by olets** [fish-shell/fish-shell#6468]
What do you all think about supporting hyphen/underscore insensitivity? So that

```
$ mkdir test
$ cd test
$ touch a-b
$ touch a_b
$ ./a-<TAB><TAB>
```

would open a completion menu with a-b and a_b.

Zsh for example can be configured to do this. (Emulating Zsh is of course not the goal but for the record one way to do that is

```shell
# zshrc
zstyle ':completion:*' matcher-list 'm:{a-zA-Z-_}={A-Za-z_-}' 'r:|=*' 'l:|=* r:|=*'
```

in case you want to try it out.)

I personally find this useful. Don't know if it'd be bad news on certain systems.

I'm on
fish, version 3.0.2
macOs 10.14.6 (18G1012)

**Comment by mqudsi** [comment]
Someone correct me if I'm wrong, but it's already (recently-ish) implemented. However, fish completions are ordered by "match strength" and a `-` vs `_` is considered a case-insensitive match, so if there are any case-sensitive completions available, the case-insensitive match will be disregarded entirely.

I can't remember for certain, but I think either @floam or I added this. Or maybe he added it and I changed something about it. There's an issue about this for sure (on my phone, can't really search).

**Comment by olets** [comment]
Haven't found that issue yet but that inspired me to do more experimenting and yep it works. Sweet! Part of my trouble was a misunderstanding of fish's tab completion — I see now that non-executable files wouldn't show up as matches in that context anyway, which is smart and nice. (Not showing lower-ranked matches if there's a high-ranked one does surprise me, coming here from Zshland, but I get that it's how fish does things 👍)

Found one place where it doesn't behave the way I'd expect though:

Following

```
mkdir mydir && cd mydir && mkdir a-b
```

these behave the way I expect

```
# expand to `./a-b/`
./a_<TAB> 
./a-<TAB>

# expand to `cd ./a-b/`
cd ./a_<TAB> 
cd ./a-<TAB>

# expand to `cd a-b/`
cd a_<TAB> 
cd a-<TAB>

# expands to `a-b/`
a-<TAB>
```

but this doesn't

```
a_<TAB>
```

In my case that brings up a menu with some global executable `aria_…` MariaDB matches, but importantly no `a-b/` option.

It's symmetrical: with a directory named `a_b`, the only case that doesn't complete with the directory is

```
a-<TAB>
```

**Comment by floam** [comment]
Yeah I changed the magnitude of hyphens when sorting completions. I hadn't intentionally  thought to try to make - and _ equal though, neat. I did it mostly for better visual alignment and UX in the pager than when a `--foo` complete was sorted in front of `-f`.

**Comment by zanchey** [comment]
See #3584

**Comment by floam** [comment]
Oh! So what I did had no effect on that behavior, it was @mqudsi.
