### ISSUE TITLE
Builtins return exit status 0 when stderr is closed by using `2>&-`

### ISSUE THREAD

**Issue by norio-nomura** [fish-shell/fish-shell#6470]
`argparse` returns exit status 0 when stderr is closed by using `2>&-`.
```terminal.sh-session
$ argparse r-require= -- --require ; echo $status
argparse: Unknown option '--require'
2
$ argparse r-require= -- --require 2>/dev/null ; echo $status
2
$ argparse r-require= -- --require 2>&- ; echo $status
0
```
`false` is not affected by `2>&-`.
```terminal.sh-session
$ false 2>&- ; echo $status
1
```
I'm using `fish` installed by `brew install --HEAD fish`.
```terminal.sh-session
$ fish --version
fish, version 3.0.2-2100-gd0b0c9a77
$ echo $version
3.0.2-2100-gd0b0c9a77
$ uname -a
Darwin norio-nomura-MacBook-Pro.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
```
`fish` invoked by `sh -c 'env HOME=$(mktemp -d) fish'` behaves similarly.

**Comment by faho** [comment]
Not just argparse, `math` is also affected:

```fish
math error 2>&- && echo haha
```

I'd imagine this to be a general thing with how our builtins handle streams.


Note however that closing streams is typically false and not of much use at the best of times so I can't recommend doing it.
