### ISSUE TITLE
tab completion broken on 3.0.1 #5668

### ISSUE THREAD

**Issue by a7hybnj2** [fish-shell/fish-shell#6472]
Hi, I just wanted to check on this. I just `brew install fish` and the version I received still had the character issue. If you look at #5568 there was a fix in --HEAD so I again `brew uninstall fish; brew install --HEAD fish` and that fixed my problems.

I think I was lead to believe, maybe since the previous issue was closed, that it was fixed. Can anyone provide insight on this?

I am happy to run HEAD for now but just thought I would check.

**Comment by mqudsi** [comment]
Can you please continue this on #5568? We can reopen it if necessary, and everyone receives the notifications even if it's marked as closed.

**Comment by a7hybnj2** [comment]
Whoops I think it was supposed to be #5668
