### ISSUE TITLE
error: ‘std::make_unique’ has not been declared  using std::make_unique

### ISSUE THREAD

**Issue by mcarans** [fish-shell/fish-shell#6474]
When I try to build fish from source following the instructions, I get a build error:
error: ‘std::make_unique’ has not been declared  using std::make_unique

What is strange is that it was building just fine a month ago. 

My version of gcc is (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0.

**Comment by mcarans** [comment]
I have looked at this issue: https://github.com/fish-shell/fish-shell/issues/6357 but the difference is I have not changed the CXX standard in CMakeLists.txt to 14. I have made no changes to the files checked out of the repository and my build fails.

**Comment by zanchey** [comment]
I suspect you will need a completely clean build, as CMake doesn't always re-run the configure checks. Try removing your build directory and starting again.

**Comment by mcarans** [comment]
Thanks for your swift and helpful response!
