### ISSUE TITLE
argparse gives misleading errors for an option whose value has been omitted

### ISSUE THREAD

**Issue by 0ion9** [fish-shell/fish-shell#6483]
The error produced by argparse when an option's required value is omitted, 

a) is incorrect and misleading
b) differs from handling within builtins such as `string sub` (which I understand to be contrary to the design goals of argparse)

**Case 1**: ('incorrect claim that option is unknown')

```fish
function foo
   argparse r/required= -- $argv
end

foo -r
```

Output: 

```
foo: unknown option -r
Standard input (line 2): 
   argparse r/required= -- $argv
   ^
in function 'foo' with arguments '-r'
```

Compare `string sub`

`echo foo|string sub -l`

Output:

`string sub: Expected argument for option -l`

**Case 2**: ('misidentification of the option which is being claimed to be unknown')

This occurs when chaining short options, the last of which expects an argument, and then omitting the argument.

```fish
function foo
  argparse m/minimum-hiscore= q/quiet c/color -- $argv
end

foo -qcm
```

Output:
```
foo: Unknown option “-qcm”
Standard input (line 2): 
  argparse s/suppress-date m/minimum-hiscore= q/quiet c/color -- $argv
  ^
in function 'foo' with arguments '-qcm'
```

So to summarize, actual behaviour:

* Options with required arguments, whose argument the user omitted, are reported as *unknown* options
* If this option with a required but omitted argument is at the end of a chain of short options, the entire chain of options are reported as both a) a single option consisting of the entire chain, and b) an unknown option

Expected behaviour:

* Omitting a required argument causes a `funcname: Expected argument for option -f` error
* When the omitted-required-argument is at the end of a chain of short options, just the last character of that chain is used in determining the option name to include in the error.

----

`fish --version`: fish, version 3.0.2-2058-gd0edd984d
`uname -a`: Linux cooler 5.4.6-arch3-1 #1 SMP PREEMPT Tue, 24 Dec 2019 04:36:53 +0000 x86_64 GNU/Linux
`$TERM`: xterm-256color
Problem occurs in clean install of fish: Yes

**Comment by 0ion9** [comment]
@krobelus 
I really appreciate how quickly you got onto this. That said, I think you may have interpreted '*When the omitted-required-argument is at the end of a chain of short options, just the last character of that chain is used in determining the option name to include in the error*' in an overly literal way (possibly due to knowing details of the option-parsing machinery which I do not).
I was expecting the format `option -l` rather than `option l` (since this matches the way the option must be specified on commandline).

Anyway, no big deal, I just want to clarify what I actually meant.

**Comment by krobelus** [comment]
Yeah, that might be better
GNU `ls -Uw` just quotes the option character

**Comment by 0ion9** [comment]
Hmm.

A quick survey:
* cut, fold, paste, column, make, mkdir, mkfs,mkfifo, fsck, chcpu, rcp, paplay, fdupes, pnmtofiasco, pacsort, sed, msgcat, sudo, alsactl, patch, cp, fish : quoted single character (eg 'W')
* gcc, xev, ppmtogif, pampick, tmsu, pfmtopam, pnmrotate, bunzip2, mogrify, ld: quoted single character with - prefix (eg '-W')
* nroff,gs* (Ghostscript), python, dvipng, git, bash, dash, zsh, sh, xprop : Unquoted single character with - prefix (eg. -W)
* xbmtopbm, xzmore, pbmlife, xclip : -W: No such file or directory 
* bscalc : does not display the offending option, only the generic help message.

So if you're going by majority rule, then quoted single character probably wins; I'm pretty sure the rest of {core, bin, text, find, diff}utils will agree with these samples on the correct way to present invalid options.

If alignment with other shells in particular is more important, then 'unquoted single character with - prefix' would be the way to go (fish currently is the odd shell out here)

**Comment by krobelus** [comment]
Quoting is probably the way to go, for consistency within fish. Looking at the output of `git grep '_(.*%ls'`, I think there may be one or two other error messages that could be streamlined, too. Of course we'd need to update translations accordingly.
`
