### ISSUE TITLE
Autosuggestion complete shortcuts

### ISSUE THREAD

**Issue by MagixInTheAir** [fish-shell/fish-shell#6489]
## Feature Request

I noticed the default shortcuts for autosuggestion aren't configurable and I think the defaults have problems that can be improved.

The default are : ctrl+f or right arrow to accept all line, alt+right arrow to accept one word.
First, these defaults aren't meaningful (why choose f ?), consistent and practical (the lesser impact shortcut, which has more use cases, requires a hand move to reach the right arrow).

I suggest changing the default shortcut to ctrl+L (to be consistent with the vim "right move" shortcut), and using ctrl+L for the smaller-impact autocomplete (single word) and ctrl+shift+L for the higher-impact autocomplete (full command).

Finally, I would suggest to make the shortcuts configurable. Defaults cannot fit everyone and this being an important feature of the shell, I think it would be very helpful to add support for configuration.

Thanks for considering my feature request

**Comment by faho** [comment]
>First, these defaults aren't meaningful (why choose f ?),

*f*orward. Control-f is bound to the "forward-char" function, which as a special case accepts not just the one char of the suggestion it moves over, but all of it.

>I suggest changing the default shortcut to ctrl+L (to be consistent with the vim "right move" shortcut)

The default bindings are *emacs*-compatible (and emacs moves forwards on ctrl-f), if you want vim-compatible bindings there is the fish_vi_key_bindings function to enable the vi-compatible preset. Tho typically in vi you'd move in normal mode with l, not ctrl-l, which is "redraw", like our ctrl-l.

>Finally, I would suggest to make the shortcuts configurable. Defaults cannot fit everyone and this being an important feature of the shell, I think it would be very helpful to add support for configuration.

They *are*? That's what [bind](https://fishshell.com/docs/current/commands.html#bind) is for?

**Comment by MagixInTheAir** [comment]
The f for "forward" makes sense, then. There is still the problem that the low-impact autocomplete is less accessible than the high-impact full-line autocomplete.

I didn't know about bind, but I would suggest adding it to the documentation where the autocomplete shortcuts are explained then :)

**Comment by faho** [comment]
The "high-impact" one is the one you typically want, so it being more accessible is *the right thing*.

For suggestions, the ideal case is that you see just what you want, you press the right-arrow and it's this magical moment where we saved you typing ~10 characters, without you having to think or do much about it.

That's the case worth optimizing for, because every time it works you've saved a bunch of time. As soon as you have to think about how much you want to accept, the saving goes down rapidly until you could just be typing it in. (this is also why accepting character-by-character makes very little sense, which is why forward-*char* accepts the entire thing)

>I didn't know about bind, but I would suggest adding it to the documentation where the autocomplete shortcuts are explained then :)

Yeah we should probably write a chapter on customizing bindings. Let's track that in #6075.

**Comment by MagixInTheAir** [comment]
I don't agree, for the simple reason that the more you predict the higher the chance of getting wrong.

Let's take an example : I wanna install a package and type "s". The shell suggests "sudo apt install libcurl-dev". I don't want to accept until the end and need to remove a word (or two if I wanted to "upgrade" instead). I find myself using the low-impact shortcut a lot more often. 

Regardless, if the shortcuts are configurable, it's a lot less of an issue :)

**Comment by Brannua** [comment]
> I don't agree, for the simple reason that the more you predict the higher the chance of getting wrong.
> 
> Let's take an example : I wanna install a package and type "s". The shell suggests "sudo apt install libcurl-dev". I don't want to accept until the end and need to remove a word (or two if I wanted to "upgrade" instead). I find myself using the low-impact shortcut a lot more often.
> 
> Regardless, if the shortcuts are configurable, it's a lot less of an issue :)

Hi, are you alreay solved your problem ? How ?
