### ISSUE TITLE
Feature request: add `base16` default themes, the next evolution of `Tomorrow` themes

### ISSUE THREAD

**Issue by lucatrv** [fish-shell/fish-shell#6492]
The `Tomorrow Theme` is now superseded by `base16`:
[https://github.com/chriskempson/tomorrow-theme](https://github.com/chriskempson/tomorrow-theme)

`base16` is an architecture for building themes, which includes `Tomorrow Theme` itself:
[https://github.com/chriskempson/base16](https://github.com/chriskempson/base16)

In particular the `base16` default themes are an evolution of `Tomorrow`'s original themes, and include "dark", "light", and other variations:
[https://github.com/chriskempson/base16-default-schemes](https://github.com/chriskempson/base16-default-schemes)

The `base16` default themes are IMHO the best themes available today, I suggest to add them to `fish`.

**Comment by ridiculousfish** [comment]
Seems reasonable, these themes live in [controllers.js](https://github.com/fish-shell/fish-shell/blob/47b87dbeb7ca9c77c72d97daf03e02335e8d709e/share/tools/web_config/js/controllers.js#L80) if you want to take a whack at it.

**Comment by ridiculousfish** [comment]
Fixed in #6504

**Comment by lucatrv** [comment]
Thanks! Sorry I did not have the time to look at `controllers.js` yet...
IMHO the "Base16 Default Dark" theme is so nice that it should set as the new "fish" default!

**Comment by ridiculousfish** [comment]
How does "Base16 Default Dark" look on light backgrounds? The fish default theme has to look good on both since we don't know which the user is using.
