### ISSUE TITLE
Using wildcards to make a list and iterate over it?

### ISSUE THREAD

**Issue by cjappl** [fish-shell/fish-shell#6498]
version: 3.0.2

Darwin CJAPPL-MBP 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64

screen-256color

I am trying to make a list such as the following in a variable and iterate over it :

```
set -x _plugin_paths "/Users/testuser/Library/Audio/Plug-Ins/Components/Company"* "/Library/Audio/Plug-Ins/Components/Company"* "/Users/testuser/Library/Audio/Plug-Ins/VST3/Company"* "/Library/Audio/Plug-Ins/VST3/Company"* "/Library/Application Support/Avid/Audio/Plug-Ins/Company"* "/Users/testuser/Music/Ableton/User Library/Templates/"* "/Users/testuser/Library/Preferences/Nuendo 10/Project Templates/Company Music/"* "/Users/testuser/Library/Preferences/Cubase 10/Project Templates/Company Music/"* "/Users/testuser/Documents/Pro Tools/Session Templates/Company Music/"* "/Users/testuser/Music/Audio Music Apps/Project Templates/"* "/Users/testuser/Documents/Pro Tools/IO Settings/"*

function remove_plugins
    echo $_plugin_paths     << ends up echoing "empty" 
    for path in $_plugin_paths   < doesn't ever go through this loop
        echo $path
        sudo rm -rf $path 
    end
end
```

Unfortunately I have had no success. I have tried the wildcard inside the quotes, but I assume this doesn't work because bash also doesn't expand wildcards inside of strings.

**Comment by faho** [comment]
Do the wildcards match anything? Do any of these directories/files exist? Can you try the `echo` *outside* of the function?

**Comment by cjappl** [comment]
Yep! They definitely do match things. Echoing outside of the function has the same result

**Comment by faho** [comment]
Okay, let's try something simple:

First, let's see how `_plugin_paths` is set exactly, via `set -S _plugin_paths`.

Then, let's see if something simpler works:

```fish
set paths "/usr/bin/"*
echo $paths
```

Just so we've confirmed that wildcard matching in general works.

Then I've noticed that much of this is in /Users/testuser. Do you actually have read permissions there? Try `ls /Users/testuser/`.

**Comment by cjappl** [comment]
`$ set -S _plugin_paths                                                                                                                                                                                                         09:24:41
$_plugin_paths: not set in local scope
$_plugin_paths: set in global scope, exported, with 0 elements
$_plugin_paths: not set in universal scope`


`$ set paths "/usr/bin/"*                                                                                                                                                                                                       09:25:15[I]|cjappl@CJAPPL-MBP:~/D/C/cjappl_europa_panner_1_0                                                                                                                                                                                   $ echo $paths                                                                                                                                                                                                                  09:25:24/usr/bin/2to3- /usr/bin/2to3-2.7 /usr/bin/a2p /usr/bin/a2p5.18 /usr/bin/actool /usr/bin/addftinfo /usr/bin/afclip /usr/bin/afconvert /usr/bin/afhash /usr/bin/afida /usr/bin/afinfo /usr/bin/afmtodit /usr/bin/afplay /usr/bin/afscexpand /usr/bin/agentxtrap /usr/bin/agvtool /usr/bin/alias /usr/bin/applesingle /usr/bin/appletviewer /usr/bin/apply /usr/bin/apropos /usr/bin/apt /usr/bin/ar /usr/bin/arch /usr/bin/as /usr/bin/asa /usr/bin/asctl /usr/bin/AssetCacheLocatorUtil /usr/bin/AssetCacheManagerUtil 
...
`

`$ ls /Users/cjappl/     << this is the actual user I'm using for this test                                                                                                                                                                                                       09:28:01
Applications               Downloads                  Library                    Pictures                   Samples                    auvaltool                  open_terminal.sh`

Everything looks good here!

**Comment by cjappl** [comment]
Sorry, nothing to see here. I'm not sure what happened but when I tried to build up the variable from scratch it worked! 

`set -x _plugin_paths "/Users/cjappl/Music/Ableton/User Library/Templates/"* "/Users/cjappl/Library/Preferences/Nuendo 10/Project Templates/"*`

Thanks for taking the time to answer!
