### ISSUE TITLE
vi mode missing

### ISSUE THREAD

**Issue by arael** [fish-shell/fish-shell#65]
Maybe I overlooked in the documentation but it seems to me that the vi mode is missing. I think that fish shell is awesome but without the vi mode I cannot use it as my everyday shell. Is there any way to enable the vi mode in fish right now? 

Maybe it is possible to achieve this through the configuration somehow although I have doubts. It is more likely that this is a missing feature.

Thank you very much for all your work.

**Comment by Gonzih** [comment]
Ugh, I just updated fish nightly on my machine to the version fish, version 2.1.2-1247-gfbe28fd and now after command execution vim mode always jumps in to insert mode. I have hard times understanding what has changed. Any tips? Thank you.

**Comment by vially** [comment]
Most probably [this](https://github.com/fish-shell/fish-shell/commit/97aa1c033bcdd839ee3fe28431c786dde2354d13) has changed.

**Comment by Gonzih** [comment]
Ok, it's related to the #1933 issue. I actually don't like this change, feels weird. Not sure that blindly mimicking vim mode from zsh is a good idea on it's own. I will erase this binding in my configuration, not a problem.

Thanks for pointing this out, @vially

**Comment by ridiculousfish** [comment]
How do other vi-mode users feel about switching to insert mode after command execution? I merged that because it's what bash and zsh do, so I assumed it would feel natural, but maybe I was mistaken.
