### ISSUE TITLE
Is there support for pseudo device UDP

### ISSUE THREAD

**Issue by pjangam** [fish-shell/fish-shell#6502]
`fish, version 3.0.2`
Please add support for pseudo device UDP
I can run this command in bash but does not work in fish
`echo "This is my data" >> /dev/udp/127.0.0.1/9050`

**Comment by faho** [comment]
No, and there won't be.

This isn't something a shell should do. If you need to do networking, use purpose-built tools like `nc` or `wget` or `curl`.

**Comment by ridiculousfish** [comment]
Holy cow, this isn't a kernel thing?  bash actually specially recognizes the string '/dev/tcp'? That is crazytown.

**Comment by blahgeek** [comment]
Still, it would be great if fish can provide a builtin command to provide simple networking communication like nc, because nc is not universally available and using an external command introduces some overhead.

**Comment by faho** [comment]
Fish will not always provide everything. Networking is sufficiently complicated (and `nc` used little enough) that adding this is fraught with problems.

Use external tools.
