### ISSUE TITLE
fish hangs on OpenBSD 6.6

### ISSUE THREAD

**Issue by Darkshadow2** [fish-shell/fish-shell#6503]
bisected to b5d00754067bbbbac3be1ed19aed4376853c2bbe

Initially things seem well, but sourcing files / running commands will eventually cause fish to hang. It doesn't crash, it just stops accepting input.

It seems to get into a select loop ... maybe. OpenBSD's debugging tools are kinda awful.

Here's output from `ktrace`:
[ktrace.txt](https://github.com/fish-shell/fish-shell/files/4063482/ktrace.txt)

Here's the file I'm sourcing to make it hang. This just sets up `LS_COLORS` and `GREP_COLORS` environment variables but does so by parsing uvars with fish colors.  It doesn't call any external commands - it's all fish builtins.
[term_command_colors.fish.txt](https://github.com/fish-shell/fish-shell/files/4063496/term_command_colors.fish.txt)

Here's a little pic to show it's not accepting input (note I did `kill -TERM` in another session to end it, so the hung fish isn't entirely non responsive):
![ss](https://user-images.githubusercontent.com/896142/72413845-b4db6a80-373e-11ea-938a-b189e0c7acb2.png)

It's not in the picture, but I did also try `sh -c 'env HOME=$(mktemp -d) ./fish` and it still hangs, so isn't an issue with any config in my home dir. I even went further and did `env -i` (and set up a few default environment variables like `TERM` in addition to `HOME`) just to make sure and it still hangs. I'm running it from the build directory there, but how I learned it wasn't working was building master and having it hang on me after installing it 🤦‍♂️.

My apologies for only now reporting this - that commit was back at the end of November. I don't log into this system all that often, and only now thought of actually updating fish on it. The version of fish that I have running on the system now (and works) is the commit before the bisected one (`fish, version 3.0.2-1860-g106af5f56`).

**Comment by faho** [comment]
Which OpenBSD version are you running? I'm guessing 6.6?

Can you try to simplify the script? That thing's a handful!

**Comment by zanchey** [comment]
> Which OpenBSD version are you running? I'm guessing 6.6?

Yes, reported in the subject of the issue :-)

**Comment by faho** [comment]
Blergh, yeah, skim reading!

**Comment by Darkshadow2** [comment]
I included that script because it seemed to always trigger the hang. I'll play around with it and see if I can make a simplified version that does the same.

**Comment by Darkshadow2** [comment]
Alright, after playing around with it a bit, I've narrowed down what will trigger the hang. Seems to be the amount of command substitutions one does.

This will not hang:
`echo (echo hi (echo bye (echo hi (echo bye))))`

This will hang:
`echo (echo hi (echo bye (echo hi (echo bye (echo hi)))))`

Seems if you keep it below 5 it works fine, 5 or higher will hang. 

It also seems somewhat additive. I can make a function that passes if called directly, but hangs if done as a command substitution.

```fish
function testme
    echo (echo hi (echo bye (echo hi (echo bye))))
end
```

Calling `testme` directly works fine, but if I do `echo (testme)` it hangs.

**Comment by faho** [comment]
It also hangs for me when pasting, and I *can't* seem to find a way to interrupt out of hangs. In fact not even `kill -9` helps (IIRC that means it's hanging in the kernel, waiting for IO?)

The limit is *around* 5 for me - I've had a hang with 5, I've had it work with 5 and hang with 6. A hang's `-d5` output looks like:

```
<5> fish: pthread 0x4ec1f678240 spawned
<5> fish: intern /home/alfa/fish-shell/share/functions/fish_title.fish
<5> fish: intern /home/alfa/fish-shell/share/functions/fish_title.fish
<5> fish: pthread 0x4ec469a0a40 spawned
<5> fish: intern /home/alfa/fish-shell/share/functions/fish_title.fish
<5> fish: pthread 0x4ebf826a240 spawned
<5> fish: intern /home/alfa/fish-shell/share/functions/fish_title.fish
<5> fish: intern /home/alfa/fish-shell/share/functions/fish_title.fish
<5> fish: intern /home/alfa/fish-shell/share/functions/__fish_pwd.fish
<5> fish: pthread 0x4ec9784d640 spawned
<5> fish: pthread 0x4ec9784da40 spawned
<5> fish: pthread 0x4ec9784dc40 spawned
```

**Comment by faho** [comment]
Oh, forgot we had the new debug system. The `-d'*'` output:

```
exec-job-status: Set status of job 1 (printf ...) to 0 using short circuit
exec-job-exec: Executed job 1 from command 'printf "\e[?2004l"' with pgrp -2
proc-job-run: Start job 1, gid -2 (printf "\e[?2004l"), COMPLETED, NON-INTERACTIVE
exec-job-status: Set status of job -1 (__fish_disable_bracketed_paste ...) to 0 using short circuit
exec-job-exec: Executed job -1 from command '__fish_disable_bracketed_paste 'echo (echo 1 (echo 2 (echo 3 (echo 5 (echo 6)))))'' with pgrp -2
proc-job-run: Start job -1, gid -2 (__fish_disable_bracketed_paste 'echo (echo 1 (echo 2 (echo 3 (echo 5 (echo 6)))))'), COMPLETED, NON-INTERACTIVE
iothread: enqueuing work item (count is 1)
iothread: pthread spawned
iothread: pthread 0x9ec3b322440 got work
exec-job-status: Set status of job 1 (set ...) to 256 using short circuit
exec-job-exec: Executed job 1 from command 'not set -q INSIDE_EMACS' with pgrp -2
proc-job-run: Start job 1, gid -2 (not set -q INSIDE_EMACS), COMPLETED, NON-INTERACTIVE
iothread: enqueuing work item (count is 1)
iothread: pthread spawned
exec-job-status: Set status of job 2 (status ...) to 0 using short circuit
exec-job-exec: Executed job 2 from command 'status current-command' with pgrp -2
proc-job-run: Start job 2, gid -2 (status current-command), COMPLETED, NON-INTERACTIVE
iothread: pthread 0x9ec3b322840 got work
iothread: enqueuing work item (count is 1)
iothread: pthread spawned
exec-job-status: Set status of job 2 (pwd ...) to 0 using short circuit
exec-job-exec: Executed job 2 from command 'pwd' with pgrp -2
proc-job-run: Start job 2, gid -2 (pwd), COMPLETED, NON-INTERACTIVE
exec-job-status: Set status of job -1 (__fish_pwd ...) to 0 using short circuit
exec-job-exec: Executed job -1 from command '__fish_pwd' with pgrp -2
proc-job-run: Start job -1, gid -2 (__fish_pwd), COMPLETED, NON-INTERACTIVE
iothread: pthread 0x9ec3b322840 got work
iothread: pthread 0x9ece7877440 exiting
exec-job-status: Set status of job 1 (echo ...) to 0 using short circuit
exec-job-exec: Executed job 1 from command 'echo (status current-command) (__fish_pwd)' with pgrp -2
proc-job-run: Start job 1, gid -2 (echo (status current-command) (__fish_pwd)), COMPLETED, NON-INTERACTIVE
exec-job-status: Set status of job -1 (fish_title ...) to 0 using short circuit
exec-job-exec: Executed job -1 from command 'fish_title echo\ \(echo\ 1\ \(echo\ 2\ \(echo\ 3\ \(echo\ 5\ \(echo\ 6\)\)\)\)\)' with pgrp -2
proc-job-run: Start job -1, gid -2 (fish_title echo\ \(echo\ 1\ \(echo\ 2\ \(echo\ 3\ \(echo\ 5\ \(echo\ 6\)\)\)\)\)), COMPLETED, NON-INTERACTIVE
iothread: pthread 0x9ec3b322440 exiting
iothread: enqueuing work item (count is 1)
iothread: notifying a thread
iothread: pthread 0x9ec3b322840 got work
iothread: enqueuing work item (count is 1)
iothread: pthread spawned
iothread: enqueuing work item (count is 2)
iothread: pthread spawned
iothread: enqueuing work item (count is 3)
iothread: pthread spawned
iothread: enqueuing work item (count is 4)
exec-job-status: Set status of job 6 (echo ...) to 0 using short circuit
exec-job-exec: Executed job 6 from command 'echo 6' with pgrp -2
proc-job-run: Start job 6, gid -2 (echo 6), COMPLETED, INTERACTIVE
iothread: pthread 0x9ece7877840 got work
iothread: pthread 0x9ec29183c40 got work
iothread: pthread 0x9ec29183440 got work
```

Same weird pthread address, 4 queued work items.

**Comment by faho** [comment]
Okay, after a couple of hours FLOGF debugging I have ascertained:

It's stuck waiting on the fillthread.

```c++
void io_buffer_t::complete_background_fillthread() {
    ASSERT_IS_MAIN_THREAD();
    assert(fillthread_running() && "Should have a fillthread");
    shutdown_fillthread_ = true;

    // Wait for the fillthread to fulfill its promise, and then clear the future so we know we no
    // longer have one.
    fillthread_waiter_.wait();
    fillthread_waiter_ = {};
}
```

That `wait()` above.

Which presumably means that the fillthread is hanging in `run_background_fillthread`, in which it indeed `select()`s.

And that's indeed what's happening - it's stuck in a `select()` loop, and the shutdown flag is never set. Which is weird, because we set it in `complete_background_fillthread()`, and that *is* executed. But, IIUC, that's in another thread.

So: Does OpenBSD have one of its famous security features here and we're doing something naughty?

**Comment by faho** [comment]
@ridiculousfish Help me obi-wan-fishnobi!

**Comment by ridiculousfish** [comment]
It's a deadlock. We need to spawn a new thread but the thread pool is filled up, because OpenBSD has a [hilariously low thread limit](https://github.com/openbsd/src/blob/master/include/limits.h#L58):

    #define	_POSIX_THREAD_THREADS_MAX		4

Nothing bad seems to happen if you spawn more than 4. Probably we should just not respect limits below 64 for 3.1. For 3.2, we should move away from the dedicated-fillthread model - a single thread can service multiple fds.

**Comment by ridiculousfish** [comment]
Looks like `PTHREAD_THREADS_MAX` is preferred, we should just switch to that.

**Comment by faho** [comment]
Yeah, switching to that works.

Tho deadlocking if the limit is reached is kinda awful.

**Comment by faho** [comment]
Okay, 64 is too low, especially if we're gonna hang if we reach it. Switching to fewer threads sounds like a great idea, but not like something I'd want to do for 3.1.0 *now*.

Research reveals that the thread limit is often quite high (ULONG_MAX on Free and OpenBSD), but on linux+glibc the #defines work out to 64, which is too low, and the real limit is runtime configurable (in /proc/sys/kernel/threads-max, 61990 on my system).

So I'm just going to hardcode a limit of 1024 (gluteally sourced, of course), because we seemingly can't detect it at compiletime (and error out if its too low), and the way we'd handle reaching the actual limit can't be worse than how we react to reaching what we think is the limit (hanging!).

**Comment by ridiculousfish** [comment]
I added a fix for this to `Integration_3.1.0` as c14d54032fb12e6b08617aefe95156c4ae809381

**Comment by zanchey** [comment]
@ridiculousfish I was going to fast forward Integration_3.1.0 along master to pick up this and a few other fixes; are you happy with that?
