### ISSUE TITLE
Variables assigned by `FOO=bar cmd` syntax should be passed to completion related functions

### ISSUE THREAD

**Issue by norio-nomura** [fish-shell/fish-shell#6507]
Currently there is no way to access the variables set in `FOO=bar cmd` style from complete related functions.
```terminal.sh-session
$ function foo; end
$ complete -c foo -s t -x -a '(echo $bar)'
$ complete -c foo -s t -x -a '(commandline -o)'
$ bar=baz foo -t
-tfoo  -t-t
```
I think it is better to call those functions with the variables set.

**Comment by krobelus** [comment]
Yeah, that makes sense, fixed by 05ddda9, thank you!

**Comment by zanchey** [comment]
I wasn't sure this is a good idea, but one example that helped me was setting `GIT_DIR` on the command-line then using the git tab completions, which should then work as expected.

**Comment by krobelus** [comment]
It should be an improvement, unless perhaps the user is running an expensive command substitution in a variable assignment, or if a command substitution has a side effect.
Therefore I guess we should disable expansion of command substitutions here (we do the same for completions, e.g. `git (echo show) ` has no useful completions.
