### ISSUE TITLE
what was that below-the-prompt search I stumbled onto?

### ISSUE THREAD

**Issue by olets** [fish-shell/fish-shell#6510]
I did something that gave me a below-the-prompt search function. It looked similar to some shell's incremental search, more or less like

```
>
search: _
```

I don't remember exactly what it said — this was a week ago, and at the time my knee-jerk reaction was "ctrl-c and get back to what I was doing." Now I'm trying to reproduce it, and can't find it or any documentation of such a thing. What was it?

```
> fish --version
fish, version 3.0.2
> uname -a
Darwin … 18.7.0 Darwin Kernel Version 18.7.0: … xnu-4903.278.19~1/RELEASE_X86_64 x86_64
> echo $TERM
xterm-256color
```

**Comment by faho** [comment]
The completion pager has a search function that says "search: ____", ctrl-s triggers it.

**Comment by olets** [comment]
Oh neat. Thanks
