### ISSUE TITLE
enhance abbr to support ANSI escape sequences

### ISSUE THREAD

**Issue by masukomi** [fish-shell/fish-shell#6521]
trying to create an abbreviation that involves ANSI escape sequences for cursor movement or text color control isn't supported. 

* fish 3.0.2
* Darwin Kays-MacBook-Pro.local 19.2.0 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64 x86_64
* xterm-256color

> Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:

done and no change

>tell us how to reproduce the problem. Including an asciinema.org recording is useful for problems that involve the visual display of fish output such as its prompt.

```
 echo -e "foo\033[3Dbar"
```
outputs `bar` because the cursor as moved back and typing occurred 

```
abbr -a foo  "foo\033[3Dbar"
```

just causes errors either complaining about the square bracket or ultimately outputting the raw text if you escape it enough.

There should be a way to support ANSI escape characters in the expansion string so that we can control color and cursor position of the expanded text.

**Comment by faho** [comment]
We're not going to do this.

Coloring abbrs doesn't make any sense and would interfere with syntax highlighting.

Choosing a cursor position is a good idea, but escapes are a fairly awful interface for this.

Instead we should provide a _nice_ way to give the cursor position after expansion, and then fish should do the movement itself.

And that has already been asked for in #2287, so I'm closing this as a duplicate.
