### ISSUE TITLE
__fish_print_xdg_mimetypes returns MIME types only from .local/share/applications

### ISSUE THREAD

**Issue by YaLTeR** [fish-shell/fish-shell#6525]
fish version: 3.0.2
OS: Arch Linux
Terminal: Alacritty

The said function, used for completion of MIME types, returns only MIME types from `.local/share/applications` rather than system-wide. To see the issue, try to tab-complete `xdg-mime query default ` and see that only the .local MIME types are shown. When starting fish via `sh -c 'env HOME=$(mktemp -d) fish'` this freezes it altogether.

**Comment by faho** [comment]
Yeah, this was a fairly simple "/" confusion. I'd bet your system has $XDG_DATA_HOME unset or *with* a trailing "/" and $XDG_DATA_DIRS without.

Also if we didn't get any matching directories we'd run `cat` without any arguments, so it would try to read from stdin.

**Comment by YaLTeR** [comment]
> I'd bet your system has $XDG_DATA_HOME unset or _with_ a trailing "/" and $XDG_DATA_DIRS without.

That is indeed the case: the former is unset and the latter has no trailing slash in any of the entries. Thanks!
