### ISSUE TITLE
prompt is broken when the terminal is resized if the prompt string is randomly changed.

### ISSUE THREAD

**Issue by acomagu** [fish-shell/fish-shell#6532]
Env:
```
$ fish --version
fish, version 3.0.2
$ uname -a
Linux acm-manjaro 4.19.97-1-MANJARO #1 SMP Sat Jan 18 00:17:24 UTC 2020 x86_64 GNU/Linux
$ echo $TERM
xterm-256color
```
I reproduced in clean env(`sh -c 'env -i TERM=$TERM HOME=$(mktemp -d) fish'`)

If I set as
```
$ function fish_prompt
    switch (random choice 1 2)
        case 1
            echo -e 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaa\n>'
        case 2
            echo -e 'bbbbbbbbbbb\n>'
    end
end
```
and I resized window, I god an merged string of them as prompt like
```
bbbbbbbbbbbaaaaaaaaaaaaaaaaaa
>
```

GIF:
![deepin-screen-recorder_konsole_20200124215608](https://user-images.githubusercontent.com/1362750/73070754-860a8480-3ef4-11ea-92dc-9d6f4e849ccb.gif)

**Comment by ridiculousfish** [comment]
Handling resizing correctly is very challenging. :(

**Comment by soumya92** [comment]
Maybe here: https://github.com/fish-shell/fish-shell/blob/e9902159c2efd052db7bd6e282690bc5d7a2a494/src/reader.cpp#L1198, instead of just joining with newlines, we also prepend each line with the clear-to-end-of-line sequence?
