### ISSUE TITLE
Drop python2 support after 3.1

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#6537]
As we all probably know, python 2 is EOL, so it might be time to drop support for it.

We currently use python in a few places:

- webconfig
- manpage completion generation
- the docs (sphinx + configuration + our fish_indent_lexer)
- littlecheck
- some completion scripts (npm, bower, yarn, composer - anything that needs json)

All of which are optional and should fail cleanly if python isn't installed.

What I am proposing is that we stop explicitly checking and supporting python 2, and we start recommending python 3 (we already use it over 2 if available), after 3.1 is released. Nothing too rash, if an issue pops up we can still fix it, and if it's just cosmetics we should still prefer allowing python 2 to work.

Or we could take a more extreme stance and improve our code actively with things that don't work in py2, or only do that for some things.

**Comment by zanchey** [comment]
To inform the decision, on our current platforms that I would consider "tier 1":

* RHEL/CentOS 6 does not easily have Python 3 installable - this platform goes EOL in November 30 2020
* macOS does not ship with Python 3 anywhere, as far as I can tell - and it sounds like all Python versions will go in the future (https://developer.apple.com/documentation/macos_release_notes/macos_catalina_10_15_release_notes) 
* RHEL/CentOS 7 as of 7.7 has Python 3.6 installable

Other platforms are fine on cursory inspection, with a general minimum of Python 3.5 available.

**Comment by geoff-nixon** [comment]
> macOS does not ship with Python 3 anywhere, as far as I can tell - and it sounds like all Python versions will go in the future

The OS proper may not, but Xcode 11 ships with a full Python 3.7 at `/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework`.

**Comment by floam** [comment]
Yes - with Xcode you get python3 now on macOS.

**Comment by geoff-nixon** [comment]
> Yes - with Xcode you get python3 now on macOS.

Yes, and double-checking now, it's included in the "Command Line Tools" package as well: there's even `python3` (etc.) shims at /usr/bin/python3 which call `xcrun`. So if a user doesn't have Xcode or the CLI tools installed, the first time the binary is called, it walks you through a painless download/install. So I'd definitely say macOS is good to go with Python 3.

**Comment by mqudsi** [comment]
We call python in the background at first startup, the `xcrun` hack is insufficient.

**Comment by zanchey** [comment]
The non-availability of Python in macOS is a problem regardless of whether we proceed to drop Python 2.7 support; I think we can explore that separately. For now, it certainly doesn't sound like there's any direct opposition to focusing on Python 3.

**Comment by mqudsi** [comment]
Can someone more familiar with Python than myself explain the backwards compatibility story there? Do minor increments within the Python 3.x family introduce any language changes or is it just the availability of APIs in the standard library? Or are they merely indicative of completely backwards-compatible improvements, fixes, optimizations, etc. to the runtime?

**Comment by faho** [comment]
>Do minor increments within the Python 3.x family introduce any language changes

They can remove deprecated stuff. E.g. there was some [hubbub regarding python 3.9 doing that](https://tirkarthi.github.io/programming/2020/01/27/python-39-changes.html)

>or is it just the availability of APIs in the standard library?

APIs and syntax. E.g. python 3.6 introduced "f-strings", so you can format strings like

```python
animal='fish'
print(f'My favorite animal is the {animal}')
```

instead of

```python
animal='fish'
print('My favorite animal is the {animal}'.format(animal = animal))
```

Running this on older python would trigger a syntax error.

**Comment by mqudsi** [comment]
Thanks for the info!

**Comment by faho** [comment]
Okay, I'm pretty sure I dropped the last mention of python 2 from the documentation (in a broader sense).

That means the only remnants of python 2 are the completions for `python2`, which is entirely harmless and non-critical, and the `__fish_anypython` function.

That would be *the* step where we drop python 2 support. Our scripts might still be compatible, but running them with py2 would require hacks - making your own `__fish_anypython` function.

So: All aboard the py3 train?

**Comment by zanchey** [comment]
I'd leave it. It does not have significant performance impact or particularly complicate the implementation - as I understand it `python` may be Python 2 or 3 on some platforms, so I think the `__fish_anypython` function needs to remain for a while anyway.

**Comment by ridiculousfish** [comment]
Perhaps just "Support for Python2 has been dropped. Python 3.5 or later is required."
