### ISSUE TITLE
fish 3.02 does not tab autocomplete .zstd files/packages

### ISSUE THREAD

**Issue by siyia2** [fish-shell/fish-shell#6543]
### Info
  
  fish 3.02
  kitty
  linux-5.4+
  Manjaro

### Reproduce

Open a terminal in a local folder with .zstd files in it and try to complete a filename with tab autocompletion.

**Comment by zanchey** [comment]
I presume you mean for `pacman`? If so, this is fixed by #6212 which is in 3.1b1 and will be in 3.1.0 in a few weeks.

**Comment by siyia2** [comment]
not only for pacman it happens with all .zstd files regardless if i call them from pacman or not

**Comment by faho** [comment]
@siyia2 Please be specific. Which commands are you trying?

The default filename completion just completes *all files*. There's very little chance that they'd randomly exclude ".zstd" files. So it's down to the *scripted* completions, and they'd be different for each command.

**Comment by siyia2** [comment]
the files i try to autocomplete are indeed pacman packages, but if i try the tab completion without pacman in terminal it still doesnt work.

**Comment by siyia2** [comment]
oh well that's the default behavior, fish also does not complete any filename/type with tab unless you specify a program to use it, so it is a duplicate of #6212
