### ISSUE TITLE
Creating side effects of regular commands?

### ISSUE THREAD

**Issue by meeoh** [fish-shell/fish-shell#6544]
Not really an issue but more of a feature request I guess? I constantly switch between a dev and prod context in my terminal and was wondering if theres a way to set some sort of colouring/text highlighting when using a certain context. E.g `kubectl config use-context dev` would show default colouring, then `use-context prod` would show like a big red prompt or something.

Is this possible in fish?

**Comment by zanchey** [comment]
You could customise your prompt either to interrogate `kubectl` as to the operating context, or write a wrapper for `kubectl` which sets a variable that your prompt then checks.

**Comment by meeohh** [comment]
For the former, does the interrogate `kubectl` on every command?

**Comment by zanchey** [comment]
Yes.

**Comment by meeohh** [comment]
Thanks a lot @zanchey 
Made a function like this
```
function update_last_arg --on-event fish_postexec
  if [ "$argv" = "kubectl to config use-context production" ]
    set -g prodkube true
  else if [ "$argv" = "kubectl config use-context dev" ]
    set -g prodkube false
  end
end
```
Then edited the fish_prompt to have this
```
  if [ "$prodkube" = "true" ]
    set_color -b red
    echo -n 'PRODKUBE'
  end
```

:+1:

**Comment by meeoh** [comment]
Thanks a lot @zanchey 
Made a function like this
```
function update_last_arg --on-event fish_postexec
  if [ "$argv" = "kubectl to config use-context production" ]
    set -g prodkube true
  else if [ "$argv" = "kubectl config use-context dev" ]
    set -g prodkube false
  end
end
```
Then edited the fish_prompt to have this
```
  if [ "$prodkube" = "true" ]
    set_color -b red
    echo -n 'PRODKUBE'
  end
```

:+1:
