### ISSUE TITLE
Failure in checks/bad-option.fish on OpenIndiana

### ISSUE THREAD

**Issue by Mno-hime** [fish-shell/fish-shell#6554]
fish 3.1 beta1 test suite compiled with GCC 6.5 fails on OpenIndiana with:
```
Testing file checks/bad-option.fish ... Failure in checks/bad-option.fish:

  The CHECKERR on line 2 wants:
    {{.*fish}}: {{unrecognized option: Z|invalid option -- '?Z'?|unknown option -- Z}}

  which failed to match line stderr:1:
    ../test/root/bin/fish: illegal option -- Z

  when running command:
    ../test/root/bin/fish -Z
```

**Comment by zanchey** [comment]
This is a platform-specific message from `getopt_long`, so I guess that's why it fails.

**Comment by faho** [comment]
Luckily littlecheck allows for multiple messages here. So the option can be "unrecognized", "invalid", "unknown", "illegal", "bogus", "bad", "green" or "mysterious".
