### ISSUE TITLE
Failure in checks/cd.fish on OpenIndiana

### ISSUE THREAD

**Issue by Mno-hime** [fish-shell/fish-shell#6555]
fish 3.1 beta1 test suite compiled with GCC 6.5 fails on OpenIndiana with:
```
Testing file checks/cd.fish ... Failure in checks/cd.fish:

  There were no remaining checks left to match stderr:1:
    rm: Cannot remove any directory in the path of the current working directory

  when running command:
    ../test/root/bin/fish -C 'set -g fish ../test/root/bin/fish' checks/cd.fish
```

**Comment by zanchey** [comment]
>     rm: Cannot remove any directory in the path of the current working directory

That's an interesting implementation (compare https://www.dragonflybsd.org/mailarchive/bugs/2005-07/msg00022.html), but shouldn't indicate any functionality problems.

**Comment by Mno-hime** [comment]
Yes, I think similar difference has been discussed around fish 3.0 GA that current working directory can't be removed on illumos (OpenIndiana's core), but couldn't find the ticket.

**Comment by faho** [comment]
#5472, 1ee57e92447781b5ff79aaa7c55f6468fc84a37d.
