### ISSUE TITLE
Failure in checks/math.fish on OpenIndiana

### ISSUE THREAD

**Issue by Mno-hime** [fish-shell/fish-shell#6557]
fish 3.1 beta1 test suite compiled with GCC 6.5 fails on OpenIndiana with:
```
Testing file checks/math.fish ... Failure in checks/math.fish:

  The CHECK on line 134 wants:
    2

  which failed to match line stdout:39:
    20

  additional output on stderr:23:
    '0x2'

  when running command:
    ../test/root/bin/fish checks/math.fish
```

**Comment by zanchey** [comment]
@Mno-hime, can you show the output of:

```
math 0x2
math 5 x 4
math 2x 4
```

on OI?

**Comment by Mno-hime** [comment]
@zanchey:
```
newman@lenovo ~> math 0x2
                 math 5 x 4
                 math 2x 4
math: Error: Unknown variable
'0x2'
   ^
20
8
```

**Comment by zanchey** [comment]
My guess is that this is because tinyexpr calls `strtod`, which [on illumos does not recognise hexadecimal strings in default mode](https://illumos.org/man/3C/strtod).

Reading https://github.com/att/ast/issues/1307 I think the easiest thing to do is to replace `strtod` with `strtold`!

**Comment by faho** [comment]
Blergh.

Yeah, let's just switch to strtold.

**Comment by zanchey** [comment]
It's odd, because G++ with `-std=gnu++11` on Linux turns on all the feature test macros that should enable the right behaviour here.

@Mno-hime, could you try compiling with `CXXFLAGS` as `-D_XOPEN_SOURCE=700`?

**Comment by Mno-hime** [comment]
> @Mno-hime, could you try compiling with `CXXFLAGS` as `-D_XOPEN_SOURCE=700`?

Seems to be the same:
```
Testing file checks/math.fish ... Failure in checks/math.fish:

  The CHECK on line 134 wants:
    2

  which failed to match line stdout:39:
    20

  additional output on stderr:23:
    '0x2'

  when running command:
    ../test/root/bin/fish checks/math.fish
```

Our `STRTOD(3C)` says:
```
       In default mode for strtod(), only decimal, INF/INFINITY, and
       NAN/NAN(n-char-sequence) forms are recognized. In C99/SUSv3 mode,
       hexadecimal strings are also recognized.
```

I checked `CMakeFiles/CMakeOutput.log` and things have both `-std=gnu++11` and `-D_XOPEN_SOURCE=700` (the latter was added manually via `CXXFLAGS`). I also got a lot of `<command-line>:0:0: warning: "_XOPEN_SOURCE" redefined`.

I am not sure illumos supports SUSv4, so I even built with `-D_XOPEN_SOURCE600` (SUSv3), but no luck.

@pyhalov FYI.

**Comment by Mno-hime** [comment]
If I compile with GCC 8, it builds fine.

**Comment by Mno-hime** [comment]
Well this is our GCC 6 & 7 not enforcing C99/SUSv3 for C++. Feel free to close unless you think `strtold` changes anything here and you are willing to change to it.

**Comment by zanchey** [comment]
It's a reasonably intrusive change, so perhaps something we can look at for 3.2 or later, but I think better to leave it - @faho?

**Comment by faho** [comment]
Thinking some more about this, I don't think changing to strtold would really work without switching to long double all the way up (in builtin_math), which would be fairly useless to us, while it might increase memory usage and difference between systems/architectures.

So, since you can apparently compile fish with gcc 8 without too much hassle, please just do that.
