### ISSUE TITLE
Fail2Ban completion / privilege escalation in completion function

### ISSUE THREAD

**Issue by herrbischoff** [fish-shell/fish-shell#6559]
```
# fish -v
fish, version 3.0.2
```
```
# uname -a
FreeBSD [REDACTED] 12.1-RELEASE-p2 FreeBSD 12.1-RELEASE-p2 GENERIC  amd64
```
```
# echo $TERM
xterm-256color
```

I'd like to create a completion for fail2ban. However, since fail2ban requires root privileges and different operating systems have different mechanisms for elevating them (`sudo`, `su`, `pbrun`, `pfexec`, `runas`, `doas`, `dzdo`, etc.): what is the preferred way to do that in a completion function?

**Comment by zanchey** [comment]
The current completions for `sudo` and `doas`, at least, will complete the subcommand correctly (that is, `sudo fail2ban -<TAB>` will complete against the fail2ban completions). So you should just be able to write completions as normal.

Doing dynamic completions such as retrieving the jail list to use as completion arguments is a bit harder; I don't think there's a good answer when not running as root (a bit like how you can't tab-complete into non-readable directories).

**Comment by herrbischoff** [comment]
The latter one is the one I'm most interested in obviously. Without jail completion, it wouldn't make much sense. And I completely agree that there is no good answer (I can think of) but I figured I might as well ask. However, is there an elegant way of doing a proper error check? This way, one could at least output a gentle reminder instead of the permission error message just barfing in place.

**Comment by zanchey** [comment]
Parsing this looks like zero fun anyway...

```
Status
|- Number of jail:      1
`- Jail list:   sshd
```

**Comment by herrbischoff** [comment]
You're correct of course but it's not as bad as it looks:

```
grep 'Jail list' | sed -E 's/^.*:  //' | tr ', ' ' \n'
```

What looks like a double-space is a literal tab-character.

**Comment by faho** [comment]
>Doing dynamic completions such as retrieving the jail list to use as completion arguments is a bit harder; I don't think there's a good answer when not running as root

Yeah. Technically completions *can* ask for a password (stdin is connected to the terminal), but I don't think it's a good idea to escalate privilege just to look something up for a completion.

Also, if you need root to get the *info*, is there anything you can use it for without being root? That seems weird.
