### ISSUE TITLE
pacman -Suu completion?

### ISSUE THREAD

**Issue by Undeterminant** [fish-shell/fish-shell#656]
Under Arch Linux, the `pacman` commands supports the option `-Suu`, which indicates that packages should be downgraded as well as upgraded (`-Su` being just upgraded). The `-Qkk` option also perfoms an in-depth check of package files whereas `-Qk` just checks that the files are there.

I'm unsure if fish supports these types of flags for completions, but regardless, these particular instances should be implemented.

**Comment by faho** [comment]
This is currently not completely possible. Doing something like

    complete -c $progname -n "$sync; and not __fish_contains_opt -s u sysupgrade" -s u -l sysupgrade   -d 'Upgrade all packages that are out of date' -f
    complete -c $progname -n "$sync; and __fish_contains_opt -s u sysupgrade" -s u -l sysupgrade   -d 'Also downgrade packages' -f

(in the appropriate place in share/functions/__fish_complete_pacman.fish)
will offer "-u" a second time with the correct description if you do

    ´pacman -Su -<TAB>

but not if you do

    pacman -Su<TAB>

**Comment by pickfire** [comment]
What about:

    pacman -S<TAB>

To:
   
    pacman -Su

**Comment by faho** [comment]
Yeah, that works with the original description.

It's just that `pacman -Su<TAB>` doesn't offer `u` anymore.

**Comment by krader1961** [comment]
Closing because a) this is a really niche case, and b) we shouldn't have open issues for writing completions unless someone is actively working on it.
