### ISSUE TITLE
Possible 3.1 regression in completion ordering

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#6568]
From #6552, [this comment](https://github.com/fish-shell/fish-shell/pull/6552#issuecomment-581202028):

> Seems like whatever function that prints the completions when using complete interactively is sorting them

we should understand if this is a regression in 3.1.

**Comment by ohk2kt3t4** [comment]
Trying to reproduce with a slimmed down test case.

So far the below is working fine, so need to try some other things:
```
touch ~/.local/bin/foo; and chmod +x ~/.local/bin/foo

cat ~/.config/fish/completions/foo.fish
complete -k -c foo -l bar -x -a "a c b"
```
