### ISSUE TITLE
Screen flicker on Ctrl-L

### ISSUE THREAD

**Issue by ajp2455** [fish-shell/fish-shell#6569]
### Version Info
`fish --version`: fish, version 3.0.2
`echo $version`: 3.0.2
`uname -a`: Darwin macbook.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
`echo $TERM`: screen-256color

### Issue
When pressing Ctrl-L, the screen does clear, but there is a noticeable flicker before the screen is redrawn again. This does happen when using the default config. I think this might be because `clear` is being called. When using `bash` (or `zsh`), I do not see this flicker happen when using Ctrl-L. I do see it when using the `clear` command in `bash`, though.

 Any way for me to fix this by rebinding Ctrl-L to something else so that this does not happen?

Here is a video of the behavior: https://asciinema.org/a/mgHHjGTeEqJ69oFQBVJ5TOgeO

The long periods of flickering are when I am holding down Ctrl-L. I also do this in `zsh`, but it is not visible.

**Comment by zanchey** [comment]
It's not the calling out to `clear` that's the problem, but the repainting of the commandline; mine takes 12 milliseconds while clear only takes 2. You could try installing a simpler prompt, perhaps?

**Comment by ajp2455** [comment]
I thought it might be something like that too, but when in `bash` or `zsh`, running `clear` also produces a flicker, while Ctrl-L, doesn't create the flicker. I thought it might be something to do with the way `fish` handles clearing the screen.

Reverting back to the basic prompt does alleviate the problem some, but it is still noticeable.

**Comment by zanchey** [comment]
If you set the prompt to simply:

```fish
function fish_prompt; echo -n "> "; end
```

the flicker disappears entirely (at least on my machine), so I'm pretty confident that's what it is.

**Comment by buckshee** [comment]
You can make a terminal to clear itself with `printf "\e[2J\033c"`, and if Bash control+l is fine then I'd expect that to be nice and fast too.

To change the bind you can do `bind \cl printf\ \'e\[2J\\033c\'\ \; commandline\ -f\ repaint`

There area few reasons why the `clear` command could be slow, if you want to work that out a good start would be the output `clear -V` and to try some different terminal emulators.
