### ISSUE TITLE
Intermittent test failure in job-control-noninteractive

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#6573]
Very occasionally (less than 1% of the time) the check job-control-noninteractive fails:

```
Testing file checks/job-control-noninteractive.fish ... Failure in checks/job-control-noninteractive.fish:

  The CHECK on line 7 wants:
    hello

  which failed to match line stdout:1:
    pgroups differed, meaning job control worked

  additional output:
    hello

  when running command:
    env fth=../test/root/bin/fish_test_helper ../test/root/bin/fish checks/job-control-noninteractive.fish
```

I wonder if there's a subtle race condition in this check, or in the code it's testing?

**Comment by ridiculousfish** [comment]
This is super weird, it looks like the stdout is being reordered!

**Comment by zanchey** [comment]
In my tests it happens 0.1% of the time, but might be more likely on the heavily-loaded build machines.

**Comment by zanchey** [comment]
Wow, it happens a heap when running in parallel: `seq 20| parallel -n0 python3 ../littlecheck.py -s fish=../test/root/bin/fish -s fish_test_helper=../test/root/bin/fish_test_helper checks/job-control-noninteractive.fish`

**Comment by ridiculousfish** [comment]
Awesome find, a repro case!

**Comment by ridiculousfish** [comment]
Doesn't show on my Mac, but it does on Linux if I pump up the parallelism really high.

**Comment by krobelus** [comment]
I can reproduce this consistently on Linux with
```fish
$ echo 'status job-control full; command echo A; echo B' | fish
B
A
```

If I run it in [rr](https://rr-project.org/), then only B is printed for some reason.

```fish
$ echo 'status job-control full; command echo A; echo B' | rr record fish
B
```

Possible (crude) fix:

```diff
diff --git a/src/parse_execution.cpp b/src/parse_execution.cpp
index 2935fcdd1..aec9c2cd8 100644
--- a/src/parse_execution.cpp
+++ b/src/parse_execution.cpp
@@ -1254,7 +1254,7 @@ end_execution_reason_t parse_execution_context_t::run_1_job(tnode_t<g::job> job_
 
     job_t::properties_t props{};
-    props.wants_terminal = wants_job_control && !ld.is_event;
+    props.wants_terminal = parser->is_interactive() && wants_job_control && !ld.is_event;
```

**Comment by ridiculousfish** [comment]
Amazing repro! I can't imagine what would cause this out-of-order printing.

**Comment by ridiculousfish** [comment]
The problem is that that we unconditionally call `tcsetpgrp` even when stdin is not a tty. The `tcsetpgrp` fails, and so we don't wait for the job.

**Comment by ridiculousfish** [comment]
Returning an error on ENOTTY was always suspect; the fix is to just not do it. We're still mixing up job control with isatty, but this is at least a principled fix. Awesome find.
