### ISSUE TITLE
[Question] Is there a way to donate money to the project?

### ISSUE THREAD

**Issue by EPadronU** [fish-shell/fish-shell#6577]
Good day everybody,

First of all, I want to thank you all for such an awesome shell. Since the first time I tried Fish, I haven't look back. I really like it.

I would want to know if there's a method to donate money to the project (BTC, PayPal, OpenCollective, Patron...). 

Thanks a lot for your time,
I look forward to hearing from you on this matter.

**Comment by faho** [comment]
There isn't currently and we have no plans to add such a thing.

As far as I'm aware no fish developer is in need of money (I mean...tell me if that's not the case, folks), and the project itself has next to no costs.

Additionally I personally would probably have more hassle with accepting donations than it's worth, as I'm pretty sure Germany has some annoying tax laws in this area. So with the amount I'd expect I'd rather not bother, tbh.

So: No, but thank you for your interest!
