### ISSUE TITLE
3.1b1 Unicode wide char issue when built with Nix

### ISSUE THREAD

**Issue by cole-h** [fish-shell/fish-shell#6584]
When building the 3.1b1 "release" with Nix, the resulting binary displays the following warning when the prompt contains a unicode character such as `λ` or `❯`**:

```
<W> fish: Tried to print invalid wide character string
```

Bisecting the issue, this problem appears to have been introduced with 5134949a14a929997eaddee26c59f6656fa5a420. 9715db94348d76db9eaa5c2ec672aed08ddc110b (the previous commit) doesn't display this problem.

Something to note is that this issue does not occur when building outside of a Nix environment (aka as detailed in the README) -- the specified characters fail to display at all. It is entirely possible this is a problem with my system due to the fact that it is not pure NixOS and instead Nix + Arch, but I figured the people who would know best are you.

**Note: I tested both [Starship](https://github.com/starship/starship/) and [Pure](https://github.com/rafaelrinaldi/pure) prompts, and both exhibited this behavior.

### STR
1. Build fish-shell with Nix ([`default.nix`](https://gist.github.com/cole-h/f34eefe20020305629ae37d2bfb06898) to be built with `nix-build`)
2. Run `sh -c 'env HOME=$(mktemp -d) ./result/bin/fish'`
3. Run `starship init fish | source` (or set up Pure; I figured Starship was easier to demonstrate)
4. `<W> fish: Tried to print invalid wide character string`

---

For what it's worth, the message on master (6682f0e8ca2fd39ef5eb5c89dc23d2f413ba28bf) is:

```
warning: Tried to print invalid wide character string
```

**Comment by faho** [comment]
So the underlying issue here seems to be that your locale is not unicode capable, which is broken if you want to use non-ascii characters.

Fix that, and you'll get the actual output as opposed to it failing to display at all.

The commit you highlighted just added an error message. Which seems excessive (and we've removed such errors previously), so I'm dropping it down to a debug message, which we can then direct people to turn on if we suspect it's an issue.

-----

>Run starship init fish | source (or set up Pure; I figured Starship was easier to demonstrate)

I think we can boil this down to just `function fish_prompt; echo λ; end`.

**Comment by faho** [comment]
407a9e2dee27f9bf1f4cf206a4303cda5da14014 in 3.1 drops the message down to debug level 3 (0 is error, 1 is warning).

In master f44f9f1 sets it to a new debug category "output-invalid".

But still, the *real fix* is to fix your locale, to make it unicode capable.

**Comment by cole-h** [comment]
Definitely less annoying, now. Thanks for the fact action! I was more confused about why this wasn't a problem for anything prior to that specific commit. Looks like I'll have to go back to the totally-uncool `>` prompt.

---

As I suspected, it's an odd issue due to using Nix but not NixOS (locales are a bit touchy; see: https://github.com/NixOS/nixpkgs/issues/6878 and https://github.com/rycee/home-manager/issues/354).
