### ISSUE TITLE
Fish v3.1.0 fails to run on Catalina due to a library not loaded error (installed via fish-3.1.0.pkg)

### ISSUE THREAD

**Issue by amichail** [fish-shell/fish-shell#6586]
> ... ~ % /usr/local/bin/fish
> dyld: Library not loaded: /usr/local/opt/pcre2/lib/libpcre2-32.0.dylib
>   Referenced from: /usr/local/bin/fish
>   Reason: image not found
> zsh: abort      /usr/local/bin/fish
>

**Comment by zanchey** [comment]
Hmm, the package must be picking up my locally-installed libraries; probably the build script needs to disable that somehow.

**Comment by ridiculousfish** [comment]
I should have a fix in a few minutes.

**Comment by ridiculousfish** [comment]
I am mired in a hell of notarization and code signing.

**Comment by ridiculousfish** [comment]
The installer package should be good now. Please reopen if it's not working.

**Comment by faho** [comment]
Would it be possible to rename the fixed package to make it clear you got the fixed one?

**Comment by ridiculousfish** [comment]
Is the idea for users to be able to check which one they have installed, or would it be to verify when they visit the site that they're seeing the new package? Anyways I'll see how hard it would be to modify the site generator script for it.

**Comment by ridiculousfish** [comment]
Yeah I think so, I'll do it.
