### ISSUE TITLE
Strange directory tailing slash after upgrade to 3.1.0

### ISSUE THREAD

**Issue by douglarek** [fish-shell/fish-shell#6588]
```
~ $ fish --version
fish, version 3.1.0
~ $ echo $version
3.1.0
```

```
~ $ uname -a
Darwin local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
~ $ echo $TERM
xterm-256color
```

After upgrade fish from `3.0` to `3.1.0`, I got this:

<img width="1438" alt="Screen Shot 2020-02-13 at 1 06 37 PM" src="https://user-images.githubusercontent.com/1488134/74403388-fa847380-4e61-11ea-8184-116c49048020.png">

And how can I do to disable it ?

**Comment by zanchey** [comment]
This is thanks to 488e208cca9da3e6ecb07a6bfe13646805db59ed, which turned on indicators for all platforms. If you really hate it, you can override the ls function:

```
function ls --description 'List contents of directory'
    set -l opt -G
            command ls $opt $argv
end
funcsave ls
```

**Comment by douglarek** [comment]
@zanchey thanks, it works!
