### ISSUE TITLE
What is [I] and [N] ?

### ISSUE THREAD

**Issue by kmvan** [fish-shell/fish-shell#6589]
fish, version 3.0.2
Sometimes fish will show [I] or [N]. What is it?

![image](https://user-images.githubusercontent.com/3839554/74427942-0a687b80-4e93-11ea-8e01-6b7ea54a0e53.png)

**Comment by faho** [comment]
They are the vi-mode. "I" for "insert", "N" for normal.

If you don't recall enabling the vi key bindings some third-party "themes"
do it for you.

If you don't want the indicator make a 'fish_mode_prompt' function that
does nothing.

Km.Van <notifications@github.com> schrieb am Do., 13. Feb. 2020, 12:00:

**Comment by kmvan** [comment]
Oh, vi mode, got it. Thanks.
