### ISSUE TITLE
Short escape delay causes problems

### ISSUE THREAD

**Issue by datenreisender** [fish-shell/fish-shell#6590]
After upgrading to 3.1.0 (Thanks for the new release!), I was confused that key bindings with escape did not work anymore. I found out:

- [The default escape delay (to differentiate between the escape key and an alt-combination) has been reduced to 30ms, down from 300ms for the default mode and 100ms for Vi mode.](https://github.com/fish-shell/fish-shell/blob/master/CHANGELOG.md#new-or-improved-bindings-1)
- I can raise it again e.g. to 100ms with `set -U fish_escape_delay_ms 100` and this fixes the issue for me.

I am still confused, why with 30ms I am almost unable to type any escape key combination:
- After trying it a lot of times, I discovered that with the default 30ms I can accomplish it sometimes, but really only seldom.
- I tried to see whether it is caused by my terminal (iTerm 3.3.8), because it might be somewhat slow or introduce a delay. But I found out that it also happens with Terminal.app or kitty 0.16.
- Maybe the problem is worsened by my bit slow computer (2012 MacBook Pro).

I do not consider myself to be a very slow typist, so I wonder whether there is something wrong with the implementation that is only triggered on slower computers? If you think the current behaviour is just fine, then feel free to close this issue and I will happily live with setting `fish_escape_delay_ms` to a higher value.

**Comment by faho** [comment]
If you want to type escape and then a key to combine it, you'll have to increase the timeout. This is for the typical case where you don't do that and need to differentiate escape from alt.

**Comment by faho** [comment]
Unfortunately we're forced to pick, so we'll pick the normal case. Working as intended, sorry.

**Comment by psifertex** [comment]
How is it that other shells are able to have both vim and shell-meta work just fine but fish cannot? I'm confused.

**Comment by zanchey** [comment]
Do they? In bash the default timeout is controlled by the readline setting keyseq-timeout (defaults to 500 milliseconds), and in zsh by the KEYTIMEOUT option (defaults to 400 milliseconds). At least in my testing, the original problem can be reproduced (though zsh wisely does not include many M- style bindings in its default vi insert mode bindings).

**Comment by jdanbrown** [comment]
Reviving an old issue — can something like the rustyline solution be adopted here?
- https://github.com/kkawakam/rustyline/issues/416
- https://github.com/kkawakam/rustyline/pull/426

**Comment by faho** [comment]
@jdanbrown This issue is quite outdated and numerous things have changed since then.

Please try git master and see if that changes anything for you. In particular it now supports the kitty keyboard protocol, which will encode alt+x as different from escape and then x.

(that's the issue with "reviving" four year old questions)

**Comment by jdanbrown** [comment]
Oh sorry about that, I didn't read the original issue clearly enough before adding my comment. (And +1 reviving old issues is problematic in the first place.)

What I meant to do was ask if `fish_escape_delay_ms 0` could be supported using a race-y solution like what rustyline did above, but the currently supported min of `fish_escape_delay_ms 10` seems good enough I guess. I can outrun the 10ms delay if I really try, but in normal usage maybe 10ms will be sufficent. If that proves wrong then I'll come back and open a new issue.

(Aside: Can the new CSI commands potentially allow reducing `fish_escape_delay_ms` to 0? I tried turning them on in iTerm2 but `fish_escape_delay_ms 100` didn't auto-magically go away.)

✌️ Thanks for keeping fish going! I'm in the process of migrating from bash and am really enjoying it.
