### ISSUE TITLE
Redirection syntax seems broken

### ISSUE THREAD

**Issue by jschank** [fish-shell/fish-shell#6591]
#4194 

fish version:
**fish, version 3.1.0**

OS:
**Darwin serenity 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64**

Did not try fish without third-party customizations.

I have a script (.fish) which attempts to execute this line:
git checkout master > /dev/null ^&1

Issue #4194, which is closed, indicates that I am using the correct syntax.

However I get this error

~/.config/fish/functions/git-clean-branches.fish (line 51): Expected a string, but instead found a '&'
    git checkout master > /dev/null ^&1

This script was unchanged, and started breaking today.

Thanks,
John Schank

**Comment by zanchey** [comment]
Yes, I think that's broken.

As a workaround (and as recommended in future, as the `^` syntax will eventually be removed), you can use `>/dev/null 2>&1`.

**Comment by faho** [comment]
Bisects to 35671dd9f094cf8c643c9cf224c27a2b55578937.
