### ISSUE TITLE
conf.d load order changed in 3.1.0 release

### ISSUE THREAD

**Issue by tough-griff** [fish-shell/fish-shell#6593]
Prior to updating to fish 3.1.0, I was able to predict the load order of files in my `.config/fish/conf.d/` folder. I designed this folder with a `___env.fish` file to set some global exported variables that could be shared among configuration files that would load later.

Now, after updating to fish 3.1.0, the `__env.fish` file loads last instead of first.

**Comment by faho** [comment]
Yeah, I can reproduce. The order of globs changed.

As a workaround I recommend calling the file `00-env.fish` instead, as numbers will be much more stable, also across locales and such.

**Comment by zanchey** [comment]
This is due to 74a22ff4262b872668d9cca3279eece5b7e49350 discussed in https://github.com/fish-shell/fish-shell/issues/5634#issuecomment-473511513

**Comment by zanchey** [comment]
I'm not sure that the order of globs is guaranteed anywhere, though I agree that it's a bit obnoxious for it to change.

**Comment by faho** [comment]
I feel like the glob order should be uncoupled from the file completion order.

**Comment by faho** [comment]
Yeah, I've now reverted the changes to glob ordering since 3.1, but *only to glob ordering*. It's now uncoupled from completion ordering, so we can change that to our heart's content.
