### ISSUE TITLE
`/etc/...` files are being installed to `${prefix}/etc/...`

### ISSUE THREAD

**Issue by FFY00** [fish-shell/fish-shell#6595]
The files that should be installed under `/etc` seem to be prefixed by `CMAKE_INSTALL_PREFIX`, which should not happen. `CMAKE_INSTALL_PREFIX` is the install prefix, so `/usr`, `/usr/local`, etc., not the absolute prefix for the installation, `DESTDIR` is used for that. No files should be installed to `{/usr,/usr/local}/etc`.

**Comment by ridiculousfish** [comment]
Thanks for filing! This is building from source, not with a released package, correct? I want to understand if this reflects a problem with 3.1.0.

**Comment by FFY00** [comment]
Yes, I am packaging fish for Archlinux. This is buiilding 3.1.0 from source, sorry, forgot to say :)

**Comment by krobelus** [comment]
You need to set `CMAKE_INSTALL_SYSCONFDIR`, as in https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=fish-git for example

**Comment by FFY00** [comment]
I can set that, sure, but the behavior is still wrong. The default value is still wrong.

**Comment by zanchey** [comment]
Thanks for asking about this. The behaviour here is right, in the sense it's what all build systems do - the convention to merge `/usr/etc` and `/etc` is not handled by CMake/autoconf but by the various packaging systems. Debian, RHEL and SUSE have macros such as `%cmake` to do this (notably the RPM macros set the wrong path), but it looks like the existing Arch package just sets it directly:

https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/fish
```
build() {
  cd fish-shell-${pkgver}
  ./configure \
    --prefix=/usr \
    --sysconfdir=/etc
  make
}
```

**Comment by FFY00** [comment]
> Thanks for asking about this. The behaviour here is right, in the sense it's what all build systems do

That's not really true. For one, meson does not do this.

From https://mesonbuild.com/Builtin-options.html#universal-options
> Installation options are all relative to the prefix, except:
>    - When the prefix is `/usr`: `sysconfdir` defaults to `/etc`, `localstatedir` defaults to `/var`, and `sharedstatedir` defaults to `/var/lib`
>    - When the prefix is `/usr/local`: `localstatedir` defaults to `/var/local`, and `sharedstatedir` defaults to `/var/local/lib`

> the convention to merge /usr/etc and /etc is not handled by CMake/autoconf but by the various packaging systems.

There's no `/usr/etc` in a unix environment.

From the Filesystem Hierarchy Standard, https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch04s09.html
>  Note that /usr/etc is still not allowed: programs in /usr should place configuration files in /etc. 

> Debian, RHEL and SUSE have macros such as %cmake to do this (notably the RPM macros set the wrong path), but it looks like the existing Arch package just sets it directly:

That doesn't really mater, and is not relevant to the issue. People manually setting the sysconfdir is no excuse for the default value to be wrong.

However I do see your point, you shouldn't need to do this manually in your build system. If this is your final call I will settle but I still think this should not happen.
