### ISSUE TITLE
npm intelligent package completion breaks path completion

### ISSUE THREAD

**Issue by jhermsmeier** [fish-shell/fish-shell#6596]
**Environment:**
- macOS Mojave, Version 10.14.6
- iTerm 2, Build 3.3.9
- fish, version 3.1.0
- node v12.15.0, npm v6.13.4

**Issue:**

npm supports installing local modules (by linking folders) via `npm install ../path/to/module`. With the addition of the "intelligent package completion" in fish 3.1.0 the automatic completion of the local file path does not work anymore, and fish attempts to search for packages with the name of the local path in question;

<img width="100%" alt="Screenshot 2020-02-13 at 19 41 46" src="https://user-images.githubusercontent.com/244907/74467459-61714f00-4e99-11ea-80b5-e7cbdc3e43be.png">

**Comment by faho** [comment]
Yeah, the completions specify "no-files". That's probably overzealous.

**Comment by jhermsmeier** [comment]
Wow, that was quick, many thanks!
