### ISSUE TITLE
Use existing git completions for other aliases 

### ISSUE THREAD

**Issue by kaushikgopal** [fish-shell/fish-shell#6601]
Please let me know if this question has to be redirected elsewhere. 

I have a two fold question, both related to using existing completions:

1. Say I have a command that runs on top of existing commands ([git-number](https://github.com/holygeek/git-number)). 

I essentially want all of the existing git completions to work with another command so `git number checkout myF<tab>` should trigger auto completion as though the number portion of the command didn’t exist in between (`git checkout myF<tab>`). 

For more context I use an abbreviation `g=git number` cause I tend to use the number variant of git more often. Occasionally though, I also want to use the traditional commands. git-number will happily bypass the “number” portion, if it doesn’t receive a number as the first argument, so I could use git normally at that point with my abbreviation, without needing two abbreviations one for g and the other for gn (for e.g.).

I also don’t want to rewrite all of the existing completions on `git` for `git number`. Is there a way to just point to the existing completions for git?

2. If I were to “alias” or use a function for `g` (I know an abbreviation would be better but curious for my own knowledge)

Is it possible again to just point to existing completions ?

**Comment by zanchey** [comment]
`complete --wraps` is probably your friend here - particularly for item 2:

```fish
function g --wraps git
    git number $argv
end
```

**Comment by kaushikgopal** [comment]
Thanks @zanchey : your suggestion worked perfectly for item 2. Might just go with it, cause in my usage, i discovered that certain commands like `rebase` don't actually work too well with git-number (it "works" but throws annoying messages) so i modified the function to ignore it for certain commands  like so:

```
function g --description "abbreviation for git, but supports auto completion this way" --wraps git
    switch $argv[1]
    case "reb*"
        git $argv
    case "*"
        git number $argv
    end
end
```

I'll still leave the question open, to find the answer for item 1, but i'm currently 💯 satisfied with your solution.

**Comment by faho** [comment]
@kaushikgopal Your first question is going to be more complicated. A rough sketch:

```fish
function complete_git_number
    set -l cmd (commandline -po)
    set -l ind (contains -i -- number $cmd)
    set -q ind[1] && set -e cmd[$ind]
    complete -C"$cmd"
end
complete -c git -n '__fish_git_using_command number' -a '(complete_git_number)'
```

The basic idea is to make a commandline to complete and pass it to `complete --do-complete` (or `-C` for short).

You'll want to add this bit to either an eagerly-loaded file like config.fish or your own git completions at ~/.config/fish/completions/git.fish, and either `source` fish's (in a directory in $fish_complete_path) from there or include them wholesale.

**Comment by kaushikgopal** [comment]
apologies for not closing this. I went with zanchey's solution and it works like a charm!
