### ISSUE TITLE
`env`-prepended aliases no longer tab-complete files

### ISSUE THREAD

**Issue by cole-h** [fish-shell/fish-shell#6605]
I have an alias for Emacs set up (`env GDK_BACKEND=x11 emacs`) because I use Emacs on Wayland, and it currently does not support Wayland natively. Ever since 0784b765700da767e755bbbc06cbe4ac3d6d9471, this alias stopped tab-completing files. As expected, 3.0.2 functions fine (because it doesn't have this commit), while 3.1.0 exhibits this behavior. Is there any way to override this inhibition?

**Comment by faho** [comment]
To override it, copy the completion to ~/.config/fish/completions/ and remove the ` complete -c env -f ` line.

However, this works for me? What exactly is your alias?

**Comment by cole-h** [comment]
Instead of using an `alias`, opting for a `function` solves the issue.

```fish
function emacs
    GDK_BACKEND=x11 emacs $argv
end
```
