### ISSUE TITLE
OBS repository for Fedora 31 does not provide any x86_64 packages

### ISSUE THREAD

**Issue by andreipoe** [fish-shell/fish-shell#6607]
Hello,

The [OBS repository for Fedora 31](http://download.opensuse.org/repositories/shells:/fish:/release:/3/Fedora_31/) ([instructions here](https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A3&package=fish)) doesn't seem to provide any packages:

```
$ sudo dnf config-manager --add-repo https://download.opensuse.org/repositories/shells:fish:release:3/Fedora_31/shells:fish:release:3.repo
$ sudo dnf --refresh repoquery -a --repo shells_fish_release_3
```

The `repoquery` command above does not list any packages. The only fish packages that DNF finds are the ones from the system repositories, where 3.1 isn't yet available:

```
$ sudo dnf list --showduplicates fish
Installed Packages
fish.x86_64                                              3.0.2-1.module_f31+3716+57207597                                              @fedora-modular
Available Packages
fish.x86_64                                              3.0.2-1.module_f31+3716+57207597                                              fedora-modular
fish.x86_64                                              3.0.2-1.module_f31+3716+57207597                                              updates-modular
```

Opening [the repository page](http://download.opensuse.org/repositories/shells:/fish:/release:/3/Fedora_31/) in a browser _does_ list [fish 3.1 RPMs for x86_64](http://download.opensuse.org/repositories/shells:/fish:/release:/3/Fedora_31/x86_64/). Is perhaps some of the metadata incorrect?

Thanks.

**Comment by zanchey** [comment]
Yes, I guess it must be. The repository files all look OK to me - they list the packages and so on - but I've no idea how to ask DNF to inspect things further.

```
[root@localhost ~]# dnf repository-packages shells_fish_release_3 info fish
Last metadata expiration check: 0:07:42 ago on Sun 16 Feb 2020 14:28:22 UTC.
Error: No matching Packages to list
[root@localhost ~]# dnf repository-packages shells_fish_release_3 list --all
Last metadata expiration check: 0:08:30 ago on Sun 16 Feb 2020 14:28:22 UTC.
[root@localhost ~]#
```

**Comment by zanchey** [comment]
Oh no:

```
# dnf -v repository-packages shells_fish_release_3 install fish
All matches were filtered out by modular filtering for argument: fish
Error: No packages marked for install.
```

So the problem is that Fedora ships a Modular package of fish, and standalone packages (contained within our OBS repository) [can never have a higher priority than Modular packages](https://docs.fedoraproject.org/en-US/modularity/architecture/consuming/upgrade-paths/).

I don't think OBS can create modular repositories, but I'll email the list tomorrow.

**Comment by zanchey** [comment]
OK, OBS can't create modular repositories. A Fedora developer has added 3.1.0 to the f31-updates-testing repos, so you should be able to pick it up from there. I under there is a plan to demodularise fish (if that's the word), so in future this should work better.

**Comment by andreipoe** [comment]
Excellent, thanks for investigating!

For a temporary workaround, it looks like you can also manually disable the fish module, which will let dnf install the version from the OBS repo:

```
# dnf list --showduplicates fish
Installed Packages
fish.x86_64                                              3.0.2-1.module_f31+3716+57207597                                              @fedora-modular
Available Packages
fish.x86_64                                              3.0.2-2.fc31                                                                  fedora

# dnf config-manager --add-repo https://download.opensuse.org/repositories/shells:fish:release:3/Fedora_31/shells:fish:release:3.repo
# dnf --refresh list --showduplicates fish
Installed Packages
fish.x86_64                                           3.0.2-1.module_f31+3716+57207597                                           @fedora-modular
Available Packages
fish.x86_64                                           3.0.2-2.fc31                                                               fedora
fish.aarch64                                          3.1.0-3.1                                                                  shells_fish_release_3
fish.armv7hl                                          3.1.0-3.1                                                                  shells_fish_release_3
fish.ppc64le                                          3.1.0-3.1                                                                  shells_fish_release_3
fish.src                                              3.1.0-3.1                                                                  shells_fish_release_3
fish.x86_64                                           3.1.0-3.1                                                                  shells_fish_release_3

# dnf upgrade fish
Dependencies resolved.
======================================================================================================================================================
 Package                                      Architecture             Version                          Repository                               Size
======================================================================================================================================================
Upgrading:
 fish                                         x86_64                   3.1.0-3.1                        shells_fish_release_3                   2.7 M
```

**Comment by eclipseo** [comment]
> Oh no:
> 
> ```
> # dnf -v repository-packages shells_fish_release_3 install fish
> All matches were filtered out by modular filtering for argument: fish
> Error: No packages marked for install.
> ```
> 
> So the problem is that Fedora ships a Modular package of fish, and standalone packages (contained within our OBS repository) [can never have a higher priority than Modular packages](https://docs.fedoraproject.org/en-US/modularity/architecture/consuming/upgrade-paths/).
> 
> I don't think OBS can create modular repositories, but I'll email the list tomorrow.

Fedora stopped shipping a Modular package of fish (It's still there bit won't be updated anymore). You can get Fish 3.1.0 on F31 by deactivating the module (`sudo dnf module disable fish`), uninstall and install fish from the standard repo ( `sudo dnf remove fish; and sudo dnf install fish`).

**Comment by zanchey** [comment]
OK, sounds like we've done all we can here.
