### ISSUE TITLE
Completing a command takes several seconds

### ISSUE THREAD

**Issue by Midar** [fish-shell/fish-shell#6611]
Fish 3.0.2.

When I tab-complete any command, it takes several seconds. I have seen this behavior on several different macOS and Linux machines, with the default configuration.

For example, if I type:
fis
It already suggests fish. If I type ^F to take the suggestion, that's instant. If, however, I press tab, fish hangs for several seconds.

This even happens when I complete files in the local directory. For example, if a directory has a configure script, and I type ./conf, it hangs several seconds as soon as I type tab - again despite already having the auto suggestion.

**Comment by faho** [comment]
Please run the following, and then upload the output:

```fish
fish --profile /tmp/fish.prof -c 'complete -C"fis"'
sort -nk2 /tmp/fish.prof | tail -n 20
```

Feel free to censor anything you consider sensitive information.

My theory is on mac this is down to #6270, which is fixed in the just-released fish 3.1.0. On linux it might be a network filesystem or also down to bad apropos performance.

**Comment by Midar** [comment]
```
105	219	-----> while read -l entry
221	221	-> for file in $__fish_config_dir/conf.d/*.fish $__fish_sysconf_dir/conf.d/*.fish $__extra_confdir/*.fish
10	249	----> if test -f $path_file
30	260	-> if test -f $__fish_data_dir/__fish_build_paths.fish
277	283	--> source /opt/pkg/share/fish/functions/__fish_set_locale.fish
67	330	-----> while read -l entry
8	363	----> if test -f $path_file
26	383	---> for x in $fish_user_paths[-1..1]
56	392	---> for entry in $$argv[1]
5	394	--> if set -q fish_user_paths
108	455	----> for path_file in $argv[2] $argv[3]/*
105	484	-> __fish_set_locale
21	499	-> __fish_reconstruct_path
29	627	---> __fish_macos_set_env 'MANPATH' '/etc/manpaths' '/etc/manpaths.d'
3	646	--> if [ -n "$MANPATH" ]
153	914	---> for path_file in $argv[2] $argv[3]/*
27	1376	--> __fish_macos_set_env 'PATH' '/etc/paths' '/etc/paths.d'
10	2125	-> if command -sq /usr/libexec/path_helper
915	4929	> builtin source /opt/pkg/share/fish/config.fish
6877	6877	> complete -C"fis"
```

**Comment by faho** [comment]
That shows it taking about 13ms. Did that take about 13ms, or longer?

Is it possible there's a contributing factor we're missing?

Also did that first command show any output?

**Comment by Midar** [comment]
Yep, there was output, and this one indeed completed pretty much immediately. It seems to be that subsequent commands are much faster.

**Comment by faho** [comment]
>It seems to be that subsequent commands are much faster.

So that's an interesting fact. What do you mean by "subsequent"? Is it only the first completion of a boot that is slow, or is it the first time you're completing a specific command, possibly in a terminal?

E.g. if you try it again, except instead of "fis" it's "git" (assuming you have git installed and haven't completed it this boot) is that any slower?

**Comment by faho** [comment]
Ooooor, since this is on a mac, try using the full string "fish", instead of just "fis". If I recall correctly, you need more than 3 characters to trigger #6270, which is apparently fixed in the next macOS beta, and worked around in fish 3.1.0.

**Comment by Midar** [comment]
I updated to 3.1.0 now and so far have not witnessed it anymore. I'll close for now and reopen should it happen again.

**Comment by Midar** [comment]
Oh, one more thing though: Can the workaround result in sometimes the command not being colored? It seems it's not colored anymore now in exactly the situations where fish would hang before.
