### ISSUE TITLE
. (... | psub) broken since 3.1.0

### ISSUE THREAD

**Issue by fairysword** [fish-shell/fish-shell#6613]
After upgraded to 3.1
```
source: Error encountered while sourcing file '/var/folders/pj/jn249gcn7ddfrjzj2_9mxjhw0000gp/T//.psub.f0iJSWRByB':
source: No such file or directory
```
How to fix the error?

**Comment by faho** [comment]
What's happening here is that psub, to do its work creates a temporary file or directory. And to do that it uses $TMPDIR if it is set or /tmp otherwise.

So it seems that something in your configuration is setting $TMPDIR to a broken value. Find that and fix it.

**Comment by floam** [comment]
It looks like a macOS mktemp/TMPDIR path, it sure would be strange that it would be set by the OS to a directory that does not exist. What is the directory in the output of `mktemp`?

**Comment by floam** [comment]
@faho I kind of doubt this is as simple as a bad configuration. Someone else reported the same thing just two days ago: https://github.com/fish-shell/fish-shell/issues/6594#issuecomment-586300363

**Comment by faho** [comment]
Yeah, they were doing

```fish
 . (rbenv init -|psub)
```

which is about two layers too convoluted - just do `rbenv init - | source`

Now why we're erroring here with `.` I'm not sure. Do we delete the tmpfile before that executes or something?

**Comment by floam** [comment]
Also weird that he was only seeing it with `fish -l` and not `fish`. Can't figure out what's up with that either. I wonder if he rebooted or something in between these reported changes which would recreate the directories.

**Comment by faho** [comment]
A simple test with `. (command echo echo wurst | psub)` works for me.

>Also weird that he was only seeing it with fish -l and not fish

That's simple: Doing rbenv only in login shells.

**Comment by floam** [comment]
> That's simple: Doing rbenv only in login shells.

Oh, right.

**Comment by faho** [comment]
Okay, I can't reproduce this. I literally put

```fish
status --is-interactive; and source (rbenv init - | psub)
```

into my config.fish and it just works?

So it might be mac-specific, and I don't have a mac. So I'm going to need one of our many mac-using users and developers to figure this one out. I'll be happy to answer any questions I can.

**Comment by zanchey** [comment]
`. (command echo echo wurst | psub)` fails on my macOS machine. I'll dig into it.

**Comment by zanchey** [comment]
I think what happens is that the outer job completes, which leads to the cleanup function running and deleting the file before `source` actually has a chance to read it. Might need @ridiculousfish to take a look.

**Comment by faho** [comment]
@zanchey Can you confirm it works with `source` instead of `.`?

**Comment by zanchey** [comment]
Indeed, it does.

**Comment by zanchey** [comment]
It works in master (65883e0e4), but not in 3.1.0. Bisects to 6bf9ae9aeb654985384426872998707bb6851298 as first "fixed" commit, but I'm not sure if that's safe to cherry-pick.

**Comment by faho** [comment]
Doesn't apply cleanly. In particular it pulls in the process_type_t stuff.

Tbh I'd rather just have a simplified version of it.

**Comment by nickolasclarke** [comment]
I am also seeing this `.` vs `source` issue with my `pyenv` configuration. The following breaks:

```
set -x PATH "/home/nclarke/.pyenv/bin" $PATH
status --is-interactive; and . (pyenv init -|psub)
status --is-interactive; and . (pyenv virtualenv-init -|psub)
```
with output: 
```
source: Error encountered while sourcing file “/tmp/.psub.BJGzc7yHU6”:
source: No such file or directory
source: Error encountered while sourcing file “/tmp/.psub.b0QHyQUAZK”:
source: No such file or directory
```
while the following works fine. 
```
set -x PATH "/home/nclarke/.pyenv/bin" $PATH
status --is-interactive; and source (pyenv init -|psub)
status --is-interactive; and source (pyenv virtualenv-init -|psub)
```

**Comment by faho** [comment]
@nickolasclarke You want just:

```fish
set -x PATH "/home/nclarke/.pyenv/bin" $PATH
status --is-interactive; and pyenv init - | source
status --is-interactive; and pyenv virtualenv-init - | source
```

`psub` is entirely useless here.

**Comment by nickolasclarke** [comment]
@faho noted, thanks. I'm tracking down which script automatically added these lines and will open a PR.
