### ISSUE TITLE
regression for io redirection syntax

### ISSUE THREAD

**Issue by u24b6** [fish-shell/fish-shell#6614]
* Version: fish, version 3.1.0 (echo reports the same)
* Terminal: elementary (TERM=xterm-256color)
* uname: Linux luna 5.5.0_1 #1 SMP Mon Feb 3 02:14:31 UTC 2020 aarch64 GNU/Linux
* distro: void

had a snippet which worked well before but no longer works. involves io redirection. snippet/error can be found below:

```
~/.config/fish/config.fish (line 8): Expected a string, but instead found a '&'
	exec startup --user 1>>~/.cache/startup.log 2>>&1
	                                               ^
from sourcing file ~/.config/fish/config.fish
	called during startup
source: Error while reading file '/home/person/.config/fish/config.fish'
```

I am not using any customizations, this is a fresh install and I had the same issue on my old customized installation

**Comment by faho** [comment]
"Append to an fd" doesn't really make any sense. You write to where the fd currently is or you don't, the difference between "append" vs "overwrite" happens earlier, when the initial write position is chosen.

I'd be okay with accepting the second ">" for compatibility, but we'd be doing nothing with it.

**Comment by floam** [comment]
> I'd be okay with accepting the second ">" for compatibility, 

Produces an error in bash and ksh93 FWIW.

**Comment by floam** [comment]
Er, duh, it worked in past fish versions. And I guess zsh.

**Comment by floam** [comment]
With fish 3.1, you can also just do: `exec startup --user &>> ~/.cache/startup.log` to append both stderr and stdout.

**Comment by thesocialdev** [comment]
This is also breaking some plugin installations like [nvm](https://github.com/derekstavis/plugin-nvm).

**Comment by thesocialdev** [comment]
I had to temporarily downgrade fish for Ubuntu bionic 18.04, see:
```
sudo apt install fish=2.7.1-3 fish-common=2.7.1-3
```

**Comment by dkowis** [comment]
This is now the default version of fish shell that ships with ubuntu 20.04 :(

So that means that fish shell is broken out of the box on Ubuntu 20.04. I have filed this: https://bugs.launchpad.net/ubuntu/+source/fish/+bug/1874560 Perhaps the ubuntu community will consider pulling in the single commit to fix their package.

A 3.1.1 from the PPA would be appreciated to help along, as I don't think I have an option to use an older version at this point.
