### ISSUE TITLE
Completing command name takes unreasonably long

### ISSUE THREAD

**Issue by bdcaf** [fish-shell/fish-shell#6615]
I encounter unreasonably slow completion for commands.
With that I mean completing `mkdi` to `mkdir` or `pop` to `popd`. 
These completions take about 10s and more and block the shell.
The examples I am giving are unique on my machine.

I use this commands frequently and also so see valid suggestions for the `Ctrl-L` shortcut.

I am on `fish, version 3.0.2` installed via homebrew on mac.
I did profile with `fish --profile profile.txt  -c 'complete -C"mkdi"'`

[profile.txt](https://github.com/fish-shell/fish-shell/files/4209511/profile.txt)
I think the relevant lines are

```
Time	Sum	Command
1742	10729	> builtin source /usr/local/Cellar/fish/3.0.2/share/fish/config.fish
...
26821	26821	> complete -C"mkdi"
```

**Comment by faho** [comment]
This is a macOS bug that we've worked around in 3.1.0. It should also be fixed in the next macos release.

**Comment by bdcaf** [comment]
good to know. Thanks couldn't  find any mention about it.
