### ISSUE TITLE
unable to change an abbr to an alias

### ISSUE THREAD

**Issue by slmjkdbtl** [fish-shell/fish-shell#6616]
version: `3.1.0` (happens in previous versions too)

if I wrote an abbr like
```
abbr ydl "youtube-dl"
``` 
run fish, it works perfectly, but if I change it to an `alias`
```fish
alias ydl "youtube-dl"
```
run fish again, it won't work as an `alias` and would still be an `abbr`.

**Comment by faho** [comment]
The abbr is still defined. You'll have to erase it with `abbr --erase ydl`

**Comment by slmjkdbtl** [comment]
I see, thanks. Is fish caching these settings anywhere on the system? Sorry for the complaint but personally it seems a little confusing if fish is encouraging command based config or config file based config.

**Comment by faho** [comment]
By default, abbrs are stored in universal variables. These are saved in ~/.config/fish/fish_variables (substitute XDG_CONFIG_HOME as necessary).

**Comment by slmjkdbtl** [comment]
Oh I see, thanks.. I have investigated into that file before but didn't know how I missed it
