### ISSUE TITLE
Abbr expansion with space key not working anymore

### ISSUE THREAD

**Issue by apirrone** [fish-shell/fish-shell#6622]
fish version : 3.1.0
OS : Ubuntu 18.04.1

For example, I have the following abbreviation : 
`abbr -a -g n emacsclient -nw`

Before the last update, when I typed : 

`n <a_file>`

It would expand to :

`emacsclient -nw <a_file>`

But now, the command expands only if I type 'n' then enter.

**Comment by zanchey** [comment]
That should definitely work; what does `bind ' '` show?

**Comment by apirrone** [comment]
bind ' ' (typed in the terminal) shows :

`bind : no link found for sequence ' '` (I translated the message from french, it may be a little different from the real message in english)

**Comment by faho** [comment]
@apirrone Here's what that should be:

```fish
$ bind ' '
bind --preset ' ' self-insert expand-abbr
```

With vi bindings you'd have to check `bind -M insert ' '`, which should print the same except with "-M insert".

If that's not the case, you're either still running an old fish, or you're running an outdated bind function. This would happen if, for instance, you copied `fish_default_key_bindings` (`funcsave` will also do that). Run `functions -D fish_default_key_bindings` (or `fish_vi_key_bindings` if you're using that) to figure out where fish found it.

**Comment by apirrone** [comment]
I typed `bind -M insert ' '` in vi bindings mode and got exactly the same as `bind ' '`

I don't remember ever using `funcsave` or playing with the key bindings ...

Any idea how to fix this ?

Thanks a lot for your help btw !

**Comment by apirrone** [comment]
Ok, I found the issue, I recently installed `ripgrep` and it messed up fish's dependencies 

I had this error when doing an `apt upgrade` : 

```
 fish : Depends on: fish-common (= 3.1.0-1~bionic) but 3.0.2-1~bionic is installed
 fish-common : Depends on: fish (= 3.0.2-1~bionic) but 3.1.0-1~bionic is installed
```
And this one when doing an `apt --fix-broken-install`:

```
dpkg: error with archive /var/cache/apt/archives/fish-common_3.1.0-1~bionic_all.deb (--unpack) :
trying to replace « /usr/share/fish/completions/rg.fish », which also belongs to package ripgrep 11.0.2
```
Uninstalling `ripgrep` with ` dpkg -P ripgrep` then running `apt upgrade` fixed it

Thanks for yout help !

**Comment by ohk2kt3t4** [comment]
@zanchey Is this just a packaging issue on behalf of ripgrep, or is it also because of the changes made in 3.1? Wonder if there are any other ones that will pop up
