### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [fish-shell/fish-shell#663]
I have looked at a few source files for your current software. I have noticed that some checks for return codes are missing.

Would you like to add more error handling for return values from functions like the following?
- [sigaction](http://pubs.opengroup.org/onlinepubs/9699919799/functions/signal.html "change a signal action") ⇒ [signal_set_handlers](https://github.com/fish-shell/fish-shell/blob/19eddddcffe9d49fc33d89b0e624ab9eae4e9ee4/signal.cpp#L504)
- [wcsdup](http://pubs.opengroup.org/onlinepubs/9699919799/functions/wcsdup.html "duplicate a wide-character string") ⇒ [handle_completions](https://github.com/fish-shell/fish-shell/blob/b8f34cdd35cfddb4573e6b1ccc8f063b840b6b54/reader.cpp#L1567)

**Comment by faho** [comment]
There's nothing actionable here. Closing.

**Comment by krader1961** [comment]
FWIW, most of these types of issues will probably get addressed as part of my initiative to make the code lint free. In fact, I think the ROI from making the code free of lint is far greater than spending the time to hunt done individual function or system calls for which we don't check the return value.

**Comment by elfring** [comment]
How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for static code analysis") also for this software?

**Comment by krader1961** [comment]
> How do you think about to improve static source code analysis also for this software?

I implemented that a few days ago. If you pull git head you should be able to `make lint` and `make lint-all` to run the code through cppcheck and oclint. See https://github.com/fish-shell/fish-shell/blob/master/CONTRIBUTING.md.

**Comment by elfring** [comment]
Did you find any more update candidates (with the help of the mentioned analysis tools) for "overlooked" return values?

**Comment by krader1961** [comment]
The lint report is over 4000 lines in length. I haven't looked for that specific type of problem in the report. Feel free to run `make lint-all` and begin fixing whatever problems bug you the most :-) However, I recommend ignoring any style problems (e.g., line too long) because I'm working on a separate initiative to fix the style problems with the code; see https://github.com/fish-shell/fish-shell/pull/2884.

**Comment by elfring** [comment]
I am curious if you would like to extend configuration settings for the check "return value of certain functions not used" by the tool "cppcheck".
How do you think about to group and filter the mentioned lint report?
