### ISSUE TITLE
Fish complains about history and settings saving on read-only file system

### ISSUE THREAD

**Issue by vyachkonovalov** [fish-shell/fish-shell#6630]
My root's HOME (which is /) is on read-only file system.
When I run fish, got errors
```
error: Your history will not be saved.
error: Unable to locate data directory derived from $HOME: '//.local/share/fish'.
error: The error was 'Read-only file system'.
error: Please set $HOME to a directory where you have write access.

error: Your personal settings will not be saved.
error: Unable to locate config directory derived from $HOME: '//.config/fish'.
error: The error was 'Read-only file system'.
error: Please set $HOME to a directory where you have write access.
```
`fish --version`: fish, version 3.1.0
OS: Android (LineageOS 16)
`echo $TERM`: xterm-256color
`uname -a`: Linux localhost 4.9.188-perf+ #1 SMP PREEMPT Mon Feb 17 23:58:32 UTC 2020 aarch64
`su -c 'env HOME=$(mktemp -d) fish'`: good, no errors

How to reproduce the problem:
1. Open Termux
2. Run `su -c fish`

**Comment by zanchey** [comment]
This seems to be working as designed. What would you expect to happen?

**Comment by vyachkonovalov** [comment]
I expected no errors.

> error: Your history will not be saved.

Yeah, I know, I'm on read-only file system.

> error: Your personal settings will not be saved.

This is fine, I have not settings, also I'm on read-only file system as I said.

**Comment by zanchey** [comment]
The most common causes of this message are misconfiguration and filesystem problems, so I don't think we're going to remove the warning, though I'm happy to hear other perspectives. You could ignore it with `fish --debug=-error` if you want.

**Comment by vyachkonovalov** [comment]
`fish --debug=-warning-path` would be great!

**Comment by faho** [comment]
Okay, done.
