### ISSUE TITLE
Adding a time builtin is a breaking change

### ISSUE THREAD

**Issue by nagisa** [fish-shell/fish-shell#6634]
I have the following in my fish configuration:

```fish
function time --description 'generate various statistics of running process'
    /bin/time -f '%P (%e real, %S kernel, %U user); %Mk resident\n%F major/%R minor pfaults; %W swaps; %c invol/%w vol contexts\n%I inputs/%O outputs; %s sck sent/%r sck recv; %k signals recv' $argv
end
```

and upgrading to 

```
$ fish --version
fish, version 3.1.0
```

is now erroring out with

```
/etc/fish/config.fish (line 106): function: The name 'time' is reserved,
and can not be used as a function name
function time --description 'generate various statistics of running process'
^
```

and the `time` alias has changed in behaviour. This should be more prominent in the changelogs. Its now being noted down as just a "new command".

**Comment by mqudsi** [comment]
Not directly a response to your statement, but I'm not sure why we block the use of functions with the same names as builtins instead of requiring them to be prefixed with `function`, except perhaps for limitations of the parser. e.g. in your case it should be possible to define the function exception it would not execute unless run as `function time ...`.

**Comment by ridiculousfish** [comment]
Note functions have the highest priority, so there is no `function` analog to `command` or `builtin`.

The reason that you can't override `time` with a function is that it is not only a builtin, it is a keyword, like `if`. 

I agree with making this more prominent in the changelog, perhaps we can do something for 3.1.1.

**Comment by mqudsi** [comment]
> Note functions have the highest priority, so there is no function analog to command or builtin.

Except for keywords like `and`, `or`, and now, `time` :)

**Comment by zanchey** [comment]
I think we're going to need an "errata for 3.1.0" section in the 3.1.1 notes, so I'll include this. Thanks for the suggestion.
