### ISSUE TITLE
using `commandline` for setting behave weird while completion.

### ISSUE THREAD

**Issue by wodesuck** [fish-shell/fish-shell#6637]
### Conclusion
When using `commandline` for setting during `complete -C STRING`, it will get command line buffer from `STRING`, but set the whole command line buffer instead of the buffer of `STRING`. This might cause weird behavior when a sub-completion such as `sudo something` is called.

--------------- 
### Details

I'm using fish 3.1.0 on macOS 10.15.3.

Recently I write my own custom completion for `kill`, which use `fzf` to select pids.
```fish
function __fzf_complete_pids
    set -l curtok (commandline -t)
    test (string sub -l 1 -- $curtok) != -
    or return

    set -q FZF_TMUX_HEIGHT
    or set -l FZF_TMUX_HEIGHT 50%

    set -lx FZF_DEFAULT_OPTS "--height $FZF_TMUX_HEIGHT --min-height 15 --reverse $FZF_DEFAULT_OPTS --preview 'echo {}' --preview-window down:3:wrap $FZF_COMPLETION_OPTS"

    set -l selected (command ps -ef | sed 1d | fzf -m -q $curtok | awk '{print $2}')
    commandline -f repaint

    if test -n "$selected"
        commandline -t "$selected "
    end
end

__fish_make_completion_signals

for sig in $__kill_signals[-1..1]
    set -l number (string split ' ' $sig)[1]
    set -l name (string split ' ' $sig)[2]
    complete -c kill -o $number -d $name
    complete -c kill -o $name -d $number
    complete -c kill -k -s s -x -a "$name\t$number"
end

complete -c kill -xa '(__fzf_complete_pids)'

if kill -L >/dev/null 2>/dev/null
    complete -c kill -s s -l signal -d "Signal to send"
    complete -c kill -s l -l list -d "List signal names"
    complete -c kill -s L -l table -d "List signal names and their #s"
    complete -c kill -s a -l all -d "Resolve PIDs from other users' too"
    complete -c kill -s p -l pid -d "Show resolved PID, don't send signal"
    complete -c kill -s q -l queue -d "Use sigqueue(2) rather than kill(2)"
    complete -c kill -l verbose -d "Print PIDs and signals sent"
else # non-GNU
    complete -c kill -s s -d "Signal to send"
    complete -c kill -s l -d "List signal names"
end
```

It works as my expectation when I type `kill <tab>`, but it behave weird when using with `sudo`. If I type `sudo kill <tab>`, and then select a pid, the command line will become `kill pid`, `sudo` is disappear.

Noticed that the document of `commandline` says:
> If `commandline` is called during a call to complete a given string using `complete -C STRING`, `commandline` will consider the specified string to be the current contents of the command line.

After reading some related code, I though the problem is, when trigger `sudo`'s completion, it will call `complete -c 'kill '`, and `commandline` will get the subcommand `kill `, but when `commandline` set, it set the whole command line buffer. I hope this could be fixed.

**Comment by krobelus** [comment]
Currently you should not modify the commandline in a completion function, because fish may overwrite it: as you observed in `sudo kill`, fish invokes the completion for `kill` with the modified command line `kill`, and then restores the original commandline. This is so user defined completions don't have to parse `sudo` and other prefixes.

Generally, a completion function (that is used like `complete -c kill -xa '(foo)'`) should not modify the command line but only output completions.I don't know if it is reasonable to support modifications of our transient command lines here, because it is not always obvious how ot apply them to the original command line. Maybe we should print an error here.

Your function already invokes fzf, so you don't need the completion's selection machinery or pager; you could bind it to some other key:
```fish
bind \eg __fzf_complete_pids
```

Or if you want to keep using Tab, then bind a function that selects between your fzf completion and fish's tab completion:

```fish
bind \t fancy-complete-or-complete
function fancy-complete-or-complete
    begin
        contains -- kill (commandline -o)
        and __fzf_complete_pids
    end
    or commandline -f complete
end
```

**Comment by zanchey** [comment]
Yeah, I think being able to modify the commandline from a completion is probably too much to expect.

**Comment by faho** [comment]
Yeah, no, modifying commandlines from the completions won't work. For one it introduces ordering dependencies to completions - do you first change the commandline and then complete that, or first complete and then change? Do you rerun all the completions once the commandline has been changed? Do you rerun them again if it changed again?

Sorry, but this won't work.

**Comment by krobelus** [comment]
> is there any way to prevent this from clashing if multiple commands want to override the `<TAB>` character?
> 
> I also want to do something like this for [zoxide](https://github.com/ajeetdsouza/zoxide)'s Fish plugin, but I don't want to override the previous bound function if possible.

it's probably not a great idea to make a plugin modify such a core binding.
Anyway, to avoid overriding a non-default binding you could override only `if test "$(bind \t)" = 'bind --preset \t complete'`.

**Comment by krobelus** [comment]
If what you want to do is to (conditionally) replace fish's completion pager with fzf, that sounds like a workaround.
The real fix is to improve fish's completion pager.
We can use Shift+Tab or Ctrl+S to activate the search field. Sadly that extra step means I barely ever use it.

One thing that's missing when using the search field is [better completion ranking](https://github.com/jhawthorn/fzy/blob/master/ALGORITHM.md#fzys-scoring), which I can implement soon.

**Comment by ajeetdsouza** [comment]
> Sadly that extra step means I barely ever use it.

True. Is there a way we can make this easier to use?

**Comment by krobelus** [comment]
yeah, I think we can try to show completions like an IDE would. After the initial Tab, if the user keeps typing, the completions should still be displayed (and filtered and ranked). Enter should accept the best completion. To ignore the completions, just keep typing or press Escape.

that will require some careful planning and potentially tricky implementation

**Comment by ajeetdsouza** [comment]
Sounds good, you could perhaps take some inspiration from [Fig](https://fig.io/).

**Comment by faho** [comment]
>One thing that's missing when using the search field is [better completion ranking](https://github.com/jhawthorn/fzy/blob/master/ALGORITHM.md#fzys-scoring), which I can implement soon.

Just so it doesn't come as a surprise later: I hate non-alphabetical ordering and disable it wherever I can. I remain open to be convinced, but I expect to despise it and either reject it or, if overruled, patch or fork it out.
