### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [fish-shell/fish-shell#664]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/fish-shell/fish-shell/blob/73046ec838ca90cbf7e1ea1b1ac89f5c44eec52d/fish.cpp#L416 "main function")" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main "Does it make sense to catch exceptions in the main(…)?") so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706 "Quality Matters #6: Exceptions for Practically-Unrecoverable Conditions")?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108 "stack unwinding") like they are described by Danny Kalev?

**Comment by zanchey** [comment]
I don't think there is going to be any change to the current behaviour here. fish doesn't have any atexit functions, nor does it have streams open that need flushing.
