### ISSUE TITLE
GPG won't work with fish

### ISSUE THREAD

**Issue by Tchekda** [fish-shell/fish-shell#6643]
- Fish version 3.1.0
- Debian 9 WSL Windows 10

When i'm trying to sign a git commit with `git commit -S -m "MESSAGE"` it returns me : 
```
error: gpg failed to sign the data
fatal: failed to write commit object
```
So i searched how to fix it and tried to execute `echo "test" | gpg --clearsign` and it showed me 
```
gpg: signing failed: Inappropriate ioctl for device
gpg: [stdin]: clear-sign failed: Inappropriate ioctl for device
```
The only i made it working is by returning temporary to `bash` to commit my stuff and then come back to fish to continue working....

**Comment by faho** [comment]
I'm assuming your gpg is configured to read the password for unlocking the key from the terminal? Because it works for me, but I use graphical pinentry.

**Comment by faho** [comment]
Also it would be great to know if you have a `gpg` function/alias. The output of `type gpg` would show. (this would make it a duplicate of #6624)

**Comment by Tchekda** [comment]
> I'm assuming your gpg is configured to read the password for unlocking the key from the terminal? Because it works for me, but I use graphical pinentry.

I'm using WSL so I can't start a graphical interface, even if I'm using Kleopatra



> Also it would be great to know if you have a `gpg` function/alias. The output of `type gpg` would show. (this would make it a duplicate of #6624)

It's at `/usr/bin/gpg`

**Comment by faho** [comment]
>I'm using WSL so I can't start a graphical interface, even if I'm using Kleopatra

Oh, yes, sure. It's just that I want to make it clear there's an important difference when reproducing. If you are using graphical pinentry, there's no reason for gpg to read from the terminal.

Tho now that I try it, using `pinentry-curses` doesn't trigger the issue for me either (with 3.1.0 or master).

Duckduckgo leads me to https://github.com/microsoft/WSL/issues/4029, which suggests you might want to try:

```fish
set -gx GPG_TTY (tty)
```

which I already have in my config.fish and also had in my bashrc from ages ago. Removing it makes gpg fail, so... try that?

**Comment by zanchey** [comment]
I've been having this problem for years and I didn't even think that fish might be part of the problem!

**Comment by zanchey** [comment]
Putting `set -gx GPG_TTY (tty)` in my config fixes it for me! Hooray! You're my hero!

**Comment by faho** [comment]
>I've been having this problem for years and I didn't even think that fish might be part of the problem!

Just to be clear: Those links? They're not using fish. It's a general problem with gpg not being able to figure out the terminal. I'm not entirely sure how or why it's failing to, but setting that variable tells it explicitly which terminal it should use.

**Comment by zanchey** [comment]
Sorry, I should have written "my fish config".

**Comment by faho** [comment]
Aaaand it's actually recommended by gpg in [its documentation](https://www.gnupg.org/documentation/manuals/gnupg/Invoking-GPG_002dAGENT.html#Invoking-GPG_002dAGENT):

>You should always add the following lines to your .bashrc or whatever initialization file is used for all shell invocations:
>
>GPG_TTY=$(tty)
export GPG_TTY
>
>It is important that this environment variable always reflects the output of the tty command. For W32 systems this option is not required.

**Comment by Tchekda** [comment]
> Putting `set -gx GPG_TTY (tty)` in my config fixes it for me! Hooray! You're my hero!

Thank you so much, seems to work for now. If it occurs again, will reopen the isssue. But for now, it's working. 
Thank you so much !!

**Comment by dakyskye** [comment]
Does not work for me.

**Comment by dakyskye** [comment]
However, it works for `echo "test" | gpg --clearsign` 
![image](https://user-images.githubusercontent.com/32128756/101011714-1c2f2280-357c-11eb-8e5b-2971fc0f7baa.png)

**Comment by Tchekda** [comment]
> Does not work for me.
> ![image](https://user-images.githubusercontent.com/32128756/101009253-649a1080-357b-11eb-834e-3b3a02093699.png)
> 

Did you correctly configured you git to use the right gpg binary ?

**Comment by dakyskye** [comment]
I just set `GIT_TRACE` variable and running the command it says:
```
❯ /usr/bin/gpg --status-fd=2 -bsau 'dakyskye <kanteladzelasha339@gmail.com>'
gpg: skipped "dakyskye <kanteladzelasha339@gmail.com>": No secret key
```

**Comment by dakyskye** [comment]
Oh maybe it's because my  `git user.name` is `dakyskye`

**Comment by dakyskye** [comment]
Yeah. Fixed.
