### ISSUE TITLE
ros command-line tools autocomplete fail

### ISSUE THREAD

**Issue by YashaAkimov** [fish-shell/fish-shell#6652]
Please tell us which fish version you are using:

`fish --version # fish version 3.1.0`

Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

`uname -a # Linux yasha-laptop 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
`echo $TERM # xterm-256color`

Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:
not affected

i try to autocomplete ros command-line tools. In bash i hit tab button twice and it show list of commands. for example:
`yasha@yasha-laptop:~$ rostopic #tab #tab`
`bw    echo  find  hz    info  list  pub   type `
But in fist i just got  list of directories
`yasha@yasha-laptop ~> rostopic #tab #tab`
`Arduino/    Desktop/    Downloads/  Pictures/  sketchbook/  Videos/ ...`

**Comment by ridiculousfish** [comment]
Thanks for filing. Are you using [http://wiki.ros.org/rosbash](rosbash)? Have you tried their [fish completions](http://wiki.ros.org/rosbash#fish)?

**Comment by YashaAkimov** [comment]
No, i didn't try it before. But now i try and it works as expected. Many thanks.
