### ISSUE TITLE
Cursor shape does not update correctly in vi mode

### ISSUE THREAD

**Issue by wylfen** [fish-shell/fish-shell#6653]
I recently updated to the most current release of fish, version 3.1.0. I found that in the new version, the cursor shape is not updated correctly anymore when using vi mode. I confirmed this for current master as well.

```sh
$ rg cursor ~/.config/fish/fish_variables
30:SETUVAR fish_cursor_default:block\x1eblink
31:SETUVAR fish_cursor_insert:line\x1eblink
32:SETUVAR fish_cursor_replace_one:underscore\x1eblink
33:SETUVAR fish_cursor_visual:block
```
With the above settings, in a new session, fish shows the correct _line_ shape. It switches to _block_ shape when I press **ESC**. However, it does not switch back to _line_ if I then enter insert mode with **a** or **i**. It also does not switch to _underscore_ if I press **r**.

I bisected this issue and traced it back to https://github.com/fish-shell/fish-shell/commit/ff5524944, which removed event handler support for implicit sets. Such a set is present in input.cpp: https://github.com/fish-shell/fish-shell/blob/e1a08e3f585a0b3a949f2980579b70b7d9ed7662/src/input.cpp#L192

To confirm this, I added code to input.cpp that would collect fired events in an `event_t` vector, and passed it to `event_fire`. With that change, the cursor updated correctly again.

I planned to send a pull request along with this report, but for this I am not familiar enough with the codebase (this is my first glance at it).

**Comment by ridiculousfish** [comment]
Wow, amazing digging. Thank you! I'll take a look.

**Comment by ridiculousfish** [comment]
Should be fixed in master as 5886b961d8ad1d54bc1eaa28930c92c5763307cf and 3.1.1 as acad9b05e2ee2066173e101e84e1c04ae6d61343. Thank you for filing, this was awesome.

**Comment by niilz** [comment]
It sounds like this got fixed in 3.1.1. But I have just updated to 3.1.2 (via installer on MacOS Catalina 10.15). And when I try ```set -g fish_cursor_insert line```, either from command-line or in ```config.fish```, the cursor is still displayed as block when in insert mode.
I use fish within alacritty

**Comment by faho** [comment]
@niilz That's https://github.com/fish-shell/fish-shell/commit/3c6c8d542410cd84b8249c84a58ec28db71fba06. Fish doesn't have alacritty in its whitelist.

That change happened after 3.1.2, so it's going to be in the next release. If you want you can download that file yourself and put it in ~/.config/fish/functions.

**Comment by niilz** [comment]
Thanks for the immediate response. I will do that.
