### ISSUE TITLE
nan crashes test

### ISSUE THREAD

**Issue by anordal** [fish-shell/fish-shell#6655]
Latest git:

```
env HOME=(mktemp -d) ./fish

echo $FISH_VERSION
3.1.0-242-gcebfaa778

test nan -gt 0
fish: ../src/builtin_test.cpp:93: {anonymous}::test_expressions::number_t::number_t(long long int, double): Assertion `0.0 <= delta && delta < 1.0 && "Invalid delta"' failed.
fish: 'env HOME=(mktemp -d) ./fish' terminated by signal SIGABRT (Abort)
```

I also see this in version 3.0.2 (OpenSuse package).

**Comment by faho** [comment]
Yup. Fixed by erroring out.

I don't think we need to support nan/inf here as they have some weird properties that serve more to confuse people than they'd have a use in a shell. `math` also won't handle or output nan/inf, so that's fine.

Cherry-picked to 3.1.1 as 3e689f1.
