### ISSUE TITLE
feature request: Expand abbreviation when entering a closing parenthesis

### ISSUE THREAD

**Issue by scooter-dangle** [fish-shell/fish-shell#6658]
I didn't find this mentioned in any of the issue titles, but it's possible it was brought up tangentially in an issue around `abbr`.

Generally when I use an abbreviation in a command substitution, the closing `)` unambiguously indicates that the token is complete, at which point it would be convenient if the abbreviation were expanded.

For example, I have the follow abbreviation defined for listing modified files:

```fish
abbr --add gsmod 'git ls-files --modified'
```

If I wanted to open all the modified files, I would run

```fish
vim (gsmod)
```

which works as intended, since the `)<CR>` combination triggers the expansion to

```fish
vim (git ls-files --modified)
```

However, if I wanted to pass any options to vim after the substitution, the following would _not_ expand and would cause an error when entered

```fish
vim (gsmod) -O
```

since I have no function or commands named `gsmod`.

The workaround I use is to remember to add an extra space prior to the `)` in cases where I know I'll be adding more to the command, which results in

```fish
vim (git ls-files --modified ) -O
```

Granted, there could be consequences of supporting additional expansion triggers that I haven't thought of.

**Comment by faho** [comment]
This is easy:

```fish
bind ')' self-insert expand-abbr
```

I'm gonna have to think some about whether it makes sense as a default.

**Comment by krobelus** [comment]
A similar issue applies to the other statement terminators  `|`, `&`, `;` and `\e\r` as well as perhaps even `<` and  `>`, let's see.

**Comment by faho** [comment]
So good news is we only expand the abbreviation if the cursor is *at the end of it*.

That means if we bind ')' et al to expand them, this only applies if you type e.g.

```fish
something (smth)
```

and not

```fish
something (smth )
```

>and \e\r as well as perhaps even < and >, let's see.

Tbh I always hated how execute expands abbrs, because that makes using abbrs with the same name as commands (like `rm` for `rm -I`) worse.

Tho now that we can bind ctrl-space it's possible to bind that to inserting space *without expanding*, so it's possibly not as bad.

**Comment by krobelus** [comment]
I didn't mean `\r` / `execute` but the actual `\e\r` which is `commandline -i \n`.
I find the abbreviation logic a bit confusing, though it works really well in most cases.

Good point, I think `execute` should not always expand abbreviations, but only if the cursor is at the command token. I don't think that behavior would surprise anyone (if you have more tokens you likely already expanded the abbreviation with a space). This should be more discoverable thatn ctrl-space.

**Comment by faho** [comment]
>I didn't mean \r / execute but the actual \e\r which is commandline -i \n.

Oh, sorry, missed that!

> Also if a command is valid, like rm, it is not expanded by execute.

It is expanded? Unless there's been a super recent change, I've been running 3.1 for a bit now.

**Comment by krobelus** [comment]
No, it will only be expanded in execute if the token left of the cursor is in command position.
Here it's a bit but the example is contrived:
```fish
$ abbr -g echo echo 123
$ echo $version
       ^
123 3.1.0
$ echo $version
        ^
3.1.0
```

**Comment by faho** [comment]
Okay, so I made it so that ctrl-space enters a space without expanding abbreviations, and made ")" and alt-enter expand abbreviations.
