### ISSUE TITLE
Fish command substitution doesn't strip trailing spaces

### ISSUE THREAD

**Issue by david-mcgillicuddy-moixa** [fish-shell/fish-shell#6663]
I'm on OSX, fish version 3.0.2. I installed the tool `pidof` from homebrew, and for whatever reason (possibly laziness around interpolation, or input sanitisation) it outputs a space at the end of its output.
```
❯ pidof foo | hexdump
0000000 39 35 38 36 35 20 0a
0000007
```
When you use command substitution to give this to kill, the space causes kill to error:
```
❯ kill (pidof foo)
kill: ‘95865 ’: invalid process id
```
and you can see the same behaviour directly:
```
❯ kill (echo "1893 ")
kill: ‘1893 ’: invalid process id
```
HOWEVER in bash this works
```
bash-5.0$ pidof foo | hexdump
0000000 39 35 38 36 35 20 0a
0000007
bash-5.0$ kill $(pidof foo)   # success
bash-5.0$
bash-5.0$ kill $(echo "1893 ") # also success
bash-5.0$
```
So in conclusion, bash command substitution strips spaces, and fish's doesn't. The same behaviour happens under `sh -c 'env HOME=$(mktemp -d) fish'`. 

Is this intended? Just from a user perspective it's pretty annoying to need to do e.g. 
```
 kill (pidof foo | xargs)
```
to strip the spaces. Of course `pidof` should not really output spaces too.

**Comment by faho** [comment]
Yes, this is intended. Fish's command substitution does not care about spaces one bit, it only splits on newlines.

To strip whitespace you can also use `string trim`.

**Comment by david-mcgillicuddy-moixa** [comment]
Okay, thanks for the quick response.
