### ISSUE TITLE
<esc>+p results in previous command with `2>&1 | less;` appended

### ISSUE THREAD

**Issue by enricozb** [fish-shell/fish-shell#6665]
## My System
    fish --version -> 3.0.2
    echo $TERM     -> xterm-256color
    terminal       -> gnome-terminal

## Behavior
The easiest way to reproduce this is just to press `<esc-p>` as if it were a keybinding. On my system it has the same behavior as `<up arrow>` followed by typing in ` 2>&1 | less;` (with a space at the beginning).

This behavior still occurs when running within `sh -c 'env HOME=$(mktemp -d) fish'`.

How do I prevent this behavior?

**Comment by faho** [comment]
Yes, escape-p is the same thing as alt-p, and it is bound to `__fish_paginate`, which adds just that.

To prevent it rebind \ep

**Comment by enricozb** [comment]
Thank you!
