### ISSUE TITLE
Grouping history

### ISSUE THREAD

**Issue by peoro** [fish-shell/fish-shell#6666]
Sometimes I'm working on something specific that takes quite a bit of shellwork. I'd like to "isolate" the history of that whole task so that the commands I run for that task and the commands I type for different tasks don't clutter each other.

Wish bash it's possible to achieve what I want using the `HISTFILE` env var: a `task $NEW_TASK` command could do something like:

```
env HISTFILE="$HISTFILE.$TASK.$NEW_TASK" TASK="$TASK.$NEW_TASK" bash
```

This starts a new bash using a history file specific for the new task and with a special prompt reminding what that shell is for. It even works recursively.

Is it possible to achieve something similar with fish?

**Comment by faho** [comment]
Set $fish_history to the task name.

**Comment by peoro** [comment]
Oh, nice! Couldn't find that variable, sorry about that.

Something like

```
set -g fish_history $TASK
```

indeed offers what I wanted, thanks!
