### ISSUE TITLE
function --on-job-exit not triggered when busy

### ISSUE THREAD

**Issue by Korkman** [fish-shell/fish-shell#6679]
Fish 3.1.0 on Debian Buster via SSH (Terminator)

It seems signals are not properly queued. When child exits at a time when fish is busy, the event is not triggered.

Reproduce:
```fish
sleep 3 &
function alarm --on-job-exit (jobs -p)
	echo alarm
end
sleep 5
```

No "alarm" output. Same goes for --on-process-exit.

**Comment by Korkman** [comment]
Does not happen with the Debian packages Fish 3.0.2

**Comment by ridiculousfish** [comment]
Bisects to f8b2e818ed6606e4fd10bc416f2f6c9ad8b49f86

**Comment by ridiculousfish** [comment]
This should also go into 3.1.1, I should have a fix in next ~16 hours.

**Comment by ridiculousfish** [comment]
Unfortunately it's annoying to write a test for this; I will do so after further improving job control in non-interactive shells.

**Comment by ridiculousfish** [comment]
cherry-pick to 3.1.1 as eec90e379eb33293eb670f70a6457dfeed885f9d
