### ISSUE TITLE
Copying from end of buffer crashes on Fish 3.1.0

### ISSUE THREAD

**Issue by okamsn** [fish-shell/fish-shell#6680]
Hello,

Copying from the end of the buffer (after the last inserted character, the position reached by `M->`) causes Fish 3.1.0 to crash.

This is on Xubuntu 20.04.

- Output of `uname -a`:

    Linux lptp2 5.3.0-40-generic #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Output of `echo $TERM`:

    xterm-256color

There are no third party customizations. That command did not affect the crash.

The crash:
    fish: /build/fish-Wz1fgo/fish-3.1.0/src/parse_util.cpp:246: void parse_util_cmdsubst_extent(const wchar_t*, size_t, const wchar_t**, const wchar_t**): Assertion `cursor_pos <= bufflen' failed.

The bindings I am trying:

    bind -k nul begin-selection
    bind \ew kill-selection end-selection yank

After using this command by selecting from the end of the buffer, immediately pressing a letter will insert the letter on the screen and print the crash message right after the letter.
- The cursor jumps back to the end of the buffer.
- I can't move the cursor with the arrow keys or `C-f` and `C-b`, but `M-<` and `M->` work. `C-p` and `C-n` don't work either.
- The copying will work. Pasting will insert the text, but it will not get syntax highlighting.
- Pressing backspace will move the cursor back through the pasted text without removing from the screen.
  - Once I "backspace" all the way though the pasted text back into the pre-paste text, there are no more errors, and it won't crash.

Shortest steps to reproduce:
1. Bind the keys.
2. Press `C-p` to go back to previous command. Now at end of buffer.
3. Press `C-SPC` to being selection. Move cursor towards beginning of line.
4. Press `M-w` to copy. Cursor jumps back to end of buffer.
5. Press `C-y` to insert the copied text. Pasted text is shown on screen without syntax coloring. Cursor is still at end of buffer.
6. Press `a` to insert `a` at end of line. "a" inserted without color. Fish crashes with above message.
   - If instead jump to beginning of line with `M-<` and then press `a`, "a" is inserted with the correct error color, and then Fish crashes.

**Comment by okamsn** [comment]
I have created this Asciinema recording showing the above steps.

https://asciinema.org/a/q7UzVZYk43cUca3aShvnS24GM

**Comment by krobelus** [comment]
Thanks for the report, fixed and cherry picked to 3.1.1.
I wonder if those keybindings should be the default, but `M-w` is taken.
