### ISSUE TITLE
`svnversion` should not be executed by default

### ISSUE THREAD

**Issue by asomers** [fish-shell/fish-shell#6681]
```
> fish --version
fish, version 3.1.0
> uname -a
FreeBSD fbsd-head.lauralan.noip.me 13.0-CURRENT FreeBSD 13.0-CURRENT #58 r358258M: Sun Feb 23 14:50:10 MST 2020     somers@fbsd-head.lauralan.noip.me:/usr/obj/usr/home/somers/freebsd/base/head/amd64.amd64/sys/GENERIC  amd64
> echo $TERM
xterm-256color
```

Fish 3.1.0 "helpfully" runs `svnversion` and `svn status` in order to change the prompt, whenever it detects that the pwd is part of a subversion working copy.  That feature is probably handy when working in small repositories.  But in a large repository, those commands take *far* too much time, especially so if the pwd lies on a remote file system.  For example, on my system I have /usr/home mounted over NFS.  In my FreeBSD source tree, `svnversion` and `svn status` take a combined 42 seconds to run.  And fish runs them after _every single command_.  That makes the shell entirely unusable.

I notice that fish runs `git branch` in git repositories.  That's fine; `git branch` is fast.  But I believe that no command that traverses the entire tree should be run by default, just to change the prompt.

**Comment by faho** [comment]
Blergh.

Yeah, it would be lovely if svn had a thing that can just display the branch, which is why the git prompt is so much faster (well, that and git just being faster than svn and hg in general).

I see we do `command svn info` in fish_svn_prompt. What does that print and is it acceptably fast?

**Comment by asomers** [comment]
`svn info` prints something like the following, and it is fast since it doesn't have to examine the entire WC:
```
> svn info
Path: .
Working Copy Root Path: /usr/home/somers/freebsd/base
URL: svn+ssh://asomers@repo.freebsd.org/base/head/sys
Relative URL: ^/head/sys
Repository Root: svn+ssh://asomers@repo.freebsd.org/base
Repository UUID: ccf9f872-aa2e-dd11-9fc8-001c23d0bc1f
Revision: 358258
Node Kind: directory
Schedule: normal
Last Changed Author: rlibby
Last Changed Rev: 358258
Last Changed Date: 2020-02-22 20:32:16 -0700 (Sat, 22 Feb 2020)
```

**Comment by faho** [comment]
Hummm... so what part of that output would be of interest in a prompt?

I'm probably too used to git et al, so I'd be expecting a branch. Is that useful for svn? Or would we use the revision? Or just an indication that you *are* in an svn repo?

**Comment by asomers** [comment]
svn doesn't have a concept of "branch".  You're branch is just part of the URL, and that's too long for the prompt.  I don't think the revision would be useful, either.

**Comment by faho** [comment]
So what should this show? Is there a useful thing to show other than the full file information (which we've ascertained is too slow)?

**Comment by asomers** [comment]
Probably not.  In this case I don't think there's anything that's really better than nothing.  (For git directories, though, I am liking the branch name).

**Comment by faho** [comment]
It's a shame, but I just commented it in fish_vcs_prompt now. That gives it a fighting chance to be discovered.

**Comment by asomers** [comment]
Thanks for the quick fix!

**Comment by faho** [comment]
Cherry-picked to 3.1.1 as c37a4258872ea.
