### ISSUE TITLE
Remove exercism completions

### ISSUE THREAD

**Issue by ignatenkobrain** [fish-shell/fish-shell#6682]
Nowadays it seems that upstream ships completions for fish, so I think it needs to be removed from fish repo.

https://bugzilla.redhat.com/show_bug.cgi?id=1733321

**Comment by ignatenkobrain** [comment]
I am not sure what policy here is, so I decided to open this as an issue before actually sending PR.

**Comment by faho** [comment]
>I am not sure what policy here is, so I decided to open this as an issue before actually sending PR.

The policy actually would be for the package to include the upstream completions in vendor_completions.d, so there is no file conflict.

**Comment by ignatenkobrain** [comment]
Fair enough.
