### ISSUE TITLE
chsh does not recognize fish as a shell

### ISSUE THREAD

**Issue by ryanthejuggler** [fish-shell/fish-shell#669]
According to [this page](http://www.debian-administration.org/article/231/Changing_your_login_shell):

> All Debian shell packages should insert the name of their binary into the shells file; if they do not this is a bug.

The `make install` command ought to do this automatically. As it is, `chsh` throws the error:

    chsh: /usr/local/bin/fish is an invalid shell

**Comment by CoolOppo** [comment]
This is still an issue to this day. I just had this problem, which led me back to this very old thread.

**Comment by faho** [comment]
The README has been updated with a command to update /etc/shells.

`make install` should _not_ do this, as it is also executed as part of packaging fish - it should not touch the system beyond $DESTDIR.

There is nothing more to do here for us. If you are a user, consider installing fish via packages or just add it to your shells file.

**Comment by Trigun27** [comment]
for me work this command usermod -s /usr/bin/fish username

**Comment by lackovic** [comment]
I installed today with:

```bash
$ sudo apt-add-repository ppa:fish-shell/release-2
$ sudo apt-get install fish
$ cat /etc/shells
# /etc/shells: valid login shells
/bin/sh
/bin/bash
/usr/bin/bash
/bin/rbash
/usr/bin/rbash
/bin/dash
/usr/bin/dash
/usr/bin/fish
/usr/local/bin/fish
```

To make `fish` my default shell - [like the README says](https://github.com/fish-shell/fish-shell/blame/master/README.md#L84-L86) - I run:

```bash
$ chsh -s /usr/local/bin/fish
```

from which I get back the following error:

```bash
chsh: /usr/local/bin/fish is an invalid shell
```

**Comment by faho** [comment]
@lackovic Use whatever path to fish your /etc/shells says. Like the README says:

> Substitute `/usr/local/bin/fish` with whatever path fish was installed to, if it differs.
