### ISSUE TITLE
Can Fish shell start without loading Config?

### ISSUE THREAD

**Issue by koumaza** [fish-shell/fish-shell#6691]
fish, version 3.1.0-276-gf89794844
3.1.0

Linux REQU-wsl 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 GNU/Linux
screen-256color

Fish uses /tmp as the Temporary Directory, which prevents access to anything running in /tmp from outside the container.
Eg fish_config
I have set config.fish to start genie on Archlinux in WSL2 environment, but this will prevent parent (Windows side) from accessing /tmp in the container.
Genie builds containers for systemd to work.
It may be bad to write in config.fish
I do not fully understand Fish, but I think it is necessary if there is no flag to specify Temporary and there is no way to start Fish without loading Config.
like bash --noprofile --norc

**Comment by faho** [comment]
>Fish uses /tmp as the Temporary Directory

Not quite - it uses $TMPDIR as the temporary directory, falling back to /tmp if that isn't set.

So just set it before starting fish, like e.g. `TMPDIR=(mktemp -d) fish`.

**Comment by koumaza** [comment]
Thanks.
TMPDIR worked fine. 😁
But fish_config uses Py Script, so it may not be relevant. sorry.

Is there currently no way to start fish without loading Config other than `env HOME=/tmp fish` ? 🤔
In WSL: `wsl -e env HOME=/tmp fish -c 'foo'`

**Comment by zanchey** [comment]
See #1256; at present, no.

**Comment by faho** [comment]
> But fish_config uses Py Script, so it may not be relevant. sorry.

Considering that it uses python's tempfile and I'm pretty sure that also obeys $TMPDIR, it should be.

**Comment by koumaza** [comment]
That's right. I didn't set TMPDIR before launching fish.
❌`set -gx TMPDIR a;fish_config`
✅`env TMPDIR=~/a fish -c 'fish_config'`
