### ISSUE TITLE
ssh autocompletion: hosts with more than one aliases

### ISSUE THREAD

**Issue by tohn** [fish-shell/fish-shell#6698]
I think I'm experiencing [this bug](https://github.com/fish-shell/fish-shell/issues/4290) again:
I have the following lines in my `.ssh/config`:

```
Include ~/.ssh/config.d/*

Host foo bar
  Hostname 127.0.0.1
```

And a lot more in the included folder. Some hosts have one name (`Host one`), some have two or more. Whenever there are more names than one, fish completes (if I use Tab) to `ssh foo\ bar`.

I'm using fish version 3.1.0 in iTerm2 3.3.9 on macOS 10.15.3.
My `$TERM`: xterm-256color

If I use fish without third-party stuff (`sh -c 'env HOME=$(mktemp -d) fish'`), there is no ssh completion using anything from `.ssh/config` or the included ones. Apparently this will only use the hosts in `/etc/hosts`.

**Comment by faho** [comment]
Yeah, regressed in b89a6451a3f18589750864e3709d24bb307b484a.

**Comment by faho** [comment]
Turns out just adding an explicit split step should work.

Added to 3.1.1.
