### ISSUE TITLE
Recursion depth reached on scp completion

### ISSUE THREAD

**Issue by debugloop** [fish-shell/fish-shell#6707]
I am having a problem when using completion on `scp`. See the following transcript.

```
me@host ~> fish --version
fish, version 3.1.0
me@host ~> uname -a
Linux waystone 5.5.7-arch1-1 #1 SMP PREEMPT Sat, 29 Feb 2020 19:06:02 +0000 x86_64 GNU/Linux

# actual test here
me@host ~> mkdir test
me@host ~> cd test
me@host ~/test> touch bla
me@host ~/test> scp blcomplete: maximum recursion depth reached
complete: maximum recursion depth reached
complete: maximum recursion depth reached
complete: maximum recursion depth reached
complete: maximum recursion depth reached
me@host ~/test> cat ~/.ssh/known_hosts | grep -E "^bl"
1 me@host ~/test>
```

This does not happen when starting fish without my configuration, but I don't see any changes that could relate to this. Any hints on debugging this would be appreciated.

**Comment by faho** [comment]
The "recursion" happening here is that fish's completion system goes through the wrap chain.

The major thing that sets up  wrapping are aliases. Do you have any aliases, particularly related to `scp` or `ssh`?

**Comment by debugloop** [comment]
I've had one related to `ssh`, but was not using it and deleted it now, but the issue persists. My whole config is kind of simple, 131 lines, nothing related to this afaict...

https://github.com/debugloop/dotfiles/blob/work/fish/.config/fish/config.fish

**Comment by faho** [comment]
Hmmm... perhaps this is related to your ssh config? Can you try moving ~/.ssh out of the way?

**Comment by debugloop** [comment]
As starting with a blank fish does not have the issue, this should not make a difference, but it somehow does. Moving my `.ssh` away gives me an autocompletion of the file, _but_ it also still completes hostnames if I type a matching one... I also don't actually have a host starting with my test string (`bl`)... 

Is scp/ssh autocompletion based on SSH config or known_hosts? I have wildcards in my config, so that might be a thing.

I'll test this more methodically tomorrow.

**Comment by faho** [comment]
>Is scp/ssh autocompletion based on SSH config or known_hosts? I have wildcards in my config, so that might be a thing.

It is.  We'd love to have a way to just ask ssh to give us hosts, but unfortunately it's entirely uncooperative in this regard, so we're forced to parse the file.

My guess is you have an include-loop or something?

**Comment by debugloop** [comment]
For some reason, I cannot reproduce this anymore, without having made any changes that I am aware of, not even a reboot. I'll debug this immediately next time this occurs... Sorry to bother you here!
