### ISSUE TITLE
Tutorial on fishshell.com has artifacts in syntax highlighting section

### ISSUE THREAD

**Issue by dmitry-voronkevich** [fish-shell/fish-shell#6710]
Example for syntax highlighting in https://fishshell.com/docs/current/tutorial.html#syntax-highlighting should demonstrate invalid command highlighted in red. Instead, it is printed as `<red>/bin/mkd</red>`.
![Screen Shot 2020-03-04 at 1 38 05 PM](https://user-images.githubusercontent.com/5955296/75885549-9f212200-5e1e-11ea-8954-01c1b2fd83ec.png)

**Comment by faho** [comment]
Duplicate of #6640
