### ISSUE TITLE
Fish SVN prompt regression in 3.1

### ISSUE THREAD

**Issue by ypnos** [fish-shell/fish-shell#6715]
In version 3.1, fish_svn_prompt does not work.

Expected:
```
⮞ fish -v
fish, version 3.0.2
⮞ __fish_svn_prompt
(26786|MX?||||X||)⏎
```

Observed:
```
⮞ fish -v
fish, version 3.1.0
⮞ fish_svn_prompt
(26786|||||||)⏎
```

I tried with different locations/repos and the result is always the same after the revision number.
It is also very slow for large subversion repositories (not the svn status retrieval but the processing in the loop for each column). I know you wouldn't expect large svn repositories in the wild in 2020, but boy do they exist.

**Comment by faho** [comment]
>It is also very slow for large subversion repositories

Unfortunately that can't really be helped - svn is just that slow, and displaying simpler information (the svn prompt is the equivalent of the "informative" git prompt, it scans all files in the entire repo) doesn't make sense.

So we're disabling it by default in 3.1.1 - #6681 

-----

Unfortunately I don't have an svn repo to test, so I'd need some of your help.

For one, what does `set | grep __fish_svn_prompt_char` print?

What is the output of

```fish
command svn status | sed -e 's=^Summary of conflicts.*==' -e 's=^  Text conflicts.*==' -e 's=^  Property conflicts.*==' -e 's=^  Tree conflicts.*==' -e 's=.*incoming .* upon update.*==' | cut -c 1-7
```

and

```fish
functions -D fish_svn_prompt
```

?

**Comment by faho** [comment]
Sorry, without more information there's nothing I can do. Closing.
