### ISSUE TITLE
How do I install fish 3.0.2 (or an older version of fish) on Ubuntu 18.04.1 LTS of Docker container?

### ISSUE THREAD

**Issue by Keiku** [fish-shell/fish-shell#6718]
If I install fish as usual, fish 3.1.0 will be installed. In the case of fish 3.1.0, oh-my-fish cannot be used due to the problem of the link below.

https://github.com/oh-my-fish/oh-my-fish/issues/736

The solution is described in the link below, but it cannot be solved in the Docker container. The easiest way is to install fish 3.0.2 (or an older version of fish) to use fish and oh-my-fish. So I want to know how to install fish 3.0.2. The environment uses Ubuntu 18.04.1 LTS of Docker container.

**Comment by faho** [comment]
Build it yourself - https://github.com/fish-shell/fish-shell#building

Alternatively, wait for the upcoming 3.1.1 which will fix that particular issue.

**Comment by Keiku** [comment]
In Docker, I was able to build fish with version specified as follows:

```
RUN wget https://github.com/fish-shell/fish-shell/releases/download/3.0.2/fish-3.0.2.tar.gz
RUN tar xvf fish-3.0.2.tar.gz
RUN cd fish-3.0.2 && ./configure && make && sudo make install
```
