### ISSUE TITLE
Hook for "before execution"

### ISSUE THREAD

**Issue by qznc** [fish-shell/fish-shell#672]
I would like to port [UndistractMe](http://mumak.net/undistract-me/) for fish. At the core it requires to measure the (real time) run time of command execution.

The "stop the clock" event could be the prompt display, although that is not accurate in combination with background execution. Enough for a workaround, though.

However, I cannot "start the clock". It requires a hook or wrapper for command execution.

Fish could provide two hooks for functions to be executed before and after a command is executed.

Alternatively, one hook which gets the command as an argument and is responsible for executing it itself. This would enable modifing commands, but is that a good idea? Also, does it work with multi-line commands?

**Comment by zanchey** [comment]
I think this is fixed with #1666.

**Comment by faho** [comment]
Yes, #1666 provides fish_preexec and fish_postexec events. If anyone believes that doesn't solve the issue, please comment and I'll reopen.
