### ISSUE TITLE
Cannot run any commands with parameters after installing fish

### ISSUE THREAD

**Issue by stephanecharette** [fish-shell/fish-shell#6723]
I'm new to mac, but not new to fish.  Installed fish v3.1.0 using `brew install fish`.  Added /usr/local/bin/fish to /etc/shells, then changed my shell with `chsh -s /usr/local/bin/fish`.

Things worked well for about a day.  But now I'm in a position where my shell no longer works correctly.  If I type a command with no parameters, it works.  But as soon as I hit the spacebar, the command turns "red" and when I press ENTER it says "Unknown command".  Here is an example:

![image](https://user-images.githubusercontent.com/5061352/76195804-5793f080-61a6-11ea-99a6-47c3aeda34fa.png)

You'll note that `ls` worked fine, but `ls ..` did not.  At a complete loss as to what I messed up since I'm new to Mac and never seen this behaviour before.

**Comment by zanchey** [comment]
What does `fish_key_reader` show when you run it and hit space?

You could also have a look in the output of `bind` for the entry for `' '`.

**Comment by faho** [comment]
Yeah, this is most likely your space key not sending a space but a non-breaking space or similar.

Anyway, closing, if you have anything else we'll reopen.
