### ISSUE TITLE
Please document the `--path` and `--no-path` settings for the `set` command

### ISSUE THREAD

**Issue by runiq** [fish-shell/fish-shell#6728]
I stumbled upon these when going through the docs, but not where I would expect them:
Instead of being listed with all the other `set` arguments, `--path` and `--no-path` are only mentioned briefly in the Introduction.

**Comment by faho** [comment]
They are documented both in the [PATH variables](http://fishshell.com/docs/current/index.html#path-variables) chapter and the [set page](http://fishshell.com/docs/current/cmds/set.html).

All they do is make a variable a path variable so there's really not a lot to say.

If you have any specific suggestions I'd be glad to hear them.

**Comment by runiq** [comment]
I'm sorry, I didn't check master, only my own version of the docs (3.0.2). I should have gone with the issue template.

Sorry for the noise!
