### ISSUE TITLE
Fish hangs with 100% cpu usage, unless started as sh -c 'env HOME=$(mktemp -d) fish'

### ISSUE THREAD

**Issue by RaymiiOrg** [fish-shell/fish-shell#6730]
I installed fish via the Ubuntu PPA and it does not start, it hangs and uses 100% cpu:

![Selectie_0700](https://user-images.githubusercontent.com/1927494/76289084-97430100-62a8-11ea-9a09-1e6c012a3d93.png)

With the command `sh -c 'env HOME=$(mktemp -d) fish'` fish does start and the CPU usage is not extreme.

strace -f shows me that when started normally, it is `stat`-ing my entire homedir and all folders on the system.

Fish version: 3.1.0, installed via Ubuntu ppa
Ubuntu version: 18.04 LTS
Uname: Linux hostname 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by faho** [comment]
Well, the obvious thing to check here is your config. 

Do you have anything in config.fish or conf.d that could be doing this?

**Comment by RaymiiOrg** [comment]
I just installed it without any alteration to any config file. 

There is one config file:

`$ ls -la .config/fish/               
total 12K
drwx------  2 remy remy 4.0K Mar 10 08:09 .
drwxr-xr-x 53 remy remy 4.0K Mar 10 08:09 ..
-rw-r--r--  1 remy remy  102 Mar 10 08:09 fish_variables
`

With the following contents:

`$ cat .config/fish/fish_variables 
# This file contains fish universal variable definitions.
# VERSION: 3.0
SETUVAR __fish_initialized:0
`

**Comment by RaymiiOrg** [comment]
When I remove the PPA repository, do a <code>apt update</code> and then install the fish version out of the Ubuntu 18.04 repository (2.7.1) the problem also occurs.

**Comment by faho** [comment]
Ah, okay.

So this is a fresh install, and it's not specific to 3.1. That's good to know.

There are a few things fish does specifically on a fresh install.

For one, it generates the man page completions. In that case you'd expect to see a *python* process, not fish, and you'd only expect it to check a lot of directories in your $HOME if you configured $MANPATH weirdly.

Then there's the fact that you have $__fish_initialized set to 0,  which basically means that it's not in `__fish_config_interactive` (because that barely does anything before setting it to a higher value) but in share/config.fish (not to be confused with your config.fish, this is fish's internal initialization).

One possibility is that it's trying to find configuration snippets in $HOME, which could conceivably happen if you've set some of the $XDG vars weirdly.

Since all of this is down to the value of some exported variable that fish inherits, I'd very much like the output of `env` in e.g. bash - assuming starting fish in that triggers it.

**Comment by RaymiiOrg** [comment]
This is the output of <code>env</code> in bash:

GS_LIB=/home/remy/.fonts
    LC_ALL=C
    KDE_FULL_SESSION=true
    TERMINATOR_UUID=urn:uuid:d6260273-d9a9-44c0-94da-bec13fc9d4ec
    LANG=C
    DISPLAY=:0
    EDITOR=vim
    COLORTERM=truecolor
    XDG_VTNR=1
    MANDATORY_PATH=/usr/share/gconf/plasma.mandatory.path
    S_COLORS=auto
    XDG_SESSION_ID=3
    USER=remy
    DESKTOP_SESSION=plasma
    DEFAULTS_PATH=/usr/share/gconf/plasma.default.path
    PWD=/home/remy
    HOME=/home/remy
    SSH_AGENT_PID=11757
    QT_ACCESSIBILITY=1
    XCURSOR_SIZE=0
    XDG_SESSION_TYPE=x11
    XDG_DATA_DIRS=/usr/share/plasma:/home/remy/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share:/var/lib/snapd/desktop
    TERMINATOR_DBUS_NAME=net.tenshu.Terminator20x1a6021154d881c
    XDG_SESSION_DESKTOP=KDE
    GTK_MODULES=gail:atk-bridge
    TERMINATOR_DBUS_PATH=/net/tenshu/Terminator2
    TERM=xterm-256color
    SHELL=/bin/bash
    VTE_VERSION=5202
    XDG_SESSION_CLASS=user
    XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
    XCURSOR_THEME=Large Mouse Cursors
    XDG_CURRENT_DESKTOP=KDE
    XDG_SEAT=seat0
    SHLVL=1
    LANGUAGE=C
    LOGNAME=remy
    DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
    XDG_RUNTIME_DIR=/run/user/1000
    XAUTHORITY=/home/remy/.Xauthority
    XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session1
    QT_AUTO_SCREEN_SCALE_FACTOR=0
    XDG_CONFIG_DIRS=/etc/xdg/xdg-plasma:/etc/xdg:/usr/share/kubuntu-default-settings/kf5-settings
    PATH=/home/remy/bin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/snap/bin:/home/remy/.local/bin:/home/remy/bin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
    KDE_SESSION_UID=1000
    KDE_SESSION_VERSION=5
    SESSION_MANAGER=local/gateway:@/tmp/.ICE-unix/4873,unix/gateway:/tmp/.ICE-unix/4873
    _=/usr/bin/env

**Comment by faho** [comment]
Okay, unfortunately that doesn't appear to have anything too unusual. You have a C locale configured, which I strongly recommend against.

You also have a sizable $XDG_DATA_DIRS, which we scan for vendor config, but only in a subdirectory fish/vendor_conf.d in each, and non-recursive. So there shouldn't be any potential for infinite loops. Also we didn't do that in 2.7.0.

You also have a sizable $PATH, but only one thing is before the normal system directories - /home/remy/bin. It's possible we mistake one of those for a command we want to run, but I'm not aware of any commands we should be running here - the startup is almost all builtins - and I'm not sure why that would be showing up as us trying to stat a load of files?

A sample of your strace capture would be nice, maybe there's some pattern to the files it appears to be scanning?

It's also possible there's a symlink somewhere that leads us to search a massive directory for functions - if you symlinked ~/.config/fish/functions, I'm pretty sure fish'd go crazy eventually. But again a *recursive* scan, which would typically be necessary to have something really take long, would be quite surprising.

**Comment by krobelus** [comment]
Does the same happen when you run fish non-interactively, for example `fish -c true`.

With fish 3.1.0 you can start it like `env fish_trace=1 fish`, then you can see which statements are executed. This should be really useful.

The culprint must be somewhere in or after `/usr/share/fish/config.fish` and before the prompt is displayed (or in __fish_config_interactive).

**Comment by faho** [comment]
Closing because of a lack of response.

If anyone manages to reproduce this, we can of course reopen!
