### ISSUE TITLE
What is the easiest and stable way to determine that I'm in fish?

### ISSUE THREAD

**Issue by anki-code** [fish-shell/fish-shell#6734]
Hi!
For example I'm writing a Python app and I want to know what shell is used to run my app.

There is a question on stackoverflow: [How to determine the current shell I'm working on](https://stackoverflow.com/questions/3327013/how-to-determine-the-current-shell-im-working-on), but there are no good solutions for fish.

How I can understand from Python script that it was run from fish?

Thanks!

**Comment by faho** [comment]
The answer most likely is: Don't.

Trying to figure out "the users shell" is usually wrong. What do you want to do?

**Comment by anki-code** [comment]
I think about seamless mode for [xxh project](https://github.com/xxh/xxh). If user run xxh from fish I could use `fish.AppImage` by default without asking about shell name.

**Comment by faho** [comment]
If you literally want to run "the user's shell", just check $SHELL. That's the one time that variable is okay.

Add an override option in case the user wants a different shell (e.g. if they want to use "bash" just this one time).

Any more complicated solution isn't worth it.
