### ISSUE TITLE
help command uses openvt's open instead of xdg-open when DISPLAY is unset

### ISSUE THREAD

**Issue by ThomasAH** [fish-shell/fish-shell#6739]
fish 3.1.0 on Debian stretch.

Issue #5756 is not fixed when DISPLAY is not set, because help.fish contains:
```
            else if type -q xdg-open; and set -q -x DISPLAY
                set fish_browser xdg-open
            end
```

In this case /bin/open (the symlink to /bin/openvt on Debian stretch) is used, which results in the unhelpful error message "Couldn't get a file descriptor referring to the console".

Workaround: ```set BROWSER xdg-open```
(or maybe use dpkg-divert to hide the open command, but I haven't tested that)

xdg-open works fine even without a DISPLAY variable, in my case it opens the help in "links".

Debian buster does no longer have /bin/open, so the error does not occur there.

**Comment by faho** [comment]
Yeah, sure, let's just skip the $DISPLAY check.

Fixed on master and 3.1.1 (62525ab6b)
