### ISSUE TITLE
chsh: PAM authentication failed

### ISSUE THREAD

**Issue by txworking** [fish-shell/fish-shell#674]
i install fish shell through source code as root 

```
autoconf
./configure
make
make install
```

but when run `chsh -s /usr/local/bin/fish`

there is a error message `chsh: PAM authentication failed`
i googled it but didn't find the answer

any help would be appreciated

**Comment by heppu** [comment]
You can also add /bin/fish to /etc/shells and then use `chsh -s /bin/fish`.

**Comment by pickfire** [comment]
In `sudo make install`:

> To use fish as your login shell:
> * use the command 'chsh -s /usr/local/bin/fish'.

In My Humble Opinion, `fish` should add a `sed` (I forgot that one-liner sed) before `chsh -s /bin/fish`. Example:

```
To use fish as your login shell:
* add fish to /etc/shells with `grep -qs (which fish) /etc/shells; or echo (which fish) >> /etc/shells`
* use the command 'chsh -s /usr/local/bin/fish'.
```

**Comment by faho** [comment]
See #1368.
