### ISSUE TITLE
'systemctl start' completions miss certain unit files

### ISSUE THREAD

**Issue by exploide** [fish-shell/fish-shell#6740]
I noticed that certain systemd units do not get autocompleted for `systemctl start` while they do for `systemctl status`. I tried to find out why but I'm a bit confused regarding the completions for systemd.

I think it boils down to what is returned here: https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_systemctl.fish#L83 (or in line 77)

This returns nothing for me, while line 77 returns most of the units but not the ones I'm missing. I tried playing with the `--state` flag but as long as I don't remove it completely, the missed unit does not show up.

This is what the `status` gives me about that unit:

```
> systemctl status nessusd.service 
● nessusd.service - The Nessus Vulnerability Scanner
   Loaded: loaded (/usr/lib/systemd/system/nessusd.service; disabled; vendor preset: disabled)
   Active: inactive (dead)
```

Does someone know what state flag is missing here or why this does not show up?

**Comment by faho** [comment]
So this one is inactive and dead. That means it should show up when checking

```fish
systemctl list-units --state dead,failed
```

Which is also what that function ends up doing for `systemctl start `.

I see a whole bunch of units of just those states, so it seems to be working okay for me?

**Comment by exploide** [comment]
Also also see a bunch of units of those states but the one I mentioned is not there. Greping yields nothing. Another unit that is affected is `fwupd.service`

**Comment by faho** [comment]
Blergh... it seems like systemctl broke output.

They're keeping a "●" marker even if output is not a terminal and with --no-legend and --no-pager.

**Comment by faho** [comment]
Fixed in master and 3.1.1.

**Comment by exploide** [comment]
Thanks for the progress. But I'm afraid that does not fix my issue.

Your patch improves the parsing of unit files but the problem is what systemctl returns.

```fish
# this returns nothing
systemctl --no-legend --no-pager --all list-units | grep -E "nessus|fwupd"

# there they are
systemctl --no-legend --no-pager --all list-unit-files | grep -E "nessus|fwupd"
fwupd-offline-update.service                                     static         
fwupd-refresh.service                                            static         
fwupd.service                                                    static         
nessusd.service                                                  disabled       
fwupd-refresh.timer                                              disabled       

# and nothing again
systemctl --no-legend --no-pager --all list-unit-files --state=dead,failed | grep -E "nessus|fwupd"
```

**Comment by faho** [comment]
fwupd is `static`, which means it's not something you need to `start`, so it's okay that it's not listed.

`--state=dead,failed` doesn't make sense for list-unit-*files*. These should be caught by the list-*units*.

Is it possible this machine has been running for ages and you've not run `systemctl daemon-reload`?

**Comment by exploide** [comment]
> fwupd is static, which means it's not something you need to start, so it's okay that it's not listed.

True, I have not checked that while searching for examples.

> Is it possible this machine has been running for ages and you've not run systemctl daemon-reload?

No, it's a laptop system restarted daily.

> --state=dead,failed doesn't make sense for list-unit-files. 

But this is what happens in
https://github.com/fish-shell/fish-shell/blob/db7dfddc3be3ba2fd48bfcebecca4c1179c10901/share/functions/__fish_systemctl.fish#L84 ... Maybe it's wrong?

**Comment by faho** [comment]
Okay, so `systemctl list-units` will:

> List units that systemd currently has in memory.

So it seems that systemd doesn't have this unit in memory, presumably because hasn't been referenced this boot.

But `list-unit-files` shows all units with *enablement* state, which isn't enough - a unit can be disabled yet still currently running (e.g. it's been pulled in as a dependency or started manually), or enabled yet inactive.

So we need to filter it by *active* state, and for `start` we only want the units that aren't currently *running*. So we do have to pass something like --state=dead,failed (contrary to what I said earlier, yes), which I'm pretty sure used to work.

But apparently we can't, now, so we'd have to find some way to work around it.

So, how about:

```fish
systemctl list-units --all --no-{legend,pager} (systemctl list-unit-files --no-legend --no-pager -t service | string replace -r '\s+.*' '') --state dead,failed
```

Does that list that unit?

**Comment by exploide** [comment]
> Does that list that unit?

No it doesn't.

Maybe this helps to reproduce:

```
>_ systemctl status nessusd.service
● nessusd.service - The Nessus Vulnerability Scanner
   Loaded: loaded (/usr/lib/systemd/system/nessusd.service; disabled; vendor preset: disabled)
   Active: inactive (dead)


>_  cat /usr/lib/systemd/system/nessusd.service
# ---------------------------------------------------- #
#                                                      #
# WARNING: DO NOT EDIT                                 #
#                                                      #
# This file has been autogenerated, edits to this file #
# directly may be overwriten during a build            #
#                                                      #
# ---------------------------------------------------- #


[Unit]
Description=The Nessus Vulnerability Scanner
After=network.target

[Service]
Type=simple
PIDFile=/opt/nessus/var/nessus/nessus-service.pid
ExecStart=/opt/nessus/sbin/nessus-service -q
Restart=on-abort
ExecReload=/usr/bin/pkill nessusd
EnvironmentFile=-/etc/sysconfig/nessusd

[Install]
WantedBy=multi-user.target
Alias=nessusd.service
```

But I did not spot the relevant difference. That `Alias=` looks strange because it already is named like this. Then the service file was marked as executable, which is not necessary. But changing this and doing `systemctl daemon-reload` did not help.

**Comment by faho** [comment]
Okay, this sucks.

We need to explicitly filter this via e.g. `systemctl show` or `systemctl is-active`. Blergh.

**Comment by exploide** [comment]
I thought about whether that proprietary nessus software does something wrong when installing the unit but I think it doesn't. The timer unit `fwupd-refresh.timer` does also not show up but I know of no reason why it shouldn't.

So it really seems to be the filtering. The bash completion gets it right. It is maintained upstream and does the filtering in multiple steps with some helper functions https://github.com/systemd/systemd/blob/master/shell-completion/bash/systemctl.in#L69

Indeed, it's done using a call to `systemctl show`

**Comment by faho** [comment]
>So it really seems to be the filtering. The bash completion gets it right

Super hecking awkward tho. Why they don't just add a thing to print all inactive units I'll probably never know.

**Comment by zanchey** [comment]
Would these completions be better done upstream?

**Comment by faho** [comment]
What would be better done upstream would be introspection facilities. The bash completions do a thing that we're currently struggling with:

```bash
    IFS=$',' read -r -a p < <(echo "Names,$properties")
    n=${#p[*]}
    readarray -t props < \
              <(__systemctl $mode show --property "Names,$properties" -- "${units[@]}")
```

With $properties being something like "CanStart=yes".

Why `systemctl show` doesn't just directly filter on the given properties I have no idea - instead it'll show everything, and just replace the "CanStart=Yes" with an empty line.
