### ISSUE TITLE
Cannot join strings beginning with '-' : Unknown option '-bar'

### ISSUE THREAD

**Issue by tuberry** [fish-shell/fish-shell#6741]
Fish: 3.1.0
OS: Linux arch 5.5.8
Term: xterm-256color

- [x] Tried fish without third-party customizations

Steps to reproduce: `string join ' ' 'foo' '-bar'` or `string join ' ' foo -bar`

**Comment by faho** [comment]
Use `--` to signal the end of options:

```fish
string join ' ' -- 'foo' '-bar'
```

This doesn't just apply to fish, but most commands - as soon as you're accepting options anywhere on the commandline you need something like this, the alternative is to only accept options before the first non-option, which is pretty awful to use.

**Comment by tuberry** [comment]
Thanks a lot!
