### ISSUE TITLE
feature request: git branch name completion

### ISSUE THREAD

**Issue by sheldon** [fish-shell/fish-shell#675]
i noticed branch name completion doesn't check remote branch names, which would be quite useful for local checkouts of new remote branches e.g.

git pull
<receive branch new-branch-3>
git checkout <tab>
<new-branch-3 should appear in the completions list here, not only already checked out local branches>

hope it's clear, i'll see if i can get it working myself too!

**Comment by brettanomyces** [comment]
This would be great. I'm always accidentally creating detached heads

**Comment by roger-zacharczyk** [comment]
+1

**Comment by sengaya** [comment]
+1

From the git man page:
>           If <branch> is not found but there does exist a tracking branch in exactly one
>           remote (call it <remote>) with a matching name, treat as equivalent to
>
>               $ git checkout -b <branch> --track <remote>/<branch>

It would be nice if the auto-completion would detect branches with exactly one remote and strip the remote part away in that case.

**Comment by faho** [comment]
I just pushed 4fcda28, which should fix this. I've been a bit careful not to show these branches on all commands - e.g. `git branch` seems to _accept_ one of these, but doesn't seem to _do_ anything with it and just quit with a 0 status. That doesn't seem too useful, so I left it out for now.
