### ISSUE TITLE
Inline editing with string builtin does not work anymore

### ISSUE THREAD

**Issue by InspectorMustache** [fish-shell/fish-shell#6756]
This used to work:
```
string replace 'one' 'two' < $file > $file
```
Now it doesn't anymore. The command turns `$file` into an empty file. I think this changed with 3.1 but I'm not a 100% sure. I don't know if this is related to the `string` command or to redirection but it is how most programs work and why sed has the `-i` flag. So I was just wondering if this is an intentional change.

**Comment by faho** [comment]
Yeah, this probably worked before because fish buffered builtin output. Removing *that* (in many cases right now, expanding) is entirely intentional.

This idiom *can't* really work with unix semantics.

**Comment by InspectorMustache** [comment]
Cheers! Good to know.
