### ISSUE TITLE
`read` in wrapper definition executed on load

### ISSUE THREAD

**Issue by ron-wolf** [fish-shell/fish-shell#6761]
I wrote a function wrapping `rm` using the built-in `read`. When it’s placed at `~/.config/fish/functions/rm.fish`, entering <kbd>rm </kbd> followed by a space and another character calls `read`. When it’s done, `fish` returns to the prompt, but only re-prints the prompt message on further input.

I have attached [the offending function’s definition](https://github.com/fish-shell/fish-shell/files/4341043/rm.fish.txt); if you would like to attempt reproducing the issue, the following one-liners are useful and can be copied with a triple-click:

```fish
# to install the file:
curl -o ~/.config/fish/functions/rm.fish --create-dirs https://github.com/fish-shell/fish-shell/files/4341043/rm.fish.txt

# to remove the file:
rm -f ~/.config/fish/functions/rm.fish
```

I am using `fish` version <span>3.1.0</span> on macOS <span>10.14.6</span>, with the default <span>Terminal.app</span>. The issue persists even when my home directory is moved. I have also created [an asciinema recording](https://asciinema.org/a/8VCDBaqizwUwZhCn1TcIpx3ch) of the issue. The only similar issue I found was #328, which concerns loading the description for a wrapper function.

**Comment by faho** [comment]
This is to be expected, the `rm` completions call `rm --version` to figure out if you have GNU or another rm, and the completions are sourced to figure out when a file is okay for autosuggestions.

In general a wrapper needs to follow the general idea of a command. In this case I'd suggest calling your thing something else, like `del`.

**Comment by ron-wolf** [comment]
> In general a wrapper needs to follow the general idea of a command - especially when it comes to changes in when you read from stdin (or write to stdout).

That makes a lot of sense, and is a good default behavior. For my particular usage, I’ll probably just add an extra case for the `--version` argument, since I’m wrapping it to make sure any usage is interactive anyway.

Thanks for the tip!
