### ISSUE TITLE
Cannot update completions on CentOS Linux release 7.7.1908 (Core)

### ISSUE THREAD

**Issue by StewAlexanderACC** [fish-shell/fish-shell#6766]
Error Message:
```
Failed to execute process './create_manpage_completions.py'. Reason:
The file './create_manpage_completions.py' does not exist or could not be executed.
```
Under  ```/u/s/f/tools>```

Fish Version: ```2.3.1```  
OS Version: ```CentOS Linux release 7.7.1908 (Core)```
Linux Version:```3.10.0-1062.12.1.el7.x86_64 ```

Tried ```$chmod +x create_manpage_completions.py``` and re-running, nope.

```
support@glyptodon /u/s/f/tools> stat create_manpage_completions.py
  File: ‘create_manpage_completions.py’
  Size: 36840           Blocks: 72         IO Block: 4096   regular file
Device: fd00h/64768d    Inode: 203005456   Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Context: system_u:object_r:usr_t:s0
Access: 2020-03-18 12:38:26.519225794 -0400
Modify: 2019-03-07 14:54:29.000000000 -0500
Change: 2020-03-18 12:38:15.550226178 -0400
 Birth: -
```

**Comment by faho** [comment]
>Fish Version: 2.3.1

Sorry, that version is waaaaayyy too old and we don't support it anymore. Please upgrade fish and try again.

**Comment by faho** [comment]
You'll want the RHEL 7 packages from our PPA at https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A3&package=fish.

**Comment by zanchey** [comment]
You might be able to work around it by running `python /usr/share/fish/tools/create_manpage_completions.py`.
