### ISSUE TITLE
source: Error encountered while sourcing file '#!/usr/bin/env fish':

### ISSUE THREAD

**Issue by 404cn** [fish-shell/fish-shell#6771]
fish version 3.1.0
mac os 10.15.3

when I start terminal it shows 

> source: Error encountered while sourcing file '#!/usr/bin/env fish':

> source: No such file or directory

Don't know what happen, it all works well before.

Here is my fish config file.

![Screen Shot 2020-03-19 at 10 13 34 PM](https://user-images.githubusercontent.com/24653356/77076517-e4ed0580-6a2e-11ea-9be3-b08c2489926d.png)

**Comment by faho** [comment]
Well, it seems that `navi widget fish` thing prints a fish *script*, not the filename of one.

Simply changing it to

```fish
navi widget fish | source
```

should fix it.

**Comment by faho** [comment]
Which would also match [navi's documentation](https://github.com/denisidoro/navi#shell-widget)

**Comment by 404cn** [comment]
Thanks very mach. It worked. 😄️

**Comment by faho** [comment]
Note: This was changed in Navi by the (*massive*) PR https://github.com/denisidoro/navi/pull/258
