### ISSUE TITLE
Cycling through history tokens overwrites commandline text

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#6774]
Using https://github.com/fish-shell/fish-shell/commit/0d43615af2c4bf44bec4299b5b1e955ac44f39c1

---

**Note:** `|` denotes cursor position

**Expected behaviour:**
```sh
$ echo foo bar baz
foo bar baz
$ echo foo r| baz
# alt+. to recall "bar" token
$ echo foo bar| baz
```

**Actual behaviour:**
```sh
$ echo foo bar baz
foo bar baz
$ echo foo r| baz
# alt+. to recall "bar" token
$ echo foo bar 
#              ^^^
#              "baz" token gets overwritten/erased
```

**Comment by krobelus** [comment]
Alright, bisects to 8a033b9f3d81411897483faf8dbaea3e210ec64f.

Oddly enough this works fine on #6686.

**Comment by zx8** [comment]
Out of curiosity, how did you bisect it to that commit so far? I'd love to include this sort of info in my issues in future to save you some time! 😄

**Comment by krobelus** [comment]
It was quick because it worked on 3.1.0 ;)

```fish
$ git bisect bad 0d43615
You need to start by "git bisect start"
Do you want me to do it for you [Y/n]?
$ git bisect good 3.1.0
Bisecting: 198 revisions left to test after this (roughly 8 steps)
[59c6663a16d052978f265c9517f3c0bccc3b9779] Migrate the "are you sure you want to exit" logic from parse_execution to exec
```

And then compile and check if the problem occurs. If yes use `git bisect bad`, otherwise `git bisect good`. It's incredibly useful.

**Comment by zx8** [comment]
Aha, yes, have used `git bisect` before.

I thought `fish` might have had some automated mechanism of invoking bindings like `alt+.`, then comparing against some expected output on each commit, but I guess you just manually pressed the keybind on each commit rather than using `git bisect run <cmd>...`?

**Comment by krobelus** [comment]
Yeah I did it manually, it's only 8 times after all.

But this is also easy to automate inside tmux:
`fish -C 'tmux send echo Space foo Space r Space baz M-b C-b M-.'`

We also have some tests using `expect` but I don't use that much.

**Comment by zx8** [comment]
Amazing tip to use something like `tmux` - would never have considered it, thank you!

(Feel free to mark these comments are off-topic/resolved as they don't relate to the OP 👍)
