### ISSUE TITLE
Allow fish_update_completions to skip already generated files

### ISSUE THREAD

**Issue by JanczarKurek** [fish-shell/fish-shell#6775]
Hi

I was making some hooks to pacman to regenerate fish completions upon installing/updating packages. Regenerating all completions each time can be pointless, and in most cases we're interested in generating only few completions.

This can be done by getting this info from package manager and manually choose files to fish_update_completions. It is unfortunately distro-dependent and maybe needs some logic already existing in code (mapping manpage names into completion names for example).

My proposal is to implement this as an optional flag into script - for example by checking mod times of manpages and completions. I am willing to implement this change if accepted.

**Comment by zanchey** [comment]
SGTM! One thing to think about is if the path is different (eg first completion generated from `/usr/share/man/man1/foo.1`, when regenerated it is picked up from `/usr/local/share/man/man1/foo.1` instead).

**Comment by faho** [comment]
I would assume you'd get most of the bang for quite a bit less effort if you just passed the paths of all the changed manpages?

If I e.g. update `coreutils`, just passing all the files that touched in /usr/share/man/man1/ (figuring that path out left as an exercise to the reader), like /usr/share/man/man1/ls.1.gz, should allow us to skip most other manpages and allow most of the speed up.

**Comment by JanczarKurek** [comment]
I agree this is possible to achieve outside python script, but e.g. that path figuring part is already done in script (and takes some lines to be as broad as possible).

**Comment by JanczarKurek** [comment]
Ok, first of all - script always removes all existing completions from destination directory, and thats not a nice thing when it comes to regenerating. Imho cleanup in target directory should be at least non mandatory, especially that we already have --cleanup-in flag that can do the same thing. What do you think?
