### ISSUE TITLE
The completions

### ISSUE THREAD

**Issue by startnoob** [fish-shell/fish-shell#6782]
Fish Version:3.1.0
OS:Linux ralph-pc 5.5.8-1-MANJARO
No third-party customizations installed.

I want to use yay to install some packages, but I found that all the completions was from AUR and "Package Group" instead of both AUR and the offcial repositories "Package". When I used pacman to install them, the completions from the official repositories worked fine.

I switched to zsh, but the same situation.
I want to know why it happened and how can I get the completions from both AUR and the official repositories "Package".
Thanks.

**Comment by faho** [comment]
Yay actually ships its completions [upstream](https://github.com/Jguer/yay/tree/next/completions), so I suggest opening an issue there.

**Comment by startnoob** [comment]
Ok,Thanks.

**Comment by startnoob** [comment]
Ok,Thanks.
