### ISSUE TITLE
Improve doc consistency on the markup of the word "fish"

### ISSUE THREAD

**Issue by Delapouite** [fish-shell/fish-shell#6785]
Hello

I'd like to get your input on the following observation regarding the current documentation.

Sometimes the word "fish" is emphasized (through markup), sometimes it is not.
Let's illustrate with some screenshots:

![image](https://user-images.githubusercontent.com/39315/77228013-a5383200-6b84-11ea-9f2e-8f9fa608f8e9.png)

![image](https://user-images.githubusercontent.com/39315/77228115-5f2f9e00-6b85-11ea-9000-fab6e9f5f326.png)

As you can see, it's quite random.

For the sake of having a consistent behavior through the doc we basically have two options:

1. **Always** use emphasis on the word "fish"

- Does it improve the ease of a reading a paragraph or a section for a human?
- Does it create needless noise and make other emphasized word like commands, paths or variables hard to distinguish?
- Should the word "fish" use "bold" or "italic" markup instead? Or even a different text color?

2. **Never** use emphasis on the word "fish"

- Is the shell brand kind of "lost" by becoming a "common word"?

What's your opinions on these matters? Thanks

**Comment by faho** [comment]
I don't think the emphasis really looks good or helps understanding - "fish" is a weird enough word to show up in these contexts that it's clear it's about the shell.

I also don't think we should be overly protective about branding in this way - the worst thing you can do with a brand is to plaster ® or ™ after it.

So I'd probably ditch it, unless we can come up with a nice subtle style that doesn't look like a command.

**Comment by zanchey** [comment]
I agree that there's no need for emphasis when referring to fish-the-program, though it's obviously still appropriate for fish-the-command. Although it would normally be capitalised as a proper noun, https://fishshell.com/ uses "fish" in lowercase (like "sh", but not like "Bash" or "Zsh"), so we should stick to that.

The galaxy-brain approach is to make it a macro!

**Comment by faho** [comment]
Calling this preliminarily done since we appear to have removed the markup.
