### ISSUE TITLE
Add missing --physical and --logical long options to pwd command?

### ISSUE THREAD

**Issue by Delapouite** [fish-shell/fish-shell#6787]
Hi

When I let fish autocomplete `pwd` options, I get the following:

![image](https://user-images.githubusercontent.com/39315/77229146-64dcb200-6b8c-11ea-8801-cae747341d38.png)

But then, since the builtin `pwd` command has no long option `--physical`:

![image](https://user-images.githubusercontent.com/39315/77229160-86d63480-6b8c-11ea-88b9-490f48d519ac.png)

Should `--physical` and `--logical` be added to the fish builtin?

**Comment by faho** [comment]
Yeah, the completions are wrong, these options don't exist.

So let's make them right - we don't typically do short-only options.

**Comment by ammgws** [comment]
So the conclusion is to add the long options to the `pwd` builtin?

Would end up matching the system command, for what it matters:
![image](https://user-images.githubusercontent.com/20397027/77229908-de4bc300-6bd3-11ea-9519-04ef0e0cc573.png)

**Comment by faho** [comment]
Yup, and it's done.
