### ISSUE TITLE
Suggestions without new prompt

### ISSUE THREAD

**Issue by beho** [fish-shell/fish-shell#679]
Is it possible to configure fish not to clone current prompt when printing out suggestions ? I would like to be able to continuously edit a single line even if navigating into some deep directory while using suggestions and completions several times.

ZSH does this out of the box (I have no idea if it's configurable). It simply prints out suggestions, overwrites/updates them when requesting another suggestion and clears them after executing a command. This way suggestions never stay on screen after issuing a command.  It is much cleaner than fish printing out a list of suggestions and new prompt with previous content every time there is an ambiguity.

**Comment by AndreTheHunter** [comment]
+1
I'd love to see this feature too

**Comment by ridiculousfish** [comment]
fish master does this now

**Comment by xfix** [comment]
If it does, then why not close this issue?
