### ISSUE TITLE
Bad link in online documentation

### ISSUE THREAD

**Issue by nrnrnr** [fish-shell/fish-shell#6794]
The 3.1.0 documentation at <https://fishshell.com/docs/current/tutorial.html> has a dangling link to <https://fishshell.com/docs/current/prompt>, which 404s.

**Comment by faho** [comment]
Already fixed by 7172bd38b3 - #6627

**Comment by nrnrnr** [comment]
I gather the web site is not updated until the new release ships?

**Comment by faho** [comment]
Indeed.
