### ISSUE TITLE
Unicode characters make the prompt disappear

### ISSUE THREAD

**Issue by shreve** [fish-shell/fish-shell#6799]
```
$ fish --version
fish, version 3.1.0

$ echo $TERM
xterm-256color
```

Since upgrading to 3.1.0 my prompt has been behaving oddly. The right prompt would shift around and if I resized my window the left prompt would completely disappear.

I tried the blank environment and the issue went away.
I disabled Oh My Fish, reverting back to the default prompt and the issue also went away.
I tried to rebuild my prompt from scratch and the issue was gone until I added back in special characters.

![2020-03-23--12-50-22--967x1165](https://user-images.githubusercontent.com/253634/77342894-43540580-6d07-11ea-9774-602cfe8caf5d.png)

The difference between these two sessions is the presence of ↓ in the left prompt.

One of the characters I had previously tried was an emoji, so I tried different values of `$fish_emoji_width`, but to no avail.

I'm currently using Konsole, but this also happens in Alacritty.

Even just the presence of a special character in the input seems to break rendering.
![2020-03-23--13-42-36--927x554--10s](https://user-images.githubusercontent.com/253634/77346178-3685e080-6d0c-11ea-97d3-8013c9acbfa2.gif)

**Comment by faho** [comment]
"↓" is not an emoji, it is a character of ambiguous width.

I.e. set fish_ambiguous_width to 1.

**Comment by shreve** [comment]
That didn't result in any difference.

**Comment by faho** [comment]
Set it to 2?

Otherwise the remaining possibility is that you have more than 1 ambiguous character in your prompt, and that they're rendered of different width.

Can you try reducing it to a simple prompt and share the code?

Also what OS is this on?

**Comment by faho** [comment]
Oh, wait, this is a duplicate of #6736 

You are using a C locale. Stop that and it'll work.

**Comment by shreve** [comment]
I had to reconfigure the locale and reboot (that's arch for you), but setting `LANG=en_US.UTF-8` resolved this.
@faho Thank you for this, and thank you for all the work you do on fish.
