### ISSUE TITLE
The `nim` theme doesn't deal gracefully with vi mode

### ISSUE THREAD

**Issue by DanielFabian** [fish-shell/fish-shell#6802]
When using vi mode, fish draws a `[I]` and `[N]`, respectively. But unfortunately, those shift the prompt making it sub-optimal:

![image](https://user-images.githubusercontent.com/1929340/77421011-fd5c7780-6dc2-11ea-8d2d-4e977879b246.png)

I'm using fish `3.0.2`, no customizations beyond setting vi mode and changing the prompt to nim from `fish_config`.

Could we please adjust the nim prompt in such a way, that it would recognise vi mode and incorporate it into the prompt rather than causing this shift?

**Comment by faho** [comment]
Yeah, the nim prompt would have to define an empty `fish_mode_prompt` and then handle the vi-mode indicator.
