### ISSUE TITLE
Playground has outdated documentation

### ISSUE THREAD

**Issue by soumya92** [fish-shell/fish-shell#6810]
https://rootnroll.com/d/fish-shell/ from the readme.

The document on the left side has a few things that are no longer true:
- "Unlike other shells, stderr is redirected with a caret ^": deprecated, probably going away soon, shouldn't included it explicitly.
- "Unlike other shells, fish does not have special syntax like && or || to combine commands": While I prefer `and`/`or` for their flexibility, we should avoid saying that "&&" and "||" are not supported, since they work as expected.

I don't know how to update the doc, so I cannot send a pull request making these changes. Hopefully someone here knows how to fix these minor issues :)

**Comment by faho** [comment]
It's a third-party project and they've simply not updated fish to 3.1.

**Comment by zanchey** [comment]
Probably https://github.com/rootnroll/library/blob/master/fish-shell/Dockerfile needs updating, I'm not sure if @psviderski can take a look.
