### ISSUE TITLE
Use multiple completion files for a single command

### ISSUE THREAD

**Issue by PiOverFour** [fish-shell/fish-shell#6814]
Hi,
is there a way to use multiple completion files for a single command?

This is useful when a program has plugins or extensions shipped separately, which are called with the same command but different options or subcommands.
In my case, I use the [`pass`](https://www.passwordstore.org/) password manager, with the [tail](https://github.com/palortoff/pass-extension-tail) extension. This extension is called with a subcommand, like:
```
pass tail [options]
```
Fish [completions](https://git.zx2c4.com/password-store/tree/src/completion/pass.fish-completion) are shipped with `pass`, but I couldn’t find a way for the extension to have its own completions since they would need to be in a file also called _pass.fish_ in order to be loaded (per the [docs](http://fishshell.com/docs/current/index.html#where-to-put-completions), “A completion file must have a filename consisting of the name of the command to complete and the suffix '`.fish`'.”), and that would conflict with the main completions.

Thanks!

fish, version 3.0.2

**Comment by faho** [comment]
The best thing to do here is probably to make a *new* pass.fish that explicitly `source`s the old one.

**Comment by PiOverFour** [comment]
Right, but then how would you distribute this in a package manager without overriding the original one? Say I have five extensions for a single program, each adding its own completions to vendor_completions.d. There is bound to be a conflict between them, and they can’t all be named pass.fish, I think?

Anyway, thank you for the reply.

**Comment by zanchey** [comment]
Your `pass.fish` can load other files, though. What about something like this at the bottom:

```
source /usr/share/pass/fish-completions/*.fish
```

**Comment by PiOverFour** [comment]
Ah yes of course, it makes complete sense! Thank you. :)
