### ISSUE TITLE
Proposal: `return --previous`

### ISSUE THREAD

**Issue by soumya92** [fish-shell/fish-shell#6817]
## Overview

Allow functions/builtins to "pass through" the previous $status. Allow the prompt/postexec functions to determine when that happens.

## Background

There are some cases where there is "no status", that is, the function/builtin should just do it's work without affecting $status. Examples:
- Backgrounded tasks. Since the exit code cannot be obtained, `foo &` will just pass through the previous status.
- `set` in some cases (all except --erase, --names, --query, --show)

This could be useful for user-defined functions as well, such as a "log" function (example later).

Currently these just return the previous status, which works in scripts, but can be annoying in interactive sessions, because there's no way to determine when this has happened, so the exit status could be attributed to the wrong command (details in #6815).

## Proposal

Allow `return --previous` to indicate that the current function does not affect $status. This would allow something like:

```
function log -a message
  echo $message
  return --previous
end
```

This function can be dropped in almost anywhere without affecting logic. For example, the following two snippets will behave the same.

```
test -n "$foo"
and do_something
```
```
test -n "$foo"
log "foo = $foo"
and do_something
```

In fish internals (C++ side only), this would return a special value that would cause $status to re-use the previous value.

Then, to correctly attribute the status, the `fish_postexec` function will get a second argument that indicates whether the $status is from the command in the first argument or not. As long as any command in the current commandline produced a non-`--previous` return value, this will be set to true. If no command produced a return value (e.g. all backgrounded), then $status will continue its current behaviour, but the postexec hook's second argument will be different.

By only surfacing this case specially in the interactive mode hook, fishscript behaviour does not change at all, and users who rely on postexec for summaries (e.g. undistract me) can correctly identify whether $status actually came from the command being executed.

## Implementation Details

All subject to change, of course, but my initial thought is that a return code with value >255 could be used for this. This value will only be seen in the internals, and an attempt to set the status to this value would simply preserve the previous value.

In reader, keep track of whether any calls were made to set the status to a normal value, and if not, flip the flag for the postexec handler.

Thoughts?

**Comment by soumya92** [comment]
## Alternative

Only add the second argument to postexec, and only allow builtins (set) to modify it.  
User-defined functions can continue to use `set prev_status $status; ...; return $prev_status`.

This is simpler and requires (almost) no user-facing changes. It would give builtins a special ability that fishscript functions will never be able to replicate, but maybe that's worth keeping the simplicity of return.

**Comment by Darkshadow2** [comment]
```fish
function somefunc
    set -l pstatus $status
    ...
    return $pstatus
end
```

**Comment by faho** [comment]
Let's keep this in #6815.
