### ISSUE TITLE
Distinction between Ctrl-C and exit 130 is gone

### ISSUE THREAD

**Issue by soumya92** [fish-shell/fish-shell#6822]
**fish, version 3.1.0-442-gdee2adf03**

Prior to the fix for `fish_postexec` not being called on interrupt, I could set a flag in `fish_preexec` and clear it in `fish_postexec`. If I made it to fish_prompt with the flag set, I would know that the previous command was cancelled (rather than exit 130).

Now, with `fish_postexec` (correctly) being called even after a Ctrl-C, there's no way to distinguish something that exited with 130 on its own from something that was terminated by the user pressing Ctrl-C.

It would be nice if there was some way to do that. Would it be possible to add an event that triggers on Ctrl-C? (`--on-signal INT` doesn't work because the signal is sent to the foreground process, not fish).

I would have called such an event `fish_cancel`, but that name is already in use. `fish_exec_cancel` maybe?

**Comment by zanchey** [comment]
Fixed with the merge of #6824.
