### ISSUE TITLE
annoying (master) suddenly appeared in prompt?

### ISSUE THREAD

**Issue by QuercusFelis** [fish-shell/fish-shell#6823]
Without touching fish, my prompt suddenly looks disgusting. This may have been a result of a system update, though I have no idea what would have caused this. All I really want to know is what do I have to do to make it go away forever, thank you.

```
wood@woodbox ~ (master)> fish --version
fish, version 3.1.0
wood@woodbox ~ (master)> uname -a
Linux woodbox 5.5.13-arch1-1 #1 SMP PREEMPT Wed, 25 Mar 2020 16:04:40 +0000 x86_64 GNU/Linux
wood@woodbox ~ (master)> sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
wood@woodbox /h/wood (master)> 
```

**Comment by krobelus** [comment]
The VCS prompt displays info inside git and mercurial repos.
Use `cp /usr/share/fish/functions/fish_prompt.fish ~/.config/fish/functions/`, then remove the VCS prompt calls from the penultimate line in `~/.config/fish/functions/fish_prompt.fish`.

**Comment by QuercusFelis** [comment]
I have done this to no effect. The message persists in the prompt even after restart.

**Comment by krobelus** [comment]
The output of `type fish_prompt` tells you where fish got the prompt, it should be using the new one.

I realize you can get the old default prompt back by running `fish_config`, go to the prompt tab and select "classic" and click "set prompt". This is simpler than manually editing the prompt.

Equivalently, put the following in `~/.config/fish/functions/fish_prompt.fish`:

```fish
function fish_prompt --description 'Write out the prompt'
    set -l color_cwd
    set -l suffix
    switch "$USER"
        case root toor
            if set -q fish_color_cwd_root
                set color_cwd $fish_color_cwd_root
            else
                set color_cwd $fish_color_cwd
            end
            set suffix '#'
        case '*'
            set color_cwd $fish_color_cwd
            set suffix '>'
    end

    echo -n -s "$USER" @ (prompt_hostname) ' ' (set_color $color_cwd) (prompt_pwd) (set_color normal) "$suffix "
end
```

**Comment by QuercusFelis** [comment]
This worked, thank you!
