### ISSUE TITLE
How to run fish with custom "rc file"?

### ISSUE THREAD

**Issue by anki-code** [fish-shell/fish-shell#6829]
Hello!

I'm going to add plugins support for fish in [xxh project](https://github.com/xxh/xxh).

And I've faced with interesting question. Every shell I've seen (bash, zsh, xonsh) has `--rcfile` argument which specify what file will be executed first. For example `bash --rcfile start.sh -i hello.sh` bring all variables from `start.sh` to `hello.sh`.

In the fish documentation I see only one default way: `$XDG_CONFIG_HOME/fish/config.fish`. It's wrong way for my case of running portable fish.

Please help: how I can run fish commands/files with preexecuted "rc file"?

Something like: `fish --rc default.fish script.fish`

Thanks!

**Comment by faho** [comment]
>In the fish documentation I see only one default way: $XDG_CONFIG_HOME/fish/config.fish.

That's it. Set $XDG_CONFIG_HOME.

>I'm going to add plugins support for fish in xxh project.

What exactly do you mean by "plugin support"?

**Comment by anki-code** [comment]
`$XDG_CONFIG_HOME` is global variable. What if I need to run fish with custom preexecuted "rc file" without changing global variables?

**Comment by anki-code** [comment]
My use case:
1. For example I have `plugins.fish` file which `source` some files.
2. I need to run fish with sourcing this files. Something like this: `bash -c "fish --rc plugins.fish -c 'hello world!'"`

**Comment by faho** [comment]
>What if I need to run fish with custom preexecuted "rc file" without changing global variables?

You don't.

If you want to run additional code (this can include `source`) *before* config.fish is sourced, there is the `--init-command` option. There is no option to stop fish from reading config.fish.

**Comment by faho** [comment]
Alternatively there is conf.d, in which you can place files (with a ".fish" suffix) that fish will then `source` on startup.

**Comment by anki-code** [comment]
It looks like the partial solution is:
```
fish -C "source rcfile.fish"
```

It works for interactive mode:
```
echo 'source 2.fish' > 1.fish
echo 'echo ok; set qqq 222'> 2.fish
fish -C "source 1.fish"
ok
f> echo $qqq
222
```
But it does not work for command:
```
> fish -C "source 1.fish" -c "echo $qqq"
ok

> fish -C "source 1.fish" -i -c "echo $qqq"
ok

```
Is there a way to run `-c` with `-C`?

**Comment by anki-code** [comment]
It looks like a bug. My fish version 3.10.

**Comment by faho** [comment]
You've double-quoted the -c argument, so $qqq is expanded before the inner fish is executed.

>fish -C "set qqq 333" -c "echo $qqq"

Try `fish -C "set qqq 333" -c 'echo $qqq'`

**Comment by anki-code** [comment]
As, sorry! My bad.

**Comment by thuzhf** [comment]
> > What if I need to run fish with custom preexecuted "rc file" without changing global variables?
> 
> You don't.
> 
> If you want to run additional code (this can include `source`) _before_ config.fish is sourced, there is the `--init-command` option. There is no option to stop fish from reading config.fish.

You said the additional code is run _before_ config.fish, but I found that it is run _after_ config.fish, and `man fish` also shows that: "-C or --init-command=COMMANDS evaluate the specified  commands  _after_  reading  the  configuration". I want some code to be run _before_ config.fish (e.g. some code that will modify config.fish, etc.). How can I achieve this?

**Comment by faho** [comment]
>I want some code to be run before config.fish (e.g. some code that will create or modify config.fish in some k8s/docker-related cases). How can I achieve this?

@thuzhf There is no such functionality in fish that I'm aware of, and modifying config.fish seems like a fairly suspect thing to do.
