### ISSUE TITLE
Messed up history after long time of use

### ISSUE THREAD

**Issue by ghost** [fish-shell/fish-shell#6832]
Fish version: `3.0.2`

For example my history is sorted from latest to oldest:

```shell
something
someone
```

Opening new session, pressing `s` will suggest `something`.

After a long time of use, `something` disappears. Then only `someone` exists. I cannot even search for `something`. But closing that session, then opening new one will make things working again.

Would you please fix?

Thank you,

**Comment by Delapouite** [comment]
As OP deleted its GitHub account, it will be hard to have more info. I suggest to close this issue.

**Comment by dab05f05-369dece7-afd33b96-b7bed6ce** [comment]
Wow.

It wasted me a lot of time for simply trying to protect my privacy.

I was the one who filed this issue.

But I learned something:

- Privacy is luxury here. I shouldn't expect it.
- Contributors referred to a human being as _"it"_, as in _"its github account"_.

And the most important thing: I _did_ you a favor by filing a bug report. I declared a bug. You can call it whatever you want. Then I got treated like this.

Thanks a lot. I learned not to mess with this project-ever-again.

**Comment by zanchey** [comment]
From our perspective, it will be difficult for us to discern your intention of protecting your privacy without it being stated. Consider also the use of "it" as a gender-neutral pronoun.

My suspicion is that you are hitting #6032; it would be interesting to know whether there are any blanks in your history file, and also if you can upgrade to 3.1.0 then if the behaviour is still there.

You might consider showing the actual lines of your history file that cause the problem, and if you can give some idea of how long "a long time of use" is that would be useful.

Finally, this is our workspace. We appreciate the time you took to file a bug report. In turn, perhaps you can appreciate that this software is entirely developed by volunteers, is made available for free, and is covered by no warranty, express or implied. While you may feel that your behaviour may be perfectly reasonable, it is at least unusual and it will cause some confusion.

I cannot decide for you if you would like to participate in this process, but will reopen the issue regardless.

**Comment by faho** [comment]
Terribly sorry, but it doesn't appear like there'll be movement on this issue, which is most likely a duplicate anyway.

Closing!
