### ISSUE TITLE
The paste is wrong when setting bind.

### ISSUE THREAD

**Issue by hotoolong** [fish-shell/fish-shell#6834]
The following settings were added to the config file
```
bind \e\] nextd-or-forward-word
```
I reread the config file and pasted the string and got the following
```
200~configs/fish/config.201~fish
```
The same thing did not happen when I removed the bind setting.

I have not been able to confirm if this is being replicated on other machines. 
Is there anyone who is experiencing the same thing?

Fish version: 3.1.0_1
Darwin hotoolong.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
screen-256color

**Comment by faho** [comment]
The "200~" and "201~" bits are parts of the bracketed paste start/end sequences. That's a terminal function that fish turns on to distinguish between pasted text and manually entered text (so it can e.g. not execute multiline input immediately).

What is your terminal? What did you paste exactly - it appears to be the string "configs/fish/config." and then possibly a "fish".

What does `bind | grep paste` say?

**Comment by hotoolong** [comment]
The copied string is `configs/fish/config.fish.`
The results of "bind | grep paste" are listed below.

```
bind --preset \cv fish_clipboard_paste
bind --preset -m paste \e\[200\~ __fish_start_bracketed_paste
bind --preset -M insert -m paste \e\[200\~ __fish_start_bracketed_paste
bind --preset -M paste \e\[201\~ __fish_stop_bracketed_paste
bind --preset -M paste '' self-insert
bind --preset -M paste \r commandline\ -i\ \\n
bind --preset -M paste \' __fish_commandline_insert_escaped\ \\\'\ \$__fish_paste_quoted
bind --preset -M paste \\ __fish_commandline_insert_escaped\ \\\\\ \$__fish_paste_quoted
bind --preset -M paste ' ' 'if set -q __fish_paste_quoted[1]; or string length -q -- (commandline -c); commandline -i " "; end'
```

**Comment by faho** [comment]
Those are the correct bindings, that's the string I assumed.

What terminal are you using? It appears to be broken.

**Comment by hotoolong** [comment]
I use iTerm2.
I had a similar problem when I checked with Hyper.

**Comment by faho** [comment]
>echo $TERM is screen-256color

So you are using *screen* or *tmux* inside of iTerm2/Hyper?

**Comment by hotoolong** [comment]
Earlier, I tried it without using tmux and had a similar problem.

I rebuilt the user separately and reinstalled fish on my Mac using homebrew, as it was affected by the plugin.

The environment settings are as follows.

Fish version: `3.1.0_1`
$TERM: `xterm-256color`
uname -a: `Darwin hotoolong.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64`
bind --key | grep paste:
```
bind --preset \cv fish_clipboard_paste
bind --preset -m paste \e\[200\~ __fish_start_bracketed_paste
bind --preset -M paste \e\[201\~ __fish_stop_bracketed_paste
bind --preset -M paste '' self-insert
bind --preset -M paste \r commandline\ -i\ \\n
bind --preset -M paste \' __fish_commandline_insert_escaped\ \\\'\ \$__fish_paste_quoted
bind --preset -M paste \\ __fish_commandline_insert_escaped\ \\\\\ \$__fish_paste_quoted
bind --preset -M paste ' ' 'if set -q __f
ish_paste_quoted[1]; or string length -q -- (commandline -c); commandline -i " "; end'
bind --preset \e\ ep fish_clipboard_paste
```
The above was a little different from the results I had previously pasted.

In the config file, I only set the following

```
bind \e\] nextd-or-forward-word
```

In this case, we had a similar problem.

**Comment by faho** [comment]
There is one other possiblity. Please check that you have actually bound

```fish
bind \e\] nextd-or-forward-word
```

and not

```fish
bind \e\[ nextd-or-forward-word
```

Because `\e\[` is a prefix of ` \e\[200\~`, in which case it would be executed first and the `200~` would be left over as normal, meaning it would be inserted into the commandline.

(solving this would require forbidding prefixes of already bound sequences to be bound, or to generally run a timeout there like we do for telling alt from escape)

**Comment by hotoolong** [comment]
I'm really sorry.
This is wrong.
Correctly, it's [, not [.

```
bind \e\[ nextd-or-forward-word
```
The paste is broken only with the above settings.

**Comment by faho** [comment]
Yeah, that setting is a horrible idea, and the right thing for us to do would be to forbid it.

It is *the* most common prefix for escape sequences, known as  CSI, or "Control Sequence Introducer".

**Comment by hotoolong** [comment]
Yes, that's right.
I'll give up binding on that key.
Thank you so much for sharing this with us.

**Comment by hotoolong** [comment]
Yes, that's right.
Incidentally, is it possible to do this with hex code?

```
$ fish_key_reader
Press a key

              hex:   1B  char: \c[  (or \e)
(  0.082 ms)  hex:   5B  char: [
bind \e\[ 'do something'
```
The hex code is also displayed when you check with fish_key_reader.

**Comment by zanchey** [comment]
You can do `bind \x1b\x5b` but it has exactly the same effect.

**Comment by hotoolong** [comment]
```
bind \x1b\x5b prevd-or-backward-word
```
I was able to do the same thing with this setting, but the paste was broken.

Check the bindings
```
bind \e\[ prevd-or-backward-word
```
It seems to be replaced internally even if you set it with Hex code.

**Comment by zanchey** [comment]
Yes, that's because it's the same, and the bind output will always use the classic style.

**Comment by zanchey** [comment]
Sounds like this is sorted.
