### ISSUE TITLE
Docs on command substitution and string split

### ISSUE THREAD

**Issue by jneem** [fish-shell/fish-shell#6836]
I'm using fish version 3.1.0.

In copy-pasting some commands involving pkg-config, I ran into the command-substitution issue mentioned [in the tutorial](https://fishshell.com/docs/current/tutorial.html#command-substitutions). My issue is that the suggested resolution there didn't work for me, because pkg-config (on my system, at least, with pkg-config 1.6.3) outputs a trailing space. In particular, `pkg-config --libs gstreamer-1.0 | string split " "` outputs

```
-lgstreamer-1.0
-lgobject-2.0
-lglib-2.0

```

(note the trailing blank line). This means that commands like

```
gcc basic-tutorial-1.c -o basic-tutorial-1 (pkg-config --cflags --libs gstreamer-1.0 | string split " ")
```

fail with `gcc: error: : No such file or directory`, because gcc tries to open a file named "".

I worked around this using `tr -s ' ' \n` instead of `string split`, and I think that this (or something equivalent) should be the solution mentioned in the tutorial.

**Comment by krobelus** [comment]
This seems really strange of pkg-config.

Anyway, the equivalent here to `tr -s ' ' '\n'` is `string split -n ' '`.

Alternatively you can slice away the last element in the list.
`gcc (pkg-config --cflags --libs gstreamer-1.0 | string split " ")[1..-2]`

or, in future fish 3.2.0
`gcc (pkg-config --cflags --libs gstreamer-1.0 | string split " ")[..-2]`

**Comment by jneem** [comment]
Thanks! I agree that it's strange behavior, but what can you do... I've made a PR for suggesting `string split -n` in the tutorial.

**Comment by krobelus** [comment]
Cherry-picked to master as 3cf1de1b7, thanks!

**Comment by zanchey** [comment]
So, this only occurs when `pkg-config` is actually [pkgconf](https://github.com/pkgconf/pkgconf) and not [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/). The latter calls `g_strstrip` on the final output. The doc fix is fine and pkgconf constructs its strings by char pointer manipulation so probably not an easy fix.
