### ISSUE TITLE
Preview file shortcut

### ISSUE THREAD

**Issue by exploide** [fish-shell/fish-shell#6838]
Sometimes, when I type a command like `mycmd --my-file ./here/comes/some/file.txt` I start wondering whether I actually selected the correct file or if I mixed something up. Then I copy the file path, open a new terminal tab and open the file in `less`.

fish has some cool shortcuts, for example Alt+H to open the man page of the current command.

What about a shortcut for opening the current file in a pager? I think it could be useful.

I'm thinking about what shortcut would be appropriate. Some of them are already occupied for other actions. So I'm leaning towards Alt+O as in Open.

What do you think?

**Comment by krobelus** [comment]
Good idea, seems convenient.

I'm playing around with this. It also works nicely when fish's pager is active.
`bind \eo 'eval less -I (commandline -ct); commandline -f repaint'`

We could also overload the Alt+L binding, to show the current token in a pager if it is a file.

**Comment by exploide** [comment]
@krobelus are you working on it? Otherwise I would give it a try.

But it should be decided whether enhancing Alt+L or introducing a new function for Alt+O is preferred. I think enhancing  `__fish_list_current_token` with file support is great but would incidentally remove 

https://github.com/fish-shell/fish-shell/blob/a29bc127cec6a911fcd5919e0c19dcc14b0ef360/share/functions/__fish_list_current_token.fish#L10-L12

which strips the filename to list the parent directory. That would obviously preview the file then. But I'm not sure if this is a no-go since I cannot imagine this is heavily used.

**Comment by krobelus** [comment]
> Otherwise I would give it a try.

Sure, go for it.

I think a new binding on Alt+O is fine.
