### ISSUE TITLE
Fish not autocompleting man page names

### ISSUE THREAD

**Issue by xylix** [fish-shell/fish-shell#6840]
fish, version 3.1.0

iterm2, macOS

Darwin forkbomb2.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

  sh -c 'env HOME=$(mktemp -d) fish'
Did not affect behaviour

Writing `man <partial program name>` for example `man gi` and pressing tab doesn't tab complete the program (here git, or with `man git-subm` `git-submodule`).

`man -` <tab> does offer the possible flags correctly.

Other commands (other than man) have working autocompletions. For example `ls` and `npm`

I ran fish_update_completions when trying to fix this, and it didn't change anything.

This reproduces in the clean fish shell so it shouldn't be related to my configuration. Is this

**Comment by faho** [comment]
Yeah, this is on purpose. The man completions have been disabled on macOS 10.15 because the man system is *broken*.

See #6270.
