### ISSUE TITLE
Feature Request: varsave

### ISSUE THREAD

**Issue by xylix** [fish-shell/fish-shell#6843]
```
fish, version 3.1.0
Darwin forkbomb2.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
```

Funced and funcsave are very handy and intuitive for creating and saving function definitions. Is there a reason vared doesn't have similar `varsave` pair to save a variable definition into a file? I would very much find this feature useful.

**Comment by krobelus** [comment]
You can do `set -U x $x`. A `varsave` doing the same thing would obscure the fact that this is a universal variable, potentially shadowed by globals or locals.

**Comment by xylix** [comment]
Hm yeah thanks, I didn't know about set -U. I'll just define a function for doing the set command like so `function varsave set -U $argv[1] $$argv[1] end` in my fish.config and that fixes my use case.

**Comment by zanchey** [comment]
Yeah, I think the existing interface is right for now.
