### ISSUE TITLE
[CPU usage] High cpu usage when idle

### ISSUE THREAD

**Issue by t-smirnov** [fish-shell/fish-shell#6847]
**Version**: fish, version 3.1.0
**OS**: Darwin Tims-MacBook-Pro.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64
**Term**: xterm-256color

Activity monitor showed 988 percent

**Comment by zanchey** [comment]
Could you try taking a sample from another terminal? `sample [PID] 5 -file myfishsample.txt` will generate a profile over 5 seconds in myfishsample.txt, which can then be inspected and upload.

Also it would be interesting to know if it reproduces with a clean config; `exec env HOME=$(mktemp -d) fish` or similar should do the trick.

**Comment by ridiculousfish** [comment]
The fact that CPU usage is over 100% implies there are multiple threads; probably this was fixed by e334becefbf221db19e8e4e4c550da036db3b61b

**Comment by faho** [comment]
Closing for lack of information. If you ever get around to it we can reopen!
