### ISSUE TITLE
Feature request: Ability to set key bindings for CMD/WIN key

### ISSUE THREAD

**Issue by muqsitnawaz** [fish-shell/fish-shell#6852]
I'm using fish version 2.7.1 on both macOS (Catalina 10.15.3) and ubuntu (18.04). For a long time now, I've wanted to assign actions such as `__fish_cancel_commandline` to key bindings such as CMD+l instead of CTRL+l but `fish_key_reader` doesn't seem to recognize the CMD key. I can only assign shortcuts for CTRL and ALT keys, and this holds true for `ubuntu 18.04` as well.

It'd be nice to be able to use other keys for defining `key_bindings` beside CTRL and ALT keys.

**Comment by faho** [comment]
Oh, you *can*!

The reason being that your terminal sends these as escape sequences. You just need to find the right one, and for that you can just use `fish_key_reader`.

In my case:

```fish
> fish_key_reader # then press win+i
Press a key

              hex:   18  char: \cX
(  0.088 ms)  hex:   40  char: @
(  0.090 ms)  hex:   73  char: s
(  0.113 ms)  hex:   69  char: i
bind \cX@si 'do something'
```

So the sequence for win+i is `\cX@si`, so if I do `bind \cX@si 'echo foo'` and press win+i it'll say "foo".

I don't think there is sufficient standardization here to add a named key to our binding system - in particular I don't think there's anything in terminfo.

>It'd be nice to be able to use other keys for defining key_bindings beside CTRL and ALT keys.

In a terminal, there is nothing else. Everything that's not just a normal "inserts this thing" key (a letter, number, punctuation) is expressed via escape sequences and control characters. The up-arrow is typically `\e\[A` - an escape key, the "[" and an "A".

Alt+e is escape+e.

**Comment by ridiculousfish** [comment]
Also your terminal emulator may have a preference to send these keys to the tty, depending on what your terminal emulator is.

**Comment by muqsitnawaz** [comment]
I tried `fish_key_reader` on macOS, but on pressing `CMD+<any_key>` it doesn't output anything. I'm using iTerm2 as my terminal emulator.

**Comment by faho** [comment]
That means your terminal doesn't pass these keys on, so there's nothing we can do. Sorry!

**Comment by zanchey** [comment]
In iTerm 2, at least, you can add a key combination that sends whatever you want:

https://www.iterm2.com/documentation-preferences-profiles-keys.html

https://www.iterm2.com/documentation-preferences-keys.html can also be used to set the behaviour of the command key, if that's preferred.
