### ISSUE TITLE
How to suppress "No matches for wildcard"?

### ISSUE THREAD

**Issue by anki-code** [fish-shell/fish-shell#6858]
Hi! I've read answers about "No matches for wildcard" and globbing but have no answer on my question.

I have the code like this:
```
for pluginrc_file in (find /../../../plugins/*-fish-*/build -type f -name '*pluginrc.fish' -printf '%f\t%p\n' 2>/dev/null | sort -k1 | cut -f2)

  echo 123

end
```
And when files not found I getting the annoying message "No matches for wildcard" instead of just not run the loop.

Please help to suppress this messages. 

Thanks!

**Comment by faho** [comment]
This error will be printed for globs used with every command, except for `for`, `set` or `count`, in which case the glob will just expand to nothing.

In this case you're using it with `find`, so the error is printed. If you wanted to let it expand to nothing, you would use a variable:

```fish
set -l dirs /../../../plugins/*-fish-*/build
for pluginrc_file in (find $dirs -type f -name '*pluginrc.fish' -printf '%f\t%p\n' 2>/dev/null | sort -k1 | cut -f2)
```

---

**HOWEVER**: If `find` isn't given a directory to look in, it defaults to ".". So if that expands to nothing, find will search for files named `*pluginrc.fish` in the current directory!

So the for-loop might still *run*, only the `find` would have looked in places you didn't predict.

That's basically exactly why this is an error - commands do weird things if the arguments aren't as expected.


The brute force solution then is to check if the variable contains anything:

```fish
set -l dirs /../../../plugins/*-fish-*/build
if set -q dirs[1]
    for pluginrc_file in (find $dirs -type f -name '*pluginrc.fish' -printf '%f\t%p\n' 2>/dev/null | sort -k1 | cut -f2)
```

**Comment by anki-code** [comment]
@faho you're the superhero! It works! Thanks!
