### ISSUE TITLE
<TAB> completion does not work if the first attempt failed

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#6863]
Using https://github.com/fish-shell/fish-shell/commit/866d506d110f2bf7c69a3c1ddd3005191ddbe80e

Let's say I'm waiting for an external process to create a file (e.g. `/var/log/foo.log`) but I don't know whether the file has been created yet, I might type something like:

```
$ less /var/log/fo<TAB>
```

If the file has *not* yet been created, I get the equivalent of `printf '\a'`, as expected, and my terminal flashes - no problem here.

However, if I hit `<TAB>` again to check if the file has been created since my last `<TAB>`, _nothing happens_. No screen flash, nothing, as if tab-completion has been temporarily disabled.

In order to get around this, it is necessary to modify the commandline in some way in order to "re-enable" tab-completion, e.g. adding the next character or deleting the current character and hitting `<TAB>` again, but it would be great if I didn't have to, and instead simply had to hit `<TAB>` again without having to fudge the commandline first.

**Comment by ridiculousfish** [comment]
Just a stupid bug - [boolean with the wrong sense](https://github.com/fish-shell/fish-shell/blob/77fb54fa9930745b8676ae3a6bc5eab11a2b389b/src/reader.cpp#L2738).

**Comment by ridiculousfish** [comment]
Great bug, thank you for filing!

**Comment by ridiculousfish** [comment]
My fix seems to have broken other scenarios, it needs more work.

**Comment by krobelus** [comment]
I have a fix that makes fish always recompute completions when hitting tab if there are no completions yet, see below. 
However, when pressing and holding tab for some time on a command line with no (file) completions, fish will block because of all those queued completion requests. Cancelling with Control+C works, but after doing so, completion autoloading was broken on some of my attempts. Admittedly, this is an extreme example but maybe we should prevent this blocking behavior for example by limiting the number of consecutive complete commands.

```diff
diff --git a/src/reader.cpp b/src/reader.cpp
index f607cbff4..00fc9da83 100644
--- a/src/reader.cpp
+++ b/src/reader.cpp
@@ -2676,7 +2676,7 @@ void reader_data_t::handle_readline_command(readline_cmd_t c, readline_loop_stat
             // Use the command line only; it doesn't make sense to complete in any other line.
             editable_line_t *el = &command_line;
             if (is_navigating_pager_contents() ||
-                (!rls.complete_did_insert && rls.last_cmd == rl::complete)) {
+                (!rls.comp.empty() && !rls.complete_did_insert && rls.last_cmd == rl::complete)) {
                 // The user typed complete more than once in a row. If we are not yet fully
                 // disclosed, then become so; otherwise cycle through our available completions.
                 if (current_page_rendering.remaining_to_disclose > 0) {
```

**Comment by zx8** [comment]
@krobelus Any chance of getting that merged in, with potentially a follow-up to throttle input in future?

**Comment by krobelus** [comment]
@zx8 Yeah, I think this is unlikely to cause any real problem, and Control+C still works. Thanks for the reminder!
