### ISSUE TITLE
Exported variable with base64 string misses `=` 

### ISSUE THREAD

**Issue by aartek** [fish-shell/fish-shell#6870]
Hi,

```
fish --version
fish, version 3.1.0
```

System: `OSX Catalina 10.15.3`

**Issue**:

I have an issue with base64 encoding.

```
> echo "test" | base64
dGVzdAo=
```

but
```
> export x=(echo "test" | base64)
> echo $x
dGVzdAo
```
`=` disappears. It's problematic when I need to set variable with base64 certificate, and it's base64ed version ends with `==`. 

Seems to work fine in fish 3.0.2

**Comment by faho** [comment]
This works for me. `export` is a compatibility function, so it could be overridden. What does `type export` say?

The "workaround" is obviously just to use the actual fish-native `set`, like 

```fish
set -gx x (echo test | base64)
```

**Comment by sjuxax** [comment]
For what it's worth, I can't replicate this here (but I'm on Catalina 10.5.4).

```
jeff@mbp ~> fish --version
fish, version 3.1.0
jeff@mbp ~> echo $version
3.1.0
jeff@mbp ~> export x=(echo "test" | base64)
jeff@mbp ~> echo $x
dGVzdAo=
jeff@mbp ~> type export
export is a function with definition
# Defined in /usr/local/Cellar/fish/3.1.0_1/share/fish/functions/export.fish @ line 1
function export --description 'Set env variable. Alias for `set -gx` for bash compatibility.'
[snipped]
end
jeff@mbp ~> sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.4
BuildVersion:   19E266
```

**Comment by aartek** [comment]
```
> type export
export is a function with definition
# Defined in /Users/xxxx/.config/fish/functions/export.fish @ line 1
function export
  set arr (echo $argv|tr = \n)
  set -gx $arr[1] $arr[2]
end
```

**Comment by faho** [comment]
Well, you've overridden the export function. Delete that file and it should use the proper one again.

**Comment by sjuxax** [comment]
Looks like a quick override from before fish provided a shim for `export` -- and it makes sense that it eats `=`, because it calls `tr` to translate `=` into a newline. 😉 Move it out of the way and you should be able to use the built-in function.

**Comment by aartek** [comment]
Ok.. I copied `~/.config/fish` from my old mac.
Removing function solved the issue. Thanks for help!
