### ISSUE TITLE
fish-shell generates error in nvim checkhealth - $TERM differs from the tmux `default-terminal`

### ISSUE THREAD

**Issue by EdmundsEcho** [fish-shell/fish-shell#6871]
Please tell us which fish version you are using by executing the following:

3.0.2

Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

Darwin xx-Mac.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64

xterm-256color

Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:

  sh -c 'env HOME=$(mktemp -d) fish'

it generates a similar error:
$TERM should be "screen-256color" or "tmux-256color" in tmux.

... my current setting is xterm-256color
... when I change it to screen-256color the error message goes away

To reproduce:
1. in nvim: `set shell=fish` (or just leave it unset and run nvim from fish)
2. run `checkhealth` from within nvim
3. read the report - ERROR...

Changing from xterm to screen eliminates the error.

**Comment by faho** [comment]
Okay, then don't set $TERM to xterm?

Fish doesn't ever touch it, so if this errors it's because of something either you or some bit in your configuration did.

I recommend grepping your config and checking `set -S TERM` to figure out if it's a universal variable.

**Comment by faho** [comment]
I'm assuming the question has been answered. If you have anything else, feel free to ask and we'll reopen!
