### ISSUE TITLE
Question: Is there any built-in functionality to create history-like menu's for other purposes?

### ISSUE THREAD

**Issue by OakNinja** [fish-shell/fish-shell#6883]
Hi,
Happy fish user here 👋

I've created a simple tool for Makefiles called [MakeMe](https://github.com/OakNinja/makeme), which still is in early development but works fairly well. I got my inspiration from how [jethrokuan/fzf](https://github.com/jethrokuan/fzf) history search works, and right now I'm exploring the possibility of creating a fish plugin.

I've skimmed documentation, code, and other repos like the [fish-menu](https://github.com/fishpkg/fish-menu) with some success. However, implementing type-ahead, styling etc will take up a fair amount of time, and while that's not a problem per se, It would be even nicer if I could build up a select menu structure using the history command but with my own input. 

So, my question is rather open-ended: While not new to fish, I'm new to creating my own fish functionality, and would really appreciate some pointers. I'm not afraid of spending quite an amount of time on this, but I'd like to spend it on the right things :)

**Comment by OakNinja** [comment]
Sometimes writing a question pushes you in the right direction. I just realized how to do this. Thanks :)

**Comment by zanchey** [comment]
See also #4036, #2805.

**Comment by OakNinja** [comment]
> See also #4036, #2805.

Thanks. I’ll post my solution here when I’m done, it might help someone else in the future.


![](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

**Comment by OakNinja** [comment]
Ok, not that polished yet, still learning, but I've uploaded my plugin here: 
https://github.com/OakNinja/MakeMeFish
It's basically just piping a bunch of strings separated by newlines into jethrokuan/fzf `__fishcmd`, piggy backing on junegunn's and jethrokuan's excellent plugins.

I'm really pleased with the result so far, and I look forward to polish this up and getting better at fish scripting. :)
