### ISSUE TITLE
Add tab completion for the iwctl command used to interact with IWD

### ISSUE THREAD

**Issue by ericonr** [fish-shell/fish-shell#6884]
[IWD](https://iwd.wiki.kernel.org/start) is a "new" wireless daemon that intends to supersede wpa_supplicant,  by being both faster and having simpler configuration. It has a pretty simple CLI, called iwctl, which has a readline interface, but can also take commands directly. It would be great to be able to use those commands with tab completion inside fish.

I am interested in implementing those completions, just want to be sure it's ok and leave this issue open if anyone wants to comment anything.

**Comment by faho** [comment]
Sure, go for it!

**Comment by mizzunet** [comment]
@ericonr Do you have it?

**Comment by ModProg** [comment]
working on this, will revive the pr in the comming days.

**Comment by ModProg** [comment]
Done: https://github.com/fish-shell/fish-shell/pull/9932
