### ISSUE TITLE
read with flag  `--shell`

### ISSUE THREAD

**Issue by charles-paperman** [fish-shell/fish-shell#6886]
Informations on the system:

* fish version (3.0.2), 
* `uname -a`: `Linux legros 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux`
* `echo $TERM`: `xterm-256color`
* On Debian 10.3

The following code:
```
 while read -l --shell entry                                                                                                                                                          
    echo "pass"
end
``` 
Return an error if the user input something with matching parenthesis (e.g `foo(bar)`):
The error message: `fish: Command substitutions not allowed`. 
The loop continue, so the error does not interrupt the while loop. 

This behaviour is not documented in the doc page of `read`. I suspect it is not the intended one.

**Comment by zanchey** [comment]
Having had a chance to think about this and test it, this is because command substitutions can't be used in the command position - so this is actually invalid syntax if used as a shell command-line.

For example:

```fish
> fish -c 'echo(echo)'
fish: Command substitutions not allowed
echo(echo)
    ^
```

Since #154 was fixed (fish 3.0+) you can use variables, but not command substitutions, in the command position. I thought we had a discussion about why somewhere but I can't find it.

**Comment by charles-paperman** [comment]
I am puzzle by the meaning of the --shell option then. 

It has to perform syntax check to do the coloration and syntax highlight but if the syntax is incorrect it block the read completly. 
Actually, if we perform a simple 
```
read --shell 
```
Then `foo(bar)` is not exiting and it display the prompt again.

**Comment by zanchey** [comment]
If it helps to understand, `read --shell` is implemented to support the `funced` tool.

The following produces an error for me:

```fish
> read --shell
read> foo(bar)
fish: Command substitutions not allowed
foo(bar)
   ^
```

**Comment by charles-paperman** [comment]
It produces the error message but without exitint the readline prompt, so it keeps the control. Which is somehow annoying to me. I guess I should not use the option and
find something more flexible than read for my needs :).

**Comment by faho** [comment]
So what are your needs? Why are you using `--shell`?

**Comment by charles-paperman** [comment]
I am trying developped an interactive console. I am using fish because it is amazingly convenient for that. The `read` function is great but I would like to be able to customized it a bit more (custom auto-completion, and highlight syntax). 

The default --shell option could have been enough with adequate hack of the env variable. However I can't use it with string like `foo(bar)` which I heavily need.

It is also a way for me to learn more on fish (that I use daily without even thinking of it :)). 

My project is here if you want more details https://gitlab.inria.fr/cpaperma/interactivec

**Comment by ridiculousfish** [comment]
This is pretty wild!

**Comment by zanchey** [comment]
I keep coming back to this but I don't think we're going to support changes to the parser in this manner.

**Comment by charles-paperman** [comment]
Understood, thank you for your time on this subject.
