### ISSUE TITLE
Command substitutions is getting split by spaces, why?

### ISSUE THREAD

**Issue by dvaerum** [fish-shell/fish-shell#6888]
> Unlike other shells, fish does not split command substitutions on any whitespace (like spaces or tabs), only newlines. This can be an issue with commands like pkg-config that print what is meant to be multiple arguments on a single line. To split it on spaces too, use string split
**ref:** https://fishshell.com/docs/current/tutorial.html#command-substitutions

According to the documentation if I run the following command `./print_args.sh (echo do not split this line)` I should get the output `'do not split this line'` but instead I get
```
'do'
'not'
'split'
'this'
'line'
```
Does anyone know what I am doing wrong or I misunderstanding something? I really cannot figure this one out

**print_args.sh**
```bash
#!/usr/bin/env bash

for i in $*; do
  echo "'$i'"
done
```

**Info**
fish version: 3.10
System: Mac
uname -a: `Darwin someone.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64`
tried without third-party customizations: yes

**Comment by krobelus** [comment]
Hi, you need to use `"$@"` here instead of `$*`. A quoted `"$*"` would join all arguments in one string, without quotes bash splits by spaces.
In my experience,  `"$@"`  is almost always what you want.

**Comment by faho** [comment]
In other words: *bash* is doing the splitting. Fish is passing the arguments in split by newlines (in this case that means it's not split), and then bash comes in and breaks it up.

**Comment by dvaerum** [comment]
Yes, that work to change from `$*` to `"$@"`
```
> ~/Projects ./print_args.sh (echo kldmaks da skldakls da) dasdas asdasdasd asdasd
'kldmaks da skldakls da'
'dasdas'
'asdasdasd'
'asdasd'
```

Unfortunately that doesn't fix my original problem which was it Ansible (probably should have mentioned), I want to be able to do something like this and get the output
```fish
ansible -m debug -a msg=(echo testererere dasdas asda sdas d) -c local localhost
localhost | SUCCESS => {
    "msg": "testererere dasdas asda sdas d"
}
```
but that doesn't work, I assume it must have something to do with Ansible parser. So my workaround ends up being something like this.
```
set test (echo testererere dasdas asda sdas d); ansible -m debug -a "msg='$test'" -c local localhost
```
but when I just realized the solution, which was also mention in the documentation I linked to
```
ansible -m debug -a "msg='"(echo testererere dasdas asda sdas d)"'" -c local localhost
```
**So conclusion, I was stupid but learned something new 😅**
Many thanks for the help 👍 😄
