### ISSUE TITLE
&> redirection

### ISSUE THREAD

**Issue by alireza** [fish-shell/fish-shell#689]
Is there any plan to support bash's redirect stdio and stderr operator? (&>)

Basically

``` shell
fish$ ls &>f.txt
```

would be like

``` shell
fish$ ls >f.txt ^&1
```

Implementing this helps with programs that use the current shell to run things. For instance, I've seen a few vim scripts that rely on this redirection and won't work when running vim inside fish.

**Comment by krader1961** [comment]
Duplicate of issue #110.
