### ISSUE TITLE
read history

### ISSUE THREAD

**Issue by charles-paperman** [fish-shell/fish-shell#6892]
Informations on the system:

    fish version (3.0.2),
    uname -a: Linux legros 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux
    echo $TERM: xterm-256color
    On Debian 10.3

The history of read does not behave like the history of the shell. By using up arrows to get to the last line, we actually get the one before.

@krobelus suggest: "The last line is supposed to be provided by the autosuggestion which read doesn't have".

**Comment by zanchey** [comment]
Is this actually a regression? From which version? (Useful for release notes)

**Comment by krobelus** [comment]
My apologies, I have been neglecting the changelog.
I believe (but haven't checked) that this was introduced in `3.0.2-1251-g51fcb79d9`, so the bug should only be present in 3.1.0.
