### ISSUE TITLE
Provide a Scoop / Chocolatey vresion

### ISSUE THREAD

**Issue by trajano** [fish-shell/fish-shell#6894]
Can you provide a package for Scoop and Chocolately so we can easily install it in Windows?

**Comment by ammgws** [comment]
If you have WSL then for example with the Ubuntu one, you can just add the ppa and install fish there.

Otherwise you can install cygwin with scoop and install fish there.

**Comment by trajano** [comment]
Cygwin is quite large,  I was hoping for the MSYS2 one.  I am thinking there should be a binary that is already built with the library that we can download.

**Comment by ammgws** [comment]
Is there an advantage of doing that versus:

Scoop install msys2
Then Pacman -Syu fish

?

**Comment by trajano** [comment]
Much more easier if we had `scoop install fish`

**Comment by ammgws** [comment]
Oh ok. Do you know of any other projects such as zsh or whatever that provide such a package, so it can be used as reference?

**Comment by zanchey** [comment]
Essentially we're happy to do what is needed to support more platforms but if it requires binary builds that aren't supported by the [Open Build Service](https://build.opensuse.org/), I'd expect someone else to provide them.

Scoop looks like it can just draw the packages from MSYS2, for which there is already a [package for fish](https://packages.msys2.org/base/fish), so probably someone with the ability to test the package can write the manifest and submit it [upstream](https://github.com/ScoopInstaller/Main).

Chocolatey's "how to make a package" course is, uh, 1.5 hours. I'll defer to someone else on that.

**Comment by trajano** [comment]
I think that would be appveyor or travis.  Which will then link up with github and publish the compiled binaries into the "releases" link for Github.  Once it is there, someone can just pick it up.

Don't do Chocolatey (it's more of a pain :) ) but I put it here for completeness as I didn't want to create two requests that are too similar.

The build ideally to keep things simple should just statically link the libs so it's a single large binary that makes it easy to run for people.

**Comment by trajano** [comment]
@ammgws just tried the msys2 install.  I think it just borked my scoop installation.

```
scoop install msys2
msys2
pacman -Syu fish with msys2
```

Anyway restarting my shell and it can't find `fish` anyway.

**Comment by faho** [comment]
Alright, I don't believe we want to do anything here. We'll leave it up to whoever wants to maintain a scoop/chocolatey version.
