### ISSUE TITLE
complete: maximum recursion depth reached

### ISSUE THREAD

**Issue by birktj** [fish-shell/fish-shell#6899]
When using the `ssh` or `scp` with tab completion I get many lines of:
```
complete: maximum recursion depth reached
```

The issue does not appear when running fish from a clean home directory and also
not when copying all the files from `~/.config/fish` to the clean home directory. 

## Environment
- os: Arch Linux
- terminal: alacritty
- fish version: `fish, version 3.1.0`

**Comment by faho** [comment]
Do you have any alias or function related to ssh or scp?

**Comment by faho** [comment]
Yeah:

```fish
alias ssh "env TERM=screen-256color ssh"
```

That'll create a function called "ssh", which will wrap "env", but env will tell the completion system to complete like its subcommand, so it will try to complete ssh, which will then complete like env....

The simple workaround is to actually make a proper function,  like

```fish
function ssh
    TERM=screen-256color command ssh $argv
end
```

I'm pretty sure we already have an issue open about that, if I can only find it...

**Comment by birktj** [comment]
Thanks!
