### ISSUE TITLE
 `string split --fields` behaviour with multiple args

### ISSUE THREAD

**Issue by ammgws** [fish-shell/fish-shell#6900]
Regarding the new `--fields` flag that was added in #6770:
> I think it's surprising that `string split` only accepts one argument:
> I would expect `string split -f1 ' ' 'a b' 'c d'` to print `a` and `c`.
> 
> Edit: it uses all arguments, but keeps the splits between them: `string split -f1-4 'x' 'axb' 'cxd'` prints all of `abcd`.

_Originally posted by @krobelus in https://github.com/fish-shell/fish-shell/pull/6896_

Due to the aforementioned behaviour, it has to be used like this:
>printf "package1 description1\npackage2 description2\n" | cut -d' ' -f1
package1
package2

>printf "package1 description1\npackage2 description2\n" | while read -l line
    string split -f1 ' ' -- $line
 end
package1
package2

Otherwise it would not return all splits (as one would expect?):
>printf "package1 description1\npackage2 description2\n" | string split -f1 ' '
package1

What are people's thoughts on how it should behave?

**Comment by zanchey** [comment]
`string replace` behaves in line with your suggested changes:

```fish
> printf 'a a\n' | string replace a b
b a
> printf 'a\na\n' | string replace a b
b
b
```

**Comment by krobelus** [comment]
Yes, this should be changed to be consistent with other `string` subcommands:

```fish
string $subcommand $argv
```

is generally equivalent to

```fish
for arg in $argv
  string $subcommand $arg
end
```

except for `string collect`, but that exists precisely to not split on newlines.
