### ISSUE TITLE
is support of dot env files in the roadmap?

### ISSUE THREAD

**Issue by shouze** [fish-shell/fish-shell#6901]
I'm pretty sure this issue has already been discussed but [I didn't find any related issue](https://github.com/fish-shell/fish-shell/issues?page=14&q=is%3Aissue+sort%3Aupdated-desc+env+file+is%3Aclosed).

Currently I'm able to write this kind of `.env` file:
```dotenv
set -Ux SOME_VAR some_value
```
And source it like this:
```fish
source .env
```

But... this is not very interoperable. I would prefer from far using the conventional form of dotenv files:
```
SOME_VAR=some_value
```

It remains of course the question of the scope. To me, flags should be `-Ux` in this precise case but this is of course subject of debate.

Anyway this should imply that the fish source builtin should be able to work with 2 parsing modes. To avoid over engineering on that, I guess it could be a good idea to put a special pragma instruction on the first line of the .env file to explicit the parsing mode. Something like that:
```dotenv
#pragma: fish.source.interoperable_format
SOME_VAR=some_value
```

We can even imagine to configure set flags with this pragma directive. What do you think?

**Comment by faho** [comment]
It is not, and it won't be.

The reason being that it's neither in super widespread use nor super useful, we don't want fish going around sourcing random builtins or add multiple ways to define variables.

Also it's quite simple to implement yourself. A rough sketch:

```fish
function readenv --on-variable PWD
    if test -r .env
        while read -l line
            set -l kv (string split -m 1 = -- $line)
            set -gx $kv # this will set the variable named by $kv[1] to the rest of $kv
        end
   end
end
```

Note also that setting a *universal* variable is basically wrong by definition here - universal variables are shared by all of your running fishes, but $PWD *isn't*. You want a global variable.

**Comment by faho** [comment]
Note also that [direnv](https://direnv.net/) has support for fish.

**Comment by shouze** [comment]
Thank you, closing this one.

**Comment by shouze** [comment]
@faho BTW in my specific case I want a universal variable because I set it in a Makefile and I want that this variable to be propagated to my parent fish process.

But... yes another way to do is to use direnv, it's more like dependency inversion and far more scoped in the right way, thank you for your time and precious advices.

**Comment by vagoff** [comment]
```
function parse-env
    for line in (cat $argv[1])
        set line (string trim $line)
        if test -z $line
        or string match -q "#*" $line
            continue
        end
        set name_value (string split -m 1 = $line)
        set name (string trim $name_value[1])
        set value (string trim $name_value[2])
        #echo "[line=$line,name_value=$name_value,name=$name,value=$value]"
        if string match -q '"*"' $value
        or string match -q "'*'" $value
            set value (string sub -s 2 -e -1 $value)
        end
        set sub1 $value
        if string match -qr '[$][{][A-Za-z_][A-Za-z_0-9]*[}]' $sub1
            set sub1 (string replace '[$][{]([A-Za-z_][A-Za-z_0-9]*)[}]' '$$$1' $sub1)
        end
        if string match -qr '[$][A-Za-z_][A-Za-z_0-9]*' $sub1
            set sub2 (eval "echo $value")
        else
            set sub2 '<none>'
        end
        echo "[name=$name,value=$value,sub1=$sub1,sub2=$sub2]"
        set -gx $name $value
    end
end

```

**Comment by HaukurPall** [comment]
The above code did not work for me. I'm unsure if it is due to changes in the fish shell or just bugs.

My version:
```fish
function load-dot-env
    for line in (cat $argv[1])
        set line (string trim $line)
        # echo line=$line
        if test -z $line
        # Skip comments
        or string match -q "#*" $line
            continue
        end
        set name_value (string split -m 1 = $line)
        set name (string trim $name_value[1])
        set value (string trim $name_value[2])
        # echo name_value=$name_value
        # echo name=$name
        # echo orig_value=$value
        # If the value is quoted, remove the quotes.
        # This is questionable since ' "often" means that the value is a string and should not be interpreted.
        # I'm simply unsure how it should be handled in '.env' files.
        if string match -q '"*"' $value
        or string match -q "'*'" $value
            set value (string sub -s 2 -e -1 $value)
            echo unquoted_value=$value
        end
        # Does the value contain a variable?
        if string match -qr '[$][{][A-Za-z_0-9]*[}]' $value
            set with_variable (string replace -r '[$][{]([A-Za-z_0-9]*)[}]' '$$$1' $value)
            # echo with_variable=$with_variable
            set value (eval "echo $with_variable")
            # If the value is empty, it means that the variable was not set before.
            # We should give a warning in that case.
            if test -z $value
                echo "Warning: unable to set $name since it contains an undefined varible: value=$with_variable"
                continue
            end
            # echo interpreted_value=$value
        end
        echo setting $name to $value
        set -gx $name $value
    end
end
```
