### ISSUE TITLE
After update to 3.1.0 /usr/local/bin has disappered from PATH. Why?

### ISSUE THREAD

**Issue by kuvaldini** [fish-shell/fish-shell#6903]
```
FISH_VERSION: 3.1.0
Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64
```
```
❯❯❯ echo $PATH
/Users/user/.cargo/bin /usr/bin /bin /usr/sbin /sbin
❯❯❯ echo $fish_user_paths
/Users/user/.cargo/bin
```
Earlier `/usr/local/bin` was in PATH and was not in fish_user_paths. 

So how can I return `/usr/local/bin` to system-wide PATH without changing fish_user_paths.

**Comment by zanchey** [comment]
I suspect you are not starting fish as a login shell - see #6594.

**Comment by kuvaldini** [comment]
@zanchey , thank you.

The answer is here https://github.com/fish-shell/fish-shell/issues/6594#issuecomment-586015504
