### ISSUE TITLE
How to set $PATH persistently for all users?

### ISSUE THREAD

**Issue by kuvaldini** [fish-shell/fish-shell#6904]
This thread https://github.com/fish-shell/fish-shell/issues/527 has exhaustive description and concrete recommendation to use `$fish_user_paths`.  

But how can I set PATH for ALL users, not the only one?

**Comment by zanchey** [comment]
You can change `$PATH` in `/etc/fish/config.fish` which is applied by all users.

On macOS, you can also use `/etc/paths` or `/etc/paths.d/`.

**Comment by kuvaldini** [comment]
Are there plans to read paths from `/etc/paths` and `/etc/paths.d` in Linux?

**Comment by zanchey** [comment]
I don't know of any Linux distributions which use that mechanism. If they did we'd certainly look at adding it. `/etc/login.defs` is probably the tool of choice on Debian, but fish doesn't need to read that - it's handled at another layer.

**Comment by kuvaldini** [comment]
> You can change $PATH in /etc/fish/config.fish which is applied by all users.

Thank you. This works fine.

**Comment by thernstig** [comment]
@kuvaldini You can read about this in the docs: https://fishshell.com/docs/current/index.html#initialization-files
