### ISSUE TITLE
Wrong hardcoded location of lsmod

### ISSUE THREAD

**Issue by FraMecca** [fish-shell/fish-shell#6912]
I can't get completion related to kernel modules:

```
# rmmod  <TAB> fish: Unknown command: /sbin/lsmod
fish: 
/sbin/lsmod | awk 'NR > 1 {print $1}'
^
in command substitution 
```
```
/bin/lsmod
```
Of course the problem disappears if I symlink lsmod to /sbin/lsmod

fish, version 3.1.0
Linux 5.6.4-gentoo SMP PREEMPT Fri Apr 17 17:33:14 CEST 2020 x86_64 Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz GenuineIntel GNU/Linux
rxvt-unicode-256color

**Comment by faho** [comment]
Blergh. Yeah, no idea why we're even hardcoding the path *at all*.

These completions haven't been touched in a while.

**Comment by FraMecca** [comment]
Thanks!
