### ISSUE TITLE
Relative path colourising broken when in 'virtual' symlink directory

### ISSUE THREAD

**Issue by OJFord** [fish-shell/fish-shell#6915]
fish v3.1.0

Fish v3 resolved #1957, such that the `pwd` is now a 'virtual' directory rather than resolving to the target directory.

However, when inside such a directory, relative paths such as `../<pwd basename>` are coloured red, as though they don't resolve and the command (such as `cd`) will fail. It doesn't, because we are in that 'virtual' directory, but the colour misleads us into thinking we're in the link's target directory instead.

**Comment by krobelus** [comment]
This only applies to the cd command. External commands use the resolved directory and the likes of `pushd` don't have cd's highlighting. Should be fixed now.
