### ISSUE TITLE
fish hangs on FreeBSD 13 after failing to reap child

### ISSUE THREAD

**Issue by asomers** [fish-shell/fish-shell#6919]
```
> fish --version
fish, version 3.1.0
> uname -a
FreeBSD fbsd-head.lauralan.noip.me 13.0-CURRENT FreeBSD 13.0-CURRENT #3 r360076M: Sat Apr 18 17:29:32 MDT 2020     somers@fbsd-head.lauralan.noip.me:/usr/obj/usr/home/somers/freebsd/base/head/amd64.amd64/sys/GENERIC  amd64
> echo $TERM
xterm-256color
```

Occasionally on FreeBSD 13-CURRENT my fish shell will hang.  This usually happens either immediately after executing a command, or after pressing CTRL-C to clear the buffer.  `ps` shows that fish has a zombie child.  `procstat` sometimes shows one thread, and sometimes more than one.  There's usually one thread blocked in `sys_read`.  For example:
```
> ps -axwwd | grep -A1 fish
 1861  1  Ss     0:41.12 | |   `-- -fish (fish)
16704  1  Z+     0:00.01 | |     `-- <defunct>
> procstat -kk 1861
  PID    TID COMM                TDNAME              KSTACK                       
 1861 100106 fish                -                   mi_switch+0x155 sleepq_switch+0x11a sleepq_catch_signals+0x3f2 sleepq_wait_sig+0x9 _sleep+0x2c3 pipe_read+0x42b dofileread+0x81 sys_read+0xc0 amd64_syscall+0x140 fast_syscall_common+0x101
```
Sending `SIGCHLD` to the hung process always fixes it.  I have only observed this problem on FreeBSD 13-CURRENT; never on 12.1-RELEASE.

**Comment by zanchey** [comment]
Maybe same as #6878?

**Comment by asomers** [comment]
But on 6878, sending `SIGCHLD` does not help.  For me, it does.

**Comment by ridiculousfish** [comment]
Nice, maybe I can repro on FreeBSD.

**Comment by asomers** [comment]
I just upgraded to fish 3.1.1, and I can reproduce this more easily now.  It's still not 100% though, and sending SIGCHLD still fixes it.

Steps to reproduce:
1) Install fusefs-lkl like this: `pkg install fusefs-lkl`
2) Type `pkg info -l fus` and then pres CTRL-C.

**Comment by ridiculousfish** [comment]
Thanks! I will definitely take a look.

**Comment by ridiculousfish** [comment]
Update: I have been able to sporadically reproduce. Still investigating.

**Comment by ridiculousfish** [comment]
Update: I believe this is a regression in FreeBSD CURRENT signal handling. Many bothans died to  produce a reduced test case, which [I filed here](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=246385.).

I'll leave this open for a bit, we may have to make a workaround in fish-shell (but I hope not).

**Comment by zanchey** [comment]
Fixed upstream, already!

**Comment by mqudsi** [comment]
Tremendous bug hunting, @ridiculousfish!
It was a real pleasure to follow the rabbit hole you traced out all the way down into the new sigfastblock code (which seems like a messy enhancement but I these days any syscall elimination is a win).

I tip my hat to you.
