### ISSUE TITLE
I get a weird math error every time I start a terminal

### ISSUE THREAD

**Issue by IgnisDa** [fish-shell/fish-shell#6921]
fish, version 3.1.0
`math: Error: Logical operations are not supported, use test instead
'44 >= 20 && 82 >= 80'`
I have no idea what this is, or why it is displayed. If it helps, I am using the oh-my-fish plugin. This is not terminal specific and I have experienced it with kitty, st and tilix.

**Comment by faho** [comment]
One of the plugins you are using hasn't been updated for compatibility with fish >= 3.0. You need to either update it or remove it.

**Comment by zanchey** [comment]
Probably https://github.com/oh-my-fish/theme-qing/:

```
function fish_greeting -d "what's up, fish?"
    if math "$LINES >= 20 && $COLUMNS >= 80" > /dev/null
        bash (dirname (status -f))/archey.sh
    end
end
```

**Comment by faho** [comment]
Yeah, that's it, and https://github.com/oh-my-fish/theme-qing/pull/4 would fix it.

**Comment by IgnisDa** [comment]
Thank you very much, I am, in fact, using that theme. However, what am I supposed to do with the piece of code you provided?

**Comment by faho** [comment]
>However, what am I supposed to do with the piece of code you provided?

That is the broken code in theme-qing that needs to be fixed. You don't have to do anything with it.

The simplest thing for you to do is to switch to a theme that isn't broken.

**Comment by IgnisDa** [comment]
Thank you very much, that fixed it.
