### ISSUE TITLE
fish doesn't cope with literal tabs in command history

### ISSUE THREAD

**Issue by sersorrel** [fish-shell/fish-shell#6923]
- fish 3.1.0
- Ubuntu 18.04, Linux 4.15.0-96-generic
- first encountered in Alacritty, reproduced in xterm

If there is a literal tab in command history (aiui this is impossible with fish itself, but I guess it's reading my ~/.bash_history and seeing this there), fish's autocomplete breaks horribly when it prints it.

Demonstration: https://asciinema.org/a/pyYipLwhQAZEvLJkZkDysXAQv

(the command it's completing there is `echo '\t' | xxd`, though obviously with the `\t` replaced by a literal tab character)

**Comment by krobelus** [comment]
I think this is the same issue as #5274, which arises when inserting literal tabs with `fish_clipboard_paste`.
 fish does not deal properly with tabs in the commandline buffer. I believe that fish assumes 1 as the width of a tab character, while terminals use 8.

**Comment by faho** [comment]
>I believe that fish assumes 1 as the width of a tab character, while terminals use 8.

Worse. Terminals assume a tab goes until the next tab stop.

We should just remove these outright. There is no reason to have a literal tab character in the commandline. You can *always* use `\t`.
