### ISSUE TITLE
Feature: Show list of options without having to double-tab

### ISSUE THREAD

**Issue by thernstig** [fish-shell/fish-shell#6924]
fish 3.1.0
Ubuntu 16.04.6
xterm-256color

Let's say you have three files such as `.bashrc`, `.bash_history` and `.bash_logout`. I believe there is an unnecessary tab that could be removed for autocompletion of these. Here is an example.

1. `vi .b` then do a tab, this will show:
2. `vi .bashrc` (where `bash` is highlighted and `rc` is greyed out)
3. Tab again and you see `.bashrc`, `.bash_history` and `.bash_logout` below the prompt.

Unless I am missing something, I am thinking that step 3) is unnecessary and that the tab in 1) should directly do both 2) and 3).

**Comment by zanchey** [comment]
I'm going to restate this as "tab completion should always invoke the pager". I thought this had been raised in the past but I can't find it.

My gut feeling is that this would be a controversial change. There are a number of people who dislike the pager (see #2249, though that is more about the search that the pager starts), and a great deal of muscle memory in the existing behaviour.

I wonder if it would be better to make this customisable (eg a binding for complete-with-pager and perhaps complete-unambiguous), though I know we're trying to avoid that.

**Comment by krobelus** [comment]
This is an interesting idea, I usually press tab twice in this scenario.

I have implemented this in https://github.com/krobelus/fish-shell/commit/9117c0d7b05ad21ceece6c3591fe0cb1956aa47b, it feels fresh and non-intrusive.
I don't think it's visually distracting - it only changes the behavior when the completion is ambiguous. The user needs to resolve this ambiguity somehow, it doesn't hurt to show the options.

However, I don't know why it has always been like this (also in other shells). Possibly to avoid needlessly cluttering the screen, but luckily fish handles this situation gracefully by only showing four lines when Tab is pressed for the first time.

**Comment by thernstig** [comment]
You have far more experience with fish and what users feel controversial than I do. But my own gut feeling would be to default to this new behavior.

Reason I am saying so is because I feel that many users that move to fish do it for all the convenience and time-saving features. It makes you feel more productive. So defaulting to this means, even it if is minor, like you work faster. One less tab.

**Comment by zanchey** [comment]
Well, perhaps we can merge it, try it out ourselves, and ask for feedback on the fish-users mailing list?

**Comment by krobelus** [comment]
> Well, perhaps we can merge it, try it out ourselves, and ask for feedback on the fish-users mailing list?

Good idea, I just sent out a mail.

Merged, thanks for filing!
I realize I forgot the changelog again, not sure how notable this is.

**Comment by zanchey** [comment]
*Definitely* notable!

**Comment by zanchey** [comment]
OK, I just tried this and I love it.

**Comment by thernstig** [comment]
Awesome 🥂
