### ISSUE TITLE
add snake, camel, kebab && pascal commands to string builtin

### ISSUE THREAD

**Issue by shouze** [fish-shell/fish-shell#6925]
As we today have commands such lower and upper, I wonder if you would accept to add some more string format conversion commands.

**Comment by zanchey** [comment]
This seems a bit out of scope for a shell - is there a rationale for adding it?

**Comment by shouze** [comment]
@zanchey this is just I've not found a lot of simple cli string manipulation tools. I've spotted https://github.com/maxlath/text-transform-cli but I'm not a big fan of the design I would prefer it can read from stdin (pipes).

**Comment by ridiculousfish** [comment]
What, sed and awk aren't "simple?" 😛 

I agree with zanchey, this seems out of scope for a shell. Thanks for filing anyways.
