### ISSUE TITLE
fish_clipboard_copy includes a newline

### ISSUE THREAD

**Issue by ariasuni** [fish-shell/fish-shell#6927]
Since commit 20099774a058b15537ffec34257aaea1f58e97c6, function `fish_clipboard_copy` adds a `\n` at the end of the copied text.

I don’t see a good reason for this behavior, and I find it annoying.

**Comment by zanchey** [comment]
@faho any thoughts?

**Comment by zanchey** [comment]
Yes, apparently :-)

**Comment by zanchey** [comment]
Took this for 3.1.1 as d9cf1be4b.

**Comment by ariasuni** [comment]
Thanks a lot :)
