### ISSUE TITLE
How to convert an array to arguments?

### ISSUE THREAD

**Issue by Magicloud** [fish-shell/fish-shell#693]
Say I have a file list.txt: "a b c d e f". In bash, I could do `someCMD `cat list.txt``, which equals to `someCMD a b c d e f`.
But in fish, the command will fail with prompt like: "a b c d e f is not a file" because fish pass the whole string as ONE parameter to the command, instead of a few.

**Comment by faho** [comment]
This is now implemented with `string`, i.e. `somecmd (string split " " < somefile)`.
