### ISSUE TITLE
Add an equivalent of bash's 'insert-completions'

### ISSUE THREAD

**Issue by hexagonal-sun** [fish-shell/fish-shell#6931]
Hello,

I've been looking at the docs for an equivilent in fish of bash's 'insert-completions' function.  According to the man page:
```
Insert all completions of the text before point that would have been generated by possible-completions.
```
My use-case of this is if there is a common prefix in a package and I wish to install/uninstall them.  Say I have a bunch of packages that I want to install:
```
xf86-video-amdgpu
xf86-video-ati
xf86-video-dummy
xf86-video-fbdev
xf86-video-intel
xf86-video-nouveau
```
If I were to write `pacman -S xf86-video` and run the `insert-completions` command the list is expanded to the results returned by completion:
```
pacman -S xf86-video-amdgpu xf86-video-ati xf86-video-dummy xf86-video-fbdev xf86-video-intelm xf86-video-nouveau
```
which then allows me to further edit the command.

**Comment by faho** [comment]
`complete --do-complete` can be used for this:

```fish
function insert-completions
    # We need to remove the descriptions, and we also don't want everything to be inserted on separate lines
    commandline -i -- (complete --do-complete | string replace -r '\t.*' '' | string join " ")
 end

bind \cg insert-completions
```

**Comment by zanchey** [comment]
That's pretty nifty, is it worth formalising as a `fish_insert_completions` function?

**Comment by hexagonal-sun** [comment]
@faho Thanks for your suggestion.  I gave it a go, however I had an issue when running `C-g` with the command line `sudo pacman -S xf86-`

```
commandline: Invalid combination of options,
insertion mode switches can not be used when not in insertion mode

.fishrc (line 3): 
    commandline -i -- (complete --do-complete | string replace -r '\t.*' '' | string join " ")
    ^
in function 'insert-completions'

(Type 'help commandline' for related documentation)
```

**Comment by jedbrown** [comment]
Thanks for making this issue. The solution isn't quite equivalent. For example, typing `pacman -S xf86-` and triggering `insert-completions` yields `pacman -S xf86-xf86-input-elographics xf86-input-evdev [...]`. I'm newly tinkering with Fish so don't know how to remove the stem before inserting the completions.
