### ISSUE TITLE
Arrow up skip last command (with blank line no autocomplete in progress)

### ISSUE THREAD

**Issue by giellamoswhard** [fish-shell/fish-shell#6932]
As I said after I updated to focalfossa with 
╰─>$ fish -version
fish, version 3.1.0

When i use the up arrow it always skip the last command Even if I have not started typing anything.

**Comment by zanchey** [comment]
Can you make a screencast or similar (eg using asciinema)? I can't reproduce this behaviour on 3.1.0 on Debian.

**Comment by giellamoswhard** [comment]
Yes: thats an example

https://asciinema.org/a/v0PekSBEKvCN1vhtb0duy9LNh

**Comment by giellamoswhard** [comment]
It seems that it was a Terminal related bug up key works as if I pressed it twice. Sorry.
