### ISSUE TITLE
How to keep pipe/file open?

### ISSUE THREAD

**Issue by kuvaldini** [fish-shell/fish-shell#6934]
In some cases it is very useful ability to keep pipe(fifo) open. In bash this looks like:

    exec 3<>/path/to/pipe

Is there similar functionality in Fish shell?

**Comment by faho** [comment]
Duplicate of #3948

**Comment by faho** [comment]
In other words: No, there currently is not.

**Comment by kuvaldini** [comment]
@faho thank you for response.
