### ISSUE TITLE
--background switch not working on all color variables

### ISSUE THREAD

**Issue by MCMaurer** [fish-shell/fish-shell#6939]
fish version 3.1.0

Using iTerm2, though same result with xterm-kitty and Mac Terminal.

I ran `sh -c 'env HOME=$(mktemp -d) fish'` and got the same results.

---

`fish` doesn't seem to be properly displaying background colors for some of the `fish_color_*` variables. For example, when I set the comment color here, the background color is not displaying properly:

https://asciinema.org/a/ROvIWyle5AYECtYXfy8VH4f1v

That exact same background color displays perfectly fine for selection, as can be seen here:

https://asciinema.org/a/oANvsFf7Hp9DlawNX3C5rNHWw

I have `set fish_color_selection --background=red` in my `config.fish`, and it's been there quite a while, but when I try to add `set fish_color_comment --background=red`, that fails in the same way as entering it on the command line.

Essentially, the exact same `--background` color settings will display for some `fish_color_*` variables but not others. Maybe it's supposed to be that way, but according to [this page](https://fishshell.com/docs/current/index.html#variables-color), "the --bold or -b switches accepted by set_color are also accepted".

**Comment by Delapouite** [comment]
It looks related to this issue https://github.com/fish-shell/fish-shell/issues/25

**Comment by zanchey** [comment]
Let's track in #25
