### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by mcandre** [fish-shell/fish-shell#694]
Could we get some screenshots on the README?

**Comment by faho** [comment]
There are screenshots on the website now. Close?

**Comment by ridiculousfish** [comment]
This is a request for them on the README. Not high priority but if someone wants to take it on they can.

**Comment by krader1961** [comment]
The README file is the wrong place for screenshots, IMHO. That file is meant to be succinct so people can quickly read it to learn what the project is about and get pointers to more detailed information such as https://fishshell.com where screenshots are appropriate. So I'm closing this.

**Comment by floam** [comment]
Without them in the README our fish project page isn't as cool as it could otherwise be. I don't see the problem.

**Comment by faho** [comment]
It's been five years (1.5 since the last comment) and nobody has made a screenshot. Apparently it's not happening. Closing!
