### ISSUE TITLE
Focus events not disabled during commands run in bind

### ISSUE THREAD

**Issue by bcgraham** [fish-shell/fish-shell#6942]
```
me:~> tmux -V
tmux next-3.2
me:~> fish --version
fish, version 3.1.0
me:~> echo $version
3.1.0
me:~> uname -a
Darwin [redacted] 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
me:~> echo $TERM
screen-256color
```
Focus events are enabled during commands run inside key bindings. So, for example, if I'm in tmux and use `\eh` to view a `man` page, the focus events get sent to `man`.

I think this is because `fish_preexec`/`fish_postexec` aren't run from the binding, so they don't run `__fish_disable_focus`/`__fish_enable_focus`, respectively. 

Reproduction:
```
set tmpdir (mktemp -d)
printf %s\n \
  "new -s misc" \
  "set-option visual-bell on" \
  "set-option focus-events on" > $tmpdir/.tmux.conf
echo "puts 3.times.map { STDIN.getc }.join.inspect" > $tmpdir/inspector.rb

env HOME=$tmpdir tmux -S $tmpdir/socket -f $tmpdir/.tmux.conf att -t misc \; splitw -dhp50 \; send Enter
```
Now run `ruby ~/inspector.rb` and toggle back and forth between tmux panes - no input.
However, if you execute `bind \cg 'ruby ~/inspector.rb; commandline -f repaint'` and then press Ctrl-g, and then toggle back and forth between panes, you'll notice the focus event sequences.

**Comment by faho** [comment]
Yes, this is to be expected.

If you want to run things from the bindings, you'll have to take care of things like this, bindings aren't meant for long-running commands in the foreground, and there is no way for us to *detect* whether you're running a long-running foreground thing or not.

If you must, run something like `commandline -r -- 'ruby ~/inspector.rb'; commandline -f execute` instead, or use abbreviations - `abbr ins 'ruby ~/inspector.rb'`.

**Comment by zanchey** [comment]
We do ship a binding that does this, though, so perhaps we should fix it.

**Comment by bcgraham** [comment]
The above is the easiest way I could think of to clearly demonstrate how to reproduce, but to @zanchey‘s point, I found this when running Alt-h to view a man page.

**Comment by zanchey** [comment]
I think we should probably enhance fish to run those events when running a bind command, though I'm aware there might be a reason that's not possible; one other option would be to rewrite our Alt-H binding to call the right events.

**Comment by imcaizheng** [comment]
I ran into same issue while playing around with fish key bindings and fzf. When fzf is triggered by a key binding and is running foreground, funny characters like "O" and "I" would be inserted before focus lost/after focus gained. Guess those input are key sequences `\e[I` and `\e[O` and fzf consumes `\e[` and leaves the last characters.

Here is a demo https://asciinema.org/a/OqZUphTdrRJKLWVUOgN7fgbnk

Anyone has idea to fix this case?

**Comment by bcgraham** [comment]
Two solutions:
1. Use `fzf-tmux -p`! (I admit this isn't a real solution).
2. I fixed it by defining a new function, `binder` (the name isn't very evocative, just telling you exactly what I did that worked):
```fish
function binder
  functions -q __fish_disable_focus; and __fish_disable_focus
  $argv
end
```
Then, when I bind, whatever command I was originally passing to `bind`, I now pass to `binder`, which is passed to `bind`:
```diff
- bind \cq fzf
+ bind \cq 'binder fzf'
+ # or
+ bind \cq binder\ fzf
```
Hope that helps!

**Comment by imcaizheng** [comment]
@bcgraham Thanks for your solutions! Never know before there's a such handy function to disable focus. Tried `bind \cq __fish_disable_focus fzf` and it simple works.

**Comment by mk12** [comment]
Thanks @bcgraham your `binder` workaround is perfect. I think a nice official solution to this would be for `bind` to accept an `--interactive` flag that makes it do this for you.

**Comment by PatrickF1** [comment]
Hi, may I make a suggestion? What if fish introduced a new bind function called something like `bind_interactive` which was simply
```fish
function bind_interactive
  bind __fish_disable_focus $argv
```
?
The reason Tmux users and plugin maintainers don't want to just add `__fish_disable_focus` to our code is because it seems to be a private function that could be renamed at any time, and it feels dirty to use a function from fish's internals. Also seems like low work for fish maintainers and now y'all can assume that `bind` is for immediate-return functions `bind_interactive` is for long-running, interactive functions.

**Comment by PatrickF1** [comment]
Thanks for following up on this!
