### ISSUE TITLE
Duplicate Path Entry on source

### ISSUE THREAD

**Issue by jrock2004** [fish-shell/fish-shell#6945]
Version: 3.1.0
OS: Mac OS Catalina
TERM: xterm-256color

The problem I have is when I do `source ~/.config/fish/config.fish` I see duplicate entries in my path for items I added like

```
set -gx PATH $PATH "$VOLTA_HOME/bin"
```

How can I fix?

**Comment by krobelus** [comment]
```fish
if not contains $VOLTA_HOME/bin $PATH
    set -a PATH $VOLTA_HOME/bin
end
```

**Comment by jrock2004** [comment]
Thank you @krobelus . This worked perfectly

**Comment by rafo** [comment]
That's a fix, but what is the cause?

**Comment by faho** [comment]
@rafo The cause is that the line is run twice, because config.fish is automatically run when fish is started, and then `source config.fish` runs it again.

The line tells it to append the entry, and so it does, dutifully. Fish is simply doing what you told it to.
