### ISSUE TITLE
Fish completion for git with multiline aliases

### ISSUE THREAD

**Issue by m0nhawk** [fish-shell/fish-shell#6946]
After setting up [gitalias](https://github.com/GitAlias/gitalias), I've noticed strange completion for `git` from `fish` (`3.1.0`).

<details> 
<summary>Example of completion</summary>
<pre>
~ ❯ git
" $(du -s | awk \'{print $1}\');         printf "
" $(find . | wc -l);         printf "%d disk usage
" $(git branch -r | grep -v " -> " | wc -l);         printf "
" $(git branch | grep -v " -> " | wc -l);         printf "%d remote branch count
" $(git log -1 --date-order --format=%cI);         printf "%d commit count
" $(git log --date-order --format=%cI | tail -1);         printf "%s latest com…
" $(git log --format=oneline --format="%ad" --date=format:"%Y-%m-%d" | awk \'{a…
" $(git log --format=oneline --format="%aE" | awk \'{a[$0]=1}END{for(i in a){n+…
" $(git log --format=oneline --format="%cE" | awk \'{a[$0]=1}END{for(i in a){n+…
" $(git ls-files | wc -l);         printf "%d file count via find command
" $(git rev-list --count HEAD);         printf "%d date count
" $(git rev-parse --abbrev-ref HEAD);         printf "%s first commit timestamp
" $(git tag | wc -l);         printf "%d author count
" $(pwd);         printf "%d file count via git ls-files
";         printf "%s
"; git churn | head -7;     }; f
"; git log-of-count-and-day | head -7;         printf "
"; git log-of-count-and-email | head -7;         printf "
ack  (Alias for -c color.grep.linenumber="bold yellow" -c color.grep.filename=…)
add                                             (Add file contents to the index)
alias                                                           (Custom command)
apply                     (Apply a patch on a git index file and a working tree)
archive                           (Create an archive of files from a named tree
</pre>
</details>

For git aliases with multiline commands it parses multiple lines as a separate commands.

**Comment by faho** [comment]
Yeah. It turns out we correctly split the aliases, using `-z` everywhere, but then when we printed the completion candidates with the descriptions we split on newlines.

I've now changed it so that we only use the first line - anything more is very likely to be too long anyway, and we have no way of knowing which part is important.

**Comment by faho** [comment]
@zanchey I've tagged this for 3.1.2 because I'm not sure how cleanly it applies to 3.1.1. If it works we could also put it in 3.1.1.

**Comment by zanchey** [comment]
Applies fine so I've included it.
