### ISSUE TITLE
Better autocompletion for Mercurial

### ISSUE THREAD

**Issue by Tinche** [fish-shell/fish-shell#695]
I noticed the Mercurial autocompletions don't entirely work with f.e. 'hg update' - fish doesn't offer tags and branches.

The git autocompletions do this (and it even says if it's a tag or branch), which is awesome. If fish could do the same for Mercurial, that would be even awesomer.

Just to clarify, when I type 'git checkout \t' inside a git repo, fish suggests something like this:

    0.0.1  (Tag)  0.4    (Tag)  0.7    (Tag)  devel               (Branch)  origin/release-0.8  (Branch)  v0.9  (Tag)
    0.0.2  (Tag)  0.4.1  (Tag)  0.7.1  (Tag)  origin/devel        (Branch)  origin/release0.9   (Branch)  v1.0  (Tag)
    0.3    (Tag)  0.5    (Tag)  0.7.2  (Tag)  origin/release-0.6  (Branch)  origin/release1.0   (Branch)  v1.1  (Tag)
    0.3.1  (Tag)  0.6    (Tag)  0.8    (Tag)  origin/release-0.7  (Branch)  origin/release1.1   (Branch)

**Comment by faho** [comment]
The PR was merged, so this is probably solved.
