### ISSUE TITLE
Version 3.10 no longer supports escape-period for history-token-search-backward keyboard binding

### ISSUE THREAD

**Issue by ASzc** [fish-shell/fish-shell#6950]
I've noticed when using fish 3.1.0 on my Arch Linux machine that one of my favourite shortcuts, `escape-dot` or `escape-period` (to recall the last word of the previous command) no longer works. It works on my Fedora Linux machine, which is running fish 3.0.2.

```
alex@elendil ~> sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
alex@elendil /h/alex> fish --version; and echo $version; and uname -a; and echo $TERM
fish, version 3.1.0
3.1.0
Linux elendil 5.5.13-arch2-1 #1 SMP PREEMPT Mon, 30 Mar 2020 20:42:41 +0000 x86_64 GNU/Linux
xterm-kitty
alex@elendil /h/alex> echo hello
hello
alex@elendil /h/alex> .
```

```
aszczucz@tyrfing ~> sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
aszczucz@tyrfing /h/aszczucz> fish --version; and echo $version; and uname -a; and echo $TERM
fish, version 3.0.2
3.0.2
Linux tyrfing 5.3.16-300.fc31.x86_64 #1 SMP Fri Dec 13 17:59:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
xterm-kitty
aszczucz@tyrfing /h/aszczucz> echo hello
hello
aszczucz@tyrfing /h/aszczucz> hello
```

To reproduce the problem, simply: press the escape key, release the escape key, then press the period key. If it fails, a period will be printed, if it works, a word will be printed instead.

This is an ancient TTY keyboard shortcut, I don't even know where it first appeared, but I'm used to it, and would rather not switch to `alt-period`, which still seems to work.

**Comment by faho** [comment]
It is still bound, but we've reduced the timeout.

You see, in a terminal alt *is escape*. Pressing escape + . sends `\e` and `.`. Pressing alt+. sends... `\e` and `.`.

So, to disambiguate pressing just escape from other things, we have to run a timeout, and in 3.1 we reduced this because it means people had to wait for the timeout had run out. If you want to use escape as alt, increase it by setting $fish_escape_delay_ms. It used to be 300 in emacs and 100 in vi-mode.

**Comment by ASzc** [comment]
Wow, that timeout is so short! I can barely make it work 10% of the time when trying to press them as quickly in sequence as possible. I pretty much have to press them simultaneously, but not actually simultaneously, because that doesn't work.

Adding the following line to `~/.config/fish/fish_variables` does fix the problem:

```
SETUVAR fish_escape_delay_ms:300
```

You've technically not disabled the shortcut, but you functionally have. There's zero discoverability for this variable, and people will just give up, thinking it has been removed like I had. If you don't change anything, hopefully people can find this issue and fix the problem.

Feel free to close if you're going to keep it as-is. I'd be disappointed at that result though.

**Comment by faho** [comment]
>Wow, that timeout is so short! I can barely make it work 10% of the time when trying to press them as quickly in sequence as possible. I pretty much have to press them simultaneously, but not actually simultaneously, because that doesn't work.

Yes, because it's not meant to be used for escape-as-alt. It's meant to distinguish between "you have just pressed escape" and "the terminal sends us an escape sequence for a thing".

That's the overwhelmingly more common case, and increasing the timeout makes that worse.

>You've technically not disabled the shortcut, but you functionally have.

We haven't, because the actual shortcut is *alt*+period. That escape works in its place is a historical quirk.

You're used to it, so that's all you're thinking of. Most people don't use it that way, don't expect to work it that way and most of all don't expect to be paying the price (in terms of delay) for it working that way.

>There's zero discoverability for this variable, and people will just give up, thinking it has been removed like I had.

The variable is mentioned in the bind documentation. There's a paragraph "SPECIAL CASE: THE ESCAPE CHARACTER" on it.

>Feel free to close if you're going to keep it as-is.

I'll do that. Sorry, but we literally have to pick one or the other, and we're picking the normal one, and the other one has to set the variable. If that still disappoints you, then so be it.

**Comment by grantjoy** [comment]
This really is a deal breaker. Is there some other command that can be used instead in fish?

**Comment by faho** [comment]
@grantjoy "The way" is to read  issue and set the setting.

```fish
set -g fish_escape_delay_ms 300
```

**Comment by grantjoy** [comment]
> set -g fish_escape_delay_ms 300

Thank you so much, you have no idea how much this helps! Made my day.

**Comment by intiocean** [comment]
For anyone else having this issue on a mac/iTerm, where hitting `alt + .` gives `≥`, I added a new keyboard shortcut for `alt + .` to `Esc+ .` as per the screenshot and now can happily use the `alt + .` shortcut.

![image](https://user-images.githubusercontent.com/725843/91434405-0f0be480-e865-11ea-926e-6eee3cc0dbd3.png)

**Comment by BarbzYHOOL** [comment]
@faho I was used to Esc+. (from the numpad) but noticed it was super hard to get
So i stumbled upon this

Then you talked about alt+., but it doesn't work with the . from the numpad.
It works if I do alt+shift+. (the key to make the dot on my french keyboard requires shift). It also works as perfectly with esc+shift+.
**So I don't know, I want to use Esc + Numpad dot, or Alt + Numpad dot, how can I proceed?**

**Comment by anjukkumar** [comment]
> For anyone else having this issue on a mac/iTerm, where hitting `alt + .` gives `≥`, I added a new keyboard shortcut for `alt + .` to `Esc+ .` as per the screenshot and now can happily use the `alt + .` shortcut.
> 
> ![image](https://user-images.githubusercontent.com/725843/91434405-0f0be480-e865-11ea-926e-6eee3cc0dbd3.png)

Wow, looking for a solution for this exact issue and your trick worked like a charm. Thx

**Comment by BarbzYHOOL** [comment]
try alt + up arrow as well

**Comment by grantjoy** [comment]
For those who want the fix forever: `set -Ux fish_escape_delay_ms 300`

**Comment by krobelus** [comment]
note that latest master allows to map "escape followed by x" independently of "alt-x":

	bind escape,x 'do something'
	bind alt-x 'do something else'

so it's possible to get the behavior without timeout (but there is a weird prefix conflict with the default `bind escape cancel`)

**Comment by faho** [comment]
> so it's possible to get the behavior without timeout

to be clear: this requires a [supporting terminal](https://sw.kovidgoyal.net/kitty/keyboard-protocol/). So far that's 

- foot
- alacritty
- wezterm
- rio
- kitty

So it is likely not available for you.

**Comment by krobelus** [comment]
no, the disambiguation between `alt-x` and `escape,x` works on every terminal. Binding the key sequence that you actually press is an alternative to the timeout
