### ISSUE TITLE
Deleting the first character on a line continuation deletes the last character of the previous line

### ISSUE THREAD

**Issue by fratajczak** [fish-shell/fish-shell#6951]
fish version: `3.0.2-1627-gd502ad2c2` and up
Tested on Fedora 31 `Linux pc 5.5.16-200.fc31.x86_64 #1 SMP Wed Apr 8 16:43:33 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
The problem seems to be caused by d502ad2, the bug occurs on both gnome-terminal and kitty with a vanilla fish config.

To reproduce:
* Write a long command until the line wraps
* Insert only 1 character on the new line
* Press backspace
* The last character of the previous line disappears, it reappears after a redraw.

**Comment by zanchey** [comment]
That change got reworked in 5ece4481a5dfadb - can I ask if you've tried a newer version?

**Comment by fratajczak** [comment]
Yes, I bisected from the master branch.

**Comment by zanchey** [comment]
Yes, and I can reproduce (sorry, it was so simple that I should have done that first)

**Comment by ridiculousfish** [comment]
More fun from the sticky right margin. We can't issue `clr_eos` if we're "after" the last column since the cursor sticks to it. Fixed as 4116829292ddcfe21da86654b0a6a2bd765816b9 - thanks for filing!
