### ISSUE TITLE
`eval (__fzfcmd)` hangs indefinitely

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#6955]
Using https://github.com/fish-shell/fish-shell/commit/2bc4228d42919fc6600f3e4c21d3a0c7dff05843

---

By default, `fzf` evaluates its executable dynamically (see https://github.com/junegunn/fzf/blob/e6d33f77/shell/key-bindings.fish#L63).

However, this recently stopped working. Running `eval (__fzfcmd)` or even just `eval (echo fzf)` seems to hang indefinitely. Hitting Ctrl-C a few times interrupts whatever is hanging and the shell returns to normal, with the following output:

![image](https://user-images.githubusercontent.com/8544900/80478877-17e7ba80-8946-11ea-8c96-8d861a911ff3.png)

**Comment by OakNinja** [comment]
I was just about to report this, created an issue for jethrokuan/fzf here: https://github.com/jethrokuan/fzf/issues/147

Seems to be related to 3.1.1.

**Comment by dive** [comment]
It seems that I have the same issue with `enhancd` in addition to the problem mentioned in the description. Started to happen after the update to 3.1.1.

**Comment by clason** [comment]
I also get similar issues with conda (`conda update` freezes without output; `ctrl-c` terminates and shows the previous update).

**Comment by ridiculousfish** [comment]
In hindsight my pushing the eval changes into 3.1.1 may have been a little reckless.

**Comment by OakNinja** [comment]
> In hindsight my pushing the eval changes into 3.1.1 may have been a little reckless.

Well, I learned a lot while I was still convinced I had totally wrecked my whole environment. It didn’t even work when I created a new user 😁

**Comment by cumulotimbus** [comment]
For the time being, the Homebrew tap https://github.com/fish-shell/homebrew-fish is still at 3.1b1, for the `--devel` flag, so that's not a bad option for Homebrew users to downgrade while still letting brew handle the dirty work. That's where I am, since I have to do a coding demonstration today. Bullet dodged. 😅

**Comment by dustinfarris** [comment]
I downgraded back to 3.1.0 for now.

**Comment by timbedard** [comment]
For the time being, the Homebrew tap https://github.com/fish-shell/homebrew-fish is still at 3.1b1, for the `--devel` flag, so that's not a bad option for Homebrew users to downgrade while still letting brew handle the dirty work. That's where I am, since I have to do a coding demo today. Bullet dodged. 😅

**Comment by OakNinja** [comment]
> For the time being, the Homebrew tap https://github.com/fish-shell/homebrew-fish is still at 3.1b1, for the `--devel` flag, so that's not a bad option for Homebrew users to downgrade while still letting brew handle the dirty work. That's where I am, since I have to do a coding demo today. Bullet dodged. 😅

Wow, thanks! I prefer to stay in brew land on my work machine.

**Comment by purge** [comment]
FYI, to downgrade to the previous version (which homebrew makes annoyingly hard):
`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/618fcd7b144c0768a01bd4eab8deee960bd86466/Formula/fish.rb`

**Comment by nicolaturcato** [comment]
Same issue here. While running a `yarn` command it doesn't output anything. When I break it with `ctrl + c` it shows the previous output.
This started happening with 3.1.1 version.

**Comment by dustinfarris** [comment]
> FYI, to downgrade to the previous version (which homebrew makes annoyingly hard):
> `brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/618fcd7b144c0768a01bd4eab8deee960bd86466/Formula/fish.rb`

don't forget to `brew pin` as well so homebrew doesn't try to re-upgrade it again later.

**Comment by faho** [comment]
Okay, folks, we know about the issue, further discussion isn't all that helpful. I have locked the issue.

**Comment by ridiculousfish** [comment]
This is a serious 3.1.1 regression (mea culpa). I have started [Integration_3.1.2 branch](https://github.com/fish-shell/fish-shell/tree/Integration_3.1.2). @zanchey do you have resources to do a 3.1.2 release?

**Comment by zanchey** [comment]
Yes, I can do it today.
