### ISSUE TITLE
Keep older versions in PPA

### ISSUE THREAD

**Issue by mochja** [fish-shell/fish-shell#6957]
Recent 3.1.1 version introduced bug (#6955) with fzf and broke my environment. I was trying to downgrade to 3.1.0 trough PPA, but the packages are not there anymore.

Would it be possible to keep older versions in PPA, so people can downgrade if necessary?

**Comment by krobelus** [comment]
In case the old package is still in `/var/cache/apt/archives/`, it is possible to downgrade using that.

**Comment by zanchey** [comment]
I have definitely thought about this in the past. The only way of doing so is to start a new PPA for each version, then copy the packages to a master PPA (or upload them in parallel, which means building everything twice). That's adding a lot more steps to an already quite long process (though mostly scriptable), so I am not rushing to do so. If someone were to write the magic to create new PPAs from the command line I'd look at it, but for now I'm closing this as will-not-implement.

Plus there's doing the same for OBS, which is a whole different platform with a different Python API...
