### ISSUE TITLE
How to make locally created functions available to child processes?

### ISSUE THREAD

**Issue by patrickf3139** [fish-shell/fish-shell#6961]
I want to be able to do something like this
```fish
def func
    def helper
        echo "helping"
    end
    fzf --preview "helper {}"
end
```
But it seems `helper` is not accessible to the fzf process even though it's executing the preview function in fish. How can I make it accessible?

**Comment by faho** [comment]
The simplest thing is to save the function to a file named "helper.fish" in ~/.config/fish/functions, making it loadable by the child fish.

Function exporting as a feature is not planned - bash has it, and it was responsible for the security vulnerability known as "Shellshock".

Also note that all fish functions are global, so stacking them like that probably won't do what you think it does. (also the word to define a function is "function", not "def")

**Comment by zanchey** [comment]
See #6842

**Comment by patrickf3139** [comment]
Gotcha that makes sense. Thank you both for answering.
