### ISSUE TITLE
About string

### ISSUE THREAD

**Issue by yyy33** [fish-shell/fish-shell#6963]
- 

````
fish, version 3.1.1
````
- 
````
yyy@x550vc-yyy ~> uname -a; echo $TMUX
Linux x550vc-yyy 5.6.4-arch1-1 #1 SMP PREEMPT Mon, 13 Apr 2020 12:21:19 +0000 x86_64 GNU/Linux
/tmp/tmux-1000/default,16845,0

````

````
yyy@x550vc-yyy /h/yyy> sh -c 'env HOME=$(mktemp -d) fish'

Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish

````

- Can't figure out why the output of the third command will have a blank line, please tell me if you know

````
yyy@x550vc-yyy ~> echo 1\n2\n3
1
2
3
yyy@x550vc-yyy ~> echo 1\n2\n3 | string collect
1
2
3
yyy@x550vc-yyy ~> echo 1\n2\n3 | string collect -N
1
2
3

````

**Comment by faho** [comment]
Because `echo` adds a newline to whatever it outputs, and `string collect -N` will keep trailing newlines.

If you don't want that, use either `echo -n` or `string collect` without the `-N`.

**Comment by yyy33** [comment]
> Because `echo` adds a newline to whatever it outputs, and `string collect -N` will keep trailing newlines.
> 
> If you don't want that, use either `echo -n` or `string collect` without the `-N`.

Why there is no blank line in the output of the first command, this is where I wonder

**Comment by faho** [comment]
Because `string collect` adds a newline to its output when it's not going into a command substitution as well (technically it emits one "element" that'll be used as-is when it's going into a command substitution, or it will be displayed as one line, with a trailing newline). So you have `echo`s newline and `string`s, making it `\n\n`, which shows up as one empty line.

**Comment by yyy33** [comment]
> Because `string collect` adds a newline to its output when it's not going into a command substitution as well (technically it emits one "element" that'll be used as-is when it's going into a command substitution, or it will be displayed as one line, with a trailing newline). So you have `echo`s newline and `string`s, making it `\n\n`, which shows up as one empty line.
> 
> There really is no reason to use `string collect` unless at the end of a command substitution tho.

Thanks, I understand
