### ISSUE TITLE
argparse does not respect short arguments -s, -e, -n, -E

### ISSUE THREAD

**Issue by benweedon** [fish-shell/fish-shell#6966]
* fish, version 3.1.2
* uname -a: `Linux <host name> 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
* xterm-256color
* Ubuntu 18.04.4 LTS
* I've tried this with `sh -c 'env HOME=$(mktemp -d) fish'`, and same behavior

When I use `argparse` to specify an option whose short form is "s", "e", "n", or "E", `argparse` seems to fail to recognize that the option is present. Take the below test script:

```fish
#!/usr/bin/env fish

argparse 's/sopt' -- $argv
echo "$_flag_sopt"
echo "$_flag_s"
```

Using the command line `./testscript --sopt` will print out "--sopt" twice. However, `./testscript -s` prints out two blank lines. The same repros for "-e", "-n", and "-E", but for no other letters or single digit numbers. `argparse` seems to be treating these options differently for some reason.

Let me know if you need any more details on this repro!

**Comment by krobelus** [comment]
This is because echo interprets `-s` as flag, you could use `echo -- $_flag_s`.

**Comment by benweedon** [comment]
Yep, that's exactly it! Thanks for the quick explanation!
