### ISSUE TITLE
fzf-file-widget is not working in fish 3.1.1

### ISSUE THREAD

**Issue by hovnatan** [fish-shell/fish-shell#6972]
Using fish 3.1.1 on Manjaro Linux. Terminal is termite. After upgrading to fish 3.1.1, `fzf-file-widget` function from https://github.com/junegunn/fzf/blob/master/shell/key-bindings.fish hangs indefinitely.

**Comment by antonlindstrom** [comment]
Same for me, this https://github.com/junegunn/fzf/issues/2008 suggests that it is fixed in 3.1.2.

**Comment by frankiexyz** [comment]
installing fish-git works for me!
PS: I was using arch's fish before

**Comment by zanchey** [comment]
Yes, please upgrade to 3.1.2 as this should be fixed there. I'll close this for now but please reopen or comment if this is a problem in 3.1.2.
