### ISSUE TITLE
Feature Request: zsh like push-line support

### ISSUE THREAD

**Issue by jnko** [fish-shell/fish-shell#6973]
It would be incredibly helpful if the fish shell had a push line functionality.

See http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#index-push_002dline or https://unix.stackexchange.com/a/74208 for a detailed explanation.

> Take a look at the push-line ZLE command. This command pushes the current contents of the line onto the buffer stack and clears the line. You can then enter another command and when ZLE starts up again, the line is popped from the buffer stack into the line buffer.

Just in case this is already somehow possible, how?

**Comment by zanchey** [comment]
You can definitely implement it yourself:

```
function push-line
    set -g __fish_pushed_line (commandline)
    commandline ""
    function on-next-prompt --on-event fish_prompt
        commandline $__fish_pushed_line
        functions --erase on-next-prompt
    end
end

bind \cu push-line
```

I actually really like this feature in irssi. fish's line editor doesn't have the concept of a buffer stack, though, so I'm not sure how naturally it fits into the existing bindings.

**Comment by jnko** [comment]
This works exactly as planned!

Thanks a lot!

**Comment by elebow** [comment]
For future readers, the suggestion in https://github.com/fish-shell/fish-shell/issues/6973#issuecomment-624649522 no longer seems to work on fish 3.6.0. It may be related to #8807.

Using the `fish_postexec` event instead of `fish_prompt` behaves as desired:
```
function push-line                                                                                  
	set -g __fish_pushed_line (commandline)                                                           
	commandline ""                                                                                    
	function after-next-prompt --on-event fish_postexec                                               
		commandline $__fish_pushed_line                                                                 
		functions --erase after-next-prompt                                                             
	end                                                                                               
end  
```
