### ISSUE TITLE
How can I disable the warning telling me my terminal is too small?

### ISSUE THREAD

**Issue by gsbhasin123** [fish-shell/fish-shell#6980]
Sometimes when I make my terminal small, I get this:
```
<W> fish: Current terminal parameters set terminal size to unreasonable value.
<W> fish: Defaulting terminal size to 8
```
I know what I am doing and wish to disable this message, how can i do that? thanks in advance.
`fish -v` in case this has been implemented later on;
```
fish, version 3.1.1
```

**Comment by faho** [comment]
There is currently no way to disable this message.

**Comment by faho** [comment]
Well, technically you could disable the "warning" log category - `fish --debug -warning`. Can't recommend that, tho.

I think I'm just gonna remove this particular warning, the one about not being able to get a terminal size should stay tho.

**Comment by faho** [comment]
I removed the entire piece of code that defaulted terminal size. If we get something, it's what there is and there's no sense in complaining about it.

**Comment by zanchey** [comment]
See also #3740

**Comment by gsbhasin123** [comment]
alright thank you!
