### ISSUE TITLE
Complete --erase --command x --arguments

### ISSUE THREAD

**Issue by Korkman** [fish-shell/fish-shell#6987]
Fish version 3.1.2

Essentially, there is no way to undo this line (individually) from ssh completions as far as I know:
```
complete -k -c ssh -a '(__ssh_history_completions 100)'
```

There doesn't seem to be an option to erase or replace positional argument completes with no option prefix.

This would be handy for example when replacing the ssh host list:
```
# currently, this will erase all ssh completion (ignores -a)
complete -e -c ssh -a '(__ssh_history_completions 100)'
# and this would add to the already present history completions
complete -c ssh --arguments '(my_custom_host_function)'
```

Wildcard matching would be best:
```
# should erase all positional argument completions
complete -e -c ssh -a '*'
# only that 'history' thing
complete -e -c ssh -a '*history*'
# or maybe that thing described as 'Remote'
complete -e -c ssh -d '*Remote*'
```

Or a --replace option when adding arguments:
```
complete -c ssh --replace --arguments '(my_custom_host_function)'
```

Or if the behavior of appending to the arguments completion was unintended, add an --append option and make replacing the default:
```
complete -c ssh --append --arguments '(custom_additive_host_function)'
```

**Comment by faho** [comment]
So, what do you want to *use* this for?

Typically, any enhancements to the completions we would expect to just go upstream, so this would be overkill.

>Essentially, there is no way to undo this line (individually) from ssh completions as far as I know:

Correct. The way to change it is to copy the completions and remove it. Copy the file from /usr/share/fish/completions/ssh.fish to ~/.config/fish/completions/ssh.fish and alter it there.

**Comment by Korkman** [comment]
The actual use is modifying completions for a function which wraps ssh like this:
```
complete -c myssh -w ssh
complete -c myssh -l custom-long-opt ...
...
complete -c myssh -a '(custom_host_function)'
```
I did copy and modify the ssh completions for now, just as you suggested, but that means I will have to track future updates to /usr/share/fish/completions/ssh.fish ...

**Comment by krobelus** [comment]
>  but that means I will have to track future updates to /usr/share/fish/completions/ssh.fish ...

In this case you can get by with only one line in `~/.config/fish/completions/ssh.fish`:

`grep -v '^complete.*__ssh_history_completions' /usr/share/fish/completions/ssh.fish | source`

**Comment by Korkman** [comment]
> `grep -v '^complete.*__ssh_history_completions' /usr/share/fish/completions/ssh.fish | source`

Nice workaround! I didn't know piping to source was even possible.

**Comment by zanchey** [comment]
Doesn't seem like there's a great appetite for this, so I'm closing it for now. Always happy to hear (here or in a new issue) if there's something we haven't thought of though!
