### ISSUE TITLE
Cartesian Product is incompatible with Zsh

### ISSUE THREAD

**Issue by norio-nomura** [fish-shell/fish-shell#6992]
```terminal.sh-session
$ fish -c 'echo {A,B}{1,2}'
A1 B1 A2 B2
$ zsh -c 'echo {A,B}{1,2}'
A1 A2 B1 B2
$ fish -version
fish, version 3.1.2
```

**Comment by faho** [comment]
Fish is, in general, not compatible.

This is a case where switching would do more harm than good.

If you need specific ordering of arguments like these,and you need it to work across fish and zsh, don't use brave expansion

**Comment by norio-nomura** [comment]
I got the same result without using brace expansion.
```terminal.sh-session
$ set a A B
$ set b 1 2
$ echo $a$b
A1 B1 A2 B2
```
The only way to get the same result as Zsh is to nest the `for` loops? 🤔

**Comment by norio-nomura** [comment]
FYI, `bash` and `tcsh` are compatible with `zsh`
```terminal.sh-session
$ bash -c 'echo {A,B}{1,2}'
A1 A2 B1 B2
$ tcsh -c 'echo {A,B}{1,2}'
A1 A2 B1 B2
```
From looking at https://rosettacode.org/wiki/Cartesian_product_of_two_or_more_lists, there doesn't seem to be any other implementation that expands the Cartesian product from the first passed array like `fish` does.

It feels very inconvenient.

**Comment by faho** [comment]
>FYI, bash and tcsh are compatible with zsh

In addition to not being zsh, fish is also not bash or tcsh.

Whether this is just brace expansion or also other forms of expansion doesn't really matter.

The important things are:

1. Fish's behavior is generally acceptable - whether you go through back-to-front or front-to-back doesn't really matter. Either is fine. It's like a right-handed vs left-handed coordinate system. Pick one and run with it.
2. Being consistent here doesn't really enable interoperability more, as cross-compatible scripts already aren't really a thing.
3. In many cases the order won't matter - e.g. if you're doing `rm {a,b}{1,2}` you don't care about the order.
4. The cases where the order *does* matter are hard to find, so changing this *now* would be a rather awful compatibility break.

If this feature was added now, and not in a release, then changing it might be sensible. But as it stands, it's been in fish for a while, and changing it would be worse than keeping it.

**Comment by norio-nomura** [comment]
Thank you for your detailed response. 🙏 
It is understandable that `fish` can't change this behavior. Furthermore, I don't think it would be acceptable to add an option to change this behavior. So, I'll give up on this.
Thanks again.
