### ISSUE TITLE
Function usage question

### ISSUE THREAD

**Issue by kai-tub** [fish-shell/fish-shell#6995]
Hi,
first of all thanks for providing such an awesome shell!

I am working on a GitHub Action and wanted to do some error checking in my script, but I found it to be too hard in bash and looked into fish as an alternative. I am new to "real" shell scripting, so this question may seem trivial. :)

To make my workflow easy to follow I want to use a function.
This function parses an argument and decides whether or not it is a valid option. 
If it isn't then the default value should be used. Afterwards, I simply echo the result.

So far so good, but now I would like to inform the user, that the parsing failed and the default value will be used. In GitHub action, one can use `echo "::warning::$message"` to highlight the warning.
But if I echo the warning message, I mess up my *return value*.

The return value is a string and not an integer.

So my question is, how do I call a function, which could print to StdOut and still return a string?

Am I thinking too "programmery"? Should I simply work on global variables? 

Thanks!
Kai

**Comment by zanchey** [comment]
I assume you're using command substitutions to capture the output of your function, so you have a few options:

- Write your warnings to standard error, which is not captured by the command substitution:

```
count (echo "this is a warning" >&2)
This is a warning
0
```

- Use a return variable - it doesn't have to be global, but you'll need to define your function with the `--no-scope-shadowing` argument:

```
function foo --no-scope-shadowing --argument-names retvar
    if good
        set $retvar return
    else
        echo "bad!"
    end
end
foo myvar
echo $myvar
```

(I might have messed up the scoping there, which might require some judicious `set -l` in the enclosing blocks)

**Comment by kai-tub** [comment]
Thanks for the answers. :)

I would need to test if the GitHub toolkit commands are also triggered over stderr.
But for the second case, wouldn't it make more sense to create a global variable, to ensure that scope isn't messed up?

If I can't output the warning via stderr, I think I will set a global variable.

```
function foo
    if good
        set -g retvar "good"
    else
        echo "bad!"
    end
end
foo myvar
echo $retvar
```

I am still open to other suggestions.
Otherwise, the issue can be closed.

**Comment by ridiculousfish** [comment]
If you have a command which outputs to stdout, you can redirect stdout to stderr:

    gh test-command 1>&2

Agreed that a global variable would be reasonable.
