### ISSUE TITLE
`type time` incorrectly reports built-in as external command

### ISSUE THREAD

**Issue by d** [fish-shell/fish-shell#6997]
### Steps to reproduce
`type time`

Expected output
`time is a builtin`

Actual output:
`time is /usr/bin/time`

Bonus action
1. Executing `time ls` has different output as `/usr/bin/time ls` (as expected)

2. `builtin time ls` results in:
   ```
   fish: Unknown builtin “time”
   builtin time ls
           ^
   ```
  (Not sure this is expected)
3. Unlike other builtins, `time --help` won't work

### System Info

info ||
----|----
version | 3.1.0
OS | Ubuntu 20.04
Can I repro with an empty `$HOME`?| yes

**Comment by zanchey** [comment]
Thanks for the report. This got fixed in 3.1.1 (though you should upgrade to 3.1.2) - see #6598.
