### ISSUE TITLE
time builtin reports wrong time

### ISSUE THREAD

**Issue by ericonr** [fish-shell/fish-shell#7002]
- fish, version 3.1.2
- Linux ericonr-void 5.6.11_1 #1 SMP Wed May 6 19:42:50 UTC 2020 x86_64 GNU/Linux
- TERM: screen (termux) or alacritty

With `sh -c 'env HOME=$(mktemp -d) fish'` the problem still happens.

I'm running a fish script, using the builtin `time` function. I have the following minimal example:

```
#!/usr/bin/env fish

time dash -c "echo hello"
```

Which outputs

```
hello

________________________________________________________
Executed in  524.00 micros    fish           external 
   usr time  506.00 micros  102.00 micros  404.00 micros 
   sys time   28.00 micros   28.00 micros    0.00 micros 
```

Running

```
#!/usr/bin/env fish

sleep .1
time dash -c "echo hello"
```

outputs, instead:

```
hello

________________________________________________________
Executed in    1.95 millis    fish           external 
   usr time  1064.00 micros  245.00 micros  819.00 micros 
   sys time  906.00 micros   81.00 micros  825.00 micros 
```

Which seems to be the correct output, given that simply running `time dash -c "echo hello"` outputs around the same value, with a certain variance (at most up to ~4 millis).

Running other commands before `time` doesn't seem to influence the result, unless it's a lengthy one, such as `sl`.

**Comment by ericonr** [comment]
`fish -c 'time sh -c "echo hello"'` has the same issue, so I suppose the timer initialization has some sort of issue.

**Comment by faho** [comment]
If you assume that `sleep` time was added to the dash time, I don't think that's the case.

`sleep .1` sleeps for .1 seconds, which is 100ms.

The time you had reported for dash was 2ms, vs the time before of 0.5ms. That's absolutely in the realm of possibility for normal variance, especially if you have a system under load.

**Comment by ericonr** [comment]
I'm consistently getting 0.5ms when I don't add the sleep, and consistently getting between 1.9ms and 4.7ms when it's added. I'm aware sleep isn't being added to the time.

Anyways, I tried running this test a few dozen times, with and without `sleep`. There were very few times (2 or 3) where the version with `sleep` outputted 0.5ms as well, so I guess there's some weird interaction going on that makes it more likely to take longer without the sleep call.

Likely not a bug, then, just computers being computers. Thanks for the quick answer!
