### ISSUE TITLE
improve modularity

### ISSUE THREAD

**Issue by eoli3n** [fish-shell/fish-shell#7003]
fish, version 3.1.2

Operating System: Arch Linux
Kernel: Linux 5.4.39-1-lts
Architecture: x86-64

Eval subdir in fish config ``conf.d`` and ``functions`` would improve modularity.

**Comment by faho** [comment]
Lete counter your cliche with another: YAGNI.

Simply put adding directories here won't help for the common case of having ten or twenty files, and it will make reasoning about ordering and precedence harder.

That's a "no".

If you have a script that benefits from breaking up, make it explicit and `source` the parts in there.

**Comment by eoli3n** [comment]
Didn't know about YAGNI: thanks for this ;)
