### ISSUE TITLE
vim slowness (with enhanced slowness due to setting shell in vim)

### ISSUE THREAD

**Issue by butterywombat** [fish-shell/fish-shell#7004]
fish, version 3.1.0
mbp catalina 10.15.4
 Darwin C02XF21YJHD4 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
xterm-kitty (almost ok with kitty, but unusable with iterm)
https://github.com/dxuehu/dotfileserino/tree/master/omf omf configs
possibly related: https://github.com/fish-shell/fish-shell/issues/4611
(didn't try without 3rd party customizations - vanilla vim works fine without any vimrc)

When running nvim or vim in fish vs zsh, it is generally much slower and not useable in iterm (still slower in kitty, but not as bad)- fzf loads slower as well.

when I then set `set shell=/usr/local/bin/fish` in vim (regardless of which shell I'm in-zsh/fish, or even using macvim) it causes strange issues that make it unusable, especially with some commands (such as nerd tree toggling/finding and git blame via fugitive.vim). Even doing `:NERDTreeToggle` can take 5-10 seconds in iterm and hang vim- (the behavior seems to have changed a bit while I was narrowing down the line in my vimrc that caused it, but now it sometimes hangs until i 'ctrl-c' and then it updates). Also having the nerd tree window open at all causes scrolling to be even slower and laggy in the other windows, or just sometimes hangs the window, in which case I then ctrl-c to wake it back up.
One reason I wanted to set shell in vim was to use the built in `:terminal` which runs fish just fine, but that's not super necessary for me.

https://asciinema.org/a/W8VxM1GPUzBAmNLX9ZLYTQyWx (general slowness- fzf takes a second for each find. after setting shell to fish in vimrc, trying to show the lagginess especially of some commands).

I really do like fish, I wish I could use it as my default shell but unfortunately due to the slowness of vim in fish, I switched back to zsh. do you have any insights?

A friend of mine has none of these issues despite running vim in fish with my vimrc setup with set shell to fish (he has the same uname -a as me, mbp catalina, iterm, but on fish 2.7.1)

**Comment by faho** [comment]
First of all, it is not recommended to set shell to fish in vim. Plenty of vim addons execute fish-incompatible shellscript, so setting it to /bin/sh is better.

Secondly, the most likely issue here is that fish *always* loads its config, even if it isn't interactive.

In addition to whatever OMF is doing, you have things like:

```fish
set -gx NVM_DIR (brew --prefix nvm)
```

that should add a second or so to each fish startup. Guard these things in

```fish
if status is-interactive # or is-login if you prefer
    set -gx NVM_DIR (brew --prefix nvm)
end
```

and your experience should be much better.

**Comment by faho** [comment]
Also you want fish 3.1.2, not 3.1.0

Dani <notifications@github.com> schrieb am Do., 14. Mai 2020, 11:44:

**Comment by faho** [comment]
Assuming the question was answered, closing!

**Comment by butterywombat** [comment]
still slow, but a little less bad. thanks!
  

  
  
  

  
  
>
