### ISSUE TITLE
Git autocomplete doesn't see staged files

### ISSUE THREAD

**Issue by sam-rad** [fish-shell/fish-shell#7009]
```
# version:
fish, version 3.1.2
3.1.2

# uname:
Darwin 19.4.0 Darwin Kernel Version 19.4.0: root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

# term:
xterm-256color

# customization
No customization
```
`git commit` doesn't autocomplete the staged files. In the below GIF the top terminal is `zsh` and the bottom one is `fish`. Is this expected? Note that those two files are `added` and `removed`. They are *not* `modified`.

![fish-git-autocomplete1](https://user-images.githubusercontent.com/12651119/82078778-8e9aec80-9696-11ea-98d2-9bddc375376a.gif)

**Comment by sam-rad** [comment]
Seems like a duplicate of https://github.com/fish-shell/fish-shell/issues/5648

**Comment by faho** [comment]
It is not. This one is about `git commit`, that one was about `git add`. Frankly I didn't even know you *could* pass files to `git commit`

**Comment by krobelus** [comment]
`git commit -- foo` where `foo` is an AD file doesn't seem to do anything

**Comment by faho** [comment]
It's an "MD" file tho.

**Comment by sam-rad** [comment]
Thanks for the quick turnaround.
