### ISSUE TITLE
`fish_exit` doesn't fire when terminal window is closed

### ISSUE THREAD

**Issue by andreiborisov** [fish-shell/fish-shell#7014]
Function defined as
```fish
function my_function --on-event fish_exit
end
```

doesn't fire when Terminal.app (or iTerm) window is closed on macOS.

Is this expected behavior? If so, how can I fire `my_function` when the terminal window is closed?

I've also tried:
`--on-process-exit $fish_pid`
`--on-signal SIGTERM`
`--on-signal SIGKILL`

No success.

P.S. `my_function` is fired after executing `exit` command in the terminal window, but I need to be able to run it when the window is closed too.

```
fish, version 3.1.2
macOS 10.15.4
Terminal.app 2.10
```

**Comment by faho** [comment]
What exactly are you doing? What function are you using?

E.g. if you do

```fish
function idea --on-event fish_exit
    date >> /tmp/idied
end
```

leaves a timestamp in the file /tmp/idied in my tests. This is on linux, so it's possible there's some macOS weirdness.

**Comment by zanchey** [comment]
The event doesn't work for me on macOS or Linux when fish receives the SIGHUP signal, such as by `kill-window` in tmux or similar. Running through the debugger shows the event firing, but not the external process starting.

**Comment by schroedincat** [comment]
@faho thank you for your answer!☺️

It does seem to be related to a particular function I'm using because your example is actually working for me.

> What exactly are you doing? What function are you using?

I'm trying to edit command history:

```
function my_function --on-event fish_exit
	history delete --case-sensitive --exact -- 'SOME_COMMAND'
	history save
end
```

**Comment by mqudsi** [comment]
I (with 60% confidence) remember adding code to call fish_exit on nohup, but I don't think we have anything special to block the exit. More importantly, I don't think fish is set up to handle this as the exit handler may try reading from stdin or writing to stdout, which would cause a SIGTTIN or SIGTTOU as we would no longer have access to the terminal window. 

e.g. if you try reading/writing from the terminal in bash after a SIGHUP, the signal handler will fail:

```bash
function finish {
    # The following line halts execution of the trap handler
    echo "hello"
    echo "hello" > hello
}
trap finish EXIT
```

It's possible something similar is happening with fish.

**Comment by mqudsi** [comment]
When SIGHUP is encountered, a flag is set to end the read loop (`s_exit_forced`). No new executions are allowed through when this flag is present, and it's set before the `fish_exit` event is fired. As @zanchey says, the event is fired but nothing is executed.
