### ISSUE TITLE
"Abandoned lines" when spawning new shells

### ISSUE THREAD

**Issue by dmfj** [fish-shell/fish-shell#7015]
Hi there,

I've recently set up a new fish installation (3.1.2, but also reproducible in the latest 2.x release) and in certain terminal emulators (notably VS Code's integrated terminal,`TERM=xterm-256color`, running on `Linux 5.6.12-arch1-1`), a `⏎` character and bunch of spaces are emitted just before the first prompt, when spawning a new shell:

```
⏎[ spaces ]Welcome to fish, the friendly interactive shell
dmfj@dmfj ~> 
```

This only seems to occurs in terminals with an initial column size greater than 80, though I have been able to work around this by adding some arbitrary delay to the fish config (e.g. `sleep 0.03`).

The number of spaces after the `⏎` seems to follow this basic formula:

```
floor($COLUMNS / 80) * 80 - 1
```

After digging through the fish source I found that the `⏎` character is referred to as [`omitted_newline_str`](https://github.com/fish-shell/fish-shell/blob/e3c4692031346dd03cdb7f0cd83865201c168a82/src/common.cpp#L572) and is [printed while dealing with "abandoned lines"](https://github.com/fish-shell/fish-shell/blob/e3c4692031346dd03cdb7f0cd83865201c168a82/src/screen.cpp#L1185). I'm not sure what abandoned lines are and how they apply to the issue, but they seem to be related.

I'd appreciate any help in figuring out the cause of this!

**Comment by krobelus** [comment]
If I put `printf ' '` in my `config.fish` to print a single space before the greeting, then fish will print `$COLUMNS`-1 spaces after the `⏎` to make the greeting appear on the beginning of a visual line.

Something must be printing spaces before the first prompt is executed. In addition to disabling configuration, perhaps try running fish as `fish_trace=1 fish`, to see if there is anything that could be printing the spaces.

On which terminal does this happen? I can't reproduce in the VSCode one.

**Comment by dmfj** [comment]
@krobelus It's only happening in VS Code when the window is open at full-width. I have noticed the issue in Terminator too, but only when the greeting is enabled (in VS Code, it happens regardless). Thanks for suggesting a trace, will look at that :+1:

**Comment by faho** [comment]
I can reproduce. Pretty sure the issue is VS Code resizing the terminal after it starts fish.

**Comment by ridiculousfish** [comment]
I was able to repro with bash as well. Filed https://github.com/microsoft/vscode/issues/98399 on VSCode

**Comment by dmfj** [comment]
@ridiculousfish Great! Thank you!

**Comment by ridiculousfish** [comment]
There may be a workaround we can do in fish, I will leave this open for a bit to see if there is any traction on the VSCode issue.

**Comment by dmfj** [comment]
@ridiculousfish I'm using a hacky workaround myself at the moment, as this is an upstream issue, I'd prefer just to wait until it's fixed there

**Comment by faho** [comment]
Yeah, let this be solved in VS Code.
