### ISSUE TITLE
How to redirect output as arguments?

### ISSUE THREAD

**Issue by tuberry** [fish-shell/fish-shell#7018]
There is a command `comm -12 <(cat file1|sort) <(cat file2|sort)` in bash to list the common lines in `file1` and `file2`, but it cannot function in fish. I have read the `Input/Output Redirection` section in documents, what have I missed? Thanks.

**Comment by exploide** [comment]
I think what you want is process substitution.

`comm -12 (sort file1 | psub) (sort file2 | psub)`

The `psub` is the way to do that `<()` thing in fish. Also note that I removed the useless `cat` since `sort` can directly take file arguments.

**Comment by tuberry** [comment]
Thanks a lot.
