### ISSUE TITLE
Unable to set fish as the default shell in msys2

### ISSUE THREAD

**Issue by trajano** [fish-shell/fish-shell#7021]
fish 3.12-1

I installed it using `pacman -S fish` in an msys2 prompt.
Running `fish` afterwards worked fine.

However, trying to set it as the default shell by modifying `msys2_shell.cmd` causes the following lines to appear on startup

```
/usr/share/fish/functions/__fish_pwd.fish (line 1):
uname
^
in command substitution
        called on line 1 of file /usr/share/fish/functions/__fish_pwd.fish

from sourcing file /usr/share/fish/functions/__fish_pwd.fish
        called on line 2 of file /usr/share/fish/functions/fish_title.fish

in command substitution
        called on line 2 of file /usr/share/fish/functions/fish_title.fish

in command substitution
        called on line 3 of file /usr/share/fish/functions/fish_title.fish

in function 'fish_title'
        called on standard input

in command substitution
        called on standard input

/usr/share/fish/functions/__fish_pwd.fish (line 1): switch: Expected exactly one argument, got 0

switch (uname)
       ^
from sourcing file /usr/share/fish/functions/__fish_pwd.fish
        called on line 2 of file /usr/share/fish/functions/fish_title.fish

in command substitution
        called on line 2 of file /usr/share/fish/functions/fish_title.fish

in command substitution
        called on line 3 of file /usr/share/fish/functions/fish_title.fish

in function 'fish_title'
        called on standard input

in command substitution
        called on standard input

/usr/share/fish/functions/fish_title.fish (line 1):
__fish_pwd
^
in command substitution
        called on line 3 of file /usr/share/fish/functions/fish_title.fish

in function 'fish_title'
        called on standard input

in command substitution
        called on standard input

Welcome to fish, the friendly interactive shell
fish: Unknown command __fish_pwd
/usr/share/fish/functions/fish_title.fish (line 1):
__fish_pwd
^
in command substitution
        called on line 3 of file /usr/share/fish/functions/fish_title.fish

in function 'fish_title'
        called on standard input

in command substitution
        called on standard input

trajano@noriko /c/U/trajano>
```

**Comment by faho** [comment]
What is happening here is that fish can't find your `uname` program.

This is either because you don't have one - in which case you need to install it, or your $PATH is misconfigured - in which case you need to fix it.

**Comment by trajano** [comment]
Except that it works with `bash` 

The only line I changed was from

```
if NOT EXIST "%WD%msys-2.0.dll" set "WD=%~dp0usr\bin\"
set "LOGINSHELL=bash"
```

to

```
if NOT EXIST "%WD%msys-2.0.dll" set "WD=%~dp0usr\bin\"
set "LOGINSHELL=fish"
```

**Comment by faho** [comment]
Because bash does not execute `uname` in this case.

You need to see where you have a `uname` command installed. Check /bin, /usr/bin et al.

**Comment by faho** [comment]
Ah, okay. The [MSYS2 documentation](https://www.msys2.org/wiki/Porting/#detecting-version-of-msys-from-gnu-make) says at one point:

>you will likely get an error since uname will not be found on your PATH.

So it appears this should be patched. I don't know why nobody ever reported this, because it means nobody has installed the msys2 package since... 2013?

Frankly, that seems like you should try using something else. The WSL stuff seems to be quite popular, try that.

**Comment by faho** [comment]
This is https://github.com/msys2/MSYS2-packages/issues/1634.

**Comment by faho** [comment]
> Check /bin, /usr/bin et al. Add that directory to $PATH.

Or rather check `bash -lc 'command -v uname'`.

**Comment by trajano** [comment]
On bash 
```
trajano@noriko MSYS ~
$ bash -lc 'command -v uname'
/usr/bin/uname
```

**Comment by faho** [comment]
Okay, so you would have to add /usr/bin to your $PATH. The easiest is to `set -U fish_user_paths /usr/bin $fish_user_paths` once, interactively.

Personally, seeing as this is an *old bug* in the msys2 package, that is visible *immediately*, and breaks *everything* (it's not just about uname - if $PATH doesn't contain /usr/bin that means the setup is entirely broken), I'd go and use something else. Cygwin and WSL are available.

**Comment by trajano** [comment]
OK `set -U fish_user_paths /usr/bin $fish_user_paths` did it.  Kind of a round about way.  Maybe there's something that can be done so a user does not have to do this work?

**Comment by faho** [comment]
Well, the fix would be to have the normal system paths set already. That's how every other system does it.

This is a bug in msys2's path setup interplaying with msys2's fish package. It needs to be fixed there.
