### ISSUE TITLE
RFC: on the fly execution of light commands

### ISSUE THREAD

**Issue by psychoslave** [fish-shell/fish-shell#7022]
# In a Nutshell
One interesting think about Fish is how it provides feeback on the fly while user is typing its command.

However, it doesn't push this concept to the point where command results are displayed before the user even valid anything.

# An Illustrative example

Let's say I type
```
cd /home/psychoslave/Projets/leksemaro
gre
```

Fish is clever enough to suggest me to complete my command as `grep '^ŝ..o$' leksemaro.txt`. However it won't run this command in background and show previews of the result bellow the current prompt, as for completion among several proposals.

I think that would be very interesting to have such a feature, so in this example, I could accept to complete the suggestion, and tweak it to see result for `^ŝ...o$`, then `^ŝ..a$` and maybe `^.ŝ..i$` after that. All that, without typing enter at any point, expect possibly once I found a result that meet my expectations and that I want to save in the history.

# Things to Consider and Possible Implementations

A first thing to say is that of course you don't want all commands to be run like that on the fly, especially those with destructive operations, and other security concerns. So this should only be operate when the command pipeline only contains whitelisted elements.

A second point is that this feedback only makes sense when the whole pipeline execution time is runnable bellow a human perceptible latency, so [above 250ms](https://www.pubnub.com/blog/how-fast-is-realtime-human-perception-and-technology/) am I told.  That means that any pipeline above this threshold (or some other) could be simply ignored and let user with the same absence of feedback as what is currently provided.

Currently it seems that Fish's event handlers don't provide a way to run a command as the user type things, but that might be a way to let user implement such a feature as a simple function. At least provided that there is a way to kill a pipeline if it takes longer than a given threshold. Also the function should receive not only what the user typed so far, but also what Fish is currently suggesting to run.

What is your opinion?

**Comment by faho** [comment]
This is way too complex an implementation for very little gain. Like you said it's very difficult to figure out which commands are safe to run (and under what circumstances - when are the arguments in a good enough state that the result even makes sense?), and very few commands will then do useful things under the timeout.

Sorry but no.

**Comment by floam** [comment]
This could basically be done on a utility by utility basis where it maybe makes sense, as completion “hints” as previously suggested by others before. I do agree figuring out regexps can be hard and feedback would be nice. But this can’t be a general feature.
