### ISSUE TITLE
How to remove the annoying background echo sound?

### ISSUE THREAD

**Issue by jiapei100** [fish-shell/fish-shell#7025]
```console
 8  ✔  fish --version                                                                                                                                                                                     ~ 
fish, version 3.1.2-630-gad020e84d
 9  ✔  uname -r                                                                                                                                                                                           ~ 
5.3.0-51-generic
 10  ✔  echo $TERM                                                                                                                                                                                        ~ 
xterm-256color
```

Whenever I run a command, no matter successfully or failed, there is an annoying echo sound. Just wonder if there is any configuration in fish.init ? So that **the fish** can be a **quiet fish**??

**Comment by faho** [comment]
What happens here is that something sends a `\a` ("Bell") to the terminal, and that decides to take it literally.

What makes matters worse is that there are some escape sequences that end in a bell, and it's possible your terminal doesn't handle them.

What is your terminal? Not your $TERM, but the actual software you are using to display fish's output and send it input.

**Comment by zanchey** [comment]
The output of `locale` might be useful as well; there's a lot of extended characters in your prompt.

**Comment by faho** [comment]
Closing for lack of response
