### ISSUE TITLE
true and false fail with arguments

### ISSUE THREAD

**Issue by dirn** [fish-shell/fish-shell#7030]
**Please tell us which fish version you are using by executing the following:** 3.1.2

**Please tell us which operating system and terminal you are using.**

    Darwin 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
    screen-256color

**Please tell us if you tried fish without third-party customizations** Yes
**and whether it affected the behavior you are reporting:** No

**Tell us how to reproduce the problem.** 

Run the following commend

    $ true argument; and echo "worked"
    true: Expected 0 args, got 1

Under other shells, however, `true` and `false` accept and ignore any arguments passed to them.

    $ bash -c "true argument"; and echo "worked"
    worked
    $ sh -c "true argument"l and echo "worked"
    worked

**Comment by faho** [comment]
Already fixed by 4eccc0f6d15f8d81f4a480bc9743d2d11e6442f4

**Comment by dirn** [comment]
Thanks!
