### ISSUE TITLE
support Administrator in fish_prompt.fish

### ISSUE THREAD

**Issue by gMan1990** [fish-shell/fish-shell#7031]
- fish, version 3.1.0

- http://cygwin.com/
```plain
> uname -a
CYGWIN_NT-10.0 3.1.4(0.340/5/3) 2020-02-19 08:49 x86_64 Cygwin
```

- fish_prompt.fish
```plain
    if contains -- $USER root toor Administrator
```

**Comment by faho** [comment]
Yeah this should probably be a helper function - `fish_is_root_user`.

That way we wouldn't have to change it in *every single prompt*. 9 of our 16 prompts do this, one only checks for "root".

**Comment by damani42** [comment]
I'm really interesting to work on this issue. I will make this soon as possible.
