### ISSUE TITLE
Fish unlinks the fish_variables file

### ISSUE THREAD

**Issue by jakem72360** [fish-shell/fish-shell#7034]
Version: `3.1.2`

Upon a configuration change (such as adding an abbreviation), fish unlinks the `fish_variables` node in the config directory, and writes to a new file. This is problematic, if for example, you try to symlink `fish_variables` to a file located elsewhere on the system.

In my particular case, I have `fish_variables` symlinked into a local copy of a repo containing relevant configuration files. The problem is; fish removes the symlink and writes to a regular file, thus preventing any changes made, from being committed in the repo.

**Comment by faho** [comment]
This is necessary to make the changes atomic.

Sorry, we don't support symlinking that file. Symlink the directory.

**Comment by jakem72360** [comment]
The directory cannot be symlinked, so as to facilitate adding local files without storing them in the repo directory. Why not lock the file, if the issue is other running shell instances?

**Comment by faho** [comment]
>The directory cannot be symlinked, so as to facilitate adding local files without storing them in the repo directory. 

In that case you can use a different directory for those. If it's functions, add a directory to $fish_function_path. If it's eagerly sourced files, `source` them.

Or use gitignore or something for whatever vcs you're using.

**Comment by zanchey** [comment]
> Why not lock the file, if the issue is other running shell instances?

It's not so much locking (which is used as well) as writing the file in a transactional (all or nothing) way - there's an explanation if you're interested in `src/env_universal_common.cpp`: https://github.com/fish-shell/fish-shell/blob/aa8c9df2d0184fe51c40e49f360d50b18c81da19/src/env_universal_common.cpp#L638-L666
