### ISSUE TITLE
Add `until` convenience builtin

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#7037]
It would be cool to support bash's [`until`](http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_09_03.html) builtin in `fish`.

I realise I can currently write `while not` to achieve the same thing (and for that reason fish's maintainers are likely to be against this proposal) but sometimes the double-negative catches me out when I'm writing something like:

`while not (foo_is_not_bar); [...]; end`

Compared with the friendlier:

`until (foo_is_not_bar); [...]; end`

I feel the second form reads more naturally and makes the intent clearer.

Thoughts?

**Comment by faho** [comment]
I don't think it's a good idea.

Adding another keyword that means *exactly* the same as something else is not what we tend to do.

Might I suggest using an abbreviation? `abbr until "while not"`?

**Comment by krobelus** [comment]
A solution can be to reformulate `foo_is_not_bar` as positive statement.

Personally I tend to get confused by `until` in shell scripts. It doesn't seem very common.

**Comment by zx8** [comment]
Fair enough! Seems like this is a no, closing. 😄
