### ISSUE TITLE
`cdh` causes the `fish_prompt` event to be sent twice

### ISSUE THREAD

**Issue by lrworth** [fish-shell/fish-shell#7039]
```
lukeworth@Lukes-MBP /tmp> function show_prompt_details --on-event fish_prompt
      echo fish_prompt received!
  end
fish_prompt received!
lukeworth@Lukes-MBP /tmp> cd a
fish_prompt received!
lukeworth@Lukes-MBP /t/a> prevd
fish_prompt received!
lukeworth@Lukes-MBP /tmp> cdh
 a  1)  /tmp/a
fish_prompt received!
fish_prompt received!
Select directory by letter or number:
```

This is particularly annoying because I was using the `fish_prompt` event to display a wrappable environment status (c.f. https://github.com/fish-shell/fish-shell/issues/904#issuecomment-290882082).

As a workaround I am using the `fish_postexec` event. (Um, if anyone's using `vim` and this starts breaking plugins, try `:set shell=sh` to force POSIX shell instead of fish. TIL)

## Environment
```
[I] ➜ echo $version
3.1.2
[I] ➜ uname -a
Darwin Lukes-MBP 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64 i386 MacBookPro11,5 Darwin
[I] ➜ echo $TERM
xterm-256color
```

**Comment by zanchey** [comment]
This is caused by `read`. It doesn't seem to me that that should fire the `fish_prompt` event.

**Comment by mqudsi** [comment]
I just checked and the only non-prompt related usage of `fish_prompt` (i.e. would be relevant to `read`) *shipping with fish itself* is enabling bracketed paste, which begs the question: is bracketed paste intentionally enabled for interactive reads executed by a command?

* If yes, then we would stop firing `fish_prompt` in `read` and use a new event handler `fish_read` with an accompanying function to enable bracketed paste when it's fired.
* If no, then we would just stop firing `fish_prompt` in `read` altogether.

**Comment by faho** [comment]
>is bracketed paste intentionally enabled for interactive reads executed by a command?

Yes. With what bracketed paste does, it *should* be enabled wherever possible.

Since `read` understands bracketed paste (because it runs the full bindings), it should be enabled there.

>If yes, then we would stop firing fish_prompt in read and use a new event handler fish_read 

That would work, yes.

**Comment by mqudsi** [comment]
Thanks, @faho, and I agree. Just pushed the commit and included a note in the changelog in case anyone was relying on the old behavior.
