### ISSUE TITLE
How to disable custom (i.e. per-command) autocompletion?

### ISSUE THREAD

**Issue by L-as** [fish-shell/fish-shell#7040]
A lot of commands have some custom autocompletion (like stack, systemctl, etc.) where they show the possible commands and such, but to be quite honest, it is very common for them to be somewhat broken, and really just in the way of what I'm trying to do.
I can e.g. not unzip a file where the name does not end in .zip, and often, e.g. for systemctl's autocompletion, an error will happen during it!

So I was wondering if there is any simple way to disable custom autocompletion while still keeping the autocompletion for selecting files (which is very useful).

**Comment by krobelus** [comment]
There is no way to turn it off for all commands, but for specific commands you can do `complete -c unzip -e` or create an empty `~/.config/fish/completions/unzip.fish` to make it persistent.

I usually insert `: ` (alias for `true`) at the beginning of the command to get generic file completions, and then delete it before executing. Which is a bit awkward..

We should fix the incomplete completions, though!
Probably the unzip ones should complete any filename.
The systemctl completion error could be  #5689 which is fixed in 3.1.0.

**Comment by mqudsi** [comment]
I've been thinking of an enhancement to fish where a second `<TAB>` after a first one fails to generate any completions will disable the `complete -x` behavior and revert to the default to address issues like this without sacrificing the default preference for convention-based filename completion.

**Comment by exploide** [comment]
How would that go with cycling through completion items by repeatedly pressing `<TAB>`?

I fear that would be a confusing behaviour. Is it such a common problem? I would still vote for fixing unhelpful completions.

**Comment by mqudsi** [comment]
No, it would only kick in when there are no completions due to the -x

**Comment by faho** [comment]
How is this different from what we used to have (fall back to file completion), other than requiring a second tab press?

Quite often there just *are no sensible completions*, so adding files is absolutely unhelpful.

**Comment by floam** [comment]
That would confuse me on second tab. +1 fix the individual annoying completions.

**Comment by floam** [comment]
The zip completions would be better to complete any file name but sort `*.zip` first.

**Comment by faho** [comment]
Nah, we should just stop the suffix filtering in most cases.

It's wrong so often it's not even funny.

**Comment by floam** [comment]
I think suffix... prioritizing is a better way to go. They at least are more likely to be the desired files.

**Comment by faho** [comment]
Anyway, that's a different point.

The question has been answered, the systemctl issue was fixed a while ago, the unzip issue is now fixed (with potential refinement).

I'm closing the issue.
