### ISSUE TITLE
Can't autocd to directories named with leading underscore

### ISSUE THREAD

**Issue by magnolialogic** [fish-shell/fish-shell#7042]
**Summary**

Unable to autocd to directories named with leading underscore
<br>
**Steps to reproduce**

1. Create a directory in ~ with an underscore as the first character of its name (e.g. "_DEV")
2. Verify autocd is working by issuing "~"
3. Attempt to autocd to newly created directory via `_DEV`

Expected: fish changes working directory to _DEV
Actual: `fish: Unknown command: _DEV`
<br>
**Version / regression info**

Fish version 3.1.2

macOS 10.15.4

Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

xterm-256color

`sh -c 'env HOME=$(mktemp -d) fish'` does not alter repro

**Comment by faho** [comment]
Oh, wait, I can't actually reproduce this!

I thought I did because I made a directory called `_DEV` and entered `_DEV` and it told me "unknown command", but it turns out (I don't use autocd) you have to enter the trailing "/".

You'll also notice the highlighter will mark your directory as an unknown command (typically red) until you enter it.

So this seems to be working as expected.

**Comment by magnolialogic** [comment]
Aha, you're right. I usually use `~/<dir>` syntax with autocd which doesn't require a trailing `/` (presumably because fish knows I'm autocd'ing based on the leading `~`) so I wasn't expecting that.

`~/_DEV`: works
`_DEV`: fails
`_DEV/`: works
`_DEV/_github`: fails
`_DEV/_github/`: works

If those behaviors are expected (I think they are) I'm good to close this as Behaves Correctly.

**Comment by faho** [comment]
>If those behaviors are expected (I think they are) I'm good to close this as Behaves Correctly.

Yeah, like I said the rule is "contains a slash after tilde-expansion". Which means if it starts with a ~ or contains a "/" it'll be used, otherwise fish will assume it's supposed to be a command in $PATH.
