### ISSUE TITLE
Fish Shell repository error

### ISSUE THREAD

**Issue by vishpillai** [fish-shell/fish-shell#7045]
Ign:1 http://ppa.launchpad.net/fish-shell/release-3/ubuntu groovy InRelease
Err:2 http://ppa.launchpad.net/fish-shell/release-3/ubuntu groovy Release           
  404  Not Found [IP: 91.189.95.83 80]
Hit:3 http://deb.playonlinux.com trusty InRelease                                            
Hit:4 https://mirror.karneval.cz/pub/linux/kali kali-rolling InRelease                       
Reading package lists... Done                       
E: The repository 'http://ppa.launchpad.net/fish-shell/release-3/ubuntu groovy Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by zanchey** [comment]
Groovy's not out yet, is it?

**Comment by faho** [comment]
Ubuntu Groovy Gorilla is 20.10, due for release in october 2020.

So no, it's not out yet, and not even far along the schedule.

Try the ppa for 20.04 "focal" instead.

David Adam <notifications@github.com> schrieb am Mi., 27. Mai 2020, 15:06:

**Comment by vishpillai** [comment]
Hello Friends,
Mine is kali linux os.
this error come up every time i try to apt update

**Comment by faho** [comment]
Okay, here's your problem:

You are using Kali, which is based on Ubuntu. That means for adding Ubuntu repositories, it uses a corresponding Ubuntu version. The way Ubuntu does things that "version" is the codename, which in your case is "Groovy", which stands for "Groovy Gorilla", which is the upcoming Ubuntu 20.10 release.

Now, Ubuntu 20.10 is supposed to be released in October (that's what the "20.10" stands for - 20*20*, *10* = October), which means it is super early in the development cycle, which means it is quite unstable and not something you want to use if you are not an Ubuntu developer.

Now, who picked that version string I don't know, but the fish PPA does not yet support Ubuntu 20.10, and I don't think we want to yet.

You either picked that version in error, or Kali is being unhelpful in picking a super early Ubuntu to base on, or you picked a beta Kali version, I don't know.

Most likely it'll work if you simply replace that "groovy" with "focal" in the entry for the fish PPA. There should be a file in /etc/apt/sources.list.d that has the line

```
http://ppa.launchpad.net/fish-shell/release-3/ubuntu groovy
```

Replace "groovy" with "focal" and the update again.

**Comment by vishpillai** [comment]
@faho Thanks sir that worked. can you help with some latest repositories to add to kali.

**Comment by faho** [comment]
I am not Kali's support.

Quite frankly, you probably want a different distribution at first, like Ubuntu.

**Comment by zanchey** [comment]
I've copied the binary packagees from the focal repository to the groovy repo, so they might work.

**Comment by zanchey** [comment]
FWIW I use the following to pick the current list of repositories to upload to:

```python
from launchpadlib.launchpad import Launchpad
launchpad = Launchpad.login_anonymously('fish shell build script', 'production', '~/.cache', version='devel')                  
ubu = launchpad.projects('ubuntu')
print('\n'.join(x['name'] for x in ubu.series.entries if x['supported'] == True and x['name'] != 'precise'))                   
```

Pre-released distributions are not in the list.
