### ISSUE TITLE
How to properly use snap packages when fish is the login shell

### ISSUE THREAD

**Issue by kodaman2** [fish-shell/fish-shell#7046]
fish version: 3.1.0
Kubuntu 20.04
Konsole terminal

Brand new machine, I've used fish before and this is the first time installing snap packages. I didn't realized all the icons where gone until I remembered I changed the login shell, had me puzzled for a few hours. I was trying to get rid of using bash and bashrc all together, but at the moment I have bash as the login shell and calling fish at the end just so it can source /etc/profile so I can see snap packages icons.

Is this the most reasonable solution? Or did I missed something in the documentation?

https://askubuntu.com/a/1004536/864252

**Comment by faho** [comment]
Either that or set $XDG_DATA_DIRS yourself. Start bash, run `echo $XDG_DATA_DIRS` and put `set -gx XDG_DATA_DIRS THATVALUE` into your config.fish. It's not beautiful, but as I understand it that value is unlikely to change so it should work.

Once upon a time Canonical wanted to have snap set this stuff in a nicer way, but they apparently nixed that plan.

(tbh I'd also love it if everyone stopped putting random stuff in /etc/profile.d)

**Comment by kodaman2** [comment]
Thanks for the response.

> (tbh I'd also love it if everyone stopped putting random stuff in /etc/profile.d)
I don't know much about why snap puts it there, but I agree with that statement.

**Comment by zanchey** [comment]
It looks like snap upstream also sets the right environment variables via `/usr/lib/environment.d/990-snapd.conf` - is that file present?

**Comment by kodaman2** [comment]
> It looks like snap upstream also sets the right environment variables via `/usr/lib/environment.d/990-snapd.conf` - is that file present?

Yes, that file exists. I'll do a bit more troubleshooting this upcoming week and post logs here. Seems that file should do the job, instead of /etc/profile.d/apps-bin-path.sh

```
/u/l/environment.d ❯❯❯ cat 990-snapd.conf 
PATH=$PATH:/snap/bin
XDG_DATA_DIRS=${XDG_DATA_DIRS:-/usr/local/share/:/usr/share/}:/var/lib/snapd/desktop

```

```
/e/profile.d ❯❯❯ cat apps-bin-path.sh 
# shellcheck shell=sh

# Expand $PATH to include the directory where snappy applications go.
snap_bin_path="/snap/bin"
if [ -n "${PATH##*${snap_bin_path}}" -a -n "${PATH##*${snap_bin_path}:*}" ]; then
    export PATH=$PATH:${snap_bin_path}
fi

# Ensure base distro defaults xdg path are set if nothing filed up some
# defaults yet.
if [ -z "$XDG_DATA_DIRS" ]; then
    export XDG_DATA_DIRS="/usr/local/share:/usr/share"
fi

# Desktop files (used by desktop environments within both X11 and Wayland) are
# looked for in XDG_DATA_DIRS; make sure it includes the relevant directory for
# snappy applications' desktop files.
snap_xdg_path="/var/lib/snapd/desktop"
if [ -n "${XDG_DATA_DIRS##*${snap_xdg_path}}" -a -n "${XDG_DATA_DIRS##*${snap_xdg_path}:*}" ]; then
    export XDG_DATA_DIRS="${XDG_DATA_DIRS}:${snap_xdg_path}"
fi

```

My machine is running X11 by the way, don't know if that matters much.

**Comment by kodaman2** [comment]
Changed my default login shell back to fish, snap is nowhere in my paths, so I don't think 990-snapd.conf is doing much here. Just doing a quick google search looks like this issues has been lingering around for quite some time with ubuntu flavors. :

```
/u/l/environment.d ❯❯❯ echo $XDG_DATA_DIRS
/usr/share/plasma:/usr/local/share/:/usr/share/
/u/l/environment.d ❯❯❯ echo $PATH
/usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games
/u/l/environment.d ❯❯❯ 
```
Links to similar issues, even similar issue with snap packages with other shells like zsh, so this is looking more of a snap issue:
https://github.com/snapcore/snapd/pull/6813
https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1640514
