### ISSUE TITLE
^F does not work when Vi Key Bindings are enabled.

### ISSUE THREAD

**Issue by mrillusi0n** [fish-shell/fish-shell#7050]
I'm on v3.1.2. I use `^F` to complete the autosuggestions, but it works only when `fish_vi_key_bindings` is disabled. I'd like to be able to use it with `fish_vi_key_bindings` enabled.

**Comment by faho** [comment]
Yes, ctrl-f is very much an emacs binding, and so it should not be enabled in vi-mode.

All it does is `forward-char`, so you can just bind:

```fish
# for insert mode:
bind -M insert forward-char
# for "normal" mode
bind -M default forward-char
```

**Comment by mrillusi0n** [comment]
Thank you, that works!
