### ISSUE TITLE
less colors over SSH than on local machine

### ISSUE THREAD

**Issue by basbebe** [fish-shell/fish-shell#7051]
```
❯ fish --version
fish, version 3.1.2
```

I'm on two machines.
Local is Mac OS 10.15.4 running iTerm 3.3.10beta4
Remote is 12.1-RELEASE-p over SSH

I'm trzing to find out why I have fewer colors on the remote machine and no italics.

`local`
```
❯ tput colors
256

~
❯ fish -d2
<2> fish: exec_path: '/usr/local/Cellar/fish/3.1.2/bin/fish', argv[0]: 'fish'
<2> fish: determine_config_directory_paths() results:
paths.data: /usr/local/Cellar/fish/3.1.2/share/fish
paths.sysconf: /usr/local/Cellar/fish/3.1.2/etc/fish
paths.doc: /usr/local/Cellar/fish/3.1.2/share/doc/fish
paths.bin: /usr/local/Cellar/fish/3.1.2/bin
<2> fish: curses var TERM='xterm-256color'
<2> fish: curses var TERMINFO missing or empty
<2> fish: curses var TERMINFO_DIRS missing or empty
<2> fish: 256 color support enabled for TERM=xterm-256color
<2> fish: default emoji width: 1
<2> fish: sourcing /usr/local/Cellar/fish/3.1.2/share/fish/config.fish
<2> fish: 256 color support enabled for TERM=xterm-256color
<2> fish: 'fish_term24bit' preference: 24-bit color enabled
<2> fish: sourcing /usr/local/Cellar/fish/3.1.2/etc/fish/config.fish
<2> fish: sourcing /Users/XXX/.config/fish/config.fish

~
❯ set | grep TERM
COLORTERM truecolor
ITERM2_COOKIE XXX
ITERM_ENABLE_SHELL_INTEGRATION_WITH_TMUX YES
ITERM_PROFILE test
ITERM_SESSION_ID XXX
LC_TERMINAL iTerm2
LC_TERMINAL_VERSION 3.3.10beta4
TERM xterm-256color
TERM_PROGRAM iTerm.app
TERM_PROGRAM_VERSION 3.3.10beta4
TERM_SESSION_ID XXX
```

`remote`
```
[I] basbebe@host /u/h/basbebe> tput colors
74

[I] basbebe@host /u/h/basbebe> fish -d2
<2> fish: exec_path: '/usr/local/bin/fish', argv[0]: 'fish'
<2> fish: determine_config_directory_paths() results:
paths.data: /usr/local/share/fish
paths.sysconf: /usr/local/etc/fish
paths.doc: /usr/local/share/doc/fish
paths.bin: /usr/local/bin
<2> fish: curses var TERM='xterm-256color'
<2> fish: curses var TERMINFO missing or empty
<2> fish: curses var TERMINFO_DIRS missing or empty
<2> fish: 256 color support enabled for TERM=xterm-256color
<2> fish: default emoji width: 1
<2> fish: sourcing /usr/local/share/fish/config.fish
<2> fish: sourcing /usr/local/etc/fish/config.fish
<2> fish: sourcing /home/basbebe/.config/fish/config.fish

[I] basbebe@host /u/h/basbebe> set | grep TERM
ITERM_ENABLE_SHELL_INTEGRATION_WITH_TMUX YES
TERM xterm-256color
TERM_PROGRAM iTerm.app
TERM_PROGRAM_VERSION 3.3.10beta4
TERM_SESSION_ID XXX
```

Is it the $COLORTERM variable which doesn't get taken over?

Thanks!

**Comment by faho** [comment]
>Is it the $COLORTERM variable which doesn't get taken over?

Yes. That would enable true color support.

Either send it along (ssh's SendEnv and AcceptEnv options) or set $fish_term24bit to 1 on the remote end.

**Comment by basbebe** [comment]
```
[I] basbebe@host /u/h/basbebe> set COLORTERM truecolor
[I] basbebe@host /u/h/basbebe> tput colors
67
```

**Comment by faho** [comment]
Yes, this is quite possibly too new to show up in your terminfo (there are "-direct" entries, but only since last year or so?), so fish relies on other ways of figuring it out.

**Comment by basbebe** [comment]
> (also your remote system has a weird xterm-256color entry - I would assume that to have an actual... you know, 256 colors)

Me too…

**Comment by faho** [comment]
I think the question has been answered? The environment ssh sends may lead fish to think it can't do truecolor, and your remote system has what I consider to be a *wrong* xterm-256color terminfo entry that makes it think it has even fewer colors.

**Comment by basbebe** [comment]
Then I might have misunderstood you.

Why does it have a _wrong_ TERM variable?
To me the environments look nearly the same and Fish reports it supported 256 colors.

And why doesn’t Fish support italics when I add the COLORTERM variable?

**Comment by faho** [comment]
>Why does it have a wrong TERM variable?

No, the *variable* is correct. Only the variable value is merely the *key* to look up in the local terminfo/termcap database, typically belonging to (n)curses, and your version of the database tells it "xterm-256color" has 67 colors. It also tells it it doesn't have italics.

So: Your remote system is at fault, take it up with them.

**Comment by basbebe** [comment]
Ah, get it, thanks.
Anything I could manually do about it or an idea where to look at?

**Comment by faho** [comment]
See https://unix.stackexchange.com/questions/291412/how-can-i-use-terminfo-entries-on-freebsd

(I'm assuming from the version number "12.1-RELEASE-p" that this is FreeBSD - you've never actually stated outright)

**Comment by basbebe** [comment]
Yes it is, thanks for the hint!
