### ISSUE TITLE
Unable to use existing vimrc when enabling vim key binding.

### ISSUE THREAD

**Issue by yuujay** [fish-shell/fish-shell#7062]
fish, version 3.0.2

Darwin ujg.mac 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64

PROBLEM:
I have enabled vim key bindings on the fish terminal and this works fine. But I do not see a way to map existing `vimrc` file that I have configured when enabling the key bindings.

**Comment by krobelus** [comment]
fish won't read your .vimrc. You can use the [`bind`](https://fishshell.com/docs/current/cmds/bind.html) command to add additional mappings.

**Comment by faho** [comment]
Vimrc is unusable for other programs because it's an arbitrary vimscript file that can contain arbitrary code, so there is no way to parse it without adding a full vimscript interpreter.

**Comment by jos128** [comment]
> fish won't read your .vimrc. You can use the [`bind`](https://fishshell.com/docs/current/cmds/bind.html) command to add additional mappings.

Is there a way to map `JJ` to exit insert mode, while still printing a single `J` immediately? This common vim key mapping seems unusable  in fish's vi-mode, as it seems fish always waits for a second `J` or another key to decide what to do.

**Comment by faho** [comment]
There is not, no. Press a second key and it will do both the j-thing and the other key thing.
