### ISSUE TITLE
Fish does not reload altered fish_prompt function

### ISSUE THREAD

**Issue by thernstig** [fish-shell/fish-shell#7064]
```sh
fish, version 3.1.2
Linux LAPTOP-EJQDJE98 4.4.0-18362-Microsoft #836-Microsoft Mon May 05 16:04:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
xterm-256color
```

According to the docs at https://fishshell.com/docs/current/#autoloading-functions:
> If the function definition is changed, all running shells will automatically reload the altered version.

However, if I try to update fish_prompt, it does not automatically update i.e. when pressing <kbd>Enter</kbd> it does not show my updates.

It is possible this is by design, but I was stumped by it since I wanted to quickly test updates to my fish prompt.

**Comment by faho** [comment]
No, it'll just take a few minutes - we don't constantly reload every function, and we don't run e.g. inotify watches.

**Comment by thernstig** [comment]
Ok, it stumped me. Is it possible the docs at https://fishshell.com/docs/current/#autoloading-functions should mention this? Or is it an internal implementation detail maybe not considered worth mentioning?

**Comment by faho** [comment]
Yeah, adding a note is fair.

**Comment by 0ion9** [comment]
@faho Is there an internal function which does the reloading?

This issue often came up for me when editing a function in one terminal tab, then wanting the updated def in another tab immediately. So I wrote a function that does the reloading, but it would be better if this function could just wrap what fish itself uses.

**Comment by zanchey** [comment]
See #743, #5176
