### ISSUE TITLE
jobs command negative CPU

### ISSUE THREAD

**Issue by yegarti** [fish-shell/fish-shell#7066]
fish, version: 3.1.2
5.4.40-1-MANJARO
xterm-256color

Hi, Played with the 'jobs' command and noticed something odd with the CPU in a specific scenario:
![image](https://user-images.githubusercontent.com/9769019/83338411-c3c95080-a2cc-11ea-967c-f38832310429.png)

Seems like the 'CPU' somehow had an overflow.
It doesn't always happen, takes about 3/4 tries (each try in a new terminal).

**Comment by mqudsi** [comment]
While I wasn't able to reproduce this on the WSL 4.4.0 kernel, I think it's theoretically possible for there to be a race condition between `cpu_use()` and `proc_get_jiffies()` if multiple calls to `proc_get_jiffies()` are executed at the same time (`jobs` is a builtin and not subject to the restriction on being called from the main thread only), which could cause either of `p->last_time` or `p->last_jiffies` to actually be more recent than the "current" snapshot they're being compared to.

**Comment by mqudsi** [comment]
@yegarti if you're able to test against fish from git/master, it should be fixed.
