### ISSUE TITLE
psub substitute input stream rather than output

### ISSUE THREAD

**Issue by kuvaldini** [fish-shell/fish-shell#7068]
`psub` works for substitution of process' stdout, in bash it is `>(process)`.

Is there a `psub` to substitute process' stdin, in bash it is `<(process)`

**Comment by faho** [comment]
Duplicate of #1786

**Comment by faho** [comment]
>psub works for substitution of process' stdout, in bash it is >(process).

Wrong way around - `psub` is `<()`.

What you want is `>()`, which is asked for in #1786.

Tbh I've not really found a use case for it - typically you just want a pipe.

**Comment by kuvaldini** [comment]
My use case is:
```
somedata | tee >(process1) >(process2) >(process3)
```

**Comment by nipunarora** [comment]
I have a similar use case, can anyone comment on how this can be achieved?

**Comment by gokulsoumya** [comment]
@nipunarora A working solution posted in the linked duplicate: https://github.com/fish-shell/fish-shell/issues/1786#issuecomment-612369426
