### ISSUE TITLE
Completion file in $fish_complete_path does not work as intented

### ISSUE THREAD

**Issue by soraxas** [fish-shell/fish-shell#7071]
As I am not familiar with fish-shell's internal, so please correct me if I am wrong.
I think this problem exists because `fish` loads completion files on-demand, i.e., whenever user tries to tab-complete some commands?

So there is this feature in `git` where every binary with the prefix `git-XXX` can be executed as a custom command like `git XXX`, which is how [git-extras](https://github.com/tj/git-extras) and [git-town](https://github.com/git-town/git-town) add extra functionalities to `git`.

When I was writing a completion file for [git-town](https://github.com/git-town/git-town), I experienced these strange behaviours.

### Behaviour 1

When I placed `git.fish` in `~/.config/fish/completions/` and spawns a new shell, the completions work when I tried to tab-complete
```sh
fish town [tab]
```
However, the original git autocomplete is no longer here. I believe it is because `fish-shell` was able to find a completion file in `~/.config/fish/completions/` before it searches in `/usr/share/fish/completions/`, and therefore the official git autocompletion does not get loaded? (similar to $PATH behaviour).

### Behaviour 2a

When I named it as `git-town.fish` in `~/.config/fish/completions/` and spawns a new shell, the completions **does not get loaded** when I tried to tab-complete
```sh
fish town [tab]
```

### Behaviour 2b

Similar as *2a*, but instead I first tried
```sh
fish-town [tab]
```
which obviously doesn't work (because `complete` command in `git-town.fish` uses `git` as the name), but then afterwards when I tried to tab-complete
```sh
fish town [tab]
```
it works just like **Behaviour 1**.

I believe it is because `fish-town [tab]` forces fish-shell to load the `~/.config/fish/completions/git-town.fish` file. And even though it wasn't able to provide completion for `git-town` commnad, it loads my completion for `git town`; hence my subsequence
```sh
fish town [tab]
```
works as intended.

----------------

## Thoughts
1. I guess I understand the reason for fish's loading autocompletion on-demand (for performance reasons). But maybe after the main shell is launched, it should async load the rest of completion files in the background? (might make the shell memory bulky?)
2. Currently, I guess the complete file must be named to be same as the command that we want to provide completion for? (e.g. If I name it as `git-town.fish`, then `fish` only expects to find completion for `git-town` command in the file?)
3. Or, maybe rather than making it similar to $PATH behaviour, we should instead load every `git.fish` completion files in all directory...? (But it doesn't really solve the problem if more than one program wants to provide completions for `git-foo` and `git-bar` in the same folder `~/.config/fish/completions/` as they would overwrite each other.)

----------------

### Sys Information
```sh
$ fish --version
fish, version 3.1.2
$ uname -a
Linux HOSTNAME 4.14.180-1-MANJARO GNU/Linux
$ echo $TERM
xterm-256color
```

> sh -c 'env HOME=$(mktemp -d) fish'

Not applicable as this behaviour depends on env variable and my home.

-------------

**Comment by faho** [comment]
Your understanding is basically correct.

We load "git.fish" once you try to complete "git", and we only load the first one.

If you want to *add* to git.fish, you need to make a copy of it and add it there.

**Comment by soraxas** [comment]
Hi @faho thank you for your prompt response.

It's not that I want to add to the existing `git.fish`, but I use `git-town` as a tool where during installation it drops a `git.fish` in `~/.config/fish/completion/`. It only really deals with its own subcommand `git town xxx xxx ...` so it doesn't make sense to modify the main `git.fish`.

I understand that copying and appending to the offical `git.fish` would work but I don't think it is a very clean way to do so (copy paste is quite nasty).

Is there a reason of only loading the first one (to avoid conflict?). From the sound of it, I don't think the current approach is very modular, as every time you want to add your own custom completion files in your `$fish_complete_path` you would need to copy/modify the entire file.

**Comment by faho** [comment]
>Is there a reason of only loading the first one (to avoid conflict?).

To avoid conflict, and to allow full customization - if we just kept on loading our file, you couldn't *remove* anything from the completions.

>From the sound of it, I don't think the current approach is very modular

It's not, and it doesn't typically need to be!

This is really a super-special case! That git allows random commands to extend it is something *special*. `apt-cache` can't be invoked as `apt cache`. So there really is little need for this, except for git.

What we could do, instead of adding overcomplication to the completion system in general, is add a thing to the *git completion script* that allows extension:

```fish
for file in ~/.config/fish/completions/git/*.fish
    source $file
end
```

**Comment by faho** [comment]
Or, and this would work in existing fish, just load the git-town completions eagerly?

Like... you *can* just drop them in ~/.config/fish/conf.d instead of completions, and they'll be sourced.

That'll have a teensy bit of impact on your startup, but it shouldn't be a lot.

**Comment by soraxas** [comment]
Thanks for your prompt response.

Yes I understand it is quite a special case where I'm not aware other cli that does that. I haven't thought of your suggestion of sourcing git-extensions completion script within a special folder, which would seem to be useful for other git-tools to add fish completions without interfering with one another. It would be nice to see it in gets implemented in the main repo, but even otherwise I would probably do something similar to that for my own use (placing `git.fish` in the my home `.config` and sourcing `/usr/share/fish/completions/git.fish` within it (i.e. the other way around) so that I won't forget to change `/usr/share/fish/completions/git.fish` in my other systems)

But either way thanks for taking your time as a maintainer to promptly respond to issues with kind suggestions.

**Comment by soraxas** [comment]
For others with similar issue, this is the script that I used in `~/.config/fish/completions/git.fish`
```fish
set -l cur_dir (dirname (status -f))    
    
for f in $fish_complete_path    
  # skip this file      
  string match -q "$cur_dir" "$f"              
  and continue                       
                                     
  # source our first found git completion file      
  test -e "$f/git.fish"       
  and source "$f/git.fish"    
  and break    
end                                  
                                     
# source git extension completions    
for file in ~/.config/fish/completions/git/*.fish    
    source $file    
end   
```
