### ISSUE TITLE
Fatal Python error on fish_config

### ISSUE THREAD

**Issue by strika** [fish-shell/fish-shell#7077]
I'm using Fish 3.1.2 on Pop!_OS 20.04 (based on Ubuntu 20.04). I tried Fish without any third party customizations.

When I run `fish_config`, I get this output:

> Fatal Python error: calculate_program_full_path: path configuration: path too long
> Python runtime state: preinitialized

I'm not sure if the problem is with Fish, Python or something else. Please let me know if I can provide more information.

**Comment by faho** [comment]
This really seems like the error is coming from python.

What happens here is that `fish_config` is a function that figures out which python it should call via the `__fish_anypython` function, and then starts the webconfig script with that.

So, what does `__fish_anypython` print, and what does it say if you call `"$__fish_data_dir/tools/web_config/webconfig.py"` with that?

**Comment by strika** [comment]
Hopefully, I got this right:

![fish-debug-2](https://user-images.githubusercontent.com/737903/83598467-0f4c5a80-a56a-11ea-913f-61a9c6a86bd1.png)

Thank you!

**Comment by ammgws** [comment]
Does running that python command with `-vv` for extra verbose mode give any more details about the error?

**Comment by strika** [comment]
If this is what you had in mind, then no:

![fish-debug-3](https://user-images.githubusercontent.com/737903/83644926-1e56fb00-a5b2-11ea-8a4d-40ace6f9b56b.png)

**Comment by faho** [comment]
This is super looking like a python bug.

Do other python things work for you? If you e.g. save

```python
print("Hello")
```

as "test.py" and execute it with `python3 test.py`, does that work?

Does copying webconfig.py somewhere else and executing *that* help?

**Comment by strika** [comment]
`python3 test.py` also doesn't work.

![fish-debug-4](https://user-images.githubusercontent.com/737903/83650210-5eb97780-a5b8-11ea-9f96-8aacf1071055.png)

I assume this closes the issue. I'll try to look elsewhere. Thank you for help!

**Comment by faho** [comment]
So, there's one more possibility that has to do with fish.

Do you have any environment variables related to python set? Or are things like $PATH super long?

Only exported variables matter here, so if `env` shows something super long, that's the problem, and then `env -i python3 test.py` should work.

That could be caused by you appending to universal variables in config.fish, e.g.

```fish
set -U fish_user_paths /some/path $fish_user_paths
```

**Comment by strika** [comment]
That's it! I placed `set -Ux fish_user_paths $HOME/.rbenv/bin $fish_user_paths` from [rbenv README](https://github.com/rbenv/rbenv#basic-github-checkout) to `config.fish`, instead of just executing it.

Thank you for your time!
