### ISSUE TITLE
sudo !! doesn't work with fish

### ISSUE THREAD

**Issue by RaviTejaCMS** [fish-shell/fish-shell#7078]
Fish version - 3.1.2
OS - 5.6.15-300.fc32.x86_64 GNU/Linux ( Fedora 32 Workstation)
I am not using any third party customisation's
**sudo !!** is used to run previous command with root privileges but that doesn't  work in fish
Checkout screenshot for reference

![](https://user-images.githubusercontent.com/13203149/83637974-0ee1ad00-a5c6-11ea-9777-c6fd9e714ae5.png)

**Comment by faho** [comment]
Yes, this isn't a feature fish supports. Use other methods of editing the commandline.
