### ISSUE TITLE
How to remove the mode indicator in vi mode?

### ISSUE THREAD

**Issue by tamis-laan** [fish-shell/fish-shell#7084]
I would like to remove the [i] [v] [r] etc mode indicator. Not deeply familiar with fish I believe I should modify fish_mode_prompt?

**Comment by faho** [comment]
> I believe I should modify fish_mode_prompt?

Yes. `fish_mode_prompt` is a function, and whatever output it produces is used as the mode prompt.

So to disable the mode prompt display, replace it with a function that doesn't print output like:

```fish
function fish_mode_prompt; end
```

**Comment by faho** [comment]
Assuming the question is answered.
