### ISSUE TITLE
Deal with escaped characters in autogenerated man completions

### ISSUE THREAD

**Issue by ammgws** [fish-shell/fish-shell#7086]
I am not familiar with how escaping works in manpages but it seems like some escape single quotes as '\(cq' etc, which gets picked up as-is by the fish completion generation script. Might be nice to see if this could be fixed trivially.

```
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pacstrap \- install packages to the specified new root directory
.SH "SYNOPSIS"
.sp
pacstrap [options] root [packages\&...]
.SH "DESCRIPTION"
.sp
pacstrap is designed to create a new system installation from scratch\&. The specified packages will be installed into a given directory after setting up some basic mountpoints\&. By default, the host system\(cqs pacman signing keys and mirrorlist will be used to seed the chroot\&.
.sp
If no packages are specified to be installed, the \fIbase\fR group will be installed\&.
.SH "OPTIONS"
.PP
\fB\-C\fR <config>
.RS 4
Use an alternate config file for pacman\&.
.RE
.PP
\fB\-c\fR
.RS 4
Use the package cache on the host, rather than the target\&.
.RE
.PP
\fB\-G\fR
.RS 4
Avoid copying the host\(cqs pacman keyring to the target\&.
.RE
.PP
\fB\-i\fR
.RS 4
Prompt for package confirmation when needed (run interactively)\&.
```

![image](https://user-images.githubusercontent.com/20397027/83945620-e2889380-a846-11ea-9269-3e07ba91bc28.png)

**Comment by faho** [comment]
Troff is just always worse than you thought.

We already detect "cq" in some capacity, but I'm guessing it's just just `\cq`?

**Comment by faho** [comment]
Okay, deroff.py handles this, but generating the completion doesn't?

**Comment by faho** [comment]
Huh, we have multiple parsers here? I didn't expect that. It's probably down to handling multiple "dialects", and this doesn't detect `\(cq`, possibly because of that weird awful no-good `(` in there (seriously, groff is *awful*).

Anyway, let's just hack this in there, since we haven't had too many complaints, and man parsing is a bit of a dead end anyway.
