### ISSUE TITLE
Tab Completion not working as expected

### ISSUE THREAD

**Issue by kodaman2** [fish-shell/fish-shell#7090]
fish version: 3.1.0
Kubuntu 20.04
Konsole terminal

I've noticed tab completion is not working sometimes, below is one example but I've noticed it in other places too. It finds the stuff as you can see on the darkened colored font, but at the moment of tabbing I get a blink from the cursor to the beginning of the prompt. I've seen it with other programs option flags, it finds the flag but it just doesn't tab complete.

However tab completion works great for `cd` it finds folders and files with no issues.

![image](https://user-images.githubusercontent.com/10265682/83952952-4177e980-a802-11ea-8f51-9b3079f1e51e.png)

Any ideas how I can fix this? Or what am I doing wrong?

**Comment by faho** [comment]
This is simple: The `apt` completion script suppresses file completions under those conditions. The solution is also simple: If it can take files then, change the script to not do that then.

I wasn't aware that `apt` could directly install deb files, I only dimly remember that `apt-get` didn't, so you had to resort to `dpkg`.

And as it happens, in this case, the solution has already been committed as part of #6209.

**Comment by kodaman2** [comment]
Not sure I follow your response regarding apt completion script. In bash the above example autocompletes with no issues.

**Comment by gokulsoumya** [comment]
The complete builtin, used to register completions has a --no-files switch that disables file name completions for that specific completion. The completion for apt install has this option option and hence file name completions are not provided.

**Comment by kodaman2** [comment]
@gokulsoumya Thanks for the info. I'm running fish from head now and is all fixed.
