### ISSUE TITLE
Build Optional Packages not found CMAKE

### ISSUE THREAD

**Issue by kodaman2** [fish-shell/fish-shell#7091]
I was able to build from head fish, version 3.1.2-794-gc5e535e79. However the following message is given after cmake. I went and still did make, and make install and everything seems to be working, including my latest issue on apt tabbing. Awesome!

```
-- The following OPTIONAL packages have not been found:

 * BZip2
 * Readline
 * Editline

```
I know they are optional just not sure what functionality is lost if any, I do have bzip2 installed on my system. Are the other two python packages, or something else? I couldn't figure out how to install them.

![image](https://user-images.githubusercontent.com/10265682/83955471-e0a7db80-a818-11ea-89e2-544031f68954.png)

**Comment by ridiculousfish** [comment]
These are all coming from PCRE2 and aren't relevant for fish. Maybe there's a way to suppress them.

**Comment by ridiculousfish** [comment]
Let's just modify pcre's CMake files, it won't be a big deal I think.

**Comment by ridiculousfish** [comment]
Cleaned up in 783a895b1163149dc98d70c66f03748413998805 and 971f108bda140829ab273558ec4e1ed2828f3879. Thanks for filing.

**Comment by zanchey** [comment]
Added a reminder when importing new PCRE versions in https://github.com/fish-shell/fish-shell/wiki/PCREctomy
