### ISSUE TITLE
sudo apt autoremove --purge doesn't autocomplete

### ISSUE THREAD

**Issue by mvysny** [fish-shell/fish-shell#7095]
Thank you for such an amazing shell, awesome job!

I'm using Ubuntu 20.04 with fish 3.1.0, x86-64 kernel 5.4.0-33, gnome-shell terminal.

I'm used to remove packages via `sudo apt autoremove --purge package_name` but fish unfortunately doesn't auto-complete on package_name - pressing tab shows nothing unfortunately.

However, the functionality is there since typing `sudo apt purge pyth\t` auto-completes packages just perfectly.

Thank you again :)

**Comment by faho** [comment]
Yeah, simple issue: We haven't marked "autoremove" as taking packages.

Also a simple solution.

**Comment by mvysny** [comment]
Awesome, thank you so much for fixing the issue so super-quickly 🙏
