### ISSUE TITLE
Vi mode word separators should not include underscore.

### ISSUE THREAD

**Issue by dpacbach** [fish-shell/fish-shell#7098]
Fish version: 3.1.0.
OS: Linux

When in vi mode, the underscore appears to be considered a word boundary, so that e.g. when I hit 'w' it stops on underscores.  This is making vi mode hard to use for me because vi itself does not consider underscore to be a word boundary.  Can we change this?  Thanks

**Comment by faho** [comment]
Duplicate of #3285
