### ISSUE TITLE
Feature request: string pad

### ISSUE THREAD

**Issue by pmlandwehr** [fish-shell/fish-shell#7102]
Would it be possible to get a `string pad` function to complement `string trim`?  I realizing that padding can effectively be accomplished using things like`printf "%<n or negative n>s\n" $strs_to_pad | tr " " "<padding char>"`, but it seems like a natural extension.

I'm at fish, version 3.1.2 on Mac OS X

**Comment by m0nhawk** [comment]
I made an attempt to implement that. It works like that:

```
❯ ./fish -c "string pad -l -r -n 10 --chars c test"
cccccccccctestcccccccccc
❯ ./fish -c "string pad -l -n 4 --chars ' ' foo"
    foo
```

**Comment by ridiculousfish** [comment]
@m0nhawk apologies for long delay, I'd be happy to review your changes if you would like to open a PR! Let us know if you have questions about how to do so.
