### ISSUE TITLE
Default stderr-nocaret and qmark-noglob to ON

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#7105]
When we introduced feature flags in #4940, the understanding was that these aren't configuration knobs, but a deprecation mechanism - we don't support setting these online, only via universal variables or a commandline argument.

With that in mind, I think it's time to continue the deprecation process by defaulting some of these to ON instead of OFF, and allowing people to turn them off.

I propose enabling the following:

- stderr-nocaret - the removal of the `^` redirection
- qmark-noglob - the removal of the `?` single-character glob

for the next release, and removing the option after a year (the flag will still be available to be *queried*, but you won't be able to set it).

Ideally we'd also have `fish -n` warn about any uses of these so it's easier to find.

**Comment by zanchey** [comment]
This is going to break heaps of stuff, even if it's easy-ish to fix quickly by turning the flags back on. I think we need to telegraph loudly at least one release beforehand, so I think this would be best noted in the release notes for 3.2 as "this is the last release that they will be left at defaults".

stderr-nocaret is easy, qmark-noglob is harder to work around (I actually use it now and then though I recognised it's a real footgun).

**Comment by faho** [comment]
>qmark-noglob is harder to work around (I actually use it now and then though I recognised it's a real footgun).

What issues have you had?

AFAIR it's basically quoting all `?`. The only other problem is with `case`s including a literal question mark, which now *needs* to be tested. I don't think that happens too often?

**Comment by zanchey** [comment]
That is, I use `?` as a glob, and it's moderately tricky to replace (`*` is not as safe). My history says I use it much more as an escaped question mark than a glob though!

**Comment by faho** [comment]
Okay, how about enabling nocaret by default and trying to figure something out for globs before we remove `?`?

**Comment by zanchey** [comment]
See also #4394

**Comment by faho** [comment]
Alright, we have enabled stderr-nocaret by default, let's close this issue for that and revisit it for other flags.

**Comment by robey** [comment]
If you found this bug because fish started throwing errors in some of your scripts after the last update, the solution is to replace every `^` with `2>`.

That is, `^/dev/null` is now spelled `2>/dev/null`

(It would have been nice to deprecate with a warning before removing, but I guess it's too late now.)
