### ISSUE TITLE
Maybe CDPATH should be fish_cd_paths and universal?

### ISSUE THREAD

**Issue by dag** [fish-shell/fish-shell#711]
For consistency and convenience.  Optionally, keep CDPATH and have the new variable appended automatically, as with PATH and fish_user_paths.  Thoughts?

**Comment by krader1961** [comment]
Closing because this proposed change doesn't add any value other than perhaps some consistency with the `$fish_user_paths` variable. It certainly doesn't make the mechanism more "convenient".
