### ISSUE TITLE
Cannot call help using msys2

### ISSUE THREAD

**Issue by malobre** [fish-shell/fish-shell#7113]
_fish version 3.1.2_

Msys2 has the `cygpath` command but no `cygstart`.

This result in `cygpath` not being called:
https://github.com/fish-shell/fish-shell/blob/27f9920c7f3f0a7438f50f7a310003bfb67808ec/share/functions/help.fish#L139-L143

When no browser are set and since it doesn't find `cygstart` it defaults to `cmd.exe` however because `cygpath` is not called the path is wrong which make this : `/c/Windows/System32/cmd.exe /c 'start file:///usr/share/doc/fish/index.html'` fail.

Instead of exiting with an error it then returns to cmd, typing `exit` will return to fish:

![image](https://user-images.githubusercontent.com/1368457/84568922-0d14a800-ad83-11ea-80fd-b2a3dcaab3b4.png)

From my understanding this could be resolved by changing the code quoted above to this:
```fish
        if type -q cygpath
            and string match -qr 'cygstart|.*cmd\.exe' $fish_browser[1]
            set page_url file://(cygpath -m $__fish_help_dir)/$fish_help_page
```

I can submit a push request if needed.

Edit: I updated the regex from `cygstart|cmd\.exe` to `cygstart|.*cmd\.exe`

**Comment by malobre** [comment]
I found why it doesn't return to fish.

Msys convert this:
`/c/Windows/System32/cmd.exe /c 'start file:///usr/share/doc/fish/index.html'`
to this:
`C:/Windows/System32/cmd.exe C:/ 'start file:///usr/share/doc/fish/index.html'`

**Comment by zanchey** [comment]
That's wild.

Does that change actually help? I don't have MSYS2 installed, just the Git for Windows Bash, but when testing with `/c/Windows/system32/cmd.exe " /c" "start notepad.exe"` I get an error complaining about the quoting. Dropping the quotes around the second argument helps but I'm not sure how that works on other platforms.

**Comment by malobre** [comment]
Yes the quotes makes it work under msys2.

I will look for a solution later today. I think we might be able to check if we're running msys2 with an env variable and then do whatever is necessary.

**Comment by malobre** [comment]
Nevermind !

I had remove the second pair of quotes, could you test this:
`/c/Windows/system32/cmd.exe " /c" start notepad.exe`

It works with msys2 and with cmd directly, I think it should work with Git for Windows too.

**Comment by malobre** [comment]
I also noticed that dots are not escaped at multiple places (`.exe` instead of `\.exe`):
https://github.com/fish-shell/fish-shell/blob/27f9920c7f3f0a7438f50f7a310003bfb67808ec/share/functions/help.fish#L145
https://github.com/fish-shell/fish-shell/blob/27f9920c7f3f0a7438f50f7a310003bfb67808ec/share/functions/help.fish#L174
https://github.com/fish-shell/fish-shell/blob/27f9920c7f3f0a7438f50f7a310003bfb67808ec/share/functions/help.fish#L181

Is this voluntary? Should I update those when I make a PR for the previously mentioned changes ?

**Comment by krobelus** [comment]
> Should I update those when I make a PR

Sure, that can't hurt.
