### ISSUE TITLE
Idea: Alt-h on an alias-like function should show the manpage for the wrapped command.

### ISSUE THREAD

**Issue by MozzarellaM** [fish-shell/fish-shell#7116]
## Summary
The Alt-h binding (`__fish_man_page`) behaves in a somewhat unexpected manner when used on a function that shadows another command.

I think the binding should check if the given command is a function, then attempt to show the manpage for the command described by that function's `--wraps` parameter.

## Steps to Reproduce

Suppose the user uses `alias` to declare a `gs` function like the following:
```sh
function gs --wraps='git status' --description 'alias gs=git status'
  git status $argv;
end
```
The user types `gs` into the commandline, then presses Alt-h, expecting to see a help page which is relevant to the command they just typed.

Instead, they see `man gs`, which either doesn't exist, or describes a command which is unrelated to the thing they just typed. In this example, they see the manpage for GhostScript. 

## What should happen instead

In the above example, the user presumably expected one of the following three behaviors:

* Show the manpage for `git-status` (the value of `--wraps`)

* Show the definition for the function `gs`, so they can see what it does.

* Show nothing.

## Complications
In addition to this being an *extremely* minor enhancement, I'm not sure which of the above behaviors would be best. In the simple alias example, it would obviously be most helpful to simply parse the value of `--wraps='git status'`, and then show `man git-status`.

However, there isn't a clear distinction between a simple alias (like above) and a function with multiple side-effects that just happens to wrap another command so it can borrow its completions:

```sh
function git_update_then_show_status_paginated --wraps='less'
  git pull
  git status | less $argv
end
```

In this case, `man less` might be more confusing than the current behavior, which is to simply do nothing (unless we declared a manpage called `git_update_then_show_status_paginated`). The user would probably find it most helpful if they were shown the full definition of this function, but showing a function declaration rather than a manpage would violate the name and expected behavior of `__fish_man_page`.

Personally, I'm still in favor of the first solution (attempting to grep the value of `--wraps=""`, and show that manpage), then possibly using the second solution as a fallback for functions which don't have this parameter. As someone who uses a lot of aliases like this, this would be the most convenient solution for me personally.

However, the introduced ambiguity leads me to recognize that it might be a better solution to simply ignore Alt-h if the given command is a function, or to simply leave the behavior as-is.

---
Using fish 3.1.2 on macOS 10.15.5

**Comment by faho** [comment]
Yeah, like you said yourself, this is quite a task for rather little gain.

I think we're gonna pass. Thanks for the proposal regardless!
