### ISSUE TITLE
Change DNF available packages completions output

### ISSUE THREAD

**Issue by yursan9** [fish-shell/fish-shell#7118]
**Fish Version:**  fish, version 3.1.2

**Operating System:**  Fedora 32

Currently this is the output of available packages for DNF:
![image](https://user-images.githubusercontent.com/17114559/84610528-1027a980-aee5-11ea-8d37-8f622ffcc125.png)

It make running DNF  for installing a few packages a pain, because it will produce more lines than it need by outputting unneeded package's version.

This is the current code to get list of DNF packages:
```
sqlite3 /var/cache/dnf/packages.db "SELECT pkg FROM available WHERE pkg LIKE \"$cur%\"" 2>/dev/null
```

We can use awk to cut off the packages version number:
```
sqlite3 /var/cache/dnf/packages.db "SELECT pkg FROM available WHERE pkg LIKE \"$cur%\"" | awk -F '-' '{printf "%s", $1; for (i=2;i<NF-1;i++) {printf "-%s", $i}; print ""}' 2>/dev/null
```

**Comment by faho** [comment]
>We can use awk to cut off the packages version number:

Alternatively, we could not use awk, because that's

1. an external command

2. Another (weird) language

It is *super* fast, but that's not gonna an issue here.

Now, I'm not brave enough to use sqlite's string functions for this, but I'd use our own `string`.

What's the logic here? Everything after (and including) the second-to-last "-" is version number, epoch, fedora version, architecture?

Is this actually always true? Could the version number include a dash itself?

If it is okay, this would be something like

```fish
sqlite ... | string replace -r -- '-[^-]*-[^-]*$' ''
```

**Comment by yursan9** [comment]
It's always consistent.
And version number doesn't include dash.

Example:
```
gedit-colorscheme-gtksourceview-2-0-5.9120e9o.fc32.noarch
```

- The package name: `gedit-colorscheme-gtksourceview-2`
- Version: `0`
- The rest is fedora identifier

**Comment by faho** [comment]
> And version number doesn't include dash.

I can see that it doesn't *in this case*. But I'd love to have something that states that it *can't* or isn't allowed to.

Which it appears we have, in [Fedora's packaging guidelines](https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/#_upstream_uses_invalid_characters_in_the_version):

> It’s possible that upstream uses characters besides ASCII letters (upper and lower case), digits and periods in its version. They must be removed and potentially replaced with valid characters

It's possible for that to change, or for another distro to adopt DNF with different guidelines. To be honest, in that case DNF should be fixed to, you know, actually use sqlite properly and store the name separately.
