### ISSUE TITLE
When Running Fish With Git Aware Command Line Tooling Shell Hangs On Large Git Repositories

### ISSUE THREAD

**Issue by bonedaddy** [fish-shell/fish-shell#7119]
# Version Info

Fish version: v3.1.2
When running: `sh -c 'env HOME=$(mktemp -d) fish'` problem does not reproduce

# Problem Description

When using `fish` with a git-aware plugin, on repositories with large commit histories, or large files (particularly those using git lfs), the fish shell hangs and become very laggy, while also effect other existing active fish shells.

# Repro Steps

1) Use a git-aware theme or plugin
2) Download a large repository, ideally one using git lfs, and in this case `mozilla/DeepSpeech`
3) `cd` into the directory
4) Run any command, press the enter key, do anything
5) Current shell and all other shells will become slow and unresponsive

[video](https://gateway.temporal.cloud/ipfs/QmSKNmYgHq4xCn63pe1yuh3udeJcf1CGQbSobhDekdsPUN)

# Related

* https://github.com/oh-my-fish/theme-chain/issues/11

**Comment by faho** [comment]
Two things to note:

OMF does its own git-logic, and that theme uses it. In the past I've seen it do unnecessary git calls that made it slower than it needed to be. When it comes to that, there's nothing fish itself can do and you should talk to the OMF people.

Similarly:

>while also effect other existing active fish shells.

If it does that, then there's some logic in your configuration/omf that's waiting on other shells (e.g. via universal variables). Fish itself doesn't do that.

Again: Talk to the OMF people.

The general idea that the vcs prompts can be slow and are blocking is tracked in #6764, so I'm closing this as a duplicate.

**Comment by faho** [comment]
In addition, what hangs in your example is checking for "dirty" (i.e. modified) files, and in fish's own `fish_git_prompt` you can turn that off, even on a per-repo basis, by setting the `bash.showDirtyState` git config option (yes, that says "bash" for compatibility) or $__fish_git_prompt_showdirtystate.

Seeing the dirty state is *super useful* tho - it's probably the second most useful thing a git prompt can display, so turning it on by default is definitely the right decision.
