### ISSUE TITLE
Define what variable values count as "true"

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#7120]
We have a bunch of places where variables are used for configuration, and often they're used as booleans.

E.g. `__fish_git_prompt_show_informative_status` (yes, that's a handful) can be set, and turns on informative status by virtue of being defined.

However, using just the fact of it being defined has issues. For one, it's impossible to turn it *off* via a universal variable, and it's hard to turn it off globally (because you actually need to erase it instead of setting it). Also the choice to have something turned off can't really be differentiated from not having it set at all.

So instead I propose defining some standard set of values for a variable to count as "true" for the purposes of using it as a boolean, and adding a helper function or builtin (or possibly option to `set` or `test`) to test that.

If a variables actual *value* is to be used, that can of course still be done, and if it's unset we can still fall back to some default.

The question here is what the set of values should be? Just "1", which is the easiest check, or any non-zero or greater-than-zero number? Also strings like "Yes", "yes", "y", "j", "true"?

Using just "1" is simple and quick to test, using strings is friendly and compatible (e.g. with `git config`, which uses `true` as the true boolean).

**Comment by zanchey** [comment]
So my key concern here is that the logical (aha) values to use here - 0 for false, 1 for true - are exactly opposite to what `if` uses! Using `set foo (true)` is more consistent, but a lot more typing. Words and initials aren't localisable either, though my unilingual impression is that most Unix systems require at least intermediate English?

**Comment by faho** [comment]
Oh, no, using simple words and initials like "yes", "on" and "true" should be absolutely no problem - we already use `if`, `while`, `for`, `begin`, `end`, and of course the most important english word of all: `argparse`.

I've also thought about the difference with $status, but I don't think it's that large a problem. It boils down to what people intuitively use, and I *think* that's going to be 1 for true?

There's another point that makes this choice important, and that's backwards-compatibility. Because this, strictly speaking, isn't backwards-compatible. If people set the variable to a value that's now interpreted as falsy, the behavior would switch. If people already set these to `1` then the variable would remain being interpreted as truthy and they wouldn't have to change. (yes, this would have to be specifically called out in the release notes)

I think I'm going to check what people use.

**Comment by IlanCosman** [comment]
I've simply been using `test "$blah" = 'true'` as a substitute for proper booleans, which allows me to use universal variables. It would definitely be nice to have a more standardized approach across fish though.

**Comment by krobelus** [comment]
> test "$blah" = 'true'

`$blah` can be used instead if the variable is necessarily defined, otherwise it throws an error

**Comment by IlanCosman** [comment]
Coming back to this, something I only realized recently even after a year of Fish experience is that you can simple use 'true' and 'false', and they will be variable-substituted and then evaluated:

```fish
if $variableSetToTrueString
    echo hello
end
```

Unfortunately this will error if `variableSetToTrueString` isn't set, is empty, or is not true/false. If `if` simply evaluated no arguments to false, this would fit your criteria Fabian would it not? I agree though that it's pretty sketchy 😂

**Comment by faho** [comment]
>Unfortunately this will error if variableSetToTrueString isn't set, is empty, or is not true/false. If if simply evaluated no arguments to false, this would fit your criteria Fabian would it not?

For completeness: My criteria implicitly include not allowing code injection.

Trying to use `if $var` for this is a bad idea because it fundamentally relies on *running* code.

Imagine if someone `set -g variableSetToTrueString rm -rf ~/*` - on accident or not.

**Comment by faho** [comment]
We've done this now for git, and that's our big consumer.

I don't think there's a pressing need to do anything here.
