### ISSUE TITLE
fish_title is disabled for all Emacs terminal emulators

### ISSUE THREAD

**Issue by tazjin** [fish-shell/fish-shell#7122]
fish: version 3.1.0
OS: Debian rodete; NixOS 20.03

----------
Fish [disables](https://github.com/fish-shell/fish-shell/commit/cc205a134b7eb9858503cbffd8f110c67a83e2f3#diff-fe41d571fb2fd19af28d8b353b24cae5) the `fish_title` function if `INSIDE_EMACS` is set. However, Emacs has a variety of terminal emulators (for example [term](https://github.com/emacs-mirror/emacs/blob/master/lisp/term.el), [shell](https://github.com/emacs-mirror/emacs/blob/master/lisp/shell.el) and [vterm](https://github.com/akermu/emacs-libvterm)) which all set different values for `INSIDE_EMACS`.

At least in vterm, title setting works fine. The check in this function should probably explicitly check for the terminal emulator that is considered broken (it seems to be `term` afaict), rather than disabling this by default in all of them.

The `INSIDE_EMACS` string for term and its derivatives looks like `26.3,term:0.96` (first is Emacs version, second is term version).

**Comment by faho** [comment]
Tbh, all of these are basically too broken to use fish in.

You need numerous hacks to get anything even remotely approaching good output, the title is the least of your worries.

But yeah, sure.

**Comment by tazjin** [comment]
Wow, thanks for the quick fix!

> You need numerous hacks to get anything even remotely approaching good output, the title is the least of your worries.

That's not true. Yes, term is kind of broken (and known to be - afterall it's not unlikely that it's older than either of us) but other ones like vterm are perfectly fine. Emacs is an application development framework (which non-Emacsers often mistake for just a text editor) and there's a variety of applications for it, with differing levels of quality - just like on any other OS ;-)

**Comment by faho** [comment]
> That's not true. Yes, term is kind of broken

Both term and shell are broken in their default configuration with fish.

You'll find issues within a minute of using them.

I just tried out vterm and it seems to be okay.
