### ISSUE TITLE
job_summary.py:49: timeout from expect_re("[0-9]+:1:true|sleep 6:SIGKILL:Forced quit:[0-9]+:sleep")

### ISSUE THREAD

**Issue by norio-nomura** [fish-shell/fish-shell#7126]
On current master branch, interactive functionality tests fail on macOS with error:
```log
Testing interactive functionality
Testing file pexpects/bind.py ... ok (5 sec)
Testing file pexpects/bind_mode_events.py ... ok (0 sec)
Testing file pexpects/commandline.py ... ok (1 sec)
Testing file pexpects/complete.py ... ok (0 sec)
Testing file pexpects/exit.py ... ok (1 sec)
Testing file pexpects/fkr.py ... ok (1 sec)
Testing file pexpects/generic.py ... ok (0 sec)
Testing file pexpects/histfile.py ... ok (2 sec)
Testing file pexpects/history.py ... ok (0 sec)
Testing file pexpects/job_summary.py ... Failed to match pattern: [0-9]+:1:true|sleep 6:SIGKILL:Forced quit:[0-9]+:sleep
job_summary.py:49: timeout from expect_re("[0-9]+:1:true|sleep 6:SIGKILL:Forced quit:[0-9]+:sleep")


Escaped buffer:
\rprompt 6>\r\n⏎                                                                              \r⏎ \r\rprompt 7>\rprompt 7>true \rprompt 7>true \rprompt 7>true |\rprompt 7>true |\rprompt 7>true | \rprompt 7>true | \rprompt 7>true | sleep \rprompt 7>true | sleep \rprompt 7>true | sleep 6\rprompt 7>true | sleep 6\r\n

When written to the tty, this looks like:
<-------
prompt 6>
prompt 7>true | sleep 6                                                        

------->

Last 10 messages:
OUTPUT     636.56 ms (Line 28): 1:0:sleep 0.5 &:ENDED
 INPUT      +0.94 ms (Line 29): \n
OUTPUT      +6.71 ms (Line 30): \rprompt 4>
 INPUT      +0.72 ms (Line 34): false; sleep 10 &; true\n
OUTPUT    +105.80 ms (Line 36): \rprompt 5>
 INPUT      +1.08 ms (Line 37): kill -TERM $last_pid\n
OUTPUT    +104.93 ms (Line 39): 1:0:sleep 10 &:SIGTERM:Polite quit request
 INPUT      +0.56 ms (Line 40): \n
OUTPUT      +1.00 ms (Line 41): \rprompt 6>
 INPUT      +0.80 ms (Line 45): true | sleep 6\n

Testing file pexpects/pipeline.py ... ok (3 sec)
Testing file pexpects/read.py ... ok (0 sec)
Testing file pexpects/signals.py ... ok (2 sec)
Testing file pexpects/wait.py ... ok (4 sec)
1 test failed
make[3]: *** [CMakeFiles/serial_test_interactive] Error 1
make[2]: *** [CMakeFiles/serial_test_interactive.dir/all] Error 2
make[1]: *** [CMakeFiles/test.dir/rule] Error 2
make: *** [test] Error 2
```
Looking at the CI logs, it appears that these tests are not running correctly in both GitHub Actions and Travis-CI.
https://github.com/fish-shell/fish-shell/runs/781564433#step:6:426
> Testing interactive functionality
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'pexpect'
pexpect tests disabled: `python3 -c 'import pexpect'` failed
All interactive tests completed successfully

https://travis-ci.org/github/fish-shell/fish-shell/jobs/699413989#L1868
> Skipping interactive tests on macOS on Travis

**Comment by faho** [comment]
Please try rerunning the test, it's possible it's a bit flaky.

It succeeds on Github Actions (https://github.com/fish-shell/fish-shell/runs/784930040), I have no clue why it still doesn't run on travis.

**Comment by norio-nomura** [comment]
Apparently, this test fails if some of the options used to build homebrew are passed to `cmake`.
In my environment, the following command always fails with this issue.
> mkdir -p build && pushd build && cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_BUILD_TYPE=Release && make test; popd

**Comment by faho** [comment]
Can't reproduce on linux with those flags.

Note that we undo `-DNDEBUG` for CXX flags, so only the CFLAGS should have any effect.

**Comment by norio-nomura** [comment]
Thank you for the note and investigation.
After restarting Terminal.app, I can't reproduce this error in my environment anymore. So I am closing this issue.

**Comment by zanchey** [comment]
I can reproduce on macOS with a clean tree and `env -i PATH="PATH" TERM=TERM ninja test`, so I think there's probably something to this.

**Comment by faho** [comment]
`I can reproduce on macOS with a clean tree and env -i PATH="PATH" TERM=TERM ninja test, so I think there's probably something to this.`

@zanchey Do you mean `PATH="$PATH" TERM=$TERM`

**Comment by mqudsi** [comment]
I can reproduce on ElementaryOS.

**Comment by mqudsi** [comment]
Sorry, this test actually completes OK for me - it's a different test that times out every time on this PC!

**Comment by faho** [comment]
Okay, we're running the tests on Github Actions, I have seen this one a few times since but not for a while.

I'm assuming it's got enough slack now.
