### ISSUE TITLE
How to customize bind complete?

### ISSUE THREAD

**Issue by LumaKernel** [fish-shell/fish-shell#7131]
Or why not separate complete as normal function and complete function as input function?
Or `and` in `bind` is not working if combined with shell command.

```
$ fish --version
fish, version 3.1.2
$ echo $version
3.1.2
$ uname -a
Linux MyComputer 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
$ # Note: That is WSL2 on Windows10
$ echo $TERM
screen-256color
$ # Note: Working with tmux on Ubuntu on WSL2 on windows-terminal.
```

Tried `sh -c 'env HOME=$(mktemp -d) fish'` ? : Yes. Refer to the following.

My motivation is to make tab completion disable when the command-line is empty.

After reading the document, intuitively I came up with `bind \t "test -n (commandline -c)" and complete` but that doesn't work.

In the below record, I use `python` as an example to check tab completion. I'm hitting tab right after typing `pyt`.

Record: [![asciicast](https://asciinema.org/a/8bOVNMUynkKnHUsdh5MG3cXa9.svg)](https://asciinema.org/a/8bOVNMUynkKnHUsdh5MG3cXa9)

### Text script I used for the record

```
bind \t complete
# works

bind \t complete and complete
# works

bind \t "echo nya"
pyt
# works

true; and echo hi
bind \t true and complete
pyt
# not working... ?

bind \t ";complete"
pyt
# no...

# intuitively...
bind \t "test -n (commandline -c)" and complete

bind \t "test -n (commandline -c); and complete"
# no...
```

**Comment by gokulsoumya** [comment]
You can disable tab completion when the commandline is empty like so:

```fish
bind \t 'test -n (commandline); and commandline -f complete'
```

**Comment by LumaKernel** [comment]
It works! Thank you.
