### ISSUE TITLE
unalias does not seem to remove an alias

### ISSUE THREAD

**Issue by EdmundsEcho** [fish-shell/fish-shell#7132]
### Description

My config included an alias that I wanted to remove.  This is what I did:

*  Deleted the entry in the config file
* Sourced the config file `.    /path/to/config`
* Ran `unalias getRidOfAlias`
* Ran the `alias` command... the `getRidOfAlias` remained
* Ran the `getRidOfAlias` and it still was pointing to what I wanted to delete
* Searched duck-duck-go for a solution; searched the fishshell docs with no avail

### Expected behavior

* Once I deleted and resourced the shell, I would have expected the alias not to show up in the list of aliases.

* Run the `unalias` command and witness the removal of the alias in the list of aliases.

*  Find documentation on the matter in the alias section of the fishshell docs :-) 

Thank you for letting me know how to proceed.

\- E

PS: the requested information was provided inside the  tags.

**Comment by faho** [comment]
Fish does not have an `unalias` command.

For that matter, it does not have "aliases", but merely functions. `alias` is itself a function that defines functions. Run `functions --erase` to erase a function.

**Comment by EdmundsEcho** [comment]
Thank you! Your answer was spot-on.

Just to clarify, per the original post, `alias` worked as expected.  I inferred the opposite of that function would also be supported.  There is even a fish-shell issue that describes the use of `unalias`.  Just maybe, it might be useful to describe how `functions --erase <alias>` is used instead of what newcomers might expect from `unalias`.

### Solution

* call `functions --erase getRidOfAlias`
* confirm the removal of the alias by running `functions -n`

Thank you again.

\- E

**Comment by JamesBissick** [comment]
functions --erase AliasName only temporarily erase that alias.
How do we permanently erase it?

**Comment by septatrix** [comment]
> To permanently remove aliases:
> 
> cd ~/.config/fish/functions
> 
> find the alias you want to remove and rm aliasName.fish

The documentation indicates that `functions --erase myalias` followed by `funcsave` should also do the trick but that does not seem to work?

**Comment by ridiculousfish** [comment]
Please file a new issue with repro steps instead of necroing closed issues.
