### ISSUE TITLE
Fish GPG Key make apt-key add fail 

### ISSUE THREAD

**Issue by Stig124** [fish-shell/fish-shell#7134]
Hello,
I tried to install the gpg for the official Docker Repo, but when I try to do 
```bash
curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
```
It fails, printing that error
```bash
gpg: invalid key resource URL '/tmp/apt-key-gpghome.HikFIVpkoI/shells:fish:release:3.asc.gpg'
gpg: keyblock resource '(null)': General error
gpg: key DC30D7C23CBBABEE: 4 signatures not checked due to missing keys
gpg: key 4DFAB270CAA96DFA: 4 signatures not checked due to missing keys
gpg: key DCC9EFBF77E11517: 2 signatures not checked due to missing keys
gpg: key 7638D0442B90D010: 4 signatures not checked due to missing keys
gpg: key 9D6D8F6BC857C906: 4 signatures not checked due to missing keys
gpg: key CBF8D6FD518E17E1: 2 signatures not checked due to missing keys
gpg: key E0B11894F66AEC98: 5 signatures not checked due to missing keys
gpg: key EDA0D2388AE22BA9: 5 signatures not checked due to missing keys
gpg: key EF0F382A1A7B6500: 2 signatures not checked due to missing keys
gpg: key 2CE2AC08D880C8E4: 1 signature not checked due to a missing key
gpg: Total number processed: 16
gpg:       skipped new keys: 16
```
I tried removing `/tmp/apt-key-gpghome.HikFIVpkoI/shells:fish:release:3.asc.gpg` file, but at each time I run `apt-key add -` it makes a new folder and fails indefinitly, even in bash shell
I didn't tried yet to remove the fish key (added by the official instruction on the download page)
I'm on Debian 10, `4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux`
Fish 3.1.2

**Comment by Stig124** [comment]
UPDATE :
You need to actually remove or rename the `/etc/apt/trusted.gpg.d/shells:fish:release:3.asc` in order to `apt-key add` to work then put it back
I'll test asap if this issue is global or just linked to Docker GPG key

**Comment by zanchey** [comment]
Probably `gpg --show-keys /etc/apt/trusted.gpg.d/shells:fish:release:3.asc` or `file /etc/apt/trusted.gpg.d/shells:fish:release:3.asc` will be useful.

The contents should be:

```
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v1.4.5 (GNU/Linux)

mQENBFJUIeUBCADc62ZBGiIY3OWWSs7hj4TWrHARq43mjxuwqN9XLi/bdDXLDpfZ
NAH+8CcgB0eSDjBuNkZcCk17nCuVru3XJp/CEpJoK0MvsJg/nGM5BaDqeXpgat36
llvqSvs9u3C1vgEbR9Ct+aQa73WNP6WQsDVuPDw1T5F9iMo3PhoeBYA5FCmp+Y/Z
6kP4HUrXZcu7PWwwRkQzvvGjodfH6j2d7oYBJvXqkaiDlKc8qrTZOSqMSqeWz6QB
s/y1MNszh490vatbirieEroRaNINHewjcXvBJQfoO/Nl/hDjWD7XrJWPpi34dH58
9IGXLS9Qb6GYnisAjwhCyhCXa4Rsse4jo1cXABEBAAG0OHNoZWxsczpmaXNoIE9C
UyBQcm9qZWN0IDxzaGVsbHM6ZmlzaEBidWlsZC5vcGVuc3VzZS5vcmc+iQE8BBMB
AgAmBQJeNtJZAhsDBQkQAWB0BgsJCAcDAgQVAggDBBYCAwECHgECF4AACgkQLOKs
CNiAyOSw8AgAweDMF8ffBo/w031frF4ne9NToP3U44P6tiN090nS8cgHF1RThJgb
hZyNM/hjnjpgrqr5LmBIp4UXZz4SysjgDGtXJD9AUBg/GpxUtJopxn0lPznz3bWZ
eB3KyBOO4KMnrDCmGZdF0qDgKnclSFZV4BsaSDNQtMghwYnDmcDB+tIbuuCSq4k7
rH8BAmlK4ZwgpgGNp8tuct6VOs9Sh0xJr/G0iVOW+dBgsDaIgA9kM/+Jjt/+WZYq
WQfNf7Jb154o1x1k3wBBU3afAQbZTjxnGrxfcUW5HtdqA6z4/EKKNl+QPVcsaQlq
BedT9tfXH+d2LO308KUXeoYT6pCbnclB3IhGBBMRAgAGBQJSVCHlAAoJEDswEbdr
nWUjYg4An0xyb6ofXvNifTCINq/aE4ArH1XgAKCgjoMJ2Wjo8RVSgkSOaQvK6uPq
eQ==
=7z/F
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by Stig124** [comment]
Before I'll reinstall the key using 
```bash
sudo wget -nv https://download.opensuse.org/repositories/shells:fish:release:3/Debian_10/Release.key -O "/etc/apt/trusted.gpg.d/shells:fish:release:3.asc"
```
Outputs are :
`gpg --show-keys /etc/apt/trusted.gpg.d/shells:fish:release:3.asc` reads :
```bash
gpg: keybox '/home/stig124/.gnupg/pubring.kbx' created
pub   rsa2048 2013-10-08 [SC] [expires: 2022-04-12]
      24A63B31CAB41B33EC48801E2CE2AC08D880C8E4
uid                      shells:fish OBS Project <shells:fish@build.opensuse.org                                                                                                                              >
```
and 
`file /etc/apt/trusted.gpg.d/shells:fish:release:3.asc` reads :
```bash
/etc/apt/trusted.gpg.d/shells:fish:release:3.asc: PGP public key block Public-Key (old)
```
And this is the same after a clean reinstallation

**Comment by idnsunset** [comment]
I encountered very similar issue as yours several days ago. It seems not the issue of shell but the **gpg** command does not support the filename supplied to gpg's `--keyring` option containing colon.

If you look into apt-key source code (a shell script), comands like `apt-key list`, `apt-key add` all supply the key filenames to gpg's  `--keyring` option.

**Comment by mqudsi** [comment]
Nice catch, @idnsunset. It looks like the colon is causing the path to be parsed as a scheme+url.

@Stig124 can you try with a hyphen instead of the colon and let me know if we can close out this issue?

**Comment by faho** [comment]
No response, so I'm assuming it works. Let us know if it doesn't!

**Comment by Stig124** [comment]
I installed a new machine, Debian 10 too, same issue, but a more descriptive error :
```
gpg: invalid key resource URL '/etc/apt/trusted.gpg.d/shells:fish:release:3.gpg'
gpg: keyblock resource '(null)': General error
```

**Comment by Stig124** [comment]
> Nice catch, @idnsunset. It looks like the colon is causing the path to be parsed as a scheme+url.
> 
> @Stig124 can you try with a hyphen instead of the colon and let me know if we can close out this issue?
This is the solution, you need to change the `:` to `-` to make it work

**Comment by zanchey** [comment]
I've reported this to the maintainers of software.opensuse.org and provided what I hope is an acceptable patch.

Thanks for helping track this down!

I note that the `apt-key add` interface is deprecated but that `apt-key list` just fails silently.

**Comment by zanchey** [comment]
Fixed upstream with https://github.com/openSUSE/software-o-o/pull/843
