### ISSUE TITLE
Feature request: forget bad commands

### ISSUE THREAD

**Issue by boxed** [fish-shell/fish-shell#7149]
Fish often auto completes commands that I screwed up, and I keep pushing them into my history over and over. It seems to me like commands that were unsuccessful and that are like a day old or something, could be ignored by the auto complete. Or something, it's still a bit of a crazy idea :P

**Comment by damani42** [comment]
No, it's not crazy, I think it's seems a good idea.

**Comment by faho** [comment]
It's such a good idea that it came up *early* - #5.
