### ISSUE TITLE
Binding CTRL-Z

### ISSUE THREAD

**Issue by kosayoda** [fish-shell/fish-shell#7152]
Version & Other Details:
```
fish, version 3.1.2
Linux 5.7.2-arch1-1 x86_64 GNU/Linux
xterm-256-color
```
Issue:
Is there currently a way to bind `CTRL-Z`? #1879 led to `stty` stuff in three other eventually closed issues that I don't understand. Thanks in advance!

**Comment by zanchey** [comment]
The short answer is no - Ctrl-Z is intercepted by the terminal (well, the line discipline) and never forwarded as a keystroke to fish.

You'll see this if you run `fish_key_reader` - pushing Ctrl-Z produces no response.

The longer answer is yes, _if_ you alter the terminal's character for sending the suspend signal to something else:

```
> stty susp '^N'
> fish_key_reader
Press a key:
              hex:   1A  char: \cZ
bind \cZ 'do something'
```

(but now you can't use Ctrl-N for a keybinding)

**Comment by kosayoda** [comment]
Thanks for the reply!

> \> stty susp '^N'

This does not seem to work on my side, any idea why?
```shell
$ stty -a
speed 38400 baud; rows 22; columns 104; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>;
start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl -ixon -ixoff -iuclc -ixany -imaxbel
-iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho
```
Running `stty susp '^N'` does not reflect in `stty -a`.

**Comment by zanchey** [comment]
Oh, sorry, that won't work in 3.1.2 because 29754f35402fb isn't in a released version yet. You'd have to do something like `stty susp '^N'; fish` to start a new shell with the new modes, which is awful I'm afraid. `exec fish` resets the modes :-(

**Comment by faho** [comment]
Is there a particular reason why we leave this enabled inside fish, at all? AFAICT we ignore the signal anyway?

**Comment by faho** [comment]
Yeah, we already ignore SIGTSTP unconditionally inside fish, so we can just disable the key mapping to free it up for our use.

**Comment by krobelus** [comment]
Sweet, thanks @faho!

Should we bind it to `undo`? (In addition to `Ctrl+_`?) That could be what users expect these days.
We don't want to bind `Ctrl+Y` to `redo` but I'd be fine with this inconsistency since redo is much less important.

**Comment by faho** [comment]
>Should we bind it to undo? (In addition to Ctrl+_?) 

Sounds good.

**Comment by zanchey** [comment]
> Yeah, we already ignore SIGTSTP unconditionally inside fish, so we can just disable the key mapping to free it up for our use.

🤯

**Comment by kosayoda** [comment]
o/ Thanks @faho!
To anyone coming here looking to bind `CTRL-Z` to put the last suspended job to the foreground, here's one way to do it:
```fish
 function fish_user_key_bindings
    bind \cz 'fg 2>/dev/null; commandline -f repaint'
 end
```

- `2>/dev/null` removes the `Send job X, “PROGRAM” to foreground ` message, omit that if you wish to keep it.
- `commandline -f repaint` tells fish to redraw the prompt to avoid weird cursor position issues.

**Comment by endersstocker** [comment]
@faho This was working, but it seems to have regressed.

**Comment by krobelus** [comment]
@endersstocker works for me. It's probably best to ask on [gitter](https://gitter.im/fish-shell/fish-shell) or open a new issue if the problem persists.

**Comment by faho** [comment]
Works for me, too.

Please make sure you're running a fish after 3d2dc856ab16e53beb8c0e0740b7233181b6f780 (i.e. a build from git, *not* the latest release 3.1.2). If you can still confirm with that, ideally da0acb28b (current git master), your operating system would be great to know - 90d8df8128e5aaa32c53370188d4ce4ef07407cc changed this to use _POSIX_VDISABLE (but special-cases the "not supported" value), so it's possible your OS is broken.
