### ISSUE TITLE
fish_config web interface not loading

### ISSUE THREAD

**Issue by succerror** [fish-shell/fish-shell#7158]
### `fish_config` is opening a tmp file on the browser but fails to start the web server

fish, version 3.1.2
OS: Arch Linux x86_64
Kernel: 5.6.13-arch1-1
Terminal: rxvt-unicode-256color
BROWSER env: firefox-developer-edition
python: Python 3.6.8

Steps to reproduce the problem:
```
$ sudo pacman -S fish
$ fish
$ fish_config
```
This will open a tmp file `file:///tmp/web_configsomehashhere.html` on the browser(here `firefox-developer-edition`) which is supposed to Meta Refresh to a local web server but it just keeps loading.

I've figured the issue is with [this line](https://github.com/fish-shell/fish-shell/blob/master/share/tools/web_config/webconfig.py#L1505) responsible for opening the browser which is not returning until the browser is closed and blocking the web server from handing the request.

I've tried changing the code to open browser in a separate thread using `threading` lib and it worked.

**Comment by faho** [comment]
If that line is blocking, then your system is misconfigured. This ordinarily does not block, so you should make it so your system doesn't.

I'd check e.g. $BROWSER.

**Comment by succerror** [comment]
> If remote browsers are not available on Unix, the controlling process will launch a new browser and wait

I found this in here https://docs.python.org/3/library/webbrowser.html

Looks like the behavior of `webbrowser.open` is different for different situations

Below is for `firefox-developer-edition`
- If the browser window is already open, it exits after opening a tab
- If the browser is not open at all, it opens a browser window and waits until its closed

I noticed same behaviour in newly installed `manjaro` with `palemoon` browser

**Comment by faho** [comment]
Okay, it seems like you're not using a "remote browser" (what an awful term). You should..

You're doing the equivalent of calling `firefox --no-remote`, which is just more annoying for everyone involved.

(note: If this was in any way common, we could be hacking around it. But since it's not, you should instead fix your config)

**Comment by succerror** [comment]
> You're doing the equivalent of calling firefox --no-remote

No I'm not. In fact the problem is when there is no browser running at all.
I think **_remote browsers_** means a browser which can accept remote commands.

FYI:
```
~ > cat (which (echo $BROWSER))
#!/bin/sh
exec /usr/lib/firefox-developer-edition/firefox "$@"
```

---
If I manually open the browser before running `fish_config`, it works as expected.

Does that means that the user have to open the browser before running `fish_config`? I don't think they have to.

**Comment by faho** [comment]
>Does that means that the user need to have the browser open before running fish_config? I don't think they have to.

So, when I do

```fish
python -c 'import webbrowser; webbrowser.open("https://www.python.org")'
```

This opens firefox, even if it is not running, and the python process exits. This is how I've always known it and we've not gotten any other bug reports about it.

In your case, that's broken, for some reason. Possibly because of configuration in your browser. That would have to be fixed.

**Comment by faho** [comment]
Ahahahaha, yeah, it's a firefox-developer-edition thing (meaning it'll possibly show up in newer firefoxen)

Yeah, we have to work around this. Blergh
