### ISSUE TITLE
[Feature request] Use 'open' command without typing it

### ISSUE THREAD

**Issue by adnion** [fish-shell/fish-shell#7165]
I'd like to open files by their names only. Any advice is highly appreciated.
https://stackoverflow.com/questions/38383414/always-open-a-txt-file-using-specified-app-in-fish-shell
https://unix.stackexchange.com/questions/5055/execute-a-file-in-an-application-based-on-the-files-extension-in-bash

**Comment by faho** [comment]
No, thanks.

This is an awful feature and should not be supported, the potential for confusion is too great.

**Comment by adnion** [comment]
I understand your point and maybe you're right. 
However I'd find it helpful.

I can think of rebinding the enter key to a custom function. If anyone has a clever solution please tell me.

**Comment by faho** [comment]
```fish
function maybe-open
    set -l cmdline (commandline -o)
    # If we only have one token...
    if not set -q cmdline[2]
        # ... and it is a file...
        if test -f "$cmdline[1]"
            # ... prepend "open"
            commandline -r -- "open $cmdline"
        end
    end
    # Execute whatever is there
    commandline -f execute
end

bind \r maybe-open
```

**Comment by adnion** [comment]
This was unexpected. Thank you so much for your time and effort!
