### ISSUE TITLE
[feature request] Sort completions for `git switch` in most recently used order

### ISSUE THREAD

**Issue by sanga** [fish-shell/fish-shell#7168]
Against fish version 3.2.1. Completions for git switch are currently in alphabetical order. To me it would seem to be more reasonable to instead be in most recently used order - rationale being that generally people will be actively working on and switching between a couple of WIP branches (?). Changing the completion to be instead MRU shouldn't be terribly difficult I guess (I have git alias to do that already), so I could make a PR to do this, but I thought it would make sense if this is a good idea or not before polishing that up. Is this a good idea or not?

**Comment by faho** [comment]
Thanks for the proposal, I don't think it's a good idea.

We don't want the ordering to change between calls. 

(yes, I do despise MRU ordering in general) 

For switching back and forth there is `git switch -` and the suggestion should pick it up.
