### ISSUE TITLE
Buggy repainting when switching directory with keybinding

### ISSUE THREAD

**Issue by terlar** [fish-shell/fish-shell#717]
I have added the following key binding to switch directories conveniently:
```sh
function fish_user_key_bindings
  bind \e'<' 'prevd; commandline -f repaint'
  bind \e'>' 'nextd; commandline -f repaint'
end
```

First it looks like this:
![screen shot 2013-05-08 at 08 38 07](https://f.cloud.github.com/assets/280235/475995/e2581fd2-b7aa-11e2-931b-23ab60e48a70.png)

But when pressing `Alt-<` to go up one directory it looks like this:
![screen shot 2013-05-08 at 08 38 27](https://f.cloud.github.com/assets/280235/475996/e493a262-b7aa-11e2-96f5-27b47db09b1d.png)

**Comment by faho** [comment]
This works for me now.

**Comment by ridiculousfish** [comment]
Ok, let's close. Thanks!

**Comment by szhu** [comment]
This can be fixed by issuing a escape sequence that tells the terminal to clear the whole line where the prompt is about to be drawn. Place this before the printing of each new line in your `fish_prompt`:

```fish
echo -ne '\033[K'
```
