### ISSUE TITLE
Update ImageMagick completions

### ISSUE THREAD

**Issue by sorairolake** [fish-shell/fish-shell#7172]
In ImageMagick 7 or later, legacy commands have been replaced with `magick`. The current completions are only valid if there is a symbolic links for compatibility.
Therefore, I think it would be better to update completions to support `magick` and it's sub-commands for compatibility.

See: [Command-line Tools](https://imagemagick.org/script/command-line-tools.php) and [Porting to ImageMagick Version 7](https://imagemagick.org/script/porting.php)

**Comment by faho** [comment]
Hallelujah! My prayers have been answered!

**Comment by mqudsi** [comment]
Just to be clear, we're not *removing* the completions for `convert` and co, right?

**Comment by faho** [comment]
Definitely not. It's gonna take ages until those aren't used anymore.

**Comment by EmilyGraceSeville7cf** [comment]
I can try to close this issue by sending one or more PRs.
