### ISSUE TITLE
gettext underscore does not parse successfully

### ISSUE THREAD

**Issue by xaverdh** [fish-shell/fish-shell#7177]
fish should correctly parse its own language, but:

`fish -n -c '_ hello'` outputs:
```
fish:
_ "echo"
^
```
while `fish  -c '_ hello'` runs just fine.

```
fish --version: fish, version 3.1.2
(running on NixOS)
```

**Comment by faho** [comment]
Duplicate of #977

**Comment by xaverdh** [comment]
right, sorry for the noise!
