### ISSUE TITLE
How to install brew on Ubuntu WSL2?

### ISSUE THREAD

**Issue by tonywei92** [fish-shell/fish-shell#7178]
```
fish, version 3.1.0
Linux DESKTOP-G6BRSIC 4.19.84-microsoft-standard #1 SMP Wed Nov 13 11:44:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
xterm-256color
```
I tried install with following command (from https://brew.sh/) :
```
⋊> /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fish: $(...) is not supported. In fish, please use '(curl)'.
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
```

Is there solution/workaround? or Is there any Fish wrapper for Brew?
All I can find is https://www.brewfish.net/

**Comment by zanchey** [comment]
Try `curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh | /bin/bash`.

**Comment by mqudsi** [comment]
I'm curious as to why you would use homebrew instead of apt?

**Comment by tonywei92** [comment]
@zanchey Thank you that's working
I also have to put below command to [profile](https://fishshell.com/docs/current/faq.html#how-do-i-run-a-command-every-login-what-s-fish-s-equivalent-to-bashrc-or-profile)
```
eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
```
So brew is available to global

@mqudsi That's a personal preference, I just love it.

**Comment by zanchey** [comment]
I did suggest to the Homebrew maintainers that they might prefer a more portable install command, but their response is that anyone who is able to install a new shell should be able to translate the command themselves.
