### ISSUE TITLE
Buggy display when using Alt-l (__fish_list_current_token)

### ISSUE THREAD

**Issue by terlar** [fish-shell/fish-shell#718]
If you have one line prompt it is kind of okay, but it would be better if the list started on the next line.

![screen shot 2013-05-08 at 09 26 50](https://f.cloud.github.com/assets/280235/476089/b3898aaa-b7b0-11e2-86c2-9d5fb0485a41.png)

This can be solved like this, but would be good if it was default behavior.
```sh
  bind \el 'echo; __fish_list_current_token'
```

However if you have a multi-line prompt it looks like this:
![screen shot 2013-05-08 at 09 31 35](https://f.cloud.github.com/assets/280235/476105/5a43bc8a-b7b1-11e2-8b8b-9fb192f52d48.png)

As you can see the prompt is covering the output which is not very useful.

**Comment by michael-younkin** [comment]
Is there a reason this hasn't been looked into for two years? If it's just an issue of finding someone to fix it, maybe I can take a crack at it?

**Comment by ridiculousfish** [comment]
Yup, that's all. If it's biting you, go for it!
