### ISSUE TITLE
Running `fish -c '<script>'` shows a bunch of weird/hidden characters

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#7181]
Following up from an odd issue I found in `fish` while testing VirtualFish (https://github.com/justinmayer/virtualfish/issues/177#issuecomment-654841214)...

![image](https://user-images.githubusercontent.com/8544900/86794824-d6217180-c064-11ea-997d-80c51362cd8a.png)

Any idea where these additional hidden characters are coming from?

**Comment by zanchey** [comment]
My guess is that your `config.fish`, or something else in your startup, writes to the terminal in non-interactive mode. Have you tried with `env HOME=(mktemp -d)`?

**Comment by zx8** [comment]
Turns out this was caused by running [`tabs -4`](https://superuser.com/questions/110421/tab-character-width-in-terminal) in a `conf.d/` startup script. I have wrapped it in a `if status --is-interactive` block now and all's well.
