### ISSUE TITLE
Passing options to command's COMMANDNAME argument

### ISSUE THREAD

**Issue by mliudev** [fish-shell/fish-shell#7184]
fish, version 3.1.2
Linux servalWS 5.7.7-arch1-1 #1 SMP PREEMPT Wed, 01 Jul 2020 14:53:16 +0000 x86_64 GNU/Linux
Terminal: alacritty 0.4.3

Reproduction:

```
/h/m> command -q ssh-add -l
command: Unknown option “-l”

(Type 'help command' for related documentation)
/h/m [2]>
```

Is there a way to pass options to the COMMANDNAME argument of the `command` command? I did a brief googling and search of the issues but I found it hard to properly describe the problem in a search engine friendly manner.

**Comment by faho** [comment]
1. The same way you inhibit *any* option parsing - with a `--`

2. You don't want `command -q` if you're going to pass any options. That only *checks* if a command by that name exists, and the command is just called `ssh-add`, not `ssh-add -l`.

3. If you don't do `command -q` it already doesn't read any options after the first non-option, `command ssh-add -l` should just work.

So:

Either you want to check if a `ssh-add` command exists and you just want `command -q ssh-add`, or you want to execute the ssh-add command with the argument `-l` and so you can just do `command ssh-add -l`.

**Comment by zanchey** [comment]
Assuming this has been answered.
