### ISSUE TITLE
on every `cd` I get  `wc` errors.

### ISSUE THREAD

**Issue by 5c0tt-b0t** [fish-shell/fish-shell#7188]
```bash
✦2944 ❯ cd git/                                                12:58:28
wc: git/: Is a directory
Integer 0 in '0 git/' followed by non-digit
/data/data/com.termux/files/usr/share/fish/functions/cd.fish (line 7):
    if test (count $argv) -gt (test "$argv[1]" = "--" && echo 2 || echo 1)
       ^
in function 'cd' with arguments 'git/'

~/git
✦277 ❯ cd ..                                                   12:58:44
wc: ..: Is a directory
Integer 0 in '0 ..' followed by non-digit
/data/data/com.termux/files/usr/share/fish/functions/cd.fish (line 7):
    if test (count $argv) -gt (test "$argv[1]" = "--" && echo 2 || echo 1)
       ^
in function 'cd' with arguments '..'
```

**P.S** THANK YOU SO MUCH FOR THIS AMAZING, UNIQUE (AND FAST!) SHELL.
Have heared alot, thought I'd check it out finally...
**Verdict?...** I wanna kick ZSH's slowww-ass ways and convert to full-time-fish! please help me!

**Comment by faho** [comment]
It appears you have a function called `count`, which conflicts with our
built-in of the same name. Rename it.

5c0tt-b0t <notifications@github.com> schrieb am Do., 9. Juli 2020, 14:05:

**Comment by 5c0tt-b0t** [comment]
That worked perfectly THANK YOU!
**Really** enjoying fish shell, its amazing!
Still getting used to certain things but the speed & efficiency of this is incredible. Honestly thank you for the quick response too, its appreciated. Have a great day!
