### ISSUE TITLE
Why does test -n treat zero arguments as non-empty?

### ISSUE THREAD

**Issue by yujiri8** [fish-shell/fish-shell#7192]
`test -n` exits 0. `test -n ''` exits 1. `test -n ' '` exits 0.

I think this might be intentional as an example in the `test` doc says:
```
If the variable MANPATH is defined and not empty, print the contents. (If MANPATH is not defined, then it will expand to zero arguments, unless quoted.)

if test -n "$MANPATH"
    echo $MANPATH
end
```
Which would suggest that zero arguments are intentionally treated as non-empty; however, the definitions of the `-n` and `-z` flags in the same doc say:
```
-n STRING returns true if the length of STRING is non-zero.

-z STRING returns true if the length of STRING is zero.
```
Additionally, `test -z` with no arguments *also* exits 0, indicating that it does think of zero arguments as zero length. I find it very confusing that `-n` and `-z` can both return true for the same input, given the above definitions.

Incase it's not intentional:

Version: 3.1.2
FreeBSD 12.1-RELEASE-p6
xfce4-terminal
$TERM: xterm-256color

I tried checking downloading the repo and building from source to make sure I had the latest version, and running without third-party customizations by executing `sh -c 'env HOME=$(mktemp -d) fish'`. The behavior persisted.

**Comment by faho** [comment]
Because POSIX says so.

`test` is one of the few parts of fish to actually follow it. Personally I consider that a mistake but we can't change it now.

What we're gonna do instead is to make a *replacement*, see #6124.

**Comment by ridiculousfish** [comment]
Yeah, POSIX says that if there is one argument, to "Exit true (0) if $1 is not null; otherwise, exit false".
