### ISSUE TITLE
Documentation: superfluous backtick

### ISSUE THREAD

**Issue by blinry** [fish-shell/fish-shell#7195]
On [this page](https://fishshell.com/docs/current/index.html#shebang-line), Chromium renders an additional backtick:

![image](https://user-images.githubusercontent.com/81277/87438515-ebac1380-c5ef-11ea-81d5-4f43cfa4307b.png)

I'm not sure why, it's not in the [source code](https://raw.githubusercontent.com/fish-shell/fish-shell/master/doc_src/index.rst). Is this a reStructuredText bug?

**Comment by zanchey** [comment]
This was fixed in 1634a3b15c and isn't in the live documentation yet - but thanks for checking!
