### ISSUE TITLE
std::vector reallocated multiple times in a loop

### ISSUE THREAD

**Issue by nadavrot** [fish-shell/fish-shell#7201]
In the file src/ast.cpp, in the method 'void populate_list(...)', on line 890:
 
std::vector<std::unique_ptr<ContentsNode>> contents;

The vector is reallocated multiple times as it grows. It grows about 5-6 times on average. The method is called frequently. I suggest reserving a constant size of something like 32-64 elements, before entering the loop.

**Comment by ridiculousfish** [comment]
Hey, there's a familiar face! This is neat, how did you find this?

A lot of times the vector will be empty. Maybe `reserve()` as soon as we know it will be non-empty?
