### ISSUE TITLE
Shortcut to delete a line from a history

### ISSUE THREAD

**Issue by AlexWayfer** [fish-shell/fish-shell#7203]
Please, add a shortcut to delete a line from a history.

For example, I've mis-typed something:

```
> git puhs
git: 'puhs' is not a git command. See 'git --help'.

The most similar command is
	push
```

Instead of doing `Arrow Up` + `Home` + typing `history delete `, I'd like to press some shortcut.

---

```
> fish --version
fish, version 3.1.2
```

```
> uname -a
Linux Alex-ArchMainPC 5.7.8-arch1-1 #1 SMP PREEMPT Thu, 09 Jul 2020 16:34:01 +0000 x86_64 GNU/Linux
```

> Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:
>
>  sh -c 'env HOME=$(mktemp -d) fish'

Doesn't work:

```
> sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
alex@Alex-ArchMainPC /h/a/P/r/r/r18n-rails (master)>
```

**Comment by faho** [comment]
```fish
bind \cg 'history delete --exact --case-sensitive -- $history[1]'
```

This binds control-g to something that deletes the last element of history.

**Comment by AlexWayfer** [comment]
> ```fish
> bind \cg 'history delete --exact --case-sensitive -- $history[1]'
> ```
> 
> This binds control-g to something that deletes the last element of history.

OK, thank you. But I not always want to delete the last element of history. I may be busy with a set of commands, do a job, and only then delete some failing command from the middle of this set.

But your example forwarded me to abbreviation like:

```fish
abbr -a hd 'history delete --exact --case-sensitive --'
```

With it I can go (via arrow keys) to specific command, press `Home`, then type `hd` and `Space`. Not a shortcut, but shorter way.

But! I've tried to test it with `echo $history[1]` (just checked how it looks) and, sadly, it was not successful because of variables interpolation. So, for exact working I should add single quotes, and this becomes complicated.

So… I still wish a simple shortcut (or bindable fish function) to just delete an entered line (text) from the history.

**Comment by faho** [comment]
Okay, try this:

```fish
function forget
    set -l cmd (commandline | string collect)
    history delete --exact --case-sensitive -- $cmd
end

bind \cg forget
```

navigate to whatever you want to remove and press ctrl-g.

**Comment by AlexWayfer** [comment]
> Okay, try this:
> 
> ```fish
> function forget
>     set -l cmd (commandline | string collect)
>     history delete --exact --case-sensitive -- $cmd
> end
> 
> bind \cg forget
> ```
> 
> navigate to whatever you want to remove and press ctrl-g.

Works almost as I wanted! Thank you.

A little additional question (sorry, didn't find in [the documentation](https://fishshell.com/docs/current/index.html) by search): can I somehow clear the command line at the end of this function?

**Comment by zanchey** [comment]
Add `commandline ""; commandline -f repaint`.

**Comment by charego** [comment]
Duplicates/relates to https://github.com/fish-shell/fish-shell/issues/2110.

**Comment by AlexWayfer** [comment]
> ```fish
> bind \cg forget
> ```

What should I enter to save this binding in another shell (open terminal tab)?

```fish
> bind \cf forget

> bind --all | grep '\\\cf'
bind --preset \cf forward-char
bind \cf forget

> fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish

> bind --all | grep '\\\cf'
bind --preset \cf forward-char
```

**Comment by krobelus** [comment]
You can add it to the function definition. Fish will reload it automatically after like 5 seconds.

```fish
echo 'bind \cf forget' >> ~/.config/fish/functions/forget.fish
```

Or if you prefer to define bindings in one place, use your `config.fish`:

```fish
echo 'bind \cf forget' >> ~/.config/fish/config.fish
source ~/.config/fish/config.fish
```

The source is only required in fish instances that are already running.

**Comment by AlexWayfer** [comment]
> You can add it to the function definition. Fish will reload it automatically after like 5 seconds.
> 
> ```fish
> echo 'bind \cf forget' >> ~/.config/fish/functions/forget.fish
> ```
> 
> Or if you prefer to define bindings in one place, use your `config.fish`:
> 
> ```fish
> echo 'bind \cf forget' >> ~/.config/fish/config.fish
> source ~/.config/fish/config.fish
> ```
> 
> `source` is only required in fish instances that are already running.

Thank you. I've read the part about:

> `--preset` and `--user` specify if bind should operate on user or preset bindings. User bindings take precedence over preset bindings when fish looks up mappings. By default, all bind invocations work on the "user" level except for listing, which will show both levels. All invocations except for inserting new bindings can operate on both levels at the same time. `--preset` should only be used in full binding sets (like when working on `fish_vi_key_bindings`).

but I didn't understand what is (default) "--user", looks like user-scope (all user terminals), like the `-U` option of `set` command.

---

> Add `commandline ""; commandline -f repaint`.

Sorry me again, please, but what if I want to echo something, like `Forgotten`, and the clear the input?

Any combinations of `commandline -f repaint`, `echo Forgoten` and `commandline ""` doesn't do such thing, there is no `echo` result of empty line.

**Comment by krobelus** [comment]
> but I didn't understand what is (default) "--user", looks like user-scope (all user terminals), like the `-U` option of `set` command.

I see. Unfortunately key bindings are not managed with variables, so the `-U`/`--universal` option does not apply here.
`bind --user` only means that a binding takes precedence over default bindings.

> I want to echo something, like `Forgotten`, and then clear the input?

I'm not sure what's the best way to do this, maybe something like this:

```fish
bind \cg "
	printf '\tForgetting command...'
	sleep 1
	commandline ''
	commandline -f repaint
"
```

or replace the `sleep 1` with `read`, then you can add a confirmation before deleting a commandline.

**Comment by AlexWayfer** [comment]
> or replace the `sleep 1` with `read`, then you can add a confirmation before deleting a commandline.

I'm getting weird result:

```fish
function forget
  set -l cmd (commandline | string collect)
  history delete --exact --case-sensitive -- $cmd
  printf "Do you want to forget '$cmd'? [Y/n]"
  switch downcase-word(read)
  case n no
    exit
  case y yes ''
    commandline ""
    commandline -f repaint
  end
end
```

```
> echo $history[1]Do you want to forget 'echo $history[1]'? [Y/n]⏎                                                                   read> n
^C
```

**Comment by krobelus** [comment]
> switch downcase-word(read)

If downcase-word is a command, then you probably want `switch (downcase-word (read))`

> exit

that makes fish exit, which is probably not what you want; use `return` to stop the current function

something like this could work:

```fish
function forget
    set -l cmd (commandline | string collect)
    printf "\nDo you want to forget '$cmd'? [Y/n]"
    switch (read | tr A-Z a-z)
        case n no
            commandline -f repaint
            return
        case y yes ''
            history delete --exact --case-sensitive -- $cmd
            commandline ""
            commandline -f repaint
    end
end
```

**Comment by AlexWayfer** [comment]
> > switch downcase-word(read)
> 
> If downcase-word is a command, then you probably want `switch (downcase-word (read))`
> 
> > exit
> 
> that makes fish exit, which is probably not what you want; use `return` to stop the current function
> 
> something like this could work:
> 
> ```fish
> function forget
>     set -l cmd (commandline | string collect)
>     printf "\nDo you want to forget '$cmd'? [Y/n]"
>     switch (read | tr A-Z a-z)
>         case n no
>             commandline -f repaint
>             return
>         case y yes ''
>             history delete --exact --case-sensitive -- $cmd
>             commandline ""
>             commandline -f repaint
>     end
> end
> ```

Thank you, but this is still ugly, I can't clear a command before the confirmation:

```
> echo $history[1]Do you want to forget 'echo $history[1]'? [Y/n]⏎
read> 
```

**Comment by faho** [comment]
Yeah, your printf isn't ending in a newline, so our prompt hack kicks in, which causes that "⏎" to appear.

Add a `\n` at the end.

Anyway, this seems to be working well enough, closing.

**Comment by AlexWayfer** [comment]
Your final suggestion don't clear input which I want to forget, but it's a pretty solution anyway. Thank you. Yes, it works.
