### ISSUE TITLE
Is --on-process-exit called if the pid has already exited?

### ISSUE THREAD

**Issue by mattgreen** [fish-shell/fish-shell#7207]
Hi,
Been switching to fish recently and loving it. Thanks for all your hard work!

I’m building an async git prompt. I create a background job to check the dirty status of the repo, grab the PID with `jobs --last  --pid`, and register a function to run when the job finishes using `--on-process-exit $pid`. If the OS scheduler interrupts  execution before I register my handler in the parent process, and the job runs to completion, will my `--on-process-exit` callback still occur?

**Comment by faho** [comment]
It will not.

**Comment by mattgreen** [comment]
Thanks for the info. I have a path forward on this, so I'm closing.

For anyone who happens upon it: since I'm starting a subshell anyway, I can have the child send itself `SIGSTP` first thing, giving the parent time to register the handler. Then, the parent sends `SIGCONT` to the child when it's ready to proceed. When in doubt, add more UNIX, I suppose.

**Comment by ridiculousfish** [comment]
Hmm, if true that `--on-process-exit` has an essential race then, it means there's no way to use it reliably. That seems bad.

The event is sent when the pid is reaped, not when the process exits. So in principle this ought to be safe. However I don't know if we are careful to control when reaping occurs - there's some haphazard `job_reap` calls scattered around. Filed #7210 to track this.

@mattgreen I believe the (not widely used) event block mechanism will make this reliable:

	begin
	    block -l
	    cmd &
	    function finished --on-process-exit $last_pid
		    echo "All done"
		end
	end

The `block` call will cause fish to hold all events until the `begin/end` is closed.

**Comment by mattgreen** [comment]
> The event is sent when the pid is reaped, not when the process exits. So in principle this ought to be safe.

Yeah, this was my worry: things might work, but ultimately be reliant on unspecified implementation details.  I'll run with `block` for now, as is exceedingly useful for this. Thanks!

This came about because I need to communicate the result of the background job (a git dirty check) to the foreground process. Right now I'm mashing it into the return code, hence needing the PID. (macOS' lack of default tmpfs sucks.) Ideally, it'd be easy to spawn a background job, and collect the STDOUT, STDERR and return code in one go without any race conditions.
