### ISSUE TITLE
stdout each newline indented in guake terminal

### ISSUE THREAD

**Issue by brunswyck** [fish-shell/fish-shell#7209]
fish, version 3.1.2
3.1.2
uname -a
Linux dahost 5.3.0-62-generic #56~18.04.1-Ubuntu SMP Wed Jun 24 16:17:03 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

cat file output or
echo "hello"; echo "hi"; echo "buenos dias" indents text instead of each line starting at the beginning of the terminal

hello
     hi
       buenos dias

http://i.imgur.com/EMMZILK.png

**Comment by faho** [comment]
The output of `locale` and `stty -a` would be useful, in both shells.

**Comment by faho** [comment]
Also which terminal is this? The actual thing and the $TERM value?

**Comment by brunswyck** [comment]
$ stty -a
speed 38400 baud; rows 57; columns 106; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = <undef>; eol2 = <undef>; swtch = <undef>;
start = ^Q; stop = ^S; susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; discard = ^O; min = 1; time = 0;
-parenb -parodd -cmspar cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl -ixon -ixoff -iuclc -ixany -imaxbel
iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke -flusho -extproc

The issue resolved itself. I pulled up and down the guake terminal somewhat later and suddenly it works like expected.
Happy to go fishing now :-)

**Comment by krobelus** [comment]
Probably a duplicate of #7133
