### ISSUE TITLE
Programmatic access to the piping backend

### ISSUE THREAD

**Issue by alxpettit** [fish-shell/fish-shell#7212]
Is there a way to change piping programmatically via hook functions? My goal is to make my config file automatically store backups of files that I pipe to with `>`, if the shell is loaded interactively.

**Comment by zanchey** [comment]
The short answer is no.

There is a "noclobber" redirection - `>?` - which will not overwrite existing files, and might be a better option for safe use. Once global abbreviations (#5003) are supported, that would be the way to implement both global noclobber and possibly even modify the redirection syntax.

See #2812, #7072.

**Comment by krobelus** [comment]
`bind '>' 'commandline --insert ">?"'` could work but might be annoying.

**Comment by faho** [comment]
Question seems to have been answered, closing.

**Comment by alxpettit** [comment]
@krobelus  The `commandline --insert ">?"`part works in isolation but the bind command doesn't. :c

**Comment by alxpettit** [comment]
@zanchey

How feasible would it be to add a piping symbol that can overwrite but keep a backup? It seems like useful high level behavior -- maybe using `>! `or something?

I often find myself overwriting files on purpose with redirection and tab completion, and working quickly. It can be dangerous -- and not every system I work on has snapshots set up. This seems like it'd be good for many use cases for other people too, but maybe I'm alone here.

Another option that occurs to me is that I could go write a program to implement this functionality in a tee-like function, e.g.:

`echo hi | safe-tee ~/hi.txt`

But it does seem a bit more verbose and inelegant than having a piping symbol. I wonder how difficult it'd be to have support in FISH for defining arbitrary symbols and then having your own script, to cover the most use cases possible.

**Comment by gokulsoumya** [comment]
@alxpettit If you are using vi mode then you have to bind the key in insert mode:

commandline -M insert --insert ">?"

**Comment by zanchey** [comment]
> I wonder how difficult it'd be to have support in FISH for defining arbitrary symbols and then having your own script, to cover the most use cases possible.

There's some thoughts on global aliases/abbreviations in #5003.
