### ISSUE TITLE
open.fish disown xdg-open on Awesome WM

### ISSUE THREAD

**Issue by phamhm** [fish-shell/fish-shell#7215]
* fish version 3.1.2
* Linux Fedora 32 5.7.8-200.fc32.x86_64. 
* Running Awesome WM. 

xdg-open will fork a new process in XFCE but won't fork in Awesome Wm. I modified to my /usr/share/fish/functions/open.fish as follow to make open/xdg-open fork a new process. 

```fish
            for i in $argv
                xdg-open $i &disown
            end
        else
```

Not sure if checking XDG_SESSION_DESKTOP to determine whether to disown would help.

**Comment by faho** [comment]
I feel like whatever xdg-open is calling here is at fault - these things fork off new processes *everywhere else*, so this should as well.

Regardless, it's probably okay to just unconditionally background and disown these.

**Comment by faho** [comment]
Ah, okay, it's xdg-open's "generic" path causing the issue.

It's already open upstream as a bug - https://gitlab.freedesktop.org/xdg/xdg-utils/-/issues/158. No reaction in 9 months, development appears to essentially be dead, with one commit in the last 13 months.

Yeah, let's work around it.

**Comment by phamhm** [comment]
Thank you for accepting this change request.

**Comment by krobelus** [comment]
Just out of curiosity, `setsid foo` does essentially the same as `foo & disown` but I'm not sure if it is available on non-Linux?

**Comment by faho** [comment]
The `setsid` command will not be available outside of linux, no.

(also if `disown` weren't fit for this we should fix it, this is its job)
