### ISSUE TITLE
rm * fails when directory contains filename starts with - (dash character)

### ISSUE THREAD

**Issue by templateK** [fish-shell/fish-shell#7224]
fish version :  3.1.0
OS               :  macOS mojave
$TERM        :  xterm-256color

create file name `-`
run shell command `rm *`

the result is 
> rm: illegal option -- .
> usage: rm [-f | -i] [-dPRrvW] file ...
>       unlink file

**Comment by ridiculousfish** [comment]
Classic Unix footgun, that :) Sadly every shell has this problem! Dup of #1519 - thanks for filing.
