### ISSUE TITLE
`read --silent` is storing passwords in plaintext in history

### ISSUE THREAD

**Issue by mdenzel** [fish-shell/fish-shell#7230]
Hello guys,

it seems that fish is storing plaintext passwords when using `read --silent` to read them in. This makes password prompts a security hazard.

It has already been fixed according to https://github.com/fish-shell/fish-shell/issues/6438 and  https://github.com/fish-shell/fish-shell/pull/5904 (also https://github.com/fish-shell/fish-shell/issues/838, https://github.com/fish-shell/fish-shell/issues/1504) but does not seem to work as expected:

```
> set | grep fish_private
fish_private_mode
> fish --private
Welcome to fish, the friendly interactive shell.
fish is running in private mode, history will not be persisted.
> set | grep fish_private
fish_private_mode 1
> read --silent password
read> ●●●●●●●●●●●●●●●●
> mysecretpassword
(simply by pressing the "up" arrowkey; it also shows up in the 'history' command)
```

Attackers could just dump passwords from fish's history.

Systeminfo:
```
> echo $TERM
xterm-256color
> uname -r
5.7.10-201.fc32.x86_64
> fish --version
fish, version 3.1.2
```

**Comment by faho** [comment]
The read history is no longer stored on disk. It is still kept in memory, but at that point you have bigger problems.

**Comment by ridiculousfish** [comment]
Reopening this - I can reproduce, it seems specific to the `--private` mode.

**Comment by ridiculousfish** [comment]
Thanks for filing, good find!
