### ISSUE TITLE
Filename Completion after Vim command

### ISSUE THREAD

**Issue by antmordel** [fish-shell/fish-shell#7231]
Running fish `fish, version 3.1.2` and after writing in the prompt `vim` filename popups are not showing up. I've checked `complete` commands and I don't have any `-f` in it. Where should I look for it?

Thanks.

**Comment by krobelus** [comment]
So after typing `vim <TAB>` in the shell, there is no `-f` in `complete | grep vim`?
Does `complete -c vim -e` fix it?

If not, what does `type vim` show?
It could be defined with `function --wraps foo` (e.g, if it's an alias), in that case the completions from `foo` are used - a `complete -c foo -f` could cause this problem.

General sanity check: does it reproduce with `HOME=(mktemp -d) fish`?

**Comment by antmordel** [comment]
It was exactly that @krobelus. It was defined as a function and the --wraps were causing the problem! thanks a lot. I learned today a new thing. Thanks!
