### ISSUE TITLE
Function __fish_pwd fails when using pwd's flags

### ISSUE THREAD

**Issue by judu** [fish-shell/fish-shell#7240]
- Fish version: 2.7.1
- Running on Linux 5.5.19-00003-g280b952b5546 #43 SMP Fri Jul 31 15:58:25 CEST 2020 x86_64 GNU/Linux
- Running fish in tmux in a libVTE terminal emulator

I'm trying zoxide (https://github.com/ajeetdsouza/zoxide) and I get an error about pwd not knowing the `-L` flag.

Here is what it looks like:

[![asciicast](https://asciinema.org/a/YsWJtuS05ZLDwrojUQP7IHMjb.svg)](https://asciinema.org/a/YsWJtuS05ZLDwrojUQP7IHMjb)

**Comment by krobelus** [comment]
You want to upgrade to 3.1.2; the `pwd -L` option was introduced in 3.0.0.

**Comment by judu** [comment]
Oh, did not think to check the version. The person who packages fish for my system seems to be late.

**Comment by zanchey** [comment]
What operating system are you using?
