### ISSUE TITLE
Got oah error with apple silicon mac DTK

### ISSUE THREAD

**Issue by thanakijwanavit** [fish-shell/fish-shell#7243]
I received the following error message when installed fish shell using `brew install fish` on mac DTK with apple silicon
error
```
oah error: /var/db/oah/e089a67a1d38c1a085254c76a7cb592fcceddb3f234a4aa318bb4ec25fe40237/9c4c85f77c58522f2b802176f01d7bbeace7eba4f4dc6294da252757c21c7b29/fish.aot: unable to mmap __TEXT: 1
```

Im unable to get fish to run at all

os and terminal info 
```
Darwin Thanakijs-Mac.local 20.0.0 eperm-5c05f49dcf4801d2 x86_64

xterm-256color
```

**Comment by zanchey** [comment]
This looks like https://developer.apple.com/forums/thread/652747

Can you show the output from `brew install fish`?

**Comment by faho** [comment]
Closing for lack of information. If anyone provides it, we'll reopen. Sorry!

**Comment by ktjd123** [comment]
having same issue

**Comment by zanchey** [comment]
Does it work if you run `brew remove fish; brew install --build-from-source fish`?

**Comment by ridiculousfish** [comment]
I got my Apple Silicon Mac, and can confirm that `brew install fish` works in both emulated and native mode. Closing.
