### ISSUE TITLE
Control+F to complete auto-suggestions over SSH

### ISSUE THREAD

**Issue by stripedpajamas** [fish-shell/fish-shell#7244]
Hi, I looked through old issues and searched online but haven't found anyone talking about this. I'm new to fish (loving it), especially the auto-suggestions. I prefer to use Control+F to accept the suggestions, rather than the right arrow key. This behavior works fine locally on machine A (fish v3.1.2) and machine B (fish v3.0.2). But when I SSH into B from A, only the right arrow key works (inside the SSH session) to accept the suggestion. Control+F doesn't do anything. 

Is there some kind of flag I need to set on the session itself to send Control+F to the remote host? Is this behavior supported?

A:
fish v3.1.2
Mac OS X 10.15.6
iTerm2 (xterm-256color)
No 3rd party customizations (fresh install)

B:
fish v3.0.2
Linux armv7l
No terminal (this is the remote host)
No 3rd party customizations (fresh install)

**Comment by ridiculousfish** [comment]
Probably either your Linux key bindings have been customized, or something is swallowing control-f over ssh.

1. If you run `bind | grep cf` on the Linux box, what bindings does it show? It should be just `bind --preset \cf forward-char`

2. If you run `fish_key_reader` and type control-F, does it show the correct `hex:    6  char: \cF`?

**Comment by stripedpajamas** [comment]
`bind | grep cf` return nothing on the Linux box. So I went ahead and ran `bind --preset \cf forward-char`. On both machines `fish_key_reader` prints the following after pressing control+f:

```
[I] ~ > fish_key_reader
Press a key

              hex:    6  char: \cF
bind \cF 'do something'
[I] ~ >
```

Despite that (and logging off and back on through SSH) it's still not doing anything when I hit control+f.

**Comment by zanchey** [comment]
Possibly you are in Vi mode, which does not include this binding by default. Does running `fish_default_key_bindings` help?

**Comment by stripedpajamas** [comment]
omg @zanchey that was it yeah... I was in Vi mode on the Linux machine. running `fish_default_key_bindings` made control+f work again. is there a way to have both? (vi mode + control+f to accept suggestions)

**Comment by krobelus** [comment]
@stripedpajamas yep, `fish_hybrid_key_bindings` does that. Like vi mode, it has some imperfections and could need some love, YMMV. See also #4019 for example

**Comment by stripedpajamas** [comment]
thanks @krobelus !
