### ISSUE TITLE
fish -n errors on conf.d snippets.

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7246]
Clean fish with the following structure:

```
fish
├── conf.d
│  └── init.fish
├── fish_variables
└── functions
   └── foo.fish
```

`init.fish`:

```fish
foo
```

`foo.fish`:

```fish
function foo
    echo FOO!
end
```

This all works just as expected, printing `FOO!` on startup:

```console
FOO!
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
ilan@archlabs ~>
```

However running `fish -n` on `init.fish` errors:

```console
ilan@archlabs ~> fish -n .config/fish/conf.d/init.fish
.config/fish/conf.d/init.fish (line 1):
foo
^
```

Putting `foo` in a block makes `fish -n` happy:

```fish
switch (uname)
    case Linux
        foo
    case Darwin
        foo
end
```

```fish
function blah
    foo
end
```

It would make sense to me to have `fish -n` pass `init.fish` when `foo` is all on its own, since `fish -n` isn't supposed to complain on unknown functions:

```fish
function blah # Passes fish -n
    nonexistant_function
end
```

**Comment by zanchey** [comment]
I'm not sure what happened to the template in the issue, but can you confirm what version you are running?

I can reproduce this behaviour on 3.0.2 and 3.1.0, but not in master with #977 fixed.

**Comment by IlanCosman** [comment]
Oh I apologize I forgot to fill that out.

fish, version 3.1.2
Linux archlabs 5.7.12-arch1-1 #1 SMP PREEMPT Fri, 31 Jul 2020 17:38:22 +0000 x86_64 GNU/Linux
xterm-256color
Fully clean fish

**Comment by IlanCosman** [comment]
#977 should solve this. I had thought that issue was closed earlier than it actually was.
