### ISSUE TITLE
commandline -f repaint not functioning as expected

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7248]
Clean fish with the following two functons, `on_foo` is in conf.d so it's loaded on startup.

```fish
function on_foo --on-variable foo
    commandline -f repaint
end
```

```fish
function fish_prompt
    printf '%s ' $PWD $foo '>'
end
```

With this setup I get the following result:

```console
/home/ilan >
/home/ilan > set foo bar
/home/ilan bar > set foo qux
/home/ilan qux >
```

[From the docs](https://fishshell.com/docs/current/cmds/bind.html#special-input-functions):

> `repaint` reexecutes the prompt functions and redraws the prompt

Given this, I had thought that `commandline -f repaint` would redraw the prompt right after I set foo meaning that I would see the **_same_** line's prompt receive the changes like so:

```console
/home/ilan >
/home/ilan bar > set foo bar
/home/ilan qux > set foo qux
/home/ilan qux >
```

On gitter @ridiculousfish suggested using `force-repaint`, but that returned the same negative result as `repaint`.

My ultimate use case is an asynchronous prompt. What am I misunderstanding about `commandline -f repaint` and is there a way of doing what I want? Regardless, the docs should be more clear as to what `commandline -f repaint` does.

<div align="center">
<sub>

fish, version 3.1.2

Linux archlabs 5.7.12-arch1-1 #1 SMP PREEMPT Fri, 31 Jul 2020 17:38:22 +0000 x86_64 GNU/Linux

xterm-256color

Clean fish

</sub>
</div>

**Comment by zanchey** [comment]
The variable hasn't changed until the command runs, so the prompt being redrawn is the one that your cursor is now on.

If you do `set -U foo qux` in another shell, you'll see the current prompt change (at least with `force-repaint`).

**Comment by IlanCosman** [comment]
Thanks for the reply zanchey :) I can indeed verify that `set -U foo qux` works with `force-repaint`, so my dreams of async prompt should be achievable using this.

> The variable hasn't changed until the command runs, so the prompt being redrawn is the one that your cursor is now on.

This however I don't quite understand. If we set `on_foo` to

```fish
function on_foo --on-variable foo
    echo $foo
end
```

we can see that `on_foo` runs before `fish_prompt` but after `set foo`.

```console
/home/ilan >
/home/ilan > set foo bar
bar
/home/ilan bar > set foo qux
qux
/home/ilan qux >
```

Given this, it seem logical to me that `commandline -f repaint` would affect the "current line" i.e the most recent `set foo`. My cursor hasn't "moved" yet as we can clearly see above.

**Comment by zanchey** [comment]
You are executing a command (`set`). Executing this command will stop the command-line editor and insert a new line. Once the command returns, the prompt is executed again and the command-line editor is started. Repaint will only do something useful when the command-line editor is active.

Run `sleep 100`. Where is the cursor after you push enter? Would you expect the prompt above this line to change while `sleep` is active?

**Comment by mattgreen** [comment]
Two things:
1. I've seen similar behavior with `repaint`/`force_repaint` when trying to work with async prompts. Might be because I have a multiline prompt?
2. It's undocumented, but I had more luck with `__fish_repaint` for this.

My [fish_prompt.fish](https://github.com/mattgreen/dotfiles/blob/master/fish/functions/fish_prompt.fish) has a working example of an async prompt, albeit through undocumented functions. `set -U` works as IPC, with the caveat that it hits the disk. I ended up using process exit codes as IPC instead.

**Comment by IlanCosman** [comment]
That makes sense zanchey, thanks for explaining. 

Thanks for your comments matt, I'm sure your `fish_prompt.fish` will be useful to me 😄

**Comment by mattgreen** [comment]
Though the issue is closed, I would like to suggest that something akin to `__fish_repaint` be officially supported.

I was also surprised by the behavior of `commandline -f repaint`, even if I was mistaken about the proper context of its usage.

**Comment by faho** [comment]
>Though the issue is closed, I would like to suggest that something akin to __fish_repaint be officially supported.

@mattgreen That's a placebo. Here's the full definition of `__fish_repaint`: https://github.com/fish-shell/fish-shell/blob/26fda2bf0dcf93014abbc7cb69f39bfded82a1ec/share/functions/__fish_config_interactive.fish#L141-L146

**Comment by IlanCosman** [comment]
@mattgreen looking at __fish_repaint: "Wait it's just `commandline -f repaint`?"
@faho behind him: "Always has been."

😂
