### ISSUE TITLE
Autosuggestion freaks out with names longer than terminal window

### ISSUE THREAD

**Issue by atheistd** [fish-shell/fish-shell#7249]
fish v 3.1.2
OS: macOS 10.15.6 **&&** Ubuntu 20.04
uname: Darwin <sensitive_hostname> 19.6.0 Darwin Kernel Version 19.6.0: Sun Jul  5 00:43:10 PDT 2020; root:xnu-6153.141.1~9/RELEASE_X86_64 x86_64 **&&** Linux <sensitive_hostname> 5.4.0-1015-raspi #15-Ubuntu SMP Fri Jul 10 05:34:24 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
colors: xterm-256color
terminal: Apple Terminal, Hyper **&&** Terminator, GNOME Terminal

Whenever the filename can't fit in the terminal's window length, autosuggestion freaks out. Here is a [video](https://imgur.com/BBjo6Rs) of what happens.

**Comment by zanchey** [comment]
Can you define "freaks out"? It seems to me that's the intended behaviour on a non-Unicode-aware system with truncation of a too-long command by $ instead of … - is it that the length of the suggestion is jumping around?

**Comment by atheistd** [comment]
A. When I press tab to autocomplete, I get the same character in the beginning of the file/dir path like `cd .../` or when I try to erase the whole command it doesn't erase the first character of the command like `ccd ../`. But when I press enter, it actually goes a directory up and doesn't give me any errors. And when I press up it actually shows up as `cd ../`. (here's a [video](https://imgur.com/a/4qIJhO9) of what's actually happening - trying to delete the entire command)
B. When I don't use tab completions and use wildcards, sometimes it truncates the characters in the statement. video [here](https://imgur.com/BBjo6Rs) I'm actually typing `mv *S02*.* *S03*.* ` (this is an incomplete statement but it's so confusing that I can't proceed with the intended command)

**Comment by krobelus** [comment]
What is the output of `locale`? Does it behave differently with a Unicode one, for example `LANG=en_US.UTF-8 fish`?

**Comment by ridiculousfish** [comment]
The second video (with `ccd`) looks like there's an autosuggestion with a Unicode character where fish and the terminal disagree on the width. Can you confirm if there's a file with an unusual character (emoji, double-width or zero-width) in `/home`? It may have a leading dot.

**Comment by atheistd** [comment]
> What is the output of `locale`? Does it behave differently with a Unicode one, for example `LANG=en_US.UTF-8 fish`?

locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=C.UTF-8
LANGUAGE=
LC_CTYPE=UTF-8
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_PAPER="C.UTF-8"
LC_NAME="C.UTF-8"
LC_ADDRESS="C.UTF-8"
LC_TELEPHONE="C.UTF-8"
LC_MEASUREMENT="C.UTF-8"
LC_IDENTIFICATION="C.UTF-8"
LC_ALL=

**Comment by atheistd** [comment]
> The second video (with `ccd`) looks like there's an autosuggestion with a Unicode character where fish and the terminal disagree on the width. Can you confirm if there's a file with an unusual character (emoji, double-width or zero-width) in `/home`? It may have a leading dot.

Checked it, no unusual file/dir names. It's the same as freshly installed Ubuntu except for my .zshrc but I'm guessing that's not the root of the issue.

**Comment by faho** [comment]
@atheistd Your locale is broken, and therefore unicode support doesn't work. Fish *needs* it in order to figure out how wide characters are, which is necessary for suggestions to work properly (it requires a bunch of cursor movement).

In particular ` LC_CTYPE=UTF-8` seems wrong (LC_CTYPE being the variable that defines the *encoding*, so it's the most important here), it's possibly `LC_CTYPE=C.UTF-8`.

See e.g. /etc/locale.conf.

**Comment by atheistd** [comment]
So how do I fix it?

**Comment by faho** [comment]
Depends on what broke it. On Ubuntu, which uses systemd, locale is typically configured in /etc/locale.conf.

On mac? I have no idea.

**Comment by atheistd** [comment]
`/etc/locale.conf` is empty in my Ubuntu machine

**Comment by faho** [comment]
Ah, I forget that Debian adds its own cruft on top. Try `dpkg-reconfigure locales` as root, that should guide you through it.

**Comment by krobelus** [comment]
Okay then adding `LC_CTYPE=C.UTF-8` to `/etc/locale.conf` might not work since something else seems to be changing the environment variable.

`LC_CTYPE=C.UTF-8 fish` should definitely work.

Check your shells' startup files, something must be messing with `LC_CTYPE`.

> Ah, I forget that Debian adds its own cruft on top. Try dpkg-reconfigure locales as root, that should guide you through it.

The C locale ought to work without that even, it's a good idea to try to add some other locale using that, though.

**Comment by faho** [comment]
>The C locale ought to work without that even, it's a good idea to try to add some other locale using that, though.

"C" wouldn't if there's non-ASCII characters. "C.UTF-8" would as long as it's available (it's not actually in upstream glibc for horrible reasons, but I think Ubuntu/Debian patches it in?).

**Comment by atheistd** [comment]
I tried running `dpkg-configure` as root, but it defaults to *C*. If you're sure that this is what's causing the problems, I can try switching from Ubuntu server to ~Raspbian~Raspberry Pi OS.

**Comment by faho** [comment]
>If you're sure that this is what's causing the problems, I can try switching from Ubuntu server to RaspbianRaspberry Pi OS.

Ubuntu server should be perfectly capable of handling this.

>I tried running dpkg-configure as root, but it defaults to C.

I don't understand. The point is that you *change* it. Does that not work? Does it not display the other locales?

**Comment by atheistd** [comment]
```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "C.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("C.UTF-8").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_CTYPE to default locale: No such file or directory
/usr/bin/locale: Cannot set LC_ALL to default locale: No such file or directory
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "C"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "C"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
```

I get this when I try to generate `en_US.UTF-8 UTF-8` and `en.US.UTF-8` for the default locale for system env with `sudo dpkg-reconfigure locales`.

**Comment by krobelus** [comment]
Try running `LC_CTYPE=C.UTF-8 sudo dpkg-reconfigure locales`

**Comment by atheistd** [comment]
> Ubuntu server should be perfectly capable of handling this.

I thought so too, but when I tried this in a 20.04 server & desktop VM, I had the same outcomes.

**Comment by atheistd** [comment]
> Try running `LC_CTYPE=C.UTF-8 sudo dpkg-reconfigure locales`
The prompt characters are messed up now :|
<img width="697" alt="Screenshot 2020-08-08 at 01 10 13" src="https://user-images.githubusercontent.com/44400303/89682166-ebafe280-d913-11ea-9818-d51b9efb74a9.png">

**Comment by faho** [comment]
Yeah, you'll have to restart fish after this.

**Comment by atheistd** [comment]
Okay, I just rebooted my machine 2 minutes ago and I no longer I have the weird gibberish, but the main problem is still there
>B. When I don't use tab completions and use wildcards, sometimes it truncates the characters in the statement. video here I'm actually typing mv *S02*.* *S03*.* (this is an incomplete statement but it's so confusing that I can't proceed with the intended command)

**Comment by krobelus** [comment]
Since you are logging in via ssh from a Mac terminal, try [this answer](https://askubuntu.com/a/778672)

**Comment by faho** [comment]
@atheistd What does `locale` now say?

**Comment by atheistd** [comment]
```
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE=UTF-8
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by faho** [comment]
Yeah, the LC_CTYPE is still broken.

*Something* in your configuration is screwing it up, and it appears this is indeed a problem with macOS sending the wrong thing over ssh, so you should try @krobelus link (https://askubuntu.com/questions/599808/cannot-set-lc-ctype-to-default-locale-no-such-file-or-directory/778672#778672):

>This same problem (LC_CTYPE=UTF-8, which is wrong) can happen when you login over ssh from a Mac to a linux box, and your terminal automatically sets environment variables. There's a checkbox for that. Uncheck it, and you're good to go.

>In iTerm it's in the profile -> Terminal tab.

>In Terminal, it's in the Terminal -> Preferences -> Profiles -> Advanced tab.

**Comment by atheistd** [comment]
I guess both issues were regarding the locale. Thanks for the help :) <3
