### ISSUE TITLE
Issue on setting PATH persistently is misleading

### ISSUE THREAD

**Issue by mattgreen** [fish-shell/fish-shell#7250]
Lost more time than I'd like to admit on this. [Issue 527](https://github.com/fish-shell/fish-shell/issues/527) details how to append to `$fish_user_paths`. The problem is the second iteration meant for scripts has the `contains` invocation wrong:

`contains $fish_user_paths /path/to/add; or set -Ua fish_user_paths /path/to/add`

It should be:

`contains /path/to/add $fish_user_paths; or set -Ua fish_user_paths /path/to/add`

This usage matches what the `contains` manpage has on it as well, where the key precedes one or more values. I _think_ the given usage succeeds if $fish_user_paths contains only `/path/to/add`, hence the confusion.

**Comment by krobelus** [comment]
Right, fixed, thanks for spotting this!

fish 3.2.0 will come with `fish_add_path`( #7028) which makes this even easier.
