### ISSUE TITLE
Add fish_indent --check

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7251]
Similarly to many other formatters, `fish_indent` should have a `-c/--check` option that will tell the user if the fish file is formatted as `fish_indent` would like.

This is currently achievable with `fish_indent $file | diff - $file`, but I think it should be added as a standard option.

<div align="center">
<sub>

fish, version 3.1.2

Linux archlabs 5.7.12-arch1-1 #1 SMP PREEMPT Fri, 31 Jul 2020 17:38:22 +0000 x86_64 GNU/Linux

xterm-256color

Clean fish

</sub>
</div>

**Comment by faho** [comment]
I don't see the benefit? Why not just reformat?

**Comment by IlanCosman** [comment]
Here's a popular formatter with a `--check` option and a bit of explanation around it:
<https://prettier.io/docs/en/cli.html#--check>

As they said above, I'm interested in using this in a CI pipeline. With linters and formatters as part of the pipeline, I'd prefer that the commit remains unchanged.

**Comment by faho** [comment]
I mean you can also just use it in the pre-commit hook, or write that thing above.

The way fish_indent is written would make this quite difficult, because it doesn't actually look at the source. It looks at the parse tree.

**Comment by faho** [comment]
Okay, no, this is much easier than I assumed.

**Comment by faho** [comment]
Yeah, added.

However fish_indent had some rather annoying regressions since 3.1.2, see #7252.

**Comment by IlanCosman** [comment]
Thanks for the quick response and feature addition @faho 😄

**Comment by IlanCosman** [comment]
Hi @faho Sorry to bother you about this issue again😕, I really appreciate you adding it 😄.

I should have thought of this in the original issue:

`fish_indent --check` should list the file names that fail. This is important for making it pleasant to work with.

**Comment by faho** [comment]
Yeah, sure, done.

It now returns the number of failed files and prints newline-separated names of the failed files (this also means it doesn't quit at the first failure - which is usually a bad idea anyway).
