### ISSUE TITLE
fish_indent regressions

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#7252]
I'm assuming this comes from the new AST, but fish_indent now insists on formatting combined if-conditions like

```fish
if foo
   and bar
```

as

```fish
if foo; and bar
```

I don't think that is what we want.

There are some other changes, including

```fish
begin
    indented code
# comment now on the level of the `end`
end
```

```fish
command \
continuation line on the same indentation
```

```fish
function __fish_systemd_machines
    machinectl --no-legend --no-pager list --all | while read -l a b
            echo $a # <-- this double-indentation is weird!
        end
end
```

However the worst is:

```fish
thing | # comment
thing
```

to

```fish
thing | # comment


    thing
```

in particular because it's not even stable. Another run will add another empty line (this was discovered while working on #7251, because ``--check`` will always return false on this).

Tested with 3dcb39f8e.

**Comment by ridiculousfish** [comment]
The three commits ending in f6c1ef58dfea3ce79d91e1c6edaa7541224b01e6 address some of this.

The remaining bits are the "worst case":

    thing | # comment
    thing

Regarding this

    if foo
        and bar

gets indented to

    if foo; and bar

this was [a deliberate choice](https://github.com/fish-shell/fish-shell/blob/f6c1ef58dfea3ce79d91e1c6edaa7541224b01e6/src/fish_indent.cpp#L305); I used the heuristic of "if you have only one or two `and`s they get put on the same line, three or more get separate lines." But I'm not attached to this behavior if someone has a strong opinion.

**Comment by faho** [comment]
>The three commits ending in f6c1ef5 address some of this.

Nice, thanks!

> I used the heuristic of "if you have only one or two ands they get put on the same line, three or more get separate lines." 

I saw that after.

To be honest I don't think these strict rules are a good idea, especially since the heuristic is quite simplistic.

This leads to behavior like clang-format, which loves to break lines if they are too long and join lines if they aren't, so it just ends up going back and forth when a line changes. See e.g. 149a0b98afbdaefc6926d908736604d25262e1d9, where it changes the perfectly clear

```c++
void clear(void) {
    text.clear();
}
```

to

```c++
void clear(void) { text.clear(); }
```

Simply because it decided that the line wasn't full yet.

That's why in 15c50703ce446b131eb3154bfa3e9596d0bbd74 I chose to keep semicolons iff the user adds them and it's an "and" or "or" continuation, instead of always keeping or adding them, and why I never tried adding anything dealing with line length.

But I might just be weird.

**Comment by krobelus** [comment]
I fixed the unstable case (not sure if there is a simpler solution), and I added another change for comments before line continuations.

I like `clang-format`, but we should probably be more like `gofmt` which never breaks lines.
That being said, I prefer the one-line version for almost all cases in `share/**.fish` where the heuristic applies.

**Comment by faho** [comment]
Okay, here's what those changes look like:

An acceptable one:

```fish
-    if test -n "$argv"
-        and not string match -qr '^-' $argv[1]
+    if test -n "$argv"; and not string match -qr '^-' $argv[1]
```

a bad one:

```fish
-            if test -f /proc/version
-                and string match -riq 'Microsoft|WSL|MSYS|MINGW' </proc/version
-                and set -l cmd (command -s cmd.exe /mnt/c/Windows/System32/cmd.exe)
+            if test -f /proc/version; and string match -riq 'Microsoft|WSL|MSYS|MINGW' </proc/version; and set -l cmd (command -s cmd.exe /mnt/c/Windows/System32/cmd.exe)
```

Granted the acceptable case is far more common, but I don't think it's actually *better* joined than broken, and the bad case is *awful* (it's 158 characters *plus indentation*).

**Comment by krobelus** [comment]
Yeah, overlong lines are not ideal, the structure is much easier to see when the statements align.

So I'd either

1. include a heuristic that takes into account line width.
2. keep the linebreaks from the input (as before).

Probably option 2 is better because it avoids introducing a column limit.

**Comment by ridiculousfish** [comment]
Either seems fine to me!
