### ISSUE TITLE
option `-o` is not working

### ISSUE THREAD

**Issue by sarisia** [fish-shell/fish-shell#7254]
```
~> fish --version
fish, version 3.1.2
~> echo $version
3.1.2
~> uname -a
Linux Lilim 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
~> echo $TERM
xterm-256color
```

`man fish` (and [HTML manual](https://fishshell.com/docs/current/cmds/fish.html)) says there's an option `-o` treats
as same as `--debug-output=path`:
> • -o  or  --debug-output=path  Specify a file path to receive the debug output, including cate‐
         gories and fish_trace. The default is stderr.

At this moment, `--debug-output=path` works well but `-o` isn't:
```
~> fish -o fish.log
fish: invalid option -- 'o'
~> fish -o=fish.log
fish: invalid option -- 'o'
~> fish -ofish.log
fish: invalid option -- 'o'
~> fish --debug-output=fish.log
~> set fish_trace 1
~> cat fish.log
+ cat fish.log
```

**Comment by zanchey** [comment]
Nice catch!
