### ISSUE TITLE
Evaluate configuration AFTER config.fish

### ISSUE THREAD

**Issue by patrickf3139** [fish-shell/fish-shell#7256]
According to https://fishshell.com/docs/current/#initialization-files and my own testing, `config.fish` is always initialized last. I don't know how much the fish authors want to cater to fish sub-communities such as fish package maintainers, but this is a problem for us. This makes it very inconvenient for us to allow users to change package behavior via config.fish.

For example, it'd be really great if
1. user's `config.fish` exports a variable
2. my package's conf.d snippet checks for that variable and branches behavior based on it

(see https://github.com/patrickf3139/fzf.fish/issues/15 for context)
Yes, I know that users can use universal variables to accomplish the same thing, but it seems that it's less intuitive, less preferable, and doesn't allow them to check their configuration into their dotfiles.

So, is there currently a way to bypass this problem? e.g. maybe a hook or a "config.fish has been evaluated" event trigger my scripts can check for? If not, is there any plan to add this functionality?

Thank you for all you do for fish!

**Comment by zanchey** [comment]
There's some prior discussion in https://github.com/fish-shell/fish-shell/pull/2498 and https://github.com/fish-shell/fish-shell/pull/5636#issuecomment-462153246.

There are some tradeoffs in terms of simplicity and functionality here. Most of the fish functions with configuration options (the git prompt in particular) check the configuration option each time, which seems to work ok. Another option is to set up a function to change behaviour whenever the variable is changed (with `function do_thing --on-variable thing_var`) or similar. Or watch for the first `fish_prompt` event and erase the function after running.

**Comment by faho** [comment]
So, in your case, what I'd recommend is to do it like the official fzf integration does and provide a function that people can then choose to execute.

If you insist on activating it via conf.d, then you'll have to tell people to disable it either by overriding the script itself or by setting the disabling variable as a universal or in an earlier conf.d script - 00-custom.fish or so, and call yours 50-fzf.fish.

I don't think we want to add yet another file to be read, the conf.d stuff is complicated enough as it is.

**Comment by patrickf3139** [comment]
@zanchey Thanks for the ideas. In my case what I want to change is keybindings. I want to check for the existence of a variable and if it exists, don't set up any keybindings so the user can set them up themselves. I suppose it may work with the event trigger. I'll try it out later this week.

@faho Thanks for the recommendation! I understand it's important to keep fish shell simple.
