### ISSUE TITLE
Send events to other fish processes

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7258]
This has probably been brought up before, but I was unable to find it if so.

[From the docs](https://fishshell.com/docs/current/cmds/emit.html#notes):

> events are only sent to the current fish process as there is no way to send events from one fish process to another.

It's easy to create a budget approximation of this with universal variables:

```fish
set -U foo 1

function on_fish_prompt --on-event fish_prompt
    set -U foo (math $foo+1)
end
```

```fish
function on_foo --on-variable foo
    echo hello
end
```

In one shell run `on_fish_prompt`, and in the other run `on_foo`.

If we can already create bootleg cross-process events, shouldn't that be a standard feature?

<div align="center">
<sub>

fish, version 3.1.2

Linux archlabs 5.7.12-arch1-1 #1 SMP PREEMPT Fri, 31 Jul 2020 17:38:22 +0000 x86_64 GNU/Linux

xterm-256color

Clean fish

</sub>
</div>

**Comment by ridiculousfish** [comment]
Interesting, what's your use case for cross-process events?

**Comment by IlanCosman** [comment]
Asynchronous prompt. My idea was that I would simply start a background shell that would run an `--on-event fish_prompt` function to do the heavy computation. Then when it was done it would run `commandline -f repaint` and my main shell would receive the changes.

The idea still holds water, but I'd just have to use the silly interface above.

**Comment by IlanCosman** [comment]
I found an inconsistency with my "great value" cross-process event system: #7260

**Comment by IlanCosman** [comment]
Another issue with this method is that setting universal variables hits the disk, making it leagues slower.

Ex: 

Spam
`time set -U blargh (math $blargh +1)` 
vs.
`time set -g flargh (math $flargh +1)` 

The differences is ~20x for me.

**Comment by krobelus** [comment]
There used to be a `fishd` which seems to be gone for good now.

The uvar solution seems fine. This could be improved with concurrent execution if all you want is a function computing the prompt in the background.

**Comment by IlanCosman** [comment]
Could you explain what you mean by concurrent execution here @krobelus?

Yah the uvar solution does work I suppose, it's just a lot more awkward (and much slower) than allowing for cross-process events. In an optimal world there would just be an `emit -g` flag that emits cross-process.

**Comment by faho** [comment]
>Could you explain what you mean by concurrent execution here 

Like proper backgrounding, with functions and stuff.

So you'd actually run the things *in the same fish*, rather than hacking around it with a worker process.

That's the plan for #238 (tho it's still a while off)

To be honest, I wouldn't try an async prompt before that, because whatever you do it's gonna be super hacky and awkward.

**Comment by IlanCosman** [comment]
> you'd actually run the things in the same fish, rather than hacking around it with a worker process.

That would be the most optimal thing yes.

> That's the plan for #238 (tho it's still a while off)

I really don't mean to be rude and I know you guys have a (very wise) policy of not giving timelines, but is there any work being done on that issue? Seeing the `fish-future` tag, not even the `next-major` one, and the issue having been opened in 2012 doesn't give me much hope.

> To be honest, I wouldn't try an async prompt before that, because whatever you do it's gonna be super hacky and awkward.

If it's the case that that feature isn't coming any time soon (which is fine), then I think I'll go ahead regardless. 

Many of the most popular prompts for other shells are asynchronous. It might not be important to you (as you mentioned on gitter), but having their prompt be fast and informative in a big git project is probably one of the features that keeps people hooked on other shells. I want to see fish grow and I think an asynchronous prompt is actually one of the large features that would improve the user experience.

**Comment by faho** [comment]
>is there any work being done on that issue?

There is a shedload of preparatory work that has to be done. Try `git log --grep=concurrent` to see some of it.

**Comment by krobelus** [comment]
Also there are [several branches](https://github.com/ridiculousfish/fish-shell/branches/all) with lots of work on concurrent execution.

**Comment by IlanCosman** [comment]
I'm willing to let this issue die for now in favor of waiting for concurrence. I have no need of cross-process events besides asynchronicity. Can we label this issue `RFC` for a while to see if anyone else has a use case?

**Comment by mattgreen** [comment]
I doubt there are use cases beyond async prompts at this time. Besides, async prompts are possible in limited use cases anyway, making this a bit more niche.

As it stands today, the existing event mechanism is quite close to a message passing paradigm already, which is good. Using something like that to communicate between threads/processes would unify in/out-process communication, and avoid synchronization issues inherent to lower-level POSIX constructs. Other nice thing is message passing imposes no constraints on concurrency mechanisms that are used. fish is free to decide to implement concurrency as threads or processes. 

At that point, I'm not sure I'd call it "events" anymore; you could implement events in terms of this anyway.

**Comment by faho** [comment]
Okay, since it appears the only use case is async prompts, and those are going to be much nicer with the logic *in the same fish*, I'm closing this.

Thanks for filing!
