### ISSUE TITLE
fish no longer exits a loop on SIGINT

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#7259]
When the loop precondition does not return non-zero with SIGINT, fish does not exit a loop.

Under fish 2.3.1, this could be aborted by holding down ^C until the timing coincided with the parser control of the tty:

```fish
while true
    timeout 0.1 ping 127.0.0.1
end
```

Under fish master, ^C is posted to the terminal likely indicating that the parser is regaining control of the tty, but at no point does the loop terminate.

**Comment by ridiculousfish** [comment]
Phew, well spotted. `while true ; sleep 1 ; end` also repros. Bisects to 2a4c545b21b265613b61695dedb8b0065897c787.
