### ISSUE TITLE
--on-variable does not trigger in other shell when variable is set to the same value

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7260]
The following functions are defined in the `functions` directory:

```fish
function on_fish_prompt --on-event fish_prompt
    set -U foo (math $foo +1)
end
```

```fish
function on_foo --on-variable foo
    echo hello
end
```

![ChangingFoo](https://user-images.githubusercontent.com/6318351/89972983-0df77800-dc14-11ea-8809-7c0114ebcaa4.gif)

As you can see in this gif, the first shell emits the `fish_prompt` event and iterates `foo` which in turn triggers the `--on-variable` event of `on_foo` in both shells, echoing hello.

In this second gif, the `on_fish_prompt` does not iterate foo, but sets it to a constant value.

```fish
function on_fish_prompt --on-event fish_prompt
    set -U foo 5
end
```

![StaticFoo](https://user-images.githubusercontent.com/6318351/89972990-12239580-dc14-11ea-9276-8de0aa0a8cc3.gif)

In the first shell, the `--on-variable` event works as it's supposed to, emitting when the value of `foo` is interacted with, regardless of if it changed. The second shell only emits the event when `foo` is changed.

Clearly there's an inconsistency here that should be addressed.

<div align="center">
<sub>

fish, version 3.1.2

Linux archlabs 5.7.12-arch1-1 #1 SMP PREEMPT Fri, 31 Jul 2020 17:38:22 +0000 x86_64 GNU/Linux

xterm-256color

Clean fish

</sub>
</div>

**Comment by krobelus** [comment]
Should it fire only when the value is changed? :thinking:

**Comment by faho** [comment]
>Should it fire only when the value is changed? thinking

Is there a need to *react* when a variable doesn't change?

@IlanCosman As always: What are you trying to do with this?

This looks to me that the idea was that you wouldn't react to a variable that was set to the same thing again, because that's.. well, the same thing again.

**Comment by IlanCosman** [comment]
That title is not fully accurate @faho as `--on-variable` _does_ trigger when a variable is set to the same value, just not when it's in a different process.

@krobelus I'd say `--on-variable` should trigger when the variable is first set, altered, or erased.

I agree @faho, there isn't a need to react when the variable doesn't change. I wasn't making any point here, merely pointing out an inconsitency with `--on-variable`, universal variables, and different processes.

**Comment by IlanCosman** [comment]
`--on-variable` shouldn't react differently in different processes when a variable in both is interacted with.

**Comment by faho** [comment]
Ah, okay. Yeah, this is probably the universal variables not syncing because they didn't change.

I feel the correct approach is to not trigger the handler even in the current shell, but that probably needs some more care.

**Comment by faho** [comment]
Okay, this basically *can't* work with universal variables. We have no way of knowing if the value was set again in another shell because in the file it just has the value. This has been clarified in the docs for #8010.

Sorry, you're gonna have to find something else.
