### ISSUE TITLE
Hitting <ENTER> without entering anything no longer triggers `fish_postexec`

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#7261]
Using https://github.com/fish-shell/fish-shell/commit/c46489bde82d7c297f1c209518519f34cbcd3255

---

### Problem

Hitting `<ENTER>` with a blank commandline does not seem to trigger `fish_postexec` anymore

### Question

Is there another way to achieve the following? It used to work but broke somewhere in the last 3-6 months:

```fish
function __fish_prompt_job_count --on-event fish_postexec
    set -e PROMPT_JOB_COUNT
    set job_count (count (jobs))
    test "$job_count" -eq 0 || set -g PROMPT_JOB_COUNT "[$job_count] "
end

function fish_prompt
    printf '%s$ ' "$PROMPT_JOB_COUNT"
end
```

Now type:

```fish
$ sleep 1 &

# Prompt now updates to
[1] $

# Wait for 1 second to elapse and hit <ENTER> a few times to
# see if there are any background jobs still running
[1] $
[1] $
[1] $
```

This used to update to `$` after 1 second, but now the old value of `$PROMPT_JOB_COUNT` is displayed because `fish_postexec` is not firing anymore.

---

EDIT: Seems this was changed in https://github.com/fish-shell/fish-shell/pull/7085 – is there any way to efficiently achieve what I'm after? Is there a new event I can subscribe to?

**Comment by zx8** [comment]
Never mind, solved it like this:

```fish
function __fish_prompt_job_count --on-event fish_prompt_will_update
    set -e PROMPT_JOB_COUNT
    set job_count (count (jobs))
    test "$job_count" -eq 0 || set -g PROMPT_JOB_COUNT "[$job_count] "
end

function fish_prompt
    emit fish_prompt_will_update
    printf "%s~ " "$PROMPT_JOB_COUNT"
end
```

**Comment by zanchey** [comment]
There's a `fish_prompt` event, which might help.
