### ISSUE TITLE
[Question] How to change the order of completions when using Tab completion?

### ISSUE THREAD

**Issue by nlpsuge** [fish-shell/fish-shell#7267]
## Fish verison I'm using
I'm using fish, version 3.1.2.

## How to reproduce my issue
It's pretty easy. Just type the command `ll`, and then hit Tab, a number files should appear. You'll find that they are actually sorted by name.

## What I want
I'm looking that if there are some ways to sort the file by the create time not the name.

I've done some searchs on google or official document, but I can not find the answer.

Big thanks, guys.

**Comment by zanchey** [comment]
You need to implement your own completion, but fortunately, it's not too hard. The `--keep-order` flag to `complete` and the `-t` flag to `ls` are what you need.

Create a new file in `.config/fish/completions/ll.fish`, which contains:

```fish
complete --command ll --wraps ls 
complete --command ll --keep-order --exclusive --arguments '(command ls -dpt (commandline -ct)*)'
```

**Comment by nlpsuge** [comment]
> You need to implement your own completion, but fortunately, it's not too hard. The `--keep-order` flag to `complete` and the `-t` flag to `ls` are what you need.
> 
> Create a new file in `.config/fish/completions/ll.fish`, which contains:
> 
> ```fish
> complete --command ll --wraps ls 
> complete --command ll --keep-order --exclusive --arguments '(command ls -dpt (commandline -ct)*)'
> ```

Hi,

When I run `ll`, it works well. 
But when I run `ll who`, in which the who is a word of a file's name, I got this output:
$ ll whofish: No matches for wildcard “(commandline -ct)*”. See `help expand`.
command ls -dpt (commandline -ct)*
                ^
in command substitution
ll who

**Comment by zanchey** [comment]
Right, it works in development builds but not in 3.1.2, sorry.

Try:

```fish
complete --command ll --wraps ls 
complete --command ll --keep-order --exclusive --arguments '(set -l token (commandline -ct); command ls -dpt $token* )'
```

**Comment by krobelus** [comment]
(also on the development build, `ls (commandline -ct)*` will throw an error if there is no glob match - so you always need to use `set` here to get `nullglob` behavior)

**Comment by faho** [comment]
Okay, the question here appears to be answered, closing!
