### ISSUE TITLE
fish crashes when recieving USR1 signal

### ISSUE THREAD

**Issue by amirzlf** [fish-shell/fish-shell#7269]
I tried to send a USR1 signal to a child process but used fish's pid by mistake.Surprisingly, fish crashed.

reproduce:
```
kill -USR1 (pgrep -n fish)
```
Is it a normal behavior?
I'm using fish version 3.1.2 on archlinux.

**Comment by faho** [comment]
Crashing is never normal behavior, no.

I can reproduce this with 0e8761bc7.

**Comment by faho** [comment]
Oh, no, it doesn't actually *crash*. It just doesn't handle SIGUSR1, so it defaults to exiting.

This is normal, and what e.g. bash also does.

**Comment by ridiculousfish** [comment]
Note [you can trap SIGUSR1](https://github.com/fish-shell/fish-shell/blob/master/tests/checks/self-signal-usr1.fish) and then fish won't exit.

**Comment by amirzlf** [comment]
> Oh, no, it doesn't actually crash. It just doesn't handle SIGUSR1, so it defaults to exiting.


so maybe there is something wrong with my terminal emulator(konsole) that doesnt get closed when fish exits?
instead it shows me : ` warning program /usr/bin/fish crashed`

> Note you can trap SIGUSR1 and then fish won't exit.

thank you.i didn't know about that syntax.

**Comment by krobelus** [comment]
Looks like Konsole interprets an exit caused by a signal as crash - which is true in many cases, so this is not surprising. Maybe Konsole should show the signal name to provide more context?
