### ISSUE TITLE
Case insensitive history-search-backward

### ISSUE THREAD

**Issue by jaelpark** [fish-shell/fish-shell#7273]
```
fish --version
fish, version 3.1.2-1228-g65e1c42a2
```

Is it possible to have `history-search-backward` perform searches case insensitively (when using up and down arrow keys)? I didn't find information on this. It would be a very helpful feature.

**Comment by faho** [comment]
Okay, I made it so history search is case-insensitive unless there's an uppercase character.

So if you look for "term" you'll find "TERM" and "term" and "TERm", if you look for "TERm" you'll only find "TERm".
