### ISSUE TITLE
install internal fish tools in $libexecdir

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#728]
The FHS says that binaries not intended to be executed directly by users or shellscripts should be stored in `$PREFIX/libexec` or `$PREFIX/lib`. We should put `fish_pager` and possibly `fish_indent` in this directory.

**Comment by floam** [comment]
I think this stuff should go in `$PREFIX/libexec/fish`:

1. `deroff.py`
2. `create_manpage_completions.py`
3. `webconfig.py`
4. `fish_key_reader`

**Comment by zanchey** [comment]
All the Python scripts are platform-independent, so I think they should stay in `$PREFIX/share`. `fish_key_reader` is supposed to be executed by end-users (occasionally), isn't it?

**Comment by floam** [comment]
> fish_key_reader is supposed to be executed by end-users (occasionally), isn't it?

Yeah - I think you're right. If it was purely a debug tool we pointed people at for getting help or just something used in our scripts, that'd be different.

**Comment by floam** [comment]
`All the Python scripts are platform-independent, so I think they should stay in $PREFIX/share.` 

What is the distinction with platform dependent executables vs. compiled binaries?

**Comment by floam** [comment]
`hier (7)` (NetBSD)

    share/	   architecture-independent text files
    libexec/ system daemons & system utilities (executed by other
                          programs)

FreeBSD has `s/text/data`

**Comment by faho** [comment]
@floam: I don't think we have much to gain here. We already ship that stuff out of the user's normal reach (so they don't run it accidentally).

libexec would just add another directory to our installation, and one that I know for a fact isn't used on arch - they put everything into /usr/lib/$packagename.

**Comment by floam** [comment]
Actually, the thinking I was having was to make it *easier* to run things like update_manpage_completions.py (which has a nice interface itself, but not through our wrapper), or the web server directly, by adding `$libexecdir` to $PATH in local scope when launching tools like this from our own scripts, without `eval` $__fish_datadir/webconfig/webconfig.py hacks being necessary.

Or, if you're a fish developer, you might be the kind of person who keeps his interactive $PATH boosted. It struck me as *annoying* in the past and I got excited when it occurred to me it might be *wrong* :) It's not a big deal, I'll live.

**Comment by faho** [comment]
> adding $libexecdir to $PATH in local scope when launching tools like this from our own scripts

That's an interesting idea, but also possible with $__fish_datadir, no? I think this might also be an issue if people ship another webconfig.py (which they _probably_ don't), and then we call that one (which isn't quite the same as calling the wrong "grep" - that's a well-known name that you really shouldn't use for something incompatible).

**Comment by floam** [comment]
> (which isn't quite the same as calling the wrong "grep" - that's a well-known name that you really shouldn't use for something incompatible).

**Comment by floam** [comment]
> (which isn't quite the same as calling the wrong "grep" - that's a well-known name that you really shouldn't use for something incompatible).

I'm probably overestimating how bizzaro it is having to dig through the directories to find our `fish_indent`, etc. lest `$PATH` serves up the wrong one.

Though I'd probably rather it be called fish_config.py - or you can also make a `fish` folder in libexec. But of course: we could also just make that existing tools/ dir (after moving over the web server script) do the same thing with a compiled in component one could easily append to $PATH if you wanted. 

At any rate, closing this as that'd be a separate discussion from this packaging/OS directory hierarchy spitballing here which doesn't really matter.
