### ISSUE TITLE
Fish > 2020/08/21 doesn't repaint prompt after Ctrl+L

### ISSUE THREAD

**Issue by ronjouch** [fish-shell/fish-shell#7280]
Debug info:

- `fish --version`: `3.1.2-1246-gb6a57a249`
- `uname -a`: `Linux xps 5.8.3-050803-generic #202008211236 SMP Fri Aug 21 12:38:46 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- `echo $TERM`: problem reproducible in both Kitty/`xterm-kitty` and GnomeTerm/`xterm-256color`
- Reproducible in a fresh fish (`sh -c 'env HOME=$(mktemp -d) fish'`): yes!

Since recent commits, Ctrl+L fails to re-paint my prompt.

Steps to reproduce:

1. Press Ctrl+L

Expected: screen is cleared and prompt is repainted

Actual: screen is cleared but prompt is not repainted (thus, screen remains black)

**Comment by krobelus** [comment]
I can reproduce by pressing Ctrl+L twice without moving the cursor or typing other keys in between.

**Comment by ronjouch** [comment]
> I can reproduce by pressing Ctrl+L twice without moving the cursor or typing other keys in between.

@krobelus correct, same for me. Thanks for the precision.

**Comment by ridiculousfish** [comment]
I'm going to remove all the redraw coalescing logic - this may have been important when there was uncontrolled redraw but I don't think it adds any value now. Thanks for reporting this!
