### ISSUE TITLE
Running command at login not working

### ISSUE THREAD

**Issue by GregTheHun** [fish-shell/fish-shell#7285]
```
greg@manjaro:~
➤ fish --version
fish, version 3.1.2
greg@manjaro:~
➤ uname -a
Linux manjaro 5.7.15-1-MANJARO ...(intentionally blocked)...
greg@manjaro:~
➤ echo $TERM
xterm-256color
greg@manjaro:~
➤ sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
greg@manjaro /h/greg> status
This is not a login shell
Job control: Only on interactive jobs
```

So, with the above information, I've noticed that running this command:
```rclone mount gdrive: /path/to/gDrive/ &```

Both just in the terminal and in the ```~/.profile``` file allows me to automatically mount my Google Drive folder. However, trying to add it to ```~/.config/fish/config.fish``` does not run for some reason. Maybe I have the command wrong for login.

Ultimately, what I would love it to do is run the above command at login to xfce environment, and when I logout, reboot, or shutdown, it would unmount it first.

**Comment by faho** [comment]
Well, is fish your login shell? Have you done `chsh` and rebooted?

If you start a login shell with `fish -l` does that start rclone (see `jobs`)?

Note that starting services isn't something a login shell is actually good at. Most likely using a systemd service would suit your needs much better - see https://github.com/rclone/rclone/wiki/Systemd-rclone-mount.

**Comment by GregTheHun** [comment]
Yeah, actually, this solution did work. All I had to change was the directory that it mounts to. Thanks for the pointer!
