### ISSUE TITLE
Tab completion entries aren't always cleaned up properly

### ISSUE THREAD

**Issue by rien333** [fish-shell/fish-shell#7289]
Somewhere in the last two days, I upgraded fish to the newest commit on github. Afterwards, going into tab completion mode, then cycling through options and selecting one, often (but not always) results in  not all the options being cleared off the screen. See [this asciinema](https://asciinema.org/a/45aP5c2XezBrgJP1WBWv8650q) for a visual demonstration.

This problem is reproducible when launching fish using `sh -c 'env HOME=$(mktemp -d) fish'`.

## System info ##

``` console
$ fish --version
fish, version 3.1.2-1258-g81d87d1c7
$ uname -mor
5.8.3-arch1-1 x86_64 GNU/Linux
$ echo $TERMINAL
kitty
```

**Comment by rien333** [comment]
Thank you for the quick fix, @krobelus. However, I think I might have noticed more drawing oddities subsequent to the recent changes in the redrawing code (i.e. those from the last few days). In particular, running `sleep 10 &`, pressing <kbd>Ctrl+d</kbd>, causes my prompt to not be redrawn . I can open a new issue if needed. 

 I cannot reproduce aforementioned "odd" behavior on fish 3.2.1 (stable).

**Comment by krobelus** [comment]
@rien333 Good catch! The same problem exists for parser error messages, for example when typing something like <kbd><</kbd> <kbd>Return</kbd>, the prompt is not redrawn below the error message.
 I added a fix to trigger redraws in these cases. Not sure if this is the right way to do it - I haven't fully understood the new repainting logic - but it seems to work.
Thanks for reporting! I wonder if there are more places where we are missing redraws.
