### ISSUE TITLE
Replace command-not-found event with a known function

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#7293]
Fish has long had the `fish_command_not_found` event that is triggered when a command isn't known.

It's always been a bit weird to me that this used the event machinery because

- it makes it awkward to *replace* the handler (because it has already been registered by the time you try)
- there is no real use for multiple handlers for this (unlike eg. pre-exec)

So really, this should just be a function that is invoked by name, `fish_command_not_found`, and if that isn't defined the default "fish: command 'choochoo' not found" one should take over.

This would also allow us to remove some rather weird logic from __fish_config_interactive and just put it in a normal function file.

**Comment by zanchey** [comment]
Sounds good. There's a reasonable number of event handlers in the wild, so perhaps as an initial implementation a `fish_command_not_found` function should just emit the event?

**Comment by faho** [comment]
Thankfully this is even easier. To allow overriding, we currently already check for a function of a certain name (because you don't want 2 handlers at the same time):

https://github.com/fish-shell/fish-shell/blob/ee84223138cf0ff5f29df06deb33e10ab87fd530/share/functions/__fish_config_interactive.fish#L265-L266

So we can just check that and either call that function or copy it.
