### ISSUE TITLE
Is it possible to stop cursor blinking?

### ISSUE THREAD

**Issue by hao-lee** [fish-shell/fish-shell#7294]
After entering fish shell, the cursor starts to blink. If I exit fish shell and return to bash, the cursor is still blinking unless I `reset` the terminal.

**Comment by faho** [comment]
The only case fish even touches the cursor is if you're using vi-mode. It sets the cursor appearance to what's mentioned in $fish_cursor_MODE, where MODE is one of the bind modes insert, default, visual, replace, as well as $fish_cursor_unknown, which defaults to "block blink".

If you don't want those to apply, change them.

**Comment by hao-lee** [comment]
Thanks! Get it !

**Comment by kmabadshah** [comment]
in your config.fish
-----------------------
set fish_cursor_unknown block
