### ISSUE TITLE
RfC: update completion configs to use long-form flags (e.g. --no-files instead of -f)

### ISSUE THREAD

**Issue by motevets** [fish-shell/fish-shell#7299]
As I've been looking through the completion configs/scripts, I've had some difficulty grokking them because they are using shorthand flag. I was taught—and it's my humble opinion that—scripts should be written using long-form flags for readability, and shorthand flags should be reserved for used in the command-line.

I'm proposing that:
1. we update the current completions scripts  (i.e. those in `/share/completions`) from using shorthand flags to long-form flags
2. we encourage contributors to follow this convention going forward.

If the consensus in this RfC is to go ahead with the proposal, I would be happy to work on it, and make a PR. I realise that this may come off as nitpicking. I don't intend it to be. I think it would lower the learning curve for future contributors/users.

Thanks for your comments and consideration. 🙂

**Comment by faho** [comment]
I don't think we have enough flags here to really matter, and most of them have a good mnemonic.

"-d" is description
"-a" is argument
"-f" is no-*f*iles (the default is to have them)
"-n" is coNdition, which isn't a great mnemonic, but it's typically the one with the condition right after it two lines up. 

And since completion lines tend to be long, using long options here just makes the lines super long.

**Comment by zanchey** [comment]
I prefer the long arguments, especially for `a`/`-n`/`-f`/`-x`, but `--description` was changed to `-d` in 68527ff20c68d2ef2eee999793c61003b939856d to save installation space.

**Comment by mqudsi** [comment]
> And since completion lines tend to be long, using long options here just makes the lines super long.

This is my rationale for keeping the current behavior as well.

**Comment by faho** [comment]
Okay, it doesn't appear like there's consensus to do this, so I'm closing it.

**Comment by xiruizhao** [comment]
Long options are more readable. So in a few months or years later, when you forget everything about fish, you will still understand what your code is doing without checking man pages. I think it's appropriate to use short options right after a line of long options (similarly to the rule that full spellings of abbreviations must be stated on first appreance). For example:
```
complete --command acpi --short-option b --long-option battery --description 'Show battery information'
complete -c acpi -s B -l without-battery -d 'Suppress battery information'
complete -c acpi -s t -l thermal -d 'Show thermal information'
```
This would be more friendly, right?
