### ISSUE TITLE
Right prompt not working quite right

### ISSUE THREAD

**Issue by Darkshadow2** [fish-shell/fish-shell#7302]
fish: fish 3.1.2-1284-g244feee69
OS: macOS 10.15.5, 10.11.6, and OpenBSD 6.2

For a little while now, my right prompt hasn't been showing. Since there was no large outcry of the right prompt not showing, I knew it had to be something in my configuration. I've been busy, and my right prompt is just the date, so I hadn't looked into it until now. I did find out what it was, but there is definitely a bug here.

I had my right prompt defined in the same file as the regular prompt. It's in my $HOME functions dir, as `fish_prompt.fish`.  I did this so long ago I didn't even remember that I had put them together like that. A change caused that to stop working, although `fish_right_prompt` is actually defined (if I did `type fish_right_prompt` it showed that it was loaded from my `fish_prompt.fish` file). Separating it out into its own file (`fish_right_prompt.fish`) and launching a new fish caused it to start showing again.

But, that's not all there is to this. In testing this, I found out that if you start fish without a right prompt defined, there is no way to add one later.  A simple test shows this: do `sh -c 'env HOME=$(mktemp -d) fish'` and then try adding a simple right prompt:

```fish
function fish_right_prompt
    echo hello
end
```

...and you'll see that the right prompt doesn't show at all. It has to be present when fish starts.  And that's not all.  If you start fish with a right prompt defined, and then delete it with `functions -e fish_right_prompt`, fish starts complaining that `fish_right_prompt` is an unknown command **and** prints

```
fish:
fish_right_prompt
^
in command substitution
```

as well. It will keep doing this at every prompt redraw until you redefine a `fish_right_prompt` function.

This bisects to 272ca37582278ba1edbc3101c6855864bcd1b926

**Comment by faho** [comment]
Yeah, the new const config object only checked at startup for a right prompt, just to define the prompt function *name*.

I've changed it so it checks every time it runs the prompt - should be fast since it should already be loaded.
