### ISSUE TITLE
fds.fish test fails on NetBSD because fd 3 is open

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#7304]
With b521ca4875260ebf39e610dc4ad7a513819a2f17 on NetBSD 9.0:

```
Testing file checks/fds.fish ... Failure:

  The CHECK on line 6 wants:
    0 1 2

  which failed to match line stdout:1:
    0 1 2 3

  Context:
    0 1 2 3 <= does not match '0 1 2'
    1 2 3
    1 3
    0 1 2 3
    0 1 2 3
    0 1 2 3

  when running command:
    ../test/root/bin/fish -C "set helper ../test/root/bin/fish_test_helper" checks/fds.fish
```

It's possible this has always worked this way or is acceptable (we probably just receive fd 3 and don't bother closing it), in which case we can just regex-match it in the test.

But since it's behavior I'm not familiar with I thought I'd open an issue.

**Comment by faho** [comment]
Bisects to 65e1c42a2b5bd94f18346c80e1e151e82fc744d1.

Tagging @ridiculousfish because I still have no single solitary clue what a "topic_monitor" even does.

**Comment by ridiculousfish** [comment]
Oh no - BSD implements anonymous semaphores using a file descriptor under the hood. That fd doesn't get marked as CLOEXEC. Guess we're not using semaphores on BSD...
