### ISSUE TITLE
accidental duplicate test?

### ISSUE THREAD

**Issue by marcusatiliusregulus** [fish-shell/fish-shell#7307]
(i am on 4f0f5daea)

in file tests/checks/andandoror.fish
lines 115 to 120 and
lines 122 to 127
seem like the same check. is this intended? (i only started learning about fish yesterday...)

regards

**Comment by dimaqq** [comment]
Code in question:

https://github.com/fish-shell/fish-shell/blob/326fd8d75065d73eac01ca1e7f496f9c121c656b/tests/checks/andandoror.fish#L114-L127

**Comment by faho** [comment]
Yeah, that's a duplicate, nice catch!
