### ISSUE TITLE
Fish build error on macOS with external ncurses

### ISSUE THREAD

**Issue by adamjstewart** [fish-shell/fish-shell#7310]
I'm trying to build fish on macOS 10.15.6 with Apple Clang 11.0.3. I'm using externally installed packages for PCRE2, gettext, and ncurses. When I build, I see the following error:
```
[ 98%] Linking CXX executable fish_indent
/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/cmake-3.18.2-hkd23wphpsyo3wminmu62gvusohcoh5n/bin/cmake -E cmake_link_script CMakeFiles/fish_indent.dir/link.txt --verbose=1
/Users/Adam/spack/lib/spack/env/clang/clang++  -Wall -Wextra -Wno-implicit-fallthrough -Wno-comment -Wno-address -Wno-strict-aliasing -Wno-redundant-move  -O2 -g  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.9 -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/fish_indent.dir/src/fish_indent.cpp.o CMakeFiles/fish_indent.dir/src/print_help.cpp.o -o fish_indent  libfishlib.a /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/ncurses-6.2-wr2lahob7rnaawch75w2p5rce4qk3qul/lib/libcurses.dylib /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/pcre2-10.35-pon6aeocnlknue3muwy4rmo2gskyxixi/lib/libpcre2-32.dylib /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/gettext-0.20.2-gdqz4kwqysrnkryiodq4ezmjvugcu6ur/lib/libintl.dylib 
Undefined symbols for architecture x86_64:
  "_cur_term", referenced from:
      init_input() in libfishlib.a(input.cpp.o)
      process_clean_after_marking(parser_t&, bool) in libfishlib.a(proc.cpp.o)
      escape_code_length(wchar_t const*) in libfishlib.a(screen.cpp.o)
      s_write(screen_t*, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, unsigned long, std::__1::vector<highlight_spec_t, std::__1::allocator<highlight_spec_t> > const&, std::__1::vector<int, std::__1::allocator<int> > const&, unsigned long, page_rendering_t const&, bool) in libfishlib.a(screen.cpp.o)
      s_reset(screen_t*, screen_reset_mode_t) in libfishlib.a(screen.cpp.o)
      screen_force_clear_to_end() in libfishlib.a(screen.cpp.o)
      calc_prompt_layout(std::__1::basic_string<wchar_t, std::__1::char_traits<wchar_t>, std::__1::allocator<wchar_t> > const&, layout_cache_t&) in libfishlib.a(screen.cpp.o)
      ...
  "_setupterm", referenced from:
      init_curses(environment_t const&) in libfishlib.a(env_dispatch.cpp.o)
      initialize_curses_using_fallback(char const*) in libfishlib.a(env_dispatch.cpp.o)
  "_tigetflag", referenced from:
      init_curses(environment_t const&) in libfishlib.a(env_dispatch.cpp.o)
Undefined symbols for architecture x86_64:
  "_tparm", referenced from:
      tparm_solaris_kludge(char*, long, long, long, long, long, long, long, long, long) in libfishlib.a(fallback.cpp.o)
  "_cur_term", referenced from:
      init_input() in libfishlib.a(input.cpp.o)
      outputter_t::write_color(rgb_color_t, bool) in libfishlib.a(output.cpp.o)
      write_foreground_color(outputter_t&, unsigned char) in libfishlib.a(output.cpp.o)
      write_background_color(outputter_t&, unsigned char) in libfishlib.a(output.cpp.o)
      outputter_t::set_color(rgb_color_t, rgb_color_t) in libfishlib.a(output.cpp.o)
      write_color_escape(outputter_t&, char const*, unsigned char, bool) in libfishlib.a(output.cpp.o)
      update_fish_color_support(environment_t const&) in libfishlib.a(env_dispatch.cpp.o)
      ...
  "_tputs", referenced from:
      outputter_t::set_color(rgb_color_t, rgb_color_t) in libfishlib.a(output.cpp.o)
      writembs_check(outputter_t&, char const*, char const*, bool, char const*, long) in libfishlib.a(output.cpp.o)
      outputter_t::term_puts(char const*, int) in libfishlib.a(output.cpp.o)
  "_setupterm", referenced from:
      init_curses(environment_t const&) in libfishlib.a(env_dispatch.cpp.o)
      initialize_curses_using_fallback(char const*) in libfishlib.a(env_dispatch.cpp.o)
  "_tigetflag", referenced from:
      init_curses(environment_t const&) in libfishlib.a(env_dispatch.cpp.o)
  "_tparm", referenced from:
ld: symbol(s) not found for architecture x86_64
      tparm_solaris_kludge(char*, long, long, long, long, long, long, long, long, long) in libfishlib.a(fallback.cpp.o)
  "_tputs", referenced from:
      outputter_t::set_color(rgb_color_t, rgb_color_t) in libfishlib.a(output.cpp.o)
      writembs_check(outputter_t&, char const*, char const*, bool, char const*, long) in libfishlib.a(output.cpp.o)
      outputter_t::term_puts(char const*, int) in libfishlib.a(output.cpp.o)
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [fish_key_reader] Error 1
make[1]: *** [CMakeFiles/fish_key_reader.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
The full build logs are attached:
* [build log](https://github.com/fish-shell/fish-shell/files/5177265/spack-build-out.txt)
* [build env](https://github.com/fish-shell/fish-shell/files/5177266/spack-build-env.txt)

Any idea what could be causing this? I'm updating the fish recipe in the [Spack](https://spack.io) package manager.

**Comment by ridiculousfish** [comment]
This looks like it's failing to find symbols in the ncurses library. On Mac this is typically in `/usr/lib/libcurses.dylib` but in the attached build it's using a separately built dylib.

What does this show:

    nm /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/ncurses-6.2-wr2lahob7rnaawch75w2p5rce4qk3qul/lib/libcurses.dylib | grep setupterm


on a build using Mac system ncurses it shows:

    00000000000010c3 T __nc_setupterm
    0000000000016cb5 T _setupterm

indicating that setupterm is present in the lib.

**Comment by adamjstewart** [comment]
This is what I get:
```console
$ nm /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/ncurses-6.2-wr2lahob7rnaawch75w2p5rce4qk3qul/lib/libcurses.dylib | grep setupterm
                 U __nc_setupterm
```
Let me play around with some of the flags I used to build ncurses.

**Comment by adamjstewart** [comment]
@ridiculousfish it looks like I was building ncurses with `--with-termlib`, `--enable-termcap`, `--enable-getcap`, etc. These flags cause the termlib features to be split into a separate library. Once I removed those, the build succeeds but I see a lot of warnings during installation:
```
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/install_name_tool: for: /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/fish-3.1.2-qy2zwrihqhiial4eor6i5p4llmyzhdxu/bin/fish_key_reader (for architecture x86_64) option "-add_rpath /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/pcre2-10.35-pon6aeocnlknue3muwy4rmo2gskyxixi/lib" would duplicate path, file already has LC_RPATH for: /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/pcre2-10.35-pon6aeocnlknue3muwy4rmo2gskyxixi/lib
```
Although the installation completes, the resulting binaries don't work:
```console
$ fish
dyld: Library not loaded: /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/ncurses-6.2-boruqq45nid2ktctev5z4634miq3z77l/lib/libncurses.6.dylib
  Referenced from: /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/fish-3.1.2-qy2zwrihqhiial4eor6i5p4llmyzhdxu/bin/fish
  Reason: no suitable image found.  Did find:
	/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/ncurses-6.2-boruqq45nid2ktctev5z4634miq3z77l/lib/libncurses.6.dylib: code signature in (/Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/ncurses-6.2-boruqq45nid2ktctev5z4634miq3z77l/lib/libncurses.6.dylib) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.
Abort trap: 6
```

**Comment by adamjstewart** [comment]
Looks like a duplicate of #6952, let me try `-DMAC_CODESIGN_ID=OFF`.

**Comment by adamjstewart** [comment]
`-DMAC_CODESIGN_ID=OFF` allows me to build master but not 3.1.2. Is a 3.2 release expected any time soon? If not, what patches would I need to backport to get 3.1.2 to work?

**Comment by adamjstewart** [comment]
P.S. Would you or anyone else like to be official "maintainers" of Spack's build recipe for fish? You don't need to be a Spack expert, it just gives us someone to ping when a user reports build issues or submits a PR to modify the recipe.

**Comment by ridiculousfish** [comment]
Yeah default-on codesigning was a mistake. For 3.1.2, assuming spack can apply a diff, you could patch the CMake file to prevent codesigning - just [comment out the command inside `CODESIGN_ON_MAC`](https://github.com/fish-shell/fish-shell/blob/Integration_3.1.2/CMakeLists.txt#L173). 3.2 has no date yet but resolves this.

re: maintaining Spack recipes, we're happy to look at build issues here but don't have the bandwidth to package it

**Comment by adamjstewart** [comment]
Thanks for all the help! I think that resolves all of my issues.

**Comment by adamjstewart** [comment]
Coming back to this issue, if I build `ncurses` with `--with-termlib`, `--enable-termcap`, `--enable-getcap`, etc., the `_setupterm` symbol is instead part of the `libtinfo.dylib` library:
```console
$ nm /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-11.0.3/ncurses-6.2-wr2lahob7rnaawch75w2p5rce4qk3qul/lib/libtinfo.dylib | grep setupterm
000000000000ba40 T __nc_setupterm
000000000000c0a0 T _setupterm
```
I can get fish to correctly build against this installation if I add:
```
LDFLAGS=-ltinfo
```
Would it be possible to modify the CMake build stuff to inject this flag if it is needed?

**Comment by faho** [comment]
@adamjstewart Are you trying to build 3.1.2 or master?

Because 4a5f0f3a3dc51634cef0c282280e6be2a92804be should already be doing that.

**Comment by adamjstewart** [comment]
I was building 3.1.2, sounds like it's already been fixed, thanks!

**Comment by ckm2k1** [comment]
I apologize in advance for not posting this in an issue of it's own, but this is the most relevant place I could find considering the conversation in #6952 is locked. 

I ran into the same code signing problem where a Homebrew installed gettext (`/usr/local/opt/gettext/lib/libintl.8.dylib`) is not signed and although everything builds, fish crashes immediately with this error:
```
dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /Users/me/Programming/fish-shell/build/./fish
  Reason: no suitable image found.  Did find:
	/usr/local/opt/gettext/lib/libintl.8.dylib: code signature in (/usr/local/opt/gettext/lib/libintl.8.dylib) not valid for use in process using Library Validation: mapping process has no Team ID and is not a platform binary
	/usr/local/opt/gettext/lib/libintl.8.dylib: stat() failed with errno=1
fish: './fish' terminated by signal SIGABRT (Abort)
``` 

I was able to fix this, build fish and run it without resorting to turning off code signing or disabling gettext. The rough steps are below, but first you'll need to have a free Apple ID and Xcode installed.

(The system i'm running is: Mojave 10.14.6, XCode 11.3.1, gettext 0.21, Homebrew 2.5.2, building fish 3.1.2 from source.)

1. Open Xcode -> preferences. 
2. Under accounts, sign in with your Apple ID and wait until the Team and Role sections populate (I noticed this might take a few minutes.)
3. Once they're populated, click `Manage Certificates`, click the little plus sign on the bottom left corner of the dialog and click `Apple Development`. This will add a new certificate in your `login` keychain. 
4. Open Keychain Access and find the new certificate in your 'login' keychain. It will be called something like `Apple Development: ${YourNameProbably}`. (**you might be tempted to change the trust settings of this cert, DON'T**)
5. Drag this certificate to the `System` keychain. (Double check it's been added). Note down the full name of the certificate, you will need it in a moment.
6. Open a shell and find the path to the `libintl.8.dylib` on your system. In my case it was under `/usr/local/opt/gettext/lib/libintl.8.dylib`.
7. Run this command: `codesign --sign '$replace_this_with_your_cert_name' -f $replace_with_full_path_to_your_dylib`. If successful there will be no output.
8. You can verify if this worked by running: `codesign --verify --deep --strict --verbose=2 /$replace_with_full_dylib_path`. If it worked, you'll get output like this: 
```
/usr/local/opt/gettext/lib/libintl.8.dylib: valid on disk
/usr/local/opt/gettext/lib/libintl.8.dylib: satisfies its Designated Requirement
```
9. You can now rebuild `fish` from scratch, but you'll need to add `-DMAC_CODESIGN_ID='name_of_your_cert'` to the `cmake ..` command.
10. Enjoy your new fish!

**Comment by zanchey** [comment]
The problem with that is that it will blow up if gettext ever changes, so it's probably better not to sign at all.

**Comment by ckm2k1** [comment]
@zanchey You have a point but it's fairly easy to re-sign the `gettext` dylib in that case. 

I don't think my suggestion is a very good permanent solution, but for people who need gettext for translations it seems like a useful workaround that doesn't require turning code signing.
