### ISSUE TITLE
Cannot install fish on Debian 10 buster armhf

### ISSUE THREAD

**Issue by neheb** [fish-shell/fish-shell#7313]
Running the instructions on https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A3&package=fish , I cannot install it on my armhf system.

Looking at the binary packages, it seems only i386, arm64, and amd64 are available.

**Comment by zanchey** [comment]
I've turned the armhf package builds on (armv7l in OBS language) so they should be available now.
