### ISSUE TITLE
Interactive pager search broken

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#7318]
Using https://github.com/fish-shell/fish-shell/commit/f88106ef96b037aceb5da44003e04d80d04bc309

---

### Repro

```fish
$ cd (mktemp -d)
$ touch foo{bar,baz,boo}
$ ls foo<TAB>
# - CTRL-s to activate interactive search
# - Type "bar" (no quotes)
```

### Expect

"foobar" to be filtered as the only result

### Actual

All results are still shown, i.e. nothing happens.

**Comment by faho** [comment]
Pretty sure it's caused by  6d339df612a62992979f203235407cf283f576b - we probably don't redraw the pager anymore in this case.
