### ISSUE TITLE
Read file into environment variable?

### ISSUE THREAD

**Issue by tamis-laan** [fish-shell/fish-shell#7323]
I'm trying to read the content of a file into an environment variable in the following way using command substitution:
```
set VIMINIT (cat ~/.config/nvim/init.vim)
```
However all line breaks are removed in the command substitution process. Whats going on here?

**Comment by faho** [comment]
Command substitutions split their input on newlines by default.

To keep the input as one, use

```fish
set VIMINIT (cat ~/.config/nvim/init.vim | string collect)
```

**Comment by faho** [comment]
Okay, answer has been accepted, on stackoverflow.

**Comment by tamis-laan** [comment]
thnx for the help!!
