### ISSUE TITLE
Fish enters infinite repaint loop

### ISSUE THREAD

**Issue by ammgws** [fish-shell/fish-shell#7324]
fish, version 3.1.2-1340-g624d0b7e4: infinite loop
fish, version 3.1 release: OK

Simplest reproduction steps I've found so far:
```sh
mkdir -p /tmp/debug/.config/fish/functions
printf "function fish_right_prompt\n set --global __fish_git_prompt_use_informative_chars 1\n fish_vcs_prompt\n end" > /tmp/debug/.config/fish/functions/fish_right_prompt.fish
sh -c 'env HOME=/tmp/debug fish --debug=screen'
```

Observe screen repaint spam and unresponsive terminal.

[This](https://github.com/ammgws/dotfiles/blob/master/fish/.config/fish/functions/fish_right_prompt.fish) is my original fish_right_prompt that I started with. Setting any of those vcs prompt vars in the fish_right_prompt function causes this to occur. It only started happening a couple weeks or so ago. Will try bisect later if there's nothing obvious here...

**Comment by faho** [comment]
Pretty sure it's 47480b2dbd43dec4a7eca4e369ea4b7a0ee73e24.

**Comment by krobelus** [comment]
Okay the git prompt is automatically repainting itself when you change a configuration variable.
If you initialize the `__fish_git_prompt_use_informative_chars` outside the function definition it will not cause the loop.
Setting it inside the prompt will trigger `__fish_git_prompt_repaint` which calls `commandline -f repaint` which always executes another prompt.

I'd be okay with Control-L (`repaint`) not re-executing the prompt but there is some stuff that assumes it does (like `__fish_git_prompt_repaint`).

**Comment by faho** [comment]
We're gonna need some form of loop detection here - "don't repaint inside a repaint".

Everything else is just super counter-intuitive to stumble upon and awful to detect.

**Comment by krobelus** [comment]
Yeah I came to the same conclusion. We do the same for `complete -C`, see `builtin_complete_recursion_level`.
