### ISSUE TITLE
fish_command_not_found not have any output on Arch Linux

### ISSUE THREAD

**Issue by akiirui** [fish-shell/fish-shell#7327]
Since 34be1b4.

`fish_command_not_found` is run with `pacman -F` instead of output `fish: Unknown command: XXX`. (if remote repostorys database is synced)

Or ouput `warning: database file for 'core' does not exist (use '-Fy' to download)`. (if remote repostorys database is not synced)

If the remote repostorys database is synced. fish is not output anything, only return a exit status with code 127.

This makes the user does not know what he did.

And the `pacman -F` tooks long time in HDD (~5s), affected the experience for use.

**Comment by faho** [comment]
> If the remote repostorys database is synced. fish is not output anything, only return a exit status with code 127.

Fixed.

>Or ouput warning: database file for 'core' does not exist (use '-Fy' to download). (if remote repostorys database is not synced)

Well, it needs the file database, so do `pacman -Fy`.

>And the pacman -F tooks long time in HDD (~5s), affected the experience for use.

There's an alternative implementation using `pkgfile` that's much faster. Install that and we prefer it. There's nothing we can do about pacman being slow here, so the alternative is to not have a pacman-based handler *at all*.
