### ISSUE TITLE
Bigword movement doesn't handle non-print non-blank characters very well

### ISSUE THREAD

**Issue by lilyball** [fish-shell/fish-shell#7328]
Bigword movement uses `std::iswblank(c)` and `std::iswgraph(c)` in its implementation, and seems to make the assumption that any character is either blank or graph (or a control character which it doesn't care about). But in the BMP alone there are 6801 codepoints (on my machine running macOS 10.15.6) that are neither blank nor graph or control. Some of these are reserved codepoints, but many are not. For example, Σ (U+03A3 GREEK CAPITAL LETTER SIGMA). Given this, the implementation should probably be using `!std::iswblank(c)` anywhere it uses `std::iswgraph(c)`.

For that matter, newlines are whitespace but they aren't blank, which means bigword movement stops on every newline, which seems odd. So it should probably be using `std::iswspace` instead of `std::iswblank` (the former includes 8 characters the latter doesn't).

**Comment by faho** [comment]
>For that matter, newlines are whitespace but they aren't blank, which means bigword movement stops on every newline

Given how important newlines are, I'd call that correct.

**Comment by lilyball** [comment]
Bigword movement should not stop on newlines. It should stop on *words*. If I have several blank lines in a row, bigword movement should not step one newline at a time.

**Comment by faho** [comment]
I don't think it's a problem, but if you think it is, feel free to change it.

**Comment by krobelus** [comment]
> Bigword movement should not stop on newlines.

On current master, `forward-bigword` never stops on newlines. However this is also  inconsistent, because it doesn't stop if there is a word at the beginning of a line.
```

For example, on this commandline, `forward-bigword` will only stop at `indented`:
'


at-start-of-line

at-start-of-line

  indented

'
```

**Comment by krobelus** [comment]
Fixed that, it seems better now.
