### ISSUE TITLE
Equivalent of bash's "$0" variable in fish scripts

### ISSUE THREAD

**Issue by rseichter** [fish-shell/fish-shell#7329]
I have been searching for a long time now, but I cannot find an answer by myself: How can a fish script determine the full file system path of its own directory? A Python program can find its location using `__file__`, and in a bash script, the following works:

```bash
➤ cat /tmp/foo.bash
#!/usr/bin/env bash
echo I am a bash script and my home path is $(realpath $(dirname $0))

➤ cd ~ && bash /tmp/foo.bash
I am a bash script and my home path is /private/tmp
```

How can I achieve the same in fish 3.1.2? The following does *not* provide what I need:

```fish
➤ cat /tmp/foo.fish
#!/usr/bin/env fish
echo I am a fish script and my home path is (realpath $_)

➤ cd ~ && fish /tmp/foo.fish
I am a fish script and my home path is /Users/ralph
```

Instead of the script file location, `$_` returns the process current working directory, which does not help me. The question boils down to: What is the equivalent of bash's `$0` variable? I have found old mailing list threads which suggest that no such thing exists, while others suggested to use `$_`, but the latter does not work for me.

If no such feature exists in fish yet, I suggest adding two functions:

* fish_script_path: The full file system path for the script file executing this function.
* fish_script_directory_path: The full file system path of the directory which contains the script file executing this function.

**Comment by faho** [comment]
`status filename`, as in

```fish
echo I am a fish script and my home path is (status filename)
```

Also in the next release `status dirname` for just the directory, and `status basename` for just the file.

**Comment by rseichter** [comment]
> Also in the next release `status dirname` for just the directory, and `status basename` for just the file.

That is going to be enormously useful to me, thank you so much. Not being able to determine a script file's home directory has prevented me from porting many of my existing bash scripts to fish.

**Comment by faho** [comment]
To be clear, those are just shortcuts for `dirname (status filename)` and `basename (status filename)`. I decided that it's a frequent enough task that it's worth it, but it's absolutely doable without.

**Comment by rseichter** [comment]
For now, I am content using this:
```
#!/usr/bin/env fish
source (dirname (realpath (status filename)))/sibling-script.fish
```
The shortcuts will make things more convenient, of course.

**Comment by faho** [comment]
If you're sourcing anyway, the realpath is unnecessary.

**Comment by rseichter** [comment]
Sure, but mine was just an example. However, when dealing with Docker volumes, absolute paths are at times necessary.

**Comment by faho** [comment]
Alright, question has been answered so I'm closing the issue.
