### ISSUE TITLE
bind to "right" key not working

### ISSUE THREAD

**Issue by sekoenig** [fish-shell/fish-shell#7330]
I am trying to bind `forward-word` to the `right` arrow key: `bind -k right forward-word`.  After executing that I see
```
$ bind -k right
bind --preset -k right forward-char
bind -k right forward-word
```
However, this has no effect, the right arrow key still executes forward-char.  Binding `forward-word` to another key (e.g. TAB) works find, so it seems this issue is specific to the arrow keys.

I am using `fish, version 3.1.2` and the issue does occur when I try it with `sh -c 'env HOME=$(mktemp -d) fish'`.

My terminal is gnome-terminal on GNOME 3.36.4 in X11 mode.

**Comment by zanchey** [comment]
My suspicion is that your terminal and the terminfo database disagree on what the right arrow key actually does - running `fish_key_reader` and pushing the right arrow key will tell you what fish actually expects to see (my terminal uses `\e\[C`, for example, and fish's default bindings contain a number of these entries because of that).

**Comment by sekoenig** [comment]
Ah, indeed:
```
$ fish_key_reader
Press a key

              hex:   1B  char: \c[  (or \e)
(  0.073 ms)  hex:   5B  char: [
(  0.077 ms)  hex:   43  char: C
bind \e\[C 'do something'
```
And then `bind \e\[C forward-word` in fact does work.  Thank you!

Now, should this be marked as a bug?  At the very least I would argue this behavior is very surprising because it *seems* as if the `--preset` binding were working, while I understand now that I should have done
```
$ bind | grep forward char

bind --preset -k right forward-char
bind --preset \e\[C forward-char
bind --preset \cf forward-char
```
and overridden all of those.

So, here is a feature suggestion: something like "bind groups" perhaps, so that (making this up) `bind -g left ...` would affect all of the above.

**Comment by faho** [comment]
>Now, should this be marked as a bug?

It is, #2139. The issue is that your terminal sends something different from what it says in terminfo unless it's been set to "keyboard_transmit" mode, so fish would have to enable it, but that would then break other terminals.

**Comment by zanchey** [comment]
I think the concept of bind groups has some merit, though the annoyingness of breaking them apart if needed probably counteracts their usefulness - would have to try it and see, I think.

**Comment by sekoenig** [comment]
To continue brainstorming regarding the potential merit of bind groups, some questions/thoughts:

1. How many keys would this be useful/relevant for (besides the arrow keys, which I would put on the list)?
2. What exactly should the semantics be?  A naive approach would be that a hypothetical `bind -g ...` is merely a shortcut for all adding all the individual bindings.  But then that would probably lead to exactly the "annoyingness of breaking them apart" that you are referring to.  I think it might make sense to take let individual bindings take precendence over group bindings.  That however (I assume) would require a larger implementation effort.
3. What known cases are there where different terminals actually use the same sequence for different keys?
