### ISSUE TITLE
Line Wrapped Delete Hides Character

### ISSUE THREAD

**Issue by nixpulvis** [fish-shell/fish-shell#7332]
Deleting the first line-wrapped character deletes the character but also appears to delete the last character from the previous line. The character is not actually deleted, and will reappear if another character is typed. A GIF's worth a thousand words:
![delete-wrapped-issue](https://user-images.githubusercontent.com/715947/93036302-8a171e00-f60d-11ea-888a-8339f71fa785.gif)

    fish, version 3.1.2
    Arch Linux
    Tested in Alacritty and Kitty

**Comment by faho** [comment]
Duplicate of #6951
