### ISSUE TITLE
Make it possible to build manpages without building fish

### ISSUE THREAD

**Issue by a-vrma** [fish-shell/fish-shell#7333]
I want to contribute to the documentation but I don't think I can build it without having to build the entire C++ project. I tried the following:

```
cmake -S . -B build
cd build
make sphinx-manpages
```
and it started building the entire project. I didn't stick around to see when it would finish, but I have a feeling it would have taken a long time.

What I want to contribute is a move away from regular lists to [option lists](https://docutils.sourceforge.io/docs/user/rst/quickref.html#option-lists), which look a lot better on the terminal and browser and are semantically correct. Here is an example:

![screenshot-20200913-224658](https://user-images.githubusercontent.com/29077900/93038481-1bd55a00-f613-11ea-8306-c2a3eacf907f.png)

The top is an option list and the bottom is a bullet list. Another improvement would be to use line blocks in the synopsis, which would make the synopsis line up with the rest of the manpage (https://wiki.herzbube.ch/index.php/WritingManPages#Writing_a_man_page_in_reStructured_text).

**Comment by zanchey** [comment]
The problem is that the manpage documentation pulls the version number from `fish_indent --version`, which necessitates the build of virtually the whole project.

It could be taught to use the FISH-BUILD-VERSION-FILE machinery.

**Comment by faho** [comment]
>I didn't stick around to see when it would finish, but I have a feeling it would have taken a long time.

A full build takes about a minute on my machine, which isn't *super* beefy (but does have an m2 ssd). Longer than the ~10 seconds building the documentation would take, but it's not untenable, and also only necessary once - after that you can just rebuild the docs.

**Comment by a-vrma** [comment]
Well you are right, only a little more than a minute with Ninja. When I tried before it was with GNU Make and it felt like it was taking a minute on the first object file...

**Comment by faho** [comment]
Okay, I'm rejecting this.

It's possible to enable building *the man pages* without fish, but not the html docs because those use `fish_indent` (which actually parses fish script, so it needs most of fish).

And

>What I want to contribute is a move away from regular lists to option lists, which look a lot better on the terminal and browser and are semantically correct. Here is an example:

Well, if you tried that just on the man pages it might look okay, and then you'd open a PR and we'd look at the generated HTML and see that it wouldn't style correctly, and then you'd have to build the HTML anyway.

Also building fish isn't a terrible burden or time commitment, so the case for just building the man pages simply isn't there.

**Comment by a-vrma** [comment]
the HTML looks pretty good too imo
