### ISSUE TITLE
`type` should be a builtin

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#7342]
As you may have noticed, I've been working towards making fish more usable without its functions and config.fish.

Partly, this involves moving important things to C++.

Today's candidate: The `type` function.

It's an important function that's useful for interactive and non-interactive use, so it should just be a builtin.

My general idea is that fish should be *usable*, especially non-interactively, without any functions. That means things like `type` and `psub` would have to be included somehow, but compatibility things like `alias` and even `export` don't have to be (because you can just use `set -x`). Enhancement like with `cd` is _probably_ okay, if that's focused on interactive use?

**Comment by IlanCosman** [comment]
I was thinking of opening an issue similar to this simply because of how slow `type` is 👍

**Comment by faho** [comment]
Okay, it is done.

Now a time call is ~10us instead of ~200us. Yes, that is a factor of 20, but it is also *micro*seconds.

(also `type`s options are a bit of a mess)

**Comment by IlanCosman** [comment]
> Now a time call is ~10us instead of ~200us. Yes, that is a factor of 20, but it is also _micro_seconds.

That's interesting, `time type fish` for me on my arch VM takes ~3.4ms, and on my Macbook Air it's 2-4ms. Then again I've had some very strange experiences with fish's performance so idk.

**Comment by faho** [comment]
@IlanCosman With 3.1.2 or master? We made `_` (the translation function) a builtin, before that it was a function that called out to the `gettext` *command*, so it would take 1.5ms. (yes, this is fundamentally silly - shelling out to something when we can literally just call the function in c++. Hence making it a builtin)

**Comment by IlanCosman** [comment]
@faho With 3.1.2. That might explain it 😄
