### ISSUE TITLE
Regression in `type` output

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#7345]
Using https://github.com/fish-shell/fish-shell/commit/533957fc2ec755bf804a3fda97d1ba7f06e7955b

---

`type -[pP]` used to return _just_ the path, i.e.

```
$ type -P cat
/bin/cat
```

However, since it became it a builtin, it now returns:

```
$ type -P cat
cat is /bin/cat
```

I was relying on the former output for one of my fish scripts, which is now broken. Do I need to update my fish script to the new format, or is this considered a regression that will be fixed?

**Comment by faho** [comment]
It's a regression.

Tho you could just use `command - s`, which is faster in released versions.
