### ISSUE TITLE
Python multiprocessing pool crash in Fish shell 

### ISSUE THREAD

**Issue by TonyWu20** [fish-shell/fish-shell#7349]
Fish shell version: 3.1.2
Terminal: Alacritty
Output of uname-a:
```
Darwin MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64
```
Output of `echo $TERM`:
```
xterm-256 color
```
Problem: When I run my python script, which includes the use of multiprocessing.pool, it will raise error:
```
+[NSApplication initialize] may have been in progress in another thread when fork() was called. We cannot safely call if or ignore if in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```
If I exit the current fish shell, execute "  sh -c 'env HOME=$(mktemp -d) fish'" and then run my script, it works without error. I then went back to my customized fish shell and tried to uninstall all my plugins and the jorgebucaran/fisher plugin manager, and stopped the [starship prompt](https://github.com/starship/starship) , but the error came again. 
Interestingly, when I run the same python script on another machine with Ubuntu 20.04 in WSL2 and the fish shell with the same configurations of plugins, fisher and starship, it just works.

**Comment by zanchey** [comment]
I discovered in another project that [multiprocessing in fork mode is not safe on macOS](https://bugs.python.org/issue33725) and you should use a different start method (such as `spawn`). That might help resolve the problem.

Trimming down your configuration is probably the place to start in getting to the bottom of this.

**Comment by TonyWu20** [comment]
> I discovered in another project that [multiprocessing in fork mode is not safe on macOS](https://bugs.python.org/issue33725) and you should use a different start method (such as `spawn`). That might help resolve the problem.
> 
> Trimming down your configuration is probably the place to start in getting to the bottom of this.
It has been working well in zsh shell before I recently take a try on fish.

**Comment by zanchey** [comment]
Sure, but there's a known landmine that you may wish to avoid.

There's quite possibly a bug in fish here! But if it works ok in a "clean" fish and not in your current fish, then the best way of working out what is going on is to comment out parts of your configuration until it works again. If you are comfortable publishing your configuration somewhere, that could be helpful too.

**Comment by TonyWu20** [comment]
**Update:** the problem has been temporarily solved by setting the environment variable **OBJC_DISABLE_INITIALIZE_FORK_SAFETY** to **YES**.
```
set --export OBJC_DISABLE_INITIALIZE_FORK_SAFETY YES
```
Because I found this variable in my previous .zshrc so I gave a try, and my python multiprocessing scripts work under the fish shell. And it also reminds me of that I had run into this problem in oh-my-zsh too. However, I still want to know **why the pure fish shell ("sh -c 'env HOME=$(mktemp -d) fish'") without customization can also get the job done.**

So here's my config.fish:
```
set --export LC_CTYPE en_US.UTF-8
set --export LC_ALL en_US.UTF-8

alias vim "/usr/local/bin/nvim"
alias ls "colorls --gs --sort-dirs"
alias lc "colorls --tree=2 -t"

set --export FZF_DEFAULT_OPTS --height 80% --reverse --border
set --export FZF_DEFAULT_COMMAND 'rg --files'
set --export LAMMPS_POTENTIALS '/usr/local/share/lammps/potentials'

fish_vi_key_bindings

###Customized alias and functions
alias vimtex 'NVIM_LISTEN_ADDRESS=/tmp/nvim vim'
alias vlc '/Applications/VLC.app/Contents/MacOS/VLC'

function brave --wraps brave --description "Open Brave Browser"
	/Applications/Brave\ Browser.app/Contents/MacOS/Brave\ Browser $argv
end
starship init fish | source
function fp
	fzf --ansi --preview-window 'right:60%' --preview 'bat --color=always --style=header,grid --line-range :300 {}'
end


function YT
	$HOME/.yabai_toggle.sh
end

function remotedesktop
	brew services stop yabai && open "$HOME/Applications/Chrome Apps.localized/Chrome Remote Desktop.app" && brew services start yabai && sleep 3 && yabai -m window --space next && yabai -m space --focus next
end
```
Here is my fishfile for fisher
```
jethrokuan/fzf
patrickf3139/fzf.fish
edc/bass
jethrokuan/z
```

**Comment by faho** [comment]
@TonyWu20 Check if the environment is the same, or if e.g. you have a different python you're calling.

Because the underlying issue seems to be a bug in macOS that causes python's "fork" multiprocessing to break sometimes, and python has routed around that by switching to a different multiprocessing mode on macOS. It's possible you're calling a python that doesn't have the workaround.

Please read [the python bug](https://bugs.python.org/issue33725) again, that would also have given you that variable.

**Comment by TonyWu20** [comment]
I just checked "which python3" after running "sh -c 'env HOME=$(mktemp -d) fish'", it points to the same python as the one I used in my own fish shell.

**Comment by faho** [comment]
Okay, then

1. You *can* disable bits of your config until you find one that changes this, but it's not really helpful - fork-mode on macOS is broken, so if it happens to work that's pure luck, and if it doesn't that's bad luck.
2. You *should* update your python and/or your code to avoid fork-mode on macOS for now, because it's broken - something like `multiprocessing.set_start_method('spawn')` if I'm reading correctly.

**Comment by faho** [comment]
Okay, closing because it's down to a macOS issue which we can't do anything about.
