### ISSUE TITLE
Tab completion problem with unzip

### ISSUE THREAD

**Issue by laughingrice** [fish-shell/fish-shell#7350]
I'm having two problems with tab completion in fish with unzip (tried both mac and ubuntu)

1) Directory name completion doesn't work if directory name starts with a ~, so ls ~/ <tab> works, unzip / <tab> works, but unzip ~/ <tab> does not)

2) how do I add an extension to the known file types? I have a file that is a zip file with a different extension (specifically for now *.makerbot) that I want to get tab completion on when doing unzip <filename>. So unzip file.zip, <tab> anywhere auto completes the file name, unzip file.makerbot, <tab> doesn't do anything

fish, version 3.1.0
Terminal is iterm2 on mac, ssh into ubuntu computer

**Comment by krobelus** [comment]
Both are fixed by 46068cd, set to be in 3.2.0. See #7040 and #7070. You can install a current version, or create `~/.config/fish/completions/unzip.fish` to fix it locally.
