### ISSUE TITLE
cycling autosuggestions?

### ISSUE THREAD

**Issue by tamis-laan** [fish-shell/fish-shell#7351]
Is it possible to cycle through autosuggestions? 

for example when I type `ls` I get autosugested `-alh | grep -i gnupg`. However I have used the `ls` command many times before so is there some shortcut to cycle through the older uses of `ls`?

**Comment by zanchey** [comment]
Pressing the <kbd>Up</kbd> key should search the history for commands beginning with `ls` - the autosuggestion picks the first one from the history.

**Comment by tamis-laan** [comment]
Yes that's what I tried before asking the question, however when I `ls ` and press up I also get suggested: 
```
yay -S mongodb-compass mongodb-tools mongodb-bin-4.0
```
To be fare 9/10 auto suggestions do start with `ls`. Any reason why this might be the case?

**Comment by faho** [comment]
>To be fare 9/10 auto suggestions do start with ls. Any reason why this might be the case?

It does an infix-search. This contains the word "tools", which includes "ls".

All as expected.

**Comment by tamis-laan** [comment]
Ah I see, whats the benefit of doing an infix search? Can I change this behavior?

**Comment by faho** [comment]
>Ah I see, whats the benefit of doing an infix search?

The benefit is that you can enter *any part* of the commandline. Did something with a directory called "tests"? Enter "tests" and search!

>Can I change this behavior?

Bind ´history-prefix-search-forward` (and backward) instead of `history-search-forward` (and backward).

**Comment by tamis-laan** [comment]
I see, thnx for the clarification!

**Comment by tamis-laan** [comment]
One more thing, when I put the following in my config.fish:

```
# User key bindings 
function fish_user_key_bindings
    # Bind key for each vim mode
    for mode in insert default visual
        # Auto suggest based on prefix 
        bind -M $mode -k up history-prefix-search-backward
        bind -M $mode -k down history-prefix-search-forward
        bind -M $mode -k ppage history-prefix-search-backward
    end
end
```
The page up key works as expected, however the up and down keys exhibit the same behavior as before i.e. executes (history-search-forward).

**Comment by faho** [comment]
Please post the output of the following:

```fish
bind -k up
```

and execute `fish_key_reader` and press the up-arrow.

**Comment by tamis-laan** [comment]
```
> bind -k up
bind --preset -k up up-or-search
bind -k up history-prefix-search-backward
> fish_key_reader 
Press a key

              hex:   1B  char: \c[  (or \e)
(  0.075 ms)  hex:   5B  char: [
(  0.089 ms)  hex:   41  char: A
bind \e\[A 'do something'
> 
```

**Comment by faho** [comment]
Ah, okay, your up-arrow isn't actually the "up" sequence (this has quite boring reasons in that terminals are weird 70s technology and we might want to enable "keypad mode", there's an issue open about that).

Bind `\e\[A` like `fish_key_reader` told you to:

    bind \e\[A history-prefix-search-backward

Same thing for down-arrow.

**Comment by tamis-laan** [comment]
Dang, terminal emulation is so wack! Thanks for the help!
