### ISSUE TITLE
^W^J no longer functions properly after quitting Vim

### ISSUE THREAD

**Issue by endersstocker** [fish-shell/fish-shell#7352]
fish, version 3.1.2-1127-gac1f63781
Darwin Kernel Version 18.7.0: Thu Jun 18 20:50:10 PDT 2020; root:xnu-4903.278.43~1/RELEASE_X86_64 x86_64
iTerm2 Build 3.3.12

I've tried fish without third-party customizations, and the behavior is the same.

## Steps to reproduce
1. Launch Vim from Fish within iTerm2
2. _Optional:_ Open a new Vim window (either **^W^N** or **^W^S**) and verify you can navigate between the windows with **^W^W**, **^W^J**, and **^W^K**
3. Quit Vim (`:q`, `:qa`, or **⇧Z⇧Z**)
4. Relaunch Vim
5. Open a new Vim window (either **^W^N** or **^W^S**) and observe that while you can navigate between the windows with **^W^W** and **^W^K**, **^W^J** no longer functions

## Notes
* Once Vim is quit, **^W^J** no longer functions in Vim for that tab
* The offending behavior does not occur in Bash
* The offending behavior does not occur in Terminal.app

**Comment by endersstocker** [comment]
Seems to be an iTerm2 issue

**Comment by faho** [comment]
Please post the output of `stty -a` before and after quitting the first vim.

**Comment by faho** [comment]
Okay, I managed to reproduce. It's enough to call vim as anything other than the first command in a session, and this is because we now turn *on* INLCR, while this requires it to be *off*.

This is a regression from #2315, so it's not in a release yet.
