### ISSUE TITLE
reader_readline only ever reads from fish's STDIN

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#7358]
Via gitter we got a question about a git commit-msg hook.

These run in an environment with a non-tty stdin, so if you want to query the user, you'd have to `read </dev/tty` explicitly. See e.g. https://stackoverflow.com/questions/3417896/how-do-i-prompt-the-user-from-within-a-commit-msg-hook.

Only that won't work in fish, because even tho `read` receives the redirected fd, it'll call `reader_readline`, and that has hard-coded `0` pretty extensively (down to input_event_queue_t::readb using `FD_SET(0, &fdset)`).

It would be great if this worked.

**Comment by mqudsi** [comment]
I've had to resort to using `/dev/tty` a lot in my fish scripts for a few other cases as well, but it's important to note that it's not just unfriendly but also unportable since I think it's a Linux-only thing.

**Comment by faho** [comment]
Sure, but:


1. This is about `read` reading interactively from *anything*, not just /dev/tty specifically
2. In this context you *need* to set the tty manually, so if you don't have /dev/tty you just need to pass it differently
