### ISSUE TITLE
fish_config only copies fish_prompt function

### ISSUE THREAD

**Issue by aeosynth** [fish-shell/fish-shell#736]
osx 10.7.5, fish HEAD

after selecting the 'Robbyrussell' prompt from the `fish_config` web interface, the shell displays errors:

```
fish: Unknown command '_git_branch_name'
/Users/james/.config/fish/functions/fish_prompt.fish (line 2): _git_branch_name
                                                               ^
in command substitution
    called on line 11 of file '/Users/james/.config/fish/functions/fish_prompt.fish',

in function 'fish_prompt',
    called on standard input,

in command substitution
    called on standard input,
```

manually copy / pasting the displayed code into `fish_prompt.fish` works fine, as does using the 'Classic + Git' prompt

**Comment by jhdxr** [comment]
8 years passed, I'm wondering if this issue get addressed? Sorin uses ` fish_right_prompt` and it seems still not working

**Comment by ridiculousfish** [comment]
This is not fixed properly; however as of b722e9ae329cf407f5a7a74d062bc1a2f677fecf none of the sample prompts define function outside of `fish_prompt`, so it's worked around. That commit will be in 3.2.

**Comment by jhdxr** [comment]
@ridiculousfish Thanks. Just curious, is there any special reason that you always prefer these workarounds rather than modifying webconfig.py?

**Comment by ridiculousfish** [comment]
No, it's just easier. Modifying webconfig.py is the right approach but would have to duplicate some work done by `funcsave`, like fetching `$__fish_config_dir` and creating the functions directory. If you or anyone has the appetite for it then we'd love to merge a PR.
