### ISSUE TITLE
fish_config not working

### ISSUE THREAD

**Issue by michaelaye** [fish-shell/fish-shell#7360]
The config screen loads in the browser but is then frozen at the `colors`, I cannot input anything or change to a different tab of the config. Interesting, clicking on a tab changes the color of the tab accordingly (deactivated tab vs activated) but doesn't switch the main display to it.

I tried both firefox and brave, same behavior.
Interesting side effect: If config is open in one browser, I close that browser, and then use the link from the console to try and open the config, it is stuck at this loading screen:

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/69774/94595756-7512cf80-0248-11eb-8fbc-60ce5a1cb7a7.png">

```bash
$ fish --version                                                                                                                                    (py37) 
fish, version 3.1.0
maye@triton|~/D/src 
$ echo $version                                                                                                                                     (py37) 
3.1.0
maye@triton|~/D/src 
```

```bash
$ uname -a                                                                                                                                          (py37) 
Linux triton 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
Let me know any other info you might need to debug this.

**Comment by faho** [comment]
This looks like #7158.

Any chance you could try current master?

The symptom you should see is that there's no more output in the console after "Hit ENTER to stop".

(also note that Ubuntu unfortunately still hasn't upgraded to 3.1.**2**, which has some important fixes - you'll want [our PPA](https://launchpad.net/~fish-shell/+archive/ubuntu/release-3))

**Comment by michaelaye** [comment]
I actually get a `$ set -L` line in the console after the browser tab has opened? And pressing Enter doesn't stop anything, I have to control-C out.

**Comment by michaelaye** [comment]
Installed 3.1.2, and retried with default Brave browser.
No change in symptoms in the browser (config is displayed but no switch of tabs possible).
Still getting a `set -L` shown in the console.

**Comment by faho** [comment]
>EDIT: Also note, I do not have FF Dev edition and the browser is running already when I launch fish_config.

Yes, but the FF Dev edition thing was *a while back* - FF Dev edition is the beta or nightly of the next firefox, so changes in it will typically be released in the normal thing.

Could you give the output of the browser console? In firefox that's ctrl+shift+k.

**Comment by michaelaye** [comment]
This is what FF says:

Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). 2 content-script.js:40:65
Some cookies are misusing the recommended “SameSite“ attribute 2
Cookie “_ga” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite analytics.min.js:4:1234
Cookie “_gat” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite

Brave wasn't that informative, just says nothing. Even unshielding the URL didn't improve things.

**Comment by faho** [comment]
>Can you be more specific about the Python version?

Well, what I'm asking is which python executes fish_config.

Because `fish_config` is a function that finds a python (via the `__fish_anypython` helper function) and calls our python script webconfig.py with it.

So `command -s (__fish_anypython)` should tell you which python it picked, and to start webconfig with a different python you'd launch it like

```fish
set -lx __fish_bin_dir $__fish_bin_dir
/path/to/python "$__fish_data_dir/tools/web_config/webconfig.py"
```

It would be great if you could try that with system python, preferably python3.

**Comment by zanchey** [comment]
Yeah, the "`py3.7`" note in your prompt is a bit suspicious.

**Comment by michaelaye** [comment]
I don't understand what is suspicious about python 3.7? Something wrong with it?

In any case, obviously, with an active conda env, the Python from there is picked up, as that's the whole point of conda:

```bash
$ command -s (__fish_anypython)                                                                                                                      (py37) 
/home/maye/miniconda3/envs/py37/bin/python3
```

I then deactivated all conda until the found Python is the system Python, but no change to the issue:

```bash
$ command -s (__fish_anypython)
/usr/bin/python3
maye@triton|~/D/src 
$ fish_config
Web config started at file:///tmp/web_config609enqq3.html
Hit ENTER to stop.
$ set -L
^C
Shutting down.
```
Screencast here: https://www.dropbox.com/s/n3fatr5ss89l43j/vokoscreen-2020-10-03_10-52-19.mkv?dl=0

**Comment by faho** [comment]
Okay, so, if this manages to print `set -L` it's at do_get_colors.

At that point, it's started the webserver (python's http.server), opened the browser, the browser has made a GET request and the webserver is answering it.

So it's hanging somewhere either in python's handling in the backend (unlikely, given it happens for multiple python versions), or the angularjs frontend.

I can only repeat my suggestion to try the current master branch given that we've had fixes in both of these things (we've updated angularjs and made the backend threaded). Other than that the only thing I can come up with is a different browser profile? It's possible you've configured both your browsers in a way that breaks this.

**Comment by krobelus** [comment]
If you start a new shell with `HOME=(mktemp -d) fish` and then run `fish_config`, it will open a fresh browser profile in that home. Does that work?

**Comment by michaelaye** [comment]
Interesting. It get's a step further, I now can switch between tabs, but the tabs are not drawn correctly:

![image](https://user-images.githubusercontent.com/69774/95820880-2a806100-0ce6-11eb-855b-a6573bd68f45.png)

and the console prints a new error and other new stuff:

```bash
maye@triton /h/maye> fish_config
Web config started at file:///tmp/web_configd7k19thm.html
Hit ENTER to stop.
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
[69271:69271:1012/235226.027479:ERROR:vaapi_wrapper.cc(546)] vaInitialize failed: unknown libva error
$ set -L
$ abbr --show
$ builtin history -z
```

**Comment by michaelaye** [comment]
ah, actually it looks like it does draw correctly, just many things are empty (hence unusual to my eyes) due to the fresh profile.
So, does that mean that some of my fish additions that i installed block stuff?
Here's a list of my fish functions, in case something is known to create problems. Half of these are from me, but don't do anything exciting:

```bash
-rw-rw-r-- 1 maye maye  650 Jun 25 16:59 bass.fish
-rw-rw-r-- 1 maye maye 3.6K Jun 25 16:59 __bass.py
-rw-r--r-- 1 maye maye  392 Dec  6  2018 configure_conda_env.fish
-rw-r--r-- 1 maye maye  133 Dec  6  2018 cp_conda_scripts.fish
-rw-r--r-- 1 maye maye  119 Dec  7  2018 create_animated_gif.fish
-rw-rw-r-- 1 maye maye  16K Jun 25 16:58 fisher.fish
-rw-r--r-- 1 maye maye 3.7K Oct 23  2018 fish_prompt.fish
-rw-r--r-- 1 maye maye 1.6K Jun 25  2019 install_jupyterlab_extensions.fish
-rw-r--r-- 1 maye maye   54 May 20  2019 pipsearch.fish
-rw-rw-r-- 1 maye maye  292 Jun 25 16:59 __ssh_agent_is_started.fish
-rw-rw-r-- 1 maye maye  158 Jun 25 16:59 __ssh_agent_start.fish
-rw-r--r-- 1 maye maye  115 Dec  7  2018 start_isis.fish
-rw-r--r-- 1 maye maye  286 Dec  6  2018 unconfigure_conda_env.fish
-rw-r--r-- 1 maye maye   79 Jan  2  2019 update_jupyterlab_extensions.fish
```

**Comment by faho** [comment]
@michaelaye 

What's mainly of interest is things that run *on startup*. That means anything in ~/.config/fish/config.fish and ~/.config/fish/conf.d, and anything called from that.

I can't really glean anything from the filenames alone, because I have little idea what those things *do*, and if they are called when fish is started by webconfig. It's possible one of these e.g. reads from the terminal, and thereby blocks what webconfig is doing.

**Comment by michaelaye** [comment]
Ok, thanks to the pointer of the startup I found the culprit!

My last line in `config.fish` is:

```
xbanish &
```

This is a tool that blanks out the mouse cursor when typing begins (https://github.com/jcs/xbanish).
Commenting out that line enables fish_config to work properly! Can you explain why that might be and suggest a better way to have this launched for every system startup? I just went with the easiest and put it in my fish as I always have a console open.
Sorry for the big noise!

**Comment by krobelus** [comment]
https://wiki.archlinux.org/index.php/Autostarting#On_Xorg_startup
