### ISSUE TITLE
fish starts and first command is very slow : sometimes fish: Locking the history file took too long (30.002 seconds)

### ISSUE THREAD

**Issue by shakenfr** [fish-shell/fish-shell#7364]
Please tell us which fish version you are using by executing the following:

  fish 3.1.0

Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:

  sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
'

Tell us how to reproduce the problem. Including an asciinema.org recording is useful for problems that involve the visual display of fish output such as its prompt.
result of fish -d 5 launch command

<5> fish: pthread 0x7f1e0acc4700 spawned
<5> fish: intern /usr/share/fish/functions/fish_title.fish
<5> fish: intern /usr/share/fish/functions/fish_title.fish
<5> fish: intern /usr/share/fish/functions/__fish_pwd.fish
default@bastion-dfc99fdf4-zqd4w /> <5> fish: pthread 0x7f1e0b4c5700 spawned
<5> fish: pthread 0x7f1e0acc4700 spawned
l<5> fish: path_get_path( 'l' )
l<5> fish: pthread 0x7f1e0b4c5700 spawned
<5> fish: pthread 0x7f1e0a4c3700 spawned
ls

**Comment by faho** [comment]
Please add more information - your os, your fish version, whether this happens without configuration, whether your $HOME is on nfs or similar.

The issue template is there for a reason.

**Comment by shakenfr** [comment]
hello,

fish version is 3.1.0
ubuntu 20.04
under openshift (kubernetes)

I fact in openshift for security reason the user of a pod is taken randomly at pod starts

ID is between 10000 and 10999, I supposed it's a problem but how to solve it

**Comment by faho** [comment]
If the UID switches randomly, then you'll also have to give it a $HOME that switches - otherwise you'll have unchangeable files lying around, so fish will rightfully complain. 

I suppose the error could be better.

**Comment by shakenfr** [comment]
yes private mode is a good workaound in my env

thanks for the help
