### ISSUE TITLE
__fish_complete_suffix doesn't handle escapes properly

### ISSUE THREAD

**Issue by jcreigh** [fish-shell/fish-shell#7366]
fish, version 3.1.2

Using `__fish_complete_suffix` in completions doesn't work when the token requires escaping, such as having a space.

https://asciinema.org/a/BDdMibEnjhSQIZocjlp2pjDOu

I believe that `__fish_complete_suffix` is using the literal token, with `\`, which breaks matching. I'll happily submit a PR which adds pipes the `commandline -ct` into `string unescape`, but I'm not sure that has any potential side effects or if there's some other reason that won't work.

**Comment by krobelus** [comment]
Thanks for reporting! I believe this was fixed by 93cb0e2abba4e5c2fa2153a18f60f5e196d5efa6.
