### ISSUE TITLE
Feature request: Auto-disable informative git prompt when slow

### ISSUE THREAD

**Issue by peey** [fish-shell/fish-shell#7367]
I'm using fish 3.1.2.

On a project with complicated git history, fish prompt takes 5-6 seconds to show. This is despite the project being on capable hardware. I debugged that the git repo is indeed the cause by following https://github.com/fish-shell/fish-shell/issues/2854 . 

I've further narrowed the slowdown to `__fish_git_prompt_show_informative_status` option. Without it, things are fine. 

My immediate question is how can I disable it globally [when my theme enables it](https://github.com/oh-my-fish/theme-cbjohnson/blob/master/fish_prompt.fish#L28)? Using `set -ge __fish_git_prompt_show_informative_status` in either command line or my config file doesn't seem to work. 

Secondly, could fish toggle this boolean automatically after doing some performance profiling on the first `fish_git_prompt` for a repository?

**Comment by faho** [comment]
> My immediate question is how can I disable it globally when my theme enables it?

Disable it in the git config for the repository :

     git config --local bash.showInformativeStatus false

as is mentioned in the docs at http://fishshell.com/docs/current/cmds/fish_git_prompt.html. (yes, that's a "bash", we share these values with the bash prompt) 

> Secondly, could fish toggle this boolean automatically

Basically not, because we have no good way to figure out if it's actually too big or your system just had a hiccup. So we don't want to remember all git repositories and we also don't want to set your git config, so it doesn't seem doable.

Tbh you probably don't want the informative prompt, it's just that many people enable it because it also changes the chars to nicer ones. We now have a separate option to use those, you most likely want that instead - `__fish_git_prompt_use_informative_chars`.

**Comment by mqudsi** [comment]
The precondition for the vcs informative prompt being enabled by default was that there were no circumstances under which the subset of git operations it performs would include any operations that would result in a noticeable slowdown of the prompt on modest hardware. @faho, @krobelus, and I tested it on a number of huge repos (and I was particularly motivated to find pathological changes) but didn't come across any at the time. @peey, could you share more info about what makes this a complex git repo?

With regards to disabling automatically, 

> We also don't want to remember all git repositories and we don't want to set your git config

If this is done per repo with a history of just one, it would sidestep that issue. i.e. if $PWD is a child of $PWD when the informative prompt was found to be slow, skip the vcs integration. If $PWD is not a child of the previously recorded $PWD, time the operation and set the flag accordingly. 

> we have no good way to figure out if it's actually too big or your system just had a hiccup.

This would be a non-issue if the determination is made according to the heuristic described above. Additionally and IMHO, it shouldn't matter either way if it's non-persistent (i.e. disabled until the end of the session).

**Comment by faho** [comment]
>The precondition for the vcs informative prompt being enabled by default 

To be clear: The *informative* prompt, the one that counts all that stuff, is _not_ enabled by default!

That's set by the user or a theme or similar, by setting `$__fish_git_prompt_show_informative_status`.

> if $PWD is a child of $PWD when the informative prompt was found to be slow,

NOOOOOOO!

1. It would have to be "if the git root has been found to be slow" - you can nest git repositories, the inner one can be slow or fast
2. If it is "determined" is *awfully complicated*. If you measure just once, it might be your computer just having a hiccup or being busy with something, and then we save that and disable the thing and it would actually have been fine. If you measure more often, you take more time. Then we would not want to save this persistently (or false-negatives become even worse), so it's mutliple times *per shell*, so it'll barely save any time on average. Any solution here is bound to be wrong quite often and take a lot of time quite often, so I don't think it's worth even bothering with.

What we should do is to discourage the informative prompt (the default non-informative version is *much* faster and has most of the usable information - it just doesn't *count* things), e.g. via switching the default characters to the much nicer informative ones so people aren't tempted to pick them. I asked about this a while back, but apparently we really really wanted to stay pixel-for-pixel identical to the bash git prompt by default for some reason.

**Comment by IlanCosman** [comment]
Personally, coming from zsh with powerlevel10k, I really like the full informative prompt with file counts. I don't have to run `git status`, it's just there already. The only reason for disliking it imo is how slow it is, which is due to fish not supporting async well.

**Comment by krobelus** [comment]
If the user (or theme) enables `__fish_git_prompt_show_informative_status` there's not much we can do without trying to be too smart.
If your theme wants to support large repositories, they should not enable `__fish_git_prompt_show_informative_status` unconditionally, but at least allow the user to override it. Or just use `__fish_git_prompt_use_informative_chars`.

There are some good points in this thread on the difficulties of detecting a slow prompt but let's track that in #6764.

BTW: https://github.com/mattgreen/lucid.fish seems like a sensible implementation of an async prompt.

**Comment by mqudsi** [comment]
Sorry, I confused the regular vcs integration with the informative.

**Comment by peey** [comment]
I found myself coming back to this issue, turns out that using

```
 git config --local bash.showDirtyState false
```

is sufficent for speedup while still displaying some information. 

note that if you have `bash.showInformativeStatus` set then it'll dominate `bash.showDirtyState`, so it wouldn't matter what `bash.showDirtyState` is set to. The way to get rid of this is to use 

```
 git config --local --unset bash.showInformativeStatus
```

**Comment by faho** [comment]
Yes, that is intentional. The informative prompt computes status separately, and the way it works not *counting* dirty state makes no sense. So we could *hide* it, but that wouldn't solve the problem.

And if the repo explicitly tells us to use informative state, we do that.
