### ISSUE TITLE
unbinding ctrl-d in config.fish doesn't work

### ISSUE THREAD

**Issue by bram2000** [fish-shell/fish-shell#7368]
fish, version 3.1.2

Darwin iMac.lan 18.7.0 Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64 x86_64

xterm-256color

I want to disable the Ctrl-D behaviour as i keep accidentally closing my terminal when trying to exit a pdb session. I have read the comments in https://github.com/fish-shell/fish-shell/issues/5593 and if i run `bind --erase --preset \cd` in  a session it does what i want and disables the behaviour. However, i've put the command at the end my `.config/fish/config.fish` file, and it doesn't seem to work.

How can i make the unbind of ctrl-d persist?

**Comment by faho** [comment]
Well, yeah, unbinding won't work because the bindings are only loaded *after* config.fish (because you could change them there).

Bind it to a noop:

```fish
bind \cd true
```

**Comment by bram2000** [comment]
Works perfectly. Thank you!
