### ISSUE TITLE
Completions for ulimit and umask

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#737]
`umask` and `ulimit` both need completions written at some point.

**Comment by krader1961** [comment]
It's been four years and no one has been motivated to write these completions. Also, `ulimit` has had a custom completion since 2007-01-16 with commit 34e27ff4c. Someone who cares simply needs to write one for umask.

**Comment by xordspar0** [comment]
It looks like #5386 finished this. It should be closed.

**Comment by zanchey** [comment]
It certainly got things started.
