### ISSUE TITLE
Some themes are not applied and give hostanme command not found

### ISSUE THREAD

**Issue by jwtiyar** [fish-shell/fish-shell#7370]
Fish 3.1.2
  
Hey, I have problen with installing some of the themes which have:
`hostname| cut -d . -f 1`

when i install theme i get this error when starting new command or opening terminal:
```
fish: Unknown command: hostname
~/.config/fish/functions/fish_prompt.fish (line 1): 
hostname| cut -d . -f 1
^
in command substitution
	called on line 4 of file ~/.config/fish/functions/fish_prompt.fish
in function 'fish_prompt'
in command substitution
jwtiyar@:~
$  
```

**Comment by faho** [comment]
It appears you don't have a hostname command. 

Fish used to call that to get the hostname, but since version 3.0 it instead just sets the $hostname variable.

You have an old prompt, so you need to update it - just replace that line with `echo $hostname`.

**Comment by jwtiyar** [comment]
> echo $hostname

Thank you :+1:

**Comment by faho** [comment]
That file it talks about? `~/.config/fish/functions/fish_prompt.fish`? That includes your prompt.

You want to fix that file, by replacing the `hostname | cut` line with `echo $hostname`.

**Comment by jwtiyar** [comment]
> That file it talks about? `~/.config/fish/functions/fish_prompt.fish`? That includes your prompt.
> 
> You want to fix that file, by replacing the `hostname | cut` line with `echo $hostname`.

Thank you. fixed
