### ISSUE TITLE
Is there a way to disable autofill for certain directories and to not store any history with certain directories?

### ISSUE THREAD

**Issue by Joe23232** [fish-shell/fish-shell#7373]
With `fish` is there some config text I can add to its config files so that I can disable autofill when it comes to certain directories?

For example lets just say I mounted a USB drive in the directory `/mnt/usb`. If I am in `~/Desktop` and I wanted to copy a file over to `/mnt/usb` then a lot of times `fish` will autofill certain directories, especially if I have accessed `/mnt/usb`. Is it possible for me to get `fish` to not autofill nor store any history in regards to `/mnt/usb`?

**Comment by faho** [comment]
No, and I don't think we want to add it.

**Comment by zanchey** [comment]
One workaround is to erase those lines from history so that they'll never be suggested, but that has the issue that they're not in your history any more.

**Comment by Joe23232** [comment]
> One workaround is to erase those lines from history so that they'll never be suggested, but that has the issue that they're not in your history any more.

Can I set it up in such a way where if I am in a certain directory, I won't get those suggestions but in other directories I will get suggestions?

**Comment by faho** [comment]
There are no configuration options for suggestions, no.

**Comment by Joe23232** [comment]
Oh ok thanks.
