### ISSUE TITLE
Allow erasing multiple variables, abbrs, etc.

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7377]
The `functions --erase` command accepts multiple arguments, erasing all of them. `set` and `abbr` should do the same. I've not infrequently found myself using the

```fish
for var in $list_of_vars
    set -e $var
end
```

idiom. `set -e $list_of_vars` would be much more convenient. Similarly with `abbr`, though in truth I've never needed to erase multiple abbrs at once.

Either the `functions --erase` command should _not_ accept multiple arguments, or `set --erase` and `abbr --erase` should (obviously I believe the latter).

**Comment by ridiculousfish** [comment]
Seems reasonable!
