### ISSUE TITLE
fish: Unknown command: code

### ISSUE THREAD

**Issue by taylorhahn27** [fish-shell/fish-shell#7380]
fish, version 3.1.2

Darwin Taylors-1.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64 x86_64

xterm-256color

I tried to add vscode to my $PATH so I am able to use "code ." to open a directory directly from my terminal. 

I now receive this error in return: "fish: Unknown command: code"

**Comment by faho** [comment]
Well, you haven't set $PATH correctly.

It would really help to know what you actually did.

**Comment by taylorhahn27** [comment]
Woops apologies for the lack of detail. I set the ‘Shell Command: Install 'code' command in PATH’ within VS Code. Was struggling adding it to my path manually via the terminal

**Comment by faho** [comment]
So you did that in VS Code and it still doesn't work?

Unfortunately I have no idea what that does - it might be writing into ~/.bashrc, which obviously won't work in fish. I'd check if that file contains anything.
Also how did you try to set $PATH manually? What commands did you try?

**Comment by zanchey** [comment]
https://github.com/Microsoft/vscode/issues/7426#issuecomment-277737150 may be relevant

**Comment by zanchey** [comment]
That function just installs a symlink:

```
> ls -l (command -s code)
lrwxr-xr-x 68 david  6 Oct 21:19 /usr/local/bin/code -> /Applications/Visual Studio Code.app/Contents/Resources/app/bin/code
```

so it would be interesting to know if `/usr/local/bin` is in `$PATH`.

**Comment by faho** [comment]
Okay, so you need to make sure /usr/local/bin is in $PATH.

There's not been any activity on this in a while, so I'm closing.

**Comment by DataEnggNerd** [comment]
In case anyone is still looking for answer here,
```shell
$ fish_add_path /opt/homebrew/bin/
$ source ~/.config/fish/config.fish
```
In short, after adding all the paths from `/opt/homebrew/bin/` to fish, restart fish shell. 
Worked for me in 
```
OS: macOS 15.0
fish, version 3.7.1
```
