### ISSUE TITLE
fish_cancel event is broken

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#7384]
This is a regression from eb35975c0fdd7420608aa743882c0fc96f3bf585.

The `__fish_cancel_commandline` function fires an event called `fish_cancel` to let the terminal know that we're cancelling the commandline. This is used by https://github.com/PerBothner/DomTerm to remove all but the last right prompt.

The C++ version `cancel-commandline` doesn't currently fire an event.

Only I tried adding it by adding

```c++
                event_fire_generic(parser(), L"fish_cancel");
```

to https://github.com/fish-shell/fish-shell/blob/48e274591a8945d91bb69c51791640cd4dc1ca0b/src/reader.cpp#L2775-L2776

only that doesn't appear to fire? I added flog messages to event.cpp to confirm, and I can't see it happening.

I'm probably just misunderstanding something about the parser here.

**Comment by ridiculousfish** [comment]
The issue with sending the event is that the cancellation from the SIGINT still lingers - maybe this is too tricky and should be reworked.

Anyways fixed as e9902159c2efd052db7bd6e282690bc5d7a2a494, glad you caught this
