### ISSUE TITLE
catting exec <SHELL> through to source exits shell

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7385]
I have a file `blah.fish` that contains one line:

```fish
exec fish
```

When I run `source blah.fish`, the shell restarts as expected and I get a new greeting etc. However when I run `cat blah.fish | source`, the shell simply exits, closing my terminal. This is the same with `bash` and `zsh`.

<div align="center">
<sub>

fish, version 3.1.2

Linux archlabs 5.8.13-arch1-1 #1 SMP PREEMPT Thu, 01 Oct 2020 20:40:35 +0000 x86_64 GNU/Linux

xterm-256color

Clean fish

</sub>
</div>

**Comment by faho** [comment]
When you run `source blah.fish`, that runs `exec fish` with stdin connected to the terminal, so it assumes it's interactive.

When you run `cat blah.fish | source`, that's not the case, so it just exits because it has no commands and no stdin.

I don't see this working any other way.

**Comment by IlanCosman** [comment]
I see, that makes sense. My use case is an install script that ends with restarting the shell using `exec fish`. I guess I'll have to make it a function instead of a script and then use `curl install.fish | source && install_function`. which should solve the issue. Thanks @faho 😄
