### ISSUE TITLE
Fish environment variable ignored by programs

### ISSUE THREAD

**Issue by MichaelC2-718** [fish-shell/fish-shell#7395]
Fish version: 3.1.0
Kernel version: 5.4.0-48-generic
Arch: x86_64
OS: Linux Mint 20

I don't have root access, so I have to build some stuff (nothing fish related) from source. I had some binaries to execute, and I couldn't put them in `/usr`, because no root. Fortunately, Lua and Java (the programs with problems), support adding paths using environment variables. Specifically, I set `LUA_PATH`, `LUA_CPATH`, and `JAVA_HOME`. None of these made a difference when I set them interactively or when I put them in `config.fish`. However, when I used `LUA_PATH=... LUA_CPATH=... lua` and `JAVA_HOME=... ant` I saw what I expected.

Why are these programs not recognizing environment variables unless I specify them in the command?

I tried without third party extensions, and I saw the same behaviour.

**Comment by zanchey** [comment]
Probably you need to add `--export`/`-x` to your `set` command.

Showing how you have set the variables would be helpful.

**Comment by faho** [comment]
@MichaelC2-718 The FAQ explicitly says `set -x variable value`. That's the fish way of spelling it.
See http://fishshell.com/docs/current/faq.html#how-do-i-set-or-clear-an-environment-variable
