### ISSUE TITLE
Add command to initialize fish again

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7396]
There are times, most usually in an install or uninstall script, one wishes to restart the shell. That is, for fish to do it's initialization processes over again. `exec fish` most nearly does this, but as it starts a new shell it is necessarily always the last thing to happen. A convoluted for loop sourcing initialization files and directories can form a poor approximation, but this method greedily loads everything and must be made to exactly follow fish's [initialization steps](https://fishshell.com/docs/current/index.html#initialization-files). 

I propose a new command that tells fish to do it's initialization processes over again, scanning the directories for autoloading, running things in conf.d and config.fish etc.

**Comment by faho** [comment]
This is quite literally impossible.

We *can't* figure out what config.fish does and redo it, it is an actual entire program.

Anything we would add here would be a half-solution.

Just start a new shell when you want a new shell.

Sorry!

**Comment by IlanCosman** [comment]
Thanks for the response fabian. I don't quite understand what you mean by "config.fish is an actual entire program". I can run some stuff in my script, source config.fish, and then continue with the script. I'd essentially like a baked in version of that, except for all of the fish initialization. Sorry if this is a pointless line of questioning, I'd just like to get a better understanding of what's going on.

**Comment by IlanCosman** [comment]
I believe you may have misinterpreted me, please correct me if I'm wrong. You thought I was suggesting that there be a command to "do literally the exact same thing as when we first started fish" which is impossible. I am suggesting that there be a command to "run the initialization steps again, with the most modern state", just like sourcing the initialization files. That is scan the config directories for the filenames so that we can autoload, source the config.fish etc. <-- I want to do those steps again.

"do it's initialization processes over again" was a very unclear way for me to have phrased it.

**Comment by faho** [comment]
We couldn't guarantee that that would have any sensible effect, is the problem.

E. g. ever seen how much of a problem it is for people to append to $fish_user_paths in config.fish? Imagine that, but for all variables you apoend to.

Configuration is, in general, not written to be idempotent, so running it twice will change things (because that's the definition of idempotent). Adding a thing to do that automatically doesn't seem like a good idea.

**Comment by zanchey** [comment]
You can run `share/config.fish` to re-run all those files, but (for example) `__fish_config_interactive` won't run twice, and there's no guarantee that you won't end up with strange issues.

**Comment by IlanCosman** [comment]
That's a solid point, I concede the argument 😂. Perhaps a command to look at the directories again for autoloading? This is pretty weird:

```fish
> curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
> fisher # works!
```

```fish
> fisher # obviously doesn't work
> curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish
> fisher # doesn't work, like fish has given up on finding it

**Comment by faho** [comment]
@IlanCosman That's #5176. The issue there is that fish's autoloading takes a while to retry loading a function, because not doing so would slow down any builtin call (because you could have added a wrapper in the meantime).

**Comment by IlanCosman** [comment]
That's an interesting point. It seems to me that a command to retry autoloading would solve that problem then, since fish wouldn't be doing it automatically.

**Comment by faho** [comment]
Read the linked issue. Our current thinking is to not cache misses for commands that are total misses - not a function, command or builtin. So this would be reduced to new wrapper functions of the same name.

**Comment by IlanCosman** [comment]
My apologies, I read the issue but it clearly didn't sink in well enough 😂 That seems like a much more elegant solution.
