### ISSUE TITLE
SIGIO notifier broken on FreeBSD

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#7400]
With 06bd1e934, the tests report, on a freshly opened FreeBSD 12.3 VM:

```
Error: Universal variable notifier (10) 0x800d3e2a0 polled failed to notice changes, with strategy 2
```

I'm going to #ifdef this out right now and leave this issue open for the time being.

I'm not entirely sure if the SIGIO notifier works as the replacement for the named pipe notifier that it was originally envisioned to be. Is it worth it, given that we apparently need to keep the named pipe strategy around anyway?

**Comment by mqudsi** [comment]
@ridiculousfish fixed this in e669c41d1b289f3ad4618ecc588456d1eb9eeed2 and a34b9036baa551fc4696bd5c326df277561b1655
