### ISSUE TITLE
Create (empty) configuration directories and files on first run

### ISSUE THREAD

**Issue by Tadaboody** [fish-shell/fish-shell#7402]
fish, version 3.1.0 (running OS X, tested on a ubuntu container to see the setup behaviour)

Completion scripts should go in `~/.config/fish/completions` but that dir does not exist when starting to use fish, I think the process could be streamlined if it was created at setup (like `.config/fish/` already is)

**Comment by IlanCosman** [comment]
Neither are the `conf.d` directory, or the `functions` directory, or the `config.fish` file. It might help new users if those were all created, blank of course.

**Comment by zanchey** [comment]
This can't be done on install but rather on first run, but I think it's a reasonable idea - the base directories already get created anyway. Probably this could be done in `__fish_config_interactive`?

**Comment by krobelus** [comment]
Yeah it seems fine. Many people might never use those directories but they don't hurt.

Compare to `git init` which creates plenty of example hooks in `.git/hooks/`.
