### ISSUE TITLE
completions/git: Handle "1 .A" files

### ISSUE THREAD

**Issue by z3ntu** [fish-shell/fish-shell#7403]
fish 3.1.2 (also tried completions from git master)

To reproduce:
```
mkdir /tmp/test
cd /tmp/test
git init
touch test
git add --intent-to-add test
git add <TAB> *NO COMPLETION*
```
```
$ git -c status.relativePaths -c core.quotePath= status --porcelain=2 -uno
1 .A N... 000000 000000 100644 0000000000000000000000000000000000000000 0000000000000000000000000000000000000000 test
```

**Comment by z3ntu** [comment]
@krobelus Thanks for the fix but I don't think it actually works yet. 

This returns the file now:
```
$ source /usr/share/fish/completions/git.fish
$ __fish_git_files added
test    Added file
```

But the `git add <TAB>` still results in no match, I'm guessing because this is used:
```
complete -f -c git -n '__fish_git_using_command add' -a '(__fish_git_files modified untracked deleted unmerged)'
```
(line 971) where `added` isn't used but just modified untracked etc. I'm not too familiar with the completions though so I might as well be wrong.

**Comment by krobelus** [comment]
You're right, it should be `untracked` and not `added`. Fixed, thanks!

**Comment by z3ntu** [comment]
Great, thanks a lot!
