### ISSUE TITLE
fish cannot handle CJK input

### ISSUE THREAD

**Issue by rty813** [fish-shell/fish-shell#7409]
### fish --version
`fish, version 2.2.0`
### uname -a
`Linux orca 4.1.15 #4 SMP PREEMPT Wed Nov 6 16:01:51 CST 2019 armv7l armv7l armv7l GNU/Linux`
### echo $TERM
`xterm-256color`

---
When I copy a text contains CJK characters and paste it in fish, fish only shows the ascii characters. 
For example, I copy "前123" and paste in fish, fish only shows "123".
![Snipaste_2020-10-21_09-43-35](https://user-images.githubusercontent.com/22488813/96662840-e9411e80-1381-11eb-8906-840eea08b6c0.png)

I tried bash and it also shows "123". Then I edit `/etc/inputrc` and add followed lines:
```
set input-meta on
set output-meta on
set meta-flag on
set convert-meta off
```
I exit and reopen bash, then bash can display CJK characters.

**Comment by mqudsi** [comment]
So this'll depend on your terminal emulator and your desktop environment (Xorg vs Wayland), which influences the paste mechanism. Plus, you're on a really old version of fish.

**Comment by rty813** [comment]
Not only paste, but also type CJK characters  can cause this error. 
I cannot type CJK characters in fish, but I can type CJK characters in bash after I config `/etc/inputrc`.
My terminal emulator is putty.

**Comment by rty813** [comment]
OH! after I upgrade fish to v3.1.2, it's fixed. Thanks
