### ISSUE TITLE
fish_config doesn't change anything

### ISSUE THREAD

**Issue by Minashraf** [fish-shell/fish-shell#7412]
Hello,
 I am using fish on my ArchLinux and when I write fish_config it opens the config webpage I change for example the background click 'Set Theme' and it says 'Theme Set!' if I go to another tab say the prompt one and go back to the theme one I find the old one 

fish, version 3.1.2
Linux ArchLinux 5.4.70-1-lts #1 SMP Wed, 07 Oct 2020 23:54:51 +0000 x86_64 GNU/Linux
xterm-256color

**Comment by faho** [comment]
Like it says, the background is just for demo purposes, we have no way of setting the terminal background.
