### ISSUE TITLE
It would be nice if $fish_pid and $last_pid get documented

### ISSUE THREAD

**Issue by klesh** [fish-shell/fish-shell#7413]
Hi, All

I was converting my bash script into fish and found that %last expansion was removed, so I went through __Introduction__ again and found no luck, then I went for google and got [this answer](https://stackoverflow.com/questions/30379934/fish-shell-how-to-get-the-pid-of-the-process-started-in-the-background),which I didn't believe it is the best solution.

Finally, I went through the release notes and found out [this issue](https://github.com/fish-shell/fish-shell/issues/1202), and I love these variables, they make much more sense than `%` expansion. 

The problem is, when I tried to search these variables on documentation, I got no formal introduction. Since they are so frequently used on job controlling, I think they should be documented, maybe in __Introduction__?

Thanks

**Comment by krobelus** [comment]
Should already be fixed on master by e03c375ee35c57e7b5c66f44ea110e8e9e31067e which adds them to the "special variables" section" of the introduction, thanks for reporting nevertheless!
