### ISSUE TITLE
Completions for ldapsearch

### ISSUE THREAD

**Issue by thernstig** [fish-shell/fish-shell#7416]
Is there any chance that ldapsearch completions could be added?

See https://linux.die.net/man/1/ldapsearch

**Comment by faho** [comment]
If someone writes them, sure.

This seems simple enough, so just take the generated completions (~/.local/share/fish/generated_completions/ldapsearch.fish), clean up the descriptions, add the arguments (like `-s {base|one|sub|children} `) and make a PR.
