### ISSUE TITLE
How to tell which function is bound to a key binding?

### ISSUE THREAD

**Issue by robenkleene** [fish-shell/fish-shell#7417]
Title is self-explanatory, e.g., see `describe-key` in Emacs, or `bindkey -M` in Zsh.

Fish version 3.1.2.

`man bind` and `man fish_key_reader` don't seem to provide this functionality.

The use case is that a common starting point for customizing software is to explore how things currently work. This isn't practical for key bindings without a way to see which functions are currently bound to which keys.

**Comment by faho** [comment]
`bind KEYSEQUENCE`, for example

```fish
bind \cr
```

to see what is bound to ctrl-r in "default" mode.If you use vi-mode, add e.g.`-M insert` to see what it is bound to in insert-mode.

**Comment by robenkleene** [comment]
@faho Works perfectly, thanks! (Wish I'd thought to try that.)
