### ISSUE TITLE
Completion fails if path to command wrapped in quotes

### ISSUE THREAD

**Issue by charleskorn** [fish-shell/fish-shell#7424]
# Issue description

Completions aren't generated if the path to the executable is wrapped in quotes.

# Steps to reproduce

(Assuming `git` is at `/usr/local/bin/git`)

1. `cd /usr/local`
2. `complete -C"git -"` ✅ produces completions
3. `complete -C"./bin/git -"` ✅ produces completions
4. `complete -C"'./bin/git' -"` :x: produces no completions
5. `complete -C'"./bin/git" -'` :x: produces no completions
6. `git -<tab>` ✅ produces completions
7. `"/usr/local/bin/git" -<tab>` :x: produces no completions
8. `"./bin/git" -<tab>` :x: produces no completions

# Environment details

* Fish version: `fish, version 3.1.2`
* Operating system: `Darwin <redacted> 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64`
* Terminal: `xterm-256color`

**Comment by krobelus** [comment]
Thanks for the report! This appears to be fixed on current master. I'm not sure which commit fixed it.
