### ISSUE TITLE
Can't get custom keybind to work in fish (User problem)

### ISSUE THREAD

**Issue by Hydranet** [fish-shell/fish-shell#7425]
I think this is a user problem since I am new to the fish shell. I'm trying to set a custom
key-bind for forward-word, I found out that I have to use fish_key_reader to find they key 
combinations to use for my bind configuration. However I can't get it to work even when 
using the example from the  [documentation](https://fishshell.com/docs/current/cmds/bind.html#examples) I'm trying to configure ctrl+w for this. This is 
what I have in my configuration:  **bind \cW 'forward-word'**  
What am I missing here?

**Comment by Hydranet** [comment]
I just figured out that cW is already in use by one of the default keybindings. So that must be the problem, I will just have to find a key combination that isn't used.

**Comment by faho** [comment]
> I just figured out that cW is already in use by one of the default keybindings. So that must be the problem,

It is not. Rebinding keys is of course possible. What does `bind \cW` say and did fish_key_reader tell you to use \cW?

**Comment by Hydranet** [comment]
Yes you are right about it not being the problem, I got it working now. The problem I think was that I have vi mode enable. So then when I did it like this it worked
`bind -M insert \cW 'forward-word'`

**Comment by faho** [comment]
Ah, okay. When you `bind` without giving a mode it binds in "default" mode. In vi-speak that's "normal" mode, so of course it won't work in insert mode.

**Comment by Hydranet** [comment]
> Ah, okay. When you `bind` without giving a mode it binds in "default" mode. In vi-speak that's "normal" mode, so of course it won't work in insert mode.
Thanks for explaining. I just started playing with around and configuring fish shell for the first time today, so I am still learning as I go. It's got a lot of nice features which makes it a good alternative for bash as an interactive shell. A many thanks to all the fish shell devs!!!
