### ISSUE TITLE
fishd should report when autoloading functions change

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#743]
When you change your prompt via fish_config, existing fish sessions don't notice until five seconds later. What we could do is support a function barrier in fishd, which causes autoloading functions to re-load.

**Comment by faho** [comment]
fishd is dead now. Any other way to add this? One of those file change notification APIs? Linux has about fifty of them.

**Comment by ridiculousfish** [comment]
We can probably leverage the universal variable notifier for this case.

**Comment by pickfire** [comment]
Does this relate to this case:

1. I had change a universal environment.
2. The environment variable is **different** on others `fish` instances.
3. I need to restart `fish` to make changes to the variable.

**Comment by ridiculousfish** [comment]
Universal variables should be the same across all instances of fish. Do you have steps to reproduce?

**Comment by pickfire** [comment]
I showed that. https://github.com/fish-shell/fish-shell/issues/743#issuecomment-150253440

**Comment by pickfire** [comment]
I guess I wasn't clear enough. Steps to reproduce:
```fish
set -e http_proxy
set -Ux http_proxy 'http://localhost:8123'
```
In another terminal:
```
echo $http_proxy
```
It will still be the old variable.

**Comment by ridiculousfish** [comment]
What is the old variable? How was the old variable set?

**Comment by pickfire** [comment]
The old variable is set with:
```fish
set -Ux http_proxy 'http://localhost:9050'
```
That is not exactly what it is, it is just similar to it.

**Comment by krader1961** [comment]
Using the uvar notification mechanism is clever but only partially solves the problem. Notably it only solves it if the prompt is changed via `fish_config`. It doesn't solve the case where the `fish_prompt.fish` file is changed via some other mechanism. For that we need to use inotify (Linux), FSevents (macOS), or a similar mechanism. Alternatively, a background thread that stats each autoloaded file at a high frequency (e.g., every 0.5 seconds) which isn't worth the cost relative to the benefit.
