### ISSUE TITLE
Prefer user-defined functions to vendor-defined functions

### ISSUE THREAD

**Issue by dmoerner** [fish-shell/fish-shell#7434]
fish, version 3.1.2. Tested on Fedora 32 and Fedora 33. 

I tried to search for duplicate bug reports because I expected people might have raised this issue before, but I didn't see any.

Fish searches $fish_function_path for functions to load. Here's the output on a Fedora 32 machine:

```
user@work ~ (master)> echo $fish_function_path
/home/user/.config/fish/functions /etc/fish/functions /usr/share/fish/vendor_functions.d /usr/share/fish/functions
```

Some vendors ship functions in /usr/share/fish/vendor_functions.d; e.g., Fedora now ships a function to alias vim to vi if you have only the vim-minimal package installed. But users may also want to define their own functions with the same name, e.g., an alias of vim to nvim. As a user, I expect that my functions defined in ~/.config/fish/functions will have precedence over vendor functions, partly because they are first in the $fish_function_path list. But that doesn't seem to be what happens. My user functions keep getting overridden by the vendor-set functions. I didn't take a look at the source code but it may be that the last entry for a function found in $fish_function_path is the one that is used. If that's the case, maybe the order of $fish_function_path could just be switched?

**Comment by faho** [comment]
> As a user, I expect that my functions defined in ~/.config/fish/functions will have precedence over vendor functions

They do.

>  it may be that the last entry for a function found in $fish_function_path is the one that is used

It isn't.

------

Please check your system, there is something else going on.

In particular the file does have to have the correct name. If the function is called "vi", then the file needs to be called "vi.fish".

Also this only works if Fedora uses autoloading for this, if they eagerly add a function called "vi" in e.g. /usr/share/fish/vendor_conf.d that would turn off autoloading (because the function already exists), and I would expect a quick bug report to get them to stop that.

**Comment by faho** [comment]
Additionally the output of `type -a vi vim` would be nice

**Comment by dmoerner** [comment]
> Also this only works if Fedora uses autoloading for this, if they eagerly add a function called "vi" in e.g. /usr/share/fish/vendor_conf.d that would turn off autoloading (because the function already exists), and I would expect a quick bug report to get them to stop that.

Thank you for the quick response. This is the problem. I'll file a bug report with Fedora.
