### ISSUE TITLE
[Question] Submitting completions to fish-shell repo or upstream projects

### ISSUE THREAD

**Issue by erazemk** [fish-shell/fish-shell#7436]
I've read a few discussions regarding completions and have searched the issues a bit, but haven't found a definitive answer.
Is it preferable to add completions to the fish-shell repository or submit them directly to upstream projects?

**Comment by faho** [comment]
If the upstream wants to take and maintain them that's typically ideal, because they know more about how their thing works and can adjust the completions to work with new versions of their tool.

However, we'll also take basically anything, and we don't require that you ask upstream first.

**Comment by erazemk** [comment]
Thanks, I'll try upstream-first then.
