### ISSUE TITLE
Pressing Alt-Enter sends command instead of producing new line

### ISSUE THREAD

**Issue by joallard** [fish-shell/fish-shell#7440]
I was playing around with Vi mode and multi-line editing. I often feel, when doing multi-line, that I'm a bit "stuck" in the command.

I was going to poke around whether `o` (open) could be added to vi-mode, but this seems like an even more mainstream case.

Documentation states:

> The fish commandline editor can be used to work on commands that are several lines long. There are three ways to make a command span more than a single line:
> 
> -   Pressing the Enter key while a block of commands is unclosed, such as when one or more block commands such as for, begin or if do not have a corresponding end command.
> -   Pressing Alt+Enter instead of pressing the Enter key.
> -   By inserting a backslash (\) character before pressing the Enter key, escaping the newline.

It seems a bit strange to find this bug, hopefully I'm not missing something obvious.

## Case 1: At end of command
1. Input `echo "hello friends"`
2. Press Alt-Enter

=> Command is executed
(Expected new line)

## Case 2: Between words
1. Input `echo "hello friends"`
2. Press Alt-Left (or navigate cursor to before letter 'f')
3. Press Alt-Enter

=> Command is executed

## Versions
* fish, version 3.1.2
* Darwin Kernel Version 18.7.0 (macOS)
* iTerm 2 (+reproduced on Terminal)

For those wondering if my Alt key is weird, I've got Alt+H and Alt+E working just fine!

**Comment by faho** [comment]
This depends on two things:

1. What does your terminal send when you press alt+enter?

2. What have you bound to that?

From your text, it's unclear whether you are using vi-mode or emacs-mode, so I will assume it's emacs-mode.

If so, please run `fish_key_reader`, press alt+enter. That will print something like

```output
Press a key:
              hex:   1B  char: \c[  (or \e)
(  0.058 ms)  hex:    D  char: \cM  (or \r)
bind \e\r 'do something'
```

So alt+enter sends `\e\r`, so we can figure out what that's bounnd to via `bind \e\r`. In my case that says:

```fish
bind --preset \e\r commandline\ -f\ expand-abbr\;\ commandline\ -i\ \\n
```

which will indeed add a newline and *not* execute anything (there's no `commandline -f execute` there anywhere).

Either your terminal sends something else, or you have rebound that combination.

**Comment by joallard** [comment]
Ah, yes, I thought to try that out but forgot along the way. 

Here's the output:
```
              hex:    D  char: \cM  (or \r)
bind \r 'do something'
```

There is no difference between my Alt+Enter and a regular Enter.

That is my mistake because when first installing Fish, I had fiddled with making the Alt key work. 

See also: 
* https://github.com/fish-shell/fish-shell/issues/3056#issuecomment-221045473
* [iTerm FAQ](https://www.iterm2.com/faq.html), search for "escape"

### Fix for iTerm
1. Open iTerm Preferences 
1. In tab *Profiles*, select the one that you use
1. Open tab *Keys*
1. At "Left Option Key" and "Right Option Key", select **Esc+** for Fish to receive the escape sequence.
1. There is no save button, you may close the window.

The default seems to be "Normal", and I had only one of two remapped. (I had only left Alt enabled, which is why I trained doing LeftAlt+H, LeftAlt+W, so on, then forgot – I forget what feature I wanted to retain. We'll see.)

Et voilà. All cases work in Emacs mode, and even in Vi mode for free. Happy times!

Hopefully this helps anyone running into the same issue. Thanks @faho for your very thorough help.
