### ISSUE TITLE
Add option to list kill ring entries

### ISSUE THREAD

**Issue by mamiu** [fish-shell/fish-shell#7445]
I couldn't find any command to obtain (or variable that holds) the entries of the [killring](https://fishshell.com/docs/current/#killring) feature (except the two bind input functions `yank` and `yank-pop` which don't list all entries).

Or is there another option to get all entries from the kill ring?

**Comment by faho** [comment]
There currently is not.

See also #4028, which could use it.

The obvious question is what this should look like:

- A command that prints the entries?
- A variable that contains them, like $history?

**Comment by septatrix** [comment]
There seems to be `$fish_killring`

**Comment by faho** [comment]
Yup, forgot to close this one (never really sure when exactly Github does that for you).

**Comment by septatrix** [comment]
While at it: Is it somehow possible to remove an entry from the killring? `yank-pop` does not seem to do anything for me (also no rotating which is mentioned in the docs) and `set --erase` does not work for that read-only variable

**Comment by krobelus** [comment]
> While at it: Is it somehow possible to remove an entry from the killring?  `set --erase` does not work for that read-only variable

not yet, probably we should support `set --erase`

> `yank-pop` does not seem to do anything for me (also no rotating which is mentioned in the docs)

it only rotates what is inserted to the commandline after C-y (the GNU Emacs tutorial explains how this kind of killring works)

**Comment by septatrix** [comment]
> not yet, probably we should support `set --erase`

I would also be fine with an extra function. My use case is a `push-line` like functionality with a stack (such that multiple commands can be stored and popped one after another) for which I wanted to use the built in killring. For now I will try to implement it using a normal list.

> > `yank-pop` does not seem to do anything for me (also no rotating which is mentioned in the docs)
> 
> it only rotates what is inserted to the commandline after C-y (the GNU Emacs tutorial explains how this kind of killring works)

Oh that makes a lot more sense now. I did not knew the concept was based on Emacs - that also explains the terminology which was rather confusing to me as I normally associate yanking with copy/cut.

**Comment by septatrix** [comment]
Should I create an issue for that (i.e. some way to remove entries from the killring)?

**Comment by ridiculousfish** [comment]
The killring should probably just be a fish variable.
