### ISSUE TITLE
Does fish support global override filenames completion?

### ISSUE THREAD

**Issue by run27017** [fish-shell/fish-shell#7446]
Just like in bash:

```bash
complete -o filenames -F _pinyin_completion file
```

I have found docs of fish about:

- `complete`: No, it must specify a command
- `__fish_complete_cd`: It seems cannot be overrided

**Comment by faho** [comment]
Fish does not allow overriding the general filename completions for all commands, and I don't think we are going to add that functionality.

There really is very little you can do globally that won't break *some* command. E.g. you'd think you could stop completing backup files (like `.somefile~`), but then what if you want to `rm` them, or if some tool makes a file that has a name like that but it's not a backup file? So a general change here is very unlikely to help.

Instead, what you do is to inhibit file completions for a tool and supply your own.

E.g. 

```fish
complete -c mything --no-files -a '(_pinyin_completion)'
```

if your tool is called "mything" and "_pinyin_completion" is a function that prints filenames.

>__fish_complete_cd: It seems cannot be overrided

It *can*. The question there is what you are trying to accomplish and what you did?

**Comment by run27017** [comment]
I admit overriding the general completions has some destructive effects. On the other hand, there is a certain circumstance that wishing to override the global ones. For example, I want to make an pinyin completion for filenames.

```fish
# current directory has: 浙江 中国 政府
$ cat zj<TAB>
$ cat 浙江
```

For most cases it is harmless because it extends the ability not limits. But it‘s hard to define, isn't it?

I have understood what you said, or the philosophy of fish shell. Maybe I can accomplish my thoughts in a limited way, for example for some certain commands: `cd`、`cat`、`ls` and so on.

 Anything has its own philosophy and fish is not bash. Anyway, thank you for your answer.

**Comment by faho** [comment]
In tha case what you would do is have your *terminal* use the pinyin input method, so fish juat receives the characters after they're done.

**Comment by zanchey** [comment]
Some terminals refer to this as a "compose character" option, I think.

**Comment by run27017** [comment]
> In tha case what you would do is have your _terminal_ use the pinyin input method, so fish juat receives the characters after they're done.

Pinyin input method is not ease in terminal environment, typing the first character '浙‘ is much slower than two characters 'zj', to say nothing of the annoying input method UI. It is the way I am using, and affects my work efficiency. After all, Chinese is ease to read but not to write, no mater in paper or in computer.

**Comment by run27017** [comment]
It seems that fish only complete according to current word prefix. For example, I want to accomplish complete in `cd` command, if I type `cd zj`，and providing completion words such as `["浙江", "最高", "足够"]`，it do nothing. It only works if providing `["zj浙江", "zj最高", "zj足够"]`, which all `zj` prefixed.

It is indeed easier than other shells to write completion. However, the ability maybe too limited.

**Comment by account-login** [comment]
Hello, I have implemented pinyin completion in my fork, in case anyone interested, commit: https://github.com/account-login/fish-shell/commit/e46c034298c256c9c0b6471c6b805a3f0ec08964
The implementation is somewhat hacky though.
