### ISSUE TITLE
Disable Travis

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#7447]
Travis just released "[The new pricing model for travis-ci.com](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing)".

The upshot is:

- Mac builds will cost 50 credits, linux builds 10 credits *per build minute*
- Opensource projects get 10000 credits (per month, I assume)

We've had 84 commits without "ci skip" last month. Given that we have 4 linux builds (that's 40 credits per minute) and one macOS build (50 credits per minute), that means according to this plan we would have used:

(40 + 50) * 3.5 minutes * 84 commits = 26460 credits

which is even blowing the $15 plan they now have (by 1460 credits, but still). Even just with macOS we're at 14700.

They say you can request additional minutes, but given that we're over by a factor of 2.5 (and October was a *quiet month*) I don' t think that'll work and I don't want to beg every month for scraps.

Note that this applies to travis-ci.com, but travis-ci.org will be disabled at the end of the year, so we have ~2 months to figure something out.

Needless to say, I'm not liking this one bit.

**Comment by faho** [comment]
July would have blown the allotment by a factor of 2.5 *on macOS alone* (and almost 5x for mac + linux).

**Comment by faho** [comment]
Buahahaha, it's 1000 credits per month, the 10000 is a one time thing.

**Comment by thernstig** [comment]
https://github.com/features/actions - free for Open Source projects.

**Comment by faho** [comment]
We are [aware](https://github.com/fish-shell/fish-shell/blob/master/.github/workflows/main.yml)

**Comment by krobelus** [comment]
> Buahahaha, it's 1000 credits per month, the 10000 is a one time thing.

Not important at all but where did you get the 1000 p.m. from? It seems like it will depend on the project, or is that what they would give us?

> We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment.

**Comment by faho** [comment]
>Not important at all but where did you get the 1000 p.m. from?

Comments on HackerNews from people who have apparently received emails.

Not the greatest source, but given how unclear Travis' announcement is here and how even the *generous one-time* allotment is basically nothing (seriously, we're a small project with 3.5 minute build time, and it's not even *close* for us) any news at all that it might be even less is baaaaaad.

**Comment by faho** [comment]
Okay, Travis has apparently reduced the resources already to where we wait hours for builds to happen.

I've now added some more slack to the pexpect tests so that Github Actions should succeed, so I'm tempted to just turn off Travis already.

**Comment by faho** [comment]
So I've been hacking some more on Github Actions. I added the other Travis builds (32-bit, asan, thread sanitizer).

For some reason the macOS tests now regularly (?) fail on this:

```python
sendline("fg")
expect_str("Send job 1, 'cat | cat' to foreground")
sendline("set -l foo bar; echo $foo")
expect_str("set -l foo bar; echo $foo")
send("\x04")
```

`\x04` is of course control+d (EOF). It manages to send the background job `cat | cat` to the foreground, but the control+d seems to reach fish as well, so it quits.

If this is pgroup shenanigans, I have no idea why it would only be triggered on Github.

Can anyone on macOS reproduce this?

**Comment by faho** [comment]
Okay, I just disabled Travis. Github Actions should now be doing anything it did, but more importantly it's already basically unusable - hour-long delays before the build even starts.

**Comment by ridiculousfish** [comment]
I'll take a run at the macOS tests.

**Comment by krobelus** [comment]
Wow, that's surprising! This means suspending and resuming `cat` can't work on Mac?
We can probably use `sleep` for `tests/pexpects/fg.py`.

The problem has resurfaced now because we are explicitly skipping interactive tests on Travis, see `tests/interactive.fish`.

**Comment by faho** [comment]
Alright, I changed it to use `sleep` instead. Good call, @krobelus!
