### ISSUE TITLE
How to reset prompt after function called from key binding

### ISSUE THREAD

**Issue by noib3** [fish-shell/fish-shell#7450]
fish version: `fish, version 3.1.2`
OS: macOs catalina 10.15.7
`$TERM`: `xterm-256color`

I'm switching from zsh to fish, and I'm trying to port the following function defined in `~/.config/fish/functions/fuzzy_edit.fish`:

```fish
function fuzzy_edit
  set -l filename (fzf --height=8) \
  && $EDITOR ~/"$filename" || true
end
```

The function works well if called directly, but if I bind it to a key, after exiting `$EDITOR` the prompt doesn't get printed until I press a key.

The equivalent function in zsh would look something like

```zsh
function fuzzy_edit() {
  local filename
  filename="$(fzf --height=8 </dev/tty)" \
  && $EDITOR ~/"$filename" || true
  zle && zle reset-prompt
}
```

What is the fish equivalent of `zle reset-prompt`?

**Comment by faho** [comment]
`commandline -f repaint`
