### ISSUE TITLE
Coloring output generically

### ISSUE THREAD

**Issue by joeky888** [fish-shell/fish-shell#7451]
Like https://github.com/fish-shell/fish-shell/issues/5340 but for more commands.

Consider coloring command output like [grc](https://github.com/garabik/grc) does.

grc is great but it is not actively maintained and it requires python3 as a dependency to run,

I hope fish shell can merge the [syntax files](https://github.com/garabik/grc/tree/devel/colourfiles) into the core and enabled coloring by default without python3.

**Comment by joeky888** [comment]
Without grc

![no grc](https://i.imgur.com/xMvlaxX.png)

With grc

![grc](https://i.imgur.com/RmO4ZIS.png)

**Comment by faho** [comment]
No, thanks.

Really, this should be done by the commands themselves, to benefit everyone. 

We turn on the commands color arguments in limited cases, but we're not in the business of filtering your commanf output. 

Also we use python ourselves, as an optional dependency, so we'd rather you have it.

**Comment by joeky888** [comment]
Ok good to know
