### ISSUE TITLE
Sourcing/Reading Another Config File

### ISSUE THREAD

**Issue by KirliAdam** [fish-shell/fish-shell#7453]
Hello.

I am using fish, version 3.1.2

I have some settings in this config file `~/.config/fish/nnn.fish`

and I want my main config file `~/.config/fish/config.fish` to read that settings.

I used `source ~/.config/fish/nnn.fish` in the main config file but it seems to neglect main settings from the main config file.

Thanks for your time and reply. Sorry for the English.

**Comment by faho** [comment]
This should definitely work.

My guess is what's happening here is that either you have the wrong config.fish (it's `~/.config/fish/config.fish` *with* the "." before "config") or you are running the `source` before the setting you expect to carry over, or you have scoping issues (like a variable set with `set -l`).

Can you post the contents of these files?

**Comment by KirliAdam** [comment]
this is my `~/.config/fish/config.fish`
`set -g default_user yasin`

this is my `~/.config/fish/nnn.fish`
`export NNN_PLUG='f:finder;d:diffs`

I can add all the code in `~/.config/fish/config.fish` but I want to separate them.

**Comment by faho** [comment]
Those are just two entirely independent lines? There are no "main settings" used in nnn.fish, and nothing from nnn.fish is used in config.fish, so I don't understand where the problem is?

1. Where are you putting that `source`
2. Where do you expect that "default_user" to be used?

(also fish automatically reads files placed in ~/.config/fish/conf.d, so you could just put nnn.fish there instead, but I still don't get what your problem here is)

**Comment by KirliAdam** [comment]
"default_user" is used by a command prompt and it works. 
content of the `~/.config/fish/nnn.fish` are related to nnn file manager. If I add `export NNN_PLUG='f:finder;d:diffs'` to my config.fish file it works too. 

If I add `source ~/.config/fish/nnn.fish` command to config.fish it does not work. 
My English is not that good I will give an example.
Lets say this is my `~/.config/fish/config.fish`
`set -g default_user yasin
export NNN_PLUG='f:finder;d:diffs'`

I want: `~/.config/fish/config.fish`
`set -g default_user yasin`
and `~/.config/fish/nnn.fish`
`export NNN_PLUG='f:finder;d:diffs'`

I want this config.fish and nnn.fish files on the `~/.config/fish` directory.
Which command should I use on the config.fish file.

If it is C you can use this command `include exampledocument.c`
or if it is python you can use `import examplepython.py`

Again sorry about English.

**Comment by faho** [comment]
Okay, do the following:

Put this into config.fish:

```fish
set -g default_user yasin
echo SOURCING $NNN_PLUG
source ~/.config/fish/nnn.fish
echo SOURCED $NNN_PLUG
```

and put this into nnn.fish:

```fish
echo NNN
export NNN_PLUG='f:finder;d:diffs'
echo NNN END
```

Then open a new fish and post the output.

**Comment by KirliAdam** [comment]
`echo NNN
export NNN_PLUG='f:finder;d:diffs'
echo NNN END`
That is the output and it gave me the expected result. I was using source command on the first line, I believe that was the problem.

So if I use source at the and of the config.fish will it override the new settings? Or will it merge?

**Comment by faho** [comment]
>So if I use source at the and of the config.fish will it override the new settings? Or will it merge?

It's *code*. It will run the *code*.

If you redefine a variable, it will redefine the variable. If you append to a variable, it will append to the variable.

If you use a variable, it will use the current value of the variable.

There is no special logic to `source` that merges anything, it just runs the code you give it.

If you put the `source` on the first line, it will run the code then, if you put it on the second/third/fourth line it will run it then. 

Unfortunately, this is still missing information - I have no idea what you are *doing* in those other lines, so I can't help you with them.

**Comment by KirliAdam** [comment]
Basically I just want to separate my options for different software. I know some information is missing since my English is not that good there is a possibility that I didn't explain myself clearly.
But I believe your answers are enough for me right now and it looks like I achieved what want to do.
I am still new to coding (If you can call this coding) and trying to figure it out.
When I have more harder questions related to fish-shell I will ask here.
Thanks for the replies and time.
