### ISSUE TITLE
Add support for the Windows clipboard (via WSL) 

### ISSUE THREAD

**Issue by ayoisaiah** [fish-shell/fish-shell#7454]
`xclip` does not integrate with the Windows system clipboard (unless an X server is running), but there are alternatives.

`clip.exe` can be used to copy while `powershell.exe Get-Clipboard` is used to paste. The latter is more of a [workaround ](https://github.com/microsoft/WSL/issues/1069)since no binary for pasting exists.

It'll be great to have these integrated to `fish_clipboard_copy` and `fish_clipboard_paste` respectively for folks using fish in Windows Subsystem for Linux.

**Comment by faho** [comment]
Fixed by merging #7455
