### ISSUE TITLE
Minor warning in src/input.h:40: unused field "in_"

### ISSUE THREAD

**Issue by mojotx** [fish-shell/fish-shell#7456]
Version:  fish, version 3.1.2-1578-gd3192d37a
OS: macOS 10.15.7 Catalina
Compiler:  Apple clang version 12.0.0 (clang-1200.0.32.21)

There's a minor warning issued when compiling on macOS with the `-Wunused-private-field` warning enabled. 

```
[ 60%] Building CXX object CMakeFiles/fishlib.dir/src/input.cpp.o
In file included from /Users/mjarvis/src/github.com/mojotx/fish-shell/src/input.cpp:28:
/Users/mjarvis/src/github.com/mojotx/fish-shell/src/input.h:40:9: warning: private field 'in_' is not used [-Wunused-private-field]
    int in_{0};
        ^
```

I looked at @faho's commit 2a07673561, and I don't see that field initialized in the constructor, and I cannot find where it's used in the code. Can the field be deleted? Or should it be renamed?

**Comment by faho** [comment]
Yeah, no, it's indeed unused - the *constructor* gets an "in" parameter, but that one's just passed to the child input_event_queue_t.
