### ISSUE TITLE
Can't get cursor shape to change in vi mode

### ISSUE THREAD

**Issue by noib3** [fish-shell/fish-shell#7458]
fish version: `fish, version 3.1.2`
OS: macOS Catalina 10.15.7
terminal: `alacritty 0.5.0 (a6681e3)`
`$TERM`: `xterm-256color`

As said in the title, I can't get my cursor shape to change when I change vi mode. I currently have
```
set fish_cursor_default block
set fish_cursor_insert line
set fish_cursor_replace_one underscore
set fish_cursor_visual block
```
in my config.fish. I've tested this with alacritty and with the default macOS terminal, and in neither of them the cursor shape changes.

**Comment by faho** [comment]
Alacritty isn't supported in 3.1.2, it needs 3c6c8d542410cd84b8249c84a58ec28db71fba06, which is only in the next release.

**Comment by noib3** [comment]
@faho I manually added alacritty to the whitelist like in the commit you posted but it still doesn't work.

**Comment by TheoStanfield** [comment]
@noib3 I solved it by manually adding this in my [config.fish](https://github.com/TheoStanfield/dotfiles/blob/master/.config/fish/config.fish)
```
function fish_mode_prompt
  switch $fish_bind_mode
    case default
      echo -en "\e[2 q"
      set_color -o brwhite
      echo "[ "
      set_color -o brred
      echo "N"
      set_color -o brwhite
      echo " ]"
    case insert
      echo -en "\e[6 q"
      set_color -o brwhite
      echo "[ "
      set_color -o brgreen
      echo "I"
      set_color -o brwhite
      echo " ]"
    case replace_one
      echo -en "\e[4 q"
      set_color -o brwhite
      echo "[ "
      set_color -o bryellow
      echo "R"
      set_color -o brwhite
      echo " ]"
    case visual
      echo -en "\e[2 q"
      set_color -o brwhite
      echo "[ "
      set_color -o brmagenta
      echo "V"
      set_color -o brwhite
      echo " ]"
    case '*'
      echo -en "\e[2 q"
      set_color -o brwhite
      echo "[ "
      set_color -o brred
      echo "?"
      set_color -o brwhite
      echo " ]"
  end
  set_color normal
end
```
I hope this solves your problem!!!
