### ISSUE TITLE
Question: syntax highlight output of commandline before executing it

### ISSUE THREAD

**Issue by noib3** [fish-shell/fish-shell#7461]
I have the following function to fuzzy search a file and edit it
```fish
function fuzzy_edit --description "Fuzzy search a file in ~ and \
open it in $EDITOR"
  set -l filename (fzf --height=8) \
  && commandline "$EDITOR ~/"(string replace -a " " "\\ " $filename) \
  && commandline -f execute
  commandline -f repaint
end
```
where instead of executing the command directly, I first print it to the commandline. This way it goes in my command history and I can issue it again using the up arrow key.

I have two questions:
1. this is totally an eye candy, but is it possible to highlight the command before executing it? The following screenshot shows what I mean: the first command was printed by the code I posted, the second one is just the result of an up-arrow. I'd be nice to have them both colored:

![2020-Nov-07@19:45:31](https://user-images.githubusercontent.com/59321248/98449194-d5433e00-2131-11eb-97e0-93eb4fa6a13c.png)

2. Is `commandline "$EDITOR ~/"(string replace -a " " "\\ " $filename)` the right way of escaping whitespaces? I basically substitute every ` ` with a `\ `. I know `string` has a `string escape` option, but I'm not sure how to use it.

**Comment by faho** [comment]
> this is totally an eye candy, but is it possible to highlight the command before executing it?

That's #5912, which was just fixed in master.

>Is commandline "$EDITOR ~/"(string replace -a " " "\\ " $filename) the right way of escaping whitespaces?

You probably want `string escape`:

```fish
commandline "$EDITOR ~/"(string escape -- $filename)
```

the reason for that is that it will escape *everything*, not just whitespace. It'll escape e.g. `$variable` expansion, `(command)` command substitutions and `*` globs. You _probably_ don't want those to run because you picked *a file* in `fzf`.

**Comment by noib3** [comment]
> That's #5912, which was just fixed in master.

That's good to know. Do you know (more or less) when the next release will be?

**Comment by faho** [comment]
"When it's done".

**Comment by noib3** [comment]
> "When it's done".

Fair enough.
