### ISSUE TITLE
Investigate if universal variables are faster than explicit globals

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#7462]
This came out of #7432 where folke observed that universal variables are faster than placing `set -U` in `config.fish` folke identified `set`, `alias`, and `abbr` as slow.

I would expect that `set` in config.fish would be very fast but `abbr` and `alias` might be slower, as these are functions which need to inspect their environment.

@folke if you are willing, can you narrow down which parts of your config.fish are slower than their universal equivalents? Is it the `set` or `abbr` or `alias`, or some mixture?

**Comment by IlanCosman** [comment]
I hope it's okay if I join in here! I did some rudimentary testing. 

Both tests were run with a perfectly clean version of fish 3.1.2. My clean `time fish -i -c 'exit'` is roughly 20 ms.

Universal:
```fish
for i in (seq 1000)
    set -U foo_$i bar_$i
end
```
`time fish -i -c 'exit'` is roughly 25 ms.

Global:
```fish
for i in (seq 1000)
    echo "set -g foo_$i bar_$i" >> $__fish_config_dir/config.fish
end
```
`time fish -i -c 'exit'` is roughly 67 ms.

By my napkin math that works out to .005 ms per universal variable, and .047 ms per global variable. Roughly a 10x difference.

**Comment by folke** [comment]
Further to what @IlanCosman did already, I created a script that sets up different fish environments that can be benchmarked with hyperfine.

```fish
#!/usr/bin/env fish

## Cleanup
rm -rf config

## Baseline
mkdir -p config/set/baseline
XDG_CONFIG_HOME=config/baseline fish -ic exit

## Set
mkdir -p config/set/fish
mkdir -p config/set-universal/fish

XDG_CONFIG_HOME=config/set fish -ic exit
XDG_CONFIG_HOME=config/set-universal fish -ic exit

for i in (seq 50)
    echo "set -gx foo$i bar$i" >>config/set/fish/config.fish
    XDG_CONFIG_HOME=config/set-universal fish -ic "set -Ux foo$i bar$i"
end

## Abbr
mkdir -p config/abbr/fish
mkdir -p config/abbr-universal/fish

XDG_CONFIG_HOME=config/abbr fish -ic exit
XDG_CONFIG_HOME=config/abbr-universal fish -ic exit

for i in (seq 50)
    echo "abbr -g foo$i bar$i" >>config/abbr/fish/config.fish
    XDG_CONFIG_HOME=config/abbr-universal fish -ic "abbr -U foo$i bar$i"
end

## Alias
mkdir -p config/alias/fish
mkdir -p config/alias-universal/fish

XDG_CONFIG_HOME=config/alias fish -ic exit
XDG_CONFIG_HOME=config/alias-universal fish -ic exit

for i in (seq 50)
    echo "alias foo$i bar$i" >>config/alias/fish/config.fish
    XDG_CONFIG_HOME=config/alias-universal fish -ic "alias -s foo$i bar$i"
end

# Execute Hyperfine
function fishy
    echo "XDG_CONFIG_HOME=config/$argv[1]" fish -ic exit
end
hyperfine --warmup 20 (fishy baseline) (fishy set) (fishy set-universal) (fishy abbr) (fishy abbr-universal) (fishy alias) (fishy alias-universal)
```

This script will setup 7 environments under the directory `config` in your current directory (so just run this in a newly created directory for testing, like `~/projects/fish-perf`).

Running this scripts:

```shell
$ fish ./test.fish
Benchmark #1: XDG_CONFIG_HOME=config/baseline fish -ic exit
  Time (mean ± σ):       7.1 ms ±   0.9 ms    [User: 4.4 ms, System: 2.1 ms]
  Range (min … max):     6.2 ms …  13.5 ms    263 runs
 
Benchmark #2: XDG_CONFIG_HOME=config/set fish -ic exit
  Time (mean ± σ):       7.8 ms ±   0.9 ms    [User: 5.0 ms, System: 2.1 ms]
  Range (min … max):     6.4 ms …  12.4 ms    246 runs
 
Benchmark #3: XDG_CONFIG_HOME=config/set-universal fish -ic exit
  Time (mean ± σ):       7.3 ms ±   0.9 ms    [User: 4.5 ms, System: 2.1 ms]
  Range (min … max):     6.1 ms …  13.6 ms    262 runs
 
Benchmark #4: XDG_CONFIG_HOME=config/abbr fish -ic exit
  Time (mean ± σ):      37.7 ms ±   1.5 ms    [User: 31.8 ms, System: 5.9 ms]
  Range (min … max):    35.1 ms …  45.4 ms    73 runs
 
Benchmark #5: XDG_CONFIG_HOME=config/abbr-universal fish -ic exit
  Time (mean ± σ):       7.1 ms ±   0.8 ms    [User: 4.5 ms, System: 1.9 ms]
  Range (min … max):     6.1 ms …  11.7 ms    275 runs
 
Benchmark #6: XDG_CONFIG_HOME=config/alias fish -ic exit
  Time (mean ± σ):      37.6 ms ±   2.6 ms    [User: 30.1 ms, System: 9.2 ms]
  Range (min … max):    34.4 ms …  53.2 ms    74 runs
 
Benchmark #7: XDG_CONFIG_HOME=config/alias-universal fish -ic exit
  Time (mean ± σ):       7.1 ms ±   0.8 ms    [User: 4.4 ms, System: 2.1 ms]
  Range (min … max):     6.1 ms …  11.8 ms    270 runs
 
Summary
  'XDG_CONFIG_HOME=config/abbr-universal fish -ic exit' ran
    1.01 ± 0.16 times faster than 'XDG_CONFIG_HOME=config/alias-universal fish -ic exit'
    1.01 ± 0.17 times faster than 'XDG_CONFIG_HOME=config/baseline fish -ic exit'
    1.03 ± 0.17 times faster than 'XDG_CONFIG_HOME=config/set-universal fish -ic exit'
    1.11 ± 0.17 times faster than 'XDG_CONFIG_HOME=config/set fish -ic exit'
    5.33 ± 0.69 times faster than 'XDG_CONFIG_HOME=config/alias fish -ic exit'
    5.35 ± 0.62 times faster than 'XDG_CONFIG_HOME=config/abbr fish -ic exit'
```

Interpretation of the results:
* baseline takes 7.1ms
* overhead of `set`
  * `config.fish`: 0.7ms
  * `fish_variables`: 0.2ms
  * the difference is negligible
* overhead of `abbr`
  * `config.fish`: 30.6ms
  * `fish_variables`: 0ms
  * there seems to be a huge performance impact of using universal abbreviations as opposed to defining them in your `config.fish`
* overhead of `alias`
  * `config.fish`: 30.6ms
  * `fish_variables`: 0ms
  * the universal variant of alias simply creates a file in `functions`, so as expected this should perform exactly as the baseline.

**Comment by IlanCosman** [comment]
Hyperfine isn't accurate at all for this use case. I get 6 ms with hyperfine, while `time fish -ic exit` (which I assume can be considered more accurate) gives me 20ms.

**Comment by folke** [comment]
@IlanCosman yeah, I noticed that as well, but I wouldn't say it's not useable because of that. The difference is probably due to event handlers running after each and every command (like in a for loop). Hyperfine simply uses system exec, so not executing within a shell which is always faster.

Either way, simply using `time` also shows that using universal variants for `alias` and `abbr` is much faster than the other way.

**Comment by faho** [comment]
Thank you for bringing some numbers to the converation!

I don't think what they tell us is really anything revolutionary:

- Variables are fast
- Universal variables are ever so slightly faster than running an actual `set`, but probably not enough to bother
- `alias` is terrible, functions are good
- `abbr` isn't a speed demon (tho it's faster than alias on my machine for some reason)

I'm closing this because I don't think there's anything specifically odious here - 30ms overhead for *50* aliases (which is already unusually many) isn't terrible. 30ms delay for interactive startup is acceptable, and my guidance has always been to avoid `alias` anyway.

The only real issue is in non-interactive shells, and those need an `if status is-interactive` guard in the config anyway (I maintain we shouldn't be reading the config non-interactively, but that's a different matter)

So it's a matter of "make everything faster", which is a standing order anyway, and as it turns out, current git master is ~20% faster than 3.1.2 across the board in this benchmark.

**Comment by ridiculousfish** [comment]
Having done some profiling, the biggest time consumers here are `malloc` (18.1%) and `free` (5.1%). This isn't surprising, as fish makes heavy use of `std::wstring` which is allocation heavy.

Unfortunately the allocations are diffuse; there is no single place it can be fixed. What we really need is a better strings (and vector) library that supports `string_view` and perhaps reference-counted immutable strings. That's tracked in #5268.
