### ISSUE TITLE
Allow source command to create local variables

### ISSUE THREAD

**Issue by AnthonyMonterrosa** [fish-shell/fish-shell#7463]
I think it'd be nice if the `source` command allowed local variables to be set in the calling script. Currently, sourcing a file will result in all local variables declared in it to have no value. This leaves the options of setting the variable to global or universal, and neither respect scoping.

My reasoning is that `source` should behave as analogous to typing those commands directly into the calling script as possible. Reading the `source` documentation, it does mention creating a block scope. Could it be possible to flatten that scope, or optionally not create it?

`fish --version` outputs `fish, version 3.1.2-1587-gb0f338cf1`.

**Comment by faho** [comment]
This is what local variables are *for*. Local variables are *supposed* to go out of scope as soon as you leave the current piece of code.

If you want a variable to stay for longer, make it global.

There is a point to be made for introducing a scope in between, that's #565, and I see that #3540 asked for an "upvar" mechanism.

I'll close this issue in favor of those two, as I don't think we want to stop `source` from creating a block.
