### ISSUE TITLE
#982 (and its FAQ entry) is incorrect

### ISSUE THREAD

**Issue by mildsunrise** [fish-shell/fish-shell#7465]
Posting as a new issue because #982 was locked...

The proposed solution there, and the FAQ entry, tell the user to run `pkg-config` (or similar tools) through `string split ' '` before the substitution.

This is not enough. When [bash does word splitting](https://www.gnu.org/software/bash/manual/bash.html#Word-Splitting), it will first trim the string (IFS characters are the start / end of the string are removed) and then it will split on *sequences* of IFS chars, not single occurrences of a character. But `string split ' '` does simple splitting, so if `pkg-config` outputs something that has a space in the end (or two spaces between words), then an empty argument will be passed to gcc and you get this cryptic error:

~~~
gcc: error: : No such file or directory
~~~

It would be great if you could unlock that issue and post a comment there linking to this one, or to the FAQ entry when it is updated.

**Comment by mildsunrise** [comment]
based on the docs, I think using `string split -n " "` should give equivalent behaviour to bash

**Comment by faho** [comment]
Have you managed to find this in the real world or is this theoretical?

**Comment by mildsunrise** [comment]
Yes, it just happened to me (that's how I got that gcc error).

**Comment by faho** [comment]
What was the pkg-config invocation you used? With which .pc file?

**Comment by mildsunrise** [comment]
I'm using Arch and it was `pkg-config --cflags gstreamer-1.0`, which returns:

~~~
-I/usr/include/gstreamer-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -pthread 
~~~

(note the space at the end)

**Comment by faho** [comment]
I changed the invocation in the FAQ to include a "-n".

Thanks!
