### ISSUE TITLE
Nitpick: __fish_print_packages should be __fish_complete_packages

### ISSUE THREAD

**Issue by dag** [fish-shell/fish-shell#747]
Docs say:

> Functions beginning with the string '__fish_print_' print a newline-separated list of strings. For example, __fish_print_filesystems prints a list of all known file systems. Functions beginning with '__fish_complete_' print out a newline separated list of completions with descriptions. The description is separated from the completion by a tab character.

**Comment by faho** [comment]
Let's track this in the larger #2440
