### ISSUE TITLE
Extended preexec functionality

### ISSUE THREAD

**Issue by czaplicki** [fish-shell/fish-shell#7470]
Add the ability to edit the commandline content, so that you can parse and replace parts of it before execution. Right now you can only parse it's content and execute additional commands.

This would enable things like line decoration, identical function of the !! Operator from posix, abriviations of commands inside scripts, etc.

Easiest and most intuitive solution would be to delay the reset of the buffer used by commandline. This would remove the ability to populate the command line buffer during this event, but that could easily be done form postexec instead.

When I looked through the code base, I saw that it should be pretty trivial to add this ability, and I'd be happy do it and do a pull request. If it would be a welcomed alteration.

**Comment by ridiculousfish** [comment]
What does "line decoration" mean?

I am nervous about a feature like this built on raw text, though I admit it would be flexible.

**Comment by faho** [comment]
Here's what we're gonna do:

- Add an `expand` builtin so you can run  specific expansions, even on a key press (#5811) 

- Add global abbreviations (#5003)

Closing this in favor of those two.

**Comment by czaplicki** [comment]
Line decorations are things like
Cmd arg arg sudo
Cmd arg arg if cmd

So things that alter the execution, declared at the end, instead of the beginning.

**Comment by czaplicki** [comment]
Would the implementation of those two issues enable line decorations in any way?
