### ISSUE TITLE
fish zfs completion should only request snapshots when demanded

### ISSUE THREAD

**Issue by Debilski** [fish-shell/fish-shell#7472]
Currently (fish 3.1.2) doing a

    zfs get refquota <TAB>

will cause fish to execute `zfs list -t snapshot -o name -H` and then list all available snapshots. The command is also executed when the name of the filesystem/snapshot is already partially specified. With 100s of file systems and perhaps 30 snapshots per file system, this is going to take a long time (few seconds) for each `<TAB>`. 

(Additionally, it makes the result basically useless, as there will only be space for the file systems starting with the letter a.)

In the bash completion script, it seems that at first they only query and list the file systems and print them as `fs1 fs1@ fs2 fs2@`, so that the `@` version can be selected when one wants to query a particular snapshot. See https://github.com/openzfs/zfs/blob/master/contrib/bash_completion.d/zfs#L68 This works much faster. It would be nice if the completions in fish could be similarly improved.

**Comment by krobelus** [comment]
Makes sense. I didn't check the bash completions in detail, but I think we can just cache the list of snapshots.
We do someting similar for package lists, for example [rpm packages are cached for 4 minutes and 10 seconds](https://github.com/fish-shell/fish-shell/blob/36337fc45d2c37b22c3cb2d2634e0a8be1e55492/share/functions/__fish_print_packages.fish#L133-L146).

**Comment by mqudsi** [comment]
I just pushed out 6bd4f52b0d410eafdae9958cdbd2b4b1f0191c4e which tries to mitigate this somewhat. I'm not a huge fan of caching the list of datasets or snapshots because then we would have to deal with invalidating them - it's quite likely (and maybe even probable) that the very next command after creating a new dataset or snapshot would reference said dataset/snapshot, in which case the completions would be wrong.

**Comment by krobelus** [comment]
Good point, caching only works well for things the users don't change often.

**Comment by Debilski** [comment]
@mqudsi On my zfs system, I can run

    zfs list -H -o name -s name -t snapshot -d 1 sub_zfs

and only see the snapshots of that sub_zfs. Is this what you were looking for in the comment to 6bd4f52 ?

**Comment by mqudsi** [comment]
Ah, you must specify either `-d` or `-r`, thanks for the pointer!
