### ISSUE TITLE
enabling multiple candidate commands for auto-completing cmds

### ISSUE THREAD

**Issue by NEWPLAN** [fish-shell/fish-shell#7475]
Hi, 
Thanks for your contributing this awesome shell,   which is the best shell that I have ever experienced!
Currently, fish-shell recommends only one standby cmd from history, by default (my current version is 3.1.2).
I would like to ask  that:
If it is possible to list multiple candidate  (auto-completion) cmds (maybe configure it with a threshold in avoidance of overwhelming the terminal)?  I think it would be very helpful to improve the experience of auto-completing cmd when there are some similar cmds with only some minor differences.
Or, the current version has already support this feature? if so, could you show me how to enable this feature?

**Comment by faho** [comment]
Thank you for your suggestion.

We won't be taking it.

The magic of autosuggestions (what this feature is called) is precisely that it's relatively low-impact. You get one, which doesn't have to be from history at all (fish can synthesize new commandlines you've never even run), and it either is what you want to do, so you just pick it, or it's not, and you just continue typing.

Adding more would mean more cognitive load (as you need to scan through all the possibilities), another key to switch between them (tab is taken for completions, which try to give you all the possible tokens we think are valid, up/down arrow are taken for history search), more load on the system (as we'd have to generate more suggestions).

And if you want to scroll through the (matching) history, you can just press up-arrow.

So overall this doesn't seem like a good idea. Sorry!
