### ISSUE TITLE
Copy timestamps when importing .bash_history

### ISSUE THREAD

**Issue by rypervenche** [fish-shell/fish-shell#7479]
I would like to request changing `should_import_bash_history_line` in `history.cpp` to accept timestamps during import of .bash_history, which are in the form below:

```bash
#1446515592
ls
#1446515600
find . -iname "*txt"
#1446515603
ls
```

Being able to keep command timestamps when migrating to a new shell would be very nice to have.

=====================
version: 3.1.2
terminal: alacritty
OS: Gentoo Linux Testing
kernel: 5.4.75-gentoo
term: xterm

**Comment by faho** [comment]
Thank you for your suggestion.

Unfortunately I don't think we'll be taking it, and here's why:

> which are in the form below:

>#1446515592
>ls

That isn't the form. The form is whatever $HISTTIMEFORMAT is set to at the time the entry was written, and it's passed to strftime(3).

That means:

- It can be anything - it could be the epoch like you have here, on a separate line, or it could be something like `HISTTIMEFORMAT="%F %T: "`, which results in `33916  2014-12-18 11:03:08: echo foo` (yes, on the same line)
- It could be localized, in a different locale from what fish has
- It could be multiple values in the same history file (whatever $HISTTIMEFORMAT is set to *at the time the entry was written*)
- It could just be a time of day, or just a month, or the string "supercallifragilisticexpialidocious"
- There is no default - or rather the default is not to write the timestamp, meaning most users won't actually have any data at all

In addition it's super ambiguous, like bash's history format in general (multiline commands are basically impossible to parse). Any command could include something that *looks* like a timestamp but isn't.

Also the time isn't super important (we only show it with `history --show-time`) and the order should still be valid (well, basically. Multiple bashes can be interleaved, but that's not super important).

So this is a lot of work that is actually impossible to get 100% right, quite tough to get even close to okay-ish for most cases (and not break on the others), for very little benefit.

Sorry!
