### ISSUE TITLE
Skip unchanged man pages with fish_update_completions

### ISSUE THREAD

**Issue by dag** [fish-shell/fish-shell#748]
I'm thinking when writing a generated completion file, set its ctime to that of the source man page, and before parsing a man page see if there's an existing generated completion file and if the ctimes match.

This might speed up subsequent updates considerably, making it less costly to run after installing new programs.  To force a full update simply remove the `generated_completions` directory, or possibly we could add an argument to the function.

**Comment by krader1961** [comment]
Four years have gone by and no one has implemented this idea.
