### ISSUE TITLE
dialogs in subcommands stopped working

### ISSUE THREAD

**Issue by Eun** [fish-shell/fish-shell#7487]
I have the following code and all of a sudden it stopped working (probably due to a version update).
The execution hangs at this line:
```
set -l RESULT (dialog --output-fd 1 --radiolist "Which option you want?" 0 0 0 A A OFF B B OFF)
```
I am running fish version 3.1.2, I also tried without third-party customizations.

I narrowed it down to the subcommand behaviour:
So running
```dialog --msgbox "Hello World" 0 0```
works as expected

```echo (dialog --msgbox "Hello World" 0 0)```
hangs for ever.

This bug can be recreated in https://rootnroll.com/d/fish-shell/ (fish version 3.0.2)

Notice that using `dialog` or `whiptail` makes no difference.

**Comment by faho** [comment]
Works for me with 3.1.2. Please double check that you actually have 3.1.2, as Ubuntu only ships 3.1.**0**.

Also what does `type dialog` say?

**Comment by Eun** [comment]
Yes its 3.1.2
type dialog points to `/usr/bin/dialog` so everything is fine. However I fixed the problem using the `3>&1 1>&2 2>&3` redirection:
```echo (dialog --msgbox "Hello World" 0 0 3>&1 1>&2 2>&3)```

Just feels wired for me because it used to work ¯\_(ツ)_/¯

**Comment by faho** [comment]
That's a workaround, not a fix. I'd still like to know what's going on here.

**Comment by Eun** [comment]
So apparently I did not test correctly.

```
echo (dialog --msgbox "Hello World" 0 0) # Does not work
echo (dialog --output-fd 1 --msgbox "Hello World" 0 0) # Does work
echo (whiptail --msgbox "Hello World" 0 0) # Does not work
echo (whiptail --output-fd 1 --msgbox "Hello World" 0 0) # Does not work
```

**Comment by zanchey** [comment]
> hangs for ever.

It's waiting for input, hit enter and you'll get your session back.

**Comment by ridiculousfish** [comment]
@Eun the command `echo (dialog --msgbox "Hello World" 0 0)` hangs for me all the way back to fish 2.7. Is that the command which used to work for you, or is there another?

**Comment by Eun** [comment]
@ridiculousfish This was not the exact command, however it was used to replicate the behaviour.
My conclusion is that its not a `fish` problem its more a `dialog` / `whiptail` problem.
