### ISSUE TITLE
Standalone fish for Windows

### ISSUE THREAD

**Issue by Midi-In** [fish-shell/fish-shell#7488]
I'm running Windows 8.1 64-bit and ConEmu terminal emulator. I would like to use fish directly in it, and prefer to avoid installing it as a part of packages like MSYS or Cygwin.

Is that a feasible option or does fish depend too strictly on some functionality provided by those packages (presumably the POSIX layer emulation)? If so, what are the chances that distributing standalone fish for Windows could be considered in future?

**Comment by faho** [comment]
Not feasible, sorry.

**Comment by zanchey** [comment]
Yes, fish uses a number of POSIX-compatible utilities and libraries, as well as a fairly wide feature set from the API. Services for Unix / Subsystem for UNIX-based Applications probably would have worked, but that's removed in 8.1 and I don't think you can get it for older versions any more.
