### ISSUE TITLE
Text is being echoed before the prompt is ready

### ISSUE THREAD

**Issue by rnhmjoj** [fish-shell/fish-shell#7489]
Unfortunately I have a rather slow prompt (can take >250ms) and it happens that I start typing text into the shell before the prompt is ready. This hasn't been an issue since fish would just delay the echo for a moment, until  the prompt is printed.
Starting from 2a3677b38659835858c9d557e7d920630bfbcbb8, however, at least part of the text is printed immediately and duplicated:

![report](https://user-images.githubusercontent.com/2817565/99719856-2695ea80-2aad-11eb-8e3f-c8045cbe2eca.png)

This is not a big deal but it's a bit ugly. Is there something I can do (besides optimising the prompt) to revert to the previous behavior?

cc: @faho

**Comment by rnhmjoj** [comment]
For the moment I came up with this:
```
function fish_greeting
  clear
end
```
It's not perfect because sometimes the text is still not cleared but it's something.

**Comment by ridiculousfish** [comment]
Let's move the call to set the tty to shell modes above the call to `fish_prompt`. This will make the prompt run with shell modes, but I feel confident in that change, because that's how fish worked prior to 2a3677b38659835858c9d557e7d920630bfbcbb8.  Thanks for filing!
