### ISSUE TITLE
Want to edit fish_user_paths in fish_config

### ISSUE THREAD

**Issue by walles** [fish-shell/fish-shell#7504]
# Request

I want to be able to launch `fish_config` and edit `fish_user_paths` from that web UI.

The point is that I edit those pretty seldom, and each time I do I have to look it up online.

If I could just edit my path in `fish_config` then I'd never have to look it up any more.

# Environment

macOS Catalina 10.15.7

```sh
~ $ fish --version
fish, version 3.1.2
~ $ echo $version
3.1.2
~ $ uname -a
Darwin Johans-MacBook-Pro-10.local 19.6.0 Darwin Kernel Version 19.6.0: Thu Oct 29 22:56:45 PDT 2020; root:xnu-6153.141.2.2~1/RELEASE_X86_64 x86_64
~ $ echo $TERM
xterm-256color
~ $
```

**Comment by zanchey** [comment]
Yeah, you can do it from the "variables" tab, but perhaps it should be made available as its own tab?

**Comment by walles** [comment]
Um, but I can't actually edit anything in the "variables" tab.

If I click variables in there nothing happens.

**Comment by zanchey** [comment]
Ah, indeed, some discussion in #3363 as well

Sounds like a good thing for someone to tackle!

**Comment by faho** [comment]
Let's leave this in #3363, which is a bit broader in scope.
