### ISSUE TITLE
MacOS fish Installer still requires Rosetta on install

### ISSUE THREAD

**Issue by rufat-badal** [fish-shell/fish-shell#7505]
<img width="732" alt="image" src="https://user-images.githubusercontent.com/19675055/100108490-21e58380-2e6b-11eb-8c0e-dd9c5c2bd3b7.png">

Starting today, it was announced that the standard installer offered on you homepage runs natively on Apple Silicon.
Nevertheless, I still get the Rosetta warning when executing the installer.
I also tried the fish App offered on your webpage and it seems to run natively on Macs with Apple Silicon.
Maybe your installer itself has some components dependent on x86?

**Comment by ridiculousfish** [comment]
This is really surprising. Can you please confirm that you got the universal package? Easiest way is through its size - the universal package is 6.6 MB while the x86-only one is 4.9 MB.

I'm not sure how to uninstall Rosetta to test this unfortunately.

**Comment by rufat-badal** [comment]
Thanks for the reply!

The one I use has the larger 6.6 MB size.

<img width="377" alt="image" src="https://user-images.githubusercontent.com/19675055/100400435-d55e9b80-3056-11eb-886c-92d265fe033d.png">

I get the error as above:

<img width="732" alt="image" src="https://user-images.githubusercontent.com/19675055/100400456-e7403e80-3056-11eb-8a5c-ecef5ef51bfe.png">

I am not an expert on macOS installers, but maybe it is something in the installer itself that needs Rosetta.

At the end of the day, I simply installed fish through Homebrew, which works like a charm!

**Comment by faho** [comment]
Can we confirm if this is still an issue with fish 3.2.0?

**Comment by ridiculousfish** [comment]
Unfortunately I do not have a way to confirm. I will close this; please reopen if you still see this.

**Comment by floam** [comment]
This is a real issue, sorry!
