### ISSUE TITLE
More math parenthesis errors

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#7508]
This time, when forgetting to use a `$` for variables:

```fish
mqudsi@studiog3 ~/fish-shell (regex_import) [127]> math n + 1
math: Error: Missing opening parenthesis
'n + 1'
   ^
```

**Comment by faho** [comment]
This assumes "n" is a function.

We should probably check if it's a valid function name before we complain about the syntax. 

But if you used e. g. "sin" instead complaining about the parens would be totally valid.

**Comment by faho** [comment]
Okay, it turns out we *did* check if it's a valid function name, but the check only compared up to the length of the given token, so it would assume "n" is equal to "ncr".

That means technically `math 'n(2,3)'` is equivalent to `math 'ncr(2,3)'`.

Yeah, we're changing that.
