### ISSUE TITLE
macOS 11: slow command autocompletion

### ISSUE THREAD

**Issue by golimpio** [fish-shell/fish-shell#7511]
After updating to Big Sur, I'm experiencing a few seconds delay every time I press tab for auto completing a command.

For example, if I type `ls` and then press [tab], _fish_ will take a few seconds before displaying the list of commands starting with "ls".

This issue seems to be similar to #6270 

Tried _fish_ without third-party customizations? 
- Yes, same issue.

My environment:

```
>  fish --version
fish, version 3.1.2

>  uname -a
Darwin dellicia.local 20.2.0 Darwin Kernel Version 20.2.0: Tue Nov 10 21:14:14 PST 2020; root:xnu-7195.60.70.111.1~1/RELEASE_X86_64 x86_64

> echo $TERM
xterm-256color
```

Running _fish_ with `--profile`, the only odd thing I've identified was:
```
1757591	1757591	-> apropos $argv 2>/dev/null | awk -v FS=" +- +" '{
		split($1, names, ", ");
		for (name in names)
			if (names[name] ~ /^'"$argv"'.* *\([18]\)/ ) {
				sub( "( |\t)*\\\([18]\\\)", "", names[name] );
				sub( " \\\[.*\\\]", "", names[name] );
				print names[name] "\t" $2;
			}
	}'
```

Similar to the other issue linked here.

**Comment by piechologist** [comment]
I had the same issue. Thank you @golimpio for mentioning [#6270](https://github.com/fish-shell/fish-shell/issues/6270). I replaced my `__fish_describe_command` (see [this comment in #6270](https://github.com/fish-shell/fish-shell/issues/6270#issuecomment-548515306) and auto completing is snappy again.

Seems like Apple had silently fixed the underlying bug in macOS 10.15.4 and has silently reintroduced it in macOS 11.0.1?

**Comment by golimpio** [comment]
Sorry, I forgot to mention that I’m running 11.1 beta, thanks for confirming that 11.0.1 has the same issue.

**Comment by faho** [comment]
Wonderful.

#7365 is the best we can do here - in the next release, we will cache the `apropos` output on macOS and invoke makewhatis in the background. This is not gated on version.
