### ISSUE TITLE
subshell shifting colors slightly

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7512]
This bug was driving me nuts trying to find it's source in my code, until i realized it was there in a perfectly clean fish instance.

Here's the code I used to demonstrate.

```fish
function compare_blocks -a color
    print_block $color
    fish -c "print_block $color"
end
```
```fish
function print_block -a color
    set -l square_size 3
    
    set_color -b $color
    
    for i in (seq $square_size)
        string repeat --count (math $square_size x 3) ' '
    end
end
```

![image](https://user-images.githubusercontent.com/6318351/100411877-cad8dd80-3027-11eb-91cd-7854f491df29.png)

<div align="center">
<sub>

fish, version 3.1.2

Linux anarchy 5.9.10-arch1-1 #1 SMP PREEMPT Sun, 22 Nov 2020 14:16:59 +0000 x86_64 GNU/Linux

xterm-256color

Clean fish

</sub>
</div>

**Comment by faho** [comment]
What most likely happens here is that the inner and outer fish disagree on whether you have truecolor support, so one of them falls back on 256 color output, which ends up looking slightly different.

Check $fish_term24bit in both.

**Comment by IlanCosman** [comment]
Yup, that works. Thanks @faho as always 😄
