### ISSUE TITLE
For loop not executing

### ISSUE THREAD

**Issue by Joeperdefloep** [fish-shell/fish-shell#7527]
A for loop does not execute when typed in the terminal. It does work in terminology with the same syntax

https://asciinema.org/a/WcRdr0HGJH7YPohdDEtDPNchw

**Comment by faho** [comment]
You're entering bash syntax. Fish is *not* bash-compatible.

In this specific case you haven't terminated the for-loop - fish's for-loops end with `end`, not `done`, so fish is still waiting for input.

The reason it runs in terminology is presumably because that runs bash.

The fish syntax is:

```fish
for i in (seq 1 5)
    echo $i
end
```

**Comment by Joeperdefloep** [comment]
Thank you so much! I could not find it in the documentation and it was giving me headaches. (was there a better way than posting an issue? I understand it bloats the issues page?)
kind regards,
Joep

**Comment by faho** [comment]
You could have checked [the page for `for`](https://fishshell.com/docs/3.1/cmds/for.html), which shows examples.

And this is why I wrote the fish-for-bash-users document, so you get a quick overview of the incompatibilities.

Or, alternatively, for quick questions ask on https://gitter.im/fish-shell/fish-shell instead.
