### ISSUE TITLE
Broken documentation content

### ISSUE THREAD

**Issue by kidonng** [fish-shell/fish-shell#7529]
I was reviewing the documentation when I noticed issues like #6640:

- Broken layout

  Some styles are missing:

  ![image](https://user-images.githubusercontent.com/44045911/101165566-d5235900-3671-11eb-9dc8-628992683660.png)

- Duplicate content

  ![image](https://user-images.githubusercontent.com/44045911/101165671-04d26100-3672-11eb-930f-23592e57d109.png)

  Interesting enough, the source doesn't have this duplicated content.

**Comment by faho** [comment]
Fixed by 2740473a65e43823b663782337ae57bc38bf6bb8 and #7024.

**Comment by kidonng** [comment]
Oh sorry! I did a quick search before submitting the issue, but looks like I just slipped over them.

Curiously though, does this mean the documentation site only gets updated when new versions are released? Because those changes are quite some time ago.

**Comment by zanchey** [comment]
Yes. There is not a great deal of wisdom in published documentation that does not reflect the published software.
