### ISSUE TITLE
Produce signed Mac OS X packages

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#753]
https://news.ycombinator.com/item?id=5723298

Is this something we want to do?

**Comment by zanchey** [comment]
No chance of any movement on this at present.

**Comment by floam** [comment]
Being an registered developer in good standing I can have Distribution Certificates which are able to be shared privately between team members. If this is really a matter of $100 or the inaccessibility I'd be happy to help a trusted fish developer produce signed, verifiable binaries.

Or if anyone crazy enough wants one send me an email, I can send you a signed, built fish HEAD for your personal usage. I have a custom kernel extension which insta-kills unsigned binaries from the Internet on my personal system and and system state auditing tools work which really go crazy over spooky non-standard binaries in the $PATH that are not accountable. i sympathize with anyone with as much OCD as me or dealing with situations like that.

It'd be better if someone on the team could just do it themselves frankly.
