### ISSUE TITLE
Help creating a test case for a crash

### ISSUE THREAD

**Issue by ericonr** [fish-shell/fish-shell#7531]
Hi!

I'm running fish 3.1.2, where I found a very weird crashing bug. However, it didn't happen with a build from master, so I'd appreciate some help in writing a test case to guarantee it can't regress.

I'm usually on Linux with musl libc, but it also happens with glibc. It happened both inside tmux and in alacritty. I tested with a clean profile.

The command I tried to run was:

```
fd --no-ignore -t x "" bin/ -x du | awk '{print $1}' | bc < +
```

Where the `+` file doesn't exist. With fish 3.1.2, it locks up and crashes if I press any key (the window closes or the panel goes away in tmux). With the version from master, it works just fine.

The basic reproducer seems to be

```
cat | cat < non_existing_file
```

**Comment by krobelus** [comment]
Sounds like #7038. I believe there is no test at the moment, you're welcome to add a test (probably to `tests/checks`).

Also see https://github.com/fish-shell/fish-shell/issues/7411#issuecomment-715669301 which suggests throwing a parser error on this specific case:

> cat | cat < foo isn't borderline invalid, it's just invalid. fish mimics bash here and just drops the < foo because there's already an input, but tbh the most correct thing to do would be throw a parser error and fail to even execute.

**Comment by ericonr** [comment]
Oh, so this had been reported already! Good to know :) 

I will see if I can flex my C++ muscles and get something going for the other problems mentioned in those issues. Will try to add the test as well.

Thanks!

**Comment by faho** [comment]
Okay, I added a test in 8172ad44630346578c194f3a33434b0224b9918d (and totally fudged the issue number).
