### ISSUE TITLE
Support for =

### ISSUE THREAD

**Issue by squidink7** [fish-shell/fish-shell#7533]
Whenever variables are set using foo=bar fish tells the user to use set foo bar, however seeing as fish doesn't do anything in it's place and just displays a warning, would it be possible to implement basic support for foo=bar? this would fix a lot of compatibility issues with simple scripts and would help ease the transition for people coming from posix shells. If there is a function that is called that might cause some issues with this you could display a warning telling users to use the set syntax, however as far as I'm aware there is nothing stopping the translation of foo=bar commands to set foo bar at least in the case where it would usually display the error. This along with the addition of && and || that happened at 3.0 it would help a ton in making simple scripts and guides built for posix shells work with less modifications, and an overall nicer experience with less friction for new users.

**Comment by squidink7** [comment]
Whoops, github search didn't show #6048, my bad.
Closing because duplicate

**Comment by squidink7** [comment]
Whoops, accidentally closed, sorry. Still getting used to github.

**Comment by faho** [comment]
Sorry, but no.

`var=val` works badly with scopes (which we really want you to pick) and lists (which we really want to emphasize).

It's also another way of doing the same thing, and compatibility is a non-goal for fish.
