### ISSUE TITLE
Shell completion issues on macOS: illegal option -- r

### ISSUE THREAD

**Issue by guw** [fish-shell/fish-shell#7536]
```
❯ fish --version 
fish, version 3.1.2

~ 
❯ echo $version 
3.1.2
```

I installed fish via Homebrew `brew install fish`.

Upon tab completion I run into the following error on macOS:
```
❯ brew install menumsed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
```

This is probably caused by the `sed` on macOS:
```
❯ which sed
/usr/bin/sed
```

**Comment by faho** [comment]
If this is only happens with the `brew` completions, we can't do anything about it as [ŧhose are maintained upstream](https://github.com/Homebrew/brew/blob/master/completions/fish/brew.fish).

Weirdly enough I can't find a `sed` call in them, anywhere.

**Comment by guw** [comment]
I saw it happing with other commands too.

**Comment by faho** [comment]
>  Is there any man/help parsing built into fish?

There is, but it's a python script that really only figures out the `-foo` options for commands, there is no sed involved, either in creating the completion scripts or in the generated scripts.

In fact checking the entirety of fish 3.1.2, `sed -r` was only ever used in very few places, some of which are directly guaranteed to have GNU sed (e.g. the completions for `apt` or `emerge` - I'm pretty sure those already require GNU tools), and the others being rarely used completions for things like `setxkbmap`. **Nothing** in the core anywhere.

So: Please confirm that you do not have any third-party modifications enabled. This includes oh-my-fish and fisher.

Also please confirm that `type sed` (basically forget that `which` exists - it shouldn't be used in general) says you're using /usr/bin/sed.

**Comment by guw** [comment]
Maybe it is Homebrew specific. I'll keep monitoring it.

![image](https://user-images.githubusercontent.com/191472/101515108-49197600-397e-11eb-9566-118603ef8b2d.png)

**Comment by faho** [comment]
Turns out it's https://github.com/Homebrew/brew/pull/9367 / https://github.com/Homebrew/brew/issues/9388
