### ISSUE TITLE
Global $PATH is set without reason

### ISSUE THREAD

**Issue by MichaelJDrK** [fish-shell/fish-shell#7539]
fish, version 3.1.2

Installed using brew on MacOS 10.15.7. Terminal is iTerm2.

$ echo $__fish_config_dir
/Users/-redacted/.config/fish

$ echo $__fish_sysconf_dir
/usr/local/Cellar/fish/3.1.2/etc/fish

When using 
set -S PATH
I get this output:

$PATH: not set in local scope
$PATH: set in global scope, exported, with 5 elements
$PATH[1]: length=14 value=|/usr/local/bin|
$PATH[2]: length=8 value=|/usr/bin|
$PATH[3]: length=4 value=|/bin|
$PATH[4]: length=9 value=|/usr/sbin|
$PATH[5]: length=5 value=|/sbin|
$PATH: set in universal scope, exported, with 6 elements
$PATH[1]: length=32 value=|/Users/-redacted-/bin|
$PATH[2]: length=14 value=|/usr/local/bin|
$PATH[3]: length=8 value=|/usr/bin|
$PATH[4]: length=4 value=|/bin|
$PATH[5]: length=9 value=|/usr/sbin|
$PATH[6]: length=5 value=|/sbin|

There is a PATH on global scope shadowing the universal scope, but PATH is never set globally. Where on earth does this come from?

There is nothing in ~/.config/fish/conf.d/, no PATH touched in ~/.config/fish/functions/*
The ~/.config/fish/config.fish is empty. 
PATH is defined as universal variable. But there is no global definition at all. The global path comes from nowhere.

**Comment by krobelus** [comment]
The global PATH is here because when fish starts, it reads all environment variables and turns them into global variables.
(historical reasons.. maybe one day we can merge global and universal scopes).

If you want to use universal variables, you should use something like `set -U fish_user_paths ~/bin`.
This is a special variable that fish will prepend to PATH.

**Comment by MichaelJDrK** [comment]
Thanks for the explanation! 

Is this part of the documentation? I read all the parts about variable scopes, the PATH, startup files, but still didn't know it. 

Should this be added to the documentation about the PATH? Because this currently has the consequence, that universal changes to PATH won't work in many cases, which might be very confusing.

Additionally I'd suggest to add documentation how exactly `fish_user_paths` is prepended. At first I thought, that two variables are being considered for execution: `fish_user_paths` first, then `PATH`. Then I figured out, that `fish_user_paths` is actually prepended to the `PATH` variable, but on startup only. If you have one entry in `fish_user_paths`, you can do `set -e PATH[1]` and remove that (for the session), but the `fish_user_paths` itself will be unaffected.

**Comment by ridiculousfish** [comment]
Sure! Would you like to suggest some language or make a PR that that would have helped you? [Here's the tutorial source]9https://github.com/fish-shell/fish-shell/blob/master/doc_src/tutorial.rst). Users finding holes in docs is one of the ways they improve.
