### ISSUE TITLE
When redirecting output, the exit code doesn't reflect the redirections exit code

### ISSUE THREAD

**Issue by alx365** [fish-shell/fish-shell#7540]
Please tell us which fish version you are using by executing the following:
  ```
  3.1.12
  ```
Please tell us which operating system and terminal you are using. 
  ```
  Linux arch 5.9.12-arch1-1 #1 SMP PREEMPT Wed, 02 Dec 2020 16:14:56 +0000 x86_64 GNU/Linux
  ```
  My terminal is alacritty.

Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:

  Yes i have.. still happens

Tell us how to reproduce the problem. --> 

  When you redirect the output of a command, and the folder you're redirecting it to, is not found, fish exits the command with a 0 exit status. Unlike bash would do in that case.
  This should be fixed, as the thing the user wanted to wasn't sucessful.

**Comment by ridiculousfish** [comment]
Fixed as 36766ea3d765dacf2a1569bf8514215382656d1d, thanks for filing!
