### ISSUE TITLE
tab completion should fallback to files

### ISSUE THREAD

**Issue by blueForestIcarus** [fish-shell/fish-shell#7543]
Sometimes, if completions are incorrect or incomplete, (or if i'm trying to run a command that will fail), tab-completion on files just doesn't work because Fish thinks a file is not a proper argument.

ex)
mount -o loop ./my/images/filenam<tab>

Will not complete. I regularly have to type out my arguments first to avoid this issue.

It would be useful if fish would fallback to file tab completion when there are no command specific completions.
This could either be a different key-bind, or the highlighting could change to indicate that fish doesn't think you are typing a valid command.

fish --version = 3.1.2
uname -a = Linux aquila 5.9.12-arch1-1 #1 SMP PREEMPT Wed, 02 Dec 2020 16:14:56 +0000 x86_64 GNU/Linux
echo $TERM = xterm-kitty

**Comment by faho** [comment]
No, it should not.

We've been there, and it's awful - #112. 

If there is a problem in the completion script, it should be fixed in the completion script.

**Comment by faho** [comment]
Okay, I made it so `mount` completes files, and also completes the block devices in /dev *by default*.

This is because we basically can't tell what a mountable "thing" is - anything could potentially have a FUSE filesystem to make it mountable.

**Comment by blueForestIcarus** [comment]
There are many commands this has been a problem with. "gunzip -c", for example, fails when the file you are unzipping does not have a .gz extension

That's just another example from the past 5 minutes. I'm not complaining: Fish has better tab completion than anything else I know of, but covering 100% of valid args for all commonly used commands isn't something I'm holding my breath for. In the mean time, it'd be nice to be able to force fish to ignore the completions and complete the damn path name.

**Comment by krobelus** [comment]
I agree this can be frustrating. Keep in mind that the default is file completion so we don't have to cover everything, just the things we explicitly complete differently.

See also #7040 and #7547 which fixes this particular problem.

> Maybe there is a way I could configure this for myself? Like adding a keybind which initiates completions but somehow looks somewhere else (somewhere empty) for the rules?

You can temporarily disable completions for some command with a binding like
`bind \eg 'complete --erase (commandline -po)[1]'`
or persistently by creating `~/.config/fish/completions/the-command.fish`.

**Comment by blueForestIcarus** [comment]
yet another example:
unzip -l doesn't tab complete at all

**Comment by krobelus** [comment]
@blueForestIcarus that's fixed in the latest release by #7547

**Comment by krobelus** [comment]
@blueForestIcarus that's fixed in the latest release by #7547
