### ISSUE TITLE
ps completions including -F on platforms where it is not supported

### ISSUE THREAD

**Issue by alvinseville7cf** [fish-shell/fish-shell#7545]
Hello! Why there is -F option in fish tip but it doesn't works when it is provided?
<img width="1372" alt="Screen Shot 2020-12-12 at 8 06 50 PM" src="https://user-images.githubusercontent.com/42812113/101981051-c3673480-3cb5-11eb-973a-027826ed05d3.png">
<img width="688" alt="Screen Shot 2020-12-12 at 8 06 58 PM" src="https://user-images.githubusercontent.com/42812113/101981053-c530f800-3cb5-11eb-9252-1d5603190194.png">
My OS is mac OS Big Sur (11.0.1) and I use Fish 3.1.2. I tried:
```
sh -c 'env HOME=$(mktemp -d) fish'
```
but nothing changed after it.

manpath command prints the following output:
```
/usr/local/opt/gnu-sed/libexec/man:/usr/local/opt/grep/libexec/man:/usr/local/opt/findutils/libexec/man:/usr/local/opt/coreutils/libexec/man:/usr/local/share/man:/usr/share/man:/Library/Apple/usr/share/man:/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/share/man:/Library/Developer/CommandLineTools/usr/share/man
```

**Comment by zanchey** [comment]
Yeah, this probably needs guards for the GNU / BSD differences.

**Comment by alvinseville7cf** [comment]
Is there any workaround for now?

**Comment by zanchey** [comment]
The easiest thing to do is to avoid selecting in, but if you want to remove it from the list entirely you could do something like `cp $__fish_datadir/completions/ps.fish ~/.config/fish/completions/`, then edit `~/.config/fish/completions/ps.fish` to remove the line that starts with `complete -c ps -s F`

**Comment by mqudsi** [comment]
Most of the completions were actually incorrect (though not invalid to specify) for the BSD version of `ps`. I've split them out in e2273bacb25b1ed252dd57fc957ea44a4a054fa4
