### ISSUE TITLE
`commandline -f repaint` does not see error code from command prior to it.

### ISSUE THREAD

**Issue by dpacbach** [fish-shell/fish-shell#7546]
Hi,
I'm using fish version 3.0.2, and it seems that I"m facing an issue with the `commandline -f repaint` command.  I have a function bound to the `F5` key, which runs each time I hit `F5`.  At the end of that function, however, I need to issue a `commandline -f repaint` call in order for the command line to redraw when then function is finished.  That works fine, except that it loses the error code from the last command in the function, which ideally I'd like to show in my prompt (my prompt displays error code of last command).  I think that what is happening is that the `commandline -f repaint` command, when run as the last step in the function, is somehow resetting the error code to zero before repainting the command line.  Any advice? 
Thanks

**Comment by ridiculousfish** [comment]
fish 3.0.2 is quite old. Does this still happen with 3.1.2? If so, can you please provide a script or steps to reproduce?

**Comment by dpacbach** [comment]
Should be easy to reproduce, for example:

1. In `fish_user_key_bindings` function, put e.g.:
```fish
bind -k f5 my_f5_func
```

2. Then in `~/.config/fish/functions/my_f5_func.fish`:
```fish
function my_f5_func
  echo "inside my_f5_func"
  /usr/bin/false # a command that returns an error.
  commandline -f repaint
end
```

Then the desired behavior is that the error should be propagated out of the function and the repainted command line should reflect that error (assuming the `fish_prompt.fish` echos the `$status` as part of the prompt, as mine does).

Let me know if you need more info.  Unfortunately I do not have access to 3.1.2 at the moment to test.  I suspect that it will still be a problem in 3.1.2 because this issue has existed in fish for a long time, i.e., this is not a new regression.

**Comment by faho** [comment]
>this issue has existed in fish for a long time, i.e., this is not a new regression.

It's not a bug either - `commandline` simply returns a status on its own. This is how $status works, in general.

If you need to return the status of a specific command, you'll have to store it in a variable and then explicitly `return` it, like 

```fish
function my_f5_func
  echo "inside my_f5_func"
  /usr/bin/false # a command that returns an error.
  set -l oldstatus $status
  commandline -f repaint
  return $oldstatus
end
```

**Comment by dpacbach** [comment]
@faho Actually I mispoke, I don't need to return the status of the command outside that function; I just need the `commandline -f repaint` command to see the error so that it paints the command line appropriately.  The problem is that the `commandline -f repaint` command does not see the `$status` from the function before it.  The code that you have above will not work for me because the command line is repainted showing an error code of 0.

**Comment by dpacbach** [comment]
I realize now that I did not express my problem properly, so I have changed the title of this issue; I do not need the error code to be returned from the function, I just need the `commandline -f repaint` to see that error so that when it repaints the command line it will put the right value for `$status`, but currently it always seems to see a value of `0` for `$status`, regardless of the exit code of the command before it.

**Comment by krobelus** [comment]
I believe this is expected behavior.
The prompt's `$status` should not not be affected by commands that are run from keybindings.
Otherwise <kbd>Control</kbd>+<kbd>L</kbd> would always reset the `$status` to 0 (see `bind \cl`).

During execution of a key binding, the status of the last command is visible
 Consider`bind \eg 'false; echo $status; commandline -f repaint'`
however that status is not used when repainting the commandline - probably because `commandline -f repaint` does not directly repaint but only schedule a repaint (my guess, didn't check). After the keybinding commands are finished, the old status is restored before repainting.

**Comment by dpacbach** [comment]
I found a workaround that works to achieve the behavior that I want:

1. Have the key-bounded function save the status in a global variable called `status_cache`:
```fish
# ~/.config/fish/functions/fish_user_key_bindings.fish
bind -k f5 my_f5_func

# ~/.config/fish/functions/my_f5_func.fish
function my_f5_func
  ...
  set -g status_cache $status
  commandline -f repaint
end
```

2. Setup a post-exec hook:
```fish
# ~/.config/fish/functions/fish_prompt.fish
function postexec_hook --on-event fish_postexec
  if string length -q $argv
    set --erase status_cache
  end
end
```

3. In the `fish_prompt` function, add this to the top:
```fish
# ~/.config/fish/functions/fish_prompt.fish
function fish_prompt
  # Save the status of the last command before we do anything else since
  # otherwise it'll be lost.
  set -l status_to_display $status
  if string length -q $status_cache
    set status_to_display $status_cache
  end
  ...
  ... proceed to draw prompt including $status_to_display.
  ...
end
```

This then causes the error code from the key-bound function to appear to propagate out of the function as with normal commands and the error will linger in the command prompt until another command is run, also as with normal commands.
