### ISSUE TITLE
Tab completions of paths not working after the `python` command when using `~`

### ISSUE THREAD

**Issue by remisalmon** [fish-shell/fish-shell#7551]
Fish version: 3.1.2
OS: Linux 5.9.13 (Fedora 33)
Terminal: GNOME Terminal
Reproduced with `sh -c 'env HOME=$(mktemp -d) fish'`: yes

Tab completions of paths are not working after the `python` command when using `~` in the path.

Steps to reproduce:
1. `cd ~`
2. `python ~/Do` -> hit tab -> nothing
3. `python ./Do` -> hit tab -> shows `./Documents/  ./Downloads/`

Any other command than `python` seem to work in both 2. and 3. cases.

**Comment by krobelus** [comment]
Fixed by 93cb0e2abba4e5c2fa2153a18f60f5e196d5efa6 - you can download [share/functions/__fish_complete_suffix.fish](../blob/master/share/functions/__fish_complete_suffix.fish) and place it in `~/.config/fish/functions` as a temporary workaround.

**Comment by remisalmon** [comment]
`__fish_complete_suffix.fish` did fix the issue with python but I am now running into the same issue with:

`pip install -t ~/Do` -> hit tab -> nothing

**Comment by krobelus** [comment]
Yeah, pip does not expand shell variables or `~`.

```
PIP_AUTO_COMPLETE=1 COMP_CWORD=3 COMP_WORDS='pip install -t ./Do' pip    # Works
PIP_AUTO_COMPLETE=1 COMP_CWORD=3 COMP_WORDS='pip install -t ~/Do' pip    # Doesn't work
```

We could fix that by using `eval` to expand the `~`, but then we also need to [unexpand it](https://github.com/fish-shell/fish-shell/issues/5811#issuecomment-487150390) so the completion still applies.

Bash does not expand it either, but they fall back on file completion when custom completion fails.
