### ISSUE TITLE
Feature: Allow to customize fish history file path

### ISSUE THREAD

**Issue by jansepke** [fish-shell/fish-shell#7553]
It would if the history file path would be customizable. My plan is to built a throw away dev VM with a fish shell. But I would like to not start with a empty history all the time because a filled shell history increases productivity ;-) So my idea is to mount the fish history file into my VM so everything is in sync. Would it be possible to add a config option for this? I already tried symlinks but that gets overridden by fish automatically.

❯ fish --version
fish, version 3.1.2

**Comment by faho** [comment]
Already available - set $fish_history to an identifier for the "session", or empty to not keep history at all - see [the documentation on special variables](https://fishshell.com/docs/current/index.html#special-variables).

I can't say I agree with your idea, since a shell history also means you can search for commands you've already used, but you do you.

**Comment by faho** [comment]
Fish's history path is $XDG_DATA_HOME/fish/"$fish_history"_history.

Set those two variables however you want.

**Comment by jansepke** [comment]
As far as I know $XDG_DATA_HOME is also used by other applications that I maybe don't want to influence (e.g. fonts, nano, ...) and setting only $fish_history is not enough because I want to configure the path and not only the file name. Would be great if I could configure it only for fish shell.

**Comment by faho** [comment]
In that case, symlink the fish/ *directory* in $XDG_DATA_HOME.

I don't think we have interest in making the full location customizable, just like we don't want config.fish's location to be customizable beyond $XDG_CONFIG_HOME.

The issue with symlinking the file is the same as with fish_variables - we want these things to be usable across shells, so we need to have atomicity guarantees, anything beyond moving a file into place is quite complicated (locking doesn't work etc), so I'll refer you to #7466 for that.

**Comment by jansepke** [comment]
Ok, that does works as long as the target directory is not a shared folder between the windows host and the linux VM. But that is now a very special case so I will do a workaround with a cron job or similar.
