### ISSUE TITLE
test -d fails but cd succeeds

### ISSUE THREAD

**Issue by ajeetdsouza** [fish-shell/fish-shell#7556]
Consider the following setup:

```fish
mkdir -p /tmp/chdir-test/symbolic-links/
mkdir -p /tmp/chdir-test/actual-directories/folder1
mkdir -p /tmp/chdir-test/actual-directories/folder2
ln -s /tmp/chdir-test/actual-directories/folder1 /tmp/chdir-test/symbolic-links
cd /tmp/chdir-test/symbolic-links/folder1
```

Now, `test -d ../actual_folder` fails, but `cd ../actual_folder` succeeds.

Notably, tab-completion works for `cd ../actual_folder` (although not for any other command), but syntax highlighting still colors the argument red (as if the directory does not exist).

If this is not a bug, what would be the best way to test if `cd` is possible without actually changing directories? In bash or zsh, I would invoke a subshell for this, but fish doesn't support subshells (see https://github.com/fish-shell/fish-shell/issues/1439).

**Comment by krobelus** [comment]
> Now, test -d ../actual_folder fails, but cd ../actual_folder succeeds.

But you didnt't create that folder? If I add `mkdir ../actual_folder` I get the reverse effect: `test -d ../actual_folder` works, but `cd ../actual_folder` doesn't (and doesn't complete).

This is expected because fish keeps a virtual working directory, that doesn't resolve symlinks. However, only builtins like `cd` and `pwd` use that, all other commands use the resolved directory. You can test the difference like this:

```
$ realpath --logical /tmp/chdir-test/symbolic-links/folder1/..
/tmp/chdir-test/symbolic-links                 # used by cd ..
$ realpath --physical /tmp/chdir-test/symbolic-links/folder1/..
/tmp/chdir-test/actual-directories             # used by test -d ..
```

So if `test -d` works but `cd` doesn't, you can use `cd (realpath ..)`.

**Comment by ajeetdsouza** [comment]
@krobelus I do understand the issue with virtual directories - in fact, this behaviour is consistent across shells. However, to check if a path is cd-able in other shell, all I need to do is invoke `cd` in a subshell and see if it succeeds. Since fish does not have subshells, this becomes tricky.

I've found a workaround for now, but I think subshell support would definitely be a nice-to-have in fish.

**Comment by krobelus** [comment]
Yeah, you can either use `sh -c 'cd ../folder2'` or `cd ../folder2 && cd -`.
Or the creative variant `CDPATH= complete -C 'cd ../folder2'` though I agree that subshells are more elegant.

**Comment by ridiculousfish** [comment]
On Mac and BSD, one can use `command cd` (defaults to `/usr/bin/cd`) which is for exactly this purpose. I don't know if there's a `cd` executable on Linux.

**Comment by ajeetdsouza** [comment]
`cd ../folder2 && cd -` would not work as expected if the current directory has been deleted by another process. The `complete` idea is really good, but somehow, while testing this idea, completion broke more than once. I haven't found a reliable way to reproduce it, I'll create a separate issue if I do. `command cd` would have been perfect, but it's not available on Linux systems unfortunately.

I think the closest thing I can do is use `sh` as a kind of subshell. Thanks for all the help!
