### ISSUE TITLE
-bash: /usr/share/Modules/init/fish: line 6: `for _mlv in (string split ' ' $MODULES_RUN_QUARANTINE)'

### ISSUE THREAD

**Issue by vorburger** [fish-shell/fish-shell#7560]
On Fedora 32, using `tmux` (not sure how much that matters?):

I'm currently initially using Bash as my shell.

Pressing <Alt-T> my custom keyboard shortcut for opening a new tab in TMUX:

```
$ fish --version
fish, version 3.1.2

$ chsh -l
/bin/bash
/usr/bin/sh
/usr/bin/bash
/usr/bin/tmux
/bin/tmux
/bin/dash
/usr/bin/fish
/bin/fish

$ chsh /bin/fish
Changing shell for vorburger.
Password:
Shell changed.
```

Pressing <Alt-T> my custom keyboard shortcut for opening a new tab in TMUX again, but now:

```
-bash: set: -g: invalid option
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
-bash: /usr/share/Modules/init/fish: line 6: syntax error near unexpected token `('
-bash: /usr/share/Modules/init/fish: line 6: `for _mlv in (string split ' ' $MODULES_RUN_QUARANTINE)'

$ echo $SHELL
/bin/bash
```

I figured (from having found https://bugzilla.redhat.com/show_bug.cgi?id=1707909), that this is because SOMETHING is, apparently, running `/usr/share/Modules/init/fish` still under `bash` instead of `fish`? But I'm clear what that that something.. what's going wrong here? Is this a packaging problem in Fedora, only? Could some customization I've applied been causing this?

**Comment by faho** [comment]
I have no idea what /usr/share/Modules/init/fish *is*. It sure isn't one of fish's things.

If bash is attempting to read a fish thing, then that's because something told it to, and you need to figure out what that is.

This looks like a bug *somewhere*, probably in the keybase package, but to be honest we don't have nearly enough to go on.

**Comment by faho** [comment]
Ah, okay, it seems /usr/share/Modules is provided by https://github.com/cea-hpc/modules. I suggest you direct your issue there.

**Comment by vorburger** [comment]
Understood. It's not keybase specific (I'm not using keybase), just someone using that had a similar problem.

From what little I've gathered here, looks like this has something to do with https://modules.readthedocs.io/en/latest/index.html - from https://github.com/cea-hpc/modules/issues/374, whatever that is good for. It's what's creating `/usr/share/Modules/init/fish`, and my machine has it installed (presumably as a dependency of... something; I'm discovering its existing in the universe through this).

https://github.com/cea-hpc/modules/issues/374 opened to pursed that there, closing this.
