### ISSUE TITLE
Syntax for variable fallback value

### ISSUE THREAD

**Issue by Flygrounder** [fish-shell/fish-shell#7561]
Bash has a nice syntax that allows you to specify a fallback value like `echo ${a:-1}`. 

Equivalent in fish would be 
```fish
if set -q a
    echo $a
else
    echo 1
end
```

Can syntax like this be added in fish?

**Comment by faho** [comment]
Thank you, but no.

Fish's syntax isn't supposed to be as terse as possible, and `${thing:-thing}` is fairly unreadable (plus there's a multitude of variants here, including `:+`, `:=` and `:?`.

Use something like `echo (set -q a && echo $a || echo 1)`.
