### ISSUE TITLE
macOS Big Sur: slow command autocompletion

### ISSUE THREAD

**Issue by nguyenthanhvuh** [fish-shell/fish-shell#7563]
fish version 3.1.2 on macOS Big Sur seems to have this exact problem described in https://github.com/fish-shell/fish-shell/issues/6270.  The suggested fix in https://github.com/fish-shell/fish-shell/issues/6270#issuecomment-548515306 also seems to work.  

Version 3.1.2 has a fix but only for macOS 10.15 https://github.com/fish-shell/fish-shell/blob/3.1.2/share/functions/__fish_complete_man.fish.  The current/main branch has a more generic fix https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_describe_command.fish.   

It would be great if the next release can come out a bit faster to resolve this issue.

**Comment by faho** [comment]
As you've mentioned yourself, it's already fixed.

**Comment by faho** [comment]
Duplicate of #7511
