### ISSUE TITLE
Turn off Fish greeting with a command line option

### ISSUE THREAD

**Issue by Flurrywinde** [fish-shell/fish-shell#7570]
Fish version: 3.1.2
Operating system: Arch Linux 5.4.84-1-lts #1 SMP x86_64 GNU/Linux
 $TERM: xterm-kitty

I currently have a fish_greeting function, and it runs each time a new interactive shell gets spawned. This is correct behavior, but sometimes I'd like to suppress the greeting for a particular situation, like if I'm using tmux. I have a layout that splits the screen into many little windows, and currently, I get the fish greeting in all of them. That's a little too much. LOL. In a case like this, I'd like just the command line prompt to appear, no greeting.

My thought was that it'd be nice if there was a command line option to suppress the greeting, or... is there some other way to suppress the greeting?

I tried `fish_greeting="" fish`, but it seems the greeting function takes precedence.

**Comment by faho** [comment]
If you have your own custom function, you'll have to suppress it yourself - 

```fish
function fish_greeting
    if set -q fish_greeting
        test -n "$fish_greeting"
        and echo $fish_greeting
        return
    end
    # do the other stuff if $fish_greeting isn't set
end
```

Note that in 3.1.2 $fish_greeting is typically a universal variable, so you might only want to suppress if it's empty and do the normal greeting otherwise. (in the next release it defaults to a global variable)

**Comment by Flurrywinde** [comment]
It works. Thanks! (Sorry for the duplicate post. I don't know how that happened.)
