### ISSUE TITLE
realpath -s doesn't resolve to absolute path

### ISSUE THREAD

**Issue by kidonng** [fish-shell/fish-shell#7574]
```
❯ fish --version
fish, version 3.1.2-1798-g4dae10691

❯ echo $version
3.1.2-1798-g4dae10691
```

Glad to see a `-s` (`--no-symlinks`) option is added to `realpath` in 568f9031aaeb688c3b157b0fb05090da9962a0fa. But there are currently two issues with `realpath`:

- [`share/functions/realpath.fish`](https://github.com/fish-shell/fish-shell/blob/4dae106911193056515ccba091ddb8d26b1793c2/share/functions/realpath.fish) isn't updated along with the builtin, so one can't just use `realpath -s`, they have to type `builtin realpath -s` instead.
- While the above is a minor issue, the main problem this issue is about is `realpath -s` doesn't resolve to absolute path at all.

```
❯ pwd
/Users/kid

❯ ls -l .cache
lrwxr-xr-x  1 kid  staff  14 Dec  5 11:29 .cache -> Library/Caches

❯ builtin realpath -s ~/.cache
/Users/kid/.cache

❯ builtin realpath -s .cache
.cache
```

But I expect `.cache` to be resolved to the absolute path `/Users/kid/.cache`.

I noticed the `-s` flag calls `normalize_path` internally, but the function seems to only deal with `.` and `..`, and it doesn't resolve to a absolute path. So is `realpath -s`'s behavior intended? Or is this just a implementation flaw?

**Comment by krobelus** [comment]
Good catch, this is used in fish_add_path.

> share/functions/realpath.fish isn't updated along with the builtin

Probably it's just meant as fallback for now.

**Comment by zanchey** [comment]
> share/functions/realpath.fish isn't updated along with the builtin

It looks there to me:
https://github.com/fish-shell/fish-shell/blob/master/share/functions/realpath.fish#L25

**Comment by kidonng** [comment]
@zanchey See https://github.com/fish-shell/fish-shell/blob/master/share/functions/realpath.fish#L36, it will refuse any options.

**Comment by krobelus** [comment]
Thanks for the explanation, d6dd532 should fix that.
