### ISSUE TITLE
Remove from PATH persistently

### ISSUE THREAD

**Issue by Christilut** [fish-shell/fish-shell#7576]
`fish, version 3.1.2`

How do you remove an entry from the `PATH` variable persistently?

I'm doing `set -eU PATH[1]` but then I get this message: `set: Universal variable 'PATH' is shadowed by the global variable of the same name.`

**Comment by faho** [comment]
You don't.

$PATH is a global variable as it is inherited from the parent process. Making it universal doesn't work as global variables take precedence. 

You're going to have to use

```fish 
if set -l index (contains -i /the/path $PATH) 
    set -e PATH[$index] 
end
```

(unless you added it via fish_user_paths, in which case you can just remove it from *that*)

**Comment by Christilut** [comment]
Thanks!
