### ISSUE TITLE
zombies leak when disowning a background process in fish_prompt

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7581]
```fish
function fish_prompt
    sleep 1 &
    disown (jobs --last --pid)
    echo $PWD
end
```

The number of `sleep <defunct>` processes grows with every prompt render. `fish 3.1.2`

**Comment by faho** [comment]
Should be fixed by #7189, and I can't reproduce it in master (but can in 3.1.2)
