### ISSUE TITLE
First variable set is still set after removing it from config.fish

### ISSUE THREAD

**Issue by emigr2k1** [fish-shell/fish-shell#7583]
If you have the following two commands in `config.fish` right after starting up the computer:

```
set -gx FOO Bar
set -gx HELLO Bye
```

then the following happens in a new shell session:

```
$ echo $FOO
Bar
$ echo $HELLO
Bye
```

Right so far but if you remove the variable declarations from `config.fish` and open a new shell session, the following happens:

```
$ echo $FOO
Bar
$ echo $HELLO

```

Only $HELLO was unset.

If you have 10 variable declarations in the same form as above and then you remove them all, only the first one will remain set. I think it has to be at the top of the file, but I'm not sure.

**Info:**

  fish --version: fish, version 3.1.2
  echo $version: 3.1.2

`uname -a`: `Linux emigr2k1-pc 5.9.11-3-MANJARO #1 SMP PREEMPT Sat Nov 28 09:08:57 UTC 2020 x86_64 GNU/Linux`

`echo $TERM`: `xterm-256color`

**Reproduce:**

Add `set -gx FOO Bar` at the top of `config.fish`.
Restart PC
Create a new session and do `echo $FOO`. Output should be `Bar`
Remove `set -gx FOO Bar` from `config.fish`
Create a new session and do `echo $FOO`. Output is still `Bar` but it shouldn't because `set -gx FOO bar` was removed.
Add `set -gx FOO Hey` at the top of `config.fish`
Create a new session and do `echo $FOO`. Output should be `Hey`
Remove `set -gx FOO Hey` from `config.fish`
Create a new session and do `echo $FOO`. Output will be `Bar` again.

This only happens if the variable is defined at the top of the file on startup. It won't happen with other variables set after that one.

**Comment by emigr2k1** [comment]
This is what I mean: https://streamable.com/n2dpjw

Even when I delete the variable declaration, `$FOO` is stil `Bar` while `$HELLO` does get unset.

I don't set `$FOO` anywhere else. And it only happens to the first variable declared after I turn my pc on.

If I add `set -gx ONE baz` at the top of my `config.fish` and then restart my pc, the same thing will happen to `$ONE`. It will keep its initial value even when I remove the declaration until I restart my pc. Other variables will be unset when I remove their declaration.

Sorry if I'm not explaining correctly.

**Comment by krobelus** [comment]
Maybe you are setting `$FOO` somewhere else? It could be a universal variable.
What is the output of `set -S FOO` after you delete it from the config?

Does it behave differently when you use another name instead of FOO?
What if you use `set -g` instead of `set -gx`?

**Comment by emigr2k1** [comment]
@krobelus, I'm not setting $FOO anywhere else. It will happen with whatever variable is set at the top of `config.fish` after I turn my pc on.

Yesterday I removed a variable I had in my `config.fish` but its value kept coming back in new shell sessions. I thought that I had set the variable somewhere else so I grepped my whole filesystem after looking in the standard locations but didn't find anything.

I'll try different options to see if it's a problem with fish or it's specific to my setup.

**Comment by faho** [comment]
@emigr2k1 You really want to look at `set -S FOO`.

The reason for that is that fish also provides "universal" variables that it persists on disk, so if you defined a universal variable $FOO this would all behave as expected.

**Comment by emigr2k1** [comment]
I was wrong.

I previously thought that only the first variable remained set but that was not true. It just happened that the second variable was being shadowed in my setup.

Now I see that every variable set at login remains set even after removing them from `config.fish`.

I think a process reads the variables at login and then, after I remove the declaration, the child processes inherit the variables that were set at login. It could be my desktop manager or something, I don't know. But they're somehow being inherited.

I'll close this because it's not related to fish.

**Comment by krobelus** [comment]
Yeah if Konsole inherited the variables then it will pass them on to new shells.
