### ISSUE TITLE
convert (...)'s output to string

### ISSUE THREAD

**Issue by tkkcc** [fish-shell/fish-shell#7587]
fish, version 3.1.2

Can `(...)`'s output as string typed from keyboard, not as arguments.

```sh
# bash
echo $(echo 1 ' 2')
1 2
# fish
echo (echo 1 ' 2')
1  2
```
In real world, I want to run this command in one line.
```sh
g++ -O3 -Wall -shared -std=c++11 -fPIC $(python -m pybind11 --includes) example.cpp -o example$(python-config --extension-suffix)
```
reference: 
https://fishshell.com/docs/current/tutorial.html#command-substitutions
https://pybind11.readthedocs.io/en/latest/basics.html#compiling-the-test-cases

**Comment by krobelus** [comment]
See https://fishshell.com/docs/current/faq.html#my-command-pkg-config-gives-its-output-as-a-single-long-string
Commandline input is split on spaces, but output from command substitutions is split on newlines. You need to use `string split` on the output.

```
$ count (echo '1 2')
1
$ count (echo '1 2' | string split ' ')
2
```

**Comment by tkkcc** [comment]
Thanks!
