### ISSUE TITLE
fish_history negates private mode

### ISSUE THREAD

**Issue by etcusrvar** [fish-shell/fish-shell#7590]
fish 3.1.2
Linux 5.9.16 x86_64

According to the [docs](https://fishshell.com/docs/current/index.html#private-mode) - "In private mode, old history is not available and any interactive commands you execute will not be appended to the global history file"

But when launching fish with both fish_history set and in private mode, private mode is ignored/overridden/negated.

```
$ d=$(mktemp -d)
$ cd $d
$ sh -c "env HOME=$d fish"
Welcome to fish, ...
x@x ~> foo
fish: Unknown command: foo
x@x ~ [127]> bar
fish: Unknown command: bar
x@x ~ [127]> history
bar
foo
x@x ~> exit

$ sh -c "env HOME=$d fish --private"
Welcome to fish, ...
fish is running in private mode, history will not be persisted.
x@x ~> history
x@x ~> exit

$ sh -c "env HOME=$d fish_history=default fish --private"
Welcome to fish, ...
fish is running in private mode, history will not be persisted.
x@x ~> history
history
bar
foo
x@x ~> baz
fish: Unknown command: baz
x@x ~ [127]> history
baz
history
bar
foo
x@x ~> exit

$ sh -c "env HOME=$d fish"
Welcome to fish, ...
x@x ~> history
baz
history
bar
foo
```

**Comment by ridiculousfish** [comment]
With 118f710e996e0ddadaff9906cc8b76aabdd6a115, `fish_private_mode` and `fish_history` are distinct. If `fish_private_mode` is set, commands you run are stored in memory, and can be recalled via up-arrow, but are not written to disk. It can be dynamically toggled on and off by setting the `fish_private_mode` variable.
