### ISSUE TITLE
Update pcre2

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#7599]
It's that time of the year again, our bundled pcre2 is at 10.35, the latest release is 10.36

This requires redoing 73ecf1576b4a049a296952a16975b07965b75ad7 (according to the instructions in b418e36f2) and possibly 8f50e5721df662884e908000f4e4a29ee6816f53 and 783a895b1163149dc98d70c66f03748413998805

Apparently we can't drop it because of macOS's "codesigning" - see 952d9eecf79b6bc78738fc3a67043dc3a18ee077 (unless homebrew et al switch to codesigning?).

See also #5353, #2985.

**Comment by zanchey** [comment]
see https://github.com/fish-shell/fish-shell/wiki/PCREctomy

**Comment by faho** [comment]
So I've followed a simplified procedure because fiddling with the files is a bit involved for little gain.

Roughly, here's what I did:

```
cd pcre2
rm -r ltmain.sh Makefile* configure m4 Run* *.bat perltest.sh testdata doc
cd pcre2/src/
rm -r -r sljit/ pcre2_jit_test.c pcre2grep.c pcre2test.c

# Add "QUIET" to the Find_Package lines in CMakelists.txt
```

The remaining files are either < 50K each (and I'm uncomfortable removing things like AUTHORS) or need to be edited instead of removed.

This yields a 2.7MB directory instead of a 2.1MB one, which should be an acceptable trade-off. If anyone wants to muck around for a few kilobytes, be my guest.
