### ISSUE TITLE
Allow updating fish_prompt after command (transient prompt)

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7602]
I'm working on trying to replicate powerlevel10k's awesome [transient prompt feature](https://github.com/romkatv/powerlevel10k/#transient-prompt).

Here's my first stab:

```fish
function fish_prompt
    if set -q foo
        echo $foo
        set -e foo
    else
        echo $PWD
    end
end

function fish_preexec --on-event fish_preexec
    set -g foo bar
    commandline -f repaint
end
```

The logic is as follow: 
1. `foo` starts out undefined, so `fish_prompt` echoes `$PWD`
2. Then you hit enter on a command, causing `fish_preexec` to run, which sets foo and reruns the prompt
3. The prompt changes to `$foo` and erases it
4. The command starts running

Thus the currently prompt will always be `$PWD` and all previous ones will be `$foo`

It doesnt work. Is there a way of doing what I want? If not, can it be added?

**Comment by ridiculousfish** [comment]
I'll take a look and see if it can be done.

**Comment by krobelus** [comment]
I think you can use a bind function instead of a preexec hook, see https://github.com/fish-shell/fish-shell/pull/6427#issuecomment-565788121.

**Comment by IlanCosman** [comment]
That example works! Thanks @krobelus 😄 I feel a little sketched-out by rebinding enter, but perhaps that's illogical. I'll see if I can make that work for my project. Should I close this issue?

**Comment by krobelus** [comment]
We could figure out why a preexec hook doesn't work.
> I feel a little sketched-out by rebinding enter,

I think that's a legitimate concern, because maybe you don't want the transient behavior when using <kbd>Enter</kbd> to go the next line.

**Comment by subhav** [comment]
Not holding my hopes too high for this, but is there any way of knowing whether running `commandline -f execute` would insert a new line instead of trying to run the command?

**Comment by faho** [comment]
There is not.

**Comment by JesseFarebro** [comment]
I did some digging on `fish_preexec` and why `commandline` doesn't work as expected. It looks like there are a couple of obstacles. I don't fully understand the nuances of these problems but I'd love to get some comments on how this can be properly implemented.

1. `commandline_builtin` scheduling. From what I understand fish schedules repaint commands sent by `commandline -f` and it seems that the repaint command gets delayed until after the command is executed. Specifically, I'm talking about,

https://github.com/fish-shell/fish-shell/blob/0631bc509b6ba18657c38f707c222687989eaf7e/src/builtin_commandline.cpp#L316-L319

This seems easy enough to fix, you could check if we came from a preexec hook and schedule repaint for immediate execution.

2. By making the above change you're able to get the preexec hook to run before the command output but it will change the prompt of the next line which just gets overwritten by the command output. This stems from the fact that the preexec hook gets called after `readline()` which inserts the newline:

https://github.com/fish-shell/fish-shell/blob/0631bc509b6ba18657c38f707c222687989eaf7e/src/reader.cpp#L4018-L4022

----

Ultimately, I was able to implement a "transient" prompt by creating a new event that schedules repaint events for immediate execution and fires the event at the end of `readline()` before a newline is inserted. Fish already repaints the prompt in this exact same location, i.e.,

https://github.com/fish-shell/fish-shell/blob/0631bc509b6ba18657c38f707c222687989eaf7e/src/reader.cpp#L4008-L4011

I'm not sure if this solution is a viable path forward? Perhaps this new event could be called something like `fish_prompt_preexec`? It seems likely that moving `fish_preexec` into `readline()` will almost certainly break some current use cases? If someone wants to give me some guidance on how to proceed I have no problem doing the work.
