### ISSUE TITLE
Using Ctrl+D bound to exit breaks arrow key navigation

### ISSUE THREAD

**Issue by etcusrvar** [fish-shell/fish-shell#7604]
fish, version 3.1.2-1856-g4116aaeb5 (current latest on master branch)
Linux 5.10.4 x86_64

This is on the master branch-- this does not occur on current release, fish 3.1.2.

Follow the example at https://fishshell.com/docs/current/cmds/bind.html#examples for binding Ctrl+D--
```
# set up and launch subshell
...> set d (mktemp -d)
...> mkdir -p $d/.config/fish/functions
...> echo bind \\cd "'exit'" > $d/.config/fish/functions/fish_user_key_bindings.fish
...> sh -c "env HOME=$d fish"

# in new subshell
...> foo
fish: Unknown command: foo
...> f<Ctrl+D>
```

At this point, up and down arrows don't work, along with many other keys-- Ctrl-C, Ctrl-D, Enter, ... 

Tried on 5 different terminals, all with the same effect:
TERM=xterm-256color konsole
TERM=xterm-256color terminator
TERM=rxvt-unicode-256color urxvt
TERM=xterm-256color xterm
TERM=xterm-kitty kitty

**Comment by etcusrvar** [comment]
I narrowed it down to [this commit](https://github.com/fish-shell/fish-shell/commit/b0182183d42b44dd007a63a7c4e8a0e9e9a0e24c).

```
> git reset --hard a83dbec07
> make
FISH_BUILD_VERSION=3.1.2-1218-ga83dbec07
```
1218 doesn't have the issue.

```
> git reset --hard b0182183d
> make
FISH_BUILD_VERSION=3.1.2-1219-gb0182183d
```
1219 does have the issue.

**Comment by faho** [comment]
What's happening here is that you've *rebound* ctrl-d to just exit (normally it's delete-or-exit).

You have something in your commandline, and pressing ctrl-d normally here would delete a character instead, but since you bound it to *just* exit it's already marked the shell to exit.

So that arrows etc don't work is immaterial, the shell is already done, it just doesn't act on it soon enough, and the only thing it *should* be doing is to exit.

**Comment by faho** [comment]
Ahahahaha, there's actually no bind function called "exit", so it executes the actual builtin.

The simplest fix here is to just add an `exit` bind function.

(cc @ridiculousfish)

**Comment by etcusrvar** [comment]
I should have focused on the "doesn't exit immediately" aspect instead of the arrow keys. Updated title. And verified fixed.
