### ISSUE TITLE
[Suggestion] Anywhere/"global" abbreviations (like zsh)

### ISSUE THREAD

**Issue by MithicSpirit** [fish-shell/fish-shell#7607]
+ Version: `3.1.2-1862-gc1ef9676c`
+ OS: Archlinux (on linux 5.10 zen kernel)
+ Terminal: `rxvt-unicode-256color`

One feature I miss from zsh are "global aliases" (with `alias -g WORD=EXPR`), which will expand the `WORD` into `EXPR` wherever it is in the prompt, not just the beginning. I have gotten very used to having `G` abbreviated to `| grep` so that I can easily pipe the output of something into grep, and I am disappointed that this is not an option in fish. This would also be interesting in fish to allow for an easier way to port `&&` and `||` from POSIX (instead of using suboptimal keyboard shortcuts).

Obs.: In fish, this should obviously be an abbreviation instead of an alias, and it shouldn't be called "global" as that already means something else for abbreviations.

**Comment by faho** [comment]
Duplo of #5003
