### ISSUE TITLE
Feature Request: path completion for 'docker cp'

### ISSUE THREAD

**Issue by arkanovicz** [fish-shell/fish-shell#7608]
It would be great to have path completion on 'docker cp' commands for paths inside containers. Maybe it require a running container to issue `ls` commands, but depending how it is implemented, not necessarily...

It needs some thoughts about feasibility, anyhow.

**Comment by faho** [comment]
The docker completions are [maintained upstream](https://github.com/docker/cli/tree/master/contrib/completion/fish), please direct your feature requests there
