### ISSUE TITLE
How to expand pager with Tab?

### ISSUE THREAD

**Issue by demxk** [fish-shell/fish-shell#7612]
Is it possible to fully expand pager when there are more than 4 results available? For some reason Shift+tab accomplishes this but not Tab which doesn't make sense to me. Basically i want to increase number of entries so i don't have to navigate through list in order to get remaining results

**Comment by krobelus** [comment]
Pressing Tab a second time will expand the completions to fit the screen. You can also press Control+S which will put you in the search mode (just like Shift+Tab).

**Comment by demxk** [comment]
@krobelus oh yea sorry, i've just looked - tab was binded to autoclose_pair which broke expansion of pager for mer. without it it works as shift-tab, Thank you
