### ISSUE TITLE
Configuration not evaluated when invoking fish with -c

### ISSUE THREAD

**Issue by eaigner** [fish-shell/fish-shell#7620]
I tried to evaluate `env` like this

    env -i /usr/local/bin/fish -l -i -c env

The `env -i` prefix is required for this test to prevent inheriting my local environment.

This should output the environment of a fresh `fish` interactive login shell, however, it doesn't seem `fish` evaluates any configuration at all.

Any user `PATH`s configured in `config.fish` or `fish_variables` do not show up in the `PATH=` line of the output.

~~~
System:

fish, version 3.1.2
macOS Big Sur 11.1 (20C69)
~~~

**Comment by faho** [comment]
Fish *always* reads config.fish, even in non-interactive and non-login shells.

Your problem is most likely that `env` *also* erases $HOME, so try

```fish
env -i HOME=$HOME /usr/local/bin/fish -l -i -c env
```

**Comment by eaigner** [comment]
You sir, are correct!

**Comment by faho** [comment]
On second look, we already try to figure out $HOME and $USER, but we do it a bit too late - after determining the config path.

Simply doing that later means this can be worked around - not that I recommend starting fish with an unset $HOME.
