### ISSUE TITLE
Is it possible to port a BASH script to a FISH scrip automatically with a converter?

### ISSUE THREAD

**Issue by jessehui** [fish-shell/fish-shell#7622]
The background is that we would like to execute script file in a constrained environment (i.e. OS with limitations). And we can't have Bash fully functional. But so far, FISH works fine. Since many projects use Bash script, we want Thus, we are thinking of a tool to convert bash script to fish script.

As far as I know, there are some differences between the syntax of these two shells. And there are already tools to do some of the conversion, e.g. bass. But for complicated syntax like condition, loop or others, I am not sure if this is possible.

And my question is whether a BASH syntax can always be converted to a corresponding FISH syntax?  Are these differences strictly mapped? 

Thank you!

**Comment by faho** [comment]
It is not, and writing a converter is a *big* task that we're not going to do - see e.g. #1420, #522

If somebody else ever does, that answer changes of course.

**Comment by jessehui** [comment]
@faho I didn't mean to ask for you to do this. I just want to know if there is a mapping relationship and if it is possible.

Thank you for the references. I think it is more complicated than I imagined before.

**Comment by Neved4** [comment]
If anyone else stumbles upon this there's https://github.com/bouk/babelfish

@jessehui
