### ISSUE TITLE
Not showing git branch in prompt

### ISSUE THREAD

**Issue by SummitPatel** [fish-shell/fish-shell#7625]
So for some reason, the fish shell won't display my current git branch occasionally. I'm not completely sure what's causing it, but one way I've been able to reproduce it is to create a new branch off of an existing branch I pulled from my repo. Existing branches from the repo seem to display properly, but ones I've created locally do not as far as I can tell.

Existing branch that displays path correctly:
<img width="568" alt="Screen Shot 2021-01-12 at 12 13 00 PM" src="https://user-images.githubusercontent.com/1831829/104348456-c0877b80-54cf-11eb-8d52-146d228c86ab.png">

Newly created branch that does not:
<img width="568" alt="Screen Shot 2021-01-12 at 12 16 24 PM" src="https://user-images.githubusercontent.com/1831829/104348687-047a8080-54d0-11eb-82c7-35d51e3f4206.png">

I recently did a factory reset on my machine due to an unrelated issue, so this is a brand new set up and essentially iTerm2 + fish shell out of the box without any customization. Oddly enough, this worked just fine before I did the factory reset.

fish, version 3.1.2

Darwin Zenith 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64

xterm-256color (iTerm2)

**Comment by faho** [comment]
Which prompt is this? The default, or any other?

What are your git prompt settings? `set | grep fish_git` should show them.

The branch name also seems to be super long. Do you also have issues with shorter branch names?

Do you use a git alias or wrapper (something like `hub`)?

**Comment by krobelus** [comment]
Fish 3.1.2. truncates long prompts to just `> `.

a2ae2d6c36147009bc565ca7ec8fc20340ac48b9 changes this to show part of the prompt plus an ellipsis (`…`)

**Comment by SummitPatel** [comment]
Wow I feel so dumb. It's exactly that, the branch name is just so long it gets truncated. I'll go ahead and close this, thank you for the speedy responses.
