### ISSUE TITLE
error with shell command

### ISSUE THREAD

**Issue by x0rld** [fish-shell/fish-shell#7628]
hi i'm using
  fish --version: 3.1.2
i'm on fedora 33
Linux localhost.localdomain 5.9.15-200.fc33.x86_64 #1 SMP Wed Dec 16 19:14:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

when I want to install docker compose with the curl command and remove the $
```bash
```
sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
I have this url which is not valid cause the uname are not executed
```
https://github.com/docker/compose/releases/download/1.27.4/docker-compose-(uname -s)-(uname -m)
```

Did I do something wrong ?

**Comment by faho** [comment]
Fish does not execute command substitutions inside of quotes, so this should be

```fish
sudo curl -L https://github.com/docker/compose/releases/download/1.27.4/docker-compose-(uname -s)-(uname -m) -o /usr/local/bin/docker-compose
```

I'd recommend you take another look at [the documentation](https://fishshell.com/docs/current/index.html), because the differences between bash and fish go deeper, scripting-wise, than just "removing the $".

**Comment by x0rld** [comment]
thank you it works now
