### ISSUE TITLE
Different Colours for stdout and stderr

### ISSUE THREAD

**Issue by MagicMuscleMan** [fish-shell/fish-shell#7632]
Sometimes, it's not clear if the output of a command came from the command's stdout or from its stderr.
Therefore, it would be nice, if Fish could optionally color them differently, e.g. by prefixing with "colorstderr" or by setting an environment variable or something similar.

**Comment by faho** [comment]
That doesn't work - stdout and stderr *do not* go through fish. They go directly to the terminal.

So the *terminal* is the place to change this, not fish.

**Comment by MagicMuscleMan** [comment]
Thanks for the hint and the quick response.

**Comment by zanchey** [comment]
There's various tools for doing this - I use https://github.com/sickill/stderred or https://github.com/poettering/rederr is an alternative.

I used to use some preexec magic in zsh, but it was quite racy from memory and would often confuse the terminal or cause interspersed writes.

**Comment by MagicMuscleMan** [comment]
Thanks, @zanchey, I tested rederr, as it is from a very well known and talented programmer, and it's simple to compile and it works as intended.
Having it in terminal would probably still be a bit cleaner, but this is good enough for the time being.
