### ISSUE TITLE
Clean up fish_git_prompt

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7633]
`fish_git_prompt` is the most dense and unreadable Fish code I've ever seen. Scientists and philosophers could study that 1000 line monstrosity for eons and not make a dent 😂 I imagine it got this way because it's trying to do too much.

1. Be compatible with the bash version
2. Read from git config as well as fish config
2. Allow for virtually infinite customization (not in the fish spirit?)

Maybe it just needs a makeover, but I'd bet it goes deeper than that, however I'm not really sure how to fix it. 

I don't actually suggest devoting developer time to this right now, but I just want to put it on the table.

**Comment by faho** [comment]
"Make code cleaner" is *always* on the table. 

Which is why this issue isn't needed - there is no point we could declare this "done".

(also note that it used to be *a lot* worse)

**Comment by IlanCosman** [comment]
Obviously code can always be better, but the point of this issue was to generate ideas on how to make _this specific piece_ better, including perhaps moving in a different direction entirely.

For example, maybe we might want to create 3 different git prompt functions at different levels of verbosity that we feel would be good defaults for 95% of users who want to customize their prompt. Maybe we want to leave `fish_git_prompt` alone but create a new function with different goals than the ones that `fish_git_prompt` currently has.

I didn't explain/title the issue well enough, my apologies. Every issue can be reduced to a "make fish better" issue. This one is just pointing out a problem, and hoping that we could brainstorm some ideas on how to fix it.
