### ISSUE TITLE
Unable to change cursor shape based on vi mode on alacritty

### ISSUE THREAD

**Issue by cubetastic33** [fish-shell/fish-shell#7634]
**fish --version**: fish, version 3.1.2
**uname -a**: Linux hogsmeade 5.10.4-arch2-1 #1 SMP PREEMPT Fri, 01 Jan 2021 05:29:53 +0000 x86_64 GNU/Linux
**echo $TERM**: alacritty
**OS**: Arch linux
I tried it without third party customizations, and the issue persisted.

### Description

I'm unable to change the cursor shape based on the vi mode on alacritty. It does, however, work perfectly fine on kitty. I have these lines in my `config.fish` file:
```fish
# Set the cursor shapes for the different vi modes.
set fish_cursor_default     block
set fish_cursor_insert      line       blink
set fish_cursor_replace_one underscore
```
I know for a fact that it's possible to switch the cursor on alacritty, because it works fine when I'm in zsh or neovim, and when I enter fish from zsh, whichever cursor I had previously persists. For example, if I'm in zsh with a line cursor, and then run `fish`, then fish runs with a line cursor. Similarly, the same thing happens with a block cursor. Quitting neovim from fish also means the block cursor persists on fish (because I'm in normal mode when quitting vim). The only issue is that fish is not able to change my cursor.

I'm not sure how to fix this, but my primary terminal emulator is alacritty, so I would really appreciate some help. Thank you!

**Comment by cubetastic33** [comment]
I'm really sorry, I just found [commit 3c6c8d542410cd84b8249c84a58ec28db71fba06](https://github.com/fish-shell/fish-shell/commit/3c6c8d542410cd84b8249c84a58ec28db71fba06) which fixes this. I installed the latest version of fish from master and now it works fine.

**Comment by cubetastic33** [comment]
Blinking cursors do not work though - but I'm not sure if this is an alacritty issue or a fish issue, because I haven't seen blinking cursors in other programs in alacritty either. Should I reopen this issue or perhaps make an issue in the alacritty repo?

**Comment by faho** [comment]
>Should I reopen this issue or perhaps make an issue in the alacritty repo?

Fish should be sending the correct sequence to make it blink (see https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_cursor_xterm.fish), so it's an alacritty issue.

**Comment by cubetastic33** [comment]
I see, thanks!
