### ISSUE TITLE
Can the current command be run and paginated in one key press?

### ISSUE THREAD

**Issue by xster** [fish-shell/fish-shell#7637]
Using version 3.1.2. Sorry if I'm misunderstanding how https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_paginate.fish is supposed to work. When I use it, it just appends `&| less` to the current line. If that was the intent, it would be nice to execute the command in one shot as well since pressing alt-p already indicates a strong intent of actually running the command.

**Comment by faho** [comment]
Executing something can be done with `commandline -f execute`, e.g.

```fish
bind \ep '__fish_paginate; commandline -f execute
```

Very few bindings should execute by default and it should be crystal clear when that happens, so we will not be changing the default.

**Comment by xster** [comment]
Thanks! Understood if the philosophy is to not execute things in one shot.
