### ISSUE TITLE
no tab-completion with alias for flatpak app

### ISSUE THREAD

**Issue by baloe** [fish-shell/fish-shell#7639]
`fish --version`:  fish, version 3.1.2
`echo $version`: 3.1.2

OS: Ubuntu 18.04.4
`uname -a`: Linux 4.15.0-132-generic #136-Ubuntu SMP Tue Jan 12 14:58:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

`echo $TERM`: xterm-256color

Without third-party customizations, i.e. after executing the following command the issue is gone.
  `sh -c 'env HOME=$(mktemp -d) fish'`

This is what happens:
typing `meld un`+`TAB` does not expand to `meld uniquename`, where `uniquename` is the name of the only file or directory starting with `un`.

**Comment by baloe** [comment]
Ahh `fish_config` lists:
```
# Defined in - @ line 1
function meld --wraps='flatpak run org.gnome.meld' --description 'alias meld=flatpak run org.gnome.meld'
    flatpak run org.gnome.meld $argv
end
```
That should be the culprit then.

**Comment by faho** [comment]
Well, yeah, that's trying to complete `flatpak`.

We don't ship completions for `meld`, and if we did we wouldn't detect it here - I don't see a general way to handle this.

We could enable file completions after `flatpak run something`.

The solution is probably to not use "--wraps" (which is added by `alias`). Just:

```fish
function meld
    flatpak run org.gnome.meld $argv
end
```

will fall back onto the default completions for `meld`, which are just the standard file completions.

**Comment by baloe** [comment]
> The solution is probably to not use "--wraps" (which is added by `alias`). Just:
> 
> ```fish
> function meld
>     flatpak run org.gnome.meld $argv
> end
> ```
> 
> will fall back onto the default completions for `meld`, which are just the standard file completions.

Awesome! With the function instead of an alias `meld`-commands are completed just fine. Thank you.
