### ISSUE TITLE
Incorrect syntax correction on string passed to remote ssh host

### ISSUE THREAD

**Issue by dlampa** [fish-shell/fish-shell#7640]
I'm encountering an issue when sending the following command to a remote host using ssh:
`ssh remote-host "some-command; echo $?"`

Fish interprets the `echo $?` as if it was meant to be executed by local fish shell (the remote machine does not have fish installed) and prompts:
`fish: $? is not the exit status. In fish, please use $status.`

I am not using any 3rd party customizations.

**Comment by faho** [comment]
You're double-quoting the string. Variables are expanded in double-quotes, by the local shell, before being passed to the command.

Use single-quotes or escape the `$` - 

```fish
ssh remote-host 'some-command; echo $?'
```

Note: This problem would also happen in bash (and zsh and any other vaguely similar shell), except it would just expand the $? and send it on. You still would not see the status of `some-command`.

**Comment by dlampa** [comment]
Thanks for the explanation, makes perfect sense!
