### ISSUE TITLE
fish_term256bit not working

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7643]
```fish
ilan@arch ~> set_color FF0002 | string escape
\e\[38\;2\;255\;0\;2m
ilan@arch ~> set -g fish_term24bit 0
ilan@arch ~> set_color FF0002 | string escape
\e\[38\;5\;196m
ilan@arch ~> set -g fish_term256bit 0
ilan@arch ~> set_color FF0002 | string escape
\e\[38\;5\;196m
```
fish 3.1.2
$TERM = xterm-256color
Terminal = xfce
Linux arch 5.10.9-arch1-1 x86_64 GNU/Linux
Perfectly clean fish

This is the specific configuration I used, however I can reproduce this with every configuration under the sun. macOS iterm2 and terminal, ubuntu with fish 3.2, linux terminals etc.

**Comment by faho** [comment]
The 256 color variable is `fish_term256`, not `fish_term256bit`.
