### ISSUE TITLE
Fish help includes erroneous backslashes in escape sequences section

### ISSUE THREAD

**Issue by schuelermine** [fish-shell/fish-shell#7644]
# Fish help includes erroneous backslashes in escape sequences section

The fish help in `/usr/share/doc/fish/index.html` as well as the one shown on https://fishshell.com/docs/current/index.html shows that the escape sequence that escapes the `<` and `>` use two backslashes.
This is incorrect, fish interprets the `\\<` sequence as an escaped backslash and an incomplete redirection statement.

# Screenshots:

![Screenshot of locally installed fish help page opened in Firefox](https://user-images.githubusercontent.com/48802534/105503519-fc3bf580-5cc6-11eb-8ed7-92d4ad5a6ca4.png)
![Fish accepting a single backslash](https://user-images.githubusercontent.com/48802534/105504030-94d27580-5cc7-11eb-821a-8f6242491895.png)

# More info:

```
fish, version 3.1.2
```

```
Linux buggeryyacht-pop 5.8.0-7630-generic #32~1609193707~20.10~781bb80-Ubuntu SMP Tue Jan 5 21:29:56 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
xterm-256color
```

Also occurs without customizations

Reproduced by opening the fish help on fishshell.com or running `help` in fish

**Comment by faho** [comment]
Already fixed by 1547a226598526b748956257b94d493a77300261
