### ISSUE TITLE
Fish FD 9 unexpected output redirection

### ISSUE THREAD

**Issue by volkov** [fish-shell/fish-shell#7646]
Using fish 3.1.2 
`echo test 8>&2 1>/dev/null` prints nothing
`echo test 9>&2 1>/dev/null` prints `test`,  fish 2.7.1 prints nothing.

Is this bug or feature around fd 9? Don't find anything in docs about redirection https://fishshell.com/docs/current/#input-output-redirection

**Comment by zanchey** [comment]
I think this is the same underlying issue as #3303 - you can write to arbitrary file descriptors using builtins, which can end up touching internal machinery (in this case fd 9 is one end of a pipe). I'll close this as a duplicate for now, though if I'm wrong then please speak up.

**Comment by zanchey** [comment]
Actually this turned out to be slightly more interesting; `/dev/null` was being opened as file descriptor 9, which then got hooked up to stderr. Anyway it was fixed with 4b9a096cf2b754f although I'm not sure that was deliberate.
