### ISSUE TITLE
Make fish_history have a single default value

### ISSUE THREAD

**Issue by etcusrvar** [fish-shell/fish-shell#7650]
fish 3.1.2
enhancement, change request

There are 3 different settings that the variable `fish_history` can have that all essentially mean the same thing ([docs](https://fishshell.com/docs/current/cmds/history.html#customizing-the-name-of-the-history-file))--
- fish_history is unset
- $fish_history = default
- $fish_history = fish

It would be nice if this was a single value.

Motivation: I've been writing snippets of code frequently such as
```
if set -q fish_history
    switch $fish_history
        case default fish
            set foo fish
        case \*
            set foo $fish_history
    end
else
    set foo fish
end
do-something-with $foo
```

This can be worked around easily enough with an `--on-variable` function, such as
```
> function _fish_history_value --on-variable fish_history
    test "$fish_history" = default && set -g fish_history fish
    not set -q fish_history && set -g fish_history fish
end
> _fish_history_value
> echo $fish_history 
fish
> set fish_history default; echo $fish_history
fish
> set -e fish_history; echo $fish_history
fish
> set fish_history foo; echo $fish_history
foo
```

I call a function like this at the top of my config.fish. And all is fine. But others I share functions or plugins or the like with may not have this workaround, or even want it.

This seems like it should be something that is handled in the `fish_history` variable itself.

**Comment by faho** [comment]
Yeah, we should probably ditch the "default" value.

However, what I'd like to know is what you're *doing* with the value? I'd expect most people and programs to not care *at all* about $fish_history, and those that do I'd expect to just set it and be done, so if you're doing anything else that's interesting.

**Comment by etcusrvar** [comment]
I essentially do exactly what you said-- just set it and be done.

Here's a function I use all the time to start a new fish "profile" subshell:
```
function fishp
    fish_history=$argv[1] $__fish_bin_dir/fish $argv[2..-1]
end
```
I freqently do
- `fishp sudo -P` # just sudo/system stuff
- `fishp chezmoi|docker|project1|project2|...`

So, I don't set fish_history interactively (yet).

But I *use* the value in a lot of places-- config.fish, fish_prompt, fish_title, ...

I turned some of my homegrown functions into a [plugin](https://github.com/etcusrvar/fish-session) that's essentially a workaround until #7589 is merged to a fish release. Here's one [snippet](https://github.com/etcusrvar/fish-session/blob/d17ded0d3cd95e6ea49415dad89769506e9ceb28/functions/session.fish#L97-L109) that prompted me to open this issue.

I also have lines in my config.fish that do extra configuration based on the profile I started fish with. Essentially,
```
set -l p $__fish_config_dir/profiles/$fish_history
set -p fish_complete_path $p/completions
set -p fish_function_path $p/functions
for f in $p/conf.d/*.fish
    source $f
end
source $p/config.fish
```
(But a tad more [elaborate](https://github.com/etcusrvar/fish-config-paths).)

In these files I have other functions, aliases, completions, etc.

I also use [direnv](https://github.com/direnv/direnv) heavily, and have lines like `export fish_history=$(basename $PWD)` in some directories' .envrc files.

I use `fish_history` as a session profile mechanism beyond simply the history file itself. I did the same kind of thing in zsh with ZDOTDIR, but fish is so much easier to use and more configurable :).

**Comment by faho** [comment]
>I use fish_history as a session profile mechanism beyond simply the history file itself.

That's.. simply not what it's meant for.

If you want to add a session mechanism, add it and then set $fish_history depending on *that*, instead of going via $fish_history.

```fish
set -q fish_profile
or set -g fish_profile fish

set -g fish_history $fish_profile
```

**Comment by etcusrvar** [comment]
I think that's what I've done in the links in the previous comment. Maybe I should have phrased that last sentence differently.

**Comment by faho** [comment]
Alright, I've just removed the special handling of "default". Now you either set $fish_history to the actual string (with "fish" being the default one), or you leave it unset (and it's still "fish").

I don't think we need to add anything more for backwards compatibility here - just use "fish", always, if you must set it. I don't expect many people to have ever used "default".
