### ISSUE TITLE
history deduplicate?

### ISSUE THREAD

**Issue by chapmanjacobd** [fish-shell/fish-shell#7651]
Is there a way to run a history cleanup? I use syncthing to synchronize my history between multiple machines and so I sometimes do

```
bat ~/.local/share/fish/fish_history.sync-conflict* >> ~/.local/share/fish/fish_history
```

and now I have a 34MB history file... now it takes about 5 seconds to run fzf ctrl+r.

Is there a way to manually trigger some kind of cleaning? I'm sure there are a lot of duplicates

https://github.com/fish-shell/fish-shell/issues/6278

**Comment by faho** [comment]
Fish automatically periodically deduplicates history and keeps the last 250000 entries.

That should take care of your problems.

**Comment by chapmanjacobd** [comment]
I searched the repo for `250000` but don't see anything except this issue :/

How periodically does it run? Once a day or...?

**Comment by faho** [comment]
>I searched the repo for 250000 but don't see anything except this issue :/

To be precise, it's 1024 * 256, so a tad more than 250 thousand.

>How periodically does it run? Once a day or...?

Every 25 commands.
