### ISSUE TITLE
Completion error on macOS with launchctl

### ISSUE THREAD

**Issue by melomac** [fish-shell/fish-shell#7655]
Hello

I am using HEAD version of `fish` for some times now and I am having the following error on current version of macOS with the completion for the command line interface `launchctl`.

To reproduce the problem on `fish` HEAD, kindly invoke `launchctl` and start writing the option with name `unload`, ex: `unl` and press the tabulation key ⇥ to trigger autocompletion:

```
user@hostname ~> launchctl unl
```

Terminal output gets flooded with the following error message, right after the `unl` user input, without any line feed:

```
complete: Completion 'attach\tAttach the system's debugger to a service' contained a syntax error
complete: Expected a string, but found a parse_token_type_t::tokenizer_error
attach\tAttach the system's debugger to a service
                   ^
complete: Completion 'limit\tReads or modifies launchd's resource limits' contained a syntax error
complete: Expected a string, but found a parse_token_type_t::tokenizer_error
limit\tReads or modifies launchd's resource limits
                         ^
complete: Completion 'bsexec\tExecute a program in another process' bootstrap context' contained a syntax error
complete: Expected a string, but found a parse_token_type_t::tokenizer_error
bsexec\tExecute a program in another process' bootstrap context
                                     ^
fish: Unknown command: targets
targets the Info.plist by default
^
in command substitution
```

Out of curiosity, I edited the `/usr/local/share/fish/completion/launchctl.fish` file to backslash `\` parenthesis `()` and single quotes \` and the error disappeared.

I am not sure why the completion is invoked that way, and I wouldn't want to push a fix that would not follow the project guidelines, so I am leaving the fix to regular maintainers with my best consideration to the project maintainers.

Many thanks for the great work with `fish`.

**Comment by faho** [comment]
Yeah, this was written in a weird manner - it passed the description as part of the argument, which is possible (so you can do dynamic descriptions), but didn't escape them properly.

This was broken as part of f507f4ad1eadfd69bbeb122bce38eefca7c82e2b, which isn't in a release yet, so I'm tagging it as a regression.

**Comment by melomac** [comment]
Many thanks @faho for the very fast fix. Shouldn't the other completions get a fix too?

**Comment by faho** [comment]
The other completions aren't affected as they don't use this weird parameter passing convention.

Tho now that I say that, I see that the gem completions are also affected.
