### ISSUE TITLE
Selecting previous command forgets trailing escaped space

### ISSUE THREAD

**Issue by Shizcow** [fish-shell/fish-shell#7661]
## Problem and Reproduction
Take the following command (where there is a space after `\`, making it escaped)
```sh
echo \ 
```
The command will execute properly. However, when pressing up to re-use the previous command, the trailing space is removed. While removing trailing spaces is usually a good idea, I don't think this should be the case when the last space is escaped.

As this __seems__ like a pretty simple fix, I'd be happy to try my hand at fixing -- assuming this is indeed a bug and someone doesn't beat me to it!

## System Info
Fish version: `3.1.2`
OS: Arch Linux
Present when customizations are disabled

**Comment by krobelus** [comment]
Yeah, looks like a bug. The space trimming is [historical behavior](https://github.com/fish-shell/fish-shell/blob/master/src/reader.cpp#L3228-L3231). I think we could exercise a `tokenizer_t` here to tell real spaces from escaped ones.

**Comment by ridiculousfish** [comment]
@Shizcow yeah seems like it should be a straightforward fix, if you know a little C++. krobelus showed the source location, you could enhance that to only trim spaces that have zero preceding `\` (or have an even number).

**Comment by Shizcow** [comment]
Yeah, just had some schoolwork to finish before I could put any time towards anything else. Everything should be in order now.

**Comment by ridiculousfish** [comment]
Merged the PR as cff5aa9130f650a2a497296942972b9922f60cc1, thank you!
