### ISSUE TITLE
`test` fails to compare a multi-line string

### ISSUE THREAD

**Issue by recolic** [fish-shell/fish-shell#7663]
in fish 3.1.2, 

# Problem

I have a file `test.txt` with the following content:

```
abc
def
efg
```

then I run

```fish
if test 'null' != (cat test.txt)
    echo 'good'
end
```

# Expected output

```
good
```

# Actual output

```
test: Expected a combining operator like '-a' at index 3

(Type 'help test' for related documentation)
```

**Comment by faho** [comment]
fish splits command substitutions on newlines.

That means test receives each line as a separate argument. Use

```fish
test 'null' != (cat test.txt | string collect)
```
