### ISSUE TITLE
fish_prompt/fish_right_prompt don't parse ANSI escape codes correctly

### ISSUE THREAD

**Issue by Lokaltog** [fish-shell/fish-shell#767]
I'm working on a [Powerline](https://github.com/Lokaltog/powerline) renderer for fish, but I'm stuck because I'm unable to get fish to render the prompts correctly.

Powerline prints standard ANSI escape codes, and requires the ability to reset colors, and set fg/bg/attribute options. An example of the default prompt output would be:

```
^[[0;38;5;231;48;5;31;1m kim ^[[0;38;5;31;48;5;240;22m ^[[0;38;5;252;48;5;240;1m~ ^[[0;38;5;240;49;22m ^[[0m
```

The output from the script is in UTF-8. Node that this utilizes combined escape sequences to shorten output. I have tried adjusting the renderer to print separate sequences (each fg/bg/attributes in their own `^[[...m` sequence) but without luck.

The prompt is tested and works fine in other shells like bash or zsh.

This is my config.fish:

```
function fish_prompt
	powerline shell left --last_exit_code=$status
end
function fish_right_prompt
	powerline shell right --last_exit_code=$status
end
```

This is a screenshot of the issues I'm having:

![2013-05-18-115723_1278x393_scrot](https://f.cloud.github.com/assets/78438/521414/6430f620-bfa1-11e2-9c19-206a07da233a.png)

As you can see the following issues occur:

* The text input is moved way to the right when the rprompt is empty
* When the left prompt is too long(?) it is replaced by `> `
* The right prompt isn't right aligned

I've tried searching through the docs but haven't found any info on the issue. I've noticed that `set_color` outputs ANSI sequences as well, but I'm not quite sure which ones break the Powerline prompt.

**Comment by faho** [comment]
I can no longer reproduce this. I'm assuming it has been fixed in the meantime.
