### ISSUE TITLE
MPV+YTDL doesnt work without quotations

### ISSUE THREAD

**Issue by Quackdoc** [fish-shell/fish-shell#7672]
An annoying issue but not the worstusing MPV and appending a youtube link causes fish to spit out "fish: no matches for wildcard..." error

mpv https://www.youtube.com/...
HOWEVER puting the youtube link in quotations does work
mpv "https://www.youtube.com/..."
works and plays the video 

neither zsh or bash have this issue

NOTE: Youtube-DL also exhibits this behavior, but MPV when playing local files does not

**Comment by ridiculousfish** [comment]
I assume this is complaining about the question mark, which is interpreted as a glob. fish is moving away from supporting `?` globs. See #3649, #4520, #967 for past discussions.

You can opt into disabling `?` globs today by setting the `qmark-noglob` feature flag ([docs here](https://fishshell.com/docs/3.1/index.html?highlight=qmark#featureflags)):

    set -U fish_features qmark-noglob

Just run that once, not at every launch; then open a new session.  Does that help?

**Comment by Quackdoc** [comment]
I can confirm this fixed it, thanks for the prompt resolution

**Comment by pashosh** [comment]
thanks.
