### ISSUE TITLE
Are you sure you want to continue connecting (yes/no/[fingerprint])? 

### ISSUE THREAD

**Issue by ketanpatil3** [fish-shell/fish-shell#7676]
How to bypass ssh prompt Are you sure you want to continue connecting (yes/no/[fingerprint])?
auto type yes and enter without human intervention

**Comment by faho** [comment]
Not a fish problem, but:

```fish
ssh -o "StrictHostKeyChecking no" user@host
```

Note that this typically isn't advisable - you can get MitM'd doing this.

**Comment by ketanpatil3** [comment]
@faho I want some way for fish-terminal to scan the output and auto enter yes. 
I do not want to use ssh -o "StrictHostKeyChecking no" user@host

**Comment by faho** [comment]
Fish is not a terminal and therefore has no connection to what ssh does. Try something like expect.

**Comment by ketanpatil3** [comment]
Thanks found out the solution. add StrictHostKeyChecking=accept-new below host * in ~/.ssh/config file
