### ISSUE TITLE
funced is wonky if terminal is too small

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7679]
Perfectly clean fish 3.1.2, `xterm-256color`, Arch Linux

![funced](https://user-images.githubusercontent.com/6318351/106830975-f5f13600-6643-11eb-84a2-5dde9ae08cf2.gif)

Notably, this doesn't happen if the terminal is already large enough to fit the full text of the function.

**Comment by krobelus** [comment]
Duplicate of #7296

**Comment by krobelus** [comment]
(the best workaround is to set `EDITOR`)
