### ISSUE TITLE
Unintentional changing mode on Fish.

### ISSUE THREAD

**Issue by bnsv** [fish-shell/fish-shell#7682]
Hello, I have difficulty to diagnosis what is happened with my Fish. I don't even know how to google it.
So suddenly today an [I] or [N] appear in my Fish prompt when i press alt+b key, or i button, and regular bash key not worked/disable (Ctrl+a, Ctrl +F). Last time I remember I installed theme name dangerous via OMF, Why does this happening? I want to my use the key combination like usually. I tried to remove, purge and reinstall the installation via apt but the problem still occur.

**Comment by faho** [comment]
Your turned on vi-mode (some "themes" have the arrogance of deciding that for you) 

Use `fish_default_key_bindings" to switch back.

The theme might try turning it on again, so you'll also want to switch that.

**Comment by bnsv** [comment]
Thank you very much @faho  you are right. 
An addon that I installed is resetting my key binding variable in my config.
So I reset from
``SETUVAR fish_key_bindings:fish_vi_key_bindings``
to
``SETUVAR fish_key_bindings:fish_default_key_bindings``
