### ISSUE TITLE
Escape sequences not being applied in correct order

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#7685]
I'll start with this: I didn't have my coffee this morning. I went and made it five minutes ago, but haven't consumed this sanity-restoring beverage as of yet, even though it's well into the afternoon.

That said, what am I missing here? Has this always been like this? Isn't this broken?

```fish
> echo (echo hello\\)
fish: Mismatched parenthesis
echo (echo hello\\)
     ^
```

**Comment by faho** [comment]
You're right, it's broken.

**Comment by mqudsi** [comment]
Yeah, I just tested on 2.0.0 and it was broken. I'm really floored this didn't break everything and get found out immediately.

**Comment by faho** [comment]
This is bound to be down to one of our i-cant-believe-its-not-a-parser bits - some "unescape" thing or other.

Adding a space fixes it, so it's really just misidentifying the escape in one place.

**Comment by faho** [comment]
Yeah, "parse_util_locate_brackets_of_type" just checked if *the previous character* was a backslash, it did not care if the one before that was also one.
