### ISSUE TITLE
fd_monitor tests fail on 32-bit Github Actions

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#7699]
From https://github.com/fish-shell/fish-shell/pull/7698/checks?check_run_id=1855961860:

```
Testing fd_monitor
Error: Test failed on line 883: item0_timeout.did_timeout
Error: Test failed on line 886: item42_timeout.length_read == 42
Error: Test failed on line 887: item42_timeout.did_timeout
Error: Test failed on line 890: item42_nottimeout.length_read == 42
Error: Test failed on line 895: item42_thenclose.length_read == 42
Error: Test failed on line 896: item42_thenclose.total_calls == 2
Error: Test failed on line 900: item_oneshot.length_read == 42
Error: Test failed on line 901: item_oneshot.total_calls == 1
Error: Test failed on line 906: item_pokee.total_calls == 1
Error: Test failed on line 907: item_pokee.pokes == 1
```

This happens regularly, but not always, since some time around 9147a30926b6bddedcbe51039c3fe467fab8b8a5.

I can't reproduce it on my 64-bit arch with -m32.

**Comment by faho** [comment]
This is probably somewhere in 7e2a538300341aefc445c3be38e3d9d475ee7b39..97bde2f2bfb2be8d07e4ab35ed4a3d7098d5688c, which appear to have been committed in one push.

Those touch the io/fd code and as far as I can tell are "shortly" before it starts happening. That does mean we got (un)lucky and had this succeed two times in a row.

**Comment by ridiculousfish** [comment]
I added a 32 bit Docker build, unfortunately it did not repro this.

**Comment by faho** [comment]
Tests have now run a bunch of times without failure, I think this is fixed.
