### ISSUE TITLE
Colors aren't correct over SSH

### ISSUE THREAD

**Issue by katacarbix** [fish-shell/fish-shell#7701]
Colors are not displaying correctly over an SSH connection. Here is a screenshot to show what I mean:
![demo](https://user-images.githubusercontent.com/1340784/107296256-9fff0280-6a36-11eb-8fb6-b258a903833c.png)
The one on the left is a local shell, and the one on the right is an SSH shell to another computer on my network. They both have almost the exact same fish configuration with the same [fish_variables file](https://github.com/katacarbix/dotfiles/blob/main/fish/fish_variables). The only real difference is that there are fewer oh-my-fish plugins on the remote machine.

This problem persists when SSHing into my own machine (`ssh localhost`). Running `sh -c 'env HOME=$(mktemp -d) fish'` is not needed as the issue is only present with my config. I looked through #7051 but their issue seems to be with 256-color, not 24-bit/true color.

Are the color variables just not being set correctly? Or do you think this is a deeper issue with the SSH protocol itself?

Edit: [Here](https://github.com/katacarbix/dotfiles/blob/main/fish/functions/print_fish_colors.fish) is the link to the `print_fish_variables` program shown above.

**Comment by faho** [comment]
In short: Most likely run `set -g fish_term24bit 1` on the remote end.

So: `tput colors` doesn't reflect *fish's* view of how many colors a terminal can support, it reflects *terminfo's*. And unfortunately this is an ideal example to show that it is broken - this is the official terminfo supplied by the upstream terminal, and yet it says it can only do 256 colors, which is just plain untrue.

So fish has to go elsewhere, and checks the environment for clues on if a terminal can actually do truecolor (unfortunately $COLORTERM wasn't in that list in 3.1, it is now), but ssh sanitizes the environment, so it often removes those clues.

When fish has to do 256 colors, it maps the rgb values it is given to what it thinks the color palette is (which is IIRC xterm's default), so if your terminal's palette differs it will come out wrong.

Also: Please upgrade to 3.1.2, use [our PPA](https://launchpad.net/~fish-shell/+archive/ubuntu/release-3) (yes, the Ubuntu package is basically unmaintained, it's annoying)

**Comment by katacarbix** [comment]
Thank you, that worked! Should I add it to my fish config then?

I will upgrade the package as well.

**Comment by faho** [comment]
>Thank you, that worked! Should I add it to my fish config then?

I'd predicate it on $COLORTERM being set to truecolor -

```fish
if test "$COLORTERM" = truecolor
   set -g fish_term24bit 1
end
```

(this won't be necessary in 3.2 because that also checks $COLORTERM when deciding on color support)

**Comment by katacarbix** [comment]
Sounds good, thank you again.
