### ISSUE TITLE
How to stop prompt from changing to '>' (arrow)

### ISSUE THREAD

**Issue by MuhmmadZohaibImtiaz** [fish-shell/fish-shell#7706]
fish, version 3.1.2
Linux reaper 5.10.14-119-tkg-bmq #1 TKG SMP PREEMPT Mon, 08 Feb 2021 12:16:22 +0000 x86_64 GNU/Linux
alacritty

I am trying to stop prompt from changing to '>' I tried changing in files of fish_prompt and fish_breakpoint_prompt but it didn't made a difference.
I always want to see full prompt.
Thanks in advance :)

**Comment by faho** [comment]
The prompt changes to `>` when a line in it is too long to fit your terminal.

So either make it smaller (you can also check $COLUMNS for this) or make your terminal wider.

The next release will truncate the prompt instead, that's #904.

**Comment by MuhmmadZohaibImtiaz** [comment]
How do I do this "spread the output over more lines" .

**Comment by faho** [comment]
> I want to see this all in same way.

Well, no, you won't see it in exactly the same way because your terminal is too small to fit it.

You'll see it on multiple lines.

What you do is open your fish_prompt (for example via `funced fish_prompt`), and where it says something like

```fish
echo $user at $host in $pwd (fish_git_prompt)
```

change it to

```fish
echo $user at $host in $pwd\n(fish_git_prompt)
```

**Comment by MuhmmadZohaibImtiaz** [comment]
I can't see the line you mentioned. 
![Screenshot_2](https://user-images.githubusercontent.com/71523302/107611879-d02ce800-6c66-11eb-9ded-e4010bcae047.png)

**Comment by faho** [comment]
It's that `echo -n -s` line at the end. Add a `\n` wherever you want a linebreak to it, probably after the `(prompt_pwd)`.

**Comment by MuhmmadZohaibImtiaz** [comment]
nope. it didn't worked.

**Comment by faho** [comment]
Well.... what did you do?

Can you paste the new prompt and show what it did? Can you show what running `fish_prompt` outputs?

Is it possible it's simply still too long? In that case you need to add more lines still.

**Comment by MuhmmadZohaibImtiaz** [comment]
1- muhammad-zohaib-imtiaz at reaper in ⌁/Documents/Gmail/workdesk-web (task/muhammad-zohaib/GR-845/regions-frontend ✚2)
2- muhammad-zohaib-imtiaz at reaper in ⌁/Documents/Gmail/backend-api (develop ⚑1)

The first one coverts to '>' the second does not. 
The change I made in the fish_prompt did nothing. in neither directories.

I missed this `funcsave fish_prompt` I rebooted the system instead. 
I think the `fish_breakpoint_prompt` runs before `fish_prompt.` I tried changing condition `$COLUMNS / 2`  to `$COLUMNS * 2` even that didn't work in file `fish_breakpoint_prompt`

**Comment by faho** [comment]
> The change I made in the fish_prompt did nothing. in neither directories.

Welll..... what change did you make?

**Comment by lordlycastle** [comment]
I too was looking for the place to remove this behavior. And if you search for obvious things the comment in `fish_breakpoint_prompt` certainly looks like the perfect obvious place. But that is only for breakpoints as name implies.

The real place where this takes place is in `src/screen.cpp:364 layout_cache_t::calc_prompt_layout` for current master (`a503371c572`). The changes were made in `a2ae2d6c36147009bc565ca7ec8fc20340ac48b9`. 

I wish to add a global config variable and make this truncation optional. People with multi-line prompt might prefer to not clip the prompt. I know it messed up the right side prompt as it needs to be one new line, but I can't think of a solution (maybe this flag only works when no right side prompt? this just adds more hidden "knowledge" complexity.)

This is a difficult one. Now wonder #904 discussion has so many comments 😅

**Comment by ridiculousfish** [comment]
@lordlycastle the prompt is supposed to only clip with … if it is too wide to fit in the tty. Is your prompt narrow enough that it ought to fit (in which case this is a bug), or would you rather that the prompt wraps across two lines?

**Comment by faho** [comment]
Alright, the question here has been answered. If someone wants to make a case for our shortening still being inadequate, please file another issue and make your case. Especially explain how it should work - do lines just overflow? Where do we put the linebreaks then? What about the right prompt?

Personally I think what we have seems perfectly acceptable and I feel anything else would get quite complicated, but have at it.

**Comment by lordlycastle** [comment]
Sorry for the late reply. Turned on the email notification 🙄 

Yeah I am pretty much changing it to be multi line. The reason I happen to use the prefix part of the prompt as well. E.g.:

```
<date_time>) short/path <tool versions e.g. py, node, tf based on activation>            [run_time/status]
> _cursor_
```
It can sadly become like this (because I have a habit of verbose folder e.g. `home/work/company/client/repositories/some.project` 🤌 ):
```
.../repositories/some.project/src <tool versions e.g. py, node, tf based on activation>[run_time/status]
> _cursor_
```
Anyways it far better with `...xxx>` than `>` which was originally why I too arrived here.
