### ISSUE TITLE
Automatically set value of DISPLAY messes up `ssh -X`, at least on Mac OS X 10.8

### ISSUE THREAD

**Issue by yosinski** [fish-shell/fish-shell#771]
When fish is launched, the value of DISPLAY is automatically populated from somewhere like this:

    $ env | grep DISPLAY
    DISPLAY=/tmp/launch-1mavYA/org.macosforge.xquartz:0

And this value causes ssh to fail:

    $ ssh -X hostname
    <hangs forever>

If I run bash, the DISPLAY is set to `:0.0`, which works fine. Further, if I run `fish` from within `bash`, the correct value is inherited and ssh works fine:

    $ bash
    $ fish
    $ env | grep DISPLAY
    DISPLAY=:0.0    
    $ ssh -X hostname
    <works great>

Why is fish populating DISPLAY differently from the Mac OS X default via bash? Where can this setting be changed?

Submitting this as an issue because (a) while one could `set DISPLAY :0.0` in `fish.config`, this would only be appropriate for local sessions, not for remotely connected ssh sessions, and (b) because this behavior does not seem to be documented anywhere.

(Fish version: 1.23.1, installed via homebrew)

**Comment by faho** [comment]
Nobody has reproduced this in 2 years. Close?

**Comment by ridiculousfish** [comment]
Let's close.
