### ISSUE TITLE
Feature Request: 'set --erase' for multiple/all scopes

### ISSUE THREAD

**Issue by daveman1010221** [fish-shell/fish-shell#7711]
Hello!

I'm not in the practice of requesting features, but I feel this is one that is missing. It seems that un-setting a variable can be more difficult than it really should be, requiring a number of logic checks to ensure a setting is really gone. Could we have a:

```
set --ERASE foo
```
wherein, it actually un-sets the variable, regardless of scoping? I will even submit a pull request, if you agree. :-)

Thanks.

Additional details:

  fish --version
  fish, version 3.1.2

  Ubuntu, Groovy
  uname -a
  Linux xxxxxxxx 5.8.0-7642-generic #47~1612288990~20.10~b8113e7~dev-Ubuntu SMP Wed Feb 3 01:55:26 U x86_64 x86_64 x86_64 GNU/Linux

  echo $TERM
  xterm-256color

**Comment by faho** [comment]
There is `set --erase` to "just erase a variable".

If I'm correct, what you're asking for is "erase in *all* scopes"?

I'd probably just allow multiple scopes to be specified with `--erase`, so you can do

```fish
set --erase --local --global --universal foo
```

or

```fish
set -elgu foo
```

for short.

**Comment by daveman1010221** [comment]
That sounds great.
