### ISSUE TITLE
fish_config does not work in MacOS 11.2 Chrome or Firefox

### ISSUE THREAD

**Issue by rr326** [fish-shell/fish-shell#7714]
`fish_config` works in Safari, but not Chrome or FireFox on MacOS 11.2.
In Safari, it looks just as it should.
In Chrome:

![Screen Shot 2021-02-14 at 5 07 13 AM](https://user-images.githubusercontent.com/1766391/107877675-bec02780-6e82-11eb-95db-116e2e8bbf7f.png)

No errors in developer console or network tabs. 

Same thing in FireFox.

I'm fine since I can use Safari, but I thought you should know. Happy to help debug.

# Environment
```
fish, version 3.1.2
Darwin xxx-imac-pro-7.localnet 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
xterm-256color
Could not do `sh -c 'env HOME=$(mktemp -d) fish'` - some other bug in my system, but this is a brand new fish install.
```

**Comment by zanchey** [comment]
Do you get any output on the terminal where you started `fish_config` from?

**Comment by rr326** [comment]
```/U/r/dev> fish_config
Web config started at file:///var/folders/yq/6wyn6yg100s6pgkfg2vtnr_80000gn/T/web_configs18ibs7m.html
Hit ENTER to stop.
$ set -L
```
Also, a ton of code gets echoed to the terminal every time I click on a new tab - like it's echoing locally. Not sure if that's abnormal.

**Comment by ridiculousfish** [comment]
I am seeing Chrome hang (!!) when exiting the variables tab on macOS 11.1, Chrome 88. A sample shows it is spending all of its time in `memmove`. It occurs in fish 3.1.2 as well.

This is probably a recent regression in Chrome, since I am sure we would have caught it by now. This may or may not be the same problem.

**Comment by ridiculousfish** [comment]
@rr326 I was not able to reproduce with fish 3.1.2 on macOS 11.2.1 with Firefox, Chrome, or Safari. Can you please check if the tabs (Prompt, Functions, etc) work? Is it possible you have a stylesheet which is taking precedence, or maybe an extension?

**Comment by jorgebucaran** [comment]
This could be related to https://github.com/microsoft/vscode/issues/100840, https://github.com/adobe-fonts/source-code-pro/issues/250, and the fix was to re-install Source Code Pro on macOS from here: https://github.com/adobe-fonts/source-code-pro/releases.

**Comment by faho** [comment]
Yeah, that's the problem. On our end the best we can do is 768defeb8ed0c5c4db30c956c225726a5d0a01db - not setting a specific font to try to avoid the Source Code Pro bug.

**Comment by rr326** [comment]
I can confirm that it is indeed the color of the font that is the problem. (And yes, the tabs all work.)  It sounds like you guys have it figured out.

**Comment by faho** [comment]
In that case I don't see anything else for us to do - we can only give the browser the html to render, and we can't really do anything about it misrendering it.

We'll try to not explicitly request the known-buggy font, but  as far as I know there isn't a way to say "anything monospace *except* source code pro", and the real solution is for the font to be fixed.

**Comment by ridiculousfish** [comment]
Awesome find @jorgebucaran
