### ISSUE TITLE
Always show pager for complete with one letter search and one result?

### ISSUE THREAD

**Issue by RobertMueller2** [fish-shell/fish-shell#7715]
Using Debian Bullseye 
tried with uxrvt and xterm, no difference
fish from distribution package, version 3.1.2, and I tried with  sh -c 'env HOME=$(mktemp -d) fish', no difference to my profile.

Imagine a directory with the following content:

```
user@host /h/r/t/y> ls
Backup/  Oldbackup/  Work/  y.stuff.txt
```

I noticed this because I *thought* I am actually in the directory Backup which has a subdirectory debian, that I wanted to complete with tab. So I type cd d *TAB* and get:

`user@host /h/r/t/y> cd Oldbackup/`

OK, I get it, for "d" there really is only one match where I am. But I think one letter matches anywhere in the word aren't great for arguments, especially when there's only one result. I think the chance that I did something wrong is way higher than me wanting to do that kind of search. So maybe if it displayed the pager for 1 result for 1 letter search would be better in slowing me down from pressing enter rather than completing it?

Or I guess I could get used to use more of forward-word but that seems to have other disadvantages...

What do you think?

p.S.:
I'm almost tempted to also use the example directory above to enter rm t *TAB* which results in 
`user@host /h/r/t/y> rm y.stuff.txt`
but I'm guessing that's what one has backup for. ;-)

**Comment by faho** [comment]
This is a case where it's better to ask for forgiveness than permission - the upcoming 3.2 has undo support, and you can just undo accepting the completion, which is the same number of keystrokes as accepting it would be, and *less* if you actually want it.

As a special case pressing escape directly after accepting a completion also undoes it, so you can just slam the cancel key.

So I don't think this is needed.
