### ISSUE TITLE
Unable to source a file in config.fish if the path contains a dash "-"

### ISSUE THREAD

**Issue by taranjlu** [fish-shell/fish-shell#7716]
#### Problem:
I have a .fish file in a path that has a dash in its name. If I try to source the file via my `~/.config/fish/config.fish` file, it fails and acts as though the file does not exist:
```
source: Error encountered while sourcing file “/home/taran/tl/src/git/github/another-with-a-dash/test.fish”:
source: No such file or directory
```
I am able to source the file from the command line using `source /home/taran/tl/src/git/github/andother-with-a-dash/test.fish`. Interestingly, if I try to copy the filepath text from the error message, fish rejects that, so I am wondering if there is some non-printing character that is getting inserted.

##### Environment:
- fish version: 3.1.2
- Fedora 33
- `$TERM` = xterm-256color

**Comment by faho** [comment]
Well, what's your exact line in config.fish?

Can you try retyping it in there? I'm thinking some whitespace or non-printing character got in *there*.

**Comment by taranjlu** [comment]
My bad, I was using an env var in the path, and it was missing a slash.

**Comment by taranjlu** [comment]
It does seem odd that it reports the correct, full path in the error though. That path that I originally posted is a valid path.

**Comment by faho** [comment]
I guess we can make the error include an *escaped* path, so e.g. if you had a tab character it would use `\t`.

What I need from you, @taranjlu, is a way to reproduce your problem. You seem to have reduced it too much so I can't confirm your findings - when I `source` something in config.fish it either works (if the path is valid) or doesn't, I can't find a way to have an error like this.

Also please note that localization adds fancy quote chars here, so if you copy `“/home/taran/tl/src/git/github/another-with-a-dash/test.fish”` with the quotes fish will interpret your path as starting in the `“` directory because `“` isn't a quote to fish. I'd have to check if this is down to the localized strings having fancy quote marks or localization being too smart for its own good.

**Comment by taranjlu** [comment]
So, I managed to get it to happen again with this config:
```fish
# Set Homebrew environment
set -gx HOMEBREW_PREFIX "/home/linuxbrew/.linuxbrew"
set -gx HOMEBREW_CELLAR "/home/linuxbrew/.linuxbrew/Cellar"
set -gx HOMEBREW_REPOSITORY "/home/linuxbrew/.linuxbrew/Homebrew"

set -l homebrew_paths "/home/linuxbrew/.linuxbrew/bin" "/home/linuxbrew/.linuxbrew/sbin" 
for i in $homebrew_paths[-1..1]
    if not contains $i $fish_user_paths
        set -U fish_user_paths $i $fish_user_paths
    end
end

if not contains "/home/linuxbrew/.linuxbrew/share/man" $MANPATH
    set -gx MANPATH "/home/linuxbrew/.linuxbrew/share/man" $MANPATH
end

if not contains "/home/linuxbrew/.linuxbrew/share/info" $INFOPATH
    set -gx INFOPATH "/home/linuxbrew/.linuxbrew/share/info" $INFOPATH
end

# Setup asdf
# NOTE: Currently using source version because is broken for brew on linux
source $TL_ROOT_DIR_PATH/src/git/github/adsf-vm/asdf/test.fish
```
And this is what I have for `TL_ROOT_DIR_PATH`:
```
❯ echo $TL_ROOT_DIR_PATH
/home/taran/tl
```
For some reason, I am unable to query information about that variable though:
```
❯ set -q TL_ROOT_DIR_PATH

```
And this is what it's entry looks like in my `fish_variables` file:
```
❯ head fish_variables 
# This file contains fish universal variable definitions.
# VERSION: 3.0
SETUVAR --export --path TL_ROOT_DIR_PATH:/home/taran/tl
SETUVAR ZO_CMD:zo
SETUVAR Z_CMD:z
SETUVAR Z_DATA:/home/taran/\x2elocal/share/z/data
SETUVAR Z_DATA_DIR:/home/taran/\x2elocal/share/z
SETUVAR Z_EXCLUDE:\x5e/home/taran\x24
SETUVAR __fish_initialized:3100
SETUVAR _fish_abbr__2E_2E_2E_:\x2e\x2e/\x2e\x2e
```
I'm pretty sure in the past I have been able to query information about variables...

**Comment by faho** [comment]
>For some reason, I am unable to query information about that variable though:

`set -q` only returns true/false depending on whether the variable is set. You want `set --show TL_ROOT_DIR_PATH`.

**Comment by taranjlu** [comment]
Could this have something to do with the fact that the env var ends with `PATH`? Also, since the error still shows up with this config, I don't think it was actually an issue of a missing slash.

**Comment by taranjlu** [comment]
This is what I get for `set --show TL_ROOT_DIR_PATH`:
```
 set --show TL_ROOT_DIR_PATH
$TL_ROOT_DIR_PATH: not set in local scope
$TL_ROOT_DIR_PATH: not set in global scope
$TL_ROOT_DIR_PATH: set in universal scope, exported, with 1 elements
$TL_ROOT_DIR_PATH[1]: length=14 value=|/home/taran/tl|


```

**Comment by faho** [comment]
>Could this have something to do with the fact that the env var ends with PATH?

The variable name ending in "PATH" makes it a "path variable", which means that it's implicitly split on `:`. But that doesn't seem to be happening here, given that there's no `:` anywhere.

**Comment by faho** [comment]
Okay, does this still reproduce for you when you remove all that homebrew gunk?

If you just have

```fish
# Setup asdf
# NOTE: Currently using source version because is broken for brew on linux
source $TL_ROOT_DIR_PATH/src/git/github/adsf-vm/asdf/test.fish
```

In your config?

Does it reproduce if you move it to, say, `$TL_ROOT_DIR_PATH/asdf-vm/asdf/test.fish`?

**Comment by taranjlu** [comment]
Sill get the same error with only that in `config.fish`. Will test moving the file as well.

**Comment by taranjlu** [comment]
Ugh, I see it now. I have a typo. The dir should be `asdf-vm` not `adsf-vm`.

**Comment by taranjlu** [comment]
@faho Thanks for helping me debug that. Sorry for the silly issue.
