### ISSUE TITLE
Is interning of much use?

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#7717]
Fish has had, since at least 2005, the time when it was written in C and stored in darcs, "intern.c".

This allows for "string interning", i.e. storing commonly-used strings so you can compare them by just checking a pointer instead of doing a full str/wcscmp.

However, it's currently only used to store the *filename* of the currently running file and to store the builtin names.

Previously it also used to store the binding sequences and bind function names, but we now use a binary search for that.

My guess is that none of this is looked up enough to warrant the complexity, so I would like for us to investigate it and if I'm correct remove the interning code entirely.

Alternatively, if it is of any use, it should probably be used a lot more.

**Comment by ridiculousfish** [comment]
The intention is that, if you have a large file with a lot of blocks/functions, we can just intern the filename, so there is only one copy of it in memory. It's probably not carrying its weight, but neither is it causing any problems. I don't object to removing it.

My dream fix would be a replacement for `wcstring` which can be efficiently shared without copying, and can also reference string literals - I think #5268 has some discussion of that.

**Comment by floam** [comment]
There used to be a thing where fish would "internalize" functions needed to bootstrap - at compile time certain scripts would get cooked in. I forget exactly how. Did that machinery use any of this?

**Comment by ridiculousfish** [comment]
I wrote the "internalized" functions to try to improve fish startup performance. Today startup seems very fast to me so I don't see a need to internalize functions.

**Comment by floam** [comment]
Startup speed isn't what I was really thinking of - to me it's kind of interesting to potentially compile in a handful of the most essential functions such that a `fish` binary can just always work without any functions path on a system. Might make the binary a tiny bit bigger, but do it right and if it's all in the __TEXT segment (rodata for ELF) that's probably actually some kind of RAM savings given a bunch processes running at once. Hardwired functions also can magically can have their completion descriptions in place without autoloading.

I was looking at https://github.com/graphitemaster/incbin with some interest.

`fish --help` can't actually even print usage information if the man pages aren't installed or the MANPATHs all set just right with proper tooling..: I'm kind of laos intrigued by the idea of  internalizing roff or even just rendered SGR/mancat output to make `--help` on builtins bulletproof as an optional compilation step.

**Comment by faho** [comment]
2a0e0d67214aa45493e2f7b1782f672164fb8bc4

**Comment by floam** [comment]
> compile in a handful of the most essential functions such that a monolithic fish binary can just always work without any functions path on a system. It'll make the binary bigger, but if it's all in the __TEXT segment / .rodata that's probably actually some kind of RAM savings given a bunch processes running at once. Hardwired functions also can magically can have their completion descriptions in place without autoloading.


> fish --help can't actually even print usage information if the man pages aren't installed or the MANPATHs all set just right with proper tooling..: I'm kind of laos intrigued by the idea of internalizing roff or even just rendered SGR/mancat output to make --help on builtins bulletproof as an optional compilation step.

NARRATOR: Years later, @floam was delighted to find the long dormant, excised, and forgotten feature restored.

#10367 intermalized… er, "embedded" the data,  but worked by a head scratcher of a mechanism extracting it to disk first. 

#11143 finally restored the good behavior of the before times: fish reads its functions, completions, manpages, and other internal data directly from the binary as a real single-file executable.
