### ISSUE TITLE
fish_config breaks when using ipconfig.exe in config.fish (WSL2)

### ISSUE THREAD

**Issue by vatsal22** [fish-shell/fish-shell#7719]
fish --version
  `fish, version 3.1.2`

 uname -a
`Linux DESKTOP-RESLM1H 4.19.128-microsoft-standard #1 SMP Tue Jun 23 12:58:10 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:

  sh -c 'env HOME=$(mktemp -d) fish'

Yes, it's reproducible without any plugins.

Issue:

I'm using ipconfig.exe to set my DISPLAY for xserver in config.fish. It works but ends up breaking 
fish_config:
![image](https://user-images.githubusercontent.com/13476564/107991281-4a7da500-6fa4-11eb-8528-5f5725fac304.png)

None of the tabs (prompt, functions ...) work or are responsive.

I can resolve this by not using ipconfig.exe, but then I can't automatically set my DISPLAY on startup.

Steps to reproduce (using Ubuntu WSL2):

1. Add the following to config.fish:
```
set wsl2_d_tmp (ipconfig.exe | grep -n -m 1 "Default Gateway.*: [0-9a-z]" | cut -d : -f 1)
set first_line (expr $wsl2_d_tmp - 4)
set wsl2_d_tmp (eval ipconfig.exe | sed $first_line,$wsl2_d_tmp!d | grep IPv4 | cut -d : -f 2 | sed -e "s|\s||g" -e "s|\r||g")
set -g --export DISPLAY "$wsl2_d_tmp:0"
```
2. Open new fish shell and run fish_config

**Comment by faho** [comment]
> fish, version 3.1.2

Please confirm it's 3.1.**2**, Ubuntu only ships 3.1.**0**.

-----

So which line here is the culprit? Is setting $DISPLAY the problem, or is it actually running `ipconfig.exe`?

Does `ipconfig.exe` print anything to stderr? fish_config works by running a fish in the background to provide e.g. the prompt output and such, and that will also run your config, so if that prints anything else it'll break.

**Comment by vatsal22** [comment]
Yes, I'm using 3.1.2. I used both `fish --version` and `echo $version` .

I stripped down the config.fish and now it only contains:
`set tempvar (ipconfig.exe)`

This also reproduces the issue so I think the problem is with actually calling ipconfig.exe. I tried that line in a prompt and it doesn't print anything. I also tried `set tempvar (ipconfig.exe) 2>/dev/null` but it didn't help.

**Comment by faho** [comment]
>I also tried set tempvar (ipconfig.exe) 2>/dev/null but it didn't help.

Put the `2>/dev/null` *inside* the parentheses.

**Comment by vatsal22** [comment]
This doesn't work either: `set tempvar (ipconfig.exe 2>/dev/null)`

**Comment by faho** [comment]
Try putting it inside a `status is-interactive` block:

```fish
if status is-interactive
   # do the ipconfig stuff
end
```

I'm guessing this is ipconfig.exe not being native and therefore messing with the terminal or something.

**Comment by vatsal22** [comment]
Yep that fixed it. Thanks for the help!
