### ISSUE TITLE
Handler for --on-job-exit $fish_pid runs constantly

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#7721]
As reported on gitter by @scorphus, another for the "fixed by status job-control full" (#5036) pile:

```fish
function on-exit --on-job-exit $fish_pid
    echo on-exit
end
```

Run this interactively and it will trigger constantly - presumably whenever you run the prompt or similar.

This is presumably because the prompt doesn't have "job-control" enabled and therefore runs with fish's pgroup.

While on-job-exit doesn't make sense here, it shouldn't trigger constantly.

**Comment by mqudsi** [comment]
Fixed in https://github.com/fish-shell/fish-shell/commit/e7398c0248ccf1240c65ffe2f6f37ab634ec2337 but I fat-fingered the commit message and it auto-closed the wrong issue.

**Comment by scorphus** [comment]
Thanks, @mqudsi
