### ISSUE TITLE
Multi-line prompts are misbehaving on HEAD

### ISSUE THREAD

**Issue by shlemas** [fish-shell/fish-shell#7722]
I installed a dev version of fish with Homebrew a few weeks ago for the Big Sur tab completion performance fixes, and it's been causing an issue with my multi-line prompt spuriously reprinting when I use the up/down arrow keys to browse command history. Since it hasn't gone away I thought I'd open an issue.

Steps to reproduce:

1. Modify the default fish prompt to echo a newline before the suffix character. (Alternatively, set your prompt to any of the multi-line prompts offered by `fish_config`.)
2. With the new prompt active, press the up/down arrow keys to browse command history.

Every time you press up or down, the first line of the prompt should be spuriously output, so your terminal will start to look like:

    me@iMac ~
    me@iMac ~
    me@iMac ~
    me@iMac ~
    me@iMac ~
    me@iMac ~
    me@iMac ~
    >

Reproduces in iTerm and Terminal.app.

This doesn't affect single-line prompts.

Other info:

    > fish --version
    fish, version 3.1.2-2123-g00fabb4fe

    > uname -a
    Darwin iMac.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

**Comment by faho** [comment]
First of all, please confirm that it reproduces with this prompt and no other customization (inside a fish started with `XDG_CONFIG_HOME=(mktemp -d) fish`):

```fish
function fish_prompt
    echo one
    echo two
end
```

Secondly: What's your $TERM?

**Comment by shlemas** [comment]
Sorry for not doing that to begin with. New reproduction steps: do what you just said, and then also do:

`set -U fish_color_normal white`

That single variable set to anything but `normal` in my `fish_variables` seems to cause this issue. Weird.

    > echo $TERM
    xterm-256color

**Comment by faho** [comment]
Interesting. What does

```fish
set_color $fish_color_normal | string escape
```

print?

**Comment by shlemas** [comment]
> set_color $fish_color_normal | string escape
    \e\(B\e\[m
    > set -U fish_color_normal white
    > set_color $fish_color_normal | string escape
    \e\[37m
    > set -U fish_color_normal red
    > set_color $fish_color_normal | string escape
    \e\[31m
    > set -U fish_color_normal normal
    > set_color $fish_color_normal | string escape
    \e\(B\e\[m

**Comment by faho** [comment]
Huh, that's just the typical white sequence, and that works for me.

How do you have your color variables set now?

```fish
set | grep '^fish_color'
```

should provide that information.

**Comment by shlemas** [comment]
A couple of these might not be stock fish color variables, but these are my usual colors:

```fish
> set | grep '^fish_color'
fish_color_autosuggestion brblack
fish_color_cancel --reverse
fish_color_command blue
fish_color_comment brcyan
fish_color_cwd 'cyan'  '--bold'
fish_color_cwd_root 'red'  '--bold'
fish_color_duration 'yellow'  '--bold'
fish_color_end magenta
fish_color_error red
fish_color_escape 'cyan'  '--bold'
fish_color_history_current --bold
fish_color_host 'white'  '--bold'
fish_color_host_remote 'yellow'  '--bold'
fish_color_match --background=blue
fish_color_normal white
fish_color_operator 'white'  '--bold'
fish_color_param cyan
fish_color_quote green
fish_color_redirection cyan
fish_color_search_match 'yellow'  '--background=white'
fish_color_selection 'white'  '--bold'  '--background=white'
fish_color_status 'red'  '--bold'
fish_color_user 'yellow'  '--bold'
fish_color_user_root 'red'  '--bold'
fish_color_valid_path --underline
```

And then when running the more minimal reproduction steps above (with temp XDG_CONFIG_HOME and setting fish_color_normal to white):

```fish
> set | grep '^fish_color'
fish_color_autosuggestion '555'  'brblack'
fish_color_cancel -r
fish_color_command 005fd7
fish_color_comment 990000
fish_color_cwd green
fish_color_cwd_root red
fish_color_end 009900
fish_color_error ff0000
fish_color_escape 00a6b2
fish_color_history_current --bold
fish_color_host normal
fish_color_host_remote yellow
fish_color_normal white
fish_color_operator 00a6b2
fish_color_param 00afff
fish_color_quote 999900
fish_color_redirection 00afff
fish_color_search_match 'bryellow'  '--background=brblack'
fish_color_selection 'white'  '--bold'  '--background=brblack'
fish_color_status red
fish_color_user brgreen
fish_color_valid_path --underline
```

And then for kicks I erased them all except:

```fish
> set | grep '^fish_color'
fish_color_normal white
```

That exhibits the bad behavior. As soon as I also delete that variable, the bad behavior is gone.

**Comment by faho** [comment]
Alright, I can't reproduce this and I'm out of ideas. And since I don't have a mac to see if it's macOS-specific, I can only ask

- either for someone else to confirm this
- or for you to `git bisect` it, if you're up for it. 80aaae5b74eaadbb0cc563648b9af53d715f94e2 is a likely commit to introduce this, so building it and its parent would already be of use.

**Comment by shlemas** [comment]
80aaae5 worked so I started a bisect from there.

It pinpointed 5f16a299a728f1ad5a8c533fb49276aa97612d9e

I double checked it and its parent and yeah, that commit seems to be the culprit.

**Comment by faho** [comment]
Okay, what does `stty -a` say?

**Comment by faho** [comment]
Alright, please try `stty -ixany -ocrnl -ofdel -ofill -olcuc oxtabs`.

**Comment by shlemas** [comment]
I don't appear to have `-olcuc` or an equivalent:
```
> stty -ixany -ocrnl -ofdel -ofill -olcuc oxtabs
stty: illegal option -- -olcuc
usage: stty [-a|-e|-g] [-f file] [options]
```

I can remove it:
```
> stty -ixany -ocrnl -ofdel -ofill oxtabs
```

```
> stty -a
speed 38400 baud; 45 rows; 80 columns;
lflags: icanon isig iexten echo echoe echok echoke -echonl echoctl
        -echoprt -altwerase -noflsh -tostop -flusho pendin -nokerninfo
        -extproc
iflags: -istrip icrnl -inlcr -igncr -ixon -ixoff -ixany imaxbel iutf8
        -ignbrk brkint -inpck -ignpar -parmrk
oflags: opost onlcr oxtabs onocr onlret
cflags: cread cs8 -parenb -parodd hupcl -clocal -cstopb -crtscts -dsrflow
        -dtrflow -mdmbuf
cchars: discard = ^O; dsusp = ^Y; eof = ^D; eol = <undef>;
        eol2 = <undef>; erase = ^?; intr = ^C; kill = ^U; lnext = ^V;
        min = 1; quit = ^\; reprint = ^R; start = ^Q; status = ^T;
        stop = ^S; susp = ^Z; time = 0; werase = ^W;
```

No difference in behavior.

**Comment by zanchey** [comment]
I can reproduce this locally on macOS 10.14 using Terminal.app.

**Comment by ridiculousfish** [comment]
Me too, confirmed the bisect to 5f16a299a728f1ad5a8c533fb49276aa97612d9e. I'll take a look.

**Comment by ridiculousfish** [comment]
We're switching the tty color back to normal before running key bindings, which is messing with the tty's timestamp, so we think the tty has been changed and redraw the prompt. I'll have a fix shortly.

**Comment by ridiculousfish** [comment]
Thank you for filing and bisecting, really glad we caught this before release!

**Comment by shlemas** [comment]
Just confirming that this is indeed now fixed for me. Thanks!
