### ISSUE TITLE
End of options

### ISSUE THREAD

**Issue by tobiaskarnat-remondis** [fish-shell/fish-shell#7726]
### System information:
  fish, version 3.1.0
  Ubuntu 20.04 inside WSL2

### Question:
How do I signify the end of the options? I tried with double dashes but this doesn't always work.

### Example:
```
> kill -- -94
kill: (-98): No such process

# Less than 94 doesn't parse correctly.
> bash -c 'kill -- -93'
bash: line 0: kill: (-93) - No such process
> kill -- -93

Usage:
 kill [options] <pid> [...]
...
```

**Comment by faho** [comment]
Bash has a kill builtin, fish just executes the command.

Whatever kill command you are using apparently doesn't support this convention and you'll have to look at its documentation - check `man kill`.

**Comment by tobiaskarnat-remondis** [comment]
This seems to be a bug in the procps-ng package. As an alternative to kill process groups this works
```
pkill -g 93
```
