### ISSUE TITLE
Running ZSH scripts with Fish shell (ros environments)??

### ISSUE THREAD

**Issue by ShivamPT4I21** [fish-shell/fish-shell#7727]
Hi all! I am new to `fish-shell` even just thinking about the advantages over the `zsh-shell`. 

I am just curious about using fish-shell with ros presently ros supports zsh and bash, so I am interested if there is a method of sourcing the generated .zsh/.sh/.bash files to set the environment variables.

Target OS: Ubuntu 20.04
Terminal Emulator: Alacritty/Terminator

**Comment by faho** [comment]
No. Fish is not compatible with zsh, bash or other posix shells.

**Comment by zanchey** [comment]
There are a couple of approaches:
- Start bash, source the ros .bash file, then `exec fish`
- Use a converter of some kind eg https://github.com/edc/bass to load the bash script into fish - there are some limitations but it works well for most scripts.

**Comment by ShivamPT4I21** [comment]
@zanchey thanks for the suggestion, I think the 1st one is working so the possible work that could be done here is adding an extra line in `~\.zshrc` to run the `fish` by default.
