### ISSUE TITLE
How to trigger direnv after switching directory via keybinding

### ISSUE THREAD

**Issue by noib3** [fish-shell/fish-shell#7729]
OS: NixOS 20.09
Fish version 3.1.2

I have the following function that finds all the directories in my home folder, passes them to fzf, cd's into the one I chose and repaints the prompt:
```fish
function fuzzy_cd
  set -l dirname (fd --base-directory=$HOME --type=d | fzf) \
    && cd $HOME/$dirname
  commandline -f repaint
end
```
this generally works fine, but if bind this to some key and use it to cd into a directory where direnv is active (i.e. there's a `.envrc` file in it), I find that direnv doesn't get triggered right away. Instead I need to press enter for it to activate. If I call the function explicitely via `fuzzy_cd` instead of with a key binding direnv gets triggered correctly.

Any ideas on how to solve this?

**Comment by ridiculousfish** [comment]
It looks like direnv [uses the fish_prompt event](https://github.com/direnv/direnv/blob/e0d2ae8509de438d1db44ac7c584969780065142/shell_fish.go#L14) which fires every time the prompt executes. Running a key binding does not re-execute the prompt so the event won't fire.

A dirty hack is to manually emit the fish_prompt event - does this work for you?

    	function fuzzy_cd
	  set -l dirname (fd --base-directory=$HOME --type=d | fzf) \
	    && cd $HOME/$dirname
	  emit fish_prompt
	  commandline -f repaint
	end

**Comment by noib3** [comment]
@ridiculousfish Nope, even after adding `emit fish_prompt` to the function direnv still doesn't trigger if I execute that via a key binding.
