### ISSUE TITLE
Is there an equivalent of the 'disown' command?

### ISSUE THREAD

**Issue by theonewolf** [fish-shell/fish-shell#773]
Does fish have support for 'disown'ing a process?

See: http://www2.research.att.com/~gsf/man/man1/disown.html

**Comment by jonhoo** [comment]
Following the change introduced by #3497, it looks like this behavior no longer works as expected. Even a job that is explicitly `bg`'d will be terminated upon exit.

**Comment by krader1961** [comment]
Yes, @jonhoo, that is the case. Until issue #2810 is addressed `nohup` is your friend if you don't want backgrounded jobs to be killed by SIGHUP when you exit your interactive shell. Alternatively, use the double-fork trick. In bash you would do `(sleep 123 &)` but fish doesn't support that syntax so you need to do `fish -c 'sleep 123 &'`.

**Comment by jonhoo** [comment]
@krader1961 yeah, that's what I'm using instead for now, but it's pretty inconvenient. Also, the messages aren't exactly helpful:
```console
$ nohup sleep 20 &
nohup: ignoring input and appending output to 'nohup.out'
$ ^D
There are still jobs active (use the jobs command to see them).
A second attempt to exit will terminate them.
```
When in fact a second attempt *won't* terminate them, it'll send a `SIGHUP`, which *may* terminate them.
