### ISSUE TITLE
`echo "foo$"` => "fish: Expected a variable name after this $."

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#7736]
Bash handles this special case correctly, but fish complains.

I understand I can single-quote the string, but it feels more correct for fish to handle a sole `$` followed by any character that is invalid for a variable as a literal `$` rather than as a variable, e.g.

### Actual

```
$ echo "foo $ bar"
fish: $  is not a valid variable in fish.
echo "foo $ bar"
```

### Expected
```
$ echo "foo $ bar"
foo $ bar
```

**Comment by faho** [comment]
We typically follow the idea of erroring when something looks wrong, e.g. why we error on `$'` or `$$`.

I don't think it's worth breaking this here - `$` in double-quotes are expanded, so you need to escape them or use single-quotes when you don't want that.

**Comment by faho** [comment]
Okay, after further thinking, I'm rejecting this.

The reason is that

```fish
echo "foo $ bar"
```

could easily be a typo for

```fish
echo "foo $bar"
```

And that seems *more* likely than a literal `$` being required here.

**Comment by zx8** [comment]
Ok, that's reasonable, but please also consider that `$` is often used as a terminating character for regular expressions, so I get stung by `"foo$"` a fair amount, then hang to backtrack to escape it.

Would you perhaps consider this as a special case?

**Comment by IlanCosman** [comment]
I agree that it can be a bit annoying while working with regexes, but that's why I almost always just use single quotes unless double quotes are really necessary.

**Comment by zx8** [comment]
@faho Apologies for pinging you directly, but I'm not sure if you receive notifications for closed issues.

Would you consider special-casing `"foo$"` at all?

**Comment by faho** [comment]
>Would you consider special-casing "foo$" at all?

I don't think so.

Like I said, I don't think it's worth breaking the rule especially when it could just be a typo.

`$` are special when un- or double-quoted, if you want to use them literally use single-quotes or escaping.

**Comment by krobelus** [comment]
Consistency makes the language easier to learn, and if we can report potential errors early, we should. The time it takes to act on the error is much less than the time it takes to debug it. It's probably not a common error but who knows.

You could use a bind function that inserts the backslash automatically.
Or use a hook to correct it:

```fish
function escape-trailing-dollar --on-event fish_posterror
    commandline -- (commandline | sed 's/\$"/\\\\$"/g')
end
```

**Comment by zx8** [comment]
Ha, very creative @krobelus – adding this to my fish config right away.

Out of curiosity, is there a way to access the error message itself inside the `fish_posterror` handler function?

**Comment by krobelus** [comment]
(the regex is slightly off, it doesn't handle already-escaped characters)

> Would it be possible to include the error message as the second parameter perhaps?

If there is a use for it, sure. Maybe the interface should be more flexible - a `string parse` or `status check-syntax` command could be used to detect fishscript errors on arbitrary strings.
