### ISSUE TITLE
cross-compiling and try_run error

### ISSUE THREAD

**Issue by etcusrvar** [fish-shell/fish-shell#7737]
While doing a trial build of the preliminary 3.2.0 release, I had a minor hiccup when cross-compiling (for Synology devices).

```
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   mbrtowc_invalid_utf8_exit (advanced)
```

https://github.com/fish-shell/fish-shell/blob/2cf5fd3d5dd20035d694f4f5116cf5bd48765cd1/cmake/ConfigureChecks.cmake#L232

I was able to build fine with a `-Dmbrtowc_invalid_utf8_exit=0` cmake arg, and the resulting build seems to work fine on my Synology device.

The [cmake docs](https://cmake.org/cmake/help/latest/command/try_run.html#behavior-when-cross-compiling) say to `use try_run only if really required`. As this is the only instance of try_run in all of fish's cmake files, it seems to me like this instance also may be worked around without the try_run. But I'm not sure.

As this is not a show-stopper for releasing 3.2.0, it seemed more appropriate to open a separate issue instead of commenting on #6585.

**Comment by faho** [comment]
Yeah, I made it only trigger `IF(APPLE)`, since that's where it fails (I'm typically a fan of feature-testing, but given that the feature test is annoying and this only ever triggered on macOS this seems acceptable).
