### ISSUE TITLE
Investigate backgrounding of initial python job

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#7739]
I'm on a remote terminal to a Solaris instance trying to fix those build issues so I'm logging this here for further investigation prior to the 3.2.0 release since as I recall this was supposed to be fixed:

![image](https://user-images.githubusercontent.com/606923/108878831-3e0dd380-75c6-11eb-9faa-adaebba788fd.png)

**Comment by faho** [comment]
This should be disowned:

https://github.com/fish-shell/fish-shell/blob/ffa24eb3610dc2853c1a468b8aa2fd327cd0d3fa/share/functions/__fish_config_interactive.fish#L95-L97

I'm not sure why it's not working, possibly "interactive" job control again.

(but yes, it *should* be backgrounded - this one takes a while and we don't want to have people wait)

**Comment by faho** [comment]
To be clear: Either way I don't believe this is critical enough to hold up the 3.2 release.

**Comment by mqudsi** [comment]
I only bring up 3.2.0 because the changelog says (or at least should say) that this was fixed, so either this gets fixed or the changelog should drop mention.

**Comment by faho** [comment]
Alright, removed it from the CHANGELOG - the fix is most likely setting job-control to full, which we're already planning *for 3.3*.

**Comment by mqudsi** [comment]
I don't think this has anything to do with the job control mode, because the initial instance is started with interactive job control mode.

**Comment by faho** [comment]
Unlike one would expect, the "interactive" in interactive job control doesn't refer to fish being interactive, but the job being in an interactive "context".

This one, because it's triggered while `source`ing a file, isn't.

**Comment by mqudsi** [comment]
Ah. That does make sense.

**Comment by faho** [comment]
Alright, there's a way around this.

The problem here is that $last_pid is fish's pid (pgid actually) because of the job control stuff, and we run `disown $last_pid` so it tries to disown fish, which predictably does nothing.

So we can just not do that.

It also means this was broken in 168677f8b354485b656897bf43a387f8a3e3aa75, working before.
