### ISSUE TITLE
Regression in post-completion behavior

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#7740]
It seems that there's some state left over from when the completions are being generated that swallows a ctrl-c after a completion, e.g.

```
$ catj<space><c-c>
```

triggers the "abandon prompt" binding and either clears the line or posts `^C` to the prompt and starts a new one, but 

```
$ catj<tab><c-c>
```

does nothing but requires another `^C` to trigger the abandon prompt binding.

This is triggered by performing any completion that resolves to and automatically self-completes a single value, e.g. in my case, `catj` is a known command and there are no other commands that start with `catj` so it is automatically accepted. If you have no command besides `foobar` that starts with `foo` and then you typed in `foo<TAB>` you would run into this behavior.

**Comment by faho** [comment]
Works for me, what's your binding?

**Comment by mqudsi** [comment]
This bisects to d334dc6643cdf146fb41ed8312deb44d7e3673fb

My completion is the old one that dropped the prompt contents,

```
> bind \cc
bind --preset \cc cancel-commandline
bind \cc 'commandline -f cancel; commandline ""'
```

**Comment by faho** [comment]
Ah, okay, that's the queue stuff biting us again.

I *think*:

- The commandline is set to empty first
- Then `cancel` runs, and still thinks you just accepted a completion, so it undoes the last change - which was emptying the commandline

**Comment by faho** [comment]
@mqudsi Please try e59aab0

**Comment by mqudsi** [comment]
That seems to work, at least at a cursory glance. I was trying to figure out if we could use the undo groups created on binding invocation to work around the function order, but that all broke down when cancel wasn't the last operation in the group.

**Comment by faho** [comment]
@zanchey e59aab0 should probably be in 3.2, unless someone finds something wrong with it.
