### ISSUE TITLE
Invalid unicode in autocomplete breaks prompt

### ISSUE THREAD

**Issue by fennewald** [fish-shell/fish-shell#7745]
fish version 3.1.2
Kitty on macos silicon
Tried with blank conf file

entering the command `echo "🯈"` breaks the autocomplete. In my screenshot, I ran the command `echo  "🯈"` as it appeared, and on the newline, I typed the letters `e`, `c`, `h`, `o` only. The autocomplete prompt instead filled in the prompt with the weirdly highlighted nonsense. If I hit enter, it will run the command `echo` without any arguements, so the autocomplete doesn't actually change the command, but it still clearly messes things up.
![Screen Shot 2021-02-26 at 3 32 46 AM](https://user-images.githubusercontent.com/23765149/109276000-79391e00-77e3-11eb-97ce-25a236355c7c.png)

Aditionally, using arrows to navigate back to the original `echo  "🯈"` command in history produces the command `eecho  "🯈"` (no typo), but this command behaves like `echo  "🯈"` when run.

**Comment by faho** [comment]
Try 


```fish
set -g fish_ambiguous_width 1
```

See also https://github.com/fish-shell/fish-shell/blob/master/doc_src/faq.rst#im-getting-weird-graphical-glitches-a-staircase-effect-ghost-characters

**Comment by faho** [comment]
Okay, I tested it in kitty 0.19.3 on linux and that works, so it's either a bug or misconfiguration in your version of kitty or macOS.

Either way, there is little fish can do here - it identifies the width correctly, your terminal mishandles it. The obvious workaround is to use a different character.
