### ISSUE TITLE
fish_title $argv is always set, even when idle

### ISSUE THREAD

**Issue by etcusrvar** [fish-shell/fish-shell#7749]
I'm testing differences between fish 3.1.2 and the soon to be 3.2.0 release.
I noticed an inconsistency with fish_title.

In 3.1.2, if nothing is actively running-- if fish is idle-- the fish_title function is called with no $argv.
This behavior changed as a result of the fix for #7444.
Now, fish_title's $argv always has 2 args. If fish is idle, argv[1] is "fish".

For this issue, the changelog says "Resumed jobs show the correct title in the terminal emulator".
But in the following code, there's no jobs involved, resumed or otherwise.

```
> set d (mktemp -d)
> cd $d
> mkdir -p .config/fish/functions
> echo 'function fish_title
    echo -- -- fish_title: argv="\'$argv\'" >&2
  end' > .config/fish/functions/fish_title.fish
```
```
> # 3.1.2
> sh -c "env HOME=$d fish"
-- fish_title: argv=''
-- fish_title: argv=''
...> <Enter>
-- fish_title: argv=''
-- fish_title: argv=''
...> <Ctrl-D>

> # latest
> sh -c "env HOME=$d ~/fish-shell/fish" 
-- fish_title: argv='fish /tmp/tmp.cUIzsQjjp7'
...> <Enter>
-- fish_title: argv='fish /tmp/tmp.cUIzsQjjp7'
...> <Ctrl-D>
```

I have a `if set -q argv[1] ...` in my $__fish_config_dir/functions/fish_title.fish, and noticed that $argv[1] is now always set, whether the prompt is idle or something is actively running.

I don't know if this is the intended behavior or not. It's just different than expected, and easily worked around.

system: `fish --version`
    fish, version 3.1.2

dev: `~/fish-shell/fish --version`
    fish, version 3.1.2-2165-gaa608a42f

Linux 5.10.17
Same behavior on multiple terminals.

**Comment by zanchey** [comment]
Yeah, I don't think that's on purpose - not sure how easy it is to fix. @mqudsi, any thoughts?

**Comment by faho** [comment]
Weirdly enough a3cb1e2dcd5bc13520c29f61ca615cf5e140db96 solves this *twice*? Once by calling `status current-command` in the default fish_title function, and once by adding it in the *call*?

At this point in the release cycle, I would revert the C++ part of that to avoid changing how custom fish_titles are called. We could reintroduce it later after checking how that's supposed to work, in particular I wouldn't want to pass $PWD as the second argument.

**Comment by mqudsi** [comment]
@faho yes, I needed to add it in both places to support cases where the default was overridden or it wasn't set. Only one of the two was actually called at any given time. I didn't realize or document that external tty emulator integrations would need to be updated accordingly.
