### ISSUE TITLE
bind undo keycode?

### ISSUE THREAD

**Issue by markstos** [fish-shell/fish-shell#7758]
This is a follow-up to the Undo feature added in Fish 3.2.0 by #6570

What do you think about binding the `undo` keycode to this function? It seems like a natural fit. Something like this:

    bind --preset $argv -k undo undo

I see that `--key-names -all` lists `undo` as possible key name:

     bind --key-names --all | grep undo

The "Undo" key code is known to QMK and is programmed into some keyboards:

https://docs.qmk.fm/using-qmk/simple-keycodes/keycodes_basic

The downside to supporting this is the use of the keycode is currently rare, so Fish will be doing a little work to set up a binding that will go unused in most cases.

But for people that do have the `undo` keycode in their keyboards, they will appreciate that one more app supports it, improving the consistency of  triggering `undo` across applications. 

I noticed that `fish --key-names -all` also mentions a "redo" key name. Perhaps this is the same as what QMK refers to as the "Again" key code, with decimal ID of  121 and Hex ID of 79.

**Comment by faho** [comment]
It's not just that the key is *rare*, the keycode not even used in the xterm-256color, xterm-kitty or alacritty terminfo entries. In fact grepping my terminfo database yields 73 supporting entries, including things like "3b1", various "atari" variants and "bsdos-sparc", all used by approximately *nobody*.

That means, until terminals start using it, it is useless and therefore not something suitable as a default. Sorry!

**Comment by zanchey** [comment]
That's amazing.
