### ISSUE TITLE
Control-C to clear the line in Fish 3.2+

### ISSUE THREAD

**Issue by justinmayer** [fish-shell/fish-shell#7765]
Congrats on the new version, everyone! Thank you for all the hard work you put into the Fish 3.2 release. 🎉

After upgrading from Fish 3.1.2 to 3.2.0 via Homebrew on macOS 10.14.6, the workaround suggested by @ridiculousfish to [restore the CTRL-C-to-simply-clear-the-existing-line](https://github.com/fish-shell/fish-shell/issues/3535#issuecomment-259538701) behavior (that was previously the default Fish shell behavior) no longer appears to achieve that goal, and it is not clear how to restore that behavior in Fish 3.2+.

Up until this point, putting the following into `~/.config/fish/functions/__fish_cancel_commandline.fish` would restore the previous clear-the-existing-line behavior:
```fish
function __fish_cancel_commandline
    commandline ""
    commandline -f repaint
end
```

It seems that @faho replaced the `__fish_cancel_commandline` Fish function with a C++ implementation via https://github.com/fish-shell/fish-shell/commit/eb35975c0fdd7420608aa743882c0fc96f3bf585, leaving long-time Fish shell fans who prefer the previous behavior without knowing how to restore that behavior. (But let me clear: I have no doubt that @faho's change was otherwise a significant improvement!)

I tried renaming the above Fish function to `cancel-commandline` or `cancel_commandline`, but that didn't seem to have any effect. (i.e., ` ^C` is appended to the end of the line, and Fish loads another prompt below)

What can one do to restore the _CTRL-C clears the existing line_ behavior?

Refs #4713 #5973 #6937 #7145

**Comment by faho** [comment]
Please show the output of `bind \cc`, most likely it's simply bound to "cancel-commandline", so you just need to rebind it to `__fish_cancel_commandline`:

```fish
bind \cc __fish_cancel_commandline
```

**Comment by justinmayer** [comment]
Many thanks for the very fast response, @faho!

> Please show the output of `bind \cc`

Indeed, as you surmised:
```fish
> bind \cc
bind --preset \cc cancel-commandline
```

Adding `bind \cc __fish_cancel_commandline` to `~/.config/fish/config.fish` did indeed restore the previous behavior. Thank you! I should have known there would be a very easy solution. 😅 

Would you mind too awfully much if I submitted a PR to add a brief [FAQ](https://fishshell.com/docs/current/faq.html) entry that describes this solution? That way folks who prefer it won't have to dig into long-ago-closed issues to find a way to restore the _CTRL-C-clears-the-existing-line_ behavior.

**Comment by faho** [comment]
>Would you mind too awfully much if I submitted a PR to add a brief FAQ entry that describes this solution?

I don't see why not

**Comment by faho** [comment]
Alright, question has been answered.

You can still open that PR if you want, but there's no need to keep this open until then.
