### ISSUE TITLE
Fish changelog is a good novel, but not a good fit for releases/ URL

### ISSUE THREAD

**Issue by rubyFeedback** [fish-shell/fish-shell#7767]
Yo fishy folks,

Fishy is a great shell and idea. I am sure bash and zsh will eventually want to pick up
on what is useful. :D

Anyway, I tried to get the most recent release, and then compile it. I compile everything
from source!

So I go to ...

https://github.com/fish-shell/fish-shell/releases/

And the changelog hits me.

I scroll down ...

I scroll down ...

I scroll down ...

I scroll down ...

Still scrolling!!!

I scroll down ...

I scroll down ...

I scroll down ...

Yep, still scrolling!

I scroll down ...

I scroll down ...

I scroll down ...

I may soon have finished scrolling to the new release ...

No wait, more scrolling.

I scroll down ...

I scroll down ...

Still more scrolling to do ...

I scroll down ...

I scroll down ...

I scroll down ...

Nope, not over yet ...

I scroll down ...

I scroll down ...

FINALLY I come to the new release.

Ok, so my gist here: would it not be better to perhaps integrate this into another page?
Ideally CHANGELOG.md or something.

I assume it is done because it is simple, but it is also super-spammy and for those who
want just the release, at https://github.com/fish-shell/fish-shell/releases/, they have
to scroll down a lot. Not sure of a simple work around. Perhaps putting the tarballs
on top may be better, if that would be possible. Or just another file, perhaps standalone,
perhaps wiki or something. Most of that is just an URL to github issues anyway.

Until then we are stuck to do more scrolling!

Peace out for the next scroll out. :)

(Still scrolling by the way ...)

**Comment by faho** [comment]
Nothing we can do about this, that's where github puts them.

**Comment by ridiculousfish** [comment]
Alternatively use https://fishshell.com
