### ISSUE TITLE
Styling makes ls -lr's on SSHs unreadable (light grey on light green)

### ISSUE THREAD

**Issue by jeremymeyers** [fish-shell/fish-shell#7768]
on Fish 3.1.2, SSHing to a server and then doing an "ls -lr" has a bit of a display color scheme issue in that it is almost impossible to read.

<img width="492" alt="Screen Shot 2021-03-02 at 3 56 35 PM" src="https://user-images.githubusercontent.com/3514095/109720136-b270e580-7b77-11eb-8bea-f2469e203ec1.png">

https://asciinema.org/a/k6AjWbYEhv85nZNowrLemKjnF for an example.

**Comment by faho** [comment]
Fish doesn't really determine these colors, it just runs the `dircolors` tool the first time you try to run `ls` to set $LS_COLORS (if it is unset).

You either want to modify $LS_COLORS or change your terminal's palette (for that check your terminal's settings).

Unfortunately the documentation for $LS_COLORS appears to be awful, maybe try http://www.bigsoft.co.uk/blog/2008/04/11/configuring-ls_colors.

**Comment by faho** [comment]
Alright, question has been answered, so I'm closing this.
