### ISSUE TITLE
slow midnight commander and broken fish subshell in fish 3.2.0

### ISSUE THREAD

**Issue by chrysos349** [fish-shell/fish-shell#7769]
mc 4.8.25 (or 4.8.26)
fish 3.2.0

With fish 3.2.0 set as a default shell, upon launch midnight commander hangs for about 10 seconds and has a broken subshell.
If launched with `--nosubshell` (or `-u`), the problem disappears in mc.
However, the fish subshell worked fine in fish 3.1.2, and mc launched immediately.

**Comment by olfway** [comment]
Have the same issue on mac os catalina with mc and fish from homebrew

mc 4.8.26

**Comment by ridiculousfish** [comment]
Thank you for filing this bug. Please do share the information requested in the issue template. The OS and terminal are crucial information.

When I try Midnight Commander 4.8.26 on macOS 11.2.1  with iTerm2 3.4.0, I see reproducible hangs on startup with fish 3.2.0, 3.1.2, and 3.0.2, and also bash 5.1, and zsh 5.8.0.2. I do not see any hangs on Linux.

My guess is that this is mc injecting weird commands into fish. mc attempts to detect your shell, and then [echo to weird file descriptors](https://github.com/MidnightCommander/mc/blob/a88a626e76139259e5b6fc0db39045f051e243dd/src/subshell/common.c#L1164); this [is now an error in fish](https://github.com/fish-shell/fish-shell/commit/11a373f1216830790974d938173281444d96211f); maybe we have to try to support that somehow.

**Comment by olfway** [comment]
I see this issue with fish 3.2.0 and it works fine in fish 3.1.2 (both from homebrew)

mc 4.8.26 (homebrew)
Mac OS 10.15.7
iTerm2 3.4.4

**Comment by chrysos349** [comment]
I forgot to say in my case this bug happens on Linux with fish 3.2.0 ONLY if fish shell is set as a default shell.
fish 3.1.2 worked fine.

I tried these configurations:

1. Void Linux with xfce4-terminal 0.8.10,
2. Void Linux with Konsole 20.12.2
3. Kubuntu with Konsole 20.08.2

**Comment by faho** [comment]
I would imagine just reverting 11a373f1216830790974d938173281444d96211f should work for the time being? I think mc opens those fds so they should be safe to use (and not some of our internal fds)?

Maybe just error out when the fd is a fish internal one?

**Comment by ridiculousfish** [comment]
Yeah I think we should just revert 11a373f1216830790974d938173281444d96211f. I thought redirecting to internal fds was useless but on reflection I think mc's usage here makes some sense.

**Comment by faho** [comment]
Alright, reverted.
