### ISSUE TITLE
Input may end up on screen while running bind commands (e.g. when pasting)

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#7770]
As reported by @trixnz on gitter.

The fix for #2114 (5f16a299a728f1ad5a8c533fb49276aa97612d9e) made it so any fishscript run via bind commands runs with the terminal modes for external commands.

Those modes also include "echo", which means that, if input is received while a bind command is running, it may end up on screen.

This can cause the ending sequence for bracketed paste to appear. For some reason I've only been able to reproduce this on Ubuntu (20.04) on WSL2, which also happens to be quite sluggish, so it's possible there's a WSL interaction or timing exacerbating this. Neither Debian on WSL 1 nor Arch on bare metal exhibit the problem.

I'm not entirely sure what the proper fix here is. Maybe only donating the terminal for external commands, given that our builtins don't actually care about it?

**Comment by vieira** [comment]
Hello @faho,

Would this have anything to do with the following issue: from time to time when I paste something some escape sequences (not included in the copied text) appear in the middle of what I paste. If I wait a bit and paste again after a while it appears to go fine for a while and then starts happening again.

I attached a video that shows the issue as I am not sure I am explaining it properly.

Never happened to me before 3.2.0. I'm on macOS Catalina (10.15.7).

https://user-images.githubusercontent.com/207460/110039212-d2033c00-7d38-11eb-8e8d-2cd7e0f8b480.mov

**Comment by faho** [comment]
Yes, that's the bracketed paste sequence.

@ridiculousfish Unless you have a better idea, I would revert 5f16a299a728f1ad5a8c533fb49276aa97612d9e for 3.2.1. It seems the issue it fixes is much rarer than the one it introduces, and the proper fix appears to be a bit more complicated.

**Comment by faho** [comment]
Alright, I've reverted it.

**Comment by ridiculousfish** [comment]
Really glad we caught this, thank you for reporting it. A simple way to reproduce it is `bind q 'sleep 1'`, then when you type q and more text, the text will be wrongly echoed.

I think we can "thread this needle" by effectively calling `term_steal` but NOT `term_donate`. That is, if you run an ordinary command which does not modify tty modes (like `/bin/echo`) then we will retain shell modes. If you run a fancy command which does modify tty modes - like `vim` from #2114 - then it may modify the modes, and on return we will restore them. I will give it a try.
