### ISSUE TITLE
Fish 3.2.0: __fish_print_pipestatus should unset bold mode where appropriate

### ISSUE THREAD

**Issue by simonwhitaker** [fish-shell/fish-shell#7771]
Beginning in fish 3.2.0, when run with the default config, `__fish_print_pipestatus` now prints the pipe and closing brackets in bold. I tested this under `sh -c 'env HOME=$(mktemp -d) fish'` and can confirm that I get the same behaviour there:

<img width="430" alt="Screenshot 2021-03-03 at 6 06 45 pm" src="https://user-images.githubusercontent.com/116432/109851140-3cd64980-7c4b-11eb-9e24-fa06fb7aba47.png">

```
$ __fish_print_pipestatus "[" "]" "|" (set_color red) (set_color --bold red) 9 9 | xxd
00000000: 1b5b 3331 6d5b 1b5b 316d 1b5b 3331 6d39  .[31m[.[1m.[31m9
00000010: 1b5b 3331 6d7c 1b5b 316d 1b5b 3331 6d39  .[31m|.[1m.[31m9
00000020: 1b5b 3331 6d5d 1b28 421b 5b6d            .[31m].(B.[m
```

My environment:

```
~ $ fish --version
fish, version 3.2.0
~ $ uname -a
Darwin Simons-MacBook-Pro-2.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
~ $ echo $TERM
xterm-256color
```

**Comment by faho** [comment]
Yes, `set_color --bold` means `set_color` writes the "enter_bold_mode" string to the terminal.

This is how it has always worked, just like setting the background and other modifiers. `set_color normal` will reset those.

The difference is that now some of the sample prompts pass a bold color to print_pipestatus. If you don't like it, make your own prompt and change it.

**Comment by simonwhitaker** [comment]
> Yes, `set_color --bold` means `set_color` writes the "enter_bold_mode" string to the terminal.
> 
> This is how it has always worked, just like setting the background and other modifiers. `set_color normal` will reset those.
> 
> The difference is that now some of the sample prompts pass a bold color to print_pipestatus. If you don't like it, adjust your prompt to not do that - `funced fish_prompt`, remove the thing and `funcsave fish_prompt`.

Apologies; I can see now that the issue here isn't with `set_color` (you're right, my example code of `echo (set_color --bold red)red(set_color yellow)yellow` works the same way under fish 3.1.2). Strictly speaking it isn't with my prompt either; it's with the implementation of `__fish_print_pipestatus`. I have indeed run `funced __fish_print_pipestatus` and saved myself a fixed copy, but fish 3.2.0 running "out the box" exhibits this behaviour that wasn't present in 3.1.2.

I believe this is a regression in 3.2.0. My prompt has used that built-in function (and passed in a bold colour for the `$argv[5]` (status_color) argument) for a long time, and until upgrading to fish 3.2.0 the prompt rendered as expected.

Thanks for the correction - I'll update the issue name and description accordingly.

**Comment by faho** [comment]
Okay, so how are you calling `__fish_print_pipestatus`?

**Comment by faho** [comment]
Ah, okay, I managed to reproduce, fix incoming.

**Comment by simonwhitaker** [comment]
Great stuff, thanks!
