### ISSUE TITLE
Universal Variables + on-variable handlers borked

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7774]
`fish, version 3.2.0-12-ga36dbad3b` For some reason I can only reproduce this on my Arch VM, and not my Ubuntu one running the exact same fish version.

Borked on Arch:
![uvar_machine_broke](https://user-images.githubusercontent.com/6318351/109872773-bb1df600-7c21-11eb-9e48-646afdf9c776.gif)

Working on Ubuntu 20.04:
![uvar_machine_not_broke](https://user-images.githubusercontent.com/6318351/109872781-bd805000-7c21-11eb-82c6-6acd253d04db.gif)

@ridiculousfish probably internally screaming each time I open an issue 😂

**Comment by faho** [comment]
Yeah, seems the SIGIO notifier is borked.

Honestly I'd probably just disable it entirely for 3.2.1.

**Comment by faho** [comment]
Okay, sorry @ridiculousfish, I've disabled the SIGIO notifier for now.

We've had enough issues with it that I just don't trust it anymore.
