### ISSUE TITLE
Wrapping `cd` no longer works on 3.2.0

### ISSUE THREAD

**Issue by CodingAnarchy** [fish-shell/fish-shell#7780]
I updated to Fish v3.2.0 today, and the result is that my function wrapping `cd` no longer actually changes the directory in the broader shell. The function is here:

```fish
#
# Wrap the builtin cd command to maintain directory history.
#
function cd --description "Change directory"
    set -l MAX_DIR_HIST 25

    if test (count $argv) -gt (test "$argv[1]" = "--" && echo 2 || echo 1)
        printf "%s\n" (_ "Too many args for cd command")
        return 1
    end

    # Skip history in subshells.
    if status --is-command-substitution
        builtin cd $argv
        return $status
    end

    # Avoid set completions.
    set -l previous $PWD

    if test "$argv" = -
        if test "$__fish_cd_direction" = next
            nextd
        else
            prevd
        end
        return $status
    end

    builtin cd $argv
    set -l cd_status $status

    if test $cd_status -eq 0 -a "$PWD" != "$previous"
        set -q dirprev
        or set -l dirprev
        set -q dirprev[$MAX_DIR_HIST]
        and set -e dirprev[1]

        # If dirprev, dirnext, __fish_cd_direction
        # are set as universal variables, honor their scope.

        set -U -q dirprev
        and set -U -a dirprev $previous
        or set -g -a dirprev $previous

        set -U -q dirnext
        and set -U -e dirnext
        or set -e dirnext

        set -U -q __fish_cd_direction
        and set -U __fish_cd_direction prev
        or set -g __fish_cd_direction prev
    end

    return $cd_status
end
```

Prior to 3.2.0, this worked transparently as the same as `cd`. On 3.2.0, the directory does not change at all.

**Comment by faho** [comment]
Works for me. What does `type cd` say?

**Comment by CodingAnarchy** [comment]
`type cd` returns the function defintion, as so:

```fish
cd is a function with definition
# Defined in /usr/local/Cellar/fish/3.2.0/share/fish/functions/cd.fish @ line 4
function cd --description 'Change directory'
    set -l MAX_DIR_HIST 25

    if test (count $argv) -gt (test "$argv[1]" = "--" && echo 2 || echo 1)
        printf "%s\n" (_ "Too many args for cd command")
        return 1
    end

    # Skip history in subshells.
    if status --is-command-substitution
        builtin cd $argv
        return $status
    end

    # Avoid set completions.
    set -l previous $PWD

    if test "$argv" = -
        if test "$__fish_cd_direction" = next
            nextd
        else
            prevd
        end
        return $status
    end

    builtin cd $argv
    set -l cd_status $status

    if test $cd_status -eq 0 -a "$PWD" != "$previous"
        set -q dirprev
        or set -l dirprev
        set -q dirprev[$MAX_DIR_HIST]
        and set -e dirprev[1]

        # If dirprev, dirnext, __fish_cd_direction
        # are set as universal variables, honor their scope.

        set -U -q dirprev
        and set -U -a dirprev $previous
        or set -g -a dirprev $previous

        set -U -q dirnext
        and set -U -e dirnext
        or set -e dirnext

        set -U -q __fish_cd_direction
        and set -U __fish_cd_direction prev
        or set -g __fish_cd_direction prev
    end

    return $cd_status
end
```

**Comment by CodingAnarchy** [comment]
Using `builtin cd ~` doesn't seem to work either - I'm basically just stuck in a setup directory:

```
 (v0.8.0) ✔ python 2.7.17 ruby 2.6.6 mtanous 11:23:42 ~/.a/i/j/a/bin >builtin cd ~
 (v0.8.0) ✔ python 2.7.17 ruby 2.6.6 mtanous 11:23:46 ~/.a/i/j/a/bin >
 ```

**Comment by faho** [comment]
What does `echo $PWD` say?

**Comment by CodingAnarchy** [comment]
`/Users/mtanous/.asdf/installs/java/adoptopenjdk-11.0.8+10/bin`

**Comment by faho** [comment]
And after `builtin cd /Users/mtanous` still the same?

**Comment by CodingAnarchy** [comment]
Correct:

```
 (v0.8.0) ✔ python 2.7.17 ruby 2.6.6 mtanous 11:27:57 ~/.a/i/j/a/bin >builtin cd /Users/mtanous
 (v0.8.0) ✔ python 2.7.17 ruby 2.6.6 mtanous 11:34:48 ~/.a/i/j/a/bin >echo $PWD
/Users/mtanous/.asdf/installs/java/adoptopenjdk-11.0.8+10/bin
```

**Comment by faho** [comment]
Interesting.

There weren't really many changes to `cd` in 3.2, so I'm assuming something *else* is running differently and possibly resetting your path.

Can you run `set -g fish_trace 1`, then `cd /Users/mtanous/` (and `set -e fish_trace`)?

**Comment by CodingAnarchy** [comment]
It looks mainly just like it traces through that script:

```
> cd /Users/mtanous/
--> set -l MAX_DIR_HIST 25
--> if
---> count /Users/mtanous/
---> test /Users/mtanous/ = --
---> echo 1
--> test 1 -gt 1
--> end if
--> if
--> status --is-command-substitution
--> end if
--> set -l previous /Users/mtanous/.asdf/installs/java/adoptopenjdk-11.0.8+10/bin
--> if
--> test /Users/mtanous/ = -
--> end if
--> cd /Users/mtanous/
--> set -l cd_status 0
--> if
--> test 0 -eq 0 -a /Users/mtanous != /Users/mtanous/.asdf/installs/java/adoptopenjdk-11.0.8+10/bin
---> set -q dirprev
---> set -l dirprev
---> set -q 'dirprev[25]'
---> set -U -q dirprev
---> set -g -a dirprev /Users/mtanous/.asdf/installs/java/adoptopenjdk-11.0.8+10/bin
---> set -U -q dirnext
---> set -e dirnext
---> set -U -q __fish_cd_direction
---> set -g __fish_cd_direction prev
--> end if
--> return 0
```

**Comment by faho** [comment]
Ah, I think we don't trace event handlers, so they won't show up.

Now, I think you'll have to try without customization (`XDG_CONFIG_HOME=(mktemp -d) fish`), and if that works you'll have to see what in your config is causing it.

**Comment by CodingAnarchy** [comment]
Yeah, that looks like it works. I'll look around for what might be causing it inside my config then.

**Comment by faho** [comment]
For instance I see you have bass and autojump, it's possible either of those is doing it.

(this could still be a fish bug, to be clear, it's just that they'd be running into it)

**Comment by CodingAnarchy** [comment]
It looks like commenting out some stuff like this that my workplace has to set the JAVA_HOME when `fish_prompt` is updated works:

```fish
function absolute_dir_path -a name
  # set --local absolute_path (cd (dirname "$name") && pwd)
  #  echo "$absolute_path"
end

function asdf_update_java_home --on-event fish_prompt
  set --local java_path (asdf which java)
  if test -n "$java_path"
    set --local full_path (absolute_dir_path "$java_path")
    set -gx JAVA_HOME (dirname "$full_path")
  end
```

So in v3.1.2, the `absolute_dir_path` being triggered when the prompt changed either didn't happen during `cd` or it was somehow locally contained there. Instead it looks like it is overriding the intentional `cd` with its own on v3.2.0.

I'm not sure if this is a new bug introduced to `fish`, or one that was fixed that we were leveraging. I do note that it is a common answer for how to do `realpath` on OSX (short of installing `coreutils` in homebrew).

**Comment by CodingAnarchy** [comment]
I have `realpath` installed on my system, so I can use that instead as a workaround. Thanks for the help in discovering the root of the issue.

**Comment by faho** [comment]
Oh, that's... not actually a bug?

Like... that should not have worked before. The $PWD was never isolated, this was never a subshell. If that happened to work it was only by accident.

> I do note that it is a common answer for how to do realpath on OSX (short of installing coreutils in homebrew).

Fish ships a realpath builtin (since 2.4.0), so it's guaranteed to be there. Unlike other builtins the command is picked by default if you have one (because that typically has more features), so if you want to ship a plugin or something use `builtin realpath` explicity.

Just do

```fish
    set --local full_path (builtin realpath "$java_path")
```
