### ISSUE TITLE
Changing interrupt key code with stty not working in config.fish

### ISSUE THREAD

**Issue by CameronNemo** [fish-shell/fish-shell#7783]
* fish, version 3.2.0
* TERM: alacritty
* uname: Linux ceci 5.10.19_1 #1 SMP 1614433022 x86_64 GNU/Linux

Tried to use `stty intr '^X'` in config.fish. Did not work. Used it outside config. It worked. Expectation was that the command would work as intended when in config.fish.

**Comment by faho** [comment]
Ah, okay.

What happens here is that we get the first terminal modes *before* config.fish, and then we do the stuff in config.fish, but non-interactively, so we don't actually perform the terminal "stealing" and "donating" that ends up changing our modes.

I think the simplest solution is to just let config.fish do its thing and then get the terminal modes again.

**Comment by CameronNemo** [comment]
Thanks!
