### ISSUE TITLE
Sometimes shell fails with Error while searching for command

### ISSUE THREAD

**Issue by alvinseville7cf** [fish-shell/fish-shell#7785]
Fish version: 3.1.2
OS: Microsoft Windows [Version 10.0.19042.804]

I use Fish from Cygwin and it often fails with `Error while searching for command` error:
![image](https://user-images.githubusercontent.com/42812113/110196992-1d7e2d00-7e94-11eb-817e-f0f3f03ee936.png)

It is frustrating because I prefer Fish instead of Bash but I have to use the second one because it doesn't have the same problem which sometimes happens several times in 5 minutes. On my Mac OS this problem doesn't occur so often.

**Comment by faho** [comment]
Wonderful. It appears `access()` fails on a file but doesn't specify an error.

@andrew-schulman any ideas? This seems like pretty buggy behavior.

The simple fix is to patch out the error (https://github.com/fish-shell/fish-shell/blob/a536ab810a02e39891eb0362415d9ac52e52dc32/src/path.cpp#L108-L112) or to take the awkward sun special case (where returning 0 is allowed) and extend it to cygwin.

**Comment by alvinseville7cf** [comment]
@faho, fish may break outside of Cygwin too:
![image](https://user-images.githubusercontent.com/42812113/110198222-a00aea80-7e9c-11eb-987d-8a271d297561.png)

**Comment by faho** [comment]
I'm not entirely sure how that's outside of cygwin?

**Comment by alvinseville7cf** [comment]
Maybe I am wrong. Sorry. :)

**Comment by faho** [comment]
Alright, I just removed the error because there isn't anything we can *do* about this anyway.

I can't see a situation where we get a report about this error appearing and us handling it in any other way than putting it on the pile of conditions to accept. If a new OS appears and it returns EDESPACITO? Well, seems we're ignoring EDESPACITO now.

So the value of the error is non-existent, and it clearly annoys people who see it, so let's just remove it.

**Comment by andrew-schulman** [comment]
WFM. Wow you guys are fast, I'm only just reading this and you already fixed it.

FWIW I'm not able to reproduce the error in fish 3.2.0 in Cygwin. @alvinseville7cf in your screenshots I see that fish is looking for functions in odd places like /cygdrive/c/Windows and /cygdrive/c/Python39/scripts. What's the value of `$fish_function_path` on your host? I have
```fish
andrew@helium ~> echo $fish_function_path 
/home/andrex/.config/fish/functions /etc/fish/functions /usr/share/fish/vendor_functions.d /usr/share/fish/functions
```
and that should be the default unless you've reset it somewhere.

**Comment by alvinseville7cf** [comment]
@andrew-schulman, value of my `$fish_function_pat` is:
```
/home/Alvin/.config/fish/functions /etc/fish/functions /usr/share/fish/vendor_functions.d /usr/local/share/fish/vendor_functions.d /usr/share/fish/functions
```
