### ISSUE TITLE
Request: desktop notifications on completion of long running tasks

### ISSUE THREAD

**Issue by kunaltyagi** [fish-shell/fish-shell#7786]
fish version: 3.1

Is it possible to have a desktop notification for long running tasks? This would be useful when I've multiple terminals running (or a tmux) and I can't know how much time a command would take to consciously put a `&& notify` onto it (where `notify` is a custom function)

This would also enhance background task monitoring (`command &`)

If long-running is ambiguous, I'll be equally happy with notifications for out-of-focus (if fish can detect that) tasks

**Comment by zanchey** [comment]
You can set this up with a hook function, along the lines of:

```fish
function notify_long_tasks --on-event fish_postexec
   if [ "$CMD_DURATION" -gt 5000 ] # 5 seconds
       notify $argv
    end
end
```

although `CMD_DURATION` doesn't get updated for background jobs. See eg #4830.

There's a more complex implementation here: https://robacarp.com/2018/05/04/terminal_long_running_command_notifications_with_hammerspoon.html

**Comment by zanchey** [comment]
Heaps of prior art in the first page of web search results, FWIW:

https://news.t0.vc/GVDL/c
https://github.com/franciscolourenco/done
https://codeyarns.com/tech/2013-06-29-how-to-get-notification-on-long-duration-command-completion-in-fish.html

**Comment by mqudsi** [comment]
Some terminal emulators even do fancy things like only alerting if the terminal (or terminal tab/window) doesn't have focus, e.g. here's the elementary OS integration script: https://github.com/elementary/terminal/blob/master/data/pantheon_terminal_process_completion_notifications.fish

**Comment by kunaltyagi** [comment]
Thanks @mqudsi That's nice since an active focus terminal wouldn't give notifications.

Guess, it means I'll be looking into terminal emulators now

**Comment by franciscolourenco** [comment]
https://github.com/franciscolourenco/done
