### ISSUE TITLE
Enhance __fish_print_addresses

### ISSUE THREAD

**Issue by exploide** [fish-shell/fish-shell#7787]
I would like to enhance the function `__fish_print_addresses` a bit. This function is currently used in completions when something like an address to bind to is required.

It could be enhanced to include the interface name as a description, which would help selecting the correct address.

Besides I would introduce an optional argument like `--all` that also outputs `0.0.0.0` and `::`.

Before conducting a PR: can I just change the existing function or should I create a new one? While a change would not affect the fish codebase, theoretically it's possible that 3rd party scripts use this functions and rely on the fact that no descriptions are included. But if I introduce a new function, the existing one would be unused across the fish codebase.

**Comment by krobelus** [comment]
It's a dundered function, and judging from https://github.com/search?l=&q=__fish_print_addresses&type=code most (or all?) uses 
 are in completions, where it would only be an improvement to add descriptions. So I think changing the output is fine.

**Comment by mqudsi** [comment]
> Dunder is the liquid left in a boiler after distilling a batch of rum. It is a traditional flavor source used in the fermentation of the wash of Jamaican rum.

😂
