### ISSUE TITLE
reference support

### ISSUE THREAD

**Issue by thioroup8** [fish-shell/fish-shell#779]
Hi all

Fish support variable dereference operator via multiple '$' symbol.
It's a good news.

BUT, it would be really nice if Fish allow real reference support at variable declaration like in C++ language.
int var1;
int & var2=var1;

With such real reference support, multiple '$' symbol won't be needed anymore and code won't be polluted anymore with such unpleasant syntax.

I know shell is not C++ language but IMO real reference support would be a very modern feature especially inside shell language and it's one of the purpose of Fish to be a modern shell...

What do you think about this suggestion ?

Fish developers, please, implement this feature inside your shell ;)

Thanks

**Comment by krader1961** [comment]
There are at least 300 open issues that would add more value than this proposal. So, sorry, but I'm closing this issue.
