### ISSUE TITLE
Manjaro ARM Official Repo Version: No config.fish file? Also: Autoload .fish file with multiple functions?

### ISSUE THREAD

**Issue by johntdavis84** [fish-shell/fish-shell#7791]
**Fish Version:**
fish, version 3.1.2
3.1.2

**OS and Terminal**
Linux teletraan1 5.11.0-3-MANJARO-ARM #1 SMP PREEMPT Wed Feb 17 13:00:12 CST 2021 aarch64 GNU/Linux
xterm-256color
(Fish installed on Raspberry Pi 4b.)

**Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:   sh -c 'env HOME=$(mktemp -d) fish'**

Yes; no change.

**Tell us how to reproduce the problem. Including an asciinema.org recording is useful for problems that involve the visual display of fish output such as its prompt.**

1. On default install from the official Manjaro ARM repo's community branch, I don't get a config.fish file. 
2. fish_config let me create a `fish_variables` file.

**Question:**
1. I want to get as close to the default install of fish as possible before I really start hacking on the settings. Having a default config file should also make troubleshooting easier, as I will be starting from where everyone expects me to start when I have a problem.
2. Is there any reason not to copy the config.fish file from this repo?
3. Can I tell the config.fish file to source an aliases.fish file instead of using one file for each defined function?

Thanks!

**Comment by mqudsi** [comment]
A config.fish is not created in a default installation, at least not at this time.  The `config.fish` that you see in this repo should definitely not be copied, this is the "system" version of `config.fish` and is installed to `/usr/local/share/fish/config.fish` and is invoked before your custom `~/.config/fish/config.fish` is run, if it exists.

**Comment by faho** [comment]
To expand on that:

>I want to get as close to the default install of fish as possible before I really start hacking on the settings

The "default install" is what you've got installed. The default configuration is to have no configuration. In the place where fish would execute config.fish it'll do nothing instead.

There is no default config.fish because it would be empty.

>Can I tell the config.fish file to source an aliases.fish file instead of using one file for each defined function?

Sure. Either put aliases.fish in ~/.config/fish/conf.d/ in which case fish will source it automatically, or put `source /path/to/aliases.fish` into config.fish.

It'll be faster to rely on autoloading, tho, because it allows fish to skip initialising the function until it's needed.

**Comment by johntdavis84** [comment]
@mqudsi & @faho : 

Thanks! That clears things up quite well. :)

> It'll be faster to rely on autoloading, tho, because it allows fish to skip initialising the function until it's needed.

Oh. I had not realized this at all. I wanted to put everything in a single file since I'm moving over from Bash, and at least when I was first installing everything it seemed easiest. I'll definitely change these to use auto-loading. My Pi needs all the help with performance it can get. :-P

**Comment by faho** [comment]
Alright, it seems like your question has been answered, so I'm closing this.
