### ISSUE TITLE
fish_ pre/postexec events no longer trigger on empty commands

### ISSUE THREAD

**Issue by uohmak4fvpqe** [fish-shell/fish-shell#7797]
```
> fish -v
fish, version 3.2.0
> echo $version
3.2.0
> uname -a
Linux bernard-laptop 5.10.17-1026.native #1 SMP Wed Feb 17 03:03:24 PST 2021 x86_64 GNU/Linux
> echo $TERM
xterm-256color
```

I have a custom fish_prompt that used to suppress empty command lines, just as nothing happened.
It looked like :
```
prompt> # you don't see it, but 'enter' was smashed here
```
Which I think should actually be the default behaviour, but I used to implement it myself by capturing 'fish_postexec' events and analysing $argv.
But now -- I suppose after a recent update -- the handler isn't triggered on empty commands anymore, which will make it more dirty to implement back.

Bytheway ;
```
> sh -c 'env HOME=$(mktemp -d) fish'
Bienvenue dans fish, le shell amical et interactif
Type help for instructions on how to use fish
bernard@bernard-laptop /h/bernard> function onpostexec --on-event fish_postexec
                                       echo @
                                   end
@
bernard@bernard-laptop /h/bernard> echo -n
@
bernard@bernard-laptop /h/bernard> 
bernard@bernard-laptop /h/bernard> # no '@' atop
```

So I would have either a proposal, or a request : 
* proposal : just do nothing on empty commands (empty as in nothing else than a bunch of \s,\n,\t and so on), and hold the current prompt untouched
* request : alternatively, please trigger again on empty commands

Thanks

**Comment by faho** [comment]
This is as expected, see the [release notes](https://fishshell.com/docs/current/relnotes.html):

> fish_preexec and fish_postexec events are no longer triggered for empty commands (#4829, #7085).

**Comment by uohmak4fvpqe** [comment]
What about the request then ?

**Comment by faho** [comment]
Sorry, but no. We decided to do it this way, and it generally works.

If you don't want anything to happen when you press enter, rebind it to check if the commandline is empty:

```fish
bind \r 'commandline | string length -q; and commandline -f execute'
```

**Comment by uohmak4fvpqe** [comment]
Seems like a perfectly fine solution, thank you

**Comment by uohmak4fvpqe** [comment]
If someone ever want to achieve the same result, here is what I came up with.
This erases the current command line -- even multiline -- if it is empty once trimmed :
```
bind \r 'commandline | string trim | string length -q \
            && commandline -f execute \
            || commandline -r ""'
```
escaping doesn't seem required
