### ISSUE TITLE
Outdated Arch Package

### ISSUE THREAD

**Issue by EPonyA** [fish-shell/fish-shell#7798]
The [Arch Community package](https://archlinux.org/packages/community/x86_64/fish/) for Fish still provides 3.12. At least [one plugin](https://github.com/IlanCosman/tide) already has a dependency on 3.2, so it would be very convenient for Arch users to have this updated soon, if possible.

**Comment by faho** [comment]
Nothing we can do about that, the package has been flagged out of date on the arch site, now the maintainer needs to update it.

**Comment by zanchey** [comment]
Can someone send a PR or something? I don't know how Arch packages work.

**Comment by faho** [comment]
>Can someone send a PR or something?

No. Arch doesn't accept PRs and doesn't accept bug reports because a package is out of date.

All anyone from the outside can do is flag the package (which it has) and wait.

There really is _nothing_ we can do.
