### ISSUE TITLE
How to save the current input into the stack

### ISSUE THREAD

**Issue by ruv** [fish-shell/fish-shell#7800]
Can fish have some alternative to [`push-input`](http://zsh.sourceforge.net/Doc/Release/Zsh-Line-Editor.html#index-push_002dinput) function of zsh?

> `push-input`
> 
> Push the entire current multiline construct onto the buffer stack and return to the top-level (PS1) prompt. If the current parser construct is only a single line, this is exactly like push-line. Next time the editor starts up or is popped with get-line, the construct will be popped off the top of the buffer stack and loaded into the editing buffer. 
>

**Comment by faho** [comment]
This is one of those things you can write yourself:

```fish
function push-input
    set -g pushed_input (commandline | string collect)
    commandline -r ""
end

function pop-input --on-event fish_postexec
    if test -n "$pushed_input"
        commandline -r -- $pushed_input
    end
end

bind \cg push-input
```

**Comment by ruv** [comment]
@faho, thanks for the hint. But zsh uses the stack for that.

I have tried the following modification:

``` shell
function push-input
    set -g --prepend pushed_input (commandline | string collect)
    commandline -r ""
end

function pop-input --on-event fish_postexec
    if test -n "$pushed_input[1]"
        commandline -r -- $pushed_input[1]
        set -g --erase pushed_input[1]
    end
end

bind \cg push-input
```

It works like a charm!
