### ISSUE TITLE
set_color --print-colors always bold

### ISSUE THREAD

**Issue by plgruener** [fish-shell/fish-shell#7805]
fish --version : current git build (3.2.0-44-g4218c1f1a-dirty)
OS: ArchLinux, terminals: all

Problem: `set_color --print-colors` outputs *every* named color (except 'normal') in bold, even the non-br-ones.  For colorschemes that define dedicated "bright" colors, this is inaccurate. It also means that the `--dim` switch does *not* work (it gets converted to bold+dim = bold font, but in normal color).

I patched `builtin_set_colors.cpp` to print the escape sequences to pipes/files, this yields:

```
$set_color --print-colors | string escape
\e\[1m\e\[30mblack
\e\[1m\e\[34mblue
\e\[1m\e\[90mbrblack
\e\[1m\e\[94mbrblue
\e\[1m\e\[96mbrcyan
\e\[1m\e\[92mbrgreen
\e\[1m\e\[95mbrmagenta
\e\[1m\e\[91mbrred
\e\[1m\e\[97mbrwhite
\e\[1m\e\[93mbryellow
\e\[1m\e\[36mcyan
\e\[1m\e\[32mgreen
\e\[1m\e\[35mmagenta
\e\[1m\e\[31mred
\e\[1m\e\[37mwhite
\e\[1m\e\[33myellow
\e\[1m\e\[30m\e\(B\e\[mnormal
```
and
```
$ set_color --print-colors --dim | string escape
\e\[2m\e\[1m\e\[30mblack
\e\[2m\e\[1m\e\[34mblue
\e\[2m\e\[1m\e\[90mbrblack
\e\[2m\e\[1m\e\[94mbrblue
\e\[2m\e\[1m\e\[96mbrcyan
\e\[2m\e\[1m\e\[92mbrgreen
\e\[2m\e\[1m\e\[95mbrmagenta
\e\[2m\e\[1m\e\[91mbrred
\e\[2m\e\[1m\e\[97mbrwhite
\e\[2m\e\[1m\e\[93mbryellow
\e\[2m\e\[1m\e\[36mcyan
\e\[2m\e\[1m\e\[32mgreen
\e\[2m\e\[1m\e\[35mmagenta
\e\[2m\e\[1m\e\[31mred
\e\[2m\e\[1m\e\[37mwhite
\e\[2m\e\[1m\e\[33myellow
\e\[2m\e\[1m\e\[30m\e\(B\e\[mnormal
```
_(edit: changed `od -c` to `string escape`)_

This confirms it's not an issue with my terminal config, but fish sending wrong escape codes.

(Note: I had a quick glance at the code, but couldn't fix the issue myself. But I saw a comment in `output.cpp` that bold mode is always entered for readability reasons, that might be related?)

**Comment by faho** [comment]
Ah, okay.

What happens here is that fish has a special case where it'll enable bold mode whenever the background is on "to make reading easier". That's pretty dubious to begin with, but removing it is probably a bigger change.

`set_color` runs into this because it *sets* a background color of "none". Fix incoming.

**Comment by faho** [comment]
Also as a sidenote:

> `$ set_color --print-colors | od -c`

`od` is super chatty and fills the entire screen with very little information here. Use `string escape` in its place and you'll get much more compact output. For example:

```fish
> set_color yellow | string escape
\e\[33m
```

**Comment by plgruener** [comment]
Thanks for the quick fix.

Ah, `string escape` is certainly much nicer than `od`, thanks for the tip. Is there any way to display the escape sequences without patching fish first? (As far as I could tell they are always omitted if output is to a pipe or file.)

**Comment by faho** [comment]
>Is there any way to display the escape sequences without patching fish first? 

 `set_color --print-colors` specifically won't do it if it's not connected to a terminal.

I suppose you *could* use `expect` or similar to connect it to a fake one (e.g. like [our tests do](https://github.com/fish-shell/fish-shell/blob/master/tests/pexpects/set_color.py)). Other than that, no.

**Comment by floam** [comment]
I think type
