### ISSUE TITLE
Improve awareness of fish_add_path by editing issue #527 again

### ISSUE THREAD

**Issue by Delapouite** [fish-shell/fish-shell#7810]
Hello

The introduction of `fish_add_path` in 3.2 should solve a lot of headache for new-comers.

In the top results returned by search engines about the topic of appending to `$PATH` in fish, this stackoverflow question has an answer which has been edited a few days ago to mention `fish_add_path`: https://stackoverflow.com/a/61882414/232943 which is great.

The other famous page returned by search engines is this GitHub issue: https://github.com/fish-shell/fish-shell/issues/527 dating from 2013. An administrator already hijacked the original post to help people. I reckon this post should be hijacked again to better reflect the recent changes related to 3.2 and mention the existence of `fish_add_path`.

**Comment by faho** [comment]
Done.
