### ISSUE TITLE
Add XDG_DATA_HOME to the vendor config sources

### ISSUE THREAD

**Issue by mrmeszaros** [fish-shell/fish-shell#7816]
System spec:
```
fish, version 3.1.0
Linux big-della 5.8.0-44-generic #50~20.04.1-Ubuntu SMP Wed Feb 10 21:07:30 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
xterm-256color
```

Currently `XDG_DATA_DIRS` are searched for vendor completions, functions and config.
I suggest we add `XDG_DATA_HOME` (default: `$HOME/.local/share`) so that a user installed tool can put their config into the respective place.

A followup of #5029.

**Comment by ThisNekoGuy** [comment]
Been actually having an issue with `XDG_DATA_DIRS` with flatpaks since I have Fish as my login and root shell
Because it never knows what it is, it never adds flatpaks to my application launcher even after reboots

And attempting to do so manually with:
```fish
set -xU XDG_DATA_DIRS $HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share $fish_user_paths
```

makes `Flatpak` satisfied but **_then_** causes the following error when trying to run `flatpak update`:
```fish
(flatpak update:318839): GLib-GIO-ERROR **: 19:11:56.509: No GSettings schemas are installed on the system
fish: “flatpak update” terminated by signal SIGTRAP (Trace or breakpoint trap)
```

**Comment by faho** [comment]
@ThisNekoGuy That's an entirely different issue.

Flatpak decided that the place to put this stuff is /etc/profile.d, and that won't work with fish.

>set -xU XDG_DATA_DIRS $HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share $fish_user_paths

That sets $XDG_DATA_DIRS wrong. For one, you *don't* want fish_user_paths in there (this isn't a path to find executables with!), and for another you either want to define it as one element with `:` in between, or make it a path variable (with `--path`) in which case fish will handle it transparently.

That it crashes seems like a bug in flatpak, but you've set this wrong to begin with.

Either way, it has nothing to do with the problem at hand, which is that fish doesn't check $XDG_DATA_HOME for its stuff.
