### ISSUE TITLE
Translation lacks ": " in cdh

### ISSUE THREAD

**Issue by lapingenieur** [fish-shell/fish-shell#7819]
## Versions

fish : version 3.1.2
gettext : version 0.21

## My issue

When using `cdh` to print last visited directories, it automatically asks for a number/letter. With `$LANG` equals to C it prints : (enters 'a' then press enter)

```bash
~/.config $ cdh
 a  1)  ~
Select directory by letter or number: a
~/ $
```

But if `$LANG` is set to `fr_FR.UTF-8` (standard french value), it's a bit stranger : (enters 'a' then press enter)

```
~/.config $ cdh
 a  1)  ~
Sélectionner un dossier par lettre ou chiffrea
~/ $
```

=> There's no `:` and the answer is just after the output (no space). I tried to fix the problem myself : `cdh` calls a fish function `_` which is a kind of alias for `gettext fish` (gettext is a GNU program). Now it's gettext that causes the bug : it doesn't add `: ` to the end of the line.

However, I don't know how to correct it. I tried to search for this string in the source code (available from GNU savanah repos / gettext) but I didn't find neither the french or the english string.

This issue might not be at the right place here but I don't know where else to put it, so if anyone here knows how to correct this I'd thank him.

**Comment by faho** [comment]
You'll want to look in https://github.com/fish-shell/fish-shell/blob/master/po/fr.po - that's *fish's* french translation.

> the source code (available from GNU savanah repos / gettext)

The ones in the GNU gettext repo are irrelevant.

**Comment by lapingenieur** [comment]
Thanks for this quick answer ! I'll correct then pr it !
