### ISSUE TITLE
Some bindings don't work in vi mode

### ISSUE THREAD

**Issue by lapingenieur** [fish-shell/fish-shell#7825]
```
fish version 3.1.2
terminal : termite v15
$TERM is 'termite' by default but I change it in config.fish to 'xterm-256color'
I use manjaro with kernel 5.9.16-1-MANJARO
```

This bug also works without customization.

I was trying to customize a bit the vi mode using the `bind` function. I wanted to remap insert_alt-backspace to `backward-kill-word`, but it doesn't work. Remaping another key to the same action actually works (like `ee` in the example below), and mapping any combinaison using backspace doesn't work (`bind` returns a 0 status but the remapping doesn't work).

```bash
bind -M insert \e\b backward-kill-word   # map alt-backspace, doesn't work
bind -M insert ee backward-kill-word     # map ee, works well
bind -M insert \c\b backward-kill-word   # map control-backspace, doesn't work
bind -M insert \b backward-kill-word     # map backspace, doesn't work
```

**Comment by faho** [comment]
Most likely your terminal doesn't send `\b` for backspace. There's some historical confusion that means most terminals send *del*, not *backspace* for backspace.

Start `fish_key_reader`, press whatever key chord you're interested in, that'll give you the sequence.

Most likely alt-backspace will send `\e\x7f` (i.e. alt+*del*).


>$TERM is 'termite' by default but I change it in config.fish to 'xterm-256color'

Please don't. $TERM should accurately reflect what the terminal is, and the best way to achieve that is to just leave it like the terminal does.

Also note that termite is dead - https://github.com/thestinger/termite/issues/760.

**Comment by lapingenieur** [comment]
Thanks, it works this way.

I changed my $TERM because several programs I use were bugging when set to `termite`... I won't be any more :D

And I didn't know about the project was dead, thanks for telling it me. Can I ask you which terminal emulator you'd advice me ? (I want true 24 bit colors)

**Comment by faho** [comment]
>And I didn't know about the project was dead, thanks for telling it me. Can I ask you which terminal emulator you'd advice me ? (I want true 24 bit colors)

Personally, I use konsole, but that's a KDE thing. Works for me. I hear people like alacritty, which has fewer dependencies. Beyond that I'm not really interested and don't have any opinions I'm willing to share, because people might think they're the opinions of the fish project.

Anyway, the question has been answered, so I'm closing this.
