### ISSUE TITLE
bash using 100% cpu when fish was default shell changed it back to bash and problem seems to be gone.

### ISSUE THREAD

**Issue by NOOBNOOB0X** [fish-shell/fish-shell#7840]
fish --version - fish, version 3.1.2
  echo $version - no return command shown

operating system - Arco linux
terminal - termite
window manager - qtile and awesome (this issue comes in this window managers whereas there is no issue in xmonad)

There is one shell script running along with fish i tried without it and issue is still there.

**Comment by faho** [comment]
I would appreciate a description of what you are *doing*. I have no idea what is starting bash here and what that bash is doing.

Also ideally you would try this with fish 3.2.0 - there's been a *lot* of changes in that, some of which (like the process group adjustments) may very well fix this. Unfortunately arch has been slow in upgrading.

Also:

> echo $version - no return command shown

If `echo $version` doesn't print anything, that means you're not running fish.

**Comment by NOOBNOOB0X** [comment]
> I would appreciate a description of what you are _doing_. I have no idea what is starting bash here and what that bash is doing.
> 
> Also ideally you would try this with fish 3.2.0 - there's been a _lot_ of changes in that, some of which (like the process group adjustments) may very well fix this. Unfortunately arch has been slow in upgrading.
> 
> Also:
> 
> > echo $version - no return command shown
> 
> If `echo $version` doesn't print anything, that means you're not running fish.

**Comment by NOOBNOOB0X** [comment]
ok so I ran sudo pacman -Syu and fish updates are not there. 
echo version- echo3.1.2

**Comment by faho** [comment]
Arch has now updated, please try again with 3.2.0.

If the problem still happens, please describe in more detail what you are doing and we'll reopen - as it stands I have no idea in what context a bash is appearing, so I can't help you.
