### ISSUE TITLE
Macports upgrade needed

### ISSUE THREAD

**Issue by Javabien** [fish-shell/fish-shell#7844]
In your installation instructions, you mention about using macports to install fish, but the current version is: 3.1.2, so it's 2 versions behind.
https://github.com/macports/macports-ports/blob/master/shells/fish/Portfile

**Comment by faho** [comment]
This is handled by the macports people, we have no influence over them.

Alternatively see https://fishshell.com/, which will allow you to install one of two different binary packages, install via homebrew or build from source.

There's nothing else we can do, so I'm closing this.
