### ISSUE TITLE
Debian fish binary package difficult to install

### ISSUE THREAD

**Issue by ilyagr** [fish-shell/fish-shell#7845]
If I want to install fish on Debian, www.fishshell.com points me to the [Suse download page](https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A3&package=fish). If I use the "Debian / Grab packages directly" option, the package I download does not install on Debian 10. That is because the platform-specific binary `fish` package depends on  the `fish-common` package, but there's no way to download the correct version of the `fish-common` package on that page.

The same problem affects the similar Debian link from the [Development Binaries](https://github.com/fish-shell/fish-shell/wiki/Development-builds) page.

Workarounds:

1. Use the "subscribe" option.
2. Manually download the `fish-common` package and install it together with the `fish` package. It is not easy to find, but here are the links: [Debian 10](https://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_10/all/), [Debian 9](https://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_9.0/all/). These links are likely to remain valid for any future Fish 3.x releases.

    The installation command I used was `sudo dpkg -i fish*3.2.1*.deb`

I'm not sure if there's a way to add `fish-common` and the instruction to install it together with `fish` to the opensuse.org download page, but it would be nice.

**Comment by ilyagr** [comment]
A separate problem that only affects the Development builds: when I try to download the Debian 10 amd64 version from https://software.opensuse.org/download.html?project=shells%3Afish%3Anightly%3Amaster&package=fish, my Google Chrome 89 browser blocks the download as insecure. I can force the download by going to the Downloads page (`Ctrl+J`). The probable reason is that, even though the button/link looks like it's pointing to an HTTPS url, the download actually happens over HTTP:

```
$ curl https://download.opensuse.org/repositories/shells:/fish:/nightly:/master/Debian_10/amd64/fish_3.2.1-7-g211f8bc89-1~unstable_amd64.deb
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="http://downloadcontent.opensuse.org/repositories/shells:/fish:/nightly:/master/Debian_10/amd64/fish_3.2.1-7-g211f8bc89-1~unstable_amd64.deb">here</a>.</p>
<hr>
<address>Apache/2.4.43 (Linux/SUSE) Server at download.opensuse.org Port 443</address>
</body></html>
```

This problem does NOT affect the release build for me at the moment (see below). I'm not sure if that depends on which mirror OpenSuse decided to use.
```
$ curl https://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_10/amd64/fish_3.2.1-1_amd64.deb
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>302 Found</title>
</head><body>
<h1>Found</h1>
<p>The document has moved <a href="https://provo-mirror.opensuse.org/repositories/shells:/fish:/release:/3/Debian_10/amd64/fish_3.2.1-1_amd64.deb">here</a>.</p>
<hr>
<address>Apache/2.4.43 (Linux/SUSE) Server at download.opensuse.org Port 443</address>
</body></html>
```

**Comment by zanchey** [comment]
Yeah, I think we should drop the "download" language from the homepage. The OBS download page does not let us recommend other packages, or remove the "download package directly" option, but direct dpkg installation is really an anti-pattern these days.

**Comment by ilyagr** [comment]
For the homepage, it might be nice to also add a note that the "Download" option does not work, if there's any place to fit it.

For me personally, the development binaries problem is the more annoying one (honestly, I doubt it matters to very many other people). It does seem that just downloading the files and installing them would be a bit reckless even if were done over https -- I guess a mirror could be EVIL. However, using `.deb` is very tempting over `make install`. The problem with the subscription option for nightly builds is that I don't know of a way to downgrade if, one night, something in the master branch breaks in a way that's annoying for me.  Is there any way to recover a `.deb` from a few nights ago in that case?

If that's not possible, and I decide to persevere, I guess I could figure out how to properly check the signature on the files. I could also see if there's a way to subscribe and get `apt` to preserve old versions in its cache on my disk somehow.

**Comment by zanchey** [comment]
> Is there any way to recover a `.deb` from a few nights ago in that case?

Not from the mirrors, but apt keeps a cache of downloaded packages and you can tweak the options to that (I think turning off `Clean-Installed` in `apt.conf` is what you want to start with).

**Comment by danieldjewell** [comment]
The alternative might be to get the Debian package updated *in Debian*.... 

https://tracker.debian.org/pkg/fish
https://salsa.debian.org/debian/fish

(It would appear that the build is failing, but I'm not an expert on lintian)

Is there some reason why there are separately distributed binaries (DEBs) for fish instead of putting those efforts into just updating the debian package itself?

**Comment by faho** [comment]
>Is there some reason why there are separately distributed binaries (DEBs) for fish instead of putting those efforts into just updating the debian package itself?

Simple: The debian package won't be updated in a release, or in testing (and in practice even unstable) during a freeze.

So users get stuck on whatever fish version the release shipped with. That's the stable release idea for you.

**Comment by danieldjewell** [comment]
> Simple: The debian package won't be updated in a release, or in testing (and in practice even unstable) during a freeze. That's the case right now, and why it won't be updated now. The timing was awful, so the next debian release will probably be shipping with fish 3.1.2, and it would be against Debian's policy to update it in the release.

Yeah..... that's a good point. (Sometimes unstable/sid is a little better, but as you said - in practice.)
 
> So users get stuck on whatever fish version the release shipped with. That's the stable release idea for you.

You might enjoy [this talk by Linus "on why desktop Linux sucks"](https://youtu.be/Pzl1B7nB9Kc) - he offers some really cool (and funny/sad) insight into the whole binary distribution process.

**Comment by zanchey** [comment]
Also, I'm not a Debian developer, so we'd need to get the uploads sponsored.

**Comment by zanchey** [comment]
OK, I thought some more about this and I'll merge a change that drops the `fish-common` packages.

The benefit of them is that we follow the Debian policy manual a little more closely (but that has limited practical impact) and that the Debian download repositories are 40% smaller on disk. But the packages are fairly small anyway so this goes from ~4.7 to ~8 MB - not really a concern unless the download repositories are hosted on a floppy array or something.

The downside, as noted, is that it complicates the install for new users who are just downloading the package, and involves a very slightly larger download size. I would prefer if everyone subscribed to the repository, but there are valid reasons for not doing that.
