### ISSUE TITLE
bash using 100% cpu when fish was default shell changed it back to bash and problem seems to be gone. Update

### ISSUE THREAD

**Issue by NOOBNOOB0X** [fish-shell/fish-shell#7846]
I had posted an issue on this https://github.com/fish-shell/fish-shell/issues/7840, i updated my fish so the issue be fixed, but its still there and now after update the apps in awesomewm is not auto starting for eg nitrogen for wallpaper and picom for transparency does not work. when i changed it back to bash it worked.

**Comment by faho** [comment]
This is still lacking a proper description of what you are doing and where the "bash" is started.
