### ISSUE TITLE
Suggestion: Utility to emulate behaviour of `set`, i.e. preserve exit code

### ISSUE THREAD

**Issue by schuelermine** [fish-shell/fish-shell#7848]
It would be useful to have a utility that ignores the status code like `set` does, but without assigning variables, and passing on standard output as well.

Specifically:
```
preserve_status COMMANDNAME [ARGS ...]
Execute COMMANDNAME, but do not alter exit status
```

(I'm not sure that name is a good one, feel free to suggest better names!)

**Comment by faho** [comment]
What's the usecase here?

Usually that just means you want to do something with the old status later, in which case you can just store it in a temporary variable.

**Comment by krobelus** [comment]
If you want to use this in `fish_prompt`, see https://github.com/fish-shell/fish-shell/issues/7830 for a dedicated solution.

I'll close until we have a compelling use case for this.
