### ISSUE TITLE
Piping while read into `head -n10` doesn't terminate

### ISSUE THREAD

**Issue by domdom** [fish-shell/fish-shell#7852]
Fish version: 3.1.2

Consider the following:
```fish
yes | while read line
    echo "no"
end | head -n10
```
I would expect this to stop after printing no 10 times. Instead it never terminates.

The bash equivalent terminates after printing 10 times.

**Comment by domdom** [comment]
I think this is a duplicate of #1396, sorry about that!

**Comment by zanchey** [comment]
Yep!
