### ISSUE TITLE
Some vi key bindings will not work after running `lazygit`

### ISSUE THREAD

**Issue by Cokile** [fish-shell/fish-shell#7853]
Fish Version:
fish, version 3.2.1

Operating System:
MacOS 10.15.7
Darwin MacBook-Pro.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64

Terminal:
iTerm2 build 3.4.4
xterm-256color

config.fish:
```
set fish_key_bindings fish_user_key_bindings
```

functions/fish_user_key_bindings.fish:
```
function fish_user_key_bindings
    fish_vi_key_bindings
    
    # map jk to Esc
    bind -M insert jk "if commandline -P; commandline -f cancel; else; set fish_bind_mode default; commandline -f backward-char force-repaint; end"
end
```

Steps to reproduce:
1. Install [lazygit](https://github.com/jesseduffield/lazygit) via Homebrew
```
$ brew install lazygit
```
2. Run lazygit
```
$ lazygit
```

3. Quit lazygit

Before running lazygit, all vi key bindings work as expected. But after running lazygit, some vi key bindings will not work:
1. `cw`, `dw`: just moving the cursor to the beginning of the next word, no characters will be deleted.
2. `jk`: just outputting the `jk` rather than switching to normal mode. But if press `j` only, nothing will appear, it seems fish is still waiting the subsequent input.

**Comment by zanchey** [comment]
After running lazygit even without vi bindings, fish is not behaving normally. Pressing right arrow works the first few times, then starts spitting `[C` (the tail end of the escape sequence) out to the terminal.

**Comment by ridiculousfish** [comment]
This is curious. Some one is configuring fish as the receiving process (via `O_ASYNC`). This sends SIGIO on every `select()` on stdin, thus fish thinks it is constantly being interrupted, which breaks multi-character key bindings including `cw` and arrow keys.

No file descriptor in the fish process has `O_ASYNC` set, so maybe there is some funny behavior where lazygit sets it and then fish inherits the behavior? Not sure, it's strange.

**Comment by ridiculousfish** [comment]
@zanchey note I cherry-picked this into 3.2.2 as 797fbbb5f53500d7e7335da83f203a272720b874

**Comment by zanchey** [comment]
Many thanks!

**Comment by Cokile** [comment]
BTW, I upgraded Lazygit to the latest release(v0.27), which replace termbox package with tcell, and the issue seems have gone.
