### ISSUE TITLE
On fresh Ubuntu 20.04, successful chsh to fish, but default gnome-terminal loading bash, until after a computer reboot

### ISSUE THREAD

**Issue by OwenAR** [fish-shell/fish-shell#7854]
This bug is likely more on the Ubuntu side than the fish side, but... yeah.

I just did a fresh install of Ubuntu 20.04,
then installed fish from the main PPA ( @zanchey ) ( https://launchpad.net/~fish-shell/+archive/ubuntu/release-3 )
then did a chsh to fish (`/usr/bin/fish`).
(And yes it had been added to `/etc/shells`)

It worked fine, and other terminals respected it (eg, konsole, or ssh-ing in, etc)...

But for some reason the ubuntu default gnome-terminal kept loading bash.

(btw, gnome-terminal is the one that mostly just labels itself plain "Terminal" in the UI. Opens on ctrl-alt-t.)

I opened new tabs, they were bash.

I closed it entirely and reopened it, it loaded bash.
(And I checked it wasn't still running in the background when I closed it to restart. I mean, `ps -e|grep gnome-terminal` gave nothing.)

( And unfortunately I didn't take super good note of it at the time as I was flailing around setting things up,
but I'm *pretty* sure `echo $SHELL` *in* the bash that gnome-terminal was running was giving "/usr/bin/fish"
)

So I considered googling up some other settings to monkey with...

But then I decided to just reboot the computer entirely and see what happened.

And yup, after reboot, gnome-terminal finally loads fish like it should.

(I suspect it may have worked if I had just used "log out" rather than completely rebooting, but obviously I'm not rushing off to do *another* fresh install just to test that.)

---
Anyway yeah, it's just a minor transient little bug, but if it affects everyone who installs fish from the PPA on ubuntu,
then that'd be a few aggravated confused people-hours...

And it's the kind of thing where, rather than rebooting your system,
you're likely to try to google for a solution in terms of something you can actually immediately *do*, *within* the system,
which is quite likely to lead to you finding some potential solutions that *sound* plausible,
but which actually involve stuff like monkeying with unrelated default config files that may well lead to yet *more* confusing little bugs later....

( And by "you", I mean I'm pretty sure I did that myself while installing this ubuntu the first time a few days ago,
just I can't remember for sure with everything else I was doing...
I just happen to have ended up redoing the fresh install again just not anyway for unrelated reasons (partition layout was wonky to begin with)
)

But it's not *just* me.
I just found this:
https://askubuntu.com/questions/26439/how-do-i-set-fish-as-the-default-shell
and the top answer is the correct one that *should* work (but doesn't without that reboot),
and you can see how that correct answer is followed by like:
"just add `fish` to the end of your `.bashrc`"
and
"`usermod -s /usr/bin/fish username`"
etc

**Comment by ridiculousfish** [comment]
Thanks for filing. Yes, chsh has always required a logout on Linux, there is nothing fish can do about it. See [this discussion](https://askubuntu.com/questions/195361/chsh-s-usr-bin-zsh-not-working) for more.

Is there something that could have been improved about the docs or tutorial that would have made this more obvious?

**Comment by OwenAR** [comment]
Hmm, well, what about the function `fish_greeting`?

Rather than just saying like "Hi, welcome to fish",
I guess it could easily be extended to give the user more actual information, like...

- alerting them to fact *that* they should be aware of potential confusing idiosyncrasies from different distros, terminal emulators, etc
(the "chsh won't actually take effect until you reboot" thing would make a good concrete example to quickly give them an idea of the *kind* of confusing idiosyncrasies that come up)

- looking at common shell variables and commands and stuff (like `$TERM` and `lsb_release -a`),
and using that to alert them to anything *specific* to their setup that caused confusion for other users in the past with the same setup

- prompting them to report any new confusion they encounter, in order to extend this informative `fish_greeting`

(
... actually, that makes me think of this thing I came across, `bro` (`gem install bropages`)
(or the fork `gem install wb-bropages` ; haven't really used it yet much, dunno any details like if one is significantly more alive)
but the basic idea is just that right-in-the-shell leaving a record of interactive questions and answers...
)

**Comment by faho** [comment]
>Hmm, well, what about the function fish_greeting?

That shows up *every time you launch fish*, which makes it seem like a horrible place for this.

Especially when you want to add what easily amounts to pages of information.

There's a bit of an issue here in that we are generally not in the business of teaching unix - `chsh` is not a fish command. We don't implement it, your operating system does. It *could* very well make it so it takes effect immediately, or they could require different arguments, or...

Adding notes on all of that frankly doesn't scale, especially not in the greeting. 
We're planning on rewriting the tutorial anyway, that might be a better place for some of this information.

But even considering that, teaching the entirety of unix doesn't seem like a good use of our documentation, so it would have to be somewhat more focussed.

**Comment by ridiculousfish** [comment]
Closing as this is indeed a Linux-ism, not a fish issue. Thanks for filing.

**Comment by kazmiali** [comment]
Its a linux issue, same thing happened to me but after logging out and logging in again, terminal was opening fish.
