### ISSUE TITLE
fish_indent --ansi syntax highlighting missing and doesn't match interactive console

### ISSUE THREAD

**Issue by PatrickF1** [fish-shell/fish-shell#7855]
# Env
fish version: 3.2.1
OS: Darwin 19.6.0 / macOS 10.15.7
Terminal: xterm-256color (running on iTerm)

# Repro
1. copy/paste this into a file named helper.fish
```fish
function helper
    return 0
end
```
2. `fish_indent --ansi helper.fish`
3. Now copy/paste it in your interactive console and notice how fish_indent syntax highlighting is not nearly as complete as the interactive console's syntax highlighting

fish_indent --ansi:
![Screen Shot 2021-03-22 at 2 40 21 PM](https://user-images.githubusercontent.com/1967248/112062015-8e704680-8b1c-11eb-8a2f-36775a277568.png)

interactive fish:
![Screen Shot 2021-03-22 at 2 40 24 PM](https://user-images.githubusercontent.com/1967248/112062004-8b755600-8b1c-11eb-852b-bb698044a1e8.png)

Perhaps fish_indent was never meant to be a colorizer. In which case, oops... (https://github.com/PatrickF1/fzf.fish/pull/135)

**Comment by IlanCosman** [comment]
I can't reproduce with Fish 3.2.1 on MacOS, or Fish master on Arch. Have you tried doing this with a perfectly clean fish instance?

**Comment by PatrickF1** [comment]
Wow Ilan you are everywhere! Can’t believe you found this so soon.
How can I do that? I’m assuming you mean running without any config files
rather than reinstalling fish.

**Comment by IlanCosman** [comment]
> How can I do that? I’m assuming you mean running without any config files

It's in the Fish issue template: `sh -c 'env HOME=$(mktemp -d) fish'`

**Comment by PatrickF1** [comment]
@branchvincent @IlanCosman thank you! I learned a lot from this. This was my own mistake not exporting `fish_color_command`. My bad for opening an issue that wasn't actually a bug.
