### ISSUE TITLE
Add max and min math functions

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#7856]
It's not super common, but I've found myself wanting these functions to set upper and lower bounds on things.

Obviously this is just a nice tool to have, but as a specific use case, some `string` commands like `pad` and `repeat` will error if you give them negative numbers. Obviously we can't use `abs` here, so I've been doing `test $blah -lt 0 && set $blah 0`. This works of course, but it is less elegant and requires setting the value to a variable first.

**Comment by ridiculousfish** [comment]
Seems reasonable, tinyexpr isn't really set up for functions of arbitrary arity, so it's a bit of a dive, but still a fun isolated change. [Start with tinyexpr functions](https://github.com/fish-shell/fish-shell/blob/bcbfd70d413155152ce1261f925a62b678c83d32/src/tinyexpr.cpp#L185).
