### ISSUE TITLE
builtins do not fail upon unsuccessful write

### ISSUE THREAD

**Issue by nertpinx** [fish-shell/fish-shell#7857]
As mentioned in #7836, the builtin `echo` does not fail when the the writes fail, making it difficult to realize whether there was an error or not.

The easiest way to reproduce this on Linux is:
```
$ builtin echo >/dev/full
write: No space left on device
$ echo $status
0
```

**Comment by faho** [comment]
This applies to builtins in general. We do not currently have the API to express that a write failed.
