### ISSUE TITLE
Screen not cleared after quitting F1 man

### ISSUE THREAD

**Issue by YaLTeR** [fish-shell/fish-shell#7863]
fish, version 3.2.1, same issue with default config.

On VTE, xterm, urxvt, Konsole (but not Alacritty) exiting the F1 man page with <kbd>q</kbd> doesn't move the prompt down and leaves the text on screen, so subsequent commands will overlap with this text.

![image](https://user-images.githubusercontent.com/1794388/112468075-e60aee00-8d78-11eb-8a57-7313a2f1f7ed.png)

[asciinema recording](https://asciinema.org/a/NDeVU9AaSlfmPLvyjK3OxGmQf)

I made a [VTE issue](https://gitlab.gnome.org/GNOME/vte/-/issues/344) where the maintainer came to the conclusion it is an issue with the sequence fish uses:

> Hmm. So this exits the alternate screen via `RM_DEC 1049` which does not clear the screen. So unless the result differs between vte and xterm, this is a problem in alacrity.

**Comment by zanchey** [comment]
fish doesn't send this sequence, it is most likely your pager. The output of `echo $MANPAGER $PAGER` might be helpful.

**Comment by YaLTeR** [comment]
> fish doesn't send this sequence, it is most likely your pager. The output of `echo $MANPAGER $PAGER` might be helpful.

Empty in both Alacritty and VTE.

**Comment by faho** [comment]
>I made a VTE issue where the maintainer came to the conclusion it is an issue with the sequence fish uses:

*fish* does not use the sequence here, your pager does.

It appears `man` uses `less` if $PAGER and $MANPAGER are unset, so I'd look at $LESS for any options you've set.

Either way, this isn't a fish issue, we just call `man`.

**Comment by YaLTeR** [comment]
> It appears `man` uses `less` if $PAGER and $MANPAGER are unset, so I'd look at $LESS for any options you've set.

Also empty.

> Either way, this isn't a fish issue, we just call `man`.

Executing the `man` command regularly and quitting out clears the screen, however using fish's F1 doesn't for some reason.

**Comment by YaLTeR** [comment]
Here's a `script(1)` recording of opening and closing `man` by itself, then opening and closing man using F1.

[regular-then-fish.log](https://github.com/fish-shell/fish-shell/files/6215191/regular-then-fish.log)

**Comment by faho** [comment]
Lovely: Apparently `less` won't use the alternate screen if stderr isn't connected to a terminal.

See e.g. `less file 2>/dev/null`.

In this case we *want* stderr to be silenced because we don't actually know if the man page *exists*.

I'm not sure what the alternative is.

**Comment by YaLTeR** [comment]
> See e.g. `less file 2>/dev/null`.

Yep, that also reproduces the issue.

**Comment by faho** [comment]
Turns out the alternative is awful:

```fish
    if man thing &>/dev/null
       man thing
```

**Comment by YaLTeR** [comment]
Seems like it works fine after that commit, thanks!

**Comment by faho** [comment]
This could be caused by https://github.com/gwsw/less/commit/4d4e6f467663a60778be6fd22aa5273e73afebff checking fd **2** for the tty to connect to. That means if you redirect fd 2 less won't believe it's in a terminal in *some* parts (but it obviously handles *input* and normal output, so it seems to be inconsistent).

I believe this is a bug in less (it's checking a different fd than it is writing to!), if anyone wants feel free to report it.

**Comment by zanchey** [comment]
Reported and fixed.

**Comment by YaLTeR** [comment]
Cheers!
