### ISSUE TITLE
$SHLVL bug

### ISSUE THREAD

**Issue by tjapro** [fish-shell/fish-shell#7864]
fish, version 3.2.1
Linux ... 5.11.8-200.fc33.x86_64 #1 SMP Mon Mar 22 01:35:01 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
xterm-256color
Comman prompt with Starship, but the bug is not affected.

See https://github.com/starship/starship/issues/2511 for more information.

The main bug is: when I start the shell (with Gnome Terminal), the $SHLVL is set to 2, and not to 1.
Then if I command `bash` the $SHLVL is set to 3, so that's correct.
This doesn't happen only with bash: it sets the $SHLVL to 1.

**Comment by ridiculousfish** [comment]
When fish starts, it sets SHLVL to 1 if unset, otherwise it increments it.

How are you starting fish? Is it possible you are starting fish from within .bashrc or similar?

**Comment by tjapro** [comment]
My default shell is fish.

config.fish file:
```
# TIAGO PROGRAMMER FISH FILE

# Init Starship Prompt
starship init fish | source

# Folders
alias pro "cd ~/Projects/personal/ && clear && ls"
alias cli "cd ~/Clients/ && clear && ls"

# Alias
alias e "exit"
alias la "ls -ah --group-directories-first --color=auto"
alias ls "ls -h --group-directories-first --color=auto"
alias ll "ls -h --group-directories-first --color=auto --format=long"
alias up "cd .. && clear && ls"
```

.bashrc file:
```
# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions

eval "$(starship init bash)"
```

**Comment by ridiculousfish** [comment]
This suggests that something else is launching fish from within another shell instance (may or may not be fish). What is the process hierarchy here?

One way you can check is with `pstree -p $fish_pid`, that will show you if there is another shell instance as parent.

**Comment by tjapro** [comment]
```
fish(3607)─┬─pstree(3704)
           └─{fish}(3702)
```

**Comment by faho** [comment]
What seems to be happening here is that fish sets $SHLVL even in non-interactive shells. That means running

```fish
bash -c fish
```

increments $SHLVL by 1, but

```fish
fish -c fish
```

increments it by 2.

We should probably only adjust it when running interactively.

**Comment by tjapro** [comment]
So, what can I do?

**Comment by faho** [comment]
This isn't something that you work around by configuring something, so unless you want to make a PR: Nothing.

**Comment by faho** [comment]
Okay, it seems bash's weird automatic exec changes the behavior here:

```fish
> echo $SHLVL
1
> bash -c 'echo $SHLVL; bash'
2
>> echo $SHLVL
2
```

That behavior seems quite ridiculous, so we're just going to interpret $SHLVL to mean "depth of interactive shell sessions".
