### ISSUE TITLE
fish 3.2 regression: Space-prepended command added to history when created by "commandline --replace"

### ISSUE THREAD

**Issue by Korkman** [fish-shell/fish-shell#7868]
```
fish --version = 3.2.1
OS =  5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l GNU/Linux (Raspbian)
TERM = xterm-256color
```
Happens in unmodified environment. Did not happen in version 3.1.2.

Reproduction:
`commandline --replace " secret"`
Press enter, up. The command was appended to history although it was prepended with a space.

**Comment by faho** [comment]
No, 3.2 will now keep space-prepended entries in the current session, they just won't be persisted to disk.

That's on purpose, see #7590.

**Comment by Korkman** [comment]
Ah, I see. Thank you for the swift reply. Since this has nothing to do with `commandline --replace`, I'll edit the title so it doesn't confuse anyone reading this.

**Comment by Korkman** [comment]
@faho Some clarification, is there a way to prevent history being added to the session at all? I have a very special case where I execute "stealth commands" with `commandline` which require to be executed on the user's prompt, but are entirely pointless to keep in any form of history.

**Comment by faho** [comment]
>is there a way to prevent history being added to the session at all? 

No.
