### ISSUE TITLE
Use portable `std::u32string` instead of `wchar_t`-based string

### ISSUE THREAD

**Issue by krobelus** [fish-shell/fish-shell#7878]
[Here](https://github.com/fish-shell/fish-shell/issues/6585#issuecomment-783669903) is some discussion on problems with character handling when `wchar_t` has less than 32 bit (apparently it's 16 on Windows).

[std::u32string](https://en.cppreference.com/w/cpp/string/basic_string) could solve this problem, without changing any behavior on platforms where `wchar_t` is already 32 bit. I haven't tested anything, so I could be very wrong.

**Comment by faho** [comment]
Unfortunately it's apparently not initializable with `L""` literals:

```gobbledygook
../src/builtin_complete.cpp:388:44: error: invalid conversion from 'const wchar_t*' to 'const char32_t*' [-fpermissive]
  388 |                     string_suffixes_string(L" ", faux_cmdline_with_completion)) {
      |                                            ^~~~
      |                                            |
      |                                            const wchar_t*
```

We would have to replace every single use of `L""` with `U""` if I'm reading https://en.cppreference.com/w/cpp/language/string_literal correctly, and I'm not sure how this works with any OS-APIs that use wchar like wcstod or wcscasecmp.

To be honest I'm not enthusiastic about non-WSL windows support to begin with, so I'm not sure if it's worth completely restructuring our string handling for it. If we did a large change it would probably be to get away from "wide" characters for the most part.

**Comment by krobelus** [comment]
Yeah, that's certainly not worth the churn - it's quite the academic issue. We should probably declare non-WSL Windows unsupported.

**Comment by ridiculousfish** [comment]
Some day we will just implement our own good string class, and that will solve this issue.

**Comment by zanchey** [comment]
It still sometimes blows my mind that C++ is still so bad at this. Is it any better in newer standards?
