### ISSUE TITLE
Editing a function adds a comment line

### ISSUE THREAD

**Issue by lucas979797** [fish-shell/fish-shell#7879]
#### System Info:
Fish Version: `3.2.1`
OS: macos Big Sur

#### Problem:
When using `funced` to edit a function with $EDITOR set to `code -n -w` or `nano`, a comment line is being added to the file where the function is defined along the lines of:

```
# Defined in /var/folders/l6/4wtwvg1903l93zlk1_5rzrzr0000gn/T//fish.43EOEP/dotupd.fish @ line 1
```
or if using `funced -i`:
```
# Defined Interactively
```

This didn't used to happen so I'm wondering if it's a feature of a new update? I'm not able to find any configuration info about it in the docs. I'd like to be able to turn this off as it changes every time I edit a function from the command line which makes my git commits messy. It's also noise that I'd rather not look at.

**Comment by faho** [comment]
Yeah I agree. I added a `--no-details` flag to `functions` to inhibit that comment, it's now used in `funced`.
