### ISSUE TITLE
Option to remove prefix from completion suggestions

### ISSUE THREAD

**Issue by sersorrel** [fish-shell/fish-shell#7883]
When I autocomplete a path in Fish, it looks like this:

![image](https://user-images.githubusercontent.com/9433472/113168597-b8241e80-923c-11eb-8445-ac2f25abe543.png)

whereas when I do the same in Bash (possibly influenced by [my ~/.inputrc](https://github.com/sersorrel/dotfiles/blob/e78706c5962bf806936b9d8f8c8c9a419dfc3244/dot_inputrc)), it looks like this:

![image](https://user-images.githubusercontent.com/9433472/113168663-c4a87700-923c-11eb-8019-e6f704c7ec0d.png)

Here, it feels much easier to read the Bash completions – apart from the fact that useless directories like `__pycache__` aren't displayed in Bash (#4440), the `…erlay.rs/` prefix in Fish is visually noisy and doesn't add anything, since I already have the path I'm completing right there before the cursor.

Is there a way in Fish to remove this prefix? If not, could there be one?

**Comment by faho** [comment]
There is not, and I don't think we want one.

The prefix does add something, namely that that's the token you're about to input. It's also colored separately so you know it's distinct from the new bit.

Sorry, but no.

**Comment by sersorrel** [comment]
>that that's the token you're about to input

...but... it's not?

It's already there. The bit I'm about to input is `Cargo.toml` or whatever.

anyway, sure.
