### ISSUE TITLE
errors and unwanted behavior when using <path>/** on big folder - can breaks OS when using sudo

### ISSUE THREAD

**Issue by LeSnake04** [fish-shell/fish-shell#7887]
fish version: 3.2.1
kernel: 5.11.11-zen1-1-zen
OS: archlinux (endeavourOS)

When I used `sudo chmod 666 /home/<user>/.steam/steam/steamapps/compatdata/40970/pfx/c:/**` my entire system broke. The number of matches is barely smaller than the maximum allowed matches. 

It started normal, but then MANY error messages came, my xfce panels broke immediately and when restarted my system I got a kernel panik 

(luckily i made a timeshift backup a few hours ago)

Tomorrow in will try to catch the error message.

**Comment by krobelus** [comment]
Very strange; an error would indeed be helpful. Maybe run `count yourpath/**` first. The maximum number of expansions is around 500k.

> sudo chmod 666 /home/<user>/.steam/steam/steamapps/compatdata/40970/pfx/c:/**

You probably don't need `sudo` here.
Also 666 is not useful for directories, use `find the-path -type d -exec chmod 755 {} +` to fix it.
You probably wanted something like `find the-path -type f -exec chmod 666 {} +` to only change permissions of files.

**Comment by LeSnake04** [comment]
Thanks for the advice!

I defiantly need to use sudo, since some files in the folder belong to root (I don't know why proton and wine does  create files owned by root, but this isnt the topic here)

I gonna try count and the find commands without the exec path. Hopefully I can catch the error message without breaking something

**Comment by faho** [comment]
@LeSnake04 What you are doing is **highly suspect**.

This should indeed not have any root-owned files, it should also not have 500k files or lead to a kernel panic or your system breaking.

I'm suspecting that directory has a symlink in it and fish dutifully follows it.

Also, you probably want `chmod -R yourpath` instead of the glob.

**Comment by LeSnake04** [comment]
count returns just 2264. 

and `find ~/.steam/steam/steamapps/compatdata/40970/pfx/dosdevices/c:/** works just fine`

I suspect @faho is right and there is a symlink to a linux system folder, causing the kernel panik. I wasnt aware chmod had a recursive option.

**Comment by LeSnake04** [comment]
With chmod 666 -R everything worked just fine. So @faho  was right. 

Thank you very much for the help!

**Comment by LeSnake04** [comment]
~/.steam/steam/steamapps/compatdata/40970/pfx/dosdevices/c:/ did not only included the wine enviroment, but also links to the linux root path… 

This explains the kernel panic.
