### ISSUE TITLE
[Question] Print array in multiple line without loop

### ISSUE THREAD

**Issue by fanliver** [fish-shell/fish-shell#7888]
Fish version: 3.2.1
OS: MacOS Catalina

How to print each array element in one line? 
For example, my expectation:
```
$ set my_array one two three 'number four'
$ print_somehow $my_array
one
two
three
number four
```

Of couse, I can use `for` to loop through the array and `echo` each element. I am wondering whether there is any built-in function to do that.

I tried `string split` but it was not my expectation:
```
$ string split ' ' $my_array
one
two
three
number
four
```

To achieve the expectation, I had to use `string join` to join the array into string with a separator, then `string split` with that separator.
```
$ string join '>>>' $my_array | string split '>>>'
one
two
three
number four
```
Is there a better way to do it?

**Comment by faho** [comment]
printf %s\n $my_array
