### ISSUE TITLE
"`$pipestatus`" doesn't change when using "`not`"

### ISSUE THREAD

**Issue by mingcenwei** [fish-shell/fish-shell#7894]
Tested on the following 2 systems (with `sh -c 'env HOME=$(mktemp -d) fish'`)

```shell
$ fish --version
fish, version 3.2.1
$ echo $version
3.2.1
$ uname -a
Linux XXX 5.11.10-arch1-1 #1 SMP PREEMPT Fri, 26 Mar 2021 00:11:29 +0000 x86_64 GNU/Linux
$ echo $TERM
xterm-256color
```

```shell
$ fish --version
fish, version 3.1.0
$ echo $version
3.1.0
$ uname -a
Linux YYY 5.4.0-66-generic #74-Ubuntu SMP Wed Jan 27 22:54:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ echo $TERM
screen
```

Returned ~~status codes~~ `$pipestatus` of all the following 4 commands are ~~0~~ `0 0`.
`true | true`
`not true | true`
`true | not true`
`not true | not true`

**Comment by faho** [comment]
>Returned status codes of all the following 4 commands are 0.

Can't reproduce. `not true | true` and `true | not true` both return 1 for me, which would also be correct.

**Comment by mingcenwei** [comment]
Oh, I found it's actually a problem with $pipestatus (I use it in the prompt):
```shell
$ not true
$ echo $status
1
$ not true
$ echo $pipestatus
0
```

**Comment by mingcenwei** [comment]
```shell
$ not true | not true ; echo $pipestatus
0 0
```'

**Comment by faho** [comment]
Ah, that's to be expected. pipestatus applies to the *unmodified* status of each separate process. `not` only applies to the $status at the end.

**Comment by mingcenwei** [comment]
Can it be imporved? The default prompt of fish using `$pipestatus` as well, and  it will be confusing for new users.

**Comment by faho** [comment]
The default prompt uses `__fish_print_pipestatus`, and that knows how to handle it.

Not applying not to $pipestatus is *correct*, because there isn't any particular process to apply it to.

**Comment by mingcenwei** [comment]
It seems that `__fish_print_pipestatus` doesn't handle it, because after running `sh -c 'env HOME=$(mktemp -d) fish')`, the prompt still won't show `[1]` when running `not true` (though you can say it's the correct behavior, since the subprocess exits normally).

**Comment by faho** [comment]
That was a bug, fixed in 3.2.0. You're testing it with 3.1.0.

**Comment by mingcenwei** [comment]
Yes, it has been fixed. Thank you.

BTW, I suggest changing the command `sh -c 'env HOME=$(mktemp -d) fish'` in the issue template to `sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'`. Otherwise old configs will still be in effect if the user has set the environment variable `XDG_CONFIG_HOME` to `$HOME/.config`

**Comment by zanchey** [comment]
I wonder about `env -i`. fish should be robust in the face of missing `HOME` and `USER` environment variables now, but TERM needs to be passed through.
