### ISSUE TITLE
fish_config does not load on WSL 2.

### ISSUE THREAD

**Issue by nosed1ve** [fish-shell/fish-shell#7895]
Please tell us which fish version you are using by executing the following:

  fish --version
  echo $version

fish 3.2.1

Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

Windows terminal, Windows 10 build 19043.899

Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:

  sh -c 'env HOME=$(mktemp -d) fish'

didnt change output

Tell us how to reproduce the problem. Including an asciinema.org recording is useful for problems that involve the visual display of fish output such as its prompt.

![image](https://user-images.githubusercontent.com/67145097/113411162-b42a0500-93d2-11eb-92cc-735b42a79be1.png)
thats how it looks like each time.

It worked in fish 3.1, after changing the `is_wsl()` function to look for a lowercase `"microsoft"` in `/etc/os-release`, but in 3.2, it doesnt work anymore. I do not know exactly what the issue is, or else I would've tried to make a PR. If someone can point the problem, I can try to make a PR though.

**Comment by faho** [comment]
Okay, I have finally gotten a change to test this in WSL2 and it works for me. If the browser is opened that also means the special WSL workaround has been applied, so we're looking at something else.

What we would need is the output in the terminal you run `fish_config` in, as well as whatever the javascript console in your browser (press ctrl-shift-k or ctrl-shift-i) says.

**Comment by nosed1ve** [comment]
Do you want me to try if it works with the `head` build or the stable 3.2 release?

**Comment by faho** [comment]
There shouldn't really be any differences, given that there have been 2 commits to webconfig.py since 3.2.2.

**Comment by nosed1ve** [comment]
Alright, I'll report back with the javascript console SS and terminal output in sometime.

**Comment by nosed1ve** [comment]
![image](https://user-images.githubusercontent.com/67145097/115105733-65599f00-9f7e-11eb-89d5-fc396fdbfa42.png)
![image](https://user-images.githubusercontent.com/67145097/115105764-8c17d580-9f7e-11eb-8319-f31c16d178d5.png)
![image](https://user-images.githubusercontent.com/67145097/115105770-93d77a00-9f7e-11eb-81dc-22295f5332b4.png)

The page colour turns grey in a few seconds, then nothing happens. I attached the screenshots of the console and terminal output above, this is on fish 3.2.2, on fish 3.2.0, the page did not even turn grey so I guess there is some improvement since 3.2.0.

**Comment by faho** [comment]
That looks like your system just doesn't allow opening this page for some reason, either some WSL configuration or your browser.

On our end everything appears to be okay - this starts cmd.exe, which opens the browser. I'm not sure why that "UNC Paths are not supported" error appears, but it shouldn't change anything as we pass the full url.

Sorry, there's not a lot I can suggest here.

**Comment by nosed1ve** [comment]
The UNC paths not supported pops up on 3.1, where fish_config works as well, so mabye that is intended. I do not think it is my system or wsl config, theres nothing thats wsl specific that ive configured for my distro, and fish_config worked just fine on fish 3.1, something in 3.2 broke it I believe.

**Comment by zanchey** [comment]
The new Angular version is a possible culprit, though with that behaviour an antivirus or adware blocker is high on my suspicion list - reloading the tab with the "network" tab of the developer tools open might be interesting.

**Comment by nosed1ve** [comment]
![image](https://user-images.githubusercontent.com/67145097/115343498-a98caf80-a1c9-11eb-9061-db7e135054b4.png)

Here is a screenshot of the network tab, also just in case, I did turn off uBlock origin for localhost and test, the result did not change.

**Comment by faho** [comment]
Well, that's loading nothing. If you've hit ctrl+r, this should look like:

![Screenshot_20210420_075514](https://user-images.githubusercontent.com/5185367/115344495-c5825800-a1ad-11eb-9cfd-67bb5ba56cf2.png)

**Comment by nosed1ve** [comment]
That does not happen for me even if i ctrl-R

**Comment by faho** [comment]
Well, in that case that's your problem. Something on your system is blocking the communication.

Like @zanchey said check your antivirus, adblocker and firewall. Possibly try in another browser.

**Comment by nosed1ve** [comment]
Ah thanks for the help, I'll check my adblocker in that case, il close this issue for now.
