### ISSUE TITLE
[Feature] Build https://fishshell.com/docs/ with Docusaurus

### ISSUE THREAD

**Issue by thernstig** [fish-shell/fish-shell#7896]
For those of us who have stumbled on the, increasingly popular, Docusaurus want every docs page to be built with it. Docusaurus builds websites from markdown (as so many other tools) but it is amazing with its search capabilities and more. Try for example https://playwright.dev/ or https://jestjs.io/docs/getting-started both that recently migrated to Dousaurus.

Just a friendly suggestion. Shot it down if you want, but I believe it would enhance the docs.

**Comment by faho** [comment]
No, sorry.

We are happy with our docs as they are

**Comment by thernstig** [comment]
All fair. It's rather subjective anyway 😃
