### ISSUE TITLE
What to do if fish can't use variable as value in for grammar

### ISSUE THREAD

**Issue by happyeggchen** [fish-shell/fish-shell#7898]
fish version:3.1.2
OS info:debian buster
For example
```
set -g hi "lol lol 123 321"

for I in $hi
    echo $hi
end
```
It directly output $hi

**Comment by faho** [comment]
It's `for`, not `For`.

**Comment by happyeggchen** [comment]
> It's `for`, not `For`.

yes i know , it is for not For

**Comment by faho** [comment]
Could you try to explain your problem again?

Your example here has a few issues (I edited my last comment to point them out), and I'm not sure how or why that relates to your problem.

**Comment by faho** [comment]
Let me try to clarify:

```fish
set -g hi "lol lol 123 321"

for I in $hi
    echo $hi
end
```

Let's replace $hi with its value here:

```fish
for I in "lol lol 123 321"
    echo "lol lol 123 321"
end
```

See how that might print `lol lol 123 321` once? Fish does not do word-splitting, so if you set $hi to `"lol lol 123 321"`, that's the value that will be used when you use the variable without quotes. So it's like we've just done here.

There is no way fish can't "use this variable as value in for grammar". It uses the variable as you told it.

What I think you meant was

```fish
set -g hi lol lol 123 321

for I in $hi
   echo $I
end
```

which will print

```
lol
lol
123
321
```

See how this sets $hi without quotes, so it's now four separate elements? Also it uses the actual loop variable in the loop.

**Comment by happyeggchen** [comment]
```
set -g medias (zenity --list --title "Noice for linux" --text "NFL1.0" --list --checklist --column "Picker" --column "Sounds" false coffee_shop false fire false forest false night false rain false sea false storm false wind | sed 's/|/\ /g')
            for medias_play in $medias
              echo $medias_play
            end
```

and the input is decided by zenity and user

the output is
```
coffee_shop fire
```

**Comment by faho** [comment]
Unlike bash, fish splits command substitutions only on *newlines*, not spaces.

That means your `sed` here is wrong, it would have to be `sed s/|/\n/g` - or alternatively just use `string split '|'`.

**Comment by happyeggchen** [comment]
thx it worked
