### ISSUE TITLE
fish may hang on exit if another process is foreground

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#7901]
On Mac, with fish 3.2.1:  Launch fish, launch zsh from within fish, and then close the window. We will see that zsh exits but fish hangs.

fish is hanging because it is trying to assign the tty back to the original owner, but fish is not in control of the tty. Prior to the fix for #7060 this would have succeeded; but with #7060 we allow SIGTTOU, so we get SIGSTOP (which cannot be ignored).

**Comment by ridiculousfish** [comment]
Fixed in 3.2.2 as fa890dc2336ebb02d30051de74a02ca0fdc3b5a6, master as ed51e2baacc47c831a14ed60a9363f5dbb0b7955

**Comment by zanchey** [comment]
I couldn't reproduce this on Linux or FreeBSD, so I've noted it as macOS-only in the release notes.
