### ISSUE TITLE
Slow performance when in a remote filesystem mount

### ISSUE THREAD

**Issue by CRISPYricePC** [fish-shell/fish-shell#7903]
Fish: version 3.2.1
Distribution: Fedora 33

Tested in a temp home environment: `sh -c 'env HOME=$(mktemp -d) fish'`

**Reproduction**:
- Mount an AWS bucket to `/mnt/mybucket` (I tested with s3fs and goofys, same results)
- In `bash`:
```bash
$ cd /mnt/mybucket
# no delay
$ ls
Documents readme.md
$ 
```
- in `fish`
```fish
$ cd /mnt/mybucket
# ~0.5s delay
$ ls
# no delay
Documents readme.md
# ~0.5s delay
$
```

I'm wondering what causes this slowdown when mounted to a remote filesystem. Is it possible that this can be disabled when `$PWD` is in a particular mountpoint?

**Comment by zanchey** [comment]
Probably your prompt contains a call to `fish_git_prompt` or `fish_vcs_prompt`. You could make it conditional on those mountpoints.

**Comment by CRISPYricePC** [comment]
I think that might be partly the cause of the slowdown. Running with my prompt (starship) sourced, it does take a lot longer between commands. Does the default fish prompt also call `fish_git_prompt`?

**Comment by faho** [comment]
Yes, the default fish prompt calls `fish_git_prompt`, `starship` however is a rust binary that has its own git logic, entirely separate from fish. In that case it would be a starship bug.

(when it comes to `fish_git_prompt` there are a bunch of settings that can cause a slowdown, especially anything that requires git to look up all files like the informative status. see [the docs](https://fishshell.com/docs/current/cmds/fish_git_prompt.html))

**Comment by CRISPYricePC** [comment]
Thanks for this, I agree I shouldn't be putting starship complaints over here, and a quick test shows that I get exactly the same slowdown when I source starship on bash.

In terms of disabling `fish_git_prompt` if I'm not using starship, I'm not sure how I could do it. Is there an easy way to detect if the current directory is a subdirectory of another?

**Comment by faho** [comment]
>Is there an easy way to detect if the current directory is a subdirectory of another?

The simplest?

1. Get physical PWD
2. Check the string prefix

Something like

```fish
function is_network_mount
    set -l networkmounts /path/one /path/two
    set -l mypwd (pwd -P)
    for p in $networkmounts
        # (dirty, will fail if there's a "*" in the networkmount)
        if string match -q "$p/*" $mypwd
            return 0
        end
    end
    return 1
end
```

Or, if you have `findmnt` from util-linux, you can ask it to give you the filesystem type of the mount you're on:

```fish
findmnt --target $PWD -no fstype
```

will print something like "ext4" or "tmpfs". You'd presumably check this for "cifs" or "smbfs" or whatever the fancy network filesystems are called nowadays.

Or, see the docs, and disable the things that take the time - just checking for the branch and such should barely take any time at all, so you'd disable showing untracked files with

```fish
git config --local bash.showUntrackedFiles false
```

(yes, that's a "bash", we reuse these settings)

in the offending git repo. Potentially do the same with "bash.showInformativeStatus" and "bash.showDirtyState".

**Comment by zanchey** [comment]
`df --output=fstype .` is easiest if you have GNU df.

**Comment by CRISPYricePC** [comment]
> > Is there an easy way to detect if the current directory is a subdirectory of another?
> 
> The simplest?
> 
> 1. Get physical PWD
> 2. Check the string prefix
> 
> Something like
> 
> ```fish
> function is_network_mount
>     set -l networkmounts /path/one /path/two
>     set -l mypwd (pwd -P)
>     for p in $networkmounts
>         # (dirty, will fail if there's a "*" in the networkmount)
>         if string match -q "$p/*" $mypwd
>             return 0
>         end
>     end
>     return 1
> end
> ```
> 
> Or, if you have `findmnt` from util-linux, you can ask it to give you the filesystem type of the mount you're on:
> 
> ```fish
> findmnt --target $PWD -no fstype
> ```
> 
> will print something like "ext4" or "tmpfs". You'd presumably check this for "cifs" or "smbfs" or whatever the fancy network filesystems are called nowadays.
> 
> Or, see the docs, and disable the things that take the time - just checking for the branch and such should barely take any time at all, so you'd disable showing untracked files with
> 
> ```fish
> git config --local bash.showUntrackedFiles false
> ```
> 
> (yes, that's a "bash", we reuse these settings)
> 
> in the offending git repo. Potentially do the same with "bash.showInformativeStatus" and "bash.showDirtyState".

This works perfectly. I'll close this now, thanks
