### ISSUE TITLE
Default prompt / __fish_print_pipestatus can't handle TERM=dumb

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#7904]
fish, version 3.2.1-90-ge56d8a8e5

```
env -i HOME=(mktemp -d) TERM=dumb ~/prefix/bin/fish
Welcome to fish, the friendly interactive shell          
Type help for instructions on how to use fish                                                                                  
error: missing argument                      
in function '__fish_print_pipestatus' with arguments '\[ \] \| 0'
        called on line 1 of file /home/wheel/zanchey/prefix/share/fish/functions/fish_prompt.fish
in command substitution      
        called on line 33 of file /home/wheel/zanchey/prefix/share/fish/functions/fish_prompt.fish
in function 'fish_prompt'        
in command substitution
```

This is because `__fish_print_pipestatus` gets called with a number of `set_color` command substitutions as arguments, which are empty when `TERM` is "dumb".

**Comment by faho** [comment]
This is a specific manifestation of #5443 - if `set_color` printed something sensible when run with no arguments (or TERM=dumb) this wouldn't be a problem.

I still have no idea *what*, tho - some no-op escape sequence would be great. The alternative is to have some way to quote a command substitution - `"$(set_color)"` would just expand to the same as `""`, an empty string.

Still worth fixing here, tho, and ideally *in* `__fish_print_pipestatus`. We might just want to use `argparse` and pass the colors as options, this current argument passing scheme is awkward.
