### ISSUE TITLE
Function completion descriptions are overly wordy

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#7911]
Consider the following scenario where I want to find a function I've defined that I know begins with `__fish` and has `git` somewhere in the name:

```fish
$ __fish_<tab>
# ctrl-s
# type "git"
```

### Actual

![image](https://user-images.githubusercontent.com/8544900/114028587-8defe380-9870-11eb-9da3-777b10538ee0.png)

None of these results are what I expect, because the description is being searched, which can contain all sorts of information that is irrelevant to the command I'm trying to recall.

### Expected

Just commands that contain the exact substring "git".

**Comment by faho** [comment]
No it *should* search the descriptions. That allows you to find more stuff, and is super helpful e.g. to find a git commit.

In this case the descriptions are overzealous - the entire definition helps nobody.
