### ISSUE TITLE
Command substitution with multiple arguments

### ISSUE THREAD

**Issue by tflori** [fish-shell/fish-shell#7913]
I'm using fish shell version 3.2.1 on manjaro linux with kernel 5.10.23 in a Konsole terminal. The problem is not related to my config (also appears in an empty $HOME).

You may or may not know the `pkg-config` command. The output is used to configure the c compiler. Example:

```console
$ pkg-config --cflags --libs cairo
-I/usr/include/cairo -I/usr/include/lzo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -lcairo
```
It is important that each parameter is separated. And I don't see any way in fish to do so I only get one parameter out of it. A simple dump of the passed arguments show that it gets one parameter:

```console
$ cat test.php
<?php

var_dump($_SERVER['argv']);
$ php test.php (pkg-config --cflags --libs cairo)
array(2) {
  [0]=>
  string(8) "test.php"
  [1]=>
  string(197) "-I/usr/include/cairo -I/usr/include/lzo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/pixman-1 -lcairo "
}
```

Sorry if that is a repeated question but I can't find anything that helps. Maybe to put a solution to the FAQ?

**Comment by faho** [comment]
>Sorry if that is a repeated question but I can't find anything that helps. Maybe to put a solution to the FAQ?

See https://fishshell.com/docs/current/faq.html#my-command-pkg-config-gives-its-output-as-a-single-long-string

**Comment by tflori** [comment]
Damn! I don't know how I landed on the documentation and FAQ for version 2 :smile:
