### ISSUE TITLE
bind -k nul accept-autosuggestion not binding in config.fish

### ISSUE THREAD

**Issue by StratusFearMe21** [fish-shell/fish-shell#7922]
Please tell us which fish version you are using by executing the following:

  fish --version: `fish, version 3.2.1`
  echo $version: `3.2.1`

Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

- `Linux isaac-ms7978 5.9.16-1-MANJARO #1 SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020 x86_64 GNU/Linux`
- `xterm-kitty`

Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:

  sh -c 'env HOME=$(mktemp -d) fish'

**^^Did not help^^**

Tell us how to reproduce the problem. Including an asciinema.org recording is useful for problems that involve the visual display of fish output such as its prompt.

1. Put `bind -k nul accept-autosuggestion` in your config.fish
2. notice that Ctrl+Space does not work
3. run in the terminal `bind -k nul accept-autosuggestion`
4. It works now

What's happening is that after updating to fish 3.2.1-1, having `bind -k nul accept-autosuggestion` does not actually bind Ctrl+Space to anything. I can still run this command in the console and it will bind, but it appears that having it in config.fish is not enough.

**Comment by faho** [comment]
Ah, lovely. The default binding was missing `--preset`, so it's bound as a user binding.

And the bindings are only applied *after* config.fish (because you could set $fish_key_bindings there), so that overrides your own binding.

Path incoming.

The workaround is to put this into a function called `fish_user_key_bindings`:

```fish
function fish_user_key_bindings
    bind -k nul accept-autosuggestion
end
```

**Comment by StratusFearMe21** [comment]
Thanks for such a quick response, this worked!
