### ISSUE TITLE
fish_git_prompt: git statuses aren’t displayed in the same order if `$__fish_git_prompt_show_informative_status` is set or not

### ISSUE THREAD

**Issue by ariasuni** [fish-shell/fish-shell#7926]
When `$__fish_git_prompt_show_informative_status` is not set:
https://github.com/fish-shell/fish-shell/blob/f75cf5c16bf8fa43ba99180a8e4ba008d5ffc685/share/functions/fish_git_prompt.fish#L414-L418

https://github.com/fish-shell/fish-shell/blob/f75cf5c16bf8fa43ba99180a8e4ba008d5ffc685/share/functions/fish_git_prompt.fish#L446-L457

https://github.com/fish-shell/fish-shell/blob/f75cf5c16bf8fa43ba99180a8e4ba008d5ffc685/share/functions/fish_git_prompt.fish#L479-L480

When `$__fish_git_prompt_show_informative_status` is set:
https://github.com/fish-shell/fish-shell/blob/f75cf5c16bf8fa43ba99180a8e4ba008d5ffc685/share/functions/fish_git_prompt.fish#L513

In the first case, the order is: dirty, staged OR invalid, stash, untracked
In the second case, the order is: staged, invalid, dirty, untracked, stash

I believe the second order is more logical, because `git status` displays: staged, invalid, dirty, untracked in this order, and then putting the stash state at the end is the only logical place.

Here’s an example of running `git status` in a repository:

```
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

You have unmerged paths.
  (fix conflicts and run "git commit")
  (use "git merge --abort" to abort the merge)

Changes to be committed:
        modified:   src/theme/default_theme.rs

Unmerged paths:
  (use "git add <file>..." to mark resolution)
        both modified:   src/info/filetype.rs

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   Cargo.lock

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        centos7/
```

Note: when`$__fish_git_prompt_show_informative_status` is not set, I’m not able to get the `__fish_git_prompt_char_invalidstate` char to appear on the prompt.

---

fish 3.2.1

**Comment by faho** [comment]
Yeah, makes sense. I picked the informative order.

(also doing this I noticed that stagedstate wasn't printed if dirtystate wasn't supposed to be, which makes no sense)
