### ISSUE TITLE
Tab completions for DNF does not match local RPM files

### ISSUE THREAD

**Issue by audreytoskin** [fish-shell/fish-shell#7928]
(Here I'm talking about DNF, the system package manager for Fedora and other Linux distros in the Red Hat family.)

## The problem

<kbd>Tab</kbd> autocomplete suggestions for `sudo dnf install foo` matches package names in the system repos, but ignores local RPM files. Say if I downloaded the RPM package for `foo-bar`...

``` fish
sudo dnf install foo#<TAB>
```

...will show matches for `foo-quux` and `football` from the repos, but not the file `foo-bar-x.y.z-1.x86_64.rpm` in the current working directory.

Typing the filename prefix `foo` does show gray text which does match the local RPM file path, which I can autocomplete but hitting the right arrow. However, this only matches a single file, whereas <kbd>Tab</kbd> autocompletion could cycle through all matches. <kbd>Tab</kbd> autocompletion could also work on directories in the beginning of the file path:

``` fish
sudo dnf install ~/Down#<TAB>
```

...will not offer any matches for the `~/Downloads/` folder.

And there are no gray-text matches either if I type a filename _infix_, like `bar` or `x.y.z`.

## Reproducing

0. Test without user-specific settings, to rule out configuration issues.
  `sh -c 'env HOME=$(mktemp -d) fish'`
0. Download, say, [ProtonMail Bridge](https://protonmail.com/bridge/install) (or some other package).
  `wget "https://protonmail.com/download/bridge/protonmail-bridge-1.6.9-1.x86_64.rpm"`
0. Type partial DNF commands and observe which <kbd>Tab</kbd> or <kbd>→</kbd> autocompletion suggestions are available...

## System setup

- Fedora 33 Workstation x86_64
- fish 3.2.1, installed from main Fedora repos
- DNF 4.6.1
- Tilix 1.9.1 (VTE-based terminal)
- GNOME Shell 3.38.4

```
> fish --version
fish, version 3.2.1

> echo "$version"
3.2.1

> echo "$TERM"
xterm-256color

> tilix --version
Versions
	Tilix version: 1.9.1
	VTE version: 0.62
	GTK Version: 3.24.28

Tilix Special Features
	Notifications enabled=1
	Triggers enabled=0
	Badges enabled=1

> uname -a
Linux localhost 5.11.11-200.fc33.x86_64 #1 SMP Tue Mar 30 16:53:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by zanchey** [comment]
Does this do the job?

`complete -c dnf -n "__fish_seen_subcommand_from install" -xa "(__dnf_list_available_packages) (__fish_complete_suffix .rpm)"`

**Comment by audreytoskin** [comment]
Yup, running that `complete` command lets me do <kbd>Tab</kbd> completions on local files and folders now. I guess I could add that to my `config.fish` until it merges here. Thanks!
