### ISSUE TITLE
TSan tests hang on locale.fish

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#7934]
On github actions, the threadsanitizer tests seem to *sometimes* hang while running tests/checks/locale.fish. Unless manually cancelled, these run for at least an hour, probably until hitting some github-imposed limit.

I have no idea what causes this or since when it happens, but I'll disable this test until we can figure out what it is.

See e.g. https://github.com/fish-shell/fish-shell/pull/7933/checks?check_run_id=2353631097:

```
Testing file checks/job-ids.fish ... ok (180 ms)
Testing file checks/jobs.fish ... ok (5459 ms)
Testing file checks/line-continuation.fish ... ok (76 ms)
Testing file checks/line-number.fish ... ok (111 ms)
Error: The operation was canceled.
```

**Comment by faho** [comment]
I can't reproduce this locally even running `ninja test_fishscript` in a loop for an hour, with TSAN turned on, using clang 11.1.0

**Comment by ridiculousfish** [comment]
Worth mentioning is the Docker tsan build. From fish dir:

    ./docker/docker_run_tests.sh docker/bionic-tsan-clang.Dockerfile

the intent of this docker image is to match the GitHub actions as close as possible

**Comment by faho** [comment]
Alright, I've not seen this for a while so I'm closing.
