### ISSUE TITLE
Fish prompt bug with ttf-jetbrains-monn

### ISSUE THREAD

**Issue by silencercore** [fish-shell/fish-shell#7937]
hello all
after install ttf-jetbrains-mono my beautiful prompt changed
![IMG_0038](https://user-images.githubusercontent.com/82746298/115135467-e885fe00-a02d-11eb-9e01-b1cf0561af9b.jpeg)

**Comment by silencercore** [comment]
thanks for help

**Comment by faho** [comment]
This is very much not a fish problem, nor actually a *bug* in anything.

Fish has no control over which font is used to render text - it just sends the text, and the *terminal then picks the font and renders it*.

And you installed a new font and your terminal decided to use that font, which also isn't *wrong* per se. So you simply need to tell your terminal to use the old font again.
