### ISSUE TITLE
string match broken with multiline input

### ISSUE THREAD

**Issue by lelgenio** [fish-shell/fish-shell#7938]
## My information
```bash
~> fish --version
fish, versão 3.2.1
~> echo $version
3.2.1
~> uname -a
Linux artix-i15 5.11.13-zen1-1-zen #1 ZEN SMP PREEMPT Sun, 11 Apr 2021 10:10:31 +0000 x86_64 GNU/Linux
```

## How to reproduce
```bash
~> sh -c 'env HOME=$(mktemp -d) fish'
~> echo "100 101" | string match -ra '(?<nums>\d+)'
100
100
101
101
~> echo $nums # Ok
100 101
~> echo "100 101" | string match -qra '(?<nums>\d+)'
~> echo $nums # Ok
100 101
~> seq 100 101 | string match -ra '(?<nums>\d+)'
100
100
101
101
~> echo $nums # No output?

~> seq 100 101 | string match -qra '(?<nums>\d+)'
~> echo $nums # Only matches first?
100
```
I expected all of them to have the same result.

I bet there's no problem at all and i'm just missing something :roll_eyes:

**Comment by ridiculousfish** [comment]
Nope it's real, well found!

**Comment by faho** [comment]
There's a few things here:

1. Variables are only imported for *the first matching argument*. We don't have lists of lists, and capturing groups can match multiple times, so anything else doesn't seem feasible. You demonstrated this yourself with the first example
2. `string` handles input via stdin as one argument per line, so this only imports the matches for the first line.

This is currently documented:

>It will create a variable with the name of the group, in the default scope, for each named capturing group, and set it to the value of the capturing group in the first matched argument.

I'm not sure there is better behavior here - how do you handle `echo "100 101"\n"102 103"`? Do you collapse it so $num becomes [100, 101, 102, 103]?

(tbh I've so far not found a great use case for variable importing to begin with, and this depends on what you want to *do* with it)

**Comment by ridiculousfish** [comment]
The problematic case is `seq 100 101 | string match -ra '(?<nums>\d+)'`. It seems obvious that this should set `$nums` to something. I plan to keep it the first argument, so it will output 100, as documented.

**Comment by lelgenio** [comment]
I don't understand why default to ignoring other arguments instead of letting the user be explicit by using `$myvar[1]`.

**Comment by krobelus** [comment]
@lelgenio the problem is that you can have something like

`string match -qra '(?<nums>\d)' '1 2' '3 4'`

so the array is already used to access all matches in the first argument (or input line).
Really depends on the use case which one is better.
