### ISSUE TITLE
pushd and popd man pages use wrong directory stack order in examples

### ISSUE THREAD

**Issue by alvinseville7cf** [fish-shell/fish-shell#7940]
Fish version: 3.1.0
OS: Linux DESKTOP-7DCKUBO 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

# Description
Stack top is on the left side when using pushd from terminal:
```bash
alvinseville7cf@DESKTOP-7DCKUBO ~> pushd /usr
alvinseville7cf@DESKTOP-7DCKUBO /usr> pushd local/
alvinseville7cf@DESKTOP-7DCKUBO /u/local> pushd bin/
alvinseville7cf@DESKTOP-7DCKUBO /u/l/bin> dirs
/usr/local/bin /usr/local /usr ~
```

But pushd and popd man pages presents wrong directory stack order in examples:
![image](https://user-images.githubusercontent.com/42812113/115184007-4430b400-a120-11eb-8fb1-104dde1346bb.png)
![image](https://user-images.githubusercontent.com/42812113/115184023-51e63980-a120-11eb-8b30-181b979d8c27.png)

**Comment by ridiculousfish** [comment]
Fixed the docs - thanks for filing!
