### ISSUE TITLE
Unexpected push -n behaviour

### ISSUE THREAD

**Issue by alvinseville7cf** [fish-shell/fish-shell#7941]
Fish version: 3.1.0
OS: Linux DESKTOP-7DCKUBO 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

# Description
```bash
alvinseville7cf@DESKTOP-7DCKUBO ~/1/2/3/4/5/6/7/8/9> dirs
~/1/2/3/4/5/6/7/8/9 ~/1/2/3/4/5/6/7/8 ~/1/2/3/4/5/6/7 ~/1/2/3/4/5/6 ~/1/2/3/4/5 ~/1/2/3/4 ~/1/2/3 ~/1/2 ~/1 ~

alvinseville7cf@DESKTOP-7DCKUBO ~/1/2/3/4/5/6/7/8/9> pushd +2
~/1/2/3/4/5/6/7 ~/1/2/3/4/5/6 ~/1/2/3/4/5 ~/1/2/3/4 ~/1/2/3 ~/1/2 ~/1 ~ ~/1/2/3/4/5/6/7/8/9 ~/1/2/3/4/5/6/7/8

alvinseville7cf@DESKTOP-7DCKUBO ~/1/2/3/4/5/6/7> pushd -2
~ ~/1/2/3/4/5/6/7/8/9 ~/1/2/3/4/5/6/7/8 ~/1/2/3/4/5/6/7 ~/1/2/3/4/5/6 ~/1/2/3/4/5 ~/1/2/3/4 ~/1/2/3 ~/1/2 ~/1
```
- While moving two directories to the end by pushd +2 - everything works fine.
- But doing reverse action produces ~ at the stack top.

What am I missing? I've expected to see: `~/1/2/3/4/5/6/7/8/9 ~/1/2/3/4/5/6/7/8 ~/1/2/3/4/5/6/7 ~/1/2/3/4/5/6 ~/1/2/3/4/5 ~/1/2/3/4 ~/1/2/3 ~/1/2 ~/1 ~` after pushd -2.

**Comment by faho** [comment]
Fixed by #6947, upgrade to fish 3.2.2
