### ISSUE TITLE
MacOS constantly fails bind tests involving escape timeout

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#7942]
Since the push from e299f89db30718fc543ebac15c58f538ee403638..7a556ec6f21f16b528be3fb94f5160e2209c3cbf, macos on Github Actions fails the bind.py test almost always. Now it's up to 5 out of 7 times, all in some tests that involve the escape timeout.

I'm guessing it's bd72791340a57fdad590234707a02a57ea9adefc, but as always I have no way to test this and I don't even know if it happens on actual hardware.

**Comment by ridiculousfish** [comment]
I think I can repro locally if I decrease the timeout - bisects to 060ce4f7daf368ed248be2e43eadcc44431fca4c

**Comment by krobelus** [comment]
Still happens sometimes, the CI failed 1/10 times for me on current master (15e265f2097c4ba79a7bd605b3e2fa2f9a3e0c1b).
(With #7952 it failed 14/52, though that's probably unrelated),

**Comment by faho** [comment]
2b0b0fe0429055c80c2c8cd3272f2855819b762b now turns the bind tests on Github Actions on macOS off.

They failed 3/10 times in the last 10 tests before, and that's just too much noise (and that's *with* trying them twice - I've not looked into how many of the successful runs had one failure).

As far as I know they don't actually fail on actual systems, and the bind system works properly on those, so it's down to GA just providing too little power to deal with. The alternative is to up the timeouts on macOS, but I've done that a few times and I've given up. If anyone on macOS cares enough, test it and provide a PR.

Until then, I'm counting this as fixed.
