### ISSUE TITLE
Dynamic Options for Completion

### ISSUE THREAD

**Issue by rliebz** [fish-shell/fish-shell#7943]
### Feature Description
The `complete` command currently defines a way to dynamically define arguments through the `--arguments` flag. There is not, however, a similar way to define completely dynamic options.

To give an example, if we had a binary `foo` that could dynamically list its own sub-commands with a `--get-sub-commands` flag, we can define completions for those, assuming that `--get-sub-commands` returns newline-separated values with an optional tab-separated description:

```fish
complete -c foo -a "(foo --get-sub-commands)"
```

What I would like to see is a flag for defining dynamic options in the same manner. Assuming we had some flag `-?` (naming is hard) that had some syntax to define a short, long, and/or old-style flag with a description, we could do the same for dynamically defining flags:

```fish
complete -c foo -? "(foo --get-options)"
```

### Use Case

I have a CLI application that dynamically defines commands and options based on a config file in the working directory. Think something like `make`, which already defines "commands" using a local directory, but one that also might define options.

With the following config:

```yaml
my-cmd:
  options:
    my-flag:
      short: f
      description: A custom flag
    other-flag:
      description: A different flag
```
 
The goal is to be able to dynamically generate functionality equivalent to the following:

```fish
complete ... -l my-flag -s f -d "A custom flag"
complete ... -l other-flag -d "A different flag"
```

### Potential Designs

Admittedly, the design of listing arguments with an optional tab-separated description is incredibly effective for defining arguments, but does not translate well to flags, which may need to map some number of short/long/old style flags to the same thing. 

These ideas are not necessarily up to par with usability, edge cases, etc.—the exact syntax is less interesting to me than whether or not the feature exists. I'm mostly including these examples for the sake of illustration.

1. Specify all variants of a flag separated by tabs, followed by an optional description. This has the advantage of being incredibly similar to the dynamic arguments syntax, but has the disadvantage of implicitly defining short/long/old style based on the number of `-` and length of the flag name, also making it impossible to define a single-letter old-style flag:
  ```
  >>> foo --get-options
  -f	--flag	Some Flag
  -g	Other flag
  --help
  ```

2. Accept the same syntax for defining flags, just as newline separated flags passed by a command substitution. This has the advantage of using a familiar syntax and the flexibility of that syntax, but the disadvantage of not matching with what `--arguments` takes today:
  ```
  >>> foo --get-options
  -s f -l flag -d 'Some flag'
  -s g -d 'Other flag'
  -l help
  ```

**Comment by faho** [comment]
This... already basically works?

```fish
function foo
    echo -- -f\t"Some flag"
    echo -- --flag\t"Some flag"
    echo -- -g\t"Other flag"
    echo -- --help
end
complete -c foo -a '(foo)'

# or

complete -c foo -a '-f\t"Some flag" --flag\t"Some flag" -g\t"Other flag" --help'
```

Or whatever else you want to do generates the options.

The only thing that's not working is option grouping (`foo -fg` won't suggest the `g`), and that's not super critical and should be fixable.

**Comment by rliebz** [comment]
Thank you for the quick response here, I really appreciate your time.

The main challenges are that it treats "options" as "arguments", so there are a few differences in behavior I've noticed so far.

One example is the short option grouping, like you've mentioned. 

Another is the fact that fish completion by default only shows options on completion if you've typed a hyphen already, while arguments are displayed immediately on `<tab>`, even if they begin with a hyphen. So there's a bit of visual noise there, and a bit of a departure in behavior from defining them manually.

Another is the fact that you can group a short and long flag together so they complete together, such as the `-a --all`, `-m --message`, and `-p --patch` flags below:

```
$ git commit -
-a  --all   (Automatically stage modified and deleted files)  --author                       (Override the commit author)  --help                             (Display the manual of a git command)
-m  --message  (Use the given message as the commit message)  --cleanup              (How to clean up the commit message)  --no-edit  (Use the selected commit message without launching an editor)
-p  --patch      (Use interactive patch selection interface)  --date                           (Override the author date)  --reset-author  (When amending, reset author of commit to the committer)
--amend           (Amend the log message of the last commit)  --fixup  (Fixup commit to be used with rebase --autosquash)  --squash             (Squash commit to be used with rebase --autosquash)
```

Support for dynamic options that have the same behavior and feature set as manually defined options is definitely desirable, although admittedly there are workarounds like the one you've described that get us pretty close if that ends up being the only path forward.

**Comment by faho** [comment]
This is a minority use case that I don't think we need to work on. Truly dynamic options are basically a novelty, I don't think I've ever seen them anywhere.

So I'm closing this.
