### ISSUE TITLE
`DOCUMENTATION_OPTIONS.LINK_SUFFIX` is `undefined`

### ISSUE THREAD

**Issue by cstyles** [fish-shell/fish-shell#7946]
I'm running fish version 3.2.2 on macOS, installed via Homebrew. Whenever I search for something using the local docs, the links for all of the search results are broken. Specifically, the extension for the links is `undefined` instead of `.html`:

<img width="553" alt="Screen Shot 2021-04-22 at 1 19 24 PM" src="https://user-images.githubusercontent.com/4869194/115780551-25276180-a36e-11eb-91a2-951646a0910d.png">

After a bit of debugging, I noticed that `DOCUMENTATION_OPTIONS.LINK_SUFFIX` is undefined which causes problems here:

https://github.com/fish-shell/fish-shell/blob/2095d744cf08bd2f7e4b08dbb0b902de05c1178a/doc_src/python_docs_theme/static/searchtools.js#L271

Here are the contents of `/usr/local/Cellar/fish/3.2.2/share/doc/fish/_static/documentation_options.js`:

```js
var DOCUMENTATION_OPTIONS = {
    URL_ROOT: document.getElementById("documentation_options").getAttribute('data-url_root'),
    VERSION: '3.2.2',
    LANGUAGE: 'None',
    COLLAPSE_INDEX: false,
    FILE_SUFFIX: '.html',
    HAS_SOURCE: false,
    SOURCELINK_SUFFIX: '.txt',
    NAVIGATION_WITH_KEYS: false,
};
```

For comparison, here are the contents of `/usr/share/doc/fish/_static/documentation_options.js` on my Arch Linux box:

```js
var DOCUMENTATION_OPTIONS = {
    URL_ROOT: document.getElementById("documentation_options").getAttribute('data-url_root'),
    VERSION: '3.2.1',
    LANGUAGE: 'None',
    COLLAPSE_INDEX: false,
    BUILDER: 'html',
    FILE_SUFFIX: '.html',
    LINK_SUFFIX: '.html',
    HAS_SOURCE: false,
    SOURCELINK_SUFFIX: '.txt',
    NAVIGATION_WITH_KEYS: false
};
```

**Comment by ridiculousfish** [comment]
Wow, thanks for debugging so deeply! I see this when fish is provided by homebrew (with or without `--build-from-source`), but not when built locally. Probably the Homebrew recipe needs to be updated, I can investigate more tomorrow.

**Comment by faho** [comment]
We could probably just hardcode the LINK_SUFFIX here, I don't see it being anything but ".html".

**Comment by faho** [comment]
```js
 linkUrl = item[0] + (DOCUMENTATION_OPTIONS.LINK_SUFFIX || ".html");
```

should work.

**Comment by zanchey** [comment]
This is a problem in the tarballs, rather than with Homebrew.

**Comment by zanchey** [comment]
It's probably because the build host has Sphinx 1.8.4 (jeepers) installed. Thanks Debian. I'll look at upgrading it.

**Comment by zanchey** [comment]
OK, I've updated the build host - I'll check the next generated tarball manually.

**Comment by faho** [comment]
Yeah the problem here is that "searchtools.js" is nabbed *from sphinx*, but a much newer version.

We do that so we can offer the special page for short search strings - offering "and", "end", "or" and such.

Apparently they aren't necessarily compatible across sphinx releases.

**Comment by zanchey** [comment]
A minimum version check in the CMake setup is probably warranted.

**Comment by zanchey** [comment]
This is working now.
