### ISSUE TITLE
when entering ~ and pressing enter it closes the terminal

### ISSUE THREAD

**Issue by badlirashid** [fish-shell/fish-shell#7947]
when entering ~ and pressing enter it closes the terminal. Using gnome terminal

fish --version fish, version 3.2.2-204-gfc0dd4984-dirty

echo $version 3.2.2-204-gfc0dd4984-dirty

uname -a Linux w 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 GNU/Linux

sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish

**Comment by ridiculousfish** [comment]
Thank you for filing. This sounds like fish is crashing, but I was not able to reproduce. What does `echo ~` show? What are the "dirty" changes? How did you install fish - did you build it yourself?

**Comment by badlirashid** [comment]
when doing an echo ~ with or without enter, the terminal crash. 
It also occurs when doing a ~ alone with or without pressing enter.

build fish with
cmake .. \
	-DCMAKE_C_FLAGS="-march=native -mtune=native -O2 -pipe" \
        -DCMAKE_CXX_FLAGS="-march=native -mtune=native -O2 -pipe" \
	-DCMAKE_BUILD_TYPE=Release \
	-DCMAKE_EXE_LINKER_FLAGS="-static"\
	-DCMAKE_INSTALL_PREFIX=/usr/local \
	-DBUILD_DOCS=True

**Comment by faho** [comment]
> -DCMAKE_EXE_LINKER_FLAGS="-static"

Static builds are very unlikely to work and we don't support them.

**Comment by faho** [comment]
Also wha about `echo $HOME`?

**Comment by faho** [comment]
Okay, I can reproduce fish crashing when statically linked, and all I can say is: Don't do that. It doesn't work, isn't expected to work and doesn't really do much of use - you don't get a single-file relocatable fish (that would require something like an appimage).

Let me see if we can get cmake to produce an error when you try.

**Comment by badlirashid** [comment]
I try without linking statically and it is working now. 

Now echo $HOME shows the /home/userhome, but i am using the new build instead of the old build.

build fish with the following configuration.
cmake ..
-DCMAKE_C_FLAGS="-march=native -mtune=native -O2 -pipe"
-DCMAKE_CXX_FLAGS="-march=native -mtune=native -O2 -pipe"
-DCMAKE_INSTALL_PREFIX=/usr/local
-DBUILD_DOCS=True

Regards,
badli

**Comment by zanchey** [comment]
I'd be curious to know where this is crashing, presumably in a call to `getpwent`?

**Comment by badlirashid** [comment]
> I'd be curious to know where this is crashing, presumably in a call to `getpwent`?

hi, sorry i dont know, the build type was a release.

**Comment by badlirashid** [comment]
@faho fyi, the cmake policy CMP0066 was change 

```
-  cmake_policy(SET CMP0066 OLD)
+  cmake_policy(SET CMP0066 NEW) 
```

**Comment by floam** [comment]
Yikes

**Comment by floam** [comment]
I assumed the problem was that we were doing something wrong with how we orchestrated the static linking of glibc, not that it is inherently a deadend for somehow… more modern versions. No, I'm not super excited about actually pulling off a Go.

**Comment by badlirashid** [comment]
Hi all,

Thanks for the insights and It is very helpful in regards to library that
is static and dynamically link.

I have not try flatpack yet to package it.
