### ISSUE TITLE
command not found for new functions

### ISSUE THREAD

**Issue by badlirashid** [fish-shell/fish-shell#7948]
Hi,

I have 2 new functions. it comes out 'command not found' on the command line.

function ....
        command cd ../../../
end

function ...
        command cd ../../
end
 

on fish_config web there was no code was shown but only the function name.

Web config started at file:///tmp/web_config9da_wsxm.html
Hit ENTER to stop.
$ set -L
$ functions
$ functions N_ | fish_indent --html
$ functions dotdotdot | fish_indent --html
$ functions dotdotdotdot | fish_indent --html

below is the details.

fish --version fish, version 3.2.2-204-gfc0dd4984-dirty

echo $version 3.2.2-204-gfc0dd4984-dirty

uname -a Linux w 5.8.0-50-generic #56~20.04.1-Ubuntu SMP Mon Apr 12 21:46:35 UTC 2021 x86_64 GNU/Linux

sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish

Regards,
Badli

**Comment by faho** [comment]
Well, where are these functions defined? What does `functions dotdotdot` say in a terminal?

Also is this with your statically linked fish? Can you try without that?

**Comment by badlirashid** [comment]
When i did the functions it shows the below in the terminal. Fish is not link statically now.
~> functions dotdotdot
~ [1]> functions dotdotdotdot 
~ [1]> 

function ...
	#
	# Go back 2 folders back 
	#
	command cd ../../
end

function ....
	#
	# Go back 3 folders back
	#
	command cd ../../../
end

**Comment by faho** [comment]
So is the function called "dotdotdot" or "..."?

**Comment by badlirashid** [comment]
the function is call ... the file is called dotdotdot.fish.

**Comment by faho** [comment]
Well, that won't work.

Fish finds function definitions by autoloading a file *named after the function*. So if it is told to use a function called "..." it tries to read a file called "....fish", and if it sees a file called "dotdotdot.fish" it expects a function called "dotdotdot".

One way around this for these specific functions is to define them eagerly in config.fish.

**Comment by badlirashid** [comment]
All right, i will try.

**Comment by faho** [comment]
Alright, question has been answered and there isn't really anything for us to do here. Closing!
