### ISSUE TITLE
git config + tab breaks fish autocomplete

### ISSUE THREAD

**Issue by alvinseville7cf** [fish-shell/fish-shell#7950]
# Environment
Fish version: 3.1.0
OS: Ubuntu 20.04.2 LTS (WSL)

# Description
`git config` + tab breaks fish autocomplete:
![image](https://user-images.githubusercontent.com/42812113/115865655-f697ac80-a47b-11eb-834a-c9a2db518239.png)

**Comment by faho** [comment]
This is an error in an old Debian package. Please upgrade to fish 3.2.2 via https://fishshell.com/

**Comment by faho** [comment]
Duplicate of #7176

**Comment by alvinseville7cf** [comment]
@faho, I've built fish from sources. Now fish --version shows `fish, version 3.2.2-204-gfc0dd4984`. But it still fails with this error.

**Comment by alvinseville7cf** [comment]
I have to note that I had to `sudo apt purge fish` to remove fish via apt to after building latest fish version from sources.
