### ISSUE TITLE
Prompt error when aliasing grep

### ISSUE THREAD

**Issue by thorstenkampe** [fish-shell/fish-shell#7953]
* version: 3.2.2
* OS: Cygwin (Linux not affected)
* no third-party customizations

Aliasing grep in `config.fish` via
```
function grep
    rg $argv
end
```
...results in an error on fish startup:
```
┌( thorsten@rednails) ( ~)
└( powershell)❯ fish
error: The following required arguments were not provided:
    <PATTERN>

USAGE:
[ripgrep usage help]

thorsten@rednails ~>
```
removing the grep alias, the prompt indicates a root user:
```
┌( thorsten@rednails) ( ~)
└( powershell)❯ fish
thorsten@rednails ~#
```

My best guess is that fish is trying to evaluate whether I'm superuser on Cygwin and uses the aliased grep (=ripgrep).

**Comment by faho** [comment]
Well, this is because your prompt is using `grep` in an incompatible way. Our prompts don't call grep, so this is your own doing, so you need to fix it.

Aliases are just functions, and if you give something the same name it should be compatible. In this case it's not, so I suggest renaming. Or... you know `rg` is already just two characters, so just use it.

**Comment by thorstenkampe** [comment]
@faho I understand. I there a way to trace which files fish is sourcing oder executing during startup?

**Comment by thorstenkampe** [comment]
I figured it out (via `fish -p`) 
```
373	393	--------> source /usr/share/fish/vendor_functions.d/iamroot.fish
20	20	---------> function iamroot --description "True if the user has admin privileges, else false"...
33890	142021	--------> id -G | grep -qE '\<(114|544)\>'
108131	108131	---------> rg $argv
```

I am closing the issue as the issue is Cywin maintainer specific

**Comment by faho** [comment]
Just to be clear: Naming a thing `grep` that isn't `grep` is a bad idea.
