### ISSUE TITLE
The fish_vi_key_bindings mode icon is not displaying correctly

### ISSUE THREAD

**Issue by pmdaly** [fish-shell/fish-shell#7954]
![Screen Shot 2021-04-25 at 1 02 52 PM](https://user-images.githubusercontent.com/8229664/116007846-8cd7e980-a5c6-11eb-9dfc-6fa7b8f7f0a6.png)
![Screen Shot 2021-04-25 at 1 03 18 PM](https://user-images.githubusercontent.com/8229664/116007855-9cefc900-a5c6-11eb-83f1-45f9119eca35.png)

The vi mode icon seems to be highlighted.  

A user in another thread seems to have the icon displayed correctly  https://github.com/fish-shell/fish-shell/issues/904#issuecomment-405648507

![Screen Shot 2021-04-25 at 1 13 17 PM](https://user-images.githubusercontent.com/8229664/116008174-0b815680-a5c8-11eb-8558-4b09c97cabe3.png)

I'm using iTerm2 3.4.5.  Settings include
- gruvbox-material color preset
- use built-in powerline glyphs selected
- font is hack nerd font mono regular

fish version: 3.2.2
uname -a: Darwin mbp.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
term: xterm-256color

**Comment by faho** [comment]
What does `type fish_mode_prompt` say? What about `fish_mode_prompt | string escape`?

**Comment by pmdaly** [comment]
![Screen Shot 2021-04-25 at 1 18 04 PM](https://user-images.githubusercontent.com/8229664/116008295-ac701180-a5c8-11eb-8338-11fcd5b23e7d.png)

**Comment by faho** [comment]
Just to be clear: The version with the red/green background *is the default one*. If you want anything else, you need to edit the `fish_mode_prompt` function. The user in that thread has apparently done just that.

Note that the next version will use a foreground color instead of a background - see #7880.

**Comment by pmdaly** [comment]
oh ok, is there a simple way to modify just the behavior of the vi mode icon instead of changing the full prompt? I could add the change directly to fish but would that effect anything when I update at some point?

**Comment by faho** [comment]
In short:

```fish
> functions --erase fish_mode_prompt
> functions --copy fish_default_mode_prompt fish_mode_prompt
> funced fish_mode_prompt
# opens your $EDITOR, adjust how you want it - e.g. remove the "--background" from the set_color calls
> funcsave fish_mode_prompt # once you're happy to make the changes permanent
```
