### ISSUE TITLE
⌘F issues in Big Sur's Terminal

### ISSUE THREAD

**Issue by rolandleth** [fish-shell/fish-shell#7956]
Hello!

Whenever I use the ⌘F command in Terminal I get this error when the search bar appears and once more when it closes. Not even sure if it's fish related, but bash and zsh don't behave like this.

```
warning: An error occurred while redirecting file '/dev/null'
open: Interrupted system call
```

- fish 3.2.2
- Big Sur 11.2.3
- Terminal, xterm-256color
- tried without third-parth customization, same behavior
- also tried removing all my functions, everything in `config.fish` and in `fish_variables`, same behavior
- bash and zsh don't have this issue, neither did fish until very recently (I suspect before latest version)
- no idea how to reproduce; the issue occurs any time ⌘F is used, at any path, no matter the history. The video shows the most basic case: open the terminal, press ⌘F

Any ideas where this might come from?

https://user-images.githubusercontent.com/1858700/116073282-dbee4f00-a698-11eb-9511-d3087005e2d0.mov

**Comment by zanchey** [comment]
I wonder if fish is getting a signal or something similar here. Can you confirm that it definitely still appears with an entirely new environment (`exec env -i HOME=(mktemp -d) TERM=$TERM fish` should do the trick)?

**Comment by rolandleth** [comment]
The command is crashing the Terminal window/tab I run it in 😄

**Comment by faho** [comment]
@rolandleth Can you run `fish_key_reader` and then press the key combo?

This seems like the terminal both uses the keys for itself *and* sends them on, which is pretty broken to begin with. Otherwise I'm not sure why fish would be doing anything, and especially anything to /dev/null.

Compare also #7506 - it seems macOS is pretty happy to interrupt system calls (I've *never* seen that error on linux).

**Comment by rolandleth** [comment]
Hmm, nothing is being passed, buuuut the issue is also gone. I did update to macOS 11.3 (probably what fixed it?) and I probably did a `brew upgrade` (shouldn't have impacted, as no new fish version was installed).

I'll keep you posted if it starts popping up again, thanks for the help so far 👍🏻

**Comment by zanchey** [comment]
Feel free to reopen the issue if it returns!
