### ISSUE TITLE
gdbserver gets stuck if external commands are executed in config.fish

### ISSUE THREAD

**Issue by s417-lama** [fish-shell/fish-shell#7957]
`gdbserver` command gets stuck when (1) fish is the default shell and (2) external commands are executed in `config.fish`.

## Condition 1: fish is the default shell

If bash, for example, is the default shell, no problem happened.

If `gdbserver` runs with `bash` as the default shell, it starts to listen on the specified port:
```
⟩ SHELL=/bin/bash gdbserver :10000 ./a.out
Process ./a.out created; pid = 2877
Listening on port 10000
```

If `gdbserver` runs with `fish` as the default shell, it gets stuck without printing anything:
```
⟩ SHELL=/usr/bin/fish gdbserver :10000 ./a.out
```

Seems like `gdbserver` internally launches a shell to execute some commands.
If the shell internally launched is `fish`, it somehow gets stuck.

## Condition 2: external commands are executed in `config.fish`

After that, I tried to run `sh -c 'env HOME=$(mktemp -d) fish'` but the bug was **not** reproduced.

I figured out that the bug was reproduced with the following minimum `config.fish`:
```
set hoge (hostname)
```

With this single line of configuration, `gdbserver` gets stuck.
From my observation, executing external commands in `config.fish` causes this problem.

I thought `gdbserver` might be the cause of this bug, but considering that it does not happen with `bash`, I decided to report this bug to this `fish` repository.

## Environment

```
⟩ fish --version
fish, version 3.2.2

⟩ uname -a
Linux shiina-XPS-15-9570 5.4.0-72-generic #80~18.04.1-Ubuntu SMP Mon Apr 12 23:26:25 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

⟩ echo $TERM
screen-256color

⟩ gdbserver --version
GNU gdbserver (Ubuntu 8.2-0ubuntu1~18.04) 8.2
Copyright (C) 2018 Free Software Foundation, Inc.
gdbserver is free software, covered by the GNU General Public License.
This gdbserver was configured as "x86_64-linux-gnu"
```

**Comment by faho** [comment]
Lovely. The last thing gdbserver does, according to strace, is `rt_sigsuspend([IO], 8`.

It has started a fish process, and that fish has started the external command - in your case that's `hostname`, I tried with `command echo` and it reproduces as well.

The external command, importantly, is already a zombie, only fish doesn't appear to be able to reap it. I would love to trace the fish as well, but... well, gdbserver is already tracing it.

It appears that's interfering with fish's operation.

----

(personally I strongly recommend for gdb to not use $SHELL here - it's not guaranteed to work anything like it expects. I have a suspicion that's fighting against windmills tho)

**Comment by ridiculousfish** [comment]
gdbserver uses ptrace, which causes signals to be reported to gdbserver before fish. gdbserver then does not properly enqueue SIGCHLD so fish waits forever.

This looks like a [known gdb bug](https://sourceware.org/bugzilla/show_bug.cgi?id=26116). I will try to add the results of my investigation there.

Let's close as a dup of the gdb bug, fish can't work unless it gets its signals properly.

**Comment by mqudsi** [comment]
Adding known workarounds to this locked issue for anyone stumbling across this via Google:

* Override `$SHELL` for `gdbserver`: `env SHELL=/usr/bin/bash gdbserver ...`
* Use `gdbserver`'s with the `--no-startup-with-shell` option.
