### ISSUE TITLE
Termux: read hangs at startup file config.fish

### ISSUE THREAD

**Issue by msn-05** [fish-shell/fish-shell#7964]
Fish version 3.2.1
I'm running fish from Termux in Android.
I'm trying to make a simple password script to call at startup.
Fish startup file is in /data/data/com.termux/files/usr/etc/fish/config.fish
I made this simple script named login to ask for password.
![Screenshot_20210429-132855_Termux](https://user-images.githubusercontent.com/68454203/116516081-f3bf1080-a8ee-11eb-9616-da1bfbfdb63b.jpg)
I added the path to this script in config.fish
![Screenshot_20210429-133135_Termux](https://user-images.githubusercontent.com/68454203/116516274-3da7f680-a8ef-11eb-802e-ce07dd5153ef.jpg)
But at startup there's no output or anything at first. If i press enter or write something then it displays the prompt "Password:" from login.
![Screenshot_20210429-133304_Termux](https://user-images.githubusercontent.com/68454203/116516468-75af3980-a8ef-11eb-8ec8-a332b2e97710.jpg)
After pressing enter 👇
![Screenshot_20210429-133310_Termux](https://user-images.githubusercontent.com/68454203/116516616-9ecfca00-a8ef-11eb-970d-5d1a2779578e.jpg)
So why do I have to press enter everytime? Is this a bug?
How to fix it.

**Comment by faho** [comment]
This works for me on linux, I'd ask the termux people for help as I have absolutely no idea what's happening here and no idea how to debug it. Maybe their greeting stuff is getting in the way.

(also this is a super cheesy thing to do and basically not anything I would recommend - your "login" here has already happened, and securing just termux is an exercise in futility)

**Comment by msn-05** [comment]
i know it's not actually "securing" termux. It's just a simple test. The greeting text was in /usr/etc/motd
i cleared it a long time ago. It's not the issue. It's not just in bash,fish. I tested it in python too. Taking input in config.fish is showing this weird type of error.

**Comment by JoaoCostaIFG** [comment]
I believe I have a problem that's related to yours.

When I execute the command `bash -c 'read abc'` in fish, I get the expected result: it waits for my input and finishes after I press enter. The problem appears when I run that command from a keybind, e.g.: `bind \ca -M insert "bash -c 'read abc'"`. With this keybind, when I press Ctrl+a (in insert mode), the prompt hangs until I press Ctrl+c. I don't think that's the intended behaviour.

I'm running fish version 3.2.2 on Linux (5.12.2-zen2-1-zen kernel) and was able to reproduce this on the st terminal (version 0.8.4) and on the XTerm terminal (version 367-1).

**Comment by faho** [comment]
@JoaoCostaIFG This isn't related, at all. Your issue is that the bash is started in a different process group because it was started as part of a keybinding, which means it can't read from the terminal, That's correct, as doing otherwise would mean any key binding could potentially steal key presses from fish. So the answer is to not do that.

**Comment by faho** [comment]
Okay, I'm gonna be honest: This needs someone more familiar with termux to look into it. I have no idea what the issue would be, and it's likely to be an issue there.
