### ISSUE TITLE
`openssl` completions don't work with LibreSSL

### ISSUE THREAD

**Issue by kidonng** [fish-shell/fish-shell#7966]
`fish --version`: 3.2.2

Neither `openssl list` nor `openssl help` used in [`openssl` completion](https://github.com/fish-shell/fish-shell/blob/daa3ae4be1ac6317861bdfab6e1beff80f26201d/share/completions/openssl.fish) exist in the latest stable LibreSSL (3.2.5). Perhaps a version check is needed:

```
$ openssl version
LibreSSL 3.2.5
```

Workaround:

``` fish
if string match -q "LibreSSL*" (openssl version)
    # any invalid command works, just using help for consistency
    complete -c openssl -n __fish_use_subcommand -x -a "(openssl help 2>&1 | tail -n +2 | string match -rv '^[A-Z]|^\$' | string split -n ' ')"
else
    source $__fish_data_dir/completions/openssl.fish
end
```

**Comment by ridiculousfish** [comment]
Turns out there was already some logic for this case, it was just busted. Fixed, thanks for filling.
