### ISSUE TITLE
Feature Request: CSI modifier support

### ISSUE THREAD

**Issue by lanza** [fish-shell/fish-shell#7975]
Many programs recently have added support for Paul Evan's ["fixterms" proposal](http://www.leonerd.org.uk/hacks/fixterms/). 

* [iTerm2](https://iterm2.com/documentation-csiu.html)
* [tmux](https://github.com/tmux/tmux/blob/master/CHANGES)
* neovim has it trivially due to using `libtermkey` which supports it out the box.
* xterm
* pangoterm

and various others. This allows you to define mappings for otherwise unmappable key combos such as ctrl-2, ctrl-., etc. 

Fish supporting this would be very useful.

**Comment by ridiculousfish** [comment]
Happily this seems to work already - if I enable CSI u mode in iTerm2 I can bind it with help from fish_key_reader. Here testing with control-period:

```
> fish_key_reader
Press a key:
              hex:   1B  char: \c[  (or \e)
(  0.061 ms)  hex:   5B  char: [
(  0.023 ms)  hex:   34  char: 4
(  0.025 ms)  hex:   36  char: 6
(  0.032 ms)  hex:   3B  char: ;
(  0.038 ms)  hex:   35  char: 5
(  0.041 ms)  hex:   75  char: u
bind \e\[46\;5u 'do something'
> bind \e\[46\;5u 'echo yay'
> yay
yay
yay
```

Is there something that you would like to see fish do beyond that? Maybe improve the `bind` syntax?

**Comment by lanza** [comment]
Wow! Thanks for pointing that out. I'd say that this should be in the docs/source code/etc to help people find it. I grepped over the codebase and docs and found nothing mentioning CSIu, CSI modifiers, fixterm, or any of the other vague descriptions of the protocol, so I just assumed that this sort of binding wasn't possible.

**Comment by ridiculousfish** [comment]
Yeah I agree, we should add it! Also I think there is an opportunity here for a clearer syntax: the advantage of CSIu is you can specify keys unambiguously, it would be awesome to be able to write `bind -u ctrl-. yank` or something. This can track that.

**Comment by faho** [comment]
>it would be awesome to be able to write bind -u ctrl-. yank or something. This can track that.

Nah, that's already #3018
