### ISSUE TITLE
underline of fish_color_valid_path expand to the end of terminal when adjust terminal size

### ISSUE THREAD

**Issue by efikarl** [fish-shell/fish-shell#7986]
WSL2 + Windows Terminal + fish, version 3.2.2
![fishbug](https://user-images.githubusercontent.com/13889433/117683564-c6277080-b1e6-11eb-8757-b6167460c8ec.png)

**Comment by faho** [comment]
The only thing you can do here is to try

```fish
set -g fish_handle_reflow 0
```

which *might* fix things if the windows terminal now handles reflow. If not this is an unfixable race condition.

**Comment by efikarl** [comment]
I tried your command, and still has this issue.

**Comment by faho** [comment]
In that case it appears to be a bug in Windows Terminal.
