### ISSUE TITLE
$fish_pager_color_selected_* variables aren’t marked as universal variables by default.

### ISSUE THREAD

**Issue by schuelermine** [fish-shell/fish-shell#7988]
```
$ fish --version
fish, version 3.2.0
$ uname -a
Linux buggeryyacht-pop 5.11.0-7614-generic #15~1618626693~20.10~ecb25cd-Ubuntu SMP Thu Apr 22 16:00:45 UTC  x86_64 x86_64 x86_64 GNU/Linux
$ echo $TERM
xterm-256color
```

The variables `fish_pager_color_selected_prefix`, `fish_pager_color_selected_completion`, `fish_pager_color_selected_description` aren’t universal variables by default. I’m not sure about `fish_pager_color_selected_background`, I may have inadvertently changed it.

**Comment by faho** [comment]
The reason they aren't universal is that they aren't set at all in some colorschemes, including the default.

So there is no scope because the variable doesn't *exist*.

**Comment by schuelermine** [comment]
ok
