### ISSUE TITLE
Make wildcard errors more informative

### ISSUE THREAD

**Issue by dag** [fish-shell/fish-shell#799]
Considering #796 and #683 and anecdotal evidence that this trips people up, perhaps it would be wise to add a note to the error on failed wildcard expansion that suggests escaping or quoting.

Something like:

```
> echo *.xml
fish: No matches for wildcard '*.xml'. If you want to use wildcard characters literally in an argument you need to escape the special characters or quote the argument, for example “\*.xml” or “'*.xml'”. For more information, see the help section on parameter expansion by typing  “help expand”.
echo *.xml
     ^
```

**Comment by ashwin** [comment]
:+1:

**Comment by ridiculousfish** [comment]
Users don't read  the "wall of text" error message. Can we make this short and sweet? Use the errors in #1288 as a model.

**Comment by Undeterminant** [comment]
How about:

```fish: No matches for wildcard '*.xml'. Did you mean '\*.xml'?```

**Comment by chrisdembia** [comment]
What about

`fish can't match '*.xml' ...`

?

**Comment by faho** [comment]
"No match found for '*.xml'. To pass it to the command, use '\*.xml.'"

**Comment by chrisdembia** [comment]
+1 for @faho's. As for my earlier comment, I think all fish errors are prepended with `fish:`, so nevermind.

**Comment by krader1961** [comment]
Closing since current fish code behaves as requested:

```
$ echo *.xml
No matches for wildcard '*.xml'.  (Tip: empty matches are allowed in 'set', 'count', 'for'.)
fish: echo *.xml
           ^
```
