### ISSUE TITLE
Introduction page section ordering seems suboptimal

### ISSUE THREAD

**Issue by ripytide** [fish-shell/fish-shell#7990]
I was reading through the intro and I found it a bit strange that you are introduced to **Index range expansions** before you are introduced to **Lists**. This is because you sort of need to know lists and list indexing before you can learn index ranges imo.

At first I thought this was an easy fix, one could just put the **Lists** section somewhere before the **Index range expansion** section, however, then I saw that the **Syntax overview** portion of the introduction page is organized into **Parameter expansion** and **Shell variables**.

Which leads me into my question/issue: should the **Parameter expansion** section (which contains things such as **Variable expansion**, **Index range expansion** and **Brace expansion**) come after the **Shell variables** section (which contains the **Lists** and **Shell variables** sections) and is it easier to learn that way round or not?

I am also unfamiliar with the (markdown?) format of the introduction page source code, hence this is an issue not a PR, sorry.

**Comment by faho** [comment]
>I am also unfamiliar with the (markdown?) format of the introduction page source code, hence this is an issue not a PR, sorry.

It's reStructuredText, formatted by sphinx. See https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html.

>should the Parameter expansion section (which contains things such as Variable expansion, Index range expansion and Brace expansion) come after the Shell variables section

The idea here is that you'd learn how to *use* variables (like $HOME and $PATH) before you'd learn how to *set* them (with, well, `set`). I think that's the right order, but we might want to add more links or even just a basic "use `set` to set variables" to the former section.

Clumping all variable-related things together is also possible, but it detracts from the other expansions - expansion is the most basic element of this flavor of shellscripting, and explaining that is important.

**Comment by ripytide** [comment]
> The idea here is that you'd learn how to use variables (like $HOME and $PATH) before you'd learn how to set them (with, well, set).

Learning things that way round may be great for lots of people, but what about for a beginner? They may just end up getting confused by the features they haven't yet learnt before they can appreciate their uses.

> Clumping all variable-related things together is also possible,

I thought they were already clumped together into the **Shell variables** section?

> but it detracts from the other expansions - expansion is the most basic element of this flavor of shellscripting, and explaining that is important.

I agree expansion is very important, but why would learning about variables first detract from other expansions?

**Comment by ripytide** [comment]
> The other way around means explaining the intricacies of variables before you actually know what they're used for

I agree, leaving intricacies such as variable scoping to afterwards is a likely a good idea.

Perhaps moving the really nice (imo) basic sections on just variables and lists to above the expansion section.

It would cut down on a some of the "read here if you don't understand" links when explaining expansions that include variables. This would make the reading of the introduction more linear, which I can only imagine being easier.
It would also introduce you to lists and list indexing before list index ranges which makes sense.

**Comment by faho** [comment]
Alright, I've added a short bit on `set` and another link to the variables section proper. I don't think switching or unifying the sections really helps - sometimes you just gotta use something before you explain it in detail.

So I'm closing this. Any other suggestions are welcome, of course.
