### ISSUE TITLE
Universal scope variable stuck with GNOME wayland session

### ISSUE THREAD

**Issue by yookoala** [fish-shell/fish-shell#7995]
Change to universal scope variable are not effective until you logout your GNOME session. This is a bit counter intuitive and annoying. Would it be possible if universal scope variable change takes effect immediately to all subsequently created shell session (even if previously started shell sessions are not closed)?

## Details

If I'm not mistaken, fish shell's universal scope variable changes do not affect previously started shell session. Also, later started fish shell session only follow the universal first shell session. So for a universal scoped variable change to work, you need to:

1. Set the variable in a shell: `set --universal -x FOOBAR=new`
2. Then make sure all shell session (except the one that you set the variable) are closed.
3. Start your new shell session.

However, GNOME (and potentially other DE) are not designed with this in mind. In a nut shell, most GNOME environment nowadays starts with gdm. It would gradually call gdm-session-worker, gdm-wayland-session, then gnome-session itself. This is an ordinary process tree:

```
root        1897       1  0 May04 ?       00:00:00 /usr/sbin/gdm
root        2483    1897  0 May04 ?       00:00:00  \_ gdm-session-worker [pam/gdm-password]
user       2523    2483  0 May04 tty2    00:00:00      \_ /usr/libexec/gdm-wayland-session /usr/bin/gnome-session
user       2532    2523  0 May04 tty2    00:00:00          \_ -/usr/bin/fish -c /usr/bin/gnome-session -l 
user       2798    2532  0 May04 tty2    00:00:00              \_ /usr/libexec/gnome-session-binary
```

As you can see, in the process 2532 here, the gnome-session is started with my default shell (`/usr/bin/fish`). Until I'm logged off or reboot, this shell session stays there forever.

So effectively, if I previous setup a universal scope variable (say `FOOBAR=old`) and I started a GNOME session, I'm stuck with that version of variable for the duration of my current session. All newly created shell session would see `FOOBAR=old` even after I run `set --universal -x FOOBAR=new` (until I logout and login GNOME).

## Environment
```text
$ fish --version
fish, version 3.2.1
$ echo $version
3.2.1
$ cat /etc/fedora-release
Fedora release 34 (Thirty Four)
$ gnome-shell --version
GNOME Shell 40.0
```

**Comment by faho** [comment]
https://fishshell.com/docs/current/faq.html#why-doesn-t-set-ux-exported-universal-variables-seem-to-work.

The upper fish has a universal version, and it does update it. But 1. the gnome-session-binary already received its copy on start, 2. all other fishes inherit a copy from that, and inherited variables are global, which is a smaller (and stronger) scope than univeral.

**Comment by yookoala** [comment]
So you meant the terminal emulator receives a copy of the universal scope variable as global scope. That's why the terminal emulator's global variable overrides the one in the universal scope variables, correct?

**Comment by faho** [comment]
Yes.

**Comment by yookoala** [comment]
@faho: In that case, universal scope variable can never be changed on-the-fly (without a logout) in DE, correct?

**Comment by faho** [comment]
Yes.

**Comment by yookoala** [comment]
@faho: This is totally counter intuitive. Why is this not considered a usability issue?

I'm not familiar with the GNOME tool chain. But if there's a way to configure how `gnome-session` should be started from shell, we can potentially start `gnome-session` with fish in a mode that doesn't load universal variables, right? Let's say if fish has a flag `--no-universal` that do not load universal variables, GNOME can safely load gnome-session like this:

```
-/usr/bin/fish -c --no-universal /usr/bin/gnome-session -l
```

then universal variables will not be affecting the global scope of terminal emulators within the session.

**Comment by faho** [comment]
Gnome shell starts

```
$SHELL -c /usr/bin/gnome-session -l
```

it has no special knowledge of fish, at all, so there can't be a special argument it passes to fish. If we had our way, they wouldn't use fish here *at all*, instead picking /bin/sh or whatever. The reason for that is that distros insist on putting configuration into /etc/profile.

But there really is no good way around this. It's all totally logical behaviors just interacting in a weird way. We recommend against exported universal variables for this reason, and we're working on replacing universal variables with something more targeted (#7379).

**Comment by yookoala** [comment]
Thanks for explaining. I changed my local script to use plain text file to store "universal" variable instead. Hope the #7379 is resolved soon. It would be painful for someone who heavily use universal variables, but it is for the better in long run.
