### ISSUE TITLE
Fish doesn't run at startup although it was set as default.

### ISSUE THREAD

**Issue by B4mbus** [fish-shell/fish-shell#8000]
Hello. A friend of mine has an issue with fish. 
 - The fish was installed with apt package manager, right after we checked if it runs - it does. 
 - We did `chsh -s /usr/bin/fish` (*the path is right*), and `sudo chsh -s /usr/bin/fish`. 
 - We checked `/etc/passwd` and for both profiles (root and his user) the shell is set to `/usr/bin/fish`.
 - `/etc/shells` contains `/usr/bin/fish`.

And althought everything appears to be set correctly the fish doesn't run at terminal start. The terminal itself is default ubuntu's terminal. 

**fish --version:** `fish, version 3.1.0`
**echo $version:** `3.1.0`
**uname- a:** `Linux Jan-IdeaPad-L340 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
**echo $TERM:** `xterm-256color`
sh -c 'env HOME=$(mktemp -d) fish'` did not affect the issue

**Comment by faho** [comment]
Have you rebooted?

Did you set the shell explicitly in the terminal configuration? If that's set to start e.g. bash, then it'll start that, the `chsh` stuff affects "the system's" view of the default shell but the terminal is of course free to start whatever.

**Comment by B4mbus** [comment]
> Have you rebooted?
> 
> Did you set the shell explicitly in the terminal configuration? If that's set to start e.g. bash, then it'll start that, the `chsh` stuff affects "the system's" view of the default shell but the terminal is of course free to start whatever.

Wow. I can't believe it was that simple. Rebooting helped. Thanks a lot.
