### ISSUE TITLE
Change private mode detection suggestion

### ISSUE THREAD

**Issue by kidonng** [fish-shell/fish-shell#8001]
Fish version 3.2.2

Quoting [the docs](https://github.com/fish-shell/fish-shell/blob/master/doc_src/interactive.rst#private-mode):

> If $fish_private_mode is **set to a non-empty value**, commands will not be written to the history file on disk.

I wonder if it will be better to suggest using `if test -n "$fish_provate_mode" ... ` instead of `if set -q fish_private_mode ...` to be more compliant to the spec.

**Comment by ridiculousfish** [comment]
Fixed as suggested. Thanks!
