### ISSUE TITLE
Line hopping at the new terminal 

### ISSUE THREAD

**Issue by syntezoid** [fish-shell/fish-shell#8005]
fish --version 3.2.2 (I don' use any plugins or modifications)
  System -- Arch Linux with Sway (wayland)
  Terminal -- alacritty, kitty, foot, qterminal

Hi I have problem with fish 3.2.x versions. If I open new terminal next to something running, the line where you entered the first command is shifted down one row. If you open a lot of them next to each other, then everything remains shattered when closing. 
I thought maybe I had something wrong with the terminal or fish configuration, but I did a test on the virtual machine and it was the same. Reverting package to fish 3.1.x removes this problem. I tried alacritty, kitty, foot and qterminal.

https://user-images.githubusercontent.com/44477799/118376356-d3b66f00-b5c7-11eb-886f-a31bd301d05b.mp4

**Comment by faho** [comment]
What seems to be happening here is one of two things:

- Either fish and your terminal disagree on the width of some character, most likely in your prompt - try replacing your prompt with something simpler
- Or your terminal is being resized while fish is just starting - #7893

But without further reduction on your end it's impossible to say.

**Comment by syntezoid** [comment]
Line `set -g fish_handle_reflow 1` didn't change anything, but my prompt is propably a problem. I use starship, I will ping them with this. thanks!

https://user-images.githubusercontent.com/44477799/118394324-45cc9980-b644-11eb-8510-8b65f551ac6f.mp4
