### ISSUE TITLE
Is there a way to only complete directories?

### ISSUE THREAD

**Issue by kidonng** [fish-shell/fish-shell#8007]
fish version 3.2.2

I'm trying to create a function utilizing [zoxide](https://github.com/ajeetdsouza/zoxide):

```fish
function z
	if test -z "$argv" || test "$argv" = - || test -d "$argv"
		cd $argv
	else
		set dir (zoxide query --exclude $PWD -- $argv) && cd $dir
	end
end
```

I want to make the function's completion only shows directories, just like `cd`, but couldn't find a way to do so. Using `function --wraps cd` doesn't work either.

Is this mechanism hard-coded for `cd`? Can we add options in `complete` to only show directories/files?

**Comment by zanchey** [comment]
Try `complete --command z --arguments '(__fish_complete_directories)'` (it is not documented and not guaranteed to be stable, but it's not something we're likely to take out any time soon).

**Comment by kidonng** [comment]
Wow, totally missed that. Thanks for the pointer! Will use it for the time being.
