### ISSUE TITLE
on-variable functions executed when variable value didn't change

### ISSUE THREAD

**Issue by giorgiga** [fish-shell/fish-shell#8010]
Functions created with `--on-variable` appear to be executed whenever the variable is assigned, regardless of whether its value is actually changed.

For example, look at:

    ~ ❱❱❱ function x --on-variable X; echo X; end;  set X x; set X x;  functions -e x
    X
    X

or

    ~ ❱❱❱ function x --on-variable PWD; echo PWD; end;  cd; cd;  functions -e x
    PWD
    PWD

Of course, for all i know, this is probably working as designed... I'm reporting this because the doc seems to imply otherwise (see below) and I cannot think of a use case where it may be desirable to execute such functions when the variable value hasn't actually changed.

     ~ ❱❱❱ function -h
    [snip]
    • -v or --on-variable VARIABLE_NAME tells fish to run  this  function  when  the  variable  VARIABLE_NAME
      changes  value.  Note that the function will not necessarily be run for each change; rather, it will be
      run when the variable has changed at least once.
    [snip]

(fish version 3.2.1 on fedora f34)

**Comment by faho** [comment]
Yes, this is to be expected. The help message should be read as "when the variable has been *set* at least once". Lemme try to clarify the wording.
