### ISSUE TITLE
functions man page seems to contradict itself

### ISSUE THREAD

**Issue by PatrickF1** [fish-shell/fish-shell#8014]
First, it says
> -e or --erase causes the specified functions to be erased. This also means that it is prevented from autoloading.

but then it says
> Automatically  loaded functions cannot be removed using functions -e. Either remove the definition file or change the $fish_function_path variable to remove autoloaded functions.

I think even if it's not directly contradictory, it might be worth clarifying.

**Comment by faho** [comment]
Yeah, this was overlooked with #5951

**Comment by PatrickF1** [comment]
Nice, thanks for the fix!
