### ISSUE TITLE
Autocomplete tag names after `vim -t`

### ISSUE THREAD

**Issue by cassepipe** [fish-shell/fish-shell#8015]
(fish version 3.1.0 on latest Linux Mint)

Would it be possible to have fish look for matching tags in the tags file after entering `vim -t` ?

Thanks for all the great work you have been doing so far.

**Comment by faho** [comment]
Works for me - both complete files.

Please upgrade to fish 3.2.2, you are missing 2357 commits - 17% of all commits ever made to fish. Then try again. Use [our PPA](https://launchpad.net/~fish-shell/+archive/ubuntu/release-3).

**Comment by faho** [comment]
Alright, after checking the zsh completion I can't see any special case of finding a "tags file" (as much as I can read zsh-script), it also doesn't seem like vim requires a special name or path or anything, so completing just them isn't tenable.

We already complete files in this case so there seems to be nothing to do.

**Comment by cassepipe** [comment]
Thanks for your answer.

I upgraded thanks to the ppa (thank you) and I get the same behavior,

Not sure I understand the secondesentence of your last post. 
I guess the solution would be to look up for tag names in the `tags` or `.tags` files whenever `vi -t` or `vim -t` is entered. I don't see what is untenable about it.

**Comment by zanchey** [comment]
zsh can complete tags, by walking up the tree until it finds a tags file then running it through some [fairly terrifying regular expressions](https://sourceforge.net/p/zsh/code/ci/master/tree/Completion/Base/Widget/_complete_tag).

A better approach might be to ask vim to spit out a tags list for the file in question, but I can't manage that with ten minutes of thrashing around.

**Comment by cassepipe** [comment]
@zanchey When you type `vim -t`, vim uses a `tags` or `TAGS` file. In it are the tags generated for all the files of a project (minus what's been excluded by ctags configuration). 
You can't specify a file and then a tag, so there is no "file in quesiton alas.

The idea is not to jump to a specific place in a file but to a specific function you are not really sure where it is (in a big project). 
But one tends to make typos or not remember exactly what was the function name, that's where autocompletion from a tagfile comes in really handy.

Don't you think that feature request deserves being re-opened ?

**Comment by zanchey** [comment]
Yeah, I think it's worth looking into.

**Comment by zanchey** [comment]
I was initially dubious about the 'look for the `tags` file' approach because there was a workflow from vim-fugitive which used `.git/tags` instead, but it turns out that stopped being recommended some years ago so I think the zsh approach is fine.

**Comment by cassepipe** [comment]
It seems like `zsh` is looking in all the sub-directories for the `tags` file (with a max depth of 10). I would think of the same approach (with maybe a smaller depth ?) unless there is something to recommend against it.

**Comment by cassepipe** [comment]
`zsh` does not do it for `vi -t` but heck it could be great to get the same behaviour than with `vim -t`

**Comment by cassepipe** [comment]
I have since been learning C++ and I was wondering if someone familiar with the codebase could point me to where tag completion from a `tags` file would have to be implemented ? Also is there a tour/documentation of the the code's general structure ?
(Yes I have read the Developper Guide)

**Comment by krobelus** [comment]
Completions for `vim` are implemented in `share/completions/vim.fish`. You can use any language (shouldn't need C++), fish script is the most obvious one.

**Comment by cassepipe** [comment]
Thank you. It seems rather straightforward although quite bare. My aim is to parse a tag file after hitting tab when `vim -t` has been inserted. Not sure how I would go about it as I am not proficient in fish yet. Seems like i would need to write a small program to parse the tag file into an array of strings and pass it to fish...

**Comment by krobelus** [comment]
According to the [ctags docs](https://docs.ctags.io/en/latest/man/tags.5.html) the tags file format is

    tag-name<tab>tag-metadata

the completion format that fish expects is

    completion<tab>description

So you can literally start with

    complete vim -s t -xa '(cat TAGS 2>/dev/null)'

The hard part is where to find the tags file, there's some discussion above.
