### ISSUE TITLE
Unable to re-evaluate completions after cancellation

### ISSUE THREAD

**Issue by ian-h-chamberlain** [fish-shell/fish-shell#8024]
> Some completions actually are cancellable for me, with ctrl-c.
> 
> I would imagine that's a side-effect of #3922, which would mean that ctrl-c is sent to whatever command the completion is running, so it would have to quit. That's not completely ideal but should work in the vast majority of cases.

I know this is an old issue, but I'm wondering if there's any way to re-run the completions after cancellation? I've noticed when I cancel a completion with `ctrl+c` and press tab again, it seems to continue using the "cached" completion (aka, nothing) and I can't get any completions for that command without restarting the shell (other completions continue to work as expected).

Example: I `ctrl-c` while the completion script for `bazel test //` is running, and it falls back to file completion. Further completions for `git` and other `bazel` subcommands continue to work, but I can no longer complete `bazel test`.

https://user-images.githubusercontent.com/11131775/118993800-d14f6e80-b953-11eb-8a72-ad55e3c24c0c.mov

_Originally posted by @ian-h-chamberlain in https://github.com/fish-shell/fish-shell/issues/23#issuecomment-845161377_

**Comment by zanchey** [comment]
Can you confirm which version you are running, on which operating systems?

**Comment by zanchey** [comment]
There were improvements to this in #6937 but that was for autosuggestions.

**Comment by ian-h-chamberlain** [comment]
Sorry for the delay, I was going to post but realized I originally reproduced on a different computer, here is my system info:

```shell
$ fish --version
fish, version 3.2.1

$ echo $version
3.2.1

$ uname -a
Darwin ichamberlain-mbp 19.6.0 Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64 x86_64

$ echo $TERM
xterm-256color-italic
```

Unfortunately I am having trouble coming up with a minimal reproduction, as the completion script being invoked when I encounter this issue is rather large and complex, and a simpler example seems to work as I would expect... 

Actually, now even the original reproducing example seems to work as expected, but as far as I know I have not updated `fish` since creating it. I will continue to investigate and see if I can come up with a reproduction or figure out what changed in my environment.

**Comment by zanchey** [comment]
If it does, feel free to reopen!
