### ISSUE TITLE
fish acts super sluggish under cygwin (windows domain login)

### ISSUE THREAD

**Issue by bochen2014** [fish-shell/fish-shell#8025]
## fish version 

  fish --version  : 3.1.2
  echo $version : 3.1.2

## fish standalone without plugins
i've tried
 sh -c 'env HOME=$(mktemp -d) fish' 
and it's the same slowness;

## reproduce
 
i've tried to debug the issue myself by following [this](https://github.com/fish-shell/fish-shell/issues/3479), but I'm not able to get any clue

`fish --profile prompt.prof -c 'fish_prompt' ` , and `sort -nk 2 prompt.prof.txt` shows

```
39      25284   -----> if set index (contains -i -- --path $packages)
19037   25849   ---------> test (count $argv) -ge 1
49      30634   ---> for i in $argv
126     31106   --> type -q git
10756   34586   ------> set index (contains -i -- --no-bundle $packages)
16      34602   -----> if set index (contains -i -- --no-bundle $packages)
67      50577   --------> switch "$argv[1]"
54348   54348   ------> command -s -- $i
58439   62541   ---> prompt_pwd
16065   70413   -----> set paths (command -s -- $i)
42      70519   ----> if test $multi != yes
20566   73036   -------> autoload $path/functions/{compat,core,index,packages,themes,bundle,util,repo,cli,search}       
8789    82010   ------> source $init $path
19806   82370   ----> require --no-bundle --path $OMF_CONFIG
63      86205   ---> for i in $argv
16797   103850  --> prompt_segment $color_dir_bg $color_dir_str (prompt_pwd)
20      103870  -> prompt_dir
17960   105771  --> type -q hg
108     130319  -----> for init in $init_path
10446   200151  ----> require --path {$OMF_PATH,$OMF_CONFIG}/pkg/*
938     308823  ---> source $OMF_PATH/init.fish
681     309541  --> source $file
4062    342668  -> for file in $__fish_config_dir/conf.d/*.fish $__fish_sysconf_dir/conf.d/*.fish $vendor_confdirs/*.fish
1669    359163  > builtin source /usr/share/fish/config.fish
515597  515597  ----> jobs -l | wc -l
524092  524092  -----> command git symbolic-ref HEAD 2> /dev/null
3458    527550  ----> set ref (command git symbolic-ref HEAD 2> /dev/null)
531840  531840  -----> echo $ref | sed  "s-refs/heads/-$branch_symbol -"
17227   532824  ---> [ (jobs -l | wc -l) -gt 0 ]
9       532833  --> if [ (jobs -l | wc -l) -gt 0 ]
556337  556390  ---> cwd_in_scm_blacklist | wc -c
561759  561759  ---> id -u $USER
31675   563515  ----> set -l branch (echo $ref | sed  "s-refs/heads/-$branch_symbol -")
13803   570193  --> [ (cwd_in_scm_blacklist | wc -c) -eq 0 ]
18921   580680  --> set -l uid (id -u $USER)
602898  602898  ----> command git rev-parse --is-inside-work-tree >/dev/null 2>&1
643151  643151  --------> command git status --porcelain $submodule_syntax $untracked_syntax 2> /dev/null
5354    648505  -------> set git_dirty (command git status --porcelain $submodule_syntax $untracked_syntax 2> /dev/null)66      648867  ------> if [ $__fish_git_prompt_showdirtystate = "yes" ]
74      648941  -----> parse_git_dirty
10237   659178  ----> set dirty (parse_git_dirty)
77      1113716 -> prompt_status
110     2354721 ---> if command git rev-parse --is-inside-work-tree >/dev/null 2>&1
54      2354824 --> prompt_git
34      3061966 -> if [ (cwd_in_scm_blacklist | wc -c) -eq 0 ]
31271   4317580 > fish_prompt
```

if I do `fish -d5`, i can see that it always paused on `path_get_path(xxx)`

**Comment by bochen2014** [comment]
![fish-slowness](https://user-images.githubusercontent.com/8207081/119248560-4f6e7800-bbd5-11eb-91ad-f7f7e3ef6af1.gif)

**Comment by bochen2014** [comment]
just upgraded to  `fish, version 3.2.2`, same slow, and `fish -d5` stops working 😭

**Comment by krobelus** [comment]
> i can see that it always paused on path_get_path(xxx)

Is one of the `$PATH` entries on a network share? You can try removing things from `$PATH` until it works.

> 938     308823  ---> source $OMF_PATH/init.fish

you should also use a an empty `$HOME` for profiling, to make it easier to compare times.
With an empty config, that `fish -c fish_prompt`  takes 28ms in the fish-shell Git repo.

> fish -d5 stops working

you can use something like `fish -d '*,-ast-construction'` for a really verbose log (but without the chatty parser log)

**Comment by faho** [comment]
>Is one of the $PATH entries on a network share? You can try removing things from $PATH until it works.

Or is $PATH massive, e.g. because you've been appending to $fish_user_paths in config.fish?

-----

Really, *everything* is slow here, that points towards some thing everything does being slow, and $PATH lookup or the filesystem is one of those.

However, since `command git rev-parse --is-inside-work-tree >/dev/null 2>&1` takes 600ms, that points to your filesystem being slow, which we can do little about. Cygwin isn't a speed demon to begin with, make a slow configuration of that and you will have a bad time.

**Comment by faho** [comment]
Alright, without more info there's nothing for us to do, closing!
