### ISSUE TITLE
Where is path stored if there is no config.fish?

### ISSUE THREAD

**Issue by cykac04** [fish-shell/fish-shell#8026]
fish, version 3.1.0
Ubuntu 16.04, xterm

I have not created any config.fish file yet, and I found all $path_file and $__fish_sysconfdir are empty. So where is the command "set path" stored to?

**Comment by faho** [comment]
There's two different things that could happen here:

1. Universal variables are stored in another file in ~/.config/fish/
2. Global variables are typically not stored *at all*, but are *inherited* from the parent process. So your terminal has the idea that $PATH (not $path - this is case-sensitive) is /usr/bin:/usr/sbin:/bin:/sbin, and when it starts fish it passes that along.

To be of any further assistance I would need *context*. What you are trying to do, what `$path_file` is supposed to be (it's not a variable fish uses) and what `set path` is.

**Comment by faho** [comment]
Alright, question has been answered to the best of my ability without further context, closing.
