### ISSUE TITLE
Implement EXECIGNORE feature

### ISSUE THREAD

**Issue by karmicdude** [fish-shell/fish-shell#8027]
I've been using bash for over a dozen years, but now I'm taking a closer look at fish. 
One of the things that is really missing is the functionality that performs the [`EXECIGNORE`](https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html) behavior in bash.
In brief, this is a list of exceptions that do not appear with autocomplete from the `PATH`-s

Why is that even necessary?

Well, for example, I install the `kubectx` package and now I have two `kubectx` and `kubens` binaries in the `PATH`.
Now if I type `kube[tab]`, instead of the expected `kubectl` completion (which I use very often, while the other two very rarely), I see the suggestion by three binaries. 

This is just one case, but it is quite revealing. I wanted to ask to implement this functionality. If this is not considered, then I will come up with some crutches, such as manual installation in the hidden `bin` directory which is not listed in the `PATH`.

Or maybe you can advise some more acceptable way.

**Comment by faho** [comment]
No, thanks.

This isn't the sort of feature we want in fish. It's customizability that few people will ever find out about or need, and there's a much better solution available: Fix your $PATH.

If you really don't want to call these other binaries, don't install them to $PATH.
