### ISSUE TITLE
Expose sending PID of trapped signal to script?

### ISSUE THREAD

**Issue by Korkman** [fish-shell/fish-shell#8029]
I don't know how feasible this is (especially if not portable, that would be a no-go), but what do you think about exposing the sending PID of a signal? My use case is having disowned background jobs which will send a SIGUSR1 back to the fish process when done. Right now, telling which job finished would require a named pipe or similar technique (possibly indirect, through universal variables, although this wastes disk I/O). Just tracking the PIDs would be way more easy and efficient.

sigaction has even more to offer, but I didn't look into it too much, so I don't know if more low-hanging fruits are in there that would be valuable to expose as well.

**Comment by faho** [comment]
>My use case is having disowned background jobs which will send a SIGUSR1 back to the fish process when done. 

.... why would you disown them?

If you want the shell to talk to a background job, don't do that. That's what `wait` is for, and what something like `function --on-job-exit` can already be used for.

Signal handlers are super gnarly and super unstandardized business, and I don't think we want to get into them more. Sorry!

**Comment by zanchey** [comment]
This recent article also covers the difficulties of doing this (tricky to get right due to the async-signal-safe handler requirements, limited platform availability, totally useless on macOS): https://vorner.github.io/2021/01/03/dark-side-of-posix-apis.html

**Comment by Korkman** [comment]
Ew, thanks for the information @zanchey. I had hopes the PID was readily available, but reading into this, it seems not worth the trouble.

@faho This kind of background jobs (a timer, in fact) should be hidden from `jobs`, so they don't confuse the user. Another approach would be a second, "hidden" jobs list (maybe accessible with jobs --hidden or smth.) but that feels even more labor intensive to implement and I'm probably the only one in need for this :grimacing:
