### ISSUE TITLE
Double clicking first output word selects rprompt

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [fish-shell/fish-shell#8037]
```
> fish --version
fish, version 3.2.2
> echo $version
3.2.2
> uname -a
Linux x1e 5.12.3-arch1-1 #1 SMP PREEMPT Wed, 12 May 2021 17:54:18 +0000 x86_64 GNU/Linux
> echo $TERM
foot
```

When double clicking the first word in the output to select it, this also selects the last word of the time/RPROMPT:
<img src="https://ragnargrootkoerkamp.nl/upload/2021-05-31T11:47:03+02:00.xqs6lGrtQf.png"/>

Expected behavior: only `selection` is selected
Actual behavior: both `selection` and `39` on the previous line are selected.

Note that this only happens with foot terminal, not with e.g. alacritty. On the other hand, ZSH in foot doesn't have this problem: when setting e.g. `RPROMPT=abc` and running `echo selection`, double clicking `selection` only selects that word and not the `abc` in the RPROMPT.
I.e., this problem only happens on fish in combination with foot, so I'm not sure which of the two need fixing.

**Comment by faho** [comment]
Fish has no mouse support and therefore no influence over what clicking in your terminal does.

It's possible fish draws this slightly differently than zsh, but the underlying issue is in your terminal, and that's where you should report it.

**Comment by RagnarGrootKoerkamp** [comment]
Right, that makes sense.

Reported this to foot as well: https://codeberg.org/dnkl/foot/issues/565

**Comment by zanchey** [comment]
Looks like this is being tackled there, so I'm closing this for now.
