### ISSUE TITLE
`git add` autocompletes untracked when `status.showUntrackedFiles=no`

### ISSUE THREAD

**Issue by Susensio** [fish-shell/fish-shell#8040]
Maybe this is an intended behaviour, but I find it rather odd.

On a crowded folder I usually set `status.showUntrackedFiled=no`. That way, `git status` only shows tracked files. I think `git add` should suggest only tracked files too.

```fish
mkdir repo
cd repo
git init
git config --local status.showUntrackedFiles no
touch file1 file2 file3
git add file1
echo hi >> file1
git status
```

```
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
	new file:   file1

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   file1

Untracked files not listed (use -u option to show untracked files)
```
and now, the unexpected behaviour

```fish
git add ↹
```
```
file1  (Modified file)  file2  (Untracked file)
```
-----
current versions
```
fish, version 3.1.2
Linux nuc 5.10.0-6-amd64 #1 SMP Debian 5.10.28-1 (2021-04-09) x86_64 GNU/Linux
```

**Comment by faho** [comment]
Calling `git add` on that file still works, so the completions should still show it.

**Comment by Susensio** [comment]
@faho 
I know this is a closed subject, but how could I modify this behaviour properly?

I've managed to copy default `completions/git.fish` to my local `.config` folder, and edit the following lines
```
#complete -f -c git -n '__fish_git_using_command add' -a '(__fish_git_files modified untracked deleted unmerged)'

function __git_showuntracked
	if test (__fish_git config --get status.showuntrackedfiles; or echo "") = no
		return 1
	end
end 

complete -f -c git -n '__fish_git_using_command add; and __git_showuntracked' -a '(__fish_git_files modified untracked deleted unmerged)'
complete -f -c git -n '__fish_git_using_command add; and not __git_showuntracked' -a '(__fish_git_files modified deleted unmerged)'
```
And it works as expected.

I had to do it this way because `complete -e` erases all completions anyway.

My question: can it be done incrementally? I just want to override the default `git add` completion, not everything else. I don't want to miss future updates by doing this the hard way.

**Comment by faho** [comment]
> My question: can it be done incrementally?

No.

Again, since git add *works* here (in a sensible manner), it should be completed. So this isn't a customization point, so your option is to override the completions completely.

**Comment by Susensio** [comment]
I know git add works on untracked files so completion should is correct, but maybe modified files should appear first in this case?  Right now they appear last!

My use case is this:
I have a dotfiles bare repository sitting in my `~/.dotfiles/` folder
I have a function `dotfiles` that wraps `git` with the necesary parameters (working dir, bare...).
When I add a file, it's usually a modified one.
Lets say I `cd ~/.config/fish/functions` and I modify `venv.fish` which is already part of my repo. When I `dotfiles add ↹` completion shows 50+ untracked files and folders and the last item in the completion list is `myfunc.fish`.
Even more. if an untracked `test` file is in my cwd, It appears **last** next to my modified file in the completion list.

```
susensio@nuc:~/.config/fish/functions$ ll
total 20K
-rw-r--r-- 1 susensio susensio  120 May 25 08:00 bat.fish
-rw-r--r-- 1 susensio susensio  375 May 31 07:50 dotfiles.fish
-rw-r--r-- 1 susensio susensio 1.1K May 24 20:50 fish_prompt.fish
-rw-r--r-- 1 susensio susensio    0 Jun 12 10:19 test
-rw-r--r-- 1 susensio susensio  163 Jun  1 07:19 upgrade.fish
-rw-r--r-- 1 susensio susensio   99 Jun 12 10:12 venv.fish
susensio@nuc:~/.config/fish/functions$ dotfiles status
On branch master
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   venv.fish

no changes added to commit (use "git add" and/or "git commit -a")
susensio@nuc:~/.config/fish/functions$ dotfiles add ↹
:/.config/calibre                    (Untracked file)
:/.config/Code                       (Untracked file)
:/.config/dconf                      (Untracked file)
:/.config/enchant                    (Untracked file)
:/.config/evolution                  (Untracked file)
:/.config/extensions-sync.json       (Untracked file)
:/.config/fish/completions/git_fish  (Untracked file)
:/.config/fish/config.fish           (Untracked file)
:/.config/fish/\\\\                  (Untracked file)
:/.config/gedit                      (Untracked file)
:/.config/GIMP                       (Untracked file)
:/.config/gnome-control-center       (Untracked file)
:/.config/goa-1.0                    (Untracked file)
:/.config/google-chrome              (Untracked file)
:/.config/gtk-2.0                    (Untracked file)
:/.config/gtk-3.0                    (Untracked file)
:/.config/gtk-4.0                    (Untracked file)
:/.config/htop                       (Untracked file)
:/.config/ibus                       (Untracked file)
:/.config/libreoffice                (Untracked file)
:/.config/menus                      (Untracked file)
:/.config/mimeapps.list              (Untracked file)
:/.config/pulse                      (Untracked file)
:/.config/solaar                     (Untracked file)
:/.config/spotify                    (Untracked file)
:/.config/tldr                       (Untracked file)
:/.config/user-dirs.dirs             (Untracked file)
:/.config/user-dirs.locale           (Untracked file)
:/.config/yelp                       (Untracked file)
:/.dbus                              (Untracked file)
:/.dotfiles.git                      (Untracked file)
:/.gitconfig                         (Untracked file)
:/.gnome                             (Untracked file)
:/.gnupg                             (Untracked file)
:/.ICEauthority                      (Untracked file)
:/.ipython                           (Untracked file)
:/.lesshst                           (Untracked file)
:/.local                             (Untracked file)
:/.mozilla                           (Untracked file)
:/.pki                               (Untracked file)
:/.profile                           (Untracked file)
:/.python_history                    (Untracked file)
:/.ssh                               (Untracked file)
:/.venv                              (Untracked file)
:/.vim                               (Untracked file)
:/.viminfo                           (Untracked file)
:/.vscode                            (Untracked file)
:/.wget-hsts                         (Untracked file)
:/Downloads                          (Untracked file)
:/Pictures                           (Untracked file)
:/Projects                           (Untracked file)
test                                 (Untracked file)
venv.fish                             (Modified file)
rows 6 to 58 of 58
```

Could this issue be classified as a feature-request or an improvement? I would like to work on it

**Comment by faho** [comment]
>I know git add works on untracked files so completion should is correct, but maybe modified files should appear first in this case? Right now they appear last!

We override the sort order where the default order doesn't make sense. In the case of commits that's because the commit hashes by themselves are meaningless, and ordering them lexicographically implies nothing. There's no reason "cafebabe" should appear before "f00df00d". So ordering by commit date gives you more information.

In this case the candidates are *filenames*, so they should just be sorted like filenames are sorted basically everywhere else. There's value in consistency.

Modified files don't appear last, "venv.fish" simply sorts after "test". If you had an untracked file called "zzz" it would appear after "venv.fish".

So: Thanks, but no.

**Comment by Susensio** [comment]
And what about the `cwd` argument? Don't you think that file completion should be based on the working directory from which it is being called?
If I edit some file with `vim` and then `git add` it, I expect completion engine to work similarly. Not doing so is rather inconsistent.

**Comment by ridiculousfish** [comment]
It does seem like `git add` doesn't work properly when run from a subdirectory. In particular `git add ./<tab>` doesn't seem to work properly at all. Probably once that's fixed, the sort order will appear more natural (though I can see improving it to preferring completions with fewer directory separators, maybe). Anyways you said you'd be willing to work on it and we'd certainly be grateful for fixes here.

**Comment by faho** [comment]
>It does seem like git add doesn't work properly when run from a subdirectory. 

No, it works.

`git add` accepts files with `:/`, which denotes the root of the repository. So if you e.g. are in the "src" subdirectory of the fish repo, you can add a file in share/ with `git add :/share/`.

That's on purpose.

>In particular git add ./<tab> doesn't seem to work properly at all

The issue here is the old problem of unresolving paths - we'd need to figure out that git's "share/completions/git.fish" matches "./completions/git.fish", and *then* we need to replace that "share/" with "./".

**Comment by Susensio** [comment]
> We override the sort order where the default order doesn't make sense. In the case of commits that's because the commit hashes by themselves are meaningless, and ordering them lexicographically implies nothing. There's no reason "cafebabe" should appear before "f00df00d". So ordering by commit date gives you more information.
> 
> In this case the candidates are _filenames_, so they should just be sorted like filenames are sorted basically everywhere else. There's value in consistency.

I'm looking at the git.fish completion code. I'm probably missing someting, correct me if I'm wrong.
`git add` completes using `__fish_git_files`, which calls `git status --porcelain=v2`
If I call it myself, tracked files appear first!

```
susensio@nuc:~/.config/fish/functions$ git --git-dir=$HOME/.dotfiles.git/ --work-tree=$HOME status --porcelain=2 -unormal
1 .M N... 100644 100644 100644 7070f7aaa2a1a2479b6fbbdaecf772a296824ce2 7070f7aaa2a1a2479b6fbbdaecf772a296824ce2 venv.fish
? ../../../.ICEauthority
? ../../../.bash_history
? ../../../.bash_logout
? ../../../.bashrc
? ../../../.cache/
? ../../Code/
? ../../GIMP/
? ../../autostart/
? ../../calibre/
? ../../dconf/
? ../../enchant/
? ../../evolution/
? ../../extensions-sync.json
? ../completions/.git.fish.swp
? ../completions/git.fish
? ../config.fish
? test
? ../../gedit/
? ../../gnome-control-center/
? ../../goa-1.0/
? ../../google-chrome/
? ../../gtk-2.0/
? ../../gtk-3.0/
? ../../gtk-4.0/
? ../../htop/
? ../../ibus/
? ../../libreoffice/
? ../../menus/
? ../../mimeapps.list
? ../../pulse/
? ../../solaar/
? ../../spotify/
? ../../tldr/
? ../../user-dirs.dirs
? ../../user-dirs.locale
? ../../yelp/
? ../../../.dbus/
? ../../../.dotfiles.git/
? ../../../.gitconfig
? ../../../.gnome/
? ../../../.gnupg/
? ../../../.ipython/
? ../../../.lesshst
? ../../../.local/
? ../../../.mozilla/
? ../../../.pki/
? ../../../.profile
? ../../../.python_history
? ../../../.ssh/
? ../../../.venv/
? ../../../.vim/
? ../../../.viminfo
? ../../../.vscode/
? ../../../.wget-hsts
? ../../../Downloads/
? ../../../Pictures/
? ../../../Projects/
```
I think `git` itself is providing a saner ordering, but where in the code is this being mangled? `__fish_git_files` appear to parse line by line.

**Comment by faho** [comment]
>If I call it myself, tracked files appear first!

Completions are sorted by default. If you want to keep the order, you need to give the `--keep-order` flag to the `complete` call.

**Comment by zanchey** [comment]
> My question: can it be done incrementally? I just want to override the default `git add` completion, not everything else. I don't want to miss future updates by doing this the hard way.

You could do something gnarly with string matching and source, but it would be pretty fragile.
