### ISSUE TITLE
hwo to add two paths for one variable in fish?

### ISSUE THREAD

**Issue by tianyma** [fish-shell/fish-shell#8045]
here is the case:
I have two paths:
`
~/.mujoco/mujoco200/bin
`
and 
`
/usr/local/cuda-10.2/lib64
`
I want to add both to variable **LD_LIBRARY_PATH**.
this is how I do but not work:
`
set -gx LD_LIBRARY_PATH $LD_LIBRARY_PATH ~/.mujoco/mujoco200/bin /usr/local/cuda-10.2/lib64
`
can anyone help me? Thank you!

**Comment by faho** [comment]
No, that's correct.

What is your fish version?

What exactly does not work?

**Comment by tianyma** [comment]
> No, that's correct.
> 
> What is your fish version?
> 
> What exactly does not work?

my fish version is 2.7.1.
the problem is when I import mujoco_py in python, it echos
`
➜  ~ python                                                                (rl) 
Python 3.9.4 (default, Apr  9 2021, 16:34:09) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mujoco_py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tianyun/anaconda3/envs/rl/lib/python3.9/site-packages/mujoco_py-2.0.2.13-py3.9.egg/mujoco_py/__init__.py", line 3, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/home/tianyun/anaconda3/envs/rl/lib/python3.9/site-packages/mujoco_py-2.0.2.13-py3.9.egg/mujoco_py/builder.py", line 510, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/home/tianyun/anaconda3/envs/rl/lib/python3.9/site-packages/mujoco_py-2.0.2.13-py3.9.egg/mujoco_py/builder.py", line 69, in load_cython_ext
    _ensure_set_env_var("LD_LIBRARY_PATH", lib_path)
  File "/home/tianyun/anaconda3/envs/rl/lib/python3.9/site-packages/mujoco_py-2.0.2.13-py3.9.egg/mujoco_py/builder.py", line 115, in _ensure_set_env_var
    raise Exception("\nMissing path to your environment variable. \n"
Exception: 
Missing path to your environment variable. 
Current values LD_LIBRARY_PATH=/home/tianyun/.mujoco/mujoco200/bin/usr/local/cuda-10.2/lib64
Please add following line to .bashrc:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/tianyun/.mujoco/mujoco200/bin
>>> 

`

**Comment by faho** [comment]
>my fish version is 2.7.1.

Ah, there's your issue. $LD_LIBRARY_PATH isn't a list in 2.7.1 (only since 3.0), so you'll have to do it like this:

```fish
 set -gx LD_LIBRARY_PATH "$LD_LIBRARY_PATH:$HOME/.mujoco/mujoco200/bin:/usr/local/cuda-10.2/lib64"
```

("$HOME" because tilde-expansion won't trigger here)

This will still work in later versions.

Sidenote: You are missing 45% of all commits ever made to fish. If you want to upgrade https://fishshell.com/ most likely has a PPA you can use.

**Comment by tianyma** [comment]
that works, thank you very much, Fabian. I will update my fish to the latest version.
