### ISSUE TITLE
[fish 3.2.2] commands preceded by space are no longer ignored in history

### ISSUE THREAD

**Issue by Drag0nFly** [fish-shell/fish-shell#8052]
**Fish version:** 3.2.2

**OS/term:** Linux/xterm-256color

To reproduce:

Start a prior version of fish, in this case 3.1.2 was tried.

run:

`>  pwd` (note the extra space at the beginning of the command)

and scroll up. notice that the " pwd" command is not present, due to being preceded by space.

Run the same command with a recent fish version (tried 3.2.1 and 3.2.2):

`>  pwd`

and scroll up. The " pwd" command is now present in history, although such was not intended.

**Comment by faho** [comment]
It is not stored on disk, it is only present until you execute the next command. This was an intentional change (#1383).
