### ISSUE TITLE
[QUESTION] Filtering of history

### ISSUE THREAD

**Issue by pawlosck** [fish-shell/fish-shell#8055]
Is it possible to filter of history from cmd?
Something like SHIFT+TAB, but for history.
I have a lot of long commands with pipes and I would like to search for commands directly in cmd. I would like to filter whole history and whole lines (with parameters, next commands in pipe etc).

Currently, I am using command "history |grep -F  "env"|less" but I would like to do it faster.

PS. Could you tell me other methods to search things in fish. I found SHIFT+TAB, but it looks like "PART_OF_COMMAND + TAB".
Is there other commands or shortcuts to find something.

**Comment by faho** [comment]
Simply enter whatever you're looking for into the commandline and press up-arrow.

**Comment by pawlosck** [comment]
"up-arrow" is ok, but I would like to use something like this
![image](https://user-images.githubusercontent.com/3769853/121739940-a1cbf600-cafc-11eb-8ac8-27232685af9d.png)

I would like to see all matched items. Is it possible for history?

**Comment by faho** [comment]
#602,  not currently implemented.

**Comment by pawlosck** [comment]
I found this issue https://github.com/fish-shell/fish-shell/pull/6686
It looks like implemented feature, but not merged with master.

**Comment by faho** [comment]
It's not done. Anyway, the question has been answered so I'm closing this.

**Comment by pawlosck** [comment]
I found solution for this problem
You have to install peco and put these  two files info /etc/fish/function/. You have to remove "txt" extension and leave ".fish" extension. Github doesn't allow to send some type of files.
[peco_select_history.fish.txt](https://github.com/fish-shell/fish-shell/files/7230430/peco_select_history.fish.txt)
[fish_user_key_bindings.fish.txt](https://github.com/fish-shell/fish-shell/files/7230431/fish_user_key_bindings.fish.txt)

I found it at youtube -> https://www.youtube.com/watch?v=KKxhf50FIPI.
I had to add one line to remove prefix with timestamp from line. Rest of code is the same.
echo $foo | cut -c 25- |read foo

You can check it, how it will look without any modification, when you run these commands "history|peco --layout=bottom-up". Line returned by peco, will be entered into command line, after using these two functions.
