### ISSUE TITLE
builtin not

### ISSUE THREAD

**Issue by Susensio** [fish-shell/fish-shell#8056]
I'm trying to understand the `not` builtin command, but I cannot find it in the source code... difficult keyword to search for.

`man not` says
```
NOT(1)                                                               fish-shell                                                              NOT(1)

NAME
       not - negate the exit status of a job
```
So I'm trying this

```
function return0; return 0; end
function return1; return 1; end
```
And it works as expected
```
return0

return1
[1]
```

But if a try to use `not`
```
not return0

not return1
[1]
```
It doesn't work. What am I missing?

**Comment by ridiculousfish** [comment]
Thanks for filing. What prompt are you using? What does this show:

    `not return0; echo $status`

I expect that to print 1 and it does for me.

**Comment by faho** [comment]
This smells like #6566 - the default prompt had a bug. In which case the answer is simple: Upgrade to fish 3.2.

Which is also why the issue template asks for your fish version, please fill it in next time.

**Comment by Susensio** [comment]
Endeed, my fish version is 3.1.2
My apologies

**Comment by faho** [comment]
So it's #6566, closing as a duplicate.
