### ISSUE TITLE
[Question] Set alias to cd to direct directory

### ISSUE THREAD

**Issue by buinguyenhoangtho** [fish-shell/fish-shell#8063]
# VERSION
```fish, version 3.1.0```
# Question 
Hi. May i ask it possible to make an alias to cd into the correct path?
Let said i have path
`~/.foo/bar/the-directory-i-want`

Now i want make alias to  `cd` to the `the-directory-i-want` by typing `$ the-directory-i-want` . Is there any way?

**Comment by zanchey** [comment]
The `CDPATH` variable might help - if you `set -U CDPATH ~/.foo/bar` then `cd the-directory-i-want` will search for that directory in the directory. See the [`cd` documentation](https://fishshell.com/docs/current/cmds/cd.html).

**Comment by buinguyenhoangtho** [comment]
Oh sorry for wrong questions. Actually i only need to create an alias like `$ the-directory-i-want`. Not cd. Sorry for miss-information

**Comment by zanchey** [comment]
Setting `CDPATH` will let it work without `cd` if you add a trailing slash (this is called "implicit `cd`): `the-directory-i-want/`. There is some discussion in #22 of this feature.

**Comment by buinguyenhoangtho** [comment]
> Setting `CDPATH` will let it work without `cd` if you add a trailing slash (this is called "implicit `cd`): `the-directory-i-want/`. There is some discussion in #22 of this feature.

so i finally understand `CDPATH` part. Im just noob about linux/ubuntu. So i can't find out where can i set CDPATH . :sweat_smile: in fish-shell

**Comment by zanchey** [comment]
The easiest way is to run `set -U CDPATH  ~/.foo/bar` at the command line. This sets a universal variable, which will apply to all other fish sessions too.

Alternatively, put `set -g CDPATH ~/.foo/bar` in your fish configuration (usually in `~/.config/fish/config.fish`). Using something like this is safest:

```fish
if status is-interactive
    set -g CDPATH ~/.foo/bar
end
```

If you go down the second route, you need to restart fish for it to apply.

**Comment by buinguyenhoangtho** [comment]
Thanks. It work :D. I will close the issue
