### ISSUE TITLE
[SOLVED] Dbus Error using fish

### ISSUE THREAD

**Issue by AllanPamplona** [fish-shell/fish-shell#8064]
`fish, version 3.2.2`

SO:
`Linux Allan-PC 5.12.10-arch1-1 #1 SMP PREEMPT Thu, 10 Jun 2021 16:34:50 +0000 x86_64 GNU/Linux`

I'm getting this error when trying to use fish in both default and interactive (from bashrc) execution modes:

```
Error org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Failed to communicate with dunst, is it running? Or maybe the version is outdated. You can try 'dunstctl debug' as a next debugging step.
Error org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Failed to communicate with dunst, is it running? Or maybe the version is outdated. You can try 'dunstctl debug' as a next debugging step.
Traceback (most recent call last):
  File "/home/allan/.script/dunst", line 58, in <module>
    RTN = mute_off()
  File "/home/allan/.script/dunst", line 28, in mute_off
    subprocess.run(["dunstctl", "set-paused", "false"], check=True)
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['dunstctl', 'set-paused', 'false']' returned non-zero exit status 1.
```

My system is currently running i3gaps and i3blocks as WM. I also have fisher installed with two plugins: dracula/fish and 
matchai/spacefish.
This is how I am executing Dunst from i3:
```
exec --no-startup-id dunst
```
Steps:

1. Set fish as default bash with chsh
2. Reboot
3. Login
4. Execute startx (I use startx to start my system - RELEVANT?)
5. i3 starts but without notifications
6. Manually execute dunst from console
7. Fails with given error after a while

This behavior happens using fish from bashrc too. If i revert my system to bash and logout, it works.
I don't know if there're more applications that fails using DBus, I just notice dunst. Also i can't say if it is a fish or a dunst problem yet.

**Comment by faho** [comment]
`dunst` is a notification daemon and notifications run over dbus. Fish doesn't do anything dbus-related.

So I'm finding it hard to see how fish could be related, but then I don't actually know how you've configured your system and I've always shied away from the startx stuff as it seemed super hacky.

**Comment by krobelus** [comment]
AFAIK most distributions don't support running fish as login shell, because
they customize /etc/profile which fish doesn't read

**Comment by AllanPamplona** [comment]
So i made this works by doing this:
`sh /etc/X11/xinit/xinitrc.d/50-systemd-user.sh`
before exec i3 in my .xinitrc.

Thanks!
