### ISSUE TITLE
Selected sub-command text is the same as it's background

### ISSUE THREAD

**Issue by alvinseville7cf** [fish-shell/fish-shell#8070]
Fish version: fish, version 3.2.2-204-gfc0dd4984
OS: Ubuntu 20.04.2 LTS (WSL)

Selected sub-command text is the same as it's background:

![image](https://user-images.githubusercontent.com/42812113/122530608-fffb5a80-d061-11eb-9b63-4ed764c38e5d.png)

Everything is normal with command options:

![image](https://user-images.githubusercontent.com/42812113/122530709-1ef9ec80-d062-11eb-8ccf-95554efe104a.png)

**Comment by faho** [comment]
The background should be $fish_pager_color_selected_background, which we don't set at all by default. It falls back on the background of $fish_color_search_match, which is "brblack" by default, while the text color is $fish_pager_color_selected_completion, which falls back on $fish_pager_color_completion, which falls back on $fish_color_normal, which is set to "normal" by default.

So either you've adjusted your configuration for any of these variables, or your terminal doesn't distinguish between "brblack" and "normal" enough. Unfortunately there is no way for us to really know what color these end up being, so you'll have to fix it yourself - supporting arbitrary terminal colorschemes and light backgrounds (which are a bit of a rarity) with the same colorscheme is basically impossible. We could try setting more rgb values, in case your terminal supports direct rgb colors.

**Comment by alvinseville7cf** [comment]
`echo (set_color normal --background=brblack)my test string` outputs:

![image](https://user-images.githubusercontent.com/42812113/122535663-1f48b680-d067-11eb-8630-2afc2a2da3aa.png)

**Comment by faho** [comment]
In that case you've customized your settings (or have some old ones left over). Check the variables I mentioned above.

**Comment by faho** [comment]
Question has been answered, closing!
