### ISSUE TITLE
Dumb Question: Why can't I send KeyboardInterrupt (Ctrl+C) in fish?

### ISSUE THREAD

**Issue by AlbinoGeek** [fish-shell/fish-shell#8073]
## Synopsis

Trying out fish for the first time, and other than this one issue, it's great to use.

In most other shells, sending a `Ctrl+C` will send a SIGINT and (generally) cause the executing script/program to close. In Fish, pressing `Ctrl+C` does literally nothing, and there does not appear to be any to send the SIGINT without opening a new terminal, finding the process ID, and manually sending the SIGINT (which... is disgracefully inefficient when other shells just do this out of the box.)

## Reproduction

```
bash# fish
 ~  yes
y
y
y
y
[ Attempt to press Ctrl+C ]
[ fish just laughs at you ]
[ nothing happens ]
```

## Versions:

Fish 3.2.1
Fedora 34
Kernel 5.12.9-300

powerline-fonts + opm + bobthefish

**Comment by AlbinoGeek** [comment]
Worth noting that Googling this just brings up advice to use `Ctrl+U` , which definitely doesn't work either (different use of `Ctrl+C` entirely.)

**Comment by faho** [comment]
Works for me. What does `type yes` say?

**Comment by AlbinoGeek** [comment]
`yes` is `/usr/bin/yes` (as expected) -- this is reproducible with ANY binary or `bash` or `sh` script.

I also literally installed fish yesterday, this was and still is the latest version available in Fedora 34 repositories.

```
# dnf list fish
fish.x86_64                                                  3.2.1-2.fc34
```

Also... fish without bob would defeat my whole purpose of trying out fish, as my bash has working powerline already -- but hey, I'll try it to simplify the bug report (remove variables):

```
 ~  omf uninstall bobthefish
bobthefish successfully removed.
 ~  exec fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
⋊> ~ yes
y
y
y
y
[ still ignoring Ctrl+C ]
```

Can confirm, **bobthefish was not the problem.**

**Comment by ridiculousfish** [comment]
This actually reproduces easily with:

    docker run -ti fedora:34
    sudo dnf install fish
    fish

and then `yes`  cannot be cancelled. This is very strange of course; I have not seen this with any other distro. I'll investigate.

**Comment by AlbinoGeek** [comment]
Whoa! I didn't realize it was that easy to reproduce. But yes, it seems
like this happens regardless of what I install.

Interestingly enough however, after I went a few levels deep in Shell
inheritance, it started working again, but only with ohmyfish, bobthefish,
fisher, and a whole bunch of other plugins installed did it start working
again.

So, I have to assume that something is broken in the main application, that
was patched by one of the programs or plugins I installed.

Yeah, I know that's not great for a bug report, so I'm glad that you were
able to reproduce it so simply from fresh installation with no plugins.

**Comment by ridiculousfish** [comment]
I take it back, the same steps also "reproduce" with bash, and on other distros...it seems like `yes` is just hard to cancel because it produces a lot of output.

@AlbinoGeek can you check if `sleep` can be SIGINTed? That is run `sleep 100` and try to cancel with control-C, does that work? It does for me.

**Comment by ridiculousfish** [comment]
My guess is this is terminal emulator dependent. It's a lot easier to sigint `yes` with alacritty than with iTerm2. But I can't reproduce any differences between fish or other shells here (and would not expect there to be any differences).

**Comment by AlbinoGeek** [comment]
To remove all the variables, I am using Fedora 34 on an Xorg Gnome-shell
(40) using Guake fullscreen terminal in tmux.

However, I have been able to reproduce this behavior in vanilla fish, on
for their 34, with gnome shell 40, using Xterm as well.

And yes, unfortunately this is reproducible with a script wrapping sleep as
well.

It is also reproducible with sleep, but both shells implement this is a
built-in not an external command, hence me testing with a script.

```
#!/usr/bin/env bash
sleep 60
```

chmod +x sleep.bash
./sleep.bash

**Comment by AlbinoGeek** [comment]
Bad habit of replying from email, I see GitHub doesn't like that much;

On the "now working" installation (with lots of plugins):

[ inside guake tmux ]

```
 ~/P/v/s/client   *$…  omf doctor
Oh My Fish version:   7
OS type:              Linux
Fish version:         fish, version 3.2.1
Git version:          git version 2.31.1
Git core.autocrlf:    no
Checking for a sane environment...
Your shell is ready to swim.
 ~/P/v/s/client   *$…  echo $SHELL $TERM $COLORTERM $GDK_BACKEND
/bin/bash screen truecolor x11
```

---

On the "still not working" installation:

[ in either guake or xterm, no tmux layer ]

```
⋊> ~/P/v/s/client on main ⨯ fish --version
fish, version 3.2.1
⋊> ~/P/v/s/client on main ⨯ type omf
type: Could not find 'omf'
⋊> ~/P/v/s/client on main ⨯ echo $SHELL $TERM $COLORTERM $GDK_BACKEND
/bin/bash xterm-256color truecolor
```

---

Both machines share these in common:

|Thing|Version
|-|-|
|distro|Fedora 34
|kernel|5.12.9-300.fc34.x86_64
|fish|3.2.1

**Comment by faho** [comment]
@AlbinoGeek 

>And hell, since I figure someone's going to ask for it, I'll also try a fresh fish (in case omf supposedly breaks things):

This is notably missing ~/.config/fish, which is where you'd typically put fish's config.

It's not *just* about OMF specifically, it's about *any* form of config.

---------------------

What does `stty -a` say on both systems?

What happens if you run the working fish outside of tmux? The broken one inside?

**Comment by krobelus** [comment]
Yeah it seems unlikely that this is specific to fish.
I can reproduce with `bash` in `xterm` with `docker run -ti rm fedora:34`.
but not on `gnome-terminal` or `konsole`. The `stty` values are the same except that xterm has `erase = ^H`

**Comment by faho** [comment]
Okay, it seems like this isn't a fish issue, as we've managed to reproduce it in bash.

Apparently it's down to certain versions of `yes` being hard to quit in certain terminals, which would be a bug there.

**Comment by ckhatton-pvfscaffolding** [comment]
Anyone stumbling accross this using Byobu... If you want to kill the window, without killing the whole session:

<kbd>ctrl</kbd> + <kbd>a</kbd> (selecting number 1, if prompted), then <kbd>k</kbd>

If it asks for confirmation, type `y` and hit <kbd>enter</kbd>.
