### ISSUE TITLE
Advice; or, wrapping functions already provided by fish?

### ISSUE THREAD

**Issue by adamroyjones** [fish-shell/fish-shell#8074]
I adore fish—thank you for all of your work!

I've a brief question about wrapping a function that fish provides: `cd`.

My aim is for shells to pick up where they left off. That is, if I open a new shell, I want it to start in the last directory that was opened. My approach has been to take the [take the definition of `cd` as provided by fish](https://github.com/fish-shell/fish-shell/blob/3.2.2/share/functions/cd.fish), define it in my configuration as `__fish_cd`, and then define

```fish
function cd
    __fish_cd $argv
    set --universal last_directory (pwd)
end
```

and to change into `$last_directory` when opening a new shell, etc.

This works (how could it not, given how trivial it is?), but it feels a bit wasteful to be copying the contents of the definition like that. In a Lisp, you can often patch things by supplying [advice](https://en.wikipedia.org/wiki/Advice_(programming)). Is there an approach like this that applies to fish?

**Comment by faho** [comment]
>Is there an approach like this that applies to fish?

No. Just copy the function - it's simple and easy to reason about.

We provide `functions --copy` so you can copy the function automatically.

*Alternatively*, define an `--on-variable PWD` handler:

```fish
function save-dir --on-variable PWD
    set -U last_dir $PWD
end
```

Or get a terminal that already starts the shell in the last directory (Konsole started doing that a while ago).

Advice is complicated semantically, and not of much more use, so I don't believe it is worth implementing.

**Comment by adamroyjones** [comment]
> We provide functions --copy so you can copy the function automatically.

Ah, that works perfectly! Thanks for the suggestion (and sorry for not noticing it in the documentation).
