### ISSUE TITLE
Please document the fish built-in wrapper of /usr/bin/man

### ISSUE THREAD

**Issue by HouzuoGuo** [fish-shell/fish-shell#8077]
Fish version and the host OS:

```
howard@ip-10-12-2-77 ~> fish --version
fish, version 3.1.0

howard@ip-10-12-2-77 ~> uname -a
Linux ip-10-12-2-77 5.8.0-1035-aws #37~20.04.1-Ubuntu SMP Tue Jun 1 09:54:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

I was looking for the manual page of `/usr/bin/time`, so quite naturally I ran `man 1 time` and was greeted with the manual page of fish built-in `time` instead of the binary executable's.

I suspected that fish may have used a wrapper around `/usr/bin/man`, so in a second attempt `/usr/bin/man 1 time` got me the manual page of the binary executable.

The built-in wrapper is however not mentioned in the docs: https://fishshell.com/docs/current/search.html?q=man

Please document the wrapper to serve as a reminder that in limited circumstances a user may wish to invoke the verbatim `/usr/bin/man` to read a manpage.

**Comment by faho** [comment]
Sure. Either a separate page or a note somewhere else is probably okay.

Or maybe even a note on every page that shadows something? Like at the bottom of our `time` man page include "this page documents fish's time builtin. For the command you might have, use `command man time`"?

>Please document the wrapper to serve as a reminder that in limited circumstances a user may wish to invoke the verbatim /usr/bin/man to read a manpage.

You want `command man` instead of hard-coding the path.

**Comment by HouzuoGuo** [comment]
`command man` sounds like a better idea indeed!

Adding clarifications to the manpage of fish built-in commands would definitely help.

**Comment by zanchey** [comment]
`man -a time` is helpful too, as it shows all manual pages in the path matching the argument.

**Comment by faho** [comment]
Alright, I added a note to the man pages specifically.
