### ISSUE TITLE
Incorrect instructions in FAQ that could lead to issues on some systems

### ISSUE THREAD

**Issue by oplexius** [fish-shell/fish-shell#8078]
The FAQ instructs to use the chsh command to set fish as the default shell (https://fishshell.com/docs/current/faq.html#how-do-i-make-fish-my-default-shell). However, this is inadvisable on some systems (e.g. Gentoo, Arch...), and will lead to issues on these systems as they do not support non POSIX shells as login shells.

On these systems, proposed solutions are running fish from .bashrc (so that bash can set up the environment and pass it on to fish), or setting fish as the login shell and sourcing various files with the bass utility in config.fish.

See https://wiki.gentoo.org/wiki/Fish and https://wiki.archlinux.org/title/fish for the methods these distributions advise to set fish as the default shell while avoiding serious issues.

I would expect these are not the only distributions for which setting a non POSIX shell as a user login shell could cause problems.

I would suggest at least indicating in the FAQ something along the lines of "Using chsh to change the login shell is a generic method that may not be appropriate for your distribution and could lead to issues. See distribution documentation for specific instructions.".

I could only find https://github.com/fish-shell/fish-shell/issues/3665#issuecomment-268527236 referencing this, but it is not concerning the FAQ.

Thanks, and all the best.

**Comment by faho** [comment]
These are very general instructions.

The reason those distros have issues is because they put system configuration into /etc/profile, but then start the session only with $SHELL. Personally, I would prefer if they stopped that. Either you specify the config outside of the shell or you don't use $SHELL.

Typically it's also not super important - some stuff my arch install does is add perl cruft to $PATH (which also seems to be done via some other method) and set $AWKPATH, whatever that is.

But yeah, it's probably tilting at windmills to ask for $SHELL to be meaningful, the chsh system has been broken by people abusing it.

**Comment by maciderio** [comment]
Agreed, though my intention in bringing this up was just to avoid any possible problems for inexperienced users blindly following the FAQ.

Looking at my Gentoo installation, I can at least see the possibility that just using chsh could cause the package manager to overwrite some configuration files and bother the user about files that should just be overwritten. To be honest, I'm having trouble working out how it all truly works - another reason for more precise documentation xD.

All the best.

**Comment by kidonng** [comment]
> However, this is inadvisable on some systems (e.g. Gentoo, Arch...), and will lead to issues on these systems as they do not support non POSIX shells as login shells.

Just FYI, I had been using Arch with fish as the default login shell for months without issues. Recently I also installed and used Arch for some time, so I can ensure things aren't much different from before.
Also, can you give a reference to this "they do not support non POSIX shells as login shells" line? Definitely not *officially* supported, but I don't think the opposite is true either.

**Comment by mqudsi** [comment]
I think it's fair for the default manual installation instructions to be the way they are. Customizing upstream packages to work with the tweaks and customizations of various distros is what patched downstream distribution-provided packages are for - whomever is writing the package for your platform could/should provide a fish-sourced equivalent of the cruft in `.bashrc` or `.profile` and include it in the distro-specific package.

That said, I'm going to re-iterate what @faho said: I've never seen any "mission critical" configurations set by distros in `.profile` or `.bashrc`, at worst, you'll be missing some optional `$PATH` component.

**Comment by oplexius** [comment]
The previous comment sums up why I thought it was important to file a bug in the first place.

With just a slight change in wording, the text could be strictly true, and **_avoid pushing anyone into problems_**. This without having to go into any details for various different systems. Even just adding something along the lines of "_some distributions may require specific steps, see relevant documentation_" might help.

Otherwise, I haven't responded yet because I want to take the time to do a fresh Gentoo install and compare with at least one other fresh distro, to be certain of how things work.

kidonng: there has been a reference on the Gentoo wiki fish article for some time (full disclosure - I have contributed to that article, but I didn't add that information, originally). There are also the issues I mentioned in the previous comment, but I'm just guessing from looking at the scripts - as I say, I really want to test. Good to know Arch works like that.

pohlt: big warning or not, I would first at least aim to have the text be strictly true ;)

All the best, thanks for the great shell.

**Comment by oplexius** [comment]
Well here is a coincidence: I sometimes listen to technical "podcasts" or presentations when doing manual work, and this came up yesterday, where the person directly brings up this very issue (at 10m49s):

https://youtu.be/Od2TJA9f2-Y?t=648

The person says that setting Fish as the default shell "broke things", causing "occasional" issues.

They mention several issues when setting Fish as the default shell with "chsh", on Arch Linux:
* image previews in vifm stop working
* problems logging in to certain window managers
* youtube-dl command issues
* errors building "snap pack" (on a different system)

I'm aware that it may be said that issues are related to the distribution in question, or software other than Fish - however a small change to the documentation here could at least warn users of possible issues, and give them a clue as to what caused some eventual issues.
