### ISSUE TITLE
GPG recipient suggestions are incomplete

### ISSUE THREAD

**Issue by torqueyy** [fish-shell/fish-shell#8079]
fish version: 3.2.1
OS: Fedora 34
Terminal: Tilix 1.9.4 and GNOME Terminal 3.40.1
No third-party customizations to fish

`gpg --list-keys` correctly shows all of my imported keys (9 of them).
`gpg -r` followed by `Tab` only presents three of these keys to use when choosing a recipient. zsh 5.8 correctly presents 9 keys to choose from with the same sequence of `gpg -r` followed by `Tab`.

How can I configure fish to work properly with gpg? I have searched the fish documentation as well as the GitHub issues here and have not found any mention of the problem am experiencing.

Thanks for reading this issue.

**Comment by zanchey** [comment]
The completion command runs `gpg --list-keys --with-colon | string split -a -f 10 : | string replace '\x3a' : | string replace -rf '(.*) <(.*)>' '$1\t$2'` so the first thing I would try and do is run that command and see if you get all the keys you are expecting.

**Comment by torqueyy** [comment]
`gpg --list-keys --with-colon | string split -a -f 10 : | string replace '\x3a' :` prints many entries, 9 of which have names. These are the same keys which appear with zsh's completion.

`gpg --list-keys --with-colon | string split -a -f 10 : | string replace '\x3a' : | string replace -rf '(.*) <(.*)>' '$1\t$2'` only presents three keys. So it would appear that it's the final string replace which is removing entries. Is there a variation of the string replace I can try which would make all entries appear?

**Comment by zanchey** [comment]
Do you have any keys which do not have usernames, or which don't match the format "Some name <email@example.com"?

**Comment by faho** [comment]
> Is there a variation of the string replace I can try which would make all entries appear?

What's removing the entries is the `--filter` or `-f`` option. So `string replace -r '(.*) <(.*)>' '$1\t$2'` would keep them.

However, I'm not sure if that's actually correct - gpg's commandline interface is... awkward.

**Comment by faho** [comment]
Alright, I just tried just a key id, and a name with and without email, and it seemed to work. So I just removed the filter.
