### ISSUE TITLE
`fish_add_path` creates empty PATH

### ISSUE THREAD

**Issue by acook** [fish-shell/fish-shell#8082]
fish, version 3.2.2

MacOS 11.4
Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
iTerm 3.4.8
xterm-256color

I've seen 2 behaviors.

One is easy to replicate - if PATH is empty before `fish_add_path`, then it will remain empty:

```fish
> set -e PATH
> fish_add_path -Pv "/usr/local/bin"
set PATH /usr/local/bin
> echo $PATH

> set PATH /bin
> fish_add_path -Pv "/usr/local/bin"
set PATH /usr/local/bin /bin
> echo $PATH
/usr/local/bin /bin
```

The second behavior I'm beginning to think was a false memory. But I swear in some situations I've seen it keep only the path passed in, and ignore all the others. This might have been because I believed `-v` was actually doing something when it wasn't.

**Comment by faho** [comment]
>One is easy to replicate - if PATH is empty before fish_add_path, then it will remain empty:

Not *empty*, _undefined_.

You've entirely erased $PATH, so when `fish_add_path` does `set PATH`, that sets it in the default scope, which is *local*. We should make it default to global here.

However: You shouldn't erase $PATH. $PATH should typically be set by the system, and if that doesn't work fish tries to give you a fallback so you don't end up with a broken system.

**Comment by acook** [comment]
Ah, that makes sense re "undefined" and "scope". Thanks for the quick fix!
