### ISSUE TITLE
Allow parenthesis to group commands instead of begin/end blocks

### ISSUE THREAD

**Issue by krobelus** [fish-shell/fish-shell#8083]
I'm not sure if this dilutes the fish language too much. I think it fits in okay.
As a programmer, I feel that `begin`/`end` are a bit awkward, especially for interactive use.

So what if instead of

```fish
$ cmd || begin; echo "error: $status"; exit 1; end
```

we could write

```fish
$ cmd || (echo "error: $status"; exit 1)
```

To implement this, we'd simply need to treat a command substitution as begin/end group **if** it is in command position.

POSIX subshells use the same syntax, but here it's just a command grouping (no external process). This might cause confusion.

**Comment by zanchey** [comment]
> POSIX subshells use the same syntax, but here it's just a command grouping (no external process). This might cause confusion.

Yes, I agree. I also think the collision with command substitution syntax is a problem. I wonder about using a different grouping character? Braces and brackets already have meaning within the fish syntax, unfortunately.

**Comment by kopischke** [comment]
I totally agree with @zanchey the collision with existing fish syntax is a problem. Overloading parens with grouping functionality in command position sounds neat, but it essentially leverages a non-feature (currently, fish does not accept command substitutions in command position). Doing that would preclude fish from ever changing this rule by allowing commands substitutions in command position. That might not be on the table ATM, but I’d be wary of welding this particular door shut – after all, fish originally didn’t support variable substitution in command position, either.

Also, overloading an operator depending on context is a lot of cognitive load for your average user: “parens mean command substitution, but they can’t be used as a command” is still much easier to grok than “parens mean command substitution, except when used as a command – then they group other commands“ (insert obligatory trademarked Consistency Bugbear Dance sequence here).

**Comment by krobelus** [comment]
Right, it feels like a bad idea to do this because people will expect the bash behavior for command substitutions in command position.

**Comment by faho** [comment]
Tbh I don't like this.

If we started fish from scratch I'd probably argue for `{}` blocks *everywhere* (so `if { conditionA; conditionB } { trueA; trueB } else { elseA; elseB}`), but since we're not it doesn't seem feasible.

**Comment by zanchey** [comment]
Sounds like a consensus on "no", then?

**Comment by krobelus** [comment]
So there are two possible behaviors for `(foo; bar)`

1. Grouping, like `begin .. end`
2. Evaluate the command substitution, and execute the resulting string

Since we now have the optional dollar for cmdsubs, what about making
`(foo; bar)` do grouping, and
`$(foo; bar)` can have the bash semantics

The behavior is subtle but it's not too bad, and Bash has pretty much the same semantics (except that a command like `echo (foo; bar)` doesn't make sense in Bash).

Given that I personally need 1 *much* more often then 2 I feel like this is still worth considering.

**Comment by gruvw** [comment]
Still no plans to support a new syntax for command grouping ?

**Comment by zanchey** [comment]
It doesn't look like it.
