### ISSUE TITLE
Document how to enable VI-Mode

### ISSUE THREAD

**Issue by hoijui** [fish-shell/fish-shell#8084]
In this place (blame view):
https://github.com/fish-shell/fish-shell/blame/master/doc_src/interactive.rst#L348

or say, here (rendered view):
https://github.com/fish-shell/fish-shell/blob/master/doc_src/interactive.rst#vi-mode-commands

I personally would want to see how to enable vi-mode, as the very first thing,
like here:
https://stackoverflow.com/a/28445450/586229

I would make a PR, if there are no objections or better ideas.

**Comment by faho** [comment]
It's in https://github.com/fish-shell/fish-shell/blob/master/doc_src/interactive.rst#command-line-editor

**Comment by kidonng** [comment]
@hoijui Please revert the changes you made on [the Stack Oveflow answer](https://stackoverflow.com/posts/28445450/revisions) (I don't have a StackExchange account). `~/.config/fish/config.fish` is [the prefered file to define your own config](https://fishshell.com/docs/current/faq.html?highlight=config%20fish#how-do-i-run-a-command-every-login-what-s-fish-s-equivalent-to-bashrc-or-profile), and it's not for something like "certain older systems".

If you want to add something new, add a link to [`$fish_key_bindings`](https://fishshell.com/docs/current/index.html?highlight=fish_key_bindings#command-line-editor) would be helpful.

**Comment by hoijui** [comment]
I reverted it, thanks.
the link you @kidonng  gave (as well as @faho ) ...

After reading it 4 times, I found it there.
For someone fro mthe outside, like me, we await .. a whole section, or at least a paragraph about how to enable it. having it in one sentence in the middle of a paragraph, and then a code block that explains how to do a special thing (vi + emacs), but no code block that shows how to enable it.. that is strange, and it's why I did not find it.

**Comment by kidonng** [comment]
If you want something straight and simple, `set -U fish_key_bindings fish_vi_key_bindings` would do it. But I feel it's too much magic happening.

There are more documentation on this topic: https://fishshell.com/docs/current/cmds/bind.html?highlight=fish_key_bindings#examples

> Turn on Vi key bindings and rebind Control+C to clear the input line:

> set -g fish_key_bindings fish_vi_key_bindings
> bind -M insert \cc kill-whole-line repaint
