### ISSUE TITLE
Remove the .exe suffix for executable completion on cygwin

### ISSUE THREAD

**Issue by account-login** [fish-shell/fish-shell#8085]
It just looks weird to execute commands with `.exe` suffix in a unix-like shell. So I patched fish to remove the `.exe` suffix from completion results. (Commit https://github.com/account-login/fish-shell/commit/0f54e36b145651b1474ae2ff4e327d3b258c599a in my fork)

What do you think about this?

**Comment by faho** [comment]
As far as I know, we don't *execute* files without the .exe suffix even on cygwin. I'm pretty sure we don't on WSL. Or am I wrong there?

**Comment by account-login** [comment]
Oops, I have just tried WSL and it indeed requires the .exe suffix (haven't tried WSL before). So this issue only applies to cygwin. Unlike WSL, executables on cygwin can be executed/accessed without the suffix. The problem is that tab completion offers something like `find.exe` or `lsattr.exe`, this not only looks weird but also stops tab completion from working if one tries something like 'find.exe -<tab>'.

**Comment by mqudsi** [comment]
Even on cygwin, this may be incorrect because Windows gives priority to a PATHed `.com` over a local `.exe`. In the case of a base name conflict, the wrong one will be launched.

**Comment by zanchey** [comment]
Looks like this would be unwise.
