### ISSUE TITLE
Doesn't build when using netbsd curses on Linux

### ISSUE THREAD

**Issue by ericonr** [fish-shell/fish-shell#8087]
fish 3.3.0

I wanted to build fish locally, but had forgotten I had https://github.com/sabotage-linux/netbsd-curses installed instead of ncurses. It failed to build because 

```
/// Under curses, tputs expects an int (*func)(char) as its last parameter, but in ncurses, tputs
/// expects a int (*func)(int) as its last parameter. tputs_arg_t is defined to always be what tputs
/// expects. Hopefully.
#if !defined(NCURSES_VERSION) || defined(__NetBSD__)
typedef int tputs_arg_t;
#else
typedef char tputs_arg_t;
#endif
```

doesn't cover this specific use case. Ideally it would be possible to run a proper test in CMakeLists and use the result of that? Not urgent, it's easy to fix locally, but still a build bug.

**Comment by ericonr** [comment]
Fixing this is not enough for it to build; this setup also confuses `FindPackage(Curses)` and fish's `pkg_config` fallback isn't 100% correct.

**Comment by faho** [comment]
If it confuses `FindPackage(Curses)`, it looks like it would have to be improved there.

**Comment by ericonr** [comment]
No worries, this is mostly a documentation issue. If I can come up with a clean fix, I will open a PR; in the meantime I just ripped some stuff out.

**Comment by ericonr** [comment]
> The FindPackage(Curses) bit would of course have to be improved in cmake (or whatever else provides that).

Using `pkgconfig` first instead of as a fallback would be almost enough, it's CMake's weird logic in FindCurses that gets things wrong.

**Comment by mqudsi** [comment]
CMake's weird `FindCurses` implementation has caused us lots of grief. We don't run on any platforms where `pkgconfig` isn't a thing; personally, if you want to open a PR that fixes the netbsd curses problem and happens to change `FindCurses` to a fallback for `pkgconfig` rather than the other way around, I would happy to review it.

**Comment by alarixnia** [comment]
NetBSD doesn't provide pkgconfig files for libcurses. That appears to be something the Linux port added... It should be easy to detect ncurses because it defines `NCURSES_VERSION_MAJOR` etc.

**Comment by faho** [comment]
>It should be easy to detect ncurses because it defines NCURSES_VERSION_MAJOR etc.

@alarixnia I'm assuming you mean we should replace the curses-related `__NetBSD__` checks with `NCURSES_VERSION_MAJOR` checks?

I'm not sure if that would work, given we do

```c++
#if !defined(NCURSES_VERSION) || defined(__NetBSD__)
```

here. So unless my brain is refusing to logic again (not an impossibility, it does that sometimes), that should already be taken on NetBSD *and on systems without ncurses*. 

Or is this specifically about NCURSES_VERSION_**MAJOR**?

**Comment by alarixnia** [comment]
@faho Hm, honestly I just scanned ncurses.h to look for something that would uniquely identify it as ncurses. But now I realize the problem is more complicated...

The problematic function is clearly a terminfo function, and I guess terminfo is usually provided by ncurses on non-NetBSD systems, but NetBSD libterminfo is still used on NetBSD if you're using ncurses. Is the Linux port of NetBSD libcurses not using NetBSD libterminfo (that seems like a mistake), or is NCURSES_VERSION being defined somehow (also a mistake)?

**Comment by faho** [comment]
This appears [ŧo have its own tputs](https://github.com/sabotage-linux/netbsd-curses/blob/master/libterminfo/tputs.c) and I can't find an NCURSES_VERSION define anywhere.

There is https://github.com/sabotage-linux/netbsd-curses/issues/43, which explains that libterminfo is still separate, so it appears our curses-finding magic finds ncurses terminfo and NetBSD curses.

Which, uh, yeah, that's... not gonna work, is it?

Using pkg-config *if possible* and falling back to FindCurses would probably fix even that, tho.

**Comment by ericonr** [comment]
> There is sabotage-linux/netbsd-curses#43, which explains that libterminfo is still separate, so it appears our curses-finding magic finds ncurses terminfo and NetBSD curses.

That isn't the case *here*. I have only netbsd-curses headers.

**Comment by faho** [comment]
>That isn't the case here. I have only netbsd-curses headers.

Then where/why is NCURSES_VERSION defined?

**Comment by faho** [comment]
Okay, I don't see how this fails to build.

Either you have ncurses, and NCURSES_VERSION is defined, so it picks the datatype that's correct for ncurses,

or you don't have ncurses, and NCURSES_VERSION is not defined, so it picks the datatype that's appropriate for NetBSD-curses - [including the linux port](https://github.com/sabotage-linux/netbsd-curses/blob/5874f9b1ced9c29d7d590d95e254b252f657a160/libterminfo/tputs.c#L162-L164).

If NCURSES_VERSION is defined, then you probably also have ncurses installed and cmake picks it up partially (or you defined it yourself and that's the issue).

Either way, I would quite like to have at the very least the actual compiler error, and ideally some reproduction steps.

**Comment by ericonr** [comment]
The issue here is that NetBSD uses the same prototype as ncurses, but netbsd-curses on Linux doesn't define `__NetBSD__`. So we fallback to the `char` definition, which is wrong. Without applying my changes:

```
/home/ericonr/mypro/fish-shell/src/output.cpp: In member function 'int outputter_t::term_puts(const char*, int)':
/home/ericonr/mypro/fish-shell/src/output.cpp:308:54: error: invalid conversion from 'int (*)(tputs_arg_t)' {aka 'int (*)(char)'} to 'int (*)(int)' [-fpermissive]
  308 |     int res = tputs(const_cast<char *>(str), affcnt, tputs_writer);
      |                                                      ^~~~~~~~~~~~
      |                                                      |
      |                                                      int (*)(tputs_arg_t) {aka int (*)(char)}
In file included from /usr/include/term.h:2002,
                 from /home/ericonr/mypro/fish-shell/src/output.cpp:16:
/usr/include/termcap.h:40:31: note:   initializing argument 3 of 'int tputs(const char*, int, int (*)(int))'
   40 | int  tputs(const char *, int, int (*)(int));
      |                               ^~~~~~~~~~~~
[42/105] Building CXX object CMakeFiles/fishlib.dir/src/parse_execution.cpp.o
ninja: build stopped: subcommand failed.
```

**Comment by faho** [comment]
>The issue here is that NetBSD uses the same prototype as ncurses, but netbsd-curses on Linux doesn't define __NetBSD__.

But the condition isn't just about __NetBSD__!

What about the first half?

```c++
#if !defined(NCURSES_VERSION) || defined(__NetBSD__)
```

Unless I am grossly misunderstanding this, this branch should *also* be taken if NCURSES_VERSION isn't defined. Which, since you've been swearing that you don't *have* ncurses*, should be the case here?

Can you just check if you have NCURSES_VERSION defined?

**Comment by faho** [comment]
Did you, uh, edit that code snippet? Because looking at the actual code it says:

https://github.com/fish-shell/fish-shell/blob/5a685c16c59d6a6382e655bdc94409ebf405f431/src/fallback.h#L56

So I have no idea who even uses `char` here?

**Comment by faho** [comment]
Ah, our old friend, OpenIndiana/Solaris/Illumos uses char. Blergh, let's just try_compile the pain away.

**Comment by ericonr** [comment]
> Did you, uh, edit that code snippet? Because looking at the actual code it says:

Shoot, sorry! I edited it like that to compile successfully locally for me, didn't realize I had pasted the edited version here. Thanks!
