### ISSUE TITLE
commandline -f repaint not responding to function handlers

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#8088]
`fish, version 3.3.0-2-g210dda2c4`

This is a regression from 3.2.2. Tested on Arch Linux and macOS.

```fish
function fish_prompt
    echo $PWD $foo
end

function on_foo --on-variable foo
    commandline -f repaint
end
```

The prompt will not update automatically, but pressing any key will update it.

https://user-images.githubusercontent.com/6318351/123681237-6d478200-d7fe-11eb-9b96-366eb0c28c50.mp4

The issue must be with repainting and not `--on-variable`, because this works:

```fish
function on_foo --on-variable foo
    echo $foo
end
```

https://user-images.githubusercontent.com/6318351/123681259-733d6300-d7fe-11eb-8b49-fd970f88454f.mp4

**Comment by douglascamata** [comment]
The "up key acting weirdly" part of this issue is very dangerous 😬

**Comment by krobelus** [comment]
Mea culpa, thanks for reporting! There should be a patch release with a fix soon.

**Comment by IlanCosman** [comment]
Can confirm this bug has been fixed on master.

> Mea culpa, thanks for reporting! There should be a patch release with a fix soon.

Haha, no worries, it's a niche use case that I should have been actively monitoring before the release.

Thank you for the quick fix @krobelus 😄

**Comment by freezlite** [comment]
Issue created 8 days ago, also it has up key bug so this is critical, could you please speed up release fix ?

**Comment by kidonng** [comment]
[It is reported](https://github.com/IlanCosman/tide/issues/171#issuecomment-880387567) that the offending commit is not fully reverted and there are still similar issues for some users.

@krobelus could you please investigate it?
