### ISSUE TITLE
alias of multiple fish shell commands isn't working in kitty terminal

### ISSUE THREAD

**Issue by backermanbd** [fish-shell/fish-shell#8098]
I am using fish 3.1.0 in kitty terminal 0.15.0

Fish shell alias
`alias contest='mkdir contest-(date +"%d-%m-%Y") && cd contest-(date +"%d-%m-%Y")'`

When I run `contest` alias in my `~/Documents/contests/` directory,
certain folder with name is created but the next command `cd contest-(date +"%d-%m-%Y")` doesn't work.

PS: writing the two commands manually in terminal works fine

whereas for bash shell alias (same as fish shell)
just added `$` before date.
it works perfectly
`alias contest='mkdir contest-$(date +"%d-%m-%Y") && cd contest-$(date +"%d-%m-%Y")'`

**Comment by faho** [comment]
>I am using fish 3.1.0 in kitty terminal 0.15.0

Please upgrade, this has been fixed since. You are four releases out of date.

Also... make an actual function. `alias` is a hack meant for very simple things.

**Comment by backermanbd** [comment]
@faho I am not that much experienced. Can you please make the alias into function?
`alias contest="mkdir contest-(date +"%d-%m-%Y") && cd contest-(date +"%d-%m-%Y")"`

**Comment by faho** [comment]
```fish
function contest
   set -l date (date +"%d-%m-%Y")
   mkdir contest-$date && cd contest-$date
end
```
