### ISSUE TITLE
Leading space to ignore command in history is not working

### ISSUE THREAD

**Issue by dideler** [fish-shell/fish-shell#8099]
Typed commands (i.e. not a pasted command) with a leading space appear in up-arrow history.
Only seems to affect up-arrow history; these commands do not appear in `history search` as expected.

This is causing sensitive information to be easily retrievable, a security vulnerability.

---

Fish version 3.3.0
iTerm2 build 3.4.8
macOS BigSur 11.4 (20F71)

Was able to reproduce without 3rd party customisations loaded.

**Comment by zanchey** [comment]
This was a deliberate change - #1383.

(Duplicate of #8052)

**Comment by faho** [comment]
To be clear, it's only kept in memory until the next command. It's not stored on disk.

This is because it's a bit silly that you can't go back to your last command to e.g. correct it.

**Comment by dideler** [comment]
Thanks for the clarification. It helps that it's not stored on disk. I'm still concerned of it being easily accessible in memory via the up-arrow key. My normal steps when working with a sensitive command would be to prefix it with a space and immediately clear the buffer (with cmd+k in iTerm2). I'm not sure how I should change my workflow now. Commit 9fdc4f903b8b421b18389a0f290d72cc88c128bb says that typing a space and hitting return should clear the sensitive command but it doesn't. I guess I could enter a comment without space as, `#`, after sensitive commands. Feels awkward but it works.

**Comment by faho** [comment]
Think of the threat model here.

To have someone get to your command, you would have to:

1. Execute a sensitive command (while thinking to prepend a space!)
2. Walk away from your computer (without locking it!)
3. Have someone walk up (who didn't already see your command shoulder-surfing!)

Even if you did all that, even without this fish feature, they would *still* see your command in the terminal scrollback!

So you would execute `clear` to remove that (ncurses' `clear` in TERM=xterm clears the scrollback), and once you do that the command is *also* gone in fish.

So: As long as you either do something else after your sensitive command, lock your machine, don't have anyone near *or* run `clear`, you are in the clear.

And if you don't do *any* of that you'd be screwed even if fish forgot your command.

**Comment by faho** [comment]
Okay, question has been answered, closing!

**Comment by dideler** [comment]
I think the threat model for exposing sensitive data is more severe if you consider intimate threats, e.g. a common attack by domestic partners and close ones. I'll personally try to adapt my workflow to remember to run another command (which includes `clear`) or closing the shell instance after running sensitive (space-prefixed) commands. 👍

**Comment by faho** [comment]
Sorry, the "threat model" is so obtuse as to be non-existent.

This requires such a weird mix of extremely hypervigilant and careless that it's just not worth bothering.
