### ISSUE TITLE
Windows version

### ISSUE THREAD

**Issue by OscarRyz** [fish-shell/fish-shell#810]
I know this may sound crazy but I really would like to use fish-shell in windows.

I work around right now by using git-bash instead of cmd which is fairly good, but after trying fish-shell in my Mac, I'm very frustrated of not being able to use it on windows too.

Why do I have to use Windows? That's a different question.

**Comment by zanchey** [comment]
I think Microsoft is coming to the party on this one with Bash on Ubuntu on Windows...

**Comment by jhasse** [comment]
Fish now also works pretty good with [MSYS2](https://msys2.github.io/) and can be installed with:

```sh
pacman -S fish
```

Can this issue be closed?

**Comment by faho** [comment]
Yes, closing.
