### ISSUE TITLE
Vi mode indicator not updating on ctrl-c when in default mode

### ISSUE THREAD

**Issue by SpikeTheMarmot** [fish-shell/fish-shell#8103]
```console
$ fish --version
fish, version 3.2.2
$ echo $version
3.2.2
$ lsb_release -d
Description:	Arch Linux
$ uname -a
Linux marmot 5.12.13-arch1-2 #1 SMP PREEMPT Fri, 25 Jun 2021 22:56:51 +0000 x86_64 GNU/Linux
$ echo $TERM
xterm-kitty
```

Hey, I just enabled vi-mode for the first time and stumbled upon this little bug with the mode indicator.

If you are in normal/default mode and cancel the current input with ctrl-c the shell prints a new prompt in the next line as expected but does not update the mode indicator.
As far as I can tell this also happens in the newest version and I am pretty sure the problem is a missing `repaint-mode` in the following line:
https://github.com/fish-shell/fish-shell/blob/768a9b1fd391fd52dfe29269a5bad6a292b38038/share/functions/fish_vi_key_bindings.fish#L78
After changing the line to
```fish
bind -s --preset -m insert \cc cancel-commandline repaint-mode
```
the mode indicator behaves as expected.

**Comment by zanchey** [comment]
Nice find! I can reproduce in 3.3.0.
