### ISSUE TITLE
type command takes x100 than it takes using root or bash, rendering tools unusable due to lag

### ISSUE THREAD

**Issue by sinapis** [fish-shell/fish-shell#8109]
executing `type gawk` takes around 50ms.
![image](https://user-images.githubusercontent.com/15230040/124364662-99726100-dc4b-11eb-8823-59255a07747a.png)

Using bash, I get around 0.5 ms:
```
./measure_time.sh type gawk
gawk is /usr/bin/gawk
.000673 seconds
```

This is the script I used to measure time on bash:
```bash
#!/bin/sh
start_time=$(date +%s.%6N)
$*
end_time=$(date +%s.%6N)

elapsed=$(echo "scale=6; $end_time - $start_time" | bc)
echo $elapsed seconds
```

Note:
When I use root, the performance problem is gone:
![image](https://user-images.githubusercontent.com/15230040/124364774-5e246200-dc4c-11eb-8698-2349beb1d039.png)

This problem is not specific to gawk, i tried awk, cat and other executables. All encounter the same performance issue.
Built ins such as ls, type or functions, do not suffer from this performance problem.

This is not a theoretical issue. I care about this because there are tools that extensively use `type -q` to check if a command exists, and doing it for several commands, resulting in very poor and noticeable lag that renders them unusable. For example see this issue: https://github.com/b4b4r07/enhancd/issues/157

system info:
fish version: 3.3.0
ubuntu 20.04
using wsl2 on windows kernel 4.19.84
Windows Terminal 1.8.1521.0

**Comment by faho** [comment]
Please check your $PATH.

In particular:

```fish
set -S PATH fish_user_paths
```

Most likely you have a massive $PATH because you append to the (universal) $fish_user_paths in config.fish.

Either that, or you've kept the old `type` function.

Check `type type`.

**Comment by sinapis** [comment]
That was it!
My PATH had some windows paths in it. Apparently, the default WSL behavior is to append Windows PATH into Linux.
That can be disabled by creating /etc/wsl.conf file and putting inside:
```
[interop]
appendWindowsPath=false # append Windows path to $PATH variable; default is true
```
Taken from this [SO answer](https://stackoverflow.com/a/51345880/987801)

Once I did that, performance was perfect:
![image](https://user-images.githubusercontent.com/15230040/124365876-aabf6b80-dc53-11eb-9baa-b4f2eae05b9a.png)

Thanks a bunch!!!
