### ISSUE TITLE
Being able to define a description for function generated via alias

### ISSUE THREAD

**Issue by morozov** [fish-shell/fish-shell#8112]
When a function is auto-generated via an alias, its description is auto-generated from the underlying command. In a certain case, I want to auto-generate a few aliases and as their user, I don't really care what their implementation is, I want to see what they do.

See this [article](https://localheinz.com/blog/2020/05/05/switching-between-php-versions-when-using-homebrew/) for example. The author defines aliases `7.1`,  `7.2`,  `7.3`... to switch between PHP versions. When I type `7` and `<TAB>`, I'd like to see descriptions like "Switch to PHP 7.1",  "Switch to PHP 7.2", etc. But I see the internal commands instead.

Instead of using aliases, I can declare the functions manually like:
```shell
function 7.1 --description="Switch to PHP 7.1"
   # code
end
```
But unlike aliases, these functions are harder to generate dynamically (which is what `alias` does).

The proposal is to add the support for the `--description` switch to the `alias` function. E.g.:
```shell
alias 7.1="...code" --description="Switch to PHP 7.1"
```

**Comment by faho** [comment]
Make a function. Alias is a compatibility hack for simple cases.

**Comment by morozov** [comment]
Thanks for the recommendation, @faho. Apparently, generating functions dynamically isn't as hard as I thought. I ended up doing something like:
```shell
function __php_get_versions
    # will return 7.1, 7.2 and so on
end

function __php_register_alias --argument v
    set -l description (string escape -- "Use PHP $v")

    echo "function $v --description $description; __php_switch $v; end" | source
end

for v in (__php_get_versions)
    __php_register_alias $v
end
```
> In this case, the actual solution I would go for would be one function with arguments

Well, the whole challenge was about generating an alias per PHP version, not having a single function that switches between them. Anyways, the problem has been solved.

**Comment by faho** [comment]
You don't even need the `source` at all, just use `--inherit-variable`:


```fish
for v in (__php_get_versions)
    function $v --inherit-variable v
        __php_switch $v
    end
end
```

**Comment by morozov** [comment]
Thanks! That's even better.
