### ISSUE TITLE
After upgrading Fish 3.3.0 my prompt has git & hg errors

### ISSUE THREAD

**Issue by jsatk** [fish-shell/fish-shell#8119]
fish 3.3.0
macOS 11.4

My prompt looks like this now after upgrading.

<img width="562" alt="image" src="https://user-images.githubusercontent.com/1005550/124525611-be361800-ddb4-11eb-99af-963b3394a3df.png">

When I run `sh -c 'env HOME=$(mktemp -d) fish'` the problem no longer shows up.

No idea why.

**Comment by jsatk** [comment]
I was able to resolve this by running the following:

```
$ rm ~/.config/fish/functions/fish_prompt.fish
$ fish_config prompt choose arrow
```

Not sure what the issue was. But blowing it away and resetting it fixed it. 🤷

**Comment by faho** [comment]
The issue was that you still had a `^` redirection somewhere. These were deprecated in fish 3.0, we've now turned them off by default.

**Comment by jsatk** [comment]
> The issue was that you still had a `^` redirection somewhere. These were deprecated in fish 3.0, we've now turned them off by default.

Thanks for clarifying. I used a default prompt that came with `fish_config`. The "arrow" one. Simply selecting it again fixed the issue. It would be nice if there was a way to warn folks using older default prompts from fish 1 or 2 days that they need to re-set their prompt.
