### ISSUE TITLE
Exporting array variable results in single variable when used in bash script

### ISSUE THREAD

**Issue by vakokako** [fish-shell/fish-shell#8120]
> fish, version 3.2.2
```
set -lx OptArray a b c
```
bash script:
```
#!/usr/bin/env bash
echo "count : ${#OptArray[@]}"
```
result:
```
count : 1
```

**Comment by zanchey** [comment]
Yes. Unfortunately, fish arrays cannot be exported (and are joined with spaces when exported). This is a problem in all shells.

See https://stackoverflow.com/questions/5564418/exporting-an-array-in-bash-script - particularly "There isn't really a good way to encode an array variable into the environment."

**Comment by faho** [comment]
Yeah, unix semantics simply don't allow for arrays. Posix sh doesn't have them, and the environment can only take a null-terminated "string" (really just a bag of bytes without any embedded NULs).

So it's impossible to solve without deep changes to the OS, and for that I wouldn't hold my breath.

**Comment by ridiculousfish** [comment]
bash needs to solve this first - nothing fish can do. Closing.
