### ISSUE TITLE
Fish slow startup sometimes causes the first few characters to be ignored

### ISSUE THREAD

**Issue by IndianBoy42** [fish-shell/fish-shell#8124]
```
fish --version #3.3.1
```
PopOS 21.04

Part of this may be my fault but I wanted to ask. So I added `macchina` to the `fish_greeting` function, just to have some Eyecandy on startup. But the problem is, with this line, the startup is a bit longer (expected) but even worse the characters I type while starting up will be ignored (they are printed to the screen but not run). Without that command even though startup is not instant, if i type something before the prompt is painted it will still run that as a command. 

This is mostly a problem with things like the neoterm plugin that can run lines from a file in a repl in an terminal. It enters the command to open a REPL as soon as it starts the terminal but fish is still starting up so that command is ignored, and then it is't able to run any repl commands

Is this expected behaviour? Is there anything I can do to mitigate this problem?

**Comment by faho** [comment]
>Is this expected behaviour?

Yes. Before fish has finished startup, which includes printing the greeting, it can't read characters, because the reader hasn't been started yet.

> Is there anything I can do to mitigate this problem?

Make your startup faster or start typing later.

**Comment by IndianBoy42** [comment]
> Make your startup faster or start typing later.
Unfortunately I cannot tell neoterm to start typing later, it is a 'dumb' plugin that just enters characters into a terminal to run commands.

> Yes. Before fish has finished startup, which includes printing the greeting, it can't read characters, because the reader hasn't been started yet.

The interesting thing is that when I remove everything (one command) from `fish_greeting`, my startup is still slow because of my old laptop, but commands I type before the prompt is visible still get run, it will even expand the abbreviation. 

I suppose that is because the prompt is asynchronously populated (a notable feature of tide mentioned in their readme). I wonder if something similar is possible for `fish_greeting`

**Comment by faho** [comment]
The issue is that the command in the greeting could be reading from the terminal. We have no way of knowing that it isn't, so we can't start reading.

**Comment by IndianBoy42** [comment]
Ah I figured out a 'workaround' run the and in greeting '&'

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
