### ISSUE TITLE
fish's `help` does not respect default browser but `fish_config` does.

### ISSUE THREAD

**Issue by hbina** [fish-shell/fish-shell#8126]
Basic information,

```
hbina@komputa ~> fish --version
fish, version 3.1.0
hbina@komputa ~> echo $version
3.1.0
hbina@komputa ~> uname -a
Linux komputa 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
hbina@komputa ~> echo $TERM
xterm-256color
```

I literally just installed this from my Ubuntu apt.
See demonstration,

https://user-images.githubusercontent.com/6733660/125099769-f4ec9500-e10a-11eb-861b-e79f75a4140c.mp4

**Comment by faho** [comment]
Upgrade, this looks like #6739 (in case you are using wayland). Unfortunately Ubuntu's fish package is basically unmaintained, use [our PPA](https://launchpad.net/~fish-shell/+archive/ubuntu/release-3).

Other than that, `help` ends up calling `xdg-open`. If that doesn't respect your browser it's a bug there or in your system's configuration.

**Comment by hbina** [comment]
Yep, that fixes it! Thanks.
