### ISSUE TITLE
Feature request: build in path add and erase functions

### ISSUE THREAD

**Issue by dancojocaru2000** [fish-shell/fish-shell#8133]
After dealing with `$fish_user_paths` for some time, I got annoyed enough by it to write my own functions.

`path_add.fish`:
```fish
function path_add -d "Adds paths to fish_user_paths"
    for arg in $argv
        set -U fish_user_paths $arg $fish_user_paths
    end
end
```

`path_erase.fish`:
```fish
function path_erase -d "Remove an item from fish_user_paths"
    set -l idx 1
    for item in $fish_user_paths
        echo $idx"." $item
        set -l idx (math $idx + 1)
    end
    set -l to_remove (read -P "Index to remove? ")
    if [ \( $to_remove -ge 1 \) -a \( $to_remove -le (count $fish_user_paths) \) ]
        set -e -U fish_user_paths[$to_remove]
    else
        echo "Invalid index"
    end
end
```

Of course these may be naive implementations, but I think having a built in easier way to manipulate the path would be nice, especially since a lot of scripts only provide the bash way of doing it.

**Comment by kopischke** [comment]
You might want to check out [`fish_add_path`](https://fishshell.com/docs/current/cmds/fish_add_path.html), introduced with [fish 3.2](https://fishshell.com/docs/current/relnotes.html).

**Comment by dancojocaru2000** [comment]
Oh damn, I missed that one! Great I wasn't the only one who thought this is needed.
