### ISSUE TITLE
Error in documentation: aliases can't be autoloaded (version 3.1.0)

### ISSUE THREAD

**Issue by lolbinarycat** [fish-shell/fish-shell#8137]
I found this bit in the HTML documentation which seems to be just plain wrong

> Autoloading is not applicable to functions created by the alias command. For functions simple enough that you prefer to use the alias command to define them you'll need to put those commands in your ~/.config/fish/config.fish script or some other script run when the shell starts.

`funcsave` works fine with `alias`, and `alias --save` also exists.

**Comment by faho** [comment]
`funcsave` and `alias --save` save the *function*, after it has been created.

What this is talking about is that once `alias` has run, the function is *already loaded*. It could probably be worded better.

But, honestly, we really really really really want to put people off using alias to begin with.

**Comment by lolbinarycat** [comment]
> What this is talking about is that once alias has run, the function is already loaded. It could probably be worded better.

Is this not basically how all functions work? sure, you have to have an `end` statement, but that seems like a syntactic difference, not anything to do with autoloading. do you mean you can't (or shouldn't) put `alias` statements in autoloading files? 

also, `alias` is much simpler than the alternative. It also handles autocomplete wrapping, something many people are likely to forget if they do it by hand. It definitely shouldn't be used for some things, but just because there are times you shouldn't use something doesn't mean you should never use it.
