### ISSUE TITLE
stock completions/rm.fish calls custom rm.fish function

### ISSUE THREAD

**Issue by jsmitley** [fish-shell/fish-shell#8138]
fish, version 3.2.2
Darwin C02F40TEML87 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64

This only affects any version with a custom `rm` override function that does not handle the `--version` flag.

When I type `rm` and then attempt autocomplete the stock `completions/rm.fish` file attempts to run
`rm --version >/dev/null 2>/dev/null` to check the rm version being used. This ends up running the override `rm` function and throwing an error if that function has problems with the `--version` flag. I've worked around this by parsing out `--version` of $argv, but I believe changing the check in the stock `completions/rm.fish` function to `command rm --version >/dev/null 2>/dev/null` is a better solution.

**Comment by faho** [comment]
If you call something by a known name, it should be compatible.

Sorry, there is no good way around that. We have no way of knowing whether an `rm` function is compatible enough for the completions to make sense (or for any particular *call* to it in other functions to make sense!), so we can only assume.

Just not accepting `--version` (even by erroring out!) is awkward, but imagine if someone wrote an `rm` function that did `cp` instead.

And using `command $thing` everywhere would 

1. break for compatible functions.
2. be super annoying

So: Please rename your function or write your own `rm` completions for your own `rm`.
