### ISSUE TITLE
Issue with screen, Ctrl-s, and fish

### ISSUE THREAD

**Issue by d5ve** [fish-shell/fish-shell#814]
I use Ctrl-s as my GNU screen escape key, rather than the default Ctrl-a. This doesn't seem to work when I use fish (2.0 or master) as my shell. 

Nothing at all happens when I press Ctrl-s, and whatever I type next just appears in the terminal. For example the screen command to create a new window is "Ctrl-s c", but this just prints the "c" into the terminal.

Under bash I did have to turn off terminal flow control with "stty -ixon" to use Ctrl-s, but this setting doesn't seem to change anything under fish.

**Comment by trulyliu** [comment]
I swtiched from bash to fish on ubuntu 16.04 recently, 
CTRL-S and CTRL-Q does not work as before.
Are there any configuration can be used to flow control on?

**Comment by faho** [comment]
@trulyliu: Fish disables flow control, i.e. that feature. There currently is no configuration option to reenable it.

If you wish to propose a way to change that, #2315 should be the correct issue to do that.
