### ISSUE TITLE
git show -p <TAB> -> strange help

### ISSUE THREAD

**Issue by pawlosck** [fish-shell/fish-shell#8140]
fish, version 3.3.1

git show -p <TAB>
-pa                                                          (Treat all files as text)  -pM                                                 (Detect and report renames)
and more

You can write -pre and fish show you something like that -> "-prea" or "-preM"

**Comment by krobelus** [comment]
I guess instead of

	-pa	(Treat all files as text)

we should render 

	a	(Treat all files as text)

in this case?

**Comment by pawlosck** [comment]
No. When i write -p, fish should show help for option/s started with "-p" or no help when there is no this option.
I checked now and similar problems are in other commands, for example. "ls -1"

**Comment by faho** [comment]
>

No. When i write -p, fish should show help for option/s started with "-p"

It does. `-p` signifies a short option, and short options can be grouped. `-pa` is the same as `-p -a`.

If you used `--p` it would show `--patch-with-raw` and `--patch-with-text`.

This is working correctly.

**Comment by faho** [comment]
Okay, question has been answered, closing!
