### ISSUE TITLE
`ls` broken in fish 3.2.1 after package updates, before process restart

### ISSUE THREAD

**Issue by DamonBlais** [fish-shell/fish-shell#8144]
Here we go again, Fish doesn't seem to like Fedora 34, or vice-versa.

After using the system for 19 days (as you do, Linux system don't need to reboot to install software updates, and with KernelCare I don't need to reboot to apply kernel patches either so...)

I digress, I went to go back to programming and this happened:

```
/usr/share/fish/functions/ls.fish (line 55): The expanded command was empty.
    command $__fish_ls_command $__fish_ls_color_opt $argv
    ^
in function 'ls' with arguments '.'
```

|Command|Output
|-|-
|`fish --version`|`fish, version 3.3.1`
|`uname -a`|`5.12.11-300.fc34.x86_64`
|`echo $version`|`3.2.1`
|`echo $TERM`|`screen`

In my case, doing an `exec fish` "fixed" the issue (as I went from 3.2.1 to 3.3.1) -- but I can't have this level of stability in my daily-driver system. Basic commands like `ls` stopping working randomly is sort of unacceptable.

Does `fish` not like being updated perhaps? (E.g.: Are the functions defined in files that get clobbered by package manager updates, but the process running can't read the new function definition files? If so, this means you made breaking changes in `3.2.1` to `3.3.1` in these function definition files...?)

Worth noting no amount of arguments passed to `ls` would work, but `dir` did, so I could still use my system somewhat.

**Comment by faho** [comment]
What happened here was you had an old fish running that loaded the new `ls` function, because you didn't have it loaded yet.

And because the `ls` function was changed to cache which ls it calls (so it can use `colorls`), that broke. That's basically unavoidable.

Our guidance on upgrade is to close all running fishes and start again. That's a necessity with autoloading.

>In my case, doing an exec fish "fixed" the issue (as I went from 3.2.1 to 3.3.1) -- but I can't have this level of stability in my daily-driver system. Basic commands like ls stopping working randomly is sort of unacceptable.

There's no need for this exaggeration. It's a minor error that can be fixed simply by restarting fish.

Also note that Fedora likes doing "offline" upgrades, only doing them after reboot. That entirely avoids this sort of situation and AFAIK the fish package is marked for it.

**Comment by DamonBlais** [comment]
I cannot agree with this decision and direction (long-running applications
are automatically bad and crashing them is acceptable) -- when this is how
servers inherently work... Imagine if your favourite websites had to go
down multiple times a day because seemingly arbitrarily package maintainers
and developers decided that applications no longer needed to survive
updates, and that systems should just "reboot to update."

In mission critical and business environments this is an unacceptable
solution.

Going forward I know not to rely on `fish` as a login shell, as it might
just "not work randomly" because my system updated, and I can't afford to
take it offline (or to not update it, as would leave it open to security
vulnerabilities.)

**Comment by DamonBlais** [comment]
Imagine if Apache HTTPd just "stopped working" after it was updated...

**Comment by faho** [comment]
>I need to do my system updates offline, with bash shell, then use fish?

Fedora has an "offline" updates system.

Either simply use that, or do the update and restart your fish sessions. There's no need to switch to bash, just update and restart.

>In mission critical and business environments this is an unacceptable

*Sigh*. You're being dramatic here. You got a minor error, there's no need to exaggerate.

**Comment by DamonBlais** [comment]
Yes, because this time it was `ls` that changed. If any internal command can change, and this change results in the command being uncallable, this could lead to many untold disaster.

One doesn't run `bash` and expect internal commands to just 'stop working'.

---

Offline Updates, after having read more about them, side-step `fish` **only if it is not** the default login / system shell, (in which case, even recovery consoles and other vTTy end up using `fish`, which could lead to a huge mess given this direction.)

Although the solution to that is marked in #8078 (don't make fish your default login / system shell, it's not worth the "breaking the system".)

---

It's entirely fair though, as this is your project, it is entirely up to you on what is expected and supported behaviour out of your application. I would recommend signaling to distribution maintainers that your application requires "special execution" flags for installation, to fully embrace the "offline update" system you point at. This would defer the package update until the next reboot, as is described in the documentation for said feature.

Package maintainers must **opt into this feature** as hinted by developers.

**Comment by faho** [comment]
>Yes, because this time it was ls that changed. If any internal command can change, and this change results in the command being uncallable, this could lead to many untold disaster.

Any **function** can change. Builtins and external commands aren't autoloaded.

This was a rare occurence because we ship a default wrapper `ls` to colorize the output. `command ls`  was entirely unaffected.

Functions, for the most part, are either prompt things (that will already be loaded) or helpers for completions and such. Nothing "critical".

>You're correct. One must be dramatic by default when seconds of downtime costs millions of dollars. Open Source seems to repeatedly misunderstand this concept of mission critical or Enterprise workloads.

Okay, I've had enough of this. Locking.
