### ISSUE TITLE
Questions about `complete --description`

### ISSUE THREAD

**Issue by kidonng** [fish-shell/fish-shell#8146]
fish --version: 3.3.1

Searching for "completion description" in the issue list gives me 200+ results so pardon me for giving up and open a new issue despite there might be duplicates.

---

Recently I have been making some completion scripts and noticed some limits (or perhaps, issues) with `complete --description`:

- If a completion command has both a short flag (`--short`) and a long flag (`--long`) provided but no description, they are not grouped together:

  ```
  $ cat cat.fish 
  complete cat -s a -l foo
  complete cat -s b -l bar
  $ cat -a[press Tab]
  -a  -b  --bar  --foo
  ```

  Edit: technically, as long as there are more than one `--short` or `--long` flag, this happens.

- If more than one completion commands have the same description, they are merged into one:

  ```
  $ cat cat.fish 
  complete cat -s a -l foo -d "test"
  complete cat -s b -l bar -d "test"
  $ cat -a[press Tab]
  -a  -b  --bar  --foo  (test)
  ```

These behaviors are, AFAIK, not documented somewhere. I would like to know the reason behind them and whether they are going to be changed or stay as-is.

**Comment by faho** [comment]
The problem here is that `complete` has no memory of which options were added at the same time, so this just groups them based on the description.

It *doesn't* do that for the empty description because that's the default.

Changing this would be a bit of work and I don't think it's a problem in practice - when the description is the same, the options either do the same thing (like short/long forms of the same option) or the description doesn't describe what they do and should be fixed.

**Comment by faho** [comment]
This is implemented [in the pager](https://github.com/fish-shell/fish-shell/blob/f345464879eeefbcd1486fee1d5f520f06869fee/src/pager.cpp#L273-L300).

**Comment by kidonng** [comment]
> The problem here is that `complete` has no memory of which options were added at the same time, so this just groups them based on the description.

That's clever! So `complete --short --long` actually creates two completions at the same time, right?

> Changing this would be a bit of work and I don't think it's a problem in practice - when the description is the same, the options either do the same thing (like short/long forms of the same option) or the description doesn't describe what they do and should be fixed.

Well when writing the issue I guessed the second case is more or less trying to be smart and personally I don't write completions that way *myself*, I discovered it when I was improving someone else's completions. 

But I'd still like a solution to the first case. Most of the time the lacking of descriptions is simply because no one cares to write, and sometimes the option is just plain obvious and I don't really feeling like writing one.

At the very least, I think the documentation should be updated to include the valuable info you have provided.

**Comment by faho** [comment]
>But I'd still like a solution to the first case. Most of the time the missing descriptions is simply because no one cares to write, and sometimes the option is just plain obvious and I don't really feel like adding one.

Sure, but if nobody bothered to write a description for two separate options?

Not grouping these just means you get two candidates and can pick one. Grouping them would mean being unable to pick one of them, which is *much* worse.

So I don't see a solution to this other than the massive pain of tracking the separate calls, and I also don't think that's necessarily correct either? At least it could trip up some completions if someone is currently adding options like

```fish
complete -c foo -l banana -l apple -l orange
```

**Comment by kidonng** [comment]
> So I don't see a solution to this other than the massive pain of tracking the separate calls, and I also don't think that's necessarily correct either? At least it could trip up some completions if someone is currently adding options like
> 
> ```fish
> complete -c foo -l banana -l apple -l orange
> ```

Fair enough. Mind I create a PR to document these nuances?

**Comment by faho** [comment]
This is the sort of thing where you don't need to ask, enhancements to the docs are pretty much always welcome, unless it's something we really want to keep flexible.

Since I missed that, I just took a stab at it myself because that's about the same hassle as telling you to do a PR, reviewing it and merging it.
