### ISSUE TITLE
cd "" crashes fish

### ISSUE THREAD

**Issue by ThePotatoChronicler** [fish-shell/fish-shell#8147]
Fish Version : 3.3.1
OS: Arch Linux, 5.12.15-arch1-1, x86_64 GNU/Linux
No 3rd party extensions

Steps to reproduce:
1. `cd ""`
2. That's it, fish crashes

![image](https://user-images.githubusercontent.com/45178972/126043849-526adccd-9d98-4e94-a98b-f9f3c0e494c2.png)
EDIT:
Proof that it happens without customization as well
![image](https://user-images.githubusercontent.com/45178972/126044258-76dca5b9-b55e-4cf4-a0a2-d9b45d58b39a.png)

**Comment by faho** [comment]
Hah, fun.

Broken in df53d1415d8fd6fa140cf9153c881c7db694435b.

**Comment by floam** [comment]
AFTER THROWING?

How?

**Comment by floam** [comment]
My understanding is on all platforms, we disable exceptions? Do we need to also `-fignore-exceptions`?

**Comment by faho** [comment]
We don't, it's simply bad phrasing.
