### ISSUE TITLE
How to append fish history to bash history after exit?

### ISSUE THREAD

**Issue by pvonmoradi** [fish-shell/fish-shell#8154]
Fish by default uses bash history (`~/.bash_history`) but it only appends to fish's own history file for commands run inside fish shell.  
As I use both shells, is it possible to sync bash history with fish history?

**Comment by faho** [comment]
It is not. There is no way to get just the history of that session, and fish deduplicates history already so that doesn't really *exist*. It's also not something we want to support because fish is not bash-compatible.
