### ISSUE TITLE
How do I consistently get my `fish_command_not_found` function invoked instead of the default handler?

### ISSUE THREAD

**Issue by rdw20170120** [fish-shell/fish-shell#8155]
When Fish encounters a nonexistent command, it reports (e.g., `fish: Unknown command: hello`) and continues executing.  This is typical shell behavior.  However, what I want to do is stop execution of the script at that point similar to what happens with Bash `set -e`.

I am new to Fish, but I am very impressed by its vastly improved behavior over Bash.  I am hoping that Fish can also do this well.  I just do not understand it well enough yet, or perhaps I am expecting it to do something that it cannot.

Here is what happens (in iTerm2 3.3.20210223 on Apple macOS 11.4 Big Sur).  I have no plugins or other Fish customizations.  I installed Fish from Homebrew, though I want to soon replace that with a better approach.
```
rob@Heka:~/repo/GitLab/WIP/private-mono$ fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
rob@Heka ~/r/G/W/private-mono (main)> fish --version
fish, version 3.3.1
rob@Heka ~/r/G/W/private-mono (main)> echo $version
3.3.1
rob@Heka ~/r/G/W/private-mono (main)> uname -a
Darwin Heka.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
rob@Heka ~/r/G/W/private-mono (main)> echo $TERM
xterm-256color
rob@Heka ~/r/G/W/private-mono (main)> hello
fish: Unknown command: hello
rob@Heka ~/r/G/W/private-mono (main) [127]> hello
fish: Unknown command: hello
rob@Heka ~/r/G/W/private-mono (main) [127]> . activate.fish
Running Fish as /usr/local/bin/fish
Executing /Users/rob/repo/GitLab/WIP/private-mono/activate.fish
Activated.
Hello, world!
Done.
rob@Heka ~/r/G/W/private-mono (main)> g0/image/Ubuntu/base/build.fish
Executing /Users/rob/repo/GitLab/WIP/private-mono/g0/image/Ubuntu/base/build.fish
Building this Docker image using Earthly
fish: Unknown command: nonexistent_command
g0/image/Ubuntu/base/build.fish (line 18):
    nonexistent_command
    ^
ERROR: Required value is absent
in function 'require_single_value' with arguments '""'
	called on line 19 of file g0/image/Ubuntu/base/build.fish
rob@Heka ~/r/G/W/private-mono (main) [98]> hello
ERROR: Command NOT found: hello
in function 'fish_command_not_found' with arguments 'hello'
in event handler: handler for generic event 'fish_command_not_found'
rob@Heka:~/repo/GitLab/WIP/private-mono$
```
Please notice that my first attempt to execute `hello` invokes the default command-not-found handler consistently.  I then `source` my `activate.fish` script (copied below) to configure Fish for this project.  That script `source`s my `fish_command_not_found`, then verifies that it is a defined function.

Invoking my script `g0/image/Ubuntu/base/build.fish` includes executing `nonexistent_command` (see source below), but that results in exercising the default command-not-found handler again **INSTEAD** of my own.

When I immediately follow this by attempting `hello` again, only **NOW** do I actually get my own command-not-found handler.

Please also notice that execution of my script continues **PAST** `nonexistent_command`, encountering the intentional error (`BO_DockerRepository` is undefined) on the following line that results in `ERROR: Required value is absent`.  I want my `fish_command_not_found` function to be invoked here, and I want its `exit` to prevent further execution.  My intention is to create safe scripts in which I either get the desired behavior or they fail fast.

Here is my `fish_command_not_found` in `fish_command_not_found.fish`:
```
function fish_command_not_found \
    --description 'Called by Fish when a command is not found'
    echo ERROR: Command NOT found: $argv[1]
    status --print-stack-trace
    exit 97
end
```
Here is `g0/image/Ubuntu/base/build.fish`.
```
#!/usr/bin/env fish

begin
    echo Executing (realpath (status filename))

    # Abort if not activated
    if not set -q BO_HomeProject ; echo NOT activated! ; exit 99 ; end

    # Redeclare path variables
    set -gx --path fish_function_path $fish_function_path

    require_argument_count (count $argv) 0
    echo Building this Docker image using Earthly
    change_directory (realpath (status dirname))
    nonexistent_command
    require_single_value "$BO_DockerRepository"

    # Irrelevant content elided for brevity

    echo Done.
end
```
And here is `activate.fish`.
```
#!/usr/bin/env cat

begin
    echo Running Fish as (status fish-path)
    echo Executing (realpath (status filename))

    # Abort if already activated
    if set -q BO_HomeProject ; echo Already activated! ; exit 99 ; end

    # Activate
    set -gx BO_HomeProject (realpath (status dirname))
    set -gx BO_Generation g0
    set -gx BO_DirGeneration $BO_HomeProject/$BO_Generation

    # Set fish_function_path
    set -gx --path fish_function_path $BO_DirGeneration/fish/functions $fish_function_path
    source $BO_DirGeneration/fish/functions/fish_command_not_found.fish
    if not functions -q fish_command_not_found
        echo "ERROR: function fish_command_not_found is NOT found"
        exit 98
    end

    # Irrelevant content elided for brevity

    echo Activated.

    hello_world
    echo Done.
end
```
So, please, what am I doing wrong?  My `fish_command_not_found` function is getting invoked eventually, but not when I expected.  Why does it **NOT** get invoked during the run of my script, but it does get invoked afterwards when I attempt a nonexistent command manually?  Is this some kind of timing issue, perhaps?

Thank you for your help.

**Comment by faho** [comment]
Ah, I see. What is happening here is that the command-not-found handler isn't used in non-interactive shells:

https://github.com/fish-shell/fish-shell/blob/c4773d40522e9e828f5b9d180ab15fc1bf975f5e/share/config.fish#L28-L34

I don't believe that's something we want to expose because it's not something command-not-found handlers are *meant* for. Their typical use is to show you the package for a missing command. If you really want it, you can pass it as `--init-command` or `source` it explicitly, like you are doing already.

What you are missing is this:

- There are multiple shells in play!

>rob@Heka ~/r/G/W/private-mono (main)> g0/image/Ubuntu/base/build.fish

Runs a new *fish* process, so that needs to `source` the file *again*.

Also, as a hint: Don't use that command-not-found handler in interactive shells. It'll quit your shell. Possibly put it into a "preamble.fish" that you source in all your scripts.

-------------------


But what you *actually* want is something like `set -o errexit`. That's tracked in #510.

Note that that's a tough one because the semantics are hard to get right (see the numerous times that bash has changed its behavior, and especially problems with `grep` and such returning non-zero without it being a fatal error). Truth be told I'm not entirely sure if the paradigm is worth it.

**Comment by rdw20170120** [comment]
Ah, I completely missed that command-not-found is only active for non-interactive shells.  Apparently I am trying to use it in a way very different from how it was intended.

I do not want Bash's `set -o errexit`, for exactly all the nightmares that #510 alludes.  What I do want is to specifically stop my scripts (both interactively and non) when they attempt to execute an unknown command (or function).  My intent is to make my scripts so solid that they never do that normally because I refine my scripts and their environment (using a DevOps/SRE approach) such that I know exactly what to expect.  I then test them thoroughly to ensure proper behavior.  So the only reason for an invalid command or function should be a typo or a mistake with the relevant search path.  I am attempting to achieve similar behavior with variables, directories, files, etc.  I have built all that in Bash, but it is a real challenge because of Bash's quirks.  I was beginning to rewrite it in Fish, which is MUCH easier and cleaner.

So, in your humble opinion, is there any appropriate way for my scripts to intercept a command-not-found such that my own Fish function can gain control, report the error, and exit the script--without the horrors of `set -o errexit`?  I think this should be an easily identifiable case (invalid command or function) that it can be handled well while not having to dive into the weeds of handling all possible error situations.  I just need to hook into the shell where it knows those details, because only the shell has the necessary information to distinguish this case from all the other possible error cases.

It also seems that I need to somehow hook into the Fish startup so that I can consistently configure each new Fish shell to reflect my desired behavior in each new instance invoked by running my various scripts.  Obviously I can do that in `config.fish`, but how would I do it specific to just my current project (within its `activate.fish`)?

I am beginning to conclude that I am simply asking too much of ANY shell.  I think that I may have reached the point where I need to jump to a full-service programming environment such as Python.

Thoughts?

**Comment by faho** [comment]
>So, in your humble opinion, is there any appropriate way for my scripts to intercept a command-not-found such that my own Fish function can gain control, report the error, and exit the script--without the horrors of set -o errexit?

Like I said: `source` it, in every script. Put a

```fish
source /path/to/preamble.fish
or exit
```

at the top. That's also where you'd define your helper functions, like `require_single_value` and such. The `or exit` is so your script errors out if it can't source the file.

That's really the only tenable way - personally I'm trying to get us away from even reading config.fish in non-interactive shells since it is weird global state.

Which I'm sure you appreciate, because that is one of the things that makes scripts behave differently across systems.

**Comment by rdw20170120** [comment]
Well said, @faho.

I really like the idea of skipping Fish configuration for non-interactive shells.  I second the motion.

I have always known that my deeper use cases would require something more substantial than a shell.  That is by design, since a shell is intended to be merely glue logic to connect the more-substantial pieces.

As a consequence, my previous Bash scripts relied upon `source`ing `activate.bash` if the shell was not already "activated".  Fish adds a new dynamic to that.  In Bash, my "activation" logic involved setting environment variables and then declaring Bash functions that were automatically inherited by any subshell.  In Fish, the environment variables are carried into new shells (if they were exported) too, but the functions are not.  That is a **good thing**, because all I really need to "carry over" my Fish functions is to properly configure `fish_function_path` to reference my project-specific directory.  I **STRONGLY** prefer the Fish approach to functions because it means that I can dynamically alter their definitions without having to jump through hoops to get them recognized in my shell (which Bash requires).  The special fish variables are carried over, but they lose some of their specialness ("path" variables).

I think that I can easily isolate the functionality that I need into a small Fish script that I can invoke from each stand-alone script in my project.  My `activate.fish` script is already MUCH smaller and simpler than my `activate.bash` script was.

Thank you for all your kind insights and explanations.  I understand Fish's behavior and  I have a direction to go now.

**Comment by faho** [comment]
Alright, question was answered, closing!

**Comment by rdw20170120** [comment]
I have been working intensely on this for the past several weeks.  I am VERY pleased with my decision to switch from Bash to Fish, and I cannot imagine EVER going back.  Bash is such a productivity killer and insanity producer!

I have nearly completed my project to create an easy-to-use and sustainable monorepo leveraging Fish along with my other key tools (e.g., Python3, Docker, Earthly).  I hope to soon publish them as an open-source project to share with everyone.  My approach is a bit different (as the above discussion should indicate), but I think that many people may find it valuable as it enables DevOps/SRE automation easily and reliably.

Thank you for all your help, and for making some great Fish!!!
