### ISSUE TITLE
Save execution time in history

### ISSUE THREAD

**Issue by simonsilvalauinger** [fish-shell/fish-shell#816]
It would be cool if fish could save (optional) the execution time of an command in the history. So it would be easy to search for the commands executed at a specific date. The fish_config history page then could be extended with a date filter.
What do you think about it?

**Comment by lmsurpre** [comment]
Would be cool if it included the end time of the command as well.  Then length of execution could be computed as well.  Not sure if this is what @simonsilvalauinger was asking or not.

**Comment by krader1961** [comment]
The time a command was executed is already stored. And the history command was recently enhanced to allow displaying it with a default or user defined format. For example, I use the following function:

```
function h --description 'alias h builtin history search -15 --show-time="%a %m-%d %R  "'
    builtin history search -15 --show-time="%a %m-%d %R  " $argv
end
```

We don't currently record how long the command ran but that could be done if someone is willing to open an issue where they argue whey that would be useful.
