### ISSUE TITLE
cd command tab completion not working for folder in PWD if CDPATH is set

### ISSUE THREAD

**Issue by delicb** [fish-shell/fish-shell#8161]
Fish version: `3.3.1`
Term: `xterm` && `xterm-256color`
OS: `Linux e0148dba6715 5.10.25-linuxkit #1 SMP PREEMPT Tue Mar 23 09:24:45 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux` && `Darwin xxx 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:31 PDT 2021; root:xnu-7195.121.3~9/RELEASE_ARM64_T8101 arm64`
Customizations: minimal, but reproduction possible in fresh docker container with zero customizations

Tab completion does not work for `cd` command for folder in `$PWD` if `CDPATH` is set. 

I have tried this on MacOS (with minimal config) and in fresh ubuntu docker container with no previous configuration. Repo:
```shell
$ mkdir -p foo/bar/my-folder
$ set CDPATH $HOME/foo/
$ cd bar  # works, since foo is in CDPATH
$ ls
my-folder
$ cd my-<tab>  # does not offer tab completion  <---
$ cd my-folder  # works normally
```

It seems that setting `$CDPATH` overrides `$PWD` for tab completion, but not for command functioning. Could I add `$PWD` to `$CDPATH` explicitly somehow. Based on [documentation](https://fishshell.com/docs/current/cmds/cd.html) I have expected this to work out of the box, since it states:
> If DIRECTORY is a relative path, the paths found in the CDPATH list will be tried as prefixes for the specified path, in addition to $PWD.

I have tried setting `CDPATH` to `'$PWD' $HOME/foo/`, but did not get any better results (using single quotes around `$PWD`, since it is expanded at the moment of setting variable, and not dynamically, which is not useful).

Either I am doing something wrong, or there is a bug. If I am doing something wrong, I would appreciate some guidance. 

Thanks.

**Comment by faho** [comment]
Aaaah, missed in #4484.

The simple workaround is to explicitly add `.` - it's also recommended, because other directories being picked first is super confusing (which was the reason for originally not implicitly using it).

**Comment by delicb** [comment]
Thanks @faho . This solved the problem. 

I see there was discussion in linked ticket if `.` should be added implicitly, but maybe at last add this behavior to documentation?

**Comment by faho** [comment]
It... is?

>  If ``DIRECTORY`` is a relative path, the paths found in the ``CDPATH`` list will be tried as prefixes for the specified path, in addition to $PWD.

Or do you mean the completions not working like that? Because that's a bug, and that's now fixed.

**Comment by delicb** [comment]
Yea, I was thinking adding info that if `CDPATH` is modified, there is no implicit `.` anymore. 

But I saw your comment from my phone, got to the laptop and tried out on laptop and completely missed the commit that fixes the bug. Part of it was that I did not expect such a quick fix :). Thanks a lot for prompt fix and workaround until next release.
