### ISSUE TITLE
OBS GPG KEY expired

### ISSUE THREAD

**Issue by kirkhansen** [fish-shell/fish-shell#8162]
[Following these instructions](https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A3&package=fish), I received `The following signatures were invalid: EXPKEYSIG 2CE2AC08D880C8E4 ` error when executing an `sudo apt update`.

```
Err:11 http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_10  InRelease
  The following signatures were invalid: EXPKEYSIG 2CE2AC08D880C8E4 shells:fish OBS Project <shells:fish@build.opensuse.org>
Reading package lists... Done
W: GPG error: http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_10  InRelease: The following signatures were invalid: EXPKEYSIG 2CE2AC08D880C8E4 shells:fish OBS Project <shells:fish@build.opensuse.org>
E: The repository 'http://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_10  InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by zanchey** [comment]
The signing key I've got expires in 2022 (`osc signkey shells:fish:release:3|gpg2 --show-keys`).

Is the clock on your computer right (one way to check is running `date`)? What does `apt-key list 2CE2AC08D880C8E4` tell you?

Is this the first time you have installed fish, or have you had the repository added for a while?

**Comment by kirkhansen** [comment]
`date` is good, but listing the keys showed two of them with the same id, and it was using the old one.
Removing it `sudo apt-key del 2CE2AC08D880C8E4` and re-fetching the new key works now though. Thanks!

```bash
sudo apt-key list 2CE2AC08D880C8E4
pub   rsa2048 2013-10-08 [SC] [expired: 2020-03-11]
      24A6 3B31 CAB4 1B33 EC48  801E 2CE2 AC08 D880 C8E4
uid           [ expired] shells:fish OBS Project <shells:fish@build.opensuse.org>

pub   rsa2048 2013-10-08 [SC] [expires: 2022-04-12]
      24A6 3B31 CAB4 1B33 EC48  801E 2CE2 AC08 D880 C8E4
uid           [ unknown] shells:fish OBS Project <shells:fish@build.opensuse.org>
```
