### ISSUE TITLE
Fish not setting up

### ISSUE THREAD

**Issue by C47F15H** [fish-shell/fish-shell#8165]
Screenshot:
![Screenshot](https://user-images.githubusercontent.com/80169337/126868507-13ff0233-a76a-444f-a09b-b3c15e4bd449.png)
Information | _
--|--
OS | Darwin 20.5.0
installed with | [`brew install fish`](https://brew.sh)
current shelll | ZSH 5.8
Software `/usr/bin/sw_vers` | macOS 11.4

**Comment by faho** [comment]
What is happening here is that fish can't find your terminfo database - and not just one entry, but absolutely none of it. Not even the absolute minimum "dumb" entry.

That should mean one of two things:

- The directory that these are in (typically /usr/share/terminfo) is inaccessible
- The (n)curses it's being compiled against is broken

It would also be possible to e.g. alter the search path so it's broken. My version of ncurses *always* checks the compile-time default but maybe yours doesn't. So the output of `env` in the environment you'd start fish in would be helpful, specifically things like TERMINFO_DIRS

**Comment by zanchey** [comment]
There's something excitingly broken in ncurses, there.

The output of the following commands might help us to work this out:

`/usr/local/opt/ncurses/bin/infocmp`
`otool -L $(which fish)`
`ls /usr/local/Cellar/ncurses/6.2/share/terminfo/78`

**Comment by C47F15H** [comment]
> `/usr/local/opt/ncurses/bin/infocmp`
> `otool -L $(which fish)`
> `ls /usr/local/Cellar/ncurses/6.2/share/terminfo/78`

```zsh
infocmp: couldn't open terminfo file xterm-256color.
/usr/local/bin/fish:
	/usr/local/opt/ncurses/lib/libncursesw.6.dylib (compatibility version 6.0.0, current version 6.0.0)
	/usr/local/opt/pcre2/lib/libpcre2-32.0.dylib (compatibility version 11.0.0, current version 11.2.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 905.6.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
ls: /usr/local/Cellar/ncurses/6.2/share/terminfo/78: No such file or directory```

**Comment by zanchey** [comment]
Your Homebrew ncurses installation is incomplete. `brew reinstall ncurses` may help.

**Comment by C47F15H** [comment]
thanks, that worked!
