### ISSUE TITLE
__fish_print_xrandr_modes is broken

### ISSUE THREAD

**Issue by lolbinarycat** [fish-shell/fish-shell#8166]
verison 3.1.0

it simply doesn't print anything.
the fix is to add `-L` to the flags for `read` in xrandr.fish

**Comment by faho** [comment]
Please update to fish 3.3.1 and try again.

We offer PPAs, see https://fishshell.com

**Comment by faho** [comment]
In this particular case it looks like #6650, which was fixed in fish 3.1.**1**, which Ubuntu has elected not to upgrade to.

That's why I'm asking you to upgrade - we've already fixed it, and released the fix, months ago.
