### ISSUE TITLE
Support fish_vi_cursor on Terminal.app

### ISSUE THREAD

**Issue by lilyball** [fish-shell/fish-shell#8167]
Apple Terminal.app gained support for xterm cursor escapes back in macOS Sierra 10.12. `fish_vi_cursor` hasn't realized this yet. I can set `fish_vi_force_cursor` but I shouldn't have to.

Terminal.app can be detected using `$TERM_PROGRAM`, which should have the value `Apple_Terminal`.

fish 3.3.1

**Comment by zanchey** [comment]
Any idea what `TERM_PROGRAM_VERSION` is in Sierra?

**Comment by ridiculousfish** [comment]
I got it installed and see `388.1.1`. I can tackle this when I get back next week.

**Comment by tami5** [comment]
Sorry, but is alacirtty supported? I couldn't fix the block shape being active in insert mode

**Comment by ridiculousfish** [comment]
@tami5 I do not see any checks for alacritty. You can set `fish_vi_force_cursor`.

**Comment by faho** [comment]
Nah, Alacritty [is supported](https://github.com/fish-shell/fish-shell/commit/3c6c8d542410cd84b8249c84a58ec28db71fba06#diff-af2d350de101d2167ef6ef249363efbfa5bb05acdc4d581cd914d80cd845db76) since fish 3.2.0, @tami5: Update fish.

**Comment by ridiculousfish** [comment]
Shame on me, just saw it too.

**Comment by ridiculousfish** [comment]
I enabled these unconditionally for Apple_Terminal since the escapes appear to be ignored on versions before 10.12.
