### ISSUE TITLE
`set -S` should mark read-only variables

### ISSUE THREAD

**Issue by lilyball** [fish-shell/fish-shell#8179]
fish 3.3.1

Most special variables defined by fish are read-only. `set -S` does not indicate this in any way. For example:

```
 ❯ set -S PWD
$PWD: set in global scope, exported, with 1 elements
$PWD[1]: |/Users/lily|
```

This should instead look something like

```
 ❯ set -S PWD
$PWD: set in global scope, exported, read-only, with 1 elements
$PWD[1]: |/Users/lily|
```

**Comment by zx8** [comment]
FWIW `$PWD` is _not_ read-only 😄 

```
$ set -S PWD
$PWD: set in global scope, exported, with 1 elements
$PWD[1]: |/usr/local/bin|

$ set -S status
$status: set in global scope, unexported, with 1 elements
Variable is read-only
$status[1]: |0|
```

**Comment by lilyball** [comment]
Was `$PWD` made writable since 3.3.1? Because it's read-only there.

```
❯ set PWD foo
set: Tried to change the read-only variable “PWD”
```

**Comment by faho** [comment]
It is read-only, setting it fails correctly, the display is broken.

I think there might be two different variables floating around?

In one place var->readonly() returns true, in another false?

**Comment by faho** [comment]
Ya know what? All the other vars work, so there's something funky going on with $PWD.

I just hard-coded it for now in `set --show`.

**Comment by lilyball** [comment]
I just put a comment on the commit explaining the issue https://github.com/fish-shell/fish-shell/commit/b3cdf4afe1311888935d1cccd91d54d46bce9d22#r54169505
