### ISSUE TITLE
alpine: python3: can't open file '/usr/share/fish/tools/create_manpage_completions.py':

### ISSUE THREAD

**Issue by agarzon** [fish-shell/fish-shell#8185]
I'm experimenting with a fresh installation of Alpine Linux, testing what of my usual tools are compatible.

### Environment:
- Alpine Linux v3.14
- Fish 3.2.2
- Python 3.9.5
- No other shell, plugin and addon has been installed, this is just a fresh clean Alpine installation created for testing purpose.
- All commands executed as **root** user.

###  Steps:
Install fish by: `apk add fish`
Went to fish shell by executing `fish` (and I can see the welcome to fish message)
Run: `fish_update_completions`
Got error: `python3: can't open file '/usr/share/fish/tools/create_manpage_completions.py': [Errno 2] No such file or directory
`

I checked and actually the folder **/usr/share/fish/tools/** does not exists.

**Comment by faho** [comment]
Alpine ships these in a separate [fish-tools](https://pkgs.alpinelinux.org/package/edge/main/armhf/fish-tools) package. Install that as well.

**Comment by agarzon** [comment]
Thank you, looks like the correct fix, the [fish-tools](https://pkgs.alpinelinux.org/package/edge/main/armhf/fish-tools) contains exactly the missing files and belongs to the main repository.

Unfortunatelly:
```bash
alpine-test:~# apk add fish-tools
ERROR: unable to select packages:
  cmd:man (virtual):
    provided by: mandoc man-db
    required by: fish-tools-3.2.2-r1[cmd:man]
```

**Comment by agarzon** [comment]
Fixed by installing ```apk add man-db``` before.
