### ISSUE TITLE
Vim "*p binding is broken, mixes input functions and fishscript together

### ISSUE THREAD

**Issue by lilyball** [fish-shell/fish-shell#8186]
fish 3.3.1

The Vim `"*p` binding is completely broken as it mixes input functions and fishscript together:

```fish
bind --preset '"*p' forward-char 'commandline -i ( xsel -p; echo )[1]'
```

Because of this, attempting to invoke this binding does nothing at all. (Side note: I'm surprised this doesn't print any errors)

Even if this worked, it would be the wrong behavior at the end of a line. Vim's behavior when `virtualedit=onemore` (which is what fish is doing) is for `p` to keep the cursor on the current line. So really we need some fishscript function that inspects the character after the cursor to determine if it's a newline, if not then advances by one char, otherwise does nothing. Then we can use that in this binding instead of `forward-char`.

**Comment by lilyball** [comment]
The end-of-line behavior affects the `p` binding too (which is currently `forward-char yank`).

**Comment by faho** [comment]
Closing in favor of #8189.

No need to have issues this granular.

**Comment by krobelus** [comment]
mixing input functions and fishscript in bindings will be fixed with https://github.com/fish-shell/fish-shell/pull/10338
