### ISSUE TITLE
Vim "*p and "*P bindings are not platform- or token-aware, broken on Darwin

### ISSUE THREAD

**Issue by lilyball** [fish-shell/fish-shell#8187]
fish 3.3.1

The `fish_vi_key_bindings` and `fish_hybrid_key_bindings` include the following two bindings:

```fish
bind --preset '"*p' forward-char 'commandline -i ( xsel -p; echo )[1]'
bind --preset '"*P' 'commandline -i ( xsel -p; echo )[1]'
```

This assumes the use of `xsel` for clipboard manipulation, which doesn't work everywhere, and especially doesn't work on Darwin.

Compare this with `fish_clipboard_paste`, which has the following logic:

```fish
    set -l data
    if type -q pbpaste
        set data (pbpaste 2>/dev/null)
    else if set -q WAYLAND_DISPLAY; and type -q wl-paste
        set data (wl-paste 2>/dev/null)
    else if type -q xsel
        set data (xsel --clipboard 2>/dev/null)
    else if type -q xclip
        set data (xclip -selection clipboard -o 2>/dev/null)
    else if type -q powershell.exe
        set data (powershell.exe Get-Clipboard | string trim -r -c \r)
    end
```

The `"*p` and `"*P` bindings should be doing the same thing.

In addition, `fish_clipboard_paste` has logic for intelligently quoting the clipboard based on the current token and other similar transformations.

Beyond that, just reading the bind it appears that it won't handle multi-line pastes correctly. It says `( xsel -p; echo )[1]`, and I'm really not sure why it's constructed this way instead of just `( xsel -p )`. But I would expect `"*p` to paste the entire clipboard, not just the first line.

Given all this , I think the right call is to just change these bindings to use `fish_clipboard_paste`.

Also see #8186 regarding the mixing of `forward-char` and fishscript in the `"*p` binding.

**Comment by faho** [comment]
Closing in favor of #8189.

No need to have issues this granular.
