### ISSUE TITLE
Vim insert mode \e binding can back up past newline unexpectedly

### ISSUE THREAD

**Issue by lilyball** [fish-shell/fish-shell#8188]
fish 3.3.1

In Vim, if the cursor is at the start of a line, pressing <kbd>Esc</kbd> does not back up past a newline. In fish it does, as fish is just blindly calling `backward-char`. This is very surprising when editing multi-line input in fish (such as writing a function definition). Either this needs to use fishscript to back up only if the previous character isn't a newline, or there needs to be additional special input functions for forward/backward-char that don't move if it would cross a newline.

Also see #8186 that talks about a similar issue.

**Comment by faho** [comment]
Closing in favor of #8189.

No need to have issues this granular.
