### ISSUE TITLE
Hi, does fish-shell have a file like .zshrc for zshshell

### ISSUE THREAD

**Issue by Yakumo-Yukari** [fish-shell/fish-shell#8190]
Hi, does fish-shell have a file like .zshrc for zshshell, and in what file should I write some environment variables for other applications if I use fish-shell?

**Comment by branchvincent** [comment]
Indeed, the closest equivalent is `~/.config/fish/config.fish`. See http://fishshell.com/docs/current/index.html#configuration for more

**Comment by ridiculousfish** [comment]
Closing as the question has been answered. [gitter](https://gitter.im/fish-shell/fish-shell) is probably a better place for questions like this (but please do search the docs first, we work hard on them!)
