### ISSUE TITLE
tmux new pane open empty fish prompt

### ISSUE THREAD

**Issue by tami5** [fish-shell/fish-shell#8193]
Fish version: 3.3.1
uname: Darwin arm64
TERM: tmux-256color

at new tmux session or opening a new pane, I get empty prompt and it stays empty for a bit but on enter it git shown.

I tried everything, removed both my tmux and fish config but still same issue.

**Comment by faho** [comment]
This works for me.

What is your `locale` both in and outside of fish? When you say you "removed" the config, you do mean entirely removed config.fish, all your plugins, and .tmux.conf?

**Comment by tami5** [comment]
Hey @faho

my locale is 

```
LANG="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_ALL="en_US.UTF-8"
```

and yes I've removed config.fish file and .tmux.conf

**Comment by faho** [comment]
How are you starting fish? Is it set as your default shell (via `chsh`)?

Do you have any *functions* left, especially a `fish_greeting`?

**Comment by tami5** [comment]
Oh indeed it is something todo with my configuration. I've renamed ~/.config/fish and now I no longer have this is issue. I will keep debugging my configuration. Thanks @faho It must be a plugin I installed that causing this.

**Comment by tami5** [comment]
Found it. it was https://github.com/tomyun/base16-fish
