### ISSUE TITLE
Installing fish-shell as another app in Ubuntu

### ISSUE THREAD

**Issue by deepanshu44** [fish-shell/fish-shell#8194]
I want bash to be default shell in terminal to be used by other apps and use fish for myself and open it through a shortcut.

Is it possible to do that?

**Comment by faho** [comment]
Yeah? Just... install it and run `fish` in your terminal.

**Comment by zanchey** [comment]
Our packages from https://launchpad.net/~fish-shell/+archive/ubuntu/release-3/+packages install a shortcut into the launcher, so you can just type "fish" into the Activities search and it will show you an icon that starts fish. The fish installed from Ubuntu directly doesn't do this though.

**Comment by deepanshu44** [comment]
@faho thanks, gnome-terminal -- fish solves the problem.
But still colours are missing but no problem.
I dropped the idea of using fish as it is creating problem for path variables.

**Comment by deepanshu44** [comment]
@zanchey thanks a ton, everything seems to be working fine now.

Don't know why fish.config was missing by installing through 'apt' but your solution have solved my problem.

**Comment by deepanshu44** [comment]
BTW if anybody uninstalling fish should make sure to set default shell to /bin/bash through chsh before uninstalling.
`chsh -s /bin/bash`

If you don't do that and uninstall, then when you restart your pc, your account would not be listed in login screen. Moreover your shell widgets wouldn't work anymore but terminal would.
