### ISSUE TITLE
Config for both osx and linux

### ISSUE THREAD

**Issue by tamis-laan** [fish-shell/fish-shell#8203]
Usually I use linux but for work I need to use osx. I would like to use my fish config for both, however some things are incompatible. Is there some way to check for the operating system in the config file?

**Comment by faho** [comment]
The normal `uname` command will print "Darwin" on macOS and "Linux" on linux.

However, typically I would recommend just looking for what you actually use - e.g. if you want to do something with `brew`, check if `brew` is available via `type -q brew` (it's also available for linux!)

**Comment by tamis-laan** [comment]
That's pretty cool, how would that work in a one liner?

**Comment by faho** [comment]
Don't force yourself to write one-liners.

I would do it something like

```fish
set -l os (uname)
if test "$os" = Darwin
    # do things for macOS
else if test "$os" = Linux
    # do things for Linux
else
    # do things for other operating systems
end
```
    
Or

```fish
switch (uname)
    case Darwin
        # do things for macOS
    case Linux
        # do things for Linux
    case '*'
        # do things for other OSs
end
```

**Comment by faho** [comment]
Question was answered, closing!
