### ISSUE TITLE
Fish autocomplete error on iOS procursus

### ISSUE THREAD

**Issue by theotheroracle** [fish-shell/fish-shell#8205]
`fish, version 3.2.2`

`Darwin borrelly 18.7.0 Darwin Kernel Version 18.7.0: Mon Nov  9 15:07:15 PST 2020; root:xnu-4903.272.3~3/RELEASE_ARM64_T7000 iPhone7,2 arm64 N61AP Darwin`
( iOS with procursus jailbreak )

there aren't any tweaks on my shell .

as far as i can tell, it's detecting that i'm on darwin, an looking for the macos binary makewhatis, but that's not available on ios .

```
fish: Unknown command: /usr/libexec/makewhatis
/usr/share/fish/functions/__fish_apropos.fish (line 37): 
            /usr/libexec/makewhatis -o $db (man --path | string split :) >/dev/null 2>&1 </dev/null &
            ^
in function '__fish_apropos' with arguments 'test'
	called on line 15 of file /usr/share/fish/functions/__fish_describe_command.fish
in function '__fish_describe_command' with arguments 'test'
in command substitution
```

it's an error with tab completion, it originally gave an error about awk, but i installed awk to fix that .

**Comment by faho** [comment]
Yeah, this is simple enough, should be fixed (this claims to be Darwin but doesn't have makewhatis where macOS has it).

However I can't say that I see jailbroken ios become one of our primary platforms, so if there's anything bigger we might have to ask downstream to carry patches instead.
