### ISSUE TITLE
Tab completion for `yadm` will freeze fish

### ISSUE THREAD

**Issue by Cokile** [fish-shell/fish-shell#8207]
fish --version: `fish, version 3.3.1`
echo $version: `3.3.1`

operation system: MacOS 11.4
terminal: Alacritty 0.9.0
uname -a: `Darwin Cokiles-MacBook-Pro.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64`
echo $TERM: `xterm-256color`

steps to reproduce:

![image](https://user-images.githubusercontent.com/8230448/128301989-8d5a9f4f-b352-4f2c-89a5-c78fd9c63ec0.png)

When I press `Tab` to auto complete `.tumx.conf`, fish will freeze (and seems not recoverable). Use fish with iTerm2 will also have this issue.

BTW, use `l` in vi normal mode or left arrow key will not have this issue.

**Comment by faho** [comment]
Most likely this will just take a while. The completions run `yadm introspect commands` on load, once, and that might just need a bit.

**Comment by Cokile** [comment]
It seems like a issue of yadm rather than fish: https://github.com/TheLocehiliosan/yadm/issues/359

**Comment by faho** [comment]
For obvious reasons, we don't use the zsh completions, so unless those do the same thing as we I'm not sure it is.

It seems we run `yadm` in a few ways here:

```fish
yadm gitconfig --get core.worktree
yadm introspect repo
yadm introspect commands
```

Other than that, it's running the git completions and just completing words on its own.

So I would assume one of the above calls hangs or takes ages.

**Comment by kkga** [comment]
It doesn't seem to be a yadm problem:
`git --git-dir ~/.local/share/yadm/repo.git --work-tree $HOME add <TAB>` results in the same hang.

**Comment by faho** [comment]
You're adding files *from $HOME*? Yeah, that's gonna take a while.

For obvious reasons. There are a lot of files in $HOME.

**Comment by kkga** [comment]
> You're adding files from $HOME? Yeah, that's gonna take a while.

I've been doing this in fish for years and on machines with much more files in $HOME: tab completion was always instant. My guess is that something changed in one of the recent releases.

**Comment by angauber** [comment]
@faho I am having the same issue when completing `.config/fish` which has not that many files

``` fish
>tree .config/fish
.config/fish
├── completions
├── conf.d
├── config.fish
├── fish_variables
└── functions
    ├── aur.fish
    └── fish_prompt.fish

3 directories, 4 files
```

Full command:

``` fish
git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME add .config/fish/<TAB>
```

The completion takes ~10 seconds, is it looking in directories upper than the provided argument ?

**Comment by faho** [comment]
>The completion takes ~10 seconds, is it looking in directories upper than the provided argument ?

It is looking in the entirety of $HOME, and then filtering *that*, yes.

I do not believe git gives us enough options to hand it the path (some fiddling with `--glob-pathspecs` might help), but even if it did completing directly after the `add` would still necessarily scan all of $HOME.

Yes, making $HOME a git directory is sometimes going to be slow.

**Comment by krobelus** [comment]
You should tell git to ignore files that are not important, for example put this in your `.gitignore`:
```
*
!/.config/fish/
```
