### ISSUE TITLE
Slow interaction between backgrounding, universal variables, and repainting

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#8209]
`fish, version 3.3.1`
`Linux arch 5.13.7-arch1-1 #1 SMP PREEMPT Sat, 31 Jul 2021 13:18:52 +0000 x86_64 GNU/Linux`

First, I ***do not*** expect anyone to work on this. It is a largely frivolous bug that effects very few users.
I've been sitting on it for a while, but decided I might as well put it here for informational purposes.

Clean fish, with the following defined in `fish_prompt.fish`:

```fish
# Defined in fish_prompt.fish
function _refresh_prompt --on-variable foo
    commandline --function repaint
end

function fish_prompt
    fish --command "set -U foo $PWD" &
    echo $foo
end
```

Here's what it looks like in Fish 3.2.2:

https://user-images.githubusercontent.com/6318351/128436273-13b501db-da8f-42d2-8ff3-e64e80f06985.mp4

In Fish 3.3.1 there seems to be a few hundred millisecond lag:

https://user-images.githubusercontent.com/6318351/128436355-3f362585-93cb-41ce-9fa4-d547010e7f40.mp4

---

Weirdly enough, this works in Fish 3.3.1, and is perfectly responsive:

https://user-images.githubusercontent.com/6318351/128437639-a4146e99-cfc4-4e9b-bdf4-1ad48e0f6591.mp4

Maybe this means the bug has something to do with pgroups?

---

Alright so there it is. Unfortunately, I wasn't able to bisect the bug because of a separate bug that happened in between, https://github.com/fish-shell/fish-shell/issues/8088

**Comment by faho** [comment]
cc @ridiculousfish

**Comment by ridiculousfish** [comment]
The issue here is that we are spawning an instance of fish which sets a uvar and then immediately exits. On Linux, uvar changes are broadcast by writing some data to a pipe, waiting a bit, and then reading it back, but there's no way to read it back if fish has exited. This means data is left on the pipe, so we stay in "polling mode" longer and the poll interval is 100 msec. Well I guess we can reduce it to 10 msec.

**Comment by IlanCosman** [comment]
No way! You're actually working on it, what a legend! I really, truly appreciate it ❤️
I swear once I take my intro to C class next quarter, I'll try to stop being such a bothersome moocher and start contributing 😄

>writing some data to a pipe, waiting a bit, and then reading it back

Forgive my ignorance, but why do we need to read it back? After all, we're the ones who just sent it, so we know what it says 😄

**Comment by ridiculousfish** [comment]
d6075885efd9dd1c0f1038ca8fddcc56d8241dcb should reduce the max delay from 100 msec to 10 msec. I think this is the best we can easily do. Thanks for filing.
