### ISSUE TITLE
Make directory creation on startup opt-in

### ISSUE THREAD

**Issue by henriquehbr** [fish-shell/fish-shell#8216]
I'm not sure if this goes against fish philosophy, but, shouldn't we allow the user decide whether or not to create empty directories on config directory? (like `config.d/`, `completions/` and `functions/`)

For the most part, fish main objective seems to be providing a full "out-of-the-box" experience, but couldn't we do like `zsh` and display a prompt on the first run asking the user for it's consent before creating those directories?

**Comment by faho** [comment]
You've basically answered it yourself - that's not how fish works. Sorry!

**Comment by faho** [comment]
What you would instead do is make a case for why we shouldn't create these directories, but do note that fish has been doing this since basically forever (at least ea998b03f2, version 1.22), and I'm not aware of anyone else ever complaining, so it's a high barrier to clear.

**Comment by henriquehbr** [comment]
Found a way to get rid of this silly inconvenience, simply comment line 273 (might change in the future) of the file `/usr/share/fish/functions__fish_config_interactive.fish`, i'm not sure, but probably this path might vary according to your distro, it looks like this:

```fish
# Create empty configuration directores if they do not already exist
test -e $__fish_config_dir/completions/ -a -e $__fish_config_dir/conf.d/ -a -e $__fish_config_dir/functions/ ||
    #mkdir -p $__fish_config_dir/{completions, conf.d, functions}
```

Leaving here in case it might help someone in the future
