### ISSUE TITLE
fish inserts newlines while typing, before hitting return

### ISSUE THREAD

**Issue by ancientjpeg** [fish-shell/fish-shell#8220]
Hi, 
I started learning react today, but before I could even properly get started, I ran into this strange issue with fish. Whenever I cd to the directory containing the react project, the fish prompt changes in several ways. Expectedly, it begins to display information about the git repo contained within the project, but also displays a bizarre behavior as I type.

**Reproduction Steps:**

Open fish via iTerm2
Change directory to a newly created react project (npx create-react-app app-name)
Type anything into the terminal (or, resize the window)

**Expected behavior:**

The shell should only go on to a new line when pressing the enter key.

**Observed behavior:**

It goes on to a new line arbitrarily when entering text. It also appears that the last digit of the system time carries over to the new line, this may be linked.

**Screenshot:**
<img width="830" alt="Screen Shot 2021-08-16 at 3 50 37 PM" src="https://user-images.githubusercontent.com/65221904/129639295-fc3ec91b-b86c-412a-86bd-f290c5bfc122.png">

**System:**
I am using iTerm2 on macOS Big Sur 11.4, with fish version 3.3.1. I also tested this using mac terminal which did not replicate the issue, so I will likely report this to iTerm as well.

**Comment by zanchey** [comment]
In the issue template, we ask if this problem occurs when you try without any customisations. Please do this.

In this case the likely issue is that your terminal and fish disagree on the width of the 💩  emoji. See https://fishshell.com/docs/current/faq.html#i-m-getting-weird-graphical-glitches-a-staircase-effect-ghost-characters-cursor-in-the-wrong-position

You can try:
- Making sure that iTerm 2 is set to Unicode 9 mode (Prefs > Profiles > Text > Use Unicode 9 widths)
- Checking whether `fish_ambiguous_width` or `fish_emoji_width` are set, and if so, to what.

**Comment by ancientjpeg** [comment]
I ran without customizations (sh -c 'env HOME=$(mktemp -d) fish') and the issue was no longer present! Further, echoing `fish_ambiguous_width` and `fish_emoji_width` shows that both are undefined, and the issue does not change when I set both environment variables to both 1 and 2. My iTerm is set to use Unicode 9 widths. Any ideas? Thanks so much for the assistance!

**Comment by faho** [comment]
How did you set the variables?

Try

```fish
set -g fish_emoji_width 2
```

(we default to Unicode 8 sizes - i.e. $fish_emoji_width of 1 in iTerm because that defaults to unicode 8 - yes, all of this sucks, no, there isn't anything better)

**Comment by ancientjpeg** [comment]
Didn't use the -g flag! Resolved the issue and I've now added it to my fish_config. Thank you again for the assistance.

**Comment by zanchey** [comment]
> iTerm because that defaults to unicode 8

iTerm defaults to Unicode 9 on anything reasonably new now, per https://gitlab.com/gnachman/iterm2/-/issues/6337#note_233630790

**Comment by faho** [comment]
>iTerm defaults to Unicode 9 on anything reasonably new now

Oooh, last time I looked I was under the impression they planned to *never* switch? Like the idea was that every program would have to keep requesting a newer width, for iTerm2 only?

Anyway, updated, now we assume a width of 2 for iTerm - of course if you change the setting from the default you still need to change the variable as well, but that can't be helped.
