### ISSUE TITLE
Multiline prompt prints the first line again once I start typing

### ISSUE THREAD

**Issue by mrjones2014** [fish-shell/fish-shell#8233]
Fish version: 3.3.1

I tried removing all 3rd party customizations and just setting my prompt to
```
function fish_prompt
  echo "(whoami)
=>"
end
```

and the same issue occurs.

Usually the first command once I open the shell is fine, but on every subsequent command, as soon as I type a character at the command line, it re-prints the first line of my two-line prompt.

https://user-images.githubusercontent.com/8648891/130075673-632a22a7-1915-4125-9a14-7cda98defc13.mov

**Comment by faho** [comment]
Works for me, try in a different terminal. Which terminal do you use? What does `locale` say?

Usually this is down to the terminal and fish disagreeing on the width of a character.

Did you actually set it to `=>` (that's a normal equals sign and a normal greater-than sign) or did you use that arrow the recording shows?

Do you have a right prompt?

**Comment by mrjones2014** [comment]
Interesting. Testing a bit further, it seems to only happen when I'm in `tmux` -- but if I'm in `tmux` it happens in both kitty and alacritty.

The recording shows my customized prompt, but here's one with customizations removed. It seems to only be reproducible when using `fish_vi_key_bindings`. (Side note, not sure why the variable expansion isn't working now in the prompt 🤔)

https://user-images.githubusercontent.com/8648891/130077659-8664daf7-0510-4762-9c2a-5606e9347223.mov

But then switching back to `fish_default_key_bindings`, the issue persists.

![image](https://user-images.githubusercontent.com/8648891/130077811-896b2f6d-5c29-4ba2-ac24-021f581ee4b6.png)

**Comment by mrjones2014** [comment]
`locale` says
![image](https://user-images.githubusercontent.com/8648891/130077878-fd127513-e17c-4b09-b2bf-c2e1d98bdf10.png)

**Comment by mrjones2014** [comment]
Huh. I just commented out my key bind code, sourced it, then uncommented, then sourced again, and now the issue is gone..... spooky.

**Comment by mrjones2014** [comment]
Nope, it just started happening again :(

**Comment by faho** [comment]
> (Side note, not sure why the variable expansion isn't working now in the prompt thinking)

1. it's not a variable expansion, but command substitution,
2. you've quoted it

```fish
function fish_prompt
    echo (whoami)"
=>"
end
```

>It seems to only be reproducible when using fish_vi_key_bindings

Okay, so does it require vi mode now or not?

**Comment by mrjones2014** [comment]
@faho the problem only starts happening once you enable `fish_vi_key_bindings`, but turning it back off does not fix the issue once it starts.

**Comment by faho** [comment]
So in other words, if fish_vi_key_bindings was ever active in that session it starts?

That sounds like something confuses tmux, most likely the cursor change sequences. Try

```fish
function fish_vi_cursor_handle; end
function fish_vi_cursor_handle_preexec; end
```

**Comment by mrjones2014** [comment]
@faho even disabling it, then running `killall fish tmux kitty`, and starting a new session, the problem still persists.

Those changes you listed don't fix the issue either.

Here's my current `fish_user_key_bindings`

```fish
# workaround for https://github.com/fish-shell/fish-shell/issues/3481
function fish_vi_cursor; end # this fixed it before but it doesn't anymore
function fish_user_key_bindings
  fish_vi_key_bindings
  bind -M insert jk "if commandline -P; commandline -f cancel; else; set fish_bind_mode default; commandline -f backward-char force-repaint; end"
end
```

**Comment by faho** [comment]
Ah, okay, this is the same as #3481 then.

**Comment by faho** [comment]
>function fish_vi_cursor; end # this fixed it before but it doesn't anymore

This needs to be done *before fish_user_key_bindings*.

The way bindings are loaded changed in fish 3.0, so you don't actually need `fish_user_key_bindings` anymore.

A side effect of that is that `fish_vi_cursor` will already have been executed before it, so you need to change fish_vi_cursor in an autoload file for it (even config.fish should be too late, I think).

**Comment by mrjones2014** [comment]
omg that fixed it, thanks!
