### ISSUE TITLE
Fish shell appends random characters in certain circumstances

### ISSUE THREAD

**Issue by nt3rp** [fish-shell/fish-shell#8240]
Seeming randomly, as I use the fish shell, it adds unexpected characters (usually, `l`, `h`, ` `, or sometimes several of the aforemention) to the beginning or end of some lines--usually the first or last line of input or output.

_I don't know enough to know if this is an issue with the shell (`fish`) or the terminal (`Hyper`), and any help would be appreciated._

## Background

**Fish Version:** 3.3.1
**Terminal:** [Hyper](https://hyper.is/)
**OS**: Windows Subsystem for Linux (WSL) (Ubuntu 18.04.5 LTS)
**$TERM**: `xterm-256color`
**Have you tried fish without third-party customizations:** Yes (via `sh -c 'env HOME=$(mktemp -d) fish'`)

## Steps to reproduce
(I didn't need to do anything special for this to happen; it happened immediately after updating from `3.0.2-1~bionic` to `3.3.1-1~bionic`)

## Notes
- Does the same behaviour occur in `bash`? No
- Does the same behaviour occur in [`xterm.js`](https://github.com/xtermjs/xterm.js) (which is used by Hyper)? Not in the demo, at least.
- Does the same behaviour occur in another terminal? No (tried `bash.exe`, PowerShell, `wsl.exe` and then `fish`; could not reproduce)
- Were you using a nerd font? The problem occurred with system default fonts and nerd fonts
- Is the behaviour caused by some config? No; I even tried deleting all `fish` config before learning of the custom home directory trick (i.e. `rm -rf ~/.config/fish/`)
- I tried setting `fish_emoji_width` and `fish_ambiguous_width` to both 1 and 2 in turn; neither seemed to have any impact?

### Example output

```shell
user@mainframe /m/c/U/User> echo banana | wcl  # Trailing `l` was not part of the input here.
      1       1       7h

user@mainframe /m/c/U/User> echo banana | wc
l      1       1       7h

nterwoord@mainframe /m/c/U/User> ls -la

ltotal 8540  # preceeding `l` is not part of normal output
# ...

luser@mainframe /m/c/U/User>chcp.com # preceeding `l` is not part of normal output
hActive code page: 437

luser@mainframe /m/c/U/User>locale
 LANG=en_US.UTF8
LANGUAGE=
LC_CTYPE="en_US.UTF8"
LC_NUMERIC="en_US.UTF8"
LC_TIME="en_US.UTF8"
LC_COLLATE="en_US.UTF8"
LC_MONETARY="en_US.UTF8"
LC_MESSAGES="en_US.UTF8"
LC_PAPER="en_US.UTF8"
LC_NAME="en_US.UTF8"
LC_ADDRESS="en_US.UTF8"
LC_TELEPHONE="en_US.UTF8"
LC_MEASUREMENT="en_US.UTF8"
LC_IDENTIFICATION="en_US.UTF8"
hC_ALL=

# The below lines have appended characters _and_ lose their chiron `>` in some instance
 user@mainframe /m/c/U/User>set fish_emoji_width 2
lhuser@mainframe /m/c/U/Userset fish_emoji_width 1
lhuser@mainframe /m/c/U/Userset fish_ambiguous_width 1
lhuser@mainframe /m/c/U/Userset fish_ambiguous_width 2
lhuser@mainframe /m/c/U/User>
```

**Comment by faho** [comment]
This means that fish sends an escape sequence that Hyper doesn't understand. Because it's specifically "l" and "h" that show up, it's probably an enable/disable pair, like

- `\e[?2004h` to enable bracketed paste (and "l" instead of h to disable)
- `\e[?1004h` to enable focus reporting
- `\e[?12l` and `\e[?25l` as part of xterm's "cnorm" sequence to reset the cursor to normal
- The xterm flashing sequence

Do you have $TERM set yourself?

**Comment by nt3rp** [comment]
I have looked through my various dot files, and `$TERM` isn't being set by me. It looks like it's being set [by Hyper](https://github.com/vercel/hyper/blob/80c7e67a0d3c83baa2124ef5b1fa8a88f8b56808/app/session.ts#L115):

```
const baseEnv = Object.assign(
      {},
      process.env,
      {
        LANG: `${osLocale.sync().replace(/-/, '_')}.UTF-8`,
        TERM: 'xterm-256color',
        COLORTERM: 'truecolor',
        TERM_PROGRAM: productName,
        TERM_PROGRAM_VERSION: version
      },
      envFromConfig
    );
```

**Comment by faho** [comment]
Okay, so hyper tells us it's xterm, and then doesn't understand an escape sequence that xterm understands. You'll probably want to report this to them instead (or, you know, switch terminals).

**Comment by faho** [comment]
Yeah, no, I've now installed hyper 3.1.2 on archlinux, and tried with fish 3.3.1, and I cannot reproduce this.

**Comment by nt3rp** [comment]
> Yeah, no, I've now installed hyper 3.1.2 on archlinux, and tried with fish 3.3.1, and I cannot reproduce this.

Interesting. I'm happy to close this, but for my own understanding, it sounds like this is most likely a bug in hyper (specifically with the windows version)?

**Comment by nt3rp** [comment]
I can't reproduce on my Mac either (Fish 3.3.1 and Hyper 3.1.2) so I'm chalking this up to an issue with the windows version. Thanks for the help @faho ! I'll file a bug against Hyper (and potentially look into other terminals in the meantime 😅)
