### ISSUE TITLE
fish_history Add custom content

### ISSUE THREAD

**Issue by jiangshengxin** [fish-shell/fish-shell#8248]
fish, version 3.2.2

```bash
tail -f ~/.local/share/fish/fish_history

#How to format the log
- cmd: fish --version
  when: 1629775163
- cmd: tail -f ~/.local/share/fish/fish_history
  when: 1629775212
  paths:
    - ~/.local/share/fish/fish_history

# Change to
- cmd: fish --version
  when: 1629775163
  pwd: /data/install/fish-3.2.2/build     -- current path
  who: jsx      pts/0        2021-08-24 11:12 (10.18.68.11)   -- who -m
- cmd: tail -f ~/.local/share/fish/fish_history
  when: 1629775212
  paths:
    - ~/.local/share/fish/fish_history
  pwd: /data/install/fish-3.2.2/build
  who: jsx      pts/0        2021-08-24 11:12 (10.18.68.11)
```

**Comment by faho** [comment]
What do you want to do with this?

How do you envision this working?

**Comment by jiangshengxin** [comment]
> What do you want to do with this?
> 
> How do you envision this working?

I want to change the log record format to this format：`Change to`，Is to add records in the original format：`pwd`、`who`

**Comment by faho** [comment]
But what do you want to do with that information?

**Comment by jiangshengxin** [comment]
```bash
# logon server
ssh jsx@10.18.68.111
# Switch user identity
sudo su root

# After switching to other users，The real user identity is not recorded
```
> So I want to use commands：`who -m`，Record original operation user
![image](https://user-images.githubusercontent.com/29392026/130593890-543b7744-db46-4bf1-ae80-449b4663bf82.png)

**Comment by faho** [comment]
># After switching to other users，The real user identity is not recorded

Yes, and it won't even be stored in the original user's history! This is an entirely new session that has its own $HOME and keeps the history (and config) entirely separate!

**Comment by jiangshengxin** [comment]
I just want to record this information in "fish"_ history"

> Or why don't you just add who -m >> somefile to your config.fish?
I don't know how to implement it in "config. Fish"

**Comment by faho** [comment]
> I don't know how to implement it in "config. Fish"

`who -m >> ~/my_fish_sessions`

will write the output of `who -m` to `~/my_fish_sessions` whenever you open fish.

If you want to only do it when it e.g. differs from `who`, then check that yourself. I don't know when or how that's the case (`who -m` doesn't seem to print anything for me, even after doing `sudo su`), so I can't help you with that.

**Comment by jiangshengxin** [comment]
> who -m >> ~/my_fish_sessions

Can solve the problem，
Can the format be modified：`fish_history`，I prefer to modify it：
````bash
- cmd: fish --version
  when: 1629775163
  pwd: /data/install/fish-3.2.2/build     # current path
  who: jsx      pts/0        2021-08-24 11:12 (10.18.68.11)   # who -m
- cmd: tail -f ~/.local/share/fish/fish_history
  when: 1629775212
  paths:
    - ~/.local/share/fish/fish_history
  pwd: /data/install/fish-3.2.2/build
  who: jsx      pts/0        2021-08-24 11:12 (10.18.68.11)
````

**Comment by faho** [comment]
> Can the format be modified：fish_history，I prefer to modify it：

Without a good rationale, which you haven't provided, and a good exploration of what should be added and how you should be able to see it inside fish, which you also haven't provided: Sorry, but no.

This is a feature most people won't know about or need, and it would increase the size of the history file a bit.

Just save it yourself and be done.

**Comment by jiangshengxin** [comment]
Can config.fish provide a way to configure a custom desired log format

**Comment by faho** [comment]
>Can config.fish provide a way to configure a custom desired log format

Sorry, it appears we are having trouble communicating.

I don't understand what you mean.

Do you mean "write that `who -m` with some other things into a file"? Yes, you just script however you want it written.

Do you mean "change what fish_history looks like"? No, and that's not the sort of configuration options we are likely to add.

**Comment by jiangshengxin** [comment]
I look forward to providing similar services [HISTTIMEFORMAT](https://www.geeksforgeeks.org/histtimeformat-variable-in-linux-with-example/)

**Comment by faho** [comment]
We will not implement $HISTTIMEFORMAT.

Your immediate question has been answered and I don't see a good reason for the feature request, so I'm closing this.
