### ISSUE TITLE
[Feature request] Use dircolors for file/directory completions

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [fish-shell/fish-shell#8251]
```
fish, version 3.3.1
Linux x1e 5.13.12-arch1-1 #1 SMP PREEMPT Wed, 18 Aug 2021 20:49:03 +0000 x86_64 GNU/Linux
foot
```

ZSH colorizes files/directories in completion output in a way similar to `ls`:
![image](https://user-images.githubusercontent.com/6233682/130812419-35d19d8b-2f3b-4251-9581-8f6bc4abe52f.png)

Fish doesn't do this, making it a bit harder to quickly spot the item you're looking for:
![image](https://user-images.githubusercontent.com/6233682/130812547-964f236e-d088-4d21-9284-8455eb0d0ddd.png)

It would be cool if this could be supported.

**Comment by faho** [comment]
This didn't get any traction and the dircolors format is, well, "miserable".
