### ISSUE TITLE
set -x in fish?

### ISSUE THREAD

**Issue by DimanNe** [fish-shell/fish-shell#8255]
I have read this issue - [Strict mode options](https://github.com/fish-shell/fish-shell/issues/805), but the discussion there is about, "strict mode", which should stop execution as soon as possible (like `assert`s in C++).

My question (and use-case of `set -x`) is **debugging and understanding** of what is going on. So, a script might be working perfectly fine, I just want to understand what it does.

Any ideas / suggestions / plans?

**Comment by DimanNe** [comment]
# [Answer](https://github.com/fish-shell/fish-shell/issues/3427#issuecomment-610048527)
```
set fish_trace 1    # print the expanded commandline before execution
set fish_trace 2    # prefix the commandline with file and line number

set fish_trace 1 1  # print the commandline before execution, 
                    #   and print its exit status after execution
set fish_trace 1 2  # as above, but print the exit status of all subprocesses (?)

set fish_trace 0 1  # only print the exit status of commandlines
```

**Comment by faho** [comment]
>set fish_trace 1 1  # print the commandline before execut

This was proposed by someone, and was not implemented, and will not be implemented in that manner.

The only thing that is currently implemented is `set fish_trace 1`.
