### ISSUE TITLE
Don't treat out-of-bounds differently than undefined variables

### ISSUE THREAD

**Issue by Undeterminant** [fish-shell/fish-shell#826]
`set a b; echo $a[1]` yields `b`, while `set a b; echo $a[2]` yields the error `fish: Could not expand string “$a[2]”`.

Meanwhile, `echo $a[2]` without setting anything simply yields an empty string. This seems kind of like an odd behaviour, and there's no reason that there should be an error if you go out of bounds on an array when there isn't one for undefined variables.

**Comment by Profpatsch** [comment]
At the moment I use the following pattern:

```fish
function findia --description 'find case insensitive anywhere (globbing)' --argument search
        # prevent out-of bounds if only one argument
        if set -q argv[2]
          set more $argv[2..-1]
        end

        command find -iname "*$search*" $more
end
```

**Comment by Profpatsch** [comment]
But isn’t that exactly what `shift` is normally for?

**Comment by cben** [comment]
> In current master the set vs unset variable inconsistency is gone.
> $a[2] is an error when $a doesn't exist just as it is when $a does exist and has 0 or 1 elements.
> $a[1] is always valid even if $a has zero elements, primarily because it's just too annoying to have that be an error.

I just encountered that and was *very* perplexed.
`$argv[1]` and `$argv[2]` behaving differently goes against everything I expected from fish.
Why?
Is the goal to preserve some kind of `$a` == `$a[1]` equivalence (which holds for single element vars but here we're talking 0-element)?

IMHO it's fine that `$unset` == `$empty` == zero words but `$empty[1]` and `$unset[1]` should be errors.

What surprised me even more was that `(count $unset[1])` == `(count $empty[1])` == 0.
When `$anything[k]` is not an error, for any k, I expected it to still be 1 (empty) word, not 0 words.
Example where 0 words is risky:

    set dist_dir $argv[1]
    mv foo.gz bar.sh $dist_dir
    # if $dist_dir is not provided, `bar.sh` will get overwritten.

However see (*) below.

----

As for ranges, +1 for Python-like behavior where [5] raises errors and [3..10] silently clips.  
Safely limiting "up to 10 first items" is much more useful than "first 10 or nothing".
And the splitting invariant `$a[..9] $a[10..19] $a[20..] == $a` is very neat.

----

**If the decision is to get rid of all out-of-bounds errors, I'm OK with that too, as long [1] and [2] are equivalent.**

(*) I do love the proposal that `$a[3..5]` == `$a[3 4 5]` == `$a[(seq 3 5)]`, which will all silently clip to existing elements iff non-existing `$a[5]` expands to zero words.  That's an extremely consistent mechanic, easy to explain and understand, which is worth a lot.

**Comment by krader1961** [comment]
I agree with @cben that Python semantics are desirable. Not least because they match most people's expectations and provide more consistent behavior.

**Comment by DavidPerezIngeniero** [comment]
+1 empty results for non-existing slices.

**Comment by artemruts** [comment]
After reading this thread I think I found what I needed.

```
echo $argv | read -l first second
test -n $fist; or set -l first "first default value"
test -n $second; or set -l second "second default value"
```

**Comment by krader1961** [comment]
@artemruts Due to quirks of the `test` command mandated by POSIX you should always quote the arguments passed to the `-n` or `-z` subcommands; e.g., `test -n "$first"`. Also, FWIW, an alternative that is in some sense more idiomatic for the fish shell is to do `set -q first[1]; or set -l first "first default value"`.

**Comment by artemruts** [comment]
@krader1961 Thanks for sharing your knowledge! Refactored my functions.

**Comment by tmccombs** [comment]
I would love to see this, or even a builtin function that returns an array of all but the first elements of an array
