### ISSUE TITLE
Theme demo needs to be adjusted so that only unmatched quote is an error

### ISSUE THREAD

**Issue by haoadoresorange** [fish-shell/fish-shell#8260]
**Please tell us which fish version you are using by executing the following:**

  3.3.1

**Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.**

MANJARO #1 SMP PREEMPT Sun Aug 15 13:15:18 UTC 2021 x86_64 GNU/Linux
xterm-256color

**Tell us how to reproduce the problem. Including an asciinema.org recording is useful for problems that involve the visual display of fish output such as its prompt.**

The terminal's text color is incorrect when not closing quote.
* this is what's supposed to be (show up in fish_config)
![image](https://user-images.githubusercontent.com/22086462/131259022-76d7bb8d-1176-4556-984a-ea5ff8e4c1f3.png)
* this is the real result (only quote is colored)
![image](https://user-images.githubusercontent.com/22086462/131258994-a3540fb6-679c-445f-968f-33ef101955a6.png)

**Comment by faho** [comment]
Most likely:

Your terminal isn't detected as truecolor capable, so fish sends the colors as one from the palette, and you've set the palette to something else. We have no way to detect that or deal with it.

Either `set -g fish_term24bit 1`, which will make fish send the color as RGB, so the terminal can't mess it up. If that doesn't work, switch to a better terminal.

Or fix your palette so it lines up.

**Comment by haoadoresorange** [comment]
The thing is, the color doesn't come from the palette, it comes from fish as the color set for text in quote.
I'm running fish vanilla, so there is no 3rd party involved here.

**Comment by faho** [comment]
>The thing is, the color doesn't come from the palette, it comes from fish as the color set for text in quote.

No, if fish doesn't deduce that it can give the terminal 24-bit/truecolor/RGB sequences, then it can only give the color as one of the 256 colors from the palette, and the only way to do that is to map the color (which the colorscheme defines in RGB) to fish's idea of the terminal's colors (IIRC the default xterm palette), so it can then send a color sequence to the terminal.

Then the terminal gets that color, and picks from its palette again.

So: Either get it to do RGB, or fix your palette.

**Comment by haoadoresorange** [comment]
I will try it on another terminal. Do you have one that is guaranteed working ?

**Comment by page-down** [comment]
Sorry, I don't quite understand why it has to do with true colors or palettes. It seems to me that the issue mentioned here is the text after the single unmatched quotation mark, which should be recognized as an error, not the quoted text.

From the screenshot, you can see that the text color is rendered correctly as quoted text. (This refers only to the color.) The error section has only a single quote, but is also rendered correctly as the error color.

![](https://user-images.githubusercontent.com/57713011/131281616-b5dfa47e-ab9c-4dbb-9b12-4429eab38ec0.png)

Here is a screenshot where I have configured "fish_term24bit".

![](https://user-images.githubusercontent.com/57713011/131281671-ef9516b3-e28b-4d2e-a715-c92497e2665d.png)

The expectation is that unmatched quoted text should be recognized as an error, as shown in "fish_config".

If it can be correctly identified as an error, the color will not be a problem.

**Comment by faho** [comment]
Aaaah, okay, yeah: 822b53c67a70ff923ba0370d763e44532e2c4c44 (included in 3.1.0) made it so only the unmatched quote is an error.

We should adjust the highlighting in the browser to match.
