### ISSUE TITLE
Loading/unloading completions dynamically

### ISSUE THREAD

**Issue by jtojnar** [fish-shell/fish-shell#8261]
For [direnv](https://github.com/direnv/direnv) and other similar tools that modify current shell to place user into a transient development environment, it would be useful if we could dynamically load completions and then have a simple way to unload them. ([relevant direnv issue](https://github.com/direnv/direnv/issues/443))

Fish scans `XDG_DATA_DIRS` for vendor completions but, unlike bash-completion, it only does so at startup so when the devenv script is sourced and `XDG_DATA_DIRS` changes, fish will not notice the new completions.

We could have fish re-scan the directories in `XDG_DATA_DIRS` if the environment variable changes, load completions in the new directories and unload completions that disappeared. Or, if that would be too inefficient, we could have `FISH_ENVIRONMENT_COMPLETIONS` environment variable explicitly list the completion script paths.

**Comment by faho** [comment]
>Fish scans XDG_DATA_DIRS for vendor completions but, unlike bash-completion, it only does so at startup

It does not.

Fish loads completions whenever the completions are first *run*.

So if direnv gives you a new command, and you then try to tab-complete it, *that* is when fish will try to get the completions.

**Comment by jtojnar** [comment]
> > Fish scans XDG_DATA_DIRS for vendor completions but, unlike bash-completion, it only does so at startup
> 
> It does not.
> 
> Fish loads completions whenever the completions are first _run_.
> 
> So if direnv gives you a new command, and you then try to tab-complete it, _that_ is when fish will try to get the completions.

Sorry, I meant to say that the `vendor_completionsdirs` is [built at startup](https://github.com/fish-shell/fish-shell/blob/e01342214325a65ad056d196f3e0bcf473811c3c/share/config.fish#L63-L82) – as far as I could tell.

Which means that when I source a script that adds some directory to `XDG_DATA_DIRS` (either manually or through direnv), `fish_complete_path` is already fixed.

I guess I could tweak `fish_complete_path` but it being a fish variable instead of an environment variable would mean the variable restoration logic would need to be duplicated in the fish script, rather than just handling it with other variables in the program the fish script invokes.

And the question of unloading the autoloaded completions still remains – `complete -e` seems to unload all completions, not just those with matching arguments.

**Comment by faho** [comment]
>I guess I could tweak fish_complete_path but it being a fish variable instead of an environment variable would mean the variable restoration logic would need to be duplicated in the fish script

Yes, do that.

>And the question of unloading the autoloaded completions still remains – complete -e seems to unload all completions, not just those with matching arguments.

`complete -e -c command` erases the completions just for that command, but also removes them from autoloading.

I have no idea why you would want to *delete* completions. Is there an actual case where the completions become invalid, even if the command doesn't? Why not just keep them loaded?

**Comment by jtojnar** [comment]
> `complete -e -c command` erases the completions just for that command

I guess I misunderstood the [docs](https://fishshell.com/docs/current/cmds/complete.html#description) “When erasing completions, it is possible to either erase all completions for a specific command by specifying complete -c COMMAND -e, or by **specifying a specific completion option to delete**.” I thought if I just add `-e`, it will be selective but it removes everything: 

```
$ complete --no-files rcfg -a '(_rcfg_completionfoo)'
$ complete --no-files rcfg -a '(_rcfg_completion)'
$ complete rcfg
complete --no-files rcfg -a '(_rcfg_completion)'
complete --no-files rcfg -a '(_rcfg_completionfoo)'
$ complete -e --no-files rcfg -a '(_rcfg_completion)'
$ complete rcfg
```

I also tried removing the listing as printed but that did not do anything:

```ShellSession
$ complete -e "complete --no-files rcfg -a '(_rcfg_completion)'"
$ complete rcfg
complete --no-files rcfg -a '(_rcfg_completion)'
complete --no-files rcfg -a '(_rcfg_completionfoo)'
```

But that should probably be a separate issue.

> but also removes them from autoloading.

Hmm, that is inconvenient. Is there a way to unload the completions for given command without disabling autoloading for it?

> I have no idea why you would want to _delete_ completions. Is there an actual case where the completions become invalid, even if the command doesn't? Why not just keep them loaded?

In project-specific development environments that you activate by sourcing a script when entering the project directory, there can be project-specific programs e.g. `rcfg` above. When you switch to work on a different project and change into its directory, the project specific program might be completely different so you want to load its own completions.

**Comment by faho** [comment]
> Hmm, that is inconvenient. Is there a way to unload the completions for given command without disabling autoloading for it?

Currently not.

>there can be project-specific programs e.g. rcfg above

Why does rcfg not have one completion script that has the logic integrated?

E.g. `git <tab>` works not just in one repo, but all of them. Why does this need special treatment per-directory?

**Comment by jtojnar** [comment]
> Why does rcfg not have one completion script that has the logic integrated?
> 
> E.g. `git <tab>` works not just in one repo, but all of them. Why does this need special treatment per-directory?

Unlike `git`, the project-specific programs are not installed globally. They only exist inside a single project and a different project can have a completely different program with the same name. So in order to be good citizens, we need to clean up the completions just like we do with `PATH` and other environment variables on the environment tear down.

**Comment by jtojnar** [comment]
That unfortunately does not work as erasing completions will disable their autoloading. Also, ideally we would only remove specifically what we added in case user has custom completions in their fish config (we would not want to remove them, only disable them temporarily).

direnv does not support that [currently](https://github.com/direnv/direnv/pull/464), so I decided to do exactly that in a custom fish script that I source until we manage to integrate functions it into direnv’s changes record. But I am still unable to deal with unloading the completions.

**Comment by krobelus** [comment]
> That unfortunately does not work as erasing completions will disable their autoloading.

>  They only exist inside a single project 

I agree that the side-effect of disabling autoloading seems odd here but I doubt it's a real problem - you don't need autoloading if the commands only exist inside projects.

> modify fish_complete_path instead of directly calling complete

Yeah that doesn't fully work yet, for now you have to compromise.
If two directories define the same private command, then one solution is to eagerly load and unload completions.

Another solution is to add conditions to your complete statements. So you'd eagerly load something like
`complete scripts/foo -n 'test "$(git rev-parse --show-toplevel 2>/dev/null)" = /path/to/project'` when you enter the project, and never unload them.
That has cosmetic side effects, but do you really care?

To get rid of the lingering completions we'd need to allow erasing completions without adding a tombstone (which prevents autoloading) - that's doable, **however**, this:

> Also, ideally we would only remove specifically what we added in case user has custom completions in their fish config

sounds really complex, so I'd just go with the solution with the conditions. That won't interfere with autoloading the user config. Autoloading is just an optimization after all; you probably don't need it unless you're writing thousands of completions scripts.

**Comment by jtojnar** [comment]
> > Also, ideally we would only remove specifically what we added in case user has custom completions in their fish config
> 
> sounds really complex, so I'd just go with the solution with the conditions. That won't interfere with autoloading the user config. Autoloading is just an optimization after all; you probably don't need it unless you're writing thousands of completions scripts.

What if we could assign names to individual completions? That would allow us to specifically remove them just like functions.

**Comment by faho** [comment]
>What if we could assign names to individual completions? That would allow us to specifically remove them just like functions.

That's, uh, super involved.

@krobelus is right - just `source` the completions when you need them, and `complete --erase` them when you don't.

You also probably want `complete --path /full/path/to/your/script` instead of `complete -c script` in the definitions.

**Comment by jtojnar** [comment]
That might actually do exactly what I want. I assume `-e` would then only clear completions for this specific path. Will test later.

**Comment by jtojnar** [comment]
Can confirm `--path` works as expected.
