### ISSUE TITLE
Getting an error "cd: '/Users/x/Downloads/' is a rotten symlink"

### ISSUE THREAD

**Issue by elimist3** [fish-shell/fish-shell#8264]
Today I logged onto my machine and tried to `cd ~/Downloads`, but to my surprise fish returned an error `cd: '/Users/x/Downloads/' is a rotten symlink`.

It seems to originate from the `builtin_cd` function call [here](https://github.com/fish-shell/fish-shell/blob/master/src/builtin_cd.cpp#L112), however I can't tell what the reason is since my Downloads directory is not a symlink.

I'm able to cd into any other directory just fine and I'm able to access `~/Downloads` through MacOS's file explorer (Finder) so I don't think the directory is corrupt.

When I `chsh -s /bin/bash`, I'm able to `cd ~/Downloads` just fine!

My `config.fish` is just the default config, and I've already tried reinstalling Fish from my package manager (homebrew), to no avail.

**System info**
Fish version: 3.3.1
Operating system: MacOS 11.5.2, arm64
Terminal: Alacritty
Affected by third-party customizations: no, output is the same

I have a feeling this may be difficult to reproduce but I thought I'd put this out there just in case there is an easy solution to be found.

**Comment by krobelus** [comment]
The error message is misleading because `EROTTEN` is a fish invention that was removed in 7ac593273 ("Remove a bunch of dead code identified by cppcheck"). It is defined as 1, which matches [EPERM](https://opensource.apple.com/source/xnu/xnu-201.5/osfmk/libsa/errno.h.auto.html).
I'm not sure how you're getting a permissions error; `fchdir` should never set `EPERM`.
Maybe you've [allowed] bash to access files but not fish? I'm not sure.

```diff
diff --git a/src/builtin_cd.cpp b/src/builtin_cd.cpp
index 9d0fa6e58..1b1910fe2 100644
--- a/src/builtin_cd.cpp
+++ b/src/builtin_cd.cpp
@@ -108,9 +108,7 @@ maybe_t<int> builtin_cd(parser_t &parser, io_streams_t &streams, const wchar_t *
     } else if (best_errno == ENOENT) {
         streams.err.append_format(_(L"%ls: The directory '%ls' does not exist\n"), cmd,
                                   dir_in.c_str());
-    } else if (best_errno == EROTTEN) {
-        streams.err.append_format(_(L"%ls: '%ls' is a rotten symlink\n"), cmd, dir_in.c_str());
-    } else if (best_errno == EACCES) {
+    } else if (best_errno == EACCES || best_errno == EPERM) {
         streams.err.append_format(_(L"%ls: Permission denied: '%ls'\n"), cmd, dir_in.c_str());
     } else {
         errno = best_errno;
diff --git a/src/path.h b/src/path.h
index 852714b15..d7e1a0a5e 100644
--- a/src/path.h
+++ b/src/path.h
@@ -9,9 +9,6 @@
 #include "common.h"
 #include "env.h"
 
-/// Return value for path_cdpath_get when locatied a rotten symlink.
-#define EROTTEN 1
-
 /// Returns the user configuration directory for fish. If the directory or one of its parents
 /// doesn't exist, they are first created.
 ///
```

**Comment by kopischke** [comment]
@krobelus

> `EROTTEN` is a fish invention that was removed in 7ac5932

Not sure what happened after that commit 7 years ago, but `EROTTEN` is very much [alive and well in the current codebase code](https://github.com/fish-shell/fish-shell/search?q=EROTTEN&type=code).

**Comment by faho** [comment]
>Not sure what happened after that commit 7 years ago, but EROTTEN is very much alive and well in the current codebase.

It isn't *set* anymore since 7ac5932, and never returned since even before that.

That's why @krobelus included the patch that removes it entirely - which should be merged (except it should also be removed from the comment below).

**Comment by faho** [comment]
>I'm not sure how you're getting a permissions error; fchdir should never set EPERM.

@krobelus The errno comes *either* from fchdir, or the `wopen_cloexec` (i.e. `open`) before. [open(2)](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/open.2.html) is also not documented to set EPERM.

**Comment by elimist3** [comment]
[Solved](https://stackoverflow.com/a/69023975/7467314). It seems to have been a simple permissions error, though I'm baffled as I've never fiddled with the access permissions of my terminal (Alacritty) and before, when I tried to debug the issue by cd'ing from MacOS's built-in Terminal.app, it also threw the same "rotten symlink" error. 

The solution on MacOS was just to go to System Preference -> Privacy -> Files and Folders and allow Alacritty (or whichever terminal you're using) to access the `Downloads` folder.

Thanks everyone!
