### ISSUE TITLE
Ellipsis character (…) in prompt causes cursor/input field to start one column further to the right.

### ISSUE THREAD

**Issue by fwr-ml** [fish-shell/fish-shell#8267]
G'Day

fish, version 3.3.1
Linux [hostname] 5.13.12-artix1-1
xterm-256color; in Konsole and Yakuake

I modified the prompt function to append the ellipsis everywhere a directory name in the current path got truncated. For every ellipsis there's one more extra space character between the end of the prompt and were the cursor is put/the input field starts (I tested, replacing every dir name by an ellipsis, cd-ing around, counting spaces).

My guess would be the ellipsis character is two bytes wide, and at some point where cursor placement gets decided the length of the prompt in bytes is used instead of the length in characters. ?

I'd try to debug it, but time …

My prompt funtion:
```
    set -l last_pipestatus $pipestatus
    set -l normal (set_color normal)

    # Color the prompt differently when we're root
    set -l color_cwd $fish_color_cwd
    set -l prefix
    set -l suffix '>'
    if contains -- $USER root toor
        if set -q fish_color_cwd_root
            set color_cwd $fish_color_cwd_root
        end
        set suffix '#'
    end

    # If we're running via SSH, change the host color.
    set -l color_host $fish_color_host
    if set -q SSH_TTY
        set color_host $fish_color_host_remote
    end

    # Write pipestatus
    set -l prompt_status (__fish_print_pipestatus "[" "]" "|" (set_color -o $fish_color_status) (set_color -o $fish_color_status) $last_pipestatus)

    if test -n "$prompt_status"
#        echo (set_color -o $fish_color_status) '╰─> ⬊ ⤷ ⤿ ⮡ ⮱ ↳ ↪ ⮩' $prompt_status (set_color -o $fish_color_status) '⏎' $normal
        echo (set_color -o $fish_color_status) '⮩' $prompt_status $normal
        echo
    end

    set -l prompt_pwd
    if set -q fish_prompt_pwd_actual_dir_length_limit
        and test "$fish_prompt_pwd_actual_dir_length_limit" -ge 1
        set -l limit $fish_prompt_pwd_actual_dir_length_limit
        set -l cutto 3
        if test "$limit" -lt 4
            set cutto (math $limit - 1)
        end
        if test "$cutto" -ge 1
            set limit (math $limit - $cutto + 1)
            set prompt_pwd (string replace -ar '([^/]{'"$cutto"'})[^/]{'"$limit"',}/' '$1…/' \
                (prompt_pwd))
        else
            set prompt_pwd (string replace -ar '([^/])[^/]*/' '$1/' (prompt_pwd))
        end
    else
        set prompt_pwd (prompt_pwd)
    end

    set -l prompt_head (string sub -l 1 $prompt_pwd)
    set -l prompt_tail (string sub -s 2 $prompt_pwd)

    echo -n -s \
        (set_color $fish_color_user) "$USER" $normal \
        (set_color $fish_color_prompt_delimiter) @ $normal \
        (set_color $color_host) (prompt_hostname) $normal \
        (set_color $fish_color_prompt_delimiter) $prompt_head $normal \
        (set_color $color_cwd) $prompt_tail $normal \
        (fish_vcs_prompt) $normal \
        $suffix " "
```

Regards

**Comment by faho** [comment]
The character U+2026 HORIZONTAL ELLIPSIS (…)  is classified by unicode as an "ambiguous" width character. Those can be displayed as either 1 or 2 cells wide in a terminal, depending on the terminal's choice (frequently, this is also a configuration option just to make things extra annoying).

In Konsole, by default, it is displayed as 1 cell wide (and so far I haven't found a setting). Because there is no way for the terminal to communicate this width to fish, there is a setting called $fish_ambiguous_width, which can be set to 1 or 2.

So:

```fish
set -g fish_ambiguous_width 1
```

**Comment by fwr-ml** [comment]
Thanks. I didn't know that. Odd stuff.
I added "SETUVAR fish_ambiguous_width:1" to my fish_variables file and after starting Konsole anew ">   echo $fish_ambiguous_width" gives "1", but the reported behaviour persists.

**Comment by faho** [comment]
What is the output of

```fish
locale
```

**Comment by fwr-ml** [comment]
Hm. For I installed the system on the Intel Optane part of the storage module, I wanted to safe space and followed some guide from the Arch wiki to make pacman skip most of the locales, when installing packages. Aside from perl complaining, whenever run, the asked for output is the following:
```
>   locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
LANG=en_US.UTF-8
LC_CTYPE=
LC_NUMERIC=
LC_TIME=
LC_COLLATE=
LC_MONETARY=
LC_MESSAGES=
LC_PAPER=
LC_NAME=
LC_ADDRESS=
LC_TELEPHONE=
LC_MEASUREMENT=
LC_IDENTIFICATION=
LC_ALL=
>   fish_prompt | od -t x1z
0000000 1b 5b 33 38 3b 32 3b 32 35 35 3b 39 39 3b 32 30  >.[38;2;255;99;20<
0000020 6d 1b 5b 34 38 3b 32 3b 36 31 3b 33 33 3b 36 37  >m.[48;2;61;33;67<
0000040 6d 6d 69 63 68 61 1b 28 42 1b 5b 6d 1b 5b 33 38  >mmicha.(B.[m.[38<
0000060 3b 32 3b 32 35 33 3b 31 36 35 3b 39 33 6d 1b 5b  >;2;253;165;93m.[<
0000100 34 38 3b 32 3b 36 31 3b 33 33 3b 36 37 6d 40 1b  >48;2;61;33;67m@.<
0000120 28 42 1b 5b 6d 1b 5b 33 38 3b 32 3b 32 35 35 3b  >(B.[m.[38;2;255;<
0000140 39 39 3b 32 30 6d 1b 5b 34 38 3b 32 3b 36 31 3b  >99;20m.[48;2;61;<
0000160 33 33 3b 36 37 6d 66 77 72 2d 6d 6c 1b 28 42 1b  >33;67mfwr-ml.(B.<
0000200 5b 6d 1b 5b 33 38 3b 32 3b 32 35 33 3b 31 36 35  >[m.[38;2;253;165<
0000220 3b 39 33 6d 1b 5b 34 38 3b 32 3b 36 31 3b 33 33  >;93m.[48;2;61;33<
0000240 3b 36 37 6d 7e 1b 28 42 1b 5b 6d 1b 5b 33 38 3b  >;67m~.(B.[m.[38;<
0000260 32 3b 32 35 35 3b 39 39 3b 32 30 6d 1b 5b 34 38  >2;255;99;20m.[48<
0000300 3b 32 3b 36 31 3b 33 33 3b 36 37 6d 2f 44 6f 63  >;2;61;33;67m/Doc<
0000320 e2 80 a6 2f 50 72 6f e2 80 a6 2f 33 50 2d 46 61  >.../Pro.../3P-Fa<
0000340 73 74 2d 44 44 53 1b 28 42 1b 5b 6d 1b 28 42 1b  >st-DDS.(B.[m.(B.<
0000360 5b 6d 3e 20 0a                                   >[m> .<
0000365
>   echo \U2026 | od -t x1z
0000000 3f 0a                                            >?.<
0000002
```

**Comment by faho** [comment]
Yeah, your locale setup is broken.

I think you never generated the en_US.UTF-8 locale. Try running `locale-gen` as root. That should tell you it's generating `en_US.UTF-8`, and then the error that `locale` prints should be gone.

```fish
>   echo \U2026 | od -t x1z
0000000 3f 0a                                            >?.<
0000002
```

This isn't actually an ellipsis, it's a replacement character. Because the locale is broken, fish has no idea what an ellipsis is, because it can't figure out the text encoding.

**Comment by fwr-ml** [comment]
Thank you very much for taking the time and figuring this out. And for pointing me in the right direction.
It looks like I'll have to learn a bit about that locale infrastructure. locale-gen just errs out saying it failed to set de_DE.UTF-8. I'll see to it. Thanks.
