### ISSUE TITLE
error in prompt

### ISSUE THREAD

**Issue by Javi3y** [fish-shell/fish-shell#8269]
i have this problem when i'm in a folder with no directories in it and it's because my prompt how can i fix it
![Screenshot_2021-09-04_20-16-23](https://user-images.githubusercontent.com/74869077/132100355-5e4f0b13-3d6d-4642-b494-50fc1e850333.png)

**Comment by faho** [comment]
Please do read the error. You're passing a wildcard to `ls` that doesn't match.

Wildcards that don't match are an error except when used with `for`, `set` and `count`.

Since you just want to check the directories in the current directory, replace that `ls -dl */ | wc -l` with `count */`.

**Comment by Javi3y** [comment]
thanks alot i worked
