### ISSUE TITLE
Qutes in Comment breaks passing of groups

### ISSUE THREAD

**Issue by IsaacOscar** [fish-shell/fish-shell#8273]
The following code, which I expect to simpley print 'hello', gives a syntax error:

```
echo (echo hello # '
)
```

```
file.fish (line 1): Unexpected end of string, quotes are not balanced
echo (echo hello # '
)
     ^
```

The same issue happens with `# "`
It seems that a `'`  and `"` in a coment, contained within a `(...)` is always passed like a string delimiter, so the parser needs it to be balanced or escaped.

So the following is accepted:

```
echo (echo hello # " start
         echo world # escaped \"
         # end ")
  ```
  
Which prints `hello world` as expected, since the `"` mark at `start` is balanced by the one at `end`, and the `"` at escaped is preceded by a backslash, so it's ignored.

**Comment by faho** [comment]
Duplicate of #7866
