### ISSUE TITLE
status -n and status --current-line-number not useful and underspecified (was 4161)

### ISSUE THREAD

**Issue by rdw20170120** [fish-shell/fish-shell#8278]
I would like to reopen #4161, as I am finding the issue quite unresolved and quite problematic.

I am using Fish version 3.3.1 within iTerm2 3.4.9 running on Apple macOS 11.4 Big Sur.  I am also using Fish version 3.1.0 running within a Docker container hosting Ubuntu focal 20.04 LTS.

I have been using Fish as my primary shell and scripting language for several months now.  I am attempting to write some useful functionality to support DevOps, DevSecOps, and SRE automation.  My desire is to fail-fast and to provide useful information to the user for troubleshooting.

I attempted to use `status --current-line-number` in my code, and I find that it always returns line number `1`.  This is obviously useless.  All of the other syntax variants do the same (as expected).

I had written a simple `abort` utility function that I could use for reporting errors with relevant source location, but it is insufficient.  I was using `status --print-stack-trace` to get the source location, but the crucial information is typically not in the call stack (too many calls are left out).  I had hoped to augment my `abort` by passing in a source filename and line number from the caller.  I can get the source filename, but the line number is unavailable due to this broken feature.

I will now have to write a lot of code throughout my dozens of Fish functions and scripts to workaround the lack of a usable line number from this feature.  For the moment, I will have to call `status --print-stack-trace` in every location where I am about to abort execution (`exit` with a code > zero).  This means that it will be a BIG scalability problem, because I will potentially need to add this functionality to each new Fish function that I write.  This could make using Fish untenable for serious work.

I do NOT need `status --current-line-number` to distinguish between line numbering within a function versus line numbering within a file.  I highly recommend making it work with JUST the line numbering within the file, so that `status --current-filename` and `status --current-line-number` together provide a unique location within the user's codebase.

BONUS POINTS if you reproduce (with a much better implementation) Bash's ability to find the source file and line number at various levels of the callstack.  Then I would not have to pass the filename and line number as arguments through the various function calls.  Instead, I would love to be able to write a single utility function that could write out my error message (with color to stderr), print out the source file and line number from the top of the call stack, then `exit` with my chosen error code.

As I learn Fish, I readily anticipate and hope to be able to add this functionality to Fish myself.  But I am certainly not there yet.

Thank you for creating my new favorite system-scripting language.  I mostly write Python nowadays, but that is too heavy for glue logic and basic automation.  Fish allows me to cleanly bootstrap my Python environment, where things get SERIOUS.  :)

**Comment by faho** [comment]
> I was using status --print-stack-trace to get the source location, but the crucial information is typically not in the call stack (too many calls are left out)

What exactly is left out here? Do you have an example?

**Comment by rdw20170120** [comment]
Actually, I tried writing some tiny test scripts to illustrate, but then I ran into [issue 1035](https://github.com/fish-shell/fish-shell/issues/1035).  I tried to capture the stdout & stderr from my functions, but failed because that does not work with command substitutions (which are essential to my use case).

I spent several hours trying things, and hunting through issues here to hopefully understand the misbehavior that I was seeing.  The net result was that I discovered that Fish has a lot of warts under the hood, and that its maintainers are not very welcoming.

After several months of trying out Fish, I have realized that I need to go bark up a different tree.  Fish is not ready for "prime time".  With this kind of enmity, it looks like it will never get there.

I will restrict Fish to a very thin glue layer for my purposes, and work around its warts.  I will embrace a full-blown programming language and environment for most of my DevSecOps purposes, just as I had always planned but now earlier than I had anticipated.

As a system architect, I now realize that using Fish represents too much of a risk to my vision and goals.  While Fish is my best option for glue logic _for now_, I will have to work towards removing it in favor of something more solid amidst a community that is more welcoming.

_**These are not the shell that you are looking for...**_

**Comment by faho** [comment]
Okay, apparently you're unwilling or unable to explain what the actual issue is, so I'm closing this.

There is also no need to leave the same comment multiple times on multiple threads.

**Comment by rdw20170120** [comment]
I am unable to explain the issue because Fish makes it darn near impossible for me to capture its output suitable for illustrating the issue.  Yes, I reckon I could do screen captures and such.  However, the general lack of an open and welcoming attitude here leaves me unable to justify the effort I would have to expend.

Besides, there are already open issues for the various elements that seem to contribute to my issue.  I would just be repeating their assessments of these long-unaddressed issues.

The same comment applies because it is relevant to the stonewalling that I am generally receiving on each of my issues.  Anyone reading my comment on any of these issues needs a reasonably-complete context in order to have any chance at comprehending.  I cannot expect anyone to hunt for all my issues in order to piece together the context.
