### ISSUE TITLE
Check when entering/leaving a tui application

### ISSUE THREAD

**Issue by maxdevjs** [fish-shell/fish-shell#8279]
```yaml
fish, version 3.3.1
3.3.1
x86_64 GNU/Linux (NixOS)
xterm-kitty
```

I wonder if there is something that can help to check when entering/leaving a `tui` application (game, text editor, etc).

Rough idea:

```yaml
function preexec_test --on-event fish_preexec (?)
  if entering tui application
    do something
  end
  
end

function postexec_test --on-event fish_postexec (?)
  if leaving tui application
    undo something did in preexec_test
  end
end
```

- the `fish_preexec` probably is not useful in this case (alternatives?)
- could I check if the prompt is unshown (for a while) then shown again (how)?
- alternatives?
- ...

**Comment by faho** [comment]
Fish cannot detect if the application it is about to start is a TUI or not. This is simply not available in the terminal model.
