### ISSUE TITLE
alias command is slower than function

### ISSUE THREAD

**Issue by elentok** [fish-shell/fish-shell#828]
Hi,

I've switched to fish about a week ago,
I'm using oh-my-fish,
When I added my aliases (~80 aliases) I noticed that it takes about 2~3 seconds to open a new shell,

after changing every "alias {a}='{b}'" to "function {a}; {b}; end" the shell suddenly opened instantly.

slow aliases: https://github.com/elentok/dotfiles/blob/master/fish/aliases_slow.load.disabled

fast aliases: https://github.com/elentok/dotfiles/blob/master/fish/aliases.load

**Comment by faho** [comment]
This should be improved a bit by 54d1d98e39 and I don't see any low-hanging fruit anymore. Since I don't think we'll make alias a built-in, this is as good as it's gonna get.
