### ISSUE TITLE
OpenSUSE 15.3: Cannot not open database file '/usr/share/scout/bin-git.db'

### ISSUE THREAD

**Issue by mrjayviper** [fish-shell/fish-shell#8284]
I've searched the net and it seems to be a common theme with fish + OpenSUSE/derivatives.

Thanks
---------------
myuser@myhost ~> cd /mnt/storage/my-stuff/apps/apps-setup/
myuser@myhost /m/s/m/a/apps-setup> git Cannot not open database file '/usr/share/scout/bin-git.db'
 --: command not found
/usr/share/fish/completions/git.fish (line 154):
git config -z --get-regexp 'alias\..*' | while read -lz alias command _
^
from sourcing file /usr/share/fish/completions/git.fish
        called on standard input

in command substitution
        called on standard input

^C
myuser@myhost /m/s/m/a/apps-setup> fish --version
fish, version 2.7.1

**Comment by faho** [comment]
> fish, version 2.7.1

Fish 2.7.1 is from 2017and lacks about half the commits ever made to fish (iirc) , please upgrade to fish 3.3.1 and try again.

**Comment by faho** [comment]
Or, alternatively, just search for the error message, which will point you to #4447, which was fixed in fish 3.0.0, released in 2018.

**Comment by faho** [comment]
Duplicate of #4447
