### ISSUE TITLE
Reflection of color settings in iTerm

### ISSUE THREAD

**Issue by yamatsum** [fish-shell/fish-shell#8288]
I use fish with iTerm.
I also use starship.

The starship color uses the ANSI color set in iterm, but the fish prompt does not reflect the iterm color.

Is it possible to use the colors set in iterm?
![CleanShot 2021-09-13 at 00 29 08@2x](https://user-images.githubusercontent.com/42740055/132993489-c34be28b-72aa-471e-81aa-972ff5993838.png)
<img width="565" alt="CleanShot 2021-09-13 at 00 28 22@2x" src="https://user-images.githubusercontent.com/42740055/132993493-bbeb707e-6a4e-41c9-9630-dabbbbbf8d82.png">

**Comment by page-down** [comment]
Set the color to the names.

```shell
set -U -L | grep color

set -U fish_color_param brblue
set -U fish_color_error red
```

ANSI Colors are very limited, so perhaps consider setting the corresponding RGB values for fish directly.

You can achieve better results by setting fish to use the same color theme as starship (set the color values to the same true color RGB).

iTerm ANSI Color is only set as a fallback for other command line programs.

**Comment by yamatsum** [comment]
@page-down 
Thank you for the setting example
Limited colors are enough for me
However, I want to have no settings as much as possible, so I thought it would be nice to have an option that allows you to use ANSI colors from the beginning without having to set individual colors if possible.

**Comment by faho** [comment]
@yamatsum There's one setting: $fish_term24bit. This disables fish's use of 24-bit RGB truecolor, which makes it fallback on the 256 color palette.

```fish
set -g fish_term24bit 0
```

do that in config.fish.

**Comment by faho** [comment]
Question has been answered: Disable truecolor to get fish to use the palette. Since there hasn't been any activity here in over a week, I'm closing this.
