### ISSUE TITLE
Add syntax highlighting variable for command options

### ISSUE THREAD

**Issue by lokesh-krishna** [fish-shell/fish-shell#8292]
Would be nice to separately highlight the options that a command accepts, such as the `-` and `--` options instead of having it tied to `fish_color_param`.

**Comment by EmilySeville7cfg** [comment]
What about options that starts with `/`?

**Comment by daveyarwood** [comment]
I just upgraded to Fish 2.4.0 and gave this a try - works great! :tada: 

Just a heads up that the option is not yet documented on [this page](https://fishshell.com/docs/2.4/index.html#variables-color) of the Fish website.

**Comment by daveyarwood** [comment]
Aha! I was going off of search results, didn't realize I was looking at an
older version. Thanks!

**Comment by andmis** [comment]
Just saying -- https://github.com/fish-shell/fish-shell/issues/8503
