### ISSUE TITLE
After installing a prompt and restarting terminal, cursor offset from prompt

### ISSUE THREAD

**Issue by OmegaLambda1998** [fish-shell/fish-shell#8297]
`fish --version: fish, version 3.3.1`
`echo $version: 3.3.1`
`uname -a: Linux Archbox 5.14.3-arch1-1 #1 SMP PREEMPT Sun, 12 Sep 2021 20:51:34 +0000 x86_64 GNU/Linux`
`echo $TERM: xterm-kitty`

```
cat .config/fish/config
if status is-interactive
    function fish_greeting
        if type -q fastfetch
            fastfetch
        end
    end

    # Alias definitions
    alias l="lsd"
    alias v="nvim"

    # Environmental variables
    set VISUAL /usr/bin/nvim
    set EDITOR /usr/bin/nvim
    set SHELL  /usr/bin/fish
end
```

Everything works fine without any prompt installed:
![1631700142_grim](https://user-images.githubusercontent.com/20032885/133413819-6399895a-e6ad-43ea-b482-58659f8c922c.png)

Everything looks okay when I first install a prompt (in this case [pure](https://github.com/pure-fish/pure))
![1631700177_grim](https://user-images.githubusercontent.com/20032885/133413951-92fac133-c2d3-426a-abf9-340362a26064.png)

However when I close and open the terminal, there's suddenly a newline!
![1631700302_grim](https://user-images.githubusercontent.com/20032885/133414094-65383c52-0f6e-47e1-b46a-a1d2b53815b4.png)

Same again with [tide](https://github.com/IlanCosman/tide). When first installed:
![1631700426_grim](https://user-images.githubusercontent.com/20032885/133414414-e5e80f34-ca6c-480f-828c-b07857130546.png)

After closing and opening the terminal
![1631700448_grim](https://user-images.githubusercontent.com/20032885/133414494-bf96e32e-71ba-4207-86ad-0249a53980ce.png)

I have no other plugins installed. The issue still occurs if I get rid of the `neofetch` call

**Comment by faho** [comment]
Typically, what happens here is that the terminal and fish disagree on the width of a character. There are two cases this frequently happens:

- Characters that were widened in unicode 9, basically all emoji. This can be altered via $fish_emoji_width, but should already be okay on your system, which is new enough to know about Unicode 9 across the board, unless you configured your terminal to use the old widths
- Characters that don't have a set width. This can be altered with $fish_ambiguous_width. If it isn't set, this defaults to 1, you can try setting it to 2. This can (unfortunately, tbh) also be set terminal-side, with something like "ambiguous-width characters are narrow/wide".

So, try:

```fish
set -g fish_ambiguous_width 2
```

Alternatively it's possible that your locale isn't properly generated - see what `locale` outputs. If that spews errors or says LC_CTYPE is C or POSIX, your setup is broken and you need to regenerate your locale.

**Comment by faho** [comment]
Honestly, you want to try to narrow this down.

If you just make your own prompt:

```fish
function fish_prompt
    echo $PWD
    echo ">"
end
```

does that add a spurious newline?

If not, you probably want to talk to the pure/tide people.

**Comment by OmegaLambda1998** [comment]
Yup, after removing both `pure` and `tide` I now have:
![1631702323_grim](https://user-images.githubusercontent.com/20032885/133418956-6084cfea-fed7-4a21-9c58-35cc1bf3b5d4.png)

**Comment by faho** [comment]
Okay, what does `locale` say? How about `type fish_prompt`?

**Comment by OmegaLambda1998** [comment]
```
locale
LANG=en_AU.UTF-8
LC_CTYPE="en_AU.UTF-8"
LC_NUMERIC="en_AU.UTF-8"
LC_TIME="en_AU.UTF-8"
LC_COLLATE="en_AU.UTF-8"
LC_MONETARY="en_AU.UTF-8"
LC_MESSAGES="en_AU.UTF-8"
LC_PAPER="en_AU.UTF-8"
LC_NAME="en_AU.UTF-8"
LC_ADDRESS="en_AU.UTF-8"
LC_TELEPHONE="en_AU.UTF-8"
LC_MEASUREMENT="en_AU.UTF-8"
LC_IDENTIFICATION="en_AU.UTF-8"
LC_ALL=
```

```
type fish_prompt
fish_prompt is a function with definition
# Defined interactively
function fish_prompt
                _ksi_end_prompt
            
end
```

**Comment by OmegaLambda1998** [comment]
```
type _ksi_end_prompt
_ksi_end_prompt is a function with definition
# Defined interactively
function _ksi_end_prompt
            set --local cmd_status "$status"
            _ksi_original_fish_prompt
            set --global _ksi_prompt_state "prompt_end"
            _ksi_mark "B"
            return "$cmd_status" # preserve the value of $status
        
end
```

**Comment by faho** [comment]
Ah, lovely. I'm assuming running `fish_prompt; echo newline` shows the word "newline" on a separate line?

**Comment by OmegaLambda1998** [comment]
Yup:
```
fish_prompt; echo newline
/home/patricka
>
newline
```

**Comment by faho** [comment]
Please file [a bug against kitty](https://github.com/kovidgoyal/kitty/issues), its shell integration adds a newline here.

**Comment by OmegaLambda1998** [comment]
Submitted: https://github.com/kovidgoyal/kitty/issues/4032
