### ISSUE TITLE
Help in getting a variable joined with string by `string join`

### ISSUE THREAD

**Issue by Divkix** [fish-shell/fish-shell#8300]
Hey All!

First of all thanks for this amazing shell, just installed it for first time and am already in love with it!!

I'm trying to set my path using the 'set -x PATH (my custom command) $PATH', but I'm having issues to get the correct PATH.

**My System Info:**
Fish Version: `fish, version 3.3.1`
Operating System: `Manjaro WSL`
Output of 'echo $TERM': `Linux Inspiron5459 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 GNU/Linux`
Output of 'echo $TERM': `xterm-256color`

**What I want to do is:**
 - Export a Variable `WINDOWS_USER_NAME` as the output of command I used to get username using `cmd`
 - Use `string join` to join the parts of path
 - Prepend the joined string to PATH

**I'm using this in `config.fish` file:**
```
if status is-interactive

    # setup gpg tty
    export GPG_TTY='(tty)'

    # check if distribution is WSL or not
    # if yes, then add some things to PATH
    if string match -r -i -q "^(.+)-microsoft-standard-WSL2" -- (uname -r)

        # Get windows user directory
        set -gx WINDOWS_USER_NAME (string split -f2 -r -m1 \\ (/mnt/c/Windows/System32/cmd.exe /c echo %USERPROFILE%))

        # add vscode to path
        set -gx PATH (string join "" "/mnt/c/Users/" $WINDOWS_USER_NAME "/AppData/Local/Programs/Microsoft VS Code/bin") $PATH

        # clean mess made by cmd
        clear

    end

    # add yarn global bin
    set -gx PATH (yarn global bin) $PATH

    # set starship config
    export STARSHIP_CONFIG=$HOME/.config/.starship.toml

    # start starship prompt
    starship init fish | source

end
```

**Expected Result of `echo "$PATH"`:**
`/mnt/c/Users/Divkix/AppData/Local/Programs/Microsoft VS Code/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`

**What is actually happening:**
`AppData/Local/Programs/Microsoft VS Code/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games`

I'm guessing the issue is somewhere in `(string join "" "/mnt/c/Users/" $WINDOWS_USER_NAME "/AppData/Local/Programs/Microsoft VS Code/bin")` but don't know how can I fix it.

**Comment by faho** [comment]
Okay, let me reduce your guff:

```fish
        # Get windows user directory
        set -gx WINDOWS_USER_NAME (string split -f2 -r -m1 \\ (/mnt/c/Windows/System32/cmd.exe /c echo %USERPROFILE%))

        # add vscode to path
        set -gx PATH (string join "" "/mnt/c/Users/" $WINDOWS_USER_NAME "/AppData/Local/Programs/Microsoft VS Code/bin") $PATH
```

So you execute some windows cmd.exe script to get the "proper" user name, and then add it to $PATH.

First of all: This `string join` here is entirely unnecessary. This is just

```fish
 set -gx PATH "/mnt/c/Users/$WINDOWS_USER_NAME/AppData/Local/Programs/Microsoft VS Code/bin" $PATH
```

Secondly: Your issue is that windows natively ends lines with a carriage return (a `\r`). When you print this to the terminal, it will reset the cursor to the start. So you don't *really* have your windows user name, you have your windows user name and a stray character.

Change

```fish
set -gx WINDOWS_USER_NAME (string split -f2 -r -m1 \\ (/mnt/c/Windows/System32/cmd.exe /c echo %USERPROFILE%))
```

to

```fish
set -gx WINDOWS_USER_NAME (string split -f2 -r -m1 \\ (/mnt/c/Windows/System32/cmd.exe /c echo %USERPROFILE% | string trim -c \r))
```

**Comment by Divkix** [comment]
Oh you're right, no need for `string join`
I used the string join because that returned the string '/mnt/c/Users/Divkix' when I did not remove the stray character `\r`.
Didn't knew about the `\r` char, completely forgot it...

Thanks a lot for help!
