### ISSUE TITLE
On macOS, it is not possible to 'cd' into the created folder in a long path

### ISSUE THREAD

**Issue by page-down** [fish-shell/fish-shell#8301]
macOS 11.6
fish 3.3.1

The folder was successfully created in Fish Shell, but I can't access it.

For APFS, there is no listed length limit on file paths, except that the default apps on macOS limits the maximum length to 1024 bytes.

It is still possible to use the command line to access these long paths. However, Fish Shell is having problems getting into the folder.

Steps to reproduce:

```fish
mkdir /tmp/path-test && cd /tmp/path-test
mkdir 1(string repeat -n127 \U0001f41f)
cd 1*
mkdir 2(string repeat -n127 \U0001f41f)
ls
cd 2*
# At this point, an error is returned.
cd: File name too long
cd: Unknown error trying to locate directory '2🐟...'

cd 2(string repeat -n127 \U0001f41f)
# Same error reported as above.
```

The folder can be accessed normally with zsh 5.8, bash 3.2 that comes with macOS  and with bash 5.1 installed by homebrew.

```shell
% zsh --version
zsh 5.8 (x86_64-apple-darwin20.0)
% cd /tmp/path-test/1*/2*
% echo "hello" > test.txt
```

Fish Shell is still unable to access the folder.

```fish
fish> ls 2*
test.txt

fish> cat 2*/test.txt
fish: No matches for wildcard '2*/test.txt'. See `help expand`.
cat 2*/test.txt
    ^

fish> cat (find . -name "*.txt")
hello
```

**Comment by ridiculousfish** [comment]
This is difficult to fix. It sort of works in bash and zsh because they just use relative paths, but if you then run `cd $PWD` in those shells, they fail in the same way. I'm very reluctant to try to fix this; many things will break if $PWD is longer than PATH_MAX. I'm going to close as NTBF but it's a good find, thanks for filing.

**Comment by floam** [comment]
Some discussion of this in #9062 - I think this should work and get other knock-on-benefits, like no weirdness in unlinked dirs, less likely race condition type stuff, if path handling continues away from being unnecessarily absolute.
