### ISSUE TITLE
Fish crash running brew reinstall

### ISSUE THREAD

**Issue by j-f1** [fish-shell/fish-shell#8303]
```shellsession
$ fish --version; echo $version
fish, version 3.3.1
3.3.1
$ name -a; echo $TERM
Darwin jeds-mbp.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64
xterm-256color
```

I am not able to reproduce the issue, but here’s what happened:

```shellsession
$ brew reinstall do-not-disturb                                                            ● 1 ✚ 1
==> Downloading https://bitbucket.org/objective-see/deploy/downloads/DoNotDisturb_1.3.0.zip
==> Downloading from https://bbuseruploads.s3.amazonaws.com/c237a8d2-0423-4819-8ddf-492e6852c6f7/do
######################################################################## 100.0%
==> Uninstalling Cask do-not-disturb
==> Running uninstall script /usr/local/Caskroom/do-not-disturb/1.3.0/Do Not Disturb Installer.app/
Password:
libc++abi: terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument

[Process completed]
```

**Comment by faho** [comment]
>I am not able to reproduce the issue

Okay, so let's see if someone else can. If nobody manages in a week or so, let's close it as a fluke (because we can't do anything if we can't reproduce it).

**Comment by floam** [comment]
Please post the crash report? It should be in the console app. It will have a backtrace.

**Comment by floam** [comment]
@j-f1 can you find the Crash Report?

**Comment by j-f1** [comment]
Sorry, I missed this. It seems like the crash report got deleted somehow, since it’s not visible in Console (or in `~/Library/Logs/DiagnosticReports`). Closing for now, but if I encounter this again I’ll try to remember to reopen the issue and upload the crash report right away.
