### ISSUE TITLE
Bracketed Paste Function Issue

### ISSUE THREAD

**Issue by HawkinsT** [fish-shell/fish-shell#8304]
**Fish Version:** 3.3.1
**OS:** Ubuntu 20.04.3 LTS on Windows 10 x86_64 (via wsl2)
**Terminal Emulator:** Alacritty (Windows)

**Issue:** I've just upgraded to Fish 3.3.1 from 3.1.0-1.2 and found that a bug seems to have been introduced (downgrading back to 3.1.0-1.2 confirms this issue doesn't occur in the older version). Seemingly at random `[?2004l` or `[?2004h` will be prepended to or overwrite the first few characters of my console output. Sometimes these strings are also truncated (e.g. `4l`). This happens about one in every 20 times I issue a command and seems to happen at random, with `[?2004l` being far more common to see than `[?2004h`. This bug is still present without third party customizations (via `sh -c 'env HOME=$(mktemp -d) fish'`). This issue does not occur when using Windows Terminal Preview.

**Reproduce:** Spam anything, e.g. `cd ~` or `fish --version`, and about 1/20 times you'll see output like `[?2004hersion 3.3.1` or `[?2004lfish, version 3.3.1` instead of `fish, version 3.3.1`.

**Comment by faho** [comment]
This is a known issue with some windows terminals, see #8240.

Fish just writes the sequence, and the terminal doesn't understand it, even tho the linux and mac versions do. It needs to be fixed in the terminal.

**Comment by faho** [comment]
https://github.com/microsoft/Terminal/issues/395

**Comment by HawkinsT** [comment]
Thanks, I'll see about reporting this to alacritty then.
