### ISSUE TITLE
no symbol on prompt

### ISSUE THREAD

**Issue by ismaelct** [fish-shell/fish-shell#8307]
fish, version 3.3.1 3.3.1

Linux aula110-126 5.11.0-34-generic #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux //
 xterm-256color

the problem is when i want to use agnoster theme it doesnt show the arrows and symbols
![](https://i.imgur.com/bkxuWGm.png)

**Comment by ismaelct** [comment]
Another problem now is that aftar running " sh -c 'env HOME=$(mktemp -d) fish' " my prompt doesnt show the themes correctly
Sorry im a newbie in shells and my english is a bit off

**Comment by krobelus** [comment]
What do you expect? Do you mean the arrows from the Git prompt? They only show up when you are inside a Git repository.
Anyway, this sounds more like an issue for https://github.com/hauleth/agnoster, not fish

> my prompt doesn't show themes correctly

that's the point of changing HOME, to not load any user specific configuration. You can install the theme in the temporary home of course
