### ISSUE TITLE
HOW TO DISABLE `fish_hybrid_key_bindings` !

### ISSUE THREAD

**Issue by arthurkiller** [fish-shell/fish-shell#8312]
HOW TO DISABLE `fish_hybrid_key_bindings`
I can not use ctrl-p any more after call this function

**Comment by faho** [comment]
You... uh, simply reset your keybindings?

`fish_default_key_bindings`

Also please note that using ALLCAPS like that comes across as shouting and rude.

**Comment by arthurkiller** [comment]
That bothers me a lot,  maybe this should be added to documents.

**Comment by arthurkiller** [comment]
I have checked for documents about `fish_hybrid_key_bindings ` and there is nothing about how to disable it.
