### ISSUE TITLE
"echo --" only emits a \n

### ISSUE THREAD

**Issue by badp** [fish-shell/fish-shell#8313]
* fish --version: 3.3.1
* uname -a: `Linux ****-Latitude-7300 5.11.0-34-generic #36~20.04.1-Ubuntu SMP Fri Aug 27 08:06:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
* $TERM: screen-256color, xterm-kitty
* Reproducible with sh -c 'env HOME=$(mktemp -d) fish'

I would have expected these three commands to behave identically, but they don't: 

```
$ echo -- | hexdump -c
0000000  \n                                                            
0000001
$ echo -n --\n | hexdump -c
0000000   -   -  \n                                                    
0000003
$ echo -ne '--\n' | hexdump -c
0000000   -   -  \n                                                    
0000003
```

What made me stumble upon this was:

```
echo -- | cat - filelist | git log --stdin
```

...where the '--' is necessary for git to know we're passing in file names and not commit references.

This isn't, strictly speaking, a bug; this behavior is documented (`help echo`). So I'm adding this mostly for documentation to the next poor soul that stumbles upon it.

**Comment by faho** [comment]
>So I'm adding this mostly for documentation to the next poor soul that stumbles upon it.

It already *is* in the documentation? So you're opening an issue after reading the documentation for documentation? I'm afraid the documentation is the documentation, not the issues. The issues are issues.

Please don't open issues like this.

**Comment by faho** [comment]
In general, please do keep in mind that opening an issue here notifies about 278 people, some of whom have to read the issue at the very least to see it's not a troll that needs to be moderated.

**Comment by badp** [comment]
I apologize for the noise, I didn't realize so many people were subscribed to all issues. In my defense, my first reaction when stumbling into this behavior was that this was a bug. I only discovered it was actually a documented feature of the echo built-in shortly before hitting submit as I kept prodding and digging.

I could argue that `echo --` should be special cased, but I won't; that would only introduce more surprises. Now people know that this is a WONTFIX.

**Comment by faho** [comment]
>I could argue that echo -- should be special cased, but I won't; that would only introduce more surprises. Now people know that this is a WONTFIX.

This is not just a WONTFIX, this is itself **a fix**.

How exactly would you print `-n` without a newline after it if you couldn't do `echo -- -n`?

And if `echo --` was special-cased, what happens with `echo -- $variable` if $variable is empty? Right, it would suddenly print `--`.

Like I said: `--` being an option-separator is a general thing, it's not a fish invention, it's one of those things you just have to get used to.
