### ISSUE TITLE
`fish_config choose` leaves previous right prompt in place

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#8314]
when switching to a prompt without a right prompt, after a prompt with a `fish_right_prompt`, you get a nasty result.

e.g.:
```
$ fish_config prompt choose disco
$ fish_config prompt choose default
```
<img width="717" alt="Screen Shot 2021-09-24 at 9 45 08 AM" src="https://user-images.githubusercontent.com/291142/134711565-479c2695-29a5-4e4c-8028-56f6e7bc4330.png">

**Comment by floam** [comment]
It's a UX nightmare.

**Comment by floam** [comment]
It's wacky "default" can't return the user to the default state, and I suggest we find a way to prevent users entering these weird intermediate states shown in my screenshot while trying prompts. It should be possible to distinguish a right prompt set by fish_config from something a user added on their own, or possible to set a uvar with the prompt selected.

**Comment by floam** [comment]
I guess I won't reapply the bug label. What do other @fish-shell/contributors think?

**Comment by faho** [comment]
>It's a UX nightmare.

Awww, come on, that's a tad dramatic.

**Comment by floam** [comment]
We could prompt the user and ask them if they would like to affect both sides, yes or no.

**Comment by faho** [comment]
Oh please no, constant prompts are also awkward.

**Comment by floam** [comment]
As it is, the user needs to find and delete a file to actually switch back to something else after trying a prompt that provides both left and right, that's kinda awkward.

**Comment by floam** [comment]
> Especially given that we'd want this to be available in config.fish

Why?

**Comment by floam** [comment]
It does a funcsave just like the HTML interface, correct? That should not be necessary.

**Comment by faho** [comment]
Really, my case for keeping whatever right prompt is this:

1. It's easier to write
2. It allows you to set a right prompt, then pick a left prompt to go with it, to augment it. Or even, yes, to pick the right prompt from one and leave it?
3. Erasing the right prompt or setting it after is easy
4. If you're just doing it interactively, you can always simply restart the shell. That's easy and fixes *everything*, so we want to encourage it.

I'm sorry, but I really don't enjoy having things I worked hard on, months ago, that were open for comments for a while *then*, to be called "a UX nightmare".

> Especially given that we'd want this to be available in config.fish

Why?

So you can do `fish_config prompt choose disco`, and it will select the disco prompt, and keep tracking the new version! We've had issues with the old one sticking around.

Plus there is literally no reason not to.

>It does a funcsave just like the HTML interface, correct? That should not be necessary.

`choose` does not. It simply `source`s, temporarily. That's what `save` is for.

**Comment by floam** [comment]
> So you can do fish_config prompt choose disco, and it will select the disco prompt, and keep tracking the new version! 

I do think tracking the newest version is valuable, but I don't really think we want to require people to make a configuration file. How about remembering the prompt name in a uvar and setting it in one of our initialization functions if the user hasn't customized it? Kinda like keybindings.

I'm sorry, I didn't mean to be rude. I don't really know the history of this feature. I'm glad a CLI interface to the web config is being added.

**Comment by floam** [comment]
> choose does not. It simply sources, temporarily. That's what save is for.

Hm, ok. I was unaware. How about `try`?

**Comment by faho** [comment]
>How about remembering the prompt name in a uvar and setting it in one of our initialization functions if the user hasn't customized it?

We... uh, want to move away from uvars (#7379).

That's also much more brittle and annoying than, you know, simply doing the same thing.

**Comment by faho** [comment]
>Hm, ok. I was unaware. How about try?

I'm sorry, that would have been great months ago before it was released [in fish 3.3.0](https://github.com/fish-shell/fish-shell/releases/tag/3.3.0). I do not want to change this or add another name for it *now*.

**Comment by mqudsi** [comment]
Could we just have `default` specify an empty right prompt with the logic that choosing the default is akin to resetting? I do think the current behavior is a tad confusing in that regard, since you don't end up with what you might intuitively expect the "default" to be after that operation.

**Comment by faho** [comment]
>Could we just have default specify an empty right prompt with the logic that choosing the default is akin to resetting?

That's inconsistent and I don't think running

```fish
fish_config prompt choose disco # or another prompt with a right component
fish_config prompt choose default # to reset it
fish_config prompt choose nim # a prompt without a right component
```

is super intuitive.

**Comment by faho** [comment]
Let's just do the thing that apparently other people think is better.

I still don't agree, but I don't have a desire to squabble over minutia like this.
