### ISSUE TITLE
Private use area codepoints are not read properly

### ISSUE THREAD

**Issue by blyxxyz** [fish-shell/fish-shell#8316]
This has to do with the direct encoding scheme (like #7723) but I couldn't find any open issues that covered it.

A unicode escape code in the F600-F6FF range is interpreted as the raw byte you get by subtracting `ENCODE_DIRECT_BASE`. For example:

```console
> echo \uF661
a
```
(`'a' == 0x61`)

The same happens when the raw codepoint is received by `read`:

```console
> /bin/printf '\uF661' | read
a
```

Or when the escape code is interpreted by fish's builtin `printf`:

```console
> printf '\uF661\n'
a
```

Relatedly, I don't seem to be able to paste these codepoints into the prompt. Pasting `ab` (`\uF5FF`) works as it should but if I paste `ab` (`\uF600`) only `ab` is inserted.

Capturing does work:
```console
> echo (/bin/printf '\uF661')

```

(This was found while fuzzing another piece of software, it's not causing me real-world problems.)

**Comment by faho** [comment]
Sorry, but this probably won't be changed.
