### ISSUE TITLE
Request: afterthought command lines

### ISSUE THREAD

**Issue by lucmp** [fish-shell/fish-shell#832]
First, let's suppose I like to initiate a download and be notified when the download is over. But as it turns out, I forgot to add the notification command:

$ wget http://somesite.com/somefile

Regretful, I can abort the download and reinitiate it the way I should have:

$ wget -c http://somesite.com/somefile; play /some/sound/file.wav

But maybe the shell could help me out in this kind of situation. I would like to be able to run:

$ wget http://somesite.com/somefile

then press some shortcut while wget is running, which would, I don't know, perhaps open another line somewhere where I would enter

$ play /some/sound/file.wav

So the 'play' command (and subsequent lines if they exist) would be executed as soon as 'wget' exited.

Of course, wget and play are just examples. It could involve many others. Right now, I am waiting for a very large 'tar' job to finish, but I find myself in this situation more often with wget.

**Comment by krader1961** [comment]
As already pointed out fish, like most UNIX shells, allows you to put a job into the background. At that point you'll be told by fish when the backgrounded job completes. For example, type `sleep 10` then press [ctrl-Z] then `bg`. Wait a few seconds and you will see `'sleep 10' has ended`. Anything more than that is a personal preference, and likely to be system dependent (e.g., `play` doesn't exist on macOS).
