### ISSUE TITLE
Fish does not respect #!/usr/bin/env shebang

### ISSUE THREAD

**Issue by lordlycastle** [fish-shell/fish-shell#8322]
If you have the following script:

```sh
#!/usr/bin/env sh
who_am_i=$(whoami)
echo $who_am_i
```

Fish shell trying to run this as a `fish` script when invoked and complains about the syntax.
```sh
fish ./script.sh
```

Other shells like `bash`, `sh`, & `zsh` run the script with the command found using the `/usr/bin/env sh`.

I see there is a related issue #843 but that is more about supporting shebang lines without `#!/usr/bin/env <command>` syntax, as far I can understand.

Can we get this feature in `fish` so I don't need to use `bash /os_agnostic_script.sh` instead?

**Comment by faho** [comment]
>Other shells like bash, sh, & zsh run the script with the command found using the /usr/bin/env sh.

This is, quite simply, incorrect:

```fish
#!/usr/bin/env fish
set -l foo bar
echo $foo
```

Run that with `bash t.fish` and you'll get:

```
t.sh: line 3: set: -l: invalid option
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
```

The only reason this *appears* to work is because those shells can all read sh scripts.

You can either make the script executable and run it via `./path/to/script` or you'll have to specify the interpreter.

**Comment by lordlycastle** [comment]
You're right. I did not try it the other way around and it does fail like you say.

Thanks for clearing that up!
