### ISSUE TITLE
Hanging in specific git folder

### ISSUE THREAD

**Issue by sam-cogan** [fish-shell/fish-shell#8324]
Just installed Fish for the first time on Debian Buster inside WSL, version 3.1.2. This has been working fine, until I tried to browse into a specific folder that container a git repo. When I do anything in this folder Fish hangs for 2-3 minutes before doing anything. Other folders are fine, even other git repos.

This is a new install of Fish, with just OMF installed and a theme configured.

**Comment by krobelus** [comment]
sounds like a third party issue in your theme or in [OMF](https://github.com/oh-my-fish/oh-my-fish)

If a plugin has set your [`$__fish_git_prompt_show_informative_status`](https://fishshell.com/docs/current/cmds/fish_git_prompt.html) in universal scope, then you might need to remove that with `set -e` (or just remove `~/.config/fish/fish_variables`)

**Comment by orcinus** [comment]
How is this a solution? This is like a person complaining their wheel falls off when backing up into a driveway, and you responding with "that seems like an issue with your driveway - you might need to not ever back into driveways" :)

**Comment by faho** [comment]
If oh-my-fish does something that is slow, that's an issue in oh-my-fish, and should be reported there.

Unfortunately oh-my-fish is [unmaintained](https://github.com/oh-my-fish/oh-my-fish/issues/788) and so your best solution is to just not use it.
