### ISSUE TITLE
Multiple word prefix history search

### ISSUE THREAD

**Issue by lallulli** [fish-shell/fish-shell#8328]
I would like to suggest to add support for multiple prefix history search. The algorithm would:

1. Break up the input string into words P1, P2, ..., Pn
2. Look for commands in history that contain all the words P1, ..., Pn as _prefixes_ of words in command (possibly in the same order)

For example, typing `dock r dj` would propose the command `docker-compose run django bash` if it has been previously issued.

Thanks!

**Comment by krobelus** [comment]
This would be a middle ground between normal autosuggestions/history search and a fuzzy search of the history.
It might work well for specific scenarios but in others the default substring search is better. It's hardly worth for the average user to remember multiple different key bindings.
Anyway, it should be possible to implement some version of this as a plugin. But why not just use history search provided by fzf?
So I'd rather not add this hard-coded behavior. We do ship `history-prefix-search-backward` in addition to the default search but I'd rather get rid of that and expose enough information so it can be implemented as a fish function.

**Comment by lallulli** [comment]
Thank you for your suggestion. Maybe multiple prefix search would be a nice feature to explore for autosuggestion. But I agree that fzf provides a great alternative based on key binding.
