### ISSUE TITLE
why my fish shell version 3.2.2 can't user jump command?

### ISSUE THREAD

**Issue by fx999** [fish-shell/fish-shell#8331]
my fish shell version is 3.2.2
my os is alpine-linux 3.14
I can use fish shell very well ,but can't use autojump command , jump or j  all error
error message :"fish: Unknown command: j"

**Comment by krobelus** [comment]
autojump is a third-party plugin, please try reinstalling it
alternatively, maybe setting CDPATH makes `cd` good enough for you? see https://fishshell.com/docs/current/cmds/cd.html

**Comment by fx999** [comment]
Allow a command to include history as a completion source #4344

Perhaps for fish 3.0 we can include support for a completion script to indicate that its completions should come from fish's history file, so that tabbing would provide a list of matches from history. A lot of commands do not have local file completions, but are often used and reused from within a certain set of arguments, this would be a huge convenience for such commands.

To illustrate with a real-life example, I use autojump religiously (aliased to j as their setup routine does automatically under all supported shells). j watches your directory changes and learns what directories you use, so that when you type in - from any CWD - j foo it will take you to the directory you use most often that matches search pattern foo (even if foo is misspelled, an abbreviation, etc).

What would be amazingly convenient is if my previous usage of j were to be considered potential completions. So when I type in j f<TAB>, history entries such as j fish and j fish-shell could provide completions for the current command line, and the completions suggestions would list fish and fish-shell as options.
