### ISSUE TITLE
Export `$fish_private_mode`

### ISSUE THREAD

**Issue by kidonng** [fish-shell/fish-shell#8332]
fish 3.3.1

Initial motivation is trying to [implement a "private mode icon" in tide](https://github.com/IlanCosman/tide/issues/157#issuecomment-864507620), a prompt using child shells to render asynchronously. Since the `$fish_private_mode` variable is set to unexported when using `fish --private`, some modifications to other parts of tide becomes necessary, instead of as a standalone module.

Recently I've be thinking that, is Fish's private mode more like browser's Incognito windows? Maybe it will better is `$fish_private_mode` is exported, therefore:

- Child shells enter private mode automatically, just like links in Incognito windows still open in Incognito windows by default.
- Other programs can read this variable to tweak their behavior, such as not recording any history, just like Fish. I've seen some Fish plugins does this but it is just limited to Fish plugins (because the variable is unexpected, obviously).

Some other thoughts:

- This is not a "backwards-compatible" change, however I can't think of a reason to dependent on the current behavior either (i.e. child shells won't follow parent's private mode).
- Should we provide a way to "exit" private mode? I don't think it is necessary, users can just erase `$fish_private_mode`.

**Comment by krobelus** [comment]
That's an interesting idea but it feels wrong to export a fish_* variable so I would avoid this as long as there is no strong motivation. A prompt can easily work around this.

**Comment by kidonng** [comment]
You are right, unless we introduce some `$FISH_PRIVATE_MODE` and repeat the problems with `$version` and `$FISH_VERSIOM`.

So I agree the issue in tide should be resolved independently. As for myself, I will use `set -q fish_private_mode && set -x fish_private_mode $fish_private_mode`.
