### ISSUE TITLE
Nested abbreviations?

### ISSUE THREAD

**Issue by tamis-laan** [fish-shell/fish-shell#8345]
What about nested abbreviations:
``` fish
abbr -a tree 'tre'
abbr -a lt 'tree | less -ar'
```
`lt` should transform to `tree | less -ar` should transform to `tre | less -ar`.

**Comment by faho** [comment]
This seems like an overcomplication.

Simply make the first `tre | less -ar`, or make `tree` a function that executes `tre`.

I don't see a need for this, sorry.

**Comment by faho** [comment]
That seems entirely straightforward to me, certainly much simpler than nested abbreviations.

But, like I said:

```fish
function tree
    if command -sq tre
        tre $argv
    else
        command tree $argv
     end
end
```

This encapsulates the entire tre/tree difference nicely in a simple function.
