### ISSUE TITLE
Drop vendored convenience copy of pcre2

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#8355]
Ever since we've been using pcre2 as the regex backend for string, we've been shipping a vendored copy so people don't have to install it.

We've not been fantastic at keeping this up-to-date - we ship 10.36, the current is 10.38, released about 2 weeks ago. Updating it requires a procedure we've been calling "pcrectomy": https://github.com/fish-shell/fish-shell/wiki/PCREctomy. This is because we don't want to ship a bunch of files not needed by us in the source tarball.

I would like to reconsider (#2985) dropping this copy.

Now, this depends of course on the idea that installing pcre2 isn't a huge burden - distro packages will depend on it anyway (because they don't want to use the vendored copy), some systems even have it preinstalled (e.g. arch has it as a dependency of systemd, their sole supported init system!).

It would be possible to drop it after 3.4, in which case we should still update it now. Or we drop it before, or not at all.

Thoughts?

**Comment by zanchey** [comment]
We had a pretty extensive discussion in #2985 in this regard.

I don't actually think it matters that we're not that up to date - it's a fairly mature library with limited changes in each version. Even the security issues don't really affect fish.

In particular, removing it makes the macOS builds much more complicated.

**Comment by floam** [comment]
> The macOS installer package needs this and can't depend on Homebrew. 

Well, we'd be talking about depending on home-brew to create the installer package, not on using it. Are we sure that's so terrible? macports or "make install" can also install the .a for static linking, no?

**Comment by ridiculousfish** [comment]
Good point regarding the .a files, however the Homebrew libs are thin (ARM64 or x86-64, not both) so they can't be used to build a universal fish. I think it's rather less risky to build PCRE2 ourselves to insulate the Mac build from Homebrew changes. FetchContent worked well, I [opened a PR](https://github.com/fish-shell/fish-shell/pull/8363).
