### ISSUE TITLE
"Unsupported use of '='" error in fish 3.1

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [fish-shell/fish-shell#8359]
Fish version: 3.1.0.
OS: Linux Mint 20.2 Cinnamon

## Problem

[Docs](https://fishshell.com/docs/current/faq.html#how-do-i-set-or-clear-an-environment-variable) says:

> Since fish 3.1 you can set an environment variable for just one command using the key=value some command syntax, like in other shells.

But in fact it doesn't work with: `Unsupported use of '='` when I type smth like `x=1`.

## Notes

I installed fish via `sudo apt install fish`.

**Comment by schuelermine** [comment]
what exactly did you type?

**Comment by EmilySeville7cfg** [comment]
@schuelermine, I've typed `x=1`.

**Comment by schuelermine** [comment]
no, that’s not valid. it’s for a *single* command.
you can type `x=1 env` to run `env` with x = 1.

**Comment by schuelermine** [comment]
```fish
x=1 env | grep '^x='; echo $status
env | grep '^x='; echo $status
```
```
x=1
0
1
```

**Comment by EmilySeville7cfg** [comment]
Thanks!
