### ISSUE TITLE
curl completions do something weird

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#836]
fish_update_completions
    curl -ooooooo<tab>

result: you get lots of output. Why are these os respected?

**Comment by faho** [comment]
This, for me, prints something like:

>-ooooooo\#  (Make curl display progress as a simple progress… [See Man Page])  -oooooook  ((SSL) This option explicitly allows curl to per… [See Man Page])

But the "-oooooo" is colored differently than the other option ("k" or "\#", though I'm not sure that needs to be escaped). 

So: I'm okay with how it works.

**Comment by zanchey** [comment]
Is there something more to do here?

**Comment by faho** [comment]
I think #1315 states this a bit better - we shouldn't always offer an option that has already been given (in fact the default should probably be not to do that, with a simple way out).

Closing this because the discussion there's better.
