### ISSUE TITLE
cd completion is slow

### ISSUE THREAD

**Issue by gdnathan** [fish-shell/fish-shell#8369]
fish version: 3.3.1
system: Manjaro linux on WSL 2
  sh -c 'env HOME=$(mktemp -d) fish' does *not* solve the issue

the issue: whenever i does ``cd <tab>``, there is a short latency making the comment slow. when i use ``ls <tab>``, this issue is not present, its only on the cd command. 

here is a gif where i do ``ls <tab>``, then ``cd <tab>`` (pressing tab as fast as possible), you see the difference

![xdWYiYPA4m](https://user-images.githubusercontent.com/53536851/137896013-671c82c5-e3ec-435e-bb91-7b261437e252.gif)

**Comment by faho** [comment]
What does `type cd` say? How about `set --show CDPATH`?

Do you have the completions overridden? Is there a network file system involved?

**Comment by faho** [comment]
>set --show CDPATH doesnt solve the issue

But what does it *say*? I am interested in the output.
