### ISSUE TITLE
not command not always returns 1 for 0 status

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#8377]
Fish version: 3.3.0 (built from source)
OS version: Linux Mint 20.2 Cinnamon

 `not` is [described](https://fishshell.com/docs/current/cmds/not.html#cmd-not) as:

> not negates the exit status of another command. **If the exit status is zero, not returns 1**. Otherwise, not returns 0.

It is not true when for example the following function is declared and called:

```fish
> function a; return 34; end
> ! a # 0
> ! ! a # 34, but not 1
```

I think this moment must be clarified for readers.

**Comment by krobelus** [comment]
>  `not` is [described](https://fishshell.com/docs/current/cmds/not.html#cmd-not) as:
>
> not negates the exit status of another command. **If the exit status is zero, not returns 1**. Otherwise, not returns 0.
>
> It is not true when for example the following function is declared and called:
> 
> ```fish
> > function a; return 34; end
> > ! a # 0
> > ! ! a # 34, but not 1
> ```
>
> I think this moment must be clarified for readers.

> [...] if anything, being able to get back the original status code after `not .... not` is a feature and not a bug

OK, let's declare this behavior a feature.

Today the documentation (`not --help`) is beautifully simple. I don't know how to document this without making it uglier, and hence more confusing to average users. So I'd rather not document it. I'd be pretty surprised if anyone relied on the opposite behavior in practice, since it's both a contrived construct, and you usually don't compare a raw exit status.

The discussion about the placement of `time` has moved to https://github.com/fish-shell/fish-shell/issues/8568

**Comment by EmilySeville7cfg** [comment]
Why not to add a section for advanced users with more detailed explanation of `not`? :) Average user will not read it, but who want know more will. After a while I or anybody else can forget about this `not` feature and we can lose our time for realizing that it's not a bug, it's a normal `not` behavior.

**Comment by krobelus** [comment]
right, how about

```patch
From f51ebf7ac0a15ef853447e96d07a3418750f3f67 Mon Sep 17 00:00:00 2001
From: Johannes Altmanninger <aclopte@gmail.com>
Date: Tue, 28 Dec 2021 16:38:53 +0100
Subject: [PATCH] Declare that two "not" keywords cancel each other out

"not not return 34" exits with 34, not 1.  This behavior is pretty
surprising but benign.  It doesn't match our docs, but it's probably
not worth changing them because that might confuse newcomers. Add
a test and a comment to explain this to anyone who digs this up
the future.

I considered adding the comment at
parse_execution_context_t::populate_not_process where this behavior
is implemented but the field defintion seems even better, because I
expect programmers to read that first.

Closes #8377
---
 src/proc.h            |  1 +
 tests/checks/not.fish | 10 ++++++++++
 2 files changed, 11 insertions(+)
 create mode 100644 tests/checks/not.fish

diff --git a/src/proc.h b/src/proc.h
index ec28b2388..7a589c50c 100644
--- a/src/proc.h
+++ b/src/proc.h
@@ -403,6 +403,7 @@ class job_t : noncopyable_t {
         bool notified_of_stop{false};
 
         /// Whether the exit status should be negated. This flag can only be set by the not builtin.
+        /// Two "not" prefixes on a single job cancel each other out.
         bool negate{false};
 
         /// This job is disowned, and should be removed from the active jobs list.
diff --git a/tests/checks/not.fish b/tests/checks/not.fish
new file mode 100644
index 000000000..77a03c419
--- /dev/null
+++ b/tests/checks/not.fish
@@ -0,0 +1,10 @@
+#RUN: %fish %s
+
+not true
+echo $status
+# CHECK: 1
+
+# Two "not" prefixes on a single job cancel each other out.
+not not sh -c 'exit 34'
+echo $status
+# CHECK: 34
-- 
2.34.1
```

**Comment by EmilySeville7cfg** [comment]
Sounds well

**Comment by mqudsi** [comment]
fyi you can test with `not not return 13` instead of invoking `sh` :)

**Comment by krobelus** [comment]
> fyi you can test with `not not return 13` instead of invoking `sh` :)

I thought the same, but that exits the script (unless interactive).
See also 3359e5d2e (Let "return" exit a script (#8148), 2021-07-21)

It's weird that a interactive behavior is different from non-interactive one here.
Maybe `return` should only exit scripts that are being sourced? I'm not sure
