### ISSUE TITLE
status print-stack-trace vs status stack-trace

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [fish-shell/fish-shell#8378]
Fish version: 3.3.0 (built from source)
OS version: Linux Mint 20.2 Cinnamon

What's the difference between `status print-stack-trace` vs `status stack-trace`? It seems they are equal but the first is undocumented (I found it via `functions __fish_print_pipestatus`). Note that tab-autocomplete works for both subcommands.

**Comment by zanchey** [comment]
Nothing:
https://github.com/fish-shell/fish-shell/blob/eb990c07c8f575b954acf43ac622050cac49e840/src/builtins/status.cpp#L68-L69
