### ISSUE TITLE
Add silent mode in read builtin

### ISSUE THREAD

**Issue by siteshwar** [fish-shell/fish-shell#838]
In silent mode, typed characters are not shown in terminal, Bash supports silent mode with '-s' flag, so `read -s` will not echo characters on terminal. We should have similar flag in fish's read builtin.

**Comment by tfga** [comment]
@jhillyerd's code as a function:

**Comment by Asuza** [comment]
I was writing a script this morning and was rather disappointed to discover I couldn't input via a "password" mode. Hoping this get implemented soon.

**Comment by mcameron** [comment]
+1

**Comment by ridiculousfish** [comment]
This seems like a nice to have feature

**Comment by cben** [comment]
Turns out `read` uses readline and stores history (#1504).
Does `stty -echo` interact sanely with readline?
IMNSHO whatever mechanism there will be to read silently should also inhibit history saving [at least by default].
I think this all points to a builtin flag of `read` being better than "do it yourself" / stdlib function.

**Comment by bucaran** [comment]
> I think this all points to a builtin flag of read being better than "do it yourself" / stdlib function.

:+1: 

For a userland implementation see here:
https://github.com/fish-shell/fish-shell/issues/2166#issuecomment-183335177

**Comment by krader1961** [comment]
Closed with squashed merge of commit 821388549135abbd6ff1dce66601da29df12c1d4.

**Comment by Pysis868** [comment]
woo!!

[GitHub - fish-shell/fish-shell - fish 2.6.0 (released June 3, 2017)](https://github.com/fish-shell/fish-shell/releases/tag/2.6.0):

> - ...
> - `read` supports a new `--silent` option to hide the characters typed (#838), for when reading sensitive data from the terminal. `read` also now accepts simple strings for the prompt (rather than scripts) with the new `-P` and `--prompt-str` options (#802).
> - ...

**Comment by mustafawm** [comment]
Can we update the docs please?
https://fishshell.com/docs/2.6/commands.html#read 
- doesn't show the --silent mode
- https://github.com/fish-shell/fish-shell/blob/master/doc_src/read.txt says -s for --silent which is not the case

**Comment by faho** [comment]
@mustafawm: We have, you're looking at an outdated version. See https://fishshell.com/docs/current/commands.html#read.

**Comment by mustafawm** [comment]
Oh! thanks @faho, I was running an older version (2.6) ...just installed the latest (3) via homebrew.

**Comment by dideler** [comment]
FWIW, made a very simple package to hide the input (instead of obscuring it): [fish-read-silent](https://github.com/dideler/fish-read-silent)

And an example use case as a dependency in another package: [fish-index](https://github.com/dideler/fish-index)
