### ISSUE TITLE
no error about wrong >>? redirection operator

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#8380]
Fish version: 3.3.0 (built from source)
OS version: Linux Mint 20.2 Cinnamon

Documentation [lists](https://fishshell.com/docs/current/language.html#input-output-redirection) only the following redirection operators (with arbitrary FD too):

- To read standard input from a file, use <SOURCE_FILE.
- To write standard output to a file, use >DESTINATION.
- To write standard error to a file, use 2>DESTINATION. 1
- To append standard output to a file, use >>DESTINATION_FILE.
- To append standard error to a file, use 2>>DESTINATION_FILE.
- To not overwrite ("clobber") an existing file, use >?DESTINATION or 2>?DESTINATION. This is known as the "noclobber" redirection.
- As a convenience, the redirection &> can be used to direct both stdout and stderr to the same destination.

But when I run code with:

```fish
echo 1 >>? test.txt
```

I obtain `warning: The file 'test.txt' already exists` instead smth like `Wrong redirection operator used`. Of course maybe `1 >` is redirected instead of `1` but I think it is unclear even if it's right because no space between first `>` and second one persists. What about to warn user about this (add this as a feature can be disabled)?

**Comment by ridiculousfish** [comment]
I added a mention of append and noclobber combined. I tried to simplify the rest a bit to compensate. Thanks for filing.
