### ISSUE TITLE
pattern matching on the command line (AKA: MOAR GLOBS!)?

### ISSUE THREAD

**Issue by lebel** [fish-shell/fish-shell#839]
Am I blind or basic command line pattern matching isn't available other than the \* wildcard?

Things like [a-e]\* to match every files that begin with the letter a through e and ends with anything.

**Comment by zzamboni** [comment]
I know this is an old issue, but I'd like to support this request, it'd be great if fish supported a wider range of wildcard expansions.

@ridiculousfish: I fully agree with being consistent, but that's a separate issue from *supporting* the wildcards in the first place :)

**Comment by danielb2** [comment]
:+1:
