### ISSUE TITLE
fish crashing randomly

### ISSUE THREAD

**Issue by brumm** [fish-shell/fish-shell#8390]
Hey there, and thanks for making fish. I'm having problems with fish crashing since yesterday. The crashes appear random except for the one way I can reliably reproduce it (with iTerm, but the crashes appear also with Terminal.app and the vscode terminal):

- split a pane
- focus to new pane
- focus back
- hit any non-modifier key

fish crashing is causing iTerm and vscode terminal windows to close themselves.
No crashes if default shell is bash and fish is started from there.

I also completely uninstalled fisher and its plugins to no avail.
fish was installed via brew which doesn't have any higher version.

```
❯ fish --version
fish, version 3.3.1

❯ uname -a
Darwin <users>-iMac.fritz.box 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

❯ echo $TERM
xterm-256color

```

Running `sh -c 'env HOME=$(mktemp -d) fish'` is still using the affected shell which crashes in the same way.

Video of me reproducing the bug:

https://user-images.githubusercontent.com/170500/139323371-6613d8f4-f61a-46e2-b051-2ea0fbae7d2f.mov

**Comment by mqudsi** [comment]
Ok can we detect when this fig garbage is loading fish and warn about this?

**Comment by floam** [comment]
Yeah, let's program our shell to have a *warning label* against a synergistic commercial product that integrates fish, because we quickly dismissed two bug reports and that's how you make friends.

**Comment by mqudsi** [comment]
Yeah, twice in two days by a proprietary program that forcibly inserts itself into shells and makes them crash, and even these long-time users of fish attribute the crashes to fish rather than suspecting fig. We get nothing out of this.
