### ISSUE TITLE
Support vi-mode cursors in Foot Terminal 

### ISSUE THREAD

**Issue by dit7ya** [fish-shell/fish-shell#8391]
Currently vi-mode dynamic block and beam cursors do not work in Foot Terminal. 

As discussed in https://codeberg.org/dnkl/foot/issues/772 I am suspecting it is going to be an easy fix by just adding `foot` in the list here https://github.com/fish-shell/fish-shell/blob/b0b6a585a86cb7b8b082418d2c9cbc39d5a9f99b/share/functions/fish_vi_cursor.fish#L34-L55. I can start a PR.

```
fish --version = fish, version 3.3.1
uname -a = Linux nixos 5.14.15 #1-NixOS SMP Wed Oct 27 07:59:56 UTC 2021 x86_64 GNU/Linux
echo $TERM = foot```

**Comment by faho** [comment]
I simply fixed it now.

In future: For issues this simple, if you're prepared to open a PR you can just do so - answering that we would accept a PR and then reviewing it and merging it is more work than just fixing it.
