### ISSUE TITLE
Cannot set '-n', '-s', '-e', '-E' as variables (or first position in list)

### ISSUE THREAD

**Issue by VeteraNovis** [fish-shell/fish-shell#8392]
When attempting to set a flag as a variable (or in a list as the first element), the letters 'n, s, e, E' do not work correctly.

The commands set the variable 'test' to blank, and will print out a blank line when echoed.
`set test -s`
`set test -e`
`set test -E`

The following command returns no blank line when echoed (similar to simply pressing return with a blank line
`set test -n`

I identified this when trying to save a list with a `-s` in the first position to enable me to store a parameter string for script. But any time either of these four flags are entered as the first element in a list (or just a single element variable), the output is not as expected.

### Recreating bug

Assigning list: `set testList -s example1 -f example2`
Expected Value:  `-s example1 -t example2`
Actual Value: `example1-texample2`

Assigning list: `set testList -e example1 -f example2`
Expected Value:  `-e example1 -t example2`
Actual Value: `example1 -t example2`

Assigning list: `set testList -E example1 -f example2`
Expected Value:  `-E example1 -t example2`
Actual Value: `example1 -t example2`

Assigning list: `set testList -n example1 -f example2`
Expected Value: `-n example1 -t example2`
Actual Value: `example1 -t example2⏎`

### Potential cause
GNU echo uses '-e', '-E', '-n' to edit the string that follows
-e = enable backslash escaped characters to print
-E = disable backslash escaped characters (default behaviour, opposite to -e)
-n = Do not output the trailing newline.
-s = print all values without spaces between them

It seems clear that these flags are being interpreted as special flags before fish is able to save it as a variable.  It doesn't matter if there are single or double quotes around the flags, the same behaviour happens.

However, if the flag is in any position in the list other than the first position the bug does not occur.

### Fish version / OS

`fish --version: 3.3.1`
`Linux USER 5.11.0-38-generic #42-Ubuntu SMP Fri Sep 24 14:03:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
`echo $TERM: alacritty`

Same behaviour after running following:
`sh -c 'env HOME=$(mktemp -d) fish'`

**Comment by faho** [comment]
Okay, the question was answered, so I'm closing this.
