### ISSUE TITLE
Only --help option is suggested for "git archive" command 

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#8398]
Fish version: 3.3.0 (built from source)
OS version: Linux Mint 20.2 Cinnamon

When I type `-` or `--` and press `Tab` I always obtain `--help` while there are several options:

- `--format`
- `-l`, `--list`
- `-v`, `--verbose`
- `--prefix`
- `-o`, `--output`
- `--worktree-attributes`
- `--remote`
- `--exec`

**Comment by faho** [comment]
PRs welcome:

https://github.com/fish-shell/fish-shell/blob/c94dec5d0ec0987938fb5d2b6181e856e4cba746/share/completions/git.fish#L1070

**Comment by EmilySeville7cfg** [comment]
@faho, maybe I'll try to fix it.

**Comment by faho** [comment]
I'm going to declare this "fixed" with #8906.

The git completions are a perpetual work in progress, there's no real need to keep this open.
