### ISSUE TITLE
Why can paths be completed by TAB in some commands but not in others?

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#8401]
```
fish, version 3.3.1
5.14.15-1-MANJARO #1 SMP PREEMPT Thu Oct 28 08:40:32 UTC 2021 x86_64 GNU/Linux
```
Reproduce:
1. get paru binary from https://github.com/Morganamilo/paru/releases
2. `sh -c 'env HOME=$(mktemp -d) fish'`
2. `./paru ./Down<Tab>` or  any other path
3. Nothing happens

From time to time I found that the path won't be completed by TAB key in some of my commands, `paru` is just an example I discovered when I started to file this issue. There are other commands I do remember right now.

So why can paths be completed by TAB in some commands but not in others?

**Comment by ammgws** [comment]
Have a look at t heir completions: https://github.com/Morganamilo/paru/blob/master/completions/fish

**Comment by c02y** [comment]
I thought completions are for options, they have to manually handle completing the paths too?

And if I write a simple wrapper
```
function par
    paru
end
```
TAB after par command will complete path (No completion for options of course), why is that?

And
1. `gitmux` binary file is a command not used in terminal normally but in tmux, I only got this single `gitmux` binary file, and no fish completion file in my system, TAB completing path works for it
2. `shfmt` binary file, I only got this single `shfmt` binary file, and no fish completion file in my system, TAB completing path works for it
3. `sysz` is just a bash script, and no fish completion file in my system, TAB completing path works for it
4. I have tons of scripts/binaries in my personal bin path that do not have fish completion files, but TAB completing path works for them.
5. I have a lot of functions in my config.fish that do not have fish completions, but TAB completing path works for them
6. Maybe not all, I just tested a few of them, TAB completing path works


And another thing is, if I remove the paru.fish from the system, TAB completing path for paru works right away, I move it back, it doesn't work. Again, `paru` is just an example, other commands have this kind of issue when I am using fish.

So is there anything I can do except write fish completion to TAB completing paths, like variable or something once for all?

**Comment by faho** [comment]
What happens here is the paru completions specifically tell fish that files aren't acceptable via `complete -f` (short for `--no-files`).

This is *correct* in many cases - like `paru -S`, which won't take a file. However, it's overly simplistic in that `paru -U` would, and it should be reenabled in that case with `complete -F` (short for `--force-files`).

This is simply a bug/enhancement in the paru completion script and needs to be handled there. Please report your grievances there.

**Comment by faho** [comment]
Okay, apparently this is even simpler and paru simply does not take file arguments - I assumed `paru -U` would act like `pacman -U`, but that assumption is wrong.

So there is no issue anywhere, the completions are correct.
