### ISSUE TITLE
fish_describe_command chokes on our own manpage

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#8404]
Yikes!

<img width="893" alt="image" src="https://user-images.githubusercontent.com/291142/140308641-1acc276f-1629-4396-851a-289d021a448a.png">

macOS 12.0.1

**Comment by faho** [comment]
Works for me.

You'll want to check what `__fish_apropos fish` prints for you.

**Comment by floam** [comment]
Yeah this is not the completion generator. It's what apropos has..

**Comment by faho** [comment]
Note: This *is not* the completion generator. This isn't taken from create_manpage_completions.py. It has nothing to do with this.

This is generated at runtime by running `__fish_describe_command (commandline)`, which calls `__fish_apropos (commandline)`, which on macOS does a bunch of magic to avoid macOS' re-broken whatis caching problem.

But then it also ends up calling `apropos ^(commandline)`, without any filtering. We'd simply have to add that filtering, in some form.

**Comment by floam** [comment]
Any filtering we do would just fix up what shows up in the descriptions, but not be the ultimate fix considering `apropos` is having trouble with our man-pages. It's worth seeing if they are not well formed.

**Comment by faho** [comment]
If the apropos output looks like

```
fish - The friendly interactive shell \n garbage
fish_indent - Description \n garbage
```

with a literal `\n` backslash-n, then we can simply `string replace` it out.

**Comment by faho** [comment]
Whatever causes apropos to choke can be reported to sphinx later, but would have to be released and such.

(technically you could also report it to Apple, but...)

**Comment by floam** [comment]
Maybe we've just got it misconfigured or something?

**Comment by faho** [comment]
It works on my system, and we don't configure much.

As far as I know, the man pages also render correctly.

I'm betting on macOS apropos being the problem, because we already know it has problems.

**Comment by floam** [comment]
Do you get the extra newlines and strange indentation towards at the top of your manages, if you render them with mandoc?

**Comment by faho** [comment]
I don't use mandoc.

**Comment by floam** [comment]
Goofiness at the top has me wondering if we are outputting anything strange
<img width="582" alt="Screen Shot 2021-11-04 at 5 21 18 AM" src="https://user-images.githubusercontent.com/291142/140312603-41b5fbca-a64c-44dc-8901-ad516ab3eee2.png">
:

**Comment by faho** [comment]
If there's something goofy being created, that's very very likely to be somewhere in sphinx/rst2man/mandoc/...

We basically don't configure anything here, we just send it off to be rendered.

(to be clear: it renders fine for me, so it's possible it's in the rst2man->mandoc part of the pipeline)

But let me reiterate my point: These are all external tools. We can figure out where exactly the problem happens, and report it to them, but then we have to wait for them to fix it and create a new release. I would suggest working around it by simply `string replace`ing the problematic parts out. This is why I suggested checking the output of `__fish_apropos fish`.

**Comment by faho** [comment]
Okay, you can call `rst2man` on the .rst files directly. Here's the first 50 lines of `rst2man doc_src/cmds/fish.rst` on my system:

```
.\" Man page generated from reStructuredText.
.
.
.nr rst2man-indent-level 0
.
.de1 rstReportMargin
\\$1 \\n[an-margin]
level \\n[rst2man-indent-level]
level margin: \\n[rst2man-indent\\n[rst2man-indent-level]]
-
\\n[rst2man-indent0]
\\n[rst2man-indent1]
\\n[rst2man-indent2]
..
.de1 INDENT
.\" .rstReportMargin pre:
. RS \\$1
. nr rst2man-indent\\n[rst2man-indent-level] \\n[an-margin]
. nr rst2man-indent-level +1
.\" .rstReportMargin post:
..
.de UNINDENT
. RE
.\" indent \\n[an-margin]
.\" old: \\n[rst2man-indent\\n[rst2man-indent-level]]
.nr rst2man-indent-level -1
.\" new: \\n[rst2man-indent\\n[rst2man-indent-level]]
.in \\n[rst2man-indent\\n[rst2man-indent-level]]u
..
.TH "FISH - THE FRIENDLY INTERACTIVE SHELL"  "" "" ""
.SH NAME
fish - the friendly interactive shell \- 
.SH SYNOPSIS
.INDENT 0.0
.INDENT 3.5
.sp
.nf
.ft C
fish [OPTIONS] [\-c command] [FILE] [ARGUMENTS...]
.ft P
.fi
.UNINDENT
.UNINDENT
.SH DESCRIPTION
.sp
fish is a command\-line shell written mainly with interactive use in mind. This page briefly describes the options for invoking fish. The 
.nf
:ref:\(gafull manual <intro>\(ga
.fi
 is available in HTML by using the 
```

Saving that as "fishman" and opening it with `man ./fishman` renders a sensible, if truncated, man page.

Note that you will get errors about `:ref:` being an Unknown text role, that's presumably because it would be interpreted by sphinx before passing it on to rst2man.

I'd suggest seeing if you get different output, and if you don't, if that output triggers the glitches.

**Comment by floam** [comment]
The issue seemed to go away after I blasted away whatever version of sphinx/python/docutils used for the above and used python3.9 and pip3 to reinstall the dependancies. The `.TH "FISH" "1" "Oct 26, 2021" "3.3" "fish-shell"` now appears lower down and I assume that's related. Oh well. Yeah we can filter it out for `fish_describe_command`.

**Comment by faho** [comment]
>Yeah we can filter it out for fish_describe_command.

... is it still necessary then? Seems like it was already fixed in sphinx.

>The .TH "FISH" "1" "Oct 26, 2021" "3.3" "fish-shell" now appears lower down and I assume that's related.

That's *possible*. My man renders your page sensibly, but maybe mandoc is more conservative in its interpretation.

**Comment by floam** [comment]
`man` renders them both the same. The only difference is whatis doesn't hate it now.

**Comment by faho** [comment]
So if the description now works, I don't think we need to do anything - just tell people to update sphinx.

The man stuff is likely to be down to additional incompatibilities between rst2man and mandoc, then, and I don't think we can do anything about that from our end except report it.

**Comment by floam** [comment]
Sure.
