### ISSUE TITLE
math reports negative values as positive when in octal or hex, also mishandles overflow

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#8417]
On fish master commit 1261b53d9669cbe635c467e2236f80d5b2701bac:

    > math --base hex -10
    0x0
    > math --base hex 'pow(2, 40)'
    0xffffffff

this is because the value is converted to a (presumably 32 bit) int, and then cast to an unsigned int before it is printed.

**Comment by floam** [comment]
I think you have this backwards.

**Comment by floam** [comment]
Current `master`:

floam@M1 ~> math --base hex -10
0x0
floam@M1 ~> math --base hex 'pow(2, 40)'
0xffffffff
floam@M1 ~> echo $version
3.3.1-573-g3de63f7e2

Because I just fixed it, no? Am I nuts?

**Comment by floam** [comment]
older versions had the output you are quoting, right?

**Comment by floam** [comment]
Pulling up the last .app bundle, or an old build from last week: 

```
floam@M1 ~> echo $version
3.3.1
floam@M1 ~> math --base hex 'pow(2, 40)'
0x0
floam@M1 ~> math --base hex -10
0xfffffff6
```

**Comment by ridiculousfish** [comment]
Yeah, was testing with the wrong fish. I'll update the issue.

**Comment by floam** [comment]
Oh gotcha, you actually fixed the output to not be naive, rather than totally backwards.

**Comment by floam** [comment]
Math can always understand its own output regardless of which `--base` it is running in, this just regressed for negative octal:

```
> math -0x50 # works
-11
> math -050 # should be -40
-50
```

**Comment by floam** [comment]
Nevermind; it was never working doing that for octal input, negative or positive.
