### ISSUE TITLE
fish_config: silently doesn't set color schemes.

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#8419]
I haven't looked too deeply into this but choosing a new color scheme causes no changes upon hitting the Set Theme button for me in Safari.

I haven't gotten to the bottom of it but I think it may be due to changes in July, but it also might not be, since I think this just doesn't get a ton of attention these could just be unrelated oversights: The console is throwing obvious errors due to `color_scheme_fish_default` being missing (it used to be in colorutils.js`, now it's nowhere, and a random static analysis tool[^1] has 4 alerts to complain about between webconfig.py and controller.js on one commit from July… which might also  not actually be the cause of the problem.

I like to imagine if this didn't work for four months people would notice. So it really could be something else.

<img width="466" alt="Screen Shot 2021-11-07 at 8 25 16 PM" src="https://user-images.githubusercontent.com/291142/140684271-f618dd35-444e-4789-83df-27ba2a0d0757.png">

[^1]: https://lgtm.com/projects/g/fish-shell/fish-shell/rev/2aec6e58146d2e0bfea2802ec147b26631edaf7d

**Comment by faho** [comment]
>I like to imagine if this didn't work for four months people would notice. So it really could be something else.

No, it actually was broken for four months. We have surprisingly few people regularly running git, and of those most won't use the color picker regularly as they've already chosen a scheme before.

So this is a very good catch and would have been awkward in a release. Thanks!

**Comment by faho** [comment]
>it used to be in colorutils.js`, now it's nowhere

Now the theme itself is in https://github.com/fish-shell/fish-shell/blob/master/share/tools/web_config/themes/fish%20default.theme -  #8127 made it so the themes are stored in separate .theme files so we can share them with the new CLI - #8132.

The variable is gone and I missed it.

**Comment by floam** [comment]
Longer term, it might be nice to make setting the theme and setting the prompt through fish_config check responses and make the webserver report failure better - such that we can definitely show an alert() or something when something has gone wrong.

And for the sake of sanity, someday implement the CLI options not as the short circuiting fishcript overlay but in fish_config itself?

**Comment by floam** [comment]
and thanks for fixing it @faho!
