### ISSUE TITLE
Unknown terminfo capability ^/dev/null

### ISSUE THREAD

**Issue by Ojd2000** [fish-shell/fish-shell#8420]
### Issue

After latest system upgrade (no fish upgrade), the string `tput: unknown terminfo capability '^/dev/null'` shows up after issuing any command. The only fish dependency I have upgraded is `ncurses`, to version `6.3-1`.
This issue has happened on two machines, although they have similar configuration.
Without any third party customizations, it does not happen.

### Information

- fish version: 3.3.1
- Terminal emulator: [wezterm](https://github.com/wez/wezterm)
  - Also tried on kitty, with same exact issue
- Distro: Arch Linux
- Kernel: Linux hardened 5.14.16

**Comment by floam** [comment]
you have something running some `tput` command that ends with `^/dev/null`. You can change that or you can disable the `stderr-nocarat` in `status features`

**Comment by floam** [comment]
I'm surprised you only upgraded ncurses. All I can guess is you must not have had `tput` before? So some code is finally able to work but it's old?

**Comment by faho** [comment]
To expand on that a bit:

>You can change that to … 2>/dev/null

This is what you want to do - the `^` redirection will eventually be removed entirely.

Try something like `grep -r "\^/dev/null" ~/.config/fish`, and replace every occurence with `2>/dev/null`.

As a temporary stopgap, you can use `set -Ua fish_features no-stderr-nocaret` to reenable the redirection. You'll have to restart fish after.

>I'm surprised you only upgraded ncurses. All I can guess is you must not have had tput before? 

My guess is there's e.g. an old copy of fish_vi_cursor, and that used to check `tput` if some other condition held, which changed after the ncurses update.

**Comment by Ojd2000** [comment]
I have better checked inside my fish config files and in fact there was a line using `tput` (I needed it in `st` terminal when I used to have it). My bad, it was an old config that I completely forgot about.

> You can change that to … 2>/dev/null
I updated that line to this, and the issue got solved.
