### ISSUE TITLE
No completions shown for complete -c command-name

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#8425]
Fish version: fish, version 3.3.1-557-gb550b3885
OS version: Linux Mint 20.2 Cinnamon

![complete problem](https://user-images.githubusercontent.com/42812113/140941170-45dd251c-64b4-4c70-befe-415c02bef4a4.png)

I don't understand what's going on with complete builtin... My `$fish_complete_path` is:

```
/home/emilyseville7cfg/.config/fish/completions /usr/local/etc/fish/completions /usr/share/cinnamon/fish/vendor_completions.d /usr/share/gnome/fish/vendor_completions.d /home/emilyseville7cfg/.local/share/flatpak/exports/share/fish/vendor_completions.d /var/lib/flatpak/exports/share/fish/vendor_completions.d /usr/local/share/fish/vendor_completions.d /usr/share/fish/vendor_completions.d /usr/local/share/fish/completions /home/emilyseville7cfg/.local/share/fish/generated_completions
```

**Comment by floam** [comment]
you are just installing an empty completion for wine there.

**Comment by floam** [comment]
To see completion output, use `complete -C`.

**Comment by EmilySeville7cfg** [comment]
Thanks!

**Comment by faho** [comment]
>you are just installing an empty completion for wine there.

Not since #7321.

`complete -c wine` shows the wine completions, but only *after* they have been autoloaded. You'll have to try completing `wine` at least once.

**Comment by floam** [comment]
Whoa what

**Comment by faho** [comment]
From [the documentation](https://fishshell.com/docs/current/cmds/complete.html):

> When complete is called without anything that would define or erase completions (options, arguments, wrapping, ...), it shows matching completions instead. So complete without any arguments shows all loaded completions, complete -c foo shows all loaded completions for foo. Since completions are autoloaded, you will have to trigger them first.

**Comment by floam** [comment]
Sorry, just catching up. I'm a big fan of replacing that with a positional argument since it always occurs. Sorry for the bad advice @EmilySeville7cfg.

**Comment by EmilySeville7cfg** [comment]
@faho, is it a good decision to show completions only for auto loaded things? What if I don't want to execute some command to obtain it's completions?

**Comment by faho** [comment]
You don't have to execute it, just press TAB.

Or, in a script: `complete -C"wine "`.

**Comment by floam** [comment]
That doesn't make sense, you cannot encounter completions without having autoloaded what you can.
