### ISSUE TITLE
Support for multi valued options

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#8426]
I suggest add support for multi valued options for `complete`. For instance if I type `mono --debug=casts,` (consider [mono.fish](https://github.com/EmilySeville7cfg/fish-shell/blob/3356be26df985e97ca9b0df3e00f3b27f0dc4824/share/completions/mono.fish)) and press tab I obtain the following hint:

```
--debug=casts  (Use debug mode)  --debug=gdb  (Use debug mode)  --debug=mdb-optimizations  (Use debug mode)
```

instead of nothing. Maybe `-S`|`--separator` option can be added to specify value separator (`,` in our case).

**Comment by faho** [comment]
This is what `__fish_append` is for. See e.g.

https://github.com/fish-shell/fish-shell/blob/bcbfd70d413155152ce1261f925a62b678c83d32/share/completions/lscpu.fish#L7-L8
