### ISSUE TITLE
ESC should abort autocompletion

### ISSUE THREAD

**Issue by septatrix** [fish-shell/fish-shell#8427]
* `fish, version 3.3.1`
* `Linux 5.14.14-200.fc34.x86_64 #1 SMP Wed Oct 20 16:15:12 UTC 2021` (Fedora)
* `xterm-256color` (Gnome Terminal)

It is a common occurrence that I want to copy some command or path from the terminal. If however the autocompletion directly touches the already existing characters it also gets selected when double clicking. This can be quite annoying. I think it would be reasonable that pressing `ESC` would hide/abort the autocompletion.

![image](https://user-images.githubusercontent.com/24257556/141175136-069797f8-a967-4f10-88c3-792fd04d1dd0.png)
![image](https://user-images.githubusercontent.com/24257556/141175173-79a0d650-9130-4805-aef7-95d7b85a4a43.png)

**Comment by faho** [comment]
Pressing escape is something you'd do frequently, killing the suggestion isn't something that seems sensible. Think about e.g. vi-mode.

Instead, if you find yourself frequently copying stuff, why not press ctrl-x to copy the entire commandline to clipboard? This is bound by default.

**Comment by floam** [comment]
This seems reasonable, if it's escape by itself and it times out.

**Comment by ridiculousfish** [comment]
You can do this today with `bind` and the `suppress-autosuggestion` readline function:

    > bind \e cancel suppress-autosuggestion

@septatrix does that work for you?

**Comment by faho** [comment]
>You can do this today with bind and the suppress-autosuggestion readline function:

@ridiculousfish Unfortunately you can't, in a released version - #8428.

But yeah, that should be the way to do it. Escape is quite overloaded, and it's currently a key you can just slam without thinking too much about it. Adding this on top would remove that rather useful property, so this should be local customization.

**Comment by faho** [comment]
Okay, the necessary issue was fixed and I do not believe we want to overload the escape binding in this way, closing!
