### ISSUE TITLE
Binding escape as user binding breaks escape sequence bindings (arrows, etc)

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#8428]
Fish 44a5db4d1, which is builtin-path on top of b96c92a7f, also reproduces in 3.3.1:

```fish
bind \e suppress-autosuggestion cancel
```

will essentially break the arrow key bindings. This is because e.g. up-arrow sends `\e\[A`, and this already matches the `\e` and calls it done. Binding it with `--preset` works.

Presumably we're not looking across the lists?

**Comment by mrjones2014** [comment]
I'm still having this issue on fish 3.4.1.

Interestingly, it _was_ fixed when I was using `brew install --HEAD fish` until a few days ago, not exactly sure when, but I think this bug was reintroduced.

**Comment by ridiculousfish** [comment]
I was unable reproduce on `brew install --HEAD fish`. Please open a new issue with repro steps, system information, etc.
