### ISSUE TITLE
Inconsistency with set and abbr

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#8431]
Now `set --query` works as defined below:

> -q  or  --query test if the specified variable names are defined. Does not output anything, but the builtins exit status is the number of variables specified that were not defined, or 255 if more than 255 variables are not defined.

while `abbr --query` works contradicationary:

> -q or --query Return 0 (true) if one of the WORDs is an abbreviation.

Why `set --query` can't behave more like abbr (check whether at least one variable is defined and return 0 in this case)? It is a breaking change of course and is not a problem when only one thing checked with set/abbr.

**Comment by faho** [comment]
We should just make abbr behave like set. Either behavior is fine by itself and it's always possible to get the other by doing multiple queries, so we should change the less used tool to match the more used one.

**Comment by floam** [comment]
Nice job, you noticed a design flaw!

**Comment by faho** [comment]
Okay, `abbr` returns 0 only if *all* given words exist. It doesn't do the counting that `set` does.

**Comment by floam** [comment]
So it doesn't even match the docs?

**Comment by floam** [comment]
I call that a free pass to make it do whatever, @faho. Want to change it up?

**Comment by IlanCosman** [comment]
`--query` is generally a complete mess 😄

```fish
function foo
    set -l var1
    set --query var1 var2 var3
    echo $status # 2

    functions --query foo bar baz
    echo $status # 2
    
    type --query foo bar baz
    echo $status # 0

    builtin --query true foo bar
    echo $status # 0

    command --query ls notCommand1 notCommand2
    echo $status # 0

    abbr abbr1 blah
    abbr --query abbr1 abbr2 abbr3
    echo $status # 1
end
```

**Comment by faho** [comment]
Ah, okay, there's a bug:

https://github.com/fish-shell/fish-shell/blob/aa470e12b22d71f6da6728aad8be3c9761fc5668/share/functions/abbr.fish#L55-L64

That `set -q $escaped` should be a `set -q $var`.

The comment says it's doing this style of returning to match `type` and `command`.

**Comment by faho** [comment]
Okay, I made abbr do what the documentation says, and what the comments explain is to be consistent with type and command.

That's the easier change than making it consistent with `set`.
