### ISSUE TITLE
:program: in sphinx doesn't link

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#8438]
With @floam's recent work, we're now trying to use more semantic markup. That's cool.

Unfortunately, while `:envvar:` links to the definition of the corresponding envvar, I can't see `:program:` do the same.

I think the actual syntax to define a program section is:

```
.. program:: name
```

with the double colons and the space after them (at least emacs' sphinx mode doesn't highlight them if that's not added). Some of the definitions lack spaces or don't exist (e.g. echo doesn't have a program definition).

Whether with that, or without, I can't see e.g. the link from return in https://github.com/fish-shell/fish-shell/blob/master/doc_src/commands.rst#keywords working.

In addition, all of the links to `fish_add_path` are broken because they still use the label, which has now been removed.

If we can't figure out how to make it link, we should revert to using normal `:ref:` links again.

Note: This should **block a 3.4 release**

**Comment by faho** [comment]
Okay, I've now replaced the references that should be linked with :ref: again. I kept the program:: definitions in place and kept the :program: roles for the program's own man page - `realpath` doesn't have to link to the `realpath` page inside the `realpath` page.

If we can make :program: work, we can switch easily by removing the cmd- labels, building the docs and seeing where it complains about the label not existing. That makes it easy to find all places a label is used.

**Comment by krobelus** [comment]
We previously rejected the idea to treat warnings as errors (`sphinx-build -W`) - I don't remember why and I can't find that discussion now. Maybe at least in the CI or in Debug builds?

**Comment by faho** [comment]
1. The issue with -Werror style things remains - different compiler version, different warnings. Our CI runs on Ubuntu, so the version you get is, uh, not super up-to-date.
2. This would not help with the :program: issue, only the missing labels.
