### ISSUE TITLE
Html docs: Remove link underlines again?

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#8439]
Since 94890c28d3b35ba2750cf393763e5f498f44269a, we underline links in the html version of the docs.

I think it's a bit much:

With:

![Screenshot_20211112_173754](https://user-images.githubusercontent.com/5185367/141502186-06c1f541-63b9-4f51-bbec-be651450bcff.png)

Without:

![Screenshot_20211112_173829](https://user-images.githubusercontent.com/5185367/141502209-f40dea69-b415-4cac-85d4-eca6ad8c1b76.png)

In the former, the links just seem overwhelming and, especially with the long section titles in the FAQ, just bleed into each other.

In the text, links are already blue, so there shouldn't be any confusion. And the section links are in the sidebar, which is reasonably obviously a place for links.

I would like to change this back.

**Comment by faho** [comment]
Compare [the python docs](https://docs.python.org/3/reference/compound_stmts.html#the-with-statement), which also do not feature underlines.

**Comment by krobelus** [comment]
Agreed. Browsers still default to rendering `<a href>` with underlines by default but most websites leave them out

**Comment by kopischke** [comment]
Though I agree on aesthetics, I would be remiss not to note there are some accessibility issues around relying on colour alone for showing links. WCAG 2.0 [recommends against them](https://webaim.org/techniques/hypertext/link_text), as [vision impaired, colour deficient](https://www.freecodecamp.org/news/link-accessibility-colors-are-not-enough/) and [dyslectic](https://www.a11y-101.com/development/underlined-links) users cannot discern these well.

**Comment by faho** [comment]
Yeah, but this ain't it. The links are hard to tell from each other. The links will get underlines when hovering over, the section links in particular are in the section link bit of the screen.

Also, from one of your links:

>WCAG 2.0 has 2 additional requirements for body text links that are not underlined by default:

> The link text must have a 3:1 contrast ratio from the surrounding non-link text.

> The link must present a "non-color designator" (typically the introduction of the underline) on both mouse hover and keyboard focus.

Since we have underline on hover, that would be enough.

**Comment by faho** [comment]
Okay, I've now left the underlining only in the body of the text. There it does make links more obvious, and the issue of links bleeding into each other doesn't really happen - you don't really have "link link link", like you do in the sidebar.

I feel that's a good compromise.

**Comment by floam** [comment]
I agree - it was making the navigation an eye chart.
