### ISSUE TITLE
doas rm has too many arguments

### ISSUE THREAD

**Issue by emmatebibyte** [fish-shell/fish-shell#8440]
Please tell us which fish version you are using by executing the following:

  fish --version
  echo $version

fish, version 3.3.1

Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

Linux noire-carnation 5.14.16-xanmod1-cacule-1 #1 SMP Thu, 04 Nov 2021 12:20:42 +0000 x86_64 unknown unknown GNU/Linux
xterm-256color

Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:

  sh -c 'env HOME=$(mktemp -d) fish'

I did try this, no change.

Tell us how to reproduce the problem. Including an asciinema.org recording is useful for problems that involve the visual display of fish output such as its prompt.

type `doas rm -R ` and then any file or folder name. The terminal will display the following error:

```complete: Too many arguments

/usr/share/fish/vendor_completions.d/rm.fish (line 3): 
complete -c rm -n "__fish_use_subcommand" -s i -l prompt before every removal
^
from sourcing file /usr/share/fish/vendor_completions.d/rm.fish
        called on line 1 of file /usr/share/fish/functions/__fish_complete_subcommand.fish
in command substitution
        called on line 1 of file /usr/share/fish/functions/__fish_complete_subcommand.fish
in command substitution
        called on line 47 of file /usr/share/fish/functions/__fish_complete_subcommand.fish
in function '__fish_complete_subcommand' with arguments '--commandline rm -R ""'
        called on line 25 of file /usr/share/fish/completions/doas.fish
in function '__fish_complete_doas_subcommand'
in command substitution

(Type 'help complete' for related documentation)
```

**Comment by faho** [comment]
I'm sorry, we're going to need more information.

Is that an error message that you see? When does that show up? What are you doing? What system? What fish version?

In general you should be following the issue template.

**Comment by krobelus** [comment]
On Fri, Nov 12, 2021 at 09:05:31PM -0800, Emma Tebibyte wrote:
> type `doas rm -R ` and then any file or folder name. The terminal will display the following error:
> 
> `complete: Too many arguments
> 
> /usr/share/fish/vendor_completions.d/rm.fish (line 3): 

This file is not installed by fish. Fish-shipped completions are in /usr/share/fish/completions/rm.fish

What are the contents of /usr/share/fish/vendor_completions.d/rm.fish (why is it installed, do you really need it?)

in particular, this line

> complete -c rm -n "__fish_use_subcommand" -s i -l prompt before every removal

should be

	complete -c rm -n "__fish_use_subcommand" -s i -l "prompt before every removal"

**Comment by faho** [comment]
@krobelus Where are you getting that information from? Github is only showing me "No description provided"?

**Comment by krobelus** [comment]
I also wondered - turns out they kept the HTML comments from the template, so it doesn't render on github. Fixed.
(the email notification still includes the comments, which is usually a minor inconvenience)

**Comment by emmatebibyte** [comment]
>  What are the contents of /usr/share/fish/vendor_completions.d/rm.fish (why is it installed, do you really need it?)

```complete -c rm -n "__fish_use_subcommand" -l interactive -d 'prompt according to WHEN: never, once (-I), or always (-i). Without WHEN, prompts always'
complete -c rm -n "__fish_use_subcommand" -s f -l force -d 'ignore nonexistent files and arguments, never prompt'
complete -c rm -n "__fish_use_subcommand" -s i -l prompt before every removal
complete -c rm -n "__fish_use_subcommand" -s I -d 'prompt once before removing more than three files, or when removing recursively. Less intrusive than -i, while still giving some protection against most mistakes'
complete -c rm -n "__fish_use_subcommand" -l one-file-system -d 'when removing a hierarchy recursively, skip any directory that is on a file system different from that of the corresponding command line argument (NOT IMPLEMENTED)'
complete -c rm -n "__fish_use_subcommand" -l no-preserve-root -d 'do not treat \'/\' specially'
complete -c rm -n "__fish_use_subcommand" -l preserve-root -d 'do not remove \'/\' (default)'
complete -c rm -n "__fish_use_subcommand" -s r -l recursive -d 'remove directories and their contents recursively'
complete -c rm -n "__fish_use_subcommand" -s R -d 'Equivalent to -r'
complete -c rm -n "__fish_use_subcommand" -s d -l dir -d 'remove empty directories'
complete -c rm -n "__fish_use_subcommand" -s v -l verbose -d 'explain what is being done'
complete -c rm -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c rm -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'```

I don't know why it's installed, I don't know what package created it.

**Comment by krobelus** [comment]
> I don't know why it's installed, I don't know what package created it.

you can ask your package manager, for example `dpkg-query -S /usr/share/fish/vendor_completions.d/rm.fish`

**Comment by faho** [comment]
Okay, question was, after some initial difficulty (sorry for that, your message appeared empty to me!) answered, and the issue lies with whoever wrote that completion script.

Closing!
