### ISSUE TITLE
Variable highlight color does not span lines

### ISSUE THREAD

**Issue by schuelermine** [fish-shell/fish-shell#8444]
```
fish, version 3.3.1
3.3.1
```

When splitting a command mid-variable using backslash-newline, the rest of the variable name isn’t highlighted in the same color as the start of it.
i.e.
```fish
echo $COL\
UMNS
```
![Screenshot from 2021-11-15 01-45-04](https://user-images.githubusercontent.com/48802534/141706032-c0e574c1-707a-45d6-9843-7b47ec1aa9af.png)

**Comment by ridiculousfish** [comment]
Nice find! There's probably other cases where we mishandle this but this one is mercifully easy to fix.  Fixed as a47f498516b3dea986dc43fc0d9e94479e755314
