### ISSUE TITLE
Possibility to erase all abbreviations.

### ISSUE THREAD

**Issue by kaddkaka** [fish-shell/fish-shell#8450]
Is there some way to clear all abbreviations in fish? I added some abbreviations to `~/.config/fish/config.fish` that I no longer want, and easiest would be to clear everything, fix my config file and resource it. Is that possible?

I'm using `fish 3.3.1` on Xubuntu (`Linux david-desktop 5.11.0-40-generic #44-Ubuntu SMP Wed Oct 20 16:16:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`)

I found `abbr --erase`, but with that command I have to erase each abbreviation one by one.

**Comment by faho** [comment]
It's a scripting language, you can write scripts!

```fish
for a in (abbr --list)
    abbr --erase $a
end
```

**Comment by kaddkaka** [comment]
I just realized I should have been using the global flag `-g` when defining abbreviations in my startup config. But now the mess is already there, so a quick to clean it out would still be nice. :)

**Comment by faho** [comment]
Run that, it will erase all the abbreviations!

**Comment by kaddkaka** [comment]
Thanks the script was so simple, I started using fish yesterday so I hadn't opened that door yet, thanks!

**Comment by kaddkaka** [comment]
Already done ;)
