### ISSUE TITLE
Subtle change in text size/position (layout shift) due to syntax highlighting

### ISSUE THREAD

**Issue by ayushnix** [fish-shell/fish-shell#8462]
This has been happening for quite some time now but I thought I should finally report this. I can observe subtle layout shift in text because of syntax highlighting. The position of the text, or maybe its size, changes subtly when I type a character that makes a command valid. This makes me uncomfortable.

This happens even though I've enabled only the `Regular` font weight in my terminal. All other font styles and weights were disabled when recording this, including italics and bold text.

[Here's](https://asciinema.org/a/450141) an asciinema recording. This is also reproducible using a temporary `$HOME` folder. Please watch the videos in fullscreen.

https://user-images.githubusercontent.com/79408161/142612078-752973cf-5fc3-4b50-9399-845cde52e074.mp4

The relevant system details are

```
$ fish --version
fish, version 3.3.1
$ uname -r
5.14.16-arch1-1
$ cat /etc/os-release | head -1
NAME="Arch Linux"
# TERMINAL
$ foot --version
foot version: 1.10.0 +pgo +ime +graphemes -assertions
$ echo $TERM
tmux-256color
$ alacritty --version
alacritty 0.9.0 (fed349aa)
$ echo $TERM
xterm-256color
```

I can observe this behavior on both alacritty and foot terminal, with and without using tmux. I've used kitty before and I had this issue in that terminal as well.

**Comment by page-down** [comment]
I had this feeling before, and then after a pixel-level comparison I found no difference.

![](https://user-images.githubusercontent.com/57713011/142614000-954bf26e-b4f4-4458-a810-a784dd9454ca.png)

I think this is related to the arrangement of the monitor RGB LEDs. Especially when switching between red and blue, there is a feeling that the text is drifting up and down.

**Comment by ayushnix** [comment]
@page-down How can I confirm this at pixel-level myself?

**Comment by page-down** [comment]
Capture the same area when the text is in a different color, then use image comparison or editing software to zoom in for comparison.

**Comment by page-down** [comment]
This is possible to fix even if there are physical and algorithmic aspects to it. Just calculate the offset needed to display the same text axis for each color, and then apply the offset when antialiasing in subpixels.

This can be done in the terminal emulator, but definitely not in the shell, which does not control text rendering and presentation.

However this is not really worth putting so much effort into, so no one is bothered to do it.

**Comment by ayushnix** [comment]
You were right @page-down. This is weird. I didn't realize this was a thing.

I'll have to disable the syntax highlighting then. This layout shift has become annoying.

**Comment by faho** [comment]
Sorry, fish has no influence over text rendering, there is nothing for us to do here.

**Comment by floam** [comment]
You could try not going from green to red but something a little closer.

**Comment by ayushnix** [comment]
> You could try not going from red (error) to green (command) but something a little closer. Or get a higher resolution display such that you cannot perceive the horizontal position of the sub pixels.

I'm already using a 27 inch 4K monitor (although I do want a 27 inch 5K monitor instead) so I don't expect low resolution to be a problem. I've disabled the colors for error and valid commands (red and green) and things seem much better. I hate layout shift, especially in a terminal while I'm typing.
