### ISSUE TITLE
Standardize all completions

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#8463]
I suggest to create smth like to standard to easily write completions and faster understand meaning of options/flags shown as tab-suggestions. Below is my attempt to write it. I will edit only this first post.

Standardize completions as shown below.

# Convention

When option definition is unknown `<option-synopsis>` placeholder is substituted instead of explicit definition.

# Quotes

Single quotes must be always preferred while possible (double quotes or backticks are required to be shown).

# Verb meaning

- Show - include smth in stdout/stder in such way it can't be redirected somewhere by command options
- Include - include smth in stdout/stder in such way it can be redirected somewhere by command options
- Use - use smth that already exist to affect command behavior in some way
- Specify - specify smth new to affect command behavior in some way

# General options

`-h`|`--help` and `-v`|`--version` should always be defined as:

```fish
complete command-name --short-option h --long-option help --description 'Show help'
complete command-name --short-option v --long-option version --description 'Show version'
```

before any other option definitions.

> Assumption: exit is always performed after running `-h`|`--help` and `-v`|`--version` so there is no need to note it explicitly until behavior diverge from mentioned one.

# Output redirection options

Options covering redirection manipulations should always be defined as:

```fish
complete command-name <option-synopsis> --description 'Redirect [any-text] stdout to [file-name] file [and diverged-behavior]'
complete command-name <option-synopsis> --description 'Redirect [any-text] stderr to [file-name] file [and diverged-behavior]'
complete command-name <option-synopsis> --description 'Redirect entire [any-text] output to [file-name] file [and diverged-behavior]' # Redirect both stdout and stderr to file

complete command-name <option-synopsis> --description 'Discard [any-text] stdout [and diverged-behavior]'
complete command-name <option-synopsis> --description 'Discard [any-text] stderr [and diverged-behavior]'
complete command-name <option-synopsis> --description 'Discard entire [any-text] output [and diverged-behavior]' # Discard both stdout and stderr

complete command-name <option-synopsis> --description 'Read [any-text] from [file-name] file [and diverged-behavior]'
```

- `any-text` must be only noticed when is not the same as `command-name`
- `file-name` must be only noticed when file name is well-known file name and not choosen by user
- `diverged-behavior` must be only noticed when behavior is different than assumed by default

> Assumption: exit is always not performed after running redirection commands so there is no need to note it explicitly until behavior diverge from mentioned one.

**Comment by faho** [comment]
>Options covering redirection manipulations should always be defined as:

Do you have any examples here? I'm not seeing what kind of options this applies to.

------

I do not believe being overly strict with conventions is worth a lot.

In terms of formatting and such we already have `fish_indent`, which you can run on your scripts and which will e.g. remove useless quotes.

But when it comes to e.g. mandating single quotes for everything that's just overly restrictive and leads to a lot of review churn.

In the context of completions, one of the most common uses of double quotes is to avoid escaping a `'` used as an apostrophe:

```fish
complete foo -l no-bogart -d "Don't bogart the funions"
```

**Comment by EmilySeville7cfg** [comment]
I thought about everything above again and decided to decline this standardization because it's very hard to support it. The only what I will do - use two descriptions for `--help` and `--version` from above. ;)
