### ISSUE TITLE
[Feature] add variable $fish_cursor_normal

### ISSUE THREAD

**Issue by realmazharhussain** [fish-shell/fish-shell#8469]
I would like for fish to support a separate variable for cursor in normal mode of fish vi keybindings

### Reason

I would like to have a block cursor in normal/command mode, underscore cursor in replace mode and line cursor everywhere else. But this could only be possible if fish supports a special variable for normal mode cursor like it does for insert, replace, visual, default modes e.t.c.

**TLDR;**
I would like to

```fish
set fish_cursor_default line blink
set fish_cursor_normal  block blink
set fish_cursor_insert  line blink
set fish_cursor_replace underscore blink
set fish_cursor_visual  block
```

### My Setup
Distro: Manjaro
Fish: 3.3.1
Installation Method: Manjaro repos

**Comment by faho** [comment]
What we call "default" *is* the vi-normal mode.

**Comment by realmazharhussain** [comment]
But I need line cursor everywhere else. If I set fish_cursor_default to block, it sets block cursor for everything else e.g. `read` command or literally any command that takes input (bash for example) **and** setting fish_cursor_unknown to line doesn't work either.

**Comment by faho** [comment]
Ah, okay, that's #4656 then.
