### ISSUE TITLE
__fish_seen_argument.fish throws exception when autocompleting

### ISSUE THREAD

**Issue by Kitt3120** [fish-shell/fish-shell#8478]
Fish version: 3.3.1-643-g566a673e4
Terminal: xterm-256color
Terminal Emulator: Konsole/Yakuake
OS: Arch Linux with Zen Kernel 5.15.4
Works as expected without third-party customizations: No
Asciinema recording: https://asciinema.org/a/Dz0qKoMr8YhjvQrOrQjYrBJR6

Description:
The __fish_seen_argument.fish script used when tab autocompletion is invoked throws an error when used on any directory for me. It does work if I do not type in sudo before the command. The Asciinema recording only shows me doing /etc, but I just found out that it is with every directory as long as I type sudo before it. I think this problem first appeared when I updated to the latest git build yesterday. I am using the aur/fish-git package, but manually installing fish did result in the same issue.

Stacktrace:
```
/usr/share/fish/functions/__fish_seen_argument.fish (line 8): Invalid index value
            if string match -qr "^-[A-z0-9]*$s[A-z0-9]*\$" -- $t
                                               ^
in function '__fish_seen_argument' with arguments '-s e'
in command substitution
```

What I already did:
- Delete .config/fish and .local/share/fish
- Delete /root/.config/fish and /root/.local/share/fish
- Build fresh from git
- Install
- Run fish_update_completions

**Comment by faho** [comment]
Oops, sorry!

**Comment by Kitt3120** [comment]
> Oops, sorry! Should be fixed now.

Haha that was fast, thanks! Will try after lunch.
