### ISSUE TITLE
open fish_config for root user to change prompt in shell in kde plasma 

### ISSUE THREAD

**Issue by VasuRamani** [fish-shell/fish-shell#8491]
no need of visual to report this but here is the problem i can change fish prompt as regular user with 'fish_config' command  but i would like to change prompt but i cannot open fish_config as root user here is the output
~ ❯❯❯ su
Password: 
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
root@Manjaro /h/vansh# fish_config
Web config started at file:///tmp/web_configzezhdi2y.html
Hit ENTER to stop.

Shutting down.
root@Manjaro /h/vansh# 
___________________
so that's it is i want to update prompt from '#' to '~ ❯❯❯' so please help me.

**Comment by faho** [comment]
Well, what does your browser do? Does it open?

What happens when you open that file:// link in a browser?

**Comment by faho** [comment]
Also, in fish >= 3.3.0, you can skip the web interface:

```fish
fish_config prompt save arrow
```

To load the "arrow" prompt and persist it. Use `fish_config prompt show` to see all prompts right in your terminal.

**Comment by faho** [comment]
Ah, okay, the file of course won't be world-readable. Yeah, I don't think we want to change that. Use the CLI-picker for root.

**Comment by VasuRamani** [comment]
> Well, what does your browser do? Does it open?
> 
> What happens when you open that file:// link in a browser?

after 'hit the enter it doesn't open but i'll try "fish_config prompt show" this '

**Comment by faho** [comment]
Okay, question was answered, unfortunately I don't believe there's anything we can do here. Closing!
