### ISSUE TITLE
Test suite failure on OpenBSD when colorls is installed

### ISSUE THREAD

**Issue by rapenne-s** [fish-shell/fish-shell#8492]
Hi

**My system**
fish --version = `fish, version 3.3.1-324-g971073d42`
uname -a = `OpenBSD daru.lan 7.0 GENERIC.MP#23 amd64`
echo $TERM = `xterm-256color`

**Issue**
When I run "make test" in the cmake build directory, I have a failure when `colorls` is installed in the system. There was an OpenBSD specific change to pick up `colorls` instead of `ls` when the binary is available but it seems it broke the test. See https://github.com/fish-shell/fish-shell/pull/8035

```
test project /home/testuser/fish/fish-shell/build
  1/223 Test #119: features-nocaret5.fish....................***Failed    0.59 sec
Testing file checks/features-nocaret5.fish ... Failure:

  The CHECK on line 2 wants:
    {{ls|/abavojijsdfhdsjhfuihifoisj}}: {{.*}}

  which failed to match line stdout:1:
    colorls: /abavojijsdfhdsjhfuihifoisj: No such file or directory

  Context:
    colorls: /abavojijsdfhdsjhfuihifoisj: No such file or directory <= does not match CHECK '{{ls|/abavojijsdfhdsjhfuihifoisj}}: {{.*}}' on line 2

  when running command:
    ../test/root/bin/fish --features no-stderr-nocaret -c 'ls /abavojijsdfhdsjhfuihifoisj ^&1'

```

**Comment by faho** [comment]
Yeah, we don't really care what produces the error here, we're testing the redirection.

I've picked `cat` for now, if that turns out to be an issue there are other things we can try.
