### ISSUE TITLE
Stop linking to StackOverflow

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#8495]
I'm quite annoyed by how many questions on StackOverflow are closed as "off-topic" and users redirected to Superuser.

The rules are also enforced inconsistently and are hard to figure out. Basically it comes down to who sees your question first if it'll be closed or not.

For instance a question for how to generate a completion file is apparently on topic, but setting $PATH is off-topic.

So pointing users there is doing them a disservice, because they might just get their question closed.

I don't actually believe Superuser is a great fit, either, and I've become quite disillusioned with the stack* system (mainly around old questions), so I would also be okay with removed it entirely.

**Comment by faho** [comment]
We could also change it to https://unix.stackexchange.com/questions/tagged/fish, which we apparently don't currently link at all?

**Comment by zanchey** [comment]
Yes, I think Unix&Linux is the right StackExchange site - the questions and answers definitely seem to be higher quality than SuperUser.

**Comment by faho** [comment]
Okay, after talking to one of the moderators responsible for closing the bulk of questions today and being met by a big wall of RULES TEXT, I have become sufficiently annoyed to actually do this.

The README and the site now point to Unix&Linux, and the readme even tells people that Stackoverflow is not the right place to go.
