### ISSUE TITLE
Prefer `apt` over `apt-get` in README and other guides

### ISSUE THREAD

**Issue by TonalidadeHidrica** [fish-shell/fish-shell#8497]
Currently the installation guide in `README.md` suggests the following commands:

```
sudo apt-add-repository ppa:fish-shell/release-3
sudo apt-get update
sudo apt-get install fish
```

However, `apt` is more user-friendly than `apt-get`, so we may replace this instruction with `apt`.
A similar message is shown when running `sudo apt-add-repository ppa:fish-shell/release-3` too, so it's desirable it's fixed too.  I don't know where the message is defined though.

**Comment by zanchey** [comment]
That's still the instructions that Launchpad provides, so I'm not sure what the story there is.

Do you actually get a warning with `apt-get`?

**Comment by TonalidadeHidrica** [comment]
@zanchey Nope.  And it is not actually "deprecated" to use `apt-get` at all.

I personally prefer `apt` because "apt is designed for end-users (human)" ([ref](https://askubuntu.com/a/446484), and actually `apt` provides user-friendly interface like colored texts and progress bars.  So it's just the matter of "what you like," and if you don't really feel like going for it, feel free to close this issue.
