### ISSUE TITLE
Try rely on GNU tools in completions when possible

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#8501]
I suggest to rely on GNU tools in completions to make them more consistent. If some GNU tool has options supported only by it I think it's better to find way to determine when it's exactly a GNU tool and only in in this case suggest specific flags/options instead of removing them from completion. ;)

**Comment by faho** [comment]
If you want to use a thing to *generate* the completions, it should wherever possible be the standard version or a widely supported subset (e.g. find has `-print0`, which all versions I know support even tho I think it's not in POSIX).

If you want to give completions for a tool, then yes, feel free to check if it's a GNU version. We already do this in a bunch of places (e.g. the [ls completions](https://github.com/fish-shell/fish-shell/blob/master/share/completions/ls.fish)). If you know of more, simply submit a PR.

I don't believe there's a need to keep an issue open for this.
