### ISSUE TITLE
Scrolling selected completion description left/right

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#8508]
Sometimes completion descriptions are too long so even fullscreen doesn't help. It will be nice if active completion description can be scrolled left/right via some customizable shortcuts.

Another option is to allow descriptions span for multiple lines. But I think the user must decide what he prefers if these two capabilities are implemented.

**Comment by faho** [comment]
I do not see a use case for descriptions that long. They should simply be shortened.

**Comment by EmilySeville7cfg** [comment]
I understand it, but the problem becomes bigger when options are long themselves so there is less space for descriptions.
