### ISSUE TITLE
fish_key_reader ^C warning isn't right anymore

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#8510]
Start fish_key_reader, and hit control-C. I'm seeing the notice that you must hit it again in order to quit however it does exit.

```fish
> fish_key_reader
Press a key:
Press [ctrl-C] again to exit
bind \cC 'do something'
> 
```

**Comment by faho** [comment]
This should only be shown for "--continuous" mode, it makes no sense when reading just one key.

**Comment by floam** [comment]
Not sure it's actually a regression, at least, it's present in 3.3.1.

**Comment by floam** [comment]
Well, I went ahead and checked 2.3.0, it's not present there. Welp!

**Comment by zanchey** [comment]
We usually keep the regression label for things introduced since the last major version, especially as they need to be fixed and don't necessarily need to be noted in the release notes.

**Comment by floam** [comment]
And I was wrong about 3.3.1. This bug has been present since forever.
