### ISSUE TITLE
Export env variable containing PATH in its name

### ISSUE THREAD

**Issue by alexxbb** [fish-shell/fish-shell#8513]
fish --version:  3.3.1

```sh
set -x FOO a:b
echo $FOO
a:b
```
```sh
set -x FOO_PATH a:b
echo $FOO_PATH
a b
```

What is the proper way to export FOO_PATH separated by `:`? (p.s `string join` doesn't work either)

**Comment by faho** [comment]
Calling a variable "...PATH" automatically makes it a [path variable](https://fishshell.com/docs/current/language.html#path-variables). Inside fish, they are treated as a list, but when exported, they are joined with `:`. See e.g. `env | grep FOO_PATH`.

They will also be joined with `:` when used quoted:

```fish
> echo "$FOO_PATH"
a:b
```

So: There's nothing more you need to do, it's already happening.

To manually make a variable not a path variable, use `set --unpath`.

**Comment by alexxbb** [comment]
Oh I see, this was a little unexpected, but makes sense! Thanks Fabian.
