### ISSUE TITLE
ffmpeg completion error

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#8514]
Attempt to complete something like the `-filter` example from the [documentation](https://ffmpeg.org/ffmpeg-filters.html) at the first quotation mark:

`ffmpeg -i in.mov -filter 'channelmap=map=DL-FL|DR-FR' out.wav`

as in 
` ffmpeg -filter '`⇥
```
string match: Regular expression compile error: missing closing parenthesis
string match: ^-(af(ilter)?|f(ilter)?:a
string match:                         ^
```

**Comment by mqudsi** [comment]
Mea culpa; I seem to have checked in a broken version of the completions! I’m not even sure if I have the working copy or if it was overwritten. The current error you ran into is easy (missing trailing parenthesis) but it looks like part of the implementation is missing.

**Comment by mqudsi** [comment]
Thanks, @faho.
