### ISSUE TITLE
Incorrectly named release packages for impish

### ISSUE THREAD

**Issue by kaddkaka** [fish-shell/fish-shell#8515]
The release packages for Ubuntu impish seem to be incorrect here: https://launchpad.net/~fish-shell/+archive/ubuntu/release-3/+packages

They are named hirsute but I'm not sure if there are other problems as well.

**Comment by zanchey** [comment]
They're the hirsute binaries, but they'll work fine. This is deliberate - Launchpad won't rebuild a package I've already uploaded for a new distribution, and to go back and regenerate the packaging and signatures for a new distribution is a lot more work than just copying the old packages forward.
