### ISSUE TITLE
set fish_color_* completions are incomplete

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#8518]
Fish version: 3.3.1-682-g0cd3ed4b8-dirty (built from source)
OS version: Linux Mint 20.2 Cinnamon

Fish suggests only `-background`|`--bold`|`--long` on tab for set command:

![image](https://user-images.githubusercontent.com/42812113/144368718-d7a63087-37ba-44bc-9033-bfc2dd433ea3.png)

while there are also: `--dim`|`--italics`|`--reverse`|`--underline`.

Also this options are suggested for not [syntax highlighting variables](https://fishshell.com/docs/current/interactive.html#variables-color).

**Comment by floam** [comment]
and --long should not be there. I'll take care of this.
