### ISSUE TITLE
[I] character before command

### ISSUE THREAD

**Issue by Scramjet-0** [fish-shell/fish-shell#8534]
I don't know why but one time i opened my terminal and an ugly [I] appeared just before the command, idk how to remove it:
![image](https://user-images.githubusercontent.com/64070810/145102686-aa46dcf2-1a23-4a20-acbb-fb17100127bb.png)

**Comment by Scramjet-0** [comment]
Resolved: 
cd /usr/share/fish/functions
sudo nano fish_mode_prompt.fish 
comment lines

**Comment by faho** [comment]
You have enabled vi-mode. If you don't know what that is, you want to disable it again.

Run

```fish
fish_default_key_bindings
```

to go back to the defaults.

Also:

Don't just modify files in /usr. They will be overwritten on upgrade.

If you wish to override a function in /usr, make a file of the same name in ~/.config/fish/functions.

Or, simpler, run `funced fish_mode_prompt`, make the changes you want and run `funcsave fish_mode_prompt` once you're happy.

Also next time please do check the documentation before opening an issue, this is [an FAQ entry](https://fishshell.com/docs/current/faq.html#why-does-my-prompt-show-a-i)
