### ISSUE TITLE
fish_config looping when trying to draw any page other than colors

### ISSUE THREAD

**Issue by macarr** [fish-shell/fish-shell#8535]
Fish version: fish, version 3.3.1

OS: Windows 11, 22000.348, using WSL2 with Ubuntu 20.04.1 LTS

I've somehow mucked up my fish install to the point that when I attempt to use any tab in fish_config beyond colors, the UI hangs rendered but un-populated, and the terminal appears to spit out a constant loop of fish scripts.

![image](https://user-images.githubusercontent.com/3357134/145105740-3e85b211-23ba-4dce-929b-9b4b33d00ad5.png)

Trying the same with sh -c 'env HOME=$(mktemp -d) fish' yields no such problems

**Comment by krobelus** [comment]
> Trying the same with sh -c 'env HOME=$(mktemp -d) fish' yields no such problems

Please try commenting lines in ~/.config/fish to find out what causes this

you can also add `set fish_trace 1` to your startup file, then you might see a what's going, but commenting lines sounds better

**Comment by faho** [comment]
No feedback in a week, closing. If you get back to us we'll reopen!

**Comment by macarr** [comment]
Oops, thanks for reminding me. It ended up being `pyenv init - | source`. Hilariously, after I validated that it worked without that line, I added the line back and it started working again?

Who knows. Probably not your bug anyways. Thanks for the assistance!
