### ISSUE TITLE
complete --condition given multiple times should complicate predicate

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#8536]
So, it seems like currently this is basically strange undefined behavior:

```fish
$ complete foo -n false -n true -x -a bar
$ complete -C'foo '
bar
$ complete --erase foo
$ complete foo -n true -n false -x -a bar
$ complete -C'foo '
<file completions>
```

I propose this should have been equivalent to: `complete foo -n "false; and true" …`.

**Comment by krobelus** [comment]
Yeah, that sounds better. Looks like we ignore all but the last -n

**Comment by floam** [comment]
There might be an argument it could be equivalent to `or`, but a quick grep suggests `and` is more useful:

```
~/s/f/s/completions (master|💩2…) $ grep -r ' -n .* and.*-d' | count
398
~/s/f/s/completions (master|💩2…) $ grep -r ' -n .* or.*-d' | count
51
```
