### ISSUE TITLE
Man for bind command is incomplete

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#8539]
Fish version: 3.3.1-682-g0cd3ed4b8-dirty (built from source)
OS version: Linux Mint 20.2 Cinnamon

There is no syntax described in synopsis for a such case:

```fish
# in __fish_shared_key_bindings
bind --preset $argv -k right forward-char
```

where I can specify mode without `-M`|`--mode` option.

**Comment by faho** [comment]
This is quite simply no mode given at all, in which case it defaults to, well, "default".

That's what the `[]` brackets mean - it's *optional*.

So this is that case:

        bind [(-M | --mode) MODE] [(-m | --sets-mode) NEW_MODE] [--preset | --user] [(-s | --silent)] [(-k | --key)] SEQUENCE COMMAND [COMMAND...]

No `-M´, no `-m`, no `-s`, but a `--preset` and a `-k`.
