### ISSUE TITLE
Make invalid Unicode escapes a tokenizer error

### ISSUE THREAD

**Issue by krobelus** [fish-shell/fish-shell#8545]
We report a tokenizer error on some invalid escape sequences

	$ echo \777
	fish: Invalid token '\777'
	echo \777
	     ^
but on others we silently interpret them as NUL bytes, which breaks many of our internal assumptions.

	$ echo \utest

	$

The fixes to https://github.com/fish-shell/fish-shell/issues/8195 fixed resulting issues in autoloading.
We should report a tokenizer error and maybe revert the fixes.

**Comment by faho** [comment]
A very simple fix would be possible:

https://github.com/fish-shell/fish-shell/blob/6fcb6f77be8e5d6cdcc1447cbf5383db7394400a/src/common.cpp#L1229-L1234

Make that `if (res > 0 && res <= max_val)`. If no valid unicode escape is read this stays at 0.

That has the side effect of making `\x00` an error as well, which is probably correct considering it can't be passed to commands, not even (currently) to builtins. So it causes things like #8468, which we currently answer by saying "don't do that, then", when, as far as I can tell, the only use for these is in `string replace -r` inside quotes. This could be handled with a flag to indicate NULLs are acceptable.

The error message might need some work (this would error with "invalid token" with no further explanation).

**Comment by faho** [comment]
I went for the simple fix - no digits are rejected. Other things, including NULLs (which are unusable in most contexts) can be done later.
