### ISSUE TITLE
Alias not working due to syntax problem

### ISSUE THREAD

**Issue by PeterDauwe** [fish-shell/fish-shell#8546]
fish, version3.3.1
Arch Linux - Alacritty

Hello , i have an alias in bash that does not work in fish. Could you have a look and tell me where i went wrong.

```
# # ex = EXtractor for all kinds of archives
# # usage: ex <file>
ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *.deb)       ar x $1      ;;
      *.tar.xz)    tar xf $1    ;;
      *.tar.zst)   tar xf $1    ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}
```

**Comment by faho** [comment]
What is wrong is that fish is not bash, on purpose. The syntax is almost entirely incompatible. You'll want to brush up on [the docs](https://fishshell.com/docs/current/index.html).

Here's a quick, incomplete, translation:

```fish
function ex
    if test -f "$argv[1]"
        switch $argv[1]
            case '*.tar.bz2'
                tar xjf $argv[1]
            case '*.tar.gz'
                tar xzf $argv[1]
            case '*.bz2'
                bunzip2 $argv[1]
            case '*.rar'
                unrar x $argv[1]
        end
   else
       echo "'$argv[1]' is not a valid file"
   end
end
```

**Comment by PeterDauwe** [comment]
TX , super.
Now i understand

alias skel='[ -d ~/.config ] || mkdir ~/.config && cp -Rf ~/.config ~/.config-backup-$(date +%Y.%m.%d-%H.%M.%S) && cp -rf /etc/skel/* ~'

This is not working either so i have to rewrite it to fish-language. No $ and so on..

**Comment by krobelus** [comment]
> alias skel='[ -d ~/.config ] || mkdir ~/.config && cp -Rf ~/.config ~/.config-backup-$(date +%Y.%m.%d-%H.%M.%S) && cp -rf /etc/skel/* ~'

This works in the upcoming release

Note that you can always put your aliases in separate scripts, then they work in any shell and also with utilities like sudo/timeout/gdb/strace..

**Comment by faho** [comment]
Question was answered, closing.
