### ISSUE TITLE
Global PATH recreated for every new session even universal exported PATH exits

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#8551]
Fish version: 3.3.1-637-gef33ec2f6 (built from source)
OS version: Linux Mint 20.2 Cinnamon

When I run `set --global --erase PATH` I expect universal exported (by myself) PATH to be visible permanently. But when I start new session I again get the old global PATH variable with the old value. It is confusing because I don't understand why global variable is created implicitly and it prevents me from changing universal PATH and make made changed visible.

I assume that this happens due to this function in `/usr/local/share/fish/config.fish`:

```fish
function __fish_reconstruct_path -d "Update PATH when fish_user_paths changes" --on-variable fish_user_paths
    # Deduplicate $fish_user_paths
    # This should help with people appending to it in config.fish
    set -l new_user_path
    for path in (string split : -- $fish_user_paths)
        if not contains -- $path $new_user_path
            set -a new_user_path $path
        end
    end

    if test (count $new_user_path) -lt (count $fish_user_paths)
        # This will end up calling us again, so we return
        set fish_user_paths $new_user_path
        return
    end

    set -l local_path $PATH

    for x in $__fish_added_user_paths
        set -l idx (contains --index -- $x $local_path)
        and set -e local_path[$idx]
    end

    set -g __fish_added_user_paths
    if set -q fish_user_paths
        # Explicitly split on ":" because $fish_user_paths might not be a path variable,
        # but $PATH definitely is.
        for x in (string split ":" -- $fish_user_paths[-1..1])
            if set -l idx (contains --index -- $x $local_path)
                set -e local_path[$idx]
            else
                set -ga __fish_added_user_paths $x
            end
            set -p local_path $x
        end
    end

    set -xg PATH $local_path # <---
end
```

Is there any reason to set global PATH instead of change any PATH available from the current context?

**Comment by faho** [comment]
The global PATH is inherited from the parent process. There is nothing fish can do about this.

This is why $fish_user_paths exists, use it instead of a universal $PATH.

See https://fishshell.com/docs/current/faq.html#why-doesn-t-set-ux-exported-universal-variables-seem-to-work.

This is also one of the reasons we want to replace universal variables.

**Comment by faho** [comment]
Question was answered, closing.
