### ISSUE TITLE
Please reconsider the recently added ls -F parameter

### ISSUE THREAD

**Issue by page-down** [fish-shell/fish-shell#8555]
In the master branch, a new `-F` parameter was added to the `share/functions/ls.fish` function in September,
which resulted in adding distinguishing characters (e.g. / *, etc.) to the end of folder and file names，
even though colors were already used to distinguish between files.

This parameter is introduced in the following commit.

https://github.com/fish-shell/fish-shell/commit/6c8b0a1245174328b53ebebc334613f560906025

It seems to me that the design intent of the following code in ls.fish is:
To find and use the first parameter that can be used to distinguish the file, giving priority to the color.

```fish
# ...
for opt in --color=auto -G --color -F
    if command ls $opt / >/dev/null 2>/dev/null
        set -g __fish_ls_color_opt $opt
        break
    end
end
# ...
```

Since it is now forced to add `-F` to `ls`, it is not as clear and concise as before. There is no need to add identifier characters after the file name for all users by default. (Only when the ls color is not in effect.) I personally think fish 3.3.1 is more user-friendly with the default ls parameter. And users can add their own parameters if they want.

And as @floam has pointed out, there is a comment in `ls.fish` that indicates that there may be a problem with `-F`.

https://github.com/fish-shell/fish-shell/commit/6c8b0a1245174328b53ebebc334613f560906025#commitcomment-57017310

```text
# OpenBSD ships a command called "colorls" that takes "-G" and "-F",
# but there's also a ruby implementation that doesn't understand "-F".
# Since that one's quite different, don't use it.
```

Please reconsider forcing the use of the ls `-F` parameter, thank you.

**Comment by faho** [comment]
It's not recently introduced, it's recently *re*-introduced. It was accidentally broken.

Our ls function is a simple default. If you don't like it, make your own. It's really quite easy - `funced ls`.

Sorry, but no.

**Comment by page-down** [comment]
> # but there's also a ruby implementation that doesn't understand "-F".
> # Since that one's quite different, don't use it.

```text
ls
colorls: invalid option: -F
```

Hmm, I found a problem while using it and that's why I posted this issue.

Anyway,  I guess it's a good `feature` in 3.2.0 and it makes sense.

Thanks for all your hard work and have a nice day.

**Comment by floam** [comment]
ls.fish did have a way of not applying -F for that colorls, but I don't think we should desire to not apply -F in general.
