### ISSUE TITLE
Locale fallback breaks locales and encoding on systems that don't have en_US.UTF-8

### ISSUE THREAD

**Issue by cgevans** [fish-shell/fish-shell#8557]
The resolution of #277 by commit [0a51b17](https://github.com/fish-shell/fish-shell/commit/0a51b177168a1806af9743fc495bd7704fa15301) caused fish to silently set LC_CTYPE to en_US.UTF-8 if it does not get a locale from elsewhere, even if this is not a valid locale on the system.

The comment at the end of that commit suggests that the intention here was to set the character encoding to UTF-8, but on machines that don't have en_US (for example, outside of the US), it doesn't do that, and instead sets an invalid locale.  This causes a number of problems (in my case, line editing and prompts broke subtly, as well as non-ASCII characters, as expected).

The commit does check for default locales in a few places, but not `/etc/default/locale`, the location that Debian and (I think) Ubuntu use.

My specific case here is connecting to a Debian 11 system (with en_IE.utf8), via SSH, from an Arch Linux system (which does not set `SendEnv LANG LC_*`, as Debian systems do).

I'm not sure what a better option is here than current behaviour, however:

1. It would make sense to check `/etc/default/locale` in order to support Debian.  It appears that this would only require adding it to the list of checked files.
2. Checking `locale -a` to see whether en_US.UTF-8 is a supported locale before setting it might be possible, but might not be portable or cheap.
3. Setting a hardcoded US locale when a locale is not set (and most other shells would assume C and leave the locale unset) seems surprising, and does cause problems outside the US; it might make sense to reconsider this, or warn the user.

**Comment by floam** [comment]
> It seems to me if we cannot determine a safe locale on a machine to switch to, we should leave it a-is.

I agree.

**Comment by floam** [comment]
> Setting a hardcoded US locale when a locale is not set (and most other shells would assume C and leave the locale unset) seems surprising, and does cause problems outside the US; it might make sense to reconsider this, or warn the user.

I agree. It seems to me if we cannot determine a safe locale change to upgrade to UTF-8, we should leave it as-is.

**Comment by faho** [comment]
>Setting a hardcoded US locale when a locale is not set 

This is *not* a US locale. This is a *UTF-8* locale.

It's LC_CTYPE, which is the encoding value. The "en_US" bit is essentially superfluous, we just unfortunately need to pick one because it's how locales work.

>The comment at the end of that commit suggests that the intention here was to set the character encoding to UTF-8, but on machines that don't have en_US (for example, outside of the US), it doesn't do that, and instead sets an invalid locale.

It does basically the same thing as having a locale of C. So if you don't have it it simply doesn't help.

This is a fallback's fallback's fallback, and it is unfortunately the best we can do until systems all grow a C.UTF-8 locale (which seems to be heading to POSIX)

**Comment by floam** [comment]
How is that not a bug? What fish is doing isn't something that should work.

**Comment by faho** [comment]
Fish can choose to either do nothing, in which case things are broken, or it can choose to do something, in which case things might be unbroken or might stay broken.

**Comment by floam** [comment]
Isn't this just something that happens in the situation where the locale is not already set?

**Comment by floam** [comment]
That shouldn't be an emergency.

**Comment by faho** [comment]
We do this when locale isn't set to try to upgrade from the implied default of "C", yes.

If we didn't do this things would be broken in the same manner as they are if it doesn't succeed.

**Comment by floam** [comment]
zsh on first glance works fine under C, considering how UTF-8 works. 
<img width="340" alt="image" src="https://user-images.githubusercontent.com/291142/146634316-9f02b84f-cc4c-4669-884a-8eef4f486fe8.png">

**Comment by floam** [comment]
we should just work no worse than the others in this kind of situation. And not care.

**Comment by floam** [comment]
<009f><008e><0084> is just what occurred when I hit paste.

**Comment by faho** [comment]
We do care more because we do a bunch of cursor movement, which needs the width, which needs wcwidth to work.

Many other string functions also just simply don't make sense for non-ASCII characters in a C locale.

This is why we try our darndest to upgrade the locale from C.

----------------

Okay, going back to the issue at hand:

I believe the only thing we can do here is to also read /etc/default/locale, in addition to #8031 that should make it as air tight as we can.

Like I said: If the prompt is broken now, it would also be broken with C.

**Comment by cgevans** [comment]
Would it make sense to try using C.UTF-8, or to try to check for a valid setting with locale -a, or, since this is a fallback to a fallback, to give a warning to the user?  As it is now, if this fallback is used, the prompt is broken, but it's not clear to the user as to why, since, as floam points out, every other shell seems to just work with these settings, while fish doesn't (it's not clear to me if this is because other shells are just ignoring this entirely and using UTF-8 anyway?).

**Comment by faho** [comment]
>Would it make sense to try using C.UTF-8

Not at the moment, no. C.UTF-8 isn't in POSIX, and, from my experience, not available often enough to matter. That might change in future.

> to try to check for a valid setting with locale -a

Not every system *has* a `locale` command, let alone `locale -a`.

> if this fallback is used, the prompt is broken

If this fallback has to be used, it's *already* broken. If the fallback *works*, it will unbreak the prompt. At no point does it make things worse.
