### ISSUE TITLE
macOS package requires Rosetta to install

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#8566]
While the binaries in the .pkg are universal, there is a missing bit of magic in some XML that leads Installer to not be aware this install will not require Rosetta. @ridiculousfish is aware but here's an issue so we don't forget.

Users are unlikely to notice unless they do not already have Rosetta installed, as this triggers a prompt that requires downloading and installing Rosetta to continue.

<img width="637" alt="Screen Shot 2021-12-20 at 9 50 51 PM" src="https://user-images.githubusercontent.com/291142/146878566-e54cf9f6-0399-4dd3-aa60-6767843c1dca.png">

**Comment by floam** [comment]
(If you hit Not Now, it will not continue the installation, either: 
<img width="321" alt="image" src="https://user-images.githubusercontent.com/291142/146878875-47876c4f-4786-434b-90a9-8642e35d5780.png"> )

**Comment by floam** [comment]
To reproduce if you already have Rosetta installed: 

Get a list of rosetta files:
```
$ pkgutil --files com.apple.pkg.RosettaUpdateAuto
Library
Library/Apple
Library/Apple/usr
Library/Apple/usr/lib
Library/Apple/usr/lib/libRosettaAot.dylib
Library/Apple/usr/libexec
Library/Apple/usr/libexec/oah
Library/Apple/usr/libexec/oah/debugserver
Library/Apple/usr/libexec/oah/libRosettaRuntime
Library/Apple/usr/libexec/oah/runtime
Library/Apple/usr/libexec/oah/translate_tool
Library/Apple/usr/share
Library/Apple/usr/share/rosetta
Library/Apple/usr/share/rosetta/rosetta
```

Disable System Integrity Protection / delete the listed files in Recovery mode. Reboot and you'll hit the first run experience when you try to execute an x86-64 binary or install fish shell.

**Comment by ridiculousfish** [comment]
Also see #7505. Any idea what the "missing bit of magic in some XML" is?

**Comment by floam** [comment]
Check the gitter.im history, I think a key like hostDistributions  or hostArchitectures or something.  It should be like x86-64, arm64.

**Comment by floam** [comment]
https://developer.apple.com/library/archive/documentation/DeveloperTools/Reference/DistributionDefinitionRef/Chapters/Distribution_XML_Ref.html#//apple_ref/doc/uid/TP40005370-CH100-SW41

hostArchtectures="x86_64,arm64"

**Comment by floam** [comment]
On https://github.com/fish-shell/fish-shell/blob/master/build_tools/osx_distribution.xml. 

I can't try it myself, a) I'm kind of hazy on the workflow b) my daughter spilled a pitcher full of bathtub water onto my M1 MacBook Air. The magic smoke came out. I sold some stuff and should have an M1 MBP on the way soon though.
