### ISSUE TITLE
`time` keyword doesn't work after variable assignment list

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#8568]
```fish
FOO=bar time sleep 1
<prints man page>
```

The parse tree indicates that `time` is expected before the variable assignment list. As in `time FOO=BAR command …`

```
 echo time sleep 1 | fish_indent --dump-parse-tree
job_list
! job_conjunction
! ! job
! ! ! keyword: time
! ! ! variable_assignment_list
! ! ! statement
! ! ! ! decorated_statement
! ! ! ! ! string: 'sleep'
! ! ! ! ! argument_or_redirection_list
! ! ! ! ! ! argument_or_redirection
! ! ! ! ! ! ! argument: '1'
! ! ! job_continuation_list
! ! job_conjunction_continuation_list
! ! <;>
```

Was this intentional? it seems like it should work more or less like `command` - a decorated statement.

**Comment by ridiculousfish** [comment]
[It's that way in the AST](https://github.com/fish-shell/fish-shell/blob/36be635393b52ecd11461203ed86e327748f8f4f/src/ast.h#L499). It makes some sense since `time` affects the entire pipeline, while variables affect only a single process.

**Comment by dahuigeniu** [comment]
thankyou

**Comment by faho** [comment]
Okay since `time` affects the entire pipeline this seems to be correct.
