### ISSUE TITLE
Fish_vi_mode cursor one char behind

### ISSUE THREAD

**Issue by hamon-e** [fish-shell/fish-shell#8569]
Why don't we keep the cursor at the end of line when we press escape to go in normal mode ?

The backward-char here
https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_vi_key_bindings.fish#L74

Personally I removed it
Before to autocomplete I add to do `vim<ESCAPE>ll` (the first l to go to the end of line)
now I just have to do `vim<ESCAPE>l`

**Comment by faho** [comment]
This is what vim does, see fcc363333cfa32a3391596b1808cbbb08f74bc6, #1391.
