### ISSUE TITLE
problem with UTF8 encoding in the completion text output

### ISSUE THREAD

**Issue by peutch** [fish-shell/fish-shell#8575]
OS: Debian GNU/Linux bookworm/sid amd64
Fish: 3.3.1
$TERM: xterm-256color

Hi,
I am getting the famous ASCII character (�) in place the right one when it is UTF8 encoded in the completion text output.
Not sure if this is a trouble with FISH or the completion script it-self or an issue with Debian or something more general...

Thanks,
Patrice

```
~>` sudo apt install qma<TAB>
qmake6        (Qt 6 qmake Makefile generator tool)  qmake6-bin-dbgsym                     (debug symbols for qmake6-bin)  qmapshack-dbgsym  (debug symbols for qmapshack)
qmake6-bin  (Qt 6 qmake Makefile generator tool �)  qmapshack  (cartographie GPS (GeoTiff et vectorielle) et gestion d�)
```

**Comment by faho** [comment]
Please give the output of `locale`.

**Comment by peutch** [comment]
Here it is:
```~> locale
LANG=fr_FR.UTF-8
LANGUAGE=
LC_CTYPE="fr_FR.UTF-8"
LC_NUMERIC=fr_FR.UTF-8
LC_TIME=fr_FR.UTF-8
LC_COLLATE="fr_FR.UTF-8"
LC_MONETARY=fr_FR.UTF-8
LC_MESSAGES="fr_FR.UTF-8"
LC_PAPER=fr_FR.UTF-8
LC_NAME=fr_FR.UTF-8
LC_ADDRESS=fr_FR.UTF-8
LC_TELEPHONE=fr_FR.UTF-8
LC_MEASUREMENT=fr_FR.UTF-8
LC_IDENTIFICATION=fr_FR.UTF-8
LC_ALL=
```

**Comment by zanchey** [comment]
That symbol is coming from the package description, which is "Qt 6 qmake Makefile generator tool — binary file"

**Comment by faho** [comment]
@zanchey Can you reproduce this? I have no idea what should be failing here.

**Comment by zanchey** [comment]
I can't reproduce it exactly - my terminal interprets things slightly differently so I just get some mucked up spacing.

I can see what's causing the issue. `__fish_print_apt_packages` uses `tr`, and GNU's version is [not UTF-8 clean/multibyte aware](https://unix.stackexchange.com/questions/228558/how-to-make-tr-aware-of-non-asciiunicode-characters). Let's just switch to `string` here.
