### ISSUE TITLE
Pass all of `$argv` to `pk-command-not-found`

### ISSUE THREAD

**Issue by septatrix** [fish-shell/fish-shell#8579]
When encountering an unknown command fish defers to different handlers.
In #365 it was changed that these handlers receive all of `$argv` though that was quickly reverted as some handlers are unable to cope with that (3559f20c8ffca8b036ff4aa6833e9e4c67eea7fc and 7a1fc028e309beef98fda54060d8f77aac377e6d).

Some handlers like PackageKit however are able to deal with them and properly pass them along when executing the fixed commands.

```fish
~ $ grep SingleMatch /etc/PackageKit/CommandNotFound.conf  # this is just for demonstration
SingleMatch=ask
~ $ /usr/libexec/pk-command-not-found mna --version
fish: mna: command not found...
Run similar command: man [Y/n] y


man 2.9.4
~ $ mna --version
fish: mna: command not found...
Run similar command: man [Y/n] y


What manual page do you want?
For example, try 'man man'.
~ [127]$ function fish_command_not_found
             /usr/libexec/pk-command-not-found $argv
         end
~ $ mna --version
fish: mna: command not found...
Run similar command: man [Y/n] y


man 2.9.4
```

After looking at [the current implementation](https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_command_not_found.fish) I overwrote the function and everything still worked flawlessly.
I think it would be best to change this for the PackageKit handler.

<hr>

Version: 3.3.1

**Comment by ridiculousfish** [comment]
Sure, it seems reasonable to extend that logic to teach it about PackageKit. Note [some handlers receive all the arguments](https://github.com/fish-shell/fish-shell/blob/36be635393b52ecd11461203ed86e327748f8f4f/share/functions/fish_command_not_found.fish#L45). If you make a PR we'll merge it.
