### ISSUE TITLE
[Question]Why the _flag_x extracted by argparse can't be test

### ISSUE THREAD

**Issue by happyeggchen** [fish-shell/fish-shell#8582]
fish, version 3.3.
I performed tests on the _flag_x using test -z,set -q but all of then return false, I don't know why argparse will behaviour like this

I want to test if _flag_x is empty (zero string)

**Comment by faho** [comment]
https://fishshell.com/docs/current/faq.html#how-do-i-check-whether-a-variable-is-not-empty

If you want more help, please post example code. It is hard to understand what exactly you are running and where the error lies.

**Comment by happyeggchen** [comment]
Done,i use set -lx
After remove the -lx,set can overwrite it,no need to declare it multiple

**Comment by happyeggchen** [comment]
For others who searched this on Google or bing
Basically,i made a container manager using fish shell and progynosh,but i want some options in argv,i declare them using set -lx twice, actually 1 -lx can work fine,you create the variable,then you just need to use set to overwrite it
