### ISSUE TITLE
 Shift-tab is broken again (#922)

### ISSUE THREAD

**Issue by JosefLitos** [fish-shell/fish-shell#8585]
version: 3.3.1
`TERM=st-256color`

It is very weird I have this issue, since on my previous laptop, though they both run the same build of st (https://github.com/JosefLitos/st), this did not happen.
On my current laptop, when I do `infocmp $TERM | grep kcbt`, I get nothing, but on my old one, I get `^[[Z`, as I should.
Is there any possible explanation for why it is different thought the `$TERM` is the same?

**Comment by faho** [comment]
Presumably your terminfo entries differ. Either you changed it on one, you didn't update or install it, or you have different versions of the terminfo database (most likely shipped with ncurses), or you pointed fish at a different terminfo database ($TERMINFO or $TERMINFO_DIRS).

If `infocmp` already tells you backtab isn't known, it's not a fish issue. The problem lies elsewhere.

**Comment by JosefLitos** [comment]
But I have no such variables as terminfo. Is there any default value I should try?

**Comment by faho** [comment]
I *think* the default could be changed at compile time of your ncurses package, so this isn't something you'd typically change.

All I can tell you is that my st-256color entry (the one included in Arch's ncurses package) doesn't have kcbt, while for example the xterm-256color entry does.

That means either one of your systems has a different st-256color entry, or its $TERM isn't st-256color.

You'll want to see where `infocmp` gets its entries from with `infocmp -D` (e.g. /usr/share/terminfo - this will include the dirs given in $TERMINFO_DIRS), then you want to find the entry there, e.g. /usr/share/terminfo/s/st-256color (do check $TERM on both systems), then you want to see which package owns that file (`pacman -Qoq /usr/share/terminfo/s/st-256color`, assuming you're on an arch system like your bio says).

Like I said, fish has nothing to do with this. Your two systems are configured differently.

**Comment by JosefLitos** [comment]
OK, I found it simpler to reinstall my system altogether, which hepled indeed. But Maybe something else would have helped too, I just didn't want to fiddle much with it.
