### ISSUE TITLE
fish's `test` isn't as broken as the usual POSIX implementation

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#8586]
Fish's `test` implementation is non-conforming because this works in fish:

```fish
set foo ""
if test -z "$foo" -o "$foo" -eq 0
    echo success
end
```

(output: `success`)

but that isn't allowed in bash & co:
```bash
foo=""
if test -z "$foo" -o "$foo" -eq 0; then
    echo success
fi
```

(output: `bash: test: : integer expression expected`)

----

I always knew `test` was braindead but I thought I'd figured out most of its warts by now. It turns out fish was still shielding me from some of its worst. It's too bad we don't have a "won't fix" label! 😁

Edit: I added the "question" label so no one thinks I'm seriously proposing to do anything about this. I just wanted to bring a smile to fellow fish devs.

**Comment by floam** [comment]
Oh, we have a won't fix label.

**Comment by floam** [comment]
I'm feeling kinda dumb. Is it the case you can't use -o or -a after an airity 1 thing like -z?

**Comment by mqudsi** [comment]
No, it's because `test` checks the validity of all expressions before evaluating the actual test, even if it could short-circuit subsequent tests combined with boolean operators. Even in fish, `test "" -eq 0` is an error (because `test` is just very pedantic and purposely hard to work with like that); so what we're seeing is that even if there's a chance that that branch of the test will not get evaluated, `test` still errors out.

It's ironically the opposite of how bash and most other posix shells work, where they'll happily execute a script containing garbage up to the point where the garbage begins (no whole file parsing in advance).

**Comment by floam** [comment]
oh I'm blind. I somehow missed the whole "" part.

**Comment by floam** [comment]
Well, we share company with ksh93 and zsh:

~ $ ksh -c 'foo=""; test -z "$foo" -o "$foo" -eq 0 && echo success'
success
~ $ dash -c 'foo=""; test -z "$foo" -o "$foo" -eq 0 && echo success'
dash: 1: test: Illegal number: 
~ [2]$ bash -c 'foo=""; test -z "$foo" -o "$foo" -eq 0 && echo success'
sh: line 0: test: : integer expression expected
~ [2]$ zsh -c 'foo=""; test -z "$foo" -o "$foo" -eq 0 && echo success'
success

**Comment by faho** [comment]
The closer you look at `test` the worse it gets, so there's no reason to keep staring at the horror. Closing!
