### ISSUE TITLE
the evil christmas tree - don't handle well certain unicode bytes

### ISSUE THREAD

**Issue by sha0coder** [fish-shell/fish-shell#8594]
fish, version 3.0.2
3.0.2
Linux hotdog 5.10.60-amd64-desktop #3 SMP Tue Nov 9 20:52:29 CST 2021 x86_64 GNU/Linux
xterm-256color

I put a christmas tree unicode byte in a command, and many weird characters start appearing on every type. 
Every time i use that command the self-complete put that unicode byte and same weird behaviour happens.
I had to remove the byte from  ~/.local/shared/fish/fish_history

http://www.unicode-symbol.com/u/1F384.html

regards.

**Comment by IlanCosman** [comment]
fish 3.0.2 was released almost 3 years ago. I can't reproduce using fish 3.3.1.

**Comment by faho** [comment]
Please upgrade fish, 3.0.2 is missing ~35% of all released commits ever made to fish.
