### ISSUE TITLE
Error message: There is no fish_key_bindings function

### ISSUE THREAD

**Issue by ppitu** [fish-shell/fish-shell#8595]
fish, version 3.3.1
Linux mynick 5.13.0-22-generic #22-Ubuntu SMP Fri Nov 5 13:21:36 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

I install fish. And I receive this error message when when i run fish shell:

There is no fish_key_bindings function called: 'fish_default_key_bindings'
Cannot find fish_default_key_bindings, falling back to very simple bindings.
Most likely something is wrong with your installation.

But when i use:
 sh -c 'env HOME=$(mktemp -d) fish'

My shell start work correctly.

**Comment by faho** [comment]
Okay, what have you configured?

What do `set --show fish_function_path` and `type fish_default_key_bindings` say?

**Comment by ppitu** [comment]
The first:

```
set --show fish_function_path
$fish_function_path: set in global scope, unexported, with 9 elements
$fish_function_path[1]: |/home/ppitu/.config/fish/functions|
$fish_function_path[2]: |/etc/fish/functions|
$fish_function_path[3]: |/usr/share/plasma/fish/vendor_functions.d|
$fish_function_path[4]: |/home/ppitu/.local/share/flatpak/exports/share/fish/vendor_functions.d|
$fish_function_path[5]: |/var/lib/flatpak/exports/share/fish/vendor_functions.d|
$fish_function_path[6]: |/usr/local/share/fish/vendor_functions.d|
$fish_function_path[7]: |/usr/share/fish/vendor_functions.d|
$fish_function_path[8]: |/var/lib/snapd/desktop/fish/vendor_functions.d|
```

And the second:
```
type --short fish_default_key_bindings
fish_default_key_bindings is a function (defined in /usr/share/fish/functions/fish_default_key_bindings.fish)
```

**Comment by faho** [comment]
Well, your $fish_function_path is broken - it doesn't include /usr/share/fish/functions, which is the normal function directory. So any functions shipped with fish (which includes things like the key bindings, but also `help` and `funced` and a lot of completion stuff) will be missing.

Since it works with the temporary home, it seems something in your configuration breaks it.

**Comment by ppitu** [comment]
How can I add this path to fish_function_path manually?

This may be a simple question, but I don't know how to do it.

**Comment by faho** [comment]
You don't want to *add* it. It's there by default, so you want to stop whatever *removes* it. Check your configuration. Check whatever plugins you installed. See what modifies $fish_function_path.

**Comment by ppitu** [comment]
I have a clean install from apt and I did not install any plugins.

But I try to find what can remove this path.

Thanks for help ;D

**Comment by ppitu** [comment]
I solve this problem when i change fish version to 3.1.2 so I think the problem is in fish not in my config.

**Comment by krobelus** [comment]
can you check and maybe post the output of `fish_trace=1 fish -i -c ''`

(or `-c fish_default_key_bindings`)

**Comment by ppitu** [comment]
But in my work (3.1.2) or broken (3.3.1) version?

**Comment by krobelus** [comment]
in the broken one - (it should definitely work; something must be removing the function path entry)

also try creating both, and running something like `diff -u` to see what changed

**Comment by faho** [comment]
Okay, no reply in a week, closing! If you do get back to us we can of course reopen it.

Because this works without configuration, it seems very likely that this is an issue in the configuration.
