### ISSUE TITLE
Windows precompiled buid?

### ISSUE THREAD

**Issue by zohozer** [fish-shell/fish-shell#8598]
Hi. I am not atechnical savvy and for me it is quite complicated to compile the sources on Windows.

There are any chances to see a prebuild executable of Fish for Windows?

Best regards.

**Comment by zanchey** [comment]
You can get a prebuilt version for WSL or Cygwin. fish can't run in a plain Windows environment - it depends on too much Unix infrastructure.

WSL is probably your best option. Most new users start with installing Ubuntu from the Windows store, then install fish for Ubuntu via fishshell.com.

**Comment by faho** [comment]
Okay, question was answered, closing.
