### ISSUE TITLE
fish_remove_path or equivalent, or documentation update

### ISSUE THREAD

**Issue by losvedir** [fish-shell/fish-shell#8604]
```
~> fish --version                                                                                                                                                                 06:22
fish, version 3.3.1

~> echo $version                                                                                                                                                                  06:22
3.3.1

~> uname -a                                                                                                                                                                       06:22
Darwin Gabes-MacBook-Pro.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

~> echo $TERM                                                                                                                                                                     06:22
xterm-256color

~>  sh -c 'env HOME=$(mktemp -d) fish'
# yes, behavior is present
```

I know this is probably a stupid question, but I've spent a bit of time trying to figure out how to do this simple thing and haven't had any luck.

How do you remove an item from the path?

I added an item to `$PATH` using the handy `fish_add_path`:

```
~> fish_add_path "/Users/gabedurazo/Downloads"
```

I then see it in `$PATH`:

```
~/zig> echo $PATH                                                                                                                                                                 06:21
/Users/gabedurazo/Downloads [other paths...]
```

I guessed `fish_remove_path`, but that isn't a known command. So I went to the [`fish_add_path` documentation](https://fishshell.com/docs/current/cmds/fish_add_path.html), and was surprised to see no mention of it there. However, it mentioned `$fish_user_paths` and pointed me to the concept of [universal variables](https://fishshell.com/docs/current/language.html#variables-universal), so I thought maybe I was supposed to remove it manually from `$fish_user_paths`. From the documentation there, it seemed that `$fish_user_paths` is a list, and so I tried using `set -e` to remove the item following the example in the documentation there, but it didn't work:

```
~/zig> echo $fish_user_paths[1]                                                                                                                                                   06:24
/Users/gabedurazo/Downloads

~/zig> set -e $fish_user_paths[1]                                                                                                                                                 06:26
set: Variable name '/Users/gabedurazo/Downloads' is not valid. See `help identifiers`.
```

At this point, I'm not sure what to try next. I think maybe ultimately this might be a suggest a documentation fix, which I'd be happy to do.

**Comment by faho** [comment]
You can remove it the same way you would remove any other element from a list: Find he index, then erase it:

```fish
if set -l index (contains -i /path/to/whatever $PATH)
    set -e PATH[$index]
end
```

There isn't really a use for a separate command here, and removing from $PATH is somewhat of a smell - if you regularly need to do it, your system's config should be changed instead to not add it in the first place.

**Comment by losvedir** [comment]
Oh, the dollar sign! Of course, not sure how I missed that. Thanks.

**Comment by madprops** [comment]
Why isn't there a function for this? I'm baffled why fish_remove_path is not ready to use...

**Comment by faho** [comment]
Because it's not possible to do the same thing as fish_add_path.

$PATH is inherited from the parent process, there is no way to permanently remove something from it because it's set to a new value each time.

We could do a fish_remove_path that would remove your path from $fish_user_paths, but that would be confusing if that's not where the path is added, because it would appear to do nothing.

Or we could add one that removes it from $PATH, but that would be confusing if it was added again later.

And both are super easy to do yourself:

```fish
set -l index (contains -i -- /my/path/to/remove $PATH)
and set -e PATH[$index]
# or replace PATH with fish_user_paths
```

The only real solution is to not add the path in the first place.

**Comment by madprops** [comment]
I thought fish_add_path added to $fish_user_paths by default

So remove would also use that...

I ended up making a custom function:

```
function remove_path
  if set -l index (contains -i "$argv" $fish_user_paths)
    set -e fish_user_paths[$index]
    echo "Removed $argv from the path"
  end
end
```

**Comment by flokno** [comment]
Hi everyone, in particular @losvedir ,

as an answer to the original question: I think `fish_add_path` adds the given path in `~/.config/fish/fish_variables` via

```bash
...
SETUVAR fish_user_paths:/your/cutom/path/...
...
```

which means that this is the correct place to remove the path. It worked for me. Writing a script is, to my eyes, therefore not necessary.

**Comment by jcelerier** [comment]
as a newcomer to fish - what's the proper way to temporarily add something to PATH then ?
for instance I'll very often have multiple shells with different environments, and I want e.g. the things added to my PATH to only last until the shell is closed, not be added in some global way. What's the solution for that ? As everything on internet points to fish_add_path which seems not easily reversible

**Comment by caleb-allen** [comment]
@jcelerier you can use `--global` to achieve this, e.g.

```
fish_add_path --global /home/foo/bar/
```

Global variables are "specific to the current fish session" as per the docs section Variable Scope

**Comment by kockahonza** [comment]
Hi, as another non-advanced user I also can't help but feel that if there is not going to be a fish_remove_path there really ought to at least be some guidance in the man/help page on how to undo its action as the "super easy" options here are really not so for someone not familiar with the universal/global idk what else variables. In the future I will very likely just stick to editing PATH in my fish config for simplicity. If you say having a remove version would be half baked then I'd argue that already having the add version is somewhat half baked.

**Comment by naikrovek** [comment]
> This thread is absolutely baffling. Just give us a utility to remove paths from the user paths.

Well they can't provide a function that can remove a path from your environment in all cases.  They can always add to a known variable, but they can't remove a path in all cases because it isn't always possible to know how the path was added.

I am ok with a function which removes from `$fish_user_paths` and gives a message if the specified path is not found in that list.  In fact there is code higher up in this issue which does just that.  And if you can't find it, or don't like what you see, here is what I wrote to do this:

```fish
function fish_remove_path
    if set -l index (contains -i $argv[1] $fish_user_paths)
        set --erase --universal fish_user_paths[$index]
        echo "Updated fish_user_paths: $fish_user_paths"
    else
        echo "$argv[1] not found in fish_user_paths: $fish_user_paths"
    end
end
```

put that in `~/.config/fish/functions/fish_remove_path` and add it to whatever OS setup automation you have, and you're golden.

The Fish maintainers themselves can't do this because people who haven't read and understood this thread will forever be opening issues that their path entries aren't being removed by the function.  Because at any given time there's no way to know for sure how a path got put into the array.  And if it's not in `fish_user_paths` how can the function possibly know what to do in the general case?  It can't.

So, you are meant to add the function yourself and understand the limitations yourself, I think.  So that's what many of us have done.

**Comment by jcelerier** [comment]
I think you could do something like this 

```fish
function fish_remove_path
    if set -l index (contains -i $argv[1] $PATH)
        set --erase PATH[$index]
        echo "Updated PATH: $PATH"
    if set -l index (contains -i $argv[1] $fish_user_paths)
        set --erase --universal fish_user_paths[$index]
        echo "Updated fish_user_paths: $fish_user_paths"
    else
        echo "$argv[1] not found in fish_user_paths: $fish_user_paths"
    end
end
```

that said, this thread helped me understand that fish was definitely not the shell for me!

**Comment by karthikbhata97** [comment]
I have multiple machines on which i run fish. I tend to not have any special config.fish (which then i have to ship them everywhere).

But this one problem pains me. I have googled this "how to remove from fish_user_paths" a lot of times already.

I still don't understand why can't this be exposed. Maybe name it in a way that avoids confusion (fish_remove_path_only_from_the_fish_user_paths_not_from_environment_path_or_whatever).

**Comment by a-chacon** [comment]
Looking the same! It is so easy to add a new route to path with `fish_add_path` but when you have to delete. There is no a good function haha thanks for this fish. But if you add a `fish_add_path` then it will be natural for users look for a `fish_remove_path`.

**Comment by nielspeen** [comment]
The limitation should be communicated by `fish_remove_path` itself, not a GitHub issue. If `fish_remove_path` cannot remove a path because it's inherited, it can just say exactly that. 

Imagine there was no `rm` command because some people may try to remove files with permissions that prevent them from doing so. It's an unusual decision IMHO.

**Comment by krobelus** [comment]
> The limitation should be communicated by `fish_remove_path` itself,
> not a GitHub issue. If `fish_remove_path` cannot remove a path
> because it's inherited, it can just say exactly that.

good idea, we should either work on that or phase out fish_add_path

**Comment by madprops** [comment]
When `fish_remove_path` is used it should output this url: https://github.com/fish-shell/fish-shell/issues/8604#issuecomment-3674904876

**Comment by AvianAnalyst** [comment]
Just gonna reiterate what a lot of people have said: 
1. fish_add_path should, intuitively, have a mirror.
2. fish_remove_path can easily provide a failure message if it can't remove the path 

And also point out that: if someone is using fish, and configuring their user paths through fish (as i am), the case in which i want to remove a path that wasn't added via fish_add_path is nonexistant. and its wild not to have that functionality. I'm going to add it myself as a custom function, but seriously this is a really weird decision.
