### ISSUE TITLE
Text input is frozen after navigating beyond the command history 

### ISSUE THREAD

**Issue by samizdatco** [fish-shell/fish-shell#8610]
**fish version**: 3.3.1
**os**: macOS 10.14 & 12, Ubuntu Focal in Docker
`$TERM`: xterm-256color

Holding the up- or down-arrow key for any amount of time after reaching the beginning or end of the history list will cause a potentially multi-second freeze before additional inputs will be processed. The longer the arrow key is held, the more `down-or-search` commands are queued up and the longer the freeze period lasts.

Here is a video showing expected behavior for the first 5 seconds, then showing what happens when the down-arrow is held for 1 second and is immediately followed with an up-arrow keypress. Note that the up-arrow's effect of bringing back the previous command takes about 2 seconds to appear:

https://user-images.githubusercontent.com/469523/147978986-d22bdbba-e9f9-4896-bb88-632378e0b56f.mp4

Running fish in profiling mode while triggering this behavior results in an extended sequence of `down-or-search` calls:
```
25      63      > down-or-search
12      38      -> if commandline --search-mode...
13      13      --> commandline --search-mode
8       8       --> commandline -f history-search-forward
5       5       --> return
25      61      > down-or-search
10      36      -> if commandline --search-mode...
13      13      --> commandline --search-mode
8       8       --> commandline -f history-search-forward
5       5       --> return
25      81      > down-or-search
15      56      -> if commandline --search-mode...
28      28      --> commandline --search-mode
9       9       --> commandline -f history-search-forward
4       4       --> return
25      83      > down-or-search
25      58      -> if commandline --search-mode...
14      14      --> commandline --search-mode
15      15      --> commandline -f history-search-forward
4       4       --> return
32      75      > down-or-search
15      43      -> if commandline --search-mode...
14      14      --> commandline --search-mode
8       8       --> commandline -f history-search-forward
6       6       --> return
```

This seems to be a somewhat recent regression: testing on version 3.1.0 does not have this lag after stepping off the end of the history list. For comparison, here's its profiling output while holding the down-arrow:

```
30	79	> down-or-search
9	49	-> if commandline --search-mode
        commandline -f history-search-forward
        return
    ...
17	17	--> commandline --search-mode
18	18	--> commandline -f history-search-forward
5	5	--> return
30	69	> down-or-search
10	39	-> if commandline --search-mode
        commandline -f history-search-forward
        return
    ...
16	16	--> commandline --search-mode
8	8	--> commandline -f history-search-forward
5	5	--> return
27	65	> down-or-search
10	38	-> if commandline --search-mode
        commandline -f history-search-forward
        return
    ...
16	16	--> commandline --search-mode
8	8	--> commandline -f history-search-forward
4	4	--> return
```

**Comment by krobelus** [comment]
This is a side effect of bbdfe126a (Flash if history search found nothing, 2020-09-30)
I'm sure there's a simple solution

**Comment by mqudsi** [comment]
It's time-debounced in master now. Ideally, it would debounce based off the time of last input event (so it would keep flashing so long as the down key is pressed, but would stop ~immediately) but I'm not sure that's worth the complexity of implementing.
