### ISSUE TITLE
C-f SHOULD autocomplete in VI mode

### ISSUE THREAD

**Issue by zim0369** [fish-shell/fish-shell#8619]
Please map `C-f` or `C-e` to accept auto suggestion in vi mode. It is a terrible
terrible experience to go back into normal mode and press `$` twice.

**Comment by faho** [comment]
C-f is an emacs-ism. It's pretty clearly not a vi-thing, so it shouldn't be bound in vi-mode.

If you want, bind it yourself:

```fish
bind -M insert \cf accept-autosuggestion
```

**Comment by krobelus** [comment]
Also try `fish_hybrid_key_bindings`
