### ISSUE TITLE
history file location

### ISSUE THREAD

**Issue by timotheecour** [fish-shell/fish-shell#862]
where is the history file location?
can it be customized?
can fish use as starting point the zsh history file?
does it merge all terminal sessions into 1 big history file? (seems so)

suggestion:
up/down searches in global history (starting from what is currently typed)
shift up/down searches in local history

**Comment by simotek** [comment]
>> can it be customized?

> No. What customizations would you want?

In bash i use a utility i wrote called hiset this allows me to set a history session per shell, so for tasks i do regually i switch to that history session and then just have the relevent commands in my history file.

see the following for more details:
http://simotek.net/tech/projects/opensuse-e/hiset-multiple-history-files-and-sessions-for-bash-and-other-tinkering/
https://github.com/simotek/scripts-config

**Comment by oconnor663** [comment]
@ridiculousfish, the [first answer](https://github.com/fish-shell/fish-shell/issues/862#issuecomment-19138822) in this thread is high in search results, but it's out of date. Maybe we could edit that one with the new path under `~/.local`?

**Comment by ridiculousfish** [comment]
@oconnor663 Done, good catch

**Comment by supercutcat** [comment]
You can find fish_history in ~/.local/share/fish
