### ISSUE TITLE
Passing any argument with `?` character to function will rise an error

### ISSUE THREAD

**Issue by Tomualdo** [fish-shell/fish-shell#8622]
fish, version 3.3.1
OS: 20.04.2-Ubuntu
`xterm-256color`
Behaviour persists on running `sh -c 'env HOME=$(mktemp -d) fish'`

## Problem
Passing link with parameter `?` as an argument to function will rise an error

```fish
function echolink
   echo $argv[1]
end

echolink https://www.youtube.com/watch?v=xxxxxxxxx
```
>fish: No matches for wildcard “https://www.youtube.com/watch?v=xxxxxxxxx”. See \`help expand`.

## Expectation
Bash function escape this character normally
```bash
echolink(){
	echo $1
}

echolink https://www.youtube.com/watch?v=xxxxxxxxx
```
> $> https://www.youtube.com/watch?v=xxxxxxxxx

**Comment by faho** [comment]
https://fishshell.com/docs/current/faq.html#my-command-prints-no-matches-for-wildcard-but-works-in-bash

`?` is the single-character glob. Good news is: We're disabling it. There is already a flag to disable it, which will be turned on by default in future and eventually removed completely.

**Comment by faho** [comment]
Okay, question has been answered, closing!
