### ISSUE TITLE
Bind mounting .local/share/fish/fish_history file results is error.

### ISSUE THREAD

**Issue by nigelgbanks** [fish-shell/fish-shell#8627]
**System Information**

| Command   | Output |
| :--------------- | :-------- |
| `fish --version` | `fish, version 3.3.1`  |
| `uname -a`  | `Linux shadow 5.15.12 #1-NixOS SMP Wed Dec 29 11:29:03 UTC 2021 x86_64 GNU/Linux` |
| ` echo $XTERM`  | `xterm` |

I have a exceptional use case in that my system is largely ephemeral with a few exceptions. There is a set of bind mounts for configuration and any persistent information into my users home directory from a separate mount. 

I would like to keep the changes to my `fish_history` between reboots, to achieve this I've used a bind mount for the file `~/.local/share/fish/fish_history`. 

Periodically I get the following error message at the terminal (likely when the fish_history has hit some max length and wants to merge).

```fish
error: Error when renaming history file: Device or resource busy
```

This makes sense as it is bind mounted, ideally there is some work around or a better strategy? Or possibliy could bind mounts or symbolic links be supported going forward?

**Comment by faho** [comment]
>This makes sense as it is bind mounted, ideally there is some work around or a better strategy?

Bind mount the *directory*. The issue is going to be that we replace the file whole, so if the mount is one level up that should improve things.

Honestly ideally you'd bind-mount ~/.local/share, because there's a bunch of other things that may write there, but that's up to you.

**Comment by nigelgbanks** [comment]
@faho thanks for the quick response and suggestion! I kinda want as much to be ephemeral or generated by Nix as possible, so that any file not generated by Nix is lost on reboot (with the exception of the history of course). But what you suggest is probably the most reasonable compromise. I'll do a bind mount for `~/.local/share/fish` and close this ticket.
