### ISSUE TITLE
Improper handling of combined focus+resize events on master and 3.3.1

### ISSUE THREAD

**Issue by gravndal** [fish-shell/fish-shell#8628]
In tmux with `$ tmux set focus-events on` fish will put "garbage" in the command line when it receives/loses focus after closing/creating a split window.

Bisect:
```
7c153a8307c662fa853280fd64657dff0cd9a625 is the first bad commit
commit 7c153a8307c662fa853280fd64657dff0cd9a625
Author: ridiculousfish <rf@fishshell.com>
Date:   Sat Apr 10 20:41:33 2021 -0700

    Introduce prepare_to_select, fixing job_summary.py

    This concerns printing status messages for background jobs which have
    stopped or finished. Previously fish would do this from two places:

    1. Before running a command (including empty string)
    2. If a signal is received during select()

    So if the job finishes while fish is doing something else (like running an
    event handler) then we would not print status messages until the user hit
    return. This caused the job_summary.py test to be flaky.

    Fix this by splitting the interrupt handler into two parts: a part that
    handles signals (e.g. triggering exit from the reader), and a part that
    always runs just before blocking in select(). This second part always
    reaps jobs and prints their status messages. This narrows the window for a
    job exit to be "missed" before fish blocks in select, and should make the
    job_summary.py test more reliable.

 src/input.cpp        | 13 +++++++++----
 src/input.h          |  3 +++
 src/input_common.cpp |  7 +++++++
 src/input_common.h   |  4 ++++
 4 files changed, 23 insertions(+), 4 deletions(-)
```

Tested on both Arch Linux and NixOS unstable.

Recording of observed behaviour in the linux tty on a clean nixos vm: https://asciinema.org/a/ODR7cnvio1vcaaZIdvFfe3oiJ

See https://github.com/fish-shell/fish-shell/issues/8628#issuecomment-1009617569 for steps to reproduce.

**Comment by faho** [comment]
The "garbage" you are seeing is the tmux focus sequences. Apparently your fish doesn't react to it.

See if `bind \e\[I` and `bind \e\[O` print the correct thing:

```fish
> bind \e\[I
bind --preset \e\[I 'emit fish_focus_in'
> bind \e\[O
bind --preset \e\[O false
```

Also please show the output of `bind --user`.

**Comment by gravndal** [comment]
Those both print the correct thing, and `bind --user` has no output as this is without any user level configuration.

**Comment by gravndal** [comment]
Tried it on a different (much slower) machine: it reproduces, though not on every split/close, it's quite rare actually.

Looking closer, it also doesn't happen on every split on the faster machine, but it's an almost every time thing.

**Comment by gravndal** [comment]
Also if you or anyone else are curious here's a reproducing `flake.{nix,lock}` that can be compiled/ran with:
```
$ rm nixos.qcow2; nixos-rebuild build-vm --flake path:(pwd)#repro && ./result/bin/run-nixos-vm
```

```nix
{
  inputs = {
    nixpkgs = { url = "github:nixos/nixpkgs/nixos-unstable-small"; };
  };

  outputs = { self, nixpkgs }:
  {
    nixosConfigurations = {
      repro = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = [ ({ pkgs, ... }: {
          console.keyMap = "colemak";
          users.users.a = {
            password = "a";
            isNormalUser = true;
          };
          nixpkgs.overlays = [
            (self: super: {
              fish = super.fish.overrideAttrs (oldAttrs: {
                src = self.fetchFromGitHub {
                  owner = "fish-shell";
                  repo = "fish-shell";
                  rev = "1eb58f905449fb3af9bf79bf2589df47f544c9cb";
                  sha256 = "ajoyk7t6tQjFWwqSbnFugeesYBB+QnSiTHC3njqaFNA=";
                };
                doCheck = false;
              });
            })
          ];
          environment.systemPackages = with pkgs; [
            fish
            tmux
            asciinema
          ];
        })];
      };
    };
  };
}
```

```json
{
  "nodes": {
    "nixpkgs": {
      "locked": {
        "lastModified": 1641789839,
        "narHash": "sha256-go3JSvI/h0IO7l7RO60WD+7KS8DmRWVrm2UQBzId8H4=",
        "owner": "nixos",
        "repo": "nixpkgs",
        "rev": "6efb39682f9c007608eb966681a11a91fcbf0c9c",
        "type": "github"
      },
      "original": {
        "owner": "nixos",
        "ref": "nixos-unstable-small",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
    "root": {
      "inputs": {
        "nixpkgs": "nixpkgs"
      }
    }
  },
  "root": "root",
  "version": 7
}
```

Though you might want to remove/change `console.keyMap = "colemak";`.

**Comment by faho** [comment]
What's the latest commit you tried? The one you bisected it to seems quite unlikely.

**Comment by gravndal** [comment]
1eb58f905449fb3af9bf79bf2589df47f544c9cb which is to say master as of an hour ago.

The bisect was with `good 3.2.2` and `bad 3.3.1`.

**Comment by faho** [comment]
I just tested on the second machine, all I can tell you is it works for me. You'll want to check all fish and tmux configuration, and this includes the system-wide configuration in /etc/fish, and the vendor configuration in (typically) /usr/share/fish/vendor_conf.d.

Typically what would cause something like this to show up, especially sometimes, is if your escape delay is set to a too small value. That would cause fish to read the escape as a separate keypress and then read the `[I` as ordinary presses of `[` and `I`. This would then be inserted into the commandline.

But the default escape delay is 30 milliseconds, which should be plenty. This is configurable via $fish_escape_delay_ms.

(unfortunately there is no better way to tell the difference in a terminal, other programs also have this notion, including things like emacs and vim)

You'll also want to check if your terminal matters. Try a different one, see if that messes it up. Some have shell integration that sometimes has bugs.

**Comment by gravndal** [comment]
Here's a fish profile for a run where it triggers a few times: https://gist.github.com/gravndal/992ce4c0c2eb733605f83b355ed20ef3

For configuration, when testing in the vm the home directory is empty on login, as for system-wide configuration unless I'm blind, there is none:
 - /etc/fish doesn't exist
 - all vendor_*.d directories are empty
 - same thing with tmux

Increasing $fish_escape_delay_ms to 4999 changes nothing.

Of the two terminals I've tried — the linux console/tty in a qemu vm, and alacritty — neither have shell integration. Also just tried XTerm(370), didn't make a difference.

Nix does some stuff to ensure that fish sources the correct runtime, however given that this reproduces fine on arch, that shouldn't matter.

The tmux version is 3.2a with the following patch backported https://github.com/tmux/tmux/pull/2755.

**Comment by faho** [comment]
What I can see from that profile is that

1. This is quite slow for you - 80ms for `emit fish_focus_in` (with no discernable handler) vs 0.03ms for me.
2. It appears to be running the signal handler for SIGWINCH right after, and I don't know why

I guess it might be possible that we read escape, then get a signal handler and only then get the `[I` part. If we misinterpreted that as no longer belonging together it might trigger this. It seems unlikely - why would you constantly get a WINCH right in the middle of the sequence that tmux presumably writes at once? @ridiculousfish might have an idea.

>Nix does some stuff to ensure that fish sources the correct runtime, however given that this reproduces fine on arch, that shouldn't matter.

Nix does some more stuff. Can you reproduce this with https://aur.archlinux.org/packages/fish-git/, or building fish yourself, manually?

**Comment by gravndal** [comment]
Profile for fish-git (3.3.1-838-g1eb58f905) on arch: https://gist.github.com/gravndal/590fb3fc0bee1c4cbe391d90182d9c31

Note that the first `Prefix-" + ^D` that causes fish to misbehave is right after the `echo $version`.

This was on a new user with an empty $HOME, and tmux was ran with `-f /dev/null` (and manually setting `focus-events on`).

**Comment by faho** [comment]
>Note that the first Prefix-" + ^D that causes fish to misbehave is right after the echo $version.

Hold on. Now you're saying `^D`, which is traditional notation for ctrl+d. Are you pressing something *else*? Is anything but `[I` or `[O` showing up?

Anyway, we again have:

```raw
23	23	> emit fish_focus_in
49	133	> __fish_winch_handler SIGWINCH
```

A focus event *immediately* followed by a winch signal.

**Comment by gravndal** [comment]
To trigger it I'm just repeatedly splitting with `Prefix-"` and immediately closing the split, as you saw in the asciinema rec in the op, by exiting the new shell with `ctrl-d`.

**Comment by gravndal** [comment]
You can also try automating this with something like this (assuming a nested tmux session):
```fish
for i in (seq 100)
    tmux send-keys -t :0.0 'C-b' \"; sleep 0.05; tmux send-keys -t :0.0 'C-d'
    sleep 0.5
end
```

Though it appears that only `[O` misbehaves when doing this:

![output](https://user-images.githubusercontent.com/4656860/148817983-5df70b91-a515-4f0f-a649-ecad455bfe13.gif)

**Comment by faho** [comment]
>You can also try automating with something like this (assuming a nested tmux session):

Sorry, I have no idea how to use any of that. I don't use tmux.

And it doesn't really matter, by now I've created and switched and quit panes enough that I'm confident it's not happening on my system.

*Something* on your system is different.

**Comment by gravndal** [comment]
I can also reproduce this in a fresh install of termux, on a phone, my three very different systems can't be simultaneously unique in the same exact way. Do note that it's very infrequent (30/1000~) on the phone:

![Screenshot_20220110-204135](https://user-images.githubusercontent.com/4656860/148828993-f56ef373-8efb-49be-9711-2fc62790f6b5.jpg)

**Comment by gravndal** [comment]
So, anyway, repro steps:

1. `$ tmux`
2. `$ env TMUX='' tmux`
3. `Prefix+Prefix+: set focus-events on<CR>`
4. `$ fish`
5. `$ echo $version`
4. `Prefix+"`
5. `$ fish`
5. The for loop.
6. (Hopefully) Observe fish misbehaving.

**Comment by faho** [comment]
>So, anyway, repro steps:

Nope, no errors in at least 1500 runs through the loop. Fish from 1eb58f905 on archlinux with tmux 3.2a from the repos, empty tmux.conf.

Running either in a temporary home with stock configuration with `sh -c 'env HOME=$(mktemp -d) fish'`, or with my normal config.

**Comment by gravndal** [comment]
Huh, well, that's unfortunate.

Well, here are two different attempts, first one that didn't reproduce:

1. Boot archiso from 20220101 (using the ipxe efi loader)
2. `mount -t tmpfs -o size=12G tmpfs /mnt`
3. `pacstrap -i /mnt base fish tmux`
4. `archchroot /mnt`
5. edit `/etc/locale.gen`
6. `locale-gen`
7. `tmux -f /dev/null`
8. etc.

And, here's what did reproduce, continuing on the same system:
1. `pacman -S weston noto-fonts`
1. edit `~/.config/weston.ini` and configure keyboard
2. `weston`
3. click the terminal icon in the top left corner
4. `tmux a`
5. exit every tmux session (you could also do kill-server and drop step 5, I didn't though)
6. back at bash in the weston terminal: `tmux -f /dev/null`
7. `env TMUX='' tmux -f /dev/null`
8. `Prefix+Prefix+:set focus-events on<CR>`
9. `fish`
10. `echo $version`
9. `Prefix+"`
10. This slightly refined for loop:
```fish
for i in (seq 100000)
    tmux send-keys -t :0.0 C-b \"
    sleep 0.05
    tmux send-keys -t :0.0 C-d
    sleep 0.05
end
```

I sadly didn't record every step in the first attempt, so I'm currently redoing this to see if I didn't just do something wrong. For loop was the same for both attempts.

This was done on a seven year old ThinkPad T550 with a slow intel dual core cpu.

**Comment by zanchey** [comment]
https://github.com/tmux-plugins/vim-tmux-focus-events/issues/2 might be related but it's not clear how it's solved

**Comment by gravndal** [comment]
I'm surprised that this is needed, but, here's a video showing the complete steps for reproducing on 3.3.1, master, 7c153a8307c662fa853280fd64657dff0cd9a625, and *not* 3684c91ad (parent of 7c153...) in a vm starting with showing checksums of the iso and moving from there: https://youtu.be/tMPjX0kOnsM

Apologies for the termux screenshot, that was pure passive aggression on my part.

Anyway, thanks for following this up!

**Comment by ridiculousfish** [comment]
I got it reproing in iTerm2 (no tmux needed) as so. Note I was ssh'd into a Linux box on both windows.

- Window 1:
  1.   Ensure Session->Terminal State -> Focus Reporting is on
  2.  Start fish and get its pid

- Window 2:
   - Run `while true ; kill -WINCH 12345 ; end` with 12345 replaced with the pid from window 1

Switch back and forth between these two windows a lot and occasionally input will get printed in window 1.

Presumably what's happening is that if SIGWINCH is delivered during `select()` in the middle of the escape sequence, fish doesn't properly recognize it as an escape sequence.

**Comment by ridiculousfish** [comment]
It's not that...the issue appears to be if we get SIGWINCH while in the middle of matching an escape sequence, we may run `__fish_winch_handler` which then enqueues a repaint readline command. This then breaks the escape sequence so we end up using other bindings, falling back to self-insert.

**Comment by ridiculousfish** [comment]
Pulling into 3.4.0 as this appears to be a regression and I think we have another report from the gitter chat.

**Comment by floam** [comment]
Is it possible to use `pthread_sigmask` to just have a dedicated thread for SIGWINCH, that we can never worry will goof up anything?

**Comment by floam** [comment]
this may be a naive question

**Comment by ridiculousfish** [comment]
Here's what's going on. Say the user has a multi-key binding:

     > bind abcd 'echo wacky'

now they type `ab`, but before finishing, fish gets a signal which runs an event handler, and that enqueues some other command, perhaps readline `yank`. Now our event queue looks like this:

    1. char a
    2. char b
    3. readline 'yank'

Today we say "Oh, this readline command doesn't match the `abcd` binding" so we fall back to the generic binding, which just prints a and b.

Now in practice the "multi-key binding" are focus-reporting escape sequences, and SIGWINCH is delivered partway through it, "tearing" the sequence. We fall back to the generic binding; that explains how random-looking stuff gets printed (it's part of the escape sequence).

This is a real UI problem - if we're halfway through an escape sequence and we get some other event, what do we do? We could try to defer the event until after the escape sequence, but in principle that could take arbitrarily long, and the event could be important. Better I think is to run the event first and then conceptually "restart" the sequence; that is rearrange the queue like:

    1. readline 'yank'
    2. char a
    3. char b

I believe this is closer to what fish 3.3.1 does (it was actually pretty sloppy about when it ran events triggered by signals). Anyways I think I'm close to a fix.

**Comment by ridiculousfish** [comment]
@gravndal are you able to test if #8692 fixes this for you?

**Comment by gravndal** [comment]
@ridiculousfish looks like that fixes it.
