### ISSUE TITLE
Multiple input redirections [enhancement]

### ISSUE THREAD

**Issue by nertpinx** [fish-shell/fish-shell#8629]
It would be really helpful to have the possibility of one command show up as a file for another one. You can do this with one command using `-` (or sometimes `/dev/stdin`), but not with two.  So unless I am missing something there is no way to redirect the output of multiple commands as input files for another command without polluting the filesystem. Of course one can use mktemp and write a whole script, but I am interested in useful one-liners that can be ran in a way more easier fashion.

I feel like there is no better way to show an example than illustrating with another shell that I know allows for this.

    comm <(command1) <(command2)

this way the comm command runs as `comm /dev/fd/3 /dev/fd/4` for example and the outputs of command1 and command2 are redirected to the file descriptiors 3 and 4 respectively (the numbers are, of course, arbitrary).

Of course the syntax would have to be different to keep backward compatibility (in order not to break existing scripts).

If there already is a way to do this (without temporary files), then I believe it is not documented.

**Comment by faho** [comment]
This is a process substitution, use `psub`:

```fish
comm (command1 | psub) (command2 | psub)
```

**Comment by nertpinx** [comment]
Oh, thanks, that's exactly it, no idea how I missed that, it clearly is in the docs too. Probably the fact that I did not know how to describe it properly. Now I know, thanks!
