### ISSUE TITLE
argparse does not ignore -s after --

### ISSUE THREAD

**Issue by prs513rosewood** [fish-shell/fish-shell#8631]
Hello,

- fish version: 3.3.1-838-g1eb58f905 (also tested 3.1.2 from Ubuntu repos)
- `Linux 5.13.0-23-generic #23-Ubuntu`

I'm using `argparse` with the `-i` flag to forward arguments, but `argparse` fails to correctly treat `$argv` if it contains an option starting with `-s` and collapses the remaining arguments into a single string. Here's a MWE

```fish
function ignorebug
    echo $argv
    argparse -i 'o/output=' -- $argv
    echo $argv
end
```

This works correctly:
```
> ignorebug -o outfile -t foo bar
-o outfile -t foo bar
-t foo bar
```
This fails:
```
> ignorebug -o outfile -s foo bar
-o outfile -s foo bar
foobar
```
This fails differently:
```
> ignorebug -o outfile -st foo bar
-o outfile -s foo bar
-stfoobar
```

**Comment by faho** [comment]
Your issue isn't with `argparse`. It's with `echo`.

`echo` takes two options: `-s` and `-n`. Use `echo --` to stop option interpretation.

```fish
function ignorebug
    echo $argv
    argparse -i 'o/output=' -- $argv
    echo -- $argv
end
```

**Comment by prs513rosewood** [comment]
Good catch, thanks, I always forget echo can take options!
