### ISSUE TITLE
Startup

### ISSUE THREAD

**Issue by MihaiStef69** [fish-shell/fish-shell#8642]
How can I make commands run at startup with fish. For example I like to add neofetch at startup how do I do that

**Comment by faho** [comment]
https://fishshell.com/docs/current/faq.html#how-do-i-run-a-command-every-login-what-s-fish-s-equivalent-to-bashrc-or-profile.

Add the commands to a file called ~/.config/fish/config.fish. Note that fish runs it on *every* startup. For things like `neofetch` that are part of the shell's greeting, you can add them to the `fish_greeting` function. Run `funced fish_greeting`, put whatever you want in there, then run `funcsave fish_greeting`.
