### ISSUE TITLE
How do you change the cursor colour?

### ISSUE THREAD

**Issue by tom-james-watson** [fish-shell/fish-shell#8649]
Fish version: 3.1.2
OS: Ubuntu 21.10

I'm trying to use a light theme with fish and my cursor is always white. My google-fu is failing me when searching for how you change this and I can't find any relevant settings with `set -n`.

Thanks!

**Comment by faho** [comment]
Fish has no control over the cursor color. Set it in your terminal.

(technically some terminals feature an escape sequence to set it, but last I looked it wasn't well-supported so we don't want to add support for the few terminals that do)

**Comment by zanchey** [comment]
Unfortunately some terminals don't expose this setting.

This has suggestions for Xterm/VTE and Linux VT:
https://stackoverflow.com/questions/11494029/how-do-i-change-the-color-of-current-cursor-position-indicator

**Comment by tom-james-watson** [comment]
Ah ok - I didn't realise that! It looks like if in Gnome Terminal you untick "Cursor color" it seems to default to your text colour, which at least follows your theme.

![image](https://user-images.githubusercontent.com/3852719/149756024-c70acb0e-3548-491f-a6a0-2eb4791b3b63.png)
