### ISSUE TITLE
Completions: `git add --chmod=(+/-)x`

### ISSUE THREAD

**Issue by spenserblack** [fish-shell/fish-shell#8652]
version: 3.3.1

Fish is missing a completion for `git add` for the `--chmod` flag. `--chmod=+x` makes the file *track* as executable, and `--chmod=-x` makes the file *track* as a non-executable file. An example usage is when using Windows, where the user knows that the file should be executable on Unix systems, but the `chmod` command is unavailable/insufficient on Windows.

Per the [docs](https://git-scm.com/docs/git-update-index#Documentation/git-update-index.txt---chmod-x), the only available options for `--chmod` appear to be `+x` and `-x`.

**Comment by faho** [comment]
To be honest, I would like to ask you not to open more issues about simple options missing in the git completions. There are literally hundreds of them, and it's known that a lot are missing. We've added the most common and useful ones, and if people are missing more we would like PRs instead.

**Comment by spenserblack** [comment]
Understood, I apologize for the clutter to the repo. I'll refrain from opening these small completion issues in the future. Are "small" *PRs* for completions OK, or should those also be larger and more substantial to reduce clutter?

Also, it might be helpful if this preference was listed in `CONTRIBUTING`, or if there was an issue template for completions that noted issues like this one aren't preferred.

**Comment by faho** [comment]
>Are "small" PRs for completions OK, or should those also be larger and more substantial to reduce clutter?

It's probably easiest if you group a few together - unless you really just have the one, in which case open the one.

E.g. a PR that's "Add five options to git completions" require us to look over once and click the big merge button once, five PRs that are "Add one option to git completions" each require us to look over each and click the big merge button five times. So if you are in a position to group them together, please do so!
