### ISSUE TITLE
Openwrt Cross Compile Support Broken for Musl Mips32 after 3.1.2

### ISSUE THREAD

**Issue by zloyle** [fish-shell/fish-shell#8653]
Has something major changed that prevents any version after 3.1.2 from working on a musl mipsel32 device?

Last working version I am able to successfully cross compile is 3.1.2. All versions afterword just hang and stop accepting input after the greeting forcing me to load another shell and kill the process to gain back control. Compiling latest master doesn't hang it just fails and thows this error.

Assertion failed: (status_.load() & STATUS_NEEDS_WAKEUP) == 0 && "No thread should be waiting" (/build/sources/fish/src/topic_monitor.cpp: try_update_gens_maybe_becoming_reader: 208)
Aborted

Is this to be expected? Thanks.

**Comment by zanchey** [comment]
No, it's not intended. Presumably there is something in the MIPS memory model we are butting against here? @ridiculousfish loves this stuff ;-)

**Comment by zloyle** [comment]
Cool. I'll keep checking the thread for an eventual fix down the line. Thank you.

**Comment by ridiculousfish** [comment]
test comment

**Comment by ridiculousfish** [comment]
I compiled both debug and release versions of fish in [this mipsel Debian image](https://blahcat.github.io/2017/06/25/qemu-images-to-play-with/) using qemu, and both ran fine. @zloyle can you please share your cross-compile setup? What compiler, etc?

**Comment by zloyle** [comment]
Its working now. Something must have got fixed on the master branch. I was able to compile latest master fish, version 3.3.1-1026-g065b769c1 without any issues and without any changes to my cross-compile setup which is just cross compiling ncurses, pcre2, and fish against the openwrt sdk which is musl based. Thank you for looking into this.

**Comment by hdhoang** [comment]
hi, it randomly happens on newly released openwrt 22.03, fish is 3.3.1: https://github.com/openwrt/packages/blob/openwrt-22.03/utils/fish/Makefile

my HW is gehua ramips, mediatek mipsel https://openwrt.org/toh/hwdata/gehua/gehua_ghl-r-001

istr this happening before, but not sure what the versions were at the time.

please consider, if you have time, thanks. i can use ash meanwhile.

**Comment by faho** [comment]
@hdhoang What "randomly happens"?

This is about *compiling* fish, and we haven't been able to reproduce the error.

>fish is 3.3.1

Our current release is 3.5.1. 3.3.1 is unsupported and is about 10% of commits behind. Please update.

**Comment by hdhoang** [comment]
running fish randomly aborts with the message in description

```
 -----------------------------------------------------
 OpenWrt 22.03.0, r19685-512e76967f
 -----------------------------------------------------
root@map:~# fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
Assertion failed: (status_.load() & STATUS_NEEDS_WAKEUP) == 0 && "No thread )
Aborted
root@map:~# fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
root@map ~# ls Assertion failed: (status_.load() & STATUS_NEEDS_WAKEUP) == 0)
Aborted
root@map:~# fish
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
root@map ~# w
fish: Unknown command: w
Assertion failed: (status_.load() & STATUS_NEEDS_WAKEUP) == 0 && "No thread should be waiting" (fish-3.3.1/src/topic_monitor.cpp: try_update_gens_ma)
Aborted
```

i will ping openwrt maintainers instead, thanks

**Comment by dainslef** [comment]
> @hdhoang What "randomly happens"?
> 
> > fish is 3.3.1
> 
> Our current release is 3.5.1. 3.3.1 is unsupported and is about 10% of commits behind. Please update.
I test `fish 3.5.0` and `fish 3.5.1` in OpenWRT 22.03.0 with `mipsel_24kc` architecture, same issue still exists. https://github.com/openwrt/packages/issues/19386

**Comment by neheb** [comment]
@ridiculousfish this is easily reproducible under QEMU. It seems this is an incompatibility with musl.
