### ISSUE TITLE
Installing Fish on MacBook Pro M1 Max

### ISSUE THREAD

**Issue by ranrinc** [fish-shell/fish-shell#8657]
Just got a new MBP M1 Max and trying to setup my terminal.
Usually I run this procedure to install fish

```
# Install Fish using brew
brew install fish

# Add shell attachement
cat /etc/shells|grep /usr/local/bin/fish ||sudo sh -c 'echo "/usr/local/bin/fish" >> /etc/shells'

# Make Fish Default
chsh -s /usr/local/bin/fish

# Get Oh My Fish
curl -L https://get.oh-my.fish | fish

# Install bobthefish theme
omf install bobthefish
```

However this time its stuck after Add shell attachement <- this is where it gets wrong where /usr/local/bin/fish is missing or not being created. Then `chsh -s /usr/local/bin/fish` creating not found error. 

I do able to run fish but dont know how to change my zsh into fish. Help

**Comment by floam** [comment]
No idea why that specifically would not work for you - I just removed fish from that file and used that line - if it matters on my brain new M1 Pro, and it worked. 

Anyhow, try this, from our instructions in the readme: `echo /usr/local/bin/fish | sudo tee -a /etc/shells`. Or just open it in a text editor and add it manually.

**Comment by ranrinc** [comment]
@floam I'm not sure on how to set it up manually. One thing for sure fish did get installed by brew. Furthermore on my intel mac I can see `/usr/local/bin` contain executable files. 

![Screen Shot 2022-01-20 at 2 50 44 PM](https://user-images.githubusercontent.com/15801696/150296463-f8e4fe2c-8fad-47f4-985c-99a64c6e1aab.png)

On my M1 Max Mac on other hand `/usr/local` dont have bin folder or any other content. Running `cat /etc/shells|grep /usr/local/bin/fish ||sudo sh -c 'echo "/usr/local/bin/fish" >> /etc/shells'` doesnt seem to matter at all. Try running `echo /usr/local/bin/fish | sudo tee -a /etc/shells` just show /usr/local/bin/fish

![Screen Shot 2022-01-20 at 2 54 48 PM](https://user-images.githubusercontent.com/15801696/150296489-28c88c43-f619-49d5-b6e9-dcb7f68dde67.png)

![Screen Shot 2022-01-20 at 2 55 54 PM](https://user-images.githubusercontent.com/15801696/150296571-fcc3ebfb-a447-4dee-898b-82412f0d890e.png)

**Comment by floam** [comment]
Oh. You are saying you also used homebrew to install on this new computer? A clean homebrew installation will be different from your previous computer. Homebrew has not defaults to /usr/local/ for years. Look at where it tells you it installed fish.

Check /opt/homebrew/bin. That’s what it is using right now. Add /opt/homebrew/bin/fish to /etc/shells. I would open it up in Text Edit and just remove the extra lines you added earlier. Then use chsh -s /opt/homebrew/bin/fish.

**Comment by ranrinc** [comment]
> /opt/homebrew/bin/fish

Got it working.. thank you so much.
