### ISSUE TITLE
How can i launch fish shell in chrome rootfs directly

### ISSUE THREAD

**Issue by happyeggchen** [fish-shell/fish-shell#8664]
I made a few fish shell scripts,but i want them to run in chromeOS(not it's vm or container),I tried to add gcc libs into it,but when i do this,and launch fishshell,it said core dump.

**Comment by faho** [comment]
You're probably better off asking people who know Chrome OS. I have absolutely no idea how this would work.

**Comment by happyeggchen** [comment]
Do you want to try it?
I have a chromeOS installed laptop

**Comment by faho** [comment]
Sorry, no. I have no interest in ChromeOS and don't want to be touching other people's machines.

**Comment by happyeggchen** [comment]
Okay

**Comment by gitdrug** [comment]
https://github.com/skycocker/chromebrew has a fish package if you want to install fish shell on chromeos
