### ISSUE TITLE
[Ask for help] Why argparse went error here

### ISSUE THREAD

**Issue by happyeggchen** [fish-shell/fish-shell#8669]
fish, version 3.1.2
Platform:chromeOS container + fedora arm
Argparse said that Invalid option spec 'ctroot=' at char 't'
But i didn't met this on 3.3.1

Btw here's the code blocks
```
argparse -i -n $prefix ctroot= ctshare= ctlog_level= ctauto_umount= ctsafety_level= ctbackend= -- $argv
```
Logs here
```
happyeggchen@penguin ~> ctcontainer init alpinelinux -f
Build_Time_UTC=2022-01-25_14:07:44
[ctcontainer] Detected First Launching,We need your password to create the config file
[ctcontainer] [Error] root.ctcontainer not found,try to create it under root
[ctcontainer]: Invalid option spec 'ctroot=' at char 't'
[ctcontainer] Deploying...
[ctcontainer] [Info] Using origin name mode,container might be killed(coverd)
######################################################################## 100.0%
[ctcontainer] [Succeeded] alpinelinux Package downloaded
[ctcontainer] [Succeeded] alpinelinux deployed in /opt/ctcontainer/alpinelinux
happyeggchen@penguin ~> ctcontainer run alpinelinux ash
Build_Time_UTC=2022-01-25_14:07:44
[ctcontainer]: Invalid option spec 'ctroot=' at char 't'
[ctcontainer] [Info] Launching alpinelinux from /opt/ctcontainer
/ $ exit
[ctcontainer] [Succeeded] Umountd
```

**Comment by krobelus** [comment]
On Fri, Jan 28, 2022 at 02:35:36AM -0800, tsingkwai wrote:
> fish, version 3.1.2
> Platform:chromeOS container + fedora arm
> Argparse said that Invalid option spec 'ctroot=' at char 't'
> But i didn't met this on 3.3.1
> 
> ```
> argparse ctroot= -- $argv
> ```

This is supported since 3.2.0, the changelog says:

-  `argparse` no longer requires a short flag letter for long-only options #7585

**Comment by happyeggchen** [comment]
So i have to add a short flag which is ignored to get this work on all version?
Btw thx ur answer
