### ISSUE TITLE
no --relative complement for ln

### ISSUE THREAD

**Issue by wuyudi** [fish-shell/fish-shell#8675]
**YOUR TEXT HERE**
fish, version 3.3.1
Linux archlinux 5.16.2-arch1-1 #1 SMP PREEMPT Thu, 20 Jan 2022 16:18:29 +0000 x86_64 GNU/Linux
alacritty
I have tried `sh -c 'env HOME=$(mktemp -d) fish'`

Problem:
the `ln` can't complete `-r`
![image](https://user-images.githubusercontent.com/30024051/151668678-5ceb20cf-b90a-43e2-9322-138d7b0f68ed.png)

but `man ln` has this

```shell
       -r, --relative
              with -s, create links relative to link location
```

I have done `fish_update_completions` before.

**Comment by krobelus** [comment]
Fixed via #8676
