### ISSUE TITLE
Characters such as ~ and variables are drawn in a bluish color

### ISSUE THREAD

**Issue by lominoss-git** [fish-shell/fish-shell#8688]
Version: 3.3.1

I'm running Arch Linux and I use the 5.16.4-zen1-1 kernel.

I tried this in a newly installed Fish instance and I still found the same issue.

**Comment by IlanCosman** [comment]
What color would you expect them to be drawn in? It's syntax highlighting, just like a programming language.

**Comment by lominoss-git** [comment]
First of all, thanks for responding. What I'm looking for is a way to change the color.

**Comment by IlanCosman** [comment]
https://fishshell.com/docs/current/interactive.html?highlight=color#syntax-highlighting-variables

**Comment by floam** [comment]
Type `fish_config` and hit enter.

**Comment by lominoss-git** [comment]
Thank you so much, for those who have the same problem, all I did is change the value of the ```fish_color_operator``` to white:
```fish
set fish_color_operator white
```
