### ISSUE TITLE
Weird error when auto-completing in brackets

### ISSUE THREAD

**Issue by ChrisJefferson** [fish-shell/fish-shell#869]
Tested on both 2.0 release and master. Type:

    for i in (cd x)

Then move cursor back to between the x and ) and press tab

The resulting output is the strange and confusing:

cd: The directory “x” does not exist
/usr/local/share/fish/functions/cd.fish (line 9): 		builtin cd $argv
                                                                  ^
in function “cd”,
	called on line 2 of file “/usr/local/share/fish/functions/__fish_complete_cd.fish”,
	with parameter list “x”

in command substitution
	called on line 2 of file “/usr/local/share/fish/functions/__fish_complete_cd.fish”,

in . (source) call of file “-”,
	called on line 22 of file “/usr/local/share/fish/functions/__fish_complete_cd.fish”,

in function “__fish_complete_cd”,
	called on standard input,

in command substitution
	called on standard input,

**Comment by faho** [comment]
Looks solved now.
