### ISSUE TITLE
Better error message for `set foo=bar`

### ISSUE THREAD

**Issue by andmis** [fish-shell/fish-shell#8694]
![image](https://user-images.githubusercontent.com/5308024/152563263-281871d3-925c-4a73-b335-1db996a5a26f.png)

People coming from Bash or whatever will be used to the `foo=bar` syntax. We could give a more-informative diagnostic here.

**Edit:** The formatting of this message could also be cleaned up IMO. There is a mix of backticks and single quotes wrapping `help` commands, the first line has punctuation and the parenthesized line does not, etc.

**Comment by krobelus** [comment]
Not sure if it's worth to make the error more verbose.
The user is meant to look up `help set` here, which is the canonical place to find the syntax. `help
set` is already mentioned.

> There is a mix of backticks and single quotes wrapping `help` commands,

Ugh yes.

> the first line has punctuation and the parenthesized line does not

IMO it's debatable whether the second needs punctuation

**Comment by andmis** [comment]
I don't think it should be more verbose, maybe just smarter. Something like "set does not support var=value syntax -- see `help set`". The current message refers the user to two different help pages, and the message itself is a little confusing.

**Comment by krobelus** [comment]
On Sat, Feb 05, 2022 at 05:56:01PM -0800, Andrey Mishchenko wrote:
> I don't think it should be more verbose, maybe just smarter. Something like "set does not support var=value syntax -- see `help set`". The current message refers the user to two different help pages, and the message itself is a little confusing.

OK
