### ISSUE TITLE
Fish 3.3.1: how do I negate the results of a string match?

### ISSUE THREAD

**Issue by mrjayviper** [fish-shell/fish-shell#8697]
as above.

basically I want to implement something like

```
    if not match then
      do these things
    else
      do these other things
    fi

```
Thanks

**Comment by zanchey** [comment]
From my answer to your SE question at https://unix.stackexchange.com/questions/689354/fish-3-3-1-shell-how-do-i-negate-the-results-of-a-string-match/689360

It depends on what you mean by match, but if you mean "exactly match", you can use the `string match` builtin with a plain argument.

```fish
if not string match --quiet "some_string" $some_argument
    echo no match
else
    echo match
end
```

To match within a string, you can use a glob in `some_string`, or a regular expression with `string match --regex`.
