### ISSUE TITLE
Aliases error, expected at most 2 args, got 3

### ISSUE THREAD

**Issue by TheAwesomeGuy47** [fish-shell/fish-shell#8701]
fish version: 3.3.1
os: arch linux
terminal: alacritty

I get a message when opening fish, to do with my aliases in fish.
Here is my config:

```bash
neofetch

if status is-interactive
    # Commands to run in interactive sessions can go here
end

# Aliases

# ls aliases (exa)
alias ls = "exa --icons"
alias la = "exa -a --icons"
alias ld = "exa -D --icons"
alias lt = "exa -a -T --icons"
alias lgi = "exa --git-ignore --icons"

fish_add_path ~/.local/bin

starship init fish | source
```

When I source or re-enter fish, I get the `neofetch` but I get 5 error messages saying `alias: Expected at most 2 args, got 3`. The aliases don't work.

Thanks!

**Comment by krobelus** [comment]
On Sun, Feb 06, 2022 at 09:17:38AM -0800, TheAwesomeGuy47 wrote:
> alias ls = "exa --icons"

lose the spaces around =.
See also `help alias` or `man alias`.

**Comment by TheAwesomeGuy47** [comment]
ah thanks it worked. used the same alias keyword and without the spaces in bash but didn't come to my stupid brain to do the same in fish
