### ISSUE TITLE
Error message when running `help`

### ISSUE THREAD

**Issue by 0x4398** [fish-shell/fish-shell#8702]
## Description

I just installed fish and ran `help` to open the documentation in my default browser (Chrome), which it did, but I also got the following error:

```
> help
Opening in existing browser session.
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[16036:16036:0100/000000.061086:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
```

I have the default settings with no 3rd party customization and I get this error every time I run `help`.

I followed the instructions and ran `sh -c 'env HOME=$(mktemp -d) fish'` and then `help`. This time the documentation was opened in Firefox, which is not my default browser, and **I didn't get any errors**.

Does anyone know what is going on? I couldn't find any information online.

## System info

```shell
> fish --version
fish, version 3.3.1
> echo $version
3.3.1
> echo $TERM
xterm-256color
> uname -a
Linux fedora 5.16.5-200.fc35.x86_64 #1 SMP PREEMPT Tue Feb 1 21:37:11 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by krobelus** [comment]
> Opening in existing browser session.
> libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
> [16036:16036:0100/000000.061086:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.

Same thing happens when running

    chromium https://example.com

so this is not a problem in fish but chromium or libva. As far as I can tell the error is benign.
I don't think we want to silence the browser command or do we?.

**Comment by zanchey** [comment]
> I don't think we want to silence the browser command or do we?.

No, I don't think so.
