### ISSUE TITLE
Fish `fish_user_paths` doesn't find nim

### ISSUE THREAD

**Issue by B4mbus** [fish-shell/fish-shell#8703]
The fish version is.. unknown? Both `$version` and `fish --version` return an empty string:
![image](https://user-images.githubusercontent.com/75364377/152763344-7198d1d1-7003-48a4-b6b7-dfdcd6c55c6f.png)

I'm on WSL2, kali linux

I install `nim` via the choosenim utility. It's being installed to `~/.nimble/`. I added the `/bin` subdirectory of that to path via `set -Ua fish_user_paths /home/b4mbus/.nimble/bin` and it doesn't find it.

Although it is present in path and the path is correct, I can't access any binaries inside the folder.
![image](https://user-images.githubusercontent.com/75364377/152763699-8ab0a161-b0aa-4bc1-bbec-347faa601ed4.png)

Doing `sh -c 'env HOME=$(mktemp -d) fish'`, then `set -Ua fish_user_paths /home/b4mbus/.nimble/bin` and invoking `nim` works for some reason (but it still doesn't display the correct version)

Yes. I did try reinstalling fish
Yes. I did restart my terminal
Yes. I did restart my computer
Yes. I did try to reinstall nim and choosenim several times
Yes. Going to `~/.nimble/bin` and invoking any binary through `./binary` works

**Comment by faho** [comment]
What does `set --show PATH` say?

**Comment by B4mbus** [comment]
@faho
```
$PATH: set in global scope, exported, a path variable with 7 elements
$PATH[1]: |/home/b4mbus/miniconda3/bin|
$PATH[2]: |/home/b4mbus/miniconda3/condabin|
$PATH[3]: |/usr/local/bin|
$PATH[4]: |/usr/bin|
$PATH[5]: |/bin|
$PATH[6]: |/usr/local/games|
$PATH[7]: |/usr/games|
```
^ this

**Comment by B4mbus** [comment]
And I just noticed it doesn't find any other binaries either? Except go, since it's in `/usr/bin/go`.

It also stopped supporting windows binaries some time ago (on WSL using windows binaries works), but I didn't really care about that. Now it seems realted.

**Comment by faho** [comment]
Okay, this is https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1001584. Debian's package resets the $PATH.

>It also stopped supporting windows binaries some time ago (on WSL using windows binaries works), but I didn't really care about that. Now it seems related.

Same issue, they remove the windows paths.

Also: 

>The fish version is.. unknown? Both $version and fish --version return an empty string:

This is https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1001583.

The Debian packagers built fish in a way that breaks version information.

What you want to do is remove the fish package, go to https://fishshell.com/ and install our package for Debian.

**Comment by faho** [comment]
From the first bug:

>As a workaround, it's possible to touch
$HOME/.config/fish/00debian-profile.fish

That won't solve the version issue tho, which would e.g. break installing oh-my-fish and everything else that checks the version.

**Comment by B4mbus** [comment]
@faho that solved it. Thanks a lot!
