### ISSUE TITLE
new error: fish_add_path -aP $snap_bin_path

### ISSUE THREAD

**Issue by agarzon-orangerine** [fish-shell/fish-shell#8713]
fish, version 3.1.0
Linux vault 5.4.0-99-generic #112-Ubuntu SMP Thu Feb 3 13:50:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
xterm

```
/usr/share/fish/vendor_conf.d/snapd.fish (line 3):
fish_add_path -aP $snap_bin_path
^
from sourcing file /usr/share/fish/vendor_conf.d/snapd.fish
        called on line 294 of file /usr/share/fish/config.fish
from sourcing file /usr/share/fish/config.fish
        called during startup
```

This is new, and never happened before. Now when I login I see that error.

The only I did was upgrade Ubutu,

Running fish_update_completions did not helped.

All the errors are coming from **/usr/share/fish/** not my personal settings.

**Comment by faho** [comment]
`fish_add_path` was added in fish 3.2.0, your fish is 3.1.0.

You have a partially upgraded system and so things break.

**Comment by faho** [comment]
Already reported upstream: https://bugs.launchpad.net/ubuntu/+source/snapd/+bug/1957948

**Comment by reitzig** [comment]
Seems to be fixed by https://github.com/snapcore/snapd/pull/11371; hope it'll hit the repos soon.
