### ISSUE TITLE
help opens wrong app

### ISSUE THREAD

**Issue by elchenberg** [fish-shell/fish-shell#8719]
```txt
> fish --version
fish, version 3.3.1

> echo $version
3.3.1

> uname -a
Linux xps13 5.13.0-28-generic #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

> echo $TERM
xterm-256color
```
`help` opens bitwarden app. I just installed fish and the first command I typed was `help`.

I found a very old issue ([Help is not shown in default browser](https://github.com/fish-shell/fish-shell/issues/293)) that mentioned `xdg-open`. My system is configured to use Firefox as the default browser and when I use xdg-open it opens URLs in Firefox.

**Comment by faho** [comment]
What does `xdg-open file:///usr/share/doc/fish/index.html` open?

Is $BROWSER set to anything? `set --show BROWSER`

**Comment by elchenberg** [comment]
`xdg-open file:///usr/share/doc/fish/index.html` opens Bitwarden. `set --show BROWSER` is empty. `xdg-mime query default text/html` prints `Bitwarden.desktop`, so not a fish problem. Thank you!

**Comment by qexat** [comment]
Hi, I face a similar issue, `help` opens Firefox instead of Google Chrome (unstable).
```
> fish --version
fish, version 3.3.1

> echo $version
3.3.1

> uname -a
Linux qexat 5.16.10-arch1-1 #1 SMP PREEMPT Wed, 16 Feb 2022 19:35:18 +0000 x86_64 GNU/Linux

> echo $TERM
xterm-256color
```
I am confused, because in my KDE settings, default browser is explicitly set to Google Chrome (unstable), and `xdg-mime query default text/html` prints `google-chrome-unstable.desktop`. Therefore, `xdg-open file:///usr/share/doc/fish/index.html` opens Google Chrome (unstable) ; but `BROWSER` is set to `firefox`.

**Comment by faho** [comment]
>but BROWSER is set to firefox

If $BROWSER is set, that takes precedence. Either unset it or set $fish_help_browser, which overrides even that.

**Comment by qexat** [comment]
Alright, thank you. Until now, I did unset `BROWSER` in my `config.fish`, but is there a way to make it not unsetting everytime fish launches?

**Comment by faho** [comment]
If fish inherits a variable, you'll have to unset it. There is no way around this.

**Comment by bytescaper** [comment]
I had the same problem and effectively, html files were set to be opened with other app different from Firefox. To solve the issue i used `xdg-mime default firefox.desktop text/html` to set it right. Thanks @faho for the clue ;)
