### ISSUE TITLE
wrong alias definition when command contains a metacharacter (like "+" or backslash)

### ISSUE THREAD

**Issue by Dieken** [fish-shell/fish-shell#8720]
fish 3.3.1, macOS Monterey, 12.0.1

```
$ alias g++ 'grc g++'

$ alias | fgrep g++
alias g++ 'g++ grc g++'

$ alias 'g\+\+' 'grc g++'

$ alias | fgrep g++
alias g++ g\\\\+\\\\+\\\ grc\\\ g++
```

**Comment by faho** [comment]
The only thing broken here is `alias` *display*.

The actual function definition is correct. See `type g++`.

**Comment by Dieken** [comment]
Thanks for your confirmation!

Another minor issue, in bash and zsh, I can use `alias xxx` to get alias definition, could fish support this too? Currently I have to use `alias | string match “alias xxx *”`.

**Comment by faho** [comment]
Fish does not, in a very real sense, *have* aliases. `alias` is a function that defines functions.

You can just use `functions xxx`.
