### ISSUE TITLE
Function If application installd do this else

### ISSUE THREAD

**Issue by Dan1jel** [fish-shell/fish-shell#8722]
I have looked everywhere for this answer vit either I'm to dumb or this haven't been a topic yet. 

I have my phone (termux) and my raspberry, if exa is not installed, to ls instead.

I want to have this so no errors would show instead (i could always install exa when I noticed it's not installed, but i want my fish settings to be  universal).

Is there a way or is this just not possible?

**Comment by IlanCosman** [comment]
`type --query`, or `command --query`. You can read about em on the docs :)

**Comment by Dan1jel** [comment]
> `type --query`, or `command --query`. You can read about em on the docs :)

I looked and looked and looked but never found -q answer. Thank you my good person. This was the answer and now everything works as intended after a "exec fish" thanks :)

This thread can now be closed.
