### ISSUE TITLE
Suppress Prompt Message

### ISSUE THREAD

**Issue by beatslikeahelix** [fish-shell/fish-shell#8725]
fish, version 3.3.1

Hello there, I'm getting extra output from fish on startup that I do not expect or want. As far as I can tell, it has nothing to do with `$fish_greeting`. The second part is the output of `uptime`, not sure about the first part. This behaviour does not occur with any other shell except fish. I installed with Homebrew.
Anyone got any idea how I can suppress this output? Cheers.

![Screenshot 2022-02-13 at 22 23 20](https://user-images.githubusercontent.com/47506872/153777934-44a48b81-09d5-4e7d-818c-2c2f11d7d309.png)

**Comment by krobelus** [comment]
does `fish_trace=1 fish` reveal anything calling `uname -a` or `uptime`?

**Comment by beatslikeahelix** [comment]
Uninstalling oh-my-fish got rid of it! 
I had a clean install, so not sure what caused it, unless there are some files hanging around on my system since the last time I had it installed.
