### ISSUE TITLE
`time` units

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#8727]
A recent commit may have worsened the output of `time ...`, and should have been first discussed and perhaps ought to be reverted. 

https://github.com/fish-shell/fish-shell/commit/2d9e51b43e8f0dd73a87e12f1abc74f99f8ff5f3

This issue is to gauge opinion. @mqudsi had some good feedback:

> I don't mean to bikeshed, but this is imho strictly worse because you alternate between using (strictly singular), long-form abbreviations for "minutes" and "seconds" then switch to two-letter abbreviations for milliseconds and microseconds. The actual results are always plural because they are floating point values and so are always as a part of a non-singular whole (1.000 would still use "seconds" and not "second"

**Comment by faho** [comment]
I would quite like to keep this ascii-only. The new style uses "μ", which isn't.

**Comment by krobelus** [comment]
I think for consistency we should either have

- mins
- secs
- millis
- micros

as before, or

- m
- s
- ms
- µs (or "us" for ascii-only)

I think the first is friendlier

**Comment by faho** [comment]
Okay, that looks fairly consensus-y that we want to revert 2d9e51b43e8f0dd73a87e12f1abc74f99f8ff5f3.

**Comment by faho** [comment]
Okay, I reverted this. Note that I ended up removing the box-drawing stuff as well because it was rather entangled and I would quite like to see it gated behind some sort of support check, if it's necessary at all. I wouldn't be surprised to see it have issues on a variety of terminals.
