### ISSUE TITLE
Wrong grammar in docs

### ISSUE THREAD

**Issue by Pound-Hash** [fish-shell/fish-shell#8728]
The [docs](https://fishshell.com/docs/current/interactive.html#vi-mode-commands) say,

> c **and** s remove the selection and switch to insert mode
> d **and** x remove the selection and switch to normal mode

But the **and** should be an **or**. It's not true that we press _c and s_, nor for _d and x_.

**Comment by faho** [comment]
Both do this. This is correct.

c does this, and s does this. c and s do this.

**Comment by floam** [comment]
I looked over the docs here and it looks right to me as well. What would have been wrong is if it had been phrased as:

> d and x remove**s** the selection ...

(emphasis on that s in removes).

In that case it could be more correct to say:

> d **or** x removes the selection and switches to normal mode.

But it was already correct: 

> c and s remove the selection and switch to insert mode

**Comment by floam** [comment]
I imagine the ambiguity that led to this issue is instead of imagining "Keys" or "Key" there, one imagined "Pressing" despite the mismatch encountered later in the plural list items.

**Comment by Pound-Hash** [comment]
The ambiguity is there, yes.

It's entirely natural to read the conjunctive _and_ as meaning both x & y _jointly_, as in "Please finish your dinner and wash the dishes." Here, the addressee is being told to do _two_ things, not _one **or** the other_. Again, this is a natural way of understanding the conjunctive _and_. Hence, such usage is prone to misunderstanding.

This is in contrast to the disjunctive _or_, which in this context is not in any way so prone. That is, no native speaker will ever misunderstand the use of a disjunctive here.

I'm happy to see further follow-up on this. Initially, I was discouraged to continue using Fish since it appeared that the developers are not so concerned with clear documentation. Thanks for the consideration.

@floam

**Comment by Pound-Hash** [comment]
Like I said originally, it's just not true that we _press c **and** s_.

And I really don't understand the intransigence in correcting this possible misconstrual.

Fish is supposed to be a friendly shell.

**Comment by floam** [comment]
I'm not being adversarial here, I think I understand where the confusion comes from and I agree either using `or` here or adding a verb could be better.

**Comment by Pound-Hash** [comment]
> I'm not trying to be adversarial here, I think I understand where the confusion came from and I agree either using `or` there or adding a verb could be better.

I know you're not. But my correction was originally refused. And that's just bizarre. The norms of language are objectively set. This is not merely my opinion. I presented a clear instance of ambiguity and the initial response was willful intransigence.

**Comment by floam** [comment]
I think it was not very clear initially. Please submit a PR that can clarify, I think that'd be fine.

**Comment by floam** [comment]
There is no standard parser for English, I personally use a brain made of meat and it was a very long time ago I took the SAT. Let's be nice.

**Comment by Pound-Hash** [comment]
That's two of us.
