### ISSUE TITLE
Support `gls` binary for the `ls` command

### ISSUE THREAD

**Issue by mfloryan** [fish-shell/fish-shell#8730]
```
fish, version 3.3.1
Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64
```

GNU `ls` (from `brew coreutils`) is installed as `gls` and much newer than the default `ls` command available on the MacOs (Monterey 12.1)

The fish `ls` function already support `gdircolor` it would be great if it also supported `gls` (when installed) automatically without having to change the path to use gnuutils.

**Comment by faho** [comment]
I don't think we want to be altering the *behavior* of commands like these unilaterally.

The dircolors thing is purely cosmetic and harmless, but this very much isn't.

So: Sorry, but no.

**Comment by mfloryan** [comment]
Understood, thanks for clarifying.
Maybe I was not very clear as I didn't suggest necessarily changing the default behaviour but perhaps providing an option (via configuration) to swap ls for gls.

**Comment by faho** [comment]
Just make your own function.

That's less restricted and simpler than any special option we could provide.
