### ISSUE TITLE
Glitch while typing (showing unwanted chars in random places)

### ISSUE THREAD

**Issue by thomiaditya** [fish-shell/fish-shell#8733]
Hello there,

I'm experiencing a glitch while typing in the prompt. It keeps showing me character like either 'l' or 'h' in random places.

![image](https://user-images.githubusercontent.com/18701474/154183964-36b1d29a-3757-40bb-a42d-6dd13e2b809e.png)
![image](https://user-images.githubusercontent.com/18701474/154184093-806625be-1a78-4fdd-beaf-0d8dd44478ed.png)
Is it a bug or just me?

Im using fish shell version 3.3.1.

Thanks.

**Comment by faho** [comment]
Duplicate of #8714

**Comment by thomiaditya** [comment]
Ok thanks.
