### ISSUE TITLE
Changing default shell to fish renders desktop with black screen & mouse cursor.

### ISSUE THREAD

**Issue by Rtizer-9** [fish-shell/fish-shell#8741]
fish --version : 3.3.1

Kubuntu 21.10
 
5.13.0-28-generic #31-Ubuntu SMP Thu Jan 13 17:41:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

The title pretty much describes the issue. The surprising thing is I was using fish as my default shell for a very long time and I never faced this issue but few days back when I rebooted the machine without any major changes in that session I was left with black screen and a mouse cursor.
I tried many solutions but none worked. I then tried to make a second user account, used it for a while and then started applying changes like apps and all....long story short I found out that changing default shell to fish was the culprit even after reinstalling the whole operating system.

I read about a user facing this same error and something about fish not posix compliant causing all these errors but that doesn't make sense since I was using it since long before as default shell.

I managed to install fish and even make it default only for kitty terminal, not changing anything in /etc/shells.

Any help is appreciated since it's hard to switch to another shell after getting used to fish.

**Comment by faho** [comment]
If you set fish as your default shell, that's the shell that will be run during login.

It will read its configuration - if that hangs or sets things weirdly (e.g. if you change $PATH or $XDG_DATA_DIRS, and the programs running during login inherit that), that may cause issues. So you want to check your configuration files. Move ~/.config/fish aside and log in again. Or create a new user with a fresh config and fish as the default shell and try that.

It also won't read things like /etc/profile, where some operating systems place their configuration. In case that's needed, that could also break things. You can check /etc/profile and /etc/profile.d for anything important, or you'll have to ask your OS vendor - in this case that's Ubuntu. Check Ubuntu forums.

**Comment by Rtizer-9** [comment]
I've now reinstalled the whole os so everything is fine now and no major changes have been made to environment variables.

Earlier according to one solution I tried renaming .config, .kde, .local too but it still didn't work.

Thanks for telling that setting $PATH can also cause these errors cause I was trying to set path for adb platform tools and frida reverse engineering tool but now I haven't set any of them and it still causes problem.

I guess maybe somebody will be able to help from kubuntu forums.

What's the solution according to you if I want to set fish as default shell and also set paths according to these tools?

I'm not really in a major problem since I can make fish default for kitty as well as konsole without changing anything in /etc/shells. I was just curious why I never faced such error before.

**Comment by faho** [comment]
>What's the solution according to you if I want to set fish as default shell and also set paths according to these tools?

Set it as default for your terminal.

>I was just curious why I never faced such error before.

Well, rule 0 of debugging: Something is wrong. Corollary to that: Something is wrong *now* - if it worked before, something changed.

So something about your system changed. You changed configuration, you did an update, ...

You need to figure out what that something was, I can't really help you with that.

**Comment by andygoossens** [comment]
I have the same issue. I have written about it here: https://bugs.launchpad.net/snapd/+bug/1957155/comments/5

A recent update of the snapd package seems the culprit. Removing the package fixes the desktop session.

**Comment by andygoossens** [comment]
I have created a separate bug in Launchpad: https://bugs.launchpad.net/snapd/+bug/1961791

**Comment by Rtizer-9** [comment]
@andygoossens thanks for the heads up. I guess making fish default for terminal emulator is best solution for now as many apps depend on snap.

PS: Please keep us posted in this thread if you find any new workaround. Thanks.

**Comment by faho** [comment]
Just to be clear: Just having snap *installed* breaks $XDG_DATA_DIRS and therefore every app that depends on that variable. You don't actually need to *use* snap for anything.

A simple workaround:

```fish
set -l dirs
for dir in /usr/share /usr/local/share
    contains -- $dir (string split : -- $XDG_DATA_DIRS)
    or set -p dirs $dir
end
set -q dirs[1]
and set -gx XDG_DATA_DIRS (string join : -- $dirs $XDG_DATA_DIRS)
```

in config.fish.

This should add the paths they forgot. It should be safe for essentially everyone to use, regardless if snap is installed or not.

**Comment by Rtizer-9** [comment]
I see. What I simply meant is that I'm using some snap apps so I thought removing snapd would be a problem.

I'll apply that config and see if it works.

**Comment by faho** [comment]
> TBH the whole Linux desktop setup is borderline annoying, and environment variables at inject through at least 3 different mechanisms, which break in very weird ways across a bunch of distros, their releases or particular shells picked by users.

From our perspective, it would be fantastic if there was a mechanism here that was either shell-agnostic (e.g. didn't use a shell at all) or explicitly picked a shell. Starting the desktop environment via $SHELL is bound to ask for problems except in very limited (but rather common) cases - just like programs like vim running their plugins in it.

Something like pam_env is *almost* there but afaik doesn't have a way to add missing path components (e.g. "append /usr/bin to $PATH if it's not already there").

**Comment by bboozzoo** [comment]
> From our perspective, it would be fantastic if there was a mechanism here that was either shell-agnostic (e.g. didn't use a shell at all) or explicitly picked a shell.

For systemd there's systemd-environment-d-generator which takes *.conf files from /usr/lib/environment.d and stuffs them into the session. Snapd also provides a conf file, but AFAIU it only works for some subset of users, basically ones who use recent GNOME on a modern distro. Systemd also supports user env generators are simple programs, but there's nothing to stop such helper from overwriting the current value of PATH/XDG_DATA_DIRS. For others, it's either /etc/environment, or /etc/profile.d (but this fails for users of zsh on Debian and Ubuntu). Then there's KDE which apparently does something else entirely. Last but not least, users also have their own buggy scripts which just override PATH/XDG_DATA_DIRS so there's always some random exotic combination that fails for some folks.

**Comment by andygoossens** [comment]
According to a post on [AskUbuntu](https://askubuntu.com/q/1394269/1573362), there is an other workaround: use LightDM instead of SDDM.
`sudo dpkg-reconfigure sddm`
