### ISSUE TITLE
Functions saved via `alias -s` are not saved with case-sensitive filenames

### ISSUE THREAD

**Issue by sgtsquiggs** [fish-shell/fish-shell#8744]
System info:
```
❯ fish --version
    echo $version
fish, version 3.3.1
3.3.1

❯ uname -a
Darwin ip-192-168-1-140.ec2.internal 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64

❯ echo $TERM
xterm-kitty
```

Given that you execute the following:
```
❯ alias -s gws='git status --short'
❯ alias -s gwS='git status'
```

Only `.config/fish/functions/gws.fish` is created - seemingly functions saved via alias are always lowercased, preventing the two aliases above from being saved properly.

The resulting file after the above commands:
```fish
function gwS --wraps='git status' --description 'alias gwS=git status'
  git status $argv; 
end
```

**Comment by sgtsquiggs** [comment]
I use a LOT of three/four letter git aliases with varying cases. As abbreviations they work as expected, but I prefer to have an alias/function so that my command history matches the alias I have memorized.

**Comment by faho** [comment]
Fish doesn't do anything special here. We simply take the function name and write to a file of that name.

If that clashes, that's because your filesystem is case-insensitive.

**Comment by faho** [comment]
Also look at using [abbreviations](https://fishshell.com/docs/current/interactive.html#abbreviations) instead, which remove much of the guess-work from short aliases, and aren't stored in separate files.

**Comment by sgtsquiggs** [comment]
I mentioned abbreviations in my comment - not ideal because I want to preserve the alias in my history not the full command. Any workarounds for this on macos? Should I just write my own `alias`?

**Comment by faho** [comment]
> Should I just write my own alias?

The issue isn't in alias! It is that you *cannot* create a file "gws.fish" and a separate file "gwS.fish" on your filesystem, because you have configured it as case-insensitive. Alias doesn't do anything that alters the case, the *filesystem* takes the second name and finds the file with the first name instead.

So you simply cannot save these two functions, with those names, in two separate files.

You can:

1. Define them eagerly, e.g. in config.fish
2. Give them names that don't just differ by case
3. Configure your filename as case-sensitive (this would be a larger change that impacts other software)

**Comment by sgtsquiggs** [comment]
Didn't know that the filenames in ~/.config/fish/functions need to match the function name. Unfortunate for me!

**Comment by faho** [comment]
This is [autoloading](https://fishshell.com/docs/current/language.html#autoloading-functions). The trick is, for function files, the function isn't loaded *at all* until it's executed for the first time, and then fish goes and finds it by its function name.

Which is also why eagerly defining the function in e.g. config.fish works.

**Comment by sgtsquiggs** [comment]
I'm using a .dotfiles setup w/ a bootstrapper - i wrote a little routine to convert a ton of aliases into a file w/ functions:

```fish
set known_funcs (functions | string split ',')

alias -s gws='git status --short'
alias -s gwS='git status'
(tons more aliases)

echo "#!/usr/bin/env fish" > git.fish

for func in (functions | string split ',')
	if not contains $func $known_funcs
		functions $func >> gitaliases.fish
	end
end

set -e known_funcs
```

I then symlink gitaliases.fish to `~/.config/fish/conf.d/gitaliases.fish`

**Comment by sgtsquiggs** [comment]
closing as this is a filesystem issue
