### ISSUE TITLE
readelf has no completion

### ISSUE THREAD

**Issue by wuyudi** [fish-shell/fish-shell#8746]
fish, version 3.3.1
3.3.1

Linux archlinux 5.16.11-arch1-1 #1 SMP PREEMPT Thu, 24 Feb 2022 02:18:20 +0000 x86_64 GNU/Linux

xterm-256color

`readelf` has no tab completion.

I have run `fish_update_completions` before.

**Comment by faho** [comment]
readelf's man page is awkwardly formatted, which makes it not usable for completion generation.

Someone will have to write a completion script by hand.

**Comment by amordo** [comment]
Hi there! I could give a basic set, relying on `tldr` output (`all, headers, symbols, file-header` options).
Does it make sense?

**Comment by ridiculousfish** [comment]
Sure, go for it.
