### ISSUE TITLE
RFE: xd … jump to the directory the file is

### ISSUE THREAD

**Issue by mcepl** [fish-shell/fish-shell#8747]
fish 3.3.1 on openSUSE/Tumbleweed (rolling distro)

This is not a bug report as more enhancement request. openSUSE has for other shells (bash, tcsh, zsh) alias `xd`, which can be translated to the fish function:
```fish
function xd --description='jump to the directory where the file is'
  cd (dirname (readlink -f $argv[1]))
end
```
I would love this alias be introduced to the standard fish function set.

**Comment by faho** [comment]
This is short and simple enough that you can just store it yourself, I don't see a need to introduce it for fish proper.

**Comment by mcepl** [comment]
Of course, I have installed for myself in my `~/.config/fish/functions`, but I thought it could be useful for others so I am sharing it. openSUSE users seem to be happy with having it in bash etc.
