### ISSUE TITLE
fish_variables eventually crashing the shell.

### ISSUE THREAD

**Issue by pnunn** [fish-shell/fish-shell#8754]
Since applying the ppa and updating to 3.3.1 I have been getting errors (on many systems) that eventually show the command line as being too long.

I have discovered that every time I start fish, it is adding to .config/fish/fish_variables as follows

SETUVAR --export XDG_DATA_DIRS:/home/pnunn/\x2elocal/share/flatpak/exports/share\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/\x3a/var/lib/snapd/desktop/

and this continues until I have to crash fish, log in as another user and remove this line from the config.

Why is this happening?  It is happening on all of my systems that I've upgraded (all the others are ubuntu 20.04 server).

**Comment by faho** [comment]
Okay, the question was answered - something in your config (or inside the snap vendor stuff) is appending to $XDG_DATA_DIRS.

Most likely this will be solved by an upgrade to snap. Closing!
