### ISSUE TITLE
fish_commandline_prepend: doesn't work as a toggle if any meta character is present

### ISSUE THREAD

**Issue by Animeshz** [fish-shell/fish-shell#8763]
Please tell us which fish version you are using: `fish 3.3.1`.
Please tell us which operating system and terminal you are using: `void x86_64 & kitty`.
The output of `uname -a`: `Linux framework 5.16.11_1 #1 SMP PREEMPT Thu Feb 24 03:39:56 UTC 2022 x86_64 GNU/Linux`

### Reproducing steps:

1. Add this to your `~/.config/fish/config.fish`
```fish
function fish_user_key_bindings
    bind \cV "fish_commandline_prepend 'xclip -sel clip -o |"
end
```

2. Now send `Ctrl+V` on terminal, twice or more, it'll put this thing again and again, along with a more space before the main command each time.

e.g.
![a06-03-22-19h21m55s](https://user-images.githubusercontent.com/26714676/156926245-0b5cc179-c809-4524-b10b-c7d05e4f0bf0.jpg)

`fish_commandline_append` works everytime regardless the position of `|`. The wrong behavior is only in `fish_commandline_prepend`.

**Comment by faho** [comment]
Ah, okay. `fish_commandline_prepend` is supposed to act on the current *process* - i.e. if you have a pipeline, it'll only act on the part of the pipeline where the cursor is, so you can e.g. toggle `sudo` in

```fish
echo foo\nbar | sudo pacman -S -
```

This will, of course, not work if the thing you're toggling adds a new part to the pipeline.

I don't believe there is a good way to make both work, so you can keep a local copy of `fish_commandline_prepend` that operates on the entire commandline.

Do `funced fish_commandline_prepend` and remove all the `-p` from `commandline` calls

**Comment by Animeshz** [comment]
> Do funced fish_commandline_prepend and remove all the -p from commandline calls

I didn't understood this part, can you please explain with an example?

**Comment by faho** [comment]
>I didn't understood this part, can you please explain with an example?

When you run `funced fish_commandline_prepend`, it will open up the source of the fish_commandline_prepend function in an editor.

Wherever that calls `commandline`, it uses the `-p` option. This causes it to refer to only the current "process", i.e. the part of the pipeline where the cursor is.

Remove it.

So https://github.com/fish-shell/fish-shell/blob/959e17faced671344f4d6879039d055439ffa687/share/functions/fish_commandline_prepend.fish#L7

turns into

```fish
set -l process (commandline | string collect)
```

and https://github.com/fish-shell/fish-shell/blob/959e17faced671344f4d6879039d055439ffa687/share/functions/fish_commandline_prepend.fish#L9

turns into

```fish
commandline --replace -- $process
```

and https://github.com/fish-shell/fish-shell/blob/959e17faced671344f4d6879039d055439ffa687/share/functions/fish_commandline_prepend.fish#L12

turns into

```fish
commandline -C 0
```

**Comment by Animeshz** [comment]
Thank you it works, I've made a separate function re-using the original source!
