### ISSUE TITLE
macos: background jobs aren't being terminated on shell exit, unlike on Linux

### ISSUE THREAD

**Issue by printfn** [fish-shell/fish-shell#8764]
I have the following fish script:

```fish
#!/usr/bin/env fish
sleep 100000 &
wait
```

If I run the script on macOS and press Ctrl+C to terminate it, the `sleep` job continues running in the background:

```
$ ./bug.fish
^C
$ ps -a
  PID TTY           TIME CMD
33774 ttys001    0:00.02 login -pf printfn /bin/zsh
33775 ttys001    0:00.19 -zsh
33856 ttys001    0:00.00 sleep 100000
33857 ttys001    0:00.00 ps -a
```

While my login shell is `zsh`, the same bug also occurs if I run the commands from `fish`. On Linux, the background job is correctly killed when the shell terminates with Ctrl+C, with `sleep` no longer showing up in `ps -a`.

Versions:
```
fish --version: fish, version 3.3.1
uname -a:       Darwin MacBook-Pro 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_X86_64 x86_64
echo $TERM:     xterm-256color
```

**Comment by zanchey** [comment]
I see this behaviour on macOS 12.2 (Manta Ray), but also on Linux, and also with bash on both platforms - so I think this is working as designed?

**Comment by ridiculousfish** [comment]
This is indeed working as designed. Background jobs spawned by shells without job control (which includes scripts) ignore SIGINT and SIGQUIT, per POSIX. See #6828 and [this SO answer](https://stackoverflow.com/questions/60626955/why-bash-background-task-ignores-sigint). Closing, thanks for filing.
