### ISSUE TITLE
I tried updating omf, and got this error... 

### ISSUE THREAD

**Issue by jdsjdk** [fish-shell/fish-shell#8765]
fish, version 3.0.2

uname -a :
16.7.0 Darwin Kernel Version 16.7.0 , xnu-3789.73.50~1/RELEASE_X86_64 x86_64

echo $TERM: 
xterm-256color

anyway, I ran this command:
`omf update`

and now I'm getting this every terminal session:

```fish: Unknown command md5sum
~/.local/share/omf/themes/lambda/functions/fish_prompt.fish (line 1):
hostname | md5sum | cut -f1 -d' ' | tr -d '\n' | tail -c6
           ^
in command substitution
	called on line 2 of file ~/.local/share/omf/themes/lambda/functions/fish_prompt.fish

in command substitution
	called on line 20 of file ~/.local/share/omf/themes/lambda/functions/fish_prompt.fish

in function 'fish_prompt'
	called on standard input

in command substitution
	called on standard input 
```

This is really frustrating because I cannot really have a normal shell now.  Can you please fix?  Thanks.

**Comment by jdsjdk** [comment]
Ummm it doesn't seem to have typed anything.... Wierd.  I can easily retype everything if I need to.

**Comment by faho** [comment]
Oh-my-fish is a third-party project we have nothing to do with.

In your case, your issue is with the "lambda" theme. Please report your issue at https://github.com/hasanozgan/theme-lambda/issues.

**Comment by faho** [comment]
Also:

> fish, version 3.0.2

You want to update your fish, the latest release is 3.3.1.
