### ISSUE TITLE
"in function 'fish_prompt' in command substitution disown: THERE ARE NO SUITABLE JOBS" Idk what that means! help!

### ISSUE THREAD

**Issue by mark-escosura** [fish-shell/fish-shell#8770]
version: `3.3.1`
uname -a: `Darwin MacBook-Pro.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T6000 arm64`
$TERM: `xterm-256color`

Issue: I changed the path from `/usr/local/bin/fish` to `/opt/homebrew/bin/fish` after doing the  `which fish` command and getting this error. Please help!

![Screen Shot 2022-03-08 at 9 16 28 PM](https://user-images.githubusercontent.com/88951042/157377657-41f5baef-6146-47e8-9e56-9e535f3632c5.png)

**Comment by IlanCosman** [comment]
This is related to Tide. Could you close this and [open an issue over in the Tide repository?](https://github.com/IlanCosman/tide/issues/new/choose)
That will allow me to get all the info I need to debug 😃

**Comment by faho** [comment]
What is happening here is that you no longer have fish in your $PATH, but Tide tries to run `fish`.

The simplest way to add it is probably to run `fish_add_path /opt/homebrew/bin/`.

**Comment by IlanCosman** [comment]
Maybe I should run fish from `status fish-path`? I don't think there's any reason I'd want the main and sub shells to differ...

**Comment by faho** [comment]
>Maybe I should run fish from status fish-path?

That is a possibility. Note that `status fish-path` on OpenBSD will pretty much just be "fish" (because it doesn't give us any API to get the path to the current executable), but that'll just leave you where you are now.
