### ISSUE TITLE
Docs: What's the rule for ">_" vs ">" vs nothing?

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#8777]
In the current docs from `fish, version 3.3.1-1098-g3a23fdf35`, some command pages prefix their examples with `>_`, others with `>`, and most seem to have nothing at all. Is there any logic behind this or should we just choose one style?

**Comment by faho** [comment]
Honestly... just use whichever you want, I do not believe this is worth arguing about.

**Comment by IlanCosman** [comment]
Fair enough. Maybe I'll make a PR at some point standardizing it, and we can just accept it (since I doubt there's any strong feeling on any side). All the benefits of consistency without the drawbacks of bikeshedding 😄
