### ISSUE TITLE
Errant bash-ism in fish_title.fish?

### ISSUE THREAD

**Issue by anoldguy** [fish-shell/fish-shell#8778]
OS:  Pop OS 21.10
Fish: 3.4.0 installed via ubuntu ppa: `deb http://ppa.launchpad.net/fish-shell/release-3/ubuntu/ impish main`

Here are the basics:
```fish
» fish --version
fish, version 3.4.0
~ 
» uname -a
Linux talon 5.16.11-76051611-generic #202202230823~1646248261~21.10~2b22243 SMP PREEMPT 
    Wed Mar 2 20: x86_64 x86_64 x86_64 GNU/Linux
~ 
» echo $TERM
xterm-256color
```
Upon upgrading via 'apt dist-upgrade -y', I got the following error:

```
...<snip>
Setting up fish (3.4.0-1~impish) ...
Processing triggers for desktop-file-utils (0.26-1ubuntu2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for libglib2.0-0:amd64 (2.68.4-1ubuntu1) ...
Processing triggers for libc-bin (2.34-0ubuntu3.2) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for dbus (1.12.20-2ubuntu2) ...
Processing triggers for mailcap (3.69ubuntu1) ...
/usr/share/fish/functions/fish_title.fish (line 7): $(...) is not supported. In fish, please use '(prompt_hostname)'.
        and set ssh "[$(prompt_hostname | string sub -l 10)]"
                      ^
from sourcing file /usr/share/fish/functions/fish_title.fish
in command substitution
source: Error while reading file “/usr/share/fish/functions/fish_title.fish”
» 
```

Is this a bash-ism that leaked thru? [Link to code](https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_title.fish#L7)

**Comment by magneticflux-** [comment]
It's because the existing `fish` instance from before the update doesn't include https://github.com/fish-shell/fish-shell/pull/8059. Since you're starting a new version when you use `fish --version`, you don't see the older, current version. Restarting the shell fixes the issue.

**Comment by faho** [comment]
Fish 3.4.0 gained support for the `$(command)` syntax, so if an older fish tries to read a file meant for that it'll break.

We recommend restarting fish on upgrade for this reason.

**Comment by anoldguy** [comment]
O

> Fish 3.4.0 gained support for the `$(command)` syntax, so if an older fish tries to read a file meant for that it'll break.
> 
> We recommend restarting fish on upgrade for this reason.

Oh wow. Really? That's awesome! (I haven't read the release notes yet, and was caught off guard by the `$(..)` syntax. :+1:
