### ISSUE TITLE
Documented fallback behavior for `fish_pager_color_selected_background` is now misleading

### ISSUE THREAD

**Issue by jaminthorns** [fish-shell/fish-shell#8787]
# Issue

With the recent release of `fish` version `3.4`, the `fish_pager_color_selected_background` variable is now set as a universal variable along with the other pager colors upon interactive initialization:

https://github.com/fish-shell/fish-shell/blob/cd62771d1245b5a49d02bf51ce193c3e96f898d3/share/functions/__fish_config_interactive.fish#L62-L67

It think this is a perfectly reasonable default, but in the [documentation for interactive use](https://fishshell.com/docs/current/interactive.html#pager-color-variables), this is stated:

> When the secondary or selected variables aren’t set, the normal variables are used, except for `$fish_pager_color_selected_background`, where the background of `$fish_color_search_match` is tried first.

This is still technically true, but because of the new initialization behavior for `fish_pager_color_selected_background`, this doesn't happen in practice, so the documentation is now misleading. To get the documented behavior, I can of course just run:

```fish
set -e fish_pager_color_selected_background
```

But the default behavior is still confusing.

# Context

I'm a maintainer of the [Dracula theme for `fish`](https://github.com/dracula/fish), and in this theme, we rely on the documented behavior for `fish_pager_color_selected_background` (falling back to the background color of `fish_color_search_match`). Upon upgrading to `fish` version `3.4`, I was confused as to why the background color of selected autocompletions had changed. Users of this theme are probably having a similar experience.

# Suggested Solutions

- Change the initialized value of `fish_color_search_match` to `-r` and remove the initialization of `fish_pager_color_selected_background`.

  This would change the background color of search matches to be the same as selected autocompletions and rely on the documented fallback behavior for `fish_pager_color_selected_background`.

- Add a note to the documentation that `fish_pager_color_selected_background` is set as a universal variable by default and needs to be unset in order to have the documented fallback behavior.

  This seems like it might be exposing the "guts" of `fish`'s initialization process too much for what is supposed to be user-friendly documentation.

- Don't change initialization code or documentation at all, but instead inform 3rd-party theme maintainers (like myself) that `fish_pager_color_selected_background` now needs to be explicitly set instead of relying on the fallback behavior.

  This issue might suffice, but a page/blurb on this repository's wiki would probably be better.

**Comment by faho** [comment]
>This is still technically true, but because of the new initialization behavior for fish_pager_color_selected_background, this doesn't happen in practice, so the documentation is now misleading. 

This isn't just technically true. It's quite directly, simply, *true* true.

It says "if the variable isn't set, it'll use the other variable instead". Well, the variable is set now.

I fail to see what's misleading here?

>Don't change initialization code or documentation at all, but instead inform 3rd-party theme maintainers (like myself) that fish_pager_color_selected_background now needs to be explicitly set instead of relying on the fallback behavior.

I believe that's the only tenable solution. If you want to have a certain color option resolve to a certain color value, you're going to *have to* set it.

Not in the least because people don't just switch from the default fish theme, they could also have had a different theme before. That's always going to be an issue if you rely on any option not being set.

Given my theme work for fish 3.4.0 - #8132 and #8127 - you'll see color variables being defined typically - because otherwise switching from one theme to another could keep coloring.

Now, there are things that might make this nicer, including e.g. falling through if a variable is empty (e.g. if you did `set -g fish_pager_color_selected_background` without a value). But nothing's set in stone.

**Comment by jaminthorns** [comment]
As a user, I just found it jarring when a variable I had previously been relying on being unset (to take advantage of the fallback behavior) became set universally with a new `fish` release.

It makes sense that as a theme developer, I should be setting everything explicitly instead of relying on the fallback behavior, though. This probably should have been my initial assumption due to how themes are set via `fish_config` (by setting universal variables), since any theme could set `fish_pager_color_selected_background` and have that value left behind as a user switches through themes. I'll be updating the Dracula theme to set that variable explicitly.

I appreciate the thorough response, thanks @faho!
