### ISSUE TITLE
fish_right_prompt not working after call status

### ISSUE THREAD

**Issue by kemko** [fish-shell/fish-shell#8791]
```
~> fish --version
fish, version 3.4.0

~> echo $version
3.4.0
```

All works if I use config like
```
function fish_right_prompt
end

if not status --is-interactive
  exit
end
```

But I've got error `fish: Unknown command: fish_right_prompt` with config like
```
if not status --is-interactive
  exit
end

function fish_right_prompt
end
```

**Comment by faho** [comment]
It appears you are calling `fish_right_prompt` in a non-interactive shell.

That won't work if you don't have `fish_right_prompt` defined if the shell isn't interactive.

**Comment by kemko** [comment]
No, I get this error when just open new iTerm 2 tab so I think it is interactive session.

Actually, I was trying to provide a simplified way to reproduce the issue. In fact I get this error when starting interactive session with starship:
```
[...]
if status --is-interactive
  starship init fish | source
  [...]
end
```

**Comment by faho** [comment]
You appear to have over-reduced the issue.

I am confident that `status --is-interactive` does the right thing, so the problem very very likely lies somewhere else.

You should look at your configuration and your terminal's integration (i.e. try other terminals). Chances are something is starting a non-interactive fish somewhere and telling it to print the right prompt, without checking if it is defined *inside the non-interactive fish*.

I.e. it does the equivalent of:

```fish
if functions -q fish_right_prompt
    fish -c fish_right_prompt
end
```

which starts *a new fish process*, which loads its configuration, which doesn't define the right prompt, and then tries to print the right prompt.

As a workaround either hard-code what `starship init fish` prints (these things don't typically change much, and calling `starship init` probably has some overhead that you want to avoid), or define a right prompt even if fish isn't interactive, e.g.

```fish
if status is-interactive
    starship init fish | source
else
    function fish_right_prompt; end
end
```

**Comment by faho** [comment]
Okay, I've given you some explanation for what seems to be happening. Other than that, we can't really do anything from our end. Closing!

**Comment by ben2talk** [comment]
I saw this with `acomagu/fish-async-prompt`
`fisher remove acomagu/fish-async-prompt` fixed this for me.
