### ISSUE TITLE
 completions: fix long `heroku.fish` descriptions #6981 

### ISSUE THREAD

**Issue by 0xtaj** [fish-shell/fish-shell#8794]
Description
Fixes issue https://github.com/fish-shell/fish-shell/issues/6981 `heroku.fish`

Shortened description strings. Removed comments from the file as they're not helpful.

remove `heroku-two-factor` as it is deprecated per: https://github.com/heroku/heroku-two-factor
update `complete $heroku_looking -xa git:clone` to make it as short as possible without losing meaning. (Now 72 Characters as opposed to 92 per https://gist.github.com/ammgws/a0f49d719a5145675c76ff161627c111)

---

Changes to fish usage are reflected in user documentation/manpages.
Tests have been added for regressions fixed
User-visible changes noted in CHANGELOG.md

**Comment by faho** [comment]
Note: We don't require an issue for everything.

This particular one just restates what the pull-request did (which is merged). I'm closing it.
