### ISSUE TITLE
How to define fish_title dynamically?

### ISSUE THREAD

**Issue by kuon** [fish-shell/fish-shell#8798]
`fish, version 3.3.1`

I have the below code in my `config.fish`

```fish
function mutt
  function fish_title
    echo "Email Mutt"
  end
  cd ~/Downloads
  /usr/bin/mutt
end
```

But the title is not updated when mutt is running, it is updated only after quitting mutt.

I figure `fish_title` must be called on new prompt (which makes sense).

Is there a way to "sync" the title before launching `mutt`?

Note: I know that mutt has `ts_enabled` and can update the title itself, but I am still interested in knowing how to do the above.

**Comment by faho** [comment]
How about you just define a fish_title that special-cases mutt?

```fish
function fish_title
    set -l command (status current-command)
    if test "$command" = mutt
        echo "Email Mutt"
    else
        echo $command
    end
end
```

You can use `functions --copy` to rename the old title and call it from this one.

**Comment by kuon** [comment]
Yes that could work. But I should have been more clear in my question, actually I am interesting in "commiting" the title.

For example if I write a script like this (pseudo code):

```fish

function some_job
   set_title "loading data"
   curl ....
   set_title "zipping data"
   zip ...
end

```

**Comment by IlanCosman** [comment]
Just have a variable that `fish_title` responds to.

I.e

```fish
function fish_title
  if test -n "$my_title"
    echo "$my_title"
  else
    # blah
  end
end
```

**Comment by ridiculousfish** [comment]
You can directly change the title by emitting the [proper escape sequence](https://tldp.org/HOWTO/Xterm-Title-3.html). Example:

    echo -n -e '\e]0;title 1\a'
    sleep 1
    echo -n -e '\e]0;title 2\a'
    sleep 1

**Comment by kuon** [comment]
Ah great, thanks. That's nice to know.
