### ISSUE TITLE
New ls behaviour

### ISSUE THREAD

**Issue by seowalex** [fish-shell/fish-shell#8799]
I have just upgraded to fish 3.4.0, and it seems that `ls` now appends a trailing slash to directories by default, when in previous versions it did not. Was there any reason for this change?

Edit: It looks like `ls` now uses the `-F` flag on purpose as per https://github.com/fish-shell/fish-shell/commit/6c8b0a1245174328b53ebebc334613f560906025, which appends an indicator (one of */=>@|) to entries.

**Comment by faho** [comment]
It used to do that, then we accidentally removed it, now we added it back.

If you don't want to have it, make your own `ls` function that doesn't have it. The default is very simple and only tries to turn on some useful features that really should be on by default.
