### ISSUE TITLE
What might prevent fish from finding an exe in the `PATH`?

### ISSUE THREAD

**Issue by EdmundsEcho** [fish-shell/fish-shell#8804]
I have several directories in my `PATH`.  I can see the path required to access the binary of interest.  For some reason, I cannot get fish to find the binary.

### The `PATH`

The path of interest is `/opt/homebrew/bin`

```fish
echo $PATH
/Users/edmund/.asdf/shims /Users/edmund/.asdf/bin /Users/edmund/.local/share/nvm/v16.14.1/bin /Users/edmund/.deno/bin /Users/edmund/.yarn/bin /Users/edmund/.local/bin /opt/homebrew/opt/llvm/bin /Users/edmund/.pyenv/shims /Users/edmund/.pyenv/bin /opt/homebrew/sbin **/opt/homebrew/bin** /usr/local/bin /usr/bin /bin /usr/sbin /sbin /Users/edmund/.krew/bin /Users/edmund/.ghcup/bin /Users/edmund/.cargo/bin /opt/homebrew/opt/findutils/libexec/gnubin /opt/homebrew/opt/make/libexec/gnubin /opt/homebrew/opt/gawk/libexec/gnubin /opt/homebrew/opt/gsed/libexec/gnubin /opt/homebrew/opt/gnu-sed/libexec/gnubin /opt/homebrew/opt/grep/libexec/gnubin /opt/homebrew/opt/ed/libexec/gnubin /opt/homebrew/opt/gnu-tar/libexec/gnubin /opt/homebrew/opt/coreutils/libexec/gnubin /opt/homebrew/opt/libtool/libexec/gnubin
```

### The content of that path

Note the presence of `yarn`

```fish
> ls /opt/homebrew/bin | ggrep yarn
yarn
yarnpkg
```

### Fish not finding the binary

```fish
> yarn
fish: Unknown command: yarn

> which yarn
<empty line>
```

### Other binaries can be found...

Fish can find other binaries in the same path (e.g., `jq` is in the directory)

```fish
> ls /opt/homebrew/bin | ggrep jq
jq

> which jq
/opt/homebrew/bin/jq
```

### The question

What might prevent fish from finding the binary?  (in this case `yarn`). How might I go about problem solving this?

Thank you in advance.

\- E

**Comment by zanchey** [comment]
You could see what the permissions on the file are:

```
stat /opt/homebrew/bin/yarn
```

The output of `contains /opt/homebrew/bin $PATH` will confirm that the path is set right.

**Comment by ridiculousfish** [comment]
Your path contains:

    **/opt/homebrew/bin**

fish does not expand globs in $PATH (nor does bash or zsh in my testing). Any idea how that got there? Anyways the correct path value should be `/opt/homebrew/bin/`

**Comment by EdmundsEcho** [comment]
@zanchey The permissions was the issue.  I confirmed this by toggling the `-/+x` to in fact show how fish will not find the binary if the permission does not include `x`.

```fish
❯ chmod +x /opt/homebrew/bin/yarn

❯ which yarn
/opt/homebrew/bin/yarn

❯ chmod -x /opt/homebrew/bin/yarn
<empty line>
```

This behavior is a "norm" given that I can replicate it in `bash`.

*This said, should it be a norm?*

Receiving an error is in-line with what I would have intuited. 

* Is there a way for the shell to report something like a "execute permission denied"?  

* Would reporting such an error be a breaking-change for scripts that don't expect a return value in the event the permissions are missing?  

* Otherwise, might the difference between the empty response and the error  be a useful hook allowing the programmer to "intervene" accordingly?

**Comment by EdmundsEcho** [comment]
> I'm assuming test -x /opt/homebrew/bin/yarn; echo $status prints 1.

@faho You got it.  This is helpful.  Thank you.

**Comment by faho** [comment]
Okay, here's what we can do:

If you try to execute a command, and none is found, we go through $PATH and try to find a file. If it's not executable, we print that with the command-not-found error.
