### ISSUE TITLE
git autocompletions broken in fish 3.4.0?

### ISSUE THREAD

**Issue by myftija** [fish-shell/fish-shell#8808]
Hi,

I'm using MacOS Monterey 12.1 and iTerm. After upgrading to fish 3.4.0, I noticed that quite a few git autocompletions no longer work. For example, the suggested autocompletions after writing `git switch` are the files in the current directory, instead of the branch names. Suggested autocompletions after writing `git` are also files in the current directory, instead of git commands.

I downgraded back to fish 3.3.1 for now.

**Comment by faho** [comment]
This works for me. You'll want to check that you're actually using the correct git completions and don't have an older version sitting somewhere.

You'll want to check that

```fish
for f in $fish_complete_path/git.fish
    test -r $f; and echo $f
end
```

prints, as the first entry, the same thing as `echo $__fish_data_dir/completions/git.fish`.

**Comment by myftija** [comment]
Thanks for the prompt response. There was indeed a `git.fish` completions file in `/Users/<username>/.local/share/fish/generated_completions/`, which was ahead of the fish 3.4.0 completions path in `$fish_complete_path`. I changed it now and it works. Thanks!

I guess when installing via brew the new version's completions path is appended to `$fish_complete_path`, right? Is there anything I can change in my setup, to avoid such issues when upgrading the fish version?

**Comment by faho** [comment]
>I guess when installing via brew the new version's completions path is appended to $fish_complete_path, right?

The only case where that happens is if you start the new version as a child process of an old one, and it inherits $fish_complete_path.

That requires you to

1. make $fish_complete_path exported (by default it's not - this implies having `set -x fish_complete_path ...` somewhere instead of `set -g fish_complete_path`)
2. run the new version as the child of the old one

Either that or you or something you installed (a plugin or something) messed with $fish_complete_path in other ways.

**Comment by myftija** [comment]
Alright, thanks for elaborating. In my case, I didn't start the new version as a child process or export the `fish_complete_path` variable. But I did add a custom completions directory using `set -gp fish_complete_path ...`. [The docs](https://fishshell.com/docs/current/completions.html#where-to-put-completions) don't mention whether it's okay to modify the `fish_complete_path` variable, but I take it it's not the correct way to add custom completions?
