### ISSUE TITLE
ls command becomes stuck with Chromium source codes

### ISSUE THREAD

**Issue by gonejack** [fish-shell/fish-shell#8814]
Hi, author.

I am following this https://chromium.googlesource.com/chromium/src/+/main/docs/mac_build_instructions.md#Faster-builds trying to build Chromium, after those gigabytes sources code downloaded, fish gets stuck about 2-3 seconds on ***every*** `ls` within directory `src`.

Everything is fine with `Bash` or `sh -c 'env HOME=$(mktemp -d) fish'`.

Here is my `~/.config/fish`, hope this helps.

[fish.zip](https://github.com/fish-shell/fish-shell/files/8302660/fish.zip)

```
fish, version 3.4.0

Darwin Youis-Macbook-Pro-2021.local 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:35:58 PST 2022; root:xnu-8020.101.4~2/RELEASE_ARM64_T6000 arm64

xterm-256color
```

**Comment by faho** [comment]
This is because fish has an `ls` function that enables coloring and indicators. This requires ls to figure that out for each entry, which takes a bit of time.

In large directories, use `command ls`.

**Comment by faho** [comment]
Okay, checking your config, you've enabled "informative" git status in your prompt:

```fish
    if not set -q __fish_git_prompt_show_informative_status
        set -g __fish_git_prompt_show_informative_status 1
    end
```

That requires fish to tell git to *count* all files of various types (e.g. check all files if they are modified instead of stopping at the first and saying "we have at least one modified file").

Disable that.

**Comment by gonejack** [comment]
I'm out of luck with `git config --local bash.showInformativeStatus false` but switching to a new prompt in `fish_config` works, this issue was gone, thank you!
