### ISSUE TITLE
Job status message erased when using multiline prompt

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#8817]
### Discussed in https://github.com/fish-shell/fish-shell/discussions/8742

<div type='discussions-op-text'>

<sup>Originally posted by **lacygoill** February 23, 2022</sup>
Consider this minimal prompt:
```fish
function fish_prompt
    printf '\n$ '
end
```
Written in `/tmp/home/.config/fish/config.fish`.

Start fish like this:

    $ XDG_CONFIG_HOME=/tmp/home/.config fish

Finally, start a job:

    $ sleep 1 &

When the job terminates, it writes a message on the terminal:

    $ fish: Job 1, 'sleep 1 &' has ended

But most of the time, this message is automatically cleared (*maybe* 5 out of 6 times):

![gif](https://user-images.githubusercontent.com/8505073/155185829-df63a3f2-180b-450c-80dd-bed0db0f0548.gif)

The issue disappears if the newline is removed from the prompt.

Is there a way to prevent the message from being cleared?
</div>

I think this is another bug in multiline prompt handling.

**Comment by lacygoill** [comment]
On Ubuntu 20.04, I can reproduce in:

   - GNOME Terminal 3.36.2 using VTE 0.60.3 +BIDI +GNUTLS +ICU +SYSTEMD
   - kitty 0.24.4
   - st 0.8.4
   - xfce4-terminal 0.8.9.1 (Xfce 4.14)
   - XTerm(353)

**Comment by zanchey** [comment]
I can't reproduce on Terminal.app when fish is running locally on macOS, but I can with mosh to a Linux session.

**Comment by krobelus** [comment]
fixed with 32ed0b80da2b4a85486f80f0703a50d4d2a35b4f,  thanks for reporting. Sadly the behavior is still flaky but it's just an occasional extra blank line.
