### ISSUE TITLE
How to trigger \e on OSX?

### ISSUE THREAD

**Issue by KangOl** [fish-shell/fish-shell#882]
From `bind --help`:

    For example, because pressing the Alt key and
    another character sends that character prefixed with an escape
    character, Alt‐based key bindings can be written using the \e escape.
    For example, Alt‐w can be written as \ew.

That doesn't work on OSX because alt is used to trigger alternative keyboard characters.
Is it a way to trigger \e using <esc> key?

**Comment by faho** [comment]
The question here is answered, so I'm closing.
