### ISSUE TITLE
A strange completion appears after changing the initial case of the folder name

### ISSUE THREAD

**Issue by page-down** [fish-shell/fish-shell#8820]
I try to change a folder with initial capital letters to lowercase and then find that a non-existent path prompt appears.

- Make sure there is no history.
- `fish --private -C "cd /tmp; mkdir Debug"`
- Enter the command: `mv Debug debug` shows `mv Debug Debug` ( This issue is tracked in #3134 )
- Delete the first `D` of the second parameter and try to change it to lowercase.
  - `mv Debug |ebug`
  - `mv Debug debug` -> `mv Debug Debug/ebug` (`/ebug` is gray, pressing tab does not complete this part.)

It seems that the `/ebug` part shouldn't be there.

fish from master branch
Reproduced under macOS and Linux.

**Comment by ridiculousfish** [comment]
Thanks for filing. This fixes it, hopefully doesn't break anything new!
