### ISSUE TITLE
Function names and script names must match

### ISSUE THREAD

**Issue by tusj** [fish-shell/fish-shell#883]
When defining new functions and placing them in ~/.config/functions, the filename.fish needs to be the same as the function name defined in the file. Otherwise, the function is only available if the filename is loaded first, which triggers an error. Correct behaviour should be to either not load the function at all, or be permissive in file naming.

**Comment by faho** [comment]
This is the other case of #735 - here it won't load the function, there it will show the filename.

**Comment by krader1961** [comment]
Yet another case of someone trying to redefine the `test` builtin and being surprised they broke their shell. See issue #3000.
