### ISSUE TITLE
`funcsave -q` is not actually quiet

### ISSUE THREAD

**Issue by anhnamtran** [fish-shell/fish-shell#8830]
Fish Version: 3.4.0
OS Version: Linux 5.4.0-104-generic #118~18.04.1-Ubuntu SMP Thu Mar 3 13:53:15 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
TERM: xterm-256color

I've tried fish without any third-party customizations by executing:
```bash
sh -c 'env HOME=$(mktemp -d) fish'
```
And running the following:
```fish
username@host /h/username> function testFunc; echo "Test"; end; funcsave -q testFunc
```
***Expected behavior***
```fish
username@host /h/username> function testFunc; echo "Test"; end; funcsave -q testFunc
username@host /h/username>
```
***Actual behavior***
```fish
username@host /h/username> function testFunc; echo "Test"; end; funcsave -q testFunc
funcsave: wrote /tmp/tmp.Jhyt5f19Lo/.config/fish/functions/testFunc.fish
username@host /h/username>
```
The actual behavior is synonymous to running the command without the `-q` flag.

***Reasoning***
I believe this is a small-ish bug, the [3.4.0 version of `funcsave`](https://github.com/fish-shell/fish-shell/blob/c7e4350ab6c5dc6ae5cca3b0bd2401db59ee32ed/share/functions/funcsave.fish) incorrectly defines/checks the `-q` flag. That is, [line 2](https://github.com/fish-shell/fish-shell/blob/3.4.0/share/functions/funcsave.fish#L2) defines the opt as just `q`, while [line 32](https://github.com/fish-shell/fish-shell/blob/3.4.0/share/functions/funcsave.fish#L32) checks for `_flag_quiet`. 

Per the [`argparse` documentation for 3.4.0](https://fishshell.com/docs/current/cmds/argparse.html)
> x means that only -x is valid. It is a boolean that can be used more than once. If it is seen then _flag_x will be set to the count of how many times the flag was seen.

So either `funcsave` needs to declare `q/quiet` for the opts, or check `_flag_q` instead.

I've tested it by editing the `funcsave.fish` in my `/usr/share/fish/functions/funcsave.fish` to have `q/quiet` and the behavior was fixed.

**Comment by faho** [comment]
It appears this long option was *removed* in ed8c78c0ea1e19cbf0e8898f7b060a450598df56? That seems unfortunately misguided.

Terribly sorry about that, I'm putting it right back in.
