### ISSUE TITLE
fish_prompt event does not fire when prompt draws on new lines due to cancellation or syntax error

### ISSUE THREAD

**Issue by page-down** [fish-shell/fish-shell#8832]
I recently tried to simplify the following prompt marking code.

https://github.com/kovidgoyal/kitty/blob/v0.24.2/shell-integration/fish/vendor_conf.d/kitty-shell-integration.fish#L80-L123

When I try to replace the code with the following, I found that when `fish_prompt` redraws on a new line when ctrl-c (command not executed yet), or when there is a syntax error, it does not trigger the `fish_prompt` event.

```fish
function __mark_prompt --on-event fish_prompt
    echo -en "\e]133;A\a"
end
```

In these cases (prompt on new lines), should the fish_prompt event be emitted?

```rst
- ``fish_prompt``, which is emitted whenever a new fish prompt is about to be displayed.
```

```text
fish> debug^C  # <- cmd not executed yet
fish>  # <- no fish_prompt event

fish> a=1
fish: Unsupported use of '='. In fish, please use 'set a 1'.
fish> a=1  # <- no fish_prompt event
```

For now (We need to support the current version of fish),
Is there a better way to mark prompt? Is the following enough?
```fish
function __mark_prompt --on-event fish_cancel --on-event fish_posterror --on-event fish_prompt
    echo -en "\e]133;A\a"
end
```

Or is the best way still to wrap fish_mode_prompt, fish_prompt functions?

Thank you.

These would no longer be needed if the OSC 133 prompt marking could be built in.

**Comment by faho** [comment]
This is indeed what the fish_posterror event is for.

**Comment by page-down** [comment]
Thanks.

I also noticed that posterror does not have a corresponding pre-error, which makes it difficult to mark the error output area lines.
So the error message is currently grouped together with prompt.

Do you think it makes sense to emit the fish_prompt event for the case of repainting the prompt on a new line?
Is such PR acceptable?

**Comment by faho** [comment]
Sorry, but events aren't usable for that sort of marking (because you can always have multiple functions subscribed to an event, and you can never guarantee your last).

To be honest, I don't believe we're really all that interested in the feature.
