### ISSUE TITLE
receiving "explorer.exe: command not found" in FISH, but fine in other shells.  

### ISSUE THREAD

**Issue by bjagasia** [fish-shell/fish-shell#8838]
Hi Fish team, i've been receiving "`explorer.exe: command not found`" in FISH. The command used to work perfectly fine a few days ago but now it doesn't seem to be working anymore. I did receive a windows update and had to disable and re-enable WSL for the Ubuntu distro layer to recognize `explorer.exe` but seems like FISH is still having issues. I've provided the requested details below. 

### Fish Versions

```
╰─ fish --version
fish, version 3.4.0
```
```
╰─ echo $version
3.4.0

```

### Running Windows 11 Pro with Ubuntu 20.04 Distro and Fish Shell with WSL2. 

```
╰─ uname -a
Linux BJAGASIA-DIGITALSTORM 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
```
╰─ echo $TERM
xterm-256color

```
### Running fish without third-party customizations:

```
╰─ sh -c 'env HOME=$(mktemp -d) fish'
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
bjagasia@BJAGASIA-DIGITALSTORM /h/bjagasia> explorer.exe .
explorer.exe: command not found
bjagasia@BJAGASIA-DIGITALSTORM /h/bjagasia [127]>
```

### asciienma.org recording:
https://asciinema.org/a/1Mak5M2Q11AJFmlgz9SwcX7Ys

**Comment by bjagasia** [comment]
As a current workaround I added the following aliases to my `~/.config/fish/config.fish` file.

```
# explorer aliases
alias explorer='/mnt/c/Windows/explorer.exe .'
alias explorer.exe '/mnt/c/Windows/explorer.exe .'

```

However, not sure why the functionality stopped working in the first place.

**Comment by faho** [comment]
What happens here is that /mnt/c/Windows is not in $PATH.

Most likely you've changed a terminal or WSL setting and it's no longer adding windows paths.

**Comment by bjagasia** [comment]
Weird, because when I run echo `$PATH` in both the Ubuntu session and drop into the Fish session, I don't see /mnt/c/Windows. However, the explorer.exe command works in Ubuntu and not Fish. Or am I misunderstanding? thanks for the prompt response

**Comment by faho** [comment]
So, calling "explorer.exe" causes the shell to look up what that *means*. It'll go through its functions and aliases, and then it'll go through the directories in $PATH.

If explorer.exe is indeed in /mnt/c/Windows, then either that directory or an equivalent one (for example a symlink to it) needs to be in $PATH so you can call things there simply by name. Or you need a function or alias that calls a specific thing.

This will be the same in fish and in bash.

> the Ubuntu session 

Ubuntu is the *operating system*. Your fish is also installed on Ubuntu. What you are referring to is *bash*, Ubuntu's default interactive shell.

**Comment by bjagasia** [comment]
Thank you! @faho. Appreciate the clarification -- I'll need to ensure I'm using my terminology correctly! :) I went ahead and added the following to my .bashrc file and that seemed to have fixed it. I wonder why it may have disappeared in the first place... but glad it's working again!

`export PATH=$PATH:/mnt/c/Windows/`

Thank you!
