### ISSUE TITLE
cannot install fish on amazon linux 2 (centos7), /usr/libexec/platform-python has no provider

### ISSUE THREAD

**Issue by neyb** [fish-shell/fish-shell#8842]
<details>
<summary>asked information (not relevent)</summary>

Please tell us which fish version you are using by executing the following:
3.3.1 (updating to 3.4.1)

Please tell us which operating system and terminal you are using. The output of `uname -a` and `echo $TERM` may be helpful in this regard although other commands might be relevant in your specific situation.

<details>
<summary>linux amazon 2, based on rhel7, based on centos7</summary>

    ❯ cat /etc/*release
    NAME="Amazon Linux"
    VERSION="2"
    ID="amzn"
    ID_LIKE="centos rhel fedora"
    VERSION_ID="2"
    PRETTY_NAME="Amazon Linux 2"
    ANSI_COLOR="0;33"
    CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
    HOME_URL="https://amazonlinux.com/"
    Amazon Linux release 2 (Karoo)
    ❯ rpm -E %{rhel}
    7
</details>

Tell us how to reproduce the problem. Including an asciinema.org recording is useful for problems that involve the visual display of fish output such as its prompt.

<details>
<summary>install fish</summary

    cd /etc/yum.repos.d/
    wget https://download.opensuse.org/repositories/shells:fish:release:3/CentOS_7/shells:fish:release:3.repo
    yum install fish
</details>

or with an existing installation `sudo yum update`

</details>

Hello,

I have a linux amazon 2 (rhel7, centos7) with a fish 3.3.1 already installed.

when i run `sudo yum install fish` I get a `    Error: Package: fish-3.4.1-1.1.x86_64 (shells_fish_release_3) Requires: /usr/libexec/platform-python` error.

<details>
<summary>error</summary>

    ❯ sudo yum install fish
    Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
    amzn2-core                                                                                                                                | 3.7 kB  00:00:00     
    Resolving Dependencies
    --> Running transaction check
    ---> Package fish.x86_64 0:3.3.1-1.13 will be updated
    ---> Package fish.x86_64 0:3.4.1-1.1 will be an update
    --> Processing Dependency: /usr/libexec/platform-python for package: fish-3.4.1-1.1.x86_64
    --> Processing Dependency: /usr/libexec/platform-python for package: fish-3.4.1-1.1.x86_64
    --> Finished Dependency Resolution
    Error: Package: fish-3.4.1-1.1.x86_64 (shells_fish_release_3)
               Requires: /usr/libexec/platform-python
     You could try using --skip-broken to work around the problem
     You could try running: rpm -Va --nofiles --nodigest

</details>

I suppose the same error applies to centos 7

more information:

<details>
<summary>repo used</summary>

    ❯ cat /etc/yum.repos.d/shells:fish:release:3.repo 
    [shells_fish_release_3]
    name=Fish shell - 3.x release series (CentOS_7)
    type=rpm-md
    baseurl=https://download.opensuse.org/repositories/shells:/fish:/release:/3/CentOS_7/
    gpgcheck=1
    gpgkey=https://download.opensuse.org/repositories/shells:/fish:/release:/3/CentOS_7/repodata/repomd.xml.key
    enabled=1

</details>

<details>
<summary>yum deplist fish</summary>

    ❯ yum deplist fish
    Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
    package: fish.x86_64 3.4.1-1.1
      dependency: /bin/sh
       provider: bash.x86_64 4.2.46-34.amzn2
      dependency: /usr/bin/pkg-config
       provider: pkgconfig.x86_64 1:0.27.1-4.amzn2.0.2
       provider: pkgconfig.i686 1:0.27.1-4.amzn2.0.2
      dependency: /usr/libexec/platform-python
       Unsatisfied dependency
    ...
   
</details>

<details>
<summary>no package seems to provide /usr/libexec/platform-python</summary>

    ❯ yum provides /usr/libexec/platform-python
    Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
    No matches found

</summary>

**Comment by zanchey** [comment]
Yeah, the actual RPM depends on `python` only, so there's presumably something transitive mucking it up.

`repoquery --treerequires fish` might help.

**Comment by neyb** [comment]
I've run a `repoquery --tree-requires fish`, no trace of /usr/libexec/platform-python, then I've run a `repoquery -i fish` to try to understand which repo was used... then i retry a `sudo yum install fish`... And now everything is fine... Probably a cache thing I don't know...

Anyway thanks.
