### ISSUE TITLE
fish_config doesn't work on Ubuntu 22

### ISSUE THREAD

**Issue by StewAlexander-com** [fish-shell/fish-shell#8844]
support@Network-VM /tmp [1]> fish_config
Web config started at file:///tmp/web_config6znokgmz.html

FireFox cannot find the file:

File not found

Firefox can’t find the file at /tmp/web_config6znokgmz.html.

----------------------
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu Jammy Jellyfish (development branch)"
PRETTY_NAME="Ubuntu Jammy Jellyfish (development branch)"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04 (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

FireFox 98.02

**Comment by faho** [comment]
Ah, Ubuntu's firefox is now delivered via snap.

You'll want to complain to Ubuntu upstream. I don't believe there is anything we can do here, sorry!

**Comment by faho** [comment]
See e.g. https://forum.snapcraft.io/t/firefox-snap-no-access-to-gvfs-and-tmp/27253
