### ISSUE TITLE
 Prevent fish command from executing through fish_preexec

### ISSUE THREAD

**Issue by yonas** [fish-shell/fish-shell#8845]
fish, version 3.3.1
FreeBSD 13.0-RELEASE-p10  root@amd64-builder.daemonology.net:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64

Similar to #5068, this is a feature request. Can we add '--check-exit-code' flag - or any other name - so that:

`
function example --on-event fish_preexec --check-exit-code
`

would check that `example` completes with exit code zero.

Fish would run these functions asynchronously, but wait their completion and verify their exit code is zero before running the command.

**Comment by faho** [comment]
Sorry, no. This isn't how events work currently, and I do not believe we want to add it.

Make your own "check-execute" function and bind it to enter.
