### ISSUE TITLE
Increase history limitation

### ISSUE THREAD

**Issue by meichengg** [fish-shell/fish-shell#8846]
I would like to increase the limitation of my `fish_history` file for storing old commands, is there any way i can do this? Sorry for this spammy issue because i couldn't find the documentation about this.

**Comment by faho** [comment]
There is not. The limit is 256 * 1024 *deduplicated* entries, hardcoded in the source, and so far nobody has been hitting that.

If you are hitting that, I would like to know about your use case, because that seems unlikely to me.

**Comment by meichengg** [comment]
For example, zsh and bash allow their users to adjust history command limitation, would be more convenient if fish allows the same.

**Comment by faho** [comment]
Why do you want that? What do you want to *do* with it?

We aren't going to make it customizable just to have it customizable, that's pointless!

If you don't hit the limit, and the file doesn't grow too large, then the limit doesn't matter and there is no need to have it changeable.

**Comment by meichengg** [comment]
What if the limit is reached? There is no particular documentation for this.

The oldest command gets deleted from the history file?

**Comment by faho** [comment]
Yes.

But again: We don't believe anyone has ever managed to reach that point. My history is months old and includes 22391 entries, that's under 10% of the limit. It is about two years old. You would expect it to grow *slower* over time because of the deduplication.

**Comment by meichengg** [comment]
If i want to store the old commands, after 2 years as you said, is there any wordaround for this? Like backing up `fish_history` to `fish_history.1` and creating an empty `fish_history` file again?

**Comment by faho** [comment]
You should be able to store the file and you can erase the history with `history clear`. I'm not entirely sure how hard it is to convince fish to pick it up again in case you want to "inject" the old commands - I don't know what exactly you want to do here.

Or you can set $fish_history to e.g. "fish2" - so it will use a file called "fish2_history".

**Comment by Darkshadow2** [comment]
2 years isn't any kind of limit. My fish history goes back to 2013 (first entry has `when: 1365951112`), and has 53129 entries - a whole 20% of the limit.

At this rate, it'll take another 60 or so years to fill it up 😆
