### ISSUE TITLE
Fish remember last folder i was in.

### ISSUE THREAD

**Issue by Aldodo91** [fish-shell/fish-shell#8858]
I use fish version 3.4.1. 
currently shell fish remembers the last folder i was in, even if i close and reopen the terminal, is there a way to disable this behavior?

**Comment by ridiculousfish** [comment]
fish shell does not have a feature like this; this is being implemented by your terminal emulator. What terminal emulator are you using? In iTerm2 this is controlled via Profiles->General->Working Directory.

**Comment by faho** [comment]
Question was answered, closing. If you have any more feel free to ask, of course.
