### ISSUE TITLE
unable to terminate certain processes with keyboard interrupt (ctrl+c)

### ISSUE THREAD

**Issue by yqiang** [fish-shell/fish-shell#886]
OS X 10.8.3
fish 2.0.0

From time to time fish doesn't return command back to shell after exiting an application. 

Repro steps:
- Run fish_config
- Hit ctrl+c to exit the program

Expected behavior:
- User is returned to the shell

Actual behavior
- Shell seems to be stuck trying to exit. The last output is "KeyboardInterrupt" from the python script.

Sample from activity monitor:
https://gist.github.com/yqiang/5834550

**Comment by jdxcode** [comment]
I had the same as @yqiang Fixed it with:

```
$ omf update
```
