### ISSUE TITLE
Unable to bind up arrow key in insert mode when using vi bindings

### ISSUE THREAD

**Issue by mrjones2014** [fish-shell/fish-shell#8861]
Fish version: `fish, version 3.4.1`

Steps to Reproduce:

1. `sh -c 'env HOME=$(mktemp -d) fish` to start a clean environment
2. `fish_vi_key_bindings` to enable vi bindings
3. bind something to the up arrow with `bind -k up something`, `bind -M insert -k up something`, or `bind -M insert --preset -k up something` (none of the variants work)
4. It should work but it doesn't

It also doesn't matter if you bind the up arrow key before or after enabling `fish_vi_key_bindings`

**Comment by faho** [comment]
Please run `fish_key_reader` and press the up-arrow.

Most likely your $TERM simply contains a different sequence than the terminal actually sends.

**Comment by mrjones2014** [comment]
Output from `fish_key_reader` when pressing the up arrow key:

```
Press a key:
bind \e\[A 'do something'
```

but if I bind that key sequence, that doesn't work either.

**Comment by faho** [comment]
That would be highly surprising, and it does work in my testing.

The default for `bind` is to bind things in "default" mode, which is vi's "normal" mode.

So if you run `bind \e\[A 'echo foo'` that will make up-arrow print "foo" in normal mode. If you run `bind -M insert \e\[A 'echo foo'` it will do that in insert mode. Does that not work for you?

**Comment by mrjones2014** [comment]
It wasn't working this morning, but it seems to be working now. My best guess is it had something to do with a stale session with tmux or something. Not sure exactly. But it's working now if I manually bind `\e\[A`.

For my own knowledge, is `\e\[A` the normal code for up arrow or no?

**Comment by faho** [comment]
>For my own knowledge, is \e\[A the normal code for up arrow or no?

It's not technically *required*, but it is the normal code, yes.
