### ISSUE TITLE
"fish: Unknown command: fish_job_summary" with every command

### ISSUE THREAD

**Issue by johtso** [fish-shell/fish-shell#8862]
fish version 3.4.1

Every command I execute fails with the following error:
```
fish: Unknown command: fish_job_summary
in event handler: handler for generic event 'fish_job_summary'
```

Running without customisations does not give this issue.

Any tips on how I can debug this as the error does not give any indication of the source of the issue.

**Comment by johtso** [comment]
I tried doing an `omf update` and I got the following error:
```
Could not send child 48707, 'basename' in job 1, 'command basename $path' from group -1 to group 48707
setpgid: No such process
Could not send child 48710, 'basename' in job 1, 'command basename $path' from group -1 to group 48710
setpgid: No such process
No release versions found.
Oh My Fish is up to date.
You are now using Oh My Fish version .
```

**Comment by krobelus** [comment]
On Wed, Apr 06, 2022 at 05:15:56PM -0700, Johannes wrote:
> Running without customisations does not give this issue.
> 
> Any tips on how I can debug this

Delete things from ~/.config/fish until it works

**Comment by faho** [comment]
It appears either:

1. Your installation is incomplete
2. Your $fish_function_path is broken

`fish_job_summary` should be defined in a file in `$__fish_data_dir/functions/fish_job_summary.fish`.

Run this:

```fish
set -S fish_function_path

sha256sum $__fish_data_dir/functions/fish_job_summary.fish
```

This will print your $fish_function_path in an unambiguous manner, and will tell us what your fish_job_summary.fish looks like.

**Comment by kschumy** [comment]
I had this same problem after updating Fish via brew. I just quit my terminal (iTerm2), and everything worked when I came reopened it.

**Comment by johtso** [comment]
@kschumy I think it very well might have been to do with that!

Was hard to do any digging as no commands could be run in the offending sessions.

Well, it was a transient issue, so no big deal. Thanks for the help!

**Comment by wybert** [comment]
> I had this same problem after updating Fish via brew. I just quit my terminal (iTerm2), and everything worked when I reopened it.

How to deal with it

**Comment by drewcdisc** [comment]
Same problem. Same fix. Kill your terminal and re-start. Tx!

**Comment by WarFox** [comment]
You could also do `exec $SHELL` if you do not want to kill your terminal and restart
