### ISSUE TITLE
Valid commands following redirection symbols at command line start are colored as $fish_color_command instead of $fish_color_error

### ISSUE THREAD

**Issue by schuelermine** [fish-shell/fish-shell#8877]
```
fish, version 3.4.1
3.4.1
```

Typing something like `>echo` doesn’t color the `echo` as an error, but it should

**Comment by schuelermine** [comment]
https://asciinema.org/a/487589

**Comment by neerajram30** [comment]
Hi there, is the issue solved ?

**Comment by schuelermine** [comment]
No

**Comment by neerajram30** [comment]
Can I work on solving this issue?

**Comment by faho** [comment]
@neerajram30 It's open and nobody has said they're working on it, so go for it!

**Comment by pradyotRanjan** [comment]
I would like to work on this.

**Comment by floam** [comment]
Sure, go ahead, it was nearly a month ago the other individual said they were interested in solving it.

**Comment by mikoreal** [comment]
I'm trying to solve this, however I have a bit of trouble finding how and in which files it's defined how colors are autosuggested based on validity of the commands. Could anyone provide any info on that?

**Comment by krobelus** [comment]
@mikoreal probably this can be fixed inside `highlighter_t::visit(const ast::decorated_statement_t &stmt)`.
If a redirection's source_range occurs textually before the statement's command, then we should probably color at least the command token as error. The syntax tree nodes are defined in `src/ast.h`.

**Comment by himmel-rider** [comment]
@krobelus  Thanks your guidance. I have submitted the PR for review. Could you please take a look when you have a chance? Thank you again! Link is  https://github.com/fish-shell/fish-shell/pull/9587

**Comment by 99jte** [comment]
May be in over my head with it (to my credit, it's still labeled a "good first issue"), but have there been any further thoughts on the options to solve this discussed in https://github.com/fish-shell/fish-shell/pull/9587#issuecomment-1436036722 ?

**Comment by ridiculousfish** [comment]
No. Probably this should be fixed at the AST level: if we encounter an erroneous redirection, then try consuming the next token and if it's a string then pull that into the error range.
