### ISSUE TITLE
`env` completions don't trigger the subcommand's completion

### ISSUE THREAD

**Issue by ericonr** [fish-shell/fish-shell#8881]
- `fish, version 3.3.1-1295-g4e109fe96`
- I'm using Linux and tmux inside foot, but I don't think it matters for this one
- this bug can be reproduced without any customizations
- recording https://asciinema.org/a/nHw9yXr01Iu5f1T44wQVy7lTf

Essentially, env seems to have received better auto completions for the environment vars (including for the `-u` option, which I remember didn't use to work), but other auto completions are broken. There are multiple issues here:

- `env [--] <partial_command_name>` does not have the option of auto completing a command name, only environment variables
- `env <command_name> <partial_file_name>` doesn't work and only shows environment variable options
- `env <command_name> -` shows short options for the `env` command instead of the subcommand
- `env <command_name> --` shows only environment variables that contain two underscores (such as `__fish_bin_dir`)

**Comment by ericonr** [comment]
Thanks @faho!

Now it seems the environment variables are only shown when I don't have anything typed out and press tab, so I can't actually use tab auto completion to type out an entire env var. Is that expected?

**Comment by floam** [comment]
That's an interesting problem. You almost wish you could present two panes through the pager at once, completing further variables in one and possible commands in another since both possible in that position.
