### ISSUE TITLE
run for loop in the terminal

### ISSUE THREAD

**Issue by GoingMyWay** [fish-shell/fish-shell#8890]
I tried to delete some files in the terminal
```
for dd in `ls`; do rm -rf $dd/replays; done
```
However, the syntax is not right. In bash, it is ok. Do you have any suggestions?

**Comment by ridiculousfish** [comment]
See [fish for bash users](https://fishshell.com/docs/current/fish_for_bash_users.html#command-substitutions). In this case you want:

    for dd in (ls); rm -rf $dd/replays; end
