### ISSUE TITLE
hide vi-mode [I] or [N]

### ISSUE THREAD

**Issue by ayoubelmhamdi** [fish-shell/fish-shell#8897]
- when am using the `vi-mode`:
how can hide the `vi-mode` form `prompt`:
```bash
[I] ~ ❯ 
```
- TO BE only `prompt` with keep using the vi-mode, just style.
```bash
~ ❯
```

**Comment by IlanCosman** [comment]
Run this:
```fish
function fish_mode_prompt; end; funcsave fish_mode_prompt
```
That will disable the `[I]` etc.

**Comment by ayoubelmhamdi** [comment]
it's work.
so this function `fish_mode_prompt` that handle `vi-mode`
```fish
function fish_mode_prompt
    echo "foo"
end
```
