### ISSUE TITLE
Set version number to something sensible

### ISSUE THREAD

**Issue by zanchey** [fish-shell/fish-shell#890]
It would be nice if `fish --version` output a version number that could be used to identify what source it was built from.

Something like `git describe --tags` works well if you have Git installed. If not, it should fall back to a manually specified value; the build scripts could do this for tarballs.

**Comment by faho** [comment]
Is this still an issue?

**Comment by zanchey** [comment]
I'd still like to make this work in Xcode, but I haven't had much luck.

**Comment by ianjray** [comment]
Hi, #2433 generates fish-build-version.h during the Xcode build using the build_tools/git_version_gen.sh script.
