### ISSUE TITLE
History is not updated when running multiple commands in the same line

### ISSUE THREAD

**Issue by liuml07** [fish-shell/fish-shell#8905]
### Environment

```
$ fish --version
fish, version 3.4.1
$ echo $version
3.4.1
$ uname -a
Darwin Mingliangs-MacBook-Pro-M1-Max.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64
$ echo $TERM
xterm-256color
```

### Problem

Running following commands, I got "true". I expect "false".

```
$ sh -c 'env HOME=$(mktemp -d) fish'
$ true
$ false; echo $history[1]
true
```

**Comment by faho** [comment]
`false; echo $history[1]` is one entry in the history.

The history is updated per-commandline.

**Comment by krobelus** [comment]
yeah I think this is the least surprising behavior.

If there is a concrete use  case, we have a mechanism for tracing every individual process (`set fish_trace 1`) that we could perhaps repurpose but it's probably not worth it.

**Comment by liuml07** [comment]
Thanks for the context.

Is there a way I can get the last command (`false`) in the same command line?

**Comment by faho** [comment]
There is no way to change this behavior so that `foo; bar` counts as two different history elements.

You haven't really explained what you want to *do* here, so we can't say any more.

**Comment by liuml07** [comment]
Probably I'm asking a XY question.   This probably should be a user question instead of an issue.

I will get email after foo completes using command `foo; notify`. I now want to know the last command foo from "notify" fish function so the notification is for foo. Running `bar; notify` will be sending notification including bar.

"notify" includes `$status` which is for command "foo" but `$history[1]` is not foo.

I now learnt history is for per-commandline and it makes sense to me. Thanks

**Comment by krobelus** [comment]
I just type `foo` <kbd>Enter</kbd> `notify` <kbd>Enter</kbd>.
A wrapper script (like `notify foo`) would be a cross-shell solution.
Another potential solution is a post-exec hook (`function --on-event fish_postexec`)

Though I think it's weird that there is no way to access the commandline *while* the command is running.

	$ sleep 3 && echo done, command: (status current-command) commandline: (commandline)
	done, command: sleep commandline:

so `status current-command` works but neither `commandline` nor `history` do.

Probably this is best exposed as `status current-commandline`.

**Comment by liuml07** [comment]
Thanks for providing solutions. They work for me!

I now start using the two solutions both: 1) I added a post-exec hook for command long commands like `mvn package` and `newt ci tail` etc, and 2) I will type `foo` <kbd>Enter</kbd> `notify` <kbd>Enter</kbd> for ad hoc commands.
