### ISSUE TITLE
`jobs` shows too high CPU usage

### ISSUE THREAD

**Issue by septatrix** [fish-shell/fish-shell#8919]
The output of `jobs` sometimes shows much too high CPU usage stats for background jobs.
It seems somewhat racy as for processes with normal usage it is either very high or 0%. `yes` seems to always show a too high result.

* fish, version 3.4.1
* 5.16.19-200.fc35.x86_64 (Fedora 35)

```
~ $ yes >/dev/null &
~ $ jobs
Job	Group	CPU	State	Command
1	1324566	99039434%	running	yes >/dev/null &
~ $ ps -p $last_pid -o %cpu,cmd
%CPU CMD
99.3 yes
```

**Comment by ridiculousfish** [comment]
Nice find. Bisects to 7a1c005b42da35b52e04705b64429c5ff962cdff.
