### ISSUE TITLE
undo alias expansion inline in terminal via pressing `esc` or `ctrl+space`

### ISSUE THREAD

**Issue by backermanbd** [fish-shell/fish-shell#8920]
I have this configuration in my config.fish
```
abbr -a gc git commit
```
After writing `gc` in terminal and pressing `space`, `gc` expands to `git commit` 

**Feature request**
For some reason, if i make a mistake, then i want to revert back from `git commit` to `gc` via pressing `space` or `ctrl+space`
Any solution for this?

**Terminal**: kitty
**Fish**: 3.1.2
**Distro**: Linux am-7c67a2811d4d.intern 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux

**Comment by faho** [comment]
What you want is "undo", bound to ctrl-z by default.

And then you want to press ctrl-space to just insert a space instead of expanding the abbreviation.

I would also recommend, if that's an abbreviation you regularly want to use unexpanded, to just rename it - call it "gco" or something instead.

**Comment by faho** [comment]
Okay, question was answered, closing!
