### ISSUE TITLE
Change fish_greeting function for superuser

### ISSUE THREAD

**Issue by MephresGH** [fish-shell/fish-shell#8922]
Hello, there. I just wanted to ask about something I found rather confusing: When I try to create a custom fish_greeting call as user, everything works as intended, but I somehow am not able to change the function call for the superuser/su, as it just changes the output of the user shell. The command I use to change the shell is "set -U fish_greeting '*test*'", so how can I change the greeting for the superuser? Do I need to pipe the command into a sudo -s, do a simple su in the script for that, or something else? I hope there is a solution to my question, as I am sure that I simply misunderstand something here. Thank you.

### System Information:

- Fish Shell: version 3.4.1
- Distro: EndeavourOS Linux SOTA 5.17.5-arch1-1 kernel
- Terminal: Alacritty

**Comment by krobelus** [comment]
universal variables are stored in ~/.config/fish/fish_variables, so they work per-user.
You'd need to login as root and run `set -U fish_greeting '*test*'` again

If you want to change it for all users, you can set the variable in /etc/fish/conf.d/ or create a function /etc/fish/functions/fish_greeting

**Comment by MephresGH** [comment]
I do already know that, I just want to know how I could do it in a script if I wanted to quickly set up the fish shell on another system? I cannot simply log into the superuser and then run that user-specific command, and piping the command into a su command has either caused errors or makes the terminal freeze indefinetly until it is being re-opened.

**Comment by krobelus** [comment]
> I just want to know how I could do it in a script if I wanted to quickly set up the fish shell on another system?

	# echo 'set -g fish_greeting test' >> /root/.config/fish/config.fish

or just for one shell

	$ sudo fish -C 'set -g fish_greeting test'

> I cannot simply log into the superuser and then run that user-specific command

Not sure what you mean. It only works if you have root access

> and piping the command into a su command has either caused errors or makes the terminal freeze indefinetly until it is being re-opened.

I don't know what commands you tried.

**Comment by MephresGH** [comment]
`echo 'set -g fish_greeting test' >> /root/.config/fish/config.fish`

I can only do that when I'm already logged in as superuser, so how could I log in as admin in my script of choice and implement such a command quickly and go back to normal user privileges immediately after for safety reasons? I want to use it in a way like doing "sudo pacman -Syu", but I'm fine with it being piped as well.

`I don't know what commands you tried.`

Might be foolishness, but I tried to pipe the command into "sudo -s" and "su", and do the reverse. Both didn't work, and trying to pipe the superuser command into the fish_greeting command only led to the terminal freezing, independent of what terminal is being used.

**Comment by krobelus** [comment]
If you want a one-off commend there are a bunch of options

	echo 'set -g fish_greeting test' | sudo tee /root/.config/fish/config.fish

or

	sudo sh -c 'echo "set -g fish_greeting test" > /root/.config/fish/config.fish'

> I tried to pipe the command into "sudo -s" and "su"

I guess `sudo -s` uses something other than fish by default so you could use

	echo 'set -U fish_greeting test' | sudo fish

**Comment by MephresGH** [comment]
Both commands actually work without any adjustments, splendid! Thank you, but that leaves the question: will the fish_greeting function stay the same after reboot?

**Comment by krobelus** [comment]
Yeah if you write to a file, it's persistent. `set -U` also writes a file.

**Comment by MephresGH** [comment]
Ah, perfect. Then this issue can be closed. Thank you very much for the help and have a great day!
