### ISSUE TITLE
Filename suffix "prioritization" is broken for multiple suffixes

### ISSUE THREAD

**Issue by mhmdanas** [fish-shell/fish-shell#8924]
## System info

- Fish version: 3.4.1
- OS: macOS 12.3.1
- Terminal: Alacritty 0.10.1 with tmux 3.2a

## Bug

A common pattern in Fish completions is something like the following:

https://github.com/fish-shell/fish-shell/blob/908da627b8a37290a23996e6fe0f5f6c8d3273b3/share/completions/unzip.fish#L44-L48

The idea is that files with these suffixes would be prioritized over others. However, what actually happens is that only the first suffix is prioritized. See https://asciinema.org/a/M3W6vObHVvm1Ldygwp3Qc352B for a quick demonstration with `unzip`, but this applies to all completions that use such a pattern.

This bug is reproducible even without third-party customizations.

https://github.com/fish-shell/fish-shell/issues/8512 may be relevant.

**Comment by mqudsi** [comment]
@zanchey I pushed the fix for this into the 3.6.1 branch.
