### ISSUE TITLE
Seems printf/echo -e does not handle escape correctly

### ISSUE THREAD

**Issue by xltan** [fish-shell/fish-shell#8925]
fish, version 3.4.1
```
> echo -e '1\\n2'
1
2
```
expect result:
`1\n2`

**Comment by krobelus** [comment]
This is working as intended. Unlike in POSIX shells, fish treats two consecutive backslashes as a single backslash even inside single quotes. See also https://fishshell.com/docs/current/language.html#quotes
So `echo` actually only receives one backslash. You can add more backslashes to prevent escaping

**Comment by xltan** [comment]
Thanks for answering, do we have options to disable this behavior, so I can make it work well with other program?

**Comment by krobelus** [comment]
There is no option to change that, sorry. In which scenario is this important to you?

Note that if you use ctrl+v to paste inside a single-quoted string, fish will automatically escape backslashes

	echo '1\\\\n2' | wl-copy
	echo -e '
	# now press ctrl+v
	echo -e '1\\\\n2

**Comment by xltan** [comment]
currently I have a json dumped string variable, I want to pipe it to another command. And I don't want to change the value of that variable

**Comment by krobelus** [comment]
I'm not sure what you're doing exactly, and how this is related to `echo -e` but there are many fine solutions

	set jsondata "$(cat data.json)"
	echo $jsondata | somecommand		# "echo" forwards the json data as-is

if you have the json dump not in a file but in clipboard you can run this and paste

	set jsondata "$(cat)"

**Comment by xltan** [comment]
```
❯ set x (python -c "import json;print(json.dumps({'1':'\n2'}))" ) | echo $x
{"1": "\n2"}

❯ set x (python -c "import json;print(json.dumps({'1':'\\n2'}))" ) | echo $x
{"1": "\n2"}

❯ set x (python -c "import json;print(json.dumps({'1':'\\n2'}))" ) | echo -e $x
{"1": "
2"}

❯ set x (python -c "import json;print(json.dumps({'1':'\n2'}))" ) | echo -e $x
{"1": "
2"}
```

**Comment by krobelus** [comment]
okay, do you expect any other behavior?

BTW jq can be helpful too 

	$ set x (python -c "import json;print(json.dumps({'1':'\n2'}))")
	$ echo $x | jq '."1"'
	"\n2"
	$ echo $x | jq '."1"' --raw-output 

	2

> set x ([...]) | echo $x

this should be `set x ([...]) ; echo $x`, because piping into echo is useless.

**Comment by xltan** [comment]
Thanks! I am using another program to generate a command to be executed by fish.  But as the backslash thing, the fish command treat different input as identical.

**Comment by xltan** [comment]
Maybe I can introduce another simple example. When using vim:
`!echo -e '1\n2'` and `!echo -e '1\\n2'`
`!echo '1\n2'` and `!echo '1\\n2'`
both returns the same result.
The `1\n2` is generated by another program, so the original information is lost.

**Comment by krobelus** [comment]
Right, if there is an unknown escape sequence in quotes, fish will forward the backslash.

If you really want to generate fish commands in your program, then you need use fish quoting syntax (which may not match other shells).
The easiest way to do this is from within fish itself with `string escape` but this also works:

```python
def fish_quote(s: str) -> str:
	return "'" + s.replace(r'\', r'\\').replace("'", r"\'") + "'"

assert fish_quote("foo") == "'foo'"
assert fish_quote(r"'\") == r"'\'\\'"
```

Last time I checked using vim with fish as login shell was a bad idea (the fix is `set shell=/bin/sh`)

**Comment by xltan** [comment]
Hi, Thanks for all the help! For my special case, I was writing some plugin to send the command to fish shell to execute. I think if that is the intended behavior, I'll close this issue.
