### ISSUE TITLE
Unexpected bind behaviour

### ISSUE THREAD

**Issue by benkeil** [fish-shell/fish-shell#8927]
\fish, version 3.4.1
    xterm-256color

I try to bind a function with `bind \ce cddev`, but now, when I use `CMD` + `RIGHT ARROW` it also triggers my function. if I bind it to `w` instead, this does not happen.

**Comment by faho** [comment]
This is a macOS terminal setting that translates cmd key chords to the emacs equivalent.

Nothing to do with fish, in your terminal cmd+right arrow *is* ctrl+e.

**Comment by benkeil** [comment]
I use iTerm 2, can I change this?

**Comment by faho** [comment]
I don't have a mac so I don't know - [the iTerm docs](https://iterm2.com/documentation-preferences-profiles-keys.html) mention something about "Terminal.app compatibility" that might apply - you might want to turn that off.

**Comment by faho** [comment]
Question was answered, closing.
