### ISSUE TITLE
coreutils: timeout and fish functions

### ISSUE THREAD

**Issue by chapmanjacobd** [fish-shell/fish-shell#8932]
```fish
# fish, version 3.4.1
sh -c 'env HOME=$(mktemp -d) fish'
function t
  sleep 10s
end
timeout -k 9s 7s t 

timeout: failed to run command ‘t’: No such file or directory
```

GNU Parallel works _swimmingly_ with fish functions but I noticed some `coreutils` like `timeout` are not able to find them.

It only works if I do:

```fish
timeout -k 28m 26m fish -c "fishfunc""$somevar""another-arg"  

# although I have encountered some strange argument parsing issues when my $somevar contains `&` at the end. Maybe I'm not doing this correctly or maybe it is one of the fish features that I'm using--or maybe that is a red _herring_ stderr-nocaret qmark-noglob regex-easyesc ampersand-nobg-in-token
```

I would like to be able to write (it works like this when using GNU Parallel):

```fish
timeout -k 28m 26m fishfunc $somevar another-arg 

# mostly because I never have argument parsing issues when it is written this way but also because it looks cleaner
```

Alternative options:

maybe if this is not possible to fix I will just use GNU parallel because it also has a timeout option...

**Comment by faho** [comment]
This doesn't work just like eg. `env` and `sudo` with functions doesn't work. These things just execute external commands.


parallel makes it "work" by having some horrible horrible crimes in its code you don't want to know about.
