### ISSUE TITLE
Tab completion broken when using bat as pager for ssh/scp

### ISSUE THREAD

**Issue by sascha-andres** [fish-shell/fish-shell#8933]
It seems that when using bat (https://github.com/sharkdp/bat) as pager tab completion parameters for the pager might be wrong.

When typing `scp <tab>` or `ssh <tab>` an error is shown:

![image](https://user-images.githubusercontent.com/3052075/166867708-3986174b-3e4a-4174-83fd-257f145a205b.png)

After the blank line, the potential completions are displayed and selectable. When opening an issue (https://github.com/sharkdp/bat/issues/2180) for bat it was closed with pointing to problems with the tab completion. I have not changed tab completion setup but using the one shipped with fish 3.4.1

Is there any known fix?

**Comment by krobelus** [comment]
looks like you have ssh completions installed that still use the old ^/dev/null style which no longer works

you can probably find the ofending file with

    grep -FR '^/dev/null' $fish_complete_path

and remove it.

**Comment by sascha-andres** [comment]
The command returns nothing, so it does not seem to be the case :(

**Comment by krobelus** [comment]
look inside `$__fish_config_dir` as well or just your entire system

**Comment by sascha-andres** [comment]
@krobelus I had a custom `__fish_print_hostnames`. That was the culprit. Thanks for pointing me :)
