### ISSUE TITLE
v3.4.1 doesn't build on Illumos/OmniOS

### ISSUE THREAD

**Issue by jakubtalich** [fish-shell/fish-shell#8937]
Hello,

version 3.4.1 stopped successfully building itself (version 3.3.1 works just fine) on Illumos (OmniOS). See enclosed screenshot.

![image](https://user-images.githubusercontent.com/80840688/167122371-d05add0f-e2af-4a6c-b726-5f8e97ea8eba.jpeg)

**Comment by jakubtalich** [comment]
Thank you!

**Comment by faho** [comment]
I know what happened - 8c13f58 is a cherry-pick from master, only it was written to master after #8769 (as a sed-patch, mostly), which removes that function, and apparently the user who reported #8780 never tested it with 3.4.1 (and I tested the version in master).

So from our end, this is working in master. The patch for 3.4.1 is trivial - just turn that "tparm" call into "fish_tparm". I'm not sure if we'd make a new release for this - @zanchey is rather busy. Ideally the Illumos package would just add the patch.

**Comment by jakubtalich** [comment]
Confirming this neat fix works 🙌🏻
