### ISSUE TITLE
Confusing error when missing ELF interpreter

### ISSUE THREAD

**Issue by kngrektor** [fish-shell/fish-shell#8938]
Trying to execute a binary with a missing ELF interpreter (e.g. not having a `/lib64/ld-linux-x86-64.so.2`) gives this somewhat confusing error:
`exec: Failed to execute process './myapp': The file does not exist or could not be executed.`

An error like the existing one for scripts using shebangs would be super helpful.
`exec: Failed to execute process './myapp': The file specified the ELF interpreter '/lib64/ld-linux-x86-64.so.2', which is not an executable command`

For NixOS users like me mentioning something like nix-alien would have been awesome but I understand if this is out of scope.

**Comment by faho** [comment]
Yeah, sure. I went for a simple solution because extracting the linker from the ELF is awkward, and we don't want to be ELF parsers.

So instead we point you towards the "interpreter or linker" if the file is executable (after checking the shebang line failed).
