### ISSUE TITLE
[Question] How to asynchronously update fish title (after a delay)?

### ISSUE THREAD

**Issue by wzxu** [fish-shell/fish-shell#8956]
fish, version 3.4.1
iTerm 2 @ macOS Monterey

Just switched from zsh to fish and still warming up to it, but so far it feels pretty good!

I'm now trying to customize fish_title, but I found a tiny annoyance when I get the title to show running command.
Because fish updates the title immediately, so for most of the commands that finishes almost instantly, like ls or cd, it shows up for just a split second before disappearing again, resulting in the visual annoyance that the title seems to keep flashing between long and short text.

I'm wondering if it's possible to update the fish title immediately with just the working directory part, but only after a short delay (say 0.5s) if the command is still running, then update it again to show the running command part. Any hint?

Thank you.

**Comment by faho** [comment]
It is not.

In particular it's not possible to update the title *while the command is running*, because at that point that command is in the foreground and fish is waiting for it.

**Comment by wzxu** [comment]
I see. Any way to delay the update of title, and most importantly, don't update if the command already finished within the delay? If I add a `sleep` before `echo` in fish_title it only delays the update, but will update anyway even if the command already finishes, so it's even worse this way…

**Comment by faho** [comment]
>Any way to delay the update of title, and most importantly, don't update if the command already finished within the delay?

No, there is not, because the title needs to be set *before* the command starts. That's what I said above: We can't update the title while the command is running, we need to set it before. And before the command has run, there's no way to tell if it will finish quickly or not.

You can adjust fish_title to skip certain commands, but that won't really help in the general case. It's, in general, impossible to tell before a command has run how long it will take.

**Comment by wzxu** [comment]
> You can adjust fish_title to skip certain commands, but that won't really help in the general case. It's, in general, impossible to tell before a command has run how long it will take.

Gotcha. This is a good idea and a manageable workaround for me, though. Think I'll get by just skipping some most commonly used simple commands.

Thanks!
