### ISSUE TITLE
Fish does not respect XDG_DATA_HOME but uses default value on login

### ISSUE THREAD

**Issue by yochem** [fish-shell/fish-shell#8961]
fish, version 3.4.1
3.4.1

OS: Darwin air 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_6
Terminal: iTerm2 ($TERM=xterm-256color)

Fish creates `~/.local/share/fish` even though during startup (at least when reading user configuration) it knows that XDG_DATA_HOME is set to something different.

To reproduce:
1. Set XDG_DATA_HOME in `/etc/profile` to something non-standard, e.g. `export XDG_DATA_HOME=/Users/{your username}/Library/Data`
2. Put `echo $XDG_DATA_HOME` at first line of `~/.config/config.fish` file
3. Starting a new login shell (by just opening a terminal) prints the right path from step 1, but it also creates `~/.local/share/fish`

**Comment by faho** [comment]
Works for me.

Try `XDG_DATA_HOME=/tmp/foo fish`. Does that create /tmp/foo?

Also confirm:

1. XDG_DATA_HOME is actually set because it's inherited from the outside and not also set in config.fish
2. XDG_DATA_HOME isn't set as a universal variable (`set --show` would tell you)

**Comment by yochem** [comment]
> Try XDG_DATA_HOME=/tmp/foo fish. Does that create /tmp/foo?

yes it does.

> XDG_DATA_HOME is actually set because it's inherited from the outside and not also set in config.fish

I only had the `echo $XDG_DATA_HOME` in my config.fish

> XDG_DATA_HOME isn't set as a universal variable (set --show would tell you)

$XDG_DATA_HOME: set in universal scope, exported, with 1 elements
$XDG_DATA_HOME[1]: |/Users/yochem/Library/Share|

> Setting it in /etc/profile may not work, either - depending on how you have iTerm2 configured, if fish is started directly it doesn't source /etc/profile.

I also tried the launchagent approach but that doesn't seem to work either. Maybe I can set it in iTerm

**Comment by faho** [comment]
>$XDG_DATA_HOME: set in universal scope, exported, with 1 elements

Okay, run `set -eU XDG_DATA_HOME` and *then* reboot/repeat your tests.

**Comment by yochem** [comment]
I think I might have found the issue. My iTerm2 setting for the shell was set to the following:

![image](https://user-images.githubusercontent.com/23235841/168833482-553d22ec-6273-4ffc-b034-ed628cec4a14.png)

Changing it to login shell:

![image](https://user-images.githubusercontent.com/23235841/168833568-0566bc24-dd1c-4a32-87d2-e9e01805bf28.png)

It seems to work fine (i.e. fish does not create .local/share/fish)

**Comment by yochem** [comment]
Can confirm either changing the iterm setting or `set -eU XDG_DATA_HOME` did the trick. Thank you for your time and great help!

**Comment by faho** [comment]
Okay, so what's happening here is that your login shell isn't started before fish, so fish never inherits a value for $XDG_DATA_HOME.

Instead, it goes through the normal process for finding its config, finds the universal variable file, and then loads config.fish.

However, at that point it has set up (and created) the directories, so the value is received too late. Notably the universal variable file is in $XDG_CONFIG_HOME, so that can't work.

This is why the xdg variables have to be set from *outside fish*, like in a different login shell. Frankly, my personal advice is to simply not bother. Use the defaults, it's the path of least resistance.
