### ISSUE TITLE
fish says unknown command. But command works after starting fish from bash

### ISSUE THREAD

**Issue by hasanramp** [fish-shell/fish-shell#8962]
```fish --version```
fish, version 3.4.1

I recently install rust and cargo. When these programs were installed, the commands ```rustup``` and ```cargo``` were working. When I restarted my terminal, these commands didn't work. Then I started ```bash``` and from ```bash``` I started ```fish``` and the commands worked.

**Comment by faho** [comment]
What does `echo "$PATH"` say in both shell?

**Comment by hasanramp** [comment]
> 

thanks for replying.
```echo "$PATH"``` in ```bash```: ( "user" isn't literally user but the name of the home directory)
```/home/user/.local/bin:/home/user/.local/bin:/home/user/.cargo/bin:/home/user/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/snap/bin:/snap/bin:/snap/bin```
```echo "$PATH"``` in ```fish```:
```/usr/local/sbin /usr/local/bin /usr/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl```

```type cargo``` says: ```/home/user/.cargo/bin/cargo```

I tried running the command ```fish_add_path /home/user/.cargo/bin/cargo``` but the command failed.
