### ISSUE TITLE
Future Request: support unset environment variables with regex expression.

### ISSUE THREAD

**Issue by VergeDX** [fish-shell/fish-shell#8964]
In my `config.fish`, I always setting 6 variables about networking proxies:  
`all_proxy`, `ftp_proxy`, `https_proxy`, `http_proxy`, `no_proxy` and `rsync_proxy`.

But sometimes I need unset them to avoid using proxy, like running Steam download.  
So I think if there is a way to unset (`set -e` in fish) there variables, that's will be great!

For security concerns, we may also have a flag for "dry run".  
Which can tells the user which variables will be remove, but not actually.

**Comment by faho** [comment]
Just write it yourself:

```fish
for f in (set -n | string match -r '.*_proxy$')
    echo set -e $f
end
```

Remove the `echo` once you're happy.

**Comment by VergeDX** [comment]
Thanks! :joy:
