### ISSUE TITLE
Git completions appear to be missing --signoff for git commit

### ISSUE THREAD

**Issue by UbiquitousPhoton** [fish-shell/fish-shell#8965]
Please tell us which fish version you are using:

Fish 3.4.1

Please tell us which operating system and terminal you are using:

Manjaro Linux, Kitty terminal, 5.17.6

The Fish completions for `git commit` appear to be missing `--signoff` - this is present for other commands, but missing from this one. It would be relatively simple for me to make a PR for this, but not so simple to test it.

I tried without third party add-ons, but the issue is also pretty clear in the completions code.

Source: Someone who has to signoff every commit.

**Comment by krobelus** [comment]
> but not so simple to test it.

placing the modified git.fish in ~/.config/fish/completions/ should be enough.
Alternatively, if you built fish, you can just run that binary and it will pick up git.fish from your git worktree.

> Source: Someone who has to signoff every commit.

Looks like there is no Git config option to do that. but you can create a Git alias for `commit --signoff` or set the `commit.template` configuration variable.
