### ISSUE TITLE
New version of Fish Shell for Slackware 15.0 - Unraid is missing

### ISSUE THREAD

**Issue by masterwishx** [fish-shell/fish-shell#8970]
Im using Unraid 6.10.0 Linux x64 - Slackware 15
using fish-3.1.0-x86_64-1_slonly.txz by nerdPack Plugin but cant find new version for Slackware 15.

also having some error on new Unraid 6.10.0 

![image](https://user-images.githubusercontent.com/28630321/169692237-08388036-4b19-4f2c-b46d-27ab24ecd105.png)

**Comment by faho** [comment]
>but cant find new version for Slackware 15.

We don't support Slackware. Talk to Slackware people or build it yourself.

>also having some error on new Unraid 6.10.0

Fish 3.1.0 is missing over 25% of all commits ever made to fish. At that point doing any form of tech support is pointless because it's very very likely that the issue was already fixed in a newer version.

**Comment by masterwishx** [comment]
OK i got it , Thanks

**Comment by masterwishx** [comment]
compiled lasted version 3.4.1
https://github.com/masterwishx/Develop-Project/blob/main/fish-3.4.1-x86_64-1_da.txz
