### ISSUE TITLE
Ignore user remappings in edit_command_buffer for vim

### ISSUE THREAD

**Issue by DMartens** [fish-shell/fish-shell#8971]
The builtin function [edit_command_buffer](https://github.com/fish-shell/fish-shell/blob/ec6fd088f2c2f37dc1cfe596b1403a3430314395/share/functions/edit_command_buffer.fish#L47=) uses the `norm[al]` command for moving the cursor to a column.
The problem is that the user can remap `|` and as such the `normal!` (notice the `!`) command which ignores remappings should be used (see [vim help](http://vimdoc.sourceforge.net/htmldoc/various.html#:normal)).
I am willing to provide a Pull Request for this change.

Fish version: 3.4.1

**Comment by faho** [comment]
>I am willing to provide a Pull Request for this change.

That would be great.

To be honest next time just open the PR directly - we will merge obvious bug fixes and enhancements, and we don't have any issue quotas to fullfil, so we don't require issues to be filed. If you can just fix it then just fix it.
