### ISSUE TITLE
No TTY for interactive shell using '-e' option of VTE

### ISSUE THREAD

**Issue by tildebyte** [fish-shell/fish-shell#898]
Under latest cygwin/X/ports, fish compiled from git.
Everything works beautifully, including using fish as a primary shell (i.e. '-e fish') in [1]:
* xterm
* urxvt
* mintty

Using VTE-based terminals:
* gnome-terminal
* mate-terminal
* roxterm
* Terminal (xfce)

I get the following:

    fish: No TTY for interactive shell (tcgetpgrp failed)
    setpgid: Inappropriate ioctl for device

I realize that cygwin isn't supported [2], but I was hoping that maybe this is one of those "oh, right, that's obvious and easy to fix"...

[1] konsole wasn't tested as it won't run under cygwin
[2] I have poked around enough to surmise that cygwin supports tcgetpgrp in *some* fashion.

**Comment by faho** [comment]
Does this still occur with fish 2.2.0?

**Comment by tildebyte** [comment]
I haven't looked at this in a while, and I have no way to test it right now...

**Comment by faho** [comment]
No reproduction in >6 months. Closing.
