### ISSUE TITLE
Cursor won't change shape depending on vi mode when running inside tmux

### ISSUE THREAD

**Issue by AmdaUwU** [fish-shell/fish-shell#8981]
fish, version 3.4.0-62-g1763e7d3b
  tmux 3.2a

EndevourOS
alacritty 0.11.0-dev (7312f33f)

The cursor always remains a block, no matter the vi mode when running fish inside of tmux. 
I have tried running
```
sh -c 'env HOME=$(mktemp -d) fish'
fish_vi_key_bindings
set fish_cursor_default block
set fish_cursor_insert line
set fish_cursor_replace_one underscore
set fish_cursor_visual line
```
https://asciinema.org/a/EX9JCqHHpMbzbSCxed1BvnhGt

But no succes.

My tmux config is 

```
set -s escape-time 0

unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix
```
The issue dosen't seem to be on tmux's side since changing cusor shape works in neovim.

Thanks!

**Comment by faho** [comment]
Vi cursor shaping isn't automatically enabled in tmux because it's impossible to detect when it supports it (when the outer terminal does).

So, inside tmux, you'll have to set $fish_vi_force_cursor to indicate you know better.

Do something like

```fish
if status is-interactive
    if string match -q -- 'tmux*' $TERM
        set -g fish_vi_force_cursor 1
    end
end
```

in config.fish.

**Comment by yochem** [comment]
Hi, I got the exact same problem, but in tmux v3.3a. I thought it was a problem on their side, but received this as response from a tmux maintainer: https://github.com/tmux/tmux/issues/3226#issuecomment-1156562045 (and see [this comment](https://github.com/tmux/tmux/issues/3226#issuecomment-1156664351) for more explanation). I don't know much about escape sequences, but maybe this will be helpful?

P.S. the solution from @faho above did not work for me.

**Comment by faho** [comment]
Ah, lovely.

We *do* use the sequence they indicated to change the cursor, but we tell tmux to just pass it on. Apparently they disabled that and want to receive the sequence themselves. That's certainly possible.

However, unless tmux now interprets the sequence and determines if it is safe to hand it to the enclosing terminal, it's still not possible to actually enable the sequence by default in tmux (unless we detect the enclosing terminal, which in some cases, including alacritty, goes via $TERM, which tmux clobbers).

I've asked the tmux people for confirmation.

**Comment by faho** [comment]
The tmux people have confirmed we can pass on DECSCUSR (the xterm version) and don't have to do the passthrough dance anymore.

Reopening because we can now, in fact, handle tmux.

**Comment by faho** [comment]
@yochem What does `type fish_vi_cursor_handle` say?

Does executing `__fish_cursor_1337 block` and `__fish_cursor_1337 line` change the cursor shape?

**Comment by yochem** [comment]
```
$ type fish_vi_cursor_handle
fish_vi_cursor_handle is a function with definition
# Defined via `source`
function fish_vi_cursor_handle --on-variable fish_bind_mode --on-event fish_postexec --on-event fish_focus_in
              set -l varname fish_cursor_$fish_bind_mode
              if not set -q $varname
                set varname fish_cursor_unknown
              end
              __fish_cursor_1337 $$varname

end
$ __fish_cursor_1337 block
# cursor still a block
$ __fish_cursor_1337 line
# cursor still a block
```

**Comment by yochem** [comment]
The `__fish_cursor_1337` command also does not  seem to do anything outside of tmux. The cursor stays the  same.

**Comment by faho** [comment]
In that case, try `__fish_cursor_xterm` instead. It's possible iTerm changed the sequences they use.

**Comment by faho** [comment]
Also confirm that `__fish_cursor_1337 block | string escape` prints `\e\]1337\;CursorShape=0\cg` (without a newline, so you'll see a "⏎" in your terminal), and doing it with `1` says Shape=1 instead of 0.

`__fish_cursor_xterm block` should print `\e\[2\ q`, and a 6 instead of 2 for line.

**Comment by yochem** [comment]
>  In that case, try __fish_cursor_xterm instead. It's possible iTerm changed the sequences they use.

This works!

```
$ __fish_cursor_1337 block | string escape
\e\]1337\;CursorShape=0\cg⏎
$ __fish_cursor_1337 line | string escape
\e\]1337\;CursorShape=1\cg⏎
$ __fish_cursor_xterm block | string escape
\e\[2\ q⏎
$  __fish_cursor_xterm line | string escape
\e\[6\ q⏎
```
Yes it does!

**Comment by broander** [comment]
I too am having the same issue with the cursor not changing, but I'm not using iTERM (instead VSCode's terminal on one machine, remoting to TMUX; and on another Linux machine, remoting with TMUX).  The cursor doesn't work inside any of the TMUX instances, whether they be local, remote, or nested, but they used to as discussed above.  What's the latest and greatest guidance for a fix or workaround?

**Comment by broander** [comment]
Also I tried the escape commands that yochem listed, didn't seem to do anything useful regarding changing the cursor shapes.

**Comment by faho** [comment]
>Also I tried the escape commands that yochem listed, didn't seem to do anything useful regarding changing the cursor shapes.

If running `__fish_cursor_xterm block` (or line) doesn't change your cursor shape to a block/line, then your terminal doesn't support shape changing in any way we know.

>What's the latest and greatest guidance for a fix or workaround?

You need fish 3.5.1, and you can try setting $fish_vi_force_cursor to 1 to disable detection. But again, if printing the escape sequences (to be clear this is without the `| string escape` bit) doesn't work, we simply don't know how to work with your terminal.

And given that this sequence has been converging to the xterm one, I also kind of doubt that it's a different sequence at all, so it might simply not be supported entirely in your terminal.

**Comment by broander** [comment]
Thanks, that was exactly what I need.  I tried it again, the escape command you suggested did work so I was clearly doing it wrong yesterday.  So, I updated Fish to 3.5.1, and now it works!  Thank you very much=)
