### ISSUE TITLE
Fish crashing when trying to install a package with dnf + TAB

### ISSUE THREAD

**Issue by diegosparente** [fish-shell/fish-shell#8984]
**fish, version 3.4.1**

Hello guys!

I'm currently using fish on version 3.4.1 and Linux Fedora 36.
When running the command sudo dnf install + <TAB> my terminal crashes and I can't resume it. After pressing CTRL+C I can drop it. I tried through ZSH and was able to see the error more clearly. In the first video, the fish just stops and I can't continue. In the second video it asks to install sqlite3 according to the video recorded with ZSH. Could you give me a suggestion for this possible problem? Thank you very much!

First video:
[![asciicast](https://asciinema.org/a/gSCmphnw83gtpdMFP1Rgxo7wx.svg)](https://asciinema.org/a/gSCmphnw83gtpdMFP1Rgxo7wx)

Second video:
[![asciicast](https://asciinema.org/a/EkzmQcCR7UAdcc5eDrhdd3XHz.svg)](https://asciinema.org/a/EkzmQcCR7UAdcc5eDrhdd3XHz)

**Comment by faho** [comment]
This is weird. Your attempt to use zsh still produces *fish* errors, and it errors out about not finding sqlite3.

We do, in fact, use sqlite3 in our dnf completions - *but only if it is available*: https://github.com/fish-shell/fish-shell/blob/f45e16e59dc97892b1e89e24ec47df0fb38fc746/share/completions/dnf.fish#L20-L28

So, what I'd like to know:

1. Why is `zsh` running fish?
2. What does `type type` say?
3. What does `sha256sum (for f in $fish_complete_path/dnf.fish; test -e $f; and echo $f; and break; end)` say?

**Comment by diegosparente** [comment]
> This is weird. Your attempt to use zsh still produces _fish_ errors, and it errors out about not finding sqlite3.
> 
> We do, in fact, use sqlite3 in our dnf completions - _but only if it is available_:
> 
> https://github.com/fish-shell/fish-shell/blob/f45e16e59dc97892b1e89e24ec47df0fb38fc746/share/completions/dnf.fish#L20-L28
> 
> So, what I'd like to know:
> 
> 1. Why is `zsh` running fish?
> 2. What does `type type` say?
> 3. What does `sha256sum (for f in $fish_complete_path/dnf.fish; test -e $f; and echo $f; and break; end)` say?

Thanks for the help bro!

I don't know why zsh is using fish. I was also curious. I installed sqlite and it apparently solved the problem. It no longer hangs and the suggestion list appeared.

[![asciicast](https://asciinema.org/a/UYOkDMWlb0FS6JJXulhhxxXYQ.svg)](https://asciinema.org/a/UYOkDMWlb0FS6JJXulhhxxXYQ)

**Comment by faho** [comment]
>I installed sqlite and it apparently solved the problem

Yes, the problem seems to be that it tries to run sqlite3 and fails. I have no idea why that happens or why it would trigger a crash.

Please do give the sha256sum of /usr/share/fish/completions/dnf.fish - you seem to have missed that part.

Also the output of `type fish_command_not_found` would be good.

**Comment by diegosparente** [comment]
> > I installed sqlite and it apparently solved the problem
> 
> Yes, the problem seems to be that it tries to run sqlite3 and fails. I have no idea why that happens or why it would trigger a crash.
> 
> Please do give the sha256sum of /usr/share/fish/completions/dnf.fish - you seem to have missed that part.
> 
> Also the output of `type fish_command_not_found` would be good.

##

Sorry, I thought I recorded the output of sha256sum. If this is not the way out, please let me know.

[![asciicast](https://asciinema.org/a/VIuuuqW6zWUeQi0kPQMxYrqEb.svg)](https://asciinema.org/a/VIuuuqW6zWUeQi0kPQMxYrqEb)

**Comment by faho** [comment]
(sidenote: You don't have to record everything - for things like this just the string is enough)

Yeah, that's the correct, newest version.

At this point I'm honestly out of ideas, I'd have to recreate the issue myself but I don't use Fedora. 

@siteshwar You're on Fedora, right? Have you ever seen this?

**Comment by siteshwar** [comment]
> I'm currently using fish on version 3.4.1 and Linux Fedora 36. When running the command sudo dnf install + my terminal crashes and I can't resume it. After pressing CTRL+C I can drop it.

Is there a crash or fish is getting stuck? If `sqlite` is not installed, fish is running `dnf repoquery` (from [here](https://github.com/fish-shell/fish-shell/blob/7489ab9d5bcd7b256d53026a5ef0fd78def8278d/share/completions/dnf.fish#L27)) that may be getting stuck depending on the repositories configured on the system. 

> @siteshwar You're on Fedora, right? Have you ever seen this?

I have never seen this, but I am on older version of Fedora.

**Comment by faho** [comment]
Ah, okay, so it's probably not a crash at all.

@diegosparente Please remove sqlite3 again, trigger the tab completion and just wait a minute. I believe the completions are simply dog slow with the alternative path (and it might be worth it to remove it again).

**Comment by diegosparente** [comment]
> Ah, okay, so it's probably not a crash at all.
> 
> @diegosparente Please remove sqlite3 again, trigger the tab completion and just wait a minute. I believe the completions are simply dog slow with the alternative path (and it might be worth it to remove it again).

##

Thank you guys!

I removed sqlite and waited a few minutes. The behavior of leaving the terminal stuck has returned. Had to use CTRL + C. Do I reinstall sqlite?

**Comment by faho** [comment]
Okay.

Try running

```fish
dnf repoquery --cacheonly "*" --qf "%{NAME}" --available
```

I would assume that just hangs?

>Do I reinstall sqlite?

Installing sqlite is an effective workaround. It'll fix it *for you*, because it avoids running the hanging dnf command in the completions.

The question is, for us, if we keep the dnf command around at all.

**Comment by faho** [comment]
>Executing the command dnf repoquery --cacheonly "*" --qf "%{NAME}" --disponível 

That's not the same command. It's "--available" not "--disponivel". Please confirm you tried "--available".

Because this is the only command we run if sqlite3 isn't installed but not with (we do skip a few things, but running things can't really be faster than not running things), it makes very little sense that this would be fast.

But if it truly is, then the only other thing I can come up with is that it's somehow slow in the completion environment and not in a normal one.

This would be because:

1. either it can use sqlite3 if it's installed (so please also try without)
2. or the streams -stdin, stdout, stderr- are set up differently when running the completions and it doesn't like that

**Comment by diegosparente** [comment]
> > Executing the command dnf repoquery --cacheonly "*" --qf "%{NAME}" --disponível
> 
> That's not the same command. It's "--available" not "--disponivel". Please confirm you tried "--available".
> 
> Because this is the only command we run if sqlite3 isn't installed but not with (we do skip a few things, but running things can't really be faster than not running things), it makes very little sense that this would be fast.
> 
> But if it truly is, then the only other thing I can come up with is that it's somehow slow in the completion environment and not in a normal one.
> 
> This would be because:
> 
>     1. either it can use sqlite3 if it's installed (so please also try without)
> 
>     2. or the streams -stdin, stdout, stderr- are set up differently when running the completions and it doesn't like that

##

Sorry bro!

I typed it wrong, but the correct command is `dnf repoquery --cacheonly "*" --qf "%{NAME}" --available`.
The result was relatively fast, returning the installed packages.
I ran the command without sqlite3 installed.

**Comment by faho** [comment]
Did you run it as root or as your normal user?

What about

```fish
set -l packages (dnf repoquery --cacheonly "*" --qf "%{NAME}" --available)
```

?

**Comment by diegosparente** [comment]
> Did you run it as root or as your normal user?
> 
> What about
> 
> ```fish
> set -l packages (dnf repoquery --cacheonly "*" --qf "%{NAME}" --available)
> ```
> 
> ?

##

Thank you very much @faho!

>Did you run it as root or as your normal user?

I ran it as root and as a local user.

After I ran the command `set -l packages (dnf repoquery --cacheonly "*" --qf "%{NAME}" --available)`, a request appeared to confirm the AnyDesk GPG keys. I had to change AnyDesk's config in yum.repos.d for it to stop asking. I just found it strange that it didn't show up when I ran the command `dnf repoquery --cacheonly "*" --qf "%{NAME}" --available`.
Now it's working without sqlite needing to be installed. \o/

**Comment by faho** [comment]
>After I ran the command set -l packages (dnf repoquery --cacheonly "*" --qf "%{NAME}" --available), a request appeared to confirm the AnyDesk GPG keys. I had to change AnyDesk's config in yum.repos.d for it to stop asking. I just found it strange that it didn't show up when I ran the command dnf repoquery --cacheonly "*" --qf "%{NAME}" --available.

Ah, that explains it. The completions are hanging on the asking for a gpg key.

I'm willing to bet this goes away if we just connect stdin to /dev/null, so it'll just get end-of-file when it tries to read input.

Since it works for you now and it'll be awkward to confirm, I'll commit that and close this. If someone else gets the same problem we can reopen this.
