### ISSUE TITLE
Fish 3.4.1 fails to build on MacPorts

### ISSUE THREAD

**Issue by acjones8** [fish-shell/fish-shell#8988]
Hello! I tried to build fish 3.4.1, the most recent version currently available in MacPorts, on my PowerBook G4 running Sorbet Leopard (10.5.9, essentially 10.5.8), using GCC 7.5.0. I've attached the whole build log in case it helps, but I believe I've narrowed it down to this line right here that signifies the issue:

    /opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_shells_fish/fish/work/fish-3.4.1/src/fds.cpp:108:77: error: invalid conversion from 'const fd_set*' to 'fd_set*' [-fpermissive]
    bool fd_readable_set_t::test(int fd) const { return fd >= 0 && FD_ISSET(fd, &fdset_); }

I initially opened a bug report in the MacPorts tracker [here](https://trac.macports.org/ticket/65270), but was redirected here as the issue doesn't seem to be with MacPorts' infrastructure. If there's anything additional I can provide that would be helpful, please let me know!

**Comment by faho** [comment]
> PowerBook G4 running Sorbet Leopard (10.5.9, essentially 10.5.8)

We only support macOS 10.10 and up.

From the release notes:

> Mac OS X 10.9 is no longer supported. The minimum Mac version is now 10.10 "Yosemite."

Sorry.

**Comment by acjones8** [comment]
Oh my apologies, I should've checked that. Thank you!
