### ISSUE TITLE
missing aarch64 build for centos8

### ISSUE THREAD

**Issue by jhdxr** [fish-shell/fish-shell#8996]
I tried to install fish shell on Oracle Linux 8 with ARM chips and I got 

>package fish-3.4.1-1.1.x86_64 does not have a compatible architecture

error. 

I checked the [opensuse repo](https://download.opensuse.org/repositories/shells:/fish/CentOS_8/) and found centos8 is the only one that doesn't have aarch64 build. I'm wondering if there is anything blocking the build?

**Comment by zanchey** [comment]
I just use whatever the defaults are for the repository, which didn't include aarch64. I've added it now.

**Comment by jhdxr** [comment]
Thanks for the promopt reply. However I checked it just now and aarch64 is still unavilable. Maybe have to wait for next release?

**Comment by zanchey** [comment]
You might need to wait for the builds, it's still running in one of the repos

**Comment by jhdxr** [comment]
okk now it appears and I confirm I can install and run it. Thanks.
