### ISSUE TITLE
ip.fish The `ip address show` command does not get the list of NICs.

### ISSUE THREAD

**Issue by caoczy** [fish-shell/fish-shell#9008]
**YOUR TEXT HERE**
In the __fish_complete_ip function, the wrong end of line 300 and 321-324 causes the "case delete" to not be closed correctly, and the show/save/flush command does not get the device list correctly.

**Comment by faho** [comment]
I'm sorry, your lines appear to be from an older version of the ip completions.

Please check them against [the current version](https://github.com/fish-shell/fish-shell/blob/master/share/completions/ip.fish)

**Comment by caoczy** [comment]
Problem Description:
When entering the `ip address show` command, pressing `Tab` does not generate the NIC list correctly.
Possible cause:
The function __fish_complete_ip in the share/completions/ip.fish file,
end' on line 300 closes `switch $count` on line 282, and the block for `case delete` is not closed correctly.
This causes the `case show save flush` selection branch to not execute properly.

This problem still exists in versions ending with commit 0ea670366183723a96fcb18aa25d9766c3649b83.
