### ISSUE TITLE
Help setup installed python3 and using brew and run this version on Mac M1

### ISSUE THREAD

**Issue by ranrinc** [fish-shell/fish-shell#9009]
I'm on macbook pro M1 Max with the latest brew install and upgraded python version 3.9. Based on `which python3` keep on getting the original python version which is 3.8. How do I setup my fish to get the brew version and not the original python3 version?

`/opt/homebrew/opt/python/libexec/bin` the new path to python and the old path `/usr/bin/`

I have been trying to find out how to set this up correctly without any result. TIA

**Comment by faho** [comment]
Run

`fish_add_path /opt/homebrew/opt/python/libexec/bin`

either once interactively or stick it in ~/.config/fish/config.fish.

**Comment by ranrinc** [comment]
> Run
> 
> `fish_add_path /opt/homebrew/opt/python/libexec/bin`
> 
> either once interactively or stick it in ~/.config/fish/config.fish. See [the tutorial](https://fishshell.com/docs/current/tutorial.html#path).

Got it.. thanks
