### ISSUE TITLE
Document `status fish-path` (deleted)

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#9018]
`status fish-path` usually produces something like `/usr/bin/fish`. 

However, if you "updated" `/usr/bin/fish`, for example by `yay fish-git`, it will say `/usr/bin/fish (deleted)`.

I'm not sure what rules trigger this change though. `yay fish-git`, even when installing the same version will trigger the change, while `sudo touch (status fish-path)` did not trigger the change.

Could this be documented? Thanks ❤️

**Comment by faho** [comment]
For the case of the "(deleted)" suffix, we can just remove it.

I'm going to do that *if* the file "/path/to/fish (deleted)" doesn't exist.

**Comment by zanchey** [comment]
Will take this for 3.5.1.
