### ISSUE TITLE
fish 3.5 failing to start under tmux

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#9019]
[User "alexpw" reports on Hacker News](https://news.ycombinator.com/item?id=31769458):

> This killed all shell interaction within my tmux setup, somehow, and I had to downgrade in osx/brew [1] back to v3.4.1 [2]. I'm still wondering what part of my (probably outdated) tmux config caused it, but the most suspicious part is the run-shell/if-shell stuff.

They [shared their .tmux.conf](https://gist.github.com/alexpw/7d406734f912f835d705066de8286bda). This issue is to track investigating it.

**Comment by faho** [comment]
>however it includes a fair number of plugins which I don't have installed.

Note: I have tried to reproduce on linux, and while I couldn't test the reattach-to-user-namespace bit I *did* try the plugins.

It seemed to work for me, so I believe we need more information here. Specifically the fish configuration would be of interest.

**Comment by leondeng** [comment]
Yeah, @alexpw, `tmux kill-server` saved me, thanks!
