### ISSUE TITLE
Clear command not working. Terminals database is inaccessible.

### ISSUE THREAD

**Issue by juniovitorino** [fish-shell/fish-shell#9023]
**Version**: fish, version 3.5.0
**Operational System**: Darwin vitorinos-mbp.lan 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64
**Term**: tmux-256color

**How to reproduce**: Type in any terminal emulator the command `clear`
**Output**: `terminals database is inaccessible`

<img width="506" alt="Screen Shot 2022-06-17 at 17 27 12" src="https://user-images.githubusercontent.com/22594/174396805-7ef65d7f-584b-4047-af77-4a0257423ce5.png">

**Comment by faho** [comment]
The `clear` command isn't a fish thing. It's an external command, typically shipped with curses.

Check the values of $TERM, $TERMINFO and $TERMINFO_DIRS.

Alternatively, if you're using anaconda it's a known issue with that: https://github.com/ContinuumIO/anaconda-issues/issues/331.

**Comment by juniovitorino** [comment]
Yes, yes, thanks @faho, and my apologies for opening an unrelated question here.
I solved it by setting in my `.tmux.conf` the default `TERM`: ```set -g default-terminal xterm-kitty```
