### ISSUE TITLE
ctrl-c while config file is running results in wierd behaviur

### ISSUE THREAD

**Issue by altermo** [fish-shell/fish-shell#9024]
When running something like sh -c 'env HOME=$(mktemp -d) fish -C "sleep 1000"' and pressing ctrl-c while sleep is running then weird behavior happen: the colors does not show (in some terminals), welcome message does not printing instantly...
I have tied it with multible terminals (xterm,alacritty,xfce-terminal) and multible distros (pop-os,manjaro,arch).
I tested it in version 3.4 and in version 3.5.0-21-g181gc7f2b.

**Comment by ridiculousfish** [comment]
Thank you, good find.
