### ISSUE TITLE
completions: fixup wg-quick completions

### ISSUE THREAD

**Issue by ammgws** [fish-shell/fish-shell#9033]
Actually it looks like that works for non-root too, so we can just get rid of the kluge altogether:

```sh
>wg show
Unable to access interface mlvd-ch2: Operation not permitted
[1]>wg show interfaces
my_wg_interface
```

_Originally posted by @ammgws in https://github.com/fish-shell/fish-shell/pull/8687#discussion_r904522552_

**Comment by faho** [comment]
Duplicate of #8954
