### ISSUE TITLE
When launching from VS Code, fish interprets parts of file names as the vi escape sequence

### ISSUE THREAD

**Issue by adriandole** [fish-shell/fish-shell#9034]
Fish version: 3.4.1
VS Code version: 1.61.1
OS: macOS 12.4
Terminal: alacritty

Reproduction steps:
`config.fish` should be the following:
```
fish_vi_key_bindings
bind -M insert -m default df backward-char force-repaint
```

In VS Code, create a Python file named `pdf.py`, or any other file name containing your vi escape sequence, in this case `df`. Execute the file from VS Code with Run -> Start Debugging, selecting 'Python File' as the debug configuration.

Result: fish tries to launch `p` rather than `pdf.py`.

**Comment by faho** [comment]
It appears VS Code's debugging just sends keystrokes. So it pressed "df", fish did the thing it was supposed to do for "df".

I don't know why it would do it like that, but if that's what it does that's what it does, and there's no way for fish to detect that it's doing that.

**Comment by adriandole** [comment]
It's very common for vim users to rebind the escape sequence; I don't think this is unusual. For example, `df` is the default escape sequence in Spacemacs. #7401 is another user doing the same thing.

In programs that have a key mapping timeout (e.g. `KEYTIMEOUT` in zsh, and the feature mentioned in #7401) all you'd have to do is type `df` slightly slower to get the literal characters. It's not a common character sequence so it's worth the inconvenience in exchange for the convenient binding.

**Comment by adriandole** [comment]
Simple enough to disable only in VS Code.
```
if [ $TERM_PROGRAM != "vscode" ]
    bind -M insert -m default df backward-char force-repaint
end
```
I guess that'll do for now. 

Thanks for the fix suggestion, maybe VS Code will be willing to implement it.

**Comment by ridiculousfish** [comment]
Closing, there's nothing fish can do here. Thanks for filing.
