### ISSUE TITLE
Implement more informative error message when exec fails with ENOENT

### ISSUE THREAD

**Issue by ericonr** [fish-shell/fish-shell#9036]
This is an enhancement suggestion rather than a bug report. When a binary file's interpreter (as specified in the shebang or the dynamic linker) doesn't exist on that system, shells usually print the error message for `ENOENT`, since that's what `exec` returns. It is, however, not the most user friendly of messages, since the file trying to be executed does exist, and that might not be obvious at first.

Example of an error message:

```
exec: Failed to execute process './ls': The file does not exist or could not be executed.
```

For that reason, I'd propose some suggestions for better error messages here if we know the file exists but `exec` still failed (there is a slight risk of a race condition here between check time and exec time, but I think it's unlikely, and we could always check again for the file):

- print an error message that says the file's interpreter might be missing
- try to decode the file's shebang to print the specific missing interpreter
- try to decode the file's ELF header to print the specific missing interpreter

The latter one is more complicated, so I'd be okay with not using it (could potentially fallback to `readelf -l` on systems that have it, though), but the others seem like usability improvements. We could keep the original error message as well, to improve error searchability.

This is a suggestion, and I'd be glad to try my hand at implementing it, if there is interest.

**Comment by ridiculousfish** [comment]
I think fish already does this - see #8938

```
> echo '#!/bin/nocommand' > file
> chmod a+x ./file
> ./file
exec: Failed to execute process '/Users/peter/file': The file specified the interpreter '/bin/nocommand', which is not an executable command.
```

**Comment by faho** [comment]
>print an error message that says the file's interpreter might be missing

We already do this, see #8938.

>try to decode the file's shebang to print the specific missing interpreter

We already do this.

We also already give a message about windows line endings if the shebang line ends in `\r` and we get ENOENT.

>try to decode the file's ELF header to print the specific missing interpreter

We are not going to do this, it's much too complicated, specifically because we'd have to do this in the weird land between fork and exec.

Overall, it seems everything doable here is already handled, closing.

**Comment by ericonr** [comment]
Awesome, I somehow missed this development while looking through issues and forgot to build from master.

Thank you for the answer and sorry for the noise.
