### ISSUE TITLE
Feature Request: `bind --query`

### ISSUE THREAD

**Issue by halostatue** [fish-shell/fish-shell#9045]
I’m preparing a plugin similar to https://github.com/zshzoo/magic-enter based on some code I have in my current configuration, and I’ve run into a situation where my magic enter binding for `\r` is being overridden by a different plug-in ([atuin](https://github.com/ellie/atuin), in this case).

I’d like to cleanly detect whether there’s already a user binding, but there’s no `--query` mode, meaning that instead of doing something like:

```fish
if bind --query --user \r
  …
end
```

I have to do something like:

```fish
if bind --user \r >/dev/null 2>&1
 …
end
```

I will need the contents of the binding, but even there I need to suppress stderr:

```fish
set binding (bind --user \r 2>/dev/null)
```

Adding `-q/--query` to `bind` allows this test without allocating a variable during startup.

**Comment by faho** [comment]
`bind --silent` (or `-s`) silences a bunch of errors, including the one about not being bound.

It already returns a falsey status if nothing is bound, so:

```fish
if set binding (bind --user -s \r)
    # act on the binding, $binding is set
else
    # binding is unused
end
```

**Comment by halostatue** [comment]
That would work for my purposes. It’s worth noting that `--silent` is only documented at the *very top* of `bind --help` and not in the `OPTIONS` section.

**Comment by faho** [comment]
Ah, good catch.

**Comment by halostatue** [comment]
For my purposes `--silent` will do exactly what I want, so my issue is solved (I need the result of the query to operate on).

I’m not sure whether `--query` should be added for consistency and/or performance, so I will leave it up to you to close this if you think that it’s not a useful feature.

**Comment by faho** [comment]
Let's leave it at that for now
