### ISSUE TITLE
CentOS Stream 9 build on Open Build Service

### ISSUE THREAD

**Issue by antonc42** [fish-shell/fish-shell#9047]
Since CentOS Stream 9 has been officially released, can you please enable fish shell builds for that version on the [Open Build Service](https://build.opensuse.org/project/show/shells:fish:release:3)? Thanks for all the great work!

@zanchey

**Comment by zanchey** [comment]
It's not in OBS yet, unfortunately. I'll keep an eye open.

**Comment by faho** [comment]
They're now building, should be done soon.
