### ISSUE TITLE
history merge in private mode clears history

### ISSUE THREAD

**Issue by PatrickF1** [fish-shell/fish-shell#9050]
```
echo $version
3.5.0
```
Yes, I tested this without third-party customizations.

# How to repro
1. Spawn a new fish session in private mode: `sh -c 'env HOME=$(mktemp -d) fish --private'`
2. Run a few commands; doesn't matter what you type because even invalid commands make it into history
3. Check history using `history`
4. `history merge`
5. Check history again and notice it is now blank

Is this a bug or intended?

**Comment by faho** [comment]
Yeah, sure, I just made it error out - merging history in private mode is by definition wrong.

**Comment by PatrickF1** [comment]
Thanks! But where does it say that it's by definition wrong? It seems to me it should actually just proceed with incorporating history into the current session.

**Comment by faho** [comment]
Merging goes both ways. And I really really really don't want to add a secondary path that barely anybody uses that needs us to only do half of that.

**Comment by PatrickF1** [comment]
I didn't know merging goes both ways. Yeah I agree erroring is the right choice here, thanks!
