### ISSUE TITLE
git blame does not complete filename

### ISSUE THREAD

**Issue by drichardson** [fish-shell/fish-shell#9053]
## Environment

```
[I] doug@dougs-mbp ~/c/cpython (main)
λ fish --version
fish, version 3.5.0
[I] doug@dougs-mbp ~/c/cpython (main)
λ echo $version
3.5.0
[I] doug@dougs-mbp ~/c/cpython (main)
λ uname -a
Darwin dougs-mbp.lan 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64
```

## Have you tried without 3rd party customizations?
Yes. Problem still occurs.

## Repro Steps

1. `cd <SOME_GIT_REPO>`
2. `git blame <TAB>`

Does not try to complete filename.

https://asciinema.org/a/RTKTHlf7CneKGz9YrP2iCuAXI

**Comment by krobelus** [comment]
Terribly sorry - this was broken in 3.5.0 in ad9b4290e ("completions/git: cache subcommand computation"), fixed in latest master by fee5a9125.

a few other scenarios where affected too, we should consider a patch release @zanchey

**Comment by drichardson** [comment]
> fixed in latest master by [fee5a91](https://github.com/fish-shell/fish-shell/commit/fee5a9125a581598a7491ab83006247b62347041).

Confirmed fixed. I just built from HEAD and it works fine. Thanks1

**Comment by zanchey** [comment]
Fine by me, I've started a branch.

**Comment by krobelus** [comment]
Cherry-picked the fix to `Integration_3.5.1`
