### ISSUE TITLE
Inconsistent behavior between array literals and variables in "nested" array literal

### ISSUE THREAD

**Issue by luisrayas3** [fish-shell/fish-shell#9059]
Context:
```fish
$ fish --version
fish, version 3.3.1
$ echo $version
3.3.1
$ uname -a
Linux chefluis-thinky 5.4.0-109-generic #123~18.04.1-Ubuntu SMP Fri Apr 8 09:48:52 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
$ echo $TERM
xterm-256color
```

I'm not sure which is correct but I feel like the below should all produce the same thing:

```fish
$ echo {a,b,(for x in {1,2,3}; echo $x; end)}
a b 1 a b 2 a b 3

$ echo {a,b,{1,2,3}}
a b 1 2 3

$ set foo 1 2 3
$ echo {a,b,$foo}
a b 1 a b 2 a b 3
```

I couldn't find any documentation on the intended behavior of an array within `{}` but maybe I missed it? My preference would be all of them behaving the way `{a,b,{1,2,3}}` behaves but maybe there's a good intuition why the substitution versions work the way they do?

Example where this would be practically relevant:

```fish
$ echo {a,b,(some command that returns multiple things)}".extension"
a.extension b.extension sth1.extension sth2.extension
```

**Comment by ridiculousfish** [comment]
The [order of expansion](https://fishshell.com/docs/current/language.html?highlight=braces#combining-different-expansions) is command subs, then variables, then braces. Braces nested in other braces do not produce a cartesian product, probably to [match bash](https://unix.stackexchange.com/questions/402315/nested-brace-expansion-mystery-in-bash).

We're stuck with this decision, for better or for worse, so I'll close. If you're up for improving the docs here I'd be happy to merge a PR. Thanks.
