### ISSUE TITLE
OSX: It seems that Fish doesn't work with the OSX defaults utility for configuration

### ISSUE THREAD

**Issue by LiamKearn** [fish-shell/fish-shell#9076]
|||
| ------------- | ------------- |
| Version  | `fish, version 3.5.0`  |
| Uname  | `Darwin 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64`  |

It seems that the [OSX `defaults` application](https://ss64.com/osx/defaults.html) doesn't work in fish?

When I try run defaults in fish it just hangs. When I `chsh` back to zsh and run defaults it works as expected.

This is either an 1d1ot error on my part or `defaults` is pretty nasty!

Any help would be awesome.

**Comment by zanchey** [comment]
It works OK here - or at least running `defaults` does. Can you show the command line you are using?

**Comment by LiamKearn** [comment]
> It works OK here - or at least running `defaults` does. Can you show the command line you are using?

Yup just running:
```
defaults domains
```
or anything really.

Since posting I've confirmed its an 1d10t error on my part. Haven't solved it yet but I've confirmed it works in regular terminal but not alacritty.

Happy to close over here while I work it out :)

**Comment by LiamKearn** [comment]
Ah yeah found the 1d10t error on my part.

Had an alias for something which opened defaults... 😬
