### ISSUE TITLE
Broken esp-idf export

### ISSUE THREAD

**Issue by ipsavitsky** [fish-shell/fish-shell#9077]
fish version: 3.5.0
When I try to export an environment for [esp-idf ](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/get-started/index.html) fish returns the following error.
```bash
./esp-idf/export.sh (line 7): Unexpected ')' found, expecting '}'
        /*) scriptdir="${arg}";;
          ^
from sourcing file ./esp-idf/export.sh
.: Error while reading file “./esp-idf/export.sh”
```
The script can be found [here](https://github.com/espressif/esp-idf/blob/release/v4.1/export.sh)

https://asciinema.org/a/w7CDB2KtvcaehTKO8xgFiP75c

**Comment by faho** [comment]
Ah, I see the fish script was added in version 4.2. You need to upgrade your esp-idf.

**Comment by ipsavitsky** [comment]
that explains a lot, thank you
