### ISSUE TITLE
Allow return to accept the first candidate after complete-and-search

### ISSUE THREAD

**Issue by daanturo** [fish-shell/fish-shell#9080]
After executing `complete-and-search`, the first completion candidate appears to be selected, but the "return"/"enter" key can't accept them.

I have to move around and back like "right" and "left", then "return" can now replace the input with the candidate.

**Comment by faho** [comment]
Ah, okay.

So your issue is that triggering complete-and-search *immediately* doesn't leave the first candidate selected.

That can probably be changed.
