### ISSUE TITLE
Add additional hints to the message pertaining to universal variables being shadowed by global ones

### ISSUE THREAD

**Issue by psychoslave** [fish-shell/fish-shell#9084]
Currently when an universal variable is set with the same name as a global one a message like `set: Universal variable 'foo' is shadowed by the global variable of the same name` is provided. That’s already nice and informative, but I feel like some additional hints on common resolution pattern would be even better.

For example, adding `If you intend to keep only the universal variable exported, use 'set -e foo && use -Ux foo bar'`, or something like that.

# Related resources

- #5258
-  #4267

**Comment by faho** [comment]
We've been moving away from adding all commands everywhere. We don't actually know you want to remove the global variable, or that you want to use the universal variable in exported form, and we can't. 

You should read the documentation, which would also tell you that [exported universal variables aren't a good idea](https://fishshell.com/docs/current/faq.html#why-doesn-t-set-ux-exported-universal-variables-seem-to-work).

(also we would like to remove universal variables in their current form anyway)

So: Sorry, but no.

**Comment by psychoslave** [comment]
The answer seems good to me, thank you @faho.

All that said, maybe a "For more information, please consult `help faq`" might be fine.
