### ISSUE TITLE
use string with the fd or find program

### ISSUE THREAD

**Issue by evanescente-ondine** [fish-shell/fish-shell#9097]
How do I get string replace or other builtin commands to work with fd ?
I need to replace strings in lots of files but there is no "glob" function yet so to select which kinds of files I want to modify I need to pass string to fd or find.

**Comment by faho** [comment]
I'm assuming you're talking about `find`'s `-exec` option that executes a program, but it has to be an actual commmand - there is no "string" binary on your system, so calling `find . -exec string replace foo {}` won't find "string".

You *could* do something like

```fish
find . -name '*.fish' -exec fish -c 'string replace foo bar < {}' \;
```

This calls `fish -c` for every single file and then tells that to run `string` on it. This is extremely wasteful, especially if your fish startup is slow.

What you actually want is to read the filenames inside fish, and then act on them:

```fish
for file in (find . -name '*.fish')
    string replace foo bar <$file
end
```

or, to also handle files with newlines in the name:

```fish
for file in (find . -name '*.fish' -print0 | string split0)
```

**Comment by evanescente-ondine** [comment]
Good, good !
Thanks.
Let's say I want to modify the files, is there something more direct that:
```
for file in (fd . -e md -e scss -e html)
                         string replace no-float center < $file > $file'.temp'
                         trash-rm $file; mv $file'.temp' $file;
                     end
```
?

**Comment by faho** [comment]
No, that's basically it if you're using `string`.

Otherwise you can use `sed`, which has some options for actually operating on files, including commonly a `-i` or `--in-place` option that causes it to basically do that dance.

**Comment by faho** [comment]
Question was answered, closing.
