### ISSUE TITLE
Make standard functions easier to override

### ISSUE THREAD

**Issue by itaranto** [fish-shell/fish-shell#9101]
I would like to override the behavior of, let's say `ls`, but with the ability to use the *exact same command*, i.e. `ls`.

This could be achieved by modifying the `ls.fish` function to be like something this:

```fish
function __ls
    # Does the thing it was already doing...
end

function ls --description "List contents of directory"
    __ls $argv
end
```

So then I could do something like:

```fish
# ~/.config/fish/functions/ls.fish
function ls --wraps __ls
    __ls -v --group-directories-first $argv
end
```

But without having to copy the *whole* `ls.fish` file into my configuration.

The same could apply to all standard functions provided by `fish`.

**Comment by krobelus** [comment]
how about:

```fish
source $__fish_data_dir/ls.fish
functions --copy ls fish-ls
function ls
    fish-ls -v --group-directories-first $argv
end
```

**Comment by itaranto** [comment]
> ```fish
> source $__fish_data_dir/ls.fish
> functions --copy ls fish-ls
> function ls
>     fish-ls -v --group-directories-first $argv
> end
> ```

That makes a lot of sense, I didn't know `fish` had this feature.

I had to do a small correction: `source $__fish_data_dir/functionls.fish`, but it works great.

This will prevent me from having to maintain basically my own version of `ls.fish`, thanks.

I think this can be closed then.
