### ISSUE TITLE
set fish_function_path no longer appends automatically

### ISSUE THREAD

**Issue by drfiresign** [fish-shell/fish-shell#9108]
Fish version:

```
$ fish --version; echo $version
fish, version 3.5.1
3.5.1
```
Running `sh -c 'env HOME=$(mktemp -d) fish'` did fix my problem, but I thought I'd open an issue just to be sure.

I think there was some kind of change that affected how `set` works, perhaps isolated to the `fish_function_path` variable. In hindsight it seems obvious that this command would break things. But it hadn't done that before 3.5.1 so maybe something was actually fixed and it revealed my error, but in either case it's a change in past behavior and could help others who made the same mistake.

---

I have a work specific configuration file that I use to import some custom functions. I do this by altering the function path like this:

```
set fish_function_path $work_config/functions
```

This has been working without trouble for several months until I updated to 3.5.1. While processing my config, as soon as it hits that statement, it overrides the built in function paths and fish suddenly can't do anything it's supposed to do. This would manifest itself in an error every time I started a new session like this:

```
/usr/local/Cellar/fish/3.5.1/share/fish/config.fish (line 144): Unknown command: _fish_config_interactive
    __fish_config_interactive
    ^
in function '__fish_on_interactive'
in event handler: handler for generic event 'fish_prompt'
~
$
```

When this occurs, all my keybindings are broken. Not just mine, but almost _all_ the bindings. I can't scroll through command history and when I hit `Ctrl-E` it just calls the function `bind` printing my bindings to the terminal. Many built in functions are no longer bound when this occurs as well. When I type `__fish_` and press tab to autocomplete in a functional session I see `rows 1 to 67 of 160` indicating there are 160 functions with that prefix, but in a broken session there are only 8 bound functions which are listed.

To reproduce this you can override the `fish_function_path` to any directory without using the `set -a` flag. As I said before, this seems obvious in hindsight, but the previous behavior was that fish's built-in function path would still be present and therefore the shell would still be able to perform normal operational functions. I don't know if the bug was that `set` was always appending instead of overriding (not observed with other uses of `set`) or if there is supposed to be protection in place that preserves the built in paths for `fish_function_path` but which is now gone.

Cheers, Dylan

**Comment by faho** [comment]
>I think there was some kind of change that affected how set works, perhaps isolated to the fish_function_path variable.

Pretty sure there wasn't.

This is, quite simply put, the way this *should* work.

>the previous behavior was that fish's built-in function path would still be present

I have just tried this with 3.4.1 and that's not how that worked there either. 

I think you have misdiagnosed or misreduced the problem.

**Comment by drfiresign** [comment]
Definitely a possibility. Just trying to offer what information I thought I had in case anyone else had a similar experience. I spent about 6 hours trying figure this out and thought I got to the root of it. I mean I guess I did because its fixed now, but my analysis must be wrong. Thanks all the same.

**Comment by nnlq** [comment]
Maybe I met the same issue.
I wrote a small script to glob function folders and prepend it to `fish_function_path`.
```
#!/usr/bin/env fish
for f in $SYNC_FISH_DIR/*/functions
  set -Up fish_function_path $f
end
```
After execute just the last folder in loop was added.
**I tested it work when execute on terminal, but not when put to script**

I tried to seperate script inside to each folder.
for example: `hook.fish`
```
#!/usr/bin/env fish
set -Up fish_function_path $SYNC_FISH_DIR/xxx/functions
```
and glob
```
#!/usr/bin/env fish
for hook in $SYNC_FISH_DIR/*/hook.fish
  $hook
end
```
**this method worked.**
I don't know why

OS: macOS Montery 12.6.1
Terminal: kitty 0.26.5
Fish: version 3.5.1
