### ISSUE TITLE
Stop messing with locale environment variables

### ISSUE THREAD

**Issue by cunlem** [fish-shell/fish-shell#9113]
On my system when logging in on VT [__fish_set_locale](../blob/master/share/functions/__fish_set_locale.fish#L77) function (after some poking) sets `LC_CTYPE` environment variable to `en_US.utf8`. That's very unexpected plus `en_US.utf8` locale doesn't even exist on my system (why would it? I don't live in the USA).  Please consider getting rid of this unnecessary behavior. It's inconsistent with other shells, if the user wants to change his locale let him do so explicitly. It's perfectly fine to *not* have any locale variables set btw

Workaround on Debian system
```sh
dpkg-divert --rename /usr/share/fish/functions/__fish_set_locale.fish
echo 'function __fish_set_locale; end' > /usr/share/fish/functions/__fish_set_locale.fish
```

fish 3.5.0, Ubuntu 20.04

**Comment by faho** [comment]
Quite simply: No.

This is LC_CTYPE. It's the *encoding*. The only actual important part of that is the "utf-8" part. The "us" bit is simply because that's how locales work, we unfortunately need to give a locale.

This *improves* things because it *enables* utf-8 (which is a superset of ascii) to work. Without it, non-ascii characters are simply *broken*. It doesn't change your language or region or anything (for that it reads your system configuration, which the other shells also have).

It's also only used if you don't provide a locale at all.

So: No, this is a good feature and will stay.

**Comment by faho** [comment]
Also do note that your post comes across as rather rude, and I'm already tempted to lock this issue.

**Comment by cunlem** [comment]
> And if you don't have that locale, then nothing will happen and things will procede as if you had set LC_CTYPE to "C"

Of course setting nonexistent locale will cause errors:

```
> LC_CTYPE=en_US.utf8 perl --version
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LC_CTYPE = "en_US.utf8",
        LANG = (unset)
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").

This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux-gnu-thread-multi
(with 50 registered patches, see perl -V for more detail)

Copyright 1987-2019, Larry Wall
```
> The "us" bit is simply because that's how locales work, we unfortunately need to give a full locale name including country and language even if only the encoding is needed

Why not `C.UTF-8` which is guaranteed to exist on every system with Unicode support?

> It's really really really not, as long as the default is ascii-only.

No other shell does that and for good reason why try to fix something that is clearly out of scope

**Comment by faho** [comment]
> Why not C.UTF-8 which is guaranteed to exist on every system with Unicode support?

It is not. It's too new to rely on.

> No other shell does that

Other shells get the distros writing config files to set it up. We don't have that luxury.

Also fish is not other shells.

**Comment by cunlem** [comment]
> Other shells get the distros writing config files to set it up. We don't have that luxury.

No I don't see any system locale-specific configuration in Bash. Bash started from `login` has no locale vars on my system (system has no locale set). And yes leaving it up to the distro is the good approach.

> We try to fix things as best we can, because not having a locale set at all is typically a misconfiguration.

As you can see from above example the end result is misconfiguration

**Comment by faho** [comment]
Okay, we are going in circles now.

If you don't like the default, change it.

I'm locking this because there is nothing more to discuss.
