### ISSUE TITLE
Make Control-C insert a newline if the command line is empty

### ISSUE THREAD

**Issue by dradetsky** [fish-shell/fish-shell#9114]
NOTE: This isn't a strong recommendation/request; I'm still not 100% sure this is a good idea yet, just want to discuss

One habit I acquired from bash/zsh is that sometimes I'm partway through typing out a command and I decide I want to discard it, but I also want to clear several lines in the terminal before doing something else. In those shells, I can press `C-c` multiple times and the first one will discard the command line, and the subsequent ones will insert extra newlines. Or to put it another way, in bash/zsh `C-c` *always* discards the current command line and sends a new line to the terminal, even if the command line is empty. As a result, I also sometimes use `C-c` instead of `<Enter>` to scroll the terminal a bit, such as if my right hand is occupied with moving the mouse/eating/aiming a firearm/etc.

Earlier I tried to send `C-c` to fish with an empty command line:

Expected: A newline is inserted in the terminal.

Actual: Nothing happens. For a second I thought the shell had locked up due to CPU starvation or something.

Trying to discover if this was customizable, I quickly discovered that this was apparently a deliberate decision by someone: https://github.com/fish-shell/fish-shell/blob/master/src/reader.cpp#L3329

On the one hand, I consider this somewhat undesirable. First, it means fish works differently than bash/zsh and requires users to adjust, which it shouldn't do without an actual reason, since then it just raises the cost of switching for nothing. Second, it means I can't scroll the terminal with just my left hand. Third, it means that if I want to cancel a command line and then scroll the terminal a bit, I can't just hold down `C-c`, I have to enter one `C-c` and then switch over to `<Enter>`.

On the other hand, maybe there's some kind of good reason for this behavior that I don't understand but someone can explain (or better yet, write as a comment above the if-statement!). I've been wrong about stuff like this before. Or maybe there's a way to customize this that I'm not aware of (although if so a note on the subject in the docs wouldn't come amiss). For example, I did discover this:

https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_cancel_commandline.fish

But I can't tell if that's a way to customize that input function, or the pre-C++ implementation of it, or some kind of python-code-based performance art (really hoping for option 3 here). Either way, the docs should make clear if a way to customize input functions exists and point to some examples.

**Comment by faho** [comment]
I'm happy with how the current thing works, you can bind this yourself if you want.

>First, it means fish works differently than bash/zsh

Fish is neither bash nor zsh.

>But I can't tell if that's a way to customize that input function, or the pre-C++ implementation of it

It's option 2. It still exists to ease upgrading.

>Either way, the docs should make clear if a way to customize input functions exists and point to some examples.

Listing everything that *doesn't* exist in the docs is a recipe for disaster.

No, there are no ways to customize input functions. If you want anything else, you write your own binding.

**Comment by krobelus** [comment]
To customize you can add your own binding.

```fish
bind \cc my_cancel_commandline
```

```fish
function my_cancel_commandline
    if test -z "$(commandline)"
	echo -sn (set_color $fish_color_cancel) "^C" (set_color normal)
        commandline -f repaint
    else
        commandline -f cancel-commandline
    end
end
```

The important question remains: what should be the default behavior.

Actually, I like the old Ctrl-C behavior much better, so I use:

```fish
function my_cancel_commandline
    commandline ""
    emit fish_cancel
    # Repaint even if we haven't cancelled anything,
    # so the prompt refreshes and the terminal scrolls to it.
    commandline -f repaint
end
```

Can we make this the default again? We now have undo to recall a command that was cancelled accidentally.
Is there any use in leaving cancelled commands in the scrollback? I'd rather hide my mistakes.


---

> https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_cancel_commandline.fish

This is an unused compatibility wrapper that will be removed.

**Comment by faho** [comment]
>Actually, I like the old Ctrl-C behavior much better, so I use:

To be clear, the "old" ctrl-c behavior here is what fish did before, which is to clear the commandline on ctrl-c.

It never was the bash/zsh behavior of unconditionally abandoning the current line.

**Comment by dradetsky** [comment]
I want to apologize to everyone for reviving the "Default Ctrl-C behavior" debate. I honestly thought that the behavior on an empty line was genuinely orthogonal to what people where discussing in previous issues. I should have known better.

Overall I agree that the suggest approaches to fixing it myself are good enough.
