### ISSUE TITLE
When command line contains a BEL or ST escape sequence, subsequent characters are output to the terminal

### ISSUE THREAD

**Issue by page-down** [fish-shell/fish-shell#9116]
I noticed that when the command line contains a BEL or ST escape sequence, the command characters following ST are drawn to the screen (not stdout).
Also the terminal bell will ring.

```fish
echo -en '\e]2;set-title\e\\' && sleep 3

# displayed during sleep:
# ' && sleep 3
```

I also tried the following
```shell
bash -c "echo -en '\nthe line above should be empty\n\e]2;set-title\a' && true"
```
```text
' && true"
the line above should be empty
```

The problem does not exist in zsh, bash.
It also works fine when executed as a fish script file.
Is this working as expected?

fish compiled from master branch

**Comment by faho** [comment]
I can't reproduce, check your config.

**Comment by page-down** [comment]
Thank you.
I thought I had avoided loading custom configuration files, but apparently there are still environment variables.

For this issue, one should make sure that the special characters are escaped and encoded when outputting the command that has just been executed.
