### ISSUE TITLE
Fish shell showing wrong

### ISSUE THREAD

**Issue by arafat877** [fish-shell/fish-shell#9118]
**YOUR TEXT HERE**

Hi,

I have an issue with my fish shell on Windows and ubuntu (WSL), that shows a phone icon in the place of 'fi' letters (consecutive) as shown in the this screen shot 👍 

![image](https://user-images.githubusercontent.com/923282/183246893-ea673d9c-0e04-4b65-81e3-3500c783b180.png)

for Winfowd : 

fish -- version : 3.5.1
uname -a : Linux DESKTOP-MHV0M3S 4.4.0-19041-Microsoft #1237-Microsoft Sat Sep 11 14:32:00 PST 2021 x86_64 x86_64 x86_64 GNU/Linux
echo $TERM : xterm-256color

when I tape :  sh -c 'env HOME=$(mktemp -d) fish' under ubuntu (WSL) the problem persists.

regards

please

**Comment by arafat877** [comment]
Any help please ????

**Comment by faho** [comment]
This appears like you have chosen a font that has an "fi" ligature that looks like a font.

Fish has no influence over your terminal's font rendering, you're going to have to fix that. Most likely it's a matter of choosing a different font in the configuration.

**Comment by faho** [comment]
See https://github.com/ryanoasis/nerd-fonts/issues/254, this appears to be an issue with nerd-fonts.
