### ISSUE TITLE
Fish crashes when doing Ctrl + L after killing a specific process

### ISSUE THREAD

**Issue by qexat** [fish-shell/fish-shell#9122]
**Description**
After running a specific set of commands, pressing `Ctrl` + `L` crashes the console.

**Steps to reproduce**
1) Open `fish`
2) Type `python3` and press Enter
3) In Python REPL, type:
```py
>>> import os
>>> os.system("fish")
```
4) Now that you're in a new instance of `fish`, run:
```sh
ps | grep python
```
5) Copy the PID and run:
```sh
kill <PID> -s
```
> `-s` can be replaced by any invalid argument
6) Right after, press `Ctrl` + `L` to clear the console

**Expected behavior**
Clears the console.

**Current behavior**
Crashes `fish`.

**Configuration**
Fish: 3.5.1
OS: EndeavourOS Linux x86_64 5.18.15-arch1-1
`$TERM`: xterm-256color

**Note**
It seems that passing a specific signal to `kill` (5) prevents fish from crashing ; I only tried with `SIGSEGV`, though.

**Comment by qexat** [comment]
The crash seems to specifically happen when incorrect arguments are passed to `kill`

**Comment by faho** [comment]
Fish receives a SIGHUP, because you've killed the process in charge of the terminal.

This is to be expected, don't do this.

**Comment by qexat** [comment]
Maybe you cannot reproduce the bug, or there is something I don't understand from your comment?

I'm absolutely aware about `os.system`, and actually you could reproduce the bug by passing `"bash"` instead of `"fish"` as argument.
I reported the issue, because the original `fish` process crashes whereas I do not think it should be affected by a `kill` that concerns a subprocess of it (here, Python). Or am I getting this wrong?

I'm going to record a video of it, maybe it will clear the things up for me

**Comment by krobelus** [comment]
Right, if I have

bash -> python -> bash -> command kill $(pgrep python) -s

then the top-level bash doesn't crash. If I  replace it with fish, it does crash. We could find out what bash does differently here. Killing python here is definitely danger-territory though.

**Comment by qexat** [comment]
> Killing python here is definitely danger-territory though.
Of course. I'm just using it because that's the only way I know to cause this specific bug, but I think the bug might be caused by a consequence of killing Python with a "sub-fish", which may be reproducible in other circumstances.

**Comment by qexat** [comment]
https://user-images.githubusercontent.com/43090614/183289971-5ceddb4e-1dbb-45bd-9c29-11d2c4619f2d.mp4

I hope the quality is not too bad. I added subtitles to make things more clear about what I'm doing
My Python interpreter looks differently because I have my custom `.pythonrc`, but I shouldn't impact anything about fish here.

**Comment by faho** [comment]
Wait, the *outer* fish stops?

Yeah, that's not supposed to happen. Sorry, missed that

**Comment by qexat** [comment]
I found another way to reproduce:
1) Open your terminal that uses `fish` (let's name it fish1)
2) Type `fish` (let's name it fish2)
3) Type `fish` again (let's name it fish3)
4) Run:
```sh
ps | grep fish
```
5) Copy the PID of the second line (fish2), and run:
```sh
kill <copied PID> -s
```
6) Press `Ctrl` + `L`

Doing this makes fish1 crash. Hope this helps

**Comment by floam** [comment]
Can't seem to reproduce on macOS fwiw.

**Comment by mqudsi** [comment]
@qexat what does the `-s` in your `kill xxx -s` do? On my WSL install (`kill from procps-ng 3.3.12`) a trailing `-s` is invalid as it requires the name of the signal to send. When I execute your steps from the previous comment, I don't reproduce your issue.

Wait, it doesn't make fish1 crash immediately - but exiting fish3 makes fish1 then crash.

Ok, that was under WSL. On a Debian 10 vm, fish3 crashes immediately after `kill <fish2>` before I even get a chance to hit `^L`. Well, I say crashes but gdb says "exited normally". fish1 continues running normally (and resumes control of the terminal).

**Comment by qexat** [comment]
@mqudsi

> a trailing -s is invalid

Yes, it's exactly its purpose. It can be anything that is invalid, as long as the command still runs.
Otherwise, my fish1 would not crash.

Also, make sure to `Ctrl` + `L` if fish1 does not crash immediately.

**Comment by mqudsi** [comment]
With an invalid trailing `-s`, nothing crashes or exits (before or after `^L`).

**Comment by Hakimi0804** [comment]
Was just reading some random issues, and tried to reproduce this one. I cannot seem to reproduce it on termux, but it seems to be reproducible on fedora.

https://user-images.githubusercontent.com/67860246/207980416-ac7b8e68-97e9-4366-8c9b-2246235c08f4.mp4

**Comment by qexat** [comment]
Some update. Using fish 3.6.0, I cannot reproduce the issue. I suppose that it has been "accidentally" fixed as a side-effect of another thing.

**Comment by ridiculousfish** [comment]
Thank you, let's close then.
