### ISSUE TITLE
Introduce `$INTERACTIVE_EDITOR` to work around unresolved VSCode issue?

### ISSUE THREAD

**Issue by lgarron** [fish-shell/fish-shell#9127]
VSCode has had an issue for at least ≈4 years ([original issue](https://github.com/microsoft/vscode/issues/138712), [re-file](https://github.com/microsoft/vscode/issues/139634)) that causes a duplicate VSCode instance to open when `code` is invoked on macOS, which is visually distracting and slow. If someone (like me) does this dozens or hundreds of times a day, that can get really annoying. This is no clear workaround that works in all cases, and so far I've been unable to find a workaround that is:

- safe,
- "clearly correct" (i.e. avoids introducing edge cases), and
- compatible with `fish`'s "edit commandline in external editor" feature.

To be clear, **this is not a bug in `fish`, this bug is 100% due to VSCode**.

However, in my situation, it would be useful to have a workaround on the `fish` side. If `fish` supported a variable like `$INTERACTIVE_EDITOR` that took precedence over `$EDITOR` and `$VISUAL` for the "edit commandline in external editor" feature, then someone in my situation could:

- `set -x INTERACTIVE_EDITOR (which code)`, and
- use a workaround for `code` in other situations.

This would still be slow when invoking `$INTERACTIVE_EDITOR`, but it would least *work*, which would be really nice compared to the status quo.

I could imagine that this might be useful in other situations as well, but I can't really speak to that myself.

**Comment by lgarron** [comment]
Actually, please ignore this, it looks like `$VISUAL` takes precedence over `$EDITOR`!

I was testing so many configurations, I must have gotten that wrong. But this works for me now:

`set -x "VISUAL" (which code)" -w"`

**Comment by faho** [comment]
Sidenote: You don't want `which`. `which` is a cheesy non-standard command that can easily give false answers. On some systems it actually checks your bash aliases (because the original csh implementation did as well)!

You basically just want

```fish
set -gx VISUAL code -w
```

or, if you *have* to ignore functions, `set -gx VISUAL (command -s code) -w`.

(those quotes are pure superstition, there's nothing here that changes when quoted)

**Comment by zgracem** [comment]
@lgarron Here's how you can circumvent that VS Code bug entirely, at least for this use case:

```fish
set -gx VISUAL open -W -b com.microsoft.VSCode
```

**Comment by lgarron** [comment]
> @lgarron Here's how you can circumvent that VS Code bug entirely, at least for this use case:
> 
> ```fish
> set -gx VISUAL open -W -b com.microsoft.VSCode
> ```

Thanks, that also works well!
(It doesn't address the original VSCode slowdown bug, unfortunately, but it works at least as well as `(which code) "-w"`!)
