### ISSUE TITLE
Weird behavior with fish_prompt event

### ISSUE THREAD

**Issue by IlanCosman** [fish-shell/fish-shell#9128]
```fish
# In config.fish

function _tide_newline_before --on-event fish_prompt
    echo
end

function fish_prompt
    echo $PWD
end
```

displays

```
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish

/Users/ilantrue

/Users/ilantrue

/Users/ilan
```

---

Wheras

```fish
# In functions/fish_prompt.fish

function _tide_newline_before --on-event fish_prompt
    echo
end

function fish_prompt
    echo $PWD
end
```

displays

```
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
/Users/ilantrue

/Users/ilantrue

/Users/ilan
```

---

Is the lack of newline before the first prompt intended in this case? 

I guess what happens is that fish emits the event before loading the `fish_prompt.fish` file?

**Comment by faho** [comment]
The event is emitted before the prompt is displayed. That means it's also emitted before fish_prompt.fish is *loaded*, which means at that time the event handler simply isn't defined.

Tbh I don't recommend producing output from an event handler - we've never really defined the order in which they're executed, and there can always be multiple (I believe currently it's the order they are defined in).

**Comment by IlanCosman** [comment]
Fair enough, thanks for the quick response Fabian :)
