### ISSUE TITLE
printf -a results in `printf: -a: unknown option`

### ISSUE THREAD

**Issue by Aiz0** [fish-shell/fish-shell#9132]
sys info:
fish, version 3.5.1
Linux 5.18.16-arch1-1
Terminal: foot

Tested with `sh -c 'env HOME=$(mktemp -d) fish'` and by prepending them by `builtin`

executing `printf -a` results in the following error
```
printf: -a: unknown option

(Type 'help printf' for related documentation)
```

From the fish documentation about `printf`
_It doesn’t support any options, so there is no need for a `--` separator, which makes it easier to use for arbitrary input than `echo`_

executing `printf -- -a` works

typing `printf --` and pressing tab fish suggest `--help` and `--version` as options

executing `printf --help` results in the man page for `printf` being brought up.

`printf --version` does not work (unknown option)

I would expect printf to not take any options and print -a without issue.

**Comment by faho** [comment]
Broken in 9e08609f85, which misguidedly decided that printf's argument parsing must be normal (as a minor addition to a separate commit).

The workaround is easy: Just use `printf %s -a`. This is also recommended because the argument could accidentally include something that formats.
