### ISSUE TITLE
Prepending a backslash does not skip aliases

### ISSUE THREAD

**Issue by Nonie689** [fish-shell/fish-shell#9136]
fish --version

Linux archlinuxuser-ms7376 5.18.16-zen1-1-zen #1 ZEN SMP PREEMPT_DYNAMIC Wed, 03 Aug 2022 11:25:10 +0000 x86_64 GNU/Linux 
xterm-256color

When I am try to ignore a aliased definied execution pattern with: \echo or "echo" it still uses the alias profile!

Steps to reproduce:

1. Type: alias echo="echo bug_isnt_fixed"

2. Type: \echo
    and/or
    Type: "echo"

When the the text is displayed it doesn't ignore the alias, like in other shells!

So when the bug is fixed, it displays no text!

**Comment by faho** [comment]
Fish doesn't, in a real sense, *have* aliases. Aliases are simply functions.

So to ignore them, you wouldn't use `\foo`, you would use `command foo` or `builtin foo`.

And `\e` is the fish notation for an escape (`\x1b``) - this is also why the `\\` escaping wouldn't work.

**Comment by faho** [comment]
I'm sorry I don't understand what you mean.

These things are true:

Making an `echo` function is inadvisable. It will be used in a lot of places that `echo` is called, and might break what they expect. And if that function behaves exactly the same, why make it at all?

That `\` unaliasing syntax will not be supported. It's super obtuse to the point that I'm pretty sure it was never designed but fell out of the order that evaluation happened. If you want to make a good language, you should not include it. And it would be inconsistent with how backslashes currently work in fish. So it's a pretty bad idea all around.


Call your `echo` alias something else.

**Comment by Nonie689** [comment]
I mean

not echo [without the"], I mean "echo"... that's the alternative way to unalias commands....!

**Comment by faho** [comment]
That's as unintuitive as `\` skipping the alias. It is also not supported and it isn't something we are likely to add.

**Comment by Nonie689** [comment]
hmmm I am not really understand why the slash is also a problem, - cause it unaliasing only commands when it is at the first character.... or just at the first character in 
/echo $(/echo) .....

that's everytime the first character....  hmmm 

But back to the "echo"... I am said this just cause the most people are searching unalias linux shell and not unalias linuc fish shell.. so I believe you will get many times the same question...

**Comment by faho** [comment]
> so I believe you will get many times the same question

I can tell you that we don't. This isn't a very common question.

**Comment by Nonie689** [comment]
Hmm I have read that command is for function.. is that wrong??

**Comment by faho** [comment]
`command` is a thing that can do three things:

- `command foo` will execute an external command called `foo` - e.g. `/usr/bin/foo`, but not a function called `foo`
- `command -s foo` will tell you which `foo` a `command foo` would execute. e.g. it'll print `/usr/bin/foo`.
- `command -q foo` will return true if a `foo` command exists (useful for `if command -q foo`)

It is not, in any way,  "for function".

Bash also has something called `command`, and it's a bit more muddled. `command -v foo` will tell you if *any* `foo` exists (function, alias, command, builtin), but `command foo` will run the external command.

**Comment by Nonie689** [comment]
Nice to know...

this will make somethings easier....

I used which foo &> /dev/null  to see that foo exists... hmm so now I know the alternative recommendet way to write it in codes...
