### ISSUE TITLE
`$(...)` in completions evaluates inner `(...)`

### ISSUE THREAD

**Issue by exploide** [fish-shell/fish-shell#9149]
I'm running fish 3.5.0 and discovered an odd behavior where I'm not sure whether it is intended or not.

Let's consider the command substitution `$(echo 'bar (boom)')`.
The following just outputs the string `bar (boom)` as expected:

```console
$ echo "$(echo 'bar (boom)')"
bar (boom)

$ echo $(echo 'bar (boom)')
bar (boom)

$ echo (echo 'bar (boom)')
bar (boom)
```

Now let's do it in a completion script.

`complete -c foo -xa "(echo 'bar (boom)')"` leads to a correctly escaped argument for the commandline `foo bar\ \(boom\)`.

But using the `$(...)` syntax, it tries to do command substitution with `(boom)`.

`complete -c foo -xa "$(echo 'bar (boom)')"`

```
$ foo fish: Unknown command: boom
fish: 
boom
^
in command substitution
bar                       bar
```

I think this leads to unintended invocations of commands when the command to be called for generating the arguments outputs something with parenthesis.

**Comment by faho** [comment]
This is correct.

When the completion script is sourced, the `$()` is expanded because it is in double-quotes.

So, this ends up executing like

```fish
complete -c foo -xa "bar (boom)"
```

which obviously has a command substitution that it executes.

This is exactly what quoted command substitutions are *for*. If you don't want the `$()` to be expanded when the file is sourced, put it in single-quotes.

**Comment by exploide** [comment]
Makes sense. This is something where one needs to pay a little more attention... Especially because I realize that using the `$(...)` syntax, this would run the command once at file loading instead of when the actual completion is triggered. But often the latter is desired to produce meaningful results. So you are right, one would need to use single quotes then.
