### ISSUE TITLE
Natilus file manager not found when Fish is default shell?

### ISSUE THREAD

**Issue by aalong** [fish-shell/fish-shell#9153]
**Fish Version:** 3.3.1

**OS Version:** Ubuntu 22.04.1 LTS (Linux along-P37V5 5.15.0-46-generic #49-Ubuntu SMP Thu Aug 4 18:03:25 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux)

**Terminal Version:** xterm-256color

**Tested without extensions?** Unsure if able, as error seems to relate to current shell at time of system startup

**Nature of problem:** After setting my default shell with `chsh -s /usr/bin/fish` and restarting my computer, Ubuntu reports an error dialog stating "Nautilus file manager not found". In practice this prevents me from opening file system dialogs from my browser, and likely disables other file system dialogs that I have not yet run into. Restoring the default shell to Bash and restarting restores normal system behavior.

**Possible extenuating circumstances:** I recently completed a complete OS reinstall after a system failure while running Ubuntu 20LTS. I was able to preserve my home directory, as it was mounted to another partition, so it is possible that the preserved contents of my old `~/.fish/config` directory or other holdovers are to blame here

Based on the (utter lack of) relevant search results, I'm guessing that I've run across something extremely esoteric, so my apologies in advance if this proves to be partially or mostly unrelated to Fish. Thank you for your time and talent on this excellent shell.

**Comment by faho** [comment]
We don't open a nautilus, so I can only guess as to why it's not found. Possible causes include:

- $PATH not being set correctly (compare $PATH with bash as default shell to fish as default shell)
- $XDG_DATA_DIRS or $XDG_DATA_HOME not being set correctly, which is where things find .desktop files
- snap integration not being set up properly

Basically what you want is execute `env > fishenv` with fish as the default shell, `env > bashenv` with bash, and then `diff -u bashenv fishenv`.

This is very likely to be down to Ubuntu's integration, so you might want to open a bug with them.
