### ISSUE TITLE
`path` man page is not correctly formatted

### ISSUE THREAD

**Issue by kidonng** [fish-shell/fish-shell#9154]
Fish shell 3.5.1 from Homebrew.

Compared to `string` man page, `path` man page does not seem to be correctly formatted:

<table>
<tr>
    <td>
	<td><strong>string
	<td><strong>path
<tr>
<td>Source
<td>

https://github.com/fish-shell/fish-shell/blob/7e75118956e85c9d7def3dc23173113b72333d3c/doc_src/cmds/string.rst?plain=1#L6-L9

</td>
<td>

https://github.com/fish-shell/fish-shell/blob/7e75118956e85c9d7def3dc23173113b72333d3c/doc_src/cmds/path.rst?plain=1#L6-L9

</td>
<tr>
<td>Generated
<td>

```man
.TH "STRING" "1" "Jul 20, 2022" "3.5" "fish-shell"
.SH NAME
string \- manipulate strings
.SH SYNOPSIS
.nf
\fBstring\fP \fBcollect\fP [\fB\-a\fP | \fB\-\-allow\
-empty\fP] [\fB\-N\fP | \fB\-\-no\-trim\-newlines\fP] [\fISTRING\fP \&...]
```

</td>
<td>

```man
.TH "PATH" "1" "Jul 20, 2022" "3.5" "fish-shell"
.SH NAME
path \- manipulate and check paths
.SH SYNOPSIS
.INDENT 0.0
.INDENT 3.5
.sp
.nf
.ft C
path basename GENERAL_OPTIONS [PATH ...]
```

</td>
<tr>
<td>Rendered
<td><img width="559" alt="image" src="https://user-images.githubusercontent.com/44045911/186414224-8f52570b-a554-401f-9aea-ea2eab2206b3.png">
<td><img width="475" alt="image" src="https://user-images.githubusercontent.com/44045911/186414244-fe7ffe77-7c7c-4d9e-ae6e-92c0a28f8e0f.png">
</table>

**Comment by floam** [comment]
You are correct.
