### ISSUE TITLE
`fish --debug-stack-frames` is not documented in the man page

### ISSUE THREAD

**Issue by kidonng** [fish-shell/fish-shell#9155]
Fish 3.5.1 from Homebrew.

`--debug-stack-frames` is present in `fish`'s completions:

https://github.com/fish-shell/fish-shell/blob/7e75118956e85c9d7def3dc23173113b72333d3c/share/completions/fish.fish#L13

But nowhere to be found in the man page. It probably doesn't make much sense, but worth documenting given `--debug` and `--debug-output` is already there.

**Comment by faho** [comment]
"--debug-stack-frames" no longer *exists*, really. The option does nothing, currently, so we can just remove it from the completions.
