### ISSUE TITLE
How to change valid path's color

### ISSUE THREAD

**Issue by lominoss-git** [fish-shell/fish-shell#9159]
Version: 3.5.1

OS: Arch Linux (I don't think the output of ```uname -r``` is relevant here)

I have the line ```set fish_color_valid_path green``` in my config.fish, but all it does is get rid of the underline, it doesn't change the color.

**Comment by faho** [comment]
Previously it only used the modifiers and threw away the actual color for $fish_color_valid_path, unless the underlying color variable was "normal" (or had no color).

Now it'll use the color for $fish_color_valid_path if that has one.

**Comment by lominoss-git** [comment]
Thank you so much my man
