### ISSUE TITLE
printf '\xFF' shows Unicode U+00FF

### ISSUE THREAD

**Issue by xfix** [fish-shell/fish-shell#916]
This happens both with my change in #915, and without it. The issue is that the buffer gets `FF`, but after `printf` ends, it outputs it as Unicode. Perhaps `printf` shouldn't use Unicode buffer, but binary buffer?

```
➜  ~ printf '\xFF' | xxd
0000000: c3bf                                     ..
```

(by the way, while bash does that properly, it has different bug)

```
glitchmr@tangerine ~ $ printf '\u0100\u00FF' | xxd
0000000: c480 ff                                  ...
```

(however, `printf` in `/usr/bin` is correct IMO)

```
➜  ~ /usr/bin/printf '\u0100\u00FF\xFF' | xxd
0000000: c480 c3bf ff                             .....
```

**Comment by faho** [comment]
I currently get "ff" for `printf '\xFF' for both the builtin and the command, so this seems to be fixed.

**Comment by X4** [comment]
I agree with @faho it's fixed for me too.

**Comment by ridiculousfish** [comment]
Woohoo
