### ISSUE TITLE
Using `history-token-search-backward` after selecting an item from the pager clobbers the selection

### ISSUE THREAD

**Issue by cstyles** [fish-shell/fish-shell#9160]
**Fish version:** fish, version 3.5.1-273-gec8a7d09c (latest master)
**OS:** macOS & Linux
**asciinema recording:**

<a href="https://asciinema.org/a/etvVOHKJtji72PnLx6jHJwJCO" target="_blank"><img src="https://asciinema.org/a/etvVOHKJtji72PnLx6jHJwJCO.svg" /></a>

In the above recording, I press enter to select `file1.txt` from the pager and then immediately press `ALT+.` to cycle through previous tokens in the history. I expect this to insert `ls` after `file1.txt` but instead `file1.txt` is replaced with `ls`.

I think the bug occurs because the completion from the pager is considered a "transient" edit but I don't know for sure. If I make other changes to the command line (e.g., pressing space) before pressing `ALT+.`, the bug doesn't occur.

**Comment by krobelus** [comment]
nice report thanks! It was indeed a transient edit that was not properly closed
