### ISSUE TITLE
(feat) Enable multiple separate histories

### ISSUE THREAD

**Issue by elgamala** [fish-shell/fish-shell#9166]
fish, version 3.2.2

I'm addict to fish with all of the power it brings to the user experience of using shell scripts for human beings. I work most of the time in multiple projects and I think it will be great if fish can support multiple history files i.e. the commands I have executed in ProjectA are kept in ProjectA scope and not overlapping with ProjectB commands. Choosing the profile can be done using three different ways:
1. Manual: user selects/switched the history profile whenever they start a fish terminal or at anytime, with one profile set as default.
2. Directory specific: each chat profile is linked to specific directory path patterns and gets activated when I do cd project-a for example.
3. Time schedule: i.e. from 8:00 AM to 5:00 PM use profileA, from 5:00 PM to 11:00 PM use profileB, over the weekends use profileC

In simple ways, just look at it as a python venv :) 

I appreciate your votes on the new feature suggestion and I'm happy to contribute and implement it, if you give it 👍🏻

**Comment by krobelus** [comment]
fish already supports history isolation: simply set the [`fish_history`](https://fishshell.com/docs/current/language.html?highlight=fish_history#envvar-fish_history) special variable

for directory-specific use case try [direnv](https://direnv.net/)

**Comment by elgamala** [comment]
Thanks a lot @krobelus, I wasn't aware of this feature. It works as a charm now! let me close the issue :)
