### ISSUE TITLE
t/T don't work when enable fish_vi_key_bindings

### ISSUE THREAD

**Issue by netherstar** [fish-shell/fish-shell#9168]
`
fish --version                                                                                                                                                         
fish, version 3.1.2
`

`Linux 5.10.0-17-amd64 #1 SMP Debian 5.10.136-1 (2022-08-13) x86_64 GNU/Linux`

t/T don't work when enable fish_vi_key_bindings
it is only jump to first character, after that press ; do nothing
and u (undo) is the same do nothing

**Comment by faho** [comment]
Please try again with an up-to-date fish, 3.1.2 is four releases out of date.

**Comment by netherstar** [comment]
I'm just tried 3.5.1, it is same

**Comment by faho** [comment]
Let's file that under #8189 - the vi-bindings are badly in need of some love, and with the state they are in it makes no sense to file a separate issue for every little niggle.
