### ISSUE TITLE
!! doesn't execute previous command

### ISSUE THREAD

**Issue by gitayam** [fish-shell/fish-shell#9169]
**Fish Version 3.3.1
When attempting to execute the previous command using `!!` fish does not recognize this. The main use case is running `sudo !!`

FISH prompts for sudo password but then does not execute the previous command

**

**Comment by floam** [comment]
History substitution is not a feature of fish, so `!!` is literally just two exclamation marks.

**Comment by floam** [comment]
Wanting to re-exec the previous command, but this time with `sudo` because oops, is a pretty common thing. I suggest an alias just for that, or you could use an abbreviate along the lines of `abbr s! 'echo sudo $history[1]\?; sudo $history[1]'`.

**Comment by faho** [comment]
Please see the documentation, this is an FAQ: https://fishshell.com/docs/current/faq.html#why-doesn-t-history-substitution-etc-work

**Comment by floam** [comment]
oh that's a much better suggestion. TIL.

**Comment by krobelus** [comment]
https://github.com/fish-shell/fish-shell/discussions/8854 is our plan to extend abbrevations. With that we can easily implement `!!`.
