### ISSUE TITLE
Unsigned/signed type comparisons

### ISSUE THREAD

**Issue by xfix** [fish-shell/fish-shell#917]
The codebase of fish throws many warnings about comparisons between `unsigned` and `signed` values. Having these is dangerous, because they may work or not, depending on platform.

```c
#include <stdio.h>
int main() {
    long a = -1;
    unsigned int b = 1;
    puts(a > b ? "32-bit" : "64-bit");
    return 0;
}
```

**Comment by faho** [comment]
I don't get any anymore, assuming this is fixed.

**Comment by krader1961** [comment]
I fixed a bunch of these with my initial lint cleanups earlier this year. We really need to focus more on making fish "lint clean". If for no other reason than it makes running lint against a new change much more useful if you don't have to deal with a lot of pre-existing lint warnings.
