### ISSUE TITLE
Single executable scripts

### ISSUE THREAD

**Issue by andreiborisov** [fish-shell/fish-shell#9170]
I would like to use fish shell to create simple portable scripts that work in all environments (with the correct dependencies), but mainly in development containers.

Unfortunately, fish is not installed by default in most cases.

It would be very handy if we could package scripts in a single executable bundled with fish shell itself. Is it technically feasible?

Maybe there is a way to achieve this in userland? Are binaries the same for a single architecture or are they different for different OSs?

**Comment by faho** [comment]
The best fix for this is to package fish as an appimage, see #6475 .

Closing as a dup of that.
