### ISSUE TITLE
reading PDF file with less in fish, displayed in binary instead of text

### ISSUE THREAD

**Issue by moisestohias** [fish-shell/fish-shell#9171]
fish --version # 3.5.1
OS: Ubuntu: 20.04 LTS
Terminal: Kitty & The default GNOME Terminal

sh -c 'env HOME=$(mktemp -d) fish'
"Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish"

When reading PDF files with less, I am used to bash behavior where it reads the content of the PDF file, rather than displaying the binary file, When switching to bash in the same terminal session, and reading the PDF file with less, it displays the content of the file like I expect switching back to fish, and reading the PDF document with less, it works just fine.

View behavior: https://mega.nz/file/oA4TEbpD#HheTIP1f19Cl9ca-RcMcc1wn1qIVbXXapTgkSBy6bTY

!Note: basically bash does this by using a tool xpdf-tools than piping the output to less,

**Comment by faho** [comment]
Your `less` in bash isn't less the pager program but probably some sort of function. That's very much not a default thing. See `type less`.

You need to port that to fish.

**Comment by mqudsi** [comment]
Just a quick mockup:

```
function less
    if type -q pdftotext && string match -iqr '.pdf$' $argv[1]
        pdftotext $argv[1] - | command less
    else
        command less $argv
    end
end
```

**Comment by moisestohias** [comment]
Thanks
