### ISSUE TITLE
Best practices for dotfiles repos

### ISSUE THREAD

**Issue by metov** [fish-shell/fish-shell#9176]
There's a decent amount of overlap between "people who care enough about shells to install fish" and "people who use a dotfiles repo".

In my experience, shells tend to be somewhat complex members of a dotfiles repo. Fish has the laudable goal of working well out of the box and minimizing the need for configuration, but if you use the shell often you will probably still want to customize/personalize quite a few things, and if you have a dotfiles repo you will probably want to put your shell config there.

With fish, it was not entirely obvious to me what exactly should be included in my dotfiles and what shouldn't. For example, at first I thought `fish_variables` should be tracked in the repo since that's where my variables show up, but it seems like it's wiser to put `fish_variables` in `.gitignore` and instead set the ones I want in `config.fish`. There were other basic things such as https://github.com/fish-shell/fish-shell/issues/9173.

I think the tutorial could have a section called `dotfiles` with advice for how to best integrate a fish config into a dotfiles repo. This would be very helpful for people who are coming from another shell *and* also have their old shell configured in their dotfiles already. The page can assume that readers are comfortable with tracking dotfiles generally. It can have a preface like "if you don't know what dotfiles are, ignore this section or read https://dotfiles.github.io/" to avoid confusing people who don't know about dotfiles repos.

It seems like the docs are [part of this repo](https://github.com/fish-shell/fish-shell/blob/master/doc_src/tutorial.rst), so I'm happy to provide a PR for such a page if there is interest. I'm not an expert on fish internals but I can get it started with some general points.

**Comment by faho** [comment]
Do whatever you want, whatever works for you.

Both keeping fish_variables and setting the variables generally work.

I'll be closing this because I don't think we need a separate document. Thank for the offer.

**Comment by metov** [comment]
Got it - my mistake. Thanks for the response!
