### ISSUE TITLE
bug with `string sub`: it cuts trailing `\n`

### ISSUE THREAD

**Issue by sshilovsky** [fish-shell/fish-shell#9182]
fish-3.5.1

### How to reproduce
```
$ sh -c 'env HOME=$(mktemp -d) fish'
> string escape "$(string sub -s 1 -l 2 a\nb)"
a
```

Expected output is:
```
a\n
```

**Comment by faho** [comment]
This isn't string sub, it's the command substitution.

This is the same as in bash.

**Comment by sshilovsky** [comment]
I'm not sure I understand. For contrast, this works:
```
> string escape "$(echo a\nb | cut -zc2)"
\n
```

**Comment by faho** [comment]
Command substitutions trim any trailing newlines.

With `cut -z`, you don't *have* a trailing newline, you have a trailing NUL-byte.

This output looks like

```
a\n\0
```

Only because NULs are the unix string terminator they can't be passed as arguments and disappear.
