### ISSUE TITLE
Link to chmod manual from umask docs

### ISSUE THREAD

**Issue by Jeroendevr** [fish-shell/fish-shell#9185]
On the docs website: 
https://fishshell.com/docs/current/cmds/umask.html?highlight=chmod
it looks there should be a link to some chmod manual page. It seems this has not been implemented. I am not proficient with RST or know the website where it should refer to. Just wandering if there should be a docs update. 

Docs is from the following file
https://github.com/fish-shell/fish-shell/blob/master/doc_src/cmds/umask.rst

**Comment by faho** [comment]
`chmod` is an external command. We don't implement it, and so there's no local html file we could link to. We also don't know *which* chmod you're running so we also can't link to for example https://linux.die.net/man/1/chmod - that's the GNU Coreutils version and wouldn't be correct on macOS, BSD, linux systems using busybox, etc. This is unix, and so there's about fifty slightly incompatible versions of every possible command.

Best we could do is explicitly tell you to run `man chmod`, but at that point I'm not sure it's all that helpful.
