### ISSUE TITLE
string replace/match, specific behavior wanted

### ISSUE THREAD

**Issue by evanescente-ondine** [fish-shell/fish-shell#9189]
Hi,
my question might be more tied to regular expressions than fish but since the behaviour of those are tied to specific engines, I may as well ask here.
I have a text, with terms between backsticks \`term\`
I want to replace all those backsticks by <q>term</q>, but I can't get it right.
I want : to use string replace (or I wouldn't ask here...) and have the same result as if searching through the whole text like a single line, so that a pair of two backsticks are replaced by the **corresponding** tag even when separated by one or several lines or paragraphs. Ideally each pair would be substituted one by one before the evalulation of the rest of the text would resume.
And I can't get that right, I'm just a beginner in regexp.
If it's not fish-specific, kick me out no worry ;-)

**Comment by faho** [comment]
So:

`string` fundamentally works on a line-by-line basis. That means this won't work:

>a pair of two backsticks are replaced by the corresponding tag even when separated by one or several lines or paragraphs

You could use `sed` and tell it to use a NUL separator instead:

```fish
sed -z 's/`\(.*\)`/\1/' file
```

This matches a backtick, *something* and then a backtick, and replaces it with just the part in-between (it's grouped with the `\(\)`).

You might want to see if the `.*` is *greedy* (i.e. matches as much as it can), so it'll only operate on the longest sequence between two backticks. You can work around this either by making it non-greedy with some marker or by ensuring that it can't match anything longer, e.g. by making it match "anything but a backtick":

```fish
sed -z 's/`\([^`]*\)`/\1/' file
```

However: Do you actually need *pairs* of backticks, or do you just want the backticks gone? You could also just `string replace -a '`' '"'` to replace all backticks.

**Comment by evanescente-ondine** [comment]
just removing would be simpler isn't it... But I need to replace things like
```
blablablabla `foreign term` blablabla
```
by
```
blablablabla <q>foreign term</q> blablabla
```
> string fundamentally works on a line-by-line basis. That means this won't work:

I'm sad I can't make use of fish, my favorite shell :sob:

**Comment by faho** [comment]
> blablablabla <q>foreign term</q> blablabla

That's one of those things that would be great in the original explanation.

Try this:

```fish
sed -z 's/`\([^`]*\)`/<q>\1</q>/g' file
```

**Comment by evanescente-ondine** [comment]
```
sed: -e expression n°1, character n°22: unknown option for « s »
```

**Comment by faho** [comment]
Ah, you have some other sed.

This is why the issue template asks for your operating system. Try using `\<` (and possibly `\>` as well).

**Comment by evanescente-ondine** [comment]
```sed -z 's/`\([^`]*\)`/\<q\>\1\</q\>/g' essai.md```
No difference except it complains about the character n°25 this time, or 24
if I only escape the <.
sed (GNU sed) 4.8
OS: EndeavourOS x86_64
Kernel: 5.19.6-arch1-1
Shell: fish 3.5.1
Terminal: foot
Locale: fr_FR.UTF-8

**Comment by faho** [comment]
Same sed I have, so the original should have worked.

Just copy and paste this one:

```fish
sed -z 's_`\([^`]*\)`_<q>\1</q>_g' essai.md
```

**Comment by evanescente-ondine** [comment]
AAAAHHH !
Thanks, it worked. I don't know what was wrong the first time. It worked as
I hoped.
You're great.
