### ISSUE TITLE
Undocumented Gnome dependencies

### ISSUE THREAD

**Issue by jlturriff** [fish-shell/fish-shell#9193]
`leslie@pinto ~> fish --version`
`fish, version 3.5.1`
` `
`leslie@pinto ~> uname -a`
`Linux pinto 5.14.21-150400.24.18-default #1 SMP PREEMPT_DYNAMIC Thu Aug 4 14:17:48 UTC 2022 (e9f7bfc) x86_64 x86_64 x86_64 GNU/Linux`
` `
`leslie@pinto ~> cat /etc/SUSE-brand`
`openSUSE`
`VERSION = 15.4`
` `
`leslie@pinto /h/leslie [1]> cat /usr/local/etc/SystemID-Desktop.txt`
`Desktop Environment: Trinity`
`Qt: 3.5.0`
`TDE: R14.0.12`
`tde-config: 1.0`
` `
`leslie@pinto /h/leslie> echo $TERM`
`xterm`
` `
`leslie@pinto ~> sh -c 'env HOME=$(mktemp -d) fish'`
`Welcome to fish, the friendly interactive shell`
`Type help for instructions on how to use fish`

I installed fish using the [link on the fish home page to the package repository  for openSUSE Leap 15.4,](https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A3&package=fish) which succeeded, but many of the fish commands fail with the message
`Gtk-Message: _hh:mm:ss:ddd_: Failed to load module "canberra-gtk-
module"`
` `
e.g.
`leslie@pinto /h/leslie> help`
`Gtk-Message: _hh:mm:ss:ddd_: Failed to load module "canberra-gtk-module"`
`No protocol specified`
`No protocol specified`
`Error: cannot open display: :1`
` `
or
` `
`leslie@pinto ~> fish_config`
`Web config started at file:///tmp/web_config1jjlpzf7.html`
`If that doesn't work, try opening http://localhost:8000/c0c2ea97c8ad7b344f79fc2c1a7a96a9/`
`Hit ENTER to stop.`
`Gtk-Message: _hh:mm:ss:ddd_: Failed to load module "canberra-gtk-module"`
`$ set -L`
` `
`Shutting down.`

So apparently, fish depends on all or part of Gnome for its functionality, but the dependencies section of the file README.rst does not mention any Gnome components.  Even after installing the offending Gnome component, the problem persists:
`leslie@pinto /h/leslie> zypper se -i canberra`
`Loading repository data...`
`Reading installed packages...`
` `
`S  | Name                          | Summary                                                       | Type`
`---+-------------------------------+---------------------------------------------------------------+-------`-`

`i  | libcanberra-gtk-module-common | Portable sound event library -- Common Files for GTK+ Modules | package`

`i  | libcanberra-gtk0              | Portable sound event library -- GTK+ 2 Library                | package`

`i+ | libcanberra-gtk2-module       | Portable sound event library -- GTK+ 2 Module                 | package`

`i  | libcanberra-gtk3-0            | Portable sound event library -- GTK+ 3 Library                | package`

`i  | libcanberra0                  | Portable sound event library                                  | package`

I can't quite see why fish needs any sound packages; surely the \ca provided by the terminal suffices?  Unless some of fish's tools use any of Gnome's GUI tools? If so, there should be a list of Gnome component dependencies in README.rst; everyone doesn't use the Gnome desktop environment.

**Comment by faho** [comment]
It doesn't, it's starting a browser.

As the README explains.

**Comment by faho** [comment]
Also:

The canberra messages aren't your issue. They're noisy and annoying, but that's not why the browser *fails*. It fails because:

> Error: cannot open display: :1

Your X-server is misconfigured and you need to fix it. I don't think there's much we can do there to help.

**Comment by jlturriff** [comment]
This is very strange; no other application on my machine is trying to use display :1.  I have gotten around the issue by pointing $BROWSER to links, which seems to have gotten around the issue.

Thanks for your help.

**Comment by jlturriff** [comment]
On 2022-09-09 01:04:32 Fabian Boehm wrote:
> Also:
>
> The canberra messages aren't your issue. They're noisy and annoying, but that's not why
the browser *fails*. It fails because:
> > Error: cannot open display: :1
>
> Your X-server is misconfigured and you need to fix it. I don't think
> there's much we can do there to help.


	Ah, okay; I'll see what I can do about X.  Assuming I get that fixed, if I remove
canberra, I'll just get complaints from fish, but it will continue?

Leslie
--
Operating System:	Linux
Distribution:		openSUSE Leap 15.4 x86_64
Desktop Environment:	Trinity

**Comment by faho** [comment]
>Assuming I get that fixed, if I remove canberra, I'll just get complaints from fish, but it will continue?

You don't get complaints from fish. The complaints come from your browser.

You'll have to check with that for what canberra is needed, but typically that's not a fatal error and it would continue, yes.
