### ISSUE TITLE
Partial completion

### ISSUE THREAD

**Issue by mlopes** [fish-shell/fish-shell#920]
Hi, 

I would like to suggest the following enhancement to the auto-completion process.
When there's a multi word completion suggestion, based on history, frequently one needs part of the command and more often than not, the end part needs to be replaced.

My suggestion consists in adding an extra auto-complete shortcut that only completes until the next white space:

Ex:

when typing "l" I get the following suggestion:

ls -lha /var/www

pressing the new shortcut key would produce "ls" and keep the remainder as a suggestion, pressing it again wound produce "ls -lha" and keep the remainder as a suggestion.

Cheers,
Marco Lopes

**Comment by Kevin-Mok** [comment]
`Alt` doesn't work for me with my i3 config, and I can't seem to find the function name for this to rebind. Could someone let me know the name of it?
