### ISSUE TITLE
__fish_complete_subcommand doesn't work when being prefixed

### ISSUE THREAD

**Issue by FollieHiyuki** [fish-shell/fish-shell#9202]
```fish
fish --version
fish, version 3.5.1
```

I'm trying to use `__fish_complete_subcommand` to create a custom completion list (by adding a prefix on each entry).

The function is like this:
```fish
# Prefix each command with a string "ab"
function __fish_complete_subcommand_ab_prefix
    __fish_complete_subcommand | awk -F'\t' '{print "ab"$1"\t"$2}'
end

complete -c cmd -x -a "(__fish_complete_subcommand_ab_prefix)"
```

When I types `cmd <TAB>` completion menu shows all the expected results, but with `cmd ab<TAB>` the completion menu contains only commands having "ab" substring.

Side note: a static completion list like thisp works:
```fish
printf "haveab\t1st\nnothaveit\t2nd\ndcab\t3rd" | awk -F'\t' '{print "ab"$1"\t"$2}'
```

**Comment by faho** [comment]
This is as expected. When it's prefixed, that's no longer the command.

You're going about this the wrong way. What you are completing isn't a "subcommand" in the way that fish talks about subcommands.

**Comment by FollieHiyuki** [comment]
Thanks. That explains why my custom list works but `__fish_complete_command` and `__fish_complete_subcommand` don't.

> If you know the prefix, you can remove it and run `complete --do-complete="command to complete"` yourself.

I've never used `--do-complete` before. Can you make it more clear in this case?

And since `__fish_complete_subcommand` doesn't intend to work here, is there some builtin way for me to get the list of available commands in the system (or I'll have to loop through PATH and do a `ls`)?

**Comment by faho** [comment]
>I've never used --do-complete before. Can you make it more clear in this case?

`complete --do-complete` (or `-C`) tells `complete` to give you the completions for the given commandline.

So if you want to, in a script, get what `git add <TAB>` would give you, you run `complete --do-complete="git add "`.

This is also what `__fish_complete_subcommand` does internally, after skipping however many tokens you tell it to.

**Comment by FollieHiyuki** [comment]
I replaced the function with:
```fish
function __fish_complete_subcommand_ab_prefix
    complete -C 'exec ' | awk -F'\t' '{print "ab"$1"\t"$2}'
end
```
and it seems to work now.

Thanks for answering. Closing the issue now.
