### ISSUE TITLE
$0 expanded to full path

### ISSUE THREAD

**Issue by prk3** [fish-shell/fish-shell#9210]
Config:
Fish version 3.5.0, no plugins
OS: Fedora 35
Terminal emulator: alacritty 0.10.1

I have a script `test.sh` with the following content:

```bash
#!/bin/bash
echo $0
```

When I run it in bash shell, it prints relative path to the script:

```bash
> ./test.sh
./test.sh
>
```

When I run it in fish shell, it prints full path to the script:

```bash
> ./test.sh
/home/prk3/test.sh
>
```

This breaks my scripts in which I used $0 to construct paths. Is this intended behavior? I am pretty sure older versions of fish did not expand $0.

**Comment by faho** [comment]
>This breaks my scripts in which I used $0 to construct paths.

Like I said in #9143: If your script relies on $0 in that way, it's already broken.

Your script can always started via whatever path leads to it. This includes relative (`./test.sh`, but also `foo/test.sh` and `../test.sh`) and absolute (`/usr/bin/test.sh` but also `/bin/test.sh` if /bin is a symlink). If you require it to be `./test.sh` your assumption is broken.

See https://mywiki.wooledge.org/BashFAQ/028.

Fish doesn't hand you a random path here, but simply the ordinary, canonical, absolute path.

That being said: This behavior is changed back in the upcoming fish 3.6.0.
