### ISSUE TITLE
[Bug] Cannot auto-cd to directory

### ISSUE THREAD

**Issue by Soromeister** [fish-shell/fish-shell#9216]
Cannot auto-cd to directory. I remember that this used to work previously at some point in time. Please see below picture:

<img width="681" alt="image" src="https://user-images.githubusercontent.com/45243695/190902220-465c1bd4-5e51-47d6-b1e9-ce0a7217cdf1.png">

I am trying to `cd` into my `~/Projects` directory by directly typing the name of the folder instead of using `cd Projects` and it doesn't work. Neither the official FISH documentation, nor the unofficial cookbook mention this feature, but I know this used to work before.

**Comment by IlanCosman** [comment]
You need to have a `/` at the end for fish to recognize it as a directory and not as a command. Just use tab completion.

**Comment by krobelus** [comment]
I think fish doesn't treat `Projects` as directory because that would make it harder to distinguish between command and directory (which is needed for completions).
You can start by typing `./` which makes fish complete directories

**Comment by Soromeister** [comment]
> You need to have a `/` at the end for fish to recognize it as a directory and not as a command. Just use tab completion.

That did the trick. Thank you!


> I think fish doesn't treat `Projects` as directory because that would make it harder to distinguish between command and directory (which is needed for completions). You can start by typing `./` which makes fish complete directories

Was not aware of this but it also works. Thank you!

Closing this as the issue was just in my mind and not the product.
