### ISSUE TITLE
UWP apps cannot be run

### ISSUE THREAD

**Issue by martin-eder-zeiss** [fish-shell/fish-shell#9228]
I am using Fish version 3.5.0 in a Cygwin environment and from there it is not possible to launch UWP apps.
For example, the result for `winget` looks like this:

```
fish: Unknown command. '/cygdrive/c/Users/user/AppData/Local/Microsoft/WindowsApps/winget' exists but is not an executable file.
```

However, the command works with bash, so I guess it's not related to Cygwin, but to Fish.

**Comment by martin-eder-zeiss** [comment]
```
❯ winget
fish: Unknown command. '/cygdrive/c/Users/user/AppData/Local/Microsoft/WindowsApps/winget' exists but is not an executable file.

❯ "/cygdrive/c/Users/user/AppData/Local/Microsoft/WindowsApps/winget"
fish: Unknown command. '/cygdrive/c/Users/user/AppData/Local/Microsoft/WindowsApps/winget' exists but is not an executable file.

❯ ll /cygdrive/c/Users/user/AppData/Local/Microsoft/WindowsApps/winget
lrwxrwxrwx 1 user Domain Users 109 Aug 23 08:54 /cygdrive/c/Users/user/AppData/Local/Microsoft/WindowsApps/winget -> '/cygdrive/c/Program Files/WindowsApps/Microsoft.DesktopAppInstaller_1.18.2091.0_x64__8wekyb3d8bbwe/winget.exe'*

❯ '/cygdrive/c/Program Files/WindowsApps/Microsoft.DesktopAppInstaller_1.18.2091.0_x64__8wekyb3d8bbwe/winget.exe'
fish: Unknown command. '/cygdrive/c/Program Files/WindowsApps/Microsoft.DesktopAppInstaller_1.18.2091.0_x64__8wekyb3d8bbwe/winget.exe' exists but is not an executable file.
```

It makes no difference whether you call the symlink or the binary directly (all work in bash).

Unfortunately, there is no newer version in Cygwin: https://cygwin.com/packages/summary/fish.html

**Comment by faho** [comment]
Okay. What does

```fish
set -l file '/cygdrive/c/Program Files/WindowsApps/Microsoft.DesktopAppInstaller_1.18.2091.0_x64__8wekyb3d8bbwe/winget.exe'
test -e $file && echo exists
test -x $file && echo executable
test -f $file && echo file
```

say?

**Comment by martin-eder-zeiss** [comment]
```
❯ set -l file '/cygdrive/c/Program Files/WindowsApps/Microsoft.DesktopAppInstaller_1.18.2091.0_x64__8wekyb3d8bbwe/winget.exe'
❯ test -e $file && echo exists
exists
❯ test -x $file && echo executable
❯ test -f $file && echo file
file

```

**Comment by faho** [comment]
Well, there's your problem.

This quite literally does `access("/path/to/thing", X_OK)`.

Cygwin appears to be broken here. I suggest you report it to them.

**Comment by mqudsi** [comment]
fwiw and for posterity, with WSL and under either of bash or fish, attempting to execute a UWP exe wrapper will not raise any errors but the app does not launch, though it can be launched with the same path under `cmd.exe`. 

You can work around this by using `open /mnt/c/Users/username/AppData/Local/Microsoft/WindowsApps/foo.exe` instead (WSL requires the `.exe` suffix; cygwin does not).

**Comment by martin-eder-zeiss** [comment]
@mqudsi This will open a new window, and that's not really what I want.
For now, I'll use a wrapper function that calls bash in between: `bash -c "winget $argv"`
