### ISSUE TITLE
Why Fish not allowed to bind Ctrl + backslash?

### ISSUE THREAD

**Issue by netherstar** [fish-shell/fish-shell#9234]
i tried to bind Ctrl + backslash but it doesn't work
bind \c\\\ "do somethings"
also using fish_key_read with ctrl + backslash show nothing.

**Comment by faho** [comment]
If `fish_key_reader` shows nothing, that means the terminal sends nothing, and so fish can't tell that you've pressed it.

This is a limitation we can't do anything about. See https://fishshell.com/docs/current/cmds/bind.html#terminal-limitations

**Comment by netherstar** [comment]
but i can map "Ctrl + \" in vim and it's work perfect.
I'm using Windows Terminal

**Comment by faho** [comment]
Okay, found it: It's typically bound in the terminal to sending the QUIT signal. It appears vim disables this, we can as well.

(one slight hiccup here is that `\c\` is an awkward escape to give to a `bind` command, so I'm gonna make it so `fish_key_reader` gives it to you in hex form - `\x1c`).
