### ISSUE TITLE
Document exit status of `type` builtin

### ISSUE THREAD

**Issue by niklasmohrin** [fish-shell/fish-shell#9252]
In my config, I have external programs that configure fish in some way:
```fish
zoxide init fish | source
```

I want to change this line so that it is only executed if `zoxide` is actually installed. An internet search yields [a stackoverflow answer](https://stackoverflow.com/a/42832284/13679671) suggesting to use `type -q zoxide` - and that seems to work. However, I noticed that this behavior is not precisely documented. In the help page for `type`, the `--query` argument is presented as "useful when testing the exit status", but the exit codes themselves are not documented along this statement. I think it might be worth it to at least mention an interpretation for zero and non-zero exit status.

---

```shell
$ fish --version
fish, version 3.0.2
```
... but it isn't documented on [the current main branch version](https://github.com/fish-shell/fish-shell/blob/ce451f67c55e2e73874bb5ad74c215b55a927153/doc_src/cmds/type.rst) either.

---

Thank you all for your work on fish, I am using it for a couple of years now!

**Comment by faho** [comment]
Sure, fixed.

>fish, version 3.0.2

Note: Compared to 3.5.1, that's 42% of all commits behind.

At this point it's ancient history.

**Comment by niklasmohrin** [comment]
Wow, that was quick, thank you!

> Note: Compared to 3.5.1, that's 42% of all commits behind.

Whoops :D. I wrote the issue on a secondary computer running debian 10 in a wsl, should probably update some time soon. My main setup uses the latest fish of course ;)
