### ISSUE TITLE
Restarting Terminal on OS X does not restore working directory

### ISSUE THREAD

**Issue by bjhomer** [fish-shell/fish-shell#926]
On OS X, turn on the setting to restore an application's windows when restarting the app. Make sure fish is your default shell. Then do the following:

 1. Open a new window in Terminal.app
 1. `cd ~/Documents`
 2. Cmd-Q
 3. Open Terminal.app
 4. Note that the working directory is `~`, not `~/Documents`

I'm running this built from `brew`, version 2.0.0.

**Comment by zanchey** [comment]
This is fixed in 2.2.0, hooray!
