### ISSUE TITLE
Sed operation working differently in Fish than Bash.

### ISSUE THREAD

**Issue by awalsh128** [fish-shell/fish-shell#9264]
I am using ``fish, version 3.5.1``

I am having trouble getting a `sed` command to work in Fish. It works correctly in Bash though. The use case is escaping a string literal to be used in a regex. I am using `sed` in this case.

```fish
set find_value "a/b.c/^"
set escaped_find (printf '%s\n' "$find_value" | sed -e 's/[]\/$*.^[]/\\&/g')
# Gives  a&b&c&& instead of  a\/b\.c\/\^
```

**Comment by faho** [comment]
Fish's quoting is different from bash's. In particular `\` still escapes in single-quotes, so `\\` becomes `\`.

You can see this difference with a simple `echo`:

```fish
> echo sed -e 's/[]\/$*.^[]/\\&/g'
sed -e s/[]\/$*.^[]/\&/g
```

bash:

```bash
>echo sed -e 's/[]\/$*.^[]/\\&/g'
sed -e s/[]\/$*.^[]/\\&/g
```

So what you want is:

```fish
printf '%s\n' "$find_value" | sed -e 's/[]\/$*.^[]/\\\&/g'
```

**Comment by awalsh128** [comment]
That makes sense, my mistake. Thanks for the quick response.
