### ISSUE TITLE
`argparse` behaviour different than documented (outdated docs or bug?)

### ISSUE THREAD

**Issue by giorgiga** [fish-shell/fish-shell#9265]
*I'm still on fish 3.5.0 (because fedora f36), so please double-check with latest version.*

The [documentation for `argparse`](https://fishshell.com/docs/current/cmds/argparse.html#example-option-specs) states:

>`h/help` means that both `-h` and `--help` are valid. The flag is a boolean and can be used more than once. If either flag is used then `_flag_h` and `_flag_help` will be set to the count of how many times either flag was seen.

Based on the that, one would expect that the script

```fish
set -e _flag_h
set -e _flag_help
argparse h/help --        && echo flag: (set -q _flag_help && echo $_flag_help || echo not set)
argparse h/help -- -h     && echo flag: (set -q _flag_help && echo $_flag_help || echo not set)
argparse h/help -- -h -h  && echo flag: (set -q _flag_help && echo $_flag_help || echo not set)
set -e _flag_h
set -e _flag_help
```
would output

```
flag: not set
flag: 1
flag: 2
```
when instead it outputs

```
flag: not set
flag: -h
flag: -h -h
```

**Comment by giorgiga** [comment]
Thanks @faho
 
The same issue seems to affect the bullets about `help` (the one following `h/help`) and `x` - could you fix those too?

I can do a PR now that I know it's just a documentation issue - let me know if you would prefer that instead of doing yourself.

**Comment by faho** [comment]
a99f5883284c9f6635b7c170ffdebb5ab95180c7 - I didn't want to repeat myself, so I just inserted "as above", which should be clear enough.
