### ISSUE TITLE
argparse o/--option=+ spec fails to aggregate when option value is a short option

### ISSUE THREAD

**Issue by 0ion9** [fish-shell/fish-shell#9267]
Compare the outputs of the following 7 commands:

```
argparse g/grep-args=+ -- -g-E -g-l && echo shortopt1 $_flag_grep_args
argparse g/grep-args=+ -- -g -E -g -l && echo shortopt2 $_flag_grep_args
argparse g/grep-args=+ -- -g -El -g -is && echo shortopt_multi $_flag_grep_args
argparse g/grep-args=+ -- -ge -gl && echo rmdash $_flag_grep_args
argparse g/grep-args=+ -- -g--E -g--l && echo longoptish $_flag_grep_args
argparse g/grep-args=+ -- -g--EEE -g--lll && echo longopt $_flag_grep_args
argparse g/grep-args=+ -- -g--EEE=foo -g--lll=bar && echo longopt_w_value $_flag_grep_args
```
In the cases shortopt1 + shortopt2, only the last value (`-l`) given is saved into `_flag_grep_args`. This is equivalent to treating the option spec as `g/grep-args=` (no +).

In all other cases parsing is as expected : the two values given are saved into `_flag_grep_args` in the order they were given.

Fish version : 3.5.1-430-gef844a63b
uname : Linux m92p 5.19.13-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 04 Oct 2022 14:36:58 +0000 x86_64 GNU/Linux
$TERM: xterm-256color  (sakura)

**Comment by faho** [comment]
Works for me. The first two cases give "shortopt1 -E -l" and "shortopt2 -E -l", respectively.

fish 85d4834b3565c519a0fb3c6182c370df1227fb84.

**Comment by 0ion9** [comment]
No, what it turned out to be is actually that my testcase didn't have the descriptive labels 'shortopt1' etc. This meant that `echo` interpreted the -E as an option rather than printing it.
I should be more careful with using echo rather than printf. Sorry for the noise.
