### ISSUE TITLE
$PATH on OS X again

### ISSUE THREAD

**Issue by ahti** [fish-shell/fish-shell#927]
So, fish does `/etc/paths` now, which is great. There is one thing that does not work that well though:

With system-bash, my path looks like this:

```
/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:
/opt/X11/bin:/usr/local/MacGPG2/bin:/usr/local/share/npm/bin:/usr/texbin
```

this is pretty much what i expected according to my `/etc/paths` and `/etc/paths.d/*`.

```
/usr/bin /bin /usr/sbin /sbin /usr/local/bin /usr/local/sbin
/opt/X11/bin /usr/local/MacGPG2/bin /usr/texbin /usr/local/share/npm/bin
```

The problem is, that fish does not reorder things that are in $PATH already when `/usr/local/share/fish/config.fish` is executed. I put a `echo $PATH` at the top of the file,  and it seems that this:

```
/usr/bin /bin /usr/sbin /sbin
```

is the path fish inherits from `launchd`.

I think that, if a `/etc/paths` file is found, fish should throw away the old path, and rebuild it completely from the files.

This would also mean moving the reconstruction of `fish_user_path` after the Mac OS X bit.

It also seems fish orders the files in `/etc/paths.d/` a bit differently than `path_helper`, but I don't think thats really an issue. The files I have in that directory are named as follows:

```
40-XQuartz
MacGPG2
TeX
npm 
```

**Comment by albertz** [comment]
Is this intended behavior? I find it quite confusing. E.g. when I'm in another shell (bash, ZSH, or whatever), or even any other tool, where there is already `$PATH` defined (which I have like I want it, on purpose, by setting it e.g. in `~/.bash_profile`, such that I e.g. have `~/.homebrew/bin` and `~/.local/bin` in the beginning of `$PATH`, which is what I want), and then I start `fish`, suddenly my `$PATH` is totally reordered (my own entries which I want to have at the front are not anymore there).

If this is intended behavior, could we have at least an option to disable this?

**Comment by faho** [comment]
@albertz: #5456.

**Comment by albertz** [comment]
@faho Thanks. But it doesn't answer my question: How to disable that? I don't want that Fish changes/reorders my `$PATH` (or maybe only add entries at the end).

**Comment by faho** [comment]
You don't. It's something we probably should change. But we shouldn't change it by introducing some weird option, but by making the default better.
