### ISSUE TITLE
fish_config save theme in a script

### ISSUE THREAD

**Issue by baronleonardo** [fish-shell/fish-shell#9276]
- fish, version 3.4.1
- NixOS
- xfce4-terminal
- Linux Utopia 5.18.14-zen1 1-NixOS ZEN SMP PREEMPT_DYNAMIC Tue Jan 1 00:00:00 UTC 1980 x86_64 GNU/Linux
- xterm-256color

problem:
I want to use this command `fish_config theme save <Theme name>` without promotion for overriding in a script I make `Overwrite theme? [y/N]`

**Comment by baronleonardo** [comment]
I found a workaround based on your solution
`sleep 1; yes | fish_config theme save coolbeans`

I'm trying to create a script that can toggle light/dark theme globally on xfce, the last part was fish
maybe you need to make this feature automatically (toggle fish color theme based on the colorscheme of the system)

**Comment by faho** [comment]
>maybe you need to make this feature automatically (toggle fish color theme based on the colorscheme of the system)

There is no reasonable widely-supported thing we could check here, sorry.

Plus, if you change your colorscheme, there's a non-zero chance it would adjust your terminal's color palette as well, so us swapping from "the black from the palette" to "the white from the palette" would undo that.

Plus which colorscheme do you switch to for dark/light? Plus many people use a dark terminal even in a bright desktop - it's the default for many terminal emulators.
