### ISSUE TITLE
`__fish_complete_path` does not behave like normal path completions would

### ISSUE THREAD

**Issue by ModProg** [fish-shell/fish-shell#9285]
I would expect:
```fish
complete -x -c my_app -a "(__fish_complete_path (commandline --current-token))"
```
and
```fish
complete -F -c my_app
```
To produce the same results, they differ strongly in capability, as `__fish_complete_path` does not support:
- globbing i.e. completing `src/*/fi` to `src/*/fish.rs`
- non prefix-substrings i.e. completing `rc` to `src`
- multi layer path completions i.e. completing `sr/sh/fi` to `src/shell/fish.rs`

Obviously it doesn't make sense to use it as a replacement of -F, but I think it should be capable of returning the same matches as you e.g. might want to change the base dir for completions to start.

In case there are any concerns about it changing the way it functions, we could just have an option to enable this or a separate command.

**Comment by ModProg** [comment]
As a workaround for anyone stumbling on this looking for a solution:
```fish
complete -x -c my_app -a '(complete -C "__fish_complete_path "(commandline --current-token))'
```
This will behave like `-F`

**Comment by krobelus** [comment]
> As a workaround for anyone stumbling on this looking for a solution:
>
> complete -x -c my_app -a '(complete -C "__fish_complete_path "(commandline --current-token))'

`__fish_complete_path` is misleading here; actually any command without user-defined completions works. This is what we usually use:

    complete -x my_app -a '(complete -C "__fish_command_without_completions "(commandline --current-token --cut-at-cursor))'

If you look for `__fish_command_without_completions` in the fish repo you can find some uses.
It looks like `__fish_complete_path` should be taught to use this pattern instead.
Digging deeper we find that `__fish_complete_path` was added to "selectively re-enable file-completion" (see 6ece8523b (__fish_complete_path: add new completion, mimics builtin path completion, 2014-09-28)).
This is exactly what `-F` (added in 2019) does (but `-F` is better as you noted). So there is no reason to use `__fish_complete_path` today.

**Comment by ModProg** [comment]
makes sense. IMO it would be great to have something less verbose than the complete -C call.

**Comment by krobelus** [comment]
I think `__fish_complete_path` has been used in large functions that are supposed to compute all completions (but still want to delegate to fish's file completions if applicable). This is similar to how you'd write completions in Bash. Not necessarily ideal for fish, but it can work fine.

Someone might be using

	complete my_app -a my_app_completions1 -f

where `my_app_completions1` delegates to `__fish_complete_path` if file-path completion is desired.

This is currently not well supported.
Instead you should write

	complete my_app --condition my_app_completions2 -a my_app_completions2 -f

where `my_app_completions2` returns non-zero if file-path completion is desired.
This will make the condition fail, so the `-f` (`--no-files`) switch will not be active.

Of course you can also cache the result

	complete my_app --condition `set -g __cargo_completions (my_app_completions2)` -a 'printf %s\\n $__cargo_completions' -f
