### ISSUE TITLE
complete(1) shows duplicates from symlinked paths

### ISSUE THREAD

**Issue by tjkirch** [fish-shell/fish-shell#9288]
>  fish --version

`fish, version 3.5.1`

> uname -a

`Linux simplify 5.19.14_1 #1 SMP PREEMPT_DYNAMIC Tue Oct 11 15:42:18 UTC 2022 x86_64 GNU/Linux`

> echo $TERM

`xterm-256color`

> Please tell us if you tried fish without third-party customizations by executing this command and whether it affected the behavior you are reporting:
>  sh -c 'env HOME=$(mktemp -d) fish'

Yes, same results.

> Tell us how to reproduce the problem.

Here's a demo:
```fish
> complete -C test | head -n4
test	Check file types and compare values
test	Check file types and compare values
test	Check file types and compare values
test	Check file types and compare values
```

I tracked this down to my system being "usrmerged" so there are actually four symlinked paths that point to the same `test` binary:
````fish
> ls -i (which -a test)
656311 /bin/test  656311 /sbin/test  656311 /usr/bin/test  656311 /usr/sbin/test
````

Since `complete -C` strips paths and just shows the command and its description, it seems like it could dedupe output coming from binaries with the same inode.  (Of course, different paths can have the same filename and need different completion, so this only applies if they're the *same* command, and inode is an easy check.)

**Comment by faho** [comment]
`complete -C` calls the completion system and that doesn't deduplicate the options because it's ordinarily handled by the pager. Deduplication is, of course, more work that is often not useful because this might end up going into the pager again anyway - we almost exclusively use `complete -C` in completion scripts to set up more complex wrapping relationships than `complete -w` can express.

My question here, as always, is what your use case is? What were you attempting to do?

**Comment by tjkirch** [comment]
Thanks for your response!

> My question here, as always, is what your use case is? What were you attempting to do?

This could make a great addition to the issue template, almost word for word!  :)

> My question here, as always, is what your use case is? What were you attempting to do?

Some tools use `complete -C` to see how fish will complete something.  I ran into this while using the great [cmp-fish](https://github.com/mtoohey31/cmp-fish) [[code](https://github.com/mtoohey31/cmp-fish/blob/8ae7bfb1b3251d433c4adf4e64396ef929fbd91f/lua/cmp_fish.lua#L6)] which does completion while editing fish scripts almost as nicely as fish would on the command line.  (The issue is that I see each command many times in the completion list.)

> To be clear: If we would dedupe this, we'd dedupe it simply by string equality.

That makes sense.  I was thinking about multiple commands with the same name but at different paths and having different arguments, and I guess I was assuming that fish would take into account which it was completing for when suggesting arguments.  That's probably a silly idea.

If this doesn't make sense generally, I can recommend that projects calling `complete -C` do their own deduplication.

**Comment by mqudsi** [comment]
> There's no reason to print something multiple times because this is about completions - whether you enter "test" or "test" doesn't matter because they are the same. Even passing as an argument to something else both would have the same effect.

The only question is whether you would deduplicate based off the completion only or also the description.

I wouldn't be against deduplicating here, fwiw.

**Comment by mqudsi** [comment]
PR #9307 would fix this and make `complete -C` actually usable to test/debug/validate/verify completions instead of having to do that interactively.
