### ISSUE TITLE
Issue --web not loading (fish_config)

### ISSUE THREAD

**Issue by Furiousfox-01** [fish-shell/fish-shell#9297]
**I  am using fish  ---> 3.5.1  in ubuntu 22.10**
fish_config is ### not working for me--- shows

![Screenshot from 2022-10-23 **10-03-24](https://user-images.githubusercontent.com/86916986/197374059-26f8f71e-c89a-465e-9892-078666d169c0.png)**

**Comment by faho** [comment]
Duplicate of #9014

**Comment by faho** [comment]
It's an Ubuntu issue - they've snapped all their browsers now, which means they can't open files in /tmp anymore.

Unfortunately there is no good replacement path we could use.

**Comment by Furiousfox-01** [comment]
Thanks it working...👍🏻👍🏻
