### ISSUE TITLE
fails: for AA in **.small cp -s $AA (path change-extension "" $AA); end

### ISSUE THREAD

**Issue by evanescente-ondine** [fish-shell/fish-shell#9299]
Please tell me what is wrong with this command:
`for AA in **.small cp -s $AA (path change-extension "" $AA); end`
it says that I try to copy with the same exact name, even though individual "cp -s image.jpg.small (path extension image.jpg.small) work all the time. but the above, never, nor does "fd '.small$' -x cp -s {} (path change-extension "" {});"
Why ??

fish 3.5.1
ALinux dr-80qr 5.19.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 28 Sep 2022 13:21:25 +0000 x86_64 GNU/Linux
Endeavoros

**Comment by faho** [comment]
This exact command:

```fish
for AA in **.small cp -s $AA (path change-extension "" $AA); end
```

consists of a for-loop with an empty body. Your `cp` here is a loop value.

You probably meant

```fish
for AA in **.small; cp -s $AA (path change-extension "" $AA); end
```

or, better

```fish
for AA in **.small
    cp -s $AA (path change-extension -- "" $AA)
end
```

**Comment by evanescente-ondine** [comment]
f**cking syntax, I hate scripting languages.
Thanks.
