### ISSUE TITLE
Feature: Typo correction like zsh

### ISSUE THREAD

**Issue by mbirth** [fish-shell/fish-shell#93]
zsh does some basic typo correction, e.g. if you run "mkae install", it will ask you "Did you mean make? (y/n)". This is controlled through the CORRECTALL flag. You can even make exceptions which should never be corrected. I'd like to see this feature in fishfish, too.

**Comment by Aeron** [comment]
Maybe it’s just enough to provide some user-overridable alias/alternative for `__fish_command_not_found_handler`?

ZSH correction is not user-friendly indeed and I prefer just to [fuck](https://github.com/nvbn/thefuck) my typos and other flaws. So… for example, if there will be such a function, like `fish_command_not_found`, I can define behavior which suits me best.

In most cases I’ll be pleased with [fuck](https://github.com/nvbn/thefuck) auto-correction. And I always can implement some extra user input, like “Do you mean [thefuck_suggested_command]?”, if necessary.

What do you think?

**Comment by RomanHargrave** [comment]
Perhaps we could implement string comparison using an algorithm like Jaro-Winkler string distance (I find this to be better for autocorrect situations than Levenshtein string distance, as it is better at detecting swaps and is more tunable). The shell could then compare the typo'd word by distance to a list of real commands and select the most similar. For the purpose of efficiency, it might also be prudent to somehow narrow the list of words to check against somehow.

**Comment by faho** [comment]
>Maybe the correction could appear underneath the invalid command, and can be summoned with the down arrow?

I'm a fan of that (and hate zsh's correction to the point that half my zshrc consisted of disabling it in all possible ways), and the "print underneath" stuff might also be useful for #2201.

**Comment by krader1961** [comment]
It has been five years since this was opened. It is clear we do not want to implement "typo correction like zsh". So I'm going to close this. If someone wants to open a new issue proposing a better solution I have no objection.
