### ISSUE TITLE
Tab-complete: Wrong options for usermod

### ISSUE THREAD

**Issue by hotfloppy** [fish-shell/fish-shell#9303]
Hello guys!

It's seems like Fish tab-complete for `usermod` is using a wrong options for `--add-subuids` and `--add-subgids`.

Here is an asciinema recording for this issue:
https://asciinema.org/a/531823

Cheers!

**Comment by faho** [comment]
This is one of those cases where a word says as much as a minute of video:

The problem is that fish suggests "--add-sub-uids" where it should be "--add-subuids".

Thanks, fixed.
