### ISSUE TITLE
eval command does not work

### ISSUE THREAD

**Issue by dalisoft** [fish-shell/fish-shell#9316]
fish: v3.5.1 (homebrew)
os: macOS 12.6.1 (arm64)

Command does not work on fish-shell whereas works on both `zsh` and `bash`.

Example command: 
```
AWS_TARGET=`aws ec2 describe-instances --filter Name=tag:Environment,Values=SOME_VALUE --query "QUERY" --output text` && aws ssm start-session --target $AWS_TARGET --document-name document_name --and-many-arguments-too
```

**Comment by faho** [comment]
Fish isn't bash or zsh. It has its own scripting language that's incompatible to both.

Now github's formattting makes your command pretty much unreadable so I' not really sure what you want to execute.

You can make a code block with three backticks at the beginning and end like

`````
```
your code here
```
`````

**Comment by dalisoft** [comment]
Thank you for reply @faho 
Yes, formatting broke syntax, sorry, i fixed it.
I am using fish already more than year and it works perfectly but there rare case where need use variables and it just not work and this is one of these case

**Comment by floam** [comment]
I don't see you using `eval`.

Are you referring to the backticks? `?

**Comment by dalisoft** [comment]
Yes, backticks (also used as like/as eval)

**Comment by faho** [comment]
Okay, let's go through:

```fish
AWS_TARGET=`aws ec2 describe-instances --filter Name=tag:Environment,Values=SOME_VALUE --query "QUERY" --output text`
```

Those are backticks used as a command substitution, and `var=val` to set a variable.

You want:

```fish
set AWS_TARGET (aws ec2 describe-instances --filter Name=tag:Environment,Values=SOME_VALUE --query "QUERY" --output text) && aws ssm start-session --target $AWS_TARGET --document-name document_name --and-many-arguments-too
```

(with the caveat that fish will split `aws ec2 describe-instances` on newlines only, bash will use $IFS)

**Comment by dalisoft** [comment]
Thank you a lot for describing
