### ISSUE TITLE
Completion of filenames starting with '#' fail to escape the first '#' from the command line

### ISSUE THREAD

**Issue by Khoulaiz** [fish-shell/fish-shell#9320]
❯ fish --version                                                                                                  fish, version 3.5.1

❯ echo $version                                                                                                   3.5.1

❯ uname -a                                                                                                        Darwin VWAGWOY00414 21.6.0 Darwin Kernel Version 21.6.0: Thu Sep 29 20:12:57 PDT 2022; root:xnu-8020.240.7~1/RELEASE_X86_64 x86_64

❯ echo $TERM                                                                                                      ~/tmp
xterm-256color

recorded with asciinema on pure installation in ~/tmp/tmp

https://asciinema.org/a/533782

Steps to reproduce: 
1. create a couple a normal files and then one with '#' in the start
2. type a file completion command like 'rm ' and type '#' + <tab> multiple times for the completion

expected behaviour: 
- all created command line are executable in terms of the filename completion

current wrong behaviour:
- command line completion creates filenames that do not exist (prefixing them with an unescaped '#')

**Comment by krobelus** [comment]
this is expected because inside a comment we fall back to file completion. I don't think we want to remove a comment that the user typed. If you want to complete a filename that starts with `#` then type `\#`.
I guess there's an argument to completely disabling completion inside comments but I don't think it really hurts.

**Comment by krobelus** [comment]
on another look the completions inside comments are quite broken, so I removed them in c4a60feff1b633524252efeefaa531158439688e to avoid similar confusion.
Thanks for reporting!
