### ISSUE TITLE
printf: extra specifiers not evaluated as if 0 supplied

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#9321]
printf(1) is supposed to have this property:

> The format operand shall be reused as often as necessary to satisfy the argument operands. Any extra b, c, or s conversion specifiers shall be evaluated as if a null string argument were supplied; other extra conversion specifications shall be **evaluated as if a zero argument were supplied**. If the format operand contains no conversion specifications and argument operands are present, the results are unspecified.

Fish doesn't do this, causing this discrepancy:

```shell
> ksh -c 'printf "%d %d\n" 1 2 3'
1 2
3 0
> zsh -c 'printf "%d %d\n" 1 2 3'
1 2
3 0
> bash -c 'printf "%d %d\n" 1 2 3'
1 2
3 0
> fish -c 'printf "%d %d\n" 1 2 3'
1 2
3 : Invalid argument
```

**Comment by faho** [comment]
This works for me in both fish 3.5.1 and #9313.

**Comment by floam** [comment]
Huh. It does not work on `master`, #9313, or 3.5.1 for me.

> /opt/homebrew/Cellar/fish/3.5.1/bin/fish -c 'printf "%d %d\n" 1 2 3'
1 2
3 : Invalid argument

**Comment by floam** [comment]
On the other hand, %f works. This is something to do with the `errno` after std::wcstoll but not std::wcstod.

```
printf "%f %f\n" 1 1 1
1.000000 1.000000
1.000000 0.000000
```

**Comment by mqudsi** [comment]
Works for me under Linux, but confirmed broken on FreeBSD. Good candidate for our test suite after it gets fixed.

**Comment by floam** [comment]
@mqudsi yeah. I added a test for this little stinker.
