### ISSUE TITLE
Escaped string acting unescaped in `string replace`

### ISSUE THREAD

**Issue by BlueFalconHD** [fish-shell/fish-shell#9324]
I am running fish shell `3.5.1` and have tried without third party customizations. My machine is running macOS and WezTerm. I am trying to get argument parsing in a function, without having to use argparse, as I despise it. I am creating a little system to style output (color, bold, italic etc.), and use a function to wrap the individual parts into one. Here is the relevant part of the function:
```fish
function style -a 'color' 'bold' 'italic' 'underline' 'strikethrough' 'faint'
  if test -n "$color"
    set -l escaped "$(echo "$color" | string escape)"
    color "$(string replace "\-\-color=" "" "$escaped" | color)"
  end
  # more here, but doesn't connect in any way to the error
end
```
Because I am using the function argument names flag, it sets each names respective variable to the value it was set to, and `''` if it isn't set. This small snippet checks if the `--color` argument is used, and if it is, it's intended purpose was to call the color function with the argument value. The problem is the argument names flag returns the arguments with the flag name, and I am not sure how to remove it. The error I am getting is as follows:
```
string replace: --color=green: unknown option

etch.fish (line 1): 
string replace "\-\-color=" "" "$escaped" | color
^
in command substitution
        called on line 80 of file etch.fish
in function 'style' with arguments '--color=green --bold=1 --italic=1 --underline=1'
        called on line 118 of file etch.fish

(Type 'help string' for related documentation)
```
I believe even though I escaped the `$color` variable it is still influencing `string replace`. Any advice on how to fix this?

**Comment by faho** [comment]
What you need to do is the same thing you would do with commands like `grep` or `rm`: Use a `--` argument to signal the end of options:

```fish
string replace -- "--color=" "" "$escaped"
```

It says so in [the documentation](https://fishshell.com/docs/current/cmds/string.html#description):

> Arguments beginning with - are normally interpreted as switches; -- causes the following arguments not to be treated as switches even if they begin with -

This isn't a fish-specific thing, this is a general unix convention - like I said, you'd also need this to `grep`` for "--color".
