### ISSUE TITLE
string repeat: require explicit -n/--count option only in presence of --max

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#9332]
`string repeat` has this usage signature:

<pre><span class="s1"><b>string</b></span><span class="s2"> </span><span class="s1"><b>repeat</b></span><span class="s2"> [(</span><span class="s1"><b>-n</b></span><span class="s2"> | </span><span class="s1"><b>--count</b></span><span class="s2">) </span><span class="s3"><em>COUNT</em></span><span class="s2">] [(</span><span class="s1"><b>-m</b></span><span class="s2"> | </span><span class="s1"><b>--max</b></span><span class="s2">) </span><span class="s3"><em>MAX</em></span><span class="s2">] [</span><span class="s1"><b>-N</b></span><span class="s2"> | </span><span class="s1"><b>--no-newline</b></span><span class="s2">]</span><br><span class="s1">              [</span><span class="s4"><b>-q</b></span><span class="s1"> | </span><span class="s4"><b>--quiet</b></span><span class="s1">] [</span><span class="s5"><em>STRING</span><span class="s1"> …</em>]</span></pre>

The enhancement suggestion is, make `string repeat 5 x` or `echo x | string repeat 5` (**which both silently exit status 1 with no error message today**) equivalent to `string repeat -n 5 x` or `echo x | string repeat -n 5`, taking the first positional argument as _COUNT_  and additional arguments as <em>STRING</em>s, like how `string join` takes the first argument as the separator.

```shell
> echo x | string repeat 5
xxxxx
> string repeat 5 x
xxxxx
```

In other words, it should basically behave how you'd expect it to if the usage synopsis had an additional simpler signature:

<pre class="p1">
<span class="s1"><b>string</b></span><span class="s2"> </span><span class="s1"><b>repeat</b></span><span class="s2"> [</span><span class="s1"><b>-N</b></span><span class="s2"> | </span><span class="s1"><b>--no-newline</b></span><span class="s2">] (</span><span class="s1"><b>-q</b></span><span class="s2"> | </span><span class="s1"><b>--quiet</b></span><span class="s2">] </span><span class="s3"><em>COUNT</em></span><span class="s2"> [</span><span class="s3"><em>STRING</em> …]<br><span class="s1"><b>string</b></span><span class="s2"> </span><span class="s1"><b>repeat</b></span><span class="s2"> [(</span><span class="s1"><b>-n</b></span><span class="s2"> | </span><span class="s1"><b>--count</b></span><span class="s2">) </span><span class="s3"><em>COUNT</em></span><span class="s2">] [(</span><span class="s1"><b>-m</b></span><span class="s2"> | </span><span class="s1"><b>--max</b></span><span class="s2">) </span><span class="s3"><em>MAX</em></span><span class="s2">] [</span><span class="s1"><b>-N</b></span><span class="s2"> | </span><span class="s1"><b>--no-newline</b></span><span class="s2">]</span><br><span class="s1">              [</span><span class="s4"><b>-q</b></span><span class="s1"> | </span><span class="s4"><b>--quiet</b></span><span class="s1">] [</span><span class="s5"><em>STRING</span><span class="s1"> …</em>]</span></pre>

`-n` or `--count` should be required only to distinguish things in the case where a `--max` is being used, for the sake of things not being ambiguous and it is important that only things that used to error start to work, but things that worked before do not have a change in behavior. This example would needs to have the same output as it does today:

```fish
> string repeat 5 x --max 3
555
xxx
```
i.e. it will still be necessary to explicitly specify a `--count` option:

```fish
> string repeat --count 5 x --max 3
xxx
```

The motivation here is to make `string repeat` easier to figure out and remember how to use, taking into consideration `--max` is a rare thing.

**Comment by ridiculousfish** [comment]
This makes sense to me; today `string repeat 3 foo` does nothing useful.
