### ISSUE TITLE
{$}: error message includes internal use char

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#9337]
```shell
> echo {$,}
```

<img width="292" alt="image" src="https://user-images.githubusercontent.com/291142/200906723-edeb618b-b10e-4841-b196-2528a8883da5.png">

The character is FDDF.

**Comment by mqudsi** [comment]
This is left over from how we abuse the tokenizer/parser to support expansion. We need a special context-sensitive error message here.

**Comment by floam** [comment]
Simplest example is actually just `{$}`, no comma needed
