### ISSUE TITLE
Incorrect warning when erasing a shadowed universal variable

### ISSUE THREAD

**Issue by floam** [fish-shell/fish-shell#9338]
Earlier today I was surprised by this when I changed directories:

```shell
> /
set: successfully set universal 'dirprev'; but a global by that name shadows it
set: successfully set universal '__fish_cd_direction'; but a global by that name shadows it
floam@MBP />
```

I couldn't figure out how that's possible given cd.fish. However, it appears when erasing a uvar that is also a global:

```shell
> set -U foo
> set -g foo
> set -eU foo
set: successfully set universal 'foo'; but a global by that name shadows it
```

**Comment by mqudsi** [comment]
Yeah, I ran into this code while supporting multiple scopes for erase. The warning isn't correct and I meant to remove it separately once that PR was accepted.
