### ISSUE TITLE
Removing of printing status codes when running Fish functions

### ISSUE THREAD

**Issue by nikitavoloboev** [fish-shell/fish-shell#9344]
```
fish, version 3.5.1
Darwin nikiv 22.1.0 Darwin Kernel Version 22.1.0
```

I have the issue where I want to make a Fish function that runs a command but when ran in Fish function this command will add extra line with 0.

My function:

```shell
# r - run `cargo run` when rust files change
# r <cmd> - cargo <cmd>
function r
    if not count $argv
        cargo watch -q -x "run -q"
    else
        cargo $argv
    end
end
```

The problem:

<img width="591" alt="image" src="https://user-images.githubusercontent.com/6391776/201449734-c8dfd01a-9b77-496c-a467-8012a7580601.png">

As you can see running `cargo watch -q -x "run -q"` doesn't print 0 but running it through fish does. It adds extra line and I want to not have it printed as it's useless info, I know it exited with 0. Can I do it?

Thanks.

**Comment by ridiculousfish** [comment]
The extra 0 is printed by `count` which outputs its count of arguments to stdout.

One option is to redirect it:

     if not count $argv > /dev/null
     
A more idiomatic alternative is to use `set -q` to ask if the first argument of argv is set:

        if not set -q argv[1]
            cargo watch -q -x "run -q"
        else
               cargo $argv
        end

Hope this helps! Closing as working as designed.
