### ISSUE TITLE
how to setup up arrow key to match begin word only?

### ISSUE THREAD

**Issue by NgoHuy** [fish-shell/fish-shell#9352]
fish --version
  3.5.1

When I type `sed` and then up arrow key to get previous command of sed, it should only search sed not `cat aaa.txt | sed 's/test//g'`
How can I setup it only search words begin with sed not in parameters or pipe?

**Comment by faho** [comment]
Bind it to "history-prefix-search-backward", like

     ﻿bind \e\[A history-prefix-search-backward

That `\e\[A` is the escape sequence that pressing the up arrow sends, run `fish_key_reader` and press up to find it.

**Comment by NgoHuy** [comment]
thank you very much, it's pretty guide.
