### ISSUE TITLE
Question: fish command which starts with a subshell

### ISSUE THREAD

**Issue by d5ve** [fish-shell/fish-shell#936]
In bash, I've been using a command like the following to check queue lengths on gearman daemons. The subshell and sleep are to (as far as I can tell) keep the connection to the gearmand open long enough to get a response over a slow link. 

```
# Sometimes returns no data over a slow link
$ echo status | netcat gearmand-01 7003
# Keeps connection open long enough to get reply.
$ (echo status ; sleep 0.5) | netcat gearmand-01 7003
```

I've been unable to work out an equivalent command with fish, as it seems like you can't start a command with a subshell. Is there another way of doing this?

There is a slow workaround doing something like the following, but it has only second-resolution, so the command will take at least 2 seconds to complete, which adds up when many hosts are being polled.

```
# Use the interval param to netcat
$ echo status | netcat -i 1 gearmand-01 7003
```

Cheers,

Dave

**Comment by nicktimko** [comment]
Or a simpler question: how to replicate something like `$(brew --prefix mysql)/bin/mysqladmin`. Using `(brew --prefix mysql)/bin/mysqladmin` chokes because it's an "Illegal command name"

**Comment by krader1961** [comment]
The solution today is `eval (brew --prefix mysql)/bin/mysqladmin)`. The long term solution to this limitation will be addressed in issue #154.

**Comment by krader1961** [comment]
The alternative to `(...)` is `fish -c`; e.g., `fish -c 'echo status; sleep 0.5'`.

**Comment by foxpy** [comment]
> Try this:
> 
> ```
> begin ; echo status ; sleep 0.5 ; end | netcat gearmand-01 7003 
> ```

But how do I do this?
```time begin
    # code
end```
