### ISSUE TITLE
Umount of /home/$(USER) not possible?

### ISSUE THREAD

**Issue by peschu123** [fish-shell/fish-shell#9360]
fish version: 3.5.1
uname -a: 
Linux blubb 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

I try to do  `sudo umount /home/{$USER}` which returns 

> umount: /home/peschu: target is busy.

`lsof /home/peschu/` gives me
> COMMAND PID   USER  FD   TYPE DEVICE SIZE/OFF    NODE NAME
> fish     13 peschu mem    REG  252,0     8441 2621444 /home/peschu/.local/share/fish/fish_history

The home dir is mounted to an encrypted container:
`mount` 
> /dev/mapper/loop0 on /home/peschu type ext4 (rw,relatime)

`losetup -a`
> /dev/loop0: []: (/home/.peschu/disk.img)

Is there a way to unmount the user home? In general it would be sufficient to do this during shutdown.
But I don't know if this is possible with WSL ... At the moment I do it manually. In bash this worked without problems, fish seems to block it?

**Comment by anordal** [comment]
It seems you've already found it, although I get a different result (I also have fish 3.5.1 on linux).

"Device or resource busy" or EBUSY is [errno](https://man7.org/linux/man-pages/man3/errno.3.html) speak for "the kernel protects you from unmounting a filesystem that has open files". The solution is as you did, to find the process(es) that have open files there, such as by asking `lsof`, and get them to close those. In your case it's the fish_history file, so the logical solution should be `exec fish --private` – replace the current shell with one that doesn't persist history.

However, this is where I get a different result. On Linux, you can see all open files of a process in the proc filesystem, such as `ls -l /proc/(pgrep fish)/fd/`. In my case, it's the current directory that fish is keeping open, so `cd /` is the fix to that.

Finally, a syntax tip: What you mean is not `/home/$(USER)` or `/home/{$USER}`, but `/home/$USER` or simply `$HOME`.

**Comment by peschu123** [comment]
Thank you for your reply and the explanations. I learned something while I investigated this. :)

in the end it was this:
> However, I get a different result. Looking at `ls -l /proc/(pgrep fish)/fd/`, it's not the history file, but the current directory that fish is keeping open, so `cd /` is the fix to that.

Maybe it was a bit late that night. ^^  But the main problem was: 
I was not aware that windows terminal kept another session open in the background.
