### ISSUE TITLE
Handling of literal line breaks in subshells is buggy

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#9364]
```
> echo (echo
foo)

Command 'foo' not found, did you mean:

  command 'fio' from deb fio
  command 'goo' from deb goo
  command 'woo' from deb python-woo
  command 'fgo' from deb fgo
  command 'fop' from deb fop
  command 'fog' from deb ruby-fog
  command 'fox' from deb objcryst-fox

Try: sudo apt install <deb name>

fish: 
foo
^~^
in command substitution
fish: Unknown command
echo (echo
foo)
     ^
```

It *seems* like `(echo` is converted into one token (subshell start) but trying it with different variations reveals there's something else that goes wrong too, because the inner subshell in the next sample evaluates to ` foo` (with a leading space, in case GitHub eats it):

```
printf "'%s'\n" (echo (echo
echo foo))
' foo'
```

**Comment by krobelus** [comment]
what's the problem exactly? this looks correct to me.

in your second example, the outer echo receives two arguments
1. an empty one (from the `echo`)
2. a `foo` (from `echo foo`)

both arguments are joined by spaces, which explains the ` foo`

**Comment by mqudsi** [comment]
Look at the first example again. Why is it trying to execute `foo`?

**Comment by krobelus** [comment]
because it's equivalent to

```fish
echo (echo; foo)
```

everything inside the cmdsub is evaluated as single fish script, so newlines are just command terminates. It works similar to

```fish
eval "echo
foo"
```

**Comment by mqudsi** [comment]
Wow, I feel dumb. I was working with the parser's implicit line continuations after `|` and forgot that a newline in a subshell doesn't act the same way.
