### ISSUE TITLE
How to save colors in dotfiles repository

### ISSUE THREAD

**Issue by Susensio** [fish-shell/fish-shell#9366]
I've been reading a lot on universal variables, there are proposals of removing then. In several places, editing or version controlling `fish_variables` file is discouraged, as it is generated by `fish`.
And I agree. The thing is, there are some things in `fish_variables` that I would like to share between my computers. Mainly, colors configured by `fish_config` and edited by me, and other visual parameters.

The question is, what is the **proper method** of not depending on `fish_variables` and keeping this colors in a remote repository? Should I declare them as globals in my `config.fish`?

**Comment by Susensio** [comment]
In your `config.fish` example, how do you manually change colors? Do you have to unset manually your universal flag in order for them to apply? Are there any drawbacks in using globals instead of universals?

**Comment by faho** [comment]
>Do you have to unset manually your universal flag in order for them to apply?

You would either change config.fish and erase $faho_colors_set, or you would change config.fish and run the `set` yourself manually.

>Are there any drawbacks in using globals instead of universals?

Not really. Some people like using universals so they can just run `set -U` manually.

(it's also very slightly faster because you can mostly skip all the setting, like in my example)

**Comment by Susensio** [comment]
I'm having problems setting --bold colors, how can this be achieved with your `colors.fish` scheme?

**Comment by faho** [comment]
Two arguments: 

```fish
set -U fish_color_user green --bold
```

These color values are like arguments to `set_color`, you would use this like

```fish
set_color green --bold
echo foo
set_color normal
```

not `set_color "green --bold"`.

(also there's no need to export these, I recommend removing the `x`)

**Comment by faho** [comment]
>whenever I change something in colors.fish, let's say the file is changed in a different machine and modified by pulling my dotfiles repo, I would have to remember to unset the variable, or else it won't take effect.

That's what I said in https://github.com/fish-shell/fish-shell/issues/9366#issuecomment-1322213280 ?

**Comment by Susensio** [comment]
I've managed to save a timestamp in the flag with 
```fish
stat --format="%Y" (status --current-filename)
```
in order to avoid redefining all the variables... but doing so is 1 ms **slower** that overwriting all the universal variables (11ms vs 10ms for fish startup time), so I think it's not worth the complexity.


Anyhow, there is my `colors.fish`
```fish
# Update variables when file is modified

set -l modified (stat --format="%Y" (status --current-filename))

if not set -q colorscheme || test $colorscheme != $modified

    set -U fish_color_autosuggestion brblack
    set -U fish_color_cancel normal
    set -U fish_color_command white --bold
    set -U fish_color_comment red
    set -U fish_color_cwd blue --bold
    set -U fish_color_end green
    set -U fish_color_error red
    set -U fish_color_escape 00a6b2 cyan
    set -U fish_color_history_current normal
    set -U fish_color_host white --bold
    set -U fish_color_host_remote yellow --bold
    set -U fish_color_match normal
    set -U fish_color_normal normal
    set -U fish_color_operator cyan
    set -U fish_color_param white
    set -U fish_color_quote yellow
    set -U fish_color_redirection 00afff brcyan
    set -U fish_color_search_match bryellow
    set -U fish_color_selection white
    set -U fish_color_status red
    set -U fish_color_user green --bold
    set -U fish_color_user_root red --bold
    set -U fish_color_valid_path normal
    set -U fish_greeting 
    set -U fish_key_bindings fish_default_key_bindings
    set -U fish_pager_color_completion normal
    set -U fish_pager_color_description B3A06D yellow
    set -U fish_pager_color_prefix white --bold --underline
    set -U fish_pager_color_progress brwhite --background=cyan
    set -U fish_pager_color_selected_background -r
    set -U fish_prompt_pwd_dir_length 0

    set -U colorscheme $modified
end
```

**Comment by faho** [comment]
>final question, any drawbacks in not guarding universal variable definition with a flag, and doing it over a over?

Writes to the universal variable file.

But hey, I'm not your dad, do whatever works for you.
