### ISSUE TITLE
Fedora 37 build on Open Build Service

### ISSUE THREAD

**Issue by antonc42** [fish-shell/fish-shell#9367]
Fedora 37 was released a few days ago. When it becomes available in the [Open Build Service](https://build.opensuse.org/project/show/shells:fish:release:3), please enable it. Thank you for all the great work and for supporting so many distros and versions!

@zanchey

**Comment by faho** [comment]
Done on both https://build.opensuse.org/project/show/shells:fish:release:3 and https://build.opensuse.org/repositories/shells:fish:nightly:master

I also removed Fedora 32 and 33 as they are long EOL. I kept 34 for the time being (EOL since 2022-06-07)
