### ISSUE TITLE
PATH environment variable completely stops working with fish for no reason

### ISSUE THREAD

**Issue by AcinonXDev** [fish-shell/fish-shell#9372]
Fish Version: 3.5.1
Operating System: `Darwin (computer domain name).local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:15:09 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T6000 arm64` (macOS 13 Ventura)
Terminal: iTerm2

At the time of the issue, I had the tide plugin installed.

As far as I can tell, this problem is not reproducible. It just happened one day.

I was trying to use software I had installed through Homebrew with fish, but I got a "command not found" error. When I ran `echo $PATH` it only reported the default system paths. I have a script that I run every time I start fish that was copied straight from my ~/.zshrc, which always worked previously and allowed me to use the software in my $PATH. However, when running it I got a new error I had never seen before saying that you can't use `export $PATH=' '` in fish, which was never a problem before. I tried 'fixing' the script and then inserting it into my fish.config (which I only just then knew about) with `cat ~/fishprofile ~/.config/fish/config.fish > ~/.config/fish/config.fish` but accidentally created an infinite loop of inserting data into the config file, which made it impossible to start fish. I ended up deleting all my configs from the fish config directory, and now nothing works and I had to switch back to zsh, which was my default login shell.
I really miss the functionality of fish and would love to get my environment variables back. Is there a way I can do this?

**Comment by faho** [comment]
Okay, you're asking this kind of late, and your information is incomplete and much of it isn't useful.

In short:

At this point it appears like you should just remove ~/.config/fish and start over.

----

Okay, now to try to explain some of what you did wrong:

> you can't use export $PATH=' ' in fish

This is essentially correct, but probably not in the way you think it is.

$PATH in fish is a list. When you write a list outside of quotes, it is expanded to one argument per element of the list, and any other string attached to it is added to each of the elements.

So, say your $PATH is /usr/bin, /sbin and /bin, this would result in

```fish
export /usr/bin=' ' /sbin=' ' /bin=' '
```

Which is just gibberish, and will tell you that "/usr/bin" is not valid as a variable name, and won't actually change anything.

So either you ran something different or this didn't cause your issue.

What you want, assuming the idea is to add a directory to $PATH, is one of these:

```fish
fish_add_path /whatever/directory

set -a PATH /whatever/directory

set -gx PATH $PATH /whatever/directory

export PATH="$PATH:/whatever/directory"
```

That last one? That's the exact same thing you would use in bash/zsh. `export $PATH=foo` is wrong in those, too.

>cat ~/fishprofile ~/.config/fish/config.fish > ~/.config/fish/config.fish

Here, config.fish is both an input and an output file. This will result in weirdness.

>When I ran echo $PATH it only reported the default system paths

It's basically impossible for us to say what happened here. One possible explanation is that you used $fish_user_paths and erased it (or some plugin helpfully did it for you). Another is that you use some tool to add paths to $PATH and it's no longer called or doesn't work anymore.
