### ISSUE TITLE
How to create files and directories with `touch` and `mkdir` using regular expressions?

### ISSUE THREAD

**Issue by warriarir** [fish-shell/fish-shell#9373]
## System

Fish is my main terminal shell that I use at the moment (`fish, version 3.5.1`).

```bash
uname -a
Darwin Max-MacBook-Air.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64
```
 For my main work, I use the iTerm2 terminal.
```bash
echo $TERM
xterm-256color
```
Using shell launch via `sh -c 'env HOME=$(mktemp -d) fish'` didn't solve my problem.

## Question

In my last `zsh` terminal shell, I often used the regular expression `touch` and `mkdir` utilities to generate files. Something like (on the example of a `touch`):

```bash
touch file{1..10}.txt
ls -l
total 0
-rw-r--r--@ 1 dex  staff  0 Nov 23 14:34 file1.txt
-rw-r--r--@ 1 dex  staff  0 Nov 23 14:34 file10.txt
-rw-r--r--@ 1 dex  staff  0 Nov 23 14:34 file2.txt
-rw-r--r--@ 1 dex  staff  0 Nov 23 14:34 file3.txt
-rw-r--r--@ 1 dex  staff  0 Nov 23 14:34 file4.txt
-rw-r--r--@ 1 dex  staff  0 Nov 23 14:34 file5.txt
-rw-r--r--@ 1 dex  staff  0 Nov 23 14:34 file6.txt
-rw-r--r--@ 1 dex  staff  0 Nov 23 14:34 file7.txt
-rw-r--r--@ 1 dex  staff  0 Nov 23 14:34 file8.txt
-rw-r--r--@ 1 dex  staff  0 Nov 23 14:34 file9.txt
```

I turned to the [documentation](https://fishshell.com/docs/current/cmds/string.html#regular-expressions) and tried to do it in the image and likeness as it was shown there, but for me it was not crowned with success. On pure `fish`, I can't do it. The following happens:

```bash
touch file{1..10}.txt
ls -l
total 0
-rw-r--r--@ 1 dex  staff  0 Nov 23 14:39 file{1..10}.txt
```
or
```bash
touch file{1,10}.txt
ls -l
total 0
-rw-r--r--@ 1 dex  staff  0 Nov 23 14:40 file1.txt
-rw-r--r--@ 1 dex  staff  0 Nov 23 14:40 file10.txt
```

My question may seem silly, but **how is it possible to create many files with `touch` and `mkdir` using regular expressions**?

**Comment by faho** [comment]
Your problem here is that fish doesn't support `{1..10}` ranges. Use `seq` instead:

```fish
touch file(seq 1 10).txt
```

>My question may seem silly, but how is it possible to create many files with touch and mkdir using regular expressions?

This isn't something regular expressions *do*. They don't *generate*, they *match*.

If you have a regular expression like `foo.*bar`, that can match an infinite number of strings. You don't want to create an infinite number of files.

**Comment by warriarir** [comment]
Thank you for your explanation, you helped me a lot ❤️
