### ISSUE TITLE
Doc request: a section to configure commun editors to work with .fish files would be great!

### ISSUE THREAD

**Issue by stephane-archer** [fish-shell/fish-shell#9374]

**Comment by faho** [comment]
There are about 50 editors in regular use, and each is different. It's also typically just using the editor's plugin system - install [fish-mode](https://github.com/wwwjfy/emacs-fish) in emacs, install the [fish plugin](https://marketplace.visualstudio.com/items?itemName=bmalehorn.vscode-fish) in vscode, install the [fish plugin](https://github.com/khaveesh/vim-fish-syntax) in vim.

So it's really just "configure your editor the way your editor is to be configured".

To be quite honest, that's not something I would want to use documentation time and real estate for.

Sorry, but no.
