### ISSUE TITLE
`open.fish` writes to stdout

### ISSUE THREAD

**Issue by oati** [fish-shell/fish-shell#9378]
Launching Gnome Files with `open some_directory` (with no existing nautilus process) makes it write warnings onto my terminal.

Are there any reasons against changing
https://github.com/fish-shell/fish-shell/blob/a770ff144edb206251542281cf27aa21dbfebc9e/share/functions/open.fish#L29
to `xdg-open $i < /dev/null &> /dev/null &`?

fish version 3.5.1
OS: NixOS
DE: Sway
terminal: Kitty

**Comment by oati** [comment]
Maybe this should have been a part of #7215? The [xdg-utils issue](https://gitlab.freedesktop.org/xdg/xdg-utils/-/issues/158) mentions this behavior.

**Comment by faho** [comment]
>Are there any reasons against changing

Yes, that it could be printing actual errors.

The correct place to fix this is in Nautilus - unfortunately GUI apps for some reason never really pay attention to their stderr/out.

Sorry, I don't think we should be adding this.
