### ISSUE TITLE
Complete registry subkeys for `reg` completion

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#9380]
For instance autocomplete `<keyname>` for [`reg add`](https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/reg-add) and other `reg` subcommands.

This issue can be closed later by me or somebody else. It's not prioritized for me as I am Linux user. But I'll try to close it.

**Comment by faho** [comment]
Note: Next time, please just open the PR or, if you decide not to work on it yourself, just leave it.

There is no need to have a lot of issues asking for specific completions open. We know there is more work to be done for completions. There is always more work to be done for completions and there will always be more work to be done for completions.

Currently in my $PATH I see 4345 executables, 2330 of which appear to not have completions. I could file a bug for most of those, but that wouldn't be helpful.

We accept basically all completions, as long as the tool is generally available to the public and they are acceptably written.
