### ISSUE TITLE
Debian release keys are missing

### ISSUE THREAD

**Issue by h4l** [fish-shell/fish-shell#9393]
The fish release keys for Debian are 404ing:

- https://download.opensuse.org/repositories/shells:fish:release:3/Debian_9.0/Release.key
- https://download.opensuse.org/repositories/shells:fish:release:3/Debian_10/Release.key
- https://download.opensuse.org/repositories/shells:fish:release:3/Debian_11/Release.key

As listed on the Debian section here:
https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A3&package=fish

**Comment by faho** [comment]
It appears the path now looks like https://download.opensuse.org/repositories/shells:/fish:/release:/3/Debian_10/Release.key, with a "/" between the "shells:" and "fish:".

I don't think that's something we can change on our end?

cc @zanchey

**Comment by faho** [comment]
Reported at https://github.com/openSUSE/software-o-o/issues/1273

**Comment by zanchey** [comment]
Yeah, that's a software.o.o issue

**Comment by faho** [comment]
Okay, I found where it was broken and reported it, there's nothing more to do on our end (we can't even work around it) so I'm closing this. Sorry for the inconvenience.

**Comment by h4l** [comment]
Thanks for investigating and sorting that @faho, much appreciated!
