### ISSUE TITLE
HelpWithFishScripting: How to have an  alias return the text after prompt rather than echoing it

### ISSUE THREAD

**Issue by pradyumnac** [fish-shell/fish-shell#9397]
# Issue Type
Help needed with scripting

# What I did
```fish
> ls ~/.config/fish/functions|gum filter|sed 's/\.fish/ /g' 
```

# What I am looking to do 
if I select an alias , I am looking to have this entered in the prompt for me to 
**type out the args**
```fish
> howdoi |
```

I am looking to save the script as an alias "aliases" so that typing "aliases" in prompt will give me a list of aliases to choose from
```fish
> alias -s aliases "ls ~/.config/fish/functions|gum filter|sed 's/\.fish/ /g' "
```

# Current behavior
It justs returns the alias name (Echoes to stdout) as expected. How to implement the above ?

**Comment by pradyumnac** [comment]
# Workaround 1
One way (though not practical) is:
```fish
> alias -s aliases "eval (ls ~/repos/fish/functions|gum filter|sed 's/\.fish/ /g')"
> aliases readme.md<cr>
```

In this case, I want to `cat` out the file using batcat alias.  But That will requirement be to remember the exact alias beforehand to type out the args first

# Workaround 2:
`> alias -s aliases "eval (ls ~/repos/fish/functions|gum filter|sed 's/\.fish/ /g' gum input)" ` 

This will trigger the argument prompt separately after choosing the alias before running eval on both alias name and thenn its args

But this is not a clean way to do it.

** I  am looking for a way to do the above  a mentioned above**

**Comment by faho** [comment]
First of all: Make it a function.

`alias` is a cheesy function that makes functions. It's limited in scope and really only suited for very simple cases.

Secondly: You want `commandline`. For example:

```fish
function foo
    commandline -r "echo foo"
end
```

If you now run `foo`, your commandline will afterwards be `echo foo`. So you want something like

```fish
function aliases
    commandline -r -- (ls ~/.config/fish/functions|gum filter|sed 's/\.fish/ /g')
end
```

**Comment by pradyumnac** [comment]
Perfect. This is what I was missing

Thanks a lot :)

About alias:
Yes. I made it a function. just referring to it as alias here. My bad
