### ISSUE TITLE
Question: invoke special input function from fish function?

### ISSUE THREAD

**Issue by bagohart** [fish-shell/fish-shell#9399]
(Using fish version 3.5.1)

Hi,
I'm trying to write a function to overload `<Tab>`, i.e. I would like to do the following:
```fish
bind -k \t overloaded_tab

function overloaded_tab
  if foo
      bar
  else
    complete # invoke tab completion here
  end
end
```

But the `complete` instead tries to invoke the `complete` command that adds tab completion entries for various commands.
The only relevant documentation I found was from the section on binds:
```
Note that special input functions cannot be combined with ordinary shell script commands. 
The commands must be entirely a sequence of special input functions (from bind -f) or all 
shell script commands (i.e., valid fish script).
```
which doesn't tell me anything about how/if they can be invoked outside bind commands.
My current guess is that it's impossible, but I wanted to ask if there is at all a way around this before I give up on this.

**Comment by krobelus** [comment]
I thing you're looking for `commandline -f complete`

**Comment by bagohart** [comment]
Great, that works! Thanks!

I notice that [the section on special input functions](https://fishshell.com/docs/current/cmds/bind.html#special-input-functions) does not mention this. What do you think about adding a sentence with a link to that section?
For example, something like this (bold for new sentence):

Note that special input functions cannot be combined with ordinary shell script commands. The commands must be entirely a sequence of special input functions (from bind -f) or all shell script commands (i.e., valid fish script).
**To invoke special input functions from a regular fish function, use commandline -f.**
