### ISSUE TITLE
Feature: Multi-level path completion

### ISSUE THREAD

**Issue by mbirth** [fish-shell/fish-shell#94]
Coming from zsh, I'm used to the multi-level path competion. Example: I type "cd /u/lo/b" and hit TAB and zsh complets it to "cd /usr/local/bin". If some completion is unclear, the cursor jumps to its position and zsh presents all matches.

**Comment by bkudria** [comment]
This would be a killer feature to have.

**Comment by pickfire** [comment]
I would switch `fish` if only it has this function, a vi-mode and a better default theme. All of it was because `zsh` with framework need almost 2 second to startup.

**Comment by GuillaumeLeclerc** [comment]
@pickfire fish already have a vi-mode. But I'm still waiting for this path expansion feature

**Comment by pickfire** [comment]
@GuillaumeLeclerc But I still can't see it in `fish_config`.

**Comment by GuillaumeLeclerc** [comment]
@pickfire just add `fish_vi_mode` into your `~/.config/fish/config.fish`. If it is still not working just pick the last version of fish and build it :)

**Comment by pickfire** [comment]
@GuillaumeLeclerc Thanks, I had correct it. But I think adding an option in the `fish_config` to change it so it would not brake [**The Law of Discoverability**](http://fishshell.com/docs/current/design.html#disc).

**Comment by ridiculousfish** [comment]
This is mostly implemented as 3a3a9f5cc15ccfc9f171f8916c5a0470a3585319 . It can do "fuzzy intermediate matching" so that e.g. `cd /u/l/b<tab>` works. However if there is ambiguity the behavior isn't yet ideal (it may erase part of your entry).

**Comment by amir20** [comment]
For anybody who is wondering how to get this to work, you should install HEAD. With brew I did `brew reinstall fish --HEAD`

**Comment by faho** [comment]
This is essentially implemented, any issues with it should be reported separately and then fixed. Closing.
