### ISSUE TITLE
Feature Request: Rotating History

### ISSUE THREAD

**Issue by X4** [fish-shell/fish-shell#940]
Hi,

it would be nice to have rotating history files and an option to intelligently merge the most used commands into a .fish_smarthistory.

Removing stuff that repeats or caused an error exit status from the .fish_smarthistory file. And archiving and compressing the oldest history files into a .fish.d directory or so.

**Comment by krader1961** [comment]
Is there any reason to not close this issue? The proposal appears to have been made based on a misunderstanding of how fish manages its history file and would add significant complexity that very few people would find useful.

**Comment by ridiculousfish** [comment]
Ok, let's close
