### ISSUE TITLE
Kitty: entered command gets broken down into multiple lines

### ISSUE THREAD

**Issue by azuenko** [fish-shell/fish-shell#9409]
Hello,

I initially opened the issue in [Kitty's repo](https://github.com/kovidgoyal/kitty/issues/5762), but Kovid suggested it could be on fish side.

In Kitty, when an entered command is larger than terminal width, it gets wrapped. However, it looks like it's wrapped with newlines, and therefore not considered by Kitty as a single line. This behaviour is best demonstrated when Kitty's window size is changed: 

**To reproduce**

1. Run Kitty & Fish with default settings: `kitty -c NONE -o shell='fish --no-config'`
2. Resize Kitty window and make it narrow enough
3. Enter a command, long enough to make it wrap, run it
![image](https://user-images.githubusercontent.com/7202664/207026515-b38d1d57-947b-49fa-a40e-3c97b933a312.png)

4. Resize the window back to make it wide enough

![image](https://user-images.githubusercontent.com/7202664/207026571-833973f9-aecd-4b24-83ba-c23ea6ad0aeb.png)

5. Observe how fish error message is wrapped correctly, but not the entered command

**Notes**

The issue is only observed with Kitty & Fish. No problems with Kitty & Zsh, neither with Alacritty & Fish.

**System info**

```
> fish --version
fish, version 3.5.1
> echo $version
3.5.1
> uname -a
Darwin azmac.local 20.6.0 Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64 x86_64
> echo $TERM
xterm-kitty
```

```
kitty 0.26.2 created by Kovid Goyal
Darwin azmac.local 20.6.0 Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64 x86_64
ProductName:	macOS ProductVersion:	11.6.8 BuildVersion:	20G730
Frozen: True
Paths:
  kitty: /Applications/kitty.app/Contents/MacOS/kitty
  base dir: /Applications/kitty.app/Contents/Resources/kitty
  extensions dir: /Applications/kitty.app/Contents/Resources/Python/lib/kitty-extensions
  system shell: /bin/zsh
Loaded config overrides:
  shell fish --no-config

Config options different from defaults:
shell fish --no-config

Important environment variables seen by the kitty process:
	PATH                                /Applications/kitty.app/Contents/MacOS:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/fzf/bin
	LANG                                en_US.UTF-8
	SHELL                               /bin/zsh
	USER                                az
	LC_CTYPE                            UTF-8
```

**Comment by faho** [comment]
Fish 3.5.1 turns off automatic rewrapping when run inside kitty, because we were informed that it would be doing it.

You probably want to turn it back on, set $fish_handle_reflow to 1: `set -g fish_handle_reflow 1`. This tells fish to rerender the prompt when it gets a SIGWINCH.

**Comment by azuenko** [comment]
Hello @faho , thanks for pointing it out. 

I quickly checked my terminfo, I've exactly the same terminal capabilities as you. The `allow_soft_wrap` returns `true` and looks like fish tries to do the best to perform the soft wraps.

I used `script` to record the output of fish. I compared Fish in Kitty and standard macos Terminal app. The output is exactly the same, bit perfect. Terminal understands well the sequences generated by Fish and correctly wraps the line. But Kitty unfortunately does not get the soft wraps...

Here is what I've found, hope it could be useful.

The terminal window is 20 columns wide. Colours are disabled. I enter `x` symbols in the command prompt:

* Cursor at position 18 (counting from 0), it remains 2 empty places on the first line.
* I enter `x`, fish yields `0x78 0x0d 0x1b 0x5b 0x31 0x39 0x43`, which translates to `x \r ESC[19C`: put `x`, carriage return, put cursor in the (last) column 19.
* I enter `x`, which takes the last 20th place on the first line. The cursor moves to the second line. Fish yields `0x78 0x0d 0x0d 0x0a`, which is `x\r\r\n`
* I enter `x`, it is the first `x` on the second line. Fish now yields `0x1b 0x5b 0x41 0x1b 0x5b 0x31 0x38 0x43 0x78 0x78 0x78 0x1b 0x5b 0x41 0x0d 0x0d 0x0a 0x1b 0x5b 0x43`, which is `ESC[A ESC[18C xxx ESC[A \r\r\n ESC[C`. I suspect the code that generates these three `x` is [this one](https://github.com/fish-shell/fish-shell/blob/master/src/screen.cpp#L797-L813).

On subsequent entries, Fish yields something like put x, arrow up key, new line, set column. 

Looks like Kitty has hard time to understand the sequences produced by Fish. I'm not an expert to judge whether it's Kitty of Fish, but there's definitely something to fix here.

**Comment by ridiculousfish** [comment]
Kitty appears to break soft-wrap when the cursor moves up into a line, then down into the next line by emitting a newline (which is the typical value of `cursor_down`). No other terminal I tried behaves this way. I have a reduced test case, I will share it.

**Comment by azuenko** [comment]
Thanks @ridiculousfish  for reducing the test case and having it reported back to kitty!

**Comment by faho** [comment]
Unfortunately, the solution the kitty maintainer recommends ("cud" instead of "cud1") doesn't work.

It won't push down the cursor if it is at the end of the screen. I'm sure the kitty people would like us to query the position, which is unacceptable for us (because it might involve a long round-trip or even awkward strings being printed on screen).

So I don't believe this is fixable on our end.

**Comment by kovidgoyal** [comment]
Nope, I dont want you to query the position. I want you to follow the terminfo documentation, which clearly states that if you want to scroll lines you use ind not cud1.  And that cud1 must not in fact alter text in anyway. Not to mention that you dont need to scroll lines when drawing a prompt, you just draw the prompt and if the line is longer than the screen width then the screen is wrapped and the screen gets scrolled automatically, if needed. Once you finish drawing the prompt you move the cursor around, though even then you would only need to move it upwards not downwards. And for this movement you use the cursor movement control, which is cud not cud1.

Quoting man terminfo, with the relevant parts bolded:

> If  there is a code to move the cursor one position to the left (such as backspace) that capability should be given as cub1.  Similarly, codes to move to the right, up, and down should be given as cuf1, cuu1, and cud1.  **These local cursor motions should not alter the  text  they pass over**, for example, you would not normally use “cuf1= ” because the space would erase the character moved over.
> 
> A very important point here is that the local cursor motions encoded in terminfo are undefined at the left and top edges of a CRT terminal.  Programs should never attempt to backspace around the left edge, unless bw is given, and never attempt to go up  locally  off  the top.  **In order to scroll text up, a program will go to the bottom left corner of the screen and send the ind (index) string.**

**Comment by mqudsi** [comment]
Without getting into any debate about what or who is right or wrong here, I believe it's now "fixed" upstream as far as fish is concerned with https://github.com/kovidgoyal/kitty/commit/68cf9f7514eb3a0c3cb269111916c1908dbf0afe.
