### ISSUE TITLE
"abbr: Cannot combine options add, show"

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#9410]
Using https://github.com/fish-shell/fish-shell/commit/d14b4b96f09124b272effc40caf55887a9316868

---

On launching fish, I get the following error:

```
abbr: Cannot combine options add, show                                          
Assertion failed: (woptind <= argc && "woptind is out of range"),
function wgetopt_long, file wgetopt.cpp, line 432.
```

**Comment by krobelus** [comment]
what's the command to trigger this?

**Comment by zx8** [comment]
How can I figure it out? Fish crashes instantly on launch.

**Comment by krobelus** [comment]
run like `fish_trace=1 fish 2>trace`

**Comment by zx8** [comment]
Seems to be:

```
abbr -a gss git show -s
```

If I quote this like:

```
abbr -a gss "git show -s"
```

The `abbr: Cannot combine options add, show` goes away, but I still get the other error:

```
Assertion failed: (woptind <= argc && "woptind is out of range"),
function wgetopt_long, file wgetopt.cpp, line 432.
```

**Comment by krobelus** [comment]
I can reproduce the "cannot combine options", will try to fix
The assertion error I cannot reproduce. I think it's caused by something other than `abbr` but it may crash before execution.

**Comment by zx8** [comment]
Found the abbr that's causing the assertion error:

```
abbr -a tfu terraform force-unlock -force
```

**Comment by krobelus** [comment]
sweet thanks so much. The third one is the same as the first, fix coming soon
