### ISSUE TITLE
abbr: Allow restricting to a specific command's arguments

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#9411]
This is very much a nice-to-have, it does not need to be in the initial release with "Mega abbr".

One of the examples in #9313:

```fish
function git_c
    string match --quiet 'git c ' -- (commandline -j); or return 1
    echo checkout
end
abbr -a git_c --position anywhere --regex c --function git_c
```

This is supposed to allow adding abbreviations for git subcommands. It would be cool if this could be

```fish
abbr --add --commmand git c checkout
```

Which allows us to save the regex, makes for easier and more correct matching and allows arbitrary transformations with arbitrary regexen without marking everything as not-an-error.

(Currently `abbr hahaha --regex '.*' --function false` will cause commands to always be marked as valid because the regex matches and it can't know that the function would fail. This is probably correct - I don't think we can run the function before and marking things as invalid even tho they could still match an abbr feels weird?)

Note that this would always be restricted to a command *argument* - because otherwise the command won't match. I don't think we need to add `--position argument` or require `--position anywhere` just for this. I also don't think we'd need to walk a command's wrap chain (i.e. `function g; git $argv; end` would need to have the abbrs specified again).

**Comment by lgarron** [comment]
I would also really like to see this.

I have a file with git abbreviations that I use heavily: https://github.com/lgarron/dotfiles/blob/a8c29fc157394e699b49f1fd8d37089475c23d64/dotfiles/fish/.config/fish/git.fish

For example:

```fish
abbr -a gcp   "git cherry-pick"
abbr -a gm
abbr -a gr
```

These can take `--continue` and `--abort` commands. So I've also added additional versions: 

```fish
abbr -a gcpa  "git cherry-pick --abort"
abbr -a gcpc  "git cherry-pick --continue"
abbr -a gma   "git merge --abort"
abbr -a gmc   "git merge --continue"
abbr -a gra   "git rebase --abort"
abbr -a grc   "git rebase --continue"
```

However, this doesn't feel like a good general solution — it feels like the first step of a Cartesian explosion.

I'd love to use something like this:

```fish
abbr -a gcp   "git cherry-pick"
abbr -a gm
abbr -a gr

abbr -a con --position anywhere -- --continue
abbr -a ab --position anywhere -- --abort
```

However, this is risky because:

- I can't pass `--position argument`, so `ab` is expanded to `--abort` even though `ab` is a binary in my `$PATH`.
- In general, this is an uncomfortable footgun — these expansions are only limited to a specific subset of `git`, but they can be accidentally applied even if I meant to input files or strings. `con` and `ab` are short but still reasonably likely to be used as codes in computing, while making them any longer would really diminish their convenience.

I would be very glad to restrict these expansions to the `git` command, or ideally to certain subcommands. If the expansion function received the current shell, this might be one way forward, although I acknowledge that this can still produce undesired behaviour if the cursor is in the middle of the command while expanding.

```fish
function con_function
    if $argv[0] = "git" & $argv[1] = "rebase"
        return --continue
    else
        return con
    end
end

abbr -a con --position anywhere --function con_function
```

**Comment by krobelus** [comment]
you can use `abbr --regex`

**Comment by lgarron** [comment]
> you can use `abbr --regex`

I don't see how I can?

> With `--regex`, the abbreviation matches using the regular expression given by **PATTERN**, instead of the literal **NAME**. The pattern is interpreted using PCRE2 syntax and must match the entire token. If multiple abbreviations match the same token, the last abbreviation added is used.

**Comment by krobelus** [comment]
nevermind, I thought that the regex applies to the entire commandline but it doesn't

**Comment by faho** [comment]
Even if you *could* match the entire commandline, writing a regex that properly covers all cases is extremely difficult, if it's possible at all.

You need to cover

```fish
foo "$(bar | command git 
```

but not `ls git`. (we'd only care about *syntactic* commands here, so `sudo git` is out of scope - because `sudo -D git` shouldn't count "git" as a command but `sudo -E git` should)

If you allow the abbr anywhere you can approximate this, but it's still quite difficult - you need `commandline --current-process --tokenize`, and then you need to remove all the decorations (time, command, not, and, or) yourself, and when we add more everyone needs to add them to all their abbreviations.

(also if you allow the abbr "anywhere" that always highlights the abbr as a valid command even tho it won't expand - this is more of a case for a "argument" position of course)

**Comment by faho** [comment]
Note, @lgarron:

> If the expansion function received the current command text

The current command text is available via `commandline`, so you can do

```fish
function con_function
  set -l cmd (commandline -op)
  if [ $cmd[1] = "git" -a $cmd[2] = "rebase" ]
       echo "--continue"
    else
      echo "con"
    end
end

abbr -a con --position anywhere --function con_function

git rebase con[cursor here, press space] # yiss
```

Also, you probably want to `return 1` instead of printing "con" - this allows other abbreviations to be attempted.

Of course it'll be tricky to handle this:

```fish
command git -C /path/to/my/repo rebase con[space]
```

This issue is about making the "command git" part of that easy, the rest essentially *requires* something like we do in the git completions with argparse. You need to partially do the command's argument parsing, at least enough to figure out that `-C` takes an argument and so the `/path/to/my/repo` isn't the subcommand.

**Comment by lgarron** [comment]
@faho Thanks, that's very handy. 😻

All those caveats make wish https://github.com/fish-shell/fish-shell/pull/9412 had landed so I could just do `abbr --command git con -- --continue`, but your code sample makes me feel comfortable enough about being able to use argument completions in some very scoped situations!

**Comment by lgarron** [comment]
> Also, you probably want to `return 1` instead of printing "con" - this allows other abbreviations to be attempted.

Could I ask for help with getting this to work?

This doesn't seem to do the trick:

```fish
abbr -a c "code"

set git_reentrant rebase merge cherry-pick
function _complete_continue
    set -l cmd (commandline -op)
    if [ "$cmd[1]" = git ]
        if contains -- "$cmd[2]" git_reentrant
            echo "--continue"
        else
            return 1
        end
    else
        return 1
    end
end
abbr -a c --position anywhere --function _complete_continue
```

**Comment by faho** [comment]
> Could I ask for help with getting this to work?

This line:

>        if contains -- "$cmd[2]" git_reentrant

Is missing a `$` - `$git_reentrant`.

And this line:

>set git_reentrant rebase merge cherry-pick

should explicitly specify a scope - `set -g`.

**Comment by lgarron** [comment]
Thanks! Sorry, I hadn't finished debugging that part. The bigger problem for me is that this abbreviation does not work, despite your suggested use of `return 1` for the other abbreviation.

> abbr -a c "code"

Is there something else I'm missing, or any other workaround (other than making `_complete_continue` a consolidated logic tree with every completion for `c` that I want under any circumstances)?

**Comment by faho** [comment]
Ah, okay. Run `abbr`. It'll tell you *just*:

```fish
abbr -a --position anywhere --function _complete_continue -- c
```

The first abbreviation is gone. That is because both of these have the same *name* of "c", and so the second call eliminates the first.

The simplest solution is to give the first abbr a different name from what it matches via `--regex`:

```fish
abbr -a code --regex 'c' "code"
```

This *names* the abbr "code" and makes it trigger on "c". (as I understand it regexen are automatically anchored, you can be explicit and make it `'^c$'`)

We could loosen that restriction iff the positions are disjoint - command and "argument", but currently you have "anywhere", which by definition overlaps command position. Also it would complicate `abbr --erase`, which currently takes the name.

**Comment by lgarron** [comment]
Thanks for all the help, @faho!

I was able to create reusable ways to define functions: https://github.com/lgarron/dotfiles/blob/2dfbb3d74aa91bcf7f82aab6e46036b6bc52bd9f/dotfiles/fish/.config/fish/config.fish#L177-L226

Here are the 5 types of abbreviation that I ended up with:

1. Command abbreviation:
  - `g[space]` → `git`
  - `m[space]` → `make`
2. Argument abbreviation where the arg can be in any position:
  - `make b[space]` → `make build`
  - `make clean b[space]` → `make clean build`
3. Subcommand abbreviation:
  - `git m[space]` → `git merge`
4. Argument abbreviation for specific subcommands (allowlisted):
  - `git commit m[space]` → `git commit --message "%"`
  - Shared for re-entrant `git` commands:
    - `git rebase c[space]` → `git rebase --continue`
    - `git merge c[space]` → `git merge --continue`
    - `git cherry-pick c[space]` → `git cherry-pick --continue`
5. Argument abbreviation for specific subcommands (denylisted):
  - Expand `m` to `main` for all `git` subcommands *except* `git commit`:
    - `git checkout m[space]` → `git checkout main`
    - `git log m[space]` → `git log main`
    - `git commit m[space]` → `git commit m ` (returns `1` to allow `fish` to try an allowlisted abbreviation for `git commit m[space]`, like the one shown above)

I'm alright with the tradeoffs and regex workarounds for now, although I'm using namespacing to work around the lack of lexical scope in `fish` and avoid collisions, which can get unwieldy:

```fish
    function _lga_git_sub_commit_message_fn; _lga_define_subcommand_arg_expansion \
        "--message \"%\"" git commit; end
    abbr -a _lga_git_sub_commit_message --regex m --position anywhere --function _lga_git_sub_commit_message_fn \
        --set-cursor
```

I'd love to see more concise ways of doing this, e.g. a way to simultaneously define something resembling the following:

1. `abbr -a g --position command` (already exists!)
2. `abbr -a b --position argument --command make build`
3. `abbr -a m --position 2 --command git merge`
4. `abbr -a c --position anywhere --command git "--continue" --subcommands rebase merge cherry-pick`
5. `abbr -a m --position anywhere --command git main --except-subcommands commit`

This could get rather tricky when working with arguments or subcommands that look like flags, though. In my example, that could possibly be handled by replacing `"--continue"` with `--expansion "--continue"`, where `--expansion` always takes the next argument as its value. And subcommand allow-/denylists could be separated from other arguments using `--` at the end. But I don't know if that works generally enough.

**Comment by faho** [comment]
> abbr -a m --position 2 --command git merge

Numbered positions are, as command argument parsing goes, very often wrong.

`git -C ~/dev/fish-shell merge` is a valid git command. It runs `git merge` in `~/dev/fish-shell`.

That's the biiiiig issue with handling subcommands - the token that determines the subcommand is determined *after* argument parsing, so you need to do the argument parsing, and that's specific to each command. Put it another way the "grammar" depends on the command.

So I think that's a no-go for abbreviations. If you really need that, you should write a function and do the argument parsing with `argparse`.

Or you live with overmatching your abbreviation and simply use ctrl-space to enter a space without expanding it whenever you do need an argument of "m" or "g" (or enter it in quotes).

>abbr -a b --position argument --command make build

For the concrete case of `build` when the command is `make`, the "argument" position isn't very important - if you have a command of "make" you're already not in command position, so "anywhere" ends up doing the same thing.

However I think an argument position might make sense in general, especially because we no longer mark commands as errors if an abbreviation could match.

**Comment by lgarron** [comment]
> `git -C ~/dev/fish-shell merge` is a valid git command. It runs `git merge` in `~/dev/fish-shell`.
> 
> That's the biiiiig issue with handling subcommands - the token that determines the subcommand is determined _after_ argument parsing, so you need to do the argument parsing, and that's specific to each command. Put it another way the "grammar" depends on the command.

Yeah, I'm aware that my solution doesn't handle those cases — I think I'm okay with that for now.
Thanks for helping me understand what I'm getting into though!

> So I think that's a no-go for abbreviations. If you really need that, you should write a function and do the argument parsing with `argparse`.

One of my favorite things about `fish` is that it provides conveniences for entering full commands, without obfuscating the final command. This is especially great for shell history and pair programming, where the expanded command is clearly visible without any hidden tricks. 😄

**Comment by lgarron** [comment]
> * Command abbreviation
> * Argument abbreviation where the arg can be in any position
> * Subcommand abbreviation
> * Argument abbreviation for specific subcommands (allowlisted)
> * Argument abbreviation for specific subcommands (denylisted)

Okay, I figured it out!

https://github.com/lgarron/dotfiles/blob/main/dotfiles/fish/.config/fish/abbr.fish

```fish
abbr_anyarg make b build
abbr_anyarg make c clean

abbr_subcommand git p push
abbr_subcommand git m merge

abbr_subcommand_arg git m "--move" branch
abbr_subcommand_arg git m "--message" commit
abbr_subcommand_arg git c --continue rebase merge cherry-pick

abbr_exceptsubcommand_arg git m main commit
```

The main trick was learning that I could use `$$` to curry function arguments. I had to generated global variables and function names using a counter because closures and anonymous functions are available, but I think the result is pretty reasonable!

**Comment by ismay** [comment]
So to take it back to the original comment:

```fish
abbr --add --commmand git c checkout
```

I would still love to see this implemented. As a user I don't mind that there are edge cases where the abbr wouldn't apply, like the aforementioned `git -C ~/dev/fish-shell m[erge]`. At a certain point you're going to have to understand the inner workings of a command to be able to apply an abbrevation in such cases, and I don't expect fish to have that.

The main timesaver in my opinion is the happy path of the abbr being the first subcommand, which to me applies 99% of the time. Being able to scope an abbr under a specific main command is exactly what I want most of the time. Just having that would be quite an improvement, especially if you compare it to the way it currently has to be implemented by the user.

**Comment by ismay** [comment]
I see https://github.com/fish-shell/fish-shell/pull/9412 was closed and added to will not implement. I was wondering why. To me this would resolve so much complexity and hacky solutions that everyone would have to implement themselves.

**Comment by faho** [comment]
@ismay Please read [my comment](https://github.com/fish-shell/fish-shell/pull/9412#issuecomment-1382704225) there.

The approach I used wasn't working properly, so I closed the PR until I (or anyone else) can figure out something better.

Yes, this is still something we would like to add, that's why the issue is still open. There's no need to ask for it again.

**Comment by ismay** [comment]
Thanks for clarifying. I did read your comment btw.

> Closing this for now, I think tok_command isn't the right thing to use here as it'll fail for decorators (command git triggers abbreviations for command, not git). Frankly I'm not sure if it's not broken everywhere, seems like a footgun.

So since the discussion in this issue has sidetracked a little with user-side implementations it would be good to get an idea of the current goals and restrictions.

The point I was trying to make in my earlier comment was that I would consider it a reasonable restriction that `command git ...` would not expand abbreviations passed to git, but instead consider git the subcommand. At least to begin with.

From your comment I gather that you do not want to ship this feature unless it can also deal with decorators? It would not be an option to address the simple usecase first, and the more complex ones afterwards?

**Comment by ismay** [comment]
In thinking about this, how do you feel about this:

```fish
# Would only complete `git c -> git checkout`, but not `decorator git c -> decorator git` checkout
abbr --scope git --position subcommand --add c checkout

# Would complete `git c -> git checkout`, `decorator git c -> decorator git checkout`, but not `decorator c -> decorator checkout`
abbr --scope git --position anywhere --add c checkout
```

This is just to illustrate the idea, the semantics need work (especially the use of the --position flag). But the gist is that the simple case just expands the first subcommand, if both the abbr and the root (i.e. --scope) command match.

The complex case expands the abbr anywhere, as long as it is preceded by the command passed with --scope. Would something in that general direction be worth exploring?

**Comment by faho** [comment]
> From your comment I gather that you do not want to ship this feature unless it can also deal with decorators?

Indeed. In `command git` the command isn't "command" it's "git". Same with `time git` or `exec git` or `and git` or `builtin string` (where the command is "string", not "builtin").

That's table stakes and simply needs to be done. The rest is faffing around to avoid doing that, and I do not believe that's warranted.

**Comment by faho** [comment]
@ismay That is what the opening comment on this issue says, yes.

**Comment by faho** [comment]
Please do read back. I specifically held off on an earlier attempt because of `command git`.

So yes, my next attempt does handle that.
