### ISSUE TITLE
Loop message running help command

### ISSUE THREAD

**Issue by andrew1412** [fish-shell/fish-shell#9413]
Fish version: 3.5.1
OS: Fedora 36
Terminal: Gnome Terminal

I just installed Fish and the first thing I tried was running the help command in the greetings message, then this message is displayed on loop:

![Captura desde 2022-12-13 15-17-02](https://user-images.githubusercontent.com/16086947/207414744-dc20bf1d-486e-43dc-b6ce-7a653a7f3e24.png)

**Comment by faho** [comment]
`help` opens up fish's documentation in a browser. It does so by using xdg-open.

"fixme:ntdll" is a classic *wine* error message.

Your system is configured with Wine's Internet Explorer as its preferred browser.

**Comment by andrew1412** [comment]
I have Librewolf as my default browser on my settings, I don't know what happened, but I put `set BROWSER librewolf` on config.fish and it works

**Comment by faho** [comment]
All I can tell you is that that's what we're doing. Check that it's the same for .html *files*, not just http(s) links - if you have the docs installed we open the files, if you don't we open the URL.

Anyway, since it's working for you now and not something wrong with fish, I'll be closing this.
