### ISSUE TITLE
man pages with same name in multiple sections are not listed in tab completion

### ISSUE THREAD

**Issue by lemmerk** [fish-shell/fish-shell#9415]
fish, version 3.5.1
Linux t15g1 6.0.10-arch2-1 #1 SMP PREEMPT_DYNAMIC Sat, 26 Nov 2022 16:51:18 +0000 x86_64 GNU/Linux
xterm-kitty

---

when i use tab completion for man pages the list of options don't seem to include additional man pages with the same name available in more than one section.

let me illustrate using btrfs man pages as an example:

```
$ ls /usr/share/man/man*/btrfs.*
/usr/share/man/man5/btrfs.5.gz  /usr/share/man/man8/btrfs.8.gz
```

```
$ man btrfs<tab>
btrfs  (5: topics about the BTRFS filesystem (mount options, supported file attributes and other))
btrfsck                                                    (8: check or repair a btrfs filesystem)
btrfstune                                                  (8: tune various filesystem parameters)
btrfs-balance                                      (8: balance block groups on a btrfs filesystem)
...
```

`man 5 btrfs` is shown in the list but `man 8 btrfs` is not listed. to make things more confusing, when accepting `man btrfs` and hitting enter, `man 8 btrfs` is opened by default (at least on my system).

to me it would make sense to list the man pages in the various sections and the completion should then also include the relevant section to avoid the above behaviour.

perhaps this issue has been reported before but i couldn't find any.

**Comment by faho** [comment]
This is almost impossible to do correctly, because it's too different between man implementations and may even be configurable.

For instance here's man from man-db:

```man
The  order  of sections to search may be overridden by the environment variable $MANSECT or by the SECTION directive in /etc/manpath.config.  By default it is as follows:

              1 n l 8 3 2 3posix 3pm 3perl 3am 5 4 9 6 7
```

Here's mandoc:

```man
Within each directory, the search proceeds according to the following list of sections: 1, 8, 6, 2, 3, 5, 7, 4, 9, 3p. The first match found is shown.
```

So we would have to figure out the man implementation (and unfortunately there are more than two and they may change in future), read $MANSECT and parse /etc/manpath.config.

**Comment by lemmerk** [comment]
thank you for the reply.

perhaps i am misunderstanding the answer. i am not suggesting that tab completion picked the wrong man page. i am suggesting that tab completion is incomplete. before moving to fish i used zsh and tab completion for man pages works as follows using my zsh configuration:

```
$ man btrfs<tab>
completing manual page, section 5 (file formats and conventions)
btrfs
completing manual page, section 8 (maintenance commands and procedures)
btrfs                   btrfs-device            btrfs-map-logical       btrfs-replace           btrfs-send
btrfs-balance           btrfs-filesystem        btrfs-property          btrfs-rescue            btrfs-subvolume
btrfs-check             btrfs-find-root         btrfs-qgroup            btrfs-restore           btrfstune
btrfsck                 btrfs-image             btrfs-quota             btrfs-scrub
btrfs-convert           btrfs-inspect-internal  btrfs-receive           btrfs-select-super
```

once a selection has been made, the completion includes the section number `$ man 5 btrfs` or `$ man 8 btrfs` depending on the desired selection. this always seemed like a very good way of showing all relevant man pages and ensuring the correct man page is shown.

**Comment by faho** [comment]
Completion only concerns itself with the current token.

If you do `man 5 btr<TAB>` it'll give you btrfs(5), if you do `man 8 btr<TAB>` it'll give you btrfs(8).

**Comment by poscat0x04** [comment]
This is how zsh's man completion works and is in my opinion much better than fish's current completion
<img width="1016" height="365" alt="Image" src="https://github.com/user-attachments/assets/8a257db0-ad9d-417d-aacd-71bf8a891128" />
I'd like to request for a reconderation on the "will not implement" decision.
