### ISSUE TITLE
Erlang and Elixir don't work

### ISSUE THREAD

**Issue by rikyDeg** [fish-shell/fish-shell#9418]
Fish version: `fish, version 3.5.1`

Operating system MacOS Monterey version 12.6.2  
- `uname -a`:  `Darwin mbr-riky.local 21.6.0 Darwin Kernel Version 21.6.0: Sun Nov  6 23:31:16 PST 2022; root:xnu-8020.240.14~1/RELEASE_X86_64 x86_64`
- `echo $TERM`:  `xterm-256color`

The output of `sh -c 'env HOME=$(mktemp -d) fish'` is empty I don't have third-party plugins.

I have installed Erlang and Elixir using [`asdf`](https://asdf-vm.com/) when I try to run: `iex` or `erl` I have the following error:

For Elixir: 
```
» iex
fish: Job 1, 'iex' terminated by signal SIGBUS (Misaligned address error)
```

For Erlang:
```
» erl
fish: Job 1, 'erl' terminated by signal SIGBUS (Misaligned address error)
```

With other shells those commands work.

**Comment by faho** [comment]
Compare the output of `command -v erl` and `command -v iex` in fish and other shells.

It is quite likely these aren't the same, because what is happening here is that these commands are crashing.

Either that, or it's some awkwardness with macOS' system integrity stuff.

**Comment by rikyDeg** [comment]
Thanks for the answer!

The commands run in different shells return the same results. So probably is some awkwardness with macOS' system integrity stuff, but I can't understand how to fix it!

**Comment by faho** [comment]
I'm afraid I won't be able to help with that as I don't use macOS.

Maybe someone else has an idea.

**Comment by rikyDeg** [comment]
If I run this command `exec /usr/local/opt/asdf/libexec/bin/asdf exec "iex"` from another shell it works on fish I have the following result:

```
» exec /usr/local/opt/asdf/libexec/bin/asdf exec "iex"
Bus error: 10
``` 
and then the fish terminates.

**Comment by faho** [comment]
>and then the fish terminates.

Just to be clear: It doesn't.

At that point, fish is no longer running. `exec` tells it to run the given program *and replace itself*. That is what `exec` does.

`exec sh` means to "become" an "sh" process. `exec asdf` means to "become" an asdf process. (in UNIX, new processes are started by forking the current process and then calling "exec" on a file - with `exec` the shell skips the forking step).

Your asdf crashes as before, with a "bus error 10", which is some form of memory violation, which points to all that awkward signing/integrity stuff that macOS does. Which means either fish doesn't have the correct entitlements or the environment is different causing asdf to do something wrong.

You might want to ask the asdf people.

**Comment by rikyDeg** [comment]
Thanks for the support, now I'm asking in the asdf repository!

**Comment by rikyDeg** [comment]
Ok, I found the problem, it was my fault, I show what I did and maybe can be useful to other people!

I added to `.config/fish/config.fish` file:

```
set -x PATH $PATH:$ANDROID_HOME/emulator 
```

If I remove that line everything works!

Many thanks for the support!
