### ISSUE TITLE
[Feature] Option to show available completions after first tab press

### ISSUE THREAD

**Issue by aristidesfl** [fish-shell/fish-shell#942]
After trying [IPython](http://ipython.org/) I really enjoyed getting the available completions right away after pressing tab the first time, as opposed to having to press tab a second time.

![screenshot](http://imgur.com/3lwV4U0.png)

This issue is for the implementation of such feature plus an option to enable/disable it.

**Comment by krader1961** [comment]
I cannot reproduce this so I'm assuming it has been fixed in the interim.
