### ISSUE TITLE
Custom function with custom help?

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#9428]
How to write a small help inside my functions?

There is the --description part, but is there something to explain what the arguments are?

**Comment by faho** [comment]
See https://fishshell.com/docs/current/language.html#argument-handling

In the simplest case, you just add a `--help` flag and then `echo` your help text:

```fish
function mybetterfunction
    argparse h/help s/second -- $argv
    or return # exit if argparse failed because it found an option it didn't recognize - it will print an error

    # If -h or --help is given, we print a little help text and return
    if set -q _flag_help
        echo "mybetterfunction [-h|--help] [-s|--second] [ARGUMENT ...]"
        return 0
    end
end
```

**Comment by BarbzYHOOL** [comment]
I don't understand the "s/second" part

What is _flag_help and where can I read about it?

**Comment by faho** [comment]
See https://fishshell.com/docs/current/language.html#argument-handling.

This uses fish's [argparse](https://fishshell.com/docs/current/cmds/argparse.html) builtin to separate options from positional arguments.

`argparse h/help s/second -- $argv`

reads from $argv (the function's arguments), and knows about the options `-h`/`--help` and `-s`/`--second`, as simple boolean flags (meaning they have been given or not, they don't have any special arguments). If `-h` or `--help` has been given, it sets the variables `$_flag_h` and `$_flag_help`. If `-s` or `--second` has been given, it sets the variables `$_flag_s` and `$_flag_second`.

The "s/second" part here is simply an example. It's just *another option* so the command does something more than *just* read the help.

`_flag_help` is simply the name you get when you allow a flag called `--help`. You can name it anything you want, you can run `argparse fart` to read `--fart` and it will set a variable called `_flag_fart`.

It is up to you to fill that with meaning - like this example does, where it checks if `--help` was there and then prints usage.

**Comment by faho** [comment]
Question was answered, closing. (if you have any more, of course feel free to ask)

**Comment by BarbzYHOOL** [comment]
thank you
