### ISSUE TITLE
I made a function to quickly open a file under your cursor (while typing)

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#9433]
## Use case

I made this function to be able to open a file in the terminal like we do with alt+w on a function or alt+h on a command
I assigned it to Alt+p and remapped the default alt+p to ctrl+p 
So you're typing `ls /etc/environment` and suddenly you wanna know what is inside, you press Alt+p and you can read it

## Function

```fish
function fish_open_in_pager --description "Open the file under the cursor in the default pager"
    set -l val (commandline -t)

    if test -f $val
        less $val
    else
        ## Beep
        printf \a
    end
    return
end
```
Can replace less by $PAGER, I suppose

**Is it good enough?** actually for me it's good but I am not sure

If you want to use it for anything go on (plugin or fish-shell)

**Comment by faho** [comment]
That's fine. I don't think we need it.

**Comment by krobelus** [comment]
On Sat, Dec 24, 2022 at 01:45:04PM -0800, Barbz wrote:
> I made this function to be able to open a file in the terminal like we do with alt+w on a function or alt+h on a command
> I assigned it to Alt+p and remapped the default alt+p to ctrl+p 
> So you're typing `ls /etc/environment` and suddenly you wanna know what is inside, you press Alt+p and you can read it

we already have a default binding for this:

$ bind \eo
bind --preset \eo __fish_preview_current_file

**Comment by BarbzYHOOL** [comment]
> On Sat, Dec 24, 2022 at 01:45:04PM -0800, Barbz wrote: I made this function to be able to open a file in the terminal like we do with alt+w on a function or alt+h on a command I assigned it to Alt+p and remapped the default alt+p to ctrl+p So you're typing `ls /etc/environment` and suddenly you wanna know what is inside, you press Alt+p and you can read it
> we already have a default binding for this: $ bind \eo bind --preset \eo __fish_preview_current_file

DAMNIT!!! so i had a nice idea but it's already done, i wasted my time :(
the function is more complex, not even sure how it works

Does it take into account $PAGER?

**Comment by BarbzYHOOL** [comment]
Where can I find a list of all fish keybindings? (not testing them one by one then reading the function etc)

**Comment by faho** [comment]
https://fishshell.com/docs/current/interactive.html#shared-bindings and the following two sections.

For the full authoritative list, see [the source](https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_default_key_bindings.fish) (also [the shared bindings](https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_shared_key_bindings.fish). You can also look at these with `type fish_default_key_bindings` and `type __fish_shared_key_bindings`, as they are on your system.

**Comment by BarbzYHOOL** [comment]
there is so much to know about fish lol

thanks faho

**Comment by BarbzYHOOL** [comment]
> On Sat, Dec 24, 2022 at 01:45:04PM -0800, Barbz wrote: I made this function to be able to open a file in the terminal like we do with alt+w on a function or alt+h on a command I assigned it to Alt+p and remapped the default alt+p to ctrl+p So you're typing `ls /etc/environment` and suddenly you wanna know what is inside, you press Alt+p and you can read it
> we already have a default binding for this: $ bind \eo bind --preset \eo __fish_preview_current_file

can you tell me what it does differently than mine? except the bell sound
