### ISSUE TITLE
--on-process-exit option not worked how to fix? 

### ISSUE THREAD

**Issue by woshichuanqilz** [fish-shell/fish-shell#9444]
Here is my function in `config.fish`
```fish
function bye --on-process-exit $fish_pid
  echo touch a file
  touch apple.txt
end
```

But no apple.txt is  touched when I exit the fish shell. 
I search for the whole home directory and not found the `apple.txt`
Why this happens? How to fix?

**Comment by floam** [comment]
That's for children processes.

Use the fish_exit event:

```fish
function bye --on-event fish_exit 
    echo touch a file
    touch apple.txt
end
```
