### ISSUE TITLE
argparse does not delete seen arguments from a list

### ISSUE THREAD

**Issue by 9seconds** [fish-shell/fish-shell#9446]
Let me cite man for argparse:

> If $argv is empty then there is nothing to parse and argparse returns zero to indicate success. If $argv is not empty then it is checked for flags -h, --help, -n and --name. If they are found they are removed from the arguments and local variables called _flag_OPTION are set so the script can determine which options were seen.

While `_flag_OPTION` works fine, I can't get argument removal from arguments list. Here is what I'm trying to do:

```fish
set -l params -h -h -h  1 2 3

argparse -s 'h/help' -- $params
or return 1

echo -- $params
```

If I run this script, I get `-h -h -h  1 2 3`. What I want to achieve is to have all seen options popped up from a list. So, `1 2 3`.

Is it a bug or I misunderstand something?

Fish version is 3.5.1

**Comment by faho** [comment]
This is a misunderstanding.

Argparse always leaves the remaining arguments in $argv, and $argv specifically.

**Comment by 9seconds** [comment]
Thanks!
