### ISSUE TITLE
Delete an entry from Ctrl-R history

### ISSUE THREAD

**Issue by lgarron** [fish-shell/fish-shell#9454]
https://github.com/fish-shell/fish-shell/issues/5791 and https://github.com/fish-shell/fish-shell/commit/049104e8df02a989e3c0ad70d2521251192013cd have made it a lot nicer to work from history.

I'd love to see this go one step further, by allowing a history entry to be deleted from the `Ctrl`-`R` history pager. For example, something similar to Chrome's autofill/omnibox dropdowns, where you can type `Shift`-`Del` to delete the currently selected dropdown item.

This would make it super practical to delete a recent item from history if you accidentally pasted a password, without having to clear any more than necessary:

- Ctrl-R
- Down key a few times
- Shift-Del

It would also bring the history page up to feature parity with the `fish_config` UI, which has exactly two clear features: search all items, and delete any single item.

<img width="1019" alt="Screenshot 2023-01-07 at 15 20 59" src="https://user-images.githubusercontent.com/248078/211173805-cb451c2a-bd46-43d6-bf13-3e4db0ef6796.png">

fish 3.6.0
macOS Ventura 13.1

(previously suggested in https://github.com/fish-shell/fish-shell/pull/9089#issuecomment-1199333297)

**Comment by krobelus** [comment]
sounds like a good idea, proposed implementation is in https://github.com/fish-shell/fish-shell/pull/9515
Can we make it more discoverable, maybe bind it to Delete? When used accidentally it deletes the command permanently but I don't think that's a huge loss.

**Comment by krobelus** [comment]
@r3a1d3a1 yeah I noticed that as well. I didn't root-cause it yet. It no longer happens with the upcoming https://github.com/fish-shell/fish-shell/pull/10359, at least on a terminal that supports CSI u
