### ISSUE TITLE
msys2 fish-shell invoke cmd error

### ISSUE THREAD

**Issue by wolfand11** [fish-shell/fish-shell#9455]
fish version 3.5.0

when i invoke pyenv command with msys2 fish shell, it's always "Microsoft Windows ......".  when i invoke pyenv with msys bash shell it's ok!

![image](https://user-images.githubusercontent.com/1425676/211251395-52bf5425-6c8f-4fc2-976a-2d9406a9ba5b.png)

![image](https://user-images.githubusercontent.com/1425676/211251679-0660d023-d64b-4adb-84ed-b384412804a8.png)

Finally, i find that invoke cmd command with msys2 fish shell always results "Microsoft Windows ......"
![image](https://user-images.githubusercontent.com/1425676/211252362-94539d66-ce30-455b-a320-078160cb8bba.png)

**Comment by faho** [comment]
The [msys fish package](https://github.com/msys2/MSYS2-packages/blob/master/fish/PKGBUILD) is at version 3.5.1-2, not 3.5.0. You probably upgraded the rest of your system but not fish. Upgrade fish as well.

This is plausible because the error you are getting is

> This problem is probably due to using incompatible versions of the cygwin DLL

**Comment by wolfand11** [comment]
i upgrade my msys. and then upgrade fish use below command:
```shell
pacman -S fish
```
but, it's not work.

![image](https://user-images.githubusercontent.com/1425676/211471210-d20baa98-3653-42f4-8119-ca47ff204c89.png)

**Comment by faho** [comment]
`cmd` is not a fish thing, it's a windows command. Fish simply executes it and gives it its arguments.

Additionally, see #6257 - running .bat files on windows directly (like any other command) doesn't work, we don't know what to do instead.

Frankly, I see the future of fish on windows as WSL, not cygwin/msys.

**Comment by wolfand11** [comment]
@faho  i find a same problem. https://github.com/fish-shell/fish-shell/issues/6257

**Comment by faho** [comment]
If `cmd /c test.bat` fails, you'll want to ask a cygwin person.

The reason running `./test.bat` fails is because fish checks if the file is executable before running it and your system tells us it isn't - bash handles this differently by just blindly running it, and it has special handling for cygwin to run bat files, we don't. Googling said this worked by automatically running `cmd /c foo.bat` if executing failed (similar to how we run /bin/sh), if that's not it I am out of ideas.

I'm going to have to send you to the msys/cygwin people.

**Comment by wolfand11** [comment]
@faho the problem is solved!

replace    'cmd /c "pyenv --version" '  with   'cmd //c "pyenv --version" '

![image](https://user-images.githubusercontent.com/1425676/211961171-1b302f1b-221d-4169-ab13-89e0240615be.png)

- https://superuser.com/questions/526736/how-to-run-internal-cmd-command-from-the-msys-shell
