### ISSUE TITLE
Custom git command completion seems to be broken in 3.6

### ISSUE THREAD

**Issue by jaminthorns** [fish-shell/fish-shell#9457]
The new 3.6 release is fantastic! Upon upgrading, though, I noticed that completions for my custom git commands are no longer working. I have a few commands that augment certain git commands, and I get completions for them by wrapping their corresponding git commands using the `-w` flag (previously discussed [here](https://github.com/fish-shell/fish-shell/discussions/8831)). I have these completions set in a `conf.d` file:

```fish
complete -c git-branches -w "git branch"
complete -c git-branches -s o -l graph-options -d "Options for the 'git graph' view"

complete -c git-compare -w "git diff"
complete -c git-compare -s p -l path -d "Show only changes from specified path"

complete -c git-history -w "git log"
complete -c git-history -s p -l path -d "Show only commits and changes from specified path"
complete -c git-history -s o -l show-options -d "Options for the 'git show' view"

complete -c git-stashes -w "git stash"
complete -c git-history -s o -l stash-show-options -d "Options for the 'git stash show' view"

complete -c git-view -w "git show"
complete -c git-view -s p -l path -d "Show only changes from specified path"
```

These completions don't seem to work at all anymore. My guess is that it might be due to [the recent change for caching commands in `share/completions/git.fish`](https://github.com/fish-shell/fish-shell/commit/842af06c5d7aa3aeb4cfbee6272661856048714c).

**Comment by faho** [comment]
>My guess is that it might be due to [the recent change for caching commands in share/completions/git.fish](https://github.com/fish-shell/fish-shell/commit/842af06c5d7aa3aeb4cfbee6272661856048714c).

Nope, it's down to us expecting `git git-branches´, not `git branches`. Broken in f5711ad5edb9fa82a37c528453f004d1bcc273d8.
