### ISSUE TITLE
`ctrl-r` does not work with vi keybindings

### ISSUE THREAD

**Issue by AminurAlam** [fish-shell/fish-shell#9459]
fish version: 3.6.0

### expected behaviour
pressing `ctrl-r` opens up command history

### actual behaviour
pressing `ctrl-r` does nothing

### how to reproduce the issue
put the command `fish_vi_key_bindings` in your config

### how to fix
manually adding the binding in the config

`bind -M insert \cr 'commandline -f history-pager'`

**Comment by faho** [comment]
In the vi bindings this is bound to `/` in normal mode, ctrl-r is redo. This is mentioned in the documentation: https://fishshell.com/docs/current/interactive.html#command-mode
