### ISSUE TITLE
Add relative paths with fish_add_path

### ISSUE THREAD

**Issue by danrot** [fish-shell/fish-shell#9463]
I would like to use the `fish_add_path` command to register some paths in my dotfiles, which works quite well so far. However, in order for my tooling to be setup correctly I rely on some relative paths like `node_modules/.bin`. This worked great for me, however, it seems like adding a path like this using `fish_add_path` will make the path absolute as described in the [documentation](https://fishshell.com/docs/current/cmds/fish_add_path.html), which is not why I want. So I am wondering if it would be possible to add an option which would not make the path absolute, so that I can configure my setup as I am used to.

Version information:

```
danielrotter@Daniels-MBP ~ $ fish --version
fish, version 3.5.1
danielrotter@Daniels-MBP ~ $ echo $version
3.5.1
danielrotter@Daniels-MBP ~ $ uname -a
Darwin Daniels-MBP.fritz.box 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64

```

**Comment by faho** [comment]
I don't want to enable fish_add_path to easily do something I consider dangerous. It's a simple command to make the common case easy, it doesn't have to cover everything.

I told you how to do it yourself, so I'm closing!
