### ISSUE TITLE
[macOS] Unable to go into Downloads folder

### ISSUE THREAD

**Issue by indietyp** [fish-shell/fish-shell#9466]
* fish version: `fish, version 3.5.1`
* operating system: macOS Ventura 13.1
* term: kitty

This is a very weird bug that I have been experiencing for quite some time now, this happens in every terminal emulator I tried.

Whenever I try to access the `Downloads/` folder, I get:

```
cd: Interrupted system call
cd: Unknown error trying to locate directory 'Downloads/'
```

but this isn't the case always, sometimes, if I accessed the folder, I am able to access the `Downloads/` folder for a bit, until encounter the error again. 
I can access the folder by creating a subshell (either via `fish`, `zsh`, or `bash`) going into the `Downloads/` folder, and then exiting. I am then able to access the folder.

This only happens in the fish shell, but I do not know if fish is the underlying cause for the issue.

Thank you for looking into the issue!

**Comment by faho** [comment]
> cd: Interrupted system call

This error means either [open(2)](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/open.2.html) or [fchdir(2)](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/fchdir.2.html) was interrupted by a signal (on linux fchdir isn't documented to return that, and open has some vaguery about a "slow device" like a fifo).

It's also possible that a macOS bug triggers these even if a signal handler with SA_RESTART has been installed (which we do for a few signals) - https://news.ycombinator.com/item?id=25967594 and https://github.com/PostgresApp/PostgresApp/issues/610, and that mentions that antivirus software can trigger the issue.

We could, of course, try restarting these if we get errno == EINTR.

cc @ridiculousfish

**Comment by ridiculousfish** [comment]
@indietyp that's pretty weird! Some questions for you:

1. Is your home directory and/or `~/Downloads` unusual in some way? For example is it an NFS volume, external drive, separate partition, non-APFS filesystem...? Or is this a normal Ventura install?

2. When `cd ~/Downloads` works, is it unusually slow - slower than other directories?

3. It may also be a funny ACL thing - does `xattr -l ~/Downloads` show anything? (`com.apple.macl` is expected, that's it).

4. Does it also happen if you run `command cd ~/Downloads`?

Regarding the proper behavior, we shouldn't unconditionally restart the `cd`, it depends on the signal. If the user tries to `cd` into a slow NFS mount, then we want control-C to cancel that. But I wouldn't expect signals to happen randomly here, I wonder which signal this is.

Please trap all signals by running this:

```
for sig in (trap --list-signals | string split ' ')
       trap "echo GOT $sig" SIG$sig
end
```

and then reproduce the bug, and please report back which signal is printed. Thanks!

**Comment by indietyp** [comment]
To answer some questions:

1. this is just a normal ventura install
2. not noticeable, but running `time` revealed that it is a bit slower (attached below), tho this could very much be in the margin of error.
3. only shows `com.apple.macl`
4. not at all, as shown here in the attached screenshot


I never opened the `Documents/` folder, but apparently, this also happens for it, when executing with the signal traps I got:

```
GOT CHLD
GOT CHLD
GOT CHLD
GOT CHLD
cd: Interrupted system call
cd: Unknown error trying to locate directory 'Documents/'
GOT CHLD
GOT CHLD
GOT CHLD
GOT CHLD
GOT CHLD
```

Maybe this has something to do with "Full Disk Access"? but both my terminal emulator (`kitty`) and `Terminal.app` both have full disk access granted.

Interestingly, my previous "hack", of opening a subshell, navigating to `Documents/` in zsh (which works), and then closing and entering via fish no longer works 🤔 

<img width="421" alt="image" src="https://user-images.githubusercontent.com/7252775/212493404-4e1a68cd-8573-4821-9e78-22b240ddbf4b.png">


<img width="474" alt="image" src="https://user-images.githubusercontent.com/7252775/212493547-edcfca97-49b4-4f13-9a2c-1d6842ea1cb2.png">

**Comment by indietyp** [comment]
Minor update, as this is super weird. This, for some reason, worked?

<img width="375" alt="image" src="https://user-images.githubusercontent.com/7252775/212493765-fa60e0f9-3fe6-4894-8c06-5864b0d24a3d.png">

**Comment by ridiculousfish** [comment]
Very strange. If it works in a clean shell with HOME as a new directory, it suggests something about your config is responsible - you'll have to figure out what.

Some things to look at:

1. Does `functions cd` show the default function ([should look like this](https://github.com/fish-shell/fish-shell/blob/master/share/functions/cd.fish))?

2. Does `echo $CDPATH` show anything?

**Comment by indietyp** [comment]
1. after looking into it, and I do not remember installing it, I had [`oh-my-fish/plugin-cd`](https://github.com/oh-my-fish/plugin-cd) installed, (which, AFAIK, is now redundant with the release of 3.6). This changes the function to the following (attached), but I do not see anything in the code below that would create my error 🤔 
2. `echo $CDPATH` returns nothing.


```fish
# Defined interactively
function cd --description plugin-cd --argument fancy_path

  # private:
  function __fish_cd
    if functions -q __wrapped_cd
      __wrapped_cd $argv
    else
      builtin cd $argv
    end
  end

  function __empty_cd -S
    __fish_cd
    set -l output_status $status

    __update_pwd

    return $output_status
  end

  function __hyphen_cd -S
    __fish_cd $OLDPWD
    set -l output_status $status

    __update_pwd

    return $output_status
  end

  function __fancy_cd -S
    set extract_from_right (echo $fancy_path | sed -n 's/^+\([0-9]*\)$/\1/g p')
    set extract_from_left (echo $fancy_path | sed -n 's/^-\([0-9]*\)$/\1/g p')

    if test -n "$extract_from_right" -o -n "$extract_from_left"
      # Generate current stack
      set -l stack (command pwd) $dirstack

      if test -n "$extract_from_right"
        if test $extract_from_right -gt (math (count $stack) - 1)
          echo "no such entry in dir stack"
          return 1
        end

        set extract_from_left (math (count $stack) - 1 - $extract_from_right)
      end

      if test $extract_from_left -gt (math (count $stack) - 1)
        echo "no such entry in dir stack"
        return 1
      else
        if test $extract_from_left -gt 0
          set stack $stack[(math $extract_from_left + 1)] $stack
          set -e stack[(math $extract_from_left + 2)]
        end

        # now reconstruct dirstack and change directory
        set -g dirstack $stack[2..(count $stack)]
        __fish_cd $stack[1]
        set -l output_status $status

        __update_pwd

        return $output_status
      end
    else
      set -l normal_path (echo $fancy_path | sed -e 's@^\.$@:@;s@^\.\([^\.]\)@:\1@g;s@\([^\.]\)\.$@\1:@g' -e 's@\([^\.]\)\.\([^\.]\)@\1:\2@g' -e 's@\([^\.]\)\.\([^\.]\)@\1:\2@g' -e 's@\.\{2\}\(\.*\)@::\1@g' -e 's@\.@\/\.\.@g' -e 's@:@\.@g')

      __fish_cd $normal_path
      set -l output_status $status

      __update_pwd

      return $output_status
    end
  end

  function __update_dirstack -S
      if contains $old_pwd $dirstack
        # If the from directory is existed in stack, remove it
        set -e dirstack[(contains -i $old_pwd $dirstack)]
      end
      # Add the from directory to the head of stack
      set -g dirstack $old_pwd $dirstack

      if contains (command pwd) $dirstack
        # If the to directory is existed in stack, remove it
        set -e dirstack[(contains -i (command pwd) $dirstack)]
      end
  end

  function __update_pwd -S
    if test $old_pwd != (command pwd)
      set -xg OLDPWD $old_pwd
      __update_dirstack
    end
  end

  # body:
  set -l old_pwd (pwd)

  switch "$fancy_path"
    case ''
      __empty_cd
    case '-'
      __hyphen_cd
    case '*'
      __fancy_cd
  end
end
```

(`__wrapped_cd` is defined and has the same code you referenced)

**Comment by indietyp** [comment]
Once I have acquired the permissions, I can access the specified folder (`Downloads/` or `Documents/`) until I restart my laptop.

<img width="615" alt="image" src="https://user-images.githubusercontent.com/7252775/212501135-0569d737-8a64-4b4b-9d3f-030045aba1dc.png">

also, now this is where things get weird. Nothing deactivated, just a normal fish subshell:

<img width="495" alt="image" src="https://user-images.githubusercontent.com/7252775/212501226-e6b4eaf2-46ab-40ed-b084-17a314800776.png">

**Comment by ridiculousfish** [comment]
When this reproduces, does `/usr/bin/cd ~/Downloads` print an error?

Are there any interesting entries related to Kitty or other terminals in System Preferences -> Privacy & Security -> Files and Folders? (This is separate from Full Disk Access)

**Comment by indietyp** [comment]
No, `/usr/bin/cd ~/Downloads` does not print an error, but once executed `cd ~/Downloads` works fine. 🤔 

There is nothing out of the ordinary in the Files and Folders entry for kitty or terminal, just Full Disk Access.

**Comment by asportnoy** [comment]
Upgrading from 3.5.1 to 3.6.0 fixed this for me. Not sure if it's a coincidence or a fix from that version.

**Comment by ridiculousfish** [comment]
Thanks, I'm out of ideas outside of adding debugging code to fish itself, so let's close.

**Comment by yogsototh** [comment]
I had the same issue. Upgrading to 3.6.0 did not help. But I just ran `omf update` and it fixed it.
