### ISSUE TITLE
use open as BROWSER if not set in OSX

### ISSUE THREAD

**Issue by jimhigson** [fish-shell/fish-shell#947]
In osx, the command: 

open file://foo/bar 

passes through to whichever the default browser is. Rather than having the user set the BROWSER variable, it makes sense to use the user's OS-level default browser setting.

**Comment by faho** [comment]
Is there any reason we don't just use our `open` function on OSX as well and then let that use `command open` if applicable? If we did that we could presumably just use it everywhere in fish where we want to... "open" something.

**Comment by zanchey** [comment]
There's not been an answer on this in a long time, and in my tests on OS X it works OK, so I'm going to close this with that intent for now. If you can still reproduce this problem please let us know!
