### ISSUE TITLE
fish_job_summary.fish string trim unknown option error on multiple lines command

### ISSUE THREAD

**Issue by Yutsuten** [fish-shell/fish-shell#9474]
## System info

**Fish version:** 3.5.1
**Arch Linux kernel:** 6.1.4-arch1-1
**Terminal:** alacritty

The issue happens even when starting fish with `sh -c 'env HOME=$(mktemp -d) fish'`

## Steps

Run:

```fish
echo \
-s "Some text that needs to be trimmed" &
```

Output:

```
string trim: -s "Some text that needs: unknown option

/usr/share/fish/functions/fish_job_summary.fish (line 1):
in command substitution
	called on line 35 of file /usr/share/fish/functions/fish_job_summary.fish
in function 'fish_job_summary' with arguments '1 0 echo\ \\\n-s\ \"Some\ text\ that\ needs\ to\ be\ trimmed\"\ \& ENDED'
in event handler: handler for generic event 'fish_job_summary'

(Type 'help string' for related documentation)

fish: Job 1, '' has ended
```

## How I found it

When running `ffmpeg` commands (making it multi-line so it is easier to look/maintain) to re-encode some videos in the background, on command finish `fish` shows the error. Seems that having an option not supported by fish's `string` in the second line and it not starting with spaces (no indentation) triggers the bug.

Probably not needed, but the real life commands that trigger this bug have this format:

```fish
nohup nice ffmpeg -nostdin \
-ss XX:XX:XX -to YY:YY:YY -i video.mp4 \
# more options \
output.mkv &> nohup.log &
```

**Comment by faho** [comment]
Fixed in 3.6.0 by 7f1e9bf57f49eaaa690dc50cdca7448ff4ce0a8.
