### ISSUE TITLE
Are any additional argparse validators planned?

### ISSUE THREAD

**Issue by mattmc3** [fish-shell/fish-shell#9479]
Are there plans to add additional `argparse` validators? As far as I can tell, fish only ships with `_validate_int`. I know users can implement them for themselves, but I think at least a couple more might be commonly used, and helpful to ship with Fish. For example:

- `_validate_file_exists` and its counterpart, `_validate_file_not_exists`
- `_validate_directory_exists` and its counterpart, `_validate_directory_not_exists`
- etc.

While those read nicely, if we dig in a lot of the useful validators would simply be wrappers for `test` functionality, so it might be clever to just provide that instead like so:

```fish
function _validate_with_test --no-scope-shadowing \
    -d "argparse validator for 'test [TEST] FILE'"

    # save test_args
    set -l test_args $argv

    # strip off not operator
    test $argv[1] != "!" || set argv $argv[2..]

    # verify one and only one test operator
    test (count $argv) -eq 1 || return 2

    # argparse file tests
    set -l options 'b' 'c' 'd' 'e' 'f' 'g' 'G' 'k' 'L' 'O' 'p' 'r' 's' 'S' 't' 'u' 'w' 'x'
    argparse -n _validate_with_test $options -- $argv
    or return 2

    # perform test
    if not test $test_args $_flag_value
        set -l msg (_ "%s: Value '%s' for flag '%s' does not pass 'test %s'\n")
        printf $msg $_argparse_cmd $_flag_value $_flag_name "$test_args" >&2
        return 1
    end
end
```

```fish
$ set _flag_value $__fish_conf_dir
$ argparse --name=foo 'f/file=!_validate_with_test -e' -- --file $_flag_value
# success - directory exists
$ argparse --name=foo 'f/file=!_validate_with_test -f' -- --file $_flag_value
# fail! - is a directory, not a regular file
$ argparse --name=foo 'f/file=!_validate_with_test -d' -- --file $_flag_value
# success - is a directory
$ argparse --name=foo 'f/file=!_validate_with_test ! -f' -- --file $_flag_value
# success - is not a regular file
```

One other handy one might be a `string match` regex wrapper - `_validate_string_matches`.

I don't think there's merit in going too crazy adding validators, but I do think at least a few more of these kinds of validators are common enough that they bear discussing inclusion in Fish itself, rather than left as an exercise for the user.

**Comment by faho** [comment]
Tbh, we barely use validate_int, snd I don't think it's worth just implementing and shipping and supporting validators that then wind up unused.

So no, they aren't planned, just write your own.

**Comment by mattmc3** [comment]
I can live with that answer, but let me present one final counter-argument before I drop it. If I implement my own validators and ship a plugin with functions like `_validate_function_exists` and `_validate_directory_exists` and other common names, what's to stop competing implementations from overwriting my functions and changing their behavior - possibly with invalid logic. One (small) advantage of having built-ins is that it keeps projects from trying to protect their validators with unique naming like `_project_foo__validate_directory_exists`.

**Comment by faho** [comment]
One thing:

> argparse --name=foo 'd/directory=!_validate_with_test -d' -- --directory $dir

This is just

```fish
argparse --name=foo 'd/directory=!test -d "$_flag_value"' -- --directory $dir
```

Similarly "function_exists":

```fish
argparse 'f/function=!functions -q "$_flag_value"' -- -f alias
```

You don't *have* to add the function. Which also stops you from having to come up with a name for it, which also neatly stops anyone from stomping on it.

**Comment by mattmc3** [comment]
D'oh! Somehow reading [the docs](https://fishshell.com/docs/current/cmds/argparse.html#flag-value-validation) didn't get me there. Instead of new validators, I think simply a proper examples section in the Flag Value Validation area would have save both of us some time. Thanks, as always, for the assist @faho!
