### ISSUE TITLE
How to restore fish's default variables

### ISSUE THREAD

**Issue by bpinto** [fish-shell/fish-shell#948]
After configuring some terminal colors:
```
set fish_color_autosuggestion normal
set fish_color_command green
set fish_color_comment normal --bold
```

how to restore these variables to their original values?

**Comment by faho** [comment]
Is this still relevant? fish_config now has a "fish default" colorscheme option which I'd imagine solves this.

**Comment by ridiculousfish** [comment]
Yes, let's close. Thanks!
