### ISSUE TITLE
Documentation of shebang should not tell people that fish is in /usr/local

### ISSUE THREAD

**Issue by marcusmueller** [fish-shell/fish-shell#9482]
Independent of fish version, https://fishshell.com/docs/current/index.html#shebang-line says:

> A script written in `bash` would need a first line like this:
> 
>     #!/bin/bash
> 
> When the shell tells the kernel to execute the file, it will use the interpreter `/bin/bash`.
> 
> For a script written in another language, just replace `/bin/bash` with the interpreter for that language (for example: `/usr/bin/python` for a python script, or `/usr/local/bin/fish` for a fish script).

Please don't tell users that! I'd assume (and very much hope) the most common way of installing fish is through package managers, and these don't put shells in /usr/local.

Also, why start with an example for bash, but not even include a complete one for fish?

An appropriate text (which I hereby transfer to Public Domain or license under WTFPL, whatever you prefer, if you want to use it) would be

> If the first line of a script starts with `#!`, the following path tells the operating system which interpreter to use to execute the script. For example, `#!/usr/bin/env fish` can be used to start a script using the `fish` shell installed on your system. You probably have seen this before, for example as `#!/bin/bash`, which uses `bash` (which must be installed into exactly the path `/bin` in this case) to execute the following script. 
> 
> Let's look at an example:
> 
> ```
> #!/usr/bin/env fish
> echo "This is $SHELL, the following feature flags exist:
> status features
> ```
> 
> Saving this text to a file (say, `simplescript`), followed by giving it executable permissions (`chmod o+x simplescript`), allows us to directly run the script, `./simplescript`. Without the shebang line, we would need to manually run `fish simplescript`.

**Comment by faho** [comment]
This is just a basic bit of information, it is *not* intended to be complete or authoritative. It's not actually information about fish, it's *your operating system*. It could interpret $PATH here for all we know.

So, that being said, how about we

1. Note that the interpreter might be installed in a different path
2. Note that `env` might be a better idea

How about:

```rst
For a script written in another language, just replace /bin/bash with the full path to the interpreter for that language. 
If you have fish installed in /usr/local/bin/fish, you could use ``#!/usr/local/bin/fish``. If you have python3 in /usr/bin, you could use ``#!/usr/bin/python3``.

Of course if you pass your script to others, they might not have it installed in the same path,
and so you can use the ``env`` program: ``#!/usr/bin/env fish``. 
This tells your system to start ``env`` (which has a strong convention of being in /usr/bin),
which then looks through $PATH to find fish,
so the script would also work for people who have it in /usr/bin/fish or ~/.bin/fish.
```

>Also, why start with an example for bash, but not even include a complete one for fish?

Simple: Because it doesn't add anything. The bash example tells people that they can execute bash code with this. They already know that fish runs fish script. If anything, a python example would be more useful than a fish one.

**Comment by marcusmueller** [comment]
> Simple: Because it doesn't add anything. The bash example tells people that they can execute bash code with this. They already know that fish runs fish script. If anything, a python example would be more useful than a fish one.

I disagree. A casual, newbie reader will want to know how to make their *fish* script work, not how to make their python work, in the fish documentation. Mental transfer of syntax is easy once you have a feeling for programming languages, but to beginners, *explicitly writing down the simplest example that verifiably works* helps a lot.
