### ISSUE TITLE
__fish_print_help should respect $MANPAGER

### ISSUE THREAD

**Issue by ian-h-chamberlain** [fish-shell/fish-shell#9488]
It seems that builtins' `--help` argument seems to display differently than usual `man` commands:
```sh
# Seems to just use my default $PAGER instead of $MANPAGER
MANPAGER='sh -c "col -bx | bat -plman"' printf --help
```
vs
```sh
# Does what I expect
MANPAGER='sh -c "col -bx | bat -plman"' man printf
```

Since the builtins use the same `man`-style output it would make sense to use `$MANPAGER` first, perhaps falling back to `$PAGER` if unset.

_Originally posted by @ian-h-chamberlain in https://github.com/fish-shell/fish-shell/issues/2170#issuecomment-1387188197_

**Comment by faho** [comment]
Note: `printf` is a bad example because that's actually not supposed to take any options, and we've fixed that in 3.6.0 - #9132.

(ideally we'd do what we do for e.g. `begin --help` and print the help if that's *literally the command*, but that's a bigger thing)
