### ISSUE TITLE
Sticky Fish Prompt Below Background Stdout Output

### ISSUE THREAD

**Issue by iamacarpet** [fish-shell/fish-shell#949]
Hello,

I've been trying to do something with bash that is starting to seem impossible and I'm hoping fish will come to the rescue.

Please see the question asked here: http://serverfault.com/questions/528993/bash-prompt-below-output-background-log-tail

And let me give a simple example:

In a bash shell, run the following command: while true; do echo `date` >> temp; sleep 3; done

Then open your fish shell and run: tail -f temp &

You'll see the output keep scrolling onto the screen, but the fish prompt is left behind and doesn't stick to the bottom of it.

Do you know of any way you could make it stick to the bottom of the output as it appears? And if it's not a current feature, is it something easy to implement?

Thanks.

**Comment by krader1961** [comment]
I should have added a comment when I closed this two months ago. This is out of scope for a shell. There isn't anyway for fish to detect that this is happening. As ridiculous fish noted we would have to introduce a mechanism for piping the output of the command through the shell for display. And you really shouldn't be putting commands in the background that write to the terminal.
