### ISSUE TITLE
commandline -r inside fish_prompt no longer works (v3.6.0)

### ISSUE THREAD

**Issue by markalfred** [fish-shell/fish-shell#9501]
One of my most-used custom functions is this one:

```fish
function repl
  if [ $interactive_mode ]
    # Already in interactive mode. Do nothing.
  else
    set -g interactive_cmd $argv
    set -g interactive_mode true
  end
end
```

It provides the same general functionality as other `repl` packages (e.g. https://github.com/defunkt/repl), but native to the Fish command line. It has always worked like so:

```fish
function fish_prompt
  print '$'
  if [ $interactive_mode ]
    commandline -r "$interactive_cmd "
  end
end
```

This allows me to type `repl git` and every subsequent command will be prepended with `$ git ` automatically. This no longer works, as of v3.6.0, though it may have been broken earlier, it's been about a year since I installed fish.

If there's some better way to get this same functionality, or if this is a complete misuse of `commandline`, I'm happy to change. But this was one of the most useful tools that fish provided for me.

Thanks for making fish, it's been really good to me for years now. ❤️

**Comment by faho** [comment]
Use a fish_postexec event:

```fish
function interactive_mode --on-event fish_postexec
    commandline -r "$interactive_cmd"
end
```

The fish_prompt function definitely isn't the right place for this because we do sometimes execute it again - whenever you do `commandline -f repaint`.

**Comment by markalfred** [comment]
Huge thank you, @faho! You're totally right.
