### ISSUE TITLE
weird characters on tab

### ISSUE THREAD

**Issue by InvisibleRasta** [fish-shell/fish-shell#9503]
What is causing all this weird characters when Tabbing?
 https://asciinema.org/a/eeVzB3ZKtRUO1OvFkvAD8Fq1S

**Comment by InvisibleRasta** [comment]
function descriptions load after they have been run once?

**Comment by faho** [comment]
Those are color escape sequences. Most likely you are using an alias somewhere that does `--color=always` and fish calls in in the completions.

If so, you should stop doing that. Name your alias something else or use `--color=auto`.

**Comment by InvisibleRasta** [comment]
that is exactly what it was. ..i was going nuts.. there is alot of new things i have to watch out with the switch im doing from zsh to fish
