### ISSUE TITLE
Is it possible to disable the vendor directories?

### ISSUE THREAD

**Issue by samuelwagen** [fish-shell/fish-shell#9504]
fish, version 3.6.0

I'm trying out Fish as a possible replacement to my hand-rolled Zsh configuration, and I'm running into some issues.
Is it possible to configure fish to **not** load the vendor directories? I'd prefer to have a more deterministic control over what gets loaded into my shell, especially on shared machines.

As it is, on a shared machine we have installed the Direnv package, which adds a function to the /usr/share/fish/vendor_conf.d/ that enables Direnv. I don't use Direnv and it is annoying to see its prompts every time I enter a directory that contains .envrc

Is there a way to configure Fish to not load the vendor directories? I found [this Fish global config](https://github.com/fish-shell/fish-shell/blob/master/share/config.fish#L57) which is where it loads those directories. I don't see a sane way to tell it not to do so, but it could just be my inexperience with Fish.

I basically had 2 annoyances with Fish - the auto suggestions and this. The auto suggestions is now solved with the config knob to turn it off, but this remains.

Thanks.

**Comment by faho** [comment]
The answer here is a simple "no". It is not possible to disable the vendor directories, you'll have to patch fish.

**Comment by faho** [comment]
To be clear: To disable single files, you can always create a file of the same name in your home conf.d.

If you have /usr/share/fish/vendor_conf.d/direnv.fish, and you don't like it, just run `touch ~/.config/fish/conf.d/direnv.fish` and that file will be loaded instead.

**Comment by samuelwagen** [comment]
Thanks. That is a potential security problem for me - direnv adding a vendor function was just an example of a bigger I gues philosophical issue - I'd have to actively notice different behaviour and go hunt down what changed so i can touch a file. That's too much work. Oh well, back to Zsh I go.

Thanks for the fast reply though, appreciated.

**Comment by samuelwagen** [comment]
Btw. there is an earlier place to slot a configuration option, as demonstrated in that very file by the `FISH_UNIT_TESTS_RUNNING` environment variable, which does exactly what I need it to, but using it like that is a hack that is highly not recommended. I'm guessing adding a "canonical" variable to control this would be against the Fish shell goals for perceived simplicity?

**Comment by faho** [comment]
>Btw. there is an earlier place to slot a configuration option

There isn't, not inside fish itself.

>the FISH_UNIT_TESTS_RUNNING environment variable

Yes, that's an *environment* variable. It needs you to run fish from somewhere else where you set it.

>I'm guessing adding a "canonical" variable to control this would be against the Fish shell goals

Indeed. We don't add configuration knobs for things like this.

This is a case where you don't like your configuration, so you should change it. It's not like anything can write to /usr/share/fish, so this isn't something where constant intervention is required. And typically anything that adds snippets there doesn't do it without reason and *should* be run.

And if something adds awkward snippets, that should be fixed - if direnv is annoying for people who don't use it their config snippet should be changed.

If that's a philosophical mismatch for you then so be it. There are many other shells you can use.

**Comment by samuelwagen** [comment]
> > Btw. there is an earlier place to slot a configuration option
> 
> There isn't, not inside fish itself.

Well yeah, but that's nitpicking. I didn't say it has to be an "inside" knob.

> 
> > the FISH_UNIT_TESTS_RUNNING environment variable
> 
> Yes, that's an _environment_ variable. It needs you to run fish from somewhere else where you set it.

I know, but that's normal. Lots of environment variables get set before you run Fish anyway.

> 
> > I'm guessing adding a "canonical" variable to control this would be against the Fish shell goals
> 
> Indeed. We don't add configuration knobs for things like this.

Fair enough.

> 
> This is a case where you don't like your configuration, so you should change it. It's not like anything can write to /usr/share/fish (it's root-owned, so it'll mostly be the package manager), so this isn't something where constant intervention is required. And typically anything that adds snippets there doesn't do it without reason and _should_ be run.

That's debatable, and should be up to the user to decide whether to ignore or not.

> 
> And if something adds awkward snippets, that should be fixed - if direnv is annoying for people who don't use it that config snippet should be changed (but it doesn't appear to be provided by direnv upstream, so you'd have to talk to your OS vendor or your admin).

Actually it is provided by Direnv itself - see their [Makefile](https://github.com/direnv/direnv/blob/master/GNUmakefile#L150)


> 
> In my practical experience, changes to vendor_conf.d rarely happen, and if they do most of the time I want what they give me. And in the rare case I don't I can just mask it and move on, or report a bug somewhere. In other words I simply don't share your fears.

Not on the same page here, but fair enough. Everyone has different priorities and worldview.

> 
> If that's a philosophical mismatch for you then that's unfortunate. There are many other shells you can use, I hope you find one that suits your needs.

Indeed. I've been very happy with Zsh for over 20 years, so I went back to it. I was curious about Fish, but so far it appears it isn't for me, I am probably too set in my ways, I guess. Fish seems to have many happy users though, so kudos for that!

I'll probably give it another shot in a few years, who knows. E.g. last time I tried it there wasn't a way to turn off auto-suggestions, there is one now. So who knows, never say never ;)
