### ISSUE TITLE
QUESTION - Read line without use interaction

### ISSUE THREAD

**Issue by JanDeDobbeleer** [fish-shell/fish-shell#9508]
As a follow-up of my question in #9507 I was looking for another way to get the information. I'm close to a solution, yet there's one element I can't seem to solve. I have the following function that prints the cursor position using an ANSI escape sequence, yet the read function requires the user to press enter before it is able to read. I want to know if there's a way to get this to work without any user interaction.

```fish
function _set_posh_cursor_position
  echo -ne "\033[6n"
  read -d ';' -l line column # <-- user interaction here, needs to accept this line.
  set --local line (string trim --chars '[' $line)
  set --local column (string trim --chars 'R' $column)
  set --global --export POSH_CURSOR_LINE $line
  set --global --export POSH_CURSOR_COLUMN $column
end
```

**Comment by faho** [comment]
First of all, as a tip: This would have been easier if you had explained from the outset what you want to *achieve*. In #9507 you simply asked for how to use `commandline --line` with no context on what you wanted to use it *for*, and if you had explained that you want to have the current position in the terminal we could have saved an issue.

Anyway, what you are hitting here is that `read` will read until a newline (or a NUL-byte if `-z` has been given). That doesn't really work with the terminal answer for the position, which ends in an "R".

That requires a way to specify an arbitrary stop character for `read`, which doesn't currently exist.

That has been asked for in #6610 (where I explicitly mentioned this use case), so I'm closing this as a duplicate.
