### ISSUE TITLE
New Snap Version of Termius is not Compatible with Fish-shell

### ISSUE THREAD

**Issue by Natgho** [fish-shell/fish-shell#9522]
```bash
ubuntu@hidden ~ [127]>  fish --version
fish, version 3.3.1
ubuntu@hidden ~> echo $version
3.3.1
ubuntu@hidden ~> uname -a
Linux hidden 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```
I am using Ubuntu mate and Termius app.
When I connect SSH to my server (it started from directly fish, I did it with "chsh -s /bin/fish" and it worked) fish is showing this error;
![image](https://user-images.githubusercontent.com/6623948/216015585-3fe9e5c5-b0ae-438f-8881-05c371a44164.png)

**Comment by faho** [comment]
> fish, version 3.3.1

First of all: This fish version is 3 releases out of date. It is missing 14% of all commits ever made to fish. Please upgrade, we offer PPAs at https://fishshell.com/.

Secondly: This is a termius problem. They inject bash-script into the shell, and fish isn't compatible. So you need to open a bug there to tell them not to do that. There isn't really anything we can do. Sorry!
