### ISSUE TITLE
Abbreviations are not saved automatically

### ISSUE THREAD

**Issue by steinemann** [fish-shell/fish-shell#9523]
Hi,

I am using :
version : Fish version 3.6.0 ( from official Suse shell repo )
OS: SLES 15.4

When adding an abbreviation with `abbr --add g git` I would expect that the abbreviation is saved and available when I start a new shell.

Unfortunately, the abbreviations are gone when I close the shell.

Any idea what might be wrong ?
Thanks

**Comment by zanchey** [comment]
Please see the [CHANGELOG](https://github.com/fish-shell/fish-shell/blob/master/CHANGELOG.rst#deprecations-and-removed-features-1):

> Abbreviations are no longer stored in universal variables. Existing universal abbreviations are still imported, but new abbreviations should be added to config.fish.

**Comment by TerryTsao** [comment]
Wow, that just cost me two hours. So I understand now we should put our `abbr` inside config.fish, however, fish_config web browser based UI doesn't work any more for me. Is that intended or is there something I'm missing here?

**Comment by DrPhil** [comment]
This wasted some time for me too. It would have been nice if it was more discoverable. Maybe one of:
-  `abbr -U` showed a warning/deprecation message
- `abbr` would warn about the ones already added with the `-U` option that it displays
- the man page for `abbr` could mention that you are intended to save abbreviations manually

The `alias` command has `-s` for saving. It would be consistent for `abbr` to have a similar flag.
