### ISSUE TITLE
Neovim completions should not inherit Vim completions

### ISSUE THREAD

**Issue by bagohart** [fish-shell/fish-shell#9535]
`fish, version 3.6.0`
`Linux 5.15.89-1-MANJARO x86_64 GNU/Linux`

With the upgrade to 3.6.0, the completion for neovim was reinstalled, that I had manually removed some time ago.
So I just removed it again, but this time remembered to create this issue.

The file `nvim.fish` installed to `usr/share/fish/completions` has a single line to ensure that neovim inherits its completions from Vim:
`complete -c nvim -w vim`
On Manjaro, Vim isn't even installed by default, so this doesn't work.

What's worse, the options for Vim and Neovim have diverged over the years.
Here's the output for `vim -h` for Vim 9:
```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Jan 12 2023 11:41:18)

Arguments:
   --			Only file names after this
   -v			Vi mode (like "vi")
   -e			Ex mode (like "ex")
   -E			Improved Ex mode
   -s			Silent (batch) mode (only for "ex")
   -d			Diff mode (like "vimdiff")
   -y			Easy mode (like "evim", modeless)
   -R			Readonly mode (like "view")
   -Z			Restricted mode (like "rvim")
   -m			Modifications (writing files) not allowed
   -M			Modifications in text not allowed
   -b			Binary mode
   -l			Lisp mode
   -C			Compatible with Vi: 'compatible'
   -N			Not fully Vi compatible: 'nocompatible'
   -V[N][fname]		Be verbose [level N] [log messages to fname]
   -D			Debugging mode
   -n			No swap file, use memory only
   -r			List swap files and exit
   -r (with file name)	Recover crashed session
   -L			Same as -r
   -A			Start in Arabic mode
   -H			Start in Hebrew mode
   -T <terminal>	Set terminal type to <terminal>
   --not-a-term		Skip warning for input/output not being a terminal
   --ttyfail		Exit if input or output is not a terminal
   -u <vimrc>		Use <vimrc> instead of any .vimrc
   --noplugin		Don't load plugin scripts
   -p[N]		Open N tab pages (default: one for each file)
   -o[N]		Open N windows (default: one for each file)
   -O[N]		Like -o but split vertically
   +			Start at end of file
   +<lnum>		Start at line <lnum>
   --cmd <command>	Execute <command> before loading any vimrc file
   -c <command>		Execute <command> after loading the first file
   -S <session>		Source file <session> after loading the first file
   -s <scriptin>	Read Normal mode commands from file <scriptin>
   -w <scriptout>	Append all typed commands to file <scriptout>
   -W <scriptout>	Write all typed commands to file <scriptout>
   -x			Edit encrypted files
   --startuptime <file>	Write startup timing messages to <file>
   --log <file>		Start logging to <file> early
   -i <viminfo>		Use <viminfo> instead of .viminfo
   --clean		'nocompatible', Vim defaults, no plugins, no viminfo
   -h  or  --help	Print Help (this message) and exit
   --version		Print version information and exit
```
whereas this is Neovim:
```
nvim

Options:
  --                    Only file names after this
  +                     Start at end of file
  --cmd <cmd>           Execute <cmd> before any config
  +<cmd>, -c <cmd>      Execute <cmd> after config and first file

  -b                    Binary mode
  -d                    Diff mode
  -e, -E                Ex mode
  -es, -Es              Silent (batch) mode
  -h, --help            Print this help message
  -i <shada>            Use this shada file
  -m                    Modifications (writing files) not allowed
  -M                    Modifications in text not allowed
  -n                    No swap file, use memory only
  -o[N]                 Open N windows (default: one per file)
  -O[N]                 Open N vertical windows (default: one per file)
  -p[N]                 Open N tab pages (default: one per file)
  -r, -L                List swap files
  -r <file>             Recover edit state for this file
  -R                    Read-only mode
  -S <session>          Source <session> after loading the first file
  -s <scriptin>         Read Normal mode commands from <scriptin>
  -u <config>           Use this config file
  -v, --version         Print version information
  -V[N][file]           Verbose [level][file]

  --api-info            Write msgpack-encoded API metadata to stdout
  --clean               "Factory defaults" (skip user config and plugins, shada)
  --embed               Use stdin/stdout as a msgpack-rpc channel
  --headless            Don't start a user interface
  --listen <address>    Serve RPC API from this address
  --noplugin            Don't load plugins
  --remote[-subcommand] Execute commands remotely on a server
  --server <address>    Specify RPC server to send commands to
  --startuptime <file>  Write startup timing messages to <file>
```

I autogenerated the completions for Neovim from the manpages, and they are decent.
Therefore, I suggest completely removing the `nvim.fish` file.
I could also add a better `nvim.fish` file myself, but I'm not sure if anyone is happy about that given that the autogenerated completions work fine in this case.

**Comment by faho** [comment]
>With the upgrade to 3.6.0, the completion for neovim was reinstalled, that I had manually removed some time ago.
So I just removed it again, but this time remembered to create this issue.

First of all, you're missing a fundamental fish feature:

Here's what you do whenever you want to use a different (or no) version of a completion script or function:

You create the completions you want, and you put them into ~/.config/fish/completions/nvim.fish. If you don't want any, you can just create an empty file. If it's a function instead, it's "~/.config/fish/functions/whatever.fish"

That is how you properly override completions or functions. This simply works via precedence. When fish looks for the completions it finds your file first and uses it, no matter if the other file is installed.

----

> I'm not sure if anyone is happy about that given that the autogenerated completions work fine in this case

They most likely won't "work fine". For instance the completion for `-t` in the generated version is:

```fish
complete -c nvim -s t -d 'Finds tag in the tags file, the associated file becomes the current file and …'
```

and in the hand-written:

```fish
complete -c vim -s t -xa '(__fish_vim_tags)' -d 'Set the cursor to tag'
```

which not only has a better decsription but actually completes tags from a tag file.

So I would vastly prefer a hand-written file.

**Comment by mqudsi** [comment]
Just seconding what faho said, hard-crafted (or at least hand-finished) completions will always be preferred for the "bread and butter" utilities. 

Incompatible completions are annoying but are not the end of the world, and are far better than no completions at all (or even auto-generated ones). There are still issues with core unix tool completions under BSD w/ incompatible options but we patch them when we get aggravated enough with them to make it worth sitting down and fixing. It's all incremental progress and throwing away what's already there is just taking a giant step back.

**Comment by bagohart** [comment]
Thanks for the explanations. The developer guide explains how to properly write completions, but it doesn't mention the auto-generated vs hand-crafted choice, so if this is a reliable guideline, maybe consider adding a sentence or two about it here:
https://github.com/fish-shell/fish-shell/blob/21026421a04a28f47bdcbbe32c8b62bd00ba640f/CONTRIBUTING.rst

The tag-completion thing looks helpful indeed. If I understand the `vim.fish` completions file correctly, this is the only non-trivial thing, and I can just reference it from `nvim.fish`. So I will try to build an `nvim.fish` that is more suitable than both `vim.fish` and the autogenerated version. 
(However, my main development machine died one hour ago, so it will probably take a while until I get around to implementing it...)
