### ISSUE TITLE
RHEL 9 build

### ISSUE THREAD

**Issue by jhdxr** [fish-shell/fish-shell#9537]
RHEL 9 has been there for months, but it seems the official builds for RHEL still stays with RHEL8 (https://software.opensuse.org/download.html?project=shells%3Afish%3Arelease%3A3&package=fish)

I'm wondering if there is any chance to get RHEL9 builds? Or is there anything blocking the build? Please let me know if there is anything I can help with this. Thanks.

**Comment by faho** [comment]
Basically, the issue is the OpenBuildService doesn't offer a CentOS "Stream" 9 (if that's even binary compatible with RHEL 9). I'm not sure if or when that's planned. Tbh I find the entire stream change quite confusing.

**Comment by jhdxr** [comment]
lol I tried several keywords before I open this issue. But I didn't try the one with *stream*.

Thanks for the info. I also agree that change is quite confusing, personally I switched to rocky linux, but I think there is a lot to go for the whole eco to change.
