### ISSUE TITLE
git `--switch=...` completion issues

### ISSUE THREAD

**Issue by mqudsi** [fish-shell/fish-shell#9538]
Don't have a minute to dig into the git completions 

* `git --exec-path=<TAB>` completes to `git --exec-path=--exec-path=<actual completion>`
* `git branch --set-upstream-to=` has no completions (it only works if not using the `=`-style argument notation)

**Comment by mqudsi** [comment]
Re-opening because I don't think anything was done about the first issue. Thanks for fixing the second though, @faho.

**Comment by faho** [comment]
no it was: c39780f, committed like 5 minutes before

**Comment by mqudsi** [comment]
Thanks, I missed that commit.
