### ISSUE TITLE
Make tab-completion with wildcards make more sense

### ISSUE THREAD

**Issue by ghost** [fish-shell/fish-shell#954]
Example:

```
$ touch file(seq 4)
$ ls
file1  file2  file3  file4
$ echo f*<tab>
```

This autocompletes to `f*ile`. It should autocomplete to `file*` or `file`, imo.

Tab completion with wildcards is pretty awkward at the moment.

**Comment by nakaomote** [comment]
Can definitely +1 on this. It's actually highly misleading:

$ touch (seq 1 9)abc(seq 1 9)
$ ls
1abc1  1abc4  1abc7  2abc1  2abc4  2abc7  3abc1  3abc4  3abc7  4abc1  4abc4  4abc7  5abc1  5abc4  5abc7  6abc1  6abc4  6abc7  7abc1  7abc4  7abc7  8abc1  8abc4  8abc7  9abc1  9abc4  9abc7
1abc2  1abc5  1abc8  2abc2  2abc5  2abc8  3abc2  3abc5  3abc8  4abc2  4abc5  4abc8  5abc2  5abc5  5abc8  6abc2  6abc5  6abc8  7abc2  7abc5  7abc8  8abc2  8abc5  8abc8  9abc2  9abc5  9abc8
1abc3  1abc6  1abc9  2abc3  2abc6  2abc9  3abc3  3abc6  3abc9  4abc3  4abc6  4abc9  5abc3  5abc6  5abc9  6abc3  6abc6  6abc9  7abc3  7abc6  7abc9  8abc3  8abc6  8abc9  9abc3  9abc6  9abc9
wfletcher@purple                                                                                                                                                                                                                                                              
$ ls *abc*7<hit me that TAB key>
*abc*1  *abc*3  *abc*5  *abc*7  *abc*9
*abc*2  *abc*4  *abc*6  *abc*8
