### ISSUE TITLE
Announcement: Fish shell gained it's page in Command Line Interface Pages project

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#9545]
![image](https://user-images.githubusercontent.com/42812113/216902469-5061c0d2-f4a4-4eaa-b37d-ada97832fe27.png)

[Here](https://github.com/emilyseville7cfg-better-tldr/cli-pages) is a repo with all available pages. And [here](https://github.com/emilyseville7cfg-better-tldr/prototypes/tree/main/clip-view) is a render available for them.

**Comment by faho** [comment]
Okay, cool, thanks for letting us know!

I don't believe there is anything for us to do here so I'm closing this.
