### ISSUE TITLE
git add tab completion is slow on MacOS, fish 3.6

### ISSUE THREAD

**Issue by scottwn** [fish-shell/fish-shell#9548]
fish version 3.6.0
MacOS Ventura 13.1

I've been a dedicated Fish user for years, on Mac, RHEL, SUSE, etc., so first of all thank you to everyone who works on this awesome project.

I have a new work laptop using MacOS 13.1. It's an Intel based MacBook Pro. As usual one of the first things I did was install Fish and set it as the default shell. Everything works well just like I'm used to, except `git add` tab completions are very slow, there is a hang for a few seconds after pressing tab. This is the same behavior described in https://github.com/fish-shell/fish-shell/issues/4117, although it seems that was already fixed.

**Comment by faho** [comment]
As we have asked in #4117, please run this:

```fish
# Note: The arguments to `complete -C` are weird - they pretty much need to be given in that exact form
fish --profile /tmp/some_file -c 'complete -C"git add "'
sort -nk 2 /tmp/some_file
```

And give us the output.

**Comment by scottwn** [comment]
[git_add.txt](https://github.com/fish-shell/fish-shell/files/10668611/git_add.txt)

**Comment by faho** [comment]
Please run `time command git --porcelain=2 --ignore-submodules=all -uall`, and try it also with `-uno` instead of `-uall`.

**Comment by scottwn** [comment]
I'm getting `unknown option: --porcelain=2`

**Comment by faho** [comment]
Sorry, I had a typo and edited it right afterwards, it was missing a `status`. Try again:

`time command git status --porcelain=2 --ignore-submodules=all -uall`

**Comment by scottwn** [comment]
```
$ time command git status --porcelain=2 --ignore-submodules=all -uall >> ~/time_uall.txt

________________________________________________________
Executed in  192.89 millis    fish           external
   usr time   57.29 millis    0.17 millis   57.12 millis
   sys time  133.17 millis    1.14 millis  132.03 millis

$ time command git status --porcelain=2 --ignore-submodules=all -uno >> ~/time_uno.txt

________________________________________________________
Executed in   15.07 millis    fish           external
   usr time    5.43 millis    0.17 millis    5.25 millis
   sys time    7.61 millis    1.09 millis    6.52 millis

```

[time_uall.txt](https://github.com/fish-shell/fish-shell/files/10668760/time_uall.txt)
[time_uno.txt](https://github.com/fish-shell/fish-shell/files/10668737/time_uno.txt)
