### ISSUE TITLE
`:` `.` and `[` not in `man` pages.

### ISSUE THREAD

**Issue by IsaacOscar** [fish-shell/fish-shell#9552]
This is the most minor complaint, but going `man :`, `man .`, or `man [` does not give you the fish man pages. I noticed these commands where returned by `builtin --names` and it took me a while to work out what they were. I had to use `help :`, `help .`, and `help [` to get their documentation. (whereas I usually use `man`)

These commands are also not listed in https://fishshell.com/docs/current/commands.html

Also what is the point of `:` ?  Apparently it is an alias for `true`.

**Comment by faho** [comment]
Unfortunately man pages would require that we use the builtin name as a filename, and that causes issues on some systems.

Since this is a very minor issue (these are all compatibility gunk), we choose not to. The help pages are nicer to look at anyway.

**Comment by IsaacOscar** [comment]
I don't know how Bash is doing it, but there is no `:` or `.` file, on my system.

Instead `man :` and `man .` somehow find the file `/usr/share/man/man1/bash_builtins.1.gz`
Which is this:

```
.\" This is a hack to force bash builtins into the whatis database
.\" and to get the list of builtins to come up with the man command.
.\"
.\" File Name macro.  This used to be `.PN', for Path Name,
.\" but Sun doesn't seem to like that very much.
.\"
.de FN
\fI\|\\$1\|\fP
..
.TH BASH_BUILTINS 1 "2021 November 22" "GNU Bash 5.2"
.SH NAME
:, ., [, alias, bg, bind, break, builtin, caller,
cd, command, compgen, complete, compopt,
continue, declare, dirs, disown, echo, enable, eval, exec, exit,
export, false, fc, fg, getopts, hash, help, history, jobs, kill,
let, local, logout, mapfile, popd, printf, pushd, pwd, read,
readarray, readonly, return, set,
shift, shopt, source, suspend, test, times, trap, true, type, typeset,
ulimit, umask, unalias, unset, wait \- bash built-in commands, see \fBbash\fR(1)
.SH BASH BUILTIN COMMANDS
.nr zZ 1
.so /usr/share/man/man1/bash.1
.SH SEE ALSO
bash(1), sh(1)
```

There is however a `/usr/share/man/man1/[.1.gz` file whose contents is merel:
```
.so man1/test.1
```

**Comment by faho** [comment]
On second thought, we can reroute these in our man function.
