### ISSUE TITLE
It appears fish is unrendering certain nerd font ligatures

### ISSUE THREAD

**Issue by mathewf2** [fish-shell/fish-shell#9553]
It seems like fish is unrendering certain ligatures of my nerd fonts. In the first image below the sequence '==>' is not rendering properly in fish. You can see the expected rendering when I switch back to bash. Interestingly, it looks like it flashes the correct rendering briefly, and then unrenders it to the default.

I am using Fira Code nerd font. I have tried different variants of Fira Code, as well as JetBrains Mono and encountered the same issue. This is a mostly fresh install of fish. I changed my prompt and installed OMF as well as starship. I have since uninstalled both OMF and starship and the issue persists.

I am running on WSL in Windows Terminal; I have changed the default Ubuntu color scheme to "One Half Dark".

![image](https://user-images.githubusercontent.com/55362774/217146635-a16cc17b-1999-4cc3-9d6d-0c6f6d80778d.png)

```
~ # ❯❯❯ echo $version
3.6.0
```

```
~ # ❯❯❯ uname -a
Linux Cattlestation 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
~ # ❯❯❯ echo $TERM
xterm-256color
```

![image](https://user-images.githubusercontent.com/55362774/217146838-3356e4d7-30c5-4987-b996-6cd54f08807e.png)

Thanks

**Comment by faho** [comment]
Font rendering is a terminal concern.

In this case my guess is they don't apply the ligatures if there is a color sequence between them, and the place to fix this is your terminal.

Please open an issue there.
