### ISSUE TITLE
Make source on stdin respond to Ctrl-C and other triggers

### ISSUE THREAD

**Issue by ghost** [fish-shell/fish-shell#956]
Running the `source` command doesn't respond to Ctrl-C; it only responds to Ctrl-D if you haven't piped anything to it.

If you run it without a pipe, it simply captures the Ctrl-C as if it's a Ctrl-C that would be sent to the command as it's running, which is... an interesting behaviour, but probably not one that we want.

Simple example: `echo sleep 10 | source` is blocking and can't be stopped with Ctrl-C.

**Comment by mattgodbolt** [comment]
LOL - thanks. Sorry for the spam :)

**Comment by krader1961** [comment]
This looks like yet another quirk of how fish manages jobs.

**Comment by faho** [comment]
The provided example can now be blocked.
