### ISSUE TITLE
Accessing list elements with variably named lists

### ISSUE THREAD

**Issue by srithon** [fish-shell/fish-shell#9562]
```shell
> fish --version
fish, version 3.6.0

> echo $version
3.6.0
```

Hello,

I recently ran into an issue where I wanted to access a list by index, where the name of the list is behind a variable.
For instance:
```fish
set LIST 1 2 3 4
set LIST_POINTER "LIST"
```

I tried the following to get the behavior I want, neither of which worked as intended (my expected output would be "1"):
```fish
> echo $$LIST_POINTER[1]
1 2 3 4
```

```fish
> echo $"$LIST_POINTER"[1]
fish: Expected a variable name after this $.
echo $"$LIST_POINTER"[1]
     ^
```

As it is documented, I believe the first attempt should dereference the result of the value at `LIST_POINTER[1]`. The second attempt is the only way I could think to do what I want: first, dereference the pointer, then substitute the expression result back in and then access the first element.
One workaround I came up with was simply to copy the list into another array with a static name, like this, and then just use `LIST_COPY` instead:
```
set LIST_COPY $LIST
```

However, although realistically it would hardly make a dent in performance, ideally I would like to avoid copying the list if there exists a better solution. I apologize if this is documented somewhere, but is there a way to get the behavior I'm looking for?

**Comment by ridiculousfish** [comment]
[Per the docs](https://fishshell.com/docs/current/language.html#shell-variables):

> `$$foo[$i]` is the value of the variable named by $foo[$i]

In your case:

    > set LIST 1 2 3 4
    > set LIST_POINTER LIST
    > echo $$LIST_POINTER[1]
    1 2 3 4

this will expand `$LIST_POINTER[1]`, which is "LIST"; so it then expands $LIST, yielding 1 2 3 4.

If you want to expand a particular index of $LIST you can use two square brackets:

    > set LIST 1 2 3 4
    > set LIST_POINTER LIST
    > echo $$LIST_POINTER[1][3]
    3

this first expands $LIST_POINTER[1], yielding LIST, then expands $LIST[3], yielding 3.

Does that answer your question?

**Comment by faho** [comment]
The direct link is https://fishshell.com/docs/current/language.html#dereferencing-variables, which discusses this reasonably explicitly.

The underlying confusion is that `$$foo[1]` can either mean "the first element of all variables $foo refers to" or "all elements of the first variable $foo refers to", and we picked the latter.

Since that's directly called out in the docs I'll be closing this. If you have any more questions do of course feel free to ask!
