### ISSUE TITLE
`zig build` completions

### ISSUE THREAD

**Issue by dweiller** [fish-shell/fish-shell#9578]
I have some completions for `zig` that I have written, and some ideas for others and am wondering if they'd be acceptable for a PR. I noticed that there are some default completions, but they have a few issues that I see.

  1.  As `zig` is still developing quite rapidly and options to the compiler change the completions may not match, especially for people following the `zig` master branch closely. Note I haven't actually used the default completions as I initially had an older version of `fish` that didn't have them and wrote my own completions before seeing that there are now default completions in the current version of `fish`, so I don't know how much of a problem this might have been for people.
  2. The default completions do not interact well with the zig build system (i.e. when calling `zig build`) as they only provide completions for default build steps and options.
  
  I think both of these can be address with essentially the same technique - parsing the output of `zig --help` or `zig build --help` to gather completions. I have done this for the `zig build` case and wonder if I should merge this with the current default completions and make a PR.

The standard build runner provides a `--help` flag (so when you run`zig build --help`) that lists all the project-specific options and build steps. The current default completions can not know about any of these, but (in my experience) they are the completions you care about in >95% of the time you're using zig, and not having access to them seems like a problem.
  
There are some potential issues with this approach that I could understand mean you wouldn't want to use this approach however. For those who do not know, the way `zig build` works is that it compiles a builder executable for the project you're in (if a cached version is not available) and then executes it. The issue is that the builder executable is essentially an arbitrary program defined by the projects `build.zig`. The standard build runner compiled by `zig build` is fixed (though there is a command line flag that lets you replace it) but it calls a `build()` function provided by a projects `build.zig` file (which again can be changed by another CLI flag) that could do whatever it wants, so there is no way to guarantee that it either compiles or executes quickly.

In practice I don't think there will really be a problem with this approach. Any builder that isn't actively malicious is going to execute resonably quickly when given the `--help` flag (though for the zig compiler repo `time zig build --help` on my system take ~234ms which I'm sure is too long for some) and it will only only be recompiled after the `build.zig` file (or a dependency it has) is changed, the user changes the version of Zig they are using or the user manually delete Zig's compilation cache. It would be possible to detect whether a non-standard build runner or build file is being used and pass along those flags (assuming that the custom build runner mimics the behaviour of the `--help` flag).

So, would a PR that runs `zig build --help` to get completions be acceptable or not?

**Comment by zanchey** [comment]
Would it be better to maintain the zig completions in the zig source if they are changing that much?

**Comment by dweiller** [comment]
> Would it be better to maintain the zig completions in the zig source if they are changing that much?

Possibly - the zig organisation has a repo with bash/zsh completions already.

**Comment by faho** [comment]
Okay I'm going to close this because it appears you want to try submitting to zig upstream first.

If they don't accept it, we'll just accept a PR, no need for a separate issue.
