### ISSUE TITLE
Config/variable for enabling `.*` tab completions by default

### ISSUE THREAD

**Issue by ian-h-chamberlain** [fish-shell/fish-shell#9597]
_Originally posted by @ridiculousfish in https://github.com/fish-shell/fish-shell/issues/3707#issuecomment-271119234_:
> This is by design. The default file completion will only show hidden files if your argument starts with a `.` After all, hidden files should be hidden.
> 
> We wouldn't introduce a config option for this.

Is there a specific reason this wouldn't be considered as a config option? Personally I'd really like to have all file completions _include_ "hidden" dot-files, and as far as I can tell it would only affect user interaction (tab-completion) so I wouldn't expect there to be a scripting-related reason not to make this configurable.

Can I ask for a re-consideration of this and propose it as a feature request? Thanks in advance.

**Comment by faho** [comment]
> Is there a specific reason this wouldn't be considered as a config option?

Yes: We don't do those.

**Comment by ian-h-chamberlain** [comment]
Okay, that's disappointing but I guess I can understand the reasoning behind this decision. 

Perhaps an alternative more in line with the design philosophy would be a function that could be overridden, but comes with a default implementation for the current behavior (similar to e.g. `fish_prompt`, `fish_greeting` etc.)? Something like

```fish
function fish_complete_files -a prefix
    printf '%s\n' $prefix*
end
```

Still, I'd imagine this would take a fair bit of effort to drop into the existing completion implementation, so I can understand if the effort/benefit ratio still doesn't make sense for this case.

Is there any kind of workaround I might be able to try to get the behavior I'm looking for, short of re-implementing file completions from scratch and using `complete --no-files` on every command I ever use?

**Comment by faho** [comment]
>Perhaps an alternative more in line with the design philosophy would be a function that could be overridden, but comes with a default implementation for the current behavior (similar to e.g. fish_prompt, fish_greeting etc.)?

I don't see this as a big customization point. For example, *excluding* files based on extension or similar is extremely tempting here, but always wrong. Imagine ignoring editor backup files, and then you need to `rm` them.

Plus the current file completions do a bunch that's not easily replicated in script.

>Is there any kind of workaround I might be able to try to get the behavior I'm looking for, short of re-implementing file completions from scratch and using complete --no-files on every command I ever use?

Nothing springs to mind, sorry.

**Comment by dancojocaru2000** [comment]
This is needlessly annoying. Even more so when config files used by common tools often start with a dot. And it's even more irritating when a directory only contains files that start with a dot and the completion just does nothing.

fish should at least say that there are dotfiles it isn't showing, in order to hint that typing a `.` will show more files. But, ideally, fish should just show files that contain dots too, or at least have an option to do that.
