### ISSUE TITLE
Vet and consider including interesting changes from fish-next

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#96]
fish-next is a branch dating from 2010 with some interesting-looking changes. This bug tracks inspecting its commits and evaluating which ones are interesting and ought to be merged.

To see which fixes are unique to fish-next, run this:

    git log remotes/origin/fish-next "^master" --no-merges

**Comment by zanchey** [comment]
I think this is pretty much finished with?

**Comment by ridiculousfish** [comment]
I think the most interesting bit from this is a009a5f94ae26d17725f11b42d2987f29b379882, which separates event handlers from functions. You instead use a `funcevents` builtin: `funcevents --on-event=BAR_EVENT foo_function` etc.

This is an interesting idea but I think adds more complication without any obvious benefit, so I don't want to merge it now. Closing.
