### ISSUE TITLE
warning: TERM environment variable not set.

### ISSUE THREAD

**Issue by karambaq** [fish-shell/fish-shell#9604]
**YOUR TEXT HERE**
version: 3.6.0

uname: Darwin MacBook-Pro.local 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64

without configuration: yes

reproduce: just open new tab of terminal

```
arning: Could not set up terminal.
warning: TERM environment variable not set.
warning: Using fallback terminal type 'xterm-256color'.
Welcome to fish, the friendly interactive shell
```

My config:

```
if status is-interactive
    set -l onedark_options '-b'

    if set -q VIM
        # Using from vim/neovim.
        set onedark_options "-256"
    end

    set_onedark_color black 14191E 255
    set_onedark $onedark_options

    set fish_greeting
    # set -Ux TERM "xterm-256color"

end

starship init fish | source
```

**Comment by faho** [comment]
The likely explanation for this message is that, in fact, the TERM variable wasn't set.

This is something that your terminal needs to set for the processes it starts, so that they know how to behave. It appears you have misconfigured your terminal so that it doesn't send it along.

**Comment by zanchey** [comment]
What terminal are you using?

**Comment by karambaq** [comment]
@zanchey I'm using iTerm2 terminal. I set it to xterm-256color and it doesn't give me a warning anymore. But now all colors looking off.

**Comment by faho** [comment]
That is the recommended $TERM value for iterm. You might need to check your settings there (I don't think it's normal that you have to set $TERM yourself?), but I'm reasonably sure it's not a fish issue. Fish doesn't change the palette and simply sends the color escape sequences to iterm to display, and will typically detect that it's iterm and decide to send full-24bit RGB sequences.

**Comment by karambaq** [comment]
Ok, thanks.

**Comment by zanchey** [comment]
I'd make sure your terminal settings look like right...

From the menu bar, choose Profiles > Open Profiles, then the Edit Profiles button, then the Terminal tab for the active profile.

Make sure "Report terminal type" is set to "xterm-256color".

Under the Colors tab you might want to choose one of the preferences to reset any custom colours.
