### ISSUE TITLE
file list output by pressing `Tab` key, some are bold but some are not

### ISSUE THREAD

**Issue by xiebruce** [fish-shell/fish-shell#9617]
**YOUR TEXT HERE**
`file --version`
> fish, version 3.6.0

`uname -a`
> Darwin Bruce's MBP 20.6.0 Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64 x86_64

`echo $TERM`
> xterm-256color

Tab list by runing `sh -c 'env HOME=$(mktemp -d) fish'`, it's normal
<img width="723" alt="image" src="https://user-images.githubusercontent.com/13575500/221421046-b72c98ce-c84e-4371-ae49-e4e9f7994b14.png">

Tab list, with my config, some files are not bold, I didn't use any third-party plugin
<img width="724" alt="image" src="https://user-images.githubusercontent.com/13575500/221420992-6548bfbb-588a-42ef-a089-09a517b88421.png">

---

To reproduce my problem, just backup your `config.fish` and `fish_variables` in `~/.config/fish/`, and use mine, then type `ls -l /usr/local/etc/` in your terminal, then press `Tab` key once, then you'll see the problem

My `config.fish`
```bash
if status is-interactive
    set -g fish_prompt_pwd_dir_length 0
    set -g theme_display_user yes
    set -g theme_display_hostname yes
    set -g fish_pager_color_prefix 787878
    set -g fish_pager_color_selected_prefix 787878
    set -g fish_pager_color_completion yellow
    set -g fish_pager_color_selected_completion yellow
    set -g fish_pager_color_background --background=black
    set -g fish_pager_color_selected_background --background=787878
    set -g fish_pager_color_description yellow
    set -g fish_pager_color_progress FFFFFF --background=21C5C6
    set -gx LSCOLORS GxFxCxDxBxegedabagaced
end
```

My `fish_variables`
```bash
# This file contains fish universal variable definitions.
# VERSION: 3.0
SETUVAR __fish_initialized:3400
SETUVAR fish_color_autosuggestion:afafaf
SETUVAR fish_color_cancel:\x2d\x2dreverse
SETUVAR fish_color_command:00ff00
SETUVAR fish_color_comment:FF9640
SETUVAR fish_color_cwd:green
SETUVAR fish_color_cwd_root:red
SETUVAR fish_color_end:FFB273
SETUVAR fish_color_error:FF7400
SETUVAR fish_color_escape:00a6b2
SETUVAR fish_color_history_current:\x2d\x2dbold
SETUVAR fish_color_host:normal
SETUVAR fish_color_host_remote:\x1d
SETUVAR fish_color_keyword:\x1d
SETUVAR fish_color_match:\x2d\x2dbackground\x3dbrblue
SETUVAR fish_color_normal:normal
SETUVAR fish_color_operator:00a6b2
SETUVAR fish_color_option:\x1d
SETUVAR fish_color_param:33CCCC
SETUVAR fish_color_quote:5CCCCC
SETUVAR fish_color_redirection:BF7130
SETUVAR fish_color_search_match:bryellow\x1e\x2d\x2dbackground\x3dbrblack
SETUVAR fish_color_selection:white\x1e\x2d\x2dbold\x1e\x2d\x2dbackground\x3dbrblack
SETUVAR fish_color_status:red
SETUVAR fish_color_user:brgreen
SETUVAR fish_color_valid_path:\x2d\x2dunderline
SETUVAR fish_key_bindings:fish_default_key_bindings
```

**Comment by jack9603301** [comment]
The problem has been tested and the cause is unknown.

**Comment by zanchey** [comment]
Please mention what terminal you are using.

**Comment by xiebruce** [comment]
> Please mention what terminal you are using.

Oh, I'm sorry, I'm using iTerm2.app(Build 3.4.16) on my macOS 11.5.1 (20G80). But I think this is not associate with terminals, because @jack9603301 meet the same problem(He's on Linux, the terminal is not iTerm2)

**Comment by jack9603301** [comment]
@zanchey I agree, my terminal is konsole, we are friends(and @xiebruce ), and we have tested and found that this problem does exist! I don't think it has anything to do with the terminal

**Comment by zanchey** [comment]
OK, I can reproduce with this as a minimum:

```fish
set -g fish_pager_color_completion yellow
set -g fish_pager_color_background --background=black
```

**Comment by lumynou5** [comment]
I have a similar problem: selected one is bold sometimes, and not bold sometimes.

![image](https://github.com/fish-shell/fish-shell/assets/84374077/7cb23bdb-d5b7-47e4-93d6-fcab5d6eb936)

config:
```
fish_pager_color_background
fish_pager_color_completion             normal
fish_pager_color_description            B3A06D
fish_pager_color_prefix                 'normal'  '--bold'  '--underline'
fish_pager_color_progress               'brwhite'  '--background=cyan'
fish_pager_color_secondary_background
fish_pager_color_secondary_completion
fish_pager_color_secondary_description
fish_pager_color_secondary_prefix
fish_pager_color_selected_background    --background=313244
fish_pager_color_selected_completion
fish_pager_color_selected_description
fish_pager_color_selected_prefix
```

**Comment by faho** [comment]
Alright, made some progress here.

For fish's internal rendering, we always enable bold mode if there is a background color, to "make reading easier". Which tbh seems quite awkward to me, especially since it *doesn't* apply to `set_color`, but oh well.

Anyway, we do this by enabling bold mode when the background color has changed, and somehow we reset the background and don't notice until the next element. Unfortunately I cannot *find* where.

There are two easy fixes:

1. Always send the bold sequence, even if we don't think the background has *changed* - this sends 4 extra bytes for every time we set the color that are mostly useless.
2. Don't set bold for background colors implicitly

The first isn't *ideal*, the second is a change in behavior that I believe is fundamentally sensible. Of course the "real" fix is to find where we move to the next line and forget that we need to re-enable bold.

@ridiculousfish That implicit bolding was added in d66700a0e4d20a9193ea83490781c0858d98c3f6 with the commit message "color work". Do you have any idea as to the reason why we do this? It seems weird and inconsistent with set_color.

**Comment by faho** [comment]
Alright, found where it happens - we didn't reset our idea of what the color is at the end of the line in some cases, and so at the next line we still assumed the same bolding was in effect when it wasn't.
