### ISSUE TITLE
Command to find/match element index in lists?

### ISSUE THREAD

**Issue by bnoctis** [fish-shell/fish-shell#9627]
```
> fish --version
fish, version 3.6.0
```

For now when I need to match elements:

```fish
for i in seq(1 (count $list)); if [ (string match 'needle' $list[$i]) ]; echo $i $list[$i]; end; end
```

I couldn't find a command that does this. Am I missing it? If not, can we have one?

**Comment by faho** [comment]
If you need a literal match like in your example:

```fish
set -l index (contains -i -- needle $list)
and echo $index $list[$index]
```

If you need a regex or wildcard match, then yes, you'll need to use the loop.

**Comment by bnoctis** [comment]
I'm indeed interested in the variable and the number, need to filter some elements out of a list, ha. Thanks for the direction!
