### ISSUE TITLE
store universal abbreviations to `config.fish`

### ISSUE THREAD

**Issue by t1** [fish-shell/fish-shell#9632]
Hi,

I understand that abbreviations should now be configured in the `config.fish` rendering the `--universal` option obsolete. But that makes creating new and persistent abbreviations more complicated (or even impossible in a web UI; see https://github.com/fish-shell/fish-shell/issues/9523#issuecomment-1453058689).

It would be really cool to restore the `--universal` option, but now store it to `config.fish`, replacing the same `abbr -a` command, if it's already in there.

**Comment by faho** [comment]
This doesn't really work. The formatting of config.fish can't be guaranteed, so we could *append* an abbr, but we could never *edit* or *remove* it.

And appending it is trivial - just do `echo whatever >> config.fish`, so you can do that yourself.

In short: Sorry, but no.

**Comment by afedulov** [comment]
How about a dedicated file specifically for abbreviations, as suggested here: https://github.com/fish-shell/fish-shell/issues/9865#issuecomment-1613969289 ?

**Comment by faho** [comment]
That has the same problem as writing to config.fish. We can't know where to write and where not to write because you could always edit it.

If you want to live with that it's possible to build it yourself. See above.

**Comment by afedulov** [comment]
Thanks for the quick reply.
> We can't know where to write and where not to write because you could always edit it.

Hmm, I am not sure I get the argumentation here completely. Is not that the case with any config file stored on the hard drive? Anyone can fiddle with and break, `.gitconfig` file format, but that does not prevent git from supporting adding aliases to it

```
git config --global alias.logg "log --pretty=format..."
``` 

Is there a fundamental difference I am overseeing?

With regards to the 'abbrsave' and 'abbradd' functions - I guess my main concerns are:
1. This does not deduplicate abbreviations - if one experiments with the right command, it can easily cause a lot of different abbreviations with the same key to pollute the config file unnecessarily
2. Call me lazy, but I really do not want to open Vim, search for the existing abbreviation and modify it. As a fellow user notes here: https://github.com/fish-shell/fish-shell/issues/9865 it was just so pleasant and "flowy" to use abbreviations in fish before became the opposite of that all of a sudden. An unfortunate regression for adding features I, personally, do not care that much.

I am not quite sure what the  argument about functions expansions means either, but I guess there is a middle ground that would make a lot of people happy: having and `abbr --add-simple` command that allows to add simple abbreviations, the once we had prior to 3.6. If storing them into variables is not possible for some reason, a key-value abbr-basic.config file should do the trick.

**Comment by faho** [comment]
> This does not deduplicate abbreviations 
> [...]
>  a lot of different abbreviations with the same key

It overwrites the entire file, and there can only be one abbreviation of the same name.

So I do not see how you would get duplicates.

> Call me lazy, but I really do not want to open Vim, search for the existing abbreviation and modify it.

Since there can only be one abbreviation of the same name, you can just create it again.

See:

```fish
abbr foo bar
abbr foo banana
```

run `abbr` and see only the latter.

You can also always `abbr --erase` any abbreviation you no longer want.

Then you run `abbrsave` and it overwrites your file and you're done.

>If storing them into variables is not possible for some reason, something like a key-value abbr-basic.config file should do the trick.

I do not believe we want to add either of these, sorry.

The above seems like it is simple enough that it'll work for your use case, and for more complicated things you really want the control that you get by just writing a script.

See e.g. [a bunch of my abbreviations](https://github.com/faho/fish-snippets/blob/main/conf.d/abbrs.fish).

**Comment by afedulov** [comment]
> It overwrites the entire file, and there can only be one abbreviation of the same name.

Ah, I was in a shell where I just erased them following the 3.6 instructions and thought that `abbr` would now only contain whatever was previously added in the variables + in the current shell. I see that it always has the full list now. This works fine than! It actually seems like it could be a valuable addition to the docs for people who are looking for preserving the old workflow.
