### ISSUE TITLE
fish_add_path defaulting to "universal" is a security worry

### ISSUE THREAD

**Issue by ltratt** [fish-shell/fish-shell#9648]
Some of my software started misbehaving today, and after I examined it with OpenBSD's `ktrace` I found it was trying to read from `~/tmp` -- but I hadn't specified that as my temporary directory.

Some head scratching later I found out that my `$PATH` didn't contain the 15 entries I expected but instead had *54 entries* including `~/tmp` so my "failing" software was clearly iterating through `$PATH` and then borking. Worryingly, `$PATH` also included non-existent subdirectories of `/tmp`, which an attacker can write to. My other boxes using fish also have similarly insecure `$PATH`s.

I believe the root problem is that (at least on OpenBSD with 3.6.0) the default behaviour is that `fish_user_paths` is "universal and sticky" and that `fish_add_path X` causes `X` to be added to `fish_user_paths` for evermore. If I create a fresh user, login twice, and do `fish_add_path X` then both login shells see `X` in `$PATH` immediately and `fish_user_paths` in `.config/fish/fish_variables` is immediately updated to include `X`. If I `rm -r X` then an attacker can later `mkdir X` and place a binary `B` in there of their choosing that might be executed instead of the `B` I expected.

In my opinion -- and I know this is something that not everyone will share -- this seems to me a security footgun. `fish_add_path` is the blessed way of manipulating `$PATH` but the default behaviour means that people end up with persistent alterations to `$PATH` that are an avenue for attacks. I must admit that I found the terminology "universal" vs. "global" unintuitive, and had to try things out to work out what the difference is.

I hate making recommendations to other people's software, partly because I might be wrong about the causes, but also because it feels incredibly impolite: you have provided me with something for free, and here I am suggesting that you change it to better suit me! However, I really like fish and want to keep on recommending it without saying "beware that if you don't use `fish_add_path` with `-g` you've got a security vulnerability". On that basis, I am left with the inescapable conclusion that the secure solution would seem to be to change `fish_add_path`s default behaviour to be `-g` not `-u`: failing that, perhaps `fish_add_path` should come with a big warning along the lines of "the default behaviour is to change `$PATH` for all running shells immediately and forever across reboots, which is a security problem: use `-g` unless you know what you're doing".

If I'm wrong in any of the above, then please accept my sincere apologies!

**Comment by faho** [comment]
If you can run `fish_add_path` with arbitrary arguments, chances are you can run any other shell command with arbitrary arguments - or, you know, launch a shell with $PATH set to something.

>If I rm -r X then an attacker can later mkdir X and place a binary B in there of their choosing that might be executed instead of the B I expected.

Yes, if you do include a directory in $PATH that an attacker can write to they can give you arbitrary files to execute, but that's a general thing, and changing it to global variables changes nothing about that. The security argument here is spurious - if we made it global by default, you would just stick it in config.fish and would have the same problem.

You can decide to use fish_add_path, or you can decide to use `fish_add_path -g`, or you can decide to not use it entirely. It's up to you.

The very *idea* of fish_add_path is to be the simple one-stop place where you can decide to add a path to $PATH and it'll "just work". That's why the default is the one that will "just work" most of the time.

Sorry, I am rejecting this.

**Comment by ltratt** [comment]
I will make one argument and then shut up.

The difference between `fish_add_path X` and `fish_add_path -g X` is that the latter is temporarily limited: when you close the current shell, the path modification disappears. In contrast, the former persists forever. That's where the security problem comes, in my opinion.

Consider this sequence:

1. Load terminal, `fish_add_path -p /tmp/X`
2. reboot machine
3. attacker does `mkdir /tmp/X`
4. Load terminal, type `B`

The attacker now has me run their `/tmp/X/B`. But if I had done `fish_add_path -g -p /tmp/X` then after the reboot my path would be "reset" and I'd be invoking the `B` I intended.

I absolutely see the use of `-U` and I don't believe the functionality should disappear: I just worry about it being the default.

**Comment by faho** [comment]
>The difference between fish_add_path X and fish_add_path -g X is that the latter is temporarily limited: when you close the current shell, the path modification disappears. 

In most cases, you want your path modifications to persist and so you will stick that `fish_add_path -g` into config.fish. And then you will just have the exact same problem as soon as you start a new fish (e.g. after a reboot).

>The objection is that fish's default is not what most users would expect, and the consequence of this is that they can easily unknowingly introduce security problems.

The default is what is documented, it is what makes it work when we tell users to "just run `fish_add_path`, it'll persist".

I'm sticking by my original answer: Sorry, but no.
