### ISSUE TITLE
FISH_CLIPBOARD_CMD should be a function

### ISSUE THREAD

**Issue by xfix** [fish-shell/fish-shell#965]
Currently, it's an env variable containing clipboard command. In my opinion, it should be function that checks `FISH_CLIPBOARD_CMD` instead.

**Comment by krader1961** [comment]
Closing this as a dup of issue #2894. I'm going to kill this "feature". If anyone thinks a fish_clipboard function (akin to fish_title) is a good idea I ask that a new enhancement request be opened with a suitable argument for its addition. Please provide scenarios illustrating why this would be useful and how such a function might be used in key bindings.
