### ISSUE TITLE
What is the best way to replace "ls" by "exa" in __fish_list_current_token (Alt+l)?

### ISSUE THREAD

**Issue by BarbzYHOOL** [fish-shell/fish-shell#9652]
I just would like to replace `ls` by `exa --icons` when pressing Alt+l

https://github.com/fish-shell/fish-shell/blob/master/share/functions/__fish_list_current_token.fish

I can copy the function, edit it and assign it to `bind \el` but maybe is there a smarter way and less troublesome?

**Comment by ridiculousfish** [comment]
I can't think of anything better than to copy it.

**Comment by BarbzYHOOL** [comment]
ok thank you
