### ISSUE TITLE
"fish_config browse" does not open in default browser

### ISSUE THREAD

**Issue by NightProwler-dc** [fish-shell/fish-shell#9655]
```
~> fish --version
fish, version 3.6.0
```

- opensuse Tumbleweed up to date
- Fresh install of fish

Type "fish_config browse", it opens a firejailed brave-browser instead of the default browser set for KDE environment which uses 
"flatpak run --branch=stable --arch=x86_64 --command=brave --file-forwarding com.brave.Browser @@u %U @@". I have both a native brave-browser and a flatpak brave-browser installed and the latter is set as the default in KDE default application settings.

For now all modifications made in the firejailed brave-browser to fish shell can not be saved. It may be related to the restriction of firejail but that's another issue unrelated to fish.

How am I able to make fish shell to open fish_config in the default browser as other apps all seem to know which browser to open when I click a link.

**Comment by ridiculousfish** [comment]
fish just calls `[webbrowser.open](https://docs.python.org/3/library/webbrowser.html#webbrowser.open)`. Can you confirm if this has the same issue?

    python3 -c "import webbrowser; webbrowser.open('https://example.org')"

If so I doubt there's much fish can do about it.

**Comment by mqudsi** [comment]
Are you running fish in firejail?

**Comment by NightProwler-dc** [comment]
Solved by changing .html file association.
