### ISSUE TITLE
`fg` doesn't work on Termux (Android)

### ISSUE THREAD

**Issue by anzhi0708** [fish-shell/fish-shell#9668]
### fish version
```
3.6.0
```

### uname -a
```
Linux localhost 4.14.186-perf-gd65dbc980d48 #1 SMP PREEMPT Fri Oct 28 22:22:47 CST 2022 aarch64 Android
```

### sh -c 'env HOME=$(mktemp -d) fish'

```
u0_a202@localhost:~►sh -c 'env HOME=$(mktemp -d) fish'      20:50
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
```

### how to reproduce the problem

- Open nvim and enter anything under insert mode
- **Ctrl-Z to suspend the process**
- **Type `fg` to see the bug**

(These worked on macOS so the problem is Android-specific)

### neofetch --off

```
u0_a202@localhost:~►neofetch --off                   0.128s 20:53
u0_a202@localhost
-----------------
OS: Android 11 aarch64
Host: Redmi 21091116AC
Kernel: 4.14.186-perf-gd65dbc980d48
Uptime: 3 days, 14 hours, 42 mins
Packages: 303 (dpkg), 1 (pkg)
Shell: fish 3.6.0
Terminal: /dev/pts/25
CPU: MT6833P (8) @ 2.000GHz
Memory: 2630MiB / 5635MiB
```

**Comment by faho** [comment]
I'm afraid you'll have better luck asking the termux people.

We have no testing environment and there's nothing unusual we do here, while Android is awkward when it comes to things like users and process management.

**Comment by mqudsi** [comment]
You kind of left us happening. You said "type fg to see the bug" but then you didn't actually show us the bug. What happens? Does something crash? Do you get an error? Does nothing happen? Does neovim hang? Does this happen with other procs than nvim?

**Comment by faho** [comment]
Okay, installed termux (note that the one from the play store is just completely broken - you need fdroid).

Ran `vim`, pressed ctrl-z (well, volume-up and z). It stops, fish gains control. Run `fg` and vim immediately stops again. Sometimes it runs long enough to show its UI before stopping again.

This seems like termux' terminal control stuff - pgroups and such - work differently from elsewhere.

Unfortunately, like I said: I have no idea how to even build fish for termux, let alone debug anything. Just typing on my phone is also sufficiently miserable that I don't feel inclined to spend a lot of time on it.

So I'm inclined to punt this to the termux people. I'm gonna keep this open for a bit to see if someone wants to take it up, but I'm not all that hopeful. Sorry.
