### ISSUE TITLE
cdh keep showing "No previous directories ..."

### ISSUE THREAD

**Issue by mbristol78** [fish-shell/fish-shell#9670]
Hello 
I recently tried to use the cdh command
but it keeps returning
"No previous directories to select. You have to cd at least once."

I cd into another path, use prevd, but it won't go anywhere and return [1]
the binding keys ALT+LEFT and ALT+RIGHT also wont do anything.

fish, version 3.6.0
Linux DESKTOP-TDDCB3T 4.4.0-22621-Microsoft #1105-Microsoft Fri Jan 01 08:00:00 PST 2016 x86_64 x86_64 x86_64 GNU/Linux
xterm-256color

Note, I have another WSL ubuntu 18.04 installed (below), which works fine
fish, version 3.6.0
Linux DESKTOP-TDDCB3T 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
xterm-256color

Thanks for help..

**Comment by faho** [comment]
This works for me?

Are you using any plugins or do you have any configuration on the broken system?

Check the output of `fish_delta -c`, which will give you the difference of your configuration from fish's stock setup, minus the completions.

**Comment by zanchey** [comment]
You've overridden the `cd` function, which is responsible for controlling the directory history. I suggest renaming your function, or copying the original to another name before defining your version, and invoking it from your function.

**Comment by mbristol78** [comment]
That is correct, it works now. Thanks for your help
