### ISSUE TITLE
(minor) how to change the "username" and path?

### ISSUE THREAD

**Issue by secretmango** [fish-shell/fish-shell#9677]
I dont know how this is called, but this `$USER:distro /v/h/$USER>` is really ugly.

I guess it is an abbreviation of `/var/home/$USER` ? I would like to remove it, is there a config for it?

**Comment by zanchey** [comment]
You can set the `fish_prompt_pwd_full_dirs` variable to the number of directories you would like to be printed in full; set it to 100 or something for it to never shorten the first 100 subdirectories.

Or you can choose a different prompt through `fish_config` if you want something else (or rewrite your `fish_prompt` function).

**Comment by mqudsi** [comment]
fyi, that thing is called "the prompt."

**Comment by firefoxlover** [comment]
Thanks! I see the shortened and the full prompt may be useful, but Konsole already displays these in the title, so I would like to remove them fully. Could not find a solution. `type fish_prompt` didnt include a line that mentions the working directory.

**Comment by mqudsi** [comment]
It's the call to `(prompt_pwd)`

**Comment by anordal** [comment]
The userfriendly option, if you don't like the default prompt, is to run `fish_config` and select another.

**Comment by faho** [comment]
> Maybe convert it to a Q&A to avoid repeating that?

https://fishshell.com/docs/current/tutorial.html#getting-started

https://fishshell.com/docs/current/faq.html#how-do-i-set-my-prompt

https://fishshell.com/docs/current/tutorial.html#prompt

https://fishshell.com/docs/current/interactive.html#programmable-prompt

https://fishshell.com/docs/current/fish_for_bash_users.html#prompts
