### ISSUE TITLE
Can't bind to Enter when using fish_hybrid_key_bindings or fish_vi_key_bindings

### ISSUE THREAD

**Issue by JanDeDobbeleer** [fish-shell/fish-shell#9683]
Fish version 3.6.0

Users reported the bug [here](https://github.com/JanDeDobbeleer/oh-my-posh/issues/3625) for oh-my-posh.

We use a custom keybinding to repaint the prompt on enter before execution ([transient](https://ohmyposh.dev/docs/configuration/transient)). This works perfectly when in `fish_default_key_bindings`, but as soon as you move to either `fish_hybrid_key_bindings` or `fish_vi_key_bindings`, the binding never executes.

I tried to find out why, but can't figure out why this shouldn't work. The code can be found [here](https://github.com/JanDeDobbeleer/oh-my-posh/blob/27c8f65cd59df25614a59595cf002c17650a17c5/src/shell/scripts/omp.fish#L119).

**Comment by faho** [comment]
You have bound the key without giving a mode, which means it will be bound in default mode, what vi would call "normal".

You want `bind --mode insert \r _render_transient` and probably `bind --mode visual \r _render_transient`.

**Comment by JanDeDobbeleer** [comment]
@faho aha! Good, I learned something 🙏🏻
