### ISSUE TITLE
Remove "The last command took 962.848 seconds." message after long commands.

### ISSUE THREAD

**Issue by VimalMollyn** [fish-shell/fish-shell#9689]
fish, version 3.5.0

`uname -a`
Darwin paans-mac.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103 arm64

`echo $TERM`
xterm-kitty

Reproducing the problem:
Everytime I run neovim for a long editing session, I get this message. It only goes away when I type in `clear` and doesn't seem to go away with `Ctrl + L` for some reason. How can I remove this message? 

Thanks!
Vimal

**Comment by ridiculousfish** [comment]
fish-shell does not print this message. There's something in your config which is causing this to happen.

Maybe search `~/.config/fish/functions` for this message? Have you installed any fish "plugins?"

**Comment by VimalMollyn** [comment]
Oh you're right! Turns out this is a message from the "wolf-theme" from oh-my-fish. Thanks!!
