### ISSUE TITLE
Documentation is clipped on right side

### ISSUE THREAD

**Issue by robfordww** [fish-shell/fish-shell#9690]
When using latest chrome and edge on Android 14, the right hand side of most documentation pages are clipped, preventing me from reading the last part of most lines.

See this screenshot for example:

![Screenshot_2023-03-23-11-17-47-53_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/24738409/227174519-08cff6b3-874b-4a2e-ab28-a382984e549d.jpg)

**Comment by faho** [comment]
Yup, it's missing a `width: 100%;` for div.documentwrapper in the CSS - this was missing from #9003.

I think we can just upload this straight to the site, no real need to make a release for it.
