### ISSUE TITLE
fish_config doesn't work in a docker container on WSL2

### ISSUE THREAD

**Issue by pm-ur** [fish-shell/fish-shell#9697]
fish, version 3.1.2

Debian 11 in docker container on Ubuntu 22.04 in WSL2

I started fish_config and pressed enter on "Start the Fish Web Config" link. The status bar shows "HTTP request sent; waiting for response." and stays like that forever until I kill the application with Ctrl+C.

**Comment by faho** [comment]
>fish, version 3.1.2

This fish version is 5 releases (excluding patch releases) and 31% of all commits ever made to fish behind.

Please update, we offer PPAs at https://fishshell.com/, and reopen if you can still reproduce.

Tho, to be honest, if that doesn't work it's likely you need to set up some sort of port forwarding to your container, and I think you might have better luck looking in the docker docs or checking stackoverflow or similar.

**Comment by pm-ur** [comment]
I see the following issue with the latest version too:
```
pm@m64:~/downloads$ fish --version
fish, version 3.6.1
pm@m64:~/downloads$ fish
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
pm@m64 ~/downloads> fish_config
Web config started at file:///tmp/web_configae6lq7wl.html
If that doesn't work, try opening http://localhost:8000/5f66d39b122fb75dcbbbe8c257d894ca/
Hit ENTER to stop.
Please add the directory containing cmd.exe to your $PATH
```

**Comment by faho** [comment]
>If I open lynx to the given URL in another terminal

fish_config needs javascript and won't work correctly in lynx.

I'm afraid in your case you need to use the CLI version - `fish_config prompt` to choose a prompt and `fish_config theme` to choose the theme (i.e. the colors), and just regular commands to do the rest.
