### ISSUE TITLE
Vi mode cursor doesn't respect iTerm2 cursor settings

### ISSUE THREAD

**Issue by ericvw** [fish-shell/fish-shell#9698]
```console
eric@G6D6PX2JTW ~> fish --version
fish, version 3.6.1
eric@G6D6PX2JTW ~> uname -a
Darwin G6D6PX2JTW 21.6.0 Darwin Kernel Version 21.6.0: Mon Dec 19 20:43:09 PST 2022; root:xnu-8020.240.18~2/RELEASE_ARM64_T6000 arm64 arm Darwin
eric@G6D6PX2JTW ~> echo $TERM
xterm-256color

```

When using any of the Vi modes in iTerm2 with default settings, the cursor is always set to block regardless of the settings in iTerm2 Settings > Profiles > Text > Cursor.

It turns out the following is where "block" is being set: https://github.com/fish-shell/fish-shell/blob/e78560d927d497e1b7a88df18d83424f0ca2a147/share/functions/fish_vi_cursor.fish#L80-L81.

Is there an opportunity to "pass-through" what iTerm sets as the default cursor style?

I tested an override to `fish_vi_cursor.fish` with the following handler code to achieve the desired behavior:

```fish
set -l varname fish_cursor_\$fish_bind_mode
if set -q \$varname
    $function \$\$varname
end
```

I'm happy to submit a PR if this is of interest.

**Comment by ericvw** [comment]
As an aside, I discovered that when any `echo -en "\e[… q"` escape control sequence is invoked, that will always take precedence no matter what the iTerm2 settings are changed to for existing interactive shells.

**Comment by faho** [comment]
I've now added a commit that will make it ignore (as in not send the escape at all) any cursor shape it doesn't know about, so you can just set the relevant cursor variables to e.g. empty.

```fish
set -g fish_cursor_unknown
set -g fish_cursor_insert
```

>As an aside, I discovered that when any echo -en "\e[… q" escape control sequence is invoked, that will always take precedence no matter what the iTerm2 settings are changed to for existing interactive shells.

Yes, that is how these are supposed to work.

**Comment by ericvw** [comment]
Thank you for the quick response and the patch to not send the escape at all.

To keep Vi and non-Vi modes consistent, does it make sense that the default `fish` behavior is to not send any escapes when Vi mode is enabled?

**Comment by faho** [comment]
>To keep Vi and non-Vi modes consistent, does it make sense that the default fish behavior is to not send any escapes when Vi mode is enabled?

No. The very *point* of the cursor shaping is to indicate the vi-mode (as in "insert" or "normal"), so this is a vi-specific thing, and the only way we can sensibly indicate it by default, given that we don't have a way to query your cursor shape, is to set a cursor shape.

**Comment by ericvw** [comment]
No worries — it makes sense to me. I appreciate the response!
