### ISSUE TITLE
`contains_seq` is undocumented?

### ISSUE THREAD

**Issue by mhmdanas** [fish-shell/fish-shell#9701]
Using Fish 3.6.1 on Void Linux, `contains_seq -h` or `contains_seq --help` both fail with an exit code of 1, without showing any help. I also couldn't find anything about it in the web documentation. Is `contains_seq` an internal function of some sort? If not, is there a reason the function practically undocumented?

**Comment by faho** [comment]
Duplicate of #6695

**Comment by mhmdanas** [comment]
Sorry for the duplicate, that issue didn't appear in my search for `contains_seq` (and still doesn't, probably because it's mentioned there a `contains_seq.fish`).
