### ISSUE TITLE
`fish_add_path --append` doesn't work?

### ISSUE THREAD

**Issue by lgarron** [fish-shell/fish-shell#9709]
fish version `3.6.1`
macOS 13.3

My dotfiles contain the following:

```
fish_add_path --append $NEW_PATH_COMPONENT
```

I was initially surprised that `fish_add_path` appended by default, so I added `--append` to avoid unintentionally shadowing built-in binaries (which has caused issues for me in the past, given that I have my Go and `cargo` binaries in my `$PATH`, and those can accumulate quite a lot of binaries while working on projects). But to my further surprise, `--append` doesn't actually result in the path component being appended!

It seems this is because it writes `fish_user_paths` to `fish_variables`, which is automatically *prepended* to the path in the future: https://github.com/fish-shell/fish-shell/pull/888

If this is intended behaviour, would it make sense to remove the `--append` flag or print a caveat?

**Comment by faho** [comment]
In this case, I'm just gonna quote the docs:

> if $fish_user_paths is used, that means they are last in $fish_user_paths, which is itself prepended to [PATH](https://fishshell.com/docs/current/language.html#envvar-PATH), so they still stay ahead of the system paths).

Removing it doesn't make sense because it has its uses, and printing a warning is something we try not to.

So I'm gonna file this one under "unfortunate". Sorry!

**Comment by lgarron** [comment]
> In this case, I'm just gonna quote the docs:
> 
> > if $fish_user_paths is used, that means they are last in $fish_user_paths, which is itself prepended to [PATH](https://fishshell.com/docs/current/language.html#envvar-PATH), so they still stay ahead of the system paths).
> 
> Removing it doesn't make sense because it has its uses, and printing a warning is something we try not to.
> 
> So I'm gonna file this one under "unfortunate". Sorry!

I see! I'm alright with my own code, although it's indeed unfortunate that I have to implement path deduping and appending when `fish_add_path` looked so appealing. 😞

Thanks for clarifying, though. I'd argue that something `fish_add_user_path` would have been more clear for that behaviour, but I guess that ship has probably sailed.

**Comment by faho** [comment]
You might have missed this, but you can use `fish_add_path --path --append`, which will directly append to $PATH, skipping $fish_user_paths. That's why the docs say "if $fish_user_paths is used".

That won't *persist* via the universal variable, but stick it in config.fish and it should do exactly what you want.

**Comment by kaddkaka** [comment]
I had this same issue even after reading `man fish_add_path`. The manpage could be made simpler for new fishermen.

I'm happy you filed this @lgarron so I could solve it😄
