### ISSUE TITLE
failed to execute process /usr/bin/git...variable exceeds the OS argument length limit...

### ISSUE THREAD

**Issue by chuckd853** [fish-shell/fish-shell#9711]
I keep getting this error when trying to access project root directory that is on github:

`exec: Failed to execute process '/usr/bin/git': An argument or exported variable exceeds the OS argument length limit.`

I don't have many args in my `fish_path`

```
❯ echo $PATH

/opt/flutter/bin /opt/flutter /usr/bin /home/chris/go /home/chris/go/bin /usr/lib/go /usr/local/sbin /usr/local/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl
```

```
❯ cat config.fish

if status is-interactive
    # Commands to run in interactive sessions can go here
end

abbr --add cl clear
abbr --add goapp cd /home/chris/go/src/github.com/mygithub/

fish_add_path /usr/lib/go
fish_add_path /home/chris/go/bin
fish_add_path /home/chris/go
fish_add_path /usr/bin	
fish_add_path /opt/flutter
fish_add_path /opt/flutter/bin
fish_add_path /usr/bin/flutter
fish_add_path /usr/bin/ninja
```

I don't have the `set -U...` line in my `.config` file as indicated by a similar issue on github `fish/issues`.

How do I fix this?

**Comment by zanchey** [comment]
It's probably not your path, but another exported variable. All the exported variables and command-line arguments have to fit inside the size given by `getconf ARG_MAX`.

`set -xL | string match -r '.{1024,}'` will show you very large exported variables.

**Comment by chuckd853** [comment]
Thanks. Turns out the error only occurs when using the `tide` prompt. I removed that and everything works.
