### ISSUE TITLE
for loops with null bytes behave strangely

### ISSUE THREAD

**Issue by IsaacOscar** [fish-shell/fish-shell#9714]
I definitely should not be trying to play with null bytes, but I'd expect the behaviour to at least be consistent. Consider this for loop:

```
for X in (echo -e 'a\0b\nc')
     set -S X
     echo "$X more text"; end
```
This prints:
```
$X: set in local scope, unexported, with 1 elements
$X[1]: |a\x00b|
a
$X: set in local scope, unexported, with 1 elements
$X[1]: |c|
c more text
```

So it seems that I have got a variable containing a null byte, which is causing the " more text" to be eaten.
(Note this happens even if I use `/usr/bin/echo` instead of the builtin).

If I do `echo $X more text` without the quotation marks, it will print `a more text`.

I also get that output if I first copy X to itself:
```
for X in (echo -e 'a\0b\nc')
     set X $X
     set -S X
     echo "$X more text"; end
```
I was very surprised to find that `set X $X` is not in fact a no-op.

This prints:
```
$X: set in local scope, unexported, with 1 elements
$X[1]: |a|
a more text
$X: set in local scope, unexported, with 1 elements
$X[1]: |c|
c more text
```

I get the same output if I first save the `echo -e` call in a variable:
```
set Y (echo -e 'a\0b\nc')
for X in $Y
    ...
```

I was under the impression that variables store C-style strings (i.e. null terminated),
so I would expect trying to store something in it that contains a null-byte to just ignore everything after the null, which is what my later examples do.

This is with 3.6.0.

**Comment by faho** [comment]
>I definitely should not be trying to play with null bytes, but I'd expect the behaviour to at least be consistent

It is.

Arguments are passed as c-style strings, even to builtins.

That means if you do `echo "$X foo"`, that passes *one argument* that includes a NUL, and if you do `echo $X foo` that passes one argument that includes a NUL and a second argument, so it can print both.

**Comment by IsaacOscar** [comment]
> > I definitely should not be trying to play with null bytes, but I'd expect the behaviour to at least be consistent
> 
> It is.
> 
> Arguments are passed as c-style strings, even to builtins.

Except they're not passed to the `for` builtin that way, as I showd above:
```
for X in (echo -e 'a\0b')
   set -S X; end
```
This shows that the `\0b` part is *not* being ignored by the `for`:
```
$X: set in local scope, unexported, with 1 elements
$X[1]: |a\x00b|
```

In fact I cannot think of any other way you could get a null-byte inside a variable,
the other builtins, e.g. `set Y (echo -e 'a\0b')` do not have this behaviour: they ignore the null-byte and everything after it:
```
$Y: set in global scope, unexported, with 1 elements
$Y[1]: |a|
```

Hence the inconsistency.

**Comment by ridiculousfish** [comment]
This is a subtle and interesting question. There is absolutely nothing wrong with playing with nul bytes.

As faho said, arguments are passed as c-style strings even to builtins. One reason is for consistency with external commands: external commands receive `argv` which is nul-terminated; fish-shell's builtins are the same to keep us honest. So you cannot use `set` for a variable whose name contains an interior nul.

But nuls are fine for command output: if you `cat` a file that has a nul byte then that should be preserved, and it is.

Where it gets interesting is command substitution, when command output becomes arguments to a new command. Here fish splits on newlines, but now some arguments will have interior nuls; they'll get naturally truncated.

I'm inclined to do nothing about this, but I'm curious if other shells have a better solution. What happens in other shells if you perform a command substitution with a nul byte?

**Comment by IsaacOscar** [comment]
> I'm inclined to do nothing about this, but I'm curious if other shells have a better solution. What happens in other shells if you perform a command substitution with a nul byte?

First I ran `echo -e 'a\0b' > ab` in Fish (so I didn't have to worry about the different shells having different echos).

Then I ran this `fish` script:
```
echo "Var:"
set X (cat ab)
echo "$X more text"

echo "For:"
for X in (cat ab)
    echo "$X more text"; end
```

The `fish` output:
```
Var:
a more text
For:
a
```

Then for `bash`/`zsh`/`ksh`/`dash` I used this script:
```
echo "Var:"
X=$(cat ab)
echo "$X more text"

echo "For:"
for X in $(cat ab); do
    echo "$X more text"; done
```
The output from `bash`:
```
Var:
bash: warning: command substitution: ignored null byte in input
ab more text
For:
bash: warning: command substitution: ignored null byte in input
ab more text
```

The `zsh` output:
```
Var:
ab more text
For:
a more text
b more text
```
In `ksh`:
```
Var:
a more text
For:
a more text
```

In `dash`:
```
Var:
ab more text
For:
ab more text
```

And for `tcsh`, I used this script:
```
echo "Var:"
set X = `cat ab`
echo "$X more text"

echo "For:"
foreach X (`cat ab`)
        echo "$X more text"
end
```

The `tcsh` output was:
```
Var:
a more text
For:
a more text
```


So out of the 6 shells I tried, I got 5 different results.
