### ISSUE TITLE
fish_pager_color_prefix is not respected anymore due to introduction of reverse-isearch functionality

### ISSUE THREAD

**Issue by ericvw** [fish-shell/fish-shell#9715]
As of `fish` version 3.6.0, issue #602 to add reverse-isearch functionally made in pull request #9089 does not respect nor react to `fish_pager_color_prefix` variable anymore.

This appears to be due to commit 1af9b8e43.

If `fish_pager_color_prefix` is desired to be supported, I'm happy to attempt on contributing a pull request to revive respecting this variable. Alternatively, if this variable wants to be dropped entirely, I can create a pull request to remove it.

**Comment by faho** [comment]
`fish_pager_color_prefix` is still supported in the completion pager.

It is not supported in the *history* pager because that is syntax-highlighted. I do not believe highlighting the prefix there is helpful, so I'll be rejecting this.

**Comment by ericvw** [comment]
> `fish_pager_color_prefix` is still supported in the completion pager.

I entirely forgot about the completion pager 🤦. Sorry for the noise.
