### ISSUE TITLE
Fish displays the wrong processor architecture on Apple Silicon, causing build problems

### ISSUE THREAD

**Issue by clstaudt** [fish-shell/fish-shell#9724]
Running on a Mac with an arm64 processor, `fish` still displays this for the architecture:

```
cls@clsm1ba ~> arch
i386
cls@clsm1ba ~> uname -m
x86_64
```

Other shells display the correct architecture here.

This causes problems when compiling code (e.g. when installing Python packages): Sometimes the resulting binaries are built for `x86` and will not run. I have verified that the problem does not occur when compiling from a different shell (`zsh`).

I have tested this with a fresh installation of `fish` (via Homebrew) and believe I have deleted all `fish` configuration files before.

Environment:

```
cls@clsm1ba ~> fish --version
fish, version 3.6.1
``

macOS 13.3.1

**Comment by faho** [comment]
`uname` is not a fish thing. It is an external tool.

I can see two possible explanations: Either you are starting a different `uname` (compare `command -v uname` in other shells), or you've built fish for x86 and now everything is running in rosetta-mode or something.

**Comment by clstaudt** [comment]
Indeed:

```
(base) cls@clsm1ba ~ % file /usr/local/bin/fish
/usr/local/bin/fish: Mach-O 64-bit executable x86_64
```

This is what homebrew builds and installs. Any idea on how to install it as arm64?

**Comment by clstaudt** [comment]
Also when forcing homebrew to build from source...

```
➤ brew install --build-from-source fish
==> Downloading https://formulae.brew.sh/api/formula.jws.json
######################################################################## 100.0%
==> Downloading https://formulae.brew.sh/api/cask.jws.json
######################################################################## 100.0%
==> Fetching fish
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/722f668
######################################################################## 100.0%
==> Downloading https://github.com/fish-shell/fish-shell/releases/download/3.6.1
Already downloaded: /Users/cls/Library/Caches/Homebrew/downloads/f800b55e658491ad4be16c0fbf42235ee6d67ce3e204b3b7de95aa18ded25243--fish-3.6.1.tar.xz
==> cmake -S . -B build -DCMAKE_INSTALL_SYSCONFDIR=/usr/local/etc -Dextra_functi
==> cmake --build build
==> cmake --install build
🍺  /usr/local/Cellar/fish/3.6.1: 1,493 files, 16.8MB, built in 49 seconds
==> Running `brew cleanup fish`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
```

I get:

```
➤ file /usr/local/bin/fish
/usr/local/bin/fish: Mach-O 64-bit executable x86_64
```

**Comment by faho** [comment]
You'll have to ask the homebrew people, we have no influence over what that builds.

**Comment by clstaudt** [comment]
https://github.com/fish-shell/fish-shell/issues/9724#issuecomment-1501568804
