### ISSUE TITLE
Starting in fish 3.6.0, abbreviations no longer trigger with following semicolon

### ISSUE THREAD

**Issue by lwolfsonkin** [fish-shell/fish-shell#9730]
Previously, starting in Fish 3.1.0, I reported #6970, which was that abbreviations stopped expanding with a following semicolon. At the time, I was given the suggestion to add `bind ';' self-insert expand-abbr` to my `config.fish`, which fixed my problem.

In my usual workflow, I use a large set of `abbr` abbreviations for all the `hg` subcommands, and often chain them together by typing e.g. the literal `amend; and upload` which would expand to `hg amend; and hg upload` and each of `amend` and `upload` respectively would expand once I typed a following space, enter, or semicolon (among others, I presume).

Now, I'm having the same issue in Fish 3.6.0 (and 3.6.1), both with and without the `bind ';' self-insert expand-abbr` workaround in my config, on two different machines of mine.

I see that Fish 3.6.0 overhauled the abbreviation handling, and I'm assuming that somehow broke my workflow. Was that intentional? Might it be possible for me to work around this in the existing version?

Thank you!

**Comment by faho** [comment]
Try the other way around:

```fish
bind ';' expand-abbr self-insert
```

In fact that's how our bindings are supposed to work already, so lemme just fix that.

**Comment by lwolfsonkin** [comment]
Ah, that workaround solved my immediate issue. Thanks @faho! I appreciate it!

**Comment by zanchey** [comment]
@faho, did you have a fix in mind here?

**Comment by faho** [comment]
>@faho, did you have a fix in mind here?

I *was* gonna switch it from "self-insert expand-abbr" to "expand-abbr self-insert", but that has some awkward side effects.

The main issue: if you have an abbr with `--set-cursor`, now triggering it inserts the space.

Other changes are that it changes what part "undo" undoes and so you might have a space less. Which seems not terrible but I'm not sure we want those repercussions here.

I think we need to look at the cursor_backtrack idea again.

**Comment by zanchey** [comment]
OK, pushing this out of 3.7.0 for now

**Comment by g0t4** [comment]
FYI flipping the order messes up the new `abbr` with `--set-cursor`, you end up getting the self-insert at the cursor position after its moved... for example:
```shell
abbr --set-cursor='!' gcmsg 'git commit -m "!"'
```
Which exands to `git commit -m "<CURSOR>"` and so if `self-insert` comes after then I get `git commit -m " <CURSOR>"` which is definitely not my intention :)

@faho this may require changes in `expand-abbr`, or perhaps a new `expand-abbr-and-self-insert` that correctly places the `self-insert` and then backtracks accordingly to perform the expand without breaking `;|&<>)` from triggering expansion.

This is my current workaround (note not a fix for all issues, just the ones that affect me most of the time):
```shell

# most of the time I use space to trigger --set-cursor abbr's and it just so happens expand-abbr works with self-insert before & after for " " only
bind --preset $argv " " self-insert expand-abbr
# rest of these I assume I am only looking for vanilla abbrs to work (so --set-cursor abbrs are broken still):
bind --preset $argv ";" expand-abbr self-insert
bind --preset $argv "|" expand-abbr self-insert
bind --preset $argv "&" expand-abbr self-insert
bind --preset $argv ">" expand-abbr self-insert
bind --preset $argv "<" expand-abbr self-insert
bind --preset $argv ")" expand-abbr self-insert
```

**Comment by g0t4** [comment]
As for `cursor_backtrack`, IIAC this goes back a char before trying expansion and ' ' won't be treated as a token so it correctly finds and expands the previous "command" positioned token (if any). Whereas with `;|&<>)` I would assume those are all treated as tokens and so expansion doesn't work unless the backtrack is 2...

https://github.com/fish-shell/fish-shell/blob/05ac1b770cd2b576323e40000561f1fdfe3ade56/src/reader.rs#L2919-L2925

https://github.com/fish-shell/fish-shell/blob/05ac1b770cd2b576323e40000561f1fdfe3ade56/src/reader.rs#L4404-L4420

All of this feels like the fish shell input functions need to more intimately understand abbr, and what is being inserted, to find a solid workaround?
