### ISSUE TITLE
disable cd to learn zoxide

### ISSUE THREAD

**Issue by stephane-archer** [fish-shell/fish-shell#9733]
Hi, I wanted to "disable cd" for interactive use to change my muscle memory.
type this in your shell and it works!
```
function cd
    if status is-interactive
          echo "Use z"
          return 1
	end
	builtin cd $argv
end
```
cd is disabled and z works!
let's `funcsave cd` then start a new terminal
cd is disabled but z says now "Use z"...

PS: in my config file I have the following:
```
if status --is-interactive
        zoxide init fish | source
end
```

System info:
```
fish, version 3.6.1
zoxide v0.9.0
Darwin MacBook-Pro.local 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:42:11 PST 2023; root:xnu-8792.81.3~2/RELEASE_X86_64 x86_64
screen-256color
```

**Comment by faho** [comment]
This appears to be a zoxide issue.

See what fish script they add by running `zoxide init fish` without the `| source`. The relevant part:

```fish
# A copy of fish's internal cd function. This makes it possible to use
# `alias cd=z` without causing an infinite loop.
if ! builtin functions -q __zoxide_cd_internal
    if builtin functions -q cd
        builtin functions -c cd __zoxide_cd_internal
    else
        alias __zoxide_cd_internal='builtin cd'
    end
end
```

This copies a cd function to `__zoxide_cd_internal` if it exists, which seems to be the wrong way around to me?

You should be able to work around this by defining it yourself:

```fish
function __zoxide_cd_internal; builtin cd $argv; end
```

**Comment by stephane-archer** [comment]
zoxide issue for reference : https://github.com/ajeetdsouza/zoxide/issues/553

**Comment by ajeetdsouza** [comment]
> This copies a cd function to `__zoxide_cd_internal` if a cd function exists, which seems to be the wrong way around to me?

Hey @faho, I wanted `z` to fall back to exactly the same behaviour as Fish's `cd` function, which is why I'm copying out the function. Any suggestions for how I can do this better would be welcome.

I did think of just copying the source code of the `cd` function, but it relies on `nextd` / `prevd` which in turn rely on more functions. It would be great if there was a way to reference builtin functions directly.

**Comment by faho** [comment]
@ajeetdsouza Hmmm... that's a good question.

You can, of course, `source $__fish_data_dir/functions/cd.fish` to get the original function (which would override the user's version again, so you would have to copy that out of the way), but fundamentally there's an issue with respecting user customization vs respecting fish's function.

The main thing here is that `functions -q cd` will basically always be true, so this code is kind of suspect - the `else` path is kinda useless?

You might want to check if `functions --details cd` prints the same as `$__fish_data_dir/functions/cd.fish` instead - `test "$(functions --details cd)[1]" = "$__fish_data_dir/functions/cd.fish"`

(tbh we should probably remove the function and just integrate the functionality into cd proper, which makes a bunch of things simpler, including this)

**Comment by ajeetdsouza** [comment]
Yeah, that does seem very convoluted. I agree that this should be a builtin, at least that's how I've seen it implemented in most other shells.
