### ISSUE TITLE
history delete with an index range (delete first/last X entries)

### ISSUE THREAD

**Issue by r3a1d3a1** [fish-shell/fish-shell#9736]
fish version:  3.5.1

Would be great to be able to delete oldest 100 or so entries for some common commands like `cd`.
This is to keep history cleaner and boot times faster.
Alternatively, a fancier cleanup method could figure out which commands are repeated with the same parameters but different paths more than N times, and delete the oldest M occurrences, possibly interactively for confirmation.

[Related doc page](https://fishshell.com/docs/current/cmds/history.html)

**Comment by faho** [comment]
> P.S. By boot times, I wasn't referring to system boot, but just that of fish. I used to wait up a few seconds for fish to initialize after opening Terminal, but that went down considerably as I cleared most of fish history.

That is not something that typically happens. I just generated an artificial history file with 250k entries, and fish starts without noticeable delay. My years-old history file has 23k entries (remember, this is deduplicated automatically).

My guess is either you were running an old version or you have configuration that accesses the history, and *that* should be improved.
