### ISSUE TITLE
Problem of autosuggestion about commands in history

### ISSUE THREAD

**Issue by c02y** [fish-shell/fish-shell#9737]
- `fish, version 3.6.1`
- `Linux archlinux 6.2.10-zen1-1-zen`
- TERM: `screen-256color`
- Already tried `sh -c 'env HOME=$(mktemp -d) fish'`

**YOUR TEXT HERE**
I wrote a function that contains a few flags in my config.fish, and I've used it for multiple times like:
```
$ func -a -b file.ext
```

But whenever I tried to use it again to replace the `file.ext` part like
```
$ func -a
```
it never auto suggests anything from the fish_history file, multiple similar commands starting with `func -a` are inside `fish_history` file or `history`'s output.

It works fine for `Up` key to get suggestion for the rest part of `func -a`, but it just never auto suggests (the gray text part).

BTW: it works for some functions I write in config.fish as far as I know, but I just notice that it doesn't work for the specific `func` function I write, this issue has been there for quite some time.

So is there anything I don't understand about the autosuggestion from history?

-------------------------
**UPDATE**:
I found that if I delete the argv file or I'm in another directory, the auto suggestion won't work at all.

So is there anything I can do to make this kind of auto suggestion work?

You can reproduce it under `sh -c 'env HOME=$(mktemp -d) fish'`
Reproduce:
- get a random short video file into /tmp directory
- create a function
- run the function 
- check if it auto suggests previous command 
- delete the video file or cd into another directory
- check again if it auto suggests previous command of the function
- NO, it doesn't auto suggest

simplified demo function:
```
function ffms
    set -l options c "b="
    argparse -n ffms $options -- $argv

    set FILE (string split -r -m1 . $argv)[1]
    set EXT (string lower (echo $argv| sed 's/^.*\.//'))
    ffmpeg -hide_banner -i $argv -c:v hevc_nvenc -c:a copy -b:v $_flag_b {$FILE}-{$_flag_b}.{$EXT}
end
```

Reproduction gif:

https://user-images.githubusercontent.com/2135996/232603350-c5b5f457-7246-4f12-9197-adee64a58471.mp4

**Comment by zanchey** [comment]
Can you try running fish with `--debug=complete,reader_render` and see if that sheds any light?

**Comment by c02y** [comment]
`sh -c 'env HOME=$(mktemp -d) fish --debug=complete,reader_render'` works the same, no auto suggestion like the original post, although the output is a mess.

I record the same process and save the output to a file, if you can get anything useful from it.

[log.txt](https://github.com/fish-shell/fish-shell/files/11303869/log.txt)

**Comment by krobelus** [comment]
after

```sh
touch file
somefunc -a -a
somefunc -a -b file
rm file
```

typing `somef` autosuggests `somefunc -a -a` but not `somefunc -a -b file`.
This is intentional because the file is gone, which usually invalidates the command.

Maybe we can improve this (autosuggest only the prefix, `somefunc -a -b`?) but that seems tricky

**Comment by c02y** [comment]
I don't know why on earth would fish shell would not auto suggest if the file is gone in the first place (as you said, the command is invalid), it chooses simplicity over complexity, it could simply not handle this kind of situation, it is just unnecessary.

I'll choose to use other method like `UP` key to get the history then.
