### ISSUE TITLE
Git completion is broken (but kinda works?)

### ISSUE THREAD

**Issue by andradei** [fish-shell/fish-shell#9738]
### Fish
fish, version 3.6.1

### Linux
Linux AE-22-01 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linu

Fish installed via homebrew. No 3rd party customizations.

---

![image](https://user-images.githubusercontent.com/2653546/232871220-26f8ccbf-60c5-4255-802b-0ed4d4f843f6.png)

**Comment by andradei** [comment]
For more context, this is my $PATH

```
/home/linuxbrew/.linuxbrew/bin /home/linuxbrew/.linuxbrew/sbin /home/myuser/.cargo/bin /home/linuxbrew/.linuxbrew/bin /home/linuxbrew/.linuxbrew/sbin /usr/local/sbin /usr/local/bin /usr/sbin /usr/bin /sbin /bin /usr/games /usr/local/games /usr/lib/wsl/lib /mnt/c/Program Files/Eclipse Adoptium/jre-8.0.312.7-hotspot/bin /mnt/c/Program Files/Eclipse Adoptium/jre-11.0.13.8-hotspot/bin /mnt/c/Program Files (x86)/Eclipse Adoptium/jre-8.0.312.7-hotspot/bin /mnt/c/WINDOWS/system32 /mnt/c/WINDOWS /mnt/c/WINDOWS/System32/Wbem /mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/ /mnt/c/WINDOWS/System32/OpenSSH/ /mnt/c/Program Files/PuTTY/ /Docker/host/bin /mnt/c/Users/My.User/scoop/shims /mnt/c/Users/My.User/AppData/Local/Microsoft/WindowsApps /mnt/c/Users/My.User/AppData/Local/Programs/Microsoft VS Code/bin /home/myuser/.cargo/bin
```

### Pretty printed

```
/usr/local/bin
/usr/sbin
/usr/bin
/sbin
/bin
/usr/games
/usr/local/games
/usr/lib/wsl/lib
/mnt/c/Program Files/Eclipse Adoptium/jre-8.0.312.7-hotspot/bin
/mnt/c/Program Files/Eclipse Adoptium/jre-11.0.13.8-hotspot/bin
/mnt/c/Program Files (x86)/Eclipse Adoptium/jre-8.0.312.7-hotspot/bin
/mnt/c/WINDOWS/system32
/mnt/c/WINDOWS
/mnt/c/WINDOWS/System32/Wbem
/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/
/mnt/c/WINDOWS/System32/OpenSSH/
/mnt/c/Program Files/PuTTY/
/Docker/host/bin
/mnt/c/Users/My.User/scoop/shims
/mnt/c/Users/My.User/AppData/Local/Microsoft/WindowsApps
/mnt/c/Users/My.User/AppData/Local/Programs/Microsoft VS Code/bin
/home/myuser/.cargo/bin
```

**Comment by faho** [comment]
Yep. Pretty typical WSL-fare.

The offending component is `/mnt/c/Program Files (x86)/Eclipse Adoptium/jre-8.0.312.7-hotspot/bin` - the `(x86)` looks like a command substitution and we didn't escape it correctly in one place, so if you have a custom git command there (which is any command named "git-something" - that's how git works) it'd try to run that `x86`.

It's fixed in master now.

**Comment by andradei** [comment]
Wow... that's the quickest PR and issue close I've seen live in my life @faho

**Comment by zanchey** [comment]
Is there any benefit to expanding command substitution in this kind of pattern? Seems to me it is more likely to cause harm.

**Comment by faho** [comment]
@zanchey It's the normal completion argument handling. There really is nothing special here.

The offending code is:

```fish
    complete -c git -f -n "__fish_git_using_command $cmd" -a "(__fish_git_complete_custom_command $cmd)"
```

where both the `-n`/`--condition` and `-a`/`--argument` argument are fish script. There is no way we can *not* expand the command substitutions here without completely overthrowing the entire complete handling and rewriting most completion scripts.
