### ISSUE TITLE
Rust builtins behave differently with NUL in arguments (mostly crash)

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#9739]
Check this out:

```fish
echo a\x00b
```

>thread '<unnamed>' panicked at 'String contained intermediate NUL character: ContainsNul { index: 1, inner: Some([97, 0, 98, 10]) }', src/wchar_ffi.rs:49:39

Mostly, rust builtins will crash when trying to print any argument that contains an embedded NUL like that (because the `\x00` will actually generate a NUL - but the same thing happens with e.g. `echo (find . -print0)`). Some will instead continue, and in some case "work", but differently than before:

- `type -q` will probably always return false (while `type a\x00b` will crash trying to print "Could not find 'aNULb'")
- `contains a\x00b a` will now fail, `contains a\x00b a\x00b` will succeed
- `echo` and `printf` crash

and so on.

A quick refresher so we're all on the same page: 

The C++ code passed the builtin arguments as `wchar_t*`, meaning they're NUL-terminated C-style strings. That means passing any NUL to a builtin would silently truncate the argument - `contains a\x00b a` would succeed. This matches what happens when you pass arguments to external commands, where you have to go through the c-string-using unix api.

We *could*, in future, change it so passing NULs to builtins is allowed, but it would have to have a few changes - `test`'s path tests should error out, for instance, `path` should either error out or automatically split on NUL like it does for stdin (`path dirname` specifically should *not* allow NULs because that's contrary to UNIX path semantics).

(also I've mentioned automatic splitting on NUL before and I still like that behavior)

For now, it's probably easiest to keep the current behavior by truncating on NUL when running a rust builtin - which would also fix the crashes.

**Comment by ridiculousfish** [comment]
Agreed with truncating on NUL when passing strings as arguments at least for now. This keeps our builtins "honest" since they're on the same level with external commands, which of course cannot receive NUL.

**Comment by mqudsi** [comment]
Taking a step back, two obvious solutions:

* conditionally fork only when we have to for cases like this, or 
* if we *really* want to avoid that, we could additionally compile each builtin to its own binary (or all of them to a single binary, hard-linked to the different builtin names the same way busybox does) and run that binary directly - but this means making sure builtins no longer used shared state, which is no small undertaking

cons are that builtin performance when used in a pipeline like this will suffer, which is probably acceptable.

**Comment by faho** [comment]
Alright, #9859 now removes the "crash" part of the equation. This was necessary because we *need* to allow NUL in output, because NUL can come from input - `string` in particular can and should be able to handle embedded NULs coming in from stdin.

I'm keeping this issue to track what I consider to be the second part: Should we truncate on NUL for *arguments*?

Now, `echo foo\x00bar` prints foo, a NUL and then bar. `\x00` is now a sensible thing to use. Any ported builtin will get this without doing anything. The effects:

- Once `set` or `read` are ported variables could conceivably contain NUL, which would mean exported variables will be misidentified by external commands - `set -x foo bar\x00baz` will probably be seen to define `foo=bar` and `baz=`
- `path` or `test` would still have these effectively truncated for path checks - `path is /usr/bin/git\x00fart` would check /usr/bin/git (fun fact this is also what zsh does - `test -e $'/usr/bin/git\x00fart'` ignores the "fart" part)
- for other builtins a NUL never makes sense - `set_color`, `math` - and the error might need to be escaped
- for others again, it'll just be passed along (`printf`, `echo`, `random choice`

I would *like* to see `\x00` be usable eventually, but that's a bigger source of bugs that I don't think we want to open just now, so we should truncate for now.

**Comment by ridiculousfish** [comment]
In general I have the (weakly held) opinion that fish builtins should nul-truncate so that they are on the same playing field as external commands - that is that `builtin echo` doesn't haven't any superpowers over `command echo`. But I might be convinced otherwise.
