### ISSUE TITLE
Abbreviations based on multiple tokens

### ISSUE THREAD

**Issue by zx8** [fish-shell/fish-shell#9748]
Not sure if this is currently possible, but I've tried a few `abbr` permutations and couldn't get it to work.

I'm trying to use the new ["mega abbr"](https://github.com/fish-shell/fish-shell/pull/9313) PR to fix common typos I make when entering commands on the CLI.

For example, I always typo `git ci -b` (short for `git commit`) rather than `git co -b` (short for `git checkout`) when trying to create a new git branch.

I thought fish abbreviations might be able to help out here by automatically correcting `ci` to `co`, but _only_ if I have typed `git ci -b`.

Is something like this already possible?

**Comment by faho** [comment]
I'm gonna redirect you to #9411, where abbreviations for your specific command (in this case "git") were discussed, and which also included explanations for how to do it *now* - the trick is to check `commandline`
