### ISSUE TITLE
ssh completions show terminal garbage

### ISSUE THREAD

**Issue by rocketraman** [fish-shell/fish-shell#9752]
On my system ssh completion produces garbage on my terminal like this (though it does seem to work if I ignore the garbage output):

```
ssh fedoracat: '^/dev/null': No such file or directory
cat: '^/dev/null': No such file or directory
cat: '^/dev/null': No such file or directory
cat: '^/dev/null': No such file or directory
cat: '^/dev/null': No such file or directory
cat: '^/dev/null': No such file or directory
cat: '^/dev/null': No such file or directory
cat: '^/dev/null': No such file or directory
cat: '^/dev/null': No such file or directory
cat: '^/dev/null': No such file or directory
cat: '^/dev/null': No such file or directory
cat: '^/dev/null': No such file or directory
cat: '^/dev/null': No such file or directory
ssh fedora-coreos-01
```

Here is the asciinema recording: https://asciinema.org/a/Pbew5WNIIdme52rZTDLIeYaBC.

Environment:

```
$ fish --version
fish, version 3.6.1

$ echo $version
3.6.1

$ uname -a
Linux edison 6.2.11-300.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Apr 13 20:27:09 UTC 2023 x86_64 GNU/Linux
```

On a shell without third-party customizations this works perfectly fine, so hints about how I can debug what customization is causing this problem would be useful.

**Comment by faho** [comment]
Run `fish_delta ssh`, that will probably tell you you have an outdated ssh completion script installed.

If it doesn't, go through the output of `fish_delta`, and see where it still does `^/dev/null`, and replace that with `2>/dev/null`.

**Comment by rocketraman** [comment]
@faho  `fish_delta ssh` returns no output at all.

**Comment by faho** [comment]
In that case, go on and run `fish_delta` without arguments, like I wrote.

Or just go through your config with `grep -r '\^/dev/null' ~/.config/fish/`.

**Comment by rocketraman** [comment]
Looking through the output of `fish_delta` with no args points me to `__fish_print_hostnames`, which is loaded from a custom file which has this helpful comment I created for myself :-)

+## This is a workaround for https://github.com/fish-shell/fish-shell/issues/4253
+## Remove it once we upgrade to fish 2.7.1

And removing that file does indeed fix the problem.

Thanks for the help!
