### ISSUE TITLE
CD with CDPATH doesn't echo the new directory path

### ISSUE THREAD

**Issue by evert-mouw** [fish-shell/fish-shell#9756]
_fish, version 3.6.1 | xterm-256color | XFCE on Arch_

Changing directory to a path specified in `$CDPATH` is a bit different than a "normal" `cd`, as one kinda jumps through the filesystem hierarchy. This could surprise users that expect to stay in some hierarchy. That's why Bash prints/echoes the new directory path after `cd`-ing into such a directory. Fish shell does not.

Request: (Optionally) output the new directory path then changing directory (cd) using $CDPATH.

**Comment by faho** [comment]
I'm going to reject this one. `cd` printing things is weird, and the prompt shows you the directory.
