### ISSUE TITLE
CMake Error at cmake/Rust.cmake:4 (include):

### ISSUE THREAD

**Issue by abhigenie92** [fish-shell/fish-shell#9762]
I don't have root privileges on my os. It's Debian 9.

```
cmake -DCMAKE_INSTALL_PREFIX=$HOME/local ..

-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to default 'RelWithDebInfo'
CMake Error at cmake/Rust.cmake:4 (include):
  include could not find load file:

    FetchContent
Call Stack (most recent call first):
  CMakeLists.txt:27 (include)


CMake Error at cmake/Rust.cmake:9 (FetchContent_Declare):
  Unknown CMake command "FetchContent_Declare".
Call Stack (most recent call first):
  CMakeLists.txt:27 (include)
```

**Comment by faho** [comment]
FetchContent requires cmake 3.11. Debian 9, released in 2017 and EOL since 2020 (including security updates! even the long term support ran out in 2022) has an older version.

You need to upgrade, for multiple reasons.

**Comment by abhigenie92** [comment]
How can avoiding building to install if I don't have  root privileges?

**Comment by zanchey** [comment]
Yeah, we don't have a great answer for that yet. Building an AppImage (#6475) is the plan in the long term. There are some unofficial AppImage builds out there but I can't vouch for their quality.

You can download the dpkg and extract it somewhere, but it might be fiddly to get right.

**Comment by krobelus** [comment]
it's easy to install latest cmake without root privileges. They offer binary tarballs
