### ISSUE TITLE
Use tab instead of spaces for interactively defined functions

### ISSUE THREAD

**Issue by TheDcoder** [fish-shell/fish-shell#9766]
I'd like to have an option to make `fish` use a single tab character instead of 4 space characters for indentation in functions which are defined interactively and also by `alias`.

I'm not trying to start a flame war but I absolutely do not like using 4 characters instead of just 1 for indentation, I use tabs even in Python scripts.

So an option (universal variable) to enable this behavior would be very nice, otherwise I'd have to use `funced` to do the job manually.

**Comment by faho** [comment]
No thanks, we've decided on spaces - and the tab key is used otherwise.

**Comment by TheDcoder** [comment]
May I ask how it was decided? Was it a purely personal choice or were there any objective reasons behind it?

**Comment by faho** [comment]
We don't do options like that so we have to decide on one. fish_indent, our autoformatter, does spaces and adding an option makes it worse.

**Comment by TheDcoder** [comment]
I understand, I do recall reading "configuration is the root of all evil" or something along those lines in the documentation :slightly_smiling_face:

I tried an interesting experiment by defining a `fish_indent` wrapper function which would replace all the spaces with tabs in the output:
```
function fish_indent
command fish_indent $argv | string replace '  ' '\t'
end
```

However this doesn't seem to be working, as the alias function I created for testing still used spaces... so I assume fish is calling the indent program directly? Perhaps you can change the behavior to make it run via the shell instead so that we can replace it with our own formatting functions?

**Comment by TheDcoder** [comment]
@faho I just noticed that `alias` produces excessive whitespace in the generated function:
```
> alias foo bar
> functions foo
# Defined via `source`
function foo --wraps=bar --description 'alias foo bar'
  bar $argv
        
end
```
It seems to be inserting an extra blank line before the end of the function with 4 indents (8 spaces)! What's up with that? :thinking:
