### ISSUE TITLE
sudo does not recognize variables exported by Fish

### ISSUE THREAD

**Issue by simonbcn** [fish-shell/fish-shell#9769]
Fish version 3.6.1
Linux cachyos 6.3.0-5-cachyos-lto (_Arch Linux-based distribution_)

I have created the following variables in Fish:
```
set -Ux EDITOR micro
set -Ux SUDO_EDITOR micro
```

But when I run `sudo visudo` it does not recognize any of these variables:
```
$ sudo visudo
visudo: no editor found (editor path = /usr/bin/vi)
```

**Comment by zanchey** [comment]
This is by design in sudo, for security reasons.

You can either set the `env_editor` or the `editors` option in the `sudoers` file.

See the [visudo(8) documentation](https://manpages.ubuntu.com/manpages/impish/en/man8/visudo.8.html) for details.

**Comment by simonbcn** [comment]
However if I export those variables with Bash and ZSH, it does work.

**Comment by zanchey** [comment]
The output of `set --show EDITOR` and `type sudo` may be helpful.

I suspect it is because you also have an exported global variable `EDITOR` which is shadowing the universal variable, but you should at least get a warning when you do that.

**Comment by simonbcn** [comment]
```
$ set --show EDITOR
$EDITOR: set in universal scope, exported, with 1 elements
$EDITOR[1]: |micro|
$EDITOR: originally inherited as |micro|

$ type sudo
sudo is /usr/bin/sudo
```

**Comment by zanchey** [comment]
The difference between `env` output in bash and fish might be instructive, but I've not got a lot of other ideas.

**Comment by simonbcn** [comment]
```
$ echo $PATH
/usr/local/sbin /usr/local/bin /usr/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl

$ echo $SUDO_EDITOR
micro

$ echo $EDITOR
micro

$ which micro
/usr/bin/micro
```

**Comment by simonbcn** [comment]
I used ZSH and it worked perfectly. The executables of the editors are in the normal path: `/usr/bin`
The output of all messages in this issue are from Fish.

The problem is: _how do you create environment variables in Fish?_

**Comment by faho** [comment]
>The problem is: how do you create environment variables in Fish?

You use `set -x`, optionally with a scope. Like you did here. Your $EDITOR variable is correctly set and exported. That isn't where the problem lies.

>The output of all messages in this issue are from Fish.

What are $EDITOR/$SUDO_EDITOR and $PATH in zsh? What does `type sudo visudo` say there and in fish?

On one of my systems, visudo does in fact ignore the environment variables (you're expected to set the "env_editor" setting), so one possibility is you have a different visudo. It is also possible for visudo to have a list of "safe" editors, where it'll ignore everything else. You are using micro in zsh as well?

**Comment by simonbcn** [comment]
The problem is not Fish. I don't know what is. But I've solved editing `sudoers` file.
