### ISSUE TITLE
fish --no-execute reports "Unknown command" for functions

### ISSUE THREAD

**Issue by paynechu** [fish-shell/fish-shell#977]
I reported here before.
https://github.com/dag/vim-fish/issues/16#issuecomment-23253056

**Comment by krader1961** [comment]
Relabeling this from "bug" to "enhancement" because the current behavior seems reasonable and is not in contradiction of the documentation. Whether we can provide a better experience is TBD.

**Comment by actionless** [comment]
what about having sorta shim loaded when running `fish -n `

so in that shim `abbr` and `alias` would be defined

**Comment by ulidtko** [comment]
> Relabeling this from "bug" to "enhancement" because the current behavior seems reasonable and is not in contradiction of the documentation

Please let me disagree. The current behavior, by far, doesn't seem reasonable.

There can be no valid reason to flag errors when "syntax checking" code which *works correctly*, runs perfectly fine; this isn't *linting*.

`--no-execute` is broken, and should be clearly labelled as such. See #6484.

**Comment by actionless** [comment]
thanks a lot! works for me now
