### ISSUE TITLE
$PATH is different when using ssh with non-login shell on Mac OS

### ISSUE THREAD

**Issue by stephane-archer** [fish-shell/fish-shell#9775]
Hi, my `$PATH` is not the same when using ssh, why and how to fix this?
For context, I'm on an Intel Mac
```
ssh localhost 'md5sum --version'
fish: Unknown command: md5sum
```
`md5sum` is located in:  `/usr/local/bin/`
```
echo $PATH
/usr/local/Cellar/bison/3.8.2/bin /usr/local/sbin/ /usr/local/opt/fzf/bin /usr/local/bin /System/Cryptexes/App/usr/bin /usr/bin /bin /usr/sbin /sbin /Library/Apple/usr/bin /usr/local/go/bin /Users/fractale/go/bin
```
```
ssh localhost 'echo $PATH'
/usr/local/Cellar/bison/3.8.2/bin /usr/local/sbin/ /usr/local/opt/fzf/bin /usr/bin /bin /usr/sbin /sbin
```
so with ssh `/usr/local/bin` is missing, I don't know why
maybe I didn't use properly `fish_add_path` when I added `/usr/local/bin` in the past? I don't see things about it in `config.fish`

**Comment by stephane-archer** [comment]
Dear @faho thank you for your answer.
I didn't expect `ssh` to pass any environment variables.
I was expecting `fish` to load the same config (having the same `$PATH`) when I open a terminal using iTerm or if I ssh to my laptop.
`fish` should be my default shell also for `ssh`
```
ssh localhost 'echo $SHELL'
/usr/local/bin/fish
```

**Comment by ridiculousfish** [comment]
I wonder if ssh is not making a login shell. What does `status --is-login; echo $status` show when run over ssh?

fish will add entries from `/etc/paths` and `/etc/paths.d` but only with a login shell.

**Comment by faho** [comment]
As I was told, shells do indeed only read /etc/paths in login shells, yes.

**Comment by ridiculousfish** [comment]
fish does not read `/etc/paths` in non-login shells because it's assumed that the parent shell (whatever is running fish) has already set up a proper $PATH.

I'll experiment with my Mac.

**Comment by stephane-archer** [comment]
one solution I found but is not working perfectly is:
in `/private/etc/ssh/sshd_config` add `PermitUserEnvironment PATH,LANG`
then in `~/.ssh/environment` add the following line `setenv PATH /Users/kyb/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin;`

now when I run `ssh localhost 'md5sum --version'` I have the following output
```
Bad line 1 in /Users/fractale/.ssh/environment
Bad line 2 in /Users/fractale/.ssh/environment
Bad line 3 in /Users/fractale/.ssh/environment
md5sum (GNU coreutils) 9.2
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Ulrich Drepper, Scott Miller, and David Madore.
```
so the `PATH` has been changed but I got some errors that I think come from `fish` because if I write `PATH=/Users/kyb/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin` `fish` complains about the equal sign and ask to use `set`

`~/.ssh/environment` has the following content:
```
setenv SSH_AUTH_SOCK /var/folders/w0/mj3pys6x27x88j79zgxw70sm0000gp/T//ssh-Ec7NKB5sUPDB/agent.2569;
setenv SSH_AGENT_PID 2571;
setenv PATH /Users/kyb/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin;
#echo Agent pid 2571;
```

**Comment by faho** [comment]
>  in /private/etc/ssh/sshd_config add PermitUserEnvironment PATH,LANG

This is typically not a good idea. $PATH is very likely to not make sense across different systems.

So, unless you can guarantee that you will only ever ssh to this system from itself you shouldn't do this.

>~/.ssh/environment has the following content:

The ssh man page says it

> adds lines of the format “VARNAME=value” to the environment if the file exists and users are allowed to change their environment

So it would appear to be handled by ssh itself, and in my tests that's how it works.

>~/.ssh/environment has the following content:

In my tests (fish as the user's $SHELL and `PermitUserEnvironment yes` in sshd_config) this needs to be `VAR=VAL`.

Also most of this is autogenerated and extremely likely to change - the agent pid for example. Unless you've arranged to write it there automatically that seems to be unhelpful.

> I got some errors that I think come from fish because if I write PATH=/Users/kyb/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin fish complains about the equal sign and ask to use set

That would be a fish error but I can't reproduce it. Have you told fish to try reading ~/.ssh/environment or something?

Note the errors you get here are "Bad line 1 in /Users/fractale/.ssh/environment" - which is very much *not* a fish error, and I *can* reproduce that one if I use `setenv`, which would match the ssh docs.

----

Anyway, there is a much simpler solution: Just use `fish_add_path`. Maybe just in config.fish when used over ssh or in a login shell.

```fish
if status is-login; or set -q SSH_TTY
    fish_add_path --path /usr/local/bin
end
```

**Comment by stephane-archer** [comment]
hi @faho , thank you for helping me, I added the following code to my `config.fish`:
```
if status is-login; or set -q SSH_TTY
    fish_add_path --path /usr/local/bin
end
```
But I can't still see it in my `$PATH` during non-login shell:
```
ssh localhost 'echo $PATH'
/usr/local/Cellar/bison/3.8.2/bin /usr/local/sbin/ /usr/local/opt/fzf/bin /usr/bin /bin /usr/sbin /sbin
```
I imagine `config.fish` is not loaded during non-login shell?

**Comment by stephane-archer** [comment]
just to recap the situation:

On mac os, if I do `ssh localhost 'md5sum --version'` the `md5sum` command located in `/usr/local/bin` is not found.

This path is listed in `/etc/paths` but this config file is not read by the shell because the command above creates a non-login shell, so the shell expects the caller to have already set up the `PATH`

How do you update the `PATH` value to include `/usr/local/bin` in that case?

**Comment by faho** [comment]
>I imagine config.fish is not loaded during non-login shell?

No. config.fish is loaded *always* - whether the shell is a login shell or interactive or both or neither.

It appears when running non-interactively ssh doesn't set SSH_TTY - it sets $SSH_CLIENT, you can check that.

**Comment by stephane-archer** [comment]
```
if status is-login; or set -q SSH_CLIENT
    fish_add_path --path /usr/local/bin
end
```
Did the trick! Thank you so much!
PS: SSH_CLIENT has a "strange value", I'm not sure if it's normal
```
ssh localhost 'echo $SSH_CLIENT'
::1 53049 22
```

**Comment by faho** [comment]
> PS: SSH_CLIENT has a "strange value", I'm not sure if it's normal

`::1` is ipv6 for localhost, 22 is the normal ssh server port, I'm assuming 53049 is the "local" client port (because it's in the ephemeral port range).

>Did the trick! Thank you so much!

Alright, I'm declaring this answered then.
