### ISSUE TITLE
Moving history file to XDG_STATE_HOME?

### ISSUE THREAD

**Issue by hukka** [fish-shell/fish-shell#9785]
The history file is stored under $XDG_DATA_HOME. I consider that folder to be the user local equivalent to /usr/share, that is, it is for install specific, immutable data files (might be changed in upgrades, but not in use). Previously software have had to make a choice between storing install specific, changing files there, and the $XDG_CONFIG_HOME. The advantage of having only config in the config, is that syncing between machines is convinient. The downside is that backups are inconvenient, either having to specify every distinct file/folder that needs backing up (things that cannot be restored by reinstalling the software), or having to back up lot's more than is really needed.

More appropriate place would be the relatively recently added $XDG_STATE_HOME which [the XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) defines as

>  The $XDG_STATE_HOME contains state data that should persist between (application) restarts, but that is not important or portable enough to the user that it should be stored in $XDG_DATA_HOME. It may contain:
    - actions history (logs, history, recently used files, …)
    - current state of the application that can be reused on a restart (view, layout, open files, undo history, …)
    
Granted, it is not exactly uncommon for software to keep constantly changing files under .local/share, but many also allow this to be configured, unlike fish, so the problem is just a matter of defaults with them.

**Comment by faho** [comment]
I do not believe we want to change the history location. Moving it now is awkward and for what we use XDG_DATA_HOME it's also not *wrong*. We already keep config in $XDG_CONFIG_HOME, so $XDG_DATA_HOME is used for history and generated completions, which isn't "lots more" to back up. It's not very large compared to other things in XDG_DATA_HOME - like steam's entire installation, or your trash directory, or my emacs packages. Plus this would be the first thing on my system that uses $XDG_STATE_HOME.

> - actions history (logs, history, recently used files, …)

Shell history is quite different from e.g. editor "recently used files" history or logs - it's used for calling back previous commands, and with fish's history I use it a fair bit, without keeping aliases or functions for some commands I execute often. So I wouldn't classify it as as unimportant as "I opened ~/.foorc recently".

Sorry, but I don't think it fits and I don't want to have an awkward upgrade cycle where the files are moved. That's a no.

**Comment by hukka** [comment]
My point on the large backup size wasn't about fish, but exactly what else is there: pretty much complete installations of software (the data files are often larger than the binaries). That makes it difficult to just categorically back up whole $XDG_DATA_HOME, but instead have to rely on choosing each directory separately.

Making the history file folder configurable would help with this. While it still requires software specific configuration, it's easier in the software using the configs, than in backup solutions.

**Comment by faho** [comment]
$XDG_STATE_HOME, by its definition, is for things *less* important than $XDG_DATA_HOME - meaning it is for stuff you are *less* likely to want to back up.

If you backed up $XDG_STATE_HOME and it was actually used, you would get editor undo files and such in your backup. It doesn't fit. It's not the right directory. 

Now I have never actually seen a ~/.local/state directory, which tells me that it's not really used, but that just means more people will miss it when doing their backups.

As an alternative, make your ~/.local/share/fish a symlink.
