### ISSUE TITLE
fish_update_completions creates invalid files if man file is duplicated

### ISSUE THREAD

**Issue by ThunderKey** [fish-shell/fish-shell#9787]
On Arch Linux, [jre-openjdk-headless](https://archlinux.org/packages/extra/x86_64/jre-openjdk-headless/) creates a symlink from `/usr/lib/jvm/java-20-openjdk/man`to `/usr/share/man/` therefore the command `fish_update_completions` finds all man pages twice. The first time it can generate the completions, but with the second file it ignores all commands because they are already added to `already_output_completions`.

The simplest way to reproduce this is to pass the same manpage file twice to `create_manpage_completions.py`.

In most cases this is no issue and it just ignores the last file, because it fails to generate the completions.

But for [The Silver Searcher](https://github.com/ggreer/the_silver_searcher) (`ag`) the second pass falls back to the `TypeDeroffManParser` and is able to generate a different, but incomplete, completion file and overwrites the previous one.

Reproducing the errors:
* Ignores failure of second file:
  * `python share/tools/create_manpage_completions.py --progress /usr/share/man/man1/grep.1.gz /usr/share/man/man1/grep.1.gz --stdout`
* Creates two different completion files:
  * `python share/tools/create_manpage_completions.py --progress /usr/share/man/man1/ag.1.gz /usr/share/man/man1/ag.1.gz --stdout`

I'd be happy to create a pull request to fix this but I see multiple options:
1. Skip generating the completion if the command was already created, unlike `already_output_completions` which is done per argument
2. Reset `already_output_completions` at the start of `parse_manpage_at_path`
3. Add all values in `already_output_completions` to the `built_command_output` to ensure that all options are written to the completions file.
4. Make the list of manpage files unique by using their checksums

I'm not sure how those workarounds would change the behaviour mentioned in https://github.com/fish-shell/fish-shell/blob/56743ae770c8f9b284e312344a4801c852e640f3/share/tools/create_manpage_completions.py#L84

## System Information

* `fish --version`: `fish, version 3.6.1`
* `uname -a`: `Linux ng-lenovo-2 5.15.110-2-MANJARO #1 SMP PREEMPT Thu May 4 06:51:53 UTC 2023 x86_64 GNU/Linux`
* `echo $TERM`: `xterm-kitty`

**Comment by faho** [comment]
First of all: Honestly, any effort spent here is probably better spent just writing an ag.fish completion script by hand, probably using the autogenerated version as a starting point.

That being said:

>But for [The Silver Searcher](https://github.com/ggreer/the_silver_searcher) (ag) the second pass falls back to the TypeDeroffManParser and is able to generate a different

Why does the second pass fall back while the first doesn't?

That seems to me to be the root of the issue - ideally, if we're told to run twice on the same file, we'd just come up with the same output and then it doesn't *matter* which of the two wins.

**Comment by ThunderKey** [comment]
Awesome, thank you!
