### ISSUE TITLE
Compilation error:error: failed to download from `https://crates.io/api/v1/crates/widestring/1.0.2/download`

### ISSUE THREAD

**Issue by bimizx** [fish-shell/fish-shell#9790]
➜  build git:(master) make
[  0%] Built target cargo-prebuild_fish-rust
    Updating git repository `https://github.com/fish-shell/autocxx`
    Updating git repository `https://github.com/fish-shell/autocxx-bindgen`
    Updating git repository `https://github.com/mqudsi/cc-rs`
    Updating git repository `https://github.com/fish-shell/cxx`
    Updating crates.io index
    Updating git repository `https://github.com/fish-shell/fast-float-rust`
    Updating git submodule `https://github.com/lemire/fast_float_supplemental_tests.git`
    Updating git submodule `https://github.com/lemire/simple_fastfloat_benchmark.git`
    Updating git repository `https://github.com/fish-shell/hexponent`
    Updating git repository `https://github.com/fish-shell/rust-pcre2`
    Updating git submodule `https://github.com/BurntSushi/pcre2-mirror`
    Updating git repository `https://github.com/fish-shell/printf-compat.git`
error: failed to download from `https://crates.io/api/v1/crates/widestring/1.0.2/download`

Caused by:
  [2] Failed initialization ([CONN-1-0] send: no filter connected)
make[2]: *** [CMakeFiles/_cargo-build_fish-rust] Error 101
make[1]: *** [CMakeFiles/_cargo-build_fish-rust.dir/all] Error 2
make: *** [all] Error 2

<img width="1512" alt="截屏2023-05-14 12 58 09" src="https://github.com/fish-shell/fish-shell/assets/88714373/bf3c2011-c255-4494-847a-6f7cf56c4b4a">

https://github.com/fish-shell/fish-shell/assets/88714373/121c0f5a-2059-4457-b98c-df328749d2c9

**Comment by faho** [comment]
This isn't something we can fix. This is generally the correct URL, and this generally works. I just tried and it works.

The best I can tell you is that crates.io had a momentary hangup. You can try again, and if that doesn't work the problem is likely with your internet connection or crates.io, not fish.

Sorry!
