### ISSUE TITLE
dnf completions produce "\%\{NAME\}" output when pressing tab

### ISSUE THREAD

**Issue by iRomanyshyn** [fish-shell/fish-shell#9791]
fish, version 3.6.1
Fresh installed Fedora 38

To reproduce, just try `sudo dnf install <TAB>` and it will produce `> sudo dnf install \%\{NAME\} \%\{NAME\} \%\{NAME\} \%\{NAME\} \%\{NAME\} \%\{NAME\}`, it adds `\%\{NAME\}` every time you press the TAB.

**Comment by faho** [comment]
Duplicate of #9783
