### ISSUE TITLE
Link `libfish_rust.a` into the executables with `-Wl,--gc-sections` or similar

### ISSUE THREAD

**Issue by sdroege** [fish-shell/fish-shell#9798]
Currently everything is linked without any special linker flags. This means that it will contain all of Rust's std library and all of the dependencies, including code that is not actually used.

By using `-Wl,--gc-sections` all this unnecessary code (i.e. code unreachable from public symbols) would get removed:

| `fish` | unstripped | stripped |
|-|-|-|
| current build | 42MB | 4.6MB |
| `-Wl,--gc-sections` | 39MB | 3.1MB |

For Windows this is AFAIU unnecessary (and the default), for macOS you'd have to pass `-dead_strip` instead.

When building executables/shared libraries with `cargo`, this is automatically done.

I don't really speak cmake so don't know how to properly add that to the build system.

**Comment by sdroege** [comment]
Even better :) As long as you don't do a release before that, it doesn't seem very important.

**Comment by faho** [comment]
We won't be making a half-rust release, no.

For one while the code is partially ported it's somewhere between 10% and 50% slower, it's much slower and harder to build. For another it's buggier - see e.g. #9739, I expect more issues of that type.

What exists currently in git master is strictly worse to use than 3.6.1 in almost every respect. That's not a slight against the people who have worked on it, it's just a natural side-effect of the port. Making a release like that makes no sense.

Pointing to [the plan](https://github.com/fish-shell/fish-shell/blob/master/doc_internal/fish-riir-plan.md#approach) again:

> We will do an incremental port in the span of one release

If we did a release with rust and cmake, we could think about adding this, of course - but it's likelier that we'd do a release branching from 3.6.1 with backports so it's pure C++.
