### ISSUE TITLE
outdated npm completions

### ISSUE THREAD

**Issue by m4rch3n1ng** [fish-shell/fish-shell#9799]
the completions in [/share/completions/npm.fish](https://github.com/fish-shell/fish-shell/blob/master/share/completions/npm.fish) are incorrect, outdated and incomplete. i have tested a bit and written some code and could almost have a pr ready to fix those issues (if you want). that pr would:

1. replace the built-in `npm uninstall` completions (from `$ npm completion`) with the one that is already used by `yarn` for local packages and a new one for global packages (`npm uninstall -g`)
2. update and remove outdated options and commands
3. add missing command aliases, commands and options

since this is a more drastic change than just a one-line fix (and npm has quite a large number of commands and aliases) i thought it would probably be better to open an issue first so i know if i should make the pr.

if i make the pr and it gets merged i could also update and expand on the yarn completions, but since yarn is much less used and seems more up-to-date i wanted to fix npm first

let me know if i should open that pr. ty.

```
$ fish --version
fish, version 3.6.1-519-g67d1d80f9
```

**Comment by faho** [comment]
> let me know if i should open that pr. ty.

Of course! I don't know why we would reject a well-written clear enhancement to completions.
