### ISSUE TITLE
[fish 3.1.2] Immediate write of command execution to fish history file (~/.local/share/fish/fish_history)

### ISSUE THREAD

**Issue by Drag0nFly** [fish-shell/fish-shell#9802]
Hi,

I've been struggling to find an alternative to bash's way of immediately saving a command to the history file, in order for it to show up between sessions and before the shell is terminated - i.e:

```
# Save each command right after it has been executed, not at the end of the session.
# Will write to history *only* after command has exited!
PROMPT_COMMAND="history -a"
```

Is this something fish currently supports? (if so, I am sorry if I missed it in the docs). As I continually have a number of fish sessions going, it would be very beneficial to have the history visible between them.

Currently, only the commands typed in the current active shell is visible in fish's command history (either when running `history -Rt`, or when doing syntax completion typing parts of the command(s)

**Comment by faho** [comment]
You want `history merge`.

You also want to update fish, as 3.1.2 is 5 releases (excluding patch releases) and 31% of all commits ever made to fish behind.
