### ISSUE TITLE
When using fish as my shell in gnome-terminal, i can't select text in minecraft

### ISSUE THREAD

**Issue by KwaiTushan** [fish-shell/fish-shell#9810]
- fish version: fish, version 3.6.1
- OS: fedora38, gnome41,mutter44.1
- Minecraft launched with bash script, executed in fish shell

When using fish as my shell in gnome-terminal, Minecraft can't select text

because when i try to use ctrl+A, it select all text in chat section, and an 'A' is typed, which overwrite all contents i've just selected

(Switched to bash solved that)

**Comment by faho** [comment]
Well, what's the bash script? What is your fish configuration? Have you tried without, like the issue template asks you?

This points towards fish either keeping control of the terminal, which it typically doesn't do, or not resetting it properly before handing it over, which it also typically doesn't.

**Comment by faho** [comment]
Alright, I just downloaded and installed Minecraft "Java Edition" again, and just ran the stock launcher. I opened a singleplayer game, selected the world name with ctrl+a, which worked, then opened chat, typed something and selected it with ctrl+a, which also worked.

It's highly suspect that a graphical window like that would be influenced by your shell choice. Possibilities include language (which might affect which keyboard layout it thinks you have), or just general weirdness with your launcher script.

That means we need the script, and you to try to narrow it down to your config or environment differences - run `env` in both fish and bash and compare the output. `env > /tmp/fish` and `env /tmp/bash`, then `diff -u /tmp/fish /tmp/bash`. If you post the output here feel free to redact it so we don't see private information.

**Comment by KwaiTushan** [comment]
First of all, thank you for download it again just because of my issues, but it's already too late here(night), I'll post inxi info and env, scripts here tomorrow.

Thanks again for your help

**Comment by KwaiTushan** [comment]
Also, when switching to i3 it's normal with fish, so i think it's a gnome problem

**Comment by KwaiTushan** [comment]
Ok, i found the solution it self

1. My XIM is not set properly, it should all be fcitx

thus add these in /etc/environment
```
GTK_IM_MODULE=fcitx
QT_IM_MODULE=fcitx
XMODIFIERS=@im=fcitx
```

2. I don't why but it seems that gnome has something to do with left CTRL key, when using right CTRL everything is fine, I guess this is something related to keybinding in minecraft or minecraft
