### ISSUE TITLE
cd does not accept path with colons

### ISSUE THREAD

**Issue by cobrafast** [fish-shell/fish-shell#9815]
Fish version: 3.6.1

```
$ cd /sys/bus/pci/devices/0000:00:00.0
cd: The directory '/sys/bus/pci/devices/0000.00.00.0' does not exist
```

Colons seemingly got implicitly replaced by dots hence the command doesn't work.

Other commands may be affected too.

**Comment by Xiretza** [comment]
Can you reproduce it without custom configuration as described in the issue template?

**Comment by cobrafast** [comment]
I cannot reproduce it with a clean fish. The OMF plugin "cd" was the culprit. Thanks for the hint.
