### ISSUE TITLE
fish_add_path is not persistent

### ISSUE THREAD

**Issue by xgnxs** [fish-shell/fish-shell#9819]
> fish 3.6.1
> macos ventura 13.3.1
> iterm2 3.4.19
> fish without third-party customizations did not affect behavior.

Adding a path to `$fish_user_paths` using `fish_add_path` with default (no) args no longer permanently adds the path, the path is only added for that session/instance. According to the documentation (and what has worked in the past), all that should be needed is `fish_add_path /some/path` for `/some/path` to be permanently added to `$fish_user_paths`.

ex:

```
> fish_add_path /Applications/Postgres.app/Contents/Versions/latest/bin
> psql
psql (15.3)
Type "help" for help.
```

open a new tab/terminal instance

```
> psql
fish: Unknown command: psql
```

do I now need to include `-g` or `-U` when adding a path via `fish_add_path`?

Thank you!

**Comment by bakotaco** [comment]
FYI the asdf issue that caused this has been solved in asdf v0.14.0. `asdf.fish` no longer uses `$fish_user_paths`, but modifies `$PATH` directly to avoid these kind of issues.
