### ISSUE TITLE
Tmux Prints [I[O[I[O[I[O....

### ISSUE THREAD

**Issue by blueray453** [fish-shell/fish-shell#9840]
fish, version 3.6.1
Zorin OS 16.2
Alacritty
% echo $TERM
xterm-256color
% uname -a
Linux ismail-zorin 5.15.0-73-generic #80~20.04.1-Ubuntu SMP Wed May 17 14:58:14 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

I have tried fish without third-party customizations.

**Steps To Reproduce:**

1. Run Fish inside Tmux.
2. Run Command `tmux display-message -p '(#{client_session}(#{session_windows})#{window_index}-#{window_name})'`

It will now show [I[O[I[O[I[O... If I click outside the terminal then this printing accelerates. 

![Peek 2023-06-10 06-06](https://github.com/fish-shell/fish-shell/assets/855297/d9069fd0-f761-4b66-98ea-bfaee3cf254c)

I have tried it with both bash and zsh, the issue is not there.

**Comment by faho** [comment]
This is tmux focus reporting. Fish turns it on automatically to use it as an event source, and the way it works is that tmux sends input to fish, which is typically just handled via a binding.

You need to bind that as well. The default is:

```fish
bind --preset \e\[I 'emit fish_focus_in'
```

which turns it into the `fish_focus_in` event. If you want it to do nothing, bind it to `true`.
