### ISSUE TITLE
`ranger` stops working after running `exec echo` inside `fish` sub-process

### ISSUE THREAD

**Issue by altermo** [fish-shell/fish-shell#9851]
```
fish, version 3.6.1
alacritty
ranger version: ranger 1.9.3
 Python version: 3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429]
 Locale: en_US.UTF-8
Linux archlinux 6.3.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 14 Jun 2023 20:10:31 +0000 x86_64 GNU/Linux
```
## Steps to reproduce:
Run `alacritty -e ranger`
Inside ranger run `:shell fish`
Inside fish run `exec echo`
After doing this `ranger` stops responding and goes up to 100% CPU.

**Comment by faho** [comment]
If *ranger* goes up to 100% CPU, have you considered filing this as a ranger bug?

**Comment by faho** [comment]
I can't reproduce this - in my case what happens is ranger gets a SIGTTOU and is suspended, which indicates that it doesn't reacquire the terminal after the child has exited.

**Comment by faho** [comment]
Yup, strace shows ranger getting a SIGCHLD (because fish died), and in response trying to set the terminal modes again:

```
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=5055, si_uid=1000, si_status=0, si_utime=12 /* 0.12 s */, si_stime=3 /* 0.03 s */} ---
write(1, "\33[?1h\33=", 7)              = 7
ioctl(1, TCSETSW, {c_iflag=IUTF8, c_oflag=NL0|CR0|TAB0|BS0|VT0|FF0|OPOST, c_cflag=B38400|CS8|CREAD, c_lflag=ISIG|ECHOE|ECHOK|IEXTEN|ECHOCTL|ECHOKE, ...}) = ? ERESTARTSYS (To be restarted if SA_RESTART is set)
--- SIGTTOU {si_signo=SIGTTOU, si_code=SI_KERNEL} ---
--- stopped by SIGTTOU ---
```

This is missing an `ioctl(0, TIOCSPGRP, [PID])` - `tcsetpgrp()` - before the `ioctl(, TCSETSW...`.

Since that is something that ranger should do *anyway* - a subprocess can get it to suspend - I'm calling this one a ranger bug.
