### ISSUE TITLE
Running a script using it's path and through $PATH lookup is different

### ISSUE THREAD

**Issue by zaquest** [fish-shell/fish-shell#9852]
Hello. I'm trying to switch to fish shell and I have a tiny script that behaves unexpectedly. The script is

```
zaquest@zaquest-desktop ~> cat $(which diff)
#!/bin/sh
diff="/usr/bin/diff"
if [ -t 1 ]; then
  $diff -u --color=always "$@" | less -RF
else
  $diff "$@"
fi
```

When script is run using absolute or relative path it outputs diffs with color as expected, but when it's run using just `diff` it shows no colors. I managed to verify that the correct branch is run, the tty one in both cases.

```
$ fish --version
fish, version 3.6.1
$ uname -a
Linux zaquest-desktop 6.3.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 14 Jun 2023 20:10:31 +0000 x86_64 GNU/Linux
$ echo $TERM
alacritty
```

I did try it with `sh -c 'env HOME=$(mktemp -d) fish'` and it's the same. I also tried it in virtual terminal with the same result.

https://asciinema.org/a/kidleAko5En8Bwh9yxJvHO3qS

**Comment by zanchey** [comment]
My first guess is that running it without the path is just running `/usr/bin/diff`. Can you show the contents of `$PATH`?

**Comment by zaquest** [comment]
```
$ echo $PATH
/home/zaquest/.local/bin /usr/local/bin /usr/bin /bin /usr/local/sbin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl
```

It runs the right script as `cat $(which diff)` shows, and I can see the effect of the `-u` option. Moreover it shows colors in both cases unless `| less -RF` is there.

**Comment by faho** [comment]
Okay, forget about `which`. `which` is an external tool, and it's fairly terrible.

Use `type -a diff`. What does that say?

**Comment by zaquest** [comment]
```
~> type -a diff
diff is a function with definition
# Defined in /usr/share/fish/functions/diff.fish @ line 3
function diff
        command diff --color=auto $argv

end
diff is /home/zaquest/.local/bin/diff
diff is /usr/local/bin/diff
diff is /usr/bin/diff
diff is /bin/diff
```

Thank you @faho now I see that the default function overrides `--color` option with `auto` and `diff` decided to not output colors when `less` is in place.
