### ISSUE TITLE
Compile and install error

### ISSUE THREAD

**Issue by jack9603301** [fish-shell/fish-shell#9853]
When compiling and installing, execute the following instructions:

```
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release
make
```

It will fail in a certain part, it seems to prompt to find libclang.so, I hope to use gcc, is there any way?

**Comment by faho** [comment]
Current fish master is in the process pf veing rewritten in rust and therefore needs libclang.

You can build the 3.6.1 release or install packages from https://fishshell.com/ instead.

**Comment by jack9603301** [comment]
@faho  When will this transplant work be completed?

**Comment by faho** [comment]
When it's done, some time before the next release.

I can't be more specific than that.

**Comment by jack9603301** [comment]
@faho okay thanks
