### ISSUE TITLE
begin should error with any arguments

### ISSUE THREAD

**Issue by ridiculousfish** [fish-shell/fish-shell#986]
As seen in #973, it's easy to accidentally pass arguments to `begin` that are just ignored. This should be an error.

We might do the same thing with `end`, but redirections to end are very common and useful. So `end` should error on arguments but allow redirections.

**Comment by cben** [comment]
Hmm.  I've been using `begin COND1; and COND2; end`, believing it's a valid shorthand.  It does work:
```
~ $ begin false; and true; end; echo $status
1
~ $ begin true; and true; end; echo $status
0
```
I suspect requiring `begin;` will break some working code.  Is there actual harm in the current behavior (except "two ways to do a thing")?

`end` ignoring anything sounds safe to fix.

**Comment by krader1961** [comment]
>  I've been using begin COND1; and COND2; end, believing it's a valid shorthand.

Which is understandable if you think of __begin__ and __end__ as syntax similar to the __{__ and __}__ used in Algol like languages. But if we're going to treat those tokens as pure syntax to delimit a block of commands then there isn't any reason not to allow a command to follow a bare `end` as well as `begin`.

The best argument I can think of for strictly treating them as, currently no-op, commands is that allows us to extend them in the future with options that would affect the blocks behavior. Unfortunately, given that this inconsistency with the docs has been known to exit for more than two years I think it's too late to close the barn door. The only question is to make the handling of __end__ consistent with __begin__ (i.e., allow a command without an intervening newline or semicolon) or change the implementation to throw a syntax error.

**Comment by faho** [comment]
This has just occured to @balupton on gitter with the following:

```fish
begin test "$a" -eq 1; and echo "a is 1"; end or; begin echo "a is not 1"; and echo "a is still not 1"; end
```end

Note the `end or`.

`begin` and `end` actually behave slightly differently here. Like you can see in 

```fish
begin echo something; end
```

the argument to `begin` - the `echo something` is executed. That means it _does_ work as a shorthand. It's a bit unclean but not actively _wrong_.

For `end` on the other hand:

```fish
begin echo something; end echo some other thing
```

It's not executed, and there's no warning, which makes that case above so annoying - the `end or` turns the `or` into a noop.

Which makes `end` much more of a problem.

**Comment by ridiculousfish** [comment]
I made arguments to `end` produce an error in a39c57c1b65d91973e781b29bf67c04815779ddc.

Let's leave the `begin` behavior as it is, it seems relatively harmless.
