### ISSUE TITLE
Completions for dnf5

### ISSUE THREAD

**Issue by mochaaP** [fish-shell/fish-shell#9862]
<https://fedoraproject.org/wiki/Changes/ReplaceDnfWithDnf5>

DNF5 just landed in Fedora rawhide and provides the `dnf` command by default.
Since DNF5 is built on libdnf5 and introduced many changes, it should now be a good time to start providing completions for the `dnf5` command.

**Comment by faho** [comment]
According https://dnf5.readthedocs.io/en/latest/changes.html#changes-on-the-command-line it's mostly a removal of unused features.

That means it shouldn't really impact us much, for now - we can't really remove the old syntax until nobody uses it anymore (i.e. until only Fedora versions with dnf5 are still supported).

**Comment by mochaaP** [comment]
We could provide a `dnf5.fish` though. This won't break the original dnf, while providing a more updated completion for dnf5 users.

**Comment by mochaaP** [comment]
Vendors could ship an config file with `alias dnf=dnf5` if dnf5 was the default provider for `/usr/bin/dnf`

**Comment by faho** [comment]
They won't. They'll ship a symlink.

**Comment by Fenimoure** [comment]
> Vendors could ship an config file with `alias dnf=dnf5` if dnf5 was the default provider for `/usr/bin/dnf`

That is not even necessary. The users can just use dnf and dnf5 as different programs for now.

**Comment by Haskellered** [comment]
> It won't be of much use - people will keep using `dnf <TAB>`.

I know for a fact myself and several other people use dnf5 due to the speed increase, so this isn't true.

**Comment by BurnerWah** [comment]
Fedora 41 just released with DNF 5 being used, and the completions fish completions are almost fully functional already

The primary exception to that i've noticed is the `__dnf_list_installed_packages` & `__dnf_list_available_packages` functions, where the usage of `dnf repoquery` results in there not being any newlines between package names, and fish just completing one giant string containing all the package names

**Comment by NotAFile** [comment]
Can confirm, shell hangs for several seconds when `__dnf_list_installed_packages` is called

This seems to be an intentional change. From the [changelog](https://dnf5.readthedocs.io/en/latest/changes_from_dnf4.7.html) (original link does not work):

> --queryformat, --qf no longer prints an additional newline at the end of each formatted string, bringing it closer to the behavior of rpm --query

**Comment by BurnerWah** [comment]
> Can confirm, shell hangs for several seconds when `__dnf_list_installed_packages` is called
> 
> This seems to be an intentional change. From the [changelog](https://dnf5.readthedocs.io/en/latest/changes_from_dnf4.7.html) (original link does not work):
> 
> > --queryformat, --qf no longer prints an additional newline at the end of each formatted string, bringing it closer to the behavior of rpm --query
> 
> I'm not sure why this doesn't seem to affect `__dnf_list_available_packages` too, as that also uses `--qf`

you probably have `sqlite3` installed.
`__dnf_list_available_packages` tries to use an sqlite DB to get the list of available packages faster if it can, while `__dnf_list_installed_packages` does not.
https://github.com/fish-shell/fish-shell/blob/3.7.1/share/completions/dnf.fish#L20-L30

**Comment by BurnerWah** [comment]
fwiw I'm actually not sure why `__dnf_list_installed_packages` doesn't also look at the same DB, since listing the installed packages is just as slow (at least on dnf 5), and there's an `installed` table in the DB that fish uses

**Comment by Rua** [comment]
I'm running into this problem as well after doing a fresh install of Fedora 41.

**Comment by BurnerWah** [comment]
so for people who need a hotfix for this, copy the default completions into ~/.config/fish/completions/dnf.fish, and then just change `%{name}` to `%{name}\n`.
That fix is less applicable to the default completions, since those need to support dnf 4 still, but it is a fix.

**Comment by sky96111** [comment]
dnf5 officially provides bash completions and much faster than dnf4.
They use readlink to differ dnf5 and dnf4 in same alias. I think it a good solution to compatible these two version.
https://github.com/rpm-software-management/dnf5/blob/d4c74147df7764bf3f80facea8ece9907e7618a4/dnf5/bash-completion/dnf5#L22

**Comment by ridiculousfish** [comment]
Cleverly fixed via #10949

**Comment by AldanTanneo** [comment]
dnf5 doesn't use the packages.db file anymore, so when sqlite3 is installed on the system, completions still break... should this be another issue?

**Comment by zanchey** [comment]
Yes, please - any further information would be useful too

**Comment by mrostd** [comment]
When typing `sudo dnf install ` and double-tapping Tab in fish shell, it lists all available packages, flooding the terminal. This makes it appear as if the screen is cleared or a crash occurs.
