### ISSUE TITLE
`read` command, when in piping ony read once in two

### ISSUE THREAD

**Issue by componhead** [fish-shell/fish-shell#9868]
fish, version 3.6.1

Hi. I noted a weird behaviour of `read` command as in the following asciinema:

[![asciicast](https://asciinema.org/a/AEd8eaZkogoVHGWKuihY2cD1Y.svg)](https://asciinema.org/a/AEd8eaZkogoVHGWKuihY2cD1Y)

**Comment by faho** [comment]
This is a simple misunderstanding.

`read myvar` reads the input *into* the variable $myvar. It does *not* print it.

When you do `foo | read myvar | echo $myvar`, that will expand $myvar *before* the `read` is executed.

What you want is `foo | read myvar; echo $myvar`.
