### ISSUE TITLE
Provide a convenient `$basename` variable

### ISSUE THREAD

**Issue by kidonng** [fish-shell/fish-shell#9872]
I love Fish's autoload. One pattern I'm employing is:

```fish
set -l cmd (status basename | path change-extension "")

complete $cmd -s h -l help -d "A helpful description"
# or
function $cmd
    echo "Never gonna give $cmd up"
end
```

This has some benefits:

- No need to repeat the command name
- To rename a autoload function/completion, just renaming the file is enough
- Create multi-call functions

I wonder if it is valuable to save the ceremony, and let Fish provide the basename (without extension) as a handy variable, say `$basename`.

I also see two points against this:

- It's just too trivial. May be easy to implement, but most users probably would not even realize its existence. A new subcommand of `status` (`status basename2`? I don't know) is a decent middle ground.
- Giving the variable a nice name like `$basename` is a breaking change, yet putting it under `$_fish_basename` makes it less useful than just typing the command name out. However, as Fish is expecting a major release soon™️, this becomes less of an issue.

Sorry if this issue reads like a utter waste of time and energy on niche stuff!

**Comment by faho** [comment]
`status basename` already *is* the shortcut - and `$_fish_basename` has *two characters* fewer than `(status basename)`.

Code-golf is not our goal.

Sorry, I'm rejecting this.

**Comment by zanchey** [comment]
I added these to completions in 472d7efe34 as it looks like they'd been missed.
