### ISSUE TITLE
Does fish need access to .trash? warning: could not open directory '.Trash/': Operation not permitted

### ISSUE THREAD

**Issue by archywillhe** [fish-shell/fish-shell#9876]
I'm getting this whenever I open fish. 

```
warning: could not open directory '.Trash/': Operation not permitted
```

I check my zshrc and all is good; Why is Fish accessing my trash?

**Comment by archywillhe** [comment]
this happens out of the blue; every command I made in FIsh now gives me this error

**Comment by faho** [comment]
Fish does not by itself access `.Trash/`, no.

This will be down to your configuration.

**Comment by faho** [comment]
Alright, question was answered, closing. Fish does not read ".Trash" by itself, so if it does that's because you or something you installed told it to.
