### ISSUE TITLE
test -z and test -n give same output when command substitution returns an empty string. 

### ISSUE THREAD

**Issue by social-anthrax** [fish-shell/fish-shell#9877]
```
fish version: 3.6.1
$TERM: xterm-256color
OS: Darwin 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64

Behaviour exhibited without third party: True
```

Running test -z and test -n can both return true when using command substitution. Using test with string literals still works as expected

Reproduction:
```
lyra@Owl ~> test -n (echo -n "")
lyra@Owl ~> echo $status
0
lyra@Owl ~> test -z (echo -n "")
lyra@Owl ~> echo $status
0

lyra@Owl ~> test -z ""
lyra@Owl ~> echo $status
0
lyra@Owl ~> test -n ""
lyra@Owl ~ [1]> echo $status
1
```

I may be misunderstanding how test and command substitution works, but I would expect the top two to behave identically to the bottom two.

**Comment by faho** [comment]
[Unfortunately](https://fishshell.com/docs/current/cmds/test.html#description):

>When using a variable as an argument for a test operator you should almost always enclose it in double-quotes. There are only two situations it is safe to omit the quote marks. The first is when the argument is a literal string with no whitespace or other characters special to the shell (e.g., semicolon). For example, test -b /my/file. The second is using a variable that expands to exactly one element including if that element is the empty string (e.g., set x ''). If the variable is not set, set but with no value, or set to more than one value you must enclose it in double-quotes. For example, test "$x" = "$y". Since it is always safe to enclose variables in double-quotes when used as test arguments that is the recommended practice.

The same goes for command substitutions - `test -n "$(echo foo)"`.

This is because fish's `test` is one of the few parts to implement POSIX. It's terrible, but we can't change it now.

Sorry.
