### ISSUE TITLE
Using bat as a manpager

### ISSUE THREAD

**Issue by LevitatingBusinessMan** [fish-shell/fish-shell#9883]
fish, version 3.5.1-677-gf81e8c7de
3.5.1-677-gf81e8c7de

```SH
set -g MANPAGER "sh -c 'col -bx | bat -l man -p'"
man 2 select
```

Does not result in bat being used for paging.

See https://github.com/sharkdp/bat#man

**Comment by henrikhorluck** [comment]
It appears you are missing `--export | -x`, the variable is not exported and therefore not available https://fishshell.com/docs/current/cmds/set.html

**Comment by LevitatingBusinessMan** [comment]
Ah, I confused `-x` with `-g`. How dumb of me. Closing this.
