### ISSUE TITLE
OS X refuses to setting fish as default shell(installed via Homebrew)

### ISSUE THREAD

**Issue by tiye** [fish-shell/fish-shell#989]
```
➤➤ chsh -s /usr/local/bin/fish
Changing shell for jiyinyiyong.
Password for jiyinyiyong:
chsh: /usr/local/bin/fish: non-standard shell
```

While it works when I use the `pkg` which installed fish at `/usr/bin/fish`.

**Comment by jitendravyas** [comment]
i m alsi having same problem. what to do?

**Comment by ridiculousfish** [comment]
@jitendravyas You must add the line `/usr/local/bin/fish` to /etc/shells

**Comment by TimothyBramlett** [comment]
Solved the problem for me also.  For anyone else who encounters this I had to add `/usr/local/bin/fish` to `/etc/shells` and then I had to re-run the command:

`chsh -s /usr/local/bin/fish`

**Comment by Eragon29** [comment]
but why is fish in that location? and not in /bin/ like the other shells?
I installed zsh over brew too, and it is in /bin/

**Comment by zanchey** [comment]
The version of zsh in `/bin/zsh` is shipped with OS X; if you install from Homebrew, it will be in `/usr/local/bin/zsh` like fish.

```
$ /usr/local/bin/zsh --version
zsh 5.4.1 (x86_64-apple-darwin15.6.0)
$ /bin/zsh --version
zsh 5.0.8 (x86_64-apple-darwin15.0)
```

**Comment by geoffmacintosh** [comment]
So that's a bit confusing. By default, macOS has bash, zsh and a few others pre-installed in /bin/. Homebrew doesn't ever install to /bin/, so you'll find an out-of-date copy of zsh at /bin/zsh and the brew version in /usr/local/bin/zsh.

**Comment by Eragon29** [comment]
Oh, that actually makes sense.
Didn’t notice because I had zsh over brew too
