### ISSUE TITLE
Poor globbing performance in nfs-mounted directory with lots of subdirectories.

### ISSUE THREAD

**Issue by kaysond** [fish-shell/fish-shell#9891]
Running fish 3.6.1 on SLES 12 (with clean home dir). For additional context, please see https://github.com/IlanCosman/tide/issues/420

I have an nfs-mounted directory with ~4000 subdirectories. If I do something like `set -l glob /path/a*/`, where `/path/` has lots of subdirs starting with `a`, it takes upwards of 2 min to complete. Doing an `ls /path` even at its worst, never takes more than ~10s. I'm not sure what the globbing is doing that is slowing it down.

The globbing does not appear to cache the results between commands, even though the filesystem itself does. If I do `set -l glob /path/a*/; set l glob /path/ab*/` where the result is the same number of directories, the second glob runs instantly. When I run the same command a second time, though, it still takes 2 minutes, even though its immediately after.

**Comment by faho** [comment]
What does `strace` say? This is really gonna be one where we would need to reduce the syscalls.

You want something like `strace -c fish -c 'set foo a*'`

**Comment by faho** [comment]
Sidenote:

> The globbing does not appear to cache the results between commands, even though the filesystem itself does

Yeah, as a rule we don't do caching like that - in most cases the filesystem cache will do better than we do and cache eviction is terrible.

I don't believe a cache is the correct answer here or most other places and don't want to add it.

**Comment by faho** [comment]
Okay, you're gonna love this one, we checked if a file existed that we already knew existed.

Since we're now using the same number of syscalls as "ls", and it's all stat-ish (newfstatat vs statx), I'm gonna call this one done for now.

Thanks for filing!

**Comment by kaysond** [comment]
> Okay, you're gonna love this one, we checked if a file existed that we already knew existed.
> 
> Since we're now using the same number of syscalls as "ls", and it's all stat-ish (newfstatat vs statx), I'm gonna call this one done for now.
> 
> Thanks for filing!

Saw the same thing in strace! Thanks for the quick fix!
