### ISSUE TITLE
fish-shell + Wayland in openSUSE doesn't work

### ISSUE THREAD

**Issue by RafaelLinux** [fish-shell/fish-shell#9906]
This issue is present in `fish-shell` versions from at least 6 months ago. I checked here that no one reported it previosly, so I do it now.

Recently, I decided to give a try to Wayland, so I selected "Wayland" in SSDM desktop switcher and click "Accept" to log in, but instead Plasma desktop, a black screen was all I got.  After a lot of googling around, someone mentioned that something similar had happened to him and found out that it was related to the shell I had installed. Indeed, I had the `fish-shell `l installed and, after uninstalling it and rebooting, I was able to get past the black screen. So I didn't try to install again fish-shell.

Yesterday, another openSUSE user, related same issue en an openSUSE forum. He had installed `fish-shell ` too and after uninstall it, issue with Wayland disapeared. Someone told us that is POSIX related, but as users, we only can uninstall `fish-shell`.

Here are some related links, but sure there are more.
https://forums.opensuse.org/t/wayland-session-not-working/167751/9
https://www.reddit.com/r/openSUSE/comments/vm4a3b/plasma_wayland_session_stopped_working_after/

My system information is:
```
Operating System: openSUSE Tumbleweed 20230718
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.10
Kernel Version: 6.4.3-1-default (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-6600K CPU @ 3.50GHz
Memory: 31.3 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2
```

**Comment by zanchey** [comment]
This looks like a problem in SDDM, and there's not much that we can do except change fish to be a completely sh-compliant shell, which isn't going to happen any time soon. There is an assumption by some developers that your login shell is bash or similar, which has never been true.

As a workaround, leave your login shell set to `/bin/bash` and configure your terminal to run `/usr/bin/fish` or wherever you have fish installed.

**Comment by RafaelLinux** [comment]
Thanks for the tip. As I told you, it doesn't occur to any user to think that the problem is related to using a different shell, so I think that if you close the query implying that the solution is not in your hands, except for a patch, I will contact the KDE developers to tell them about the problem. 

Users are the ones who get hurt in situations like this, since they waste hours trying to figure out why something that in principle should not work and blaming Wayland in this case, when the problem is not in Wayland's code.

But I find it sad that it has to be the users (as I am going to do in this case) who have to be the intermediaries between different groups of developers in the open source world.

Thanks

**Comment by faho** [comment]
https://github.com/sddm/sddm/issues/1592

https://github.com/sddm/sddm/issues/1391

**Comment by RafaelLinux** [comment]
Thank you for including the references in these threads. Moreover, I had - after your last message - notified KDE, thinking that SSDM was a KDE development. Right now, I don't know if it would be wise to report it to openSUSE, because as I've seen, there are other distributions affected and it's really up to the SSDM developers to solve the problem ...
