### ISSUE TITLE
Can't exit from config.fish

### ISSUE THREAD

**Issue by Philipp15b** [fish-shell/fish-shell#991]
I have a script in my `config.fish` that automatically starts tmux for me. After closing tmux, the shell that started tmux should exit too. That does not seem to work though.

The documentation states

> If exit is called while sourcing a file (using the . builtin) the rest of the file will be skipped, but the shell itself will not exit.

It seems there is no way to exit the shell from the `config.fish` file. There should be a parameter to force exiting the shell for the `exit` builtin.

**Comment by MarkVillacampa** [comment]
After battling with this issue for a while, I've come up with this solution:

```fish
if which tmux > /dev/null; and not set -q TMUX
  exec tmux new-session -A -s main
end
```

This will either create a session named "main", or attach to it if it already exists. This way you can use the  `exec` command since you don't need the '; or' construct.

**Comment by krader1961** [comment]
We can't change the behavior without breaking backward compatibility. Since this is a niche use with simple alternatives I'm closing it.
