### ISSUE TITLE
Check whether right options are used for builtins

### ISSUE THREAD

**Issue by EmilySeville7cfg** [fish-shell/fish-shell#9912]
It would be nice to have option validation like in Nushell:

![image](https://github.com/fish-shell/fish-shell/assets/42812113/6e555616-b816-43ef-aa17-2375c40efc11)

in addition to `fish -n`. Now to explore available options I have to open an interactive Fish session and use autocomplete for a command I wanna explore options of. It's not as fast as in Nushell.

As a sidenote, there is no option validation in Bash LSP, but there are suggestions thanks to man pages:

![image](https://github.com/fish-shell/fish-shell/assets/42812113/685ce7fd-4f93-4641-b420-12c34d153b82)

**Comment by faho** [comment]
Counterpoint:

```fish
set -l regex -r
string replace $regex '^.*' ''
```

The language is too dynamic to make this feasible, sorry.

**Comment by EmilySeville7cfg** [comment]
I am not asking for validation in cases like this. I am asking for cases where options are explicitly written.

**Comment by faho** [comment]
You can override most builtins with a function - at runtime, dynamically.

The language is too dynamic to make this sort of  thing feasible from the outside.

**Comment by EmilySeville7cfg** [comment]
> You can override most builtins with a function - at runtime, dynamically.
> 
> The language is too dynamic to make this sort of thing feasible from the outside.

```bash
#!/usr/bin/env bash

head() {
  echo "Overriden builtin"
}

seq 10 | head --lines=4
```

In Bash it's possible too. In this case when I hover `head` invokation LSP tells me that it's defined in this file, but it still suggests me options for an external command:

![image](https://github.com/fish-shell/fish-shell/assets/42812113/5f5c14fe-db14-43fa-95e2-72f6b963c23c)

I guess there is no way too to determine what something is till executing script.

**Comment by faho** [comment]
Inside fish, you have completions. They will give you the options you can use, with a description.

Outside of fish, there really isn't a lot at the moment - someone could write an lsp module thing, and it could invoke fish's `complete -C` to ask fish for its completions.

But they would have to write such a thing, and I do not believe we here at the fish-shell organization are planning to do such a thing.
