### ISSUE TITLE
fish prompt flashes for a few milliseconds when clearing screen using `CTRL+l`

### ISSUE THREAD

**Issue by ayushnix** [fish-shell/fish-shell#9917]
When I clear the screen using `CTRL+l`, the fish prompt flashes for a few milliseconds. I can't observe the same behavior in bash or nushell when using the same `$TERM`s.

`fish --version`: fish, version 3.6.1
`echo $version`: 3.6.1
OS: Arch Linux
`echo $TERM`: foot, tmux-256color, and xterm-kitty

I tried running fish using `sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'` and I got the same behavior.

[Here's a recording](https://0x0.st/He58.mp4) of a terminal session that shows the flashing effect on the fish prompt (although the effect seems to be a bit slower and delayed in the video for some reason).

**Comment by faho** [comment]
When you press ctrl-l, what fish does is

1. Tell the terminal to clear the screen
2. Rerun your prompt to redraw it

That means if you notice slowness, you need to look at your prompt.

Bash has $PS1, which is just a format string and so can be redrawn much quicker. It's a trade-off.

**Comment by ayushnix** [comment]
I made the fish_prompt.fish function a simple `printf '$ '`, which is considerably simpler than bash's `$PS1`, but I'm still seeing the same issue.

**Comment by faho** [comment]
It turns out while we can't fix the latency in generally drawing a prompt, we can remove the flicker on clear specifically by drawing the old prompt first and then updating - #10044
