### ISSUE TITLE
Support for history-beginning-search-{forward,backward}

### ISSUE THREAD

**Issue by jiyinyiyong** [fish-shell/fish-shell#992]
By examining the default binds of Fish, I found Fish doesn't use `history-search-backward` for up arrow. It's quite a habit in Bash to use up arrow for that.
How can I rewrite up arrow and bind it with `history-search-backward`?

``` fish
bind \e\eOA history-token-search-backward
bind \e\eOB history-token-search-forward
bind \e\e\[A history-token-search-backward
bind \e\e\[B history-token-search-forward
bind \eO3A history-token-search-backward
bind \eO3B history-token-search-forward
bind \e\[3A history-token-search-backward
bind \e\[3B history-token-search-forward
bind \e\[1\;3A history-token-search-backward
bind \e\[1\;3B history-token-search-forward
bind \cp history-search-backward
bind \cn history-search-forward
```

The escaped characters in Fish are so hard to read, let alone figuring out which is the up arrow.

**Comment by jmerkow** [comment]
Any update on this?

**Comment by faho** [comment]
This seems to be the same as #1072.

**Comment by stahara** [comment]
Reading the `up-or-search` function, it seems to me the issue here is that `commandline -f` incorrectly mimics the `history-search-backward` readline function.  The apparent functionality (matching *anywhere* in a history line) is actually that of `history-substring-search-backward`.  Here is the relevant documentation from `readline(3)`:

> **history-search-backward**
>               Search backward through the history for the string of characters between the start of the current line and the current cursor position (the point).  The search string must match at the beginning of a history line.  This is a non-incremental search.
> 
> **history-substring-search-backward**
>               Search backward through the history for the string of characters between the start of the current line and the current cursor position (the point).  The search string may match anywhere in  a history line.  This is a non-incremental search.

**Comment by stahara** [comment]
Hm, I see the source of confusion, I think: the `bash(1)` manpage contradicts this and describes the behavior as implemented in fish.

**Comment by half-potato** [comment]
6 years later is there a solution to this? I tried fish for a while but I switched back to zsh because the substring search is never what I want and frustrates me to no end.

**Comment by ridiculousfish** [comment]
There's no binding for a history prefix search yet.

**Comment by binaryplease** [comment]
What steps would be required to implement this? I would like to give it a go, but don't know where to start.

**Comment by domdom** [comment]
I've had a go at implementing this. Would you like a PR?
