### ISSUE TITLE
#9018 fixed, but broke in 3.6.1-714 again

### ISSUE THREAD

**Issue by NextAlone** [fish-shell/fish-shell#9925]
#9018 fixed but in 3.6.1-714 version, it broke again after upgrading fish-shell through pacman on ArchLinux
```
 status fish-path
/usr/bin/fish (deleted)
```

**Comment by faho** [comment]
cc @krobelus - the rust implementation of `get_executable_path` uses rust's [std::env::current_exe()](https://doc.rust-lang.org/std/env/fn.current_exe.html), which unfortunately seems to just defer to the OS.

**Comment by NextAlone** [comment]
Hi, any progress?

**Comment by faho** [comment]
No. Typically if there is any, we'll note in the issue.

Krobelus is away for a bit.

Honestly, currently I recommend just using 3.6.1 if all you want to do is *use* the thing - it's faster and less buggy than master, and master has few features and improvements over it.

**Comment by NextAlone** [comment]
> No. Typically if there is any, we'll note in the issue.
> 
> Krobelus, who is currently the person best suited to work on it, is away for a bit.
> 
> Honestly, currently I recommend just using 3.6.1 if all you want to do is _use_ the thing - it's faster and less buggy than master, and master has few features and improvements over it.

Thanks for your advice, i'll use 3.6.1 for these days.
