### ISSUE TITLE
Inside tmux, function | less crashes fish when the function produces lots of output

### ISSUE THREAD

**Issue by alanbbr** [fish-shell/fish-shell#993]
I don't know if this is a fish problem or a tmux problem, or them not playing nicely together, but running the closest equivalent in bash, with the same tmux and Hadoop software, works. fish also works correctly outside of tmux (just an ssh connection).

set __fish_hadoop /usr/bin/hadoop

function htxt
    if test -n "$__fish_hadoop"
        hadoop fs -text $argv
    end
end

htxt /large/file | less

and fish-2.0.0-201305151006.1.x86_64 on epel-release-6-7.8.amzn1.noarch, with kernel 3.2.30-49.59.amzn1.x86_64 crashes fish. I have not verified the minimal file size needed to cause the crash, but 6GB definitely does.

**Comment by faho** [comment]
Closing in favor of #1396 - more discussion there.
