### ISSUE TITLE
Same fish_color_param produces different color in terminal

### ISSUE THREAD

**Issue by networkException** [fish-shell/fish-shell#9933]
I cannot explain this to myself: Having the same `fish_color_param` set causes a different result on two different systems.

asciinema recording a. https://asciinema.org/a/QiBgjhWsVnCMvC3VpRRmeRa6S
asciinema recording b. https://asciinema.org/a/dryrXRMpeisz5V6XW94jsS3Ye

![image](https://github.com/fish-shell/fish-shell/assets/42888162/c3094eb4-0eef-4707-be37-587db73998ec)

**Comment by zanchey** [comment]
Which terminal emulator/version are you using?

**Comment by faho** [comment]
What does `set_color $fish_color_param | string escape` say on both?

What does `fish --debug term-support -c exit` say?

The most likely ways this happens is if either fish thinks one of these can't do rgb colors but the other can, or it thinks both can't do it and the color palette they use is different.
