### ISSUE TITLE
`Ctrl+R` behavior when no matches: cancelled command

### ISSUE THREAD

**Issue by jerrygreen** [fish-shell/fish-shell#9934]
In normal bash, when no results found while using reverse-i-search (Ctrl+R), you still able to run the command you started to type.

In fish, if search fails, pressing enter just cancels the search.

I think fish should stick to bash behavior in here, – actually execute command on pressing Enter.

After all, if user wants to cancel his command, he can always press Ctrl+C.

There's no need to duplicate this behavior for Enter, basically removing other useful functionality.

**Comment by krobelus** [comment]
makes sense, good find

**Comment by josharsh** [comment]
Hey 
Is this issue still open and up for grabs?
May I pick it?

@zanchey @faho @uggedal @krobelus @jerrygreen

**Comment by faho** [comment]
> Is this issue still open and up for grabs?

As far as I know, yeah.

>  May I pick it?

Go right ahead!

---

However, @josharsh: Please don't tag random people in your comment.

**Comment by krobelus** [comment]
I don't think it should execute directly but only copy the search field text to the commandline, to be consistent with successful matches

**Comment by jerrygreen** [comment]
> I don't think it should execute directly but only copy the search field text to the commandline, to be consistent with successful matches

100% true. I didn't mean to execute it right away. You're completely right in this one

> May I pick it?

❤
