### ISSUE TITLE
The `builtin` returns true with garbage arguments

### ISSUE THREAD

**Issue by faho** [fish-shell/fish-shell#9942]
```fish
builtin -- whatever
```

will always just return true without doing anything because it hasn't been told to query (`-q`) or to list the names (`-n`) and so just does nothing.

This is not a regression in the rust version, this is how it worked in 3.6.1 as well.

Of course `builtin whatever` is the *decorator* version, and will try to run a builtin called "whatever", but as soon as you add the `--` it'll call the builtin.

The `command` and `time` builtins open their help if called like that - which also isn't *great*, tbh, because it opens a pager and I find it unexpected. I'd expect just a regular error.

In the interest of consistency, I'll make it open the help first.

(@zanchey This could be backported to 3.7.0, I'll fix it in the rust version first because it's not a big deal)

**Comment by zanchey** [comment]
@faho let me know if you still want to fix this for 3.7.0

**Comment by faho** [comment]
It's fine to skip it - it's a weird reaction to already buggy code in a small edge case, and nobody stumbled over it in practice (I found it by snooping around for `builtin -- $foo`).
