### ISSUE TITLE
Strange parsing of argument list

### ISSUE THREAD

**Issue by boxed** [fish-shell/fish-shell#9951]
fish, version 3.3.1
OS: Darwin *** 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:39:35 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8103 arm64

This is a little weird thing my (very much non-programmer) wife accidentally stumbled on. She was trying to run a curl command and missed a space between the url and the output argument, causing weird behavior. A simpler reproduction is:

```term
> cat test.py
import sys
print(sys.argv)
> python3 test.py 'foo' bar
['test.py', 'foo', 'bar']
> python3 test.py 'foo'--bar
['test.py', 'foo--bar']
```

it seems more reasonable to me to have some kind of syntax error in this situation.

**Comment by faho** [comment]
This is working as expected. Options are nothing special syntactically.

There is nothing to error out about because "test--bar" is an entirely valid argument.

**Comment by boxed** [comment]
You missed the point.

`foo 'bar'bar` is interpreted as `foo barbar`. Which is super weird! You have a start quote, and then it's thrown away at the end, and the rest of the string is just appended?

**Comment by henrikhorluck** [comment]
It might rather be the need for quoting which is causing the confusion, in fish (and bash, zsh, tcsh, and ksh) the _default_ is to be a string, so you don't need delimiting quotes, and the quotes can rather be seen as toggles for different kinds of subsitution-behavior as can be seen in the [docs](https://fishshell.com/docs/current/language.html#quotes), or as the [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html#tag_18_02)-standard lays it

> Quoting is used to remove the special meaning of certain characters or words to the shell.

It is therefore not problematic to mix different "toggles" in the same string like `'foo'--bar` or `a"b"'c'` (which is equal to `abc`)

Also: this is how python works as well, just that it needs each piece to be a quoted, and allows optional whitespace in between: 

```python3
> python3
>>> a = "a""b"'c'
>>> a
'abc'
```

**Comment by boxed** [comment]
Yea, @henrikhorluck you got it.

The way it works in C and Python is a huge foot gun and even hurts professionals who have used those languages for decades. 

Plus, as you say, it's an implicit append in those cases. What I'm talking is not that.

**Comment by henrikhorluck** [comment]
> Plus, as you say, it's an implicit append in those cases. What I'm talking is not that.

I don't think I completely understand what you find surprising in `foo 'bar'bar` being interpreted as `foo barbar`, there is nothing problematic syntax-wise?

> You have a start quote, and then it's thrown away at the end

That would be the case if `'barbar` was interpreted as `barbar`, but it is not, that is actually a syntax-error (fish even points to where!):

```shell
> fish -c "python3 test.py 'barbar"
fish: Unexpected end of string, quotes are not balanced
python3 test.py 'barbar
                ^
```

In the case of `'bar'bar`, the quotes are properly used as delimiting the quoting so `'$(echo a)'bar` is interpreted as `$(echo a)bar` and not `abar` which is how `$(echo a)bar` ends up (due to command-substitution)

**Comment by boxed** [comment]
hmm.. yea ok, I see where my confusion lies. I think of ' and " not as toggling an escaping mode, but as start/end delimiters for strings. 

Well... I'll just have to settle for "I think this is enormously mistaken" and accept that it can't be changed due to compatibility requirements with POSIX :/

**Comment by henrikhorluck** [comment]
> Well... I'll just have to settle for "I think this is enormously mistaken" and accept that it can't be changed due to compatibility requirements with POSIX :/

Fish is not POSIX-compatible, unless it doesn't hurt, see the [Design document](https://fishshell.com/docs/current/design.html#design). This can rather be a useful feature, as otherwise to write arguments that intermix quote-style would need `$(string join "" "mode1" 'mode2' mode3)` which is quite a bit more tedious.

**Comment by boxed** [comment]
Ah.. well then I'll go back to arguing for my case then! I don't think mixing like this makes sense. It's error prone. `foo "bar" baz` makes sense but `foo b"a"r baz` being the same thing to me does not. Nor does it make sense that `p""thon3` starts python3 I think. 

To me, it makes sense that each token is either a raw string or a quoted string. But treating everything as one long string with quote characters toggling escape mode seems unintuitive at best.

**Comment by Xiretza** [comment]
I'm quite certain that's not changing now, and it actually is useful behaviour, e.g. to specify a wildcard together with a path containing spaces (`"path with spaces"/*`).
