### ISSUE TITLE
fish: Unknown command: $default function

### ISSUE THREAD

**Issue by learnercys** [fish-shell/fish-shell#9967]
fish, version 3.6.1
MacOs Intel

I had previously installed `oh my zsh` and decided to uninstall it, once I did that I installed fish with brew.

I can't use any default function like `fish_config`, every try shows the next error:

```
fish: Unknown command: fish_config
```

**Comment by faho** [comment]
The issue template asks you to run fish without configuration. Have you tried that?

What does `set -S fish_function_path` say?

What does your ~/.config/fish/config.fish contain?

**Comment by learnercys** [comment]
First command is showing nothing and config.fish is also empty.

Not sure if this helps but I have brew in a different folder from where is usually located(I have done this in another computer before and works correctly). I also noticed that some default fish env variables like `__fish_data_dir`, `__fish_help_dir` and `__fish_sysconf_dir` does not have the correct directories(because of brew's location), I'm not sure how to change this values?

**Comment by faho** [comment]
> First command is showing nothing

Well, there's your problem.

Fish finds functions (like `fish_config`) by looking at the directories in $fish_function_path.

This file is set by default. If it isn't set for you, you either have some extremely broken configuration or a quite broken install.

> I also noticed that some default fish env variables like __fish_data_dir, __fish_help_dir and __fish_sysconf_dir does not have the correct directories

What's "correct" here depends on how your system is set up. E.g. $__fish_sysconf_dir would typically be /etc, but I'm fairly sure some systems use /usr/local/etc.

$__fish_data_dir should contain one element, and that should be a directory with a `config.fish` file and a `functions` directory. If that's not the case either something changed it after startup or your install is broken.

I would suggest trying a reinstall. Unfortunately I can't help with brew issues, and I'm not sure where to best ask for help for it.

**Comment by faho** [comment]
Alright, your installation is broken, there's not a lot for us here to do, closing!
