### ISSUE TITLE
pressing the tab button leads to tracing

### ISSUE THREAD

**Issue by saber716rus** [fish-shell/fish-shell#9969]
here is the actual trace:
saber716rus@saber716rus-BOM-WXX9 ~> sudo nala inTraceback (most recent call last):
  File "/usr/bin/nala", line 5, in <module>
    from nala.__main__ import main
  File "/usr/lib/python3/dist-packages/nala/__main__.py", line 30, in <module>
    import nala.fetch as _fetch  # pylint: disable=unused-import
  File "/usr/lib/python3/dist-packages/nala/fetch.py", line 37, in <module>
    import typer
  File "/usr/lib/python3/dist-packages/typer/__init__.py", line 12, in <module>
    from click.termui import get_terminal_size as get_terminal_size
ImportError: cannot import name 'get_terminal_size' from 'click.termui' (/home/saber716rus/.local/lib/python3.10/site-packages/click/termui.py)

[sudo] пароль для saber716rus: 
Попробуйте ещё раз.
[sudo] пароль для saber716rus: 
Попробуйте ещё раз.
[sudo] пароль для saber716rus: 
sudo: 3 попытки ввода неправильного пароля
but by entering this command, the package starts working correctly
saber716rus@saber716rus-BOM-WXX9 ~ [1]> sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
saber716rus@saber716rus-BOM-WXX9 /h/saber716rus> nala search 

fish 3.3.1+ds-3 [Ubuntu/jammy universe]
├── is installed
└── friendly interactive shell

fish-common 3.3.1+ds-3 [Ubuntu/jammy universe]
├── is installed
└── friendly interactive shell (architecture-independent files)

fish-common 3.3.1+ds-3 [Ubuntu/jammy universe]
├── is installed
└── friendly interactive shell (architecture-independent files)

**Comment by saber716rus** [comment]
updated to the current version, but the problem persists.
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
saber716rus@saber716rus-BOM-WXX9 ~> nala sTraceback (most recent call last):
  File "/usr/bin/nala", line 5, in <module>
    from nala.__main__ import main
  File "/usr/lib/python3/dist-packages/nala/__main__.py", line 30, in <module>
    import nala.fetch as _fetch  # pylint: disable=unused-import
  File "/usr/lib/python3/dist-packages/nala/fetch.py", line 37, in <module>
    import typer
  File "/usr/lib/python3/dist-packages/typer/__init__.py", line 12, in <module>
    from click.termui import get_terminal_size as get_terminal_size
ImportError: cannot import name 'get_terminal_size' from 'click.termui' (/home/saber716rus/.local/lib/python3.10/site-packages/click/termui.py)

saber716rus@saber716rus-BOM-WXX9 ~> nala seaTraceback (most recent call last):
  File "/usr/bin/nala", line 5, in <module>
    from nala.__main__ import main
  File "/usr/lib/python3/dist-packages/nala/__main__.py", line 30, in <module>
    import nala.fetch as _fetch  # pylint: disable=unused-import
  File "/usr/lib/python3/dist-packages/nala/fetch.py", line 37, in <module>
    import typer
  File "/usr/lib/python3/dist-packages/typer/__init__.py", line 12, in <module>
    from click.termui import get_terminal_size as get_terminal_size
ImportError: cannot import name 'get_terminal_size' from 'click.termui' (/home/saber716rus/.local/lib/python3.10/site-packages/click/termui.py)

Traceback (most recent call last):
  File "/usr/bin/nala", line 5, in <module>
    from nala.__main__ import main
  File "/usr/lib/python3/dist-packages/nala/__main__.py", line 30, in <module>
    import nala.fetch as _fetch  # pylint: disable=unused-import
  File "/usr/lib/python3/dist-packages/nala/fetch.py", line 37, in <module>
    import typer
  File "/usr/lib/python3/dist-packages/typer/__init__.py", line 12, in <module>
    from click.termui import get_terminal_size as get_terminal_size
ImportError: cannot import name 'get_terminal_size' from 'click.termui' (/home/saber716rus/.local/lib/python3.10/site-packages/click/termui.py)
saber716rus@saber716rus-BOM-WXX9 ~ [1]> fish --version
fish, version 3.6.1
saber716rus@saber716rus-BOM-WXX9 ~> echo $version
3.6.1
saber716rus@saber716rus-BOM-WXX9 ~> sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish'
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
saber716rus@saber716rus-BOM-WXX9 /h/saber716rus> nala search sof

**Comment by faho** [comment]
> but by entering this command, the package starts working correctly

Since the problem doesn't occur without configuration, your configuration is at fault.

Have you tried checking it? Is there any customization for the tab key, or of $fish_complete_path?

Do you use any plugins or similar?

It appears something in your config runs `eval` or similar when you try to tab complete.

**Comment by faho** [comment]
It appears this is generating completions via the [typer](https://github.com/tiangolo/typer) library, and that appears to not be set up correctly.

It can't import "get_terminal_size" from "click.termui".

Since it appears you got these packages from your distribution, you'll have to talk to them, they seem to be missing dependencies.

The reason you're seeing this with configuration only is likely because you needed to enable these completions specifically.
