### ISSUE TITLE
Right prompt prints "Permission Denied" errors to fish stderr.

### ISSUE THREAD

**Issue by NiklasBeierl** [fish-shell/fish-shell#9975]
System info

```
> echo $TERM
tmux-256color
> fish --version
fish, version 3.6.1
> uname -a
Linux <HOSTNAME> 6.4.7-arch1-2 #1 SMP PREEMPT_DYNAMIC Mon, 31 Jul 2023 11:41:04 +0000 x86_64 GNU/Linux
```

The default `fish_right_prompt` uses `git rev-parse --git-dir 2>/dev/null` to determine if it is inside a git repository.

That causes git (or at least version  2.41.0) to check all directories that are `.gitignored` for a file called `.gitkeep`.
If this .gitignored folder is not readable for the current user, fish prints: `path/to/ignored_dir/.gitkeep: Permission denied` to **its own stderr**.  Since `fish_right_prompt` gets run anytime I run any command, I get this error anytime I do anything in an affected git repository. This does not occur when running the `git rev-parse` command in bash.
```
A ~ echo $0
-bash
A ~ cd code/swag/swager/
A ~/code/swag/swager (main) git rev-parse --git-dir
.git
A ~/code/swag/swager (main) fish
docker/volumes/postgres/.gitkeep: Permission denied
A ~/c/s/swager git rev-parse --git-dir                                    main ⬆ ✖ ✱ ◼
.git
docker/volumes/postgres/.gitkeep: Permission denied
A ~/c/s/swager cd ..                                                      main ⬆ ✖ ✱ ◼
A ~/c/swag cd
A ~ cd code/swag/swager/
docker/volumes/postgres/.gitkeep: Permission denied
A ~/c/s/swager cd docker/                                                 main ⬆ ✖ ✱ ◼
docker/volumes/postgres/.gitkeep: Permission denied
A ~/c/s/s/docker cd volumes/                                              main ⬆ ✖ ✱ ◼
docker/volumes/postgres/.gitkeep: Permission denied        
```
And it is definitely fish printing this message! If i redirect fish's stderr to /dev/null, I do not get the output:
```
A ~ fish 2>/dev/null
A ~ cd code/swag/swager/
A ~/c/s/swager cd docker/    
```

I am also confident that `fish_right_prompt` is causing the access to the `.gitkeep` files, because disabling it also makes the messages go away:
```
A ~ fish
A ~ cd code/swag/swager/
docker/volumes/postgres/.gitkeep: Permission denied
A ~/c/s/swager cd .                                                       main ⬆ ✖ ✱ ◼
docker/volumes/postgres/.gitkeep: Permission denied
A ~/c/s/swager functions -e fish_right_prompt                             main ⬆ ✖ ✱ ◼
A ~/c/s/swager cd docker
A ~/c/s/s/docker cd ../
A ~/c/s/swager
```

You might be wondering why I have a gitignored directory that my user may not read from: 
It is used as a volume for a docker container running postgres, the container runs with a different uid and sets the permissions of the directory.

**Comment by zanchey** [comment]
> The default `fish_right_prompt` uses `git rev-parse --git-dir 2>/dev/null` to determine if it is inside a git repository.

fish does not ship with a default `fish_right_prompt`. What theme are you using?

**Comment by NiklasBeierl** [comment]
Oh, I see. I admit one of the first things I did was select a color theme via fish_config. 
I can't seem to figure out which one I selected, tho.

**Comment by NiklasBeierl** [comment]
Maybe this helps:
My `~/.config/fish/functions/fish_right_prompt.fish` is a subset of [share/tools/web_config/sample_prompts/scales.fish](https://github.com/fish-shell/fish-shell/blob/81cd0359509621bd8fb11556bdfd65462ede54a9/share/tools/web_config/sample_prompts/scales.fish#L27)

My version of the file is missing the first 23 lines.

**Comment by faho** [comment]
Okay, run this:

```fish
function fish_right_prompt; end
```

That should remove the errors from the prompt.

Now, run this:

```fish
command git status --porcelain
```

That should give you "permission denied" errors - it's the only git call in scales that doesn't have its stderr silenced, and I don't see anything else that would print that error.

The reason for them is that you have git directory above your current directory, that git finds, but it's inaccessible to git. That seems like a weird setup and I would recommend fixing it.

Nevertheless, we can silence that git call as well.

**Comment by NiklasBeierl** [comment]
Thanks for the fix! :heart: Sorry for misattributing the print, guess I need to up my strace game.
