### ISSUE TITLE
math  division error

### ISSUE THREAD

**Issue by asterlinux** [fish-shell/fish-shell#9979]
**fish, version 3.6.1**

when 1 is divided by 0.000000000000001 I get the following 999999999999999.875 but I need to get 1000000000000000 

How to reproduce the problem ->
  math 1/0.000000000000001

**Comment by faho** [comment]
Math uses 64-bit "double" numbers under the hood.

That is an unavoidable rounding error simply due to how those numbers work.

See https://floating-point-gui.de/basic/
