### ISSUE TITLE
math --scale does not emit trailing zeros

### ISSUE THREAD

**Issue by katrinafyi** [fish-shell/fish-shell#9983]
The [manual page](https://fishshell.com/docs/current/cmds/math.html) says math should use a fixed representation when -s is given, but this seems to not be the case.

```bash
$ math -s10 "1.01"
1.01
```

This is with "fish, version 3.6.1".

**Comment by faho** [comment]
What "--scale" does is give you *up to* X digits, still removing trailing zeroes. The default scale is 6 digits.

We should probably just fix the docs to explain that.
