### ISSUE TITLE
Cannot use `command time` in pipeline

### ISSUE THREAD

**Issue by llenck** [fish-shell/fish-shell#9985]
- `fish, version 3.6.1`
- current arch linux (`Linux arch-lia 6.4.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 11 Aug 2023 11:03:36 +0000 x86_64 GNU/Linux`)
- `sh -c 'env HOME=$(mktemp -d) XDG_CONFIG_HOME= fish` makes no difference

When running `command time true`, fish runs `/usr/bin/time`, as I'd expect. However, when running `true | command time true`, I get:
![tmp](https://github.com/fish-shell/fish-shell/assets/43119619/3d1d1f1e-bd90-43f2-afbe-475d947f7447)

I believe this is a bug, as I'd expect fish to run `time` as found in `PATH`.

**Comment by faho** [comment]
Ha, cool.

@zanchey: Pretty trivial to backport because I had to implement this twice - dunno where the rust version of `detect_errors_in_decorated_statement` is used yet, if it is at all.
