### ISSUE TITLE
C++ dependency warnings when running shell commands from Matlab R2023a

### ISSUE THREAD

**Issue by SeSodesa** [fish-shell/fish-shell#9989]
### Required information

**fish version:** 3.6.1  
**OS:** Ubuntu LTS 22.04  
**Terminal:** Matlab R2023a REPL
**Customizations:** Matlab links against its own C++ libraries.

### The problem

Matlab (R2023a) allows running shell commands from its REPL by typing
```matlab
!shell_command [options] args
```
or
```matlab
[exit, msg] = system ( "shell_command [options] args" ) ;
```
However, when I do this with the setup listed above, I get the following 3 warnings:
```sh
/usr/bin/fish: /usr/local/MATLAB/R2023a/sys/os/glnx64/libstdc++.so.6: version `CXXABI_1.3.13' not found (required by /usr/bin/fish)
/usr/bin/fish: /usr/local/MATLAB/R2023a/sys/os/glnx64/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/bin/fish)
/usr/bin/fish: /usr/local/MATLAB/R2023a/sys/os/glnx64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/bin/fish)
```
As the warning says, the version of the C++ standard library shipped with Matlab seems to be missing the versions that fish requires, which can be confirmed by running the following command on the symbolic link `libstdc++.so.6` in the Matlab installation folder:
```sh
strings /usr/local/MATLAB/R2023a/sys/os/glnxa64/libstdc++.so.6 | grep LIBCXX
strings /usr/local/MATLAB/R2023a/sys/os/glnxa64/libstdc++.so.6 | grep CXXABI
```
Their respective outputs are
```text
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
```
and
```text
CXXABI_1.3
CXXABI_1.3.1
CXXABI_1.3.2
CXXABI_1.3.3
CXXABI_1.3.4
CXXABI_1.3.5
CXXABI_1.3.6
CXXABI_1.3.7
CXXABI_1.3.8
CXXABI_1.3.9
CXXABI_1.3.10
CXXABI_1.3.11
CXXABI_1.3.12
```
Now, this does not seem to have absolutely broken anything substantial, but it seems to be worth mentioning.

The obvious fix is for MathWorks to update the libraries they provide, but I wonder what the right action would be if one wanted to fix this temporarily. Change the symbolic link in the Matlab installation folder to point to a system-wide version of `libstdc++.so.6`, in case it also provides newer versions, and see if Matlab can still be started?

**Comment by faho** [comment]
You're better off asking the Matlab people, they're gonna have a better idea of how that environment works.
