### ISSUE TITLE
Ctrl-/ binding `bind -M normal -m insert \c_ history-pager repaint-mode` doesn't open pager in normal mode.

### ISSUE THREAD

**Issue by MIvanchev** [fish-shell/fish-shell#9993]
Ver: 3.6.1

An insert mode binding `bind -M insert \c_ history-pager` works fine.

**Comment by faho** [comment]
"normal" mode is called "default" in fish.

**Comment by MIvanchev** [comment]
@faho Thanks :) works beautifully!

**Comment by MIvanchev** [comment]
Bind could output an error for an illegal mode though.

**Comment by faho** [comment]
> Bind could output an error for an illegal mode though.

It's not "illegal". Modes are created simply by being bound.

You did correctly bind this in "normal" mode - only nothing invoked "normal" mode so you could never use it.

**Comment by MIvanchev** [comment]
You are right, I kinda misunderstood the whole concept of modes. Thanks.
