### ISSUE TITLE
Variables for single command doesn't work with `exec`

### ISSUE THREAD

**Issue by Harazi** [fish-shell/fish-shell#9995]
`fish --version`
```
fish, version 3.6.1
```

`uname -a`
```
Linux R3UB 6.4.12-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 24 Aug 2023 00:38:14 +0000 x86_64 GNU/Linux
```

`echo $TERM`
```
tmux-256color
```

Overriding variables for a single command using `var=val` syntax doesn't work when the command to be executed is `exec`.

![image](https://github.com/fish-shell/fish-shell/assets/66067027/48dfe1f6-3d35-4c46-8ef3-b92bafa93de4)

**Comment by ridiculousfish** [comment]
Good find, this should be fixed.
