### ISSUE TITLE
What is (proton-style) in prompt

### ISSUE THREAD

**Issue by heddxh** [fish-shell/fish-shell#9996]
fish version 3.6.1 on Arch Linux, Konsole.

I don't change any fish config and when I cd to a directory and delete it in my file explore(Dolphin), I got this: `heddxh@myArchLinux ~/.qt (proton-style)>` .

![Screenshot_20230831_130835](https://github.com/fish-shell/fish-shell/assets/63106571/68a525ae-40e8-4ec0-8f24-e54be10907f6)

**Comment by faho** [comment]
In that place it would typically be the git branch. Run `fish_git_prompt`, which should give you the same output.

If not, something changed your prompt and e.g. added a python venv display (python's venv activation script does this).

**Comment by heddxh** [comment]
Thanks for the response.
It is either in a git repo nor a python env. This directory have only one file `.qtrc`.
And  it only happed when I deleted the `.qt` directory.

I try to reproduce but I can't. Maybe it is a konsole bug(incorrectly reporting git repositories info in other locations to the shell)

**Comment by faho** [comment]
> Maybe it is a konsole bug

The terminal has nothing to do with this. It's not really at the level where the terminal would influence things.

>It is either in a git repo nor a python env

Note: A python venv is typically displayed just by printint the $VIRTUAL_ENV environment variable.

And a git repository is any directory that has a valid ".git" directory *somewhere above it*.

So just checking the directory itself isn't enough to see that it is or isn't a venv/git repo.

>I try to reproduce but I can't.

In that case, I'm closing the issue.

If you do happen to see it again, you'll want to run `fish_git_prompt` to see if it's a git branch, `echo $VIRTUAL_ENV` to see if it's a virtual environment, and if it is neither check `type fish_prompt` for your prompt's definition for what else it could be.
